### ISSUE TITLE
Better error messages when invoking deprecated modules

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1003]
Give some automatic assistance when invoking modules with deprecated names.

**Comment by gregw** [comment]
@WalkerWatch can you test this.  Known deprecated modules are:
```
gcloud-memcached-sessions : replaced by 'session-store-cache,session-store-gcloud'
gcloud-session-idmgr : no longer required.
gcloud-sessions : replaced by 'session-store-gcloud'
infinispan : replaced by either 'session-store-infinispan-embedded' or 'session-store-infinispan-remote'
jdbc-sessions : replaced by 'session-store-jdbc'
logging : renamed to 'stderrout-capture'
monitor : no longer supported
nosql : replaced by 'session-store-mongo'
```

**Comment by WalkerWatch** [comment]
@gregw LGTM

**Comment by sbordet** [comment]
Trying 9.4.0.RC1, I get:

```
14:59:12 simon@opal:~/tmp/jetty.base$ java -jar ../jetty-distribution-9.4.0.RC1/start.jar --add-to-start=resources,logging,requestlog,server,proxy-protocol,http,http2c,deploy,rewrite,fcgi,servlets
WARN : Deprecated module 'logging' is renamed to 'stderrout-capture'
WARN : Unknown module='logging. List available with --list-modules
```

Okay that module `logging` is deprecated, but the next line says it's unknown, which is very confusing (and the line formatting is wrong - missing a closing single quote).

Why is the second warning line appearing at all ?

**Comment by WalkerWatch** [comment]
@sbordet 

I can understand the second line. Regardless of the initial warning, the module does not exist. That said, I can understand how it may be a bit redundant. As for the latter, I tested this in 9.3. and seems to be something that may have been around for a while - if a module does not exist and there is an error like above, nothing is added.

**Comment by sbordet** [comment]
@WalkerWatch 

This is going to be the number one issue that users will face. I myself got totally confused and could not progress in updating my test jetty.base, let alone our websites, because I had no idea what to do.

**Comment by joakime** [comment]
This seems completed
