### ISSUE TITLE
Pattern for javax classes should be precompiled in ReflectUtils

### ISSUE THREAD

**Issue by dreis2211** [eclipse/jetty.project#1004]
Hey,

I just noticed a small possible improvement in ReflectUtils by precompiling the pattern in order to check for javax classes instead of compiling the pattern on every check.

Cheers,
Christoph

**Comment by gregw** [comment]
thanks

**Comment by joakime** [comment]
Just reopening to make sure this gets backported to 9.3.x (at least) ...

**Comment by dreis2211** [comment]
Cool. Thanks!

**Comment by joakime** [comment]
Not going to backport. closing.

**Comment by dreis2211** [comment]
@joakime May I ask what changed your mind?

**Comment by jmcc0nn3ll** [comment]
9.3 is a dead end, likely only getting security releases or support updates from here on out
