### ISSUE TITLE
2023-07-04 11:39:30.493:WARN:oejs.HttpChannel:qtp101775274-153: handleException /monitor/allre.jsp org.eclipse.jetty.http.BadMessageException: 500: Bad query encoding

### ISSUE THREAD

**Issue by haha132** [eclipse/jetty.project#10059]
**Jetty version**
Jetty 9.4.48.v20220622
**Java version**
openjdk 1.8
**Question**
2023-07-04 11:39:30.493:WARN:oejs.HttpChannel:qtp101775274-153: handleException /monitor/allre.jsp org.eclipse.jetty.http.BadMessageException: 500: Bad query encoding

How to solve ?

**Comment by lachlan-roberts** [comment]
Can you provide more info? what query string is being used.
Are you doing any servlet dispatches?

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

If this is still a problem on Jetty 10 (or newer), let us know and we'll reopen this issue for those versions of Jetty.
