### ISSUE TITLE
Should getParts() in Request only allow content type multipart/form-data or should it also permit multipart/mixed

### ISSUE THREAD

**Issue by LukeButtersFunnelback** [eclipse/jetty.project#1006]
Hi
I noticed under jetty multipart requests only seem to work with content type "multipart/form-data", yet under tomcat it seems to allow "multipart/mixed". I started using this content type as I saw it in a spring example (http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-multipart-forms-non-browsers) however this will not work under jetty as https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2288 checks the content sub type is form-data.
* Is jetty incorrect to enforce the content type `multipart/form-data`? Should it do what the apache library did which was confirm the content type started with `multipart/`?
* Within that code the match is an exact match, does this mean the Content-Type can not have any parameters? 
* If jetty is correct I guess I should raise a bug against the spring doco and apache commons fileupload.

**Comment by sbordet** [comment]
References: 
`multipart/form-data`: https://tools.ietf.org/html/rfc7578, obsoleting 2388.
`multipart/mixed`: https://tools.ietf.org/html/rfc2046

IMHO, `multipart/mixed` was historically used for emails, where text and attachments could be sent together.
OTOH, `multipart/form-data` is more appropriate for HTML form submission, which is _the_ case when talking to HTTP servers.

**Comment by LukeButtersFunnelback** [comment]
I guess in my case I have a multi part request which isn't likely to be used in  HTML form submission, so maybe mixed makes more sense. It doesn't bother me to much as I doubt I understand the standards well enough to make a good argument.

I guess enforcing `multipart/form-data` results in someone (other than me) who needs to use a different subtype wont be able to use jetty. I think it is best for you/other jetty guys, to decide if jetty should allow other subtypes or not.

**Comment by sbordet** [comment]
@gregw any opinion on this ? Does the servlet spec mandate something in particular ?

**Comment by janbartel** [comment]
The servlet spec specifically discusses file upload with "multipart/form-data":

3.2 File upload
Servlet container allows files to be uploaded when data is sent as multipart/form-
data .
The servlet container provides multipart/form-data processing if any one of the
following conditions is met.

- The servlet handling the request is annotated with the "@MultipartConfig" as
defined in Section 8.1.5, “@MultipartConfig” on page 8-70.
- Deployment descriptors contain a multipart-config element for the servlet handling the request.

How data in a request of type multipart/form-data is made available depends on
whether the servlet container provides multipart/form-data processing:
- If the servlet container provides multipart/form-data processing, the data is
made available through the following methods in HttpServletRequest :
 - public Collection<Part> getParts()
 - public Part getPart(String name)
Each part provides access to the headers, content type related with it and the content via the Part.getInputStream method. For parts with form-data as the Content-Disposition , but without a filename, the string value of the part will also be available through the getParameter and getParameterValues methods on HttpServletRequest , using the name of the part.
 - If the servlet container does not provide the multi-part/form-data processing the data will be available through the HttpServletRequest.getInputStream.

**Comment by sbordet** [comment]
`multipart/mixed` does not mandate the presence of the `Content-Disposition` header, which is required in case of `multipart/form-data`.

I think the Spring example is incorrect: the `Content-Type: multipart/mixed` lacks the mandatory parameter `boundary`. Furthermore, the example can perfectly have `Content-Type: multipart/form-data` and be legal.

In summary, we would need to relax the checks for the presence of certain headers such as `Content-Disposition` header when parsing `multipart/mixed`; if a `multipart-mixed` request is sent without `Content-Disposition` header, I am guessing it will break existing applications that typically expect this header and its parameters; the Spring example reported is actually better implemented as `multipart/form-data`, for which there is _guaranteed_ support by the Servlet API (while there is no guarantee of support for `multipart/mixed` by the Servlet API).

I guess Jetty _could_ support `multipart/mixed`, but I think would be best for the client to stick with `multipart/form-data`: it will have larger and guaranteed support by every Servlet container.

**Comment by janbartel** [comment]
As jetty is implementing the spec correctly I am going to close this issue for now. I can't see the jetty project pursuing an implementation of multipart/mixed, but we would be happy to evaluate a pull request for an optional feature.

**Comment by LukeButtersFunnelback** [comment]
Reading the comments I think jetty is doing the correct thing and I am happy to use `form-data`. Thank you all for looking into this :)

**Comment by AnkBurov** [comment]
SOAP uses Multipart/Related content type and Jetty generates tons of warnings because of getParts() check - contentType is multipart/related and not multipart/form-data.
