### ISSUE TITLE
Jetty 12: instantiation of `HashLoginService`

### ISSUE THREAD

**Issue by zUniQueX** [eclipse/jetty.project#10068]
**Jetty version(s)**
12.0.0.beta2

**Description**
Hey Jetty team. The beta versions of Jetty 12 work well so far. However, while trying to upgrade from 11, I've experienced a problem with instantiation in a Maven integration test.

When using the Maven plugin for Jetty 11, the `config` property of the `HashLoginService` was a String and could be set via the Maven configuration directly as described in the docs. In Jetty 12 the config is now an instance of `Resource`. Since no implementation of `Resource` provides a no-arg constructor, the existing implementations cannot be used in the Maven configuration.

Maybe we could add a utility module with classes supporting Maven configurations to solve the instantiation problem without changing the current resource semantics.

**Comment by gregw** [comment]
In our XML configuration we can create `Resource` instance with something like:
```java
    <Call id="ResourceFactory" class="org.eclipse.jetty.util.resource.ResourceFactory" name="of">
       <Arg><Ref refid="Server" /></Arg>
       <Call id="realmResource" name="newResource"
         <Arg><Property name="login.realm" default="src/test/resources/realm.properties"/></Arg>
       </Call>
    </Call>
```

But I'm guessing that maven cannot do something like that?  @janbartel does maven have any other way to create instances to pass to methods that we can support via some static API?

**Comment by janbartel** [comment]
@zUniQueX yes, `Resource` was completely reworked in jetty-12 and the interfaces of a lot of classes that used resources internally. 

Pondering what we could do about this. Ideally in any solution we would tie the `ResourceFactory` to the `Server` instance, however at the time of plugin configuration, the `Server` instance does not exist. We might be able to do something with a `URLResourceFactory` instead.

Anyway, while we ponder this, I just wanted to bring to your attention that it has always been possible to define a `jetty.xml` file in which you can configure the `Server` or any container-level jetty object, including a `HashLogin` service. That would allow you to call the new `Resource` code as per Greg's snippet posted above for jetty-12 (you could also convert your plugin configurations of older versions of jetty to do the same thing).  Or if this is a context-specific object, you can define a `context.xml` file instead.

**Comment by janbartel** [comment]
@zUniQueX I think PR #10077 should address your concerns.  

You would use it like this:

``` xml
          <configuration>
              <loginServices>
                  <loginService implementation="org.eclipse.jetty.security.HashLoginService">
                      <config implementation="org.eclipse.jetty.ee10.maven.plugin.MavenResource">
                          <resourceAsString>${basedir}/src/config/login.xml</resourceAsString>
                      </config>
                  </loginService>
              </loginServices>
          </configuration>
```

**Comment by zUniQueX** [comment]
Looks very good. Thanks for the fast implementation :+1:

**Comment by normana400** [comment]
can anyone on this thread offer an example on how to setup a HashLoginService using jetty.xml? On earlier versions of jetty you could configure it in the webapp.xml and ee9 (org.eclipse.jetty.ee9.webapp.WebAppContext) doesn't appear to have a way to update the securityHandler. Also the HashLoginService contructor requires a Resource and there no example online on how to construct a resource via the Jetty xml (ie do I need to obtain a resource factory to get a resource or is there a way I can just construct a resource from a string?

**Comment by janbartel** [comment]
@normana400 have you seen the examples in the jetty demos? It's here: https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-home/src/main/resources/modules/demo.d/jetty-demo-realm.xml

**Comment by ThrawnCA** [comment]
> [@zUniQueX](https://github.com/zUniQueX) I think PR [#10077](https://github.com/jetty/jetty.project/pull/10077) should address your concerns.

That PR has ee10 and ee9 versions, but not ee8?

**Comment by lachlan-roberts** [comment]
@ThrawnCA the EE8 code is generated from the EE9 code.
