### ISSUE TITLE
Improve Jetty-12 EE10 DefaultServlet

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#10063]
**Jetty version(s)**
12

**Enhancement Description**

Several key optimisations have been lost in the process or developing the ee10 DefaultServlet.  Other optimisations are now available with the new handler architecture.  Identified issues include:
 
 + The servlet API request/response are always wrapped as `ServletCoreRequest`/`ServletCoreRequest`, even if the passed servlet request/response instances are not themselves wrapped, so the original core requests are still available.
 + Serving of the static content is always done by a blocking invocation of the `ResourceService`, even if there are no filters before the default servlet, so an asynchronous serving of the content would be possible.

We need to review the `DefaultServlet` and make sure that it is both correct and optimal.

**Comment by gregw** [comment]
Currently the `DefaultServlet` contains a `ResourceService` and always adapts the servlet request/response back to being core request/responses and invokes the nested servlet.  For the sake of simplicity, this path has not been optimised for the common case of now request/response wrappers

I'd like to propose the following architecture change:
 + We keep the DefaultServlet as the non-optimized path that can deal with servlet request/response wrapping.  This keeps the handling simple.
 + Instead of the ResourceService being held by the DefaultServlet, it is instead held by a `ServletResourceHandler`, which would be the next handler in the chain (i.e. ServletContenxtHandler->SessionHandler->SecurityHandler->ServletHandler->ServletResourceHandler)
 + The ServletHandler would be modified to know about the our `DefaultServlet` implementation, and if a request arrives that is mapped directly to it, rather than invoking the servlet mechanisms (or all the servlet mechanisms), it lets the core request/response that it receives pass through to the next handler (i.e. the `ServletResourceHandler`), which can handle it efficiently as an asynchronous core request.
 + If the DefaultServlet is invoked, it can assume a non trivial invocation, so it will always wrap the request/response and invoke the `ServletResourceHandler` in blocking style (i.e. much the same as what we do now).
 + The `ServletResourceHandler` would be pretty much the standard `ResourceHandler`, but with servlet specific welcome file logic applied.

**Comment by gregw** [comment]
@lorban I have allocated this issue to you, as I'd like you to take the lead in all things static content.... but I @lachlan-roberts wrote much of the current `DefaultServlet` and @joakime also contributed, so feel free to delegate work to them as you see fit.

**Comment by lorban** [comment]
Reminder from https://github.com/eclipse/jetty.project/issues/10330: consider adding a `Content.Source newContentSource()` method to `Resource` as that would help avoid using and duplicating the following pattern when serving resources:

```java
if (resource.getPath() != null)
  // use NIO with Path: async and no unnecessary buffer copies
else
  // fallback to InputStream: blocking and requires extra buffer copies
```

**Comment by lorban** [comment]
Superseded by #10738, #10739 and #10741
