### ISSUE TITLE
Allow custom transport for HttpClient

### ISSUE THREAD

**Issue by marchof** [eclipse/jetty.project#10080]
**Jetty version(s)**
12+

**Enhancement Description**
Allow to configure HttpClient to use a local Java API for data (bytes) transport without envolving any TCP or unix domain sockets.

This would allow to use a custom transport for different use cases:

* Testing
* Using other means of data transports (e.g. ssh tunnel).

I came across this use case while implementing a pure Java reverse proxy which uses ssh tunnels for the upstream connections. As discussed with @sbordet at JCrete I filed this enhancement request.

**Comment by gregw** [comment]
yeah yeah, let's all pretend that JCrete is actually about java and not just sipping beers by the pool!

We should be able to feed such a transport directly into the servers LocalConnector.

**Comment by marchof** [comment]
> We should be able to feed such a transport directly into the servers LocalConnector.

By "we" you think of library users or maintainers? Also at least my use case is about the `HttpClient`.

😎 (heading back to the beach)

**Comment by sbordet** [comment]
Closing this issue as it will be fixed by the work being done for #8979.

**Comment by sbordet** [comment]
@marchof can you please try #11368 and see if it works for your use case?
We have tests, but would be great if you can confirm it works for you. Thanks!
