### ISSUE TITLE
Deprecated methods in org.eclipse.jetty.util.Pool

### ISSUE THREAD

**Issue by SwatiJainGoyal** [eclipse/jetty.project#10088]
**Jetty version 10.0.15**

**Java version 17.x**

**Question**
org.eclipse.jetty.util.Pool.getMaxMultiplex()
org.eclipse.jetty.util.Pool.getMaxUsageCount()
org.eclipse.jetty.util.Pool.setMaxUsageCount(int maxUsageCount)
org.eclipse.jetty.util.Pool.setMaxMultiplex(int maxMultiplex)

These methods have been marked deprecated. 
Q1) When will these be removed from Jetty?
Q2) Is there any alternative way to implement same functionality?
Q3) Is there any way to set max streams per connection?

**Comment by lorban** [comment]
Hi,

> Q1) When will these be removed from Jetty?

In 12.0.0. `org.eclipse.jetty.util.Pool` was changed from a class to an interface and its API was simplified, [as you can see in the latest 12.0.0.beta3](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/util/Pool.html).

> Q2) Is there any alternative way to implement same functionality?

That is now dependent on the `Pool` implementation. The `ConcurrentPool` implementation for instance [takes a lambda as a constructor parameter](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/util/ConcurrentPool.html#%3Cinit%3E(org.eclipse.jetty.util.ConcurrentPool.StrategyType,int,boolean,java.util.function.ToIntFunction)) to figure out the max multiplexing value.

> Q3) Is there any way to set max streams per connection?

By calling [AbstractHTTP2ServerConnectionFactory.setMaxConcurrentStreams(int maxConcurrentStreams)](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.html#setMaxConcurrentStreams(int)). Here's a example of how to do it:

```java
int maxConcurrentStreams = 5;

HTTP2ServerConnectionFactory http2 = new HTTP2ServerConnectionFactory(new HttpConfiguration());
http2.setMaxConcurrentStreams(maxConcurrentStreams);
Server server = new Server();
Connector connector = new ServerConnector(server, 1, 1, connectionFactories);
server.addConnector(connector);
server.start();
```
