### ISSUE TITLE
[9.3.x] ThreadLimitHandler has no method setBlockForMs

### ISSUE THREAD

**Issue by message** [eclipse/jetty.project#1009]
```
java.lang.NoSuchMethodException: class org.eclipse.jetty.server.handler.ThreadLimitHandler.setBlockForMs(class java.lang.String)
```
https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/config/etc/jetty-threadlimit.xml#L14

**Comment by joakime** [comment]
Looks like something is off.

The ThreadLimitHandler was added as part of Issue #844 (28ca70378e90226b699d52aed5db693981d6340c), but I can find no mention of the `setBlockForMs` in its history.

@gregw is this a mistake and should be removed from the XML/mod/ini ?  or is it missing functionality that needs to be added to `ThreadLimitHandler`?

**Comment by gregw** [comment]
Oops that was a late removal from the API during review... obviously module was not tested afterwards!
