### ISSUE TITLE
NCSARequestLog frequently fails to rollover daily

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#101]
migrated from Bugzilla [#387302](https://bugs.eclipse.org/bugs/show_bug.cgi?id=387302)
status ASSIGNED severity _major_ in component _server_ for _9.0.x_
Reported in version _7.5.4_ on platform _PC_
Assigned to: Project Inbox

On 2012-08-15 12:53:41 -0400, Robert Kuhar wrote:

> My jetty.xml is configured to produce the Jetty NCSARequestLog like...
> 
> ```
> 
> <Ref id="AccessLog">
>   <Set name="requestLog">
>     <New id="RequestLogImpl" class="org.eclipse.jetty.server.NCSARequestLog">
>       <Arg><SystemProperty name="jetty.logs" default="/data/logs"/>/dm-app1_access.yyyy_mm_dd.log</Arg>
>       <Set name="filenameDateFormat">yyyyMMdd</Set>
>       <Set name="retainDays">3</Set>
>       <Set name="append">true</Set>
>       <Set name="extended">false</Set>
>       <Set name="logLatency">true</Set>
>       <Set name="LogTimeZone">GMT</Set>
>     </New>
>   </Set>
> </Ref>
> ```
> 
> In production what we are observing is that the log file frequently fails to rollover to the new day.  This results in some logfiles containing 2 or more days worth of request log entries.  The effect of this is that our aggregate reporting is having difficulty integrating with Jetty.
> 
> Note below how the head and tail of dm-app1_access.20120810.log and dm-app1_access.20120813.log is just 24 hours apart BUT dm-app1_access.20120811.log is 48 hours and dm-app1_access.20120814.log (current) includes more than just one day.
> 
> Whats up with that?
> 
> [rkuhar@dm-app1 ~]$ ls -l /data/logs/dm-app1_access.2012*log
> -rw-r--r-- 1 jetty jetty  91506402 Aug 10 23:53 /data/logs/dm-app1_access.20120810.log
> -rw-r--r-- 1 jetty jetty 179615954 Aug 12 23:53 /data/logs/dm-app1_access.20120811.log
> -rw-r--r-- 1 jetty jetty  88965122 Aug 13 23:53 /data/logs/dm-app1_access.20120813.log
> -rw-r--r-- 1 jetty jetty 155233912 Aug 15 16:29 /data/logs/dm-app1_access.20120814.log
> 
> [rkuhar@dm-app1 ~]$ head -n 2 /data/logs/dm-app1_access.20120810.log
> 10.23.138.134 -  -  [10/Aug/2012:00:00:17 +0000] "GET /devices/HT25AW303448/config?names=stores HTTP/1.1" 200 139  4
> 10.23.138.136 -  -  [10/Aug/2012:00:00:17 +0000] "GET /devices/HT15TT509480/profile HTTP/1.1" 200 166  2
> [rkuhar@dm-app1 ~]$ tail -n 2 /data/logs/dm-app1_access.20120810.log
> 10.23.138.134 -  -  [11/Aug/2012:00:00:16 +0000] "GET /devices/SH254W107502/profile HTTP/1.1" 200 165  1
> 10.23.138.136 -  -  [11/Aug/2012:00:00:16 +0000] "GET /devices/SH23SVP01744/profile HTTP/1.1" 200 165  1
> [rkuhar@dm-app1 ~]$ head -n 2 /data/logs/dm-app1_access.20120811.log
> 10.23.138.136 -  -  [11/Aug/2012:00:00:17 +0000] "GET /devices/HT16PHX10599/profile HTTP/1.1" 200 165  2
> 10.23.138.133 -  -  [11/Aug/2012:00:00:17 +0000] "GET /admin/hb " 200 137  2
> [rkuhar@dm-app1 ~]$ tail -n 2 /data/logs/dm-app1_access.20120811.log
> 10.23.138.136 -  -  [13/Aug/2012:00:00:16 +0000] "GET /devices/SH24SVP00694/profile HTTP/1.1" 200 165  1
> 10.23.138.134 -  -  [13/Aug/2012:00:00:16 +0000] "GET /devices/HT23MW407650/profile HTTP/1.1" 200 165  1
> [rkuhar@dm-app1 ~]$ head -n 2 /data/logs/dm-app1_access.20120813.log
> 10.23.138.134 -  -  [13/Aug/2012:00:00:17 +0000] "GET /devices/HT26JS405035/profile HTTP/1.1" 200 165  2
> 10.23.138.133 -  -  [13/Aug/2012:00:00:18 +0000] "GET /admin/hb " 200 137  1
> [rkuhar@dm-app1 ~]$ tail -n 2 /data/logs/dm-app1_access.20120813.log
> 10.23.138.135 -  -  [14/Aug/2012:00:00:17 +0000] "GET /devices/HT24GW408085/config?names=stores HTTP/1.1" 200 139  1
> 10.23.138.135 -  -  [14/Aug/2012:00:00:17 +0000] "GET /devices/HC27MMG18780/config?names=stores HTTP/1.1" 200 139  2
> [rkuhar@dm-app1 ~]$ head -n 2 /data/logs/dm-app1_access.20120814.log
> 10.23.138.135 -  -  [14/Aug/2012:00:00:17 +0000] "GET /devices/HT1ATVJ13049/config?names=stores HTTP/1.1" 200 139  2
> 10.23.138.135 -  -  [14/Aug/2012:00:00:17 +0000] "GET /devices/HT278S408000/config?names=stores HTTP/1.1" 200 139  2
> [rkuhar@dm-app1 ~]$ tail -n 2 /data/logs/dm-app1_access.20120814.log
> 10.23.138.134 -  -  [15/Aug/2012:16:46:58 +0000] "PUT /devices/HC1CPMA00945/profile HTTP/1.1" 204 0  1
> 10.23.138.134 -  -  [15/Aug/2012:16:46:58 +0000] "GET /devices/12B9WQ2B0073270/profile HTTP/1.1" 200 166  2
> 
> While you are at it, the rollover itself always seems to be 16 or 17 seconds beyond the hour.  It would be nice if this occurred within a second of midnight.

On 2012-08-15 14:47:02 -0400, Joakim Erdfelt wrote:

> NCSARequestLog uses our RolloverFileOutputStream to manage rollover.
> Our RolloverFileOutputStream uses java.util.Timer and java.util.TimerTask to perform the nightly (at midnight) rollover of the file.
> 
> http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java#n162
> 
> If this is not accurate enough for you, I would recommend using a more robust logging framework such as slf4j + logback + logback-access with its replacement access logging framework for jetty.
> 
> http://logback.qos.ch/access.html
> 
> We've prepared an example project that integrates slf4j + logback + logback-access at https://github.com/jetty-project/jetty-and-logback-example

On 2012-08-16 18:34:42 -0400, Greg Wilkins wrote:

> Rollover is an ancient class.... probably needs a good makeover. Coming soon.

**Comment by joakime** [comment]
Work done in many other recent issues.
