### ISSUE TITLE
Code of Conduct file required by Eclipse

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#10107]
**Jetty version(s)**
9, 10, 11, 12

**Description**

Going through the progress review (release review replacement) they noticed we are missing a Code of Conduct file.

- https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/537

You can see the required repo files here and our compliance.

- https://www.eclipse.org/projects/tools/documentation.php?id=rt.jetty

We can drop the following file directly into the 9, 10, 11, 12 repos and be in compliance for the jetty.project repo

- https://raw.githubusercontent.com/eclipse/.github/master/CODE_OF_CONDUCT.md

**Comment by joakime** [comment]
@jmcc0nn3ll are you going to submit the PRs? 

For `jetty-9.4.x` and `jetty-10.0.x` at least? those should merge forward to Jetty 12.

**Comment by jmcc0nn3ll** [comment]
@joakime I will if I get a chance later today, you can knock it out if you like.
