### ISSUE TITLE
Refactor getResource() usages

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1011]
See [JEP 220](http://openjdk.java.net/jeps/220).

We should verify all the code that does `Class.getResource()` and `ClassLoader.getResource()`, both usages and implementations in `WebAppClassLoader` (and possibly OSGi) will work fine in JDK 9 too.

Perhaps the best way is to refactor those usages in a utility class, so that we will have a single point where we sniff whether it's JDK 9 or not, and call appropriate APIs, if needed.

**Comment by joakime** [comment]
I think the work done in Issues #1490, #1489, #1498, and #1499 address this, no?
