### ISSUE TITLE
How to duplicate Request?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10119]
Given https://github.com/eclipse/jetty.project/issues/10105, is there a built-in mechanism to duplicate an existing Request so that it can be reused?

`HttpClient.copyRequest(HttpRequest, URI)` looks great but it is a protected method.

**Comment by sbordet** [comment]
No, there is no way.

Applications typically handle this, they build the request and if they need some common code to build them, that code could be factored into an application method.

Do you have a specific use case in mind?

**Comment by joakime** [comment]
One example is to take all of the request details (access token, accept indicator, other headers, etc) and iterate through the results for a paginated graphql result.

Maybe something in the HttpClient.newRequest builder pattern?

Like what is done in the JDK.
https://docs.oracle.com/en/java/javase/17/docs/api/java.net.http/java/net/http/HttpRequest.html#newBuilder(java.net.http.HttpRequest,java.util.function.BiPredicate)

In Jetty terms.

``` java
Request request = client.newRequest(oldRequest)
                .header("X-GraphQL-Page", i); // sometimes seen in query section
```

**Comment by sbordet** [comment]
I'm not against it, but if you can reference the old request, you probably are close to the code that built it.

I was wondering if there is a use case where you want to duplicate a request that you have not built?

Furthermore, the devil is in the details.
For example, sometimes you cannot duplicate the body, as the body is not reproducible.
Cookies, authorization headers, `Expect` headers, are some that you may not want to duplicate, especially if the URI is different.

With the current APIs (with a mutable `Request`), I am not convinced it is a good idea.

**Comment by cowwoc** [comment]
@sbordet Those are good points. Out of curiosity, how does `HttpClient.copyRequest()` handle duplicating the request body?

In terms of our use-case, we've got the following pseudocode:

  `requestWithRetry(createRequest(...some arguments...))`

To your point, I think that if we were to replace `createRequest()` with `() -> createRequest())` then we should be able to create a new `Request` each time and we wouldn't need this functionality.

**Comment by sbordet** [comment]
> how does HttpClient.copyRequest() handle duplicating the request body?

It does not, it just tries to use the previous body hoping that it is reproducible.
This may cause problems, but I don't think there is a generic solution.

Method `copyRequest()` is called by the implementation only in 2 specific scenarios: authentication and redirect, where requests are supposed to be automatically re-sent by the implementation.

But for these cases, the implementation knows that it must retain specific headers and remove others.

**Comment by cowwoc** [comment]
Fair enough.

As an aside, the way that `HttpClient.newRequest()` solves this problem is by requiring that the request body supplier must be repeatable. Quoting the relevant section of `BodyPublisher`'s Javadoc:

> If a request needs to be resent for any reason, then a new subscription is created which is expected to generate the same data as before.

Then `BodyPublisher.ofInputStream()` reads:

> The {@code Supplier} may return {@code null} on subsequent attempts, in which case the request fails.

I am happy to close this issue, as I found a way to solve my particular use-case (passing a `Supplier<Request>` instead of a `Request` into a method). I'll leave it up to you to decide if you want to investigate this further or close the issue. Thank you for your help.
