### ISSUE TITLE
Should the `RequestDispatcher.ERROR_*` attributes be handled by `Dispatcher$ErrorRequest`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10129]
While other dispatcher types like forward/include handle their dispatcher specific attributes in `Dispatcher$ForwardRequest` and `Dispatcher$IncludeRequest`, the `Dispatcher$ErrorRequest` does not follow that behavior.

Analyze if we can move that handling to the `Dispatcher$ErrorRequest`.

The `RequestDispatcher.ERROR_*` attributes are being set from 2 places before this `Dispatcher$ErrorRequest` is created.

* `org.eclipse.jetty.ee10.servlet.ServletRequestState.sendError(int code, String message)`
* `org.eclipse.jetty.ee10.servlet.ServletRequestState.sendError(Throwable th)`

_Originally posted by @joakime in https://github.com/eclipse/jetty.project/pull/10124#discussion_r1267909739_

**Comment by gregw** [comment]
I believe errors are sufficiently different that it can't be done the same way.
