### ISSUE TITLE
ee9 to ee8 conversion not working for JSP files with jakarta imports

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#10121]
**Jetty version(s)**
12.0.0

**Description**
In the module `jetty-ee9-demo-spec-webapp` there is `logout.jsp` which has an import for `jakarta.servlet.http.HttpSession`.
This is not converted to `javax.servlet.http.HttpSession` for the ee8 version of this war.

**Comment by olamy** [comment]
PR #10159
