### ISSUE TITLE
DefaultServlet not working with named dispatch in Jetty-12 EE10.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#10139]
Discovered from investigations into https://github.com/eclipse/jetty.project/issues/10138.

This seems to have been introduced in the various PRs to fix #9910.

If there is a named dispatch then `DefaultServlet#getEncodedPathInContext` ignores the servletPath of the request because `isDefaultMapping(HttpServletRequest req)` incorrectly says that the default servlet is not at the default mapping.

In the case of the websocket ee10 demo this results in the wrong `index.html` file being served.

**Comment by joakime** [comment]
Merged PR #10140
