### ISSUE TITLE
welcome-file ignored on jetty12ee10 on exploded deploy, works on ee9 and older jettys.

### ISSUE THREAD

**Issue by andresluuk** [eclipse/jetty.project#10141]
**Jetty version(s)**
jetty12ee10 built from latest source.
**Java version/vendor** `(use: java -version)`
JDK17
**OS type/version**
Windows/Unix
**Description**
Maybe the same issue as described under https://github.com/eclipse/jetty.project/issues/10139 ?
**How to reproduce?**
Anyway I have a simple webapp with the following web.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/j2ee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee 
	      http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
	version="2.4">

	<context-param>
		<param-name>org.eclipse.jetty.servlet.Default.welcomeServlets</param-name>
		<param-value>true</param-value>
	</context-param>

	<servlet>
		<servlet-name>myServlet</servlet-name>
		<servlet-class>test.MyServlet</servlet-class>
	</servlet>

	<servlet-mapping>
		<servlet-name>myServlet</servlet-name>
		<url-pattern>/myServlet</url-pattern>
	</servlet-mapping>

	<welcome-file-list>
		<welcome-file>myServlet</welcome-file>
	</welcome-file-list>
</web-app>
```

If I deploy the application as packaged application on jetty12ee10 then it works and MyServlet is hit.
But If I deploy it as exploded application then I will get the directory listing from the webapp root.
The same application for jett12ee9 it works in both modes.

The request made looks like that:
http://localhost:8080/exp-http-welcomeServlet/?foo=bar&1801

**Comment by joakime** [comment]
The following XML context-param configuration is not used in ee10. (it is used, however, in ee8/ee9)

``` xml
	<context-param>
		<param-name>org.eclipse.jetty.servlet.Default.welcomeServlets</param-name>
		<param-value>true</param-value>
	</context-param>
```

Instead you would need to configure the `DefaultServlet` properly with init-params.

Eg:

``` xml
  <servlet>
    <servlet-name>default</servlet-name>
    <servlet-class>org.eclipse.jetty.ee10.servlet.DefaultServlet</servlet-class>
    <init-param>
      <param-name>welcomeServlets</param-name>
      <param-value>true</param-value>
    </init-param>
  </servlet>
```

**Comment by andresluuk** [comment]
Thanks.
I tryed it out, you are right it works with that servlet.

I am a little sad that the new servlet, will fail with other servers, but I can work around that.

**Comment by andresluuk** [comment]
Okei, I got one more question here. The explanation you gave, is about the parameter not beeing used. But why does it work on packaged mode? and the issue arrises only on exploded deploy.

**Comment by andresluuk** [comment]
Ok my mistake here. I did not actually run it in packaged mode. so no more questions here.

**Comment by joakime** [comment]
I'm reintroducing `org.eclipse.jetty.servlet.Default.` prefix support for ee10 in PR #10149

Can you please test it out with your examples too.

**Comment by andresluuk** [comment]
I can confirm that this worked when I used jetty built from the PR.
