### ISSUE TITLE
CustomRequestLog lacks the ability to log RequestTime with millisecond precision

### ISSUE THREAD

**Issue by trtrmitya** [eclipse/jetty.project#10153]
**Jetty version(s)**
11.x, 10.x, 9.x
_[Jetty 9.x is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958)_

**Enhancement Description**

I am in the process of migration from deprecated AbstractNCSARequestLog to CustomRequestLog.
AbstractNCSARequestLog has setLogDateFormat() method which accepts time pattern with "SSS" to log millis.
CustomRequestLog uses DateCache which does not allow time precision less than a second.

Thus I am unable to reproduce old behaviour and log milliseconds.

I have low traffic and do not need to cache formatted time, but I do need milliseconds in logs.

I am asking to add this functionality so I can log RequestTime with milliseconds precision like I did with (now removed) AbstractNCSARequestLog.

**Comment by lachlan-roberts** [comment]
`AbstractNCSARequestLog` also used the `DateCache` class, so there should be no change of behaviour to use the `CustomRequestLog` with code `%{HH:mm:ss,SSS}t` to format the time.

Otherwise if you really need a more precise ms time we can consider adding another % code option for it.

**Comment by trtrmitya** [comment]
Looks like format string does support "SSS", I see milliseconds in logs (at least with Jetty 10.0.15).
Sorry for the noice.

**Comment by lachlan-roberts** [comment]
The work in https://github.com/eclipse/jetty.project/pull/10176 makes it so that millisecond precision is the default from `DateCache`. So now closing this issue.
