### ISSUE TITLE
EE10 Servlet include after `HttpServletResponse.getWriter().println()` omits `Content-Length` from the response

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10155]
**Jetty version(s)**
12

**Description**
Any EE10 servlet that does the following:
```java
response.getWriter().println("Include:");
getServletContext().getRequestDispatcher("/test.txt").include(request, response);
```
will not add the `Content-Length` header to the response.

**Comment by gregw** [comment]
@lorban content length is not expected when include is used, instead chunking or EOF will be used.
However, we do need to write some code to covert writers to outputstreams and visa versa

**Comment by lorban** [comment]
We at least need to assert that the EE10 behavior is sane as using the `OutputStream` instead of the `PrintWriter` results in a content length header in the response, and EE9 adds content length no matter if you use the output stream or the writer.

**Comment by gregw** [comment]
@lorban See #10157 for a potential fix with new tests
