### ISSUE TITLE
Thread Stuck observed while sending message out 

### ISSUE THREAD

**Issue by KDTech10** [eclipse/jetty.project#10167]
Jetty version
11.0.11
Java version
17.0.4
Question
Following Thread stuck traceback is observed when Jetty was trying to send HTTP/2 message out. Could you please help understand when this can happen? 

- Tx Buffer full on the TCP socket 
- process memory shortage
- ??

```
[org.eclipse.jetty.client.RequestNotifier.notifyContent(RequestNotifier.java:162)
org.eclipse.jetty.client.HttpSender.someToContent(HttpSender.java:166)
org.eclipse.jetty.client.HttpSender$ContentConsumer.succeeded(HttpSender.java:521)
org.eclipse.jetty.http2.client.http.HttpSenderOverHTTP2$HeadersPromise.succeeded(HttpSenderOverHTTP2.java:207)
org.eclipse.jetty.http2.client.http.HttpSenderOverHTTP2$HeadersPromise.succeeded(HttpSenderOverHTTP2.java:190)
org.eclipse.jetty.http2.HTTP2Session$StreamsState.lambda$createLocalStream$20(HTTP2Session.java:2207)
org.eclipse.jetty.http2.HTTP2Session$StreamsState$$Lambda$1651/0x00000008018ef9b0.run(Unknown Source)
org.eclipse.jetty.util.Callback$3.succeeded(Callback.java:155)
org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:392)
org.eclipse.jetty.util.CountingCallback.succeeded(CountingCallback.java:63)
org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:392)
org.eclipse.jetty.http2.HTTP2Session$DataEntry.succeeded(HTTP2Session.java:1433)
org.eclipse.jetty.http2.HTTP2Flusher$$Lambda$1622/0x00000008018e1658.accept(Unknown Source)
java.base@17.0.4.1/java.util.ArrayList.forEach(ArrayList.java:1511)
org.eclipse.jetty.http2.HTTP2Flusher.finish(HTTP2Flusher.java:323)
org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:315)
org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:291)
org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386)
org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:292)
org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214)
org.eclipse.jetty.http2.HTTP2Session$StreamsState.flush(HTTP2Session.java:2317)
org.eclipse.jetty.http2.HTTP2Session$StreamsState.createLocalStream(HTTP2Session.java:2224)
org.eclipse.jetty.http2.HTTP2Session$StreamsState.newLocalStream(HTTP2Session.java:2127)
org.eclipse.jetty.http2.HTTP2Session.newStream(HTTP2Session.java:603)
org.eclipse.jetty.http2.client.http.HttpSenderOverHTTP2.sendHeaders(HttpSenderOverHTTP2.java:127)
org.eclipse.jetty.client.HttpSender$ContentConsumer.onContent(HttpSender.java:496)
org.eclipse.jetty.client.util.AsyncRequestContent.notifyContent(AsyncRequestContent.java:264)
org.eclipse.jetty.client.util.AsyncRequestContent.produce(AsyncRequestContent.java:234)
org.eclipse.jetty.client.util.AsyncRequestContent.demand(AsyncRequestContent.java:109)
org.eclipse.jetty.client.HttpSender.demand(HttpSender.java:237)
org.eclipse.jetty.client.HttpSender.send(HttpSender.java:83)
org.eclipse.jetty.http2.client.http.HttpChannelOverHTTP2.send(HttpChannelOverHTTP2.java:102)
org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:122)
org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:110)
org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2.send(HttpConnectionOverHTTP2.java:104)
org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:382)
org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:358)
org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:313)
org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:296)
org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:290)
org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:267)
org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:247)
org.eclipse.jetty.client.HttpClient.send(HttpClient.java:560)
org.eclipse.jetty.client.HttpRequest$$Lambda$1571/0x00000008018b2478.accept(Unknown Source)
```

**Comment by sbordet** [comment]
The stack trace seems incomplete, as after `RequestNotifier.notifyContent()` there is nothing that blocks unless it is your code in your application.

That particular thread has just finished writing a chunk of the request content (so there is no network congestion), and it is notifying the request listeners of this.

All looks normal to me, the thread is not blocked.

**Comment by KDTech10** [comment]
@sbordet Is it possible that notifyContent() function is making any network call which may lead to some wait ?

**Comment by sbordet** [comment]
> @sbordet Is it possible that notifyContent() function is making any network call which may lead to some wait ?

No.

`notifyContent()` is notifying application listeners, therefore your code if you registered a `Request.ContentListener` either on the request instance or on `HttpClient`.

**Comment by KDTech10** [comment]
@sbordet Got it Thanks

**Comment by sbordet** [comment]
Closing as solved. 
Please comment on this issue if you find more evidence (and we'll reopen the issue), but as I said it all looks normal from the Jetty side.

**Comment by KDTech10** [comment]
@sbordet 
I am seeing many occurrences of thread stuck cases with following stacktrace .. 
Any pointer why this could happen ? 

`
{"instant":{"epochSecond":1689095799,"nanoOfSecond":98208830},"thread":"boundedElastic-345","level":"WARN","message":"Thread(s) Stuck,  details:: [ThreadInfo{threadId=467, isStuck=true, lastUpdatedTime=Tue Jul 11 17:16:38 UTC 2023, stuckOccurrence=1, threadName='app-worker-10', status=COMPLETED, runnableHashCode=[], stackTrace='[java.base@17.0.4.1/sun.nio.ch.FileDispatcherImpl.writev0(Native Method), java.base@17.0.4.1/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66), java.base@17.0.4.1/sun.nio.ch.IOUtil.write(IOUtil.java:217), java.base@17.0.4.1/sun.nio.ch.IOUtil.write(IOUtil.java:153), java.base@17.0.4.1/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563), java.base@17.0.4.1/java.nio.channels.SocketChannel.write(SocketChannel.java:642), org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110), org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422), org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275), org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254), org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386), org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:292), org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232), org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214), org.eclipse.jetty.http2.HTTP2Session$StreamsState.flush(HTTP2Session.java:2317), org.eclipse.jetty.http2.HTTP2Session$StreamsState.createLocalStream(HTTP2Session.java:2224), org.eclipse.jetty.http2.HTTP2Session$StreamsState.newLocalStream(HTTP2Session.java:2127), org.eclipse.jetty.http2.HTTP2Session.newStream(HTTP2Session.java:603), org.eclipse.jetty.http2.client.http.HttpSenderOverHTTP2.sendHeaders(HttpSenderOverHTTP2.java:127), org.eclipse.jetty.client.HttpSender$ContentConsumer.onContent(HttpSender.java:496), org.eclipse.jetty.client.util.AsyncRequestContent.notifyContent(AsyncRequestContent.java:264), org.eclipse.jetty.client.util.AsyncRequestContent.produce(AsyncRequestContent.java:234), org.eclipse.jetty.client.util.AsyncRequestContent.demand(AsyncRequestContent.java:109), org.eclipse.jetty.client.HttpSender.demand(HttpSender.java:237), org.eclipse.jetty.client.HttpSender.send(HttpSender.java:83), org.eclipse.jetty.http2.client.http.HttpChannelOverHTTP2.send(HttpChannelOverHTTP2.java:102), org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:122), org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:110), org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2.send(HttpConnectionOverHTTP2.java:104), org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:382), org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:358), org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:313), org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:296), org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:290), org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:267), org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:247), org.eclipse.jetty.client.HttpClient.send(HttpClient.java:560), org.eclipse.jetty.client.HttpRequest$$Lambda$1573/0x00000008018b95c8.accept(Unknown Source), org.eclipse.jetty.client.HttpRequest.sendAsync(HttpRequest.java:818), org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:805), org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.send(ResponseListenerProcessor.java:167), org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onRequest(ResponseListenerProcessor.java:153), org.eclipse.jetty.reactive.client.internal.AbstractSinglePublisher.request(AbstractSinglePublisher.java:83), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:134), org.eclipse.jetty.reactive.client.internal.AbstractSinglePublisher.subscribe(AbstractSinglePublisher.java:55), reactor.core.publisher.MonoSource.subscribe(MonoSource.java:69), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203), reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126), reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:196), reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:268), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209), reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89), reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:121), reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60), reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:81), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203), reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:140), org.springframework.http.client.reactive.JettyClientHttpRequest.lambda$writeWith$2(JettyClientHttpRequest.java:98), org.springframework.http.client.reactive.JettyClientHttpRequest$$Lambda$2014/0x0000000801a86228.accept(Unknown Source), reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58), reactor.core.publisher.Mono.subscribe(Mono.java:4400), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263), reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51), reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157), reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74), reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664), reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180), reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152), reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400), reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171), reactor.core.publisher.MonoSingle$SingleSubscriber.doOnRequest(MonoSingle.java:103), reactor.core.publisher.Operators$MonoInnerProducerBase.request(Operators.java:2731), reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194), reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068), reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:115), reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96), reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68), reactor.core.publisher.Mono.subscribe(Mono.java:4400), reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263), reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51), reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64), reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52), reactor.core.publisher.Mono.subscribe(Mono.java:4400), reactor.core.publisher.Mono.subscribeWith(Mono.java:4515), reactor.core.publisher.Mono.subscribe(Mono.java:4371), reactor.core.publisher.Mono.subscribe(Mono.java:4307), reactor.core.publisher.Mono.subscribe(Mono.java:4254), 
`

**Comment by sbordet** [comment]
The stack trace shows that the TCP connection is congested.

This is typically because the client cannot read fast enough, or you have reached the max network bandwidth.
In order to arrive at this point, you must have configured the HTTP/2 flow control window to a very large value.

Nothing wrong in Jetty, this is normal.

If you are doing a load test, you're probably hitting limits in the client, which is very common.
