### ISSUE TITLE
some names are not converted from jakarta to javax in ee9 to ee8 conversion

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#10166]
A lot of names of methods/fields/variables are not translated from jakarta to javax in ee8 modules.

- `JavaxWebSocketFrameHandle#newJakartaWebSocketFrameHandler`
- `JavaxWebSocketFrameHandlerFactory#discoverJakartaFrameHandlerMetadata`
- All methods on `JavaxWebSocketSessionListener`.
- `JavaxWebSocketServerContainer#JAKARTA_WEBSOCKET_CONTAINER_ATTRIBUTE`
- `Origin#JAKARTA_API`
- `Source#JAKARTA_API`
- Variable names.

**Comment by olamy** [comment]
I don't think it is worth spending time on local variables. 
The generated sources are not supposed to be read or modified.

**Comment by lachlan-roberts** [comment]
Fair enough I was thinking its probably not worth fixing that one as well
what about method names?

**Comment by olamy** [comment]
yes I can try to do this. This might be a bit tricky but doable
