### ISSUE TITLE
Jetty HTTP/2 Secure Client stops creating new connection despite active connection being less than configured maxConnectionsPerDestination count

### ISSUE THREAD

**Issue by KDTech10** [eclipse/jetty.project#10177]
**Jetty version(s)**
11.0.15

**Java version/vendor**
17.0.7
**OS type/version**
Linux 4.14.35-1818.3.3.el7uek.x86_64

**Description**
Configured value of maxConnectionsPerDestination is 4

When AppOne using Jetty HTTP/2 Client is sending a secure message(https) to service AppTwo having fqdn destpod1svc.testns.svc.cluster.local (10.107.198.39:8443), the remote service (i.e. AppTwo) sends success response and kills the underlying TCP connection by sending a FIN packet directly after 5 seconds.

When AppOne tries to send the 2nd secure message to service AppTwo, a new connection is established along with TLS Handshake. Again, the remote service(i.e. AppTwo) sends success response and kills the underlying TCP connection by sending a FIN packet directly after 5 seconds.

Now, this flow works for 4 iterations.

Post that on 5th iteration, when AppOne tries to send the same message to service AppTwo, Jetty HTTP/2 client does not send any message. From this time onwards, all attempts to send any message to  AppTwo having fqdn destpod1svc.testns.svc.cluster.local fails.

httpDump of Jetty shows, there are 4 httpsession present with an error. Looks like these entries are not cleaned and due to that Jetty is not trying to establish the next connection when a new request needs to be sent. 

Following dump shows, all 4 http connections are present in error state, and post this new connection attempt is happening.

```
HttpDestinationOverHTTP2 [numberOfIps=0] - STARTED||  += 
|  |  +> java.util.ArrayList@f792c2f(size=4)
|  |     +: {u=2,c=HttpConnectionOverHTTP2@64a7c3ad(closed=true)[HTTP2ClientSession@6b1589{local:null,remote:null,sendWindow=65275,recvWindow=16776956,state=[streams=0,CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@7156f623{0/no_error/stop},failure=java.io.IOException: no_error/stop]}]}
|  |     +: {u=1,c=HttpConnectionOverHTTP2@51b553d8(closed=true)[HTTP2ClientSession@6b9e4273{local:null,remote:null,sendWindow=65275,recvWindow=16776956,state=[streams=0,CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@19ff54d5{0/no_error/stop},failure=java.io.IOException: no_error/stop]}]}
|  |     +: {u=1,c=HttpConnectionOverHTTP2@2f3432ba(closed=true)[HTTP2ClientSession@37cf242c{local:null,remote:null,sendWindow=65275,recvWindow=16776956,state=[streams=0,CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@268619bd{0/no_error/stop},failure=java.io.IOException: no_error/stop]}]}
|  |     +: {u=1,c=HttpConnectionOverHTTP2@7f2fafbf(closed=true)[HTTP2ClientSession@64ed68d3{local:null,remote:null,sendWindow=65275,recvWindow=16776956,state=[streams=0,CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@9bb1143{0/no_error/stop},failure=java.io.IOException: no_error/stop]}]}
|  +> exchanges size=0
```

Complete logs and dump attached.
[jetty_dump_and_logs.zip](https://github.com/eclipse/jetty.project/files/12215777/jetty_dump_and_logs.zip)

Note: This issue is not observed for HTTP/2 non secure connection

**How to reproduce?**

- Set maxConnectionsPerDestination to x
- Send HTTP/2 secure message to a remote recipient
- Remote recipient must send FIN packet before IDLE timeout expiry of the HTTP/2 connection
- once x send attempts are exhausted, attempt to send x+1 message won't work

**Comment by sbordet** [comment]
Are you replacing some of the core components of Jetty?

I ask because a normal dump would be, for example:

```
+= HttpDestination[Origin@d54a8564[http://localhost:35199,tag=null,protocol=Protocol@301a9e[proto=[h2c],nego=false]]]@466276d8,state=STARTED,queue=0,pool=MultiplexConnectionPool@5ce8d869[s=STARTED,c=0/1/64,a=0,i=1,q=0,p=@31c7528f[inUse=0,size=1,max=64,closed=false]],stale=false,idle=-1 - STARTED
|  += MultiplexConnectionPool@5ce8d869[s=STARTED,c=0/1/64,a=0,i=1,q=0,p=@31c7528f[inUse=0,size=1,max=64,closed=false]] - STARTED
|  |  +- @31c7528f[inUse=0,size=1,max=64,closed=false]
|  |     +> entries size=1
|  |        +> MultiEntry@2b76ff4e{IDLE,usage=1,multiplex=0,pooled=HttpConnectionOverHTTP2@7a1234bf(closed=false)[HTTP2ClientSession@60856961{local:/127.0.0.1:45468,remote:localhost/127.0.0.1:35199,sendWindow=1048576,recvWindow=16777216,state=[streams=0,NOT_CLOSED,goAwayRecv=null,goAwaySent=null,failure=null]}]}
|  +> exchanges size=0
```

This is quite different from your dump.

**Comment by KDTech10** [comment]
No, no components are replaced. This data is obtained using the dump() API of org.eclipse.jetty.client.HttpClient

**Comment by sbordet** [comment]
> This data is obtained using the dump() API of org.eclipse.jetty.client.HttpClient

So why is the output format different?

In Jetty there is no code that writes `[numberOfIps=0]` in the dump.

**Comment by KDTech10** [comment]
My Bad, the Jetty Lib I was using was a custom one with some changes. With vanilla jetty Client it works . 
Closing the ticket.
