### ISSUE TITLE
Allow Request.getPart()/getParts() to be called from anywhere (and still clean up tmp files)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#102]
migrated from Bugzilla [#391187](https://bugs.eclipse.org/bugs/show_bug.cgi?id=391187)
status ASSIGNED severity _enhancement_ in component _server_ for _7.6.x_
Reported in version _8.1.7_ on platform _PC_
Assigned to: Jan Bartel

On 2012-10-05 01:27:04 -0400, Jan Bartel wrote:

> A further tweak to fix for bug 391080:
> 
> Although the 3.0 spec says you can only call Request.getPart()/getParts() from a servlet annotated with @MultiPartConfig or <multipart-config>, we want to allow it to be called from any servlet. Currently, if that was done, the tmp files would not be cleaned up, so requires some refactoring to allow it to work.

On 2012-10-07 20:51:53 -0400, Jan Bartel wrote:

> Marking this as an enhancement.

**Comment by janbartel** [comment]
This issue is no longer valid, so I'm closing it.
