### ISSUE TITLE
Increasing the ConnectionLimit -Still system is slow 

### ISSUE THREAD

**Issue by smitagarg0807** [eclipse/jetty.project#10215]
We are constantly facing this issue where we had Connection Limit to 1000 and QueueThreadPool size to 1000 .1000 Connection Limit got exhausted at one point of time and we increased the Connection Limit to 2000 .But system started behaving very slow at peak load even though we see no of connections haven't exhausted . We are discussing around increasing the QueuedThreadPoolSize . How can we decide on ideal jetty config provided max expected connection in system is 1500 .Acceptor size is 7

**Comment by sbordet** [comment]
The acceptor size should be 1, as 7 is typically way too much and not necessary.

You have provided too little information to help you. 
Likely your application is the bottleneck, as Jetty can easily do 100k+ connections without issues.

You should monitor the Jetty components, for example via JMX, and profile your system to see where the bottleneck is.

For example, applications that use a database may have a bottleneck in the database connection pool, that won't be solved by tuning Jetty.

**Comment by sbordet** [comment]
Closing as answered.
