### ISSUE TITLE
Implement CrossOriginHandler

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10220]
**Jetty version(s)**
12

**Enhancement Description**
The functionality of `CrossOriginFilter` should be moved to a `CrossOriginHandler`.
It should be possible to add the `CrossOriginHandler` _after_ a `ServletContextHandler` in case different web applications want to configure cross-origin differently.

**Comment by gregw** [comment]
It is now possible to add handles after ee10 ServletContextHandler.

However for ee8/9 it might be a bit more fiddly to insert a core handler in the right location
