### ISSUE TITLE
Uses of ServiceLoader.iterator() should catch ServiceConfigurationError with reasonable behavior

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1022]
Our various uses of ServiceLoader.iterator() should be improved upon to skip iterations where the `ServiceLoader.iterator().next()` would produce a `ServiceConfigurationError`.

See javadoc:

http://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html#iterator--

**Comment by janbartel** [comment]
@joakime  I've reviewed the use of ServiceLoader.iterator() for Annotation handling and I'm satisfied of the exception handling.  Suggest you assign this to @sbordet  and @gregw to review the ALPN usage of ServiceLoader.

**Comment by sbordet** [comment]
ALPN already does that: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java#L62.

When trying to load the JDK 9 service in a JDK 8 JVM, we would get `ClassFormatError`, so we catch it, ignore it, and continue with the iteration.

Failures in `hasNext()` will unwind the stack and fail to start Jetty, as they're thrown from the `ALPNServerConnectionFactory` constructor.

**Comment by joakime** [comment]
Considering this closed.
