### ISSUE TITLE
Restore buffer leak tracking in tests.

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10226]
**Jetty version(s)**
12

**Description**
Build on `ArrayByteBufferPool.Tracking` introduced in #10225 to fix the TODOs named "restore leak tracking".

**Comment by sbordet** [comment]
See also #9148

**Comment by lorban** [comment]
Leak tracking has been re-enabled in #10325, but some leaks remain. The affected tests have been marked with `@Tag("DisableLeakTracking")` and still need fixing.

**Comment by lorban** [comment]
Leak tracking in tests has been restored, and known leaky tests have been marked with `@Tag("DisableLeakTracking")`.

This issue can be considered solved; known leaks will be fixed independently.
