### ISSUE TITLE
Make idle timeouts transient

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#10234]
**Jetty version(s)**
12

**Enhancement Description**

Idle timeouts delivered via read() should be transient, i.e. another read can be attempted after the timeout of the read chunk is not last

**Comment by gregw** [comment]
After work on #10233, it became apparent that AsyncContentProducer is not able to handle transient timeouts, as the error chunk is consumed in an isReady call and then null returned on the following read. This implementation needs to be modified to ensure error chunks are delivered to application before being released.

**Comment by gregw** [comment]
It may be that writes cannot have transient timeouts, as it will be unclear how much data, if any, was written. 

Perhaps it is not worth doing transient timeouts for just reads? In which case this issue is to remove all the TODOs added in #10233

**Comment by gregw** [comment]
@sbordet @lorban Can we make a time to review this later this week or early next.  I don't want this to get punted.  I we should do this quickly or remove the TODOs and stay as is.

**Comment by gregw** [comment]
@lorban I think we should move this to 12.0.2

**Comment by lorban** [comment]
@gregw ack

**Comment by sbordet** [comment]
Fixed by #10844 and further refined by #10920.
