### ISSUE TITLE
Review read failures impacting writes 

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10277]
**Jetty version(s)**
12

**Description**
Read failures should not impact writes (too much), as a write might still be possible even if the read failed.
Typical examples are early EOF in reads -- they should not impact writes.

The idea is that if a read failure is catastrophic, we would attempt the write anyway and will get the failure through the write, rather than assuming that the writes will fail.

Child issues / prs
 - [ ] #10431 
 - [ ] #10432

**Comment by sbordet** [comment]
I think this should also help with #10234, because idle timeouts should be treated as read failures and always as hard failures for pending writes.

**Comment by lorban** [comment]
While investigating a server buffer leak in `HttpClientStreamTest.testUploadWithConcurrentServerCloseClosesStream()` we discovered that stopping a connector while there is an in-flight request does not notify the failure listeners.

While not exactly the same issue, this should be taken into account too.

**Comment by sbordet** [comment]
FIxed by #10948.
