### ISSUE TITLE
How to retrieve Request query parameters without servlets?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10283]
**Jetty version**
12.0.0

**Java version**
20

**Question**
My understanding is that we're supposed to be able to drop the servlet API in Jetty 20 and use the `Request`, `Response` and `Handler` classes instead.

I see most of what I need here, but it's not clear how I am supposed to look up an HTTP request's query parameters? All the interesting methods are package-private.

**Comment by cowwoc** [comment]
Ah, am I supposed to use `Request.getHttpURI().getQuery()`? Is there a way to get a parsed version of the query parameters so I can easily look up key-value pairs?

**Comment by sbordet** [comment]
Static method `Request.extractQueryParameters()`.

**Comment by cowwoc** [comment]
Thank you :) I feel a bit silly for forgetting that `Request` was an interface so all methods are public, not public-private by default.

**Comment by cowwoc** [comment]
It would be great if you could document a Servlet API -> Jetty API mapping. That would help a lot of people.

**Comment by sbordet** [comment]
It's a very good suggestion, we will work on that on the migration guide. Thanks!

**Comment by sbordet** [comment]
@cowwoc see #10298, in particular class `ServletToHandlerDocs`.
Your feedback or PR review will be appreciated. Thanks!

**Comment by cowwoc** [comment]
@sbordet Sorry, I was away on vacation last week. I left some comments/questions but on the whole the PR looks good to me.
