### ISSUE TITLE
Document all HttpFields methods

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10284]
**Jetty version(s)**
12.0.0

**Enhancement Description**
Some `HttpFields` methods, such as `get(HttpHeader)` need some clarification. For example, is this method returning all the values of a header? Is it returning only the first value? Some methods return `List` or an array. Do these methods ever return `null`? If so, when?

In general I would advocate documenting all the methods since they are a public part of the API.

**Comment by sbordet** [comment]
@cowwoc see #10308.

**Comment by cowwoc** [comment]
@sbordet I left some comments on the PR

**Comment by sbordet** [comment]
Fixed by #10308.
