### ISSUE TITLE
Request.getContext().getContextPath()

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10294]
**Jetty version(s)**
12.0.0

**Java version/vendor** `(use: java -version)`
20

**OS type/version**
Microsoft Windows [Version 10.0.19045.3324]

**Description**
When I invoke `Request.getContextPath(Request)` I get back `null`. The Javadoc does not indicate that the return value may be `null` and it's not clear what this indicates. Does this imply a context path of `"/"`? If so, why not return `"/"`?

**Comment by lachlan-roberts** [comment]
A return of `null` would mean that you are in a handler not wrapped by a `ContextHandler`.

The default value returned by `ContextHandler.ScopedContext#getContextPath` is `"/"`. 
But if you are not in a context you will instead get the `ServerContext` which will return null for `getContextPath()`.

**Comment by cowwoc** [comment]
Got it. Mentioning this behavior in the method(s)` Javadoc would resolve it for me.

**Comment by gregw** [comment]
> Got it. Mentioning this behavior in the method(s)` Javadoc would resolve it for me.
@cowwoc will do.  The core handler API in jetty 12 is new in 12 and very much under documented, so feedback like this is most welcome.

**Comment by gregw** [comment]
@cowwoc see #10297

**Comment by gregw** [comment]
fixed with #10297
