### ISSUE TITLE
Injection.setTarget() fails when default Locale causes String.toUpperCase() to produce unexpected results

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#103]
migrated from Bugzilla [#393363](https://bugs.eclipse.org/bugs/show_bug.cgi?id=393363)
status ASSIGNED severity *major* in component *server* for *7.6.x*
Reported in version *unspecified* on platform *All*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[0001-The-use-of-toUpperCase-must-be-Locale-insensitive.-O.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=223085)_ (ID 223085)

On 2012-11-01 14:58:16 -0400, Mike Christianson wrote:

> Created attachment 223085
> Locale insensitive patch
> 
> The use of toUpperCase() must be Locale insensitive. Otherwise, setTarget() will throw a NoSuchMethodException when the rules of the default Locale produce an unexpected result. For example, if user.language=tr, then the following would produce "setÄ°nitialSize" rather than the expected "setInitialSize":
> 
>     String target = "initialSize";
>     String setter = "set"+target.substring(0,1).toUpperCase()+target.substring(1);
> 
> This applies to current and past versions of Jetty.

On 2012-11-01 20:56:10 -0400, Greg Wilkins wrote:

> This needed a wider solution as we do lots of toUpperCase and toLowerCase calls assuming the default local will work.
> 
> I have patched jetty-7 ( 65202e9 ) and these changes will soon be merged to 8 and 9.
> 
> I've not yet done a test harness for this.

**Comment by janbartel** [comment]
Looks like this was fixed some time ago. Closing.
