### ISSUE TITLE
Remove Jetty from Eclipse Wiki

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#10302]
https://wiki.eclipse.org/Jetty

If I remember right, we talked about removing the Wiki contents long ago, but our argument for keeping it was that it was the only docs available for Jetty 7 and Jetty 8.

Now that 12 is out, it seems a good time to revisit the question.

I would like to see if go since it _still_ shows up in some search results despite there being much newer and more relevant information available.

The Wiki will be shut down in 2026, so if we wait long enough, the problem will be solved.

**Comment by joakime** [comment]
+1 to eliminate all of the Jetty 7 and Jetty 8 wiki content.

Can we ask Eclipse Webmasters to redirect any requests to `https://wiki.eclipse.org/Jetty*` to `https://eclipse.dev/jetty/` (the directory, no attempt to rewrite the urls to other places that do exist)

**Comment by jmcc0nn3ll** [comment]
I got confirmation from the webmasters that they can set up a 301 redirect like this.

I'll make sure to get this coordinated and close out this issue when it is complete.
