### ISSUE TITLE
Document porting to jetty-12

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#10303]
**Jetty version(s)**
12

**Enhancement Description**

We need to document how to port to jetty 12.
Now that 12.0.0 is out, we should make a simple guide a very high priority, with a more in depth guide developed over time.

**Comment by sbordet** [comment]
@gregw can we close this?

We have migration guide docs for Maven artifacts, class/package changes for `HttpClient` and WebSocket (and API change descriptions), migrating from Servlets to Handlers.

What would you like to see more as minimal and urgent?
