### ISSUE TITLE
Remove jetty-home-with-docs to eliminate build time cyclic dependencies

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#10312]
**Jetty version(s)**
Jetty-12

**How to reproduce?**
```
mvn clean install -DskipTests -Dasciidoctor.skip=false
```
console has error for all ascii doc extension trying to capture output:
```
[INFO] Working Dir: /home/olamy/dev/sources/jetty/jetty.project/target/tests/test-bases/jetty_base_15951583927940853877
[INFO] Executing: [/home/olamy/.sdkman/candidates/java/21.ea.32-open/bin/java, -Djava.io.tmpdir=/home/olamy/dev/sources/jetty/jetty.project/target/tests/test-bases/jetty_base_11481260225660893827/work, -jar, /home/olamy/dev/sources/jetty/jetty.project/jetty-home/target/jetty-home/start.jar, --add-modules=threadpool-virtual-preview,http]
[INFO] Working Dir: /home/olamy/dev/sources/jetty/jetty.project/target/tests/test-bases/jetty_base_11481260225660893827
[INFO] Error: Unable to access jarfile /home/olamy/dev/sources/jetty/jetty.project/jetty-home/target/jetty-home/start.jar
```
It means documentation is partially generated.

This is because the asciidoc extension depends on a build and exploded jetty-home module https://github.com/eclipse/jetty.project/blob/c66f9809ba3f6a1a6cc0a27c254460c22d94c71b/documentation/jetty-asciidoctor-extensions/src/main/java/org/eclipse/jetty/docs/JettyIncludeExtension.java#L94 (BUT this is not declared in the pom whereas jetty-documentation wheres it really depend on jetty-home and an exploded) It would be better to use maven-dependency-plugin and unpack the dependency rather than depend on a build output directory of another module (and not even declared as a dependency)

BUT as jetty-home depends on jetty-documentation (to include it in the home zip) this would be a cyclic dependency...

Not sure how to fix that: get back jetty-distribution? another solution?

**Comment by sbordet** [comment]
Fixed by #10348.
