### ISSUE TITLE
Remove references to ContinuationThrowable

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10317]
**Jetty version(s)**
12

**Description**
ee10.ServletChannel and ee9.HttpChannel still reference `ContinuationThrowable` as a String in a catch block.
@gregw is it still necessary?

**Comment by gregw** [comment]
Technically there is still a library out there as part of 9.4.x release, so it may still be used in some webapps.
@joakime can you work out how many dependencies there are on `jetty-continuation` artifact?

**Comment by gregw** [comment]
Thanks @joakime : There are over [4000 projects](https://github.com/eclipse/jetty.project/network/dependents?package_id=UGFja2FnZS0xNzk4MDUzOTk%3D) with a direct reference to `jetty-continuation`.  At least some of those are actively maintained and on the latest 9.4.x release.   So it is conceivable that some of those are actually using the continuation API wrapper and would thus benefit from the support to suppress `ContinuationThrowable`s.  So I think we should keep it for now until jetty-9.4 is EOL for some time.

However, we could move the handling of it into `handleException` to be clearer.

**Comment by gregw** [comment]
Not worth the noise for such a minor cleanup.
