### ISSUE TITLE
Review mod/xml property usage in `jetty-12.0.x`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10334]
It started with a comment on PR #10209 ...

> The property `jetty.httpConfig.port` does not exist, remove it.
>
> _Originally posted by @sbordet in https://github.com/eclipse/jetty.project/pull/10209#discussion_r1297156912_

But there's more to review than just that 1 property.

**Comment by joakime** [comment]
First pass through the `jetty-12.0.x` branch to identify what needs to be addressed.

## Deprecated Properties
*`jetty.connection.limit`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-connectionlimit.xml

*`jetty.customrequestlog.formatString`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-requestlog.xml

*`jetty.gzip.compressionLevel`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-gzip.xml

*`jetty.gzip.deflaterPoolCapacity`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-gzip.xml

*`jetty.gzip.inflaterPoolCapacity`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-gzip.xml

*`jetty.http.compliance`*
 + jetty-core/jetty-server/src/main/config/etc/jetty.xml

*`jetty.openid.authMethod`*
 + jetty-core/jetty-openid/src/main/config/etc/jetty-openid.xml

*`jetty.openid.openIdProvider`*
 + jetty-core/jetty-openid/src/main/config/etc/jetty-openid.xml
 + jetty-ee8/jetty-ee8-openid/src/main/config/etc/jetty-ee8-openid.xml
 + jetty-ee9/jetty-ee9-openid/src/main/config/etc/jetty-ee9-openid.xml

*`jetty.sslContext.trustStoreAbsolutePath`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-ssl-context.xml

*`jetty.truststore`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-ssl-context.xml

*`threads.max`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-threadpool-virtual-preview.xml
 + jetty-core/jetty-server/src/main/config/etc/jetty-threadpool.xml

*`threads.min`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-threadpool-virtual-preview.xml
 + jetty-core/jetty-server/src/main/config/etc/jetty-threadpool.xml

*`threads.timeout`*
 + jetty-core/jetty-server/src/main/config/etc/jetty-threadpool-virtual-preview.xml
 + jetty-core/jetty-server/src/main/config/etc/jetty-threadpool.xml

----

Deprecated Property is still used in non-deprecated way: *`jetty.openid.authMethod`*
 * Deprecated in: jetty-core/jetty-openid/src/main/config/etc/jetty-openid.xml
 * Active in: jetty-ee8/jetty-ee8-openid/src/main/config/etc/jetty-ee8-openid.xml
 * Active in: jetty-ee8/jetty-ee8-openid/src/main/config/modules/ee8-openid.mod
 * Active in: jetty-ee9/jetty-ee9-openid/src/main/config/etc/jetty-ee9-openid.xml
 * Active in: jetty-ee9/jetty-ee9-openid/src/main/config/modules/ee9-openid.mod
----

Active Property used in MOD not present in any XML: *`connection-type`*
 * Present in: jetty-integrations/jetty-nosql/src/main/config/modules/session-store-mongo.mod

Active Property used in MOD not present in any XML: *`db-connection-type`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/session-store-jdbc.mod

Active Property used in MOD not present in any XML: *`jetty.byteBufferPool.retainedDirectMemory`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/bytebufferpool-quadratic.mod
 * Present in: jetty-core/jetty-server/src/main/config/modules/bytebufferpool.mod

Active Property used in MOD not present in any XML: *`jetty.byteBufferPool.retainedHeapMemory`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/bytebufferpool-quadratic.mod
 * Present in: jetty-core/jetty-server/src/main/config/modules/bytebufferpool.mod

Active Property used in MOD not present in any XML: *`jetty.deploy.monitoredPath`*
 * Present in: jetty-core/jetty-deploy/src/main/config/modules/core-deploy.mod
 * Present in: jetty-ee10/jetty-ee10-webapp/src/main/config/modules/ee10-deploy.mod
 * Present in: jetty-ee8/jetty-ee8-webapp/src/main/config/modules/ee8-deploy.mod
 * Present in: jetty-ee9/jetty-ee9-webapp/src/main/config/modules/ee9-deploy.mod

Active Property used in MOD not present in any XML: *`jetty.gzip.checkGzExists`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/gzip.mod

Active Property used in MOD not present in any XML: *`jetty.gzip.dispatcherTypes`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/gzip.mod

Active Property used in MOD not present in any XML: *`jetty.statistics.gracefulShutdownWaitsForRequests`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/graceful.mod

Active Property used in MOD not present in any XML: *`session-data-cache`*
 * Present in: jetty-core/jetty-server/src/main/config/modules/session-store-cache.mod
----

Active Property used in XML not present in any MOD files: *`jetty.debug.append`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/jetty-debug.xml

Active Property used in XML not present in any MOD files: *`jetty.deploy.defaultsDescriptorPath`*
 * Present in: jetty-ee10/jetty-ee10-webapp/src/main/config/etc/jetty-ee10-deploy.xml

Active Property used in XML not present in any MOD files: *`jetty.http.connectTimeout`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/jetty-http.xml

Active Property used in XML not present in any MOD files: *`jetty.httpConfig.persistentConnectionsEnabled`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/jetty.xml

Active Property used in XML not present in any MOD files: *`jetty.logs`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/jetty-debug.xml

Active Property used in XML not present in any MOD files: *`jetty.session.hazelcast.configurationLocation`*
 * Present in: jetty-integrations/jetty-hazelcast/src/main/config/etc/sessions/hazelcast/default.xml
 * Present in: jetty-integrations/jetty-hazelcast/src/main/config/etc/sessions/hazelcast/remote.xml

Active Property used in XML not present in any MOD files: *`jetty.session.infinispan.idleTimeout.seconds`*
 * Present in: jetty-integrations/jetty-infinispan/jetty-infinispan-common/src/main/config/etc/sessions/infinispan/infinispan-common.xml

Active Property used in XML not present in any MOD files: *`jetty.session.infinispan.serialization`*
 * Present in: jetty-integrations/jetty-infinispan/jetty-infinispan-common/src/main/config/etc/sessions/infinispan/infinispan-common.xml

Active Property used in XML not present in any MOD files: *`jetty.session.jdbc.schema.catalogName`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/sessions/jdbc/session-store.xml

Active Property used in XML not present in any MOD files: *`jetty.session.jdbc.schema.schemaName`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/sessions/jdbc/session-store.xml

Active Property used in XML not present in any MOD files: *`jetty.ssl.connectTimeout`*
 * Present in: jetty-core/jetty-server/src/main/config/etc/jetty-ssl.xml

**Comment by joakime** [comment]
I'll be able to address all of these (and possibly more) on Monday.

**Comment by sbordet** [comment]
Add `jetty.httpConfig.port`, used in distribution tests (for sure in `DemoModulesTests`).

**Comment by joakime** [comment]
Should review other Issues with properties

* #5305
