### ISSUE TITLE
Multiple WebAppContexts with EE8 and EE10

### ISSUE THREAD

**Issue by janitza-bjag** [eclipse/jetty.project#10332]
**Jetty 12**

**Jetty core ee8 ee10**

**Java 17**

I can't find any documentation about how to use multiple WebAppContexts with different EE Versions. Are there any examples or demos how to handle that?

**Comment by joakime** [comment]
See https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-deploy

Pay attention to "Environment Resolution"

**Comment by joakime** [comment]
For demos, you can ...

``` shell
$ $ mkdir demos-12-all-env
$ cd demos-12-all-env/
$ java -jar ~/code/jetty/distros/jetty-home-12.0.0/start.jar --add-modules=ee8-demos,ee9-demos,ee10-demos
...(snip all of the demos are installed in your new jetty.base)...
$ java -jar ~/code/jetty/distros/jetty-home-12.0.0/start.jar
# jetty starts
```

**Comment by janitza-bjag** [comment]
Thanks, is there also a way of creating these WebAppContexts by hand?
Currently we have an interface providing attributes for our WARs and also extending the WebAppClassLoader with additional JARs ...

**Comment by joakime** [comment]
> Thanks, is there also a way of creating these WebAppContexts by hand?

Just use the appropriate WebAppContext.

* org.eclipse.jetty.ee10.webapp.WebAppContext
* org.eclipse.jetty.ee9.webapp.WebAppContext
* org.eclipse.jetty.ee8.webapp.WebAppContext

> Currently we have an interface providing attributes for our WARs and also extending the WebAppClassLoader with additional JARs ...

Attributes can be set with `WebAppContext.setAttribute(String, Object)`, that's built-in.

Why can't you just use the built-in `WebAppContext.setExtraClasspath(List<Resource>)`? 
The `setExtraClasspath` call participates with the WebApp's Configuration layer properly, which performs the servlet appropriate descriptor build-out mechanisms, a custom `WebAppClassLoader` does not, and you can easily mess up servlet spec behaviors doing it that way.  Not to mention you'll lose plenty of debugging and dump functionality built into Jetty too.

**Comment by joakime** [comment]
It would probably make more sense for you to have a custom Deployment Provider, that sets up the WebAppContext before it's started.
That allows you to have a single point of control, and not trying to extend all of the various things like you are.

**Comment by janitza-bjag** [comment]
Thanks a lot,
I got stuck because I didn't realize that the WebAppContext no longer derives directly from Handler, but is a supplier to it ...
