### ISSUE TITLE
Flaky Test `org.eclipse.jetty.server.CustomRequestLogTest.testLogRequestTimeCustomFormats`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10333]
**Jetty version(s)**
12.0.0

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**

Flaky test ...

```
Error
Expected: is "[Sun Aug 13 15:28:14 -05:00 2023]"
     but: was "[Sun Aug 13 15:28:13 -05:00 2023]"

Stacktrace
java.lang.AssertionError: 
Expected: is "[Sun Aug 13 15:28:14 -05:00 2023]"
     but: was "[Sun Aug 13 15:28:13 -05:00 2023]"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.server@12.0.1-SNAPSHOT/org.eclipse.jetty.server.CustomRequestLogTest.testLogRequestTimeCustomFormats(CustomRequestLogTest.java:566)
```

Looks like it's off by 1 second.

**Comment by lachlan-roberts** [comment]
The reason for this is because `Request.getTimeStamp(request)` will not always return a consistent value. This method does the following:
```java
System.currentTimeMillis() - millisElapsed(request.getHeadersNanoTime(), NanoTime.now())
```

so the amount of time elapsed between the `System.currentTimeMillis()` and `NanoTime.now()` calls can vary.

I don't think we can de-flake this test without having a consistent request timestamp.

@lorban @gregw thoughts?

**Comment by lorban** [comment]
> so the amount of time elapsed between the System.currentTimeMillis() and NanoTime.now() calls can vary.

What do you mean by 'can vary'? Do you mean the time is not monotonic (i.e.: it can go backward)? If so, by how much?

I agree that this code is less precise than simply taking a timestamp and saving it as a field, but it's a bit faster and saves a field. We need to balance the cost of extra precision vs its worth.

**Comment by lachlan-roberts** [comment]
@lorban I just mean that you could call `Request.getTimeStamp(request)` 10 times on the same request and get a different value every time.

An extreme example is if there was a 1 second GC pause between `System.currentTimeMillis()` and `NanoTime.now()`, then the `Request.getTimeStamp(request)` value is going to be 1 second off.

**Comment by lorban** [comment]
@lachlan-roberts I guess you mean a 1s GC between `System.currentTimeMillis()` and the substraction of `NanoTime.millisSince()`? Yes, you're right, that's an overlook. My bad.

Then I guess we're back to saving the timestamp in a request field, or maybe store it as a request attribute from within `Request.getTimeStamp(request)`?
