### ISSUE TITLE
Make `ErrorHandler.writeErrorJson()` a method that can be overridden

### ISSUE THREAD

**Issue by mdindoffer** [eclipse/jetty.project#10338]
**Jetty version(s)**
12

**Jetty Environment**
N/A

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

**OS type/version**
Linux

**Description**
The `ErrorHandler#writeErrorJson` is private, while all other error response generating methods are protected. This makes it the only response type that is impossible to override by extending the ErrorHandler.

Please change the visibility of the method to `protected`, just like the rest of the methods in the `ErrorHandler`.

**How to reproduce?**
N/A

**Comment by olamy** [comment]
PR merged https://github.com/eclipse/jetty.project/pull/10360
