### ISSUE TITLE
`ServletHandler` javadoc needs update to indicate requirement with `ServletContextHandler`

### ISSUE THREAD

**Issue by mdindoffer** [eclipse/jetty.project#10345]
**Jetty version(s)**
Jetty 12.0.0

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

**OS type/version**
linux

**Description**
Jetty throws `java.lang.IllegalStateException: Cannot use ServletHandler without ServletContextHandler` when I try to run `Server` with just a `ServletHandler`. This was 100% possible in Jetty 11.
Even the Javadocs for `ServletHandler` state this as a valid scenario (emphasis mine):
> This handler maps requests to servlets that implement the jakarta.servlet.http.HttpServlet API.
This handler does not implement the full J2EE features and is intended to be used directly when a full web application is not required. If a Web application is required, then this handler should be used as part of a org.eclipse.jetty.webapp.WebAppContext.
**_Unless run as part of a ServletContextHandler or derivative_**, the initialize() method must be called manually after start().

And yet a check in `doStart` of `ServletHandler` throws an ISE.:
```
java.lang.IllegalStateException: Cannot use ServletHandler without ServletContextHandler

	at org.eclipse.jetty.ee10.servlet.ServletHandler.doStart(ServletHandler.java:180)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:601)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.Server.doStart(Server.java:542)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at com.example.ServletHandlerTest.test(ServletHandlerTest.java:14)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**How to reproduce?**
```
@Test
void test() throws Exception {
	Server server = new Server(0);
	ServletHandler servletHandler = new ServletHandler();
	server.setHandler(servletHandler);
	server.start();
	// servletHandler.initialize();
}
```

**Comment by joakime** [comment]
This is not a regression.
ServletHandler has always been an internal class, not meant to be used directly. 

Back in the Jetty 6 days this was a valid setup.
In those days, the servlet spec was simpler, and using a ServletHandler without a ServletContext was an easy alternative setup.
But the servlet spec has gotten more complex over time.
Now the initialization phases of the servlet spec require a ServletContext, something a raw ServletHandler does not have.

Jetty 9 was the last version of Jetty to contain documentation and examples showing how to use a raw ServletHandler.
That behavior was removed entirely in the Jetty 10 documentation and examples.

The past desire to have a raw ServletHandler was to avoid using a ServletContext and the mechanisms of Servlet in general.

Now in Jetty 12, with the split of Servlet out from the Jetty core, that desire is now handled by jetty core itself, which is completely free of all Servlet concepts and behaviors.  EE specific behaviors are now in the appropriate `jetty-ee#-servlet` layer.

**Comment by joakime** [comment]
This is not a bug, but a documentation (javadoc) issue that needs to be fixed.

**Comment by joakime** [comment]
Closing as answered
