### ISSUE TITLE
Implement servlet3.1 spec section 2.3.3.5 upgrade processing

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#104]
migrated from Bugzilla [#398468](https://bugs.eclipse.org/bugs/show_bug.cgi?id=398468)
status ASSIGNED severity *enhancement* in component *servlet-3.1* for *9.0.1*
Reported in version *9.0.0* on platform *PC*
Assigned to: Project Inbox

On 2013-01-18 00:51:33 -0500, Jan Bartel wrote:

> See pg. 2-20 of 3.1 spec for details.

On 2013-06-24 00:38:06 -0400, Greg Wilkins wrote:

> Not intended to support in the initial release

**Comment by joakime** [comment]
Commit f2e0a46058934bcdac1f1171def00c57393aea7f disabled `HttpServletRequest.upgrade()`, do you just want to close this issue?

**Comment by janbartel** [comment]
Closing as not supported.
