### ISSUE TITLE
Review deployment of Jetty Context XML files

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10411]
**Jetty version(s)**
12

**Description**
Follow-up issue to #10158, where the deployment of Jetty Context XML files should be able to pick a default environment.
See the comments in #10158, as this should not be resolved by documentation only -- it should work out of the box.

**Comment by gregw** [comment]
Note that currently it does "work out of the box"  for many (most?) deployments that will only have single environment enabled, as that will be the environment used for xml deployments.

If we have multiple deployments than currently we use the "heuristic" of:
1. If there is an env defined in a property file, then use that.
2. else default to the most "senior" environment: core < ee8 < ee9 < ee10

To do something smarter we'd need to do:
1. If there is an env defined in a property file, then use that.
2. inspect the deploy target for a hint of which environment to use
3. else default to the most "senior" environment: core < ee8 < ee9 < ee10

To get the hint we might need:
- to crack open a `WEB-INF/web.xml` to look for which version of EE it is using as it's schema/dtd.  But this only gives the minimal environment and plenty of webapps are deployed in ee9 with earlier ee descriptors
- parse a context.xml looking for the class of the  context.   This will work if they directly use an eeN ContextHandler, but will be difficult if they use their own extended handler.   We may end up having to try environments to see which we can load in?

I'm not sure either of these is robust enough to be worthwhile.

**Comment by gregw** [comment]
Oh I just tested my assumption above that a context.xml would be deployed if we only had a single environment enabled.   Apparently not!     So I think if we fix that, then this will be a lot better.  Looking....

**Comment by sbordet** [comment]
Fixed by #10415.
