### ISSUE TITLE
Returning Trailers from read()?

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10412]
**Jetty Version**
12

**Question**
While writing docs, I wondered why we return `Trailers` from `server.Request.read()` and possibly also in `client.Response` content.

Seems to me that we can always look for EOF, and after that retrieve the trailers via APIs:

`server.Request.getTrailers()`
`client.Response.getTrailers()`.

It would be nicer to avoid people doing `instanceof Trailers`.

Thoughts?

**Comment by gregw** [comment]
I recall the conversation was about when we wrap `Content.Source`.  If there are multiple APIs that can deliver events, then wrapping becomes more difficult.   If read() is the sole source of events: data, errors, trailers, then all we need do is have a single notification of "hey there is something to read" and then the app calls `read()` and finds out what it is.   I do like this simplicity as if we are wrapping a source we do not need to check multiple APIs to see how the stream ended.

The doubts I have is once we have returned a Trailers EOF chunk, should we be able to read that again?  Currently I think the next read returns a normal last EOF, which is unlike how we end with a failure, as once you get a last failure you always get the same failure on the next read.  So it  is kind of strange that for Trailers, last is true but we return something different on the next read.

If we were to keep returning the Tailers chunk on all subsequent reads, then we could have a utility method that did something like:
```java
    static HttpFields getTrailers(Content.Source source)
    {
        Content.Chunk chunk = source.read();
        if (chunk.hasRemaining() || !chunk.isLast())
        {
            chunk.release();
            throw new IllegalStateException("not at EOF");
        }
        if (chunk instanceof Trailers trailers)
            return trailers.getTrailers();
        return null;
    }
```
You could then always read to a last chunk and then call this API to get the trailers.....  but I don't think it is much better.

**Comment by sbordet** [comment]
Ok, in light of `Content.Source` APIs I agree that returning `Trailers` is the right thing.
Users of the `Content.Source` will just see it as EOF.

Within the context of a `Request` it may be handled there with an `instanceof`, or seen as a EOF, and after that applications can call `Request.getTrailers()`.

I don't think we need the static method, all good as it is.
