### ISSUE TITLE
Docs: Jetty 12 Operations Guide shows exception for virtual threads example jetty output

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse/jetty.project#10445]
**Description**

Take a look at 

https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-server-threadpool-virtual

I don't think the exception should be in the code block. It should show jetty startup output when using virtual threads

**Comment by sbordet** [comment]
Thanks, yes, we will update the documentation on the website today for 12.0.1, and that error should be gone.

**Comment by joakime** [comment]
We had to rebuild the 12.0.1 docs manually (post-release) due to a bug in our release build

* #10449

Stay tuned, we are working on updating the website for all of the releases this past week (9.4.52, 10.0.16, 11.0.16, and 12.0.1)

**Comment by sbordet** [comment]
The release profile now enforces Java 21, so this issue should be fixed.
