### ISSUE TITLE
Review HTTP session documentation

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10466]
**Jetty version(s)**
12

**Description**
The HTTP session documentation in the programming guide needs a review.

* Drop references to eeN or Servlets, everything should be explained in terms of core only
* Verify that the class diagrams are still up to date
* Verify that configuration of the various elements is still valid (properties, setter methods, etc.)
* Review the prose in light of Jetty 12.

**Comment by sbordet** [comment]
@janbartel I added a short introduction as `server-http-session.adoc` that links to the existing comprehensive documentation.

Happy to do it in your place (so I'll learn more about sessions), let me know.

**Comment by janbartel** [comment]
@sbordet on it

**Comment by janbartel** [comment]
Updates to session documentation committed via #10497. Probably a little more to do on this, so leaving this issue open.
