### ISSUE TITLE
Update Jetty 12 MANIFEST's Bundle-Copyright

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10475]
**Jetty version(s)**
12

**Description**
Jetty 12 jars have the following attribute in their `MANIFEST.MF` files:

```
Bundle-Copyright: Copyright (c) 2008-2021 Mort Bay Consulting Pty Ltd an
 d others.
```

That was for `jetty-client-12.0.1.jar`.

It has a range (I think should be the same as the sources. i.e. no range), and the inception year is weird (2008 vs 1995).

**Comment by janbartel** [comment]
Fixed via #10531
