### ISSUE TITLE
Clarify documentation about how to make a non-blocking handler tree

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10484]
**Jetty version(s)**
12.0.x

**Enhancement Description**
Since 12, the Core API allows writing entirely non-blocking handlers by extending `Handler.Abstract.NonBlocking` that are executed by the `AdaptiveExecutionStrategy`'s `ProduceConsume` sub-strategy.

Currently, the documentation mentions this fact but the information is scattered across many chapters. It also doesn't mention the fact that the entire handler tree has to be non-blocking, nor common pitfalls like the fact that `ContextHandlerCollection` is dynamic by default, which prevents it from being non-blocking.

This should be clarified.

**Comment by sbordet** [comment]
Fixed by #10934.
