### ISSUE TITLE
https support for jetty server

### ISSUE THREAD

**Issue by viragpurnam** [eclipse/jetty.project#10491]
**Jetty Version** : 10.0.12

**Java Version**: JDK-17

**Question**: I am using below plugin in pom.xml and I am using **mvn p2:site** and **mvn jetty:run**. It works fine with http://localhost:8080 but now with latest Eclipse we can not use http url. We have to use https. Can we run jetty that supports https url? How to configure that? Could you please help me?

                           <plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>${jetty-maven-plugin.version}</version>
				<configuration>
					<webAppSourceDirectory>${basedir}/target/repository/</webAppSourceDirectory>
					<webApp>
						<contextPath>/site</contextPath>
					</webApp>
					<httpConnector>
						<port>8080</port>
					</httpConnector>
				</configuration>
			</plugin>

**Comment by janbartel** [comment]
Can you clarify what you are asking? How are you running Jetty "with Eclipse"? Are you deploying the jetty bundles into the Eclipse OSGi container and using Jetty's OSGi support classes, or are you coding your own embedded Jetty setup or something else? Or are you asking how to use https with jetty-maven-plugin?

**Comment by viragpurnam** [comment]
Hi @janbartel,

I am creating a local p2 repository for my maven project using jetty. (**http**://localhost:8080/site). I am using this url for eclipse target platform. As we have http, latest eclipse throws error and suggest to use https. 
I want to use https with jetty-maven-plugin, so the url will be like **https**://localhost:8080/site. 
Could you please guide me how to achieve this?

Thanks and regards,
Virag

**Comment by janbartel** [comment]
If you see the jetty maven plugin documentation here: https://eclipse.dev/jetty/documentation/jetty-10/programming-guide/index.html#deployment-modes, it tells you that you need to configure a https connector using jetty xml configuration files. Those configuration files should be based on the xml config files that are used by the `https` module. Then set the comma separated list of those xml files as arg to the `jettyXmls` configuration parameter.

**Comment by viragpurnam** [comment]
Thanks, I will try with https connectors.

**Comment by olamy** [comment]
@viragpurnam please re open if you still have questions
