### ISSUE TITLE
Jetty 12 Jakarta Websockets user principal is always null

### ISSUE THREAD

**Issue by uhrm** [eclipse/jetty.project#10490]
**Jetty version(s)**
Tested with Jetty 12.0.1

**Jetty Environment**
Jetty 12, EE10

**Java version/vendor** `(use: java -version)`
openjdk 19 2022-09-20
OpenJDK Runtime Environment Zulu19.28+81-CA (build 19+36)
OpenJDK 64-Bit Server VM Zulu19.28+81-CA (build 19+36, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
When using Jakarta websockets with Jetty, the current implementation of `Session.getUserPrincipal()`
returns `null` even when the HTTP upgrade request is authenticated (see
[JakartaServerUpgradeRequest.java (line 36)](https://github.com/eclipse/jetty.project/blob/476874584943daf3041eb0ca584d4de3a87f19fd/jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaServerUpgradeRequest.java#L36)

This prevents us from upgradeing to Jetty 12 since we rely on authenticated requests to be able to
identify the user.

I guess the implementation would be relatively easy. Maybe it would be enough to
```java
return AuthenticationState.getUserPrincipal(this.servletRequest);
```
or use machinery analogous to [ServletApiRequest](https://github.com/eclipse/jetty.project/blob/jetty-12.0.1/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java).

**Comment by lachlan-roberts** [comment]
Will be fixed in `12.0.2`.
