### ISSUE TITLE
How to set local address while sending Request to server

### ISSUE THREAD

**Issue by navalgoyal** [eclipse/jetty.project#10496]
**Jetty Version**
jetty-10.0.15

**Java Version**
java 17.0.6

**Question**
How to set local address and local port while sending request from Jetty Client. is there any way??

**Comment by olamy** [comment]
there is no much details here.
are you using embedded or distribution?
by the way version 9.4.x is now End of Community Support  https://github.com/eclipse/jetty.project/issues/7958

**Comment by navalgoyal** [comment]
we are using embedded version

**Comment by navalgoyal** [comment]
we have client which we run inside kubernetes pod. by default request going out from client takes pod id and local random port. we want to fix this local port by passing when sending request. 

Connection should be created using the local port we provided.

**Comment by navalgoyal** [comment]
@olamy any comment??

**Comment by sbordet** [comment]
@navalgoyal please update your Jetty version.

What you want is possible, but you need to use the PROXY protocol in both client and server.

There is an example in the test cases here:
https://github.com/eclipse/jetty.project/blob/jetty-12.0.1/jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientProxyProtocolTest.java#L95

We need to document this.

**Comment by navalgoyal** [comment]
@sbordet Thanks for the response... i will try and let you know..

**Comment by navalgoyal** [comment]
Hi @sbordet as per your example we need to create a Proxy Server before starting the client connection. The client will connect to this proxy server which will further relay the request to the destination?

is this understanding correct??

**Comment by sbordet** [comment]
You don't need a proxy server.
You just need the server to support the PROXY protocol.
If the server is Jetty, see https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-connector-protocol-proxy-http11

**Comment by joakime** [comment]
It is not possible to run Jetty 10 with Java 8 btw.

**Comment by navalgoyal** [comment]
@sbordet we are using embedded client which we are running inside kubernetes pod. by default, client send request using pod ip and arbitrary local port. we don't want to send pod ip in the tcp packet. we have service which return static ip and that service provided port which can be used as local port for request. 

we want to configure that ip and port when sending request from jetty client.

what changes we need to do in the client if we want to achieve the above usecase??

@joakime we are using java 17.0.6 to run jetty 10

**Comment by joakime** [comment]
> @joakime we are using java 17.0.6 to run jetty 10

I'll update the question details then.

**Comment by sbordet** [comment]
@navalgoyal you cannot change the IP/port of a TCP packet unless you use OS tools to do that.

Therefore you must do it at the application level.

The PROXY protocol does exactly this, it is a standard that is used by all proxies and load balancers products.

The example I linked shows how to configure the PROXY protocol on the client and on the server.
Do the same in your code, and your problem is solved.

**Comment by joakime** [comment]
> @sbordet we are using embedded client which we are running inside kubernetes pod. by default, client send request using pod ip and arbitrary local port. we don't want to send pod ip in the tcp packet. we have service which return static ip and that service provided port which can be used as local port for request.
> 
> we want to configure that ip and port when sending request from jetty client.

Does your kubernetes pod have multiple network interfaces that the client can use to initiate the outgoing connection? (and what you are actually asking is how to use a specific interface to initiate the client connection on)

**Comment by navalgoyal** [comment]
@joakime yes we can add multiple network interface inside pod which client can use for outgoing connection. we use that service to get the local port which can be used by client when connection is initiated with server.  Client bind that port as src port when sending request to the server.

we used similar way for different protocol where we are passing that port when binding connection with server. below are the code snippet:

stackConfiguration.addPeer( uri, port , peer.getConnectAddress() );

here uri is server uri
port – The local port to use for communicating
connect address is the ip of the server.

can be do in similar way in jetty client??

**Comment by sbordet** [comment]
@navalgoyal have you already tried `HttpClient.setBindAddress()`?

Frankly, I do not understand what you are trying to do.
For a server to require that client connection come from a specific port seems... weird.

Can you make a clear example with IP and port numbers of what you have now and what you are trying to achieve instead?

**Comment by navalgoyal** [comment]
@sbordet We are able to run using setBindAddress...

Thanks for the help..
