### ISSUE TITLE
Use of Path to set up webapp context

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#105]
migrated from Bugzilla [#398997](https://bugs.eclipse.org/bugs/show_bug.cgi?id=398997)
status ASSIGNED severity *enhancement* in component *server* for *9.0.x*
Reported in version *9.0.0* on platform *All*
Assigned to: Project Inbox

On 2013-01-24 12:24:24 -0500, Haralds Ulmanis wrote:

> In java 7 it is possible to implement own file systems and when using Path - it is possible to reference folders/files in such.
> Use cases: Files can be stored somewhere in databases and changed centralized on fly. That would add some freedom on multi-node site setups.

On 2013-01-24 17:34:23 -0500, Greg Wilkins wrote:

> Jetty has a Resource abstraction that hides if the resource is a File or URL.   It should be relatively easy to come up with a PathResource class that uses a Path file system as the backing store.
> 
> Unfortunately we are flat out getting 9 out the door without taking on such new functionality ourselves.    However we would be very much interested in helping somebody contribute such a feature or sponsoring its development

On 2013-01-25 11:53:26 -0500, Haralds Ulmanis wrote:

> It looks kind a simple actually. 
> I'll give a try next week.

On 2013-01-31 05:49:35 -0500, Haralds Ulmanis wrote:

> So, i did simple implementation with Path. It works with standard file system where file:// is prefix. If we speak about custom FS with some other prefix like fs1:// etc. It does not work anymore .. URL complains about unknown protocol, Methods like: 
> makeTempDirectory(new File(System.getProperty("java.io.tmpdir")),context,true); also will not work. Even Path is wrapped with resource old java Methods does not work with it.
> 
> First probably I need to remove old io stuff and replcae with Files, Path etc., maybe diffetent implementation of Resource, replace URL with URI. It will take a more time that expected.

On 2013-01-31 06:45:15 -0500, Haralds Ulmanis wrote:

> Btw, maybe someone have idea how to make unified resource.
> What i see,
> I did not find a straight way to use Path with URL. It means, that there should/can be two method sets (if we want to keep URL).  One which will work with Path (any file system) and one which works with network resource URL.
> Or ... implement filesystem with URL base. And then everything would work with Path. :)

On 2013-01-31 17:10:06 -0500, Greg Wilkins wrote:

> I was thinking that you would make PathResource extend Resource and not URLResource, to avoid the issues with URL conflicts etc.....  or are you saying it is some other URL that is complaining about unknown protocol.
> 
> Perhaps put you code up on github and we can both have a look?

On 2013-02-05 05:41:07 -0500, Haralds Ulmanis wrote:

> I'll try shortly to describe there.
> So We have Resource class which to extend, where i added static method 
>  public static Resource newResource(Path path) throws IOException {
>         return new PathResource(path);
>     }
> to support PathResource.
> 
> and 
> public class PathResource extends Resource {}
> 
> The problem is Resource method 
>  public abstract URL getURL();
> which I need to implement (not URI). And that method getURL is used inside other code, like:
> XmlConfiguration xmlc = new XmlConfiguration(resource.getURL());
> BufferedReader br = new BufferedReader(new InputStreamReader(r.addPath(path).getURL().openStream()));
> etc.
> So that method is used in many places in code. It will work fine with file, http etc. protocols which are supported by URL. 
> 
> I've custom FS like:
> public class CasFSProvider extends FileSystemProvider { ... }
> with 
> 	@Override
> 	public String getScheme() {
> 		return "cas";
> 	}
> 
> in general my uri looks like: cas:/path/path/file.ext
> When I try to convert URI to URL, I got exception regarding unknown protocol.
> 
> What i think. To make it compatible in future with any kind of protocols (and custom ones), getURL probably needs to be replaced with general getURI.
> 
> Regards,
> Haralds

On 2013-02-06 13:55:18 -0500, Haralds Ulmanis wrote:

> I went through code and inspected .getURL uses. 
> The most common use is to resource.getURL() and then open it again with different method.. something like:
>  XmlConfiguration xmlc = new XmlConfiguration(resource.getURL());
> ->
>    public XmlConfiguration(URL configuration) throws SAXException, IOException
>     {
>         synchronized (__parser)
>         {
>             _url=configuration;
>             setConfig(__parser.parse(configuration.toString()));
>             _dtd=__parser.getDTD();
>         }
>     }
> -> there is conversion configuration.toString
> 
> and .parse methods:
> public synchronized Node parse(InputSource source) throws IOException, SAXException
> public synchronized Node parse(String url) throws IOException, SAXException
> public synchronized Node parse(File file) throws IOException, SAXException
> public synchronized Node parse(InputStream in) throws IOException, SAXException
> 
> Actually if we have Resource abstraction then extra converts like .getUrl.toString is not needed.
> We need to pass Resource as general resource. and in that case ... it would look like
> XmlConfiguration xmlc = new XmlConfiguration(resource);
> 
> public XmlConfiguration(resource) throws SAXException, IOException{
> ....
> setConfig(__parser.parse(resource)); or setConfig(__parser.parse(resource.getInputStream()))
> ....}
> in case of resource ...
> public synchronized Node parse(Resource resource) throws IOException, SAXException {
> return parse(resource.getInputStream); }
> 
> Not sure when, but i could try to set up workspace and try just to remove .getURL and rewrite places where it is used, rather than doing full scale redesign of Resource as it is now.

On 2013-02-07 14:29:17 -0500, Haralds Ulmanis wrote:

> It will take more time than I though initially. 
> as this:
> _classLoader=new URLClassLoader(paths);
> will not work .. and there is no such URI class loader. 
> And other implementations (URIClassLoader) I found already, takes URI and converts to URL. So it means probably there is a need to write new ClassLoader.

On 2013-11-28 20:16:31 -0500, Jan Bartel wrote:

> Haralds,
> 
> Sounds like you needed to add a URLStreamHandler for the cas:// protocol. 
> 
> See http://docs.oracle.com/javase/7/docs/api/java/net/URL.html#URL%28java.lang.String,%20java.lang.String,%20int,%20java.lang.String%29
> 
> Jan
> 
> (In reply to Haralds Ulmanis from comment # 6)
> > I'll try shortly to describe there.
> > So We have Resource class which to extend, where i added static method 
> >  public static Resource newResource(Path path) throws IOException {
> >         return new PathResource(path);
> >     }
> > to support PathResource.
> > 
> > and 
> > public class PathResource extends Resource {}
> > 
> > The problem is Resource method 
> >  public abstract URL getURL();
> > which I need to implement (not URI). And that method getURL is used inside
> > other code, like:
> > XmlConfiguration xmlc = new XmlConfiguration(resource.getURL());
> > BufferedReader br = new BufferedReader(new
> > InputStreamReader(r.addPath(path).getURL().openStream()));
> > etc.
> > So that method is used in many places in code. It will work fine with file,
> > http etc. protocols which are supported by URL. 
> > 
> > I've custom FS like:
> > public class CasFSProvider extends FileSystemProvider { ... }
> > with 
> > 	@Override
> > 	public String getScheme() {
> > 		return "cas";
> > 	}
> > 
> > in general my uri looks like: cas:/path/path/file.ext
> > When I try to convert URI to URL, I got exception regarding unknown protocol.
> > 
> > What i think. To make it compatible in future with any kind of protocols
> > (and custom ones), getURL probably needs to be replaced with general getURI.
> > 
> > Regards,
> > Haralds

**Comment by joakime** [comment]
The original bug for this asked for support of Path in WebAppContext.

Now that we have PathResource, we can accomplish this.
Closing as fixed.
