### ISSUE TITLE
Jetty 12 IllegalArgumentExeption when setting a HTTP header to null

### ISSUE THREAD

**Issue by ekupcik** [eclipse/jetty.project#10508]
**Jetty version(s)**
12.0.1

**Description**
In jetty 12.0.1 calling HttpServletResponse.addHeader("name", null) throws an IllegalArgumentException

java.lang.IllegalArgumentException: null value
	at org.eclipse.jetty.http.HttpFields$Mutable.add(HttpFields.java:901) ~[?:?]
	at org.eclipse.jetty.ee10.servlet.ServletApiResponse.addHeader(ServletApiResponse.java:217) ~[?:?]

This used to work till 12.0.0 in Jetty, works in Tomcat and i also found this description https://github.com/jakartaee/servlet/issues/159 This seems to be a regression

**Comment by joakime** [comment]
When you use `HttpServletResponse.addHeader(name, value)` you are adding a value to a list of values for a header.

Using `HttpServletResponse.addHeader("X-Foo", null)` would attempt to add a null value to the list of values to the header `X-Foo`.
That's invalid, hence the `IllegalArgumentException`

Note: If you had used `HttpServletResponse.setHeader("X-Foo", null)` then you are essentially removing that header (you are setting the header to have no value or values, which eliminates it)

**Comment by joakime** [comment]
The linked spec issue https://github.com/jakartaee/servlet/issues/159  is about `setHeader()` not `addHeader()` btw.

**Comment by joakime** [comment]
The javadoc for the various setHeader / addHeader (and variants) calls out behavior when nulls are passed as parameters.

PR incoming.

**Comment by joakime** [comment]
Opened PR #10510 to address this

**Comment by janbartel** [comment]
Fixed via #10510
