### ISSUE TITLE
NCSARequestLog/RolloverFileOutputStream does not roll day after DST ends

### ISSUE THREAD

**Issue by kaaveland** [eclipse/jetty.project#1051]
Hey,

This line makes the assumption that a day is always 24 hours long, which is right almost every day of the year:
https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java#L185 

In its constructor, this class calculates the next midnight (eg. 00:00 Saturday October 29th) and schedules a `setFile` call to happen at that time and every 24 hours thereafter (00:00 Sunday October 30th). However, when DST ends, there's a 25 hour day, so `setFile` will happen 1 hour before midnight (23:00 Sunday October 30th). This causes `RolloverFileOutputStream` to calculate the same filename as it had already opened (https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java#L230) and decide to not do a rollover.

For us, that was problematic because the logrotate script compressed and deleted that file a few hours later, but jetty was still writing access-log to it through NCSARequestLog. Apparently, writing to a file that is gone is fine, what happens on our linux-system is that jetty successfully writes, but the log ends up nowhere (I might be able to retrieve it with some lsof and /proc hackery if I really wanted to). If we had restarted our application yesterday, everything would've been fine as RolloverFileOutputStream would recalculate midnight instead of just ticking on a fixed 24 hour schedule.

As far as I can tell, it would be safe to have this task on a 1-hour schedule (instead of the 24 hour one), which would fix the issue. Another option would be for each "tick" of the task to calculate the next midnight, instead of just assuming that there are always 24 hours between each midnight (which is wrong twice a year in our timezone).

I'll work around this in our logrotate setup, but we'll still end up with log files containing "the wrong" data, eg. next year, when DST ends, we'll have one log file containing two days worth of log (which I can live with). So it would be nice to have a fix for this.

**Comment by joakime** [comment]
Sounds like an annoying bug (tough to test too!).

Meanwhile, You can use the [`Slf4jRequestLog`](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/Slf4jRequestLog.html) implementation and route your access logs to a more capable logging infrastructure.

**Comment by kaaveland** [comment]
Thanks, that's a great idea. :-)

**Comment by gregw** [comment]
@Joakim (or anybody else listening),
want to have a go at updating RolloverFileOutputStream? It is an ancient class, probably from java 1.2 and there are probably a lot better techniques and utility classes it could use now.     I think the aim would be to simplify and correct the class - not to significantly enhance it (ie no size rollovers etc.) as we still want to defer to other logging mechanisms for anything more sophisticated than simple roll over!

**Comment by joakime** [comment]
@gregw i'll take a stab at fixing RolloverFileOutputStream for just the rollover bit.
