### ISSUE TITLE
Disable maven build cache during release

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10534]
**Jetty version(s)**
12

**Jetty Environment**
All

**Java version/vendor** `(use: java -version)`
21

**OS type/version**
Linux

**Description**
During a release (when the `-Peclipse-release` profile is active), I would like to disable the Maven Build Cache.

The problem is that the `deploy` stage goals are cached, and that prevents both re-upload and alternate distribution repository scenarios

**Comment by joakime** [comment]
@olamy I added this commit https://github.com/eclipse/jetty.project/pull/10532/commits/1f7bbe660ee544989eaa75584058138ae557499e to PR #10532, you ok with this just being default behavior?

**Comment by olamy** [comment]
better to disable the cache entirely in the profile with 
```
  <properties>
    <maven.build.cache.enabled>false</maven.build.cache.enabled>
  </properties>

```
I have added on purpose the property `-Dmaven.build.cache.enabled=false` in the release-jetty.sh. (so maybe not using the script ;) .

**Comment by olamy** [comment]
done
