### ISSUE TITLE
Call to org.eclipse.jetty.server.Request.getRemoteAddr gives IncompatibleClassChangeError

### ISSUE THREAD

**Issue by kolstae** [eclipse/jetty.project#10536]
**Jetty version(s)**
12.0.1

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
```
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)
```

**OS type/version**
```
Linux eak-ardoq 6.5.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 x86_64 GNU/Linux
```

**Description**

Call `org.eclipse.jetty.server.Request.getRemoteAddr(request)` where `request` is an instance of `org.eclipse.jetty.server.handler.ContextRequest` gives:
```
java.lang.IncompatibleClassChangeError: Method 'java.lang.String org.eclipse.jetty.server.Request.getRemoteAddr(org.eclipse.jetty.server.Request)' must be InterfaceMethodref constant
```
Calls to `org.eclipse.jetty.server.Request.getServerName(request)` and `org.eclipse.jetty.server.Request.getServerPort(request)` fails in the same way.
As well as a call to `org.eclipse.jetty.io.Content$Source.asInputStream` on an instance of `org.eclipse.jetty.server.handler.ContextResponse`

**How to reproduce?**

Setup a `ContextHandler` with a `Handler` that calls `org.eclipse.jetty.server.Request.getRemoteAddr` on it's request

**Comment by olamy** [comment]
We need more details on the dependencies you are using.
A reproducer project will be great.

**Comment by kolstae** [comment]
I'm sorry this was due to my other libraries.
