### ISSUE TITLE
Re-introduce a more complete set of stats in `StatisticsHandler`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10555]
**Jetty version(s)**
12.0.1

**Enhancement Description**
In Jetty 10/11, `StatisticsHandler` used to expose more of the internals than Jetty 12 currently does. Here is a list of such stats available on 10/11 and absent from 12:

```
getStatsOnMs()
getDispatchedActive()
getDispatched()
getDispatchedActiveMax()
getDispatchedTimeTotal()
getDispatchedTimeMax()
getDispatchedTimeMean()
getDispatchedTimeStdDev()
getExpires()
getAsyncDispatches()
getAsyncRequestsWaiting()
```

Those should be re-implemented as they were or eventually revisited if the changes between 10/11 and 12 necessitate slightly different stats.

**Comment by jluehe** [comment]
Thank you, @lorban!
