### ISSUE TITLE
Update quiche to 0.18.0

### ISSUE THREAD

**Issue by zugazagoitia** [eclipse/jetty.project#10557]
The last update was in #8695, now 0.18.0 has been released.
It introduces some "breaking" changes that shouldn't affect the final user much.

https://github.com/cloudflare/quiche/releases/tag/0.18.0

**Comment by lorban** [comment]
Here are  the changes made to the `quiche.h` C header since our last update: https://github.com/cloudflare/quiche/compare/0.16.0...0.18.0#diff-8677002d221c3e20ec05af5a64f7125a501aade052ab378600fcc3b0a3148c91

No breaking change indeed, so updating to version 0.18.0 should be pretty straightforward.

**Comment by joakime** [comment]
@lorban jetty-quiche-native update to 0.18.0 exists in PR https://github.com/jetty-project/jetty-quiche-native/pull/66

**Comment by lorban** [comment]
@joakime Once `jetty-quiche-native` version 0.18.0 has been released, we can update the dependency in Jetty 10, do the few extra changes needed and merge forward.

**Comment by lorban** [comment]
Fixed in 10.0.x and merged to 11.0.x and 12.0.x.

**Comment by zugazagoitia** [comment]
Swift release, thank you very much!

Let's hope the JDK team invest a little of their time in implementing the protocol natively on Java.
