### ISSUE TITLE
increasing p99.9(response time) in Jetty Http Client

### ISSUE THREAD

**Issue by kjhunjhunwala** [eclipse/jetty.project#10567]
**Jetty Version**
9.4.49.v20220914
**Jetty Environment**

**Java Version**
Java 11
**Question**
We are using jetty http client with below configuration in sync mode
httpClient = new HttpClient();
        httpClient.setConnectTimeout(10000);
        httpClient.setIdleTimeout(10000);
        httpClient.setMaxConnectionsPerDestination(25);
        httpClient.start();

method call 
response = request.send();

TPS : 80 

We are observing a pattern where the p99.9(response time) keeps on increasing from 3ms-15ms and drops after a while and the pattern continues. p99 is stable. 
Downsteam service's p99.9 is constant at 1ms. 

<img width="1546" alt="image" src="https://github.com/eclipse/jetty.project/assets/107423719/86da27d9-6ffe-432d-aaf9-1ebac8720d6e">

What could be the issue here?

**Comment by sbordet** [comment]
Jetty 9.4.x is at end of community support, you should update to Jetty 12, see #7958.

Seems a pattern similar to that of a GC.

Did you monitor the GC and found that the p99.9 curve follows the GC curve?

Also, using blocking calls is the wrong way to do benchmarks that measure latency.

**Comment by sbordet** [comment]
Closing as answered, and no reply from OP.
