### ISSUE TITLE
`ConcurrentPool` should not use the thread-local cache when running on a virtual thread

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10568]
**Jetty version(s)**
12.0.x

**Enhancement Description**
`ConcurrentPool` has a thread-local cache that can be optionally enabled to increase the pool's performance for certain kinds of pooled objects. But this is counter-productive when the thread is a virtual one, so the pool should avoid using the cache in that case.

**Comment by lorban** [comment]
Recent benchmarks have shown that for Jetty 12, the concurrent pool's thread local cache tends to lower the performance when combined with the THREAD_ID strategy, which is the only time where the cache is enabled.

So it looks like the thread local cache should be removed, which would sort this issue out as a side effect.

**Comment by gregw** [comment]
THREAD_ID strategy is essentially a threadlocal hash anyway.

**Comment by gregw** [comment]
See fix in #11504

**Comment by lorban** [comment]
@gregw We already removed the thread local from `ConcurrentPool` as part of https://github.com/jetty/jetty.project/pull/10787 and deprecated the constructors that refer to it so I think we can close this issue.
