### ISSUE TITLE
Improve Request.getCookies() performance

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1056]
We are using a per-connection Trie to hold headers so that they are not parsed again.

However, we don't use a Trie for cookie instances, so that every time a request comes with the same cookies we need to parse them again and again to convert them from string to `javax.servlet.http.Cookie` instances.

We should apply a similar optimization: using a Trie to hold `Cookie` instances given a raw string.

**Comment by gregw** [comment]
Note that it could be a little more costly to do this as Cookies may come in multiple header fields and each may be coma separated.    Thus any key to a cache is a List<String> and not just a String, so it may be more costly to calculate and check.

Also what should the scope and size of the cache be?

A size of 1 will work perfectly for most connections, unless they are from an aggregating front end.

The scope could be the connection, which would work for different transports. Or it could be just the channel, which would then only work for recycling channel connections (HTTP/1)

**Comment by sbordet** [comment]
We want to optimize the common case, so cache size of 1-2 would work, and caching only the first cookie header, perhaps... Unless `HttpHeaders` coalesces multiple headers into a raw string ?

**Comment by joakime** [comment]
*bump*  is this still and issue? (over 2 years old now)

**Comment by gregw** [comment]
The CookieCutter class already has a cache of cookies in the CookieCutter, which works for Request objects recycled within a connection.   This is fine for HTTP1, but doesn't work for h2 as the HttpChannel is not recycled.    I think we'd be better off working out how to recycle the HttpChannel in h2 and leaving this cache as is
