### ISSUE TITLE
Connection rejected: No ALPN Processor

### ISSUE THREAD

**Issue by mdu39170** [eclipse/jetty.project#10561]
Hi,
**Jetty version(s)**
jetty 11.0.15

**Jetty Environment**
jetty embeded into javalin

**Java version/vendor** `(use: java -version)`
openjdk version "19.0.2" 2023-01-17

**OS type/version**
 Ubuntu 22.04.3 LTS 

**Description**
I use jetty through javalin. 
i realised a embedded jar file with shadow. 
when i run it on windows, all it's ok, but, when i run it on ubuntu server and requested a endpoint, i obtain a error message with the ALPN Processor :
`2023-09-20 14:55:32.286 WARN  [org.eclipse.jetty.io.ManagedSelector]:904 - Could not accept java.nio.channels.SocketChannel[closed]: java.lang.IllegalStateException: Connection rejected: No ALPN Processor for sun.security.ssl.SSLEngineImpl from [org.eclipse.jetty.alpn.conscrypt.server.ConscryptServerALPNProcessor@58489899] `

**How to reproduce?**
run it on linux an request a endpoint.

thanks

**Comment by sbordet** [comment]
Please check that you have shadowed in the proper way.
It is common to shadow and miss `/META-INF/services/*` files.

**Comment by mdu39170** [comment]
the files are present :
![image](https://github.com/eclipse/jetty.project/assets/135130147/70cb68b7-162a-4507-bb74-2589050f9c78)

**Comment by sbordet** [comment]
They may be present, but not have the right names or the right values inside because you shaded, but you have not provided enough information to help you.

Look, Javalin works with Jetty and there are a lot of users that don't get the exceptions you are getting.
Therefore, it is very likely that you are doing something wrong. 
I would double check what you are doing.

Does it work if you do not shade?

**Comment by mdu39170** [comment]
If the problem came from shadow, would it even occur under Windows 11? 
However, I have no problem with this archive on Windows...
What do you think ?

**Comment by sbordet** [comment]
Does it work if you don't shade?

**Comment by mdu39170** [comment]
it's run without shadowJar...

**Comment by joakime** [comment]
The default implementation of gradle's shadowJar is often enough, but you have to be careful to merge some services file and not others.

Example: `org.eclipse.jetty.http.HttpFieldPreEncoder` and `jakarta.servlet.ServletContainerInitializer` often have multiple entries in them.
But `org.slf4j.spi.SLF4JServiceProvider` MUST have only have 1 entry.
Go check these in your jar.
If they all have multiple entries, then you have to adjust your dependencies.
If they all have 1 entry, then your shadowJar configuration is not merging services files properly.

How to fix this? Some people configure shadowJar behavior to behave correctly, others adjust their dependencies to give shadowJar only what's needed.

**Comment by sbordet** [comment]
Closing as it is likely a problem in shading the services files.
