### ISSUE TITLE
Improve WebSocketUpgradeFilter fast path performance

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1057]
`WebSocketUpgradeFilter` performs check to see if the request is an upgrade request.

Since these checks always happen, even if the request is a plain HTTP POST request, they should be stripped down at minimum, and the "fast path" in case of no upgrade should be made as terse as possible, and possibly without allocation.

**Comment by joakime** [comment]
Implemented in jetty-9.2.x - merged up to 9.3 -> 9.4 -> master
