### ISSUE TITLE
ReferrerPushStrategy should cache based on user-agent

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#106]
migrated from Bugzilla [#399774](https://bugs.eclipse.org/bugs/show_bug.cgi?id=399774)
status ASSIGNED severity *enhancement* in component *http2* for *9.3.x*
Reported in version *9.2.10* on platform *PC*
Assigned to: Project Inbox

On 2013-02-02 11:54:39 -0500, Simone Bordet wrote:

> Currently, ReferrerPushStrategy creates resource dependencies based on the Referer header only.
> 
> In case a website does user-agent sniffing to provide different resources based on the user agent, the resource dependencies may be built for e.g. a desktop browser and pushed to a mobile browser.

On 2015-04-01 18:07:45 -0400, Greg Wilkins wrote:

> Consider for http2?

**Comment by sbordet** [comment]
For HTTP/2 the mechanism for pushing has been made more external (a servlet filter) and as such application can configure it, override it or even rewrite it more easily.
Requirements for a real website are probably very peculiar to each website, so perhaps a generic mechanism for caching based on user agent could not be that important.
