### ISSUE TITLE
Where is JavaDoc for Jetty12 ???

### ISSUE THREAD

**Issue by minduch** [eclipse/jetty.project#10604]
**Jetty version(s)**
Jetty 12

**Jetty Environment**
Any.

**Java version/vendor** `(use: java -version)`
Any.

**OS type/version**
Any.

**Description**
Where is the JavaDoc of the Jetty 12 API? Jetty 9 to 11 can be found in various places, but the REAL JavaDoc of Jetty 12 cannot be found ANYWHERE on the web. The links pointing to JavaDoc's are only pointing to some client Java programming examples of WebSockets or Http(X) clients.

**Comment by minduch** [comment]
in addition, I would like to add that samples and Jetty 12 documentation relating to e.g. how to use HTTP client and WebSocket are generally not Jetty 12, but rather Jetty 11 with a different namespace "javax..." instead of "jakarta...". Please help me out here with the links, I cannot find anywhere online the JavaDoc of all of Jetty 12 API's!

**Comment by joakime** [comment]
It is supposed to be at https://eclipse.dev/jetty/javadoc/jetty-12/index.html?overview-summary.html

But due to a bug in the release (#10449) it is not available right now.
The 12.0.2 release should fix things.

Meanwhile, go to javadoc.io and you can find the javadoc there.
Eg: https://javadoc.io/doc/org.eclipse.jetty/jetty-http/latest/org.eclipse.jetty.http/module-summary.html

**Comment by joakime** [comment]
The Jetty 12 Programming Guide has examples for what you need.

* [Async HTTP Client Doc](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-client-http)
* [HTTP2 Client Docs](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-client-http2)
* [HTTP3 Client Docs](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-client-http3)
* [WebSocket Client Docs](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-client-websocket)

**Comment by minduch** [comment]
> It is supposed to be at https://eclipse.dev/jetty/javadoc/jetty-12/index.html?overview-summary.html
> 
> But due to a bug in the release (#10449) it is not available right now. The 12.0.2 release should fix things.
> 
> Meanwhile, go to javadoc.io and you can find the javadoc there. Eg: https://javadoc.io/doc/org.eclipse.jetty/jetty-http/latest/org.eclipse.jetty.http/module-summary.html

Yes, the JavaDoc for Jetty 12.0.2 is there, but not Jetty 12.0.3 (the latest).

**Comment by olamy** [comment]
We are currently working on fixing some issues with the website (including the aggregated javadoc).

**Comment by joakime** [comment]
Closing, as latest javadoc has been present for several versions now.
