### ISSUE TITLE
Non-native WatchService sleep defaulting to 5 sec

### ISSUE THREAD

**Issue by visvadw** [eclipse/jetty.project#1061]
Hello,

Although I couldn't find (yet) any info about Java 9's WatchService having a consistent behaviour, have you considered updating the [PathWatcher sleep to 5 sec on OSX](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java#L1431) ?

As a workaround, [directory-watcher](https://github.com/takari/directory-watcher) covers it.

Thanks.

**Comment by joakime** [comment]
OSX has no native watchservice (yet).

http://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else/11182515#11182515

The default/fallback watchservice fails frequently if the sleep is less then 5 seconds.

**Comment by joakime** [comment]
We could update the sensitivity on the non-native register() step.

https://github.com/eclipse/jetty.project/blob/jetty-9.3.14.v20161028/jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java#L1203

That might make a difference too.

**Comment by joakime** [comment]
@WalkerWatch this issue seems more like a documentation concern, then a code concern.
Do you concur?

**Comment by WalkerWatch** [comment]
@joakime That seems fine to me. I will look for a place to get this in.

**Comment by visvadw** [comment]
Alright, I'll take a look on the [PathWatcher](https://github.com/eclipse/jetty.project/blob/jetty-9.3.14.v20161028/jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java#L1203).
Many thanks to everybody for the feedback!
