### ISSUE TITLE
Jetty not allowing special character in http header name. 

### ISSUE THREAD

**Issue by SarathChandraRS** [eclipse/jetty.project#10616]
**Jetty Version** 10.0.15

**Jetty Environment**

**Java Version** Java 8 

**Question**
With Jetty 9.0.x version, when we send request with request header name having special character. It used to allow the special character and works. But after upgrading Jetty 10.x or Jetty 9.4.X we see an error as Illegal character VCHAR='/' with 400 Bad Request. 
I understand HTTP doesn't support special character in header name. But  since you are allowing in older version, wanted to check if there is a way we can pass this validation in Jetty 10.x as well. 
One way we can think of is encoding the special character in header name. But I am looking for a way if we can achieve without even doing that ? 
Appreciate any help. 
Thanks.

**Comment by sbordet** [comment]
Can you make an example of how this invalid header looks like?
Also, the header is a request header or a response header?

**Comment by SarathChandraRS** [comment]
x-amz-meta-/: 3
Above is the sample header with illegal character '/'
It is request header.

**Comment by sbordet** [comment]
I just tried Jetty 9.4.52, and I get the same error: `400: Illegal character VCHAR='/'`.
You report that the error is there since Jetty 9.2.x.

I don't think we can allow these headers without opening up security vulnerabilities, sorry.
Can you sanitize these headers before sending them?

For example, `x-amz-meta-%2F: 3` passes.
Your application would then have to decode the `%2F` back into a `/`.

@gregw thoughts?

**Comment by SarathChandraRS** [comment]
Sure. We can encode at client side and decode the header back in application code. 
I wanted to check if there is any other option that jetty provides instead of making changes at application code. 
Update : Sorry I meant Jetty 9.4.x version not Jetty 9.2.x as mentioned in the question. (updated in question as well)
This clarifies the question. 
Thanks for the quick response.

**Comment by joakime** [comment]
For the record, `field-name` of `x-amz-meta-/` is a violation of the `token` rules in the HTTP/1, HTTP/2, and HTTP/3 specs.

* https://datatracker.ietf.org/doc/html/rfc9110#name-fields

```
5.6.2.  Tokens

   Tokens are short textual identifiers that do not include whitespace
   or delimiters.

     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

   Many HTTP field values are defined using common syntax components,
   separated by whitespace or specific delimiting characters.
   Delimiters are chosen from the set of US-ASCII visual characters not
   allowed in a token (DQUOTE and "(),/:;<=>?@[\]{}").
```

The character `/` is considered a delimiter in HTTP speak, and as such is not allowed in the `field-name` side of a header declaration.  (Technically it has never been allowed, it is just that old versions of Jetty didn't care as Jetty HTTP support was limited to HTTP/1 on RFC2616)

Back in Jetty 9.0.0 (March 2013) the header parsing was very forgiving.
But once Jetty 9.2.x started (June 2014), the updated RFC7230 hit, which made things more strict.
Then 9.3.0 (June 2015) started to work on the then draft HTTP/2 spec. which made things even more strict for HTTP across the board.
By the time Jetty 9.4.x started (Dec 2016), the HTTP/2 spec formalized, which again made things even more strict for HTTP across the board.

**Comment by SarathChandraRS** [comment]
Thanks for confirmation @joakime  @sbordet . 
I will be closing the question. Thanks for the help.
