### ISSUE TITLE
jetty-http-tools-12.0.1.jar  is not well-formed

### ISSUE THREAD

**Issue by merks** [eclipse/jetty.project#10657]
**Jetty version(s)**

I'm not sure where to report this issue.  This jar's

https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http-tools/12.0.1/jetty-http-tools-12.0.1.jar

MANIFEST.MF is like this:

> Manifest-Version: 1.0
> Created-By: Apache Maven Bundle Plugin 5.1.9
> Build-Jdk-Spec: 21
> Implementation-Vendor: Eclipse Jetty Project
> Implementation-Version: 12.0.1
> url: https://eclipse.dev/jetty/
> Bundle-Classpath: .
> Bundle-Copyright: Copyright (c) 2008-2021 Mort Bay Consulting Pty Ltd an
>  d others.
> Bundle-Description: Jetty module for Core :: HTTP Tools
> Bundle-DocURL: https://eclipse.dev/jetty/
> Bundle-License: https://www.eclipse.org/legal/epl-2.0/, https://www.apac
>  he.org/licenses/LICENSE-2.0
> Bundle-ManifestVersion: 2
> Bundle-Name: Core :: HTTP Tools
> Bundle-RequiredExecutionEnvironment: JavaSE-11
> **Bundle-SymbolicName:** 
> Bundle-Vendor: Eclipse Jetty Project
> Bundle-Version: 12.0.1
> Export-Package: org.eclipse.jetty.http.tools.matchers;uses:="org.eclipse
>  .jetty.http,org.hamcrest";version="12.0.1"
> Import-Package: java.lang,java.util,org.eclipse.jetty.http;version="[12.
>  0.1,13)",org.hamcrest;version="[2.2.0,3)",org.slf4j;version="[1.7,3.0)"
>  ,org.slf4j.event;version="[1.7,3.0)",org.slf4j.helpers;version="[1.7,3.
>  0)",org.slf4j.spi;version="[1.7,3.0)"
> Tool: Bnd-6.3.1.202206071316

I.e., the **Bundle-SymbolicName** is missing.

So it's not easy to use this "bundle" because it's not a bundle:

![image](https://github.com/eclipse/jetty.project/assets/208716/7105aa38-71a7-482d-b7c0-b956702175ef)

**Comment by joakime** [comment]
Interesting, I would have assumed that jetty-http-tools was NOT a bundle. (it has no reason to be).

It's just a jar with utility classes / methods used in unit testing scenarios.

**Comment by sbordet** [comment]
@joakime should be enough to add the property `bundle-symbolic-name` in the POM like the others.

**Comment by joakime** [comment]
@sbordet sure, it's an easy fix in either way (with or without).
Just was surprised it had anything in it at all, let alone it being bad.

**Comment by sbordet** [comment]
Fixed by c41509950b0d04292530114fb1aa4c40a50c4282.

**Comment by merks** [comment]
Thanks.  👍
