### ISSUE TITLE
What is the default connection timeout and how can I set it in Spring Boot?

### ISSUE THREAD

**Issue by waterdrake** [eclipse/jetty.project#10676]
I am using Jetty in a Spring Boot application. I am trying to figure out what is the default time a connection can be idle for before getting a timeout error. Is it 30 seconds? If so, where is that listed?

I am looking at the property [server.jetty.connection-idle-timeout](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.jetty.connection-idle-timeout) in the Spring Boot docs but it does not show a value. Is that value coming straight from Jetty then? Where can I find the default value

I want to set the timeout to be 60 seconds. is setting `server.jetty.connection-idle-timeout=60s` the right way to do it if I am in Spring Boot? Or is there another setting?

**Comment by lachlan-roberts** [comment]
The default in Jetty is 30sec.

We don't have much to do with the spring boot configuration properties, but this looks like the right one to configure the connector idle timeout. So if you want a 60sec idleTimeout I would use the property and set it explicitly instead of relying on the default.
