### ISSUE TITLE
Jetty WebSocket remembers mappings on restart

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10687]
**Jetty version(s)**
12+

**Jetty Environment**
`core`

**Description**
During `Server` start, a WebSocket endpoint is mapped to a pathspec.
Performing a `Server` restart (stop+start) results in an exception that the endpoint is already mapped.
This is because the mappings are not discarded or cleared upon restart.
The `eeN` environments do not have this problem.

**Comment by sbordet** [comment]
While working on this, `ServerWebSocketContainer` should be reviewed to add its components as beans.

**Comment by sbordet** [comment]
@lachlan-roberts any reason why `WebSocketMappings` is not a `ContainerLifeCycle`?
Seems like we have to register lifecycle listeners anyway to get it working with other components that have a lifecycle.

**Comment by lachlan-roberts** [comment]
In the ee8/ee9/ee10 environments we add `WebSocketComponents` and `WebSocketContainer` with a SCI and they are removed when stopping.

So `WebSocketContainer` and `WebSocketMappings` are not persisting between restarts so the mappings doesn't need to be a lifecycle.

But we need to review this for the `WebSocketUpgradeHandler` which doesn't use any SCI. `WebSocketMappings` is a `LifeCycle.Listener` which clears itself when stopping but I can't see this being used anywhere.

**Comment by sbordet** [comment]
Fixed by #10773.
