### ISSUE TITLE
Introduce Jetty 12 ee8 osgi layer

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10688]
**Jetty version(s)**
12

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
As pointed out in a eclipse releng issue https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1430#issuecomment-1754416750

The current release of Jetty 12.0.2 does not contain a ee8 OSGI layer.

There does exist an OSGi layer for ee10 and ee9 though.

* https://repo1.maven.org/maven2/org/eclipse/jetty/ee10/osgi/
* https://repo1.maven.org/maven2/org/eclipse/jetty/ee9/osgi/

Looks like the jetty-ee8/osgi layer isn't even present in the source tree.

https://github.com/eclipse/jetty.project/tree/jetty-12.0.x/jetty-ee8

**Comment by olamy** [comment]
PR available here https://github.com/eclipse/jetty.project/pull/10711

**Comment by joakime** [comment]
Merged into `jetty-12.0.x`
