### ISSUE TITLE
ResourceHandler doesn't support range requests

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#107]
migrated from Bugzilla [#400738](https://bugs.eclipse.org/bugs/show_bug.cgi?id=400738)
status ASSIGNED severity *normal* in component *server* for *9.0.x*
Reported in version *9.0.0* on platform *All*
Assigned to: Project Inbox

On 2013-02-13 16:27:03 -0500, Joakim Erdfelt wrote:

> If you request a range of content from the ResourceHandler it returns the entire file.

On 2013-02-13 16:28:21 -0500, Joakim Erdfelt wrote:

> Adding testcase showing failure at
> jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerRangeTest.java
> 
> in [master f15d4c0]

**Comment by joakime** [comment]
See https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerRangeTest.java

**Comment by gregw** [comment]
Already fixed in master by the addition of [ResourceService](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java) as common code to ResourceHandler and DefaultServlet
