### ISSUE TITLE
Java RESTful Application using Jetty Server 12.x with Jersey Java example

### ISSUE THREAD

**Issue by ashok-mariyala** [eclipse/jetty.project#10709]
**Jetty Version**
jetty-server: 12.0.2

**Jetty Environment**
jetty-server: 12.0.2

**Java Version**
Java 17

**Question**
I would like to develop Java RESTful application using Jersey with Jetty embedded server. It seems there are many changes happened in 12.x series. I could not find any examples for Jersey with Jetty embedded server.

**Comment by joakime** [comment]
This is question better asked of the Jersey developers.

They seem to have targeted Jetty 11 for their embedded modes, so they (Jersey) will need to make changes in their embedded code for Jetty 12 before you can upgrade to use Jetty 12.

Does the Jersey project have a filed issue about this yet?
It would be best to coordinate the changes over on that project.

**Comment by ashok-mariyala** [comment]
@joakime thanks for your response. It seems jersey is not yet implemented Jetty 12. Is there any other alternative way to develop REST application using Jetty 12. Please let me know. Thanks in advance.
