### ISSUE TITLE
http/3 connector does not work when used with sslcontext set in sslcontextfactory

### ISSUE THREAD

**Issue by abvaidya** [eclipse/jetty.project#10702]
**Jetty version(s)**
11.0.17

**Java version/vendor** `(use: java -version)`
Temurin-17.0.8.1+1

**OS type/version**
Apple M1 Pro Ventura 13.5.2

**Description**
I am trying to write a sample http/3 program but get following error on server start -
- Unable to start the server: 
java.lang.IllegalStateException: Invalid KeyStore: no aliases
	at org.eclipse.jetty.quic.server.QuicServerConnector.doStart(QuicServerConnector.java:164)
	at org.eclipse.jetty.http3.server.HTTP3ServerConnector.doStart(HTTP3ServerConnector.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)

From what I can see, the alias map only gets populated when sslContext is null - https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L315 

so when I am creating my sslContext and setting it on sslcontextfactory, alias map doesn't get populated and QuicServerConnector doesn't like that.

**How to reproduce?**

```
    QueuedThreadPool threadPool = new QueuedThreadPool();
    threadPool.setMaxThreads(256);
    Server server = new Server(threadPool);
   SslContextFactory.Server sslContextFactory = new SslContextFactory.Server();
   // createSSLContext() returns a reloadable ssl context
   sslContextFactory.setSslContext(createSSLContext());
    // create and configure the HTTP/3 connector
    HTTP3ServerConnector connector = new HTTP3ServerConnector(server, sslContextFactory,
            new HTTP3ServerConnectionFactory(httpsConfig));
```

Please let me know if I can provide any additional information. Thank you.

**Comment by lorban** [comment]
`javax.net.ssl.SSLContext` acts as a factory of objects using the TLS protocol, but QUIC is not built on TLS and does not use SSLContext. `HTTP3ServerConnector` uses `SslContextFactory` for the sake of being configurable as much as possible like HTTP 1 and 2 but not all configurations are compatible with QUIC.

I understand that you got confused by the unclear error message, which definitely should be improved. I've opened #10705 to track this.

To fix your problem, you should not set your own SSLContext and instead set the keystore and its password.

**Comment by abvaidya** [comment]
Thank you for the explanation!
