### ISSUE TITLE
HttpServlet and UserIdentity classes not found in Jetty server 12.x

### ISSUE THREAD

**Issue by ashok-mariyala** [eclipse/jetty.project#10707]
**Jetty version(s)**

```
jetty-server: 12.0.2
jetty-servlet: 11.0.17
jetty-util: 12.0.2
```

**Jetty Environment**

```
jetty-server: 12.0.2
jetty-servlet: 11.0.17
jetty-util: 12.0.2
```

**Java version/vendor** `(use: java -version)`
`java 17.0.8`
**OS type/version**
`Mac`
**Description**

``` java
try {
	// we created handler without sessions, because REST is stateless.
	var contextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);

	// Sets application path to the root.
	contextHandler.setContextPath("/");
	jettyServer.setHandler(contextHandler);

	// Adds Servlet that will handle requests on /api/*
	ServletHolder jerseyServlet = contextHandler.addServlet(ServletContainer.class, "/api/*");
	jerseyServlet.setInitOrder(0);

	// set package where rest resources are located.
	jerseyServlet.setInitParameter("jersey.config.server.provider.packages",
			"com.ashok.gateway.rest.controller");
	jettyServer.start();
	LOG.error("Jetty Server started...!!");
	jettyServer.join();
} catch (Exception e) {
	LOG.error("Exception while starting jetty server. {}", e.getMessage(), e);
	Thread.currentThread().interrupt();

	try {
		jettyServer.stop();
	} catch (Exception ex) {
		LOG.error("Exception while stoping jetty server. {}", ex.getMessage(), ex);
	}
	jettyServer.destroy();
}
```

I am using above code to handle REST requests. Above code works fine in Jetty 11.x jars. But when i update jetty versions to 12.x above code compilation is failed. Gives following errors.

```
[ERROR] /src/main/java/com/ashok/gateway/jetty/JettyApiServer.java:[45,69] cannot access jakarta.servlet.http.HttpServlet
[ERROR]   class file for jakarta.servlet.http.HttpServlet not found
[ERROR] /src/main/java/com/ashok/gateway/jetty/JettyApiServer.java:[46,38] cannot access org.eclipse.jetty.server.UserIdentity
[ERROR]   class file for org.eclipse.jetty.server.UserIdentity not found
[ERROR] -> [1m[Help 1][m
```
**How to reproduce?**

**Comment by joakime** [comment]
You are mixing versions of Jetty components, this will never work reliably.

```
jetty-server: 12.0.2
jetty-servlet: 11.0.17
jetty-util: 12.0.2
```

Jetty 12 is a core, without Servlet, and a collection of environments now.
Jetty 12.0.2 ships with `ee10`, `ee9`, and `ee8` options. (you can define more environments btw).

In your short list of artifacts ...

* jetty-server is a core component and has no changes to its maven coordinate
* jetty-util is also a core component
* jetty-servlet belongs to an EE environment, and has 3 different options on Jetty 12.0.2 (based on your chosen EE environment).

Please use the migration guide to find your new artifact and namespace locations.

https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12

**Comment by ashok-mariyala** [comment]
@joakime I didn't see your response. There is an empty response from you.

**Comment by joakime** [comment]
@ashok-mariyala reload, it should show up now

**Comment by ashok-mariyala** [comment]
@joakime Thank you for your quick response. Above code snippet is working with following dependencies. 
```
jetty-server: 11.0.14
jetty-servlet: 11.0.12
jetty-util: 11.0.11
```
Along with above dependencies i am using following dependencies.
```
jersey-server: 3.1.0-M8
jersey-container-servlet-core: 3.1.0-M8
jersey-container-jetty-http: 3.1.0-M8
jersey-hk2: 3.1.0-M8
jakarta.annotation-api: 3.1.0-M8
``` 
After upgrading the jetty versions i am facing compilation issues. Could you please let me know what is the issue with my code in jetty 12.x.

**Comment by joakime** [comment]
This would be a question for the Jersey folks, since they are the ones maintaining `jersey-container-jetty-http`
