### ISSUE TITLE
jetty.sh start does not work due to new --start-log-file argument

### ISSUE THREAD

**Issue by lonerook** [eclipse/jetty.project#10713]
**Jetty version(s)**
12.0.2

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
17.0.8, 17.0.4.1

**OS type/version**
Debian 12.1
macOS 13.5.2

**Description**
Running `jetty.sh start` gives an exception:

`java.lang.IllegalArgumentException: unknown arg --start-log-file=/some_path/jetty/jetty-start.log
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1941)`

This problem is new in Jetty 12.0.2 and seems to be due to updates in jetty.sh where argument `start-log-file` has been replaced by `--start-log-file` in several places.

**How to reproduce?**
Stand in base directory, call `$JETTY_HOME/bin/jetty.sh start`

**Comment by gregw** [comment]
@lonerook thanks.  Yes we have already spotted this issue and are addressing it in #10700 for #10696.
For now, you can use the jetty.sh from 12.0.1

**Comment by lonerook** [comment]
Great, thanks a lot for quick reply!

**Comment by joakime** [comment]
Fixed a while ago in PR #10696
