### ISSUE TITLE
Trim down EE10 DefaultServlet

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10739]
**Jetty version(s)**
12.0.x

**Enhancement Description**
Currently, the EE10 `DefaultServlet` tries to do too many things: being the default servlet bound to the root of the context as well as a general-purpose resource-serving servlet, and some requirements of both facets sometimes clash with each other.

`DefaultServlet` should be simplified to just be the bare-bone servlet meant to be bound to the root of the context and nothing else.

See #10738 for the `ResourceServlet` issue.

**Comment by joakime** [comment]
@lorban haven't we kinda done this with the ResourceServlet work?

**Comment by lorban** [comment]
@joakime yes, it looks like #11933 is addressing both this issue and #10738 so I've linked the PR to close this bug too when merged. Thanks for the reminder!
