### ISSUE TITLE
Introduce EE10 ResourceServlet

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10738]
**Jetty version(s)**
12.0.x

**Enhancement Description**
Currently, the EE10 `DefaultServlet` tries to do too many things: being the default servlet bound to the root of the context as well as a general-purpose resource-serving servlet, and some requirements of both facets sometimes clash with each other.

A new `ResourceServlet` should be introduced to allow general-purpose resource-serving with all the configurable settings while not being designed to be bound to the root of the context.

See #10739 for the `DefaultServlet` issue.

**Comment by janbartel** [comment]
@lorban we should schedule this

**Comment by lorban** [comment]
@janbartel we should take the time to form a plan, as https://github.com/jetty/jetty.project/issues/9080 and https://github.com/jetty/jetty.project/issues/10739 are related and https://github.com/jetty/jetty.project/issues/8790 should at least be kept at the back of our mind.

I'm not yet sure if we should redesign our current content handling architecture or modify just the necessary bits to split the default servlet.

**Comment by gregw** [comment]
@lorban I think we need to get moving on this. There is not much time between now and 12.1.0

I don't see why we can't immediately in 12.0.x split DefaultServlet into a ResourceServlet that is extended to be the DefaultServlet.       The extended DefaultServlet would only need to mix in: a) that resources come from the context resourceBase; b) how the pathInContext is used to request a context.
The ResourceServlet itself can be a lot more flexible about those assumptions.

If the API split is not 100% correct then: users can continue to use DefaultServlet as they are now (but we really don't want them to);  plus we will have the break to 12.1.x to refine the API.


I think most of the other resource issues can be done orthogonal to these kind of changes... although I would not we need to get a hurry on with those as well in the 12.1.x timeframe.

**Comment by gluser1357** [comment]
Would _ResourceServlet_ be specific for Jetty (in contrast to the `<servlet-name>default</servlet-name>` mechanism for _DefaultServlet_ that works e. g. for both Jetty and Tomcat)? That would be great since the same _web.xml_ could be used for both servers (see also #11884).

**Comment by gregw** [comment]
@gluser1357 ResourceServlet will still be jetty specific, as there are many jetty internals that it can deal with that will make serving static content more efficient.
Creating a portable ResourceServlet may indeed be a good idea, but it would be hard to do that within the jetty project.   Having an artifact from a non server project would be the best place for that, so it would not have any dependencies on either.
