### ISSUE TITLE
jakarta.websocket.Session.getRequestParameterMap() contains the value as key

### ISSUE THREAD

**Issue by johnAtWorking** [eclipse/jetty.project#10734]
**Jetty version(s)**
12.0.2

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
OpenJDK17U-jre_x64_linux_hotspot-17.0.8.1_1 / Eclipse

**OS type/version**
Windows 10

**Description**
I open a websocket like
url = ((window.location.protocol == "https:") ? "wss:" : "ws:") + "//" + 	window.location.host + path + "ws?pageId=6";
webSocket = new WebSocket(url);

in the controller I will read the parameter "pageId"

@ServerEndpoint(ContentPaths.websocketPath)
public class WebsocketController implements WebListener
{
    @OnOpen
    public void onOpen(final Session session)
    {
        final var params = session.getRequestParameterMap();
        final var list = params.get("pageId");
    }
}

The key "pageId"  in session.getRequestParameterMap() ist not found. Instead the map contains 6=6.

In think in org.eclipse.jetty.websocket.core.Negotiated.Negotiated(URI, String, boolean, ExtensionStack, String)
the "map.put(field.getValue(), Collections.unmodifiableList(field.getValues()));" 
should be " map.put(field.getName(), Collections.unmodifiableList(field.getValues()));" 

**How to reproduce?**

**Comment by joakime** [comment]
@lachlan-roberts can you look at this?

**Comment by lachlan-roberts** [comment]
Merged fix in PR #10736, will be released with `12.0.3`.
