### ISSUE TITLE
JDK9 support in Jetty 9.3.x

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1073]
Currently, JDK 9 support is in Jetty 9.4.x (in a branch), and must be ported to Jetty 9.3.x.

**Comment by sbordet** [comment]
Tests in:

* http2-alpn-tests
* http2-http-client-transport
* test-jetty-osgi
* test-http-client-transport

have been put into a `jdk8` profile, but needs to be ported to both JDK 8 and JDK 9.

**Comment by sbordet** [comment]
`http2-alpn-test` done.

**Comment by gregw** [comment]
Closing this as all known issues have been backported to 9.3.  Anything else discovered should have an individual issue opened.
