### ISSUE TITLE
Consider introducing a Content.Source newContentSource() method to Resource

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10741]
**Jetty version(s)**
12.0.x

**Enhancement Description**
Modifying `Resource` to expose a `Content.Source` instead of both an `InputStream` and a `ReadableByteChannel` would make a more natural construct for Jetty.

That would help avoid using and duplicating the following pattern when serving resources while still getting optimum performance:

```java
if (resource.getPath() != null)
  // use NIO with Path: async and no unnecessary buffer copies
else
  // fallback to InputStream: blocking and requires extra buffer copies
```

**Comment by joakime** [comment]
Wouldn't it be easier to have `Content.Source.from(Resource)` instead?

I say this because `Content.Source` is in the `jetty-io` package, and `Resource` is in the `jetty-util` package.

Since jetty-util doesn't depend on jetty-io, it would be better to go the opposite direction.

**Comment by lorban** [comment]
From an API perspective, this makes more sense, indeed. Thanks for the suggestion!

**Comment by lorban** [comment]
Done in https://github.com/jetty/jetty.project/pull/11364
