### ISSUE TITLE
Jetty 11.0.16/11.0.17 doesn't compile jsp

### ISSUE THREAD

**Issue by jbonofre** [eclipse/jetty.project#10766]
**Jetty version(s)**
Issue introduced in Jetty 11.0.16/11.0.17 (upgrading from 11.0.15)

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 17.0.9+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.9+0, mixed mode, sharing)

**OS type/version**
MacOS (x86/arm64) Sonoma

**Description**
More details:
https://issues.apache.org/jira/browse/AMQ-9327

While updating to Jetty 11.0.17 in ActiveMQ, I have this error while accessing a JSP:

```
jakarta.servlet.ServletException: jakarta.servlet.ServletException: org.apache.jasper.JasperException: /index.jsp (line: [18], column: [0]) Cannot invoke "org.apache.jasper.compiler.TldCache.getTldResourcePath(String)" because the return value of "org.apache.jasper.Options.getTldCache()" is null 
```

I identified the commit which introduced this error:

```
939f1362f6d6142c0fca196f6472c10e639c6361 is the first bad commit
commit 939f1362f6d6142c0fca196f6472c10e639c6361
Merge: 7f0b7d5e11 e33d026259
Author: Simone Bordet <simone.bordet@gmail.com>
Date:   Thu Aug 17 17:02:13 2023 +0200


    Merged branch 'jetty-10.0.x' into 'jetty-11.0.x'.


    Signed-off-by: Simone Bordet <simone.bordet@gmail.com>


 jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java | 3 ++-
 jetty-websocket/websocket-jetty-server/pom.xml                     | 2 +-
 jetty-websocket/websocket-jetty-tests/pom.xml                      | 5 +++++
 pom.xml                                                            | 2 +-
 4 files changed, 9 insertions(+), 3 deletions(-) 
```

More specifically, the error is due to the change in `websocket-jetty-server` which now depends to `jetty-webapp` whereas it depends to `jetty-annotations` before this change.

I tried to add `jetty-annotations` in our classloader, but it required also `jetty-plus` with additional configuration.

Can you point me why `websocket-jetty-server` dependency has been changed ?

Thanks !

**How to reproduce?**
Update Apache ActiveMQ to Jetty 11.0.16 or 11.0.17.

**Comment by sbordet** [comment]
@joakime the change reported by the OP was introduced in this PR: https://github.com/jetty/jetty.project/pull/10316.

Thoughts?

**Comment by sbordet** [comment]
@jbonofre I think it's reasonable to expect that if you depend on `websocket-jetty-server` you should not have a dependency on the code that compiles JSPs (you're just doing websockets).

If you need both JSP and WebSocket, now you should probably explicitly add the dependencies, rather then relying on transitiveness.

Have you tried explicitly adding JSP support?

**Comment by jbonofre** [comment]
@sbordet I agree. Actually, I need both websocket and JSP in the same classpath (for activemq standalone distribution).
Currently, with Jetty 11.0.15, I have this jar files in my classpath:

```
apache-el-10.0.14.jar
apache-jsp-10.0.14.jar
apache-jsp-11.0.15.jar
apache-jstl-11.0.0.jar
asm-9.6.jar
ecj-3.17.0.jar
jakarta.annotation-api-2.1.1.jar
jakarta.servlet.jsp.jstl-3.0.1.jar
jakarta.servlet.jsp.jstl-api-3.0.0.jar
jakarta.websocket-api-2.1.0.jar
javax.security.auth.message-1.0.0.v201108011116.jar
jdom2-2.0.6.1.jar
jetty-annotations-11.0.15.jar
jetty-http-11.0.15.jar
jetty-io-11.0.15.jar
jetty-jakarta-servlet-api-5.0.2.jar
jetty-jndi-11.0.15.jar
jetty-plus-11.0.15.jar
jetty-rewrite-11.0.15.jar
jetty-security-11.0.15.jar
jetty-server-11.0.15.jar
jetty-servlet-11.0.15.jar
jetty-util-11.0.15.jar
jetty-webapp-11.0.15.jar
jetty-xml-11.0.15.jar
json-simple-1.1.1.jar
rome-2.1.0.jar
rome-utils-2.1.0.jar
spring-web-6.0.13.jar
spring-webmvc-6.0.13.jar
websocket-core-common-11.0.15.jar
websocket-core-server-11.0.15.jar
websocket-jetty-api-11.0.15.jar
websocket-jetty-common-11.0.15.jar
websocket-jetty-server-11.0.15.jar
websocket-servlet-11.0.15.jar
```

It works like a charm (for a while :) ).

Upgrading to Jetty 11.0.17, I have this:

```
apache-el-10.0.14.jar
apache-jsp-10.0.14.jar
apache-jsp-11.0.17.jar
apache-jstl-11.0.0.jar
asm-9.6.jar
ecj-3.17.0.jar
jakarta.annotation-api-2.1.1.jar
jakarta.servlet.jsp.jstl-3.0.1.jar
jakarta.servlet.jsp.jstl-api-3.0.0.jar
jakarta.websocket-api-2.1.0.jar
javax.security.auth.message-1.0.0.v201108011116.jar
jdom2-2.0.6.1.jar
jetty-http-11.0.17.jar
jetty-io-11.0.17.jar
jetty-jakarta-servlet-api-5.0.2.jar
jetty-rewrite-11.0.17.jar
jetty-security-11.0.17.jar
jetty-server-11.0.17.jar
jetty-servlet-11.0.17.jar
jetty-util-11.0.17.jar
jetty-webapp-11.0.17.jar
jetty-xml-11.0.17.jar
json-simple-1.1.1.jar
rome-2.1.0.jar
rome-utils-2.1.0.jar
spring-web-6.0.13.jar
spring-webmvc-6.0.13.jar
websocket-core-common-11.0.17.jar
websocket-core-server-11.0.17.jar
websocket-jetty-api-11.0.17.jar
websocket-jetty-common-11.0.17.jar
websocket-jetty-server-11.0.17.jar
websocket-servlet-11.0.17.jar
```

I don't change anything else, just upgrading. And then, `index.jsp` doesn't compile:

```
jakarta.servlet.ServletException: jakarta.servlet.ServletException: org.apache.jasper.JasperException: /index.jsp (line: [18], column: [0]) Cannot invoke "org.apache.jasper.compiler.TldCache.getTldResourcePath(String)" because the return value of "org.apache.jasper.Options.getTldCache()" is null 
```

I'm suspecting that now I need additional jar in my classpath (maybe `jetty-annotations` as it came from `websocket-jetty-server` with Jetty 11.0.15).

I tried to add both `jetty-annotations`, `jetty-plus`, and `jetty-jndi` in my classpath, and it works.

I close this issue, sorry for the noise 😄
