### ISSUE TITLE
IRI support

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10764]
**Jetty version(s)** 12

**Enhancement Description**
I want to be able to interact with IRIs as defined by [RFC 3987](https://datatracker.ietf.org/doc/html/rfc3987). Unfortunately Java does not support IRIs out of the box. Supposedly, OkHttp is one of the few libraries to add support.

I'm just throwing this out there. If you think there is no demand and/or we'd rather wait for built-in support in the JDK then it should be okay for now.

**Comment by joakime** [comment]
Some history of IRI support attempts in the JVM. (This was last attempted in Java 6)

https://cr.openjdk.org/%7Edfuchs/writeups/updating-uri/

**Comment by joakime** [comment]
Looks like a `java.net.IRI` was attempted in JDK 13, but backed out as it caused too many other issues.

https://cr.openjdk.org/~dfuchs/writeups/updating-uri/iri-prototype/webrev/api/java.base/java/net/IRI.html

**Comment by joakime** [comment]
Looks like there's a standalone `jena-iri` component (from the Apache Jena project) that could do it.

https://central.sonatype.com/artifact/org.apache.jena/jena-iri?smo=true

License: Apache Source License 2

Haven't looked too closely at it.

**Comment by cowwoc** [comment]
Jena looks like it's well maintained, but https://jena.apache.org/documentation/notes/iri.html doesn't look promisng. I've asked for clarification: https://github.com/apache/jena/issues/2052

**Comment by cowwoc** [comment]
Nevermind. I just realized that URIs can represent all the same addresses as IRIs and it's more a question of performance. 

Given that, I guess I don't really care about IRI support at this time.
