### ISSUE TITLE
Review ConnectionMetaData.isSecure()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10775]
**Jetty version(s)**
12

**Description**
The current implementation just checks if the `EndPoint` in an instance of `SslEndPoint`, but that may not be enough, especially in the case of the PROXY protocol.

See the logic in `SecureRequestCustomizer.customize()`.
How does the logic in `SecureRequestCustomizer` play with the logic of `ForwardedRequestCustomizer`?

**Comment by joakime** [comment]
Discovered during a review of PR #10772

**Comment by joakime** [comment]
@gregw take a look at this please

**Comment by sbordet** [comment]
Fixed with #10853.
