### ISSUE TITLE
Maven Plugin: Warning about connectors

### ISSUE THREAD

**Issue by melloware** [eclipse/jetty.project#10780]
**Jetty version(s)**
11.0.17

**Java version/vendor** `(use: java -version)`

`Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10`

**OS type/version**
```
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: C:\tools\apache-maven-3.9.5
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

**Description**
```
[WARNING] Parameter 'connectors' is unknown for plugin 'jetty-maven-plugin:11.0.17:run (default-cli)'
```

![image](https://github.com/jetty/jetty.project/assets/4399574/09c2c7ac-e428-4278-ae2b-02d3e550cb6d)

**How to reproduce?**

```xml
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>11.0.17</version>
                <configuration>
                    <!-- see https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-configuration-6 -->
                    <webApp>
                        <contextPath>/primefaces-test</contextPath>
                        <jettyEnvXml>${project.basedir}/src/main/conf/jetty-env.xml</jettyEnvXml>
                    </webApp>
                    <scan>5</scan>
                    <webXml>${project.build.directory}/web.xml</webXml>
                    <connectors>
                        <connector implementation="org.eclipse.jetty.server.nio.SelectChannelConnector">
                            <host>0.0.0.0</host>
                            <port>8080</port>
                            <maxIdleTime>60000</maxIdleTime>
                        </connector>
                    </connectors>
                </configuration>
            </plugin>
```

NOTE: Everything works fine its just odd this is a WARNING when the plugin has this setting and feature.

**Comment by joakime** [comment]
The section ...

``` xml
                    <connectors>
                        <connector implementation="org.eclipse.jetty.server.nio.SelectChannelConnector">
                            <host>0.0.0.0</host>
                            <port>8080</port>
                            <maxIdleTime>60000</maxIdleTime>
                        </connector>
                    </connectors>
```

... is invalid, nothing in jetty-maven-plugin uses an element called `connectors` in that location.

With your configuration, you are actually using the default deployment mode of `EMBED`, that uses the default `ServerConnector`, with the default `HttpConnectionFactory`, on default port 8080, listening on the default of all interfaces, with the default idle timeout of 30000.

Also, `org.eclipse.jetty.server.nio.SelectChannelConnector` doesn't even exist in Jetty 9+
That's a class from Jetty 7 thru Jetty 8. (it was called [`org.mortbay.jetty.nio.SelectChannelConnector` in Jetty 6](https://github.com/jetty-project/codehaus-jetty6/blob/master/modules/jetty/src/main/java/org/mortbay/jetty/nio/SelectChannelConnector.java) and older)

There wasn't even a [`org.eclipse.jetty:jetty-maven-plugin` in existence during Jetty 7 thru Jetty 8 days](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-maven-plugin/).  

See example source tree back in the Jetty 8.1.22 days -> https://github.com/jetty/jetty.project/tree/jetty-8.1.22.v20160922

I suspect this configuration is very old in your pom, probably dating back to Jetty 6 days, and the `org.mortbay` namespace, and you updated it along the way and didn't realize that `connectors` is not being used anymore.  Only these more recent versions of Maven are now giving you a warning that it is not being used.

If you want to setup the connectors, then you should look at which deployment mode you want to operate in, and setup the connectors appropriate for your chosen mode.

See documentation at https://eclipse.dev/jetty/documentation/jetty-11/programming-guide/index.html#deployment-modes

**Comment by melloware** [comment]
Awesome!  Yep ancient configuration just updated to:

```xml
                    <httpConnector>
                        <host>0.0.0.0</host>
                        <port>${jetty.port}</port>
                        <idleTimeout>60000</idleTimeout>
                    </httpConnector>
```
