### ISSUE TITLE
DigestAuthentication should use realm from server, even if unknown in advance

### ISSUE THREAD

**Issue by aliebrich** [eclipse/jetty.project#1078]
Hi!

I'm debugging a problem with jetty HttpClient where I can't connect to an URL which is protected via Digest Authentication.
I added a ``DigestAuthentication`` as follows:
```
AuthenticationStore authenticationStore = httpClient.getAuthenticationStore();
authenticationStore.addAuthentication(new DigestAuthentication(uri, ANY_REALM, user, password));
```

Why do I need ``Authentication.ANY_REALM``?
Because one does not necessarily know the realm the server is asking for. Because it could be changing over time, unknown in advance, or for whatever reason.
I think that's what ``ANY_REALM`` was designed for, btw.

But this exact ``Authentication.ANY_REALM`` is causing my problems.

What happens?
``HttpClient`` sends a Digest Authentication Header with ``realm="<<ANY_REALM>>"`` instead of the one requested by the server via the header "WWW-Authenticate: Digest realm="xyz" ..."

Why?
First it is explicit used in [``AbstractAuthentication.matches()``](https://github.com/eclipse/jetty.project/blob/master/jetty-client/src/main/java/org/eclipse/jetty/client/util/AbstractAuthentication.java#L55) => correct usage
Then it is implicit used in [``DigestAuthentication.authenticate()``](https://github.com/eclipse/jetty.project/blob/master/jetty-client/src/main/java/org/eclipse/jetty/client/util/DigestAuthentication.java#L102) => wrong usage, i think

I think it could easily be resolved.
Instead of this:
```
return new DigestResult(headerInfo.getHeader(), response.getContent(), getRealm(), user, password, algorithm, nonce, clientQOP, opaque);
```
You better should use:
```
return new DigestResult(headerInfo.getHeader(), response.getContent(), headerInfo.getRealm(), user, password, algorithm, nonce, clientQOP, opaque);
```

One could think of some 'protection' like:
```
ANY_REALM.equals(getRealm()) ? headerInfo.getRealm() : getRealm()
```
But this i would leave up to you, imho it should not be necessary.

Best regards and thanks for looking into this,
Andi

**Comment by sbordet** [comment]
Good catch, good fix, and it also unveiled #1081.
