### ISSUE TITLE
Fix documentation for Maven jetty plugin for Jetty 12

### ISSUE THREAD

**Issue by hantsy** [eclipse/jetty.project#10809]
The official doc related to maven jetty plugin: https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#get-up-and-running

I am using jetty in my project, when updating the jetty version to 12.0.2 from v11, the `maven-jetty-plugin` is missing in the Maven public repo. Check https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-maven-plugin

**Comment by olamy** [comment]
you need to use the corresponding eeX version.
ee10 use this one https://repo.maven.apache.org/maven2/org/eclipse/jetty/ee10/jetty-ee10-maven-plugin/
you will find versions for ee8, ee9 and ee10

**Comment by hantsy** [comment]
So the maven jetty plugin doc should be updated.

**Comment by olamy** [comment]
> So the maven jetty plugin doc should be updated.

Good catch! we definitely  need to fix this.
Would you be happy to provide a PR?

**Comment by hantsy** [comment]
@olamy I will try to send a PR soon.

**Comment by joakime** [comment]
The moved jetty-maven-plugin coordinates are in the migration tables -> https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12

**Comment by JWT007** [comment]
See https://github.com/jetty/jetty.project/issues/11329 - currently some of those coordinates are not correct.

**Comment by sbordet** [comment]
Fixed by #11341.
