### ISSUE TITLE
Can't always access remote address from RequestLog

### ISSUE THREAD

**Issue by jamesagnew** [eclipse/jetty.project#10806]
**Jetty version(s)**
12.0.2

**Jetty Environment**
ee10

**Java version/vendor** 
OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)

**OS type/version**
MacOS

**Description**
Using `CustomRequestLog` with the `NCSA_FORMAT`, the remote address is often (but not always) missing from the resulting logs. There doesn't seem to be any pattern to this, often two runs of the exact same test will produce different results (sometimes the remote address is present, other times it is blank).

In debugging through what's going on, I've pinpointed this down to:

* CustomRequestLog uses `Remote.getRemoteAddr(request)` here:

https://github.com/jetty/jetty.project/blob/7be6c4b375de7cf44f71f4f7e7f1c87ed386ef9b/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java#L821-L824

* getRemoteAddr calls `getRemoteSocketAddress` here:

https://github.com/jetty/jetty.project/blob/7be6c4b375de7cf44f71f4f7e7f1c87ed386ef9b/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L391-L395

* ...but `SocketChannelImpl` has a check that the socket is still open, but finds the socket closed by the time the RequestLog is called and therefore throws an exception:

https://github.com/openjdk/jdk/blob/1ec0d02717b6be4faeb13cd0596d80eea90e81ed/src/java.base/share/classes/sun/nio/ch/SocketChannelImpl.java#L255-L260

**Comment by joakime** [comment]
Opened PR #10815

**Comment by joakime** [comment]
PR #10867 merged
