### ISSUE TITLE
How long does it take for the latest jetty-distribution to be available?

### ISSUE THREAD

**Issue by UnsungHero97** [eclipse/jetty.project#1083]
It looks like `jetty-9.3.14.v20161028` was released around October 28th:

<img width="400" alt="screen shot 2016-11-07 at 10 26 27 am" src="https://cloud.githubusercontent.com/assets/440299/20070344/f69d33b8-a4d4-11e6-886d-6c6c39c6edc5.png">

Today is November 7th, and `jetty-9.3.14.v20161028` is still not available for download here:

<img width="400" alt="screen shot 2016-11-07 at 10 26 37 am" src="https://cloud.githubusercontent.com/assets/440299/20070391/129dae3a-a4d5-11e6-88fc-8338e97590a0.png">

How long does it take for the latest jetty-distribution to be available for download? Are there other places to download besides https://www.eclipse.org/jetty/download.html?

**Comment by jmcc0nn3ll** [comment]
those are just links into maven central which is the canonical durable repository for all jetty releases

updating that page lags a bit because we need to have new snapshots pushed, etc to rebuild the website, etc.

as for this release, I have pushed the changes and have the website rebuilding now

**Comment by joakime** [comment]
The latest distribution is *always* available on the Global Maven Repository system.

eg: http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.3.14.v20161028/

The date you see on the tag is when the release was staged and entered into its testing phase.
It can be hours, days, weeks before it is promoted out from this staging phase to be released.

Also of note, this promotion is only for staging to the Global Maven Repository system.

There is still the p2 repository generation, javadoc, documentation updates, website, etc before it will show up on the downloads.eclipse.org page.

**Comment by UnsungHero97** [comment]
Got it, thanks!

**Comment by jmcc0nn3ll** [comment]
website is updated and I also added a note about this on the download page as well

thanks for the feedback!

**Comment by UnsungHero97** [comment]
Nice! I see the updates. Thanks!
