### ISSUE TITLE
Dropping async code

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10848]
**Question**
I know that something related has been investigated in the past, but do you have any thought about this discussion? https://twitter.com/helidon_project/status/1720066785003860182?t=KFnciv6P8uS8ZhBGg3dYqA&s=19

Have you done any sort of benchmarking comparing the performance of going all-in on Loom in JDK 21 vs keeping the async part of the API?

**Comment by joakime** [comment]
Both @gregw and @sbordet have blogged about loom and Jetty.
https://webtide.com/category/loom/

Dropping async code from Jetty internals is currently not a goal for Jetty.
That being said, going virtual threads for all things with application code is doable today with Jetty.
