### ISSUE TITLE
Improve documentation to HTTP/3

### ISSUE THREAD

**Issue by Horcrux7** [eclipse/jetty.project#10845]
The documentation to configure HTTP/3 is very simple.
https://eclipse.dev/jetty/documentation/jetty-10/programming-guide/index.html#pg-server-http-connector-protocol-http3
https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-connector-protocol-http3

the follow should be added:

* In the sample code I am missing a line like:
        connector.getQuicConfiguration().setPemWorkDirectory(pemDir);
* the security implications of the pemDir
* that it use a native quiche library
* for which platforms the native library is available
* possible problems with different Java versions. I have see some switches on the native bindings. I am unclear which consequences it has.
* magic things that I does not know yet. It does not work for me: https://stackoverflow.com/questions/77389111/how-to-configure-an-embedded-jetty-with-http-3-via-api

**Comment by sbordet** [comment]
Fixed in dc2eff5f42793d546b8d3ed0a9559772baa8675a.

We will expand the documentation once we find the right way to make it work.
See also #10519.
