### ISSUE TITLE
Clarify `Handler.setDynamic()` javadoc

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10849]
**Jetty version(s)**
12

**Enhancement Description**
Handler.setDynamic()'s Javadoc reads `@param dynamic whether this container is dynamic` but does not clarify what it means for a container to be dynamic. Please improve the Javadoc to clarify what this means.

I eventually figured this out, but I had to wade through source-code comments to do it. We don't want users to have to look at the source-code to figure out how the API works :)

**Comment by cowwoc** [comment]
Possible explanation:

> A dynamic handler is one that can be added or removed from a server at runtime, while a non-dynamic handler cannot be added or removed at runtime.

**Comment by sbordet** [comment]
@cowwoc the `AbstractContainer` class javadocs explain in longer details what dynamic exactly means.
Repeating in the getter and setter seems just duplication.

**Comment by cowwoc** [comment]
Agreed. Thank you.
