### ISSUE TITLE
Is org.eclipse.jetty.ee10.servlets.PushCacheFilter removed in Jetty 12.0.3?

### ISSUE THREAD

**Issue by minduch** [eclipse/jetty.project#10846]
**Jetty Version**
12.0.3

**Jetty Environment**
ee10

**Java Version**
OpenJDK 21

**Question**
Where is `org.eclipse.jetty.ee10.servlets.PushCacheFilter`?
Has it been removed since Jetty 12.0.2? If so, permanently?
I haven't seen anything about it anywhere.

**Comment by joakime** [comment]
It has been deprecated in Jetty 10/11, and removed in Jetty 12.

* #9715
* #10755

For 2 reasons.
* The HTTP/2 push features in the spec are essentially dead anyway, most browsers and HTTP/2 clients have either removed (or disabled) support for it already.
* The PushCacheFilter had too many bugs that were not worth addressing in light of the previous point.

**Comment by minduch** [comment]
Thanks: I was wondering who used it!
