### ISSUE TITLE
Why doesn't ClassLoaderResource resolve paths at request time?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10851]
**Jetty Version**
12

**Question**
I was hoping to find a Resource that would load files from the classpath the same way that PathResource does. Meaning, every time a request would come in, it would invoke `ClassLoader.getResource()` and return any matches.

Instead, I found ResourceFactory.newClassLoaderResource() which only resolves one file at a time, and it does so at construction-time instead of each time a request comes in.

Do you plan to provide such functionality? Alternatively, I am forced to explicitly check on startup whether I am running inside a JAR file or within an expanded directory, and then mount a path or a JAR file depending on what I find. If I had a ClassloaderResource that resolved paths at request time I could ignore where the files are coming from.

Thoughts?

**Comment by joakime** [comment]
Are you using `ResourceFactory.newClassLoaderResource()` against a file or a directory?

If your parameter points to a file will be just that, only a file.

If your parameter points to a directory, it should result in a directory that can be used to look up other resources relative to that Classloader resource.

> Do you plan to provide such functionality? Alternatively, I am forced to explicitly check on startup whether I am running inside a JAR file or within an expanded directory, and then mount a path or a JAR file depending on what I find. If I had a ClassloaderResource that resolved paths at request time I could ignore where the files are coming from.

Seems like you can just do that like this ...

``` java
URL urltoresource = Main.class.getResource("/static-content/");
if (urltoresource == null) throw FileNotFoundException("Unable to find static-content");
Resource resource = webappContext.getResourceFactory().newResource(urltoresource.toURI());
```

or any variation of asking for the directory you are interested in via the ClassLoader, and using the resulting URL to create the Resource.
If it's in a jar, that URL will be in the form `jar:file://path/to/myapp.jar!/static-content/`, and if it's an expanded directory it will be `/path/to/expanded-app/static-content`.

**Comment by cowwoc** [comment]
I was invoking something along the lines of ` ResourceFactory.newClassLoaderResource("/")` and it wasn't finding the files I expected. That said, I no longer need this functionality :) I ended up realizing I actually wanted something along these lines:

```
ResourceHandler staticFiles = new ResourceHandler();
Path browserDirectory = ...;

Path srcPath = browserDirectory.resolve("src").normalize();
if (Files.exists(srcPath))
	resources.add(resourceFactory.newResource(srcPath));
Path browserClassesPath = browserDirectory.resolve("target/classes");
if (Files.exists(browserClassesPath))
	resources.add(resourceFactory.newResource(browserClassesPath));
Path browserJar = browserDirectory.resolve("target/client.browser-" + scope.getVersion() + ".jar");
if (Files.exists(browserJar))
	resources.add(resourceFactory.newJarFileResource(browserJar.toUri()));
staticFiles.setBaseResource(ResourceFactory.combine(resources));
```

In order words, what I was really after was an order for precedence for resolving files and the above code works just fine. I will close this issue.
