### ISSUE TITLE
MS IE7 cannot connect to Jetty 9.3.13 probably because SHA ciphersuites are excluded

### ISSUE THREAD

**Issue by michal-niklas** [eclipse/jetty.project#1085]
My servers use Jetty as WebServer and after change from Jetty 9.3.12 to 9.3.13 (and 9.3.14) clients using very old browser (MS IE7 on WinXP) cannot connect. My configuration add some ciphers to include list and some to exclude, but now some ciohers are excluded by default and I cannot enable them back. I need SHA them because MS IE7 cannot connect without this algorithm. I know that now such algorithms are insecure and my server will get lower rating at ssllabs.com tests, but I cannot force clients to upgrade from WinXP+MS IE7.

Report from start of Jetty server which can work with MS IE7:

	Jetty 9.3.12.v20160915
	Included cipher suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:...
	Excluded cipher suites: 
	Included protocols: TLSv1:TLSv1.1:TLSv1.2
	Excluded protocols: SSLv2Hello:SSLv3

Report from start of Jetty server which can not work with MS IE7:

	Jetty 9.3.13.v20161014
	Included cipher suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:...
	Excluded cipher suites: ^.*_(MD5|SHA|SHA1)$
	Included protocols: TLSv1:TLSv1.1:TLSv1.2
	Excluded protocols: SSL:SSLv2:SSLv2Hello:SSLv3

My configuration is the same, but as you see 9.3.13 excluded some cipher suites and protocols.

Is it possible to enable SHA with Jetty 9.3.13 or newer?

**Comment by sbordet** [comment]
See https://github.com/eclipse/jetty.project/issues/713#issuecomment-231985540

**Comment by michal-niklas** [comment]
OK. Thank you. `sslContextFactory.setExcludeCipherSuites();` works very well.

**Comment by joakime** [comment]
@michal-niklas Be aware of the Global SHA1-Deprecation (Jan 1, 2017),  your need for SHA/SHA1/MD5 support will become increasingly difficult then, even for older browsers.
