### ISSUE TITLE
Documentation for Jetty-12 JNDI EnvEntry refers to classes that don't exist

### ISSUE THREAD

**Issue by fudgemond** [eclipse/jetty.project#10856]
I'm trying to get JNDI working at the Server scope level and the documentation here refers to a class, org.eclipse.jetty.plus.jndi.EnvEntry, which does not exist.  The actual class is org.eclipse.jetty.eeNN.plus.jndi.EnvEntry and it appears that it cannot be defined at the server scope, but only at the Web App Context scope.  If this is the case, can the documentation please be updated to reflect what is correct.

**Comment by janbartel** [comment]
This was fixed in commits 7fc4b74a0418250921b180c7f3e775ad7c6a973f and efafbedb271ecf9653b50f3d1a33d88a32de1cb0.

**Comment by fudgemond** [comment]
Thank you Jan and team.
