### ISSUE TITLE
In Case Jetty is Behind a Load Balancer, DosFilter will always use the IP of the Load Balancer

### ISSUE THREAD

**Issue by eladmena** [eclipse/jetty.project#1086]
When using the DosFilter (org.eclipse.jetty.servlets.DoSFilter) there are the options to whilte list ips and in case of thresholds reached the ip is logged.

As the implementations is `request.getRemoteAddr()` and the server is behind a load balancer the ip will be the load balancer instead of the actual client.

It would be great if the application can override it by implementing a way to get the ip
If not overriden use `request.getRemoteAddr()` so for regular deployment it'll work as usual.
For complex ones the application can set its own way to get the IP.

**Comment by sbordet** [comment]
We accept contributions, see http://www.eclipse.org/jetty/documentation/9.3.x/advanced-contributing.html. Would you like to give it a try ? Thanks !

**Comment by eladmena** [comment]
Sure,
I'm trying to set gitHub on my machine

Elad

**Comment by joakime** [comment]
@eladmena you know about the [`ForwardRequestCustomizer`](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/ForwardedRequestCustomizer.html) and its handling of `X-Forwarded-*` headers (provided by your load balancer) right?

This is part of the HttpConfiguration setup, and will apply the `X-Forwarded-*` request header information into the `HttpServletRequest` object, making it sane for things like `getRemoteAddr()`.

**Comment by eladmena** [comment]
I was not aware of **ForwardRequestCustomizer**.
I will use it.

This issue can be closed.
Thanks
