### ISSUE TITLE
Jetty 12.0.3 have build error

### ISSUE THREAD

**Issue by Helly987** [eclipse/jetty.project#10863]
Hi, I try toibuild Jetty from source code, the version is 12..03, the latest version, but I encounter an error when building, please check this issue, thanks.

build command:

mvn  -Pfast clean install

![image](https://github.com/jetty/jetty.project/assets/150114018/b8de2b10-bad2-46b1-b545-d18ef715bbb6)

**Comment by Helly987** [comment]
$ git clone https://github.com/eclipse/jetty.project.git
$ cd jetty.project
$ mvn -Pfast clean install # fast build bypasses tests and other checks

The version for this with git is jetty-10.0.19, not the latest version 12.0.3.

**Comment by olamy** [comment]
what jvm version are you using?
jdk 17 is required as minimum.
default branch in git is still `jetty-10.0.x`

**Comment by joakime** [comment]
@Helly987 run `mvn --version` and copy/paste the results into here (please avoid using screenshots, it doesn't help others find this issue).

**Comment by Helly987** [comment]
Thank you for checking.Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: C:\Program Files\maven-3.8.4
Java version: 11.0.18, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-11
Default locale: en_US, platform encoding: GBKOS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"                                                                                      发自我的 iPhone在 2023年11月7日，22:13，Joakim Erdfelt ***@***.***> 写道：﻿
@Helly987 run mvn --version and copy/paste the results into here (please avoid using screenshots, it doesn't help others find this issue).

**Comment by sbordet** [comment]
@Helly987 you need Java 17 to build Jetty 12.
Also, Windows builds are typically more unstable due to filesystem issues.

**Comment by olamy** [comment]
@Helly987 To build Jetty 12.x you will need jdk 17 as minimum and Maven 3.9.x+ as well.
https://github.com/jetty/jetty.project/blob/jetty-12.0.x/documentation/jetty-documentation/src/main/asciidoc/contribution-guide/4-build.adoc

**Comment by Helly987** [comment]
Ok，I will try. Thanks发自我的 iPhone在 2023年11月13日，18:11，Simone Bordet ***@***.***> 写道：﻿
@Helly987 you need Java 17 to build Jetty 12.
Also, Windows builds are typically more unstable due to filesystem issues.

**Comment by janbartel** [comment]
Closing as answered.
