### ISSUE TITLE
How to set HttpConfiguration.securePort when the HTTPS port is dynamic?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10870]
**Jetty Version**
12.0.3

**Java Version**
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)

**Question**
I think I identified a potential design problem... My server uses `SecureRedirectHandler` which means that I must set `HttpConfiguration.securePort()` before the server is started, but when I run unit tests I always allocate the HTTPS port dynamically (so I can run tests concurrently). So I can't know the port number ahead of time.

Instead of passing a secure port into `HttpConfiguration`, wouldn't it be easier to just pass the `NetworkConnector` that `SecureRedirectHandler` needs to redirect to in its own constructor?

**Comment by cowwoc** [comment]
The following code worked for me:

``` java
import org.eclipse.jetty.http.HttpHeader;
import org.eclipse.jetty.http.HttpStatus;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.server.NetworkConnector;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Response;
import org.eclipse.jetty.util.Callback;
import org.eclipse.jetty.util.URIUtil;

/**
 * A SecuredRedirectHandler for servers whose securePort is not known at configuration-time.
 */
public class DynamicSecuredRedirectHandler extends Handler.Wrapper
{
	/**
	 * The redirect code to send in response.
	 */
	private final int _redirectCode;
	/**
	 * The secure connector to redirect to.
	 */
	private final NetworkConnector _secureConnector;

	/**
	 * Uses moved temporarily code (302) as the redirect code.
	 *
	 * @param secureConnector the secure connector to redirect to
	 * @throws NullPointerException if {@code secureConnector} is null
	 */
	public DynamicSecuredRedirectHandler(NetworkConnector secureConnector)
	{
		this(secureConnector, null, HttpStatus.MOVED_TEMPORARILY_302);
	}

	/**
	 * Use supplied code as the redirect code.
	 *
	 * @param secureConnector the secure connector to redirect to
	 * @param code            the redirect code to use in the response
	 * @throws NullPointerException     if {@code secureConnector} is null
	 * @throws IllegalArgumentException if parameter is an invalid redirect code
	 */
	public DynamicSecuredRedirectHandler(NetworkConnector secureConnector, int code)
	{
		this(secureConnector, null, code);
	}

	/**
	 * Uses moved temporarily code (302) as the redirect code.
	 *
	 * @param secureConnector the secure connector to redirect to
	 * @param handler         the handler to wrap
	 * @throws NullPointerException if {@code secureConnector} is null
	 */
	public DynamicSecuredRedirectHandler(NetworkConnector secureConnector, Handler handler)
	{
		this(secureConnector, handler, HttpStatus.MOVED_TEMPORARILY_302);
	}

	/**
	 * Use supplied code as the redirect code.
	 *
	 * @param secureConnector the secure connector to redirect to
	 * @param handler         the handler to wrap
	 * @param code            the redirect code to use in the response
	 * @throws NullPointerException     if {@code secureConnector} is null
	 * @throws IllegalArgumentException if parameter is an invalid redirect code
	 */
	public DynamicSecuredRedirectHandler(NetworkConnector secureConnector, Handler handler, int code)
	{
		super(handler);
		if (secureConnector == null)
			throw new NullPointerException("secureConnector may not be null");
		if (!HttpStatus.isRedirection(code))
			throw new IllegalArgumentException("Not a 3xx redirect code");
		_redirectCode = code;
		_secureConnector = secureConnector;
	}

	@Override
	public boolean handle(Request request, Response response, Callback callback) throws Exception
	{
		if (request.isSecure())
		{
			// Nothing to do here.
			return super.handle(request, response, callback);
		}

		HttpConfiguration httpConfig = request.getConnectionMetaData().getHttpConfiguration();
		String secureScheme = httpConfig.getSecureScheme();
		String url = URIUtil.newURI(secureScheme, Request.getServerName(request), _secureConnector.getLocalPort(),
			request.getHttpURI().getPath(), request.getHttpURI().getQuery());
		// TODO need a utility for this
		response.getHeaders().put(HttpHeader.LOCATION, url);
		response.setStatus(_redirectCode);
		response.write(true, null, callback);
		return true;
	}
}
```

Instead of initializing the securedHandler using `new SecuredRedirectHandler(contextHandler)` I used `new DynamicSecuredRedirectHandler(https3Connector, contextHandler)`. The key line in the alternative implementation is using `_secureConnector.getLocalPort()` instead of the `HttpConfiguration.securePort`.

Thoughts?

**Comment by joakime** [comment]
It has potential.
We need to verify if the work going with regards to `isSecure()` in Issue #10775 and PR #10853 will still allow this technique.

**Comment by joakime** [comment]
We cannot totally ignore `HttpConfiguration.securePort` as that's relevant for systems behind intermediaries (eg: load balancers, TLS offloaders, etc)

**Comment by sbordet** [comment]
@cowwoc in your tests you just need:

```java
Server server = ...;
HttpConfiguration httpConfig = ...;
ServerConnector secureConnector = ...;
...
server.start();

httpConfig.setSecurePort(secureConnector.getLocalPort());

// Your test code here.
```

**Comment by cowwoc** [comment]
@sbordet I was afraid to use this approach because there is no guarantee that someone didn't use the HttpConfiguration prior to being changed. Is this a safe assumption to be making?

**Comment by joakime** [comment]
@cowwoc that usage is safe.

We use it ourselves in our own unit testing

one example:

https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/SecuredRedirectHandlerTest.java#L87-L97

**Comment by cowwoc** [comment]
@joakime I've almost got this working but I've run into one last complication.

I need an event listener that will be invoked before `QuicServerConnector.open()` is invoked, and I can't find one.

First, let me restate the problem. I'm trying to spin up a server that responds to HTTP/1.1, HTTPS 1.1, HTTP/2, HTTP/3. My goal is to bind HTTP to one port and HTTPS to a second port. After much research, I now understand that I need 3 connectors: one for HTTP 1.1, a second one for HTTPS 1.1 and HTTP/2, and a third one for HTTP/3.

I expect the HTTP/2 connector to bind to a TCP/IP port and the HTTP/3 connector to bind to the same port, but this time on UDP. So far so good.

The problem is that the HTTP/2 connector uses a dynamic port number. I cannot set the HTTP/3 connector's port after the server has started because by that point it has already bound itself to another port.

I tried solving this by doign the following:

```
http2Connector.addEventListener(new LifeCycle.Listener()
{
	@Override
	public void lifeCycleStarted(LifeCycle event)
	{
		int actualPort = connector.getLocalPort();
		log.info("HTTP/2 bound to port {}", actualPort);
		httpConfig.setSecurePort(actualPort);
	}
});

http3Connector.addEventListener(new LifeCycle.Listener()
{
	@Override
	public void lifeCycleStarting(LifeCycle event)
	{
		int actualPort = httpConfig.getSecurePort();
		log.info("HTTP/3 bound to port {}", actualPort);
		connector.setPort(actualPort);
	}
});
```

The http2 connector works wonderfully. The problem is that the http3Connector's `lifeCycleStarting` is invoked *after* `QuicServerConnector.open()` is invoked, and by that point it has already bound itself to a port.

Is there an event listener I can register that will get invoked before `QuicServerConnector.open()` so I can change the port number? The only workaround I've come up with is to subclass each connector and override its `open()` method. This works, but is fragile. Today `ServerConnector` has two `open()` methods. Tomorrow it might have a different number. Maybe we need to add a new method to the `LifeCycle.Listener` that will be invoked prior to `open()`?

Thank you.

**Comment by sbordet** [comment]
What do you exactly mean by "dynamic port number"? 
You mean it's a random number that you receive via configuration?
Or it is an _ephemeral_ port assigned at `bind()`?

If the former, the same configuration value can be used for HTTP/2 and HTTP/3.

If the latter you can first obtain an ephemeral port and the use the value for both connectors:

```java
public int freePort() throws IOException
{
    try (ServerSocket server = new ServerSocket())
    {
        server.setReuseAddress(true);
        server.bind(new InetSocketAddress("localhost", 0));
        return server.getLocalPort();
    }
}
```

**Comment by cowwoc** [comment]
By "dynamic port number" I mean an ephemereal port that is assigned by `bind()`.

Reading the Javadoc of `ServerSocket.setReuseAddress(true)`, I don't think it works the way you think it works. The flag guarantees that we can bind a port that is currently in the process of a `TIMED_WAIT` shutdown. It doesn't guarantee that when the above code closes the `ServerSocket` and returns the port number to Jetty that:

1. Jetty will be able to bind to the port (because we'll be back in the `TIMED_WAIT` state again which will block binding.
2. That some other process won't steal the port.

For this reason, I think overriding `open()` is the superior approach. It guarantees that the port number that is the same one that Jetty has already successfully bound. It cannot fail to bind, nor can it be stolen by another process.

Here is what that code looks like:

```
ServerConnector connector = new ServerConnector(server, sslContextFactory, proxy, ssl, alpn, http2, http11)
{
	@Override
	public void open() throws IOException
	{
		super.open();
		portOpened();
	}

	@Override
	public void open(ServerSocketChannel acceptChannel) throws IOException
	{
		super.open(acceptChannel);
		portOpened();
	}

	private void portOpened()
	{
		// When using a dynamic port number (e.g., unit tests), we need to defer some configuration until
		// the actual port number is determined.
		int actualPort;
		if (httpsPort > 0)
			actualPort = httpsPort;
		else
			actualPort = getLocalPort();
		httpConfig.setSecurePort(actualPort);
	}
};
```

Thoughts?

**Comment by sbordet** [comment]
@cowwoc the code in your latest comment will work for now (you can simplify it by just overriding `open()` unless you use `open(ServerSocketChannel)`.

As for integrating it in Jetty, I think I would prefer a more explicit mechanism, something like a `NetworkBindListener` or `OpenListener` for those connectors that can bind, so you would be able to use an API rather than overriding.

**Comment by cowwoc** [comment]
@sbordet Agreed. Are you able to transform this issue into an enhancement request to that end? You might need to update the title as well.

**Comment by sbordet** [comment]
@cowwoc I gave this a try, but I don't think it needs new code, as it seems to me that it is already doable:

```java
ServerConnector secure = ...;
ServerConnector plain = ...;
HTTP3ServerConnector http3 = ...;

// You want to add the connectors in this order: secure, plain, http3,
// so that secure starts first and can operate on the other two.
server.addConnector(secure);
server.addConnector(plain);
server.addConnector(http3);

// Add a listener to the secure Connector.
secure.addEventListener(new LifeCycle.Listener()
{
    @Override
    public void lifeCycleStarted(LifeCycle lifeCycle)
    {
        if (lifeCycle instanceof NetworkConnector networkConnector)
        {
            int port = networkConnector.getLocalPort();

            // Configure the plain connector for secure redirects.
            plainConfig.setSecurePort(port);

            // Configure the HTTP3 connector port to be the same as HTTPS/HTTP2.
            http3.setPort(port);
    }
});

server.start();
```

Can you give it a go and tell us if this works for you?

**Comment by sbordet** [comment]
Fixed by #11085.

**Comment by cowwoc** [comment]
@sbordet I've hit a bit of a snag with using the `lifeCycleStarted` event to set the port numbers.

Jetty invokes `connector.open()` on all connectors, followed by `connector.start()` on all connectors.

By the time the `lifeCycleStarted` event is thrown it is too late, because `QuicServerConnector.open()` was already invoked and was bound to a local port. It sounds like we want to get notified after `open()` instead of after `start()`, but as far as I can tell no such event listener exists.

Any ideas?

The only approach that works for now is to override `open()` as I discussed at https://github.com/jetty/jetty.project/issues/10870#issuecomment-1816576472

**Comment by cowwoc** [comment]
Ah. I figured it out. You need to replace:

```
secure.addEventListener(new LifeCycle.Listener()
{
    @Override
    public void lifeCycleStarted(LifeCycle lifeCycle)
    {
        if (lifeCycle instanceof NetworkConnector networkConnector)
        {
            int port = networkConnector.getLocalPort();
```

from your code with:

```
secure.addEventListener(new Container.Listener()
{
    @Override
    public void beanAdded(Container parent, Object child)
    {
        if (child instanceof ServerSocketChannel serverSocket)
        {
          int port = serverSocket.socket().getLocalPort();
```

Does any documentation need to get updated? Or is your code snippet undocumented?

**Comment by sbordet** [comment]
@cowwoc you are right, but using `instanceof ServerSocketChannel` is not generic enough.

Reopening this issue to provide a correct fix.
