### ISSUE TITLE
Support .well-known serving in handlers

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1087]
The `.well-known` directory is being used for more and more things to automate operations related to websites. 

For example, see #794.
Also, Let's Encrypt uses the `.well-known` directory to automate the issue of certificates.

For "normal" contexts, this is rather easy, since it's enough to add the `.well-known` directory to the `resourceBase` and it's done.

For less "normal" contexts, this is not doable.
For example, a `MovedContextHandler` would need to be able to serve content under `.well-known` and if that fails, fall back to the "moved" behavior.
Same goes for contexts that use a `RedirectHandler`.

The major problem is trying to serve the "/" URI.

Currently, a handler that has a `resourceBase` will try to serve `/` as a directory, or give a 403 if directory listing is not allowed.

What would be needed is a handler with some logic along these lines:
- If URI matches `/.well-known` and descendants => serve it like a `ResourceHandler` would from file system
- If URI matches `/` => forward to next/wrapped handler

So that is basically a `ResourceHandler`, but only for a particular directory (or set of paths).

If there are ways to achieve this, will be great to know.

**Comment by sbordet** [comment]
Doh. 

It's enough to add a context mapped to `/.well-known`. 
It will be more specific than `/` and so preferred.

One such context could serve for multiple virtual hosts.

**Comment by joakime** [comment]
@sbordet and @WalkerWatch would it be worth documenting this? 

I can imagine this being a pretty common setup.

**Comment by gregw** [comment]
I think we should create a `demo-base/webapps/well-known` and a `demo-base/webapps/well-known.xml` in the standard jetty distro and then document it as well.

**Comment by joakime** [comment]
Interestingly, the concept of `/.well-known/` in a URI is actually an RFC.

https://tools.ietf.org/html/rfc5785

**Comment by joakime** [comment]
From a `${jetty.base}` point of view, I think supporting something like we do for `${jetty.base}/webapps/ROOT/`, but for this usecase.

Perhaps something like `${jetty.base}/webapps/WELL-KNOWN/` is a good start.

I didn't suggest ``${jetty.base}/webapps/.well-known/` as that doesn't work (the directory starting with `.` is seen as a hidden directory by the DeploymentManager currently.

We could make that specific directory `/.well-known/` an exception in DeploymentManager.

If we go this route, should we allow directory listing by default?

For embedded-jetty, a `ResourceHandler` with `.well-known` directory support is already well supported.

**Comment by sbordet** [comment]
I don't think we need anything special, this XML file is enough:

```xml
<Configure class="org.eclipse.jetty.server.handler.ContextHandler">
  <Set name="contextPath">/.well-known</Set>
  <Set name="handler">
    <New class="org.eclipse.jetty.server.handler.ResourceHandler">
      <Set name="resourceBase">/your/directory/.well-known</Set>
      <Set name="directoriesListed">false</Set>
    </New>
  </Set>
</Configure>
```
I guess it's only a documentation issue, and perhaps an example in `demo-base`.
