### ISSUE TITLE
HashSessionManager lazy loading is just not lazy enough

### ISSUE THREAD

**Issue by hoomanv** [eclipse/jetty.project#1088]
Currently (on 9.3.14) HashSessionManager's lazy loading works like this:
On server start, loading of all stored sessions into memory will be delayed until the server receives the first request for a session, or the session scavenger runs for the first time, whichever happens first.
In other words lazy load means more like delayed load.

On the other hand, with IdleSavePeriod set, idle sessions will eventually leave memory to free up heap space.

Having said that, I'm not so convinced that lazyLoad with the way it works now is of any use. Also because the first time it loads every stored session back into memory, that somehow violates the idea behind setting idleSavePeriod.

I think the correct implementation would be to not load all sessions all together, but only load one if requested for.

**Comment by janbartel** [comment]
@hoomanv I have good news for you - we have compeletely rearchitected sessions in jetty-9.4. There is now a new session-store-file module that you can enable that will persist sessions to the filesystem and it indeed will lazily load each session as necessary. Many many other things have changed on sessions, including how to modify the behaviour of the in-memory cache - indeed whether you want an in-memory cache at all.  [Download jetty-9.4.0.RC1 from maven central ](http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.0.RC1/jetty-distribution-9.4.0.RC1.tar.gz) and have a play with it.
