### ISSUE TITLE
Support the "Partitioned" cookie attribute

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10891]
**Jetty version(s)**
10+

**Enhancement Description**
A proposal for a new cookie attributed called `Partitioned` is underway, with plans from Chrome and Firefox to support it in the near future.

See https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies (and related links).

This is a server-side only change, as `HttpClient` does not have the concept of a "top-level context" (i.e. a web page) under which other requests are made, and the current behavior of the client-side `HttpCookieStore` is equivalent to `SameSite=Strict`, i.e. cookies set by a domain are only sent with requests for the same domain.

**Comment by joakime** [comment]
Looks like the Cookie spec RFC6265 is being updated to handle some of the new things that this `Partitioned` spec is introducing.  (eg: the `__Secure` and `__Host` prefixes, among other things)

https://datatracker.ietf.org/doc/draft-ietf-httpbis-rfc6265bis/

**Comment by olamy** [comment]
chrome as well https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned
