### ISSUE TITLE
Jetty 11: no longer possible to override WebSocket RemoteEndpoint 

### ISSUE THREAD

**Issue by darnap** [eclipse/jetty.project#10893]
**Jetty Version**
11.0.17

**Java Version**
11

**Question**
With Jetty 9 it was possible to configure a custom RemoteEndpointFactory to provide your own implementation of RemoteEndpoint. This allowed efficient handling of cases in which the application could send TEXT frames from existing byte arrays (e.g. already serialized UTF8 data) without going through a needless String conversion.

Jetty 11 does not seem to allow this any longer. Is there an equivalent feature available, or plan to implement one? 
Thanks

**Comment by joakime** [comment]
Sounds like you want to use the low level websocket API, and not the high level jakarta.websocket or Jetty WebSocket API.

**Comment by sbordet** [comment]
@darnap we currently do not support custom implementations.

You should be able to send binary, and the application on the receiving side would convert to String if necessary.

Please reopen if you want to detail your use case.
