### ISSUE TITLE
SSL client certificates do not work in Jetty 9.0.0.RC2

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#109]
migrated from Bugzilla [#402626](https://bugs.eclipse.org/bugs/show_bug.cgi?id=402626)
status REOPENED severity _normal_ in component _server_ for _9.0.1_
Reported in version _9.0.0.RC2_ on platform _PC_
Assigned to: Simone Bordet

Original attachment names and IDs:
- _[jetty9-client-cert-bug.tar](https://bugs.eclipse.org/bugs//attachment.cgi?id=228050)_ (ID 228050)

On 2013-03-07 05:11:37 -0500, Ben Summers wrote:

> Created attachment 228050
> tar archive containing keystore & client cert generation scripts and modified example config
> 
> I am porting my application to Jetty 9, and while everything else works perfectly and the API is much improved, I cannot get SSL client certificates to work.
> 
> In the attached archive, there is a script which generates a Java keystore containing:
> - A self-signed server certificate
> - A CA for client certificates
> 
> It also generates an example client certificate, client.pkcs12, for you to use to test.
> 
> The supplied configuration files are the examples from the distribution, except:
> - Change keystore passwords to 'password'
> - Add <Set name="NeedClientAuth">true</Set>
> 
> To test:
> - Run ./makekeystore.sh
> - Start the Jetty 9 server using the configuration files, eg using ./run.sh after setting CLASSPATH
> - Import the client.pkcs12 file on your computer (password is 'password')
> - Attempt to connect to the server https://HOSTNAME:8443 with the appropriate hostname.
> 
> You will get a certificate warning following by a "choose client certificate" prompt. (I'm using Safari on a Mac). But after that, the connection fails.
> 
> Removing NeedClientAuth shows the rest of the SSL server config is OK, but obviously it doesn't ask for a client cert.
> 
> I have tried a similar configuration on Jetty 7. Client certs work with this version, so I believe the keystore generation and configuration is correct. (use same makekeystore.sh script, copy example configs, change password and add NeedClientAuth, run server, import client cert, connect to server.)

On 2013-03-07 16:39:14 -0500, Ben Summers wrote:

> I have confirmed that the current testing version, jetty-9.0.0.v20130306, also has this problem.

On 2013-03-07 17:00:42 -0500, Greg Wilkins wrote:

> Ben,
> 
> thanks for the report and test harnesses required to replicate.
> 
> I will look today and see if we can get a fix into the 9.0.0 branch, but currently I'm expecting that we'll miss that train and this will be fixed in 9.0.1.
> 
> I'll see if we can use your tests to create a unit test for client certificate processing.
> 
> Note that jetty 9 has an entirely new SSL connection, so I'm guessing we just forgot to turn on need client cert or similar.
> 
> cheers

On 2013-03-07 17:02:51 -0500, Ben Summers wrote:

> Thanks for looking at it, very much appreciated. It'd be great to have a fix in 9.0.0 if at all possible.

On 2013-03-07 20:12:32 -0500, Greg Wilkins wrote:

> This is the core exception that is causing the handshake failure:
> 
> javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>   at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1364)
>   at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:513)
>   at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:790)
>   at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:758)
>   at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
>   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:488)
>   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:216)
>   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:589)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:520)
>   at java.lang.Thread.run(Thread.java:722)
> Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>   at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
>   at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1703)
>   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:278)
>   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
>   at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1673)
>   at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:176)
>   at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
>   at sun.security.ssl.Handshaker$1.run(Handshaker.java:808)
>   at sun.security.ssl.Handshaker$1.run(Handshaker.java:806)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1301)
>   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:547)
>   ... 5 more
> Caused by: java.security.cert.CertificateException: No name matching localhost found
>   at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:208)
>   at sun.security.util.HostnameChecker.match(HostnameChecker.java:93)
>   at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:347)
>   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:255)
>   at sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:132)
>   at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1660)
>   ... 12 more

On 2013-03-07 20:37:57 -0500, Greg Wilkins wrote:

> I can't yet find a way to get the trustmanager used by the ssl context to trust localhost.   I can see reports of setting a hostnamechecker, but can't find the right magic juice to do this for SSLEngine.
> 
> Can you configure jetty logging to printout ignored exceptions, so you should be able to verify that you get the same exception.
> 
> We then have to work out how to make it trust localhost, which will either make it work, or reveal the next problem.

On 2013-03-08 04:31:26 -0500, Ben Summers wrote:

> I'm afraid I couldn't check the error as I can't seem to get it to display the ignored errors. However, the exception and a quick look at the OpenJDK sources have enabled me to work out the problem.
> 
> It's not that client certs don't work, it's that Jetty 9 has a surprising default configuration which is different to that in Jetty 7: it's performing hostname verification of the client on the server side!
> 
> Client certificates won't generally use hostnames as common names, as they're generally identifying people not hosts, and just rely on the signing CA having their root certificate in the keystore. Verifying the hostname of the client is probably a rather unusual configuration.
> 
> I resolved the issue in my application by calling setEndpointIdentificationAlgorithm(null) on the SslContextFactory.
> 
> If you would like to restore the Jetty 7 behaviour, which probably makes sense, then, if and only if the SslContextFactory is ONLY used on the server, you just need to change
> 
> ```
> /** EndpointIdentificationAlgorithm - when set to "HTTPS" hostname verification will be enabled */
> private String _endpointIdentificationAlgorithm = "HTTPS";
> ```
> 
> to
> 
> ```
> /** EndpointIdentificationAlgorithm - when set to "HTTPS" hostname verification of the client certificate will be enabled */
> private String _endpointIdentificationAlgorithm = null;
> ```
> 
> If this code _is_ shared with Jetty client, then this would be a very bad change, for obvious reasons.
> 
> I suspect the setEndpointIdentificationAlgorithm() Java API is confusingly named. I would have called it setEndpointCommonNameMatchingRules(). If you look in the JDK sources, you can see that the certificate is verified regardless of this option.
> 
> Thanks for your help in tracking this down.
> 
> Incidentally, I couldn't work out how to set null in the XML configuration. My reading of the docs meant I thought this would do the job:
> 
> ```
>   <Set name="EndpointIdentificationAlgorithm"></Set>
> ```
> 
> But it doesn't seem to.
> 
> (For showing ignored errors, I tried this command line:
> 
> java -Dorg.eclipse.jetty.util.log.IGNORED=true -Dorg.eclipse.jetty.util.log.stderr.LONG=true -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog org.eclipse.jetty.xml.XmlConfiguration jetty.xml jetty-https.xml
> 
> which I thought should have worked according to the docs, but didn't.)

On 2013-03-08 08:13:46 -0500, Jesse McConnell wrote:

> given the migration of docs from the wiki to the docbook setup can you point out the bad docs?
> 
> (jetty-9 docs) 
> 
> http://www.eclipse.org/jetty/documentation/current/

On 2013-03-08 08:16:52 -0500, Ben Summers wrote:

> http://www.eclipse.org/jetty/documentation/current/reference-section.html#jetty-xml-arg
> 
> (referred to by the <Set> section.)
> 
> In the example, it gives:
> 
> <Arg></Arg> 
> 
> Which I tried, but it didn't work.
> 
> It's possible the docs are correct and I didn't read them properly. Does it use the signature of the setter function to determine type automatically?

On 2013-03-11 02:44:42 -0400, Greg Wilkins wrote:

> Ben,
> 
> thanks for progressing this.
> 
> The best logging documentation is currently at http://wiki.eclipse.org/Jetty/Feature/Jetty_Logging
> 
> and all you need to see the exception is 
> 
> -Dorg.eclipse.jetty.server.HttpConnection.LEVEL=debug
> 
> or just
> 
> -Dorg.eclipse.jetty.LEVEL=debug
> 
> (sorry was miss information about the IGNORED)
> 
> We will add a logging section to Jetty-9 doco soon.
> 
> Looking at other aspects now

On 2013-03-11 03:01:59 -0400, Greg Wilkins wrote:

> (In reply to comment # 8)
> 
> > http://www.eclipse.org/jetty/documentation/current/reference-section.
> > html#jetty-xml-arg
> > 
> > (referred to by the <Set> section.)
> > 
> > In the example, it gives:
> > 
> > <Arg></Arg> 
> > 
> > Which I tried, but it didn't work.
> > 
> > It's possible the docs are correct and I didn't read them properly. Does it
> > use the signature of the setter function to determine type automatically?
> 
> I added   
> 
>   <Set name="EndpointIdentificationAlgorithm"></Set>
> 
> to the section in jetty-https.xml that starts with
>   <New id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
> 
> and that worked fine!

On 2013-03-13 18:26:32 -0400, Greg Wilkins wrote:

> Changed the default so that host identity is not done by default.

On 2013-03-13 18:28:05 -0400, Greg Wilkins wrote:

> Simone,
> 
> can you update the client code/examples so that SslContextFactory.setEndpointIdentificationAlgorithm("HTTPS") is done.

On 2013-06-12 04:29:37 -0400, Prasad BLV wrote:

> Are there any updates on the above mentioned issue. I am also facing same problems in 9.0.3.v20130506 version.

On 2013-06-12 04:55:21 -0400, Ben Summers wrote:

> Prasad -- read comment 6 and following comments for the solution.

On 2013-06-12 05:38:23 -0400, Prasad BLV wrote:

> Thank you for your quick reply. I tried the configuration mentioned after comment 6 but I am getting the below given exception : 
> 
> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
>         at sun.security.ssl.SSLSessionImpl.getPeerCertificateChain(SSLSessionImpl.java:446)
>       at org.eclipse.jetty.util.ssl.SslContextFactory.getCertChain(SslContextFactory.java:1354)
>         at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:104)
>         at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:54)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:259)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:225)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:225)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
>         at java.lang.Thread.run(Thread.java:722)
> 
> Below given is my configuration for SSLContext Factory :
> <Configure id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
>   <Set name="KeyStorePath"><Property name="jetty.home" default="." />/<Property name="jetty.keystore" default="etc/keystore"/></Set>
>   <Set name="KeyStorePassword"><Property name="jetty.keystore.password" default="password"/></Set>
>   <Set name="KeyManagerPassword"><Property name="jetty.keymanager.password" default="password"/></Set>
>   <Set name="TrustStorePath"><Property name="jetty.home" default="." />/<Property name="jetty.truststore" default="etc/keystore"/></Set>
>   <Set name="TrustStorePassword"><Property name="jetty.truststore.password" default="password"/></Set>
>   <Set name="EndpointIdentificationAlgorithm"></Set>
>   <New id="sslHttpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
>     <Arg><Ref refid="httpConfig"/></Arg>
>   <Call name="addCustomizer">
>       <Arg><New class="org.eclipse.jetty.server.SecureRequestCustomizer"/></Arg>
>     </Call>
>   </New>
> </Configure>
> 
> Please let me know if missing anything...

**Comment by joakime** [comment]
This was implemented in commit 92400393667236c9d4a2823e610d725af0213cd3
