### ISSUE TITLE
Allow WebSocketUpgradeFilter to be used by WEB-INF/web.xml

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1090]
The current implementation of `WebSocketUpgradeFilter` will not work in `WEB-INF/web.xml` if you have the JSR-356 features enabled.

Alter the `WebSocketUpgradeFilter` (and associated `WebSocketServerContainerInitializer`) to use the `WebSocketUpgradeFilter` defined in a `WEB-INF/web.xml` (if defined)

**Comment by joakime** [comment]
Work completed in 9.2.x and merged up.

**Comment by joakime** [comment]
Not working as intended, the storage of the WSUF instance in the attribute conflicts between Native WS and JS356.

**Comment by sbordet** [comment]
@joakime, I believe this has been fixed by 51f68dc and subsequent merges ?

**Comment by joakime** [comment]
I agree. closing
