### ISSUE TITLE
Review completion of Handler's callback

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#10916]
**Jetty version(s)**
12+

**Description**
After #10844, idle timeouts are "transient" failures; we need to clarify whether the `Handler` callback may be automatically failed by the implementation, and exactly in what cases.

I see one obvious case where the `Handler` callback should be failed automatically: when the `Handler` chain has not been called.
This may happen in these cases: a bad request (e.g. bad headers, etc.) that should result in an automatic 400, an idle timeout while parsing the headers, and a network close while parsing the headers.

After the `Handler` chain has been called, I don't think we should automatically fail the `Handler` callback.
This is because applications can always register a failure listener.

For example, in case of idle timeout, no demand, no pending writes, no idle timeout listeners, the idle timeout is dropped.

For example, in case of RST_STREAM failures, the `HttpChannel` should be marked as failed, and at that point any subsequent operation will fail (so the application will know), or a failure listener will be notified.

Note that for HTTP/1 we are not interested in reads while processing the request, so a client network close will be "silent" until the application tries to read or write, so in absence of failure listeners the behavior of HTTP/1 and HTTP/2/3 will be the same.

If there is a failure listener, HTTP/2/3 will benefit from it when receiving a RST_STREAM, since the failure will be notified immediately.

**Comment by sbordet** [comment]
@gregw this issue is to collect the thoughts about what to do with the `Handler` callback that have been mentioned in other issues/pr, or otherwise discussed, so we track the decision.

**Comment by lorban** [comment]
Now that Core will never complete the handler's callback on behalf of the user, shouldn't we add some facility to deal with a user's handler who forgets to complete the callback? Maybe a handler wrapper with some configurable timeout mechanism that needs to be added to the chain?

If we don't, we risk leaking internal resources because of a user error; and that would be very hard to track down if that happens very slowly. While if we had such a facility, we could always ask the user to configure it to check if the Jetty resources aren't leaked anymore.

**Comment by sbordet** [comment]
@gregw I think we agree that:

* Automatically fail Handler callback if Handler tree not called.
* Otherwise, Handler callback must be completed by application, possibly registering listeners.

I'm leaving the issue open to decide whether to provide an out-of-the-box Handler that alerts if the callback is not completed.
Something like:

```java
class EnsureCallbackCompletionHandler extends Handler.Wrapper
{
    private long timeout;
    private boolean completeAtTimeout;

    @Override
    public void handle(Request request, Response response, Callback callback)
    {
        // Start timeout if any configured.
        // Wrap the callback to detect if it's completed.
        // If timeout fires and not completed, emit warning and complete the callback if configured so.
    }
}
```

Note that the callback that is being failed may not be the outermost one created by wrapping, but it'll guarantee the safety of the server.

**Comment by sbordet** [comment]
It was agreed that automatic completion of the `Handler` callback should not be done, unless the `Handler` has not been invoked yet.

This work has been done in #10912 and #10920, so this issue can be closed.

**Comment by gregw** [comment]
> @gregw I think we agree that:
> 
> * Automatically fail Handler callback if Handler tree not called.

or if it is called and returns false.


> * Otherwise, Handler callback must be completed by application, possibly registering listeners.
> 
> I'm leaving the issue open to decide whether to provide an out-of-the-box Handler that alerts if the callback is not completed.

I think it is a good example Handler to have, even if only for documentation.    There are three cases that it needs to deal with:
 + Handle called but has not returned (should get a stack trace of the thread and perhaps try to interrupt it)
 + A demand/write/error callback has been called but has not returned (ditto stack trace)
 + Nothing is dispatched, everything has returned, but callback has not yet completed.

**Comment by sbordet** [comment]
@gregw filed https://github.com/jetty/jetty.project/issues/11072 about the proposed `Handler`.
