### ISSUE TITLE
POST request not handled

### ISSUE THREAD

**Issue by gverran** [eclipse/jetty.project#10910]
**Jetty Version**

Jetty 9.4.48.v20220622

**Jetty Environment**
Embedded Jetty

**Java Version**
Java 8

**Question**
First of all, in this specific instance, I am unable to upgrade to later versions of Jetty unless I am required to upgrade to the latest Jetty 9.4.x to address this issue.

I am using embedded Jetty.  In the logs attached, around line 1056, we are posting a call and getting a response on line 1111.
Following that, we are posting a subsequent call on line 1314, but in this case, the servlet is not getting the call at all.  I added a comment in the log around line 1316 whereby I specify that,  Comparing this call to the previous call, I am not seeing the content parsing as completed in the web service.  

I did check out the Jetty 9.4 code to attempt to figure out what the logging means, but I was unable to get much further with this.

Is there anybody who is very familiar with the logging to ascertain as to why I am not seeing content parsing been completed from line 1363 or so as compared to the previous call so that this call can make it to my servlet?   I noticed the logging "onContentComplete" on line 1085, but not after line 1362.

This did work in Jetty 9.3.x

[Log.txt](https://github.com/jetty/jetty.project/files/13438467/Log.txt)

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Support is provided for Jetty 10, Jetty 11, or Jetty 12.

**Comment by joakime** [comment]
If you have the same problem on Jetty 10, or Jetty 11, or Jetty 12 we will be happy to troubleshoot with you.

**Comment by sbordet** [comment]
@gverran did you figure out what it was?
Peeking at the logs, the client was not sending the content, so it did not seem to be a Jetty issue.

**Comment by gverran** [comment]
> @gverran did you figure out what it was? Peeking at the logs, the client was not sending the content, so it did not seem to be a Jetty issue.

I thought so too, but I did see some evidence in the logs which looks like a trimmed down payload whereby I saw some soap XML. around line 1360.  I got this tested in our UAT system and all was good.  We do some hardening for production which I would find odd would have an impact otherwise we would have seen issues years ago.
