### ISSUE TITLE
Jetty 12 documentation: references to jetty-maven-plugin

### ISSUE THREAD

**Issue by senivam** [eclipse/jetty.project#10925]
**Jetty version(s)**
Jetty 12

**Jetty Environment**
ee8, ee9, ee10

**Description**
Documentation for Jetty 12: https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#jetty-maven-plugin refers to maven plugin which does not exist. Since Jetty 12 jetty-maven-plugin is jetty-ee*-maven-plugin and this is not reflected in the documentation. This should be fixed.

**Comment by janbartel** [comment]
@senivam the documentation has been updated, but the update hasn't made it onto the eclipse site yet.
In the interim, you could download the docs from the nightly builds: https://oss.sonatype.org/content/repositories/jetty-snapshots/org/eclipse/jetty/documentation/jetty-documentation/12.0.4-SNAPSHOT/

I just checked it, and there's a few improvements I can make, so I've opened this PR: #10939

**Comment by senivam** [comment]
Thanks a lot for the help!

**Comment by joakime** [comment]
PR #10939 completed
