### ISSUE TITLE
AttributeNormalizer does not support combined resources

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#10926]
In Jetty 12 `AttributeNormalizer` throws `IllegalArgumentException` if the base resource is a `CombinedResource`. 

A comment was left saying

> Combined resources currently are not supported (see #8921) but such support could be added. That would require some form of (potentially expensive) existence check in expand() to figure out which URIAttribute actually contains the resource.

If a webapp has jars with files in `META-INF/resources` then the base resource is a `CombinedResource`, so we need support for `CombinedResource` with the `AttributeNormalizer`.

**Comment by janbartel** [comment]
See #8921

**Comment by joakime** [comment]
PR #10926 merged
