### ISSUE TITLE
MultiPart files should be written to disk by default

### ISSUE THREAD

**Issue by essobedo** [eclipse/jetty.project#10936]
**Description**

In Jakarta EE 10, the expected behavior when `fileSizeThreshold` is set to `0` aka the default value has been clearly specified as you can see [in the Javadoc](https://jakarta.ee/specifications/platform/10/apidocs/jakarta/servlet/multipartconfigelement#getFileSizeThreshold()).

I quote:

> A value of zero means files must always be written to disk. 

The current behavior of Jetty is not compliant since only strictly positive values are taken into account.

**Comment by essobedo** [comment]
A potential fix for it https://github.com/jetty/jetty.project/pull/10937

**Comment by joakime** [comment]
The first version of Jetty that supports EE10 / Servlet 6.0 specs (where this language about fileSizeThreshold value of 0) is Jetty 12 on the ee10 environment.

**Comment by joakime** [comment]
Jetty 12 has support for fileSizeThreshold value of 0 in the EE10 environment already.

See EE10 handling ...

https://github.com/jetty/jetty.project/blob/d1da7269f625603fe27849740e7c53c95991e989/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java#L129

Which uses jetty-core handling ...

https://github.com/jetty/jetty.project/blob/d1da7269f625603fe27849740e7c53c95991e989/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java#L344-L355

Which is implemented here ...

https://github.com/jetty/jetty.project/blob/d1da7269f625603fe27849740e7c53c95991e989/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java#L421-L432

**Comment by essobedo** [comment]
Yeah I've just realized that, thx for the quick feedback
