### ISSUE TITLE
Flaky test `IdleSessionTest.testNullSessionCache`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10942]
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee9

**Description**

`org.eclipse.jetty.ee9.session.IdleSessionTest.testNullSessionCache` sometimes fails with:

```
expected: <200> but was: <500>
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1710/testReport/junit/org.eclipse.jetty.ee9.session/IdleSessionTest/Parallel_Stage___Build___Test___JDK21___testNullSessionCache/

**Comment by sbordet** [comment]
Fixed by #10950.
