### ISSUE TITLE
Flaky test `ReservedThreadExecutorTest.testBusyEvict`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10943]
**Jetty version(s)**
12.0.x

**Jetty Environment**
All

**Description**
`org.eclipse.jetty.util.thread.ReservedThreadExecutorTest.testBusyEvict` sometimes fails with:

```
org.eclipse.jetty.util.thread.ReservedThreadExecutorTest$$Lambda/0x00000007c0448220 expected a value greater than <0> but <0> was equal to <0> within 10 seconds.
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1713/testReport/junit/org.eclipse.jetty.util.thread/ReservedThreadExecutorTest/Parallel_Stage___Build___Test___JDK21___testBusyEvict/

**Comment by sbordet** [comment]
Fixed by #10947.
