### ISSUE TITLE
[jetty-maven-plugin] jetty:run block resource files for editing in Windows

### ISSUE THREAD

**Issue by coinicon72** [eclipse/jetty.project#10952]
**Jetty version(s)**
Jetty-mavn-plugin 10.0.18, 11.0.15, 11.0.18

**Java version/vendor** `(use: java -version)`
openjdk 17 / 17.0.2 / 21.0.2, oracle jdk 17.0.9
 
**OS type/version**
Windows 10 / 11

**Description**
start webapp with `mvn jetty:run`, visit any simply html page from browser, things are fine here.
then try to edit html file while keep jetty running, but I get a error (`Failed to save 'hello.html': Unable to write file 'd:\works\temp\test-jetty-maven-plugin\src\main\webapp\hello.html' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'd:\works\temp\test-jetty-maven-plugin\src\main\webapp\hello.html')`) and can't save html file.

**How to reproduce?**
1. create a simple webapp which can be only has a single html file (say `hello.html`) under `src/main/webapp` dir
2. create basic `pom.xml` with `jetty-maven-plugin` configured
3. run `mvn jetty:run`
4. before step 5, use any editor to modify `hello.html` and save it, no problem at all.
5. open any browser and visit `http://localhost:8080/hello.html`, page will shows normally with correct content changed in step 4.
6. use any editor to modify `hello.html` again and save it, then error occurred. 

I attached my test project which only have two files (`pom.xml` and `hello.html`).

**NOTE**: I tested same project in WSL, things are fine, no any errors.

Thanks!
[test-jetty-maven-plugin.zip](https://github.com/jetty/jetty.project/files/13508257/test-jetty-maven-plugin.zip)

**Comment by janbartel** [comment]
I can't find the doco for this for jetty10/11/12 at the moment, but the solution is the same as for jetty9:  https://eclipse.dev/jetty/documentation/jetty-9/index.html#troubleshooting-locked-files-on-windows

**Comment by coinicon72** [comment]
Yes, the solution is work.

Thank you, sir.

BTW: Should this be documented in every version?

**Comment by janbartel** [comment]
@coinicon72 yes, the doco is a work-in-progress.
