### ISSUE TITLE
How to access HTTP/2 headers?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10955]
**Jetty Version**
12.0.3

**Jetty Environment**
Handler API

**Java Version**
21.0.1

**Question**
I am hitting my own server using Chrome. Chrome DevTools shows that it sends the HTTP/2 ":authority" header, but when I invoke org.eclipse.jetty.server.Request.getHeaders() on the server side I don't see it or any other HTTP/2-specific headers.

How are supposed to access the new headers?

**Comment by cowwoc** [comment]
I'm going to go out on a limb and guess that HTTP/2 pseudo headers are translated into `Request.getHttpURI().getAuthority()` and friends. Is that correct?

I'm trying to retrieve the equivalent of the `HOST` request header, indicating what hostname:port that the client hit to reach the server.

**Comment by gregw** [comment]
@cowwoc correct.  They are indeed pseudo headers and replace the URI in a HTTP/1.1 request line.  The authority is indeed where you should find them.
