### ISSUE TITLE
Simplify `Expect: 100-Continue` handling

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#10956]
**Jetty version(s)**
12

**Description**

There is duplicate handling for `Expect: 100-Continue` in jetty-12.
Also reports of hanging from #10513, so more testing is needed

**Comment by gregw** [comment]
@sbordet I asked the ietf http working group and was referred to [RFC9113 8.1](https://www.rfc-editor.org/rfc/rfc9113.html#name-http-message-framing), which says:
> A server can send a complete response prior to the client sending an entire request if the response does not depend on any portion of the request that has not been sent and received. When this is true, a server MAY request that the client abort transmission of a request without error by sending a [RST_STREAM](https://www.rfc-editor.org/rfc/rfc9113.html#RST_STREAM) with an error code of [NO_ERROR](https://www.rfc-editor.org/rfc/rfc9113.html#NO_ERROR) after sending a complete response (i.e., a frame with the END_STREAM flag set). Clients MUST NOT discard responses as a result of receiving such a [RST_STREAM](https://www.rfc-editor.org/rfc/rfc9113.html#RST_STREAM), though clients can always discard responses at their discretion for other reasons.

So if the server sends a response (or commits the headers) before commencing reading of the request (and hence causing a 100 to be sent), then once the response is complete, we need to terminate the stream with a reset(NO_ERROR), to ensure the client does not hang waiting to send the request body.   @lorban Apparently h3 is similar but a little different: https://datatracker.ietf.org/doc/html/rfc9114#section-4.1  

It is plausible that this is the cause of the hangs in #10513, but I don't see how this was working in jetty-10?  Perhaps we have just changed it enough to trigger this on a timing basis? or perhaps it is something else.

**Comment by gregw** [comment]
@sbordet I'm thinking that we should do a reset(NO_ERROR) for H2 consumeAll?

**Comment by sbordet** [comment]
@gregw I agree on the reset after `consumeAvailable()`.

**Comment by sbordet** [comment]
Fixed by #10957.
