### ISSUE TITLE
Jetty rewrite/Redirect via XML does not work with "?"

### ISSUE THREAD

**Issue by rgruschow01** [eclipse/jetty.project#1097]
Working with jetty (jetty-all-server-8.1.17.v20150415.jar) I am attempting to use the RedirectRegexRule and RewriteRegexRule. Here is how my xml file is setup:

<New id="RewriteHandler1" class="org.eclipse.jetty.rewrite.handler.RewriteHandler">
		<Set name="rewriteRequestURI">true</Set>
		<Set name="rewritePathInfo">false</Set>
		<Set name="originalPathAttribute">requestedPath</Set>

		<Call name="addRule">
			<Arg>
				<New class="org.eclipse.jetty.rewrite.handler.RedirectRegexRule">
					<Set name="regex">/some/url/test(.*)</Set>
					<Set name="replacement">/cxf/some/url/test$1</Set>
				</New>
			</Arg>
		</Call> 
		<Call name="addRule">
			<Arg>
				<New class="org.eclipse.jetty.rewrite.handler.RewriteRegexRule">
					<Set name="regex">/some/url/test(.*)</Set>
					<Set name="replacement">/cxf/some/url/test$1</Set>
				</New>
			</Arg>
		</Call>  
	</New>

My results show that if I go to https://127.0.0.1:8184/some/url/test/temp, the system sends me to the wanted new url of https://127.0.0.1:8184/cxf/some/url/test/temp. The problem is when I add a ? into the URL
entered: https://127.0.0.1:8184/some/url/test?wsdl
result: https://127.0.0.1:8184/cxf/some/url/test

I have tried using escape characters with the same results.

**Comment by joakime** [comment]
[Jetty 8 is EOL (End of Life)](https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html), and if this is a bug, it is unlikely to be fixed for Jetty 8.

IIRC, the rewrite rules for Jetty 8 were only path based, they did not operate on host, port, scheme, query, path param, fragment, etc ...

How are you accessing the "result" URI in your testing?

Example: The test cases for 9.3.14.v20161028 show how we test for the behavior with query parameters on `RewriteRegexRule`.

https://github.com/eclipse/jetty.project/blob/jetty-9.3.14.v20161028/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteRegexRuleTest.java

These tests show that the `HttpServletRequest` accessed information for a `Rewrite*Rule` behaves as designed, the [`HttpServletRequest.getQueryString()`](http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getQueryString--) reports the proper information for the query portion, and [`HttpServletRequest.getRequestURI()`](http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getRequestURI--) reports the path portion.

This is how the query parameters are presented in the usecase of a `Rewrite*Rule`, following the Servlet Spec rules.

**Comment by rgruschow01** [comment]
The result was found after I typed in the "entered" in the address bar with FireFox.

**Comment by joakime** [comment]
OK, that's "entered" covered, where did you get "result" from?

**Comment by rgruschow01** [comment]
the result is what is displayed in the address bar after hitting enter (using the "entered url") I am assuming its showing that rewrite and redirect is working, but dropping anything found from the ? on.

**Comment by joakime** [comment]
The rewrite rules wouldn't affect the location bar.

However, the redirect rules should.

This is not reproducible in Jetty 9.3.14.v20161028, and we even have [test cases specifically for it](https://github.com/eclipse/jetty.project/blob/jetty-9.3.14.v20161028/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RedirectRegexRuleTest.java#L81-L91).

**Comment by joakime** [comment]
Ah, i think i see your issue clearer now.

You have the same regex / replacement for both rewrite and redirect.
Don't do that, pick either the RedirectRegexRule or the RewriteRegexRule, not both.

If you want to see the change on your location bar (and incur more network round-trips) use RedirectRegexRule, otherwise use RewriteRegexRule.

**Comment by joakime** [comment]
Closing as question was answered, no bugs/issues to fix in code.
