### ISSUE TITLE
JSR356 Encoder#init is not called when created on demand

### ISSUE THREAD

**Issue by fbuecklers** [eclipse/jetty.project#1100]
I have created a BaseMessage class and 3 sub classes wich can be converted by one generic Encoder&lt;BaseMessage&gt; encoder.

Jetty correctly creates encoders for my subclasses but the init methods of the created Encoders are not called.

The reason seems to be in EncoderFactory#getWrapperFor implementation where the on demand wrapper creation doesn't call the Encoder#init method after creation.

Testet with Jetty 9.3.14.v20161028

**Comment by joakime** [comment]
Cannot replicate this.

Do you have a sample project that can replicate this?

**Comment by joakime** [comment]
Unable to Replicate.  Feel free to reopen if you have a reproduction case.

**Comment by ericljiang** [comment]
I'm encountering this in [9.4.18.v20190429](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.18.v20190429). It seems very similar to https://github.com/eclipse/jetty.project/issues/425. Jetty constructs and initializes (calls `init()`) an encoder instance upon connection but never uses it. Instead it creates a new instance upon calling `session.getBasicRemote().sendObject(event)` and never calls `init()` on the new instance. Debugging shows that the second instance is created by the same code @fbuecklers referenced:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/EncoderFactory.java#L139-L147

Working on providing a sample project soon.

**Comment by joakime** [comment]
@ericljiang interesting discovery.  reopened.

**Comment by joakime** [comment]
@lachlan-roberts do you recall any changes on `jetty-9.4.x` related to this?

I cannot seem to replicate this.

**Comment by lachlan-roberts** [comment]
@joakime not that I can recall, I don't think I've touched encoders in 9.4. 
I'll take a closer look and see if I can replicate the issue.

**Comment by lachlan-roberts** [comment]
@joakime I was able to reproduce this and have proposed a fix in PR #4987.

**Comment by lachlan-roberts** [comment]
The fix for this has been merged into 9.4.x with PR #4987 and will be available in a 9.4.31 release.
