### ISSUE TITLE
Insufficient configured threads: required=4 < max=4 for QueuedThreadPool[qtp538185145]@20140db9{STARTED,2<=2<=4,i=2,r=-1,t=96ms,q=0}[ReservedThreadExecutor@4a3631f8{reserved=0/1,pending=0}]

### ISSUE THREAD

**Issue by leonchen83** [eclipse/jetty.project#11008]
**Jetty Version**
jetty 12
**Jetty Environment**
ee10
**Java Version**

jdk 17

**Question**

we upgrade jetty 11  to jetty 12

the following code work well in jetty 11 but exception in jetty 12
```
ServletContextHandler sh = new ServletContextHandler();
		sh.addServlet(MockHttpService.class, "/status");
		Server server = new Server(new QueuedThreadPool(4, 2, 120));
		ServerConnector sc = new ServerConnector(server);
		sc.setPort(8080);
		server.setConnectors(new Connector[]{sc});
		server.setHandler(sh);
		server.start();
```

in jetty 12 the following exception
```
Insufficient configured threads: required=4 < max=4 for QueuedThreadPool[qtp538185145]@20140db9{STARTED,2<=2<=4,i=2,r=-1,t=96ms,q=0}[ReservedThreadExecutor@4a3631f8{reserved=0/1,pending=0}]
```

**Comment by sbordet** [comment]
The behavior between Jetty 11 and 12 should not have changed.
Please post the full stack trace.
One explanation is that you are running on different hardware, is that the case?

It is typically a bad idea to configure Jetty with so few threads.
Why are you doing that?

Jetty will only use the threads that are necessary, and efficiently remove those that are not used anymore.

**Comment by sbordet** [comment]
@leonchen83 what was the issue, just to understand?

**Comment by leonchen83** [comment]
we test above code snapshot in different laptop.
MBP m1 works fine in jetty 11 and jetty 12.
my laptop `13th Gen Intel(R) Core(TM) i7-13700H   2.40 GHz`  throw above exception both in jetty 11 and 12.
so we changed max threads to `5`

**Comment by sbordet** [comment]
@leonchen83 as I said, `5` threads is typically either a bad idea or wrong, as you won't have threads left for processing and you risk a server lockup.
Is there any reason you want so few max threads?

**Comment by leonchen83** [comment]
@sbordet we use jetty to mock a web server to run unit test.  if `5` is a bad idea. I think jetty should check this argument and throw exception in `QueuedThreadPool` 's constructor or set properly thread override user's setting
