### ISSUE TITLE
RedirectRegexRule and RewritePatternRule should consider relativeRedirectAllowed

### ISSUE THREAD

**Issue by dsmiley** [eclipse/jetty.project#11014]
There is an HttpConfiguration option "relativeRedirectAllowed" that is taken into consideration by sendRedirect().  But RedirectRegexRule and RewritePatternRule don't use that sendRedirect.  Perhaps they should?

**Comment by gregw** [comment]
This already appears fixed in Jetty-12 as we do this check in `Request.toRedirectURI` which is used by the rewrite rules.. although there is a TODO there.
Thus this is mostly a 10/11 issue.
