### ISSUE TITLE
UrlResourceFactoryTest.testHttps fails when access to webtide.com is blocked

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/jetty.project#11068]
**Jetty version(s)**
12.0.5-SNAPSHOT

**Jetty Environment**
any

**Java version/vendor** `(use: java -version)`
any

**OS type/version**
macOS 14.2

**Description**
```
[ERROR] Failures: 
[ERROR]   UrlResourceFactoryTest.testHttps:67 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 2170, Failures: 1, Errors: 0, Skipped: 103
```

When access to webtide.com is blocked (for example via an application firewall like Little Snitch), the test fails.

Ideally, unit tests should not require a network connection. If that test is really required, connectivity should be verified through separate means (e.g., URLConnection) before assuming a test failure instead of unmet test prerequisites due to network failure/policy rejection.

**How to reproduce?**
```
cd jetty-core/jetty-util
mvn -Dmaven.build.cache.enabled=false test 
```

**Comment by joakime** [comment]
You can run tests with the `external` group excluded.

```
mvn clean install -DexcludedGroups=external
```

That will skip any tests that rely on an external resource.

**Comment by janbartel** [comment]
I think @joakime's suggestion addresses the problem. Closing.
