### ISSUE TITLE
URIUtilTest.testFileUriGetUriLastPathSegment fails on recent macOS

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/jetty.project#11066]
**Jetty version(s)**
12.0.5-SNAPSHOT

**Jetty Environment**
any

**Java version/vendor** `(use: java -version)`
any

**OS type/version**
macOS 14.2

**Description**
```
[ERROR] Failures: 
[ERROR]   URIUtilTest.testFileUriGetUriLastPathSegment:818 
Expected: is "número.war"
     but: was "número.war"
[ERROR]   UrlResourceFactoryTest.testHttps:67 expected: <true> but was: <false>
```

The test code has a special case for macOS around NFD form normalization. Apparently that is no longer the case for macOS, at least on 14.2.

**How to reproduce?**
```
cd jetty-core/jetty-util ; mvn clean install
```

**Comment by joakime** [comment]
Ah, yeah, we are aware of the whole NFC / NFD thing on MacOS, we even have tests specifically for that.
Need to modify that test case to be more resilient.

**Comment by joakime** [comment]
I suspect this isn't Mac OS 14.2 specific, but rather JVM specific behavior.

**Comment by joakime** [comment]
PR #11067 merged
