### ISSUE TITLE
"Failed to open local endpoint" occur.

### ISSUE THREAD

**Issue by urumax** [eclipse/jetty.project#11087]
**Jetty Version**
version 9.4.48.v2022062

**Java Version**
Java 8

**Question**
When connecting to a WebSocket server using jetty, onWebSocketError() was called on the client side and a TimeOut occurred.

After that, when the client reconnect(call WebSocketClient.connect() ) to the server, onWebSocketConnect() is called, but immediately onWebSocketClose() is called, the statusCode value is 1006, and the reason value is "Failed to open local endpoint".

On the server side, onWebSocketConnect() is called, and immediately after that, onWebSocketClose() is called. The value of statusCode is 1000 and the value of reason is "null".

Reconnect tried 5 times(100ms interval), same result.

While this problem occurred, several sessions were communicating at the same time. I think that the firewall settings are unlikely to be the cause. Client and server are separate EC2 instances, same jetty version 9.4.48.v2022062.

What shall I do, in order to solve this?

**Comment by lachlan-roberts** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Is the client trying to close the websocket session inside `onWebSocketConnect()`? it is strange that the server is seeing a close status of `1000`, which should mean that it has received a close frame.

There has been some big websocket changes in Jetty 10+, so maybe first try updating to a more recent version.

**Comment by urumax** [comment]
Thank you lachlan-roberts.
Below are the client side and server side logs when the error occurs.
What could be the cause of the strange error? Is there a potential issue with 9.x that is why you are recommending an update?
There are framework dependencies and it cannot be easily updated to jetty10 (Java11).

Is it possible to avoid this error with 9.4.53.v20231009?

[client log]
13:17:01.626 ERROR : onError call. Throwable:java.net.SocketTimeoutException: Connect Timeout
13:17:01.635 INFO : Websocket ReConnect. retryCount:1 
13:17:01.636 INFO : onConnect call. 
13:17:01.636 ERROR : onClose call. statusCode=1006 reason=Failed to open local endpoint 
13:17:01.735 INFO : Websocket ReConnect. retryCount:2 
13:17:01.736 INFO : onConnect call. 
13:17:01.736 ERROR : onClose call. statusCode=1006 reason=Failed to open local endpoint 
13:17:01.835 INFO : Websocket ReConnect. retryCount:3 
13:17:01.836 INFO : onConnect call. 
13:17:01.836 ERROR : onClose call. statusCode=1006 reason=Failed to open local endpoint 
13:17:01.936 INFO : Websocket ReConnect. retryCount:4 
13:17:01.936 INFO : onConnect call. 
13:17:01.937 ERROR : onClose call. statusCode=1006 reason=Failed to open local endpoint 
13:17:02.036 INFO : Websocket ReConnect. retryCount:5 
13:17:02.037 INFO : onConnect call. 
13:17:02.037 ERROR : onClose call. statusCode=1006 reason=Failed to open local endpoint

[server log] 
13:17:01.636 INFO : onConnect call. 
13:17:01.697 ERROR : onClose call. statusCode=1000 reason=null 
13:17:01.736 INFO : onConnect call. 
13:17:01.797 ERROR : onClose call. statusCode=1000 reason=null 
13:17:01.836 INFO : onConnect call. 
13:17:01.897 ERROR : onClose call. statusCode=1000 reason=null 
13:17:01.936 INFO : onConnect call. 
13:17:01.997 ERROR : onClose call. statusCode=1000 reason=null 
13:17:02.036 INFO : onConnect call. 
13:17:02.097 ERROR : onClose call. statusCode=1000 reason=null

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958 

That means there is no support for that version.
Please upgrade, and then we can support you.

**Comment by urumax** [comment]
Thank you for your cooperation.
We are considering upgrading our application and Jetty.

**Comment by urumax** [comment]
Thank you for your cooperation.
We are considering upgrading our application and Jetty.
