### ISSUE TITLE
Exclude WITH_NULL cipher suites by default in SslContextFactory

### ISSUE THREAD

**Issue by oscarlantz** [eclipse/jetty.project#1110]
A suggestion to make jetty even more secure by default is to exclude all WITH_NULL cipher suites in SslContextFactory. Something like this:

```
addExcludeCipherSuites("^*._WITH_NULL_*.$");
```

**Comment by sbordet** [comment]
The `WITH_NULL` ciphers are not enabled by default in the JDK (8+), so it appears that there is no need to do what you suggest.

**Comment by oscarlantz** [comment]
Sorry, it seems I was confusing the lists of enabled vs supported ciphers.
