### ISSUE TITLE
why  i delete the  project's war, but it is still running?

### ISSUE THREAD

**Issue by aqnaruto** [eclipse/jetty.project#1113]
![image](https://cloud.githubusercontent.com/assets/9067159/20418908/ce3dcf84-ad8c-11e6-9233-f4a44c55a449.png)
how to delete the tempfile?  why do not give a simple setting  tempfile method ?
and why do not clean tempfile automaticly when webapp is update?

-----------
ubuntu12 ,amazon ec2,jetty 9.4
![image](https://cloud.githubusercontent.com/assets/9067159/20420513/42c23ab4-ad99-11e6-9001-c4d61b09b620.png)

**Comment by aqnaruto** [comment]
![image](https://cloud.githubusercontent.com/assets/9067159/20419122/e9c3f510-ad8e-11e6-9963-38b018c20f0f.png)
how to find those location? why i am already settinged word dir , still not work

**Comment by janbartel** [comment]
@aqnaruto  can you please paste your configuration?

Also, can you please clarify your question? Are you saying that you have deleted a webapp from $jetty.base/webapps and it is still deployed? Or are you saying that you have deleted a webapp from $jetty.base/webapps and you can still see its unpacked directory in /tmp?

**Comment by aqnaruto** [comment]
yes i am grateful to recieve ur repply.   i depoyed a war  in `$jetty.base/webapps`, when i delete this war, this war's services is still running .     i think it must run in a tempfile , but i can't find it ,and i can't set it

**Comment by aqnaruto** [comment]
![image](https://cloud.githubusercontent.com/assets/9067159/20419484/bc62b6d0-ad91-11e6-8e15-8c9834a6b2a7.png)
i know i should set a xml file ,but how should i  edit or create this xml file on where ? which dir?

**Comment by aqnaruto** [comment]
okay，i add a xml file named `tempfileset.xml` under context‘s dir 
···
<Configure class="org.eclipse.jetty.webapp.WebAppContext">

  <Set name="contextPath">/webapps</Set>
  <Set name="war">lottery.war</Set>

  <Set name="tempDirectory">/work/lotterytemp</Set>
</Configure>

</Configure>
···

then ,i restart jetty ,still not work

**Comment by aqnaruto** [comment]
close.  thank you rapidly repply and excellent work @janbartel .
