### ISSUE TITLE
quickstart generator of quickstart-web.xml should keep ids

### ISSUE THREAD

**Issue by ludoch** [eclipse/jetty.project#1117]
We would like to differentiate entries coming from webdefault.xml from app entries by adding an id, for example
```<filter-mapping id = 'appengine-webdefault.xml'>```
in our webdefault.xml

But for now, it seems that the generated quickstart web xml does not keep the ids we put in webdefault.xml

**Comment by joakime** [comment]
what should the reaction be if there is an XML id attribute conflict?

as having for example ...

```xml
    <filter-mapping id="appengine-webdefault.xml">
      .. setup filter A ..
    </filter-mapping>
    <filter-mapping id="appengine-webdefault.xml">
      .. setup filter B ..
    </filter-mapping>
```

... would make the XML invalid due to conflicting IDs

**Comment by ludoch** [comment]
No, we would define this same id for all our webdefault.xml entries.

**Comment by ludoch** [comment]
Oh, I see that would be an error...
Maybe we can increment the Ids after a well know prefix if we can find the corret xpath to find them all?

**Comment by janbartel** [comment]
@ludoch just checking that you know that you can see info on the origin of each element in quickstart-web.xml by enabling debug on org.eclipse.jetty.quickstart.QuickStartDescriptorGenerator.

Some example outputs from quickstart gen using just jetty distro:
```
<listener origin="DefaultsDescriptor(file:///home/janb/src/jetty-eclipse/jetty-9.3.x/jetty-distribution/target/distribution/etc/webdefault.xml)">
<listener origin="WebDescriptor(file:///home/janb/src/jetty-eclipse/jetty-quickstart-base/webapps/test/WEB-INF/web.xml)">
<servlet-class origin="FragmentDescriptor(jar:file:///home/janb/src/jetty-eclipse/jetty-quickstart-base/webapps/test-spec/WEB-INF/lib/test-web-fragment-9.3.15-SNAPSHOT.jar!/META-INF/web-fragment.xml)">com.acme.test.AnnotationTest</servlet-class>
<servlet-class origin="@WebServlet on com.acme.test.SecuredServlet">com.acme.test.SecuredServlet</servlet-class>
```
Of course, the locations of the descriptors will be different from generation to runtime, but the 'origin' attribute is there purely for documentation purposes and is not interpreted by jetty.

**Comment by gregw** [comment]
We could provide an option to include the origin without turning debug on.  ie the option would default to true/false depending on debug, but could be separately configured.  @ludoch do you want that?

**Comment by janbartel** [comment]
We will provide the ability to set the name of the attribute that contains the origin. By default it will be "origin".  The origin attribute will have appended to it a number (counter) that guarantees that each attribute will be unique and therefore satisfy xml validation.

I will post a syntax for the origin attribute shortly.

**Comment by janbartel** [comment]
Syntax is:
```
attr-name"="["DefaultsDescriptor"|"WebDescriptor"|"FragmentDescriptor"|"OverrideDescriptor"|"@"annotation-name]"("location"):"count
```

where:

-  `attr-name` is any string
- `annotation-name` is the simple classname of an annotation 
- `location` is either a url in the case of a descriptor or the name of class in the case of an annotation
- `count` is a monotonically increasing integer

eg

```
<listener origin="DefaultsDescriptor(file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-distribution/target/distribution/etc/webdefault.xml):21">
<listener origin="WebDescriptor(file:///home/janb/src/jetty-eclipse/jetty-quickstart-base/webapps/test/WEB-INF/web.xml):22">
<servlet-class origin="FragmentDescriptor(jar:file:///home/janb/src/jetty-eclipse/jetty-quickstart-base/webapps/test-spec/WEB-INF/lib/test-web-fragment-9.4.0-SNAPSHOT.jar!/META-INF/web-fragment.xml):23">com.acme.test.AnnotationTest</servlet-class>
<servlet-class origin="@WebServlet(com.acme.test.SecuredServlet):24">com.acme.test.SecuredServlet</servlet-class>
```

To configure the `attr-name`, there is a new setter on the QuickStartWebApp class:
```java
QuickStartWebApp.setOriginAttribute(String)
```

To configure whether or not the attribute is generated into the quickstart output (it is _false_ by default), either enable debug logging, or use the new setter on QuickStartWebApp class:
```java
QuickStartWebApp.setGenerateOrigin(boolean)
```
