### ISSUE TITLE
System CPU time spins on pipe read/write

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#112]
migrated from Bugzilla [#404278](https://bugs.eclipse.org/bugs/show_bug.cgi?id=404278)
status ASSIGNED severity *normal* in component *server* for *9.0.x*
Reported in version *8.1.8* on platform *PC*
Assigned to: Project Inbox

On 2013-03-25 11:46:11 -0400, Joe Fago wrote:

> In our production environment, even under moderate load, there are system cpu spikes that generally last 1-5 minutes. Running an strace shows the following:
> 
> [pid 27153] write(171, "\1", 1)         = 1
> [pid 27153] read(170, "\1", 128)        = 1
> [pid 27153] write(171, "\1", 1)         = 1
> [pid 27153] read(170, "\1", 128)        = 1
> [pid 27153] write(171, "\1", 1)         = 1
> [pid 27153] read(170, "\1", 128)        = 1
> [pid 27153] write(171, "\1", 1)         = 1
> [pid 27153] read(170, "\1", 128)        = 1
> 
> read/write pattern repeats 11,000+ times in 10s. File descriptors 170/171 are the read/write ends of a pipe, not a socket.
> 
> lr-x------ 1 root root 64 Mar 23 03:40 170 -> pipe:[15520976]
> l-wx------ 1 root root 64 Mar 23 03:40 171 -> pipe:[15520976]
> 
> Note that the same thread is continuously writing and reading a single byte (value = 1). The jstack output shows this for thread 27153:
> 
> Thread 27153: (state = IN_NATIVE)
>  - sun.nio.ch.EPollArrayWrapper.interrupt(int) @bci=0 (Compiled frame; information may be imprecise)
>  - sun.nio.ch.EPollArrayWrapper.interrupt() @bci=4, line=256 (Compiled frame)
>  - sun.nio.ch.EPollSelectorImpl.wakeup() @bci=18, line=175 (Compiled frame)
>  - org.eclipse.jetty.io.nio.SelectorManager$SelectSet.wakeup() @bci=10, line=822 (Compiled frame)
>  - org.eclipse.jetty.io.nio.SelectChannelEndPoint.updateKey() @bci=215, line=539 (Compiled frame)
>  - org.eclipse.jetty.io.nio.SelectChannelEndPoint.schedule() @bci=117, line=173 (Compiled frame)
>  - org.eclipse.jetty.io.nio.SelectorManager$SelectSet.doSelect() @bci=739, line=619 (Compiled frame)
>  - org.eclipse.jetty.io.nio.SelectorManager$1.run() @bci=181, line=290 (Compiled frame)
>  - org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(java.lang.Runnable) @bci=1, line=608 (Interpreted frame)
>  - org.eclipse.jetty.util.thread.QueuedThreadPool$3.run() @bci=47, line=543 (Interpreted frame)
>  - java.lang.Thread.run() @bci=11, line=662 (Interpreted frame)
> 
> I also see evidence of thread SEGfaults in the strace output - usually after several thousand read/write single-byte repetitions. The thread gets respawned and continues this read/write behaviour. 
> 
> [pid 27153] --- SIGSEGV (Segmentation fault) @ 0 (0) ---
> [pid 27153] --- SIGSEGV (Segmentation fault) @ 0 (0) ---
> 
> 
> We are running the 1.6 Oracle jvm on Redhat.
> OS/JVM/Jetty versions:
> 
> Red Hat Enterprise Linux Server release 5.8 (Tikanga)
> 
> java version "1.6.0_37"
> Java(TM) SE Runtime Environment (build 1.6.0_37-b06)
> Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01, mixed mode)
> 
> jetty-8.1.8.v20121106 - 06 November 2012
> 
> Let me know if there is any more information I can provide. Still digging through logs for more info, but hoping this looks like a known issue.

On 2013-03-25 17:31:22 -0400, Greg Wilkins wrote:

> My first guess is that this looks like a JVM bug or at least weirdness.  Jetty does not use pipes, so I assume this is part of the implementation of the NIO selector?  Hence the EPollXxxx in the stack trace.  Also SEGV's imply a JVM problem rather than a Jetty problem.
> 
> It would be interesting to know how far out of that stack the thread gets.  Is it repeatedly calling updateKey, or is it looping within there or is it looping within EPoll etc?
> 
> Your JVM looks recent-ish, although there is a _41 out I think.  You could also try java 7
> 
> So unfortunately this is not a known issue.

**Comment by joakime** [comment]
Jetty 8.1.8, closing
