### ISSUE TITLE
Should TLS_EMPTY_RENEGOTIATION_INFO_SCSV be excluded?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1122]
In the default configuration of jetty-distribution, the cipher `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` is available for use.

Should that be disabled by default in the SslContextFactory?

Perhaps under the pattern `.*_EMPTY_.*` ?

**Comment by sbordet** [comment]
No, that is not really a cipher, but a TLS feature, see https://tools.ietf.org/html/rfc5746. Don't exclude it.
