### ISSUE TITLE
AsyncListener question

### ISSUE THREAD

**Issue by jkvargas** [eclipse/jetty.project#11226]
**Jetty Version**
11.0.19

**Java Version**
17

**Question**
when I am handling a request I am acquiring a semaphore and releasing when complete.
Do I actually need to release at some other moment? Can complete not happen for some reason?
consider baseRequest of type org.eclipse.jetty.server.Request and _concurrencyGate of type Semaphore.

``` java
if (_concurrencyGate.tryAcquire(...)) {
  var asyncContext = baseRequest.getAsyncContext();

  asyncContext.addListener(new AsyncListener() {
                      @Override
                      public void onComplete(AsyncEvent event) {
                          _concurrencyGate.release();
                      }
  
                      @Override
                      public void onTimeout(AsyncEvent event) {\
                      }
  
                      @Override
                      public void onError(AsyncEvent event) {
                      }
  
                      @Override
                      public void onStartAsync(AsyncEvent event) {}
  
                  }, request, response);
  }
}
```

**Comment by sbordet** [comment]
Without looking at the full code, it's difficult to say.

If the code does the following in the same thread:

1. enter the Servlet method
1. acquire the semaphore
1. startAsync()
2. add the listener
3. exit the Servlet method

then it's safe to say that the listener's `onComplete()` will be called IFF the application calls `AsyncContext.complete()`.

Other cases may be subject to a race (e.g. the listener is added after the completion has happened, or multiple threads are involved).
