### ISSUE TITLE
WebSocketClient.connect with URI including query parameters don't work for HTTP2 connector

### ISSUE THREAD

**Issue by rickardoberg** [eclipse/jetty.project#11223]
**Jetty version(s)**
11.0.19

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.2" 2022-01-18

**OS type/version**
Win11

**Description**
Calling WebSocketClient.connect(this, uri, clientUpgradeRequest) with a URI that includes query parameters doesn't work when using the HTTP2 connector. The query parameters always gets lost when looking at the request on the server. The exact same code just without adding the HTTP2 connector works, i.e. server-side websocket servlet has access to query parameters in the request.

**How to reproduce?**
Take any existing code that does WebSocketClient.connect, add a query parameter to the URI, enable HTTP2 connector in client, and set debug breakpoint in server. You will see that the query parameters are lost.

**Comment by sbordet** [comment]
Hi @rickardoberg 👋🏼 

Surprised that this issue remained undiscovered this long!

A PR is on its way, thanks for reporting this!

**Comment by rickardoberg** [comment]
Hey @sbordet , yeah that's what I thought too! I was tracing the call from connect() through the client, and it seemed to always have query parameters, but then all of a sudden I was on the server handler, and no query parameters. I only got lucky and noticed the "HTTP2" in the client class name, tried disabling the HTTP2 connector, and voila, it all worked again :) Does this only affect websocket stuff, or does it apply to any other cases as well?

**Comment by sbordet** [comment]
@rickardoberg WebSocket over HTTP/2 requires a special treatment, as it is "tunneled" via an HTTP/2 stream using the CONNECT method.

The client creates a special request in `HttpSenderOverHTTP2.sendHeaders()`, and if it is an upgrade tunnel the query parameters are lost while creating `MetaData.ConnectRequest`.

Note that "normal" tunnel requests should not have a path, but upgrade tunnel requests with the `:protocol` pseudo-header should retain path and query -- but we only retain the path.

So it only affect WebSocket over HTTP/2, other cases are fine.
