### ISSUE TITLE
jmx-remote-auth password file encrypt

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#11221]
**Jetty Version**
jetty10.0.19
**Jetty Environment**

core
**Java Version**
jdk11
**Question**

I would like to ask, how to encrypt the password in the jmx password file? Does it support OBF or other encryption? Since it's now in clear text, this doesn't look very secure

jmxremote.password file：

```
myadmin 12345678
```
can i encrypt the password 12345678？

**Comment by joakime** [comment]
Both the `jmxremote.password` and the associated `jmxremote.access` are JVM specific configuration files.
Only the JVM reads them, Jetty never reads them.

You can find the documentation for their syntax in the JVM itself.

* `$JAVA_HOME/conf/management/jmxremote.access`
* `$JAVA_HOME/conf/management/jmxremote.password.template`

Read the comments in those two files.

Eventually, the JVM will need 2 system properties defined pointing to your specific versions of those 2 files.

```
java -Dcom.sun.management.jmxremote.access.file=/path/to/jmxremote.access \
     -Dcom.sun.management.jmxremote.password.file=/path/to/jmxremote.password \
     org.example.MyApp
```
