### ISSUE TITLE
org.eclipse.jetty.aggregate jetty-all 9.3 does not import necessary libs 

### ISSUE THREAD

**Issue by MikeMitterer** [eclipse/jetty.project#1125]
I'm using IntelliJ 2016.3 and Gradle 3.1

If I import group: 'org.eclipse.jetty.aggregate',   name: 'jetty-all',  version: "9.2.19.+"
it imports all the necessary files:
![capturfiles-23-22-2016_09 22 00](https://cloud.githubusercontent.com/assets/116654/20577628/7c2c2570-b1c3-11e6-806a-2b82bfe1c44d.png)

But with "9.3.14.+" I get this???? (only websockets and http2)
![capturfiles-23-24-2016_09 24 11](https://cloud.githubusercontent.com/assets/116654/20577627/7c2b2e68-b1c3-11e6-8fbf-2dd20195f373.png)

----
IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Gradle 3.1
Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.11.6 x86_64

**Comment by joakime** [comment]
This is intentional.

Read: https://dev.eclipse.org/mhonarc/lists/jetty-users/msg06030.html
