### ISSUE TITLE
Support BSD expr in startup script

### ISSUE THREAD

**Issue by neirbowj** [eclipse/jetty.project#11273]
**Jetty version(s)**

All supported versions.

**Enhancement Description**

When the startup script reads the config file to detect XML files, it [uses the `expr` command to skip comment lines](https://github.com/jetty/jetty.project/blob/090287db5e0b6b69245a841457ced993dc286838/jetty-home/src/main/resources/bin/jetty.sh#L462). The only non-comment entry in the default config file [starts with a hyphen](https://github.com/jetty/jetty.project/blob/090287db5e0b6b69245a841457ced993dc286838/jetty-home/src/main/resources/etc/jetty.conf#L11). `expr` on Linux, macOS, and probably elsewhere, does not care.

```
$ expr "--module=pid,state" : "#"
0
```

`expr` on FreeBSD complains.

```
expr "--module=pid,state" : "#"
expr: illegal option -- -
expr: usage: expr [-e] expression
```

Both implementations recognize the use of "--" to signal the end of the command line options so that subsequent arguments that begin with a hyphen are not treated as options. This works on Linux and BSD:

```
$ expr -- "# comment" : "#"
1
$ expr -- "--module=pid,state" : "#"
0
```

**Comment by joakime** [comment]
Done, will be available in next releases of Jetty 10.0.20 / 11.0.20 / 12.0.6 (due at end of month)
