### ISSUE TITLE
Missing 12.0.5 release of various quic and http3 artifacts on maven central.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#11272]
**Jetty version(s)**
12.0.5

**Jetty Environment**
Core

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
When looking at 12.0.5 releases on maven central, some artifacts seem to be missing.
We need to identify what happened to prevent this from happening again.

Some examples (missing a 12.0.5 release)

* https://repo1.maven.org/maven2/org/eclipse/jetty/http3/jetty-http3-common/
* https://repo1.maven.org/maven2/org/eclipse/jetty/quic/jetty-quic-server/

At first it seems like an http3 or quic deployment issue.
But some artifacts are there.
Example:

* https://repo1.maven.org/maven2/org/eclipse/jetty/quic/jetty-quic-common/

**Comment by joakime** [comment]
CC @sbordet @olamy @lorban

**Comment by olamy** [comment]
jetty-quic-server 12.0.5 is here https://repo1.maven.org/maven2/org/eclipse/jetty/quic/jetty-quic-server/12.0.5/

**Comment by olamy** [comment]
I can't really see something in the poms which could prevent the deployment of those artifacts.
maybe we should have the release script redirecting output to a log file so we can search for possible errors?

**Comment by olamy** [comment]
12.0.5 is not in list via the UI https://repo1.maven.org/maven2/org/eclipse/jetty/http3/jetty-http3-common/
but https://repo1.maven.org/maven2/org/eclipse/jetty/http3/jetty-http3-common/12.0.5/ is fine even in a browser
curl/wget are fine:
`wget https://repo1.maven.org/maven2/org/eclipse/jetty/http3/jetty-http3-common/12.0.5/jetty-http3-common-12.0.5.jar`

**Comment by lorban** [comment]
12.0.5 is also in [maven-metadata.xml](https://repo1.maven.org/maven2/org/eclipse/jetty/http3/jetty-http3-common/maven-metadata.xml), so this looks more and more like an infrastructure problem of Central. We should report that to Sonatype.

**Comment by olamy** [comment]
email sent to central-support@sonatype.com

**Comment by olamy** [comment]
Sonatype purged the CDN cache for these directory listings.
All good now
