### ISSUE TITLE
No work directory is created even though I have a work.md module 

### ISSUE THREAD

**Issue by vmassol** [eclipse/jetty.project#11286]
Hello,

I thought that having a `work.mod` module file + referencing it when starting Jetty would lead to the creation of the `work/` directory automatically, based on the description inside that module:

```
[description]
Creates the $JETTY_BASE/work directory as a persistent temp directory.
If a work directory exists, it is used for context temp directories, but
they are persisted between runs of Jetty, so generated files (eg JSPs)
can be kept.

[tags]
server

[files]
work/
```

However that doesn't happen (tested on Jetty 10.x and 12.x). Thus I'm curious about:
* The reason for `work.md` to exist if it doesn't create that directory
* Or am I missing something (most likely ;))?

Thanks a lot

**Comment by joakime** [comment]
The `[files]` entries in a module are only created if using `--add-module=<name>` or `--create-files` command line.

**Comment by vmassol** [comment]
hmm indeed we start Jetty with `java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED -Xmx1024m -Dxwiki.data.dir=data -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -Djetty.home=jetty -Djetty.base=. -Dfile.encoding=UTF8 -Djetty.http.port=8080 -jar jetty/start.jar jetty.http.port=8080 STOP.KEY=xwiki STOP.PORT=8079`  and we have a `./start.d/xwiki.ini` file containing:

```
--module=xwiki

## Default configuration values for XWiki

## Disable WAR scanning and hot deployments since we use static expanded WAR to speed up Jetty.
jetty.deploy.scanInterval=0
jetty.deploy.extractWars=false

## Jetty 10.0.3+ has added a protection in URLs so that encoded characters such as % are prohibited by default. Since
## XWiki uses them, we need to configure Jetty to allow for it. See
##   https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-server-compliance
jetty.httpConfig.uriCompliance=RFC3986
```

And `xwiki.mod` has the the dependency to the `work.mod`.

So I guess we should simply drop `work.mod` and create the `work` directory in our start script.

Thanks @joakime !

**Comment by joakime** [comment]
> And `xwiki.mod` has the the dependency to the `work.mod`.
> 
> So I guess we should simply drop `work.mod` and create the `work` directory in our start script.

Or tell people to use `--add-module=xwiki` to enable it on their `${jetty.base}` and the work.mod will come along for the ride and also have it's content created.

**Comment by vmassol** [comment]
Thanks again @joakime
