### ISSUE TITLE
Jetty 12 EE10 OSGi Boot invalid jetty.xml Handler configuration

### ISSUE THREAD

**Issue by cmark** [eclipse/jetty.project#11280]
**Jetty version(s)**
Jetty 12.0.3 (but according to the source code it affects the current jetty-12 main as well)

**Jetty Environment**
ee10 (ee8 working without problems)

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

**OS type/version**
Microsoft Windows 10 22H2 (OS Build 19045.3930)

**Description**
When trying to run an embedded Jetty 12 Jakarta EE10 in an OSGi unit test environment via the `jetty-ee10-osgi-boot` bundle it fails because the jetty.xml file incorrectly references the Handler class from jetty-server module, specifically this line:
```
    ...
    <Set name="handler">
      <New id="Handlers" class="org.eclipse.jetty.server.handler.Handler.Collection">   <----- Handler interface is in the org.eclipse.jetty.server package not in the handler package.
        <Set name="handlers">
        ...
```

Replacing the [Handler configuration section](https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/jettyhome/etc/jetty.xml#L26-L39) in the EE10 jetty.xml from the EE8 boot's [jetty.xml](https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-ee8/jetty-ee8-osgi/jetty-ee8-osgi-boot/jettyhome/etc/jetty.xml#L25-L27) solves the issue and Jetty 12 can start without any errors.

**How to reproduce?**
I don't have a simple example project that demonstrates the problem, but if that's needed let me know.

**Comment by joakime** [comment]
@janbartel The tree `jetty-ee10-osgi/jetty-ee10-osgi-boot/jettyhome/` seems to be totally unused in code at runtime or testing.
The contents of that tree appear to be packaged into the `target/jetty-ee10-osgi-boot-<ver>.jar`, but nothing refers to it.

We can probably get rid of it.

The up to date XML examples, used in testing, are found in https://github.com/jetty/jetty.project/tree/jetty-12.0.x/jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/config/etc

**Comment by janbartel** [comment]
@joakime see https://eclipse.dev/jetty/documentation/jetty-9/index.html#framework-jetty-osgi. We provide those files inside the boot jar as a convenience for users. We should probably fix their contents, and create/alter at least one unit test to use them rather than externally provided files to ensure their contents are validated.
