### ISSUE TITLE
EE8/9 `DefaultServlet.doPost()` doesn't behave like Jetty 10/11

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#11299]
**Jetty version(s)**
12

**Jetty Environment**
EE 8/9

**Description**
In Jetty 10/11 `DefaultServlet.doPost()` does what `doGet()` does:

```java
@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException
{
    doGet(request, response);
}
```

While  in Jetty 12 EE 8/9 it returns an error 405:

```java
@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException
{
    response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED);
}
```

The pre-existing behavior should be restored for backward compatibility.

**Comment by joakime** [comment]
The DefaultServlet needs to support GET, HEAD, and OPTIONS properly for sure.

Should it support POST too? (we used to just redirect doPost to doGet, Tomcat does it too)

Should it support any other methods? (PUT is supported by Tomcat, but that adds a whole read-only aspect, and would be confusing with our CombinedResource)

**Comment by lorban** [comment]
@joakime Since we're talking about EE8/9, my mental model is that we should behave exactly how Jetty 10/11 do, even if that's odd or questionable. In this case, Jetty 10/11 treat POST exactly like GET but PUTs are rejected, so IMHO this is what EE8/9 should do.

But your question remains valid for EE10, and in that case responding to POST with 405 is IMHO the right thing to do.
