### ISSUE TITLE
AbstractLoginModule porting issue

### ISSUE THREAD

**Issue by brettwooldridge** [eclipse/jetty.project#11296]
**Jetty Version**
Jetty 9 to Jetty 12 migration

**Jetty Environment**
ee9

**Java Version**
Java 17

**Question**
I am trying to port our Jetty 9 application to Jetty 12, and have run into an issue with our current implementation of ``AbstractLoginModule``. Our current implemenation provides an implemenation of the ``getUserInfo()`` method, in fact that is where most of the heavy-lifting is done, but this method is missing from the current implementation.

However, the class documentation from ``AbstractLoginModule`` still references overriding this method as the work that needs to be done:
```
/**
 * AbstractLoginModule
 *
 * Abstract base class for all LoginModules. Subclasses should
 * just need to implement getUserInfo method.
 */
```
I don't understand what the current correct pattern is for using the ``AbstractLoginModule``.

The "old" ``AbstractLoginModule`` imposed this signature, however it is now missing from the class definition:
```
public UserInfo getUserInfo(String username)
```

**Comment by janbartel** [comment]
@brettwooldridge oops, old javadoc comment left in that class. Take a look at the subclasses of `AbstractLoginModule` like `AbstractDatabaseLoginModule`. You need  to implement the `getUser(String username)` method, and to subclass the `JAASUser`  class to implement the `doFetchRoles` method.
