### ISSUE TITLE
Jetty SNI Integration / please provide better informations

### ISSUE THREAD

**Issue by MikeMitterer** [eclipse/jetty.project#1129]
I'm using a JETTY-keystore with two self signed certificates: CN localhost and CN mac42
CERTs are added to the System-KeyStore (I'm on Mac)

https://localhost:8443/ - works in Chrome
https://mac42:8443/ - fails

Now I delete the Cert for "localhost" from Jettys keystore, restart it and now
https://mac42:8443/ - works

I don't know if it's bug or if my config is wrong??? 
This instruction http://www.eclipse.org/jetty/documentation/current/configuring-ssl.html#_configuring_sni has only a few lines and it looks like if SNI should work out of the box - but it dosen't BTW: ExtendedSSlContextFactory - dosen't exist at all...

On Jetty 9.3 thats how I configure SslContextFactory:
```java
    public SslContextFactory getContextFactory() throws FileNotFoundException {
        final SslContextFactory sslContextFactory = new SslContextFactory();
        sslContextFactory.setKeyStorePath(getAbsolutePath());

        // Wurde mit /Volumes/Daten/DevLocal/DevJava/WebApp.Core/EmbeddedServer/bin/genobf generiert
        sslContextFactory.setKeyStorePassword(getPassword());
        sslContextFactory.setKeyManagerPassword(getPassword());

        return sslContextFactory;
    }
```

**Comment by joakime** [comment]
the hostname "localhost" has all sorts of special meaning to browsers/ssl/tls and https clients, don't do testing with that particular name.

consider setting up more hostnames in your `/etc/hosts` for your own machine (eg: "myaltmac") to create/test SNI with.

**Comment by joakime** [comment]
Also consider setting up logging (of your choice), with the named logger `org.eclipse.jetty.util.ssl` set to DEBUG level.

That should provide you more information on what jetty is doing.

If you don't see mentions of `SniX509ExtendedKeyManager` then you haven't setup your keystore with an appropriate SNI capable certificate.

You should see logging messages with the phrase `SNI matching for` indicating that SNI logic is being performed.

**Comment by MikeMitterer** [comment]
OK - Thanks, I'll try that

**Comment by joakime** [comment]
Closing due to lack of updates
