### ISSUE TITLE
How to detect failures in sending data?

### ISSUE THREAD

**Issue by urumax** [eclipse/jetty.project#11302]
Jetty Version
version 9, 12

Java Version
Java 8, 17

Question
I tried the following settings to detect that data is not being sent to the WebSocket server.

1. Set a value for setMaxOutgoingFrames() in the WebSocketRemoteEndpoint class (e.g., 10).
2. Connect to the WebSocket server from a WebSocket client application (port: 8443).
3. Use the iptables command to drop packets destined for port 8443.
    iptables -A OUTPUT -p tcp -d xxx.xxx.xxx.xxx --dport 8443 -j DROP

I have tried different values for setMaxOutgoingFrames(), such as 1, 10, and 20, but encountered WritePendingException at almost the same timing. Is setting setMaxOutgoingFrames() the correct approach to accurately detect that no data is being sent?
How can I use Jetty's functionality to detect failures in sending data to a WebSocket server?

Below is part of my code.

WriteCallbackImpl writeCallbackImpl = new WriteCallbackImpl();

while (runflag) {
    byte[] senddata = binarydata.poll();
    ByteBuffer buffer = ByteBuffer.wrap(senddata);
    session.getRemote().sendBytes(buffer, writeCallbackImpl);
}

**Comment by joakime** [comment]
Just dropping packets will not trigger failures in the network stack.
With that technique, I would expect you will experience backpressure of your local networking layers (os + drivers) only after some amount of data is in the networking layers, then eventually one of your attempts to write will not complete.
Pretty typical TCP behaviors here, nothing magical about websocket.

Now for options:

Most libs built on top of websocket do one of two things to detect networking issues.

1. Have an acknowledgement feature, where the remote has to acknowledge the receipt of the message/frame.

or 

2. Use the PING/PONG features of WebSocket to issue a PING (with a small payload marking that specific PING unique), and the response of the PONG shows which PING was responded, and indicate that the connection is still active and valid.
    If the expected PONG isn't received within a specified time frame, you have a bad/slow connection.

**Comment by urumax** [comment]
Thank you for your cooperation.
I try use PING/PONG feature to detect connection errors.

**Comment by lachlan-roberts** [comment]
There is also a feature in websocket-core that lets you set a `writeTimeout`. If the frame takes longer than this to be sent it will fail the websocket connection.

But I don't believe there is a way to access this through the Jetty WebSocket API, only through the Jakarta API and the Jetty Core API.
