### ISSUE TITLE
jetty-osgi - No org.osgi.service.http.HttpService, Only org.eclipse.jetty.server.Server

### ISSUE THREAD

**Issue by gpfeifer** [eclipse/jetty.project#11315]
**Jetty Version**
12.0.5

**Jetty Environment**
ee8

**Java Version**
Java 17

**Question**
I'm trying to migrate some legacy code from Jetty 10 to Jetty 12 which uses jetty-osgi.

Using Jetty 10 two (Jetty related) OSGi services are available:
- org.osgi.service.http.HttpService
- org.eclipse.jetty.server.Server

Using Jetty 12 only one (Jetty related) OSGi services is available:
- org.eclipse.jetty.server.Server

The code uses org.osgi.service.http.HttpService to deploy a javax.ws.rs based Servlet by calling 'httpService.registerServlet'

Two question:
Is there a way to 'activate' Jetty as an org.osgi.service.http.HttpService? If not: What is the recommended way to deploy a Jersey based Rest API using Jetty 12 in an an OSGI container?

**Comment by joakime** [comment]
See https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12

Jetty Core has no servlet apis or dependencies anymore.

If you want servlet behaviors (aka `httpService.registerServlet`) you have to select which environment you want to use first, then choose the osgi deps for that environment.

Environment | Servlet Ver | Servlet Namespace | OSGI Deps 
---- | ---- | ---- | ----
`ee10` | Servlet 6 | `jakarta.servlet` | `jetty-ee10-osgi-*` - https://repo1.maven.org/maven2/org/eclipse/jetty/ee10/osgi/
`ee9` | Servlet 5 | `jakarta.servlet` | `jetty-ee9-osgi-*` - https://repo1.maven.org/maven2/org/eclipse/jetty/ee9/osgi/
`ee8` | Servlet 4 | `javax.servlet` | `jetty-ee8-osgi-*` - https://repo1.maven.org/maven2/org/eclipse/jetty/ee8/osgi/

**Comment by gpfeifer** [comment]
WOW, quick response :-), Thank you !

I'm using this dependencies:


		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>12.0.5</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-osgi</artifactId>
			<version>12.0.5</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty.ee8</groupId>
			<artifactId>jetty-ee8-servlet</artifactId>
			<version>12.0.5</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty.ee8</groupId>
			<artifactId>jetty-ee8-servlets</artifactId>
			<version>12.0.5</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty.ee8.osgi</groupId>
			<artifactId>jetty-ee8-osgi-boot</artifactId>
			<version>12.0.5</version>
		</dependency>


For Jetty 10 there was this: 

      https://mvnrepository.com/artifact/org.eclipse.jetty.osgi/jetty-httpservice

which provides the OSGi service 'org.osgi.service.http.HttpService' implemented by Jetty.

Seems to be missing in Jetty 12.

**Comment by janbartel** [comment]
@gpfeifer oops, my bad. We were all under the impression that nobody used that, so I removed it from jetty-12.  A little too enthusiastic on the removal, as I should have retained it for ee8 to maintain backward compat and only removed for ee10. I'll put it back.

**Comment by janbartel** [comment]
@gpfeifer scratch that, I can't put it back, as it depends on Equinox classes that reference jetty, but have not been ported to jetty-12.

Can you use the `jetty-ee8-osgi-boot` functionality that creates a jetty server, connectors etc and then waits to see bundles that contain webapps or jetty contexts and then deploys them? Even though the doco has not yet been ported to jetty-12, the doco for jetty-9 will still show you the options:  https://eclipse.dev/jetty/documentation/jetty-9/index.html#framework-jetty-osgi.  You could either deploy a bundle with a context.xml file that sets up a `org.eclipse.jetty.ee8.servlet.ServletContextHandler` and registers the jersey servlet, or you could deploy a bundle with an `Activator` that creates the `ServletContextHandler` as an osgi `Service`, register the jersey servlet to the `ServletContextHandler`` and `jetty-ee8-osgi-boot`  will see it and deploy it.

**Comment by gpfeifer** [comment]
@janbartel I will try. Thank you very much for your help.

**Comment by gpfeifer** [comment]
Hi @janbartel

A bundle with a simple servlet basically works, if I deploy the bundle as a webapp.

MANIFEST:
Web-ContextPath: /test
Jetty-Environment: ee8

It took me a couple of hours to find out that 'Jetty-Environment: ee8' is required. Without this entry it does not work.

But I'm still not able to deploy a bundle which is using javax.ws.rs. I'm not able to deploy the Jersey example https://github.com/eclipse-ee4j/jersey/tree/2.x/examples/osgi-helloworld-webapp

Of course you need to add: Jetty-Environment: ee8

I get this log entry:
[2024-01-30 13:07:02] [WARNING] [org.eclipse.jetty.ee8.webapp.WebAppContext] Failed startup of context oeje8w.WebAppContext@65099eb1{/helloworld,/helloworld,file:///tmp/jetty-0_0_0_0-8080-bundleFile-_helloworld-any-3729372861759542448/webapp/,false}{file:/home/gpf/cix/git/vpms-server/vsrv-deliver/server/vpms-server-data/org.eclipse.osgi/98/0/bundleFile} 
[2024-01-30 13:07:02] [INFO   ] [org.eclipse.jetty.server.handler.ContextHandler] Started oeje8n.ContextHandler$CoreContextHandler@13f204a3{/helloworld,/helloworld,b=file:///tmp/jetty-0_0_0_0-8080-bundleFile-_helloworld-any-3729372861759542448/webapp/,a=UNAVAILABLE,h=oeje8n.ContextHandler$CoreContextHandler$CoreToNestedHandler@705b8920{STARTED}} 

I have debugged it. Jersey throws this Exception, which is caught by Jetty. Jersey throws a ResourceFinderException. I created another simple example with a javax.ws.rs.code Application, because error message of the exception suggested to declare one. But I still get the same log and the message of the ResourceFinderException is:

org.glassfish.jersey.server.internal.scanning.ResourceFinderException: The URI scheme bundleentry of the URI bundleentry://157.fwk53940034/com/csc/dip/vpms/server/rest/admin/Application.class is not supported. Package scanning deployment is not supported for such URIs.
Try using a different deployment mechanism such as explicitly declaring root resource and provider classes using an extension of javax.ws.rs.core.Application

Seems to be a "class not visible" problem. Any idea?

Best regards
Gregor

**Comment by gpfeifer** [comment]
@janbartel 
>  Even though the doco has not yet been ported to jetty-12, the doco for jetty-9 will still show you the options: https://eclipse.dev/jetty/documentation/jetty-9/index.html#framework-jetty-osgi. 

This seems not to work with Jetty 12:

    public void start(BundleContext context) throws Exception
    {
        WebAppContext webapp = new WebAppContext();
        Dictionary props = new Hashtable();
        props.put("Jetty-WarResourcePath",".");
        props.put("contextPath","/acme");
        context.registerService(WebAppContext.class.getName(),webapp,props);
    }

**Comment by joakime** [comment]
> org.glassfish.jersey.server.internal.scanning.ResourceFinderException: The URI scheme bundleentry of the URI bundleentry://157.fwk53940034/com/csc/dip/vpms/server/rest/admin/Application.class is not supported. Package scanning deployment is not supported for such URIs.

That looks like Jersey is saying it does not support OSGi, which is surprising, as that has worked in the past for other people.  (I wonder if Jersey has direct Jetty integration points and has not updated those to Jetty 12 yet?)
Perhaps there's something about your version of Jersey that needs to configure how it's runtime operates to let it know that OSGi is in play?
Seems like it's in a mode where it assumes no OSGi is present.

**Comment by gpfeifer** [comment]
I don't think that this is a Jersey problem because the same code is working with Jetty 10

**Comment by joakime** [comment]
> I don't think that this is a Jersey problem because the same code is working with Jetty 10

It can easily be a Jersey problem if Jersey has integration code against Jetty (which I do not know).
There are important APIs and behavior changes in Jetty 12 that are different than Jetty 10.

**Comment by joakime** [comment]
Here's an open issue from 2016 on Jersey that has the same bundleentry error.

https://github.com/eclipse-ee4j/jersey/issues/3480

But that is on Tomcat with Jersey.

The error recommends ...

> Try using a different deployment mechanism such as explicitly declaring root resource and provider classes using an extension of javax.ws.rs.core.Application

Have you tried that?

**Comment by gpfeifer** [comment]
Yes. I will create an issue in https://github.com/eclipse-ee4j/jersey

**Comment by gpfeifer** [comment]
You can close this. I found a solution and created a PR. See https://github.com/eclipse-ee4j/jersey/issues/5522#issuecomment-1919813114.
Thank you very much for your help.

**Comment by joakime** [comment]
@gpfeifer if we need to do something as a result of your issue / PR at jersey, please file a new issue here.
