### ISSUE TITLE
baseResource/resourceBase is no longer extracted from ServletContext

### ISSUE THREAD

**Issue by benleers** [eclipse/jetty.project#11312]
**Jetty version(s)**
12.0.5

**Jetty Environment**
ee10

**Java version/vendor** 
21.0.1

**OS type/version**
MacOS 14.2.1

**Description**
We use the Spring boot ServletContextInitializer to set the init parameter baseResource/resourceBase. 
``` java
servletContext.setInitParameter("org.eclipse.jetty.servlet.Default.resourceBase", "/location");
```

This no longer works using Jetty 12, as the way this init parameter is loaded in the DefaultServlet has changed. The parameter is renamed, but there is also a new getInitParameter method is added, to provide backwards compatibility for the old name.

``` java
    private String getInitParameter(String name, String... deprecated)
    {
        String value = super.getInitParameter(name);
        if (value != null)
            return value;

        for (String d : deprecated)
        {
            value = super.getInitParameter(d);
            if (value != null)
            {
                LOG.warn("Deprecated {} used instead of {}", d, name);
                return value;
            }
        }

        return null;
    }
```

This method does not use the getInitParameter(String) from the DefaultServlet. 

``` java
    public String getInitParameter(String name)
    {
        String value = getServletContext().getInitParameter(CONTEXT_INIT + name);
        if (value == null)
            value = super.getInitParameter(name);
        return value;
    }
```

The method tries to fetch init parameters from the ServletContext (with the CONTEXT_INIT prefix) first and then falls back to the ServletConfig. 

I think the getInitParameter(String,String) should be altered so that it uses the getInitParameter(String) from the DefaultServlet

**Comment by joakime** [comment]
Do you have access to either the `ServletContextHandler` or the `WebAppContext` during your init?

**Comment by joakime** [comment]
Opened PR #11314
