### ISSUE TITLE
Duplicate context attribute map

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1132]
Jetty has 2 context attribute maps, one in `ContextHandler` which is never reset when the context is stopped, and one in the `ServletContext` implementation that is reset when the context is stopped.

Wondering if we really need two of them, and if the difference in behavior is justified.

**Comment by joakime** [comment]
I would think that the `ServletContextHandler` version should override the `ContextHandler` version.

**Comment by gregw** [comment]
The reason for two maps is that some attributes are set before start and need to remain over start stop start stop cycles. Other attributes are set during start or by the app and must be cleared during stop to avoid leaks and to ensure the next start does not see attr from a previous cycle. 

We could have one map and a smart clear.

**Comment by sbordet** [comment]
Two maps is fine, I was just wondering the reason behind. Thanks !
