### ISSUE TITLE
Change jetty-nosql MongoDB dependency from unmaintained mongo-java-driver to mongodb-driver-sync

### ISSUE THREAD

**Issue by jchernin4** [eclipse/jetty.project#11322]
**Jetty version(s)**
12

**Enhancement Description**

Jetty is currently using mongo-java-driver to manage it's sessions, but this is no longer maintained by MongoDB. It was moved to mongodb-driver-sync, which is the most up-to-date.

**Comment by joakime** [comment]
If that happens, it will only happen on Jetty 12.

**Comment by olamy** [comment]
pr #11681

**Comment by olamy** [comment]
@jchernin4 feel free to test the linked PR
