### ISSUE TITLE
jetty9.2  jdbc

### ISSUE THREAD

**Issue by Paladnix** [eclipse/jetty.project#1133]
I want to connect with mysql in my jsp code. I have download the mysql-connector.jar and put it in the web-inf/lib than I import the java.sql.*  however when I open the web page it show me that it can not find the Driver  of mysql.
I want to know how could I do .
AND when the jetty compile my jsp , where it load the jar I downloaded from.
I donot ues the mvn or eclipse .
I just use the command line.
thanks for you to help me.

**Comment by janbartel** [comment]
@Paladnix can you please post your code where you load the driver, and please also post the error message output in full?

Please also post the version of jetty you are using, and the version of mysql.

**Comment by joakime** [comment]
Closing as Unable to Replicate.  Feel free to reopen if you have more information.
