### ISSUE TITLE
Charset issue in jetty 12 headers

### ISSUE THREAD

**Issue by PavelTurk** [eclipse/jetty.project#11338]
**Jetty Version**

Jetty 12.0.3 .

**Jetty Environment**
 ee10 

**Java Version**
openjdk version "21.0.1" 2023-10-17

**Question**

In jetty-http module in org/eclipse/jetty/http/encoding.properties I have the following lines:
```
...
text/html=utf-8
text/plain=iso-8859-1
...
```

How when I get response from server I have in my headers:

```
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Language: en-US
Content-Type: text/html;charset=iso-8859-1
Date: Tue, 23 Jan 2024 18:24:54 GMT
Expires: 0
Pragma: no-cache
Server: Jetty(12.0.3)
```

As you see it is text/html but charset is not utf-8.

Could anyone say if it is a bug or not? If not how to make jetty use utf-8 by default for text/html?

**Comment by sbordet** [comment]
Do you (or the application, or some library that generates the HTML) explicitly set the content encoding?

Also bear in mind that the default encoding mandated by the Servlet Specification and HTTP/1.1 is ISO-8859-1 for historical reasons.

We will double-check.
Do you have an example snippet of exactly what you are doing to generate the response?
For example, do you call `response.setContentType()`, or similar methods?

**Comment by PavelTurk** [comment]
@sbordet Thank you for a quick response. 

I use Jetty + Spring + Thymeleaf. When I removed Spring and Thymeleaf and used a pure Servlet then from Jetty I got `text/html;charset=utf-8`. 

So the problem was not in Jetty.

If anyone has same problem I fixed it this way:

```
@Bean
public ViewResolver viewResolver() {
    var resolver = new ThymeleafViewResolver();
    resolver.setCharacterEncoding("UTF-8"); <--- add this line
   ...
}
```
