### ISSUE TITLE
Content-type additional parameters

### ISSUE THREAD

**Issue by michal-trnka** [eclipse/jetty.project#11339]
**Jetty version(s)**
12.0.5

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)

**OS type/version**
Ubuntu / Mac OS Ventura 13.4 

**Description**
When sending POST requests with Content-type application/x-www-form-urlencoded the behaviour is different between Jettty 11 and 12.

Sending additional parameter in the header causes request.getParameterMap() to be empty, while in Jetty 11 it was not empty. 
ParameterMap is used by Spring to map request into RequestObjests.
This can (and do) cause issues with backward compatibility when migrating.

Based on preliminary investigation I did it seems that the bug stems from:
1.  Here the charset is determined to be null https://github.com/jetty/jetty.project/blame/a2d86c7f674a831fcd6cf2c27961b95ab0bab417/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/FormFields.java#L55C9-L55C9
2. If the charset is null, the parameters are null too https://github.com/jetty/jetty.project/blame/a2d86c7f674a831fcd6cf2c27961b95ab0bab417/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/FormFields.java#L169
3. (Spring consequence) This causes spring to incorrectly map request https://github.com/spring-projects/spring-framework/blob/d7778c0212d0e23b86fcd4585d749307c89c5bef/spring-web/src/main/java/org/springframework/http/server/ServletServerHttpRequest.java#L249

**How to reproduce?**
The issue is demonstrated here: https://github.com/michal-trnka/jetty-bug
If you send curl to both versions you get different output. Curl example (change port to 8042 for 11):
`curl --location 'http://localhost:8666/post' \
--header 'Content-Type: application/x-www-form-urlencoded; param=value' \
--data-urlencode 'param1=value1' \
--data-urlencode 'param2=value2' \
--data-urlencode 'param3=value3'`

**Comment by sbordet** [comment]
Thanks for the detailed report.
Fix is in PR https://github.com/jetty/jetty.project/pull/11340.
Should be part of 12.0.6 due early this coming week.

Can you test the fix and confirm it works for you?

**Comment by michal-trnka** [comment]
I can confirm that the fix in the PR fixes the issue in the reproduction code sample.

I can also confirm that it fixes the issue in the underlying project where I have discovered the issue.

[edit]
I forgot to say thanks! I really appreciate the speed of the bug fix.
