### ISSUE TITLE
Monitor other projects (like cloudflare/quiche) for releases and file issues to upgrade our codebase accordingly

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#11350]
**Jetty version(s)**
12 / 11 / 10

**Enhancement Description**

Create a daily (cron) github action to monitor https://github.com/cloudflare/quiche for new releases, and file an issue when a new release is detected.

**Comment by joakime** [comment]
The way I see this happening ...

1. A new github action, with a cron schedule (daily or less frequent, maybe weekly?)
2. It checks `https://api.github.com/repos/cloudflare/quiche/releases/latest` for a new release.
3. When it detects a changed version it files a new Issue in this repo.

The check for new version could be done something like this ...

``` shell
RELEASE_VER=$(curl -s https://api.github.com/repos/cloudflare/quiche/releases/latest | jq -r '.tag_name')
ACTIVE_VER=$(echo jetty-quiche/quiche.version)
if [ $RELEASE_VER != $ACTIVE_VER ] ; then
    # create issue announcing $RELEASE_VER
fi
```

**Comment by joakime** [comment]
One important thing to figure out is to have our "create issue" step not constantly create a new issue (each crontab) if one exists for that specific version.

**Comment by joakime** [comment]
Looks like we could even use the `gh` command (in the action) to do much of this.

https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation

**Comment by olamy** [comment]
maybe this should create an issue in this project https://github.com/jetty-project/jetty-quiche-native and not in Jetty itself
get last release is easy as `gh release list --repo cloudflare/quiche -L 1` 
but yeah it looks like reinventing dependabot :)

**Comment by joakime** [comment]
Not reinventing dependabot, it wont make a branch / pr for sure.   (as that is super complicated)
And a https://github.com/cloudflare/quiche release is only source (it does not have binaries).
Those binaries we have to build on 3 platforms / architectures.

**Comment by olamy** [comment]
see https://github.com/jetty-project/jetty-quiche-native/pull/80

**Comment by joakime** [comment]
Fixed in https://github.com/jetty-project/jetty-quiche-native/pull/81
