### ISSUE TITLE
Avoid allocations from Method.getParameterTypes() if possible

### ISSUE THREAD

**Issue by dreis2211** [eclipse/jetty.project#1135]
Hey,

I found some occurences where we call Method.getParameterTypes() just to get the parameter count, which involves cloning the underlying params array every time. Since JDK 8 there is luckily Method.getParameterCount() for that which avoids the cloning.

Cheers,
Christoph

**Comment by gregw** [comment]
@dreis2211 This looks good.  Could you give us a pull request from your fork - against our jetty-9.3.x branch would be best (as master will not be released for some time).

@janbartel can you review - perhaps manually merge if no PR forthcoming.

**Comment by dreis2211** [comment]
@gregw Just to clarify. Simply another one additionally to the already merged one - just for 9.3?

**Comment by gregw** [comment]
@dreis2211 Oh I missed the fact that there was a PR already merged to master.   Did that include your commit  16334c1 made after the merge?

If so, then we'd best just cherry-pick the merge commit back to 9.3 and then merge forward to 9.4

**Comment by dreis2211** [comment]
I think you can just cherry-pick it. :)

**Comment by janbartel** [comment]
Ooops, sorry, I didn't see that it was for master. Cherry picked back to jetty-9.3 and merged forward to jetty-9.4.
