### ISSUE TITLE
Scheduler queue in the HTTP client grows infinitely when a server times out

### ISSUE THREAD

**Issue by piotrrzysko** [eclipse/jetty.project#11372]
**Jetty version(s)**
12.0.5, 12.06

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
21

**OS type/version**
macOS 13.6

**Description**
After migrating from Jetty 11.0.15 HTTP client to 12.0.5, I noticed that when a server times out, the memory used by the heap in my client application rapidly grows and is never released. A heap dump revealed that the major part of the heap is used by [the scheduler queue from the class CyclicTimeout](https://github.com/jetty/jetty.project/blob/3aed62e4959bb8c01f5975fe81e078e3ff626126/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/CyclicTimeout.java#L67). 

I've reproduced this issue (link to the repo in the section below). It turns out that the exact same setup of the client doesn't lead to this problem in 11.0.15.

**How to reproduce?**
The instructions on how to reproduce this issue have been attached to a repository with an application demonstrating the problem: https://github.com/piotrrzysko/jetty-memory-leak?tab=readme-ov-file#jetty-memory-leak.

**Comment by sbordet** [comment]
@piotrrzysko thank you for the detailed report.

Can you try #11373 and report back if it fixes the problem for you?
It does in your reproducer project, but perhaps you can try in your real code?
Thanks!

**Comment by piotrrzysko** [comment]
I tested the fix, and it works correctly. Thanks for the quick response.
