### ISSUE TITLE
Custom error pages not shown using HttpServletResponse.setStatus(error-code)

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse/jetty.project#11393]
**Jetty Version**
12.0.4

**Jetty Environment**
ee8

**Java Version**
21

**Question**

I have a `web.xml` file with multiple `4xx` and `5xx` error codes configured to produce a custom error page using the `<error-page>` XML tag. The `<location>` tag points to HTML files deployed with the web application.

It seems that any `HttpServletResponse.setStatus(4xx | 5xx)` call does not cause jetty to show these custom error pages. I can only make the 404 and 500 pages show up by requesting a non-existing URL within the web app or throwing an exception in a filter/servlet. So it only seems to work if jetty itself decides to produce a HTTP 4xx / 5xx code.

I am wondering if that is intended?

**Comment by joakime** [comment]
Surprising, as we have multiple test cases specifically for this setup that pass.

One thought, If the 404 or 500 error is generated outside of the ServletContext then that will not cause a dispatch to your declared 404 or 500 location in your web.xml (those would be dispatched the the server level error handler)

Please detail your ServletContext configuration, and how you are testing.
If you can provide a replication example that would be the best way to troubleshoot this reported issue.

**Comment by joakime** [comment]
Also, please use Jetty 12.0.6 and try again.

**Comment by jnehlmeier** [comment]
I just tried 12.0.6 and it also does not work. 

The jetty 12 container is configured to use jetty modules: `resources,jmx,logging-logback,deploy,threadpool,bytebufferpool,statistics,graceful,sessions,ee8-deploy,ee8-webapp`.

The web application is named `app.war` and thus deployed on context path `app`. Because the app is pretty large I removed all servlet context listeners, all filters and all servlets to make sure it is not the app causing the issue. Then I just added a single filter that sends 503 status code:

```java
public class StatuscodeFilter implements Filter {

  @Override
  public void doFilter(
      ServletRequest request,
      ServletResponse response,
      FilterChain chain) throws IOException, ServletException {

    ((HttpServletResponse) response).setStatus(503);

  }
}
```
The filter is then registered at `/503` in web.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd" id="WebApp_ID" version="4.0">

  <distributable/>

  <display-name>app</display-name>
  
  <session-config>
    <session-timeout>600</session-timeout>
    <cookie-config>
      <name>sid</name>
      <path>/</path>
    </cookie-config>
  </session-config>

  <filter>
    <filter-name>status</filter-name>
    <filter-class>com.example.jetty.filter.StatuscodeFilter</filter-class>
  </filter>

  <filter-mapping>
    <filter-name>status</filter-name>
    <url-pattern>/503</url-pattern>
  </filter-mapping>

  <error-page>
    <error-code>401</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

  <error-page>
    <error-code>403</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

  <error-page>
    <error-code>404</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

  <error-page>
    <error-code>405</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

  <error-page>
    <error-code>500</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

  <error-page>
    <error-code>501</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

  <error-page>
    <error-code>503</error-code>
    <location>/statuscode_error.html</location>
  </error-page>

</web-app>
```
The referenced file `statuscode_error.html` is on the root of `app.war` file.

Now you have:
- `localhost:8080`: listing of deployed apps
- `localhost:8080/doesnotexist`: default jetty 404 page
- `localhost:8080/app/`: directory listing of app
- `localhost:8080/app/doesnotexist`: shows custom error page deployed with app
- `localhost:8080/app/503`: returns 503 status code without any body/content

If filter is modified to throw a `ServletException` then `localhost:8080/app/503` will show custom error page for status code 500 deployed with app.

**Comment by jnehlmeier** [comment]
Instead of a filter one can also use a servlet. Result is the same.

**Comment by joakime** [comment]
Unable to replicate.
Error Handling in ee8 environment is working as expected.
Example webapp can be found at https://github.com/jetty/jetty-examples/tree/12.0.x/webapps/error-handling-4

That project will create a war file that deploys into ee8 environment on Jetty 12.0.6 and behaves as expected.
There is also junit5 test cases for that example project.

```
[joakim@hyperion bases]$ mkdir errors-12
[joakim@hyperion bases]$ cd errors-12/
[joakim@hyperion errors-12]$ java -jar ../../jetty-home-12.0.6/start.jar --add-modules=ee8-deploy,http,ee8-webapp
INFO  : mkdir ${jetty.base}/start.d
INFO  : ee8-deploy      initialized in ${jetty.base}/start.d/ee8-deploy.ini
INFO  : server          transitively enabled, ini template available with --add-modules=server
INFO  : sessions        transitively enabled, ini template available with --add-modules=sessions
INFO  : ee8-webapp      initialized in ${jetty.base}/start.d/ee8-webapp.ini
INFO  : resources       transitively enabled
INFO  : threadpool      transitively enabled, ini template available with --add-modules=threadpool
INFO  : ee8-security    transitively enabled
INFO  : deploy          transitively enabled
INFO  : logging-jetty   transitively enabled
INFO  : security        transitively enabled
INFO  : ee8-servlet     transitively enabled
INFO  : http            initialized in ${jetty.base}/start.d/http.ini
INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-jetty
INFO  : logging/slf4j   dynamic dependency of logging-jetty
INFO  : bytebufferpool  transitively enabled, ini template available with --add-modules=bytebufferpool
INFO  : mkdir ${jetty.base}/resources
INFO  : mkdir ${jetty.base}/webapps
INFO  : copy ${jetty.home}/modules/logging/jetty/resources/jetty-logging.properties to ${jetty.base}/resources/jetty-logging.properties
INFO  : Base directory was modified

[joakim@hyperion errors-12]$ cp /home/joakim/code/jetty/github-jetty/jetty-examples/webapps/error-handling-4/target/error-handling.war webapps/
[joakim@hyperion errors-12]$ echo "Environment: ee8" >> webapps/error-handling.properties

[joakim@hyperion errors-12]$ java -jar ../../jetty-home-12.0.6/start.jar
2024-02-12 08:52:37.653:INFO :oejs.Server:main: jetty-12.0.6; built: 2024-01-30T02:43:24.387Z; git: 78ab6e6ba163f89cdd97f2ae0283fbb5e371cfaf; jvm 17.0.6+10
2024-02-12 08:52:37.675:INFO :oejdp.ScanningAppProvider:main: Deployment monitor ee8 in [file:///home/joakim/code/jetty/distros/bases/errors-12/webapps/] at intervals 0s
2024-02-12 08:52:37.683:INFO :oejd.DeploymentManager:main: addApp: App@ea6147e[ee8,null,/home/joakim/code/jetty/distros/bases/errors-12/webapps/error-handling.war]
2024-02-12 08:52:37.803:INFO :oejew.StandardDescriptorProcessor:main: NO JSP Support for /error-handling, did not find org.eclipse.jetty.ee8.jsp.JettyJspServlet
2024-02-12 08:52:37.835:INFO :oejsh.ContextHandler:main: Started oeje8n.ContextHandler$CoreContextHandler@19b843ba{error handling webapp,/error-handling,b=file:///tmp/jetty-0_0_0_0-8080-error-handling_war-_error-handling-any-11988055499795156569/webapp/,a=AVAILABLE,h=oeje8n.ContextHandler$CoreContextHandler$CoreToNestedHandler@64ec96c6{STARTED}}
2024-02-12 08:52:37.838:INFO :oejs.DefaultSessionIdManager:main: Session workerName=node0
2024-02-12 08:52:37.851:INFO :oejs.AbstractConnector:main: Started ServerConnector@2a7ed1f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2024-02-12 08:52:37.857:INFO :oejs.Server:main: Started oejs.Server@757acd7b{STARTING}[12.0.6,sto=5000] @1006ms
```

If you open `http://localhost:8080/error-handling/` in your browser at this point, there's an index.html that presents a bunch of triggers for errors.

At this point we need a replication example.
Please fork the https://github.com/jetty/jetty-examples repo, and modify that `webapps/error-handling-4` example to demonstrate the bug you are reporting.
Send us the link to your fork that demonstrates this issue.

**Comment by joakime** [comment]
> ```java
> public class StatuscodeFilter implements Filter {
> 
>   @Override
>   public void doFilter(
>       ServletRequest request,
>       ServletResponse response,
>       FilterChain chain) throws IOException, ServletException {
> 
>     ((HttpServletResponse) response).setStatus(503);
> 
>   }
> }
> ```

One thing to note, the call to `HttpServletResponse.setStatus(503)` does not result in an ERROR dispatch on the servlet spec.
That's a normal status code set.

If you use `HttpServletResponse.sendError(503)` then that results in an ERROR dispatch back to the `ServletContext`.

**Comment by jnehlmeier** [comment]
Thanks for taking a closer look at it. The example project is pretty nice for future reference.
I didn't know the subtle difference between `setStatus(503)` and `sendError(503)` but it is logical that such a difference exists. Because of configuration changes I now have to use `sendError` for some routes.
