### ISSUE TITLE
Bring back overlay deployer

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#114]
migrated from Bugzilla [#404508](https://bugs.eclipse.org/bugs/show_bug.cgi?id=404508)
status REOPENED severity _normal_ in component _server_ for _9.0.x_
Reported in version _9.0.0_ on platform _PC_
Assigned to: Joakim Erdfelt

On 2013-03-27 18:12:06 -0400, Greg Wilkins wrote:

> port the overlay deployer to jetty-9

On 2013-05-13 16:46:06 -0400, Jesse McConnell wrote:

> I have this brought over locally, am still sorting out how to reconcile with the lose of the contexts directory and the general direction we are going with deployment.
> 
> leaning towards perhaps jetty.home/webapps/overlays.d with that being configurable.

On 2013-05-20 10:25:05 -0400, Jesse McConnell wrote:

> overlay is renabled, decided to keep things they way they were for the time being with regards to the overlay directory and we can review this for 9.1 when we roll in the new startup configuration process

On 2013-07-05 08:38:38 -0400, Sergey Korzhevsky wrote:

> I cannot find overlay components in jetty-distribution-9.0.4.v20130625.tar.gz, e.g. there are no 
> etc/jetty-overlay.xml
> lib/jetty-overlay-deployer*
> 
> Although they are exist in  jetty-distribution-8.1.11.v20130520

On 2013-07-05 08:45:06 -0400, Jesse McConnell wrote:

> hm.  they made it into the repository but not the distro looks like
> 
> http://repo2.maven.org/maven2/org/eclipse/jetty/jetty-overlay-deployer/9.0.4.v20130625/
> 
> if you unjar the -config artifact from the above user and put the actual binary jar into the lib dir it should work, we'll have to take a look at what didn't work in the distro for this

On 2013-07-05 09:56:16 -0400, Sergey Korzhevsky wrote:

> Thank you, Jesse!

On 2013-08-20 12:35:21 -0400, Jesse McConnell wrote:

> Greg, I am passing this over to you since I don't think it is worth doing more on this for 9.0 but it should be a use case for 9.1 distro rejiggering work

On 2014-06-16 12:52:12 -0400, Jan Bartel wrote:

> **\* Bug 437468 has been marked as a duplicate of this bug. ***

On 2014-06-24 16:14:10 -0400, Greg Wilkins wrote:

> Joakim,
> 
> I'm passing this one to you as I've not got time to consider it.   This is not a high priority, but if you wanted a pet project it would be interesting to make the overlays work with the multiple base directories of start.jar mechanism as there are some very similar deployment concepts there.
> 
> But not a huge priority unless a sponsor come forward - remember the only thing worse than generalizing from one example is to generalize from no examples :)

**Comment by gregw** [comment]
Review this in light of docker

**Comment by gregw** [comment]
The overlay deployer was unmaintained an no interest has been shown for some time, so it has been removed from 10.0.x
