### ISSUE TITLE
What is the `jetty.deploy.scanInterval` default?  module, ini, code, and documentation do not agree.

### ISSUE THREAD

**Issue by razisam** [eclipse/jetty.project#11424]
**Jetty version(s)**
Jetty 12.0.6

**Jetty Environment**
ee9

**Java version/vendor** `(use: java -version)`
jdk21

**OS type/version**
linux

**Description**
i was sure, the suggestions in ee9-deploy.mod/.ini are telling us, what the default-value is and if we want it another way, we can change it in the ini file:
```
...
## Monitored directory scan period (seconds)
# jetty.deploy.scanInterval=1
...
```
but looking into the code, the default of this scanInterval is "0":
![image](https://github.com/jetty/jetty.project/assets/59828907/95f6e425-216d-4e2e-9a56-77f95826ff48)

is this a bug or some feature, which i do not find any default value for in documentation?
maybe it's also just missing "default=1" in /etc/jetty-ee9-deploy.xml:

`<Set name="scanInterval" property="jetty.deploy.scanInterval"/>`
-->
`<Set name="scanInterval" property="jetty.deploy.scanInterval" default="1"/>`

**Comment by joakime** [comment]
The Jetty XML syntax ...

``` xml
<Set name="foo" property="propname"/>
```

means that the setter `.setFoo(...)` will be called if the property `propname` is set.
If the property `propname` is unset, then the named setter is not even called.

This means the defaults in code win if you don't set a the property.

This is expected and intentional behavior, not a bug in the XML that needs addressing.
The commented out example property in the module and ini file could be updated, but ultimately those are just examples, not default values.

**Comment by razisam** [comment]
> This is expected and intentional behavior, not a bug in the XML that needs addressing. The commented out example property in the module and ini file could be updated, but ultimately those are just examples, not default values.

debugging/klicking through jetty code should not be the source of information.
but maybe i missed the "default-value" documentation somewhere. it was "1" in the previous versions and was changed in jetty 12. so if you upgrade von jetty11 to jetty12, there is no chance to see this change, only by noticing the "new behaviour", so please change the "ini-template" at least. it might be an example only, but i'ms sure it's missleading because many people think, it's also the default value.

Also look here:

![image](https://github.com/jetty/jetty.project/assets/59828907/83c23a43-f0e2-40f4-a596-dab1fc246ac0)

**Comment by joakime** [comment]
Now documentation, that's an important thing to address.
Also, WHY is it defaulting to 0? (need to dig into the history for that)

But still, the XML doesn't need changing to address either of those concerns.
