### ISSUE TITLE
Review number of acceptor threads

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#11432]
**Jetty version(s)**
12+

**Description**
As reported in #11421, people can get confused by multiple acceptor threads competing for the blocking `accept()` call.

A suggestion is that the heuristic should default to 1, or even to 0 (i.e. the accepts will be non-blocking).

**Comment by zhipengzuo** [comment]
hello ,about selectors should be set?

**Comment by sbordet** [comment]
@zhipengzuo can you clarify your question?

**Comment by zhipengzuo** [comment]
> @zhipengzuo can you clarify your question?
if you set acceptor = 1 
should I also set selectors=1?
![image](https://github.com/jetty/jetty.project/assets/54702578/7a7fbda0-f3e4-4f87-8693-0d341264bb2d)

**Comment by gregw** [comment]
@zhipengzuo you typically want more than 1 selector if you want high throughput.    Thus I would leave this at -1 to let the heuristic pick a value for you.
If you do want to be specific about it, then you would need to benchmark your specific algorithm to find the best value (which is unlikely to be 1).

**Comment by sbordet** [comment]
@zhipengzuo see also the documentation:
https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-connector-selectors

**Comment by zhipengzuo** [comment]
> @zhipengzuo see also the documentation: https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-connector-selectors

thanks.
