### ISSUE TITLE
Quote escaping in HTML file

### ISSUE THREAD

**Issue by PavelTurk** [eclipse/jetty.project#11441]
**Jetty Version**
12.0.6

**Question**
I work with Jetty sources and found out that in file `./jetty-home/src/main/resources/modules/demo.d/root/index.html` in the first line the first double quote is escaped in a strange way. I think this is a bug (not significant of course) but I am not 100% sure.
```
<html xmlns=\ "http://www.w3.org/1999/xhtml\" xml:lang=\"en\">
              ^
```

**Comment by joakime** [comment]
Confirmed.

https://github.com/jetty/jetty.project/blob/bfac61cd89f2c70ad6d5706b5f03989d61c5b02a/jetty-home/src/main/resources/modules/demo.d/root/index.html#L1

**Comment by joakime** [comment]
Fixed.
