### ISSUE TITLE
Problem adding a Mime Mapping for "*.js.gz" (IllegalArgumentException: extensions cannot contain '.')

### ISSUE THREAD

**Issue by Verdoso** [eclipse/jetty.project#11449]
**Jetty version** 12.0.6

**Jetty Environment**
ee10

**Java version/vendor** 
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

**OS type/version**
Windows 10

**Description**
I used to register and extra Mime Mapping for the compressed JavaScript code and those are "*.js.gz" files. These files have to be treated differently because you have to add the encoding gzip header but set the mime type as text/javascript, otherwise they are not uncompressed but treated as JavaScript source.

After upgrading to Jetty 12, I get an exception when trying add such mime type due to this line in org.eclipse.jetty.http.MimeTypes class:
```
        public String addMimeMapping(String extension, String type)
        {
            if (extension.contains("."))
                throw new IllegalArgumentException("extensions cannot contain '.'");
            return _mimeMap.put(StringUtil.asciiToLowerCase(extension), normalizeMimeType(type));
        }
```
**How to reproduce?**
Simply try to add a new mime mapping for "js.gz" files.

Is there any way one can add these kind of mappings now for Jetty 12?
Thank you
D.

**Comment by joakime** [comment]
Why are you attempting to work around the "precompressed" behaviors?
Lets say you have 2 files on disk (or as web resources in your WAR).

* `/css/foo.js`
* `/css/foo.js.gz`

If the HTTP Client requests `/css/foo.js` then one of those 2 files is actually served (by DefaultServlet / ResourceHandler / ResourceService).

* If the HTTP Client (eg: Browser) sent a request header with `Accept-Encoding: gzip` then `/css/foo.js.gz` is actually served from disk.
* If the HTTP Client (eg: Browser) sent a request without the `Accept-Encoding` header (or that header lacks a `gzip` entry) then `/css/foo.js` is actually served from disk.

It is a good idea to have both the uncompressed AND the compressed versions present in your web resources.
Also you can register other precompressed formats.
Example: you can use the `"precompressed"` init-param on `DefaultServlet` to add more, such as ...

In your `WEB-INF/web.xml`
``` xml
    <servlet>
        <servlet-name>default</servlet-name>
        <init-param>
            <param-name>precompressed</param-name>
            <param-value>br=.br,gzip=.gz,bzip2=.bz</param-value>
        </init-param>
    </servlet>
```

Which would also support precompressed brotli or bzip entries as well.

**Comment by Verdoso** [comment]
Hey there,
I'm migrating the code up from previous versions, and I introduced the code quite a while ago because simply leaving the files without adding the mime type, and a specific header, was not working and that was the soluction that I found.

But you're right, I'll try again and see if whatever it was (Spring Boot is also in between and has been migrated too) is fixed.
Thanks

**Comment by Verdoso** [comment]
Hello again,
You have to configure Spring also so the information gets to Jetty but I managed to get it work. In fact, it's now a simple property (spring.web.resources.chain.compressed) to enable it, so great.
Thanks for the pointer. I was so focused on getting the previous code to work that I forgot to check I might not need that hack anymore.
Cheers!
