### ISSUE TITLE
restricting to TLS1.2V for client calls to AWS

### ISSUE THREAD

**Issue by durga-kumari-tfc** [eclipse/jetty.project#11458]
**Jetty Version**
9.3.19

**Jetty Environment**

**Java Version**
8

**Question**

HI Team, I have to set jdk.tls.client.protocols="TLSv1.2" in Jetty so that any AWS calls happen can be enabled only with TLS1.2 and not 1.3. I don't see SslClientConnectionFactory settings. We already have Jetty SSL enabled. Will it work if I set SslContextFactory.addExcludeProtocols ? Is this right approach?

**Comment by sbordet** [comment]
The right approach would be:

```java
SslContextFactory.Client sslClient = ...;
sslClient.setIncludeProtocols("TLSv1.2");
```

In this way, only TLS 1.2 will be used.

**Comment by sbordet** [comment]
By the way, Jetty 9.3 is _extremely_ out of date.

See 
* #7958
* #10485.

You must upgrade to Jetty 12.

**Comment by durga-kumari-tfc** [comment]
> ```java
> SslContextFactory
> ```

Hi, Thanks for your response.

In the implementation of the method...
public void setIncludeProtocols(String... protocols) {
        this._includeProtocols.clear();
        this._includeProtocols.addAll(Arrays.asList(protocols));
    }
 I see its clearing existing protocols and adding only 1.2

In my case I just want to remove 1.3 and everything else must be there including CIPHERs

May be below method works?

public void addExcludeProtocols(String... protocol) {
        this._excludeProtocols.addAll(Arrays.asList(protocol));
    }

Please let me on this.

**Comment by sbordet** [comment]
@durga-kumari-tfc the methods are self explanatory and you read the source code.
Call the methods you need for your use case.
