### ISSUE TITLE
EOF error while closing not fully consumed ContentSourceInputStream 

### ISSUE THREAD

**Issue by ovidijusnortal** [eclipse/jetty.project#11460]
Jetty version(s)
12.0.6 (along with Spring Boot 3.2.3)

Jetty Environment
ee10

Java version/vendor (use: java -version)
17 (Zulu17.46+19-C)

OS type/version
macOS

Description

For example I have something like this

```
@Override
public boolean handle(Request request, Response response, Callback callback) throws Exception {
    try (var in = Content.Source.asInputStream(request)) {
        in.read();
        //Error or other cause preventing from reading the input stream to the end
    }

    Content.Sink.asOutputStream(response).write("Hello".getBytes());
    callback.succeeded();
    return true;
}
```

If request has body with couple characters I will get this error:

```
java.io.IOException: closed before EOF
	at org.eclipse.jetty.io.content.ContentSourceInputStream.close(ContentSourceInputStream.java:154)
	at org.example.Main$1.handle(Main.java:30)
```

So question would be: how properly handle requests body for those cases where we may decide for example that contents  are 
invalid (malformed XML body) while reading inputStream? do we just ignore exception from close()?

**Comment by joakime** [comment]
> ``` java
> @Override
> public boolean handle(Request request, Response response, Callback callback) throws Exception {
>     try (var in = Content.Source.asInputStream(request)) {
>         in.read();
>         //Error or other cause preventing from reading the input stream to the end
>     }
> 
>     Content.Sink.asOutputStream(response).write("Hello".getBytes());
>     callback.succeeded();
>     return true;
> }

You didn't close the OutputStream.

Change it to use the OutputStream properly.

``` java
try (OutputStream out = Content.Sink.asOutputStream(response)) {
    out.write("Hello".getBytes(UTF_8));
}
callback.succeeded();
return true;
```

The reason is that your OutputStream is not managed by Jetty, but Jetty expects the Content.Sink.write() that eventually reports that it is the last chunk of response data (so that things in the HTTP spec can be completed properly, eg: transfer-encoding, connection management, persistence management, trailers, chunking, etc)

**Comment by joakime** [comment]
> If request has body with couple characters I will get this error:
> 
> ```
> java.io.IOException: closed before EOF
> 	at org.eclipse.jetty.io.content.ContentSourceInputStream.close(ContentSourceInputStream.java:154)
> 	at org.example.Main$1.handle(Main.java:30)
> ```
> 
> So question would be: how properly handle requests body for those cases where we may decide for example that contents are invalid (malformed XML body) while reading inputStream? do we just ignore exception from close()?

You can just open the InputStream and read, and then when you are absolutely done reading close the InputStream.

Keep in mind that you must honor the full read of the input in order to satisfy the HTTP spec (for things like transfer-encoding, content-encoding, connection management, persistence management, trailers, chunking, etc).
So if you don't read the request fully (even it it's bad and there's no point in reading the rest of the request), then other features of HTTP have to be dealt with.

In your example of a bad XML, I would recommend catching the failed XML parse, and then respond with a 4xx status code (400 Bad Request?, or something else to convey that your application failed to parse the request body).  Make sure you send `Connection: close` header on the response headers to tell the client that you have no intention of further reading of the request.

Something like this ...

``` java
InputStream in = Content.Source.asInputStream(request);
try {
    doc = xmlparser.parse(in);
} catch(XMLException e) {
    Response.writeError(request, response, callback, HttpStatus.BAD_REQUEST_400, "Bad XML", e);
    return;
}
// consume the remainder of the input stream, up to EOF.
String remainder = IO.toString(in);
if (!remainder.isEmpty())
{
    Response.writeError(request, response, callback, HttpStatus.BAD_REQUEST_400, "Content after XML document not supported", e);
    return;
}
in.close();
// produce response here
```

Note: the `Response.writeError()` methods will deal with the connection close, and unconsumed request body content.
The results of using `writeError()` will also trigger the Server ErrorHandler to produce the error.
You can customize the `ErrorHandler` behavior with configuration, or provide your own `ErrorHandler`.

**Comment by ovidijusnortal** [comment]
> Keep in mind that you must honor the full read of the input in order to satisfy the HTTP spec (for things like transfer-encoding, content-encoding, connection management, persistence management, trailers, chunking, etc). So if you don't read the request fully (even it it's bad and there's no point in reading the rest of the request), then other features of HTTP have to subverted.
> 
> In your example of a bad XML, I would recommend catching the failed XML parse, and then respond with a 4xx status code (400 Bad Request?, or something else to convey that your application failed to parse the request body). Make sure you send `Connection: close` header on the response headers to tell the client that you have no intention of further reading of the request.

Thanks for explanations and examples. This gives me better better understanding what is happening here and how to deal with that. 
Did migration from previous version of jetty and tried to keep everything as close as possible to old implementations, looks like I will need to invest bit more time to avoid some random errors in failure cases.

**Comment by joakime** [comment]
@ovidijusnortal also keep in mind that depending on your choice of XML parser (or other parser, like JSON), there could be options in that parser to read to EOF as well.

Take this example from Jackson JSON parser, which configures json to read to EOF always, and fail if there is content after the JSON document, even a valid JSON document ...

``` java
    public ObjectMapper restObjectMapper() {
        ObjectMapper restObjectMapper = new ObjectMapper();
        restObjectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        restObjectMapper.enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS); // <-- the key change to read to EOF always.
        return restObjectMapper;
    }
```
