### ISSUE TITLE
HttpURI.toURI() sets userInfo to null

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#11465]
**Jetty version(s)**
12.0.6

**Jetty Environment**
core

**Description**
Similar to https://github.com/jetty/jetty.project/issues/7750 I am wondering why `toURI()` forces `userInfo` to `null` when other methods use it as-is.

I am expecting `toURI()` to return all the available information.

**Comment by gregw** [comment]
Yeah, I see no reason not to pass those over now.   If fact, considering that all URI constructors end up creating and then parsing the string version of the URI, we might as well just pass in the string version anyway.   See PR #11468
