### ISSUE TITLE
The StatisticsHandler doesn't count 2xx codes

### ISSUE THREAD

**Issue by AlekseyMishanin** [eclipse/jetty.project#11482]
**Jetty version(s)**
12.0.6

**Jetty Environment**
ee10

**Java version/vendor** 
18.0.2

**OS type/version**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar

**Description**
Hello friends!!!
When I use `StatisticsHandler` in Jetty 12, I come across the fact that `2xx` codes are not counted, that is, the counter is always 0.

For example, I have a rest controller in a simple spring-boot project. And when my controller writes json in a response, `StatisticsHandler` does not count this event as `2xx`. 
When I looked closely at the `StatisticsHandler`, I saw that the response codes are calculated in the `onResponseBegin` method. This method is called in the `notifyOnResponseBegin` method of the parent `EventsHandler` class. `notifyOnResponseBegin` is called in two places:
```
    @Override
    public boolean handle(Request request, Response response, Callback callback) throws Exception
    {
         ...
         Request.addCompletionListener(request, x ->
         {
             notifyOnResponseBegin(roRequest, wrappedResponse);
             ...
         });
        ...
    }
```
```
private class EventsResponse extends Response.Wrapper
    {
        ...
        @Override
        public void write(boolean last, ByteBuffer byteBuffer, Callback callback)
        {
            notifyOnResponseBegin(getRequest(), this);
            ...
        }
        ...
    }
```
When the rest controller writes the response body, the `write` method is called first and the `listener` is called at the end. But when the `write` method is called, the response status is 0, and when the `listener` is called, the response status is 200, but it is ignored.

**How to reproduce?**
[Here](https://github.com/AlekseyMishanin/jetty-statistics-handler) is a project that can help you reproduce the problem. This project shows that `StatisticsHandler` counts 4xx/5xx codes, but not 2xx

**Comment by AlekseyMishanin** [comment]
This bug was not present in Jetty 11 and below.

**Comment by lorban** [comment]
Thanks for reporting this issue; this is indeed a bug that needs to be addressed.
