### ISSUE TITLE
Wrong WebSocketPolicy validations 

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1149]
`WebSocketPolicy` performs a number of validations that are wrong.

The `inputBufferSize` is not related to the max message size, and should not be compared with it.
In particular, it validates that is less than the max message size, which causes cometd/cometd#690.

Also, the `idleTimeout` and the `asyncWriteTimeout` are not related as well and should not be compared.

**Comment by joakime** [comment]
If the `inputBufferSize` is larger then `max message size` then we'd have to perform more ByteBuffer allocation and copying in the binary message cases. Is that really desired?

We already have to do allocation / copy this in the Text message cases, and decompression cases, so perhaps this is an obsolete check.

There are many different `idleTimeout`, which one specifically are you referencing in this issue?

**Comment by sbordet** [comment]
@joakime I don't see how a larger `inputBufferSize` would cause any additional copy.
The `idleTimeout` is `WebSocketPolicy.idleTimeout`.

**Comment by joakime** [comment]
These validations have been adjusted in jetty-9.4.7-SNAPSHOT and newer.
