### ISSUE TITLE
CustomRequestLog.ignorePath doesn't work as documented

### ISSUE THREAD

**Issue by ikozar** [eclipse/jetty.project#11490]
**Jetty Version**
12.0.6

**Jetty Environment**
core

**Java Version**
1.17

**Question**
I'm trying to skip logging /actuator/* endpoints from accesslog, but org.eclipse.jetty.server.CustomRequestLog#_ignorePathMap doesn't match with my request because it uses full URI path - request.getHttpURI().toString() instead of request.getHttpURI().getCanonicalPath()

Could you suggest how to skip the endpoints accesslog?

**Comment by joakime** [comment]
Merged PR #11638 
This will be available on Jetty 12.0.9
