### ISSUE TITLE
how to inject a business object into an endpoint?

### ISSUE THREAD

**Issue by damnms** [eclipse/jetty.project#11502]
**Jetty Version**
12.0.7

**Jetty Environment**

core/ee10

**Java Version**
17

**Question**
I have the same problem/question like in https://stackoverflow.com/questions/60214685/how-to-pass-the-parameters-to-websocket-endpoint-hander, but i dont use WebsocketServlet but:

```
        ServletContextHandler servletContextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
        servletContextHandler.setContextPath("/");

        server.setHandler(servletContextHandler);

        // Add jakarta.websocket support
        JakartaWebSocketServletContainerInitializer.configure(servletContextHandler, (context, container) ->
        {
            // Add echo endpoint to server container
//            ServerEndpointConfig.Builder.create(EventSocket.class, "/").configurator()
            //container.addEndpoint(EventSocket.class);
              container.addEndpoint(???);

        });
```

Do i have to create my own EndpointConfiguration and copy/paste a lot of the existing code or is there an easier way to achieve that?
The reason i am asking is that my application starts in a console like mode but also spawns a jetty in the background (via websockets) and makes the state available, so i must create my own EventSocket (contains the @OnError @OnClose etc.) which has a constructor for this business object.

**Comment by lachlan-roberts** [comment]
This would be very straight forward using the Jetty WebSocket API but since you are using Jakarta WebSocket API I think you will need a `ServerEndpointConfig.Configurator`.

You should be able to add your parameters into the `ServerEndpointConfig.getUserProperties()` map, and then downcast them in onOpen. Something like this:
```java
JavaxWebSocketServletContainerInitializer.configure(_context, (context, container) ->
{
    Object businessObject = new Object();
    ServerEndpointConfig config = ServerEndpointConfig.Builder
        .create(MyServerEndpoint.class, "/")
        .configurator(new ServerEndpointConfig.Configurator()
        {
            @Override
            public void modifyHandshake(ServerEndpointConfig sec, HandshakeRequest request, HandshakeResponse response)
            {
                super.modifyHandshake(sec, request, response);
                sec.getUserProperties().put("businessObject", businessObject);
            }
        })
        .build();
    container.addEndpoint(config);
});
```

**Comment by damnms** [comment]
I have no problem to switch to Jetty WebSocket API when its more straight forward :)
I will read about that! 

edit: so i switched now to jetty's websocket api, and i use now 
```
@Override
    protected void configure(JettyWebSocketServletFactory jettyWebSocketServletFactory) {
        jettyWebSocketServletFactory.register(EventSocket.class);
    }
```

where/how can i overwrite this now? Do i have to create my own JettyWebSocketCreator?
edit 2: guess i found it, created now my own creator and lets see if that works :)

**Comment by damnms** [comment]
thanks, it worked! 

  ```
  @Override
    protected void configure(JettyWebSocketServletFactory jettyWebSocketServletFactory) {
        JettyWebSocketCreator creator = (req, resp) ->
        {
            try {
                return new EventSocket(application);
            } catch (Throwable t) {
                return null;
            }
        };
        jettyWebSocketServletFactory.setCreator(creator);
    }
```
