### ISSUE TITLE
org.eclipse.jetty.util.Attributes.getAttribute() should specify return type if no match is found

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#11507]
**Jetty version(s)**
12.0.6

**Jetty Environment**
core

**Description**
I believe that `org.eclipse.jetty.util.Attributes.getAttribute()` returns `null` if no match is found, but the Javadoc does not specify either way. In contrast, the servlet API makes this explicit.

**Comment by gregw** [comment]
@cowwoc Can you give a quick review of #11843.  Is that what you intended?

**Comment by cowwoc** [comment]
@gregw yes. This is perfect. Thank you!
