### ISSUE TITLE
Jetty Connection 

### ISSUE THREAD

**Issue by SarathChandraRS** [eclipse/jetty.project#11521]
**Jetty Version**

**Jetty Environment**

**Java Version**

**Question**
Hi Team, 
The question is related to Jetty Connection Limit. 
In general, we use Connection limit as configuration and we set this value before Jetty start. 
But as we have setMaxConnections() method on ConnectionLimit class we can change the connections dynamically. 
Now the question is would it be ok to change the connection limit dynamically without restart. Since the method is supported mostly it would be. But I would like to know if there are any drawbacks with this mechanism ? 
Thanks.

**Comment by joakime** [comment]
What version of Jetty?
How are you configuring Jetty's Connection Limit?
What connectors are you using?
What are your connector configurations?
We need more information.

**Comment by joakime** [comment]
For Jetty 12, using a `org.eclipse.jetty.server.ConnectionLimit` bean that was created before the Connector were started, you can use the `ConnectionLimit.setMaxConnections(int)`.
But ...
* that will only work on Connectors that have "accepting" event.
* if the "limiting" feature has kicked in (you are at max) the change will not undo the limiting in place.
* after setting the `setMaxConnection(int)` only a newly accepted connection will cause the state change in the `ConnectionLimit`.
* if you use multiple Connectors, the limit is across all connectors, not per connector.

**Comment by SarathChandraRS** [comment]
Thanks @joakime 
We are currently using Jetty 10. 
As of now we are configuring it as part of constructor. Which means we set this value before we start the server. 
We have multiple connectors. Around 2. We are using using ServerConnector.

**Comment by joakime** [comment]
Jetty 11 and older are now at End of Community Support.

* #10485 
* #7958 

I can only comment about behaviors in Jetty 12 (the only supported version of Jetty at the moment)
