### ISSUE TITLE
Websocket session.close(statuscode,reason) on server only works for NORMAL (1000), all others cause 1006 ("Session Closed") on client

### ISSUE THREAD

**Issue by rickardoberg** [eclipse/jetty.project#11529]
**Jetty version(s)**
11.0.20

**Java version/vendor** `(use: java -version)`
openjdk 18.0.1

**OS type/version**
Win11

**Description**
If websocket server invokes session.close(statuscode,reason) with a status code other then NORMAL then the client onWebSocketClose is always invoked with 1006/"Session Closed". Only if you call session.close(1000,myReason) will that information be transferred to the client. I would have expected to be able to use all the standard status codes and my own reason string on the server when closing a session, but for some reason that doesn't work.

**How to reproduce?**
Call session.close(statuscode,reason) on a websocket server with any code other than 1000. Observe that client onWebSocketClose(statuscode,reason) is always invoked with 1006/"Session Closed" as values instead of the ones used to call .close on the server.

**Comment by sbordet** [comment]
@rickardoberg the [WebSocket RFC](https://datatracker.ietf.org/doc/html/rfc6455) requires some special handling for status codes, see [this section](https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.2).

The logic is implemented here:
https://github.com/jetty/jetty.project/blob/jetty-11.0.20/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/CloseStatus.java#L289

What status codes did you try exactly?

If you need to have an application-triggered status code and reason that are meaningful to the remote peer, probably best to use codes between 3000-3999 or 5000+.

**Comment by rickardoberg** [comment]
@sbordet so, what seems to be the issue is that the connection is closed. The client gets a 1006 Session Closed, no matter what the server sends, because of this line:
https://github.com/jetty/jetty.project/blame/jetty-11.0.20/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketSessionState.java#L227
That throw gets caught further up and translated to 1006. So the question is why is the connection closed prematurely, before the close handshake is all done.

I tracked this down, and the decision happens here:
https://github.com/jetty/jetty.project/blame/jetty-11.0.20/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketSessionState.java#L189
What I want to do is to use StatusCode.SERVER_ERROR in most cases, but even SHUTDOWN, BAD_PAYLOAD, TRY_AGAIN_LATER, etc. would be useful. But on everything except NORMAL the server immediately closes the connection here:
https://github.com/jetty/jetty.project/blob/922f8dc188f7011e60d0361de585fd4ac4d63064/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketCoreSession.java#L515

It looks like the frame makes it to the client, but then it checks if connection is open (see above) and gets false, throws an exception, and ends up reporting 1006 to the websocket callback.

Is this intended behaviour? Am I missing something?

**Comment by sbordet** [comment]
My suspicion is that RFC error codes are meant for implementations, not applications.

For example, BAD_PAYLOAD would refer to bad UTF-8 for text messages, but it should not be reused by applications to indicate "I did not receive the JSON field I was expecting" or similar.

@lachlan-roberts can you shed some light on what @rickardoberg pointed out above?

@rickardoberg just out of curiosity, you should be able to send status codes > 3000 and have them relayed to the client.
Would that be a less appealing solution for you?

**Comment by rickardoberg** [comment]
Well, I always prefer using well known codes, like HTTP status codes for example, whenever possible. In this case some of the codes match perfectly with the intent, like SERVER_ERROR or SHUTDOWN, so it did seem appealing to use them from the application layer. If that would be possible, great, if not then I guess I have to just shift them up into 3000 range and treat them the same way.

**Comment by joakime** [comment]
Jetty 11 is now at End of Community Support.

See:

* #10485 

Would recommend upgrading to Jetty 12.

Note that Jetty 11 and Jetty 12 both pass the Autobahn WebSocket Testsuite, and are able to send/receive the entire range of RFC6455 status codes that are allowed to be sent (note: not all codes are allowed to be sent over the network, especially so for codes in the `1xxx` range, as many are designated as local side status codes only.  Also local failures trump remote failures in cases where the shutdown handshake didn't properly complete)

**Comment by rickardoberg** [comment]
I've updated our entire codebase to Jetty 12 now. It was quite a big change, but OMG the new APIs are fabulous. Closing this ticket. Thanks @sbordet for assistance.
