### ISSUE TITLE
Jetty pom depends on unpublished dependency

### ISSUE THREAD

**Issue by johngmyers** [eclipse/jetty.project#1152]
I was attempting to do a snapshot build of Jetty in order to test the fix to #1146. The build failed with

[ERROR] Failed to execute goal org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.2:attach-version-text (attach-version) on project jetty-project: Execution attach-version of goal org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.2:attach-version-text failed: Plugin org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.2 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.jetty.toolchain:jetty-version-maven-plugin:jar:2.2 -> org.kohsuke:github-api:jar:1.73 -> com.infradna.tool:bridge-method-annotation:jar:1.14 -> org.jenkins-ci:annotation-indexer:jar:1.4: Failed to read artifact descriptor for org.jenkins-ci:annotation-indexer:jar:1.4: Could not find artifact org.jenkins-ci:jenkins:pom:1.26 in [redacted]

Indeed, org.jenkins-ci:jenkins:pom is not published in Maven Central.

**Comment by olamy** [comment]
Hi,
You can our snapshot repo:
		<repository>
			<id>jetty.snapshot</id>
			<url>https://oss.sonatype.org/content/repositories/jetty-snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>

Otherwise regarding jenkins you can add this repo in your settings:
          <id>jenkins-repository</id>
          <url>http://repo.jenkins-ci.org/public/</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>

Anyway I agree this is a weird dependency. Maybe we can check that.

**Comment by gregw** [comment]
Strange?  I see when I do a `mvn dependency:tree` in the top level.  
```
gregw@Tile440: ~/src/jetty-version-maven-plugin ((jetty-version-maven-plugin-2.2))
[2033] mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Jetty:: Version Management Maven Plugin 2.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jetty-version-maven-plugin ---
[INFO] org.eclipse.jetty.toolchain:jetty-version-maven-plugin:maven-plugin:2.2
[INFO] +- org.apache.maven:maven-plugin-api:jar:2.2.1:compile
[INFO] +- org.apache.maven:maven-project:jar:2.2.1:compile
[INFO] |  +- org.apache.maven:maven-settings:jar:2.2.1:compile
[INFO] |  +- org.apache.maven:maven-profile:jar:2.2.1:compile
[INFO] |  +- org.apache.maven:maven-model:jar:2.2.1:compile
[INFO] |  +- org.apache.maven:maven-artifact-manager:jar:2.2.1:compile
[INFO] |  |  +- org.apache.maven:maven-repository-metadata:jar:2.2.1:compile
[INFO] |  |  +- org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-6:compile
[INFO] |  |  \- backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[INFO] |  +- org.apache.maven:maven-plugin-registry:jar:2.2.1:compile
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.11:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:1.5.15:compile
[INFO] |  +- org.apache.maven:maven-artifact:jar:2.2.1:compile
[INFO] |  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[INFO] |     \- classworlds:classworlds:jar:1.1-alpha-2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.0.1:compile
[INFO] +- org.kohsuke:github-api:jar:1.73:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.7:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.2.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.2.3:compile
[INFO] |  +- commons-io:commons-io:jar:1.4:compile
[INFO] |  \- com.infradna.tool:bridge-method-annotation:jar:1.14:compile
[INFO] |     \- org.jenkins-ci:annotation-indexer:jar:1.4:compile
[INFO] +- com.squareup.okhttp:okhttp-urlconnection:jar:2.0.0:compile
[INFO] |  \- com.squareup.okhttp:okhttp:jar:2.0.0:compile
[INFO] |     \- com.squareup.okio:okio:jar:1.0.0:compile
[INFO] \- org.eclipse.jetty.toolchain:jetty-test-helper:jar:3.1:test
[INFO]    +- junit:junit:jar:4.12:test
[INFO]    |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    \- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.263 s
[INFO] Finished at: 2016-12-08T12:13:00+11:00
[INFO] Final Memory: 16M/225M
[INFO] ------------------------------------------------------------------------
```
and I can see that jenkins dep in maven: http://repo2.maven.org/maven2/org/jenkins-ci/annotation-indexer/1.4/

**Comment by olamy** [comment]
@gregw look http://repo2.maven.org/maven2/org/jenkins-ci/annotation-indexer/1.4/annotation-indexer-1.4.pom
The parent is 
````
<parent>
<groupId>org.jenkins-ci</groupId>
<artifactId>jenkins</artifactId>
<version>1.26</version>
</parent>
```
That's the issue.

**Comment by gregw** [comment]
Oh oops didn't look one more step.   So I have that in my local mvn repo, but I have no idea how it got there - if not from maven central.... surely it would not have been deleted from there?

@jmcc0nn3ll can you have a look at this?

@johngmyers try just removing that plugin, I don't think it is actually needed for the build.     

I was about to ask how our CIs are building, but now I notice they are suffering from a OSGi failure - which I will look at....

**Comment by joakime** [comment]
Not an issue.

And follows the `central.maven.org` rules as outlined by `oss.sonatype.org` sync to maven central.

There is an extra repository declared in the main/parent dependency at ...

[org.kohsuke:github-api:1.73](http://search.maven.org/#artifactdetails%7Corg.kohsuke%7Cgithub-api%7C1.73%7Cjar)

which says ...

```xml
  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>http://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>
```

You can find that artifact at ...

http://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.26/jenkins-1.26.pom
