### ISSUE TITLE
Why are spaces in query parameters encoded as a plus character?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#11525]
**Jetty Version**
12.0.7

**Jetty Environment**
core

**Java Version**
JDK 21

**Question**
https://github.com/jetty/jetty.project/issues/3565 and https://github.com/jetty/jetty.project/issues/7713 discuss the usage of `%20` versus `+` to encode spaces in URIs.

I noticed that in Jetty 12, `HttpClient.newRequest().param(key, value)` encodes spaces using `URLEncoder.encode()` which is specific to `application/ x-www-form-urlencode` which uses `+`.

But per https://stackoverflow.com/a/29948396/14731 and other sources I've seen, we are supposed to use `%20` to encode spaces in URIs, and `+` to encode `application/ x-www-form-urlencode` form data. `Request.param()` is meant for query parameters, not form data, so it should be using `%20` as well.

Thoughts?

**Comment by cowwoc** [comment]
Reading further, it sounds like `%20` is required for URI paths, but for the query parameters both `+` and `%20` are acceptable. Was this your conclusion as well?

**Comment by joakime** [comment]
Correct, the encoding of query is slightly different than encoding of say path in a URL/URI.

The html spec is where the concept of `+` comes from.

See:

* https://html.spec.whatwg.org/multipage/urls-and-fetching.html#resolving-urls
* (which links to) https://url.spec.whatwg.org/#urlencoded-parsing

It is still present there and is in super widespread usage still.
Even the standard java `java.net.URLDecoder` still supports it.

Eg:

```
jshell> URLDecoder.decode("?a=foo+bar")
$1 ==> "?a=foo bar"
```
