### ISSUE TITLE
Jetty 12.0.6 upgrade issue: Resource.getInputStream() is not able to find

### ISSUE THREAD

**Issue by ilapavuluri** [eclipse/jetty.project#11531]
**Jetty version(s)**

Jetty 12.0.6
**Jetty Environment**

Jetty 12.0.6
**Java version/vendor** `(use: java -version)`
Java 17
**OS type/version**
Windows
**Description**

I am upgrading my Jetty application from 9.x to 12.x and for the below code snippet:
res = org.eclipse.jetty.util.resource.Resource
		            .newResource(securityProperties.get(TransportConstants.SSL_KEYSTORE));
			keystoreInputStream = res.getInputStream();

Getting below error:
cannot find symbol
[ERROR]   symbol:   method newResource(java.lang.String)

cannot find symbol
[ERROR]   symbol:   method getInputStream()
 
What is the alternative to this? and how to resolve? I got struck due to this, appreciate any help on this
**How to reproduce?**

res = org.eclipse.jetty.util.resource.Resource
		            .newResource(securityProperties.get(TransportConstants.SSL_KEYSTORE));
			keystoreInputStream = res.getInputStream();

Getting below error:
cannot find symbol
[ERROR]   symbol:   method newResource(java.lang.String)

cannot find symbol
[ERROR]   symbol:   method getInputStream()

**Comment by joakime** [comment]
Change ...

``` java
res = org.eclipse.jetty.util.resource.Resource
.newResource(securityProperties.get(TransportConstants.SSL_KEYSTORE));
keystoreInputStream = res.getInputStream();
```

to 

``` java
ResourceFactory resourceFactory = ResourceFactory.of(server); // or of(WebAppContext), basically what the scope of that resource is.
Resource res = resourceFactory.newResource(securityProperties.get(TransportConstants.SSL_KEYSTORE));
InputStream in = res.newInputStream();
```

**Comment by ilapavuluri** [comment]
@joakime Thank you so much for the quick response, in my case the below code is part of a static API which hits during the initialization of that java class, hence I am not sure what to keep the of(....), hence I tried below, please correct me if I am wrong

``` java
private static Scheme createDefaultHTTPSScheme() throws C2OException {
		InputStream keystoreInputStream = null;
		org.eclipse.jetty.util.resource.Resource res = null;
		try(ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {

			

			// Create TrustManager
			TrustManager tm = new CertificateTrustManager();
			SSLContext sslcontext = SSLContext.getInstance(sslProtocol);

			// Get security properties
			ConcurrentHashMap<String, String> securityProperties = TransportUtil.getSecurityProperties();
			
			
			res =resourceFactory
					.newResource(securityProperties.get(TransportConstants.SSL_KEYSTORE));
			keystoreInputStream = res.newInputStream();
			KeyStore keyStore = KeyStore.getInstance(securityProperties.get(TransportConstants.SSL_KEYSTORE_TYPE));
			keyStore.load(keystoreInputStream, securityProperties.get(TransportConstants.SSL_PASSWORD) == null ? null
					: securityProperties.get(TransportConstants.SSL_PASSWORD).toCharArray());

			KeyManagerFactory keyManagerFactory = KeyManagerFactory
					.getInstance(securityProperties.get(TransportConstants.SSL_KEYMANAGER_ALGORITH));

			keyManagerFactory.init(keyStore, securityProperties.get(TransportConstants.SSL_KEY_PASSWORD) == null ? null
					: securityProperties.get(TransportConstants.SSL_KEY_PASSWORD).toCharArray());
			KeyManager[] keyManagers = null;
			keyManagers = keyManagerFactory.getKeyManagers();

			sslcontext.init(keyManagers, new TrustManager[] { tm }, new SecureRandom());

			SSLSocketFactory sslf = new SSLSocketFactory(sslcontext, SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

			return new Scheme("https", 443, sslf);

		}  catch (Exception ex) {
			logger.error("Exception creating https scheme ", ex);
			throw new C2OException("Exception creating https scheme " + ex.getLocalizedMessage());
		} finally {
			if (keystoreInputStream != null) {
				try {
					keystoreInputStream.close();
				} catch (Exception ignore) {
					// ignore
				}
			}
			if (res != null) {
			
			}
		}

	}
```

**Comment by joakime** [comment]
The Resource's are tracked via a ResourceFactory.
Each ResourceFactory instance has a scope / lifecycle that those resources have to exist for.

Eg: if you used `ResourceFactory.of(webappContext)` and then you did `webappContext.stop()` then the resources for that webappContext get released.

In your example code you have a short lived ResourceFactory, hence short lived Resource instances.

``` java
try(ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {
   // resources created here will be closed when the try-with-resources block completes.
}
```

If multiple ResourceFactory instances track the same resource on disk, then there is reference counting in play and only when the last reference is released will the Resource be freed.

So I would suggest either passing in the ResourceFactory on the constructor, or having this method not be static and using a class field ResourceFactory that is already initialized against some kind of Jetty LifeCycle (like the `Server` class, or a `Handler`, or `ServletContextHandler`, or `WebAppContext`, etc...)

**Comment by ilapavuluri** [comment]
@joakime my above API is a kind of util function which builds a http conn Scheme by building the resource, keyStore, sslContext & SSLSocketFactory and return it back, not seeing any Jetty LifeCycle related container in this class, sorry if I am confusing
Really appreciate your help.

Thanks
Ashokk.

**Comment by ilapavuluri** [comment]
@joakime appreciate your inputs on the above

**Comment by joakime** [comment]
Generally, this is safe...

``` java
try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {
    Resource res = resourceFactory.newResource(...);
    try (InputStream input = res.newInputStream()) {
        foobar.load(input);
    }
} catch (Exception e) {
    // do something with the exception
}
```

But this isn't safe, as you hand off the Resource and then release it when the try-with-resources finishes

``` java
try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {
    Resource res = resourceFactory.newResource(...);
    foobar.setBaseResource(res);
} catch (Exception e) {
    // do something with the exception
}
```

**Comment by ilapavuluri** [comment]
@joakime, I re-designed my code like below based on your inputs, please let me know whether the below is acceptable 


private static Scheme createDefaultHTTPSScheme()  {
		//InputStream keystoreInputStream = null;
		org.eclipse.jetty.util.resource.Resource res = null;
		try(ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {

			

			// Create TrustManager
			TrustManager tm = new CertificateTrustManager();
			SSLContext sslcontext = SSLContext.getInstance(sslProtocol);

			// Get security properties
			ConcurrentHashMap<String, String> securityProperties = TransportUtil.getSecurityProperties();
			
			
			res =resourceFactory
					.newResource(securityProperties.get(TransportConstants.SSL_KEYSTORE));

			**try(InputStream keystoreInputStream = res.newInputStream();){**
				KeyStore keyStore = KeyStore.getInstance(securityProperties.get(TransportConstants.SSL_KEYSTORE_TYPE));
				keyStore.load(keystoreInputStream, securityProperties.get(TransportConstants.SSL_PASSWORD) == null ? null
						: securityProperties.get(TransportConstants.SSL_PASSWORD).toCharArray());

				KeyManagerFactory keyManagerFactory = KeyManagerFactory
						.getInstance(securityProperties.get(TransportConstants.SSL_KEYMANAGER_ALGORITH));

				keyManagerFactory.init(keyStore, securityProperties.get(TransportConstants.SSL_KEY_PASSWORD) == null ? null
						: securityProperties.get(TransportConstants.SSL_KEY_PASSWORD).toCharArray());
				KeyManager[] keyManagers = null;
				keyManagers = keyManagerFactory.getKeyManagers();

				sslcontext.init(keyManagers, new TrustManager[] { tm }, new SecureRandom());

				SSLSocketFactory sslf = new SSLSocketFactory(sslcontext, SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

				return new Scheme("https", 443, sslf);
			}


		}  catch (Exception ex) {
			logger.error("Exception creating https scheme ", ex);
			throw new C2OException("Exception creating https scheme " + ex.getLocalizedMessage());
		}

	}

**Comment by joakime** [comment]
The brief snippet looks ok in standlone.
Without knowing more about your code, i cannot say how it will react.
Go test it. try it out.

**Comment by ilapavuluri** [comment]
sure @joakime, thank you so much for your help.
