### ISSUE TITLE
jetty-io:9.4.48.v20220622 : while running with mvn test , getting Class not Available

### ISSUE THREAD

**Issue by shivsrivastava** [eclipse/jetty.project#11545]
**Jetty version(s)**
jetty-io:9.4.48.v20220622

**Jetty Environment**

**Java version/vendor** `(use: java -version)`
tried with JDK 8 and above

**OS type/version**
Windows 10 and Linux

**Description**
jetty-io:9.4.48.v20220622 : while running with mvn test , getting Class not Available

**How to reproduce?**

We are trying to build source code with test cases , here are the details.

Java version - 8 and above 
Maven - 3.3.1 and above 

But we are getting this exception. Also attached log.

Please help me to understand on 
[build-jetty-io-9.4.48.v20220622-2024-02-27-10-56-35-139-6266227635 (1).txt](https://github.com/jetty/jetty.project/files/14695554/build-jetty-io-9.4.48.v20220622-2024-02-27-10-56-35-139-6266227635.1.txt)
**which jdk version, Maven version and test command it will work.**

_"[ERROR] Errors:
[27 11:08:49.924] | [ERROR]   URIUtilTest.uriLastSegmentSource:679 » NoSuchFile /tmp/pkgs_raw/jetty-io%20/9.4.48.v20220622/jetty-util/src/test/resources/test-base-resource.jar
[27 11:08:49.924] | [ERROR]   PathResourceTest.testNonDefaultFileSystemGetFile:104 » NoSuchFile /tmp/pkgs_raw/jetty-io%20/9.4.48.v20220622/jetty-util/src/test/resources/example.jar
[27 11:08:49.924] | [ERROR]   PathResourceTest.testNonDefaultFileSystemGetInputStream:56 » NoSuchFile /tmp/pkgs_raw/jetty-io%20/9.4.48.v20220622/jetty-util/src/test/resources/example.jar
[27 11:08:49.924] | [ERROR]   PathResourceTest.testNonDefaultFileSystemGetReadableByteChannel:80 » NoSuchFile /tmp/pkgs_raw/jetty-io%20/9.4.48.v20220622/jetty-util/src/test/resources/example.jar
[27 11:08:49.924] | [ERROR]   PathResourceTest.testNonDefaultFileSystemWriteTo:125 » NoSuchFile /tmp/pkgs_raw/jetty-io%20/9.4.48.v20220622/jetty-util/src/test/resources/example.jar
[27 11:08:49.924] | [INFO]"_

**Comment by joakime** [comment]
Jetty 9.x is at End of Community Support.

See:

* #7958 

To build Jetty 9, you require OpenJDK 8 (MUST be OpenJDK based, eg: IBM based JVMs do not work.) and Maven 3.9.6
Note: Java 8 based builds will not build + test everything in Jetty.

**Comment by joakime** [comment]
Oh, and you cannot build Jetty 9 with a OpenJDK versions newer than OpenJDK 11. (so don't attempt to use OpenJDK 17 or OpenJDK 21, it wont work.  If you want to use OpenJDK 17 or newer, use Jetty 12)

**Comment by shivsrivastava** [comment]
I have taken github code and trying to build using jdk 8 . Requirement is, it should also include test cases while building. I got stuck on this issue.

**Comment by gregw** [comment]
@shivsrivastava as stated above, jetty-9.4 is end-of-community support. 
You can see [here](https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x/2647/pipeline) that jetty-9.4 can be compiled and is passing tests.  The configuration for that jenkins instance is [here](https://github.com/jetty/jetty.project/blob/jetty-9.4.x/Jenkinsfile) so you should be able to discover the information you need.

For any further assistance on jetty-9.4, please contact sales@webtide.com to enquire about commercial support.

**Comment by shivsrivastava** [comment]
I have tried with OpenJDK 8 and Maven 3.9.6 . UT status is getting failed still. Please suggest how to build with UT

**Comment by joakime** [comment]
@shivsrivastava as stated above, jetty-9.4 is end-of-community support. 
You can see [here](https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x/2647/pipeline) that jetty-9.4 can be compiled and is passing tests.  The configuration for that jenkins instance is [here](https://github.com/jetty/jetty.project/blob/jetty-9.4.x/Jenkinsfile) so you should be able to discover the information you need.

For any further assistance on jetty-9.4, please contact sales@webtide.com to enquire about commercial support.

**Comment by shivsrivastava** [comment]
> @shivsrivastava as stated above, jetty-9.4 is end-of-community support. You can see [here](https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x/2647/pipeline) that jetty-9.4 can be compiled and is passing tests. The configuration for that jenkins instance is [here](https://github.com/jetty/jetty.project/blob/jetty-9.4.x/Jenkinsfile) so you should be able to discover the information you need.
> 
> For any further assistance on jetty-9.4, please contact [sales@webtide.com](mailto:sales@webtide.com) to enquire about commercial support.

sure will check and confirm.

**Comment by shivsrivastava** [comment]
Tried with possible JDK version 8 and Maven , but got failed.

**Comment by joakime** [comment]
@shivsrivastava as stated above, jetty-9.4 is end-of-community support. 
You can see [here](https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x/2647/pipeline) that jetty-9.4 can be compiled and is passing tests.  The configuration for that jenkins instance is [here](https://github.com/jetty/jetty.project/blob/jetty-9.4.x/Jenkinsfile) so you should be able to discover the information you need.

For any further assistance on jetty-9.4, please contact sales@webtide.com to enquire about commercial support.

**Comment by devidandupati** [comment]
I have tried with OpenJDK 17,11,8 and Maven 3.9.6 &3.9.4 . UT status is failing still.

**Comment by meetankit24** [comment]
At last i also got UT failure with OpenJDK18 and Maven 3.9.6

**Comment by sourabhmagdum45** [comment]
I have tried with different JDK version with Maven 3.9.6 but still UT status Failing

**Comment by shivsrivastava** [comment]
Please update on it.

**Comment by joakime** [comment]
@meetankit24 @sourabhmagdum45 @shivsrivastava Jetty 9 is at End of Community Support.

You should not expect support here for that version of Jetty.
