### ISSUE TITLE
Flaky test `NetworkTrafficListenerTest.testTrafficWithRequestContentWithResponseRedirectOnPersistentConnection`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#11555]
**Jetty version(s)**
12.0.7

**Description**
`NetworkTrafficListenerTest.testTrafficWithRequestContentWithResponseRedirectOnPersistentConnection` sometimes fails with:

```
expected: <GET / HTTP/1.1
Accept-Encoding: gzip
User-Agent: Jetty/12.0.8-SNAPSHOT
Host: localhost:41841
Content-Type: application/x-www-form-urlencoded
Content-Length: 7
a=1&b=2> but was: <GET / HTTP/1.1
Accept-Encoding: gzip
User-Agent: Jetty/12.0.8-SNAPSHOT
Host: localhost:41841
Content-Type: application/x-www-form-urlencoded
Content-Length: 7
>
```

See: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-11549/1/tests

**Comment by sbordet** [comment]
Fixed by f633ccc35ec211df3228390342915a312da4dd62.
