### ISSUE TITLE
Implement Web3 OAuth/Sign-In Functionality

### ISSUE THREAD

**Issue by 0xmulch** [eclipse/jetty.project#11560]
### **Overview**

I would like to suggest Jetty should integrate Web3 OAuth/Sign-In to let users log in with their blockchain wallets, like MetaMask or WalletConnect. 

This move taps into the secure and user-friendly aspects of blockchain, offering a modern twist to logging in without traditional usernames and passwords. Impact to legacy code is minimal, so this would be a means of radically modernizing Jetty in the eyes of the public, without a lot of technical overhead for maintainers.

Following implementation, users would be able to authenticate by simply connecting their wallet! It’s like “Sign in with Google" but on-chain and permission-less. Moreover, numerous libraries already provide this functionality.

Long-term, Jetty could have significant potential within the Web3 space, particularly for enhancing cross-chain communications and supporting decentralized physical infrastructure. Jetty could play a crucial role in the evolving Web3 ecosystem. If explored, this direction could greatly amplify Jetty's impact on blockchain interoperability and the broader adoption of decentralized and open source systems.

**Enhancement-Specific Description**

- User Perks: Instant account setup with a wallet address and one-click logins. No forms or PII, just a quick signature.
- Compatibility: Works natively with major EVM wallets, keeping an eye on a smooth integration with our current system.
- Benefits: This boosts security, protects user privacy by obfuscating PII, and puts Jetty ahead in the Web3 space. 

Looking forward to making Jetty a pioneer in Web3. Open to feedback/questions. 

CC: @jmcc0nn3ll

**Comment by gregw** [comment]
@lachlan-roberts is this something you'd like to look into?

**Comment by 0xmulch** [comment]
@lachlan-roberts If you run into any snags, don't hesitate to reach out and I can try to help you out.

**Comment by lachlan-roberts** [comment]
@0xmulch I have opened PR #11883 if you wish to review.

It is still a draft PR as there is still work to do including the documentation, but it is working and would be good to receive some early reviews.

**Comment by lachlan-roberts** [comment]
Completed in the `12.1.x` branch.
