### ISSUE TITLE
What causes Broken pipe?

### ISSUE THREAD

**Issue by urumax** [eclipse/jetty.project#11569]
**Jetty Version**
Jetty9.4

**Java Version**
$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

**Question**
When the websocket is disconnected, onError is rarely called and "Broken pipe" is displayed in Reason.
OnError has not been called on the connection destination. No error log is output either.
What causes broken pipe instead of timeouts?
Does it occur when client and server perform disconnect operations at the same time?
Is it okay to ignore it?

Due to system limitations, we are using version 9.
If this problem does not occur even after upgrading, I would like to consider upgrading.

**Comment by lachlan-roberts** [comment]
Note: Jetty 9, Jetty 10, and Jetty 11 are all now at End of Community Support.
So you should strongly consider upgrading to Jetty 12.

See:

* https://github.com/jetty/jetty.project/issues/7958
* https://github.com/jetty/jetty.project/issues/10485

**Comment by lachlan-roberts** [comment]
But just means that the connection was closed when you were trying to write.

The WebSocket implementation has been completely re-written for the newer versions of Jetty, I would expect onError to be called in the newer versions.

**Comment by urumax** [comment]
I have resolved but I forgot to close the ticket.

I would like to take this opportunity to thank everyone who provided advice.

I will now close this ticket. Thank you for your continued support.
