### ISSUE TITLE
Deploy behaves differently when both WAR and XML exist in ${jetty.base}/webapps/ and you update the XML vs updating the WAR.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#11572]
**Jetty version(s)**
12.0.7

**Jetty Environment**
ee10 (but might exist for other environments too)

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
If you have a deployable pair (both WAR and XML) in `${jetty.base}/webapps/` the hot-deploy will behave differently if you simply touch the XML vs touch the WAR.
In some cases, if you just touch the WAR, the XML changes are not applied (eg: TempDirectory setting)

**How to reproduce?**

Setup the jetty.base

``` shell
$ mkdir newbase
$ cd newbase
$ java -jar $JETTY_HOME/start.jar --add-modules=http,ee10-deploy,ee10-webapp
$ echo "jetty.deploy.scanInterval=1" >> start.d/ee10-deploy.ini
$ mkdir work
$ cp $PROJ/demo.war webapps/
$ cp $PROJ/demo.xml webapps/
$ ls webapps
demo.war   demo.xml
$ cat webapps/demo.xml
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.ee10.webapp.WebAppContext">
   <Set name="contextPath">/demo</Set>
   <Set name="war"><Property name="jetty.webapps"/>/demo.war</Set>
   <Set name="tempDirectory"><Property name="jetty.base"/>/work/demo</Set>
   <Set name="tempDirectoryPersistent">false</Set>
</Configure>
```

Run the server.
Wait for it to start.

Touch the WAR (but not the XML)
``` shell
touch ${jetty.base}/webapps/demo.war
```

Notice that the XML configuration for TempDirectory was not applied to the WebAppContext on reload of the WAR.

**Comment by janbartel** [comment]
See PR #11576

**Comment by janbartel** [comment]
See #11576
