### ISSUE TITLE
Get :authority field when using Websockets over http/2 with the jakarta websocket-api 

### ISSUE THREAD

**Issue by meszarv** [eclipse/jetty.project#11589]
**Jetty Version** 12.0.7

**Jetty Environment** jetty-ee10

**Java Version** 17

**Question**
I am using websockets over http/2 with the jakarta websocket-api (JSR356).

Can you advise how can I access the :authority pseudo field inside the 
javax.websocket.server.ServerEndpointConfig.Configurator#modifyHandshake(ServerEndpointConfig sec, HandshakeRequest request, HandshakeResponse response) method? 

when using http/1.1 I could get the "Host" header by calling HandshakeRequest#getHeaders() in the modifyHandshake method, but with http/2 the Host is no longer present.

With plain servlet api, the authority can be obtained by calling ServletRequest.getServerName() and ServletRequest.getServerPort(), but the HandshakeRequest lacks these methods

Thanks

**Comment by sbordet** [comment]
You should add the `HostHeaderCustomizer` to the `HttpConfiguration`.

`HostHeaderCustomizer` would create the `Host` header if missing, with the value from the `:authority` pseudo-header, so your application would not change whether it's HTTP/1.1 or HTTP/2: it would look up the `Host` header in both cases.

We should document this in more details.

Also, the Jetty module should have this added by default.

**Comment by meszarv** [comment]
Thank you Simone, yes, when I configure HostHeaderCustomizer then it works as if I was using http/1.1

But I was rather interested whether you are aware of any server agnostic way of implementing this- my application can only use the jakarta-websocket-api, as it can be deployed to any servlet container.  I could not find any mention how this should be handled in the JSR356 spec. 

Also adding the HostHeaderCustomizer will affect all requests not only the websocket related ones.

**Comment by joakime** [comment]
> I could not find any mention how this should be handled in the JSR356 spec.

File an issue at https://github.com/jakartaee/websocket/ asking how it can be done in a Servlet neutral way.

**Comment by joakime** [comment]
@meszarv as you have discovered, the `Host` header is not a stable source of host information.
Even in HTTP/1.1, if your request has forwarding headers, the `Host` header is now invalid (and in HTTP/2 the `:authority` pseudo-header is now invalid), as the forwarding headers are likely overriding it.
The request URI/URL authority section is the only source of the truth on the request.

**Comment by sbordet** [comment]
@meszarv 

> But I was rather interested whether you are aware of any server agnostic way of implementing this

Unfortunately this is not possible; as @joakime suggested this is a lack in the specification, and there is not much we can do.
Synthesizing by default the `Host` header if it is missing would penalize all those applications that don't look at that header.

> Also adding the HostHeaderCustomizer will affect all requests not only the websocket related ones.

It would be fairly easy to extend `HostHeaderCustomizer` and apply the customizer logic only if it is a WebSocket request.

The request customizers have been documented in #11682, so I am closing this issue.
