### ISSUE TITLE
UTF-8 NFC/NFD tests fail on Macos

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#11594]
**Jetty version(s)**
12.0.x

**Java version/vendor** `(use: java -version)`
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)

**OS type/version**
Macos Monterey 12.7.4

**Description**
`ResourceHandlerTest.testGetUtf8NfcFile()` and `ResourceHandlerTest.testGetUtf8NfdFile()` both fail on Macos.

See:
 - https://jenkins.webtide.net/job/nightlies/job/jetty-12.0.x-mac-nightly/11/testReport/junit/org.eclipse.jetty.server.handler/ResourceHandlerTest/testGetUtf8NfcFile/
 - https://jenkins.webtide.net/job/nightlies/job/jetty-12.0.x-mac-nightly/11/testReport/junit/org.eclipse.jetty.server.handler/ResourceHandlerTest/testGetUtf8NfdFile/

**Comment by joakime** [comment]
Did they work on Jetty 12.0.0? what about Jetty 10.0.20?
I've noticed recently that these are failing on 12.0.8-SNAPSHOT on Windows as well.

**Comment by lorban** [comment]
Not sure about 12.0.0 but they do pass on 11.0.x: https://jenkins.webtide.net/job/nightlies/job/jetty-11.0.x-mac-nightly/480/

**Comment by lorban** [comment]
The tests do not fail on 11 because they add a `AllowedResourceAliasChecker`, exactly like their 12.0.x counterparts.
