### ISSUE TITLE
HTTPS Connector doc does not accurately reflect Jetty 9.3 default value for excludedCipherSuites

### ISSUE THREAD

**Issue by rondagostino** [eclipse/jetty.project#1160]
As per #860 only TLS 1.2 is supported out-of-the-box with Dropwizard 1.0+ due to a code change in Jetty 9.3 (see https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb) that sets a very restrictive `excludedCipherSuites` value, but the HTTPS Connector documentation shows the default value for `excludedCipherSuites` as being `(none)`.  The documentation should accurately reflect the default, which is `^.*_RSA_.*_(MD5|SHA|SHA1)$`.  (I guess regular expressions are supported, which the doc should also indicate.)

**Comment by rondagostino** [comment]
Oops, this is a Dropwizard issue, not a Jetty issue. I will close this issue and open a Dropwizard issue instead.

**Comment by joakime** [comment]
If anyone arrives in here via a Google Search, please consider using the *dump* facility in Jetty to get the list of included/excluded CIpherSuites and Protocols in your configuration/environment.

See Issue #1108
