### ISSUE TITLE
HttpClient and WebSocketClient should not remove all cookies on stop

### ISSUE THREAD

**Issue by hoomanv** [eclipse/jetty.project#1161]
On jetty 9.2.17

Both HttpClient and WebSocketClient attempt to clear the CookieStore on doStop().
WHY ?

I have written a PersistentCookieStore hoping that cookies would survive an app restart, but surprisingly jetty is not letting that happen. I think this was just a poor decision by jetty. Don't you ?

**Comment by hoomanv** [comment]
Cookies with a specified maxAge can survive a restart as long as not expired.

**Comment by sbordet** [comment]
Typically the lifecycle of a `HttpClient` instance is the same of the JVM.

By default, cookies are stored in memory, so when the JVM shuts down, the cookies will be gone anyway.

The cookie store is pluggable, so you can write your own cookie store and save the cookies to a file, RDBMS, NoSQL, etc. and restore them upon restart.

**Comment by joakime** [comment]
@sbordet i think @hoomanv is saying that this line, shouldn't be called in doStop()

```java
    cookieStore.removeAll();
```

See: https://github.com/eclipse/jetty.project/blob/jetty-9.3.14.v20161028/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java#L243

**Comment by hoomanv** [comment]
> The cookie store is pluggable, so you can write your own cookie store and save the cookies to a file, RDBMS, NoSQL, etc. and restore them upon restart.

That is exactly what I've done, but since HttpClient (And WebSocketClient) call `cookieStore.removeAll();` on doStop(), anything that was persisted will be removed as a consequence.

**Comment by joakime** [comment]
Closing as fixed
