### ISSUE TITLE
Jetty 12.0.6 upgrade issue: org.eclipse.jetty.client request.header("KEY", "VALUE") not available

### ISSUE THREAD

**Issue by ilapavuluri** [eclipse/jetty.project#11628]
**Jetty Version**
Jetty 12.0.6
**Jetty Environment**
Jetty 12.0.6, ee8 & ee10

**Java Version**
Java 17
**Question**
I am upgrading my Jetty application from 9.x to 12.x and for the below code snippet:

``` java
if(...){
request.header("KEY1", "VALUE1"); //request is org.eclipse.jetty.client.Request
}
else {
request.header("KEY2", "VALUE2"); //request is org.eclipse.jetty.client.Request
}
```

``` java
while(...){
if(..){
request.header("KEY3", "VALUE3"); 
} else {
request.header("KEY4", "VALUE4"); 
}
}
```

I am getting below compilation error:
_cannot find symbol
[ERROR]   symbol:   method header(String,String)_

and I found we need to use request.headers(HEADERS)  where HEADERS is of type Consumer<HttpFields.Mutable>

But in multiple places I have request.header conditionally (as mentioned above)

Hence I tried below:

``` java
Map<String, String> headersMap = new HashMap<>();
if(...){
headersMap.put("KEY1", "VALUE1"); //request is org.eclipse.jetty.client.Request
}
else {
headersMap.put("KEY2", "VALUE2"); //request is org.eclipse.jetty.client.Request
}
```

``` java
while(...){

if(..){
headersMap.put("KEY3", "VALUE3"); 
} else {
headersMap.put("KEY4", "VALUE4"); 
}
}
```

//and finally

``` java
final  Consumer<HttpFields.Mutable> headers = httpFields -> {
			headersMap.forEach((headerName, headerValue) -> {
				httpFields.add(headerName, headerValue);
			});
		};
		request.headers(headers);
```

Is this right approach? please correct me. Really appreciate your help

**Comment by joakime** [comment]
You can use something like ...

``` java
    request.headers(headers -> headers
        .put(HttpHeader.ALLOW, "*/*") // using spec name
        .put("Accept-Language", "en-US,en;q=0.9,pt;q=0.8") // using arbitrary name
        .put("X-AppHeader", "Something Interesting") // using application extension name
        .put(HttpHeader.CONNECTION, "Close") // using spec name
    ); 
```

**Comment by ilapavuluri** [comment]
@joakime thank you for the quick response.

In my case in multiple places based on conditions I need to insert headers. If I do something like below,
Will it override the already added headers ? please share your thoughts 

```java
while(...){
  if(..){
    request.headers(headers -> headers
        .put(KEY1, "*/*"));
  } else {
    request.headers(headers -> headers
        .put(KEY2, "close"));
  }
  request.headers(headers -> headers
        .put(KEY3, "Something Interesting"));
}
```

at the end of the above code I want either KEY1,KEY3 or KEY2,KEY3 should be added to the headers.

**Comment by ilapavuluri** [comment]
@joakime any inputs on the above?

Thanks
Ashok.

**Comment by sbordet** [comment]
@ilapavuluri What inputs do you need? 

You're asking a basic programming question, and you can actually try the code yourself and see what you end up with.

Why would you put the modifications of the header in a while loop?
You may have your reasons to do so, but then it's your code, your logic, and Jetty is out of the picture.

The lambda calls `headers.put()` have the same `put` semantic as that of a `Map`, just read the javadocs.

**Comment by ilapavuluri** [comment]
@sbordet @joakime I am really sorry for the confusion, I totally agree this is not related to Jetty and thank you so much for the help.
