### ISSUE TITLE
Jetty12.0.8 cannot run my war successfully, but jetty-9.4.48.v20220622 can.

### ISSUE THREAD

**Issue by Helly987** [eclipse/jetty.project#11633]
With below error:
![image](https://github.com/jetty/jetty.project/assets/150114018/95368cf6-e531-4409-94ee-788f25ec0d0a)

add modules:
java -jar $JETTY_HOME/start.jar --add-modules=http,ee10-deploy,ee10-webapp
start command: java -jar $JETTY_HOME/start.jar

demo.xml:
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.ee10.webapp.WebAppContext">
   <Set name="contextPath">/demo</Set>
   <Set name="war"><Property name="jetty.webapps"/>/demo.war</Set>
   <Set name="tempDirectory"><Property name="jetty_base"/>/work/demo</Set>
   <Set name="tempDirectoryPersistent">false</Set>
</Configure>

**Comment by Helly987** [comment]
demo.xml:
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.ee10.webapp.WebAppContext">
   <Set name="contextPath">/demo</Set>
   <Set name="war"><Property name="jetty.webapps"/>/demo.war</Set>
   <Set name="tempDirectory"><Property name="jetty_base"/>/work/demo</Set>
   <Set name="tempDirectoryPersistent">false</Set>
</Configure>

**Comment by Helly987** [comment]
For the version Jetty9.x and Jetty12.x, can I use the same war?  Can th emaven  configuration be the same for the two different jetty version?

I found that Jetty 12.x was not compatible with jetty 9.x, it has a huge change.

**Comment by janbartel** [comment]
Jetty 12 EE10 corresponds to the Servlet 6 specification, and all classes that were `javax.servlet` changed to `jakarta.servlet` so you will need to modify your web app accordingly. Or alternatively use the EE8 environment instead.

**Comment by joakime** [comment]
Change to use `ee8` instead ...

```
java -jar $JETTY_HOME/start.jar --add-modules=http,ee8-deploy,ee8-webapp
```

and try deploying your webapp again

**Comment by Helly987** [comment]
> Change to use `ee8` instead ...
> java -jar $JETTY_HOME/start.jar --add-modules=http,ee8-deploy,ee8-webapp
> and try deploying your webapp again

**Yes, for http mode, it works fine. Thanks a lot.**
But I still want to run in https mode:
java -jar $JETTY_HOME/start.jar --add-modules=ssl,https,ee8-deploy,ee8-webapp

You know that I need to write the keystore and password to the ssl.ini, the content is as below:
![image](https://github.com/jetty/jetty.project/assets/150114018/a7481e7a-022b-418c-829c-f8eee01d4e8b)

Unfortunately, when I run java -jar $JETTY_HOME/start.jar,  it seems work fine just with  "The system cannot find the drive specified." on the command line.
but I cannot access https://localhost:8443/ui
![image](https://github.com/jetty/jetty.project/assets/150114018/d03cf4b9-f1ff-47e5-bf7d-717e51899493)
Could you help me check this?

**Comment by Helly987** [comment]
@joakime   Please help check the https mode, I cannot run web application  with it.
I use the jetty12.0.6, I think it is almost the same as the jetty12.0.8.

**Comment by joakime** [comment]
SNI has rules you must follow ...

* It cannot be an IP literal (not IPv4 or IPv6)
* It cannot be a localhost, localdomain, or local reference (eg `localhost`, `foo.local`, etc)
* It must be a hostname that has at least 1 `.` (dot)
* The hostname cannot end with a `.` (dot)

The rules back in Java 8 were very lax, with each version of Java since the rules have been made to be more in line with the specs for SNI.

**Comment by joakime** [comment]
You must also use an HTTP Client that supports sending the SNI details in the TLS negotiation properly.
Many older HTTP Clients do not perform this step properly.

**Comment by Helly987** [comment]
I try the link use https://HOSTNAME/8443, it still has the same issue.
![image](https://github.com/jetty/jetty.project/assets/150114018/6b4ea0b7-b0cc-4979-b1da-f403440ca9fe)

**How can I use the https client?** 
I read the guilde, it supports the [Secure HTTP/1.1](https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-protocols-https)

**Comment by joakime** [comment]
Your host does not follow the SNI rules.
It fails point 3 on my comment - https://github.com/jetty/jetty.project/issues/11633#issuecomment-2049647861

Your host name must by fully qualified, not abbreviated, not just a relative name (like your example).  
It must be fully complete, all the way through to the top level domain segment.
These are the rules for SNI in both the spec for SNI, and also how new Java JVMs have it implemented.
Jetty has no control over these rules, as they are baked into Java itself.

**Comment by Helly987** [comment]
@joakime   Is there any solution to disable the SNI validation?  My computer is used as the server, no virtualhost.
But I tried to configure the ssl.ini with
 jetty.ssl.sniRequired=false
 jetty.ssl.sniHostCheck=true
or
jetty.ssl.sniRequired=true
 jetty.ssl.sniHostCheck=true , the result is the same.

**Comment by sbordet** [comment]
@Helly987 please read the documentation:
https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-protocols-ssl-sni

You can fully disable the SNI check with:

```
jetty.ssl.sniRequired=false
jetty.ssl.sniHostCheck=false
```

**Comment by Helly987** [comment]
If I change them to be false, the result is not as expected.
![image](https://github.com/jetty/jetty.project/assets/150114018/54799a14-3609-4657-b106-0d00d8036de0)

I refer to the jetty Operation guide, no clear guide about how to configure in https mode. still try to access https://localhost:8443/

**Comment by sbordet** [comment]
The image above shows that your TLS configuration is correct.

You just did not type any context path in your browser, or you have not deployed any web application.

What do you want to configure?

**Comment by Helly987** [comment]
No, I have configured the context path, but it is not working.
![image](https://github.com/jetty/jetty.project/assets/150114018/b718ea20-03bc-4e6c-9072-f4b0bdf689f5)

**Comment by sbordet** [comment]
@Helly987 we cannot help you if the only information you give is "it is not working".

Please at least report the DEBUG logs when you start Jetty.

Also read the documentation section here:
https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-deploy-jetty

Why do you call `<Set name="war">` twice?
Are you sure that you have a property called `jetty.webapps` properly defined?

**Comment by Helly987** [comment]
Sorry, I do not know how to write configure set in jetty.xml, my environment is **windows11**.
jetty.webapps is just referred from website.
How to deploy web application ui and two wars in jetty.xml in https mode?    
 jetty-12.0.6\jetty_base\webapps\test1.war,  jetty-12.0.6\jetty_base\webapps\test.war,  jetty-12.0.6\jetty_base\webapps\ui

**Comment by janbartel** [comment]
@Helly987 you need an xml file for each of the war files you want to deploy, and they should have the same name root as your war.  In it you can set whichever context paths that you want for your webapps. So make:

`qdb.xml`: 
```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://eclipse.dev/jetty/configure_10_0.dtd">

<Configure id="wac" class="org.eclipse.jetty.ee8.webapp.WebAppContext">
  <Set name="contextPath">/qdb</Set>
  <Set name="war"><Property name="jetty.webapps" />/qdb.war
  </Set>
```

`NXReportingIndexer.xml`:
```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://eclipse.dev/jetty/configure_10_0.dtd">

<Configure id="wac" class="org.eclipse.jetty.ee8.webapp.WebAppContext">
  <Set name="contextPath">/nxreportingindexer</Set>
  <Set name="war"><Property name="jetty.webapps" />/NXReportingIndexer.war
  </Set>
```

Then put the above xml files into your `${jetty.base}/webapps` directory, along with your `qdb.war` and `NXReportingIndexer.war` and the deployer will find and deploy them.

**Comment by Helly987** [comment]
@janbartel  ok, thank you. I will try it.

**Comment by janbartel** [comment]
Closing this issue as addressed.
