### ISSUE TITLE
Unresolved callbacks

### ISSUE THREAD

**Issue by mpfau** [eclipse/jetty.project#11647]
**Jetty version(s)**
12.0.8

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
21.0.2

**OS type/version**
linux

**Description**
We found that some callbacks get never resolved and implemented a callback registry to make sure that we find places where callbacks are not succeeded/failed.

Every callback passed from jetty to root handler is wrapped and registered. The callbacks get unregistered once the `succeeded` or `failed` function is called on the wrapped callback. Besides that, the wrapper is a delegate. Two hours after a callback was registered, we evict it from the registry and log the request URL.

The stack trace to the point where we wrap the callback is the following:
```
	at de.tutao.tutadb.rest.RootHandler.handle(RootHandler.java:391)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:549)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:805)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:619)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**How to reproduce?**
We see unresolved callbacks on a daily base in our prod environment but we are still unsure what is triggering them.

We noticed that while callbacks get resolved most of the time, when they don't get resolved they don't get resolved in batches.
<details>
  <summary>log</summary>

W 12:50:33.060 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.060 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.060 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.086 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.086 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.086 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.086 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.086 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.086 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.121 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.121 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.139 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.139 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.152 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.488 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.489 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.489 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.489 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.489 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.517 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.517 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.517 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.517 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.618 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.618 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.618 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.619 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.619 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.873 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.873 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.873 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.873 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.873 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.873 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.937 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.960 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
W 12:50:33.960 sys CallbackRegistry.java:34  unresolved callback for uri https://tuta.com/, isDone: false
</details>

**Comment by joakime** [comment]
This might overlap with #11072

**Comment by sbordet** [comment]
Closing this in favor of #11072.
