### ISSUE TITLE
Restore jetty-ee8-runner

### ISSUE THREAD

**Issue by haubi** [eclipse/jetty.project#11642]
**Jetty Version**

Jetty 12

**Jetty Environment**

Jetty 12.0.6 EE8, as available in Eclipse 2024-03 RCP

**Java Version**

Java 17

**Question**

I'm in the process of upgrading from Jetty 10 to Jetty 12 EE8, since neither EE9 nor EE10 are published via Eclipse 2024-03 release repositories yet.
We are using Jetty-Runner version 10.0.16 right now (directly as Maven artifact, not available via Eclipse repos), and my idea was to upgrade to Jetty-Runner version 12.0.6, the "EE8" variant in particular.
The idea to use Jetty EE8 Runner actually is backed by the list of built artifacts shown here:
https://eclipse.dev/jetty/documentation/contribution-guide/index.html#cg-build-artifacts

However, somehow I fail to find the Maven artifact that could resemble the Jetty EE8 Runner in version 12.

Is this a bug in not being published, or is there another Jetty Runner I should use instead, like to continue using Jetty Runner version 10, even if the application uses version 12 EE8?

Thanks a lot!

**Comment by janbartel** [comment]
@olamy  we appear to have a `jetty-ee9/jetty-ee9-runner` project, but not a `jetty-ee8/jetty-ee8-runner` project. Should we restore it?

**Comment by olamy** [comment]
@janbartel yup I will look at using same translation mechanism if we can. Just figured out there are some TODO test to restore as well

**Comment by olamy** [comment]
done via https://github.com/jetty/jetty.project/commit/ea8139e94a6918b6edb2a3a1e8e83af45f0057abhttps://github.com/jetty/jetty.project/commit/ea8139e94a6918b6edb2a3a1e8e83af45f0057ab
