### ISSUE TITLE
Does it possible bind JNDI resource from a war inner maven plugin?

### ISSUE THREAD

**Issue by kentyeh** [eclipse/jetty.project#11641]
**Jetty Version**
12.0.8

**Jetty Environment**
ee10

**Java Version**
JDK 22

**Question**
Does it possible bind JNDI resource from deployed war?

I wrote an example with multiple module maven project,
one startup withing maven jetty plugin and another with packaged war.

when I start with jndi project, It work properly.
[jettyJndi.zip](https://github.com/jetty/jetty.project/files/14926519/jettyJndi.zip)
```sehll
mvn clean package && mvn jetty:run --projects HelloJndi
```
[http://localhost:8080/HelloKitty/](http://localhost:8080/HelloKitty/) and
[http://localhost:8080/HelloJndi/hello/Jetty](http://localhost:8080/HelloJndi/hello/Jetty) work find.

But when I start with non-jndi project
```shell
mvn clean  package && mvn jetty:run --projects HelloKitty
```
A exception of ` Nothing to bind` occured.

So how could I do to make it possible bind jdni from a war?

**Comment by kentyeh** [comment]
I got the answer when I removed &lt;resource-ref&gt; from the web.xml of HelloJndi.,

All jobs work.

But I still do not know why.

**Comment by janbartel** [comment]
@kentyeh the `HelloKitty` `src/test/resources/web.xml` does not have a definition of a `<resource-ref>` for your database connector, unlike your `HelloJndi` project, which has the following in it's `web.xml`:

```xml
    <resource-ref>
        <description>JNDI DataSource</description>
        <res-ref-name>jdbc/${project.artifactId}</res-ref-name>
        <res-type>javax.sql.DataSource</res-type>
        <res-auth>Container</res-auth>
    </resource-ref>
```

**Comment by kentyeh** [comment]
@janbartel 
the `HelloKitty` is just a plain web  that does not necessarily need a database connection, 
even I put  a &lt;resource-ref&gt; into web.xml,
```xml
    <resource-ref>
        <description>JNDI DataSource</description>
        <res-ref-name>jdbc/HelloJndi</res-ref-name>
        <res-type>javax.sql.DataSource</res-type>
        <res-auth>Container</res-auth>
    </resource-ref>
```
 The same error occurred.

I noticed when I started with `HelloKitty`, jetty load `HelloJndi.war` first,
 then activate the JNDI resource . Maybe wrong activation orders make this error happen.

**Comment by janbartel** [comment]
There are 2 problems:

1. `HelloKitty` project defines that it runs the `HelloJndi.war,` but yet does not have a dependency on the build output of the `HelloJndi` project, so as far as maven is concerned it cannot order the builds of those 2 projects correctly.
2. As the `HelloKitty` project is running a war from another project, you shouldn't be using the `jetty:run` goal, you should be using the `jetty:run-war` goal. See https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#jetty-run-war-goal

**Comment by kentyeh** [comment]
@janbartel 
First, Maven project cannot depend on another war,
Next, HelloJndi is a third party war to provide API access,
That is why I must give it a JNDI connection to do the integration test.

**Comment by janbartel** [comment]
Your `HelloKitty` project starts a separate context to deploy the pre-built `HelloJndi` war with this configuration:

```xml
                    <contextHandlers>
                        <contextHandler implementation="org.eclipse.jetty.ee${ee.ver}.maven.plugin.MavenWebAppContext">
                            <war>${project.parent.basedir}/HelloJndi/target/HelloJndi.war</war>
                            <contextPath>/HelloJndi</contextPath>
                        </contextHandler>
                    </contextHandlers>
```

However, your `HelloJndi` war contains a `web.xml` that says:

```xml
    <resource-ref>
        <description>JNDI DataSource</description>
        <res-ref-name>jdbc/HelloJndi</res-ref-name>
        <res-type>javax.sql.DataSource</res-type>
        <res-auth>Container</res-auth>
    </resource-ref>
```

So you must provide it a jndi resource to satisfy that binding (the same way you do when you run the `HelloJndi` project by itself by using the `<jettyEnvXml>${project.build.testOutputDirectory}/jetty-env.xml</jettyEnvXml>` line in the jetty maven plugin configuration).

So your `HelloKitty` jetty maven plugin configuration should look like:

```xml
                    <contextHandlers>
                        <contextHandler implementation="org.eclipse.jetty.ee${ee.ver}.maven.plugin.MavenWebAppContext">
                            <war>${project.parent.basedir}/HelloJndi/target/HelloJndi.war</war>
                            <contextPath>/HelloJndi</contextPath>
                            <jettyEnvXml>${project.build.testOutputDirectory}/jetty-env.xml</jettyEnvXml>
                        </contextHandler>
                    </contextHandlers>
```

**Comment by kentyeh** [comment]
@janbartel 
Appreciate your help. It did work.

**Comment by kentyeh** [comment]
@janbartel 
[jettyJndi.zip](https://github.com/jetty/jetty.project/files/15293228/jettyJndi.zip)

I found another problem.

No matter I start from
```shell
mvn clean package && mvn jetty:run --projects HelloJndi
```
or start from 
```shell
mvn clean  package && mvn jetty:run --projects HelloKitty
```

I notice jetty starts both of them twice.

```console
[INFO] Session workerName=node0
[INFO] Started oeje10mp.MavenWebAppContext@4a2bf50f{HelloKitty,/HelloKitty,b=file:///tmp/jettyJndi/HelloKitty/target/HelloKitty/,a=AVAILABLE,h=oeje10s.SessionHandler@383cdd4d{STARTED}}{/tmp/jettyJndi/HelloKitty/target/HelloKitty.war}
[INFO] Started oeje10mp.MavenWebAppContext@4a2bf50f{HelloKitty,/HelloKitty,b=file:///tmp/jettyJndi/HelloKitty/target/HelloKitty/,a=AVAILABLE,h=oeje10s.SessionHandler@383cdd4d{STARTED}}{/tmp/jettyJndi/HelloKitty/target/HelloKitty.war}

[INFO] No Spring WebApplicationInitializer types detected on classpath
[INFO] Started oeje10mp.MavenWebAppContext@3b850bb7{HelloJndi,/HelloJndi,b=file:///tmp/jettyJndi/HelloJndi/src/main/webapp/,a=AVAILABLE,h=oeje10s.SessionHandler@3ba815ee{STARTED}}{file:///tmp/jettyJndi/HelloJndi/src/main/webapp/}
[INFO] Initializing Spring root WebApplicationContext
[INFO] Initializing Spring DispatcherServlet 'springServlet'
[INFO] Started oeje10mp.MavenWebAppContext@3b850bb7{HelloJndi,/HelloJndi,b=file:///tmp/jettyJndi/HelloJndi/src/main/webapp/,a=AVAILABLE,h=oeje10s.SessionHandler@3ba815ee{STARTED}}{file:///tmp/jettyJndi/HelloJndi/src/main/webapp/}
[INFO] Started ServerConnector@7441eed3{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
```
And on another application like this, when I initial a network access, it invokes twice and causes problems.
Is it a jetty plugin bug ?

I need some help. 
Thank You

**Comment by janbartel** [comment]
@kentyeh there's nothing to worry about, it's just 2 different loggings of the same event from the 2 subclasses of `MavenWebAppContext`:  `ServletContextHandler` and `ContextHandler` are both logging the same start event. Maven logging seems to hide the 2 different origins of these log messages, but you can see it clearly when running jetty from the distro instead of the plugin, eg:

> 2024-05-14 02:13:36.457:INFO :oejsh.ContextHandler:main: Started oeje10w.WebAppContext@5b2f8ab6{EE10 Demo JAAS WebApp,/ee10-test-jaas,b=file:///home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/work/jetty-0_0_0_0-8443-ee10-demo-jaas_war-_ee10-test-jaas-any-/webapp/,a=AVAILABLE,h=oeje10s.SessionHandler@576c5536{STARTED}}{/home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/webapps/ee10-demo-jaas.war}
> 2024-05-14 02:13:36.459:INFO :oejes.ServletContextHandler:main: Started oeje10w.WebAppContext@5b2f8ab6{EE10 Demo JAAS WebApp,/ee10-test-jaas,b=file:///home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/work/jetty-0_0_0_0-8443-ee10-demo-jaas_war-_ee10-test-jaas-any-/webapp/,a=AVAILABLE,h=oeje10s.SessionHandler@576c5536{STARTED}}{/home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/webapps/ee10-demo-jaas.war}

It would probably be nicer if just a single event was logged, I've opened an issue to see if there's anything to be done about that: #11787 


In the meanwhile, you could change your log4j setup to log the same info as the jetty logger used by the distro (ie include the name of the class that is originating the log message).

**Comment by kentyeh** [comment]
@janbartel 
Thanks you for your answer.
