### ISSUE TITLE
Cannot start embedded Jetty in read-only container

### ISSUE THREAD

**Issue by oleborup** [eclipse/jetty.project#11667]
**Jetty version(s)**
Jetty 12.0.7

**Jetty Environment**
Spring Boot 3.2.4

**Java version/vendor** `(use: java -version)`
Java 17

**OS type/version**
Any

**Description**

We use Spring Boot with embedded Jetty and Jersey for microservices running as Docker containers. For improved security we run Docker containers read-only.

After upgrading to Jetty 12 with Spring Boot 3.2, Jetty fails to initialize, as temp directory creation fails on read-only filesystem.

Running embedded with Jetty does not require the use of the temp directory. Cannot find a way to allow Jetty to run without creating temp directory.

Previously this worked to allow read-only.

```java
@Bean
public ConfigurableServletWebServerFactory servletContainer() {
    JettyServletWebServerFactory factory = new JettyServletWebServerFactory();
    factory.setDocumentRoot(new File(System.getProperty("java.io.tmpdir")));
    return factory;
}
```

**How to reproduce?**

See sample project: https://github.com/oleborup/spring-boot-jetty-jersey-error-handling

    mvn clean install
    docker build -t sampleapp .
    docker run --read-only -p 8080:8080 sampleapp
    

```
org.springframework.context.ApplicationContextException: Unable to start web server
    ...
Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp
    ...
Caused by: java.nio.file.FileSystemException: /tmp/jetty-docbase.8080.17697230866097709625: Read-only file system
    ...
```

**Comment by joakime** [comment]
Since you are using Servlet features (namely from the Jersey deps), know that Temp Directory is a requirement per spec.
It MUST exist per spec.

https://github.com/jakartaee/servlet/blob/6.0.0-RELEASE/spec/src/main/asciidoc/servlet-spec-body.adoc#481-temporary-working-directories

Can't get away from that.

**Comment by joakime** [comment]
Also note that the directory you see `/tmp/jetty-docbase.8080.17697230866097709625` is being created by Spring, not Jetty.

https://github.com/spring-projects/spring-boot/blob/v3.2.4/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/JettyServletWebServerFactory.java#L321

**Comment by oleborup** [comment]
@joakime Thanks for pointing this out. We will try to find alternatives to harden containers.

**Comment by joakime** [comment]
@oleborup for the Jetty side, (can't speak about the spring need for temp directory), if you have a temp directory created, but empty, and define/declare/set that temp directory in Jetty before you start Jetty, then Jetty will not attempt to create that directory (as it already exists).

You have 2 places that have a temp directory.

* `Server.setTempDirectory`
* `ServletContextHandler.setTempDirectory`

Ideally these should not be the same directory, but they can overlap.
eg:

* `Server.setTempDirectory` = `/tmp/server-work/`
* `ServletContextHandler.setTempDirectory` = `/tmp/server-work/context-work/`

The only thing left for you after you set the temp directory, and run in read-only mode, is to ensure you do not use technologies or features that require a temp directory (eg: `multipart/form-data` processing).

You can just run your webapp in this read-only mode and try out all of your features, if one produces an IOException / FileSystemException around this temp directory then you know you have to dig deeper to understand why you are using that feature that requires a temp directory.
