### ISSUE TITLE
Broken link to DefaultServlet in "Configuring Static Content Deployment"

### ISSUE THREAD

**Issue by gouessej** [eclipse/jetty.project#1168]
The last link in this page is broken:
[http://www.eclipse.org/jetty/documentation/current/static-content-deployment.html](http://www.eclipse.org/jetty/documentation/current/static-content-deployment.html)

It goes to [this page](http://download.eclipse.org/jetty/stable-9/xref/org/eclipse/jetty/servlet/DefaultServlet.html) whereas [this one](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/servlet/DefaultServlet.html) works.

I'm not sure that "stable-9/xref" exists.

The source code of this documentation is (probably) here:
[https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-documentation/src/main/asciidoc/configuring/deploying/static-content-deployment.adoc](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-documentation/src/main/asciidoc/configuring/deploying/static-content-deployment.adoc)

**Comment by jmcc0nn3ll** [comment]
all fixed up, thanks for reporting
