### ISSUE TITLE
Is it possible to change the keystore path or password without restarting Jetty

### ISSUE THREAD

**Issue by dattasid** [eclipse/jetty.project#11698]
**Jetty Version**
Jetty 11 or Jetty 12
**Jetty Environment**
core

**Java Version**
JDK 11 or latest

**Question**
Seems like ssl-reload only watches one keystore. Is there a way to change the keystore path or keystore passwords in ssl.ini and ask Jetty to reload the ssl.ini and SslContextFactory ?

Edit: Running standalone Jetty , starting it with jetty.sh .

**Comment by joakime** [comment]
Sounds very custom.

If you have access to the `SslContextFactory` in your code, you can do the following.

``` java
SslContextFactory.Server sslContextFactory = getSslContextFactory();

sslContextFactory.reload(ssl ->
{
    ssl.setKeyStorePath("/path/to/alt/keystore.p12");
    ssl.setKeyStorePassword("storepwd");
    ssl.setTrustStorePath("/path/to/alt/truststore.p12");
    ssl.setTrustStorePassword("storepwd");
    // and any other things you want the SslContextFacotry to change
    ssl.setEndpointIdentificationAlgorithm(null);
});
```

Up to you to determine how to trigger that code.

**Comment by dattasid** [comment]
I am running standalone Jetty using XML configuration. Is it possible to do something similar there ?

**Comment by joakime** [comment]
You would need a custom Jetty bean to trigger your custom code, and a Jetty module that defines any dependencies to other modules (like ssl), along with an XML entry.  Then you would have an XML to add the bean to the Server or SslContextFactory.

Similar to

* https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-server/src/main/config/modules/ssl-reload.mod
* https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-server/src/main/config/etc/jetty-ssl-context-reload.xml
* https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/KeyStoreScanner.java
