### ISSUE TITLE
Support proxies with WebSocketClient

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#117]
migrated from Bugzilla [#409516](https://bugs.eclipse.org/bugs/show_bug.cgi?id=409516)
status ASSIGNED severity _normal_ in component _websocket_ for _9.3.x_
Reported in version _9.0.3_ on platform _All_
Assigned to: Joakim Erdfelt

Original attachment names and IDs:
- _[0001-Add-proxy-support-to-websocket-client.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=233681)_ (ID 233681)

On 2013-05-30 12:21:45 -0400, Joakim Erdfelt wrote:

> Need to add support to configure a proxy for WebSocketClient.

On 2013-06-26 09:40:32 -0400, Missing name wrote:

> Any plans when it will be implemented?

On 2013-07-22 16:10:29 -0400, Gustavo GirÃ¡ldez wrote:

> Created attachment 233681
> Proposed patch for websocket proxy support
> 
> Here's a proposed patch to add proxy support to WebSocket client. It'll only work properly with HTTP/1.1 proxy servers and currently supports basic and digest authentication.
> 
> The ProxyConnection class is based heavily on UpgradeConnection (et al) and DigestAuthentication was taken and adapted from jetty-client.
> 
> From what I've read in Eclipse site pages a patch is the preferred way of sending a contribution but we can make a pull request from https://github.com/manastech/jetty.project/tree/websocket-proxy if that's convenient. Also, we need this functionality and would like for it to be included in a future version of Jetty. Please let me know what changes are required to make this happen. Thanks!

On 2013-07-22 16:20:45 -0400, Jesse McConnell wrote:

> First stop is here: 
> 
> http://www.eclipse.org/jetty/documentation/current/contributing-patches.html#contributing-cla
> 
> thanks for the patch!

On 2013-09-23 16:50:18 -0400, Jesse McConnell wrote:

> Gustavo, can you complete the CLA paperwork so we can consider your patch?

On 2013-09-24 10:56:01 -0400, Gustavo GirÃ¡ldez wrote:

> I'm confused about what are the next steps. I already signed the CLA. Is there anything else I should do? Thanks!

On 2013-09-24 10:56:44 -0400, Jesse McConnell wrote:

> hm...I'll ping wayne about it, there should be a little check mark by your name now :)

On 2013-09-24 11:38:35 -0400, Wayne Beaton wrote:

> (In reply to Jesse McConnell from comment # 6)
> 
> > hm...I'll ping wayne about it, there should be a little check mark by your
> > name now :)
> 
> The CLA system is based on the email address. 
> 
> The database shows that Gustavo has a CQ, but under a gmail address.

On 2013-09-24 12:11:11 -0400, Gustavo GirÃ¡ldez wrote:

> Hmm, I remember creating my account with my personal email address (gustavo.giraldez@gmail.com) but then I changed it to my work email ggiraldez@manas.com.ar. I signed the CLA after this change IIRC. Is there anything I can do?

On 2013-09-25 07:26:45 -0400, Wayne Beaton wrote:

> (In reply to Gustavo GirÃ¡ldez from comment # 8)
> 
> > Hmm, I remember creating my account with my personal email address
> > (gustavo.giraldez@gmail.com) but then I changed it to my work email
> > ggiraldez@manas.com.ar. I signed the CLA after this change IIRC. Is there
> > anything I can do?
> 
> According to my records, you signed the CLA using your gmail account.
> 
> Did you create a second account, or change the email address on the first account?

On 2013-09-25 09:33:51 -0400, Gustavo GirÃ¡ldez wrote:

> No, I only have one account. I just invalidated my CLA and signed a new one. I can now see the tick next to my name, as well as next to Joakim's and Jesse's, which for some reason I didn't get before. So, it looks like it's fixed now :)

On 2013-11-28 10:00:13 -0500, Axel Uhl wrote:

> The patch proposed by Gustavo looks good. Now that the IP / CLA issues have been solved, what is keeping the patch from getting merged? Do you already have a target release in mind?

On 2013-11-28 10:04:00 -0500, Joakim Erdfelt wrote:

> We'll see about merging this patch back into master (aka Jetty 9.1.0) after the holiday.

On 2014-03-07 07:19:15 -0500, Vlad Lucian Ginju wrote:

> Any news on adding the proxy support for websocket client?

On 2014-05-08 23:18:39 -0400, Arthur Naseef wrote:

> Any update?

On 2015-02-12 00:36:32 -0500, Thrilochana Rajappa wrote:

> Does the latest jetty libraries(9.1.1) support proxy server?

On 2015-02-12 11:56:58 -0500, Joakim Erdfelt wrote:

> (In reply to Thrilochana Rajappa from comment # 15)
> 
> > Does the latest jetty libraries(9.1.1) support proxy server?
> 
> Latest Jetty is 9.2.7.v20150116
> 
> See: http://download.eclipse.org/jetty/

On 2015-02-13 03:18:02 -0500, Thrilochana Rajappa wrote:

> Thanks. Does these libraries(9.2.7) support proxy server?

On 2015-03-04 05:03:52 -0500, Steffen Koehler wrote:

> It would be a huge help also in our project to have Jetty websockets with proxy support, 'cause other ways I would have to search for another solution for my proxy problem and mix that then with the Jetty webserver somehow, which will be a pain, I guess..
> 
> I would really appreciate to have Gustavos patch (or something simular) been implemented. Unfortunately I'm not enough of an expert to support :-|
> 
> Thanks for your great work on Jetty
> 
> regards
> Steffen

On 2015-04-16 14:30:26 -0400, Adam Foxman wrote:

> Hi all,
> 
> Seems like this issue has stalled.  I'd like to help kick-start it and get the original patch into the mainline distribution.
> 
> What is the next step?  Is the patch suitable, or does it need work?  I'm happy to provide dev support to help this along, if necessary.

On 2015-04-16 16:27:05 -0400, Gustavo GirÃ¡ldez wrote:

> Just a quick comment to let you know that we continued to add some functionality and fixes over the proposed patch. You can find the most current version (what we use in production) at https://github.com/manastech/jetty.project/commits/websocket-proxy. We added NTLM support and authentication over non-persistent connections. There are also a couple of bug fixes.
> 
> OTOH, it probably won't merge cleanly with the current version of Jetty and we added jCIFS as an extra dependency for the NTLM support.

On 2015-10-15 18:04:47 -0400, Joakim Erdfelt wrote:

> Now that HttpClient has the beginnings of HTTP/1.1 upgrade support, we can start this work for proxy support.
> 
> Initial commit to [feature/wsclient-httpclient 3f1d566]

On 2016-01-26 03:26:54 -0500, Amir Karo wrote:

> Hi Joakim,
> This is good news that you started working on it as we have a lot of customers waiting for it.
> 
> Can you estimate when we can have a jetty version with this support?
> 
> Thanks!
> Amir

**Comment by maggu2810** [comment]
Hi,
does this change also allow the usage of ProxyServlet for a reverse proxy of WebSockets, too?

**Comment by joakime** [comment]
No, that would be a different task / support level.
Essentially HTTP Upgrade Support in the ProxyServlet.

**Comment by joakime** [comment]
This was implemented in Jetty 9.4.0+
