### ISSUE TITLE
Jetty 9.4 breaks Resource.newClassPathResource() when switching thread context class loader

### ISSUE THREAD

**Issue by Martin-Wegner** [eclipse/jetty.project#1170]
Since Jetty 9.4 `Resource.newClassPathResource(String)` does not work for me anymore (returns `null`)  when switching thread context class loader.

The reason is the commit https://github.com/eclipse/jetty.project/commit/a311c8bde171551a57ff28c04851a3b53acfc1e0 (480904 - jetty-util Loader simplification) which changed the `jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java`:

Jetty 9.3 line 287: `url=Loader.getResource(Resource.class,name);`

Jetty 9.4 line 286: `url=Loader.getResource(name);`

Example code:

```
System.out.println(Resource.newClassPathResource("certDev/server.pfx")); // not null

// create Jetty class loader
jettyClassLoader = new URLClassLoader(Arrays.stream(jettyJarFiles)
  .map(jettyJarFile -> {
	try {
	  return jettyJarFile.toURI().toURL();
	} catch (final MalformedURLException exception) {
	  throw new RuntimeException(exception);
	}
  })
  .toArray(size -> new URL[size]), null);

// backup class loader of the current thread
final ClassLoader currentClassLoader = Thread.currentThread().getContextClassLoader();

// set Jetty class loader as context class loader of the current thread
Thread.currentThread().setContextClassLoader(jettyClassLoader);

System.out.println(Resource.newClassPathResource("certDev/server.pfx")); // null since Jetty 9.4
```

**Comment by joakime** [comment]
Can you submit a PR with a testcase (add a new testcase in [`ClassPathResourceTest.java`](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ClassPathResourceTest.java) file) that shows `newClassPathResource()` usage working in Jetty 9.3 and not in 9.4?

Note: we have testcases that use `newClassPathResource()` in [`HttpOutputTest`](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java) too.

**Comment by gregw** [comment]
@Martin-Wegner ,

The code that was changed in 9.4, is that we no long look to load classes/resources from the same classloader that loader jetty.    That was really just encouraged code to not properly set the thread context classloader.

For this method to work for you, then the class you are looking for needs to either be on the system classpath or visible to a Classloader that is set as the current thread context classloader.     If executed from within a webapp, you will have a classloader that is able to see WEB-INF classes, but jetty and some system classes are hidden from it.

This is a deliberate change, which I think is the correct way to go.  However, we are open to understand your use-case of why we may need to search a bit harder for classes, so please describe your classloader setup and classpath.

**Comment by joakime** [comment]
What happens if you instantiate the `jettyClassLoader` with the parent classloader in your example?

```java
// create Jetty class loader
final ClassLoader parentClassLoader = Thread.currentThread().getContextClassLoader();
jettyClassLoader = new URLClassLoader(Arrays.stream(jettyJarFiles)
  .map(jettyJarFile -> {
	try {
	  return jettyJarFile.toURI().toURL();
	} catch (final MalformedURLException exception) {
	  throw new RuntimeException(exception);
	}
  })
  .toArray(size -> new URL[size]), parentClassLoader); // <-- this
```

**Comment by Martin-Wegner** [comment]
@joakime and @gregw thanks for your response. I don't want and I can't set the parent class loader. My use case and intention were:

I'm working on a large project which consists of multiple WAR files. Every WAR module needs to be tested with embedded integration tests. That means, that our unit test framework starts a Jetty server and deploys all WAR files. This Jetty server must run in a "sand box" which means, no classes and resources from the current WAR module (from the class loader which runs the unit test) should be visible to the Jetty class loader. Therefore, I have a new class loader which only contains the Jetty JAR files. The whole code which setups and starts the Jetty server uses reflection to be completely independent from the current class loader. The Jetty server needs a trust and key store which is available in the class path of the current WAR module project. Both are loaded also via reflection. This all works until Jetty 9.4... But I can try to determine the absolute resource path before changing the Thread context class loader...

**Comment by Martin-Wegner** [comment]
>  But I can try to determine the absolute resource path before changing the Thread context class loader...

This works and after changing the class loader I can use `Resource.newResource(string)` via reflection and the absolute path.

**Comment by joakime** [comment]
Your requirement is exactly what the whole WebAppContext and WebAppClassLoader default behavior is all about.

It enforces the Servlet Spec mandated classloader isolation already, don't manipulate it further by specifying your own ThreadContextClassLoader.

For your testing reasons, be sure you don't ever set/call WebAppClassLoader.setParentLoaderPriority(boolean)

But even in that scenario, the meaning of "Server ClassLoader" and "WebApp ClassLoader" still applies.   Your desire to access a classpath resource depends entirely on the context of _when_ you want to access that resource.  (Within the lifecycle of a ServletContext? then only the WebApp's ClassLoader applies.   Within the Server LifeCycle? then only the Server ClassLoader applies)

**Comment by Martin-Wegner** [comment]
@joakime I tested it without reflection and without any class loader swithcing but the servlet context sees the classes and resources of the unit test class loader :(

**Comment by joakime** [comment]
@Martin-Wegner that's a separate issue.

For your specific testing requirements, you should probably have separate modules/projects, one that builds the war, and another that depends on that war to perform some integration testing using embedded-jetty, that's the only surefire (hah!) way to ensure that the classpath is uncontaminated of compile time dependencies during build time.

**Comment by Martin-Wegner** [comment]
@joakime it's not that easy, it's a little bit more complicated :)
