### ISSUE TITLE
Setting up a dedicated ThreadPool for each SeverConnector

### ISSUE THREAD

**Issue by shmulik-ubimo** [eclipse/jetty.project#1174]
I'm trying to configure a dedicated executor in `jetty.xml` (jetty-9) for each of my `ServerConnector`s, as I'm able to do in Tomcat, but for some reason I get lost, is that even possible ?

**Comment by sbordet** [comment]
Yes it is possible: you can pass an `Executor` to one of the `ServerConnector` constructors.

**Comment by joakime** [comment]
Also, this will only apply for the general processing of the initial incoming request, but not all executor usage (like I pointed out in your stackoverflow.com question).

Most components in Jetty will just use `server.getExecutor()` when it needs an executor for whatever purpose it needs.

**Comment by joakime** [comment]
The Tomcat approach and the Jetty approach for connector specific Executors are entirely different.  Your desired end goal (behavior on Jetty that is consistent with Tomcat) is not achievable.

**Comment by shmulik-ubimo** [comment]
Thanks @joakime!
