### ISSUE TITLE
Unexpected HTTP Response Status Code: 404 Not Found

### ISSUE THREAD

**Issue by RomanKhabarov** [eclipse/jetty.project#11748]
**Jetty version(s)**
`12.0.8`

**Jetty Environment**
`ee8`

**Java version/vendor** `(use: java -version)`
`openjdk version "17.0.7" 2023-04-18 LTS`

**OS type/version**
`macOS 14`

**Description**
I've tried to create websocket server and found out strange behavior.
I wanted to create single endpoint with `PathParam` variable in the *middle* of the path, like this: `/test/{param}/category` and if I run server and try to call this endpoint it says `404 Not Found`. If I move parameter to the end of path like this: `/test/category/{param}` everything works as expected.

After much investigation, I discovered that if I add another endpoint *without parameters*, the endpoint with a parameter in the middle will start working.

**How to reproduce?**

*Endpoint with parameter:* ([github](https://github.com/RomanKhabarov/ee8-websockets-example/blob/main/src/main/java/examples/endpoint/EchoServerGenericEndpoint.java))
```
public class EchoServerGenericEndpoint extends Endpoint {
    private static final Logger LOG = LoggerFactory.getLogger(EchoServerGenericEndpoint.class);

    @Override
    public void onClose(Session session, CloseReason close) {
        super.onClose(session, close);
        LOG.info("WebSocket Close: {} - {}", close.getCloseCode(), close.getReasonPhrase());
    }

    @Override
    public void onOpen(Session session, EndpointConfig config) {
        LOG.info("WebSocket Open: {}", session);
        String param = session.getPathParameters().get("param");
        session.getAsyncRemote().sendText("You are now connected to " + this.getClass().getName() + " " + param);
    }

    @Override
    public void onError(Session session, Throwable cause) {
        super.onError(session, cause);
        LOG.warn("WebSocket Error", cause);
    }
}
```

*Endpoint without parameter:* ([github](https://github.com/RomanKhabarov/ee8-websockets-example/blob/main/src/main/java/examples/endpoint/EchoServerEndpoint.java))
```
public class EchoServerEndpoint extends Endpoint {
    private static final Logger LOG = LoggerFactory.getLogger(EchoServerEndpoint.class);

    @Override
    public void onClose(Session session, CloseReason close)  {
        super.onClose(session, close);
        LOG.info("WebSocket Close: {} - {}", close.getCloseCode(), close.getReasonPhrase());
    }

    @Override
    public void onOpen(Session session, EndpointConfig config) {
        LOG.info("WebSocket Open: {}", session);
        session.getAsyncRemote().sendText("You are now connected to " + this.getClass().getName());
    }

    @Override
    public void onError(Session session, Throwable cause) {
        super.onError(session, cause);
        LOG.warn("WebSocket Error", cause);
    }
}
```

*Endpoints initialization:* ([github](https://github.com/RomanKhabarov/ee8-websockets-example/blob/main/src/main/java/examples/endpoint/EchoServer.java#L26))
```
JavaxWebSocketServletContainerInitializer.configure(servletContextHandler, (context, container) ->
        {
            ServerEndpointConfig echoConfig = ServerEndpointConfig.Builder.create(EchoServerEndpoint.class, "/echo").build();
            container.addEndpoint(echoConfig);

            ServerEndpointConfig pathParamsConfig = ServerEndpointConfig.Builder.create(EchoServerGenericEndpoint.class, "/test/{param}/category").build();
            container.addEndpoint(pathParamsConfig);
        });
```

With configuration above everything works fine, both endpoints are reachable, but if you try to comment out the first endpoint (`/echo`) initialization without any other changes the second endpoint `/test/{param}/category` will stop working and will respond `404 Not Found`. 
Configuration with one parameterized endpoint that doesn't work:
```
JavaxWebSocketServletContainerInitializer.configure(servletContextHandler, (context, container) ->
        {
            //ServerEndpointConfig echoConfig = ServerEndpointConfig.Builder.create(EchoServerEndpoint.class, "/echo").build();
            //container.addEndpoint(echoConfig);

            ServerEndpointConfig pathParamsConfig = ServerEndpointConfig.Builder.create(EchoServerGenericEndpoint.class, "/test/{param}/category").build();
            container.addEndpoint(pathParamsConfig);
        });
```

It will fail with the following message: `Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found`

There are tests [here](https://github.com/RomanKhabarov/ee8-websockets-example/blob/main/src/test/java/examples/endpoint/EchoTest.java) to connect to endpoints:
```
@Test
    public void testGenericEcho() throws Exception {
        URI uri = new URI("ws", server.getURI().getAuthority(), "/test/p1/category", null, null);
        clientEndPoint.connect(uri);
        clientEndPoint.close();

        assertThat(messages, contains("You are now connected to " + EchoServerGenericEndpoint.class.getName() + " p1"));
    }
```

---

You can find whole project [here](https://github.com/RomanKhabarov/ee8-websockets-example).

**Comment by lachlan-roberts** [comment]
Looks like a bug in `PathMappings`, it is also present in `10.0.x`/`11.0.x`.

@RomanKhabarov btw in your project you are not using the server from `Server newServer(int port)` in your main method. see https://github.com/RomanKhabarov/ee8-websockets-example/blob/86a3f1aea19c4a7bb55db864cae0402f0111b2c7/src/main/java/examples/endpoint/EchoServer.java#L13

But I found the bug so will put up a PR to fix. Thanks for reporting the issue.
