### ISSUE TITLE
Use fluent style for HttpConfiguration

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#11742]
**Jetty version(s)**
12

**Enhancement Description**

Allow style of 
```
    connectionFactory.getHttpConfiguration()
        .setRelativeRedirectAllowed(true)
        .setGenerateRedirectResponse(true);
```

**Comment by olamy** [comment]
what about?
```
    connectionFactory.getHttpConfiguration()
        .relativeRedirectAllowed(true)
        .generateRedirectResponse(true);
```
or
```
    connectionFactory.getHttpConfiguration()
        .withRelativeRedirectAllowed(true)
        .withGenerateRedirectResponse(true);
```

**Comment by sbordet** [comment]
Careful to not break JMX, which tests for setters to have a `void` return type.

It's convenient, but it's 3 lines against 3 lines, so there is not much saved?

**Comment by gregw** [comment]
I was planning on keeping the names so it would not require any changes.... however, @sbordet point about JMX is good.   We sometimes do use that to adjust config at runtime.  I'm not in the mood to duplicate all the setters: one fluent and one JMX, so let's close this.
