### ISSUE TITLE
Use Enable-Native-Access manifest attribute for FFM

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#11751]
**Jetty version(s)**
12.0.9+

**Java version/vendor** `(use: java -version)`
22+

**Description**
Currently, use of the Jetty module to access Quiche via FFM requires `--enable-native-access` to be specified on the command line, and in the POM files for testing.

However, it _should_ be possible to use the `Enable-Native-Access` manifest attribute to achieve the same, and avoid specifying the command line option, which is easier because it does not require any additional configuration.

Investigate if this is possible, and if so, update the `*.jar` generation and the POM configuration.

**Comment by lorban** [comment]
According to my understanding of https://openjdk.org/jeps/454, this won't help; quoting:

_the JAR-file manifest attribute Enable-Native-Access: ALL-UNNAMED can be used **in an executable JAR** to enable warning-free use by **all code on the class path**_

**Comment by joakime** [comment]
So put it in multiple places.
The quiche jars, the start.jar, and the runner.jars ?

**Comment by lorban** [comment]
We don't want to put that in `start.jar`, as that might become a security issue: any lib of any war would be able to mess around with native code freely while the goal of the JVM is to also restrict native code, including JNI.

And this has no effect if the jar is not an executable jar given to `java -jar ...`, so I think this won't help us in any way.
