### ISSUE TITLE
ChunkAccumulator read and readAll should be static

### ISSUE THREAD

**Issue by scrat98** [eclipse/jetty.project#11757]
**Jetty version(s)**
12.0.8

**Enhancement Description**

ChunkAccumulator.read and ChunkAccumulator.readAll methods create AccumulatorTask that's under the hood creates ChunkAccumulator instance and pass it to the take method, therefore I think it's more accurate to make these methods static

**Comment by gregw** [comment]
@scrat98 please note #11598 which deprecates ChunkAccumulator.   It is still draft status, but we are working on improving this area of the code.   So until we have decided on that, we are unlikely to make API changes here.

**Comment by scrat98** [comment]
@gregw then I think we can close this issue if eventually ChunkAccumulator will be removed
