### ISSUE TITLE
Update documentation for #10077

### ISSUE THREAD

**Issue by basil** [eclipse/jetty.project#11761]
**Jetty version(s)**
12.0.8

**Jetty Environment**
EE8

**Java version/vendor** `(use: java -version)`
```
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)
```

**OS type/version**
Ubuntu 22.04.4 LTS x86_64

**Description**
The documentation for `jetty-maven-plugin` was never updated per https://github.com/jetty/jetty.project/pull/10077#pullrequestreview-1516697930.

**How to reproduce?**
Try to configure the plugin using [the existing documentation](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#configuring-security-settings).

**Comment by janbartel** [comment]
Raised PR #11771
