### ISSUE TITLE
Race condition in QoSHandler

### ISSUE THREAD

**Issue by arcticmosquito** [eclipse/jetty.project#11763]
**Jetty version(s)**
12.0.x

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
irrelevant

**OS type/version**
irrelevant

**Description**
QoSHandler contains a race between 'expire' (getServer().getScheduler()) and 'resume' threads (getServer().getThreadPool()) , which causes the "resume" thread to busy-loop until another request is suspended, i.e. added to one of the queues, which may never happen.
Consider the following serialization order (Jetty codestyle dropped for brevity):
```java
// 1. resume thread (QoSHandler.java#L291)
int permits = state.getAndIncrement();
if (permits >= 0)
    return;

// 2. expire thread (QoSHandler.java#L361)
boolean removed = queues.get(priority).remove(this);

// 3. resume thread (QoSHandler.java#L299) - now trapped in a busy loop
while (!resumeSuspended())
    Thread.onSpinWait();
```

**How to reproduce?**
This might be notoriously hard to reproduce on purpose, but one could reason about the issue without reproduction steps.

**Comment by sbordet** [comment]
@arcticmosquito good catch!

**Comment by arcticmosquito** [comment]
@sbordet thanks for the swift fix
