### ISSUE TITLE
request.getHttpURI().getScheme() is null on FORWARD dispatched request, causing NPE

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#11760]
**Jetty version(s)**
12.0.8

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
When working with a RequestDispatcher forward request, the request.getHttpURI().getScheme() returns null.
It shouldn't return null in this use case.

**Comment by janbartel** [comment]
@joakime can you please clarify if this is a cross-context dispatch or a dispatch within the same context?

**Comment by jluehe** [comment]
@janbartel, it's a cross-context dispatch ...

**Comment by janbartel** [comment]
Raised #11770

**Comment by jluehe** [comment]
Thank you, @janbartel, for the quick fix! I've noticed your PR covers `ee9` and `ee10`, but we're (still) on `ee8`. Would it be possible to apply the same change to `ee8` as well?

**Comment by janbartel** [comment]
The ee8 code is automatically generated from the ee9 code, so the fix will be available in ee8 too.

**Comment by jluehe** [comment]
Oh nice! I had forgotten about that! Thank you, @janbartel
