### ISSUE TITLE
jetty-http-spi does not properly provide SPI for modules

### ISSUE THREAD

**Issue by bowbahdoe** [eclipse/jetty.project#11778]
**Jetty version(s)**
12.0.9

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
21.0.1"

**OS type/version**
Mac OS / Ventura 13.3.1 (Apple Silicon)

**Description**

**How to reproduce?**

I made a reproducer repo here

https://github.com/bowbahdoe/jdk-httpserver-todobackend

```
./mvnw clean compile jlink:jlink
./target/maven-jlink/classifiers/image/bin/server
```

If you go to `localhost:7777` in a browser you'll see that `/favicon.ico` is requested and that produces an exception. Jetty is not in the stacktrace, so I conclude that its implementation is not being used.

My guess is that its due to not having a `provides` here https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-http-spi/src/main/java/module-info.java

in addition, that artifact does not depend on `jetty-server` so i have to add it manually - not sure if thats intentional or not.

**Comment by sbordet** [comment]
@bowbahdoe is there a reason you closed #11768?

**Comment by bowbahdoe** [comment]
@sbordet Yes. I tried to go through the ECA and got to the end but the email that agreed wasn't the same as the email I had configured for the commit; though both are on my github account. Then i couldn't figure out how to add an email to the agreement.

So i got frustrated and figured opening an issue would be easier.

**Comment by sbordet** [comment]
Sorry about the ECA experience 😞 

It was a good change.

Let us know if you want to try again, so you'll have your contribution registered.
Otherwise, we'll do it.

Thanks!

**Comment by bowbahdoe** [comment]
> Let us know if you want to try again, so you'll have your contribution registered.
> Otherwise, we'll do it.

If I have something else I will. I only looked at this one usage, but it might be worth doing a scan to see if there are other service providers that are in META-INF/services but not the module-infos.

**Comment by sbordet** [comment]
Ok, we will do it.
Thanks!
