### ISSUE TITLE
Announce correct issue system

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/jetty.project#1178]
Several locations in the web still announce https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Jetty but if you follow that link, all you get is:

>  Sorry, entering a bug into the product Jetty has been disabled. 

Can this message point to the new issue system? Of course existing links should be updated, too, e.g., from

- https://projects.eclipse.org/projects/rt.jetty/developer
- https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/CONTRIBUTING.md

**Comment by joakime** [comment]
Eclipse organization has rejected our requests to have various old URLs mapped with redirects to more accurate/current locations.

There is no solution for this, sorry.

**Comment by stephan-herrmann** [comment]
At least https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/CONTRIBUTING.md seems to be under your sole control :)
Also the PMI at https://projects.eclipse.org/projects/rt.jetty/developer should allow you to edit that information ...

**Comment by joakime** [comment]
9.3.x is old
9.4.x is current and accurate -> https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md

**Comment by joakime** [comment]
Need to cherry pick back to 9.3.x the changes in CONTRIBUTING.md

**Comment by joakime** [comment]
Applied cherry-pick of commits e63f86ab2f9a4c446f18b11ac936182705c74a9e 49da7397b59da316572326b0d910f4896c788663 to older jetty-9.3.x branch.

**Comment by jmcc0nn3ll** [comment]
@stephan-herrmann what setting under https://projects.eclipse.org/projects/rt.jetty/developer cause all I have ever seen is hardcoded Bugzilla stuff in there.

**Comment by stephan-herrmann** [comment]
@jmcc0nn3ll  I see, one can enter only a bugzilla product/component, but not a github url. Too bad, should contact Wayne.
OTOH, you _can_ provide a free-text "Contribution Message" ...

Anyway, I just wanted to let you know I had to hunt for some time until I found you here ...
