### ISSUE TITLE
How to configure Jetty Server v12 ee10 for serving multiple static resources in the same base directory?

### ISSUE THREAD

**Issue by Emilyserap** [eclipse/jetty.project#11791]
**Jetty version(s)**
12.0.9

**Jetty Environment**
ee10

**Java Version**
JavaSE-17

I am working on a web application using Java, and I have configured servlets to serve static resources using ServletHolder and DefaultServlet. Here is the configuration code:

`ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);`
`context.setContextPath("/");`
`ResourceFactory resourceFactory = ResourceFactory.of(context);`
`context.setBaseResource(resourceFactory.newResource(mainResourceBase));`
`ServletHolder holderAlt = new ServletHolder("static-alt", DefaultServlet.class);`
`holderAlt.setInitParameter("dirAllowed", "true");`
` holderAlt.setInitParameter("acceptRanges", "true");`
`context.addServlet(holderAlt, "*.js");`
`ServletHolder holderDef = new ServletHolder("default", DefaultServlet.class);`
`holderDef.setInitParameter("dirAllowed", "true");`
`context.addServlet(holderDef, "/");`

i'm encountering a 404 Not Found error when trying to access static resources ending with .js.
I would appreciate any insights or suggestions to help resolve the issue of static resources returning 404 errors.

**Comment by Emilyserap** [comment]
Are there any limitations for Jetty 12 PathSpecs?

**Comment by janbartel** [comment]
I think we have a bug in `ee10` handling of suffix-mapped `DefaultServlet` instances.  I believe this works in `ee9`, can you back down to that version? 

I've opened  issue #11794.

**Comment by Emilyserap** [comment]
Yes, it works in EE9, but I want to know if this bug will be fixed soon in EE10?

**Comment by Emilyserap** [comment]
Thanks for fixing this issue, but I want to know why when I refresh the dependencies, I don't see the new modification in the class DefaultServlet.java

**Comment by Emilyserap** [comment]
> I think we have a bug in `ee10` handling of suffix-mapped `DefaultServlet` instances. I believe this works in `ee9`, can you back down to that version?
> 
> I've opened issue #11794.



> I think we have a bug in `ee10` handling of suffix-mapped `DefaultServlet` instances. I believe this works in `ee9`, can you back down to that version?
> 
> I've opened issue #11794.

I'm also having the same problem with static  resources index.html. I'm not sure if it's a bug in DefaultServlet or a limitation of PathSpecs, but I'd appreciate it if you could take a look into it.


```
ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
context.setContextPath("/");
ResourceFactory resourceFactory = ResourceFactory.of(context);
context.setBaseResource(resourceFactory.newResource(mainResourceBase));
ServletHolder holderAlt = new ServletHolder("static-alt", DefaultServlet.class);
holderAlt.setInitParameter("dirAllowed", "true");
 holderAlt.setInitParameter("acceptRanges", "true");
context.addServlet(holderAlt, "*.js");
ServletHolder holderstat = new ServletHolder("static", DefaultServlet.class);
holderstat.setInitParameter("dirAllowed", "true");
holderstat setInitParameter("acceptRanges", "true");
holderstat.setInitParameter("cacheControl", "no-store");
context.addServlet(holderstat , "/index.html");
ServletHolder holderDef = new ServletHolder("default", DefaultServlet.class);
holderDef.setInitParameter("dirAllowed", "true");
context.addServlet(holderDef, "/");
```
