### ISSUE TITLE
Split `DefaultServlet`

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#11796]
**Jetty version(s)**
12.1

**Enhancement Description**
We should:
 + rename the existing `DefaultServlet` to `ResourceServlet`
 + create a new `DefaultServlet` that extends `ResourceServlet`
 + move anything that assumes context resources or '/' pathspec from `ResourceServlet` to `DefaultServlet`
 + make the `DefaultServlet` warn if it is deployed anywhere but '/'

**Comment by lorban** [comment]
This relates to https://github.com/jetty/jetty.project/issues/10738 and https://github.com/jetty/jetty.project/issues/10739

**Comment by janbartel** [comment]
I'm closing this issue as @gregw has recently committed https://github.com/jetty/jetty.project/pull/11933 that introduces the `ResourceServlet` and addresses this issue.
