### ISSUE TITLE
UnrecoverableKeyException

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#118]
migrated from Bugzilla [#411104](https://bugs.eclipse.org/bugs/show_bug.cgi?id=411104)
status ASSIGNED severity *major* in component *server* for *9.0.x*
Reported in version *9.0.2* on platform *PC*
Assigned to: Greg Wilkins

On 2013-06-19 06:41:22 -0400, Samuel Fung wrote:

> I have a keystore containing many key-pairs. I set the following in jetty-ssl.xml (choosing 1 key-pair):
> 
> <Configure id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
>   <Set name="KeyStorePath">..</Set>
>   <Set name="KeyStorePassword">...</Set>
>   <Set name="CertAlias">...</Set>
>   <Set name="KeyManagerPassword">...</Set>
> 
> I've verified several times that the settings are correct, but Jetty keeps throwing this exception:
> 
> java.security.UnrecoverableKeyException: Cannot recover key
>     at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
>     at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:138)
>     at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:55)
>     at java.security.KeyStore.getKey(KeyStore.java:792)
>     at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:131)
>     at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:68)
>     at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:259)
>     at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:903)
>     at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:296)
> ...
> 
> I trace to SslContextFactory.java:903
> keyManagerFactory.init(keyStore,_keyManagerPassword == null?(_keyStorePassword == null?null:_keyStorePassword.toString().toCharArray()):_keyManagerPassword.toString().toCharArray());
> 
> _keyManagerPassword (corresponds to keytool genkeypair -keypass option)
> and
> _keyStorePassword (corresponds to keytool genkeypair -storepass option)
> are 2 different passwords, they must not be used interchangeably like the above statement.

**Comment by gregw** [comment]
Closing for now as this code has been significantly reworked in 9.2 and 9.3
