### ISSUE TITLE
Maven "relativePath" usage

### ISSUE THREAD

**Issue by scrat98** [eclipse/jetty.project#11807]
**Jetty Version**
12.0.x

**Jetty Environment**
any

**Java Version**
any

**Question**
I would like to ask what's the reason do not use "relativePath" in so multi module project. Otherwise IDEs typically are going crazy in modules resolving while seeking those poms in local/remote registry, but not directly in the codebase.

What do you think if it a good idea to add everywhere relativePath in pom?

**Comment by olamy** [comment]
I do not have such issues locally using IntelliJ.
What sort of IDE are you using?

**Comment by scrat98** [comment]
@olamy I'm really sorry for such a long reply. I'm also using IntelliJ IDEA 2023.3.6 (Community Edition). Especially that issue appears on the first build within IDE (when you have an empty .m2 local repo). Sometimes IDE cannot find the imports from other modules and another issues.

Maybe it's local issue, but I typically found that in multi module project using relativePath gives the advantages to run "reload maven projects"/"generate sources"/"reload all maven projects"/etc

**Comment by sbordet** [comment]
We use IDEA as well, and we have no problems.
Given convention over configuration, I don't think it's a good idea to put `relativePath` explicitly, but with the default value, in all the POMs.

**Comment by scrat98** [comment]
@sbordet okay, closed this issue. Thanks for your time
