### ISSUE TITLE
Unable to upload Multipart data with Embedded jetty service 

### ISSUE THREAD

**Issue by pranavv** [eclipse/jetty.project#1182]
I need to upload multipart form data using jersery with embedded jetty , i am getting exception multipart injection error 
what do i need to do configure  support for multipart upload webservice

import java.io.InputStream;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.Consumes;
import javax.ws.rs.Produces;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.core.MediaType;
import org.glassfish.jersey.media.multipart.FormDataContentDisposition;
import org.glassfish.jersey.media.multipart.FormDataParam;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
/**
 * REST Web Service
 *
 */
@Path("UploadFile")
public class FileUploaderService {

    @Context
    private UriInfo context;

    /**
     * Creates a new instance of FileUploaderService
     */
    public FileUploaderService() {
        System.out.println("Got a request");
    }

    /**
     * @return an instance of java.lang.String
     */
    @GET
    @Path("/testme")
    @Produces(MediaType.TEXT_PLAIN)
    public String getXml() {
        System.out.println("Success Printing");
        //TODO return proper representation object
        return "success";
    }

    /**
     * PUT method for updating or creating an instance of FileUploaderService
     * @param  representation for the resource
     */
    @POST
    @Path("/upload")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public String uploadFile(@FormDataParam("file") InputStream uploadedInputStream,
			@FormDataParam("file") FormDataContentDisposition fileDetail) {
     String fileLocation = targetDir();
     try {  
                FileOutputStream out = new FileOutputStream(new File(fileLocation + "/" + fileDetail.getFileName()));  
                int read = 0;  
                byte[] bytes = new byte[1024];  
                while ((read = uploadedInputStream.read(bytes)) != -1) {  
                    out.write(bytes, 0, read);  
                }  
                out.flush();  
                out.close();  
            } catch (IOException e) {e.printStackTrace();}  
            String output = "File successfully uploaded to : " + fileLocation;  
            String filePath = "/Volumes/Installers/";
            return filePath + fileDetail.getFileName();  
    }
    private String targetDir() {
        String uploadDIR = null;
        try {

            String TmpDir = System.getProperty("java.io.tmpdir");
            File Dir = new File(TmpDir + "/Installers");
            if (Dir.exists()) {
                System.out.println("Directory Exists");
            } else {
                if (Dir.mkdir()) {
                    System.out.println("Directory created");
                } else {
                    return null;
                }
            }
            uploadDIR = Dir.getAbsolutePath();
            return uploadDIR;
        } catch (Exception ex) {
            System.out.println("error in getting path for downloading apps "+ex.getMessage());
            return null;
        }
    }
}

**Comment by joakime** [comment]
There's nothing Jetty about what you pasted.
It appears to be Jersey and Glassfish.

Suggest that you ask this question on the Jersey support forums/mailing list/issue tracker.
Also suggest you include the exception stacktrace for them.
