### ISSUE TITLE
jetty-ee8-websocket-javax-server export not honoured

### ISSUE THREAD

**Issue by Maurice-Betzel** [eclipse/jetty.project#11851]
**Jetty version(s)**
12.0.9

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

**OS type/version**
Win11

**Description**

Declared export package in Maven Bundle Plugin is not included in manifest:

<Export-Package>org.eclipse.jetty.websocket.javax.server.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}"</Export-Package>

**How to reproduce?**
noop

**Comment by olamy** [comment]
just to confirm is it the jar `jetty-ee8-websocket-javax-server`?

**Comment by Maurice-Betzel** [comment]
> just to confirm is it the jar `jetty-ee8-websocket-javax-server`?

 <groupId>org.eclipse.jetty.ee8.websocket</groupId>
  <artifactId>jetty-ee8-websocket-javax-server</artifactId>
    <version>12.0.9</version>
