### ISSUE TITLE
Connection abruptly closed for HEAD requests

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1185]
Trying to send a HEAD request to a Jetty 9.4.0 server results in the connection being abruptly closed without a response.

**Comment by gregw** [comment]
We really need a unit test that should have detected this problem.

**Comment by joakime** [comment]
Note: any such unit test must perform HEAD request against a Servlet to trigger this condition.  (Using Handlers or Filters will not trigger this issue)

**Comment by sbordet** [comment]
The tests were added in 9.3.x in 3e42b68, where they passed, and so 8cafca7 only shows the fix for 9.4.x.
