### ISSUE TITLE
SecureRequestCustomizer() for HTTP3 

### ISSUE THREAD

**Issue by edgecase14** [eclipse/jetty.project#11855]
**Jetty version(s)**
12.0.9
**Enhancement Description**
I am using this to get SSL client certificate on HTTP1.1/2 server side.  I don't see a way to do this with HTTP3 although mutual TLS auth is working.

**Comment by lorban** [comment]
It should be possible to get the peer's certificate with HTTP3 but this currently isn't exposed.

Thanks for filing this issue, we're going to fix this.

**Comment by sbordet** [comment]
See #11892.
