### ISSUE TITLE
Where can i find SocketConnector .java and BlockingChannelConnector.java etc?

### ISSUE THREAD

**Issue by CaoTianze** [eclipse/jetty.project#1186]
**I read _The Definitive Reference（Version: 9.4.1-SNAPSHOT）_. In _Chapter 30. Architecture_ , there have a text discribed as follow:**
> SocketConnector –for few busy connections or when NIO is not available
> BlockingChannelConnector –for few busy connections when NIO is available
> SelectChannelConnector –for many mostly idle connections or asynchronous handling of Ajax requests
> SslSocketConnector –SSL without NIO
> SslSelectChannelConnector –SSL with non blocking NIO support
> AJPConnector –AJP protocol support for connections from apache mod_jk or mod_proxy_ajp

**But ,i can't find these java files in source code(Version: 9.3.14.v20161028).
I only find _ServerConnector.java, NetworkTrafficServerConnector.java_ and _NetworkTrafficSelectChannelConnector.java_.
Can someone give me a link**

**Comment by sbordet** [comment]
That section of the documentation is outdated and still refer to Jetty 8.x.

In Jetty 9.x the connector architecture has completely changed, and it's entirely based on `ServerConnector`.

We will take are of updating the documentation.
