### ISSUE TITLE
Remove old documentation resources.

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#11877]
**Jetty version(s)**
Jetty 10, 11, 12, 12.1

**Enhancement Description**
We need to clean up the leftovers from the documentation migration to Antora.

documentation/jetty-asciidoctor-extensions/*
documentation/jetty-documentation/*

The complete removal of these directories should be enough.

**Comment by mojavelinux** [comment]
This appears to be done.

**Comment by joakime** [comment]
Closing as complete
