### ISSUE TITLE
GzipHandler switches response transfer encoding to chunked 

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#11882]
**Jetty version(s)**
12.0.10

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
With Jetty 12, when the content is large enough and the client accepts gzip, GzipHandler always sends the response in chunked mode. This seems reasonable, but we have clients that cannot read chunked responses. So at the moment, we cannot find a way to send a gzipped response that is not chunked. The workaround is to not use GzipHandler at all.

This was different in Jetty 11.
Would it be possbile to introduce a setting for controlling this behavior, at least when all the content is known upfront and written synchronously?

This is probably related to #2912.

**How to reproduce?**
```java
var server = new Server();
var connector = new ServerConnector(server);
connector.setPort(8080);
server.addConnector(connector);
server.setHandler(new GzipHandler(new Handler.Abstract() {
    @Override
    public boolean handle(org.eclipse.jetty.server.Request request, Response response, Callback callback) {
        String content = """
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore\s
            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\s
            aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\s
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in\s
            culpa qui officia deserunt mollit anim id est laborum.
            """.repeat(10_000);
        Content.Sink.write(response, true, content, callback);
        return true;
    }
}));
server.start();
server.join();
```

The above snippet starts a Server that exposes an endpoint at http://localhost:8080, that returns a large text (10,000 lorem ipsums) as gzip. The response is sent in chunked mode. If the custom handler is not wrapped in a GzipHandler (or if the content is small enough), the response is not sent in chunked mode.

**Comment by joakime** [comment]
> but we have clients that cannot read chunked responses

You know that all HTTP/1.1 applications MUST be able to read chunked responses right?
This has been a non-optional requirement since 1997.
Your problematic clients are so far out of spec it's silly.

See: https://www.rfc-editor.org/rfc/rfc2068.html#section-3.6 (last paragraph)

```
   All HTTP/1.1 applications MUST be able to receive and decode the
   "chunked" transfer coding, and MUST ignore transfer coding extensions
   they do not understand. 
```

Even the up to date HTTP/1.1 spec says the same thing.
https://datatracker.ietf.org/doc/html/rfc9112#section-7.1

```
   A recipient MUST be able to parse and decode the chunked transfer coding.
```

Also note that Jetty 11 and Jetty 12 handle fundamental IO differently.

**Comment by joakime** [comment]
You'll want a custom `Handler.Wrapper` before `GzipHandler` that looks for the unique signature of those out of spec HTTP clients and strip the `Accept-Encoding` request header from those requests before it hits `GzipHandler`.

**Comment by mperktold** [comment]
No I didn't know that, but I was surprised that not being able to read chunked content is a thing.
Wow, this is silly indeed.

So you suggest to simply not use gzip with clients that do not support chunked, right? A custom handler for that is a good idea, thanks.

OK, I see there is no point in avoiding chunked content just to please ancient clients.

**Comment by gregw** [comment]
Note that if you wish to avoid chunked responses with http 1.1 you can add a connection : close header. However this can have a cost if a new connection is needed for subsequent requests
