### ISSUE TITLE
Cannot --add-to-start=logback-access due to logback-core dependancy

### ISSUE THREAD

**Issue by dresken** [eclipse/jetty.project#1188]
sudo /usr/bin/java -jar $JETTY_HOME/start.jar --add-to-start=logback-access
ERROR : No module found to provide logback-core for logback-access{enabled}

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information

------------------------
sudo vim $JETTY_HOME/modules/logback-access.mod 
....
[depend]
server
logback-core
resources
....

------------------------
I'm not entirely sure about how this all hangs together - "logback-impl.mod" appears to install the logback-core.jar - and it works if I change the dependancy from logback-core to logback-impl

**Comment by WalkerWatch** [comment]
@dresken I believe this is just a bug via a typo as there is no `logback-core` module. Using `logback-impl` is correct.

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch can this be closed then?

**Comment by WalkerWatch** [comment]
@jmcc0nn3ll Yup, please close
