### ISSUE TITLE
Type Mismatch between OpenIdAuthenticator and Authenticator in Jetty 12 EE9

### ISSUE THREAD

**Issue by Emilyserap** [eclipse/jetty.project#11899]
**Jetty Version**
12.0.x
**Jetty Environment**
ee9
**Java Version**
17
**Question**
I am migrating my project to Jetty 12 EE9 and encountering a type mismatch issue between OpenIdAuthenticator and Authenticator. Below is the code implementation causing the issue:

```
import org.eclipse.jetty.ee9.nested.ServletConstraint;
import org.eclipse.jetty.ee9.security.Authenticator;
import org.eclipse.jetty.ee9.security.ConstraintMapping;
import org.eclipse.jetty.ee9.security.ConstraintSecurityHandler;
import org.eclipse.jetty.security.openid.OpenIdAuthenticator;
import org.eclipse.jetty.security.openid.OpenIdConfiguration;
import org.eclipse.jetty.security.openid.OpenIdLoginService;
public class OpenIdSecurityHandler extends ConstraintSecurityHandler
{
		public OpenIdSecurityHandler(String realm, String provider, String clientId, String clientSecret)
	{
		super();
	
		OpenIdConfiguration openIdConfig = new OpenIdConfiguration(provider, clientId, clientSecret);
		OpenIdLoginService loginService = new OpenIdLoginService(openIdConfig);
		Authenticator authenticator = new OpenIdAuthenticator(openIdConfig, "/error?error=Authentication");

		setRealmName(realm);
		setLoginService(loginService);
		setAuthenticator(authenticator);
```

**Error**
 Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	Type mismatch: cannot convert from OpenIdAuthenticator to Authenticator

 How can i fix that please??

**Comment by lachlan-roberts** [comment]
There is some EE9 specific classes for OpenID, try using the `org.eclipse.jetty.ee9.security.openid.OpenIdAuthenticator` class.

you will need a dependency on org.eclipse.jetty.ee9:jetty-ee9-openid

**Comment by Emilyserap** [comment]
okay thanks
