### ISSUE TITLE
Aggregate all webapp configuration exceptions together

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#119]
migrated from Bugzilla [#412719](https://bugs.eclipse.org/bugs/show_bug.cgi?id=412719)
status ASSIGNED severity _minor_ in component _server_ for _9.0.x_
Reported in version _9.0.3_ on platform _All_
Assigned to: Jan Bartel

On 2013-07-10 18:00:40 -0400, Joakim Erdfelt wrote:

> The webapp configuration process should collect all of the various configuration errors and exceptions together and report them all before failing the deployment of the webapp.
> 
> Such as bad entries in the web.xml or
> Annotation scanning errors (such as bad expectations when an annotation is encountered)
> 
> Ideally, these errors should be ...
> - Reported to logging
> - Captured internally for reporting to JMX
> 
> I see something like a DeployErrorListener or DeployListener that could be configured via the DeploymentManager, which adds it to the WebAppContext before starting/configuring it.

On 2013-07-10 18:01:02 -0400, Joakim Erdfelt wrote:

> Assigned to Jan

On 2013-07-10 18:01:46 -0400, Joakim Erdfelt wrote:

> Idea / Brainstorming.
> 
> If we use the DeployListener approach, then the default implementation simply logs the errors via the Jetty Logger.

**Comment by janbartel** [comment]
Closing.
