### ISSUE TITLE
Update pom.xml and configure.dtd locations

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#11917]
The pom.xml files should point to the home jetty website at https://jetty.org and we should update the configure.dtd locations to point to https://jetty.org/configure.dtd as well.

I suspect since we still see releases of jetty 9, 10, 11, and 12 we should make those changes everywhere?

**Comment by 08AHAD** [comment]
@jmcc0nn3ll I would like to work on this isuue, and might you please explain the issue further do I have to automate the changes if I have to update multiple files or just I have to do it manually.

**Comment by joakime** [comment]
This is done for 9.4.x, 10.0.x, 11.0.x, 12.0.x, and 12.1.x branches.
