### ISSUE TITLE
Jetty 9.2.20.v20161216 missing dependencies in maven repo

### ISSUE THREAD

**Issue by giantninja** [eclipse/jetty.project#1192]
I went to test out Jetty 9.2.20.v20161216, and I noticed that it seems like it's not in the main maven repository.  Is that a mistake, or is there a reason for that?

seems like it stops at 9.2.19: 

[jetty-server](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server) (maven repo link)
[jetty-servlets](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-servlets) (maven repo link)

Has that version not made it's way to the main repository yet?

**Comment by jmcc0nn3ll** [comment]
It is still syncing into maven central, give an an hour or two I suspect

**Comment by jmcc0nn3ll** [comment]
looks like central is having some issues, I reverted the download links on the download site back to 9.2.19 and will update them once things are in central

**Comment by giantninja** [comment]
awesome, thanks!

**Comment by jmcc0nn3ll** [comment]
looks like it is in central now, updating website now
