### ISSUE TITLE
Jetty client request origin

### ISSUE THREAD

**Issue by sxam** [eclipse/jetty.project#1193]
Hi guys,
Still trying to transfer to Jetty Http client. There seems to be some problem with one of the flows, both in HTTP/1.1 and HTTP/2 clients. The thing is that at first it seems like an applicative problem but now I am in doubt. While calling https://api.facebook.com/method/user.register Facebook api after couple of hours (not at first, only after some time!) I start to receive in part of my requests (only in part) weird error "An error has occurred while merging pages. This may be caused by your attempt to merge too many pages.". Now, I am still in the process of figuring out from the Facebook side but it could be some rate limitation. The strange thing is that with OkHttp (HTTP/1.1) client I definitely don't encounter this problem, so it's transfer to Jetty which is the cause. I compared Headers and Parameters and everything seems the same. So my question is very vague - is there something that Jetty adds that could made Facebook to think that requests come from the same origin or something like that? What could be the reason for OkHttp requests pass some rate checks while Jetty requests don't? And another thing - there isn't any retry in Jetty, right? (that could automatically retry failed requests)

**Comment by joakime** [comment]
Do you have any reproduction cases?

**Comment by sxam** [comment]
No, couldn't reproduced it from my machine. Happens sometimes on production, but happens regularly.  Any ideas what to look for?

**Comment by sbordet** [comment]
@sxam The first thing to look for is the error you get. Jetty does not have any concept of "page", nor "merging pages". What does that error mean ? When does it happen ? If you can figure that out we can reason about other things.

There is no automatic retry for failed requests in Jetty `HttpClient`.

Could be that Jetty `HttpClient` is better at reusing the same connection to send requests, rather than using different connections ?

**Comment by sxam** [comment]
@sbordet Yes, of course "merging" errors are not directly come from Jetty or from HTTP/2 protocol. But that is the result of a transfer between OkHttp and Jetty. So I am trying to understand the possible reason. Can server somehow understand that the Jetty uses the same connection? (perhaps he thinks we spamming him, passing some api rate limit for same connection or something).

**Comment by sbordet** [comment]
@sxam from googling around it seems either a permission issue, or a throttling issue.
Is there any information (HTTP header, perhaps) in the responses about whether they were throttled or not ?

**Comment by sxam** [comment]
The problem was solved. The difference was due to the default Cookie mechanism which is different between OkHttp and Jetty. Sorry for the false alarm.
