### ISSUE TITLE
Consider re-introducing `ByteBufferPool.NON_POOLING` constant

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#11956]
**Jetty version(s)**
12.1.x

**Enhancement Description**
The constant `ByteBufferPool.NON_POOLING` pool has been replaced with new instances of the non-pooling pool everywhere it was used. We should consider re-introducing this constant.

See: #11801

**Comment by gregw** [comment]
@lorban I thought I'd done this ... oh I have now!
