### ISSUE TITLE
Problem using STOP.PORT and STOP.KEY with --exec

### ISSUE THREAD

**Issue by jmcmaster2000** [eclipse/jetty.project#1195]
Hello, I recently upgraded my Jetty platform from 9.3.14 to 9.4.0 and now have a problem in using the STOP.PORT/KEY parameters.  Jetty is no longer binding to the STOP.PORT and listening for shutdown requests.  After investigating this further it seems to occur after I add the log4j logging module to the start.d configuration.

To re-create the issue, try the following steps:

(1) Confirm it is working with the default out-of-the-box demo-base

cd ${jetty.home}/demo-base
java -jar ../start.jar STOP.PORT=9999
netstat -an | grep 9999

You should see that Jetty is now listening on port 9999.  Stop the server.

(2) Now, add the log4j infrastructure and restart the server.

cd ${jetty.home}/demo-base
java -jar ../start.jar --add-to-start=logging-log4j --create-files --approve-all-licenses
java -jar ../start.jar STOP.PORT=9999
netstat -an | grep 9999

You should see that Jetty is NOT listening on port 9999.

Thank-you,
Joe

**Comment by janbartel** [comment]
I tested adding a different logging impl (slf4js-simple-impl) and the stop port was listening. Investigating how log4j is involved in this.

**Comment by janbartel** [comment]
Turns out log4j module was doing an exec, and we didn't set the STOP.PORT,STOP.KEY,STOP.WAIT props on the exec'ed jetty instance. Fixed in jetty-9.4 and cherry-picked back to jetty-9.3. I assume this used to work for you in jetty-9.3 because we weren't exec'ing with the log4j module.

**Comment by joakime** [comment]
@janbartel i see STOP.KEY, STOP.PORT, STOP.WAIT in that commit, but what about STOP.HOST ?

**Comment by jmcmaster2000** [comment]
Hi @janbartel, thank-you for investigating and determining the root cause.  To answer your question, yes it has always worked fine in the 9.3 stream.

**Comment by janbartel** [comment]
@joakime we never do an exec on a --stop command, so the STOP.HOST property does not need to be copied into system properties, and more-over, is never looked for within the system properties (only the command line properties).
