### ISSUE TITLE
WebSocketClient not sending `Authorization` request header

### ISSUE THREAD

**Issue by aiyanbo** [eclipse/jetty.project#1197]
```scala
val request = new ClientUpgradeRequest()
request.setHeader(HttpHeaders.AUTHORIZATION, s"Sign SHA1 $sign")
client.connect(endpoint, uri, request).get()
```
The `AUTHORIZATION` header cannot send to server.

`9.3.14.v20161028` is work

**Comment by joakime** [comment]
In Jetty 9.4.0, the WebSocketClient has changed from using its own HTTP client library to using the jetty-client library for all of the HTTP specific bits.  Authorization is 100% in the HTTP side of things (not websocket).

Client authorization will definitely work if using the HttpClient specific authorization techniques.

Supporting authorization header using the ClientUpgradeRequest should be supported, I consider this broken support a regression.
