### ISSUE TITLE
Install jenkins flaky test plugin

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#11981]
We still have many [flaky tests](https://github.com/jetty/jetty.project/labels/flaky-test).
We should install the [Jenkins Flaky Test Handler](https://plugins.jenkins.io/flaky-test-handler/) to understand better which tests are flaky and which are not.   We can then make hunting down those flaky tests a higher priority.

**Comment by olamy** [comment]
Started some work:
- setup `rerunFailingTestsCount` to 1 (if test failure the test is retry once) https://github.com/jetty/jetty.project/pull/11985
- setup Jenkins plugin https://github.com/jetty/jetty.project/pull/11984 
- setup launchable (https://www.launchableinc.com/docs/features/unhealthy-tests/) to collect data https://github.com/jetty/jetty.project/pull/11983

**Comment by olamy** [comment]
done
