### ISSUE TITLE
Jetty 9 migration to Jetty 12: BASIC AUTH

### ISSUE THREAD

**Issue by alan-vos** [eclipse/jetty.project#11998]
**Jetty Version**
12.0.10

**Jetty Environment**
ee10
 
**Java Version**
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)

**Question**
Apologies for the simple question ... I looked in many places to find this answer without a working solution.

This code used to work in 9.4.x (latest)

```
        // I believe this is the new way, however, untested
        final HashLoginService loginService;
        try (final ResourceFactory.Closeable rf = ResourceFactory.closeable()) {
            loginService = new HashLoginService(REALM_NAME, rf.newResource(Paths.get("users.properties")));
        }
        
       // This was the 9.4.x way and this code does not work (or compile) 
       final Constraint constraint = new Constraint();
       constraint.setName(Constraint.__BASIC_AUTH);
       constraint.setAuthenticate(true);
       constraint.setRoles(new String[]{Constants.ROLES});
```        

Can someone please provide me a working example code snippet or test?

**Comment by joakime** [comment]
The BasicAuthenticatorTest can show you a few ways to implement the SecurityHandler rules.

https://github.com/jetty/jetty.project/blob/c8b3373bbc9a309eec5b6e86d86148a7db20d552/jetty-core/jetty-security/src/test/java/org/eclipse/jetty/security/BasicAuthenticatorTest.java#L87-L102

But for the HashLoginService, you cannot use the closable ResourceFactory like that, as the resource itself cannot be closed until that HashLoginService is completely done doing what it needs to do (and it can hot reload too)

Use a ResourceFactory tied to the lifecycle of your Server.

``` java
ResourceFactory resourceFactory = ResourceFactory.of(server);
Resource hashConfig = resourceFactory.newResource(Paths.get("users.properties"));
if (!Resources.isReadableFile(hashConfig))
    throw new IOException("Unable to open users.properties: " + hashConfig);
HashLoginService loginService = new HashLoginService(REALM_NAME, hashConfig);

// ... some time later ...
server.start();
```

**Comment by alan-vos** [comment]
Thank you for the clarification.  It looks like my searchs lead me astray.  I hope this code helps others as well.

**Comment by janbartel** [comment]
Looks like we've answered the original question so I'll close this issue.
