### ISSUE TITLE
Restore `jetty-p2` for Jetty 12.0.x

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#12007]
**Jetty version(s)**
12.0.x

**Enhancement Description**

Looks like the `jetty-p2` module was dropped during the work for Jetty 12.0.x.

Should we restore it?

We'll need to lean on @laeubi to understand how to make it work for our Environments (ee10, ee9, ee8), where the same maven coordinates exist under different versions.

**Comment by laeubi** [comment]
@joakime if you can explain what are the problem with the p2 module I'm here to help :-)

**Comment by janbartel** [comment]
@laeubi I'm not sure there's a problem per se, just we aren't experts so don't really know what we're doing with it :)  When we moved to jetty-12, we probably decided to leave `jetty-p2` out as the fastest route to getting on with our new software structure.  We now have different sub-modules for each of the eeX variants of the servlet spec, but all in a single repository. So we have `jetty-core` which is spec- independent artifacts, then `jetty-ee8`, `jetty-ee9`, jetty-ee10` and soon `jetty-ee11` with jetty artifacts appropriate for each spec. I guess what we really need is:

- to know if  `jetty-p2` still useful to people?
- if so, someone with expertise to take it on and update it to jetty-12

**Comment by laeubi** [comment]
I assume the spec dependent artifacts are just different jar with different names? In this case I don't see much of a problem here to enable it again, if there is still interest I can take a look at it. The main consumer of this is mostly eclipse platform but also others as in the past often people have consumed this from there and then complained that a specific artifact was missing, so it was good to have a site that contains everything.

**Comment by olamy** [comment]
not sure about what is the problem?
I have created a PR to restore the jetty-p2 module here https://github.com/jetty/jetty.project/pull/12015

**Comment by joakime** [comment]
> I assume the spec dependent artifacts are just different jar with different names? In this case I don't see much of a problem here to enable it again, if there is still interest I can take a look at it. The main consumer of this is mostly eclipse platform but also others as in the past often people have consumed this from there and then complained that a specific artifact was missing, so it was good to have a site that contains everything.

@laeubi I was worried about our different versions of the same maven coordinates.

But looking at [the generated output](https://github.com/jetty/jetty.project/pull/12015#issuecomment-2217897639) ([`artifacts.xml` snippets](https://github.com/jetty/jetty.project/pull/12015#issuecomment-2217891260) and [`content.xml` snippets](https://github.com/jetty/jetty.project/pull/12015#issuecomment-2217893403)) from PR #12015 I see that's not much of a worry.

Is that going to work for tycho-p2 ok?

**Comment by olamy** [comment]
done via https://github.com/jetty/jetty.project/pull/12015
