### ISSUE TITLE
X-Forwarded-For incorrectly set in jetty-http-forwarded.xml

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1201]
A cut and paste error in `jetty-http-forwarded.xml` incorrectly sets the `X-Forwarded-For` to `X-Proxied-Https`

**Comment by astralblue** [comment]
The same error is also seen in 9.3.17.

**Comment by gregw** [comment]
Doh!

**Comment by gregw** [comment]
fixed in 9.3 (pity we just missed release)
