### ISSUE TITLE
There is no org.eclipse.jetty.http2.client package in official  jetty-12.0.11 download

### ISSUE THREAD

**Issue by Quantum2Bits** [eclipse/jetty.project#12027]
**Jetty version(s)**

**Jetty Environment**

**Java version/vendor** `(use: java -version)`

**OS type/version**

**Description**

In official download jetty-home-12.0.11 (also 12.0.10), there is no package org.eclipse.jetty.http2.client, as well packages org.eclipse.jetty.http2.client.transport, org.eclipse.jetty.http3.client, org.eclipse.jetty.http3.client.transport, and org.eclipse.jetty.quic.client

I download the source files, and manually compile theses packages. It works.

**How to reproduce?**

**Comment by sbordet** [comment]
`jetty-home` provides Jetty as a standalone server, so typically the artifacts you refer to are not necessary in a server.

There is no need to download the source files and compile them, as they are available in Maven Central, so it is enough to add the dependencies and they will be downloaded.

Can you detail your use case, where you need those packages in a server environment?

**Comment by Quantum2Bits** [comment]
I find the client jar files in Maven Central. Thank you.

I am try to improve the jetty proxy. The new proxy has a local part and a remote part. The remote part can only accept http request. it may prefer http/2 or http/3.

**Comment by joakime** [comment]
Closing as answered

**Comment by sbordet** [comment]
@joakime perhaps we should consider to add at least HTTP/2 client artifacts to `jetty-home`, given that the `jetty-client` is there.

In this way proxy apps can get the HTTP/2 classes provided by the server -- if we do it for HTTP/1, why not HTTP/2?

For HTTP/3 I would not bother, because it is experimental and not really well suited for a proxy.

**Comment by gregw** [comment]
@sbordet rather than always include them in the download, can we just have a module that downloads the http2 client jars and dependencies?
