### ISSUE TITLE
HttpSessionBindingListener#valueUnbound not called consistently in 9.4.0

### ISSUE THREAD

**Issue by silviobierman** [eclipse/jetty.project#1203]
After session creation an instance of a class that implements HttpSessionBindingListener is set as an attribute on the HttpSession instance.
After porting my application from 9.3.13 to 9.4.0 valueUnbound is no longer called on the attribute when HttpSession#invalidate is called. It is however called when the session times out. Reverting to 9.3.13 solves the issue.

**Comment by janbartel** [comment]
Bug fixed and test case added for this in jetty-9.4.x. Thanks.
