### ISSUE TITLE
SecurityManager prevents JSP from loading

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1205]
As reported in jetty-dev : https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02857.html

When a SecurityManager is active, the Apache Jasper implementation cannot load due to a missing class.

```
org.apache.jasper.runtime.JspRuntimeLibrary$PrivilegedIntrospectHelper
```

A check of our jar shows ...

``` shell
$ jar -tvf ~/.m2/repository/org/mortbay/jasper/apache-jsp/8.5.5/apache-jsp-8.5.5.jar | grep Privileged
  1772 Thu Oct 27 16:03:32 MST 2016 org/apache/jasper/runtime/JspFactoryImpl$PrivilegedGetPageContext.class
  1091 Thu Oct 27 16:03:32 MST 2016 org/apache/jasper/runtime/JspFactoryImpl$PrivilegedReleasePageContext.class
   772 Thu Oct 27 16:03:32 MST 2016 org/apache/tomcat/util/security/PrivilegedGetTccl.class
   868 Thu Oct 27 16:03:32 MST 2016 org/apache/tomcat/util/security/PrivilegedSetTccl.class
```

And a check of the official apache jasper jar shows ...

``` shell
$ jar -tvf ~/.m2/repository/org/apache/tomcat/tomcat-jasper/8.5.5/tomcat-jasper-8.5.5.jar | grep Privileged
  1772 Wed Aug 31 20:51:46 MST 2016 org/apache/jasper/runtime/JspFactoryImpl$PrivilegedGetPageContext.class
  1091 Wed Aug 31 20:51:46 MST 2016 org/apache/jasper/runtime/JspFactoryImpl$PrivilegedReleasePageContext.class
```

**Comment by joakime** [comment]
Note: not even the newest Apache Jasper jar has that missing file.

``` shell
$ jar -tvf tomcat-jasper-9.0.0.M15.jar | grep Privil
  1772 Mon Dec 05 13:44:50 MST 2016 org/apache/jasper/runtime/JspFactoryImpl$PrivilegedGetPageContext.class
  1091 Mon Dec 05 13:44:50 MST 2016 org/apache/jasper/runtime/JspFactoryImpl$PrivilegedReleasePageContext.class
```

**Comment by joakime** [comment]
Note: The source for Jasper 8.5.5 is also missing this `PrivilegedIntrospectHelper` sub-class

http://svn.apache.org/viewvc/tomcat/tc8.5.x/tags/TOMCAT_8_5_5/java/org/apache/jasper/runtime/JspRuntimeLibrary.java?revision=1772784&view=markup

**Comment by joakime** [comment]
Bug on Apache Jasper side - https://bz.apache.org/bugzilla/show_bug.cgi?id=60101

Looks like Apache Jasper 8.5.6 had a release with the following commit (that seems to address this)

apache/tomcat85@865e067f1f513ea0f5b876a89c7b8ff6cefedd7c

**Comment by janbartel** [comment]
I've opened a CQ with Eclipse to allow us to update to 8.5.9.

**Comment by SkateScout** [comment]
An update to 8.5.9 would be great if it is fixed there.
Another solution would to simply take the FiX mentioned in the commit
BUG-60101: Remove preloading of the class that was deleted. And backport it
to the supplied classes in jetty.
a)
-            loader.loadClass( basePackage +
-                "runtime.JspRuntimeLibrary$PrivilegedIntrospectHelper");
 b) 
-              factory.getClass().getClassLoader().loadClass( basePackage +
-                        "runtime.JspRuntimeLibrary$PrivilegedIntrospectHelper");

**Comment by janbartel** [comment]
See #1271

**Comment by janbartel** [comment]
#1271  apache jasper 8.5.9 upgrade checked in for next release of jetty-9.4.
