### ISSUE TITLE
Introduce Jetty module for HTTP/2 client dependencies

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#12063]
**Jetty version(s)**
12

**Jetty Environment**
core

**Description**
When a web application is proxying and wants to use HTTP/2, it may need to have the HTTP/2 client dependencies provided by the server, rather than the webapp.

There currently is no module for HTTP/2 client, while there is for HTTP/1.

Following the suggestion from #12027, this new Jetty module should download the dependencies on-the-fly.

**Comment by joakime** [comment]
We have a `client` module already.
What would you call this new module? `http2-client` perhaps? (same for `http3-client`?)
What libs would you put in it?
