### ISSUE TITLE
WebSocket upgradeRequest.getCookies() returns empty list despite upgradeRequest.getHeaders() contains "Cookie"

### ISSUE THREAD

**Issue by lglowania** [eclipse/jetty.project#12076]
**Jetty version(s)**
12.0.11
**Jetty Environment**
ee10
**Java version/vendor** `(use: java -version)`
21
**OS type/version**
Debian Bookworm
**Description**

```java
    @Override
    public void onWebSocketOpen(Session session) {

        super.onWebSocketOpen(session);

        UpgradeRequest upgradeRequest = session.getUpgradeRequest();

        Map<String, List<String>> headers = upgradeRequest.getHeaders();

        List<String> cookie = headers.get("Cookie");
        System.out.println("Cookie-Header: " + cookie);
        // prints Cookie-Header: [fontSize=120%; theme=dar; SdkTestSID=node01m22j8bu2edb9e32icuebltcs0.node0]

        List<HttpCookie> cookies = upgradeRequest.getCookies();
        System.out.println("Cookie-List: " + cookies);
        // prints Cookie-List: []
```

**How to reproduce?**
The WebSocket setup is embedded mode with using `JettyWebSocketServletContainerInitializer.configure(context, null);` and extending `org.eclipse.jetty.ee10.websocket.server.JettyWebSocketServlet` for registering the WebSocket.

**Comment by joakime** [comment]
Accessing HTTP level components AFTER the HTTP layer has ended has always been a problem (and it's not unique to Jetty or Servlet).
If you are being called at `onWebSocketOpen()` you are technically no longer in HTTP, you are past HTTP and are upgraded to WebSocket.
The `HttpServletRequest` (an HTTP component) is very likely already recycled and rendered invalid by the time you call it here.  
The `UpgradeRequest` object you see will sometimes have the barest of basics still accessible (usually in the form of method, URIs, headers, etc), but not always.
The `HttpServletRequest.getCookies()` is a product of Servlet handling of Cookies, and only functions as long as the `HttpServletRequest` is valid.

If you want to carry over HTTP level details to WebSocket reliably, you need to do it during the Upgrade process.
The Upgrade process is the stage where HTTP still exists, and you are making the call on what details from HTTP you need, and what details from the HTTP Upgrade request to WebSocket should result in what WebSocket endpoint. (or error, or auth failure, etc)
For Jetty's WebSocket API, that means a Creator, such as `org.eclipse.jetty.ee10.websocket.server.JettyWebSocketCreator` which is registered against the `org.eclipse.jetty.ee10.websocket.server.JettyWebSocketServletFactory` in its `addMapping(String, JettyWebSocketCreator)` or `setCreator(JettyWebSocketCreator)` methods.

It is at this point in time, when you can get all kinds of information from the HTTP level, and put them into your WebSocket endpoint instance return from the `JettyWebSocketCreator.createWebSocket(JettyServerUpgradeRequest req, JettyServerUpgradeResponse resp)`.

**Comment by lglowania** [comment]
ok, for now i'm parsing the cookie-header manually to get the required infos. Thanks.

**Comment by joakime** [comment]
> ok, for now i'm parsing the cookie-header manually to get the required infos. Thanks.

If you are still doing that in `onWebSocketOpen(Session session)`, then that is an unreliable solution.
It is very easy to have even the `headers.get(String)` calls all return null as the `HttpServletRequest` was fully recycled.
The fact that it's working for you is just lucky timing of your call in relation to the HTTP request recycle.
