### ISSUE TITLE
HttpSession lastAccessedTime and isNew not getting updated

### ISSUE THREAD

**Issue by Horcrux7** [eclipse/jetty.project#12070]
**Jetty version(s)**
12.0.11

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

**OS type/version**
Windows 10 and Windows 11

**Description**
In our environment the value of the `HttpSession.getLastAccessedTime()` is always identical to `HttpSession.getCreationTime()`. Also the value of `HttpSession.isNew()` returns always `true`.

The `getId()` and the `hashCode()` does not change between different HTTP request. This means the session cookie was send and received correctly. It was not a new session.

The requests are HTTP1/1 POST requests.

Attached is JettyServer Dump:
[jettydump.txt](https://github.com/user-attachments/files/16334501/jettydump.txt)

**Comment by janbartel** [comment]
Looking into this.

**Comment by janbartel** [comment]
Fixed via #12078
