### ISSUE TITLE
WebSocketPolicy configuration inconsistent when using JSR

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1207]
Applications that use JSR 356 call `ContainerProvider.getWebSocketContainer()` that creates a `ClientContainer`.

`ClientContainer` creates a `SimpleContainerScope`, which owns a `WebSocketPolicy` object.
`ClientContainer` also creates a `WebSocketClient` that also owns a (different) `WebSocketPolicy` object.

When applications call, for example, `WebSocketContainer.setDefaultMaxTextMessageBufferSize()`, the implementation delegates to `WebSocketClient`, modifying its `WebSocketPolicy`.

When a connection is created by the client, `WebSocketUpgradeRequest` creates an `EventDriver` (field `localEndpoint` that uses a `WebSocketPolicy` from the `EventDriverFactory` which in turn received it from from the `SimpleContainerScope`.

Because there are 2 `WebSocketPolicy` instances, configurations made by the application onto `WebSocketClient` are "lost" because the wrong instance (that of the `SimpleContainerScope`) is being used.

There must be only one `WebSocketPolicy` object.

**Comment by joakime** [comment]
This is correct.  One policy is for the server scope.  The other is for the client scope.  

The call ContainerProvider.getWebSocketContainer() must create both.

**Comment by sbordet** [comment]
It's not correct. The client has 2 `WebSocketPolicy` instances, one in `WebSocketClient`, one in the `EventDriver` that creates connections.

CometD tests with Jetty 9.4.x fail when the test configures a large max message size, and then sends a large message, exactly because there are 2 `WebSocketPolicy` instances, and only one is configured with the large max message size. It was working with Jetty 9.3.x.

**Comment by joakime** [comment]
Corrected in commit 941f063 and the merge 487748c
