### ISSUE TITLE
No jetty-core API to determine if sessionId is obtained from cookie or URL

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#12088]
**Jetty version(s)**
12.0.x

**Jetty Environment**
core

**Description**
In the servlet API there is the methods `isRequestedSessionIdFromCookie()` and `isRequestedSessionIdFromURL()` on `HttpServletRequest`. 

However it does not seem possible to determine this from jetty-core.

**Comment by janbartel** [comment]
Should be easy enough to implement this in the `org.eclipse.jetty.session.SessionHandler.SessionRequest` class, and add it to the `org.eclipse.jetty.server.Request` interface. The information is available to the `SessionRequest`, just a matter of exposing it.

**Comment by janbartel** [comment]
This was fixed by #12145
