### ISSUE TITLE
the content of element type "configure" must match "(Id?,Class?,Arg*,(Set|Get|Put|Call|New|Ref|Array|Map|Property)*)"

### ISSUE THREAD

**Issue by fgolzari** [eclipse/jetty.project#12099]
**Jetty Version**
12
**Jetty Environment**
ee10
**Java Version**
21
**Question**
Jetty gives this error:  `the content of element type "configure" must match "(Id?,Class?,Arg*,(Set|Get|Put|Call|New|Ref|Array|Map|Property)*)"`,  while deploying the project ,while parsing jetty.xml file

**Comment by joakime** [comment]
That's a standard Xml Schema error telling you the structure of your XML is invalid per the schema.

Double check the syntax and structure of the XML being referenced in the stacktrace for that and correct the mistakes.

**Comment by fgolzari** [comment]
@joakime Thank you very much for your guidance.
That previous issue was resolved. now  while deploying the project ,while parsing jetty.xml file, it gives `classNotFoundException:org.eclipse.jetty.ee10.webapp.WebAppContext` class. 
When I search in the log of jetty, I see `ee10-webapp` jar file, loaded in class path. Why does this error happen?

**Comment by sbordet** [comment]
@fgolzari you have another issue now, so please open a new issue.
Also, likely it is a problem in your configuration, so in the new issue please add as many details as possible about your configuration.
