### ISSUE TITLE
Using symmetric key(tls-psk) to configure SSL on Jetty

### ISSUE THREAD

**Issue by efajk** [eclipse/jetty.project#1210]
I used this [embedded Jetty ](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fequinox%2Fhttp%2Fjetty%2Fpackage-summary.html) for my web server.
I have already successfully used asymmetric keys and certificate to configure SSL on jetty.
Now, I want to used symmetric key to configure SSL on jetty. 
I used keytool to generate the symmetric key by following command:
`keytool -genseckey -alias mykey -keyalg AES -keysize 256 -storetype jceks -keystore mykeystore`
Then, I configure the keystore and its password on jetty.

> org.eclipse.equinox.http.jetty.https.enabled=true
org.eclipse.equinox.http.jetty.https.port=8443
org.eclipse.equinox.http.jetty.ssl.password=password
org.eclipse.equinox.http.jetty.ssl.keypassword= password
org.eclipse.equinox.http.jetty.ssl.keystore=/Users/user/key/mykeystore 
org.eclipse.equinox.http.jetty.ssl.protocol=TLSv1.2

When I use Chrome to connect to the website, the website shows:
**ERR_SSL_VERSION_OR_CIPHER_MISMATCH**
Does Jetty support this way by using symmetric key(tls-psk) to configure SSL?

**Comment by sbordet** [comment]
See also: http://dev.eclipse.org/mhonarc/lists/jetty-users/msg07376.html

**Comment by sbordet** [comment]
I asked to the JDK mailing list as well: http://mail.openjdk.java.net/pipermail/security-dev/2017-January/015384.html

**Comment by joakime** [comment]
Looks like the JVM will support this starting with TLS 1.3

https://bugs.openjdk.java.net/browse/JDK-8049402

Considering that this JVM feature request was created back in 2008 and has had no updates, not sure we should keep this issue open.

**Comment by dain** [comment]
Does this work now with TLS 1.3 in Java 11?

**Comment by dain** [comment]
@joakime, I was more asking about this issue where we have manually pre-shared a key with clients and servers, as opposed to using some kind of PKI infrastructure.

**Comment by sbordet** [comment]
@dain I don't think this is possible yet, see https://bugs.openjdk.java.net/browse/JDK-8049402.

The JDK supports session resumption with PSK, so you have to first open a connection, and then a second connection to the same host and port will be resumed using PSK.

Out-of-band PSK secretly shared between client and server are not supported, as there is no JDK API yet to create a `SSL[Server]Socket` using external cryptographic material, AFAIK.

**Comment by sbordet** [comment]
I believe this issue has been answered, closing it.
