### ISSUE TITLE
Upgrade to ASM Version 6.0_ALPHA for JDK9

### ISSUE THREAD

**Issue by cfiehe** [eclipse/jetty.project#1213]
To be compatible with Java 9, an update of ASM to version 6.0_ALPHA is required.

**Comment by joakime** [comment]
This will require an Eclipse CQ request to use the updated version of ASM.

@janbartel want to get the ball rolling now? (as it can take a few months to get approval), or should we wait for a non-alpha ASM 6.0?

**Comment by janbartel** [comment]
We should wait for non-alpha, and also until apache spy-fly (for osgi) is updated to asm-6.

**Comment by joakime** [comment]
@janbartel asm 6.0 final is now available on maven central.

http://central.maven.org/maven2/org/ow2/asm/asm/6.0/

``` xml
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
    <version>6.0</version>
</dependency>
```

We should also be able to get a PB CQ for this final release via:
 http://dev.eclipse.org/ipzilla/show_bug.cgi?id=14395

**Comment by janbartel** [comment]
I've created a piggyback CQ for ASM 6.0 based off CQ 14348

**Comment by janbartel** [comment]
I've updated asm 6.0 into jetty-9.3.x. jetty-9.4.x and jetty-10(master).

Unfortunately there is no version of apache spifly that supports asm-6.0, so for now, the jetty osgi tests still use asm-5. I've updated the manifests for the jetty-annotations bundle to accept 5 <= asm < 7.
