### ISSUE TITLE
Accepted subprotocol is not provided when @OnWebSocketConnect method is invoked

### ISSUE THREAD

**Issue by violetagg** [eclipse/jetty.project#1214]
Hi,

I'm following the example [1] for Jetty WebSocket Server API.
In my WebSocketCreator implementation I'm setting the accepted subprotocol to the response:

```response.setAcceptedSubProtocol(subprotocol);```

Then in my @WebSocket implementation, I expect in the method annotated with @OnWebSocketConnect when I call the statement below to receive the subprotocol that was set earlier by the WebSocketCreator:

```session.getUpgradeResponse().getAcceptedSubProtocol();```

With the latest available Jetty 9.4.x this call returns "null".

I think that the following line [2] causes this "null" to be returned. When the specified key is not available in the map, the default is returned, but this default is not added to the map.

What do you think?

Best Regards,
Violeta Georgieva

[1] https://www.eclipse.org/jetty/documentation/9.4.x/jetty-websocket-server-api.html
[2] https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeResponse.java#L114

**Comment by violetagg** [comment]
Hi,

I think it is still not fixed.
Here [1] you can find a test case.

Regards,
Violeta

[1] https://github.com/violetagg/jetty.project/commit/debea681e571beeb5165e00fed50b8f0cb3ce1d6

**Comment by joakime** [comment]
Will test your techniques.

**Comment by joakime** [comment]
Pushed a testcase, which replicated the bug, and a fix.

**Comment by violetagg** [comment]
Thanks,
Violeta
