### ISSUE TITLE
jetty12 migration issue

### ISSUE THREAD

**Issue by johmn123-wq** [eclipse/jetty.project#12166]
public class ApacheServerHandler extends Handler.Abstract{

   private ApacheServerHandler(){
       client = HttpClients.createDeafult();
   }

@Override
public void handle(Request request, Response response, Callback callback) throws IOException, ServletException{

  String newHost = request.getHeaders().get('sb_host');
  if(newHost.endsWith("/")){
     newHost  = StringUtils.substring(newHost, 0, newHost.length() - 1);  
   }
 
 HttpUriRequest = null;
 String method = request.getMethod();
 String queryString = request.getHttpURI().getQuery();
 String path = request.getHttpURI().getPath();
 Enumeration<String>headers = request.getHeaders().getFieldNames();

 String newUrl = String.format("http://%s%s", newHost, path, queryString);

 if(HttpMethod.GET.matches(method)){
   uriRequest = new HttpGet(newUrl);
 }
 else if(HttpMethod.POST.matches(method)){
   uriRequest = new HttpPost(newUrl);
 }
 else if(HttpMethod.PUT.matches(method)){
   uriRequest = new HttpPut(newUrl);
 }
 else{
   return true;
 } 

 if(uriRequest instanceof HttpEntityEncloseingRequest){
  HttpEntityEnclosingRequest entityRequest = (HttpEntityEnclosingRequest) uriRequest;
  entityRequest.setEntity(Content.Source.asInputStream(request), 
 ContentType.create(request.getHeaders().get(HttpHeaders.CONTENT_TYPE)));
 }

while(headers.hasMoreElements()){
    String headerName = headers.nextElement();
    if(headerName.equalIgnoreCase('Content-length'))
       continue;
    uriRequest.addHeader(headerName, baseRequest.getHeader(headerName));
}

    try(ClosableHttpResponse resp = client.execute(uriRequest)){
         for(Header header: resp.getAllHeaders){
                response.**add**(header.**getName**(), header.**getValue**());
         } catch(ParseException e){
                throw new IOException(e);
     } 

         String body = EntityUtils.toString(resp.getEntity());
         reponse.write(true, ByteBuffer.wrap(body.getBytes()), callback);

         return false;

 }

**Can you please provide the alternative of this block of code 'response.add(header.getName(), header.getValue())' adding each of these headers to a new HTTP response.**

**HttpEntityEnclosingRequest entityRequest = (HttpEntityEnclosingRequest) uriRequest;
  entityRequest.setEntity(Content.Source.asInputStream(request), 
 ContentType.create(request.getHeaders().get(HttpHeaders.CONTENT_TYPE))); having an issue with method setEntity in interface org.apache.hc.core5.http.httpEntityContainer cannot be applied to given types;
required : org.apache.hc.core5.http.httpEntity
found: java.io.inputStream, org.apache.hc.core5.http.ContetntType
reason: actual and formal aregument lists differ in length.**

Need you assistance here.

_Originally posted by @johmn123-wq in https://github.com/jetty/jetty.project/issues/12158#issuecomment-2289671390_

**Comment by joakime** [comment]
Closing, as the mentioned `org.apache.hc.core5.http.ContetntType` is both not a Jetty class, and it looks like it has a typo.
