### ISSUE TITLE
Java Compatibility Documentation

### ISSUE THREAD

**Issue by kansasSamurai** [eclipse/jetty.project#12167]
**Jetty Version**
see question

**Jetty Environment**

see question

**Java Version**
see question

**Question**
I cannot seem to find documentation on the website about which version of Java is required for which version of Jetty.  This seems like it would be highly valuable.  My apologies if I have overlooked existing documentation but I did browse the online documentation and also attempt to google the information.  What little information was out there was not from the Jetty web site.

**Comment by olamy** [comment]
I agree maybe we could make more easy to find :)
You will have your information here https://jetty.org/download.html#version-history. (column `Min JVM`)

**Comment by kansasSamurai** [comment]
that is perfect.  I think that's a good location but it doesn't come up in searches (and I obviously overlooked it... especially since I installed jetty via sdkman).  I'll close this issue but maybe consider trying to get it to show up in google searches better :)  tyvm
