### ISSUE TITLE
QosHandler suspend queue limit

### ISSUE THREAD

**Issue by LarsKrogJensen** [eclipse/jetty.project#12185]
**Jetty version(s)**
12.0.11

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
java 21.0.3 2024-04-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)

**OS type/version**
Ubuntu  22.04

**Description**
We are using QoSHandler to protect app from being flooded with requests, but had an incident with a combination slow backend  and sudden big increase in requests causing suspend queue to grow without a limit and finally OOM:ed. AWS auto scaling could not scale out quick enough, all instances died.

Suggestion is to have similar limit check to suspended requests as already exists for max active requests to prevent this scenario.

Happy to provide a PR if you consider this a valid feature of QoSHandler.

**Comment by sbordet** [comment]
> Happy to provide a PR if you consider this a valid feature of QoSHandler.

Yes please.

**Comment by LarsKrogJensen** [comment]
PR ready for review

**Comment by sbordet** [comment]
Fixed by #12189.
