### ISSUE TITLE
jetty-start / Add ability to set Environment variables in start.ini when using --exec

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#122]
migrated from Bugzilla [#414007](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414007)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _9.0.4_ on platform _All_
Assigned to: Joakim Erdfelt

On 2013-07-30 09:53:28 -0400, Joakim Erdfelt wrote:

> When using the --exec features of the start.ini, provide a means to set environment variables for the spawned JVM.

On 2014-07-04 10:19:07 -0400, Philippe PRADOS wrote:

> It's possible to add -DXXX but no -DXXX=YYY.

**Comment by joakime** [comment]
Note, to implement this, you would need to be aware of environment variables (such as PATH and LD_LIBRARY), vs jvm variables (like system properties), and set them accordingly.

**Comment by janbartel** [comment]
No progress or votes since 2013, so closing this issue.
