### ISSUE TITLE
PushCacheFilter does not add the context path to pushed resources

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1220]
For an app deployed on `/ctx`, I would have expected `PushBuilder.path("/foo").push()` to push resource `/ctx/foo`, while instead it pushes resource `/foo` which typically yields a 404.

The fix for `PushCacheFilter` is easy, just prepend the context path when calling `PushBuilder.path(String)`.

@gregw However, I wonder if this is really the intended behavior for Servlet 4.0.

`PushBuilder` is obtained from the request object, and used inside a `Filter`, so it has an implicit application scope in the sense that the request is for that application, the filter configured for the application, and the expectation would be that pushed resources also belong to the same application.

However, `PushBuilder.path(String)` explicitly says that if the path starts with `/`, then it's absolute.
I find this confusing, since it forces applications to either prepend the context path every time, even if the `PushBuilder` object is obtained from a request (and therefore knows the context path), or perform some logic to remove the leading `/` to make the path relative.

`PushBuilder` reminds of `RequestDispatcher`, both are obtained from the request object, so I would have expected both to work on paths relative to the context path of the request they were obtained from.

**Comment by gregw** [comment]
See question asked at https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2017-01/message/0
Note however that the current behaviour is similar to `sendRedirect`
