### ISSUE TITLE
Connections Not Terminating After Idle Timeout Despite No Network Traffic

### ISSUE THREAD

**Issue by MohammadNC** [eclipse/jetty.project#12215]
**jettyVersion="11.0.20**

**Java Version = 17**

Hi Team,

I've set the idle timeout to 70 seconds using the following configuration: 
httpClient.setIdleTimeout(70s);

However, during traffic tests, I've observed that connections are not being terminated despite no network activity. Instead, the connections are only terminated after 140 seconds. I've collected Jetty debug logs, which show that a GOAWAY frame is initiated, but the connection still isn't terminated.

Could you please explain what might be happening here and why the connections are not getting terminated as expected? The detailed logs are provided below for your review.
 

30168 {"instant":{"epochSecond":1724941801,"nanoOfSecond":968685792},"thread":"@1f3b992-41","level":"DEBUG","loggerName":"org.eclipse.jetty.io.ManagedSelector","message":"Connected true java.nio.channels.SocketChannel[connected local=/192.168.219.91:39492 remote=/192.168.219.95:8080]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":41,"threadPriority":5,"messageTimestamp":"2024-08-29T14:30:01.968+0000","processId":"1"}

30173 {"instant":{"epochSecond":1724941801,"nanoOfSecond":969026615},"thread":"@1f3b992-42","level":"DEBUG","loggerName":"org.eclipse.jetty.io.IdleTimeout","message":"Setting idle timeout 0 -> 70000 on SocketChannelEndPoint@7c3e720c[{l=/192.168.219.91:39492,r=/192.168.219.95:8080,OPEN,fill=-,flush=-,to=0/70000}{io=0/0,kio=0,kro=8}]->[<null>]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.L og4jLogger","threadId":42,"threadPriority":5,"messageId":"","messageTimestamp":"2024-08-29T14:30:01.969+0000","processId":"1"}

30187 {"instant":{"epochSecond":1724941801,"nanoOfSecond":970189887},"thread":"@1f3b992-42","level":"DEBUG","loggerName":"org.eclipse.jetty.io.AbstractEndPoint","message":"onOpen SocketChannelEndPoint@7c3e720c[{l=/192.168.219.91:39492,r=/192.168.219.95:8080,OPEN,fill=-,flush=-,to=1/70000}{io=0/0,kio=0,kro=8}]->[HTTP2ClientConnection@60cc72c3]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":42,"threadPriority":5,"messageId":"","messageTimestamp":"2024-08-29T14:30:01.970+0000","processId":"1"}

 30437 {"instant":{"epochSecond":1724941802,"nanoOfSecond":76907746},"thread":"@1f3b992-41","level":"DEBUG","loggerName":"org.eclipse.jetty.io.SelectableChannelEndPoint","message":"Key interests updated 1 -> 1 on SocketChannelEndPoint@7c3e720c[{l=/192.168.219.91:39492,r=/192.168.219.95:8080,OPEN,fill=FI,flush=-,to=0/70000}{io=1/1,kio=1,kro=1}]->[HTTP2ClientConnection@60cc72c3]","endOfBatch":false,"logg       erFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":41,"threadPriority":5,"messageId":"","messageTimestamp":"2024-08-29T1  4:30:02.076+0000","processId":"1"}

68034 {"instant":{"epochSecond":1724941871,"nanoOfSecond":969282037},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.io.IdleTimeout","message":"SocketChannelEndPoint@7c3e720    c[{l=/192.168.219.91:39492,r=/192.168.219.95:8080,OPEN,fill=FI,flush=-,to=69892/70000}{io=1/1,kio=1,kro=1}]->[HTTP2ClientConnection@60cc72c3] idle timeout check, elapsed: 69892 ms, remaining: 108 ms"  ,"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageId":"","messag   eTimestamp":"2024-08-29T14:31:11.969+0000","instanceType":"prod","processId":"1"}

 
  68538 {"instant":{"epochSecond":1724941872,"nanoOfSecond":79655324},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Session","message":"Closing no_error/Idle timeout expired: 70000 ms HTTP2ClientSession@3559d3e{local:/192.168.219.91:39492,remote:/192.168.219.95:8080,sendWindow=65274,recvWindow=16777072,state=[streams=0,NOT_CLOSED,goAwayRecv=null,goAwaySent=nu       ll,failure=null]}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageTimestamp":"2024-08-29T14:31:12.079+0000","processId":"1"}
68539 {"instant":{"epochSecond":1724941872,"nanoOfSecond":80017477},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Session","message":"Sending GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms} on HTTP2ClientSession@3559d3e{local:/192.168.219.91:39492,remote:/192.168.219.95:8080,sendWindow=65274,recvWindow=16777072,state=[streams=0,LOCALLY_CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms},failure=null]}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"messageTimestamp":"2024-08-29T14:31:12.080+0000","processId":"1"}

68542 {"instant":{"epochSecond":1724941872,"nanoOfSecond":80247587},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Flusher","message":"Processing GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageId":"","messageTimestamp":"2024-08-29T14:31:12.080+0000","processId":"1"}
68543 {"instant":{"epochSecond":1724941872,"nanoOfSecond":80413001},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Flusher","message":"Generated 47 frame bytes for GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageId":"","messageTimestamp":"2024-08-29T14:31:12.080+0000","processId":"1"}
 
 68546 {"instant":{"epochSecond":1724941872,"nanoOfSecond":80819558},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.io.WriteFlusher","message":"Flushed=true written=47 remaining=0 WriteFlusher@3cf2d842{WRITING}->null","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageTimestamp":"2024-08-29T14:31:12.080+0000","processId":"1"}
68547 {"instant":{"epochSecond":1724941872,"nanoOfSecond":80895859},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Session","message":"Flushed 47/47 frame bytes for GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","messageTimestamp":"2024-08-29T14:31:12.080+0000","processId":"1"}
68548 {"instant":{"epochSecond":1724941872,"nanoOfSecond":80958138},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Flusher","message":"Written 1 buffers - entries processed/pending 1/0: [GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms}]/[]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,       "messageId":"","messageTimestamp":"2024-08-29T14:31:12.080+0000","processId":"1"}
68549 {"instant":{"epochSecond":1724941872,"nanoOfSecond":81071832},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Flusher","message":"Flushing HTTP2ClientSessio       n@3559d3e{local:/192.168.219.91:39492,remote:/192.168.219.95:8080,sendWindow=65274,recvWindow=16777072,state=[streams=0,LOCALLY_CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@2eb34ff6{0/no_error/Idle        timeout expired: 70000 ms},failure=null]}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageTimestamp":"2024-08-29T14:31:12.081+0000","processId":"1"}

 68550 {"instant":{"epochSecond":1724941872,"nanoOfSecond":81162426},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Flusher","message":"Flushed HTTP2ClientSession       @3559d3e{local:/192.168.219.91:39492,remote:/192.168.219.95:8080,sendWindow=65274,recvWindow=16777072,state=[streams=0,LOCALLY_CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms},failure=null]}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageTimestamp":"2024-08-29T14:31:12.081+0000","processId":"1"}

 68551 {"instant":{"epochSecond":1724941872,"nanoOfSecond":81262295},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.http2.HTTP2Session","message":"Idle timeout ignored for H       TTP2ClientSession@3559d3e{local:/192.168.219.91:39492,remote:/192.168.219.95:8080,sendWindow=65274,recvWindow=16777072,state=[streams=0,LOCALLY_CLOSED,goAwayRecv=null,goAwaySent=GoAwayFrame@2eb34ff6{0/no_error/Idle timeout expired: 70000 ms},failure=null]}","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageTimestamp":"2024-08-29T14:31:12.081+0000","processId":"1"}

 105950 {"instant":{"epochSecond":1724941942,"nanoOfSecond":81627478},"thread":"@1f3b992-scheduler-1","level":"DEBUG","loggerName":"org.eclipse.jetty.io.IdleTimeout","message":"SocketChannelEndPoint@7c3e720c       [{l=/192.168.219.91:39492,r=/192.168.219.95:8080,OPEN,fill=FI,flush=-,to=70000/70000}{io=1/1,kio=1,kro=1}]->[HTTP2ClientConnection@60cc72c3] idle timeout expired","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":49,"threadPriority":5,"messageId":"","messageTimestamp":"2024-08-29T14:32:22.081+0000","processId":"1"}

**Comment by sbordet** [comment]
This is expected behavior.

The receiver of the GOAWAY should send a GOAWAY back, and apparently in your case this does not happen.

So the sender waits another idle timeout, and then closes the connection.

**Comment by MohammadNC** [comment]
Hi @sbordet,

Thank you for your response. Could you please let me know how long Jetty will wait for a GOAWAY response from the server? Is this configurable?

**Comment by sbordet** [comment]
Jetty will wait another idle timeout.
