### ISSUE TITLE
Undefined JETTY_LOGS breaks jetty.sh 

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1226]
The 9.4.x changes to the logging infrastructure broke `jetty.sh` which relied on `JETTY_LOGS` to be defined since it is later in the file referenced by `--start-log-file`.

Missing `JETTY_LOGS`, is not clear how `jetty.sh` can configure the start logs ?
Can this be done in the `*.mod` files, or it is too late ?

**Comment by sbordet** [comment]
@gregw the fix is not enough.

When having multiple websites, starting them (e.g. at reboot) will cause all of them to compete to write to `$JETTY_RUN/start.log`.

We should either have different directories or different file names.

Furthermore, `/var/run` is typically owned by `root`. While it is indeed `root` that writes `$JETTY_RUN/$NAME.pid` and so it will not have permission problems to write it, it's `$JETTY_USER` that writes `start.log`.
This means that `/var/run/jetty` should be writable by anyone.

I am kind of leaning towards having `$JETTY_RUN` to be `$JETTY_BASE` so that one does not have to walk directories around to find relevant files - it's all in `$JETTY_BASE`.

**Comment by gregw** [comment]
@sbordet if using jetty.sh for multiple instances, then there are several points of conflict and several env variables would need to be customized to make it workable: `JETTY_RUN` being an obvious example.

perhaps we should change the init script to be able to look for a directory of multiple bases and to run an instance for each?

I'll double check the permissions on `/var/run` and ownership when the file is opened and written to... but my testing indicated that it was working fine.

**Comment by sbordet** [comment]
@gregw we use `jetty.sh` renamed for 3 or our websites, and the only clash is for `start.log`.

Writing the PID is already good, since we use `$JETTY_RUN/$NAME.pid`, and `root` writes it.

The definition of `JETTY_RUN` is:

```
JETTY_RUN=$(findDirectory -w /var/run /usr/var/run $JETTY_BASE /tmp)/jetty
```

We should perhaps change it to:

```
  JETTY_RUN=$(findDirectory -w $JETTY_BASE /var/run /usr/var/run /tmp)/$NAME
```

I would keep things simpler and just set it to:

```
JETTY_RUN=$JETTY_BASE
```

**Comment by gregw** [comment]
@sbordet I have updated the script to use `$NAME-start.log`, so it is renamed like PID files based on the script name.

But I'm not actually sure what this log file does or who it is for?    is it a start-stop-daemon thing?   IT is not the jetty.start file, which we do separately?

**Comment by sbordet** [comment]
It is the log file of the Jetty start module, _before_ the logging module(s) kick in.
Serves the purpose of figuring out errors in the module configuration, and it's activated by the `start-log-file` property that we pass on command line in `jetty.sh`.

@gregw I still think that for improved usability it would be better to _not_ try to write into `/var/run` or `/usr/var/run` because most likely the Jetty user will not have write permission, causing Jetty to fail to start without a clear reason.

So while your last change for `$NAME-start.log` is fine, I think we should choose a better default for the `$JETTY_RUN` directory.

**Comment by gregw** [comment]
Is it a start-stop-daemon thing?  I can't find any doco?

How about we look for a $JETTY_BASE/logs directory and if it exists we put it there in preference to $JETTY_RUN?

**Comment by gregw** [comment]
closing this as there is not clear thing to fix.
If a specific problem with start is identified, please open a new issue.
