### ISSUE TITLE
Introduce `BufferUtil.ensureDirect(ByteBuffer)` method

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#12262]
**Jetty version(s)**
12.1.x

**Enhancement Description**

A need for a new utility called `ensureDirect(ByteBuffer)` has been identified during review of #12075

**Comment by sbordet** [comment]
@joakime can you detail why?

**Comment by joakime** [comment]
First pass implementation will be in PR #12075 as it seems to only be needed there.
If in the future we want it in a more generic place we can move it then.
