### ISSUE TITLE
org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern property seems not to work starting with 11.0.16 

### ISSUE THREAD

**Issue by cliviu** [eclipse/jetty.project#12304]
**Jetty Version**
11.0.16 - 11.0.24

**Java Version**

OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)

**Question**

the property  org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern seems not to work starting with 11.0.16 or something has changed in comparison with 11.0.15. The same Vaadin application starts with the embedded Jetty 11.0.15 but not with any Jetty 11 version greater as 11.0.15

Does it ring any bells? Any change with 11.0.16?

**Comment by joakime** [comment]
Jetty 11 is at End of Community Support.

* #10485 

You should be using a supported version of Jetty at this point in time.
That would be Jetty 12.

**Comment by joakime** [comment]
Both the `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` and the `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern` work as designed (as Context Attributes) on Jetty 12.0.x, in environments ee8 thru ee10.

If you have a reproduction example, using a released version of Jetty 12.0.x, let us know where to get it and how run it.

**Comment by cliviu** [comment]
> Jetty 11 is at End of Community Support.
> 
> * [EoCS (End of Community Support) for Jetty 10 / Jetty 11 - January 2024 #10485](https://github.com/jetty/jetty.project/issues/10485)
> 
> You should be using a supported version of Jetty at this point in time. That would be Jetty 12.

Yes I know but I have some problems with Jetty12:  https://github.com/jetty/jetty.project/issues/11092  and  it looks like pac4j is also not running with Jetty 12 (https://github.com/jetty/jetty.project/issues/11809)

**Comment by cliviu** [comment]
> Both the `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` and the `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern` work as designed (as Context Attributes) on Jetty 12.0.x, in environments ee8 thru ee10.
> 
> If you have a reproduction example, using a released version of Jetty 12.0.x, let us know where to get it and how run it.

I'm trying to see what is the difference between Jetty 11.0.15 and 11.0.16 that makes my Vaadin application not working. 
Same Vaadin version, no changes in code, just swapping the 11.0.15 with any Jetty 11 version greater than it results in https://github.com/vaadin/flow/issues/15991 .

**Comment by joakime** [comment]
@cliviu this is Jetty 11, a version that is out of support.

* #10485 

If this happens in Jetty 12 we can address it, otherwise this issue is considered out of support.

**Comment by cliviu** [comment]
> @cliviu this is Jetty 11, a version that is out of support.
> 
>     * [EoCS (End of Community Support) for Jetty 10 / Jetty 11 - January 2024 #10485](https://github.com/jetty/jetty.project/issues/10485)
> 
> 
> If this happens in Jetty 12 we can address it, otherwise this issue is considered out of support.

Ok, I understand
