### ISSUE TITLE
LdapLoginModule support for Jetty Password obfuscation

### ISSUE THREAD

**Issue by nbiqvia** [eclipse/jetty.project#12350]
**Jetty version(s)**
>= 10

**Enhancement Description**
The LdapLoginModule (org.eclipse.jetty.jaas.spi.LdapLoginModule) doesn't support Jetty password obfuscation.

The module login configuration often need a `bindPassword`, it would be nice for such configuration to be compliant with the rest of Jetty configuration and support [Password obfuscation](https://jetty.org/docs/jetty/12/operations-guide/tools/index.html#password)

**Comment by sbordet** [comment]
This is going to be fixed in Jetty 12.

**Comment by nbiqvia** [comment]
Can we add this to Jetty 10.x.x and 11.x.x? happy to create the PR in case

**Comment by sbordet** [comment]
@nbiqvia sorry but Jetty 10/11 are at end of community support, see the table here:

* #10485 

You can [contact Webtide](https://webtide.com) for commercial support.
