### ISSUE TITLE
ContextHandler.isShutdown() throws NPE before started up

### ISSUE THREAD

**Issue by raimohanska** [eclipse/jetty.project#1236]
The method [ContextHandler.isShutdown](https://github.com/eclipse/jetty.project/blob/b2162cb34793b7a937d80ed168a329794ccd00c2/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L692) throws NullPointerException when called before server is started up.

This causes problems with JMX (in my case, the Prometheus JMX exporter), because the method may be called during server startup. 

I believe this could be easily fixed by initializing the `_availability` variable to `Availability.UNAVAILABLE` instead of `null`. I tested this assumption by running my application with a patched version of `ContextHandler` and the problem does get fixed. Want a Pull Request?

**Comment by janbartel** [comment]
Pull requests are good.

**Comment by janbartel** [comment]
Fix merged, thanks.
