### ISSUE TITLE
Getting ReentrantLock

### ISSUE THREAD

**Issue by ajabhi** [eclipse/jetty.project#12381]
spark 3.53
Spark using jetty 9.4.54.v20240208
Java 17

When Spark long running job than in some runs got stuck, and found thread block

Lock(java.util.concurrent.locks.ReentrantLock$NonfairSync@1040073191)

java.base@17.0.12/sun.nio.ch.Net.accept(Native Method)
java.base@17.0.12/sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:425)
java.base@17.0.12/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:391)
app//org.sparkproject.jetty.server.ServerConnector.accept(ServerConnector.java:388)
app//org.sparkproject.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:704)
app//org.sparkproject.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
app//org.sparkproject.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
java.base@17.0.12/java.lang.Thread.run(Thread.java:840)

**Comment by sbordet** [comment]
The thread is blocked in the `accept()` operation.
This is normal and by design.
