### ISSUE TITLE
Backport connection limit fix to Jetty 11

### ISSUE THREAD

**Issue by vlsorokin** [eclipse/jetty.project#12383]
**Jetty Version**

Jetty-11.x

**Question**

Would it be possible to backport the changes from PR https://github.com/jetty/jetty.project/pull/12320, which address Issue https://github.com/jetty/jetty.project/issues/7515, to Jetty 11?

I have created a PR https://github.com/jetty/jetty.project/pull/12382 with a cherry-pick of the fix.

From what I can tell, it appears safe to backport this to Jetty 11 (however I've never contributed to Jetty project and might overlook some potential concerns)

**Comment by sbordet** [comment]
@vlsorokin sorry but Jetty 10/11 is at end of community support, see the table here:

* #10485 

You have to assume that there may never be another Jetty 11 version.
There _might_ be another Jetty 11 release, for security reasons, or to support Webtide clients, but it is not guaranteed if neither of those reasons occur.

You can [contact Webtide](https://webtide.com) for commercial support, or you can upgrade to Jetty 12.
