### ISSUE TITLE
Any alternate class for org.eclipse.jetty.annotations.ServletContainerInitializersStarter in jetty 12?

### ISSUE THREAD

**Issue by dVenkatNaveen** [eclipse/jetty.project#12394]
**Jetty Version**
jetty 12
**Jetty Environment**

**Java Version**
java 17
**Question**
Any alternate class for org.eclipse.jetty.annotations.ServletContainerInitializersStarter in jetty 12?

**Comment by joakime** [comment]
As with anything servlet related, these kinds of classes are now in environment specific locations.

Here's the one for ee10, there are also ones for ee9, ee8 (in Jetty 12.0.x), and ee11 (in Jetty 12.1.x)

https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/ee10/servlet/ServletContextHandler.ServletContainerInitializerStarter.html
