### ISSUE TITLE
Don't produce text/html error response if the request doesn't accept text/html

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#124]
migrated from Bugzilla [#414860](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414860)
status ASSIGNED severity *enhancement* in component *server* for *9.0.x*
Reported in version *7.6.12* on platform *All*
Assigned to: Project Inbox

On 2013-08-12 07:31:43 -0400, Vladimir Tsukur wrote:

> Consider the case when client is asking for resource which does not exist. Jetty responds with standard text/html HTTP ERROR 404 page. The problem is that Jetty ignores "Accept" header sent by the client always responding in HTML.
> 
> Let's assume HTTP client is sending the request with specific MIME type like application/json. Returning text/html actually breaks the client since it is not what he asked for.
> 
> According to the HTTP 1.1 RFC (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):
> If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.
> 
> Would it make sense to comply to the rules of content negotiation and return response in compatible content type? Or 4xx/5xx responses should be treated as response which may not confirm to the rules imposed by Accept header?

On 2013-08-12 07:46:03 -0400, Vladimir Tsukur wrote:

> Let me elaborate a little bit more on this: returning response in client-compatible MIME type would at least ensure that client may parse the request. Response itself may be HTML if client requests content in */*, text/* or text/html and may be empty in all cases (like application/json).

**Comment by joakime** [comment]
The generic ErrorHandler should at a bare minimum honor the `Accept` header to the point where it does not produce body content if if the mime type is unrecognized.

At which point, the webapp will have to add their own custom Error Page handling for mime types based on context for that specific webapp.
