### ISSUE TITLE
HandshakeRequest getHeaders are case sensitive.

### ISSUE THREAD

**Issue by laurentriviere** [eclipse/jetty.project#12429]
**Jetty version(s)**
12.0.14

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
17.0.12

**OS type/version**
Ubuntu 24.04.1 LTS

**Description**
In JsrHandshakeRequest the method getHeaders() is case sensitive.

In JavaEE8 and JakartaEE9/10 
https://javaee.github.io/javaee-spec/javadocs/javax/websocket/server/HandshakeRequest.html#getHeaders--
_Return the read only Map of Http Headers that came with the handshake request. The header names are case insensitive._

**How to reproduce?**

* In Jetty 9.4.56 : 
  * hReq..getHeaders().get("cookie") return headers for Cookie
  * hReq..getHeaders().get("Cookie")  return headers for Cookie
* In Jetty 12.0.14 :
  * hReq..getHeaders().get("cookie") is null
  * hReq..getHeaders().get("Cookie") return headers for Cookie

**Comment by lachlan-roberts** [comment]
@laurentriviere thanks for the report, this has been fixed in #12441 and will be available in the next release `12.0.16`.
