### ISSUE TITLE
How Do I Use the Jetty Client to Connect to the IIS Web Server of the two-way authentication?

### ISSUE THREAD

**Issue by xiaoma0513** [eclipse/jetty.project#12447]
**Jetty version(s)**

**Jetty Environment**

**Java version/vendor** `(use: java -version)`

**OS type/version**

**Description**
Our Jetty client is used to request the IIS web server. The ssl settings of the IIS web server is configured with require. 
![image](https://github.com/user-attachments/assets/16a9d20e-86d6-46f0-a9b4-cbac02fdfdf0)

However, the client does not receive the Handshake Protocol: Certificate Request message during the handshake process, 
![image](https://github.com/user-attachments/assets/4b3a7ca0-c777-4d9e-86e6-50a91b7db13f)

Therefore, the client does not send the identity certificate to the IIS web server. As a result, the server authentication fails.The server error code is 403.7.

When we run the curl command to request the IIS web server and specify the identity certificate,

Like this curl --cert server.cer --pass: keypass --key server_key.pem -H "Content-Type: application/json" -X GET "https://1.1.1.1:443/XXX"

the client still does not receive the Handshake Protocol: Certificate Request, but the IIS web server receives the identity certificate from the client. When we capture and analyze the data packets, we do not see the packets that the client sends the certificate.

![image](https://github.com/user-attachments/assets/f9e7ab68-c707-45b7-93cc-74ed752bc350)

We try to use Python to send a request wiht the certificate. The result is the same as that of the curl command line. The server does not request the certificate or the client sends the certificate, but the server obtains the certificate information of the client.

**How to reproduce?**

**Comment by sbordet** [comment]
Sorry, but this is not a Jetty issue, but likely an IIS issue.

The Jetty client cannot force the send of the client certificate if the server does not request it.
This is controlled by the OpenJDK TLS implementation, and there is nothing that Jetty can do.

**Comment by xiaoma0513** [comment]
> Sorry, but this is not a Jetty issue, but likely an IIS issue.
> 
> The Jetty client cannot force the send of the client certificate if the server does not request it. This is controlled by the OpenJDK TLS implementation, and there is nothing that Jetty can do.

thanks for your commented
