### ISSUE TITLE
HTTP/2 headers may not be split in CONTINUATION frames

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#12488]
**Jetty version(s)**
12.0.x

**Description**
HTTP/2 headers generation invokes the `HpackEncoder` with a `ByteBuffer` that is sized to the `maxFrameSize`.
This is incorrect for those cases where `maxHeaderListSize > maxFrameSize`.

**Comment by wendigo** [comment]
How does it affect the server when this condition happens?

**Comment by sbordet** [comment]
@wendigo the server would throw an error and close the connection.

However, this event is quite rare, because it really needs very large headers, typically way more than the 16 KiB max frame size thanks to Huffman compression (say 20 KiB or more).

Note that common response headers are about 300-500 bytes, so to trigger this problem the headers would need to be 40x bigger, which is very rare. 
We have not seen this error ever reported.
