### ISSUE TITLE
CustomRequestLog %q inconsistency with a doc

### ISSUE THREAD

**Issue by wendigo** [eclipse/jetty.project#12482]
**Jetty version(s)**
12.0.14

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
23

**OS type/version**

**Description**
Javadoc says:

> %q The query string, prepended with a ? if a query string exists, otherwise an empty string.

Meanwhile the code is:
```
    private static void logQueryString(StringBuilder b, Request request, Response response)
    {
        append(b, "?" + request.getHttpURI().getQuery());
    }
```
Append is unconditional which renders empty query string as `?null`

**How to reproduce?**

**Comment by joakime** [comment]
I wonder if this should produce just a `-` if there is no query string?
