### ISSUE TITLE
MultiPartFormData.Parser question.

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse/jetty.project#12496]
**Jetty Version** jetty 12.0.15

**Jetty Environment** windows 10

**Java Version** openjdk version "23" 2024-09-17

**Question**

I have handler that I use to handle multipart upload.

The Javadoc say:  (jetty-http-12.0.15-javadoc.jar/org.eclipse.jetty.http/org/eclipse/jetty/http/MultiPartFormData.html)

// Parse the content.
 **formData.parse(content)**
     // When complete, use the parts.
     .thenAccept(parts -> ...);
	 
When I try to use it, I get that it is deprecated. (forRemoval = true, since = "12.0.15")	

Is the Javadoc needs updating ?

Some sample code would be appreciated.

Thanks for any response.

**Comment by sbordet** [comment]
Thanks, I'll update the documentation and point you to it.

**Comment by joakime** [comment]
For a working example, see 

https://github.com/jetty/jetty-examples/blob/12.0.x/embedded/form-post/src/main/java/examples/FormEndpoints.java

Note: the jetty-examples shows how to use the static methods instead of the Parser.

**Comment by sbordet** [comment]
@eitan-rosenberg we had to move away from `CompletableFuture` APIs because they have inherent problems.

Your best choice is to use `MultiPartFormData.onParts(...)`.

We have updated javadocs, examples, code, etc. in #12500.

**Comment by eitan-rosenberg** [comment]
First, many thanks to you all.

I used @joakime pointer "https://github.com/jetty/jetty-examples/blob/12.0.x/embedded/form-post/src/main/java/examples/FormEndpoints.java" and it did the job for me

@sbordet May I suggest a working example for MultiPartFormData.onParts(...).

Have a nice weekend.

**Comment by eitan-rosenberg** [comment]
Thanks
