### ISSUE TITLE
performance improvement: file resource metadata not cached

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#125]
migrated from Bugzilla [#416482](https://bugs.eclipse.org/bugs/show_bug.cgi?id=416482)
status ASSIGNED severity _normal_ in component _server_ for _9.0.x_
Reported in version _9.0.4_ on platform _PC_
Assigned to: Project Inbox

On 2013-09-03 20:13:15 -0400, Viktor Szathmary wrote:

> The default servlet creates a ResourceCache which is supposed to avoid repeated expensive operations. However jetty still repeatedly issues filesystem stat calls (eg. via FileResource.isDirectory and exists).
> 
> This can be evidenced by following the operations during file serving using:
> 
> strace -f -p <pid> -e stat

On 2013-09-05 01:41:41 -0400, Greg Wilkins wrote:

> Viktor,
> 
> The cache still checks on every access that the file is still valid on the disk and of the same date stamp and type etc.
> 
> The resource cache could be made to check these only at intervals.  Even if done every second, then this could save many thousands of lookups.
> 
> However the problem remains with filemapped buffers that if the file changes, we would see the content changed before we checked the meta data.  But in most cases this is not a real risk.

**Comment by joakime** [comment]
Closing (6 years old)
