### ISSUE TITLE
Received binary messages in Jetty WebSocket Client are prepended with unexpected bytes

### ISSUE THREAD

**Issue by lglowania** [eclipse/jetty.project#12510]
**Jetty version(s)**
12.0.15

**Jetty Environment**
ee10

**Java version/vendor** 
openjdk version "21.0.5" 2024-10-15 LTS

**OS type/version**
Debian Bookworm

**Description**
I have a Jetty 12.0.5 websocket-server using the jetty-websocket-api. And a Jetty websocket-client. The client connects to the server. The server sends a binary message to the client by just getting bytes from a string. The client receives the bytes, but they are prepended with some other bytes, that were not sent by the server.

**How to reproduce?**
Server side:
```java
String testStr = "test";
byte[] bytes = testStr.getBytes();
ByteBuffer wrap = ByteBuffer.wrap(bytes);
session.sendBinary(wrap, Callback.NOOP);
```
Client side:
```java
@Override
public void onWebSocketBinary(ByteBuffer payload, Callback callback) {

    byte[] payloadBytes = payload.array();
    
    ByteUtils.printBytesAsString(payloadBytes);
    // prints �test
}
```
In this case 2 unexpected bytes were added. In longer messages i saw 4 unexpected bytes added. Where do they come from?

**Comment by lachlan-roberts** [comment]
You are using `payload.array()`, which actually just gives you the underlying array for that `ByteBuffer`.

But the `ByteBuffer` has things like a position and a limit to specify where the data is in that array.

For example the Jetty utility to convert `ByteBuffer` into a `byte[]` array does this
https://github.com/jetty/jetty.project/blob/f78cbc1d4ba2edb6616af363de3e70e75be13ae1/jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java#L289-L309

**Comment by sbordet** [comment]
@lachlan-roberts can you please make sure the buffer we give to applications is sliced?
In this way this won't happen.

**Comment by sbordet** [comment]
My bad, `slice()` does not copy the array, so calling `array()` would really show the underlying array in its entirety.

**Comment by lglowania** [comment]
I have no detail-knowledge about ByteBuffers. But usually limit and position are not stored in the underlying array.
```java
  byte[] bytes = "test".getBytes();
  ByteBuffer bb = ByteBuffer.wrap(bytes);
  bb.position(1);
  byte[] array = bb.array();
  System.out.println(Arrays.equals(bytes, array));
  // prints true
```
So the prepended bytes are unexpected. Maybe a specialized `WebSocketByteBuffer`-class with some documentation and a `getPayloadBytes()`-method  would help.

**Comment by sbordet** [comment]
@lglowania you should use `ByteBuffer`s properly; how to properly use `array()` is well documented by the JDK.

Besides, you cannot call `array()` without first checking `hasArray()`.

```java
byte[] bytes = new byte[bb.remaining()];
bb.get(bytes);
```

> Maybe a specialized WebSocketByteBuffer-class with some documentation and a getPayloadBytes()-method would help.

It won't help. 
`ByteBuffer` has extensive documentation in javadocs, tutorials online, etc.

**Comment by lglowania** [comment]
Ok, no problem. It's just: `i send a bytebuffer` and `i receive a different bytebuffer`. But i'm totally ok with the current state. Thank you.
