### ISSUE TITLE
jetty-core 12.0.15 is missing from Maven Central

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#12515]
**Jetty version(s)**
12.0.15

**Jetty Environment**
core

jetty 12.0.15 is unusable because `jetty-core` is missing from Maven Center: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-core/12.0.15/

It's pretty crazy that no one else has complained. The release is 5 days old already! :)

**Comment by olamy** [comment]
it;s there https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-core/12.0.15/

```
curl -I https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-core/12.0.15/jetty-core-12.0.15.pom
HTTP/2 200 
etag: "9463b99b4edfbcc3c1567ddae0697f8f"
content-type: text/xml
last-modified: Tue, 05 Nov 2024 19:55:04 GMT
x-checksum-md5: 9463b99b4edfbcc3c1567ddae0697f8f
x-checksum-sha1: b3ba19fc04e32170f274bd0fa4d6d13ce4c96b63
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
date: Tue, 12 Nov 2024 01:32:17 GMT
age: 0
x-served-by: cache-iad-kcgs7200152-IAD, cache-bne12520-BNE
x-cache: HIT, MISS
x-cache-hits: 7877, 0
x-timer: S1731375137.295433,VS0,VE221
content-length: 6963

```

It's just a pom. Not sure what are you expecting?
Maybe there is some caching issue?

**Comment by cowwoc** [comment]
Yeah, I feel stupid now :) It's just a POM. I got confused because of an unrelated cache corruption issue in my IDE. Closing this issue now. Sorry for the false alarm.

**Comment by olamy** [comment]
no worries
