### ISSUE TITLE
9.4.x Server resource handler welcome files forwarding not working

### ISSUE THREAD

**Issue by MatthijsEM** [eclipse/jetty.project#1254]
When using the default resource handler welcome files are not working when forwarding (default behaviour) is used. This is even when using a minimalistic approach of creating a Server and adding a ResourceHandler and nothing else.

During debugging the code will end up here
[resource service line 415 ](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java#L415)

which leads to 
[request line 1247](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L1247)

but the request does not have a context set so the function will always return null causing the ResourceService to do nothing. 

If you are running e.g. this [File server example](http://download.eclipse.org/jetty/stable-9/xref/org/eclipse/jetty/embedded/FileServer.html), you will get a 

_Error 404 - Not Found.

No context on this server matched or handled this request.
Contexts known to this server are:_

**Comment by gregw** [comment]
Fixed by falling back to a redirect if dispatcher not found.
improved tests a little bit
