### ISSUE TITLE
Max local stream count issue

### ISSUE THREAD

**Issue by deroude** [eclipse/jetty.project#1255]
I have the following setup:
```
        int reqs=2000;
        CountDownLatch latch = new CountDownLatch(reqs);

	// Prepare the listener to receive the HTTP response frames.
	Stream.Listener responseListener = new Stream.Listener.Adapter() {
	    @Override
	    public void onData(Stream stream, DataFrame frame, Callback callback) {
		byte[] bytes = new byte[frame.getData().remaining()];
		frame.getData().get(bytes);
		if (re.containsKey(stream.getId())) {
		    re.get(stream.getId()).append(new String(bytes));
		} else {
		    re.put(stream.getId(), new StringBuffer(new String(bytes)));
		}
		if (frame.isEndStream()) {
		    System.out.println("Stream " + stream.getId() + "[closed: " + stream.isClosed() + "; reset: " + stream.isReset() + "] " + re.remove(stream.getId()).toString());
		    latch.countDown();
		}
		callback.succeeded();
	    }

	};

	for (int i = 0; i < reqs; i++) {
	    session.newStream(headersFrame, new FuturePromise<>(), responseListener);
	}

        latch.await();
	client.stop();
```

The `latch.await()` never finishes. A variable number of logs arrive through the listener onData method, slightly more than the number of concurrent streams configured (in my case 128).

The following loop works however:
```
for (int i = 0; i < reqs; i++) {
	    FuturePromise<Stream> fp = new FuturePromise<>();
	    while (session.getStreams().size() > 127) {
		Thread.sleep(10);
	    }
	    session.newStream(headersFrame, fp, responseListener);
	    try {
		System.out.println("Added stream " + fp.get().getId());
	    } catch (ExecutionException e) {
		System.out.println("Bang, couldn't add stream. Going too fast.");
		latch.countDown();
	    }
	}
```

First issue: unless I call `get` on the FuturePromise<Stream> passed to the `session.newStream` method, I don't get the ExecutionException (it doesn't bubble) -- although it probably occurs, because the streams affected never reach the target.
Second issue: my solution is a miserable hack; since the stream itself is a Future anyway, is it not possible to pipeline the `session.newStream` request so that it will be served immediately, if there is enough room, or as soon as a stream slot is free, otherwise? (i.e. not throw any exception)

**Comment by sbordet** [comment]
To answer your first "issue", if you pass an empty `FuturePromise` when creating the streams without checking whether you had a failure, you can't then complain that you were not notified.
The HTTP/2 low-level API is asynchronous, so there is no exception bubbling: the exceptions are notified via a `Promise` callback.
Jetty 9.4.x introduces utility classes to convert `Promise` from/to `CompletableFuture`.
You may want to use those utility classes to chain actions that needs to wait for the previous.

To answer your second "issue": the low-level HTTP/2 API does not have any queuing facility; the high-level `HttpClient` API does.
