### ISSUE TITLE
org.eclipse.jetty.http.HttpURI.getDecodedPath() throws an NPE when there is no path

### ISSUE THREAD

**Issue by gnikolaidis** [eclipse/jetty.project#12577]
Probably a minor nitpick, but shouldn't getDecodedPath() return null when the path is null? Right now it throws a NPE, which is not documented behavior.

**Comment by joakime** [comment]
Please don't skip the issue form.
What is your Jetty version?
What is your Java version?
What OS is this happening on?
What is the complete stracktrace you are encountering?
How can this be replicated?

**Comment by gnikolaidis** [comment]
My bad, I didn't see the issue form.

What is your Jetty version? 12.0.14
What is your Java version? 17
What OS is this happening on? Debian Stable
What is the complete stracktrace you are encountering? n/a
How can this be replicated? HttpURI.from("http://").getDecodedPath();

**Comment by joakime** [comment]
Stacktrace ...

```
java.lang.NullPointerException: Cannot invoke "String.length()" because "path" is null
	at org.eclipse.jetty.util/org.eclipse.jetty.util.URIUtil.decodePath(URIUtil.java:479)
	at org.eclipse.jetty.http/org.eclipse.jetty.http.HttpURI$Immutable.getDecodedPath(HttpURI.java:390)
	at org.eclipse.jetty.http/org.eclipse.jetty.http.HttpURITest.testDecodedPath(HttpURITest.java:513)
```

This is a `URIUtil.decodedPath()` bug.

**Comment by joakime** [comment]
Opened PR #12580
