### ISSUE TITLE
oejhs.AbstractHTTP2ServerConnectionFactory installs the HTTP2SessionContainer bean twice

### ISSUE THREAD

**Issue by gnikolaidis** [eclipse/jetty.project#12588]
**Jetty version(s)**
12.0.14

**Jetty Environment**
core

**Java version/vendor**
OpenJDK 17

**OS type/version**
Debian Stable

**Description**
The `AbstractHTTP2ServerConnectionFactory(@Name("config") HttpConfiguration httpConfiguration, @Name("protocols") String... protocols)` constructor calls `installBean()` on the `sessionContainer`, which implements `EventListener`. `ContainerLifeCycle.installBean(Object, Managed)` first adds the listener, causing a bean to be created, then adds the bean again, resulting in 2 exact same beans being registered. 

**How to reproduce?**
`new HTTP2ServerConnectionFactory().dump(System.out);`

**Comment by sbordet** [comment]
@gnikolaidis good catch!
