### ISSUE TITLE
Log lifecycle exception only once

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#126]
migrated from Bugzilla [#416688](https://bugs.eclipse.org/bugs/show_bug.cgi?id=416688)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _9.0.5_ on platform _PC_
Assigned to: Project Inbox

Original attachment names and IDs:
- _[test.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=235222)_ (ID 235222)

On 2013-09-06 03:53:00 -0400, Mikhail Mazursky wrote:

> Created attachment 235222
> Three stacktraces
> 
> Please take a look at the attached stacktraces. Can exception be logged only once please? Exception can have much bigger stacktrace and a cause chain. This will result in a lot of traces in logs.

**Comment by janbartel** [comment]
Old issue.
