### ISSUE TITLE
JettyWebSocketServlet.java and related classes do not exits for EE8

### ISSUE THREAD

**Issue by amarktl** [eclipse/jetty.project#12616]
**Jetty version(s)**
Jetty 12.x

**Jetty Environment**
EE8

**Description**
For EE89 the JettyWebSocketServlet.java and related classes do not exits. This is available for EE9 as well as EE10 - Is this by intention ? If this is on purpose what is the expected migration strategy for applications which made use of these?

**Comment by sbordet** [comment]
> For EE8 the JettyWebSocketServlet.java and related classes do not exits.

They exist.

The EE8 implementation is generated from EE9 via a translation tool, since they are identical (apart the namespace change).

If you want to look at the source code, look at EE9.

If you're looking for the binaries, they are in Maven Central.

**Comment by amarktl** [comment]
Thanks for pointing out. I totally missed that. :)

**Comment by olamy** [comment]
generated sources are deployed to Maven central.
such https://repo.maven.apache.org/maven2/org/eclipse/jetty/ee8/websocket/jetty-ee8-websocket-javax-server/12.0.15/jetty-ee8-websocket-javax-server-12.0.15-sources.jar
using intellij download sources link should download this for you.
