### ISSUE TITLE
mvn -Pfast clean install  fail

### ISSUE THREAD

**Issue by dabao1990** [eclipse/jetty.project#12624]
1、spack install --overwrite --keep-stage --no-checksum -y jetty-project@12.0.16  maven@3.9.2
2、cd jetty-project@12.0.16
3、ulimit -n 1048576
4、mvn -Pfast clean install

[INFO] Build :: Resources ................................. SUCCESS [  1.409 s]
[INFO] Jetty :: Project ................................... SUCCESS [  2.533 s]
[INFO] Build .............................................. SUCCESS [  0.041 s]
[INFO] Core ............................................... SUCCESS [  0.032 s]
[INFO] Core :: SLF4J Implementation ....................... SUCCESS [  1.189 s]
[INFO] Core :: Utilities .................................. FAILURE [  0.630 s]
[INFO] Core :: JMX ........................................ SKIPPED
[INFO] Core :: IO ......................................... SKIPPED
[INFO] Core :: ALPN ....................................... SKIPPED
[INFO] Core :: ALPN :: Client ............................. SKIPPED
[INFO] Tests .............................................. SKIPPED
[INFO] Tests :: Multipart Test Tools ...................... SKIPPED
[INFO] Core :: HTTP ....................................... SKIPPED
[INFO] Core :: HTTP Tools ................................. SKIPPED
[INFO] Core :: Utilities :: JSON .......................... SKIPPED
[INFO] Core :: HTTP2 ...................................... SKIPPED
[INFO] Core :: HTTP2 :: HPACK ............................. SKIPPED
[INFO] Core :: HTTP2 :: Common ............................ SKIPPED
[INFO] Core :: HTTP2 :: Client ............................ SKIPPED
[INFO] Core :: ALPN :: Conscrypt Client ................... SKIPPED
..........
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.335 s
[INFO] Finished at: 2024-12-11T10:45:13+08:00
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 5 plugin(s)
[WARNING]
[WARNING]  * org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.7
[WARNING]  * com.mycila:license-maven-plugin:4.5
[WARNING]  * org.apache.felix:maven-bundle-plugin:5.1.9
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
**_**[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:3.2.1:create (create-buildnumber) on project jetty-util: Cannot get the revision information from the scm repository :
[ERROR] Exception while executing SCM command.: The git log command failed: /bin/sh -c cd '/home/stage/root/spack-stage-jetty-project-12.0.16-ofhflzqn5m6qkcztzgyauk55whgvo66q/spack-src' && 'git' 'log' '-1' '--no-merges' '--format=format:%H %aI %aE %aN' returned fatal: not a git repository (or any of the parent directories): .git**_**
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jetty-util

**Comment by olamy** [comment]
As it's not a git repo and our usual build needs some git metadata to be added, you must add the following parameter to Maven
```
-Dmaven.buildNumber.skip=true
```

**Comment by dabao1990** [comment]
> As it's not a git repo and our usual build needs some git metadata to be added, you must add the following parameter to Maven
> 
> ```
> -Dmaven.buildNumber.skip=true
> ```

=============================
=============================
Based on your reply, I can go on. But there's another problem with Ubuntu. I mentioned an issue once, but the solution you gave didn't get resolved.
[https://github.com/jetty/jetty.project/issues/12005](url)


[INFO] EE8 :: Websocket :: Jetty Server ................... SUCCESS [  0.068 s]
[INFO] EE8 :: Websocket :: Javax Common ................... SUCCESS [  0.091 s]
[INFO] EE8 :: Websocket :: Javax Client ................... SUCCESS [  0.055 s]
[INFO] EE8 :: Websocket :: Javax Server ................... SUCCESS [  0.061 s]
[INFO] EE8 :: Demo :: Jetty WebApp ........................ SUCCESS [  0.073 s]
[INFO] EE8 :: Demo :: Mock Resources ...................... SUCCESS [  0.053 s]
[INFO] EE8 :: Demo :: JNDI WebApp ......................... SUCCESS [  0.060 s]
[INFO] EE8 :: Demo :: JSP WebApp .......................... SUCCESS [  0.057 s]
[INFO] EE8 :: Demo :: Proxy WebApp ........................ SUCCESS [  0.064 s]
[INFO] EE8 :: Demo :: Simple WebApp ....................... SUCCESS [  0.059 s]
[INFO] EE8 :: Demo :: Servlet Spec ........................ SUCCESS [  0.026 s]
[INFO] EE8 :: Demo :: Servlet Spec :: ServletContainerInitializer Jar SUCCESS [  0.046 s]
[INFO] EE8 :: Demo :: Servlet Spec :: Fragment Jar ........ SUCCESS [  0.045 s]
[INFO] EE8 :: Demo :: Servlet Spec :: WebApp .............. FAILURE [  0.017 s]
[INFO] EE8 :: Websocket :: Jetty Client ................... SKIPPED
[INFO] EE8 :: Websocket :: Jetty Client WebApp ............ SKIPPED
[INFO] EE8 :: Home Assembly ............................... SKIPPED
[INFO] EE9 ................................................ SKIPPED
[INFO] EE9 :: Nested ...................................... SKIPPED
[INFO] EE9 :: Security .................................... SKIPPED
[INFO] EE9 :: Servlet ..................................... SKIPPED
[INFO] EE9 :: WebApp ...................................... SKIPPED
[INFO] EE9 :: Plus ........................................ SKIPPED
[INFO] EE9 :: Servlet Annotations ......................... SKIPPED
[INFO] EE9 :: Apache JSP .................................. SKIPPED
[INFO] EE9 :: CDI ......................................... SKIPPED
[INFO] EE9 :: Proxy ....................................... SKIPPED
[INFO] EE9 :: FCGI Proxy .................................. SKIPPED
[INFO] EE9 :: Glassfish JSTL .............................. SKIPPED

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.237 s
[INFO] Finished at: 2024-12-11T15:25:10Z
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 5 plugin(s)
[WARNING]
[WARNING]  * org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.7
[WARNING]  * com.mycila:license-maven-plugin:4.5
[WARNING]  * org.apache.felix:maven-bundle-plugin:5.1.9
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Required array size too large -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

**Comment by olamy** [comment]
Please try with mvn 3.9.9 and the mvn flag `-e` as there is not enough information here.

**Comment by dabao1990** [comment]
> Please try with mvn 3.9.9 and the mvn flag `-e` as there is not enough information here.


[root@localhost spack-src]#
[root@localhost spack-src]#mvn --version
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: /home/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/maven-3.9.2-z3wixe2wv3clmlrdnbo2v4oedc3eu5ic
Java version: 17.0.2, vendor: Oracle Corporation, runtime: /home/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/openjdk-17.0.2-d2dyxehy4kfew6i7kbrnpkewihcstggn
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.15.0-112-generic", arch: "aarch64", family: "unix"

[root@localhost spack-src]#export MAVEN_OPTS="-Xmx4G -Xms4G"
[root@localhost spack-src]#export
......
declare -x MAVEN_OPTS="-Xmx4G -Xms4G"
....
[root@localhost spack-src]#mvn -e -Pfast clean install -Dmaven.buildNumber.skip=true  

......
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.875 s
[INFO] Finished at: 2024-12-11T15:40:56Z
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 5 plugin(s)
[WARNING]
[WARNING]  * org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.7
[WARNING]  * com.mycila:license-maven-plugin:4.5
[WARNING]  * org.apache.felix:maven-bundle-plugin:5.1.9
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Required array size too large -> [Help 1]
java.lang.OutOfMemoryError: Required array size too large
    at java.nio.file.Files.readAllBytes (Files.java:3294)
    at org.apache.maven.buildcache.checksum.DigestUtils.file (DigestUtils.java:57)
    at org.apache.maven.buildcache.checksum.MavenProjectInput.calculateChecksum (MavenProjectInput.java:217)
    at org.apache.maven.buildcache.DefaultProjectInputCalculator.calculateInputInternal (DefaultProjectInputCalculator.java:112)
    at org.apache.maven.buildcache.DefaultProjectInputCalculator.calculateInput (DefaultProjectInputCalculator.java:89)
    at org.apache.maven.buildcache.CacheControllerImpl.findCachedBuild (CacheControllerImpl.java:180)
    at org.apache.maven.buildcache.BuildCacheMojosExecutionStrategy.execute (BuildCacheMojosExecutionStrategy.java:128)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:910)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

**Comment by olamy** [comment]
interesting I'm using ubuntu as well with `MAVEN_OPTS=-Djava.awt.headless=true -Xmx4G -Xms4G`
but 
```
OS name: "linux", version: "6.9.3-76060903-generic", arch: "amd64", family: "UNIX"
```
As the message is saying you can add more memory 
```
MAVEN_OPTS="-Xmx8G -Xms8G"
```
Or disable the build cache
```
-Dmaven.build.cache.enabled=false
```

**Comment by dabao1990** [comment]
> interesting I'm using ubuntu as well with `MAVEN_OPTS=-Djava.awt.headless=true -Xmx4G -Xms4G` but
> 
> ```
> OS name: "linux", version: "6.9.3-76060903-generic", arch: "amd64", family: "UNIX"
> ```
> 
> As the message is saying you can add more memory
> 
> ```
> MAVEN_OPTS="-Xmx8G -Xms8G"
> ```
> 
> Or disable the build cache
> 
> ```
> -Dmaven.build.cache.enabled=false
> ```

Execute Pass，Thank you
