### ISSUE TITLE
Does Jetty support named pipes on Windows?

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#12629]
**Jetty Version**
12

**Jetty Environment**
core

**Java Version**
23

**Question**
I am trying to communicate with the local docker engine on Windows, which happens to use named pipes instead of unix sockets. Out of curiosity, does Jetty provide a way to its `HttpClient` to transport requests over named pipes?

**Comment by joakime** [comment]
First question.

Does the JDK support Named Pipes on Windows?

**Comment by sbordet** [comment]
@cowwoc no, we don't support Windows named pipes.

However, Unix-Domain sockets are supported on Windows too, so did you try that?

**Comment by joakime** [comment]
Link to the Java JNA code to access/use a Win32 Named Pipe ...

https://github.com/java-native-access/jna/blob/master/contrib/platform/test/com/sun/jna/platform/win32/Kernel32NamedPipeTest.java

**Comment by cowwoc** [comment]
@joakime See also https://github.com/docker-java/docker-java/blob/9f3d369bd6db48d99d8fc41109a8bca28cc604b6/docker-java-transport/src/main/java/com/github/dockerjava/transport/NamedPipeSocket.java

**Comment by cowwoc** [comment]
> However, Unix-Domain sockets are supported on Windows too, so did you try that?

🤯 Going to try this now :)

**Comment by sbordet** [comment]
For reference, see https://openjdk.org/jeps/380 about Unix-Domain socket support in Windows.

**Comment by cowwoc** [comment]
@sbordet Unfortunately, this doesn't seem to work (or I am doing something wrong). When I try `transport = new Transport.TCPUnix(Path.of("/var/run/docker.sock"))` I get `java.net.SocketException: Network is down: connect`

I suspect this will work if I run inside WSL2, so I'm trying that next.

**Comment by sbordet** [comment]
Do you have a directory called `/var/run` in Windows, and with the proper permissions?
The file `docker.sock` must not exist for the server (it is created by the server when it starts), and must exist for the client.

This is a JDK feature, so it must work for Windows too.

**Comment by cowwoc** [comment]
@sbordet Well, the good news is that I got it working... but only under WSL.

For example, to send a request to https://docs.docker.com/reference/api/engine/version/v1.47/#tag/System/operation/SystemInfo

I use this code:
```
Request request = client.newRequest("http://localhost/info").
  transport(new Transport.TCPUnix(Path.of("/var/run/docker.sock"))).
  method(GET));
```

The hostname (localhost) doesn't seem to matter so long as something is there. The protocol needs to be http (https won't work).

In order to get this to work, I mapped `--volume /var/run/docker.sock:/var/run/docker.sock`. I have no idea what `/var/run/docker.sock` maps to on the Windows host (because said directory does not actually exist) but it just works...

If I try to run the same code directly on the Windows host, I get `java.net.ConnectException: Connection refused: connect`.

Docker for Desktop on Windows is a strange beast... if I add `"hosts": ["unix:///var/run/docker.sock"]` to `daemon.json` then Docker engine refuses to start with:

```
time="2024-12-13T02:07:15.521258350Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
failed to load listeners: can't create unix socket /var/run/docker.sock: device or resource busy
EOF
```

In the end, I decided to just enable "Expose daemon on tcp://localhost:2375 without TLS". It is exponentially faster to develop against the local host than update and launch a docker image every time I modify my application.

I guess this resolves my question regarding whether Jetty supports named pipes and how to connect to Docker over unix sockets. Thank you for your help.

**Comment by cowwoc** [comment]
PS: I almost managed to implement a `org.eclipse.jetty.io.Transport` for named pipes using https://github.com/sbt/ipcsocket but I couldn't figure out a way to implement `Transport.getSocketAddress()`. That implementation just returns `null` and Jetty wants some non-null value. It would probably be possible to create the equivalent of `java.net.UnixDomainSocketAddress` for `Win32NamedPipeServerSocket` but I decided to just move on instead.

I hope this helps others in case someone wants to take this further one day.

**Comment by sbordet** [comment]
> The hostname (localhost) doesn't seem to matter so long as something is there.

With TCP, the host name is used both as authority and for TCP address resolution (where to connect to, via DNS).
With Unix-Domain sockets, the host name is only used as authority.
If your server performs some logic related to the authority (for example, virtual host selection), then it is important to specify the right authority.

> The protocol needs to be http (https won't work).

`https` should work too, since Unix-Domain sockets are a level below that. We have tests for `https` over Unix-Domain, but no Docker and no Windows.
Not sure why it does not, unless it's a server problem (i.e. no secure connector on the server).

> I almost managed to implement a org.eclipse.jetty.io.Transport for named pipes using https://github.com/sbt/ipcsocket but I couldn't figure out a way to implement Transport.getSocketAddress().

`Transport.getSocketAddress()` is used when `Transport.requiresDomainNameResolution=false`, and it is transparently passed back to `Transport.connect(SocketAddress, Map<String, Object>)`.

Did you try implementing something like `UnixDomainSocketAddress` (or even using that) also for your implementation?

As long as you can eventually complete the `connect()` operation using the `ipcsocket` APIs, you should be good.

Anyway, thanks for the feedback, as usual it is much appreciated 😃

**Comment by cowwoc** [comment]
> https should work too, since Unix-Domain sockets are a level below that. We have tests for https over Unix-Domain, but no Docker and no Windows.
> Not sure why it does not, unless it's a server problem (i.e. no secure connector on the server).

Sorry, I didn't mean to imply that something was wrong with Jetty. It's just that, by default, docker is not configured with any TLS certificate so https won't work. This should be workable if I sink more time into it.

> Transport.getSocketAddress() is used when Transport.requiresDomainNameResolution=false, and it is transparently passed back to Transport.connect(SocketAddress, Map<String, Object>).
>
> Did you try implementing something like UnixDomainSocketAddress (or even using that) also for your implementation?

Yes, my implementation was a modified version of UnixDomainSocketAddress. The problem is that `getSocketAddress()` returns null and Jetty tries to pass that value into a map. Unfortunatley, that map does not permit nulls, so an exception is thrown.

It sounds like I was very close to getting this to work :) I might circle back one day.
