### ISSUE TITLE
War package project for deploying Spring Boot in Jetty 11.0.0

### ISSUE THREAD

**Issue by liuqiang1008** [eclipse/jetty.project#12631]
Why Can't Spring Boot Beans Be Loaded When the Jetty Is Started After a Project Is Deployed?

**Comment by sbordet** [comment]
@liuqiang1008 sorry, but you need to respect the template and specify Jetty version, etc.

Also, there is not enough information for us to understand what the issue is.

Please open a new issue, fill in the template, and be as detailed as possible in describing your problem.
