### ISSUE TITLE
Improve javadoc surrounding Executors and org.eclipse.jetty.util.thread.ThreadPool

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#127]
migrated from Bugzilla [#417223](https://bugs.eclipse.org/bugs/show_bug.cgi?id=417223)
status REOPENED severity *normal* in component *server* for *9.0.x*
Reported in version *9.1.0* on platform *All*
Assigned to: Greg Wilkins

On 2013-09-13 16:01:22 -0400, Joakim Erdfelt wrote:

> Since most of our code has been switched to use java.util.concurrent.Executor (such as the ServerConnector and whatnot).
> 
> Is it time now to eliminate the org.eclipse.jetty.util.thread.ThreadPool interface and class?

On 2013-09-15 20:58:18 -0400, Greg Wilkins wrote:

> No.
> 
> Executor is the API for a consumer of execution services.
> 
> ThreadPool is-a Executor, but with some extra management method on it which are used in features such as resource monitoring.
> 
> We should reduce the usage of the ThreadPool API and only use Executor in places that only need to dispatch something to be executed, but at the Server layer at least we need to insist that our Executor impl is-a ThreadPool, so we can access the management methods.

On 2013-09-15 21:00:12 -0400, Joakim Erdfelt wrote:

> Fair enough, it only came up as people in the process of migrating were confused that there seemed to be no way to setup or control threadpool in the connectors anymore.
> 
> Once we pointed out that the connectors are using executors and that QTP is an executor, it clicked, but it was still confusing in the javadoc and documentation.

On 2013-09-15 21:14:44 -0400, Greg Wilkins wrote:

> Reopened to improve the javadoc

**Comment by gregw** [comment]
Javadoc looks ok.
