### ISSUE TITLE
Update ALPN versions for 8u111

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1272]
Looks like 8u111 is missing from ...

https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions

**Comment by joakime** [comment]
Also check for any further updates to Java 8. (such as a reported u122)

**Comment by WalkerWatch** [comment]
@sbordet Have 8u112 and 8u122 been fully released for OpenJDK yet? I was having some problems tracking this down. Heard you'd be the expert.
