### ISSUE TITLE
Remove org.eclipse.jetty.websocket.server.WebSocketServerFactory from SPI

### ISSUE THREAD

**Issue by plinyar** [eclipse/jetty.project#1276]
In version 9.3 no-args constructor was removed from WebSocketServerFactory. However, noone removed it from SPI registration (https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-server/src/main/resources/META-INF/services/org.eclipse.jetty.websocket.servlet.WebSocketServletFactory). This cause initialization exceptions in SPI-complient frameworks (like with Aries in OSGI).

Compare it: 
 https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java#L103 
with version 9.2:
 https://github.com/eclipse/jetty.project/blob/jetty-9.2.x/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java#L91

**Comment by sbordet** [comment]
@joakime, having a service file is only useful if the code uses `ServiceLoader` to load it.

I don't see that code anymore in branch `jetty-9.3.x`, since it was replaced by sing normal reflection fixing #1124 in commit 70247d7.

I think we should remove the service file.

**Comment by joakime** [comment]
@sbordet i agree, remove that file.
