### ISSUE TITLE
unnecessary root user check in jetty.sh

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#128]
migrated from Bugzilla [#419191](https://bugs.eclipse.org/bugs/show_bug.cgi?id=419191)
status ASSIGNED severity _normal_ in component _server_ for _9.1.x_
Reported in version _8.1.13_ on platform _All_
Assigned to: Greg Wilkins

On 2013-10-10 22:00:15 -0400, xzer lr wrote:

> At first, the background is that we using a shell to login into the
> remote server and restart the jetty service on the remote server by
> ssh, it works well until the version 8.1.8.
> 
> Then, we decided to upgrade our jetty distributions to the newest
> 8.1.13, as a test result, we found that the startJetty.sh will hang up
> the remote ssh session.
> 
> I dug the new startJetty.sh and found that it will not use
> start-stop-daemon to start jetty process when the current user is not
> root. I tried to study the commit logs, then I found the commit
>  (commit id:SHA: 38d701753c3105600ac189d97c2f5a8b2ea44371)
> for bug[403281]: "jetty.sh waits for started before OK". 
> 
>  ##################################################
>  # Setup JAVA if unset
> @@ -407,23 +428,15 @@ case "$ACTION" in
>        exit
>      fi
> -    if type start-stop-daemon > /dev/null 2>&1 
> -    if [ $UID -eq 0 ] && type start-stop-daemon > /dev/null 2>&1 
>    then
>      unset CH_USER
>      if [ -n "$JETTY_USER" ]
>      then
>        CH_USER="-c$JETTY_USER"
>      fi
> -      if start-stop-daemon -S -p"$JETTY_PID" $CH_USER -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
> -      then
> -        sleep 1
> -        if running "$JETTY_PID"
> -        then
> -          echo "OK"
> -        else
> -          echo "FAILED"
> -        fi
> -      fi
>   +
> -      start-stop-daemon -S -p"$JETTY_PID" $CH_USER -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
> 
> Then I checked the bug ticket too: https://bugs.eclipse.org/bugs/show_bug.cgi?id=403281, 
> but there seems be nothing about the root user check.

On 2013-10-13 22:54:25 -0400, Greg Wilkins wrote:

> start-stop-daemon is intended for system processes, hence we added that test.
> 
> Can you explain what you mean by "hang up the remote ssh session"?
> 
> The alternative to start-stop-daemon does a disown of the process, so it should be running correctly in the background.

On 2013-10-14 21:36:04 -0400, xzer lr wrote:

> sorry, it seems that I missed typing some words in my description.
> 
> we are using a shell script to login into the remote server automatically and restart the jetty server on the remote server by the following command:
> 
> ssh someuser@xxx.xx.x.xx 'jetty.sh restart'
> 
> since the 'someuser' is not root, your new jetty.sh will not start jetty by start-stop-daemon, hence the ssh session will catch the sysout and syserr from jetty process then hang up to wait the jetty process to finish.

**Comment by ettavolt** [comment]
I don't think this is an issue since v.9.2 at least.
Currently using this kind of script (copies of actually) to start several instances of jetty v.9.4:
```
cd "$( dirname "${BASH_SOURCE[0]}" )"
export JETTY_BASE=$( pwd )
export JAVA_OPTIONS="-Dname=value -XX:…"
/opt/jetty/bin/jetty.sh $*
exit $?
```
It doesn't block on start/stop or restart. And logging out of ssh session doesn't stop the instance.

**Comment by sbordet** [comment]
Closing as not an issue anymore.
