### ISSUE TITLE
Reading from ServletInputStream produces truncated HTTP packet

### ISSUE THREAD

**Issue by karoliskap** [eclipse/jetty.project#1286]
Jetty: jetty-all-9.4.1.v20170120
Java: 1.8.0_101
OS: Windows 10 Pro

The problem: ServletInputStream object reading a HTTP packet (example attached) from a stream produces less bytes than packet contains.

Code that produces the issue:

`
protected byte[] getRequestBody(ServletRequest request)
    {
        int length = request.getContentLength();
        if (length == 0)
            return null;

        byte[] body = null;

        try
        {
            int contentLength = request.getContentLength();
            if (contentLength > 0)
            {
                ServletInputStream inputStream = request.getInputStream();
                body = new byte[length];
                int got = inputStream.read(body);

                if (got != length)
                {
                    info("Invalid request - got " + got + " bytes instead of " + length);
                    return null;
                }
            }
        }
        catch (IOException e)
        {
            info("Invalid request header");
        }
        return body;
    }
`
Initially I suspected malformed packets coming from network. But capturing packets locally with Wireshark I found out that they arrive intact. So further debugging decompiled Jetty sources revealed that the problem is with Jetty do not correctly handling byte channel reading when all bytes do not arrive at once.

Attaching trace logs where it is visible that it reads remaining bytes after result COMPLETE. Here is an excerpt:

2017.01.26-09:28:38.950 [HTTPD] TRACE: close HttpParser{s=CONTENT,1087 of 1770}
2017.01.26-09:28:38.950 [HTTPD] TRACE: CONTENT --> CLOSE
2017.01.26-09:28:38.950 [HTTPD] TRACE: HttpChannelOverHttp@6b5dfac4{r=1,c=false,a=IDLE,uri=null} handle exit, result COMPLETE
2017.01.26-09:28:38.950 [HTTPD] TRACE: filled 683 SocketChannelEndPoint@c850de{/10.40.40.5:43769<->/10.40.40.240:9081,OSHUT,fill=-,flush=-,to=1/30000}{io=0/0,kio=0,kro=1}->HttpConnection@1d691730[p=HttpParser{s=CLOSE,1087 of 1770},g=HttpGenerator@5fe5fae3{s=START}]=>HttpChannelOverHttp@6b5dfac4{r=1,c=false,a=IDLE,uri=null}

I put a conditional breakpoint (note that sources are decompiled): ((HeapByteBuffer) buffer).position != 0 && ((HeapByteBuffer) buffer).position < 1800 && ((HeapByteBuffer) buffer).mark == -1
at ChannelEndPoint:fill(ByteBuffer buffer):if (LOG.isDebugEnabled()) // Avoid boxing of variable 'filled' 
For me request that produce incomplete packets always stop at this breakpoint.

Now if I run _channel.read(buffer); once more while standing at a breakpoint in a debugger it produces the remaining 683 bytes.
What I noticed that for each request this code line always called twice, but successful packets have all bytes red at the first time and 0 bytes at the second.

We used our in-house developed java http server before switching to Jetty. And looks like it had the same issue too. At the time I dismissed this as network issue, because it was very rare. That was in 2013-2015 and we were still using Java6 (later Java7). So at least for Java7 it was still there.

I've attaching example packet binary. But we have tried multiple times feeding it to Jetty and it always produced correct results. Also the same issue appears with both encrypted and plain text packets so it does not seem to be the issue with some special characters.

Also it is interesting to note that it always read the same number of bytes 1248 at the first time. In my case it is always this number. And I did rebooted my PC at least once. For other users I've seen a different number, but for a single reported the number is always the same.

Including thread dump at the time of breakpoint.
[threads_report.txt](https://github.com/eclipse/jetty.project/files/731865/threads_report.txt)
[log.txt](https://github.com/eclipse/jetty.project/files/731867/log.txt)
[packed_example.zip](https://github.com/eclipse/jetty.project/files/731868/packed_example.zip)

**Comment by sbordet** [comment]
The snippet of code that you wrote above is wrong, you don't read in that way from an `InputStream`.
The contract of `InputStream.read(byte[])` is (from the JavaDocs):

> Reads **up to** len bytes of data

Emphasis is mine.

When you call `InputStream.read(byte[])` you can get a number of bytes that is less than the length of the buffer you passed in; that's why the method has a return value.
Jetty could return you one byte at a time, and be a totally valid implementation of `InputStream`.

Your code expects that a single read will yield the whole buffer length, but that is rarely the case.

Performs your `InputStream` reads in a loop.
