### ISSUE TITLE
Missing servlet DTD files

### ISSUE THREAD

**Issue by paulmillar** [eclipse/jetty.project#1287]
Hi,

Jetty 8 included a dependency on servlet-api v2.3.  This version of the servlet-api included DTD files (e.g., web-app_2_3.dtd), which are used to validate deployment description XML infosets.

Jetty 9 depends on servet-api v3.1.  This version of servlet-api does NOT include the DTD files.

This is not immediately obvious: the XML parser will download the DTD files when necessary, so the lack of DTD files will likely be unnoticed by most internet-connected servers.

Some time ago, I opened [a ticket](https://java.net/jira/browse/SERVLET_SPEC-115) requesting this omission of DTD files be fixed:    

It turns out that the omission of the DTD files was deliberate.  The expectation is that frameworks, like Jetty, should include the DTD files themselves.  This is (apparently) true for GlassFish, but currently not true for Jetty.

Therefore, this ticket requests that Jetty be updated to include the files necessary to valid XML files within its jar files.

**Comment by janbartel** [comment]
@paulmillar jetty already has the dtds and schemas :)  It's in a jar in the distro in $jetty.home/lib/jetty-schemas-3.1.jar.   The maven coords are:                

org.eclipse.jetty.toolchain:jetty-schemas:3.1.M0

regards
Jan
