### ISSUE TITLE
HEAD requests not returning headers on 9.4

### ISSUE THREAD

**Issue by nevafuse** [eclipse/jetty.project#1288]
If I try a HEAD request on a path that returns headers with a GET request, no headers are returned.  There doesn't appear to be any logging indicating an issue.  The HEAD request works successfully on 9.3.10.v20160621 but not on 9.4.0.v20161208.

curl -I http://server:port/path/to

**Comment by sbordet** [comment]
```
$ curl -I https://webtide.com/
HTTP/1.1 200 OK
Set-Cookie: wordpress_google_apps_login=<omissed>; path=/; secure
Content-Type: text/html;charset=utf-8
Link: <https://webtide.com/wp-json/>; rel="https://api.w.org/"
Content-Length: 0
Server: Jetty(9.4.1.v20170120)
```

You must provide a failing case that we can reproduce, because works for us.

**Comment by nevafuse** [comment]
Have anything using the defaultservlet?  Serving static content?

**Comment by sbordet** [comment]
@nevafuse please submit a reproducible case.

**Comment by nevafuse** [comment]
@sbordet I just tried 9.4.1.v201170120 and the problem appears to be fixed.  Closing issue.
