### ISSUE TITLE
Allow to override the SslContextFactory on a per-destination basis

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#129]
migrated from Bugzilla [#419432](https://bugs.eclipse.org/bugs/show_bug.cgi?id=419432)
status ASSIGNED severity _normal_ in component _client_ for _7.6.x_
Reported in version _7.6.13_ on platform _PC_
Assigned to: Simone Bordet

On 2013-10-15 05:21:59 -0400, Simone Bordet wrote:

> When using client-side certificates, and the certificate is not known at HttpClient setup time, it would be good to be able to override the SslContextFactory on a per-request basis.
> 
> HttpsURLConnection allow this by having a setSSLSocketFactory(SSLSocketFactory) method.
> 
> Need to understand if it is better to have this at a per-destination level, or at a per-request level, and the interactions with the connection pool.

On 2013-10-18 05:34:48 -0400, Simone Bordet wrote:

> Definitely the SslContextFactory should be overridable per-destination, not per-request.

On 2013-10-18 06:05:27 -0400, Simone Bordet wrote:

> Fixed and pushed for Jetty 7 and 8. To be done for 9.1, probably skip it for 9.

**Comment by sbordet** [comment]
Closing this as it is possible to use different `HttpClient` instances, configured with different `SslContextFactory`s to implement the use case. 
An `HttpClient` will connect to certain destinations, other `HttpClient`s to other destinations.

For cases where it's not possible to use different `HttpClient` instances, see #4177.
