### ISSUE TITLE
http2-hpack not visible in OSGi

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1290]
Reported on stackoverflow: http://stackoverflow.com/questions/41870597/jetty-9-http-2-in-osgi-container-cannot-load-a-httpfieldpreencoder-implementati

**Comment by janbartel** [comment]
Fixed in jetty-9.4.x master ready for 9.4.2 release.

**Comment by akurtakov** [comment]
This causes issues for Eclipse Platform. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=512807 . Can we workaround it on our side somehow to not distribute apache aries bundles too?

**Comment by joakime** [comment]
Out of curiosity, how does the Eclipse Help system operate with HTTP/2?
HTTP/2 support requires a JVM specific Xbootclasspath setup to function.

Perhaps the Eclipse Help system should not rely on HTTP/2?
Just exclude the HTTP/2 components from your environment (they are optional anyway)

**Comment by joakime** [comment]
@akurtakov Jetty 9.4.2.v20170220 has been released.

**Comment by mbooth101** [comment]
Eclipse does not use http2, we use the "jetty-http" bundle only.

**Comment by joakime** [comment]
@mbooth101 then exclude all of the http2 jars/bundles/components, they are not needed/used, and are optional for Jetty.

**Comment by mbooth101** [comment]
Please see PR #1365
