### ISSUE TITLE
jetty-home has unresolvable dependencies

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#1292]
Same for jetty-distribution.
Use a simple pom as
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.olamy</groupId>
  <artifactId>foo</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-home</artifactId>
      <version>9.4.0.v20161208</version>
      <type>tar.gz</type>
    </dependency>
  </dependencies>
</project>
```
And try:
`
mvn compile
`
Result
`
[ERROR] Failed to execute goal on project foo: Could not resolve dependencies for project org.olamy:foo:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.jetty:jetty-home:tar.gz:9.4.0.v20161208 -> org.eclipse.jetty:test-jetty-webapp:war:9.4.0.v20161208: Failed to read artifact descriptor for org.eclipse.jetty:test-jetty-webapp:war:9.4.0.v20161208: Failure to find org.eclipse.jetty.tests:test-webapps-parent:pom:9.4.0.v20161208 in http://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
`

**Comment by jmcc0nn3ll** [comment]
home shouldn't have a dependency on test-jetty-webapp at all, we'll have to scrape that out
