### ISSUE TITLE
GOING_AWAY(1001) error code is not reported when server is shutdowning

### ISSUE THREAD

**Issue by rupashka** [eclipse/jetty.project#1293]
When jetty server is shutdowning WebSockets are closing with closeReason = 1005. I believe 1001 code should be used. I need to report some useful message to users when server is shutdowning....

jetty version: 9.3.14.v20161028

**Comment by joakime** [comment]
This seems related to Issue #1249

**Comment by rupashka** [comment]
No. The main problem is clients always get 1005 when server goes down. According to the spec:

1001 indicates that an endpoint is "going away", such as a server going down or a browser having navigated away from a page.

**Comment by joakime** [comment]
jetty-9.4.x (jetty-9.4.7-SNAPSHOT) has testcases that prove the 1001 going away behavior.
The ability of a websocket to send 1001 is dependent on many networking factors and states, a best effort is made, but there is no 100% guarantee that the 1001 will be received by the opposite side (OS behavior, various network buffers, etc all have an impact on this ability)
