### ISSUE TITLE
Remove Resource finalizers

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#130]
migrated from Bugzilla [#420234](https://bugs.eclipse.org/bugs/show_bug.cgi?id=420234)
status ASSIGNED severity *normal* in component *server* for *9.1.x*
Reported in version *9.1.0* on platform *All*
Assigned to: Project Inbox

On 2013-10-24 01:10:56 -0400, Greg Wilkins wrote nothing.
On 2014-06-25 13:02:28 -0400, Mikhail Mazursky wrote:

> As a quick improvement of the current situation I think it is possible to remove finalize() method from Resource class and only add it to classes where close() is not empty. This could decrease the number of objects that need to be finalized and hence help GC.

**Comment by gregw** [comment]
Closing in favour of #218
