### ISSUE TITLE
Uber jar has maven dependencies

### ISSUE THREAD

**Issue by jonnyzzz** [eclipse/jetty.project#1310]
I download uber jar from 9.3 and see it actually re-download same dependencies as all jar. 
Could you please remove dependencies that are not necessary (all?) from uber jar to avoid duplication

**Comment by jonnyzzz** [comment]
I use the following workaround now to declare the dependency in Gradle

```
dependencies {
   compile  group     : 'org.eclipse.jetty.aggregate',
                             name      : 'jetty-all',
                             version   : '9.3.15.v20161220',
                             classifier: 'uber',
                             transitive: false
}
```

**Comment by joakime** [comment]
https://dev.eclipse.org/mhonarc/lists/jetty-users/msg06030.html

No, the uber jar is not meant to be used in a project or build.
Use the dependencies and do not use the classifier 'uber'.

**Comment by jonnyzzz** [comment]
Why do you have it than?

Best regards,
Eugene Petrenko

**Comment by joakime** [comment]
As outlined in [the jetty-users message](https://dev.eclipse.org/mhonarc/lists/jetty-users/msg06030.html) i linked, its only remaining purpose is for the quick start documentation.

The jetty-all artifact is not, and cannot be, the entirety of Jetty anymore (this role ceased to be true in Jetty 9).

The future of jetty-all is even more uncertain when you take JDK9 and JPMS into account, its likely to be rendered entirely obsolete in the future.
