### ISSUE TITLE
Insufficient Bytes behavior change in jetty 9.4.x due to HTTP Trailers support?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1313]
It appears that the behavior with regards to insufficient bytes in Jetty 9.4.x has changed as a result of the HTTP Trailers support that was recently added.

Before the HTTP Trailer support was added, if a handler did the following ...

```java
        public void handle(String target, Request baseRequest, 
              HttpServletRequest request, HttpServletResponse response) 
              throws IOException, ServletException
        {
            baseRequest.setHandled(true);
            response.setContentLength(6);
            response.getWriter().write("foo");
        }
```

Then it would result in an HTTP Response with a server closed connection.

Now it will result in a server closed connection, with no response generated.

Look at the `jetty-server` tests, the `HttpManyWaysToCommitTest`.

This `testSetContentLengthAndWriteInsufficientBytes` testcase shows the behavior change.

This is what it looks like now ...

```java
    @Test
    public void testSetContentLengthAndWriteInsufficientBytes() throws Exception
    {
        server.setHandler(new SetContentLengthAndWriteInsufficientBytesHandler(false));
        server.start();

        HttpTester.Response response = executeRequest();
        // This is likely not right
        assertThat("response has no status", response.getStatus(), is(0));
        assertTrue("response eof", response.isEarlyEOF());
    }
```

This is what it looked like [during jetty-9.4.0 release](https://github.com/eclipse/jetty.project/blob/jetty-9.4.0.v20161208/jetty-server/src/test/java/org/eclipse/jetty/server/HttpManyWaysToCommitTest.java#L448-L468)

```java
    @Test
    public void testSetContentLengthAndWriteInsufficientBytes() throws Exception
    {
        server.setHandler(new SetContentLengthAndWriteInsufficientBytesHandler(false));
        server.start();

        try
        {
            // TODO This test is compromised by the SimpleHttpResponse mechanism.
            // Replace with a better client
            SimpleHttpResponse response = executeRequest();
            String failed_body = ""+(char)-1+(char)-1+(char)-1;
            assertThat("response code is 200", response.getCode(), is("200"));
            assertThat(response.getBody(), Matchers.endsWith(failed_body));
            assertHeader(response, "content-length", "6");
        }
        catch(EOFException e)
        {
            // expected
        }
    }
```

**Comment by sbordet** [comment]
@joakime, yes the behavior in 9.4.x has changed and we don't send anymore a response, but rather immediately close the connection. 
We have reviewed this together. I don't understand why are you reporting this ?

**Comment by joakime** [comment]
This issue was requested by @gregw he wanted to review it as well.

**Comment by gregw** [comment]
@sbordet I'm not sure we should just close without at least a 4xx response.  So I want to review again.
