### ISSUE TITLE
Recent class changes make websocket server depend on websocket-client.jar

### ISSUE THREAD

**Issue by hiepth** [eclipse/jetty.project#1314]
When upgrading my websocket server from jetty 9.3.12 to 9.4.1 and 9.3.16 the error below occurred.
Include websocket-client-9.3.16.v20170120.jar, javax-websocket-client-impl-9.3.16.v20170120.jar, jetty-client-9.3.16.v20170120.jar into classpath can fix this.

08/02 07:31:04.192 STDERR: java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/jsr356/ClientContainer
08/02 07:31:04.192 STDERR:      at java.lang.ClassLoader.defineClass1(Native Method)
08/02 07:31:04.192 STDERR:      at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
08/02 07:31:04.193 STDERR:      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
08/02 07:31:04.193 STDERR:      at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
08/02 07:31:04.193 STDERR:      at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
08/02 07:31:04.193 STDERR:      at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
08/02 07:31:04.193 STDERR:      at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
08/02 07:31:04.193 STDERR:      at java.security.AccessController.doPrivileged(Native Method)
08/02 07:31:04.193 STDERR:      at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
08/02 07:31:04.193 STDERR:      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
08/02 07:31:04.193 STDERR:      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
08/02 07:31:04.193 STDERR:      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
08/02 07:31:04.193 STDERR:      at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.configureContext(WebSocketServerContainerInitializer.java:139)
08/02 07:31:04.193 STDERR:      at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:194)
08/02 07:31:04.193 STDERR:      at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
08/02 07:31:04.193 STDERR:      at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:330)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
08/02 07:31:04.194 STDERR:      at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:253)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.server.Server.start(Server.java:422)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.server.Server.doStart(Server.java:389)
08/02 07:31:04.195 STDERR:      at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

**Comment by joakime** [comment]
That is correct.

The class `org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer` sets up the JSR-356 `javax.websocket` layer for Jetty.

The JSR-356 WebSocket Server component depends on the WebSocket Client component.

If you look at [`javax.websocket.server.ServerContainer`](http://docs.oracle.com/javaee/7/api/javax/websocket/server/ServerContainer.html) you'll see it extends `javax.websocket.WebSocketContainer`, which is the JSR-356 WebSocket Client.

What you are seeing is proper behavior, you need websocket-client when using JSR356.

**Comment by hiepth** [comment]
So we need more jar file ~500k size to upgrade from 9.3.12 to 9.4.1.
May be split dependency classes to something like websocket-common.jar help?
