### ISSUE TITLE
ClientConnector abstraction

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#132]
migrated from Bugzilla [#423722](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423722)
status ASSIGNED severity _enhancement_ in component _client_ for _9.1.x_
Reported in version _9.1.0_ on platform _PC_
Assigned to: Project Inbox

On 2013-12-10 11:15:07 -0500, Simone Bordet wrote:

> While Jetty has a clear ServerConnector abstraction, that can work with multiple connection factories to handle a number of different protocols, a similar, client-side abstraction is missing for the client.
> 
> Requirements:
> 1. Be able to wrap an existing SocketChannel, already connected, with Jetty's EndPoint and Connection objects.
> 2. Support NPN or ALPN negotiation. This must be supported at 2 levels: in a SPDYClient and in a HTTPClient. The SPDY client part is already implemented, but the HTTPClient part is difficult to make it work, especially with the SPDY client transport. This is because HttpClient has its own SelectorManager, and the SPDY HttpClientTransport uses SPDYClient, which also has its own SelectorManager. When opening the connection, it is not known yet that the protocol will be SPDY, so HttpClient opens that SocketChannel. Then the SPDY protocol is selected, but it is now difficult to "pass" the opened socket to SPDYClient's SelectorManager.
> 3. Be able to share a single SelectorManager component among different "clients". This is useful for HttpClientTransports
> 4. Have a clear semantic for idle timeouts, especially for multiplexed protocols, at the connection level. What would it mean to set the connection idle timeout to 1000 ms for a multiplexed protocol ?
> 
> See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=404889.

**Comment by joakime** [comment]
@sbordet  This has been implemented in jetty-client long ago, right? Can we close this?

**Comment by sbordet** [comment]
Nope, not yet implemented, leave open.

**Comment by joakime** [comment]
@sbordet isn't this complete (for Jetty 10) ?

**Comment by sbordet** [comment]
This was merged in #3267.
