### ISSUE TITLE
Request.extract*Parameters() behaves differently with UTF8 vs ISO88591

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1322]
If you have a UTF8 scenario, and a bad codepoint/encoding is encountered, a UTF8 replacement string is used and parsing continues.

If you have ISO88591, then there is an immediate failure and no further parsing is performed.

Either the UTF8 scenario should throw immediately, or the ISO88591 scenario should use replacement strings and attempt to continue parsing.

**Comment by joakime** [comment]
After a conversation with @gregw it was felt that the behavior of the UTF8 side with replacement characters should be changed to throw on first failure, like the `extract*Parameters()` methods do for ISO88591.   But this would need adequate testing to know what the fallout could be.

**Comment by joakime** [comment]
This was discovered during a conversation about issue #1316

**Comment by joakime** [comment]
Note: the origin of the UTF8 replacement character behavior in Jetty can be found at https://bugs.eclipse.org/411538 (first showed up in Jetty 9.0.5)

**Comment by joakime** [comment]
Commit 32ec8255db2b2923142dbe0f8b26128ca26d79a9 introduced the UTF8 replacement character behavior in Jetty query processing.

**Comment by joakime** [comment]
The non-UTF8 replacement character behavior was added as part of https://bugs.eclipse.org/399703 on commit 1610329d3eff744c99d3d1767f6e53e121ab310d

**Comment by joakime** [comment]
@gregw this issue and https://bugs.eclipse.org/399703 seem very similar.

**Comment by gregw** [comment]
@joakime I agree with the summary there: decoding errors should be handled with the replacement character.  But I also think the decoder should throw and allow higher levels to decide if that is fatal or not.

As discussed, throwing BadMessage is a good choice to work towards (if the class is visible to the decoders).  More over, the default behaviour of jetty should be to allow such exceptions to result in a 400 response.

However, I think we need to make changes in a considered fashion, just in case there are unintended consequences.  I suggest making the changes in a branch that we can test on some tame deployments.

**Comment by joakime** [comment]
Closing as not an issue.
