### ISSUE TITLE
High CPU with Jetty & java 1.7

### ISSUE THREAD

**Issue by computinglife** [eclipse/jetty.project#1323]
Hi, 

We use Openfire for running a small chat system & it uses Jetty underneath.The Jetty version is 9.2.14.v20151106. We are currently profiling a high cpu issue right now, which is affecting the throughput. I ran with hprof enabled with cpu sampling option - 

The thread that shows up on top are Jetty, mainly involving epollWait. I was wondering if there is a bug about this on JDK / Jetty, like JDK-6403933. 

To be fair, this shows up only when load is running and process is churning through http IO.

Linux kernel version is 2.6.32-573.18.1.el6.x86_64 & the java version is Sun java 1.7.0_101-b14 

Thanks in advance for any response. 

Rgds
Arun

The stack that shows up are 

TRACE 303608:
	sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java:Unknown line)
	sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:600)
	org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:549)
	org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	java.lang.Thread.run(Thread.java:745)

TRACE 303862:
	sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java:Unknown line)
	sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	org.apache.mina.transport.socket.nio.NioSocketAcceptor.select(NioSocketAcceptor.java:234)
	org.apache.mina.core.polling.AbstractPollingIoAcceptor$Acceptor.run(AbstractPollingIoAcceptor.java:417)
	org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:745)

TRACE 303611:
	sun.nio.ch.ServerSocketChannelImpl.accept0(ServerSocketChannelImpl.java:Unknown line)
	sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	java.lang.Thread.run(Thread.java:745)

TRACE 304058:
	sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java:Unknown line)
	sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:72)
	org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1077)
	org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:745)

**Comment by joakime** [comment]
Run a Heap Dump when its in high-cpu.

Look for the ManagedSelectors, report back how many you have, and also who owns them.

**Comment by computinglife** [comment]
The issue hasn't happened since then for whatever reason. Thank you for your fast response.

**Comment by santosh103** [comment]
Has anyone found any solution. I am also facing similar problem with exactly same stack trace.

**Comment by gregw** [comment]
@santosh103 make sure you are on the latest 9.2.x release and latest java 7.  Both of these are end of life, so we are not going to be able to give you much help solving this... other than to say upgrade.

Alternately, you can try falling back to jetty 8, which was probably a bit more stable than the 9.2.x series

**Comment by santosh103** [comment]
We are already using Jetty 9.3.7 and java is 1.8.0_91.


It looks like thread goes on infininite loop which causes high cpu usage. I just suspended the thread and then resumed and then cpu usage came down to normal.


Also this looks to be some boundary condition as it happened only couple of times while I am running endurance testing for couple of days.


________________________________

**Comment by gregw** [comment]
If you have identified the infinite thread and can suspend/resume it, then it would be of great value to get several stack traces from it to see where it goes in it's loop.
