### ISSUE TITLE
Broken link on documentation index page

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1324]
The link to the 9.3.16.v20170120 documentation (https://www.eclipse.org/jetty/documentation/9.3.16.v20170120) is broken.

**Comment by jmcc0nn3ll** [comment]
pom.xml on eclipse/jetty.website needs updated to pull this or axe it out of the doc version table (which is appropriate imo since 9.4.x replaces 9.3.x as stable.

**Comment by WalkerWatch** [comment]
Committed this change in 8bbb1a4 in eclipse/jetty.website
