### ISSUE TITLE
Jetty shutdown command got NullPointerException (http2 module added to start)

### ISSUE THREAD

**Issue by sige224** [eclipse/jetty.project#1326]
Follow this commands:
1. mkdir testApp
2. java -jar ../start.jar --add-to-start=http,http2,deploy,annotations
3. java -DSTOP.KEY=KEY -DSTOP.PORT=2222 -jar ../start.jar 
Start successfully.

Another terminal:
1. java  -jar ../start.jar STOP.PORT=2222 STOP.KEY=KEY STOP.HOST=127.0.0.1 --stop
java.lang.NullPointerException
	at org.eclipse.jetty.start.Main.stop(Main.java:576)
	at org.eclipse.jetty.start.Main.stop(Main.java:519)
	at org.eclipse.jetty.start.Main.doStop(Main.java:507)
	at org.eclipse.jetty.start.Main.start(Main.java:402)
	at org.eclipse.jetty.start.Main.main(Main.java:77)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information

If I remove http2 module, stop command works successfully.

**Comment by joakime** [comment]
Which specific version of Jetty?

**Comment by sige224** [comment]
Thanks for reply. jetty-9.4.1.v20170120

**Comment by sige224** [comment]
I change start command to : java -jar ../start.jar STOP.KEY=KEY STOP.PORT=2222
Jetty can be shutdown successfully.

**Comment by joakime** [comment]
Reopening ... We should, at a minimum make the NPE a bit more clear/meaningful.
