### ISSUE TITLE
Consider dropping non-standard "%uXXXX" encoding support

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1327]
The "%uXXXX" encoding support we have in our `UrlEncoded` class is for very old IIS based compatibility, and is not a codified standard at ietf.org or microsoft.com

This will simplify much of what exists in our UrlEncoded implementation.

**Comment by gregw** [comment]
+1

**Comment by joakime** [comment]
This has already been dropped in Jetty 9.4.4+ already.
