### ISSUE TITLE
DSA cipher suites not supported by embedded jetty 9.4 in java

### ISSUE THREAD

**Issue by tangenbo** [eclipse/jetty.project#1338]
I am using the latest jetty and jdk, it should be supporting DSA cipher suites like TLS_DHE_DSS.... So I generated a certificate file and key pairs with DSA algorithm, uploaded it to my server, and restarted my server, the server started successfully. But after that, I could not use any browser to open any page of that server. All I saw is an error message on the page: ERR_SSL_VERSION_OR_CIPHER_MISMATCH.

Could anyone help me with this? Is there any issue with jetty for DSA?

**Comment by joakime** [comment]
Dump your startup and look at why the ciphers you are interested in are disabled.

```
$ cd /path/to/my/jettybase
$ java -jar /path/to/jetty-dist/start.jar jetty.server.dumpAfterStart=true
```

Look for the `SslContextFactory` tree, and the `Cipher Suites` branch.
The `Disabled` section will list every disabled Cipher suite, and also indicate where that particular cipher suite was disabled.

You'll see... 

`JreDisabled` which means that the JVM itself has it disabled.
`ConfigExcluded` which means that your `${jetty.base}` configuration has it disabled.

Either way you'll want to look at the [Enabling / Disabling Specific Cipher Suites](https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html#configuring-sslcontextfactory-cipherSuites) in the documentation to understand how to set it up to suite your particular needs.

> Note: on my environment (OpenJDK 8u111) there's only 2 Cipher Suites starting with `TLS_DHE_DSS...` are  `TLS_DHE_DSS_WITH_AES_128_CBC_SHA` and `TLS_DHE_RSA_WITH_AES_128_CBC_SHA`, both of which are disabled by default due the fact that they use the SHA/SHA0/SHA1 vulnerable algorithms.  All web browsers permanently disabled SHA/SHA0/SHA1 on Jan 1, 2017 as part of the global SHA deprecation.
> Current JDK9 EA releases have already disabled SHA/SHA0/SHA1, and the next update to Java 8 (after update 121) is expected to do the same.
> When TLS/1.3 hits, SHA/SHA0/SHA1/MD5 will be impossible to configure.

**Comment by tangenbo** [comment]
But I actually have enabled related ciphers through sslContextFactory.setIncludeProtocols("TLS_DHE_DSS.*"), and my codes server.getConnectors()[1]).getConnectionFactory(SslConnectionFactory.class).getSslContextFactory().dump() can dump such things:

+- Cipher Suite Selections
     +- Enabled (size=24)
     |   +- TLS_DHE_DSS_WITH_AES_128_CBC_SHA
     |   +- TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
     |   +- TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
     |   +- TLS_DHE_DSS_WITH_AES_256_CBC_SHA
     |   +- TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
     |   +- TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
     ...

So I think this is a bug of Jetty?
