### ISSUE TITLE
Reinstate AJP support in Jetty 9

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#134]
migrated from Bugzilla [#425244](https://bugs.eclipse.org/bugs/show_bug.cgi?id=425244)
status ASSIGNED severity _enhancement_ in component _server_ for _9.1.x_
Reported in version _9.1.0_ on platform _PC_
Assigned to: Project Inbox

On 2014-01-09 19:38:31 -0500, Samuel Beeman wrote:

> Per http://wiki.eclipse.org/Jetty/Howto/Configure_AJP13, filing a ticket to reinstate jetty-ajp support in Jetty 9.
> 
> I am currently using Jetty 8 for an enterprise web product that requires AJP support. The real-world use case is allowing X509 client (i.e. browser) certificate authentication with a Jetty server sitting behind a reverse proxy. The reverse proxy and client cert auth are both requirements due to business constraints.
> 
> Per http://www.zeitoun.net/articles/client-certificate-x509-authentication-behind-reverse-proxy/start, there are two main ways to address this problem. The first solution requires installation of headers modules and reconfiguration of the reverse proxy, which is unfortunately not possible due to no root access. The second solution is to use AJP, which contains support for passing along the client certificate via +ExportCertData. This is the approach that has been taken, and hence why my application requires AJP support.
> 
> Jetty 8 is stable, but I now would like to take advantage of new features in Servlet 3.1, which is only available in Jetty 9.1.0. The lack of AJP support in Jetty 9.1 is hence a blocker.

On 2014-01-09 20:51:11 -0500, Greg Wilkins wrote:

> Using apache mod_proxy to forward the request to Jetty as HTTP rather than as AJP is preferable.    The last time we benchmarked this we achieved 15% better throughput with HTTP rather than AJP!
> 
> Is the work required to encode the x509 details in headers significant?  It is pretty simple in Jetty to extract such details from headers and add them to the request correctly.
> 
> Note that jetty AJP would need to be extensively rewritten (for the better) to work with the new jetty-9 multi protocol architecture, so it is not a trivial port.
> 
> Note also, while this issue may be a blocker for your application, it is not a blocker for further releases of jetty, so I'm changing the priority to enhancement request.

On 2014-01-09 22:56:38 -0500, Samuel Beeman wrote:

> Hi Greg,
> 
> Thanks for your quick response, and apologies for filing under the wrong priority.
> 
> Unfortunately, approval for configuration changes to the reverse proxy (to add the appropriate headers) is nearly impossible to obtain, and the reverse proxy has been set up to use AJP long before my time.
> 
> I too would prefer to have simply HTTP headers instead of going through an outdated protocol with worse performance, but that doesn't seem to be an option in this case. Without Jetty 9 AJP support, the only other workaround I see is to switch to Tomcat 8, which would be unfortunate as we've already invested quite heavily in Jetty.

On 2014-01-09 23:16:34 -0500, Greg Wilkins wrote:

> Samuel,
> 
> thanks for the explanation.   I accept that getting front line server changes can be hard in many deployment environments, so that is a valid non-technical use case for supporting AJP.
> 
> However, I'm not sure what priority we can give this as it is not a simple port and will need a substantial rewrite.  However the result should be a better connector as the jetty-9 multi-protocol support is far far better than jetty-8, so perhaps the result will be highly performance?
> 
> I'll chat to the powers that be about resourcing this.

On 2014-01-15 02:28:07 -0500, Samuel Beeman wrote:

> Hi Greg, any updates on this ticket?

On 2014-01-15 12:03:19 -0500, Jesse McConnell wrote:

> It would be some time before we got to this from the open source perspective, if at all, we simply do not get a lot of requests for the functionality...having said that you are not the first person I have heard mention having it resurrected so if you ping me at jesse@intalio.com we can discuss other options.  Historically we have had some of these sorts of low interest/high value features sponsored by interested parties.  Ping me if you are interested in knowing more.
> 
> cheers

On 2014-07-08 07:56:33 -0400, Martin Goldstone wrote:

> Just to add a +1 to this, we're using an application from a commercial provider which runs on Jetty. We are using Shibboleth for authentication in the current release of it.  The product internally uses the remote_user variable, and this is set by mod_shib in Apache. In order to pass this through, we have to use AJP. The new version of this software uses Jetty 9, so we find our upgrade path blocked by this. Unfortunately we can't use HTTP with mod_proxy, as this would mean the application would have to be adapted by our supplier to make use of a custom request header. If this modification is possible, it will be quite expensive for us.

On 2015-03-28 17:39:13 -0400, Christian Sprajc wrote:

> +1 from me aswell. We also use AJP + Apache mod_shib for Shibboleth user authentication.

On 2015-04-16 10:44:09 -0400, Scott Koranda wrote:

> The Laser Interferomter Gravitational-Wave Observatory (LIGO) is a large NSF funded project to detect signals from energetic astrophysical events like the collision of two black holes. We also use AJP + Apache with the Shibboleth Identity Provider (IdP) and REMOTE_USER and would like to move to using Jetty instead of Tomcat. We would like to see AJP support restored.

On 2015-04-16 11:26:26 -0400, Joakim Erdfelt wrote:

> Possible alternative approach?
> 
> http://serverfault.com/a/231577 - how to setup REMOTE_USER for mod_proxy

On 2015-04-19 21:06:10 -0400, Greg Wilkins wrote:

> Just to set expectations here....
> 
> It is exceedingly unlikely that we will find time to re-instate AJP support as there is so much work to do with HTTP/2 and soon Servlet 4.0 that more than consumes our available development resources.
> 
> If AJP is to make a comeback, then it is either going to need a community contribution of code or a commercial support customer that requires AJP.  Sorry, but that is just the reality of the situation and we'd need a whole bunch more +1's before priorities will change this.

**Comment by sprajcpf** [comment]
FYI: We successfully migrated from AJP to HTTP using Apache + mod_shib -> jetty/PowerFolder Server. It requires a bit more configuration of the Apache, but that's ok: 

- https://wiki.powerfolder.com/display/PFS/Apache+configuration
- https://wiki.powerfolder.com/display/PFS/Shibboleth+Configuration

Also we needed to re-encode the attributes values from ISO-8859-1 / UTF-8 for whatever reason.

So there is a -1 from us for this feature request.

**Comment by jmcc0nn3ll** [comment]
Really is for the best to not use AJP.  I don't know when or if we will bring this support back...obviously not in a huge rush to resurrect it.

**Comment by joakime** [comment]
AJP has been removed from the jetty codebase entirely back in September 2012.

The AJP layer is dead on Jetty.

Anyone seeing this issue, please note that Apache `mod_proxy` is much better supported and is superior in every way to the old `mod_proxy_ajp`.
