### ISSUE TITLE
Lost connection with secure websocket and Java 8u121

### ISSUE THREAD

**Issue by lisandroTSilva** [eclipse/jetty.project#1344]
I can't establish secure websocket communication (wss) using Java 8u121, in previous versions of java it worked perfectly.

I notice that non-secure websocket (ws) works perfectly on any version.

I use the libraries below:
- websocket-server-9.3.15.v20161220.jar
- websocket-common-9.3.15.v20161220.jar
- websocket-api-9.3.15.v20161220.jar
- jetty-util-9.3.15.v20161220.jar
- jetty-io-9.3.15.v20161220.jar
- websocket-client-9.3.15.v20161220.jar
- websocket-servlet-9.3.15.v20161220.jar
- javax.servlet-api-3.1.0.jar
- jetty-servlet-9.3.15.v20161220.jar
- jetty-security-9.3.15.v20161220.jar
- jetty-server-9.3.15.v20161220.jar
- jetty-http-9.3.15.v20161220.jar

Code snippet

```
Server server = new Server();

SslContextFactory sslContextFactory = new SslContextFactory();
sslContextFactory.setKeyStorePath(EventServer.getKeystorePath());
sslContextFactory.setKeyStorePassword("..........");
sslContextFactory.setKeyManagerPassword("..........");
sslContextFactory.setCertAlias("myAlias");
		
SslConnectionFactory sslConnectionFactory = new SslConnectionFactory(sslContextFactory, HttpVersion.HTTP_1_1.asString());
HttpConnectionFactory httpConnectionFactory = new HttpConnectionFactory(new HttpConfiguration());
ServerConnector sslConnector = new ServerConnector(server, sslConnectionFactory, httpConnectionFactory);

sslConnector.setPort(1212);
sslConnector.setIdleTimeout(0);

server.addConnector(sslConnector);

ServletContextHandler cntx = new ServletContextHandler(ServletContextHandler.SESSIONS);
cntx.setContextPath("/");
server.setHandler(cntx);

ServletHolder holder = new ServletHolder("jja", EventServlet.class);
cntx.addServlet(holder, "/jja");

try {
	server.start();
	server.dump(System.err, "");
	server.join();
} catch (Exception t) {
	t.printStackTrace();
}
```

**Comment by joakime** [comment]
Other then your unconfigured `HttpConfiguration` the rest is fairly normal.

Went ahead and added a [`SecureWebSocketServer.java`](https://github.com/jetty-project/embedded-jetty-cookbook/blob/master/src/main/java/org/eclipse/jetty/cookbook/websocket/SecureWebSocketServer.java) example to the [`embedded-jetty-cookbok`](https://github.com/jetty-project/embedded-jetty-cookbook) to demonstrate.

**Comment by joakime** [comment]
Closing due to lack of info and replication.   Feel free to reopen (or ask for a reopen) if you can provide a replication testcase. (your demo code does not replicate)
