### ISSUE TITLE
LdapLoginModule with embedded Jetty

### ISSUE THREAD

**Issue by agileheat** [eclipse/jetty.project#1349]
I have the following initialization for my Jetty Servlet.  HashLoginService works however I the LdapLoginModule is not connected to JAASLoginService, "ldaploginmodule" refers to the default ldap-loginModule.conf which I want to skip and pass all the paramters in the options Map (or somehow specify as file location).

    Server jettyServer = new Server(8080);

    ServletContextHandler context = new ServletContextHandler(jettyServer, "/", ServletContextHandler.SESSIONS | ServletContextHandler.SECURITY);

    context.addServlet(new ServletHolder(new DefaultServlet() {
        @Override
        protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
            request.getSession().invalidate();  // do logout
            response.getWriter().append("<html><form method='POST' action='/j_security_check'>"
                + "<input type='text' name='j_username'/>"
                + "<input type='password' name='j_password'/>"
                + "<input type='submit' value='Login'/></form></html>");
             }
         }), "/login");

    context.addServlet(new ServletHolder(new MyServlet()),"/*");

    Constraint constraint = new Constraint();
    constraint.setName(Constraint.__FORM_AUTH);
    constraint.setRoles(new String[]{"user"});
    constraint.setAuthenticate(true);

    ConstraintMapping constraintMapping = new ConstraintMapping();
    constraintMapping.setConstraint(constraint);
    constraintMapping.setPathSpec("/*");

    ConstraintSecurityHandler securityHandler;

    if (ldapEnabled) { // *** something is missing ****
        LdapLoginModule lm = new LdapLoginModule();
        Map options = new HashMap<>();
        options.put( "hostname", "127.0.0.1" );
        options.put( "port", "389" );
        options.put( "contextFactory", "com.sun.jndi.ldap.LdapCtxFactory" );
        options.put( "bindDn", "CN=admin,OU=example,OU=com" );
        options.put( "bindPassword", "password" );
        options.put( "userBaseDn", "dc=example,dc=com" );
        lm.initialize(null,null,null,options);

        securityHandler = new ConstraintSecurityHandler ();
        securityHandler.addConstraintMapping(constraintMapping);
        JAASLoginService loginService = new JAASLoginService("ldaploginmodule");
        loginService.setIdentityService(new DefaultIdentityService());
        securityHandler.setLoginService(loginService);
    } else {  // This works
        securityHandler = new ConstraintSecurityHandler();
        securityHandler.addConstraintMapping(constraintMapping);
        HashLoginService loginService = new HashLoginService();
        loginService.putUser("username", new Password("password"), new String[]{"user"});
        securityHandler.setLoginService(loginService);
    }

When users tries to login in ldapEnabled mode

HTTP ERROR: 500

Problem accessing /j_security_check. Reason:

    java.io.IOException: ldap-loginModule.conf (No such file or directory)

How can I get this working without using configuration files (*the jetty server is **embedded** inside another app as a dynamically loaded jar*)

**Comment by janbartel** [comment]
So you must still be passing the property jaas.login.conf on the runline? I think a lot of this is out of our control, as it is mediated by jvm classes - have you checked in the jvm documentation for programmatic login module configuration?

**Comment by janbartel** [comment]
As I commented before, I think the programmatic configuration of jaas classes is something that would have to be supported at the jvm level. I'm closing this as an issue - it is more in the nature of a request for advice, and so probably better addressed to the jetty-users@eclipse.org mailing list anyway.
