### ISSUE TITLE
Pause accepting incoming connections when server is under low resource to prevent jetty from OOME

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#135]
migrated from Bugzilla [#425640](https://bugs.eclipse.org/bugs/show_bug.cgi?id=425640)
status ASSIGNED severity *enhancement* in component *server* for *9.1.x*
Reported in version *9.1.0* on platform *PC*
Assigned to: Project Inbox

On 2014-01-14 05:16:16 -0500, Zen Zhong wrote:

> I'm running jetty-9.1.0.v20131115, jetty is used as Comet server, it may hold more than 1 million connections, I want to prevent jetty from OOME when there're many connections, so I tried lowresources module and looked into org.eclipse.jetty.server.LowResourceMonitor.java, I found it will try to close all alive connections and jetty will still accept incoming connections.
> 
> Is it possible to pause accepting incoming connections when server is under low resource?

On 2014-01-19 19:17:13 -0500, Greg Wilkins wrote:

> 
> Zen,
> 
> 1,000,000 connections is a really nice number! Both for your application and for jetty/cometd!
> 
> However, this is a difficult use-case to solve generically as many different applications will want to handle low resources differently.
> 
> But jetty is very extensible and you can probably add some behaviour to achieve this fairly easily by extending the ServerConnector accept method to have a mutex and  extending the LowResources monitor setLowResources method to grab and hold that mutex to stop the accepting.
> 
> I guess this could perhaps be added in a generic way to the connectors.... but I'd like to see/hear how this goes for your specific use-case.

On 2014-01-20 05:34:33 -0500, Zen Zhong wrote:

> Thanks Greg. I'll try it and feedback later.

**Comment by joakime** [comment]
Please reopen if this is still an issue.
