### ISSUE TITLE
jetty-server does not have jetty-util with the same version as dependency in pom.xml

### ISSUE THREAD

**Issue by MattiL** [eclipse/jetty.project#1354]
jetty-server does not have jetty-util with the same version as dependency in pom.xml
This has lead to too old jetty-util being included.
E.g.
http://stackoverflow.com/questions/37269049/eclipse-project-move-from-linux-to-windows-10-causes-class-not-found-errors

**Comment by joakime** [comment]
This is not reproducible with our own builds (on various flavors of Linux, various versions of OSX, various versions of Windows, even different versions of the JDK).

We would need a reproduction testcase to understand what you are experiencing.

**Comment by joakime** [comment]
OP no longer working on Java.
