### ISSUE TITLE
RolloverFileOutputStream: No rollout performed at midnight

### ISSUE THREAD

**Issue by panchi** [eclipse/jetty.project#1357]
Since [this commit](https://github.com/eclipse/jetty.project/commit/9f317dee94404f5ed4573b6109fcfe59bf3a5268) RolloverFileOutputStream.scheduleNextRollover() is wrongly calling Timer.schedule() and that results in the first rollout to be scheduled in more than 47 years rather than next midnight.

I added [a comment](https://github.com/eclipse/jetty.project/commit/9f317dee94404f5ed4573b6109fcfe59bf3a5268#commitcomment-21057902) about that with a possible fix.

**Comment by joakime** [comment]
There is something wrong with the TZ data either on your system, or your java installation then.

**Comment by panchi** [comment]
Hi Joakime, the [documentation](https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html#schedule(java.util.TimerTask,%20long)) states that the **long** parameter is a **delay** parameter rather than an epoch-milli-timestamp.

I think, the **schedule(...)** method which receives a Date parameter must be used as it was before. The code may remain the same as it is now, and the second parameter of the schedule call wrapped with a **new Date(...)**

¿What do you think?

**Comment by joakime** [comment]
Yes, that's correct.  `schedule(task, delay)` is the behavior.

Its interesting that this isn't actually manifesting as a bug in various installations with this change atm.
Will dig into it.

**Comment by panchi** [comment]
Hi Joakime, glad that we agree now.

It is manifesting as bug when **NCSARequestLog** is used, I noticed that after upgrading jetty requests logs stopped rotating at all.

**Comment by joakime** [comment]
The analysis is sound, the behavior in several production cases says otherwise.
We're missing something.

**Comment by joakime** [comment]
Added RolloverFileOutputStreamTest and some minor refactors to sanity check the behavior better.

Will be merged to 9.4.x this week

**Comment by panchi** [comment]
Hi Joakime, using **schedule(task, delay)** will schedule the next rollover **delay** millis at the moment is called because it uses internally **System.currentTimeMillis**. 

The method **scheduleNextRollover** is called after **setFile** (which performs I/O operations like rename) so it may be unsafe to assume that **schedule(..)** will be called exactly at midnight, rather it may be called some little before. If that little before is 1 ms or more, the next rollout won't be scheduled exactly at next midnight.

Even using something like:
`__rollover.schedule(_rollTask,midnight.toInstant().toEpochMilli() - System.currentTimeMills());`
may not be accurate, because **System.currentTimeMills()** may answer different numbers in two consecutive calls. So it seems that using a **schedule** with a **delay** will be unsafe anyways.

Calling something like this:
`__rollover.schedule(_rollTask, new Date(midnight.toInstant().toEpochMilli()));`
will make Timer class to internally call:
`sched(_rollTask, midnight.toInstant().toEpochMilli(), 0);`
because it uses **Date.getTime()** which return the same **long** passed in the constructor.

¿What do you think?

**Comment by joakime** [comment]
We specifically moved away from schedule(task, Date) as it causes problems with time jitter (from OS) and also Daylights Savings Time.

It went from sometimes not firing at all, to firing +/- a few ms.

**Comment by panchi** [comment]
Yes, but computing correctly **when** the next rollout should happen, which had the DST problem you mentioned and now seems fixed, is independent on **how** Timer class it is used.

Using new Date() here should not break the DST fix as it will be used after the new **midnight** value is computed and only has to do on how **sched(..)** is internally called. Unfortunately Timer class does not have any other public method to use if you want to make a best effort to schedule a task in a specific timestamp.

These ms delays are accumulative, so after some days many log lines may be incorrectly written to a request log file for another date.

**Comment by joakime** [comment]
Its not accumulative, the scheduleNextRollover always resets to start of day.

**Comment by panchi** [comment]
Hi Joakim, about the accumulation please take a look at the following example:

* First rollout is scheduled OK at T (where T is some day at exactly midnght)
* First rollout is performed OK at T and there is a delay of 1ms in **setFile**
* Therefor, first **scheduleNextRollover** executin is done at day T + 1ms, where new **midnight** value is correctly compued at the start of the day so the result of **midnight.toInstant().toEpochMilli() - lastMs** is exactly 1 day.
* Second rollout is scheduled at **"now" + 1 day** which is **T + 1 day + 1ms**
* Second rollout is performed at T + 1 day + 1ms and there is also a delay of 1ms in **setFile**
* Second **scheduleNextRollover** execution is done at day T + 1 day + **2ms**, where new **midnight** value is correctly compued at the start of the day so the result of **midnight.toInstant().toEpochMilli() - lastMs** is exactly 1 day.
* Third rollout is scheduled at **"now" + 1 day** which is **T + 2 day + 2ms**
* Third rollout is performed at T + 2 day + 2ms.

This results in the third rollout accumulating both delays.

Do you see something wrong in my sequence?

**Comment by panchi** [comment]
Hi Joakim, another potential problem when using the **delay** approach is that, if the executing thread is paused for a significant amount of time (eg: in a Full GC) just before [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/Timer.java?av=f#193) 
`sched(task, System.currentTimeMillis()+delay, 0);`
that will result in a wrongly scheduled rollout, so that function is not reliable in order to do a best efffort to accurately schedule an event in a specific timestamp.

Instead, passing a **new Date(midnight.toInstant().toEpochMilli())** is not affected by that nor another unexpected behaviour, and will result as the same as this call
`sched(task, midnight.toInstant().toEpochMilli(), 0);`
because the Date object is used as merely **long** wrapper and nothing else.

**Comment by joakime** [comment]
Been testing 9.3.17.RC0 a few days now.
Seems to be working properly.
