### ISSUE TITLE
A little doubt. [Proxy]

### ISSUE THREAD

**Issue by Kurimatzu** [eclipse/jetty.project#1359]
Server server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(3311);
        server.addConnector(connector);

        // Setup proxy handler to handle CONNECT methods
        ConnectHandler proxy = new ConnectHandler();
        server.setHandler(proxy);
   
        server.start();

How do I make a "Handler" that can capture the events? (When a page was loaded, etc.)

**Comment by joakime** [comment]
What sort of information are you trying to capture? (there might be a different approach)

**Comment by Kurimatzu** [comment]
@joakime  Want to do an event type, when you load a page, if the page is in a list of disallowed pages won't load, or a custom error page.

**Comment by joakime** [comment]
Then create a new Handler, call it `ForbiddenHandler`, check for the `CONNECT` method, and the URI provided, do your own check on if its valid or not.

If its invalid ...
  * use `HttpServletResponse.sendError(HttpServletResponse.SC_FORBIDDEN);`
  * `Request.setHandled(true)`

If its valid, do nothing.

Put the new `ForbiddenHandler` in front of the standard `ConnectHandler`.

**Comment by Kurimatzu** [comment]
You can prevent the loading of the page?

Send an error saying the page is offline?

**Comment by joakime** [comment]
Up to you what you want the response to look like.
Sending SC_FORBIDDEN will show up as a HTTP 403 Response to the client. (which may make sense for some clients)
