### ISSUE TITLE
HttpSession expiration and lifetime for WebSocket connections

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#136]
migrated from Bugzilla [#427130](https://bugs.eclipse.org/bugs/show_bug.cgi?id=427130)
status ASSIGNED severity _normal_ in component _websocket_ for _9.1.x_
Reported in version _9.1.1_ on platform _PC_
Assigned to: Joakim Erdfelt

On 2014-01-31 10:19:34 -0500, Simone Bordet wrote:

> HttpSession has a default expiration of 30 mins.
> 
> An application may create/access the HttpSession during the WebSocket upgrade and store data into it.
> 
> If then the application exchanges WebSocket messages for 1 hour, is the HttpSession supposed to expire after 30 mins or is it supposed to stay alive for the duration of the connection ?

On 2014-09-22 18:18:57 -0400, Joakim Erdfelt wrote:

> Some discussion about this relationship ...
> 
> https://java.net/jira/browse/WEBSOCKET_SPEC-5 - HttpSession and authenticated user
> https://java.net/jira/browse/WEBSOCKET_SPEC-175 - HttpSession.lastAccessTime
> 
> Some tasks:
> - HttpSession.lastAccessTime should be updated constantly with websocket use
> - If HttpSession is expired / cleaned up, then the websocket connection itself should also be terminated with close code 1008
> 
> Related: 
> - If the (user) principal is logged out, then the websocket connection itself should also be terminated with close code 1008

**Comment by joakime** [comment]
This is probably more suitable for documentation, as there is nothing for us to do here.

**Comment by joakime** [comment]
@WalkerWatch i'll work with you over the next few weeks to get this documentation into place.

**Comment by joakime** [comment]
Current spec locations for this issue is at ...

* eclipse-ee4j/websocket-api#175
* eclipse-ee4j/websocket-api#5

Going to close this, as keeping it open isn't helping.
Once the websocket-api is updated to mandate these behaviors a new issue will be created to track that effort.
