### ISSUE TITLE
Can't connect to server if multiple ServerConnector are created for same ip but different port

### ISSUE THREAD

**Issue by pagrigaliunas** [eclipse/jetty.project#1360]
Hello,

We use embedded Jetty server (9.4.2.v20170220). 
If we create single ServerConnector per IP, all works fine. But if we create multiple ServerConnector per IP but different port, our client can not connect to server.
We have no such problems with 9.3.16.v20170120.

Connectors are created like this:

        Collection<ConnectionFactory> factoryCollection = new ArrayList<>();
        HttpConfiguration httpConfig = (HttpConfiguration)serverConfiguration.getIdMap().get("httpConfig");
        httpConfig.setSecurePort(sslPort);
        factoryCollection.add(new HttpConnectionFactory(httpConfig));

        for (String ip : bindIps)
        {
            for (int port : ports)
            {
                ServerConnector connector = new ServerConnector(httpServer);
                connector.setHost(ip);
                connector.setPort(port);
                connector.setConnectionFactories(factoryCollection);
                connector.start();
                httpServer.addConnector(connector);
            }
        }

HttpConfiguration object is declared in jetty.xml file and taken from  XmlConfiguration object. 
[jetty_xml.zip](https://github.com/eclipse/jetty.project/files/806281/jetty_xml.zip)

Client code looks like this:

        client = new WebSocketClient();
        client.getPolicy().setMaxBinaryMessageSize(RpcParty.RPC_MESSAGE_MAX_SIZE);
        netStream = new RpcSocket();
        client.start();
        ClientUpgradeRequest upgradeRequest = new ClientUpgradeRequest();
        Future<Session> connect = client.connect(netStream, new URI(getWebSocketURI(host, port)), upgradeRequest);
        connect.get();

**Comment by joakime** [comment]
Do not call `connector.start()` manually like that.

Let the `httpServer.start()` lifecycle manage the connector startup.

**Comment by pagrigaliunas** [comment]
It works now. 
But the problem is (if I understand correctly) you have to restart http server every time you want to add/remove connector. This would cause any client, connected using different ip, to disconnect from server. It seems not optimal to me.

**Comment by joakime** [comment]
Just use `.addConnector()` and `.removeConnector()` with an already started `Server` then.

Let the existing LifeCycle handle the start/stop of the connector, along with the appropriate add/remove lifecycle beans.
