### ISSUE TITLE
Get Request Body results in -1/EoF

### ISSUE THREAD

**Issue by Kurimatzu** [eclipse/jetty.project#1362]
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.eclipse.jetty.proxy.ConnectHandler;
import org.eclipse.jetty.server.Request;



public class ProxyServer extends ConnectHandler
{
	@Override
	public void handle( String target,
			Request baseRequest,
			HttpServletRequest request,
			HttpServletResponse response ) throws IOException, ServletException	{
		
		super.handle(target, baseRequest ,  request , response ) ;

		String host = baseRequest.getServerName();

		System.out.println(host);

		BufferedReader br = null;
		
		System.out.println(baseRequest.getInputStream());

		try {

			br = new BufferedReader(new InputStreamReader(baseRequest.getInputStream()));

			String line;

			StringBuilder sb = new StringBuilder();

			while ((line = br.readLine()) != null) {

				sb.append(line);
				sb.append(System.lineSeparator());
			}

			System.out.println(sb);
		} finally {

			if (br != null) {
				br.close();
			}
		}
	}
}

```

Returns nothing, it is a problem of baseRequest.getInputStream ()?

System.out.println(baseRequest.getInputStream()); == HttpInputOverHTTP@3ff0e181[c=0,q=0,[0]=null,s=STREAM]

**Comment by joakime** [comment]
Use the `HttpServletRequest.getInputStream()` instead.

Also ...
 * Does the incoming request have a body content? (it will be empty if there's no body content)
 * Did something before your handler read the body content? (it will also be empty as the content has already been read)

**Comment by joakime** [comment]
Also, don't wrap the `HttpServletRequest.getInputStream()` with a `InputStreamReader`.

Use the `HttpServletRequest.getReader()`, as that will provide a `Reader` that is properly initialized from the HTTP Request headers (regarding issues such as charset).

**Comment by Kurimatzu** [comment]
```
	BufferedReader br = null;
		

		try {

			br = request.getReader();

			String line;

			StringBuilder sb = new StringBuilder();

			while ((line = br.readLine()) != null) {

				sb.append(line);
				sb.append(System.lineSeparator());
			}

			System.out.println(sb);
		} finally {

			if (br != null) {
				br.close();
			}
		}
```

The answer is empty.

Is there another way?

**Comment by joakime** [comment]
A read() of == -1 means you have hit the end of the request body.
You either received no request body (the likely scenario), or something else read it before you.

What doe your request look like (from your browser)?
Use the browser debug tools to look at the request uri + headers.
Report back here what the request looks like.

**Comment by gregw** [comment]
Depends on what the super class is?

**Comment by joakime** [comment]
This isn't correct.

You have overridden `ConnectHandler.handle()` 
then used `super.handle(target, baseRequest ,  request , response ) ;`

The `ConnectHandler` has processed the input stream already, there's nothing left for you to read.
