### ISSUE TITLE
HttpInput.read deadlock (async mode)

### ISSUE THREAD

**Issue by cy6erGn0m** [eclipse/jetty.project#1363]
Jetty 9.4.2 (currently latest)

qtp thread is here stalled on the monitor (`_inputQ`'s)

```
at org.eclipse.jetty.server.HttpInput.isAsyncEOF(HttpInput.java:716)
      at org.eclipse.jetty.server.HttpChannelState.unhandle(HttpChannelState.java:433)
      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
      at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:267)
```

my app's thread just checked servletInputStream.isReady, got true and called servletInputStream.read(buffer)
```
at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
      at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
      at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
      at org.eclipse.jetty.util.thread.Locker.lock(Locker.java:48)
      at org.eclipse.jetty.server.HttpChannelState.onReadEof(HttpChannelState.java:1216)
      at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:311)
```

so it is a deadlock: mixed locks order: Locker vs inputQ monitor, see outlines below

HttpChannelState.unhandle outline:
```
try (locker.lock) {
    switch (...) {
        ....
    }

    switch(...) {
        case STARTED:
            input.isAsyncEOF:
                synchronized(inputQ) { ... }
    }
}
```

HttpInput.read outline
```
synchronized(inputQ) {
    ...
    while (true) {
        if (...) _channelState.onReadEof():
            try (locker.lock) { ... }
    }
}
```

**Comment by joakime** [comment]
Show us your usage of ServletInputStream.
It is a very particular API and must be used properly.

See:

* https://www.slideshare.net/SimoneBordet/servlet-31-async-io
* https://www.youtube.com/watch?v=j1VjAHTxCBo

**Comment by cy6erGn0m** [comment]
https://github.com/Kotlin/ktor/blob/8ecb3aca90c35638152e2761b753633a05915052/ktor-hosts/ktor-servlet/src/org/jetbrains/ktor/servlet/ServletReadChannel.kt

Usage is not so simple in fact but generally when I do like this in my application thread 

```
if (servletInputStream.isReady)
    return servletInputStream.read(dst)
```
it could get stuck because of some kind background processing in the container

**Comment by cy6erGn0m** [comment]
Also, I believe that so typical deadlock need to be eliminated anyway, even if I use API wrong

**Comment by joakime** [comment]
It is actually prohibited to use the API from a thread that isn't the Servlet dispatch thread.

**Comment by cy6erGn0m** [comment]
@joakime neither the specification nor javadoc specify it clearly

also then it's not clear how do I use async at all: what if the application can't consume all the input at once? consider scenario

1. setReadListener, then suspend
2. got callback onDataAvailable, let's assume we have 1000 bytes available but the application can only process 500, so we read 500 and have 500 bytes remaining, then go suspend
3. later in the app thread we discover that we can process more bytes, how do I read them? according to your logic there is no way to consume remaining 500 bytes as I can't touch the API and no way to trigger onDataAvailable again

**Comment by cy6erGn0m** [comment]
The only API that provides way to run on dispatcher thread is `AsyncContext.start` but it doesn't work: fails with NPE

**Comment by gregw** [comment]
We definitely should support async API calls from any arbitrary thread.  It does make the API stupidly hard to implement but it is required.

I also agree that even if there is an API usage issue, a deadlock should not result.

**Comment by gregw** [comment]
@joakime calling the servlet async IO API from arbitrary threads is not something that is explicitly discussed in the spec, but it is definitely something that is needed to be supported for general async applications where more than one async concerns are mixed.

@cy6erGn0m thanks for the detailed report of the deadlock.  It is very clear what we have done wrong.  It is a problem we just introduced with our fix for #1317.      I'm just about to hop onto a long international flight.... I'm hoping I'll have an alternate fix by the end of it.... standby...

**Comment by cy6erGn0m** [comment]
@gregw do you think I can downgrade to 9.4.1 for now or it is better to use 9.3.x?

**Comment by jmcc0nn3ll** [comment]
9.4.1 and we'll likely have a 9.4.3 out later next week sometime.

**Comment by gregw** [comment]
first attempted fix was a disaster... never code on a plane.
As @jmcc0nn3ll said, 9.4.1 does not have this problem, but does have a race so that onAllDataRead is sometimes not called, but if you are reading until -1 then you may not be affected.

Working on an alternate strategy now....

**Comment by cy6erGn0m** [comment]
Yeah, I use both onAllDataRead and -1 as EOF so it seems to be working well for me

**Comment by gregw** [comment]
@sbordet I think we need to get our heads together on this one.  I can see how to avoid the deadlock by simply pushing the state from HttpInput into HttpChannelState, but the whole HttpInput class is just a bit too complex for my liking, specially with regards to how onAllDataRead is called.   So a bit of a review will be needed I think.  Let's chat first thing next week.

**Comment by defnull** [comment]
Thanks a lot @gregw. I triggered this bug today. Looking forward to the 9.4.3 release.

**Comment by joakime** [comment]
@defnull if you would like to test the staged (potential) release 9.4.3, see the jetty-dev announcement email ...

http://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02911.html

**Comment by joakime** [comment]
@gregw could this issue have an effect on the similar ones #1074 and #997 ?

**Comment by joakime** [comment]
Oh, and also #1047 ?

**Comment by gregw** [comment]
@joakime all those bugs are loosely related.   Essentially the async aspect of the container were initially developed for being called by container dispatched threads, which had the nice feature that there was only ever one of them.  Async IO extended the API to need to be async callable by any arbitrary thread and these issues have all been about corner cases where races exist.   So  taken together these fixes should now make it safe to call the async IO API from any thread... at least that is what I believe the current state is - hence all issues are closed.    If there are further async problems, then it will be hard to say which of these is responsible, so best carried on in a new issue describing any new symptoms etc.

**Comment by defnull** [comment]
@joakime I switched to 9.4.3-SNAPSHOT when I wrote that comment and hadn't had any issue since then. No deadlocks or incorrect behavior, even under (simulated) high load.
