### ISSUE TITLE
Need to support KeyStore/TrustStore with null passwords

### ISSUE THREAD

**Issue by garypgithub** [eclipse/jetty.project#1368]
I am working with a specialized KeyStore and TrustStore (z/OS SAF) and I need to be able to load from the these stores with a null password.  Currently, there is no provision for this.  I'm requesting a new property for SslContextFactory that would allow for a null password in the setKeyStorePassword and setTrustStorePassword methods.  So, for example, the setKeyStorePassword method might look something like this:

```java
    public void setKeyStorePassword(String password)
    {
        if (password == null)
        {
            if (System.getProperty("jetty.sslContext.allowNullKeyStorePassword").equalsIgnoreCase("true")
                _keyStorePassword = null;
            else if (_keyStoreResource != null)
                _keyStorePassword = getPassword(PASSWORD_PROPERTY);
            else
                _keyStorePassword = null;
        }
        else
        {
            _keyStorePassword = newPassword(password);
        }
    }
```

I'm currently accomplishing this through convoluted means but it would be nice to have something more straightforward.

Thanks

**Comment by joakime** [comment]
Just don't set a keystore password, no code changes needed.

**Comment by garypgithub** [comment]
If you don't specify a password, the default in jetty-ssl-context.xml is supplied.  If you specify your own DI .xml file and blank the password out altogether, you are prompted for a password in SslContextFactory.setKeyStorePassword if you also specified (or defaulted to) a KeyStorePath.

**Comment by joakime** [comment]
That's default behavior for the most common jetty-distribution behavior, yes.

Do this ..

 * copy `${jetty.home}/etc/jetty-ssl-context.xml` to your `${jetty.base}/etc/jetty-ssl-context.xml`
 * remove the entire `<Set name="KeyStorePassword" ...>` element (and associated `TrustStorePassword` element)

start your `${jetty.base}` instance.

at this point you have no declared `KeyStorePassword` or `TrustStorePassword`

**Comment by garypgithub** [comment]
Thanks Joakim.  Thank you very much for this.  I'd prefer not having to replicate jetty-ssl-context.xml and then modifying it.  The reason is that I'd need to check each new release to see if it changed and then do the same thing every time.  Please consider this as an enhancement request if it comes up again.  In the meantime, I do have something work.

**Comment by jmcc0nn3ll** [comment]
FWIW the point of using the {jetty.base} is so that you can freely move between jetty versions within the same minor release without having to go back and make the same change to {jetty.home} each and every time.  But I think your point is that you feel the need to go check that jetty-ssl-context.xml file each time to see if it changed and that is valid I suppose.

**Comment by joakime** [comment]
@gregw what do you think about making `"OBF:" == <null>` as a possible solution instead?

I really don't want to see optional XML properties that have different meanings of `""` (empty string) vs `null` (null value).  

That being said ... what I don't understand about this issue is ... If you setup a JKS keystore using the JVM keytool and don't define a keystore password in the tool. then both `""` and `null` apply in SslContextFactory (both work btw)

**Comment by garypgithub** [comment]
Joakim, as I mentioned above, this is a non-JKS keystore.  The resource requires relies on a URL protocol handler that does not permit the specification of a password in the URL so a null password is used.  The password used in KeyStore.load has to match the password used in creating the input stream (which is null) so the password supplied to KeyStore.load has to be null.  A zero length string is treated differently from null for this particular non-JKS keystore.  I hope this clarifies things.

**Comment by joakime** [comment]
bump @gregw see my comment above

**Comment by joakime** [comment]
This seems similar to issue #901

**Comment by gregw** [comment]
I'm inclined to think that almost nobody would be using the prompt for password approach, so it would be good to make null mean null.

Maybe we only do the prompt for password if the setter has not been called?

let me have a play....

**Comment by gregw** [comment]
I'm not so keen on `OBF:` being null, but we could probably add support for `NULL:` being null pretty easily.

**Comment by gregw** [comment]
On balance, I'd prefer to have setter(null) mean set null, so I'd like to deprecate/remove the prompting.  I can definitely do this in 10.0.0, but not in 9.4.x. @garypgithub are you OK with your work around until next major release?

Note also that an easier work around might be to override SslContextFactory and replace the newPassword(String) method with return null

**Comment by joakime** [comment]
@gregw others that have tried extending SslContextFactory for this same behavior (null) have hit other issues with the TrustStore part of the equation. See #901 and https://bugs.eclipse.org/473321

**Comment by garypgithub** [comment]
Sorry for the late reply.  I've been unavailable.  I'm fine with my workaround.  I just created my own file in my jetty.base and have a Configure element for org.eclipse.jetty.util.ssl.SslContextFactory with just the children that I need (omitting the Password elements) and then I specified that file in my start.ini.  Works fine for what I need.

**Comment by gregw** [comment]
null now means null in 10.0
