### ISSUE TITLE
Support OAuth

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#137]
migrated from Bugzilla [#427619](https://bugs.eclipse.org/bugs/show_bug.cgi?id=427619)
status ASSIGNED severity _enhancement_ in component _client_ for _9.1.x_
Reported in version _unspecified_ on platform _All_
Assigned to: Simone Bordet

On 2014-02-07 01:11:05 -0500, Mikhail Mazursky wrote:

> Please add support for OAuth authentication to Jetty Client.

**Comment by gregw** [comment]
This will be addressed by #4038
