### ISSUE TITLE
When `Server.start` fails, beans ought to be stopped

### ISSUE THREAD

**Issue by jhannes** [eclipse/jetty.project#1374]
If `org.eclipse.jetty.server.Server` fails to start correctly, by default the `QueuedThreadPool` and any other threads potentially started by the server (such as session cleanup schedulers) are left running, which leaves the JVM running (unless the thread pool is replaced by a daemon thread pool). This is probably not desired default behavior.

This will happen for example, if the server is started on a port that was already in use.

By adding `stop()` to `AbstractLifeCycle.setFailed` (or the catch block in `AbstractLifeCycle.start`) "dead" resources will be cleaned up.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java#L73

**Comment by gregw** [comment]
@jhannes How are you starting your server?   I'm not seeing this with a simple test of running two instances of `java -jar start.jar` in the jetty distribution.  The second instance exits cleanly with the appropriate errors.

**Comment by jhannes** [comment]
I run jetty embedded in my own process. I don't like app servers, so `start.jar` is not for me. :-)

```java
public class DemoServer {

    public static void main(String[] args) throws Exception {
        Server server = new Server(10080);
        server.start();
    }
}
```

If I start this twice, the second server gets `Exception in thread "main" java.net.BindException: Address already in use: bind` (as expected), but the second server remains running because of non-daemon threads. (In this case, just qtp-threads, but if I also add a WebAppContext, the session cleanup thread will also keep the process alive).

**Comment by gregw** [comment]
Ah you are right.... but I'm too cautious to change this core behaviour of our fundamental object.
However, I have added a utility listener that will do the job, you just have to modify your code to:
```java
public class DemoServer {
    public static void main(String[] args) throws Exception {
        Server server = new Server(10080);
        server.addLifeCycleListener(Server.STOP_ON_FAILURE);
        server.start();
    }
}
```

**Comment by jhannes** [comment]
Brilliant - thank you.
