### ISSUE TITLE
Misleading javadoc for initialization of SessionIdPathParameterName

### ISSUE THREAD

**Issue by nlwillia** [eclipse/jetty.project#1379]
In [SessionHandler.java](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java)

````
...
    /**
     * Session id path parameter name.
     * Defaults to <code>jsessionid</code>, but can be set with the
     * <code>org.eclipse.jetty.servlet.SessionIdPathParameterName</code> context init parameter.
     * If set to null or "none" no URL rewriting will be done.
     */
    public final static String __SessionIdPathParameterNameProperty = "org.eclipse.jetty.servlet.SessionIdPathParameterName";
...
    protected String _sessionIdPathParameterName = __DefaultSessionIdPathParameterName;
    protected String _sessionIdPathParameterNamePrefix =";"+ _sessionIdPathParameterName +"=";
...
    protected void doStart() throws Exception
    {
...
            tmp=_context.getInitParameter(__SessionIdPathParameterNameProperty);
            if (tmp!=null)
                setSessionIdPathParameterName(tmp);
...
    }
...
    /**
     * Sets the session id URL path parameter name.
     *
     * @param param the URL path parameter name for session id URL rewriting (null or "none" for no rewriting).
     * @see #getSessionIdPathParameterName()
     * @see #getSessionIdPathParameterNamePrefix()
     */
    public void setSessionIdPathParameterName(String param)
    {
        _sessionIdPathParameterName =(param==null||"none".equals(param))?null:param;
        _sessionIdPathParameterNamePrefix =(param==null||"none".equals(param))?null:(";"+ _sessionIdPathParameterName +"=");
    }
...
````
The javadoc for `__SessionIdPathParameterNameProperty` indicates that if the session id path parameter name is set to null or "none", then no URL rewriting will be done; however, if the value is set via a context parameter, then the only value with this effect is "none".  In the snippet, note where the call to `setSessionIdPathParameterName` is checked by `tmp!=null`.  That prevents a context parameter value of a literal null from overriding the default, and URL rewriting still occurs.  "none" still works as an override value.  This mainly affects an embedded scenario where it's possible to pass null as an init parameter value.

The javadoc should be updated to remove null as an option for the init parameter value.

**Comment by janbartel** [comment]
Updated javadoc in jetty-9.4 branch.
