### ISSUE TITLE
Support optional packages for alpn boot

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1381]
The code in [NegotiatingServerConnectionFactory](https://github.com/eclipse/jetty.project/blob/0c8273f2ca1f9bf2064cd9c4c939d2546443f759/jetty-server/src/main/java/org/eclipse/jetty/server/NegotiatingServerConnectionFactory.java#L44) prevents the ALPN implementation from being loaded as an optional package as such packages have non null classloaders.

We should either be able to explicitly support optional packages (if there is a reliable way to detect them) or at least allow this check to be optionally disabled.

**Comment by sbordet** [comment]
@gregw considering that the optional (I think you mean "endorsed" here) mechanism has been removed from JDK 9, this is not going to be implemented. JDK 8 users will continue to have `alpn-boot` on the boot classpath, and JDK 9 users will have ALPN from the JDK.
