### ISSUE TITLE
Expose StatisticsServlet to webapp

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1384]
Expose the Stats servlet to a webapp... or move it to `org.eclipse.jetty.servlets.` package which is already exposed.

**Comment by gregw** [comment]
I've added the servlet to the classpath patterns for now, but moving may be a better option.  The servlet also needs updating for it's listeners are deprecated.

**Comment by gregw** [comment]
Actually, I'm just going to close for now.   Moving the servlet can be another issue.

**Comment by janbartel** [comment]
See #1128

**Comment by gregw** [comment]
Sorry all, I confused this one somewhat.

The situation is that in 9.4.x, we have a new mechanism that allows modules to modify the classpath exposed to the webapps.  The `stats.mod` file includes:
```
jetty.webapp.addServerClasses+=,-org.eclipse.jetty.servlet.StatisticsServlet
```
So I have reverted the change in 9.4 that adds the servlet by default.

I expect the problem for users of 9.4 is that they are not using the module fully, so they have not modified the classpath.   If they are running embedded, they will need to modify the server/system classes directly.  Otherwise they should use the module ini file (or manually add the line about to their start.ini) to ensure the classpath is exposed.

For 9.3.x, I have left the change to the default in, as it does not have this module mechanism.

**Comment by joakime** [comment]
The `jetty.webapp.addServerClasses+=,-org.eclipse.jetty.servlet.StatisticsServlet` should probably be moved from the `[ini-template]` section to a `[ini]` section so that its always applied, regardless if the user does `--add-to-start` or not.

If they choose to override it, it will take the overridden choice.

**Comment by gregw** [comment]
@joakime I opened #1407 to consider using `[ini]` more.
