### ISSUE TITLE
Setting the TOS/DS field for websocket traffic

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#139]
migrated from Bugzilla [#427880](https://bugs.eclipse.org/bugs/show_bug.cgi?id=427880)
status REOPENED severity _normal_ in component _websocket_ for _9.3.0_
Reported in version _9.1.1_ on platform _PC_
Assigned to: Joakim Erdfelt

On 2014-02-11 05:45:26 -0500, Xavier BRUGGHEMAN wrote:

> I'm using Jetty 9.1.1 as websocket client & server over SSL, and need to set the Type Of Service / Differentiated Services fields (RFC 1349 / RFC 2474) on the generated TCP traffic in order for it to be routed with the same level of priority as the associated non-websocket traffic it controls (currently Express Forwarding, but others might be used depending on the environment).
> 
> I've had a look around, but couldn't find an easy way to configure it for the socket/channels created by either the Server or the WebSocketClient. The nearest thing I've found is the configuration of another socket options (lingerTime) for server sockets, but not much of the WebSocketPolicy applies to the creation of client sockets.
> 
> The only way I currently managed to do that is through rather ugly
> hacks:
> - On the server side, subclass oejs.ServerConnector and override protected void configure(Socket) in order to call socket.setTrafficClass(tos).
> - On the client side, subclass oejwci.ConnectionManager, override public ConnectPromise connect(WebSocketClient, EventDriver, ClientUpgradeRequest), and return a class similar to PhysicalConnect which would either call channel.socket().setTrafficClass(tos) or channel.setOption(StandardSocketOptions.IP_TOS, tos) before connecting.
>   This is much uglier due to the private PhysicalConnect inner class and its lack of socket configuration hooks.
> 
> I'm filing this issue as suggested by the jetty-dev mailing list to request a configuration option for this on the ServerConnector and on the WebSocketClient.

On 2014-02-11 05:58:48 -0500, Xavier BRUGGHEMAN wrote:

> Also, i'm not sure which component to file this under as it affects the sockets created by both the Server and the WebSocket client.

On 2014-02-11 09:22:04 -0500, Joakim Erdfelt wrote:

> websocket is the right component :)

On 2015-04-29 18:26:52 -0400, Simone Bordet wrote:

> Assigned to Greg for review.

On 2015-04-29 21:51:52 -0400, Greg Wilkins wrote:

> I have added the socket customization listener in response to 464629
> 
> Can you verify  if that is sufficient for per protocol socket customization?

On 2016-01-08 13:40:11 -0500, Joakim Erdfelt wrote:

> Assuming this is fixed based on solution in bug # 464629

On 2016-01-12 05:26:05 -0500, Xavier BRUGGHEMAN wrote:

> Sorry for the lack of feedback, after a year the issue fell off my radar.
> 
> I'm reopening it now because the proposed fix in # 464629 only allows the server side of the websocket to be customized, but not the client side which still uses the private ConnectionManager$PhysicalConnect#run() method to create the client socket. 
> 
> As far as I understand the RFCs, for DSCP and especially ECN to work, both sides need to be customized otherwise some equipments along the way may decide the configuration is invalid and ignore the field entirely, falling back to default traffic prioritisation / congestion handling.
> 
> Could you add support for a SocketCustomizationListener in either the WebSocketClient or its ConnectionManager to allow websocket client socket to be customized as well ?

**Comment by joakime** [comment]
This is now possible in Jetty 9.4.0+

You'll need a customized `HttpClient` implementation to pass to the `new WebSocketClient(HttpClient)` constructor.

This customized `HttpClient` will have customized version of the 
`protected void configure(HttpClient client, SocketChannel channel) throws IOException`
method found in implementations of `org.eclipse.jetty.client.AbstractHttpClientTransport`.

Such as extending from `org.eclipse.jetty.client.http.HttpClientTransportOverHTTP`
This is where you can manipulate the `SocketChannel` settings to suit your needs.
