### ISSUE TITLE
Unable to add `ServletContextListener` to servlet context during `lifeCycleStarting()` phase.

### ISSUE THREAD

**Issue by defnull** [eclipse/jetty.project#1395]
Hi everyone,

for e2e tests I'd like to re-use an existing `ServletContainerInitializer` to set-up my application, so I call `ServletContainerInitializer.onStartup()` from a `LifeCycle.Listener.lifeCycleStarting()` callback. The listener is registered to a `ServletContextHandler`.

This works fine, expect that `ServletContextHandler.getServletContext().addListener()` fails for instances of `ServletContextListener`. According to the Servlet spec, `ServletContextListener` is allowed during `ServletContainerInitializer.onStartup()`, and I thought `lifeCycleStarting` was a suitable live-cycle phase to call `onStartup()`.

The problem is that `org.eclipse.jetty.server.handler.ContextHandler.Context.setExtendedListenerTypes(true)` is never called as far as I can tell and `checkListener()` (same class) will always fail for `ServletContextListener` instances regardless of the life-cycle phase. This might be a bug, or I am doing something wrong.

I am using jetty 9.4.3-SNAPSHOT (downloaded today).

**Comment by defnull** [comment]
Minimal example:

```java
public class JettyServletInitializerTest {
	public static void main(String[] args) throws Exception {
		final Server server = new Server(0);

		final ServletContextHandler context = new ServletContextHandler();
		context.setContextPath("/");
		server.setHandler(context);

		context.addLifeCycleListener(new AbstractLifeCycle.AbstractLifeCycleListener() {
			@Override
			public void lifeCycleStarting(LifeCycle event) {
				try {
					new ServletContainerInitializer() {
						@Override
						public void onStartup(Set<Class<?>> c, ServletContext ctx) throws ServletException {
							ctx.addListener(new ServletContextListener() {
							});
						}
					}.onStartup(Collections.emptySet(), context.getServletContext());
				} catch (final ServletException e) {
					e.printStackTrace();
				}
			}
		});
		server.start();
	}
}
```

This will throw:

    java.lang.IllegalArgumentException: Inappropriate listener class JettyServletInitializerTest$1$1$1
	at org.eclipse.jetty.server.handler.ContextHandler$Context.checkListener(ContextHandler.java:2433)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.addListener(ContextHandler.java:2383)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.addListener(ServletContextHandler.java:1448)
	at JettyServletInitializerTest$1$1.onStartup(JettxBug.java:31)
	at JettyServletInitializerTest$1.lifeCycleStarting(JettxBug.java:34)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

**Comment by janbartel** [comment]
@defnull the ServetContainerInitializer is a moving part in the strangely complex machine that is the servlet specification :) As such, it is difficult to re-use it outside of that. It needs the services of annotations, which you're not using, and also of WebAppContext, which you're not using either. So you're going to have to make the calls that these would normally make, ie you'll need to call context.getServletContext().setExtendedListenerTypes(true) in your code.

I actually think mostly you would have been fine with using your existing ServletContainerInitializer if it didn't need to do stuff with listeners - the spec is extremely specific about when and how listeners can be programmatically added. Not sure if there is a way I could easily modify jetty to do the same checks but without needing the support of the other classes (annotations, webapps etc). I'll have a look.

But, in the meanwhile, if I were you, I'd probably refactor (if possible) your ServletContainerInitializer to extract the setup it does into another class , so ServletContainerInitializer.onStartup() just calls the new class, and  your LifeCycleListener can do the same.

**Comment by defnull** [comment]
Thinking about this again: Adding `ServletContextListener` to a servlet context is allowed _only_ during `ServletContainerInitializer.onStartup()` and since I am the one calling `onStartup()` and bypassing the `WebAppContext` logic, I should also be responsible for unlocking the context via `ContextHandler.Context.setExtendedListenerTypes(true)` and locking it again afterwards. It's a public interface after all, and during server startup I _know_ I'm using jetty and can use jetty-specific APIs.

So, this is not a bug, not even unexpected behavior. I'm closing this issue. Thanks for the insight :)

Working example:

```java
public class JettyServletInitializerTest {
	public static void main(String[] args) throws Exception {
		final Server server = new Server(0);

		final ServletContextHandler context = new ServletContextHandler();
		context.setContextPath("/");
		server.setHandler(context);

		context.addLifeCycleListener(new AbstractLifeCycle.AbstractLifeCycleListener() {
			@Override
			public void lifeCycleStarting(LifeCycle event) {
				try {

                    ContextHandler.Context ctx = context.getServletContext();
                    ctx.setExtendedListenerTypes(true);

					new ServletContainerInitializer() {
						@Override
						public void onStartup(Set<Class<?>> c, ServletContext ctx) throws ServletException {
							ctx.addListener(new ServletContextListener() {
							});
						}
					}.onStartup(Collections.emptySet(), context.getServletContext());

                    ctx.setExtendedListenerTypes(false);

				} catch (final ServletException e) {
					e.printStackTrace();
				}
			}
		});
		server.start();
	}
}
```

**Comment by vorburger** [comment]
@defnull @janbartel thanks for providing this info here; I've used in a [JettyLauncher](https://github.com/vorburger/opendaylight-simple/blob/25c2fb64b5896c96615fd38cc2ee62599fcd2d43/src/main/java/org/opendaylight/infrautils/simple/web/impl/JettyLauncher.java#L180), but was wondering if it was possible to dynamically create new ServletContexts register additional new Servlets/ Filters/ Listeners on it - AFTER `server.start()` .. possibly feasible, or no go? Basically I wanted [this test](https://github.com/vorburger/opendaylight-simple/blob/d34b3e64b5df2c1e9f99ba08e30907865aa45be4/src/test/java/org/opendaylight/infrautils/simple/jetty/test/JettyLauncherTest.java#L86) to pass... but couldn't figure out how. (The `system.ready();` in that test does the `server.start();`, _before_ that `newServletContext` & `addServlet` there.)

I **CAN** do it dynamically using my own thin [WebContext API](https://github.com/vorburger/opendaylight-simple/blob/25c2fb64b5896c96615fd38cc2ee62599fcd2d43/src/main/java/org/opendaylight/infrautils/web/WebContext.java#L39), which uses the Jetty API directly, without `ServletContainerInitializer` / `ServletContextListener` ... which is fine too - just wondered if there was a way.

**Comment by janbartel** [comment]
@vorburger  the jetty deployment manager does hot deploys of newly discovered webapps after startup, therefore  I don't see why you should have a problem. You don't say how your test fails?

**Comment by vorburger** [comment]
@janbartel thanks for reply! The failure was an `IllegalStateException`  - it somehow thought I was doing it too late, and didn't like it after `server.start()` anymore? But never mind, I've meanwhile concluded that a (Jetty independant) simple custom API to dynamically register Servlets & Filters, instead of relying on ServletContainerInitializer / ServletContextListener, is what we really need in the context where this came up - so I don't want to take any of your time to help figure this out more; just FYI https://git.opendaylight.org/gerrit/#/c/68415/, if interested.
