### ISSUE TITLE
Set-Cookie produced by Jetty is invalid for RFC6265 and Chrome

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1396]
Seen at Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=700618

Currently, when Jetty produces a `Set-Cookie` line, it follows the java.net.HttpCookie and javax.servlet.http.Cookie behavior for values with forbidden (to the cookie spec) characters.

Eg:

    Set-Cookie: foo="bar;baz";Version=1;Path="/secur"

The existence of the unencoded `;` character in the value for `foo` is in violation of the updated RFC6265 spec.

**Comment by joakime** [comment]
The use of java.net.HttpCookie and javax.servlet.http.Cookie means we are stuck on RFC2965 support level, which allowed for this behavior.

Encoding the values of the `HttpServletResponse.addCookie()` calls would need to be done to comply with the RFC6265 spec.   However, care will be needed to ensure we don't double-encode the certain characters (like `%` which is allowed in the Cookie spec)

**Comment by joakime** [comment]
@gregw any thoughts on how we want to tackle this?

One thought would be to just trigger an `IllegalArgumentException` (with a message "illegal characters per RFC6265 spec, did you forget to encode the value?") on `HttpServletRequest.addCookie()` if a name or value with illegal characters is encountered. (such as ` `(space) and `;` (semi-colon) and any control character).

**Comment by gregw** [comment]
We need to change to ensure that we never generate a set cookie that is in violation to RFC6265, but I think we can still be accepting of cookies that do have quoted semicolons in their values.

ie be strict in what we generate but forgiving in what we parse.

**Comment by joakime** [comment]
@gregw I went ahead and added a more complete testcase, along with updating the behavior to follow the RFC6265 spec more.   The RFC6265 spec points out that for Cookie.name is based on RFC2616 logic, while for Cookie.value its based on the more strict syntax in RFC6265.

**Comment by joakime** [comment]
Added a bunch of valid RFC6265 Cookie name tests and realized that the Cookie name verification wasn't correct either.  The recent commit ff3db36 corrects that.

**Comment by joakime** [comment]
Considering this complete in jetty-9.4.x branch

**Comment by joakime** [comment]
@WalkerWatch we need to highlight this in the next release of jetty 9.4.x, as this change can trigger issues with existing web applications that are not URLEncoding their Cookie values.

Should probably point out bad behavior, the URLEncoding proper behavior, and as a last resort, how to declare the RFC2965 compliance mode.
