### ISSUE TITLE
jetty.state file permissions with setuid enabled

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#140]
migrated from Bugzilla [#428114](https://bugs.eclipse.org/bugs/show_bug.cgi?id=428114)
status ASSIGNED severity _normal_ in component _server_ for _9.1.x_
Reported in version _9.1.1_ on platform _PC_
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[FileNoticeLifeCycleListener.java](https://bugs.eclipse.org/bugs//attachment.cgi?id=241081)_ (ID 241081)

On 2014-02-13 10:53:31 -0500, Brian Crockett wrote:

> I am attempting to monitor the jetty.state file for the status of my webapps. It appears that the file is created on the filesystem with permissions of the user that started jetty. I am using the setuid plugin to run jetty as 'nobody'. The file gets created, but then jetty complains in stderror.log file that jetty.state can't be written to. I suspect because it created the file before it dropped privileges.
> 
> drwxrwxr-x. 12 nobody nobody 4.0K Feb 13 15:22 .
> drwxrwxr-x.  7 nobody nobody 4.0K Jan 17 19:48 ..
> drwxrwxr-x.  3 nobody nobody 4.0K Jan 17 19:46 bin
> drwxrwxr-x.  8 nobody nobody 4.0K Jan 17 19:46 demo-base
> drwxrwxr-x.  3 nobody nobody 4.0K Feb 12 20:54 etc
> -rw-rw-r--.  1 bcrockett          bcrockett            99 Feb 13 15:22 jetty.state
> drwxrwxr-x. 13 nobody nobody 4.0K Jan 17 19:46 lib
> -rw-rw-r--.  1 nobody nobody  30K Jan 17 19:46 license-eplv10-aslv20.html
> drwxrwxr-x.  3 nobody nobody 4.0K Feb 13 15:22 logs
> drwxrwxr-x.  4 nobody nobody 4.0K Jan 17 19:46 modules
> -rw-rw-r--.  1 nobody nobody 6.2K Jan 17 19:46 notice.html
> -rw-rw-r--.  1 nobody nobody 1.2K Jan 17 19:46 README.TXT
> drwxrwxr-x.  3 nobody nobody 4.0K Jan 17 19:46 resources
> drwxrwxr-x.  4 nobody nobody 4.0K Jan 17 19:46 start.d
> -rw-rw-r--.  1 nobody nobody 2.1K Jan 17 19:46 start.ini
> -rw-rw-r--.  1 nobody nobody  81K Jan 17 19:46 start.jar
> drwxrwxr-x.  6 nobody nobody 4.0K Jan 17 19:58 .svn
> -rw-rw-r--.  1 nobody nobody 344K Jan 17 19:46 VERSION.txt
> drwxrwxr-x.  3 nobody nobody 4.0K Jan 17 19:58 webapps
> 
> 2014-02-13 15:00:50.694:WARN:oejuc.FileNoticeLifeCycleListener:Thread-1:
> java.io.FileNotFoundException: /home/bcrockett/jetty-9.1.1/jetty.state (Permission denied)
>         at java.io.FileOutputStream.open(Native Method)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
>         at java.io.FileWriter.<init>(FileWriter.java:78)
>         at org.eclipse.jetty.util.component.FileNoticeLifeCycleListener.writeState(FileNoticeLifeCycleListener.java:45)
>         at org.eclipse.jetty.util.component.FileNoticeLifeCycleListener.lifeCycleStopping(FileNoticeLifeCycleListener.java:72)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.setStopping(AbstractLifeCycle.java:195)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
>         at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:132)

On 2014-03-20 23:28:05 -0400, Greg Wilkins wrote:

> **\* Bug 428900 has been marked as a duplicate of this bug. ***

On 2014-03-20 23:29:03 -0400, Greg Wilkins wrote:

> I've tried to reproduce, and while the state file is owned by root, I am not getting that exception?
> 
> can you do an ls -l of the jetty.state file?  perhaps it has to do with the umask?

On 2014-03-20 23:35:55 -0400, Greg Wilkins wrote:

> Created attachment 241081
> Alternate implementation
> 
> Perhaps try with this impl of the lifecyclelistener.
> 
> This opens the file when it is constructed and keeps it open, so it should survive through setuid.
> 
> Still a mystery why it works for me?   So would like to see your umasks and full ls -l of the file and directory as well.

On 2014-03-24 11:05:13 -0400, Brian Crockett wrote:

> (In reply to Greg Wilkins from comment # 3)
> 
> > Created attachment 241081 [details]
> > Alternate implementation
> > 
> > Perhaps try with this impl of the lifecyclelistener.
> > 
> > This opens the file when it is constructed and keeps it open, so it should
> > survive through setuid.
> > 
> > Still a mystery why it works for me?   So would like to see your umasks and
> > full ls -l of the file and directory as well.
> 
> umask for the directory is:
> 
> [bcrockett@config-1 jetty-latest]$ umask
> 0002
> 
> I've provided the full 'ls -l' when I opened the ticket - could you be more clear? I'm happy to provide it. 
> 
> I'm spinning up a node to see if I can test your lifecyclelistener, but admittedly I'm not a developer so we'll see how that goes.

On 2014-03-24 11:15:22 -0400, Brian Crockett wrote:

> I believe this is due to a previous assumption of my predecesor.
> 
> It seems that the environment variable had been set:
> 
> UMASK="002"
> 
> However, in the start.d directory there was a (commented) line for:
> jetty.umask=002
> 
> After uncommenting that line, my error seems to have been resolved. 
> 
> Side note - I don't know that it's appropriate for me to change the STATE on the ticket.

On 2014-03-24 11:41:43 -0400, Brian Crockett wrote:

> Something I hadn't noticed before (I was testing the before/after)
> 
> It it seems that the error reveals itself on jetty stop.
> 
> While I think my jetty setuid changes are more 'technically correct', they don't seem to be at the root of the issue.

On 2014-04-10 21:03:40 -0400, Greg Wilkins wrote:

> thanks for the update.  I'll keep this open and look at your alternate implementation in due course.

On 2014-12-16 16:43:45 -0500, Brian Crockett wrote:

> It tooks some doing, but I've recompiled jetty with your change. It seems that the jetty.state file is still owned by root. While the error in the logfile is now gone, I suspect the core issue (file creation before permissions drop) still exists. 
> 
> [bcrockett@tc-testjetty-1 webapps]$ ls -alh /var/ryl/runtime/j2ee/jetty-latest/logs/
> total 72K
> drwxr-xr-x.  3 nobody        nobody        4.0K Dec 16 21:38 .
> drwxr-xr-x. 11 bcrockett bcrockett 4.0K Dec 16 21:38 ..
> -rw-rw-r--.  1 root          root           17K Dec 16 21:39 2014_12_16.request.log
> -rw-r--r--.  1 root          root          2.5K Dec 16 21:39 2014_12_16.stderrout.log
> -rw-r--r--.  1 root          root          2.6K Dec 16 19:51 2014_12_16.stderrout.log.195202096
> -rw-r--r--.  1 root          root          5.1K Dec 16 21:26 2014_12_16.stderrout.log.212645886
> -rw-r--r--.  1 root          root           17K Dec 16 21:31 2014_12_16.stderrout.log.213202690
> -rw-r--r--.  1 root          root          3.0K Dec 16 21:37 2014_12_16.stderrout.log.213803083
> -rw-r--r--.  1 bcrockett bcrockett    0 Dec 16 19:49 .donotdelete
> drwxr-xr-x.  6 bcrockett bcrockett 4.0K Dec 16 19:50 .svn
> [bcrockett@tc-testjetty-1 webapps]$ ls -alh /var/ryl/runtime/j2ee/jetty-latest/logs/^C
> [bcrockett@tc-testjetty-1 webapps]$ ls -alh /var/ryl/runtime/j2ee/jetty-latest/jetty.state 
> -rw-r--r--. 1 root root 99 Dec 16 21:38 /var/ryl/runtime/j2ee/jetty-latest/jetty.state

On 2014-12-31 10:08:14 -0500, Greg Wilkins wrote:

> **\* Bug 453416 has been marked as a duplicate of this bug. ***

**Comment by joakime** [comment]
Reported as fixed.
