### ISSUE TITLE
Does increasing maxFormContentSize require increasing Xmx?

### ISSUE THREAD

**Issue by clintmilner** [eclipse/jetty.project#1400]
I don't know if this is the correct forum for this question, but I'm hoping you could provide a little advice for myself - the contact form on your website doesn't seem to work properly on HTTPS. I have a web app that can sometimes hit this 200000 limit for form submitting. I'd like to double this value in the JVM using:
-Dorg.eclipse.jetty.server.Request.maxFormContentSize=400000

 I've read your docs and understand why this is capped, but if we were to increase the limit for our web app, would you recommend increasing the Xmx value as well? How much extra resource would be required if this number was doubled? Many thanks, 

Clint M.

**Comment by sbordet** [comment]
@clintmilner you realize that we don't know what is your current max heap size, nor hardware, nor max number of concurrent requests, etc. etc. ?

We cannot really help you out without information.

**Comment by clintmilner** [comment]
Hi @sbordet 
Apologies for the missing information, I didn't know it was required to fully answer the question. 
Xmx is currenlty set at 2048M, we run on Linux / Centos 7 standard in-house (not cloud) appliance with 32GB + RAM for running other processes. We do have some flexibility in the Xmx setting. Concurrent requests is probably pretty low. The number of times the default limit of 200000 is surpased is also pretty low, but in certain instances, it can be breached.

I'm not really looking for an exact number, but more of a recommendation of whether we should allocate more memory or if the handler is okay as is.

Thanks for you time.

**Comment by sbordet** [comment]
So your worst case is that for the max number of concurrent requests all of them require a larger limit.

The form parameters are converted to Strings, and stored into a Map, which will probably require a bit of extra space. Now it's just matter of doing the math, yes ?

**Comment by clintmilner** [comment]
@sbordet that's great information. Leave the rest with me, I really appreciate it.


Cheers!
