### ISSUE TITLE
HttpOutput.recycle() does not clear the write listener

### ISSUE THREAD

**Issue by bjorncs** [eclipse/jetty.project#1401]
During an investigation of a heap dump we discovered that old instances of `WriteListener` was kept alive by recycled/reset `HttpOutput` instances. The `HttpOutput` instances had `_state == OutputState.OPEN`.

Observed in Jetty 9.4.2

**Comment by joakime** [comment]
@gregw seems like something we should look into before 9.4.3 release

**Comment by gregw** [comment]
Fixing in 9.3 and 9.4 ....
