### ISSUE TITLE
Server Mod should include Cookie Compliance

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1406]
The server.mod should include reference to CookieCompliance setting based on changes in #1396.

**Comment by WalkerWatch** [comment]
Was completed already in #1396 in 3b1d33e9447abab397d794d32400e989d54a299f

Whoops.

**Comment by gregw** [comment]
FYI that the CookieCompliance stuff is in server.mod/jetty.xml because it applies to all transports, whole the HttpCompliance stuff is just in http.mod/jetty-http.xml because it applies only to HTTP/1
