### ISSUE TITLE
Review [ini] vs [ini-template] usage

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1407]
The use of module `[ini]` vs `[init-template]` needs to be reviewed in most modules.
Configuration put in an `[ini]` will always apply no matter how the module is enabled.  Configuration in an '[ini-template]` only applies after the module is `--add-to-start`ed and may be modified by the user.

See #1384 for an example

**Comment by gregw** [comment]
@WalkerWatch perhaps this is something that you could review? Look for config in `[ini-template]` that would not be modified by a user and is essential for the module to run.

**Comment by WalkerWatch** [comment]
@gregw I only saw a few instances of this, both when using `addServerClasses`. I've corrected both instances to use `[ini]` rather than `[ini-template]` in  e091701.
