### ISSUE TITLE
Implement com.sun.net.httpserver.HttpsServer for jetty-http-spi

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1414]
Currently an attempt at creating an com.sun.net.httpserver.HttpsServer in jetty-http-spi returns an UnsupportedOperationException.

**Comment by joakime** [comment]
See http://stackoverflow.com/a/2323188/775715 for an example usage pattern for HttpsServer

**Comment by olamy** [comment]
@joakime not sure if we still want this?
