### ISSUE TITLE
Make jetty http/1.1 graceful shutdown more graceful

### ISSUE THREAD

**Issue by jsravn** [eclipse/jetty.project#1415]
As far as I understand it, when shutting down Jetty with `Server#setStopTimeout` and the `StatisticsHandler`, it will:

1. Finish processing any in-flight requests
2. Return 503s for new requests, even on existing http/1.1 connections
3. Close all connections once in flight requests are done processing, without any application layer notification (just a FIN at tcp layer gets sent)

The problem here is that clients don't necessarily know that Jetty has closed the connection. There is a race condition where they could send a request before receiving the FIN. Detecting the FIN requires doing a read on the socket before sending the request, which is not ideal either.

In our case, we always prefer the client closes the connection. I think this is the only way to obtain 0 failures during shutdown. (This is also how haproxy does its graceful shutdowns, incidentally).

What I'd like Jetty to do is:

1. Process any in-flight requests, and any new requests for the `stopTimeout`, attaching `Connection: Close` header to the response. This lets clients safely close connections rather than just dropping them at the transport layer.
2. Return 503s for new connections, or simply stop accepting new connections (optional - traffic can be redirected at the load balancing level)
3. Wait up to `stopTimeout` for all existing client connections to terminate

Thanks for listening :).

**Comment by joakime** [comment]
This would be ServerConnector specific processing then (applied to HTTP/1.0 and HTTP/1.1 equally, with different rules for HTTP/2).

Some initial questions that pop to mind:

Why are your clients not following the updated HTTP/1.1 RFC7230 spec? (With regards to connection closure rules)
What about in-Jetty Proxy requests?
What about websocket? (or other upgraded connections)
Would this cause problems with long polling requests? (thinking about how cometd)

**Comment by jsravn** [comment]
> Why are your clients not following the updated HTTP/1.1 RFC7230 spec?

They are as far as I know. Do you mean in terms of retries? That doesn't help for non-idempotent methods, which is a good chunk of our traffic, being mostly rest services talking to each other. Please correct me if I am missing something here.

While I agree Jetty is to spec, I think there is a better way to handle things, hence this issue. Otherwise we're forced to use intermediate layers, like commercial load balancers with connection draining features, if we want non disruptive deployments. nginx also has this annoying behaviour, which has forced us to mostly abandon it in favour of haproxy.

We're pretty invested in http/1.1 at the moment, so websockets are not on the radar. I think an rpc protocol would be nice for us as well, but that's not really an option at the moment. I assume long polling would just be handled w/ `connection: close` too.

**Comment by joakime** [comment]
@gregw is this issue addressed now? (as a result of issues #1549 and #2076?)

**Comment by gregw** [comment]
yes
