### ISSUE TITLE
setWriteListener causes race

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1418]
Another variation of #1047 has been detected.

If `HttpInput.setReadListener` is first called from a container dispatched thread when there is no input available, then when the container dispatched thread eventually calls `unhandle`, interest in filling will be set with a call to `channel.asyncReadFillInterested()`

Then is `HttpOutput.setWriteListener` is called from a **non** container dispatched thread, then because the channel is in `ASYNC_WAIT` state, it is woken up so that `onWritePossible` can be called for the first time. This is done by dispatching a thread to call `channel.handle`.

We now have a race between the actual execution of the `channel.handle` and possible arrival of a [succeeded callback](https://github.com/eclipse/jetty.project/blob/jetty-9.4.3.v20170317/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java#L626-L632) for the `asyncReadFillInterested` call.

This race has at least two bad outcome.  Firstly the [succeeded callback](https://github.com/eclipse/jetty.project/blob/jetty-9.4.3.v20170317/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java#L626-L632) does a call to `fillAndParseForContent`, which is not protected by mutual exclusion, so it may enter the parse together with the thread that calls the `handle` method and ends up doing a call to the application code that does a `read()`.  The parser is not reentrant, so this can result in arbitrary corruption while parsing.

Secondly, if the call to `fillAndParseForContent` returns false, the succeeded callback does not know if this is because insufficient data has been received to be content or if the content was received but the app decided it does not yet need to read anymore.  So the callback may then call `channel.asyncReadFillInterested()` as it guesses it needs more data.    However, the other thread may have already called unhandle and registered fill interest, so a Pending read exception may be generated.

**Comment by gregw** [comment]
The fundamental problem is that the async fill succeeded callback is assuming it is the only thread acting on the connection.  It fills and parses in an attempt to determine if there really is content available before possible invoking a call to handle to perform the actual application callback.   It does not simply call handle, as there may actually be no application content available (it might just be a chunk header for example), so it is not possible to simply call handle to call `onDataAvailable` to let the filling/parsing be done within the resulting call to `isReady()`/`read()`, because there may actually be no data and because the application may choose to use the one byte `read()` API, there is no mechanism to always return zero bytes read!

However, the solution is probably along those lines - the handling of the async succeeded callback needs to be done within the scope of `channel.handle`, with filling/parsing done prior to any call to application `onDataAvailable`.   This is significantly different to the initial filling/parsing of a `HttpConnection` prior to calling the application, as that is correct in it's assumption that no other threads will also be filling/parsing.

**Comment by gregw** [comment]
@sbordet need a second brain on this when you have some time available.

**Comment by gregw** [comment]
I've pushed a fix that I think is pretty good... but there are still areas of vulnerability where there is no mutual exclusion, but that correct usage of the API should avoid races.   Need to review if that is good enough.

**Comment by joakime** [comment]
Can we close this one?
