### ISSUE TITLE
Jetty becomes unresponsive after an increase of onReadEof log messsages

### ISSUE THREAD

**Issue by bpoweski** [eclipse/jetty.project#1427]
We've been experiencing some issues with Jetty that appear to only show up under higher load that we have been unable to recreate.

We've observed this issue with the following versions of Jetty:

* Jetty 9.2.9.v20150224 (originally observed in this version, we then upgraded to the following)
* Jetty 9.4.2.v20170220

### Observed Behavior

We first started experiencing these issues after we migrated to use AWS ELB directly to Jetty rather than front end Jetty with Nginx.  This is relevant as our setup previously only utilized HTTP 1.0 whereas it is now using HTTP 1.1 with keep-alive connections.

It appears the issue starts when the ELB closes the connection.  After a short period of time the server stops accepting new connections and the number of `CLOSE_WAIT` sockets on the server steadily increases until the process is restarted.

We managed to capture the event with debug enabled.  I don't see any obvious errors surrounding the issue other than `EofException` (my understanding this is an indicator of the underlying connection being closed).

The following is a dump of the thread pool via JMX:

```
qtp51688773{STARTED,8<=50<=50,i=0,q=870} - STARTED
 +- 17494 qtp51688773-17494 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17500 qtp51688773-17500 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 272 qtp51688773-272-lowPrioritySelector RUNNABLE @ sun.nio.ch.EPollArrayWrapper.epollWait(Native Method) prio=1
 +- 17498 qtp51688773-17498 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17438 qtp51688773-17438 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17502 qtp51688773-17502 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 276 qtp51688773-276-acceptor-2@290f2e93-ServerConnector@762306e{HTTP/1.1,[http/1.1]}{0.0.0.0:8084} BLOCKED @ sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:233) prio=3
 +- 266 qtp51688773-266-lowPrioritySelector RUNNABLE @ sun.nio.ch.EPollArrayWrapper.epollWait(Native Method) prio=1
 +- 17497 qtp51688773-17497 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17474 qtp51688773-17474 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17481 qtp51688773-17481 BLOCKED @ clojure.lang.LazySeq.seq(LazySeq.java:49)
 +- 17488 qtp51688773-17488 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17469 qtp51688773-17469 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17486 qtp51688773-17486 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17506 qtp51688773-17506 WAITING @ sun.misc.Unsafe.park(Native Method)
 +- 17439 qtp51688773-17439 WAITING @ sun.misc.Unsafe.park(Native Method)
....
```

### Environment

```bash
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

```bash
$ uname -a
Linux ip-172-20-104-52 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bpoweski** [comment]
Might be related to #634

**Comment by bpoweski** [comment]
Upon further investigation our issue doesn't appear to have anything to do with Jetty.

**Comment by Thrinath-K** [comment]
I have similar issue with load test. What was your findings related to this issue

**Comment by gregw** [comment]
@Thrinath-K as this issue has been closed some time, it is probably best to open a new one with your exact versions and symptoms.
