### ISSUE TITLE
SelectorManager dispatch time

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#143]
migrated from Bugzilla [#428153](https://bugs.eclipse.org/bugs/show_bug.cgi?id=428153)
status ASSIGNED severity *enhancement* in component *server* for *9.1.x*
Reported in version *9.1.1* on platform *All*
Assigned to: Project Inbox

On 2014-02-13 18:07:54 -0500, Greg Wilkins wrote:

> Evaluate the performance impact of modifying the SelectorManager to record the last selected time on every EndPoint, so a filter could determine how long an individual request has been waiting since last IO.   Note that this is still an imperfect measure as the last IO may occur long after connection and log after the first byte of a request is received.

**Comment by gregw** [comment]
The ability to do this is demonstrated by the [ExtendedServerTest](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/test/java/org/eclipse/jetty/server/ExtendedServerTest.java)
