### ISSUE TITLE
fatal: reference is not a tree: 54f7378064d7e3c786a46ab84b7a53e1efcf034a

### ISSUE THREAD

**Issue by XuSihan** [eclipse/jetty.project#1431]
also, reference is not a tree: 85a690e3cdbbb8447342eefdf690e22ad1b33e02

**Comment by olamy** [comment]
Can you give us more details on your issue?

**Comment by XuSihan** [comment]
Sorry that I got the wrong commit hash...
Thank you :)

**Comment by XuSihan** [comment]
closed
