### ISSUE TITLE
Wrong status message for code 417

### ISSUE THREAD

**Issue by jeffreymorlan** [eclipse/jetty.project#1433]
Response.setStatus(SC_EXPECTATION_FAILED) sends a status line of "HTTP/1.1 417 Im a Teapot". In addition to having a missing apostrophe, this is the wrong message (it's supposed to be for code 418).

This is caused by the constant `HttpStatus.IM_A_TEAPOT_418` having the wrong numeric value. Its `Code` object with the message overwrites the real 417 `Code` in codeMap. From jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java:
```java
public final static int EXPECTATION_FAILED_417 = 417;
public final static int IM_A_TEAPOT_418 = 417;
...
public enum Code {
    ...
    EXPECTATION_FAILED(EXPECTATION_FAILED_417, "Expectation Failed"),
    IM_A_TEAPOT(IM_A_TEAPOT_418, "Im a Teapot"),
    ...
}
```

**Comment by janbartel** [comment]
@jeffreymorlan   :)   fixed.
