### ISSUE TITLE
NullPointerException when calling changeSessionId

### ISSUE THREAD

**Issue by bitpimp** [eclipse/jetty.project#1436]
A bit of a contrived case but still an unexpected NPE when calling changeSessionId and COOKIE is not enabled as the tracking mechanism.

Eg. Only allow URL as session tracking mechanism in web.xml
```
   <session-config>
        <tracking-mode>URL</tracking-mode>
    </session-config>
```

Then issue changeSessionId invocation at some point resulting:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.server.Response.addCookie(Response.java:176)
	at org.eclipse.jetty.server.Request.changeSessionId(Request.java:1492)

```

**Comment by gregw** [comment]
version?

**Comment by bitpimp** [comment]
Sorry, it's jetty-9.4.2.v20170220

**Comment by gregw** [comment]
It will now be a noop.
thanks

**Comment by bitpimp** [comment]
Makes sense. Thanks for a rapid fix!
