### ISSUE TITLE
Logging append defaults should be false

### ISSUE THREAD

**Issue by mrossi975** [eclipse/jetty.project#1437]
hi all,

I have recently discovered that properties

jetty.logging.append
jetty.requestlog.append

default to **false** in their respective XML files jetty-logging.xml and jetty-requestlog.xml

I think they should default to **true** instead as I have discovered when my production environment crashed.
As those properties were both set to false (as I had no knowledge of them) I lost my request log for the day  and crucially the stdout/stderr log too (they were overwritten).

This is obviously a minor problem but I thought it would be worth fixing.

thanks,
Michele

**Comment by WalkerWatch** [comment]
Thank you for bringing this up. I discussed this with another team member and I believe this is the correct default. A typical use case would expect the user would be interested in that run of the server, not prior runs, making **false** most appropriate. Jetty is designed to be lightweight out of the box, allowing users to turn on features to fit their needs.

An additional note:

Configuration of logging in the distribution is best carried out by editing the associated ini file (or start.ini [depending on your setup](https://www.eclipse.org/jetty/documentation/current/startup-modules.html#start-vs-startd)) as opposed to the xml. I did notice that the ini-template for the requestlog module is set up with `true` as the default which contradicts the value in `jetty-requestlog.xml` - I will correct this.

**Comment by mrossi975** [comment]
hi,
I respect your decision but do you have any evidence that 

"A typical use case would expect the user would be interested in that run of the server"

is indeed typical?

That way every time the JVM / Jetty crashes (e.g. OutOfMemory etc) you loose all evidence of what caused the crash. 

How can it be the desired default behavior?

thanks,
Michele

**Comment by mrossi975** [comment]
forgot to add, I loose those files in my case as my Jetty server is managed by linux's "initctl" which of course attempts to restart it right away.

If this is not the usual way to do things I would love to hear about different approaches as the Jetty documentation is quite thin on deployment aspects.

thanks,
Michele

**Comment by jmcc0nn3ll** [comment]
Ah, that last bit is the key point here.  I was trying to understand how these things were just disappearing magically for you.   We can add a bit to the docs around your sort of startup scenario which is of course perfectly valid.  

By default (for better or for worse) the distribution is oriented towards someone downloading and getting things working.  In that respect, you typically are not interested in everything that went on for all of your previous runs so 'false' on the append case makes sense.  Once you have everything working normally then folks invest some time in configuring for their specific needs and deployment scenario, and in my mind your taking the action to integrate with initctl means you would review any other applicable settings related to logging, etc.  Apparently these settings aren't clear enough in the documentation and we can absolutely address that.

fwiw, we have seen plenty of these sorts of scenarios with auto-restart and many of those have logging configured in such a way that logs are getting pulled off the machine and aggregated to some centralized logging service which would not suffer from the problem you have here.  Logging, how much, and what to do with them all is just a huge topic.  We'll try and clear it up a bit more based on your feedback. :)

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch can you take a look at the deployment with this auto-restart concept in mind? might need to add a section specifically for that do it is clear in the toc.

**Comment by WalkerWatch** [comment]
@jmcc0nn3ll I added notes in the appropriate documentation. Can you take a look at d841dba ?

**Comment by WalkerWatch** [comment]
@joakime Can you clarify what needs doing here? I thought we'd decided to leave them default to false but to address it in documentation (which I've done).

**Comment by mrossi975** [comment]
hi, judging by the fact that @joakime changed the issue title from 'Logging append defaults should be false' to 'Logging append defaults should be true' I'd say in absence of a newer comment from him we can go with the latter.

**Comment by joakime** [comment]
Disregard me, I was just changing labels and titles to suite other tooling
If I got it wrong then I got it wrong.
Change it @WalkerWatch to be correct.

**Comment by WalkerWatch** [comment]
They are false as defaults but the associated ini templates for both are set to true. All users need to do is uncomment the line and they are set. I've also noted this in the documentation.
