### ISSUE TITLE
session checkValid not synchronized

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#144]
migrated from Bugzilla [#429519](https://bugs.eclipse.org/bugs/show_bug.cgi?id=429519)
status ASSIGNED severity *normal* in component *server* for *9.1.x*
Reported in version *9.1.0* on platform *PC*
Assigned to: Jan Bartel

On 2014-03-03 17:50:24 -0500, Nathan Robinson wrote:

> The checkValid() method (in AbstractSession.java) has access to '_invalid' in an unsynchronzied block, whereas all other access to that field is wrapped in a synchronized block.
> 
> I suspect this is not intended.

On 2014-03-13 01:28:19 -0400, Jan Bartel wrote:

> Hi Nathan,
> 
> The checkValid() method is mostly called from within synchronized blocks, so does not necessarily need to be synchronized itself.
> 
> I say "mostly" because there are a couple of cases where it is not called from sync blocks:
> 
> + getCreationTime()
> + getLastAccessedTime()
> + isNew()
> + invalidate()
> 
> Of these, the first 2 are probably oversights, and could probably be changed to use sync blocks. However, the last 2 I don't want to change because of unexpected effects - invalidate() could potentially involve deadlocks. 
> 
> This is not as dire as it sounds, as it is relatively rare that the same session is accessed from different threads concurrently.
> 
> The better plan would be to rewrite the session management code, for which there is already an issue open: https://bugs.eclipse.org/bugs/show_bug.cgi?id=429359
> 
> So, in summary, unless you've got a case where the missing synchronization for these calls of checkValid() is a demonstrable problem, then I'd rather address the rewrite.
> 
> regards
> Jan

On 2014-03-13 12:31:16 -0400, Nathan Robinson wrote:

> Hi Jan,
> 
> I don't think it's as rare as you may think. Most web browsers, by default, have 2 open connections to a webserver and some have 10, not including websockets (or other transport protocols) that may be in use.
> 
> 
> I noticed this because I have multiple threads that could call invalidate() at the same time -- which resulted in exceptions getting thrown. My investigation lead to this "not every access is synchronized" issue, and so I synchronized my own calls to alleviate this issue -- and I suspect there are similar workarounds in other concurrent projects.
> 
> 
> As you said, a better plan would be to rewrite session management and I agree that introducing potential deadlocks requires a very careful evaluation of what to do. 
> 
> 
> Until sessions are rewritten, at least others have something to go on, as I suspect that others have said "wtf is going on here" when looking at their logs and noticing that a session's invalid state isn't always correct.
> 
> 
> Thank you for your time,
> -nathan

**Comment by janbartel** [comment]
I'm going to close this issue, as it has been addressed in jetty-9.4.x session rewrite.
