### ISSUE TITLE
Documentation refers to missing class 'AbstractSessionHandler'

### ISSUE THREAD

**Issue by ctron** [eclipse/jetty.project#1447]
The documentation around statistics [1] refers to the non-existing class `AbstractSessionHandler`.

[1] https://www.eclipse.org/jetty/documentation/current/statistics-handler.html#session-statistics

**Comment by janbartel** [comment]
Since jetty-9.4.0 some session statistics are kept on the SessionHandler (no. of sessions created, time spent in sessions etc), and other stats are kept on the DefaultSessionCache.
