### ISSUE TITLE
OnMessage*Callable decoding of streaming binary or text is not thread safe

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#145]
migrated from Bugzilla [#430088](https://bugs.eclipse.org/bugs/show_bug.cgi?id=430088)
status ASSIGNED severity _normal_ in component _websocket_ for _9.1.x_
Reported in version _9.1.2_ on platform _PC_
Assigned to: Joakim Erdfelt

On 2014-03-11 07:15:33 -0400, Mark Thornton wrote:

> This method in org.eclipse.jetty.websocket.jsr356.annotations.OnMessageTextStreamCallable
> 
> ```
> public Object call(Object endpoint, Reader reader) throws DecodeException, IOException
> {
>     super.args[idxMessageObject] = textDecoder.decode(reader);
>     return super.call(endpoint,super.args);
> }
> ```
> 
> can be called from multiple threads. The effect is that some messages are delivered twice while others are not delivered at all!
> 
> Simplest fix would be to clone the array before using it.

On 2014-03-14 14:17:18 -0400, Joakim Erdfelt wrote:

> Can you describe the following in your scenario?
> 
> What is the full / complete signature of your @OnMessage annotated method?
> What is the signature of your Decoders?
> 
> I ask this, as the behavior is rather nuanced for Streams.
> 
> Some examples:
> 
> If the Decoder accepts a TextStream but the object it produces is _NOT_ a Reader itself, then the decoder receives the Reader on the first frame parsed (in a dispatched scenario) and should process the reader in its entirety before the @OnMessage is called.
> 
> But if the Decoder accepts a TextStream _AND_ the object it produces is a Reader as well, then the Decoded object is created on first frame, notified (via a dispatched call) to the @OnMessage on first frame, and subsequent frames are pushed to the internal buffer of the original Reader that the decoder received.
> 
> This is complicated for sure, and there's no test cases (currently) for them.
> I'll be adding a few to test out these behaviors.  Meanwhile it would be useful to know what your signatures look like.

On 2014-03-14 15:32:58 -0400, Mark Thornton wrote:

> public class AbstractJaxbDecoder<T> implements Decoder.TextStream<T>
> {
> public synchronized T decode(Reader reader) throws DecodeException, IOException
> {
> // use JAXB Unmarshaller to parse the stream
> }
> }
> 
> @OnMessage public void onMessage(NetworkRequest request)
> 
> where NetworkRequest is decoded by the decoder above.
> 
> However the problem in this case is the array super.args which is common to all threads using the instance. This is vulnerable between the point that the element [idxMessageObject] is set and when it is used by the reflection in super.call(...). Although this window is short, it does happen more frequently than I might have expected. Unfortunately it is also a classic heisenbug in that trivial modifications to the environment affect the result.

On 2014-03-14 16:28:33 -0400, Joakim Erdfelt wrote:

> In your case, there's a problem with your report.
> 
> The reading thread is single threaded, 
> it parses raw network bytes, 
> on a completed frame it notifies the upstream,
> the upstream calling of Decoder and @OnMessage is never multi-threaded.
> 
> The OnMessageTextStreamCallable is created per instance of the Endpoint, so there's not even any shared instances between Endpoints.
> 
> Still fleshing out a decent test case for this, but the multi-threaded concern is bothersome.
> 
> Are you doing something strange with regards to the Configurator where you are managing your own .getEndpointInstance() perchance?

On 2014-03-14 16:43:15 -0400, Mark Thornton wrote:

> Each message is decoded on a different thread (in general) when using Stream decoders. It is how you handle pushing data to a stream decoder. When the decoder is completed the message is passed to onMessage on that same thread.

On 2014-03-14 16:48:39 -0400, Joakim Erdfelt wrote:

> Added a JSR Client side test for Decode.TextStream behavior to commit [master e141786]

On 2014-03-14 16:49:39 -0400, Joakim Erdfelt wrote:

> Why are you spawning a thread to perform the decoding?
> Implementations of JSR-356 should be dispatching to a new thread for you when working with Streams.

On 2014-03-14 16:53:52 -0400, Joakim Erdfelt wrote:

> Are you using any sort of custom websocket extension that is doing message interleaving?

On 2014-03-14 17:02:58 -0400, Mark Thornton wrote:

> I'm not spawning the thread, Jetty provides it.
> 
> This is some trace from within the onMessage method:
> 
> Received request 1, class=uk.co.optrak.roadmap.services.types.ConnectedLinksRequest, thread=qtp138741741-31
> concurrent onMessage
> Received request 0, class=uk.co.optrak.roadmap.services.types.SetVehicleDescription, thread=qtp138741741-35
> 
> The requests were sent with incrementing message ids. The trace is showing the id as received, the class of message (subclasses of NetworkRequest) and the thread name on which it is received (at the server). The fact that the messages are out of order, and the the handler for message 1 had not completed before it was called with message 0, is the subject of a separate report. The issue here is that because separate threads are in use, the sharing across threads of the array used to construct the call is unsafe.
> 
> I am not using any extensions or custom configuration.

On 2014-03-14 17:40:21 -0400, Joakim Erdfelt wrote:

> Working on validating this on the server side as well, but ...
> 
> That's the order of creation for a OnMessageTextStreamCallable.
> 
> Each endpoint instance gets its own.
> The args[] array is created / copied for each instance of OnMessageTextStreamCallable already.
> 
>   OnMessageTextStreamCallable.<init>(OnMessageCallable) line: 53  
>   JsrEvents<T,C>.<init>(AnnotatedEndpointMetadata<T,C>) line: 99  
>   JsrClientEndpointImpl.create(Object, WebSocketPolicy) line: 49  
>   JsrEventDriverFactory(EventDriverFactory).wrap(Object) line: 118  
>   WebSocketClient.connect(Object, URI, ClientUpgradeRequest, UpgradeListener) line: 194  
>   ClientContainer.connect(EndpointInstance, URI) line: 135  
>   ClientContainer.connectToServer(Object, URI) line: 186  
> 
> So that means ...
> 
> https://github.com/eclipse/jetty.project/blob/master/jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/annotations/OnMessageTextStreamCallable.java#L50
> 
> which is the copy constructor ...
> 
> https://github.com/eclipse/jetty.project/blob/master/jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/annotations/OnMessageCallable.java#L51
> 
> which creates the array ...
> 
> https://github.com/eclipse/jetty.project/blob/master/jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/annotations/JsrCallable.java#L61-L68
> 
> which then copies the values of the array ...
> 
> https://github.com/eclipse/jetty.project/blob/master/jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/annotations/JsrCallable.java#L61-L68

On 2014-03-14 17:54:25 -0400, Mark Thornton wrote:

> Right, but if you now send two messages from a single client to the same endpoint, the thread decoding the first message is suspended for some reason immediately after assigning the result into that array, then the second message has a chance to 'overtake' it and replace that value in the same array. Now the calls take place and what we see is the second message being delivered twice  while the first is lost.
> 
> The decode method on my decoder is synchronized which seems to raise the probability of this unfortunate sequence of events. My test environment involves lots of very short messages that are quick decode and are sent with no significant gap. Why do I use a stream decoder: at least some of the real messages would be rather bigger than my test cases.
> 
> So to get this problem requires the use of stream decoders and a rapid sequence of small messages from a client to an endpoint instance. The client and server probably have to be on the same machine, otherwise network delays would make the event very unlikely.

On 2014-03-14 18:07:48 -0400, Joakim Erdfelt wrote:

> I can set up a test case for that easily enough.
> But it still shouldn't be possible, as the parse/decode/notify is still single threaded.
> The first decode would need to finish + notification would have to complete before the second message even starts being parsed or read from the network.

On 2014-03-14 18:09:49 -0400, Joakim Erdfelt wrote:

> Also, "big messages" in a websocket sense are messages over your memory capacity.
> We have load tests that utilize 40MB messages as single delivery "whole" messages without streaming or compression just fine.

On 2014-03-14 18:12:10 -0400, Joakim Erdfelt wrote:

> (In reply to Mark Thornton from comment # 10)
> 
> > Right, but if you now send two messages from a single client to the same
> > endpoint, the thread decoding the first message is suspended for some reason
> > immediately after assigning the result into that array, then the second
> > message has a chance to 'overtake' it and replace that value in the same
> > array. Now the calls take place and what we see is the second message being
> > delivered twice  while the first is lost.
> 
> Again, if that first message is suspended, then the delivery to @OnMessage for that first message is also suspended.
> If that is suspended, then the second message isn't even parsed.
> No overtake possible here.

On 2014-03-14 18:40:25 -0400, Joakim Erdfelt wrote:

> Commit [master 81c5ca7]
> 
> ```
> + Adding testcase for Decoder.TextStream and lots of short messages with
>   order indicator (for the order in which they were sent)
>   Test case validates that all of the messages were received, not that
>   they were in any particular order (as the use of Streaming prevents
>   reliable ordering)
> + Adding defensive copy of callable array in order to prevent any
>   possibility of concurrency issues with streams and dispatched
>   calls.
> ```

On 2014-03-14 18:46:00 -0400, Joakim Erdfelt wrote:

> Feel free to test this defensive change out.
> The new test case does not fail on Linux w/JDK 7u51, Windows 7 w/JDK 7u45, or OSX 10.9.2 w/ JDK 7u45. (even without the defensive change)
> 
> Added the defensive copy anyway.
> 
> Know this, your use case for websocket streaming is really abusing the API.
> Unless your messages are consistently over 1MB then you should really be using whole message delivery.  It uses less memory, less threads, message order delivery is guaranteed, produces less GC churn, faster throughput, can handle more connections, etc ...
> 
> Streaming websocket was really not designed for a scenario where the majority of messages received are small.

On 2014-04-09 10:27:08 -0400, Mark Thornton wrote:

> I changed to whole message delivery, however despite calling this on opening a session (inside the @OnOpen method):
> 
> ```
>   session.setMaxTextMessageBufferSize(500000);
> ```
> 
> I get this
> 
> org.eclipse.jetty.websocket.api.MessageTooLargeException: Text message size [321106] exceeds maximum size [65536]
>   at org.eclipse.jetty.websocket.api.WebSocketPolicy.assertValidTextMessageSize(WebSocketPolicy.java:140)
>   at org.eclipse.jetty.websocket.common.Parser.assertSanePayloadLength(Parser.java:126)
>   at org.eclipse.jetty.websocket.common.Parser.parseFrame(Parser.java:476)
>   at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:253)
>   at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.read(AbstractWebSocketConnection.java:500)
>   at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:409)
> 
> How are you permitting larger messages?

On 2014-04-09 10:40:37 -0400, Mark Thornton wrote:

> The instance of WebSocketPolicy associated with the frame parser is not the same as the instance associated with the session, so my bigger limits have no effect.

On 2014-05-06 15:35:00 -0400, Joakim Erdfelt wrote:

> Interesting, that technique for JSR endpoints is not tested.
> 
> Here's the thing, if you use an annotated @OnMessage, then you have an @OnMessage(maxMessageSize = 111222) technique.
> 
> If you use Session.addMessageHandler(myHandler), then the Session.setMaxTextMessageBufferSize(int) takes effect.
> 
> Otherwise the @OnMessage use without parameters _should_ indicate a -1 (or no max messages size) limit.

On 2015-12-17 06:56:55 -0500, Haresh Moradiya wrote:

> This issue comes while sender message size is greater than server side setMaxBinaryMessageBufferSize /setMaxTextMessageBufferSize.

**Comment by joakime** [comment]
The entire OnCallable layer is being reworked for bug #207 
Which should fix this for Jetty 9.4.x+

**Comment by joakime** [comment]
This is addressed in the issue-207 branch.
