### ISSUE TITLE
JMX does not export session statistics

### ISSUE THREAD

**Issue by ctron** [eclipse/jetty.project#1450]
The documentation of Jetty says:
> The session statistics are enabled by default and do not need to be configured.

However I was unable to find any session handler, session store, cache, context or other object which actually exports the session statistics in Jetty. Even enabling different session modules and stores did not bring any change.

Tested with Jetty 9.4.2

**Comment by janbartel** [comment]
Thanks, I've instrumented sessions for jmx now.  The stats were on the SessionHandler object, but may not have been visible in jmx.
