### ISSUE TITLE
Support log compression with default NCSARequestLog

### ISSUE THREAD

**Issue by mattsheppard** [eclipse/jetty.project#1458]
I'd be interested in having support in NCSARequestLog for compressing log files to save space. Would you be open to adding that as a feature?

(Aside: I appreciate I could already achieve this by switching to slf4j, but that's mildly inconvenient for reasons that probably aren't of interest)

At a glance, it seems like actually doing it ought to be fairly simple, e.g.

```
msheppard@MacBook-Pro ~/D/t/jetty.project> git diff
diff --git a/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java b/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java
index db3b7be..7659ef1 100644
--- a/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java
+++ b/jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java
@@ -32,6 +32,7 @@ import java.util.Locale;
 import java.util.TimeZone;
 import java.util.Timer;
 import java.util.TimerTask;
+import java.util.zip.GZIPOutputStream;

 /**
  * RolloverFileOutputStream.
@@ -272,7 +273,11 @@ public class RolloverFileOutputStream extends FilterOutputStream
             if (!_append && file.exists())
                 file.renameTo(new File(file.toString()+"."+_fileBackupFormat.format(now)));
             OutputStream oldOut=out;
-            out=new FileOutputStream(file.toString(),_append);
+            OutputStream newOut=new FileOutputStream(file.toString(),_append);
+            if (filename.endsWith(".gz"))
+                newOut=new GZIPOutputStream(newOut);
+            out=newOut;
             if (oldOut!=null)
                 oldOut.close();
             //if(log.isDebugEnabled())log.debug("Opened "+_file);
```

If it would be of interest but not a priority for any current developers I might be able to dedicate a little time to properly implementing it if someone can provide some guidance about how you would prefer to see it exposed configuration-wise.

**Comment by joakime** [comment]
The way to accomplish this is to use the [`Slf4jRequestLog`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/Slf4jRequestLog.java) and setup a formal logger to do whatever you want it to do with the output of the request log events.

We resist making the `StdErrLog` and `RolloverFileOutputStream` fully "logging" capable, as that's not the roll of those classes.  They are for simple behaviors, if you want something more complex, you'll have to graduate to a more formal logging setup and configuration.

**Comment by joakime** [comment]
Your desire is Gzip, the next person will be brotli, the next one will want 7zip, etc.
Then someone will want rolling based on a different trigger, or multiple triggers.
Then another group will want a different filesystem flushing behavior, or synchronization behavior.

(These have all been requests for RolloverFileOutputStream in the past).

Before you know it, we'll have a giant logging infrastructure for something that was intended to be basic and simple, duplicating what many other projects have already accomplished in this space.

**Comment by joakime** [comment]
Also, using GZIPOutputStream here is going to introduce a memory leak in the Deflator objects used, it would need to use a raw Deflater from a pool of Deflater's to get around that. (see #300)

**Comment by mattsheppard** [comment]
Fair enough - Pretty much what I expected to hear - Thanks anyway.

Matt

**Comment by LukeButtersFunnelback** [comment]
Unless I am mistaken, if jetty loads (and configures) sl4j then that sl4j will be used for all of the war files that jetty is going to run. This means that each webapp could not configure sl4j separately. I know very little about the class loading jetty does for its web apps so maybe this wont happen and the webapss class loaders will load their own sl4j and have those configured separately.

@joakime could the logging classes be re-design to so that they are extendable, such that users can make their minor modifications without needing to edit Jetty?

**Comment by joakime** [comment]
By default, without making customizations to the WebAppClassloader behavior, slf4j on the server side has no effect on the webapps choice of logging.

Each webapp can have its own jars and configuration for slf4j, log4j, logback, etc.

This is standard Servlet WebApp ClassLoader isolation.

The only exception is java.util.logging, which is JVM wide (for obvious reasons).

Of particular note, if the webapp uses one of the `ServletContext.log()` methods then it goes to the server logging, not the webapps.

**Comment by joakime** [comment]
@LukeButtersFunnelback the logging classes are all in [`org.eclipse.jetty.util.log`](https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/log) are are extensible already.

Note: `RolloverFileOutputStream` is *not* a logging class.   It is used by the `jetty-distribution` to perform a console capture to file for the usecase of `StdErrLog`.   It is also used by a few (but not all) `RequestLog` implementations to produce a simple file.

**Comment by gregw** [comment]
Note that we accept PRs on documentation also.  So if you did setup a compression logging framework under jetty, we'd be interested in seeing that as an example in the documentation.

**Comment by LukeButtersFunnelback** [comment]
I don't think it would be possible because the methods of interest in `RolloverFileOutputStream` are marked private and even if `RolloverFileOutputStream` could be tinkered with I use a `AsyncNCSARequestLog` which does not let you specify your own implementation of `OutputStream`.  Although maybe you meant doco for using sl4j and logback.

**Comment by gregw** [comment]
I did mean doco for using slf4j/logback.
But if our classes are also too closed to be usefully extended, then we'd certainly look at a PR to make them more flexible.   Adding extensibility to our release is something we do much more frequently than added specific extensions.
