### ISSUE TITLE
Support JDTJavaCompiler on Java 8

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#146]
migrated from Bugzilla [#430691](https://bugs.eclipse.org/bugs/show_bug.cgi?id=430691)
status ASSIGNED severity *normal* in component *jsp* for *9.1.x*
Reported in version *9.1.2* on platform *PC*
Assigned to: Jesse McConnell

On 2014-03-19 08:59:41 -0400, Eirik BjÃ¸rsnÃ¸s wrote:

> I was testing Jetty on Java8 today, and noticed that the JDT Java compiler used by jetty-jsp does not support Java 8.
> 
> Because of https://java.net/jira/browse/JSP-38, I was initially not able to reproduce this on Jetty 9.
> 
> Instead, I tried it on Jetty 8.1.14 which have me the following compilation exception for some JSPs:
> 
> org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP||PWC6199: Generated servlet error:|The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files||
> 	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
> 	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
> 	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
> 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
> 
> I then found a more recent version of jdt-core in this P2 repository:
> 
> http://build.eclipse.org/eclipse/builds/4P/siteDir/updates/4.3-P-builds/P20140317-1600/plugins/
> 
> by way of this wiki: http://wiki.eclipse.org/JDT/Eclipse_Java_8_Support_%28BETA%29
> 
> Upgrading JDT to the GA release seems to fix my issues using Java 8.
> 
> I guess this issue is blocked by either JSP-38 or switching to Apache JSP.
> 
> Is there any legal work required for an upgrade to JDT Core 3.9.50.v20140317 ?

On 2014-03-19 09:04:35 -0400, Eirik BjÃ¸rsnÃ¸s wrote:

> Let me add that I've also tested the combination of JDT Core 3.9.50.v20140317 with Jetty 9.2.3 and Glasshfish JSP 2.3.3-SNAPSHOT with my patch of JSP-38 resurrecting the JDTCompiler. Seems to work fine.

On 2014-03-21 11:47:43 -0400, Jesse McConnell wrote:

> eirik,
> 
> do you have an eclipse p2 repository that contains both a binary and src artifact that solve this issue?

On 2014-03-21 11:50:06 -0400, Jesse McConnell wrote:

> does this represent the stuff that works?
> 
> http://download.eclipse.org/eclipse/downloads/drops4/R-4.3.2-201402211700/#JDTCORE
> 
> they are different named and sized artifacts but I seem to remember ecj was just what was needed originally

On 2014-03-22 06:23:39 -0400, Eirik BjÃ¸rsnÃ¸s wrote:

> Jesse,
> 
> I'm not at all familiar with P2 repositories or the Eclipse release process to say what's the right jar. 
> 
> But I've updated my test to use ecj-4.3.2.jar from your link and that works fine on both Java 8 and Java 7.
> 
> But I guess we need to see this copies to Maven Central, right?

On 2014-03-23 23:23:13 -0400, Jan Bartel wrote:

> Assigning to Jesse to handle the process for the IP clearance and availability in maven central for latest ecj compiler. Assign back to me to do the support inside the tomcat-based version of jasper
> 
> Jan

**Comment by janbartel** [comment]
Was fixed by commit https://github.com/eclipse/jetty.project/commit/781a380fbd6f5f8186a88b107ce90755e04a4db6 for jetty-9.3.6 and above.
