### ISSUE TITLE
Jetty-Client trigger ResponseSuccess when http response's content-length is greater than actual received chunk size

### ISSUE THREAD

**Issue by likaiwalkman** [eclipse/jetty.project#1460]
I used jetty client in async way, when I requested a mocked service which will send content-length: 11 while only provide '1234567890' in its response body.but the client at last triggered OnResponseSuccess handler.
Further more, I would like to know which is the right way to collect http response for asyn invocation.
My way is like this:
```
.onResponseContentAsync(new Response.AsyncContentListener {
        override def onContent(response: Response, content: ByteBuffer, callback: Callback): Unit = {
          val b = new Array[Byte](content.remaining)
          content.get(b, 0, b.length)
          val str = new String(b)
          println(str)
          phaseEventDispatchActor ! OnResponseContentAsync(str)

          callback.succeeded()
        }
      })
```
and:
```
request.send(new BufferingResponseListener() {
        override def onComplete(result: Result): Unit = {
          val content = getContent
          println(content)
        }
      })
```
as the official guide tells me, to know the final request is successful or not by !result.isFailed().
Does anyone encountered the problem i mentioned above?

**Comment by likaiwalkman** [comment]
Sorry, I didn't repeat this issue again.
Maybe previous phenomenon occured due to testing is exceeding proper time.

**Comment by sbordet** [comment]
If it's resolved for you, please close the issue. Thanks !

**Comment by likaiwalkman** [comment]
Not an issue.
