### ISSUE TITLE
ThreadPool check thread funtionality

### ISSUE THREAD

**Issue by cy6erGn0m** [eclipse/jetty.project#1461]
```java
public interface ThreadPool extends Executor {
....

    /**
    * returns true if the given thread is a member of the pool
    */
    public boolean isPoolThread(Thread thread)

....
}
```

for general QueuedThreadPool it could be done like this

```
public boolean isPoolThread(Thread thread) {
    return thread != null && _threads.contains(thread)
}
```

Not sure if it should be added to `ThreadPool` interface as it probably impossible to implement for `ExecutorThreadPool`.

**Comment by gregw** [comment]
I don't think we can put this into the `ThreadPool` interface, even with a default method, as many users use ExecutorThreadPool and there is no equivalent on Executor.

Without the API on `ThreadPool` nor `Excecutor` then it is not really a general purpose method and will need specific knowledge and down casting.... thus it is probably best to leave as you have it - a simple extension to a specific thread pool usage.   However, if you really would prefer it not to be in Kotlin, then we can add it to `QueuedThreadPool`, but you will still need jetty specific code that is not that much simpler that what you already have.  Thoughts?

**Comment by cy6erGn0m** [comment]
For now the only solution I know is to use a separate thread group so we can compare it to check thread. But it doesn't work as far as users could provide no thread group at all. For queued thread pool the only solution is ‘Thread.name. startsWith(pool.name)‘ that is definitely too bad :)

**Comment by sbordet** [comment]
@cy6erGn0m can you detail _why_ you need to know if a thread is from the Jetty thread pool ?
What use do you make of that information ?

**Comment by apatrida** [comment]
@sbordet, this issue was referenced from https://github.com/Kotlin/ktor/commit/8eb12fd5b603b4f19e51b9d8bdcb9436fb2a43d2 adding coroutines support for KTOR framework when working on top of Jetty.  (Coroutines instead of threads)

**Comment by sbordet** [comment]
@cy6erGn0m I don't see any problem adding the method to `QueuedThreadPool` (but not to `ThreadPool` as you noted).

The code referenced by @apatrida already casts down to `QueuedThreadPool` so it would just be a little more efficient (hash search versus string search)

**Comment by joakime** [comment]
Considering that `QueuedThreadPool` already supports `ThreadGroup` wouldn't this issue be moot anymore?
As you can just ask the `Thread.getThreadGroup()` and see if it belongs to the pool.
Even if you are using java's `Executor`, you can set many of those implementations up to also use `ThreadGroup` too.

@sbordet thoughts?
