### ISSUE TITLE
RFC5746 : Review TLS/1.2 and Renegotiation

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1465]
See https://tools.ietf.org/html/rfc5746

Does this mean any changes in Jetty? (code or configuration)

**Comment by joakime** [comment]
Possibly we should default the `setRenegotiationAllowed(bool)` to `false` in both `SslContextFactory` and `SslConnection` ?

**Comment by gregw** [comment]
A renegotiation limit was added
