### ISSUE TITLE
Only use ServletContainerInitializers from server path for web.xml < 3.0

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1466]
ServletContainerInitializers are currently loaded from both the server path and the webapp's classpath. If a webapp includes a jar that happens to contain a ServletContainerInitializer, it will be applied, even if the webapp itself has a web.xml version < 3.0.  This might be considered unexpected behaviour.  We could apply ServletContainerInitializers only from the server's classpath in the case where web.xml < 3.0.

**Comment by joakime** [comment]
Since this would be a Server path only fix.
Perhaps we could have an annotation `@ServletSupportLevel(3.0)` that can help trigger these in appropriate places (such as Servlet 2.5 and JSR356 websockets).

**Comment by janbartel** [comment]
Not sure I follow @joakime. The point here would be to not do any annotation processing at all, if web.xml < 2.5.

**Comment by joakime** [comment]
Of the 2 SCIs in Websocket, the JSR356 one should never execute (even with a blank class Set) on a webapp declared as Servlet 2.5.  

But the other one (native Jetty Websocket) is fine on Servlet 2.5.

**Comment by joakime** [comment]
Are you proposing that all SCI's on the Server side do not run when the webapp is Servlet 2.5?

**Comment by janbartel** [comment]
@joakime, no I'm proposing that ONLY SCIs that are on the server path run when web.xml < 3.

**Comment by joakime** [comment]
Perhaps only run server SCIs that have no `@HandlesTypes` present?

**Comment by janbartel** [comment]
@joakime I think that if the SCIs are present on the server side then they've a) been selected for use by the user and b) necessary for the server to deliver services, so I would run all server SCIs, and if they happen to have an @HandlesTypes, then so be it.  

Where are the SCIs for websocket, on the server path or on the webapp path?

**Comment by joakime** [comment]
There's 2, both on the server side.

[/javax-websocket-server-impl - `WebSocketServerContainerInitializer.java`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/javax-websocket-server-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/server/deploy/WebSocketServerContainerInitializer.java)

JSR356 was introduced as a part of JEE7 / Servlet 3.1, this one cannot function on older Servlet specs and APIs, it should never be executed for Servlet 2.4/2.5/3.0 webapps.

[/websocket-server - `NativeWebSocketServletContainerInitializer.java`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/NativeWebSocketServletContainerInitializer.java)

This one should work find on Servlet 2.4+

**Comment by janbartel** [comment]
Change committed.  Users who had previously never updated their web.xml past version 2.5 but had newer 3.1 jars with SCIs etc in WEB-INF/lib will need to either:

1. update the web.xml
or
2. use WebAppContext.setConfigurationDiscovered(true)

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch should make sure there is a NOTE on this in the docs under deployment somewhere, probably near a metadata-complete=true comment

**Comment by ThrawnCA** [comment]
@jmcc0nn3ll Yeah, I don't think that this ever reached the docs. We're trying to update from Jetty 9.2 to 9.4 and were getting 404s on everything because our `web.xml` still declared webapp version 2.4. Would be good to document this.
