### ISSUE TITLE
Change default for WebAppContext.isConfiguredDiscovered to false

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1467]
WebAppContext configurationDiscovered was added back during the transition from servlet spec 2.5 -> 3.0 before the expert group had released any schemas, and was intended to allow webapps to take advantage of 3.0 behaviour (eg annotations).

It's default value is true.  This means that even if you have a 2.5 web.xml, you will still get annotation scanning happening by default. We should consider setting it to false, or removing it.

**Comment by janbartel** [comment]
Changed the default to false.

Also made sure that if it is a 2.5 webapp and !configurationDiscovered, or its a 3.x webapp with metadata-complete==true, we do not even bother looking for web-fragment.xmls.

Also added some unit tests to check skipping annotation scanning and looking for web-fragment.xmls.

**Comment by sd4324530** [comment]
Oh,the bug maker is here! 😂😂
I have been using servlet 3.0 for a long time , and I upgrade jetty to 9.4.4.v20170414, then my project can't run!
Because I used this annotation ‘@WebListener’

**Comment by sd4324530** [comment]
`<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>9.4.4.v20170414</version>
				<configuration>
					<scanIntervalSeconds>0</scanIntervalSeconds>
					<httpConnector>
						<port>8080</port>
					</httpConnector>
					<webApp>
						<contextPath>/test</contextPath>
						**<configurationDiscovered>true</configurationDiscovered>**
					</webApp>
				</configuration>
			</plugin>`

**Comment by sd4324530** [comment]
<configurationDiscovered>true</configurationDiscovered>
<configurationDiscovered>true</configurationDiscovered>
<configurationDiscovered>true</configurationDiscovered>
<configurationDiscovered>true</configurationDiscovered>
<configurationDiscovered>true</configurationDiscovered>
<configurationDiscovered>true</configurationDiscovered>

then it's OK
