### ISSUE TITLE
Configure PKIX Revocation Checker for SslContextFactory

### ISSUE THREAD

**Issue by aminjashki-okta** [eclipse/jetty.project#1468]
Java 8 has a [security enhancement](https://docs.oracle.com/javase/8/docs/technotes/guides/security/certpath/CertPathProgGuide.html#PKIXRevocationChecker) which has to do with checking the revocation status of certificates. 

This class comes with a few [options](https://docs.oracle.com/javase/8/docs/api/java/security/cert/PKIXRevocationChecker.Option.html) to be configured. It would be great if this could be a configuration option for SslContextFactory to allow the users of Jetty to use the new JDK8 feature.

For example, if one needs to soft fail CRL list downloads you can achieve that with the following snippet. 

<code>

        PKIXBuilderParameters pbParams = new PKIXBuilderParameters(trustStore, new X509CertSelector());

        CertPathBuilder certPathBuilder = CertPathBuilder.getInstance("PKIX");
        PKIXRevocationChecker revocationChecker = (PKIXRevocationChecker) certPathBuilder.getRevocationChecker();

        revocationChecker.setOptions(EnumSet.of(PKIXRevocationChecker.Option.PREFER_CRLS, PKIXRevocationChecker.Option.SOFT_FAIL, PKIXRevocationChecker.Option.NO_FALLBACK));

        pbParams.addCertPathChecker(revocationChecker);
</code>

As of right now, the only way to achieve this is to extend SSlContextFactory and override 

 `getTrustManagers(....)` which is less than ideal for obvious reasons. It would be great if Jetty supported this out of the box as a configuration.

**Comment by joakime** [comment]
We accept pull requests (with valid Eclipse ECA)

**Comment by gregw** [comment]
I have added a setter for the revocation checker, plus I have moved the whole param handling into a protected method for simpler extension.

For now I have just added a commented out example of how to configure in XML in the jetty-ssl-context.xml.   However, if there was a best practise setup for this, then we could add that as a module of its own.

**Comment by sbordet** [comment]
@gregw is this issue finished?

**Comment by gregw** [comment]
It would be good to get a better example, but I'd need some external guidance from the OP.  Will leave open, but labelled Stale do see if OP can give more info.

**Comment by sbordet** [comment]
Closing in favor of #5533.
