### ISSUE TITLE
Broken *.gz symlinks cause NPE in DefaultServlet.

### ISSUE THREAD

**Issue by brimworks** [eclipse/jetty.project#1472]
To reproduce this issue, simply setup jetty to serve compressed content with the DefaultServlet.

In the directory serving content, create a broken symlink for a .gz file:

`ln -s does-not-exist index.html.gz`

Now, make a request for index.html with the Accept-Encoding: gzip header which should attempt to serve the *.gz and cause a NullPointerException.

The fix is very simple:

https://github.com/Distelli/jetty.project/commit/a518185bf72f0e6efe4e67bfbb769fafe3f134ad

Thanks,
-Brian

**Comment by janbartel** [comment]
Hi @brimworks, would you like to submit a pull request, or are you happy for me to just put in the null check?

**Comment by brimworks** [comment]
Feel free to add the null check yourself.

Thanks,
-Brian

**Comment by janbartel** [comment]
Done! Thanks.
