### ISSUE TITLE
ErrorHandler should not force Writer mode for JSPs

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1478]
A report has been made where the error-page handling for `<location>/myerror.jsp</location>` doesn't work because the `ErrorHandler `sets the output mode to Writer (where the Apache JSP engine uses OutputStream).

**Comment by gregw** [comment]
sendError is now always used to generate an error page.  However as this can be directed to an arbitrary page that may generate the error page any way that it likes, the caller cannot assume anything about how that page is generated (nor can Jetty make any guarantees about it).
