### ISSUE TITLE
IPAccessHandler doesn't work for IPv6

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#148]
migrated from Bugzilla [#434583](https://bugs.eclipse.org/bugs/show_bug.cgi?id=434583)
status ASSIGNED severity _normal_ in component _server_ for _9.2.x_
Reported in version _9.1.4_ on platform _PC_
Assigned to: Project Inbox

On 2014-05-10 17:27:01 -0400, Thomas Meyer wrote:

> Using the IPAccessHandler gives this result, when accessing jetty from IPv6 network:
> 
> <html>
> <head>
> <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
> <title>Error 500 </title>
> </head>
> <body>
> 
> <h2>HTTP ERROR: 500</h2>
> 
> <p>Problem accessing /index.html. Reason:
> <pre>    Invalid IP address: 2a01:4f8:d15:1944:0:0:0:2</pre></p>
> 
> <hr /><i><small>Powered by Jetty://</small></i>
> </body>
> </html>
> 
> The problem is that the class
> jetty-server/src/main/java/org/eclipse/jetty/server/handler/IPAccessHandler.java
> uses the 
> jetty-util/src/main/java/org/eclipse/jetty/util/IPAddressMap.java
> (static class IPAddrPattern which seems only to support IPv4).

On 2014-05-13 05:06:59 -0400, Greg Wilkins wrote:

> Thomas,
> 
> we definitely want to support IPv6 completely.   However we currently don't have a good IPv6 testing environment, so it may take us a little while to get around to looking at this issue.
> 
> So if you do have a good IPv6 test environment and if you were ever interested in contributing to the Jetty project, then this is a perfect opportunity!  It would be great to get a contribution to upgrade IPAddressMap to also handle IPv6!

On 2014-05-19 14:48:46 -0400, Thomas Meyer wrote:

> > So if you do have a good IPv6 test environment and if you were ever
> > interested in contributing to the Jetty project, then this is a perfect
> > opportunity!  It would be great to get a contribution to upgrade
> > IPAddressMap to also handle IPv6!
> 
> Hi, I could implement this. But this is just a hobby project, and I have currently really little free time, so this could take a while...

On 2014-05-19 15:58:34 -0400, Greg Wilkins wrote:

> Thomas,
> 
> Jetty started out as a hobby project - 20 YEARS AGO!!! so from little things big things grow.
> 
> We certainly don't have time to look into this at the moment, so a slow contribution would be better than no contribution!
> 
> cheers

**Comment by dsmiley** [comment]
Based on the discussion in #1072 it appears this issue should be closed as Won't-Fix because this class is deprecated, _partially_ replaced by `InetAccessHandler` which is IPv6 compatible.
