### ISSUE TITLE
Add --lenient-ssl command line switch to start.jar to allow for any ssl target

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#149]
migrated from Bugzilla [#436521](https://bugs.eclipse.org/bugs/show_bug.cgi?id=436521)
status ASSIGNED severity _enhancement_ in component _start_ for _9.2.x_
Reported in version _9.2.0_ on platform _All_
Assigned to: Joakim Erdfelt

On 2014-06-03 19:20:35 -0400, Joakim Erdfelt wrote:

> When using https:// based URLs in [files] sections, the default java security is used, allow a command lines switch to enable lenient accept-all ssl certificate operation.

**Comment by gregw** [comment]
wont implement
