### ISSUE TITLE
WebAppClassloader needs to handle Classes with no location

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1490]
The changes to the `WebAppContext` and `WebAppClassloader` in Jetty 9.4.x introduced a novel approach for checking the origin/location of a Class to know if its a Server or System class.

As a result of a review of `TypeUtil.getLoadedFrom()` in issue #1489 (due to a review in Issue #1448), its clear that location is not always available.

These checks in WebAppContext need to handle the case where the Class has no location.
What does that mean for the `WebAppContext.isServerClass()` or `.isSystemClass()`?

Some scenarios where this is true.

 * On some environments, fundamental java base classes, such as `java.lang.String`, have no location (either via ProtectionDomain.CodeSource.Location, or via ClassLoader resource lookup).
 * Where Custom ClassLoader prevent the lookup via Resource.
 * Where Classes that are dynamically created in memory.
 * Where Custom URLStreamHandler's change the behavior of how a class is loaded.
 * Java security constraints.
 * Java 9 and module use.
 * OSGi and non-jar "bundle:" use.
 * Android's JVM security for core classes.

**Comment by gregw** [comment]
This has been resolved by #1498 and #1499.  Classes loaded from modules will have a jrt:// location, which can be included/excluded in the classpath patterns,
