### ISSUE TITLE
Add JRTResource for Java 9 behaviors

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1498]
As documented in JEP220 - 
http://openjdk.java.net/jeps/220#New-URI-scheme-for-naming-stored-modules-classes-and-resources

There is a new `jrt://` scheme that we should add if we want `ClasspathPattern` to work with the Java 9 Run Time in the future.

**Comment by gregw** [comment]
I think this should be developed in jetty 10.0.x and backported to 9.4 if/when appropriate

**Comment by joakime** [comment]
Then `PathResource` in Jetty 9.4 should be changed to recognize `file:` and `jrt:` to be equivalent while we wait for the Jetty 10 approach.

Code using the TypeUtil.getLocation*(Class) methods will return URL/URI's that contain `jrt:` schemes when running on Java 9 today.  Those URL/URI's are being interpreted incorrectly due to our lack of `jrt:` support.

For example Resource.getResource(URL) doesn't recognize it, it can then go to Resource.getResource(String) which assumes badly things like `jrt:/java.base/` being a classpath resource.

Another example: a `jrt:` URL/URI passed to `Paths.get(url)` will return a valid Path, but not one that is for an actual real physical filesystem, so doing things like .getParent() or list() on that path has no meaning or an unexpected meaning.

**Comment by gregw** [comment]
@joakime I've done some quick testing and so far it mostly works via the Resource.getResource(URI) path which returns a URLResource.

We should probably still specialise that to a JRTResource so we can put in meaningful behaviours for getParent etc.

**Comment by gregw** [comment]
@joakime @sbordet I think URLResource with the small tweak I just committed is sufficient.   Unless otherwise indicated I will cherry pick this back to jetty-9 tomorrow.

**Comment by gwtuser** [comment]
In Jetty 9.4.7 included with the GWT Plugin for Eclipse, I'm getting the following when running with JDK9.0.1:
"Found resouce but unrecognized URL format: 'jrt:/java.sql/javax/sql/DataSource.class'"

Note the misspelling.  That line apparently comes from GWT's JettyLauncher.  But to confirm, jetty itself (v 9.4.7) should have no problem with a jrt: resource?

**Comment by joakime** [comment]
@gwtuser The misspelling of "resouce" tells me this is a message from GWT.

Yup ... https://groups.google.com/forum/#!msg/google-web-toolkit-contributors/9Qt4TBPUBBU/SWjFrqDWTwEJ

This is a problem in GWT, not Jetty. sorry.
