### ISSUE TITLE
ClasspathPattern needs MODULE ruleset

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1499]
Currently ClasspathPattern has PACKAGE, CLASSNAME, and LOCATION

Starting with Java 9, the new `jrt://<module>/<path>` behaviors (see Issue #1498), there should also be a MODULE ruleset to define any classes found within a specific module

**Comment by joakime** [comment]
Current ClasspathPattern rules for LOCATION do not work with `jrt:` schemes.

It identifies as `Type.CLASSPATH` which never matches java classes (like java.lang.String)

**Comment by gregw** [comment]
I think this should be developed in jetty 10.0.x and backported to 9.4 if/when appropriate

**Comment by joakime** [comment]
This is affecting users on Jetty 9.4 using Java 9 today.

It should be fixed to at least recognize the `jrt:` scheme and set to be equivalent to `Type.LOCATION` in the short term.

In other words `file:` and `jrt:` should be equivalent in meaning on Jetty 9.4.

The ClasspathPatternTest fail on Java 9 now, and show this behavior difference currently if you want to debug it.

**Comment by gregw** [comment]
@sbordet @joakime I've committed a more efficient implementation, which I think could be cherry picked back to jetty-9 already.

**Comment by gregw** [comment]
Note that currently it only supports including/excluding jrt:/module and not jrt:/module/classname.    I see no reason to include/exclude both module and classname as you can simply use the classname patterns.  Correct me if I'm wrong???

Otherwise will cherry pick to jetty-9 tomorrow
