### ISSUE TITLE
extraClasspath() method on WebAppContext dont support dir path

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#150]
migrated from Bugzilla [#438482](https://bugs.eclipse.org/bugs/show_bug.cgi?id=438482)
status ASSIGNED severity _enhancement_ in component _server_ for _9.2.x_
Reported in version _8.1.12_ on platform _PC_
Assigned to: Jan Bartel

On 2014-06-29 06:33:09 -0400, Nir Barel wrote:

> Hi,
> 
> I am trying to load extra libs using extraClasspath() from a dir path but jars are not loaded.
> if I specify the list of jars one by one it works well.
> I checked that in Jetty 8 and Jetty 9
> I need it to work for Jetty 8 mostly.
> 
> my configuration:
> 
> <?xml version="1.0"?>
> <!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
> 
> <Set name="contextPath">/war</Set>
> <Set name="war"><Env name="SERVER" default="."/>/app/webapps/war.war</Set>
> <Set name="extraClasspath"><Env name="SERVER" default="."/>/extralibs</Set>
> <Call name="setInitParameter">
>     <Arg>org.eclipse.jetty.servlet.Default.dirAllowed</Arg>
>     <Arg>false</Arg>
> </Call>

On 2014-06-30 20:19:44 -0400, Jan Bartel wrote:

> Nir,
> 
> If I understand correctly, you are asking for an enhancement to enable setExtraClasspath to recursively add jars to the classpath, yes? I'm updating the bug accordingly.
> 
> Jan

On 2014-07-01 00:59:54 -0400, Nir Barel wrote:

> Hi,
> 
> In the documentation example you already explain that you support directory and not just jar's...
> 
> <Configure class="org.eclipse.jetty.webapp.WebAppContext">
>  ...
>  <Set name="extraClasspath>../my/classes,../my/jars/special.jar,../my/jars/other.jar>
>  </Set>
>  ...
> 
> see:
> 
> jetty 8:
> http://wiki.eclipse.org/Jetty/Reference/Jetty_Classloading#Using_the_extraClasspath.28.29_method
> 
> jetty 9:
> http://www.eclipse.org/jetty/documentation/current/jetty-classloading.html
> 
> So I think it's a bug and not enhancement.
> 
> can you fix it also for jetty 8?

On 2014-07-01 05:27:14 -0400, Jan Bartel wrote:

> Nir,
> 
> I'm still not sure what problem you are reporting. The documentation and the code shows that we support a classpath just like a java classpath. In other words, you can add a series of extra classpath elements, where each element can be a directory of classes, or a jar file. Are you saying that this does not work? Or are you saying that you want to add a directory that contains jar files and have jetty add all the jar files in that directory???
> 
> Jan
> 
> (In reply to Nir Barel from comment # 2)
> 
> > Hi,
> > 
> > In the documentation example you already explain that you support directory
> > and not just jar's...
> > 
> > <Configure class="org.eclipse.jetty.webapp.WebAppContext">
> >  ...
> >  <Set
> > name="extraClasspath>../my/classes,../my/jars/special.jar,../my/jars/other.
> > jar>
> >  </Set>
> >  ...
> > 
> > see:
> > 
> > jetty 8:
> > http://wiki.eclipse.org/Jetty/Reference/
> > Jetty_Classloading#Using_the_extraClasspath.28.29_method
> > 
> > jetty 9:
> > http://www.eclipse.org/jetty/documentation/current/jetty-classloading.html
> > 
> > So I think it's a bug and not enhancement.
> > 
> > can you fix it also for jetty 8?

On 2014-07-01 05:34:04 -0400, Nir Barel wrote:

> Hi,
> 
> OK now I understand what ../my/classes means..
> Yes I want to add folder with jars and let Jetty to load them all.
> a "nice to have" feature can be arguments with exclude / include lists for this folder.
> 
> actually because jetty doesn't support it I add my own function that generate that list and I invoke a java method from the XML configuration.
> 
> <Set name="extraClasspath">
> <Call class="com.company.jetty.ExtraClasspath" name="generateCpmClasspath">
> <Arg><Env name="SERVER" default="."/></Arg>
> </Call>
> </Set>
> 
> can enhancement be delivered also to Jetty 8?

**Comment by chinhodado** [comment]
I am running into this same issue. Is this fixed yet or is there a workaround, instead of having to specify each jar file manually.

**Comment by janbartel** [comment]
@chinhodado  we would be very happy to accept a pull request that implements this enhancement.

**Comment by janbartel** [comment]
This feature was added to jetty-9.4.
