### ISSUE TITLE
HttpServletResponse.sendError() should commit and close

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1500]
We have reports that its possible to continue to use the `HttpServletResponse` after using `.sendError()`

Per the _Servlet Spec 5.6 Closure of Response Object_ the sendError() call should commit, flush, and close the response object.

**Comment by joakime** [comment]
Unable to replicate with testcase.

**Comment by joakime** [comment]
@gregw after review, it seems the `closeOutput()` behavior is spread around in many different places.

See the various locations in `ErrorHandler` and also in one path in `sendError()`.
Would it make sense to have `sendError()` always call `closeOutput()`? (per the servlet spec), and not in the limited number of scenarios that it currently has?

**Comment by gregw** [comment]
@joakime +1 on that proposed solution. testing that now.
