### ISSUE TITLE
WebSocket endpoints cannot be mapped when the session id is url encoded

### ISSUE THREAD

**Issue by martin-g** [eclipse/jetty.project#1502]
Version: 9.4.4

If the session id is tracked in the url then making a request to `ws://.../my/endpoint;jsessionid=xyz` won't match because org.eclipse.jetty.websocket.server.NativeWebSocketConfiguration#getMatch() [1] does an `EXACT` match without stripping `;jsessionid=...` before doing this.

Without `;jsessionid=...` the mapping works but `javax.websocket.server.HandshakeRequest#getHttpSession()` returns `null` in `javax.websocket.server.ServerEndpointConfig.Configurator#modifyHandshake()`.

1. https://github.com/eclipse/jetty.project/blob/5e4853e177abf5819f221c63a800edb36b4acc7d/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/NativeWebSocketConfiguration.java#L100

**Comment by joakime** [comment]
PathMapping matching is performed based on the type of PathSpec implementation in play.

What PathSpec implementation are you using? (there are 3)

Note, "/my/endpoint;jsessionid=xyz" is a path parameter, it belongs to the path element "endpoint".  Just like "/my/endpoint;jsessionid=xyz/subtype;foo=bar" is a path with 2 parameters (one on "endpoint", and one on "subtype".  How did you create such a URL with Jetty? (I thought our Session implementations discouraged that for security reasons)

**Comment by martin-g** [comment]
Hi @joakime !

The issue I'm trying to solve is https://issues.apache.org/jira/browse/WICKET-6360.
What I need is to get a reference to the http session in `#modifyHandshake()`.
The `ws://...` url is constructed in JavaScript code, so I actually appended `;jsessionid=theID` myself.
The debugger says that `org.eclipse.jetty.http.pathmap.UriTemplatePathSpec` is being used for this mapping.

**Comment by joakime** [comment]
`UriTemplatePathSpec` is from the JSR356 support level.  

Know that JSR356 paths are declared as URI Template Level 1 supported paths.
http://docs.oracle.com/javaee/7/api/javax/websocket/server/ServerEndpoint.html#value--

These paths are not part of the Servlet spec behaviors.  Never have been.
The use of `;text` is actually part of the URI-Template Level 3 support.
https://tools.ietf.org/html/rfc6570#section-3.2.7

JSR356 deployed endpoints should never work with path parameters.

However, that being said, the `ServletPathSpec` behavior is also failing on this particular scenario when used within the Filter based WebSocket upgrade paths (works fine in Servlet based and Handler based).

**Comment by joakime** [comment]
This doesn't feel right.  JSR356 is a weird minefield of behaviors.
Need to see if we can support this without breaking the expectations of JSR356.

**Comment by martin-g** [comment]
Does that mean that if the session id is url encoded then there is no way to get a reference to the HTTP session during the upgrade ?

**Comment by martin-g** [comment]
BTW by chance this behavior works fine in Tomcat 8.5.13.

**Comment by joakime** [comment]
The fact that there is no HttpSession in the request object means that the pre-websocket code doesn't even see that as a session reference.

The websocket code to match and endpoint is a primary concern of this issuem which we should focus on first.

If you have no HttpSession after that fix, then we need to look at the Session configuration logic you have in play.

**Comment by martin-g** [comment]
OK. Please let me know if I can help with testing!
Thank you!

**Comment by joakime** [comment]
@martin-g I pushed a fix to the the jetty-9.4.x branch at commit 4c5dd93

**Comment by martin-g** [comment]
Where I can find a new -SNAPSHOT with the change ?
There is no `jetty` at https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/

**Comment by joakime** [comment]
We have our own repos on oss.sonatype.org

https://oss.sonatype.org/content/repositories/jetty-snapshots/

We were a very early adopter of oss.sonatype.org 

Snapahot version `9.4.5-20170425.090919-6` should have that change

**Comment by joakime** [comment]
@martin-g any update?

**Comment by martin-g** [comment]
I'll test it tomorrow morning!

**Comment by martin-g** [comment]
We use 
```xml
<dependency>
	<groupId>org.eclipse.jetty.aggregate</groupId>
	<artifactId>jetty-all</artifactId>
	<version>${jetty.version}</version>
	<scope>test</scope>
        <classifier>uber</classifier>
</dependency>
```
but it seems there are no 9.4.5-SNAPSHOT builds for the aggregates.
It will take me some more time to figure what dependencies I'll have to use to replace it.

**Comment by joakime** [comment]
@martin-g do not use jetty-all as a dependency, its not meant for that.

See https://dev.eclipse.org/mhonarc/lists/jetty-users/msg06030.html

**Comment by martin-g** [comment]
Thanks, @joakime !
I confirm that the fix is good!

One more question: 
with (web.xml)
```xml
<session-config>
        <cookie-config>
            <name>blah</name>
        </cookie-config>
</session-config>
```
I can change the name of the session cookie.
Do you know whether it is possible to change the name of the path parameter `jsessionid` with any means, Servlet API or Jetty specific ones ?

**Comment by martin-g** [comment]
> @martin-g do not use jetty-all as a dependency, its not meant for that.

Improved with https://issues.apache.org/jira/browse/WICKET-6363! Thank you!

**Comment by joakime** [comment]
Considering this fixed.
