### ISSUE TITLE
Negative delay Timer.schedule exception due to mismatched local and _logTimeZone values

### ISSUE THREAD

**Issue by KentPeacock** [eclipse/jetty.project#1507]
I'm getting this exception when the _logTimeZone value is the default (GMT) while in US/Pacific (-7).

2017-04-25 18:21:44.407:INFO:oejs.AbstractConnector:main: Started ServerConnector@4c18516{SSL,[ssl, http/1.1]}{0.0.0.0:443}
java.lang.IllegalArgumentException: Negative delay.
        at java.util.Timer.schedule(Timer.java:192)
        at org.eclipse.jetty.util.RolloverFileOutputStream.scheduleNextRollover(RolloverFileOutputStream.java:216)
        at org.eclipse.jetty.util.RolloverFileOutputStream.<init>(RolloverFileOutputStream.java:182)
        at org.eclipse.jetty.server.NCSARequestLog.doStart(NCSARequestLog.java:228)
        at org.eclipse.jetty.server.AsyncNCSARequestLog.doStart(AsyncNCSARequestLog.java:104)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:452)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:419)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.nimblestorage.nsjetty.NsJetty.startServersFromXml(NsJetty.java:158)
        at com.nimblestorage.nsjetty.NsJetty.main(NsJetty.java:124)

The problem looks to be that that RollOverFileOutputStream.toMidnight function figures out what day it is in the local time zone, but then computes the delay based on the timezone passed in. In this case, any time between 17:00 and 24:00 on day x in PDT computes midnight as midnight at the start of day x in GMT, and nextMidnight at midnight on day x+1 in GMT. However, the current System.currentTimeMillis() time is already past midnight on day x+1 in GMT as soon as the time is past 17:00 on day x. Hence, the negative delay in midnight.toInstant().toEpochMilli() - System.currentTimeMillis().

**Comment by KentPeacock** [comment]
Maybe this will fix it:

--- jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java	2017-03-17 09:54:58.000000000 -0700
+++ jetty-util/src/main/java/org/eclipse/jetty/util/RolloverFileOutputStream.java.new	2017-04-26 20:50:19.000000000 -0700
@@ -177,7 +177,7 @@
             
             _rollTask=new RollTask();
 
-            midnight = toMidnight(ZonedDateTime.now(), zone.toZoneId());
+            midnight = toMidnight(ZonedDateTime.now(zone.toZoneId()), zone.toZoneId());
             
             scheduleNextRollover();
         }

**Comment by gregw** [comment]
@KentPeacock  thanks
@joakime Can you double check this.  I made the change suggested, but I also put in a safety while loop to ensure midnight is in the future.   I also changed a few private methods to have now passed in as taking multiple samples of now can be a race if midnight occurs between the two samples.

**Comment by joakime** [comment]
@KentPeacock what version of Jetty?

The scheduling in this class was broken in Jetty 9.4.0 thru 9.4.3 and a negative schedule was very possible to occur.

Jetty 9.4.4 has it fixed

**Comment by joakime** [comment]
Decided to check this out with the codebase as it exists in 9.4.4 ...

( you can also find this code at https://gist.github.com/joakime/492d50ca247b99c4cbb153126a29a521 )

``` java
package time;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalAccessor;
import java.util.TimeZone;

public class MidnightBug
{
    public static void main(String[] args)
    {
        // Get Los_Angeles TimeZone (aka PST)
        // This is a zone, and it has no care about daylights savings.
        // Daylights savings is calculated based on a specific point in time.
        // This varies from zone to zone, and time to time in that zone, and even
        // what the year is within that specific zone (as zone offsets change
        // year to year)
        ZoneId zonePST = toZoneId("America/Los_Angeles");
        ZoneId zoneGMT = toZoneId("GMT");
        
        // Lets get a ZonedDateTime for the local system time
        ZonedDateTime localSystemClockNow = toClock("2017 April 27 - 20:00:00", zonePST);
        ZonedDateTime localGmtClockNow = toClock("2017 April 27 - 20:00:00", zoneGMT);
        System.out.printf("local zoned clock (now): %s%n", toString(localSystemClockNow));
        System.out.printf("local zoned clock (gmt): %s%n", toString(localGmtClockNow));
        long currentSystemMillis = localSystemClockNow.toInstant().toEpochMilli();
        System.out.printf("local system epoch (now): %,d ms%n", currentSystemMillis);
        
        // Grab midnight of this day
        ZonedDateTime localClockMidnight = toMidnight(localGmtClockNow, zonePST); // Suggested Wrong calculation
        // ZonedDateTime localClockMidnight = toMidnight(localSystemClockNow, zonePST); // Suggested Change
        System.out.printf("local zoned midnight (today): %s%n", toString(localClockMidnight));
        System.out.printf("local system midnight epoch (today): %,d ms%n", localClockMidnight.toInstant().toEpochMilli());
        
        // Calculate midnight of next day from now
        ZonedDateTime nextClockMidnight = nextMidnight(localClockMidnight);
        System.out.printf("local zoned next midnight (tomm): %s%n", toString(nextClockMidnight));
        System.out.printf("local system next midnight epoch (tomm): %,d ms%n", nextClockMidnight.toInstant().toEpochMilli());
        
        // Calculate schedule duration (in millis)
        long scheduleMillis = nextClockMidnight.toInstant().toEpochMilli() - currentSystemMillis;
        System.out.printf("Scheduled millis: %,d ms%n", scheduleMillis);
    }
    
    private static ZonedDateTime toClock(String timendate, ZoneId zone)
    {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy MMMM d - k:mm:ss")
                .withZone(zone);
        return ZonedDateTime.parse(timendate, formatter);
    }
    
    private static String toString(TemporalAccessor date)
    {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd / kk:mm:ss.S z");
        return formatter.format(date);
    }
    
    private static ZoneId toZoneId(String zoneName)
    {
        ZoneId zoneId = TimeZone.getTimeZone(zoneName).toZoneId();
        System.out.printf(".toZoneId(\"%s\") = [id=%s,normalized=%s,rules=%s]%n", zoneName, zoneId.getId(), zoneId.normalized(), zoneId.getRules());
        return zoneId;
    }
    
    public static ZonedDateTime toMidnight(ZonedDateTime dateTime, ZoneId zone)
    {
        return dateTime.toLocalDate().atStartOfDay(zone);
    }
    
    public static ZonedDateTime nextMidnight(ZonedDateTime dateTime)
    {
        // Increment to next day, based on Configured TimeZone, then find start of that day.
        // Will always be in the future, even if the Daylights Savings Time kicks in during
        // the calculation.
        return dateTime.toLocalDate().plus(1, ChronoUnit.DAYS).atStartOfDay(dateTime.getZone());
    }
}
```

The output of this ...

```
.toZoneId("America/Los_Angeles") = [id=America/Los_Angeles,normalized=America/Los_Angeles,rules=ZoneRules[currentStandardOffset=-08:00]]
.toZoneId("GMT") = [id=GMT,normalized=Z,rules=ZoneRules[currentStandardOffset=Z]]
local zoned clock (now): 2017-04-27 / 20:00:00.0 PDT
local zoned clock (gmt): 2017-04-27 / 20:00:00.0 GMT
local system epoch (now): 1,493,348,400,000 ms
local zoned midnight (today): 2017-04-27 / 24:00:00.0 PDT
local system midnight epoch (today): 1,493,276,400,000 ms
local zoned next midnight (tomm): 2017-04-28 / 24:00:00.0 PDT
local system next midnight epoch (tomm): 1,493,362,800,000 ms
Scheduled millis: 14,400,000 ms
```

The above codebase simulates the bad `ZonedDateTime.now()` (zone-less, aka GMT+0) and shows a transition of ...

```
local zoned clock (gmt): 2017-04-27 / 20:00:00.0 GMT
local zoned midnight (today): 2017-04-27 / 24:00:00.0 PDT
local zoned next midnight (tomm): 2017-04-28 / 24:00:00.0 PDT
```

That is the proper transition, and the times/dates are correct for "start of day".

If we take `2017-04-27 / 24:00:00.0 PDT` and wait 1 minute it becomes `2017-04-27 / 24:01:00.0 PDT`
If we take `2017-04-27 / 24:00:00.0 PDT` and wait 2 hours it becomes `2017-04-27 / 02:00:00.0 PDT`

The action performed in `toMidnight(ZonedDateTime dateTime, ZoneId zone)` always performs the calculation correctly to the timezone "start of day" belongs in, even if the `dateTime` is in a different `TimeZone`, it does not matter.

While it is more correct to use the zoneId, as we have it, and the `java.time` API supports it, there is no bug present in the 9.4.4 codebase, and your proposed change does not alter the behavior.

**Comment by joakime** [comment]
Updated the change to be simpler, with included documentation, and a testcase for this specific scenario.

**Comment by KentPeacock** [comment]
This is in 9.4.3.

**Comment by joakime** [comment]
Yes, 9.4.3 had bugs in RolloverFileOutputStream, fixed in 9.4.4

Here's another demonstration of the `dateTime.toLocalDate().atStartOfDay(zoneDest)` behavior.
As found in `toMidnight(ZonedDateTime dateTime, ZoneId zone)`

``` java
package time;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;
import java.util.TimeZone;

public class ToMidnightDemo
{
    public static void main(String[] args)
    {
        ZoneId zonePST = TimeZone.getTimeZone("America/Los_Angeles").toZoneId();
        testToMidnight(toZonedDateTime("2017 April 27 - 20:00:00 PDT"), zonePST);
        testToMidnight(toZonedDateTime("2017 April 27 - 20:00:00 GMT"), zonePST);
        testToMidnight(ZonedDateTime.now(), zonePST);
    }
    
    private static void testToMidnight(ZonedDateTime dateTime, ZoneId zoneDest)
    {
        ZonedDateTime midnight = dateTime.toLocalDate().atStartOfDay(zoneDest);
        System.out.printf("%s -(midnight)-> %s%n", toString(dateTime), toString(midnight));
    }
    
    private static ZonedDateTime toZonedDateTime(String timendate)
    {
        return ZonedDateTime.parse(timendate, DateTimeFormatter.ofPattern("yyyy MMMM d - k:mm:ss z"));
    }
    
    private static String toString(TemporalAccessor date)
    {
        return DateTimeFormatter.ofPattern("yyyy-MM-dd / kk:mm:ss.S z").format(date);
    }
}
```

results in output ...

```
2017-04-27 / 20:00:00.0 PDT -(midnight)-> 2017-04-27 / 24:00:00.0 PDT
2017-04-27 / 20:00:00.0 GMT -(midnight)-> 2017-04-27 / 24:00:00.0 PDT
2017-04-27 / 08:50:58.8 MST -(midnight)-> 2017-04-27 / 24:00:00.0 PDT
```

**Comment by KentPeacock** [comment]
This doesn't replicate the situation where the logTimeZone is GMT, while the local zone is PST. In that case, the call to testToMidnight should have zoneGMT as the zoneDest argument, which would give:

2017-04-27 / 20:00:00.0 PDT -(midnight)-> 2017-04-27 / 24:00:00.0 GMT

I looked at the diffs between 9.4.3 and 9.4.4, and I don't think this problem is fixed in 9.4.4.

(I've worked around it in my code by making sure that logTimeZone is the same as the getDefault TZ.)

**Comment by gregw** [comment]
@joakime i preferred the version that passed the now time into the various methods.   Generally it is bad form to grab multiple samples of now, because significant changes may happen between samples.  Even if you are sure it can't happen, let's just follow best practise.

It also makes it possible to test for different values of now, which is impossible if methods grab their own sample of now from the clock.

**Comment by KentPeacock** [comment]
This is in 9.4.3.
