### ISSUE TITLE
More flexible cookie domain

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#151]
migrated from Bugzilla [#441026](https://bugs.eclipse.org/bugs/show_bug.cgi?id=441026)
status ASSIGNED severity *enhancement* in component *server* for *9.2.x*
Reported in version *9.2.2* on platform *Macintosh*
Assigned to: Project Inbox

On 2014-08-02 10:10:40 -0400, Laurent D wrote:

> From what I understand this is the current behavior of jetty:
> - by default cookie domain is not set,
> - the cookie domain can be set to a static value through `org.eclipse.jetty.servlet.SessionDomain` property (or programmatically with SessionManager.getSessionCookieConfig().setDomain()).
> 
> It would be nice to have more choice/flexibility on it. For instance a website with different domains and subdomains may want to set the cookie domain differently depending on the domain requested.
> Example:
> - request to `foo.example.com` will get a session cookie domain set to `.example.com`,
> - same for a request to `bar.example.com`,
> - and a request to `www.example.org` will get `.example.org`.
> 
> I haven't found any way so far to do that in jetty.

On 2014-08-06 19:12:43 -0400, Jan Bartel wrote:

> Laurent,
> 
> How about using virtual hosts to deploy different instances of the same webapp so that you can configure the cookie domains appropriately?  See http://www.eclipse.org/jetty/documentation/current/configuring-virtual-hosts.html
> 
> Jan

On 2014-08-09 17:06:05 -0400, Laurent D wrote:

> Hi Jan,
> 
> Thanks for the idea. I'm embedding jetty in my application, so if I understand correctly, for handling *.example.com and *.foobar.com I would have to create two SessionHandler (one for each cookie domain) and then two ServletContextHandler (one for each SessionHandler) each of them configured with the appropriate virtual hosts, right?
> 
> The other solution I found so far was to extend the AbstractSessionManager and manage to get the Request passed to getSessionCookieâ¦ but this requires to rewrite also a bit of the Request class. Quite messy hack.
> 
> Just tried your idea as I was writing thisâ¦ it seems to work, thanks. The only drawback now is that the application has to be aware of the domain names instead of performing some generic operation (setting the cookie domain based on the request).
> 
> Thanks again.
> 
> Laurent.

**Comment by joakime** [comment]
Laurent seems to indicate that Jan's solution works.
Closing
