### ISSUE TITLE
Review JmxIT test

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1522]
@joakime the `JmxIT` does not make any sense to me.

It looks up for MBeans that are never registered, it runs integrations tests even when the tests are skipped, and contains too much magic in assumption of things that should be there but are not.

Can we just remove it ?

**Comment by gregw** [comment]
I think we still need a test to check that MBeans are being registered for the container and potentially from within the webapp.   So I  don't know much about this test, but I do know we need a JmxIT test.  Even if it is just a simple check of 1 MBean.
