### ISSUE TITLE
Update ALPN support for Java 8u131

### ISSUE THREAD

**Issue by barrycaceres** [eclipse/jetty.project#1523]
I am going through Jetty documentation and one of the early instructions is to add both https and http2 support to my JETTY_BASE.  When I try to add http2 support the following happens:

Command Line 1> cd $JETTY_BASE
Command Line 2> java -jar $JETTY_HOME/start.jar —add-to-start=http2

java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_131.mod
at org.eclipse.jetty.start.Modules.registerModule(Modules.java:200)
at org.eclipse.jetty.start.Modules.enable(Modules.java:352)
at org.eclipse.jetty.start.Modules.enable(Modules.java:357)
at org.eclipse.jetty.start.Modules.enable(Modules.java:374)
at org.eclipse.jetty.start.Modules.enable(Modules.java:284)
at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:129)
at org.eclipse.jetty.start.Main.start(Main.java:435)
at org.eclipse.jetty.start.Main.main(Main.java:79)

Command Line 3>

-----------
NOTE: There is no such file "modules/alpn-impl/alpn-1.8.0_131.mod".  I could only find "modules/alpn-impl/alpn-1.8.0_121.mod"

**Comment by joakime** [comment]
Your JDK is too new for that jetty-distribution.
The alpn-boot jar and associated module have no JDK 1.8_131 release version (yet)

**Comment by barrycaceres** [comment]
I was just wondering that….I will downgrade.

The webpage says “Latest (JDK 8+)” so I thought I would be fine.

Thanks.

-Barry

**Comment by gregw** [comment]
You can try copying `modules/alpn-impl/alpn-1.8.0_121.mod` to `modules/alpn-impl/alpn-1.8.0_131.mod`.  If nothing has changed in the JVM in the TLS implementation, then this should work.

Note that with java 9, we will have an ALPN solution that does not need this kind of change per each JVM version.

**Comment by barrycaceres** [comment]
@gregw Good to know -- thanks -- I will give that a try before downgrading JDK
