### ISSUE TITLE
MongoSessionDataStore old session scavenging is broken due to the missing $ sign in "and" operation

### ISSUE THREAD

**Issue by umutuzgur** [eclipse/jetty.project#1526]
It is fixed with the PR #1525 but I don't have the ECA file and I'm too lazy to sign up and get the file. Sorry for my laziness :)

**Comment by janbartel** [comment]
@umutuzgur ok, as its a small change, I'll just put in the missing $ sign myself and commit.  If you come up with some more fixes, then it would be great if you would sign up the Eclipse agreement so we could accept your PRs ;)
