### ISSUE TITLE
Missing 9.4.5 release in http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/

### ISSUE THREAD

**Issue by akurtakov** [eclipse/jetty.project#1529]

**Comment by WalkerWatch** [comment]
We are aware that 9.4.5 and 9.3.19 are not yet available and are working on resolving this.

**Comment by jmcc0nn3ll** [comment]
Publishing the p2 repository is a temperamental process and we are having a permissions issues with the build.  I opened the following issue in eclipse bugzilla.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=516124

**Comment by WalkerWatch** [comment]
This has resolved and the 9.4.5 and 9.3.19 repositories are available.
