### ISSUE TITLE
Jetty deletes logs every day

### ISSUE THREAD

**Issue by Eleeist** [eclipse/jetty.project#1535]
I have a fresh install of Jetty 9.4.4.v20170414. I enabled logging with:

`java -jar start.jar --add-to-start=console-capture`
and configured its settings in start.ini. `java -jar start.jar --list-config` gives this output:

`...`
`jetty.console-capture.append = true`
`jetty.console-capture.dir = logs`
`jetty.console-capture.retainDays = 90`
`...`

When jetty starts it creates log file in logs directory, it works just fine.

But the file is gone the next day and no new file for following day is created.

When I was using 9.3.x, every day jetty just created another file to log into.

**Comment by WalkerWatch** [comment]
As @joakime mentioned on your post on StackOverflow, this has been fixed in Jetty 9.4.5, which was released this week.
