### ISSUE TITLE
Jetty BOM should include more artifacts

### ISSUE THREAD

**Issue by gjdev** [eclipse/jetty.project#1536]
The jetty bom is missing:

- all artifacts from the org.eclipse.jetty.http2 group
- jetty-alpn-server
- alpn-api

**Comment by joakime** [comment]
alpn and consequently http2 are JVM specific in versioning.

**Comment by joakime** [comment]
To support this properly, the jetty-bom would need to have a profile section for each supported JVM.
However, profiles are not resolved within dependencies.

There is also no negative profile option (meaning, if the jvm doesn't match a declared profile, then fail, or use a default profile that causes a failure)

**Comment by gjdev** [comment]
AFAIK only the alpn-boot artifact has jvm specific versioning (and I therefore did not suggest to add that).

I don't see why the suggested artifacts are not in the BOM. I basically had to create my own BOM, importing the jetty one, then adding dependencyManagement for all the http2 stuff, pinning it to the same jetty version.

**Comment by joakime** [comment]
@gjdev would recommend not using `jetty-bom` for your situation, use a simple project property instead.  The jetty-bom provides only 1 thing, a version.
All artifacts in the jetty-bom are on the same version, always will be.

**Comment by joakime** [comment]
The whole "missing artifacts" or "include more artifacts" rationale in jetty-bom is a never ending slope.

What about jetty-schemas?
jetty-test-helper? if so, under what scope?
the various `<classifier>tests</classifier>` artifacts in active use by other projects?
asm minimum requirements cannot go below a specific version of asm with a specific version of jetty? do we care?
slf4j minimum requirements part of jetty-util optional dependencies? i can see a good argument here easily.
google-cloud requirements about 20 optional components part of jetty-google-cloud-* artifacts?  not very useful unless you declare more stuff, be careful of the scopes!
memcached requirements for jetty-memcached?
forked apache jasper needed for jsp layers? not on same coordinate space as normal apache jasper, no automatic conflict resolution here.
Do we stop at just what jetty-distribution has? or jetty-home? or embedded-jetty? or what's useful for a an http client project? or a websocket client project?
What about those using any of the alternate maven coordinates for servlet-api, jsp-api, jstl-api, jsp-impl, jstl-impl? (most of these are on multiple alternate maven coordinates)  Should we specify all of those as dependencyManagement entries too?
What about those using alternate ssl layers? such as what's found in grpc? or bouncycastle? suddenly you have a conflict with jetty-bom that cannot be resolved as long as jetty-bom is being used along with a jetty component.
What about those using cdi/weld and the myriad of optional dependencies? suddenly they have more work to use jetty-bom then to use a more traditional maven setup. 
What about those not using maven to build (gradle, ivy, buildr, sbt), but still use the global central repository system?  this jetty-bom is useless to them (we have 3 reported users of jetty-bom successfully, about 30 unsuccessfully.  this does not bode well for jetty-bom)
What about those that have server at one version, but client at a different version? (this is rather common, no jetty-bom for you)
The man hours spent troubleshooting issues with jetty-bom (in our builds, and others) are getting ridiculous.

**Comment by gregw** [comment]
@joakime I'm sensing you don't like the concept of a bom?

I have to say I'm struggling to really see the value, but I think I get it after reading many times - essentially it gives the ability to add a fixed version of the project to the dependencyManagement section of a project without necessarily depending on every component. 

However I'm thinking that we'd best generate it by processing the output of dependency:tree plugin and merging with specific sections on our parent pom.

**Comment by sbordet** [comment]
+1 for automatic generation, as nobody will ever remember to update the bom module in case a module is added or removed.

**Comment by jmcc0nn3ll** [comment]
I also don't think we need to care too much about the various sections in this pom, license, etc...it is just dependencyManagement, it doesn't actually add in any artifacts to build that the users don't add themselves and _those_ artifacts have the necessary goop declared.

**Comment by joakime** [comment]
alpn-api is a stand alone release, not part of the normal jetty release process, it will not be included in the jetty-bom.

only artifacts that belong to the same jetty release version are included in the jetty-bom, all other dependencies are outside the scope of jetty-bom.

**Comment by joakime** [comment]
Also note, since these are just `<dependencyManagement>` entries, the build will not fail if there is something amiss in the jetty-bom.  Wrong entries, non-existent entries, etc will not fail the build.
