### ISSUE TITLE
WebSocket : Network failure not detected

### ISSUE THREAD

**Issue by iamjamalkhan** [eclipse/jetty.project#1537]
Hi ,

I am using Jetty 9.2.4 and on Network failures I have Observed couple of issues

1. onClose/OnError is not triggered.
2. Even setting the idleTimeout does not work as expected. It should basically timeout if there is no interaction from client side, but I don't see any timeout.
3. After this the outgoing queue of socket for that client never de-queues resulting in out of memory exception.
4. The server does not serve any new WebSocket connection, handshake timeout.

**Comment by joakime** [comment]
Seems like a duplicate of Issue #1534

**Comment by joakime** [comment]
Current HEAD in jetty-9.4.x seems to behave properly.
A variety of connection issues now have tests to prove out the behavior.
