### ISSUE TITLE
JarFileResource mishandles paths with spaces

### ISSUE THREAD

**Issue by gthelleloid** [eclipse/jetty.project#1539]
Jetty 9.4.0.v20161208 will fail to serve any resource with a space in its name that is located in a jar file (more generally, any resource with a character in its name encoded by URIUtil.encodePath(String)). The problem arises in three steps:

1. JarFileResource.addPath(String) (implemented in URLResource) encodes the path using URIUtils.encodePath(String). This causes a JarFileResource to be created with a (jar) url string in which the path is encoded.
2. JarFileResource.newConnection() extracts the encoded path from the jar url string and assigns it to the _path field.
3. JarFileResource.exists() uses the value of _path as the argument to JarFile.getJarEntry(String). This fails to find the resource because JarFile.getJarEntry(String) requires the unencoded path.

I have attached a zip file with three files:

1. test.jar, which contains two files named "file1" and "file 2" (note the space in the filename).
2. JarFileWithSpaceTest.java, which shows that a Jetty server serving test.jar does not serve "file 2" successfully.
3. JarFileWithSpaceTest2.java, which shows more directly that JarFileResource says that "file 2" does not exist even though it does.

The Java files were both compiled and run with a classpath including javax.servlet-api-3.1.0.jar, jetty-http-9.4.0.v20161208.jar, jetty-io-9.4.0.v20161208.jar, jetty-server-9.4.0.v20161208.jar, and jetty-util-9.4.0.v20161208.jar. (I apologize if a Maven project would have been preferable.)

It appears to me that the solution may be as simple as changing the path assignment line in JarFileResource.newConnection() from 

`_path=_urlString.substring(sep+2);`

to

`_path=URIUtil.decodePath(_urlString.substring(sep+2));`

but perhaps I am missing something.

Due to the pervasive use of static Resource.newResource() methods to create JarResource and JarFileResource instances, the best workaround I have is to create a "fixed" version of JarFileResource that correctly decodes the path, create a subclass of JarResource that returns instances of the "fixed" JarFileResource subclass from addPath(String), and always explicitly instantiate JarResources in my code instead of letting Jetty classes do it (e.g., as done in the ResourceCollection(String[]) constructor).

[test.zip](https://github.com/eclipse/jetty.project/files/988547/test.zip)

**Comment by gregw** [comment]
reproduced in a unit test.  Looking for a fix...

**Comment by gregw** [comment]
@gthelleloid Your proposed fix appears to be good... but I'm struggling to find a specification that tells me exactly how the contents of a jar files should be formatted and encoded.
