### ISSUE TITLE
Inconsistencies in Shutdown with Jetty Runner

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1550]
While preparing documentation for #1549 I noticed that the shutdown methodology for the Jetty distribution and jetty-runner conflict. That is, the way by which you define the stop port and stop key is different for both, which is a bit confusing. An example:

Starting with an instance of Jetty-runner, I start up my server and define `--stop-key` and `--stop-port`:

`> java -jar jetty-runner-9.4.5.v20170502.jar my.jar --stop-key dog --stop-port 8181`

Now, if I want to stop it I need to navigate to a distribution and stop it from there, except that `--stop-key` and `--stop-port` are not valid for `start.jar` (though [the documentation states](https://www.eclipse.org/jetty/documentation/current/runner.html#jetty-runner) otherwise). `start.jar` does not parse spaces (or so it seems) so instead I have to do the following:

`> java -jar start.jar -DSTOP.PORT=8181 -DSTOP.KEY=dog --stop`

The issue here then is two-fold. The documentation is currently incorrect (though maybe was correct at some point) in it's instructions for how to stop runner, at least using the distribution. Secondly, the method by which stop port and stop key is defined is divergent between runner and the distribution. Runner is not meant for production, obviously, but the two should have a common ground.

After talking this over with @joakime, I think the best solution is to make `--stop-key=` and `stop-port=` valid in both jetty-runner and `start.jar` (the addition of the = sign is a bit cleaner).

**Comment by janbartel** [comment]
@WalkerWatch  I'd do it the other way around: keep the jetty distro behaviour of STOP.PORT and STOP.KEY and make the jetty-runner obey both those and the --stop-key and --stop-port args.

**Comment by WalkerWatch** [comment]
@janbartel I have no strong preference so long as there is parity, but preferred the streamlined <parameter>=<value> for ease of use. Putting a space in feels uncomfortable and is in contrast to most other command line options we use in Jetty.

**Comment by olamy** [comment]
@WalkerWatch is it ```-STOP.KEY=dog ``` or ```-DSTOP.KEY=dog ```

**Comment by WalkerWatch** [comment]
@olamy It is `-DSTOP.KEY=`. I've updated my original commentary above to reflect this and add a few other thoughts.
