### ISSUE TITLE
DefaultAnnotationProcessor.fallbackToManualAnnotatedClasses: Unable to detect annotations. Application may fail to deploy

### ISSUE THREAD

**Issue by gcamargoboj** [eclipse/jetty.project#1559]

**Comment by janbartel** [comment]
DefaultAnnotationProcessor is not a jetty class. Perhaps you have raised this issue on jetty by mistake? If not, please reopen and explain exactly how it relates to jetty, providing stacktraces, your version of jetty, and any jetty config files.
