### ISSUE TITLE
SSE client disconnect causes automatic reconnection on clients behalf by server after org.eclipse.jetty.io.EofException

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#156]
migrated from Bugzilla [#443729](https://bugs.eclipse.org/bugs/show_bug.cgi?id=443729)
status ASSIGNED severity _normal_ in component _server_ for _9.2.x_
Reported in version _9.1.5_ on platform _PC_
Assigned to: Greg Wilkins

On 2014-09-10 11:48:30 -0400, Jessica Viles wrote:

> Using Jersey Restful Web Service library to create web service application servlet that is deployed on Jetty server.
> 
> Every time a restful client abruptly disconnects open SSE stream (by closing browser, curl command window, java application rest client, etc).  Jetty server prints stack trace and attempts to re-open the SSE stream connection for the client.  We substituted servers from Jetty to the Jersey Grizzly web server and the issue went away.
> 
> Do you know of a work around which will help us to prevent Jetty server from outputting stack trace on abrupt client disconnect, and prevent it from automatically reconnecting on client's behalf (which when the browser is closed, etc, is unnecessary and causes unnecessary traffic to our web servlet). 
> 
> Stack trace:
> 
> Sep 10, 2014 8:40:42 AM org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
> SEVERE: Error while committing the output stream.
> org.eclipse.jetty.io.EofException
>   at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:188)
>   at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:335)
>   at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:125)
>   at org.eclipse.jetty.server.HttpConnection$ContentCallback.process(HttpConnection.java:682)
>   at org.eclipse.jetty.util.IteratingCallback.processIterations(IteratingCallback.java:166)
>   at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:126)
>   at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:303)
>   at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:720)
>   at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:751)
>   at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:128)
>   at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:122)
>   at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:201)
>   at org.glassfish.jersey.message.internal.CommittingOutputStream.flush(CommittingOutputStream.java:292)
>   at org.glassfish.jersey.message.internal.OutboundMessageContext.commitStream(OutboundMessageContext.java:813)
>   at org.glassfish.jersey.server.ContainerResponse.commitStream(ContainerResponse.java:393)
>   at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:612)
>   at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:378)
>   at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:368)
>   at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:262)
>   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
>   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
>   at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>   at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>   at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
>   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
>   at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
>   at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
>   at org.glassfish.jersey.jetty.JettyHttpContainer.handle(JettyHttpContainer.java:192)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>   at org.eclipse.jetty.server.Server.handleAsync(Server.java:516)
>   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:288)
>   at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:237)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
>   at java.lang.Thread.run(Thread.java:722)
> Caused by: java.nio.channels.ClosedChannelException
>   at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:251)
>   at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:440)
>   at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:167)
>   ... 34 more

On 2014-10-30 14:14:49 -0400, Jessica Viles wrote:

> Only seems to happen when running out of Eclipse IDE, not when running in JVM.  
> 
> Using Eclipse IDE version:  Version: Kepler Service Release 2
> Build id: 20140224-0627

**Comment by gregw** [comment]
too old; wont fix
