### ISSUE TITLE
Jetty: Unknown SSL protocol error in latest IBM Java 1.7 version [1.7.0.sr9.30 and above, 1.7.1.sr3.30 and above]

### ISSUE THREAD

**Issue by selva3k** [eclipse/jetty.project#1564]
Hi,

This is the continuation of the issue "https://github.com/eclipse/jetty.project/issues/1547"
I could not able to reopen the issue, hence I have opened this defect. I have given below the summary in short description.

Description: Jetty 9 version lesser than 9.3 (I used 9.2.16) does not work with latest IBM releases (IBM Java 1.7)

Here is the continuation of the jetty defect id (1547)

Thanks for the response. I tested this and TLSv1.1 / TLS1.2 is not enabled in older versions of IBM Java as well. I noticed that SSLv3 is enabled in older versions, which are not enabled in latest versions

Older version of IBM Java 1.7

SSLEngine.supported = [SSLv3, TLSv1, TLSv1.1, TLSv1.2]
 SSLEngine.enabled = [SSLv3, TLSv1]

Latest version of IBM Java 1.7

SSLEngine.supported = [TLSv1, TLSv1.1, TLSv1.2]
 SSLEngine.enabled = [TLSv1]

I noticed that IBM Java disabled MD5 from the below version onwards only
 IBM Java 1.7 version [1.7.0.sr9.30 and above, 1.7.1.sr3.30 and above]

I suspect that SSL handshake is failing due to the MD5 disablement in IBM Java. From this Java version onwards only, Jetty is not working.

 In few places still Jetty code uses "javax.net.ssl.X509TrustManager" instead of "javax.net.ssl.X509ExtendedTrustManager". Is it possible to get the Jetty debug bits by changing the trust manager to "javax.net.ssl.X509ExtendedTrustManager"

**Comment by sbordet** [comment]
Let's continue on #1547.
