### ISSUE TITLE
ServletUpgradeRequest mangles query strings containing percent-escapes by re-escaping them

### ISSUE THREAD

**Issue by Zalathar** [eclipse/jetty.project#1568]
(version 9.4.5)

When a ServletUpgradeRequest instance is created, it creates a request URI by passing each of its URL components into one of URI's multi-argument constructors.

However, if the request's query string contains percent-escaped characters, then the URI constructor will double-escape those percent-escape sequences by replacing `%` with `%25`. This ends up confusing any server-side code that was expecting to receive the actual query string sent by the client.

For example, this request URL:

```
wss://example.net/service?param=BL%26T
```

ends up being changed to:

```
wss://example.net/service?param=BL%2526T
```

### Expected behaviour

ServletUpgradeRequest should create its URI instance in a way that preserves the raw percent-escapes present in the received query string, instead of re-escaping them.

**Comment by gregw** [comment]
Correct.  URI.getPath() is decoded, while URI.getQuery() is not.  
The solution is not to simply decode the value from getQueryString() as it may include characters like & and =, which will then be wrongly handled.   A different URI constructor needs to be used.

**Comment by joakime** [comment]
Fixed in commit 296050d

**Comment by Zalathar** [comment]
It looks like the new version will now decode any existing `%26` or `%3d` sequences into `&` or `=` respectively, which changes the meaning of the query string.

For example, this query string:

```
breakfast=bacon%26eggs&2*2%3d5=false
```

will appear in the URI (via URI#getRawQuery) as

```
breakfast=bacon&eggs&2*2=5=false
```

which changes how the query parameters will be parsed.

(This applies to code that tries to extract the query string by calling URI#getRawQuery. Code that calls ServletUpgradeRequest#getQueryString will see the original query string, but it's surprising that the two give different results.)

**Comment by gregw** [comment]
@joakime I think the `ServletUpgradeRequest` code is best done in Strings rather than URIs.  There is a lot of parsing and decoding/encoding going on in your version.   I think somethink like below should do:
```
    public ServletUpgradeRequest(HttpServletRequest httpRequest) throws URISyntaxException
    {
        this.queryString = httpRequest.getQueryString();
        this.secure = httpRequest.isSecure();

        StringBuffer uri = httpRequest.getRequestURL();
        if (this.queryString!=null)
            uri.append("?").append(this.queryString);
        uri.replace(0,uri.indexOf(":"),secure ? "wss" : "ws");        
        this.requestURI = new URI(uri.toString());
        this.request = new UpgradeHttpServletRequest(httpRequest);
    }
```

However, I think there is something wrong in the test harness as the query string is arriving as if the results of URI.getQuery() have been sent rather than URI.getRawQuery().  Not familiar with the setup so don't initially know where to look...

**Comment by gregw** [comment]
@joakime Ah I see that WSURI#toHttp is using the multipart URI constructor - which is basically fatally flawed it does not allow proper handling of query strings with quoted special characters.  Again I think the solution is to do the URI manipulations as Strings and only create the URI at the very end.

I think we need to track down all usages of the multi arg constructor for URI and fix.

**Comment by gregw** [comment]
Blah `URI` is a really confused class - even URI.getRawSchemeSpecificPart() is returning the partially decoded query string!  That's probably a JVM bug I think!  anyway will avoid using it at all!

**Comment by gregw** [comment]
@joakime I've pushed my fix, but I've not rigorously checked for similar problems, nor alternative uses of the same code.   So will leave this issue open for now.

I definitely think we need to check for and avoid URI where possible.  

I'll research `URI.getRawSchemeSpecificPart()` to see if that really is a JVM bug.

**Comment by gregw** [comment]
Ha I definitely think there is a JVM bug!   The following test fails
```
    @Test 
    public void testRawURI() throws Exception
    {
        URI base = new URI("http://auth/");
        
        URI uri = base.resolve("/path?easy=encoded%20value&hard=encoded%26value");
        assertThat(uri.toString(),is("http://auth/path?easy=encoded%20value&hard=encoded%26value"));
        assertThat(uri.getRawQuery(),is("easy=encoded%20value&hard=encoded%26value"));
        
        // This fails on JDK 1.8.0_121
        assertThat(uri.getRawSchemeSpecificPart(),is("//auth/path?easy=encoded%20value&hard=encoded%26value"));
    }
```

**Comment by gregw** [comment]
For the record, the JVM bug report was accepted: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8181074

**Comment by joakime** [comment]
I'm considering this complete. closing.
