### ISSUE TITLE
Allow setting of maxBinaryMessageSize to 0 in WebSocketPolicy

### ISSUE THREAD

**Issue by alex-rufous** [eclipse/jetty.project#1569]
The existing implementation of WebSocketPolicy#setMaxBinaryMessageSize(int) restricts settings of maxBinaryMessageSize to positive integers. It seems Jetty internally supports unconstrained maxBinaryMessageSize (if set to 0). The only way to set it to 0 is to use reflection. Would it be possible to relax the constraint in setter and allow '0'?

**Comment by joakime** [comment]
Setting the maxBinaryMessageSize at 0 would mean you never send a binary message payload (no length).
Jetty has traditionally not support unconstrained whole binary messages delivery.
It only supports unconstrained binary messages via the streaming APIs.
Internally, the maximum whole message size (or individual frame payload size) is [Integer.MAX_VALUE](http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#MAX_VALUE).

This is well below what the WebSocket protocol is capable of handling at the frame level.
But if you are attempting to set this for the frame level, know that efforts underway with WebSocket over HTTP2 will likely make the websocket frame maximum conform to the HTTP2 frame maximum (65k IIRC)
Also, with websocket extensions in play, the frame level maximums can also be constrained to small values.

Know that there are 2 values when using the Jetty Native WebSocket API (message and buffer), but only 1 value when using JSR356 WebSocket API (buffer).

I'll relax the message size limit checks, but not the buffer size limits.

Know that you are opening yourself to many different classes of OutOfMemory errors if you do this.
It would be trivially easy for a websocket client to crash your server with a single short message with this kind of configuration.

**Comment by joakime** [comment]
Change applied.

But I would encourage you to either use the streaming APIs or set the max message size to something reasonable.
