### ISSUE TITLE
JSR356 Encoder duplicate results in exception stating "Duplicate decoder for type:"

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#157]
migrated from Bugzilla [#444308](https://bugs.eclipse.org/bugs/show_bug.cgi?id=444308)
status ASSIGNED severity _normal_ in component _websocket_ for _9.2.x_
Reported in version _9.2.3_ on platform _All_
Assigned to: Joakim Erdfelt

On 2014-09-16 16:55:51 -0400, Joakim Erdfelt wrote:

> The exception message for duplicate encoder says "decoder", this is a typo that should be fixed.

**Comment by joakime** [comment]
The work being done in Bug #207 will fix this starting in Jetty 9.4.x+
