### ISSUE TITLE
Expose actual (TCP) client address

### ISSUE THREAD

**Issue by jkrems** [eclipse/jetty.project#1573]
Afaict there is no reliable way to retrieve the remote address of the immediate client right now. All code paths that *might* be returning the remote address in some scenarios, return random data if the client sends an `X-Forwarded-For` header. If the clients sends `X-Forwarded-For: I$love%20paris`, jetty will happily return something like `I$love%20paris:56084` as the remote address.

Would it be acceptable to expose the actual/TCP remote address in some way? Maybe as an attribute..? If so: are there any preference for the naming?

P.S.: I looked at various options but I couldn't find one that didn't require using jetty-specific types like `HttpChannel`. But the project I'm working on shouldn't depend on jetty being on the classpath since it's a generic servlet filter.

**Comment by joakime** [comment]
Only the `ForwardRequestCustomizer` uses or sets the `X-Forwarded-For` headers to update the `HttpServletRequest.getRemoteAddr()`.

If you have nothing in front of Jetty, then remove the `ForwardRequestCustomizer` and use the raw remote address found during socket accept.

**Comment by joakime** [comment]
If you need the `ForwardRequestCustomizer` and have something in front of Jetty, consider using [RFC7239](https://tools.ietf.org/html/rfc7239) exclusively on your proxy/load balancer/hardware/software that sits in front of Jetty.

You might also want to consider updating proxy/load balancer/hardware/software to reject the `Forwarded` header provided by the client and overwriting it with the real Proxy network information instead.
