### ISSUE TITLE
Client resets stream, pending server data is failed, write hangs

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#158]
migrated from Bugzilla [#444485](https://bugs.eclipse.org/bugs/show_bug.cgi?id=444485)
status ASSIGNED severity _normal_ in component _http2_ for _9.2.x_
Reported in version _9.3.0_ on platform _PC_
Assigned to: Greg Wilkins

On 2014-09-18 10:17:46 -0400, Simone Bordet wrote:

> When a client resets a stream while the server is sending data, then frames queued by the server are failed and discarded.
> 
> Currently, when a frame is discarded for this reason, it may trigger the call of a blocking API such as AsyncContext.complete(), which tries to call ServletOutputStream.close(), also a blocking API.
> When this happens, we may hang with this stack:
> 
> HTTP2Flusher.process()
>   DataFrameEntry.reset()
>     Callback.failed()
>       AsyncContext.complete()
>         HttpOutput.close()
>           HTTP2Flusher.append()
>           HTTP2Flusher.iterate()
>           block
> 
> Since close() is blocking, process() cannot proceed and dequeue the frame that has just been appended to call its callback, and thus the hang.

On 2014-09-18 10:35:51 -0400, Simone Bordet wrote:

> Commit SHA: bfda3620f3a7500f7999eccaf2bb384d3605a7b6.
> 
> Fixed by ensuring that when a failure happens, either by catching an exception or by failing a callback, we always call completed() and abort the channel (via new method terminate()).
> 
> Greg, this needs review for the following cases: an application calls write(), a frame is queued, the stream is reset, then the application calls one of HttpOutput.sendXXX() methods.
> Other blocking methods such as close(), flush(), write() have a state machine that is checked and, for example, if the stream is closed they throw an exception.
> I think a similar state machine should be implemented for sendXXX() methods as well.

**Comment by sbordet** [comment]
@gregw see my last comment.
