### ISSUE TITLE
why do rest webservice path params should be double quoted while sending rest request using rest clients?is it limitation

### ISSUE THREAD

**Issue by satishsutar** [eclipse/jetty.project#1582]
Hi Jetty Team,

I am working on rest web service project deployed on JettyServer programatically. The problem which i am facing is path parameters in rest service path needs to be double quoted to access the service. If path parameters are not double quoted the rest server does not respond gives 500 http error. 

http://localhost:8080/restservice/api/employees/"empname"
above this url GET request works

But below one does not work
http://localhost:8080/restservice/api/employees/empname

empname should be double quoted get server response. if not double quoted it responds with http 500 error code.

Can you please let me know the way to avoid these double quotes. Is it limitation in jetty server. As i have seen above url with no double quotes for path parameter works in  apache tomcat server.

Regards,
Satish

**Comment by joakime** [comment]
Not enough information to help you.
The quotes have nothing to with any spec.
The 500 error should tell you a stacktrace, what does it look like?
What rest service?
How do you have it configured?
Do you have a demonstration project?

**Comment by jmcc0nn3ll** [comment]
on the server object there is a method called something like
setDumpOnStart(true) that you want to call once you are all wired as you
think you should be

that will print out to logging the actual configuration, I suspect things
are not configured as you think they are configured

cheers,
Jesse

--
jesse mcconnell
jesse.mcconnell@gmail.com

**Comment by satishsutar** [comment]
sorry its not 500 http error code... its 404
when i try to hit below restservice GET request url on chrome browser where satish is path parameter without double quoted gives below error response.
http://localhost:8080/restservice/api/employees/satish


erst webservice has been defined as below restController class as below
@Path("/")
@Controller
public class RestController{
@GET
@Path("/restservice/api/employees/{employeeName})
@Produces(MediaType.APPLICATION_JSON)
public Response getEmployeeByName(
@PathParam("employeeName") final String employeeName,
			@Context HttpHeaders headers){
             System.out.println("Received request for ="+employeeName);
           //logic to build response
return response;
}
}
HTTP ERROR: 404

Problem accessing /rdwservice/api/attributes/FEED_MASTER. Reason:

Not Found
Powered by Jetty://

Assume this simple restwebservice deployed on jetty server java class process. using below apis to programatically configure jettyserver and deploy restservice on top of it.

import org.eclipse.jetty.annotations.ServletContainerInitializersStarter;
import org.eclipse.jetty.apache.jsp.JettyJasperInitializer;
import org.eclipse.jetty.http.HttpVersion;
import org.eclipse.jetty.plus.annotation.ContainerInitializer;
import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.server.HttpConnectionFactory;
import org.eclipse.jetty.server.SecureRequestCustomizer;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.SslConnectionFactory;
import org.eclipse.jetty.server.handler.ContextHandler;
import org.eclipse.jetty.server.handler.ContextHandlerCollection;
import org.eclipse.jetty.server.handler.ResourceHandler;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.eclipse.jetty.util.ssl.SslContextFactory;
import org.eclipse.jetty.webapp.WebAppContext;


There is no stacktrace on server side... Tried to check if this request went to server or no using filter... 
above request hits server but no response only 404 error code ...

**Comment by joakime** [comment]
After turning on java formatting for your code, it's apparent that you have an invalid class declaration.

Your `@Path` declaration has no closing double quote.

**Comment by satishsutar** [comment]
Assume it has closing double quote... code is working perfectly. with http://localhost:8080/restservice/api/employees/"satish"  for this reqiuuest
but fails for http://localhost:8080/restservice/api/employees/satish
@Path("/")
@Controller
public class RestController{
@GET
@Path("/restservice/api/employees/{employeeName}")
@Produces(MediaType.APPLICATION_JSON)
public Response getEmployeeByName(
@PathParam("employeeName") final String employeeName,
			@Context HttpHeaders headers){
             System.out.println("Received request for ="+employeeName);
           //logic to build response
return response;
}
}

**Comment by joakime** [comment]
This seems like a problem with your rest service of choice. (either a bug, or a bad configuration)

The `@Path("/restservice/api/employees/{employeeName}")` is not a feature of the servlet spec, the support for `@Path` annotation and path parameter declarations is not the responsibility of Jetty, these features would be provided by the Rest implementation you are using.

It seems like the Rest Implementation is not parsing the Servlet spec `request.pathInfo` properly to find the path parameter for you.
Would suggest filing a issue with the rest service implementation bug tracker, or their equivalent stackoverflow.com tag.
