### ISSUE TITLE
Donate jetty-hazelcast to hazelcast project

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1585]
In light of the work done in Issue #1571 and the comments from the hazelcast team at https://twitter.com/olamy/status/870140237590089728

It appears that the hazelcast project is keen on having the work donated back to hazelcast for them to manage.

Having this reside at hazelcast seems ideal.

**Comment by gregw** [comment]
Having it reside at hazelcast may not be as ideal as having it at jetty.   If it is at jetty we can just enable it with a module.

Alternately, the impl can be at hazelcast but we have a module in jetty that will download and enable it

**Comment by olamy** [comment]
Sounds good to have at least module metadata part of the distro to ease users life.
@emre-aydin what do you think? I can made a pull request to your code.

**Comment by olamy** [comment]
well finally the code will be hosted in jetty source repo.
So we can close it?

**Comment by olamy** [comment]
@joakime  can be closed?
