### ISSUE TITLE
JSR369 adjustments to PushBuilder

### ISSUE THREAD

**Issue by klopfdreh** [eclipse/jetty.project#1586]
Hi,

just wanted to let you know that the method getPushBuilder of the HttpServletRequest has been renamed to newPushBuilder and a new version of the spec has been released

See:
* https://github.com/javaee/servlet-spec/releases

kind regards

Tobias

**Comment by klopfdreh** [comment]
I just renamed the issue to be more general, because I didn't had the time to sync the current implementation with the spec to point out the exact changes. Hope it is only the renaming of the method.

Anyway thanks for the fast response.

**Comment by sbordet** [comment]
@klopfdreh Servlet 4 will be implemented in Jetty 10, and AFAICT the method is already correctly named `newPushBuilder` there (branch `master`).

What code are you looking at, exactly ?

**Comment by klopfdreh** [comment]
@sbordet for wicket-examples we are using 9.4.5.v20170502 and PushBuilder is there available, too.

https://github.com/apache/wicket/blob/master/wicket-experimental/wicket-http2/wicket-http2-jetty/src/main/java/org/apache/wicket/http2/markup/head/Jetty9PushBuilder.java#L40

**Comment by gregw** [comment]
note that there are ongoing discussions and renaming of various APIs after the b06 release....  the current master branch of jetty is tracking the staged master of the javax.servlet API

**Comment by klopfdreh** [comment]
Hi @sbordet and @gregw ,

do you plan to also down port the changes if the Servlet API is finished?

I ask because if we use the final method names we have a minimum requirement regarding the server if this feature is used: https://ci.apache.org/projects/wicket/guide/8.x/single.html#_wicket_http_2_support_experimental

thanks a lot for the clarification. 👍

**Comment by gregw** [comment]
By down port, do you mean update the method names in Jetty 9?
I think we can do that, so let's leave this issue open until the 4.0 API is final and then we can update the names in 9 (leaving originals as deprecated).

**Comment by klopfdreh** [comment]
Yes exactly. Thanks a lot! I let the issue open.

**Comment by gregw** [comment]
This has been left open for a while now.  I'm not going to change jetty 9 as the 'getPushBuilder' returns a Jetty API anyway.
Closing!
