### ISSUE TITLE
maven repository doesn't have 9.2.22.v20170531

### ISSUE THREAD

**Issue by giantninja** [eclipse/jetty.project#1589]
Is there any reason why 9.2.22.v20170531 isn't available in the maven repo yet?  Looks like it was released 2 days ago.

**Comment by joakime** [comment]
That is not a release yet.

https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg03016.html

> This is a potential release of the Jetty 9.2.x branch, and exists on a oss.sonatype.org staging repository.
> Pending approval, this specific staged release will be promoted to official and start to show up in the usual places.

In fact, it's going to be dropped for a RolloverFileOutputStream bug, it will never be a release with that specific version id. (it will be a new one)

**Comment by giantninja** [comment]
Ok, cool.  Thanks for clarifying.  I was just going off of the releases page (https://github.com/eclipse/jetty.project/releases)

**Comment by joakime** [comment]
Github has no distinction between release and tag.

A tag is git.  A github release is automatically created from every tag.
A github release can also be manually created.

A staged release, has a tag, and is just a potential release while being tested.
Once its approved, it gets promoted to everywhere (maven central, eclipse downloads, various p2 repositories, docker images, etc ...)

**Comment by giantninja** [comment]
I honestly did not know that, and that explains a lot since I've had this happen before, so thank you for that
