### ISSUE TITLE
Create alias checker to accept paths containing // as alias

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#159]
migrated from Bugzilla [#444701](https://bugs.eclipse.org/bugs/show_bug.cgi?id=444701)
status ASSIGNED severity _normal_ in component _server_ for _9.2.x_
Reported in version _9.2.3_ on platform _All_
Assigned to: Greg Wilkins

On 2014-09-21 22:11:40 -0400, Jan Bartel wrote nothing.

**Comment by gregw** [comment]
handled with rewrite rule and URI normalization
