### ISSUE TITLE
CompressedContentFormat.tagEquals() - incorrect comparison of entity tag hashes

### ISSUE THREAD

**Issue by veselinandreev** [eclipse/jetty.project#1592]
Above mentioned method appears to be doing incorrect comparison of entity tag hashes if browser have sent a compressed variant of same resource. In the below snippet:

        if (etag.equals(tag))
            return true;

        int dashdash = tag.indexOf("--");
        if (dashdash>0)
            return etag.regionMatches(0,tag,0,dashdash-2);
        return false;

indexOf() returns the position at which the text starts and not where it ends. For safety, a length check would be advisable, as otherwise "123" will be matched to "1--". Here's an idea:

		if (etag.equals(tag))
			return true;

		int offset = tag.indexOf("--");
		if (offset > 0 && offset == etag.length())
				return etag.regionMatches(0, tag, 0, offset);

		return false;

Based on the usage of this method, etag variable will never hold a compression suffix, so looking for such might as well be for safety, otherwise it becomes a hidden gem when you swap the arguments upon calling this method.

Kind Regards,
Ves.

**Comment by gregw** [comment]
Thanks - but needed to adjust length for the trailing quote.
