### ISSUE TITLE
Update GZip documentation for removal of deflate in 9.3.x and 9.4.x

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1598]
Deflate is [no longer used in 9.x.x ](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java#L309-L315)and the documentation needs updated to reflect this.

**Comment by joakime** [comment]
The deflate http compression method.

See https://tools.ietf.org/html/rfc1951 (never updated)
and https://en.wikipedia.org/wiki/HTTP_compression
