### ISSUE TITLE
output of start.jar --dry-run is not executable

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#160]
migrated from Bugzilla [#444702](https://bugs.eclipse.org/bugs/show_bug.cgi?id=444702)
status ASSIGNED severity *enhancement* in component *start* for *9.2.x*
Reported in version *9.2.3* on platform *All*
Assigned to: Joakim Erdfelt

On 2014-09-21 22:33:10 -0400, Greg Wilkins wrote:

> the output of --dry-run is not executable directly because:
>  + it contains \CRLF which does not expand correctly
>  + it can contain ${jetty.base}, which is not escaped.
> 
> should be able to do 
> 
>   CMD=$(java -jar start.jar --dry-run)
>   eval $CMD

On 2014-11-05 11:07:40 -0500, Joakim Erdfelt wrote:

> that syntax ...
> 
> CMD=$(java -jar start.jar --dry-run)
> eval $CMD
> 
> ... is shell dependent.
> 
> Making it work for bash wouldn't necessarily mean it would work for zsh or even regular sh. (mainly due to escaping differences)

On 2014-11-05 11:21:36 -0500, Joakim Erdfelt wrote:

> Since eval is a shell command, we would have to pick a shell to support and tweak the output of our --dry-run to suit it best.
> 
> These tweaks should be OS.IS_LINUX specific.
> As other OSs (OSX, Windows) would not benefit from this.
> Also, its hard to detect cygwin from java, so there's no point wasting effort there.
> 
> My vote would be to target bash (versions post 4.3).
> Mainly because we find/use bash for bin/jetty.sh and versions of bash up to 4.3 have shellshock, people shouldn't be using those versions in production anyway.
> 
> It might make more sense to just drop --dry-run and introduce shell specific versions of the same command line.
> 
> --dry-run-bash3 (for cygwin, osx, raspberry pi, and android envs)
> --dry-run-bash4 (for modern linux)
> --dry-run-windows (for windows syntax)

On 2014-11-05 11:23:38 -0500, Joakim Erdfelt wrote:

> or --dry-run=<mode>

On 2014-11-05 11:36:23 -0500, Joakim Erdfelt wrote:

> oh yeah, and we should be aware of command line upper-limits to the produced command line as well, possibly produce an error / System.exit()
> 
> For linux (all flavors), the practical limit is 32,767 arguments. (this is the limit for kernel 2.6 era distributions running 32-bit linux, common among RHEL and cloud providers still)
> 
> For debian, the practical limit is 2,097,152.  (this is the limit seen on old versions of debian running on raspberry pi)
> 
> For OSX (all flavors 10.5+), the practical limit is 262,144 arguments. (this is the OSX 10.5 era, first version with intel)
> 
> For Solaris (9+), the practical limit is 1,048,320 arguments.
> 
> For Windows (XP+), the practical limit is 8,191 characters.
> 
> With this, the logic could be ..
> 
> if(OS.isWindows()) {
>   assertThat(dryRunString.length(), lessThan(8191));
> } else if(OS.isLinux()) {
>   assertThat(cmdLine.size(), lessThan(32767));
> } else if(OS.isUnix()) {
>   assertThat(cmdLine.size(), lessThan(262144));
> }

On 2014-11-05 11:42:54 -0500, Joakim Erdfelt wrote:

> Linking to some interesting discussion on command line length limits on different platforms in the comments on Bug # 327193

On 2014-11-05 17:30:02 -0500, Greg Wilkins wrote:

> 
> I like 
> 
>  --dry-run[=mode]
> 
> with the default being some humanly readable format (ie with the \CRLF line endings).
> 
> 
> So we could do
> 
>   --dry-run         # pretty printed version
>   --dry-run=sh      # generic unix version
>   --dry-run=windows # windows version
>   --dry-run=ibm     # z/OS version
> 
> 
> So we could then do
> 
>   CMD=$(java -jar start.jar --dry-run=sh)
>   eval $CMD

**Comment by joakime** [comment]
The Docker images apparently work with this currently.
Do we need this anymore?
