### ISSUE TITLE
ContainerProvider.getWebSocketContainer() behavior is not to spec

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1605]
Per spec, the default behavior is to always create a new WebSocketContainer on each call to the .getWebSocketContainer() method.

This might be a performance issue though.
See javaee/websocket-spec open issues

* javaee/websocket-spec#184
* javaee/websocket-spec#212
* javaee/websocket-spec#230

**Comment by joakime** [comment]
This regression was introduced in Jetty 9.4.x when the HttpClient support was added.
The behavior in Jetty 9.4.x is that getWebSocketContainer() is now a JVM wide singleton.

**Comment by joakime** [comment]
We could have configurable behavior.

Possible configuration:

* Default per-spec
* Use ServletContext ServerContainer if available
* Use singleton instance.

**Comment by joakime** [comment]
Javadoc says:

> Obtain a new instance of a WebSocketContainer. The method looks for the ContainerProvider implementation class in the order listed in the META-INF/services/javax.websocket.ContainerProvider file, returning the WebSocketContainer implementation from the ContainerProvider implementation that is not null.

http://docs.oracle.com/javaee/7/api/javax/websocket/ContainerProvider.html#getWebSocketContainer--

**Comment by sbordet** [comment]
Please report to cometd/cometd#727 when this is resolved.

**Comment by joakime** [comment]
Default Spec behavior.

New ClientContainer each time.
But with the following shared objects:
* Executor
* ByteBufferPool
* HttpClient (pass in Executor and ByteBufferPool)

**Comment by joakime** [comment]
Initial behavior implemented.

Working on shared object support next.
