### ISSUE TITLE
Add DateHeaderPatternRule for manipulating date headers

### ISSUE THREAD

**Issue by xz64** [eclipse/jetty.project#1607]
This is an enhancement request for a specific type of header pattern rule which would call setDateHeader / addDateHeader on the HttpServletResponse based on some sort of offset from the current system time.

Here is an example of the usage I was thinking of:

```xml
<New id="header" class="org.eclipse.jetty.rewrite.handler.DateHeaderPatternRule">
    <Set name="pattern">*.js</Set>
    <Set name="name">Expires</Set>
    <Set name="offset">31540000000</Set>
</New>
```

Related discussion: [https://stackoverflow.com/questions/12124523/how-to-set-a-dynamic-expires-header-in-jetty](https://stackoverflow.com/questions/12124523/how-to-set-a-dynamic-expires-header-in-jetty)

**Comment by joakime** [comment]
Static file content is served from the DefaultServlet.
It would make more sense to have this kind of configuration present on the DefaultServlet, not a generic non-context rule like that.

**Comment by xz64** [comment]
What do you think of having generic date/string header Filters instead of a config on the DefaultServlet? I could also see a use case for setting headers like Content-Security-Policy / X-Frame-Options.

**Comment by joakime** [comment]
Added to `jetty-9.4.x` as part of PR #1613
