### ISSUE TITLE
Add facility to verify webapp/server classpath sanity

### ISSUE THREAD

**Issue by jjYBdx4IL** [eclipse/jetty.project#1608]
My impression is that a lot of developers and users don't understand or care about the class loading hierarchy involved in web application containers and related servers/parent class loaders. This leads to misleading errors like "class not found" despite the class being clearly on the classpath (one of the lesser evils), to annotations being ignored because Class.isAnnotationPresent() does not match if the argument is a class from a different class loader.

To remedy this to some extent, I suggest adding a "verify webapp classpath" goal to the jetty-maven-plugin. That goal would do something like:

* take classpath locations for server libraries and classes
* take classpath locations for webapp libraries and classes
* use WebAppContext information about system and server classes to issue errors/fail depending on plugin goal configuration, ie. when finding non-server, non-system duplicate classes on both server and webapp classpaths; issue warnings for classes found on the webapp's classpath that are marked as system classes.

It is required that this is part of Jetty because noone else has information about the server/system classes defined in WebAppContext.

Embedded, modified Jetty servers should be supported by this, too, which is easy: let the user point the plugin to the server lib directory or something similar, which then gets scanner recursively for jar and class files. The same functionality should be provided for webapps.

**Comment by joakime** [comment]
We had an old tool for this.

https://github.com/jetty-project/jetty-webapp-verifier

(sadly, It wasn't very popular, and has fallen into disrepair)

Perhaps that should just be revived and cover your use case.

**Comment by joakime** [comment]
Note: server classes and libraries will require knowledge of your `${jetty.base}` configuration, and is not going to be useful analysis point in any build time goal.

A runtime analysis tool, available during actual `${jetty.base}` deployment (using DeploymentManager) is probably the best option, as you have everything you need to perform that analysis at that point (server knowledge and webapp knowledge).

**Comment by jjYBdx4IL** [comment]
Sounds reasonable. Maybe exposed through JMX, which could be used during verify maven phase to check for consistency.
