### ISSUE TITLE
Add support for SessionTrackingMode.SSL

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#161]
migrated from Bugzilla [#445713](https://bugs.eclipse.org/bugs/show_bug.cgi?id=445713)
status ASSIGNED severity _enhancement_ in component _servlet-3.1_ for _9.3.x_
Reported in version _9.2.3_ on platform _Macintosh_
Assigned to: Jan Bartel

On 2014-10-01 15:49:50 -0400, Joakim Erdfelt wrote:

> There appears to be no support for SessionTrackingMode.SSL present in Jetty 9.2
> 
> Example setup in servlet api.
> 
> rivate static final SessionTrackingMode[] modeArray = 
>   { SessionTrackingMode.SSL };
> private static final Set<SessionTrackingMode> SESSION_TRACKING_MODES = 
>   new HashSet<>(Arrays.asList(modeArray));
> 
> @Override
> public void init(ServletConfig config) throws ServletException {
>     super.init(config);
>     config.getServletContext().setSessionTrackingModes(SESSION_TRACKING_MODES);
> }

On 2014-10-08 19:03:00 -0400, Jan Bartel wrote:

> FYI 
> 
> Jetty has never implemented this tracking mode although its been in the servlet spec for many iterations. For now, I'm changing this to an enhancement request. If the issue receives some votes then we can up the priority of implementing this.
> 
> cheers
> Jan

On 2014-10-08 19:30:44 -0400, Joakim Erdfelt wrote:

> This feature request was filed as a result of a request on stackoverflow.
> 
> http://stackoverflow.com/questions/26148432/does-jetty-support-sessiontrackingmode-ssl

**Comment by joakime** [comment]
Closing due to lack of interest.
