### ISSUE TITLE
Jetty-Client: QueuedThreadPool timing out with huge RAM (196 GB or 256 GB)

### ISSUE THREAD

**Issue by omkusre** [eclipse/jetty.project#1610]
Hi Team,

We are using Jetty-Client 9.2.9.v20150224 in our application for hitting HTTP calls. We have used QueuedThreadPool as executor while creating instance for HTTPClient object. Overall, it works ok, however, recently we have seen timeout issues in few customer installations where server had huge RAM configurations. (196 GB or 256 GB RAM). The HTTP logs are consistently getting TimeoutException from the QueuedThreadPool executor. We did not see any traces in Wireshark Logs for these HTTP hits. 

In our internal testing with up to 32 GB RAM configurations, it looks to be working fine without any issues.

We have enabled all DEBUG logs at org.eclipse.jetty package and could get below logs. We have changed the executor to CacheThreadPool provided with Executor Service by Java and it was working properly without any issues in such high RAM configuration. 

**Note:** We are able to replicate this issue with Jetty-Client 9.4.6.v20170531 (Latest version). Hence, even the latest version for Jetty-Client is not working for the QueuedThreadPool and getting TimeoutException, 

Could you please look into it and provide us suggestions why QueuedThreadPool is facing these issues with High RAM configuration environment. 

**Please see the debug logs below:** 

```
2017-05-24 11:13:13.162:DBUG:oejc.HttpClient:main: Created HttpDestination[http://10.4.122.74]@2d6d8735,queue=0,pool=DuplexConnectionPool@67117f44[c=0/2,a=0,i=0]
2017-05-24 11:13:13.167:DBUG:oejc.HttpDestination:main: Queued HttpRequest[GET / HTTP/1.1]@17ed40e0 for HttpDestination[http://10.4.122.74]@2d6d8735,queue=1,pool=DuplexConnectionPool@67117f44[c=0/2,a=0,i=0]
2017-05-24 11:13:13.168:DBUG:oejc.AbstractConnectionPool:main: Connection 1/2 creation
2017-05-24 11:13:13.173:DBUG:oejut.QueuedThreadPool:main: queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$4/1654589030@224aed64
2017-05-24 11:13:20.175:DBUG:oejc.HttpExchange:main: Failed HttpExchange@c39f790 req=COMPLETED/java.util.concurrent.TimeoutException@71e7a66b res=COMPLETED/java.util.concurrent.TimeoutException@71e7a66b: req=true/rsp=true java.util.concurrent.TimeoutException
2017-05-24 11:13:20.175:DBUG:oejc.HttpExchange:main: Aborting while queued HttpExchange@c39f790 req=COMPLETED/java.util.concurrent.TimeoutException@71e7a66b res=COMPLETED/java.util.concurrent.TimeoutException@71e7a66b: java.util.concurrent.TimeoutException
Error sending request java.util.concurrent.TimeoutException
```

Should be

```
2017-05-24 10:40:24.040:DBUG:oejc.HttpDestination:main: Queued HttpRequest[GET / HTTP/1.1]@4ac68d3e for HttpDestination[http://10.4.122.74]@61064425,queue=1,pool=DuplexConnectionPool@136432db[c=0/2,a=0,i=0]
2017-05-24 10:40:24.041:DBUG:oejc.AbstractConnectionPool:main: Connection 1/2 creation
2017-05-24 10:40:24.044:DBUG:oejut.QueuedThreadPool:main: queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$4/1971489295@161cd475
_2017-05-24 10:40:24.044:DBUG:oejut.QueuedThreadPool:qtp793589513-13: run org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$4/1971489295@161cd475
2017-05-24 10:40:24.046:DBUG:oeju.SocketAddressResolver:qtp793589513-13: Resolved 10.4.122.74 in 0 ms
2017-05-24 10:40:24.048:DBUG:oeji.ManagedSelector:qtp793589513-13: Queued change org.eclipse.jetty.io.ManagedSelector$Connect@43fb8c2d on org.eclipse.jetty.io.ManagedSelector@73a8dfcc id=0 keys=0 selected=0
2017-05-24 10:40:24.049:DBUG:oejut.QueuedThreadPool:qtp793589513-13: ran org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$4/1971489295@161cd475
2017-05-24 10:40:24.049:DBUG:oeji.ManagedSelector:qtp793589513-12: Selector loop woken up from select, 0/0 selected
2017-05-24 10:40:24.049:DBUG:oeji.ManagedSelector:qtp793589513-12: Running action org.eclipse.jetty.io.ManagedSelector$Connect@43fb8c2d
2017-05-24 10:40:24.049:DBUG:oeji.ManagedSelector:qtp793589513-12: Selector loop waiting on select
2017-05-24 10:40:25.113:DBUG:oeji.ManagedSelector:qtp793589513-12: Selector loop woken up from select, 1/1 selected_
```

The lines in _ITALICS_ are all run inside a qtpXXXXXXX-XX thread that doesn't seem to wake up high RAM configuration server. 

**Machine Configuration:**
**OS:** Microsoft Windows Server 2012 R2 Standard
**RAM:** 256 GB
**Processor(s):**              
2 Processor(s) Installed.
       [01]: Intel64 Family 6 Model 62 Stepping 4 GenuineIel ~1197 Mhz
       [02]: Intel64 Family 6 Model 62 Stepping 4 GenuineIel ~1197 Mhz

**HTTPClient Initialization/Invocation:** 

```       
        HttpClient client = new HttpClient();
        client.setExecutor(new QueuedThreadPool(10));
        client.setIdleTimeout(5000);
        client.setMaxConnectionsPerDestination(2);
        client.setConnectTimeout(5000);
        client.start();
        Request request = client.newRequest("http://10.4.122.74/")
				.method(HttpMethod.GET);
        request.timeout(7000, TimeUnit.MILLISECONDS);
        content = request.send();
```

**Comment by joakime** [comment]
What version of Java?
What are the JVM command line options when you are running this instance?
Does running the same configuration with a lower JVM memory setting make it work reliably?

**Comment by joakime** [comment]
Getting access to a machine that has this kind of memory configuration will take some time.
When you ran with the 64GB configuration, how quickly did this issue arise?
What are you doing on that machine, and in HttpClient that can trigger this?
Do you have a test case that can replicate this scenario?

**Comment by sbordet** [comment]
It appears that the DNS task that has been submitted to the thread pool never runs.

This can happen if the thread pool ran out of threads.

Can you please take a JVM thread dump when this happens, and possibly also a server dump ?
See http://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html.

**Comment by omkusre** [comment]
Hi joakime,
Thanks for your responses. Here are our inputs on the questions you have asked. 

**What version of Java?**
- Java 1.8 (jdk1.8.0_121)

**What are the JVM command line options when you are running this instance?**
- We have launched a test jar with POM.xml having below dependencies.
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlets</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-proxy</artifactId>
        </dependency>
    </dependencies>
The jar is run with below command line parameter: 
java -jar JettyTestApp-with-dependencies.jar 

**Does running the same configuration with a lower JVM memory setting make it work reliably?**
- The issue is observed only with High RAM configuration machines (196 GB and 256 GB RAM). We have tested same setup in 32 GB/16 GB RAM machine and it was working fine. 

Getting access to a machine that has this kind of memory configuration will take some time.
**When you ran with the 64GB configuration, how quickly did this issue arise?**
- As mentioned earlier, setups with 32 GB RAM and 16 GB RAM machines are working ok. We do not have any 64 GB RAM machine to try out. This issue was observed in few customer side installations where RAM was 256 GB and 196 GB. This was reproducible consistently on the client machine.
We have tried to reproduce the same with 256 GB VM, however, we could not reproduce the issue on the VM. Hence, we have now asked for physical machine with 256 GB RAM and see if it reproduces the issue. 


**What are you doing on that machine, and in HttpClient that can trigger this?**
As mentioned in the issue, we are hitting a simple GET call for a IP Address with URL as http://10.4.122.74/. This URL is accessible from all browsers i.e. Chrome/Firefox/IE on the same machine where jetty is placed and renders the HTML page properly. 
 
**Do you have a test case that can replicate this scenario?**
We have only seen this issue on few client machines with 256 GB / 196 GB RAM configuration. However, we are not yet able to replicate the same on VM with same configuration. We have requested for physical server machine with same configuration and will see if it replicates the issue. 
Hence, at the moment, steps to replicate issues are: 
1. Get a physical server with 256 GB RAM and processors as mentioned in the issue. Use Windows server 2012 R2 standard on the machine.
2. Create a test jetty client with latest jetty version Jar. Please use QueuedThreadPool as executor. 
3. Hit a GET call to any HTTP URL and see if it returns response back. Check logs and see if we can see the timeout issue as mentioned above.

**Comment by omkusre** [comment]
@sbordet : Thanks for your reply. Here are our input on your questions.

**Can you please take a JVM thread dump when this happens, and possibly also a server dump ?
See http://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html.**

- We will check if we can update jetty.xml from customer machine and get the thread dump from the same. 

So as I understood, we need to update Jetty.xml as below. Could you please confirm this, so that we can check with customer if they can provide same.

    <?xml version="1.0"?>
    <!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN" "http://jetty.mortbay.org/configure.dtd">

      <Configure class="org.eclipse.jetty.server.Server">

	**<Set name="ThreadPool">
		 
		 <New class="org.eclipse.jetty.util.thread.QueuedThreadPool">
		   <Set name="minThreads">10</Set>
		   <Set name="maxThreads">200</Set>
		   <Set name="detailedDump">true</Set>
		 </New>
	</Set>**
	
    
    
    
    
    

    
    <Call name="addConnector">
        <Arg>
            <New class="org.eclipse.jetty.server.nio.SelectChannelConnector">
                <Set name="host">
                    <Property name="jetty.host" />
                </Set>
                <Set name="port">
                    <Property name="jetty.port" default="8181" />
                </Set>
                <Set name="maxIdleTime">300000</Set>
                <Set name="Acceptors">2</Set>
                <Set name="statsOn">false</Set>
                <Set name="confidentialPort">8443</Set>
                <Set name="lowResourcesConnections">20000</Set>
                <Set name="lowResourcesMaxIdleTime">5000</Set>
				**<Set name="dumpAfterStart">true</Set>
				<Set name="dumpBeforeStop">true</Set>**
            </New>
        </Arg>
    </Call>

    
    
    
    
    
    
    
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">karaf</Set>
                <Set name="loginModuleName">karaf</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">default</Set>
                <Set name="loginModuleName">karaf</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>

</Configure>

**Comment by sbordet** [comment]
You got the configuration wrong, as `org.eclipse.jetty.server.nio.SelectChannelConnector` is a Jetty 8 class, not Jetty 9.2.x like you said you're using.

By the way, we recommend to upgrade to Jetty 9.4.x if you can.

Taking a JVM thread dump and server dump is something that you have to do when the issue presents itself, it's not something that you can obtain via configuration.

I don't think the issue has something to do with the amount of RAM, probably just running out of threads due to blocked threads, but this can be known only by providing a JVM thread dump and server dump.

**Comment by omkusre** [comment]
@sbordet : We have tried with jetty-client 9.4.x in the test jar we had tried on customer machine. However, it was not working and getting timeout exception. 

We are working with customer if we can get thread-dump and server dump. We will get back to you with this soon.

**Comment by sbordet** [comment]
jetty-client 9.4.x does work, you have a different problem if it times out. Anyway, waiting for your dumps.

**Comment by omkusre** [comment]
@sbordet : We luckily had threadpool captured fro our last debug session with customer. Please find it attached. This thread pool is captured using below Java code. Please let us know if this can be useful.


    public static void crunchifyGenerateThreadDump()
    {
        final ThreadMXBean threadMXBean = ManagementFactory.getThreadMXBean();
        final ThreadInfo[] threadInfos = threadMXBean.getThreadInfo(threadMXBean.getAllThreadIds(), 100);
        for (ThreadInfo threadInfo : threadInfos)
        {
            System.out.println('"');
            System.out.println(threadInfo.getThreadName());
            System.out.println("\" ");
            final Thread.State state = threadInfo.getThreadState();
            System.out.println("\n   java.lang.Thread.State: ");
            System.out.println(state);
            final StackTraceElement[] stackTraceElements = threadInfo.getStackTrace();
            for (final StackTraceElement stackTraceElement : stackTraceElements)
            {
                System.out.println("\n        at ");
                System.out.println(stackTraceElement);
            }
            System.out.println("\n\n");
        }
    }


[ThreadPool.txt](https://github.com/eclipse/jetty.project/files/1074224/ThreadPool.txt)

**Comment by sbordet** [comment]
I don't understand ? This is a Jetty 9.4.x thread dump, not 9.2.x.

**Comment by sbordet** [comment]
There are 3 pools, and almost all of them have threads that are waiting to select, for a total of 35 (!).

One of the pools is configured with a `SynchronousQueue`, which is typically not the right queue for a thread pool.

I don't think you need 35 selectors, so you have a configuration problem on your side. I would recommend to leave everything at default for Jetty and avoid weird configurations with the thread pools.

**Comment by omkusre** [comment]
Sorry If I have confused you. Our application is using 9.2.9 version. However, to debug at customer site, We have wrote standalone class to run using latest Jetty version as below. and got thread pool dump as shared above. 

I am re-attaching all the details from the standalone class which is using below version:
[ThreadPoolDump.txt](https://github.com/eclipse/jetty.project/files/1074303/ThreadPoolDump.txt)

**Jetty Version:**
version=9.4.5.v20170502
groupId=org.eclipse.jetty
artifactId=jetty-client

**These are the logs generated from that java file:**
Creating request OK
Send request 2017-05-24 13:38:29.265:DBUG:oejuc.ContainerLifeCycle:main: org.eclipse.jetty.client.HttpClient@5a01ccaa added {HttpDestination[http://10.4.122.74]@6108b2d7,queue=0,pool=null,MANAGED}
2017-05-24 13:38:29.265:DBUG:oejuc.AbstractLifeCycle:main: starting HttpDestination[http://10.4.122.74]@6108b2d7,queue=0,pool=null
2017-05-24 13:38:29.265:DBUG:oejuc.ContainerLifeCycle:main: HttpDestination[http://10.4.122.74]@6108b2d7,queue=0,pool=DuplexConnectionPool@1554909b[c=0/2,a=0,i=0] added {DuplexConnectionPool@1554909b[c=0/2,a=0,i=0],POJO}
2017-05-24 13:38:29.265:DBUG:oejuc.AbstractLifeCycle:main: STARTED @7561ms HttpDestination[http://10.4.122.74]@6108b2d7,queue=0,pool=DuplexConnectionPool@1554909b[c=0/2,a=0,i=0]
2017-05-24 13:38:29.265:DBUG:oejc.HttpClient:main: Created HttpDestination[http://10.4.122.74]@6108b2d7,queue=0,pool=DuplexConnectionPool@1554909b[c=0/2,a=0,i=0]
2017-05-24 13:38:29.265:DBUG:oejc.HttpDestination:main: Queued HttpRequest[GET / HTTP/1.1]@6bf256fa for HttpDestination[http://10.4.122.74]@6108b2d7,queue=1,pool=DuplexConnectionPool@1554909b[c=0/2,a=0,i=0]
2017-05-24 13:38:29.266:DBUG:oejc.AbstractConnectionPool:main: Connection 1/2 creation
2017-05-24 13:38:36.267:DBUG:oejc.HttpExchange:main: Failed HttpExchange@6cd8737 req=COMPLETED/java.util.concurrent.TimeoutException@22f71333 res=COMPLETED/java.util.concurrent.TimeoutException@22f71333: req=true/rsp=true java.util.concurrent.TimeoutException
2017-05-24 13:38:36.267:DBUG:oejc.HttpExchange:main: Aborting while queued HttpExchange@6cd8737 req=COMPLETED/java.util.concurrent.TimeoutException@22f71333 res=COMPLETED/java.util.concurrent.TimeoutException@22f71333: java.util.concurrent.TimeoutException
Error sending request java.util.concurrent.TimeoutException

**Code:** 
        **testJettyRequest("10.4.122.74", new QueuedThreadPool(10));**

 public static void testJettyRequest(String ipaddress, Executor executorService)
    {
        System.setProperty("org.eclipse.jetty.LEVEL", "ALL");
		System.out.println("Logger : " +System.getProperty("org.eclipse.jetty.LEVEL"));
        HttpClient client = new HttpClient();
        client.setExecutor(executorService);
        client.setIdleTimeout(2000);
        client.setMaxConnectionsPerDestination(2);
        client.setConnectTimeout(2000);
        System.out.print("Creating client ");
        try
        {
            client.start();
            System.out.println("OK");
        }
        catch (Throwable tr)
        {
            System.out.println("Error while starting client " + tr);
        }
        Request request = null;
        System.out.print("Creating request ");
        try
        {
            request = client.newRequest("http://" + ipaddress + "/").method(HttpMethod.GET);
            request.timeout(7000, TimeUnit.MILLISECONDS);
            System.out.println("OK");
        }
        catch (Throwable tr)
        {
            System.out.println("Error creating request " + tr);
        }
        ContentResponse content = null;
        System.out.print("Send request ");
        try
        {
            content = request.send();
            System.out.println("OK");
            System.out.println("Content: " + content.getContentAsString());
        }
        catch (Throwable tr)
        {
            System.out.println("Error sending request " + tr);
        }
    }

**Comment by omkusre** [comment]
@sbordet : Hi, Good Morning. Do you have any update on this? Please let me know if any additional information is required from our side.

**Comment by sbordet** [comment]
Does it work if you configure the `QueuedThreadPool` with 100 threads ?

**Comment by omkusre** [comment]
@sbordet : No, we have not tried to increase thread pool size and won't be able to try that until we get a local setup to reproduce the issue. However, we have verified same with threapool size as 10 on 16GB and 32GB RAM machines and it was working fine. It was giving TimeoutException only for 196 GB and 256 GB RAM machines which customer has. 

Also, we had sent a single HTTP request through above standalone class. Hence, I assume thread pool with 10 threads should be good enough.

**Comment by sbordet** [comment]
`HttpClient` configures the number of selectors based on the number of cores, by default `cores/2`.
If you hard code your thread pool at 10 threads, it may work on smaller machines because you have for example 8 cores, and so 6 threads will be available to process requests.

If the machines with more RAM have a larger number of cores, say 24, then all threads in the pool will be dedicated to selectors, and none will be available for processing requests.

**Comment by omkusre** [comment]
@sbordet : Good point. So this means, if I launch a VM with more than 20 cores, I should be able to replicate the issue. or If i just reduce number of threads as 2-3 on Octa core VM, this issue should get replicated. Is it correct understanding?

**Comment by omkusre** [comment]
@sbordet : I have tried on a VM with 10 cores, for threadpool size with 3, 4 and 5 it was getting timeout. However, for Threadpool size as 6, I got the response back properly. Looks like, we have got the root cause. 

Thank you very much for assisting us in seeking the root cause.

**Comment by jmcc0nn3ll** [comment]
Just a note that commercial production support in available through webtide.com as well.
