### ISSUE TITLE
AbstractNCSARequestLog does not extract the user from the http header when it has not been authenticated

### ISSUE THREAD

**Issue by mat013** [eclipse/jetty.project#1614]
We are running spring boot and jetty, and we are using NCSARequestLog. The authentication in spring boot seems to be at a later stage and therefore the request has not been authenticated. 

But should it not be possible to extract the userid from the Authorization in the http header then?

At the moment that is not possible in the AbstractNCSARequestLog

**Comment by joakime** [comment]
The logging in RequestLog occurs after the response has been sent.  
Well after anything in Spring Boot.

Can you give us an example application that has the behavior you are reporting?

**Comment by mat013** [comment]
I have created an example at [jetty-1614](https://github.com/mat013/jetty-1614)

You will need an active directory server and this can be configured in application.yml

The issue is that when I log on the service the access log looks as follows:

0:0:0:0:0:0:0:1 - - [14/Jun/2017:20:05:37 +0000] "GET /portfolio HTTP/1.1" 401 345 
0:0:0:0:0:0:0:1 - - [14/Jun/2017:20:05:42 +0000] "GET /portfolio HTTP/1.1" 200 7 
 
Instead of the second dash I would have expected my user id to appear

the issue is that in the log method on the class org.eclipse.jetty.server.AbstractNCSARequestLog in line
line 130 is null and therefore no userid can be logged.

            Authentication authentication = request.getAuthentication();
            append(buf,(authentication instanceof Authentication.User)?((Authentication.User)authentication).getUserIdentity().getUserPrincipal().getName():null);

But if I debug the application I can see that the http header contains Authorization and it should be possible to extract the userId (for basic auth it should be trivial)

I have implemented a proposal in the class com.domain.jetty.AbstractNCSARequestLog that would solve the issue.
