### ISSUE TITLE
Password defaults in jetty-ssl-context.xml should be removed

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1615]
Currently the [etc/jetty-ssl-context.xml](https://github.com/eclipse/jetty.project/blob/jetty-9.4.6.v20170531/jetty-server/src/main/config/etc/jetty-ssl-context.xml) has defaults for some of the passwords for the keystore.

There should be no password defaults.

Also, the SslContextFactory should produce meaningful errors if the passwords are invalid/incorrect.

**Comment by gregw** [comment]
Note that we want the demo keystore to work without the user needing to
edit files.  Perhaps move passwords and keystore file itself to a testssl
module?

**Comment by gregw** [comment]
@WalkerWatch Can you check these changes and update doco?

**Comment by WalkerWatch** [comment]
@gregw Sure thing. I will make sure to include as well as part of #1677

**Comment by WalkerWatch** [comment]
@gregw From a feature standpoint this looks good and it works. If you want to go ahead and merge it, thatd be great. I will make sure it ends up documented.

**Comment by lachlan-roberts** [comment]
We now have the `test-keystore` module for Jetty 10 and the default passwords have been removed elsewhere.

Leaving open issue #4228 for the documentation of this change.
