### ISSUE TITLE
AsyncContext.dispatch() does not use raw/encoded URI

### ISSUE THREAD

**Issue by rstoyanchev** [eclipse/jetty.project#1618]
The Servlet spec says this about the parameter-less dispatch:

> If the AsyncContext was initialized via the startAsync(ServletRequest, ServletResponse) and the request passed is an instance of HttpServletRequest , then the dispatch is to the URI returned by HttpServletRequest.getRequestURI()

Yet given a URL with an encoded slash:
`/foo/vv%2F1234/add/2` 

The dispatch ends up going to:
`/foo/vv/1234/add/2`

**Comment by joakime** [comment]
What version of Jetty?

**Comment by rstoyanchev** [comment]
Sorry this is on 9.4.6.v20170531.

**Comment by yairogen** [comment]
@joakime any idea when we can expect a fix for this?

**Comment by joakime** [comment]
@gregw added a unit test in commit 59e919b to attempt to verify this bug (currently set to @Ignore for you to investigate).

The output is inconsistent, and hints at a bug, but I also know that the Servlet spec is very particular on what should be encoded versus something that shouldn't be encoded.

Anyway, here's the output from the updated test, hopefully it can shed some light on the behavior.

```
doGet:getServletPath:/test2
doGet:getRequestURI:/ctx/test2/something%2felse
doGet:getRequestURL:http://localhost/ctx/test2/something%2felse
doGet:getPathInfo:/something/else
doGet:async:getServletPath:/test2
doGet:async:getRequestURI:/ctx/test2/something%2felse
doGet:async:getRequestURL:http://localhost/ctx/test2/something%2felse
doGet:async:getPathInfo:/something/else
async:run:attr:servletPath:/test
async:run:attr:pathInfo:/hello/there
async:run:attr:queryString:dispatch=true
async:run:attr:contextPath:/ctx
async:run:attr:requestURI:/ctx/test/hello%2fthere
```

**Comment by joakime** [comment]
So far, the only encoding inconsistency that this test shows is in the `HttpServletRequest.getPathInfo()`, not the Request URI or Request URL as the OP for this issue has reported.

Note: the javadoc for `getPathInfo()` reports that the value return is decoded, so that isn't a bug, just a behavior nuance of the Servlet spec.

http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getPathInfo--

**Comment by joakime** [comment]
Updated unit test expectations on `getPathInfo()` in light of the official javadoc, test passes now.

@rstoyanchev there is no bug we can reproduce.

Do you have a specific scenario where you can replicate this?

**Comment by rstoyanchev** [comment]
@joakime I can provide a sample but let me see if this clarifies it.

I'm not saying `getPathInfo()` works incorrectly. The scenarios is quite simple -- a call to `request.startAsync(request, response)` followed by a call to `asyncContext.dispatch()` at some point later on. The dispatch should go to the encoded path via `requestURI` and that's not what I'm observing.

**Comment by joakime** [comment]
Lets see if I can distill what you are saying ...

* A `FooServlet` on url-pattern `/foo/*`
* A `VvServlet` on url-pattern `/foo/vv/*`
* A request to `/foo/blah` is processed by `FooServlet`.
* `FooServlet` performs an AsyncContext dispatch to `/foo/vv%2F1234/add/2` which you expect to hit `FooServlet` again, but instead hits `VvServlet`?

Is this right?

**Comment by rstoyanchev** [comment]
This is a Spring Boot app:

- `DispatcherServlet` is mapped to `"/*"`
- request is to `/foo/vv%2F1234/add/2`
- starts async and performs `dispatch()`
- that should go to the requestURI as the quote from the spec says

**Comment by joakime** [comment]
The `DispatcherServlet` mapped to `/*` means that everything not matching other more specific Servlet mappings will get that request.
Do you have any other Servlets mapped to other url-patterns?

You should dump the server (or the specific WebAppContext) after startup and see what's active.
See http://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html

**Comment by rstoyanchev** [comment]
Sorry but I'm really not following your questions. Yes DispatcherServlet is mapped to everything and there is no other Servlets. Isn't it how all web frameworks work?

Let me put together a basic sample..

**Comment by rstoyanchev** [comment]
Here it is.. https://github.com/rstoyanchev/jetty-issue-1618/tree/master

**Comment by joakime** [comment]
No, most web frameworks do not work that way.

The minute you setup a scenario like that, you are no longer using the Servlet spec to delineate your specific behaviors, its all controlled in your DispatcherServlet.  You essentially have 1 servlet, not even an error handler, no static resource handling, etc.

It can be a very inefficient setup (eg: you are not using most of the performance enhancements that Jetty provides this way).

**Comment by rstoyanchev** [comment]
Hm, we're off topic here but most web frameworks do use the front controller pattern with a single Servlet serving as the gateway with higher level features such request mappings as a feature of the web framework. The "/*" mapping may seem odd but many application don't want extra an extra prefix enforced on every URL. As for static resources requests can still be forwarded to the default Servlet but Spring MVC for example provides more advanced static resource handling features. I don't see how any of this is outside the Servlet spec.

**Comment by joakime** [comment]
So here's what happening ...

The use of `request.startAsync(request, response)` is rebuilding the URI from the constituent parts (using standard servlet spec techniques)

``` java
String requestURI = request.getServletPath() + request.getPathInfo();
```

Since you declared your url-pattern mapping as `/*` the request looks like this ...

```
request.getRequestURI = "/foo/vv%2F1234/add/2"
request.getRequestURL = "http://localhost:9999/foo/vv%2F1234/add/2"
request.getContextPath = ""
request.getServletPath = ""
request.getPathInfo = "/foo/vv/1234/add/2"
```

Now, the behavior you are seeing is due to this use of the `startAsync(ServletRequest, ServletResponse)`, which is beholden to rebuild the URL from the provided information in the 2 objects handed it.

If you use the parameterless `startAsync()` then the original URL/URI is used.

The spec, isn't very clear here on proper behavior (nor are the tests).
The behavior is following the original pre-Servlet 3.0 behavior with regards to rebuilding a URL/URI from the parts provided in the `ServletRequest` object (which could be a wrapped object).

You might be tempted to say that we should rebuild from the `getRequestURI()` or `getRequestURL()`, stripping off the contextPath and servletPath to provide dispatch to the appropriate place.

But that's not practical in the spec, as the decoding/normalizing is something that is done outside of / before the context that is being served.   I wanted to link to the jsr369-experts@servlet-spec.java.net archive about this specific topic, but now that java.net is closed, i cannot find the archives.

Either way, I think @gregw, our resident servlet-spec guru, is going to need to chime in here.

**Comment by joakime** [comment]
@gregw new testcase `testDispatchAsyncContext_SelfEncodedUrl()` added which replicates this reported behavior.  It is currently set to `@Ignore` (to let you work on the issue when you get back)

**Comment by joakime** [comment]
@gregw This is the relevant line where the reported behavior manifests...

https://github.com/eclipse/jetty.project/blob/jetty-9.4.6.v20170531/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2261

**Comment by rstoyanchev** [comment]
The spec seems pretty clear to me. The following (in chapter 2 above code example 2-1):

> public void dispatch() - Provided as a convenience to dispatch the request
and response used to initialize the AsyncContext as follows. If the
AsyncContext was initialized via the startAsync(ServletRequest,
ServletResponse) and the request passed is an instance of
HttpServletRequest , then the dispatch is to the URI returned by
HttpServletRequest.getRequestURI() .

**Comment by joakime** [comment]
Not that straight forward.  The spec list had a conversation about this topic.

Some examples:
* A wrapped ServletRequest can change the getRequestURI() to be outside of the same ServletContext that started the Async (which is a violation of the dispatch)
* The original request can have a confusing path (you have a context on "/foo" and another on "/bar", a request arrives with URI path of "/foo/../bar/nut".  which one do you send the request to? its not what you think.)

**Comment by joakime** [comment]
@gregw note, this issue is similar to #911

**Comment by gregw** [comment]
As @rstoyanchev says, the spec is pretty clear here.  But the problem is that it can be very difficult to strip off the context path from an encoded URI, specially of the context path itself can be encoded!

But as the spec is clear, I guess we have to do that hard work.

**Comment by gregw** [comment]
So I have committed a partial fix, which works so long as the context path itself is not encoded.  @rstoyanchev can you verify this works in your springboot env before I put the effort in to handle the very very rare encoded context path situation

**Comment by rstoyanchev** [comment]
@gregw I can confirm the fix works in my own sample, which is a Boot app and I have also [asked the original reporter|https://jira.spring.io/browse/SPR-15652?focusedCommentId=152490&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-152490] to confirm in their actual application just in case.  Thanks!

**Comment by igreenfield** [comment]
@gregw @rstoyanchev I check this snapshot on my full server and it works! When can we get a release? it is very urgent for us.

**Comment by gregw** [comment]
Typically we release every month or two, but currently don't have a release cycle planned for the next few weeks. So I would expect a release in about 3 to 5 weeks.

Note that as part of our commercial support services, we can schedule an impromptu release for urgent client requirements, but it is not something we do on an open source basis for non security issues.

**Comment by joakime** [comment]
@igreenfield its part of the 9.4.7 release, which we are staging/testing this week.
Stay tuned to [jetty-announce](https://dev.eclipse.org/mailman/listinfo/jetty-announce) for a formal release announcement.
