### ISSUE TITLE
Clarify behavior for Exception thrown from AsyncListener callbacks

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#162]
migrated from Bugzilla [#445822](https://bugs.eclipse.org/bugs/show_bug.cgi?id=445822)
status ASSIGNED severity *normal* in component *servlet-3.1* for *---*
Reported in version *9.2.3* on platform *All*
Assigned to: Greg Wilkins

On 2014-10-02 16:25:48 -0400, Joakim Erdfelt wrote:

> Example:
> 
>     public class AsyncOnStartIOExceptionHandler extends AbstractTestHandler implements AsyncListener
>     {
>         @Override
>         public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
>         {
>             AsyncContext ac = request.startAsync();
>             ac.setTimeout(1000);
>             ac.addListener(this);
>             baseRequest.setHandled(true);
>         }
> 
>         @Override
>         public void onTimeout(AsyncEvent event) throws IOException
>         {
>         }
> 
>         @Override
>         public void onStartAsync(AsyncEvent event) throws IOException
>         {
>             throw new IOException("Whoops");
>         }
> 
>         @Override
>         public void onError(AsyncEvent event) throws IOException
>         {
>             LOG.warn("onError() -> {}",event);
>         }
> 
>         @Override
>         public void onComplete(AsyncEvent event) throws IOException
>         {
>         }
>     }
>     
> This would result in an exception being logged, and then the timeout occurs, and the handle() happens again (just created a loop)
> The onError also never gets called.

On 2014-10-02 16:56:34 -0400, Joakim Erdfelt wrote:

> Newly added RequestLogHandlerTest has a demonstration of this behavior.
> 
> The only way to work around the specific onAsyncStart use case is to set the asyncContext.complete() before throwing the exception (like the testcase does).
> 
> (other use cases of exceptions from other listeners methods not covered yet by a test case)

On 2014-10-02 16:56:56 -0400, Joakim Erdfelt wrote:

> See branch [jetty-9.2.x] for testcase

**Comment by joakime** [comment]
The refactoring of async error handling has solved this issue.
