### ISSUE TITLE
JettyRunMojo use dependencies from reactor (outputdirectory)

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#1623]
With huge project such:
parent
pom.xml
 |
 - feature1
 |
 - feature2
 |
 - feature3
 |
 - webapp

With webapp using feature*, when running jetty:run first you need to install all the feature jars then running jetty:run for only webapp module. 
The goal is to be able to launch jetty:run from the top module, all modules will be compile then webapp module will ${build.outputDirectory} from modules rather than the jars.
Make development mode a bit faster.

**Comment by janbartel** [comment]
Great idea! I've just got 3 questions:

1. did we test how this affects the other plugins that derive from the JettyRunMojo? I'm thinking of JettyRunForkedMojo particularly.
2. did we verify how this affects projects that have dependencies that are web fragments or contain annotations? Are the fragments properly found? Are the annotations scanned for? If they're not, then we would need to add a note to the documentation to warn users of that.
3. did we update the doco on the jetty maven plugin for this?

**Comment by olamy** [comment]
Good questions!
I have to reckon no to all of those :-(
So I will add some it tests ( #1638 ) and doco as well

**Comment by olamy** [comment]
ok JettyRunForkedMojo do not work in this case.
annotations no problem.

**Comment by janbartel** [comment]
@olamy could you take another look at this code? I'm trying to merge it into branch issue-1640 and a couple of questions arose:

In JettyRunMojo:

- why are the dependencyResources treated differently than the dependencyFiles? Can the method getDependencyFiles() return either the location of the jar for dependencies that are not in the reactor, or the location of the classes dir for dependencies that are in the reactor?

- line 292, why are the project classes in the reactor added to the container resources? These are webapp dependencies aren't they?

In MavenWebInfConfiguration:

- do we need line 96 if we can treat the dependencyFiles and the dependecyProjects as one and the same and in JettyRunMojo do something like webapp.setWebInfLib(dependencyFiles+dependencyProjects)? Or better yet just have dependencyFiles as mentioned above?

**Comment by olamy** [comment]
sure. looks better to simplify!
As far I remember I had issues with web-fragment for directories dependencies.
Anyway I did the changes here https://github.com/olamy/jetty.project/tree/bugfix/maven_plugin_fix_master 
And yes I have issues with web fragments.
I will investigate. If you have any ideas?

**Comment by janbartel** [comment]
In JettyRunMojo on line 591, can you add a Log statement like the one on line 602?

I think the problem you are experiencing is to do with MavenWebInfConfiguration around line 206: we are only adding resources to the virtual WEB-INF/lib iff they are jar files.  To fix:  change MavenWebInfConfiguration.findJars to call JettyWebAppContext.getWebInfJars() instead of getClassPathFiles(). For consistency make a method in JettyWebAppContext.getWebInfClasses() and return _webInfClasses and call that method in MavenWebInfConfiguration.findClassDirs () instead of getClassPathFiles().

Let me know if that helps.

**Comment by olamy** [comment]
definitely helps!!
see #1680  
Can you merge in master as well so I can keep working on #1670
Remember to use -Prun-its to run Maven it tests :-)

**Comment by natros** [comment]
I'm testing jetty-maven-plugin:9.4.7-SNAPSHOT and I'm getting this NPE with manual hot reloading
```
[ERROR] Error reconfiguring/restarting webapp after a new line on the console
java.lang.NullPointerException
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:416)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.restartWebApp(JettyRunMojo.java:566)
	at org.eclipse.jetty.maven.plugin.ConsoleScanner.restartWebApp(ConsoleScanner.java:111)
	at org.eclipse.jetty.maven.plugin.ConsoleScanner.checkSystemInput(ConsoleScanner.java:75)
	at org.eclipse.jetty.maven.plugin.ConsoleScanner.run(ConsoleScanner.java:45)
```

**Comment by janbartel** [comment]
@olamy merge is done into master.

@natros  I'll look into that

**Comment by janbartel** [comment]
@natros fix pushed.

**Comment by janbartel** [comment]
@olamy  can you add a test for causing a restart of the webapp?

**Comment by olamy** [comment]
@janbartel yup

**Comment by olamy** [comment]
@janbartel this looks to be a console scanner restart so I cannot generate this with the maven it test. Weird but I cannot generate a restart with touching files. Scanner supposed to generate the restart? It looks not

**Comment by janbartel** [comment]
Touching one of the monitored files should generate a restart. There's a description here of what the monitored files are: http://www.eclipse.org/jetty/documentation/current/jetty-maven-scanning.html

**Comment by olamy** [comment]
weird I can't get this working see pr #1689

**Comment by janbartel** [comment]
Looks like it works to me:

```text
[INFO] Running org.eclipse.jetty.its.jetty_run_mojo_it.TestHelloServlet
port used:35318
[main] INFO org.eclipse.jetty.util.log - Logging initialized @202ms to org.eclipse.jetty.util.log.Slf4jLog
httpResponse hello annotation servlet:hello beer
httpResponse ping fragment servlet:pong beer
touch pom.xml touch.txt
[INFO] restarting o.e.j.m.p.JettyWebAppContext@5a50d9fc{/,file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/,AVAILABLE}{file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/}
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@5a50d9fc{/,file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/,UNAVAILABLE}{file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/}
[INFO] Webapp source directory = /home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] nonBlocking:true
[INFO] Classes = /home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/target/classes
[INFO] Context path = /
[INFO] Tmp directory = /home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp
[INFO] Reconfiguring scanner after change to pom.xml ...
[INFO] Scanning elapsed time=105ms
[INFO] Started o.e.j.m.p.JettyWebAppContext@5a50d9fc{/,file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/,AVAILABLE}{file:///home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-mojo-it/jetty-simple-webapp/src/main/webapp/}
```

**Comment by olamy** [comment]
doh interesting!
What are your os and jvm?
mine
`
MacBook-Pro:jetty.project olamy$ mvn -v
Apache Maven 3.5.1-SNAPSHOT (b1002575177abd1108fe50f457cceb9c7c3cf7d8; 2017-07-19T11:33:59+10:00)
Maven home: /Users/olamy/softs/maven/trunk
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac
`

**Comment by olamy** [comment]
so the test in pr #1689 is working but not on my machine :-)

**Comment by janbartel** [comment]
@olamy 
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=512m; support was removed in 8.0
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/java/maven/apache-maven-3.3.9
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_112/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-83-generic", arch: "amd64", family: "unix"
```

**Comment by olamy** [comment]
"funny" because PathWatcher usually works on osx but not in this case...
ATM no idea why... Maybe Thread.sleep cause some issues...

**Comment by DaiJitao** [comment]
ok

**Comment by olamy** [comment]
@janbartel I have also noticed we do not configure the PathWatcher with the scanningInterval. Is it on purpose? I changed it here https://github.com/eclipse/jetty.project/pull/1689/files#diff-ff02a462f6cc50644669e515c691229dR482

**Comment by janbartel** [comment]
@olamy yes I think so. Some time ago the thread that scanned all of the files at the scanInterval was changed to a PathWatcher instead. At that point, the scanInterval lost its meaning, but seems to have been used to still gate whether or not files should be watched (ie non zero setting meant files should be watched).  When that change was made, we should have removed the scanInterval setting and just made it a boolean instead. Possibly we could add another param to set the quiet time, but I guess as nobody has complained, the default settings to ignore "jitter" in a fast-changing file seem to be adequate :)  I think for jetty-10 we should remove scanInterval and make a boolean param called "scan" instead.

**Comment by olamy** [comment]
implemented
