### ISSUE TITLE
Support new IANA declared Websocket Close Status Codes

### ISSUE THREAD

**Issue by fRoSt13iT** [eclipse/jetty.project#1625]
When I trying to close websocket with `CloseReason.CloseCodes.TRY_AGAIN_LATER`, Jetty throws `ProtocolException` (see `org.eclipse.jetty.websocket.common.CloseInfo`).

I think close codes 1012 and 1013 should be available for use.
These codes are registered in IANA:
https://www.iana.org/assignments/websocket/websocket.xhtml#close-code-number

**Comment by joakime** [comment]
Note: The industry standard websocket testsuite actually tests these codes as invalid.

https://github.com/crossbario/autobahn-testsuite/blob/master/autobahntestsuite/autobahntestsuite/case/case7_9_X.py#L21-L22

I'm going to make 1012, 1013, and 1014 formally declared and available to be transmitted (sent or received)

It's likely that while Jetty has enabled support for these, the industry has standardized on the autobahn testsuite for ensuring their interop is compatible, which means those codes are likely not to work in other implementations (even some browsers!)

**Comment by joakime** [comment]
Committed to jetty-9.4.x, merged master [10.x.x]
