### ISSUE TITLE
http DELETE or PUT not show error page

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#163]
migrated from Bugzilla [#446039](https://bugs.eclipse.org/bugs/show_bug.cgi?id=446039)
status REOPENED severity _enhancement_ in component _server_ for _9.2.x_
Reported in version _unspecified_ on platform _All_
Assigned to: Jan Bartel

On 2014-10-06 08:28:25 -0400, Web Beler wrote:

> When use http DELETE or PUT and throw an exception, jetty do not show the error page.
> 
> See the following code in org.eclipse.jetty.server.handler.ErrorHandler.handle():
> 
> 69         String method = request.getMethod();
> 70         if (!HttpMethod.GET.is(method) && !HttpMethod.POST.is(method) && !HttpMethod.HEAD.is(method))
> 71         {
> 72             baseRequest.setHandled(true);
> 73             return;
> 74         }
> .......
> 
> Why the error page just handle the GET/POST/HEAD methods and ignore the others(DELETE/PUT...)?

On 2014-10-08 19:39:05 -0400, Greg Wilkins wrote:

> Sending a response body, such as an error page is not an expected response to a DELETE or PUT request, as they are not coming from a browser.
> 
> Thus the error is sent as just the error code and no body.

On 2014-10-08 21:32:51 -0400, Web Beler wrote:

> Actually, I wrote a webapp, I used ajax request to handle the data, like DELETE request  to delete data from database.
> 
> I used the error page to handle the exception. When exception in DELETE, I need the error page handler response the detail error.
> 
> My error page not a static file, but a servlet. So, my error page is not a html page, but json format data.

On 2014-10-08 21:35:38 -0400, Web Beler wrote:

> Or "DELETE or PUT no response body" is some kind of specification?

On 2014-10-08 21:51:32 -0400, Web Beler wrote:

> Let me explain my issue in detail.
> 
> I have a REST api "DELETE /user/1" wrote in SpringMVC controller called UserController.
> And a an error page "/error" config in web.xml, then "/error" is mapped to an another SpringMVC called ErrorController.
> 
> When the UserController throw an exception, if not handle by the ErrorController, it return HTTP 500.
> 
> I expect it handle by the ErrorController, in ErrorController, I will handle the exception then return HTTP 200 with JSON format error detail. So the client can get detail about the result.
> 
> It work's fine when use GET or POST, but DELETE not work because when DELETE the ErrorHalder set "baseRequest.setHandled(true);".

On 2014-10-08 22:21:09 -0400, Greg Wilkins wrote:

> This code was change a long time ago for: http://jira.codehaus.org/browse/JETTY-669
> 
> So I'm not keen to change in the general case.   You are able to replace the error handler with your own version.
> 
> Or better yet, why not develop a patch to put the acceptable methods for error page generation into a Set<String> with a default value of [GET,POST,HEAD].  You can then configure that list to include other methods if need be.
> 
> IF you submitted such a patch, we'd look at including it in the next release

On 2014-10-08 22:39:53 -0400, Joakim Erdfelt wrote:

> Perhaps the decision on "should generate response body content" can be based on the error/response status code and the RFC rules instead?
> 
> Lets see, RFC7231 says ...
> 
> 204 No Content - no response payload allowed
> 205 Reset Content - no response payload allowed
> 400 Bad Request - not specified / ambiguous (difficult to setup against an ErrorHandler anyway)
> 
> Seems all other response status codes, regardless of request method, allow body content.

On 2014-10-08 23:11:54 -0400, Web Beler wrote:

> I'd like return 200 install 500 with customer json format error data by error page when exception throw.
> 
> I will try to submit a patch suggested by Greg Wilkins.

On 2014-10-09 00:33:34 -0400, Greg Wilkins wrote:

> Note that the concern with generating error page bodies for PUT/DELETE responses is that the error page handler will send the request to a servlet that is not prepared to handle PUT/DELETE - or that will attempt to act on those methods rather than to generate an error page.
> 
> Strictly speaking, the method should probably be changed to GET when generating an error page.

On 2014-10-09 00:39:02 -0400, Greg Wilkins wrote:

> See https://java.net/jira/browse/SERVLET_SPEC-108

**Comment by joakime** [comment]
The changes for Issue #124 short circuits the original purpose of this bug.

We should consider closing this.

The new topics related to future enhancements to error mapping (https://java.net/jira/browse/SERVLET_SPEC-108) is really outside of the scope of this bug and should be tracked differently.

**Comment by joakime** [comment]
New spec issue location ...

* https://github.com/jakartaee/servlet/issues/108

**Comment by gregw** [comment]
Error handling is fraught with complexity. Thus I'm closing this as unnecessary complication

**Comment by flozano** [comment]
as a reference for others having this issue:

just extend `ErrorPageErrorHandler` and override `errorPageForMethod`:

```java
		@Override
		public boolean errorPageForMethod(String method) {
			return true;
		}
```

**Comment by joakime** [comment]
@flozano note that some methods do not have a response body. (eg: HEAD to name one such example, there are many more)
And you also want to avoid sending a response body if the status code is something that doesn't support response bodies (like status codes 204, or 100, to name a few)

**Comment by flozano** [comment]
thanks for your comment @joakime !

I understand that, and I was going to exclude HEAD - but keep in mind that original jetty "ErrorHandler" implementation (ErrorPageErrorHandler)  has

```java
    public boolean errorPageForMethod(String method)
    {
        switch (method)
        {
            case "GET":
            case "POST":
            case "HEAD":
                return true;
            default:
                return false;
        }
    }
```

Actually if I recall correctly (please feel free to correct me) only HEAD and TRACE are forbidden from responding with a body - but with original ErrorPageErrorHandler method  returning `true` for `HEAD`, I assumed just returning true would be better.

> And you also want to avoid sending a response body if the status code is something that doesn't support response bodies (like status codes 204, or 100, to name a few)

Yes but this is an error handler, so usually 4xx and 5xx can have a body

**Comment by joakime** [comment]
If the request is HEAD, the response cannot include a body.

**Comment by gregw** [comment]
But the headers for a HEAD response should be identical to those for a GET, so often it is just easier to generate the body, so that sizes and types can be calculated the same. Jetty will stop the body from actually being sent

**Comment by joakime** [comment]
Yes, but the headers for a HEAD response _should_ represent the resource being requested.

If it's an error on the resource, then the HEAD response headers represent the error, not the resource.
This is not ideal, esp for those user-agents that treat HEAD requests properly (those that care about cache rules)

**Comment by gregw** [comment]
No.  A server "SHOULD send the same header fields in response to a HEAD request as it would have sent if the request method had been GET".   So the HEAD response represents the equivalent GET response, including errors.  It is clear that any header included (e.g. Content-Length) would be representing the error response body and not any other resource.  A correct cache implementation as per RFC9111 must take the response status into account.

So applications and error handlers in Jetty need not handle HEAD requests explicitly.  They can generate the headers/body assuming a GET and Jetty will ensure that no body is actually sent.     However, if an application wants to avoid the expense of generating a body that will not be sent, it can explicitly generate a HEAD response.    However, for error pages, I do not think it would be worth the effort.
