### ISSUE TITLE
Thread per connection retained in HTTP/2

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1637]
The EatWhatYouKill scheduling algorithm dispatches preallocated producer threads which wait to be used. In HTTP/2 this eventually results in a thread per connection.

**Comment by gregw** [comment]
Leaving open as we need to benchmark to determine optimal settings

**Comment by sbordet** [comment]
@gregw I believe that with lazy threads in `ReservedExecutor` and `TryExecutor` this issue is solved.
