### ISSUE TITLE
Add it test for Maven Plugin

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#1638]
the goal is to have it test for each mojo

**Comment by olamy** [comment]
@WalkerWatch please assign to me

**Comment by olamy** [comment]
@janbartel I have a branch with the it tests here https://github.com/olamy/jetty.project/tree/feature/maven_plugin_its
ATM fragment doesn't work but forked has been fixed.

**Comment by olamy** [comment]
regarding fragments I can see a TODO :-)  here https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/MetaInfConfiguration.java#L279

**Comment by janbartel** [comment]
@olamy  now that @joakime merged pr #1644 should this issue be closed, or is there more to do?

**Comment by joakime** [comment]
There's something up with the testcases in master.
https://jenkins.webtide.net/job/jetty.project/job/master/363/testReport/

Probably a bad merge. :-(

**Comment by olamy** [comment]
ok I will have a look on master branch

**Comment by olamy** [comment]
well it looks master has a lot changes which cause a lot of failure in the maven plugin.
So it's not simply a bad merge!
Working on it. Well finally a good idea to add some tests :-) 
I guess we can close this one. I have created #1670 to track issues with master.
