### ISSUE TITLE
SslConnection performance over WebSocket client

### ISSUE THREAD

**Issue by vishwajeetdusane** [eclipse/jetty.project#1641]
Writing large binary data (~4MB) over websocket client over SSL sends 4KB chunks. Has anyone observed this issue ?  Please note writing same amount data over websocket client without SSL does aggressively scale TCP to send larger buffer. 

Did tried changing BufferUtil.TEMP_BUFFER_SIZE to 64KB however no impact on the chunk size.

**Comment by joakime** [comment]
Is this with / or without the `permessage-deflate` websocket extension in use?

**Comment by joakime** [comment]
Also, what version of Jetty?

**Comment by vishwajeetdusane** [comment]
Tried with 9.4.0.RC2 and the trunk code, both has same behavior. Have not explicitly set permessage-deflate, What should be default?

**Comment by joakime** [comment]
9.4.0.RC2 is a beta/alpha/pre-release/non-stable release.
Please use a stable release, such as Jetty 9.4.6.v20170531.
Ignore permessage-deflate for now, lets test with a stable release first.

**Comment by vishwajeetdusane** [comment]
Have test with 9.4.6.v20170531 as well and behavior is same.

**Comment by joakime** [comment]
Looks like we are using the values from [javax.net.ssl.SSLSession.getPacketBufferSize()](http://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getPacketBufferSize--) and [javax.net.ssl.SSLSession.getApplicationBufferSize()](http://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getApplicationBufferSize--) to determine the size of buffers to use for SSL connections.

In your case, on your environment, those seem to be returning 4kb.

Have you tried enabling the JVM support for large buffers?

```
$ java -Djsse.SSLEngine.acceptLargeFragments=true <classpath> <main-class>
```

**Comment by vishwajeetdusane** [comment]
Yes i have setup before SSLSession is initialized.
`System.setProperty("jsse.SSLEngine.acceptLargeFragments", "true");`

Also verified the setting kicking off, instead of getPacketBufferSize() returns 16KB, with above setting 32KB is returned. However that does not impact the result.

**Comment by vishwajeetdusane** [comment]
Thanks @joakime  -Realized that Java8 with GCM has performance issue, causing performance issue i was facing. Java9 has addressed this issue but still native is performing 2x.

**Comment by joakime** [comment]
@vishwajeetdusane you can use openssl and its specialized s_client called s_time to perform a simple test of the various cipher timings on your java server.

Example Script:

Be sure to set `192.168.1.116:8443` to be the server you are testing.
And adjust the `-www /` to be the resource path that will return a status code 200.

``` sh
#!/bin/bash

IFS=":"
for cipher in $(openssl ciphers ALL); do
  echo $cipher
  openssl s_time -connect 192.168.1.116:8443 \
       -www / -new -time 10 -cipher $cipher 2>&1
  echo
done
```

**Comment by vishwajeetdusane** [comment]
Thanks @joakime  - i already did the benchmark. BTW benchmarking with C++ with openssl shows significant performance numbers compare to Java 8.

Is there a consideration to use openssl in Jetty ? Like Apache Crypto has binding with openssl?

**Comment by joakime** [comment]
@vishwajeetdusane last time we looked the various openssl integration layers with java were very poor.  the JNI layer added performance issues or ALPN support requirement we have was non-existent in the integration layer.

We have considered boringssl, but hit issues.

At this point, if you want native ssl handling, consider putting haproxy (or to a lesser extent nginx) in front of jetty to offload the ssl handling (and only the ssl/tls handling, not the alpn or http layers).

**Comment by vishwajeetdusane** [comment]
@joakime  - Thanks for the information. I came across https://github.com/wildfly/wildfly-openssl/ which provides a interfacing with OpenSSL. I have not benchmarked yet but would like to know you opinion on this project.

**Comment by LukeButtersFunnelback** [comment]
@vishwajeetdusane did you ever try it?

**Comment by gregw** [comment]
Note that we now have conscrypt support, which is a native SSL provider for both java8 and java9.

**Comment by LukeButtersFunnelback** [comment]
Cool, seems to be slower though :(, maybe I am now using a more secure cypher

**Comment by LukeButtersFunnelback** [comment]
Interestingly it seems to be slower the worse is when I use it both in client and server.
Do you expect conscrypt to be faster?
weirdly I notice it is using a lot less CPU e.g. 43% -> 18% while the number of requests drops from 2600/s down to 2000/s

**Comment by gregw** [comment]
@LukeButtersFunnelback any data on how much faster it is for your test would be good to know!

**Comment by LukeButtersFunnelback** [comment]
In my tests which involves sending requests that are on avg 14KB (some smaller some bigger like 8MB big) to my server on the local machine the speed up was from `2732requests/s` to `3683request/s`!
Note that I switched my java client to use conscrypt as well otherwise (from memory) it just resulted in the server using less CPU with little improvement too requests per second.
