### ISSUE TITLE
ProxyServlet always uses default number of selector threads - constructor should allow to overwrite the default.

### ISSUE THREAD

**Issue by IngoSchuster** [eclipse/jetty.project#1643]
I use Spark on a big server (88 cpus). In some configurations, Spark sets up several ProxyServlets for the admin UI.
Unfortunately, each ProxyServlet instantiates HttpClient with HttpClientTransportOverHTTP using the default constructor which lets me end up with 44 selector threads for each ProxyServlet.
This exhausts the thread pool. You can of course increase the number of threads in the pool, but it is really ridiculous to instantiate 300+ threads for an admin UI which serves probably rarely more than one concurrent request...

I can overwrite ProxyServlet.newHttpClient(), but it would really be nicer if the AbstractProxyServlet allowed to set the number of selector threads to instantiate.

**Comment by gregw** [comment]
@sbordet I've pushed a fix for this, but can you check it when you are back, as I'm concerned I may have missed some nuance in the various proxies.

**Comment by sbordet** [comment]
@gregw I reviewed the fix and extended it to `FastCGIProxyServlet`.
