### ISSUE TITLE
servlet3.0 feature, META-INF/resources could not be requested

### ISSUE THREAD

**Issue by gdyxml2000** [eclipse/jetty.project#1646]
servlet 3.0 web-fragment.xml can be Analysis, but META-INF/resources could not be requested

**Comment by janbartel** [comment]
@gdyxml2000 I don't understand, can you please explain the situation more? Please include jetty version, operating system, jvm version and any relevant customizations.

**Comment by janbartel** [comment]
@gdyxml2000 please provide more details, otherwise there is not enough information here to work with.

**Comment by janbartel** [comment]
Closing due to lack of information.If you can provide full details on how you are running jetty, what jetty version, what jvm you're using, debug log output and and a reproduction test case then please reopen.
