### ISSUE TITLE
No way of making a distinction between no context found because of no virtual host matches or a misconfigured context pointing to a non existent directory

### ISSUE THREAD

**Issue by gouessej** [eclipse/jetty.project#1648]
I'm using Jetty 9.4.6.v20170531.

I see that I get the same error message (404, no context found, ...) when there is no context that matches and when the only context that should match uses the resource base of the ResourceHandler is a non existent directory.

If I take [this example](http://www.eclipse.org/jetty/documentation/current/static-content-deployment.html) and delete the directory /home/jesse/scratch, I get the same error message than if I add a virtual host and if there is no longer any context that matches.

Now I'm aware of this limitation but would it be possible to display a different error message when there is a matching context but no file to serve? Personally, knowing that a context matches but that there is no such directory matching with the resource base would indicate that the virtual hosts are correct but that the problem comes from a moved or deleted directory whereas the current error message makes me believe that my virtual hosts are wrongly configured.

Maybe my request is absurd or unsafe.

**Comment by gregw** [comment]
There is something I'm missing in your example.  If I write a very simple version of what you describe:
```
public class OneContext
{
    public static void main( String[] args ) throws Exception
    {
        Server server = new Server( 8080 );

        ContextHandler context = new ContextHandler();
        context.setContextPath( "/scratch" );
        
        ResourceHandler resources = new ResourceHandler();
        resources.setResourceBase("/tmp/does/not/exist");
        resources.setDirectoriesListed(true);
        context.setHandler( resources );
        
        HandlerList handlers = new HandlerList(context,new org.eclipse.jetty.server.handler.DefaultHandler());
        server.setHandler( handlers );

        server.start();
        server.join();
    }
}
```
Then I get the default error response which is just a `404 Not Found`

If I extend the example to use the DefaultHandler more like a normal configuration:
```
public class OneContext
{
    public static void main( String[] args ) throws Exception
    {
        Server server = new Server( 8080 );

        ContextHandler context = new ContextHandler();
        context.setContextPath( "/scratch" );
        
        ResourceHandler resources = new ResourceHandler();
        resources.setResourceBase("/tmp/does/not/exist");
        resources.setDirectoriesListed(true);
        context.setHandler( resources );
        
        HandlerList handlers = new HandlerList(context,new org.eclipse.jetty.server.handler.DefaultHandler());
        server.setHandler( handlers );

        server.start();
        server.join();
    }
}
```

The the error page is generated by the DefaultHandler, which is still a `404 Not Found`, but with the message: `No context on this server matched or handled this request.`

Even if I add a ContextHandlerCollection, I still get the same error message.

I searched the code base for the string "no context found" and that does not appear in the jetty codebase.  So something else is generating that message for you?!?!?

**Comment by gouessej** [comment]
I get exactly this error message when there is really no context that matches, sorry for the lack of accuracy:

> "Error 404 - Not Found.
> No context on this server matched or handled this request.
> Contexts known to this server are: "

I'll make another test and let you know.

**Comment by gregw** [comment]
That's the error message I would expect.   I think it is about as explicit as it can be.   No handler matched OR handled the request.   It is impossible for the DefaultHandler to really know why a request has not been handled - it could be because it did not match (a path or virtual host) or it could be that it did match, but the handler chose not to handle (because of missing file etc.).
