### ISSUE TITLE
websocket server test failure 9.4.x

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1651]
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   WebSocketOverSSLTest.testEcho Leaked Resource Count for [Test]
Expected: is <0L>
     but: was <1L>

Head of 9.4.x branch, maven 3.3.9, java 1.8_112, ubuntu 16.04.

**Comment by joakime** [comment]
No point fixing this in jetty-9.4.x HEAD atm, as issue #1650 will replace that testcase entirely.
