### ISSUE TITLE
Improve extensibility of ServerConnector

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1655]
Allow the server channel to be overriden

**Comment by sbordet** [comment]
@gregw I think I'd like to have a setter too, throwing `IllegalStateException` if it's already set.

**Comment by gregw** [comment]
@sbordet done

**Comment by joakime** [comment]
Some thoughts on things to check if the ServerConnector's Channel is null at the wrong time.

* JMX output of ServerConnector details
* ConnectionStatistics
* RequestLog setup
* Various XML configuration that expects a Channel (not sure if this is valid)
* Debug Logging
* Dump output
* FastCGI setup
* LowResourceMonitor
* Various existing extensions to ServerConnector (like NetworkTrafficServerConnector)
* Use of BaseRequest.getHttpChannel() - such as for setting up ContextHandler for Connector.name behaviors

**Comment by gregw** [comment]
@joakime being null at the wrong time is not really a problem, as it was already able to be null and is only assigned during start.  The setter is disabled once started, so it cannot null the channel when it is expected to be non null.

the problem is that for setters, you expect the value to persist, except in this case a start/stop cycle will null the setting.   We probably need to make it so that if manually set, then it is not closed or nulled by a call to stop.... although it is more like the setter is handing over the channel rather than loaning it to the connector....  maybe OK as is.

**Comment by gregw** [comment]
tried having non auto close option, but interrupting a blocking acceptor closes the accept channel, so it is not an option.
