### ISSUE TITLE
System class can be loaded from webapp loader

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#166]
migrated from Bugzilla [#447461](https://bugs.eclipse.org/bugs/show_bug.cgi?id=447461)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.2.3* on platform *PC*
Assigned to: Jan Bartel

On 2014-10-15 21:51:58 -0400, Jan Bartel wrote:

> If a class that is designated a system class does not exist in the container's classloader parent hierarchy, but is inside the webapp's classloader, the WebAppClassLoader.loadClass method falls back to calling findClass, which results in it being loaded from the webapp's classloader.

On 2014-11-13 21:49:20 -0500, Jan Bartel wrote:

> *** Bug 447187 has been marked as a duplicate of this bug. ***

**Comment by janbartel** [comment]
@gregw should we throw an exception if a system-scoped class is not loaded from the parent classloader?

**Comment by gregw** [comment]
I don't think so.  The protection is that system class cannot be overridden. If the container chooses not not provide a class/package, then there is no reason why the webapp cannot provide it's own.
