### ISSUE TITLE
Need release notes on download page

### ISSUE THREAD

**Issue by khoaminhbui** [eclipse/jetty.project#1660]
I go to Jetty download page and cannot find release notes to decide if it's worth upgrading.
I to Google to find those information elsewhere.
Could you please to put a link to release notes on the download page for user convenient.
Thank you.

**Comment by joakime** [comment]
No need, the release notes exist in multiple places currently.

The sources of release notes:

* As a Github release entry (each version) - eg: https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.6.v20170531
* Inside the `jetty-distribution-<ver>.tar.gz` (or zip) see `/VERSION.txt` - http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.6.v20170531/jetty-distribution-9.4.6.v20170531.tar.gz
* Inside the `jetty-home-<ver>.tar.gz` (or zip) see `/VERSION.txt` - http://central.maven.org/maven2/org/eclipse/jetty/jetty-home/9.4.6.v20170531/jetty-home-9.4.6.v20170531.tar.gz
* In github repository as file - https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/VERSION.txt
* In the global central repository (each release) - `http://central.maven.org/maven2/org/eclipse/jetty/jetty-project/<ver>/jetty-project-<ver>-version.txt` - http://central.maven.org/maven2/org/eclipse/jetty/jetty-project/9.4.6.v20170531/jetty-project-9.4.6.v20170531-version.txt  
* For every Jetty release announcement on the [jetty-announce mailing list](https://dev.eclipse.org/mailman/listinfo/jetty-announce) - https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00109.html

**Comment by joakime** [comment]
Would recommend that you subscribe to the jetty-announce mailing list (that's what its for).

**Comment by khoaminhbui** [comment]
Thank you, I will subscribe. That will keep me up to date.

**Comment by joakime** [comment]
You can also go to the github project release page and click into the specific release you are interested in.

https://github.com/eclipse/jetty.project/releases

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch has cleaned up some of the download pages a while back, flagging this for future ideas as well.

**Comment by WalkerWatch** [comment]
We could probably link the VERSION.txt on the downloads page but unsure if it is worthwhile as it is available in so many other locations. Thoughts @jmcc0nn3ll and @joakime ?

**Comment by joakime** [comment]
@WalkerWatch nah, just have text that links to the jetty-announce mailing list.  

Something along the lines of "For details about each release, use jetty-announce@eclipse.org or the github.com/eclipse/jetty.project/releases page"
