### ISSUE TITLE
NPE with WebSockets when BatchMode is ON

### ISSUE THREAD

**Issue by AnywhereSoftware** [eclipse/jetty.project#1662]
We have upgraded from Jetty 9.3 to 9.4.6 and started seeing NPE errors in CompressExtensions after calling WebSocket.flush();
 
After some digging I believe that it is related to a change in CompressExtensions.deflate.
It tries to compress the FLUSH_FRAME and throws a NPE as it has no payload. Adding payload to FLUSH_FRAME doesn't help as it will prevent FrameFlusher from behaving correctly.
 
The suggested solution is to change CompressExtensions.deflate to:
```
private void deflate(FrameEntry entry) 
{

Frame frame = entry.frame; 
BatchMode batchMode = entry.batchMode; 
if (OpCode.isControlFrame(frame.getOpCode()) || frame == FrameFlusher.FLUSH_FRAME) 
{
// Do not deflate control frames 
nextOutgoingFrame(
frame,this,batchMode); 
return; 
}
compress( entry,true); 
}

```

**Comment by joakime** [comment]
This wasn't unique to BatchMode.ON or flush(), the NPE itself was harmless and didn't actually affect the production the compressed output any harmful way.  Those frames were reported and skipped by the ExtensionStack essentially.

**Comment by AnywhereSoftware** [comment]
They were not harmless. For us flushing didn't work without this change.

**Comment by joakime** [comment]
@AnywhereSoftware commit 45a4b87 addresses the NPE directly.
