### ISSUE TITLE
Refactoring of Request

### ISSUE THREAD

**Issue by joaoplm** [eclipse/jetty.project#1669]
Hello everyone.
I was analyzing the modularization of some classes, and I identified that the class Request has an opportunity for cohesion improvement. 
The class NCSARequestLog was in the same situation and the problem was solved as follows: The AbstractNCSARequestLog class was created, and several get() and set() methods that were used only to configure the class parameters were moved from NCSARequestLog to AbstractNCSARequestLog. 
The new class was then accessed through an instance variable in NCSARequestLog. This strategy has cleaned and improved NCSARequestLog cohesion.
With this in mind, I would recommend creating a new class: RequestConfig , and moving the following methods:

getRealPath
getRequestDispatcher
setRemoteAddr
getServletContext
setHttpURI
setAttribute
getScheme
getParts
setContentType
getLocalAddr
setDispatcherType
getAuthentication
getDateHeader
getAuthType
getHttpVersion
setMetaData
setURIPathQuery
setCharacterEncodingUnchecked
getHeader
setSessionManager
setContext
setContextPath
getContentRead
setCookies
getUserPrincipal
getContextPath
getLocale
setQueryString
getLocalName
getSession
getPathTranslated
getQueryString
getContentType
getCookies
getRemoteUser
setCharacterEncoding
setAuthority
setQueryParameters
getRemoteHost
setServletPath
getServletName
getInputState
setTimeStamp
setPathInfo
getReader
getServerPort
getMetaData
getContentLength
getIntHeader
getSessionManager
getHttpURI
getAsyncContext
getMethod
getAttribute
getAttributeNames
getQueryParameters
getHeaders
getParameterMap
getHttpChannelState
getRequestURI
setAttributes
getHttpChannel
getResponse
getServletPath
getDispatcherType
setMethod
getParameterNames
getRemoteInetSocketAddress
setSecure
setRequestedSessionIdFromCookie
getContentLengthLong
getPathInfo
getLocalPort
getResolvedUserIdentity
setAuthentication
getQueryEncoding
getRemotePort
getRequestURL
getRequestedSessionId
getLocales
getPushBuilder
setContentParameters
getUserIdentityScope
setRequestedSessionId
getAttributes
getPart
getParameter
getProtocol
setQueryEncoding
getInputStream
getRemoteAddr
getUserIdentity
getHeaderNames
getServerName
getBaseRequest
getServletResponse
getHttpInput
getHttpFields
getParameterValues
getRootURL
setHandled
setUserIdentityScope
getCharacterEncoding
getContext
setAsyncSupported
setScheme
setSession
getTimeStamp

from the Request.
Those parameters accessed by an instance variable in the Request.
Moreover, the orthogonality is the design would be enhanced.

What do you think about that?

**Comment by gregw** [comment]
@joaoplm ,

firstly I'm not understanding your example NCSARequestLog extends AbstractNCSARequetLog and there is no instance variable.

Now I don't deny that the `Request` class is very fat and could benefit from some simplification, however I do not see how creating a `RequestConfig` class helps all that much, plus I would be concerned about the additional object creation and dereferences required from a performance point of view.

Note also that Request already does have an inner instance that is kind of a `RequestConfig`.   It is already passed a `MetaData.Request` instance which holds method, URI, version, headers and trailers of the request.  Many of the methods you list are already handled by referencing this instance:

setScheme
setMethod
setAuthority
setURIPathQuery
setVersion

etc.

**Comment by joaoplm** [comment]
Thank you Greg. I used the wrong example, and I did not know about the internal Metada class. I recommended this strategy because I thought it would be simple to apply. But at least I hit the spot, the Request class could benefit from some kind of refactoring right?

**Comment by gregw** [comment]
@joaoplm well it is true that Request is a very large somewhat ugly class that is carrying lots of history with it. It also fulfils several roles: internal jetty request that is mutable; standard API class that is not mutable.. except via dispatch.

It is the mutability aspect of the class that makes it rather difficult to simplify.  It would be much easier if there was an immutable core class that represented the original request and then a mutable facade, that can cope with rewrites and dispatches etc.     But it is hard to strike a balance that does not have too much duplication or data copying.

So yes I'd like to see a cleaner class, but it is a much more difficult task than it looks.  So I've punted to the too-hard-basket several times and only made minor improvements.     But if you want to have a crack at it, we'd be happy to receive a pull request and would review and work with you to see what could be done to improve the class.

**Comment by joaoplm** [comment]
Hi @gregw. Thank you for the answer.  I have a short list of classes in which I have also identified opportunities:

ContextHandler
WebAppContext
Response
AbstractSessionManager
ContextHandler$StaticContext
ServletHandler

Could you please take a look and tell me if it's viable? Maybe some of these classes can be cleaned with a simple refactoring, similar to the one I proposed.
