### ISSUE TITLE
Servlet classes should be loaded using TCCL

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#167]
migrated from Bugzilla [#447462](https://bugs.eclipse.org/bugs/show_bug.cgi?id=447462)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.2.3* on platform *PC*
Assigned to: Jan Bartel

On 2014-10-15 21:57:32 -0400, Jan Bartel wrote:

> Currently BaseHolder.doStart() method will use the java.util.Loader.loadClass() method to load the servlet class. This method will fall back to other loaders if the TCCL fails to load the class. Probably the BaseHolder should simply use the TCCL, so we can be sure to respect its system/server class settings.

On 2015-07-10 10:01:22 -0400, Michael Fahy wrote:

> Any update on this bug ? 
> 
> It doesn't look like it was fixed in 9.3.0.
> 
> Basically, I am embedding an application which uses Jersey. And because of the auto-discovery stuff Jersey does, it discovers classes that are in my container and which should not be present in the embedded application.

On 2015-07-15 19:52:14 -0400, Greg Wilkins wrote:

> @Michael,
> 
> I'm not understanding how this bug can affect Jersey discovery?  This bug is just that once discovered/configured, a Servlet/Filter may be loaded from the server or system classloader even if it is hidden by the context loader.
> 
> This should not affect Jersey discovery at all - as that should use other mechanisms.  Ie this is a load issue, not a discovery issue.
> 
> So can you explain your situation some more? Perhaps create a small example and attach to a new bug.

On 2015-07-16 01:56:31 -0400, Greg Wilkins wrote:

> I've committed a fix for this into the Jetty-9.3-Feature2 branch, as it requires a change to the way we expose server classes.  Thus it is a bit too much of a change to sneak into a dot release, but it will be in 9.4 or 10.0, which ever is next.

**Comment by joakime** [comment]
The changes to `Loader.loadClass()` in jetty 9.4.x seem to have this already applied via commit a311c8bde171551a57ff28c04851a3b53acfc1e0

**Comment by janbartel** [comment]
This issue was fixed in jetty-9.4 and beyond with the commit referenced by @joakime .
