### ISSUE TITLE
Session id should not be logged with INFO level in AbstractSessionCache

### ISSUE THREAD

**Issue by knes1** [eclipse/jetty.project#1675]
Many projects that use Jetty may have INFO level logging turned on at root logger level (such as Spring Boot for example). In such default configs AbstractSessionCache will under certain circumstances log active session IDs to the log file. This is not a good security practice. Reference: OWASP ASVS standard ( download here: https://www.owasp.org/images/3/33/OWASP_Application_Security_Verification_Standard_3.0.1.pdf ), under Session Management Requirements, OWASP ASVS says:

    Verify that the session id is never disclosed in URLs, error messages, or logs. This 
    includes verifying that the application does not support URL rewriting of session 
    cookies.

When a new session ID is created (for example, when user logs in) this is logged with lNFO level in 
AbstractSessionCache:

    LOG.info("Session id {} swapped for new id {}", oldId, newId);

Should a malicious user obtain access to log files (which typically log INFO level log entries), they could obtain access to active session ids. While this could be prevented by other means, I believe it would be beneficial if Jetty was configured with high level of security by default. I suggest that active session ids are logged with level of at most DEBUG or TRACE.

**Comment by joakime** [comment]
Jetty logging has no concept of TRACE.  
Setting it to DEBUG makes sense though.

**Comment by janbartel** [comment]
I'll take a look and see what I can change to DEBUG level instead. However, whilst laudable in motive, requirement 8.1 and 8.4 on page 36 are somewhat in conflict - very hard to include necessary info on error logging for sessions without including the session id!

**Comment by janbartel** [comment]
Changed 2 INFOs (1 identified in AbstractSessionCache and another in Session) to DEBUG.

**Comment by knes1** [comment]
Thank you!
