### ISSUE TITLE
Embedded Jetty server's classpath parsing/scanning broken with Maven Surefire's useManifestOnlyJar feature

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#168]
migrated from Bugzilla [#447790](https://bugs.eclipse.org/bugs/show_bug.cgi?id=447790)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.0.6* on platform *PC*
Assigned to: Jan Bartel

On 2014-10-18 18:01:49 -0400, Karl M. Davis wrote:

> I was attempting to use Maven Surefire/Failsafe to run some integration tests using that start up an embedded Jetty server and ran into problems today. Given this configuration, Jetty would fail to launch correctly and my tests would all fail:
> 
> <plugin>
> 	<groupId>org.apache.maven.plugins</groupId>
> 	<artifactId>maven-failsafe-plugin</artifactId>
> 	<configuration>
> 		
> 		<useManifestOnlyJar>true</useManifestOnlyJar>
> 	</configuration>
> </plugin>
> 
> With things set that way, I'd end up with messages like this in my log:
> 
> [main] INFO  / - No Spring WebApplicationInitializer types detected on classpath
> 
> After a lot of debugging and cursing, it turns out that Spring MVC relies on Jetty to have correctly scanned the classpath and found all of the JARs/class directories in use. However, when Surefire's "manifest" JAR feature is enabled, the JVM's base classpath just contains a JAR with a manifest that points to all of the project's dependencies. This is apparently done by Surefire to work around command line length limitations on Windows, which makes sense.
> 
> Unfortunately, Jetty doesn't check the manifests of the JARs on its classpath for "transitive" dependency JARs, and so misses all of the project's dependencies. I've kinda-sorta tracked this down to the org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebAppContext) method. In the scenario I'm describing here, containerUris ends up with the following value that Jetty doesn't handle correctly:
> 
> [file:/home/karl/workspaces/rps-tourney/rps-tourney.git/rps-tourney-service-app/target/surefire/surefirebooter7082852056793464207.jar, file:/home/karl/.m2/repository/org/jacoco/org.jacoco.agent/0.6.5.201403032054/org.jacoco.agent-0.6.5.201403032054-runtime.jar]
> 
> All that surefirebooter7082852056793464207.jar contains is a MANIFEST.MF with the actual classpath:
> 
> Manifest-Version: 1.0
> Class-Path: file:/home/karl/.m2/repository/org/apache/maven/surefire/s
>  urefire-booter/2.16/surefire-booter-2.16.jar file:/home/karl/.m2/repo
>  sitory/org/apache/maven/surefire/surefire-api/2.16/surefire-api-2.16.
>  jar file:/home/karl/workspaces/rps-tourney/rps-tourney.git/rps-tourne
>  y-service-app/target/test-classes/ file:/home/karl/workspaces/rps-tou
>  rney/rps-tourney.git/rps-tourney-service-app/target/classes/ file:/ho
>  ...
> Main-Class: org.apache.maven.surefire.booter.ForkedBooter
> 
> In order to properly run in such a scenario, Jetty would have to evaluate the Class-Path manifest attribute of each JAR on its classpath.

On 2014-10-18 18:03:22 -0400, Karl M. Davis wrote:

> Some Googling led me to mentions of the following related troubles that other folks have had with this problem:
> 
> 1. http://stackoverflow.com/questions/19469292/cant-load-jstl-in-multi-module-maven-project-with-embedded-jetty
> 2. http://dev.eclipse.org/mhonarc/lists/jetty-users/msg01653.html

On 2014-11-06 23:11:27 -0500, Jan Bartel wrote:

> Karl,
> 
> Are you sure you have the jetty-annotations.jar on the classpath and that you are applying the appropriate set of XXXConfigurations to the WebAppContext? The XXXConfig classes should be set to the following (if you're doing an embedded jetty startup, otherwise check the etc/jetty-annotations.xml and etc/jetty-plus.xml files in the distro for the xml):
> 
> org.eclipse.jetty.webapp.Configuration.ClassList classlist = org.eclipse.jetty.webapp.Configuration.ClassList.setServerDefault(server);
> classlist.addAfter("org.eclipse.jetty.webapp.FragmentConfiguration", "org.eclipse.jetty.plus.webapp.EnvConfiguration", "org.eclipse.jetty.plus.webapp.PlusConfiguration");
> classlist.addBefore("org.eclipse.jetty.webapp.JettyWebXmlConfiguration", "org.eclipse.jetty.annotations.AnnotationConfiguration");
> 
> Also, the way I read the failsafe doco, their booter mechanism is responsible for extracting the classpath and setting that up in a new classloader. I would expect that synthetic classloader to be the parent for the WebAppClassLoader that we create.  If that's true, then the java.util.ServiceLoader mechanism should be able to find the SpringServletContainerInitializer, which has an @HandlesTypes=WebApplicationInitializer.class. If Jetty finds an @HandlesTypes annotation then we do a full scan of the classloader hierarchy to find type hierarchy.
> 
> You should enable full debug for jetty (-Dorg.eclipse.jetty.LEVEL=DEBUG) and check the output from the AnnotationConfiguration which will let you know which jars and classes are being scanned.
> 
> regards
> Jan
> 
> 
> 
> 
> 
> (In reply to Karl M. Davis from comment # 1)
> > Some Googling led me to mentions of the following related troubles that
> > other folks have had with this problem:
> > 
> > 1.
> > http://stackoverflow.com/questions/19469292/cant-load-jstl-in-multi-module-
> > maven-project-with-embedded-jetty
> > 2. http://dev.eclipse.org/mhonarc/lists/jetty-users/msg01653.html

On 2015-01-09 10:04:32 -0500, Jan Bartel wrote:

> Karl,
> 
> Are you able to attach a small demonstration project for this please?
> 
> thanks
> jan

On 2015-02-04 00:56:40 -0500, Jan Bartel wrote:

> Karl? Any responses to my questions, or a test harness?
> thanks
> Jan

**Comment by joakime** [comment]
@janbartel use the https://github.com/jetty-project/embedded-jetty-jsp project.

Disable the `<useManifestOnlyJar>false</useManifestOnlyJar>` first.
Then execute (from the maven command line) a full build/test `mvn clean install`

**Comment by janbartel** [comment]
For jetty to work correctly with the surefire plugin, you need to use the  isolated classloader method, which is configured by using useManifestOnlyJar=false parameter.  This was the default for surefire for versions prior to surefire 2.4, so things would naturally have worked. However, in version 2.4, the plugin changed to using a generated manifest jar instead, hence the need for the useManifestOnlyJar=false setting.

Worth noting that according to the documentation at  [Surefire Classloading](http://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html) there is no longer any reason for using a manifest-only jar to shorten the forked command line.
