### ISSUE TITLE
Jetty-WarFragmentFolderPath directive has no effect in eclipse runtime mode except for the first launch

### ISSUE THREAD

**Issue by jbrazeau** [eclipse/jetty.project#1682]
Let's consider I have a plugin that contains a webapp (according to https://www.eclipse.org/jetty/documentation/9.4.6.v20170531/framework-jetty-osgi.html#_deploying_bundles_as_webapps ) using `Jetty-WarFolderPath` directive in its `META-INF/MANIFEST.MF` : 
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Webapp
Bundle-SymbolicName: org.jetty.test.webapp
Bundle-Version: 1.0.0.qualifier
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Jetty-WarFolderPath: WebContent
Web-ContextPath: /mywebapp
```
Let's imagine I have a very simple webapp with a single `index.html` resource in it (`web.xml` is almost empty, it only contains XML root `<web-app/>` directive, no servlet, no filter, ...) : 
![screen shot 2017-07-20 at 17 36 17](https://user-images.githubusercontent.com/1405453/28425922-fa3b03f4-6d71-11e7-8932-88977ab3804a.png)

I create a target platform resource to describe the dependencies I want to use by selecting : 
* Neon base plugins (http://mirror.update.eclipse.obeo.fr/neon )
* Jetty 9.4.6.v20170531 (http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.4.6.v20170531/ )

I create a product with an simple `IApplication` configured to bootstrap Jetty.

At this stage, everything works fine, I get the result I expect in a browser when I try to access http://localhost:8080/mywebapp/ , I retrieve the `index.html` static resource content (note : I also had to import Apache Aries & ASM to avoid getting this problem : https://stackoverflow.com/questions/43775025/after-jetty-update-to-9-4-x-missing-constraint-require-capability-osgi-extend ) : 
![screen shot 2017-07-20 at 17 45 11](https://user-images.githubusercontent.com/1405453/28426380-35b96d0c-6d73-11e7-9dad-3c8565d37e54.png)

Now I add a fragment that contributes to the previous plugin using the `Jetty-WarFragmentFolderPath` directive : 
![screen shot 2017-07-20 at 17 48 59](https://user-images.githubusercontent.com/1405453/28426548-c02c4c34-6d73-11e7-8694-7f76894048d3.png)

Here is the `META-INF/MANIFEST.MF` : 
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Fragment
Bundle-SymbolicName: org.jetty.test.webapp.fragment
Bundle-Version: 1.0.0.qualifier
Fragment-Host: org.jetty.test.webapp
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Jetty-WarFragmentFolderPath: WebFragment
```

This fragment simply adds a `fragment.html` resource. The first time I launch my runtime, I get the result I expect if I enter http://localhost:8080/mywebapp/fragment.html in my browser : 
![screen shot 2017-07-21 at 08 46 57](https://user-images.githubusercontent.com/1405453/28452086-4836eed6-6df1-11e7-9dba-a24cea01580c.png)

But if I stop my webapp and restart it it doesn't work anymore : 
![screen shot 2017-07-21 at 08 50 14](https://user-images.githubusercontent.com/1405453/28452180-a863f470-6df1-11e7-879a-74d2d6a0f372.png)

I finally understood what happens after a few hours spent on this problem. The first time the runtime is launched, equinox discovers the fragment. In that situation, eclipse storage returns an absolute canonical path for the plugin path and everything works well.

But when eclipse is restarted, equinox uses a `framework.info.14` file (numeric value may differ from 14) that contains cached informations about plugins, and among other things path informations. And those path informations are relative to the storage area, so that in that situation, the path that is returned contains several `../` (in opposition to what happens the first time the plugin or fragment is "discovered").

For a reason that I don't perfectly understand, Jetty considers in that situation (when the path is not canonical) that the path is an alias (`org.eclipse.jetty.util.resource.PathResource#isAlias()`returns `true`). In that situation, the 
`org.eclipse.jetty.server.handler.ContextHandler` invokes two alias checkers in the `checkAlias` method (`AllowSymLinkAliasChecker` and `ApproveNonExistentDirectoryAliases`) and both of them return `false` so that the `ContextHandler#getResource()` finally returns `null` to the caller instead of the expected result (I mean the `fragment.html` resource path).

A simple way to hightlight it can be followed to reproduce the observation : 
* remove the `<Path to the workspase>/.metadata/.plugins/org.eclipse.pde.core/org.jetty.test.app.product/org.eclipse.osgi/framework.info.14` resource (numeric value at the end may differ)
* restart the runtime => If you do so, everything works fine again
* restart again the runtime => we get a 404 error ; we can see in the filesystem that  `framework.info.XX` has been recreated by equinox

I attach to this ticket a simple test case made of 6 plugins that isolates the issue : [bug-jetty-fragment-20170720-1803.zip](https://github.com/eclipse/jetty.project/files/1164682/bug-jetty-fragment-20170720-1803.zip)

The archive simply contains :
* The test case itself :
  * `org.jetty.test.app` : the eclipse application (that is launched in runtime mode) ; this plugin also contains the target platform and product definition files (`org.jetty.test.app.target` and `org.jetty.test.app.product`)
  * `org.jetty.test.webapp` : the webapp
  * `org.jetty.test.webapp.fragment` : the fragment
* Apache Aries & ASM (to avoid getting this problem : https://stackoverflow.com/questions/43775025/after-jetty-update-to-9-4-x-missing-constraint-require-capability-osgi-extend) :
  * `org.apache.aries.spifly.dynamic.bundle`
  * `org.apache.aries.util`
  * `org.objectweb.asm.all`

This archive is shipped with target platform definition file (`/org.jetty.test.app/org.jetty.test.app.target`) and a product definition file (`/org.jetty.test.app/org.jetty.test.app.product`) that eases the way to reproduce the steps described in this ticket (simply set the target platform and launch the product).

Note : this reproduction package is tested with Jetty 9.4.6.v20170531, but I faced the same problem with 9.3.20.

Tell me if something is unclear. The only workaround I have found is to add a custom `AliasCheck` implementation to the `ContextHandler` that accepts everything. I am not very happy with this workaround.

My environment : Mac OS, Java 1.8.0_121-b13

**Comment by janbartel** [comment]
Thank you very much @jbrazeau  for the repro test case! I'd like to run it, but as I'm not an Eclipse plugin developer, I'm not sure exactly how to go about it - can you give me some pointers? 

In your setup, is it possible to put a breakpoint in the org.eclipse.jetty.osgi.boot.utils.internal.DefaultFileLocator.getBundleInstallLocation(Bundle) method around line 96 and report what the URL is that is returned from the call to bundle.getEntry("/META-INF/MANIFEST.MF") both on first deployment and after redeployment?

I agree that you should not use a lax AliasCheck - I feel that the solution is to modify the DefaultFileLocator.getBundleInstallLocation(Bundle) method, but I need to see the different urls to understand how to fix it.

**Comment by jbrazeau** [comment]
Thank you @janbartel to pay attention to this issue I've reported.

I hav put the breakpoint you describe (and I added a condition to the breakpoint so that it is activated only when the bundle is `org.jetty.test.webapp`, which I guess is the one you want me to test). In both cases (first startup & second), it returns the same information: `bundleentry://32.fwk173099767/META-INF/MANIFEST.MF`.

This is an eclipse internal URL that targets OSGI bundle resources. This is classically resolved by using `org.eclipse.core.runtime.FileLocator#resolve`.

It seems that Jetty uses a different approach through reflection (from line 107 to 167 in `org.eclipse.jetty.osgi.boot.utils.internal.DefaultFileLocator`) ; I guess Jetty doesn't use `FileLocator` for a question of dependency management ? (maybe Jetty cannot depend on `org.eclipse.core.runtime` ?).

Nevertheless, at line 134 of the same class, I get the following results if I look at the file absolute path (which variable name is `f` in the code: 
* first launch : `/path_to_my_workspace/org.jetty.test.webapp/META-INF/MANIFEST.MF`
* second launch : `/path_to_my_workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/../../../../org.jetty.test.webapp/META-INF/MANIFEST.MF`

(As you may understand, I just replaced my real workspace's path by the string `path_to_my_workspace` but the end of both paths remains unchanged) 

So when `f.getParentFile().getParentFile()` is returned by the method, the caller gets : 
* second launch : `/path_to_my_workspace/org.jetty.test.webapp`
* first launch : `/path_to_my_workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/../../../../org.jetty.test.webapp`

**Comment by janbartel** [comment]
@jbrazeau  thanks for that information, very helpful.

I've made a fix in DefaultFileLocatorHelper class. Could you checkout the jetty-9.4.x branch, build and test locally for me?

**Comment by janbartel** [comment]
@jbrazeau  failing any feedback, I'm calling this one fixed and closing the issue. If you test and find there is still a problem, please reopen and provide all data.

**Comment by jbrazeau** [comment]
@janbartel Thank you for the fix, and sorry, I didn't have time to test it before. I'd like to test it now, but as I am in an OSGi environment, I need the code to be packaged. Can you tell me if there is a p2 repository (like this one : http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/) that would contain nightly builds ? (as far as I can see, the one I mention only contains releases)

It seems that such a p2 repository exists for 7.x and 8.x branches as it is mentionned here : https://wiki.eclipse.org/Jetty/Contributor/Update_Site#Jetty-rt-bundles_repositories ; but I don't find the equivalent for 9.x (or 9.4.x).

Or can you tell me how I can build this p2 repository ? (I've built jetty on the given branch by launching maven, and it has been successfull, but I can't find any p2 repository in the source tree after the build is complete)

Thank you in advance.
