### ISSUE TITLE
Request with `Content-Encoding: gzip` should not perform parameter extraction

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1688]
Since Jetty does not support Request decompression, if a request shows up with `Content-Encoding: gzip` and the servlet does a HttpServletRequest.getParameter*() method call, then this should automatically fail, as its not possible for Jetty to satisfy this kind of request.

**Comment by joakime** [comment]
Perhaps access to HttpServletRequest.getInputStream() should also be protected.

**Comment by sbordet** [comment]
@joakime `HttpServletRequest.getInputStream()` should be accessible from applications so that they can ungzip the content.

**Comment by joakime** [comment]
@sbordet i'm not saying that HttpServletRequest.getInputStream() should be disabled, just that in the specific case of ...

Client:

    GET /foo?key=value
    Content-Type: application/x-www-form-urlencoded; charset=utf-8
    Content-Encoding: gzip
    Content-Length: 4000001
    Host: server
   
    <lots of binary. compressed gzip. containing form urlencoded data>

arrives at to a Jetty Server which ..

* Does not have GzipHandler specified.
* Is dispatched to a ServletContext
* Is dispatched to a user HttpServlet
* User HttpServlet does `HttpServletRequest.getParameter("key")`

In this scenario, the part of Jetty's `Request.getParameters()` that performs Request body content parsing for `application/x-www-form-urlencoded` cannot work, and should be skipped.
This just means that the `Request.getParameters()` method should not perform content extraction if the `Content-Encoding` exists and is one of the compressed formats.

Now, if GzipHandler is present, it will wire up the HttpInput Interceptor and automatically decompress the request body, which also (should be) removes the `Content-Encoding` header from the request.

**Comment by gregw** [comment]
I think the `HttpServletRequest.getParameter("key")` and any other attempt to extract the parameters should throw an `IllegalStateException` or perhaps `BadMessageException(HttpStatus.NOT_IMPLEMENTED_501)`

**Comment by slonopotamus** [comment]
This suddenly broke our software. I think you're violating documentation contract of javax.servlet.ServletRequest#getParameterMap. It doesn't say that is it ever supposed to throw an exception. It even isn't actually clear how user is supposed to work with getParameterMap. Should I check the same condition that you check before calling getParameterMap? Why you cannot simply return an empty map?

**Comment by joakime** [comment]
@slonopotamus if you send a `Content-Encoding` and there's nothing configured on the server to understand that `Content-Encoding` then you'll at best wind up with incredibly bad data with `HttpServletRequest.getParameterMap()`, or a `BadMessageException` when it cannot parse the unparseble body content.

An Empty Map has proven to be problematic as it hides issues, quietly continuing with bad or incomplete data.  It will even cause problems with RequestDispatching and JSPs and JSFs.
Spring will also throw exceptions on this kind of bad data scenario.

The correct technique is to fail the request, but with the Servlet spec we don't pre-parse the request body content before dispatching the request.  We can only fail when the APIs are used to access the data in the Servlet spec default way.  There's nothing preventing a Servlet from not using .getParameterMap() and choosing to ignore Content-Encoding and Content-Type and reading the request body content its own way. (a generally questionable approach, but not forbidden).

**Comment by SebasPalm92** [comment]
There is really no reason to deny the a request when it contains a Content Encoding: identity. 
identity: Indicates the identity function (i.e., no compression or modification). This token, except if explicitly specified, is always deemed acceptable.
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding)

**Comment by joakime** [comment]
@SebasPalm92 developer.mozilla.org is not the HTTP spec.

If you have `Content-Encoding: identity` then you have an invalid header per RFC7231.

Why?
Because the `identity` Content Coding token is only for `Accept-Encoding` per the RFC spec, and also the registered at the IANA Content Codings as reserved (not used) for "no encoding" on the `Accept-Encoding` header.

* https://tools.ietf.org/html/rfc7231#section-3.1.2.1 - Content Codings
* https://tools.ietf.org/html/rfc7231#section-5.3.4 - Accept-Encoding Header
* http://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding - IANA Registerd Content Codings

Even in the older (now obsolete) RFC2616, the `identity` Content-Coding value has the following text ...
https://tools.ietf.org/html/rfc2616#section-3.5

```
    identity
        The default (identity) encoding; the use of no transformation
        whatsoever. This content-coding is used only in the Accept-
        Encoding header, and SHOULD NOT be used in the Content-Encoding
        header.
```
