### ISSUE TITLE
ContextHandlerCollection.mapContexts missing synchronization

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#169]
migrated from Bugzilla [#448390](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448390)
status ASSIGNED severity _normal_ in component _server_ for _9.2.x_
Reported in version _9.1.0_ on platform _All_
Assigned to: Jan Bartel

On 2014-10-22 10:52:55 -0400, Ingo Haase wrote:

> We have discovered that integrating Jetty in a dynamic environment like OSGi causes problems due to the incorrect handling of multiple parallel initialization requests.
> In OSGi jetty automatically recognizes and processes war files in the OSGi framework.
> When a new webapp is to be instantiated (e.g. during a restart of the OSGiframework), the current state of the context handlers structure in jetty is taken, some initializations are done, a new handler is added and the reference in jetty is updated.
> 
> However, in the OSGi case the start event for every webapp bundle is added in a separate thread.
> These threads work in parallel and it can happen that they both get a copy of the initial state of the structure, which is empty. Then they both add their handlers in parallel and set the reference in jetty. Obviously, whoever updates it second replaces the first one and causes the first webapp to malfunction.
> 
> We fixed this problem by adding sync blocks in several places in the jetty code, in order to be sure that the adding of the handlers is done sequentially:
> 
> package org.eclipse.jetty.server.handler;
> 
> ContextHandlerCollection.mapContexts - this method is not protected, if it is used by several threads at the same time. It updates the following structure:
> private volatile Trie<ContextHandler[]> _contexts;
> which is used later for handling requests.
> 
> this method is called by HandlerCollection - where there is another structure:
>  private volatile Handler[] _handlers;
> 
> we have added synchronizations where set/get of these _handlers is called.
> 
> We are using:
> JVM: ejre 1.7.0_51
> OSGi: ProSyst mBeddedServer SH 7.5.1
> jetty version 9.1.0.v20131115
> 
> The described problem could occur also in setups without OSGi - anywhere where several installations/initializations of webapps could be triggered in parallel.

On 2014-10-22 18:19:21 -0400, Jan Bartel wrote:

> Ingo,
> 
> FYI we also fixed this osgi-related issue with webapp deployment in jetty-9.2: https://bugs.eclipse.org/bugs/show_bug.cgi?id=427951
> 
> If you were able to run jetty-9.2.3 and produce a patch set based on that code then that may be helpful. 
> 
> Jan

**Comment by joakime** [comment]
Seems like this was fixed in Jetty 9.2.x already.
We've had no complaints of similar issues in the past 4 years since this was filed.
