### ISSUE TITLE
Jetty 9.4.x must depend on javax.websocket 1.0 

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1690]
@joakime, `javax.websocket` should remain at 1.0 for 9.4.x and 1.1 for 10.0, right ?

Current 9.4.x `pom.xml` has a dependency on 1.1.

Also, the `pom.xml` for module `test-jetty-webapp` hardcodes version 1.0, while instead it should inherit from the project `pom.xml`.

**Comment by joakime** [comment]
This can go either way.
Its a minor decision in the grand scheme of things.

Personally, i would like to see the javax.websocket-1.1 support announcement at least.

**Comment by joakime** [comment]
With the rollback of websocket 1.1 in jetty 9.4.x, this is no longer relevant.
