### ISSUE TITLE
WebSocket EndPoint throw-away instantiation

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1691]
`ServerContainer.assertIsValidEndpoint()` instantiates (via the zero-argument constructor) a throw-away WebSocket `EndPoint` to perform validation checks.

`EndPoint`s are created via `ServerEndPointConfig.Configurator.getEndpointInstance()` and application are entitled to use any constructor they want, and omit the zero-argument constructor. This is what CometD does.

I think the validation should be rewritten without instantiating a throw-away `EndPoint`.

**Comment by joakime** [comment]
Yeah, this is bad.

**Comment by joakime** [comment]
This is part of the ServerContainer.addEndpoint() layer, which is tied to the ServletContext init phase.
Which is part of the WebSocket init and DeployException requirements of the JSR.
The existing EndpointFunctions / CommonEndpointFunctions is where this needs to be fixed, and that's a crucial layer between the internal implementation and the end users websocket endpoint.

**Comment by joakime** [comment]
Being fixed in Jetty 10.x (as that's where this behavior started)

**Comment by joakime** [comment]
This has been addressed in the jetty-10.x-websocket branch already.
