### ISSUE TITLE
Annotation scanning should ignore `module-info.class` files

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1692]
If a class has a JDK9 / JPMS specific feature known as `module-info.class`, then this class should never be scanned for annotations by Jetty's bytecode scanner.

To reproduce this bug, include the following classes in the `WEB-INF/lib` of a war file.

`slf4j-api-1.8.0-alpha2.jar`
`log4j-over-slf4j-1.8.0-alpha2.jar`
`jcl-over-slf4j-1.8.0-alpha2.jar`

**Comment by joakime** [comment]
See: https://stackoverflow.com/questions/45311295/slf4j-error-when-starting-jetty-server

**Comment by janbartel** [comment]
Done for jetty-9.4.x.
