### ISSUE TITLE
addXForwardedHeaders() doesn't work with SSL offloading network hardware

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#170]
migrated from Bugzilla [#448964](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448964)
status ASSIGNED severity _normal_ in component _server_ for _9.2.x_
Reported in version _9.2.0.M0_ on platform _PC_
Assigned to: Simone Bordet

On 2014-10-27 10:36:57 -0400, Andrew Brown wrote:

> addXForwardedHeaders() in ProxyServlet always adds X-Forwarded-Proto. In an enterprise where SSL is offloaded at the load balancer (e.g. an F5 LTM) then the request received by Jetty will be detected as insecure when in fact the actual caller is secure. In this scenario it's the load-balancer that sets the proto header.
> 
> Ideally we could configure whether this header is added or not. Also, the current "replace" implementation appears to be flawed anyway. From the HttpRequest class:
> 
> ```
> public Request header(HttpHeader header, String value)
> {
>     if (value == null)
>         headers.remove(header);
>     else
>         headers.add(header, value);
>     return this;
> }
> ```
> 
> headers.remove() only removes the first instance from the ArrayList of headers. If a caller manually sets a header twice then only the first will get removed because in remove(HttpHeader name)...
> 
> ```
>     for (int i=_fields.size();i-->0;)
>     {
>         HttpField f=_fields.get(i);
>         if (f.getHeader()==name)
>             return _fields.remove(i);
>     }
> ```
> 
> ...the return statement breaks out before all headers have been checked.

**Comment by joakime** [comment]
Is this the scenario being described?

```
  (Internet)
     https/tls
  (hardware load balancer / F5)
     http / paintext / with "Forwarded" headers
  (jetty server)
    ProxyServlet
      jetty-client (in ProxyServlet) connection to remote
  (destination server)
```

If so, that would mean the Jetty server was not configured for `SecureRequestCustomizer` to see/use the Forwarded headers from the F5 correctly.

**Comment by joakime** [comment]
Closing this due to lack of details over the past 4 years.
