### ISSUE TITLE
Log Implementation ignored when executing under OSGi

### ISSUE THREAD

**Issue by peterdsdoyle** [eclipse/jetty.project#1706]
When running Jetty (9.4.6.v20170531) under OSGi (Karaf 4.0.7/Felix) container and specifying a particular Log implementation using java parameter  '-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.Slf4j'
This causes the Log implementation to default to 'StdErrLog' as class Loader is unable to find specified logging class.

The problem is caused by the class loader used by default to load the Log implementation. as follows
Log.java -> Loader.loadClass( __logClass);
Loader.java -> Thread.currentThread().getContextClassLoader() == sun.misc.Launcher$AppClassLoader
This class loader is not bundle aware and therefore is unable to find the Log implementations.

if we alter Log.java to use the same classloader as the Log class itself as follows 
Log.java -> Loader.loadClass(Log.class, __logClass);
Loader.java -> loaderClass.getClassLoader() == org.apache.felix.framework.BundleWiringImpl$BundleClassLoaderJava5
This class loader is bundle aware and therefore locates the Log implementations.

**Comment by gregw** [comment]
@janbartel while this seams obvious/harmless, let's chat about this to double check...

**Comment by janbartel** [comment]
@gregw as far as OSGi is concerned, using the classloader of the Log.class will certainly find other classes in the jetty-util jar like Slf4jLog.class. I think this change would also allow someone to potentially supply their own AbstractLogger impl and have it found by making a fragment bundle that exports their class and attaches itself to the jetty-util bundle.

Outside of OSGi-land it would mean that all AbstractLogger impls will need to be on the server classpath, which I think is the case anyway?

**Comment by gregw** [comment]
fixed with 7b5d3b2b5a6ae31ee5ab0c6202c16df311bc6dd1
