### ISSUE TITLE
Specify HTTP authentication for a single request

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#171]
migrated from Bugzilla [#448985](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448985)
status ASSIGNED severity _enhancement_ in component _client_ for _9.2.x_
Reported in version _9.2.3_ on platform _All_
Assigned to: Simone Bordet

On 2014-10-27 12:21:04 -0400, Mikael  Staldal wrote:

> It would be nice if you could add username/password for HTTP authentication for a single Request, without saving it for other requests. That useful if you use the same HttpClient object and need different credentials for different requests.
> 
> It could be a method like this in org.eclipse.jetty.client.api.Request:
> 
> ```
> void addAuthentication(Authentication authentication);
> ```

**Comment by joakime** [comment]
This request seems to be about pre-emptive authentication to a specific request.
The Authentication layer in jetty-client seems to be based on a ResponseListener behavior.
Is this enhancement even compatible with the current jetty-client design?

**Comment by sbordet** [comment]
Updated documentation, this is already possible with the current `HttpClient` APIs.
