### ISSUE TITLE
QueuedThreadPool not exposed on JMX

### ISSUE THREAD

**Issue by lpandzic** [eclipse/jetty.project#1718]
After upgrading from 9.4.5.v20170502 to 9.4.6.v20170531
MBean "org.eclipse.jetty.util.thread.queuedthreadpool" is no longer exposed on JMX althrough
other jetty JMX MBeans are. QueuedThreadPool is still being constructed.
Any thought about what it might be?

**Comment by sbordet** [comment]
We need more evidence.

> QueuedThreadPool is still being constructed

is too vague, as `QueuedThreadPool` is typically the first object being instantiated, and without it nothing else works.

Start with a barebone server and enable the JMX module. Can you see the `QueuedThreadPool` MBean ?

**Comment by lpandzic** [comment]
After more thorough investigation it was determined that jetty wasn't the cause of the issue so I'm closing it.

**Comment by lpandzic** [comment]
After further investigation, I've managed to pinpoint the issue with @wilkinsona.
AFAIK, there is no breaking change on jetty, it simply does not work (on any of the mentioned versions) and this was exposed by spring boot change.
This code reproduces the issue:

```java
public static void main(String[] args) throws Exception {
        Server server = new Server();
        server.addBean(new MBeanContainer(ManagementFactory.getPlatformMBeanServer()));
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(8080);
        server.addConnector(connector);
        server.start();
        checkThreadPoolMBean();
        Connector[] connectors = server.getConnectors();
        server.setConnectors(null);
        checkThreadPoolMBean();
        server.setConnectors(connectors);
        checkThreadPoolMBean();
    }

    private static void checkThreadPoolMBean() throws MalformedObjectNameException {
        ObjectName queuedthreadpool = new ObjectName("org.eclipse.jetty.util.thread:type=queuedthreadpool,id=0");
        try {
            ManagementFactory.getPlatformMBeanServer().getMBeanInfo(queuedthreadpool);
            System.out.println(queuedthreadpool + " was available");
        }
        catch(Exception ex) {
            System.out.println(queuedthreadpool + " was not available");
        }
    }
```
