### ISSUE TITLE
Improved Response Content Handling

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#172]
migrated from Bugzilla [#448999](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448999)
status ASSIGNED severity _enhancement_ in component _client_ for _9.2.x_
Reported in version _9.2.3_ on platform _All_
Assigned to: Simone Bordet

On 2014-10-27 13:46:18 -0400, Mikael  Staldal wrote:

> It would be nice if Jetty client have something like JAX-RS' MessageBodyReader or Spring's HttpMessageConverter. A pluggable component to read the response and convert it into a Java object.
> 
> Comprehensive mapping between Content-Type and Java classes might be a bit overkill, but it would be very nice to at least be able to specify such a ContentConsumer (to make up a name for it) when doing the request.
> 
> Something like this:
> 
> package org.eclipse.jetty.client.api;
> 
> public interface ContentConsumer<T> {
>     T consumeContent(Response response, InputStream contentStream) 
>         throws java.io.IOException;
> }
> 
> public interface Request {
>     // ...
> 
> ```
> // blocking, return when the ContentConsumer is done
> <T> T send(ContentConsumer<T> contentConsumer) 
>     throws InterruptedException, TimeoutException, ExecutionException;
> 
> // asynchronous, execute the ContentConsumer in a background thread
> <T> void send(ContentConsumer<T> contentConsumer,
>               Response.ContentConsumedListener<T> listener);
> ```
> 
> }
> 
> public interface Response {
>     // ...
> 
> ```
> public interface ContentConsumedListener<T> extends ResponseListener {
>     void onContentConsumed(Response response, T content);
> }
> ```
> 
> }
> 
> (For the request, org.eclipse.jetty.client.api.ContentProvider seems to do the job.)

**Comment by sbordet** [comment]
The idea of buffering the response content until the end and then converting it can already be done with `BufferingResponseListener`.
