### ISSUE TITLE
Java 9 version parsing in jetty-start should use JRE classes

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1722]
Currently, the Java version parsing in jetty-start uses a custom parser for Java 8 vs Java 9.

The `java.lang.Runtime.Version` class exists to do this parsing (starting in Java 9) for us.
If that class exists, we should use it, not our custom parsing code.

**Comment by gouessej** [comment]
java.lang.Runtime.getRuntime().version().major() returns 9 when using Java 1.9.

**Comment by sbordet** [comment]
@joakime seems a lot of additional work to use reflection to invoke the JDK 9 APIs, versus just using what we already have. The spec for parsing JDK 9 versions is clear, so.

**Comment by gregw** [comment]
I think we should delay switching until we have a release that only runs on jdk9.

**Comment by sbordet** [comment]
Jetty 10.0.x will not be based on JDK 9 (will still be compatible with JDK 8 to support JEE 8), so this is not going to happen soon.
See also #1814.
