### ISSUE TITLE
Module files should have DO NOT EDIT comments

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#173]
migrated from Bugzilla [#449508](https://bugs.eclipse.org/bugs/show_bug.cgi?id=449508)
status ASSIGNED severity _normal_ in component _start_ for _9.2.x_
Reported in version _9.2.3_ on platform _All_
Assigned to: Joakim Erdfelt

On 2014-10-31 15:04:48 -0400, Joakim Erdfelt wrote:

> Module files should have a comment near the top saying
> 
> DO NOT EDIT
> Want customization?
> Use a {jetty.base}, you'll thank us later.
> See documentation: <url>

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch do we have a suitable doc page we could link to in a comment like this?

*.mod file:
# DO NOT EDIT (see http:// foo )

**Comment by WalkerWatch** [comment]
@jmcc0nn3ll We have warnings in various sections that state: "Jetty Home should always be treated as a standard of truth. All configuration modifications, changes and additions should be made in the appropriate Jetty Base directory."  I will add a similar note [here](https://www.eclipse.org/jetty/documentation/current/startup-modules.html#startup-configuring-modules) to reinforce the idea.

**Comment by jmcc0nn3ll** [comment]
Oh my, looks like I stumbled over some markdown in my example :)

Yeah, if we have a solid URL to point to we can add a note in each of the .mod files and close this issue out.
