### ISSUE TITLE
AuthenticationProtocolHandler - copyRequest

### ISSUE THREAD

**Issue by StenKnudsen** [eclipse/jetty.project#1730]
Hello all.
I have a Websocket client with a AuthenticationStore, holding a Basic Auth, that makes a http request to a server. 
The server challanges and requires Basic Auth. 
The client then looks through the AuthenticationStore and find the required auth. 
Then the problem appears. In line 161 in the org.eclipse.jetty.client.AuthenticationProtocolHandler -> Request newRequest = client.copyRequest(request, requestURI); 
The copyRequest returns a new org.eclipse.jetty.client.api.Request which is not an instance of either WebsocketUpgradeRequest or HttpConnectionUpgrader, which is required when upgrading to a websocket in the org.eclipse.jetty.client.http.HttpChannelOverHTTP exchangeTerminating method.

Do you know of any workaround ?

Sincerely
Sten

**Comment by sbordet** [comment]
@joakime I don't understand this ? `WebsocketUpgradeRequest` should just be a wrapper that is created _after_ the 101 response, so I don't see how it would impact the upgrade ?

**Comment by joakime** [comment]
WebSocketUpgradeRequest is created before the 101 is received.  It holds all of the HTTP side behavior and then performs the actual AbstractWebSocketConnection upgrade once it verifies a 101 and its headers are accurate. 

It serves both the standard HTTP layer, and the WebSocket Handshake, everything after the 101 is no longer jetty-client.

**Comment by sbordet** [comment]
@joakime do we have a test case that replies with a 401 and then with a 101 like reported by the OP ?

**Comment by StenKnudsen** [comment]
Additional the AuthenticationProtocolHandler class only supports basic www-authenticate responses, see

Line 35
rivate static final Pattern AUTHENTICATE_PATTERN = Pattern.compile("([^\\s]+)\\s+realm=\"([^\"]*)\"(.*)", 2);

if a WWW-Authenticate: Negotiate is received, it does not match the above patteren.

The initial issue I have bypassed by implementing my own HttpClient only overriding the copyRequest to return the same WebsocketUpgradeRequest if instanceof else calling super.

The second issue mentioned above in this comment i have implemented my own WWWAuthenticationProtocolHandler and overwriting the getResponseListener and 'hacks' the WWW-Authenticate: Negotiate header to include a default realm, so the response is handled correctly. Not pretty, but it works.

Sincerely

**Comment by joakime** [comment]
Fixed in Issues ##2875 and #2901
