### ISSUE TITLE
Keep eclipse logging setup

### ISSUE THREAD

**Issue by juhaszPeterDev** [eclipse/jetty.project#1731]
Hi!
I have a project configured in eclipse that uses logback-logstash-encoder and it works well without deployment. As a .war file this is naturally different, as stated in the documentation the deployement manager will configure a different logging tool. My question is: can I somehow keep the original setup that uses a logging.properties file and a logback.xml file for logging?

**Comment by joakime** [comment]
If your logging jars/libs and configuration files (`logging.properties`?) are in your WAR you are set.
Standard Servlet webapp isolation kicks in and your webapp will log its own events to the configuration within your webapp.

Server logging is separate from webapp logging, always has been.
If you want server logging to use logback + logstash + encoder then you'll need the logging jars and configuration ALSO at the server level. (Be careful to not log to the same file from both locations).

**Comment by msimple** [comment]
Sorry, that close was an accident, i can properly reply on monday.

**Comment by msimple** [comment]
The war file has the following contents:
...
WEB-INF/classes/logging.properties
WEB-INF/classes/logback.xml
...
WEB-INF/lib/logback-core-1.1.8.jar
WEB-INF/lib/logback-classic-1.1.8.jar
WEB-INF/lib/slf4j-api-1.7.25.jar
WEB-INF/lib/jul-to-slf4j-1.7.25.jar
WEB-INF/lib/logstash-logback-encoder-4.7.jar
...
In the logging.properties file I'm changing the jul handler, can that be the problem?
Server logging is working, no problems there.

**Comment by msimple** [comment]
I made a hello world webapp that logs a message on initialization.
[web-sample.zip](https://github.com/eclipse/jetty.project/files/1222207/web-sample.zip)
It still won't use a different configuration.

(note: for some reason I couldn't run it in eclise as jetty, it didn't see the linked maven libraries, but I applied scenario 1 from here:
http://jetty.4.x6.nabble.com/Usage-of-JUL-to-SLF4J-td4958903.html
and that solved the missing class errors)
