### ISSUE TITLE
Consider sorting webapp classloader urls so classpath order is consistent.

### ISSUE THREAD

**Issue by bmenasha** [eclipse/jetty.project#1742]
See java.org.eclipse.jetty.webapp.WebAppClassLoader.addJars

String[] files=lib.list();
for (int f=0;files!=null && f<files.length;f++)
{
....
    addClassPath(jar);
 }

The order jars are added to the classpath is undefiend as File.list order is undefined https://docs.oracle.com/javase/7/docs/api/java/io/File.html#list()

The Section 4.6 of the servlet specification also says jars are loaded in an undefined order ( http://download.oracle.com/otn-pub/jcp/servlet-3.0-fr-eval-oth-JSpec/servlet-3_0-final-spec.pdf). 

But this vauge ordering causes problems when applications are deployed to systems with a different file system that have unexpected directory order of files. 

It seems to me that it would be better to sort this list so Jetty is always consistent in it's loading order regardless of the filesystem used by the host. I've seen Jetty in a docker container change directory order even from docker running on localhost and the image deployed to a remote host. 
Since this is a backwards incompatible change a flag gating the behavior might be wise. 

Thanks for considering.

**Comment by joakime** [comment]
What order?
FileSystem order?
File Path order?
Filename order?
ASCII order?
Natural sort?
Charset sort? (which charset origin?)
Does case matter?
Do symlinks matter?
What about encoded characters? if so, what encoding should be decoded? and which ones shouldn't?

As you can see, there is a reason that no java.lang.ClassLoader implementation provides a search order. 
The java.lang.ClassLoader itself has no facility to provide a search order, the only thing that Java honors is the parent/child search order of delegated ClassLoaders (which is backwards from the Servlet spec btw)

Even the API for java.lang.ClassLoader shows that you can only get answers in an unsorted fashion (Enumeration, not Iterator).

This kind of behavior is an anti-pattern for Java.
If you have an application that relies on this you will always have this issue.

Note: The upcoming Java 9 release makes this ClassLoader behavior even more complicated, as it creates a bunch of ClassLoader for each level of the module system that is present, and it is ultimately in charge of the classloading (which has no order within a ClassLoader)

**Comment by joakime** [comment]
> Since this is a backwards incompatible change a flag gating the behavior might be wise.

There is no version of Jetty that had support in WebAppClassLoader for some kind of sorted/predictable search order in the same ClassLoader.
If you experienced such a phenomena, it was likely by coincidence, not intentional.

Also note, that there is a delegated search order as prescribed in the Servlet 3 specs related to web fragments (`web-fragment.xml`) and the resolved descriptor, and web resources (aka `WEB-INF/lib/*.jar!/META-INF/resources/`), but not classes.

Perhaps you can still achieve your desired end result with some use of the web-fragment ordering concepts and ServletContext attributes in the effective web descriptor to achieve whatever behavior you are striving for.

**Comment by bmenasha** [comment]
Thanks joakime.   I was thinking any order... doesn't much matter as long as it's consistent. Using directory order (the current code) isn't consistent as the directory order changes when the filesystem changes. 

But I can understand if there is an objection as I agree applications shouldn't depend on a consistent ordering if ordering is undefined.  Just thought it would be more user friendly if it was easy to be consistent. Fine to close this. thanks

**Comment by joakime** [comment]
@bmenasha what in your code is relying on order?  Perhaps there is a Java (or Servlet) specific way to accomplish your desired end result?

**Comment by bmenasha** [comment]
@joakime  I understand it's a bug that the application depended on an order and it was simple to correct (cleaned-up the jars in WEB-INF/lib so that the jars containing the unexpected class versions no longer contain unexpected class version/deleting jars containing invalid versions).  It was just troubling this problem didn't turn up in any non-production environment. If Jetty had a consistent order despite changes in filesystem type the problem would have occured in other envrionments and not first in production. 
thanks

**Comment by joakime** [comment]
Also of note, the other containers that used to provide this kind of behavior have dropped it in the recent past as well.

* Tomcat 8 no longer does it - https://bz.apache.org/bugzilla/show_bug.cgi?id=57129
* DSpace had to update as well - https://jira.duraspace.org/browse/DS-2437
