### ISSUE TITLE
Timeout scanning annotations : when start project with jetty，i got follow  question.

### ISSUE THREAD

**Issue by danshijin** [eclipse/jetty.project#1748]
<h3>im using jetty server (9.4.6.v20170531), and i get this.</h3>
<code>java.lang.Exception: Timeout scanning annotations

	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:494)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:363)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1458)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
</code>
i have tried add <h3><code>metadata-complete="true"</code></h3> in web.xml,but it did not work.
<h3>i follow the source code, then i found bellow in org.eclipse.jetty.annotations.AnnotationConfiguration</h3>
<code>
createServletContainerInitializerAnnotationHandlers(context, getNonExcludedInitializers(context)); // cause _classInheritanceHandler & _containerInitializerAnnotationHandlers to be not empty

       if (!_discoverableAnnotationHandlers.isEmpty() || _classInheritanceHandler != null || !_containerInitializerAnnotationHandlers.isEmpty()) // _discoverableAnnotationHandlers is empty as the metadata-complete set to be true
           scanForAnnotations(context);
</code>

**Comment by janbartel** [comment]
@danshijin if your webapp contains one or more jars that have an implementation of the ServletContainerInitializer interface with an @HandlesTypes annotation, then as per the servlet specification, we need to scan your entire webapp.   

By default, we will wait up to 60sec for the scanning to complete. Your options are to set the timeout to be longer, or to evaluate whether your code is really relying on the that ServletContainerInitializer - sometimes they can be present in a jar in WEB-INF/lib but not used by the application. In that case you can control which jars will be scanned, and potentially skip the jar with the unnecessary ServletContainerInitializer.  This documentation page explains all of the above and how to configure it: http://www.eclipse.org/jetty/documentation/9.4.6.v20170531/using-annotations.html
