### ISSUE TITLE
PathWatcher DepthLimitedFileVisitor doesnt implement FileVisitor.visitFileFailed

### ISSUE THREAD

**Issue by dellgreen** [eclipse/jetty.project#1754]
When using HashLoginService with hot-reload set to true, can get AccessDeniedException if  something in the same directory as the configfile doesnt have correct permissions. It would be better if FileVisitor.visitFileFailed was overridden to not fail the whole process as user is only interested in the config file set being watched for changes and is not aware that config file parent directory is being file walked.

The situation came to light in a java unit test that was creating a config file in the tmp directory on linux, which obviously has other files/dirs in there with different permissions. Unit test fixed by creating a tmp directory in /tmp with correct permissions to hold the config file. However it could happen in production code

[PathWatcher.java](https://github.com/eclipse/jetty.project/blob/71d5fcf246034dce91cd642d35cdbaace9806329/jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java#L480)

**Comment by joakime** [comment]
Seems like ignoring failures would hide legitimate errors that need to be communicated. Hmm..

**Comment by dellgreen** [comment]
could errors be logged instead?  user is not expecting the failure as they only have the option to set path to a single config file. They are not expecting exceptions thrown for to unrelated things in the same directory as the config file they specified? :)

**Comment by dellgreen** [comment]
Maybe a better way to go is for PropertyUserStore to subClass PathWatcher and override the 
prepareConfig (final Config baseDir) throws IOException
method and add an exclude regex pattern that is everything that is not the config file path and then call super.prepareConfig at the end of the method with update Config instance?

**Comment by dellgreen** [comment]
Ok Looks like i have found the possible problem. It looks like PathWatcher 'prepareConfig' method is not honouring the provided config parameter's recurseDepth value which is zero when used with a single file path. By not honouring whats been requested it results in Files.walkFileTree defaulting to Integer.MAX_VALUE for a single file path, causing it to query directories in the basedir which it shouldnt.

[PathWatcher](https://github.com/eclipse/jetty.project/blob/71d5fcf246034dce91cd642d35cdbaace9806329/jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java#L965)

Have tested a fix but this seems to break a test in PropertyUserStore which i need to investigate, as either I have misjudged whats going on or the failing test isnt quite correct.

**Comment by dellgreen** [comment]
Appears a recursedepth of zero does not produce events for PropertyUserStore changes to the config file whilst a recurse depth of 1 does, whilst also preventing recursing into sub directories of the config file parent

**Comment by gregw** [comment]
FYI I've also started looking at some PathWatcher issues in #1200, so perhaps it needs a bit of an overhaul

**Comment by dellgreen** [comment]
Ok cool, would you like me to go ahead and produce a fix and pull request, or hold fire until all PathWatcher is overhauled?

**Comment by gregw** [comment]
Dell, if you have some time,, then writing a new test method on the unit test that reproduces your exact problem would be worthwhile.  I'll rewrite some of the internals in the next day or two before I look at your exact issue.

**Comment by dellgreen** [comment]
ok, no problem

**Comment by gregw** [comment]
@dellgreen - I have a refactored PathWatcher in branch jetty-9.4.x-1200.  It would be great if you could test against your specific use case.

**Comment by dellgreen** [comment]
ok cool.

**Comment by dellgreen** [comment]
Greg, I have submitted a test, which highlights the problems on linux and mac, doesnt seem to have the problem on windows, although that is probably more about the permissions model and the new test than the underlying code as i dont use windows to know what a an equivalent test woudl be to produce the same error

**Comment by dellgreen** [comment]
Instead of setting permissions in the test, it might be better to be have a way to observe what is being iterated over when pathwatcher registertree method is called as its failing on         
`Files.list(dir).forEach(p->...`

**Comment by gregw** [comment]
Thanks for the test.  I think it demonstrates that the PathWatcher approach is fundamentally broken in the JVM,  as it is throwing (and/or reporting if the private file is created after start) non call stack exceptions for private files discovered.

Thus I think we need to really consider if it is worthwhile using the watcher mechanism and perhaps a scanner approach is best.

**Comment by dellgreen** [comment]
ok, glad it was helpful :)

**Comment by sbordet** [comment]
Fixed in #1900 and #4239.

**Comment by dellgreen** [comment]
thankyou :)
