### ISSUE TITLE
Clarify javadoc for WebSocketPolicy Max Text & Binary Size

### ISSUE THREAD

**Issue by MIOB** [eclipse/jetty.project#1756]
In [documentation for WebSocketPolicy](https://github.com/eclipse/jetty.project/blob/a7e8b4220a410b85c843bffcd13f07d70f1b3fe8/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java#L230) it is written that maxTextSize should affect both text message parsing and generating. So it sounds like it should take care both sending and receiving messages. But actually it affect only received messages. So I think javadoc should be clarified.

**Comment by joakime** [comment]
It is a memory limit concern.
It only applies to received whole text messages, or received partial text messages.
It does not apply to sending of any format text message.
It also does not apply to the use of streaming (Reader, Writer) use to handle text messages.

I'll update the javadoc.
