### ISSUE TITLE
the cpu jump ！！

### ISSUE THREAD

**Issue by topno3rpg** [eclipse/jetty.project#1764]
use  jetty   9.3.0.M1
start jetty
when i do  curl http://localhost:21411/index.jsp
the cpu jump too high  and not down !
but when i use chrome , it do not happen.
![image](https://user-images.githubusercontent.com/8730710/29612877-080e0bbe-8836-11e7-851b-4bc06808b328.png)

**Comment by sbordet** [comment]
Please updated Jetty to the latest version. Releases with the "M" are beta and may be broken.
