### ISSUE TITLE
RemoteEndpoint.sendBytes() changing ByteBuffer content.

### ISSUE THREAD

**Issue by johnnyleitrim** [eclipse/jetty.project#1765]
Using the example on the [Jetty WebSocket Client API page](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-websocket-client-api.html), I changed the `SimpleEchoSocket. onConnect()` method to use `RemoteEndpoint.sendBytes()`.

However, I can see that the ByteBuffer content has changed after using the `sendBytes` method.  This causes problems if you want to do other things with the byte buffer after sending (for example, calculating checksum of a file you're sending).  I changed the method to this:
```java
    @OnWebSocketConnect
    public void onConnect(Session session) {
        System.out.printf("Got connect: %s%n", session);
        this.session = session;
        try {
            for (int i = 0; i < 10; i++) {
                ByteBuffer buffer1 = ByteBuffer.wrap("Hello".getBytes());
                System.out.print(DatatypeConverter.printHexBinary(buffer1.array()));
                session.getRemote().sendBytes(buffer1);
                System.out.println(" - " + DatatypeConverter.printHexBinary(buffer1.array()));
            }
            ByteBuffer buffer2 = ByteBuffer.wrap("Thanks for the conversation.".getBytes());
            session.getRemote().sendBytes(buffer2);

            session.close(StatusCode.NORMAL, "I'm done");
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
```
And I see the following output for the buffer printouts:
```
48656C6C6F - F2DB42A6D5
48656C6C6F - EDE07245CA
48656C6C6F - 6921164B4E
48656C6C6F - 1D202E543A
48656C6C6F - DDC4F81FFA
48656C6C6F - A97283F38E
48656C6C6F - 815B8ED4A6
48656C6C6F - E55ECBDCC2
48656C6C6F - 89567C8BAE
48656C6C6F - A279A2B685
```

The buffer is always a different (random?) value after `sendBytes()` has executed.  What is the cause of this?
[jetty-websockets-example.tar.gz](https://github.com/eclipse/jetty.project/files/1246160/jetty-websockets-example.tar.gz)

I've attached a sample maven project with the code.

**Comment by joakime** [comment]
That is correct.

You do not own the ByteBuffer once you hand it off to the RemoteEndpoint.
The implementation is free to change the positions, limits, contents, etc..

As to why the bytes change, that's because in a WebSocketClient scenario the bytes are masked per RFC6455 before being sent.

WebSocket extensions can also change the contents of the ByteBuffer to suite the requirements of the extension.

If you need to perform some operations on the websocket payload data, you should do so before you give the ByteBuffer (or byte[]) to the RemoteEndpoint.

**Comment by johnnyleitrim** [comment]
Thanks for the quick reply @joakime - I think it would be useful if the javadoc/documentation stated that.  I spent ages thinking there was a bug in my code.
