### ISSUE TITLE
Remove spammy Executor output

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1767]
Running the server and test cases produces thousands of lines of the following output ...

```
### Executor: org.eclipse.jetty.util.thread.ReservedThreadExecutor@30c7da1e{s=1,p=0}
```

Seems like a System.err debug somewhere that needs to be removed.

**Comment by sbordet** [comment]
@joakime those logs come from classes:

- `org.eclipse.jetty.websocket.jsr356.DelayedStartClientTest`
- `org.eclipse.jetty.websocket.jsr356.server.DelayedStartClientOnServerTest`

Recent additions by you :wink:

**Comment by joakime** [comment]
really? doh!
