### ISSUE TITLE
Utility class for encoding 'Set-Cookie' values

### ISSUE THREAD

**Issue by bjorncs** [eclipse/jetty.project#1769]
Hi,

`org.eclipse.jetty.server.Response` in `jetty-server` provides logic for encoding cookies for the _Set-Cookie_ header (`addSetRFC2965Cookie`/`addSetRFC6265Cookie`).  It would be useful to have the encoding logic in a separate utility class in `jetty-http` or `jetty-util`.

**Comment by joakime** [comment]
This work has already been started in issue #1551 for Jetty 10.x
