### ISSUE TITLE
IllegalStateException: Closed with pending callback

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#177]
migrated from Bugzilla [#452673](https://bugs.eclipse.org/bugs/show_bug.cgi?id=452673)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.2.3* on platform *PC*
Assigned to: Greg Wilkins

On 2014-11-21 11:01:15 -0500, Gili wrote:

> I'm getting the following exception:
> 
> 10:30:39.025 [qtp119636033-496] WARN  org.eclipse.jetty.server.HttpChannel$CommitCallback.failed() - Commit failed
> java.lang.IllegalStateException: Closed with pending callback org.eclipse.jetty.server.HttpConnection$SendCallback@2e98eb2e[CLOSED][i=ResponseInfo{HTTP/1.1 204 No Content,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@1736e96f]
> 	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:397)
> 	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:429)
> 	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:330)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.destroyEndPoint(SelectorManager.java:749)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint.close(SelectChannelEndPoint.java:169)
> 	at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:225)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.closeNoExceptions(SelectorManager.java:713)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.access$1100(SelectorManager.java:406)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector$EndPointCloser.run(SelectorManager.java:1020)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> I believe that the server is being shut down while another thread is closing a connection. I don't believe I am doing anything wrong from an end-user point of view. I expect the server to detect this race condition and shut down gracefully.

On 2014-11-26 22:20:48 -0500, Greg Wilkins wrote:

> Gill,
> 
> are you still seeing this on the latest release? 9.2.5?

On 2014-11-26 23:48:52 -0500, Gili wrote:

> Greg,
> 
> I'll switch over to 9.2.5 and we'll see if I run into this over the next week.

On 2014-12-02 23:31:41 -0500, Gili wrote:

> Greg,
> 
> I don't see the original exception but I just got this exception which I believe is related (in 9.2.5):
> 
> 23:27:53.300 [qtp1753415235-190] WARN  org.glassfish.jersey.server.ServerRuntime$Responder.release() - Attempt to release request processing resources has failed for a request.
> org.glassfish.jersey.server.ContainerException: I/O exception occurred while sending "415/Unsupported Media Type" error response.
> 	at org.glassfish.jersey.servlet.internal.ResponseWriter.commit(ResponseWriter.java:202)
> 	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:413)
> 	at org.glassfish.jersey.server.ServerRuntime$Responder.release(ServerRuntime.java:717)
> 	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:445)
> 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
> 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
> 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
> 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
> 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
> 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:497)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.nio.channels.ClosedChannelException: null
> 	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:459)
> 	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:429)
> 	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:330)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.destroyEndPoint(SelectorManager.java:749)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint.close(SelectChannelEndPoint.java:169)
> 	at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:225)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.closeNoExceptions(SelectorManager.java:713)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.access$1100(SelectorManager.java:406)
> 	at org.eclipse.jetty.io.SelectorManager$ManagedSelector$EndPointCloser.run(SelectorManager.java:1020)
> 	... 3 common frames omitted
> 
> Does this help you understand what is going on? I'm guessing the server is being shut down while attempting to flush its output.

**Comment by joakime** [comment]
Jersey received an error, and when attempting to send a `415/Unsupported Media Type` it couldn't as the response was already committed.
This is standard behavior of Servlet spec.
Closing.
