### ISSUE TITLE
Allow for common resource use in heavy WebSocket usage scenarios

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1775]
Currently, if you have many webapps deployed, each with JSR356 enabled, the Client based `WebSocketContainer` accessed via [`javax.websocket.ContainerProvider.getWebSocketContainer()`](http://docs.oracle.com/javaee/7/api/javax/websocket/ContainerProvider.html#getWebSocketContainer--) will cause a fresh set of resources to be created each and every time that command is accessed.

This includes some heavyweight components like:
 * Executor / ThreadPool
 * BufferPool

There should be some mechanism to allow for tweaking the JSR356 standard behavior to minimize this excessive resource utilization.

**Comment by joakime** [comment]
At a minimum, the following features exist in the Jetty implementation of `javax.websocket.ContainerProvider` currently in Jetty 9.4.6+.

* `JettyClientContainerProvider.setUseSingleton(boolean)` - default: false - this will break the JSR356 api to always return a singleton of the `WebSocketContainer` (the API contract states that a new container is created each time that is called).
* `JettyClientContainerProvider.setUseServerContainer(boolean)` - default: false - this will cause [`javax.websocket.server.ServerContainer`](http://docs.oracle.com/javaee/7/api/javax/websocket/server/ServerContainer.html) to be returned when using `ContainerProvider.getWebSocketContainer()` on a servlet environment, from a thread that has an active ServletContext threadlocal allowing the server container to be accessed.

These configurations on `JettyClientContainerProvider` :

_Pros:_
 * Using `JettyClientContainerProvider.setUseSingleton(true)` prevents new resource creation on repeated use of `ContainerProvider.getWebSocketContainer()` from within the same classloader. (this applies to both forms of use: non-webapp standalone, and webapp usage)
 * Using `JettyClientContainerProvider.setUseServerContainer(true)` prevents new resource creation on repeated use of `ContainerProvider.getWebSocketContainer()` from within a webapp.

_Cons:_
 * In a multiple webapp scenario, each webapp still has its own Client `WebSocketContainer` with its own set of resources (the `WebSocketContainer` will probably have to live as an instance in each webapp, due to API needs: Decoders / Encoders / EndpointConfigs / Endpoint metadata / etc)
 * No sharing of Executor / ThreadPool for many webapps
 * No sharing of BufferPool for many webapps


The 2 boolean configuration features in `JettyClientContainerProvider` above were created to address a variety of concerns seen within a single classloader. (be it a standalone java application without webapps, and a server with a webapp)

However, as these features were being worked on, a new variant of this core resource concern was reported to us with the usecase of many deployed webapps on the same server.  In an example environment with 20 webapps deployed, each with websocket enabled and needed, there was an explosion of threads allocated (reports indicate over 1,000 new threads, all idle at startup).  This is because each webapp created their own `ServerContainer` (which extends `WebSocketContainer`), each with their own Executor, which caused a bunch of new threads to be preallocated for that specific webapp.

It was asked if there could be a way to change this behavior to use a common Executor instead of each webapp having its own new Executor.

An effort was started with Jetty 9.4.6 to try to address this by focusing on the tree of components involved.

1. `javax.websocket.serverServerContainer`
2. `org.eclipse.jetty.websocket.jsr356.server.ServerContainer`
 a. `org.eclipse.jetty.websocket.server.WebSocketServerFactory`
 b. `org.eclipse.jetty.websocket.server.WebSocketServerConnection`
3. `javax.websocket.WebSocketContainer`
 a. `org.eclipse.jetty.websocket.jsr356.ClientContainer`
 b. `org.eclipse.jetty.websocket.client.WebSocketClient`
 c. `org.eclipse.jetty.client.HttpClient`

The Executor is needed for:
 * Local endpoint Streaming read behaviors
 * WebSocketServerFactory - held for WebSocketServerConnection creation
 * WebSocketClient - held for WebSocketClientConnection creation
 * New client connection establishment
 * HttpClient

The BufferPool is needed for:
 * WebSocket Extensions
 * WebSocket Parser
 * WebSocket Generator
 * WebSocketServerFactory - held for WebSocketServerConnection creation
 * WebSocketClient - held for WebSocketClientConnection creation
 * Local endpoint whole message handling
 * HttpClient

At this point, it was identified that other components should also be investigated:
 * Scheduler
 * SslContextFactory

A partial solution was attempted that would address a portion of this concern at the Client `WebSocketContainer` level.

All forms of JSR356 Client usage needed to be addressed:
``` java
WebSocketContainer container = ContainerProvider.getWebSocketContainer();
WebSocketContainer container = (WebSocketContainer) servletContext
                            .getAttribute("javax.websocket.server.ServerContainer");
ServerContainer container = (ServerContainer) servletContext
                            .getAttribute("javax.websocket.server.ServerContainer");
```

It was felt that the changes made as a result of Issue #155 to allow for configuring the Http layer for the JSR356 Client could just be reused to accomplish this by defining a `jetty-websocket-httpclient.xml` webapp resource that is used to build/configure the HttpClient used by the WebSocketClient, leaving it up to the XML to pull the HttpClient from the appropriate places.

An extra feature on the Server side's `javax.websocket.server.ServerContainer` initialization was added to attempt to pull a pre-built HttpClient from the webapps ServletContext attributes, and then the Server attributes as another choice to configure the HttpClient used by the WebSocketClient side.

Upon a code review, this server side effort was not implemented properly and is essentially a no-op.

The code review also shows that these partial efforts are not really addressing the core concern with common resources properly.   A new solution needs to be identified for this.

**Comment by joakime** [comment]
If we focus on the Executor concern alone, we have the following places to address.

* Server Container use
* Server Connection use (for creating connections)
* Client Container use
* Client Connection use (for creating connections)
* Local Endpoint Streaming read use

The Server and Client containers themselves do not use the Executor directly, but instead hand it off to other components to use.

The Client Container uses the executor for the HttpClient creation, and also the WebSocketUpgradeRequest (implements HttpClient's HttpRequest) creation for each connection attempt, which uses the Client Container executor to create the Client Connections.

The Server Container uses the executor to create Server Connections.

Both the Client Container and Server Container hand off the executor to the SessionFactory for Session creation.

The Session hands off the executor to the Local Endpoint.

The Local Endpoint hands off the executor to the message handling that has asked to receive messages in a streaming form.  A newly dispatched thread calls the Local Endpoint implementation's onMessage() method with the stream object.

**Proposal:**

When `WebSocketServerFactory` is created, its Executor is the same one that the Server uses.
This will affect the JSR356 `ServerContainer` as well.

Said another way: If a JSR356 `WebSocketContainer` (this includes `ServerContainer` as well) is created within the context of a Jetty `ServletContextHandler`, then the Executor used is the server one, otherwise it is a new Executor.

By default, the Executor used by `WebSocketClient` is used to create the `HttpClient`
By default, the Executor used by `WebSocketUpgradeRequest` to create the Client Connection is the same one that `HttpClient` is using.

**Comment by gregw** [comment]
I'm generally +1 on sharing the container executor for standard services that the container provides.  If the JSR means that we must provide a WebSocket client (and thus an internal HttpClient), then it should indeed use the containers executor, so that the user need only configure a single pool.

If the application explicitly configures a HttpClient themselves, then I think the default should be a new executor.

**Comment by joakime** [comment]
Closing. This has been implemented already.
