### ISSUE TITLE
Provide Proxy Support on JSR WebsocketClient

### ISSUE THREAD

**Issue by srmo** [eclipse/jetty.project#1776]
Ahoi,

is it already possible to do this? In [this](https://stackoverflow.com/questions/32785018/configuring-jetty-websocket-client-to-use-proxy) thread from May 2017 it says that it would require me to add 
an issue here. The search on github didn't bring it up, so here we go :)

Trying to use the java vm properties to configure a non-transparent proxy doesn't work, i.e. the proxy settings aren't honored by the Websocket connection.
We are using the JSR WebsocketClientEndpoint (Annotated Endpoint Class) on Java 8 current, using jetty 9.4.5.v20170502 in a Spring container 4.3.8.RELEASE

**Comment by joakime** [comment]
A preliminary feature for this was added in Jetty 9.4.6, it isn't really complete, as there's 3 different ways to access a client in JSR356.  The feature added addresses only 1 of those access points.  (this is being addressed in Jetty 9.4.x currently, hopefully it will be addressed in time for the 9.4.7 release).

Consider these 3 ways to access a container suitable for using JSR356's `connectToServer()` methods.

```java
WebSocketContainer container = ContainerProvider.getWebSocketContainer();
WebSocketContainer container = (WebSocketContainer) servletContext
                            .getAttribute("javax.websocket.server.ServerContainer");
ServerContainer container = (ServerContainer) servletContext
                            .getAttribute("javax.websocket.server.ServerContainer");
```

We have a solution for the first one, but not the other 2 at the current time.

The current solution requires the creation of a `jetty-websocket-httpclient.xml` which dictates how you want the HTTP layer for your WebSocket client to behave (including connect timeouts, cookie stores, authentication, proxies, etc...)

An example of the contents of this file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.client.HttpClient">
  <Arg>
    <New class="org.eclipse.jetty.util.ssl.SslContextFactory">
      <Set name="trustAll" type="java.lang.Boolean">false</Set>
      <Call name="addExcludeProtocols">
        <Arg>
          <Array type="java.lang.String">
            <Item>TLS/0.1</Item>
          </Array>
        </Arg>
      </Call>
    </New>
  </Arg>
  <Set name="connectTimeout">5555</Set>
  <Set name="executor">
    <New class="org.eclipse.jetty.util.thread.QueuedThreadPool">
      <Set name="name">XmlBasedClient@</Set>
    </New>
  </Set>
</Configure>
```

We could use some feedback on this.  Let us know if this is a sane solution, or not.

**Comment by srmo** [comment]
Amazing! Thanks for the quick feedback. We will give this a try in the coming days.

**Comment by srmo** [comment]
PS: for what it's worth, we are using embedded jetty with programmatic configuration and if I'm not mistaken we use the first option to aquire the container.

**Comment by joakime** [comment]
Since you are using the first approach, you might want to pay attention to Issue #1775 for some other goodies that are available to you.

**Comment by srmo** [comment]
@joakime 
I'm now using this rather crude approach
`<Configure class="org.eclipse.jetty.client.HttpClient">
  <Get name="proxyConfiguration">
      <Get name="proxies">
        <Call name="add">
          <Arg>
            <New class="org.eclipse.jetty.client.HttpProxy">
              <Arg type="String">localhost</Arg>
              <Arg type="Integer">8080</Arg>
            </New>
          </Arg>
        </Call>
      </Get>
  </Get>
</Configure>`

This has the websocket use the correct HttpClient and proxy now.

Then I hit the next wall. I'm currently testing with Squid and figured, that Squid doesn't support the Upgrade Request model (I'm still very new to this topic so I might get things wrong).
Looking at http://lists.squid-cache.org/pipermail/squid-users/2017-January/013953.html

> WebSockets has several ways to initiate connections:
> 
> 1) native WebSocket port
>   - requires any intermediary has native Websocket support
> 
> 2) CONNECT tunnel (maybe with Upgrade)
>   - requires only that the intermediary has HTTP CONNECT support
> 
> 3) GET request with Upgrade
>   - requires that the intermediary has both HTTP Upgrade and WebSockets 
> native support
> 
> 
> Squid supports method #2.
> 
> The transaction you are showing as broken is mechanism #3. Both the 
> Upgrade and WebSockets support requirements are not existing in Squid.
> 
> That particular request going through a non-WebSockets proxy is supposed 
> to be passed to the server as a regular GET request (without Upgrade). 
> Exactly what Squid does. The server itself is producing the 400 response 
> instead of using alternative things like HTTP long-polling in place of 
> WebSockets. That is its choice, nothing to do with Squid and a perfectly 
> valid choice on the servers part.

Any suggestions on what to do here? Is there even a way to have Jetty use other means to connect to a websocket or is this rather a "Setup a different Proxy Server" thing?

**Comment by srmo** [comment]
PS: it works when using SSL connection, so the issue is only with plain HTTP handshake

**Comment by srmo** [comment]
Ok, this approach can be a workaround for now in 9.4.6.v20170531
It's a bit cumbersome as on how to provide the SSLContextFactory with the correct keystore properties which are usually injected into our Spring DI container. We would now have to resort to this manual XML fiddling. But glad seeing you working on it!

**Comment by srmo** [comment]
@joakime we consider using the programatic approach. JSRWebSocketClientEndpoint is our JSR annotated ClientEndpoint instance which will then call container.connect(instance, url) internally: 
`final JSRWebSocketClientEndpoint clientEndpoint = new JSRWebSocketClientEndpoint(config);

        SslContextFactory ssl = new SslContextFactory();
        ssl.setTrustAll(true);
        ssl.setNeedClientAuth(true);
        ssl.setKeyStorePath(authKeystoreFile);
        ssl.setKeyStorePassword(authKeystorePasswd);
        ssl.setKeyManagerPassword(authKeyPasswd);

        HttpClient httpClient = new HttpClient(ssl);
        httpClient.setUserAgentField(new HttpField(HttpHeader.USER_AGENT, "foobalistic"));
        /** we can now add all the proxy config here **/

        WebSocketClient containerScope = new WebSocketClient(httpClient);
        ClientContainer clientContainer = new ClientContainer(containerScope);
        clientContainer.start();

        clientEndpoint.setWebSocketContainer(clientContainer);
        return clientEndpoint;`

Thoughts?

**Comment by joakime** [comment]
Closing as using the HttpClient to configure proxy support is the correct way.
