### ISSUE TITLE
'@{argLine}'  in Pom files breaks Netbeans

### ISSUE THREAD

**Issue by dellgreen** [eclipse/jetty.project#1779]
In Netbeans 8.2, testing whole project is fine, however running individual test or debugging test fails to run as '@{argLine}' is being passed to the java process as a literal i.e. has not been subjected to  variable substitution.
To make everything work as normal, involves removing @{argLine} from `<argline>` element in main pom file 
Is @{argLine} being used in this project by anything?, or was it a default added on project creation?

**Comment by joakime** [comment]
Both Eclipse and IntelliJ have support for `@{argLine}` from maven.  Its a standard feature of the surefire plugin.  

Removing `argLine` will break our CI builds (especially surrounding the coverage reporting of our unit testing), so we will not be doing that.

According to bug at netbeans, your Netbeans 8.2 installation should not have a bug with argLine.
https://netbeans.org/bugzilla/show_bug.cgi?id=146287

I would suggest filing an update on that bug (they are asking for updates, specifically from NetBeans 8.2)

**Comment by dellgreen** [comment]
Thanks for the build insight, i have reopened this issue on the Netbeans bug tracker

**Comment by joakime** [comment]
Out of curiosity, if you can set properties for your run/test configurations, perhaps setting an `argLine` property to something valid (or blank) might get you past it.

**Comment by dellgreen** [comment]
Thanks for this suggestion, yer i did think of this and spent ages trying to figure out how, but the stdout shows '@{argLine}' is being passed directly to the Java process as the first argument in a shell script startup and not as a property so it fails thinking its the class name/path to execute. I havent figured out yet how netbeans starts the processes via 'sh' . Will investigate further if netbeans team doesnt respond :)
