### ISSUE TITLE
Update JASPI implementation and add test harnesses

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#178]
migrated from Bugzilla [#455047](https://bugs.eclipse.org/bugs/show_bug.cgi?id=455047)
status ASSIGNED severity _normal_ in component _server_ for _9.2.x_
Reported in version _9.2.6_ on platform _PC_
Assigned to: Greg Wilkins

On 2014-12-12 10:24:25 -0500, Greg Wilkins wrote nothing.
On 2014-12-12 10:28:05 -0500, Greg Wilkins wrote:

> Subject: [servlet-spec users] Re: JASPI was: session(-less) applications
> Reply-To: users@servlet-spec.java.net
> X-Loop: users@servlet-spec.java.net
> X-Sequence: 877
> Errors-to: users-owner@servlet-spec.java.net
> Precedence: list
> X-no-archive: yes
> List-Id: <users.servlet-spec.java.net>
> List-Help: mailto:sympa@servlet-spec.java.net?subject=help
> List-Subscribe: mailto:sympa@servlet-spec.java.net?subject=subscribe%20users
> List-Unsubscribe: mailto:sympa@servlet-spec.java.net?subject=unsubscribe%20users
> List-Post: mailto:users@servlet-spec.java.net
> List-Owner: mailto:users-request@servlet-spec.java.net
> 
> Hi,
> 
> On Fri, Dec 12, 2014 at 2:30 PM, Greg Wilkins gregw@intalio.com wrote:
> 
> > Arjan,
> > 
> > I've started having a bit of a look at this in jetty.  It's like an
> > archaeological dig discovering code not used for some time!
> > 
> > Note that jetty does have BASIC/DIGEST/FORM etc. implemented
> > 
> > https://github.com/eclipse/jetty.project/tree/master/jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules
> 
> Wow, looks like a great start.
> 
> > But this code has been untested/unused for a while.    I'll wake it up with
> > a few test harnesses and then try out some of your modules.   If you wanted
> > to cast your expert eye over them to see if they look approximately correct,
> > that would be handy.
> 
> I did a quick look, and saw a few things:
> 
> // not mandatory or its the login or login error page don't authenticate
> if (!mandatory ||
> isLoginOrErrorPage(URIUtil.addPaths(request.getServletPath(),request.getPathInfo())))
> return AuthStatus.SUCCESS;
> 
> While a lot of (early) auth modules just returned SUCCESS when "doing
> nothing", the idea is to actually only return SUCCESS when the
> CallerPrincipalCallback has been handled. If nothing needs to be done,
> the CallerPrincipalCallback can be invoked with a null as follows:
> 
> handler.handle(new Callback[] { new
> CallerPrincipalCallback(clientSubject, null) });
> 
> I've put this on the Javadoc of the "doNothing" method from the
> example I referenced as:
> 
> /**
>      \* Instructs the container to "do nothing".
>      *
>      \* <p>
>      \* This is a somewhat peculiar requirement of JASPIC, which
> incidentally almost no containers actually require
>      \* or enforce.
>      *
>      \* <p>
>      \* When intending to do nothing, most JASPIC auth modules simply
> return "SUCCESS", but according to
>      \* the JASPIC spec the handler MUST have been used when returning
> that status. Because of this JASPIC
>      \* implicitly defines a "protocol" that must be followed in this case;
>      \* invoking the CallerPrincipalCallback handler with a null as the username.
>      *
>      \* <p>
>      \* As a convenience this method returns SUCCESS, so this method
> can be used in
>      \* one fluent return statement from an auth module.
>      *
>      \* @return {@link AuthStatus#SUCCESS}
>      */
> 
> Another thing that I noticed:
> 
> boolean success = tryLogin(messageInfo, clientSubject, response,
> session, username, new Password(password));
> if (success)
> {
> 
> ```
> [...]
> 
> response.sendRedirect(response.encodeRedirectURL(nuri));
> return AuthStatus.SEND_CONTINUE;
> ```
> 
> }
> 
> Where tryLogin among others does this when returning true:
> 
> CallerPrincipalCallback callerPrincipalCallback = new
> CallerPrincipalCallback(clientSubject,
> loginCallback.getUserPrincipal());
> GroupPrincipalCallback groupPrincipalCallback = new
> GroupPrincipalCallback(clientSubject, loginCallback.getRoles());
> 
> callbackHandler.handle(new Callback[] { callerPrincipalCallback,
> groupPrincipalCallback });
> 
> If SEND_CONTINUE is returned, then the invocation of the handler that
> was done in tryLogin is to be ignored.
> 
> Because JASPIC is effectively stateless, it would not really make
> sense to authenticate and directly redirect. In Java EE 7 an extra
> option was added so the authentication is semi-remembered, so it might
> make sense in that case.
> 
> At any length, because of the stateless aspect the module should check
> if there's an existing login remembered somewhere (e.g. put in the
> session) and then re-authenticate at the start of validateRequest.
> 
> I'll take a more in-depth look later if needed ;)
> 
> > Would you mind if I added your HttpHeaderAuthModule as a test/example ?
> 
> Not at all, but do note it depends on a library called OmniSecurity
> that I've been incubating.
> 
> Kind regards,
> Arjan Tijms

On 2014-12-12 10:49:02 -0500, Greg Wilkins wrote:

> test harnesses added with commit SHA: fe444b28dd05d7f7c668335a7b68844ffc9047b9

On 2015-10-28 07:00:28 -0400, Mohd Farid wrote:

> Hi Greg
> 
> As a part of plan to increase the test coverage of this module to the maximum, I have implemented few unit tests for this module. The same is present on github repo of my organisation. 
> 
> Can I address a pull request to you for the same.
> 
> Thank you
> Farid

On 2015-10-28 16:38:55 -0400, Greg Wilkins wrote:

> A PR would be great! Just include a link to this issue in the description.
> 
> thanks

On 2016-01-02 06:13:49 -0500, Mohd Farid wrote:

> Hi Greg
> 
> I have raised a PR with the unit test cases for this module. Here is a link to the same: https://github.com/eclipse/jetty.project/pull/64

**Comment by sbordet** [comment]
@olamy isn't JASPI part of the Servlet TCK? If so, we can close this issue.

**Comment by olamy** [comment]
but we do not run this part of the TCK and I'm not sure how to run this...
