### ISSUE TITLE
Consider using assembly.tarLongFileMode=posix for jetty-home and jetty-distribution

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1782]
We have some reports of build failures on Ubuntu 16 when the assembly plugin kicks in for the modules:

 * `jetty-home`
 * `jetty-distribution`

**Comment by olamy** [comment]
@joakime  I don't mind doing the change. But I tried to reproduce and could not.
Do you have any logs?

**Comment by olamy** [comment]
see #1942 and #1943

**Comment by olamy** [comment]
well I think we can close this one. everything merged in 3 branches.
