### ISSUE TITLE
Question or feature request: How to get details for all established connections real-time?

### ISSUE THREAD

**Issue by avkonst** [eclipse/jetty.project#1783]
I have not found a way to dispatch events when a TCP connection is established and when a TCP connection is closed. TCP connections are managed by Netty, which is managed by Jetty. This suggests it should be technically possible to get this information up to the Jetty based server application level.

I have got https server powered by Jetty 9. I need an API to get client IP addresses for all established connections (i.e. for audit, security, monitoring, QoS and other purposes). Ideally, it could be event (callback) driven API notifying about established and closed connections. How can I achieve it?

Current workaround is to poll a tool similar to netstat, but it is very inconvenient and not really real-time (i.e. short connections can be missed).

**Comment by gregw** [comment]
@avkonst If you have a standard ServletRequest instance, you can call  [getRemoteAddr](http://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getRemoteAddr--) which has the benefit that if Jetty is configured to use the PROXY protocol or the ForwardedRequestCustomizer, then the actual remote client IP can be returned (not just the IP of the firewall/proxy/gateway/loadbalancer etc.).

If you really want to do it on Connections, then setup a Connection.Listener (look at the stats module for an example) and then you will get callbacks on connect.  You can ask a Connection for its EndPoint and then ask that for the remote address.... but it will just be the first hop of what is typically a multi hop connection.

**Comment by avkonst** [comment]
Thank you!
