### ISSUE TITLE
Can an interrupted thread be returned to the ThreadPool?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1788]
If a thread is interrupted, the internal flag for "interrupted" is set. right?

A thread thats interrupted is useful for closing blocking I/O actions (usually seen as a `java.nio.channels.ClosedByInterruptException` and later on as a EoFException)

If this thread is returned to the ThreadPool then wouldn't the interrupted state be returned along with it?  Do we have safety checks for this kind of situation?

**Comment by joakime** [comment]
If this kind of "pre-interrupted" thread is later pulled from the ThreadPool, wouldn't it automatically trigger I/O failures and whatnot when its attempted to be used?

**Comment by sbordet** [comment]
`QueuedThreadPool` [deals with this situation](https://github.com/eclipse/jetty.project/blob/jetty-9.4.6.v20170531/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L594), clearing the `interrupted` flag and terminating the thread (i.e. it's not pooled).
