### ISSUE TITLE
Update MongoSessionManager to newer API and make more configurable

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#179]
migrated from Bugzilla [#455519](https://bugs.eclipse.org/bugs/show_bug.cgi?id=455519)
status ASSIGNED severity _enhancement_ in component _server_ for _9.2.x_
Reported in version _9.2.6_ on platform _All_
Assigned to: Jan Bartel

On 2014-12-17 11:17:17 -0500, Jan Bartel wrote:

> The java driver for the MongoSessionManager has undergone many releases and has a lot of new features. We should update to the newer api, and along the way expose more of the Mongo objects so that they can be configured, eg the Mongo/MongoClient instance.  The configuration of the Mongo/MongoClient object would eg allow users to select the level of atomicity for writes/reads.

**Comment by pbtura** [comment]
Any expected timeline on this? Being stuck with the old mongo drivers is preventing the rest of my project from using newer features.

**Comment by joakime** [comment]
when this was filed 4 years ago, we were still on mongo 1.x drivers.
since then, issue #611 has updated it to mongo 3.2.2 drivers.
that issue was fixed via a community pull request.

**Comment by janbartel** [comment]
Probably still need to upgrade to even newer mongo version, but we can open a fresh issue specifically for the newer version. I'll close this one.
