### ISSUE TITLE
Datacache thread leak in embedded app

### ISSUE THREAD

**Issue by Bardammu** [eclipse/jetty.project#1791]
I have an application with a Jetty HTTP Servlet Server (version 9.0.7)

When I shutdown the server(not shutting down the JVM) a thread is leaked by DataCache.

As a workaround, I'm terminating the timer manually:
`DateCache.getTimer().cancel();`

But this approach doesn't work since when I need to start the server again the following exception is thrown:
>  java.lang.IllegalStateException: Timer already cancelled.

I assume this is not a bug, but I'd like to know if there is a correct way to address this scenario.

**Comment by janbartel** [comment]
@Bardammu I suggest you take a look at the o.e.j.util.component.ContainerLifeCyle and o.e.j.util.component.LifeCycle classes.  Server is a ContainerLifeCycle, and thus you can call any of the addBean() methods on it. You could make bean that implements LifeCycle and stops/starts the DataCache. If you add it to the Server as a managed bean, then when the Server starts and stops, the start/stop methods will be called on your bean.

**Comment by Bardammu** [comment]
Thanks for your suggestion @janbartel.

The problem is that DataCache has a static attribute with the timer. This timer is created when the jetty server is started for the first time. If I cancel the timer when the server is stopped, the second time I start the server it fails.

I've created a bean where I've implemented a hacky method with reflection where I clean the timer to work around my issue. It works for now.

It looks that I'll have to update the Jetty version if no other solution arises.

Thanks again.

**Comment by janbartel** [comment]
@Bardammu there's not really enough information about what DataCache is and how you're calling it for me to comment much further.  I don't see how changing the jetty version will help you, as I can't see how this problem is related to jetty from what you've described, although it's always a good idea to keep up-to-date. If you're happy with your solution, then can we close this issue?

**Comment by Bardammu** [comment]
Hi @janbartel 

> DataCache Computes String representations of Dates and caches the results so that subsequent requests within the same minute will be fast

It is used in the Jetty Server in version 9.0.7. And it was removed in 9.4:
https://github.com/eclipse/jetty.project/commit/d5f83a81598a598d0ed6018ae6cc9d7f47476bdc

I wanted to see if someone has a better solution, but I'm closing this since it looks like I won't get any response.

**Comment by janbartel** [comment]
Ahhh, Dat**e**Cache, not DataCache!

Yep, your best move is to upgrade from 9.0 as that has been End Of Life for many years now.
