### ISSUE TITLE
Fix session id manager workerName

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1795]
The [server.mod](https://github.com/eclipse/jetty.project/blob/jetty-9.4.6.v20170531/jetty-server/src/main/config/modules/server.mod#L86-L87) uses a property that isn't actually used anywhere in Jetty.

```
## The name to uniquely identify this server instance
#jetty.defaultSessionIdManager.workerName=node1
```

**Comment by janbartel** [comment]
Removed old unused properties from server.mod:

jetty.defaultSessionIdManager.workerName
jetty.sessionInspectionInterval.seconds
