### ISSUE TITLE
Jetty CPU Usage Spikes

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#180]
migrated from Bugzilla [#456736](https://bugs.eclipse.org/bugs/show_bug.cgi?id=456736)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.2.6* on platform *Other*
Assigned to: Greg Wilkins

On 2015-01-05 20:37:00 -0500, Gregory Grillo wrote:

> I'm in the beginning stages of debugging a Jetty CPU spiking problem where the CPU usage continues to increase and ultimately ends up locking Jetty to the point where new connections cannot be made.  I've seen many posts about this issue but they were several years ago (https://jira.codehaus.org/browse/JETTY-937 - for example).  
> 
> However, as I understand it, Jetty 9 no longer uses the SelectChannelConnector so although my issue is similar, it doesn't appear to be related.  Via the "jvmtop" tool, I can see what thread is using the CPU and basically Jetty cannot recover once the issue begins.  I have a very small user base so its not like 1,000 of users are making requests, maybe 20 simultaneous users at the most.  The "jvmtop" output that illustrates the problem thread looks like this:
> 
> ./jvmtop.sh [java process id]
> 
>  ARGS: 
>  VMARGS: -Xms512m -Xmx2g -XX:MaxPermSize=1g -XX:+HeapDumpOnOutOfMemoryErro[...]
>  VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.7.0_25
>  UP:  4:24m  #THR: 138  #THRPEAK: 149  #THRCREATED: 2049 USER: **********   
>  GC-Time:  0: 1m   #GC-Runs: 2104      #TotalLoadedClasses: 23734   
>  CPU: 50.04% GC:  0.00% HEAP: 512m /1820m NONHEAP: 167m /1072m
> 
>   TID   NAME                                    STATE    CPU  TOTALCPU BLOCKEDBY
>      36 qtp2146135443-36-selector-Serv       RUNNABLE 88.80%    93.69%       
>    2044 RMI TCP Connection(708)-10.240       RUNNABLE 10.46%     0.09%       
>    1870 RMI TCP Connection(712)-10.240       RUNNABLE  0.39%     0.00%       
>    2045 JMX server connection timeout   TIMED_WAITING  0.18%     0.00%       
>    1922 RMI TCP Connection(711)-10.240       RUNNABLE  0.05%     0.00%       
>       9 RMI TCP Accept-0                     RUNNABLE  0.02%     0.00%       
>      10 RMI TCP Accept-6969                  RUNNABLE  0.01%     0.00%       
>      21 DefaultQuartzScheduler_Worker-  TIMED_WAITING  0.00%     0.00%       
>      22 DefaultQuartzScheduler_Worker-  TIMED_WAITING  0.00%     0.00%       
>      19 DefaultQuartzScheduler_Worker-  TIMED_WAITING  0.00%     0.00%  
> 
> It is the qtp thread that causes the problem.  It usually spikes up to well over 100% for a few minutes before Jetty becomes unresponsive.   I have a Java/Vaadin app that uses RPC between server and client for dynamic UI updates (if that matters).  The server notifies the browser at times, when updated UI data is available.  Given this output and problem description, can you point me in any direction as to the root cause?  
> 
> Thanks very much.

On 2015-04-01 18:31:12 -0400, Greg Wilkins wrote:

> Sorry been slow to respond on this one.
> 
> Are you still seeing this? Have you tried a more recent version of 9.2.x?

**Comment by joakime** [comment]
Closing as not-reproducible.

Feel free to reopen with a testcase if you have one.
