### ISSUE TITLE
Reserved threads for HTTP/2

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1802]
@gregw with HTTP/2, we have N selectors and M reserved threads. However, since HTTP/2 is always non-blocking, what happens is that 1 thread will be in `select()`, wake up, see the task is non-blocking, consuming the task (i.e. read from the connection), eventually going back to `select()`. The reserved threads will remain idle forever, but will steal a thread each because they are eagerly allocated and never time out.

Because HTTP/2 is always non-blocking, ideally it should set `reservedThreads=0` onto the `SelectorManager`, since it will never happen that a thread blocks (but of course the `SelectorManager` does not know that).

Typical case of 8 cores and 200 threads will waste 8 threads out of 200.

A thread pool with 3 threads, one acceptor, one selector, one reserved thread.
Since HTTP/2 is in PEC mode, it will queue the request handling, but no threads available to run it - although the reserved thread is always idle in the pool (and will never be used).

I think we can mitigate this by lazily allocating `ReservedThread`s. I'll give it a go.

**Comment by sbordet** [comment]
Lazily allocating `ReservedThread` works, but it needed to convert a couple of `ManagedSelector` inner classes to be non-blocking, namely `CreateEndPoint` and `DestroyEndPoint` (the latter was a lambda).

@gregw waiting for your thoughts.

**Comment by sbordet** [comment]
A thread pool of size 3 (one acceptor, one selector) now (with lazy reserved threads) works for HTTP/2, but does not for HTTP/1.

The reason is that we get a blocking task, we call `tryExexecute()` which finds that there are no reserved threads (and so we move to PEC mode), so dispatched a reserved thread, which steals the last thread in the pool. The task is then submitted but there are no threads available.

**Comment by gregw** [comment]
@sbordet you cannot lazily allocate resourced threads.... because there may not be any more threads in the thread pool when you want to lazily allocated.  The whole point is having a guarantee that a thread is available before EPC is done.

In order to reduce wasted threads in HTTP/2 we could release a reserved thread to try selecting, even if the produced task is non-blocking - (it still may take some time).

**Comment by gregw** [comment]
To be clear we currently do the logic:
```
if (task is non-blocking)
  do PC
else if (reserved thread is available)
  do EPC
else 
  do PEC
```
we could improve reserved thread usage by changing to:
```
if (reserved thread is available)
  do EPC
else if (task is non-blocking)
  do PC
else 
  do PEC
```

However, the true solution is to move the execution strategy higher up.... I will make that the subject of a different post to explain plan.

**Comment by sbordet** [comment]
Slight correction on the current logic:
```
if (task is non-blocking)
  do PC
else if (reserved thread is available)
  do EPC
else 
  do dispatch reserved thread; do PEC
```
We _can_ allocate reserved threads lazily because that's what the else branch does.
We will pay an initial cost of doing PEC for the first N blocking tasks, but those will spawn reserved threads, so eventually the system will be as if the reserved threads are eagerly allocated.

There is currently no relationship between the thread pool and the number of reserved threads: I can setup them independently and set `maxThreads=3` on the pool and `reservedThreads=1024` which will obviously not work.

The default logic that we have when `reservedThreads=-1` is fine for all values of `maxThreads` apart `3`. However, for HTTP/2 (and HTTP/1.1 non-blocking) we waste threads.

**Comment by gregw** [comment]
@sbordet OK I understand what you mean by lazy now, start with zero reserved threads and grab them whenever somebody asks and we say no.   Sure that is a reasonable change, however I think we should also trial the change of logic I suggested.... however I think there is an inherent conflict between what is good for a mostly idle server vs a mostly busy one.

**Comment by gregw** [comment]
I have created #1803 in which we can discuss wider changes to the execution strategies

**Comment by sbordet** [comment]
@gregw I pushed #1804 and #1805 which somehow are an improvement over the previous behavior although still not optimal, see also #1806.

**Comment by sbordet** [comment]
@gregw I believe this can be closed.
