### ISSUE TITLE
Review usage of scheduling strategies 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1803]
Current usage of the Eat-What-You-Kill scheduling strategy has been reduced in order to avoid the issue of thread starvation.    Now with experience of that problem and more information from bench marking, we should review the usage of our scheduling strategies.

**Comment by gregw** [comment]
Summary of execution strategies 

Abbrev. | Name | Description
-----------|----------|---------------
`PC` | Produce Consume | The same thread that `P`roduces (creates) a job and `C`onsumes(runs) the job
`PEC` | Produce Execute Consume | One thread `P`roduces a job and then `E`xecute another thread to `C`onsume the job
`EPC` | Execute Produce Consume | Another thread has been `E`xecuted to `P`roduce while the current thread `C`onsumes a job it has previously produced. 
`EWYK` | Eat What You Kill | Was originally nick name of `EPC`, but has become a name for a strategy that dynamically switches between `PC`, `PEC`, `EPC` using non-blocking invocation indicators and a reserved thread pool to select between appropriate strategies.

**Comment by gregw** [comment]
Summary of problem space:

To handle incoming requests and IO events we need to:
1. *Select* the EndPoint
2. *Parse* in Connection callback (typically Connection#onFillable) to read & parse
3. *Handle* the resulting task (typically HttpChannel#handle or flow control event)

We can put execution strategies between any of these steps. 

Flow control events must never be executed, as this can result in them being queued waiting for a thread, but all threads may be consumed by blocking tasks waiting for a flow control event.  For HTTP/1 flow control is handled simply be there being data available to read/write, which for HTTP/2 flow control requires a frame to be read and parsed to see if it is a flow control frame (queuing non flow control frames so that head of line blocking does not prevent later flow control frames from being seen) 


Early versions of Jetty used `select-PEC-parse-PC-handle`.  In 9.0.0 we tried `select-PC-parse-PEC-handle`, but that [resulted in parallel slowdown](https://webtide.com/avoiding-parallel-slowdown-in-jetty-9/).   The conclusion was that `PEC` between parse and handling is a very bad idea and we reverted to initially to  `select-PEC-parse-PC-handle`.

The introduction of HTTP/2 made is impossible to have `PC` between parse and handle, because flow control requires parsing.    Thus we came up with  `EPC` and `EWYK` motivated to avoid the parallel slowdown of `PEC` between parse and handle.    However `select-EPC-parse-EPC-handle` suffers from thread starvation problems which I will describe in another post.

The result being that we are currently configured as `select-EWYK-parse-EWYK0-handle`. As `EWYK` is a dynamic strategy, we need to look at events and protocols to see what actually occurs:

Protocol | Event | Strategy | Comment
---|----|----|----
HTTP/1 | Request  |  `select-EPC-parse-PC-handle` |  Good!
HTTP/1 | Flow Control |  `select-PC-parse-PC-handle` |  Perfect!
HTTP/2 | Request |  `select-PC-parse-PEC-handle` |  Bad (see below)!
HTTP/2 | Flow Control |  `select-PC-parse-PC-handle` |  Perfect!

**Comment by gregw** [comment]
Thread starvation with `select-EWYK-parse-EWYK-handle` for http/2!  (this explanation is a mess, but the best I can come up with for now).

Consider if only a single thread is left active and that all other threads are blocked in handling waiting for flow control events.    In order to not suffer from thread starvation, we must ensure that for flow control events we are `select-PC-parse-PC-handle` otherwise the last thread may be executed and thus block.  However for request events, we must be `select-PC-parse-PEC-handle` so we can queue the non flow control frames and avoid head of line blocking of subsequent flow control frames.

However, for HTTP/2 we cannot distinguish between request and flow control until after we have parsed, so you think we could have a dynamic mix of  `select-PC-parse-PC-handle(flowcontrol)` and `select-PC-parse-EPC(request)`.     But there is a problem as the `select-PC-parse` part can only be done if we know the next step is non-blocking, but from the selectors point of view a `EPC` step is blocking, so if we are low on threads we need to do `select-PEC-parse-PC(request)`.   

Essentially with  `select-EWYK-parse-EWYK-handle` we have two dynamic strategies in a race trying to make a decision about if there is a thread shortage or not.   If they are both dynamic it is impossible to avoid accidentally ending up with `select-PC-parse-EPC-handle(request)`, which is thread starvation if that was the last thread.

Thus we need to be either  `select-EWYK0-parse-EWYK-handle` (bad for HTTP/1) or  `select-EWYK-parse-EWYK0-handle` (bad for HTTP/2).   We've settled on  `select-EWYK-parse-EWYK0-handle`  which gives the effective results summaries in the table in the previous comment.

**Comment by gregw** [comment]
@sbordet just writing down some more thoughts on this issue for us to consider.

The fundamental issue that we have to deal with is that if we are to avoid thread starvation then the selector thread must execute the selection callbacks for flow control (else a busy thread pool full of blocked threads may never unblock if the flow control callbacks are put in the job queue) .  But for HTTP/2, we do not know what is flow control until we fill and parse, so for HTTP/2 at least we must fill and parse from the selector thread.     Our problem this is that we can never do EWYK within HTTP/2, as the selector thread might be the last thread and we cannot use it to call the application, else it may block and we are starved.

So considering that, another way to describe Proposed Solution 1 above, is to change our selection mechanism so that every connection works like HTTP/2.  Ie the selector thread always will do the fill and parse for all connections.

To achieve this, we need to replace `Callback` with `Producer` in our lower layers.  The `Runnable onSelected()` method becomes `Producer onSelected` and we change `FillInterest` an `WriteFlusher` to also take `Producer`.  We also need to change `Connection.onFillable` to return a `Runnable`.

The ManagedSelector's Producer loop then becomes:

1. If the Collection of selected keys is not empty
    - pick the next key and call onSelected
        - if it returns a producer, call `produce()`
            - if it returns a task, 
                - add the producer to the list of current producers
                - return the task as the task we have produced
            - else repeat step 1.
2. If the list of current Producers is not empty (and it's not too long since last select)
    - Remove the first Producer and call it's`produce()`
        - If it returns a task,
            - add the  producer to the end of the producer list.
            - return that as the task we have produced.
        - else repeat step 2. 
3. Run any queued Actions
4. Select and add selected keys to the collection of selected keys.

You'll note that with this loop we are protected against busy producers, as we will always fair share between the current producers, plus we can do a select if it has been too long since our last select.

The onSelected Producers would be like some of the following:
- call `connection.onFillable()` which would fill and parse until it wants to call `HttpChannel.handle`, which it would do by returning the channel as it's produced task.  Both h1 and h2 work the same here.
- for H1 blocking reads, unblock `HttpInput` and return null.
- for H1 async reads, fill, parse and maybe return the `HttpChannel` if `onDataAvailable` needs to be called
- for H1 writes, run the WriteFlusher and return the HttpChannel if `onWritePossible` needs to be called

With this setup, we would be able to use EWYK as our execution strategy, which would act in one of two ways:
- the selector thread will fill, parse and produce a HttpChannel, it will then run the HttpChannel as a reserved thread continues selecting.
- the selector thread will fill, parse and produce a HttpChannel, which will be executed to the thread pool because no reserved thread is available.

If we have only one thread left, it will select and call produce, but queue all the tasks produced on the thread pool and keep selecting.

Currently, I think all tasks returned will be blocking, so we can probably get rid of the Invocable stuff as unnecessary complication.

Thoughts?

**Comment by gregw** [comment]
Proposal 2.

I believe it would be possible to apply EWYK scheduling to HTTP/2 with minimum changes if we use the EITHER invocation type.  We previously tried this by having two selector schedulers, but there was a problem with the two racing.

To make the EITHER invocation type work, the EWYK strategy would need to be modified to act as follows:

1. If the produced task is `BLOCKING` and we are invoked as `BLOCKING`
     - if tryExecute ourselves succeeds
         - consume the task ourselves (EPC mode) with `BLOCKING` invocation
     - else
         - execute the task (PEC mode)
2. else if the produced task is `NON_BLOCKING`
     - consume the task ourselves (PC mode)
3. else if the produced task is `EITHER`
     - if we are invoked as `BLOCKING` and tryExecute ourselves succeeds
         - consume the task ourselves (EPC mode) with `BLOCKING` invocation
     - else
         - consume the task ourselves (PC mode) with `NON_BLOCKING` invocation


Executions strategies can then be chained. In the case of HTTP/2, it will be an `EITHER` invocation type, so that if the last thread is running the selector, it will fail to tryExecute and invoke HTTP/2 in `NON_BLOCKING` so that tasks will be consumed as either PC or PEC.    Only if the selector has a reserved thread, will a HTTP/2 connection be invoked as BLOCKING and only then will it be able to run in EPC mode. 

Secondary to this proposal, I believe that having multiple ReservedThreadExecutor is confusing and difficult to understand and/or configure.  Instead I think that the primary Executor should be wrapped as a ReservedThreadExecutor and the execute method on ReservedThreadPool changed to be passthrough.   Execution strategies could then use an instanceof test to see if the exectutor can work in EWYK mode.   Note that we'd also have to look at usages of instanceof SizedThreadPool

**Comment by joakime** [comment]
I have to say, I appreciate all of the detail present in this issue wrt the various strategies.

**Comment by gregw** [comment]
Proposal 3 is to modify proposal 1 so that the list of producers is a ForkJoin task and use a ForkJoinThreadPool to allocate threads to produces with work stealing etc.

This might not be EWYK, but there may be other smarts in there that make it really fast???

**Comment by gregw** [comment]
This is going to be a bit of a rambling comment.... but tl;dr; I don't think Proposal 1 is feasible.

The essence of proposal 1 is to make the Connection implementations Producers, so that fill and parse is done as part of production and that calling the application (via something like HttpChannel.handle) is a produced task that can be consumed via an execution strategy. However, there are several problems with this....

Firstly we currently pass Callbacks from the Connection all the way down to the EndPoint onSelection handling.  Callbacks can't be simply replaced with Producers as Producers do not have a `fail` method.  We would have to produce a hybrid interface like a ProducingCallback, which doesn't really feel conceptually clean.

Then we have a problem with connection types like HTTP/1, which need to handle the connection in series with the execution of the application.   While a prior request is still executing, we cannot read any pipelined requests that may have arrived.   This is a complex sequence to achieve with a Producer as the contract for Producer in proposal 1 if for produce to keep being called until null is returned. Thus we can have the following sequence:
 - The connection is selected
 - the connections producer is called, which fills and parses.  If it get's a complete request it returns a task that will run HttpChannel.handle.  This task is given to the execution strategy to run.
 - eventually the ManagedSelector's producer will call the connections producer again to see if there is 
more that can be done.  This is fine for HTTP/2, which needs to keep filling and parsing, but not so good for HTTP/1.   It is essentially in a race between the completion of the execution of HttpChannel.handle and the next call to connection produce...
    + Either: HttpChannel.handle has completed when the produce is called, which case production can continue to fill and parse.
    + Or: HttpChannel.handle has not completed, in which case null must be returned and production will cease.  When HttpChannel.handle returns, the task that called it must now detect that there will be no further call to produce and thus must call produce itself and run any resulting task.  This will probably work, but we have the problem that produce can return a task that runs a task return from produce that runs a task returned from produce that runs a task returned from produce.... ie we can get an infinitely deep stack on a busy connection (or slow handler).  Some iterating callback mechanism may be deployed here... but it will be complex.

So while proposal 1 is conceptually simple (produce fills and parses the protocol and consume calls the application), it is practically rather complex and a lot different from our current code base.   We'd need very good indications that it is worth it before even attempting an implementation!
