### ISSUE TITLE
HttpChannel events

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1807]
For auditing and performance tracking would be great if Jetty could expose HttpChannel events such as:

* requestBegin
* requestBeforeDispatch
* requestAfterDispatch
* requestContent
* requestContentEnd
* requestTrailers
* requestEnd

**Comment by sbordet** [comment]
@gregw what do you think of events such as:

* requestReadCallback

for `onDataAvailable()` and `onAllDataRead()` ?
But then, should be also emit an event when we call `ReadListener.onError()` ?

**Comment by gregw** [comment]
I don't think we need a callback callback :) but the rest look good!

**Comment by sbordet** [comment]
@gregw I pushed the work for this issue at 8e1e396.

All events are emitted by `HttpChannel` so that transport specific subclasses have nothing more to do.
You want to review it, in particular a couple of things:

* `HttpChannel.CommitCallback` and `HttpChannel.ContentCallback` now need to `slice()` the content buffer in order to call multiple listeners; this has a slight allocation impact (just the `ByteBuffer` wrapper around the original buffer)
* The code now has a number of `notify*` calls, and each creates a non-capturing lambda, so hopefully the cost is only paid at the first call. Escape analysis gets rid of the allocation of the iterator in the `for..each` notification loops.

To decide is where an application can provide a `HttpChannel.Listener`.
Currently listeners are extracted from the `Connector` in `HttpChannel` constructor.
I don't think it's right to have them in `HttpConfiguration`; we create the TLS `HttpConfiguration` from the clear-text one, so I think it's confusing when I want to configure events in one but not the other.

Also, perhaps we want to expose the `HttpChannel.Listener` to the application, so that application events and `HttpChannel` events can be combined (e.g. call a third party service):

```java
public class MyServlet extends HttpServlet {
    public void service(HttpServletRequest request, HttpServletResponse response) {
        HttpChannel.Listener listener = (HttpChannel.Listener)request.getAttribute(HttpChannel.Listener.class.getName());
        // use the listener
    }
}
```

However, this runs into the issue of punching a hole in the server classes to make `HttpChannel.Listener` seen from the application classloader.
Not sure it's worth the trouble for now. Thoughts ?

**Comment by sbordet** [comment]
@gregw I tried to implement what we discussed yesterday, namely modern lazylist, but eventually code has more duplication (have to duplicate try/catch blocks), so I left it as is.
The normal path should have zero allocations in the normal case anyway, so I think we're good.
