### ISSUE TITLE
Configuring search filter in LdapLoginModule

### ISSUE THREAD

**Issue by Myllyenko** [eclipse/jetty.project#1808]
I'm trying to authenticate a user with AD and `LdapLoginModule` but authentication fails because user is not found. I've compared LDAP dumps of successful user search with Python and unsuccessful attempt with Jetty and found only these differences:

fail:
![not-ok](https://user-images.githubusercontent.com/10358254/30214615-cf2d2b68-94b5-11e7-8e3e-2ad71404904d.png)

success:
![ok](https://user-images.githubusercontent.com/10358254/30214614-cdd956b0-94b5-11e7-8565-c75d1a8e5a8f.png)

As far as I understand, the differences in `derefAliases` and `sizeLimit`  cannot lead to fail (`derefAliases` in Jetty is even more "broad") so the fail is caused by the search filter (`equalityMatch` instead of `present`).

I want to create a pull request to make search filter configurable. Right now I'm trying to find out where it can be configured but I din't find any clues yet. An advice would be helpful.

**Comment by gregw** [comment]
@Myllyenko thanks for your offer of a PR. Very much appreciated as we don't really have an LDAP env we can develop and test in easily or quickly.

Configuring the `LdapLoginModule` has to be done via the `ldap-loginModule.conf` file, as jetty does not directly instantiate the module and thus cannot inject it with configuration.

I believe you can add your own options to that file, which would then be available in the options map in the method:
```
    public void initialize(Subject subject,
                           CallbackHandler callbackHandler,
                           Map<String, ?> sharedState,
                           Map<String, ?> options)
```

You can then pull out any optional parameters you wish to add to the options array to configure the searches performed.

**Comment by janbartel** [comment]
@Myllyenko  that looks like a bug either in the jvm ldap client code, or the ldap service provider. That's not going to be something that is configurable on the search by jetty.

According to the ldap search filter spec "attribute=*" should be interpreted as a presence check, not an equality exact match. Looks like your python example is interpreting correctly, but the java example is not.  Can you try changing the version of the jdk? Can you debug more with the ldap service provider?
