### ISSUE TITLE
long response time lead to high CPU in jetty when using httpd server in front and a short timeout setting

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#181]
migrated from Bugzilla [#456741](https://bugs.eclipse.org/bugs/show_bug.cgi?id=456741)
status REOPENED severity *normal* in component *server* for *9.2.x*
Reported in version *8.1.16* on platform *PC*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[jetty-issue-demo.zip](https://bugs.eclipse.org/bugs//attachment.cgi?id=249728)_ (ID 249728)
- _[httpd-fuse.conf](https://bugs.eclipse.org/bugs//attachment.cgi?id=249729)_ (ID 249729)

On 2015-01-06 01:05:02 -0500, Xiaohui Wu wrote:

> My scenario is below:
> I have a long response time CXF restful web service and I am using camel to expose this CXF endpoint. The response time is 2 mins. 
> At the same time I have the httpd as the front proxy while it has the setting timeout=60
> <VirtualHost *:443>
> ...
>       <Proxy balancer://cxfrs>
>            BalancerMember https://localhost:9292/demo/aaa retry=10 timeout=60
>       </Proxy>
>       ProxyPass /demo/aaa balancer://cxfrs
> ...
> </VirtualHost>
> 
> When I visit the service through the below command several times(3~5 times):
> 
> curl -k --user admin:admin https://localhost:443/demo/aaa
> 
> after several mins, I can see the high cpu in the jetty through "top" command and the jetty code is running in an infinite loop.

On 2015-01-06 01:13:27 -0500, Xiaohui Wu wrote:

> 
> Reproduce steps:
> 1. 
> unzip the attachment jetty-issue-demo.zip 
> mvn clean package
> mvn camel:run
> 
> then you will see the port 9292 is listening.
> 
> 
> 2. 
> Install Apache HTTPD (tested with version 2.2.15)
> Install Apache mod_ssl module
> Copy the following configuration(attached) to a new file in conf.d.
> 
> 3. restart the httpd server, after visiting the service through the below command several times:
> curl -k --user admin:admin https://localhost:443/demo/aaa
> 
> then I can see the high cpu in the jetty.

On 2015-01-06 01:15:18 -0500, Xiaohui Wu wrote:

> From the stacktrace:
> "qtp680330057-225" prio=10 tid=0x00007f42dc732000 nid=0x33f3 runnable [0x00007f42a8e40000]
>    java.lang.Thread.State: RUNNABLE
> 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.fill(SelectChannelEndPoint.java:365)
> 	at org.eclipse.jetty.io.nio.SslConnection.process(SslConnection.java:333)
> 	- locked <0x00000000e24efdf8> (a org.eclipse.jetty.io.nio.SslConnection)
> 	at org.eclipse.jetty.io.nio.SslConnection.access$900(SslConnection.java:48)
> 	at org.eclipse.jetty.io.nio.SslConnection$SslEndPoint.flush(SslConnection.java:690)
> 	at org.eclipse.jetty.io.nio.SslConnection$SslEndPoint.flush(SslConnection.java:697)
> 	at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:838)
> 	at org.eclipse.jetty.http.AbstractGenerator.flush(AbstractGenerator.java:443)
> 	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:100)
> 	at org.eclipse.jetty.server.AbstractHttpConnection$Output.flush(AbstractHttpConnection.java:1123)
> 	at org.eclipse.jetty.server.AbstractHttpConnection$Output.sendContent(AbstractHttpConnection.java:1237)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination$JettyOutputStream.copyFrom(JettyHTTPDestination.java:414)
> 	at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:105)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination$WrappedOutputStream.copyFrom(AbstractHTTPDestination.java:706)
> 	at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:105)
> 	at org.apache.cxf.helpers.IOUtils.copyAndCloseInput(IOUtils.java:113)
> 	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.copyInputToOutput(BinaryDataProvider.java:136)
> 	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:105)
> 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1317)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:284)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:157)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:86)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
> 	- locked <0x00000000e2517f10> (a org.apache.cxf.phase.PhaseInterceptorChain)
> 	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:81)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
> 	- locked <0x00000000e2511e48> (a org.apache.cxf.phase.PhaseInterceptorChain)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.resume(PhaseInterceptorChain.java:242)
> 	- locked <0x00000000e2511e48> (a org.apache.cxf.phase.PhaseInterceptorChain)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:78)
> 	- locked <0x00000000e2511e48> (a org.apache.cxf.phase.PhaseInterceptorChain)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.serviceRequest(JettyHTTPDestination.java:355)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.doService(JettyHTTPDestination.java:319)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPHandler.handle(JettyHTTPHandler.java:72)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:193)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
> 	at org.eclipse.jetty.server.Server.handleAsync(Server.java:410)
> 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:519)
> 	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
> 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
> 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
> 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
> 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
> 	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
> 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
> 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
> 	at java.lang.Thread.run(Thread.java:744)
> After debuging the code, when the issue occurs, here it goes to a infinite loop, while the len==0 since the flush is not successful.   
> AbstractHttpConnection.sendContent(Object content)
>                  while (len>=0)
>                     {
>                         super._generator.completeUncheckedAddContent();
>                         _out.flush();
> 
>                         max = super._generator.prepareUncheckedAddContent();
>                         buffer = super._generator.getUncheckedBuffer();
>                         len=buffer.readFrom(in,max);
>                     }
> 
> In the AbstractGenerator.flush(long maxIdleTime) seems here there should be an exception thrown out.
> It has an condition _endp.isOpen()&& !_endp.isOutputShutdown() actually here in customer's scenario, the endpoint is closed due to the timeout in the http side.
> 
>             while (now<end && (content!=null && content.length()>0 ||buffer!=null && buffer.length()>0) && _endp.isOpen()&& !_endp.isOutputShutdown())
>             {
>                 blockForOutput(end-now);
>                 now=System.currentTimeMillis();
>             }

On 2015-01-06 01:18:42 -0500, Xiaohui Wu wrote:

> I setup a testcase using the camel:run can reproduce the issue even with the latest community version camel 2.14.1 + CXF3.0.3 + jetty 8.1.15V20140411.
> This issue still exist. 
> 
> while the code stack and analyze in comment# 2 are in jetty8.1.14V20131031.

On 2015-01-06 02:18:02 -0500, Xiaohui Wu wrote:

> Created attachment 249728
> project

On 2015-01-06 02:18:45 -0500, Xiaohui Wu wrote:

> Created attachment 249729
> httpd config

On 2015-01-06 05:24:41 -0500, Xiaohui Wu wrote:

> I just hacked the default dependency of cxf on jetty, 
> and adding the dependency of the latest jetty 8.1.16.v20140903. 
> This issue still exist.
> 
> So I think the code fix should check the endpoint's inputstream too 
> and if the endpoint's inputstream  is closed by httpd due to timeout, then an exception should be thrown out.
> I added a claus to throw out the exception in the while condition then the issue disappear. But I guess there should be a more proper way to fix.
> 
> <jetty-version>8.1.16.v20140903</jetty-version>
> 
>     <dependency>
>         <groupId>org.eclipse.jetty</groupId>
>         <artifactId>jetty-continuation</artifactId>
>         <version>${jetty-version}</version>
>       </dependency>
>       <dependency>
>         <groupId>org.eclipse.jetty</groupId>
>         <artifactId>jetty-http</artifactId>
>         <version>${jetty-version}</version>
>       </dependency>
>       <dependency>
>         <groupId>org.eclipse.jetty</groupId>
>         <artifactId>jetty-io</artifactId>
>         <version>${jetty-version}</version>
>       </dependency>
>       <dependency>
>         <groupId>org.eclipse.jetty</groupId>
>         <artifactId>jetty-security</artifactId>
>         <version>${jetty-version}</version>
>       </dependency>
>       <dependency>
>         <groupId>org.eclipse.jetty</groupId>
>         <artifactId>jetty-server</artifactId>
>         <version>${jetty-version}</version>
>       </dependency>
>       <dependency>
>         <groupId>org.eclipse.jetty</groupId>
>         <artifactId>jetty-util</artifactId>
>         <version>${jetty-version}</version>
>       </dependency>

On 2015-02-05 00:43:47 -0500, Xiaohui Wu wrote:

> I did a test using the latest jetty 9.2.6.v20141205 and cxf 3.1.0-SNAPSHOT, this issue does not occur!
> the below log being printed on the server side. Seems jetty is using com.ctc.wstx.sw.BaseStreamWriter now and  improved a lot.
> {code}
> 254471 [qtp110138755-17] ERROR org.apache.cxf.jaxrs.utils.JAXRSUtils  - Problem with writing the data, class [B, ContentType: application/json
> 254485 [qtp110138755-17] WARN  org.apache.cxf.phase.PhaseInterceptorChain  - Interceptor for {http://jetty.esb/}IssueDemo has thrown exception, unwinding now
> org.apache.cxf.interceptor.Fault
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:363)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:266)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:117)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:80)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
> 	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.resume(PhaseInterceptorChain.java:277)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:78)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.doService(JettyHTTPDestination.java:234)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPHandler.handle(JettyHTTPHandler.java:70)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1063)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:189)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handleAsync(Server.java:553)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
> 	at java.lang.Thread.run(Thread.java:744)
> Caused by: org.eclipse.jetty.io.EofException
> 	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
> 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:791)
> 	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
> 	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
> 	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:128)
> 	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:664)
> 	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
> 	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
> 	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:465)
> 	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:766)
> 	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:804)
> 	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
> 	at org.eclipse.jetty.server.HttpOutput$InputStreamWritingCB.process(HttpOutput.java:1046)
> 	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
> 	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
> 	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:542)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination$JettyOutputStream.sendContent(JettyHTTPDestination.java:285)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination$JettyOutputStream.copyFrom(JettyHTTPDestination.java:302)
> 	at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:139)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination$WrappedOutputStream.copyFrom(AbstractHTTPDestination.java:763)
> 	at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:139)
> 	at org.apache.cxf.helpers.IOUtils.copyAndCloseInput(IOUtils.java:147)
> 	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.copyInputToOutput(BinaryDataProvider.java:186)
> 	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:151)
> 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1360)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:244)
> 	... 22 more
> Caused by: java.io.IOException: Broken pipe
> 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
> 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
> 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
> 	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
> 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
> 	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
> 	... 51 more
> 254509 [qtp110138755-17] WARN  org.apache.cxf.phase.PhaseInterceptorChain  - Interceptor for {http://jetty.esb/}IssueDemo has thrown exception, unwinding now
> org.apache.cxf.interceptor.Fault: XML_WRITE_EXC
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor.handleMessage(JAXRSDefaultFaultOutInterceptor.java:102)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
> 	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:113)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:365)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:323)
> 	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.resume(PhaseInterceptorChain.java:277)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:78)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.doService(JettyHTTPDestination.java:234)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPHandler.handle(JettyHTTPHandler.java:70)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1063)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:189)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handleAsync(Server.java:553)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
> 	at java.lang.Thread.run(Thread.java:744)
> Caused by: com.ctc.wstx.exc.WstxIOException: Closed
> 	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:261)
> 	at org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor.handleMessage(JAXRSDefaultFaultOutInterceptor.java:100)
> 	... 23 more
> Caused by: org.eclipse.jetty.io.EofException: Closed
> 	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:320)
> 	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination$JettyOutputStream.write(JettyHTTPDestination.java:314)
> 	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
> 	at com.ctc.wstx.io.UTF8Writer.flush(UTF8Writer.java:100)
> 	at com.ctc.wstx.sw.BufferingXmlWriter.flush(BufferingXmlWriter.java:241)
> 	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:259)
> 	... 24 more
> {code}

On 2015-03-10 10:48:28 -0400, Joakim Erdfelt wrote:

> Jetty 8 is EOL (End of Life), no further work will be done on that version of Jetty.
> 
> Tested a configuration similar to attached.
> 
> Updated to use :
>   * Apache httpd 2.4.10 on Fedora 20
>   * Jetty 9.2.9.v20150224
>   * Java 1.7.0_75
> 
> Changes to pom in example project
>   * Removed all of the fusesource repos, as they always seem to produce problems in peoples builds
>   * Eliminated all of the OSGi goop (pax, felix, fabric8)
>   * Used released Camel 2.14.1
>   * Used recommended CXF 3.0.2 (recommended by Camel 2.14.1) 
> 
> This works, no long response times seen.
> 
> Considering this WORKSFORME on Jetty 9.

On 2015-03-10 21:40:18 -0400, Xiaohui Wu wrote:

> Joakim,
> Thanks for the confirming it is fixed on jetty 9.X.

On 2015-03-31 21:03:36 -0400, Greg Wilkins wrote:

> we'll have a look at this one.

On 2015-03-31 23:35:30 -0400, Greg Wilkins wrote:

> I'm not that familiar with camel... particularly the mvn camel:run command.
> Any chance you can give me a modification to that demo project that includes a main that I can run from a debugger?

On 2015-04-01 01:19:19 -0400, Greg Wilkins wrote:

> It appears I can reproduce this at will directly to your test project.
> If I do the curl operation directly to 9292 and then control-C it, 2 minutes later the server goes 100%.
> 
> The problem is definitely with sendContent as you have identified.
> 
> I have tried to reproduce on the current jetty-8 head, but not there is some more EoF protection.  I'm now trying to reproduce with 8.1.14

On 2015-04-01 01:49:12 -0400, Xiaohui Wu wrote:

> Greg,
> Thanks a lot for looking into this. 
> The fix for this bug looks fine to me. I think it resolved this issue.
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=445953
> 
> 
> Best Regards,
> Vicky

On 2015-04-01 01:55:25 -0400, Greg Wilkins wrote:

> I can't reproduce it in the same way with 8.1.14 directly with my own test harness, so your app is doing something I'm not fully understanding yet.
> 
> However, when I took the latest 8.1.17-SNAPSHOT and deployed in your application, I could not reproduce with a stopped curl.
> 
> Any chance you could test a recent build to see if it is also fixed in the full proxy environment?
> 
> Tomorrow I'll see if I can deploy an instrumented snap-shot in your app to see if I can understand more what is going on.

**Comment by joakime** [comment]
Fixed in Jetty 9.
Jetty 8 is EOL, closing.
