### ISSUE TITLE
Customization of WebSocket Server Connections via WebSocketPolicy

### ISSUE THREAD

**Issue by vijoshi** [eclipse/jetty.project#1811]
There are environments where Jetty serves a mix of HTTP and WebSocket clients needing to act as a single gateway for both types of clients (example - Apache Knox). There's a need to be able to apply special transport level properties (e.g. TCP keepAlive) when a server connection upgrades to a WebSocket. Currently `WebSocketServerConnection` uses `WebSocketPolicy` to apply WebSocket specific properties. Considering that WebSockets may commonly require different treatment with regards to their transport (channel/socket) properties vs HTTP connections, there needs to be a way to accomplish something like what overriding the `ServerConnector`'s `configure(Socket socket)` allows but kicking in only when a connection upgrades to a WebSocket. One way may be for `WebSocketPolicy` to include policy attributes for such transport/TCP level settings.

**Comment by vijoshi** [comment]
I would have by the way preferred to put this out on one of the mailing lists prior to opening the issue, but for the last few days have tried multiple times to subscribe to those but never got an email response asking/confirming  the subscription.

**Comment by joakime** [comment]
ServerConnector's `configure(Socket socket)` is inappropriate for HTTP Upgrade, as that happens far far later in the process.

TCP KeepAlive is a strange thing for WebSocket and when used is quickly dropped as being ineffective.

In practice, the TCP KeepAlive is off by default on all TCP implementations and must be turned on in code (both sides need to).  The TCP KeepAlive also has a stupidly long interval (like 2 hours per attempt).  The TCP KeepAlive is also only generally seen between proxies, not endpoints.

The IETF took these into account when they designed WebSocket and introduced the PING/PONG control frames to address the keepalive needs during WebSocket.

Also note that the TCP KeepAlive has no effect on the WebSocket idle timeouts.  If your WebSocket idle timeouts are shorter then your TCP KeepAlive then you will have a connection close well before TCP KeepAlive has even done anything.

That being said, you can use the `org.eclipse.jetty.websocket.servlet.WebSocketCreator` interface to control this.

eg:

``` java
public class SocketOptionsCreator implements WebSocketCreator
{
    @Override
    public Object createWebSocket(ServletUpgradeRequest req, ServletUpgradeResponse resp)
    {
        // TODO: check for null everywhere.
        EndPoint endpoint = HttpConnection.getCurrentConnection().getHttpChannel().getEndPoint();
        if(endpoint instanceof ChannelEndPoint)
        {
            ByteChannel channel = ((ChannelEndPoint) endpoint).getChannel();
            if(channel instanceof SocketChannel)
            {
                // TODO: handle IOException from setOption() call
                ((SocketChannel) channel).setOption(StandardSocketOptions.SO_KEEPALIVE, true);
            }
        }

        return new MySocket();
    }
}
```

The creator can be assigned to the `WebSocketFactory` passed into the `WebSocketServlet.configure()` method ...

eg

``` java
public class SocketOptionsServlet extends WebSocketServlet
{
    @Override
    public void configure(WebSocketServletFactory factory)
    {
        factory.setCreator(new SocketOptionsCreator());
    }
}
```

or if you are using the `WebSocketUpgradeFilter` you can use your custom creator there as well.

``` java
public class SocketOptionsListener implements ServletContextListener
{
    @Override
    public void contextInitialized(ServletContextEvent sce)
    {
        WebSocketUpgradeFilter wsfilter = (WebSocketUpgradeFilter) sce.getServletContext()
                .getAttribute(WebSocketUpgradeFilter.class.getName());
        wsfilter.addMapping(new ServletPathSpec("/myecho"), new SocketOptionsCreator());
    }
}
```

**Comment by joakime** [comment]
Also, if the WebSocket connection goes through a web proxy, then the TCP KeepAlive settings and behaviors do not propagate.

**Comment by vijoshi** [comment]
@joakime - thanks for the detailed response!

**Comment by joakime** [comment]
Note, you don't need to use `WebSocketServletFactory.register(Class)`.
The `WebSocketServletFactory` is a `WebSocketCreator` itself, and all the `.register(Class)` method does is register the specific class you want that creator to use.

Since you'll be providing your own `WebSocketCreator`, the `.register(Class)` no longer has any effect.

**Comment by joakime** [comment]
Closing as answered.  Feel free to reopen if you feel the need.
