### ISSUE TITLE
Update Garbage Collection documentation to reflect JDK9 changes

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1813]
Current documentation on tuning the JVM, specifically Garbage Collection makes reference to parameters that are deprecated in Java 9. Needs reviewed for content and updated parameter values, such as `-Xlog: gc*`.

**Comment by sbordet** [comment]
@WalkerWatch, I have pushed updated documentation for your review. I also removed incorrect and non-relevant sections.
