### ISSUE TITLE
WebSocket test failures

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1815]
From Jenkins:

* org.eclipse.jetty.websocket.server.WebSocketUpgradeFilterTest.testStopStartOfHandler[wsuf/WebAppContext/web.xml/Servlet.init] (build 898-899)
* org.eclipse.jetty.websocket.server.DecoratorsLegacyTest.testAccessRequestCookies (build 895)
* org.eclipse.jetty.websocket.server.WebSocketUpgradeFilterTest.testStopStartOfHandler[wsuf/WebAppContext/web.xml/ServletContextListener/alt-config] (build 894)

**Comment by joakime** [comment]
Tests are currently set to `@Ignore` by commit ac27762
