### ISSUE TITLE
Infinispan tests failing with JDK 9

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1818]
@janbartel, can you please review these tests from Infinispan:

* ClusteredLastAccessTimeTest
* ClusteredSessionScavengingTest

They use an old version of Infinispan (7.1.1.Final) that tries to use a `sun.*` class, which cannot be loaded by JDK 9.
The latest version of Infinispan is 9.1.0.Final and has a different API than 7.1.1.Final, but is probably JDK 9 compliant.

I have currently "disabled" the test for JDK 9 only using JUnit's Assume. Feel free to remove it when the test works with JDK 9 as well.

**Comment by janbartel** [comment]
I've begun the process for asking permission from Eclipse to use infinispan 9.1.0.Final jars in a works-with capacity (compile and test only, no distribution).

It looks like it will be possible to keep compiling the jetty-infinispan module against version 7.1.1, but use 9.1.0 for tests/test-sessions/test-infinispan-sessions tests.

**Comment by janbartel** [comment]
Updated tests to use infinispan-9.1.0.

Also created new modules "session-store-infinispan-embedded-910" and "session-store-infinispan-remote-910" that use the new infinispan-9.1.0 jars. The existing "session-store-infinispan-embedded" and "session-store-infinispan-remote" (that use infinispan-7.1.1) are unaffected.
