### ISSUE TITLE
ResourceHandler with ranged requests does not return Content-Type response header

### ISSUE THREAD

**Issue by harringtonp** [eclipse/jetty.project#1823]
I was running Jetty 9.2 and added an explicit mime type which set the content type for mp4 when sending movies back to the client. This worked fine. I then had to upgrade to Jetty 9.4.6 and set range request to true so I could get Safari to play mp4. This also works fine. However since applying the upgrade the content type for mp4 is no longer sent back to the client. Why ?

``` java
  // Add a handler for statically served content
  ResourceHandler resourceHandler = new ResourceHandler();

  MimeTypes mimeTypes = new MimeTypes();
  mimeTypes.addMimeMapping("mp4", "video/mp4");
  resourceHandler.setMimeTypes(mimeTypes);

  resourceHandler.setAcceptRanges(true);
  resourceHandler.setResourceBase("content");
  handlerCollection.addHandler(resourceHandler);

  // This handle will deal with unhandled requests in the server. For requests for favicon.ico, the Jetty icon is served. 
  // For all other requests a normal 404 is served.
  handlerCollection.addHandler(new DefaultHandler());
```

**Comment by joakime** [comment]
Do you have an example of the request headers + response headers for when this happens?

**Comment by harringtonp** [comment]
Hi,

I've used curl to demo a request and response, the content-type header is
missing. Output shown below.

I've also attached the entire jetty server code I use as it is a very
simple application of jetty.

Paul

---

paulh@ubuntu1404:~$ curl -v --range 101-150 127.0.0.1:8001/demo.mp4 -o
/dev/null
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> GET /demo.mp4 HTTP/1.1
> Range: bytes=101-150
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8001
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Date: Sat, 16 Sep 2017 12:55:24 GMT
< Last-Modified: Thu, 14 Sep 2017 15:25:01 GMT
< Accept-Ranges: bytes
< Content-Range: bytes 101-150/1493419
< Content-Length: 50
* Server Jetty(9.4.6.v20170531) is not blacklisted
< Server: Jetty(9.4.6.v20170531)
<
{ [data not shown]
100    50  100    50    0     0    334      0 --:--:-- --:--:-- --:--:--
347
* Connection #0 to host 127.0.0.1 left intact
paulh@ubuntu1404:~$

**Comment by gregw** [comment]
I tried to  reproduce by running the embedded FileServer example and I got the following output:
```
gregw@Tile440: ~
[2004] curl -v 127.0.0.1:8080/VERSION.txt -o /dev/null
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /VERSION.txt HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 19 Sep 2017 06:54:54 GMT
< Last-Modified: Tue, 19 Sep 2017 03:45:19 GMT
< Content-Type: text/plain
< Accept-Ranges: bytes
< Content-Length: 488292
< Server: Jetty(9.4.z-SNAPSHOT)
< 
{ [16179 bytes data]
100  476k  100  476k    0     0   181M      0 --:--:-- --:--:-- --:--:--  232M
* Connection #0 to host 127.0.0.1 left intact

gregw@Tile440: ~
[2005] curl -v --range 10-20 127.0.0.1:8080/VERSION.txt -o /dev/null
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /VERSION.txt HTTP/1.1
> Host: 127.0.0.1:8080
> Range: bytes=10-20
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 206 Partial Content
< Date: Tue, 19 Sep 2017 06:55:04 GMT
< Last-Modified: Tue, 19 Sep 2017 03:45:19 GMT
< Content-Type: text/plain
< Accept-Ranges: bytes
< Content-Range: bytes 10-20/488292
< Content-Length: 11
< Server: Jetty(9.4.z-SNAPSHOT)
< 
{ [11 bytes data]
100    11  100    11    0     0   1147      0 --:--:-- --:--:-- --:--:--  1222
* Connection #0 to host 127.0.0.1 left intact
```

So there is a content type for that.  I also tried the default servlet in a standard deployment and that worked fine as well.

Can you experiment with the FileServer code from a jetty checkout and come up with a reproduction that I can try?    I'll try your code now....

**Comment by gregw** [comment]
@harringtonp I've found the problem - firstly we should define mp4 by default now, but then the ResourceHandler is ignoring the set mimetypes and using the one from the context.   I'll have a fix for both in the next release, but for now you can work around by using a `ContextHandler`.  Note also you should use a HandlerList rather than a HandlerCollection, so the following code works for me:
```
    public static void main(String[] args) throws Exception
    {
        ResourceHandler resourceHandler = new ResourceHandler();

        MimeTypes mimeTypes = new MimeTypes();
        mimeTypes.addMimeMapping("mp4", "video/mp4");

        ContextHandler context = new ContextHandler("/");
        context.setMimeTypes(mimeTypes);

        resourceHandler.setAcceptRanges(true);
        resourceHandler.setResourceBase("/tmp");
        context.setHandler(resourceHandler);

        HandlerList handlers = new HandlerList();
        handlers.addHandler(context);
        handlers.addHandler(new DefaultHandler());

        Server server = new Server(8080);
        server.setHandler(handlers);

        server.start();
        server.join();
    }
```

**Comment by harringtonp** [comment]
Thanks guys. Worked

Paul.
