### ISSUE TITLE
Order WEB-INF/lib jars before adding to classpath

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1828]
See PR #1824 .

We are listing the contents of WEB-INF/lib twice: once in WebInfConfiguration in preconfigure() to find jars to apply an initial ordering to for the purposes of discovering taglibs, resources, fragments and annotations; and then again in WebInfConfiguration.configure() when we form up the classpath.  We should only do the listing once (and as per the PR, the listing should be ordered).

**Comment by janbartel** [comment]
PR applied for jetty 9.4.8 and above.

**Comment by joakime** [comment]
Closing.
This was not feasible in the past.
PR #1824 committed to 9.4.8 only solves for simple webapps (that don't have descriptor order, extra classpath, library specific classloaders, etc..)
And newer JVMs (Java 9+) makes the hack in the above PR no longer work.

**Comment by jglick** [comment]
> newer JVMs (Java 9+) makes the hack in the above PR no longer work

I am not sure what is meant by this, could you elaborate?

**Comment by joakime** [comment]
Behavior of loading classes can no longer be ordered within a single Classloader.
You can only control loading order of classes via the Classloader parent hierachy. (parent interrogated first)
The newer the JVM the less likely you are even able to have the same class in two different jars. (newer JVMs will fail the Classloader if detected).

We are not the only group to notice this, all other containers have made the same discovery.
Ordered classloaders have even been removed in other containers as a result.
