### ISSUE TITLE
Improve direct buffer usage/configurability

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#183]
migrated from Bugzilla [#458236](https://bugs.eclipse.org/bugs/show_bug.cgi?id=458236)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Greg Wilkins

On 2015-01-23 05:41:16 -0500, Greg Wilkins wrote:

> Make it easier to user/configure direct buffer usage (or not use)

**Comment by jmcc0nn3ll** [comment]
plenty of enhancements in IO since this issue was originally opened in bugzilla

**Comment by sbordet** [comment]
Yet still not done.

**Comment by sbordet** [comment]
Closed in favor of #3952 and #3953.
