### ISSUE TITLE
Document Conscrypt SSL

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1830]
Document the Conscrypt SSL module and associated implementation per #215

**Comment by travisspencer** [comment]
I didn't find anything in those updated docs, @WalkerWatch , about how to use Conscrypt with Jetty when embedding Jetty. Is that due to my lack of knowledge about modules or did I just miss it in your patch or is that part of the docs TBD?

**Comment by WalkerWatch** [comment]
@travisspencer Sorry about that, I will get it added. It is actually quite easy to do - simply instantiate an instance of Concrypt's OpenSSLProvider and add it as a provider to the JVM Security class. After that, add `Conscrypt` as the provider in Jetty's sslContextFactory.

**Comment by travisspencer** [comment]
That sounds very easy, @WalkerWatch . Thanks for the info and the update to the docs!

**Comment by gregw** [comment]
We need to document client side usage as well
