### ISSUE TITLE
Locker is not reentrant on ServerConnector#setConnectionFactories

### ISSUE THREAD

**Issue by mneedham** [eclipse/jetty.project#1835]
[version: 9.4.7.v20170914]

Hi,

I have the following code snippet to try and start a Jetty server:

```
import java.util.Collections;

import org.eclipse.jetty.server.HttpConnectionFactory;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;

public class JettyThing
{
    public static void main( String[] args ) throws Exception
    {
        Server server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setConnectionFactories( Collections.singletonList( new HttpConnectionFactory() ) );
        server.start();
    }
}
```

```
 <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
      <version>9.4.7.v20170914</version>
    </dependency>
```

When I run the main method I get this exception:

```
Exception in thread "main" java.lang.IllegalStateException: Locker is not reentrant
	at org.eclipse.jetty.util.thread.Locker.lock(Locker.java:47)
	at org.eclipse.jetty.server.AbstractConnector.removeConnectionFactory(AbstractConnector.java:465)
	at org.eclipse.jetty.server.AbstractConnector.setConnectionFactories(AbstractConnector.java:488)
	at JettyThing.main(JettyThing.java:13)
```

From looking at the code around there it seems like there are embedded try with resources blocks trying to acquire a lock but the same thread isn't allowed to acquire the lock if it already has it.

https://github.com/eclipse/jetty.project/blame/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java#L482

It looks like the change in that area of the code was in this commit:
https://github.com/eclipse/jetty.project/commit/5197ce4f543d0b6aa9ed7f4c4ff5e7429c4568ed

Any ideas?

Thanks, Mark

cc @praveenag

**Comment by sbordet** [comment]
@gregw see #1836.

**Comment by gregw** [comment]
While #1836 will certainly solve the problem, it is unclear to me why that class is so heavily mutexed on connection factories.  They should not be changed once the connection is started?
