### ISSUE TITLE
Review Locker

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1836]
Class `Locker` has gone through quite some refactorings over the years.

It was supposed to implement a spin lock _and_ a regular lock; because of that, it was made non-reentrant.
Then we figured out spin locks were not that great, so we removed them.

Right now it's just a thin wrapper around JDK's `ReentrantLock`, and it has a weird JVM-wide singleton that is used when `lockIfNotHeld()` is used that seems wrong to me.

I propose to clean it up by being just a tiny wrapper around JDK's `ReentrantLock`, and therefore remove the non-reentrancy (therefore making it reentrant), remove the singleton, remove `lockIfNotHeld()`, and keep the `AutoCloseable` feature.

**Comment by gregw** [comment]
@sbordet,

i agree. but need to keep api same in 9.4 and remove unneeded methods in
10.x
