### ISSUE TITLE
ConnectionStatistics should be backward compatible to deprecated ConnectorStatistics

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1837]
Currently the [`org.eclipse.jetty.io.ConnectionStatistics`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.v20170914/jetty-io/src/main/java/org/eclipse/jetty/io/ConnectionStatistics.java) is the replacement of the now deprecated [`org.eclipse.jetty.server.ConnectorStatistics`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.v20170914/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectorStatistics.java).

The methods in question:

ConnectorStatistics | ConnectionStatistics
------------------- | --------------------
long getConnectionDurationMax() | long getConnectionDurationMax()
double getConnectionDurationMean() | long getConnectionDurationMean()
double getConnectionDurationStdDev() | long getConnectionDurationStdDev()
int getConnections() | long getConnections()
int getConnectionsOpen() | long getConnectionsTotal()
int getConnectionsOpenMax() | long getConnectionsMax()
int getMessagesIn() | long getReceivedMessages()
int getMessagesInPerConnectionMax() | n/a
double getMessagesInPerConnectionMean() | n/a
double getMessagesInPerConnectionStdDev() | n/a
int getMessagesInPerSecond() | long getReceivedMessagesRate()
int getMessagesOut() | long getSentMessages()
int getMessagesOutPerConnectionMax() | n/a
double getMessagesOutPerConnectionMean() | n/a 
double getMessagesOutPerConnectionStdDev() | n/a
int getMessagesOutPerSecond() | long getSentMessagesRate()
long getStartedMillis() | n/a
n/a | long getReceivedBytes()
n/a | long getReceivedBytesRate()
n/a | long getSentBytes()
n/a | long getSentBytesRate()

It seems the older `ConnectorStatistics` used the `org.eclipse.jetty.util.statistic.SampleStatistic` object to track Total / Max / Mean / StdDev, but the newer `ConnectionStatistics` does not use if for the majority of cases.  

Was there a technical reason for this? (I can imagine there being an ugly contention on the update of `SampleStatistics` which prevented this kind of usage)

**Comment by joakime** [comment]
@sbordet you were the last one to update `ConnectionStatistics`, did you have a specific reason for not using `SampleStatistics` class to gain the Max / Mean / StdDev calculations?

**Comment by sbordet** [comment]
The only reason to use `SampleStatistics` was to implement methods that named `*PerConnection*`.
IIRC we discussed that these methods don't make much sense, so we removed them.

A couple of methods have the correspondent:

| ConnectorStatistics | ConnectionStatistics |
| --- | --- |
| int getMessagesInPerSecond() | long getReceivedMessagesRate() |
| int getMessagesOutPerSecond() | long getSentMessagesRate() |

**Comment by kviphong** [comment]
Is it possible to get back those *PerConnection* stats like in ConnectorStatistics?

**Comment by sbordet** [comment]
@kviphong they don't make much sense, as for example a HTTP/1.0 or HTTP/2 client will skew the average and stddev so much to render the statistic useless.

Also, as I'm looking at `ConnectorStatistics`, I see copy/paste errors that make those numbers even more wrong :/ (the _out_ methods actually return _in_ numbers).

**Comment by kviphong** [comment]
Thanks for the info @sbordet .

Another method my team is using in the deprecated class is getStartedMillis(). Any chance to have this back?

**Comment by joakime** [comment]
Note: `.getStartedMillis()` is the time (in milliseconds) since last `.reset()`

**Comment by joakime** [comment]
Updated the top level comment with the corrected table, per new information from @sbordet 

@WalkerWatch is that information (in the first comment) suitable for the porting guide?

**Comment by joakime** [comment]
@sbordet would a HTTP Version specific API be meaningful?

something like this ...

``` java
int getReceivedMessages(HttpVersion version)
int getReceivedMessagesMax(HttpVersion version)
double getReceivedMessagesMean(HttpVersion version)
double getReceivedMessagesStdDev(HttpVersion version)
```

**Comment by sbordet** [comment]
@joakime `ConnectionStatistics` _is-a_ `Connection.Listener`, so it can be added to a specific `ConnectionFactory` if you're interested in statistics grouped by HTTP version.

**Comment by sbordet** [comment]
@kviphong because of the removal of `*PerConnection*` methods, `getStartedMillis()` and `reset()` are not needed anymore.
The `*Rate` methods now calculate the rate between each invocation.

**Comment by kviphong** [comment]
@sbordet 
The way we use getStartedMillis() is to track how long the connection stats have been tracked, since last reset. (I'm not sure why we are tracking this TBH, just trying to archive one to one mapping when moving to ConnectionStatistics).

**Comment by joakime** [comment]
Sounds like this issue is not needed, as new class supports features in different way.
Closing.
