### ISSUE TITLE
Servlet 4.0.0 artifact now available on central.maven.org

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1838]
For Jetty 10.x the Servlet 4.0.0 artifact is now available (we don't have to use the `4.0.0-b07` version anymore)

See http://central.maven.org/maven2/javax/servlet/javax.servlet-api/4.0.0/

``` xml
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
    <version>4.0.0</version>
</dependency>
```

The [eclipse/jetty.toolchain/jetty-schemas](/eclipse/jetty.toolchain/tree/master/jetty-schemas) will need to be updated too.

**Comment by janbartel** [comment]
Fixed in master branch for jetty-10.
