### ISSUE TITLE
Reduce contention on ServletHolder

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1841]
On large machines (>=32 cores) there is some contention seen on ServletHolder.ensureServlet.

**Comment by gregw** [comment]
The holder class has not changed in many years and probably needs a full review, but there are some simple changes we can do in the short term

**Comment by joakime** [comment]
@gregw did you mean to close this so quickly after opening it?

**Comment by gregw** [comment]
@joakime no but the commit went in just after, so no need to reopen.  It is fixed for now and while further review is needed, I don't think keeping the issue open will help with that... as wider review is needed always
