### ISSUE TITLE
Implement RFC 7239 (Forwarded header)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#185]
migrated from Bugzilla [#461578](https://bugs.eclipse.org/bugs/show_bug.cgi?id=461578)
status ASSIGNED severity *enhancement* in component *proxy* for *9.3.x*
Reported in version *9.3.0* on platform *All*
Assigned to: Simone Bordet

On 2015-03-06 06:59:36 -0500, Simone Bordet wrote:

> http://tools.ietf.org/html/rfc7239.
> 
> Currently the proxy servlets use the old format of "X-Forwarded-*", but the new format should be there too.

**Comment by joakime** [comment]
For those looking for Help Wanted work, this work on this should be done in the [ForwardedRequestCustomizer](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java) class.
