### ISSUE TITLE
Augment security documentation with security constraints

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1850]
Update the configuring-security-authentication.html page with more explicit info about configuring security constraints, in addition to configuring the realm.

**Comment by janbartel** [comment]
Those additions look great.

Can we also add a section on how to totally configure the security in a context xml file, ie not using web.xml at all?  And I suppose a section on how to do it equivalently programmatically (note there's example code that might be useful in https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/SecuredHelloHandler.java).

**Comment by janbartel** [comment]
Chris, here's an example of a context xml file that sets up all the security, no web.xml needed.
[context.txt](https://github.com/eclipse/jetty.project/files/1339373/context.txt)

**Comment by gouessej** [comment]
@janbartel What happens when you define the roles in multiple places, for example both in web.xml with `<security-role>` & `role-name` and in a database (JDBCLoginService) or both in web.xml and in a context file? Is it possible and advised to avoid putting the roles into several files or means? Can I use a role defined in the database in `<security-constraint><auth-constraint>` in web.xml?

**Comment by janbartel** [comment]
@gouessej  when a security-role is defined in web.xml, the ConstraintSecurityHandler.addRole(String) method is called. You would call the same method if you were defining security roles in a context xml file. The roles are held in a set, so there are no duplicates.  

I don't understand your question about JDBCLoginService - that is not defining roles for the webapp, that is defining roles that are possessed by a user.

In general, jetty has been forgiving about requiring all roles to be defined in security-role elements in web.xml, however, with the advent of servlet 3.1 and new security constraints of "**" and particularly "*" if you want to use those security constraints then you should define all roles in security-role elements in your web.xml (or in your context xml if you're not using web.xml).

As insinuated by the last sentence, I would always recommend that you declare all roles in one file only: either web.xml or in a context xml file if you can't use web.xml. Or alternatively of course there's annotations.

**Comment by gouessej** [comment]
Actually, I use HttpServletRequest.isUserInRole(final String role) to check whether the authenticated (using a form) user is in a role, this role is only mentioned in the database and not in web.xml. I configure JDBCLoginService in the context file of the webapp. I can use web.xml.

If I understand what you wrote, I'll have to define the roles either in web.xml or in a context xml file and JDBCLoginService just tells which roles are possessed by a user. "Defining" the roles only in the database isn't enough, they have to be defined elsewhere.

**Comment by janbartel** [comment]
@gouessej almost correct. Yes, you obviously have to define the authentication and authorization information that your chosen LoginService accesses. Then, you need to declare all the roles that may be referenced programmatically or declaratively in web.xml IFF you use *  in your security constraints, or you map those names using security-role-refs.  If you don't do any of those things, jetty will use the role name you supply to isUserInRole  to check against the auth info supplied by the LoginService.
