### ISSUE TITLE
Improve insufficient thread warnings/errors

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1851]
If a server or client is configured with a threadpool containing insufficient threads, then an informative warning and/or error should occur

**Comment by gregw** [comment]
Branch jetty-9.4.x-1851-ThreadBudget has an improved thread usage warning.   Instead of a heuristic hard coded in the server, there is now a ThreadBudget.Allocation interface that components can implement to declare how many threads they will need.

**Comment by gregw** [comment]
@sbordet review needed, specially on the client side.

**Comment by gregw** [comment]
@sbordet I had to take an entirely different approach.   There are now leases on threads taken to express commitments.

**Comment by sbordet** [comment]
@gregw I think we must also call `leaseTo()` from the `SelectorManager` for the number of selectors.

These threads will be blocked in `select()` and therefore unavailable, especially in a shared thread pool scenario (e.g. one `HttpClient` is completely idle, but "steals" a number of selector threads, while another `HttpClient` is active and will not have enough threads).

Also, should `Server` lease one thread ? The minimal case would be 1 acceptor, 1 selector, 0 reserved, but there must be one more thread to run the request.

Furthermore, I'd like to rename `ThreadPool.SizedThreadPool` to just `ThreadPool.Sized` and `ThreadBudget` to `ThreadPoolBudget`.

**Comment by gregw** [comment]
Good point on the selectors....
I'm neutral on the name changes... they are better names, but perhaps only rename in jetty-10?

Note that minimal is 0 acceptors, as we can do async accepting.

I don't think the Server should lease a thread, as we have the warnAt margin.  If you have < warnAt (defaults to number of CPUs) then you get a warning, which becomes an error at 0.  So if no threads available to handle requests, that is already a hard error

**Comment by sbordet** [comment]
@gregw I added leasing on selectors and renamed `ThreadBudget` to `ThreadPoolBudget` (which is a newly introduced class never released and does not need deprecation).
Added a test case for multiple `HttpClient`s sharing the same `ThreadPool`.
