### ISSUE TITLE
GZIPContentTransformer fails to send entire message if used with BufferedContentTransformer

### ISSUE THREAD

**Issue by shauntarves** [eclipse/jetty.project#1857]
When using the `AsyncMiddleManServlet`, if the server response is gzipped and chunked, it's necessary to use the `GZIPContentTransformer` together with some type of a `BufferedContentTransformer` to collect the entire response before further transformation. This generally works on the basis of doing some meaningful transformation _only_ when the `finished` parameter is true.

However, because of some of the logic in the provided `GZIPContentTransformer`, the call to `transformer.transform(input, true, output)` doesn't always get made with the correct content. Here's an example:

When requesting a gzipped, chunked css file from the target server, the responses are received like this:
```
HttpResponse[HTTP/1.1 200 null]@5a4dfa30
Content-Type: text/css;charset=UTF-8
Content-Encoding: gzip
Content-Length: 19021

...

received server content: 10 bytes
downstream content transformation 10 -> 0 bytes
received server content: 8096 bytes
downstream content transformation 8096 -> 0 bytes
received server content: 8096 bytes
downstream content transformation 8096 -> 0 bytes
received server content: 2811 bytes
downstream content transformation 2811 -> 0 bytes
received server content: 8 bytes
downstream content transformation 8 -> 20 bytes
```
The response succeeds, but it's not the correct content length (should be 19021 bytes, or at worst, 19003 bytes as the first and last request decode to a zero-byte buffer). This seems to occur because the last chunk of 8 bytes is empty when decoded so the call to the internal (buffered) transformer with a finished value of true never gets called.

```java
if (decoded.hasRemaining()) { // <--- this is false for the last input buffer of 8 bytes
    transformer.transform(decoded, finished && !input.hasRemaining(), buffers);
}
```

**Comment by sbordet** [comment]
I tried, but could not reproduce a case where `input>0` but `decoded=0`.
I guess it may happen though, so I'm changing the logic to:

```java
boolean done = finished && !input.hasRemaining();
if (decoded.hasRemaining() || done) {
    transformer.transform(decoded, done, buffers);
}
```

**Comment by sbordet** [comment]
@shauntarves are you able to test the latest code to confirm the issue is fixed ?

**Comment by shauntarves** [comment]
Yes, this change fixed the problem. Here's the log for the same request as above

`2017-10-03 15:08:42,168 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipping 10 bytes, finished=false`
`2017-10-03 15:08:42,170 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipped 0 bytes, complete=false`
`2017-10-03 15:08:42,171 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipping 8096 bytes, finished=false`
`2017-10-03 15:08:42,172 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipped 41516 bytes, complete=false`
`2017-10-03 15:08:42,172 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipping 8096 bytes, finished=false`
`2017-10-03 15:08:42,172 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipped 44720 bytes, complete=false`
`2017-10-03 15:08:42,173 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipping 2811 bytes, finished=false`
`2017-10-03 15:08:42,173 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipped 10971 bytes, complete=false`
`2017-10-03 15:08:42,173 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipping 8 bytes, finished=true`
`2017-10-03 15:08:42,173 [pool-82-thread-8] DEBUG GZIPContentTransformer - Ungzipped 0 bytes, complete=true`

**Comment by sbordet** [comment]
Thanks for confirming the fix!
