### ISSUE TITLE
when the request cross the jetty9, it has two same key of some attributes in request header

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#186]
migrated from Bugzilla [#462071](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462071)
status ASSIGNED severity *normal* in component *client* for *9.2.x*
Reported in version *9.2.9* on platform *PC*
Assigned to: Simone Bordet

On 2015-03-13 09:53:09 -0400, Yuffie Chow wrote:

> when the request cross the jetty9 from camel-2.15.0, it has two same key of some attributes in request header like the follows:
> --------------this one has two User-Agent,Accept-Encoding
> Accept-Encoding: gzip
> User-Agent: Jetty/9.2.9.v20150224
> Accept: */*
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: zh-CN,zh;q=0.8
> Cookie: ASP.NET_SessionId=jc412f45qx2mqw55ivfuhljm
> dnt: 1
> Referer: http://localhost:8080/MobileService/
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
> x-requested-with: XMLHttpRequest
> -------------------------------------------------------------
> -------------------with two SAME cookie
> Accept-Encoding: gzip
> Content-Type: application/json
> Accept: */*
> Accept-Encoding: gzip, deflate
> Accept-Language: zh-CN,zh;q=0.8
> Cookie: ASP.NET_SessionId=hv5tiq55muv1ki55esc2hi45
> DNT: 1
> Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
> Cookie: ASP.NET_SessionId=hv5tiq55muv1ki55esc2hi45
> --------------------------------------------

On 2015-03-13 11:18:38 -0400, Simone Bordet wrote:

> More information is needed, since as explained this could well be a Camel issue, not a Jetty issue.
> 
> Do you have a reproducible test case ?

On 2015-03-13 14:07:29 -0400, Joakim Erdfelt wrote:

> downgrading importance to normal (as this is not yet reproducible in normal operation of jetty-client)

**Comment by joakime** [comment]
Now a year old, with no reproducible test case provided.
Closing.

Feel free to reopen if you can provide a test case.
