### ISSUE TITLE
ContextHandler ignores set contextPath when doHandle is called manually

### ISSUE THREAD

**Issue by tipsy** [eclipse/jetty.project#1869]
I'm using a `ContextHandler` and calling `doHandle()` manually. This works fine, but if I try to set a the context-path using `ContextHandler#setContextPath`, it gets ignored. There are no error messages or exceptions.

(My end goal is to be able to use `ResourceHandler` with a context-path)

**Comment by gregw** [comment]
@tipsy I can assure you that `setContextPath` works, so it is probably something about how/when you are calling it.   Have a look at the examples: 
 - [ManyContexts](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyContexts.java)
 - [FileServer](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/FileServer.java)

If you can't work it out there, please re-open this issue with what version your are using and a snippet of  your code.

**Comment by joakime** [comment]
@tipsy if you have a `ServletContextHandler` (a great class btw!) you really don't want to be using `ResourceHandler` intermixed with it, either inside or outside.

If you are sticking with `ServletContextHandler` (as evidenced from your other issue), consider using alternate (named!) `DefaultServlet` configurations and `RequestDispatcher` to forward to that servlet to handle the request.

Keep in mind that once you enter a `ServletContextHandler` you never leave it, there is no next handler, all requests in a `ServletContextHandler` are "handled" by that `ServletContextHandler` and no further Jetty handlers execute.

If you are not using `ServletContextHandler` then you'll have much better luck using the standard Jetty `Handler` layers properly and let them do their own thing, falling through, nesting, context awareness, virtual host awareness, scope awareness, etc.  This is how Spark and Jetty operate for everything.

If you still have a need to have a manual call to a jetty class, to serve static files, outside of the `ServletContextHandler`, consider using [`ResourceService`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java) and a call its `doGet()` from your own handler instead (don't forget to `setHandled(true)` in your handler)
