### ISSUE TITLE
Automatic-Module-Name header needed for Java 9

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1873]
See discussion about this on cross-project-issues-dev ...
https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg14888.html

**Comment by joakime** [comment]
Since we create `META-INF/MANIFEST.MF` entries for OSGi, we should also be careful to add the `Automatic-Module-Name` header that Java 9 uses.

The OSGI `Bundle-SymbolicName` header and the Java 9 `Automatic-Module-Name` header have the same meaning, and when the 2 systems co-exist, this meaning should be kept in sync.

See the cross-project-issues-dev discussion on this topic from the first comment.

**Comment by sbordet** [comment]
Duplicate of #2127.
