### ISSUE TITLE
How to push a custom number of video segments for each request with HTTP/2?

### ISSUE THREAD

**Issue by Ali4uk** [eclipse/jetty.project#1875]

**Comment by sbordet** [comment]
The description is really lacking.
From the title it's not clear what you want to do.
You want to provide a detailed explanation of your problem if you want to have a chance of a reply.

**Comment by Ali4uk** [comment]
Thank you Simone, my question is about what I should modify in the jetty server to let it push k-segments at once for each request. Suppose the client requesting for dash video segments.
Kind regards

**Comment by sbordet** [comment]
@Ali4uk it's not enough. You have to detail exactly how the whole thing works, what is a "k-segment" and a "dash video segment" and how the protocol of requesting a video segment work.

**Comment by joakime** [comment]
Closing due to lack of followup
