### ISSUE TITLE
Website: jetty-build@eclipse.org links to jetty-commit.

### ISSUE THREAD

**Issue by jhansen2015** [eclipse/jetty.project#1877]
On the website's mailing lists page, the link for jetty-build@eclipse.org links to jetty-commit.
https://www.eclipse.org/jetty/mailinglists.html

**Comment by WalkerWatch** [comment]
Removed the jetty-build and jetty-commit mailing list information from Jetty site (a48f0761776ea9540b37d55e2980c3aaff8c52bd). Both are unused.
