### ISSUE TITLE
reconsider recycling of HttpURI and MetaData classes

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#188]
migrated from Bugzilla [#462515](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462515)
status ASSIGNED severity _enhancement_ in component _server_ for _9.2.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Greg Wilkins

On 2015-03-18 21:12:26 -0400, Greg Wilkins wrote:

> The HttpConnection recycles the HttpURI and MetaData.Request instances.
> This is not used in HTTP2 nor FCGI.
> 
> There can be significant benefits in both complexity and performance by having immutable instances.
> 
> However, there is the issue of the HttpFields class being a part of the metadata, as this is also recycled.     There is also the issue of rewriting handlers that modify the metadata (URI and fields), so a strictly immutable metadata instance would required further copying.
> 
> If it proves too difficult to have a strictly immutable meta data and uri, then perhaps HTTP2 should consider recycling as well?

**Comment by sbordet** [comment]
Recycling in HTTP/2 has proven to be challenging. Closing this one, eventually we can reconsider it.
