### ISSUE TITLE
HttpClient missing setAuthenticationStore()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1880]
There seems to be a missing `.setAuthenticationStore(AuthenticationStore store)` method for `HttpClient` to allow for custom implementations of `AuthenticationStore`.

**Comment by sbordet** [comment]
@joakime what code are you looking at ? This was fixed recently in #212.

**Comment by joakime** [comment]
Jetty 9.4.7.v20170914 release.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.v20170914/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java

We can access the default AuthenticationStore via `getAuthenticationStore`, but not set it to a custom one.

**Comment by joakime** [comment]
The [commit](https://github.com/eclipse/jetty.project/commit/aa4a77794e5c00dc6c56f5e40172f396d04fe7d4) for issue #212 doesn't add a `.setAuthenticationStore()` method.

**Comment by sbordet** [comment]
@joakime there are two commits, the one that adds `setAuthenticationStore()` is ce9be291d30c02c773372cf27ead51883d3a38b6.

**Comment by joakime** [comment]
Fair enough.  So it's not available in a release yet.
Closing as duplicate of #212
