### ISSUE TITLE
getMaxInactiveInterval returns 0 after session is configured with a negative maxInactiveInterval

### ISSUE THREAD

**Issue by upthewaterspout** [eclipse/jetty.project#1885]
If sessions are configured to use a negative session timeout using SessionHandler.setMaxInactiveInterval(), we would expect Session.getMaxInactiveInterval() to also return a negative number, indicating that the session will not expire.

Unfortunately, SessionHandler.newSession converts any negative number to -1, here
```java
Session session = _sessionCache.newSession(request, id, created,  (_dftMaxIdleSecs>0?_dftMaxIdleSecs*1000L:-1));
```

And Session.getMaxInactiveInterval divides this number (-1) by 1000, which rounds up to 0:
```java
return (int)(maxInactiveMs < 0 ? -1 : maxInactiveMs /1000);
```

So configuring any negative value for maxInactiveInterval will result in getMaxInactiveInterval returning 0.

**Comment by janbartel** [comment]
Merged, thanks.
