### ISSUE TITLE
CrossOriginFilter does not return "*" even if allowedOrigins="*"

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#189]
migrated from Bugzilla [#462653](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462653)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.2.9* on platform *PC*
Assigned to: Simone Bordet

On 2015-03-20 06:38:52 -0400, Simon Oberhammer wrote:

> Defaulting allowCredentials=true is dangerous because it allows foreign scripts to access the cookie values. It's not just that the client can send the cookies (as was discussed in # 355103) but it also allows JavaScript from a foreign domain to read the cookie values (they can read the whole response).
> 
> I would have expected it to default to false and only allow cookie requests from foreign origins if the server maintainer decides to explictly allow it.
> 
> ---
> 
> Defaulting to true was discused in https://bugs.eclipse.org/bugs/show_bug.cgi?id=355103 and is currently implemented (although the javadoc says the default is false) https://github.com/eclipse/jetty.project/blob/master/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java#L186

On 2015-03-25 05:21:28 -0400, Simone Bordet wrote:

> There are 2 domains, a.com and b.com.
> You control CORS on b.com.
> 
> A script downloaded from a.com now makes a XHR request to b.com.
> If you don't want to accept requests from scripts downloaded from a.com, then in the CORS configuration for b.com you don't allow the a.com domain.
> Currently all domains are allowed, so your reasoning about the "openness" of allowCredentials would apply even more to allowedOrigins.
> 
> Same goes for methods, headers, etc.: they all have relaxed settings to allow easier interoperability of scripts, as opposed to negate everything and require a more complicated setup.
> 
> If b.com is sending cookies that are security sensitive it can mark them as HttpOnly, and they won't be available from JavaScript.
> If the cookie is meant to be read, but only from trusted scripts, then it's probably better to tune allowedOrigins.
> 
> The relaxed settings proved to be less confusing for people (that in general are not aware of CORS, even after many years), while security aware people have the mean to strengthen the configuration.
> 
> If we strengthen the default CORS configuration to allow nothing, forcing people to manually configure what they want, we are going to break lots of apps.
> 
> I'm inclined to leave things as is.
> 
> Another solution could be to deprecate CrossOriginFilter, and make it extend a new class CORSFilter which has all settings strict (no domain, no methods, no credentials, etc.). 
> 
> However, the chances that this deprecation gets noticed are only true for people using CrossOriginFilter in Jetty embedded; people that just declares it in web.xml won't be typically aware of the deprecation warning.
> 
> Assigning to Greg for review.

On 2015-03-25 16:41:32 -0400, Simon Oberhammer wrote:

> I understand your reasoning for keeping things working out of the box, and i wouldn't want to change that.
> 
> My surprise was that allowedOrigins=* together with credentials flag true work. And that is only because Jetty always returns the literal request Origin (and never "*").
> 
> CORS wouldn't allow those two defaults but jetty weakens the constraint and that felt dangerous to me. Of course, as you explained, httponly cookie would also help in this situation.
> 
> I don't use any complex Origin matchers and can't say how much sense it would make to have a special case and respond with "*" (and not the request origin) if "*" is the value of allowedOrigins.
> 
> This would be a breaking change but users will quickly find google help "star origin not working with credentials".

On 2015-03-25 19:40:24 -0400, Greg Wilkins wrote:

> I've not got my head into this issue entirely and would need to find a few hours spare to really understand it all again.....  but I'll comment with partial understanding anyway:
> 
> The CrossOriginFilter is not installed by default, so for this to be a problem it needs to be found, installed and configured by somebody.      So I don't think this is a huge problem either way.
> 
> If we default to false, somebody can just change it to true and create the problem (if there is one).
> 
> Thus I think the solution is probably documentation rather than defaults.   The javadoc and other documentation should make it clear that there are some dangerous configurations possible and using the filter has to be done with careful consideration.
> 
> Specifically we should warn that the default is to allow all domains and that is not advised in production.   Perhaps we can do a runtime warning to that effect and if they really want all domains they have to explicitly configure that to turn off the warning???
> 
> back to you Simone....  unless Simon wants to contribute a patch for our javadoc to this effect????

On 2015-03-26 16:07:25 -0400, Simon Oberhammer wrote:

> I changed the bug title to better reflect the actual problem.
> 
> I can prepare a documentation patch. 
> 
> My original confusion stemmed from this: CORS per spec 6.1.3 does not allow the following combination of headers as a security measure:
> 
>     Access-Control-Allow-Origin: *
>     Access-Control-Allow-Credentials: true
> 
> Jetty behaves spec compliant and never never sends this combination even if allowedOrigins="*". But this seems against the spirit of the spec but I can't spell out a security problem.
> 
> 
> 6.1.3 http://www.w3.org/TR/cors/#resource-requests

**Comment by joakime** [comment]
Seems like this is "works as intended"?
