### ISSUE TITLE
Jetty ALPN Server - No Server ALPNProcessors!

### ISSUE THREAD

**Issue by pyaillet** [eclipse/jetty.project#1894]
There seems to be a problem with jetty alpn server, I can't manage to have it find a Server ALPNProcessor with jetty-alpn-server:10.0.0-SNAPSHOT

I tried to set up the bootstrap jar alpn-boot-8.1.11.v20170118.jar for my jdk1.8.0_131 which should be correct according to this: https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html#alpn-versions
In fact, it used to work with this snapshot: 20170905.073526-180

I also tried the jetty-alpn-agent with the debug option, which gives me this output:
```[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar```

But I always get the ```java.lang.IllegalStateException: No Server ALPNProcessors!``` from ```org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory``` 

Am I doing something wrong ? 
Is there another way to get the ALPNProcessors working on java8 now ?

Thank you

**Comment by gregw** [comment]
ALPN now uses the ServiceLoader to find one or more ALPNProcessors.  These are found in the new modules:
- jetty-alpn-openjdk8-client
- jetty-alpn-openjdk8-server
- jetty-alpn-java-client
- jetty-alpn-java-server
- jetty-alpn-conscrypt-client
- jetty-alpn-conscrypt-server

and you have to have the appropriate ones of those on the classpath.  If you are using our boot path ALPN implementation, then the openjdk8 modules are the ones you want.

Note that if you use conscrypt as the TLS provider (see our new conscrypt module) then you can user the conscrypt providers above with nothing on the boot path for simpler startup and much faster SSL/TLS!
https://webtide.com/conscrypting-native-ssl-for-jetty/

**Comment by pyaillet** [comment]
Got it working.

Thanks for your help

**Comment by hieplq** [comment]
i try to use jetty-alpn-conscrypt-server on Osgi environment and also got 

> Root exception:
java.lang.IllegalStateException: No Server ALPNProcessors!
	at org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.<init>(ALPNServerConnectionFactory.java:53)

it's run well with jetty 9.4.7

to update 9.4.8, i do bellow step:
1. install osgi bundle jetty-alpn-conscrypt-server
2. it dependency to package org.conscrypt so i wrap conscrypt-openjdk-uber to osgi
active both bundle, but still got error.

my environment:
1. open java 8 latest
2. equinox latest

**Comment by sbordet** [comment]
@janbartel perhaps we don't have the right OSGi metadata for consuming services with `ServiceLoader` ?

**Comment by janbartel** [comment]
Opened new issue #2015 to track report from @hieplq .
