### ISSUE TITLE
Request.getCookie() should ignore invalid cookies

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1898]
During the parsing of Cookies from the request, if an invalid cookie is encountered, it should be ignored.
As for logging it (or not), that's a separate question.

Example bad cookie: Path="/value"

This `<name>=<value>` will fail in javax.servlet.http.Cookie because "Path" is a reserved token.

**Comment by gregw** [comment]
This is already the case.  I added a test in 9.3 to verify the cookie is ignored and the exception is logged at debug level

**Comment by gregw** [comment]
It is not the case for jetty 10!
