### ISSUE TITLE
Back port java 9 support to Jetty-9.3 for quickstart

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1899]
Backport enough java9 support to jetty-9.3, so that a user with java 9 can generate quickstart configuration for deployment on java8.

**Comment by gregw** [comment]
Requires at least:
 - #1797 Multi release jar 
 - #1499 jrt:// class location
 - #1213 ASM6

**Comment by gregw** [comment]
@janbartel can you do #1213 thanks

**Comment by janbartel** [comment]
@gregw  #1213  is done.

I've just noticed another problem: the  ServiceLoader mechanism that we use to find ServletContainerInitializers would discover any java9 SCIs even though we don't want them if targetting java8. I'll work on a fix.

**Comment by janbartel** [comment]
For those interested in this issue, I posted the following on the core-libs-dev mailing list for jdk9:

> 
> http://openjdk.java.net/jeps/238 says:
> 
> "JAR metadata, such as that found in the MANIFEST.MF file and the
> META-INF/services directory, need not be versioned."
> 
> Does the language "need not" actually mean "is not", or is the intention to
> leave the door open to versioning of META-INF/services?
> 
> If it is possible to version services, is there any requirement that the
> annotations on a service must be the same for all versions of that service
> in a multi-release jar?
> 
> The motivation for the question is a scenario where we need to support
> build and pre-deployment discovery of services on a different version of
> the jvm (ie 9) to deployment/runtime (ie 8).  During discovery we examine
> services returned from the ServiceLoader for particular annotations, such
> as the @HandlesTypes annotation from the servlet spec.  If services can be
> versioned, and annotations may be different between versions, we would need
> some support from the jvm to be able to ensure we examine the correct
> version for the target runtime jvm version.
