### ISSUE TITLE
Update cdi module to version 2

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1900]
The current jetty cdi module uses weld 2.4.3, which targets version 1 of the cdi api.

We should create another module which targets  version 2 of the cdi api.

**Comment by janbartel** [comment]
The current cdi module is an experimental integration of jetty and weld, with jetty code performing the integration and putting weld on the container classpath.

For the update to cdi 2, we will let weld do the integration, and also let users put weld inside their webapps, at that seems to be the most common use case. 

NB that the weld integration is still fragile as it references internal jetty classes that are subject to change, and also require relaxation of classloading restrictions to allow those classes to be used. What would be ideal is a generic cdi api based configuration mechanism.

**Comment by janbartel** [comment]
Added cdi2.mod to jetty-9.4.x and also to jetty-10, and also in jetty-10 the cdi.mod is effectively aliased to cdi2.mod

**Comment by joakime** [comment]
@janbartel  Could this update have caused the issues reported in #1940 ?

**Comment by janbartel** [comment]
@joakime  I don't see how it could be involved: I added another jetty module for cdi 2.0 and just added the Deprecated annotation to existing jetty/cdi integration classes.
