### ISSUE TITLE
Conflict between server defaults for server and system classes and webapp defaults

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1902]
WebAppContext has __dftServerClasses and __dftSystemClasses. We also allow defaults for a Server to be set via the SERVER_SYS_CLASSES and SERVER_SRV_CLASSES attributes. We also want a user to be able to explicitly set the desired system and server classes for any given context. We need to resolve these 3 modes of setting the classpath conditioning.

**Comment by gregw** [comment]
@janbartel is this not now handled by the `Configuration` and `ClassMatcher` mechanisms in 10?  I'm closing for now, please re-open if you think more is needed.
