### ISSUE TITLE
Thread race condition in Jetty 9.4.3.v20170317

### ISSUE THREAD

**Issue by vikram1234** [eclipse/jetty.project#1903]
Jetty Team,

We had been using jetty version 7.6.10 and it was working fine.

Since we upgraded to Jetty 9.4.3 we have been seeing some strange behavior in our application. 
When thread counts grows or http sessions, our other application threads stops working, only http request thread keep working, all of our other threads stops working and this issue comes once in two
 weeks.  

We reverted back the Jetty version and it works fine, issue is only when we upgraded to new Jetty and stops other threads at some point (or long delays in threads).

Could you please check if something is wrong with Jetty or IO, or any pointer that might help us?

We also tried to upgrade to latest after 9.4.3 and its became more worse. 

Regards,
ATT Team

**Comment by jmcc0nn3ll** [comment]
9.3.4 is old, from v20151007

If you are having an issue try updating to at least the latest version in
that line which is 9.3.21.v20170918

cheers,
Jesse

--
jesse mcconnell
jesse.mcconnell@gmail.com

**Comment by vikram1234** [comment]
@jmcc0nn3ll thanks for quickly reply, my apology, i have updated the description, its "9.4.3" and we have also we have tried with 9.4.7 which is latest i hope.

**Comment by jmcc0nn3ll** [comment]
Not a lot to go on here, can you describe a bit more what you are doing when you say:

> When thread counts grows or http sessions, our other application threads stops working, only http request thread keep working, all of our other threads stops working

and

> stops other threads at some point (or long delays in threads)

Those sound like interesting details and that http threads continue working makes it sound like Jetty is still handling requests.  Are you trying to forcefully kill active processing threads or something instead of configuring timeouts?

**Comment by joakime** [comment]
@vikram1234 can you detail the race condition you are seeing.  There's not enough information to work with in your original description.

If you are coming from Jetty 7, that means Servlet 2.5, which had no support for application threads using the HttpServletRequest or HttpServletResponse (or anything those 2 provided, such as the request streams or response streams).

Servlet 3.0 added the ability to use HttpServletRequest and HttpServletResponse from application threads. (better if you used the new servlet AsyncContext to access them)

Servlet 3.1 added the ability to use the request streams and response streams from application threads. (better if you used the new servlet Async I/O features)

**Comment by joakime** [comment]
@vikram1234 we also require knowledge of your server setup. 

Standalone (jetty-home or jetty-distribution), using jetty-base properly?
Using Embedded-jetty instead?
Connector setup (http/1.0, http/1.1, http/2)?
ThreadPool settings (implementation / configuration)?

**Comment by vikram1234** [comment]
@joakime thanks for reply - following are more details if can help. 

Embedded Jetty 
HTTP Version - HTTP_1_1
Threadpool - default (we have not configured anything)
Servlet version - servlet-api-3.1

We do not have issue with Jetty to receiving HTTP Requests from clients, issues is Jetty is locking our other application threads. 

The other application threads are put in background and never being executed for hours because of load on server, but if we revert back to old version we do not see this issue.

**Comment by joakime** [comment]
Still not enough information.
That description puts the fault in the JVM, not Jetty.

Perhaps some threaddumps will help.
Can you show a normal operational thread, and a few different "never being executed" threads?

**Comment by vikram1234** [comment]
Yes i can get you that information, there were threads which were not executed till 20 hours which are not Jetty threads though, our application threads. Some kind of locking which never allows other threads to get executed. The threads are blocked for hours... Only Jetty (HTTP Threads) are running continuously, its obviously while on high load. There are 200-500 live threads (we do send files with http put)

**Comment by vikram1234** [comment]
[threads.txt](https://github.com/eclipse/jetty.project/files/1392188/threads.txt)

Thread are attached, does threadpool of Jetty controls JVM threads?

**Comment by vikram1234** [comment]
@joakime @jmcc0nn3ll  This defect is so server for us if you could help us or we should revert back our deployment, it has impacted around instances out of 60 and we have no choice then revert that back. 

Could you please suggest if you see anything in this dump? 

The delivery threads are RUNABLE but not able to get pointer to run. " 
"Delivery Thread" prio=5 tid=25 RUNNABLE
"

**Comment by sbordet** [comment]
The thread dump you attached shows that Jetty is basically idle, and you have 40 threads ("Delivery Threads") started by your application and not related to Jetty that are stuck in a socket write.

I think this issue has nothing to do with Jetty and the fact that if you use Jetty 7 everything works is just pure luck, or otherwise related to something else in your environment (e.g. JDK version, etc.).

**Comment by vikram1234** [comment]
thanks @jmcc0nn3ll @joakime @sbordet  .. looks like we are able to find the pool issue.

**Comment by jmcc0nn3ll** [comment]
good deal!  since you mentioned production deadlines and the like feel free to drop us a line at webtide.com if need be

**Comment by vikram1234** [comment]
@jmcc0nn3ll @joakime @sbordet We are seeing this issue back again, could you reopen the issue. 

Here is thread dump if that helps, the Jetty threads are running but blocked app. 

[Thread1.txt](https://github.com/eclipse/jetty.project/files/1394792/Thread1.txt)

![locked](https://user-images.githubusercontent.com/11531441/31722022-eeeb1ef4-b3e8-11e7-960c-65d760e14716.png)

**Comment by sbordet** [comment]
What exact Jetty version ?
For some Jetty versions this is completely normal, as those Jetty versions had 2 threads producing from the selector, which is what the screenshot above shows.

**Comment by vikram1234** [comment]
@sbordet its - 9.4.3.v20170317

**Comment by sbordet** [comment]
It's normal then. We have removed those 2 producer threads in 9.4.7.

**Comment by vikram1234** [comment]
@sbordet So should we upgrade or are fine with this Jetty version? "9.4.3.v20170317"

**Comment by sbordet** [comment]
You're good either way, but we always recommend to upgrade to latest releases. Ideally you should always be on the last release.
