### ISSUE TITLE
Eclipse consumes 100% CPU on Jetty 9.2.9 idle loop

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#191]
migrated from Bugzilla [#463244](https://bugs.eclipse.org/bugs/show_bug.cgi?id=463244)
status ASSIGNED severity *normal* in component *server* for *9.2.x*
Reported in version *9.2.9* on platform *PC*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[jetty_using_2_full_processors.png](https://bugs.eclipse.org/bugs//attachment.cgi?id=251941)_ (ID 251941)
- _[jetty_high_cpu.png](https://bugs.eclipse.org/bugs//attachment.cgi?id=253470)_ (ID 253470)

On 2015-03-26 20:17:20 -0400, Fabio Zadrozny wrote:

> Created attachment 251941
> Jetty 9.2.9.v20150224 using lots of CPU (windows 8.1 / Java jre1.8.0_25)
> 
> Note that there was a previous "closed invalid" report (https://bugs.eclipse.org/bugs/show_bug.cgi?id=460242) which seems to be the same thing, yet, I can still reproduce this on 9.2.9 when running on Eclipse.
> 
> The information I have is the following:
> 
> JDT starts Jetty to show somethings using the Eclipse help infrastructure which in turn starts Jetty.
> 
> Jetty then does nothing for quite a while behaving well (on Windows 8.1 / Java 1.8.25).
> 
> Then, after being in idle mode for some time (i.e.: I just leave Eclipse open in the computer for say 1 hour) it suddenly decides to use a lot of CPU, so, when I come back it's using 50% of the computer power in the Jetty idle loop (in my case that's 2 full CPUs) -- as the profile measurement shows -- at that point, no matter what I do it doesn't come back to normal (restarting Eclipse is the only solution).
> 
> It's as if Java is suddenly optimizing something in the Jetty idle loop which makes it run too fast... I'm having this issue since Jetty 8.x, so, I'm inclined to think that the problem is the approach being used on Jetty on a Java 8 jre (polling can definitely lead to a high cpu usage and the profiler clearly shows this is happening in its idle loop).
> 
> Ideas? Anything else I can add to this to help to have this fixed?

On 2015-03-26 21:16:52 -0400, David Williams wrote:

> (In reply to Fabio Zadrozny from comment # 0)
> 
> > Ideas? Anything else I can add to this to help to have this fixed?
> 
> I suggest you try with "JIT turned off" ... as you said, "It's as if Java is suddenly optimizing something  ..." and JIT is a common example of that. (VMs often do not "JIT a method" until it's been called, like 40,000 times, or similar). 
> 
> And ... you're using the Oracle VM? If so, their "JIT option specs for WIndows Java 8' is here: 
> 
> http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html#BABDDFII
> 
> and there it says to run in "interpreted mode only" (i.e. no JIT) is to use this option on command line. 
> 
> -Xint
> 
> If JIT is suspected, as I've debugged in the past, it's convenient to first demonstrate "no problem" by first demonstrating there is no problem with "no JIT at all" ... but, that changes so much, it is not very definitive. So subsequent steps would be to exclude, ideally, just exactly one method from "being JITed" and then that's pretty narrow. There's other things you can play with, such as have that method JITed aggressively, etc., so you don't have to wait an hour :) [But, again, there's no guarantee, having it JITed aggressively might change the way something else is JITed, and then maybe the bug would no longer occur, and on and on ...]
> 
> Good luck, JIT problems are notoriously hard to debug.

On 2015-03-27 12:29:53 -0400, David Williams wrote:

> 
> For the record, I did try to reproduce using Eclipse SDK, and could not. I used milestone 6 "plain" SDK, with fresh workspace, and just one Java class ... enough to bring up a "tool tip" on the Java. Have let it idle, after that, with no change in "CPU consumption" (according to Windows "resource manager"). 
> 
> I am running it on Windows 7 (there's one difference). And, using Oracle's JDK 1.8 _31 (another small difference?) The -version says HotSpot is running in "mixed mode" (not exactly sure what that means ... but, just providing to compare notes) and says "hot spot" is "64-Bit Server VM (build 25.31-b07). 
> 
> I also used no other "vm args" other than defaults. 
> 
> Fabio, do you use any other VM arguments? Aggressive GC or anything specified?

On 2015-03-27 13:23:32 -0400, Fabio Zadrozny wrote:

> I have no custom vmargs (Eclipse just passes some -Xms/-Xmx to raise the memory, but that's all).
> 
> I'll try upgrading to 1.8.0_31 to see if that makes a difference here...

On 2015-05-13 19:08:49 -0400, Fabio Zadrozny wrote:

> Created attachment 253470
> Jetty still using lots of CPU on Java 7
> 
> As a note, I still have the same issue, even going to other java versions (I just went back to Java 7 -- 1.7.0_55 -- and still got the high cpu usage issue -- in Windows 8.1).
> 
> -- as a second note, all the java versions I'm using were x64 versions (i.e.: Java HotSpot(TM) 64-Bit Server VM).
> 
> Adding a new sampling snapshot (which shows all the time on the jetty SelectorManager)... 
> 
> As a note, I'm currently having to restart Eclipse at least 2-3 times a day because of this issue. Do you think there's something which could be customized to give some hint to jetty to be less performant? (I don't really need much speed on Jetty when using it inside Eclipse).

**Comment by joakime** [comment]
Cannot replicate. closing.

Feel free to reopen if you have a reproducible test case.
