### ISSUE TITLE
jetty client fails to parse response with RFC2045 conformant Content-Type: charset="utf-8"

### ISSUE THREAD

**Issue by fdummert** [eclipse/jetty.project#1914]
Hi together,

jetty-client fails to parse a response with following header:

`Content-Type: application/soap+xml; charset="utf-8"`

According to [RFC2045](https://www.ietf.org/rfc/rfc2045.txt), section 5.1, using quotes for the charset is explicitly allowed, but in following [lines](https://github.com/eclipse/jetty.project/blob/be04d47a9d6ba14d4f91983b249cad7d446e4371/jetty-client/src/main/java/org/eclipse/jetty/client/util/BufferingResponseListener.java#L90-L96), the String `"utf-8"`, including double quotes, is finally being passed to 
`new String(getContent(), encoding)` 
(see [this line in HttpContentResponse](https://github.com/eclipse/jetty.project/blob/be04d47a9d6ba14d4f91983b249cad7d446e4371/jetty-client/src/main/java/org/eclipse/jetty/client/HttpContentResponse.java#L119)), resulting in a UnsupportedCharsetException.

Greg has fixed this 15 years ago for the server side (see https://developer.jboss.org/thread/36081), somehow jetty-client has been forgotten. Funny that nobody came across it since then :-)

Best Regards,
Florian

**Comment by sbordet** [comment]
What Jetty version ?

**Comment by sbordet** [comment]
So it's been fixed in 9.2.x onwards, but unlikely we will be making other 9.2.x releases.
If you need it for CometD, be aware that CometD can be built against Jetty 9.4.x.
