### ISSUE TITLE
Misspelling (typo) on the Jetty Website

### ISSUE THREAD

**Issue by jtermine** [eclipse/jetty.project#1917]
The first sentence of the Jetty website (https://www.eclipse.org/jetty/) reads — 

“Elcipse Jetty provides a Web server and javax.servlet container, plus support for HTTP/2, WebSocket, OSGi, JMX, JNDI, JAAS and many other integrations...”

“Elcipse” needs to be “Eclipse.”  Google indexes that line and show it in the search result when one hunts for the Jetty web server.

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch *cough* you got it one!

**Comment by WalkerWatch** [comment]
Fixed in: https://github.com/eclipse/jetty.website/commit/6eb82c238ffa7ec5c2105ba09c570cdc5aba32a8

Website building now.
