### ISSUE TITLE
GCThreadLeakPreventer won't work with Java 9

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse/jetty.project#1923]
In Java 9 the class `sun.misc.GC` has been moved to `sun.rmi.transport.GC` making `GCThreadLeakPreventer` non functional. 

https://bugs.openjdk.java.net/browse/JDK-8153286

**Comment by sbordet** [comment]
Thanks ! Care to submit a patch that works with JDK 9 ? See http://www.eclipse.org/jetty/documentation/9.4.x/contributing-patches.html.

**Comment by tbroyer** [comment]
Not sure there's anything to do here: https://bugs.openjdk.java.net/browse/JDK-8157570

**Comment by sbordet** [comment]
We need to review those preventers and possibly put them in a different Jetty 10 module so that we can have a specific `module-info.java` without polluting the `jetty-util` one.
