### ISSUE TITLE
API changes report for Jetty Utilities

### ISSUE THREAD

**Issue by lvc** [eclipse/jetty.project#1926]
Hi,

I'd like to share report on API changes and backward compatibility for the Jetty Utilities library: https://abi-laboratory.pro/java/tracker/timeline/jetty-util/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools for jars found at http://central.maven.org/maven2/org/eclipse/jetty/jetty-util/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

The snapshot version (9.4.x-SNAPSHOT) is taken from https://oss.sonatype.org/content/repositories/jetty-with-staging/org/eclipse/jetty/jetty-util/.

Hope the report will be helpful for users and maintainers of the library.

Please let me know if you'd like to see reports for other Jetty modules in the tracker.

Thank you.

![jetty-util-2](https://user-images.githubusercontent.com/1517837/32141208-3aac65a0-bc8b-11e7-8902-11f0d9d9bd38.png)

![jetty-util-1](https://user-images.githubusercontent.com/1517837/32141209-3af0a6e8-bc8b-11e7-8341-a6ec6fc67da9.png)

**Comment by janbartel** [comment]
@lvc thanks for the info, we'll take a look.
