### ISSUE TITLE
Idle sessions created by startAsync are not scavenged.

### ISSUE THREAD

**Issue by akhanzode** [eclipse/jetty.project#1930]
- Start a Async handling in doGet()
- Do ctx.complete() to make sure we did everything
- Looks like session.complete is not called which results in session hanging with _requests == 1

Is this a known issue? I use a simple servlet use curl to hit the servlet. I am using embedded jetty.
I am using 9.4.x branch.

**Comment by janbartel** [comment]
@akhanzode do you have a reproduction test case? I haven't been able to reproduce this using the jetty async-rest example.

**Comment by janbartel** [comment]
@akhanzode I also suggest you enable DEBUG for:

org.eclipse.jetty.server.HttpChannelState and org.eclipse.jetty.server.session

**Comment by janbartel** [comment]
@akhanzode  do you have the reproduction test case? I can't make any progress on this because I can't reproduce it without your help.

**Comment by janbartel** [comment]
@akhanzode  any progress?

**Comment by janbartel** [comment]
No info supplied, so I'm going to close this issue for now. If you can provide a repro test case, please reopen.
