### ISSUE TITLE
Fair distribution of connection over selectors

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1936]
There is some evidence that the non-atomic ++ used by the SelectorManager to pick a SelectorManager may not be resulting is an event distribution of load over selectors.   An atomic int would cost little more and would keep the distribution fairer (at least excluding closed connections).

**Comment by sbordet** [comment]
Implemented in 6fb7c9ec2e899cc4d1329d43e2dd61726f765802.
