### ISSUE TITLE
RequestLogHandler does not log query parameters for async requests

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#194]
migrated from Bugzilla [#463506](https://bugs.eclipse.org/bugs/show_bug.cgi?id=463506)
status ASSIGNED severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.2.5_ on platform _All_
Assigned to: Greg Wilkins

On 2015-03-30 13:34:31 -0400, Nicolas Bielza wrote:

> In the access logs, asynchronous requests are stripped off their parameters.
> 
> I tracked this to org.eclipse.jetty.server.Server.handleAsync(HttpChannel<?> connection) where the uri for the base request is replaced by the truncated version (at line 535).

**Comment by gregw** [comment]
fixed long ago
