### ISSUE TITLE
Integrate CDI

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#195]
migrated from Bugzilla [#463731](https://bugs.eclipse.org/bugs/show_bug.cgi?id=463731)
status ASSIGNED severity *enhancement* in component *cdi* for *9.3.x*
Reported in version *9.3.0* on platform *All*
Assigned to: Joakim Erdfelt

On 2015-04-01 18:04:27 -0400, Jan Bartel wrote:

> TODOs for the Weld/CDI integration with jetty:
> 
> 1. Ensure that webapps can opt in or out of weld/cdi startup
> 2. Fully initialize weld/cdi without requiring jetty-specific code in the weld project

**Comment by joakime** [comment]
Considering this first pass as completion of this issue.
