### ISSUE TITLE
PrintWriter obtained via ServletResponse.getWriter should use same logic as ServletOutputStream for line separator

### ISSUE THREAD

**Issue by DietmarHechensteiner** [eclipse/jetty.project#1950]
The method `Response.getWriter` returns an object of type `ResponseWriter` which extends `PrintWriter`. In the class `ResponseWriter`, a `static final field __lineSeparator` is initialized with the method `System.getProperty("line.separator")`.
This value determines the output of the various `println` Methods. Thus, the output is server platform dependent, so a server application using Jetty running on a Windows system behaves differently than the same application running on a Linux or Mac OSX system, or on an old Mac system. In my opinion, if anything, the server should rather consider the client platform and possibly the MimeType. Therefore, the `__lineSeparator` field should be initialized with the constant `"\n"`, but there are probably doubts about backward compatibility. In any case, it should be possible to programmatically specify `"\r\n"`, `"\n"`, or `"\r"` as the newline value for `ResponseWriter`.

**Comment by joakime** [comment]
The `PrintWriter` contract specifies that it implements all of the `print` methods from `PrintStream`.

See: https://docs.oracle.com/javase/8/docs/api/java/io/PrintWriter.html

`PrintStream` behavior for newline is dependent on the System Property `line.separator`

See: https://docs.oracle.com/javase/8/docs/api/java/io/PrintStream.html#println--

Thus our implementation of `PrintWriter` (called `ResponseWriter` internally) and its new line separator logic is consistent with the contracts of the API `javax.servlet.ServletResponse.getWriter()`

See: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html#getWriter--

It would be a violation of API contract to make it behave any differently.

**Comment by DietmarHechensteiner** [comment]
The Problem is that the `PrintWriter` was designed with only one platform in mind. But on a web server,
you have to deal with 2 platforms: the server platform and the client platform.
Since the output is targeted to the client platform, you should consider the 
rules of the client platform.

Because of this special situation, already more of the standard `PrintWriter` 
API contracts are violated, and these violations are documented in the head of the
`ResponseWriter` class.
For example, the method `format(String format, Object... args)` violates the contract because
it does not use the default locale of the server platform, but uses the locale
supplied by the `ServletResponse#getLocale()` instead.

Without the ability to control the newline behavior, none of the `println` methods
can be used, and you have to use a combination of `print` and `write("\n")` instead.

**Comment by joakime** [comment]
@gregw, we can use a servlet spec review here. 
The servlet spec seems to have no language about honoring or using the JVM `line.separator` for the `PrintWriter` returned from `ServletResponse.getWriter()` call.

However, curiously, the `javax.servlet.ServletOutputStream` (from `ServletResponse.getOutputStream()`) does indicate a preference to use (CRLF) only.

See javadoc for the various `print` methods: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletOutputStream.html

**Comment by janbartel** [comment]
The javax.servlet.jsp.JspWriter class, which uses the response's PrintWriter, says explicitly that the methods JspWriter.newline() and JspWriter.println() will output a new line that is dependent on the system property line.separator. That is also in keeping with the contract of PrintWriter. 

See https://docs.oracle.com/javaee/1.4/api/javax/servlet/jsp/JspWriter.htm

I also note that other servlet containers, such as Tomcat for example, also implement the same PrintWriter behaviour of using the system line.separator.

Thus, I would suggest that the OP raise this issue with the servlet expert group to obtain a change in the currently specified behaviour.

**Comment by joakime** [comment]
@gregw do you know what the Servlet EG says about this?

**Comment by gregw** [comment]
I agree with the OP that the client environment should have been taken into account when determining line termination.   However, I think that horse has bolted long ago and it is not something that we can fix unilaterally.  Perhaps a programmatic API would be best or at least some configuration. But that would have to go via the servlet EG/spec process.

So I'm closing this as it is not a jetty issue.

**Comment by joakime** [comment]
Linking to new servlet spec issue about this eclipse-ee4j/servlet-api#228
