### ISSUE TITLE
Not generating any bean definitions from org.eclipse.jetty.cdi.core.*

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#196]
migrated from Bugzilla [#464215](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464215)
status ASSIGNED severity *enhancement* in component *cdi* for *9.3.x*
Reported in version *9.3.0* on platform *PC*
Assigned to: Joakim Erdfelt

On 2015-04-08 20:24:07 -0400, Jan Bartel wrote:

> Following log lines are generated when cdi module is enabled:
> 
> INFO: WELD-000119: Not generating any bean definitions from org.eclipse.jetty.cdi.core.AnyLiteral because of underlying class loading error: Type org.eclipse.jetty.cdi.core.AnyLiteral not found.  If this is unexpected, enable DEBUG logging to see the full error.
> Apr 09, 2015 10:21:13 AM org.jboss.weld.bootstrap.MissingDependenciesRegistry handleResourceLoadingException
> INFO: WELD-000119: Not generating any bean definitions from org.eclipse.jetty.cdi.core.JettyLogFactory because of underlying class loading error: Type org.eclipse.jetty.cdi.core.JettyLogFactory not found.  If this is unexpected, enable DEBUG logging to see the full error.
> Apr 09, 2015 10:21:13 AM org.jboss.weld.bootstrap.MissingDependenciesRegistry handleResourceLoadingException
> INFO: WELD-000119: Not generating any bean definitions from org.eclipse.jetty.cdi.core.ScopedInstance because of underlying class loading error: Type org.eclipse.jetty.cdi.core.ScopedInstance not found.  If this is unexpected, enable DEBUG logging to see the full error.
> Apr 09, 2015 10:21:13 AM org.jboss.weld.bootstrap.MissingDependenciesRegistry handleResourceLoadingException
> INFO: WELD-000119: Not generating any bean definitions from org.eclipse.jetty.cdi.core.SimpleBeanStore because of underlying class loading error: Type org.eclipse.jetty.cdi.core.SimpleBeanStore not found.  If this is unexpected, enable DEBUG logging to see the full error.
> Apr 09, 2015 10:21:13 AM org.jboss.weld.bootstrap.MissingDependenciesRegistry handleResourceLoadingException
> INFO: WELD-000119: Not generating any bean definitions from org.eclipse.jetty.cdi.core.NamedLiteral because of underlying class loading error: Type org.eclipse.jetty.cdi.core.NamedLiteral not found.  If this is unexpected, enable DEBUG logging to see the full error.

**Comment by pbougrier** [comment]
Same issue on 9.3.9.v20160517.
`WebAppContext.getServerClasses()` forbids Weld to load jetty classes.
Workaround:
```java
WebAppContext web = new WebAppContext();
//...
List<String> blackList = new ArrayList<>(Arrays.asList(webapp.getServerClasses()));
blackList.add(0, "-org.eclipse.jetty.cdi.core."); // note the minus sign, and the insertion point
web.setServerClasses(blackList.toArray(new String[blackList.size()]));
```

**Comment by gregw** [comment]
@pbougrier you can just do
```java
web.prependServerClass("-org.eclipse.jetty.cdi.core.");
```
Which technically excludes the org.eclipse.jetty.cdi.core package from the server classes, which are the ones on the system classpath that are hidden from the webapplication.

**Comment by pbougrier** [comment]
Nice.
thanks !

**Comment by joakime** [comment]
> Note: the `jetty-cdi` effort is not well tested (and likely out of date already)

While there was some effort to make `jetty-cdi` work in `embedded-jetty`, it required alot of setup.

See https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-cdi/cdi-servlet/src/main/java/org/eclipse/jetty/cdi/servlet/EmbeddedCdiHandler.java

Which is what's required if you are using a `ServletContextHandler`.

There is also a convenience static method you can use for manipulating the `WebAppClassloader`.

See `org.eclipse.jetty.cdi.servlet,JettyWeldInitializer.initWebApp(WebAppContext)`

Since you are using a `WebAppContext` you'll have better luck using the official weld-cdi jars within your WebApp/WAR instead.
