### ISSUE TITLE
HttpMethod case sensitive

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1966]
The HttpMethod is currently matched case insensitively in the HttpParser

**Comment by gregw** [comment]
If a lower case method (eg "get") is received,  currently the HttpParser acts as follows:
 - in `LEGACY` mode the case of the method is retained and a compliance violation is issued.
 - in other compliance modes, the method is converted to 'GET'.

This is actually an inversion of what should happen as the RFCs indicate that method should be case sensitive.    However, care needs to be taken to avoid breaking existing users.

With PR #1967 I have inverted only the compliance warning and not the behaviour:
 - in `LEGACY` mode the case of the method is retained
 - in other compliance modes, the method is converted to 'GET' and a compliance violation is issued.

We then need to consider what is the correct fix mid term.  One possibility is simply:
 - in all mode the case of the method is retained

However a more thorough and flexible solution might be necessary to fully support backwards compatibility and fine grained compliance switching.    In jetty-10, the compliance mode could be replaced by a EnumSet over `LEGACY`,`RFC2616`,`RFC7230`,`ISSUE1966` and the behaviour changed to:
 - if 'ISSUE1966' compliance flag is set, convert method to 'GET' and a compliance violation is issued.
 - otherwise the case of the method is retained

**Comment by sbordet** [comment]
@gregw is this issue fixed ?
