### ISSUE TITLE
Per context feature enable/disable

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#197]
migrated from Bugzilla [#464216](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464216)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[464216.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=252363)_ (ID 252363)

On 2015-04-08 20:24:18 -0400, Greg Wilkins wrote:

> Jetty has several optional features that can be apply to a context by the container:  annotations, websockets, CDI, JMX
> 
> Currently these can be turned on/off simply by including them in the container classpath or not.
> 
> However, if they are included in the container classpath, then each of these features has varying degree of support for selective application to individual contexts.  Some will always be applied, others need to detect attributes of the application, yet others have explicit enable/disable semantics.
> 
> It would be desirable to have a common mechanism 9or at least pattern) to allow configuration and enquiry of which features are applied to individual contexts.

On 2015-04-08 20:25:33 -0400, Greg Wilkins wrote:

> probably add jndi to that list

On 2015-04-08 21:24:25 -0400, Greg Wilkins wrote:

> Current per context enabling mechanisms are as follows:
> 
> JNDI:
> The PlusConfiguration is added to the ConfigurationClassList of the serverDefaults.   Thus if jetty-plus.xml is deployed, plus is enabled for all contexts unless they explicity remove their configuration.
> 
> There is a "-org.eclipse.jetty.jndi." added to the context server classes by default.
> There is a "org.eclipse.jetty.jndi." added to the context system classes by default.
> 
> JAAS:
> java.security.auth.login.config system property is set with login.conf location. Each context requires a JAASLoginService to be configured in a context.xml
> There is a "-org.eclipse.jetty.jaas." added to the context server classes by default.
> There is a "org.eclipse.jetty.jaas." added to the context system classes by default.
> 
> Annotations: 
> The AnnotationConfiguration is added to the ConfigurationClassList of the serverDefaults.
> 
> There is a "-org.eclipse.jetty.util.annotation." added to the context server classes by default.
> There is a "org.eclipse.jetty.util.annotation." added to the context system classes by default.
> 
> JMX:
> Context init param "org.eclipse.jetty.server.context.ManagedAttributes" is inspected for a list of attribute names.  If any context attributes are set with a matching name, the are added to the ContextHandler as managed beans.
> 
> There is a "-org.eclipse.jetty.jmx." added to the context server classes by default.
> There is a "org.eclipse.jetty.jmx." added to the context system classes by default.
> 
> JSP:
> There is a JettyJasper ServletContextInitializer, which if present on the container classpath will always run.  This extends the tomcat initializer and implements the newTldScanner method that checks the context init parameter "org.eclipse.jetty.jsp.precompiled", which if true causes a Null scanner to be returned.   If not set or false, then context attribute "org.eclipse.jetty.tlds" is checked for prescanned (quickstart) TLDs otherwise normal startup.
> 
> There is a "-org.eclipse.jetty.jsp." added to the context server classes by default.
> There is a "org.eclipse.jetty.jsp.JettyJspServlet." added to the context system classes by default.
> 
> WebSocket.jsr356:
> There is a WebSocketServerContainerInitializer that calls an isEnabled method. This check for "org.eclipse.jetty.websocket.jsr356" first as an init parameter, then as a context attribute.  If set it is respected.   If not set then the presence of scanned classes is used to determine if it should be on or off.
> 
> There is a "-org.eclipse.jetty.websocket." added to the context server classes by default.
> There is a "org.eclipse.jetty.websocket." added to the context system classes by default.
> 
> WebSocket.CDI
> There is a WebSocketCdiInitializer.  It only checks that the context is a jetty context and then proceeds to add a WebSocketCdiListener Container.InheritedListener to the context to control the wsScope lifecycle

On 2015-04-08 21:28:49 -0400, Greg Wilkins wrote:

> A generic context enable/disable mechanism will need to support:
> - enabling/disabling ServletContextInitializers in the style of WebSockets
> - adding servlet and system classes to the context classloader
> - adding Configurations with ordering constraints
> - explicit enable/disable by init-param or context attribute
> - computed default enable/disable using presence of annotations etc.
> - server wide default enable/disable

On 2015-04-08 21:29:49 -0400, Greg Wilkins wrote:

> annotations enabling has an extra degree of difficulty.      We may need to enable the servlet annotations, but disable the annotations that clash with CDI!

On 2015-04-08 22:05:02 -0400, Jan Bartel wrote:

> Don't forget we already have 2 mechanisms to control the ServletContainerInitializers: http://www.eclipse.org/jetty/documentation/current/using-annotations.html#servlet-container-initializers
> 1. is a context attribute that defines a regex of SCI classnames to exclude
> 2. is a context attribute that defines the ordering of invocation of allowed SCIs
> 
> Jan

On 2015-04-08 22:09:36 -0400, Greg Wilkins wrote:

> Further complication of a generic mechanism is when to run it.
> If it is going to be able to add Configurations, then it needs to run before any Configurations are executed, in which case it means that init parameters cannot be checked!
> 
> Similar problem with enabling on the basis of discovered annotations and classes, as that scanning is also done as part of a Configuration

On 2015-04-10 23:47:45 -0400, Joakim Erdfelt wrote:

> For CDI, there's 2 levels of Feature.
> 
> CDI basics for servlet, and CDI features for websocket.
> 
> The question on if it should be enabled at all is best done by looking for META-INF/beans.xml in the webapp (and all of its WEB-INF/lib/*.jar files).
> 
> Opened as bug # 464337
> 
> This is slightly different approach than the property/attribute based enable keys.
> 
> Maybe a more comprehensive set of activation rules for a Feature makes sense.
> 
> Some thoughts on typical activation techniques found in other products.
> - property based allow-all/deny-individual
> - property based deny-all/allow-individual
> - system property equals (aka "os.name" == "Windows")
> - java version (aka "1.7+" or "1.8+")
> - file / resource exists
> - file / resource missing

On 2015-04-10 23:49:03 -0400, Joakim Erdfelt wrote:

> To continue, the activation of the CDI+WebSocket Feature would then be an activation equivalent of "Feature CDI enabled" and "Feature WebSocket.jsr enabled"

On 2015-04-13 21:52:57 -0400, Greg Wilkins wrote:

> Created attachment 252363
> partial implementation
> 
> This is the Feature implementation for JDNI, Plus, Websocket and Annotations.
> 
> currently breaking OSGi test harnesses and needs more attention to the maven plugin.
> 
> Not yet implemented JSP or CDI features.

On 2015-04-14 02:38:21 -0400, Greg Wilkins wrote:

> created branch jetty-9.3-Feature

On 2015-04-15 01:30:53 -0400, Greg Wilkins wrote:

> While the Feature changes in the branch are working, they are very invasive and it is moderately complex to deal with all the permutations of ContextHandlers ServletContextHandlers and WebAppContexts.
> 
> Thus I'm thinking that we have not yet got the right abstraction.   So I'm going to put this on hold for a little bit....   it is probably not a good feature for 9.3.0 anyway as it would break pretty much all our documentations and examples.
> 
> Perhaps this can be incorporated into a new feature in Servlet 4.0

On 2015-04-15 02:07:15 -0400, Greg Wilkins wrote:

> So I think I will note down a few of the issues that I'm having with Features as currently proposed/implemented.
> 
> The branches enabling a feature for a context involves at least 3 phases:
> 1. Firstly the modules jar file needs to be put on the system classpath and this is typically done with our module system.    Once on the classpath then ServletContainerInitialisers will be discovered but may fail to load if the contexts ClassLoader has not been conditioned.  
> 
> [ Note that in master we have added known exceptions to the WebAppContext classpath so that putting a jar on the JVMs class path is sufficient to enable a feature unless otherwise disabled.] 
> 1. We then server.addBean(new SomeFeature()).   Then for each context deployed, the features are pre-enabled, which does at least the conditioning required to prevent SCIs failing to load.  It can also do other classpath conditioning as needed.
> 2. Finally we use configuration on each context to explicitly enable/disable/auto enable the features.  This is typically setting attributes or declaring annotations etc.
> 
> This is too many steps and there is confusion between the adding of the jar to the system classpath and the adding of a feature to the server.     So perhaps we need to go for a two phase approach:
> 1. The modules jar is added to the system classpath.    The JVM ServiceLoader would then be used to discover all the features available on the classpath and would avoid the need to server.addBean(new SomeFeature()).  Down side is that if you have multiple servers they all see the same feature set, but that could be handled by allowing optional allow/deny declarations on an individual server instance if need be.
> 2. We use configuration on each context to explicitly enable/disable/auto enable the features.  Hopefully this will be a Servlet 4.0 declaration

**Comment by joakime** [comment]
This is out of date now, a new issue on the specific "Feature" (or JPMS) support in Jetty 10.x is probably a better choice.
