### ISSUE TITLE
ManagedSelector can lose selector thread under high concurrent load

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1970]
Under high concurrent load, the following has been observed in a `HttpClient` dump:
```
 |       += org.eclipse.jetty.io.ManagedSelector@2227ebf5 id=0 keys=1864 selected=23 - STARTED
 |       |   += EatWhatYouKill@6b36f90e/SelectorProducer@6644bc44/IDLE/ReservedThreadExecutor@org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager@13eb4671{s=38/40,p=0} - STARTED
 |       |       +- SelectorProducer@6644bc44
```
The `ManagedSelector` is dumped, reports 1864 keys, but none of the keys is actually printed out.

**Comment by sbordet** [comment]
Turned out that the problem was the `ConcurrentStack` data structure that suffered of the ABA problem.

**Comment by sbordet** [comment]
The issue of losing a selector thread seems still present.

**Comment by gregw** [comment]
@sbordet can we close this now?

**Comment by sbordet** [comment]
@gregw I think so, I've never seen it again.
