### ISSUE TITLE
How to merge ServletContextHandler with ContextHandler to one context ?

### ISSUE THREAD

**Issue by jiacai2050** [eclipse/jetty.project#1974]
Maybe the title isn't clear, let me tell with an example
```
ContextHandlerCollection root = new ContextHandlerCollection();
server.setHandler(root);


ServletContextHandler servletContextHandler = new ServletContextHandler(root, "/servlet", ServletContextHandler.SESSIONS);
servletContextHandler.addServlet(new ServletHolder(new HelloServlet()), "/hello");
servletContextHandler.addServlet(new ServletHolder(new HelloServlet()), "/hello2");



ContextHandler contextHandler = new ContextHandler(root, "/");
contextHandler.setHandler(new HelloWorldHandler());
```        
With code above, I have defined three paths:
- `/servlet/hello` and `/servlet/hello2`, dealt with a servlet
- `/`, dealt with a normal handler

Now, I want `/servlet/other-path` to be passed to my handler not just return a 404. 
Is this possible in Jetty? 
Thanks in advanced.

**Comment by janbartel** [comment]
You could create a Handler that is in the HandlerList before the ContextHandlerCollection. If the path is /servlet/other-path it handles the request, otherwise it lets the request flow through to the ContextHandlerCollection to be picked up by the appropriate *ContextHandler.
