### ISSUE TITLE
Allow jdk9 modules to be selected by pattern for scanning

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1978]
See also #1933 .

For jetty-10, which targets the jdk9 runtime, we need to apply some pattern matching on modules the way we currently do with jar filenames via the ContainerIncludeJarPattern.

To be considered:

- how to determine which modules from a combination of the java.module.path and the java.module.upgrade.path have actually been resolved by the jvm and should be considered for matching
- should it be a name pattern, or a list of module names to be included/excluded
- how does building a jlinked executable change the references to the module locations, and is this important.

**Comment by joakime** [comment]
Can anything from the work on #1499 be reused?

**Comment by janbartel** [comment]
Not necessarily. The work in #1499 was about the url jrt://. That url is only used for the location of resources that are part of the base modules of the jvm. For any user supplied modules, their location is a file:// url on disk. In any case, I don't think we want to base this on location, but rather the name of the module - I'm assuming that when you use the jdk.module.upgrade.path  to replace either system or user modules, that the name of the module would be the same - needs more investigation.

**Comment by joakime** [comment]
The `jrt://<module-name>` urls are just that, a module name, not a location on disk.
I don't think it's possible to reverse that `jrt://<module-name>` format to a location on disk anyway.

**Comment by janbartel** [comment]
@joakime  correct - if a module has a location of jrt:/ it does not have an accessible on-disk location.

In any case, I'm thinking of a simple list of module names to be included in the scanning. This would be similar to the ContainerIncludeJarPattern, which assumes that no container jars will be scanned, so you have to opt in.

**Comment by sbordet** [comment]
@janbartel I believe this is yet to be addressed?
