### ISSUE TITLE
PushCacheFilter does not push TLS offloaded HTTP/2 requests

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1980]
In typical HTTP/2 setups, TLS is offloaded via e.g. HAProxy and then HTTP/2 is forwarded clear-text to Jetty, perhaps via the PROXY protocol to retain the client IP and port.

For such requests, the referrer has the `https` scheme, but `HttpServletRequest.isSecure()` returns `false`.
This combination confuses the `PushCacheFilter` that thinks that the referrer is "external" and therefore won't cache resources.

**Comment by sbordet** [comment]
Note that in a HTTP/2 request the pseudo header `:scheme` is set to `https` so it should be possible for `HttpServletRequest.isSecure()` to return true.

**Comment by joakime** [comment]
I thought `HttpServletRequest.isSecure()` was set to true by the `SecureRequestCustomizer` in these scenarios.

**Comment by sbordet** [comment]
But `SecureRequestCustomizer` cannot be used in this case, as the traffic already arrives to Jetty unencrypted.

**Comment by joakime** [comment]
The `ForwardedRequestCustomizer` also sets `HttpServletRequest.isSecure()` to true.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.v20170914/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L314

It sets secure to true in various scenarios.

**Comment by sbordet** [comment]
But there is forwarding in the HTTP sense. Just decryption and opaque relaying to the backend.
