### ISSUE TITLE
Need Jetty impl of org.jboss.weld.environment.deployment.discovery.DiscoveryStrategy

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#199]
migrated from Bugzilla [#464330](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464330)
status ASSIGNED severity _normal_ in component _cdi_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Jan Bartel

On 2015-04-09 16:42:36 -0400, Joakim Erdfelt wrote:

> The weld DiscoveryStrategy is the interface that weld uses to obtain bytecode class scanning information from the classpath.
> 
> There is a default implementation found at
> org.jboss.weld.environment.deployment.discovery.ReflectionDiscoveryStrategy
> 
> which uses your standard bytecode scanning, in a similar way that Jetty does.
> 
> And there's also a Jandex specific implementation found at
> org.jboss.weld.environment.deployment.discovery.jandex.JandexDiscoveryStrategy
> 
> We should strive to create a JettyDiscoveryStrategy that utilizes the information that Jetty knows, including any information obtained from quickstart.

On 2015-04-09 16:43:14 -0400, Joakim Erdfelt wrote:

> We'll need to submit a patch to weld against
> 
> org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory
> 
> so we can pick our own implementation.

**Comment by gregw** [comment]
Integration redone in #3804
