### ISSUE TITLE
When using Server Enabled CDI, webapp included impls should not run

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#200]
migrated from Bugzilla [#464331](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464331)
status ASSIGNED severity _normal_ in component _cdi_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Greg Wilkins

On 2015-04-09 16:47:11 -0400, Joakim Erdfelt wrote:

> For a successful implementation of our Server Enabled CDI, we will need a means to disable webapp instantiated / included CDI implementations and use the one from the Server instead.
> 
> This means that the weld ServletContainerInitializer and Listeners should not execute.
> 
> See classes in weld-servlet-core.jar ...
> 
> org.jboss.weld.environment.servlet.EnhancedListener (this is the declared CDI entry point)
> 
> org.jboss.weld.environment.servlet.Listener (this is the recommended servlet listener added to the webapp's WEB-INF/web.xml)

**Comment by joakime** [comment]
This is implemented already.
