### ISSUE TITLE
Do not submit blocking tasks as managed selector actions

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2003]
`ManagedSelector` actions are intended to be tasks that must be run by the selector thread, between selections.   Currently we are submitting actions like `CreateEndPoint` that are blocking invocation, so they will be dispatched to a thread and run potentially concurrently with selections.  Such tasks can be directly executed via `SelectorManager.execute()`.

**Comment by sbordet** [comment]
Looking at this more in detail. `CreateEndPoint` and other actions also implement `Closeable` to take advantage of the logic in `EatWhatYouKill` that if a task is rejected (submission to the thread pool throws `RejectedExecutionException`), then `EatWhatYouKill` would test if the action implements `Closeable` and if so, call `close()`. This is important to avoid leaking file descriptors.

**Comment by gregw** [comment]
Fixed by #2013
