### ISSUE TITLE
Refactor Container.Listener and Container.addEventListener()

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2007]
From comment by @gregw on PR #2000 -

> While changing addEventListener, it is an opportunity to fix a problem we have with a clash/confusion with ContainerLifeCycle#addEventListener. The Container.Listener interface should extend EventListener and this method should check for instanceof and call addEventListener(Container.Listener). We also need a getter for all listeners and to include them in dump.

Unfortunately a fix is more complicated that this comment presupposes.

The difficulty is in the implementation of the new getListeners() method.  As the ContainerLifeCycle keeps its own list of Container.Listeners, and the ServletContextHandler keeps a different list of EventListeners what should be returned by a call to getListeners() on each? Moreover, HttpSession related listeners are passed to ServletContextHandler.addEventListener() but not kept in the ServletContextHandler, instead they are shipped off to the SessionHandler. Thus, should a call to getListeners() on ServletContextHandler include the session listeners or only the listeners that it keeps itself.

Resolving the above is likely to be distruptive to the jetty-9 series, so this should be done in jetty-10.

**Comment by sbordet** [comment]
@gregw can this be closed?
