### ISSUE TITLE
CDI enablement for Webapp should follow META-INF/beans.xml existence

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#201]
migrated from Bugzilla [#464337](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464337)
status ASSIGNED severity _enhancement_ in component _cdi_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Joakim Erdfelt

On 2015-04-09 17:28:30 -0400, Joakim Erdfelt wrote:

> The decision to not have CDI enabled for all webapps on a server, if only 1 needs it can be accomplished based on information present in the webapp.
> 
> If the classloader for the webapp returns a hit on 
> 
> ClassLoader.getResource("META-INF/beans.xml")
> 
> then the webapp can be assumed to be CDI aware.
> 
> Note: just relying on the webapp's own top level META-INF/beans.xml is insufficient for libraries that use CDI, even if the webapp itself isn't using CDI.

**Comment by gregw** [comment]
CDI redone with #3804
