### ISSUE TITLE
Improve ALPN documentation

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2011]
With 9.4.8 we have now 3 mechanisms for ALPN.
They are documented for a standalone server, but not for embedded usage for both client and server.

**Comment by janbartel** [comment]
The alpn documentation needs to be overhauled to make clear the usages between all the different mechanisms we support, and how boot.jar relates to them. We don't seem to have any doco on the java jdk9 alpn mechanism at all. @gregw  and @sbordet  can you provide @WalkerWatch  with any necessary information?

**Comment by gregw** [comment]
Reading the doco at https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html, it does appear to touch on most things... but it is perhaps a bit verbose and could be made more concise and to the point.
The points that need to be pushed are:
- ALPN is need to negotiate the http2 or https protocol over SSL
- We have multiple ALPN providers and at least 1 must be enabled (using our modules system or just put on the classpath as the serviceloader is used) to use http2.  
- More than one ALNP provider can be enabled and the most appropriate one for the environment will be selected.
- It may be that all enabled providers are not appropriate for the environment and thus no ALPN provider may be available.

We have 3 providers:

_OpenJDK 8_
PROS: works with java8   CONS: needs a boot loader path modification; only works with openJDK

_Java_
PROS: works with any JVM >= 9    CONS: not available for java 8

_Conscrypt_

PROS: works with java >=8;  allows fast SSL with conscrypt    CONS:  uses native libraries and only available on platforms supported by conscrypt.


I'm not sure we need much more than that, other than describing specifically which modules exist and how to enable them
