### ISSUE TITLE
Add start.jar --locate-class=<name> option

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#202]
migrated from Bugzilla [#464342](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464342)
status ASSIGNED severity _enhancement_ in component _start_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Project Inbox

On 2015-04-09 19:04:36 -0400, Joakim Erdfelt wrote:

> Add a new command line option called --locate-class=<name> that will investigate all of the jar files for the specified class (or resource).
> 
> It should list the jar file it was found in, what part of the configuration stack it was found (jetty.base vs jetty.home), and also the modules that would activate references to the located jar entry.
> 
> Idea from "Tim Halloran" [jetty-users] mailing list
> https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05707.html

On 2015-04-09 21:22:32 -0400, Greg Wilkins wrote:

> I'm a bit 50:50 about this one....  it is a bit special purpose.
> 
> Perhaps   --locate=<name>
> 
> and that will look for an xml, a jar or a class within a jar.
> 
> But I am cautious about bloat in start.jar!

**Comment by janbartel** [comment]
No progress on this one since 2015, and no votes, so closing this issue.
