### ISSUE TITLE
Introduce a name for `HttpClient` instances

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2020]
It would be handy, for systems that use multiple `HttpClient` instances in the same JVM, that `HttpClient`s have a name that differentiates them. This name should also be used in JMX, and in the internally created `QueuedThreadPool`.

**Comment by sbordet** [comment]
@gregw why did you close this ? It should be implemented.
#1921 was closed as an initial attempt to provide the functionality, but now the requirements are larger (e.g. name in JMX), so it really needs to be implemented.

**Comment by gregw** [comment]
sorry. confused
