### ISSUE TITLE
Illegal character 0x20 in state=HEADER for buffer

### ISSUE THREAD

**Issue by fbuecklers** [eclipse/jetty.project#2022]
Hi,
we are using the the jetty HTTP client in our server to request external resources. But we get some strange errors on some pages since they do not behave compatible to the latest HTTP specs. 

For instance if you request [https://us.braun.com/en-us](https://us.braun.com/en-us) we get following logs:
`Illegal character 0x20 in state=HEADER for buffer DirectByteBuffer@7b362163[p=590,l=13192,c=16384,r=12602]={HTTP/1.1 200 OK\r\n...-Allow-Headers <<<: Origin, X-Reque...4E\xFd\xF0\xF84z \xF4+|\xF4\x95=\x1b>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}`

The Response headers looks as the following:
```
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Vary: User-Agent, Accept-Encoding
Server: Microsoft-IIS/8.5
Set-Cookie: braun_us#lang=en-US; path=/
Set-Cookie: ASP.NET_SessionId=pimb44eu1ts4sd1raqs2sl4t; path=/; HttpOnly
Strict-Transport-Security: max-age=300
X-Frame-Options: SAMEORIGIN
Set-Cookie: __CSRFCOOKIE=m71fgPdokWdedn4Lt3TyntwmLA5QtPDEiFIXZRVByhalmgOTVboj5BP; path=/; HttpOnly
Access-Control-Allow-Headers : Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: IE=edge
X-Server: WPSC38
X-Content-Type-Options: nosniff
Date: Tue, 05 Dec 2017 20:51:25 GMT
Set-Cookie: BIGipServer~MAN3-PNG-RD1~us.braun.com-SC-ares.com=rd1o00000000000000000000ffff0a8bc13co8651; path=/
Content-Encoding: gzip
Transfer-Encoding: chunked
```

Affected Jetty Version:
9.3 (Tested with 9.3.14.v20161028)
9.4 (Tested with 9.4.8.v20171121)

Note that the issue does not happen always on that webpage.

The error seems to be in the [HttpParser](https://github.com/eclipse/jetty.project/blob/d4061fcfeb5a959e67547404a1fdfa5a203680db/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java#L1290) since a space is not expected in the HTTP header. However, there exist Servers which misbehave here and I expect that the Jetty Client should communicate with those Servers.

Do you see a way how Jetty can handle this properly? I see that there already exists many compliance checks in the Parser. Can this be added too?

**Comment by gregw** [comment]
@fbuecklers This is specified in [RFC7230 s3.2](https://tools.ietf.org/html/rfc7230#section-3.2) and the exact ABNF is:
```ABNF
     header-field   = field-name ":" OWS field-value OWS

     field-name     = token
     field-value    = *( field-content / obs-fold )
     field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
     field-vchar    = VCHAR / obs-text

     obs-fold       = CRLF 1*( SP / HTAB )
```

So the current spec is pretty clear that not even optional white space is allowed there, as was the prior spec: [RFC2616 s4.2](https://tools.ietf.org/html/rfc2616#section-4.2)

However we do have compliance modes to allow us to be more accepting, and I've just checked that in jetty-8 we did allow optional white space there.... so I guess we should support it in some compliance mode.

We were going to overhaul the compliance modes in jetty-10, but that is still a few months away.  So we'll look at supporting it in 9.4.x.  But it is not a high priority for us, so it may still be weeks or even months before we get a chance.  

However, we'd look favourably on a PR.  The fix would have to go around [here](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java#L1290) with the difficulty being that we want to accept `Header : value`, but not `Header with space: value`.  The compliance mode switching is also a bit of a mess... hence the need to refactor in 10.

**Comment by joakime** [comment]
Note that modern browsers will reject bad headers (in other words, that header will not exist, not be present, and not be used by the browser).

That bad header is essentially a no-op and does not do what the server thinks it does.
Perhaps our HttpParser could use a "drop bad headers" option?

**Comment by fbuecklers** [comment]
This sounds a useful extension since there are exists many web servers which do not implement the HTTP standard correctly.

**Comment by fbuecklers** [comment]
Hm, I try to provide a pull request, but currently, it seems not to be possible to provide a compliance mode in the jetty client.
Should I just ignore all invalid chars when an http header name is parsed? Or it should be possible to configure a compliance mode in the jetty client too.

**Comment by joakime** [comment]
@gregw how do you want to describe this in VERSION.txt ? (change the title of this issue to fit please)

**Comment by fbuecklers** [comment]
You mean RFC or? :-D
Really cool and many thanks for the help and the good solution!
