### ISSUE TITLE
When start.jar encounters error reading ini or xml file error, report the file name

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#203]
migrated from Bugzilla [#464441](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464441)
status ASSIGNED severity _normal_ in component _start_ for _9.3.x_
Reported in version _9.3.0_ on platform _PC_
Assigned to: Joakim Erdfelt

On 2015-04-11 08:12:00 -0400, yang kun wrote:

> Now, if .ini or .xml file charset has problems, will cause expetion,the error is flowing:
> 
> java.nio.charset.MalformedInputException: Input length = 1
>   at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
>   ...
>   at org.eclipse.jetty.start.TextFile.<init>(TextFile.java:57)
> 
>   or 
> 
> java.lang.reflect.InvocationTargetException
>        ...
>         at java.lang.reflect.Method.invoke(Method.java:483)
>         at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
>         at org.eclipse.jetty.start.Main.start(Main.java:817)
>         at org.eclipse.jetty.start.Main.main(Main.java:112)
> Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 2 å­èç UTF-8 åºåçå­è 2 æ æã
> ...
> 
>   Above exception, we don't know which files has problem, So I suggest catch the IOException,then rethrow IOException, but report the file,for exampe,If I modify the TextFile constructor:
> 
>   try (BufferedReader buf = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
>   } catch (IOException e) {
>   throw new IOException("read " + file + " error: ", e);
>   }
> 
>   The error info will be folowing, I think this better, :)
> 
> // report the error file
> java.io.IOException: read E:\Java\soft\jetty-distribution-9.2.3.v20140905\my-demo-base\start.ini error: 
>   at org.eclipse.jetty.start.TextFile.<init>(TextFile.java:70)
>   at org.eclipse.jetty.start.StartIni.<init>(StartIni.java:33)
>   ...
>   at org.eclipse.jetty.start.Main.main(Main.java:107)
>   ...
> Caused by: java.nio.charset.MalformedInputException: Input length = 1
> 
>   The xml read is similar.

**Comment by joakime** [comment]
This has been addressed in the XMLConfiguration class itself and is no longer an issue.
