### ISSUE TITLE
org.eclipse.jetty.server.session.FileSessionDataStore.deleteAllFiles(File, String) can become slow

### ISSUE THREAD

**Issue by LukeButtersFunnelback** [eclipse/jetty.project#2038]
Hi

After upgrading jetty which required switch to using `FileSessionDataStore` it appears that a bunch more CPU is being used. After running jvisualvm it appears the time is taken in `FileSessionDataStore#deleteAllFiles`.

It seems that `FileSessionDataStore#deleteAllFiles` can become very slow, I suspect when the the directory holding the files contains lots of sessions for example here is how long it takes to list the files in that directory:
```
time ls sessions_dir | wc
  27172   27172 1640249

real    0m0.879s
user    0m0.206s
sys     0m0.029s
```

Perhaps the issue is unlike the `HashSessionManager` the `FileSessionDataStore` I think does not remove old sessions so I guess Jan's answer on https://stackoverflow.com/questions/46332223/upgrading-to-jetty-9-4-replacing-the-hashsessionmanager may need to be updated

**Comment by janbartel** [comment]
Hi 

The FileSessionDataStore is indeed the equivalent replacement for the HashSessionManager's ability to persist sessions to the disk. It does behave slightly differently, although both can delete session files.  

It think the slowness in FileSessionDataStore is due to iterating over all the files to find the one for the session under consideration. It iterates because the name of the file contains the expiry time, not just the session id. If for some reason we failed to delete older files for the same session there may be more than one and this method tries to ensure they're all cleaned up.

There may be a faster way to do this, see #538.

**Comment by LukeButtersFunnelback** [comment]
I think the issue is that we are listing so many files (the `return (name.contains(idInContext));` probably doesn't cost that much.
On my (very fast machine) with 38K files in the session data folder it takes 29ms to run deleteAllFiles (I made a copy of the function locally and ran it). Considering that requests are typically sub 100ms, adding 29ms is a substantial amount of time added.

I think to avoid that a trivial way of dealing with that is to spread the session files into sub folders within the session data folder. If we had 1000 sub folders the work should be about 1000 times less. Although this might not speed it up I don't think this solves the problem.

Looking at the session data folder with the latest version of jetty I see 3 week old session files. Are we expecting session files to live this long? I notice for the previous setup with `HashSessionManager` no files are actually present on disk. I think it cached in memory however if it was holding on to sessions like `FileSessionDataStore` appears to I would have expect to see a bunch of memory usage.  I am still somewhat convinced that the suggest configuration does not result in sessions being cleaned up as they used to.

**Comment by janbartel** [comment]
No question that it would be good to be faster, and I'll have a look at that.

3 week old session files would not be unusual if any of the following is true: you have session max inactive time >= 3 weeks; you have an indefinite session max inactive time; you have no session housekeeping  (dead or you haven't configured the housekeeper); you have configured a huge housekeeping thread scavenging interval; the housekeeper can't delete expired session files.

If you could post your jetty session configuration, including the max inactive interval for sessions, that would be useful. Might also be useful if you posted some examples of the session file names and last modified times (but please do NOT include the session ids in the filenames).

I wouldn't have recommended that you use the old HashSessionManager nor the new FileSessionDataStore in a production environment where you have a lot of sessions - any of the other session store technologies (jdbc, mongo, infinispan, gcloud if you're using google services etc etc) would be more performant, and more robust (using separate servers).

**Comment by janbartel** [comment]
Hi Luke,

I've started implementing improvements to FileSessionDataStore. Take a look at the branch jetty-9.4.x-2038-slow-filesessiondatastore to see the direction I'm thinking. I've got a few more tweaks to go (eg look on the filesystem during a load if there is no filename in the _sessionFileMap), but I will be AFK for a few days. Just wanted to flag it to you if you've got time to give it a run/comment.

**Comment by LukeButtersFunnelback** [comment]
Right so the change is to have in a map `sessions` to `filenames`. Which should make the lots of sessions case way faster at the cost of more JVM heap usage, will that be an issue?. I think this is similar to what was done before.
 
The `doGetExpired` might be a bit of a worry because that `Set<String>` has the potential to be a large set, is this called infrequently? Can a runnable be passed in that gets executed on each expired session, to help reduce sudden spikes in memory usage? I guess the case is sessions might be growing slowly and a sys-admin would have time to watch it grow and do something about it but if we have hundreds of megs of session ids, then the occasional call to `doGetExpired` we will cause a sudden mem usage spike that might lead to a OOM.

I guess this also stamps out any possible behavior of trying to restore or copy sessions from a backup or another machine running jetty, this probably makes sense as implementations that want to share sessions over multiple machines shouldn't be using this implementation.

thanks for taking the time to dig into this.

**Comment by janbartel** [comment]
@LukeButtersFunnelback  thanks for the feedback, appreciated. I'm back at the keyboard on and off and will be working on this issue again.

FYI the doGetExpired() method gets scheduled on a thread as per the scavenge interval that is configured - I think the default is 10mins.  The next scavenge cycle timer only starts once the previous scavenge has finished.

**Comment by janbartel** [comment]
@LukeButtersFunnelback I've made a PR for the changes to FileSessionDataStore. I've made a few adjustments since you last looked, including adding an infrequent scavenge over the actual files on the disk to delete "orphans'. You might want to take a peek.

**Comment by janbartel** [comment]
Committed PR #2102.

**Comment by LukeButtersFunnelback** [comment]
ah doing the check every now and again makes sense, thanks Jan!
