### ISSUE TITLE
Review blocking write timeout

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2042]
`HttpOutput` blocking writes are currently defaulting to "infinite" wait, because of the logic in `HttpOutput.WriteBlocker` and the default configuration values for `HttpConfiguration.blockingTimeout`.
Review whether it's the case to change the logic to use `HttpConfiguration.idleTimeout` instead and/or change the default values.

**Comment by gregw** [comment]
It makes little sense to have blocking timeout and idle timeout the same value, as this results in two timeouts racing for the same event on many io operations. The intention may be too deprecate the blocking timeout so a default infinite value is a good match for that.

**Comment by gregw** [comment]
See also #1958

**Comment by sbordet** [comment]
Closing, as blockingTimeout has been deprecated/removed.
