### ISSUE TITLE
ConcurrentModificationException during annotation parsing

### ISSUE THREAD

**Issue by JoonasVali** [eclipse/jetty.project#2043]
I believe the fix to issue https://github.com/eclipse/jetty.project/issues/1819 seen here: https://github.com/eclipse/jetty.project/commit/7ad415b9b8dba2b78eb486aab6191face654e72b
has caused a ConcurrentModificationException on the ArrayList now used in the _parsedClassNames.
While the ConcurrentHashMap itself is thread safe, the internal ArrayLists are not when iterating over the list is being done in 
`LOG.warn("{} scanned from multiple locations: {}", classname, existing);`

I observed a ConcurrentModificationException happening in our test logs which resulted in deployment failure:

java.util.ConcurrentModificationException
	|	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	|	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	|	at java.util.AbstractCollection.toString(AbstractCollection.java:461)
	|	at java.lang.String.valueOf(String.java:2994)
	|	at org.eclipse.jetty.util.log.StdErrLog.format(StdErrLog.java:552)
	|	at org.eclipse.jetty.util.log.StdErrLog.format(StdErrLog.java:441)
	|	at org.eclipse.jetty.util.log.StdErrLog.warn(StdErrLog.java:296)
	|	at org.eclipse.jetty.annotations.AnnotationParser.addParsedClass(AnnotationParser.java:572)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:913)
	|	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:879)
	|	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
	|	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:875)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:839)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	|	at java.lang.Thread.run(Thread.java:748)

**Comment by janbartel** [comment]
Fix applied to jetty-9.4.x and master.

**Comment by tholu** [comment]
This regression also seems to be present in Jetty 9.3.22 and newer, at least I get lots of `scanned from multiple locations` warnings when I try to use those versions.

**Comment by joakime** [comment]
The warning `scanned from multiple locations` is valid and indicates a messy setup/configuration on your side.

You have multiple locations for the same class, potentially even different versions.
The presence of these warnings indicates a high probability of unpredictable / ambiguous behavior at runtime.
Potentially different behavior each time you start your webapp.

Pay attention to the details of these warnings, it tell you each location of where it found the multiples copies.

**Comment by tholu** [comment]
@joakime Thanks for the explanation! Is there any common cause of this? In my warnings often the same file is listed twice (e.g. in my Maven repository).

**Comment by joakime** [comment]
The likely reason for the same class to be listed multiple times in the "Locations" portion of that warning means your classpath / classloader has that JAR listed multiple times.  

That would means a slow startup / scan, but is harmless at runtime.

**Comment by joakime** [comment]
@tholu The work @janbartel made in commit eebe1394945231f87259b274890727cafd750628 to minimize duplicates will show up in Jetty 9.4.9 (not yet released)
