### ISSUE TITLE
JDBCSessionManager.Session#setCookieSet() is not synchronized

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#205]
migrated from Bugzilla [#465162](https://bugs.eclipse.org/bugs/show_bug.cgi?id=465162)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.2.5* on platform *PC*
Assigned to: Jan Bartel

On 2015-04-22 02:37:55 -0400, yang kun wrote:

> The _cookieSet field's getter/setter method is:
> 
> // is not synchronized
> public void setCookieSet(long ms) {
> 	_cookieSet = ms;
> }
> 
> public synchronized long getCookieSet() {
> 	return _cookieSet;
> }
> 
>   Others, these fields can use volatile, then remove getter/setter's synchronized.

**Comment by janbartel** [comment]
Fixed in jetty-9.4 as part of session impl refactoring
