### ISSUE TITLE
remove all/most javadoc warnings

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2056]
The code base has a lot of javadoc warnings.    It would be good to reduce these to a minimum.

**Comment by gregw** [comment]
@olamy I know this is not much fun... but if  you gave this one a go,  it would be a reasonable tour of the code and get your commit karma increased.

**Comment by olamy** [comment]
Not sure to fix all english/aussie typos :-)
but sounds good!

**Comment by gregw** [comment]
The aussie typos are a test.... if you don't understand them we'll be calling border farce!
