### ISSUE TITLE
Backport #347 to Jetty 9.2.x

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2065]

**Comment by joakime** [comment]
Lots of test failures on jetty-9.2.x due to this backport.

**Comment by sbordet** [comment]
@joakime thanks, I have pushed a better fix for this issue, and build now passes fine.

**Comment by sbordet** [comment]
Turned out that the backport contained a mistake, resetting the wrong field to -1 in `HttpConnectionOverHTTP`.

**Comment by sbordet** [comment]
Fixed.
