### ISSUE TITLE
Support javax.websocket version 1.1

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#207]
migrated from Bugzilla [#467246](https://bugs.eclipse.org/bugs/show_bug.cgi?id=467246)
status ASSIGNED severity _normal_ in component _websocket_ for _9.4.x_
Reported in version _9.4.0_ on platform _All_
Assigned to: Joakim Erdfelt

On 2015-05-13 11:23:43 -0400, Joakim Erdfelt wrote:

> Add support for the changes introduced in javax.websocket version 1.1

On 2016-01-22 08:10:59 -0500, Sergii Kabashniuk wrote:

> Hello
> I'm trying to add support of javax.websocket version 1.1
> And I need some advice.
> 
> This is my prototype of JsrSession.
> 
> ```
> @Override
> public <T> void addMessageHandler(Class<T> clazz, MessageHandler.Whole<T> handler) {
>     doAddMessageHandler(clazz, handler);
> }
> 
> @Override
> public <T> void addMessageHandler(Class<T> clazz, MessageHandler.Partial<T> handler) {
>     doAddMessageHandler(clazz, handler);
> }
> 
> @Override
> public void addMessageHandler(MessageHandler handler) throws IllegalStateException
> {
>     doAddMessageHandler(ReflectUtils.findGenericClassFor(MessageHandler.class, handler.getClass()), handler);
> }
> private <T> void doAddMessageHandler(Class<T> clazz, MessageHandler handler) {
>     Objects.requireNonNull(handler, "MessageHandler cannot be null");
> 
>     synchronized (wrappers)
>     {
>         for (MessageHandlerMetadata metadata : messageHandlerFactory.getMetadata(clazz))
>         {
>             DecoderFactory.Wrapper wrapper = decoderFactory.getWrapperFor(metadata.getMessageClass());
>             if (wrapper == null)
>             {
>                 StringBuilder err = new StringBuilder();
>                 err.append("Unable to find decoder for type <");
>                 err.append(metadata.getMessageClass().getName());
> ```
> 
> The part where I have problems is here messageHandlerFactory.getMetadata(clazz).
> Joakim can you help me? Is there any simple utility method that can allow to move forward.
> Or this code need more complex refactorings.
> Can you help me with some inputs?

On 2016-02-08 09:45:59 -0500, Joakim Erdfelt wrote:

> @Sergii
> 
> What are you trying to do?

On 2016-02-08 09:58:45 -0500, Sergii Kabashniuk wrote:

> I'm trying to implement two methods  ( addMessageHandler) what was added in websocket 1.1 API
> See more
> https://jcp.org/aboutJava/communityprocess/maintenance/jsr356/websocket-1.1-changes.txt
> 
> To do that I've added fourth method 
> 
> private <T> void doAddMessageHandler(Class<T> clazz, MessageHandler handler)
> 
> And trying to call it from original one.
> My question is around             
> 
> for (MessageHandlerMetadata metadata : messageHandlerFactory.getMetadata(clazz))
> 
> I don't know how to handle it.

On 2016-02-08 13:33:45 -0500, Joakim Erdfelt wrote:

> (In reply to Sergii Kabashniuk from comment # 3)
> 
> > I'm trying to implement two methods  ( addMessageHandler) what was added in
> > websocket 1.1 API
> > See more
> > https://jcp.org/aboutJava/communityprocess/maintenance/jsr356/websocket-1.1-
> > changes.txt
> > 
> > To do that I've added fourth method 
> > 
> > private <T> void doAddMessageHandler(Class<T> clazz, MessageHandler handler)
> > 
> > And trying to call it from original one.
> > My question is around             
> > 
> > for (MessageHandlerMetadata metadata :
> > messageHandlerFactory.getMetadata(clazz))
> > 
> > I don't know how to handle it.
> 
> This is especially tricky to implement.
> 
> The existing tracking is based on classes.
> The MessageHandlerFactory tracks based on MessageHandler classes, and each one of those can be 1 or 2 MessageHandler implementations. (one for TEXT and one for BINARY is supported)
> 
> So that if you had something like ...
> 
> public class FooHandler implements Whole<String>, Whole<ByteBuffer> {
> }
> 
> then you could use the same FooHandler for either TEXT or BINARY.
> 
> With lamda expressions, this relationship is no longer true.
> There's no class with any sanity, the tracking of class to message handler is irrelevant.
> There's no need really with lamdas, but the MessageHandlerFactory is integral to how this functions, and with lamdas we have to somehow bypass this step entirely.  This is going to be potentially awful for performance, as it essentially tosses out any intelligence useful for caching or object reuse (adding to the time to establish an endpoint, and increasing GC churn)

On 2016-02-09 09:14:52 -0500, Joakim Erdfelt wrote:

> Bumping to Jetty 9.4.0, as the changes to support this are turning out to be far too dramatic.

**Comment by joakime** [comment]
Present in jetty-9.4.x (the next release, 9.4.7, should have it)
Also merged to master/10.0.x

**Comment by yamass** [comment]
If I get it right, this has _not_ found its way into version 9.4.x of jetty. (see https://github.com/eclipse/jetty.project/issues/1650#issuecomment-322299153)
