### ISSUE TITLE
Consider deprecating/removing MultiException

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2075]
Now that every `Throwable` can have suppressed `Throwable`s, is there a reason to keep `MultiException` around ?

**Comment by gregw** [comment]
I think the class is still needed.   At the very least it provides useful/readable utility methods to make it clear that multiple exceptions are expected and that they are being aggregated.

But I also think there is a difference between and exception with suppressed exceptions, which can mean there was an exception and other things were thrown while handling it,  vs a MultiException that indicates multiple probably independent failures occurred and one of them does not suppress the others.

However, I do think that we can perhaps update the class and remove it's own internal array list and just use the suppressed list.
