### ISSUE TITLE
Embedded Jetty graceful shutdown

### ISSUE THREAD

**Issue by chazovams** [eclipse/jetty.project#2076]
Hi! Seems like there is inconsistent behavior in Jetty Server stopping. Jetty Server.stop() at first closing connections and then finishing processing queued requests. In my application at server stopping I have some successfully processed requests, but responses cannot be sent because of connections closed. I'm using 9.4.7 version of server. Please help me to understand if this is correct Jetty behavior or maybe you can tell, how can I prevent connections closing before requests processing is done

**Comment by joakime** [comment]
This question has come up on stackoverflow.com recently too.

* https://stackoverflow.com/questions/47922475/jetty-graceful-shutdown
* https://stackoverflow.com/questions/47925525/jetty-graceful-stopping

**Comment by joakime** [comment]
This question seems to overlap with the following issues:

* #2048 - Server.stop not closing connections (open - has commit fdc847f)
* #1415 - Make jetty http/1.1 graceful shutdown more graceful (open - no commits)
* #1549 - Cannot stop Jetty gracefully (closed - documentation commit only)
* #1913 - Waiting for Server Shutdown (open - no commits, more info required)

**Comment by joakime** [comment]
Note: work on issue #2048 is being done in branch [jetty-9.4.x-2046-Not-Graceful](https://github.com/eclipse/jetty.project/tree/jetty-9.4.x-2046-Not-Graceful) (PR #2047)

**Comment by chazovams** [comment]
Yes, this questions in StackOverFlow are mine. Thanks for the answer. So could you tell me please when this branch expected to be merged to master and will be available in release?

**Comment by joakime** [comment]
master branch is for Jetty 10.x and isn't ready yet.

jetty-9.4.x branch (where you seem to show interest) is the place this change (in that  `jetty-9.4.x-2046-Not-Graceful` topic branch) will be eventually merged too.  

Pay attention/star/subscribe to PR #2047 and that will tell you when that is merged back to an official branch.  

But be patient, this time of year is slow for commits/merges (too many people out/away for the holidays)

**Comment by gregw** [comment]
@chazovams do you have the stats handler installed and a positive stop timeout set?   Without either of those, then server.stop will not be graceful.

Give us as much detail as possible so we can make sure the changes we are working on will solve your problem as well as other problems.

**Comment by chazovams** [comment]
@gregw stop timeout is 30 sec by default, but I had no statistic handler for server. With this handler shutdown works fine, thank you. Could you explain please why jetty's graceful shutdown doesn't work without it? I'm using spring boot and I see the only one way to set stats handler to server - through server customizer, which one I'd prefer not to use in my app.

**Comment by gregw** [comment]
Without the stats handler, jetty does not keep a central count of the number of outstanding requests.  It is the stats handler that keeps that count and it is actually the graceful shutdown of the stats handler that waits for the count to go to zero.

We do say this in our documentations, but I'll add a note in the javadoc as well.
