### ISSUE TITLE
CSV splitting utility

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#208]
migrated from Bugzilla [#467868](https://bugs.eclipse.org/bugs/show_bug.cgi?id=467868)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.3.0* on platform *All*
Assigned to: Project Inbox

Original attachment names and IDs:
- _[split.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=253638)_ (ID 253638)

On 2015-05-21 10:06:12 -0400, Greg Wilkins wrote:

> Created attachment 253638
> patch
> 
> refactor multiple split(",") calls.

**Comment by joakime** [comment]
Fixed in commit 3e401a62e9e60accfa8550d7c45e0b659ff6ff88
