### ISSUE TITLE
Removed embedded ReservedThreadExecutors

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2087]
From working with various proposals for #1803, it has become increasingly clear that the current usage of the ReservedThreadExecutor is difficult to configure and fragile to changes.

Currently each component that wishes to use reserved threads has to create it's own reservedThreadExecutor, which has to be sized either by configuration or heuristics.   The thread budget mechanism works to inform the user if such a configuration in not workable, but it would be far better to avoid the problem in the first place.

I would propose that instead of having RTEs embedded in the components that need them, we instead simply make a RTE that the servers executor may or may not implement.  If it implements the interface then components can call tryExecute, if it doesn't then they cannot.   This would mean that typically only a single RTE would need to be configured and it would be safe to slightly oversize it as it will lazily allocate threads and dynamically find the optimal level.

**Comment by gregw** [comment]
@sbordet thoughts

**Comment by sbordet** [comment]
Implemented by #2119.
