### ISSUE TITLE
websocket parseAndFill race

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2092]
In  jetty-10, the websocket parseAndFill method had the following logic
```java
    private void fillAndParse()
    {
        if(!fillAndParseScope.compareAndSet(false,true))
            return;
                
        try
        {
            // do the filling and parsing

            if (filled == 0)
                fillInterested();
        }
        finally
        {
            fillAndParseScope.set(false);
        }
    }
```

This is a race.  Once `fillInterested()` is called, another thread may be dispatched to call `fillAndParse`, if it arrives before  `fillAndParseScope.set(false)` then it will become a noop and the call will be lost.

This has been fixed in the jetty-10 branch, but if similar logic exists in 9.x, it also needs to be fixed.

**Comment by joakime** [comment]
Turns out onFillable in jetty-9.4.x doesn't have the same logic.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java#L378-L412
