### ISSUE TITLE
jetty's response not contains head of "Connection : keep-alive"

### ISSUE THREAD

**Issue by greatwallgoogle** [eclipse/jetty.project#2099]
httpclient's request has head of "Connection : keep-alive",but jetty's response not contains head of "Connection : keep-alive"

**Comment by sbordet** [comment]
There is no need for `Connection: keep-alive` because in HTTP/1.1 connections are persistent by default.

**Comment by greatwallgoogle** [comment]
Apache httpclient throw exception with no “Connection: keep-alive”

**Comment by joakime** [comment]
Then Apache HttpClient is old and only uses HTTP/1.0

See the spec: https://tools.ietf.org/html/rfc7230#section-6.3
