### ISSUE TITLE
Update licence headers and plugin for 2018

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2108]
@joakime  do you have a cool script to do that?

**Comment by joakime** [comment]
Nothing fancy on my end, just some bash command line basics with SED.

**Comment by joakime** [comment]
The technique, included here for future new years celebrations ...

``` shell
$ find . -name "*.java" -exec sed -i -e "s/1995-2017/1995-2018/g" {} \;
```

**Comment by joakime** [comment]
Starting with jetty-9.2.x and merging forward to

* jetty-9.3.x
* jetty-9.4.x
* jetty-10.0.x

not touching master

**Comment by joakime** [comment]
Ironic that updating for year 2018 on issue 2108.

The number of times I've mis-typed both ends on this is silly.

**Comment by joakime** [comment]
Upgrade for s/1995-2017/1995-2018/ is complete in the following branches.

* jetty-9.2.x
* jetty-9.3.x
* jetty-9.4.x
* jetty-10.0.x

Closing issue.
