### ISSUE TITLE
Jetty server crashes

### ISSUE THREAD

**Issue by kgupta4** [eclipse/jetty.project#2111]
We are using jetty server and when it is on load then the server is crashed without showing much of information.
We have also put it on JMX. The CPU usage and memory looks fine, but still Jetty server crashes. Please let me know what parameters we should look for and how can we isolate issue which is causing jetty server crash.

**Comment by janbartel** [comment]
This is being discussed on the jetty-user lists, with subject line "Jetty Server Crashes" and as stated there, would not seem to be a jetty bug. I'm closing this issue - if  the discussion throws up anything that could be construed as a jetty problem it can be reopened.
