### ISSUE TITLE
Fix NPE in JettyHttpServerProvider

### ISSUE THREAD

**Issue by williampeer** [eclipse/jetty.project#2114]
I am currently trying to instantiate an HttpServer using the `public static HttpServer create()`, as found within `com.sun.net.httpserver`, which uses `jetty-http-spi` found on the classpath.
However, when Jetty is used as the SPI, calling `HttpServer.create()` results in an NPE. This seems to be due to that the `create()`-method calls the `JettyHttpServerProvider` with a `(InetSocketAddress)null`-parameter, which will then break when calling `.getPort()` on the null-reference.

Consulting the JavaDoc for the `create`-method, found here: https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html#create--,
it states that create

> creates a HttpServer instance which is initially not bound to any local address/port. The HttpServer is acquired from the currently installed HttpServerProvider The server must be bound using bind(InetSocketAddress,int) before it can be used.

Thus, resulting in an NPE when attempting to use its unbound address and port.

In order to reproduce the bug, you may clone and run this repo: https://github.com/williampeer/jetty-http-spi-test

Following is the resulting stacktrace output:

```
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.jetty.http.spi.JettyHttpServer.bind(JettyHttpServer.java:107)
	at org.eclipse.jetty.http.spi.JettyHttpServerProvider.createHttpServer(JettyHttpServerProvider.java:69)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:105)
	at JettyHttpServerTestMain.main(JettyHttpServerTestMain.java:9)
```

## Suggested fix

The JavaDoc for `HttpServer.create()` states that 

> The server must be bound using bind(InetSocketAddress,int) before it can be used.

Perhaps the JettyHttpServerProvider could omit calling bind in the event of the InetSocketAddress being `null`?
This would make it compliant with the JavaDoc, presumably enabling implementations to call bind on the server without resulting in an NPE.

### Jetty version
The above issue is currently tested (and confirmed to be present) in jetty versions 9.4.8.v20171121, as well as in 9.2.x (tested for versions 9.2.22.v20170606 and 9.2.23.v20171218).

**Comment by janbartel** [comment]
@williampeer thanks for the report with the repo test case. Can you update your report to include the version of jetty please?

**Comment by williampeer** [comment]
@janbartel updated the report now

**Comment by janbartel** [comment]
@williampeer  have a look at PR #2115.  Try building the branch if you like to see if that fixes the issue, I think it should do.

**Comment by williampeer** [comment]
@janbartel thank you. I was able to verify that it fixes the issue. (https://github.com/williampeer/jetty-http-spi-test/tree/test-9.4.9-SNAPSHOT)

**Comment by janbartel** [comment]
@williampeer 9.2 is not being released on a regular basis as it has been superceded. However, I've added just the null protection fix in if you want to build it yourself.
