### ISSUE TITLE
Refactor jetty-deploy for Jetty 10.x

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2116]
The conversation in Issue #1602 indicates a desire to remove jetty-deploy as the behavior in Jetty Component/LifeCycle has changed enough in the past 8 years to make jetty-deploy less viable.

**Comment by joakime** [comment]
Back in the days of Jetty 7.0, before the days of Servlet 3.0 and bytecode scanning, web-fragments, and a myriad of other new servlet/web technologies, the DeploymentManager was created to help groups that wanted to hook into / modify the deployment processes within Jetty.

Here's a quick rundown of some of the ways the DeploymentManager have been used since Jetty 7.0 days.   Hopefully we can document new ways to accomplish each goal / task that has done in the DeploymentManager in the past for users upgrading to Jetty 10.x

Deployment of a Context points of interest.
(or where people want to get involved in a deployment)

The Basic 4 steps:

1) Deploy
2) Start
3) Stop
4) Undeploy


The Points where people want to hook into

**1: app-discovered (app discovered) [Node: UNDEPLOYED]**

  * The app has been discovered.
  * The app has no ContextHandler defined yet.
  * The app location/war/resource is known.
  * validate / verify the webapp contents itself
  * inject / modify webapp contents itself
  * copy webapp to cluster of Jetty instances.
  * DevOps auditing (eg: log app discovery and location)
  * DevOps system setup for webapp (eg: dns for <webappname>.company.com)
  * Reject webapps based on arbitary criteria.

**2: deploy (app is placed into server handler heirarchy) [Nodes: DEPLOYING & DEPLOYED]**

  * The app now has a ContextHandler / WebAppContext.
  * The Server reference is now valid for the WebAppContext.
  * The handler heirarchy is now valid.
  * Tell cluster to deploy their webapp copies too.
  * Knowledge of contextPath is being replaced (hot deploy).
  * DevOps modification of context (eg: virtualhosts, centralized logging)
  * DevOps point for auditing.
  * DevOps point for adding monitoring features.

**3: pre-start (app will be started) [Node: STARTING]**

  * The app wants to start.
  * Jetty Component LifeCycle has not yet been applied.
  * Common coordination point for cluster deployments.
  * DevOps point for injecting metrics tracking.
  * DevOps point for auditing.

**4: start (app is starting) [Node: STARTING]**

  * Jetty Component LifeCycle for webapp .start() is in progress.

**5: app-available (app is started and is accepting requests) [Node: STARTED]**

  * Jetty Component LifeCycle has completed for .start().
  * WebApp is started.
  * DevOps location for auditing.
  * WebApp is now accepting requests. (Prior to this step, you will get either a status code 404 or 503 against contextPath)

**6: pre-stop (app will be stopped) [Node: STOPPING]**

  * The app wants to stop.
  * Jetty Component LifeCycle has not called .stop() yet.
  * WebApp is no longer accepting new requests.
  * DevOps point for auditing.
  * DevOps point for monitoring.
  * DevOps point for interacting with other components (firewall, load balancer, batch processing, etc)
  * Coordination point for custom cluster deployments.

**7: stop (app is being stopped) [Node: STOPPING]**

  * Jetty Component LifeCycle for webapp .stop() is in process.

**8: post-stop (app is stopped) [Node: STOPPED]**

  * Jetty Component LifeCycle for webapp .stop() is complete.
  * DevOps point for auditing.
  * DevOps point for monitoring.

**9: undeploy (app is being removed from server) [Node: UNDEPLOYING]**

  * WebApp is being removed from Server handler tree.
  * DevOps point for auditing.
  * DevOps point for cleanup.

**Comment by gregw** [comment]
I think this is a bit of an overreaction to the issue raised by #1602 .  Jetty-10 will still need jetty-deploy as it has all the functionality to discover and inject webapps.   The only issue is that it has a start phase, which didn't really do what was intended because managed beans are started/stopped by their container.

So perhaps the deployment manager could be simplified a bit.  Perhaps a full extensible graph implementation is no longer required?   However, I certainly think that we do have behaviours binding to deployment steps, so it cannot be completely removed.

**Comment by WalkerWatch** [comment]
Good write-up, Joakim. Based on all the places where folks can hook into the `DeploymentManager`, is this something we would really want to completely eliminate in Jetty-10? It sounds like the real issue exists around the start-up phase.

I think it is still worth the exercise of pointing out where parts of the lifecycle have changed over the years to help users see where their processes can change perhaps, but I'd be -1 to complete removal in Jetty-10, at least it stands right now.

**Comment by joakime** [comment]
More information for the discussion ...

There is a jetty-deploy `AppLifeCycle` which is a generic state graph (directional, but not unidirectional), defaulted but not hardcoded, the node names and the transitions (edges) and the number of nodes are all flexible.
The default node names and default bindings for those nodes happen to have similar names to what exists within the Jetty `LifeCycle`.
Advanced user of `DeploymentManager` are free to rework the AppLifeCycle to fit into their needs.

Some examples: 
 * Lets start the App before we attach/deploy it to the ContextHandlerCollection.
 * Lets use a custom ContextHandlerCollection that allows for both the old App and the new App to coexist in the collection, swapping which one gets the traffic with a custom AppLifeCycle binding.  (example AppLifeCycle: requestAppGoal(ENABLE_TRAFFIC, newApp): START -> DEPLOY_STAGE -> ENABLE_TRAFFIC -> UNDEPLOY_OLD(requestAppGoal(GRACEFUL_STOP -> UNDEPLOY, oldApp))

I encourage us to find a way to keep the jetty-deploy `AppLifeCycle` in Jetty 10.x, and recognize that its not directly relatable to the Jetty `LifeCycle`, only the distributed Standard Bindings have that relationship/connection with the Jetty LifeCycle.

**Comment by gregw** [comment]
The newly added in 9.4.x deploy state `FAIL` is not rigorous.   It will be used for hot deploy when the context may fail when started during the standard deploy/start steps, but it will not be followed during a normal startup deployment as the context is not started by the StandardStarter.

A LifeCycle listener could be used to track the success/failure of a subsequent start.
