### ISSUE TITLE
Java9 name conflict between apache-jsp from jetty and org.mortbay.jasper

### ISSUE THREAD

**Issue by jontro** [eclipse/jetty.project#2123]
When trying to import StandarJarScanner using the following setup as described here https://github.com/jetty-project/embedded-jetty-jsp/blob/master/src/main/java/org/eclipse/jetty/demo/Main.java in a java 9 project I get an ambiguous name collision between
org.mortbay.jasper:apache-jsp and org.eclipse.jetty:apache-jsp

Using 9.4.8.v20171121 of jetty. 

`
import org.apache.tomcat.util.scan.StandardJarScanner;
import org.eclipse.jetty.apache.jsp.JettyJasperInitializer;`

In module-info.java I use `requires apache.jsp;`

Unfortunately both jars will be named apache-jsp so there is an ambiguous include

(https://stackoverflow.com/a/46574200/429972 to see some more context)

I'm not sure how to proceed, but is adding module-info.java and naming the modules more uniquely to jetty:apache-jsp possible?

**Comment by namannigam** [comment]
@jontro My two cents here, either of the library owners can make use of the [`Automatic-Module-Name`](https://stackoverflow.com/a/46501811/1746118) and rename their module. Which one, would probably be answered better by someone else.

**Comment by janbartel** [comment]
Note that I opened issue https://github.com/jetty-project/jasper-jsp/issues/4 for this. When the PR to update the version of org.mortbay jars is approved (PR #2129 ) , I'll close this issue.
