### ISSUE TITLE
Assign stable Java 9 Automatic-Module-Name for all published artifacts

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2127]
In light of Issue #2123 it would be a good idea to specify the `Automatic-Module-Name` manifest entry for all of the published artifacts in Jetty to be unique and stable now.

Other open source projects have gone with ...

```
Automatic-Module-Name: <groupId>.<artifactId>
```

We should follow suit.

**Comment by sbordet** [comment]
Nope that's wrong, we cannot use `groupId.artifactId`, as explained in:
http://blog.joda.org/2017/04/java-se-9-jpms-modules-are-not-artifacts.html and
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by sbordet** [comment]
See also #1873.

**Comment by sbordet** [comment]
Done.
