### ISSUE TITLE
jetty.osgi.boot requires Server services registered before ContextHandler services

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#213]
migrated from Bugzilla [#470116](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470116)
status ASSIGNED severity *normal* in component *osgi* for *9.3.x*
Reported in version *9.2.9* on platform *Other*
Assigned to: Jan Bartel

On 2015-06-12 17:51:00 -0400, Magnus Jungsbluth wrote:

> I really like the service based ContextHandler approach to deploying web apps with jetty.osgi.boot. I stumbled on some oddity and found that in ServiceWatcher#addService if no Server is registered with a matching name no deployment will ever happen. If the Server was registered later the ContextHandler should still be deployed.
> 
> The really bad corollary of this is that ports are open before content is deployed. This means that for fractions of a second 404 status codes can be received which is especially bad for rest style services booting up under high load.
> 
> As a possible workaround we can register a root handler that returns 5XX status codes if no child handler handles the request

On 2015-06-19 02:07:47 -0400, Jan Bartel wrote:

> Magnus,
> 
> Hmmm .... tricky ...
> 
> As regards the startup scenario where the server starts before any contexts are deployed to it, certainly the simplest thing to do is to modify the jetty.xml file that configures the default server instance and have the DefaultHandler return a page of your choice.  
> 
> There are a couple of ways that I can think of to implement preventing a server from opening its connectors before any contexts are deployed to it but they're mostly ugly solutions. Nor do they prevent the need for the DefaultHandler as the handler-of-last-resort and an informative error page. Consider these scenarios:
> 
> +  there are contexts deployed to the server instance on startup, but none of them are started. In non-osgi jetty the connectors would still open, but the DefaultHandler will handle requests.
> 
> + after the server instance has started, all of the deployed contexts have been stopped, thus requests will fall through to the DefaultHandler.
> 
> Having the server look for bundles  & services to deploy after it has started is also problematic ... I think the solution would entail each of the 4 flavours of deployer (BundleContextProvider, BundleWebAppProvider, ServiceContextProvider, ServiceWebAppProvider) each iterating over all the bundles or services at startup time to see which could be deployed. In the case of the services, its not too inefficient, as they can be filtered by the class type (ContextHandler or WebAppContext). But in the case of the Bundle providers, they have no choice but to each iterate over all of the Bundles installed in the system, which could be very very many.
> 
> Jan

On 2015-06-25 06:37:42 -0400, Magnus Jungsbluth wrote:

> I neither use a jetty.xml not the DefaultHandler, since I configure the Server directly in code. 
> 
> Maybe let's just split the two concerns (correctness w.r.t start order and open ports).
> 
> Concerning correctness (In OSGi it should not matter when a service is registered) and looking for existing services bundles I would propose the following (I am not sitting in front of the Jetty code atm so I might be off at some point):
> - You are already using ServiceTrackerS as far as I remember so you already have all existing services right there and locally cached (no need to query again). The culprit is that they are opened when the Activator starts and events are only processed if the Server service already exist
> - If you open the required ServiceTrackerS at the time of Server discovery you get both for free (events are fired for existing ContextHandler/WebApp services and events for services that come later). The only really difference would by that a more specific OSGi filter would be required (i.e. (&(objectClass=ContextHandler)(managedServer=mySuperServer)) )
> - I am not sure about the case where no "managedServer" property is used (i.e. default). Maybe for this case you still need to open a ServiceTracker with a filter like (!(managedServer=*))
> - I would not handle the BundleTracking part specifically and leave it as is since as far as I remember the osgi.boot bundle registers approbate ContextHandler WebApp... services respectively so this would be solved automatically if the above changes are applied
> 
> I wouldn't expect the inner code to change much but changes around the Activator and the methods where ServerS added/removed events are processed. 
> 
> Does this sound like a viable approach?

On 2015-08-25 15:21:49 -0400, Wei Yan wrote:

> Have the same issue here, server won't deploy the context handler created before server starting.

**Comment by janbartel** [comment]
Fixed for jetty-9.3.11 and above.

As a result of the fix, it will no longer be possible for jetty to generate an error message for a context or webapp deployed as either a bundle or service for which a corresponding jetty server instance cannot be found. Note that it is still valid not to provide the name of a target server instance on the webapp/context bundle or service properties - this will be deployed to the default server instance. This caveat only applies if you deploy to a server instance named "fooServer" and no such server instance exists.
