### ISSUE TITLE
Make simpler to configure the server thread pool for standalone

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2130]
The proposal is to extract the thread pool configuration out of `jetty.xml` and make a small module, say `threadpool.mod` (with associated `jetty-threadpool.xml`), so that module `server.mod` depends on it.

In this way, people that want to change the thread pool implementation only need to override `jetty-threadpool.xml` in `$JETTY_BASE/etc`, rather than copy/pasting the whole `jetty.xml` that also contains the `httpConfig` and a number of other things.

**Comment by WalkerWatch** [comment]
+1 to this. I am all for more compartmentalized configuration options that allows users to plug-and-play to their specific needs.

I imagine we'd just make an ini template for `minThreads`, `maxThreads`, `idleTimeout`, and `detailedDump` so users wouldn't -have- to override `jetty-threadpool.xml` by inserting one in `$JETTY_BASE/etc`, right?

**Comment by sbordet** [comment]
@WalkerWatch correct, both the xml file and the mod file will be split.

**Comment by sbordet** [comment]
Note that this is only required for people that want to have different _implementations_ of the thread pool.
See also #2131.
