### ISSUE TITLE
Introduce a monitored thread pool

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2131]
For benchmarks and JMX reporting it would be good to have a monitored thread pool that reports number of tasks executed, the task latency in the queue, the task execution time, etc.

There are already incarnations of this class in CometD and in jetty-project/jetty-perf, etc. so it's about time that we introduce it in `jetty-util`, also to keep it in sync with the recent `QueuedThreadPool` changes.

**Comment by sbordet** [comment]
Perhaps introduce a `ThreadPool.Monitored` interface and a `MonitoredQueuedThreadPool` subclass.

**Comment by sbordet** [comment]
Implemented in #2260.

**Comment by lubinson** [comment]
@sbordet 

I am recently touch similar monitoring topic, and have two question:
1, is JMX applied to Jetty Http Client?
2, Can I monitor the queue size set by the setMaxRequestsQueuedPerDestination() of Http Client?

The generally idea is to monitor the Http Client to know how busy on this client-server connection. 

Thanks.

**Comment by sbordet** [comment]
> Is JMX applied to Jetty Http Client?

Yes, `HttpClient` is annotated with Jetty's JMX annotations, so when an `MBeanContainer` is added as a bean it will expose `HttpClient` MBeans to the platform `MBeanServer`.
See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.18.v20190429/jetty-client/src/test/java/org/eclipse/jetty/client/jmx/HttpClientJMXTest.java

> Can I monitor the queue size set by the setMaxRequestsQueuedPerDestination() of HttpClient?

Yes. You need to find the destination you are interested in as MBean, and then monitor its attribute `QueuedRequestCount`.
