### ISSUE TITLE
UnixSocketEndPoint should return local and remote SocketAddress

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2134]
Currently, our UnixSocketEndPoint has null's for the local/remote endpoints.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/UnixSocketEndPoint.java#L46-L56

If we can change those methods to return a java.net.SocketAddress then the
existing jnr.unixsocket.UnixSocketChannel can be used to obtain the local/remote UnixSocketAddress (which implements java.net.SocketAddress)

Hopefully these local/remote addresses can then be exposed in the HttpServletRequest local/remote address APIs.

**Comment by sbordet** [comment]
This is trivial to implement, as we have just have to delegate to the `UnixSocketChannel` passed to the constructor.

**Comment by joakime** [comment]
Seems like it, but it has a hitch ...

``` java
    @Override
    public InetSocketAddress getLocalAddress()
    {
        return _channel.getLocalAddress(); // fails, as this is just a SocketAddress, not a InetSocketAddress
    }
```

**Comment by joakime** [comment]
That's because a UnixSocket's `SocketAddress` is a file, and has nothing to do with Inet anything.

**Comment by sbordet** [comment]
Duplicated by #6410.
