### ISSUE TITLE
Android 8.1 needs direct buffers for SSL/TLS to work

### ISSUE THREAD

**Issue by wakkow** [eclipse/jetty.project#2135]
We're using Jetty client 9.2.23 by way of CometD 3.1.3 on Android. I know 9.2 is deprecated but we're stuck with it for now because 9.4 uses Java 8 APIs that aren't available pre-Android N devices, which includes a large number of devices and users. Everything has worked fine except on Android 8.1 / API 27 where Jetty 9.2 does not work with SSL endpoints. When we try to make a POST, it just adds the plain text post body to the request and the server just closes the connection. Here's output from Wireshark with a sample project that just tries to do a simple POST:

![image](https://user-images.githubusercontent.com/492538/35070666-e4e257b4-fb92-11e7-9b28-711e5ce552df.png)

The Android 8.1 changelog has a number of underlying [cypto changes](https://developer.android.com/about/versions/oreo/android-8.1.html#crypto) that may be the real cause. I tested with Jetty 9.4 on Android 8.1 and everything works fine, so something between 9.2 and 9.4 acts differently. I tracked it down to this [commit](https://github.com/eclipse/jetty.project/commit/f6cfe07a69669197accb166fc7359a4e2a810871), specifically setting `_encryptedDirectBuffers` in SslConnection.java to `true`. If I take Jetty 9.2 and just flip that boolean only to true, everything works fine. I'm sure this is just masking the actual problem, but understanding how the SSL wrapping/unwrapping/state and how it's handled in Jetty is beyond me. Would flipping this boolean (or cherry picking that commit back to 9.2) be a reasonable 'fix'? Is there a better way to troubleshoot and find the root cause?

**Comment by joakime** [comment]
The [upcoming changes in the Play Store mandating updated code for Oreo](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html) changes this requirement, no?

We have reports from other developers that Jetty 9.3 and Jetty 9.4 work fine on Android API level 19 and newer.

**Comment by wakkow** [comment]
We are building with and have source compatibility set for 1.8, targeting API 26 but still trying to maintain compatibility back to api 21. The problem is [not everything Java 8 is supported](https://developer.android.com/studio/write/java8-support.html#supported_features) in pre-Nougat devices. For example, in Jetty.java, the use of 'XXX' (capital X's) in SimpleDateFormat works fine Nougat+ but crashes pre-nougat when initializing Jetty with `java.lang.IllegalArgumentException: Unknown pattern character 'X'`. 

I remove that, and it crashes in MappedByteBufferPool due to a lambda using java.util.function.Function. java.util.function's aren't supported pre-Nougat. 

Picking an older 6.3 release (6.3.11), I get crashes in SelectorManager.chooseSelector because SocketAddress.getRemoteAddres() is once again only supported in Nougat+.

We could go through and remove/change all the unsupported things, but that really holds back real Jetty developers like you. We can also fork 9.4 and remove all the unsupported functionality for Android users, but I was hoping there was a simpler solution. Thanks for your quick response, btw!

**Comment by gregw** [comment]
@wakkow I think cherry picking the commit back is a reasonable approach.   Using direct buffers can definitely affect thinks like crypto, specially with the native provider used in Android.

Do you want to make a pull request with that cherry pick and test on the platforms you have available.  Once you are happy with it, we can review and merge back to 9.2 (which while end-of-life still get's some maintenance for clients that also cannot switch).

**Comment by joakime** [comment]
Seems Issue #351 is related to this one.

**Comment by joakime** [comment]
Issue #226 seems related as well.

**Comment by joakime** [comment]
I think this might be a conscrypt bug that using direct buffers would work around.

Possible bug causing this -> https://android.googlesource.com/platform/external/conscrypt/+/e56958e7dea05c1784317f139e2216e2e707d391

**Comment by joakime** [comment]
This was merged in issue #3952.
