### ISSUE TITLE
Master branch deletion fails --add-to-startd=resources on jetty-9.3

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2138]
Report from jetty-users:

java -jar /opt/jetty-distribution-9.3.22.v20171030//start.jar --add-to-startd=http,https,logging,deploy,jsp,jstl,plus,servlets,annotations,ext,resources,logging,requestlog
INFO: ext             initialised in ${jetty.base}/start.d/ext.ini
INFO: logging         initialised in ${jetty.base}/start.d/logging.ini
INFO: resources       initialised in ${jetty.base}/start.d/resources.ini
INFO: server          initialised (transitively) in ${jetty.base}/start.d/server.ini
INFO: http            initialised in ${jetty.base}/start.d/http.ini
INFO: requestlog      initialised in ${jetty.base}/start.d/requestlog.ini
INFO: ssl             initialised (transitively) in ${jetty.base}/start.d/ssl.ini
INFO: https           initialised in ${jetty.base}/start.d/https.ini
INFO: servlets        initialised in ${jetty.base}/start.d/servlets.ini
INFO: deploy          initialised in ${jetty.base}/start.d/deploy.ini
INFO: plus            initialised in ${jetty.base}/start.d/plus.ini
INFO: annotations     initialised in ${jetty.base}/start.d/annotations.ini
INFO: jsp             initialised in ${jetty.base}/start.d/jsp.ini
INFO: jstl            initialised in ${jetty.base}/start.d/jstl.ini
MKDIR: ${jetty.base}/lib
MKDIR: ${jetty.base}/lib/ext
MKDIR: ${jetty.base}/logs
MKDIR: ${jetty.base}/resources
DOWNLOAD: https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=master to ${jetty.base}/etc/keystore
java.io.IOException: URL GET Failure [404/Not Found] on https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=master
        at org.eclipse.jetty.start.fileinits.UriFileInitializer.download(UriFileInitializer.java:79)
        at org.eclipse.jetty.start.fileinits.UriFileInitializer.init(UriFileInitializer.java:60)
        at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:283)
        at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:375)
        at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:239)
        at org.eclipse.jetty.start.Main.start(Main.java:408)
        at org.eclipse.jetty.start.Main.main(Main.java:76)
MKDIR: ${jetty.base}/webapps
WARNING: Failed to process all file resources.
 - [IOException] URL GET Failure [404/Not Found] on https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=master - /opt/jetty/etc/keystore
java.lang.RuntimeException: Failed to process all file resources.
 - [IOException] URL GET Failure [404/Not Found] on https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=master - /opt/jetty/etc/keystore
        at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:394)
        at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:239)
        at org.eclipse.jetty.start.Main.start(Main.java:408)
        at org.eclipse.jetty.start.Main.main(Main.java:76)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information

Confirmed with 9.3, not sure about 9.4 yet.

**Comment by janbartel** [comment]
Seems to be fine in jetty-9.4.

Looks like it affects jetty-9.3 and below.

**Comment by gregw** [comment]
We need to identify the actual resources referenced and then delete everything but those from the master branch. Master can then live on for a few years, but will not be mistaken for the active development branch.

**Comment by jmcc0nn3ll** [comment]
I think the original rationale behind pulling that from master was because we had a keystore in use in the demo ages ago that expired or something.  +1 on smoking everything outside of that file in master though to prevent further confusion.

**Comment by janbartel** [comment]
Here's a list of references in 9.3 to github master:

./jetty-server/src/main/config/modules/ssl.mod
* https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=${jetty.tag.version}|etc/keystore

./jetty-start/src/test/resources/dist-home/modules/ssl.mod
 * https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=${jetty.tag.version}|etc/keystore

./jetty-start/src/test/resources/usecases/logging/modules/logging.mod
* https://raw.githubusercontent.com/jetty-project/logging-modules/master/logback/logback.xml|resources/logback.xml
* https://raw.githubusercontent.com/jetty-project/logging-modules/master/logback/jetty-logging.properties|resources/jetty-logging.properties

**Comment by joakime** [comment]
The last two are on [jetty-project/logging-modules](https://github.com/jetty-project/logging-modules), not [eclipse/jetty.project](https://github.com/eclipse/jetty.project).

**Comment by joakime** [comment]
So far, that just leaves the `keystore`

**Comment by janbartel** [comment]
Yep, and I think I should just change the keystore reference to use the jetty-9.3.x branch instead of referring to master. Keep that file in master as well for older 9.3 releases to use, but going forward it would refer to the 9.3.x branch instead.
