### ISSUE TITLE
Incomplete response & idle timeouts on larger files

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#214]
migrated from Bugzilla [#470360](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470360)
status ASSIGNED severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.2.11_ on platform _Other_
Assigned to: Project Inbox

Original attachment names and IDs:
- _[96k-success.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=254501)_ (ID 254501)
- _[96k-failure.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=254502)_ (ID 254502)

On 2015-06-17 06:57:28 -0400, Jack Patwork wrote:

> Created attachment 254501
> 96k success debug log
> 
> I am getting intermittent incomplete responses that are timing out when serving static resources from jetty. There appears to be a filesize threshold and I can see it more consistently for files > 96k
> 
> See the attached response for two identical local requests.

On 2015-06-17 06:58:24 -0400, Jack Patwork wrote:

> Created attachment 254502
> 96k failure debug log

On 2015-06-17 07:08:36 -0400, Jack Patwork wrote:

> In both requests you can see there two exceptions logged:
> 
> java.io.IOException: Stream closed
>   at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
>   at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:142)
>   at java.io.FilterInputStream.read(FilterInputStream.java:133)
>   at java.io.FilterInputStream.read(FilterInputStream.java:133)
>   at org.eclipse.jetty.server.HttpOutput$InputStreamWritingCB.process(HttpOutput.java:1036)
> ...
> and subsequently:
> 
> java.lang.Throwable
>   at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:202)
>   at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:136)
> ...
> 
> The key difference in the logs from these two requests seems to be in the SelectorManager log lines. In the successful response the Selector loop wakes up and apppears to complete the response. In the failure case this never happens and instead an idle timeout kicks in and closes the connection after 30 seconds.
> 
> It feels like a race condition, could it be related to Bug 468714 - Race in selectorManager updateKey?

On 2015-06-17 20:10:04 -0400, Greg Wilkins wrote:

> Jack,
> 
> the size threshhold is probably just related to how the DefaultServlet chooses to serve your content.  In this can it appears to be using the InputStreamWritingCB, which is used for large content that does not fit into the resource cache (or can't be direct mapped).
> 
> But I need to understand your situation some more.   What is the situation immediately before the exception?  Is the client stalled? was content recently written? 
> 
> More over, it is very strange that the inputstream is seen as closed?  Is the static content being deleted while it is being served (is this windows or unix filesystem?)
> 
> Can you give me the steps necessary to reproduce?

On 2015-06-18 06:28:44 -0400, Jack Patwork wrote:

> This is a unix filesystem (Centos 5.4). Content was indeed recently written, from the clients perspective (a local curl request) it gets part of the response but will stop before the content is completely written and then hang until the timeout closes the connection. The content is actually coming from a classpath resource from inside the same jar file. 
> 
> It does seem strange that the inputstream is closed, I'll try and create a reproducable test case for you.

On 2015-06-18 06:53:23 -0400, Jack Patwork wrote:

> Could this be related to this old bug 364936? 
> 
> Although my application does already have the work around suggested:
> Resource.setDefaultUseCaches(false);

On 2015-06-18 18:50:09 -0400, Greg Wilkins wrote:

> Jack,
> 
> it could perhaps be related to the zip cache, as that is indeed a strange bit of JVM code.  But I can't really say until I know more about how to reproduce this.

**Comment by joakime** [comment]
This is not reproducible on 9.3.14.v20161028 or 9.4.0.v20161208, closing
