### ISSUE TITLE
Hazelcast and Infinispan session data stores don't fetch expired sessions

### ISSUE THREAD

**Issue by rosenqui** [eclipse/jetty.project#2140]
[SessionExpiryTest.zip](https://github.com/eclipse/jetty.project/files/1644306/SessionExpiryTest.zip)

Using Jetty 9.4.8.v20171121 via Maven.

If you use the DefaultSessionCache and set the L1 eviction timer to be shorter than the session expiry timer, evicted sessions get orphaned in the L2 cache.

To reproduce this, set the eviction timer a value between 1 and the session expiry timer so that the session is taken out of the L1 cache and moved to the L2 cache prior to expiring. If the time values are the same you'll usually get the correct behaviour, but you're at the mercy of the original session timeout firing slightly early.

This has been observed with the HazelcastSessionDataStore and I believe the same problem exists in the Infinispan implementation since the code is similar.

I've traced the different behaviour vs. the FileSessionDataStore and the JDBCSessionDataStore to the fact that the Hazelcast/Infinispan implementations only look at the list of candidates supplied to them rather than doing a search. When the eviction timer expires and the session is moved to L2, the timer is not reset, so the session is forgotten. Without searching, doGetExpired() will never return such sessions and they won't be scavenged.

Take note of the data store implementations and see that JDBC and File both search their stores, whereas Hazelcast and Infinispan simply query the IDs in the supplied list of candidates.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/FileSessionDataStore.java#L168
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/JDBCSessionDataStore.java#L811
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStore.java#L123
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-infinispan/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataStore.java#L134

I'm not building Jetty from its source code, so my attached test case doesn't fit into the test-sessions module framework, but hopefully it's enough to illustrate the problem.

**Comment by janbartel** [comment]
I'm not sure about hazelcast, but I think with infinispan you can also configure a timeout to apply to each entry. If you can do that, then the orphaned sessions will be removed. Only downside is that you won't have any sessions listeners called when the session is destroyed. But it can be a workaround while we take a look at the code.

**Comment by janbartel** [comment]
A bit more info:  I believe Hazelcast also offers the ability to set an expiration idle timeout on entries. So as per the case with Infinispan, long expired sessions would be removed from Hazelcast, just with no session destroyed listeners called.

**Comment by janbartel** [comment]
@olamy  yes there are. Look at the InfinispanSessionDataStore and HazelcastSessionDataStore test cases and you'll see some tests that are overridden to do nothing with the comment that they are known not to work with the current implementations.

**Comment by janbartel** [comment]
Checked in for jetty-9.4.17 and beyond.
