### ISSUE TITLE
Enabled h2, http/1.1 + https failed with invalid preface

### ISSUE THREAD

**Issue by tianchen047** [eclipse/jetty.project#2145]
I'm using jetty-distribution-9.4.7.v20170914, turn on alpn, h2, https, http/1.1 and some other...
h2 response well. http1.1 failed with invalid preface.
It seems defaultProtocol in newConnection function failed to check http/1.1
     negotiated.contains(HttpVersion.HTTP_1_1.asString())
all negotiated values are lower case, defaultProtocol will be set to h2.

the solution with set 
     jetty.alpn.defaultProtocol=http/1.1
will fix this problem

**Comment by sbordet** [comment]
The faulty code is in `NegotiatingServerConnectionFactory` where indeed there is a case mismatch with `contains()`.
