### ISSUE TITLE
Upload a file of size greater than 2 GB failed with an Idle timeout error

### ISSUE THREAD

**Issue by AjithAnbu** [eclipse/jetty.project#2146]
I have built the jetty proxy server with the help of Jetty ProxyServlet. The upload working smooth with small files. But got an error as below when I tried to upload a 1GB file.

" onProxyResponseFailure Total timeout 60000 ms elapsed "

Not sure why the error thrown, whereas the client connection having 'keep-alive: true'

After setting the timeout parameter to -1, the above error resolved.
proxyServletHolder.setInitParameter("timeout", "-1"); 

But now when I try to upload a file of size greater than 2 GB (say 3 GB) the upload failed with an error,

" onProxyResponseFailure Idle timeout 30000 ms "

Noticed that the contentLength in the HttpServletRequest is in negative value 'contentLength=-2147483648'

**Comment by joakime** [comment]
We'd like to replicate this.

What are you using for your web client?
What kind of request are you issuing with this client? (HTTP/1, HTTP/2, POST, PUT, etc.  Anything you can tell us might prove useful)
What is your jetty proxy configuration?
Have you modified the jetty proxy in any way?

**Comment by AjithAnbu** [comment]
I am using curl tool for my web client with the HTTP/1.1 PUT request.

I have not modified jetty proxy and the configuration is as follows :
IDLE_TIMEOUT_DEFAULT = 30000;
TIMEOUT_DEFAULT = -1;

**Comment by sbordet** [comment]
What Jetty version ?

**Comment by AjithAnbu** [comment]
jettyVersion = "9.4.8.v20171121"

**Comment by sbordet** [comment]
@AjithAnbu can you provide the proxy DEBUG logs ?

**Comment by joakime** [comment]
Closing due to lack of response.
