### ISSUE TITLE
Remove compact3 build from Jetty 10.x ?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2147]
Do we need to keep the compact3 build around for Jetty 10.x ?
Not sure who is using that?  We don't deploy it to maven central.
Consumers of that build have to build/use it themselves anyway.

**Comment by jmcc0nn3ll** [comment]
I think we could get away with this, should we need to wire something like this back up on 10.x in the future it will likely be in the context of jdk modules which changes everything anyway..

**Comment by ViToni** [comment]
I'm using jetty (client) on "small" devices which don't have always full blown JVM and support at most compact3. It would be nice to keep this in mind. Maybe the non-compact3 profile stuff (if any) could be made optional or "on-top".

**Comment by joakime** [comment]
Closing as compact3 was removed in 57866ba1bbbc8fe9046d23931705d7a99c923d5d

**Comment by JochenHiller** [comment]
We are using also the Jetty-9.x versions (Client and server) on a compact3 profile environment (Azul JVM). This might stop us from using Jetty 10.x if really Full-JRE features will be introduced.

**Comment by joakime** [comment]
In today's reality, Java 9+ has hit, and OpenJDK is now the norm for Java.

That means the idea of a Java Runtime Environment has changed as well.
A JRE is no longer a concept that ships, instead each user and vendor is free to define their own runtime environment (see jlink).
Compact 3 is one of countless variations to this idea.
The meaning of "Compact 3" as defined in JEP 161 hasn't been updated since Java 8, and has many vague / ill defined / muddy parts that the OpenJDK 9+ vendors have discovered.  So much so that "Compact 3" isn't even standardized across vendors of OpenJDK since the release of OpenJDK 9 (with variations continuing to get larger and more pronounced as the JDK levels seem to increase).

We also removed the compact3 aggregate build as it had exceedingly low usage (lower then even CGI support or HTTP/0.9).

All this removal means is that we are not endorsing a specific runtime configuration over another, and don't have the time or resources to maintain (or test, which that build never had!) the compact3 build on all OpenJDK variations.
You are free to build it yourself under compact 3, if you find issues, you can let us know and we'll likely make adjustments to allow it to work.  
If you want to maintain that build on github, chances are we would collaborate with you (time permitting).   
Wouldn't be the first time we've added Azul JVM specific fixes to Jetty.

We also encourage Pull Requests with fixes for specific runtime configurations as well.

**Comment by JochenHiller** [comment]
Thanks Joakim for detailed answer.

I agree that Java 9+ is out some time, and Java 8 is in maintenance now.

If you have a fleet of Embedded Devices running JavaSE Embedded 8 in the field it is a major effort to update JVMs to recent one (if it is even possible, when running on ARM, MIPS, x86). That is the reason why we are using Azul Java8 Embedded with maintenance support for some more years.

It is fine for us to build a compact 3 version for ourselves.

The issue is that developers tend to use then full JRE set of APIs so it will get more difficult over time to restrict it to compact 3 packages (this makes even sense for Java 9+ as the number of referred modules might be less as well).

Thanks for offering to provide issues when we find incompatibilities. Lets see what developers are doing ;-)

**Comment by sbordet** [comment]
@JochenHiller if you are going to stick with Java 8 for a while, you won't be able to move to Jetty 10 that requires Java 11.
Could be that by the time you switch to Java 11, you may find a custom JRE image built with `jlink` better than a compact3 profile.

**Comment by JochenHiller** [comment]
Thanks @sbordet for the hint that Jetty 10.x does require Java 11.
Then compact 3 profile support in Jetty 10 is an obsolete question ;-)

About `jlink`: we can run our solution on Java 11 as well, and we saw a decrease of runtime size from about 34 MB down to 31 MB. Unfortunately the startup times on an embedded device are longer (10-20%) than on Java 8, so we first have to check for reasons.

But as said, to roll out a new JVM to a fleet of devices is not as easy.

But thanks again for pointing us to Java 11 dependency.
