### ISSUE TITLE
Limit BufferUtil.toDetailString() raw character display to USASCII 7-bit printable characters

### ISSUE THREAD

**Issue by mpapirkovskyy** [eclipse/jetty.project#2148]
Pretty annoying thing when debugging websocket frames.
Frames often have 0x7F byte for large unmasked messages.
Logging output not only lacks this byte, but also has other output damaged.
Confuses a lot.

**Comment by joakime** [comment]
For TEXT based websocket messages (be it in 1 frame or many), all bytes must conform to UTF-8 encoding rules.

See: https://tools.ietf.org/html/rfc6455#section-5.6

Note: this UTF-8 encoding rule also applies to optional reason phrase in CLOSE frames.

Our WebSocket implementation does not use `BufferUtil.appendContentChar` as that cannot handle WebSocket frames that are split in the middle of a UTF-8 codepoint.

If you have a demonstration of a sequence of bytes that fail our UTF-8 handling, please let us know in this issue.

**Comment by joakime** [comment]
When you say "debugging websocket frames" are you talking about your own debug session in your IDE? or something else?

**Comment by mpapirkovskyy** [comment]
@joakime I mentioned logging output only. Used from WriteFlusher:
https://github.com/eclipse/jetty.project/blob/21365234f8cf036829f7a03e5c7b89a9572444f9/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java#L313-L316

**Comment by joakime** [comment]
Ah `toDetailString()` ... checking ...

**Comment by joakime** [comment]
Proposed fix exists at PR #2149 - pending review, it will be merged back into jetty-9.4.x and forward.
