### ISSUE TITLE
Produce jetty-home-source artifacts for Eclipse Jetty source jars

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2152]
Update the assembly plugin to produce a new `<classifier>src</classifier>` object that has a similar `${jetty.home}/lib/` structure, but with `-source.jars` only.

Various tool implementors have expressed an interest in this.

**Comment by jmcc0nn3ll** [comment]
@gregw you can check out if this fits the bill for what you need, only went into the lib dir but if need others we can wire those up, this should take care of the lion share of normal cases though

**Comment by jmcc0nn3ll** [comment]
@gregw we don't need this anymore, right?  If not we can close this and resolve the PR I had

**Comment by gregw** [comment]
The original requirement for this has changed to need `-src.jar` extension rather than `-sources.jar`.
While I'm loath to change this when it has already been released, I think it can be done as few will have seen/used it yet.

**Comment by olamy** [comment]
lol :-)

**Comment by joakime** [comment]
"src" is not a common classifier on maven central.
Its "sources" for a reason. ;-)

**Comment by olamy** [comment]
doh we have to rename all the jars included in jetty-home-9.4.10-SNAPSHOT-sources.zip?

**Comment by gregw** [comment]
Actually,  let's leave it as is an I'll rename as I import (which is done by script anyway).
However, I still need the sources jar for the servlet API added

**Comment by olamy** [comment]
@gregw done.
