### ISSUE TITLE
ALPN Chapter needs more information about Java 9 and OSGi usages

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2154]
While researching Issue #2153 it became clear that we are missing two topics in our ALPN documentation.

1. How to use ALPN in Java 9
2. Why the Apache Aries SPI Fly is needed for OSGi usage.

The Apache Aries SPI Fly is a more general concern for OSGi and ServiceLoader so it could probably live somewhere else, with the ALPN documentation referencing it.

**Comment by WalkerWatch** [comment]
The first part of this was covered by @sbordet in https://github.com/eclipse/jetty.project/commit/1466aa1f750528f481496a5686f8b3d5192f2d42 as part of 2107. We do cover the use of Aries in [the OSGi](https://github.com/eclipse/jetty.project/blame/jetty-9.4.x/jetty-documentation/src/main/asciidoc/development/frameworks/osgi.adoc#L877) but only as a brief snippet that identifies it as the reference implementation for the Service Loader Mediator. How much do you think this should be expanded?

**Comment by joakime** [comment]
We have a mention in the ALPN side documentation mentioning the need for a specific artifact.  Perhaps that section can also have a link to the OSGi documentation about the project Aries requirement. 

Also, see the Aries SPI Fly details in #2153 (if you think any of it is useful)
