### ISSUE TITLE
NoSqlSessionManager needs cap for number of sessions in _sessions cache

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#216]
migrated from Bugzilla [#471502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=471502)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.3.0* on platform *PC*
Assigned to: Jan Bartel

On 2015-06-30 20:38:42 -0400, Christopher Exell wrote:

> We're running into a bug in production where we can exhaust the available memory when there are a large number of sessions bound to a single jetty container which is using mongo session storage. 
> 
> 
> In the NoSqlSessionManager, _sessions is a ConcurrentHashMap, but it might be better if it was some type of capped LRU cache. That way users can limit the number of items that the cache will store in order to limit memory usage.
> 
> I don't see anything in use in the jetty project right now that supports LRU caching, but I may be missing it. Guava has one that seems to fit this nicely
> 
> https://code.google.com/p/guava-libraries/wiki/CachesExplained
> 
> 
> Happy to submit a github pull request with the changes if I can use Guava or someone can point out the preferred way to build an LRU for jetty.
> 
> 
> Also wondering if at the same time it would make sense to add the ability to disable caching, I don't see a way to avoid it with the current code.

On 2015-06-30 21:36:39 -0400, Jan Bartel wrote:

> Hi Christopher,
> 
> The purpose of the nosql session manager is to permit (persistent) session clustering. This means that a session cannot be stored in the memory of a single jetty instance. It would be counterproductive and confusing if some sessions were stored into the cluster whilst others sessions were local to a single jetty instance.
> 
> I think you need to take steps to a) see if you can reduce the amount of data stored in sessions so only the essentials are stored;  b) increase the amount of memory available ;c) check if your sessions should be expired sooner d) be really happy that you have such a popular application ;)
> 
> Jan

On 2015-06-30 22:36:03 -0400, Jan Bartel wrote:

> Oops, sorry, just realized what you meant: you want to keep sessions in jetty instance, but evict the LRU when you need to create a new session or load an existing session from the cluster.  Could maybe work. Things to be wary of would be trying to evict a session that is the lru candidate, but is in fact currently in use; bouncing backwards and forwards evicting then loading straight back in a session; not having any sessions that you can evict in order to load a session or create a session; multiple threads concurrently trying to load in the same session and both evicting a session to free up 2 spaces when only 1 will succeed in putting the session into memory. Will also make the scavenging and other invalidation logic much more complicated.
> 
> I still think you're much better off following the strategy I proposed. 
> 
> That said, if you come up with the code and a thorough set of tests for it then I'll sure take a look at it.
> 
> Jan

On 2015-07-03 03:21:35 -0400, Jan Bartel wrote:

> Changing to an enhancement.

**Comment by janbartel** [comment]
I'm marking this as closed, as I believe the concerns are addressed by the new session management architecture in jetty-9.4.x with the mechanisms that allow you to control the residency of Session objects in memory:  you can evict a Session after it has not been accessed for a configurable length of time, or you can evict a Session once all concurrent requests have exited the Session.
