### ISSUE TITLE
Contribute Jetty 9.4.8 to Photon.0.M5

### ISSUE THREAD

**Issue by nickboldt** [eclipse/jetty.project#2162]
Could the latest Jetty 9.4.8 be contributed to Photon.0.M5?

http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.4.8.v20171121

Related: https://bugs.eclipse.org/bugs/show_bug.cgi?id=530458

**Comment by joakime** [comment]
We do not participate in the Eclipse release train.
We make P2 repositories available when people ask, but generally we do not do this for every release.

**Comment by joakime** [comment]
@akurtakov usually pings us for specific versions of Jetty to make into P2 repositories.

Example:

* Issue #1834 - jetty p2 for jetty 9.4.7
* Issue #1587 - please stage p2 repository

**Comment by WalkerWatch** [comment]
For what it's worth, 9.4.8.v20171121  did have a P2 build. Zip file can be downloaded [here](http://www.eclipse.org/downloads/download.php?file=/jetty/updates/jetty-bundles-9.x/9.4.8.v20171121/Jetty-bundles-repository-9.4.8.v20171121.zip).

**Comment by nickboldt** [comment]
Yeah, Spoke with @akurtakov after opening this and I think the solution is to make sure the WTP update site includes the jetty bundles not already included via Platform's update site. Sorry for the churn - didn't realize your process was more in parallel to the simrel, than part of it directly. :)
