### ISSUE TITLE
Consider removing QueuedThreadPool.interruptThread(String id)

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2163]
The existing `QueuedThreadPool.interruptThread()` is not used by Jetty anywhere.
We should remove it, as it just encourages bad behavior.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L729-L745

**Comment by joakime** [comment]
We should deprecate this QTP method in `jetty-9.4.x` and remove it in `jetty-10.0.x`

**Comment by sbordet** [comment]
The method is retained as a managed operation.
