### ISSUE TITLE
Ensure all jetty modules that use ServiceLoader have correct OSGi manifest headers

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2164]
Several jetty modules use the ServiceLoader these days, but they have not been updated to include the necessary manifest headers to ensure that the ServiceLoader will work in osgi.

Modules found so far that need attention:
* jetty-xml
* jetty-util
* jetty-spring

**Comment by janbartel** [comment]
Depends on #2166 because spifly hardcodes use of asm 4 opcode, but the use of ServiceLoader in a static initializer requires asm 5 opcode.

**Comment by janbartel** [comment]
Merged to jetty-9.4 and above.

**Comment by akurtakov** [comment]
https://github.com/eclipse/jetty.project/pull/1365

**Comment by akurtakov** [comment]
If we can get a release with this issue fixed it would allow the release for Java 10 comptability to ship compatible Jetty too.

**Comment by mbooth101** [comment]
@akurtakov I submitted a PR to fix this for Eclipse's use-case. See #2377
