### ISSUE TITLE
Deprecated GzipFilter broke Gzip Request processing in other projects

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#217]
migrated from Bugzilla [#471577](https://bugs.eclipse.org/bugs/show_bug.cgi?id=471577)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.3.0* on platform *All*
Assigned to: Greg Wilkins

On 2015-07-01 08:38:06 -0400, Joakim Erdfelt wrote:

> Our deprecation of GzipFilter (in favor of GzipHandler) has broken other projects integration with us.
> 
> Namely Dropwizard extended our GzipFilter to add handling for Gzip compressed request payloads.
> 
> Should we add Gzip compressed request payload processing to GzipHandler?
> 
> https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jetty/src/main/java/io/dropwizard/jetty/BiDiGzipFilter.java

On 2015-07-01 08:43:18 -0400, Joakim Erdfelt wrote:

> Filed related bug at Dropwizard side.
> 
> https://github.com/dropwizard/dropwizard/issues/1147

On 2015-07-01 17:43:42 -0400, Greg Wilkins wrote:

> Gzip handling has been moved to a new interceptor architecture so that it works correctly with all async IO modes.
> 
> There is no similar interceptor yet on the input side.
> 
> I'll look at making this interception point in the near future, but it would be good to have somebody from the dropwizard team to collaborate with when creating a gzip input handler

**Comment by joakime** [comment]
Jetty 9.3.7 and onwards has warning message on use of deprecated filters.

eg:

```
2016-03-02 09:11:55.196:WARN:oeju.DeprecationWarning:main: Using @Deprecated Class org.eclipse.jetty.servlets.MultiPartFilter
2016-03-02 09:11:55.201:WARN:oeju.DeprecationWarning:main: Using @Deprecated Class org.eclipse.jetty.servlets.GzipFilter
```
