### ISSUE TITLE
Move server classes and dependencies out from websocket-core

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2173]
Currently, `websocket-core` has server classes and dependencies.

These are not appropriate for `websocket-core` as they contaminate the dependency tree for both websocket clients.

These classes, test cases, and dependencies should be moved out of `websocket-core`

**Comment by gregw** [comment]
I think we are OK with the current package structure? Can this be closed?

**Comment by sbordet** [comment]
I reported that some *.internal.* classes were present in signatures of public classes.

Not sure this is the right issue though. @lachlan-roberts?
