### ISSUE TITLE
Update tmp directory configuration documentation

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2178]
tmp directory configuration is very old school: https://www.eclipse.org/jetty/documentation/9.4.x/ref-temporary-directories.html

it needs to be modernized to at least say how you would do it with a modules based deployment.

**Comment by janbartel** [comment]
@WalkerWatch  the only thing to update on the tmp dir documentation is that you could mention the 2 ways of setting the java.io.tmpdir system property:  either on the command line, or use the jvm module and add it to the start.d/jvm.ini file instead. The latter approach is only effective if you have jetty exec a new instance to run (ensure --exec is uncommented in jvm.ini).
