### ISSUE TITLE
Deprecate jetty-9.2 

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2179]
Chris, can we make jetty-9.2 deprecated, as there is no reason anyone on 9.2 can't migrate directly to 9.3.

**Comment by joakime** [comment]
The biggest reason for 9.2 usage (server + http-client + websocket-client) is still Android.

**Comment by sbordet** [comment]
And for people still on JDK 7.

**Comment by WalkerWatch** [comment]
@janbartel @joakime Should we send out a mailing about it being "Officially" deprecated/EOL, or maybe just include it in the next patch notes? It's easy enough to change in the documentation but I want to make sure we are giving folks proper notice I guess.

**Comment by jmcc0nn3ll** [comment]
next patch notes should be fine for now, but it should be on the jetty version box on the site asap, then we just refer to that

**Comment by jmcc0nn3ll** [comment]
actually, we should just do what we did last time with Jetty 7 and Jetty 8

https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html

**Comment by WalkerWatch** [comment]
Official deprecation notice was released. 

https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00116.html
