### ISSUE TITLE
Resource implementations should be immutable

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#218]
migrated from Bugzilla [#472124](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472124)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Project Inbox

On 2015-07-08 02:11:31 -0400, Greg Wilkins wrote:

> Currently the UrlResource classes are internally stateful.  This is inefficient and can result in problems like 471985
> 
> Resource is currently like the URL class when it should be more like the URI class!

**Comment by sbordet** [comment]
Closing in favor of #2386.
