### ISSUE TITLE
Jetty plugin install in Oxygen 

### ISSUE THREAD

**Issue by balabesimple** [eclipse/jetty.project#2180]
I couldn't install jetty plugin bundle in oxygen. Any assist in below issue?
Cannot complete the install because one or more required items could not be found.
  Software being installed: Jetty - Bundles: all the jetty bundles 9.4.8.201711291701 (org.eclipse.jetty.bundles.f.feature.group 9.4.8.201711291701)
  Missing requirement: Jetty :: Apache JSP Implementation 9.4.8.v20171121 (org.eclipse.jetty.apache-jsp 9.4.8.v20171121) requires 'package org.apache.jasper.servlet [8.5.0,9.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Jetty - Bundles: all the jetty bundles 9.4.8.201711291701 (org.eclipse.jetty.bundles.f.feature.group 9.4.8.201711291701)
    To: org.eclipse.jetty.apache-jsp [9.4.8.v20171121]

I tried with this Update site : http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/

**Comment by janbartel** [comment]
@balabesimple  our jetty p2 repository only contains jetty jars. We do not redistribute bundles for 3rd party dependencies such as the jsp implementation, which we say clearly on our osgi documentation page here: https://www.eclipse.org/jetty/documentation/9.4.8.v20171121/framework-jetty-osgi.html#_osgi_containers. 

Follow the instructions on the page to manually pre-install into your eclipse the necessary bundles that can be found in the jetty distro, or on maven.

**Comment by simonjhy** [comment]
the link is invalid. Can you give us a correct url? Thanks

**Comment by olamy** [comment]
look https://www.eclipse.org/jetty/documentation/9.4.x/framework-jetty-osgi.html#_osgi_containers
