### ISSUE TITLE
onWebSocketText invoked after onWebSocketClose

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2182]
Version 9.4.8.v20171121

I am running across intermittent failures where `onWebSocketError` is invoked followed by `onWebSocketClose` followed by `onWebSocketText`. Unfortunately, I do not have a reproducible testcase but my log files hint at what is going on:

```
03:29:27.754 [HttpClient@1724256292-scheduler] DEBUG f.b.i.BinanceOrderStream$WebSocketListener.onWebSocketError - this: foobar.binance.internal.BinanceOrderStream$WebSocketListener@42120c52
03:29:27.763 [HttpClient@1724256292-scheduler] DEBUG f.b.i.BinanceOrderStream$WebSocketListener.onWebSocketClose - this: foobar.binance.internal.BinanceOrderStream$WebSocketListener@42120c52
03:29:28.167 [WebSocketClient@1724256292-196] DEBUG f.b.i.BinanceOrderStream$WebSocketListener.onWebSocketText - this: foobar.binance.internal.BinanceOrderStream$WebSocketListener@42120c52, session: null
```

Notice that the websocket is being closed by a thread called `HttpClient@1724256292-scheduler` whereas normal websocket communication is coming from the `WebSocketClient@1724256292-196` thread. My theory is that some sort of scheduled event (timeout?) is taking place immediately before a message is completed/received by the websocket.

**Expected behavior**: no events should occur after `onWebSocketClose `, certainly not `onWebSocketText` :)

This issue may be related to https://github.com/eclipse/jetty.project/issues/2175

**Comment by joakime** [comment]
It is possible for Streaming based message handling to receive their events out of order or even after other terminal events (such as close).

This is because each new stream results in a dispatch to a new thread, and that thread handling can easily cause things to arrive out of order.

If order is important to you, don't use Streaming based message handling.

**Comment by cowwoc** [comment]
@joakime Excuse my ignorance but where do I find examples or documentation for non-streaming based message handling? Aren't all WebSocket clients streaming-based?

**Comment by joakime** [comment]
There's a few different ways to handle the messaging in websocket.

- **Frame based** - this is the raw websocket frame payload bytes delivered as a ByteBuffer to the endpoint that wants it.
- **Partial based** - this is the data type specific partial bytes.
  - for BINARY its equivalent to raw websocket frame payload byte
  - for TEXT its the UTF-8 partial string (which might include the now complete UTF-8 code-point from a previous partial, or leave off the incomplete UTF-8 code-point from the end of the current partial)
- **Whole message based** - _(This is the most common technique)_ The entire message is collected and delivered as ByteBuffer or String to the endpoint that wants it.
- **Streaming based** - each message is delivered as a InputStream for BINARY or Reader for TEXT to the endpoint that wants it.

For Jetty Native WebSockets you have the following options

Mode | Code
------ | ------
Frame | [WebSocketFrameListener](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/WebSocketFrameListener.html)  or [`@OnWebSocketFrame`](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/annotations/OnWebSocketFrame.html) with type [`Frame`](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/extensions/Frame.html)
Partial | [WebSocketPartialListener](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/WebSocketPartialListener.html) (not supported by annotations)
Whole | [WebSocketListener](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/WebSocketListener.html) or [`@OnWebSocketMessage`](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.html) with types (String) for TEXT, or types (byte[] buffer, int offset, int length) for BINARY
Streaming | [`@OnWebSocketMessage`](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.html) with types Reader for TEXT or InputStreamfor BINARY

For JSR356 (javax.websocket) WebSockets you have the following options

Mode | Code
------ | ------
Frame | _(not available in JSR356)_
Partial | Using [`@OnMessage`](https://docs.oracle.com/javaee/7/api/javax/websocket/OnMessage.html) with types (String message, boolean isLast) for TEXT or (ByteBuffer payload, boolean isLast) for BINARY or (byte[] buffer, boolean isLast) for BINARY.   Or using [`javax.websocket.MessageHandler.Partial`](https://docs.oracle.com/javaee/7/api/javax/websocket/MessageHandler.Partial.html) implementation with `Session.addMessageHandler()`
Whole | Using [`@OnMessage`](https://docs.oracle.com/javaee/7/api/javax/websocket/OnMessage.html) with types (String message) for TEXT or (ByteBuffer payload) for BINARY or (byte[] buffer) for BINARY.   Or using [`javax.websocket.MessageHandler.Whole`](https://docs.oracle.com/javaee/7/api/javax/websocket/MessageHandler.Whole.html) implementation that has a datatype declared with `Decoder.Text` or `Decoder.Binary` with `Session.addMessageHandler()`
Streaming | Using [`@OnMessage`](https://docs.oracle.com/javaee/7/api/javax/websocket/OnMessage.html) with types (Reader reader) for TEXT or (InputStream stream) for BINARY.   Or using [`javax.websocket.MessageHandler.Whole`](https://docs.oracle.com/javaee/7/api/javax/websocket/MessageHandler.Whole.html) implementation that has a datatype declared with `Decoder.TextStream` or `Decoder.BinaryStream` with `Session.addMessageHandler()`

The streaming based versions are the only ones that have delivery order behavioral differences.

**Comment by joakime** [comment]
Including @WalkerWatch about documentation concerns.

**Comment by joakime** [comment]
@cowwoc Streaming based handling is common for those that only have 1 giant message (like video conferencing suites or gaming).   If you have multiple messages, and delivery order is important, use whole message or partial message handling.

**Comment by cowwoc** [comment]
@joakime My code uses `org.eclipse.jetty.websocket.client.WebSocketClient` to with a class that extends `org.eclipse.jetty.websocket.api.WebSocketAdapter` which implements `org.eclipse.jetty.websocket.api.WebSocketListener`. According to the above documentation, doesn't this qualify as `Whole` mode with consistent delivery order?

**Comment by joakime** [comment]
Yes.  Using `WebSocketListener` is whole message delivery, not streaming.

The fact that you see events from two different threads is not troublesome.
Are you using [`Session.suspend()`](https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/websocket/api/Session.html#suspend--) in your project perhaps?

**Comment by cowwoc** [comment]
No, I am not. I just connect to a websocket and `session.close()` if an error occurs.

**Comment by cowwoc** [comment]
I think I figured out my mistake. I was connecting the same websocket object/listener to multiple URIs. I assume that I only needed a single instance but thinking about it now if one stores the `session` object then you really must keep a separate listener per connection. Sorry for the false alarm.

Should I close this issue or do you want to keep it open for the documentation bit?

**Comment by joakime** [comment]
Yes. if you are using WebSocketAdapter, that is per session/connection usage type.

There are ways, using the `@OnWebSocketMessage` annotation to have a single endpoint instance for multiple sessions/connections.

That method would need to declare that it's interested in the Session.

eg:

``` java
@OnWebSocketMessage
public void onMessage(Session session, String textMessage)
{
   // process this message, within the scope of this session.
}
```

No need to keep this open for documentation.
Feel free to close it if you want.

**Comment by cowwoc** [comment]
Is there a way to get the session in `onMessage` using `WebSocketListener`? Or does this require the use of annotations?

**Comment by joakime** [comment]
No.  The `WebSocketListener` has a fixed interface that isn't designed for singleton use.

Note that annotations use in websocket do not require annotation or bytecode scanning to function.
