### ISSUE TITLE
Include DispatcherType.FORWARD in default WebSocketUpgradeFilter declaration

### ISSUE THREAD

**Issue by CLovinr** [eclipse/jetty.project#2183]
https://github.com/eclipse/jetty.project/blob/ec769390b8506a136981a8775dedf915444e38e2/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeFilter.java#L81

Could you change the code like this :

> EnumSet<DispatcherType> dispatcherTypes = EnumSet.of(DispatcherType.REQUEST,**_DispatcherType.FORWARD_**);

so that websocket can be also available by this way:(this work on tomcat but not jetty)

> request.getRequestDispatcher("/constWebsocketPath").forward(request,response);
it's useful for dynamic coding

**Comment by joakime** [comment]
A websocket upgrade request cannot be upgraded from a forwarded dispatch.
That's too late in the process.

Anyway, If you want it to be a specific way, declare the `WebSocketUpgradeFilter` manually in your `WEB-INF/web.xml` and Jetty should use that one.

**Comment by joakime** [comment]
Closing.
`WEB-INF/web.xml` configuration option exists.
Not adding DispatcherType.FORWARD to default behavior.
