### ISSUE TITLE
Update build to perform license check on documentation too

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2185]
Currently the license check plugin in the main pom only validates `**/*.java`.
We should split up the execution (and configuration).
So that we have 1 execution configuration for `**/*.java` and another execution for `**/*.adoc`.

The split is likely going to be needed to verify the slightly different header format that the `**/*.adoc` files use.

**Comment by joakime** [comment]
This will have to be done from Jetty 9.2.x on up through 10.0.x

**Comment by joakime** [comment]
Can we close this now?  Is it rolled out to all of the active branches?

**Comment by WalkerWatch** [comment]
Joakim - it is. I meant to close it yesterday!
