### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by janacm** [eclipse/jetty.project#2194]
All of the links to the annotations on this page: http://www.eclipse.org/jetty/documentation/9.3.x/jetty-websocket-api-annotations.html are broken. 

Please let me know where to find the correct links and I would be happy to fix them myself.

**Comment by WalkerWatch** [comment]
I fixed this for the 9.4.x branch in #1858 and forgot to do it in 9.3.x. Committed a change for this and updated the nightly Jenkins process. You'll see it after it builds overnight. Alternately, you can use the [documentation for the latest 9.3.x release](https://www.eclipse.org/jetty/documentation/9.3.22.v20171030/). As a note, we took the link off the website for the nightly 9.3.x builds so time ago but I forgot to remove it from the site script. I don't have immediate plans to remove it but I would not count on it being around long term. Far better to use documentation for the associated release.
