### ISSUE TITLE
Add Jetty Start Timestamps for general module / ini usage

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2196]
In light of Issue #2195 it would be keen to add some timestamp formats (including ISO8601) for "when jetty start.jar was executed" to the default list of system properties that can be used from the module system.

Proposal:
Using time/date of the following:
GMT: Wednesday, February 14, 2018 at 16:15:56
Local TimeZone being [CST(GMT -6)](https://www.timeanddate.com/worldclock/usa/austin)

System Property | Pattern | Example
----------------- | ------- | ----------
`jetty.start.timestamp` | `yyyy-MM-dd'T'HH.mm'Z'` | `2018-02-14T16.15Z`
`jetty.start.timestamp.iso8601.strict` | `yyyy-MM-dd'T'HH:mm'Z'` | `2018-02-14T16:15Z`
`jetty.start.timestamp.iso8601.date` | `yyyy-MM-dd` | `2018-02-14`
`jetty.start.timestamp.iso8601.time` | `HH.mm'Z'` | `16.15Z`
`jetty.start.timestamp.local` | `yyyy-MM-dd'T'HH.mm` | `2018-02-14T10.15`
`jetty.start.timestamp.local.date` | `yyyy-MM-dd` | `2018-02-14`
`jetty.start.timestamp.local.time` | `HH.mm` | `10.15`

Note: the ISO8601 format isn't strict (it uses `.` character instead of the filesystem problematic `:` character) unless you use the `.strict` suffix (which uses the `:` properly)

This proposal is not for a "live timestamp" that constantly changes every time its requested, this is for a statically assigned timestamp for when start.jar itself starts.  Each request for the above property expansion return the static timestamp in the format desired.

An alternative to this approach is to let the expansion parameter include the format desired.
Example:  `${jetty.start.timestamp|yyyy-MM-dd}`
This would have a few limitations (such as not being able to use "}" sanely inside of the format), it could be a more general purpose solution for the above.

**Comment by sbordet** [comment]
Or perhaps a start/stop listener to server ? Don't we already have lifecycle listeners ? With a listener, we won't have formatting issues and won't pollute system properties with a gazillion versions of the same information.

**Comment by joakime** [comment]
Don't get hung up the system property approach (its just a convenient way to talk/discuss about it).

This can easily be dynamically expanded based on the name and never exist as a real system property.
The implementation in this approach would be self contained in the jetty-start [`Props.expand()`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-start/src/main/java/org/eclipse/jetty/start/Props.java#L188) by having these names be special to the expansion routines only.
However, going this dynamic way would not let our XML use these properties too.

This proposal is for start.jar start timestamp, not the server, that already has mechanisms.

As for usage, this would be useful for JVM setup, especially around `--exec` usage.

What if you wanted to use this timestamp JVM setup (of gc logs)? 
See issue #2195 for example where this could be used.

or Logging setup?
```
-Djava.util.logging.config.file=resources/${deploy.env}/logging.properties
-Dcustom.logging.file.prefix=logging-${deploy.env}-${jetty.start.timestamp.local.date}
```

**Comment by gregw** [comment]
I'm not sure I can see the use-case for these, even in the context of #2195 ? Why would a user need to specify the start time in a --exec argument?

Even if needed, it feels like overkill to have all the formats.  Just have a single one in iso8601.strict

**Comment by joakime** [comment]
I'm keen on implementing this for gclogs example (but only contained in Props object during start.jar, not as formal System properties)

Example.

```
-Xloggc:${jetty.base}/logs/gc-${jetty.start.timestamp.local}.log
```
