### ISSUE TITLE
Use GlobalWebAppConfigBinding rather than special methods on DeploymentManager/WebAppProvider

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2203]
Currently the DeploymentManager has a setter to allow context attributes to be set on every context that it deploys.  Additionally the WebAppProvider has setters that mirror a few of the setters on WebAppContext eg extract wars, parent loader priority, defaults descriptor.

It may be less brittle and more productive to allow the DeploymentManager and/or WebAppProvider to specify the name of a generic context xml file that will be applied to each context deployed instead.  Such a generic context xml file would be applied before any specific context xml file.  The context xml file could either configure a ContextHandler, or a WebAppContext - it would be up to the user to determine which is appropriate for their setup.

An example of this in the jetty-deployer.xml might look something like:

```xml
<Set name="contextXml"><Property name="jetty.base"/>/etc/generic.xml</Set>
```

Thoughts?

**Comment by joakime** [comment]
So would this initialize first, and then the actual webapp specific configure would overlay it?

Some thoughts...

How do we deal with `${jetty.base}/webapps/<context>.xml` that has a XML id declared? (eg: `<Configure id="foo">` )

We'll have to ensure that `WebAppContext` never has mandatory constructor based configuration from this point forward. (just thinking of the upheaval that the `Server` object went through with users)

**Comment by joakime** [comment]
If this is implemented, we should probably forbid XML `id` usage within the `<Configure id="foo">` element in this generic xml.

**Comment by janbartel** [comment]
Well, there's lots of things it would be a bad idea to configure in a generic context xml file, like the context path, the war file etc etc.

But fair point about the fact that the deployer currently lets the XmlConfiguration do the creating of the webapp/contexthandler.  The jetty maven plugin allows an xml file to be applied also, but the difference is that the webapp instance already exists and is passed in to the  XmlConfiguration to configure  instead.

I think there's still value in this idea, just needs more thinking.

**Comment by janbartel** [comment]
Well,well, well .... turns out that we already have this mechanism! It's called the GlobalWebAppConfigBinding:  https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/bindings/GlobalWebappConfigBinding.java.

I've raised issue #2207 for this to be documented, as its pretty useful for applying across-the-board basic configuration to all webapps.

@joakime I think this is correct, but can you just confirm that any xml applied via the GlobalWebAppConfigBinding will be applied _after_ any context xml file for the webapp? @WalkerWatch  you should include @joakime's answer in the documentation as well.

@joakime in light of this facility - and wanting to reduce any editing of etc files from the distro as much as possible - should we remove the special WebAppContext-like methods on DeploymentManager/WebAppProvider, as that functionality can be provided more flexibly by the GlobalWebAppConfigBinding?  In jetty-10.x I'd suggest.

**Comment by joakime** [comment]
Neat!
I'll check it out over the next day or two.

+1 for the cleanup on jetty-10.x

**Comment by janbartel** [comment]
I've added a PR for a module to allow users to easily enable GlobalWebAppConfig.

**Comment by gregw** [comment]
For the deployer context attributes, I would suggest the following approach:
 - create a ContextAttributeBinding  class that wraps an attribute map and when processBinding is called it will copy it's attributes to the passed App context.
- modify all the Deployment manage attribute methods to lazily create an instanceof ContextAttributeBinding and  to set their attributes on it.
- remove the explicit handling of attributes in App.getContextHandler()
- deprecate the attribute methods
- document the use of ContextAttributeBinding

This can be done in 9.4.x and we then just remove the deprecated methods in 10.0.x

**Comment by gregw** [comment]
Jan's PR is #2215

**Comment by joakime** [comment]
Closing as PR #2215 was merged.
