### ISSUE TITLE
Enable ErrorProne analysis in jetty build. Fix resulting warnings/errors.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2206]
Enable https://github.com/google/error-prone for the jetty build (initially as an optional profile).

Fix any errors/warnings that result (or at least prepare report here what they mostly are and discuss if they should be fixed).

**Comment by gregw** [comment]
@olamy has prepared #2200 to enable error-prone, hope to have that merged soon.
@lachlan-roberts let's chat next week about how to proceed

**Comment by lachlan-roberts** [comment]
A list of remaining numbers of errorprone warnings. @gregw 

 250 [DefaultCharset]
 175 [JdkObsolete]
 106 [FutureReturnValueIgnored]
 105 [ClassCanBeStatic]
  78 [BoxedPrimitiveConstructor]
  67 [NarrowingCompoundAssignment]
  46 [StringSplitter]
  43 [ClassNewInstance]
  43 [AssertEqualsArgumentOrderChecker]
  39 [AssertionFailureIgnored]
  20 [SynchronizeOnNonFinalField]
  17 [ImmutableEnumChecker]
  12 [MissingCasesInEnumSwitch]
  11 [URLEqualsHashCode]
  10 [EqualsHashCode]
   8 [MissingFail]
   6 [Finally]
   6 [FallThrough]
   5 [JUnit4TestNotRun]
   5 [IntLongMath]
   5 [InputStreamSlowMultibyteRead]
   4 [ThreadLocalUsage]
   4 [StreamResourceLeak]
   4 [ShortCircuitBoolean]
   4 [HidingField]
   3 [UnsynchronizedOverridesSynchronized]
   3 [NullTernary]
   3 [MissingOverride]
   3 [CollectionIncompatibleType]
   3 [CatchFail]
   2 [TypeParameterUnusedInFormals]
   2 [TryFailThrowable]
   2 [ReturnValueIgnored]
   2 [ReferenceEquality]
   2 [IndexOfChar]
   2 [IncrementInForLoopAndHeader]
   2 [GetClassOnAnnotation]
   2 [DeadException]
   1 [ThreeLetterTimeZoneID]
   1 [SizeGreaterThanOrEqualsZero]
   1 [OverrideThrowableToString]
   1 [NonOverridingEquals]
   1 [ModifyCollectionInEnhancedForLoop]
   1 [JUnit4SetUpNotRun]
   1 [GetClassOnClass]
   1 [ConstantOverflow]
   1 [AmbiguousMethodReference]

**Comment by gregw** [comment]
@lachlan-roberts thanks for that list - any chance of doing it again but with the link to the errorprone description so we can tell if they are serious or not?

Can you also look through the list and recommend the next few problems you think we should fix?   Also I think there are some ignorable ones there (eg StringSplitter)

**Comment by lachlan-roberts** [comment]
Some easy ones to fix which would also eliminate a significant amount of warnings are DefaultCharset, AssertEqualsArgumentOrderChecker and ClassCanBeStatic.

250 [DefaultCharset]  -  http://errorprone.info/bugpattern/DefaultCharset
175 [JdkObsolete]  -  http://errorprone.info/bugpattern/JdkObsolete
106 [FutureReturnValueIgnored]  -  http://errorprone.info/bugpattern/FutureReturnValueIgnored
105 [ClassCanBeStatic]  -  http://errorprone.info/bugpattern/ClassCanBeStatic
78 [BoxedPrimitiveConstructor]  -  http://errorprone.info/bugpattern/BoxedPrimitiveConstructor
67 [NarrowingCompoundAssignment]  -  http://errorprone.info/bugpattern/NarrowingCompoundAssignment
46 [StringSplitter]  -  http://errorprone.info/bugpattern/StringSplitter
43 [ClassNewInstance]  -  http://errorprone.info/bugpattern/ClassNewInstance
43 [AssertEqualsArgumentOrderChecker]  -  http://errorprone.info/bugpattern/AssertEqualsArgumentOrderChecker
39 [AssertionFailureIgnored]  -  http://errorprone.info/bugpattern/AssertionFailureIgnored
20 [SynchronizeOnNonFinalField]  -  http://errorprone.info/bugpattern/SynchronizeOnNonFinalField
17 [ImmutableEnumChecker]  -  http://errorprone.info/bugpattern/ImmutableEnumChecker
12 [MissingCasesInEnumSwitch]  -  http://errorprone.info/bugpattern/MissingCasesInEnumSwitch
11 [URLEqualsHashCode]  -  http://errorprone.info/bugpattern/URLEqualsHashCode
10 [EqualsHashCode]  -  http://errorprone.info/bugpattern/EqualsHashCode
8 [MissingFail]  -  http://errorprone.info/bugpattern/MissingFail
6 [Finally]  -  http://errorprone.info/bugpattern/Finally
6 [FallThrough]  -  http://errorprone.info/bugpattern/FallThrough
5 [JUnit4TestNotRun]  -  http://errorprone.info/bugpattern/JUnit4TestNotRun
5 [IntLongMath]  -  http://errorprone.info/bugpattern/IntLongMath
5 [InputStreamSlowMultibyteRead]  -  http://errorprone.info/bugpattern/InputStreamSlowMultibyteRead
4 [ThreadLocalUsage]  -  http://errorprone.info/bugpattern/ThreadLocalUsage
4 [StreamResourceLeak]  -  http://errorprone.info/bugpattern/StreamResourceLeak
4 [ShortCircuitBoolean]  -  http://errorprone.info/bugpattern/ShortCircuitBoolean
4 [HidingField]  -  http://errorprone.info/bugpattern/HidingField
3 [UnsynchronizedOverridesSynchronized]  -  http://errorprone.info/bugpattern/UnsynchronizedOverridesSynchronized
3 [NullTernary]  -  http://errorprone.info/bugpattern/NullTernary
3 [MissingOverride]  -  http://errorprone.info/bugpattern/MissingOverride
3 [CollectionIncompatibleType]  -  http://errorprone.info/bugpattern/CollectionIncompatibleType
3 [CatchFail]  -  http://errorprone.info/bugpattern/CatchFail
2 [TypeParameterUnusedInFormals]  -  http://errorprone.info/bugpattern/TypeParameterUnusedInFormals
2 [TryFailThrowable]  -  http://errorprone.info/bugpattern/TryFailThrowable
2 [ReturnValueIgnored]  -  http://errorprone.info/bugpattern/ReturnValueIgnored
2 [ReferenceEquality]  -  http://errorprone.info/bugpattern/ReferenceEquality
2 [IndexOfChar]  -  http://errorprone.info/bugpattern/IndexOfChar
2 [IncrementInForLoopAndHeader]  -  http://errorprone.info/bugpattern/IncrementInForLoopAndHeader
2 [GetClassOnAnnotation]  -  http://errorprone.info/bugpattern/GetClassOnAnnotation
2 [DeadException]  -  http://errorprone.info/bugpattern/DeadException
1 [ThreeLetterTimeZoneID]  -  http://errorprone.info/bugpattern/ThreeLetterTimeZoneID
1 [SizeGreaterThanOrEqualsZero]  -  http://errorprone.info/bugpattern/SizeGreaterThanOrEqualsZero
1 [OverrideThrowableToString]  -  http://errorprone.info/bugpattern/OverrideThrowableToString
1 [NonOverridingEquals]  -  http://errorprone.info/bugpattern/NonOverridingEquals
1 [ModifyCollectionInEnhancedForLoop]  -  http://errorprone.info/bugpattern/ModifyCollectionInEnhancedForLoop
1 [JUnit4SetUpNotRun]  -  http://errorprone.info/bugpattern/JUnit4SetUpNotRun
1 [GetClassOnClass]  -  http://errorprone.info/bugpattern/GetClassOnClass
1 [ConstantOverflow]  -  http://errorprone.info/bugpattern/ConstantOverflow
1 [AmbiguousMethodReference]  -  http://errorprone.info/bugpattern/AmbiguousMethodReference

**Comment by joakime** [comment]
@gregw @olamy hasn't this been accomplished already?  can this issue be closed?

**Comment by olamy** [comment]
yup there is a maven profile called errorprone.
