### ISSUE TITLE
Trie getBest on StringBuilder

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#221]
migrated from Bugzilla [#474363](https://bugs.eclipse.org/bugs/show_bug.cgi?id=474363)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.2_ on platform _All_
Assigned to: Project Inbox

On 2015-08-05 18:08:45 -0400, Greg Wilkins wrote:

> If the HttpParser fails on a getBest(buffer) call due to split buffers, then bytes are copied to a StringBuilder... subsequent lookups require the string to be built and then looked up.   If the Trie could lookup into a StringBuilder, then it could save the string creation.

**Comment by sbordet** [comment]
Still an enhancement to look into @gregw?

**Comment by gregw** [comment]
I do not think this is a priority.   Saving cycles on parting HTTP/1 in split buffers is likely to be counter productive.
