### ISSUE TITLE
getServletPath() truncates path at the first semicolon

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#222]
migrated from Bugzilla [#474554](https://bugs.eclipse.org/bugs/show_bug.cgi?id=474554)
status ASSIGNED severity *major* in component *server* for *9.3.x*
Reported in version *9.2.13* on platform *PC*
Assigned to: Greg Wilkins

On 2015-08-08 21:08:27 -0400, veggen skrikk wrote:

> Given a URL with path parameters (e.g. "/data/matrixvars;foo=bar1/multiple;foo=bar2"), the result of getServletPath() is truncated after the first semicolon (e.g. "/data/matrixvars" instead of "/data/matrixvars/multiple").
> This is easiest to see when a Servlet is mapped to "/*" as the whole path after the context path is the Servlet path.
> This is in violation of the Servlet spec.
> 
> Tomcat, as of version 7 at least (not sure about earlier), handles this correctly: it strips away the parameters, but the path remains intact. With the example above, for "/data/matrixvars;foo=bar1/multiple;foo=bar2" calling getServletPath() would yield "/data/matrixvars/multiple".

**Comment by gregw** [comment]
Closing in favour of #405
