### ISSUE TITLE
Use a dedicated URL for certificate authentication

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#223]
migrated from Bugzilla [#474645](https://bugs.eclipse.org/bugs/show_bug.cgi?id=474645)
status REOPENED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.2_ on platform _PC_
Assigned to: Project Inbox

On 2015-08-10 17:19:55 -0400, Benjamin Jaton wrote:

> The SecureRequestCustomizer allows to get the certificate in the HTTP request but this setting is server wide (all URLs).
> 
> It would be great to be able to do this only for a specific URL. I know this is possible in other web server where you can have a /auth/certificate that would ask for the certificate, which in turns usually triggers a popup in the browser to select the certificate to use.

On 2015-09-25 00:48:34 -0400, Greg Wilkins wrote:

> Benjamin,
> 
> I can't see how this can work.  The URL is data that is sent in the request, which can only be received if the connection is accepted and decoded.  The connection can only be accepted and decoded if we have already selected a certificate.
> 
> or are you talking about client certificates?  If so, can you reopen and give some more details about what you want.

On 2015-09-25 02:12:28 -0400, Benjamin Jaton wrote:

> It is about client certificate authentication indeed.
> 
> As I was describing, the scenario I would like to achieve is this:
> - The user connect to the web application using HTTPS:
>   https://host:1234/login
> - The login page offers the user several options for authenticating himself:
>   - a login/password form authentication
>   - but also a "button" for client certificate authentication
> - If if chooses the certificate authentication, he is redirected to https://host:1234/auth/certificate which will trigger the browser's client certificate selection popup (and only then).

On 2015-09-28 18:38:24 -0400, Greg Wilkins wrote:

> Benjamin,
> 
> OK we will look at this, but can't say how soon it will be.
> 
> My first guess is that it is more likely that we need to so something in ClientCertAuthenticator  rather than SecureRequestCustomizer
> 
> If you wish to expedite this, then please feel free to try a few changes yourself and propose a direction to go.

**Comment by joakime** [comment]
This seems like application logic.  

@gregw Jetty has the hooks in place for this sort of thing already, right? Shouldn't this just be closed?
