### ISSUE TITLE
JDK9 Test failure: org.eclipse.jetty.io.IdleTimeoutTest.testShorten

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2235]
`jetty-9.4.x` branch.
Linux build.
Bare metal build. (no container / docker)

```
Stacktrace
java.lang.AssertionError
	at org.eclipse.jetty.io.IdleTimeoutTest.testShorten(IdleTimeoutTest.java:130)
```

(sorry, that's all that is reported for this failure)

**Comment by gregw** [comment]
fixed be1a011120df75526b9c0f3a145628a3ea976071
