### ISSUE TITLE
HTTP session setAttribute does not work across servlets on Jetty/OSGi

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#224]
migrated from Bugzilla [#474716](https://bugs.eclipse.org/bugs/show_bug.cgi?id=474716)
status ASSIGNED severity *normal* in component *osgi* for *9.3.x*
Reported in version *9.2.9* on platform *Macintosh*
Assigned to: Jan Bartel

Original attachment names and IDs:
- _[de.tecthnology.tests.jetty.sessions.zip](https://bugs.eclipse.org/bugs//attachment.cgi?id=255790)_ (ID 255790)

On 2015-08-11 10:58:50 -0400, Todor Dimitrov wrote:

> Created attachment 255790
> Test OSGi bundle project
> 
> Since upgrading to the Mars release of Equinox (Jetty 9.2.9), our web authentication logic no longer works. It seems that setting a session attribute in one servlet and then performing a redirect to the next somehow resets the session or clears the session attributes. The session id is maintained between requests and the sessions cookie is properly set. The same code, without any modifications, works perfectly fine on the Luna release of Equinox (Jetty 8.1.14).
> 
> A rudimentary OSGi bundle project is attached, which registers two HTTP servlets using the OSGi HttpService. The first servlet sets an attribute and redirects to the second one. The second servlet reads the attribute and outputs it to the browser. The test can be invoked by calling the following URL: 
> 
> http://127.0.0.1/set (port may need to be appended).
> 
> After the redirect occurs the URL changes to http://127.0.0.1/read and the following text should be output when working properly:
> 
> test = 1
> 
> On Jetty 9 and Equinox Mars the output is:
> 
> test = null
> 
> Is there any configuration for the HttpService or Jetty, which is new to the Jetty 9 and which we might be missing?
> 
> Thanks in advance,
> Todor

On 2015-08-12 05:20:14 -0400, Todor Dimitrov wrote:

> It seems that the session attributes are scoped using the identifier of the HttpContext. When registering the two servlets in the example, no HttpContext instance is provided such that two default contexts with different ids will be used. Thus the attributes set by the first servlet are not visible in the second one. This also implies that servlets, which are registered by different OSGi bundles, cannot share HTTP session attributes*. Is this the indented behaviour?
> 
> Regards,
> Todor
> 
> * well, this could be accomplished by using some weird global HttpContext singleton(s)

On 2015-09-30 04:19:30 -0400, Jan Bartel wrote:

> Todor,
> 
> This link: https://osgi.org/javadoc/r4v42/org/osgi/service/http/HttpService.html says that if you want 2 servlets to share a single ServletContext, then they must have a common HttpContext passed into registerServlet method call. 
> 
> Also, I think this issue may be better addressed by the eclipse folks that maintain the org.eclipse.equinox.http.servlet.HttpServiceServlet that implements the HttpService.
> 
> Jan

**Comment by janbartel** [comment]
Nothing for jetty to fix here: seems like it is possible within the OSGi api for servlets to share a common HttpContext.
