### ISSUE TITLE
Suspected Flakey Test: linux_jdk8 / Test / org.eclipse.jetty.websocket.jsr356.server.OnMessageReturnTest.testEchoReturn

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2246]
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x-1803-proposal-0+2/43/

**Comment by joakime** [comment]
`jetty-9.4.x-1803-proposal-0+2` branch. (Likely true on `jetty-9.4.x` branch too)
Linux build.
JDK8 build.
Bare metal build. (no docker / container)
