### ISSUE TITLE
Selector activity verifier

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2248]
It would be interesting to have something that can report some statistics about the activity of the selector.
These would be how many selections, how many selections per second, how many actions, how many actions per second, how long a `select()` calls last, etc.

It is critical code, so perhaps an external component rather than instrumenting the selector itself.
Or perhaps subclassing the selector.

**Comment by joakime** [comment]
Could this effort also be used to highlight the strangeness we see with the selector on windows?

**Comment by sbordet** [comment]
@joakime what strangeness ? Link ?

**Comment by joakime** [comment]
Just thinking about the OP_CONNECT (and related) issues we've discussed recently surrounding behaviors we've observed on Windows.

**Comment by joakime** [comment]
@gregw this is the issue I mentioned
