### ISSUE TITLE
Jetty 9.3.X fails to start when module-required files are not at their default locations or are missing

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#225]
migrated from Bugzilla [#475409](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475409)
status ASSIGNED severity *normal* in component *start* for *9.3.x*
Reported in version *9.3.2* on platform *All*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[patch.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=255961)_ (ID 255961)

On 2015-08-19 13:18:08 -0400, Michael Domingues wrote:

> Created attachment 255961
> Proposed Patch
> 
> Overview
> --------
> When files that are specified in module [files] directives are missing (or located at alternative locations), Jetty warnings that the files are missing, erroneously logs an info message that the base directory has been modified, and exits.
> 
> This is a regression (introduced on the 9.3.X branch) of Bug ID: 427204, where it was decided that module directives for [files] should only trigger warnings, not lead to startup failure.
> 
> Steps to reproduce
> ------------------
> 1) Configure Jetty to use a module which includes a [files] directive (ssl, for example)
> 2) Do not place the required file (for ssl, etc/keystore) at the location that the .mod file specifies
> 3) Start Jetty from $JETTY_BASE using java -jar $JETTY_HOME/start.jar
> 
> Actual Result
> -------------
> Jetty logs the following warnings, followed by an info message, and fails to start:
> 
> WARNING: Missing Required File: ${jetty.base}\etc\keystore
> WARNING:   Can be downloaded From: http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/test/config/etc/keystore?id=master
> WARNING:   Run start.jar --create-files to download
> INFO: Base directory was modified
> 
> Expected Result
> ---------------
> Jetty logs the following warnings, without the info message, and starts properly:
> 
> WARNING: Missing Required File: ${jetty.base}\etc\keystore
> WARNING:   Can be downloaded From: http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/test/config/etc/keystore?id=master
> WARNING:   Run start.jar --create-files to download
> 
> Additional Information
> ----------------------
> According to the method documentation on org.eclipse.jetty.start.BaseBuilder.processFileResource(), the return boolean indicates:
> 
> * @return true if change was made as a result of the file, false if no change made.
> 
> Since no changes are made in the two particular conditions that could lead to these messages, they ought to return false, rather than true.

On 2015-08-19 18:07:02 -0400, Greg Wilkins wrote:

> Michael,
> 
> you can use the --skip-file-validation=  option to list files that need not be checked for.
> 
> I have already noted the incorrect warning about directory modification.  I have started working on a major refactor of this mechanism in the branch jetty-9.3-Feature2    I will look at bringing that impl to 9.3.x rather than 9.4.x as intended.

**Comment by joakime** [comment]
`--skip-file-validation=<moduleid>` is the recommended way.

Closing.
