### ISSUE TITLE
Make customizable whether to use direct or heap buffers

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#226]
migrated from Bugzilla [#475729](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475729)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _9.3.2_ on platform _PC_
Assigned to: Simone Bordet

On 2015-08-24 11:25:50 -0400, Simone Bordet wrote:

> We must make customizable whether to use direct or heap buffers.
> 
> This is to allow running Jetty with little memory, controlling the off-heap memory by using heap buffers.
> 
> Also, direct buffers should involve less copies and should be preferrable in most cases.

**Comment by sbordet** [comment]
Closed in favor of #3952 and #3953.
