### ISSUE TITLE
Implementing mod_cluster integration with Jetty

### ISSUE THREAD

**Issue by phoe** [eclipse/jetty.project#2261]
According to https://developer.jboss.org/thread/252385 : 

> A Jetty module would simply need to implement the interfaces found in the mod_cluster-container-spi module.

The interfaces in question are at https://github.com/modcluster/mod_cluster/tree/master/container/spi/src/main/java/org/jboss/modcluster/container

If I wanted to implement this myself, what would be required from my side to start working on this? What suggested reading should I do and what JBoss/Jetty concepts must I understand before trying to implement mod_cluster integration in Jetty?

This issue is a mirror of https://issues.jboss.org/browse/MODCLUSTER-644

**Comment by sbordet** [comment]
@phoe can you point us at how it is done for other containers ?
Then we would just need to translate from those APIs to Jetty APIs and we can point you in the right direction.

**Comment by rhusar** [comment]
As mentioned, the project exposes a simple SPI that needs to be implemented by containers (https://github.com/modcluster/mod_cluster/tree/master/container/spi/src/main/java/org/jboss/modcluster/container).
Here is an implemenetation for Tomcat 7.x: https://github.com/modcluster/mod_cluster/tree/master/container/tomcat

**Comment by phoe** [comment]
@sbordet Undertow also has an implementation of this interface at https://github.com/wildfly/wildfly/tree/master/mod_cluster/undertow

I think I somewhat understand this SPI right now, but I don't yet know how Jetty APIs and classes map to it. I will read more on this today and try to fork and do a little bit of code on this.

**Comment by phoe** [comment]
Is it okay to implement these interfaces in a new Maven submodule named `jetty-modcluster` in the root directory of the project?

**Comment by phoe** [comment]
I have created the skeleton of the implementation at https://github.com/phoe-trash/jetty.project/tree/jetty-9.4.x/jetty-mod_cluster

Now is the time when I need support from the Jettyfolk with understanding the APIs that Jetty exposes.

**Comment by sbordet** [comment]
@phoe the number of methods to implement is pretty large, so this would be a considerable effort for us.

It would be better if you'd ask direct questions such as:

"Method `isReverse()` should return whether gear shift is in reverse position. Tomcat does it in this way, asking to engines and valves. How can I implement the same semantic in Jetty ?".

Otherwise we would need to reverse engineer another implementation, which means becoming proficient in the other Servlet Container, which is even more reverse engineering.

**Comment by gregw** [comment]
@phoe Just to back up @sbordet here, there are too many TODO's in that skeleton.   To start filling them in, we'd basically have to understand and completely implement.
If you can have a go at the ones that should be pretty easy/obvious (eg `Connector#getPort` should be pretty easy for you to map to our `Connector#getLocalPort`).

Once you have filled in most of the boiler plate (borrowing from other implementations etc.), then we are happy to help you with the more difficult methods - virtual hosts, loading factors, threads etc.   So make a start on it and then ask here when you get bogged down/stuck.  No problems if there are lots of questions, as we can answer more easily than us looking at the skeleton to find the questions that you might ask!

**Comment by phoe** [comment]
I likely will be unable to spend time on this as our company will be unable to use these SPIs. The only mod_cluster supported by Red Hat is 2.x where the SPIs are only exposed in mod_cluster 3 and later.

**Comment by rhusar** [comment]
@phoe Incorrect, the SPI are available since mod_cluster 1.1.x (since Aug 2011).

**Comment by phoe** [comment]
@rhusar Oh! So I was wrong.

I could not see them in the mod_cluster repository - the folder `/containter/spi` at https://github.com/modcluster/mod_cluster/tree/1.4.x/container/spi does not exist in earlier branches.

Where should I look for them in 1.2?

**Comment by rhusar** [comment]
@phoe https://github.com/modcluster/mod_cluster/tree/1.2.x/container-spi

**Comment by phoe** [comment]
@rhusar Gah. I was blind. Thanks!
