### ISSUE TITLE
JDK8 Test failure: org.eclipse.jetty.server.session.CreationTest.testSessionCreateForward

### ISSUE THREAD

**Issue by phoe** [eclipse/jetty.project#2267]
`jetty-9.4.x` branch.
Linux build.
Bare metal build. (no container / docker)

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ uname -a
Linux phoebox 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.26 s <<< FAILURE! - in org.eclipse.jetty.server.session.CreationTest
[ERROR] testSessionCreateForward(org.eclipse.jetty.server.session.CreationTest)  Time elapsed: 0.092 s  <<< FAILURE!
java.lang.AssertionError
	at org.eclipse.jetty.server.session.CreationTest.testSessionCreateForward(CreationTest.java:271)
```

Attaching a better Maven log and surefire test results.

[maven.txt](https://github.com/eclipse/jetty.project/files/1770953/maven.txt)
[surefire-reports.zip](https://github.com/eclipse/jetty.project/files/1770966/surefire-reports.zip)

**Comment by joakime** [comment]
Is this from the latest HEAD of `jetty-9.4.x` branch?

**Comment by phoe** [comment]
It seems so. The last commit I see is:

```
commit c684295f7e1676a65af8ac3bfc8156c1492ac908
Author: Greg Wilkins <gregw@webtide.com>
Date:   Thu Mar 1 16:35:25 2018 +1100

    removed accidentally merged file
```

**Comment by joakime** [comment]
`jetty-9.4.x` HEAD is at 8cf357a17d7608abda45faed6d8fe0f9984aa14a currently.

**Comment by joakime** [comment]
That's close enough.  you are only missing a few documentation commits.

**Comment by janbartel** [comment]
@phoe  can you rerun the CreationTest  but with DEBUG log level enabled for "org.eclipse.jetty.server.session" please?

**Comment by joakime** [comment]
Linking to code (at commit c684295f7e1676a65af8ac3bfc8156c1492ac908) that produced this report (line 271 failed)

https://github.com/eclipse/jetty.project/blob/c684295f7e1676a65af8ac3bfc8156c1492ac908/tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/CreationTest.java#L270-L272

**Comment by phoe** [comment]
Ran the test several times and was unable to reproduce this again.

**Comment by joakime** [comment]
Closing
