### ISSUE TITLE
bad content-type on compressed content (like issue#474358)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#227]
migrated from Bugzilla [#476462](https://bugs.eclipse.org/bugs/show_bug.cgi?id=476462)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.3.2* on platform *PC*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[accept-gzip.pcapng](https://bugs.eclipse.org/bugs//attachment.cgi?id=257004)_ (ID 257004)

On 2015-09-02 14:23:47 -0400, Jayadevan VK wrote:

> This is on version 9.3.3 where issue # 474358 is marked as fixed. But I can still see the issue in effect. To repeat, if I make a request for app.js and there is already a pre-compressed app.js.gz available, the content-type of response is set to application/gzip instead of application/javascript.
> 
> If it is any help, I tracked down this issue as due to copying of headers from HttpContent object into response in line 1107 com.ubiquiti.servlets.DefaultServlet.putHeaders(HttpServletResponse, HttpContent, long)
> 
> which is eventually called from line 533 com.ubiquiti.servlets.DefaultServlet.doGet(HttpServletRequest, HttpServletResponse)
> 
> where the content object is looked up from _cache using app.js.gz path and therefore has application/gzip as content type.

On 2015-09-03 20:39:30 -0400, Joakim Erdfelt wrote:

> What's "com.ubiquiti." ?

On 2015-09-03 20:54:43 -0400, Jayadevan VK wrote:

> I am so sorry about the package name. I was trying some workarounds in my own pet project and copied FQN blindly.
> 
> I meant line 1107 org.eclipse.jetty.servlet.DefaultServlet.putHeaders(HttpServletResponse, HttpContent, long)
> 
> called from line 533 org.eclipse.jetty.servlet.DefaultServlet.doGet(HttpServletRequest, HttpServletResponse)

On 2015-09-30 17:24:08 -0400, Greg Wilkins wrote:

> Can you try https://oss.sonatype.org/content/repositories/jetty-with-staging/org/eclipse/jetty/jetty-distribution/9.3.4-SNAPSHOT/jetty-distribution-9.3.4-20150930.035527-19.tar.gz

On 2015-10-02 09:32:19 -0400, Jayadevan VK wrote:

> The issue remains. I have a .js file that is pre-gzipped. The content-type is application/gzip. I looked at the debug logs:
> 
> 2015-10-02 09:16:22,520 [qtp20191344-19] DEBUG o.e.jetty.servlet.DefaultServlet - uri=xyz.js, resource=file://xyz.js.gz, content=CachedContent@a32f08{r=file://xyz.js.gz,e=true,lm=Last-Modified: Mon, 01 Sep 2014 23:00:02 GMT,ct=Content-Type: application/gzip}
> 
> Looks like it is using CachedHttpContent; but I think it should be using CachedGzipHttpContent. I have not yet traced the call hierarchy.

On 2015-10-02 11:58:55 -0400, Joakim Erdfelt wrote:

> Tested on jetty-distribution-9.3.3.v20150827
> 
> Modifications to distribution ...
>   Edit ${jetty.home}/etc/webdefault.xml to enable DefaultServlet gzip=true
>   (its defaulted to false)
> 
> Run
>   $ cd jetty-distribution-9.3.3.v20150827
>   $ cd demo-base
>   $ java -jar ../start.jar
> 
> Tests
> 
> # No GZIP Accept
> 
> $ curl -I http://localhost:8080/test/da.txt
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Vary: Accept-Encoding
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Content-Type: text/plain
> Accept-Ranges: bytes
> Content-Length: 61000
> Server: Jetty(9.3.3.v20150827)
> 
> # With GZIP Accept
> 
> $ curl -H "Accept-Encoding: gzip" -I http://localhost:8080/test/da.txt
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Vary: Accept-Encoding
> Content-Encoding: gzip
> Content-Type: text/plain
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Accept-Ranges: bytes
> Content-Length: 2565
> Server: Jetty(9.3.3.v20150827)
> 
> # With GZIP Accept (and bigger file)
> 
> $ curl -H "Accept-Encoding: gzip" -I http://localhost:8080/test/dat.txt
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Content-Type: text/plain
> Accept-Ranges: bytes
> Content-Length: 244000
> Server: Jetty(9.3.3.v20150827)
> 
> # With GZIP Accept (requesting smaller file again)
> 
> $ curl -H "Accept-Encoding: gzip" -I http://localhost:8080/test/da.txt
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Vary: Accept-Encoding
> Content-Encoding: gzip
> Content-Type: text/plain
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Accept-Ranges: bytes
> Content-Length: 2565
> Server: Jetty(9.3.3.v20150827)
> 
> Not able to reproduce.
> Do you have a testcase showing this not working?

On 2015-10-02 12:11:48 -0400, Joakim Erdfelt wrote:

> Fetching the request, as opposed to using HEAD (which "curl -I" does), causes the failure.
> 
> $ curl --compressed -# --dump-header - \
>        -o /dev/null http://localhost:8080/test/da.txt
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Vary: Accept-Encoding
> Content-Encoding: gzip
> Content-Type: application/gzip
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Accept-Ranges: bytes
> Content-Length: 2565
> Server: Jetty(9.3.3.v20150827)
> 
> THIS is a bad Content-Type

On 2015-10-02 12:22:25 -0400, Joakim Erdfelt wrote:

> Some truly bizarre behavior here.
> (Attaching captured wireshark pcapng too)
> 
> $ curl -# --dump-header - -o /dev/null http://localhost:8080/test/da.txt
> 
> GET /test/da.txt HTTP/1.1
> User-Agent: curl/7.32.0
> Host: localhost:8080
> Accept: */*
> 
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Vary: Accept-Encoding
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Content-Type: text/plain
> Accept-Ranges: bytes
> Content-Length: 61000
> Server: Jetty(9.3.3.v20150827)
> 
> $ curl --compressed -# --dump-header - -o /dev/null http://localhost:8080/test/da.txt
> 
> GET /test/da.txt HTTP/1.1
> User-Agent: curl/7.32.0
> Host: localhost:8080
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Vary: Accept-Encoding
> Content-Encoding: gzip
> Content-Type: application/gzip
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Accept-Ranges: bytes
> Content-Length: 2565
> Server: Jetty(9.3.3.v20150827)
> 
> $ curl -H "Accept-Encoding: gzip" -# --dump-header - -o /dev/null http://localhost:8080/test/dat.txt
> 
> GET /test/dat.txt HTTP/1.1
> User-Agent: curl/7.32.0
> Host: localhost:8080
> Accept: */*
> Accept-Encoding: gzip
> 
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Content-Type: text/plain
> Accept-Ranges: bytes
> Vary: Accept-Encoding, User-Agent
> Content-Encoding: gzip
> Transfer-Encoding: chunked
> Server: Jetty(9.3.3.v20150827)
> 
> $ curl -H "Accept-Encoding: deflate, gzip" -# --dump-header - -o /dev/null http://localhost:8080/test/dat.txt
> 
> GET /test/dat.txt HTTP/1.1
> User-Agent: curl/7.32.0
> Host: localhost:8080
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
> HTTP/1.1 200 OK
> Set-Cookie: visited=yes
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Last-Modified: Thu, 27 Aug 2015 17:36:08 GMT
> Content-Type: text/plain
> Accept-Ranges: bytes
> Vary: Accept-Encoding, User-Agent
> Content-Encoding: gzip
> Transfer-Encoding: chunked
> Server: Jetty(9.3.3.v20150827)

On 2015-10-02 12:23:59 -0400, Joakim Erdfelt wrote:

> Created attachment 257004
> accept-gzip.pcapng
> 
> There are 4 requests on the attached pcapng
> 
> The CURL order is ...
> 
> [0]$ curl -# --dump-header - -o /dev/null http://localhost:8080/test/da.txt
> 
> [1]$ curl --compressed -# --dump-header - -o /dev/null http://localhost:8080/test/da.txt
> 
> [2]$ curl -H "Accept-Encoding: gzip" -# --dump-header - -o /dev/null http://localhost:8080/test/dat.txt
> 
> [3]$ curl -H "Accept-Encoding: deflate, gzip" -# --dump-header - -o /dev/null http://localhost:8080/test/dat.txt

On 2015-10-02 12:30:14 -0400, Joakim Erdfelt wrote:

> So the size of the gzip'd content seems to have a role in triggering this bug.
> If the size is small, then the Content-Type is correct.
> If the size is large (like the dat.txt on the test webapp on demo-base) then the Content-Type is incorrect

**Comment by joakime** [comment]
Can no longer replicate on Jetty 9.3.7
