### ISSUE TITLE
Problem with scope provided dependencies in jspc-plugin

### ISSUE THREAD

**Issue by Stasnek** [eclipse/jetty.project#2270]
Hi, this is a known issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=470327.
Is it possible to backport this bugfix to 9.2.x branch?
I can not use versions 9.3.x and 9.4.x in my project, because they are not compatible with JDK 1.7. 
Thanks.

**Comment by joakime** [comment]
That fix in jetty-9.3.x was done in commit aeb3da139335e7da4727be3794435dfc4b3b21b9

That's a 3 year old commit against a major version release of Jetty.

> (Jetty versioning reminder: `<servlet_support>.<major_version>.<minor_version>`)

The two branches jetty-9.2.x and jetty-9.3.x are very very different now.
We are unlikely to spend time to backport that commit against the deprecated Jetty 9.2.x branch.
(We are far too busy with Jetty 10.x / Servlet 4 / JDK9 / JDK10 issues at the moment)

**Comment by Stasnek** [comment]
Thank you for answer.
