### ISSUE TITLE
jetty.server.ResourceService.doGet() + RequestDispatcher INCLUDE

### ISSUE THREAD

**Issue by blop** [eclipse/jetty.project#2275]
Hello,

it seems doGet() is not working properly when using a RequestDispatcher INCLUDE.

I'd suggest replacing : 
`boolean endsWithSlash=(pathInfo==null?request.getServletPath():pathInfo).endsWith(URIUtil.SLASH);
`
with : 
`boolean endsWithSlash=(pathInfo==null?servletPath:pathInfo).endsWith(URIUtil.SLASH);
`
As the servletPath is overridden when processing an include and might switch from something that ends with slash to something that does not. It causes an issue for one of my usage.

Thanks.

**Comment by blop** [comment]
You might also want to replace : 
`if (endsWithSlash && pathInContext.length()>1)
`with : 
`if (!included && endsWithSlash && pathInContext.length()>1)
`
As the redirect is not allowed anyway when processing an include request.

**Comment by joakime** [comment]
Feel free to submit a PR (with test cases please) on this.

**Comment by gregw** [comment]
I'll do this.

**Comment by gregw** [comment]
I made these changes..... but I'm now wondering if that code is still needed.   I tried to write a test harness, but was unable to obtain a non-directory resource that ended in / that needs this redirection?   @joakime is it perhaps a windows thing that `/context/content.txt/` might return the same resource as `/context/content.txt` ?

**Comment by joakime** [comment]
Interesting.   I'll try a few things on Windows.
