### ISSUE TITLE
HTTP session can be automatically (re)created after session invalidation under race conditions

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#228]
migrated from Bugzilla [#477121](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477121)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.2.9* on platform *PC*
Assigned to: Jan Bartel

On 2015-09-10 19:48:16 -0400, D. P. wrote:

> Stack: Jetty 9/Spring MVC.
> The following behavior was observed.
> Prerequisites: HTTP session established and authenticated.
> The client works within the same session in 2 threads.
> ThreadA (caused by HTTP requestA)-> ends/invalidates the session by calling session.ivalidate()
> ThreadB (caused by HTTP requestB)-> performs some operations (within session)
> Sequence:
> 
> 1. ThreadA: starts processing, user is authenticated (since in security context is filled from still valid session).
> 2. ThreadB: starts processing, user is authenticated (since in security context is filled from still valid session).
> 3. ThreadA: executing the session invalidation operation -> session deleted
> 4. ThreadB (still in the processing): new session is created for already auth. user. This session is authenticated.
> As a result, we have the new authenticated session created while in such scenario I would expect the session to be terminated and no new session created.

On 2015-09-10 20:09:14 -0400, Jan Bartel wrote:

> The actual session object will be the same between ThreadA and ThreadB. Can you confirm if the session object that ThreadB is working with is set to invalid (either look at the session data if it has been persisted, or try calling a method that throws IllegalStateException if the session is invalidated such as getLastAccessedTime()).
> 
> FWIW the servlet spec does not provide any transactionality for session/request management so all kinds of race conditions are possible.

On 2015-09-11 15:24:16 -0400, D. P. wrote:

> First, this is intermittent problem we've found during one of the runs of our client, thus I can  not reproduce the test mentioned: try calling a method that throws IllegalStateException if the session is invalidated such as getLastAccessedTime().
> What we have in logs:
> the Id of session is the same in both threads (qtp1427015498-325 and qtp1427015498-264):
> 07/23/2015 12:48:43.718 TRACE [XX...X] [] [XX...X] [qtp1427015498-325]    x.x.x.XX...X Setting [session] to [xL5Pjefv2SOvnbywqU4uQApk4jezzwulc71v7bywhaanuqv] 
> vs
> 07/23/2015 12:48:43.877 TRACE [XX...X] [] [XX...X] [qtp1427015498-264] x.x.x.XX...X Setting [session] to [xL5Pjefv2SOvnbywqU4uQApk4jezzwulc71v7bywhaanuqv]
> 
> The session was destroyed:
> 07/23/2015 12:48:43.895 DEBUG [XX...X] [xL5Pjefv2SOvnbywqU4uQApk4jezzwulc71v7bywhaanuqv] [XX...X] [qtp1427015498-325]  x.x.x.HttpSessionMonitor x.x.x.HttpSessionMonitor@56094be5: destroying session [xL5Pjefv2SOvnbywqU4uQApk4jezzwulc71v7bywhaanuqv]
> 
> The HTTPSessionMonitor implements org.springframework.context.ApplicationListener and logs the mentioned line on receiving of org.springframework.security.web.session.HttpSessionDestroyedEvent.
> 
> Right after session was destroyed in thread qtp1427015498-325, the in the second thread qtp1427015498-264 the creation of new session was reported: 
> 07/23/2015 12:48:43.896 TRACE [XX...X] [xL5Pjefv2SOvnbywqU4uQApk4jezzwulc71v7bywhaanuqv] [XX...X] [qtp1427015498-264]   x.x.x.HttpSessionMonitor x.x.x.HttpSessionMonitor@56094be5: processing session created
> 
> 07/23/2015 12:48:43.896 TRACE [XX...X] [xL5Pjefv2SOvnbywqU4uQApk4jezzwulc71v7bywhaanuqv] [XX...X] [qtp1427015498-264]   x.x.x.HttpSessionMonitor x.x.x.HttpSessionMonitor@56094be5: registering session [xL5Pjefv2SOvnbywqU4uQA108c58wjxednp17sfrxbxbzv93]

On 2015-09-29 23:57:46 -0400, Jan Bartel wrote:

> Please report which session manager you are using.
> 
> thanks
> Jan

On 2015-10-20 15:34:46 -0400, D. P. wrote:

> (In reply to Jan Bartel from comment # 3)
> > Please report which session manager you are using.
> > 
> > thanks
> > Jan
> 
> org.eclipse.jetty.server.session.HashSessionManager
> and 
> org.eclipse.jetty.server.session.HashSessionIdManager

**Comment by janbartel** [comment]
The session manager code has been completely re-architected in jetty-9.4 with better and more consistent locking. I think these kind of race conditions are much less likely to occur, but as the servlet spec does not have any support for transactionality, there is always the likelihood (in a clustered scenario particularly) that races occur.

Please try out the new jetty-9.4 and see if you can reproduce the initial problem. If so, please provide full logs (with org.eclipse.jetty.server.session.LEVEL=DEBUG) and a description of exactly how the situation was produced.

thanks
Jan
