### ISSUE TITLE
Cleanup the statistics classes

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2288]
`SampleStatistic` should be cleaned up so that `getMean()` is guarded against division by zero and rename the confusing `set` method with `record`.

Both `CounterStatistics` and `SampleStatistic` can get better javadocs.

**Comment by gregw** [comment]
and make them JMX beans with names

**Comment by olamy** [comment]
done with https://github.com/eclipse/jetty.project/commit/a3100e02118fca25358c8b59baea9bd95b86e92f
