### ISSUE TITLE
unbalanced SelectorManager

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2295]
Dumps from some production machines have shown unbalanced SelectorManagers, with some selectors having thousands of keys while others are near idle.

**Comment by gregw** [comment]
@sbordet in your recent review of the log files, did you again see unbalanced selectors?
If not, can you close this issue and associated PR for now.

**Comment by joakime** [comment]
Looks like Issue #2005 is related.

**Comment by sbordet** [comment]
Have not seen unbalanced selectors, so closing this issue.
