### ISSUE TITLE
jetty-version-maven-plugin is not marked threadsafe.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2303]
```
[WARNING] The following plugins are not marked @threadSafe in Jetty :: Utility Servlets and Filters:
[WARNING] org.eclipse.jetty.toolchain:jetty-version-maven-plugin:2.5
```

**Comment by joakime** [comment]
Work completed at jetty-version-maven-plugin.
https://github.com/jetty-project/jetty-version-maven-plugin/commit/b8ae0277ce2d2023a0ea48055521b9081fd9820b
Going to kick off a new release this week.
