### ISSUE TITLE
 upstream prematurely closed connection while reading response header from upstream, client:

### ISSUE THREAD

**Issue by sdcuike** [eclipse/jetty.project#2306]
When use nginx as a proxy to jetty，and upstream part set keepavlie  10000，some error happend：

2018/03/04 22:39:30 [error] 19106#19106: *20638423165 upstream prematurely closed connection while reading response header from upstream, client.....

**Comment by sdcuike** [comment]
resolve it

**Comment by keredson** [comment]
resolved how?

**Comment by joakime** [comment]
No information was provided by the OP.
We did nothing on our side.

**Comment by sdcuike** [comment]
@keredson @joakime  caused by nginx upstream servers keepalive timeout, see https://theantway.com/2017/11/analyze-connection-reset-error-in-nginx-upstream-with-keep-alive-enabled/

https://serverfault.com/questions/845171/http-502-response-generated-by-a-proxy-after-it-tries-to-send-data-upstream-to-a/901372#901372

**Comment by SpComb** [comment]
nginx 1.15 adds an `upstream { keepalive_timeout ...}` configuration setting: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_timeout

This defaults to 60s, which is longer than the default `jetty.http.idleTimeout=30000`. This configuration introduces a race condition when using HTTP keepalive, resulting in sporadic nginx `upstream prematurely closed connection while reading response header from upstream` errors: https://trac.nginx.org/nginx/ticket/1484#comment:4

Not entirely sure about nginx 1.14 and earlier, I suspect it may keep the keepalive connections around indefinitely, until it notices that they have been closed.
