### ISSUE TITLE
Type change in MonitorTask - int cannot be converted to ThreadPoolExecutor

### ISSUE THREAD

**Issue by wltjr** [eclipse/jetty.project#2308]
Building 9.4.9 under Java 9, I get the following exception on Jetty Monitor

```java
src/main/java/org/eclipse/jetty/monitor/jmx/MonitorTask.java:45: error: incompatible types: int cannot be converted to ThreadPoolExecutor
    private static ThreadPool _callback = new ExecutorThreadPool(4,64,60,TimeUnit.SECONDS);;
```

A possible fix
```diff
--- a/jetty-monitor/src/main/java/org/eclipse/jetty/monitor/jmx/MonitorTask.java   2018-03-08 15:32:29.965072205 -0500
+++ b/jetty-monitor/src/main/java/org/eclipse/jetty/monitor/jmx/MonitorTask.java   2018-03-08 15:32:47.999017040 -0500
@@ -22,6 +22,8 @@
 import java.util.Map;
 import java.util.Timer;
 import java.util.TimerTask;
+import java.util.concurrent.LinkedBlockingQueue;
+import java.util.concurrent.ThreadPoolExecutor;
 import java.util.concurrent.TimeUnit;

 import org.eclipse.jetty.util.log.Log;
@@ -42,7 +44,7 @@
     private static final Logger LOG = Log.getLogger(MonitorTask.class);

     private static Timer __timer = new Timer(true);
-    private static ThreadPool _callback = new ExecutorThreadPool(4,64,60,TimeUnit.SECONDS);;
+    private static ThreadPool _callback = new ExecutorThreadPool(new ThreadPoolExecutor(4,64,60,TimeUnit.SECONDS,new LinkedBlockingQueue<>()));
     private static Map<String,TimerTask> __tasks  = new HashMap<String,TimerTask>();

     private final MonitorAction _action;
```

**Comment by olamy** [comment]
jetty-monitory is not part anymore of jetty-9.4.x main build.
@janbartel @jmcc0nn3ll  @sbordet @gregw  @joakime I don't have the history of it is it intentional?
If we don't want to maintain IMHO we should remove the jetty-monitor directory
WDYT?

**Comment by joakime** [comment]
+1 for removing it entirely

**Comment by wltjr** [comment]
FYI I am not using jetty-monitor, just [packaged it](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jetty-monitor/jetty-monitor-9999.ebuild) in my Gentoo overlay repository. Along with other pieces of Jetty to ensure I had them all, if someone needed any component  in particular. Completely moot to me either way. Just ran into the issue, and thought I would mention it. I am good with removal, or anything. Thanks!

**Comment by gregw** [comment]
I think we should kill it.  It has never really been completed or used and is not actually built.  I'll do it!
