### ISSUE TITLE
Cannot use jetty-http-client in webapp

### ISSUE THREAD

**Issue by lglowania** [eclipse/jetty.project#2316]
I enabled client.mod and it shows up in --list-config:
44:          9.4.8.v20171121 | ${jetty.home}/lib/jetty-client-9.4.8.v20171121.jar

But when i try to deploy a webapp that uses jetty-client, a class is not found:

java.lang.ClassNotFoundException: org.eclipse.jetty.client.api.ContentProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:550)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:475)

**Comment by joakime** [comment]
The package `org.eclipse.jetty.client` is exposed by default.
You can add that exposure yourself for the webapp you are interested in exposing it to.

In your `${jetty.base}/webapps/<context>.xml` (where `<context>` is your webapp's file name)

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/example</Set>
  <Set name="war"><Property name="jetty.webapps"/>/example.war</Set>

  <Call name="addSystemClass">
    <Arg>org.eclipse.jetty.client.</Arg>
  </Call>
</Configure>
```
