### ISSUE TITLE
ConnectionPool in Jetty 9

### ISSUE THREAD

**Issue by Pratibha24** [eclipse/jetty.project#2319]
Hi,

Need a help. I am doing the following:
	Request	request = client.POST(uri);
		request.method("GET");
		request.content(new StringContentProvider(content));
		request.timeout(clientOpts.getReadTimeout(), TimeUnit.SECONDS);
                request.header(HttpHeader.AUTHORIZATION, "blabla");
		request.send();

But i found that when it goes to "process" method of "HttpDestination", then the connection becomes null and then control comes out from the loop due to break statement.

Connection connection = connectionPool.acquire();
 if (connection == null)
       break;

How to set this connection pool.

Regards,
Pratibha

**Comment by sbordet** [comment]
I don't understand what your concern is.
The connection will be created asynchronously and the request sent when the connection is available.

**Comment by sbordet** [comment]
Please reopen if you have further questions about this issue.
