### ISSUE TITLE
WWWAuthenticationProtocolHandler fails with "Buffering capacity exceeded..." if HTTP 401 response has length greater than 4096

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#232]
migrated from Bugzilla [#477900](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477900)
status ASSIGNED severity *normal* in component *client* for *9.3.x*
Reported in version *9.2.11* on platform *PC*
Assigned to: Simone Bordet

On 2015-09-21 02:01:58 -0400, Mark Mielke wrote:

> I am using Jetty HttpClient to access a remote JIRA install, and a remote Crucible install. Some requests are failing with "Buffering capacity exceeded ..."
> 
> This appears to be because the JIRA HTTP 401 response sometimes has long headers and an HTML body that exceeds 4096 bytes by just a few bytes. For the details, it appears that there is a different error for regular HTTP 401 "not authorized" to access a REST resource, and HTTP 401 "session not recognized" in the case that the session cookie has expired. I believe the latter outputs an HTML response.
> 
> WWWAuthenticationProtocolHandler calls AuthenticationProtocolHandler with a maxContentLength of AuthenticationProtocolHandler.DEFAULT_MAX_CONTENT_LENGTH which is only 4096.
> 
> Is there a reason why AuthenticationProtocolHandler.DEFAULT_MAX_CONTENT_LENGTH is so small? Why shouldn't it use the same default as a BufferingResponseListener of 2 MBytes? Since it will accept up to 2 MBytes for a regular response, why wouldn't it accept up to 2 MBytes for an HTTP 401 response?
> 
> Thanks!
> 
> P.S. I had a thought that WWWAuthenticationProtocolHandler and most others should only need to buffer the headers, and buffering the content is unnecessary. But, I think this may be tricky to implement as a general case, and allowing buffering up to 2 MBytes for an HTTP 401 response would suffice.

On 2015-09-24 03:24:19 -0400, Greg Wilkins wrote:

> With commit 1af9b3e I have increased the size the 16KB.
> Assigned to Simone for comment and perhaps consideration of something more dynamic with a larger limit?

**Comment by sbordet** [comment]
A larger default is fine, and it is possible to customize the authentication protocol handlers max buffer capacity via the `ProtocolHandlers` API.

**Comment by catap** [comment]
@sbordet how does it possible to customise such value via `ProtocolHandlers` api?
