### ISSUE TITLE
Document usage of Jetty in Docker/Containers

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#2330]
Should document usages of Jetty as it relates to container technologies, namely Docker. Things to look out for, pitfalls...etc. Include items like the ability to overwrite available processors introduced in #2298

**Comment by joakime** [comment]
Bump documentation issue for one more year.

**Comment by WalkerWatch** [comment]
Bump. Perhaps @lachlan-roberts this is in your wheel-house
