### ISSUE TITLE
Refactor MultiRelease Jar handling

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2334]
I'd like to propose that we add a ZipFsResource implementation, and deprecate / remove the following in Jetty 10.x

MultiReleaseJarFile
JavaVersion
JarFileResource

Possibly even UrlResource.

This can even be the synthesis for a totally immutable Resource layer.

Example of how ZipFs works ...

``` java
    Map<String, Object> env = new HashMap<>();
    env.put("multi-release", "9"); // can be "release" to use the JVM runtime platform

    // URI is jar:file://

    try (FileSystem zipfs = FileSystems.newFileSystem(uri, env))
    {
        zipfs.getRootDirectories().forEach((rootPath) ->
        {
            try
            {
                Files.walkFileTree(rootPath, new DumpTree(rootPath));
            }
            catch (IOException e)
            {
                e.printStackTrace();
            }
        });
    }
```

**Comment by joakime** [comment]
Issue #206 might be addressed by the immutable Resource layer setup this refactor could produce.

**Comment by gregw** [comment]
+1
