### ISSUE TITLE
ServletUpgradeRequest getSubProtocols() creates an ArrayList even if sub protocols is absent. 

### ISSUE THREAD

**Issue by JerryChin** [eclipse/jetty.project#2337]
I found this method [UpgradeHttpServletRequest#getHeaders](https://github.com/eclipse/jetty.project/blob/39013cbc9166401599e4b30a4df94275c847a057/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/UpgradeHttpServletRequest.java#L160) is returning an empty `Enumeration<String> ` instead of null, subsequently, [ServletUpgradeRequest#getSubProtocols](https://github.com/eclipse/jetty.project/blob/39013cbc9166401599e4b30a4df94275c847a057/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeRequest.java#L388) creates an ArrayList initialized with 2 elements.

I think this behavior can be avoided to make Jetty web-socket connection more efficient.

**Comment by joakime** [comment]
Merged in commit 2b32f82aeb64acc6105c08d8a7a141279f8b91d0
