### ISSUE TITLE
Support for JDK 11

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2339]
A quick attempt to run the Jetty build with JDK 11 failed because JaCoCo failed in the forked JVM that runs the tests.
JaCoCo fails because of jacoco/jacoco#629, which boils down to be ASM not supporting yet JDK 11 bytecode format.

**Comment by sbordet** [comment]
Support for JDK 11 should be started because it contains important NIO changes, see http://mail.openjdk.java.net/pipermail/nio-dev/2018-March/004830.html

**Comment by sbordet** [comment]
@olamy can you setup Jenkins with this and perhaps for now skip using JaCoCo ?

**Comment by olamy** [comment]
done see jenkins job here: https://jenkins.webtide.net/job/jetty-9.4.x-jdk11/
