### ISSUE TITLE
Support Hourly Access Log Rotation

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#234]
migrated from Bugzilla [#479112](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479112)
status ASSIGNED severity _normal_ in component _server_ for _9.3.x_
Reported in version _unspecified_ on platform _All_
Assigned to: Joakim Erdfelt

On 2015-10-06 03:47:51 -0400, Viktor Szathmary wrote:

> Hi,
> 
> For larger traffic sites, it would be great if NCSARequestLog / RolloverFileOutputStream supported more granular log rotation (e.g. hourly). Currently it only seems to support a daily rotation schedule.
> 
> Thanks,
>   Viktor

On 2015-10-06 03:50:20 -0400, Greg Wilkins wrote:

> Good idea.... but doubt we will get around to it any time soon.   Would welcome contribution to extend/replace/change the rollover stream support to hourly.
> 
> You have the CLA ticked, so just go make a github PR :)

On 2015-10-06 09:27:03 -0400, Joakim Erdfelt wrote:

> This is possible right now.
> 
> Use the org.eclipse.jetty.server.Slf4jRequestLog
> 
> Send the requests to a specific named slf4j logger.
> Then use that named logger to produce a log file of your preferred behavior/format.
> 
> http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/Slf4jRequestLog.html

**Comment by joakime** [comment]
This is low priority, leaving it open for others that want to help.

**Comment by sbordet** [comment]
@joakime have we not already implemented this ?

**Comment by joakime** [comment]
Closing as this would be a feature of using Slf4jRequestLog an advanced logger library.
