### ISSUE TITLE
File Descriptor Leak: Conscrypt: "Too many open files"

### ISSUE THREAD

**Issue by GautamGupta** [eclipse/jetty.project#2342]
I don't have a lot on the root cause, but we ran into the not-so-helpful "too many open files" error while using HTTP/2 with Dropwizard (which uses Jetty). Reverting the change made the issue go away—using https 1.1 with the same library versions (but without Conscrypt) works just fine. Here's the relevant part of the pretty standard config:

Dropwizard:
```git
applicationConnectors:
--  type: https
++  type: h2
++  maxConcurrentStreams: 1024	
++  initialStreamRecvWindow: 65535	
  keyStorePath: ...
  keyStorePassword: ...
++  jceProvider: Conscrypt
```
Gradle:
```git
++ 'org.conscrypt:conscrypt-openjdk-uber:1.0.1',
'io.dropwizard:dropwizard-core:1.3.0-rc7',
... some other dropwizard libraries
++ 'io.dropwizard:dropwizard-http2:1.3.0-rc7',
++ 'org.eclipse.jetty:jetty-alpn-conscrypt-server:9.4.8.v20171121',	
```

From the logs:
```
WARN  [2018-03-14 16:47:36,619] org.eclipse.jetty.server.AbstractConnector: 
! java.io.IOException: Too many open files
! at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
! at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
! at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
! at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:379)
! at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:638)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
! at java.lang.Thread.run(Thread.java:748)
... same warning multiple times

WARN [2018-03-14 16:48:32,780] sun.rmi.transport.tcp: RMI TCP Accept-*: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=*] throws
! java.net.SocketException: Too many open files (Accept failed)
! at java.net.PlainSocketImpl.socketAccept(Native Method)
! at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
! at java.net.ServerSocket.implAccept(ServerSocket.java:545)
! at java.net.ServerSocket.accept(ServerSocket.java:513)
! at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
! at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
! at java.lang.Thread.run(Thread.java:748)
... same warning multiple times
```

I believe this is what led to connections to our database failing, which is when we looked into the issue.

![image](https://user-images.githubusercontent.com/187822/37485818-c18281de-2849-11e8-896b-37d44faf10a4.png)

First came a restart, but the open file descriptors kept increasing. Reverting the aforementioned changes and deploying fixed it.

From #354, I see there was a fix to prevent this from happening. If you feel Jetty doesn't have anything to do with this, please feel free to close the issue.

**Comment by joakime** [comment]
Can you cause this reliably?

You could install the file-leak-detector at http://file-leak-detector.kohsuke.org/ (used as a java agent)
And see what it reports as the cause.

**Comment by bjokax** [comment]
We have seen similar issues when using Jetty 9.4.8 and Conscrypt. In our case it looks like Conscrypt is leaking 2 PIPE per created SSLEngine.

**Comment by sbordet** [comment]
@bjokax did you file an issue to the [Conscrypt project](https://github.com/google/conscrypt) ?

**Comment by AnywhereSoftware** [comment]
Same here. Updated to Jetty 9.4.10, Http/2 enabled with Conscrypt and for the first time we got a "too many open files" error.
I see many open pipes in the file descriptors list.

**Comment by sbordet** [comment]
@bjokax or @AnywhereSoftware, have you reported this issue to the [Conscrypt project](https://github.com/google/conscrypt) ? If so, can you link it here ?

**Comment by AnywhereSoftware** [comment]
https://github.com/google/conscrypt/issues/491

**Comment by bjokax** [comment]
If SSLEngine.closeOutbound() is not called, these PIPEs will be closed using java finalizers, but with a big heap, that could take some time. Could it be that Jetty need to add some extra calls to closeOutbound() to ensure that the PIPEs are clean up early!?

**Comment by sbordet** [comment]
@bjokax seems to me that Jetty calls `SSLEngine.closeOutbound()` at the proper times, i.e. as a consequence to a `EndPoint.shutdownOutput()` and `EndPoint.close()` calls.

If `SSLEngine` itself produced `SSLEngineResult.Status.CLOSED`, we don't call `SSLEngine.closeOutbound()`, as the `SSLEngine` should have freed resources itself, since it produced the `CLOSED` state.

**Comment by joakime** [comment]
@sbordet looks like conscrypt will have a new release out with the week with the fix for google/conscrypt#491

**Comment by cakofony** [comment]
The 1.1.4 release is available.

**Comment by AnywhereSoftware** [comment]
FWIW, we still see a file descriptors leak with conscrypt, tested with v1.1.4. Maybe we are doing something wrong however it does work properly with the default Java 9+ provider (which is good enough for us).

**Comment by hwiegard** [comment]
Same for us, we also see the number of pipes increasing. It looks like 

```java
public boolean isOutboundDone() {
    synchronized (ssl) {
        return state == STATE_CLOSED || state == STATE_CLOSED_OUTBOUND || ssl.wasShutdownSent();
    }
}
``` 
returns `true` and due to this `SslConnection#doShutdownOutput` returns early (`boolean oshut = isOutputShutdown();` is `true`).

**Comment by tk-l2002** [comment]
Confirm here, using "Jetty 9.4.12" with "Conscrypt 1.2" provokes file descriptors leak

**Comment by radifalco** [comment]
I'm also seeing this issue. I'm using 9.4.11.v20180605 and conscrypt 1.4.1.

**Comment by radifalco** [comment]
I'll add that I only have this issue with HTTP/2. HTTPS does not give me the issue.

**Comment by jjestrel** [comment]
Reproduced on jetty `9.4.12.v20180830` conscrypt `1.1.4`

**Comment by sbordet** [comment]
Moved to #3111.
