### ISSUE TITLE
On initial onslaught of server, sessions not being created

### ISSUE THREAD

**Issue by ebremer** [eclipse/jetty.project#2348]
I've made a image tiling server using Jetty.  One client may request multiple subimages with many http calls to the Jetty image tiling server.  If I ask for one sub-image, a new session is created that stores the main image object in that session.  If I then hammer the image server for dozens of images, everything works as expected and all of the subsequent connection will use the same session and the same shared image object.  However, if I do not do the initial single call, and just hammer the server with the same multiple connections, each of those connections all look like new sessions and never use the same shared image object.  Is there a way to do this without that initial "priming" single call?  Is this a glitch in Jetty or am I doing something wrong?  I am using 9.4.5.v20170502 with an in-memory session handler:

        SessionHandler sessions = context.getSessionHandler();
        SessionCache cache = new DefaultSessionCache(sessions);
        cache.setSessionDataStore(new NullSessionDataStore());
        sessions.setSessionCache(cache);

**Comment by janbartel** [comment]
It's not surprising that multiple simultaneous requests don't share the same session: a newly created session id needs to get back to the client (either as cookie or url rewrite) so it can be used on subsequent requests so those requests are linked. If the cookie doesn't get back in time before you send the next request, then it looks like there is no session and a new one will be created.

IIWY I would store the image elsewhere, and just store a key to it in the session. That way if you do happen to create multiple sessions, they can all share the same image.  Of course you need a way to identify which requests should share the same image: if you can control the request formation, then maybe you could insert a cookie with the id that you want the requests to share. You can do some synchronization in your app to ensure that the image only gets created once and the key to it shared amongst all the sessions.

If you can't control the request formation, then best thing to do is effectively make a single request to establish the session to share on the subsequent sessions.

**Comment by ebremer** [comment]
Yeah, I had the "duh" moment realizing this in the hours after my post.  I should have thought it through more.  Thanks!
