### ISSUE TITLE
Review HTTP/2 max streams enforcement

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2349]
The HTTP/2 specification requires to treat a stream that exceeds the max number of concurrent streams as a stream error (https://tools.ietf.org/html/rfc7540#section-5.1.2).

`HTTP2Session.createRemoteStream()` has the logic to do that, but it's in a race with other threads that just completed a stream. The race is as follows, assuming `max_concurrent_stream=1`:

- T1 is about to complete a stream, sending the last frame with `endStream=true`
- T1 writes the frame and the callback is invoked (either `HTTP2Session.ControlEntry` or `HTTP2Session.DataEntry`)
- The frame travels to the client, which receives it and completes the stream, thereby issuing another request for the same session
- T1 is about to call `HTTP2Session.removeStream()` but it is preempted
- T2 handles the new request, calls `HTTP2Session.createRemoteStream()` but there fails because T1 has not finished to perform the `removeStream()` operation that would decrement the number of streams for that session

**Comment by joakime** [comment]
Issue #752 seems relevant

**Comment by sbordet** [comment]
@joakime nah, #752 is about something different.

**Comment by sbordet** [comment]
Fixed by #2389.

**Comment by gregw** [comment]
It appears max streams can still be violated

**Comment by sbordet** [comment]
@gregw commit 8cf15659be0b41d89ac335c91059d8d17b413cdd had the proper `updateClose()` call in place for `DATA` frames; however, merging #2366 a month later somehow removed that call.

**Comment by sbordet** [comment]
Restored removed code with 635cf4d, closing.

**Comment by gregw** [comment]
I think we still need a unit test added that checks this functionality.

**Comment by sbordet** [comment]
@gregw I'm adding it as part of #2672.
