### ISSUE TITLE
CachingWebAppClassLoader is not using cache properly

### ISSUE THREAD

**Issue by arokhmistrov** [eclipse/jetty.project#2361]
It seems there should be `if (url==null)` on line 68.
https://github.com/eclipse/jetty.project/blob/afd067771937bd46eb72bbd2c4d27956e0874386/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/CachingWebAppClassLoader.java#L65-L71

**Comment by joakime** [comment]
That does look suspicious.

Linking to other CachingWebAppClassLoader issues that might be impacted ... #260, #269

**Comment by joakime** [comment]
Merged into jetty-9.4.x (did not make it into jetty-9.4.9)
