### ISSUE TITLE
Use start.d and individual ini files as default instead of start.ini

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#2364]
Currently, `start.ini` is the default implementation if users activate modules without first running `--create-startd`. While this works, I prefer the `start.d` implementation with individual ini files, and our documentation points in this direction. 

As such, I propose that in Jetty 10 and beyond the default implementation is `start.d`. If a user attempts to add a module and neither `start.ini` nor the `start.d` directory exists, start.d is created and the individual ini file(s) populated.

**Comment by joakime** [comment]
I'm -1 on removal of `start.ini`.

It makes communicating the behaviors overly complicated in mailing lists, stackoverflow, etc ...

**Comment by jmcc0nn3ll** [comment]
Originally the idea of the start.ini was loosely modeled on the way that eclipse itself starts up, with a start.ini file.  Simple to understand, everything in one place and you can edit one file with vi to make ordered changes.

It has gone much farther and incorporated configuration elements or strategies of other sorts of applications now and we basically have this two pronged configuration approach.  If anything I think it might behoove us to provide a utility that lets you swap between the two approaches and enforce any conventions that make this possible.  IE strongly typed configuration values that map to modules they are associated with, things like that.  Joakim added a lot of really good tooling to dig out what modules affect which others and where every value is getting set and overridden from.  Perhaps we just need to push that a little bit further so we have a --validate option akin to what haproxy or nginx has...something that validates we have sane configuration and conventions are all passing muster.

**Comment by joakime** [comment]
its not unique to eclipse.
many java projects do the same thing. (even IntelliJ!)

**Comment by jmcc0nn3ll** [comment]
Initially I was far more on the one file approach then anything, but I suppose the counter in comparing other software and Jetty in this context would be that those apps (eclipse, intellij, etc) have built in configuration mechanisms for adding functionality akin to our mod system.  In a server container like Jetty we would probably need to provide an admin interface for configuring all that goop to make it an apples to apple comparison.  On something like Jetty I think far more people prefer administration from command line than click click click apps.

A bit stronger convention approach to this setup, that had a written or unwritten goal of being able to conceptually toggle between the approaches, would maybe be the best of both worlds?  My concern with the start.d approach as always been the issue of from the command line 'Which file did I need to open with vi to make that simple change again?'.  We have heavily moved towards stronger conventions on configuration variables and the like but maybe for Jetty 10 it makes sense to complete that work in a verifiable and validatable(?) way?

**Comment by gregw** [comment]
@joakime This is not a proposal to remove `start.ini`, only to make using a `start.d` the default rather than a `start.ini`.  If a `start.ini` exists then it will be used for starting and any future --add-to-start.

The `start.d` approach should be familiar to many system administrators.  Examples of the same approach I can find on my ubuntu system are:
- `/etc/grub.d/`
- `/etc/init.d/`
- `/etc/rc*.d/`
- `/etc/apache2/conf-enabled/`
- `/etc/apache2/mods-enabled/`
- `/etc/apt/apt.conf.d/`
- `/etc/apt/sources.list.d/`

and 10s more like that!

**Comment by joakime** [comment]
Funny enough, of the list you provided @gregw the following directories are now deprecated and not even present on Fedora 28 (you can thank SystemD).

```
/etc/grub.d/
/etc/init.d/
/etc/rc*.d/
/etc/apache2/conf-enabled/
/etc/apache2/mods-enabled/
/etc/dnf/
```

**Comment by gregw** [comment]
I'm going to close this issue.  I think we currently have the balance correct - users can use either start.ini or start.d
While I would prefer an implicit `--create-startd` to have been the default, I think changing now will make more problems than it solves.
