### ISSUE TITLE
Review HTTP/2 interleaving

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2366]
Current interleaving algorithm:

```
Queue: A B C
Generate: A1, B1, C1, A2, B2, C2, A3, C3, A4
Write: A1, B1, C1, A2, B2, C2, A3, C3, A4
Queue: D E
Generate: D1, E1, D2, E2, D3, D4
Write: D1, E1, D2, E2, D3, D4
```

This scheme favors `A B C` over `D E`, since `D E` won't be written until `A B C` are fully written.
Furthermore, `A B C` may generate large writes that may go into TCP congestion and may take time to finish, possibly delaying `D E` by a non negligible amount of time.
The positive side of this algorithm is that only 2 writes are needed to write all the frames.

Alternate algorithm:

```
Queue: A B C
Generate: A1, B1, C1
Write: A1, B1, C1
Queue: A B C D E
Generate: A2, B2, C2, D1, E1
Write: A2, B2, C2, D1, E1
Queue: A C D E
Generate: A3, C3, D2, E2
Write: A3, C3, D2, E2
Queue: D
Generate: D3
Write: D3
Queue: D
Generate: D4
Write: D4
```

This algorithm is fairer, but requires 5 writes to write all the frames.

Both algorithms suffer from the fact that that they don't know how much to write before hitting TCP congestion.

**Comment by sbordet** [comment]
@gregw now that's laid out above, I can see pros in the fairness, but cons in the number of writes.
Thoughts ?

**Comment by gregw** [comment]
@sbordet I think the number of writes is not a big problem, so long as they are not small writes.   ie enough to drive TCP/IP at full speed

**Comment by sbordet** [comment]
The final algorithm performs multiple generation passes but without generating all frames for the current entries - it stops after N complete passes over the entries when the number of bytes to write is large enough. It also remembers where the generation stopped and resumes from there the next generation.

```
Queue: A B C
Generate: A1, B1, C1, A2, B2
Write: A1, B1, C1, A2, B2
Queue: C A D E
Generate: C2, A3, D1, E1, C3, D2
Write: C2, A3, D1, E1, C3, D2
Queue: E D
Generate: E2, D3, D4
Write: E2, D3, D4
```
