### ISSUE TITLE
HTTP/2 and ALPN clients missing from distribution jar

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#237]
migrated from Bugzilla [#479706](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479706)
status NEW severity *normal* in component *client* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Project Inbox

On 2015-10-13 19:40:18 -0400, Zach Swasey wrote:

> The tarball released for distribution doesn't seem to include client libraries for ALPN or HTTP/2.
> 
> This URL: http://download.eclipse.org/jetty/stable-9/dist/jetty-distribution-9.3.3.v20150827.tar.gz
> 
> Under libs/http2 only includes http2-common, http2-hpack, and http2-server. No http2-client, or http2-http-client-transport.
> 
> Same with alpn. The distribution tarball is missing alpn-client.
> 
> Note: I put this in "Other" component, since it's not directly related to HTTP/2, but to the Jetty project's as a whole's distribution. If that's not correct, please re-assign.

On 2015-10-14 18:38:19 -0400, Zach Swasey wrote:

> Happens in latest 9.3.5 distribution tarball from 2 days ago as well.

On 2015-11-24 13:36:29 -0500, Zach Swasey wrote:

> 9.3.6 as well. Changing component to client as maybe that applies more.

**Comment by joakime** [comment]
The distribution doesn't have those clients, as the clients cannot be used from the webapps due to the webapp isolation layer.
