### ISSUE TITLE
Request cancellation listener for HTTP2

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#238]
migrated from Bugzilla [#479799](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479799)
status ASSIGNED severity _enhancement_ in component _http2_ for _9.4.x_
Reported in version _9.4.0_ on platform _All_
Assigned to: Simone Bordet

On 2015-10-14 17:51:41 -0400, Greg Wilkins wrote:

> Need a listener so application code can be cancelled if a HTTP2 request stream is closed or failed

On 2015-10-14 18:48:36 -0400, Simone Bordet wrote:

> Use cases are:
> A) for the server to be able to detect when a client is abruptly gone after having sent a processing-heavy request, in order for the server to interrupt the processing
> B) for the server to be able to receive a cancellation request from the client for a processing-heavy request
> 
> Proposed:
> 
> AsyncContext ctx = request.startAsync();
> ctx.addListener(new HTTP2AsyncListener()
> {
>     public void onCancel() // request cancelled by client via RST_STREAM
>     public void onClosed() // connection closed by client via GO_AWAY or abrupt
> });
> 
> This would solve the current issue of HTTP/1.1 where there is no way to detect if a client is gone (because we don't register for read interest when we are async - while HTTP/2 is always read interested because it's multiplexed).
> 
> It would also solve the issue of a client wanting to explicitly cancelling a request, a feature that HTTP/1.1 does not have (it has to be simulated by the application - typically send primary request, receive back a 102 or 202 response and then poll the server to know when the processing is finished, while cancellation is performed by an additional request referencing the transaction ID of the primary request).

On 2015-10-14 19:33:25 -0400, Greg Wilkins wrote:

> I have raised this on JSR369-experts: https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2015-10/message/25
> 
> I proposed a simpler extension to the existing ServletRequestListener API:
> 
> ```
> default void requestCancelled(ServletRequestEvent sre) {}
> ```
> 
> as I'm not sure there is any value in the app know the difference between a RST, GO_AWAY, PING timeout, IOException or even server shutdown.
> 
> I also think this can equally apply to blocking handling... perhaps even more so.  Thus I've proposed it on the existing ServletRequestListener API.

**Comment by sbordet** [comment]
The mechanics for this has been implemented in #824.

Unfortunately, Servlet 4.0 did not include a specific change in the API for applications to be notified of this event.
We notify such events to `AsyncListener.onError()`, but (obviously) only for async requests.

I guess this issue can be closed, as A) there is no Servlet 4.0 API for this and B) we do notify `AsyncListener.onError()`.

**Comment by victornoel** [comment]
@sbordet any idea if this was added to Servlet 5/6 and where? Cheers

**Comment by sbordet** [comment]
@victornoel what do you mean by "this", exactly?

HTTP/2 and HTTP/3 resets from the remote peer are notified to `AsyncListener.onError()`.
For HTTP/1.1 there is no such mechanism.

**Comment by victornoel** [comment]
@sbordet sorry, my question was confusing 😅 

You mentioned in your previous comment that "Servlet 4.0 did not include a specific change in the API for applications to be notified of this event", and I was wondering if Servlet 5 or 6 did? I would like to be able to be notified on this event, even for non-async requests.

I may be misunderstanding this but I was thinking that it would be useful to interrupt the thread processing the request in case the connection is closed by the remote peer (I didn't know this is only for HTTP 2/3, but I guess that's life).

My main use case would be to cancel long running blocking I/O on the server side when the client stops the request.

**Comment by sbordet** [comment]
@victornoel I am not aware that Servlet 4+ added any new APIs about this, so the answer is very likely no.

The current status in Jetty is that for HTTP/1.1 you won't know if the client closed the connection unless you read or write.

For HTTP/2 and HTTP/3, `AsyncListener.onError()` will be notified and you will be able to coordinate with your application to cancel other blocking I/O operations on the server.

**Comment by victornoel** [comment]
Ok, thank you for the explanation @sbordet! Does it make sense to open a ticket to support non-async requests?

**Comment by sbordet** [comment]
@victornoel you can certainly try, but in general the mechanism will be hard/impossible to implement for HTTP/1, so a generic API may be difficult to find (although there are HTTP/2/3 only APIs in Servlet to support HTTP/2 push).

FTR, the Jetty APIs already have such mechanism, via `Request.addFailureListener(...)`.

Perhaps it can be ported to `HttpServletRequest.addFailureListener()`, but then exactly specified that it is only called for non-async requests, etc.
You see how the matter becomes complicated very quickly, which makes agreeing on the new API quite difficult.

**Comment by victornoel** [comment]
> FTR, the Jetty APIs already have such mechanism, via Request.addFailureListener(...).

ha! then all the rest of the discussion is moot then, that's only what I was looking for, I don't really care about the Servlet API itself :) I got confused and conflated what's provided by the Servlet API and what is provided by Jetty's APIs.
