### ISSUE TITLE
Review Resource for potential immutable behavior

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2386]
There have been a number of issues throughout the years that have had multiple developers asking why the Resource layer is mutable in Jetty.

This is a Review issue to evaluate if we can move to an immutable Resource implementation.

**Comment by joakime** [comment]
A breakdown of the methods in [org/eclipse/jetty/util/resource/Resource.java](https://github.com/eclipse/jetty.project/blob/jetty-9.4.9.v20180320/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java)

Method | Immutable behavior | Notes
-------- | -------------------- | ---------
addPath(String) | yes |
close() | **no** | but this really a java.io.Closeable / java.lang.AutoCloseable requirement
copyTo(File) | **no** | used by quickstart, WebInfConfiguration.unpack, jetty-maven-plugin
delete() | **no** | **remove** - only used by tests
encode(String) | yes | Deprecated - should be **removed** in Jetty 10.x entirely
exists() | yes | 
finalize() | yes | should be **removed** in favor of AutoCloseable instead
getAlias() | yes | 
getAllResources() | yes |
getAssociate() | **no** | **remove** - not used
getFile() | yes |
getInputStream() | yes |
getListHTML(String, boolean) | yes | should not be here, **move to ResourceService** instead (only used there)
getName() | yes |
getReadableByteChannel() | yes |
getResource(String) | yes |
getURI() | yes |
getURL() | yes | Deprecated - should be **removed** in Jetty 10.x entirely
getWeakETag() | yes |
getWeakETag(String) | yes |
hrefEncodeURI(String) | yes | **remove** with getListHTML(String, boolean)
isAlias() | yes | 
isContainedIn(Resource) | yes |
isDirectory() | yes |
lastModified() | yes |
length() | yes |
list() | yes | should consider having a Iterable<String> instead, or even .forEach(Consumer<String>) function interface
release() | yes | Deprecated - the AutoCloseable behavior covers this - should be **removed** in Jetty 10.x entirely
renameTo(Resource) | **no** | **remove** - only used in test cases
setAssociate(Object) | **no** | **remove** - not used
writeTo(OutputStream, long, long) | yes | does not modify resource, is instead used to write resource contents to specific output stream

**Comment by joakime** [comment]
I think this is doable.

**Comment by joakime** [comment]
@gregw thoughts?

**Comment by gregw** [comment]
The mutability of the resource layer has always really been a horrid implementation detail due to the deficiencies of URL class.
Now a future FS based implementation may still need internal reference counting, but it may be that autocloseability may be sufficient to maintain that, but we would need to give the code base a good review, as every call to addPath will create a new resource that will need to be closed.

**Comment by gregw** [comment]
Your table of proposed changes LGTM.
We could also try deprecating entirely URLResource and just go forward with PathResource and/or FSResource.... (do we need an explicit ZipFS resource or would a generic FSResource be sufficient?)

**Comment by joakime** [comment]
I'm still keen on doing this.
