### ISSUE TITLE
improve async onError handling

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#239]
migrated from Bugzilla [#479903](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479903)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *unspecified* on platform *All*
Assigned to: Greg Wilkins

On 2015-10-15 23:50:29 -0400, Greg Wilkins wrote:

> Refactor the async calling of onError:
>  * avoid error dispatches unless there is an error page
>  * use a single sendError entry
>  * ensure contexts are correctly entered/dispatched for all callbacks
>  * better handle exceptions thrown from async callbacks

On 2015-10-15 23:53:01 -0400, Greg Wilkins wrote:

> Commit cfeee5c to master squashes all the work in progress from async_onerror branch

**Comment by gregw** [comment]
done in master for 9.4.x
