### ISSUE TITLE
Allow for optional "\u####" escaping in org.eclipse.jetty.util.ajax.JSON.toString()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2391]
https://tools.ietf.org/html/rfc8259#section-7

Mentions an optional (old school) behavior of escaping unicode with "\u####" notation.
We should allow for this kind of usage, but not default to it, as its a discouraged form of use.

https://tools.ietf.org/html/rfc8259#section-8
Makes it clear that JSON supports the UTF-8 spec cleanly.

If we do implement such a feature, it should be noted that 4+byte unicode usage is unsupported by the https://tools.ietf.org/html/rfc8259#section-7 (it only supports up to 3 byte encodings), so we should definitely throw an exception (of some kind) if this feature cannot be supported by the input string.

The JSON parser should probably also be updated to support this form of UTF-8 encoding.

**Comment by joakime** [comment]
The JSON object relied on the `QuotedStringTokenizer.quote()` which didn't handle the escaping properly.

Problems with `QuotedStringTokenizer.quote()`

* Doesn't escape `/`  (solidus) per Section-7
* Doesn't escape 0x7F (DEL) (probably a bug in QuotedStringTokenizer similar to Issue #2148)
* Doesn't escape beyond char 32 (decimal) (an intentional limit present in `QuotedStringTokenizer.escapes[]`, also that `escapes` should be limited to 31 decimal, and not include `' '` space at decimal 32)

**Comment by gregw** [comment]
We should probably review the usages of `QuotedStringTokenizer`, as it's an ancient class that was trying to do too many things and it's slowly has been replaced eg by `QuotedCSV`.   It would be good to get rid of it, perhaps moving some methods to StringUtil ?

**Comment by joakime** [comment]
So we have a JavaScript escaping behavior we need to mimic.

Note that per-spec, the "\u####" behavior is optional for escaping/encoding, and mandatory for decoding.
So I don't see any asymmetry here.

The QuotedStringTokenizer is too generic and we cannot apply JavaScript behaviors to it without impacting many many other users of that class.

They way I see it, we have (using [RFC 2119](https://tools.ietf.org/html/rfc2119) language) ...

1. Core JavaScript Required Escaping behavior.  - we MUST implement this correctly.
2. Optional 8-bit / UTF-8 Escaping behavior. - this SHOULD be configurable.
3. Recommended Escaping behavior. - we SHOULD implement this

Here's a breakdown ...

## Required Encoding - per various JSON spec

character | description
--------- | ----------
`"` | quotation mark
`\` | solidus
`/` | reverse solidus
`\b` | backspace
`\f` | form feed
`\n` | new line
`\r` | carriage return
`\t` | tab

All remaining characters from hex 0x00 through 0x19 (control characters) must be escaped with "\u00##" syntax.

## Optional Encoding - per various JSON spec

Any 8-bit+ character (including UTF-8) from hex 0x80 through 0x10FFFF into (1 or more) `\u####` escaped syntaxes

This means if we have a unicode codepoint consisting of multiple characters with surrogate pairs they might be encoded in multiple `\u####` pairs.

## Recommended Encoding - per real world lessons learned in other projects.

There are many JSON libraries/projects that have learned that other characters are subject to encoding/escaping as well.
These escape sequences are very common in the real world.

character | description | escaped form
--------- | ----------- | ------
0x7F | DEL character (unprintable 7-bit) | `\u007F`
`&` | ampersand should be encoded | `\&`
`'` | single quote character | `\'`

**Comment by gregw** [comment]
@joakime @sbordet my point is that we don't need to inject an encoder.  We only need to inject a decision on which characters to encode.
Very happy to take QuotedStringTokenizer out of the impl.

**Comment by joakime** [comment]
Current behavior is to honor the default JSON escaping spec. (even the oddball "solidus" escaping, which I think we'll remove).

The user can optionally override the `encodeUnicode(Appendable buffer, char c)` method to handle unicode their own way.

Example (from testscase):

https://github.com/eclipse/jetty.project/blob/5cab0ccd5fc68838939ea18018c1a4a1add25c4b/jetty-util-ajax/src/test/java/org/eclipse/jetty/util/ajax/JSONTest.java#L185-L197

The javadoc and default implementation for `encodeUnicode(Appendable buffer, char c)` looks like this  ...

https://github.com/eclipse/jetty.project/blob/5cab0ccd5fc68838939ea18018c1a4a1add25c4b/jetty-util-ajax/src/main/java/org/eclipse/jetty/util/ajax/JSON.java#L315-L335

**Comment by joakime** [comment]
Merged in commit ab9c3f5f1dedc4649f352e715861177f4584a3a0
