### ISSUE TITLE
Jetty 10 - split documentation guide

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#2394]
The documentation for Jetty has grown very large and unwieldy and it can be difficult to find the specific content folks are interested in. 

@WalkerWatch and I are investigating a better way of developing and presenting the documentation for Jetty 10. The initial branch commit will be doing the following:

- moving all individual content into a single topics/ directory organized by initial subject
- create administrative book framework
- create developer book framework
- create contribution book framework
- create index placeholder

Once we have this basic framework in place we are looking at testing out some assumptions regarding chunks of content or topics and how they can be both woven into the narrative context of each of these books while additionally building out an overall index of topics across the books which can be separately rendered into a page that can be easily consulted and let you drill down from there.

Initially I want to try and see if this index can be generated automagically using the existing toolchain but if that doesn't work out then it can take the form of a script that is run which processes the html output of the books and renders the appropriate index.

Additionally the current toolchain for rendering documentation involves the asciidoctor->docbook->html toolchain and we would like to validate in this effort if there is a path forward to completely remove the docbook translation layer and have asciidoctor->html achieve our goals.  Currently we have some custom xslt fobs that pull live source code examples from github and then highlights the code in the final output.

Finally we would like to be able to produce the documentation in PDF form once again and perhaps eventually epub and if we do that under the current documentation we produce a single 500 page book which is hefty.  If we can split the documentation from a narrative perspective into smaller books this becomes a more bite sized task.  It would be nice to be able to provide the community with this sort of content without massive overhead.

**Comment by jmcc0nn3ll** [comment]
@WalkerWatch I cobbled together the contribution guide as a sample document showing the structure I am largely thinking.  The root index.adoc contains references to chapters and those chapters have a determined order in their naming 1-*, 2-*, etc.  Those files themselves should be able to contain the glue that ties the individual topics into the narrative structure that is the individual book.  Any deep linking id's coming from these books should be prefixed with ag-*, dg-*, and cg-* (contributionguide-).  The topics themselves can have their linking changed over to t-* and perhaps t-<topic name>-* for convention purposes.  

Rendering wise, I wonder if we should continue to chunk the output of the books or if we should produce them as one large html file for each.  I kind of like the idea of producing single html files for each of the books and then additionally rendering reach topic under the auspices of the published index, with each topic having its own single html page.

**Comment by sbordet** [comment]
Asciidoctor only has chunking via DocBook, see asciidoctor/asciidoctor#626.
CometD's documentation is a single HTML file, and it's easy to search in the browser, but not sure how Google friendly a single HTML is.

**Comment by WalkerWatch** [comment]
Jesse, I like the structure so far. One question on them though. If I recall our conversation correctly, we want to write chunks in easily consumable bits. How far do we want this to go?  I ask because to achieve this, some existing pages will inevitably be broken up. This is fine, but I don't want to explode our documentation base into a ton of too small pieces. Sure, we can stitch everything together in the back-end, but doing this too much makes for frustrating formatting.

As for rendering, I like the idea of single HTML files if we can make it work nicely.

**Comment by sbordet** [comment]
What's the idea behind the split ? To target different groups of readers ?
What's "administrative" and what's "developer" ? Is there a clear line that can be drawn to separate the documentation ?
What's "contribution" ?

**Comment by jmcc0nn3ll** [comment]
That is actually fine @sbordet since my thinking is that the index is the part that we want want Google to index the most.  The thought on the index was to render out something akin to the old way we linked documentation in Jetty 6, 7 and 8 in the wiki's, a master page that listed out topics and let you quickly drill down to the item of interest.  The books would then be more useful for people who are broadly trying to come to terms with how the overall system works.

**Comment by WalkerWatch** [comment]
> What's the idea behind the split ? To target different groups of readers ?
> What's "administrative" and what's "developer" ? Is there a clear line that can be drawn to separate the documentation ?
> What's "contribution" ?

Yes, the focus is to curate content based on the needs of the reader. I think the terms of admin vs developer are relative to the mode of usage, that is, distribution vs embedded. As such, it is a lot easier to define and demarcate the differences. As for contribution, I think @jmcc0nn3ll 's point here was to store project-specific information, such as mailing lists, how to contribute, relevant project methodology...etc., though he can correct me if I am wrong. Still early days so lots can change.

**Comment by jmcc0nn3ll** [comment]
By way of example, the contribution book would largely be the current content under [Contributing](https://www.eclipse.org/jetty/documentation/9.4.x/advanced-contributing.html)

As for the clear line between the two, that is part of the impetus for the index.  It is hard sometimes to say X should be in one or the other which clouds the process in how to locate that content.  Right now we effectively force content into the sections of the monolithic book so that it exists somewhere in the rendering.  My goal is to make that process cleaner...all content has a home in the index and only the important bits in the books need be in the relevant book.

**Comment by joakime** [comment]
> What's "administrative" and what's "developer" ? Is there a clear line that can be drawn to separate the documentation ?

What about devOps? (that covers both)
If you follow stackoverflow.com (for developers) and serverfault.com (for administrators) you'll see there is no real distinction.

**Comment by WalkerWatch** [comment]
Just as a note, I -really- like the single page model that CometD uses for its [documentation](https://docs.cometd.org/current/reference/). The only thing I think I'd change is the ability to collapse the indexed topics.

**Comment by sbordet** [comment]
@WalkerWatch AFAIK Asciidoctor supports themes, so it would be possible to change the appearance via CSS customization.
See also asciidoctor/asciidoctor#699.

Also note that the current default theme is also good on mobiles: the TOC appears at the top, the rest below it.

**Comment by joakime** [comment]
@jmcc0nn3ll isn't this resolved already?

**Comment by sbordet** [comment]
This is resolved by the work in #3164.
