### ISSUE TITLE
MultiPartFormInputStream parsing should default to UTF-8, but allowed to be overridden by Request.setCharacterEncoding()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2398]
Currently, the default behavior of MultiPartFormInputStream correctly assumes UTF-8 for parsing.

However, there are scenarios where the user wants the section contents to be parsed in a different charset.

Take the following multipart body content ...

``` none
------WebKitFormBoundaryjJR29nbr1TDUu2yh
Content-Disposition: form-data; name="japanese"

Œ’Ž¡
------WebKitFormBoundaryjJR29nbr1TDUu2yh
Content-Disposition: form-data; name="hello"

ƒƒƒ†&#25094;ƒ^
------WebKitFormBoundaryjJR29nbr1TDUu2yh--
```

This was submitted via the form

``` html
<html>
<head>
<meta charset="utf-8">
</head>
<body>
    <h1>Form SJIS</h1>
<form accept-charset="shift-jis"
      method="POST"
      enctype="multipart/form-data"
      action="/capture/sjis-form">
    <p>Japanese</p>
    <input type="text" name="japanese" value="健治"/>
    <p>Hello</p>
    <input type="text" name="hello" value="ャユ戆タ"/>
    <p></p>
    <input type="Submit" value="Capture">
</form>
</body>
</html>
```

The key is `<form accept-charset="shift-jis">`

That makes the form part contents `shift-jis` in the charset.

If the developer is aware of this, and makes their servlet do the following ...

``` java
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
    {
        req.setCharacterEncoding("Shift-JIS");
        String japanese = req.getParameter("japanese");
        // process the value
    }
```

I would hope that could be allowed.
But I don't know how to apply that correctly.
For example, what would happen if the user did this instead ?

``` java
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
    {
        req.setCharacterEncoding("UTF-16"); // 2 bytes per char, but what about the query and multipart headers that are not 2 bytes per char?
        String utf16string = req.getParameter("a_multipart_name_that_points_to_utf16_body_content");
        // process the value
    }
```

One case that I don't know what to do with would be what if the `Content-Type` has a `charset` too?

Example:

``` none
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryD4GyXQgjBRmK3aBz; charset=shift-jis
```

Is that possible?

**Comment by lachlan-roberts** [comment]
@joakime there were changes made in Request.getParts() so that the charset used for a part will be:
```
1. use the charset in the parts content type; else
2. use the default charset set in the _charset_ part; else
3. use the default charset set in the request.setCharacterEncoding; else
4. use UTF_8
```

**Comment by joakime** [comment]
That search order works for me.

Some minor niggles for documentation reasons ...

1. Use the part specific charset as provided in the part Content-Type header; else
2. Use the overall default charset.  Determined by:
  a. if part name `_charset_` exists, use that part's value.
  b. if the `request.getCharacterEncoding()` returns a value, use that.  (note, this can be either from the `charset` field on the request `Content-Type` header, or from a manual call to `request.setCharacterEncoding()`)
  c.  use `utf-8`.

**Comment by joakime** [comment]
Do we need to document that the charset behavior is for the part value only? and not the part header/field names?

**Comment by lachlan-roberts** [comment]
Good idea @joakime but as I don't have commit privileges, and this is not really worth a pull request could you do a commit for this.
