### ISSUE TITLE
allow --add-to-start to  specify maven repository location

### ISSUE THREAD

**Issue by belerweb** [eclipse/jetty.project#2403]
When use --add-to-start( example: "--add-to-start=logging-logback") , start.jar will download dependencies from maven central repository. But sometime or some network access maven central repository smoothly.

So consider allow user to specify the maven center (mirror) location according arguments.

**Comment by olamy** [comment]
sounds interesting to implements or at least a parameter to override base uri which is http://central.maven.org/maven2/ (doh a http url and not https :-) )

**Comment by olamy** [comment]
all done

**Comment by olamy** [comment]
@joakime typo fixed with pr #2480
