### ISSUE TITLE
Allow overriding of DefaultServlet SC_NOT_FOUND behavior for subclasses

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#241]
migrated from Bugzilla [#480130](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480130)
status NEW severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.2.13* on platform *PC*
Assigned to: Project Inbox

On 2015-10-19 10:54:37 -0400, Martin Karpisek wrote:

> Hi,
> proposal for DefaultServlet implementation:
> 
> Use case:
> - in embedded Jetty we are using DefaultServlet
> - we want to reuse default servlet implementation as is (which behavior is fine for nearly all time)
> - in addition, in case standard default servlet logic do not find any resource (currently will send SC_NOT_FOUND), we want to plug our own additional logic (fallback - fetch resource from other store or possibly send SC_NOT_FOUND if not available also elsewhere)
> 
> Something like to extract from doGet
> response.sendError(HttpServletResponse.SC_NOT_FOUND);
> into separate protected method allowing subclasses to perform additional actions before sending definitive SC_NOT_FOUND
> 
> Thank you
> Martin

**Comment by joakime** [comment]
This can be accomplished with a custom Error handling page linked to the 404 status code.
Closing
