### ISSUE TITLE
Websocket error 200

### ISSUE THREAD

**Issue by Maka1795** [eclipse/jetty.project#2410]
I have created a WebSocket in Java, and when I start Jetty (version 9.4.9) on locahost:8080, i have an error of handshake, code 200. How can I resolve this bug?

**Comment by joakime** [comment]
Not enough information to work with here.

200 isn't a websocket code, that sounds like an HTTP 200 OK.
If true, that would means the request didn't upgrade to websocket.

How did you create the websocket?
How did you deploy and/or start Jetty?
If you used jetty-home (or the older jetty-distribution) what was your configuration like? (eg: did you enable the websocket module?)
If you used embedded-jetty, how did you setup your Server and Context (ServletContextHandler or WebAppContext)?
How did you test this connection? (browser? command line? other client?)

**Comment by joakime** [comment]
Closing due to lack of feedback.
