### ISSUE TITLE
Expose HTTP/2 LastStream error

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#242]
migrated from Bugzilla [#480139](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480139)
status NEW severity *enhancement* in component *client* for *9.3.x*
Reported in version *9.3.5* on platform *All*
Assigned to: Simone Bordet

On 2015-10-19 12:22:32 -0400, Hrvoje Ban wrote:

> From 480061 (thanks for fixing that!):
> 
> It would be very useful if I could in some way detect when connection was closed because of a GOAWAY frame when using Jetty HttpClient with HttpTransportOverHTTP2 - I could safely retry request if I know it was never handled by server.

**Comment by sbordet** [comment]
This is now implemented, along with the changes for #396.

Applications can override `HttpClientTransportOverHTTP2.onClose()` get the last stream id and check which HTTP request mapped to that stream in this way:

```java
Request request = ...
ContentResponse response = request.send();
Stream stream = (Stream)request.getAttributes().get(HTTP2Stream.class.getName());
```

If `stream` is `null` it means that the request was not even sent to the server.
