### ISSUE TITLE
Review BufferUtil.isMappedBuffer()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2425]
In Java 11, `BufferUtil.isMappedBuffer(ByteBuffer)` does not work anymore.

It was performing a check for `ByteBuffer.isLoaded()` that throws an `UnsupportedOperationException` is JDK < 11, but does not anymore in JDK 11.

Since there is no easy way to detect whether a buffer is direct or mapped, we should review also the usage of `BufferUtil.isMappedBuffer(ByteBuffer)` in `CachedContentFactory.CachedHttpContent.invalidate()` - the only place where it is used.

**Comment by sbordet** [comment]
@gregw why do we need this distinction between mapped and direct buffers in `CachedContentFactory.CachedHttpContent` ?

If we really need it, I think it's best to add a new field `_mappedBuffer` and treat mapped buffers differently from direct - a bit more code but working for any JDK.

**Comment by sbordet** [comment]
Note also that `ResourceCacheTest.testResourceCache()` fails because of this behavior difference in JDK 11.

**Comment by gregw** [comment]
Mapped buffers do not consume heap or kernel space thus they do not count towards the total cache size

**Comment by joakime** [comment]
Strange that the javadoc doesn't indicate this UnsupportedOperationException ...

https://download.java.net/java/early_access/jdk11/docs/api/java.base/java/nio/MappedByteBuffer.html#isLoaded()

**Comment by joakime** [comment]
Why are we not paying attention to the return `boolean` on `MappedByteBuffer.isLoaded()` ?

**Comment by sbordet** [comment]
@joakime because we rely on the fact that it throws `UnsupportedOperationException`.
Which does not in JDK 11.

@gregw if that's fine for you, I will add the `_mappedBuffer` field in `CachedContentFactory.CachedHttpContent` and get rid of `BufferUtil.isMappedBuffer()`.
