### ISSUE TITLE
SessionInactivityTimeout does not stop upon expiration

### ISSUE THREAD

**Issue by blop** [eclipse/jetty.project#2427]
Hello,

It seems the SessionInactivityTimeout keeps running, and calling onIdleExpired() multiple times even when the session inactivity timer expired.

I think onIdleExpired() should stop the timer from running again, as the session can only expire once.

Currently it keeps calling getSessionHandler().sessionInactivityTimerExpired() but for nothing because session has already been added to _candidateSessionIdsForExpiry.

Thanks!

**Comment by janbartel** [comment]
When the inactivity timer goes off, the session should join the  queue of sessions to be scavenged, and ultimately deleted.   This requires that the Housekeeper is configured. 

Assuming you have a Housekeeper, are you saying that the session is never scavenged, or just that the timer keeps going off while it's waiting to be scavenged?

**Comment by blop** [comment]
Yes, the timer keeps going off while it's waiting to be scavenged.
I think it could stop when the session has been marked for scavenging.

**Comment by janbartel** [comment]
Fixed in jetty-9.4.10
