### ISSUE TITLE
NullSessionCache prevents cleaning up old session from SessionDataStore

### ISSUE THREAD

**Issue by blop** [eclipse/jetty.project#2428]
Hello,

Currently NullSessionCache forces the use of the EVICT_ON_SESSION_EXIT eviction policy.
I'm not sure why ?

This as some bad side effect as AbstractSessionCache.put() is always marking the session as resident=false. And calling doDelete() but NullSessionCache does nothing.

That resident flag that is also used in SessionInactivityTimeout.isOpen().
And the isOpen() is checked in IdleTimeout.checkIdleTimeout().

This means that when using the NullSessionCache, the SessionInactivityTimeout.onIdleExpired() is never called, and session is never added to the candidates for expiry in SessionHandler.sessionInactivityTimerExpired().

So NullSessionCache is not compatible with inactivity eviction.
But this also means that session are never removed from the SessionDataStore, which is a bigger issue.

I guess no one is using that NullSessionCache, but then why providing it ?

The main goal of using it was to disable caching, as we are using the HazelcastSessionDataStore(Factory) which already keeps everything in memory for us.

Thanks.

**Comment by janbartel** [comment]
As the null cache does not store sessions in memory the eviction policy is naturally to evict. 

Other session data stores implement the ability to check for  expired sessions that are not known to the session cache, but hazelcast and infinispan session data stores don't have that ability. There is already an open issue to add that ability to them. In the meanwhile you can set a timeout on the life of the object with infinispan and I assume hazelcast has a similar feature. The only downside with that is that session listeners will not be called when the session times out.

We'd be happy to accept a pull request to add that feature to the hazelcast and infinispan session managers.

**Comment by janbartel** [comment]
I'm going to close this issue, as the failure to clean up the session does not lie with the NullSessionCache, but more likely the already-known problem with Hazelcast and Infinispan #2140.
