### ISSUE TITLE
Consider classloader caching

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#243]
migrated from Bugzilla [#480258](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480258)
status NEW severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.3.5* on platform *All*
Assigned to: Project Inbox

On 2015-10-20 17:02:01 -0400, Greg Wilkins wrote:

> Some application frameworks make heavy usage of classpath resource searches that have frequent not found results.   This can result in slow performance due to contention and the time taken to determine a resource is not present.   Caching not found results has been shown to improve performance on such applications.

**Comment by joakime** [comment]
Commit c0e6e66b49831a26307b73b678cf5c385b69a912 added this feature
