### ISSUE TITLE
did jetty-8.1.16 web server  support to  listening ipv6 address??

### ISSUE THREAD

**Issue by hongxiaomao** [eclipse/jetty.project#2433]

**Comment by sbordet** [comment]
Jetty 8 is end of life, you should upgrade to Jetty 9.4.x.

Yes, Jetty 8 supports listening to IPv6 addresses, as long as the JVM and the OS are configured properly.
There is typically nothing special to do, if IPv6 is supported at the OS level, the JVM will support binding and listening to IPv6 addresses.

**Comment by joakime** [comment]
It was very preliminary work back then.  
There's probably some features that don't work quite right.
eg: IP Access Controls, Host Header Parsing, Proxy Header Parsing, Virtual Host configs, etc ...
