### ISSUE TITLE
Test failure: org.eclipse.jetty.hazelcast.session.client.ClientSessionScavengingTest.testClusteredScavenge()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2440]
Failed in:
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/179/

Also seen failing in various `jetty-9.4.x-jdk11` builds.

**Comment by olamy** [comment]
should be fixed with b90f6de54ee292639e0614a0da2c7627331c8dbd
