### ISSUE TITLE
Add HttpServletRequest support to DefaultCallbackHandler

### ISSUE THREAD

**Issue by sconnall2** [eclipse/jetty.project#2445]
We would like to access the current session in our custom login module which would require adding the HttpServletRequest or the like to the DefaultCallbackHandler where we currently grab the username and password object.

**Comment by jmcc0nn3ll** [comment]
@janbartel this is the issue for what we were chatting about last week

**Comment by janbartel** [comment]
@sconnall2  please take a look at the branch I've just pushed called "jetty-9.4.x-2445-defaultcallbackhandler".  There is a new callback, the o.e.j.jaas.ServletRequestCallback. If your LoginModule adds that callback, then you can access the current request as a ServletRequest. You can cast it as necessary to HttpServletRequest.

**Comment by sconnall2** [comment]
Jan, thanks for the quick response to this. I really appreciate it.  The code looks good and I will test it out as soon as possible.

**Comment by sconnall2** [comment]
I just tested the code and everything is working perfectly. Thanks!

**Comment by sconnall2** [comment]
When is 9.4.10 going to be officially released?

**Comment by WalkerWatch** [comment]
@sconnall2 We do not have a definitive date yet, but the team is hoping to have it available over the course of the next few weeks.

**Comment by sconnall2** [comment]
Sounds good. Thanks for the update.

**Comment by janbartel** [comment]
Fixed, closing.
