### ISSUE TITLE
Support Unix Domain Sockets

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#245]
migrated from Bugzilla [#480827](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480827)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.4.0* on platform *All*
Assigned to: Greg Wilkins

On 2015-10-28 00:39:09 -0400, Greg Wilkins wrote:

> Support Unix Domain sockets for local connections for all protocols

**Comment by gregw** [comment]
done
