### ISSUE TITLE
Getting java.util.concurrent.TimeoutException in Jetty

### ISSUE THREAD

**Issue by Pratibha24** [eclipse/jetty.project#2450]
Hi,

I am trying to connect to Twitter backend using Jetty 9.4.8 version but getting the java.util.concurrent.TimeoutException exception.
In case of failure response, it works and returns the response like 401 Unauthorized , but in case of Successful response it gets hanged and timed out.
@joakime  @sbordet 
Thanks,

**Comment by sbordet** [comment]
@Pratibha24 as explained in #2143, you are probably not using the Twitter endpoints correctly.

**Comment by sbordet** [comment]
@Pratibha24 you have yet to provide any evidence of what you're saying.
Do you have the code _and_ the DEBUG logs for both the sync and async cases ?

**Comment by Pratibha24** [comment]
@sbordet , What i suspect is when we were using Jetty 7.6.5, for that implementation we were using waitForDone() along with all the callbacks.
I have put a debug point and found that after waitForDone() execution, it calls multiple times onResponseContent() and twitter then sends data in chunks for "HttpStreaming" and if there is no data present then it keeps sending empty data.

But in case of latest jetty, if i simply do req.send(), then it gets stuck there only, may be due to large data or because this exchange keeps happening and never completes (since it continuously streams data). req.send() checks only for response status or waits for complete data as well?

**Comment by sbordet** [comment]
@Pratibha24 so your _problem_ is: you want to call a Twitter API that returns a stream-like response that never ends, and you want to get notified every time you have new content ?

Is that a correct statement of your problem ?

**Comment by Pratibha24** [comment]
yes correct. Is it possible using blocking apis?

**Comment by sbordet** [comment]
It's not possible using the blocking APIs because they will wait for the response to finish, and it never does.
You can do it in this way:
```java
httpClient.newRequest(...)
        .onResponseContent((response, content) -> {
            // Your code here.
        })
        .send(null);
```
After `send(null)` the thread will not block. If you want to block after the send, until somehow the response ends, you can do it in this way:
```java
CountDownLatch latch = new CountDownLatch(1);
httpClient.newRequest(...)
        .onResponseContent((response, content) -> {
            // Your code here.
        })
        .send(result -> latch.countDown());
//latch.await(); // Waits forever
latch.await(30, TimeUnit.MINUTES);
``` 
What above was already explained in [this section of the documentation](https://www.eclipse.org/jetty/documentation/current/http-client-api.html#http-client-async).

**Comment by Pratibha24** [comment]
@sbordet , Thanks a ton! I was not aware of the countDown concept of it.
I will try it out and let you know if any further challenges comes. :+1:  :1st_place_medal:

**Comment by Pratibha24** [comment]
@sbordet , yes , it is working now as expected. Thanks alot for your help :) You may close this issue.
