### ISSUE TITLE
Request Accept-Encoding order is not used for DefaultServlet precompressed lookup

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2457]
(Issue discovered during conversion of tests in Issue #2431)

If you have the files ...

```
/data.txt
/data.txt.br
/data.txt.gz
```

And an incoming request ...

```
GET /context/data0.txt HTTP/1.1
Host: localhost:8080
Accept-Encoding: br, gzip
```

You will get the gzip content as the response.
I would have expected that the `data.txt.br` would be returned first.

**Comment by gregw** [comment]
I think this is by design see aa8597c
Specifically "Sort equal quality accept-encoding values based on server configured preference" #507
If the browser wants to preference `br` over `gzip`, then it needs to provide `q` parameters:
```http
GET /context/data0.txt HTTP/1.1
Host: localhost:8080
Accept-Encoding: br;q=1.0, gzip;q=0.9
```

This is tested for in `testDefaultBrotliOverGzip`
