### ISSUE TITLE
Deprecate jdk9 and jdk10 builds once jdk11 is officially released.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2458]
We currently build / test on ...

jdk8,
jdk9,
jdk10,
jdk11

Once the release of jdk11 is official, we should deprecate the jdk9 and jdk10 builds and only support jdk8 and jdk11.

**Comment by kant111** [comment]
That's interesting! may I know why?

**Comment by joakime** [comment]
jdk11 is an LTS release.  Once it goes official, older non-LTS releases go out of service.

Eg: jdk10 is out now. it's not LTS, but jdk9 is already deprecated and in "archive" status on oracle.com.

**Comment by kant111** [comment]
Got it!

**Comment by joakime** [comment]
Fixed in commit 5a17a33045ee5865314889b2c3695bdd2ec0e497
