### ISSUE TITLE
central.maven.org is no longer valid

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#2472]
currently it's http://central.maven.org/maven2/ we need to use https://repo.maven.apache.org/

**Comment by gregw** [comment]
We appear to be trying to get maven artifacts from https://central.maven.org/ which does not exist!!

**Comment by gregw** [comment]
We also need an integration test to check that we can fetch at least one dependency from maven

**Comment by joakime** [comment]
@WalkerWatch @jmcc0nn3ll looks like the default download page at https://www.eclipse.org/jetty/download.html needs to be updated too.

**Comment by joakime** [comment]
@WalkerWatch also, our documentation uses central.maven.org a ton. we need that updated as well.

**Comment by joakime** [comment]
There are multiple valid URLs now.

* https://repo1.maven.org/maven2/ - what exists in the maven super-pom (https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Super_POM)
* https://repo2.maven.org/maven2/ - a mirror of repo1.maven.org (in Europe i think)
* http://uk.maven.org/maven2/ - Official European Mirror or repo1.maven.org
* https://repo.maven.apache.org/maven2/ - a very common address seen around the web

@olamy we should be using the same URL as the official maven super pom (repo1.maven.org), not (repo.maven.apache.org).

**Comment by joakime** [comment]
Whoop.

Looks like maven 3.0.4 (at least) changed the main repo url ...
http://maven.apache.org/ref/3.0.4/maven-model-builder/super-pom.html

To https://repo.maven.apache.org/maven2/  (like @olamy is using already)

**Comment by joakime** [comment]
We should consider implementing Issue #149 now as well (to make SSL verification lenient)

**Comment by joakime** [comment]
I think we should use the canonical url at https://repo1.maven.org/maven2

See: http://central.sonatype.org/pages/consumers.html

**Comment by olamy** [comment]
LGTM :-)

**Comment by WalkerWatch** [comment]
I've updated all the links on the website. Looks like @olamy hit the documentation references on his branch/pr.

**Comment by jmcc0nn3ll** [comment]
Ideally, we can see the central.maven.org certificate thing sorted out ASAP and then make a more deliberate push to clean up these references and add that mirror feature @joakime mentioned.

**Comment by jswank** [comment]
I'll throw in some additional Sonatype perspective: if you desire to use SSL (excellent!), use https://repo1.maven.org or https://repo.maven.apache.org. These are the documented & functional SSL endpoints since Central began supporting SSL.  I'll point out that there are some challenges in supporting legacy Java SSL clients with modern TLS server deployments, so you may want to take that into consideration. 

Additionallt, there are a number of legacy URLs available via HTTP and there is no intent to remove or change that.  The URL used by your project- http://central.maven.org- is one of those.

**Comment by jmcc0nn3ll** [comment]
Actually, we do have a broken public release, 9.4.10 is broken for installing modules that use the maven:// reference

java -jar ../start.jar --add-to-start=session-store-infinispan-remote

That will trigger this issue.  But it is restricted to this release and is isolated to modules that leverage this mechanism to retrieve files.

I don't think anything is required on the Sonatype side to fix this, this is our screw up for that release and we'll get new releases out with this fix soon, and there is a CLI option that will allow people to bypass the issue if need be on this release.

Thanks for the help @brianf and @jswank!  Your quick response is very welcome!

**Comment by joakime** [comment]
Closing as fixed by @olamy and @gregw
