### ISSUE TITLE
Permanently elevated server thread counts after upgrade to 9.4.9

### ISSUE THREAD

**Issue by nicktrav** [eclipse/jetty.project#2478]
We've been noticing that after upgrading to 9.4.9, the thread counts for the pools used by Jetty remain elevated after an initial spike in load.

Concretely, if we start a server with, for example, a `ThreadPoolExecutor` with 300 core threads and a max pool size of 300, in releases _prior_ to 9.4.9, we'd see 300 threads created initially when running a load test, which would then be reaped after the keep alive time for the executor.

Compare this to the behavior in 9.4.9, which does not seem to allow the threads to be reaped. This is problematic for us, as we have large thread pools to allow for spikes in load, and typically the threads are reaped when idle for a period of time.

Here's an example thread count from YourKit when running a loadtest with a keep-alive time of 20 seconds in 9.4.8:

<img width="684" alt="screen shot 2018-04-24 at 12 46 37 pm" src="https://user-images.githubusercontent.com/804457/39210501-c394f4d2-47bd-11e8-822f-19c6b35e166a.png">

And in 9.4.9 (I can let the test run, and the thread count remains elevated):

<img width="689" alt="screen shot 2018-04-24 at 12 46 44 pm" src="https://user-images.githubusercontent.com/804457/39210509-c9f42bf4-47bd-11e8-98e6-869e22925ce5.png">

As a further datapoint, we only seem to notice this when creating _new_ connections in the loadtest (i.e. we don't see this when we re-use the connections to send load).

When bisecting the changes between the two releases, it looks like https://github.com/eclipse/jetty.project/commit/2067eac701799d4f545129f8b96350df030049c2 is the commit that introduced this change in behavior.

If I was to guess what might be happening here, it looks like `CreateEndPoint` and `DestroyEndPoint` both run directly on the executor, whereas before there were submitted to the executor. So perhaps the current implementation is continually "touching" threads, and resetting their keepalive timers, whereas previously, the tasks were scheduled on the executors, and the underlying pool was smart enough to schedule tasks on threads that was most recently active, allowing older threads to be reaped.

I've pushed what I believe to be a minimal reproducer to [this branch](https://github.com/nicktrav/jetty.project/tree/nickt.jetty-thread-test). I've branched from the commit _prior_ to where the issue was introduced, added my change, and then the commit with the issue, so it's easier to go back and forth by a commit to see the change in behavior.

For the load test I used [`vegeta`](https://github.com/tsenart/vegeta), with the following target file:

```
$ cat target.in
HEAD https://localhost:1338/foo
```

and invocation:

```
$ vegeta attack -insecure -targets target.in -rate 50 -connections 50 -output out
```

**Comment by sbordet** [comment]
FTR, we changed the behavior of `CreateEndPoint` and `DestroyEndPoint` multiple times between  running them and executing them.
We eventually settled on the current behavior of executing them for two reasons: they may call application code that may block (it would be bad if they were to be called from the selector thread) and with HTTP/2 there may be selector thread starvation if `CreateEndPoint` is run from the selector thread.

> we don't see this when we re-use the connections to send load

Your analysis is correct.
Using a HTTP/1.0 (i.e. open, request, response, close) is typically not resembling real traffic.

The question then becomes whether you indeed have this kind of HTTP/1.0 traffic shape.

If you don't, then you have a load test that tests a bogus case and yes, it has the behavior you see.
Will not happen in real life.

If you do, then I'd like to hear more about it, and we can discuss.

**Comment by gregw** [comment]
@nicktrav thanks for the detailed analysis... 

Are you saying that your thread count never goes down even if there is no load, or that a very small load is able to keep all the threads busy enough to never age out?

**Comment by gregw** [comment]
So I have been unable to reproduce with http rather than https. Running your server with vegeta client I see:
 - Initial spike to 26 while starting server
 - falls to 18 while idle
 - once load is applied there is a spike to 28, a fall another spike to 24 then falls to 20 and stays stable
 - removing load causes a small spike to 21, then a fall to 20
 - re applying load gives a small spike to 23, then fall to 20
![screenshot from 2018-04-25 08-50-35](https://user-images.githubusercontent.com/70829/39218018-c676b9d0-4865-11e8-9b15-3aaff62072fb.png)

Will now try with ssl...

**Comment by nicktrav** [comment]
@gregw - cheers. It's the latter; a very small load (in this case it was 50 QPS across 300 threads) is able to keep all the threads busy enough to never age out. This is different behavior to 9.4.8, where they did age out back to a pool size of ~15.

@joakime - macOS 10.13.2 (17C205), running jdk1.8.0_162. I've seen this in Java 9 and Java 10, as well as on Linux in our deployed environments (CentOS).

**Comment by nicktrav** [comment]
@gregw - I also didn't attempt this with vanilla HTTP, as we don't run anywhere without HTTPS as far as I know. I'll try that test case too.

**Comment by nicktrav** [comment]
For completeness, if we have no load on the server then the threads _are_ reaped, as you'd expect. 

That part is fine, although we're never really going to have that situation in our deployed environments, there's alway enough of a trickle of load balancer and healthcheck requests on new connections that "tickle" the threads in such a way that none of them can be reaped and we have the "pegged thread pool" situation. That said, only ~15 of them are ever active.

**Comment by gregw** [comment]
I'm also not reproducing with https?   Note that I am running against the HEAD of jetty-9.4.x, but I can't think of anything that we've changed in this area since 9.4.9...
![screenshot from 2018-04-25 09-03-05](https://user-images.githubusercontent.com/70829/39218333-85654914-4867-11e8-9c57-1d2a9f5a8378.png)

**Comment by nicktrav** [comment]
I did the same, and ran against the HEAD of 9.4.x, and I'm seeing the same elevated threads issue:

![screen shot 2018-04-24 at 4 16 19 pm](https://user-images.githubusercontent.com/804457/39218708-d9d8bca2-47da-11e8-9dd0-6b0f65a0380f.png)

I did have to update my pom.xml in my example to build against the new SNAPSHOT.

**Comment by gregw** [comment]
So I can't reproduce, but I think I can understand the situation.  It probably is a bit time/machine/tuning sensitive.   With the change 2067eac we do execute tasks a bit more frequently during accepting connections, so it may have pushed you into a goldie locks zone where there are just enough tasks to tickle the thread pool enough so it does not shrink.

Now a lot here depends on the design of your thread pool - Does it round robin tasks to all available threads or does it use them in a FIFO mode? Round robin can be more vulnerable to a low load keeping all your threads alive (1 request per second is enough to keep 20 threads alive with a 20s timeout).  You're using the JVMs `ThreadPoolExecutor`, which I'm not sure how it is implemented.    Can you perhaps try our `QueuedThreadPool`, just to see?  We still see some performance advantages with our thread pool... but it may not be immune from being pegged as it uses the the wakeup order on a queue lock to determine which thread goes next... which I think by default is unfair and thus kind of random... well I'm hoping that hot recent threads get preferenced over cold idle ones, but I don't know that for sure (and that is probably OS dependent anyway).

I have looked at this in the past and never really come up with a better design for the thread pool that does not slow down too much.    However, I have previously mused about regularly executing some kind of suicide job that causes the thread it is allocated to die regardless.... then the thread pool will have to grow again if it really needs it.      But let's see if we can nail down an precise cause before we muse about such work arounds.

**Comment by gregw** [comment]
At 500/500 rate/connections I see a peak to 97, then a drop to 33 steady state threads (https)

**Comment by nicktrav** [comment]
@gregw - my original graphs had 300 threads too. I haven't run with anything other than 50 connections for all of these tests.

My understanding of vegeta is that this basically implies 50 TLS setups per second, as I'm not re-using the connections.

**Comment by gregw** [comment]
At 1500/1500 load I see a spike to 313 threads, but then that falls to 31 steady state handling the load no problems at all!

At 2000/2000 I see rejected execution exceptions (why I don't like the ThreadPoolExecutor), which is effectively game-over for the server.  Far better to queue tasks rather than reject them... OK you risk OutOfMemoryException, but that needs lots and lots and lots of jobs and is no less fatal than RejectedExecutionException.... but that's another topic....

**Comment by gregw** [comment]
@nicktrav It is strange that 50/50 can drive your thread pool to 300 threads?   Let alone keep them!!!
So we definitely have something strange here on your machine(s).

**Comment by nicktrav** [comment]
@gregw - thanks for the comments so far! I'll try some VMs elsewhere and report back. We definitely see this on our Cent7 based boxes (`3.10.0-693.17.1.el7.x86_64`) too. Not just macOS.

**Comment by gregw** [comment]
@nicktrav give our QueuedThreadPool a go as well.    If you can see the problem with that, then we have more freedom to come up with a better way of shrinking it (eg regular suicide jobs), which we don't have with ThreadPoolExecutor.

**Comment by joakime** [comment]
Wow, Linux Kernel "3.10".  I don't have access to that ancient kernel, sorry. 

I've not had much success in replication yet.

Using vegeta 6.3.0.
Using golang 1.7.3.

on Fedora 25 (kernel 4.13.16-100.fc25.x86_64, Core i7)
on Fedora 27 (kernel 4.15.17-300.fc27.x86_64, Core i7)

Using Jetty 9.4.8, 9.4.9, and 9.4.x HEAD.
Using Default QueuedThreadPool configuration
Using HTTP plaintext default configuration
Using HTTPS default configuration
Using Java 8u171

So far, I'm getting similar results as Greg on the 50/50, 300/300, and 1500/1500 settings.

I'm adding OSX 10.12.6 (on Mid 2012 Core i7 2.6 Ghz) to this testing now.
I'll see if I can find an old copy of CentOS laying around that I can install and see if this is really just another kernel 3.x issue.

**Comment by joakime** [comment]
Just ran it on Windows 10 too. (An environment notorious for bad NIO behavior), and go the following results ...

``` shell
>C:\bin\vegeta.exe attack -insecure -targets target.in -rate 50 -connections 50 -output out -keepalive=false
```

Peak of 24 threads, steady state at 22.
Thread drop off back to idle state as expected.

``` shell
>C:\bin\vegeta.exe attack -insecure -targets target.in -rate 300 -connections 300 -output out -keepalive=false
```

Peak of 27 threads, steady state at 24.
Thread drop off back to idle state as expected.

``` shell
>C:\bin\vegeta.exe attack -insecure -targets target.in -rate 1500 -connections 1500 -output out -keepalive=false
```

Peak of 54 threads, steady state at 52.
Thread drop off back to idle state as expected.
This run didn't peak immediately, vegeta had a hard time ramping up to its full capacity, there was a stair-step up to the peak over the course of 2 minutes, then it settled down.
The networking statistics page shows that vegeta isn't sending the traffic at full capacity.
At 1500/1500 I'm showing vegeta only sending 604 kbps / reading 275 kbps.

Wiresharks shows that `-keepalive=false` isn't doing anything to change the `vegeta` behavior as we would expect, it opens a handful TCP connection and continually sends multiple requests on those connections.
Network Activity panel shows only 6 connections ever active for `vegeta` at the 1500/1500 configuration.

**Comment by joakime** [comment]
Some `vegeta` observations.

50/50, 300/300, and 1500/1500 all have 6 connections.
Using **no** `-keepalive` argument or using `-keepalive=false` results in the same behavior on Wireshark with regards to connection use: 6 connections established, connections not closed by vegeta, used for the entirety of the vegeta run.

The `-rate` argument doesn't do what you think it should do.

at 50/50 the rate is about 12 requests a second.
at 300/300 the rate is about 21 requests a second.
at 1500/1500 the rate is about 48 requests a second.

The server sits practically idle at about 7% cpu utilization.

**Comment by joakime** [comment]
Prior to today, I had never heard of the vegeta load testing tool.

**Comment by nicktrav** [comment]
Thanks @joakime - I might try and put together some kind of Docker container where this is easily reproducible on a given architecture / OS. Might make it a little easier to repro amongst us.

**Comment by joakime** [comment]
@nicktrav you might want to use a different (and more mature) load testing tool too.

**Comment by nicktrav** [comment]
I pushed another couple commits with two more Dockerfiles, one for each of Ubuntu (`4.9.87-linuxkit-aufs`) and Fedora (`4.9.87-linuxkit-aufs`).

Same issues with both. Interestingly, Fedora has a noticeably _better_ performance in terms of "threads created", before the commit that changes the behavior.

**Comment by gregw** [comment]
What branch did base your branch on?  You are >500 commits behind 9.4.x head and don't have the fix for the threadpool getMinSize issue..., so I'm getting a NPE when I run your docker file?
Out of time today to look more, might  be next week before I get another chance.

**Comment by cheister** [comment]
I can reproduce the problem on the latest SHA of the `jetty-9.4.x` branch.  I cherry picked the SHA from @nicktrav branch that has the ThreadCountRepro test onto the latest `jetty-9.4.x` and still see the problem,  the thread count never goes below 315 according to JConsole.  

Here is what I did to reproduce:

```
git checkout jetty-9.4.x
git pull
git cherry-pick 235a00bddf9c6a5b5395597b46a1af830029b04c
```

`git log` has
```
commit 235a00bddf9c6a5b5395597b46a1af830029b04c (HEAD -> jetty-9.4.x)
Author: Nicholas Travers <nickt@squareup.com>
Date:   Tue Apr 24 12:26:43 2018 -0700

    Minimal repro for elevated thread issue

commit 25888f0d838142f78152eacedc4d45a20d8381f4 (origin/jetty-9.4.x, origin/HEAD)
Author: Konstantin Lutovich <konstantin.lutovich@neotechnology.com>
Date:   Thu Apr 26 00:35:24 2018 +0200

    Fix NPE in PreEncodedHttpField constructor (#2488)
```

I had to modify `jetty-thread-test/pom.xml` to use the parent `9.4.10-SNAPSHOT`

created target.in
```
cat target.in
HEAD https://localhost:1338/foo
```

Then  `mvn clean package -am -pl jetty-thread-test -DskipTests=true` and run `org.ecplipse.jetty.threadtest.ThreadCountRepro` in IntelliJ.

Run `jconsole` and select the `org.ecplipse.jetty.threadtest.ThreadCountRepro` thread.

Thread counts starts at 25.

Run `vegeta attack -insecure -targets target.in -rate 50 -connections 50 -output out -keepalive=false`

Thread count goes up to 315 and for as long as vegeta is running.

**Comment by gregw** [comment]
@nicktrav @cheister  I've been able to reproduce and as far as I can tell, it is something funky going on with the `ThreadPoolExecutor` or perhaps our `ExecutorThreadPool` wrapper?
I followed @cheister steps and while I don't see how that could be different to what I did before, I do see 315 threads created and kept!

If I switch to the `QueuedThreadPool`, I only see 44 threads created and that just handles all the load.

I switched back to the `ThreadPoolExecutor` and then wrapped every task that was executed as follows:
```java
    final AtomicInteger running = new AtomicInteger(0);
    final AtomicInteger max = new AtomicInteger(0);
    
    @Override
    public boolean tryExecute(Runnable task)
    {
        return super.tryExecute(()->
        {
            try
            {
                int r = running.incrementAndGet();
                int m = max.get();
                while (r>m)
                {
                    if (max.compareAndSet(m,r))
                    {
                        System.err.println("max="+m);
                        break;
                    }
                    m = max.get();
                }
                task.run();
            }
            finally
            {
                running.decrementAndGet();
            }
        });
    }

    @Override
    public void execute(Runnable command)
    {
        super.execute(()->
        {
            try
            {
                int r = running.incrementAndGet();
                int m = max.get();
                while (r>m)
                {
                    if (max.compareAndSet(m,r))
                    {
                        System.err.println("max="+m);
                        break;
                    }
                    m = max.get();
                }
                command.run();
            }
            finally
            {
                running.decrementAndGet();
            }
        });
    }
  }
```
This reports max=38, yet the pools threads go to ~300.
Looking at those threads in the `ThreadPoolExecutor` with jvisualvm thread inspector, I see that they are mostly idle and stay idle and never get any tasks to run! So I have no idea why they don't age out!

So while I will investigate a bit more.... I highly recommend just using the `QueuedThreadPool`.  It is what we develop against, tune against, debug against, optimize for etc.  It's faster for our load tests than `ThreadPoolExecutor`, so I don't really know why you'd want to replace it.   It also looks to me like `ThreadPoolExecutor` can be tickled in some way to act very strangely!

**Comment by gregw** [comment]
There is definitely something very bizarre happening with the `ThreadPoolExecutor`, as I logged each time it increased it's current thread and you can see the last few increments here:
```
try max threads=296 SizedExecutorThreadPool[etp1867083167]@6f496d9f{STARTED,0<=297<=300,i=283,q=0,ReservedThreadExecutor@7d809f9d{s=7/8,p=0}}
try max threads=297 SizedExecutorThreadPool[etp1867083167]@6f496d9f{STARTED,0<=298<=300,i=284,q=0,ReservedThreadExecutor@7d809f9d{s=7/8,p=0}}
try max threads=298 SizedExecutorThreadPool[etp1867083167]@6f496d9f{STARTED,0<=299<=300,i=285,q=0,ReservedThreadExecutor@7d809f9d{s=7/8,p=0}}
try max threads=299 SizedExecutorThreadPool[etp1867083167]@6f496d9f{STARTED,0<=300<=300,i=286,q=0,ReservedThreadExecutor@7d809f9d{s=7/8,p=0}}
```
So when it allocated the 300th thread, it had 285 idle threads (plus 7 reserved threads).

So I'm guessing there is something wrong in how it is setup with:
```java
  private static final int CORE_THREADS = 300;
  private static final int MAX_THREADS = 300;
  private static final int THREAD_KEEPALIVE_SECS = 20;
...
    ThreadPoolExecutor executor = new ThreadPoolExecutor(CORE_THREADS, MAX_THREADS,
        THREAD_KEEPALIVE_SECS, SECONDS, new ArrayBlockingQueue<>(MAX_THREADS),
        (ThreadFactory) Thread::new);
```
So this set's core threads to 300, of which the javadoc says:
```
	 When a new task is submitted in method execute(Runnable), and fewer than corePoolSize threads are 
	 running, a new thread is created to handle the request, even if other worker threads are idle.
```
So it may be that threads are idling out, but this configuration will always create more thread to replace them!
If I set `CORE_THREADS` to 30, I get 44 threads in total.

So I think this is just a miss configuration of `ThreadPoolExecutor` (in part because of it's bizarre design).   Previously we used our eatWhatYouKill scheduler for creating new connections, so that would have mostly used our reserved thread pool of  threads already taken from the executor and thus we would not have tickled the strange starting of a thread even if you have idle ones!   Now we directly execute the new connections, resulting in a call to execute which does trigger the creation of a thread, even if there are idle ones available.

So I think this explains this issue, so I'm closing as I don't think there is anything we can do... other than say again - use QueuedThreadPool!

cheers

**Comment by nicktrav** [comment]
Thanks for persevering with us, @gregw! Glad we got a least one commit out of it ;)

We're doing some spring cleaning, and will take you up on the `QueuedThreadPool`. Thanks again.
