### ISSUE TITLE
Add ability to set configurations to apply to WebAppContext for jetty-maven-plugin

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#248]
migrated from Bugzilla [#481203](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481203)
status ASSIGNED severity *enhancement* in component *maven* for *9.3.x*
Reported in version *9.3.5* on platform *All*
Assigned to: Jan Bartel

On 2015-11-01 20:34:07 -0500, Jan Bartel wrote:

> The list of Configurations to apply to the JettyWebAppContext for the jetty-maven-plugin are hardcoded. 
> 
> Change this to a) use the Configuration.ServerDefault mechanism and also allow it to be explicitly overridden by a pom.

**Comment by janbartel** [comment]
Was fixed for jetty-9.3.6 and beyond.
