### ISSUE TITLE
Possible NPE in MemcachedSessionDataMapFactory

### ISSUE THREAD

**Issue by BenBE** [eclipse/jetty.project#2482]
When a null array of addresses is passed into MemcachedSessionDataMapFactory.setAddresses it is checked for not being null, but not properly acted upon:

https://github.com/eclipse/jetty.project/blob/fbbf5d2d2dc855b36de08a32f1c3653335e47dce/jetty-memcached/jetty-memcached-sessions/src/main/java/org/eclipse/jetty/memcached/session/MemcachedSessionDataMapFactory.java#L48

If a null value is present, the _addresses field is reset to null and reinitialized with an empty ArrayList, but the for loop crashes with a NPE encountering the null value.

**Comment by janbartel** [comment]
Thanks, fix applied.
