### ISSUE TITLE
Exception dropped instead of throwing it in jetty-ant

### ISSUE THREAD

**Issue by BenBE** [eclipse/jetty.project#2483]
At the two marked places a new RuntimeException is created, but not actually thrown. Instead it is silently garbage-collected. For the second case a stack trace is printed, but the overall exception is not acted upon:

https://github.com/eclipse/jetty.project/blob/fbbf5d2d2dc855b36de08a32f1c3653335e47dce/jetty-ant/src/main/java/org/eclipse/jetty/ant/ServerProxyImpl.java#L280
https://github.com/eclipse/jetty.project/blob/fbbf5d2d2dc855b36de08a32f1c3653335e47dce/jetty-ant/src/main/java/org/eclipse/jetty/ant/ServerProxyImpl.java#L285

**Comment by olamy** [comment]
closing as not sure we want to invest time in ant tooling.
