### ISSUE TITLE
What does the latency field measure in the Jetty request logs?

### ISSUE THREAD

**Issue by ruchimutneja** [eclipse/jetty.project#2492]
In our project
50th percentile of the requests is taking 50ms processing time.
And latency in jetty logs shows the same number.

As per [docs](http://www.eclipse.org/jetty/documentation/9.3.x/configuring-jetty-request-logs.html) `Latency is the amount of time it took the server to handle the request`

Our web application is getting thousands of requests per minute. The requests hit the AWS ALB which routes it out application. The application is running an embedded Jetty server (9.3.x). ALB logs shows the request took 1000ms to process. But the Jetty request log's latency field only shows 100ms. This corresponds with the application specific logs. I am trying to understand where did the remaining 900ms got spent. 

My original guess was that the requests must be getting queued at Jetty (configured with default thread pool). I expected the Jetty latency time to be closer to the ALB response times.

Does latency include waiting time as well?

**Comment by gregw** [comment]
@ruchimutneja The latency reported in the log is the time period as measured against the `System.currentTimeMillis()` from the call to `HttpChannel.onRequest(...)` to the call to log the request as the request is completed.

The `HttpChannel.onRequest(...)` call is made after: 
 - initial network selection
 - potentially some dispatch latency in the thread pool, although we can often handle without a dispatch.
 - reading the initial request bytes into a buffer
 - parsing the request bytes (either as HTTP, HTTP2, FCGI, etc.)

The log method is called from `onComplete`, which is after both request processing and flushing of the complete response.

Note that recent releases have a [HttpChannel.Listener](https://github.com/eclipse/jetty.project/blob/jetty-9.4.9.v20180320/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L1031) that can allows more detailed timings of phases of the request handling to be determined.   However it still does not allow a measure of the time from initial selection to request dispatch.

**Comment by gregw** [comment]
Note also that we do have [an example](https://github.com/eclipse/jetty.project/blob/jetty-9.4.9.v20180320/jetty-server/src/test/java/org/eclipse/jetty/server/ExtendedServerTest.java#L119) of how to record a much earlier timestamp against a request.  In this case it is the time at which the selector last called the endpoint prior to the parsing of the request line.     This is much closer to the first point in time that the server new of the request, however the time at which the selector exited from selection would be the most accurate.   Let's see what we can do to achieve that.... stand by...

**Comment by amithgeorge** [comment]
@jmcc0nn3ll the "issue" has been closed, but the issue still remains that we can't get actual latency from the jetty logs. @gregw seems to have attempted fixing it. Can the issue be reopened and kept open till we can get a resolution? This "issue" is not really a question, it is a feature request.

**Comment by sbordet** [comment]
@amithgeorge you *can* get the latency from the Jetty logs, only it's not the latency you want.
@gregw has explained how you can get the latency you want, but you will need to write a bit of extra code because you want to go deeper to cope with your case. 

In the original report by @ruchimutneja the hypothesis was that the 900 ms were queuing time inside Jetty.
However, have you verified that is not the client delaying the send of the content, or AWS delaying the send of the request, etc. ?

You have hypotheses to verify and means to get all the information from Jetty, with a bit of code on your part. If you need a new feature, you need to specify exactly what you want.

**Comment by gregw** [comment]
Note that going forward, I do wish to add a mechanism to access the select time, which would give the most accurate measure.  But we need to proceed with caution as this is sensitive parts of the code and small changes can slow the server greatly.

**Comment by joakime** [comment]
@gregw your `jetty-9.4.x-2492-request-latency` branch is still lingering around.
Also, isn't the work being done in branch `jetty-9.4.x-113-CustomRequestLog` (Issue #113) going to address this issue as well?

**Comment by gregw** [comment]
@joakime the custom request log does not really cover it.   The issue is really that we take a request timestamp after it has been parsed, when it would be interesting to know when the very first byte had been selected for the request.  However, I currently think that is too invasive to do and so I'm closing for now until we have a real need to drive the requirements.

**Comment by boyxgc** [comment]
I've encountered the same problem. Where my Dropwizard application has an average of 40ms latency that I cannot explain. After adding logs in a registered HttpChannel.Listener (pseudo implementation attached below). I found an average of ~40ms latency was spent between `onRequestBegin` and `onBeforeDispatch`. What does Jetty do during between these two states? My payload size is very small (80bytes).


##### HttpChannelListener in Jetty v9.4.11.x #######################################################################
```
private void registerHttpChannelListener(Environment environment) {
    environment
        .lifecycle()
        .addServerLifecycleListener(
            server -> {
              Arrays.stream(server.getConnectors())
                  .forEach(
                      connector -> {
                        if (!(connector instanceof ServerConnector)) {
                          return;
                        }
                        boolean successful =
                            connector.addBean(
                                new HttpChannel.Listener() {
                                  @Override
                                  public void onRequestBegin(Request request) {
                                    // log timestamp
                                  }

                                  @Override
                                  public void onBeforeDispatch(Request request) {
                                    // log timestamp
                                  }

                                  // more methods to implement
                        if (!successful) {
                          throw new RuntimeException("Failed to add event listener");
                        }
                      });
            });
  }
```

**Comment by sbordet** [comment]
@boyxgc

Between the `requestBegin` event and the `beforeDispatch` event Jetty is waiting for the request headers and the first chunk of request content.

Whether or not waiting for the latter can be configured via `HttpConfiguration.delayDispatchUntilContent`.

You can play with this configurable parameter and see how it goes, but likely it is the client delaying the send of the request content. That can be confirmed by a Wireshark network trace.

If it is the client that is sending the request content after a delay, either Jetty waits for it before dispatching, or you're going to wait in the application code in a blocking `read()`.
