### ISSUE TITLE
FileSessionDataStore: private save method

### ISSUE THREAD

**Issue by mdobrovnik** [eclipse/jetty.project#2495]
We are are beginning to switch from jetty 9.2.X to 9.4.9V20180320 (embedded). We would like to use the FileSessionDataStore to persist session data, the main reason being sessions to survive server restarts.

Whats somewhat peculiar (but unavoidable) in our application is the usage of Session.addAttibute() to add _nonserializable_ objects. This breaks saving the session. But those attributes are not essential for _persistent_ session semantics, so there is no need that they get written to the store.

In a jetty 9.2.X this has been handled via extending the _HashedSession_ and overriding the _save()_ method,  avoiding to write nonserializable session attributes. This has been working fine.

Since somewhere between 9.2 and 9.4, the session handling has changed, the _FileSessionDataStore_ has a _save()_ method that would be the place of choice to extend/override. Alas the _save()_ method is **private**, so there is no obvious extension point.

Overriding _doStore()_ in _FileSessionDataStore_ would be the next approach, but this is also suboptimal regarding separation of concerns.

From my (isolated) point of view it would be nice to be able to just override _save()_ (and maybe _load()_). 

Any opinions or suggestions?

**Comment by janbartel** [comment]
Have you tried implementing the passivation/activation listeners instead? When the session is about to be passivated you can remove the non serializable object, and then put I back when activate is called.

**Comment by mdobrovnik** [comment]
Many thanks for your suggestion (and for jetty at large of course).

No, i did not take HttpSessionActivationListener into account.

Since such nonserializable session attributes will be added by independent third party code (which has been doing so for quite some time), i cannot really require them to implement HttpSessionActivationListener.

Ok, i could add just one special session attribute just for the reason to implement HttpSessionActivationListener and to take care of all the problematic attributes).

I am still reluctant to do so because it would also lead to lots of unneeded/unexpected calls to _HttpSessionAttributeListener_.

**Comment by janbartel** [comment]
Well, the HttpSessionAttributeListener passivate/activate calls were designed for precisely this purpose, so ideally you would be able to use it.

However, that said, I have made the previously private methods protected on FileSessionDataStore, as we do want to make them amenable to subclassing. I think this change should be in time for 9.4.10 release.
