### ISSUE TITLE
Include accepting connections in connection limit.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2501]
Currently we have two mechanisms to limit the number of connections in the server:
 - [LowResourceMonitor](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java#L285) which samples several metrics including connection count, and can stop accepting if a threshold is exceeded.
 - [ConnectionLimit](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionLimit.java) which uses the `Connection.Listener` mechanism to enforce a hard connection limit.

However, neither of these mechanism includes connections that have been accepted, but not yet processed by [ManagedSelector$Accept](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L667).   So a large burst of new connections can be accepted before either mechanism kicks in to limit connections.

**Comment by gregw** [comment]
I think that the two mechanisms should be unified, so that LowResourcesMonitor will use a ConnectionLimit to listen for connections rather than poll for them.   This will reduce duplication and mean that we need to fix this problem only once.

**Comment by gregw** [comment]
I think the fix can be best implemented by added a `Connector.Listener` interface like:
```java
interface Listener extends EventListener
{
  onAccept(Channel channel);
}
```

There is no matching close event, but this should not be a problem as any count of accepting connections can be reduced by also listening for `Connection.onOpened`.  If this is leaky, then it may even be sufficient to periodically zero the accept count.

**Comment by gregw** [comment]
@sbordet @joakime

**Comment by joakime** [comment]
The LowResourcesMonitor specific issue was opened at #2508

**Comment by gregw** [comment]
On consideration, I don't think that simple interface will work to allow precise counting.  I think we will need:
```java
interface AcceptListener extends EventListener
{
  onAccepting(Channel channel);
  onAcceptFailed(Channel channel);
  onAccepted(Channel channel, EndPoint endPoint);
}
```

**Comment by gregw** [comment]
@WalkerWatch We have now merged this PR, so can you have check the documentation and update as necessary.   Simone did update some of the doco, but good to get that reviewed and checked.  The main changes that we have made are:

 - We have deprecated the connection limit in LowResourceMonitor, as it was only a soft limit
 - updated the connectlimit class/module to be more precise and to limit connections in the process of being connected.
 - added an acceptratelimit class/module that can control the rate at which new connections are accepted.
