### ISSUE TITLE
Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by schmitzli** [eclipse/jetty.project#2502]
We experience the error "Software caused connection abort: recv failed" on the client.
Our client server communication is using http servlet requests. The server has an embedded jetty.
We can "randomly" reproduce this error on Windows environments using local loopback connection (to eliminate hardware issues).
Our program is just doing defined requests over and over and runs into this issue roughly every 100.000 requests.

the environment:
Jetty 9.4.6 and also 9.4.9 and 9.4.10, but not 9.1.5
java 1.8.0_144 and also 1.8.0_172
Windows 10, Windows server 2012, we are unsure if this also occurs with linux servers, at least this specific client side error is not experienced

We found evidence in the jetty debug log when comparing the regular requests debug output to the problematic request.
We think the error is caused on the client because the server closed the connection, after aborting due to "unconsumed input".
For the problematic request we found that when parsing the request "addContent EOF" is not performed, 
caused by a seemingly incomplete state change sequence (missing TRAILER --> END).

When we tried to debug and determine what the "unconsumed input" might be we only found it empty.

The attached files are 2 debug logs for when the problem occurs.

Any help is greatly appreciated
Thanks and best regards
Stefan

[jetty_unconsumed_missing_eof_log_input_channel.log](https://github.com/eclipse/jetty.project/files/1970688/jetty_unconsumed_missing_eof_log_input_channel.log)
[jetty single client connection abort2.log](https://github.com/eclipse/jetty.project/files/1970689/jetty.single.client.connection.abort2.log)

**Comment by joakime** [comment]
What HttpClient are you using?

**Comment by joakime** [comment]
```
Line 760851: 2018-05-02T16:12:34.881	DEBUG	Idle pool thread	
     releaseRequestBuffer HttpConnection@5e9593db[p=HttpParser'{'s=CHUNKED_CONTENT,80 of 0},
     g=HttpGenerator@1183f6dc'{'s=END}]=>HttpChannelOverHttp@32415a6d
     '{'r=1,c=true,a=COMPLETED,uri=//127.0.0.1:5080/client/iiiCR}<-SocketChannelEndPoint@7e6627e2
     '{'/127.0.0.1:49514<->/127.0.0.1:5080,OPEN,fill=-,flush=-,to=1/30000}
     '{'io=0/0,kio=0,kro=1}->HttpConnection@5e9593db[p=HttpParser'{'s=CHUNKED_CONTENT,80 of 0},
      g=HttpGenerator@1183f6dc'{'s=END}]=>HttpChannelOverHttp@32415a6d'{'r=1,c=true,a=COMPLETED,uri=//127.0.0.1:5080/client/iiiCR}
Line 760857: 2018-05-02T16:12:34.881	DEBUG	Idle pool thread	
      abort HttpConnection@5e9593db[p=HttpParser'{'s=CHUNKED_CONTENT,80 of 0},
      g=HttpGenerator@1183f6dc'{'s=END}]=>HttpChannelOverHttp@32415a6d
      '{'r=1,c=true,a=COMPLETED,uri=//127.0.0.1:5080/client/iiiCR}<-SocketChannelEndPoint@7e6627e2
      '{'/127.0.0.1:49514<->/127.0.0.1:5080,OPEN,fill=-,flush=-,to=1/30000}'{'io=0/0,kio=0,kro=1}
      ->HttpConnection@5e9593db[p=HttpParser'{'s=CHUNKED_CONTENT,80 of 0},g=HttpGenerator@1183f6dc
      '{'s=END}]=>HttpChannelOverHttp@32415a6d'{'r=1,c=true,a=COMPLETED,
      uri=//127.0.0.1:5080/client/iiiCR} java.io.IOException: unconsumed input
```

That says your client was actively sending chunked data on the request body but the server side didn't read it all.
The server side servlet code stopped reading from the Request.getInputStream() and exited the servlet dispatch.
The server itself recognized this and attempted to finish reading the request body content input (consume all) as the connection was in an HTTP persistence state (no `Connection: close` and HTTP/1.1 being used).

Are you sure you are fully consuming the Request.getInputStream() before you exit the servlet?

**Comment by schmitzli** [comment]
On the client we are using url.openConnection(), i.e. sun.net.www.protocol.http.HttpURLConnection,
with con.setChunkedStreamingMode(0);con.setDoOutput(true);

>>Are you sure you are fully consuming the Request.getInputStream() before you exit the servlet?
Yes, in the servlet we read the input stream to its end, and log an error if anything is found.

**Comment by joakime** [comment]
Using ...

``` java
HttpURLConnection.setChunkedStreamingMode(0); // invalid
```

... will result in an undetermined state and/or behavior in HttpURLConnection as 0 is an invalid value.

If you don't want chunking, just don't call `setChunkedStreamingMode()` and then the default behavior kicks in (which will cache the entire contents written, set the `Content-Length` header on the request, and then start sending the request).

**Comment by joakime** [comment]
Also, don't downcast to `sun.net.www.protocol.http.HttpURLConnection` as that's invalid in many JVMs (even newer Oracle JVMs).

**Comment by schmitzli** [comment]
HttpURLConnection.setChunkedStreamingMode(0);
will use the default size which is 4096 in java.net.HttpUrlConnection

We do not cast to the implementation, i stated the exact class to answer the question which client we are using.

**Comment by joakime** [comment]
The server side code, are you reading the POST body contents via HttpServletRequest.getParameter*() calls? or HttpServletRequest.getPart() calls? or HttpServletRequest.getInputStream()?

**Comment by schmitzli** [comment]
we only use HttpServletRequest.getInputStream() to read from the request

**Comment by joakime** [comment]
@schmitzli i've added a ChunkedReadTest to attempt to replicate this and cannot produce the same results as you.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x-issue-2502-chunked-httpurlconnection/jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ChunkedReadTest.java

Can you modify that testcase to cause the issue you are seeing?

**Comment by schmitzli** [comment]
Thank you, we will try to reproduce with the test case.

Do you see a way how we could detect the situation in the servlet.doPost() implementation?
Perhaps we can get and check the HttpInputOverHTTP instance?

**Comment by sbordet** [comment]
@matthiaslarisch in your test case in #2510, the server does not read the content sent by the client.

Jetty sees that there is some content to be read, but the application does not want to read it.
At this point the only thing that Jetty can do is to abort the connection, otherwise it may be stuck reading content that the client never sends.

This behavior matches with what you originally saw ("unconsumed input").
Jetty has to protect itself from this case because it can be seen as an attack vector, so it closes the connection if it sees unconsumed request content that is not complete.

The fact that you see it only some times is due to the fact that if Jetty knows the content is finished (i.e. Jetty sees EOF for the request content), then it can just discard it.
However, if Jetty does not see the EOF it cannot wait for it and it closes the connection.
Depending on whether the EOF is arrived when the application returns control to Jetty you get different behaviors.

The solution is therefore for you to always read the content on the server, or don't bother if the connection is being closed by the server.

Please close the issue if this explanation is sufficient for you.

Thanks !

**Comment by schmitzli** [comment]
Hi, thank you for the explanation.
But the test case might be to extreme.
I think we have this issue also when reading the complete input stream in the servlet.
We'll try to modify the test case once more with input stream data and consumption.

**Comment by sbordet** [comment]
If you can reproduce when you completely read the request content, then we want to see the detailed logs.

**Comment by schmitzli** [comment]
We are not able to reproduce the issue with a testcase.
To solve our problems we do not use the chunked transfer mode for small requests anymore.

**Comment by joakime** [comment]
> To solve our problems we do not use the chunked transfer mode for small requests anymore

That still seems troublesome.
Small chunked transfers should be no different then large chunked transfers.
