### ISSUE TITLE
Expose more WebSocket details in JMX and Server Dump

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2504]
In light of the conversation in #2061 more information should be exposed about WebSocket in JMX and even the server dump.

Some initial thoughts ...

* Each WebSocket Server Container (either Jetty Native or JSR356) should be listed separately.
  * Max Message Size (TEXT / BINARY)
  * Idle Timeouts
  * Registered Potential Endpoints (url-pattern + creator / configurator / endpoint class)
    *  URI Template Variables (if using UriTemplatePathSpec)
* Each Client Container should be listed separately.
* The Sessions tracked within each Container should be accessible.
* Each Session details
  * In use Connection implementatino (jetty-io layer, identify type of connection)
  * Network EndPoints (jetty-io layer stuff, which endpoint impl)
  * WebSocket Endpoint (event handler in use, and user object/instance toString)
  * Negotiation Details
    * Request URL
    * URI Template Variable Values
    * Requested / Negotiated Sub Protocols
    * Requested / Negotiated Extensions
  * Idle Timeouts
  * Registered Decoders (if JSR356)
  * Registered Encoders (if JSR356)
  * Registered MessageHandlers (if JSR356)
  * User Properties (if JSR356)

**Comment by joakime** [comment]
This still needs to be done.

**Comment by lachlan-roberts** [comment]
@joakime are you sure we want all these details about the session in the dump?

We could have an extremely large number of active sessions and to include all that information could potentially be hundreds of lines of information per session.

Also I don't think we currently have the information available for the Connection and Network Endpoints of each websocket session, not sure how we could do those ones.
