### ISSUE TITLE
Consider removing SSLEngine.beginHandshake() calls.

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#251]
migrated from Bugzilla [#481777](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481777)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.3.5* on platform *PC*
Assigned to: Simone Bordet

On 2015-11-09 15:48:27 -0500, Simone Bordet wrote:

> The call to SSLEngine.beginHandshake() is not strictly needed for the initial handshake (as per javadocs), and it is only useful for initiating a re-handshake.
> 
> Since re-handshakes are not recommended, and we don't do them in Jetty anyway, the call can be safely removed.

**Comment by sbordet** [comment]
Calls to `SSLEngine.beginHandshake()` have been removed.
