### ISSUE TITLE
UriBuilder-like functionality

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2515]
It doesn't look like Jetty contains any functionality like https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriBuilder.html

Specifically I am looking for the ability to build up a URI a bit at a time (e.g. append multiple paths as opposed to replacing the entire path in one go). It doesn't look like there is a client-independent alternative out there, so it probably makes sense to bundle one with Jetty, no?

**Comment by sbordet** [comment]
`Request` lets you add the scheme, host, port, path, params.

It's not clear at all what is the use case you are after and why you can't do it with existing classes, e.g. `StringBuilder`.

**Comment by cowwoc** [comment]
@sbordet Sorry for assuming you can read my mind.

In my application, I often need to build up the URI path from multiple components. When doing so, I get tripped up over whether the previous component ended with a slash or not, and having to convert non-String components to a String.

`UriBuilder` handled both of these use-cases quite well. They would add slashes as needed and use `Object.toString()` to convert arbitrary arguments to String.

The former was great (though I will admit it is lazy of developers like myself to handle this at runtime instead of figuring this out at compile-time). I used to think the latter was good but I'm no longer so sure. The fact that they invoke `Object.toString()` is problematic because I ended up with many runtime failures where I was mistakenly passing in `Optional<T>` and the wrong value got sent over the while. I would have preferred getting a compile-time error in that case.

Anyway, I hope this explains my mindset. I think it would be useful being able to append components to the path, and have `Request` add slashes (between the previous component and the new component) as needed.

**Comment by cowwoc** [comment]
Another example I just ran into is incrementally building up form parameters. (Concrete example in the second paragraph in case you get lost). Currently one invokes `Request.content(new FormContentProvider(Fields))`. Once a `FormContentProvider` is constructed there is no way to append new parameters. One would need to pass around separate `Request` and `Fields` parameters and only join them at the end of building up a request, or one would need to decode the old `Fields` out of an existing `FormContentProvider`, add the new fields, and replace the `FormContentProvider` with a new one. Either option is painful. Ideally, I want my code to pass around `Request` and have different pieces contribute additional parameters.

I'll give you a concrete example: I have a method that adds authentication parameters to outgoing parameters. This code is not tied to any specific request. On the other hand, some requests needs to contribute their own form parameters (e.g. offset, limit for pagination). So now we've got two separate pieces of code that need to contribute form parameters.

(I am not the author of the server API so I don't control the fact that they decided to use the request body for these kind of parameters.)

**Comment by rakeshk15** [comment]
@sbordet sorry to hijack this conversation but I am also looking for inherent support for path params. I have asked a question on SO for the same, if you could please help with that - https://stackoverflow.com/questions/67995883/path-params-support-in-jetty-httpclient-v11-x

**Comment by sbordet** [comment]
@rakeshk15 I don't understand what you're trying to do.

URI path parameters are a different thing.

What you have in your StackOverflow question is a URI "pattern", akin to a regexp with capturing groups.
However, clients do not send URI patterns, they send full URIs, and it's the server-side that has patterns and performs the matching on the full URI sent by the client.

**Comment by sbordet** [comment]
@cowwoc I know this is old, do you still need it?

One problem is to try to figure out the `Content-Length` from the form parameters, which must be URL-encoded.

I can write an async version of the form content, but then your application needs to call `close()` when it's done adding parameters.

Otherwise the parameters will be sent as chunked content.

The idea would be something like (Jetty 10):

```java
Request request = ...;
AsyncFormRequestContent body = (AsyncFormRequestContent)request.getBody();
body.getFields().add(...);

// In some other code...
body.close();

// In yet some other code...
request.send();
```

Would that work for you?

**Comment by rakeshk15** [comment]
> @rakeshk15 I don't understand what you're trying to do.
> 
> URI path parameters are a different thing.
> 
> What you have in your StackOverflow question is a URI "pattern", akin to a regexp with capturing groups.
> However, clients do not send URI patterns, they send full URIs, and it's the server-side that has patterns and performs the matching on the full URI sent by the client.

@sbordet I implied like JAX-RS PathParam in my question where we get the value from url using this annotation e.g if the url is /api/users/{id} the in a JAX-RS resource we can get the value of {id} using the annotation PathParam. I should have provided the JAX-RS reference

consider this JAX-RS resource method.

`@Path("/users/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public User getUser(@PathParam("id") String id) {
        return this.userRepository.findOneById(id);
    }`

Similarly I wanted to provide a way in the RestClient I wrote on top of Jetty HttpClient where consumer could do something.

`Request jettyRequest = jettyClient
                .newRequest("https://apiserver.com/api/users/{id}").pathParam("id", 1234)
                .method(method.toString());`

I was just looking for the same in HttpClient, I know this can be done before passing the URI to the newRequest method here.

Thanks,
Rakesh

**Comment by joakime** [comment]
Perhaps an API on the client that supports URI Template - https://datatracker.ietf.org/doc/html/rfc6570

Just like `javax.websocket` currently does.

Start with level 1 support, and add other levels if they seem to be useful.
The API could just take the pre-defined template, along with setters for template variables.

``` java
Request req = client.newRequest("https://api.machine.com/api/users/{id}").uriVariable("id", "1234").method("GET");
```

The `.uriVariable(String name, String value)` should only support string variables.

Use "uri variable" (the name from the URI template spec), not "path parameter" (the name from the URI and HTTP specs).

Bonus is that if we do this, supporting actual path parameters is easier on level 3 uri template.

``` java
Request req = client.newRequest("https://machine.com/users{;id}/details").uriVariable("id", "1234").method("GET");
// results in ...
// https://machine.com/users;id=1234/details

Request req = client.newRequest("https://machine.com/users{;id}/details").uriVariable("id", "complex/example").method("GET");
// results in ...
// https://machine.com/users;id=complex%2fexample/details
```

**Comment by rakeshk15** [comment]
@joakime do you think it would be a value add to the HttpClient? If yes, shall I create a new issue or you want to track it from here itself.

**Comment by cowwoc** [comment]
@sbordet I am not actively working on this kind of code at the moment so for now I don't need this. Regarding `AsyncFormRequestContent` can't you compute `Content-Length` on the fly (cache the value if nothing changes) instead of requiring a user to `close()`?

**Comment by sbordet** [comment]
@cowwoc because the implementation needs to know if the application is done adding fields. Since it's a body, it can be send _after_ the request is sent.
