### ISSUE TITLE
How to handle 100-continue responses that don't fire onComplete callback

### ISSUE THREAD

**Issue by rgriffith** [eclipse/jetty.project#2518]
Jetty version: 9.4.10.v20180503

I have a pretty straight-forward setup where a single, re-used `HttpClient` uses the non-blocking API to send HEAD requests with a timeout in order to check if a URL returns a successful status. There is a complete listener being added to the `Request.send` call which checks the result's response status and attempts to perform a second GET request just in-case the server denied the initial HEAD request.

The issue I am running into is, after upgrading from Jetty 9.2.4.v20141103, in some cases, such as the URL https://tutor.stcloudstate.edu/, the response contains a 100 Continue and the thread appears to just hang and never complete or timeout. Prior to the upgrade, the complete callback would be called with an exception saying the response contained a 100 response code.

Here's what the `curl` output looks like for that particular URL:

```
$ curl -i -L https://tutor.stcloudstate.edu/
HTTP/1.1 100 Continue

HTTP/1.0 302 Found
Location: TracWeb40/Default.html
Set-Cookie: RSCSessionID=NnzEpoJnvNnzJqsGnsNnz; path=/; expires=Sat, 4 May 2019 13:55:59 GMT
Set-Cookie: ProductCode=RSC1002-10481; path=/; expires=Sat, 4 May 2019 13:55:59 GMT
Set-Cookie: RSCmobile=; path=/; expires=Sat, 4 May 2019 13:55:59 GMT

HTTP/1.0 200 OK
MIME-Version: 1.0
Content-Type: text/html
Content-Length: 34643
Set-Cookie: RSCSessionID=NqwEslJqsNqwJrrFukNnz; path=/; expires=Sat, 4 May 2019 13:55:59 GMT
Set-Cookie: ProductCode=RSC1002-10481; path=/; expires=Sat, 4 May 2019 13:55:59 GMT
Set-Cookie: RSCmobile=; path=/; expires=Sat, 4 May 2019 13:55:59 GMT

... body content here ...
```

After adding some additional callbacks to the request, `onRequestBegin`, `onRequestSuccess`, `onResponseBegin` and `onResponseSuccess`, I'm seeing the following flow:

- Request begin
- Request success
- Response begin
- Response success
- Response begin

Is there a recommended way to handle actually completing requests like this?

Let me know if you need any additional information. Thank you in advance.

**Client snippet**

```
httpClient = new HttpClient();
httpClient.setFollowRedirects(true);
httpClient.setCookieStore(new HttpCookieStore.Empty());

QueuedThreadPool jettyThreadPool = new QueuedThreadPool();

String name = HttpClient.class.getSimpleName() + "@" + httpClient.hashCode();
jettyThreadPool.setName(name);
httpClient.setExecutor(jettyThreadPool);

httpClient.start();
```

**Request snippet**

```
Request request = client.newRequest(url).method(requestMethod).accept("*/*");

request.timeout(5000, TimeUnit.MILLISECONDS);

request.send(new Response.CompleteListener() {
  @Override
  public void onComplete(Result result)
  {
     LOG.debug("Request completed");
  }
});
```

**Comment by sbordet** [comment]
This server replies with `100 Continue` to basically _every_ request, ignoring the fact that the request does not have content (so there is no point in replying `100 Continue`) _and_ ignoring that the client did not send the `Expect: 100-Continue` header.

So the trace is:
```
GET /
...

HTTP/1.1 100

HTTP/1.0 302
Location: TracWeb40/Default.html
...

GET /TracWeb40/Default.html
...

HTTP/1.1 100 

HTTP/1.0 200
```

RFC 7231 [says](https://tools.ietf.org/html/rfc7231#section-6.2.1) that useless `100 Continue` can be ignored.

`HttpClient` does not ignore them and gets confused on the second.

We'll fix this, but you really want to fix your server too.

**Comment by rgriffith** [comment]
Thank you for the follow up @sbordet. I am glad to hear this is something you're willing to address.

Unfortunately, the server would be out of our control and this type of response eventually causes instability in our application due to the request never actually completing. Any thoughts/suggestions on a workaround for now so we can avoid this issue? 

I can see in `onResponseContent` with a GET that I eventually get to the last response that has the 200 status, but with no way of getting to completion. 

Not ideal, but I believe I was able to sort of mimic what we had with Jetty 9.4.2, which appeared to simply abort the request when a 100 is encountered, by providing my own `ContinueResponseHandler` to the client that has an `onContinue` with a call to `request.abort(Throwable)`.

**Comment by sbordet** [comment]
You can either wait for 9.4.11, or copy/paste the solution in d4144f2.

**Comment by rgriffith** [comment]
Thank you for applying this fix, @sbordet. I will look into a custom build to test and see if it helps us.

In the meantime, would you happen to know if there is a timeline for the 9.4.11 release? Thanks!

**Comment by sbordet** [comment]
9.4.10 was just out last week, so around one/two months, when it's ready.

**Comment by rgriffith** [comment]
Thank you for following up, @sbordet. I was able to build a snapshot release at that commit and confirmed it resolved the issue we were running into. 

Unfortunately, since this issue can eventually have a negative impact on our application, we're looking for options prior to the release of 9.4.11. 

Curious, can you comment on whether or not snapshot builds could be considered somewhat stable? I noticed there's generally a fair amount of tests added along with changes, but wanted to get a second opinion. Otherwise, I'm thinking we may need to consider my Plan B, which was to hook into `onContinue` and abort the requests right away to prevent the issue.

**Comment by sbordet** [comment]
@rgriffith Jetty stable branch, 9.4.x, follows a rolling model: we cut a release, we do developments on branches that are code reviewed, built and tested in a CI, and then merged in the stable branch.
It is rare that an enhancement or bug fix that went through that process makes the stable branch unstable, but may happen.
Since 9.4.10 was only few days ago, not many changes went into the stable branch, so I am guessing it's quite stable.
Other than that, [Webtide](https://webtide.com) offers [support](https://webtide.com/lifecycle-support/) for this kind of things (e.g. cutting releases for customers), so if you have this need you may consider becoming a customer (and in this way sponsor the Jetty open source project).
