### ISSUE TITLE
how to disable hostname verification in jetty embedded 9.x versions

### ISSUE THREAD

**Issue by trilirili80** [eclipse/jetty.project#2519]
Dear all
Currently I have a Verison 9.3.x Embedded Jetty server working perfectly offering websockets communications through port 8080 and through 8443 for secure communications.
I need to disable the validation of the hostname as well as the certificates but I can not disable it.

I am using the method setTrustAll and setEndpointIdentificationAlgorithm(null) but the hostname verification is still activated.
sslContextFactory.setTrustAll(true);
sslContextFactory.setEndpointIdentificationAlgorithm(null);
How can avoid it?

**Comment by sbordet** [comment]
Duplicate of #2520.
