### ISSUE TITLE
No Response page in case of invalid url (IllegalArgumentException)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#252]
migrated from Bugzilla [#481839](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481839)
status NEW severity *major* in component *server* for *9.3.x*
Reported in version *9.3.2* on platform *PC*
Assigned to: Project Inbox

On 2015-11-10 08:56:47 -0500, ali baba wrote:

> Hi everyone,
> 
> Send a get request to jetty(9.3.2) with url = http://localhost:8080/any% causes response code 400, but nothing is shown to the user. User have to use some plugin to know that the response code is 400. if it is bug, the following block of HttpParse class is guilty:  (org.eclipse.jetty.http.HttpParser)
> 
> catch(Exception|Error e)
>         {
>             BufferUtil.clear(buffer);
> 
>             LOG.warn("parse exception: "+e.toString()+" for "+_handler,e);
> 
>             switch(_state)
>             {
>                 case CLOSED:
>                     break;
>                 case CLOSE:
>                     _handler.earlyEOF();
>                     break;
>                 default:
>                     setState(State.CLOSE);
>                     _handler.badMessage(400,null);   <<<<<<<null, but at least e.getMessage()
>             }
>         }

**Comment by joakime** [comment]
The Error 400 is returned as the request isn't detected as being a valid HTTP request.
It could be another service (such as an email client) just connecting to your connector and attempting to talk.

The RFC7230 approach is to close with status code 400 and then terminate the connection.
This behavior is consistent with the recommendations in the RFC.
