### ISSUE TITLE
setEndpointIdentificationAlgorithm(null) does not disable host name verification

### ISSUE THREAD

**Issue by trilirili80** [eclipse/jetty.project#2520]
Dear all
Currently I have a Verison 9.3.x Embedded Jetty server working perfectly offering websockets communications through port 8080 and through 8443 for secure communications.
I need to disable the validation of the hostname as well as the certificates but I can not disable it.

I am using the method setTrustAll and setEndpointIdentificationAlgorithm(null) but the hostname verification is still activated.
sslContextFactory.setTrustAll(true);
sslContextFactory.setEndpointIdentificationAlgorithm(null);
How can avoid it?

**Comment by sbordet** [comment]
How do you know that hostname verification is still enabled ?

**Comment by joakime** [comment]
Your "secure websockets tester" is where the change for your SSL should be.
What's your "secure websockets tester"?  (if Jetty, how did you set it up?)

**Comment by joakime** [comment]
The default behavior of SslContextFactory is to have no endpoint identification algorithm.

https://github.com/eclipse/jetty.project/blob/c134792d2d8bcf71eaa0b2f413bd10bef1492d2c/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L173

Also note, the call to `setTrustAll(true)` sets the endpoint identification to null already.

https://github.com/eclipse/jetty.project/blob/c134792d2d8bcf71eaa0b2f413bd10bef1492d2c/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L921-L926

**Comment by joakime** [comment]
If the "secure websockets tester" is a web browser, then be aware that a websocket connection to a localhost IP (doesn't matter the hostname) has MANY extra security rules around it.

**Comment by joakime** [comment]
Closing due to lack of feedback.
Will reopen if more information is provided.
