### ISSUE TITLE
http2-http-client-transport: Unable to find/resolve artifact

### ISSUE THREAD

**Issue by Kry1702** [eclipse/jetty.project#2524]
Issues one
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:copy (copy) on project http2-http-client-transport: Unable to find/resolve artifact.: Could not find artifact org.mortbay.jetty.alpn:alpn-boot:jar:undefined in alimaven (http://maven.aliyun.com/nexus/content/groups/public/) 

Issues two
[ERROR] Failed to execute goal on project jetty-server: Could not resolve dependencies for project org.eclipse.jetty:jetty-server:jar:9.4.11-SNAPSHOT: Could not find artifact org.eclipse.jetty:jetty-http:jar:tests:9.4.11-SNAPSHOT in apache.snapshots (https://repository.apache.org/content/repositories/snapshots) -> [Help 1]

to build use "-Dmaven.test.skip=true" run err .

Execute the command：mvn -Dmaven.test.skip=true clean install

**Comment by Kry1702** [comment]
Execute the command"mvn clean install" run is successful.

**Comment by sbordet** [comment]
If you get this issue sorted out, please close it.
