### ISSUE TITLE
Unable to remove illegal characters from response in case of illegal characters in request URL

### ISSUE THREAD

**Issue by abondin** [eclipse/jetty.project#2531]
Hello we are using Jetty 9.4.6 in commercial product. And our security department warries if jetty can hide information about the requested URL if it contains illegal characters.
They think it might be a potencial XSS attack.

The example request:
`GET /1999/1<script>test</script> HTTP/1.1`

And the response it that case is:
`Illegal character in path at index 32: http://xxx.xx/1999/1<script>test</script>`

Is it possible to remove the request URL from the response body?
Or may you just confirm, that it cannot be used in XSS attack?

![image](https://user-images.githubusercontent.com/1029937/39986633-efe285ce-576a-11e8-8dcb-3516167d0ad9.png)

**Comment by sbordet** [comment]
I tried this in 9.4.6, and I don't get the `Illegal character in path at index 32` that you get.
Also, the response is not what you report.
Are you sure that it is not some of your application components that is both producing the error and writing the response ?

**Comment by abondin** [comment]
Thanks @sbordet.
Seems that it not a problem of Jetty.
I was not able to reproduce on fresh jetty docker.
I think we can close the issue.
