### ISSUE TITLE
Slow HTTP2 per-stream download performance

### ISSUE THREAD

**Issue by ChangSurrey** [eclipse/jetty.project#2545]
In a nutshell, I have implemented a Jetty HTTP2 client and a Jetty HTTP2 server (both embedded, not standalone). The client is in UK and the server is deployed at Japan in Google Compute Cloud. The RTT latency is around 230ms. 

The server has implemented server push (which is the main use case I'm testing). I'm testing the application of MPEG-DASH video streaming using dash.js. For example, if a user requests a video segment file, the server will push a number of subsequent video segments. The exact number of pushed files can be dynamically configured. 

The issue I'm observing is that the per-stream download performance is not governed by TCP. Instead, it seems there is a per-stream speed limit enforced by Jetty server. 

For example, if I push 5 files, each file download stream gets around 0.7Mbps speed. However, if I push 50 files over the same link, each download stream still gets around 0.7Mbps. 

This is clearly in contradiction with how TCP works. Since the connection is well-past slow-start phase, the download speed aggregated over all streams multiplexed in a single TCP connection is expected to be the same, instead of the 10-time difference I'm currently seeing. 

Furthermore, through overriding onData() in Stream.Listener.Adapter(), I can see that regardless of the TCP windows settings in both Linux kernel and Jetty server (posted below), the Jetty server always sends exactly 65536 bytes per RTT. In other words, it alwasy sends 64KB, waits for client ACK (which takes one RTT), and sends the next 64KB. 

In the meantime, if I use a browser (Chrome or Firefox) to download the same files over the same link, I get throughput that is at least 10 times higher. 

My configurations for http_config (server side): 
```
// HTTP Configuration
HttpConfiguration http_config = new HttpConfiguration();
http_config.setSecureScheme("https");
http_config.setSecurePort(8443);
http_config.setHeaderCacheSize(327680);
http_config.setRequestHeaderSize(32768);
http_config.setResponseHeaderSize(32768);
http_config.setOutputAggregationSize(327680);
http_config.setOutputBufferSize(327680);
```

My configurations for Jetty HTTP2 client: 

```
HTTP2Client h2client = new HTTP2Client();
h2client.setInputBufferSize(8388608);
h2client.setInitialSessionRecvWindow(8388608);
h2client.setInitialStreamRecvWindow(8388608);
        
sslContextFactory = new SslContextFactory(true);
h2client.addBean(sslContextFactory);
h2client.start();
```

My server side Linux kernel TCP windows: 
```
net.core.optmem_max = 25165824
net.core.rmem_default = 25165824
net.core.rmem_max = 25165824
net.core.wmem_default = 25165824
net.core.wmem_max = 25165824
net.ipv4.tcp_mem = 851968       851968  851968
net.ipv4.tcp_rmem = 425984      851968  25165824
net.ipv4.tcp_wmem = 851968      851968  25165824
```

The client side Linux kernel TCP configurations are exactly as above. 

My questions are: 
- Is this behaviour intended? Does Jetty by default enforce some sort of per-stream speed limit? 
- The http_config parameters I set at server side (shown above) do not seem to have any effect on the Jetty server's behaviour - it still sends only 65536 bytes per RTT. Is there any other API that I can tune to modify this behaviour? 

Thanks, 
Chang

**Comment by ChangSurrey** [comment]
@sbordet I'm using Jetty v9.4.9(v20180320). 

How can I see / tune the HTTP/2 flow control window in Jetty?

**Comment by ChangSurrey** [comment]
@sbordet Here're my Jetty client configuration (I forgot to attach it earlier): 

```
h2client = new HTTP2Client();
h2client.setInputBufferSize(8388608);

h2client.setInitialSessionRecvWindow(8388608);
h2client.setInitialStreamRecvWindow(8388608);
        
sslContextFactory = new SslContextFactory(true);
h2client.addBean(sslContextFactory);
h2client.start();
```

**Comment by ChangSurrey** [comment]
@sbordet Just FYI I have updated both my server and client program to using the latest Jetty v9.4.10 and the issue is still there.

**Comment by sbordet** [comment]
@ChangSurrey I'll analyze this as soon as possible... You'll have my news early next week.

**Comment by sbordet** [comment]
Turned out to be a bug in `HTTP2Client`: when creating new streams, their recv window was not updated with the value set via `h2client.setInitialStreamRecvWindow()`, but remained at the default value of `65535`, which explains your slow downloads.

The high-level `HttpClient` with the `HttpClientTransportOverHTTP2` does not have this issue.

It has a simple workaround:

```java
HTTP2Client h2client = new HTTP2Client();
h2client.setInitialStreamRecvWindow(8388608);
...

h2client.connect(address, new Session.Listener.Adapter()
{
    @Override
    public Map<Integer, Integer> onPreface(Session session)
    {
        Map<Integer, Integer> settings = new HashMap<>();
        settings.put(SettingsFrame.INITIAL_WINDOW_SIZE, h2client.getInitialStreamRecvWindow());
        return settings;
    }
}, promise);
```
In this way, the client tells the server its stream recv window size, and the server will know it is large and not the small default.

Overriding `onPreface()` won't be needed after the fix.

**Comment by sbordet** [comment]
@ChangSurrey it's fixed. Can you test the latest code to verify the fix works for you ?

**Comment by ChangSurrey** [comment]
@sbordet Yes I can confirm the issue has been fixed, thank you very much for the prompt fix. 

Regards, 
Chang

**Comment by chanh1964** [comment]
Hi @ChangSurrey,

I'm currently doing research on DASH over HTTP/2 and struggling with setting up the experiment with Jetty and DASH.js.
Could you kindly explain how you set up the server and client to execute the server push?

Thank you very much.
