### ISSUE TITLE
Optimize preface frames writes

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#255]
migrated from Bugzilla [#482463](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482463)
status NEW severity _normal_ in component _http2_ for _9.3.x_
Reported in version _9.3.6_ on platform _PC_
Assigned to: Simone Bordet

On 2015-11-18 06:41:05 -0500, Simone Bordet wrote:

> HTTP/2 clients (may) send in a single write the following frames:
> 
> write(PREFACE + SETTINGS + WINDOW_UPDATE + HEADERS)
> 
> Jetty replies with multiple writes:
> 
> write(SETTINGS) // server preface
> write(SETTINGS) // reply to client's SETTINGS
> write(HEADERS)  // response
> 
> It would be nice if we could coalesce the writes into a single one, or at least the first two writes.

**Comment by sbordet** [comment]
The server does not have the context of whether the client `SETTINGS` frame is already read, parsed and valid when it processes the client preface.
We _could_ delay the send of the server `SETTINGS`, but what if the client `SETTINGS` never arrives ?
All in all, this seems too complicated to implement for a tiny benefit.
