### ISSUE TITLE
Non-blocking DNS resolver

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2557]
According to https://stackoverflow.com/a/44871699/14731 most of the threads in Jetty's thread pool are used for blocking DNS lookups

> These threads are used to perform DNS lookups (that are blocking in Java, and with no possibility to make them non-blocking)

I found an old post from 2012 that indicates multiple projects were working on a non-blocking DNS lookup mechanism: https://stackoverflow.com/q/11955409/14731

Does it make sense to revisit this? Maybe we can find a project with a compatible license and incorporate their non-blocking DNS resolver.

You'd still need a thread pool to handle incoming responses, but the number should be much lower.

**Comment by sbordet** [comment]
I really hope this will be fixed in the JDK.
Writing an maintaining a DNS lookup implementation would be quite some work.
I know Netty has one, so I think it could be plugged in by implementing `SocketAddressResolver`.
