### ISSUE TITLE
Use addEventListener(EventListener listener)

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2578]
Classes that declare their own listener types should follow the pattern of having those listeners extend `EventListener` and having an `addEventListener(EventListener listener)` method.

Existing API to add listeners by specific type can either be retained as an alternative or deprecated.

Examples that need to be updated include:
- [Connection](https://github.com/eclipse/jetty.project/blob/jetty-9.4.10.v20180503/jetty-io/src/main/java/org/eclipse/jetty/io/Connection.java#L41)
- [AbstractLifeCycle](https://github.com/eclipse/jetty.project/blob/jetty-9.4.10.v20180503/jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java#L139)

**Comment by joakime** [comment]
This was closed via PR #2511 and PR #3966
