### ISSUE TITLE
Getting too many CLOSE_WAIT states on heavy load

### ISSUE THREAD

**Issue by caimite** [eclipse/jetty.project#2591]
The application is an embedded Jetty webserver
1- Jetty libs used: jetty*.9.2.11.M0,jar
2- Linux version 3.10.0-514.26.2.el7.x86_64 (Centos)
3- java version "1.8.0_144"
4- Disk 20 GB and Memory 8 and 4 CPu

Install the following tools to use apache benchmark to simulate too many request
yum install httpd-tools

Run this command:
ab -c 1000 -n 10000 http://JettyApplicationAddres:Port/EntryPage/

parallely run this command to see if there is close_wait

netstat -napco | grep -i close_wait

**Comment by caimite** [comment]
@joakime ,
Can you try to overload your jetty server with requests and see if you will get the close_wait? I am pretty sure it's not fixed yet.
Thanks.

**Comment by joakime** [comment]
That would be due to the major version update from 9.2 to 9.4

> Reminder: Jetty versioning (since 1995) has been `<servlet_support>.<major_version>.<minor_version>`

The Session management has been overhauled a while ago for the 9.4.0 release.
There is no JDBCSessionIdManager anymore, and the concept of a SessionIdManager is even different.
See https://www.eclipse.org/jetty/documentation/9.4.x/session-management.html#jetty-sessions-architecture

If you are using the standalone `jetty-home` artifact (or the bigger `jetty-distribution` artifact) you just have to enable the `jdbc` module in your `${jetty.base}` directory.
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-sessions-jdbc.html

If you are using embedded-jetty, then you'll be using a JDBCSessionDataStore instead.

https://github.com/eclipse/jetty.project/blob/65070e6b2a5a75f209ee7f46993c1c8ade32c08e/examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneServletContextWithSession.java#L35-L60

So, instead of a `NullSessionDataStore`, you'll have a `JDBCSessionDataStore`.

See https://www.eclipse.org/jetty/javadoc/9.4.10.v20180503/org/eclipse/jetty/server/session/JDBCSessionDataStore.html

**Comment by caimite** [comment]
Thanks a lot for this information. However, I was able to upgrade my libs to the version you've suggested to me and I was able to get the close_wait once I overloaded the server with request. Here my actual libs files

jetty-client-9.2.24.v20180105.jar        jetty-http-9.2.24.v20180105.jar  jetty-plus-9.2.24.v20180105.jar      jetty-servlet-9.2.24.v20180105.jar   jetty-webapp-9.2.24.v20180105.jar
jetty-continuation-9.2.24.v20180105.jar  jetty-io-9.2.24.v20180105.jar    jetty-security-9.2.24.v20180105.jar  jetty-servlets-9.2.24.v20180105.jar  jetty-xml-9.2.24.v20180105.jar
jetty-deploy-9.2.24.v20180105.jar        jetty-jndi-9.2.24.v20180105.jar  jetty-server-9.2.24.v20180105.jar    jetty-util-9.2.24.v20180105.jar

**Comment by joakime** [comment]
Was trying to get my hands on a CentOS that had linux kernel 3.10 per your initial issue comment.

But was unable to find a CentOS with that old of a kernel.
That's when I discovered that Kernel 3.10 is EOL (End of Life) as well.
https://www.linux.com/news/linux-kernel-310-reached-end-life-users-are-urged-move-linux-44-lts-1

**Comment by caimite** [comment]
Hi Joakime, the same occurs also for one our client with is under the last Red hat version. I don' t think you need Centos, you can try that on any OS Linux distro that you have.

**Comment by caimite** [comment]
I am currious to see your actual system will be able to get the close_wait by overloaded the server the apache benchmark requests.

**Comment by joakime** [comment]
Does not happen on the following system.

```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 25 (Twenty Five)
Release:        25
Codename:       TwentyFive
$ uname -a
Linux ceres 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Testing with ...
* Jetty 9..4.10.v20180503
* Java 8u171

Results:

```
$ ab -c 1000 -n 10000 http://localhost:8080/demo/dump
This is ApacheBench, Version 2.3 <$Revision: 1796539 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        Jetty(9.4.10.v20180503)
Server Hostname:        localhost
Server Port:            8080

Document Path:          /demo/dump
Document Length:        544 bytes

Concurrency Level:      1000
Time taken for tests:   0.953 seconds
Complete requests:      10000
Failed requests:        0
Non-2xx responses:      10000
Total transferred:      6490000 bytes
HTML transferred:       5440000 bytes
Requests per second:    10498.06 [#/sec] (mean)
Time per request:       95.256 [ms] (mean)
Time per request:       0.095 [ms] (mean, across all concurrent requests)
Transfer rate:          6653.56 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   1.5      1      21
Processing:     0    4   6.2      3     211
Waiting:        0    4   5.9      3     210
Total:          0    5   7.5      4     212

Percentage of the requests served within a certain time (ms)
  50%      4
  66%      5
  75%      5
  80%      6
  90%      7
  95%      9
  98%     11
  99%     13
 100%    212 (longest request)
```

The netstat monitoring shows that CLOSE_WAIT does show up, but only exists for 1 netstat polling duration. (approx 1 second).

```
$ netstat -napco | grep -i close_wait
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6     650      0 ::1:59960               ::1:8080                CLOSE_WAIT  -                    off (0.00/0/0)
tcp6       0      0 ::1:60014               ::1:8080                CLOSE_WAIT  -                    off (0.00/0/0)
tcp6       0      0 ::1:59928               ::1:8080                CLOSE_WAIT  -                    off (0.00/0/0)
tcp6       0      0 ::1:60080               ::1:8080                CLOSE_WAIT  -                    off (0.00/0/0)
tcp6     650      0 ::1:60212               ::1:8080                CLOSE_WAIT  -                    off (0.00/0/0)
tcp6       0      0 ::1:60146               ::1:8080                CLOSE_WAIT  -                    off (0.00/0/0)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
^C
$
```

**Comment by joakime** [comment]
Same results (using same Jetty and Java version) on the following linux system.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
$ uname -a
Linux build 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by joakime** [comment]
Fired up a Fedora 27 VM and tried in there too.

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 27 (Twenty Seven)
Release:	27
Codename:	TwentySeven
$ uname -a
Linux tethys-vm-fedora 4.15.17-300.fc27.x86_64 #1 SMP Thu Apr 12 18:19:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

Same results.

Even tried the newer Java 10.0.1 release on this VM, with also the same results.
```
$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by caimite** [comment]
Thanks @Joakim for this excellent test.  Can you test with  100 000 request instead of 1000 and see if you the GUI page will be available. I forgot to mention that to you. Once you have ClOSE_wait your GUI page will spin and spin .

**Comment by joakime** [comment]
No change.  Everything is working as is.
Even testing on a browser makes no difference.
It works, as expected.

```
$ ab -c 1000 -n 100000 http://localhost:8080/demo/dump && curl http://localhost:8080/demo/dump && netstat -tnlp | grep close_wait
This is ApacheBench, Version 2.3 <$Revision: 1796539 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        Jetty(9.4.10.v20180503)
Server Hostname:        localhost
Server Port:            8080

Document Path:          /demo/dump
Document Length:        544 bytes

Concurrency Level:      1000
Time taken for tests:   6.121 seconds
Complete requests:      100000
Failed requests:        0
Non-2xx responses:      100000
Total transferred:      64900000 bytes
HTML transferred:       54400000 bytes
Requests per second:    16336.26 [#/sec] (mean)
Time per request:       61.214 [ms] (mean)
Time per request:       0.061 [ms] (mean, across all concurrent requests)
Transfer rate:          10353.74 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        4   31  46.9     29    1082
Processing:     4   30  10.0     30     234
Waiting:        2   19  10.5     18     230
Total:         22   61  46.6     59    1106

Percentage of the requests served within a certain time (ms)
  50%     59
  66%     61
  75%     62
  80%     62
  90%     64
  95%     66
  98%     69
  99%     71
 100%   1106 (longest request)
<HTML>
<HEAD>
<TITLE>Demo Dump</TITLE>
<BODY>
...(snip lots of info)...
</HTML>
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
```

**Comment by caimite** [comment]
Thanks @joakime . I will try to adapt my existing code to fit with Jetty 9.4 and update you with my findings. Thanks a lot for your time.

**Comment by caimite** [comment]
Hi @joakime ,
I implemented the LowRessourcesMonitor to see if this can help but it's not help for now. However, when the close_wait occurs, I run jstack to get a dump of the PID. Can you help me with if I send you the dump file?
Thanks.

**Comment by sbordet** [comment]
@caimite how do you know it's Jetty causing the CLOSE_WAITs ?

Do you have other libraries in your application that open sockets to other places ? Those libraries may be leaving sockets in CLOSE_WAIT.

Please report the CLOSE_WAIT you find on terminal (like @joakime did), because so far you have not shown any evidence.
`netstat` or `ss` will report the port numbers and they may not be the Jetty ports.

**Comment by caimite** [comment]
Here is  my evidence:
       1      0 192.168.0.25:48150         192.168.0.4:50276        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6     463      0 192.168.0.25:48150         192.168.0.4:50274        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50277        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50275        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50278        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 127.0.0.1:1701          127.0.0.1:52780         CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 127.0.0.1:49900         127.0.0.1:1701          CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50283        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50276        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6     463      0 192.168.0.25:48150         192.168.0.4:50274        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50277        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50275        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50278        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 127.0.0.1:49900         127.0.0.1:1701          CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50283        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 127.0.0.1:1701          127.0.0.1:53038         CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50276        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       0      0 192.168.0.25:48150         192.168.0.4:50274        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50277        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50275        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50278        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 127.0.0.1:49900         127.0.0.1:1701          CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50283        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50276        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       0      0 192.168.0.25:48150         192.168.0.4:50274        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50277        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50275        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50278        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50283        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50276        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       0      0 192.168.0.25:48150         192.168.0.4:50274        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50277        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50275        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50278        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50283        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50276        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       0      0 192.168.0.25:48150         192.168.0.4:50274        CLOSE_WAIT  28165/java           off (0.00/0/0)
tcp6       1      0 192.168.0.25:48150         192.168.0.4:50277        CLOSE_WAIT  28165/java           off (0.00/0/0)

**Comment by caimite** [comment]
[root@exfo ~]# ab -c 1000 -n 10000  http://10.8.2.118:7070/dashboard/
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.8.2.118 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests

**Comment by caimite** [comment]
Not all the request have been sent but my UI is hang due to the close_wait

**Comment by caimite** [comment]
Jstack for the pid show the following:


"qtp378622607-1163" #1163 prio=5 os_prio=0 tid=0x00007f4dd4159800 nid=0x5484 waiting for monitor entry [0x00007f4d80fa6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.caucho.util.LruCache.updateLruImpl(LruCache.java:427)
	- waiting to lock <0x00000006d7ea4cc8> (a java.lang.Object)
	at com.caucho.util.LruCache.updateLru(LruCache.java:421)
	at com.caucho.util.LruCache.get(LruCache.java:242)
	at com.caucho.quercus.env.Env.createString(Env.java:4384)
	at com.caucho.quercus.lib.file.FileModule.parseIniValue(FileModule.java:2477)
	at com.caucho.quercus.lib.file.FileModule.parseIni(FileModule.java:2385)
	at com.caucho.quercus.lib.file.FileModule.parse_ini_file(FileModule.java:2328)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.caucho.quercus.module.StaticFunction.invoke(StaticFunction.java:135)
	at com.caucho.quercus.env.JavaInvoker.callMethod(JavaInvoker.java:737)
	at com.caucho.quercus.env.JavaInvoker.call(JavaInvoker.java:643)
	at com.caucho.quercus.expr.CallExpr.evalImpl(CallExpr.java:237)
	at com.caucho.quercus.expr.CallExpr.evalCopy(CallExpr.java:164)
	at com.caucho.quercus.expr.BinaryAssignExpr.eval(BinaryAssignExpr.java:88)
	at com.caucho.quercus.expr.Expr.evalTop(Expr.java:523)
	at com.caucho.quercus.statement.ExprStatement.execute(ExprStatement.java:67)
	at com.caucho.quercus.statement.BlockStatement.execute(BlockStatement.java:105)
	at com.caucho.quercus.program.Function.callImpl(Function.java:433)
	at com.caucho.quercus.program.Function.call(Function.java:349)
	at com.caucho.quercus.expr.CallExpr.evalImpl(CallExpr.java:239)
	at com.caucho.quercus.expr.CallExpr.eval(CallExpr.java:151)
	at com.caucho.quercus.expr.Expr.evalArg(Expr.java:511)
	at com.caucho.quercus.expr.FunArrayExpr.eval(FunArrayExpr.java:117)
	at com.caucho.quercus.expr.Expr.evalCopy(Expr.java:497)
	at com.caucho.quercus.expr.BinaryAssignExpr.eval(BinaryAssignExpr.java:88)
	at com.caucho.quercus.expr.Expr.evalTop(Expr.java:523)
	at com.caucho.quercus.statement.ExprStatement.execute(ExprStatement.java:67)
	at com.caucho.quercus.statement.BlockStatement.execute(BlockStatement.java:105)
	at com.caucho.quercus.program.QuercusProgram.execute(QuercusProgram.java:412)
	at com.caucho.quercus.page.InterpretedPage.execute(InterpretedPage.java:89)
	at com.caucho.quercus.env.Env.executePage(Env.java:3896)
	at com.caucho.quercus.env.Env.include(Env.java:5377)
	at com.caucho.quercus.env.Env.includeOnce(Env.java:5330)
	at com.caucho.quercus.expr.FunIncludeOnceExpr.eval(FunIncludeOnceExpr.java:92)
	at com.caucho.quercus.expr.Expr.evalTop(Expr.java:523)
	at com.caucho.quercus.statement.ExprStatement.execute(ExprStatement.java:67)
	at com.caucho.quercus.statement.BlockStatement.execute(BlockStatement.java:105)
	at com.caucho.quercus.program.QuercusProgram.execute(QuercusProgram.java:412)
	at com.caucho.quercus.page.InterpretedPage.execute(InterpretedPage.java:89)
	at com.caucho.quercus.env.Env.executePage(Env.java:3896)
	at com.caucho.quercus.env.Env.include(Env.java:5377)
	at com.caucho.quercus.env.Env.includeOnce(Env.java:5330)
	at com.caucho.quercus.expr.FunIncludeOnceExpr.eval(FunIncludeOnceExpr.java:92)
	at com.caucho.quercus.expr.Expr.evalTop(Expr.java:523)
	at com.caucho.quercus.statement.ExprStatement.execute(ExprStatement.java:67)
	at com.caucho.quercus.statement.BlockStatement.execute(BlockStatement.java:105)
	at com.caucho.quercus.program.QuercusProgram.execute(QuercusProgram.java:412)
	at com.caucho.quercus.page.InterpretedPage.execute(InterpretedPage.java:89)
	at com.caucho.quercus.env.Env.executePageTop(Env.java:3907)
	at com.caucho.quercus.env.Env.executeTop(Env.java:3848)
	at com.caucho.quercus.servlet.QuercusServletImpl.service(QuercusServletImpl.java:188)
	at com.caucho.quercus.servlet.QuercusServlet.service(QuercusServlet.java:592)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1129)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:588)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:257)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:220)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1129)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by caimite** [comment]
@sbordet, I posted evidence and a part of the threadDump.

**Comment by sbordet** [comment]
What port is `48150`? Is it the port Jetty listens on?

**Comment by caimite** [comment]
this is a local port

**Comment by caimite** [comment]
I replace the real port by this port

**Comment by sbordet** [comment]
Is it the port Jetty listens on?

**Comment by caimite** [comment]
Yes

**Comment by caimite** [comment]
http://192.168.0.25:48150/ ---> to access the web application on the port that Jetty is listening

**Comment by sbordet** [comment]
OMG, Quercus. Apparently the latest release was 4 years ago.
Do you know that Jetty supports PHP as well?
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-fastcgi.html.

**Comment by caimite** [comment]
Yes, In my case we are using PHP.

**Comment by sbordet** [comment]
@caimite ok I see _some_ CLOSE_WAIT, but they don't seem many to me. 
Can you post some evidence that they get created in large quantities _and_ that they remain for a while?
It may be Quercus that is contending the LRU lock and delays the close of the socket.

If you deploy a super-simple web application that only replies with "hello, world", and make the `ab` test again, do you see CLOSE_WAITs ? 
I want to determine if it is really Jetty causing the CLOSE_WAITs or something else.

**Comment by caimite** [comment]
Ok, I will have to create a simple web application because the actual was not developped by me but I am working on it to fix this problem. Can you config that when you have the close_wait that your GUI is still accessible? In my case the UI is hang over until all the requests have been processed.

**Comment by sbordet** [comment]
@caimite it's not clear what you mean by "hang over", but there are a lot of things moving here.

So let's first see if it's Jetty causing the CLOSE_WAITs. That's one problem. We figure this out with a simple web application (no Quercus, just a static file), or with your application but requesting a static file (making sure that Quercus is not involved in the request handling).

Another problem is your application taking a lot of time to respond, IIUC (what you call "hang over"). That may be Quercus.

**Comment by caimite** [comment]
Hang over, the web application becomes unresponsive. user can't use the app. 

Ok. I will do the test with a simple file and give you feedback after.

**Comment by caimite** [comment]
or can you just share me you actual static file and I can run it in my side. If there no comprise information on your code. 

Thanks.

**Comment by gregw** [comment]
@caimite having a quick look at this... it looks to me that Quercus is getting blocked, the client then closes the connection (may occur in opposite order).   The connection is in CLOSE_WAIT waiting for jetty to respond to the close, but it will not do that while the application has not yet returned.   If the Quercus thread returned, I expect jetty would close the connection and the CLOSE_WAIT would go.

So I think CLOSE_WAIT is a symptom and not a cause.   

This is unlike other (old) reported CLOSE_WAIT problems, where the request handling had completed, but the connection was left in CLOSE_WAIT.

**Comment by caimite** [comment]
Thanks for this input @gregw! I realized that we are using quercus in Php code to call method from java(soap api). Even i don't well quercus, i will do my best to see how I can adjust the existing approach. I will let yoi know if i found something.

**Comment by caimite** [comment]
Hey Guys, 
After implementing the LowRessourceMonitor in my actual webengine and specifying timeaout for connection made through quercus. I have a better performance. However, By using JDBCSessionIdManager to established session to the DB, I realized there are a bunch of connections that are kept alive between my app and the DB. I am wondering if you can help provide lower value to get this session expired and **scavengePeriod   to check if session expired to purge them.  I am found this https://www.eclipse.org/jetty/documentation/9.2.22.v20170531/session-clustering-jdbc.html but it's not clear how that I can manage the Session created. Thanks

**Comment by joakime** [comment]
@caimite sounds like a question outside of the scope of this specific issue (and more suitable for the jetty-users mailing list)

**Comment by caimite** [comment]
Yes. But sorry!

**Comment by joakime** [comment]
No worries.
Can this Issue be closed then?

**Comment by gregw** [comment]
@caimite best to ask these questions on jetty-user mailing list.  Closing this issue.
