### ISSUE TITLE
Failing tests on windows UnixSocketTest

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#2597]
this test is consistently failing on windows, see [jetty-9.4.x-windows-nightly](https://jenkins.webtide.net/job/nightlies/job/jetty-9.4.x-windows-nightly/)

it seems this line in the setup does not produce a valid path on windows
https://github.com/eclipse/jetty.project/blob/154298af643a898601e374f1d7078bb33c5b40e4/jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketTest.java#L64

**Comment by joakime** [comment]
I've just disabled this test for Windows on the `jetty-9.4.x-junit5` branch.

https://github.com/eclipse/jetty.project/blob/c86ccffcc9160607897b7e2216db485d6473494e/jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketTest.java#L54-L55

**Comment by joakime** [comment]
Fixed with commit fac63f4
