### ISSUE TITLE
CachingWebAppClassLoader breaks JSP

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#260]
migrated from Bugzilla [#483119](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483119)
status ASSIGNED severity _normal_ in component _jsp_ for _9.3.x_
Reported in version _9.4.0_ on platform _PC_
Assigned to: Project Inbox

On 2015-11-26 18:37:35 -0500, Greg Wilkins wrote:

> JSPs fail to work with the caching WebAppClassLoader?!?!?
> which is a pity as it is intended to help with el repeated resource lookups?

**Comment by gregw** [comment]
I always thought this was a bad idea.... I'm probably more in favour of dropping the caching classloader.

**Comment by lordbuddha** [comment]
OK as the orginal requester for this functionality in the first place, let me re-state, that for use this makes a 20 to 30% difference in throughput on multi socket servers (real tin).

We ourselves have not moved to use CachingWebAppClassLoader as yet.  We are still using my original patched version of WebAppClassLoader and getting fantastic performance.  

However, when we have time, we would be looking to move back to a vanilla Jetty distribution but will/can only do that if you have a working CachingWebAppClassLoader (or a mechanism to add caching some how).

Have not looked yet at 9.4.0 and the reported bug...  Is the bug saying that JSPs are completely broken or sometime broken.  If always broken then of course this should have been picked up by automated tests :)

**Comment by joakime** [comment]
Issue #243 is likely where this new CachineClassLoader arrived from

**Comment by joakime** [comment]
Added in commit c0e6e66b49831a26307b73b678cf5c385b69a912

**Comment by joakime** [comment]
(Meant to close other issue)

**Comment by joakime** [comment]
Commit cea05f17d9ae016ed41f8038462b46a06986ef3e has some work towards this issue.

**Comment by gregw** [comment]
Not intending any more work on this
