### ISSUE TITLE
jetty-maven-plugin IT failure

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2600]
JDK9.01
9.4.x at eb3461fd847bcd37917e1fb2925e1c3a75773db3

fails with

```
[INFO] --- maven-invoker-plugin:3.1.0:integration-test (integration-test) @ jetty-maven-plugin ---
[INFO] Building: run-mojo-gwt-it/pom.xml
[INFO]           run-mojo-gwt-it/pom.xml .......................... FAILED (61.1 s)
[INFO]   The Maven invocation failed. Error while executing external command, process killed.
[INFO] Building: jetty-run-distro-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/gregw/.m2/repository/org/codehaus/groovy/groovy-all/2.4.8/groovy-all-2.4.8.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO]           jetty-run-distro-mojo-it/pom.xml ................. FAILED (51.8 s)
[INFO]   The build exited with code 1. See /home/gregw/src/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-distro-mojo-it/build.log for details.
```

**Comment by gregw** [comment]
I have a jar of the entire it target directory if anybody needs it.

**Comment by olamy** [comment]
yup please.
but what's in  /home/gregw/src/jetty-9.4.x/jetty-maven-plugin/target/it/jetty-run-distro-mojo-it/build.log ?

**Comment by gregw** [comment]
[build.log](https://github.com/eclipse/jetty.project/files/2053879/build.log)

**Comment by gregw** [comment]
@olamy ^

**Comment by gregw** [comment]
[jetty.txt](https://github.com/eclipse/jetty.project/files/2053909/jetty.txt)
This was renamed from jetty.out

**Comment by janbartel** [comment]
I can see that a random port was picked by jetty as expected, and the port number written to the jetty-run-distro-port.txt file also as expected. The test case makes 20 attempts to read this file, waiting 100ms between attempts. Perhaps the writing of the file was slow to happen, and the test case exhausted all attempts to read it. We could increase the pause from 100ms to something a little larger to make that less likely.

**Comment by olamy** [comment]
@gregw your machine is too slow :-) jetty process is forked in an other process and the main build wait the start for a maximum of 20*100ms=2s. (see loop in TestGetContent#getPort)
So reading the jetty.out file first line 
```
2018-05-30 11:51:36.874:INFO
```
Then
```
2018-05-30 11:51:43.444:INFO:oejs.Server:main: Started @12960ms
```
maybe increase the attempt number to read the port file in the loop?

**Comment by sbordet** [comment]
There is really not another way to communicate the port?

It appears that we pass the filename where the port is written as a system property, so can't we just pass the port as a system property?

**Comment by olamy** [comment]
@sbordet we have 2 separate process here. One is starting a server with port 0 so the real port is then "allocated" on start so we don't know the port before Jetty has finished starting. The other process is started as well. Not sure how we could transfer data between those processes except file.
I will try something similar to how we allocate stop/start ports (sounds feasible).
But as we have 2 separate processes there is still a need to wait jetty distro start before running the test. Well it can probably be achieved trying to connect to http with a connect timeout (maybe a larger one for slow machines..)

**Comment by olamy** [comment]
@janbartel the project has been generated from an archetype. I missed to cleanup ref to tomcat maven plugin but it's not used as it's in <pluginManagement>  section. But sure I will clean that :-)

**Comment by olamy** [comment]
Ok I found a solution. But I'd like to keep at least one test reading the port file as it's feature we offer to users. So we need to have a test for this.

**Comment by gregw** [comment]
I tried changing the retries for getting the port to 50 and it still sometimes fails.

Also, it's not good that there are at least 8 instances of this class - can we make a single version in a test artefact that is used by the others?
I also noted some example classes in org.olamy    probably best to make those org.example
 
Also with the reading of the file containing the port, I'm a bit worried about reads of a partially written file.  So perhaps it should be read twice and the port returned only if the same value is obtained after a 100ms delay.... or some better mechanism for communicating the port.

**Comment by olamy** [comment]
yup I don't like neither this class copy/paste but surefire maven plugin looks for test in target/test-classes of the project (and not in jar dependencies) but there is maybe a way to do it I will investigate.

**Comment by olamy** [comment]
I reworked the pr please have a look. Thanks!

**Comment by gregw** [comment]
I still cannot build locally:
```
[INFO] Building: run-mojo-gwt-it/pom.xml
[INFO] run post-build script postbuild.groovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/gregw/.m2/repository/org/codehaus/groovy/groovy-all/2.4.8/groovy-all-2.4.8.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO]           run-mojo-gwt-it/pom.xml .......................... FAILED (61.6 s)
[INFO]   The Maven invocation failed. Error while executing external command, process killed.
```

**Comment by gregw** [comment]
I've tried 3 times with clean builds and failed every time.

**Comment by gregw** [comment]
The buildlog looks normal, but it does down load a lot of stuff, which could take more than 60seconds?
Not sure why it is downloading all this stuff when this is the third time i've done a build after the poms were update?
[build.log.txt](https://github.com/eclipse/jetty.project/files/2087597/build.log.txt)

**Comment by olamy** [comment]
nothing in this build.log file shows a failure.
```
[INFO] WEB-INF/web.xml already added, skipping
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] beer ............................................... SUCCESS [  0.003 s]
[INFO] beer-shared ........................................ SUCCESS [  5.177 s]
[INFO] beer-client ........................................ SUCCESS [ 42.119 s]
[INFO] beer-server ........................................ SUCCESS [  9.901 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.504 s
[INFO] Finished at: 2018-06-09T19:08:10+02:00
Running post-build script: /home/gregw/src/jetty-9.4.x/jetty-maven-plugin/target/it/run-mojo-gwt-it/postbuild.groovy
Finished post-build script: /home/gregw/src/jetty-9.4.x/jetty-maven-plugin/target/it/run-mojo-gwt-it/postbuild.groovy
```
What is the end of the output of the main maven build?
most of the artifacts are downloaded from your disk (INFO] Downloading from local.central: file:///home/gregw/.m2/repository/org/apache/maven/maven-plugin-api/3.0/maven-plugin-api-3.0.pom ).
the it test start a new build using your local repo as a proxy (if the artifacts are not there they will be downloaded to this new build local repo)

**Comment by gregw** [comment]
Nothing in the end of normal build either. Just failure.

**Comment by olamy** [comment]
what about maven-invoker-plugin part
```
[INFO] --- maven-invoker-plugin:3.1.0:integration-test (integration-test) @ jetty-maven-plugin ---
[INFO] Building: jetty-start-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-start-mojo-it/pom.xml ...................... SUCCESS (8.9 s)
[INFO] Building: jetty-run-distro-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-run-distro-mojo-it/pom.xml ................. SUCCESS (9.1 s)
[INFO] Building: jetty-run-war-exploded-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-run-war-exploded-mojo-it/pom.xml ........... SUCCESS (9.0 s)
[INFO] Building: jetty-cdi-run-forked/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-cdi-run-forked/pom.xml ..................... SUCCESS (9.1 s)
[INFO] Building: jetty-run-war-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-run-war-mojo-it/pom.xml .................... SUCCESS (7.0 s)
[INFO] Building: jetty-deploy-war-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-deploy-war-mojo-it/pom.xml ................. SUCCESS (8.0 s)
[INFO] Building: jetty-run-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-run-mojo-it/pom.xml ........................ SUCCESS (6.0 s)
[INFO] Building: jetty-run-forked-mojo-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           jetty-run-forked-mojo-it/pom.xml ................. SUCCESS (7.1 s)
[INFO] Building: run-mojo-gwt-it/pom.xml
[INFO] run post-build script postbuild.groovy
[INFO]           run-mojo-gwt-it/pom.xml .......................... SUCCESS (32.1 s)
[INFO] 
[INFO] --- maven-invoker-plugin:3.1.0:verify (integration-test) @ jetty-maven-plugin ---
```

**Comment by olamy** [comment]
can you run mvn with -e parameter that can give use more informations.

**Comment by gregw** [comment]
Ooops I attached the wrong build.log.  Here is the one with the error
[target-it-run-mojo-gwt-it-build.log](https://github.com/eclipse/jetty.project/files/2087918/target-it-run-mojo-gwt-it-build.log)

**Comment by gregw** [comment]
This is with java 9.0.1

**Comment by olamy** [comment]
in your logs ``` Logging initialized @60228ms ```
So I increased the timeout to check if the server has started because it looks to take too long in your case.

**Comment by gregw** [comment]
Dang! tried your change but now failing earlier: #2650

**Comment by joakime** [comment]
Last report from @gregw is that his builds have been happy/stable for a few days.
Considering this fixed. (it can always be reopened)
