### ISSUE TITLE
WebSocket ByteAccumulator initialized with wrong maximum

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2603]
https://github.com/eclipse/jetty.project/blob/1509d1c9aa97e108de7d978f6ac68668e258db16/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/compress/CompressExtension.java#L150-L154

The maximum byte accumulator size should be based on text/binary message size (not buffer size)

**Comment by joakime** [comment]
@sbordet do you want to see fix this rolled back to jetty-9.2.x as well?

**Comment by sbordet** [comment]
@joakime yes please, should be trivial.

**Comment by joakime** [comment]
In the future, we should probably just remove the ByteAccumulator and send multiple frames down the ExtensionStack instead.

**Comment by joakime** [comment]
Fixed in 1269419
