### ISSUE TITLE
Make finding orphaned expired sessions common across SessionDataStores

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2609]

**Comment by joakime** [comment]
@janbartel the branch `jetty-9.4.x-2609-findexpiredsessions` is still lingering around, and hasn't been updated in a while. (it now fails to build)

**Comment by janbartel** [comment]
Just merged 9.4.x into it. The branch is still needed, just work on it going sloooowly.

**Comment by janbartel** [comment]
I think I'll rebase this off jetty-10.0.x because it is going to involve api changes that are probably too much for jetty-9.4.x.

**Comment by janbartel** [comment]
I will re-evaluate where I am with this one.
