### ISSUE TITLE
Cannot serve files in symbolically linked directory if the link contains dots

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#261]
migrated from Bugzilla [#483298](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483298)
status NEW severity *normal* in component *server* for *9.3.x*
Reported in version *unspecified* on platform *PC*
Assigned to: Project Inbox

Original attachment names and IDs:
- _[webapp.zip](https://bugs.eclipse.org/bugs//attachment.cgi?id=258357)_ (ID 258357)

On 2015-11-30 06:26:23 -0500, Antti Luomi wrote:

> Created attachment 258357
> minimal webapp to reproduce the problem
> 
> This was tested with Jetty 9.3.7-20151125.
> 
> Jetty 9.3.7 does not serve files in symbolically linked directories if the link contains dots. Jetty 9.2.14.v20151106 does.
> 
> To reproduce:
> * Initialize the Jetty base directory with modules http, webapp and deploy (--add-to-startd=http,webapp,deploy)
> * Unzip the zip file attached to this ticket to jetty base directory (will create directory webapps/test).
> * Start Jetty
> * Browse to http://localhost:8080/test/
> * Click link-with-dots
> * Click test-file.txt
> * With Jetty 9.3.7 youâll get HTTP error 404. With Jetty 9.2.14 you'll see contents of the file.
> * Suprisingly, clicking link-to-test-file.txt instead of test-file.txt shows the file content correctly.

**Comment by joakime** [comment]
Attached zip has no problems in Jetty 9.3.7
Possibly because it has no "link-with-dots" file/resource in it.
Closing.

Feel free to reopen if you have a way to replicate.
