### ISSUE TITLE
Scavenging scheduler skipping session records which are invalidated using Session.invalidate

### ISSUE THREAD

**Issue by bhuva3** [eclipse/jetty.project#2617]
We have Implemented MongoDB based Session Clustering. We are using Jetty version 9.4.10.v20180503 
we observed that, if any session has been invalidated using Sesssion.invalidate then it replace current session record with new session record in mongoSessionDatastore. Newly created session records (looks like below) never get delete/scavenged by scavenging scheduler. 

`{ "_id" : ObjectId("5b150570349a2d2c24cf4a14"), "id" : "node0118mrt4ezetuu61nsw5lt4w2ymc1", "created" : NumberLong("1528104304202"), "valid" : true, "context" : { "0_0_0_0:" : { "__metadata__" : { "version" : NumberLong(1), "lastSaved" : NumberLong("1528104304226"), "lastNode" : "node01" } } }, "maxIdle" : NumberLong(-1), "expiry" : NumberLong(0), "accessed" : NumberLong("1528104304202"), "lastAccessed" : NumberLong("1528104304202") }`

**Comment by janbartel** [comment]
Do you have a simple reproduction test case? 

The mongo record shows that the session has no max inactive time, that means that it is immortal. Have you configured max idle time of 0 or less? Do you have more than 1 context sharing the same sessionid?

**Comment by bhuva3** [comment]
We are using non-sticky load balancer for two of our web server and they are sharing same session. Before calling Session.Invalidate below was the session data in MongoSessionDatastore. And once we call Session.Invalidate it removes below existing record and creates new record with maxIdle=-1 and expiry=0. here is example of session data before and after Session.Invalidate call. We have set maxIdle time to 60sec for testing purpose. 

**Before calling Session.Invalidate :**
`{ "_id" : ObjectId("5b1576ae349a2d2c24cf4b10"), "id" : "node011j0fp2hcmckj5ey01bpb33lxq0", "created" : NumberLong("1528133294394"), "valid" : true, "context" : { "0_0_0_0:" : { "__metadata__" : { "version" : NumberLong(6), "lastSaved" : NumberLong("1528133296382"), "lastNode" : "node01" }, "SESSION_DATA" : "some session data", "maxIdle" : NumberLong(60000), "expiry" : NumberLong("1528133356313"), "accessed" : NumberLong("1528133296313"), "lastAccessed" : NumberLong("1528133295617") }`

**After calling Session.Invalidate :**
`{ "_id" : ObjectId("5b1576b7349a2d2c24cf4b27"), "id" : "node011xo49t9n2t3o015pl0hq2o00ol1", "created" : NumberLong("1528133303000"), "valid" : true, "context" : { "0_0_0_0:" : { "__metadata__" : { "version" : NumberLong(1), "lastSaved" : NumberLong("1528133303034"), "lastNode" : "node01" } } }, "maxIdle" : NumberLong(-1), "expiry" : NumberLong(0), "accessed" : NumberLong("1528133303000"), "lastAccessed" : NumberLong("1528133303000") }`

We are able to reproduce same error using JDBC based session clustering as well. We do have a Simple Service/Browser test for our service. It creates session and then we force logout, which calls Session.invalidate(). After that happens we can see that 
record in the MongoDB session datastore gets parked (-1) for the maxIdle and expiry to 0. 

Let me know if you need more details around this.

**Comment by janbartel** [comment]
These are 2 different sessions. As you can see the session IDs are different. I assume that after your app invalidated the first session, a subsequent request came in and create the second session.  If you turn on debug for org.eclipse.jetty.server.sessions you should see what is happening.

BTW using a sticky load balancer is highly recommended. If you're not using one then make sure you have disabled the session cache as discussed in the jetty docs.

**Comment by janbartel** [comment]
@bhuva3 I'm going to close this issue for now as there does not seem to be a jetty issue. If you have evidence of a jetty problem, please reopen.
