### ISSUE TITLE
ProcessorUtilsTest fragile, must run before other tests e.g. ReservedThreadExecutorTest

### ISSUE THREAD

**Issue by javabrett** [eclipse/jetty.project#2618]
Running a build on Travis for 9.4.x @ 7af2eecf6a78818e674ad13006b1462fb9b062dd (plus a couple of Travis bits), I noticed:

```
[INFO] Running org.eclipse.jetty.util.ProcessorUtilsTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.005 s <<< FAILURE! - in org.eclipse.jetty.util.ProcessorUtilsTest
[ERROR] getPropertyValue(org.eclipse.jetty.util.ProcessorUtilsTest)  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError: expected:<42> but was:<2>
	at org.eclipse.jetty.util.ProcessorUtilsTest.getPropertyValue(ProcessorUtilsTest.java:39)
```
This is caused by `ProcessorUtils` using static clinit to determine once only whether the value to use comes from `JETTY_AVAILABLE_PROCESSORS`, which the test sets to `42`, but if any other prior test in the same JVM results in `ProcessorUtils` being classloaded e.g. `ReservedThreadExecutorTest` -> `ReservedThreadExecutor`, then the test is doomed to fail.

If this is to remain testable, the hard static init might have to be forgone and a reset method added, or some other side-test might have to do.

**Comment by sbordet** [comment]
I'll look into this, thanks for reporting it.
