### ISSUE TITLE
Exception from user endpoint onClose results in unclosed WebSocketSession

### ISSUE THREAD

**Issue by JerryChin** [eclipse/jetty.project#2620]
Hey, I'm using Jetty `9.4.6.v20170531` in PROD, web-socket is heavily utilized in our service.

Today two nodes are found memory leak, GC threads took up nearly all computing power, after carefully examining the heap dumped, we find many `WebSocketSession`s are not properly released, so are our web-socket handlers.

~~When `onWebSocketError` is called, the following action is taken:~~

        if (this._session != null) {
            // resources clean up here

            if(_session.isOpen()){
                Session s = _session;
                _session = null;
                try {
                    s.disconnect();
                } catch (Exception e) {
                    logger.error("disconnect failed", e);
                }
            }
            logger.info("close user handler finished");
        }
        this._session = null;

~~but, unlike `onWebSocketClose` callback, the source code of [WebSocketSession#disconnect](https://github.com/eclipse/jetty.project/blob/7af2eecf6a78818e674ad13006b1462fb9b062dd/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L231) shows us the managed WebSocketSession is not cleared, we later managed to cast `Session` object back to `WebSocketSession`, and call [getContainerScope().onSessionClosed()](https://github.com/eclipse/jetty.project/blob/7af2eecf6a78818e674ad13006b1462fb9b062dd/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L350) to manually release leaked sessions as follows:~~

         if(this._session != null) {
                if(this._session instanceof WebSocketSession) {
                    ((WebSocketSession)this._session).getContainerScope().onSessionClosed((WebSocketSession) this._session);
                }
            }

Edited: the initial finding is misleading, see the following discussion.

We believe this behavior is a bug, if you should need information, feel free to ask me.

**Comment by joakime** [comment]
Interesting report.

One note:  We cannot release/null/dereference the session with onClose as that's part of the websocket close handshake.
Only when the websocket close handshake is completed (is fully disconnected) can we remove the session reference.

**Comment by joakime** [comment]
Please try with the latest stable release of Jetty 9.4.x series - (currently version: 9.4.10.v20180503)

There's been updates to the Jetty 9.4.x series with regards to websocket close behavior.
In Jetty 9.4.8.v20171121 some important changes to how close behaved in various code paths was introduced.

**Comment by JerryChin** [comment]
We've located the problem! 

The short story is a NPE is mistakenly thrown from `onWebSocketClose` callback, subsequently [containerScope.onSessionClosed(this)](https://github.com/eclipse/jetty.project/blob/28466efa0420e6fa1ce924c12c41132c5b298558/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L562) is not getting called.

The buggy path is as follows:

1. Client connects to our server, `onWebSocketConnect` event is fired, we store the `Session` reference to `_session` variable and update `idleTimeout` to 30 seconds for now.
2. Idle timeout fired, because no any data received( it happens we are not sure why), `onWebSocketError ` is first called, some clean up work is done, including nullizing the previous session reference,  but we mistakenly access an uninitialized field, a NPE is thrown, see below:
    
           if (this._session != null) {
                // clean up resources

                // a NPE is thrown here!

                if(_session.isOpen()){
                    Session s = _session;
                    _session = null;
                    try {
                        s.disconnect();
                    } catch (Exception e) {
                        logger.error("disconnect failed", e);
                   }
              }
               logger.info("close user handler finished");
           }
            this._session = null;


3. `onWebSocketClose` is also fired, we try to clean up again, this time the clean up is supposed to do nothing as `_session` is nullized as seen in above code, but due to our mistake, an another NPE is thrown, this time, we're in trouble.

        //  the NPE goes way up here, the subsequent code is not executed, causing `WebSocketSession` leaked
        notifyClose(close.getStatusCode(),close.getReason());
       try
        {
            if (LOG.isDebugEnabled())
                LOG.debug("{}.onSessionClosed()",containerScope.getClass().getSimpleName());
            containerScope.onSessionClosed(this);
        }
                    catch (Throwable t)
        {
            LOG.ignore(t);
        }

    the above code is copied from [here](https://github.com/eclipse/jetty.project/blob/28466efa0420e6fa1ce924c12c41132c5b298558/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L554).


@joakime Do you think the exception should be captured inside `WebSocketSession`, or just leave it alone? if it's expected outcome, I'll close the issue.

**Comment by joakime** [comment]
Nah, the implementation on our side should be more resilient to errors from the user endpoints.
This smells like a bug on our side.

**Comment by lachlan-roberts** [comment]
Fixed by PR #4346
