### ISSUE TITLE
Test failure: ShutdownMonitorTest.testStartStopSamePortDifferentKey

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2626]
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/391/testReport/junit/org.eclipse.jetty.server/ShutdownMonitorTest/linux_jdk8___Test___jdk8___testStartStopSamePortDifferentKey/

**Comment by joakime** [comment]
We should probably move these tests to `test-distribution` technique.

**Comment by joakime** [comment]
These tests were written because of Bug [403513](https://bugs.eclipse.org/403513) and created in commit 25f5e38e13f78209648276eabbc309801b325e3b
Moving them to `test-distribution` will not address the concerns brought up in the original bug.

**Comment by joakime** [comment]
I wonder if the port reuse in these test cases is the reason for the problem.
As it was `testStartStopSamePortDifferentKey` that failed in the past.

The testcase ... 
1. starts a ShutdownMonitor on port 0 (have system bind to available port).
2. remember port number assigned.
3. stop ShutdownMonitor
4. set port to remembered port
5. start ShutdownMonitor again

I can see the port being "stolen" again by a different parallel testcase execution between steps 3 and 5.
