### ISSUE TITLE
jetty-alpn-server Import-Package manifest header should specify version of org.eclipse.jetty.alpn.api

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#263]
migrated from Bugzilla [#483339](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483339)
status REOPENED severity *normal* in component *maven* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Jan Bartel

On 2015-11-30 20:00:02 -0500, hiep lq wrote:

> bundle alpn.server is required to create ALPNServerConnectionFactory
> it import org.eclipse.jetty.alpn [9.3.6,9.3.7)
> i just find out newest version of alpn-api is 1.1.2.v20150522,
> but it export org.eclipse.jetty.alpn at 1.1.2
> 
> so, constraint isn't satisfaction.
> my work-around is edit manifest of jetty.alpn

On 2016-01-05 22:58:49 -0500, Jan Bartel wrote:

> Hi,
> 
> I suspect you might not have your osgi environment set up correctly. Here's a link to the alpn doc: http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html
> 
> For osgi, you need to ensure that the alpn-boot jar is on the -Xbootclasspath for the osgi container. That boot jar will contain the alpn-api.
> 
> Then, you need to deploy the jetty-osgi-alpn jar into the container. This has a FragmentHost directive in the manifest that makes sure the api is exposed.
> 
> Finally, you can look at the junit tests for jetty osgi with alpn to get some hints: https://github.com/eclipse/jetty.project/blob/master/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2.java
> 
> As I think this is a misconfiguration of your setup, I am going to close this issue. If you can show that there is a problem with jetty, please reopen the issue and include all relevant information, such as how you have configured your osgi container, which jars you have deployed, any stacktraces or logs that show the error etc.
> 
> regards
> Jan

On 2016-01-05 23:36:52 -0500, hiep lq wrote:

> Thanks Jan Bartel for reply.
> Has a difference from TestJettyOSGiBootHTTP2.java with my environment.
> TestJettyOSGiBootHTTP2 don't materialize alpn-api bundle, my issue at alpn-api bundle.
> 
> why need alpn-api? because alpn.server bundle import package org.eclipse.jetty.alpn (9.3.6,9.3.7) you can see in MF file
> now, i just see alpn-api export this package. but version isn't match.
> 
> why TestJettyOSGiBootHTTP2 pass? error just fire at runtime, when alpn.server need load class in package org.eclipse.jetty.alpn
> 
> In eclipse, when i click validate plug-in, it also detect this issue.

On 2016-01-07 10:19:19 -0500, hiep lq wrote:

> i don't get feedback, so i will reopen it.

**Comment by hieplq** [comment]
I just check MANIFEST.MF of alpn.server and alpn.api on release 9.3.9.M1 and see this issue isn't yet resolve.
MANIFEST.MF of alpn.server: import package org.eclipse.jetty.alpn;version="[9.3.9,9.3.10)"
MANIFEST.MF of alpn.api: export package org.eclipse.jetty.alpn;uses:="javax.net.ssl";version="
 1.1.2"

maybe is wrong but please figure me out how this issue is resolved?

**Comment by janbartel** [comment]
@hieplq Let me explain how we use alpn for the osgi unit test TestJettyOSGiBootHTTP2, and then you tell me why you need to do something different :)

So, we use the org.mortbay.jetty.alpn.alpn-boot.jar. This contains the api too.  This is then put onto the bootclasspath of the osgi runtime using -Xbootclasspath/p: command line arg.

Then, to ensure that the classes are exposed correctly, we deploy the org.eclipse.jetty.osgi.jetty-osgi-alpn.jar. This contains a "Fragment-Host" directive that exposes the classes onto the system classpath of the osgi runtime. Without this jar and the "Fragment-Host" header the jetty alpn api classes will NOT be seen by the osgi classloader.

Now, can you explain why and how what you want to do differs from that?

**Comment by hieplq** [comment]
Thanks @janbartel for help me clear about issue.
i think i do exact what you said just difference way.
i come from idempiere community, 
we use mercurial to manager source (you use git), 
use buckminster for fetching library (you use maven)
we use equinox for osgi.

when i run my application, it will check dependency, and bellow is error message.

`
java.version=1.8.0_72-internal
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.adempiere.server.server_product
Command-line arguments:  -product org.adempiere.server.server_product -data /mnt/data/dev/project/me/repository/idempiere-hsv-group/idempiere-hsv/../runtime-server.product -dev file:/mnt/data/dev/project/me/repository/idempiere-hsv-group/idempiere-hsv/.metadata/.plugins/org.eclipse.pde.core/server.product/dev.properties -os linux -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.jetty.alpn.server 2 0 2016-04-22 16:35:41.013
!MESSAGE Could not resolve module: org.eclipse.jetty.alpn.server [122]
  Unresolved requirement: Import-Package: org.eclipse.jetty.alpn; version="[9.3.8,9.3.9)"
`

when i change MANIFEST.MF of bundle org.eclipse.jetty.alpn.api to 

`Export-Package: org.eclipse.jetty.alpn;uses:="javax.net.ssl";version="
 9.3.8"`

everything just run fine.

**Comment by hieplq** [comment]
i already setup a web project use mercurial + equinox + buckminster for reproduce issue.
do you interest to use it to investigate?

**Comment by janbartel** [comment]
@hieplq  it is the org.eclipse.jetty.osgi.jetty-osgi-alpn.jar (maven coord: org.eclipse.jetty.alpn: alpn-api:1.1.2.v20150522,  bundlename: org.eclipse.jetty.osgi.alpn.fragment) that exports the org.eclipse.jetty.alpn.api at the version that matches the jetty version that you are using.  Without this jar deployed correctly into the osgi container the alpn-server bundle will indeed not resolve correctly. Check that you have it deployed.

The org.eclipse.jetty.alpn.api jar has its own release lifecycle: it is deliberately **not** tied to any particular version of jetty, thus you cannot change its manifest.  That is why you must use the org.eclipse.jetty.osgi.jetty-osgi-alpn.jar to do the package export at the correct jetty version.

Please check your deployment and make sure that you have all of the jars deployed correctly as I posted previously. If things are still not working, then please post your analysis of why your deployment environment is not respecting the Fragment-Host header in the org.eclipse.jetty.osgi.jetty-osgi-alpn.jar, as that is the only reason I can think of for the api not to be resolved.

**Comment by hieplq** [comment]
I already have this fragment-host.
just check it and see "Export-Package: org.eclipse.jetty.alpn;version="1.1.2""
so it also don't suitable.

**Comment by janbartel** [comment]
@hieplq ah! Now we're getting somewhere!

Running the TestJettyOSGiBootHTTP2 test again, and checking if all bundles are resolved or started shows that the alpn-server jar is in fact not resolved. However, the test runs! So it must be that the classloading works at runtime.

Looking into why the resolution does not work, as I think this used to be the case.

**Comment by janbartel** [comment]
OK, I found the problem, although I don't understand why it is happening. When the bnd plugin processes the jetty-alpn-server bundle, it generates an Import-Package header for the alpn-api at version 9.3.8 (ie same as jetty version), rather than the version that is actually a dependency (1.1.2.v20150522). 

I've forced it to generate the correct version in the Import-Package header.  

The commit for jetty-9.3.x is here: https://github.com/eclipse/jetty.project/commit/2850f98fb4ed9a8edf1a80c100e77984ec456e75. I've also pushed it to master.

Thanks for persisting with this, I finally worked out the problem!

**Comment by hieplq** [comment]
hi @janbartel, jetty-alpn-openjdk8-server got same issue,
it have Import-Package: org.eclipse.jetty.alpn;version="[9.4.8,9.4.9)"

refer:http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-alpn-openjdk8-server/9.4.8.v20171121

**Comment by janbartel** [comment]
@hieplq  I've opened issue #2016  to track your problem report.

**Comment by hieplq** [comment]
i see, thanks for consider it.
