### ISSUE TITLE
AsyncContext complete while pending async Reads/Writes

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#264]
migrated from Bugzilla [#483427](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483427)
status ASSIGNED severity _normal_ in component _server_ for _9.4.x_
Reported in version _9.4.0_ on platform _All_
Assigned to: Simone Bordet

On 2015-12-01 23:03:29 -0500, Greg Wilkins wrote:

> The Servlet EG has discussed how a call to complete should behave if there are pending async writes/reads
> 
> The favoured proposal is for compelete (and probably close) to always work, but it may truncate the response (potentially equal to an abort in jetty).

On 2015-12-02 00:09:37 -0500, Greg Wilkins wrote:

> See https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2015-11/thread/1# 00001

On 2015-12-02 00:10:12 -0500, Greg Wilkins wrote:

> Fix with 4bbd060
> 
> sbordet - please review when you have time

**Comment by joakime** [comment]
This was completed in commit 4bbd060ca8468f3289ef049379a7cf4ec20ececa

**Comment by joakime** [comment]
New location of discussion archive - http://download.oracle.com/javaee-archive/servlet-spec.java.net/jsr369-experts/2015/11/0312.html
