### ISSUE TITLE
Switch SslContextFactory.keystoreType from `JKS` to `PKCS12`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2643]
Since the default implementation in Java is now `PKCS12`, perhaps with Jetty 10 we should switch our defaults over to `PKCS12` as well, retiring the `JKS` default in SslContextFactory.

**Comment by joakime** [comment]
@sbordet do we still want to do this for Jetty 10?

**Comment by sbordet** [comment]
Yes we want to do it for 10.
