### ISSUE TITLE
Better handle concurrent calls to change session id and invalidate within a context

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2646]
It is possible that several requests may concurrently try to change the id of the same session, or invalidate it whilst the id is changing. Currently the outcome of that is uncertain. Concurrent invalidation is already handled, but we need to also handle concurrent changing of id with/without concurrent invalidation as well. The spec is totally silent on this topic. We will ensure that the first call (either to change the session id or invalidate the session) is fully completed before the next call proceeds.

**Comment by janbartel** [comment]
Fixed in jetty-9.4.15

**Comment by joakime** [comment]
> Fixed in jetty-9.4.15

9.4.15?  are we making a new release of 9.4.15 then?

**Comment by joakime** [comment]
Ah, I understand, this was an old issue.
