### ISSUE TITLE
What happened to JSR356 Client Container LifeCycle stop?

### ISSUE THREAD

**Issue by mpsrig** [eclipse/jetty.project#2659]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=423646#c0

I can reproduce this bug in 9.4.11.v20180605

The supposed fix was https://github.com/eclipse/jetty.project/commit/44a7d235161a9bd96185d67ca69165b392c47db2

This can be easily reproduced with https://github.com/jetty-project/embedded-jetty-websocket-examples/tree/master/javax.websocket-example ; simply commenting the call to stop() at https://github.com/jetty-project/embedded-jetty-websocket-examples/blob/master/javax.websocket-example/src/main/java/org/eclipse/jetty/demo/EventClient.java#L38 causes the client to never exit.

@joakime

**Comment by joakime** [comment]
JSR356 Client Container has no LifeCycle.

See: eclipse-ee4j/websocket-api#212

Our past addition of it breaks our spec compliance.

The layers present in JSR356 makes this even more difficult ...

JSR356 Client Container -> WebSocket Client -> Http Client

You'd have to unwrap down to the HttpClient to initiate the stop any more.
The upcoming support for the new WebSocket over HTTP/2 drafts also complicates this even further.

**Comment by joakime** [comment]
The design of the JSR356 Client Container is that it exists for the life of the JVM.
You have no control over the JSR356 Client Container.
You can't even set/configure proxy support.
You can't even set/configure SSL/TLS support.

It you require more control, then you shouldn't be using the JSR356 Client Container.

**Comment by mpsrig** [comment]
@joakime I'm not sure if those comments were addressed to me?  The issue I am trying to report is that this down-casting hack is necessary, when it should not be.

**Comment by joakime** [comment]
I sense you are finding that the Jetty JSR356 Client Container uses too many resources.
That's probably true, especially in light of (the recent) Issue #2655 (being worked on).

**Comment by mpsrig** [comment]
That's not so much my concern; my goal is to not be writing unnecessary platform-specific (Jetty-specific) code; after all that's the whole reason for using JSR356.

**Comment by joakime** [comment]
There's nothing to do here, as JSR356 (javax.websocket) has no lifecycle, no stop, no close, no shutdown.  Once you create the Client container it's live for the entirety of the JVM's runtime.
In the future, should a new API arise in javax.websocket, we'll create a new issue to add that feature/functionality.
