### ISSUE TITLE
jetty-client redirection process is aborted if redirect response have corrupt body

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#266]
migrated from Bugzilla [#484025](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484025)
status NEW severity *major* in component *client* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Simone Bordet

On 2015-12-09 10:09:45 -0500, Konstantin Gribov wrote:

> It seems strange to fail redirection process if resource with status 301/302/307 and correct `Location` header returns some incorrect body (corrupt gzip stream, corrupt chunked stream).
> 
> Most user agents usually follow such redirect without parsing body at all.
> 
> To reproduce:
> // Test client, expected to successfully get response from /ok after redirect and print "ok"
> public class JettyClient {
>   public static void main(String[] args) throws Exception {
>     HttpClient httpClient = new HttpClient();
>     httpClient.start();
>     try {
>       System.out.println(httpClient.GET("http://localhost:8088/302gz").getContentAsString());
>     } catch (Exception e) {
>       e.printStackTrace();
>     } finally {
>       httpClient.stop();
>     }
>   }
> }
> 
> // Test server, which produce redirect response with "corrupted gzip" data and correct page after redirect:
> public class BogusServer extends AbstractHandler {
>   public static void main(String[] args) throws Exception {
>     Server server = new Server(8088);
>     server.setHandler(new BogusServer());
>     server.start();
>     server.join();
>   }
> 
>   @Override
>   public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)
>       throws IOException, ServletException {
>     if ("/302gz".equals(target)) {
>       response.setHeader(HttpHeader.LOCATION.asString(), "http://localhost:8088/ok");
>       response.setHeader(HttpHeader.CONTENT_ENCODING.asString(), "gzip");
>       response.setContentType("text/plain");
>       response.setStatus(HttpServletResponse.SC_FOUND);
>     } else {
>       response.setContentType("text/plain");
>       response.setStatus(HttpServletResponse.SC_OK);
>     }
>     response.getWriter().write("ok");
>     baseRequest.setHandled(true);
>   }
> }

**Comment by grossws** [comment]
Ok, I'll track it here.

**Comment by sbordet** [comment]
Fixed by disabling content decoding - we are ignoring the content anyway.

**Comment by grossws** [comment]
Thanks :+1:
