### ISSUE TITLE
Why does SessionHandler.doStart() use some invalid code?

### ISSUE THREAD

**Issue by ph0ly** [eclipse/jetty.project#2660]
In jetty branch 'jetty-9.4.x', SessionHandler.doStart method at line 444:
`server.setSessionIdManager(_sessionIdManager);`
`server.manage(_sessionIdManager);`
`_sessionIdManager.start();`

Question1: 
When debug, i found that the _setSessionIdManager_ method already add the _sessionIdManager_ to container, and start it, why in next line use _server.manage_ to manage the _sessionIdManager_?

Question2:
Why jetty explicit call __sessionIdManager.start();_ , actually __sessionIdManager_ already start when _setSessionIdManager_？

Question3:
and at line 455:
`addBean(_sessionIdManager,false);`
The comment says that 'server session id is never managed by this manager', we see that when sessionIdManager is null, SessionHandler will create one, and the server will manage sessionIdManager, this line will cancel the SessionHandler manage, why?

Can anybody help me to understand this code, thank u very much?

**Comment by joakime** [comment]
@ph0ly if your `SessionHandler.setSessionIdManager()` was called, then [the lines of code from 430 to 456](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java#L430-L456) would never be called.

Questions 1, 2, and 3 are all moot if you had previously called `SessionHandler.setSessionIdManager()` before the start of the `LifeCycle` of the `SessionHandler`.

I'm curious, why do you feel you need to be debugging / stepping through the SessionHandler code?
What sort of error / condition / behavior are you experiencing where you feel you need to debug this?

**Comment by ph0ly** [comment]
@joakime I am studying this framework now, so i debug this code.

Actually my question is under the condition of _sessionIdManager == null is true, why the server.setSessionIdManager, then server.manage, and _sessionIdManager.start, in fact, server.setSessionIdManager will start the _sessionIdManager, why explicit call _sessionIdManager.start?

**Comment by janbartel** [comment]
server.setSessionidManager will add the bean as AUTO instead of MANAGED. We want it to be MANAGED instead so that it will stop when the server stops.

**Comment by ph0ly** [comment]
@janbartel server.setSessionIdManager will add the bean to server container, i think the server will auto start the _sessionIdManager, but why at line 446 explicit call _sessionIdManager.start?

**Comment by janbartel** [comment]
Looks like it's a superfluous call.

**Comment by ph0ly** [comment]
@janbartel thank u very much!

**Comment by janbartel** [comment]
OPs original question has been answered
