### ISSUE TITLE
Unnecessary boxing conversions

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#2662]
While digging through Jetty's source code, we found a couple of unnecessary conversions of primitive types to their boxed representations.

Most of them are of the following form:
```java
long value = Long.valueOf(someString);
```
Here, `Long.valueOf()` returns a boxed `Long` object just to unbox it immediately afterwards.
To avoid this, it should be changed to:
```java
long value = Long.parseLong(someString);
```
The same pattern applies to `int` and `boolean`.

Will create a pull request for this soon.

**Comment by gregw** [comment]
thanks
