### ISSUE TITLE
DoSFilter does not work with session managers that passivate

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#267]
migrated from Bugzilla [#484064](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484064)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.4.0* on platform *All*
Assigned to: Project Inbox

On 2015-12-10 01:39:12 -0500, Jan Bartel wrote:

> The DoSFilter.RateTracker class implements session binding and passivation listeners. The passivation listener removes the rate tracker matching the session from the list of trackers, and then removes the tracker attribute from the session. The activation listener does nothing.
> 
> Thus, if a session is ever passivated, its rate tracker is never re-established.
> 
> The DoSFilter.RateTracker class should be made properly serializable (it has all transient fields), and should only remove itself from the list of trackers upon passivation. Upon activation it should add itself into the list of trackers.  The class will have to be made public scope.

**Comment by janbartel** [comment]
Looks like this was fixed by a commit by gregw for bugzilla 484622 and was released with jetty-9.3.7.RC0.
