### ISSUE TITLE
Demo rewrite rules prevent URL Session tracking

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2675]
One of the rewrite rules used in the demo-base is removing the URL parameters so that session URL tracking cannot be used.

**Comment by joakime** [comment]
None of the rewrite rules seem to do that.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/tests/test-webapps/test-jetty-webapp/src/main/config/demo-base/etc/demo-rewrite-rules.xml

Are you sure they are not being removed by something within the ServletContext?

**Comment by joakime** [comment]
Can't find anything in the webapps deployed with demo-base that remove the URL session tracking.

What did you do to setup Session tracking?

**Comment by joakime** [comment]
There's no override descriptor or custom default descriptor that changes it.
There's also no `webapps/<context>.xml` content that modifies it as well.

**Comment by joakime** [comment]
Found it.

This block of code eliminates the request parameters.

https://github.com/eclipse/jetty.project/blob/4f544475853b1e1a7d8bdb161fe7bb34b5a3a3ff/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java#L187-L194

So, if the RuleContainer exists, and has at least 1 rule, and is using default RewriteHandler configuration, the request URL parameters are removed by that block of code.

**Comment by joakime** [comment]
Closing in favor of #4329
