### ISSUE TITLE
Add Tests for Session Tracking Mode URL

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2676]
In light of open issue #2675 it was discovered that we have no unit tests for Session Tracking Mode URL.

We also have no tests for null / undefined tracking modes  (in other words a descriptor that declares a `<tracking-mode>` element with no child elements)

Note sure how important this is, as URL Tracking Mode is the main way for Session Fixation attacks to work.
Many libraries now don't even allow this to be configured away from COOKIE anymore (spring, jersey, dropwizard, google app engine as some examples)

**Comment by olamy** [comment]
give this more time but we need it
