### ISSUE TITLE
Decode URI before matching against "/favicon.ico"

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#2677]
https://github.com/eclipse/jetty.project/blob/ada36ec4a9d408615886f3b70ab8aa8a7754d575/jetty-server/src/main/java/org/eclipse/jetty/server/handler/DefaultHandler.java#L93

Since `request.getRequestURI()` returns the raw path, it does not pass this check if some characters are percentage encoded.

Supporting a percentage encoded URL to the favicon might not be neccessary, but it does seem common.
For example, it's possible to access GitHub's favicon using the following URL:
https://github.com/%66avicon.ico

More importantly, this code serves as a template for how to match the request URI against some known paths in custom handlers, where usually the decoded URI is to be used.

Therefore, I think the comparison should be changed to:
```java
if (/*... &&*/ URIUtil.decodePath(request.getRequestURI()).equals("/favicon.ico"))
```

**Comment by gregw** [comment]
I think you are correct, but I'll look for another solution and double decoding the path is a waste of effort.  We should be able to access the decoded path already.

**Comment by mperktold** [comment]
That would be even better. 👍

One solution could be a static method which returns the decoded path of a `HttpServletRequest` and caches the result as a request attribute.

But that's just an idea.

**Comment by gregw** [comment]
@mperktold the target is already the decoded path, so I'll just compare to that.

@joakime you added an integration test called DefaultHandlerTest that does not even create a DefaultHandler, let alone test it.  So I've added a new DefaultHandlerTest unit test.   Can you check your existing test and perhaps rename it (looks more like a ResourceHandlerTest)
