### ISSUE TITLE
HTTP/2 Spec Compliance

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2679]
As revealed in h2spec v2.1.1 testrun.
Finished in 71.8993 seconds
146 tests, 108 passed, 0 skipped, 38 failed

See output: [h2spec_jetty-94x-HEAD.log](https://github.com/eclipse/jetty.project/files/2134648/h2spec_localhost.log)

The above results were from current `jetty-9.4.x` HEAD (at commit 6b335877d9cc8a6be0c61c5d6d2a559ab9035323)
Using `examples/embedded/src/main/java/org/eclipse/jetty/embedded/Http2Server.java`
on Open JDK 9.0.4

server command line:

    $ cd examples/embedded
    $ mvn exec:java -Dexec.mainClass=org.eclipse.jetty.embedded.Http2Server

h2spec command line: 

    $ ./h2spec --insecure --strict --host=localhost --port=8443 --tls --verbose > h2spec_localhost.log

**Comment by sbordet** [comment]
https://github.com/summerwind/h2spec/

**Comment by sbordet** [comment]
Work completed, all `h2spec` 2.1.1 tests are passing.

**Comment by joakime** [comment]
Jetty 9.4.12.v20180830 is now released and available.
