### ISSUE TITLE
Improve handling of Direct and Mapped buffers for static content

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#268]
migrated from Bugzilla [#484622](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484622)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Greg Wilkins

On 2015-12-17 20:05:22 -0500, Greg Wilkins wrote:

> The max buffer size for non cached content is not being set, thus direct nor indirect buffers are used if there is no cache and only a ByteChannel is used.
> 
> The ResourceCache also does not account correctly for mapped buffers and direct buffers in the total cached size.

**Comment by gregw** [comment]
This has been improved
