### ISSUE TITLE
ProxyServlet (and Transparent) are blocked in class loader (by design?)

### ISSUE THREAD

**Issue by tobias-** [eclipse/jetty.project#2680]
ProxyServlet (and the Transparent one which I need) are blocked in the class loader by WebAppContext, while e.g. DefaultServlet is not. The culprit seems to be a missing `"-org.eclipse.jetty.proxy."` in the `__dftServerClasses` in `org.eclipse.jetty.webapp.WebAppContext`.

The comment says that they need to be included in the war, but what's the point of having it as an enableable module, if it needs to be included in the war anyway?

If this should be fixed, it is a trivial fix for someone with a signed ECA.

I'm creating a ProxyServlet.Transparent() in a ServletContainerInitializer.onStartup() (war project) and get a `ClassNotFoundException` when trying to use it.

**Comment by joakime** [comment]
You can add an XML webapp deployable to manage the Jetty 9.4.x server classes yourself.

In your `${jetty.base}/webapps/` directory add an xml.

Lets say your webapp is called `myapp.war`, in that case your `${jetty.base}/webapps/` will have 2 files: `myapp.war` and `myapp.xml`

The `myapp.xml` could look like this ...

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/myapp</Set>
  <Set name="war"><Property name="jetty.webapps" default="."/>/myapp.war</Set>
  <Call name="prependServerClass">
    <Arg>-org.eclipse.jetty.proxy.</Arg>
  </Call>
</Configure>
```

**Comment by tobias-** [comment]
@joakime Thanks!

Closing this issue that turned into a support request. I have no problem with either way of doing it, but was stuck for several hours debugging classloaders before I found the comment mentioned in the initial post. The 10.x way of doing it will avoid causing somebody else the same headache.
