### ISSUE TITLE
Backport #1579 improvements to QuotedQualityCSV to Jetty 9.3.x

### ISSUE THREAD

**Issue by jebeaudet** [eclipse/jetty.project#2682]
Tested on `9.3.24.v20180605`, although version `9.4.11.v20180605` does not exhibit this issue, looks like `QuotedQualityCSV` had some extensive change in it.

Somewhat related to https://github.com/eclipse/jetty.project/issues/1351. Like the description says, Jetty will throw a `StringIndexOutOfBoundsException` on an invalid Accept-Language header.

Easy to reproduce, just send a request with the header `Accept-Language: en-US;es-ES,q=0.5`.

Relevant stack trace : 

```
StringIndexOutOfBoundsException: String index out of range: -1
org.eclipse.jetty.http.QuotedQualityCSV in parsedParam at line 90
org.eclipse.jetty.http.QuotedCSV in addValue at line 156
org.eclipse.jetty.http.QuotedQualityCSV in addValue at line 54
org.eclipse.jetty.http.HttpFields in getQualityCSV at line 441
org.eclipse.jetty.server.Request in getLocale at line 876
```

Thanks!

**Comment by joakime** [comment]
The current stable major version tree is `jetty-9.4.x`.
Is this report against the older major version `jetty-9.3.x`?

**Comment by jebeaudet** [comment]
yes it against `jetty-9.3.x`, I was just mentioning that the latest 9.4.x does not exhibit the issue.

**Comment by joakime** [comment]
This isn't quite right on `jetty-9.4.x` as well.

``` java
        // This test passes on jetty-9.4.x
        QuotedQualityCSV values = new QuotedQualityCSV();
        values.addValue(" en-US;es-ES,q=0.5");
        assertThat(values,contains("en-US;es-ES", ""));
```

On `jetty-9.4.x` the results from `addValue()` includes an empty entry with a quality of `0.5`

**Comment by joakime** [comment]
As far as this original issue is concerned, it's turning out to just be a request to backport #1579 to `jetty-9.3.x`

**Comment by jebeaudet** [comment]
Good catch on the content of the parsed header!

Thanks
