### ISSUE TITLE
Bad content in QuotedQualityCSV can result in empty entries

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2685]
When troubleshooting Issue #2682 (turns out to be a request to backport #1579 to `jetty-9.3.x`) it was discovered that the example provided will result in empty values on `jetty-9.4.x`.

This doesn't seem quite right, but I also think this behavior is ultimately harmless (there's nothing to match against with the value being empty).

``` java
        // This test passes on jetty-9.4.x
        QuotedQualityCSV values = new QuotedQualityCSV();
        values.addValue(" en-US;es-ES,q=0.5");
        assertThat(values,contains("en-US;es-ES", ""));
```

On `jetty-9.4.x` the results from `addValue()` includes an empty entry with a quality of `0.5`

**Comment by gregw** [comment]
https://tools.ietf.org/html/rfc7230#section-3.2.6
https://tools.ietf.org/html/rfc7230#section-7
https://tools.ietf.org/html/rfc7231#section-5.3.1

**Comment by gregw** [comment]
There is no real standard ABNF for weights, rather individual field definitions.  None of these really suggest that they support empty values as they all ultimately come down to `token [ weight ]` and token cannot be empty string (`1*tchar`).

So perhaps technically the value should be "q=0.5" and there be no weight for this one?

**Comment by joakime** [comment]
"this one" being bad from the start anyway :stuck_out_tongue_winking_eye:

I'm of the opinion that we just let this one be.
Can you see any fault/issue if the value is empty?

**Comment by gregw** [comment]
I tend to think we can let this be... but not so sure we really should :)

Without a ';' we really should not be treating the q=0.5 as a parameter...
let's leave this open for a bit and we can look a bit more at the parser to check exactly what is happening before we decide one way or the other.

**Comment by gregw** [comment]
@lachlan-roberts the question for you is why is ",q=0.5" being seen as a quality and not a value?  For it to be a quality, it must be seen as a parameter, but parameters should have a ; before them???    Would the string "foo,bar=0.5" result in values of ["foo",""] ?   I don't think so, so why should "foo,q=0.5"?
