### ISSUE TITLE
CachingWebAppClassLoader throws errors when webapp restarted

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#269]
migrated from Bugzilla [#484624](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484624)
status NEW severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.3.6_ on platform _PC_
Assigned to: Project Inbox

On 2015-12-17 20:18:39 -0500, Jan Bartel wrote:

> Restarting the test webapp with CachingWebAppClassLoader enabled throws:
> 
> 2015-12-18 12:08:02.998:WARN:oejw.StandardDescriptorProcessor:RMI TCP Connection(1)-127.0.0.1: Could not instantiate listener org.eclipse.jetty.servlet.listener.ELContextCleaner
> java.lang.ClassNotFoundException: org.eclipse.jetty.servlet.listener.ELContextCleaner: in notfound cache
>   at org.eclipse.jetty.webapp.CachingWebAppClassLoader.loadClass(CachingWebAppClassLoader.java:81)
>   at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
>   at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1659)
>   at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1893)
>   at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:83)
>   at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:70)
>   at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:402)
>   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1339)
>   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
>   at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
>   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
> 
> and
> 
> 2015-12-18 12:08:03.013:WARN:oejw.StandardDescriptorProcessor:RMI TCP Connection(1)-127.0.0.1: Could not instantiate listener org.eclipse.jetty.servlet.listener.IntrospectorCleaner
> java.lang.ClassNotFoundException: org.eclipse.jetty.servlet.listener.IntrospectorCleaner: in notfound cache
>   at org.eclipse.jetty.webapp.CachingWebAppClassLoader.loadClass(CachingWebAppClassLoader.java:81)
>   at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
>   at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1659)
>   at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1893)
>   at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:83)
>   at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:70)
>   at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:402)
>   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1339)
>   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
>   at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
>   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)

On 2015-12-17 20:43:34 -0500, Jan Bartel wrote:

> Note that this is only happening in jetty-9.3.x, and apparently only when using jmx to do the stop/start. Doesn't seem to happen if you stop/start via touching webapps/test.xml.

**Comment by janbartel** [comment]
@gregw  do we really need to keep the CachingWebAppClassLoader? It seems to have several problems, such as #260.

**Comment by gregw** [comment]
@janbartel We have at least one very very keen user of it, so while I think there are problems we need to review exactly their use case and triple check we can remove.

**Comment by gregw** [comment]
Not intending any more work on this
