### ISSUE TITLE
LdapLoginModule does not find accounts in subtrees

### ISSUE THREAD

**Issue by kasimon** [eclipse/jetty.project#2691]
The way LdapLoginModule determines the user name by concatenating the user to the basedn (
https://github.com/eclipse/jetty.project/blob/45472bf10bfe86201a47eda367917e0b02c8f352/jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java#L337). This fails when using nested LDAP structures, like the following

    ou=users
    - ou=team1,ou=users
      - uid=user1,ou=team1,ou=users
      - uid=user2,ou=team1,ou=users
    - ou=team2,ou=users
      - uid=user3,ou=team2,ou=users

This kind of setup is extremely common in real world ldap setups. Now if users from all teams are supposed to use the ldap authentication, the expected behaviour of a well-written ldap client is to *search* for the user below it's configured basedn instead of just concatenating the username to the basedn, assuming a flat structure. A quick google gave the following example on how to do this in java:

https://gist.github.com/jbarber/2909828#file-ldapauth-java-L37

or 

http://www.adamretter.org.uk/blog/entries/LDAPTest.java

**Comment by joakime** [comment]
Can you prepare a patch for this?

**Comment by kasimon** [comment]
I can try to come up with a patch, but my java is quite rusty. I'll see what I can do.

**Comment by janbartel** [comment]
@p-alik  please raise a PR on the jetty project with your patch.

**Comment by p-alik** [comment]
Thanks @janbartel. I'll do it during next week.
