### ISSUE TITLE
Bad DynamicImport-Package in Websocket Servlet

### ISSUE THREAD

**Issue by cdelg** [eclipse/jetty.project#2694]
Websocket Servlet has a dynamic import for packages in Websocket Server:

```xml
<DynamicImport-Package>
   org.eclipse.jetty.websocket.server.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}",
   org.eclipse.jetty.websocket.server.pathmap.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}"
</DynamicImport-Package>
```
however, wildcard package declarations match only subpackages not the content of the package itself. So pathmap is already dynamically imported by `org.eclipse.jetty.websocket.server.*` declaration and  the `org.eclipse.jetty.websocket.server` package is not imported. This leads to a class path exception when the Websocket Servlet bundle try to load a class from the `org.eclipse.jetty.websocket.server` package.

The correct import is:

```xml
<DynamicImport-Package>
   org.eclipse.jetty.websocket.server;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}",
   org.eclipse.jetty.websocket.server.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}"
</DynamicImport-Package>
```

**Comment by janbartel** [comment]
Thanks @cdelg, do you want to contribute a patch for that?

**Comment by cdelg** [comment]
Yes, can you give me a pointer on what you expect for this kind of contribution?

Also, what do you prefer between these propositions:

1. If new subpackages are added to the  `org.eclipse.jetty.websocket.server` they will be imported by the Websocket Servlet bundle without modification.
```xml
<DynamicImport-Package>
   org.eclipse.jetty.websocket.server;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}",
   org.eclipse.jetty.websocket.server.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}"
</DynamicImport-Package>
```

2. If new subpackages are added to the  `org.eclipse.jetty.websocket.server`, the Websocket Servlet bundle will need to be updated to able to import the new subpackages. I think it's safer and that it was the intended behaviour (Websocket Server contains only this 2 packages: `org.eclipse.jetty.websocket.server` and `org.eclipse.jetty.websocket.server.pathmap`). 

```xml
<DynamicImport-Package>
   org.eclipse.jetty.websocket.server;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}",
   org.eclipse.jetty.websocket.server.pathmap;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}"
</DynamicImport-Package>
```
