### ISSUE TITLE
GcloudDataStore dependency generation broken

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2696]
The build uses some ant scripts to auto generate the list of dependencies for gcloud based off the pom. Under java 9 this is broken, file names that are generated look like this:
```text
'api-common-1.0.0.jar'$'\033''[36m -- module api.common'$'\033''[0;1;33m (auto)'$'\033''[m'
'auto-value-1.1.jar'$'\033''[36m -- module auto.value'$'\033''[0;1;33m (auto)'$'\033''[m'
'commons-codec-1.3.jar'$'\033''[36m -- module commons.codec'$'\033''[0;1;33m (auto)'$'\033''[m'
'commons-logging-1.1.1.jar'$'\033''[36m -- module commons.logging'$'\033''[0;1;33m (auto)'$'\033''[m'
'datastore-v1-proto-client-1.3.0.jar'$'\033''[36m -- module datastore.v1.proto.client'$'\033''[0;1;33m (auto)'$'\033''[m'
```
This might be to do with either the java version or some update to some of the plugins in the build.

**Comment by joakime** [comment]
wow.

We should add some integration tests for this then.
that would have caught this kind of issue sooner.

**Comment by janbartel** [comment]
PR applied to jetty-9.4.x branch in time for 9.4.12.
