### ISSUE TITLE
Failing test under jdk9: org.eclipse.jetty.websocket.client.ClientCloseTest.testProtocolException

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2698]
Error Message
Client Open Sessions
Expected: an empty collection
     but: <[WebSocketSession[websocket=JettyListenerEventDriver[org.eclipse.jetty.websocket.client.ClientCloseTest$CloseTrackingSocket],behavior=CLIENT,connection=WebSocketClientConnection@e01714a8[ios=IOState@6785df10[CLOSED,!in,!out,finalClose=CloseInfo[code=1002,reason=Invalid control frame payload length, [402] cannot exceed [125]],clean=false,closeSource=ABNORMAL],f=Flusher@144440f5[queueSize=0,aggregateSize=-1,terminated=java.nio.channels.ClosedChannelException],g=Generator[CLIENT,validating],p=Parser@3e2c8ef[ExtensionStack,s=PAYLOAD_LEN_BYTES,c=0,len=402,f=null]]<-TestEndPoint@290807e5{localhost/127.0.0.1:39805<->/127.0.0.1:47478,CLOSED,fill=-,flush=-,to=4/1000}{io=0/0,kio=-1,kro=-1}->WebSocketClientConnection@e01714a8[ios=IOState@6785df10[CLOSED,!in,!out,finalClose=CloseInfo[code=1002,reason=Invalid control frame payload length, [402] cannot exceed [125]],clean=false,closeSource=ABNORMAL],f=Flusher@144440f5[queueSize=0,aggregateSize=-1,terminated=java.nio.channels.ClosedChannelException],g=Generator[CLIENT,validating],p=Parser@3e2c8ef[ExtensionStack,s=PAYLOAD_LEN_BYTES,c=0,len=402,f=null]],remote=WebSocketRemoteEndpoint@60bc308b[batching=true],incoming=JettyListenerEventDriver[org.eclipse.jetty.websocket.client.ClientCloseTest$CloseTrackingSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.client.io.WebSocketClientConnection]]]>
Stacktrace
java.lang.AssertionError: Client Open SessionsExpected: an empty collection     but: <[WebSocketSession[websocket=JettyListenerEventDriver[org.eclipse.jetty.websocket.client.ClientCloseTest$CloseTrackingSocket],behavior=CLIENT,connection=WebSocketClientConnection@e01714a8[ios=IOState@6785df10[CLOSED,!in,!out,finalClose=CloseInfo[code=1002,reason=Invalid control frame payload length, [402] cannot exceed [125]],clean=false,closeSource=ABNORMAL],f=Flusher@144440f5[queueSize=0,aggregateSize=-1,terminated=java.nio.channels.ClosedChannelException],g=Generator[CLIENT,validating],p=Parser@3e2c8ef[ExtensionStack,s=PAYLOAD_LEN_BYTES,c=0,len=402,f=null]]<-TestEndPoint@290807e5{localhost/127.0.0.1:39805<->/127.0.0.1:47478,CLOSED,fill=-,flush=-,to=4/1000}{io=0/0,kio=-1,kro=-1}->WebSocketClientConnection@e01714a8[ios=IOState@6785df10[CLOSED,!in,!out,finalClose=CloseInfo[code=1002,reason=Invalid control frame payload length, [402] cannot exceed [125]],clean=false,closeSource=ABNORMAL],f=Flusher@144440f5[queueSize=0,aggregateSize=-1,terminated=java.nio.channels.ClosedChannelException],g=Generator[CLIENT,validating],p=Parser@3e2c8ef[ExtensionStack,s=PAYLOAD_LEN_BYTES,c=0,len=402,f=null]],remote=WebSocketRemoteEndpoint@60bc308b[batching=true],incoming=JettyListenerEventDriver[org.eclipse.jetty.websocket.client.ClientCloseTest$CloseTrackingSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.client.io.WebSocketClientConnection]]]>	at org.eclipse.jetty.websocket.client.ClientCloseTest.testProtocolException(ClientCloseTest.java:458)

**Comment by joakime** [comment]
This means Issue #2655 might need to be reopened.

**Comment by joakime** [comment]
Closing.  This hasn't been seen again in a few months.
