### ISSUE TITLE
Context specific LoginService causes context restart to fail under jmx

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#270]
migrated from Bugzilla [#484625](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484625)
status NEW severity *normal* in component *server* for *9.3.x*
Reported in version *9.3.6* on platform *All*
Assigned to: Project Inbox

On 2015-12-17 20:51:33 -0500, Jan Bartel wrote:

> 2015-12-18 12:39:39.944:WARN::RMI TCP Connection(4)-127.0.0.1: test webapp is deployed. DO NOT USE IN PRODUCTION!
> 2015-12-18 12:39:40.387:WARN:oejw.WebAppContext:RMI TCP Connection(4)-127.0.0.1: Failed startup of context o.e.j.w.WebAppContext@7b227d8d{/test,file:///tmp/jetty-0.0.0.0-8443-test.war-_test-any-6881984275708105224.dir/webapp/,STARTING}{/test.war}
> java.lang.IllegalStateException: No LoginService for org.eclipse.jetty.security.authentication.FormAuthenticator@5495333e in org.eclipse.jetty.security.ConstraintSecurityHandler@68034211
> 	at org.eclipse.jetty.security.authentication.LoginAuthenticator.setConfiguration(LoginAuthenticator.java:76)
> 	at org.eclipse.jetty.security.authentication.FormAuthenticator.setConfiguration(FormAuthenticator.java:131)
> 	at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:354)
> 	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:448)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
> 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:93)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
> 	at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:116)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
> 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:93)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
> 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:801)
> 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:346)
> 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1380)
> 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
> 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
> 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:518)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.eclipse.jetty.jmx.ObjectMBean.invoke(ObjectMBean.java:553)
> 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
> 	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
> 	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1471)
> 	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
> 	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1312)
> 	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1404)
> 	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:832)
> 	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
> 	at sun.rmi.transport.Transport$1.run(Transport.java:200)
> 	at sun.rmi.transport.Transport$1.run(Transport.java:197)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
> 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
> 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
> 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$95(TCPTransport.java:683)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> 
> To reproduce, comment out use of the etc/test-realm.xml in start.ini. Enable jmx. Do normal java -jar start.jar.  Use jconsole to connect to the server and stop and restart the test webapp.
> 
> Doesn't happen if you restart the webapp via the Deployer.

**Comment by janbartel** [comment]
Tested with 9.3.10 and does not happen any more.
