### ISSUE TITLE
current default for headerCacheSize is not large enough for many requests

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#2709]
PR #2707
> I was writing a jmh benchmark for the the HttpParser and found that the 512 bytes of the _fieldCache wasn't enough to cache all the headers in the sample requests I was using. Then in a call with @gregw and @sbordet I showed how much cache was needed for a few sample requests I captured which some used around 1kB of cache. Simone suggested using 4kB.

**Comment by gregw** [comment]
We have some feedback that 4kb is frequently wasting memory. Trading the PR, it seams that 1k would have been sufficient, so we should probably dial back to that.

**Comment by joakime** [comment]
PR #4292 is closed
