### ISSUE TITLE
Support HSTS

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#271]
migrated from Bugzilla [#484657](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484657)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Greg Wilkins

On 2015-12-18 06:08:04 -0500, Simone Bordet wrote:

> In order to get A+ ratings on https://www.ssllabs.com/, the HSTS header defined by https://tools.ietf.org/html/rfc6797 should be provided.
> 
> This can probably be added to HttpConfiguration as: 
> 
> setStrictTransportSecurity(long) 
> 
> with perhaps a default of 90 days (i.e. 90*24*3600=4458000) - 90 days is the default validity for letsencrypt.com certificates (https://letsencrypt.org/2015/11/09/why-90-days.html)

On 2015-12-23 00:42:33 -0500, Greg Wilkins wrote:

> It is probably better to just create a StrictTransportSecurityCustomizer.
> 
> I know that customizers are really called for requests, but it can navigate to the response and add the required header.
> 
> By making it a customizer, it should be easier to support more diverse parameters and user extension.
> 
> I'll do a proof of principal... stand by....

On 2015-12-23 01:16:24 -0500, Greg Wilkins wrote:

> I have pushed a simple implementation where I have just added it to the existing SecureRequestCustomizer
> 
> 19d6e36  in 9.3.x branch.    
> 
> Happy to discuss alternatives, so will leave this open for now.

On 2015-12-23 05:15:30 -0500, Simone Bordet wrote:

> Greg, I'm fine using SecureRequestCustomizer.
> 
> Can you please add a couple of properties in jetty-ssl.xml (end of file, where the SecureRequestCustomizer is instantiated) so that HSTS can be configured via start.ini ?

**Comment by gregw** [comment]
done
