### ISSUE TITLE
Async requests are not considered when shutting down gracefully

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#2717]
I'm trying to enhance Spring Boot's Jetty integration to optionally gracefully shut down Jetty. It's working nicely for synchronous requests but does not work for asynchronous requests. If I call `StatisticsHandler.shutdown` when there's a single asynchronous request in progress, the returned future is completed immediately rather than only completing once the request has completed. 

Here's the stats HTML captured at the time of `StatisticsHandler` [calling `shutdown.succeeded()`](https://github.com/eclipse/jetty.project/blob/9c1579640392fb2fca117145c4f307cde5254b95/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java#L588):

```
<h1>Statistics:</h1>
Statistics gathering started 14026ms ago<br />
<h2>Requests:</h2>
Total requests: 1<br />
Active requests: 1<br />
Max active requests: 1<br />
Total requests time: 0<br />
Mean request time: 0.0<br />
Max request time: 0<br />
Request time standard deviation: 0.0<br />
<h2>Dispatches:</h2>
Total dispatched: 1<br />
Active dispatched: 0<br />
Max active dispatched: 1<br />
Total dispatched time: 32<br />
Mean dispatched time: 32.0<br />
Max dispatched time: 32<br />
Dispatched time standard deviation: 0.0<br />
Total requests suspended: 1<br />
Total requests expired: 0<br />
Total requests resumed: 0<br />
<h2>Responses:</h2>
1xx responses: 0<br />
2xx responses: 0<br />
3xx responses: 0<br />
4xx responses: 0<br />
5xx responses: 0<br />
Bytes sent total: 0<br />
```

**Comment by joakime** [comment]
Interesting.  Do you have a testcase or demo project demonstrating this we can use?

**Comment by sbordet** [comment]
Uhm. Don't you have a `CountDownLatch` with count=1, but make 2 requests?

What happens if you first try `/async` and then `/sync`?

**Comment by wilkinsona** [comment]
I guess you haven't tried running the example. Calling `/sync` causes the JVM to exit after the request has completed. That why I said "Start the server again and make a request to `/async`" in the instructions above.

**Comment by sbordet** [comment]
Now I ran the example :smiley: 

To discuss your original intent, shutting down gracefully a server that may be bombed with requests is kind of hard, but here's what I suggest:

1. Call `ServerConnector.setAccepting(false)`. This will stop Jetty from accepting new connections.

2. Now you need a way to cancel new requests arriving in existing connections.
This can be done in a custom handler that is the first to be hit and that somehow can be notified when it needs to start rejecting requests.

3. Then you need to wait for existing requests to finish.
Jetty's `Server` class inherits a `stopTimeout` that can be set to a desired value (by default 30 s).
Stopping the `Server` will tap into the `shutdown()` method which will return a future that Jetty will wait on.

Unfortunately,  `StatisticsHandler` waits until `_dispatchedStats.getCurrent() == 0` but that is not correct, it should have waited on `_requestStats.getCurrent() == 0`. @gregw your thoughts here?
If I modify `StatisticsHandler` to wait on `_requestStats` @wilkinsona's case will work fine.

@wilkinsona if you don't have 2. then it may be that `getCurrent()` never goes to zero, and eventually the `stopTimeout` will elapse and forcibly close connections - so it's really your call if you want to implement 2. for a more graceful shutdown, or if the existing mechanism (without 2.) is enough for you.
