### ISSUE TITLE
NPE using more than one Endpoint.publish

### ISSUE THREAD

**Issue by mattiasbe** [eclipse/jetty.project#2718]
Using the http-spi with jetty works fine on older java versions such as jdk 8_u74 
Using a JDK later than 8_u162 (or maybe 151+?) (the latest java 8 u172 fails for example).
Works if only calling ` Endpoint.publish(...)` once on all versions.

Base example without setting Jetty as provider, works fine. If setting jetty as provider it fails if the second publish is there.

```
 Endpoint.publish(String.format("http://%s:%d/hello", host, port), new Ws());
 Endpoint.publish(String.format("http://%s:%d/hello2", host, port), new Ws());
 System.out.printf("Started, check: http://localhost:%d/hello?wsdl%n", port);
```

Find attached file (scratch.zip) with a simple test case (also with a working example without jetty as well). Works fine on older java as per above, fails on newer with:

```
Exception in thread "main" com.sun.xml.internal.ws.server.ServerRtException: Server Runtime Error: java.lang.NullPointerException
	at com.sun.xml.internal.ws.transport.http.server.ServerMgr.createContext(ServerMgr.java:130)
	at com.sun.xml.internal.ws.transport.http.server.HttpEndpoint.publish(HttpEndpoint.java:64)
	at com.sun.xml.internal.ws.transport.http.server.EndpointImpl.publish(EndpointImpl.java:232)
	at com.sun.xml.internal.ws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:126)
	at javax.xml.ws.Endpoint.publish(Endpoint.java:240)
	at scratch.EndpointMultiplePublishProblem.mainJetty(EndpointMultiplePublishProblem.java:45)
	at scratch.EndpointMultiplePublishProblem.main(EndpointMultiplePublishProblem.java:19)
Caused by: java.lang.NullPointerException
	at com.sun.xml.internal.ws.transport.http.server.ServerMgr.createContext(ServerMgr.java:88)
	... 6 more
```

**Attachment:**
[scratch.zip](https://github.com/eclipse/jetty.project/files/2196130/scratch.zip)

**Test case inline as well:**

```
package scratch;

import javax.jws.WebService;
import javax.xml.ws.Endpoint;

import org.eclipse.jetty.http.spi.DelegatingThreadPool;
import org.eclipse.jetty.http.spi.JettyHttpServerProvider;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.handler.ContextHandlerCollection;
import org.eclipse.jetty.util.thread.QueuedThreadPool;

public class EndpointMultiplePublishProblem {
    static int    port = 8081;
    static String host = "0.0.0.0";

    public static void main(String[] args) throws Exception {
        // mainDefaultImpl(args); //works
        mainJetty(args); // fails on 8u172 (u162+ or so)
    }

    public static void mainDefaultImpl(String[] args) throws Exception {
        Endpoint.publish(String.format("http://%s:%d/hello", host, port), new Ws());
        Endpoint.publish(String.format("http://%s:%d/hello2", host, port), new Ws());
        System.out.printf("Started, check: http://localhost:%d/hello?wsdl%n", port);
    }

    public static void mainJetty(String[] args) throws Exception {
        System.setProperty("com.sun.net.httpserver.HttpServerProvider", JettyHttpServerProvider.class.getName());

        // Can't just do new Server(8081); built-in http server expects a DelegatingThreadPool ?
        // So instead of a one-liner all these are needed:
        Server jettyWebServer = new Server(new DelegatingThreadPool(new QueuedThreadPool()));
        ServerConnector connector = new ServerConnector(jettyWebServer);
        connector.setHost(host);
        connector.setPort(port);
        connector.setReuseAddress(true);
        jettyWebServer.addConnector(connector);
        jettyWebServer.setHandler(new ContextHandlerCollection());

        JettyHttpServerProvider.setServer(jettyWebServer);

        Endpoint.publish(String.format("http://%s:%d/hello", host, port), new Ws());
        // Comment out the below line for success in later java such as java8_u172, works before u151 or so
        Endpoint.publish(String.format("http://%s:%d/hello2", host, port), new Ws());

        jettyWebServer.start();

        System.out.printf("Started, check: http://localhost:%d/hello?wsdl%n", port);

    }

    @WebService
    public static class Ws {
        public String hello() {
            return "Hello";
        }
    }
}

```

**Comment by mattiasbe** [comment]
This jdk change seems to be the cause, it now checks the port of the address (inetaddress). If memory serves this can be null with jetty for delayed bind or similar.

Added with 8u152:
 if (s.getServer()
                             .getAddress()
                             .getPort() == finalPortNum) {

https://bugs.java.com/view_bug.do?bug_id=JDK-8146086
getPort line is line 88.

http://hg.openjdk.java.net/jdk8u/jdk8u/jaxws/file/9b94b2a51e16/src/share/jaxws_classes/com/sun/xml/internal/ws/transport/http/server/ServerMgr.java

**Comment by olamy** [comment]
is it really Jetty project related? I'm not quite sure what we can do to help here.

**Comment by mattiasbe** [comment]
Well it works fine if not setting jetty as the provider and it fails if jetty is set as the provider.

**Comment by olamy** [comment]
@mattiasbe ok.
but what about your comment ```  Comment out the below line for success in later java such as java8_u172, works before u151 or so ``` 
does it work with Jetty for java versions previous u151?

**Comment by joakime** [comment]
We should also make sure that `JettyHttpServerProvider.setServer(Server)` checks for the required `server.getThreadPool() implements DelegatingThreadPool` behavior and fail if Server is not setup this way.

**Comment by mattiasbe** [comment]
Well @joakime jetty checks for instanceof DelegatingThreadpool already and throws an exception if not.

Minor detail: I wouldn't mind an overload or two of the Server constructor which could specify the threadpool along with ip and port. Not a big thing though.

**Comment by gregw** [comment]
I don't understand why the example is calling setServer on the provider in the first place?   Shouldn't it just be using HttpServer.create()... or not even creating the server and letting the ws stuff do it instead?

It is a pain that we need the DelegatingThreadPool..... which actually needs to be updated to support the TryExecutor API if we want this to be efficient.

**Comment by olamy** [comment]
merged in jetty-9.4.x

**Comment by mattiasbe** [comment]
Hello again, this solves the exception but it won't actually start the handlers it seems.
The test case doesn't crash anymore but actually checking the wsdl url as stated in the example shows nothing and checking the base url (no path) gives:

> Error 404 - Not Found.
> No context on this server matched or handled this request.
> Contexts known to this server are:
> /hello ---> o.e.j.h.s.HttpSpiContextHandler@36d4b5c{/hello,null,UNAVAILABLE} [stopped]
> /hello2 ---> o.e.j.h.s.HttpSpiContextHandler@18be83e4{/hello2,null,UNAVAILABLE} [stopped]

Using the example in the test case:
jetty.project/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestEndpointMultiplePublishProblem.java

Checking the url: http://localhost:8081/hello?wsdl
![image](https://user-images.githubusercontent.com/1568245/45362274-b5a53f00-b5d4-11e8-82ed-2dee050a7bbc.png)

And base url with no path, jetty says:
![image](https://user-images.githubusercontent.com/1568245/45362210-8d1d4500-b5d4-11e8-85e9-aa0409722945.png)

**Comment by olamy** [comment]
@mattiasbe sorry I forgot to work on that one. I will have a look now.

**Comment by joakime** [comment]
Opened PR #3145

**Comment by olamy** [comment]
fixed with https://github.com/eclipse/jetty.project/commit/b4ab8a07c12cd8c3bd5f242b02ab37c61ab06676
