### ISSUE TITLE
Expose interesting HTTP/2 attributes and operations via JMX

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#273]
migrated from Bugzilla [#484818](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484818)
status ASSIGNED severity *enhancement* in component *http2* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Simone Bordet

On 2015-12-22 15:08:24 -0500, Simone Bordet wrote:

> The HTTP/2 implementation exposes little or no details about its internals to JMX, we should do better.

**Comment by sbordet** [comment]
HTTP/2 details have now been exposed to JMX.
