### ISSUE TITLE
AuthenticationProtocolHandler Multiple Challenge Pattern

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#2739]
If one of the authentication param's contain a string containing a comma, followed by some characters and followed by a space, while this is legal inside a quoted-string the CHALLENGE_PATTERN regex will see this as an additional challenge

for example this a test containing the challenge `"Digest param=\",f \""` would currently fail, as the "f" is being seen as an additional challenge.

```
    @Test
    public void testSingleChallangeLooksLikeMultipleChallenge()
    {
        AuthenticationProtocolHandler aph = new WWWAuthenticationProtocolHandler(client);
        List<HeaderInfo> headerInfoList = aph.getHeaderInfo("Digest param=\",f \"");
        Assert.assertEquals(1, headerInfoList.size());
    }
```

**Comment by gregw** [comment]
I think that using a regex to split this is not the right approach as it cannot well handle quotes.
Probably best to split the list into elements using `QuotedCSV` class and then have a state machine that processes each element of the list checking for challenges, token68s and/or auth-param
