### ISSUE TITLE
AsyncMiddleManServlet hangs on response when end-point server answers Content-Length header with value less than actual

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#274]
migrated from Bugzilla [#484881](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484881)
status NEW severity *major* in component *proxy* for *9.3.x*
Reported in version *9.2.10* on platform *PC*
Assigned to: Simone Bordet

On 2015-12-24 08:16:40 -0500, Felix Basin wrote:

> Had found this case in our application on next case:
> nginx-based web server answer in headers that resource is gziped and its Content-Length is .... (value was less than unpacked resource), but in reality resource was unpacked.
> 
> In try of getting this resource in browser through proxy - browser hangs on page loading. As I noticed it happens by next reason
> 
> public void onContent(...) {
> ..
> // this line never been true if contentLength > length
> boolean finished = contentLength > 0 && length == contentLength;
> }
> 
> My suggested fix:
> ...
> length += contentBytes;
> // Begin of inserted code
> if (length > contentLength) {
>   contentLength = -1;
>   proxyResponse.setContentLength(-1);
> }
> // End of inserted code

**Comment by sbordet** [comment]
The suggested fix won't work because in general it will not be possible to change the `proxyResponse` content length at this late stage: the `proxyResponse` headers may have long been committed.

The fact that the server sends a `Content-Length` header with a value, but then actual data that is different than what advertised is a server bug.

There is not much we can do in `AsyncMiddleManServlet` to protect against bad servers.

**Comment by korvindest** [comment]
It really helps to protect against bad servers. It allows downloading all stream instead of stop in the "middle" of a file. Issue that I faced was a part of file after AsyncMiddleManServlet.

**Comment by sbordet** [comment]
@korvindest there _is_ protection against bad servers: the connection will be eventually idle timed out.

If you have ideas of how to recover from a server that tells that the content is gzipped and of length X, but then sends non-gzipped content of length Y, we accept contributions.

If you have a case that is trivially recoverable, let's discuss it.

**Comment by gregw** [comment]
Note the main concern would be if Jetty is holding a thread while waiting for the bad server.  I don't believe it is, so there is nothing much more we can do about a server that lies to its clients about how much content it will send.
