### ISSUE TITLE
Jetty OSGI Classloader in 9.4.8 is inconsistent

### ISSUE THREAD

**Issue by rvinjamu** [eclipse/jetty.project#2740]
Hi, 
Recently we migrated from Jetty 9.3.9 to Jetty 9.4.8 in our Eclipse based Application embedding Jetty.  We started facing classloading issues because of the inconsistency between the single argument loadClass method overridden in OsgiWebAppClassLoader and the two argument loadClass method inherited from the super class WebAppClassLoader. The former loads classes from the '_contributor' OSGI Bundle class loader while the latter loads from WEB-INF/lib jars and WEB-INF/classes. Let me explain the scenario that we have and the classloading invocation sequence that spoils things for us 

All the activity happens in a web application running in embedded Jetty in our OSGI container (eclipse).

1. We have two interfaces com.xyz.IntSub and com.xyz.IntSup - IntSub extends from IntSup, the quirk is that IntSup has package access in the package com.xyz . Both of these classes are archived in a library mylib.jar placed in web-inf/lib. These two classes are also present in the contributor osgi bundle say com.xyz.SomeBundle

2. We have a factory class say com.xyz.pqr.Factory that needs to be loaded from a configured jar URL using a URLClassLoader. Let us call the jar as factory.jar.  The URLClassLoader is created with the thread context classloader as parent - and in the web application, it would be OsgiWebAppClassLoader. The factory class com.xyz.pqr.Factory refers to the interface com.xyz.IntSub

Let us examine the following invocation sequence. 
Class myFactoryClass = URLClassLoader.loadClass(com.xyz.pqr.Factory)
Object factoryObject = myFactoryClass.newInstance()
     > ................
     > ................
     > results in URLClassLoader.loadClass(IntSub, resolve flag)
                Now as IntSub is not present in factory.jar, the call is delegated to parent.
        >> OsgiWebAppClassLoader.loadClass(IntSub, resolveFlag)
                       This finds the class in web-inf/lib/mylib.jar and proceeds to define it
             ..........
             >>>ClassLoader#defineClass(IntSub)
                          The referred super class IntSup is sought to be loaded now
                   >>>> OsgiWebappClassLoader#loadClass(IntSup) - Note that the single arg variant of loadClass is called which is overridden in OsgiWebAppClassLoader - this seeks to load the class using the contributor osgi bundle -  com.xyz.SomeBundle
 
Now we have the subclass IntSub loaded by OsgiWebAppClassLoader to be linked with IntSup loaded by OSGI Bundle ClassLoader#com.xyz.someBundle and IntSup has package access. Thus it results in an Illegal Access Error. 

If we look up javadoc for loadClass methods, it recommends that the single argument variant should be equivalent to calling the two argument method with resolve flag as false.  This is not the case in the Jetty 9.4.8 OsgiWebAppClassLoader - the two loadClass methods differ in where they load classes from.

**Comment by joakime** [comment]
_Not an answer to the question_
You should probably upgrade to Jetty 9.4.11 due to CVEs.
https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00123.html

**Comment by janbartel** [comment]
@rvinjamu can you explain why the IntSup and IntSub classes are in a jar file in web-inf/lib and also deployed as bundles in your osgi container? Why not just one or the other? Can you explain how your webapp is packaged (is it a bundle with a nested web-inf/lib directory?) and deployed?

**Comment by janbartel** [comment]
@rvinjamu whilst you definitely should not have your classes in 2 places (ie the webapp bundle and also other bundles), I think there has been a behaviour change in 9.4 wrt classloading.  So I've made a tentative fix.  Please can you checkout out, build and test branch jetty-9.4.x-2740-osgi-classloader-use-bundleloader in your environment and let me know if that solves your issue?

**Comment by rvinjamu** [comment]
Hi, Thanks for looking into the issue. Our product is OSGI based. We are using Eclipse Equinox as the OSGI container. We organized all our code as logical OSGI plugins.  But given the requirements for API extensions, we had to surface the public interfaces. Same time we did not want to disturb the logical packaging of these classes in the various plugins. We took recourse to the OSGI Framework extension to the System bundle to surface these API classes at a higher level to avoid class casting issues.  

I will test the fix asap. 
regards

**Comment by janbartel** [comment]
@rvinjamu any progress?

**Comment by joakime** [comment]
PR opened at #2804

**Comment by rvinjamu** [comment]
Hi, tested it out. No longer face this issue now. Thanks.
