### ISSUE TITLE
Idle timeout doesn't work when request is blocked on reading content

### ISSUE THREAD

**Issue by mingyu89** [eclipse/jetty.project#2741]
Jetty version 9.2.10
We saw requests last for days and in the thread dump, it's blocking on
<img width="603" alt="screen shot 2018-07-19 at 4 57 53 pm" src="https://user-images.githubusercontent.com/12734110/42972437-0e786092-8b75-11e8-8ca5-151aed4a9f1b.png">

The SharedBlockingCallback has default idle timeout value of -1. And HttpInputOverHTTP doesn't overwrite this value. So once we are blocking on reading request content, we may wait forever.

In the mean time HttpOutput does overwrite the timeout to __channel.getIdleTimeout()_. So I assume for output stream the idle timeout does work.

**Comment by joakime** [comment]
Jetty 9.2 is EOL (End of Life).

https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

Consider upgrading to something supported and stable.

**Comment by djscholl** [comment]
Hi @joakime - it's me again. Mingyu works with me. As mentioned in other threads we do want to upgrade to something newer but the slight changes in behavior around "technically invalid http requests" are giving us pause and are going to require us to do some homework before making the upgrade.

Is your statement meant to be an acknowledgement that 9.2.10 has a bug in that Jetty will block forever on an input stream that's not receiving any data? Or was it more of a blanket "That release is no longer supported and I don't want to spend time looking into this". Both answers are valid, just wondering which yours was! Thanks!

**Comment by joakime** [comment]
> Reminder: Jetty versioning (since 1995) is `<servlet_support>.<major_version>.<minor_version>`

9.2.x as a whole is very old.   
Lots of changes have been made to both major versions 9.3.x and 9.4.x.
9.2.10 as a specific version is also old within the 9.2.x major version release, its not even the most recent minor release version. (9.2.25.v20180606 was the last release, to address CVEs).

We do not and can not spend time supporting / debugging / troubleshooting / patching old EOL versions (we sometimes make exceptions for specific vulnerabilities).

We typically have 2 major versions active / stable, with 1 major version in development.
Currently the active / stable major versions are 9.3.x and 9.4.x. (both Servlet 3.1)
With the development version being 10.0.x. (Servlet 4.x)

**Comment by joakime** [comment]
Some numbers for you ...

* Jetty 9.2.10 to 9.2.25 diff (3 years, 15 releases, and 332 commits in difference) - https://github.com/eclipse/jetty.project/compare/jetty-9.2.10.v20150310...jetty-9.2.25.v20180606
* Jetty 9.2.25 to 9.4.11 diff (36 releases, and 5,670 commits in difference) - https://github.com/eclipse/jetty.project/compare/jetty-9.2.25.v20180606...jetty-9.4.11.v20180605

**Comment by mingyu89** [comment]
Not a Jetty issue. Thank you @joakime
