### ISSUE TITLE
ManagedSelector 100% CPU spin

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2755]
`HttpClientTransportOverHTTP2Test.testConnectionIdleTimeoutSendsResetFrame()` sometimes produces a 100% CPU spin, while still passing the test.

**Comment by sbordet** [comment]
Analysis showed that the test triggers a race condition between `ManagedSelector.start()` and `ManagedSelector.stop()`.

`ManagedSelector.start()` submits an action to set `_started` to `true`, but `stop()` is called before that action is run. This causes the logic in `ManagedSelector.doStop()` to be skipped as `_started` is not yet `true` and so the `StopSelector` action is not run, leaving the selector into `select()`.

Because `ManagedSelector.stop()` is triggered by `HttpClient.stop()`, that also stops the `QueuedThreadPool`, it happens that the thread waiting in `select()` cannot be stopped in `QueuedThreadPool.doStop()`, and so `QueuedThreadPool` attempts to `interrupt()` the thread waiting in `select()`.

This wakes up the thread, but there are no checks of whether the thread is interrupted or whether `ManagedSelector` is still running, so the selection loop continues, `select()` is called again but returns immediately because the thread is interrupted, causing the 100% CPU spin.

**Comment by sbordet** [comment]
@gregw can you please review #2756 and give your thoughts on the fix?

**Comment by bjorncs** [comment]
Hi @sbordet. Do you know which Jetty versions are affected by this bug?

**Comment by joakime** [comment]
@bjorncs please try 9.4.12.RC2, it has the commit that @sbordet made about this issue.

**Comment by joakime** [comment]
@bjorncs also note this specific issue is only triggered if you stop/start the HttpClient rather frequently.

**Comment by bjorncs** [comment]
We have observed behaviour in our Jetty integration in production similar to what is described here (9.4.11). We decided to downgrade to 9.4.10 while waiting for 9.4.12 to be released. Is it likely that 9.4.10 contains the same bug as well? Any ETA on 9.4.12 release? :)

**Comment by sbordet** [comment]
@bjorncs 9.4.12 should be this week.

Can you detail your case? I find strange that you are hitting this case, which happens only rarely in tests (where `HttpClient` is started and stopped very rapidly).
