### ISSUE TITLE
how do i send all logs including web request logs to stdout w/ jetty-runner?

### ISSUE THREAD

**Issue by dfuentes77** [eclipse/jetty.project#2759]

**Comment by joakime** [comment]
You start by not using jetty-runner, it's deprecated.

Switch to `jetty-home` and `jetty-base`
Set the logging to use SLF4J, then configure your RequestLog implementation to also use SLF4J.

Next, you choose a SLF4J binding you like.

Finally, you configure that SLF4J binding to use Console output.

**Comment by dfuentes77** [comment]
I forgot to mention, I'm trying to use this under Heroku or another 12factor env so I don't want to install an instance of Jetty and run a script to launch it, but be able to launch it in a similar with to how jetty-runner was used, with one command.   Is that possible with `jetty-home` or `jetty-base`?  I'm looking in the project and I'm not finding that capability, at least for `jetty-home`.

**Comment by mezhaka** [comment]
I have a legacy app that writes logs to a file.  I now run it as a K8s deployment and would like it to write the logs to stdout, where K8s can pick it up.  Is there absolutely no way to specify the `--log` parameter to use stdout?

**Comment by joakime** [comment]
If it's embedded, the way to configure it is with whatever that embedded solution offers you.
It's really out of Jetty's hands at this point.

**Comment by mezhaka** [comment]
Jetty is not embedded.  The app uses jetty-runner.  The solution is to specify `/dev/stdout` for `--log` parameter:
```bash
$ $JAVA_HOME/bin/java \
    -jar jetty-runner-9.4.30.v20200611.jar \
        --log /dev/stdout \
        --port 8080  \
        --path my-app \
        my-app.war
```
