### ISSUE TITLE
Fails to parse double forward slashes in the url after the host (eg example.com//test)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#276]
migrated from Bugzilla [#485382](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485382)
status NEW severity *minor* in component *server* for *9.3.x*
Reported in version *9.4.0* on platform *Macintosh*
Assigned to: Project Inbox

On 2016-01-07 19:41:09 -0500, Landon Alder wrote:

> Jetty fails to parse any url that has two forwardslashes in the URL after the host. It works fine with one or three+, but doesn't parse correctly with two.
> 
> Example:
> http://www.test.com//thing1/thing2  -- Won't work
> http://www.test.com///thing1/thing2  -- Works
> 
> Both are technically valid URLs, but for two forward slashes doesn't parse correctly and results in a blank page being returned.

On 2016-01-07 20:43:57 -0500, Eclipse Genie wrote:

> New Gerrit change created: https://git.eclipse.org/r/63811

**Comment by joakime** [comment]
Fixed in commit 6a9002991ae32e8eaf084013716bff4aef00e707

**Comment by landonalder** [comment]
So exciting to see this get merged!
