### ISSUE TITLE
how to use qos filter of jetty in spring boot application

### ISSUE THREAD

**Issue by rohitmalekar2117** [eclipse/jetty.project#2773]

**Comment by gregw** [comment]
This is not really an issue, rather a usage question.  Can you please ask this on jetty-users@eclipse.org mailing list... or perhaps on stackoverflow.com, where you can use both the #jetty and #spring-boot tags to get experts from both sides.

I'm not a spring-boot user, but the qos filter is just a standard servlet filter, so if spring-boot supports standard filters they should document how to deploy.
