### ISSUE TITLE
Allow overriding the conversion of a String into a Credential

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#278]
migrated from Bugzilla [#485625](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485625)
status ASSIGNED severity *enhancement* in component *server* for *9.3.x*
Reported in version *9.4.0* on platform *All*
Assigned to: Project Inbox

On 2016-01-12 05:23:59 -0500, Julien Gouesse wrote:

> Credential.getCredential(String credentials) is currently responsible for the conversion of a string into a credential. It's used in several login modules including PropertyFileLoginModule, this method is called in its user storage here:
> http://download.eclipse.org/jetty/stable-9/xref/org/eclipse/jetty/security/PropertyUserStore.html# 260
> 
> I need to add some support of several kinds of credential not currently supported by Jetty and I have to duplicate a lot of code (PropertyUserStore and PropertyFileLoginModule for the login module based on a property file, several classes for LDAP and JDBC, ...) only because there is no mean of providing a custom class to perform the creation of a credential by passing a string.
> 
> There are several possibilities to drive the management of credentials more flexible.
> I suggest to create a new interface (CredentialProvider) representing a credential provider with a single method String getCredential(String credentials), the default implementation (DefaultCredentialProvider) would call Credential.getCredential(String credentials) and would be used to replace the call of Credential.getCredential(String credentials). Each login module would create an instance of the credential provider and pass it to its store if necessary.
> Another solution consists in allowing to add some hooks into Credential.getCredential(String credentials) with a method called addCredentialManager(String prefix, Class credentialClass). Those hooks would be read after treating known prefix (MD5, CRYPT) but before using the Password class:
> http://download.eclipse.org/jetty/stable-9/xref/org/eclipse/jetty/util/security/Credential.html# 75
> 
> I can sign a CLA and provide a patch. Let me know which solution is the most acceptable for you.

On 2016-01-12 16:42:31 -0500, Jan Bartel wrote:

> Or here's a 3rd possibility: use the ServiceLoader mechanism to discover CredentialProviders. You can have a CredentialFactory that does the discovery and consults the providers until it finds one that can return the credential (based on the prefix).

On 2016-01-12 17:37:03 -0500, Julien Gouesse wrote:

> (In reply to Jan Bartel from comment # 1)
> > Or here's a 3rd possibility: use the ServiceLoader mechanism to discover
> > CredentialProviders. You can have a CredentialFactory that does the
> > discovery and consults the providers until it finds one that can return the
> > credential (based on the prefix).
> 
> I'll follow your recommendation. CredentialFactory will loop on all implementations (if necessary):
> 
> public class CredentialFactory {
>     private ServiceLoader<CredentialProvider> credentialProviderLoader;
> 
>     public CredentialFactory() {
>         super();
>         credentialProviderLoader = ServiceLoader.load(CredentialProvider.class);
>     }
> 
>     public String getCredential(String credentials) {
>         for (CredentialProvider cp : credentialProviderLoader) {
>             if (credential.startsWith(cp.getPrefix())) {
>                 return cp.getCredential(credentials);
>             }
>         }
>         return new Password(credentials);
>     }
> }
> 
> The interface CredentialProvider will contain two methods:
> String getCredential(String credentials);
> String getPrefix();
> 
> CredentialFactory will be called in Credential.getCredential(String credential):
> private static final CredentialFactory CREDENTIAL_FACTORY = new CredentialFactory();
> 
> public static Credential getCredential(String credential)
> {
>     return CREDENTIAL_FACTORY.getCredential(credential);
> }
> 
> The file META-INF/services/org.eclipse.jetty.util.security.CredentialProvider will contain one line per default provider, i.e one for Crypt (CryptFactory) and one for MD5 (MD5Factory) except if some developers prefer using the existing classes before looping on the implementations by using those lines before the loop above:
> if (credentials.startsWith(Crypt.__TYPE)) return new Crypt(credentials);
> if (credentials.startsWith(MD5.__TYPE)) return new MD5(credentials);

On 2016-01-12 22:31:31 -0500, Greg Wilkins wrote:

> Julien,
> 
> If you are a github user, then it would be good to get your work as a pull request against https://github.com/eclipse/jetty.project
> 
> Can you make this against master branch (destined to become 9.4.x) and we can then evaluate if we back port to 9.3.x
> 
> cheers

On 2016-01-13 06:52:08 -0500, Julien Gouesse wrote:

> (In reply to Greg Wilkins from comment # 3)
> > Julien,
> > 
> > If you are a github user, then it would be good to get your work as a pull
> > request against https://github.com/eclipse/jetty.project
> > 
> > Can you make this against master branch (destined to become 9.4.x) and we
> > can then evaluate if we back port to 9.3.x
> > 
> > cheers
> 
> Hi Greg
> 
> Yes, I am a Github user: https://github.com/gouessej
> 
> I plan to make a pull request Thursday or Friday so that we have a concrete base of discussion. I'll expect some feedbacks and I'll adjust "my" code until the patch will be worth being accepted.

On 2016-01-13 17:39:43 -0500, Eclipse Genie wrote:

> GitHub Pull Request 70 created by [gouessej]
> https://github.com/eclipse/jetty.project/pull/70

On 2016-01-13 17:41:06 -0500, Julien Gouesse wrote:

> Hi
> 
> (In reply to Greg Wilkins from comment # 3)
> > Can you make this against master branch (destined to become 9.4.x) and we
> > can then evaluate if we back port to 9.3.x
> > 
> > cheers
> 
> Done: https://github.com/eclipse/jetty.project/pull/70

On 2016-01-15 12:55:43 -0500, Eclipse Genie wrote:

> GitHub Pull Request 72 created by [gouessej]
> https://github.com/eclipse/jetty.project/pull/72

On 2016-01-15 12:58:50 -0500, Julien Gouesse wrote:

> As my previous pull request got closed when resetting the head in order to fix a commit with missing information (for the IP validation), I had to make another one:
> https://github.com/eclipse/jetty.project/pull/72
> 
> Please note that using the formatter of the Jetty project on Credential.java has modified some code unrelated to my RFE.

**Comment by joakime** [comment]
Applied as part of pr #72
