### ISSUE TITLE
Unix-specific tests introduced

### ISSUE THREAD

**Issue by rauch** [eclipse/jetty.project#2780]
It's kind of funny to have uinx-specific tests in 2k18:

org.eclipse.jetty.servlet.GzipHandlerTest:

[ERROR] Failures: 
[ERROR]   GzipHandlerTest.testGzipFormRequest:538 
Expected: is "name: value\n"
     but: was "name: value\r\n"

**Comment by joakime** [comment]
Yet it works on Windows 10.

**Comment by joakime** [comment]
What OS / Java version are you on?

**Comment by joakime** [comment]
Commit cf3681ef568be2fea41e89b2937112a7474c5c07 introduced this testcase.
We want to know what OS / Java version you are running, so we can make sure that combination is covered in CI.
(currently, our CI builds use Windows 10 with Java 10.0.1)

**Comment by joakime** [comment]
Closing due to lack of response from OP.
Once the asked for information is provided, we'll be happy to reopen this issue.
