### ISSUE TITLE
Typo in Javadoc

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2781]
Javadoc at https://github.com/eclipse/jetty.project/blob/6b335877d9cc8a6be0c61c5d6d2a559ab9035323/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java#L181 contains a typo ("mad by idle")

I suggest replacing this with `The time in ms (milliseconds) that a websocket may be idle before closing.` which is used elsewhere in the same file.

**Comment by cowwoc** [comment]
@WalkerWatch Sorry. The typo is not fully fixed yet. You wrote "may by idle" instead of "may be idle".

**Comment by WalkerWatch** [comment]
@cowwoc So I did. Good catch. :)
