### ISSUE TITLE
Update Request.java add extra nullcheck for _metadata

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#279]
migrated from Bugzilla [#485867](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485867)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *unspecified* on platform *All*
Assigned to: Jan Bartel

On 2016-01-14 12:53:55 -0500, Pether Sorling wrote:

> https://github.com/eclipse/jetty.project/pull/69
> 
> extractQueryParameters() causes nullpointer.
> 
> 
> https://github.com/eclipse/jetty.project/pull/69/files
> 
> and
> 
>  @Override
>     public String getContentType()
>     {
>         String content_type = _metadata.getFields().get(HttpHeader.CONTENT_TYPE);
> 
> 
> Also needed null check for _metadata.
> 
> Versions: 9.3.7.RC0, 9.3.7.RC1, and 9.4.0-SNAPSHOT .
> 
> 
> Best regards
> Pether

On 2016-01-14 18:09:04 -0500, Greg Wilkins wrote:

> Jan,  you were looking at another case that could do with the NPE protection. Can you merge this and add the other cases - not urgent.

On 2016-02-15 07:03:13 -0500, Jan Bartel wrote:

> This is related to previous bug:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=482290
> 
> Also the github pull request # 69 has been subsumed by # 71.
> 
> Jan

**Comment by joakime** [comment]
This was applied as part of pr #71
