### ISSUE TITLE
Generate p2 repos for Jetty 9.3.24.v20180605 and Jetty 9.2.25.v20180606

### ISSUE THREAD

**Issue by kitlo** [eclipse/jetty.project#2794]
Jetty 9.3.24.v20180605 and Jetty 9.2.25.v20180606 address and resolve 5 important CVEs. They are very important to the users of the Eclipse project. Without the p2 repos for Jetty 9.3.24.v20180605 and Jetty 9.2.25.v20180606, it may not be easy for the Eclipse project to rebuild and apply the patches to the maintenance streams. Please help generate p2 repos for Jetty 9.3.24.v20180605 and Jetty 9.2.25.v20180606.

**Comment by joakime** [comment]
Jetty 9.2 is EOL (End of Life)

When Eclipse removed our means to sign jars we lost our ability to create P2 repos.
We no longer maintain the P2 repos, that's handle by others at the Eclipse foundation now.
Please reach out to those maintaining them now - See Issue #2639

**Comment by rgrunber** [comment]
I can go ahead and handle this. It just may take some time to get to it. I asked @kitlo to file the bug here so there is at least a clear record of those versions being wanted and jetty.project being fine with this.

In order to satisfy this I mainly need to confirm that commit #2786 (merged in 9.4.x) would also work on the other branches, and once confirmed, I would request that commit be merged. If you're opposed to merging on EOL branches that's fine (we could temporarily patch the build system to carry it for that single build of 9.2.x).

**Comment by kitlo** [comment]
According to https://www.eclipse.org/jetty/previousversions.html I thought 9.2 is still supported (and the 5 CVEs were backported to 9.2.25.v20180606). Only 9.1 and earlier releases are EOL.

**Comment by joakime** [comment]
@kitlo versions documentation - https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

@rgrunber do you want that PR merged back into the branches `jetty-9.2.x` and `jetty-9.3.x`?
Not sure how that would help for those older releases though.

**Comment by joakime** [comment]
@kitlo we announced [our intentions to EOL Jetty 9.2 back in April 2016](https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02726.html), it [became official in Jan 2018](https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00116.html).

**Comment by rgrunber** [comment]
@joakime , I don't think it would cherry-pick cleanly, so I'd likely to have to modify it a bit, and submit against that branch, but in order to build 9.3.x and 9.2.x. It would be ideal to have that commit on those branches.

**Comment by rgrunber** [comment]
@kitlo 
http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.25.v20180606/
http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.3.24.v20180605/

I'm also building 9.2.26.v20180806 , which I presume will be needed as well.

Let me know if this solves your issues.

**Comment by kitlo** [comment]
@rgrunber that's exactly what we needed! Thanks!

**Comment by joakime** [comment]
Closing as it seems to have been addressed.
