### ISSUE TITLE
Test failure org.eclipse.jetty.websocket.jsr356.server.DelayedStartClientOnServerTest.testHttpClientThreads_AfterClientConfigure

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#2795]
We can observe this failure
```
Response
Expected: a string starting with "Configured org.eclipse.jetty.websocket.jsr356.ClientContainer"
     but: was "Configured org.eclipse.jetty.websocket.jsr356.server.ServerContainer - org.eclipse.jetty.websocket.jsr356.server.ServerContainer@19e4bbd3
```
https://jenkins.webtide.net/job/jetty.project/view/change-requests/job/PR-2790/lastCompletedBuild/testReport/org.eclipse.jetty.websocket.jsr356.server/DelayedStartClientOnServerTest/linux_jdk9___Test___jdk9___testHttpClientThreads_AfterClientConfigure/

**Comment by joakime** [comment]
Fixed in commit a107ac3b8a597ee6c83a824a1668d9d35d2ea5a8
