### ISSUE TITLE
ThreadPoolBudget logs WARN when minThreads == maxThreads (was: Reasoning behind ThreadPoolBudget warning logic change on 3/5/18)

### ISSUE THREAD

**Issue by accwebs** [eclipse/jetty.project#2798]
Hello,

I recently upgraded an application from Dropwizard 1.2.5 to Dropwizard 1.2.8, and as a result, upgraded from Jetty 9.4.8.v20171121 to 9.4.11.v20180605.  As part of this upgrade, I'm getting a warning printed out from ThreadPoolBudget.java that wasn't being printed before:
````
WARN  [2018-08-11 01:16:06,732] - - - [main] org.eclipse.jetty.util.thread.ThreadPoolBudget: Low configured threads: (max=1408 - required=4)=1404 < warnAt=1408 for InstrumentedQueuedThreadPool[dw]@7c47b0f8{STARTING,1408<=0<=1408,i=0,q=0}[ReservedThreadExecutor@399fd710{s=0/4,p=0}]
````

To track this down, I dug back into the commit history to understand why this is now showing up, and discovered that this is caused by a change made on 3/5/2018 to the thread count warning logic where the minimum thread count setting is now taken into account as part of the warning threshold (rather than just the number of available processor).  Specifically, I am referring to line 100 in commit:  9f2e4fd1f4d050b229375d4ebaf92ddffc571a1c   Because our min thread count and max thread count are set to the same value (and because a few 'required' threads are subtracted from the 'minimum' warning threshold value) we get a warning.  

It's possible I'm not searching correctly, but based on what I can tell, the commit message doesn't mention this change, explain the reasoning, nor reference an associated issue.

Does anyone know the reasoning behind this change?  I am trying to decide whether I should be changing our app's thread counts (i.e. I've always had it set wrong and it's finally alerting now) or if the alert is false (due to a possibly-accidental or erroneous change?).

Thanks for your time and all you do!

**Comment by joakime** [comment]
You have an unusual configuration.
You have a modest maximum thread count of 1408, but have configured the minimum to be the exact same, which means you start all of the threads at startup, and never grow or shrink the thread pool.

This kind of setup isn't specifically disallowed, nor can I think of a reason why it would ever be, but it is a new one on us.

As for the reason this check became a thing, it was to solve 2 issues.
Too small thread pool configurations.
And demands on Threading when HTTP/2 is being used.

We had many individuals that took opposite extreme of your configuration and attempted to setup threadpools of minimum 1 and maximum of 1. (that won't work, and is the cause of not understanding how a modern web application actually works).
We also encountered a thread starvation issue with HTTP/2, with its hybrid of real physical connections, selectors, virtual connections (sessions), where the selector thread could be starved enough to not allow the processing of the virtual connections (sessions).   

Both issues were solved with the reserved thread concept.
Each component you use will declare what its minimum needs are wrt the ThreadPool, and the check will warn you when your configuration is inadequate.

Ultimately though, for your specific scenario, this seems like a unique corner case in our warning logic only.
But I'll defer to @gregw or @sbordet for the ultimate answer to this.

**Comment by accwebs** [comment]
Thanks for the explanation.  Of course, you are indeed correct that it's odd that we've set the min and max threads to the same value.  This was done in a (possibly vain) attempt to reduce latency jitter in our app caused by thread warm-up in case of a sudden traffic spike.  (Applications calling us are very latency sensitive.)  

But I have no empirical evidence (currently) to confirm whether setting min==max really helps.  I'll add that to the list of stuff to performance test.  :-)

**Comment by joakime** [comment]
For now, don't change anything, lets see what @gregw and/or @sbordet say about it.

**Comment by sbordet** [comment]
@gregw opinions?

**Comment by gregw** [comment]
I think that minThreads==maxThreads is a perfectly valid configuration and that we should not warn just because of that. However, in my simple test we don't warn just because they are the same???? So I'm missing some nuance...

**Comment by gregw** [comment]
Ah I see the problem.  The behaviour is different for:
``` java 
  QueuedThreadPool qtp = new QueuedThreadPool(1408,1408);
  Server server = new Server(qtp);
```
and 
``` java 
  QueuedThreadPool qtp = new QueuedThreadPool();
  qtp.setMinThreads(1408);
  qtp.setMaxThreads(1408);
  Server server = new Server(qtp);
```
Since using the setters is done after the budget is constructed, so therefor it's warnAt value is not modified to 1408.

So I'm thinking that we need to ensure that warnAt is min(minThreads,availableCores) no matter how we setup the QTP.

**Comment by gregw** [comment]
I've created PR #2799 that by default initializes the warnAt level of the thread budget to availablecores and ignores min threads.  I think this is fine because we warn if `max-required<warnAt`, which has nothing to do with min threads.  So now we warn if the thread pool has insufficient threads to drive all cores of the machine.   Thoughts?

**Comment by joakime** [comment]
So, we have 3 paths ...

1. A sufficiently sized thread pool (happy path, no issues, no info, no warnings)
2. An inefficiently sized thread pool.  Thread Pool will function fine, but you are not using the machine to its fullest potential.  This is an INFO level event.
3. An insufficiently sized thread pool.  Thread Pool will not function.  Will cause issues / hangs.  This is a WARN level event, and possible Exception / Failure to start.

**Comment by joakime** [comment]
Open questions on `ThreadPoolBudget.check()` ...

## Scenario 1: Executor is shared with other components at a later event?

``` java
QueuedThreadPool pool = new QueuedThreadPool(16, 1);
pool.start(); // some other thread has started the pool already.

// A later event starts a new container
ContainerLifeCycle container = new ContainerLifeCycle();
container.start();

// A later event creates a new demand on the threadpool, by sharing it
container.addManaged(new HttpClient(pool));
container.addManaged(new HttpClient(pool));
container.addManaged(new HttpClient(pool));
container.addManaged(new HttpClient(pool));
container.addManaged(new HttpClient(pool));
```

Since the `ThreadPoolBudget.check()` is only performed during the `ThreadPool.doStart()`, this scenario will not be reported.

## Scenario 2: Executor is resized after start

``` java
QueuedThreadPool pool = new QueuedThreadPool(16, 1);
pool.start();
pool.setMaxThreads(4);
```

Since the `ThreadPoolBudget.check()` is only performed during the `ThreadPool.doStart()`, this scenario will also not be reported.

**Comment by gregw** [comment]
Hmmmm,

I think we need to keep this simple.

The error condition is if maxThreads is ever less than then number of thread leases granted in the thread budget.
Thus this error condition can vary whenever the number of leases granted varies OR if maxThreads is varied, so I can't see how we can avoid having setMaxThreads call check on the budget?

The secondary concern is if (maxThreads - leases) is less than CPUs, in which case we may have a sub optimal threadpool OR we may have a deliberately configured small threadpool.  Eitherway, this is just optimization and I think we should say it is beyond the scope of the task of ThreadBudget.

Thus I'm included to deprecate the warnAt concept and just warn if maxThreads is ever less than leases.
