### ISSUE TITLE
GzipHandler not supporting "deflate" encoding?

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#280]
migrated from Bugzilla [#485873](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485873)
status ASSIGNED severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.3.6_ on platform _PC_
Assigned to: Greg Wilkins

On 2016-01-14 13:24:57 -0500, Constantin Muraru wrote:

> Hi guys,
> 
> I've noticed that GzipFilter was removed and now GzipHandler should be used (jetty 9.3.6). It seems though that the GzipHandler does not support deflate as GzipFilter used to.
> 
> Therefore for a request coming with the header "Accept-Encoding: deflate", no compression is performed.
> 
> What are your thoughts on this?
> 
> Thanks,
> Constantin

On 2016-01-14 18:08:07 -0500, Greg Wilkins wrote:

> on the fly compression is surprisingly difficult to get right - specially with async IO, etags, vary based caching, already compressed content, incompressible content types, etc.
> 
> The code is complex and was made more so by the choice of deflate vs gzip.      Gzip appears to be well supported by all major browsers and favoured by most servers.
> 
> So in the interests of simplicity, deflate support was dropped while we did the major refactor of dynamic gzip handling.
> 
> However, if somebody can give us a compelling use-case to support deflate, we can consider re-adding support now that the refactor is done and stable.

**Comment by gregw** [comment]
will not support deflate.
