### ISSUE TITLE
jndi-datasources.adoc - MariaDbPoolDataSource

### ISSUE THREAD

**Issue by softconex-github** [eclipse/jetty.project#2808]
Hi,

first post / first issue here from my side regarding jetty project on github. Let me know if I shall create a pull request for this documentation issue.

Regarding

jetty-documentation/src/main/asciidoc/administration/jndi/jndi-datasources.adoc

There's also a connection pool from MariaDB which I've tested sucessfully under jetty. I think it's worth mentioning this pool in the docs

Here's an example:

    <New id='DSTest' class='org.eclipse.jetty.plus.jndi.Resource'>
        <Arg></Arg>
        <Arg>jdbc/DSTest</Arg>
        <Arg>
            <New class="org.mariadb.jdbc.MariaDbPoolDataSource">
                <Set name="user">root</Set>
                <Set name="password">root</Set>
                <Set name="url">jdbc:mariadb://localhost:3306/databasename</Set>
            </New>
        </Arg>
    </New>

**Comment by olamy** [comment]
Hi
Sure a pull request will help.

**Comment by softconex-github** [comment]
ok I guess I will have to go through the formal stuff (ECA), that'll take a few days.

**Comment by joakime** [comment]
ECA signing isn't too hard.
Basics are, setup an account on eclipse, then electronically sign the ECA.
See: https://www.eclipse.org/legal/ecafaq.php (point 10)

**Comment by softconex-github** [comment]
Right, that was easy.

Here's the pull request with suggested amendments for 9.4.x branch

https://github.com/eclipse/jetty.project/pull/2820

Best,
Holger

**Comment by softconex-github** [comment]
New pull request with signed commit

https://github.com/eclipse/jetty.project/pull/2822

**Comment by joakime** [comment]
Closing due to lack of Eclipse ECA (Eclipse Legal Requirement) on submitted PR.
