### ISSUE TITLE
WebSocket upgrade response should honor HttpConfiguration server version settings

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#281]
migrated from Bugzilla [#485969](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485969)
status ASSIGNED severity *enhancement* in component *websocket* for *9.3.x*
Reported in version *9.3.6* on platform *All*
Assigned to: Joakim Erdfelt

On 2016-01-15 14:10:12 -0500, Joakim Erdfelt wrote:

> The response header "Server" isn't being set properly in a WebSocket upgrade response, it should work, and also honor the HttpConfiguration setting for that connector.

**Comment by joakime** [comment]
Fixed in commit 9f8df9a1a84433cdaf4b52471210f63d6e005f2d
