### ISSUE TITLE
MIME Envelope content in Jetty 9.4.8 is inconsistent with earlier jetty versions 8.x.x

### ISSUE THREAD

**Issue by SonaliDasgupta** [eclipse/jetty.project#2813]
We are in the process of upgrading our product to use Jetty 9.4.8 from Jetty 8.1.16 .

In use cases where MIME content is being sent in the request, the older jetty 8.x.x server sends the following response: `mimeEnvelopeElement:  text/plainbase64text1<plaintext-content>`.  While Jetty 9.4.8 sends the response as `mimeEnvelopeElement:  application/x-www-form-urlencodedbase64<some-additional-mime-content>text/plainbase64text1<plaintext-content>`.

The `application/x-www-form-urlencodedbase64<some-additional-mime-content>` part is being added to the MIME Envelope element in the newer Jetty version, which is unexplained behavior.

This  is causing backward-compatibility issues in our product, and a fix/work-around is urgently needed.

**Comment by sbordet** [comment]
Jetty does not send the `mimeEnvelopeElement` headers you are talking about.
It's your application that does that.

**Comment by SonaliDasgupta** [comment]
There has been no change in our application. And this change in the mimeEnvelopeElement content has been noticed after upgrading the Jetty version, with no other changes. The Mime Envelope Element I am referring to is the MIME content, and not a header.

**Comment by joakime** [comment]
Jetty has no code to work with requests that have `Content-Type: application/x-www-form-urlencodedbase64`  (that's a meaningless Content-Type to Jetty)

Here's how Jetty gets involved with request `Content-Type` behaviors ...

Per the Servlet Spec the use of the `HttpServletRequest.getParameter*()` or `getPart*()` methods behave like this ...

1) All request URI query parameters are parsed.
2) If the request has `Content-Type: application/x-www-form-urlencoded` then parse the request body contents for more parameters.
3) If the request has `Content-Type: multipart/form-data` *and* a `<multipart-config>` or `@MultipartConfig` then parse the request body contents for more parameters.  The content parsed here is now available in the `HttpServletRequest.getPart*()` methods.

All other `Content-Type` values are handed by the application via reading the request body content using the `HttpServletRequest.getInputStream()` or `.getReader()` methods.

**Comment by joakime** [comment]
Now, as for the reported response being produced.
That header could to indicate a bad use of the HttpServletResponse API.
Can you capture the raw HTTP request and response (headers included)?
That will help narrow down things.

**Comment by SonaliDasgupta** [comment]
The request is as follows :

POST /RequestURI_field--GV_Str1_Value?P_QStr_1=P1%23V1%20&P_QStr_2=P2%24V2%20&P3_Repeating=P3%25V1_QStr%20&P3_Repeating=P3%2FV2_QStr%20 HTTP/1.1
content-type: multipart/mixed; type=application/x-www-form-urlencoded ; boundary=_NextPart_000_0002_01C3E1CC.3BB37320
accept-encoding: gzip
accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*
accept-charset: iso-8859-1,*,utf-8
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:8113
Content-Length: 2282

--_NextPart_000_0002_01C3E1CC.3BB37320
Content-type: application/x-www-form-urlencoded

P1_Required=P1%23V1_PData%20&P2_Optional=P2%24V2_PData%20&P3_Repeating=P3%25V1_PData%20&P3_Repeating=P3%2FV2_PData%20
--_NextPart_000_0002_01C3E1CC.3BB37320
Content-type: text/plain
Content-id: text1@*.com

START.
Client ONE text attachment Line one$$
Client ONE text attachment Line two$$
END.
--_NextPart_000_0002_01C3E1CC.3BB37320
Content-type: image/gif
Content-id: binary1@*.com

GIF89a}



While the response is as follows :

HTTP/1.1 200 OK
Date: Fri, 17 Aug 2018 05:20:29 GMT
Content-Type: multipart/mixed; type=Response_Content-Type_field-POST ; boundary=_NextPart_000_0002_01C3E1CC.3BB37320
Set-Cookie: Response_Set-Cookie_field=POST
Location: Response_Location_field-POST
Pragma: Response_Pragma_field-POST
Content-Length: 2750
Server: Jetty(9.4.8.v20171121)


--_NextPart_000_0002_01C3E1CC.3BB37320
Content-type: Response_Content-Type_field-POST

Response_asciiContent_Field-POST
--_NextPart_000_0002_01C3E1CC.3BB37320
Content-type: image/gif

GIF89a~

**Comment by SonaliDasgupta** [comment]
@joakime Thank you for the explanation :) . I hope the request and response captured above will help.  In the request , I see the Content-Type being sent as "content-type: multipart/mixed; type=application/x-www-form-urlencoded " , and under the Next_part element as ' application/x-www-form-urlencoded' . But the MIME Envelop being sent by the server seems to append the base64 part.

**Comment by joakime** [comment]
Before we go any further, you'll need to fix your `Content-Type` creation.
Both on your client, and your servlet response.

Your Client sends ...

    content-type: multipart/mixed; type=application/x-www-form-urlencoded ; boundary=_NextPart_000_0002_01C3E1CC.3BB37320

Your Servlet sends ...

    Content-Type: multipart/mixed; type=Response_Content-Type_field-POST ; boundary=_NextPart_000_0002_01C3E1CC.3BB37320

Both of those are invalid for the MIME specs and `multipart/mixed` specs.

The `multipart/mixed` has only 1 parameter: `boundary`.  The `type` parameter present on your capture shouldn't be there.
In fact, the client generated `multipart/mixed; type=application/x-www-form-urlencoded ; boundary=_NextPart_000_0002_01C3E1CC.3BB37320` is attempting to say that the request body content contains 2 different (conflicting) content-types! (both `multipart/mixed` and `x-www-form-urlencoded`)

The client request header should be ...

    content-type: multipart/mixed; boundary=<boundary_string>

The response header should be ...

    Content-Type: multipart/mixed; boundary=<boundary_string>

**Comment by joakime** [comment]
@SonaliDasgupta and updates?

**Comment by joakime** [comment]
No response. Closing.
Will reopen if OP has anything new to add.
