### ISSUE TITLE
ALPN still missing for JRE8u181 - Jetty 9.4.11

### ISSUE THREAD

**Issue by draeath** [eclipse/jetty.project#2819]
I see in #2774 was closed with "Update to 9.4.11."

However, 9.4.11 _does not fix this problem._ (or the jetty-home*.tgz on maven didn't package it!)

`jetty-home-9.4.11.v20180605.tar.gz` (with SHA1 5841e94a4b5410d6909e1b0de7a5b7944a5f7cca, to verify my file is intact) does not contain an ALPN for jre8u181, the most recent version in modules/alpn-impl is alpn-1.8.0_172.mod:

```
alpn-10.mod
alpn-11.mod
alpn-1.8.0_05.mod
alpn-1.8.0_101.mod
alpn-1.8.0_102.mod
alpn-1.8.0_111.mod
alpn-1.8.0_112.mod
alpn-1.8.0_11.mod
alpn-1.8.0_121.mod
alpn-1.8.0_131.mod
alpn-1.8.0_141.mod
alpn-1.8.0_144.mod
alpn-1.8.0_151.mod
alpn-1.8.0_152.mod
alpn-1.8.0_161.mod
alpn-1.8.0_162.mod
alpn-1.8.0_171.mod
alpn-1.8.0_172.mod
alpn-1.8.0_20.mod
alpn-1.8.0_25.mod
alpn-1.8.0_31.mod
alpn-1.8.0_40.mod
alpn-1.8.0_45.mod
alpn-1.8.0_51.mod
alpn-1.8.0_60.mod
alpn-1.8.0_65.mod
alpn-1.8.0_66.mod
alpn-1.8.0_71.mod
alpn-1.8.0_72.mod
alpn-1.8.0_73.mod
alpn-1.8.0_74.mod
alpn-1.8.0_77.mod
alpn-1.8.0_91.mod
alpn-1.8.0_92.mod
alpn-1.8.0.mod
alpn-8.mod
alpn-9.mod
```

Reproduced with debian stretch package `openjdk-8-jre-headless` version `8u181-b13-1~deb9u1` in the updates/main repository.

**Comment by draeath** [comment]
Thank you!

I had noticed that 171 and 172's files were identical and there wasn't a newer version of alpn-boot that I could see, so locally I was copying alpn-1.8.0_172.mod over to alpn-1.8.0_181.mod as a workaround (it workes). I see that the two files are identical in commit/merge eceaff7 so that makes me feel a bit better :)

Should we close this, since I've effectively confirmed that particular change works? Or should we get a confirmation from someone using 9.4.12.RC2 first?

**Comment by joakime** [comment]
Normally I would direct you to the ALPN documentation at https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions

Unfortunately our documentation sync has been out of wack for the past month (being worked on at https://bugs.eclipse.org/537802)

An alternative location to look for the current mapping of Java version to alpn-boot version is the pom.xml in the root of the project.

https://github.com/eclipse/jetty.project/blob/13792a65d2c193d7855437ecd6e06ce08bb5a8a1/pom.xml#L1772-L1783

I'm going to close this.
