### ISSUE TITLE
AuthenticationProtocolHandler should not always cache Authentication.Result

### ISSUE THREAD

**Issue by CaoManhDat** [eclipse/jetty.project#2821]
Recently I tried to using jetty-client to connect to Kerberos Solr Server. Although currently `Jetty-Client` only support `BasicAuthentication` and `DigestAuthentication`, I managed to create another `KerberosAuthentication` class to support Kerberos. 
But `AuthenticationProtocolHandler` cache all the `Authentication.Result` by URI, since Kerberos is connection based authentication, therefore, subsequence requests don't need to include the `Authorization` in the header. 

Therefore I propose to change `AuthenticationProtocolHandler` a little bit, to not cache `Authentication.Result` if its `getURI()` return null.

**Comment by sbordet** [comment]
Care to prepare a pull request? Thanks!

**Comment by CaoManhDat** [comment]
@sbordet Based on your suggestion, I created a pull request that adds `SpnegoAuthentication` support to Jetty client. But I do not have much time as well as knowledge about jetty test framework to add more tests.
