### ISSUE TITLE
Every call to HttpServletRequest.getParameter*() methods results in a newly created Map object if both query and body content exist

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2824]
Every call to the various HttpServletRequest.getParameter() methods results in a new Map being created.

From the `Request.getParameters()` method ...

https://github.com/eclipse/jetty.project/blob/ddd80deeb96eed136029b944258b36b285af79c6/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L409-L419

Since all other `.getParameter*()` methods uses `.getParameters()`, this will result in a new `MultiMap` if the request contains **both** query and content parameters.

**Comment by gregw** [comment]
Note the description of the problem is not exactly correct.    A new `_parameters` map is created on every call only if the request has both query parameters and content parameters.     Still a silly bug, but not as nasty as at first look.

**Comment by janbartel** [comment]
Fix was applied.
