### ISSUE TITLE
JSR356 Encoder with no defined constructors is not supported

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#284]
migrated from Bugzilla [#485978](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485978)
status NEW severity _enhancement_ in component _websocket_ for _9.3.x_
Reported in version _9.3.6_ on platform _All_
Assigned to: Joakim Erdfelt

On 2016-01-15 17:19:47 -0500, Joakim Erdfelt wrote:

> If a new Encoder is created, without a constructor of any kind, it should still work.
> 
> Eg:
> 
> ```
> public class JsonEncoder implements Encoder.TextStream<Json>
> {
>     @Override
>     public void init(EndpointConfig config)
>     {
>     }
> 
>     @Override
>     public void destroy()
>     {
>     }
> 
>     @Override
>     public void encode(Json json, Writer writer) throws EncodeException, IOException
>     {
>         writer.write(json.getData());
>     }
> }
> ```
> 
> Exception in thread "main" org.eclipse.jetty.websocket.common.events.annotated.InvalidSignatureException: Encoder must have public, no-args constructor: jetty.websocket.PerMessageDeflateBug$JsonEncoder
>   at org.eclipse.jetty.websocket.jsr356.metadata.EncoderMetadataSet.discover(EncoderMetadataSet.java:61)
>   at org.eclipse.jetty.websocket.jsr356.metadata.CoderMetadataSet.addAll(CoderMetadataSet.java:78)
>   at org.eclipse.jetty.websocket.jsr356.server.AnnotatedServerEndpointMetadata.<init>(AnnotatedServerEndpointMetadata.java:51)
>   at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.getServerEndpointMetadata(ServerContainer.java:161)
>   at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.addEndpoint(ServerContainer.java:86)
>   at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.doStart(ServerContainer.java:138)

**Comment by joakime** [comment]
This has been addressed in Issue #207 and will show up there.
