### ISSUE TITLE
Reflect JDK flavor in documentation

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#2849]
Update documentation/website to include vendor of the JDK(s) a release is tested against/certified for.

**Comment by WalkerWatch** [comment]
Up to now, we have only been using official releases to test against. Do we have any plans of using builds from Azure, et al, as part of our build/test infrastructure going forward? Think the landscape has evolved differently from when I opened this.

**Comment by sbordet** [comment]
@WalkerWatch I think we want to restrict our compliance only to OpenJDK versions from Oracle.
Perhaps we can run our builds on Jenkins with LTS releases from AdoptOpenJDK when they release them, but I would not make other efforts, unless it's very, very easy to obtain the JDK builds freely and set them up in Jenkins.

**Comment by WalkerWatch** [comment]
That was my thought as well, @sbordet. Closing this for now. Will re-open if it becomes relevant again.
