### ISSUE TITLE
PathContentProvider - Use of Direct buffers without pooling

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#285]
migrated from Bugzilla [#486147](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486147)
status NEW severity *minor* in component *client* for *9.3.x*
Reported in version *9.2.14* on platform *All*
Assigned to: Simone Bordet

On 2016-01-19 20:04:36 -0500, Veselin Andreev wrote:

> PathContentProvider uses Direct buffers which are not pooled. This could cause a memory hog when playing with larger buffer sizes and uploading multiple files rather frequently. Can the allocated buffer be pooled ? - preferably allocated prior to channel creation and released back to the pool upon closure of the channel. By default, I hope, the HttpClient buffers pool can be utilized for this.

**Comment by sbordet** [comment]
Added `PathContentProvider.setByteBufferPool(ByteBufferPool)` so that this is possible:

```java
PathContentProvider content = new PathContentProvider(filePath);
content.setByteBufferPool(httpClient.getByteBufferPool());
```

If the `ByteBufferPool` is present, will be used, otherwise a buffer will be allocated as before.
