### ISSUE TITLE
Create documentation for logging properties

### ISSUE THREAD

**Issue by polarapfel** [eclipse/jetty.project#2850]
Hi,

I wish there was documentation on properties Jetty honors to configure logging.

For example, I was running into [this issue](https://stackoverflow.com/questions/51978990/how-to-suppress-logging-output-to-stdout-when-using-jetty-websocket-client/51979135).

Properties such as _org.eclipse.jetty.util.log.announce_ should be documented somewhere.

thanks,

Tobias

**Comment by joakime** [comment]
Still need to document this.
