### ISSUE TITLE
Best way for discarding response content when using InputStreamResponseListener

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#2856]
In our project, we use `InputStreamResponseListener` for reading response content and parsing it as JSON or XML.

But sometimes, if the response does not meet certain criteria, we don't need the content.

For example, consider a POST request of JSON data to an API that returns the posted data if successful or a JSON object indicating the reason for the failure otherwise. If the request fails, we read the content to understand why, but otherwise we're just happy that it succeded and we don't read the response.

The most straightforward way to implement this would be something like:

```java
InputStreamResponseListener listener = new InputStreamResponseListener();
httpClient.POST("/api/some-data/")
    .content(jsonContentProvider)
    .send(listener);

Response response = httpClient.getResponse(10, TimeUnit.SECONDS);
if (!HttpStatus.isSuccess(response.getStatus())) {
    try (InputStream in = listener.getInputStream()) {
        // ... parse InputStream as JSON and handle the error
    }
    catch (Exception e) { }
}
```

The problem with such an approach, however, is that Jetty waits for the `InputStreamResponseListener` to call the `Callback` of each content chunk so it knows that the content was actually handled.
In the example above, that never happens if the response status is successful.

The effect is that when a certain number of callbacks are left uncalled, Jetty stops delivering more content to listeners, also for other requests.
And rightfully so, since it is the responsibility of the caller to tell Jetty when the content was handled.

So how should we do that in the above example?
A few possible solutions come to my mind:

#### 1. Read the content anyway
```java
try (InputStream in = listener.getInputStream()) {
    JsonObject jsonContent = parseJson(in);       // First read content, then decide whether to use it
    if (!HttpStatus.isSuccess(response.getStatus())) {
        // ... handle the error
    }
}
catch (Exception e) { }
```
**Pro:**
- Lets the response complete normally.

**Con:**
- Quite wasteful.

#### 2. Close the `InputStream` without reading it
```java
try (InputStream in = listener.getInputStream()) {
    if (!HttpStatus.isSuccess(response.getStatus())) {
        // ... parse InputStream as JSON and handle the error
    }
}
catch (Exception e) { }   // here, all remaining Callbacks are called with an AsynchronousCloseException
```
**Pro:**
- Most natural way for ignoring content of an `InputStream`.

**Con:**
- As this causes the response to fail with an `AsynchronousCloseException`, it is hard for a generic error handling listener to tell whether that is actually a problem or not.

#### 3. Abort the `Response`
```java
if (HttpStatus.isSuccessful(response.getStatus())
   response.abort(new CancellationException());    // or some other type known not to be an actual issue
else {
    try (InputStream in = listener.getInputStream()) {
        // ... parse InputStream as JSON and handle the error
    }
    catch (Exception e) { }
}
```
**Pro:**
- Easier to be destinguished from actual failures.
- Most clear API for actually telling Jetty to stop reading the response.

**Con:**
- *Aborting* in case of *success* might seem contradictory, but that's specific to this example only.

----

At the moment we are using solution 1, but the more I think about it, the more solution 3 seems to be the way to go.

What do you think?

A small side note:
While the JavaDoc of `InputStreamResponseListener` does state that the producer blocks if the consumer is slow, maybe it should be added explicitly that the consumer must eventually either close the `InputStream` or abort the `Response`.

**Comment by joakime** [comment]
@gregw any thoughts on this one?

**Comment by joakime** [comment]
I wonder if using `HttpServletResponse.sendError(-1);` (to abort the exchange and the connection entirely) is what you are looking for?

**Comment by sbordet** [comment]
@joakime this is on the client side.

@mperktold 
Solution 1. is wasteful only if the content is very large; otherwise there is a good chance that the server has already sent the whole content, so the content is basically already all on the client; a few buffers will be allocated and such, but the connection will remain open.

Solutions 2. and 3. have the disadvantage that they will cause the connection to be closed, so there is some saving on buffers, but the connection will be closed.

I would go for solution 3. only if you can prove that the "waste" you think happens in solution 1. is really impacting you more than closing the connection with solution 3.

**Comment by mperktold** [comment]
> Solutions 2. and 3. have the disadvantage that they will cause the connection to be closed

You are right, I haven't thought of that, thanks! 👍

So I will stick with solution 1 and only switch to solution 3 when and where needed.
