### ISSUE TITLE
NoSqlSessionManager has bogus methods

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#286]
migrated from Bugzilla [#486301](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486301)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Jan Bartel

On 2016-01-21 14:16:30 -0500, Jesse McConnell wrote:

> There are some methods on here that duplicate concepts from the AbstractSessionManager that are dangerous, namely the setIdlePeriod which duplicates the concept/functionality in setMaxInactiveInterval on the AbstractSessionManager.

**Comment by janbartel** [comment]
@jmcc0nn3ll I think these are 2 separate things:   

AbstractSessionManager.setMaxInactiveInterval() sets the default amount of time that a session is regarded as being valid (ie not expired). It's equivalent to <session-timeout> in <session-config> from web.xml, although the units are different :)

NoSqlSessionManager.setIdlePeriod() is the amount of time a valid session should remain in memory before being passivated out to mongo, thus reducing the number of sessions stored in memory. Whenever that id is next referenced, it will be populated into memory again from mongo.

Or am I missing something in the problem description?

**Comment by jmcc0nn3ll** [comment]
could be, when I was looking through it that method had no implementation and the javadoc read like it was the maxinactive behavior, if it has an implementation now and there is a difference then we can close this :+1:

**Comment by janbartel** [comment]
Ok, cool I'll close this now. In the jetty-9.4.x branch I think the naming is clearer, as the idle passivation timeout is actually called setIdlePassivationTimeoutSecs() - so it describes what it does and the units it uses in one go :)
