### ISSUE TITLE
Leakage of HttpDestinations in HttpClient

### ISSUE THREAD

**Issue by AntonIvanov87** [eclipse/jetty.project#2860]
### Problem
There is a memory leak in `HttpClient` that causes our production system to crash.
Idle `HttpDestination` can remain forever in the `HttpClient.destinations` field even if `removeIdleDestinations` is set to true.

### Investigation
Normally `PoolingHttpDestination` is removed from the `HttpClient.destinations` when last connection to the destination is closed.
But what if we were unable to open any connection to a destination? For example, because we can not resolve host ip address, destination server is down, etc.
Then there will be no last connection to close, so the destination will remain forever in 'destinations'. (Unless destination server is up and a new request to the server is made.)

**Comment by AntonIvanov87** [comment]
Fixed in https://github.com/eclipse/jetty.project/pull/2862

**Comment by sbordet** [comment]
Thanks!
