### ISSUE TITLE
WebSocketClient.connect() hangs for invalid endpoint

### ISSUE THREAD

**Issue by coudy** [eclipse/jetty.project#2875]
I’ve been using the web socket client for a while and recently noticed that the session future doesn’t always complete on `connect()`. Specifically, this happens when I accidentally use ‘ws://' instead of ‘wss://', so the upgrade fails with my server responding with a 301 (and a Location rewritten to HTTPS). My code looks as follows:

```
var client = new WebSocketClient();
client.start();
var request = new ClientUpgradeRequest();
var sessionFuture = client.connect(delegate, serviceUri, request);
var session = sessionFuture.get();
```
I’d expect `session` to be `isDone()` and throw an `ExecutionException`. Instead, the blocking get hangs forever.

I can reproduce this on 9.4.12.RC2 from Maven Central.

**Comment by joakime** [comment]
I think I've been able to reproduce.

**Comment by joakime** [comment]
See PR #2902 
Branch `jetty-9.4.x-issue-2875-websocketclient-redirect` has proposed fix.
