### ISSUE TITLE
Jetty Brotli compression support?

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#288]
migrated from Bugzilla [#486770](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486770)
status ASSIGNED severity _enhancement_ in component _server_ for _9.4.x_
Reported in version _unspecified_ on platform _Other_
Assigned to: Project Inbox

On 2016-01-28 13:59:08 -0500, JJ Frankovich wrote:

> Any plans to support Google's new Brotli algorithm as an alternative to your gzip support in Jetty? For compact3 profiles with limited cpu, this sounds promising so speed up web pages and lower cpu consumption: 
> 
> http : // google-opensource.blogspot.jp/2015/09/introducing-brotli-new-compression.html?m=1

On 2016-02-02 02:31:37 -0500, Greg Wilkins wrote:

> No immediate plans... at least not prior to you raising this.
> 
> In fact with master branch we had gone the other direction and dropped support for deflate so we could just have a simpler interceptor that can handle async content generation properly.
> 
> But if Brotli does take off and offers significant benefits, then it would be good to support it.   So thanks for bringing it to our intention - we will monitor progress and see how it goes.   Of course code contributions and/or sponsored development welcome on this if we don't get around to it soon enough.

On 2016-02-02 02:35:27 -0500, Greg Wilkins wrote:

> https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/
> http://www.omgchrome.com/brotli-http-compression-coming-to-chrome/

**Comment by Corni** [comment]
Hi,

whats the state of this issue? Yesterday it was announced that Brotli is supported by Edge (as well as Chrome and Firefox) - https://blogs.windows.com/msedgedev/2016/12/20/introducing-brotli-compression/ so there is a real userbase for this out there.

**Comment by joakime** [comment]
Quick check on the status of Brotli in the Java space ...

As of Dec 20166, there is no Brotli encoder available for Java (provided by the JDK, or Java 9, or from another open source project that deploys to central.maven.org).

**Comment by joakime** [comment]
Semi up to date list of browsers that support brotli.

http://caniuse.com/#feat=brotli

For those looking at brotli, please read the following ...

https://samsaffron.com/archive/2016/06/15/the-current-state-of-brotli-compression

Some highlights:

 * Compression ratios on brotli are about 5% to 29% better then gzip.
 * The bigger the file, the better the ratio.
 * Only works on HTTPS, does not work on plaintext HTTP.
 * Encoding to brotli is extremely slow.  (gzip can do about 140MB/s encoding, while brotli can do 0.4MB/s using native code)

**Comment by gregw** [comment]
Note that in the newly released jetty-9.4, you can have precompressed brotli static content.   So if the client asks for foobar.txt and accepts br encoding and the file foobar.txt.br exists on disk, then it will be served as transfer encoded content.

This is a good match for brotli, as the encoding is slow, so it is not great for dynamic compression, but good for pre-compression.

**Comment by meetakshay99** [comment]
@gregw Can you please let know how to support brotli static content?

**Comment by joakime** [comment]
@meetakshay99 compress the static content with a command line.

Make sure you have both the original uncompressed and the compressed versions in your webapp.

Eg:

```
index.html
index.html.gz
index.html.br
css/main.css
css/main.css.gz
css/main.css.br
script/app.js
script/app.js.gz
script/app.js.br
script/processing.js
script/alt-min.js
script/alt-min.jz.gz
```

It will look at the `Accept-Encoding` header on the request to know if  client supports compression.

Some examples of this request header ...

```
Accept-Encoding: gzip
Accept-Encoding: br, gzip
Accept-Encoding: gzip;q=0.9, br
```

When a resource is requested, the other compressed files are looked for by following the `Accept-Encoding` header order.

So using the above files, and the following requests

Accept-Encoding | Requested Resource | Served Resource
------------------- | ---------------------- | -------------------
`gzip` | `/index.html` | `/index.html.gz`
`br` | `/index.html` | `/index.html.br`
`gzip, br` | `/css/main.css` | `/css/main.css.gz`
`gzip, br` | `/script/alt-min.js` | `/script/alt-min.js.gz`
`br, gzip` | `/script/alt-min.js` | `/script/alt-min.js.gz` (as there's no `.br` version present in your webapp)
`br` | `/script/alt-min.js` | `/script/alt-min.js` (as there's no `.br` version present in your webapp)
`br, gzip` | `/script/processing.js` | `/script/processing.js` (as there's no compressed versions present in your webapp)
`gzip, br` | `/script/processing.js` | `/script/processing.js` (as there's no compressed versions present in your webapp)

**Comment by joakime** [comment]
Closing as implemented.  Just needs to be documented.
@WalkerWatch want to open a new issue for documenting brotli vs gzip pre-compressed content?

**Comment by mgol** [comment]
I don't think following the order of declared compression formats is desirable. For regular script tags, both Chrome & Firefox send:
```
accept-encoding: gzip, deflate, br
```
but that should still get the Brotli-compressed assets when available.
