### ISSUE TITLE
Jetty takes 100% CPU when uploading a file and transmission is interrupted before completion

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#289]
migrated from Bugzilla [#486826](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486826)
status ASSIGNED severity *normal* in component *server* for *9.3.x*
Reported in version *9.0.4* on platform *PC*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[ServletEofTest.java](https://bugs.eclipse.org/bugs//attachment.cgi?id=259522)_ (ID 259522)
- _[BasicJetty.java](https://bugs.eclipse.org/bugs//attachment.cgi?id=259760)_ (ID 259760)

On 2016-01-29 09:23:22 -0500, Pablo Frias wrote:

> Dear all,
> 
> We have been facing an issue when a file is being uploaded through Jetty and suddenly transmission is interrupted before completion.
> The result in this scenario is that CPU gets at 100% and can only be restored by restarting the web server.
> We are using Jetty version 9.0.4.v20130625 (also tested on 9.3.6.v20151106) embedded in a Spring application. 
> 
> When debugging, we found that Jetty generates an EofException upon acknowledment of the socket being closed. 
> Afterwards it appears that the code gets into a generic exception handling which tries to send a HTTP error response back to the client.
> In turn this response is attempted to be written to the socket before NIO has properly updated its records that the connection is lost, hence entering a blocking write.
> 
> With further debugging we could see that there is an exception handler in ServletHandler which attempts to filter out EofException, but it would appear that it is failing to detect it due to the EofException being chained into another Exception.
> (See https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java#L625)
> 
> As it fails to filter out the Eof, then the default error handling kicks in and an Internal Server Error is attempted to be sent back to the client
> (see https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java#L650)
> 
> We've attempted a fix for this issue, which would be to look for a chained EofException in line 625, as follows:
>  
> // remove else if   
> if (isEofException(th)){
>    ((org.eclipse.jetty.server.Response) response).getHttpChannel().earlyEOF(); // on Version 9.0.4.v20130625
>    ((org.eclipse.jetty.server.Response) response).getHttpChannel().abort(th); // on Version 9.3.6.v20151106
>    throw (EofException)th;
> }
> 
> As for isEofException method, it helps to identify if an EofException exists on a nested Exception:
> 
> private boolean isEofException(Throwable cause) 
> {
>         while (cause != null && !(cause instanceof EofException))
>         {
>                 cause = cause.getCause();
>         }
>         
>         return cause != null;
> }
> 
> Also, on Response class we made getHttpChannel() public.
> 
> This helped to avoid the issue when the transmission is cut.
> 
> This is the Thread dump for the one which is consuming all CPU:
> 
> "qtp529864074-68" - Thread t@68
>    java.lang.Thread.State: RUNNABLE
>         at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
>         at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
>         at sun.nio.ch.IOUtil.write(IOUtil.java:148)
>         at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
>         - locked <6ddac168> (a java.lang.Object)
>         at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177)
>         at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419)
>         at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
>         at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141)
>         at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:735)
>         at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
>         at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
>         at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:509)
>         at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:668)
>         at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:722)
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:177)
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:441)
>         at org.eclipse.jetty.util.ByteArrayISO8859Writer.writeTo(ByteArrayISO8859Writer.java:109)
>         at org.eclipse.jetty.server.Response.sendError(Response.java:606)
>         at org.eclipse.jetty.server.Response.sendError(Response.java:512)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:650)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
>         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
>         at org.eclipse.jetty.server.Server.handle(Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
>         at java.lang.Thread.run(Thread.java:745)
> 
> Best regards,
> Pablo

On 2016-02-03 06:41:24 -0500, Greg Wilkins wrote:

> Pablo,
> 
> thanks for the good analysis.
> 
> Note that in the master branch (for Jetty-9.4.x), we have significantly reworked the exception handling specifically for looping problems like this.
> 
> Looking at your suggested fixes now...

On 2016-02-03 07:35:57 -0500, Greg Wilkins wrote:

> Created attachment 259522
> Test Harness
> 
> This is an attempt to reproduce the 100%.  I cannot reproduce, so there must be something different about your setup or how the client is closing.  Can you try to reproduce within this test harness?

On 2016-02-11 08:56:49 -0500, Pablo Frias wrote:

> Thanks Greg, sorry for the delay. I am currently working on a sample that shows the issue. In our system, we have an embedded Jetty server + Spring MVC as a basic configuration.
> I created a simple single-class sample with this config but so far it works fine. However, in one case, leaving the program running during almost 4-5 days in a row, we could see the issue happen. Still, this is quite weird.
> I will back when I get the sample running.

On 2016-02-15 07:39:08 -0500, Pablo Frias wrote:

> Created attachment 259760
> Basic Scenario
> 
> This is a (very) basic scenario including features that we are using (embedded Jetty + Spring MVC). To test it, we use the command:
> 
> curl -i -X POST -H "Content-Type: multipart/form-data" -F "file=@a_big_file" http://virtual_server:57001/file/send
> 
> an cut the transmission manually. The strange thing is that we could reproduce it only once under a stressed server (after a few days running).

**Comment by pablofrias** [comment]
Hello Everyone, this is not a Jetty bug. We finally found that one JNI process was sending endless SIGPIPE signlas from Linux Kernel. Removing this fixed the issue.
