### ISSUE TITLE
Ability to track Request object through redirects

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2891]
Following up on https://github.com/eclipse/jetty.project/issues/1445#issuecomment-410055732 we need a way to figure out whether one `Request` object is the result of another `Request` getting redirected. In Jetty terminology, we need a way to find out whether two `Request`s are part of the same "conversation".

Currently I am reading this information using reflection but this is slow and brittle.

**Comment by sbordet** [comment]
You can disable automatic redirection (`HttpClient.setFollowRedirects(false)`), and do it yourself with the utility class `HttpRedirector`.
Would that work for you?
