### ISSUE TITLE
trailing spaces

### ISSUE THREAD

**Issue by p-alik** [eclipse/jetty.project#2898]
For sure the issue is of low priority, but for optical matter it would be nice to solve it.

Many of files are containing lines with trailing spaces.

They could be easily removed with
```bash
find  -type f -name "*.java" -exec sed -i 's/ *$//' {} \;
```

**Comment by joakime** [comment]
This should be part of the New Years Eve big syntax cleanup effort.

**Comment by joakime** [comment]
Closing this as it will be addressed by #3059
