### ISSUE TITLE
Avoid Listener instantiation during QuickStart generation

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2903]
Listener instances are created during quickstart generation phase. Ideally running user code during quickstart generation should be avoided.

**Comment by gregw** [comment]
Current and proposed interactions (generated from free version of  https://www.websequencediagrams.com/ thanks!)
![quickstart](https://user-images.githubusercontent.com/70829/45459030-d76c0680-b739-11e8-8334-35b894da6328.png)

**Comment by janbartel** [comment]
Closed, fixed.

**Comment by janbartel** [comment]
A ListenerHolder change that is part of this issue is not correct: in ListenerHolder.setListener(listener), we should not call setClassname() because that nulls out the class instance.

**Comment by janbartel** [comment]
Fix applied.
