### ISSUE TITLE
jetty-maven-plugin run goal adds output directory of reactor project dependencies to classpath without regard for scope

### ISSUE THREAD

**Issue by knutsiem** [eclipse/jetty.project#2906]
Consider an `mvn jetty:run` reactor build with one war module and one jar module. The war module has a dependency to the jar module with scope provided. Classes from the jar module are available in the running webapp.

Seemingly, the cause of this is that output directories of resolved project references in particular are added without regard for artifact scope in `JettyRunMojo.getDependencyFiles()`:
https://github.com/eclipse/jetty.project/blob/27208684755d94a92186989f695db2d7b21ebc51/jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java#L528-L558

I'm using version 9.4.12.v20180830. If needed I can attach a small project illustrating the problem.

**Comment by olamy** [comment]
Thanks for report!
Yes please provide a small project to reproduce.

**Comment by knutsiem** [comment]
[jetty-maven-plugin-provided-module-dep.zip](https://github.com/eclipse/jetty.project/files/2383262/jetty-maven-plugin-provided-module-dep.zip)

`mvn jetty:run`

ClassLoadingTestinServletContextListener should throw ClassNotFoundException
when starting Jetty because class test.Api should not be present at runtime as
it is in the jar of a dependency with scope provided.

Instead, the class is available as demonstrated by the message sent to
System.out:

Class test.Api is available and loaded by classloader
WebAppClassLoader=1788048182@6a937336. Expected ClassNotFoundException.

**Comment by olamy** [comment]
pr #2914

**Comment by olamy** [comment]
fixed with #cfe7fa1cb2d418e01405b7a76063a9ab85704839

**Comment by knutsiem** [comment]
Thanks!
