### ISSUE TITLE
Disable to see server status info in response

### ISSUE THREAD

**Issue by muhammedOzbilici** [eclipse/jetty.project#2908]
Is there any tag to allow only for localhost to see server info ?
For example , with this tag ,I can disable server version info in response.
`<Set name="sendServerVersion">false</Set>`

**Comment by joakime** [comment]
The `Server` response header control `sendServerVersion` is a connector level configuration that impacts the HTTP Generator for that connector.

Your solution is to have multiple `ServerConnector`s.

1. One listening on `localhost` with that option set to true.
2. One listening on your public interface with that option set to false.

**Comment by joakime** [comment]
There's no path called `/server-status` on Jetty.

If this is your own webapp / servlet / handler, then add some access controls to that specific url-pattern within your webapp.  (The most appropriate and easiest solution)

You could also have that be an isolated webapp that only exists on a named ServerConnector (that you have conveniently declared to only listen on localhost)
Eg: you have ServerConnector listening on localhost and a name of `"local"`, you have your `${jetty.base}/webapps/server-status.xml` declared with a virtualhost entry of `@local`.  (requires 2 ServerConnectors, and is a average difficulty solution)

You could also wrap your `WebAppContext` (declared/configured in your `${jetty.base}/webapps/server-status.xml`) to wrap an IPAccessHandler that only whitelists localhost. (a complex solution)

**Comment by joakime** [comment]
note: A resource on path `/server-status` and `<Set name="sendServerVersion">false</Set>` are completely different things and are unrelated.
