### ISSUE TITLE
Remove B64Code

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2909]
The ancient `B64Code` class in `jetty-util` should be replaced by JDK 8's `Base64` class, which is more up-to-date with base64 RFCs and not maintained by us.

**Comment by gregw** [comment]
I have merged @joakime 's PR #3640 
@lachlan-roberts can you do another for using ` java.util.Base64.Decoder#wrap(InputStream)` in `MultiPartInputStreamParser`

**Comment by lachlan-roberts** [comment]
@gregw I don't think you can just do this to replace the `Base64InputStream` class. The InputStream used has the content as base64 but the part boundary as plain text.

The `MultiPartInputStreamParser` class has been deprecated and the `Content-Transfer-Encoding` has also been deprecated from [RFC7578](https://tools.ietf.org/html/rfc7578#section-4.7). So it is probably not worth spending much effort trying to improve the performance of this.
