### ISSUE TITLE
useFileMappedBuffer true is an inconvenient default for jetty-maven-plugin on Windows

### ISSUE THREAD

**Issue by knutsiem** [eclipse/jetty.project#2925]
Windows users of jetty-maven-plugin's run goals quickly encounter the problem of locked files for web resources such as .html, .css and .js files. After finding out about the `org.eclipse.jetty.servlet.DefaultServlet` init-param useFileMappedBuffer being true being the cause (perhaps from [Troubleshooting Locked Files on Windows](https://www.eclipse.org/jetty/documentation/9.4.x/troubleshooting-locked-files-on-windows.html)), the question becomes how to set it to false _when using jetty-maven-plugin_.

The simplest way I have found that is applicable to 9.4.x is to provide an `override-web.xml`

   ```xml
  <?xml version="1.0" encoding="UTF-8"?>
  <web-app 
      xmlns="http://xmlns.jcp.org/xml/ns/javaee" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
      version="3.1">

    <!-- Don't use memory-mapped files for static resources as it causes locked files on Windows. -->
    <servlet>
      <servlet-name>default</servlet-name>
      <init-param>
        <param-name>useFileMappedBuffer</param-name>
        <param-value>false</param-value>
      </init-param>
    </servlet>

  </web-app>
   ```
   
with the following `<plugin>` `<configuration>`

   ```xml
   <webApp>
     <overrideDescriptor>${project.basedir}/src/dev/jetty/override-web.xml</overrideDescriptor>
   </webApp>
   ```

While the above solution is relatively simple, leaving it to every project to piece this puzzle together is not ideal. There may be downsides to the above solution I am unaware of; It seems like the most common solution is to duplicate and modify Jetty's `webdefault.xml` -- a verbose solution (500+ lines) that also introduces a maintenance burden of keeping it in sync with the one distributed with Jetty. Looking at the "Troubleshooting ..." guide mentioned above, using a connector not based on NIO appears to be a possibility, but I am not aware of any such connectors. 

Jetty is not to be blamed for memory-mapped files causing locked files on Windows. I'm assuming there are very good (performance?) reasons to use NIO and memory-mapped files. However, in the case of jetty-maven-plugin, the key feature is rapid development, i.e. the ability to quickly deploy changes. 

Would it be possible to change the default value of `useFileMappedBuffer` from true to false for jetty-maven-plugin? If not, it would at least be helpful if the jetty-maven-plugin documentation mentions that this is an issue for Windows users (and those seeking portable builds) and what the preferred way to avoid the problem is.

**Comment by joakime** [comment]
The absolute most common reason for locked files and directories on windows is actually the JVM internal Java Class Cache from URLConnection.
The next most common is other JVM's that haven't died yet. (check your `jps` for other JVMs that are still lingering)
Still quite common are singleton's from various classes (3rd party and jvm internal!) that cache open resources and prevent them from being either cleaned up by the GC or the FileSystem.
See https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/preventers for examples of preventers that we ship to prevent classloader resource lockups on windows.
Finally, at the very end, are memory mapped file references and NIO, a tiny category that is very timing sensitive, and is often not a problem on windows if you have no active connections and a webapp that has been idle long enough.

For the majority of users that encounter locked files on Windows, the `useFileMappedBuffers` change isn't a fix that will work for them.
Glad it's working for you though.

**Comment by joakime** [comment]
@janbartel what do you think about having a few new `<configuration>` options on `jetty-maven-plugin` for both of the following?

* DefaultServlet.setUseFileMappedBuffers
* ResourceService.setDefaultUseCaches

Yes, I know both can be configured away with XML, but they are quite common (on Windows) to configure to off/false.

**Comment by janbartel** [comment]
I'm not opposed to it, but on the other hand, the xml setup would have to be done for the webapp to work in the distribution anyway.

**Comment by knutsiem** [comment]
I might be misunderstanding but if you're saying that the same configuration must be applied in production with XML that only applies to those who actually run Jetty in production. I would expect those users to be much more familiar with Jetty's mechanics, understanding that configuration applied to the Maven plugin may be somewhat of a duplication and perhaps even preferring the configuration mechanism that will apply in production.

For myself and many others, using Jetty Maven Plugin has been a great way to speed up development while deploying to heavier containers in production.

**Comment by janbartel** [comment]
@knutsiem I don't think we need to add any extra configuration params to the plugin. You can either use the override-web.xml as you previously pointed out, or, you can **directly configure this into the plugin** already:
```xml
<webApp>
  <_initParams>
          <org.eclipse.jetty.servlet.Default.useFileMappedBuffer>false</org.eclipse.jetty.servlet.Default.useFileMappedBuffer>
  </_initParams>
</webApp>
```

So I think we just need to document this.

**Comment by joakime** [comment]
PR #3061 has been opened for this documentation concern.

**Comment by janbartel** [comment]
Doc updated.

**Comment by knutsiem** [comment]
@janbartel Great doc update, thanks! I was not aware of `<_initParams>`. That's really useful and convenient!
