### ISSUE TITLE
Error during initial RequestDispatch with bad request query results in failure for ErrorHandler to process

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2936]
The chain of events ...

1. Initial request with bad URI `/status?baa=%88%A4`
2. Servlet at `/status` attempts to forward to correct status page: `getRequestDispatcher(`/longer-status.do`).forward(req,resp)`
3. The `getRequestDispatcher()` call fails with BadMessageException(400) due to the bad query string.
4. The ErrorPageErrorHandler is setup to forward `BadMessageException` to `/internalError` name servlet.
5. This second forward within ErrorPageErrorHandler also triggers a BadMessageException(400)
6. Results in a generic / simple error page response.

Tested on Jetty 9.4.12.v20180830.
Example project demonstrating this behavior is at https://github.com/joakime/error-handling-bad-messages

**Comment by gregw** [comment]
I cannot reproduce this error? I have tried the same project on both 9.4.12.v20180830 and 9.4.x branch
I have also added a similar test to the HEAD of 9.4.x with c3ca4b7, which even attempt to get the parameters again within the error page.

Can you attach any exceptions you are seeing?

**Comment by joakime** [comment]
Updated testcase to replicate reported scenario properly on branch `jetty-9.4.x-issue-2936-badmessage-error-handling`.
It fails as reported now.

**Comment by joakime** [comment]
The problems reported are usages entirely within `Request.mergeQueryParameters()`.
The original `request.getRequestDispatcher(String path).forward(request, response)` and  
the resulting use of RequestDispatcher in `ErrorHandler.doError(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)`

https://github.com/eclipse/jetty.project/blob/c3ca4b7ee9d979e6d2e975bff521e4b3746c0c62/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L112-L119

Line 112 above fails during error dispatching

**Comment by joakime** [comment]
Closing, Work completed and merged.
