### ISSUE TITLE
ProxyServlet with prefix and null context

### ISSUE THREAD

**Issue by radfast** [eclipse/jetty.project#2937]
In 9.4.x, in the `Transparent` proxy, I think [this line of code](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L723)

    _prefix = _prefix == null ? contextPath : (contextPath + _prefix);

should maybe read like this instead, at least in a situation where `_prefix` is not null:

    _prefix = contextPath == null ? _prefix : (contextPath + _prefix);

----------------------------------------------

The current code produces this in logs when trying to use ProxyServlet when contextPath is null, even when the servlet's handler has a good mapping from `.addServletWithMapping()`.

    2018-09-28 14:22:14.904:DBUG:oejpP.194a1b5:qtp22374712-13: org.eclipse.jetty.proxy.ProxyServlet$Transparent-194a1b5 @ null/media to https://media-server
    2018-09-28 14:22:14.904:DBUG:oejpP.194a1b5:qtp22374712-13: 21964987 rewriting: http://localhost:8080/media/image.jpg -> null

My intended parameters are:

    prefix: /media
    proxyTo: https://media-server

But in `AbstractProxyServlet` the code has changed the `_prefix` to `"null/media"` because the ServletContext.getContextPath() was null. And that causes the proxy to redirect everything to null because with _prefix set to `null/media`, nothing's going to match that.  For more details of the context in which I'm reporting this, please see https://stackoverflow.com/questions/52557018/jetty-9-x-proxyservlet-how-to-set-up-servletcontext-correctly-in-xml

**Comment by joakime** [comment]
you don't seem to have setup a ServletContext?

Are you using the `ProxyServlet` (or the better `AsyncProxyServlet`) from within a `ServletContextHandler`?
I hope you are not using a raw `ServletHandler` (as that's only for the most extremely simplistic of use cases)

**Comment by joakime** [comment]
I went ahead and provided a solution for you on the stackoverflow side.
See: https://stackoverflow.com/a/52597488/775715

**Comment by radfast** [comment]
Thank you very much for your time.

Seems like many of the older guides and examples I found were badly out-dated.  I hope this and the stackoverflow answer will help anyone else who finds them in future.
