### ISSUE TITLE
NullPointerException when BufferingResponseListener#onContent() receives empty content.

### ISSUE THREAD

**Issue by martin-g** [eclipse/jetty.project#2938]
After upgrade from 9.4.11 to 9.4.12 I get a NPE:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.util.BufferUtil.flipToFill(BufferUtil.java:180)
	at org.eclipse.jetty.util.BufferUtil.append(BufferUtil.java:417)
	at org.eclipse.jetty.client.util.BufferingResponseListener.onContent(BufferingResponseListener.java:127)
    ...
```

The problem is at https://github.com/eclipse/jetty.project/blob/c3ca4b7ee9d979e6d2e975bff521e4b3746c0c62/jetty-client/src/main/java/org/eclipse/jetty/client/util/BufferingResponseListener.java#L119 where `length` is 0 in my case and `buffer` is still `null`.
The condition (`if (0 > 0)`) doesn't pass and because of this https://github.com/eclipse/jetty.project/blob/c3ca4b7ee9d979e6d2e975bff521e4b3746c0c62/jetty-client/src/main/java/org/eclipse/jetty/client/util/BufferingResponseListener.java#L127 is executed with `buffer` still being `null`.

**Comment by joakime** [comment]
Opened PR #2944

**Comment by sbordet** [comment]
@martin-g please attach full stack trace.

There is no reason we call `onContent()` if the response has no content. So either there is something else going on, or we introduced a bug elsewhere and we should not call `onContent()`.

@joakime your PR cures the symptom, not the cause, so it's on hold for now.

**Comment by sbordet** [comment]
@martin-g can you also dump the request/response headers, or attach a network trace via Wireshark?

**Comment by martin-g** [comment]
In that case we have to fix it in our code. It is in a test code with mocks involved.
Thank you!
