### ISSUE TITLE
DebugListener can't log enterScope events

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#294]
migrated from Bugzilla [#487200](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487200)
status NEW severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.3.7_ on platform _All_
Assigned to: Project Inbox

On 2016-02-04 04:55:39 -0500, Jan Bartel wrote:

> As the DebugListener is a ServletContextListener that instantiates and adds a ContextScopeListener when its contextInitialized() method is called, it is too late for it to be able to log scope entry inside ContextHandler.doStart(). This has become apparent after bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=487198 was fixed.

**Comment by janbartel** [comment]
@sbordet  the only way I can think of to fix this is to make the DebugListener a ContextScopeListener and do all of the initialization (creating a ServletContextListener, a RequestListener etc) guarded by an atomic in the listener's enterScope method.  The downside to this is that every single invocation of the listener enterScope method is going to have to consult the atomic.

The way it is presently implemented, as a ServletContextListener that does all of its initialisation in the contextInitialized() method, it is called way too late to be able to register the initial scope entry when the context is starting up.

Do you have any ideas? Maybe we should just live with this limitation of the DebugListener and document that it can't register the initial enterScope?

**Comment by sbordet** [comment]
@janbartel I'm not sure I understand the problem.

At first I thought, "why are we not using a `Handler`?", but then I saw that `DebugHandler` was deprecated in favor of `DebugListener` fixing [477123](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477123).

Is the problem only that the first request is not logged properly?
Because after `DebugListener` is added as scope listener, it should be triggered for every scope event, no?

**Comment by janbartel** [comment]
@sbordet the problem is that it cannot log the very first scope enter event when the context starts up. This is because the listener is initialized AFTER the scope is entered on startup.

**Comment by sbordet** [comment]
I would just document this limitation. It's just a debug utility after all.

**Comment by gregw** [comment]
We can modify ContextHandler so in addEventListener  it does:
```java

        if (listener instanceof ContextScopeListener)
        {
            _contextListeners.add((ContextScopeListener)listener);
            if (__context.get()!=null)
                ((ContextScopeListener)listener).enterScope(__context.get(),null,"Listener registered");
        }
```

**Comment by janbartel** [comment]
@gregw  good idea, will do

**Comment by janbartel** [comment]
Fix applied.
