### ISSUE TITLE
Use Eclipse IP Generated legal documents

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2942]
The Eclipse Foundation has a legal document generator that has been in use by various other Eclipse projects.

The RT/Jetty project has it's own generated legal documents.

See: https://www.eclipse.org/projects/tools/documentation.php?id=rt.jetty

We should review the generated documents on the above link and look into adopting them in our own project.
This could tie into the efforts in Issue #2923 as well

**Comment by joakime** [comment]
I think the junit references should not be there.
Likewise for the mockito references.

**Comment by gregw** [comment]
Also the copyright statement is not strictly correct as we assign to Mort
Bay, although I'm not sure there is value in that other than it is what we
have done.

**Comment by joakime** [comment]
Work completed on commit bc1e58b0f591311b5909029c13b0b5d620a18d49
