### ISSUE TITLE
Inaccurate Introduction about websocket in Document Ch. 26

### ISSUE THREAD

**Issue by luduoduo** [eclipse/jetty.project#2951]
In the Chapter 26. WebSocket Introduction. (https://www.eclipse.org/jetty/documentation/current/websocket-intro.html)
"WebSocket is a new protocol for bidirectional communications **over HTTP**."
It is inaccurate that websocket is based "over" http, but the truth is over TCP, although its connection is initiated from HTTP. So as a brief introduction, in my opinion, the Jetty document should keep this line accurate to avoid misunderstanding.

**Comment by joakime** [comment]
"Initiated via HTTP/1.1 upgrade and providing basic message framing, layered over TCP" ?

**Comment by WalkerWatch** [comment]
Sounds good to me, Joakim.

It is worth noting that the entirety of our Websocket documentation is going to be re-written or at the very least heavily edited, once Jetty 10 releases to account for the large number of changes that have been/are being made.
