### ISSUE TITLE
About the problem of embedded filter filtering HTTPS in jetty-proxy?

### ISSUE THREAD

**Issue by ToBeAMonk** [eclipse/jetty.project#2956]
I used the original jetty-proxy in jetty 9, when the embedded start ProxyServer, after modifying the browser's proxy port, all access can be through the proxy server, I added my own filter in ProxyServer, add the way is:

> ServletHandler handler = new ServletHandler(); FilterHolder fh = handler.addFilterWithMapping((Class) OTLFilter.class, "/*", EnumSet.of(DispatcherType.REQUEST));
> context.addFilter(fh, "/*", EnumSet.of(DispatcherType.REQUEST));

But my filter can only filter HTTP requests, but I can't filter HTTPS. Please help me.I am a new person in the workplace.

**Comment by sbordet** [comment]
I'm not sure I understand where your filter is.

What you need to know is that if you setup a forward proxy, then clear-text requests will arrive to the proxy, which will forward them to the target server; encrypted requests are _tunnelled_ directly to the target server.

You cannot look at encrypted requests in your proxy because they will be encrypted by the client using the target server cryptographic material. Your proxy will just see encrypted bytes (that cannot decrypt).

**Comment by ToBeAMonk** [comment]
Thank you for your reply, my filter is a project in the company, there is an entrance, that is, OTLFilter, HTTP and HTTPS requests can be proxy, but only HTTP through the company's filter project, HTTPS does not pass, what can make HTTPS pass?

**Comment by ToBeAMonk** [comment]
I added my own filter project to the jetty-proxy proxy proxy proxy server, which is mainly about making changes to the content returned from visiting the site. For example, I visited https://www.google.com to replace the word "google" on Google's home page with "elgoog".

All in all, HTTP requests can pass through my filter, and now what is needed is the way HTTPS passes through my filter, and I'm in a hurry.

There are ways to add my own filter to the problem. I need help.

**Comment by ToBeAMonk** [comment]
@sbordet Thank you for your reply, Mr. Bordet. If we proxy our own HTTPS site, we have the relevant key, can we modify the return content in the proxy?I beg your reply.

**Comment by ToBeAMonk** [comment]
@sbordet  Thank you very much sir.You've developed jetty, and I don't know how to use it. The gap is clear. Jetty-proxy in the jetty source code is a forward proxy. If you use a reverse proxy, does that mean you don't use jetty-proxy in the jetty source code anymore? As you said, using a reverse proxy can do what I want, but I only know n Ginx can be used as a reverse proxy. What should I do with jetty?
