### ISSUE TITLE
http_config.setOutputBufferSize maybe block?

### ISSUE THREAD

**Issue by ligzy** [eclipse/jetty.project#2958]
HI, 
Here is my question,
I use https/2.
I have this set:
  	        https_config.setRequestHeaderSize(1024 * 1);
		https_config.setResponseHeaderSize(1024 * 1);
		https_config.setOutputBufferSize(1024 * 8);

and i output through the outputstream,
		response.getOutputStream().write(body);
		response.getOutputStream().flush();

if body's length >1024*8 , such as 8642 bytes, it will block till timeout?
I found that this will block. is it?

**Comment by sbordet** [comment]
The `outputBufferSize` is only an internal buffer that Jetty uses to aggregate lots of small writes into a larger write to the TCP stack.

This is an important optimization for example for JSPs that write small chunks of code many times.

Whether `write()` or `flush()` blocks depends mostly on other things.

For HTTP/2 it heavily depends on the client-side flow control window.
Browsers have it large enough, but you don't tell what your client is.

**Comment by ligzy** [comment]
> The `outputBufferSize` is only an internal buffer that Jetty uses to aggregate lots of small writes into a larger write to the TCP stack.
> 
> This is an important optimization for example for JSPs that write small chunks of code many times.
> 
> Whether `write()` or `flush()` blocks depends mostly on other things.
> 
> For HTTP/2 it heavily depends on the client-side flow control window.
> Browsers have it large enough, but you don't tell what your client is.

I got, Maybe the client has some problem. Thanks!
