### ISSUE TITLE
Failed to start jetty.service: Unity jetty.service not found

### ISSUE THREAD

**Issue by ghost** [eclipse/jetty.project#2966]
Hi folks, 

I have been following this tutorial (http://zetcode.com/java/jetty/install/) and am stuck at "Starting the service" using 'sudo service jetty start'

I did exactly as mentioned in the post so far, I only used nano instead of vi and I replaced openjre with oracle-8-java
Im on a Raspberry Pi 3, that I bought a few days back

I'd really appreciate any help. If any files are needed to adress this issue, just tell me ... 
I am using putty on a windows computer for setting it up, however that should not change anything, I guess.

**Comment by janbartel** [comment]
@kev1807 that tutorial is based on an older version of jetty, we're up to 9.4.12 currently, so please try and make sure you're using the latest version.

Also, please describe what you mean by "stuck"? Do you run the command, if so what happens? Is there any error output, stacktraces etc? Please provide a thorough description of your steps, and any outputs generated.

**Comment by janbartel** [comment]
@rafialhamd  copy the $JETTY-HOME/bin/jetty.service file to  /etc/systemd/system/multi-user.target.wants/.  Then do the command "systemctl jetty enable" to tell the system that the service file is there.  You can now do "service jetty start".

**Comment by rafialhamd** [comment]
@janbartel I'm afraid I do not have the file: $JETTY-HOME/bin/jetty.service.
But, ONLY jetty.sh.
/opt/jetty/jetty-distribution-9.4.14.v20181114/bin# ls -a
.  ..  jetty.sh

What should I do, please...?
Thanks!

**Comment by cosenmarco** [comment]
You may create your own service file but it's not exactly easy to provide the same functionality of jetty.sh.

You can check this little project of mine to have an idea about how you could make it work:
https://github.com/cosenmarco/jetty-systemd-notifier

**Comment by rafialhamd** [comment]
@cosenmarco Thanks for the response! 
Will attempt your suggestion, next time, when I would need it.
