### ISSUE TITLE
HttpClient return onResponseFailure random failure - TLS expired cert

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#297]
migrated from Bugzilla [#487680](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487680)
status NEW severity *normal* in component *client* for *9.3.x*
Reported in version *9.3.7* on platform *PC*
Assigned to: Simone Bordet

On 2016-02-11 10:56:39 -0500, Jakub Migas wrote:

> Hi,
> In scenario server side certificate is expired.
> `HttpClient` during connection to `https://localhost:8443/hello` TLSv1.2 Jetty 8.1.12 server has random onResponseFailure method failure exception: mostly `SSLHandshakeException` but 1/10 is jetty or java `EofException` or `ClosedChannelException`.

**Comment by sbordet** [comment]
Closing as duplicate of #464.
