### ISSUE TITLE
Quickstart tests broken

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2975]
This affects jetty-9.4.x and jetty-10.0.x

Looks like it was caused by commit https://github.com/eclipse/jetty.project/commit/0ae0c500f0057d5c2f09e266bf8b15953a83ce22  to fix something do to with javadoc generation.  I think the inclusion of the change in the quickstart tests looks like an error - nothing to do with javadoc generation, and the build phase for the dependency plugin has to be way before package because it copies artifacts that the tests need.

**Comment by olamy** [comment]
definitely change the phase in quickstart test

**Comment by janbartel** [comment]
Fixed jetty-9.4.x and jetty-10.0.x
