### ISSUE TITLE
How can i ignore the order check of :authority

### ISSUE THREAD

**Issue by ligzy** [eclipse/jetty.project#2977]
Hi
Here is my question:
We have release some client sdk bae h2s, and the sdk send the header not in the correct order.
https2 connection can't be established with  "Pseudo header :authority after fields error".
(the Authorization send before the :authority.  it work in before version but not in 9.4.12.v20180830 ,so we can't notice this question:( .)

Has there some method to solve this quesion?

Thanks.

**Comment by sbordet** [comment]
The HTTP/2 specification requires that pseudo-headers such as `:authority` are sent before normal headers, see https://tools.ietf.org/html/rfc7540#section-8.1.2.
We fixed this in 9.4.12.

You need to fix your client.

**Comment by ligzy** [comment]
> The HTTP/2 specification requires that pseudo-headers such as `:authority` are sent before normal headers, see https://tools.ietf.org/html/rfc7540#section-8.1.2.
> We fixed this in 9.4.12.
> 
> You need to fix your client.

Thanks , I see ,BUT  there have many ten housands devices, in user's hand.we can't handle.:(

**Comment by sbordet** [comment]
@gregw what do you think? This check is done in HPACK... perhaps a configurable option?

**Comment by joakime** [comment]
Not following the spec runs the common risk of also triggering intermediaries (load balancers, firewalls, etc) that must follow the spec too.
Your broken clients / tens of thousands of devices will fail with many other things, not just jetty.
The only real place to correct this is in your tens of thousands of devices.

**Comment by gregw** [comment]
If HTTP/2 had ever been released without these requirements, then we would definitely provide a backwards compatibility option.
However, it is considerable work to do this as we have to evaluate all the compliance tests in hpack and http2 (there are many) and decide which will be optional. We then need to write, configure,  test, document and maintain for the foreseeable future.    Not to be too mercenary about this... but this is exactly why we have commercial support clients (so we do this kind of work for them) and that the code is open source (you are free to fix yourself and build your own version).

I appreciate that dealing with bad clients is difficult, but so is maintaining optional compliance modes.

**Comment by joakime** [comment]
@sbordet @gregw this was reopened to possibly implement a configuration choice.  What's the plan? will this be done? or can we close this issue?

**Comment by sbordet** [comment]
I guess we can close.

**Comment by gregw** [comment]
@ligzy I'm going to close this for now, as I can't see a reason for us to take on this option.
If you wish to build your own release with that code removed, we are happy to give advice as to how to do that.
