### ISSUE TITLE
Review diffs 9.4.x to 10.0.x

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2979]
As branch `jetty-10.0.x` has undergone some messy changes, it is important to check that changes done in 9.4.x are present in 10.0.x and that we did not miss anything.

**Comment by joakime** [comment]
I removed the Stale label this one to keep it alive.
We still need to do this.

Joakim Erdfelt / joakim@webtide.com

**Comment by sbordet** [comment]
I think we are good on this - we did a large chunk of work.
The 2 releases (9.4.x and 10.0.x) are rolling well and we'll eventually address small differences.
