### ISSUE TITLE
qtp threads spin-locked in MBeanContainer.beanAdded

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#298]
migrated from Bugzilla [#487745](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487745)
status NEW severity *critical* in component *websocket* for *9.3.x*
Reported in version *9.3.7* on platform *PC*
Assigned to: Joakim Erdfelt

On 2016-02-12 10:19:10 -0500, Kristoffer Erlandsson wrote:

> After upgrading Jetty we started running into issues where several of our qtp threads were spin-locked with the stack trace below.
> 
> We have had similar problems before, with spin-locks in hashmaps and they have always been caused by unsynchronized access to a thread-unsafe Map.
> 
> From what I can tell, accesses to the WeakHashMap in question (_beans in MBeanContainer) are not synchronized and evidently the map is accessed concurrently by the qtp threads.
> 
> "qtp1807837413-2270" # 2270 prio=5 os_prio=0 tid=0x00007f650772e000 nid=0x75a7 runnable [0x00007f6510d1b000]
>    java.lang.Thread.State: RUNNABLE
>         at java.util.WeakHashMap.getEntry(WeakHashMap.java:431)
>         at java.util.WeakHashMap.containsKey(WeakHashMap.java:417)
>         at org.eclipse.jetty.jmx.MBeanContainer.beanAdded(MBeanContainer.java:148)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.addEventListener(ContainerLifeCycle.java:366)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:256)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:244)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.manage(ContainerLifeCycle.java:411)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:274)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:243)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.addManaged(ContainerLifeCycle.java:339)
>         at org.eclipse.jetty.websocket.server.WebSocketServerFactory.upgrade(WebSocketServerFactory.java:612)
>         at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:197)
>         at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:207)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
>         at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
>         at org.eclipse.jetty.server.Server.handle(Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
>         at java.lang.Thread.run(Thread.java:745)

**Comment by sbordet** [comment]
@gregw The fix does not work because `Locker` is not reentrant, and many `MBeanContainer` methods are reentrant (e.g. `beanAdded()`).

Also, we should pay attention that we don't call application code (in particular listeners) while holding the lock.

I'd suggest to use plain old `synchronized` here, and copy collections before iterating over them (rather than iterating over them while holding the lock).

**Comment by sbordet** [comment]
Fixed by replacing `WeakHashMap` with `ConcurrentHashMap` in `MBeanContainer`.
