### ISSUE TITLE
Getting 200 code in onResponseFailure() method

### ISSUE THREAD

**Issue by Pratibha24** [eclipse/jetty.project#2982]
Hello,

I have done setup for twitter HTTP streaming using Jetty where i get the real time tweets from the back-end.

There is an observation that if i send any header in the request which backend does not accept (for example in case of twitter, have sent cache-control HTTP header) then it goes to the onResponseFailure() method but in the Response it gives the code as 200 OK while its a failure and there is no way to identify that request has been failed and what was the reason since it sends 200 OK.

Please help!

Thanks,
Pratibha

**Comment by joakime** [comment]
There's some information missing on this issue.

Are you using the Jetty Http Client?  If so, which version?
Are you accessing the normal Twitter server? or the api server?
When you provide it information / headers that you think are breaking it, what are the complete headers and body content of the response?

**Comment by Pratibha24** [comment]
Thanks for the reply. 

I will check once the twitter API behavior.
As of now i will close this issue.

Regards,
Pratibha
