### ISSUE TITLE
Websocket leak if exception in @OnWebSocketMessage

### ISSUE THREAD

**Issue by dmitrymurashenkov** [eclipse/jetty.project#2991]
I've written a test that connects client websocket to server, sends message and closes websocket. This is done in loop.

If no exceptions are thrown then sockets are closed and number of open file descriptors stays the same.

However if exception is thrown out of @OnWebSocketMessage method then file descriptor leak occurs.

In @OnWebSocketError the Session.isOpen() is true, then in @OnWebSocketClose it is false.

Calling Session.close() doesn't help, however calling Session.disconnect() fixes the problem.

I've attached maven project with unit test to reproduce the problem. Run it and see number of fds grow with:

`lsof -p <pid> | wc -l`

[jetty-ws-test.zip](https://github.com/eclipse/jetty.project/files/2484321/jetty-ws-test.zip)

Jetty version: 9.4.8.v20171121

**Comment by dmitrymurashenkov** [comment]
Just retested with Jetty 9.4.12.v20180830 - not reproduced. Calls to Session.close() and Session.disconnect() can be omitted altogether and no leak occurs.

**Comment by joakime** [comment]
This was likely fixed with issue #2655
