### ISSUE TITLE
Use webapp artifacts for examples and tests 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2992]
Lots of tests and examples are using relative paths to find webapps and keystores to run/test against. Examples include:
  + [OneWebApp](https://github.com/eclipse/jetty.project/blob/0962fdb4e6d4c3ce4153d7298ff1124a30722db7/examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneWebApp.java#L51-L57)
  + [ManyConnectors](https://github.com/eclipse/jetty.project/blob/0962fdb4e6d4c3ce4153d7298ff1124a30722db7/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyConnectors.java#L48)
  + [AsyncRestServer](https://github.com/eclipse/jetty.project/blob/0962fdb4e6d4c3ce4153d7298ff1124a30722db7/examples/async-rest/async-rest-server/src/main/java/org/eclipse/jetty/example/asyncrest/AsyncRestServer.java#L35-L42)

This is fragile and dependent on working directory, IDEs etc.

Instead, we should import webapps as maven artifacts and install them in a known location in target.

**Comment by gregw** [comment]
@olamy this feels like something you could tackle?

**Comment by olamy** [comment]
@gregw yup for sure.

**Comment by olamy** [comment]
starting working on it and found few examples broken/not maintained :)

**Comment by olamy** [comment]
depends on #3138

**Comment by olamy** [comment]
definitely todo

**Comment by joakime** [comment]
This was addressed in multiple commits. 
First introduced with 862e6d008e99223ad048860dd69c19914732a4f7 
Finished up in PR #4056
