### ISSUE TITLE
Jetty handles browser Content-Encoding

### ISSUE THREAD

**Issue by doxiaoguo** [eclipse/jetty.project#2994]
Content-Encoding in Request Headers in the browser is Gzip, is it decompressed in jetty? I just saw GzipHandler

**Comment by gregw** [comment]
If the inflateBufferSize is configured to a value > 0, then GzipHandler will handle inflation of compress request bodies.
Normally creating an issue is not a good way to ask such usage questions... but in this case I see our javadoc is lacking... so I will fix that here.

**Comment by gregw** [comment]
Actually there is javadoc: http://download.eclipse.org/jetty/9.4.3.v20170317/apidocs/org/eclipse/jetty/server/handler/gzip/GzipHandler.html#setInflateBufferSize-int-

**Comment by doxiaoguo** [comment]
@gregw Thank you ！

**Comment by doxiaoguo** [comment]
@gregw I do not think you have understood my meaning or my understanding ability is too weak. If the browser returns a Gzip, for example, Content-Type: text / html, whose Content-Encoding is gzip, I need to decompress the Gzip if I want to get the text / HTML plaintext in the code. I wonder if Jetty has decompressed Gzip in addition to the Gzip-compressed handler. If it exists, where is it? I look forward to your reply.

**Comment by joakime** [comment]
@doxiaoguo the GzipHandler in Jetty does 2 things.

1. If the HTTP Request body content is compressed and has a `Content-Encoding` header with the value `gzip`, then the Request Body Content is decompressed when being read by your Filters and Servlets.  (It is important that you have a valid `inflateBufferSize` value configured for the `GzipHandler` for this to work.)
2. If the HTTP Response body content being produced by your Filters and Servlets belong to the matching set of conditions you have configured on the `GzipHandler` (paths, mime-types, methods, etc) and the HTTP Request contains an `Accept-Encoding` header that allows for `gzip` then the response body content is compressed by the `GzipHandler` automatically on its way out to the HTTP client.

There is no other compressions / decompression behaviors performed by GzipHandler.

**Comment by doxiaoguo** [comment]
@joakime  Thank you very much. I will understand your reply carefully.
