### ISSUE TITLE
qtp thread blocking indefinitely due to Invalid TLS Padding Data exception

### ISSUE THREAD

**Issue by git-jamie-s** [eclipse/jetty.project#2999]
Jetty 9.3.13
I have a web client that submits some data periodically.   We have thousands of users, and one single user in particular is causing hung threads in Jetty.

Essentially, with HttpServletRequest request, I am calling:

    InputStream stream = request.getInputStream();
    byte[] bytes = new byte[65536];

    int count;
    int offset = 0;
    do
    {
        count = stream.read(bytes, offset, bytes.length-offset);
        if (count > 0) 
            offset += count;
    } while(count > 0 && offset < bytes.length);

If the client is connected over http, _stream.read(...)_ will return when the input stream is exhausted, and my servlet can continue normally.
However, when connected over https, _stream.read(...)_ hangs indefinitely, and the qtp thread is stuck until I restart the server.

Attached is the DEBUG level Jetty logs, with names changed.
[scrubbed.log](https://github.com/eclipse/jetty.project/files/2492681/scrubbed.log)

Notes:

Line
45: New request comes in from client
84: WWW-Auth challenge
372: WWW-Auth challenge response
499: Invalid TLS padding data

At this point, that qtp thread is stuck in _HttpInput.blockForContent(...)_. 
Using JMX and taking a thread dump shows it is stuck.

Line 648: Server is being shut down
716: qtp thread receives an _InterruptedIOException_ and finally leaves _HttpInput.blockForContent(...)_

As can be seen in the stack trace on line 716, Jetty was stuck in _HttpInput.blockForContent()_ for about 
10 seconds before I shut the server down.  We have seen qtp threads stuck for days, eventually consuming all threads in the pool, causing Jetty to become unresponsive.

We have confirmed that the do..while loop is not looping (Our actual code has log statements in it).

Thanks for any help!!!

**Comment by git-jamie-s** [comment]
I am upgrading to 9.4.12, and we'll see what happens when they connect next.

**Comment by joakime** [comment]
@git-jamie-s any update on this issue?

**Comment by joakime** [comment]
Closing due to lack of response.
We'll be happy to reopen this issue if you have any further information about the problem.
