### ISSUE TITLE
Augmenting service implementations with command line option

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3000]
@nicolaiparlog, 

We have a case where a class uses `ServiceLoader` to load implementations of service `org.foo.S`; the JPMS module where this class lives does not provide any service of that kind.

However, for testing purposes, we have - in the same Maven module - `src/test/resources/META-INF/services/org.foo.S` that provides a dummy service `org.foo.DummyS`.

AFAIU, Maven runs the tests on the module-path, and patches the JPMS module with the test classes.

When we run the tests, the service is not discovered (it was of course discovered when running on the class-path). That seems reasonable because the tests add the service but not in the JPMS way, and the test classes (since they are patched into the module) are in a proper JPMS module

Is there something like `--add-provides <module>/org.foo.S=org.foo.DummyS` that we can add on command line to the Maven Surefire Plugin?

There is a `jdk.internal.module.Modules.addProvides(Module m, Class<?> service, Class<?> impl)`, but apparently no public APIs?

Thanks!

**Comment by nicolaiparlog** [comment]
Hi @sbordet, sorry for never getting back to you on this. 😔 Is this still an open issue?

**Comment by sbordet** [comment]
@nicolaiparlog I could only see that as a missing options, and command line has `--add-reads` a concept that is not present explicitly in the module descriptor.
What else is missing?
Do you think it'll be worthwhile to drop a message on the JDK mailing list?
