### ISSUE TITLE
v9.3 Client hangs on 24 core machine

### ISSUE THREAD

**Issue by ivankelly** [eclipse/jetty.project#3005]
Observed with 9.3 series (oringally observed on 9.3.11.v20160721, but also observed on 9.3.25.v20180904).

Repro is simple, but I've only seen it happen on 24 core machines (on two different machines).
- clone https://github.com/ivankelly/incubator-pulsar/tree/http-proxy-test-debug
- mvn install -DskipTests
- cd pulsar-proxy && mvn test

There's only one test in this whole tree, I've removed the rest.

testMultipleRedirect is the failing test.

The test sets up two http backing servers and then Pulsar's proxy server, which uses a transparent proxy to proxy requests to the backing servers. The test simply tries to GET each path.

When the hang occurs, the first client GET, to server1 succeeds, but the second hangs and times out. The GET request is reaching the proxy server, which then tries to create a client to the backing server, and this is where it hangs.

In the call to create the http client to the backing server, the pool returns null.
```
13:42:15.564 [pulsar-external-web-31-16:org.eclipse.jetty.client.HttpDestination@199] DEBUG org.eclipse.jetty.client.HttpDestination - Queued HttpRequest[GET /blahblah HTTP/1.1]@38e2aa09 for HttpDestination[http://67.195.81.158:46138]@75d21b17,queue=1,pool=DuplexConnectionPool[c=0/256,a=0,i=0]
13:42:15.565 [pulsar-external-web-31-16:org.eclipse.jetty.client.DuplexConnectionPool@136] DEBUG org.eclipse.jetty.client.DuplexConnectionPool - Connection 1/256 creation
```
See https://builds.apache.org/job/pulsar_precommit_java8/4381/artifact/pulsar-proxy/target/surefire-reports/org.apache.pulsar.proxy.server.ProxyIsAHttpProxyTest-output.txt for full log.

It looks like there's a race in
https://github.com/eclipse/jetty.project/blob/3ce520221d0240229c862b122d2b06c12a625732/jetty-client/src/main/java/org/eclipse/jetty/client/DuplexConnectionPool.java#L138

It kicks off an async connection creation, but tries to return the idle connection without waiting for the async operation to complete. I don't know this code well, but I have verified that it is returning null from this call, which is hanging the request.

It doesn't seem to happen with 9.4 series, so I'm going to work around it by upgrading, but I thought I should let you all know. I suspect it may be something to do with there not being enough threads. Only 32 are configured, and 9.4 complains about this.

**Comment by joakime** [comment]
Large core count machines were an issue addressed in the Jetty 9.4.x series.

If you want to stay with the 9.3.x series, consider reducing your selector count.  Many folks report success at a selector count of 1.

``` java
int selectorCount = 1;
HttpClientTransport transport = new HttpClientTransportOverHTTP(selectorCount);
HttpClient client = new HttpClient(transport, sslContextFactory);
```

**Comment by ivankelly** [comment]
The code creating the clients is all jetty code (in the AbstractProxyServlet I guess), so I don't think I have access to that. Going to push to 9.4 in any case.

**Comment by joakime** [comment]
@ivankelly if it's `AbstractProxyServlet` then just set the `selectors` init-parameter.

https://github.com/eclipse/jetty.project/blob/3490add2a96e683c96693fa3c91c3c31c3ca66d1/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L349-L361

You could, alternatively, override the `newHttpClient()` method as well.

**Comment by joakime** [comment]
@ivankelly any update on your efforts for Jetty 9.4?

**Comment by ivankelly** [comment]
9.4 works fine, so feel free to close.

**Comment by joakime** [comment]
Closing per OP
