### ISSUE TITLE
jetty 9.4 jetty-web.xml for custom SessionManager and Session

### ISSUE THREAD

**Issue by smanikim** [eclipse/jetty.project#3008]
I am migrating from really old jetty version 6.1.26. We have custom SessionIdManager and Session. ( We add encoding/decoding to Sessions and different storage medium to Manager)
I have looked into https://github.com/eclipse/jetty.project/issues/1716 to understand how to create jetty-web.xml but looks like that wont work for me.

Could someone suggest me or point me to some doc

**Comment by smanikim** [comment]
Also, Can I do this stuff inside my code instead of jetty-web.xml

**Comment by janbartel** [comment]
@smanikim here's the documentation page on jetty-web.xml: https://www.eclipse.org/jetty/documentation/9.4.12.v20180830/jetty-web-xml-config.html

Note that for jetty-9.4,it would be preferable if you packaged up your custom session manager as a jetty module. Have a read of the administration section of the jetty documentation: https://www.eclipse.org/jetty/documentation/9.4.12.v20180830/startup-modules.html
