### ISSUE TITLE
Contributing instructions are out of date

### ISSUE THREAD

**Issue by johngmyers** [eclipse/jetty.project#301]
CONTRIBUTING.md and the contributing-patches section of the Jetty documentation contain out-of-date instructions.

> The canonical Jetty git repository is located at git.eclipse.org and we are unable to directly merge pull requests into the GitHub mirrored repository.

**Comment by jmcc0nn3ll** [comment]
https://github.com/jetty-project/jetty-documentation

repo for our documentation is there, we freely take pull requests :)

thanks for the ticket, this is on the list of things to iron out once this move is completed

**Comment by jmcc0nn3ll** [comment]
short and sweet: https://www.eclipse.org/jetty/documentation/current/contributing-patches.html

removed the old bad info and this should be enough, at least in short term...hoping that the whole github forking concept doesn't need explaining, at least at this point

**Comment by johngmyers** [comment]
CONTRIBUTING.md is still out of date

**Comment by joakime** [comment]
Fixed in commit e63f86ab2f9a4c446f18b11ac936182705c74a9e
