### ISSUE TITLE
Refactor HttpCompliance and HttpComplianceSection to be friendlier to customization

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3012]
(Discovered during analysis of #3009)

The `HttpCompliance` object is an enum with awkward CUSTOM0 entries for customization, it should really be a class.
The `HttpComplianceSection` seems OK at first blush.

**Comment by gregw** [comment]
+1  It was kept as an enum initially to jsut to keep compatibility with Jetty-9.x, but we can make the break of API in jetty-10 and avoid the clunky CUSTOMx enums.

**Comment by joakime** [comment]
Opened PR #3029
