### ISSUE TITLE
ErrorHandler http meta contentType doesn't match actual charset

### ISSUE THREAD

**Issue by rainmanhhh** [eclipse/jetty.project#302]
in method handle it set contentType to MimeTypes.Type.TEXT_HTML_8859_1 and write with ByteArrayISO8859Writer

in method writeErrorPageHead it set http header `<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>`

this makes non-ascii characters unrecognizable

suggest to set contentType by configuration, or at least change writeErrorPageHead to use iso-8859-1

**Comment by joakime** [comment]
All of the formatting within ErrorHandler has been overhauled.
This seems to have been addressed as well. (and even takes into account the `Accept` and `Accept-Charset` Request header too)
