### ISSUE TITLE
JDK 11 Infinispan test failure

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3024]
Jetty 10 builds fail test `ClusteredSessionScavengingTest.testClusteredScavenge()`.

https://jenkins.webtide.net/job/jetty.project/job/jetty-10.0.x/120/testReport/junit/org.eclipse.jetty.server.session/ClusteredSessionScavengingTest/testClusteredScavenge/

The reason is that Infinispan class `org.jboss.marshalling.river.Protocol` performs deep reflection on JDK class `EnumSet$SerializationProxy`, whose implementation has changed in JDK 11.

**Comment by sbordet** [comment]
@janbartel perhaps you have already opened an issue to Infinispan?

**Comment by janbartel** [comment]
There are more problems here. We need to update the version of infinispan to the latest. When we do that, then deserialize fails because the way they do that changed in the newer version. I have been working on a solution for a couple of days.

**Comment by janbartel** [comment]
@sbordet  the test failure you reported won't occur once we merge the fix from PR #2964  - that uses an entirely different way of serializing/deserializing data.

I tested PR #2964 also with jdk11 and it works fine. However there are some warnings produced like:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction$1 (file:/home/janb/src/jetty-eclipse/jetty-9.4.x/jetty-distribution/target/distribution/demo-base/lib/infinispan/infinispan-remote-9.1.0.Final.jar) to constructor java.io.OptionalDataException(boolean)
> WARNING: Please consider reporting this to the maintainers of org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

I attempted to get rid of the warnings by upgrading infinispan to 9.4.0 from 9.1.0, however that brings in an entirely different problem:  the deserialization mechanism changed sometime after 9.1.0 and now they have introduced an async thread pool to which we don't seem to have access and thus we cannot set what the appropriate classloader is to deserialize the data. I have posted a question on their support forum, lets see what they say.

**Comment by janbartel** [comment]
The suggestions from the support forum, whilst appreciated, are not practical for our use-case. I think the only solution is for us to do our own serialize/deserialize of the session attributes.

As that would entail changing the stored session data format, we probably only want to do that once. Thus, I think PR #2964 should be amended (yet again) to also introduce this change to doing our own attribute serialize/deserialize. In that way, we only have to convert the legacy format sessions once, and we should also be immune from the changes to the threading when we upgrade to infinispan 9.4.0. @sbordet  comments?

**Comment by janbartel** [comment]
I blame the jetlag: the changes I outlined in the previous comment I already folded into this PR. So it's good to go for final review and then merge.

**Comment by janbartel** [comment]
Closing after merge of PR #2964, which fixes the test failure under jdk11. We can open a separate issue to update to infinispan-9.4.0 when necessary.
