### ISSUE TITLE
I can't start demo page when I try to start jetty based on steps in quick start document.

### ISSUE THREAD

**Issue by k-andou** [eclipse/jetty.project#3033]
Summary
Documentation Problem
I can't start demo page when I try to start jetty based on steps in quick start document.

Step To Reproduce
1. open http://www.eclipse.org/jetty/documentation/current/quickstart-running-jetty.html
2. run "java -jar start.jar" and jetty starts.
3. open http://localhost:8080 and you will see 404 Error.
4. try next section Dome Base.

Actual Result
I can't run "cd demo-base/" because Jetty is still running.

Expected Result
I can run "cd demo-base/" and following commands.

Proposal
They should be "hit CTRL+C to stop jetty" after "you will see a 404 error page served by Jetty".

**Comment by WalkerWatch** [comment]
Thank you for the head's up. I will get this corrected/make it clearer.
