### ISSUE TITLE
Ability to retry port binding. 

### ISSUE THREAD

**Issue by krisnik** [eclipse/jetty.project#3037]
Sometimes when the service is restarted, OS may not release the port. So, this may cause the restart to fail with BindException. 

Please provide a way to retry port binding.

**Comment by joakime** [comment]
Jetty startup is so fast, it would probably be easier to just have the shell script detect the failed startup due to BindException and restart Jetty.

**Comment by JerryChin** [comment]
You can try `ReuseAddress` option.

**Comment by sbordet** [comment]
@krisnik as suggested, use `ServerConnector.setReuseAddress(true)`.
