### ISSUE TITLE
NPE when notifying the session listener if the channel is closed before a session has been opened

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#305]
migrated from Bugzilla [#487926](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487926)
status NEW severity *major* in component *http2* for *9.3.x*
Reported in version *9.3.7* on platform *PC*
Assigned to: Simone Bordet

On 2016-02-17 06:00:43 -0500, Jude Pereira wrote:

> Using the HttpClientTransportOverHTTP2, if the channel is closed before a session is opened, an NPE is generated.
> 
> Using the sources to http2-http-client-transport-9.3.7.v20160115:
> 1. The connection object declared on line 144 of class HttpClientTransportOverHTTP2 remains null if the method SessionListenerPromise#succeeded is never called.
> 2. Now, if the connection is closed due to a ChannelClosedException, SessionListenerPromise#onFailure (line 194) is called.
> 3. Since the connection in the SessionListenerPromise is null (as succeeded was not called), an NPE is generated.
> 
> Here's a stack trace:
> [HttpClient@380242442-14] INFO org.eclipse.jetty.http2.HTTP2Session - Failure while notifying listener org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2$SessionListenerPromise@2f02d770
> java.lang.NullPointerException
> 	at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2$SessionListenerPromise.onFailure(HttpClientTransportOverHTTP2.java:196)
> 	at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1021)
> 	at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:930)
> 	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:818)
> 	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:191)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:162)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101)
> 	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:97)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:197)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by judepereira** [comment]
I figured out a way to reproduce this: have the server send a self-signed certificate, which is not present in Java's keystore (the one in the JRE lib).

**Comment by judepereira** [comment]
Perhaps Jetty should throw a CertificateException?

**Comment by sbordet** [comment]
Thanks for the details about reproducing this. Fixed by adding the null-check guard.
