### ISSUE TITLE
Seeing a memory leak in com.rsa.sslj.x.cm security provider

### ISSUE THREAD

**Issue by serrabelli** [eclipse/jetty.project#3056]
jetty version 9.2.X

following are the security provider configured in java.security file
security.provider.1=com.rsa.jsafe.provider.JsafeJCE
security.provider.2=com.rsa.jsse.JsseProvider
security.provider.3=sun.security.provider.Sun

We are using openfire and every few days we see CPU going high and upon analysing the heap dump we see that the class com.rsa.sslj.x.cm is leaking memory, it has two hash maps which are leaking and one of the hash maps has multiple entries for the same host and different ephemeral port. I see thousands of such entries and different IP's.

sample:

10.50.14.104:59466 com.rsa.sslj.x.az @ 0x8af41a00
10.50.14.104:59466 com.rsa.sslj.x.az @ 0x8af41a03

It would be of great help if some one can point why this provider is leaking.

**Comment by sbordet** [comment]
@serrabelli this is the Jetty project and we don't know anything about `com.rsa.sslj.x.cm`.
You will have better chance at filing an issue to the project that provides the `com.rsa.sslj` security provider.

**Comment by sbordet** [comment]
@serrabelli sure but it's not Jetty code holding `SslSelectChannelEndPoint` and causing the memory leak.

**Comment by serrabelli** [comment]
Thanks Simone

I have attached the screen shot from heap dump for your reference. please check once and confirm 

<img width="736" alt="screen shot 2018-09-17 at 2 38 18 pm" src="https://user-images.githubusercontent.com/7894495/47907381-253afa80-deb1-11e8-9b95-20ded4be711b.png">

**Comment by sbordet** [comment]
I can tell you that we don't have any confirmed report of Jetty leaking memory.

From the screenshot I can see that an instance of the obfuscated class `c` is holding a reference to an object of class `SslSelectChannelEndPoint` via field `_engine`.
It is not Jetty code.

**Comment by joakime** [comment]
Also of not, Jetty 9.2.x series is EOL (End of Life) - https://www.eclipse.org/lists/jetty-announce/msg00116.html

Current supports and stable version of Jetty is 9.4.x series.  Most recent release is Jetty 9.4.12.v20180830.
