### ISSUE TITLE
Merge jetty-parent into jetty-project

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#306]
migrated from Bugzilla [#487521](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487521)
status NEW severity *trivial* in component *build* for *9.3.x*
Reported in version *9.3.5* on platform *All*
Assigned to: Jesse McConnell

On 2016-02-09 11:07:34 -0500, Joakim Erdfelt wrote:

> As part of the effort to move to github.com/eclipse/jetty.project ...
> 
> Merge the relevant pieces of jetty-parent into jetty-project.
> 
> Remove the defunct/deprecated parts of jetty-parent in the process.

**Comment by gregw** [comment]
nice!
