### ISSUE TITLE
Monitor contention in AbstractNCSARequestLog

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#307]
migrated from Bugzilla [#487155](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487155)
status NEW severity _normal_ in component _other_ for _9.3.x_
Reported in version _9.2.13_ on platform _Other_
Assigned to: Project Inbox

On 2016-02-03 12:41:07 -0500, Tim Hanson wrote:

> Load testing Jetty, I noticed lots of strack traces like the below indicating monitor contention when formatting dates for the request log. It appears that the wrong method for DateCache is being used. 
> 
> Clearly the intent is that date formatting is something that would be used. However, DateCache has two methods: format() and formatNow(). The former is being used; however, it _never_ updates the cached formatted string. The latter method also formats, but it will update the cached string. 
> 
> The result is worse than not using a cached string because you are forcing monitor contention on _every_ log write.
> 
> Here is the line in question:
> https://github.com/eclipse/jetty.project/blob/SHA: ac24196b0d341534793308d585161381d5bca4ac/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractNCSARequestLog.java#L138
> 
> Here is the stack trace I see on my server:
> "dw-2945" # 2945 prio=5 os_prio=0 tid=0x00007faa5468c000 nid=0x6ab7 waiting for monitor entry [0x00007faa3b73c000]
>    java.lang.Thread.State: BLOCKED (on object monitor)
>         at org.eclipse.jetty.util.DateCache.format(DateCache.java:204)
>         - waiting to lock <0x000000070072b6d8> (a org.eclipse.jetty.util.DateCache)
>         at org.eclipse.jetty.server.AbstractNCSARequestLog.log(AbstractNCSARequestLog.java:127)
>         at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:113)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>         at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>         at org.eclipse.jetty.server.Server.handle(Server.java:499)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
>         at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
>         at java.lang.Thread.run(Thread.java:745)

**Comment by nddipiazza** [comment]
i see this a lot too.

**Comment by nddipiazza** [comment]
i have 10,000 thread pool size and 6505 threads are stuck here.

**Comment by olamy** [comment]
it looks we can definitely improve this part of the code and removing the synchronized block with using  java 1.8 DateTimeFormatter class.

**Comment by olamy** [comment]
fixed with commit https://github.com/eclipse/jetty.project/commit/0ba1d9b5a567e76596d667136be263d7720a2196
