### ISSUE TITLE
Suspect about embedded Jetty consuming a lot CPU with Logback

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#308]
migrated from Bugzilla [#485907](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485907)
status NEW severity *normal* in component *other* for *9.3.x*
Reported in version *unspecified* on platform *PC*
Assigned to: Project Inbox

Original attachment names and IDs:
- _[threaddump-1452851733242.tdump](https://bugs.eclipse.org/bugs//attachment.cgi?id=259196)_ (ID 259196)

On 2016-01-15 05:09:36 -0500, Mauro Molinari wrote:

> Created attachment 259196
> Thread dump
> 
> First of all: I'm posting here because I'm having a suspect about Jetty being the cause through Logback, but:
> - I'm not using Jetty in my Eclipse installation, so it seems like an embedded instance is started automatically I don't know exactly for what purpose
> - I'm not 100% sure the problem is in Jetty+Logback, but the thread dump seems to reveal that's the only "activity" in progress
> 
> Recently it happens that just leaving my Eclipse instance running, without doing anything (actually, I'm surfing the web, reading e-mails, etc.) at certain point I hear the CPU fan spin a lot. Looking at Task Manager, I see my Eclipse instance eating about 12-14% CPU constantly (which I guess is just a 100% busy thread of my 4-core + Hyperthreading i7 CPU).
> This goes forever and does not stop until I restart Eclipse.
> I'm attaching a thread dump, which reveals that nothing is in progress, except for a Jetty instance trying to append to a Logback log.
> 
> Any suspect?
> 
> I'm using Eclipse 4.5.1 (M20150904-0015).
> The list of "Installed Software" shows:
> 
>   Code Recommenders for Java Developers	2.3.0.v20160106-1243	org.eclipse.recommenders.rcp.feature.feature.group	Eclipse Code Recommenders
>   Code Recommenders Mylyn Integration	2.3.0.v20160106-1243	org.eclipse.recommenders.mylyn.rcp.feature.feature.group	Eclipse Code Recommenders
>   Dali Java Persistence Tools - EclipseLink JPA Support	3.4.1.v201409111648	org.eclipse.jpt.jpa.eclipselink.feature.feature.group	Eclipse Web Tools Platform
>   Dali Java Persistence Tools - JPA Diagram Editor	1.2.101.v201501141513	org.eclipse.jpt.jpadiagrameditor.feature.feature.group	Eclipse Web Tools Platform
>   Dali Java Persistence Tools - JPA Support	3.4.2.v201505291546	org.eclipse.jpt.jpa.feature.feature.group	Eclipse Web Tools Platform
>   Data Tools Platform Enablement Extender SDK	1.12.0.v201406061321-7IAB-FE9JgeWjZZhMd-z0vb1ifD4	org.eclipse.datatools.enablement.sdk.feature.feature.group	Eclipse Data Tools Platform
>   Data Tools Platform Extender SDK	1.12.0.v201406061321-7PB21FEpPZQXdcX0z-_yMM0Hfz0w	org.eclipse.datatools.sdk.feature.feature.group	Eclipse Data Tools Platform
>   Eclipse Automated Error Reporting	1.0.1.v20150913-0716	org.eclipse.epp.logging.aeri.feature.feature.group	Eclipse Packaging Project
>   Eclipse Faceted Project Framework	3.7.0.v201505072140	org.eclipse.wst.common.fproj.feature.group	Eclipse Web Tools Platform
>   Eclipse Faceted Project Framework JDT Enablement	3.6.3.v201501141810	org.eclipse.jst.common.fproj.enablement.jdt.feature.group	Eclipse Web Tools Platform
>   Eclipse Java Development Tools	3.11.1.v20150904-0015	org.eclipse.jdt.feature.group	Eclipse.org
>   Eclipse Java EE Developer Tools	3.7.0.v201505131719	org.eclipse.jst.enterprise_ui.feature.feature.group	Eclipse Web Tools Platform
>   Eclipse Java Web Developer Tools	3.7.1.v201509021802	org.eclipse.jst.web_ui.feature.feature.group	Eclipse Web Tools Platform
>   Eclipse Platform	4.5.1.M20150904-0015	org.eclipse.platform.ide	Eclipse.org
>   Eclipse Quicksearch	3.7.2.201511260840-RELEASE	org.springsource.ide.eclipse.commons.quicksearch.feature.feature.group	Pivotal Software, Inc.
>   Eclipse Web Developer Tools	3.7.1.v201509022125	org.eclipse.wst.web_ui.feature.feature.group	Eclipse Web Tools Platform
>   Eclipse XML Editors and Tools	3.7.1.v201508271605	org.eclipse.wst.xml_ui.feature.feature.group	Eclipse Web Tools Platform
>   Gradle IDE	3.7.2.201511260851-RELEASE	org.springsource.ide.eclipse.gradle.feature.feature.group	Pivotal Software, Inc.
>   Groovy Compiler 2.3 Feature	2.9.2.xx-201601121952-e45	org.codehaus.groovy23.feature.feature.group	Codehaus.org
>   Groovy Compiler 2.4 Feature	2.9.2.xx-201601121952-e45	org.codehaus.groovy24.feature.feature.group	Codehaus.org
>   Groovy-Eclipse Feature	2.9.2.xx-201601121952-e45	org.codehaus.groovy.eclipse.feature.feature.group	Codehaus.org
>   JavaHL 1.8.14 Win64 Binaries (Optional)	5.0.1.I20151028-1700	org.polarion.eclipse.team.svn.connector.javahl18.win64.feature.group	Polarion Software
>   JavaScript Development Tools	1.6.201.v201508262249	org.eclipse.wst.jsdt.feature.feature.group	Eclipse Web Tools Platform
>   JDT Core patch for Groovy-Eclipse plugin on Eclipse 4.5	2.9.2.xx-201601121952-e45	org.codehaus.groovy.jdt.patch.feature.group	Codehaus.org
>   JRebel (required)	6.3.1.RELEASE	org.zeroturnaround.eclipse.feature.feature.group	ZeroTurnaround
>   JRebel for Java EE	6.3.1.RELEASE	org.zeroturnaround.eclipse.wtp.feature.feature.group	ZeroTurnaround
>   JSF Tools	3.8.0.v201505112336	org.eclipse.jsf.feature.feature.group	Eclipse Web Tools Platform
>   JSF Tools - Tag Library Metadata (Apache Trinidad)	2.6.0.v201410101748	org.eclipse.jst.jsf.apache.trinidad.tagsupport.feature.feature.group	Eclipse Web Tools Platform
>   JSF Tools - Web Page Editor	2.7.1.v201508270443	org.eclipse.jst.webpageeditor.feature.feature.group	Eclipse Web Tools Platform
>   JST Server Adapters	3.2.400.v201503102136	org.eclipse.jst.server_adapters.feature.feature.group	Eclipse Web Tools Platform
>   JST Server Adapters Extensions	3.3.401.v201508232356	org.eclipse.jst.server_adapters.ext.feature.feature.group	Eclipse Web Tools Platform
>   JST Server UI	3.4.200.v201503102136	org.eclipse.jst.server_ui.feature.feature.group	Eclipse Web Tools Platform
>   Memory Analyzer	1.5.0.201505271423	org.eclipse.mat.feature.feature.group	Eclipse Memory Analyzer
>   Memory Analyzer (Charts) [optional]	1.5.0.201505271423	org.eclipse.mat.chart.feature.feature.group	Eclipse Memory Analyzer
>   Mylyn Builds Connector: Hudson/Jenkins	1.9.0.v20150908-1655	org.eclipse.mylyn.hudson.feature.group	Eclipse Mylyn
>   Mylyn Context Connector: Eclipse IDE	3.17.0.v20150625-2044	org.eclipse.mylyn.ide_feature.feature.group	Eclipse Mylyn
>   Mylyn Context Connector: Java Development	3.17.0.v20150828-2014	org.eclipse.mylyn.java_feature.feature.group	Eclipse Mylyn
>   Mylyn Context Connector: Team Support	3.17.0.v20150625-2044	org.eclipse.mylyn.team_feature.feature.group	Eclipse Mylyn
>   Mylyn Task List	3.17.0.v20150909-1822	org.eclipse.mylyn_feature.feature.group	Eclipse Mylyn
>   Mylyn Task-Focused Interface	3.17.0.v20150625-2044	org.eclipse.mylyn.context_feature.feature.group	Eclipse Mylyn
>   Native JavaHL 1.8 Implementation (Optional)	5.0.1.I20151028-1700	org.polarion.eclipse.team.svn.connector.javahl18.feature.group	Polarion Software
>   Oomph Dynamic Working Sets	1.2.0.v20150915-0926	org.eclipse.oomph.workingsets.feature.group	Eclipse Oomph Project
>   Oomph Preferences Management	1.2.0.v20150915-0926	org.eclipse.oomph.preferences.feature.group	Eclipse Oomph Project
>   Oomph Project Configuration	1.2.0.v20150915-0926	org.eclipse.oomph.projectconfig.feature.group	Eclipse Oomph Project
>   Optimizer for Eclipse	1.0.9	com.zeroturnaround.eclipse.optimizer.feature.feature.group	ZeroTurnaround
>   PHP Development Tools (PDT)	3.6.0.201509151953	org.eclipse.php.feature.group	Eclipse PDT
>   PHP Development Tools (PDT) Mylyn Integration	3.6.0.201509151953	org.eclipse.php.mylyn.feature.group	Eclipse PDT
>   RegexUtil Featch	1.2.4	com.ess.regexutil.feature.group	null
>   Spring IDE Core (required)	3.7.2.201511260958-RELEASE	org.springframework.ide.eclipse.feature.feature.group	Spring IDE Developers
>   Spring IDE Integration, Flex and Web Services Extension (optional)	3.7.2.201511260958-RELEASE	org.springframework.ide.eclipse.integration.feature.feature.group	Spring IDE Developers
>   Spring IDE Mylyn Integration (optional)	3.7.2.201511260958-RELEASE	org.springframework.ide.eclipse.mylyn.feature.feature.group	Spring IDE Developers
>   Spring IDE Security Extension (optional)	3.7.2.201511260958-RELEASE	org.springframework.ide.eclipse.security.feature.feature.group	Spring IDE Developers
>   Spring IDE Spring Data Support	3.7.2.201511260958-RELEASE	org.springframework.ide.eclipse.data.feature.feature.group	Spring IDE Developers
>   Subversive Revision Graph (Optional)	3.0.0.I20150529-1700	org.eclipse.team.svn.revision.graph.feature.group	Eclipse.org
>   Subversive SVN Connectors	5.0.2.I20151228-1700	org.polarion.eclipse.team.svn.connector.feature.group	Polarion Software
>   Subversive SVN Integration for the Mylyn Project (Optional)	3.0.0.I20150529-1700	org.eclipse.team.svn.mylyn.feature.group	Eclipse.org
>   Subversive SVN JDT Ignore Extensions (Optional)	3.0.0.I20150529-1700	org.eclipse.team.svn.resource.ignore.rules.jdt.feature.group	Eclipse.org
>   Subversive SVN Team Provider	3.0.1.I20150722-1700	org.eclipse.team.svn.feature.group	Eclipse.org
>   SVNKit 1.8.11 Implementation (Optional)	5.0.2.I20151228-1700	org.polarion.eclipse.team.svn.connector.svnkit18.feature.group	Polarion Software
>   Swing Designer	1.8.0.r45x201506110826	org.eclipse.wb.swing.feature.feature.group	Eclipse WindowBuilder
>   WST Server Adapters	3.2.402.v201505042029	org.eclipse.wst.server_adapters.feature.feature.group	Eclipse Web Tools Platform

**Comment by joakime** [comment]
This is not reproducible, 
Thread dump shows normal thread behavior in Jetty.

Open a fresh bug if you can show a reproducible testcase.
