### ISSUE TITLE
Do not create and use jars with "tests" classifier

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3080]
Some Jetty Maven modules create a "tests" jar using the `test-jar` goal of the Maven Jar Plugin.
These "tests" jars contain utility classes that are later reused by other modules.

Unfortunately these jars are very cumbersome to use with JPMS, as they need special command line options passed to the Maven Compiler Plugin and the Maven Surefire Plugin.
Not only, the additional JPMS command line options often require to explicitly add additional Maven dependencies (especially transitive ones) that would not be necessary otherwise, and that if missing lead to build errors that are difficult to figure out.

We should refactor the test utility classes into a separate proper Maven module, and use normal Maven test dependencies which will play well with JPMS.

**Comment by gregw** [comment]
Really?  This is a bad feature that is just perverting good software engineering and creating even more work.
Wouldn't it be better to get the maven plugins updated so that all the "special command line options" can be handled by the plugins?

**Comment by joakime** [comment]
Actually, having split jars from a maven module has always been a bad idea.
Good software engineering from a maven point of view is to have a different module, not classified artifacts.

**Comment by sbordet** [comment]
Really.

I don't think it can be done in a generic way.

How could a Maven Plugin know that Maven module `http2-client` needs to have`jetty-http` patched because it carries a `tests` jar that it's used by the tests?

That's the point of reusable code: you put it into its own artifact, rather than an attachment to something else. To avoid split jars we would need a "*.test.*" package or something alone those lines, but it's not a big deal.

**Comment by olamy** [comment]
+1

**Comment by gregw** [comment]
@sbordet has confirmed that cyclic dependencies do exist in his first attempt to split a module.  While the first examples might be easy to work around, I think we need a general solution.  So here are the ways the cyclic dependencies between `FooBar` and `FooBarTools` can be handled:
0. Do not split `FooBarTools` and just have a test artifact.  Note that this has the con that the test artifact contains both unit tests for `FooBar` and the testing tools that we want to export.
1. Have 3 modules: `FooBar`, `FooBarTools` and `FooBarTests`, with the later containing the unit  tests.   This has the con that the unit tests are far removed from the module.
2. Put the unit tests for `FooBar` into test dir of `FooBarTools`.  Less modules, but still a little removed.
3. Move classes/behaviours from `FooBar/src/tests` to `FooBar/src/main`.   Would work in many cases, but not really general and starts perverting our software design.
4. Copy test utilities so a copy is both in `FooBar/src/tests` and `FooBarTools/src/main`.  But the whole point of a test artifact is to not duplicate this code!
5. Don't use `FooBarTools` to unit test `FooBar`.  Not sure this can be done generally, but....

**Comment by gregw** [comment]
I think I like option 5.     `FooBarTools` should not be something that is used to test `FooBar`, it should be something that uses `FooBar` to test other modules.
To achieve this, there may be a little bit of code duplication between `FooBar/src/tests` and `FooBarTools/src/main`, but minimal duplication can be accepted. If the duplication is significant, then perhaps that code is a candidate to be moved from `FooBar/src/tests/` to `FooBar/src/main`.

**Comment by sbordet** [comment]
@gregw turned out that for `websocket-core` there was only one class reused for tests (`DummyCoreSession`).
The class has been refactored as `FrameHandler.CoreSession.Empty` in `websocket-core/src/main` following option 3. above - it was only one empty class.

**Comment by gregw** [comment]
So we don't need `websocket-core-tools`, but I still think we need to establish a general pattern to go for to solve this problem, which I think is to strive for 5., but use 3. or possibly 4. in limited places to make that possible.

**Comment by joakime** [comment]
This should be done for Jetty 10.

Some dependencies not yet covered...

**Seen in jetty-server and apache-jsp and test-jetty-webapp**

``` xml
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-servlet</artifactId>
      <version>${project.version}</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
```

The only usages of `<classifier>tests</classifier>` that remain should be those in use by jetty-maven-plugin's IT tests.
