### ISSUE TITLE
Restore Dump methods for backwards compatibility reasons

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3085]
In Jetty 9.4.12.v20180830 the interfaces are ...

* String	dump​()	 
* void	dump​(java.lang.Appendable out)	 
* void	dump​(java.lang.Appendable out, java.lang.String indent)	 
* static void	dump​(java.lang.Appendable out, java.lang.String indent, java.util.Collection<?>... collections)	 
* static java.lang.String	dump​(Dumpable dumpable)	 **(MISSING in 9.4.13-SNAPSHOT)**
* protected void	dumpBeans​(java.lang.Appendable out, java.lang.String indent, java.util.Collection<?>... collections)	 **(MISSING in 9.4.13-SNAPSHOT / DIFFERENT SIGNATURE?)**
* static void	dumpObject​(java.lang.Appendable out, java.lang.Object o)	 **(MISSING in 9.4.13-SNAPSHOT)**
* void	dumpStdErr​()	
* protected void	dumpThis​(java.lang.Appendable out)

In Jetty 9.4.13-SNAPSHOT we have

* String	dump() 
* void	dump(Appendable out)
* void	dump(Appendable out, String indent)
* static void	dump(Appendable out, String indent, Collection<?>... collections) **@Deprecated**. 
* protected void	dumpBeans(Appendable out, String indent, Object... items) **(NEW to 9.4.13)**
* void	dumpStdErr() 
* protected void	dumpThis(Appendable out) **@Deprecated**

**Comment by sbordet** [comment]
Methods have been restored as deprecated in 9.4.x.
Deprecated methods have been removed from 10.0.x during the merge from 9.4.x.
