### ISSUE TITLE
FastCGI request idle timeout is handled incorrectly

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#309]
migrated from Bugzilla [#484683](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484683)
status NEW severity *normal* in component *fastcgi* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Simone Bordet

On 2015-12-18 08:17:30 -0500, Simone Bordet wrote:

> FastCGI request idle timeout is controlled by HttpChannelOverFCGI.FCGIIdleTimeout.
> 
> However, calls to notIdle() are not performed on request/response events, and FCGIIdleTimeout.isOpen() returns information about the connection, not about the request.

**Comment by sbordet** [comment]
Fixed by commit 0713c17cfa9eb09078fcf497faea282bbfb952a4.
