### ISSUE TITLE
Promote WebSocket PathMappings / PathSpec to Jetty Http

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#310]
migrated from Bugzilla [#484349](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484349)
status REOPENED severity *normal* in component *other* for *9.3.x*
Reported in version *9.4.0* on platform *All*
Assigned to: Joakim Erdfelt

On 2015-12-14 13:15:23 -0500, Joakim Erdfelt wrote:

> The proposed replacement of the venerable PathMap class exist in the WebSocket server classes.
> 
> This issue is to track the promotion of those classes into /jetty-http/ for eventual use by Bug # 482042

On 2015-12-14 13:20:36 -0500, Joakim Erdfelt wrote:

> Committed to [master] SHA: dddba5b0043c7f821602b22f5ddab38a6e813309

On 2016-01-13 22:28:34 -0500, Greg Wilkins wrote:

> Joakim,
> 
> can you review commit 7925697 which contains the optimisation we discussed.

**Comment by joakime** [comment]
The optimization makes sense so far.
However, we need to review what the official order of lookups are going to be with this feature.
Considering this issue closed. (should open separate one about lookup order in mixed spec scenarios)
