### ISSUE TITLE
Support ALPN on non-Oracle OpenJDK 8 runtimes

### ISSUE THREAD

**Issue by abarsov** [eclipse/jetty.project#3100]
Hello!

To the moment every update of Oracle jdk is supported with appropriate alpn-boot jar.
The mapping is here: 
https://raw.githubusercontent.com/jetty-project/jetty-alpn/master/docs/version_mapping.properties

But there is no mapping provided for openjdk builds published by other vendors.
This make it difficult to use jetty with non-oracle openjdk 8 builds.

Recent example of such behavior is an update released by debian openjdk maintainers:
The problem was that updated package (`8_8u181-b13-2~deb9u1`) contains backported fixes from 8u191, and while `alpn-boot 8.1.12.v20180117` was compatible with  `8_8u181-b13-1~deb9u1`, it became incompatible with  `8_8u181-b13-2~deb9u1`. See details in [BND-1781](https://youtrack.jetbrains.com/issue/BND-1781).
A bit later Ubuntu maintainers published their package [8u181-b13-1ubuntu0.16.04.1](https://launchpad.net/ubuntu/+source/openjdk-8/8u181-b13-1ubuntu0.16.04.1) with the same back ports from `8u191`. And `alpn-boot 8.1.12.v20180117` became incompatible with latest Ubuntu openjdk as well (see details in [JT-50247](https://youtrack.jetbrains.com/issue/JT-50247)).

So the question is as follows:
is there any plans for Jetty to provide alpn-boot jars for other openjdk vendors? 
(I suppose in most cases that means simply supporting separate mappings from alpn-boot version to 3-rd party openjdk build numbers, and in few cases it might require a separate version of alpn-boot jar compiled against sources of 3-rd party openjdk version)

The problem is worsened by the fact that since 1 Jan 2019 Oracle will no longer provide public bug-fix updates for the java 8 (https://www.oracle.com/technetwork/java/javase/eol-135779.html), 
though such updates will be published by 3-rd party vendors, like [Azul](https://www.azul.com/eliminating-java-update-confusion/), [RedHat](https://developers.redhat.com/blog/2018/09/24/the-future-of-java-and-openjdk-updates-without-oracle-support/),  [AdoptOpenJDK](https://adoptopenjdk.net/support.html), Linux Distros...

It is a good chance that Oracle will keep contributing all updates into an open, GPL-licensed repository for the entire period that the LTS release is maintained. This way it won't be a hell of different back ports from different vendors with different source code in those classes touched by alpn-boot. I mean still there will be several updates provided by different vendors, but it is likely that all of them will be compatible with the same alpn-boot jar.

I look forward and hope Jetty maintainers will further provide alpn-boot jars for the upcoming openjdk 8 builds from 3-rd party vendors, 
otherwise it is not clear how to run Jetty on java 8 LTS free builds after 1 Jan 2019.

**Comment by sbordet** [comment]
There are no plans to provide `alpn-boot` for other OpenJDK vendors.

We will continue to provide `alpn-boot` for OpenJDK though, as new releases are pushed out (although this process is new and it's a bit unclear who and where these will be pushed).

We cannot track every vendor and every possible modification they make, so here is where the community can help.

For example, you know about Debian and Ubuntu modifications, then I think you can make a pull request to [jetty-project/jetty-alpn](https://github.com/jetty-project/jetty-alpn/) for a `debian_version_mapping.properties` file and `ubuntu_version_mapping.properties` file.

We won't be able to double test that the vendor mapping is correct (especially if it requires a support contract with the vendor), but we trust the community to post the correct information.
Sounds reasonable?

**Comment by abarsov** [comment]
I have added proposal with initial mapping for ubuntu packages.
And it seems I was wrong about debian package `8_8u181-b13-2~deb9u1`.  It looks to be incompatible with both `alpn-boot 8.1.12.v20180117` and `alpn-boot 8.1.13.v20181017`.

**Comment by sbordet** [comment]
@abarsov do you know why Debian did not push a vanilla 8u192 now that's more than 1 month old?

**Comment by abarsov** [comment]
@sbordet 
Unfortunately not, I hasn't strictly followed openjdk updates of different vendors. Though users started complaining about incompatibility, this is why I went into this problem deeper.
I think that the most safe way for me personally would be selecting most appropriate (compatible) openjdk 8 build and bundle that together with jetty into the product. Otherwise it is getting too complicated to support running jetty on all possible builds of openjdk.
But still for community that would be great to support 3-rd party vendors (at list most significant ones) since soon there will be no more free oracle jre builds for java 8 and those who by some reason can't upgrade to 11 and still would like to get security updates will have to migrate to 3-rd party openjdk 8builds.

**Comment by sbordet** [comment]
@abarsov I agree with you that if a distribution starts to backport important fixes, but does not change `java.version` so it's actualy 8u191 code, but `java.version` still shows 8u181, then it's a royal mess and I would go with a stable OpenJDK binary rather than half-backported version.

There will be free OpenJDK 8 builds from https://adoptopenjdk.net/ and from https://aws.amazon.com/corretto/.

**Comment by nthung82** [comment]
openjdk version "1.8.0_252"
OpenJDK Runtime Environment Corretto-8.252.09.2 (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM Corretto-8.252.09.2 (build 25.252-b09, mixed mode)
-------------
with java version above, it still does not work

**Comment by sbordet** [comment]
@nthung82 "it still does not work" is not helpful.

Make sure you have read this: https://webtide.com/jetty-alpn-java-8u252/.

Please open a new issue and detail _exactly_ what does not work if you still have problems after reading the information above.

**Comment by nthung82** [comment]
tks for your helping, I will create the code, and post it here
at here:
https://github.com/eclipse/jetty.project/issues/4928
I read the link you posted carefully
