### ISSUE TITLE
Jetty does not accept space in URL of request

### ISSUE THREAD

**Issue by jborik5** [eclipse/jetty.project#3107]
**Scenario:**
1. Client sends following HTTP GET request to Apache HTTPD server: `http://mydomain.com/app/my%20request`
1. Apache HTTPD server "canonizes" the request before it is proxied to Jetty. One aspect of the canonization is decoding of special characters. So the resultant request (the first line) passed to Jetty looks like: `GET /app/my request HTTP/1.1`.
1. Jetty responds with HTTP code `400` and error message `Illegal character SPACE=' '`

I know that from Jetty's POV this is invalid request, but it is quite common scenario to use Apache HTTPD as proxy for Jetty.
It is worth to mention that Apache server offers [nocanon](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) flag for disabling the canonization of requests.

> The optional nocanon keyword suppresses this and passes the URL path "raw" to the backend. Note that this keyword may affect the security of your backend, as it removes the normal limited protection against URL-based attacks provided by the proxy.

I believe using of `nocanon` is viable option for new projects. However we are migrating from Weblogic to Jetty and there is a risk that there is a code in our application which expects canonized requests.
Additionally we want to do the migration gradually so Jetty and Weblogic must work side by side. I know that this is not issue for Jetty, I just describe our scenario.

Weblogic doesn't accept spaces in URL by default, but it offers `URIContainsSpace` parameter which allows it.

Would it make sense for you to support such scenario? Is it acceptable to add an option which would switch Jetty to more lenient mode and would accept raw spaces in URL of requests?

Thanks in advance for any feedback on this issue.

**Comment by joakime** [comment]
It is a screamingly bad security issue to accept arbitrary whitespace in a request line or request headers.
Allowing for all sorts of shenanigans surrounding request hijacking and request poisoning.

Then there is also the Servlet security requirements that we MUST perform url-pattern matching against the raw request uri, not the canonized / normalize / decoded uri.
Thus, when working with _any_ Servlet container, you MUST have `nocanon` enabled.

**Comment by gregw** [comment]
I agree with @joakime , that we simply cannot risk security problems by accepting such malformed request lines.

So if you wish to do your migration gradually, then I suggest running `nocanon` to jetty but then using a `RequestCustomizer` to expand out the URL before giving it to the servlet engine.   Note however that users of the Servlet API will only see the canonical URI anyway, so I think the risk of having behaviour changes is very very small.

If you really REALLY can't do it any other way, then that's the beauty of open source!  You can make your own build with a parser that does accept spaces in the URI.   This should be simple enough to do yourselves or is exactly the kind of thing we do for our commercial support clients.    So I'm going to close this for now as we will not "fix" in a general release.   But please do ask questions about how to achieve either of the above options,  either on the user forums or directly if you want commercial support.
