### ISSUE TITLE
Result of calls to String.replace is discarded without use in MongoSessionManager.createContextId

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#311]
migrated from Bugzilla [#483506](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483506)
status ASSIGNED severity *normal* in component *other* for *9.3.x*
Reported in version *9.4.0* on platform *PC*
Assigned to: Jan Bartel

On 2015-12-02 13:27:29 -0500, Alex Henrie wrote:

> An operation on an immutable object won't change the object itself.
> 
> Identified with `pmd -d . -R java-unnecessary`
> 
> https://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-nosql/src/main/java/org/eclipse/jetty/nosql/mongodb/MongoSessionManager.java?h=jetty-9.3.6.v20151106#n731

**Comment by janbartel** [comment]
This is fixed in jetty-9.4
