### ISSUE TITLE
REQUEST_URI should retain original query string in case of rewrites

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#312]
migrated from Bugzilla [#482846](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482846)
status NEW severity *enhancement* in component *fastcgi* for *9.3.x*
Reported in version *9.3.6* on platform *PC*
Assigned to: Simone Bordet

On 2015-11-23 11:27:56 -0500, Simone Bordet wrote:

> Related to bug # 479378, which made possible to specify an attribute for the original request URI in case of rewrites.
> 
> What was missing was that the original query was not tracked.
> Bug # 482173 solved the tracking of the original query in RewriteHandler, so this bug is about making FastCGIProxyServlet aware of this new original query attribute and use it.

**Comment by joakime** [comment]
Commit cfca16f64d73ba140ae04ca773e11a4bb2b040de added ability to track the request uri

**Comment by sbordet** [comment]
While the feature was added in the rewrite code, this issue is about exposing it in `FastCGIProxyServlet`.
