### ISSUE TITLE
Is Jetty 8.1.22.v20160922 a blessed-release?

### ISSUE THREAD

**Issue by javabrett** [eclipse/jetty.project#3122]
Just wanted to check on the status of `8.1.22.v20160922` - whether it is a blessed/completed release.  I'm seeing these inconsistencies:

- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/8.1.22.v20160922/ exists
- https://search.maven.org/artifact/org.eclipse.jetty/jetty-distribution/8.1.22.v20160922/pom exists

... however:

- https://www.eclipse.org/jetty/previousversions.html lists `8.1.21.v20160908` as current/latest for the 8.1 branch
- There's no tag for this release - newest in Git is `jetty-8.1.21.v20160908`

Is this `8.1.22.v20160922` a blessed release, and if so, can it gain a Git tag and a mention on previousversions?

**Comment by joakime** [comment]
### NOTE: All Jetty 8.x releases are now EOL (End of Life)
See: https://www.eclipse.org/lists/jetty-announce/msg00069.html

http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/8.1.22.v20160922/ <-- this is most definitely released.

Checking the git blame log, it looks like the 8.1.22.v20160922 release was commit f3a0bc90f8431686f0bac2c92c94bc47255c25dc
Seeing as we want nobody using Jetty 8.x, we will not be recreating the tag (as said tag will then show up as new in various reporting and tooling).

The diff between jetty-8.1.21.v20160908 and the 8.1.22.v20160922 release can be found at ...
https://github.com/eclipse/jetty.project/compare/jetty-8.1.21.v20160908...f3a0bc90f8431686f0bac2c92c94bc47255c25dc

It consists of a pom.xml change to set source/target on the compiler to Java 1.6, no other changes.

**Comment by joakime** [comment]
For the record, the last announced version of Jetty 8.x was version 8.1.17.v20150415

https://www.eclipse.org/lists/jetty-announce/msg00078.html

RedHat software sponsored that post EOL (End of Life) release to fix some issues they needed resolved.

**Comment by joakime** [comment]
Closing Issue.
Backdated tag created.
https://github.com/eclipse/jetty.project/releases/tag/jetty-8.1.22.v20160922

**Comment by javabrett** [comment]
Thanks @joakime, better that this is now tagged. Only the previousversions page is out of date now, but that is of least importance and the version table might even auto update with next doc build. At least I couldn't find the source for that page.
