### ISSUE TITLE
javax-websocket-common pom.xml is wrong

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3129]
This is wrong, there is no such package as org.eclipse.jetty.websocket.jsr356.common:
             

>    <Export-Package>     org.eclipse.jetty.websocket.jsr356.common.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}"
>                 </Export-Package>

**Comment by gregw** [comment]
I'm struggling with all the different directory names vs maven names vs package names.   I'm thinking we need to just rename everything to the same sensible set of names, else this is going to be confusing for all time.  Jetty-10 is the time/place to make such changes

**Comment by joakime** [comment]
The naming syntax currently ...

`<api>-<role>-<artifact>`

where ...

`api` is one of `javax` or `jetty` (or in the future `reactive`)
`role` is one of `client` or `server`
`artifact` is optional, but commonly used to indicate the type of artifact, such as one of `-api` or `-common` or `-impl`

Then we have the oddballs `websocket-core`, which should follow the syntax `websocket-core-<role>-<artifact>`
Meaning we would have ...

`websocket-core-client`
`websocket-core-server`
`websocket-core`

**Comment by joakime** [comment]
directory names are the maven module name.
the maven module name should match the maven artifactId.

package names cannot change wholesale without breaking lots of users of our APIs.

The syntax could be ...
`org.eclipse.jetty.websocket.<api>` (where `api` is one of: `core`, or `javax`, or `jetty`, or even `reactive`)
with child packages indicating `<role>` (such as `api`, or `client`, or `server`)
"common classes" would just be at the top level of the `org.eclipse.jetty.websocket.<api>`

**Comment by joakime** [comment]
Note that the history of the package name `org.eclipse.jetty.websocket.jsr356`, is that it was chosen over `org.eclipse.jetty.websocket.javax` name because of `WebSocketClassLoader` behaviors that treated `javax` in a package name uniquely/differently (something that is no longer true)

There's no API breakage in Jetty 10.0.x if we wanted to change `org.eclipse.jetty.websocket.jsr356` package name (its all internal implementation to the `javax.websocket` API anyway).

So perhaps one of the following ?

1. `org.eclipse.jetty.websocket.javax`
2. `org.eclipse.jetty.websocket.java`
3. `org.eclipse.jetty.websocket.jakarta`
4. `org.eclipse.jetty.websocket.ee4j`

**Comment by gregw** [comment]
I think moving to 10 is a twice a decade chance to break a few APIs to improve usability.
I think jsr356 is definitely wrong into the future, but then so might javax be?  Although I think the current policy is to keep it for current APIs but to use just `java` for new APIs

So I think a directory `<api>-websocket-<role>` should contain package `org.eclipse.jetty.websocket.<api>.<role>`
Where `api` can be `null`, `jetty`, `javax`, `reactive` etc.  null being our internal code with no fixed api.
The `role` is a little dependent on the `api`, so the null api can have roles of `core`, `servlet` etc. but `role` will mostly be `api`, `client`, `server`, `tools`, etc.

But I also think we can have some exceptions and I think we can go with:

 directory & maven | package | Comment
------------ | ----------- | --------
websocket-core | org.eclipse.jetty.websocket.core |
websocket-servlet |  org.eclipse.jetty.websocket.servlet |
websocket-tools | org.eclipse.jetty.websocket.tools | Doesn't yet exist, but I think it should
jetty-websocket-api | org.eclipse.jetty.websocket.api |
jetty-websocket-common | org.eclipse.jetty.websocket.common  |
jetty-websocket-client |  org.eclipse.jetty.websocket.client |
jetty-websocket-server | org.eclipse.jetty.websocket.server  |
jetty-websocket-tests | org.eclipse.jetty.websocket.* | needs to be recreated, but no artifact published
javax-websocket-common |  org.eclipse.jetty.websocket.javax.common |
javax-websocket-server |  org.eclipse.jetty.websocket.javax.server |
javax-websocket-client | org.eclipse.jetty.websocket.javax.client  |
javax-websocket-tests |  org.eclipse.jetty.websocket.javax.* |
reactive-websocket-* |  org.eclipse.jetty.websocket.reactive.* |

Strictly speaking, the `jetty-websocket-*` modules should have packages of `org.eclipse.jetty.websocket.jetty.client`, but breaking the pattern keeps backwards compatibility and is not too much of a travesty

**Comment by gregw** [comment]
@lachlan-roberts can you do a PR for the renaming suggested above

**Comment by joakime** [comment]
Completed by @greg in PR #3198
