### ISSUE TITLE
Upgrade to jetty 9.4.12 from 8.1.16 causing logout

### ISSUE THREAD

**Issue by smanikim** [eclipse/jetty.project#3143]
We were on 8.1.16.v20140903 and using custom session storage. For 9.4.12, we followed docs for storing session Data  and written backward compatible transcoder. When we upgrade to 9.4.12, we get "NO HTTP Session found" and logout is being called.

I am not getting any log line which says it tried to decode earlier session to find sessionData. 

Any leads

**Comment by joakime** [comment]
> Reminder: Jetty versioning since 1995 is `<servlet_support>.<major_version>.<minor_version>`

We need more information on your "custom session storage" as the Session handling setup has drastically changed in the 5 major versions of Jetty you just upgraded through.

**Comment by smanikim** [comment]
I had issue with sessionStorage. Closing this one
