### ISSUE TITLE
Bring back packageRoot parameter in jetty-jspc-maven-plugin

### ISSUE THREAD

**Issue by akurtakov** [eclipse/jetty.project#3156]
Being able to precompile jsp files in predefined java package name instead of the default jasper one is quite useful for people using minimal jetty and providing custom jsp container in it (like Eclipse Platform does). This parameter was removed in 9.1.0 for some reason.

**Comment by janbartel** [comment]
Thanks

**Comment by akurtakov** [comment]
Thanks for the fast responses.
