### ISSUE TITLE
WebSocket permessage-deflate RSV1 validity check

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3159]
A problem with our `permessage-deflate` implementation.

You get the following frames ...

1. TEXT (fin==false, rsv1==true) - payload compressed data
2. CONTINUATION (fin==false, rsv1==true) - payload compressed data
3. CONTINUATION (fin==false, **rsv1==FALSE**) - payload **not** compressed.
4. CONTINUATION (fin==true, rsv1==true) - final payload compressed data

The 3rd frame, if received, should trigger a `ProtocolException` (status code 1002) and close the connection.

Our implementation currently concats the 3rd frame to the uncompressed data.
This is in violation of the spirit of RFC 7692 and we should not allow this.

**Comment by joakime** [comment]
@lachlan-roberts we need to verify that the implementation on `jetty-10.0.x` performs this rsv1 check (and throws a ProtocolException)

**Comment by lachlan-roberts** [comment]
@joakime The RFC seems to indicate that RSV1 should only be set on the first frame of a fragmented message.

https://tools.ietf.org/html/rfc7692#section-9.2
```
The "Per-Message Compressed" framing header bit is used on the first
   fragment of data messages to indicate whether the payload of the
   message is compressed by the PMCE or not.
```

**Comment by gregw** [comment]
@lachlan-roberts so on subsequent fragments should we ignore RSV1 or should we do a 1002 if it is set?     Can you check what browsers are currently doing or is there anything else in the RFC that suggests what we should do?
Eitherway, our implementation is wrong and the 3rd frame in @joakime 's example should be handled as compressed data.... and perhaps we should 1002 on frames 2 and 4?

**Comment by lachlan-roberts** [comment]
I tested this in my browser and when chrome generates continuation frames using permessage-deflate it only sets the RSV bit on the first frame like it is supposed to.

Our current implementation will ignore the `RSV1` bit if it is set on a `CONTINUATION` frame.

**Comment by joakime** [comment]
Per https://tools.ietf.org/html/rfc7692#page-11

```
   An endpoint MUST NOT set the "Per-Message Compressed" bit of control
   frames and non-first fragments of a data message.  An endpoint
   receiving such a frame MUST _Fail the WebSocket Connection_.
```

**Comment by joakime** [comment]
Opened PR #3401

**Comment by joakime** [comment]
Working on `jetty-9.4.x` version of this issue in branch `jetty-9.4.x-3401-websocket-permessage-deflate-rsv1`

**Comment by joakime** [comment]
Opened PR #3418 (for `jetty-9.4.x`)

**Comment by lachlan-roberts** [comment]
This has been fixed in #3418 and #3401

**Comment by lachlan-roberts** [comment]
The autobahn-testsuite sends continuation frames with the RSV1 bit set and expects it to work. Giving a `ProtocolException` for this is causing us to fail many of the autobahn tests.

All the tests pass if we give a warning instead of `ProtocolException`.

**Comment by gregw** [comment]
Perhaps make it configurable? plus raise an issue against autobahn to see what they have to say

**Comment by lachlan-roberts** [comment]
Doesn't look like its autobahn sending the RSV1 bit on continuation frame but it is set by the parser when a TEXT or BINARY frame is auto-fragmented.

**Comment by gregw** [comment]
@lachlan-roberts Ah that makes sense.   I guess when auto fragmenting we have to decide do we copy the RSV bits or not.....  Is there any way to know in general if a RSV should be per message or per frame?
Perhaps the extension could set something on the extension stack so you can ask if it is per message or per frame and then duplicate or not accordingly.... or perhaps we just never duplicate until we have an extension that needs it?
