### ISSUE TITLE
add chm mime mapping to mime.properties

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#316]
migrated from Bugzilla [#475515](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475515)
status ASSIGNED severity *normal* in component *other* for *9.2.x*
Reported in version *9.2.9* on platform *PC*
Assigned to: Project Inbox

On 2015-08-20 12:48:33 -0400, Stefan Vigerske wrote:

> We are running a documentation using an Eclipse Help System and had it including a .CHM (MS Compressed HTML Help format) file. Jetty was serving this file as plain/text, so the webbrowser tried to show it as such.
> 
> We could fix this by adding
> 
> chm=application/chm
> 
> to org/eclipse/jetty/http/mime.properties
> in plugins/org.eclipse.jetty.http_9.2.9.v20150224.jar
> 
> Would be nice if this change could make it into the official jetty system.

On 2015-08-20 15:08:02 -0400, Simone Bordet wrote:

> I looked around, and "application/chm" does not seem to be a registered mime type.
> 
> I could find "application/x-chm", but the registered one seems to be "application/vnd.ms-htmlhelp" (from http://www.freeformatter.com/mime-types-list.html, see also http://www.iana.org/assignments/media-types/application/vnd.ms-htmlhelp).
> 
> If you have an official reference of the right mime type, please comment on this issue.

On 2015-08-21 05:49:22 -0400, Stefan Vigerske wrote:

> I don't have an offical reference, but application/vnd.ms-htmlhelp sounds very good.

**Comment by joakime** [comment]
Added in jetty-9.2.x
