### ISSUE TITLE
Review javax-websocket-server tests

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3165]
There is only a single unit test in javax-websocket-server, yet about 10 classes.  I suspect most of those classes are not used.  Please review and cleanup.

**Comment by lachlan-roberts** [comment]
@gregw can this be closed

**Comment by lachlan-roberts** [comment]
There is now `WebSocketServerExamplesTest` which runs and tests all of the example classes. The remaining classes for `JsrBrowserDebugTool` are important for debugging.
