### ISSUE TITLE
Run of autobahn websocket tests on CI

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3166]
We need a CI mechanism to frequently run the autobahn test suit on websocket core, javax and jetty APIs

**Comment by joakime** [comment]
See http://normanmaurer.github.io/autobahntestsuite-maven-plugin/

**Comment by olamy** [comment]
9.4.x or 10.0.x?

**Comment by joakime** [comment]
@olamy start with Jetty 10.x - since @gregw mentioned "core" which is new to Jetty 10.x

**Comment by olamy** [comment]
done in 10.0.x

**Comment by olamy** [comment]
currently the plugin http://normanmaurer.github.io/autobahntestsuite-maven-plugin/ is failing the build in case of failed test. We probably don't want this but only an unstable build and report of failure.
Furthermore the tests are not up2date and the plugin is not really maintained...
As the plugin is Apache license I will create a fork and make the updates. If the changes are not merged I can simply make a fork using our own groupId.

**Comment by sbordet** [comment]
@olamy don't fork it. @normanmaurer is usually responsive and we have collaborated in the past (we use his stuff, he uses our stuff).

**Comment by normanmaurer** [comment]
@olamy the plugin is maintained there was just not much to do in the last years ;) I am happy to review PRs if you have any and cut a new release if needed.

**Comment by normanmaurer** [comment]
@olamy @sbordet also I just did a release last week ;)

**Comment by olamy** [comment]
@normanmaurer ok thanks that's great. I will test the last release. We had some differences between using the plugin and running testsuite via python cli. I'd like to have something similar to `-Dmaven.test.failure.ignore=true` so when using Jenkins the build is marked as Unstable and we can look at reports. Yup I will make a pr.

**Comment by olamy** [comment]
merged in jetty-10.0.x
