### ISSUE TITLE
SNI fetching only the first certificate

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#317]
migrated from Bugzilla [#475005](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475005)
status ASSIGNED severity *normal* in component *other* for *9.3.x*
Reported in version *9.3.2* on platform *PC*
Assigned to: Greg Wilkins

On 2015-08-14 17:50:23 -0400, Poornima Iyer wrote:

> Tried SNI to fetch the appropriate certificate with default keystore as well as the my keystore, it fetches only the first certificate. I have illustrated the steps that I did for each case.
> 
> Using Jetty 9.3.2 Distribution
> Case 1: With my keystore
> =============================
> Set up the keystore with 2 certificates.
> 
> EMAILADDRESS=company@company.com, CN=company.com, OU=Eng, O=company, L=San Francisco, ST=California, C=US
> 
> EMAILADDRESS=admin@apakau.com, CN=apakau.com, OU=Engineering, O="Apakau, Inc.", L=Santa Clara, ST=CA, C=US
> 
> Changed the jetty-ssl-context.xml to the following:
> <Configure id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
>   <Set name="KeyStorePath"><Property name="jetty.base" default="." />/<Property name="jetty.sslContext.keyStorePath" deprecated="jetty.keystore" default="etc/mykeystore" /></Set>
>   <Set name="KeyStorePassword"><Property name="jetty.sslContext.keyStorePassword" deprecated="jetty.keystore.password" default="OBF:<generated password>"/></Set>
>   <Set name="KeyStoreType"><Property name="jetty.sslContext.keyStoreType" default="JKS"/></Set>
>   <Set name="KeyStoreProvider"><Property name="jetty.sslContext.keyStoreProvider"/></Set>
>   <Set name="KeyManagerPassword"><Property name="jetty.sslContext.keyManagerPassword" deprecated="jetty.keymanager.password" default="OBF:<generated password>"/></Set>
>   <Set name="TrustStorePath"><Property name="jetty.base" default="." />/<Property name="jetty.sslContext.trustStorePath" deprecated="jetty.truststore" default="etc/mykeystore"/></Set>
>   <Set name="TrustStorePassword"><Property name="jetty.sslContext.trustStorePassword" deprecated="jetty.truststore.password" default="OBF:<generated password>"/></Set>
>   <Set name="TrustStoreType"><Property name="jetty.sslContext.trustStoreType" default="JKS"/></Set>
>   <Set name="TrustStoreProvider"><Property name="jetty.sslContext.trustStoreProvider"/></Set>
>   <Set name="EndpointIdentificationAlgorithm"></Set>
>   <Set name="NeedClientAuth"><Property name="jetty.sslContext.needClientAuth" deprecated="jetty.ssl.needClientAuth" default="false"/></Set>
>   <Set name="WantClientAuth"><Property name="jetty.sslContext.wantClientAuth" deprecated="jetty.ssl.wantClientAuth" default="false"/></Set>
> <Set name="EndpointIdentificationAlgorithm">HTTPS</Set>
>   <Set name="ExcludeCipherSuites">
>    <Array type="String">
>     <Item>SSL_RSA_WITH_DES_CBC_SHA</Item>
>     <Item>SSL_DHE_RSA_WITH_DES_CBC_SHA</Item>
>     <Item>SSL_DHE_DSS_WITH_DES_CBC_SHA</Item>
>     <Item>SSL_RSA_EXPORT_WITH_RC4_40_MD5</Item>
>     <Item>SSL_RSA_EXPORT_WITH_DES40_CBC_SHA</Item>
>     <Item>SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA</Item>
>     <Item>SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA</Item>
>    </Array>
>   </Set>
>   <Set name="useCipherSuitesOrder"><Property name="jetty.sslContext.useCipherSuitesOrder" default="true"/></Set>
> </Configure>
> 
> ------------------------------
> 
> But on testing with the following command :
> openssl s_client -connect apakau.com:8443 -servername "apakau.com"
> 
> I get only the first certificate "company.com".
> 
> Case 2: Default Keystore
> ============================
> With the default keystore also, when I try the following command :
> openssl s_client -connect company.com:8443 -servername "Jetty Server"
> 
> I get only the first certificate.

On 2015-08-20 07:36:12 -0400, Greg Wilkins wrote:

> Can you run with -Dorg.eclipse.jetty.util.ssl.LEVEL=DEBUG as that will tell us a lot more about what is happening.
> 
> Also note that we do test this with the SniSslConnectionFactoryTest unit test, so it would be great if you could modify that test harness to reproduce your problem.

On 2015-09-17 22:42:20 -0400, Greg Wilkins wrote:

> more info required

On 2015-09-24 03:29:06 -0400, Greg Wilkins wrote:

> Reducing priority until information for reproduction provided

On 2015-09-29 14:40:43 -0400, Poornima Iyer wrote:

> (In reply to Greg Wilkins from comment # 3)
> > Reducing priority until information for reproduction provided
> 
> This bug is resolved but there is another related bug. But I have raised another bug for that.

**Comment by joakime** [comment]
Closing as resolved per final comment from Greg.
