### ISSUE TITLE
Cookie store per request

### ISSUE THREAD

**Issue by alamothe** [eclipse/jetty.project#3174]
Is it possible to set cookie store per request (as opposed to per client instance)? Would you consider adding such feature?

**Comment by joakime** [comment]
Wouldn't this be functionally identical to having no CookieStore? (or null CookieStore?)

Can you explain what you are trying to do?

**Comment by alamothe** [comment]
For each request, I want to be able to provide cookie store to use. Let's say it's a multi-user system, and each user should have a separate cookie store (for security purposes), but they should share client instance.

**Comment by alamothe** [comment]
Thank you for your reply 😺

**Comment by sbordet** [comment]
@alamothe on `HttpClient` currently you cannot specify a `CookieStore` per request. However, `HttpClient` would also need to separate the response cookies per user, a feature that is entirely application dependent.

I guess your best option is to use `HttpCookieStore.Empty` on `HttpClient`, and then intercept response cookie headers and store them per user. Then use `Request.cookie()` with the per-user cookies.

**Comment by sbordet** [comment]
Closing as solution was given to the OP.
