### ISSUE TITLE
BufferingResponseListener does not clear buffer in onHeaders

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3178]
reported in jetty-user:
```

I run a custom WebSocketServlet for Jetty, which sends short text push notifications (for an async mobile and desktop word game) to many platforms (Facebook, Vk.com, Mail.ru, Ok.ru also Firebase and Amazon messaging) using a Jetty HttpClient instance:

public class MyServlet extends WebSocketServlet {
    private final SslContextFactory mSslFactory = new SslContextFactory();
    private final HttpClient mHttpClient = new HttpClient(mSslFactory);

    @Override
    public void init() throws ServletException {
        super.init();

        try {
            mHttpClient.start();
        } catch (Exception ex) {
            throw new ServletException(ex);
        }

        mFcm      = new Fcm(mHttpClient);    // Firebase
        mAdm      = new Adm(mHttpClient);    // Amazon
        mApns     = new Apns(mHttpClient);   // Apple
        mFacebook = new Facebook(mHttpClient);
        mMailru   = new Mailru(mHttpClient);
        mOk       = new Ok(mHttpClient);
        mVk       = new Vk(mHttpClient);
    }

This has worked very good for the past year (thank you!), but since I have recently upgraded my WAR-file to use Jetty 9.4.14.v20181114 the trouble has begun -

public class Facebook {
    private final static String APP_ID      = "XXXXX";
    private final static String APP_SECRET  = "XXXXX";
    private final static String MESSAGE_URL = "https://graph.facebook.com/%s/notifications?" +
            // the app access token is: "app id | app secret"
            "access_token=%s%%7C%s" +
            "&template=%s";

    private final HttpClient mHttpClient;

    public Facebook(HttpClient httpClient) {
        mHttpClient = httpClient;
    }

    private final BufferingResponseListener mMessageListener = new BufferingResponseListener() {
        @Override
        public void onComplete(Result result) {
            if (!result.isSucceeded()) {
                LOG.warn("facebook failure: {}", result.getFailure());
                return;
            }

            try {
                // THE jsonStr SUDDENLY CONTAINS PREVIOUS CONTENT!
                String jsonStr = getContentAsString(StandardCharsets.UTF_8);
                LOG.info("facebook success: {}", jsonStr);
            } catch (Exception ex) {
                LOG.warn("facebook exception: ", ex);
            }
        }
    };

    public void postMessage(int uid, String sid, String body) {
        String url = String.format(MESSAGE_URL, sid, APP_ID, APP_SECRET, UrlEncoded.encodeString(body));
        mHttpClient.POST(url).send(mMessageListener);
    }
}

Suddenly the getContentAsString method called for successful HttpClient invocations started to deliver the strings, which were fetched previously - prepended to the the actual result string.

What could it be please, is it some changed BufferingResponseListener behaviour or maybe some non-obvious Java quirk?

```

**Comment by gregw** [comment]
@sbordet Looks like a recent change in BufferingResponseListener no longer allocates a new buffer in onHeaders.  Is this intended?  Perhaps we should just clean any buffer that is allocated?

**Comment by sbordet** [comment]
@gregw `BufferingResponseListener` was never intended to be reusable.
It was just a mere coincidence that it was working for the OP; while the buffer was reallocated in `onHeaders()` there was no guarantee that `encoding` and `mediaType` were reset because the original intent of this class was to not be reusable.

**Comment by gregw** [comment]
@sbordet It may not have been intended to be reused, but it was reusable and worked as reusable.

I can't see anything in the Listener contracts that say listeners can't be reused, even potentially simultaneously on multiple requests.  So reusability is an aspect of the individual utility listeners and thus at the very least we need javadoc to say if they are intended to be reusable or not.  Better yet, we should have an abstract base classes for:
 + ConcurrentListener - allows reuse and concurrent usage
 + ReusableListener - allows reuse, but throws ISE if onHeaders is called a second time before onComplete
 + SingleUseListener - throws ISE if onHeaders is called a second time.

Then once we clearly indicate which utilities listeners are reusable, it would be easy to make BufferingResponseListener extend either ReusableListener or SingleUseListener

**Comment by sbordet** [comment]
@gregw it was never reusable. Fields `encoding` and `mediaType` were never reset.
You may have been lucky that you were getting the same content type for all the responses that were reusing it, but that was not the intention.

I am not keen to introduce a class hierarchy for classes that are instantiated and controlled by applications.

`BufferingResponseListener` cannot have a lifecycle that is controlled by the implementation - an application can keep a reference to it, and call `getContent()` way after the response is completed, hence it cannot be reset by the implementation.

Giving an explicit API to reset it may be a solution, but I don't see any benefit for the added complexity and maintenance burden.

**Comment by gregw** [comment]
@sbordet then at the very least, the javadoc needs to be updated
