### ISSUE TITLE
LDAPLoginModule does not support obfuscated _bindPassword

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#318]
migrated from Bugzilla [#472676](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472676)
status NEW severity _normal_ in component _other_ for _9.3.x_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-07-14 21:53:53 -0400, Lin Yan wrote:

> When use the {OBF} style password generated using Password util for bindPassword, the LDAPLoginModule simply pass the obfuscated password to LDAP server for authentication.

**Comment by gregw** [comment]
will not implement
