### ISSUE TITLE
Getting 200 code when the Transfer-Encoding header have any fake value

### ISSUE THREAD

**Issue by naddame** [eclipse/jetty.project#3188]
We have experienced a problem on some requests that use Transfer-Encoding header with any fake value when we upgraded the version of jetty to 9.4.14.v20181114. The expected status code is 201 but returned by jetty 200.

Ok if latest versions of jetty expects a regular value for the header Transfer-Encoding. But if (a fake value is passed) the status code should be equal or higher than 400 instead of 200 status code.

<< In our case we use a fake value just to force a non use of chunk mode >>

No problem detected with  jetty version 9.4.6.v20170531 as we expect a response with status code 201.

In access log we can see the log of this request with status code 200, but our internal filters and services are never reached.

After removing the header  Transfer-Encoding the expected status is returned.

To reproduce this bug, you have just to CURL with Transfer-Encoding : nochunk header.

The debug mode do not show any interesting information about this bug

**Comment by joakime** [comment]
Is this in reference to Jetty HttpClient use of `Transfer-Encoding` for requests?
Or the Jetty Server use of `Transfer-Encoding` for responses?

**Comment by gregw** [comment]
@naddame I really don't understand what you are trying to do here? The `Transfer-Encoding` set on a request has nothing to do with any `Transfer-Encoding` used on the response, thus it will not affect if the response is chunked or not.
I also don't understand why you would get a 201 response?  That is a response for a PUT method, for which jetty does not provide any handling unless you install the `PutFilter`. What do you think generates the 201?  What method are you using? Does the request have content?

Finally, we only check `Transfer-Encoding` for chunking.  In fact, looking at the quotes from 7230 from @joakime, I realise that we are too relaxed.  We only send a 400 response if there is a sequence of transfer encodings that includes `chunked` as not the last element in the list.     For requests, we should 400 if there is a transfer encoding and chunked is not last.

**Comment by naddame** [comment]
@joakime thank you for this details.

Sorry, i haven't a time to investigate more in depth. But I tried today to reproduce this bug.

I note that with CURL command the bug is not reproduced.

But using ansible-playbook uri tasks (The same request but using ansible), the response in ansible is:
 [Error 400: Transfer-Encoding and Content-Length"] 
AND the line in access-log of the jetty server
`127.0.0.1 - - 11/Dec/2018:16:55:17 +0100 "POST /admin-external/v1/formats HTTP/1.1" 200 0 "-" "-" 0 - - -` => We have status code 200.

This issue was opened because after experienced ansible-playbook request and not CURL request.

**Analyse:**
I think that ansible reject the request with  [Error 400: Transfer-Encoding and Content-Length"]  this match what you said.

And the status code 200 in access log of the jetty server, is explained by the SSL nature of the connection (I use https). First try to establish the SSL connection => status code 200. Then ansible reject the request.

@gregw Just for detail, in our case, 201 status code is returned as a response for POST method when the application successfully create any given entity.

Thanks you, this issue can now be closed
