### ISSUE TITLE
dropping CONTENT-LENGTH

### ISSUE THREAD

**Issue by Devmond** [eclipse/jetty.project#3189]
In
org/eclipse/jetty/proxy/AsyncMiddleManServlet.java

there is this line:
proxyRequest.header(HttpHeader.CONTENT_LENGTH, null);

ie dropping the content length header...I am using the proxy to go forward to an origin that I don't control and that origin requires the Content-Length header be present for POST requests.

Is the stripping of the Content-Length header required for the proxy to work properly?

**Comment by sbordet** [comment]
That line is nested inside `if` statements that control whether there is enough information to proxy the request content with a known content length.
When that line executes, the content length is unknown, so the only solution is to drop the header.

If you explain in detail your case and your transformations, perhaps we can suggest a way to retain the content length header.

**Comment by Devmond** [comment]
Thanks @sbordet 

I ended up overriding sendProxyRequest and reinserting the original content length, it is working so far :)

**Comment by sbordet** [comment]
Closing the issue then. Feel free to reopen if you have problems.
