### ISSUE TITLE
Timeouts in BlockheadClient.readFrames()

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#319]
migrated from Bugzilla [#472407](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472407)
status NEW severity _normal_ in component _build_ for _9.3.x_
Reported in version _unspecified_ on platform _PC_
Assigned to: Jesse McConnell

Original attachment names and IDs:
- _[jetty_install_3.out](https://bugs.eclipse.org/bugs//attachment.cgi?id=255126)_ (ID 255126)

On 2015-07-10 18:54:45 -0400, Bill Ross wrote:

> Created attachment 255126
> first saved build output
> 
> These tests failed in various build attempts on the current tree over the last week. Commenting them out led to a successful build.
> 
> --- first param = 1
> 
> WebSocketCloseTest.testFastClose:172
> EventQueue<WebSocketFrame> frames = client.readFrames(1,1,TimeUnit.SECONDS);
> 
> WebSocketCloseTest.testFastFail:204 
> EventQueue<WebSocketFrame> frames = client.readFrames(1,1,TimeUnit.SECONDS);
> 
> TooFastClientTest.testUpgradeWithLargeFrame:168
> EventQueue<WebSocketFrame> frames = client.readFrames(1,1,TimeUnit.SECONDS);
> 
> MisbehavingClassTest.testAnnotatedRuntimeOnConnect:115
> EventQueue<WebSocketFrame> frames = client.readFrames(1,1,TimeUnit.SECONDS);
> 
> --- first param = 2
> 
> TooFastClientTest.testUpgradeWithSmallFrames:110 
> EventQueue<WebSocketFrame> frames = client.readFrames(2,1,TimeUnit.SECONDS);
> ---
> 
> Here is the error log for the last case:
> 
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.059 sec <<< FA
> ILURE! - in org.eclipse.jetty.websocket.server.TooFastClientTest
> testUpgradeWithSmallFrames(org.eclipse.jetty.websocket.server.TooFastClientTest)
>   Time elapsed: 1.032 sec  <<< ERROR!
> java.util.concurrent.TimeoutException: Timeout waiting for 2 events (found 0)
>         at org.eclipse.jetty.toolchain.test.EventQueue.awaitEventCount(EventQueu
> e.java:71)
>         at org.eclipse.jetty.websocket.common.test.BlockheadClient.readFrames(Bl
> ockheadClient.java:596)
>         at org.eclipse.jetty.websocket.server.TooFastClientTest.testUpgradeWithS
> mallFrames(TooFastClientTest.java:110)

**Comment by joakime** [comment]
Need to overhaul the BlockheadClient, i have some plans, but they are low priority.

**Comment by sbordet** [comment]
@joakime consider instead using the real client.

**Comment by joakime** [comment]
The real client would need a host of hacks to intentionally control its behavior, to allow it to test various non-happy path scenarios (timeouts, bad data, write but dont read, etc)

**Comment by sbordet** [comment]
Sure. You fix things once only, in the real client, rather than in a test class.

**Comment by joakime** [comment]
Last time we looked into this, there were changes in jetty-io and jetty-http that you were uncomfortable with.
That hasn't changed AFAIK.
