### ISSUE TITLE
PathWatcher scan/recurse depth configuration

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#320]
migrated from Bugzilla [#469786](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469786)
status ASSIGNED severity *normal* in component *other* for *9.3.x*
Reported in version *9.3.0* on platform *All*
Assigned to: Jan Bartel

On 2015-06-09 19:50:34 -0400, Joakim Erdfelt wrote:

> Current implementation incorrectly uses Files.walkFileTree() and a customized DepthLimitedFileVisitor to control walk/scan depth.
> 
> The proper way is to use the maxDepth parameter on Files.walkFileTree()

On 2015-06-09 21:44:36 -0400, Jan Bartel wrote:

> Joakim,
> 
> I still have some outstanding changes to this class, so I'll take this issue for now.
> 
> Jan

On 2015-06-10 07:18:00 -0400, Joakim Erdfelt wrote:

> This was a reminder issue for myself. :-)
> 
> Not saying that the DepthLimitedFileVisitor is wrong, just that there's specific way already built-into the Files.walkFileTree() method that seemed more appropriate.
> 
> Heck, I believe I'm the one that originally created the DepthLimitedFileVisitor.

**Comment by joakime** [comment]
This doesn't seem relevant anymore.
