### ISSUE TITLE
Sessions leaking with error pages from async dispatch

### ISSUE THREAD

**Issue by carey** [eclipse/jetty.project#3203]
As discussed in the thread at https://www.eclipse.org/lists/jetty-users/msg08704.html, we're seeing sessions created with `_requests` always set to 1 with Jetty 9.4.14. Since `_requests_` never goes to 0, these sessions are never expired, which leads to a memory leak.

This was initially seen with a JSP error page for 503 status codes from the Jetty QoSFilter. However, the code at https://github.com/carey/jetty-sessions-bug reproduces this without filters or JSPs by calling `req.startAsync().dispatch()`, calling `sendError(404)` from the async request, then calling `req.getSession()` from the servlet configured as the `<error-page>` for that status.

**Comment by carey** [comment]
It appears that I didn't make my test case simple enough. I don't even need an error page, just a session that gets created on an async dispatch.

**Comment by janbartel** [comment]
Yup. But your test case was good enough for me to work out the problem
anyway.

 I'll check my fix in tomorrow.

Jan

**Comment by janbartel** [comment]
Fix checked in to jetty-9.4 and beyond.
