### ISSUE TITLE
Threadpool module creates unmanged threadpool

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3210]
The fix for #2130 creates a threadpool in an XML `<Configure>` clause, so the `XmlConfiguration` mechanism starts the threadpool itself rather than letting the server instance start it.  Thus the thread pool ends up being unmanaged and does not appear in detail in a server dump.

**Comment by gregw** [comment]
This can be fixed either by:
 + explicitly managing the threadpool in `jetty.xml`
 + or not creating the threadpool as a top level object in `jetty-threadpool.xml`

**Comment by gregw** [comment]
@sbordet @WalkerWatch what is your preferred fix?  Do you want to take it, or shall I ?

**Comment by sbordet** [comment]
@gregw if possible I would go for not creating the `ThreadPool` as a top level object.

The change would be from:

```xml
<Configure id="threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
```

to 

```xml
<Configure>
  <New id="threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
```

If it is that simple, go for it.
