### ISSUE TITLE
Autobahn WebSocketServer failures in jetty 10

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3216]
fix existing Autobahn WebSocketServer failures in jetty 10

**Comment by olamy** [comment]
@lachlan-roberts fyi currently autobahn is in branch `jetty-10.0.x_autobahn_test_ci` 
to run the tests: ` mvn clean install -pl :test-websocket-autobahn -am -e -DskipTests -Pautobahn `

**Comment by lachlan-roberts** [comment]
@olamy  I was getting some failures of the autobahn tests locally and I made some changes to fix them however the failures in https://jenkins.webtide.net/job/nightlies/job/jetty-10.0.x-autobahn/ look different to the ones I was getting

**Comment by lachlan-roberts** [comment]
there are instructions how to run it in the javadoc of the AutobahnWebSocketServer

i just run the AutobahnWebSocketServer through the IDE then run the command 
`wstest --mode=fuzzingclient --spec=fuzzingclient.json` from command line

https://github.com/eclipse/jetty.project/blob/a5e89d03409bb3563838ea302b4e26be9fc925f5/jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/autobahn/AutobahnWebSocketServer.java#L33-L64

**Comment by olamy** [comment]
ah ok I didn't know this AutobahnWebSocketServer.java I have to update both branches to use that :)
