### ISSUE TITLE
Need better jar bytecode scanning exclusion mechanism

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#322]
migrated from Bugzilla [#465020](https://bugs.eclipse.org/bugs/show_bug.cgi?id=465020)
status ASSIGNED severity _enhancement_ in component _other_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Jan Bartel

On 2015-04-20 09:19:04 -0400, Joakim Erdfelt wrote:

> The use of "org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern" and "org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern" are cumbersome when dealing with many many jar files.
> 
> This enhancement is requesting an alternative (easier) approach.
> 
> Here's 2 ideas:
> 
> 1) Instead of relying on an include based approach only, how about allowing for a similar "org.eclipse.jetty.server.webapp.WebInfExcludeJarPattern" (and to a lesser extend a "org.eclipse.jetty.server.webapp.ContainerExcludeJarPattern")
> 
> Where the exclude pattern is evaluated first, flagging jars to never include.
> 
> 2) Allow webapps to make an empty marker file in the webapp that can be used to indicate what jars should not be scanned eg: WEB-INF/lib/extjs-5.1.0.jar.noscan
> 
> These files can be used during the evaluation of "org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern" to exclude jars from the scanning in an individual basis.

**Comment by joakime** [comment]
Another approach would be to allow tagging of jars that should be scanned with empty files via their filename.

Example: 

WEB-INF/lib/.noscan
WEB-INF/lib/mylib.jar.scanme

This is similar to how Android works with its media scanner.
