### ISSUE TITLE
Proxied headers are not logged

### ISSUE THREAD

**Issue by travisspencer** [eclipse/jetty.project#3227]
The proxy servlet does not log the headers forwarded to the origin server. It logs those made to the proxy itself, but not those that are send upstream. This can make debugging harder as Jetty log files are not enough to know what is actually forwarded. Looking at the code, it seems that these headers meant to be logged, but aren't due a small bug in `AbstractProxyServlet.java` causing them to besilently dropped:
```java
_log.debug("{} proxying to upstream:{}{}{}{}",
                    getRequestId(clientRequest),
                    System.lineSeparator(),
                    builder,
                    proxyRequest,
                    System.lineSeparator(),
                    proxyRequest.getHeaders().toString().trim());
```
The issue is that the log message is missing a format specifiers, and SLF4J is then silently ignoring the extra parameter, the proxy request headers.
The fix is obvious -- add another specifier.

**Comment by sbordet** [comment]
Fixed by ce3defa2f5cdc588b122fba18e34fede93803da7.
