### ISSUE TITLE
oej.http.HttpURI and oej.util.URIUtil overlap in functionality

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#323]
migrated from Bugzilla [#464743](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464743)
status ASSIGNED severity _trivial_ in component _build_ for _9.3.x_
Reported in version _9.3.0_ on platform _PC_
Assigned to: Project Inbox

On 2015-04-15 16:58:46 -0400, Joakim Erdfelt wrote:

> The features and functiona of jetty-http's HttpURI overlap with the features of jetty-util's URIUtil

On 2015-04-21 01:27:25 -0400, Greg Wilkins wrote:

> There is not a huge overlap, albeit that the class design is a little bit strange as it was influenced over time by the JVMs changing implementation and URL vs URI schism.
> 
> URIUtil is applicable to all URIs including file: jar:file: jndi:  schemes.  It is a static method only class and is never instantiated.
> 
> HttpURI is a parser for http: URIs and does not duplicate any URIUtil functionality.  It actually uses URIUtil for some methods... although it does also use UrlEncoded that does have a bit of overlap with URIUtil
> 
> So there is probably scope to review these three classes, but if we wait until Jetty goes java-8 only then there are probably a lot more JVM provided libraries that can be used.

**Comment by joakime** [comment]
Closing as not relevant.
