### ISSUE TITLE
AuthenticationProtocolHandler should not cache the failed results

### ISSUE THREAD

**Issue by graju256** [eclipse/jetty.project#3234]
https://github.com/eclipse/jetty.project/blob/dc194456056eb9ea10a4cca250e0c91802e6c8c0/jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java#L312

AfterAuthenticationListener should check the response status prior to storing the Authentication.Result for future use. It might save the round trip time in seeing the failures but it creates a problem where the same client is used but two protected resources are fetched one with correct credentials and other with incorrect ones. Wouldn't be good if we skip storing the failed auth results to store?

**Comment by sbordet** [comment]
Fixed.
