### ISSUE TITLE
Missing source bundle for org.eclipse.jetty.proxy

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#324]
migrated from Bugzilla [#463758](https://bugs.eclipse.org/bugs/show_bug.cgi?id=463758)
status NEW severity *normal* in component *build* for *9.3.x*
Reported in version *unspecified* on platform *PC*
Assigned to: Jesse McConnell

On 2015-04-02 04:11:55 -0400, Xavier Coulon wrote:

> I currently use Jetty 9.2.5 and I noticed that 
> http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.5.v20141112/plugins/ misses the source bundles for org.eclipse.jetty.proxy_9.2.5.v20141112.jar and  org.eclipse.jetty.proxy_9.2.5.v20141112.jar.pack.gz
> 
> The same problem occurs on the latest version at the time when this bug is opened: http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.10.v20150310
> 
> Would it be possible to include the missing source bundles in the next build ?
> Thanks

On 2016-01-25 23:39:01 -0500, Wagner Tsuchiya wrote:

> I realized that the sources jar are generated during the build process.
> 
> Could you explain about how these bundles are generated? So I could fix it.
> 
> Thanks,

**Comment by janbartel** [comment]
I've updated the jetty-9.3 p2 build to include the proxy source bundle and regenerated the 9.3  bundles.
