### ISSUE TITLE
Generate jetty-maven-plugin website

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#3247]
We should generate the maven plugin website and bundle it up as a downloadable artifact for mounting on the eclipse.org/jetty website.

**Comment by olamy** [comment]
@jmcc0nn3ll do you want me to look at this?

**Comment by jmcc0nn3ll** [comment]
It is on my list of things to get ironed out, should be this week.

**Comment by olamy** [comment]
pr still ready for jetty-10 https://github.com/eclipse/jetty.project/pull/3364

**Comment by gregw** [comment]
I believe this is fixed?  @olamy reopen if there is more to do
