### ISSUE TITLE
Add integration tests for jsp, jstl and custom taglibs

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3254]
We need to add some integration tests for maven-plugin testing:
- simple jsps
- jstl usage
- custom taglibs (located in both WEB-INF/classes or WEB-INF/lib/*.jar)
- user with jstl standard/api jar in the WEB-INF/lib/

**Comment by joakime** [comment]
The last one may or may not be a valid test case.
Perhaps it's a testcase for a negative situation (a known bad setup/configuration)?
Wdyt @janbartel ?

**Comment by janbartel** [comment]
I'm not keen on testing jstl inside the webapp with the plugin. That should be tested elsewhere in jetty.

**Comment by janbartel** [comment]
@joakime, yes I know. I mean I'm not interested in supporting this scenario in the maven plugin. Elsewhere in jetty we can test whether deploying in the distro a webapp containing jstl works - useful to know whether we have any impediment to it working, but not something we need to support with the plugin.

**Comment by olamy** [comment]
ok I get it jsp was failing only with jetty-maven-plugin. So we probably don't too much sophisticated test?
