### ISSUE TITLE
check jetty-10.0.x websockets for backward compatibility with 9.4 jetty API

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3256]

**Comment by sbordet** [comment]
I don't think this is strictly needed - kinda nice to have but there are many thing that were wrong/bad that may be improved, so API changes are fine, also considering this is going to require JDK 11.

**Comment by gregw** [comment]
I think we should still do this as if we find differences, we might just document them rather than revert them.

**Comment by gregw** [comment]
Also within this issue resolve the question from @joakime raised in #3222: "Missing the embedded-jetty pre-configured mappings attribute. where did they go?"
