### ISSUE TITLE
Jetty's CGI servlet does not use the expected working directory when executing scripts

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#326]
migrated from Bugzilla [#458483](https://bugs.eclipse.org/bugs/show_bug.cgi?id=458483)
status ASSIGNED severity _normal_ in component _other_ for _9.2.x_
Reported in version _9.2.6_ on platform _Macintosh_
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[CGI-working-directory.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=250241)_ (ID 250241)

On 2015-01-27 01:26:35 -0500, Matthew Sheppard wrote:

> Created attachment 250241
> Patch to set the working directory for CGI script invocation correctly
> 
> According to http://www.ietf.org/rfc/rfc3875 the working directory for a CGI script invocation "SHOULD be set to the directory containing the script". Currently Jetty's CGI servlet instead uses the CGI servlet's resourceBase, which does not account for the possibility of scripts existing in sub-directories of the resourceBase.
> 
> A simple change which fixes this is attached.
> 
> Happy to provide it in some other form (i.e. one described in https://www.eclipse.org/jetty/documentation/current/contributing-patches.html#d0e23974) if desired. It doesn't seem like it's feasible to create a unit test for this without substantial changes, but happy to discuss if you feel it needs one.
> 
> Note that Jetty 8's CGI servlet appears to have behaved correctly in this regard, so the change seems to be a regression.

**Comment by mattsheppard** [comment]
I long since worked around it for my case, so no longer care much about it, but it may still be valuable to fix for anyone who is using the default CGI servlet.

**Comment by mattsheppard** [comment]
Raised a pull request for this in https://github.com/eclipse/jetty.project/pull/4338 because the stale bot reminded me it existed.

I'm totally fine, though, if you'd just like to close this with no further action - The issue no longer affects me, and doesn't seem to be tripping anyone else up.
