### ISSUE TITLE
Exec mode breaks ServerConnector inheritChannel

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#327]
migrated from Bugzilla [#457988](https://bugs.eclipse.org/bugs/show_bug.cgi?id=457988)
status ASSIGNED severity _normal_ in component _spdy_ for _9.2.x_
Reported in version _9.2.6_ on platform _PC_
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[file_457988.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=250113)_ (ID 250113)

On 2015-01-20 15:22:49 -0500, Thomas Meyer wrote:

> Enabling the spdy modules enables protonego as dependency which enables apln module which has an exec section. That exec section silently enables the exec mode.
> 
> But it seems that the exec mode doesn't inherit the fd 0 and 1 needed for the System.inheritChannel call in the ServerConnector.
> 
> I changed the default spdy etc file to set inheritChannel to true.

On 2015-01-20 16:31:11 -0500, Joakim Erdfelt wrote:

> What do you mean by "fd 0 and 1"?
> 
> We eat our own dogfood with our own websites, and the module system for spdy (and now http2) work as expected on java 8u25, no failures.

On 2015-01-20 16:31:55 -0500, Joakim Erdfelt wrote:

> changing component to spdy, as its that module's configuration we are talking about.

On 2015-01-20 16:56:44 -0500, Thomas Meyer wrote:

> I want to use systemd socket activation, also know as xinetd, with the spdy protocol.
> 
> I want to run jetty as an unprivileged user but still want to be able to connect via IPv6 so therefore above trick.
> 
> To get socket activation you need to set the attribute inheritChannel of the ServerConnector to true, this is what I did.
> 
> Sadly the protonego module has an exec section with enables --exec mode. But the process created with the ProcessBuilder doesn't inherit the file descriptors (fd) 0 and 1 which are normally connected to the stdin and stdout.
> 
> But in the xinetd/systemd socket activation case fd 0 and 1 are used as the stream input and output.
> 
> So how do you solve IPv6 connectivity on your installation? Do you run your Java process as root?
> 
> Maybe it is possible to change the file descriptors 0 and 1 in the --exec case to get connected to the original ones of the initial Java process.
> 
> So I think start was the correct assignment of this bug report.

On 2015-01-21 10:56:30 -0500, Thomas Meyer wrote:

> Created attachment 250113
> proposed patch

**Comment by gregw** [comment]
wont fix
