### ISSUE TITLE
OSGi versions of java.base classes in org.apache.felix:org.osgi.foundation:jar conflicts with new rules on Java 9+

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3274]
OSGi includes a jar file `org.apache.felix:org.osgi.foundation:jar` that has `java.base` classes (and java microedition classes) with no other osgi classes present.
These classes conflict with Java 9+ behaviors.
And it conflicts with compilation.
And it conflicts with javadoc generation.

**Comment by janbartel** [comment]
@joakime, what are the build errors? I have been building fine at the command line with jdk-11 ...

**Comment by joakime** [comment]
various flavors of "Type <java.lang.*>" is "inaccessible" from various contexts.
This is because of JDK-11 and JPMS.
That entire jar is forbidden with JDK-11 and JPMS.
It needs to be removed for Jetty 10.x+ at a minimum.

**Comment by joakime** [comment]
@janbartel run your project in JDK 11.0.2 and/or in JPMS mode (for test cases) on your chosen IDE.
Or run the javadoc build (anywhere, command line or IDE)
Or run the javadoc inspection reports in your chosen IDE.

Ultimately, it doesn't matter where the problem is, that jar is forbidden on JDK9+ anyway.
As even the non-JPMS mode will still use `java.base` and that will conflict with the JAR mentioned.

**Comment by joakime** [comment]
This manifests quicker on JDK 11.0.2 then other earlier JDKs.
But it can happen on earlier JDKs (even JDK7 or JDK6!).
Especially when the `org.eclipse.foundation` jar exists on the classloader before the JDK's `rt.jar` (or the `java.base` module)
The classes in `org.eclipse.foundation` are ancient, pre generics, likely from the JDK 1.3 time period.

Other projects have hit similar issues and are excluding `org.osgi.foundation`.

* https://ecosystem.atlassian.net/browse/STRM-2074
* http://web.ist.utl.pt/ist162500/?p=49
* https://issues.gradle.org/browse/GRADLE-1682
* https://github.com/seges/acris/wiki/CodeGenerationPlatform_Pitfall_EclipseDep
* https://github.com/apache/camel/blob/master/components/camel-test-blueprint/pom.xml#L117-L136
* https://apache.googlesource.com/geronimo-specs/+/56c92b3ca0326d8c3fb2eab3d1cfae19b7cb69e2/geronimo-jpa_2.1_spec/pom.xml#69
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=343069
* https://www.mail-archive.com/servicemix-commits@geronimo.apache.org/msg04182.html

**Comment by janbartel** [comment]
Merged.
