### ISSUE TITLE
Jetty can't presently be a HTTP proxy server - it chokes on the CONNECT invocation

### ISSUE THREAD

**Issue by paul-hammant** [eclipse/jetty.project#3276]
If you launch a Jetty (embedded) wanting it be a proxy server, the parsing of the CONNECT HTTP line is messed up.  If there's a "yes, let's support this" reaction, then I'll make a maven standalone demo of the bug for y'all.

**Comment by sbordet** [comment]
CONNECT parsing is not "messed up" in Jetty and we know many that use Jetty as a proxy server.

Perhaps if you detail what your code is, what Jetty version you are using, what you are trying to do, what exact error you get - the basics of issue reporting - we may be more helpful.

Browsing Jetty source code for "ProxyServer" yields you a couple of examples, e.g. https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ProxyServer.java.

**Comment by paul-hammant** [comment]
Thanks for the insta-close

**Comment by joakime** [comment]
There's little to work with on your initial message and your followup.
Just like other places, if there's no detail the issues is closed until there is.
You mention proxy server, and embedded, but not once do you detail how you have it setup.

Example:
https://github.com/eclipse/jetty.project/blob/afa708a6b88aa2d0a2891696fb09e7b13e3ed8e2/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ProxyServer.java#L37-L46

Closed is not permanent, we can reopen (and have done so many times in the past).
So feel free to provide some detail on what you are doing, what you have tried, and what you expect.

**Comment by paul-hammant** [comment]
So you're say "yes, make a maven standalone demo of the bug for us", right?  Or would something else be more amenable to the dev team. For the OSS pieces I maintain, standalone reproductions on GH is the gold standard of what I would expect from my user community. I'm not going to go that far, if is explicitly not what you want.

**Comment by paul-hammant** [comment]
On it.

**Comment by paul-hammant** [comment]
I can't reproduce this in a *legitimate* way. I can make a handler and start Jetty listening in a Unit test, then direct RestAssured to ask for a resource (with Jetty as a proxy server). It has messed up `getRequestURL()` reporting if the subject of the GET is a also a localhost address (Jetty the proxy server is implicitly a localhost address to from the point of view of the test). This is so marginal as a use case that it's **not worth viewing this as something worth investigating**.  Specifically, Jetty's reporting getRequestURL() as "http://localhost:8080localhost:8080" or similar.  I think I'm just going to avoid the double localhost setup for my niche testing, if I can.

**Comment by joakime** [comment]
> Jetty's reporting getRequestURL() as "http://localhost:8080localhost:8080" or similar.

There are many components in Jetty with a `getRequestURL()`, which component was giving you that?

**Comment by paul-hammant** [comment]
OK, I'll give it another go. Paring down a large solution to a tight testcase is the challenge.

```
jettyServer.setHandler(new AbstractHandler() {

            @Override
            public void handle(String target, org.eclipse.jetty.server.Request baseRequest,
                               HttpServletRequest request, HttpServletResponse response) throws IOException {

      request.getRequestURL().toString();
      // ^ the culprit

});
```

**Comment by paul-hammant** [comment]
OK, that was mentioned before. Cool. I'd add two handlers then. I'm guessing the connect handler first, and I should be sure to do the `baseRequest.setHandled(true);` line so that the vanilla handler doesn't get the same request with (*the messed up*) getRequestURL() result.

**Comment by joakime** [comment]
Nope, that wont help.
A `CONNECT` method request only has a `host:port` pair, no context, no path, no scheme, etc.  There's no information to form the URI/URL from.  

What you are seeing when you see `http://localhost:8080localhost:8080` is likely a `CONNECT` request, as the `host:pair` will be seen as a "path" by the entirety of Jetty.
Resulting in `<active-httpconfiguration-scheme>://<active-connector-host>:<active-connector-local-port>/<path>`
