### ISSUE TITLE
WebSocket write may hang forever

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3279]
* [T1] Client receives a message from server, it happens to be a message too large for the client configuration.
* [T1] WebSocket endpoint's `onError()` is called, notifying the application.
* [T1] `WebSocketSession.close()` is called to generate the `CLOSE` frame to send to the server.
* [T1] The `CLOSE` frame is enqueued and flushed by the `FrameFlusher`, but its callback is not completed yet.
* [T2] Application writes a message with callback and enqueues it in the `FrameFlusher`. This is possible because `FrameFlusher.enqueue()` does not stop accepting frame after a `CLOSE` frame (which may be ok - see below).
* [T2] Tries to `iterate()` the flusher, but it's a noop because the flusher is currently processing.
* [T2] Now waiting for the callback to be completed.
* [T1] Runs the `CLOSE` frame callback `OnCloseLocalCallback`.
* [T1] `FrameFlusher.succeedEntries()` is called, which calls `FrameFlusher.terminate()` which terminates the `FrameFlusher` with still one entry in the queue. Log line proof:
`2019-01-21 11:10:04,541 WebSocketClient@1650955365-785 [DEBUG][io.FrameFlusher] Terminating Flusher@b665ba2[queueSize=1,aggregateSize=-1,terminated=java.nio.channels.ClosedChannelException]`
Note `queueSize=1`. At this point, `FrameFlusher.closed=true`.
* [T1] There is still an attempt to flush the `FrameFlusher`, but the logic in `FrameFlusher.process()` does this:
`if (closed) return Action.SUCCEEDED;`
That is, there is no attempt to drain the queue.
* [T1] T1 returns but the entry in the queue is never notified, possibly hanging T2 forever.

The combination of `FrameFlusher.enqueue()` not checking for `CLOSE` frame, coupled with `FrameFlusher.terminate()` not draining the queue, or alternatively `FrameFlusher.process()` not draining the queue if closed make the events above possible.

**Comment by dreis2211** [comment]
Hi @sbordet . Might this be possibly related to #2061?

**Comment by sbordet** [comment]
@dreis2211 could be.

Are you able to take a [server dump](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html)?
The dump should show if the `FrameFlusher` has queued entries or not.
If so, you are probably hitting the same case as this issue.

**Comment by sbordet** [comment]
See also #272.

**Comment by dreis2211** [comment]
@sbordet That might be difficult as we have the mitigation in place described in #272 and #2061 for our production systems. And our staging systems unfortunately show this behaviour very rarely. I'll see what I can do.

**Comment by sbordet** [comment]
@dreis2211 what mitigation? To use your own callback?

**Comment by dreis2211** [comment]
@sbordet How would one be able to access the `Server` instance in `BlockingWriteCallback`? I'd be happy to do that, but I see no way to do it.

**Comment by dreis2211** [comment]
Same problem. I see no way accessing this in BlockingWriteCallback without rewriting more and surpasses my Jetty knowledge. Do I miss something?

**Comment by sbordet** [comment]
@dreis2211 can you show what modification you have done?

**Comment by dreis2211** [comment]
```

**Comment by dreis2211** [comment]
@sbordet While thinking about it, even with this modifications one should be able to see that in a server dump. E.g. that the FrameFlusher still has an entry. It is way shorter timeframe, but it should be noticeable, right?

**Comment by sbordet** [comment]
If you can get your system to a point where it's quiet (no traffic) and appears to be hung, then yes a `Server.dump()` via JMX should be able to show the `FrameFlusher` in the wrong state. 
Not sure how easy for you to get into that condition.
You should have a positive if you see the `FrameFlusher` in this condition:

`Flusher@b665ba2[queueSize=1,aggregateSize=-1,terminated=java.nio.channels.ClosedChannelException]`

The important bits are `queueSize > 0` _and_ `terminated != null`.

If you see both those conditions, then your issue is this issue.

**Comment by joakime** [comment]
Opened PR #3315

**Comment by gbrehmer** [comment]
@sbordet i can confirm that in case of the mentioned thread leakage behavior in #2061 the FrameFlusher has a queuesize of 1 and terminated is the same exception like yours: java.nio.channels.ClosedChannelException (checked with memory heap dump)

**Comment by joakime** [comment]
Merged into `jetty-9.4.x` from PR #3315
