### ISSUE TITLE
Better XMLConfiguration Validation for values

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#328]
migrated from Bugzilla [#452331](https://bugs.eclipse.org/bugs/show_bug.cgi?id=452331)
status ASSIGNED severity _normal_ in component _other_ for _9.2.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Greg Wilkins

On 2014-11-19 12:38:57 -0500, Joakim Erdfelt wrote:

> Some value conversions do not warn on invalid values.
> 
> Example from etc/jetty.xml:
> 
> ```
> <Set name="dumpAfterStart"><Property name="jetty.dump.start" default="false"/></Set>
> ```
> 
> If the start.ini entry reads ...
> 
> jetty.dump.start=trrrue
> 
> then this will result in Server.setDumpAfterStart(false); as it doesn't match "true".  
> 
> It would be great if attempts to provided string values to native types did some sort of validation that the provided string values even match the range of possible choices for that native type.
> 
> This would mean a warning message akin to the following could be displayed.
> 
> WARN:2014-11-29: XML Value Error [trrrue] is not a valid java.lang.Boolean for <Set> on id="Server" name="dumpAfterStart" in etc/jetty.xml

On 2014-11-19 23:30:44 -0500, Greg Wilkins wrote:

> The code is currently using new Boolean(String) to parse the values and the issue is that it does not throw an exception for "trrue" or any other bad values.
> 
> We could consider a special case for Boolean?

On 2014-11-20 06:37:25 -0500, Joakim Erdfelt wrote:

> I would also wonder about conversions to numbers (Integer, Long, Double, etc...)
> 
> What happens on these input values?
> 
>    "100 dogs"  (likely becomes 100)
>    "1.5"       (likely becomes 1 for Integer, 1.5 for Double)
>    "1,234"     (this would be Locale specific.
>                 as it could either be "1234" Integer in US
>                 or "1.234" Double in some European countries.)
> 
> If I think of more I'll add them to this bug.

On 2014-11-20 06:38:20 -0500, Joakim Erdfelt wrote:

> Note: this bug was filed as a more specific response to bug # 441209

On 2014-11-20 16:51:55 -0500, Greg Wilkins wrote:

> The integer and float constructors appear better at raising errors than new Boolean(String)

**Comment by gregw** [comment]
leave as is
