### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: ....MvcConfiguration$$EnhancerByCGLIB$$8199e631 is not an enhanced class

### ISSUE THREAD

**Issue by temmyg** [eclipse/jetty.project#3285]
Hi 

I used below command line to start an web application, however, I met this stack trace, 
My project is [here](https://github.com/temmyg/SpringMvcFormExample3).

To produce:

1. clone to local folder

2. run `java -classpath C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1 -jar C:\Users\someone\Desktop\Admin\OnlineLab\jetty-runner-9.4.12.v20180830.jar C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3 --lib C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\lib --classes C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1`

Also let you know, if you change > WEB-INF\classes1 to > WEB-INF\classes

 and run 

`java -jar C:\Users\someone\Desktop\Admin\OnlineLab\jetty-runner-9.4.12.v20180830.jar C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3`

All is working fine.

> Failed startup of context o.e.j.w.WebAppContext@1a052a00{SpringMvcFormExample,/,file:///C:/Users/someone/Desktop/Admin/OnlineLab/SpringMvcFormExample3/,UNAVAILABLE}{file:///C:/Users/someone/Desktop/Admin/OnlineLab/SpringMvcFormExample3/}
> javax.servlet.ServletException: SpringDispatcher@3fafd0b4==org.springframework.web.servlet.DispatcherServlet,jsp=null,order=1,inst=false
>         at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:691)
>         at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
>         at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
>         at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
>         at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:168)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.server.Server.start(Server.java:416)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:383)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.runner.Runner.run(Runner.java:532)
>         at org.eclipse.jetty.runner.Runner.main(Runner.java:577)
> Caused by:
> java.lang.IllegalStateException: Cannot load configuration class: net.codejava.spring.config.MvcConfiguration
>         at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:366)
>         at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:242)
>         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
>         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:633)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
>         at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:651)
>         at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:599)
>         at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:665)
>         at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:518)
>         at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:459)
>         at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
>         at javax.servlet.GenericServlet.init(GenericServlet.java:244)
>         at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
>         at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
>         at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
>         at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
>         at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:168)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.server.Server.start(Server.java:416)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:383)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.runner.Runner.run(Runner.java:532)
>         at org.eclipse.jetty.runner.Runner.main(Runner.java:577)
> Caused by:
> java.lang.IllegalArgumentException: class net.codejava.spring.config.MvcConfiguration$$EnhancerByCGLIB$$8199e631 is not an enhanced class
>         at org.springframework.cglib.proxy.Enhancer.setCallbacksHelper(Enhancer.java:621)
>         at org.springframework.cglib.proxy.Enhancer.registerStaticCallbacks(Enhancer.java:594)
>         at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:120)
>         at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:92)
>         at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:356)
>         at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:242)
>         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
>         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:633)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
>         at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:651)
>         at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:599)
>         at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:665)
>         at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:518)
>         at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:459)
>         at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
>         at javax.servlet.GenericServlet.init(GenericServlet.java:244)
>         at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
>         at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
>         at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
>         at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
>         at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:168)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
>         at org.eclipse.jetty.server.Server.start(Server.java:416)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:383)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.runner.Runner.run(Runner.java:532)
>         at org.eclipse.jetty.runner.Runner.main(Runner.java:577)
> 
>

**Comment by olamy** [comment]
Reading  ` Caused by:
java.lang.IllegalArgumentException: class net.codejava.spring.config.MvcConfiguration$$EnhancerByCGLIB$$8199e631 is not an enhanced class ` so I don't see error coming from Jetty.
You only provide classes.
In order to be able to help We need sources and how to build your project.

**Comment by temmyg** [comment]
Thank you, the source is [here](https://github.com/temmyg/SpringMvcFormExample3-Src), built by maven

**Comment by olamy** [comment]
thanks but how to reproduce your problem with this git repo?

**Comment by temmyg** [comment]
1. clone https://github.com/temmyg/SpringMvcFormExample3 to a local folder .\mylocal
2. under .\mylocal, **run** 
java -classpath C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1 -jar C:\Users\someone\Desktop\Admin\OnlineLab\jetty-runner-9.4.12.v20180830.jar C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3 --lib C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\lib --classes C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1

**Comment by olamy** [comment]
Please give a way to reproduce how you compile your classes (a maven pom and goals, commands your are using) because giving the error message there is definitely something wrong with that...

**Comment by temmyg** [comment]
@olamy , when you downloaded from https://github.com/temmyg/SpringMvcFormExample3-Src, open it in IntelliJ IDE, and then there is a POM file there, use it to compile the project to a .war file along with its exploded folder, that folder content is similar to what I am giving in (https://github.com/temmyg/SpringMvcFormExample3). 

Try to do that, if you met problem, let me know. 

Thank you for your attentions on it.

**Comment by olamy** [comment]
So I did 
- to create the war `mvn clean package` 
- to run the war `java -jar jetty-runner-9.4.12.v20180830.jar target/SpringMvcFormExample.war' 

this starts without error. (there are other issues with your project but I cannot see anything related to Jetty)

Please provide all command line to reproduce your issue

**Comment by temmyg** [comment]
Did you run this as I said:

java -classpath C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1 -jar C:\Users\someone\Desktop\Admin\OnlineLab\jetty-runner-9.4.12.v20180830.jar C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3 --lib C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\lib --classes C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1

**Comment by olamy** [comment]
Nope I use the src project. I need to know how do you compile your project.
As far I can see from logs the cause is from Spring
```
Caused by:
java.lang.IllegalArgumentException: class net.codejava.spring.config.MvcConfiguration$$EnhancerByCGLIB$$8199e631 is not an enhanced class
at org.springframework.cglib.proxy.Enhancer.setCallbacksHelper(Enhancer.java:621)
at org.springframework.cglib.proxy.Enhancer.registerStaticCallbacks(Enhancer.java:594)
at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:120)
at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:92)
at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:356)
```
so maybe due how do you compile your project.
so your compiled classes doesn't help me...

**Comment by temmyg** [comment]
in src project, use maven package to create .war and exploded folder from .war under "target" folder, then you copy all files under that exploded folder for your testing. 

I already know it's due to a bug from Jetty's ClassLoader, when you set your compiled classes using --classpath or  application  -classes option, and run, that will throw exceptions and it occurs every time. 

If you do not like to look into it, I am fine, I already past it and using other approaches to launch web app.

**Comment by olamy** [comment]
running a web application (i.e war file) has some requirements defined by servlet api specifications.
So definitely will not work as you expect with arguments such `2\. -classpath C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1 -jar C:\Users\someone\Desktop\Admin\OnlineLab\jetty-runner-9.4.12.v20180830.jar C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3 --lib C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\lib --classes C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1 ` 
But you can still use embeded mode?

**Comment by temmyg** [comment]
according to your own [documentation](https://www.eclipse.org/jetty/documentation/9.4.x/runner.html#jetty-runner):

> Usage: java [-Djetty.home=dir] -jar jetty-runner.jar [--help|--version] [ server opts] [[ context opts] context ...]
Server opts:
 --version                           - display version and exit
 --log file                          - request log filename (with optional 'yyyy_mm_dd' wildcard
 --out file                          - info/warn/debug log filename (with optional 'yyyy_mm_dd' wildcard
 --host name|ip                      - interface to listen on (default is all interfaces)
 --port n                            - port to listen on (default 8080)
 --stop-port n                       - port to listen for stop command (or -DSTOP.PORT=n)
 --stop-key n                        - security string for stop command (required if --stop-port is present) (or -DSTOP.KEY=n)
 [--jar file]*n                      - each tuple specifies an extra jar to be added to the classloader
 [--lib dir]*n                       - each tuple specifies an extra directory of jars to be added to the classloader
 [--classes dir]*n                   - each tuple specifies an extra directory of classes to be added to the classloader
 --stats [unsecure|realm.properties] - enable stats gathering servlet context
 [--config file]*n                   - each tuple specifies the name of a jetty xml config file to apply (in the order defined)
Context opts:
 [[--path /path] context]*n          - WAR file, web app dir or context xml file, optionally with a context path

`

>  **[--classes dir]*n                   - each tuple specifies an extra directory of classes to be added to the classloader**

Using above option should work. I just follow IntelliJ [JettyRunner](https://plugins.jetbrains.com/plugin/7505-idea-jetty-runner) plugin's approach. If you have bug in it, JettyRunner plugin will also not work.

`

**Comment by olamy** [comment]
@temmyg maybe there is an issue I cannot argue with that. But you need to give us some way to reproduce your problem.
Sorry but I don't have anything locally such ` C:\Users\someone\Desktop\Admin\OnlineLab\SpringMvcFormExample3\WEB-INF\classes1 ` 
So I only need a way to reproduce your problem with 
- a project with a maven build
- a command line with some relative path to this sample project
