### ISSUE TITLE
Javadoc for HttpTester and ServletTester needs to reference limited HTTP version scope

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#329]
migrated from Bugzilla [#446952](https://bugs.eclipse.org/bugs/show_bug.cgi?id=446952)
status ASSIGNED severity _minor_ in component _other_ for _9.2.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Project Inbox

On 2014-10-13 13:34:30 -0400, Joakim Erdfelt wrote:

> We need to evaluate the effects of the Jetty 9.3 branch and its changes to the HttpParser / HttpGenerator when it comes to the HttpTester and ServletTester classes.
> 
> It might be that only minor changes need to be made.
> 
> However, the javadoc documentation, and jetty-documentation on these classes should be updated to highlight the limited scope/role of these classes to only refer to HTTP/1.1 processing.

On 2014-10-13 13:55:01 -0400, Joakim Erdfelt wrote:

> The documented use of HttpTester should make it clear that because of the nature of SPDY and HTTP/2 the use is object based, not protocol based.
> 
> You create Request objects, hand it off, and get Response objects.
> 
> Not, you create a wireline HTTP/1.1 raw request and hand it off and receive a wireline HTTP/1.1 response.

**Comment by joakime** [comment]
This is irrelevant as theses support both HTTP/1.0 and HTTP/1.1 now.
