### ISSUE TITLE
org.eclipse.jetty.client.HttpClientTLSTest.testNoCommonTLSProtocol fail with jdk 11.0.2

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3293]

**Comment by joakime** [comment]
@sbordet this fails in `jetty-9.4.x` as well (when using JDK 11.0.2)

**Comment by olamy** [comment]
I did cherry pick in `jetty-9.4.x`

**Comment by sbordet** [comment]
@olamy but if you just cherry picked, you will break tests in JDK 8 that don't support TLS 1.3, no?

**Comment by olamy** [comment]
@sbordet all tests pass. Does seem right to you?
