### ISSUE TITLE
Hello Retry Request  TLS 1.3 problem with Jetty and chrome

### ISSUE THREAD

**Issue by zacoben** [eclipse/jetty.project#3295]
with crhome browser any default TLS get request is not getting the normal TLS 1.3 fast handshake :+1: 
Instead of the quick TLS 1.3 handshake the server reply with "Hello Retry Request"
(just look these packets in wireshark) 

how can we solve this bug with Jetty ?

**Comment by sbordet** [comment]
It is not a Jetty bug, it's a JDK bug, see https://bugs.openjdk.java.net/browse/JDK-8217709.
Hopefully will be backported to JDK 12.

**Comment by zacoben** [comment]
a Workaround would be to use x25519 key algorithm instead  of the classic x509 everybody uses

my standard SSLContext init is this one :

            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance("SunX509");
            keyManagerFactory.init(keyStore, "mypassword".toCharArray());
            KeyManager[] km = keyManagerFactory.getKeyManagers();
            // Create trust manager
            TrustManagerFactory trustManagerFactory =TrustManagerFactory.getInstance("SunX509");
            trustManagerFactory.init(keyStore);
            TrustManager[] tm = trustManagerFactory.getTrustManagers();
            // Initialize SSLContext
            SSLContext sslContext = SSLContext.getInstance("TLSv1.3");
           
            sslContext.init(km, tm, null);


how can I deal with X25519 ? do you have any sample code ?

**Comment by sbordet** [comment]
What you can do with Jetty is to **not** use the JDK TLS implementation.

Jetty's `SslContextFactory` can use Conscrypt instead of the JDK for the TLS implementation.
See https://webtide.com/conscrypting-native-ssl-for-jetty/
See https://www.eclipse.org/jetty/documentation/9.4.x/configuring-ssl.html

Let us know if using Conscrypt worked for you.
