### ISSUE TITLE
Embedded HTTP2 with Conscrypt on Java9+ (OpenJDK 11)

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/jetty.project#3300]
Client can't connect to Jetty server, it work fine without Conscrypt: scf.setProvider("Conscrypt");
code:
```
var threadPool = new QueuedThreadPool();
		threadPool.setMaxThreads(20);
		Server server = new Server(threadPool);
		var threadPool = new QueuedThreadPool();
		threadPool.setMaxThreads(20);
		Server server = new Server(threadPool);
		new Thread(() -> {
			try {
				//scheduled
				server.addBean(new ScheduledExecutorScheduler());
				
				// HTTP Configuration
		        var httpConf = new HttpConfiguration();
		        httpConf.setSecureScheme("https");
		        httpConf.setSecurePort(50443);
		        httpConf.setSendXPoweredBy(false);
		        httpConf.setOutputBufferSize(32768);
		        httpConf.setRequestHeaderSize(8192);
		        httpConf.setResponseHeaderSize(8192);
		        httpConf.setSendServerVersion(false);
		        httpConf.setSendDateHeader(true);
		        
		        
		        //extra, log
		        server.setDumpAfterStart(false);
		        server.setDumpBeforeStop(false);
		        server.setStopAtShutdown(true);
		        
		        
		        //HTTP Connector
		        var httpConnector = new ServerConnector(server, new HttpConnectionFactory(httpConf));
		        httpConnector.setPort(58080);
		        httpConnector.setIdleTimeout(15000);
		        httpConnector.setName("http");//for virtual host
				server.addConnector(httpConnector);
				
		        
				//https settings
				var scf = new SslContextFactory();
				scf.setProvider("Conscrypt");//enable chacha20, x25519 and others
				scf.setKeyStorePassword(new String(keyPassword));//for test
				scf.setKeyStore(serverKeyStore);
				scf.setCipherComparator(HTTP2Cipher.COMPARATOR);
				scf.setEndpointIdentificationAlgorithm("HTTPS");
				//enabled
				scf.setIncludeProtocols("TLSv1.2", "TLSv1.3");
				scf.setIncludeCipherSuites(
						"TLS_AES_256_GCM_SHA384",
						"TLS_CHACHA20_POLY1305_SHA256",
						"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
						"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
						);
				//TLS renegotiation could be disabled too to prevent an attack based on this feature.
				scf.setRenegotiationAllowed(false);
				
				
				// HTTPS Configuration
				var httpsConf = new HttpConfiguration(httpConf);
				httpsConf.addCustomizer(new SecureRequestCustomizer());
				
				
				//HTTP2
				var h2 = new HTTP2ServerConnectionFactory(httpsConf);
				var alpn = new ALPNServerConnectionFactory();
				alpn.setDefaultProtocol("h2");
				
				// SSL Connector
		        var sslConnector = new ServerConnector(server,
		            new SslConnectionFactory(scf, alpn.getProtocol()),
		            alpn,
		            h2,
		            new HttpConnectionFactory(httpsConf));
		        sslConnector.setPort(50443);
		        sslConnector.setIdleTimeout(15000);
		        sslConnector.setName("https");//for virtual host
				server.addConnector(sslConnector);

				
				//context list
				var contextCollection = new ContextHandlerCollection();
				
		        // Add a Dump Hello World on context "/"
		        var context = new ContextHandler("/");
		        context.setContextPath("/");
		        context.setHandler( new JettyHelloHandler() );//simple hello world
		        context.setVirtualHosts(new String[] { "@https" });
		        
		        
		        //HTTP to HTTPS
		        var redirectHandler = new ContextHandler("/");
	            redirectHandler.setHandler(new SecuredRedirectHandler());
	            redirectHandler.setVirtualHosts(new String[] { "@http" });
	            
	            //all handler
	            contextCollection.setHandlers(new Handler[] {redirectHandler, context});
	            server.setHandler(contextCollection);
		        
				
				server.start();
		        server.join();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}).start();
```

Server info:
WARN:oeji.ManagedSelector:qtp1992550266-19: java.lang.IllegalStateException: Connection rejected: No ALPN Processor for org.conscrypt.Java8EngineWrapper from [org.eclipse.jetty.alpn.java.server.JDK9ServerALPNProcessor@79490c2]

System:
OpenJDK 11
Libs:
conscrypt-openjdk-uber-1.4.2.jar
jetty-all-9.4.14.v20181114-uber.jar
jetty-alpn-java-server-9.4.14.v20181114.jar
jetty-alpn-server-9.4.14.v20181114.jar

**Comment by nexwo** [comment]
My fault, needed +lib: jetty-alpn-conscrypt-server-9.4.14.v20181114.jar

**Comment by nexwo** [comment]
Jetty can't enable or disable Cipher Suites at TLSv1.3 (function: scf.setIncludeCipherSuites())
E.g.: when I not set the TLS_AES_128_GCM_SHA256, then it still enabled.
It work fine with TLSv1.2

**Comment by nexwo** [comment]
code part:
```
scf.setIncludeProtocols("TLSv1.2", "TLSv1.3");
scf.setIncludeCipherSuites(
	"TLS_AES_256_GCM_SHA384",
	"TLS_CHACHA20_POLY1305_SHA256",
	"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
	"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
);
```
So only the AES 256 and CHACHA20 enabled at TLS 1.2 and TLS 1.3.
When the client connect to the server with TLS 1.3 protocol (e.g.: chrome or openssl) then the client is able to choose AES 128 as cipher (TLS_AES_128_GCM_SHA256)
But, when the client connect to the server with TLS 1.2 protocol then only AES 256 and CHACHA20 are enabled.

**Comment by joakime** [comment]
Please perform a `SslContextFactory.dump()` (of your started `SslContextFactory`).

That will tell us a bit more about what's going on.

**Comment by openron** [comment]
Result if I use this at main: Security.addProvider(new OpenSSLProvider());
(Log not show the CHACHA20 cipher but it is enabled for client)

SslContextFactory@6665f107[provider=Conscrypt,keyStore=null,trustStore=null] - STOPPED
+>trustAll=false
+>Protocol Selections
| +>Enabled size=2
| | +>TLSv1.2
| | +>TLSv1.3
| +>Disabled size=4
|   +>SSLv2Hello - ConfigExcluded:'SSLv2Hello', ConfigIncluded:NotSelected JVM:disabled
|   +>SSLv3 - ConfigExcluded:'SSLv3', ConfigIncluded:NotSelected JVM:disabled
|   +>TLSv1 - ConfigExcluded:'TLSv1', ConfigIncluded:NotSelected
|   +>TLSv1.1 - ConfigExcluded:'TLSv1.1', ConfigIncluded:NotSelected
+>Cipher Suite Selections
  +>Enabled size=2
  | +>TLS_AES_256_GCM_SHA384
  | +>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  +>Disabled size=42
    +>TLS_AES_128_GCM_SHA256 - ConfigIncluded:NotSelected
    +>TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*DSS.*', ConfigIncluded:NotSelected
    +>TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'.*DSS.*', ConfigIncluded:NotSelected
    +>TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'.*DSS.*', ConfigIncluded:NotSelected
    +>TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*DSS.*', ConfigIncluded:NotSelected
    +>TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'.*DSS.*', ConfigIncluded:NotSelected
    +>TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'.*DSS.*', ConfigIncluded:NotSelected
    +>TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 - ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 - ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 - ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 - ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'.*RSA.*', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'.*RSA.*', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 - ConfigExcluded:'.*RSA.*', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'.*RSA.*', ConfigExcluded:'.*ECDH_.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined

**Comment by openron** [comment]
Result if I use this at main: Security.insertProviderAt(new OpenSSLProvider(), 1);

SslContextFactory@5d1568e6[provider=Conscrypt,keyStore=null,trustStore=null] - STOPPED
+>trustAll=false
+>Protocol Selections
| +>Enabled size=2
| | +>TLSv1.2
| | +>TLSv1.3
| +>Disabled size=2
|   +>TLSv1 - ConfigExcluded:'TLSv1', ConfigIncluded:NotSelected
|   +>TLSv1.1 - ConfigExcluded:'TLSv1.1', ConfigIncluded:NotSelected
+>Cipher Suite Selections
  +>Enabled size=4
  | +>TLS_AES_256_GCM_SHA384
  | +>TLS_CHACHA20_POLY1305_SHA256
  | +>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  | +>TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  +>Disabled size=21
    +>SSL_RSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$', ConfigExcluded:'.*DES.*', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected JVM:disabled
    +>TLS_AES_128_GCM_SHA256 - ConfigIncluded:NotSelected JVM:disabled
    +>TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 - ConfigIncluded:NotSelected
    +>TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected
    +>TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected JVM:disabled
    +>TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected JVM:disabled
    +>TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 - ConfigIncluded:NotSelected JVM:disabled
    +>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 - ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_EMPTY_RENEGOTIATION_INFO_SCSV - ConfigIncluded:NotSelected
    +>TLS_FALLBACK_SCSV - ConfigIncluded:NotSelected JVM:disabled
    +>TLS_PSK_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected JVM:disabled
    +>TLS_PSK_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigIncluded:NotSelected JVM:disabled
    +>TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
    +>TLS_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'.*RSA.*', ConfigIncluded:NotSelected
key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined

**Comment by openron** [comment]
Meanwhile chrome browser shows (F12/Security tab)
Connection - secure (strong TLS 1.3)
The connection to this site is encrypted and authenticated using TLS 1.3 (a strong protocol), X25519 (a strong key exchange), and AES_128_GCM (a strong cipher).

**Comment by joakime** [comment]
Your Conscrypt setup has 2 Cipher Suites enabled.

```
+>Cipher Suite Selections
  +>Enabled size=2
  | +>TLS_AES_256_GCM_SHA384
  | +>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
```

Your OpenSSL setup has 4 Cipher Suites enabled.

```
+>Cipher Suite Selections
  +>Enabled size=4
  | +>TLS_AES_256_GCM_SHA384
  | +>TLS_CHACHA20_POLY1305_SHA256
  | +>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  | +>TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
```

Looks like there are no `CHACHA20` based cipher suites on conscrypt to even enable.

**Comment by openron** [comment]
Looks like, but it is enabled.
The AES_128 is enabled too at TLSv1.3.

(When i not use Conscrypt then the browser is not able to use chacha20 and x25519 named group.)

**Comment by readonlynetwork** [comment]
OpenSSL TLS 1.2 test, client code:` openssl s_client -tls1_2 -CAfile caCert.crt -cipher 'AES128' localhost:50443`

Result:
```
CONNECTED(00000003)
140484529013184:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1528:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 200 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1548858539
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

OpenSSL TLS 1.2 test2, client code: `openssl s_client -tls1_2 -CAfile caCert.crt -cipher 'AES256' localhost:50443`

Result:
```
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1481 bytes and written 293 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 384 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: C714897617B9C696AEFAF1B3FC7B8964ABFD5F5A890FDF79FA5F5A2660051E15
    Session-ID-ctx: 
    Master-Key: C920C21D1F2307F3A0F0CC2E6BD0483273EF7E82C362AD399CB7B5E34C78D7006847EC9F41B42EE68E4CE51DA81E3AD2
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1548858545
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```
