### ISSUE TITLE
Support host:port in X-Forwarded-For header in ForwardedRequestCustomizer

### ISSUE THREAD

**Issue by abarsov** [eclipse/jetty.project#3302]
The problem is that Azure load balancer adds `X-Forwarded-For` header in a form of `IP:port`.
And it is not configurable there. See related issues:
- https://feedback.azure.com/forums/217313-networking/suggestions/20220997-support-for-dropping-port-out-of-x-forwarded-for-h
- https://feedback.azure.com/forums/217313-networking/suggestions/33043528-azure-application-gateway-x-forwarded-for-remove-p

It would be great to support that format in ForwardedRequestCustomizer
(IP address should be additionally resolved from the value returned by getLeftMost() before assigning that to `forwardedFor`).  Something like that: https://github.com/pbojinov/request-ip/pull/30/commits/6b3cd1f3adb9d8ea839dd37d322442a4d140ae59

Note: 
- nginx has also supported IP:port in  X-Forwarded-For  since 1.11.0 (https://trac.nginx.org/nginx/ticket/1201)

**Comment by gregw** [comment]
@abarsov I agree that the `ForwardedRequestCustomizer` should have this ability.... should be moderately simple (other than avoiding confusing IPv6 addresses as `IP:port`).
We'll definitely do this... eventually.... or better yet, why not do it yourself and submit a pull request to hurry us along.

**Comment by gregw** [comment]
merged to 9.3, 9.4  and 10

**Comment by gregw** [comment]
thanks for the PR!
