### ISSUE TITLE
Update to jakarta ee javax artifacts for jetty-10

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3303]
The servlet-api and all ee apis have moved to the Eclipse Foundation. We should update jetty to use the new artifacts as published by the Eclipse Jakarta project as all development on the old javax apis has ceased.

**Comment by sbordet** [comment]
FTR, `org.eclipse.jetty.toolchain:jetty-servlet-api:4.0.2` is now based on `jakarta.servlet:jakarta.servlet-api:4.0.2`.
The latter still lacks `Automatic-Module-Name` and Servlet resources (XSDs, etc.) so we need our own for now.
Hopefully `jakarta.servlet-api:4.0.3` will have all we need and we can get rid of `jetty-servlet-api`.

**Comment by sbordet** [comment]
`jakarta.transaction:jakarta.transaction-api:1.3.2` has the right `Automatic-Module-Name`, so using that now.

**Comment by sbordet** [comment]
`jakarta.annotation:jakarta.annotation-api:1.3.4` is in use now.

**Comment by jmcc0nn3ll** [comment]
> FTR, `org.eclipse.jetty.toolchain:jetty-servlet-api:4.0.2` is now based on `jakarta.servlet:jakarta.servlet-api:4.0.2`.
> The latter still lacks `Automatic-Module-Name` and Servlet resources (XSDs, etc.) so we need our own for now.
> Hopefully `jakarta.servlet-api:4.0.3` will have all we need and we can get rid of `jetty-servlet-api`.

@gregw did this end up coming to pass?

**Comment by joakime** [comment]
``` shell
[joakim@hyperion ~]$ cd tmp

[joakim@hyperion tmp]$ curl -O https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/4.0.3/jakarta.servlet-api-4.0.3.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82872  100 82872    0     0   459k      0 --:--:-- --:--:-- --:--:--  459k

[joakim@hyperion tmp]$ jar -xvf jakarta.servlet-api-4.0.3.jar META-INF/MANIFEST.MF
 inflated: META-INF/MANIFEST.MF

[joakim@hyperion tmp]$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.
 org/software/classpath/license.html
Bundle-SymbolicName: jakarta.servlet-api
Archiver-Version: Plexus Archiver
Built-By: default
Bnd-LastModified: 1566398855350
Implementation-Vendor-Id: org.eclipse
Bundle-DocURL: https://www.eclipse.org
Import-Package: javax.servlet,javax.servlet.annotation,javax.servlet.d
 escriptor
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Export-Package: javax.servlet;uses:="javax.servlet.annotation,javax.se
 rvlet.descriptor";version="4.0.0",javax.servlet.annotation;uses:="jav
 ax.servlet";version="4.0.0",javax.servlet.descriptor;version="4.0.0",
 javax.servlet.http;uses:="javax.servlet";version="4.0.0"
Bundle-Name: Jakarta Servlet
Extension-Name: javax.servlet
Bundle-Description: Jakarta Servlet 4.0
Automatic-Module-Name: java.servlet
Implementation-Version: 4.0.3
Bundle-ManifestVersion: 2
Specification-Vendor: Eclipse Foundation
Bundle-Vendor: Eclipse Foundation
Tool: Bnd-4.0.0.201805111645
Implementation-Vendor: Eclipse Foundation
Bundle-Version: 4.0.0
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_202
Specification-Version: 4.0

[joakim@hyperion tmp]$ jar -tvf jakarta.servlet-api-4.0.3.jar | grep xsd

[joakim@hyperion tmp]$
```

That means version 4.0.3 has the `Automatic-Module-Name: java.servlet` (which is wrong IMO, it should have been `javax.servlet`)
And has no schemas.

**Comment by flozano** [comment]
> That means version 4.0.3 has the Automatic-Module-Name: java.servlet (which is wrong IMO, it should have been javax.servlet)

All modules that contain `javax.*` packages still are named as `java.*`.
Eg: java.transactions.xa, java.xml, java.sql.rowset, java.naming.

**Comment by janbartel** [comment]
This has been done for jetty-11.
