### ISSUE TITLE
Add JSR107 Implementation of CacheFilter

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#331]
migrated from Bugzilla [#438818](https://bugs.eclipse.org/bugs/show_bug.cgi?id=438818)
status ASSIGNED severity _normal_ in component _other_ for _9.2.x_
Reported in version _unspecified_ on platform _PC_
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[CacheFilter.java](https://bugs.eclipse.org/bugs//attachment.cgi?id=244777)_ (ID 244777)

On 2014-07-03 07:59:00 -0400, Thomas Meyer wrote:

> Created attachment 244777
> v1
> 
> Hi,
> 
> please have a look at this initial implementation of an JSR107 cache filter mechanism.
> 
> To use the filter in a webapp you must do these steps:
> 
> 1.) provide jsr107 api+implementation in WEB-INF/lib:
> cache-api-1.0.0.jar (jsr107 API)
> cache-ri-impl-1.0.1-SNAPSHOT.jar (jsr107 RI -> or any other implementation)
> 
> 2.) set jsr107 service provider in file 
>  "META-INF/services/javax.cache.spi.CachingProvider":
> org.jsr107.ri.spi.RICachingProvider (or any other implementation)
> 
> 3.) include filter in the web.xml file:
> 
> ```
> <filter>
>     <filter-name>jsr107filter</filter-name>
>     <filter-class>de.m3y3r.servlets.jsr107.CacheFilter</filter-class>
>     <async-supported>true</async-supported>
> </filter>
> 
> <filter-mapping>
>     <filter-name>jsr107filter</filter-name>
>     <servlet-name>cgi-servlet</servlet-name>
> </filter-mapping>
> ```
> 
> Also make sure to include the CacheFilter class in the classpath of your web app!
> 
> If you like it feel free to add it to the jetty servlets/filters.
> 
> Feedback is welcome.

On 2014-07-03 08:50:40 -0400, Greg Wilkins wrote:

> Hey Thomas,
> 
> thanks for the contribution!
> 
> The main feedback I have is that servlet 3.1 has basically broken filters that operate like this one.  They will work for blocking IO, but fail for async IO.
> 
> We are dealing with this issue in jetty-9 for GzipFilter by deprecating it and replacing it with AsyncGzipFilter.     I think the mechanism used by that filter can be cleaned up and used for a caching filter.
> 
> Do you have any test harnesses for the filter?
> 
> cheers

**Comment by joakime** [comment]
This should probably be changed to use the same pattern as [GzipHandler](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java) and its implementation of [HttpOutput.Interceptor](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java) called [GzipHttpOutputInterceptor](https://github.com/eclipse/jetty.project/blob/master/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java)

**Comment by joakime** [comment]
@gregw I think this one should be closed, its not going to happen with the default JSR107 in any current/stable version of Jetty anyway.
The JSR107 RI made sense back in the Jetty 7/8 days, not anymore.
