### ISSUE TITLE
Ability to serve HTTP and HTTPS from the same port

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3311]
This feature would be useful when migrating services from the `http` to the `https` scheme, and the migration process cannot atomically update all clients, and using more than 1 listening port may not be allowed.

The updated clients will use `https` schemes, but the old client would still use the `http` scheme.

**Comment by sbordet** [comment]
See also #1095.

**Comment by joakime** [comment]
The title of this issue seems off.

Wouldn't it be "Ability to return non-secure HTTP error response on HTTPS port" ?
