### ISSUE TITLE
Why jetty wants to protect WEB-INF and META-INF paths

### ISSUE THREAD

**Issue by 450839686** [eclipse/jetty.project#3316]
Why jetty wants to protect WEB-INF and META-INF paths. Is there any security issue? What is the specific problem?

        jetty.project/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
1323-1328 lines
                  if (isProtectedTarget(target))
                    {
                        response.sendError(HttpServletResponse.SC_NOT_FOUND);
                        baseRequest.setHandled(true);
                        return;
                    }

**Comment by sbordet** [comment]
Confirmed that this is required by the Servlet Specification.
