### ISSUE TITLE
Test code should use package org.eclipse.jetty.test

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3318]
We need to exclude some classes from the aggregated javadoc jar see #2878 
so we usually use package names but some test (test-sessions-common) use package org.eclipse.jetty.server.session and for this reason we cannot exclude it.

**Comment by olamy** [comment]
to review if everything has been fixed

**Comment by gregw** [comment]
Closing as fixed. @olamy please open a specific issue if there is more to do.
