### ISSUE TITLE
CGI: Apply resourceBase to SCRIPT_FILENAME and introduce an pathAlwaysValid parameter

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#332]
migrated from Bugzilla [#432468](https://bugs.eclipse.org/bugs/show_bug.cgi?id=432468)
status ASSIGNED severity _normal_ in component _other_ for _9.1.x_
Reported in version _9.1.4_ on platform _PC_
Assigned to: Simone Bordet

Original attachment names and IDs:
- _[CGI-fixes.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=241799)_ (ID 241799)
- _[web.xml](https://bugs.eclipse.org/bugs//attachment.cgi?id=241800)_ (ID 241800)
- _[Fix-scriptName-execCmd.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=241984)_ (ID 241984)

On 2014-04-09 16:39:24 -0400, Thomas Meyer wrote:

> Created attachment 241799
> Patch to CGI servlet
> 
> 1.) Apply resourceBase to SCRIPT_FILENAME
> This enables an wordpress install in another directory, e.g. /usr/share/wordpress
> 
> 2.) Introduce an pathAlwaysValid parameter
> This enable CGI servlet for cgi programs like cgit.

On 2014-04-09 16:41:15 -0400, Thomas Meyer wrote:

> Created attachment 241800
> example web.xml for cgit cgi script

On 2014-04-10 20:50:45 -0400, Greg Wilkins wrote:

> Thomas,
> 
> I have pushed a variation of you patch with commit 5a0811b to the master branch for inclusion in 9.2.0.
> 
> I changed some of the names to be more understandable and also wrote a bit better javadoc.   Can you confirm this still works for you.
> 
> Also, can you click on the CLA link besides your name in this bugzilla can complete the contributors agreement?
> 
> Simone,
> 
> can you review this for compatibility with the fast CGI servlet?
> 
> thanks

On 2014-04-14 18:38:20 -0400, Thomas Meyer wrote:

> Created attachment 241984
> Fix for cgit CGI
> 
> I'm not sure if this is the right thing to do, but this patch fixes the cgit CGI with attached web.xml.

**Comment by gregw** [comment]
will not implement
