### ISSUE TITLE
org_eclipse_jetty_setuid_SetUID.h is missing from jetty-setuid-native sources, hence building libsetuid-linux fails

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#333]
migrated from Bugzilla [#428870](https://bugs.eclipse.org/bugs/show_bug.cgi?id=428870)
status ASSIGNED severity *trivial* in component *other* for *9.1.x*
Reported in version *unspecified* on platform *PC*
Assigned to: Jesse McConnell

On 2014-02-24 03:35:28 -0500, Alexei Mikhailov wrote:

> /subj
> 
> To reproduce:
> * Clone/download jetty-toolchain either from Eclipse git repo (http://git.eclipse.org/c/jetty/org.eclipse.jetty.toolchain.git) or github mirror (https://github.com/eclipse/jetty.toolchain)
> * cd jetty-setuid
> * mvm clean install
> 
> Building libsetuid-linux will fail with:
> [INFO] --- native-maven-plugin:1.0-alpha-8:compile (default-compile) @ libsetuid-linux ---
> [INFO] /bin/sh -c cd /root/org.eclipse.jetty.toolchain/jetty-setuid/libsetuid-linux && gcc -fPIC -O -I/root/org.eclipse.jetty.toolchain/jetty-setuid/libsetuid-linux/target/generated -I/usr/lib/jvm/jdk1.7.0_45/jre/../include -I/usr/lib/jvm/jdk1.7.0_45/jre/../include/linux -o /root/org.eclipse.jetty.toolchain/jetty-setuid/libsetuid-linux/target/objs/org_eclipse_jetty_setuid_SetUID.o -c /root/org.eclipse.jetty.toolchain/jetty-setuid/libsetuid-linux/target/generated/org_eclipse_jetty_setuid_SetUID.c
> /root/org.eclipse.jetty.toolchain/jetty-setuid/libsetuid-linux/target/generated/org_eclipse_jetty_setuid_SetUID.c:20:45: fatal error: org_eclipse_jetty_setuid_SetUID.h: No such file or directory
> compilation terminated.
> 
> I have locally fixed this by finding a released libsetuid-linux-1.0.2-sources.jar, and placing org_eclipse_jetty_setuid_SetUID.h that it contains to jetty-setuid/jetty-setuid-native/src/main/resources/, which makes build go through.
> However I suspect that that header file should be in git repos.
> 
> Thanks!

**Comment by joakime** [comment]
Moved bug to eclipse/jetty.toolchain/issues/2
