### ISSUE TITLE
jetty-maven-plugin - transitive dependencies not loaded from "target/classes"

### ISSUE THREAD

**Issue by mironbalcerzak** [eclipse/jetty.project#3332]
Greeting,
Hope you are doing fine. I presume what I've encountered might be a bug in jetty-maven-plugin, but wanted to clarify first (because, maybe, I am missing some configuration here..?)

Long story short:
jetty-maven-plugin is missing "target/classes" while loading classes (plugin miss to load transitive dependencies from target/classes, even thought they are present in the maven structure - more on that can be seen in the sample project that I've created)

Here's the link:
https://github.com/mironbalcerzak/gist-jetty-maven-plugin-w-overlay

Hope to hear from you soon, and have a great day! :)

--- Miron Balcerzak

**Comment by janbartel** [comment]
@mironbalcerzak very thorough repro, thank you!

One problem I can see is that you should not use the jetty:run goal to bind to a phase. This is because it starts a parallel build to ensure that the webapp is built. The jetty:start goal is the goal that is designed to be bindable to a phase. See https://www.eclipse.org/jetty/documentation/9.4.14.v20181114/jetty-maven-plugin.html#jetty-start-goal.  I think I need to make that crystal clear in the doco on the jetty:run goal too.

**Comment by mironbalcerzak** [comment]
Thank you for getting back to me so soon @janbartel!

```Also, if you bind to a phase like deploy with jetty:start, it will start jetty jetty, but jetty will stop as soon as the deploy phase is over and the maven process exits. Usually the start goal would be bound to a phase like pre-integration-test and the stop goal bound to post-integration-test. So I'm not sure why you want to bind to a phase, especially one like deploy?```
It does not stop..it's working pretty well that way actually :) and I've bind it only for an ease of use in sample project (mvn deploy -Pxxx,yyy).

I've done some digging into jetty-maven-plugin and I am not totally convinced by the way dependencies are resolved.
There seem to be 2 issues:
1) When resolving single WAR (example: moduleA/B), only "first level" (only dependencies that are introduced to given WAR pom.xml ) are resolved to dependencies within the project - however, we can safely assume that those "first-level" dependencies may have dependencies as well - and we skip the search for those with current approach).
2) Different approach is taken for resolving dependencies (resources) within "lib" of WAR that is managed as overlay within "uberWAR" - which totally skips project scan.

If there is a problem I'd be happy to contribute to the project :)

**Comment by janbartel** [comment]
@mironbalcerzak looks to me like overlays are working as expected.  We do not do deep resolution of projects during the build:  we are looking at the _products_ of the builds of the dependent/overlaid wars.  So we unpack the dependent/overlaid built wars to the target directory and then use those locations during runtime.

Also, please see my comment that the jetty:run goal forks a separate build process: so you've got 1 build process from the mvn deploy command and another from the jetty:run goal.

**Comment by mironbalcerzak** [comment]
> Also, please see my comment that the jetty:run goal forks a separate build process: so you've got 1 build process from the mvn deploy command and another from the jetty:run goal.

@janbartel, I've reviewed the [jetty-maven-plugin.html#jetty-run-goal](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html#jetty-run-goal) paragraph and I miss the part regarding "forking" of the build... did you mean `jetty:run-forked` by any chance? 

> We do not do deep resolution of projects during the build: we are looking at the _products_ of the builds of the dependent/overlaid wars. So we unpack the dependent/overlaid built wars to the target directory and then use those locations during runtime`

True that - result's provided in a sample project. Is there a bigger reason for that?

It's massively limiting rapid development since classes are not hot swapped even if scanner is manually set to monitor them, and project (module) containing them is present in the reactor ("note" of jetty:run paragraph is advertising it should be possible).

Correct me if I am wrong but I presume jetty, during (re)deployment is doing loads of "magic" (keeping it simple :) ) around  classloaders and their hierarchy so there's no real reason why proper (=deep) dependency resolution is not taking place.
From what I could tell, resources from overlaid war (which are unpacked) are handled through abstraction (`org.eclipse.jetty.util.resource.Resource`) so - let's say - JARs that are present in `WEB-INF/lib` of overlay might be ignored, if given "lib" of same name and version is present in the reactor? (and `mavenProject.getBuild().getOutputDirectory()` is not empty?).
Same goes to libs of regular WAR (or uberWAR) [ webApp.setWebInfLib(getDependencyFiles())](https://github.com/eclipse/jetty.project/blob/9a25f2757e5737496d5ee7f621b22f2f8dfe6a1a/jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java#L287) - since both are configured in same place.

-- mb

**Comment by olamy** [comment]
@mironbalcerzak  this generate https://github.com/eclipse/jetty.project/issues/4699
