### ISSUE TITLE
Jetty 10 standalone cannot start on the module-path

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3333]
Since now Jetty 10 has proper `module-info.java`, when it is started in standalone mode, the only JPMS modules that are in the root are `org.eclipse.jetty.xml` and those specified by explicit `[jpms]` sections in `*.mod` files such as `org.objectweb.asm` and `java.instrument`.

With Jetty 9.4 and `Automatic-Module-Name`, the JPMS modules were automatically added to the module-path because the jars did not have an explicit `module-info.java`.

**Comment by sbordet** [comment]
@olamy is there a way to write an integration test that runs Jetty standalone on the module path and verifies that it starts a minimal configuration?

**Comment by sbordet** [comment]
A possible quick solution would be to add `--add-modules=ALL-MODULE-PATH`

**Comment by olamy** [comment]
How do I have to start Jetty to reproduce that?
From distro?
` java -jar start.jar ` ?

**Comment by sbordet** [comment]
@olamy yes a distro should start with:

`java -jar start.jar --jpms`

Have at least one web application deployed, make a request to verify it's working, then shutdown.

Is that possible?
If so, do it in `jetty-9.4.x` where it should work.
In `jetty-10.0.x` is broken for sure, until we merge #3168, so you may merge forward your test but `@Ignore` it.

**Comment by sbordet** [comment]
@olamy I pushed a fix in #3338. It would still need a test case.

**Comment by olamy** [comment]
possible? not exactly as i wish (but I have to finish the way of doing some distro testing...) 
Anyway I can do this with the current maven plugin...

**Comment by sbordet** [comment]
@olamy we really need to be able to test the distro: minimal startup, http, http2, jpms, websocket, jsp at least to be sure we have not broken anything.

If you can test the Jetty Maven Plugin we should be able to test also the distro, no?

**Comment by olamy** [comment]
https://github.com/eclipse/jetty.project/issues/3343
https://github.com/eclipse/jetty.project/pull/3344/
