### ISSUE TITLE
Update session tests to check classloading for serialization

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3337]
The tests we apply to each type of SessionDataStore currently don't require any serialization. However, we should update the tests to:

* ensure that a test object loadable only with the webapp classloader is stored in the session
* use a fresh thread when calling the SessionDataStore methods

Both of the above will ensure that we test that SessionDataStore methods handle anointing a calling thread with the context classloader before serializing/deserializing SessionData.

**Comment by olamy** [comment]
are we already doing that with profile `mongodb` (i.e remote mongodb instance) and hazelcast client mode (fixed with this commit https://github.com/eclipse/jetty.project/commit/63bb31f800bb23941152af884f1202c9fed47d58 )
Or I misunderstand something?

**Comment by janbartel** [comment]
@olamy these are separate unit tests of each SessionDataStore. Currently those tests don't involve any real classloading serialisation because the session is just storing mickey mouse string attributes.

**Comment by janbartel** [comment]
I've already made a branch and started work. I pushed it, but it won't fully compile yet.

**Comment by janbartel** [comment]
Merged to jetty-9.4.x
