### ISSUE TITLE
support parallel deployment (for continuous delivery)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#334]
migrated from Bugzilla [#422906](https://bugs.eclipse.org/bugs/show_bug.cgi?id=422906)
status ASSIGNED severity _enhancement_ in component _other_ for _9.1.x_
Reported in version _unspecified_ on platform _PC_
Assigned to: Jan Bartel

On 2013-12-01 12:22:20 -0500, Fabio Bonfante wrote:

> Tomcat has this particular useful feature when you've a single instance webapp and don't want any downtime while redeploying.
> 
> >    You may deploy multiple versions of a web application with the same context >path at the same time. The rules used to match requests to a context version are >as follows:
> > 
> > ```
> >    If no session information is present in the request, use the latest >version.
> >    If session information is present in the request, check the session >manager of each version for a matching session and if one is found, use that >version.
> >    If session information is present in the request but no matching session >can be found, use the latest version.
> > ```
> > 
> >    The Host may be configured (via the undeployOldVersions) to remove old >versions deployed in this way once they are no longer in use.
> 
> http://tomcat.apache.org/tomcat-7.0-doc/config/context.html#Parallel_deployment

On 2013-12-01 17:58:51 -0500, Jan Bartel wrote:

> Hi Fabio,
> 
> For information: its always been possible to deploy multiple webapps at the same context path & virtual host with jetty - only the first active one of them will receive traffic. If you stop the first active context, then the next will receive traffic. So there are never 2 contexts at the same path & virtual host combo serving requests at the same time.
> 
> I can't remember if we stop the context straight away so that requests that are in progress are disrupted, or if we prevent new requests from entering and then finish the shutdown once all requests have drained out ... I'll check in the code.
> 
> Jan

On 2013-12-01 18:37:14 -0500, Greg Wilkins wrote:

> Fabio,
> 
> it would not be very much effort at all to write a handler to do that kind of load balancing between two versions of a webapp.    To have a handler that does the logic you describe could be done in only a few hours work.   
> 
> The problem is more about how the deployer is to know if these are multiple versions of the same webapp and to set them up behind such a handler.  It will be difficult to come up with a really generic scheme that will work for most and be able to be included in a standard release.
> 
> For such enhancements, it is often good to work with a real user who has a real use-case so that we are not developing in the abstract.

**Comment by janbartel** [comment]
There's been no interest in this issue for years now, so I'm closing it.
