### ISSUE TITLE
Microsoft ASP.NET MS-DOS Device Name DoS found when doing security scan

### ISSUE THREAD

**Issue by miaofenk** [eclipse/jetty.project#3345]
Hi,

My embedded jetty web application is running on a CentOS VM and got a security issue when doing Nessus security scan. Following are the issue description:

> Microsoft ASP.NET MS-DOS Device Name DoS
> 
> Description
> 
> The web server running on the remote host appears to be using Microsoft ASP.NET, and may be affected by a denial of service vulnerability. Requesting a URL containing an MS-DOS device name can cause the web server to become temporarily unresponsive. An attacker could repeatedly request these URLs, resulting in a denial of service.
> 
> Additionally, there is speculation that this vulnerability could result in code execution if an attacker with physical access to the machine connects to a serial port.
> 
> Solution
> 
> Use an ISAPI filter to block requests for URLs with MS-DOS device names.
> 
> See Also
> 
> https://seclists.org/fulldisclosure/2007/May/378
> https://seclists.org/fulldisclosure/2007/May/415
> http://www.nessus.org/u?d32fbf50
> 
> Output
> 
> Nessus received an HTTP 500 or related error message by requesting
> the following URL :
> 
> http://10.76.62.30:8880/AUX/.aspx
> 
> Port Hosts
> 
> 8880 / tcp / www 10.76.62.30 (8880 is my jetty service port)

Actually, I have no idea about the security issue. I tried to google it but most of them are Windows platform related tickets.
Have you ever met the issue before? Do you have any ideas about how to resolve it?

Thanks!

**Comment by joakime** [comment]
Accessing `/AUX/` is a windows thing.
Accessing `/AUX/.aspx` is a ASP.net thing on Windows.

Neither should be relevant on CentOS running Jetty.

The error 500 received isn't due to the described / linked issues, but something else.

Testing on Jetty 9.4.14.20181113 we see the following ...

```
$ curl http://localhost:8080/AUX/.aspx
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /AUX/.aspx. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.14.v20181113</a><hr/>

</body>
</html>
```
```
$ curl http://localhost:8080/AUX
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /AUX. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.14.v20181113</a><hr/>

</body>
</html>
```
```
$ curl http://localhost:8080/AUX/
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /AUX/. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.14.v20181113</a><hr/>

</body>
</html>
```

What is the stacktrace for that error 500? (seen either on the server logs or the http response message)

**Comment by joakime** [comment]
Also note, we do have specific checks for users of Jetty on windows for various filesystem resource hacks.

https://github.com/eclipse/jetty.project/blob/c4550056e785fb5665914545889f21dc136ad9e6/jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java#L232-L234

https://github.com/eclipse/jetty.project/blob/c4550056e785fb5665914545889f21dc136ad9e6/jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java#L813-L821

https://github.com/eclipse/jetty.project/blob/c4550056e785fb5665914545889f21dc136ad9e6/jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java#L858-L868

https://github.com/eclipse/jetty.project/blob/c4550056e785fb5665914545889f21dc136ad9e6/jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java#L905-L913

**Comment by miaofenk** [comment]
Thanks for your quick response.

I'm using Jetty 9.4.12.v20180830 and I start a default servlet to handle all the URLs that not as expected.

`       final ServletHolder defaultServlet = new ServletHolder(new DefaultServlet());
        context.addServlet(defaultServlet, "/*");`

The stacktrace when receiving the 500 internal error is as follow:

> java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getStatus()I
> 	at org.eclipse.jetty.server.handler.ErrorHandler.doError(ErrorHandler.java:142)
> 	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:78)
> 	at org.eclipse.jetty.server.Response.sendError(Response.java:655)
> 	at org.eclipse.jetty.server.Response.sendError(Response.java:590)
> 	at org.eclipse.jetty.server.ResourceService.notFound(ResourceService.java:465)
> 	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:246)
> 	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:459)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:503)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
> 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
> 	at java.lang.Thread.run(Thread.java:748)

I'm not sure if I use it the right way.

**Comment by sbordet** [comment]
You have a `NoSuchMethodError` for `HttpServletResponse.getStatus()`, which means that you are missing the Servlet jar from your classpath.

Closing as this is not a Jetty issue.

**Comment by joakime** [comment]
You are either missing the servlet JAR in your embedded-jetty classpath, OR you have the wrong one.

For Jetty 9.4.x you would need Servlet 3.1 API Jar.
