### ISSUE TITLE
duplicate http status code constants in org.eclipse.jetty.http.HttpStatus to provide a more convenient auto-completion lookup (improvement)

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#335]
migrated from Bugzilla [#403974](https://bugs.eclipse.org/bugs/show_bug.cgi?id=403974)
status ASSIGNED severity *normal* in component *other* for *9.0.x*
Reported in version *unspecified* on platform *All*
Assigned to: Project Inbox

On 2013-03-21 01:35:25 -0400, Mark S. wrote:

> I use the jetty-http package's http status code constants because there is javadoc in maven and they contain the actual numbers. For a more convenient auto-completion lookup when starting out with the number, it would be great to have the constants named the other way round, maybe in addition to the existing name+number method. Example:
> HttpStatus.INTERNAL_SERVER_ERROR_500 -> HttpStatus.500_INTERNAL_SERVER_ERROR
> That way the autocompletion provided by the average IDE can also give an overview over all 4XX status code just by entering "4".

On 2013-03-21 18:24:17 -0400, Greg Wilkins wrote:

> I tend to agree that with hind sight they should have been called
> 
> SC_500_INTERNAL_SERVER_ERROR
> 
> 
> But now that jetty-9 is released, I'm loath to change the API and break other peoples code that also might be using them.
> 
> So good idea, but wont fix for now.

On 2013-03-21 18:24:50 -0400, Greg Wilkins wrote:

> Ah I see you are suggesting duplicating them.....
> 
> hmmm reopening and will thing about it.

**Comment by gregw** [comment]
Closing. It is an OK idea, but the squeaky wheel didn't squeak enough :)
