### ISSUE TITLE
Do not expect to be able to connect to https URLs with the HttpClient created from a parameterless constructor

### ISSUE THREAD

**Issue by alexamies** [eclipse/jetty.project#3350]
The [Jetty Client doc](https://www.eclipse.org/jetty/documentation/9.4.14.v20181114/http-client.html) states, "When you create a HttpClient instance using the parameterless constructor, you will only be able to perform plain HTTP requests and you will not be able to perform HTTPS requests." However, I found that on my Linux VM, that is not the case, in [my test app](https://gist.github.com/alexamies/4ba13b6a8e6d1c820d7fe56234f7fa89) the Jetty client with parameterless constructor,successfully connects to a https URL. On my MacBook, the Jetty client cannot connect to the URL, as expected. The linked Gist gives detailed instructions on how to reproduce the issue.

Linix environment:
$java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Sample code:
``` java
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.api.ContentResponse;

/**
 * Excercise the Jetty HttpClient
 */
public class HttpClientApp  {

  public int sendRequest() throws Exception {
    System.out.println("Sending request");
    HttpClient httpClient = new HttpClient();
    httpClient.start();
    // Do not expect to be able to connect to a https URL with the parameterless
    // HttpClient() constructor
    ContentResponse response = httpClient.GET("https://opencensus.io/community");
    return response.getStatus();
  }

  public static void main( String[] args ) {
    HttpClientApp app = new HttpClientApp();
    try {
      app.sendRequest();
    } catch(Exception e) {
        e.printStackTrace();
    }
  }
}
```

**Comment by joakime** [comment]
What version of the Jetty HttpClient are you using?

**Comment by alexamies** [comment]
9.4.14.v20181114

**Comment by sbordet** [comment]
@alexamies thanks for reporting this regression!
