### ISSUE TITLE
occasional NPE in org.eclipse.jetty.server.Server on Linux platform

### ISSUE THREAD

**Issue by pkcs11newbie** [eclipse/jetty.project#3353]
Hello

We have jetty embedded server application serving http and http endpoints and occasionally I run into below NPE in jetty server serving https endpoint on Linux platform only at the time of server startup:
![image](https://user-images.githubusercontent.com/30663103/52661222-2ecbf980-2ec7-11e9-96db-761a3bfc6831.png)

In the event when the jetty based https server starts up fine, I see below:
file:./config/jetty-admin/jetty.xml
file:./config/jetty-admin/jetty-threadpool.xml
file:./config/jetty-admin/jetty-jmx.xml
file:./config/jetty-admin/jetty-ssl.xml
file:./config/jetty-admin/jetty-ssl-context.xml
file:./config/jetty-admin/jetty-https.xml
file:./config/jetty-admin/jetty-stats.xml
2019-02-12 10:42:25.668:INFO:oejs.Server:main: jetty-9.4.12.v20180830; built: 2019-01-17T21:28:29.611Z; git: unknown; jvm 1.8.0_102-b14
2019-02-12 10:42:25.686:INFO:oejs.session:main: DefaultSessionIdManager workerName=
2019-02-12 10:42:25.686:INFO:oejs.session:main:  Scavenging every 660000ms

Additional Info: 
In our codebase, we have maintained below jetty files ordering prior to handing off to KeyManagerHttpServerLifeCycleXmlLoader class.
        list.add(new URL("file", "", path + separator + "jetty.xml"));
        list.add(new URL("file", "", path + separator + "jetty-threadpool.xml"));
        list.add(new URL("file", "", path + separator + "jetty-jmx.xml"));
        list.add(new URL("file", "", path + separator + "jetty-ssl.xml"));
        list.add(new URL("file", "", path + separator + "jetty-ssl-context.xml")); 
        list.add(new URL("file", "", path + separator + "jetty-https.xml"));
        list.add(new URL("file", "", path + separator + "jetty-stats.xml"));

In below code, configuration.configure() for jetty.xml throws InvocationTargetException, the cause for it being NPE.
   public KeyManagerHttpServerLifeCycleXmlLoader(String[] strXmlsContent, URL[] urlXmls, InputStream[] isXmls)
   {
      int totalXmls = strXmlsContent == null ? 0 : strXmlsContent.length;
      totalXmls += urlXmls == null ? 0 : urlXmls.length;
      totalXmls += isXmls == null ? 0 : isXmls.length;

      if (totalXmls == 0)
      {
         throw new NullPointerException("Jetty configuration can't be empty.");
      }

      Object[] xmls = new Object[totalXmls];
      int pos = 0;
      if (strXmlsContent != null && strXmlsContent.length > 0)
      {
         System.arraycopy(strXmlsContent, 0, xmls, pos, strXmlsContent.length);
         pos += strXmlsContent.length;
      }
      if (urlXmls != null && urlXmls.length > 0)
      {
         System.arraycopy(urlXmls, 0, xmls, pos, urlXmls.length);
         pos += urlXmls.length;
      }
      if (isXmls != null && isXmls.length > 0)
      {
         System.arraycopy(isXmls, 0, xmls, pos, isXmls.length);
         pos += isXmls.length;
      }

      Properties properties = new Properties();
      // Add System Properties
      Enumeration<?> ensysprop = System.getProperties().propertyNames();
      while (ensysprop.hasMoreElements())
      {
         String name = (String) ensysprop.nextElement();
         properties.put(name, System.getProperty(name));
      }

      try
      {
         XmlConfiguration lastXmlConfig = null;
         Object[] objects = new Object[totalXmls];

         // load all strXmls
         for (int i = 0; i < totalXmls; i++)
         {
             Object tmp = xmls[i];
             XmlConfiguration configuration = null;
             if (tmp instanceof String)
             {
                 configuration = new XmlConfiguration((String) tmp);
             }
             else if (tmp instanceof URL)
             {
                 configuration = new XmlConfiguration((URL) tmp);
                 System.out.println( ((URL)tmp).toString() );
             }
             else if (tmp instanceof InputStream)
             {
                 configuration = new XmlConfiguration((InputStream) tmp);
             }
             if ( configuration != null )
             {

                 if (lastXmlConfig != null)
                 {
                     configuration.getIdMap().putAll(lastXmlConfig.getIdMap());
                 }
                 if (properties.size() > 0)
                 {
                     Map<String, String> props = new HashMap<String, String>();
                     for ( Entry<Object, Object> entry : properties.entrySet() )
                     {
                         props.put( entry.getKey().toString(), String.valueOf(entry.getValue()) );
                     }
                     configuration.getProperties().putAll(props);
                     objects[i] = configuration.configure();
                     lastXmlConfig = configuration;
                 }
             }
         }

         for (Object object : objects)
         {
            if (object instanceof LifeCycle)
            {
               lifeCycles.add((LifeCycle) object);
            }
         }
      }
      catch (Exception ex)
      {
         if( ex instanceof java.lang.reflect.InvocationTargetException )
         {
             throw new RuntimeException( ex.getCause() );
         }         
    	 if (ex instanceof RuntimeException)
         {
            throw (RuntimeException) ex;
         }
         else
         {
            throw new RuntimeException(ex);
         }
      }
   }
   
 Linux machine configuration:
        PLATFORM        = x86_64
        MODEL           = Virtual Platform
        PROCESSORS      = 4
        EFFECTIVE CPUs  = 8
        CLOCK SPEED     =
        TOTAL MEMORY    = 7 GB

        OSVERSION       = LNX:CentOS Linux release 7.0.1406 (Core) 3.10.0-123.el7.x86_64
        KERNEL PATCH    = 3.10.0-123.el7.x86_64
        COMPILERS       = gcc-4.8.2-16.el7.x86_64

Attaching jetty.xml for reference:
[jetty_xml.log](https://github.com/eclipse/jetty.project/files/2857288/jetty_xml.log)

Please let me know if I'm missing anything. Any help greatly appreciated..

Thanks..

**Comment by sbordet** [comment]
At `Server.java:124`, where you get the `NullPointerException`, the code reads:

```java
120  public Server(@Name("address")InetSocketAddress addr)
121  {
122      this((ThreadPool)null);
123      ServerConnector connector=new ServerConnector(this);
124      connector.setHost(addr.getHostName());
125      connector.setPort(addr.getPort());
126      setConnectors(new Connector[]{connector});
127  }
```

That means you are passing `null` as the `InetSocketAddress`.

**Comment by joakime** [comment]
Also, the order of your XML is invalid.

```
ist.add(new URL("file", "", path + separator + "jetty.xml"));
list.add(new URL("file", "", path + separator + "jetty-threadpool.xml"));
list.add(new URL("file", "", path + separator + "jetty-jmx.xml"));
list.add(new URL("file", "", path + separator + "jetty-ssl.xml"));
list.add(new URL("file", "", path + separator + "jetty-ssl-context.xml"));
list.add(new URL("file", "", path + separator + "jetty-https.xml"));
list.add(new URL("file", "", path + separator + "jetty-stats.xml"));
```

If those are copies of the XML from the `jetty-home` artifact, then you have the order incorrect.
Eg: `jetty-threadpool.xml` would never be AFTER the `jetty.xml`

Example:

```
[joakim@Rhea ~]$ cd Code/Jetty/distros/bases/
[joakim@Rhea bases]$ mkdir issue3353-base
[joakim@Rhea bases]$ cd issue3353-base/
[joakim@Rhea issue3353-base]$ java -jar ../../jetty-home-9.4.14.v20181113/start.jar --add-to-start=https,stats,jmx
INFO  : server          transitively enabled, ini template available with --add-to-start=server
INFO  : jmx             initialized in ${jetty.base}/start.ini
INFO  : stats           initialized in ${jetty.base}/start.ini
INFO  : https           initialized in ${jetty.base}/start.ini
INFO  : ssl             transitively enabled, ini template available with --add-to-start=ssl
INFO  : threadpool      transitively enabled, ini template available with --add-to-start=threadpool
MKDIR : ${jetty.base}/etc
COPY  : ${jetty.home}/modules/ssl/keystore to ${jetty.base}/etc/keystore
INFO  : Base directory was modified
[joakim@Rhea issue3353-base]$ java -jar ../../jetty-home-9.4.14.v20181113/start.jar --list-config

...(snip lots of output)...

Jetty Active XMLs:
------------------
 ${jetty.home}/etc/jetty-threadpool.xml
 ${jetty.home}/etc/jetty.xml
 ${jetty.home}/etc/jetty-ssl.xml
 ${jetty.home}/etc/jetty-ssl-context.xml
 ${jetty.home}/etc/jetty-https.xml
 ${jetty.home}/etc/jetty-jmx.xml
 ${jetty.home}/etc/jetty-stats.xml
```

**Comment by pkcs11newbie** [comment]
Thank you all..

So, I'm guessing the order of the jetty files is possibly why I may be getting intermittent NPE issue on linux?  
Sorry, I couldn't quite find definite information as to the ordering  of the files. I based it of https://www.eclipse.org/jetty/documentation/9.4.x/embedding-jetty.html -> Like Jetty XML

**Comment by joakime** [comment]
The XML you find in the `jetty-home` artifact is ordered by the `jetty-start` artifact.
The order is determined by what modules you have enabled, and their resolved directed acyclic graph.
The modules themselves only mention what they need and what they depend on, the rest is calculated.
