### ISSUE TITLE
websocket client earlyEOF when doing Upgrade

### ISSUE THREAD

**Issue by mmitkevich** [eclipse/jetty.project#3355]
I'm getting earlyEOF on Upgrade request when connecting from jetty. I have no such problem when connecting with curl, so I consider it jetty bug.

Consider this script:
```
     curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: real.idcm.io:10030" \
     --header "Origin: http://real.idcm.io:10030/websocket" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     https://real.idcm.io:10030/websocket 
```
It prints
```
Mikhails-MacBook-Pro:idcm-gateway mike$ ./test-ws-success.sh 
HTTP/1.1 101 Switching Protocols
Server: websocket-sharp/1.0
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
```

So basically websocket upgrade was successfull. I want to note here that server seems to be very slow and responds only after 1-2 seconds timeout which is visible even with curl.

When connecting with jetty I've got `read==-1` here
```
HttpReceiverOverHttp.process() {
...
           if (parse())
                    return;

                int read = endPoint.fill(buffer); ///// ---> returns -1 here: no data
                if (LOG.isDebugEnabled())
                    LOG.debug("Read {} bytes {} from {}", read, BufferUtil.toDetailString(buffer), endPoint);

                if (read > 0)
                {
                    connection.addBytesIn(read);
                    if (parse())
                        return;
                }
                else if (read == 0)
                {
                    releaseBuffer();
                    fillInterested();
                    return;
                }
                else
                {
                    releaseBuffer();
                    shutdown(); // fails the connection with EOFException
                    return;
                }
```
Here is screenshot:

![image](https://user-images.githubusercontent.com/3052367/52693540-03edae00-2f78-11e9-9fb9-0515ec7a3f40.png)
```
earlyEOF:333, HttpReceiverOverHTTP (org.eclipse.jetty.client.http)
parseNext:1551, HttpParser (org.eclipse.jetty.http)
shutdown:209, HttpReceiverOverHTTP (org.eclipse.jetty.client.http)
process:147, HttpReceiverOverHTTP (org.eclipse.jetty.client.http)
receive:73, HttpReceiverOverHTTP (org.eclipse.jetty.client.http)
receive:133, HttpChannelOverHTTP (org.eclipse.jetty.client.http)
onFillable:155, HttpConnectionOverHTTP (org.eclipse.jetty.client.http)
succeeded:305, AbstractConnection$ReadCallback (org.eclipse.jetty.io)
fillable:103, FillInterest (org.eclipse.jetty.io)
onFillable:411, SslConnection$DecryptedEndPoint (org.eclipse.jetty.io.ssl)
onFillable:305, SslConnection (org.eclipse.jetty.io.ssl)
succeeded:159, SslConnection$2 (org.eclipse.jetty.io.ssl)
fillable:103, FillInterest (org.eclipse.jetty.io)
run:118, ChannelEndPoint$2 (org.eclipse.jetty.io)
runJob:765, QueuedThreadPool (org.eclipse.jetty.util.thread)
run:683, QueuedThreadPool$2 (org.eclipse.jetty.util.thread)
run:748, Thread (java.lang)
```

It looks like jetty can't wait for Upgrade response too much. When it receives empty frame it shuts down the connection. But (probably) the Upgrade response could come later so it is worth not closing here? What exactly does read==-1 mean? Is it connection closed by server?

Here is wireshark screenshot and dump
[ws_dump.txt](https://github.com/eclipse/jetty.project/files/2859255/ws_dump.txt)

![image](https://user-images.githubusercontent.com/3052367/52694025-7d39d080-2f79-11e9-8151-6305ae082eac.png)

I see FIN sent by client (192.168.1.178) to the server (80.240.29.222). It happens BEFORE shutdown() is called on stack frame above (I had a breakpoint there)

Also I see some TLS v. 1.2 Alert. Probably it could be consequence of some SSL/TLS problem But I have no clue as for now...

I would appreciate any feedback. Thanks.

**Comment by sbordet** [comment]
There are multiple issues here.

First of all, if you are doing a clear-text upgrade, and the client reads -1, that means the connection has been closed by the server.
This is a bad server behavior, as we have just upgraded in order to use another protocol and the server can't just close the connection (well it can, but then we cannot communicate).

The wireshark dump shows a different thing: it shows your client cannot even talk TLS to the server, as the client sends the `ClientHello` and the server replies by closing the connection.
You need to look at the server logs to understand why the server did not like the `ClientHello`.

**Comment by mmitkevich** [comment]
Thanks for your prompt reply, @sbordet. This TLS insight is very helpful. I collected wireshark from curl and it seems that TLS 1.2 isn't properly supported by the server, while TLS 1 is OK:

![image](https://user-images.githubusercontent.com/3052367/52699227-546c0800-2f86-11e9-8386-c21a8a443d75.png)

 Could you kindly help me is there any possibility to force using TLS v.1 instead of TLS v. 1.2 in Jetty WS client?

**Comment by sbordet** [comment]
```java
SslContextFactory sslContextFactory = new SslContextFactory();
sslContextFactory.setIncludeProtocols("TLSv1");
HttpClient httpClient = new HttpClient(sslContextFactory);
WebSocketClient wsClient = new WebSocketClient(httpClient);
wsClient.start();
```

**Comment by mmitkevich** [comment]
Thanks, it finally worked but only after I added
```
sslContextFactory.setExcludeCipherSuites();
```
as described in https://stackoverflow.com/questions/52565445/tlsv1-support-in-embedded-jetty-server. Not sure what it means but probably it would help somebody in the future.

**Comment by sbordet** [comment]
`SslContextFactory` by default excludes weak and broken cipher suites.
Calling `sslContextFactory.setExcludeCipherSuites()` will exclude none, thus making them all available (including weak and broken), which is probably necessary for TLSv1 to work.

**Comment by joakime** [comment]
> ``` java
> sslContextFactory.setIncludeProtocols("TLSv1");
> ```

Note that even the above snippet will not work on newer JVMs as TLS/1.0 and TLS/1.1 are disabled at the JVM level for being insecure.
