### ISSUE TITLE
Handle websocket error for twice in WebsocketUpgradeRequest.java

### ISSUE THREAD

**Issue by lanlvyip** [eclipse/jetty.project#3358]
Hi Jetty team,

When result fail and responseStatusCode is not 101, onWebsocketError will be called twice.

On Websocket Client (9.4.14) side, I make a websocket class implement from WebSocketListerner, and use WebsocketClient to create WebsocketSession.

On Websocket Server side, it is also using Jetty javax-websocket-server-impl, websocket-api, websocket-servlet with 9.4.14 and javax.servlet-api 4.0.1 (Running in linux)

When I do upgrade on Websocket Server, Websocket Client side will jump into onWebsocketError twice:
By checking the code, on the first websocket error, after finish the whole function onWebsocketError, it goes to https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java#L517, and then in the checking of  responseStatusCode, it throws exception from https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java#L524 and the jump to onWebsocketError again.

**Comment by joakime** [comment]
Taken care of in PR #3315
