### ISSUE TITLE
Port HTAccessHandler from jetty-6

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#336]
migrated from Bugzilla [#396567](https://bugs.eclipse.org/bugs/show_bug.cgi?id=396567)
status ASSIGNED severity _enhancement_ in component _other_ for _7.6.x_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2012-12-13 23:05:01 -0500, Jan Bartel wrote:

> This issue has been moved from jetty codehaus jira: http://jira.codehaus.org/browse/JETTY-1239

**Comment by joakime** [comment]
This is the old code from Jetty 6, if anyone wants to take a stab and updating it for Jetty 9.3+

https://github.com/jetty-project/codehaus-jetty6/blob/master/modules/jetty/src/main/java/org/mortbay/jetty/security/HTAccessHandler.java

**Comment by gregw** [comment]
will not implement
