### ISSUE TITLE
HandlerCollection.addHandler is lacking synchronization

### ISSUE THREAD

**Issue by axeluhl** [eclipse/jetty.project#3361]
We're running Jetty 9.4.8 in an Equinox OSGi environment and deploy several web bundles as auto-start bundles. Equinox activates those bundles in parallel threads. We encounter race conditions in HandlerCollection.addHandler(Handler). We were able to prove by adding corresponding log statements that such race conditions can occur:

     public void addHandler(Handler handler)
     {
         System.out.println("Handler: " + handler);
         Handler[] addToArray = ArrayUtil.addToArray(getHandlers(), handler, Handler.class);
         System.out.println("Handlers: " + Arrays.toString(addToArray));
         setHandlers(addToArray);
     }

With this we get the following output:

Handler: 
o.e.j.w.WebAppContext@bbca5a5{/security,null,UNAVAILABLE}{file:/C:/data/projects/e-sap-sailing/repository/java/com.sap.sse.security/}
Handler: 
o.e.j.w.WebAppContext@2b09cb99{/igtimi,null,UNAVAILABLE}{file:/C:/data/projects/e-sap-sailing/repository/java/com.sap.sailing.domain.igtimiadapter.gateway/}
Handlers: 
[o.e.j.w.WebAppContext@bbca5a5{/security,null,UNAVAILABLE}{file:/C:/data/projects/e-sap-sailing/repository/java/com.sap.sse.security/}]
Handlers: 
[o.e.j.w.WebAppContext@2b09cb99{/igtimi,null,UNAVAILABLE}{file:/C:/data/projects/e-sap-sailing/repository/java/com.sap.sailing.domain.igtimiadapter.gateway/}]

Observe how two calls are being logged, but eventually only one handler ends up in the _handlers array. This seems obvious as addHandlers undertakes nothing to synchronize concurrent calls.

A patch should be easy to provide and should include prependHandler and removeHandler in the synchronization efforts as well.

**Comment by joakime** [comment]
HandlerCollection isn't meant to be used in a concurrent fashion. 
It's meant to be initialized before you use it, before any of the entries are started, and before the server is started.
Once started it's generally immutable (in a default configuration).

Perhaps your implementation should have it's own collection to add those bundles to, once all are found, a single call to `HandlerCollection(Handler[])` or `HandlerCollection.setHandlers(Handler[])` is more appropriate.  Consider doing this before you call `server.start()`.

Or you can flip this on its head and use the `DeploymentManager` with an OSGi specific `AppProvider` (like the [`jetty-osgi-boot`](https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-osgi/jetty-osgi-boot) project shows) targeting bundles and services automatically and properly

**Comment by axeluhl** [comment]
joakime, we're only using Equinox + Jetty and register web bundles. I don't think we should be facing these issues. It's a fact that OSGi launches bundles concurrently, using multiple threads. If Jetty wants to play with this then it better be thread-safe in such a central area.

**Comment by sbordet** [comment]
@gregw I think this is something you should look at.

**Comment by gregw** [comment]
Yes I think this is a problem.   We did not synchronize those methods because we don't want that handler to be used as a hot plugable collection (we have other handlers for that).  However, we didn't consider that multiple threads might be configuring the collection at the same time.

**Comment by gregw** [comment]
@axeluhl can you add a `new Throwable().printStackTrace()` to your modified addHandler (or setHandlers) method and paste the stack trace here so I can verify the calling path that you are experiencing.

**Comment by gregw** [comment]
I can see a similar problem in ContextHandlerCollection.  There we allow hot modification of contexts by building always processing the context path mappings into a new Trie, which we then set on a volatile field, essentially making the mapping copy on write semantics.    However, we again don't protect from multiple threads simultaneously changing/processing the mappings.

So I think synchronisation of the mutating methods with a copy-on-write semantic volatile to pass the results to the field accessed by handle is probably best for both ContextHandlerCollection and HandlerCollection

**Comment by joakime** [comment]
@gregw opened PR #3372 to address this

**Comment by janbartel** [comment]
@axeluhl  can you confirm if you are using the jetty-osgi-boot bundle to deploy your webapp bundles, or do you have custom code to do it?

**Comment by axeluhl** [comment]
Yes, we're using org.eclipse.jetty.osgi.boot (currently in version 9.4.8v20171121).

My personal take is that it will be sufficient to synchronize the read-update-write cycles and that the read of the _handlers field won't need synchronization. This is how we safe-guarded this in subclasses of the handler collections in question which we then use in our Jetty configuration. Works beautifully :-)

**Comment by axeluhl** [comment]
#3361 solved this. Closing
