### ISSUE TITLE
TLSv1.2/h2: Can't connect with cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256

### ISSUE THREAD

**Issue by mpfau** [eclipse/jetty.project#3369]
When using a jetty client and a jetty server, I can't connect to the server when using TLSv1.2 with h2 and the cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256.

However, connecting is possible with http1.1 or a different cipher suite.

**Comment by sbordet** [comment]
This is one of the ciphers that is forbidden by the HTTP/2 protocol.
https://tools.ietf.org/html/rfc7540#appendix-A

**Comment by mpfau** [comment]
@sbordet sorry my fault! However, it would be nice if the client would throw something meaningful (currently `java.io.IOException: Broken pipe`).

**Comment by sbordet** [comment]
The client implementation cannot do much. 
You have configured the client with the wrong cipher, which arrives at the server, which chokes on it. 
The server replies with a `close_notify`, and the client reports that.
There is no specific TLS message for "I cannot accept your cipher for this protocol".
