### ISSUE TITLE
CGI Servlets should be able to flush their output

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#337]
migrated from Bugzilla [#396563](https://bugs.eclipse.org/bugs/show_bug.cgi?id=396563)
status ASSIGNED severity _enhancement_ in component _other_ for _7.6.x_
Reported in version _unspecified_ on platform _All_
Assigned to: Simone Bordet

On 2012-12-13 22:25:51 -0500, Jan Bartel wrote:

> This issue was moved from jetty codehaus jira: http://jira.codehaus.org/browse/JETTY-930

**Comment by sbordet** [comment]
This issue lost context since it was referring to CodeHaus, closing.
