### ISSUE TITLE
JSR356 RemoteEndpoint.Async.setSendTimeout() logic invalid in Jetty 10.0.x

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3374]
Current implementation does ...

https://github.com/eclipse/jetty.project/blob/a76e25e3ebebc84f0f87ef8b72fbea5aabd33edf/jetty-websocket/javax-websocket-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketAsyncRemote.java#L57-L61

This is invalid, if you have a busy read, this will not work.
The send only should timeout here.

**Comment by joakime** [comment]
Issue #847 might be related

**Comment by lachlan-roberts** [comment]
this is also currently unimplemented in in 9.4.x
[JsrAsyncRemote](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/JsrAsyncRemote.java)

in jetty-10.0.x there is also  `JavaxWebSocketContainer.setAsyncSendTimeout()` which doesn't seem to be wired up to anything

**Comment by lachlan-roberts** [comment]
`RemoteEndpoint.Async.setSendTimeout()` has now been implemented in jetty-10 with the new WebSocket write timeout

https://github.com/eclipse/jetty.project/blob/90e849af76eb1977b43c05f28cbd4734f7597fb8/jetty-websocket/javax-websocket-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketAsyncRemote.java#L56-L60
