### ISSUE TITLE
Tracking of WebSocket Sessions in WebSocket containers

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3379]
In Jetty 9.x all open sessions are tracked for when the container (client or server) is stopped via the Jetty lifecycle.
This is used by both Jetty WebSockets and Javax WebSockets to gracefully close all open connections when the container stops (this is tracked in issue #3375)

This tracking is also used by Jetty WebSocket API and Javax WebSocket API to return the list of open sessions via the `session.getOpenSessions()` API.

**Comment by joakime** [comment]
In a conversation with @sbordet the tracking shouldn't be accomplished via raw `ContainerLifeCycle.addBean()` as this can be problematic with large collections.
The past issue about this in HTTP2 resulted in a new collection object being tracked as a LifeCycle child on the containers lifecycle with the individual HTTP2 sessions being just entries on this special purpose collection object.
The implementation in Jetty 9 should move to this collection object, and the implementation in Jetty 10 should provide the same functionality.

**Comment by joakime** [comment]
In Jetty 9.4.x there is a WebSocketSessionListener that is used to handle the add/remove of sessions to this collection.
Issue #3378 was created to add this listener back to the Jetty 10 implementation.

**Comment by sbordet** [comment]
HTTP2 equivalent was reported in #2828.

**Comment by joakime** [comment]
Opened PR #3383

**Comment by gregw** [comment]
Can you explain why this is needed? The managed selector would already close we connections on stop?

**Comment by joakime** [comment]
First is to support `session.getOpenSessions()`

Then there's the tear down at the Session level, along with the application notification requirements.
Not sure closing via the managed selector is sufficient here.

Then there's the ability to hook into the Session activity via listeners (something people have asked for).
Then there's also the graceful shutdown that others have asked for.

These features exist on Jetty 9.4.x currently btw.
This issue is for Jetty 10.0.x

**Comment by joakime** [comment]
Completed, and merged.

**Comment by borowskimarcin** [comment]
Hey, I got an issue with the sessionTracker, could you look at the: https://github.com/jetty/jetty.project/issues/14328 ?
