### ISSUE TITLE
Make <contextHandlers> able to configure nested <contextHandlers> that have nesting

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#338]
migrated from Bugzilla [#396154](https://bugs.eclipse.org/bugs/show_bug.cgi?id=396154)
status ASSIGNED severity _enhancement_ in component _ant_ for _7.6.x_
Reported in version _9.0.0_ on platform _All_
Assigned to: Jan Bartel

On 2012-12-10 01:43:44 -0500, Jan Bartel wrote:

> The <contextHandlers> element can have nested <contextHandler> elements, however the org.eclipse.jetty.server.ContextHandler only has a setHandler(Handler) method, and therefore Ant won't allow a <contextHandler> to have a nested <handler> element, it insists on converting it to a handler attribute instead. 
> 
> This means that you cannot have a ContextHandler with a nested ResourceHandler, which is a common occurrence.
> 
> The workaround is to define these other handlers in a jetty.xml and apply that.

**Comment by gregw** [comment]
will not implement
