### ISSUE TITLE
Make ant plugin <requestLog> configure the location of the logfile

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#339]
migrated from Bugzilla [#396153](https://bugs.eclipse.org/bugs/show_bug.cgi?id=396153)
status ASSIGNED severity _enhancement_ in component _ant_ for _7.6.x_
Reported in version _9.0.0_ on platform _All_
Assigned to: Jan Bartel

On 2012-12-10 01:40:59 -0500, Jan Bartel wrote nothing.

**Comment by janbartel** [comment]
The ant plugin is not being actively maintained and will likely be dropped from future releases.
