### ISSUE TITLE
java.security.acl.Group is deprecated and marked for removal

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3394]
There are a few classes that use the "marked for removal" class [`java.security.acl.Group`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/acl/Group.html).

* org.eclipse.jetty.jaas.RoleCheckPolicy
* org.eclipse.jetty.jaas.StrictRoleCheckPolicy
* org.eclipse.jetty.jaas.JAASGroup

We need to evolve our Jetty 10.x JAAS implementation to not use this deprecated and slated for removal class.

**Comment by janbartel** [comment]
Actually, these classes are absolutely unneeded and have been for a loong time. So I will remove them from jetty-9.4.x, then merge through to jetty-10.

**Comment by janbartel** [comment]
Classes remove in jetty-9.4.x and beyond.
