### ISSUE TITLE
ClassLoadingObjectInputStream needs to be updated to support JPMS Modules

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3395]
The method [`java.lang.reflect.Proxy.getProxyClass()` is deprecated and the reasoning highlights that it's incompatible with JPMS Modules](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Proxy.html#getProxyClass(java.lang.ClassLoader,java.lang.Class...)).

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-util/src/main/java/org/eclipse/jetty/util/ClassLoadingObjectInputStream.java#L132

This usage needs to be evaluated and either changed or removed prior to the Jetty 10.0.0 release

**Comment by joakime** [comment]
Even the JDK implementation of ObjectInputStream is using the same method.
This might not be a bug we can work around.

@janbartel can you triage this issue?

**Comment by janbartel** [comment]
@joakime correct - the ObjectInputStream is still using the deprecated Proxy.getProxyClass because there simply  is no other equivalent:  the only accessible methods on Proxy actually construct an instance of  the proxy!

I think once the jvm resolves this, then we can resolve it, but not before.

**Comment by janbartel** [comment]
I think I will add a better test for serializing/deseriazling a proxy class - the current tests put all of the classes on the application classloader, whereas they should all really be on a different classloader that is the equivalent to the webapp classloader. I'll do a PR for that.

**Comment by janbartel** [comment]
jdk13 ObjectInputStream still uses the deprecated Proxy.getProxyClass method.

**Comment by gregw** [comment]
I've removed from 10.0.0 project.   
@janbartel  Can this be closed? what will trigger further work?
