### ISSUE TITLE
Remove support for javax.servlet.SingleThreadModel in Jetty 10.0.x

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3397]
In our ServletHolder there's an attempt to support the long deprecated `javax.servlet.SingleThreadModel` ...

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java#L410-L411

But we also have some code to throw an ISE if a SingleThreadModel is attempted to be used ....

https://github.com/eclipse/jetty.project/blob/3a7dee0e189b34419c5243dd6a918c2fd03c4257/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java#L169-L172

Is it even possible to support `javax.servlet.SingleThreadModel` anymore in the codebase?
This attempted support should probably just be removed and the ISE text made more clear as to what is going on.

**Comment by gregw** [comment]
While this mechanism is indeed deprecated, the TCK still tests for it, so I do not believe we can remove it: https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/servlet/api/javax_servlet/singlethreadmodel
