### ISSUE TITLE
XmlConfiguration jetty.webapps.uri is the uri of the webapp not the parent dir

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3399]
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L155

The property is called "jetty.webapps.uri", but the actual value is the uri of the webapp being configured, not its parent dir, but the "jetty.webapps" property contains the path of the parent dir.

**Comment by joakime** [comment]
Opened PR #3430

**Comment by janbartel** [comment]
Fix applied to jetty-10.0.x branch.
