### ISSUE TITLE
JettyAwareLogger cannot run in Maven

### ISSUE THREAD

**Issue by eirbjo** [eclipse/jetty.project#341]
This is a comment / continuation of the resolved Bugzilla https://bugs.eclipse.org/bugs/show_bug.cgi?id=482728
# Observations:

It seems to me that Maven's plexus realm classloader only exposes,
org.slf4j., org.slf4j.spi., but that org.slf4.helpers.  is not
exposed. (Additionally, Maven somewhat magically excludes our plugin's
dependency on slf4j-api.)

This causes a CNFE on any attempt to load classes from
org.slf4j.helpers.\* from inside a Maven plugin.

In our case, the hudson slf4j spy jar is what triggers this. It causes
a different Slf4J logger impl to be used instead of Maven's
slf4j-simple.

Jetty's Log.java detects this Slf4J logger to be an instance of
LocationAwareLogger and wraps it in a JettyAwareLogger, which again
uses MessageFormat from org.slf4j.helpers

We worked around this issue by setting the this system property in the
Hudson job:
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog
# Question / feedback:

Since Maven hides org.slf4.helpers, JettyAwareLogger cannot currently
be used inside Maven. This isn't really a Hudson problem. Hudson
exposes a problem of running Jetty inside Hudson.

Could the Jetty project rewrite JettyAwareLogger to _not_ use
FormattingTuple and MessageFormatter?

Maven could also stop hiding parts of slf4j-api, but they probably
hide it for some reason?

**Comment by joakime** [comment]
This seems to no longer be a problem in Maven.
Closing.
