### ISSUE TITLE
GzipHandler defaults to only Gzipping GET

### ISSUE THREAD

**Issue by mikebell90** [eclipse/jetty.project#3410]
We noticed this recently. Before we blindly turn it on for POSTS at our main public ingress, would you mind explaining the reasoning? I tried to track it through the commits, but couldn't find a comment.

Cheers,
Mike

**Comment by joakime** [comment]
It's configurable.  GET is the safest operation to apply the gzip compression of responses to.

Feel free to use `GzipHandler.addIncludedMethods("POST");` yourself if you want GzipHandler to also process POST exchanges.

**Comment by sbordet** [comment]
POSTs typically do not have large responses that need compression.

For normal web pages after a POST you want to redirect, so the response does not even have a body.
For REST it may vary, but typically it's a description that the POST went well with maybe some `id` to use in a subsequent GET and not much more.

**Comment by mikebell90** [comment]
Ok, thanks
