### ISSUE TITLE
HttpClient does not timeout during multiple redirection 

### ISSUE THREAD

**Issue by kbadruka** [eclipse/jetty.project#3411]
HttpClient performing multiple redirection does not timeout even when the timeout is set. The process hangs on send() method and does not come out. Though setting lower value for maxRedirect results in 'max redirects exceeded' error but here the requirement is to keep redirecting until the result come or timeout happens. It seems timeout() method is not considering internal redirection happening.
```
            SslContextFactory sslContextFactory = new SslContextFactory(true);
            HttpClient client = new HttpClient(sslContextFactory);
            client.setMaxRedirects(Integer.MAX_VALUE);
            client.setConnectTimeout(30000);
            client.start();

            ContentResponse response = client.newRequest("http://19744ww.club")
                .method(HttpMethod.GET)
                .timeout(30, TimeUnit.SECONDS)
                .followRedirects(true)
                .send();
```
Appreciate response on this.

**Comment by sbordet** [comment]
Thanks for reporting. 

The server redirects to the same URI, so it's an infinite redirect.

We should detect that the redirect is the same and abort, and also enforce the total timeout, which now is reset for every redirect - and that is wrong.
