### ISSUE TITLE
problems with jetty 10 WebSocket session customizer

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3412]
the `autoFragment` boolean is set on the `WebSocketChannel` by the `FrameHandler.Customizer` in the upgrade method of the `ClientUpgradeRequest`, however this is done after the `WebSocketConnection` creates the `Parser`, so the autoFragment in the `Parser` is never properly updated

there is also currently no way to give a `FrameHandler.Customizer` to the `WebSocketClient` for the jetty-api

**Comment by joakime** [comment]
@lachlan-roberts is this completed?

**Comment by lachlan-roberts** [comment]
yes, the WSChannel is now customised directly after its creation, and the `WebSocketPolicy` methods on  `WebSocketClient` now configure a `ConfigurationCustomizer` which is given to the WSCoreClient
