### ISSUE TITLE
Windows Service documentation

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#3417]
Community member T. Vogd brought this issue to light. His comments are below.

"There are two minor errors in the documentation on page "Startup via Windows Service" (v. 9.4.15.v20190215):

1) In the example install-jetty-service.bat, in line 
 --JvmOptions="%PR_JVMOPTIONS%" ^
the quotes should be removed  (should be  --JvmOptions=%PR_JVMOPTIONS% ^)
Otherwise they quotes collides with those in the parameter %PR_JVMOPTIONS%.

2) During module deployment, the command
C:\opt\myappbase>java -jar ..\jetty\start.jar --add-to-start=deploy,http,logging
tries to deploy the deprecated module "logging", which has been replaced.
It should be:
C:\opt\myappbase>java -jar ..\jetty\start.jar --add-to-start=deploy,http,console-capture"

**Comment by joakime** [comment]
Using that without quotes means that paths or options that have spaces will not be interpreted properly.

**Comment by thvogd** [comment]
@joakime: That is correct for other parameters like %PR_JVM% etc.

However the mentioned parameter PR_JVMOPTIONS uses quotes itself:
set PR_JVMOPTIONS=-Duser.dir="%JETTY_BASE%";-Djava.io.tmpdir="C:\opt\temp";-Djetty.home="%JETTY_HOME%";-Djetty.base="%JETTY_BASE%"

Thus when enclosing it with quotes as in line
  --JvmOptions="%PR_JVMOPTIONS%" ^
of install-jetty-service.bat, the result contains to many quotes:
  --JvmOptions="-Duser.dir="%JETTY_BASE%";-Djava.io.tmpdir="C:\opt\temp";-Djetty.home="%JETTY_HOME%";-Djetty.base="%JETTY_BASE%""

Therefore the quotes should be removed in this line (in other lines they achieve the wanted effect and should remain).
