### ISSUE TITLE
Setup a build to run Jetty against TCK

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3420]
Now TCK is available as an opensource project: https://github.com/eclipse-ee4j/jakartaee-tck
So we can run TCK tests as part of our build process (at least once a day or week):
- EL TCK
- JSP TCK
- Servlet TCK
- Websocket TCK

**Comment by sbordet** [comment]
@olamy you may give it a go, but try not to spend too much time on it.
Last time I heard about the TCK tests for JavaEE, they were taking one week to run on powerful machines.

**Comment by joakime** [comment]
@olamy if you can build it sufficiently to have the 2 core standalone TCKs that would be a great start.

* `${WORKSPACE}/standalone-bundles/servlettck-4.0_latest.zip`
* `${WORKSPACE}/standalone-bundles/websockettck-1.1_latest.zip`

From my reading of the various shell scripts, I think we can just use those zip files and test those specific APIs, without running the entire EE TCK (which is pointless for Jetty)

If we can prove out those 2, then we can start adding others (`jsp`, `jstl`, `securityapi`, `javamail`, and `jaspic` are possible candidates)

**Comment by olamy** [comment]
done see https://github.com/jetty-project/tck-run
