### ISSUE TITLE
CLOSE_WAIT socket status forever after terminating websocket client side

### ISSUE THREAD

**Issue by ykonrad** [eclipse/jetty.project#3422]
Hi,
jetty 9.4.15 - After websocket  client app is abnormally terminated  (kill -9, OOM, core dump, etc...) , the websocket stays in CLOSE_WAIT forever. 
As result of this, the onWebSocketClose hook is never executed, leaving the server side unaware of the lost client. I am almost positive this is not websocket exclusive issue but it is very easy to reproduce it with websockets.
this can be encountered in 9.4.15 only; After rolling back to 9.4.14 issue is gone/ So, this is new one.

**Comment by ykonrad** [comment]
Not sure if this is relevant, but I'm using embedded server with ssl connector. I saw several fixes were made around the area of closing ssl connection in 9.4.15, Just saying.

**Comment by sbordet** [comment]
If you `kill -9` the JVM, I don't think we can close any socket, in any version of Jetty, as the JVM process will exit immediately and no Jetty code will run to close sockets.

**Comment by ykonrad** [comment]
I’m killing the websocket client process. Not the server. When client terminated abnormally the server peer stays close_wait. Didn’t test it with plain connection. Only ssl. In 9.4.14 it’s working fine so it’s something in 9.4.15

**Comment by joakime** [comment]
using demo-base from jetty-distribution, connecting to the secure port (8443) and using the test chat client that connects, says something, then `System.exit()` shows the CLOSE_WAIT in some preliminary testing.

**Comment by joakime** [comment]
Once server side idleTimeout kicks in for the connection, the CLOSE_WAIT is removed, as expected.

**Comment by sbordet** [comment]
The receive the close from the client, so we should close immediately, not wait for the idle timeout.
We are working on this.

**Comment by joakime** [comment]
Opened PR #3467

**Comment by joakime** [comment]
Work completed and merged into `jetty-9.4.x` branch.
Will be present on next Jetty 9.4.x release (likely 9.4.16)
