### ISSUE TITLE
Upgrade conscrypt version to 2.0.0 and remove usage of reflection

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3425]

**Comment by olamy** [comment]
some reflection cannot be removed in 9.4.x as SSLEngine new methods are only available from java9. So we will have a different code base: 
- https://docs.oracle.com/javase/10/docs/api/javax/net/ssl/SSLEngine.html#getApplicationProtocol()
- https://docs.oracle.com/javase/10/docs/api/javax/net/ssl/SSLEngine.html#setHandshakeApplicationProtocolSelector(java.util.function.BiFunction)

**Comment by sbordet** [comment]
@olamy I don't understand.

The `Conscrypt` class has all methods you need to set and get the application protocols in a way that is Java8 compatible.
You just replace where we use reflection with calls to the `Conscrypt` class.

**Comment by joakime** [comment]
@sbordet that's what he already did in commit 94f02041385d77d2e242bd7e6f542941332ffbdd

**Comment by sbordet** [comment]
@joakime nope, he's doing the set, but it's using the Java9 API for the get, while instead he should use the Conscrypt API for get too.

**Comment by olamy** [comment]
@sbordet oops my bad it's available using Conscrypt static methods. I will fix that. But why not using SSLEngine public API in jetty 10.0.x as we are java11 minimum?

**Comment by sbordet** [comment]
@olamy do public SSLEngine APIs work on 10.0.x with Conscrypt? Have you tried?

**Comment by olamy** [comment]
@sbordet yes everything works fine except a test failure with OSGI only for jdk8.. (Test: ` TestJettyOSGiBootHTTP2Conscrypt ` )

**Comment by olamy** [comment]
https://github.com/google/conscrypt/issues/635
