### ISSUE TITLE
org.eclipse.jetty.http.Http1FieldPreEncoder generates an invalid header byte-array if header is null

### ISSUE THREAD

**Issue by sebneter** [eclipse/jetty.project#3444]
If Http1FieldPreEncoder#getEncodedField is called with null for header then the generated byte[] is invalid. The ":" to separate key and value is overwritten and the value is not added to the byte[] at all.

example:
`byte[] bytes = new Http1FieldPreEncoder().getEncodedField(null, "X-XSS-Protection", "1; mode=block");`
`System.out.println(new String(bytes, StandardCharsets.ISO_8859_1));`
will print: X-XSS-Protection

This header is invalid. If the Http1FieldPreEncoder is used in combination with org.eclipse.jetty.http.PreEncodedHttpField and the PreEncodedHttpField is added to a response the response is invalid as well.

For example if this SecureRequestCustomizer is used

```
public class MySecureRequestCustomizer extends SecureRequestCustomizer {

    private static final PreEncodedHttpField X_XSS_PROTECTION_FIELD = new PreEncodedHttpField("X-XSS-Protection", "1; mode=block");

    @Override
    protected void customizeSecure(Request request) {
        super.customizeSecure(request);
        request.getResponse().getHttpFields().add(X_XSS_PROTECTION_FIELD);
    }
}
```

**Comment by joakime** [comment]
Modifying the response from a [`HttpConfiguration.Customizer`](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/HttpConfiguration.Customizer.html) seems out of scope of what that Customizer concept was created for.

Anyway, adding testcase (in commit 13a4a10c036c6fca597e96f696039ec63aca175) for both...

* `HttpFields.add(PreEncodedHttpField)`
* `HttpFields.add(HttpField)`

both work as advertised, not able to replicate report.

**Comment by joakime** [comment]
Added a testcase for your reported issue at commit b1477ac0673c547f2de2280a8ade86debaf87ddb

Interestingly, PreEncodedHttpField sets the state of the Response improperly, and doesn't let the correct ServiceLoaded PreEncodedHttpField operate like it should.
The result is NO RESPONSE, none, no headers, no body, nothing, nada, zilch.  No bytes over the network/connector are sent.

But if you just use HttpField instead, then the process works properly.
https://github.com/eclipse/jetty.project/blob/b1477ac0673c547f2de2280a8ade86debaf87ddb/jetty-server/src/test/java/org/eclipse/jetty/server/HttpConfigurationCustomizerTest.java#L53-L59

**Comment by sebneter** [comment]
Thanks for your responses and for the testcases.
I'm using a `HttpConfiguration.Customizer` to add this header to treat it the same as the "Strict-Transport-Security" header. This is added by the `SecureRequestCustomizer` which is also a `HttpConfiguration.Customizer`. What other solution would you suggest?

If there are other implementations of the interface `HttpFieldPreEncoder` available, the reported issue with the `HttpConfiguration.Customizer` might not occure, because this other implementation might encode the header correctly.

I guess the issue is in the method `getEncodedField `of the class `Http1FieldPreEncoder` as reported. 

If the header is null then the value is assigned to the variable "v". But only the length of this byte[] is used. The bytes itself are never copied to the result bytes. And the whitspace is assigned to exactly the same position as the ":".

  ```
      byte[] n=headerString.getBytes(ISO_8859_1);
        byte[] v=value.getBytes(ISO_8859_1);
        byte[] bytes=Arrays.copyOf(n,n.length+2+v.length+2);
        bytes[n.length]=(byte)':';
        bytes[n.length]=(byte)' ';
        bytes[bytes.length-2]=(byte)'\r';
        bytes[bytes.length-1]=(byte)'\n';

        return bytes;
```

**Comment by joakime** [comment]
@gregw please checkout branch `jetty-9.4.x-3444-httpfields-add-preencoded` and check out the `HttpConfigurationCustomizerTest.java`.
If you swap that commented out line number 54 with the one below, you'll see how PreEncodedHttpField trips up the Response object.

**Comment by gregw** [comment]
@joakime wow that was a bit of bug to have out there for a while!   I've fixed it and added a test harness. I'll create a PR.

**Comment by joakime** [comment]
Opened PR #3452

**Comment by gregw** [comment]
This is now fixed and will be in next release.
