### ISSUE TITLE
class HttpStatus and HttpServletResponse int constants are superflous

### ISSUE THREAD

**Issue by martinmeeser** [eclipse/jetty.project#3449]
The class HttpStatus does define all HTTP status codes.

The class HttpServletResponse also has final static int SC_XXX = XX to define all status code.

Personally I would prefer to see the final statics at HttpServletResponse to be removed, and HttpServletResponse should make use of HttpStatus.

**Comment by sbordet** [comment]
`HttpServletResponse` is a class provided by the Servlet Specification and we cannot change it.
