### ISSUE TITLE
Removing moved Extension classes from jetty-websocket-api

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3453]
classes defining jetty-api extensions exist such as 

```
Extension
ExtensionFactory
IncomingFrames
OutgoingFrames
```

but these don't seem to be used or tested anywhere

**Comment by joakime** [comment]
Most of the extension behaviors have been moved to websocket-core.

To document for future viewers of this issue ...

* `org.eclipse.jetty.websocket.api.extensions.Extension`  is now at `org.eclipse.jetty.websocket.core.Extension`

**Comment by joakime** [comment]
Opened PR #3455
