### ISSUE TITLE
Multiple programmatic login logout in same request not working

### ISSUE THREAD

**Issue by basinilya** [eclipse/jetty.project#3456]
With auth-method FORM in web.xml and inside a dynamic login page you cannot call request.login() after request.logout() or a previous request.login() call with a bad password. The use case is when you want to try more than one password to login programmatically.

It throws one of these:

	Already authenticated as: null // if called login() with bad password
	Already authenticated as: UNAUTHENTICATED // if called logout()

I think one problem is on this line: https://github.com/eclipse/jetty.project/blob/dbf0d2e6becc09ef0310616bd9045e4f97130cab/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2437

Perhaps the code should not assign the `_authentication` field without checking it for null.

The other problem is in the logout() method on the line: https://github.com/eclipse/jetty.project/blob/dbf0d2e6becc09ef0310616bd9045e4f97130cab/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2453

login() expects the field to be `instanceof Authentication.Deferred`, but `Authentication.UNAUTHENTICATED` does not implement it.

**Comment by janbartel** [comment]
Fixed in jetty-9.4.x and beyond.
