### ISSUE TITLE
Supporting SSE with ProxyServlet

### ISSUE THREAD

**Issue by xd101x** [eclipse/jetty.project#3459]
Hi,

We are trying to use Server Side Events with the  ProxyServlet but this does not seem to be working.

The write method in onResponseContent is being called but the client does not receive the data.

As a test, I've added a flush just after the write and that seems to work.

Can someone please advise on this matter?

Thanks.
D.

**Comment by sbordet** [comment]
Can you please detail exactly how your system is setup?

Are you using the `EventSourceServlet` (https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/EventSourceServlet.java)?

**Comment by xd101x** [comment]
Hi,

We are just loading the ProxyServlet Class using Jetty to "rerouting" http traffic over to a back-end server that is handing the request.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/ProxyServlet.java

This works fine but when we tried to use SSE, the client (UI) does not receive any responses back.

UI <---> Jetty with Proxyservlet <--> BackEnd.

Regards,
David.

**Comment by sbordet** [comment]
Jetty will optimize the `write()` calls from the application by aggregating the bytes and flushing them in less network writes.
Of course this strategy won't work (and it's actually doing the opposite) if you use SSE.

You have these choices:

1. Override `ProxyServlet.onResponseContent()` and call first `super` and then `response.getOutputStream().flush()`
1. Change the aggregation buffer size to zero: `HttpConfiguration.setOutputAggregationSize(0)` - but this will affect all the requests, not only those handled by the `ProxyServlet` like the previous solution.

Let us know how it goes.

**Comment by xd101x** [comment]
Hi Simone,

Thank you for the reply.

I've implemented 1) as a test but we are seeing other side effect in that the HTTP client is timing out the the upstream connection after the Idle timeout kicks in. 

BTW, We are currently and have been using the ProxyServlet as an API gateway and were looking to use SSE as a means of notification. 

Regards,
David.

**Comment by sbordet** [comment]
As a side note, SSE is really, _really_ basic - good for hello world, but the moment you want to do something serious it does not cut it.

Client-to-server (in your case proxy-to-server) idle timeout is a common case with SSE because there is no heartbeat - if the server is idle the client will likely idle timeout.

I recommend that you look into some other solution, for example `CometD` (https://cometd.org) - which we also support - for systems that emit server-side events that needs to be sent to remote clients.

**Comment by xd101x** [comment]
Hi Simone,

Thank you for the help you've provided.

We'll look into the CometD technology.

Regards,
David.
