### ISSUE TITLE
JAAS configuration example in configuration is wrong

### ISSUE THREAD

**Issue by JasperHorn** [eclipse/jetty.project#3463]
On https://www.eclipse.org/jetty/documentation/current/jaas-support.html there's a (pretty annoying) mistake in the examples. There are three files, each with things called a "name".

- The web.xml file with (1) a realm-name
- The xml snippet with (2) a Name and (3) a LoginModuleName
- The conf file, which starts with (4) an application name

In the example, (1), (3) and (4) are the same, while (2) is different. In reality, (1) should be the same as (2), while (3) should be the same as (4). The "Caution" block on the page explains this correctly, but as it was so vague with all the things called a name that I was relying on the example to interpret that block, meaning I was doing things completely wrong.

The easiest fix would be to change (1) to be "Test JAAS Realm", as that's the value of (2) in this example.

(I would have provided the suggested change as a contribution, if it weren't for the fact that the change itself was less effort then reading the contribution guidelines and making sure everything was following those rules, so instead, I'm making this issue and leaving the change for someone who has made other contributions and doesn't have the same overhead.)

**Comment by joakime** [comment]
@WalkerWatch work with @janbartel and see about getting this corrected.

**Comment by janbartel** [comment]
There are a lot of different name fields aren't there?!  I've fixed the doco, sorry for the confusion.
