### ISSUE TITLE
[Question] Weird Characters At Http Client Response

### ISSUE THREAD

**Issue by davidasync** [eclipse/jetty.project#3468]
Jetty version: 9.4.15.v20190215
Take a look at this code

```
suspend fun main () = coroutineScope {
    val sslContextFactory = SslContextFactory()
    val httpClient = HttpClient(sslContextFactory)
    httpClient.connectTimeout = 30000
    httpClient.start()

    val content = jsonBody.toByteArray()

    httpClient.newRequest("https://httpbin.org/get")
        .method("get")
        .send(object : Response.Listener.Adapter() {
            override fun onContent(response: Response, buffer: ByteBuffer) {
                val responseString = String(buffer.array())
                println(responseString)
            }
        })

    httpClient.newRequest("https://httpbin.org/get")
        .method("get")
        .send(object : Response.Listener.Adapter() {
            override fun onContent(response: Response, buffer: ByteBuffer) {
                val responseString = String(buffer.array())
                println(responseString)
            }
        })
}
```

Not sure why there are weird chars at the end of the response string

![image](https://user-images.githubusercontent.com/17562956/54478098-489f8a00-4841-11e9-8069-9af342f6e40f.png)

**Comment by joakime** [comment]
``` java
val responseString = String(buffer.array())
println(responseString)
```

That is the wrong way to convert a ByteBuffer to a String.
The `ByteBuffer.array()` is the underlying array, which isn't guaranteed to exist (using `.array()` can result in an Exception when the ByteBuffer is not backed by an array).
And you are using the ByteBuffer without any regard to the position/limit information that the ByteBuffer is tracking.
You are also not taking into account the charset of the bytes you are working with. (your code will use your own machine's locale/charset, it will run differently on mine).

To convert a ByteBuffer to String has many different techniques.

Here's a few different ways.

Using the Charset to decode the ByteBuffer properly.

``` java
String s = StandardCharsets.UTF_8.decode( buffer ).toString();
System.out.println( s );
```

and the longer form, to convert a ByteBuffer to array properly, then to a String.

``` java
byte[] bytes;
if( buffer.hasArray() ) {
    bytes = buffer.array();
} else {
    bytes = new byte[buffer.remaining()];
    buffer.get( bytes );
}
String s = new String( bytes, StandardCharsets.UTF_8 );
System.out.println( s );
```

**Comment by davidasync** [comment]
Nice, that's work,
Thanks ~
