### ISSUE TITLE
temp directory on remote file system isn't cleaned up when jetty stopped

### ISSUE THREAD

**Issue by kyata0629** [eclipse/jetty.project#3469]
I'm setting the temp directory on remote file system and
having trouble in cleaning up temp directory.

Deployment of application by war file worked well, but
the temp directory is not deleted on shutdown of Jetty.
Of cource setPersistTempDirectory is set false, and
temp directory is properly cleaned up when I set it on local file system.

The shutdown log shows no error messages and there are no difference between
setting temp directory on local and remote file system.

**Comment by joakime** [comment]
If it works on a local file system, then Jetty is operating properly.
Be sure you are not using known faulty remote filesystems (eg: NFS, ClearCase).
These faulty remote filesystem don't report their success/failures to applications.
Nor do they handle file locks properly (if at all), causing applications to expect one behavior while the remote filesystem is doing the opposite.

There's not much that Jetty (running on Java) can do to fix this kind of situation, if the remote filesystem doesn't behave in regards to `java.nio.file.FileSystem` then there's nothing we can do to work around it.
You'll either need to tweak that remote filesystem's configurations to behave more normally, or you'll have to live with the behaviors that using the remote filesystem has introduced.

**Comment by joakime** [comment]
On a different note, it's unwise to have a working directory and webapp temp directory on a non-local filesystem.
Those directories are used frequently and are critical for proper operation of the webapps running on your Jetty instance.

**Comment by janbartel** [comment]
I'm closing this issue for now, as there does not appear to be anything that jetty can do about remote file systems. If you have further information or suggestions feel free to reopen.
