### ISSUE TITLE
Avoid sending request using a connection that is idle timing out

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#347]
This is a follow up to BugZilla [484585](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484585).

It is still possible that a request is sent while the connection is timing out.
The reason is that the scheduler thread may decide to call `onIdleExpired()` just before `notIdle()` is called. This race is unavoidable in `IdleTimeout`.

In `HttpConnection` there is now a guard that "disables" the idle timeout if a request is being sent.
The guard increments atomically an integer before the send, and decrements it after the send.
At the same time, the guard is `cas(0, -1)` by the idle timeout mechanism.

It could happen that:
* T1, the idle timeout thread decides to call `onIdleExpired()`
* T2 increases the guard
* T2 sends the request
* T2 calls `notIdle()` but it's too late
* T2 decreases the guard
* T1 calls `onIdleExpired()`, finds the guard to be 0, and performs the idle timeout actions

**Comment by sbordet** [comment]
Fixed by adding a timestamp and checking that enough time has passed from the last timestamp.

The last step above will find the guard to be 0, check if enough time has passed, and only then perform the idle timeout actions.

**Comment by rajivjain83** [comment]
we are facing this issue in 9.4.12

**Comment by sbordet** [comment]
@rajivjain83 please open a new issue and detail **exactly** why you think you are facing an issue similar to this one.
We need evidence of the problem, and you saying it is not enough. We need DEBUG logs and wireshark traces.
