### ISSUE TITLE
HttpInput don't update _blockUntil

### ISSUE THREAD

**Issue by ligzy** [eclipse/jetty.project#3475]
HI,
This is my situation.
I wan't keep a async servlet active long time (such as several  hours --data upload evenry second),  if no data received in 30 seconds, then close the request.
i wan't use the setBlockingTimeout.

I found that i must set  http_config.setBlockingTimeout(3600000),(mybe more.)
i can't set  http_config.setBlockingTimeout(30000),

I read the source and found that :
In class org.eclipse.jetty.server.HttpInput 
 _blockUntil  didn't been updated. 
it just cant be set one time.

      if (!isAsync())
            {
                // Setup blocking only if not async
                if (_blockUntil == 0)
                {
                    long blockingTimeout = getBlockingTimeout();
                    if (blockingTimeout > 0)
                        _blockUntil = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(blockingTimeout);
                }
            }

so ,Is there have some method  to set the parameters in my case? 
Thanks!

**Comment by sbordet** [comment]
Your scenario is best handled with non-blocking reads, so `blockingTimeout` won't be of any use for you.

Tutorial:
https://blogs.oracle.com/arungupta/non-blocking-io-using-servlet-31:-scalable-applications-using-java-ee-7-totd-188

Read this to avoid pitfalls:
https://www.slideshare.net/SimoneBordet/servlet-31-async-io

**Comment by ligzy** [comment]
> Your scenario is best handled with non-blocking reads, so `blockingTimeout` won't be of any use for you.
> 
> Tutorial:
> https://blogs.oracle.com/arungupta/non-blocking-io-using-servlet-31:-scalable-applications-using-java-ee-7-totd-188
> 
> Read this to avoid pitfalls:
> https://www.slideshare.net/SimoneBordet/servlet-31-async-io

Let me try.
Thanks!

**Comment by joakime** [comment]
Also note that the `blockingTimeout` concept/configurable has been removed from Jetty 10.0.x branch.

**Comment by joakime** [comment]
Closing as answered.
