### ISSUE TITLE
Received fatal alert: handshake_failure ( Using org.eclipse.jetty 9.4.15.v20190215)

### ISSUE THREAD

**Issue by honeyVader007** [eclipse/jetty.project#3477]
I'm attempting to use mutual auth and connect using jetty as the client into a rest end point over https. I'm able to make this work using CURL and JMeter with the same keystore and trustore files. Here's what the HttpClient error looks like

**HttpClient@3d71d552-16, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
HttpClient@3d71d552-16, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure**

Note that I see another warning message prior in the debug log as follows

**ServerHelloDone
Warning: no suitable certificate found - continuing without client authentication
 Certificate chain Empty**

Not certain why the jetty client is unable to present the certificate and then causing the handshake failure. Would appreciate any short term recommendations as well.

**Comment by sbordet** [comment]
Have you configured the client with the right `SslContextFactory` configuration?

If you show the code, we may be able to help you.
Jetty version?

**Comment by honeyVader007** [comment]
Jetty version is 9.4.15.v20190215.

Here’s the SSLContextFactory config

	SslContextFactory sslContextFactory = new SslContextFactory(true);
		sslContextFactory.setNeedClientAuth(true); 
		sslContextFactory.setKeyStorePath("identity.jks");
		sslContextFactory.setKeyStorePassword("pass1234");
		sslContextFactory.setKeyStoreType("JKS");
		sslContextFactory.setTrustStorePath("cqatruststore.jks");
		sslContextFactory.setTrustStorePassword("pass1234");
		sslContextFactory.setTrustStoreType("JKS");

**Comment by joakime** [comment]
After you have started the `HttpClient` can you dump it?

Something like this https://gist.github.com/joakime/3986412e8c18939c3d6726fc2ca1b239#file-clientssldemo-java-L32-L33

``` java
        client.start();
        client.dump(System.out);
```

**Comment by sbordet** [comment]
`setNeedClientAuth(true)` must be set on the server, not on the client. Are you setting it on the server too?

The server should also be configured with `setEndpointIdentificationAlgorithm(null)` because you typically don't want to verify the client host, just the certificate chain.
The server should also be configured with the right truststore, unless the client certificate is signed by a known CA.

**Comment by honeyVader007** [comment]
Here’s the HttpClient dump.

HttpClient@7506e922{STARTED} - STARTED
+= HttpClientTransportOverHTTP@1b40d5f0{STARTED} - STARTED
|  += ClientSelectorManager@ea4a92b{STARTED} - STARTED
|     += ManagedSelector@5ba23b66{STARTED} id=0 keys=0 selected=0 updates=0 - STARTED
|     |  += EatWhatYouKill@2ff4f00f/SelectorProducer@6bdf28bb/PRODUCING/p=false/QueuedThreadPool[HttpClient@7506e922]@66cd51c3{STARTED,8<=8<=200,i=6,q=0}[ReservedThreadExecutor@6b71769e{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2019-03-20T15:21:57.851-07:00 - STARTED
|     |  |  +- SelectorProducer@6bdf28bb
|     |  |  += QueuedThreadPool[HttpClient@7506e922]@66cd51c3{STARTED,8<=8<=200,i=6,q=0}[ReservedThreadExecutor@6b71769e{s=0/4,p=0}] - STARTED
|     |  |     += ReservedThreadExecutor@6b71769e{s=0/4,p=0} - STARTED
|     |  |     +> threads size=8
|     |  |        +> 11 HttpClient@7506e922-11 SELECTING RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
|     |  |        +> 12 HttpClient@7506e922-12 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
|     |  |        +> 9 HttpClient@7506e922-9 SELECTING RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
|     |  |        +> 15 HttpClient@7506e922-15 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
|     |  |        +> 10 HttpClient@7506e922-10 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
|     |  |        +> 14 HttpClient@7506e922-14 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
|     |  |        +> 13 HttpClient@7506e922-13 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
|     |  |        +> 16 HttpClient@7506e922-16 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
|     |  +> updates @ 2019-03-20T15:21:57.841-07:00 size=0
|     |  +> keys @ 2019-03-20T15:21:57.846-07:00 size=0
|     += ManagedSelector@2752f6e2{STARTED} id=1 keys=0 selected=0 updates=0 - STARTED
|        += EatWhatYouKill@e580929/SelectorProducer@1cd072a9/PRODUCING/p=false/QueuedThreadPool[HttpClient@7506e922]@66cd51c3{STARTED,8<=8<=200,i=6,q=0}[ReservedThreadExecutor@6b71769e{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2019-03-20T15:21:57.858-07:00 - STARTED
|        |  +- SelectorProducer@1cd072a9
|        |  +~ QueuedThreadPool[HttpClient@7506e922]@66cd51c3{STARTED,8<=8<=200,i=6,q=0}[ReservedThreadExecutor@6b71769e{s=0/4,p=0}] - STARTED
|        +> updates @ 2019-03-20T15:21:57.856-07:00 size=0
|        +> keys @ 2019-03-20T15:21:57.857-07:00 size=0
+= SslContextFactory@511baa65[provider=null,keyStore=file:///Users/XXX/Documents/FICO-EC2/FAI/keys/identity.jks,trustStore=file:///Users/XXX/Documents/FICO-EC2/FAI/keys/cqatruststore.jks] - STARTED
|  +> trustAll=true
|  +> Protocol Selections
|  |  +> Enabled size=3
|  |  |  +> TLSv1
|  |  |  +> TLSv1.1
|  |  |  +> TLSv1.2
|  |  +> Disabled size=2
|  |     +> SSLv2Hello - ConfigExcluded:'SSLv2Hello'
|  |     +> SSLv3 - ConfigExcluded:'SSLv3' JVM:disabled
|  +> Cipher Suite Selections
|     +> Enabled size=25
|     |  +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
|     |  +> TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
|     |  +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
|     |  +> TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
|     |  +> TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
|     |  +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
|     |  +> TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
|     |  +> TLS_EMPTY_RENEGOTIATION_INFO_SCSV
|     +> Disabled size=57
|        +> SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$' JVM:disabled
|        +> SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$'
|        +> SSL_DHE_DSS_WITH_DES_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$' JVM:disabled
|        +> SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$' JVM:disabled
|        +> SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$'
|        +> SSL_DHE_RSA_WITH_DES_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$' JVM:disabled
|        +> SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> SSL_DH_anon_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> SSL_DH_anon_WITH_DES_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> SSL_RSA_EXPORT_WITH_DES40_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$' JVM:disabled
|        +> SSL_RSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$'
|        +> SSL_RSA_WITH_DES_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$' JVM:disabled
|        +> SSL_RSA_WITH_NULL_MD5 - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
|        +> SSL_RSA_WITH_NULL_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^SSL_.*$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
|        +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_DH_anon_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_DH_anon_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_DH_anon_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_DH_anon_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_DH_anon_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_DH_anon_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_ECDSA_WITH_NULL_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
|        +> TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDHE_RSA_WITH_NULL_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
|        +> TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_ECDSA_WITH_NULL_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
|        +> TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|        +> TLS_ECDH_RSA_WITH_NULL_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
|        +> TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_ECDH_anon_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_ECDH_anon_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_ECDH_anon_WITH_NULL_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^.*_NULL_.*$', ConfigExcluded:'^.*_anon_.*$' JVM:disabled
|        +> TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$' JVM:disabled
|        +> TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$' JVM:disabled
|        +> TLS_KRB5_WITH_3DES_EDE_CBC_MD5 - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$' JVM:disabled
|        +> TLS_KRB5_WITH_3DES_EDE_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$' JVM:disabled
|        +> TLS_KRB5_WITH_DES_CBC_MD5 - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$' JVM:disabled
|        +> TLS_KRB5_WITH_DES_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$' JVM:disabled
|        +> TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^TLS_RSA_.*$'
|        +> TLS_RSA_WITH_NULL_SHA256 - ConfigExcluded:'^TLS_RSA_.*$', ConfigExcluded:'^.*_NULL_.*$' JVM:disabled
+- org.eclipse.jetty.client.ProtocolHandlers@340f438e
|  +> java.util.LinkedHashMap@17cf9d17{size=4}
|     +@ continue=org.eclipse.jetty.client.ContinueProtocolHandler@30c7da1e
|     +@ redirect=org.eclipse.jetty.client.RedirectProtocolHandler@5b464ce8
|     +@ www-authenticate=org.eclipse.jetty.client.WWWAuthenticationProtocolHandler@57829d67
|     +@ proxy-authenticate=org.eclipse.jetty.client.ProxyAuthenticationProtocolHandler@19dfb72a
+- org.eclipse.jetty.client.HttpClient$ContentDecoderFactorySet@17c68925(size=1)
|  +: org.eclipse.jetty.client.GZIPContentDecoder$Factory@30a95a
+~ QueuedThreadPool[HttpClient@7506e922]@66cd51c3{STARTED,8<=8<=200,i=6,q=0}[ReservedThreadExecutor@6b71769e{s=0/4,p=0}] - STARTED
+- org.eclipse.jetty.io.MappedByteBufferPool@59a6e353
+= ScheduledExecutorScheduler@7a0ac6e3{STARTED} - STARTED
+- org.eclipse.jetty.util.SocketAddressResolver$Async@71be98f5
+> requestListeners size=0
*********************************
* URL:        https://fai.cqa.gs.ficoanalyticcloud.com:443/falconservice/actuator/info
* Iterations: 2
*********************************

Setup time: 641 ms
Exception in thread "main" java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:362)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:347)
	at com.fico.http.client.http11client.Http11Client.main(Http11Client.java:71)
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:578)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

**Comment by honeyVader007** [comment]
I may not have much control over the server configuration but i shall definitely look into your questions specific to the server config.
As mentioned earlier, I have not had issues connecting into the same endpoint using Curl and JMeter.

**Comment by joakime** [comment]
Great, now run your curl command again, but with verboseness, check the cipher suite used.

```
$ curl -vv -op /dev/null https://mymachine.com/
...(snip)...
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
...(snip)...
```

You might see that CURL is using a protocol and/or cipher suite that is disabled/excluded by default in the Jetty HttpClient.

**Comment by honeyVader007** [comment]
Yes, i've tried this earlier and this is what i got on the protocol and cipher suite

`SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384`

Is there a way to include this explicitly from HttpClient.
I tried including using the api but that did not work.

**Comment by joakime** [comment]
According to your dump you have that enabled already.

```
|     |  +> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

So, it's not a protocols / cipher suites issue anymore, it's down to certificates and ssl configurations.
What's the curl command line you are using to test with client certificates?

**Comment by honeyVader007** [comment]
curl -k --cert <cert-file>:password --key <key-file> <https URL>

**Comment by sbordet** [comment]
`Warning: no suitable certificate found - continuing without client authentication` means that the client is about to send the client certificate, but it cannot load it from the client keystore.

What exact JDK version are you using?

I think you have your client-side keystore wrong, or containing unsupported certificates for the JDK version you're using.

We have tests in the Jetty test suite that prove that client certificates are working, so it must be something in your configuration.

**Comment by honeyVader007** [comment]
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by honeyVader007** [comment]
Simone and Joakim - Just wanted to close the loop on this request. You were spot on about the client certificate, I had to add all the issuer chains and the handshake worked. Thanks for all your help and the prompt support!

**Comment by sbordet** [comment]
Thanks for reporting back. Closing.
