### ISSUE TITLE
review and cleanup of jetty-websocket-api in jetty-10

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3479]
review the jetty-websocket API for any problems or any potential changes that should be made before the first release of jetty-10

**Comment by lachlan-roberts** [comment]
BatchMode in `@WebSocket` annotation not wired up to set the `BatchMode` on `RemoteEndpoint`

`FrameCallback` interface is not used or implemented

`WSUri` only usage in jetty-websocket-tests, there is duplicated code for this also in javax-tests and WSCore's `Negotiated`, if possible we should reduce the duplication of this code, and perhaps deprecate the API version of it

usages of `QuoteUtil` have been replaced by `QuotedStringTokenizer`, this should be deprecated

**Comment by joakime** [comment]
`WSUri` is used by many projects outside of the Jetty that also use Jetty's WebSocket API.
It's a super handy convenience utility class. 

`FrameCallback` interface was an interim class created when we migrated the codebase to jetty 10.  It doesn't exist on Jetty 9.4.x.
https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api
Remove it.

`QuoteUtil` is for parsing and generating quoted values.
`QuotedStringTokenizer` wasn't used as it introduced a jetty-util dependency in jetty-websocket-api, and the rules for headers in websocket back during the websocket-mux days meant that `QuotedStringTokenizer` was inappropriate / inadequate.
Anymore, `QuoteUtil` is an internal class, not meant to be exposed as an API class.  Feel free to move it.

**Comment by lachlan-roberts** [comment]
`getInetSocketAddress()` and `flush()` have not been implemented properly on `JettyWebSocketRemoteEndpoint`

**Comment by gregw** [comment]
With regards to WSUri, I'm OK with leaving it as a convenience class in the jetty-API.    Does the container provide the api classes as system classes? If so, it may be safe for the api class to be implemented in terms of the core class... but if that introduces complexity, then don't worry about a little bit of code duplication.

**Comment by lachlan-roberts** [comment]
Having the `CoreSession` return a `SocketAdress` makes the implementation of `JettyWebSocketRemoteEndpoint.getInetSocketAddress()` a bit awkward.

Not sure what the reasoning is for having `CoreSession` like this
https://github.com/eclipse/jetty.project/blob/90b3a576b1c0bf3e5d6d03c8bf5129ce9df7738f/jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/FrameHandler.java#L248-L258
as the only implementation in `WebSocketChannel` returns an `InetSocketAddress`

**Comment by joakime** [comment]
Do not make it return InetSocketAddress, as then it will need to change back to SocketAddress when we fix UnixSocket support for WebSocket again.
Please leave that as a SocketAddress.

**Comment by lachlan-roberts** [comment]
okay sure, how about the `RemoteEndpoint.getInetSocketAddress()` should I deprecate that and add a `getSocketAddress()`, or just return null if it is not an InetSocketAddress

**Comment by sbordet** [comment]
If `RemoteEndpoint` is our internal stuff, just change the method. If it's Jetty APIs, deprecate and add a `getSocketAddress()` but I think you must add either `Local` or `Remote` as in `getRemoteSocketAddress()`.

**Comment by lachlan-roberts** [comment]
in `RemoteEndpoint` we don't support asynchronously sending partial data frames.

to support this I could implement these methods
```java
void sendPartialBytes(ByteBuffer fragment, boolean isLast, WriteCallback callback);
Future<Void> sendPartialBytesByFuture(ByteBuffer fragment, boolean isLast);
void sendPartialString(String fragment, boolean isLast, WriteCallback callback);
Future<Void> sendPartialStringByFuture(String fragment, boolean isLast);
```

<hr>

also, the ping and pong frames are currently sent without blocking, and the methods do not provide any notification method such as the WriteCallback or Future, I will change these to blocking calls
Should we also provide async methods for these frames?

maybe it would be worth moving to the same style we have in javax where we have a basic and async remote instead of combining them into one
