### ISSUE TITLE
Jetty + Conscrypt != SNI

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/jetty.project#3483]
I use Jetty 9.4.15 with conscrypt 2.0 (+Java 11)
I created two Cert with different alternative names. I modified the host file of linux to check it.
Firefox show me it doesn't work, when I disable conscrypt the it is fine, the Jetty find the right cert for the arbitrary/random domain name.

Is there any solution for use conscrypt and SNI at the same time? I need conscrypt because that implement/enable x25519 and chacha20.

**Comment by sbordet** [comment]
@readonlynetwork we need exact configuration and exact error. Do you have virtual hosts configured in Jetty?

**Comment by readonlynetwork** [comment]
I connect to alt1.name.tld

Server:
```
KeyStore clientTrustStore = KeyStore.getInstance("PKCS12");
//load empty
clientTrustStore.load(null, null);
//ca of client
clientTrustStore.setCertificateEntry("onlyone", clientCert.getCertificateChain()[1]);

//HTTPS
scf = new SslContextFactory();
scf.setNeedClientAuth(true);
scf.setProvider("Conscrypt");//enable chacha20, x25519
scf.setKeyStorePassword(new String(keyPassword));
scf.setKeyStore(serverKeyStore);//two key
scf.setTrustStore(clientTrustStore);
scf.setTrustStorePassword(null);
scf.setCipherComparator(HTTP2Cipher.COMPARATOR);
scf.setEndpointIdentificationAlgorithm(null);// no check client name
//exclude
scf.addExcludeCipherSuites(".*NULL.*");
scf.addExcludeCipherSuites(".*RC4.*");
scf.addExcludeCipherSuites(".*MD5.*");
scf.addExcludeCipherSuites(".*SHA1.*");
scf.addExcludeCipherSuites(".*DES.*");
scf.addExcludeCipherSuites(".*DSS.*");
scf.addExcludeCipherSuites(".*RSA.*");
scf.addExcludeCipherSuites(".*ECDH_.*");
scf.addExcludeProtocols("SSL");
scf.addExcludeProtocols("SSLv2");
scf.addExcludeProtocols("SSLv2Hello");
scf.addExcludeProtocols("SSLv3");
scf.addExcludeProtocols("TLSv1");
scf.addExcludeProtocols("TLSv1.0");
scf.addExcludeProtocols("TLSv1.1");
//enabled
scf.setIncludeProtocols(new String[] {"TLSv1.2", "TLSv1.3"});
scf.setIncludeCipherSuites(new String[] {
		"TLS_AES_256_GCM_SHA384",//TLSv1.3
		"TLS_CHACHA20_POLY1305_SHA256",//TLSv1.3
		"TLS_AES_128_GCM_SHA256",//TLSv1.3
		"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",//TLSv1.2
		"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",//TLSv1.2
		"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"//TLSv1.2
});
//TLS renegotiation could be disabled too to prevent an attack based on this feature.
scf.setRenegotiationAllowed(false);
```

Log:
```
2019-03-25 13:03:21.364:INFO::Thread-0: Logging initialized @1677ms to org.eclipse.jetty.util.log.StdErrLog
2019-03-25 13:03:21.709:INFO:oejs.Server:Thread-0: jetty-9.4.15.v20190215; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 11.0.2+9
2019-03-25 13:03:21.771:INFO:oejsh.ContextHandler:Thread-0: Started o.e.j.s.h.ContextHandler@1b43fc78{/stop,null,AVAILABLE,127.0.0.1}
2019-03-25 13:03:21.772:INFO:oejsh.ContextHandler:Thread-0: Started o.e.j.s.h.ContextHandler@11e40211{/other,null,AVAILABLE}
2019-03-25 13:03:21.802:INFO:oejus.SslContextFactory:Thread-0: x509=X509@516382a4(server1,h=[alt1.name.tld, cn1.name.tld],w=[]) for SslContextFactory@1100634b[provider=Conscrypt,keyStore=null,trustStore=null]
2019-03-25 13:03:21.803:INFO:oejus.SslContextFactory:Thread-0: x509=X509@16ba7b8e(server2,h=[alt2.name.tld, cn2.name.tld],w=[]) for SslContextFactory@1100634b[provider=Conscrypt,keyStore=null,trustStore=null]
2019-03-25 13:03:21.951:WARN:oejusS.config:Thread-0: No Client EndPointIdentificationAlgorithm configured for SslContextFactory@1100634b[provider=Conscrypt,keyStore=null,trustStore=null]
2019-03-25 13:03:21.978:INFO:oejs.AbstractConnector:Thread-0: Started ServerConnector@15925715{SSL,[ssl, alpn, h2, http/1.1]}{0.0.0.0:50443}
2019-03-25 13:03:21.979:INFO:oejs.Server:Thread-0: Started @2292ms

Client: No subject alternative DNS name matching alt1.name.tld found.java.io.IOException: No subject alternative DNS name matching alt1.name.tld found.

```
Same error in HttpClient (Java 11) and Firefox

It work fine without Conscrypt OR connecting to alt2.name.tld with Conscrypt is fine, just alt1.name.tld-not work with Conscrypt. I think Conscrypt only use the last cert what is added to keystore.

**Comment by sbordet** [comment]
Have you reported this to the Conscrypt project?
https://github.com/google/conscrypt

**Comment by readonlynetwork** [comment]
Not yet. Is it conscrypt fault?

**Comment by sbordet** [comment]
@readonlynetwork you have tried without Conscrypt and works. You tried with Conscrypt and does not work. Seems a Conscrypt bug to me.

**Comment by readonlynetwork** [comment]
Conscrypt or Integration... I check the source code and seems a Conscrypt bug to me too, sorry.

**Comment by sbordet** [comment]
Then please open an issue at the Conscrypt project and please link it in this issue. Thanks!

**Comment by readonlynetwork** [comment]
New issue: https://github.com/google/conscrypt/issues/644

**Comment by readonlynetwork** [comment]
> We don't yet support that... - Conscrypt

**Comment by sbordet** [comment]
@readonlynetwork thanks for reporting back!

**Comment by readonlynetwork** [comment]
Does it work if I add two SslConnectionFactory with different trust and keystore to ServerConnector? Will the ServerConnector automatical select the right connector like SNI extension?

**Comment by sbordet** [comment]
I'm afraid we don't support either of these features - we only have 1-1 between `SslContextFactory` and `ServerConnector`.

@gregw thoughts?

**Comment by gregw** [comment]
It would be a difficult feature to implement.  SslConnection is initiated with an endPoint and an SslEngine from the SslContextFactory and then let to proceed to negotiate the TLS connection.   If this negotiation failed, then we would need to create a new SslConnection with an SslEngine from a different SslContextFactory and the replay the bytes already consumed.   I guess it is possible, but it looks like significant work which we are unlikely to take on, just to develop a feature that will not be required the moment Conscrypt implements SNI correctly.    I think it probably simpler to put pressure on Conscrypt to implement.... I've given it a +1.

**Comment by joakime** [comment]
Closing this issue as it's specific for Conscrypt and SNI.
The other ideas brought up should be a new issue.
