### ISSUE TITLE
Update Architecture Documentation

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#3490]
The [current Architecture documentation](https://www.eclipse.org/jetty/documentation/9.4.15.v20190215/architecture.html) is rather old and in need of updating. This includes new diagrams as well as a refresh of the 10,000-foot view of Jetty.

**Comment by jmcc0nn3ll** [comment]
@joakime What was that tool we used a long time ago that described graphs in a text file and generated the images during build?  That might be good to wire up here.

**Comment by sbordet** [comment]
@jmcc0nn3ll we should not need many tools - asciidoctor supports a bunch out of the box.
https://asciidoctor.org/docs/asciidoctor-diagram/

**Comment by sbordet** [comment]
This has been reworked entirely in Jetty 10 documentation, so I consider this issue closed.
