### ISSUE TITLE
CustomRequestLog should just be a formatter for logging, so that Slf4jRequestLog can use it too.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3502]
Currently, the CustomRequestLog is the formatter and appender for the custom request logging formatting.

This should be refactored so that the formatting and appending are separate.

The formatting should be able to be reused for both internal RollingFileAppender and also the Slf4jRequestLog.

**Comment by joakime** [comment]
This would allow for an answer to issues like qos-ch/logback#269

**Comment by joakime** [comment]
(For those following links to this issue from elsewhere) the existing `CustomRequestLog` formatting options are listed in the javadoc.

See: https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/CustomRequestLog.html

**Comment by lachlan-roberts** [comment]
@joakime 
CustomRequestLog already has a separation between the formatter and appender. There is the `CustomRequestLog` itself which handles the formatting of the log line, and there is the `RequestLog.Writer` interface which is where the log line is written.

The `CustomRequestLog` is given a  `RequestLog.Writer` in its constructor to use to output the formatted log lines. There are multiple implementations of the writer such as `RequestLogWriter` which uses a `RolloverFileOutputStream`, and there is an `Slf4jRequestLogWriter` which uses an Slf4jLog Logger.

**Comment by joakime** [comment]
Great news!

Guess we should document that :-)

**Comment by lachlan-roberts** [comment]
where should this be documented, I have an unpublished blog post on the CustomRequestLog which is probably more suitable for documentation than a blog post so maybe this could be put somewhere

**Comment by joakime** [comment]
Considering this working as intended.
Example of usage:

``` java
        Slf4jRequestLogWriter slf4jRequestLogWriter = new Slf4jRequestLogWriter();
        slf4jRequestLogWriter.setLoggerName("my.requestlog"); // the slf4j named logger to output to
        // The format of the output. (See javadoc for CustomRequestLog for details)
        String requestLogFormat = CustomRequestLog.EXTENDED_NCSA_FORMAT;
        CustomRequestLog requestLog = new CustomRequestLog(slf4jRequestLogWriter, requestLogFormat);
        server.setRequestLog(requestLog);
```
