### ISSUE TITLE
JMX listener/logging

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3509]
Would be great to introduce a JMX listener, or at least logging (which can be implemented as a logging listener), when the JMX infrastructure invokes Jetty's MBeans.

Applications can then know when JMX methods are invoked (and possibly by whom or at least know the stack trace) and log that activity.

The listener would be invoked for `getAttribute()`, `setAttribute()` and `invoke()` JMX methods, and multiple listeners could be attached to `MBeanContainer`.

**Comment by joakime** [comment]
Seems like this already exists in the JVM ...

* [`java.beans.PropertChangeListener`](https://docs.oracle.com/javase/8/docs/api/java/beans/PropertyChangeListener.html)
* [`java.beans.PropertyChangeEvent`](https://docs.oracle.com/javase/8/docs/api/java/beans/PropertyChangeEvent.html)

**Comment by sbordet** [comment]
@joakime those are not good as they only convey information for bean _property_ changes.
For JMX we would need JMX metadata and cover the `invoke()` semantic.

**Comment by joakime** [comment]
for JMX Attributes there's already ...

* [`javax.management.AttributeChangeNotification`](https://docs.oracle.com/javase/8/docs/api/javax/management/AttributeChangeNotification.html)
* [`javax.management.AttributeChangeNotificationFilter`](https://docs.oracle.com/javase/8/docs/api/javax/management/AttributeChangeNotificationFilter.html)

For a JMX Operation, that would just be a normal [`Notification`](https://docs.oracle.com/javase/8/docs/api/javax/management/Notification.html) and [`NotificationListener`](https://docs.oracle.com/javase/8/docs/api/javax/management/NotificationListener.html)

Wouldn't it make more sense to ensure support for what's already there vs creating a new API that only works with our MBean layer?

**Comment by sbordet** [comment]
I'll look into this.

**Comment by joakime** [comment]
I just tried it, it would require each MBean that we care to listen to, to implement the `javax.management.NotificationBroadcaster`.
These exist, but it's not like it's all that easy to use.

**Comment by sbordet** [comment]
No, `AttributeChangeNotification` must be emitted by the MBean implementation itself.

We don't do that in `ObjectMBean` ourselves.

There is no standard for operation notifications.
It would be impossible to detect if a notification is emitted as a result of a JMX invocation (e.g. carrying method name and the result if the invocation), or as a result of some other event emitted by the MBean (e.g. timer events or other events that follow an invocation).

Both `AttributeChangeNotification` and `OperationInvocationNotification` could be implemented in a listener.

For non-`ObjectMBean`s, unfortunately, we won't have these new events.

**Comment by sbordet** [comment]
There are 2 approaches:

1. Introduce `ObjectMBean.Listener` as a custom interface so that application can register listeners and be notified of attribute events or invocation
1. Use JMX built-in `NotificationEmitter` support and base as much as possible on JMX classes such as `AttributeChangeNotification`. Unfortunately there is no event for operation invocation, which means that the API has be to based on `Notification.getUserData()` to be a `Map` with a number of predefined keys for objects that applications may need (e.g. the invoked method name, parameters list, invocation result, etc.)

While would be nice to base the implementation of already existing JMX support, it is really too basic and cumbersome. However, it may be supported by tooling that understand JMX notifications so there would be some merit using JMX notifications.

**Comment by sbordet** [comment]
See also comments in #3517.

**Comment by sbordet** [comment]
Also, I think `MBeanServer` supports interceptors, it could be an alternative way of supporting this feature.
