### ISSUE TITLE
HttpClient parameters Info for help

### ISSUE THREAD

**Issue by ltp217** [eclipse/jetty.project#3511]
In Jetty 9.4.14 client, there are many params in HttpClient, like idleTimeout, requestBufferSize,
connectTimeout, and so on. I also can config them, but I don't understand the meaning of them, Is there any reference material that I can figure them out? BTW, when create an idle connection ,if it's not used , when it will be removed, can I config it with any param?

**Comment by sbordet** [comment]
@ltp217 the meaning of those parameters is explained in the Javadocs.

Have you read https://www.eclipse.org/jetty/documentation/9.4.x/http-client.html?

**Comment by ltp217** [comment]
@sbordet yeah, I have read the website before, but I found for jetty client, there're less reference materials than as server, do you have any other suggestions for learning jetty client Systematic?

**Comment by sbordet** [comment]
@ltp217 we can improve the documentation (or you can submit a PR), but most of the features in `HttpClient` are self-speaking.

If you are confused, please detail exactly what you are confused about, and we will improve the documentation.

**Comment by ltp217** [comment]
@sbordet  ok, I should read the source code with the documentation, tks.

**Comment by sbordet** [comment]
@ltp217 reading the source code is ok, but can be confusing or difficult.

As I said, we are all for improving the docs, but frankly you did not say exactly what problems you have encountered.

Explain what you want to do, tell us what you have done, and tell us what problems or difficulties you have found, and we'll improve documentation and examples.

**Comment by ltp217** [comment]
@sbordet  For now, I have two questions:
1.when jetty-client create a new connection, if it is not used, when it will be recycled, is there any parameter for this (like the keep-alive timeout).  

2. could you simply explain when sending a request ,how it will be responsed, like when it will in the task queue, and when it will get/create a connection,  when a connection handled a request, it will back to the conncetionpool or it will get the task from the task queue ?  when the server set the keep-alive timeout like 60s, will it get the EOFException occasionally?

**Comment by sbordet** [comment]
1. idle connections are closed after the `HttpClient.idleTimeout`, otherwise they are pooled.
2. a request is first queued, waiting for a connection to be available; if there are no connections available, a new connection is created (and it may take a while) and when it's created it will be put in the pool; at this point there is a connection available from the pool (either newly created or pooled previously), and it will be used to send the request and read the response; when both the request _and_ the response have been completed, the connection is put back into the pool.

You can be notified of the events listed in 2. via `Request.Listener` and `Response.Listener`.

`EOFException` is only thrown if a connection is closed and the correspondent request or response is not completed.

**Comment by ltp217** [comment]
@sbordet  Thanks, and I have found that when a request is finished, the connection will put back to the idleConnections, and it's a Deque, it uses offerFirst method to ensure use the "hot" connections first. 

But in some scenarios, when a request is coming, and there is no idle connection, so it needs to create a new `connection A`, this connection will put in the `idleconnection`, at this time,the `activeconnection` have handled the other request ,so it will use offerFirst method to put this `activeconnection B` to the `idleconnection`,  when handle the request ,it will use `connection B`, for after the `idletimeout`, `connection A` may be never used, another request may get this `connection A` when this connection is running timeout logic, after that `connection A` is closed, but the request have get it, at this time it will throw `EOFException`. I am confused about this scenes.

**Comment by ltp217** [comment]
@sbordet Thank you, and I think I have got it now, for this scenario maybe we should set the keep-alive timeout longer than the idletimeout.
