### ISSUE TITLE
CustomRequestLog support for preferProxiedForAddress

### ISSUE THREAD

**Issue by ben-manes** [eclipse/jetty.project#3516]
`Slf4jRequestLog` supports using the `X-Forwarded-For` header when logging the address, falling back to the client's host (`request.getRemoteHost`) if not set. This doesn't appear to be a supported option in `CustomRequestLog` (`server`, `client`, `local`, `remote`).

**Comment by joakime** [comment]
Sounds like you don't have `SecureRequestCustomizer` configured.

**Comment by ben-manes** [comment]
I am upgrading from `9.4.14` to `9.4.15` and `Slf4jRequestLog` is deprecated. I currently have the following, and from `CustomRequestLog` I am unsure how to migrate this appropriately. 

```java
private void addLogger(Server server) {
  var requestLog = new Slf4jRequestLog();
  requestLog.setPreferProxiedForAddress(true);
  requestLog.setLogLatency(true);
  server.setRequestLog(requestLog);
}
```

I do have `SecureRequestCustomizer` added to `HttpConfiguration` with its default constructor when setting up the connection. I don't see any relevant setting in `SecureRequestCustomizer` regarding this topic, but I may have missed something.

Can you provide a hint on how to migrate to the new logger class and retain the prior behavior?

**Comment by ben-manes** [comment]
Perhaps you meant `ForwardedRequestCustomizer`? I don't have that configured, and can if that is the recommended solution. If so, it would be great if you updated the `Slf4jRequestLog` deprecation to include that hint.

**Comment by joakime** [comment]
Yes, you are correct.
I meant `ForwardedRequestCustomizer`, that's the one that adjust the HttpServletRequest to fit the information presented in the various Forwarding headers.

As for adjusting the behavior of your code ...

``` java
        // What writes the log events
        Slf4jRequestLogWriter slf4jRequestLogWriter = new Slf4jRequestLogWriter();
        slf4jRequestLogWriter.setLoggerName("my.requestlog");

        // The format of the output.
        String requestLogFormat = CustomRequestLog.EXTENDED_NCSA_FORMAT;

        // Look at the javadoc for CustomRequestLog
        // There is no special case handling of "proxiedForAddress", relies on ForwardRequestCustomizer
        // For Log Latency, see "%D" formatting option
        CustomRequestLog requestLog = new CustomRequestLog(slf4jRequestLogWriter, requestLogFormat);

        // add request log implementation to server 
        server.setRequestLog(requestLog);
```

**Comment by ben-manes** [comment]
Thank you. That was what I had figured out, except I hadn't known about `ForwardRequestCustomizer`. I think it would be helpful if the JavaDoc of either the old or new request logger included that hint to assist migrations.
