### ISSUE TITLE
request locale not retained in WebsocketUpgrade request

### ISSUE THREAD

**Issue by stuban** [eclipse/jetty.project#3526]
The org.cometd.bayeux.server.BayeuxContext from cometd offers a getLocales() method wich is to supposed to return a list of request locales (or a server default locale).
When using the JettyWebSocketTransport as transport it always returns an empty list.

I opened the bug here (and not on cometd) because it relies on the org.eclipse.jetty.websocket.servlet.UpgradeHttpServletRequest which copies over a lot of the original properties but not the locales from the original request.
Was this overlooked or do I miss something here?

**Comment by sbordet** [comment]
@stuban good catch. Jetty forgets to copy the locales from the `HttpServletRequest` to the `UpgradeHttpServletRequest`.
