### ISSUE TITLE
Jetty Client doesn't forward authentication headers with redirects when using proxy

### ISSUE THREAD

**Issue by artur-c** [eclipse/jetty.project#353]
Jetty Client 9.3.7.v20160115 doesn't send authentication headers when a target site responds with 302 HTTP code. 
To be precise, the communication scheme is as follows:
 - a jetty client sends http request
 - a proxy responds with authorization required header
 - the jetty client sends the request to the proxy with authorization header
 - proxy sends the request further
 - the target server responds with 302 HTTP code
 - the jetty client understands 302 HTTP code and executes sendRedirect() method, which calls copyRequest(), which removes authentication headers

PS. In Jetty 8.1.17.v20150415 it worked perfectly.

**Comment by sbordet** [comment]
I don't think this set of steps is correct.

The proxy cannot reply to a URI with a 401 without contacting the origin server, and then when the origin server is contacted for real, it responds with a 302.

Imagine the client sends the credentials following the 302. If, for any reason, the redirect goes to another server, then that server will have the client's credentials.
Looks like a security hole to me.

The right way would be for the proxy to contact the origin server for the given URI, forward the 302 to the client, which will follow it, requesting the new URI, which the proxy forwards to the origin server, which at that point may return 401 and the whole thing will work properly.

**Comment by artur-c** [comment]
> The proxy cannot reply to a URI with a 401 without contacting the origin server, and then when the origin server is contacted for real, it responds with a 302.

I'm sorry if I wasn't clear enough in my previous post but 401 comes from proxy.

The scenario:
A client sends a request to the proxy with authentication header, proxy sends the request further. The target server replies with 302. The proxy forwards response from the target server to the client. At this point, the client receives 302. It tries to connect to a new URI through proxy but this time authentication header is gone and proxy complains.

**Comment by sbordet** [comment]
Why the proxy complains ? It seems to be correct that if the client sends the credentials to mybank.com and gets a 302 to google.com, then the client should not send the bank credentials to google.
Even if it is the same domain, the redirect could send to a URI that does not require authentication, or requires a different one, etc.

I don't understand how the proxy can return 401 without contacting the server. Is this proxy authentication or server authentication ?

**Comment by artur-c** [comment]
I agree with the scenario you described since it would be security problem to send credentials to the target site. 
At the company I work there is a proxy server that every request goes through if one wants to send a request from intranet to the Internet. The proxy requires my credentials to allow for sending the request to the target site, let it be google.com. I configured Jetty Client to use the company's proxy and sent a request with URI: google.com. As far as I understand what happened next was that the request was captured by the proxy server at my company and authentication challenge started. The proxy responded that it requires a sender to be authenticated, Jetty found the proxy configuration and sent the same request as before but this time with Proxy-Authorization header set with my credentials. The proxy validated my credentials and sent the request further to google.com. Google replied with 302 HTTP code and since Jetty has configured follow redirects it tried to sent the original request to a new URI(google.pl). The new request was also intercepted by company's proxy but this time Proxy-Authorization header was not present in the request.
I compared headers generated by Jetty 8 and 9 and version 8 sents Proxy-Authorization header with second request but Jetty 9 does not.

**Comment by sbordet** [comment]
Ok, so it's proxy authentication, not server authentication.
Are you sure the proxy replies with a 401 ? It should reply with a 407.

**Comment by artur-c** [comment]
Yes, the proxy replies with 407.

**Comment by sbordet** [comment]
I need the client DEBUG logs.

**Comment by artur-c** [comment]
Here you are:

[log.txt](https://github.com/eclipse/jetty.project/files/144559/log.txt)

**Comment by sbordet** [comment]
I just added a test case that already works perfectly fine.
I don't understand how you can get those logs without the `Proxy-Authorization` header.
I can reproduce a similar sequence of requests like yours, except that mine has the correct headers.

Since I cannot access your proxy, can you please try to debug what happens to you, in particular `HttpConnection.normalizeRequest()` towards the end of the method. In that method there is the logic to add the `Proxy-Authorization` header, which works fine for me, but evidently not for your particular case.

**Comment by artur-c** [comment]
It looks like the following code is problematic:
`Authentication.Result authnResult = getHttpClient().getAuthenticationStore().findAuthenticationResult(authenticationURI)` since authnResult is null. 
I checked my configuration and it looks like this:
`Origin.Address proxyAddress = new Origin.Address(httpConfig.get(HttpConstants.PROXY_HOST), Integer.parseInt(httpConfig.get(HttpConstants.PROXY_PORT)));
HttpProxy httpProxy = new HttpProxy(proxyAddress, false);
proxyConfiguration.getProxies().add(httpProxy);'

Then I configure BasicAuthentication by passing uri as this:
`URI.create("http://" + httpConfig.get(HttpConstants.PROXY_HOST) + ":" + httpConfig.get(HttpConstants.PROXY_PORT));`

I debugged the code and it turned out that passing port to the URI makes findAuthenticationResult() return null. 

So it looks like this problem can be solved by changing my configuration, but I am not sure whether this breaks anything else in Jetty?
I am also not convinced with API, since it looks like Origin.Address structure requires a port but URI passed to BasicAuthentication does not otherwise it will fail.

**Comment by sbordet** [comment]
I don't understand exactly what do you mean by "passing port to the URI makes findAuthenticationResult() return null" ?

If your proxy is "proxyHost:3128", then both `Origin.Address` and the URI will have 3128 as port.

What is the port of your proxy ?

**Comment by artur-c** [comment]
The port is 80. 
I noticed that a method URIUtil.appendSchemeHostPort() doesn't append port if scheme is http and port is 80. Thus there are two URIs: one in BasicAuthenticationStore with port and one that comes as an argument to BasicAuthenticationStore.matches() method without it. Since the logic in matches() is uri.toString().startsWith(this.uri.toString()) this will not be true in this case.

**Comment by sbordet** [comment]
Got it. Stand by for a fix.

**Comment by sbordet** [comment]
Fixed by taking into account default HTTP ports when comparing URIs.
