### ISSUE TITLE
Produce warning when attempting RFC8441 - WebSocket over HTTP/2

### ISSUE THREAD

**Issue by japgolly** [eclipse/jetty.project#3530]
I see from https://github.com/eclipse/jetty.project/issues/1364 that WebSockets over HTTP2 is not supported. Unfortunately if you don't already know that (and realise that's what's being attempted) it's really, really hard to discover it. I just spent ~8 hrs debugging before finally arriving at the above ticket and realisation because there's nothing to indicate such in Jetty's logging, javax.net debug output, or the Chrome/Firefox consoles. Everything seems to just work except that it doesn't.

In order to help others in the future, it'd be pretty helpful if, when Jetty detects a WS upgrade request over HTTP2, it would log some kind of WARN message.

It's weird that browsers don't just try to use HTTP 1.1 when connecting to `wss://...` if the page was loaded over HTTP2. In any case I finally got things to work by switching the `http2` module to just `https`. If that's the ultimate recommended solution then it would be nice to suggest it in the logging too.

**Comment by gregw** [comment]
... or better yet we could just implement support for websockets over http2 (@lachlan-roberts !) 
but in the meanwhile a warning is a good idea!  Looks like @joakime  is on it!

**Comment by sbordet** [comment]
https://tools.ietf.org/html/rfc8441

**Comment by lachlan-roberts** [comment]
I will start looking into it

**Comment by joakime** [comment]
Opened PR #3532

**Comment by joakime** [comment]
Work completed in `jetty-9.4.x` via commit 7ee8b10aec90533ae43fbcf0357ed46633626c04

**Comment by japgolly** [comment]
Wow  awesome, thank you!
