### ISSUE TITLE
Unexplained delay in the execution of most queries

### ISSUE THREAD

**Issue by bdevost** [eclipse/jetty.project#3533]
Hi, 

We use HAProxy with regular and aggressive L7 checks over embedded Jetty service with RestEASY. 

Over the last year, we've observed backends being disabled by the health check very regularly, to the point where we had to start investigate why. To correlate the information we had, we started tracking the health check with Zabbix. 

It turns out that Jetty occasionally takes a (up to) 3 seconds pause before selecting an incoming connection. I can't understand exactly why this is, but I could reproduce it with 

jetty-9.4.15.v20190215; jvm 11.0.2+9-LTS

on a very simple Hello World style service (without RestEASY as well). It happens both on Windows and Linux, and the earliest versionI could observe it on is 9.3.6.v20151106 (previous version were never tested in the application).

![2019-04-08 10_52_01-Greenshot](https://user-images.githubusercontent.com/43377232/55737746-cb0c0b80-59f3-11e9-9740-b732168e3cdf.png)

This is a service with litterally no other load than one health check every 3 minutes. We've had that reproduce on systems with heavy load as well.

I am curious to know if you've seen this before and if so, how it can be fixed.

**Comment by joakime** [comment]
Are the health checks done against TLS?  If so, disable TLS/1.3 on your Jetty running on Java 11.0.2 - https://webtide.com/openjdk-11-and-tls-1-3-issues/

Are you logging your GC behaviors?
Do the GC behaviors on the JVM correlate to the 3 second pause (a 3 second pause seems very much like a poorly tuned GC with large stop-the-world GC events)

**Comment by sbordet** [comment]
Do you have a Full GC that is taking 3 seconds in your GC logs?

Do you have THP (Transparent Huge Pages) enabled?

The option we recommend is to run jHiccup on the system to understand who's pausing and see if the hiccup pauses match the Jetty pauses.

**Comment by bdevost** [comment]
Thanks for the quick replies;

Health checks are done both in http and https, and both fail at the same time usually, leading me to believe this is not Connector-based.

I was not logging the GC up to now, but could not reproduce the issue by triggering Garbage Collection from JConsole through jmx (the behavior shows with or without jmx setup). I have been suspecting the GC for a while but it seems like a stretch since there is nothing happening in the server. 

FYI the server runs in production with the following parameters: -XX:+DoEscapeAnalysis -XX:+UseG1GC -XX:MaxGCPauseMillis=200.

I will try to log the garbage collecting activity in the basic service implementation to see if I can correlate the issues.

I'll check for THP on on Linux boxes, but I can reproduce on Windows so I don't expect that's the issue here specifically.

I will be running jHiccup and try to reproduce but I can't seem to find how I will help me tie back to what is pausing jetty?

**Comment by sbordet** [comment]
jHiccup will tell you if it's a JVM internal pause, or something that happens externally.

RMI also performs regular Full GC every hour or so. You want to check that that is not happening.
Options such as `-XX:+ExplicitGCInvokesConcurrent` will help in such cases.

**Comment by joakime** [comment]
@bdevost it's generally good practice to log GC events in production, always (not in a temporary sense, but always).
Many organizations will even graph the GC event details (size, duration, frequency, etc) along with their other performance metrics.
analysis of those logs can tell you a fair bit about your app, and when you need to make alterations.

**Comment by bdevost** [comment]
Thank you all for the tips, it helped me drill down a few more ways. So, a few interesting things about the issue:

- Even using verbose gc logs, I could not match GC pauses to the 3s delays I'm observing (the longest GC pause in 115h is 1.290 s, and it nowhere near the 3s pause I could observe in the same timelapse. There is no corelation between any kind of GC pause and the request delays.
- Adding  -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -XX:+ExplicitGCInvokesConcurrent to my initial -XX:+UseG1GC DID have some effect on the process. Pauses are still as long, but happen a lot less often. I've just had a 50h run without any pause, which is the longest I've observed in the control enviroment.
- XX:+ExplicitGCInvokesConcurrent might not have a huge impact since only 3.24s of GC out of 66.59s were concurrent.
- Pause time total was 1 min 2s 350 ms over 115h, with an average of 87.9 ms, stdev 128 ms. Those specs sound really healthy to me right now.

This then seems to be revolving around the GC, but I can't identify a clear causality link.

**Comment by sbordet** [comment]
You want to keep `-XX:+ExplicitGCInvokesConcurrent` in case something calls `System.gc()` (for example RMI), otherwise you risk going into Full GCs.

Other than that, you may want to try to add `-XX:+PrintGCApplicationStoppedTime` which - despite the name - print safepoint time.
It could be that you're suffering of some form of time-to-safepoint pause.

What's the Jetty thread pool configuration?

**Comment by bdevost** [comment]
I planned on keeping -XX:+ExplicitGCInvokesConcurrent already/

I will try printing the StoppedTime to see if I can find correlation. 

I use something fairly standard for the thread pool configuration:

this.queue = new ArrayBlockingQueue<>(webConfig.requestQueueSize());
this.threadPool =  new QueuedThreadPool(webConfig.maxThreads(), webConfig.minThreads(), appConfig.defaultTimeout(), queue);

web.requestQueueSize = 256
web.minThreads = 256
web.maxThreads = 512
app.defaultTimeout = 30000

Thank you kindly.

**Comment by sbordet** [comment]
Ah, the `ArrayBlockingQueue` setup is typically wrong.

You don't want to limit the thread pool queue, because it may need to queue spikes of load of small and fast tasks that _needs_ to be executed.

That is probably the source of your pauses.

I recommend that you use the default configuration - i.e. an unbounded Jetty's `BlockingArrayQueue` that also outperforms JDK's `ArrayBlockingQueue`.

**Comment by djelinski** [comment]
The pattern visible on the graph (requests take either 0 or 3 seconds, nothing in between) usually indicates that time is spent waiting on / retransmitting data lost on the network. GC pauses would display at least some variability.
Since this happens frequently even on low load servers, you could capture this in tcpdump to verify.

**Comment by sbordet** [comment]
@bdevost going to close this issue due to inactivity - reopen if you still have the problem.
