### ISSUE TITLE
WebSocketClient deos not allow to change the size of text messages

### ISSUE THREAD

**Issue by acaproni** [eclipse/jetty.project#3536]
I have written a java class that sends big strings to the web server but the socket is closed with this message

``` WebSocket connection closed. status: 1009, reason: Text message size [75508] exceeds maximum size [65536]```

The `OnError` method shows the following:

```[WebServerSender.java:436] [WebSocketClient@60768217-100] Error from websocket
org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
        ..........
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        ........```

I tried setting a bigger maximum size of the text buffer in many ways (annotation and sets in the client and in the policy) but none of them worked.

This is a snippet of my class:

```
@WebSocket(maxTextMessageSize = 1000000,maxBinaryMessageSize = 1000000, inputBufferSize = 1000000) // About 1000 IASValues
public class WebServerSender  {

    private WebSocketClient client;

	@OnWebSocketConnect
	public void onConnect(Session session) {
	   sessionOpt = Optional.ofNullable(session);
	   this.connectionReady.countDown();
	   socketConnected.set(true);
	   logger.info("WebSocket got connect. remoteAdress: " + session.getRemoteAddress());
   }
    private void sendStringToWebsocket(String str) {

        sessionOpt.ifPresent( session -> {
            String strToSend=str;
            try {
            	session.getRemote().sendString(strToSend);
				logger.debug("{} IasValues sent" + iasValuesInString);
			} catch (IOException ioe) {
            	logger.error("Error sending,ioe);
			}
        });
    }

	public void connect() {
		try {
			sessionOpt = Optional.empty();
			this.connectionReady = new CountDownLatch(1);
			client = new WebSocketClient();
			client.getPolicy().setMaxTextMessageSize(1100000);
			client.getPolicy().setMaxBinaryMessageSize(1100000);
			client.setMaxBinaryMessageBufferSize(1400000);
			client.setMaxTextMessageBufferSize​(1500000);
			client.start();
			client.connect(this, this.uri, new ClientUpgradeRequest());
                        logger.info("WebSocketClient after connecting, {} , {}, {}, {}",
					client.getMaxTextMessageBufferSize(),
					client.getMaxTextMessageSize(),
					client.getMaxBinaryMessageBufferSize(),
					client.getMaxBinaryMessageSize());
		}
		catch( Exception e) {
			logger.error("Error on WebSocket connection", e);
		}
	}
}
```

The output shows that the sizes are all taken by client:

```18:39:03.134 |INFO | [WebServerSender.java:590] [main] WebSocketClient after connecting, 1500000 , 1100000, 1400000, 1100000```

But the socket gets closed because the size of the string is too big.

I am using the following jars:
- jetty-client-9.4.15.v20190215.jar
- jetty-io-9.4.15.v20190215.jar
- websocket-api-9.4.15.v20190215.jar
- websocket-common-9.4.15.v20190215.jar
- jetty-http-9.4.15.v20190215.jar
- jetty-util-9.4.15.v20190215.jar
- websocket-client-9.4.15.v20190215.jar

**Comment by sbordet** [comment]
Isn't the server closing the connection because the message is too big? 
If that's the case, you should configure the server.

**Comment by joakime** [comment]
I agree with @sbordet , this looks like the server is rejecting what the client is sending (the complete client stacktrace would be a confirmation on this).
Check your server side settings for those endpoints for their max message sizes.

**Comment by acaproni** [comment]
Yes, both of you are right.
I close the ticket. Thank you a lot.
