### ISSUE TITLE
Spin loop in case of exception thrown during accept()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#354]
`ServerConnector.accept(int)` may thrown an exception (typical case could be "Too many open files").

If this happens, the current code catches the exception, logs it and tries to call `accept()` again potentially resulting in a spin loop.

**Comment by sbordet** [comment]
@gregw I need review on this.

I introduced an overridable method with a `Thread.sleep(1000)` to avoid spin looping.

I am not sure it is worth more, because the error could be recovered (so closing altogether is not an option), and backoff policies may become complicated (linear, exponential, constant ?).

If you think we're good with my fix, please close the issue.

**Comment by gregw** [comment]
LGTM.  I think there was another similar issue which I will link and close.
