### ISSUE TITLE
hi Joakim Erdfelt, When to publish jetty 9.4.16 jar ?

### ISSUE THREAD

**Issue by woniu56432** [eclipse/jetty.project#3546]
hi Joakim Erdfelt:

I see Jetty 9.4.16 source code has been released, but Jetty 9.4.16 Jar has not been released, Jetty Jar can be released as soon as possible?

**Comment by woniu56432** [comment]
@joakime

**Comment by olamy** [comment]
any questions must go to mailing list https://www.eclipse.org/jetty/mailinglists.html
thanks

**Comment by joakime** [comment]
@woniu56432 as [pointed out before in the jetty-users mailing list](https://www.eclipse.org/lists/jetty-users/msg08765.html).

> github makes all git tags into "releases".
> But that's invalid, not all tags are releases.
> 
> The tag `jetty-9.4.16.v20190410` was created for a staged / in testing / potential release.
> Once that staged / potential release has been accepted by the various testers it gets promoted to "release" status.
> When that happens, the potential release moves from staging into the actual release process.
> This includes:
> * all artifacts are placed on maven central.
> * jetty-distribution artifact is placed on eclipse downloads.
> * final documentation is generated and placed on eclipse.org website.
> * final apidocs are placed on eclipse.org website.
> * announcement on jetty-announce mailing list (with CC on jetty-dev and jetty-users mailing list)

In short, it's not an official release until it's announced and shows up in the official places.
