### ISSUE TITLE
Property from start.ini is null in context configuration

### ISSUE THREAD

**Issue by boughtonp** [eclipse/jetty.project#3548]
Defining a property inside start.ini should (according to `start.jar --help`) be available to the `Property` tag in XML files, but the example below demonstrates this only working if defined as a system property.

start.ini
```
test.prop=testprop
-Dtest.sysprop=testsysprop
--module=deploy
--module=http
```

webapps/test.xml
```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="resourceBase"><Property name="test.prop" />/path</Set>
</Configure>
```

webapps/systest.xml
```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="resourceBase"><SystemProperty name="test.sysprop" />/path</Set>
</Configure>
```

Running `java -jar ../jetty-distribution-9.4.16.v20190411/start.jar` the relevant output shows only the system property works:
> 2019-04-14 16:14:22.786:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@52a86356{/,file:///S:/jetty/property-testing/testsysprop/path,AVAILABLE}
> 2019-04-14 16:14:22.817:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@59906517{/,file:///S:/jetty/property-testing/null/path,AVAILABLE}

**Comment by joakime** [comment]
This is expected behavior.

The start properties (ones from `start.d/*.ini` and `start.ini` and command line) are not retained for other parts of the jetty lifecycle, such as the ones from the DeploymentManager (which happens after start) and the context XMLs  found in the `${jetty.base}/webapps/*.xml` files.

It could, in theory, be maintained via some cooperation between the `org.eclipse.jetty.deploy.PropertiesConfigurationManager` and the `start.jar`
How it would work is that the `start.jar` takes its resolved list of active properties, writes it to say `${jetty.base}/etc/start.properties` and then the `WebAppProvider` configuration is tweaked to include ...

``` xml
        <Set name="appProviders">
          <Array type="org.eclipse.jetty.deploy.AppProvider">
            <Item>
             <New class="org.eclipse.jetty.deploy.providers.WebAppProvider">
              <Set name="monitoredDirName"><Property name="jetty.base" />/webapps</Set>
              <Set name="scanInterval">20</Set>
              <Set name="configurationManager">
                <New class="org.eclipse.jetty.deploy.PropertiesConfigurationManager">
                  <Set name="file">
                    <Property name="jetty.base"/>/etc/start.properties
                  </Set>
                </New>
              </Set>
             </New>
            </Item>
          </Array>
        </Set>
```

**Comment by joakime** [comment]
An alternative approach would be to have `XmlConfiguration` have a system property that is used to preload all properties before and `XmlConfiguration` is executed within that JVM.
This would have the benefit of working in more places that `XmlConfiguration` is used (over the single location of `WebAppProvider`)

@janbartel what do you think of this approach?

**Comment by janbartel** [comment]
The user has already found that if you set a system property, that can be accessed at any point in the start up lifecycle, whereas a module property cannot. Thus, it could be argued that there is already a way to access module information from outside that module.  Similarly, it could be argued that if we automatically made module properties accessible outside of the module system, then that could be considered leaking information.  So, it seems to me that all we need to do is to correct the documentation to make clear that properties in modules can only be used in xml files declared in modules?

**Comment by boughtonp** [comment]
In so far as system properties work and are considered a valid approach, I'm fine with doing it that way.

But it would be good if the docs say a bit more than not being able to use module properties outside of module xml files - I'm not sure if I've wrapped my head around what is the difference between start properties and module properties and where the boundaries between different property "types" are.

Like when jetty.http.port is set as a start property, it appears to be passed through to the http module, and inside {base}/etc/jetty-deploy.xml it works if you swap jetty.deploy.monitoredDir for jetty.http.port, but it's not available inside webapps xml.

That suggests it may work in layers, like [start]->[module]->[webapps], and the start properties only get passed one layer deep, whilst system properties go the whole way? Or is there more to it than that?

And jetty.home and jetty.base are special cases that act like system properties and work everywhere*, but are not actually and can be accessed with (non-system) Property tag.

*Do system properties work everywhere, or only in XML? There's no mention of a `${pname}` equivalent syntax, so I'd guess the latter.

A brief section in the documentation which confirmed/corrected these things would be great.

**Comment by boughtonp** [comment]
This issue is still valid (should not be closed yet), unless the documentation has been updated as per Jan's comment:
> [we need to] correct the documentation to make clear that properties in modules can only be used in xml files declared in modules?

I cannot verify this with the online documentation because there's a broken redirect (raised at https://github.com/eclipse/jetty.website/issues/3) but checking local v9.4.26 docs I don't see any relevant changes.
