### ISSUE TITLE
DefaultHandler should not reveal base resource

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3555]
When you have an environment where the DefaultHandler has to produce an error page showing the list of contexts, the base resource directory of each context is revealed.

**Comment by joakime** [comment]
Similar to what was found in Issue #3549 - this is an information reveal

**Comment by joakime** [comment]
Work completed in `jetty-9.2.x` and merged up to `jetty-9.4.x`.
This will be present in the next release.

**Comment by joakime** [comment]
Old DefaultHandler (with issue) presents as ...

![default-handler-error-old](https://user-images.githubusercontent.com/191721/56389861-48076400-61f0-11e9-9518-302aaaf49e75.png) 

New DefaultHandler presents as ...

![default-handler-error3](https://user-images.githubusercontent.com/191721/56302210-eadfb580-60fe-11e9-8d1e-2978b7c540b4.png)

**Comment by carlspring** [comment]
Hi @joakime ,

What's the next version in which is going to be included and when is it scheduled for?

**Comment by joakime** [comment]
@carlspring already available in ...

* 9.2.28.v20190418
* 9.3.27.v20190418
* 9.4.17.v20190418

Announced in jetty-announce mailing list - https://www.eclipse.org/lists/jetty-announce/msg00130.html

**Comment by carlspring** [comment]
@joakime ,

Thank you very much for confirming! :)
All the best!
