### ISSUE TITLE
InetAccessHandler should be able to apply to a certain port or connecdtor

### ISSUE THREAD

**Issue by nddipiazza** [eclipse/jetty.project#3561]
I often want to use the InetAccessHandler so that it will block HTTP from everyone except a small white list, but I want HTTPS to be globally allowed.

Is this possible? 

Is there some way we can add this as a parameter to the new module created here?  https://github.com/eclipse/jetty.project/commit/3a4da94e1a69ee4c9cd3c936f50d58ee3440188e

**Comment by sbordet** [comment]
Closing, see #3562.

**Comment by nddipiazza** [comment]
hi sorry - had a network blip and accidentally created it twice
