### ISSUE TITLE
UrlEncoded.encodeString() doesn't handle URI space properly

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3565]
UrlEncoded.encodeString() will convert `" "` (space) to `"+"` which is invalid for URI encoding, that's a deprecated feature of `application/x-www-form-urlencoded` and shouldn't be used.

Proper URI encoding of paths should always use `"%20"`.

This is broken at least as far back as `jetty-9.2.x`

**Comment by joakime** [comment]
Some interesting observations ...

* Browsers (chrome + firefox) will not use `"+"` in their location bar if a space is used, they will use `"%20"`.  this makes sense as the location bar is not subject to `x-www-form-urlencoded` behaviors.
* Browsers (chrome + firefox) will encode `"+"` to `"%2B"` on the Location bar before issuing the HTTP request (see network inspection panel).
* Jetty will not parse the character `"+"` as a space when parsing the HTTP Request Line URI.  It will remain a `"+"` character.

Per https://tools.ietf.org/html/rfc3986#appendix-D.2 the `"+"` is listed as deprecated syntax for URIs

**Comment by joakime** [comment]
The existing `UrlEncoded.encodeString()` isn't following `x-www-form-urlencoded` rules properly.

See: https://url.spec.whatwg.org/#concept-urlencoded-byte-serializer

We should (at least) expand the characters we don't percent-encode with `'_', '.', '-', '*'`. (from above link)

**Comment by joakime** [comment]
Since UrlEncoded is javadoc documented to be specifically for `x-www-form-urlencoded`, perhaps we should introduce a `UriEncoded` class which handles things according to the URI spec RFC3986?

**Comment by sbordet** [comment]
@joakime in `jetty-client`, `FormContentProvider` uses `java.net.URLEncoder`.
Where else do we need to encode following `x-www-form-urlencoded`?
On the server I would expect to just decode it.

**Comment by gregw** [comment]
As far as I can see, the encode side of this class is now only used for CGI

**Comment by joakime** [comment]
In that case, we should deprecate all of the `encode()` methods in 9.x and remove them in 10.x (or move it to CGI for specific `x-www-form-urlencoded` behavior?)

**Comment by joakime** [comment]
A review shows that the various encode methods in URIUtil are sufficient to solve for the bug.
But the cleanup / deprecation of encode methods in UrlEncoded should probably still be done.

**Comment by joakime** [comment]
Closing as original reported issue is misplaced.
We have a `URIUtil` class that does this properly for request line.
`UrlEncoded` is still used for `x-ww-form-urlencoded` content, where space handling is consistent.
