### ISSUE TITLE
Context Path with ';' is handled oddly

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3566]
If you have a context path such as `"/;ZZZ"`, then all paths on that context path will have `;ZZZ` appended to it when Jetty is processing those URLs.

See: DefaultHandler or ResourceHandler directory listing

**Comment by gregw** [comment]
Are you saying a context that is configured with a context path `/;ZZZ`?    I don't think we should allow that as I'm not sure what it means to have path parameters in a context?  Is that saying we will only match requests that have that path parameter?

I think we should just throw an IAE if such a context path is set.

**Comment by janbartel** [comment]
@joakime  I think we need more info.

I configured the test webapp with the context path "/;test" - whilst this deploys, requests to http://localhost:8080/;test only ever match the root context, as expected.

If I configure the test webapp normally with context path "/test", but make a request to list the contents of a directory called "foo" with a request like http://localhost:8080/test/foo/;xyz I don't see the path params ";xyz" appended to the links to any of the files listed.

**Comment by joakime** [comment]
@janbartel This was filed when working issue what a strange setup like this ...

```
[listing-odd-base]$ tree
./
├── start.ini
├── webapps/
│   └── ;ZZZ/
│       ├── alt/
│       ├── deep/
│       ├── example.css
│       ├── example.js
│       └── example.png
└── work/
```

with `start.ini` of ...

```
--module=http
jetty.http.port=8080
--module=deploy
```

When I filed this issue, the `/;ZZZ` would be remembered, as a path parameter, and all requests would include the ";ZZZ" in all path segments on any directory listing or link produced by JSTL (as the problem exists in how we generate the answers on HttpServletRequest .getRequestURI, getPathInfo, and similar methods).   The root cause seemed to point at some odd behavior in UriUtil.

So, you request say `/;ZZZ/deep/path/to/dir/` and the directory listing will have entries like ... `/;ZZZ/deep;ZZZ/path;ZZZ/to;ZZZ/dir;ZZZ/example.css`

I'll see if I can replicate or create a unit test for this.

**Comment by janbartel** [comment]
I made a directory in webapps called ";zzz" like this:   
;zzz/
  a/a.txt
  b/b.txt

If I make a request to localhost:8080/;zzz/  I get 404 Not Found.  If I click on the link in the jetty generated page of known contexts (which is http://localhost:8080/%3Bzzz/), then I get the directory listing which looks fine:

http://localhost:8080/%3Bzzz/a/
http://localhost:8080/%3Bzzz/b/

So I can't reproduce this.

But, I'm more than happy to put in a PR that disallows a contextPath that commences with ; as @gregw  suggested.

**Comment by joakime** [comment]
Closing due to inability to reproduce again.
