### ISSUE TITLE
Update jetty-bom for new infinispan artifacts.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3573]
The new infinispan artifacts are missing from the jetty-bom.
They need to be added to the jetty-bom starting in jetty-9.4.x and newer.

**Comment by janbartel** [comment]
See PR #3574.

@joakime why can't the bom pom reference ${project.version} instead of having to specify it? Also, how do I know if I've got all the necessary artifacts included?

**Comment by olamy** [comment]
@janbartel we already discussed this here https://github.com/eclipse/jetty.project/issues/1527

**Comment by janbartel** [comment]
Merged for 9.4.17 and beyond.
