### ISSUE TITLE
EPL 1.0 or 2.0

### ISSUE THREAD

**Issue by cuixinye** [eclipse/jetty.project#3577]
In the LICENSE file, it shows that
"This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0, or the Apache Software License
2.0 which is available at https://www.apache.org/licenses/LICENSE-2.0."

But the license contents is "Eclipse Public License - v 1.0".
So is it licensed in EPL 1.0 or 2.0?

**Comment by joakime** [comment]
This header text got introduced incorrectly from issue #2923 (PR #2940) .
Introduced in `jetty-9.4.13.v20181111`

Prior to that issue the license text (EPL 1.0) was at ...
https://github.com/eclipse/jetty.project/blob/jetty-9.4.12.v20180830/LICENSE-eplv10-aslv20.html

Also, our source headers are consistently validated against the `header-template-java.txt`, which also says EPL 1.0.
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/header-template-java.txt

We are EPL 1.0 (not EPL 2.0)

**Comment by jmcc0nn3ll** [comment]
I don't think Jetty 9 will ever be EPL 2.0 but it is something we are considering for Jetty 10.
