### ISSUE TITLE
Adopt EPL-2.0 for Jetty-10

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#3578]
EPL 1.0 is deprecated and we should update to 2.0, Jetty-10 seems to appropriate time to make that change.  We can discuss any concerns here.

Information on the differences between the two are [explained here.](https://www.eclipse.org/legal/epl-2.0/faq.php#h.a0eux401qus)  I think this is a pretty simple update for us, we can avoid the whole secondary licenses bits and pieces for the time being and retain our dual licensing.  Source wise I think we should make sure we have appropriate language and this directive as well.

 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0

**Comment by gregw** [comment]
+1

**Comment by joakime** [comment]
I can prepare a PR for this.

**Comment by joakime** [comment]
`jetty-10.0.x` branch is now Eclipse Public License 2.0

We should probably make a blog for that and also a few mailing list announcements
