### ISSUE TITLE
Using WebSocketSession.disconnect() from WebSocket Client causes unresponsive Server v9.4.16

### ISSUE THREAD

**Issue by 2beers** [eclipse/jetty.project#3581]
I'm using Jetty in a websocket server implementation. Sometimes I need to disconnect clients without a warning. The code I used in my program is quite old( 2 years) and worked great with jetty 9.3x and 9.4.x
The last version that I used was ` 9.4.14` and worked great.  

2 days ago I updated to `9.4.16` and after I call `session.disconnect` ( `org.eclipse.jetty.websocket.api.Session.disconnect()` ) , Jetty doesn't accept new connections. The client just waits to connect without any response from jetty. Also the http server is not responding as well. Nothing happens. I had to reboot the app in order for clients to be able to connect again.
This situation happens 80% of the time. Sometimes after I call disconnect() and a client tries to connects immediately, it works. But after the second `disconect()` jetty stops responding. No errors are thrown except` java.io.EOFException: Disconnected` which is expected

If I switch back to 9.4.14 everything works great and I'm not able to replicate this situation.

NOTE: I've skipped v9.4.15 because I got some weird errors on  websocket implementation , errors that I saw are not there on v9.4.16

UPDATE: I forgot to tell  you that I tested with java 11, windows 10

**Comment by 2beers** [comment]
I've checked the disconnect() method from websocket.common.WebSocketSession in 9.4.14 and 9.4.16 
In 9.4.14
    @Override
```
    public void disconnect()
    {
        connection.disconnect();

        // notify of harsh disconnect
        notifyClose(StatusCode.NO_CLOSE,"Harsh disconnect");
    }
```

in 9.4.16
```
    @Override
    public void disconnect()
    {
        connection.disconnect();
   }
```

I see that notifyClose method was removed in 9.4.16. Maybe the problem is coming from there.

**Comment by megglos** [comment]
Same issue here using a Websocket registered as endpoint using JSR 356 annotations and SpringConfigurator.
{{@ServerEndpoint(value = "/ws/status", configurator = SpringConfigurator.class)}}
Still present with latest release 9.4.17, falling back to 9.4.14 for now.

**Comment by joakime** [comment]
@megglos you might be having a different issue.
Can you do the steps outlined at https://github.com/eclipse/jetty.project/issues/3550#issuecomment-485797056 and when your server becomes unresponsive can you run the `Server.dump()`.   We need to see what's going on.  So far, nobody that has reported this issue has given us this dump.
We cannot replicate this report with the many varied server load tests we perform. (both on our own direct server implementation, and via spring-boot, or cometd, or GAE)

**Comment by joakime** [comment]
> UPDATE: I forgot to tell you that I tested with java 11, windows 10

Please be aware of https://webtide.com/openjdk-11-and-tls-1-3-issues/ if using TLS/SSL
