### ISSUE TITLE
Question : Does HTTP/2 jetty client work on HTTPS with proxy ? 

### ISSUE THREAD

**Issue by SonaliDasgupta** [eclipse/jetty.project#3585]
After referring to similar issues , I am still unclear on whether the Jetty HTTP/2 client works for HTTPS servers , with proxy. Also, what is the behavior of the HTTP 2 client with proxy and HTTP server without SSL ? Urgently need this information to decide on a client library for HTTP/2 implementation in a project.

**Comment by sbordet** [comment]
This is currently not implemented, and it's being implemented as part of resolving #250 in Jetty 10.

**Comment by SonaliDasgupta** [comment]
Thank you for the confirmation. Closing this issue.
