### ISSUE TITLE
Jetty Client terminates connections too early with connection=close

### ISSUE THREAD

**Issue by artur-c** [eclipse/jetty.project#359]
Component: Jetty 9.3.7.v20160115.
When sending a GET request with a header connection=close and a target server responds are slow Jetty terminates connection too early and doesn't wait for response to arrive.

I walked through the code and it looks like HeadersCallback receives SHUTDOWN_OUT state from HttpGenerator due to connection=close header. Then it calls shutdownOutput(), which in fact calls Socket.shutdownOutput() -> sends FIN to the server.

I attached a screen from Wireshark that shows it.
![connection_close](https://cloud.githubusercontent.com/assets/17410360/13283371/ce87c66a-daed-11e5-8038-116a1e1bf8de.png)

The scenario works in Jetty 8.1.17.v20150415.

**Comment by sbordet** [comment]
This is exactly what the client should do when a `Connection: close` header is sent.
The connection is not terminated, it's half-closed and the client can still read the response.
Jetty 8 had a bug in that it was not sending the FIN like it should have.

**Comment by artur-c** [comment]
According to my knowledge conenction is terminated on both sides. You can see it clearly that the client sent [FIN, ACK]. If you want to keep the connection half open you need to send only [FIN].

**Comment by sbordet** [comment]
The connection is not terminated on both sides, exactly because we call shutdownOutput, which only shuts down the output. The input side is still readable.

**Comment by artur-c** [comment]
I checked it once again and it turns out that on both Win 7 and Ubuntu 14 a socket.shutdownOutput() sends [FIN, ACK]. Looks like it is not Jetty problem.

**Comment by chuckdumont** [comment]
I think that this issue should be reopened.  I also am seeing problems with connections being closed too early by the server when the client sends FIN/ACK with the request.  In my case, the server responds by sending a FIN/ACK without sending the response.

According to the [HTTP 1.1 spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), "HTTP/1.1 defines the "close" connection option for the sender to signal that the connection will be closed **after completion of the response**." (my emphasis).  It doesn't say anything about the connection being 'half-closed' by the client.  Is this new behavior for HTTP2?

At any rate, there are still lots of older servers in use that won't respond well to this new behavior so it should at least be configurable.

**Comment by sbordet** [comment]
@chuckdumont please open a new issue, since this one was agreed by the OP to not be a Jetty issue.
