### ISSUE TITLE
Support MicroProfile

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/jetty.project#3592]
Is it planned to support Eclipse MicroProfile?

**Comment by joakime** [comment]
Got a link?

**Comment by readonlynetwork** [comment]
Main: https://microprofile.io
Api: https://github.com/eclipse/microprofile
Eclipse: https://projects.eclipse.org/projects/technology.microprofile

**Comment by janbartel** [comment]
@readonlynetwork AFAIK we have no plans in that direction. As it seems to be more of a feature set, as jetty is very embeddable and also very pluggable, its already possible to use most of those technologies with jetty, just not summed up as as "microprofile". What kind of support were you looking for jetty to provide?

**Comment by joakime** [comment]
Been trying to come to terms with what "MicroProfiles" means as far as technology requirements.
Like a list of technologies (or acronyms) that you have to satisfy to become a "MicroProfile".
Can't find a definitive list using the links you provided.

I see CDI and JAX-RS in the list, those are awfully heavyweight components for a "micro" profile.
Is there a "NanoProfile" without CDI and JAX-RS integrated (and no bytecode scanning requirement)? 
If so, then that's what Jetty (and _Tomcat_) would be out of the box.
(I see _TomiTribe_ listed on the vendor support list for MicroProfile, so that would be _TomEE_, not _Tomcat_)

However, that being said, "MicroProfile" might be useful as a Jetty module on `jetty-home` (or the older `jetty-distribution`).

**Comment by readonlynetwork** [comment]
I would like to create some microservice with CDI, JAX-RS, JSON-P/B and JPA. The extra components (openapi, healthcheck and fault tolerance) would make it complete. Other way, I would like to create separated war files and two or more jar for local and secure remote access.

Restful + JPA would be the minimum request. I known, I can use servlet for everything, but I don't want to reinvent the wheel.

I can move to Thorntail, but Jetty is faster at startup and it supports Conscrypt, so I can extend the Java TLS security, finally Jetty can be embedded. Thorntail not support that, TomEE maybe, but not support Conscrypt. Payara and GlassFish create extra features that is unwanted (listening on other port).

**Comment by joakime** [comment]
There's a lot to work out before a `microprofile.mod` can exist.

There's still conflicts between the various specs that need to be resolved, and have not yet been resolved.  (Java EE 8 and Jakarta EE 8 still do not have those conflicts resolved, but we are hoping that Jakarta EE 9 does!)
Example: The annotations that CDI/Weld defines, uses, and scans for ... conflicts with the Servlet and JNDI specs that have the same annotations, but have different meanings. (see problems with `javax.annotation.Resource`)

Restful or JPA isn't something that Jetty will work on or have it's own implementation for, it'll just use one of the various open source providers for those.
Many people have added various Rest libraries and JPA libraries to Jetty already, so which one do we pick?

Something that the MicroProfile websites don't make clear, is the scope of contexts, is a "microprofile" going to ever only be 1 `ServletContext` scope? a single `WebAppContext`?  If so, should we artificially prevent hot deploy, the deployment manager, multiple webapps, etc..?

You mentioned "openapi, healthcheck, and fault tolerance" lets see ...

* Open API (https://github.com/eclipse/microprofile-open-api) would be WebAppContext specific, nothing at the Jetty server level could provide that information.
* HealthCheck (https://github.com/eclipse/microprofile-health) - external checks into Jetty? or Applications making requests to external systems?  if its external checks into Jetty, then this is quite a narrow subset of health checks.  it makes assumptions on how a server behaves that frankly doesn't apply to Jetty. (only UP/DOWN? what about HTTP/2? what about Network state vs Server state vs Application state?).   If its Applications making requests to external systems, then Jetty isn't involved again, this would also be a WebAppContext specific behavior.
* Fault Tolerance (https://github.com/eclipse/microprofile-fault-tolerance) - this seems to be focused on providing fault tolerance to other services outside of Jetty.  this is also WebAppContext specific, there's nothing for Jetty to do here.

I sense a trend here, there's not much that Jetty can do at it's Server level, but the WebAppContext is in control of it all, so at a minimum all Jetty needs to do is provide the necessary implementations of the APIs to the WebAppContext's classloader, there's nothing for Jetty itself to do.
Is that right?   If a MicroProfile service is only 1 deployed WebAppContext, and MicroProfile's various apis are all Application (not server) specific, then there's really 3 layers.

1. Server - with enforced only 1 webapp (on root context) behavior
2. MicroProfile ClassLoader - for MicroProfile libs (apis and impls)
3. WebAppContext

Heck, it might even make sense to just have a `MicroProfileContext extends WebAppContext` that does the classloader behaviors properly.

If CDI is in this picture (and there's only 1 context still) then `MicroProfileContext` could setup the `WebAppContext` specific CDI layer too.

**Comment by joakime** [comment]
Out of curiosity, are there any "Pet Store" like applications that use the full gamut of MicroProfile features?  A war that can be deployed on a MicroProfile compliant server that uses all of the various features of MicroProfile?

**Comment by joakime** [comment]
I found https://github.com/eclipse/microprofile-samples
But that seems to uber-jar builds for wildfly and tomee.
No `jetty-home` (or `jetty-distribution`) based deployment scenario needed, it's all `embedded-jetty` from here?

**Comment by readonlynetwork** [comment]
Weld imp. maybe, but in CDI spec. https://javaee.github.io/tutorial/cdi-adv004.html it looks like separated.

I imagine about create WebAppContext and set features: restful, jpa, or other and run.

**Comment by olamy** [comment]
give this feature more time
