### ISSUE TITLE
Make a distribution test for jsp.mod

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3593]
Add a test for enabling the jsp jetty module and verify jsp is working as correctly.

**Comment by olamy** [comment]
well finally DistributionTests already have jsp mod tests https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java#L89
it is very basic do we need something more elaborate?

**Comment by janbartel** [comment]
@olamy I think the existing tests cover it pretty well, I'm closing this issue.
