### ISSUE TITLE
Multipart content not working after release 9.3.11

### ISSUE THREAD

**Issue by exdirectory** [eclipse/jetty.project#3596]
I have tried a few times to use later versions but find our file upload code fails each time, this is what we are doing...

      request.setAttribute(Request.__MULTIPART_CONFIG_ELEMENT, new MultipartConfigElement(System.getProperty("java.io.tmpdir")));
      String contentType = request.getContentType();
      if (contentType != null && contentType.startsWith("multipart/form-data")) {
         for (Entry<String, String[]> entry : request.getParameterMap().entrySet()) {
		    ...

On 3.11 this works fine, on anything later it crashes out on the request.getParameterMap(). Did a new library get added that we might be missing or a change in spec?

**Comment by sbordet** [comment]
Multipart must be handled with https://docs.oracle.com/javaee/6/tutorial/doc/gmhba.html.

I'm surprised `getParameterMap()` ever worked with multipart.

Please update your code to use the correct API and report back if it works for you.
Also update to 9.4.x is recommended (wait for 9.4.18).

**Comment by exdirectory** [comment]
Hi, yes, i am using already getParts after getParameterMap(). So if i lose getParameterMap() and then call 
`               for (Part part : request.getParts()) {`

I get the same, crashes out. I am now thinking maybe i am missing a library, we use ant builds so not automatically pulling in all jetty and javax libs maybe. Would you happen to know which one this would be looking for and I can check that?

**Comment by joakime** [comment]
Do you get a stacktrace?
If so, can you copy/paste it here?

Joakim Erdfelt / joakim@webtide.com

**Comment by exdirectory** [comment]
No , unusually not, which is why it makes me think it could be missing library. Using Eclipse in debug, just literally bombs out. Like the web servlet call terminates and nothing more happens.

**Comment by joakime** [comment]
Regarding the debugging in Eclipse ...

The Jetty threads are likely timing out and being terminated.
So make sure you set your ServerConnector and HttpConfiguration idle timeouts to something huge when you are debugging.

**Comment by exdirectory** [comment]
Solved, was bringing in wrong servlet-api jar version.

Thanks for your help.
