### ISSUE TITLE
When using `--add-to-start=https` is there a way to listen on multiple addresses?

### ISSUE THREAD

**Issue by nddipiazza** [eclipse/jetty.project#3599]
Let's say i want to add https using the `java -jar start.jar --add-to-start=https`

Is there a way to create the TLS/https connector such that it listens on both 8443 *and* 443?

**Comment by sbordet** [comment]
Enabling the `https` module means you are referencing an XML file that configures the `https` support.
From the `https.mod` file: https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/config/modules/https.mod
The correspondent XML file: https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/config/etc/jetty-https.xml
Note that the actual `ServerConnector` is defined in this XML file: https://github.com/eclipse/jetty.project/blob/jetty-9.4.15.v20190215/jetty-server/src/main/config/etc/jetty-ssl.xml, which is a transitive dependency.

You have 2 choices:

1. Make your own custom module in `$JETTY_BASE/modules/my_https.mod` and reference a custom XML in `$JETTY_BASE/etc/my_https.xml`
See this section of the documentation: https://www.eclipse.org/jetty/documentation/9.4.x/custom-modules.html
This is the recommended way.

1. Copy `$JETTY_HOME/etc/jetty-https.xml` into `$JETTY_BASE/etc/my_https.xml` and modify it to start 2 `ServerConnectors`: leave the section that starts the existing connector unchanged, and add a section that starts a second `ServerConnector`.

**Comment by shubhashreeR** [comment]
Thanks for the detailed info.
There are many files like https.mod, jetty-https.xml, ssl.mod, jetty-ssl.xml, jetty-ssl-context.xml, jetty.xml.
I see port 8443 configured in these. should I add 443 as well. can you please elaborate the changes with example.

Thanks

**Comment by joakime** [comment]
@shubhashreeR the goal you have is a new `ServerConnector`, defined via XML.
The existing `https.mod` is a fantastic way to start, copy it to your `${jetty.base}/etc/` directory and change the details you want. (don't worry about any other xml file yet!)
Next, add a reference to your new xml file in your `${jetty.base}/start.ini` or in a new `${jetty.base}/start.d/*.ini` file.
That reference should be a new line that says `etc/<mynewname>.xml` (whatever that new name is).
Now start Jetty.

> Note: do not edit / change / modify / add / delete any content in your `${jetty.home}` directory (what your unpacked `jetty-home-*.tar.gz` or `jetty-distribution-*.tar.gz` unpacked into).  That directory should be treated as read-only.

**Comment by sbordet** [comment]
I believe this issue has been addressed, closing. Please reopen/comment if you think something is missing.
