### ISSUE TITLE
IdleTimeout with Jetty HTTP/2 and InputStreamResponseListener

### ISSUE THREAD

**Issue by CaoManhDat** [eclipse/jetty.project#3605]
Here is the exception
```
   [junit4]   2> Caused by: java.util.concurrent.TimeoutException: idle_timeout
   [junit4]   2> 	at org.eclipse.jetty.http2.client.http.SolrConnection.onIdleTimeout(SolrConnection.java:143) ~[java/:?]
   [junit4]   2> 	at org.eclipse.jetty.http2.client.http.SolrTransportHttp2$SessionListenerPromise.onIdleTimeout(SolrTransportHttp2.java:260) ~[java/:?]
   [junit4]   2> 	at org.eclipse.jetty.http2.HTTP2Session.notifyIdleTimeout(HTTP2Session.java:1166) ~[http2-common-9.4.14.v20181114.jar:9.4.14.v20181114]
   [junit4]   2> 	at org.eclipse.jetty.http2.HTTP2Session.onIdleTimeout(HTTP2Session.java:1004) ~[http2-common-9.4.14.v20181114.jar:9.4.14.v20181114]
   [junit4]   2> 	at org.eclipse.jetty.http2.HTTP2Connection.onIdleExpired(HTTP2Connection.java:151) ~[http2-common-9.4.14.v20181114.jar:9.4.14.v20181114]
   [junit4]   2> 	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:401) ~[jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
   [junit4]   2> 	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166) ~[jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
   [junit4]   2> 	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50) ~[jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
   [junit4]   2> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
   [junit4]   2> 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
   [junit4]   2> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
```

After digging into the Jetty code, here is what I found
* The sever did successfully write the response to the client.
* The client did receive the data but the listener is not called with new data.
* At first I thought that `HeadersFrame.endStream=true`  -> subsequent data does not trigger the listener. But it is not true `HeadersFrame.endStream=false`
* The reason here is `HttpReceiverOverHTTP2` is reused between multiple req-resp calls. For some reason the `Receiver` does not reset and stuck at SUCCEEDED state. 

So here is the flow that leads to the problem

1. `HttpReceiverOverHTTP2.ContentNotifier.process()` is called, `prevDataInfo.frame` have `endStream=true` therefore the method return `Action.SUCCEEDED`.  `IteratingCallback` then get changed to `SUCCEEDED` and the `HttpExchange.response` state is changed to `TERMINATED`. This whole process is called in a thread that is reading data from `InputStreamResponseListener`. In this case `HttpReceiverOverHTTP2.reset()` is called, note that the `HttpExchange.Response` state before this reset call is PENDING and after the response state is TERMINATED.
2. In another thread of `HttpClient` executor. The same `HttpReceiverOverHTTP2.ContentNotifier.process()` is called with same `prevDataInfo.frame` (same frame with same hashCode()). But since the exchange response state is TERMINATED. `HttpReceiverOverHTTP2.reset()` is not called.
3. For the next request response that use same `HttpReceiverOverHTTP2`, even data is offered to the queue, the Receiver do nothing since `ContentNotifier` state now is `SUCCEEDED`

**Comment by CaoManhDat** [comment]
This problem can be reproduced quite reliably (sometimes it does not happen), by doing this. On lucene-solr project, run this command
`ant test  -Dtestcase=TestDistributedStatsComponentCardinality -Dtests.method=test -Dtests.seed=423C6CB5EC79E8B7 -Dtests.multiplier=2 -Dtests.nightly=true -Dtests.slow=true -Dtests.badapples=true -Dtests.locale=zh-Hans -Dtests.timezone=Africa/Abidjan -Dtests.asserts=true -Dtests.file.encoding=UTF-8`

**Comment by sbordet** [comment]
@CaoManhDat if you disable `HttpChannelOverHTTP2` by commenting out, in `HttpConnectionOverHTTP2.release(HttpChannelOverHTTP2)`, the call to `offer()`, do you see the issue?

In your analysis above, in point 2 the same `HttpReceiverOverHTTP2` is used for another response?

**Comment by CaoManhDat** [comment]
Here is my modified version for logging
```
if (prevDataInfo != null && prevDataInfo.frame.isEndStream()) {
          LOG.info("Notifier callback: process() endStream with frame:{} this:{} notifier:{}", prevDataInfo.frame, this, contentNotifier);
          return Action.SUCCEEDED;
        }
```
The hashcode of `Notifier` and `Frame` is the same in both point1 and point 2, so I think they are handling for the same response.

In point 3, the same `Receiver` (hence `Notifier`) is used for another response.

Does this commenting out correct?
```
    protected void release(SolrChannel channel)
    {
        if (LOG.isDebugEnabled())
            LOG.debug("Released {}", channel);
        if (activeChannels.remove(channel))
        {
            // Recycle only non-failed channels.
            if (channel.isFailed())
                channel.destroy();
//            else
//                idleChannels.offer(channel);
        }
        else
        {
            channel.destroy();
        }
    }
```

**Comment by CaoManhDat** [comment]
It seems problem goes away with the comment.

**Comment by CaoManhDat** [comment]
The #3632 did fix the problem.

**Comment by sbordet** [comment]
Thanks for the feedback!
