### ISSUE TITLE
Fix Infinispan start module dependencies

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3609]
When we updated to infinispan 9.4.8, we used the wrong infinispan jars.

**Comment by janbartel** [comment]
Fix applied for jetty-9.4.18. However, the module still needs cleaning up, so I'll leave this issue open for now.

**Comment by janbartel** [comment]
Refactor of modules into better structure done for 9.4.19 and beyond.

**Comment by WalkerWatch** [comment]
@janbartel Does the associated documentation for Infinispan need to be updated to reflect any of this? I feel like it doesn't, as most of this is background implementation, but I wanted to be sure.
