### ISSUE TITLE
Javadoc for deprecated GZipHandler methods is incorrect

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#361]
In trying to upgrade Spring Boot to Jetty 9.2.15, I've just stumbled across the changes made in 5e3fbbcc. The javadoc for a number of the deprecated methods is incorrect. For example, `setMimeTypes` says to use `setIncludedMimeTypes()` or `setExcludedMimeTypes()` but neither method exists. It should be `add…` rather than `set…`.

As a secondary point, I was rather surprised to see a method being deprecated and its implementation changed to throw an `UnsupportedOperationException` in the same release.

**Comment by gregw** [comment]
Yeah... the history of GzipHandler has not exactly been the best.     In releases <= 9.2 it was not really a well supported class and GzipFilter was the main focus.    However , with the introduction of aync IO the filter wrapping approach of GzipFilter is no longer workable, so in 9.3.x the GzipHandler was reworked to an entirely new class that would work for async.     

However, some changes have been backported to 9.2.x, attempting to provide an easier upgrade path for some users that are planing 9.3.x upgrades, but this was obviously not-optimal for existing users of GzipHandler in 9.2.x 

The javadoc does appear to be correct in 9.3 and beyond.  We'll have look at 9.2.x to make sure the doc is up to date and better explains the state of that class.
