### ISSUE TITLE
CWE-384: Session Fixation on ConfigurableSpnegoLoginService

### ISSUE THREAD

**Issue by mikexliu** [eclipse/jetty.project#3627]
My company uses veracode and as part of the scan, it found that ConfigurableSpnegoLoginService.java:181 may suffer from http://cwe.mitre.org/data/definitions/384.html. Just wanted to check if this may be a concern or if it's a false positive scan.

**Comment by joakime** [comment]
Link to line 181 in section of code referenced by OP ...

https://github.com/eclipse/jetty.project/blob/6c6646286d4b8a239e5b6e57881b33391e0b2735/jetty-security/src/main/java/org/eclipse/jetty/security/ConfigurableSpnegoLoginService.java#L177-L186

**Comment by janbartel** [comment]
All types of LoginAuthenticator in Jettyby default will automatically change the id of a session that already existed prior to authentication succeeding. Does that address your area of concern?

**Comment by mikexliu** [comment]
@janbartel 
Can you show me where in the code that's done? I did not find it for the class `ConfigurableSpnegoLoginService.java`.

I'm just looking at the code through github (I haven't loaded the code in an IDE to look at it yet) and I'm very unfamiliar with the code base. Please excuse any obvious mistakes and misunderstandings in my comments.

Other `LoginServices`:
- https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-security/src/main/java/org/eclipse/jetty/security/SpnegoLoginService.java#L131
Does not return the existing session.
- https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-security/src/main/java/org/eclipse/jetty/security/AbstractLoginService.java#L170
Does not return the existing session.
- https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-jaas/src/main/java/org/eclipse/jetty/jaas/JAASLoginService.java#L271
Does not return the existing session.
- https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-security/src/main/java/org/eclipse/jetty/security/ConfigurableSpnegoLoginService.java#L181
Tries to retrieve any existing session.

The relationship between `LoginService` and `LoginAuthenticator` seem to be almost `1:1`.

**Comment by joakime** [comment]
@mikexliu the piece of logic that @janbartel is referring to is in the `LoginAuthenticator.login`.

https://github.com/eclipse/jetty.project/blob/6c6646286d4b8a239e5b6e57881b33391e0b2735/jetty-security/src/main/java/org/eclipse/jetty/security/authentication/LoginAuthenticator.java#L56-L66

See the implementation of `renewSession` ...

https://github.com/eclipse/jetty.project/blob/6c6646286d4b8a239e5b6e57881b33391e0b2735/jetty-security/src/main/java/org/eclipse/jetty/security/authentication/LoginAuthenticator.java#L98-L143

The `javax.servlet.http.HttpSession` is cast down to a `org.eclipse.jetty.server.session.Session` and the ID's are renewed and the cookies replaced with the new ID.

**Comment by mikexliu** [comment]
Thanks @joakime.

I think the issue is that https://github.com/eclipse/jetty.project/blob/9b7afd8a0341f4712031abd322ab8669f07f5c5b/jetty-security/src/main/java/org/eclipse/jetty/security/ConfigurableSpnegoLoginService.java#L181 is called before the renew. That seems to be what CWE-384 is referring to.

**Comment by janbartel** [comment]
@mikexliu  I think there is potentially a problem, but not exactly for the reason you think.  

Every time the LoginService.login method is called and returns a non-null UserIdentity we assume it signifies a fully authenticated user and forcibly change the session id. This prevents session fixation attacks.

For spnego, it is possible that the LoginService.login method returns a non-null UserIdentity, but the authenticity of the user has not been fully established (needs more round-trips to the user).

If your particular spnego authentication exchanges only ever take 2 steps (the first being a request that triggers the need for authentication and the 2nd being a request that contains a token that satisfies spnego/kerberos etc), then we will change the session id correctly on the 2nd response and all is good.

If, however, your spnego exchanges require _more_ intermediate round trips, jetty will have changed the session id after the 2nd exchange, _before_ the user authenticity is fully established. Thus a session id is returned to the client that will _not_ be changed after the final authentication step happens.

PR #3629 ensures that the session id is only changed *after* the user identity is fully authenticated.

**Comment by janbartel** [comment]
Fix for multi-step session fixation with spengo checked in for 9.4.18 and beyond.

**Comment by joakime** [comment]
Uhm, 9.4.18 was released last month.
I think you meant these changes will be available for 9.4.19 and beyond?

**Comment by janbartel** [comment]
Updated my comment - I was looking at an old pom in a different branch.

**Comment by mikexliu** [comment]
Thank you @janbartel @joakime 

You're right there's a problem, but probably not exactly what was reported. I think the veracode scan may have been confused about some ordering of the code too. I'll look into that myself.
