### ISSUE TITLE
endpointIdentificationAlgorithm enabled by default jetty-ssl-context.xml

### ISSUE THREAD

**Issue by naddame** [eclipse/jetty.project#3633]
Hi,
In relation to issues : https://github.com/eclipse/jetty.project/issues/3454
When i downloaded jetty 9.4.18, I don't understand why in jetty-ssl-context.xml we have:
`
<Set name="EndpointIdentificationAlgorithm"><Property name="jetty.sslContext.endpointIdentificationAlgorithm" default="HTTPS"/></Set>
`

Why the param "EndpointIdentificationAlgorithm" is specified and why default value is HTTPS even if SslContextFactory.Server force it to be null?

Thanks

**Comment by sbordet** [comment]
@naddame it's a bug.

**Comment by joakime** [comment]
Opened PR #3634
