### ISSUE TITLE
When adding a JsonLayout to log4j2.xml jetty is using org.eclipse.jetty.util.log.StdErrLog for logging log4j2

### ISSUE THREAD

**Issue by kajh** [eclipse/jetty.project#3675]
When adding a JsonLayout to log4j2.xml jetty is using org.eclipse.jetty.util.log.StdErrLog for  logging log4j2.

See the https://stackoverflow.com/questions/55002855/getting-log4j2-to-use-json-as-logformat for a description of how to reproduce this. I have reproduced this with jetty-distribution-9.4.18.v20190429.

_Copied Stackoverflow Question:_

I'm trying to get jetty 9.4.14 to log as json to stdout istead of the default org.eclipse.jetty.util.log.StdErrLog. To debug this I run jetty from the demo-base directory with ```java -jar ../start.jar```.

I have 

 - ran ```java -jar ../start.jar --add-to-start=logging-log4j2```
 - ran ```java -jar ../start.jar --add-to-start=ext```
 - added jackson-databind-2.9.8.jar and jackson-core-2.9.8.jar to ./lib/ext

If just change loglevel in ./resources/log4j2.xml from "info" to "warning" I see that I only get warning logging to stdout, so the log4j2.xml is read. 

When I try to add a new appender with JsonLayout to this file, I see that the org.eclipse.jetty.util.log.StdErrLog logging is used insted of log4j2.

I see this when I add the appender "console2" bellow:

``` xml
      <Appenders>
        <Console name="console" target="SYSTEM_ERR">
          <PatternLayout>
            <Pattern>xxx %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n</Pattern>
          </PatternLayout>
        </Console>
    
        <Console name="console2" target="SYSTEM_ERR">
              <JsonLayout></JsonLayout>
        </Console>
      </Appenders>
```

Any ideas? Thanks! :)

**Comment by joakime** [comment]
@kajh this seems more like a log4j2 specific question.

What do your startup logs say?  Either it worked, or there was a startup error.
Why those 2 specific jackson dependencies? What about the dependencies that jackson itself has on other jars?
How do you know it's StdErrLog being used?
Have you disabled the console-capture module?

**Comment by kajh** [comment]
Hi, thanks for looking into this issue! 

The two jackson dependencies are required for using JsonLayout with log4j2.xml.

When I start the demo-base app with JsonLayout defined in log4j2.xml, the logging shows that org.eclipse.jetty.util.log.StdErrLog is used, see bellow:
```
demo-base$ java -jar ../start.jar 
2019-05-20 13:50:14.426:INFO::main: Logging initialized @1009ms to org.eclipse.jetty.util.log.StdErrLog
```
If I remove the JsonLayout from log4j2.xml I get the following showing that Slf4jLog aka log4j2 is used:
```
demo-base java -jar ../start.jar   
2019-05-20 13:53:16 INFO  log:193 - Logging initialized @803ms to org.eclipse.jetty.util.log.Slf4jLog
```
I have not done anything releated to the console-capture module. Thanks in advance for any ideas to how to debug this or to what info I can provide that can be usefull to you!

**Comment by joakime** [comment]
What 2 Jackson Dependencies?
Be specific.

**Comment by kajh** [comment]
Thanks for answering and sorry for not beeing specific! 

I added jackson-databind-2.9.8.jar and jackson-core-2.9.8.jar to ./lib/ext. I got these from maven central.

I have not added any transitive/downstream dependencies. I don't get any ClassNotFoundException. Jetty just silently ignore my log4j2.xml config and use the default logging (org.eclipse.jetty.util.log.StdErrLog) instead.

**Comment by joakime** [comment]
> Jetty just silently ignore my log4j2.xml config and use the default logging (org.eclipse.jetty.util.log.StdErrLog) instead.

Jetty has very little to do with this, the process is ...

1. Load `org.eclipse.jetty.util.log.Slf4jLog`
2. It calls `org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger("org.eclipse.jetty.util.log");`
3. If that fails, then slf4j and/or the slf4j implementation outputs a message.
4. Jetty falls back to `org.eclipse.jetty.util.log.StdErrLog` if the slf4j logger fails.

What's missing here is step 3, that always happens with slf4j, and is the key piece of output that is missing to troubleshoot this properly.

> I added jackson-databind-2.9.8.jar and jackson-core-2.9.8.jar to ./lib/ext. I got these from maven central.

Why did you choose those 2 versions?
Even the latest release of Log4j2 doesn't use those versions.
Make sure you use the versions of jackson that the version of log4j2 you are using references. (see [log4j-core pom for your version of log4j](https://search.maven.org/search?q=g:org.apache.logging.log4j%20AND%20a:log4j-core&core=gav) and follow the parent dependencies to learn what version of jackson it wants)

You need the downstream dependencies. [jackson-databind](https://search.maven.org/artifact/com.fasterxml.jackson.core/jackson-databind/2.9.9/bundle), for example, has dependencies.
Make sure you use the appropriate version of the dependencies for your version of jackson (which is dependent on your version of log4j).
Advice: don't expect/assume that the jackson uses the same version for all of its dependencies (jackson's dependencies do not have that behavior, it is quite common for downstream dependencies to be different versions from the upstream ones).

**Comment by kajh** [comment]
Thanks for the description! You can close this issue.

**Comment by joakime** [comment]
@kajh if you have a solution you might want to post it here or on stackoverflow, so that others in your same situation can benefit from it.
