### ISSUE TITLE
rename javax websocket in jetty-10 now?

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3678]
Jetty-10 is not yet released and it contains a rename of the standard websocket implementation from `JsrWebsocket` to `JavaxWebsocket`.   The name `JSR` is already deprecated and now we know that `javax` is going to have to be renamed to `jakarta`, so maybe we should avoid changing to `javax`?

Arguing against myself here.... the name is only really user visible in the module name, so I can see a future where we have both javax-websocket and jakarta-websocket and we can enable either (or maybe both) to get whichever API we want.      So unless anybody disagrees, I will close this issue almost immediately after we have considered it.

**Comment by sbordet** [comment]
@gregw I agree that we should keep `javax` for now. JPMS modules can be deprecated and we can create the new one with `jakarta` when needed.

**Comment by joakime** [comment]
Strictly speaking, we are not allowed to use "Javax" in our classname.
That's a name trademarked and copyrighted by Sun/Oracle.

**Comment by gregw** [comment]
@joakime DOH!   So we should rename the classes and modules to...... ??????

**Comment by sbordet** [comment]
I don't think "javax" in a classname is trademarked.
@joakime you have an authoritative source?

**Comment by joakime** [comment]
Just read all of the discussions about the `javax.*` to `jakarta.*` transition.
The reason isn't just the package name, its fundamentally the name "java" and "javax", and the fact that those words are owned by Sun/Oracle.
Example: https://twitter.com/mmilinkov/status/1124377130438135809

**Comment by sbordet** [comment]
> Any instance of the word “Java” will need replacing.

It obviously does not make sense at the package level, otherwise we would need to replace `**java**.lang.Object`.
It also does not make sense when using `javax.naming` and other `javax` classes.

I want to see an authoritative source for this specific case, not a tweet that is possibly out of context.

If we need to contact Eclipse legals, let's do it. We need to know if "javax" is usable within package names (e.g. `org.eclipse.jetty.websocket.javax`) class names, method names, JPMS module names, etc. with the goal to differentiate implementations (e.g. a "javax" implementation of WebSocket versus a "jetty" implementation of WebSocket).

**Comment by joakime** [comment]
You are not making the distinction of correct use.

* Using "java" is fine. (that's specifically called out in the GPL2 with classpath exception that OpenJDK has)
* Documenting the use of java is fine. (also specifically allowed in the licensing of Java)
* Using other artifacts outside of our project with java in their name is fine (for us the only requirement is that their license is compatible with us).
* Calling anything we create with the word "java" is NOT ok. (this is a license violation of OpenJDK and Sun/Oracle trademark)

**Comment by sbordet** [comment]
@joakime find me the authoritative source, otherwise we're just guessing.

**Comment by sbordet** [comment]
Meh, after more thinking and reading around I changed my mind and I think it's best if we don't use neither "javax" nor (in the future) "jakarta" in class names or JPMS module names.

I propose to use `stdws` instead of `javax`.

In the future, if "jakarta" comes into play, we can use `stdws2`.

We have the same problem in CometD, BTW. If we agree on the name to use, I will do the same changes in CometD 5.0.x.

**Comment by gregw** [comment]
Yeah I kind of agree it is best to proactively avoid the trademarks rather than be forced to change at some later date.
But `stdws` means nothing to me.

I note that currently we just have a module called  `websocket` that appears to enable both APIs.  I'm not sure we can continue doing that as there will soon be 3 APIs at least.  So perhaps let's work back from module names.   We should be able to start with `websocket-jetty`, so what about `websocket-ee8` an `websocket-ee9`?    Let me ask eclipse if that is allowed and other advice about naming implementations?

**Comment by sbordet** [comment]
Please do ask.

**Comment by gregw** [comment]
I have asked: 
```
The jetty project is  looking at the naming consequences of the transition with regards to implementation names (eg module names and classnames).   Let's consider the websocket API.  It will soon be the case that a container may wish to offer it's webapps the choice of using the javax.* version of the API or the jakarta.* version.

Would be be allowable (with regards to trademarks) to have the various modules, classes and options for those to use javax and jakarta in their names.    For example the user could choose between enabling modules websocket-javax and websocket-jakarta, which internally might enable classes like org.eclipse.jetty.websocket.javax.* and org.eclipse.jetty.websocket.jakarta.*, which are configured with parameters etc. that also might include javax and jakarta?    

Or is that going to run foul of one or more trademarks?  Are there fair use provisions that allows us the use these trademarks in the names of things that work with the APIs of those trademarks?

If so,  are there similar issues with the use of ee ?   Ie could the modules be called websocket-ee8 and websocket-ee9, which internally refer to classes like org.eclipse.jetty.websocket.ee8.* and org.eclipse.jetty.websocket.ee9.*  etc.  ?    Is this usage still OK if it is within an non certified container that does not implement the full ee stack?  Is ee subject to trademarks?

Is this something the Eclipse Foundation can get legal advice on?  Or is the answer known already?
```

Will edit with a link to the thread when the [archiver updates](https://www.eclipse.org/lists/jakartaee-platform-dev/).

**Comment by gregw** [comment]
Also I think we have a reasonable fair use case:
http://www.patenttrademarkblog.com/trademark-fair-use/
https://en.wikipedia.org/wiki/Fair_use_(U.S._trademark_law)

**Comment by joakime** [comment]
The umbrella term "Fair Use" doesn't apply for our software product very well (too vague).
The subset known as "Nominative Fair Use" does, however. (just as I mentioned above)
https://en.wikipedia.org/wiki/Nominative_use

But even that has limits to how far we can go.
Documenting our use of the term, describing our relationship to the term, referencing the term. all ok (as long as we satisfy the trademark notice requirements of the owner)
Using the term in the name of something we create, is generally not ok. (the notice requirements make statements on this)

* https://openjdk.java.net/legal/openjdk-trademark-notice.html
* https://www.oracle.com/legal/trademarks.html

So a description like "Jetty implementation of javax.websocket" is described in the trademark notices above as ok.
But using "javax.websocket on Jetty" would not be ok. (also pointed out in the trademark links above).

Naming our classes would need to be something awkward like WebSocketClientForJavax and WebSocketClientForJakarta
The modules would be websocket-for-javax and websocket-for-jakarta
The key being the "XYZ for <term>" style of syntax that the trademark links point out.

We could even bite the bullet and just use `LegacyWebSocketClient` and `JakartaWebSocketClient` (as i'm comfortable with the understanding that Jakarta EE would allow us to use that form)

**Comment by gregw** [comment]
"Legacy" is no good, as what happens when jetty or EE9 APIs becomes legacy.  Too generic.

"For" is not really right either,  "With" is perhaps a little better.

So I think we can avoid some verbosity by just not using any prefix in the class name and whatever name resolution we come up with we put in the package name.  So maybe one of:
 - `org.eclipse.jetty.websocket.for.javax.Client`
 - `org.eclipse.jetty.websocket.with.javax.Client`
 - `org.eclipse.jetty.websocket.javax_api.Client`
 - `org.eclipse.jetty.websocket.with.javax_api.Client`
 - `org.eclipse.jetty.websocket.with_javax_api.Client`
 - `org.eclipse.jetty.websocket.with_javax.Client`

**Comment by sbordet** [comment]
Please no.

If we are allowed to use "javax" in a package name, just use that and drop "with", "for" and underscores.

**Comment by joakime** [comment]
@waynebeaton are we allowed to use "javax" within an Eclipse project for its java package and/or artifact name?

Examples: 

Java Package: `org.eclipse.jetty.websocket.javax.client`
Artifact Coordinates: 
```
<dependency>
  <groupId>org.eclipse.jetty.websocket</groupId>
  <artifactId>javax-websocket-client</artifactId>
  <version>10.0.0.alpha1</version>
</dependency>
```

**Comment by joakime** [comment]
Until we get feedback from Wayne, here's some examples of other Eclipse projects doing the same thing we are worried about.

* https://search.maven.org/artifact/org.eclipse.birt.runtime.3_7_1/javax.wsdl/1.5.1/jar
* https://search.maven.org/artifact/org.eclipse.persistence/javax.persistence/2.2.1/jar
* https://search.maven.org/artifact/org.eclipse.ecf/javax.servlet/3.1.0.v201410161800/jar
* https://search.maven.org/artifact/org.eclipse.birt.runtime/javax.xml.stream/1.0.1.v201004272200/jar

**Comment by waynebeaton** [comment]
Oracle claims "javax" as it's trademark. The general rule is that you must avoid adding confusion regarding ownership. Calling something "javax something" is offside, but "something for javax" is generally okay (yes, I know that that particular example is silly). 

I assume that you're implementing javax.websocket.... why not just call it "websocket-client"?

FWIW, the second example that you're citing is likely the actual javax.persistence (the API JAR was at one point developed by the EclipseLink project). I'm not sure about the others, so I'll have a quick look at follow up with them.

**Comment by joakime** [comment]
> Oracle claims "javax" as it's trademark. The general rule is that you must avoid adding confusion regarding ownership. Calling something "javax something" is offside, but "something for javax" is generally okay (yes, I know that that particular example is silly).

The "Something for javax" is easy for Descriptions and whatnot.

A bit hard to use that "for" syntax for namespaces and artifact names. :-/

> I assume that you're implementing javax.websocket.... why not just call it "websocket-client"?

We already have ...

* websocket-client.jar (the Jetty native websocket client, predates javax.websocket - being renamed to jetty-websocket-client for Jetty 10.0.x)
* websocket-core.jar (the Jetty core websocket lib)
* javax-websocket-client.jar (the Jetty implementation for javax.websocket)

**Comment by gregw** [comment]
I think we need to look at this the other way around... ie let's worry about correct usage of `jakarta` name and then do the same for `javax`.   I hope we can get a very definitive answer that we are using `jakarta` correctly and then the pattern should give us clarity that we are using `javax` in the for usage style.

Note we have two naming issues: the module  `jakarta-websocket-client` and the package `org.eclipse.jetty.websocket.jakarta.client`.    To me the package name is clearly scoped by eclipse and jetty, so I really hope that it is not a problem.   The module name could be more of a problem as it falls foul of the "it's a websocket client for jakarta' vs 'it is the jakarta websocket client' confusion (Why do I feel like I'm in the four candles vs handles for forks sketch :)

I think leading with `jakarta` or `javax` is going to be problematic - confusing at best, illegal at worst.   Remember that we had to rename `maven-jetty-plugin` to the `jetty-maven-plugin`, so perhaps we should not lead with `jakarta`.

So I'd like to propose that the module name follow the word order of the package name, so for package `org.eclipse.jetty.websocket.jakarta.client`, the module name should be  'websocket-jakarta-client`.  

@waynebeaton can you confirm that is an acceptable usage of `jakarta`?

If so, that would then give us:

+ `websocket-javax-client` / `org.eclipse.jetty.websocket.javax.client`
+ `websocket-jakarta-client` / `org.eclipse.jetty.websocket.jakarta.client`
+ `websocket-jetty-client` / `org.eclipse.jetty.websocket.jetty.client`
+ `websocket-reactive-client` / `org.eclipse.jetty.websocket.reactive.client`

A good side effect is that all the websocket modules will then sort together!

**Comment by waynebeaton** [comment]
> I think we need to look at this the other way around... ie let's worry about correct usage of `jakarta` name and then do the same for `javax`. I hope we can get a very definitive answer that we are using `jakarta` correctly and then the pattern should give us clarity that we are using `javax` in the for usage style.

I wish that it was this simple. We actually have considerably more leeway with how we use names trademarked by the Eclipse Foundation than we do with those of others.  I'm confident that websocket-jakarta-client and websocket-jetty-client are both fine, but I'm not sure about websocket-javax-client. I'll investigate.

**Comment by joakime** [comment]
> If so, that would then give us:
> 
> * `websocket-javax-client` / `org.eclipse.jetty.websocket.javax.client`
> * `websocket-jakarta-client` / `org.eclipse.jetty.websocket.jakarta.client`
> * `websocket-jetty-client` / `org.eclipse.jetty.websocket.jetty.client`
> * `websocket-reactive-client` / `org.eclipse.jetty.websocket.reactive.client`
> 
> A good side effect is that all the websocket modules will then sort together!

I'm +1 for this approach, and the proposed example names.  (I take it this would also apply to the server/servlet versions too?)
Just need to resolve the `javax` specific case (legally speaking).

**Comment by gregw** [comment]
So I think we should do the work now to reorder the names, so that jakarta will be good and if anybody who does care about javax looks at it, it will be the best we can do simple.  If they really don't like it, then we can always `s/javax/legacy/`

**Comment by waynebeaton** [comment]
Using "websocket-javax-client" as a JAR file name and/or Maven artifactid is fine. Thanks for checking.

**Comment by gregw** [comment]
Thanks
@lachlan-roberts  can you action this!

**Comment by lachlan-roberts** [comment]
@gregw the following name change has been made for the websocket modules in jetty-10 (#4441) 

`javax-websocket-client` -> `websocket-javax-client`
`javax-websocket-server` -> `websocket-javax-server`
`javax-websocket-common` -> `websocket-javax-common`
`javax-websocket-tests` -> `websocket-javax-tests`

`jetty-websocket-api` -> `websocket-jetty-api`
`jetty-websocket-client` -> `websocket-jetty-client`
`jetty-websocket-server` -> `websocket-jetty-server`
`jetty-websocket-common` -> `websocket-jetty-common`
`jetty-websocket-tests` -> `websocket-jetty-tests`

**Comment by gregw** [comment]
awesome
