### ISSUE TITLE
Bom manages non-existent infinispan-remote and infinispan-embedded dependencies due to config classifier

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#3680]
The 9.4.18.v20190429 bom manages `infinispan-embedded` and `infinispan-remote` dependencies:

https://github.com/eclipse/jetty.project/blob/e1bc35120a6617ee3df052294e433f3a25ce7097/jetty-bom/pom.xml#L222-L226

https://github.com/eclipse/jetty.project/blob/e1bc35120a6617ee3df052294e433f3a25ce7097/jetty-bom/pom.xml#L212-L216

Looking at [Maven Central](https://repo1.maven.org/maven2/org/eclipse/jetty/infinispan-remote/9.4.18.v20190429/), these dependencies are only published with a `config` classifier:

```
../
infinispan-remote-9.4.18.v20190429-config.jar     2019-04-29 21:10      2972      
infinispan-remote-9.4.18.v20190429-config.jar...  2019-04-29 21:10       801      
infinispan-remote-9.4.18.v20190429-config.jar...  2019-04-29 21:10       801      
infinispan-remote-9.4.18.v20190429-config.jar...  2019-04-29 21:10        32      
infinispan-remote-9.4.18.v20190429-config.jar...  2019-04-29 21:10        40      
infinispan-remote-9.4.18.v20190429.pom            2019-04-29 21:10      1506      
infinispan-remote-9.4.18.v20190429.pom.asc        2019-04-29 21:10       801      
infinispan-remote-9.4.18.v20190429.pom.asc.as...  2019-04-29 21:10       801      
infinispan-remote-9.4.18.v20190429.pom.md5        2019-04-29 21:10        32      
infinispan-remote-9.4.18.v20190429.pom.sha1       2019-04-29 21:10        40 
```

Unfortunately, this makes the dependency management for them useless. 

```xml
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>infinispan-remote</artifactId>
    <classifier>config</classifier>
</dependency>
```

The above fails as no version is provided for the dependency with the `config` classifier.

```xml
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>infinispan-remote</artifactId>
</dependency>
```

The above fails as the `org.eclipse.jetty:inifinispan-remote:9.4.18.v20190429` dependency does not exist.

**Comment by janbartel** [comment]
@wilkinsona  can you show me an example of how you are expecting to use the jetty-bom?

**Comment by wilkinsona** [comment]
Here's a complete pom for the first case I described above:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>example</groupId>
	<artifactId>jetty-bom-problem</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>jetty-bom-problem</name>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-bom</artifactId>
				<version>9.4.18.v20190429</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>infinispan-remote</artifactId>
			<classifier>config</classifier>
		</dependency>
	</dependencies>

</project>
```

**Comment by janbartel** [comment]
@wilkinsona ok, but there is no code in infinispan-remote to depend on, it's all just configuration, so I don't see the value in using a dependency on it?  You want to get all of it's transitive deps, is that it? Can you explain how you are intending to use the infinispan-remote module?

**Comment by wilkinsona** [comment]
The problem came to my attention as part of verifying Spring Boot's bom which imports Jetty's bom. We have [a tool](https://github.com/spring-io/bomr) that verifies that every dependency managed by Spring Boot's bom can be resolved.

I'm not familiar with the specific purpose of the `infinispan-remote` module but, presumably, it's published to Maven Central as you expect it to be used. Perhaps in a build that uses Maven's dependency or assembly plugin to depend upon it and extract some of the configuration from the jar? As things stand, the bom cannot be used to manage the version of a dependency on the `infinispan-remote` module. FWIW, I believe the problem can be addressed by adding `<classifier>config</classifier>` to the entry in the bom for `infinispan-remote`.

**Comment by janbartel** [comment]
@joakime can you comment please - I'm minded to just remove all the jetty-infinispan declarations from the jetty-bom, I just don't see the point of them being there?

**Comment by joakime** [comment]
if we have (non-test) artifacts on maven central, then they should be in the jetty-bom.
In this specific case, the entry for `infinispan-remote` should have a classifier for the config, as there's no default jar file artifact.
But in reality, how is `infinispan-remote` used in an application?  Does a runtime class access that data?
Or is it just used to build a `jetty-home`, like the other `config` classified artifacts?

@olamy any input on this?

**Comment by janbartel** [comment]
> if we have (non-test) artifacts on maven central, then they should be in the jetty-bom.
But many modules have classifier config artifacts, and I can't see them of being any use to anyone, other than the jetty distro build? So clearly we do have artifacts on maven central that are not represented in the bom.

In reality, both infinispan-embedded and infinispan-remote contain no code, just .mod and .xml files that help set up infinispan. The infinispan-embedded-query and infinispan-remote-query and infinispan-common on the other hand, do all contain classes (along with .mod and .xml files).

**Comment by joakime** [comment]
if that `<classifier>config</classifier>` isn't used at runtime, then remove it.
People that want to build/modify a `jetty-home` programmatically should just use the `jetty-home` artifacts to start with anyway.

**Comment by olamy** [comment]
as those artifacts will be not be used by users building their own emebedded jetty we can definitely get rid of those dependencies declarations in the bom

**Comment by janbartel** [comment]
Change applied for 9.4.19 and beyond. 

If there are still problems, please reopen.
