### ISSUE TITLE
Unwrap JavaxWebSocketClientContainer.connectToServer() exceptions

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3696]
`JavaxWebSocketClientContainer.connectToServer()` - which is a WebSocket API blocking method that throws IOException - is implemented using `Future.get()`.

Any exception in the actual connection attempt is therefore wrapped into an `ExecutionException`, which is unexpected by the user code calling `connectToServer()` which expects the wrapped `IOException` instead - `ExecutionException` is an implementation detail that we should not leak out.

**Comment by joakime** [comment]
This is Jetty 10?

**Comment by sbordet** [comment]
> This is Jetty 10?

Yes

**Comment by joakime** [comment]
@lachlan-roberts opened PR #3699
