### ISSUE TITLE
Review JNDI logging

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3697]
`NamingUtil` in `jetty-jndi` has a logger that is only called `jndi`, not the usual `org.eclipse.jetty.jndi.NamingUtil`.

Many other classes in the `jetty-jndi` module reference this logger (also weird).

Typical logging configurations that set the logging level for `org.eclipse.jetty` won't work on this logger - it does not match.

Is there any reason for the name of this logger?

**Comment by joakime** [comment]
This logging behavior was introduced back in Dec 2010 by @gregw in commit 2b43ae931cdbadcc2db001aed740ed91be1a75e8 (not associated with any bug/issue)

**Comment by janbartel** [comment]
We should be able to just call Log.getLogger("org.eclipse.jetty.jndi"), same way we do for sessions (eg all session code does Log.getLogger ("org.eclipse.jetty.server.session")). As the jndi stuff - same as the session stuff - has various flavours that are pluggable at runtime, the user shouldn't have to worry about enabling logging on exactly which individual impl classes.

**Comment by sbordet** [comment]
@janbartel I consider it a feature that I can only enable e.g. the JDBC session implementation rather than all of the implementation.

Users can always configure their loggers to log everything from "org.eclipse.jetty.server.session", but if we use only that they won't be able to fine tune the logging as they please.

I think we should just stick with the idiom and use `Log.getLogger(<current class>)` everywhere.

**Comment by janbartel** [comment]
@sbordet  if you're using the JDBC session store impl, then its immaterial if Infinispan session store impl etc all have the same logger, as they will never ever be called. Moreover, it is extremely rare that you would only ever want to enable logging on a single class in the session stuff - it's a machine of many many moving parts and you need to see how they all interact, logging on a single class is next to useless.

That said, the use of a fixed string for logging the session stuff is very historical in jetty, probably pre logging at an individual class level, so all of the session stuff could be changed to use individual class name logging, but I think that is of infinitesimally small benefit.

For the jndi stuff, we could do individual class logging - @gregw no reason why you picked a fixed string of "jndi" is there? Classloading issues or anything?

**Comment by gregw** [comment]
I have no recollection of why I did that!!!!
I can see no reason why we would not just use the per class logger pattern we use everywhere else?  It has all the power and flexibility needed to log selectively or by specific package/classes

**Comment by sbordet** [comment]
Let's clean up this old cruft then!
