### ISSUE TITLE
Swap various java.lang.String replace() methods for better performant ones

### ISSUE THREAD

**Issue by c6zo2sYjG** [eclipse/jetty.project#3708]
JDK before version 9 uses regular expressions in such methods:
* java.lang.String#replace(java.lang.CharSequence, java.lang.CharSequence)
`
public String replace(CharSequence target, CharSequence replacement) {
        return Pattern.compile(target.toString(), Pattern.LITERAL).matcher(
                this).replaceAll(Matcher.quoteReplacement(replacement.toString()));
}
`
* java.lang.String#replaceFirst
`
public String replaceFirst(String regex, String replacement) {
        return Pattern.compile(regex).matcher(this).replaceFirst(replacement);
}
`
* java.lang.String#replaceAll
`
public String replaceAll(String regex, String replacement) {
        return Pattern.compile(regex).matcher(this).replaceAll(replacement);
}
`
It leads to the serious performance issue:
* https://blog.jooq.org/2017/10/11/benchmarking-jdk-string-replace-vs-apache-commons-stringutils-replace/
* https://github.com/qxo/Benchmark4StringReplace
Apache Commons Lang’s StringUtils drastically outpeforms the JDK’s String.replace() in every discipline, especially when no match is found in a short string.

Also this issue was partially fixed for `replace` method in` JDK 9.

So I suggest to enhance the following points:
1. java.lang.String#replace(java.lang.CharSequence, java.lang.CharSequence) can be changed by Apache Commons Lang StringUtils#replace(java.lang.String, java.lang.String, java.lang.String) with qoute replacement.
2. String#replaceFirst can be changed to the StringUtils#replace(java.lang.String, java.lang.String, java.lang.String, int) with last argument as "1".
3. java.lang.String#replaceAll can be changed by StringUtils#replace(java.lang.String, java.lang.String, java.lang.String)

But I didn't find
`
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.9</version>
</dependency>
`
So can I still add this improvement? And how can I use StringUtils from common-lang3?

**Comment by joakime** [comment]
It is highly unlikely that we will pull in the dependency for `commons-lang3` just for to use one method.

**Comment by joakime** [comment]
Excluding test cases, we have ...

* 29 instances where we use `String.replace(String,String)`
* 2 instances where we use `String.replaceFirst(String, String)`
* 16 instances where use use `String.replaceAll(String, String)`

It would be easier to just expand on our `StringUtil` for those usages.
Create a jmh test to prove things out, etc ...

**Comment by joakime** [comment]
Opened PR #3768

**Comment by joakime** [comment]
Merged PR #3768
