### ISSUE TITLE
WebSocket Sub-Protocol validation behaviors need validation

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3709]
WebSocket Sub-Protocol behaviors in Jetty 9.4.x seem to not follow the spec.
This needs to be validated.

Sections of spec that are important ...

https://tools.ietf.org/html/rfc6455#page-7

>   The server selects one or none of the acceptable protocols and echoes
>   that value in its handshake to indicate that it has selected that
>   protocol.

... and ...

>   Option fields can also be included.  In this version of the protocol,
>   the main option field is |Sec-WebSocket-Protocol|, which indicates
>   the subprotocol that the server has selected.  WebSocket clients
>   verify that the server included one of the values that was specified
>   in the WebSocket client's handshake.  A server that speaks multiple
>   subprotocols has to make sure it selects one based on the client's
>   handshake and specifies it in its handshake.

https://tools.ietf.org/html/rfc6455#page-20

>    6.  If the response includes a |Sec-WebSocket-Protocol| header field
>       and this header field indicates the use of a subprotocol that was
>       not present in the client's handshake (the server has indicated a
>       subprotocol not requested by the client), the client MUST _Fail
>       the WebSocket Connection_.

**Comment by gregw** [comment]
@joakime I think this is similar to the extension handling that @lachlan-roberts fixed in 10.  Ie the negotiated extensions are echoed with their selected parameters (not just names).

**Comment by joakime** [comment]
You can't echo the parameters in 100% of cases.  
`permessage-deflate` for example needs a subset of parameters. (stripping out the various `max_window_bits` parameters) especially for Chrome users.

**Comment by lachlan-roberts** [comment]
Yes the parameters can be changed on the response. Some of the things I added for extensions and sub-protocol in jetty-10 were:
- The client can request multiple requests with different parameter sets, so ensure only one extension of the same name is echoed back
- Make sure all negotiated extensions were actually requested by the client (checked on server and client sides)
- Verify that any subprotocol selected by the server was actually offered by the client
- If a subprotocol was not selected make sure no subprotocols were offered


<br>

I'm not so sure if that last point is correct now... the spec says
```
|Sec-WebSocket-Protocol|, which indicates
the subprotocol that the server has selected. WebSocket clients
verify that the server included one of the values that was specified
in the WebSocket client's handshake. A server that speaks multiple
subprotocols has to make sure it selects one based on the client's
handshake and specifies it in its handshake.
```
which seems to indicate that if a subprotocol was offered one should be selected. But it also says
`The server selects one or none of the acceptable protocols and echoes that value in its handshake` which would mean no subprotocol could be selected even if one was offered.


<br>

These changes to jetty-10 were done in #3478 and #3470.
And this behaviour is tested in [WebSocketNegotiationTest](https://github.com/eclipse/jetty.project/blob/f4f9763761fb270d217da5d88da153d5663aafef/jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketNegotiationTest.java) which might be useful to test this in 9.4.x, although its based on the core api so will need to be adapted.

**Comment by lachlan-roberts** [comment]
I think we can leave 9.4.x websocket sub-protocol validation as is.
For more thorough validation you can upgrade to 10/11.
