### ISSUE TITLE
jasper dependencies are outdated in 9.2.x

### ISSUE THREAD

**Issue by tsachev** [eclipse/jetty.project#371]
Hi is there are reason to not update the jasper dependencies to `8.0.27` in 9.2.x release, but only in 9.3.x?

**Comment by janbartel** [comment]
@tsachev  I don't believe there's an impediment. I've updated to 8.0.27. However, please be aware that we only rarely do releases of jetty-9.2, as it is superceeded. However, as its the last version before java-8 is required, we do try and keep it up-to-date ... but I can't promise a release tomorrow :)

**Comment by janbartel** [comment]
Actually I updated to 8.0.33. Release 9.2.16 should be hitting maven central anytime now.
