### ISSUE TITLE
Clean up jetty-10 modules

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3719]
The module mechanism needs some clean up, specifically in regards to how some xml files are setup.  Most modules put their XMLs into $JETTY_HOME/etc and they are used from there, but a few put them in $JETTY_BASE/modules/$MODULE and copy them into $JETTY_BASE/etc as the module is enabled.  The difference being the expectation that the xml will need to be modified or not.

We need to make sure the right modules are using the right mechanism.  Currently:
+ customrequestlog does the copy, but it's XML could easily be parameterized, so it should never need to be edited and thus should be in $JETTY_HOME.
+ rewrite module doesn't copy, yet its xml must be edited if the module is to be meaningful, so it should be copied.

**Comment by gregw** [comment]
Note also that customrequestlog can now just be renamed requestlog as there is no alternative.

**Comment by gregw** [comment]
Looking at the jetty-server -config artefact, I can see that it contains:
+ etc/jetty-ssl-context.xml.orig
+ modules/requestlog/.idea/misc.xml

so we need to be a bit better how we create that!

**Comment by gregw** [comment]
@olamy can you look at how we can exclude files from .gitignore (like .orig etc.) from being included in -config artefacts?

**Comment by joakime** [comment]
The `modules/requestlog/.idea/misc.xml` shouldn't even be there.
That directory `/.idea/` is in the wrong place entirely.

Taking a look at what files we have to deal with ...

```
$ find . -wholename "*/src/main/config/*" -type f -print
```

Perhaps it should be ...

**config-assembly.xml**

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<assembly>
  <id>config</id>
  <includeBaseDirectory>false</includeBaseDirectory>
  <formats>
    <format>jar</format>
  </formats>
  <fileSets>
    <fileSet>
      <directory>${project.build.directory}/config</directory>
      <outputDirectory></outputDirectory>
      <includes>
        <include>**/*.mod</include>
        <include>**/*.xml</include>
        <include>**/*.properties</include>
        <include>**/*.ini</include>
        <include>**/*.conf</include>
        <include>**/*.txt</include>
        <include>**/keystore*</include>
      </includes>
      <excludes>
        <exclude>*/.idea/*</exclude>
      </excludes>
    </fileSet>
  </fileSets>
</assembly>
```

We still won't capture 100% of the files.
But those are easily fixed (renamed) to fit within the limited allowed names.

Eg (not an exhaustive list):

```
./jetty-security/src/main/config/etc/README.spnego
./jetty-overlay-deployer/src/main/config/overlays/nodes/README.TXT
./jetty-overlay-deployer/src/main/config/overlays/instances/README.TXT
./jetty-overlay-deployer/src/main/config/overlays/webapps/README.TXT
./jetty-overlay-deployer/src/main/config/overlays/templates/README.TXT
```

**Comment by joakime** [comment]
I could be convinced that the exclusions should cover all `.` (dot) prefixed directories and files.

Eg:

``` xml
      <excludes>
        <exclude>**/.*/**</exclude>
        <exclude>**/.*</exclude>
      </excludes>
```
