### ISSUE TITLE
Produce warnings for bad ServletContextHandler Base Resource usage

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3724]
I'd like to produce a warning message if a ServletContextHandler is started without a Base Resource declared.

Also, if ...

* the Base Resource is not a directory
* the Base Resource doesn't exist

I am motivated because of this SO question.
https://stackoverflow.com/questions/56379066/how-can-i-change-this-to-replace-the-404-page-error-with-a-html-page

**Comment by janbartel** [comment]
I'm not in favour of a warning if there is no base resource - it's perfectly valid to have no static content in your context. But if there is one provided, then yes I think it is reasonable to check it's a directory and it exists.

**Comment by joakime** [comment]
I'm not proposing that we fail the ServletContextHandler startup, just that it produce a warning.

if we don't have a Base Resource then the following do not work ...

* ServletContext.getRealPath(String)
* ServletContext.getResource(String)
* ServletContext.getResourceAsStream(String)
* ServletContext.getResourcePaths(String)
* ServletContext.getRequestDispatcher(String)
* JasperJspServlet init (which uses the features above)
* ErrorPageErrorHandler.addErrorPage(int, String)

Also if there is no Base Resource at ServletContextHandler.doStart() ...

* we shouldn't use the `webdefault.xml`.
* there shouldn't be a DefaultServlet added automatically (it should be `Default404Servlet` only).
* invalid entries on WelcomeFiles and ErrorPageErrorHandler should also throw warnings (if they don't point to existing registered Servlets). 

While it's valid in a narrow subset of usages of ServletContextHandler to not have a Base Resource, the minute you step into other common features of the servlet spec and jetty behaviors the Base Resource becomes required/mandatory.

**Comment by joakime** [comment]
The following methods should also throw a hissy fit and an IllegalStateException if a base resource isn't declared saying as much.

* ServletContext.getRealPath(String)
* ServletContext.getResource(String)
* ServletContext.getResourceAsStream(String)
* ServletContext.getResourcePaths(String)

If the `DefaultServlet` exists, is dispatched to, and a base resource isn't declared (in the ServletContextHandler or the init-param of the DefaultServlet) then that should also throw an exception / error (and/or Log a warning)

**Comment by janbartel** [comment]
ServletContextHandler doesn't know anything about webdefault.xml, that's only in WebAppContext. Similarly a DefaultServlet is only added by webdefault.xml for WebAppContexts, not ServletContextHandler.

I still think that it is perfectly valid to have a ServletContextHandler, indeed a WebAppContext, that does not have any static content, and thus a resource base. Printing out a warning when the user intends to not have a resource base may be confusing? it's certainly going to generate a heck of lot more log lines in jetty unit and integration tests :)

**Comment by gregw** [comment]
If a warning is to be produced, it should only be if one of those methods is called rather than at startup.   Note also that requests may not even have a context at all, so all those methods return null in that case.
