### ISSUE TITLE
Remove OSGi export uses of servlet-api from jetty-util

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3726]
Testing #3703 has revealed that jetty-util incorrectly says that it uses servlet-api in it's exports.

**Comment by gregw** [comment]
To expand more on what the issue is....

jetty-util should not really use the `servlet-api`, it is only a provided dependency because the deprecated `MultiPartInputStreamParser` was erroneously added to `jetty-util`.   The bundle plugin analyses the exported APIs from jetty-util and see that `javax.servlet.http.Part` is exposed in an API, thus in the OSGI export of `org.eclipse.jetty.util` it includes a uses clause for the specific version of the servlet-api used.   This is different to an OSGi import, which declares what is used in the implementation, as it is declaring what is used in the public interface to the bundle.

The consequence of this is that the jetty-util OSGi module cannot be used by an OSGi webapp that is deployed on a server that uses a different version of the `servlet-api`, because the `servlet-api` is used in the API contract between the web application bundle and the server bundle, it's version is fixed.  This can then clash with the exported servlet-api version of `jetty-util`

**Comment by joakime** [comment]
Testing of #3703 is for Jetty 10.0.x?
But that class, `MultiPartInputStreamParser` was removed from jetty 10.0.x.

So this is a jetty-9.4.x specific issue?

**Comment by gregw** [comment]
@joakime it is a using jetty-util-9.4 in an OSGi webapp deployed in jetty-10.

For now, I'm going to remove the test in #3703, because we know it works when tested against a 9.4 SNAPSHOT.  will re-enable test once we have a corrected 9.4 release... not that we really know how to do that yet.... other than assign to @janbartel and wait :)

**Comment by janbartel** [comment]
Closing this, as appropriate fixes were committed to jetty-9 and jetty-10.
