### ISSUE TITLE
metadata==null should be processed separately

### ISSUE THREAD

**Issue by dsyzhu** [eclipse/jetty.project#3728]
Class Request function extractQueryParameters()

if (metadata==null || metadata.getURI() == null || !metadata.getURI().hasQuery())
            _queryParameters=NO_PARAMS;

metadata==null may be processed separately. Otherwise sometimes dirty request object is used without being noticed

**Comment by gregw** [comment]
I'm not sure I understand?   If a request object is being used incorrectly after a request is completed, it can fail in many different ways.
So perhaps we should throw ISE here if metadata==null,  but the program calling it is broken anyway.

**Comment by dsyzhu** [comment]
Our use case is extractQueryParameters() is called during the recyle() is running. So when the request object is reused for following query _queryParameters=NO_PARAMS. No request execution failure. Just wrong query parameters are used.

What is the best way to avoid this?

Thanks

**Comment by sbordet** [comment]
@dsyzhu `extractQueryParameters()` is called by your application. If it is called during `recycle()` it means that you are using the request object beyond its lifecycle, where it is illegal to use as per the Servlet specification.
Your solution is to call `getParameters()` which in turn calls `extractQueryParameters()` earlier in the request processing when the object is still valid.

**Comment by dsyzhu** [comment]
@sbordet ,

Thanks for the replying.

So it is the app's responsibility to make sure calling extractQueryParameters() during lifecyle? I know our use case is not proper. Should at least some warning message in the log to notice this?

**Comment by sbordet** [comment]
Yes it's the application responsibility to call `getParameters()` when the request object is valid.

It's not possible, in general, to warn about improper concurrent usage without grabbing a coarse lock that will kill the performances.

**Comment by joakime** [comment]
@dsyzhu when we encounter users doing this (accessing the HttpServletRequest outside of the prescribed lifecycle) they often are not aware of other features present in either Jetty or the Servlet spec.

If you are writing some kind of metrics tooling, consider using the [`HttpChannel.Listener`](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/HttpChannel.Listener.html) instead.

If you are using the `HttpServletRequest` from multiple threads, consider using the [`javax.servlet.AsyncContext`](https://docs.oracle.com/javaee/7/api/javax/servlet/AsyncContext.html) to properly manage the lifecycle.

**Comment by dsyzhu** [comment]
@joakime ,

Thank you very much for the suggestion.

Am working on platform apis. It is not guaranteed all apps to code correct. From platform apis perspectives what is the preferred  processing if apps happen to call extractParameters outside lifecycle of a request object? 

Thanks.

**Comment by gregw** [comment]
@dsyzhu any application code that calls any request methods after the end of the lifecycle is very error prone and can/will result in unpredictable behaviour.   We probably should throw an ISE exception in this case, but that would not help you much as by the nature of the problem it is async and the failure could happen 1 ns after we do the == null check!

From a platform point of view, it would be best to not allow application code to hold references to request objects.  Instead, your platform can hold the reference, perhaps in an AtomicReference, then when the request is complete you can null that reference and all future access attempts will fail or become noops.

**Comment by joakime** [comment]
Jetty recycles request objects (which is allowed in the servlet spec, and many application servers do this), those bad apps that hold onto request references from old requests and are now operating on a new / unrelated request.
At a minimum they have bad data, at worst, they are changing a request behavior on a different request (**a really bad thing ™**)
