### ISSUE TITLE
Allow non-RFC 2616 characters in headers

### ISSUE THREAD

**Issue by andrewgaul** [eclipse/jetty.project#373]
Some servers like AWS S3 allow non-RFC 2616 characters in headers, e.g., `\x04`.  I would like Jetty to optionally allow these characters to enable other servers like [S3Proxy](https://github.com/andrewgaul/s3proxy) to emulate this behavior.  Currently Jetty rejects these with:

```
W 07-24 11:08:02.144 S3Proxy-14 o.e.jetty.http.HttpParser:1719 |::] Illegal character 0x4 in state=HEADER_IN_VALUE for buffer HeapByteBuffer@3d6811d8[p=279,l=410,c=16384,r=131]={PUT /gaul-33o3yv7...-meta-meta1: h\x04<<<w\r\nAuthorization:...-57-generic\r\n\r\n>>>\r\n\r\n-generic\r\n\r\n\n...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
W 07-24 11:08:02.144 S3Proxy-14 o.e.jetty.http.HttpParser:1344 |::] badMessage: 400 Illegal character 0x4 for HttpChannelOverHttp@4b0947c6{r=1,c=false,a=IDLE,uri=-}
```

References andrewgaul/s3proxy#75.

**Comment by gregw** [comment]
Andrew,  RFC2616 has been replaced with RFC7230 and it is even more precise about what characters are acceptable.  \x04 is certainly not an acceptable character by the RFC.

Why do you wish to send \x04 characters in headers? is it only to mimic AWS S3?  What S3 headers required such characters?

I am not inclined to change the parser away from RFC compliance as that the road towards security violations and/or other incompatibilities.   Rather you should raise a bug on AWS to say that they should not accept such headers!

**Comment by gregw** [comment]
Not going to fix based on current information.  Please reopen if you have more arguments about why we should not follow the standard.

**Comment by voa808** [comment]
@andrewgaul : I am facing similar issue while running s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_infix(https://github.com/ceph/s3-tests). Getting "S3ResponseError: S3ResponseError: 400 Illegal character 0x4". Were you able to surpass the issue anyway?

**Comment by andrewgaul** [comment]
@voa808 Unfortunately I do not know a workaround.  It would be nice if Jetty supported non-conformant headers to allow conformance with buggy servers.  Perhaps behind a configuration knob?  I am curious if you are experiencing this with S3Proxy or another S3 implementation?

**Comment by joakime** [comment]
BTW, The header behavior in Jetty became more strict in the Jetty 9.4.3 recently.
See: https://webtide.com/jetty-cookies-and-rfc6265-compliance/

Also, [the test you are failing is specifically flagged as being `@attr('fails_strict_rfc2616')`](https://github.com/ceph/s3-tests/blob/master/s3tests/functional/test_s3.py#L1228-L1236).
Added as part of ceph/s3-tests@09681c62dcd046e81a81cae1ae1a76ca14c4ff54 (back in Jul 2012)
