### ISSUE TITLE
DistributionTester.Run not closing child process

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#3733]
when testing logging module or any module forking an other process the child process is not closed (related to #1822)
easy fix with jdk11 as Process has descendants methods (but not for jdk8/jetty-9.4.x)

**Comment by sbordet** [comment]
@olamy `jetty-start` `Main` class is what forks the child process. I see there it attached a shutdown hook to the parent to destroy the child, so children processes should be destroyed.
Why is that not the case?

**Comment by olamy** [comment]
@sbordet currently close use destroy so destroyForcibly. This is probably doing a brutal kill not executing shutdown hook. changing to use destroy fix my case (Using OSX but I need to test on Ubuntu)

**Comment by olamy** [comment]
@sbordet confirmed to fail on ubuntu as well.

**Comment by joakime** [comment]
Opened PR #3742

**Comment by joakime** [comment]
Merged into jetty-9.4.x
