### ISSUE TITLE
websocket suspend when input closed

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3734]
suspending a WebSocket when it is already input closed has different behavior from jetty-9 to jetty-10
- jetty-10 an ISE is thrown
- jetty-9 it is a no-op

`SuspendResumeTest.testSuspendAfterClose()` has been disabled in jetty-10 as I was not sure which approach was correct.

**Comment by gregw** [comment]
I think ISE is probably the most correct API choice... but if there is need we could maintain behaviour with jetty-9 as no-op is OKish.  @joakime your thoughts?

**Comment by joakime** [comment]
I personally like the ISE.
It sends a clear message to the application user that they need to tighten up their suspend logic.
They can choose to correct their implementation, or ignore the ISE.

**Comment by lachlan-roberts** [comment]
changed suspend while closed to throw ISE in both jetty-9.4.x and jetty-10.0.x
