### ISSUE TITLE
ClassCastException in WriteFlusher.java - IdleState cannot be cast to FailedState

### ISSUE THREAD

**Issue by shamsimam** [eclipse/jetty.project#3746]
This happened for us while streaming chunks of data asynchronously.

Detailed stack trace (from a Clojure project):

Jetty version: 9.4.18.v20190429

```
#error {
 :cause org.eclipse.jetty.io.WriteFlusher$IdleState cannot be cast to org.eclipse.jetty.io.WriteFlusher$FailedState
 :via
 [{:type java.lang.ClassCastException
   :message org.eclipse.jetty.io.WriteFlusher$IdleState cannot be cast to org.eclipse.jetty.io.WriteFlusher$FailedState
   :at [org.eclipse.jetty.io.WriteFlusher fail WriteFlusher.java 310]}]
 :trace
 [[org.eclipse.jetty.io.WriteFlusher fail WriteFlusher.java 310]
  [org.eclipse.jetty.io.WriteFlusher write WriteFlusher.java 304]
  [org.eclipse.jetty.io.AbstractEndPoint write AbstractEndPoint.java 380]
  [org.eclipse.jetty.http2.HTTP2Flusher process HTTP2Flusher.java 247]
  [org.eclipse.jetty.util.IteratingCallback processing IteratingCallback.java 241]
  [org.eclipse.jetty.util.IteratingCallback iterate IteratingCallback.java 224]
  [org.eclipse.jetty.http2.HTTP2Session newStream HTTP2Session.java 569]
  [org.eclipse.jetty.http2.client.http.HttpSenderOverHTTP2 sendHeaders HttpSenderOverHTTP2.java 95]
  [org.eclipse.jetty.client.HttpSender send HttpSender.java 214]
  [org.eclipse.jetty.http2.client.http.HttpChannelOverHTTP2 send HttpChannelOverHTTP2.java 96]
  [org.eclipse.jetty.client.HttpChannel send HttpChannel.java 128]
  [org.eclipse.jetty.client.HttpConnection send HttpConnection.java 201]
  [org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2 send HttpConnectionOverHTTP2.java 77]
  [org.eclipse.jetty.http2.client.http.HttpDestinationOverHTTP2 send HttpDestinationOverHTTP2.java 38]
  [org.eclipse.jetty.client.HttpDestination process HttpDestination.java 346]
  [org.eclipse.jetty.client.HttpDestination process HttpDestination.java 304]
  [org.eclipse.jetty.client.HttpDestination send HttpDestination.java 294]
  [org.eclipse.jetty.client.HttpDestination send HttpDestination.java 269]
  [org.eclipse.jetty.client.HttpDestination send HttpDestination.java 246]
  [org.eclipse.jetty.client.HttpClient send HttpClient.java 576]
  [org.eclipse.jetty.client.HttpRequest send HttpRequest.java 726]
  [org.eclipse.jetty.client.HttpRequest send HttpRequest.java 718]
  ...]}
```

**Comment by lachlan-roberts** [comment]
The `WriteFlusher` method `fail(Callback, Throwable...)` requires that the state to be `FailedState` when the method is called,  from the usages of `fail` in the code it doesn't seem this is always the case.

In this instance it looks like `Callback` given to `write()` is throwing an exception when succeeded.

https://github.com/eclipse/jetty.project/blob/5b5848eb7314a5942d8a4932c047d2e67445f186/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java#L292-L306

Say the state transition 292 succeeds, we are now in state `IDLE` and then `callback.succeeded()` throws, so in the catch we fail the state transition `WRITING->FAILED` as we have already transitioned to `IDLE`, and this results in `fail()` being called when we are still in `IDLE` state.

**Comment by sbordet** [comment]
@lachlan-roberts good analysis - it not only happens at the lines you pointed out, but in several other places.
Either we are very defensive here and wrap any possible callback completion into a `try/catch` (but then not sure what to do when a call to `succeeded()` throws), or we trust that user callbacks do not throw.
Here probably we can avoid the `ClassCastException` without being too defensive.

@shamsimam we suspect one of you `Callback.succeeded()` methods throws a `RuntimeException`, so you need to fix that while we work on avoiding the `ClassCastException`.

**Comment by shamsimam** [comment]
@sbordet we have enabled debug logging at our end and are trying to reproduce this to determine the exception that was thrown when this occurred. Can you tell me why you suspect that `Callback.succeeded()` threw an exception? We will fix the exception from `Callback.succeeded()` once we detect it.

**Comment by shamsimam** [comment]
Potentially related scenario where `Callback.succeeded()` is throwing an exception: https://github.com/eclipse/jetty.project/issues/3753
