### ISSUE TITLE
Make Jetty Demo work with JPMS

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3747]
Currently, the Jetty Demo under `demo-base` does not work when specifying `--jpms` on the command line, because it requires additional configuration (for example for JPMS module `java.sql`).

**Comment by janbartel** [comment]
Specifically:  the test-jndi and test-spec webapps use javax.sql package. @sbordet  how should webapps communicate their needs to use various jpms modules?

**Comment by sbordet** [comment]
@janbartel currently webapps cannot tell the server what they need, as JPMS is not even considered in JEE (well, even without JPMS they cannot tell the server what they need - e.g. JDBC drivers).

My idea is that we have a `jpms.mod` in the demo that is present in the `$JETTY_BASE/modules` directory but not enabled, and that will contain the required directives in the `[jpms]` section.

If you want to run the demo with JPMS, you do `java -jar start.jar --module=jpms` (i.e. add it on the fly while starting Jetty).
Sounds reasonable?

**Comment by janbartel** [comment]
Sounds like this would not be a general purpose jpms module, but rather a specific module for the demo webapps that make it work in jpms. Can't we just extend the existing demo.mod?

**Comment by sbordet** [comment]
@janbartel yes it's a specific module for the demo.
We don't want to extend `demo.mod` because we want to be able to run on the class-path and only if we add the `jpms` module on the fly on command line we switch to module-path.
