### ISSUE TITLE
DeprecationWarning Decorator

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3764]
The `DeprecationWarning` decorator is always added to the `DecoratedObjectFactory` in the constructor of `ServletContextHandler`.
However, over a stop/start cycle the factory is cleared and the decorator is not re-added.

Moreover, is it really our responsibility to always warn if a deprecated servlet is used?  Could we not make this optional? Perhaps in jetty-10 we can have a DeprecatedConfiguration that will add this decorator in pre-configure (and thus will work over stop/start)?

**Comment by joakime** [comment]
Stop / Start is not typical behavior.

The `DeprecationWarning` decorator notifies on many things, not just Servlets.
Add the obvious Filters and Listeners to the list, and then you start to see where this becomes useful.
As an example, we've had multiple reports that this helped folks understand that `GzipFilter` needed to be replaced as it was deprecated.

I say we don't bother with stop/start behavior and leave it like it is.
