### ISSUE TITLE
Issue with default cipher excludes in org.eclipse.jetty.util.ssl.SslContextFactory

### ISSUE THREAD

**Issue by wilx** [eclipse/jetty.project#3773]
I think there is an issue with the default cipher excludes in org.eclipse.jetty.util.ssl.SslContextFactory. Code says:

```java
    private SslContextFactory(boolean trustAll, String keyStorePath)
    {
        setTrustAll(trustAll);
        addExcludeProtocols("SSL", "SSLv2", "SSLv2Hello", "SSLv3");
        setExcludeCipherSuites("^.*_(MD5|SHA|SHA1)$");
        if (keyStorePath != null)
            setKeyStorePath(keyStorePath);
    }
```

It excludes old SSL protocols which should I think imply availability of TLSv1, TLSv1.1 and TLSv1.2 (Java 8 in my case). However the `setExcludeCipherSuites("^.*_(MD5|SHA|SHA1)$");` line actually excludes all TLSv1.1 and 1.0 cipher suites. We have added the following XML configuration bit to override the Jetty default:

```xml
                    <Set name="excludeCipherSuites">
                      <Array type="java.lang.String">
                        <Item>^.*_MD\d$</Item>
                        <Item>^.*_NULL.*$</Item>
                        <Item>^.*_anon.*$</Item>
                        <Item>^.*_RC\d.*$</Item>
                        <Item>^.*_3?DES.*$</Item>
                        <Item>^.*_DHE.*$</Item>
                      </Array>
                    </Set>
```

I am all for disabling TLSv1 by default but I think it should be explicit through the `addExcludeProtocols` above.

**Comment by joakime** [comment]
TLSv1 is still possible on IBM Java 8 JVM, Android Java 8 JVM, Azul systems JVM, Amazon JVM, and even the Oracle Java 8 with more/stronger security providers installed.

I believe the OpenJDK project is planning on disabling TLSv1 in a (near) future release.
But I can't find that on the security / crypto roadmap page at Oracle ... 
https://java.com/en/jre-jdk-cryptoroadmap.html

**Comment by joakime** [comment]
I wonder if there's a way to use the standard APIs to interrogate the Protocol / Cipher lists and see which ciphers work with which protocols.

We could improve our debug / dump output with that detail on the Protocols side indicating something like "Not possible to use, no supported Cipher Suite enabled" ...

```
|  += SslConnectionFactory@26e356f0{SSL->http/1.1} - STARTED
|  |  += Server@5b38c1ec[provider=null,keyStore=file:///home/joakim/code/jetty/distros/bases/ssl-dump-base/etc/keystore,trustStore=file:///home/joakim/code/jetty/distros/bases/ssl-dump-base/etc/keystore] - STARTED
|  |     +> trustAll=false
|  |     +> Protocol Selections
|  |     |  +> Enabled size=4
|  |     |  |  +> TLSv1
|  |     |  |  +> TLSv1.1
|  |     |  |  +> TLSv1.2
|  |     |  |  +> TLSv1.3
|  |     |  +> Disabled size=2
|  |     |     +> SSLv2Hello - ConfigExcluded:'SSLv2Hello' JVM:disabled
|  |     |     +> SSLv3 - ConfigExcluded:'SSLv3' JVM:disabled
|  |     +> Cipher Suite Selections
|  |        +> Enabled size=27
|  |        |  +> TLS_AES_128_GCM_SHA256
|  |        |  +> TLS_AES_256_GCM_SHA384
|  |        |  +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
|  |        |  +> TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
|  |        |  +> TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_EMPTY_RENEGOTIATION_INFO_SCSV
|  |        +> Disabled size=18
|  |           +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|  |           +> TLS_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|  |           +> TLS_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|  |           +> TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|  |           +> TLS_RSA_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|  |           +> TLS_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^TLS_RSA_.*$'
```

**Comment by wilx** [comment]
I think the grouping is well enough visible in <https://www.openssl.org/docs/man1.1.0/man1/ciphers.html>. Their _TLS v1.0 cipher suites_ list matches what I can see in [RFC 2246](https://www.rfc-editor.org/rfc/rfc2246.html) under _A.5. The Cipher Suites_ section. All of the original TLS 1.0 cipher suites are now obsolete and excluded by Jetty's defaults. Java seems to support all of the AES suites in [RFC 3268](https://www.ietf.org/rfc/rfc3268) extending TLS 1.0 but they are also excluded due to SHA1. This leaves the cipher suites pool for TLS 1.0 empty.

**Comment by sbordet** [comment]
@wilx I'm not sure I understand your suggestion? Are you saying that we should disable `TLSv1` and `TLSv1.1` by default?

**Comment by wilx** [comment]
> I'm not sure I understand your suggestion? Are you saying that we should disable TLSv1 and TLSv1.1 by default?

Well, Jetty is already disabling it now by exclusion of SHA-1. Why not be explicit about it?

> Given that TLS always tries the most recent protocol, you must have configured the server to explicitly exclude TLSv1.2 or higher, so if you are explicitly configuring SslContextFactory you have probably already configured the ciphers as well.

No. The server has TLS 1.2 enabled. In fact, it has TLS 1 through TLS 1.2 enabled in our default configuration. But not all clients support it TLS 1.2 or newer, so they connect with earlier TLS and cipher suites and that fails with default Jetty configuration due to exclusion of SHA-1 as I have described.

**Comment by sbordet** [comment]
> But not all clients support it TLS 1.2 or newer, so they connect with earlier TLS and cipher suites and that fails with default Jetty configuration due to exclusion of SHA-1 as I have described.

That is exactly intended. If you want to allow insecure clients to connect, you have to tweak the ciphers and allow insecure or weak ones.

So with the current setup, you only have to tweak the ciphers; with your proposed setup you would have to tweak the ciphers _and_ the protocols.

Seems to me that the current setup is better. What am I missing?

**Comment by wilx** [comment]
It is rather non-obvious. I expect that if I connect with TLS 1 as protocol I will be able to continue and find a common cipher suite from TLS 1 cipher suites list. But because SHA-1 is rejected, I get no cipher suite overlap error. If instead I got unsupported protocol error I would know immediately. 

What I want is a consistent setting. If you are already rejecting TLS 1 *and* TLS 1.1 via SHA-1 rejection, why not go all the way and actually say that via the protocols exclusion?

Ultimately, I now have the experience and I can work around this. But it is rather unexpected and takes time to realise what is wrong the first time one encounters this.

**Comment by sbordet** [comment]
> I expect that if I connect with TLS 1 as protocol I will be able to continue and find a common cipher suite from TLS 1 cipher suites list.

That is not the case. Ciphers evolve faster than the TLS protocol, so you can easily connect with `TLSv1.1` and a stronger cipher that is not listed in the `TLSv1.1` RFC.
For example, HTTP/2 forbids all the ciphers of `TLSv1.2` and mandates a stronger one, see https://tools.ietf.org/html/rfc7540#section-9.2.2.

**Comment by sbordet** [comment]
I'm inclined to close this issue, I think the current behavior is correct.
Please reopen/comment if you have more thoughts.
