### ISSUE TITLE
QueuedThreadPoolTest.testLifeCycleStop() race can stop to run the second job

### ISSUE THREAD

**Issue by aschugunov** [eclipse/jetty.project#3785]
```
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.eclipse.jetty.util.thread.QueuedThreadPoolTest.testLifeCycleStop(QueuedThreadPoolTest.java:392)
```

The reason is QueuedThreadPool gets stop status faster than all necessary jobs are run.
This issue can be solved by Thread.sleep() before `tp.stop`
Nonetheless, I have found comments `TODO need to give time for threads to read idle poll after setting idle` in `testDump`. 
It looks like the same issue.

Do you have some vision for solving them?

**Comment by joakime** [comment]
What branch are you building? 
With what version of Java?
With what version of Maven?
On what OS?

**Comment by joakime** [comment]
Also, what kind of Machine are you using to build/test on?
It could be that the 200ms expectation for stop is just too slow on your machine.

**Comment by aschugunov** [comment]
branch - jetty-9.4.x (Updating to version 9.4.20-SNAPSHOT)
version of Java - 1.8.0_171
version of Maven - 3.5.3
OS - Windows 10
I run QueuedThreadPoolTest on i7 7700 3.6GHz 16Gb RAM

**Comment by lachlan-roberts** [comment]
I think `QueuedThreadPool.doStop()` was interrupting the jobs before they reached the try/finally block in `RunningJob.run()`.  I have made some changes here (0a7d2005672f49406b45c77ebef3933d003f425e) to wait for the jobs to be running before `tp.stop()`. @aschugunov can you run the test with these changes to confirm if it fixes the issue on your machine.

**Comment by aschugunov** [comment]
Yes, it works.
Thanks.
