### ISSUE TITLE
XmlConfiguration set from property

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3789]
The jetty xml files have many `Set` clauses like:
```xml
        <Set name="forwardedHostHeader"><Property name="jetty.httpConfig.forwardedHostHeader" default="X-Forwarded-Host"/></Set>
```

This means that during startup the setter is always called and there is a default value in the XML.      It may improve startup time and reduce the duplication of default values if we implemented the following:
```xml
        <Set name="forwardedHostHeader" property="jetty.httpConfig.forwardedHostHeader"/>
```
where the setter is only called if the property is actually set.

**Comment by gregw** [comment]
@sbordet @joakime @janbartel thoughts?

**Comment by joakime** [comment]
+1 from me, I'm good with that syntax.

**Comment by janbartel** [comment]
I think it's a good idea. Just have to be sure some XML files aren't relying on the default value being set.

**Comment by gregw** [comment]
@janbartel I've been reviewing the XMLs as I modify them and keeping defaults if they differ from what the class does by itself.   I'd say I'm only 98% on this and need to review some more.... but the exercise does show how annoying it is to have defaults in more than one place!
