### ISSUE TITLE
Meaning of MaxRequestsPerDestination for HTTP2 Client

### ISSUE THREAD

**Issue by iamrohitbanga** [eclipse/jetty.project#3793]
Per the [documentation](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/client/HttpClient.html#setMaxRequestsQueuedPerDestination(int)) on HTTPClient, the parameter MaxRequestsExceededPerDestination kicks if all connections managed by that destination are "busy".

What is the meaning of "busy" here esp in the context of HTTP2Client over HTTP Transport?

Since HTTP2 can have multiple requests going on concurrently why would the connection be busy.

Several options I can think of:
1. Whenever sending a frame over the connection, it might be busy due to "transmission delay" for a brief period. Is it because of the transmission delay?

2. Is it considered busy while N concurrent streams are outstanding. In other words does it include, propagation delay, server response time?

I guess even before HTTP 2 we could have pipelining, so (1) above seems more likely.

Seeking some clarification so that I can understand when the requests end up getting queued in Jetty.

Thanks in advance!

**Comment by sbordet** [comment]
In HTTP/2 a connection is busy when it has a number of outstanding streams equal to the `maxConcurrentStreams` configuration parameter. This parameter is communicated by the server to the client when the connection is opened.
