### ISSUE TITLE
Can idleTimeout seperate into keep_alive_timeout and response_timeout?

### ISSUE THREAD

**Issue by zhaowenxishi** [eclipse/jetty.project#3796]
For our server-end(nginx), we set the keep_alive timeout to a small value to get high efficiency. We use jetty as the http client-end, but jetty doesn't have keep_alive timeout. SomeTimes we do need to handle some big responses which take a long time. But due to the low keep_alive timeout of the server-end, we get a EOFException occasionally. So can idleTimeout of jetty seperate into keep_alive_timeout and response_timeout? Then the system can balance efficiency and performance。

**Comment by gregw** [comment]
Why do you think a small `keep_alive` gives you high efficiency?   Perhaps a long time ago this was true when a thread was allocated to every connection, but now all modern clients and servers are fully asynchronous internally and minimal resources are allocated to a connection (for jetty we don't even allocated buffers for a truly idle connection).       Keeping a connection alive has many good efficiencies: avoiding the latency and cost of renegotiating a connection;  use of a warmed up TCP/IP connection with flow control windows correctly sized for the network;   Even short keep alives can migrate connection data structure into longer lived GC spaces, so once there it is better for GC to keep them as long as possible.

So in almost all situations now, it is better to have high keep alive times, specially if you control both the client and the server!

But to answer your question, Jetty client has both an idletimeout on `HttpClient` and a `timeout` on the `HttpRequest`, which is the total time.
