### ISSUE TITLE
ClasspathPattern match method throws NPE. URI can be null

### ISSUE THREAD

**Issue by ruozhuochen** [eclipse/jetty.project#3798]
https://github.com/eclipse/jetty.project/blob/5e3cecee6feb9313496c1652821aca642a51ce19/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClasspathPattern.java#L356

Should the code check for null? Or relying on it being caught by 

https://github.com/eclipse/jetty.project/blob/5e3cecee6feb9313496c1652821aca642a51ce19/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClasspathPattern.java#L695

**Comment by joakime** [comment]
I think this is being fixed in Issue #3700 and PR #3777

**Comment by ruozhuochen** [comment]
thanks for the update.

**Comment by janbartel** [comment]
As PR #3777 has been committed, I am closing this issue.
