### ISSUE TITLE
XmlConfiguration whitespace mode should be configurable

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3810]
Currently, `XmlConfiguration` expects and honors whitespace in a partial way.
It performs a `String.trim()` element body content. - which seems to not get rid of things like tab/CR/LF, etc... (based on details in error messages)

This behavior should be configurable.

1. Always off - no trimming
2. All whitespace (including non-printable control characters) are trimmed.

This configuration should be baked into the XML itself, probably as an attribute.
At least at the top level `<Configuration>`, and perhaps also as an attribute on any other element to flip the value for specific use cases.

**Comment by joakime** [comment]
This is a more general case for Issue #3805

**Comment by gregw** [comment]
Currently the approach taken is that if there is an explicit `type="String"`, then no trimming is done at all.
Otherwise, we have to handle the case of `[white space]<SomeElement(s)/>[white space]`, where the element might be a complex nested object.

**Comment by joakime** [comment]
Sure, but even with nested elements you still trim whitespace around it ...

Example ...
``` xml
<Set name="foo">
 <Property name="price"/>-
 <Property name="age"/>
</Set>
```

That should result in a String on `foo` that is `"[price]-\n [age]"`, not `"\n [price]-\n [age]\n"`, agreed?

**Comment by gregw** [comment]
@joakime No I don't agree.  If you are after a String then it has to be literally what is there because you may want to have the leading white space etc.  So in your example if you don't want the leading/trailing ws you would have to do:
```xml
<Set name="foo" type="String"><Property name="price"/>-
 <Property name="age"/></Set>
```

Ugly, but it is a consequence of XMLs ability to make text between elements significant

So I don't see this as a different issue to #3805
