### ISSUE TITLE
PropertyFileLoginModule adds user principle as a role

### ISSUE THREAD

**Issue by sjrd218** [eclipse/jetty.project#3815]
https://github.com/eclipse/jetty.project/blob/7b941098d02a7d305a38a02ddf447eaa8f19070a/jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/PropertyFileLoginModule.java#L119-L126

When PropertyFileLoginModule adds the principles to the role list it does not discriminate between the user principle and the role principles. This causes the user to be added to the list of roles which is not desirable. 

The expected behavior is for only role type principles to be added to the role list without also adding the user principle.

**Comment by janbartel** [comment]
Fixed in 9.4.20 and above.
