### ISSUE TITLE
Jetty blocks ciphers starting with SSL_ and due to which none of the IBM java supported ciphers are allowed

### ISSUE THREAD

**Issue by nainap** [eclipse/jetty.project#3817]
We are using Jetty as embedded server and we want to use IBM Java 8 instead of Oracle Java 8 to start Jetty server as AIX platform only supports IBM Java.

Whenever we try to start Jetty sever with IBM Java, it shows "No supported cipher suites <from_the_list_of_ciphers>". When we contacted IBM team for this, they informed us that all the IBM cipher suites starts with SSL_ (even TLS 1.2 supported ciphers) but Jetty blocks SSL_ ciphers by default, as it is considered as weak ciphers.

Kindly let me know how we can support IBM Java 8 with Jetty 9.4.18. Is there any workaround available?

As it works fine on other windows and unix based platforms using Oracle Java 8, we need your help to get it work with IBM Java 8 also, so that AIX platform can be supported with our product.

**Comment by gregw** [comment]
Currently our understanding of best practises for SSL ciphers results in us blocking the following ciphers by default:
```java
    private static final String[] DEFAULT_EXCLUDED_CIPHER_SUITES = {
        // Exclude weak / insecure ciphers
        "^.*_(MD5|SHA|SHA1)$",
        // Exclude ciphers that don't support forward secrecy
        "^TLS_RSA_.*$",
        // The following exclusions are present to cleanup known bad cipher
        // suites that may be accidentally included via include patterns.
        // The default enabled cipher list in Java will not include these
        // (but they are available in the supported list).
        "^SSL_.*$",
        "^.*_NULL_.*$",
        "^.*_anon_.*$"
    };
```

However you are free to replace this by calling `SslContextFactory.setExcludeCipherSuites(String... cipherSuites)` with your own exclusions.

Please reopen if this does not resolve your problem.

**Comment by joakime** [comment]
This is also a duplicate of #2921
