### ISSUE TITLE
Support Request auto decompress in GzipHandler

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#382]
The GzipHandler should support async i/o behavior for Request body content that might be compressed.

The Request body should be decompressed in-line for components that are using Async I/O to read the request body content.

**Comment by crafty78** [comment]
Wondered what the status of this issue was and why it isn't resolved? I can see the code was merged but the inflateBufferSize option needs to be set to activate it and is not documented. Is it just the docs that need updating, happy to create a pull request or is the code not ready for real use?

**Comment by joakime** [comment]
@crafty78 the initial implementation has been completed by @gregw.

The only testing done with this change (the newly introduced `GzipContentDecoder`) is the unit testing performed in the [`GzipContentDecoderTest`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java) and [`GzipHandlerTest`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java).  

We have no feedback yet on if this is a general real-world implementation that works for them.

Care to give it a go with your use case?

**Comment by crafty78** [comment]
OK will give it a go over next couple of weeks and feedback.

**Comment by joakime** [comment]
Implemented and merged into `jetty-9.4.x` via PR #964
Available starting in release `jetty-9.4.0.v20161208`
