### ISSUE TITLE
Jetty annotations: scanned from multiple locations

### ISSUE THREAD

**Issue by mironbalcerzak** [eclipse/jetty.project#3833]
Greetings,
I've noticed that jetty-annotations module is logging an (incorrect) warning.
It may cause a significant delay while starting a jetty server (from jetty-maven-plugin) due to printing to console.

Here's a tiny excerpt from console log:

```
[WARNING] javax.servlet.http.HttpSessionListener scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/HttpSessionListener.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/HttpSessionListener.class
[WARNING] javax.servlet.http.HttpUpgradeHandler scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/HttpUpgradeHandler.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/HttpUpgradeHandler.class
[WARNING] javax.servlet.http.HttpUtils scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/HttpUtils.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/HttpUtils.class
[WARNING] javax.servlet.http.NoBodyOutputStream scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/NoBodyOutputStream.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/NoBodyOutputStream.class
[WARNING] javax.servlet.http.NoBodyResponse scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/NoBodyResponse.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/NoBodyResponse.class
[WARNING] javax.servlet.http.Part scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/Part.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/Part.class
[WARNING] javax.servlet.http.WebConnection scanned from multiple locations: jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/WebConnection.class, jar:file://(m2-repo)/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar!/javax/servlet/http/WebConnection.class
```

Have a good day.

Kind regards,
-- mb

**Comment by janbartel** [comment]
@mironbalcerzak  can you please attach an example pom.xml that produces this output?

**Comment by mironbalcerzak** [comment]
Howdy,
Please take a look at
https://github.com/mironbalcerzak/gist-jetty-maven-plugin-w-overlay.git

Kind regards,
- mb

**Comment by janbartel** [comment]
Thanks @mironbalcerzak.  FYI the "run" goal isn't designed to be bound to an execution phase, as it kicks off a parallel build cycle. The "start" and "stop" goals are the correct ones to use.

**Comment by mironbalcerzak** [comment]
```
mvn deploy -PmoduleA
```
is good enough to see that behaviour.

( thank you for advice =) )

**Comment by janbartel** [comment]
@mironbalcerzak the javax.servlet-api jar should be marked as scope provided in the module-a-war pom.

**Comment by mironbalcerzak** [comment]
@janbartel That is very true :) however, in "enterprise" grade products, it'll be very difficult (close to impossible I'd say?) to analyze dependency graph from that perspective. One would expect to "just start" jetty - since both pom.xml files are perfectly valid. Jetty is starting, indeed - but overhead due to console printing can be massive..

Should this scenario be handled in jetty-maven-plugin then?

**Comment by janbartel** [comment]
It has always been a part of the servlet specification that the container provides the servlet api, never the webapp. This is exactly the sort of thing that maven &lt;scope&gt;provided&lt;/scope&gt; is intended for, so I believe the correct solution is to use this scope on your webapp.

 It also has the added benefit that you won't have the javax.servlet-api jar put inside your webapp - it's never a good idea to have it in there.

Any code that seeks to knock out the servlet api jar from scanning would be inherently fragile, as it would have to be based on the name of the jar, which of course may have many permutations.

**Comment by mironbalcerzak** [comment]
makes sense - thanks you for your time :)

PS.I was not thinking of skipping "by name" as indeed it would be fragile (and extremely terrible) - but, I think things are good as they are after all :)

**Comment by robozb** [comment]
Thanks @Janbartel, It helps me at another project :)
