### ISSUE TITLE
org.eclipse.jetty.client.api.Request should support an onResponseTrailers listener

### ISSUE THREAD

**Issue by shamsimam** [eclipse/jetty.project#3843]
For completeness with handling http/2 requests, `org.eclipse.jetty.client.api.Request` should support the following method: `Request onResponseTrailers(Response.TrailersListener listener);`

This allows simplified handling on request bodies and trailers without requiring the user to ensure that all body has been read before trying to access the trailers.

**Comment by sbordet** [comment]
See also #1442.

**Comment by shamsimam** [comment]
Closing as it duplicates #1442.
