### ISSUE TITLE
Embedded Jetty v9.4.17, sometimes doesn't invoke deployed Servlet

### ISSUE THREAD

**Issue by mprashpat** [eclipse/jetty.project#3851]
Java Version
--------------------------
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Jetty Version
--------------
9.4.17

We embedded Jetty in our application.
We wish to invoke a Servlet (WebService) on receiving HTTP Post. Sometimes, Jetty Server receives request and doesn't invokes appropriate Servlet while
thread seems to be running (as it appears in jstack).

There is no particular pattern to achieve this scenario. 
However this issue occurs only when Jetty Server is idle for some time.

In error scenario we observe following:

1. HTTP Post request is reaching the server. Verified using tcp dump.
   HTTP POST was around 8 KB in size.

2. Jetty Sever received the request as verified enabling logs, startup logs attached.
   
3. In error scenario, however selector thread goes in Running state nothing is processed.(Jstack before and after instant (2019-07-04 10:00:52.767) attached)
   
    A. Before instant (2019-07-04 10:00:52.767) qtp2008106788-120-acceptor-0 was in BLOCKED scenario.(Thread dump before_jstack.txt)
    B. At instant (2019-07-04 10:00:52.767) second HTTP POST was received    
    C. Thread qtp2008106788-121-acceptor-1 handled the request.
    D. qtp2008106788-121-acceptor-1 is running while qtp2008106788-120-acceptor-0 is blocked.(Thread dump after_jstack.txt))

I am also attaching the tap, thread dump and logs for successful case just for reference.

Please guide us to resolve above scenario.
[failure_scenario.zip](https://github.com/eclipse/jetty.project/files/3358747/failure_scenario.zip)
[success_scenario.zip](https://github.com/eclipse/jetty.project/files/3358752/success_scenario.zip)

**Comment by gregw** [comment]
I think you are suffering from #3550!  This is fixed in 9.4.18 (but 9.4.19 is out now as well).
I'll close for now, please reopen if upgrade does not fix the problem.
