### ISSUE TITLE
Jetty could not running on MacOS Catalina(10.15)

### ISSUE THREAD

**Issue by KyongSik-Yoon** [eclipse/jetty.project#3860]
Jetty not working on Mac OS Catalina Beta.
I found the reason that latest Mac OS version has different mount path of main partition with before version and It seems to keep.
So I prepare additional alias checker on #3855 
After adopting this one Jetty startup successfully.

**Comment by KyongSik-Yoon** [comment]
continuous-integration/jenkins/pr-merge processing always failed.
I checked other PR but all of CI result failed. What's happened?

**Comment by joakime** [comment]
Seeing as Mac OS Catalina is still beta, this issue will have to wait until it's officially released.

**Comment by KyongSik-Yoon** [comment]
I agree.

**Comment by Maj0rT** [comment]
Thanks for your patch, it's working for me.
I was already pretty frustrated :-).

**Comment by olamy** [comment]
close per comment #3855
