### ISSUE TITLE
unable to create new native thread

### ISSUE THREAD

**Issue by itsgauravsaxena** [eclipse/jetty.project#3861]
I know this is very generic error but for some reason all our jetty servers running springboot applications are crashing with this error. We have increased **nproc** and **ulimit** commands confirms the change. Is it some known issue and if so, is there some known workaround from jetty point of view?
We are using embedded jetty in springboot 2.0.3.Release.

```
[o.e.j.util.thread.QueuedThreadPool] - 
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:48)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:725)
```

**Comment by sbordet** [comment]
You probably have a too small heap configured for your JVM.

**Comment by itsgauravsaxena** [comment]
Most of our micro services are running with 1gb or 1.5 go as Xmx. But sure I will try to add more and see if it improves the situation. Thanks for your comment

**Comment by sbordet** [comment]
A heap of 1 GiB or more should be large enough, unless subject to a heavy load.
More probably you have another problem.
First thing you want to do is to take a server dump as described [here](https://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html).

**Comment by itsgauravsaxena** [comment]
Thanks for your reply. I can enable dump but if we have 50 microservices, whould we enable on all because we dont know which one crashes - the behaviour is bit random .

**Comment by sbordet** [comment]
@itsgauravsaxena we need more information.
Your last comment shows a `QueuedThreadPool` with only 12 active threads out of 200, so it's unlikely that the JVM failed to allocate a new one.

**Comment by itsgauravsaxena** [comment]
The actual issue was ulimit wasn't set correctly. It required us to set both hard and soft limit but that solved the issue for good. Thanks for your response 👍

**Comment by richardtan** [comment]
@itsgauravsaxena We seem to have the same problem as well
Do you remember what ulimit did you change on your box?

**Comment by joakime** [comment]
@richardtan I think it's the `-u` ulimit value (max user processes)

Mines ...

```
$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 514797
max locked memory           (kbytes, -l) 16483840
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 514797
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Comment by itsgauravsaxena** [comment]
@richardtan Sorry but I am not sure if I remember it correct. But vaguely remember that hard limit(ulimit -Hn) was like some large number. But we did set soft limit to 4k(ulimit -Sn)
