### ISSUE TITLE
Enforce use of SNI

### ISSUE THREAD

**Issue by silviobierman** [eclipse/jetty.project#3863]
I would like Jetty to reject HTTPS requests for which it can not select a matching certificate from the SNI provided host-name (or which lack SNI info in the first place). Currently it delegates the request to the normal key-manager which results in the first certificate in the key-store being served. This
- serves a certificate that usually does not match the request
- exposes that certificate to all clients that do not provide SNI info which is undesirable in multi-tenant configurations

A setting to disable the forward would solve this nicely.

**Comment by silviobierman** [comment]
Thank you Simone. I will look into that tomorrow. Out on a short trip now.Cheers.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Simone Bordet <notifications@github.com> Date: 9/13/19  08:23  (GMT+01:00) To: "eclipse/jetty.project" <jetty.project@noreply.github.com> Cc: silviobierman <sbierman@jambo-software.com>, Mention <mention@noreply.github.com> Subject: Re: [eclipse/jetty.project] Enforce use of SNI (#3863) @silviobierman the methods are on Server because they don't make sense on Client.
If you are using embedded Jetty, you should be moving to use Server rather than the base class - will be a smoother migration when you move to Jetty 10.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eclipse/jetty.project/issues/3863?email_source=notifications\u0026email_token=AAFTLLPJ6UA6GLIA5HVTAU3QJMWUJA5CNFSM4H7NADA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6UCSAI#issuecomment-531114241",
"url": "https://github.com/eclipse/jetty.project/issues/3863?email_source=notifications\u0026email_token=AAFTLLPJ6UA6GLIA5HVTAU3QJMWUJA5CNFSM4H7NADA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6UCSAI#issuecomment-531114241",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by silviobierman** [comment]
I replaced SslContextFactory with SslContextFactory.Server and tested 
the no-SNI scenario after calling setRejectUnmatchedSNIHost(true). It 
works perfectly. No certificate is sent and the handshake fails.

Thank you very much! This is exactly what I need. I can not wait for the 
release that contains this.

Kind regards,

Silvio

**Comment by sbordet** [comment]
@silviobierman, thank you for confirming the behavior.

However, the issue a bit more nuanced - what may be a good behavior for you may not work for others.
We will need some more time to discuss whether this is the right solution so it may take a little longer to come up in a release.

**Comment by silviobierman** [comment]
Ok, that sounds fair. Even being optional I can imagine you might want 
to refine this or make it a more general facility. One alternative 
handling of SNI absence could be sending a designated default 
certificate. That would allow supporting non-SNI clients for some 
primary host while allowing SNI to address additional hosts. Other 
sensible definitions of behavior are conceivable.

I will keep my fingers crossed an wait what happens.

Cheers,

Silvio
