### ISSUE TITLE
Review exposure of JavaxWebSocketServletContainerInitializer

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3872]
Following #3661, the Jetty WebSocket classes have been moved to proper packages so that they can be hidden from web apps and properly exposed via JPMS to embedded users.

The same should be done for Javax WebSocket classes.

**Comment by gregw** [comment]
@lachlan-roberts So I'm thinking that there should be no `org.eclipse.jetty.websocket.javax.server`, everything should either be an implementation of the standard API and thus in `org.eclipse.jetty.websocket.javax.server.internal` or something used to init/configure the implementation and thus in `org.eclipse.jetty.websocket.javax.server.config`.   There should be no Jetty API classes exposed to the webapp for javax ?
