### ISSUE TITLE
WebSocketPartialListener is only called for initial frames, not for continuation frames

### ISSUE THREAD

**Issue by magnus-gustafsson** [eclipse/jetty.project#3876]
In jetty-9.4.x `WebSocketPartialListener` is only called for first TEXT / BINARY frame, not for the following continuation frames.

`JettyListenerEventDriver` should override `onContinuationFrame` from `AbstractEventDriver` so that it can both check if listener is of type  `WebSocketListener` (and if so aggregate message) and if its of type `WebSocketPartialListener` delegate to its methods.
This change would make it possible to use  `WebSocketPartialListener` and get both the initial start BINARY/TEXT frame as well as all CONTINUATION frames.

Right now `AbstractEventDriver` also enforces that the listener is of type  `WebSocketListener` in its `onContinuationFrame` method (since if the listener is any other type, the `activeMessage` field will be null, and it will throw an exception).
This change would fix this as well.

**Comment by joakime** [comment]
Your assessment of the situation is correct.
This is a regression in the WebSocketPartialListener support, and I consider this a bug.
I'm shocked there's no test cases for WebSocketPartialListener present in the codebase.
Could have sworn there were back when WebSocketPartialListener was created.

**Comment by joakime** [comment]
Opened PR #3879 to add testcases and a proper fix.

**Comment by joakime** [comment]
PR #3879 merged into `jetty-9.4.x`
