### ISSUE TITLE
JSR annotations in REST ignored

### ISSUE THREAD

**Issue by PushpaMH** [eclipse/jetty.project#3882]
The JSR annotations like @NotNull, @Min, @Max are ignored in rest API's used in jetty server. Where as the same thing works in WAS.

```
   import javax.validation.constraints.NotNull;

  @Path("/{target}/algorithms")
  @GET
  @Produces(MediaType.APPLICATION_JSON)
   public Response getAlgorithms(@Context SecurityContext securityContext, @Context 
   HttpHeaders headers,
   @QueryParam("offset") **@NotNull** String offset
```
Even if i pass null value for offset, it goes through instead throwing back error. 

Java version used 1.8. 
Jetty version : <jetty.version>9.4.7.v20170914</jetty.version>

where as hybernate bean validation works.
![image](https://user-images.githubusercontent.com/26792379/61369603-15800c80-a8ae-11e9-9537-5c5eb5573e56.png)

**Comment by joakime** [comment]
The annotations found in `javax.validation` (such as @Min, @Max, @NotNull) are used by your REST library (not Jetty) for validation.
Those concepts do not exist in the `javax.servlet` space, where Jetty lives.

**Comment by PushpaMH** [comment]
The same code works with Websphere liberty profile(WLP) and only with Jetty it is not working.

Is there any particular configuration or settings to have this support in jetty? 

Or are there any alternatives for @NotNull, @Min, @Max etc alternatives in Jetty??

**Comment by janbartel** [comment]
Jetty does not provide a javax.validation implementation, you need to supply that yourself, so you should use something like hibernate validation.

**Comment by PushpaMH** [comment]
Yes, i'm importing ( import javax.validation.constraints.NotNull; ) 
And trying to use them. On the bean object it works. But on REST API's it doesn't. And when i change the app server from Jetty to WLP, it all works. So i doubt on the app server configurations if i'm missing anything.

**Comment by joakime** [comment]
Bean Validation 1.1 is a feature of the library you are using. (hibernate, jpa, ejb, rest, cdi, etc...)  
Bean Validation is not a feature that Servlet containers implement. (which is what Jetty and other containers are)

Your REST library, for example, would need to have that javax.validation support.
Note: not all REST libraries support javax.validation.

You might also be able to just use Hibernate Validator (https://hibernate.org/validator/) in your webapp and get the javax.validator support you are looking for.

**Comment by PushpaMH** [comment]
@joakime : We are using javax.ws.rs library for REST. But what i couldn't understand is with the same rest library how is it working for WLP.  I see that Jetty also has J2EE container support as per : https://www.eclipse.org/jetty/documentation/current/jetty-javaee.html

Jetty Version we are using :  9.4.7.v20170914

We can't use hibernate validator for certain reasons. Is there any other options to achieve this with Jetty? 
I'm even fine with any online webex / other calls. This is very critical for us. Please let me know. 

Thanks,

**Comment by janbartel** [comment]
It could be working in weblogic because they supply an implementation of javax.validation - you'd have to check their documentation to verify that. As discussed, this is something you need to plug into jetty, selecting an implementation that is appropriate for your environment.
