### ISSUE TITLE
Client: support embedding threadlocal data (e.g. distributed tracing data) into the request 

### ISSUE THREAD

**Issue by marshallpierce** [eclipse/jetty.project#3883]
My goal is to make it easy for services to set data like a call id, etc, in a threadlocal and then propagate it on to calls to other services to allow matching log lines across services by call id, etc. I'm tinkering with accessing data in a threadlocal and stuffing whatever's in there in a request header. I've sketched out https://bitbucket.org/marshallpierce/async-http-client-threadlocal-header-filter/src/master/ and https://bitbucket.org/marshallpierce/okhttp-threadlocal-header-interceptor/src/master/ for those http clients, and I'd like to do the same for Jetty's. However, there isn't an obvious way to do that since `onBegin` is called from a different thread than the thread that initiated the request.

Chatting with @sbordet, it seems like one potential way would be to have a concept of "request attribute suppliers" that could be invoked (on the original thread) to populate the request attributes, and then the request listener's `onBegin` would simply copy the attribute, if present, to the headers. Of course, there are probably plenty of other  approaches, too...

**Comment by joakime** [comment]
Are you asking that the server side handling of a request support thread local behaviors on a Servlet 3.0+ container?
Or are you asking that the client side handling of a request support thread local behaviors?

**Comment by marshallpierce** [comment]
The latter -- just the ability to decorate a request with headers based on threadlocals present in the original thread that kicked off the request.

**Comment by joakime** [comment]
Considering that Jetty's HttpClient is 100% async and a single exchange can handled over 1..n threads this sounds infeasible.

**Comment by sbordet** [comment]
It's not doable with thread local, but doable with request attributes. I'll have a look. @marshallpierce want to contribute a PR?

**Comment by marshallpierce** [comment]
Certainly, happy to!

**Comment by sbordet** [comment]
@marshallpierce I think there is a way to do this already.

```java
String correlationName = "X-Correlation-Data";
String correlationData = "123456";
ThreadLocal<String> correlation = new ThreadLocal<>();

// Setup the client 
HttpClient client = new HttpClient();
client.start();
client.getRequestListeners().add(new Request.Listener.Adapter()
{
    @Override
    public void onQueued(Request request)
    {
        request.header(correlationName, correlation.get());
    }
});

// Somewhere else...
correlation.set(correlationData);

// In the same thread, create and send a request
// having the correlation automagically added.
ContentResponse response = client.newRequest("localhost", connector.getLocalPort()).send();
```

This works because `onQueued()` is guaranteed to be called by the thread that sends the request.
Would this cover your use case?

**Comment by marshallpierce** [comment]
Sorry for going dark on this; went directly from jcrete to more traveling -- yes, I think that will work fine! I had implemented (but didn't get around to pushing) something like what we outlined above where there was a `Supplier` called when requests were created, but if `onQueued` is called from the originating thread, that will work perfectly. Thanks!
