### ISSUE TITLE
JDBCSessionDataStore does not support SQLite

### ISSUE THREAD

**Issue by mpe85** [eclipse/jetty.project#3890]
The SQLite JDBC driver does not implement `JDBC4ResultSet.getBlob(String)` which is used by `DatabaseAdaptor.getBlobInputStream(ResultSet, String)`. Hence Jetty fails with an `SQLFeatureNotSupportedException` when it tries to read the session attributes map back from the database.
When reading binary data from SQLite you should use `resultSet.getBytes(String)` instead.

See 
https://stackoverflow.com/questions/31759603/error-java-sql-sqlexception-not-implemented-by-sqlite-jdbc-driver-when-retrievi

A solution could be something like this (inside `DatabaseAdaptor.getBlobInputStream(ResultSet, String`):

```
try {
  Blob blob = result.getBlob(columnName);
  return blob.getBinaryStream();
} catch (SQLFeatureNotSupportedException ex) {
  byte[] bytes = result.getBytes(columnName);
  return new ByteArrayInputStream(bytes);
}
```

**Comment by janbartel** [comment]
Would you like to contribute a pull request?

**Comment by mpe85** [comment]
Yes, of course. Please expect it in the next few days.

**Comment by mpe85** [comment]
There you are.

**Comment by janbartel** [comment]
Thanks @mpe85, I've committed that for jetty-9.4.20 and beyond.
