### ISSUE TITLE
java.lang.NullPointerException: Deflater has been closed

### ISSUE THREAD

**Issue by ekapinos** [eclipse/jetty.project#3892]
Found two different outcomes for same issue, probably in websocket-common lib in org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension. 

See log [log1.txt](https://github.com/eclipse/jetty.project/files/3411899/log1.txt) 

Can be reproduced with HTTP header "Sec-WebSocket-Extensions: permessage-deflate". I use STOMP to run it.

1.  Set breakpoint 
  - For iIssue "java.lang.NullPointerException: Deflater has been closed" on java.util.zip.Deflater.deflate(byte[], int, int , int) method
  - For issue "java.io.EOFException: Connection has been closed locally" on java.util.zip.Deflater.ensureOpen() method
2. Open in new browser tab page which uses web sockets
3. Breakpoint should be triggered.
4. Close browser tab
5. Release Breakpoint
6. Voila 

It looks it is happen because method ExtensionStack.outgoingFrame(Frame , WriteCallback , BatchMode) can be triggered in parallel with ExtensionStack(inherited from AbstractLifeCycle).stop().

Due to race condition attempt to send init web socket message may occur after closing web socket connection  

Tested on 9.3.27.v20190418.jar. Looks not fixed on latest 9.4.19.v20190610.

**Comment by lachlan-roberts** [comment]
@ekapinos there has been some changes to the way Deflaters are used in websockets since 9.4.19 done in #3771

Can you test if you have the same problem with the current 9.4.x branch because i suspect this might have fixed this issue.

**Comment by lachlan-roberts** [comment]
In PR #4108 it was changed so that frames will be failed before the `ExtensionStack` if the websocket has been closed. So you should not see any errors like this from the Deflater anymore.

**Comment by ekapinos** [comment]
Hi guys. Thanks for update. Sorry for delay. I'll do my best to test it on my environment. I'm not an owner, so it may take time or never happen. Anyway, if is will happen, I'm going to give you feedback.

**Comment by xujl930** [comment]
wonderful, solved my problem of too many tcp CLOSE_WAIT in zeppelin server backend
