### ISSUE TITLE
Jetty 10 new documentation

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3897]
Jetty 10 documentation should be composed of just 2 books: standalone and embedded.

The former is for users that use Jetty standalone and should contains the Jetty "home" and Jetty "base" concepts, Jetty modules, etc.

The latter is for users that use Jetty embedded and should be similar to the CometD, Spring, etc. (i.e. project that provide libraries to use) documentation, describing concepts, design, APIs, etc.

**Comment by jmcc0nn3ll** [comment]
Yes, an Administration Guide (standalone) and a Developer's Guide (embedded).

**Comment by sbordet** [comment]
@lorban this is the Jetty 10 new documentation issue.
Any suggestion please add a comment here.

**Comment by WalkerWatch** [comment]
The work to separate these has already been done. Work is ongoing to migrate old docs. I think this particular issue can be closed.
