### ISSUE TITLE
HttpConfiguration.setSendDateHeader() missing Javadoc

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#3900]
version 9.4.15.v20190215

Please add Javadoc to `HttpConfiguration.setSendDateHeader()` and `getSendDateHeader()`. Thank you.

**Comment by sbordet** [comment]
@cowwoc would you like to contribute a PR?

**Comment by cowwoc** [comment]
@sbordet Sure. I need your help with the eca check on https://github.com/eclipse/jetty.project/pull/3915 though. Thank you in advance.

**Comment by joakime** [comment]
PR #3915 is merged.
