### ISSUE TITLE
Is StatisticsHandler production ready?

### ISSUE THREAD

**Issue by trance1st** [eclipse/jetty.project#3921]
Hi all,

I want to have graceful shutdown for my app and in order to achieve this I need to configure the stats module.
My question is if StatisticsHandler is production ready? Do you guys see any problems enabling the stats module in production in terms of the overhead added to request processing?
Let's say that the app must handle a very large number of requests.

**Comment by sbordet** [comment]
> My question is if StatisticsHandler is production ready?

Depends on what you exactly mean by "production ready". We have many people using it in production.

> Do you guys see any problems enabling the stats module in production in terms of the overhead added to request processing?

There is a little overhead, but in all cases I've seen it was entirely negligible if even noticeable at all.

**Comment by joakime** [comment]
@trance1st once you have a satisfactory answer, please close this issue.
