### ISSUE TITLE
Jetty maven plugin does not load Service Loaders in application class path

### ISSUE THREAD

**Issue by kannanekanath** [eclipse/jetty.project#3922]
Asked at https://stackoverflow.com/questions/57292717/jetty-maven-plugin-does-not-load-service-loaders-in-application-class-path and was suggested to file a bug/issue.

Jetty and jetty-maven-plugin: 9.4.19.v20190610

I am using a HashLoginService and I want the username and password to be encrypted with "scrypt" algo. The box standard Jetty only provides plain, crypt and md5 encryption as seen in [HashLoginService ](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-security/src/main/java/org/eclipse/jetty/security/HashLoginService.java)and most importantly [Credential](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/security/Credential.java#L66)

This [enhancement ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485625)was added in Jetty 9.4 where by the Credential class would consult the standard JVM ServiceLoader mechanism to load additional CredentialProvider class.

In my project I have a dependency like this which contains the credential provider implementation. It also has the correct manifest entry with the interface/implementation

```
<dependency>
   <groupId>com.mygroup</groupId>
   <artifactId>myartifact-contains-credential-provider</artifactId>
   <version>0.3-SNAPSHOT</version>
</dependency>
```
I can verify this by simply doing `ServiceLoader.load(CredentialProvider.class)` in my test class which has the dependency in the classpath to make sure that my provider is present.

When I run this via the jetty-maven-plugin this provider is NOT available. I confirmed this by adding a breakpoint in the Credential class in jetty-util library. 

My guess is that when running via the jetty plugin the jetty loads these extensions using the system/server classpath and my dependencies/libraries are only present in the application classpath. Can someone tell me how I can achieve this?

**Comment by janbartel** [comment]
Sounds like the credential provider needs to be on the equivalent of the container classpath, therefore your dependency should be added to the plugin, not your webapp.

**Comment by janbartel** [comment]
@kannanekanath I believe I've answered your question, so I'm closing this issue. Please reopen, with further information, if you feel there is an error in jetty.
