### ISSUE TITLE
Refactor MultiPartFormInputStream to allow jetty-client to use a subset of it for parsing `multipart/byterange` responses

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3926]
Currently, the existing `MultiPartFormInputStream` is good for forms, but there should probably be a refactor to this class take out the basics for multipart parsing so that a new class for jetty-client could be used to parse `multipart/byterange` responses too.

**Comment by lachlan-roberts** [comment]
we currently have the  `MultiPartParser` class which separates the multipart parsing from  `MultiPartFormInputStream`

**Comment by sbordet** [comment]
@lachlan-roberts is this still to do?

**Comment by joakime** [comment]
@sbordet aren't you working on this for jetty 12?

**Comment by sbordet** [comment]
Fixed in 12.
