### ISSUE TITLE
Race condition when modifying session + sendRedirect()

### ISSUE THREAD

**Issue by blop** [eclipse/jetty.project#3936]
Hello,

We are using the NullSessionCacheFactory with a HazelcastSessionDataStoreFactory.
We also rely on Spring Security for Authentication & Authorization.

There is a race condition occurring when the user tries to login where it's security context, stored as a session attribute (see org.springframework.security.web.context.HttpSessionSecurityContextRepository), is not fully written in hazelcast but the browser tries to load the next page already (after being redirect by org.springframework.security.web.authentication.SimpleUrlAuthenticationSuccessHandler).

The thing is, the redirect calls org.eclipse.jetty.server.Response#sendRedirect(int, java.lang.String), which already commit the answer (sending headers and closing the output). 

And this is happening *before* getting out of the org.eclipse.jetty.server.session.SessionHandler#doScope, which then ensureCompletion() and complete() the session, actually writing it to the SessionCache.

It seems the browsers then tries to load the redirect target, using it's newly set cookie and asking to use the new session. But all it finds is the previous version of the SessionData.

Using the DefaultSessionCache seems to help a bit (reducing the delay after which the session is retrievable with the new attributes), but the value is still updated after.
Also DefaultSessionCache can induce other issues when using a non-sticky load balancers.

Any though about this ?
I'd be nice to delay the redirect until the session is stored ;)

Thank you!

Olivier

**Comment by olamy** [comment]
I wonder if you have any sample project we could use to reproduce your issue?

**Comment by blop** [comment]
I will try to create one as soon as possible ;-)

**Comment by janbartel** [comment]
@blop you want to look at using the saveOnCreate option on the sessioncache (NullSessionCache for you).  That option will immediately write through a newly created session to the backing store (Hazelcast for you). This option is specifically designed for situations where it's likely a response with the session id might have been committed back to the client and a new request referencing it arrive before the current request has finished.  See https://www.eclipse.org/jetty/documentation/9.4.19.v20190610/sessions-details.html#_sessioncache and also https://www.eclipse.org/jetty/documentation/9.4.19.v20190610/session-configuration-sessioncache.html

**Comment by blop** [comment]
@janbartel Yes, I saw that option and looked into it.
It's actually already enabled, but it doesn't help.

org.eclipse.jetty.server.session.AbstractSessionCache#newSession(javax.servlet.http.HttpServletRequest, java.lang.String, long, long) is indeed checking its value when the session is created, and it does save a first version of the session in the datastore.

But the Spring Security needs to store information as session attributes.
It seems there is no way to do that atomically, it first call javax.servlet.http.HttpServletRequest#getSession(boolean) which calls org.eclipse.jetty.server.session.SessionHandler#newHttpSession which calls org.eclipse.jetty.server.session.SessionCache#newSession(javax.servlet.http.HttpServletRequest, java.lang.String, long, long) which stores the session *without* attributes (when saveOnCreate is enabled).
Then it uses javax.servlet.http.HttpSession#setAttribute, implemented by org.eclipse.jetty.server.session.Session#setAttribute which calls org.eclipse.jetty.server.session.SessionData#setAttribute.

The new session is thus modified right after its creation.
Only the first incomplete version is stored.
Then the complete version with attributes is stored again when getting out of org.eclipse.jetty.server.session.SessionHandler#doScope. 
But this is too late when we send a redirection, the browser is already querying the target :/

**Comment by janbartel** [comment]
Sounds like you shouldn't be using the NullSessionCache then. Mostly the DefaultSessionCache is the right option, with very few exceptions.

**Comment by blop** [comment]
I fail to see how the DefaultSessionCache is preventing the issue. Is it because you share the same object in memory? Because the session is not stored in the cache before the response is committed to the client.

Also, the DefaultSessionCache is not helping when loadbalancing requests to multiple nodes. (And using more memory).

Is there a way to configure jetty so that the session is stored in the cache/datastore right before the response is committed if the session is new ? Or a way to register such custom handling. I want to avoid sub-classing all your code :)

**Comment by joakime** [comment]
> Also, the DefaultSessionCache is not helping when loadbalancing requests to multiple nodes. (And using more memory).

You have Session stickiness enabled on your load balancer, right?
If so, the `DefaultSessionCache` is the way to go.

**Comment by janbartel** [comment]
@blop the whole point of the DefaultSessionCache is to ensure that all simultaneous requests share the same session object.  The ideal setup is to have a sticky load balancer to ensure that all requests all go to the same node that has in-use sessions in memory.  The only time you should really use a non-sticky load balancer is if you have absolutely stateless code, but because you're using sessions you're not stateless.  Unfortunately the servlet spec sessions are really not up to the job, because they have no guarantees of transactionality, atomicity, nor any definitions of how multiple simultaneous requests are even handled. Ideally, for security, you'd use some mechanism other than sessions that provides all those features. However, if you're using sessions, the best you can do is sticky load balancer+DefaultSessionCache.

**Comment by blop** [comment]
Thank you all for your help.

I know stateful sessions are not great, we are already shifting towards JWT Tokens but I cannot get rid of the session feature just yet.
I also know that DefaultSessionCache + Sticky load balancing helps with this.

I just wanted to point out that there is still room for improvement, and that in the same spirit of the saveOnCreate option, we could have the possibility to trade speed for consistency in this case.

**Comment by joakime** [comment]
There's really only 2 places to address this enhancement.

1. The Servlet spec itself, as it needs a serious overhaul to address clustered Session behavior.

   If you want to pursue this, then start by filing an issue at https://github.com/eclipse-ee4j/servlet-api and keep the conversation going.

or

2. The Session data storage layer.  But that's an entire project, as complex as Jetty itself is.

   If you want to pursue this, then look at the various Session Clustering solutions available now.
   Example: https://ignite.apache.org/


Both are out of scope for Jetty.

**Comment by janbartel** [comment]
@blop  I don't think it would be that difficult for you to extend the NullSessionCache to do what you want (always bearing in mind the total lack of session consistency with this approach :) ). I've quickly whipped up some code that you could use as a basis. I've also made a jetty module for you that enables the special WriteThroughNullSessionCache.


[nullwritethroughsessions.zip](https://github.com/eclipse/jetty.project/files/3495001/nullwritethroughsessions.zip)

**Comment by blop** [comment]
Thank you @janbartel.
I tested your solution and it's working great!

Using the WriteThroughNullSessionCache, all the attributes are stored before sending the redirect to the client.
Actually, I don't need perfect consistency, as the session is not modified later on, only read.
I just needed the whole session to be stored when it's created and modified during the login request, which is now the case.

Maybe you can provide the WriteThroughNullSessionCache(Factory) or something similar with the standard distribution?

**Comment by janbartel** [comment]
Thank you for the feedback! @blop , your unflagging enthusiasm for this issue has won me over ;)  I'll look at adding something to the code base for this in time for the 9.4.21 release. I'll leave this issue open until then.

**Comment by janbartel** [comment]
@blop, see PR #3984.  

In particular, see the solution where I prevent passivation listeners causing infinite loops - if your setup uses them you should modify the draft code I gave you appropriately.

**Comment by janbartel** [comment]
@blop  a heads-up that this solution is not going forward for jetty-9.4.21. Instead, I've done a more general-purpose solution that works with both the NullSessionCache, and the DefaultSessionCache and is more robust. Details are here: #4025  and PR here: #4049

**Comment by janbartel** [comment]
The originally proposed solution has been withdrawn in favour of a better solution committed via PR #4049, which has been committed for jetty-9.4.21 and beyond.

**Comment by blop** [comment]
Perfect ;-) Thank you @janbartel !
