### ISSUE TITLE
Improve the getHeader response speed, at least for cases in which the case match.

### ISSUE THREAD

**Issue by LukeButters** [eclipse/jetty.project#3939]
I think it would make sense to speed up getHeader because that shows up as being taking a bunch of time when trying to read all headers, or get headers which don't exist.

Perhaps it possible to use something like a Map in the Request getHeader call so that when the case matches which might happen if I use `Request#getHeaderNames()` it does not need to do a ignore case equals check on up to `n` headers in `org.eclipse.jetty.http.HttpFields.get(String)`.

Of course it would need to fall back to doing a ignore case check, but I think that could also avoid the n checks. We could for example first fill out the `Map` with the current case of the header and as needed add header to the `Map` in lower case form when it is first given a value that does not match the current case of any header. We should could then lowercase the string once.

so I think the code could be something like:
```
// something inits this, the constructor?
ConcurrentHashMap<String, String> headers = mapOfHeadersToValuesInCurrentCaseForm();
public String getHeader(String name)
    {
        MetaData.Request metadata = _metaData;
        String value = headers.get(name);
        if(value != null) return value;
        return headers.computeIfAbsent(name.toLowerCase(), (k) -> metadata.getFields().get(k));
    }
```

Another way to do it could be search to search the map like a **radix** tree, that would also help in the case that a header is not set. Which would be very useful when using with spring which often looks for the `Origin` header multiple times per request however it is often not defined.

**Comment by gregw** [comment]
@LukeButters yu'd think a Map would be a better data structure for fields!   But surprisingly/unfortunately it's not that clear cut a winner when you consider that HttpFields must be:
- case insensitive
- order is important for some headers.
- multi valued.  There can be a difference between a single header with a CSV and multiple single valued headers.

We recently did some JMH bench marks to validate if we really are doing the right thing: #3929 
For lookups <= 15ish the list implementation is best. For lookups >15 <30 using the list is about the same as the best map we could thing of, including Tries (radix trees).

So we think the list is still best.    In our own code we go to lengths to avoid repeated lookups for headers that are probably not there.  Instead we typically do a single iteration and pull out all the headers that are relevant to us and then act on them.  For example see the [FowardedRequestCustomizer](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L377-L391)

So as we have recently reviewed this, I'm going to close this issue for now.   But the JMH benchmark is checked in and if you can think of a better data structure then please have a play and if the numbers indicate that we should reconsider, then please reopen.

**Comment by joakime** [comment]
If you are not opposed to using Jetty specific APIs there is a growing pattern for accessing (potentially many) headers in an efficient way within the Jetty source itself.

It uses the Jetty specific `Request.getHeaders()` method that returns a Jetty `HttpFields` object, which you then iterate through only once.
Gain information about the headers that interest you, a lack of header means it wasn't sent.

Examples:

Request based

https://github.com/eclipse/jetty.project/blob/9950f6b52861601ea5245e5dcba2f905a3642dd5/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L379-L395

https://github.com/eclipse/jetty.project/blob/0a1722d652c984b09d535362ca65201efd2813c6/jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/server/Negotiation.java#L78-L120

https://github.com/eclipse/jetty.project/blob/9950f6b52861601ea5245e5dcba2f905a3642dd5/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java#L488-L512

https://github.com/eclipse/jetty.project/blob/9950f6b52861601ea5245e5dcba2f905a3642dd5/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java#L641-L664

https://github.com/eclipse/jetty.project/blob/9950f6b52861601ea5245e5dcba2f905a3642dd5/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PushCacheFilter.java#L137-L165

Response based

https://github.com/eclipse/jetty.project/blob/e73522255aa154b31a1843ad9a21f875c49d0669/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L1062-L1089

**Comment by LukeButters** [comment]
Thanks for the quick response, jetty dev's are the best. 

If I git clone jetty, can I run a test or something to see the performance so I can tinker with it? What is it that I need to do to run the benchmark on http headers.

Using the HttpFields thing I think is something I could do deep down in the application hopefully I can get to it.
