### ISSUE TITLE
Double initialization of Log

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#3940]
After #3708 (commit 877815e1959963f051a1c425405b0a4360f8a9e7), we now emit _twice_ the message:

```
2019-08-06 11:57:30.460:INFO::main: Logging initialized @219535ms to org.eclipse.jetty.util.log.StdErrLog
```

Class `A` has a static reference to `Log`, so it first initializes the `Log` class.
To initialize the `Log` class, it must runs its `<clinit>` _in source order_.

The first `<clinit>` is a privileged block, that calls `StringUtil.replace()`.
`StringUtil` has a static reference to `Log` which is now under class initialization (so it does not run the class initializers), and eventually `Log.initialized()` is called to print the message the first time.

Then, the `Log` class initialization (started by class `A`) continues with the second `<clinit>` which is:

```java
private static boolean __initialized = false;
```

This resets `__initialized` to `false` (it was set to true by the call to `initialized()` started by class `StringUtil`).

Initialization of class `A` and its `Log` continues and calls `Log.initialized()` which prints the message a second time.

**Comment by sbordet** [comment]
Class `Log` is poorly structured.

Static fields should be before static initializer blocks and this alone would have avoided the issue.

However, static initializers must not use (recursively) any logging since the logging is being initialized, so I think `StringUtil` must not be used inside the `Log` class (or any other class that has a static `Log` field).

**Comment by joakime** [comment]
I had removed Logging from `StringUtil` when issue #3715 was worked (see commit e294527ab4b2be18059271ae54b0b55f839ad982).
Because Logging shouldn't be initialized during Logging initialization.
But on your review, you didn't like that change, so it was reverted.
What I should have done is the reverse, remove `StringUtil` from Logging initialization.
