### ISSUE TITLE
X-Forwarded-Port header customization isn't possible

### ISSUE THREAD

**Issue by harbulot** [eclipse/jetty.project#3969]
When setting up a Jetty 9.4.19 behind an Apache Httpd reverse proxy, the `Host` header says `443` and the request URL's authority part is also just `443` (no host name).

These are the Apache settings:

```
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port 443
```

When debugging the headers (via `request.getHeader(...)`), I have:

```
X-Forwarded-Proto: https
X-Forwarded-Host: www.example.com
X-Forwarded-Port: 443
X-Forwarded-For: x.x.x.x
X-Forwarded-Server: www.example.com
Host: 443
```

`request.getRequestURL()` also gives `https://443/...` (just `443` instead of the actual host).

Could this be due to a typo in [ForwardedRequestCustomizer.java](https://github.com/eclipse/jetty.project/blob/jetty-9.4.19.v20190610/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L246)?

Looking at this, although the method name would suggest it's meant to set the forwarded port, it actually sets the forwarded **host**.

```java
    public void setForwardedPortHeader(String forwardedPortHeader)
    {
        if (_forwardedHostHeader == null || !_forwardedHostHeader.equalsIgnoreCase(forwardedPortHeader))
        {
            _forwardedHostHeader = forwardedPortHeader;
            updateHandles();
        }
    }
```

A workaround is to remove `RequestHeader set X-Forwarded-Port 443` from the Apache configuration altogether (it seems to help in some cases). However, I'm not sure setting the host with the port setter was intended.

**Comment by joakime** [comment]
Is there a reason you are not using [`RFC7239`](https://tools.ietf.org/html/rfc7239) (The `Forward` header standard) on your Apache Httpd? (Jetty supports RFC7239 now)

There is no standard for the `X-Forwarded-*` headers, as a consequence we now have a situation where the various changes by vendors to their meaning is breaking things across the board.

Some history here ...

* Issue #3302 - Azure changes the meaning of the (not a standard) `X-Forwarded-For` header (released in Jetty 9.4.19)
* Issue #3630 - This breaks IPv6 support for `X-Forwarded-For` header (released in Jetty 9.4.19)
* Issue #3782 - Fix for IPv6 breaks the combination of `X-Forwarded-Port` and `X-Forwarded-For` (not released yet, will show up in Jetty 9.4.20)

Those setters are confusing, agreed, but they are trying to satisfy the complicated mess that is conflicting meanings of `X-Forwarded-*` headers.
See existing test cases: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java

That being said, I'll whip up a new testcase of your example to see if the fixes on #3782 addresses your situation, or replicates your issue.

**Comment by joakime** [comment]
Yup, your example is fixed in `jetty-9.4.x` HEAD.
Due to be released in Jetty 9.4.20.

https://github.com/eclipse/jetty.project/blob/4b17d28cb085b2c33ace9d45f401295d2e200f43/jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java#L630-L651

**Comment by joakime** [comment]
Opened PR #3970 for testcase

**Comment by harbulot** [comment]
@joakime Thank you, you're right, I don't actually need `X-Forwarded-Port` at all (and I was copying this from a legacy config, but the standard `Forward` header is indeed the way to go).

That said, what surprises me is that `setForwardedPortHeader` has exactly the same content as `setForwardedHostHeader`: both set `_forwardedHostHeader`. That's at least the case in the latest commit I can see on branch `jetty-9.4.x` (commit d10fea9b7eeee0e37f896f9bf9bb486946f21f8f).
In `ForwardedRequestCustomizer`, only `setForwardedOnly` sets `_forwardedPortHeader`, not `setForwardedPortHeader`. That's what feels like a typo when implementing the setter.

**Comment by joakime** [comment]
PR #3970 - simple unit test is merged.

**Comment by joakime** [comment]
Opened PR #3972 to address header host/port setter issue.
