### ISSUE TITLE
Verify that multipart parsing reads until EOF

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#397]
Multipart content sent by a client may be chunked.

On server-side, applications calls `request.getParts()` to read multipart content.

The multipart parser may be reading until the last multipart boundary and then thinking that it is done (thus returning from `request.getParts()`), while perhaps the client has not sent yet the terminal chunk.

Instead, the multipart parser should read until the last multipart boundary _and_ until EOF before returning from `request.getParts()`.

**Comment by gregw** [comment]
Fixed just the read until EOF aspect.  @sbordet  is also concerned about:
````
 I wanted to know why the server was closing
 and still... the client should have been able to continue working even in half close
````

**Comment by joakime** [comment]
@lachlan-roberts here's an old Multipart issue that you might want to pay attention to as well.

**Comment by gregw** [comment]
@lachlan-roberts this is definitely something that you need to consider.   The new multipart parser now correctly handles an epilogue and will not reach END state until the last content is delivered (EOF in the server setup).    So while using the parser to re-implement the MultiPart InputStream, you need to consider if it will drive the parser all the way to END state or just to the last part?    You may need to add an extra event to the parser handler so you can distinguish between the end of parts and the end of epilogue.

**Comment by lachlan-roberts** [comment]
@gregw @sbordet 
`At the end of MultiPartFormInputStream.parse()` an exception will be latched if the `MultiPartParser` is not in the END state. The END state can only be reached in `MultiPartParser` by fully consuming the last buffer. So I think this issue can be closed.

**Comment by sbordet** [comment]
@lachlan-roberts I'm not sure I understand your last comment.

This issue is about the request content being both chunked (as in `Transfer-Encoding: chunked`) _and_ multipart.

Example:
```
35\r\n
--b\r\n
Content-Type: text/plain\r\n
\r\n
TEXT\r\n
--b--\r\n
0\r\n
\r\n
```

First line is part of `Transfer-Encoding: chunked`, says that 53 bytes follow.
Last 2 lines are the terminal chunk.

The multipart parser should not stop at:
```
--b--\r\n
```
It should instead parse the last boundary _and_ also ask for end of content to the `InputStream`.

**Comment by sbordet** [comment]
@lachlan-roberts thanks for clarifying. Is there already a test case that verifies this behavior ? If not, please write one.

**Comment by lachlan-roberts** [comment]
@sbordet the state of the `MultiPartParser` is checked at the end of `MultiPartFormInputStream.parse()` and an exception is thrown if it is not in the `END` state. The relevant tests in `MultiPartParserTest` will also check if the state is in `END` state after parsing.

**Comment by lachlan-roberts** [comment]
can this be closed @sbordet
