### ISSUE TITLE
Please upload 9.4.20 to maven central

### ISSUE THREAD

**Issue by mpe85** [eclipse/jetty.project#3971]
I'd like to update to 9.4.20 but it's not available on maven central yet. Could you please upload the artifact?

**Comment by sbordet** [comment]
9.4.20 has been staged for internal testing, it's not released yet.
When it's ready it will be in Maven Central.

**Comment by joakime** [comment]
See past answers to this at Issues #3546 and #2566

**Comment by mpe85** [comment]
Thanks for the clarification :thumbsup:
I just saw the tag in the github project and it looked like a final release
