### ISSUE TITLE
WebSocketConnectionStatsTest is flaky in 9.4.x

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3982]
```
java.lang.AssertionError: stats.receivedBytes
Expected: is <170271L>
     but: was <170263L>

```

disabling until fixed

**Comment by joakime** [comment]
I've only been able to recreate that failure ONCE locally.
But it occurs on CI/CD often. :-/

**Comment by joakime** [comment]
When it fails on CI/CD, I've noticed that the difference is always 8 bytes.

**Comment by gregw** [comment]
Can we please exclude flakey tests until they are fixed.  They're killing productivity.

**Comment by joakime** [comment]
Merged, and fixed.
