### ISSUE TITLE
Third-Party Library Version Inconsistencies in your project


### ISSUE THREAD

**Issue by ThirdLibResearch** [eclipse/jetty.project#3986]
We are currently investigating the usage of different versions of the same third-party library in different modules of a project (i.e., the library version inconsistency problem). It is a non-trivial and time-consuming task to maintain the evolving third-party libraries. In that sense, it seems necessary to harmonize the different versions of the same third-party library in different modules into one single version. Thus we developed a prototype tool to detect library version inconsistencies and suggest harmonized version with detailed maintenance efforts. We applied our tool on your GitHub project, and attached the generated report. We hope that the report could be useful for you to be aware of the library version inconsistencies in your project and to decide whether to harmonize inconsistent library versions.
Here is the report:
[eclipse jetty.project.pdf](https://github.com/ThirdLibResearch/ThirdLibSource/blob/master/issues/report/eclipse%20jetty.project.pdf)

Some pictures may be too large to present in the pdf so we attach them below: 
[85_javax.servlet____javax.servlet-api____jar_0.png](https://raw.githubusercontent.com/ThirdLibResearch/ThirdLibSource/master/issues/image/85_javax.servlet____javax.servlet-api____jar_0.png)
[85_org.eclipse.jetty.toolchain____jetty-test-helper____jar_0.png](https://raw.githubusercontent.com/ThirdLibResearch/ThirdLibSource/master/issues/image/85_org.eclipse.jetty.toolchain____jetty-test-helper____jar_0.png)

We will appreciate your comments very much.

Best regards

**Comment by joakime** [comment]
Closing, no issue is reported.
PDF report doesn't tell you anything.

**Comment by joakime** [comment]
If you want people to take you seriously, don't EVER use PDF. (It's a known vector for viruses)
Use markdown, on github, normally.
Don't just spam projects.
Tell the project some details. (what branch did you investigate? what version of the released project?, etc...)

If all you are doing is investigating library version inconsistencies, perhaps you should work with the existing github tooling for the same thing.
Submit patches against the standard tooling to make it better.
