### ISSUE TITLE
How does the Jetty server treat the request body (if sent) for DELETE HTTP requests ?

### ISSUE THREAD

**Issue by SonaliDasgupta** [eclipse/jetty.project#3992]
This is a question, regarding a requirement we have in our project, to send a request body with a DELETE HTTP request. Various sources cite that the Jetty server rejects the request body for a DELETE/GET request. Could the developers please explain in depth how the jetty server handles the request body in these cases, as this would be most helpful for us.

**Comment by olamy** [comment]
Please report only issue here.
For any question please use the user mailing list https://www.eclipse.org/jetty/mailinglists.html
