### ISSUE TITLE
Changelog, Upgrade / migration guide - websockets

### ISSUE THREAD

**Issue by black-snow** [eclipse/jetty.project#3999]
Is there any detailed changelog or upgrade guide for jetty versions?

I use dropwizard in combination with [dropwizard-websockets](https://github.com/LivePersonInc/dropwizard-websockets). Sadly, the websocket stuff is not maintained anymore. Dropwizard has moved to to newer jetty versions and things broke. I'd like to fix this but I honestly don't know where to start.

I'm sitting at a 

    java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
        at org.eclipse.jetty.websocket.jsr356.server.JsrCreator.createWebSocket(JsrCreator.java:113)

and going through thousands of commits to see what changed since the original jetty version (9.4.10.v20180503) is not an option.

**Comment by joakime** [comment]
I took a cursory glance at the github repository you linked.

You seem to be mixing native jetty websocket API and javax.websocket API arbitrarily.
Try picking one API or the other, but not both.

**Comment by black-snow** [comment]
@joakime thanks for taking a look. Taking a cursory look myself they seem to be mixed anyway. E.g. `org.eclipse.jetty.websocket.jsr356.endpoints.EndpointInstance.getConfig()` returns a `javax.websocket.EndpointConfig`.

**Comment by black-snow** [comment]
I *"fixed"* my issue by explicitly adding

```xml
<dependency>
            <groupId>javax.websocket</groupId>
            <artifactId>javax.websocket-api</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>javax-websocket-server-impl</artifactId>
            <version>9.4.20.v20190813</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>9.4.20.v20190813</version>
        </dependency>
```

to my project. I don't know how or why this works but I'll stick with it for now.

I'd still be glad to see some sort of a more detailed changelog, though!

**Comment by joakime** [comment]
You fixed it by adding those dependencies to what exactly?  Your server?

Your initial experiences could be due to having a mismatched version jetty-util loaded.
Please ensure you have all the same version of Jetty in your dependencies.
Consider using the jetty-bom to ensure that.

One red flag, is that if you did have a mismatched jetty-util version, why?
That usually means you have another dependency that is expecting an older version of jetty-util.
You might have broken some other dependency with this change.

> ``` xml
> <dependency>
>             <groupId>javax.websocket</groupId>
>             <artifactId>javax.websocket-api</artifactId>
>             <version>1.1</version>
>      </dependency>
> ```

One minor quibble, Jetty 9.4.x uses javax.websocket 1.0, not 1.1
javax.websocket 1.1 support was introduced in Jetty 10.

**Comment by joakime** [comment]
Closing as OP reports it's fixed.

**Comment by black-snow** [comment]
Thanks again.

I added the dependencies to my project that uses dropwizard-websockets. There is a broken dependency in one of dropwizard's modules, that's true. But fixing this somehow wasn't enough.

I'll use the websocket-api 1.0 then, thanks!

**Comment by joakime** [comment]
> I'd still be glad to see some sort of a more detailed changelog, though!

Every release has a VERSION.txt

Example:

* http://central.maven.org/maven2/org/eclipse/jetty/jetty-project/9.4.20.v20190813/jetty-project-9.4.20.v20190813-version.txt
* https://github.com/eclipse/jetty.project/blob/jetty-9.4.20.v20190813/VERSION.txt
* https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.20.v20190813
* https://www.eclipse.org/lists/jetty-announce/msg00133.html

**Comment by black-snow** [comment]
Thanks!
