### ISSUE TITLE
Add doc on quickstart for jetty-10

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4005]
Quickstart seems to be missing from jetty-10 documentation set. Quickstart is different to jetty-9, needs documenting.

**Comment by WalkerWatch** [comment]
@janbartel The Quickstart documentation still exists, and you can find it [here](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-documentation/src/main/asciidoc/distribution-guide/deploying/quickstart-webapp.adoc).

Do you have an overview that contains the changes to Quickstart? I am unsure how much has changed.

**Comment by gregw** [comment]
Whilst this is important, it is not a show stopper for 10.0.0 - bumping to 10.0.1

**Comment by WalkerWatch** [comment]
This exists in 10 and 11 

https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-quickstart

https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-quickstart
