### ISSUE TITLE
Jetty should select ciphers from enabled set and not supported set

### ISSUE THREAD

**Issue by harisv339** [eclipse/jetty.project#4011]
Ref: 
https://github.com/eclipse/jetty.project/blob/1a0f08b84df7aa127d7aa2e9dd56fd70de519743/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1427

TLS/SSL cipher suites are made available to Jetty runtime due to various reasons like - 
* Provider Support (JSSE and other such provider libraries known to JVM), 
* JVM security config (java.security) settings, 
* JVM Security policy (Security manager permissions), etc.

When "IncludeCipherSuites" is EMPTY, Jetty moves on to select all ENABLED cipher suites (subset of supported cipher suites). However, when this is NON-EMPTY (possibly because user opted to specify ciphers of interest either programmatically or via _jetty-ssl-context.xml_) Jetty seems to look at ALL SUPPORTED cipher suites and not the ENABLED cipher suites, which I think is incorrect. Jetty should respect JVM settings and policies and work on ENABLED cipher suites only while arriving at SELECTED cipher suites using the include/exclude jetty preferences.

**Comment by sbordet** [comment]
That would make impossible for people that want to use a weak or insecure (but fast) cipher to use it.
I think this behavior is intended - if you tell Jetty to use cipherA and cipherA is supported, Jetty will use it.
@joakime thoughts?

**Comment by joakime** [comment]
This seems to break the policy of Exclude wins of Include that the SslContextFactory works under.

**Comment by sbordet** [comment]
@joakime it's not much a matter of exclude vs include (we can fix that), it's a matter of supported vs enabled.

The OP only wants enabled, while I think the intent for _explicit_ include is for supported - to be able to say "I _really_ want this cipher, no matter what".
For example, I would be able to select the `NULL` cipher which is supported but not enabled.

**Comment by joakime** [comment]
A quick test, on Oracle Java 8u202, and AdoptOpenJDK 11.0.3+7, by default, the ENABLED and SUPPORTED Cipher Suites lists are identical (for that JVM).

``` java
package tls;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;

public class SslCipherSuiteDump
{
    public static void main(String[] args) throws NoSuchAlgorithmException
    {
        SSLEngine ssl = SSLContext.getDefault().createSSLEngine();

        System.out.println("java.version=" + System.getProperty("java.version"));
        System.out.println("java.vm.version=" + System.getProperty("java.vm.version"));

        dumpCipherSuites("SUPPORTED", ssl.getSupportedCipherSuites());
        dumpCipherSuites("ENABLED", ssl.getEnabledCipherSuites());
    }

    private static void dumpCipherSuites(String heading, String[] cipherSuites)
    {
        System.out.printf("-- %s --%n", heading);
        List<String> ciphers = new ArrayList<>();
        ciphers.addAll(Arrays.asList(cipherSuites));

        ciphers.stream()
            .sorted()
            .forEach((cipher) -> System.out.println(cipher));
    }
}
```



Name | Java 8u202 (SUPPORTED) | Java 8u202 (ENABLED) | Java 11.0.3+7 (SUPPORTED) | Java 11.0.3+7 (ENABLED)
-- | -- | -- | -- | --
TLS_AES_128_GCM_SHA256 | :x: | :x: | :heavy_check_mark: | :heavy_check_mark:
TLS_AES_256_GCM_SHA384 | :x: | :x: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_EMPTY_RENEGOTIATION_INFO_SCSV | :x: | :x: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_256_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:

**Comment by joakime** [comment]
Update, I checked against Oracle Java 8u202, AdoptOpenJDK 11.0.3+7, and Conscrypt 1.0 (as a Security Provider).

The code for the Conscrypt check ...

``` java
package tls;

import java.security.NoSuchAlgorithmException;
import java.security.Provider;
import java.security.Security;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.stream.Collectors;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;

import org.conscrypt.OpenSSLProvider;

public class SslCipherSuiteDump
{
    public static void main(String[] args) throws NoSuchAlgorithmException
    {
        dumpProvider(new OpenSSLProvider());
    }

    private static void dumpProvider(Provider provider) throws NoSuchAlgorithmException
    {
        Security.addProvider(provider);
        SSLEngine ssl = SSLContext.getInstance("Default", provider).createSSLEngine();
        System.out.println("java.version: " + System.getProperty("java.version"));
        System.out.println("java.vm.version: " + System.getProperty("java.vm.version"));

        Map<String, Set<String>> ciphers = new HashMap<>();
        Arrays.stream(ssl.getSupportedCipherSuites()).forEach(new ModeTracker(ciphers, "SUPPORTED"));
        Arrays.stream(ssl.getEnabledCipherSuites()).forEach(new ModeTracker(ciphers, "ENABLED"));
        List<String> names = ciphers.keySet().stream().sorted().collect(Collectors.toList());
        names.forEach((name) ->
        {
            boolean isSupported = ciphers.get(name).contains("SUPPORTED");
            boolean isEnabled = ciphers.get(name).contains("ENABLED");
            System.out.printf("%-46s \t %b \t %b %n", name, isSupported, isEnabled);
        });
    }

    private static class ModeTracker implements Consumer<String>
    {
        private final Map<String, Set<String>> cipherMap;
        private final String mode;

        public ModeTracker(Map<String, Set<String>> cipherMap, String mode)
        {
            this.cipherMap = cipherMap;
            this.mode = mode;
        }

        @Override
        public void accept(String cipher)
        {
            Set<String> modes = cipherMap.get(cipher);
            if (modes == null)
            {
                modes = new HashSet<>();
                cipherMap.put(cipher, modes);
            }
            modes.add(mode);
        }
    }
}
```

This now shows a difference, in conscrypt, between SUPPORTED and ENABLED.



Name | Java 8u202<br/>(SUPPORTED) | Java 8u202<br/>(ENABLED) | Java 11.0.3+7<br/>(SUPPORTED) | Java 11.0.3+7<br/>(ENABLED) | Conscrypt 1.0<br/>(SUPPORTED) | Conscrypt 1.0<br/>(ENABLED)
-- | -- | -- | -- | -- | -- | --
SSL_RSA_WITH_3DES_EDE_CBC_SHA | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_AES_128_GCM_SHA256 | :x: | :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_AES_256_GCM_SHA384 | :x: | :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_CHACHA20_POLY1305_SHA256 | :x: | :x: | :x: | :x: | :heavy_check_mark: | :heavy_check_mark:
TLS_DHE_DSS_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_DSS_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 | :x: | :x: | :x: | :x: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 | :x: | :x: | :x: | :x: | :heavy_check_mark: | :heavy_check_mark:
TLS_EMPTY_RENEGOTIATION_INFO_SCSV | :x: | :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_FALLBACK_SCSV | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_PSK_WITH_AES_128_CBC_SHA | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_PSK_WITH_AES_256_CBC_SHA | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x:
TLS_RSA_WITH_AES_128_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:
TLS_RSA_WITH_AES_128_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_RSA_WITH_AES_128_GCM_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_256_CBC_SHA | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
TLS_RSA_WITH_AES_256_CBC_SHA256 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:
TLS_RSA_WITH_AES_256_GCM_SHA384 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
