### ISSUE TITLE
Servlet which is added by ServletRegistration can't be started

### ISSUE THREAD

**Issue by chiqiu** [eclipse/jetty.project#4022]
Hi, 
We got a problem that servlets added by the following code:
ServletRegistration servletRegistration =
                context.addServlet(TheServlet.class.getName(), TheServlet.class);
can't be initialized correctly. The issue starts from 9.4.13, we didn't have this problem using 9.4.12 and 9.4.11.
An 500 response with  nullpointer exception is thrown when tried to access the servlet.
I debugged that the isRunning() method in ServletHolder always returns false.
Could you please take a look? We'd like to migrate to 9.4.19 

Thanks.

**Comment by olamy** [comment]
what is ` context `?
can you please provide a full reproductible test case?

**Comment by chiqiu** [comment]
The context here is ServletContext, we get this one by calling getServletContext()

**Comment by chiqiu** [comment]
I will try to reproduce it in  a test case

**Comment by janbartel** [comment]
@olamy I've got a PR #4024  that adds a couple of simple unit tests for servlet registration. So far we've been testing by using the test-spec-webapp in integration or manual tests, but we haven't had simple unit tests for registration.

**Comment by chiqiu** [comment]
Hi ,
I can reproduce the issue in this repo:  https://github.com/chiqiu/jettyut
you can get the error while accessing  "http://localhost:8082/hi/"
Please take a look.
Thank you!

**Comment by janbartel** [comment]
This is the stack trace I get when I fix up the supplied test case and access "localhost:8082/hi/foo":

> java.lang.NullPointerException
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:505)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
> 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by janbartel** [comment]
From the Servlet Spec, section 4.4:

> The following methods are added to ServletContext since Servlet 3.0 to enable
> programmatic definition of servlets, filters and the url pattern that they map to.
> These methods can only be called during the initialization of the application either
> from the contexInitialized method of a ServletContextListener
> implementation or from the onStartup method of a
> ServletContainerInitializer implementation.

So actually, you should never have been able to add a Servlet from a Servlet.init() method :)  I will look at how we generate a better error message rather than a NPE.

**Comment by chiqiu** [comment]
Thanks for the explanation.  My question is we have used the Servlet.init() to add servlets for a long time without problems until 9.4.13, is the behavior of jetty changed because of the new Spec?

**Comment by janbartel** [comment]
Well, I think we probably changed the startup order a little bit in the last couple of releases which now results in the NPE.

**Comment by chiqiu** [comment]
So the fix plan will be a new error message or fix the startup order?

**Comment by janbartel** [comment]
The fix plan is to throw IllegalStateException if trying to use the ServletContext.addServlet after the ServletHandler has been initialized (ServletContainerInitializers and ServletContextListeners are called before initialization of the ServletHandler).

**Comment by chiqiu** [comment]
Ok, thank you very much!

**Comment by janbartel** [comment]
Fix commited for jetty-9.4.21 and above.
