### ISSUE TITLE
Provide more write-through behaviours for DefaultSessionCache

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4025]
Currently the DefaultSessionCache behaviour is to only write out a session once the last concurrent request is finished.  There are 2 areas where this behaviour can be problematic:

* the response might have already returned to the client before the request is finished being handled on the server, and thus we have not yet written the session out before the next request arrives for it. This is not a problem if the request arrives to the same server (as the session is in the DefaultSessionCache and will be shared), but if the sessions are not sticky and the request goes to a different server, that server will not see the updated session data.

* with long polling, a subsequent client request is likely to arrive before the previous long poll request has finished being handled on the server and the session data written out. Potentially, these back-to-back requests might significantly delay the session data being written out.

To address these problems, it is proposed to enable similar set of write-through modes for the DefaultSessionCache as has been done for the NullSessionCache, namely:

* ALWAYS:  every change to a session attribute causes a full write of the session data.
* NEW:  every change to a session attribute causes a full write of the session data while the session is new (ie its id not yet returned to the client).
* ON_EXIT: current behaviour: the session data will be written when the last request exists the session.

**Comment by joakime** [comment]
PR #4049 opened

**Comment by janbartel** [comment]
Please see comments on PR #4049. This was fixed a different way, by introducing the "flushOnResponseCommit" option for all the session caches (currently DefaultSessionCache, NullSessionCache). 

Checked in for 9.4.21 and beyond.
