### ISSUE TITLE
jetty-runner question

### ISSUE THREAD

**Issue by janikgithub** [eclipse/jetty.project#4037]
I pulled jetty-runner-9.4.18.v20190429.jar and websockets are no longer working in my project (it used to be running on Tomcat).
Google search mentions that JSR-356 is not enabled on jetty-runner (although search results are 2-3 years old).

Can you please tell whether it is correct and if it is how do I enable  JSR-356 in the jetty-runner.
Thank you

**Comment by joakime** [comment]
You would need to compile your own jetty-runner to add that feature.

Have you considered either making a uber jar for your webapp, or making an executable war for it?

* https://github.com/jetty-project/embedded-jetty-uber-jar
* https://github.com/jetty-project/embedded-jetty-live-war

**Comment by janikgithub** [comment]
Let me try uber first. 
Thank you

**Comment by janikgithub** [comment]
Where can I find instructions on how to build  jetty-runner including  JSR-356 support?
Thanks

**Comment by janikgithub** [comment]
I can't use either uber nor embedded-jetty-live-war

**Comment by joakime** [comment]
uber jar is just a jar that you package with all of your projects classes, and all of the classes from your dependencies as well.

This is accomplished with the `maven-shade-plugin`, which is the general go-to for making uber jars.

See example of maven-shade-plugin use at
https://github.com/jetty-project/embedded-jetty-uber-jar/blob/0872750e70baff4845d93955e317c47a59a8c27c/pom.xml#L62-L139

If you build that project and run it you can see it in action.

``` shell
# build + package project
$ mvn clean install
# run the resulting jar
$ java -jar target/embedded-jetty-uber-jar-1-SNAPSHOT.jar
```

**Comment by janikgithub** [comment]
Thank you
