### ISSUE TITLE
please help with oracleJDK and open-JDK support matrix with Jetty

### ISSUE THREAD

**Issue by rajivjain83** [eclipse/jetty.project#4039]
Hi,

Can we have open-JDK and oracle-JDK support matrix for Jetty version 9.4.18, 9.4.20?

Regards
Rajiv

**Comment by joakime** [comment]
For Jetty 9.4.x, it's all versions of public Oracle JDK and OpenJDK releases (we test with AdoptOpenJDK).
We have not tested on private Oracle JDK releases, or other commercial OpenJDK releases (from the likes of redhat, azul, ibm, amazon, etc)
We work with Java 1.8 up to Java 14.

If you need to use ALPN, then consult the ALPN versions table - https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions
