### ISSUE TITLE
MaxUploadSizeExceededException handling with spring-boot and jetty

### ISSUE THREAD

**Issue by zenonwch** [eclipse/jetty.project#4041]
I'm running my application with spring-boot-starter-jetty: 2.1.4 (and tryed with 2.1.7).
With JettyConfig:
```java
@Configuration
@Profile("default")
public class JettyConfiguration {

    @Value("classpath:jetty-env.xml")
    private Resource jettyEnvResource;

    @Bean
    public ConfigurableServletWebServerFactory webServerFactory() {
        JettyServletWebServerFactory jettyContainer = new JettyServletWebServerFactory();
        jettyContainer.addServerCustomizers(jettyServerCustomizer());
        return jettyContainer;
    }

    private JettyServerCustomizer jettyServerCustomizer() {
        return server -> {
            try {
                WebAppContext webAppContext = (WebAppContext) server.getHandler();
                new XmlConfiguration(new FileInputStream(jettyEnvResource.getFile()))
                        .configure(webAppContext);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        };
    }
}
```
and jetty-env.xml:
```xml
<?xml version="1.0"?>

<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN" "http://jetty.mortbay.org/configure.dtd">
<Configure id="WebAppContext" class="org.eclipse.jetty.webapp.WebAppContext">
    <Call class="java.lang.System" name="setProperties">
        <Arg>
            <New class="java.util.Properties">
                <Call name="putAll">
                    <Arg>
                        <Call class="java.lang.System" name="getProperties"/>
                    </Arg>
                </Call>
            </New>
        </Arg>
    </Call>
    <New id="DataSource" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg>jdbc/source</Arg>
        <Arg>
            <New class="oracle.jdbc.pool.OracleDataSource">
                <Set name="DriverType">thin</Set>
                <Set name="URL">@url@</Set>
                <Set name="User">@db_user@</Set>
                <Set name="Password">@db_password@</Set>
                <Set name="connectionCachingEnabled">true</Set>
                <Set name="connectionCacheProperties">
                    <New class="java.util.Properties">
                        <Call name="setProperty">
                            <Arg>MinLimit</Arg>
                            <Arg>5</Arg>
                        </Call>
                    </New>
                </Set>
            </New>
        </Arg>
    </New>
    <New class="org.eclipse.jetty.plus.jndi.EnvEntry">
        <Arg></Arg>
        <Arg>application.encryption.key</Arg>
        <Arg type="java.lang.String">@key@</Arg>
        <Arg type="boolean">true</Arg>
    </New>
</Configure>
```
I'm trying to handle MaxUploadSizeExceededException using ResponseEntityExceptionHandler as follows:
```java
@ControllerAdvice
public class CustomResponseEntityExceptionHandler extends ResponseEntityExceptionHandler {
    @Value("${spring.servlet.multipart.max-file-size}")
    private Long maxAllowedSize;

    @ResponseBody
    @ResponseStatus(HttpStatus.PAYLOAD_TOO_LARGE)
    @ExceptionHandler(MaxUploadSizeExceededException.class)
    public ResponseEntity<String> handleMaxUploadSizeExceededException(final MaxUploadSizeExceededException exception) {
        String message = "Attempt to upload file with the size exceeded max allowed value = " + maxAllowedSize + " byte(s).");

        return ResponseEntity.status(HttpStatus.PAYLOAD_TOO_LARGE).body(message);
    }
}
```
But Spring's org.springframework.web.multipart.MultipartException is not thrown. Instead I see in logs `org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content` with rootCause `java.lang.IllegalStateException: Multipart Mime part query exceeds max filesize`
![image](https://user-images.githubusercontent.com/17174214/64030846-039db480-cb50-11e9-884b-bef4f5aa4583.png)

Please point me what I'm doing wrong.

**Comment by joakime** [comment]
Configuring the size limits on `multipart/form-data` is done from one of the following ...

## [`javax.servlet.annotation.MultipartConfig`](https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/MultipartConfig.html) annotation

This is the most common way.

``` java
@MultipartConfig(location="/tmp/upload", fileSizeThreshold=1024*1024, maxFileSize=1024*1024*50)
@WebServlet(urlPatterns={"/upload"}, name="upload")
public class UploadServlet extends HttpServlet
{
```

## [`javax.servlet.MultipartConfigElement`](https://docs.oracle.com/javaee/7/api/javax/servlet/MultipartConfigElement.html) with embedded-jetty.

This can be done per-request, by setting a Request attribute ...

``` java
MultipartConfigElement multipartConfig = new MultipartConfigElement(tmpdir.getAbsolutePath());
request.setAttribute(Request.MULTIPART_CONFIG_ELEMENT, multipartConfig);
```

... or by registering the Multipart Config during servlet registration ...

``` java
String location = multipartTmpDir.toString();
long maxFileSize = 10 * 1024 * 1024; // 10 MB
long maxRequestSize = 10 * 1024 * 1024; // 10 MB
int fileSizeThreshold = 64 * 1024; // 64 KB
MultipartConfigElement multipartConfig = new MultipartConfigElement(location, maxFileSize, maxRequestSize, fileSizeThreshold);
servletHolder.getRegistration().setMultipartConfig(element);
```

### `<multipart-config>` element in the `WEB-INF/web.xml`

``` xml
<servlet>
    <servlet-name>upload</servlet-name>
    <servlet-class>org.eclipse.jetty.demo.UploadDemoServlet</servlet-class>
    <multipart-config>
        <max-file-size>104448</max-file-size>
        <max-request-size>26214400</max-request-size>
        <file-size-threshold>1048576</file-size-threshold>
    </multipart-config>
</servlet>
<servlet-mapping>
    <servlet-name>upload</servlet-name>
    <url-pattern>/upload/*</url-pattern>
</servlet-mapping>
```

**Comment by zenonwch** [comment]
@joakime thanks for the quick reply.
Sorry, but I forgot to add the part of my application.yml where multipart element is already configured:
```yml
spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 20971520 #20 MB
            max-request-size: 26214400 #25 MB
```

**Comment by joakime** [comment]
That's spring doing whatever it's doing.
You'll want to also set the `location` and `file-size-threshold`, so that large files can be written to temp disk space and not be held in memory.
All I can comment on is how Jetty works.
And the error you reported is from receiving a request that falls outside of the configured MultipartConfig settings for your servlet.
You might have to increase your max-file-size and/or max-request-size.

**Comment by zenonwch** [comment]
Sorry, but I do not understand what I'm doing wrong (or what I need to do to handle MaxUploadSizeExceededException with Spring + jetty).
I tried to set Multipart Config during servlet registration - no luck.
Again got Jetty error instead of Spring MaxUploadSizeExceededException.

**Comment by joakime** [comment]
The exception `MaxUploadSizeExceededException` is produced by spring, not jetty.

The exception `java.lang.IllegalStateException: Multipart Mime part query exceeds max filesize` is an exception from Jetty.
It's telling you that the (`multipart/form-data`) part called "query" is larger then your configured MultipartConfig.maxFileSize.

From Jetty's point of view, you have 2 options:

* Configure MultipartConfig.maxFileSize to be bigger.
* or Send less content to satisfy the MultipartConfig.maxFileSize.

The `MultipartConfig` is a servlet spec feature, you have to satisfy that before you can accomplish what you need in Jetty (or Tomcat, or JBoss, or Glassfish, or Resin, or any other Servlet container that spring runs on).

At this point, I would suggest asking the Spring folks how to configure that using their spring-boot and application.yml setup.
Or look at https://stackoverflow.com/questions/28572700/i-am-trying-to-set-maxfilesize-but-it-is-not-honored

**Comment by zenonwch** [comment]
@joakime, thanks for your time.
I reported the issue in the spring-boot repository: https://github.com/spring-projects/spring-boot/issues/18088
