### ISSUE TITLE
NullPointerException in o.e.j.h.HttpFields

### ISSUE THREAD

**Issue by SerCeMan** [eclipse/jetty.project#4057]
Hi, Jetty Maintainers!

After upgrading to `9.4.20.v20190813` 3 weeks ago, we started seeing the following exception. 
```
java.lang.NullPointerException: null
    at org.eclipse.jetty.http.HttpFields.containsKey(HttpFields.java:240)
    at org.eclipse.jetty.server.Response.containsHeader(Response.java:267)
    at com.company.security.MyFilter.doFilter(MyFilter.java:118)
    at ...
```

The code is similar to the following:

```java
HttpServletResponse httpResponse = (HttpServletResponse) response;
// ...
chain.doFilter(request, response);
// ...
if (httpResponse.containsHeader(LOCATION_KEY)) {
...
}
```

I couldn't find a real reproducer for the issue. I noticed that there were a few changes introduced to `HttpFields` recently and I was wondering if you could have any ideas on what could be causing this?

**Comment by joakime** [comment]
This NPE is a simple enough fix.

But it also means you (somehow) have a response header field with a null `name`.

Does this exception occur often enough that you can toss in a debug statement for us to confirm this?

``` java
HttpServletResponse httpResponse = (HttpServletResponse) response;
// ...
chain.doFilter(request, response);
// ...
try
{
  if (httpResponse.containsHeader(LOCATION_KEY)) {
  ...
  }
} catch(NullPointerException npe)
{
  Response jettyResponse = (Response) response;
  log.debug("The Response HttpFields are: " + jettyResponse.getHttpFields());
  throw npe;
}
```

**Comment by joakime** [comment]
The only way I've found to replicate this is to abuse the `HttpField` class.

https://github.com/eclipse/jetty.project/blob/49ba6d1acb230ecc5d2cdca1517d3e97dff4bfbf/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java#L37-L42

If I use the following, it triggers the same stacktrace ...

``` java
HttpFields fields = new HttpFields();
fields.put("Host", "localhost");
HttpField nullField = new HttpField(HttpHeader.CONNECTION, null, "bogus");
fields.put(nullField);

assertTrue(fields.containsKey("Host"));
```

@sbordet @gregw is there any reason we are not null checking the `_name` field here?

**Comment by joakime** [comment]
@SerCeMan are you using HTTP2 by any chance?

**Comment by joakime** [comment]
Opened PR #4059

**Comment by joakime** [comment]
PR #4059 has been merged.
This will show up in the next 9.4.x release (probably 9.4.21)

**Comment by SerCeMan** [comment]
Hi, @joakime! Thank you for the very switft fix! Would the debugging information still be helpful? E.g. regarding the header values?

**Comment by joakime** [comment]
@SerCeMan we still don't know HOW that HttpField with a null name came to be.
So yeah, any new information you can give us would be helpful.

**Comment by SerCeMan** [comment]
Just an update, interestingly after adding loggin we've stopped seeing this exception, although it might have also stopped due to other changes.
