### ISSUE TITLE
GzipHandler: allow to override the Vary response header

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#406]
`GzipHandler` has its internal logic to customize response headers (for example, adding the `Vary` header).

Introduce an overridable method so that applications can subclass `GzipHandler` and intercept when `GzipHandler` modifies the response headers, and decide whether to allow the modification or not.

**Comment by joakime** [comment]
Seems related to Issue #383

**Comment by sbordet** [comment]
Added overridable method `GzipHandler.getVaryField()`.
