### ISSUE TITLE
login services should use modules for configuration of each implementation

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#4073]
Currently to use a specific `LoginService` you must configure it through xml, but ideally this should be configured using modules for each implementation of `LoginService`.

Each of those login service modules would "provide loginservice", and all of the login service modules would configure a `LoginService` with the same, well-known id (eg "loginService") so that other modules could reference it.

This could then be used from the openid module which needs to wrap a `LoginService`, currently this needs to be configured through xml.

**Comment by janbartel** [comment]
A comment to bear in mind when implementing this: as the OpenID loginservice would need to "provide loginservice", but also want to depend on "loginservice" (to obtain the login service to wrap) it might be a little tricky.
