### ISSUE TITLE
Use of HttpConfiguration.setBlockingTimeout(long) in jetty.xml produces warning on jetty-home startup

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4084]
The HttpConfiguration.setBlockingTimeout(long) is deprecated.
The new deprecation warnings in XmlConfiguration is correctly reporting that our use of setBlockingTimeout(long) is deprecated.
Even if we are not setting it to a value (default value in jetty-home modules / xml is -1)

```
2019-09-11 16:22:35.810:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.server.HttpConfiguration.setBlockingTimeout(long) in
     file:///home/joakim/code/jetty/distros/jetty-home-9.4.20.v20190813/etc/jetty.xml
```

Should we make an effort to remove this warning?

**Comment by gregw** [comment]
@joakime @sbordet I'm not sure how to fix this?  Either we remove the `<Set>` in jetty.xml, in which case we have removed a deprecated feature in a dot release, or we don't warn?

In 10, we have the ability to avoid the warning by using `<Set property=foobar/>`, but that doesn't help us for 9

**Comment by gregw** [comment]
I think I will just make the warning a debug for now.

**Comment by gregw** [comment]
I made it debug only in 9, but kept the warning in 10 (as it has the `<Set property=foobar/>` symmantic to avoid the warning if need be).

**Comment by joakime** [comment]
I would have preferred that XmlConfiguration not attempt to <Set> call.
Either because the property is empty/unset.
Or if the value provided is the same as the default value.

**Comment by sbordet** [comment]
Yes we want the warnings to be at INFO at least, and we can easily remove the call from the XML - the default value should be the same.

**Comment by gregw** [comment]
I think we have enough to do on other issues.  Let's not sweat this one in 9.4 - all is good in 10.

**Comment by joakime** [comment]
If we are going to go this route, I would prefer the old 9.4 behavior, reverting commit 157910d79a4a3554774292b767c70de334db27a6 on `jetty-9.4.x` at least.

**Comment by gregw** [comment]
I really don't think this is worth the effort - but fix it if you like.   But we can't have warnings from a normal distro, nor should we remove a feature in a dot release.

**Comment by vmassol** [comment]
@sbordet I don't see where you removed the property from the jetty.xml file. It seems it's still there on master.

**Comment by vmassol** [comment]
FTR I've replaced it with the following but I don't know if that's correct:

```
    <Set name="minResponseDataRate"><Property name="jetty.httpConfig.minResponseDataRate" default="-1"/></Set>
    <Set name="minRequestDataRate"><Property name="jetty.httpConfig.minRequestDataRate" default="-1"/></Set>
```

**Comment by sbordet** [comment]
@vmassol it's there but we don't WARN about it anymore.
Unfortunately it cannot be removed from the XML file because people may actually use it.

See also #4014 for the actual behavior of the data rates - we may change it in future.

**Comment by joakime** [comment]
@vmassol the `setBlockingTimeout(long)` was just squelched from WARN to DEBUG in PR #4107 (if that property is unset), due to be in Jetty 9.4.21 (currently staged and being tested).

**Comment by vmassol** [comment]
@sbordet @joakime Thanks guys for your answers (and fast ones!), makes sense.
