### ISSUE TITLE
Http client authentication with proxy server

### ISSUE THREAD

**Issue by smatei** [eclipse/jetty.project#409]
Hi,

In AuthenticationProtocolHandler I had to change the parseAuthenticateHeader method 

`private List<Authentication.HeaderInfo> parseAuthenticateHeader(Response response, HttpHeader header)
        {
            // TODO: these should be ordered by strength
            List<Authentication.HeaderInfo> result = new ArrayList<>();
            List<String> values = Collections.list(response.getHeaders().getValues(header.asString()));
            for (String value : values)
            {
              if (value.equals("Basic realm=\"\"Proxy\"\""))
                value = "Basic realm=\"Proxy\"";
              
                Matcher matcher = AUTHENTICATE_PATTERN.matcher(value);
                if (matcher.matches())
                {
                    String type = matcher.group(1);
                    String realm = matcher.group(2);
                    String params = matcher.group(3);
                    Authentication.HeaderInfo headerInfo = new Authentication.HeaderInfo(type, realm, params, getAuthorizationHeader());
                    result.add(headerInfo);
                }
            }
            return result;
        }` 

The value of the response contains double qotes: Basic realm=""Proxy"". This works with apache http client, but not with your AUTHENTICATE_PATTERN. If I strip one quote, the pattern works.

`              if (value.equals("Basic realm=\"\"Proxy\"\""))
                value = "Basic realm=\"Proxy\"";`

**Comment by sbordet** [comment]
Wow, that is a pretty broken server.

Double quotes are actually forbidden by the specification, see https://tools.ietf.org/html/rfc7235#appendix-C.

**Comment by smatei** [comment]
Ok, I got it, but the authentication is awkward. Why send the request using no authentication, then receive 407, then parse some stupid header the server returns (the browsers don't care about it, just ask for user and password), then search for an authentication matching the proxy, then send the request with authentication. It is not straightforward. You should send the request with the authentication from the start, if the server does not like it, it will reject it. I mean that I know for sure I need authentication, no need to get that from the server.

Look how simple it is in apache http client (3.1)

`aClient.getHostConfiguration().setProxy(mProxyServer,xmProxyPort);
aMethod.setDoAuthentication(true);   
 aClient.getParams().setAuthenticationPreemptive(true);        
        state.setProxyCredentials(AuthScope.ANY, new UsernamePasswordCredentials(mProxyUser, mProxyPassword)); aClient.getParams().setAuthenticationPreemptive(true);        
        state.setProxyCredentials(AuthScope.ANY, new UsernamePasswordCredentials(mProxyUser, mProxyPassword));`

And it goes with authentication from the first request.

Otherwise the library will fail on squid servers that work with any other browser or library that do not care about that header.

**Comment by sbordet** [comment]
@smatei the problem with authentication is that in general it requires the roundtrip with the server in order to compute the right credentials.
AFAIK, all authentication schemes apart _Basic_ require this additional roundtrip.

You have a point that for _Basic_ authentication it could be simpler, so now you can do:

```java
AuthenticationStore authenticationStore = client.getAuthenticationStore();
URI uri = URI.create("http://host/path");
authenticationStore.addAuthenticationResult(new BasicAuthentication.BasicResult(uri, "username", "password"));
```

`BasicResult` has an additional constructor where you can specify the HTTP header, replacing `Authorization` with `Proxy-Authorization` if you need to.
