### ISSUE TITLE
Unable to initialize WebSocketPolicy.maxTextMessageBufferSize

### ISSUE THREAD

**Issue by fvaleri** [eclipse/jetty.project#4092]
It seems that `WebSocketPolicy.maxTextMessageBufferSize` is not initialized in https://github.com/eclipse/jetty.project/blob/master/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServlet.java#L107:L150. 

This is a problem if you need to raise this value to send big payloads.

**Comment by joakime** [comment]
Well ... `master` is not the active code branch, nor is it the default branch on git at the moment, that would be `jetty-9.4.x`.

Also, that code in Jetty 9.4.x ...

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServlet.java#L110-L143

... just sets the value if specified, if you don't specify it, it doesn't set it.

The default values are indicated in WebSocketPolicy ...

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java#L38-L54

The values you have are a hierarchy in reality ...

1. Default on WebSocketPolicy
2. Declared value during initialization of WebSocket Container
3. Declared value on endpoint annotation / or endpoint config
4. Per connection declared value

So, yes, you have to set it to a valid value, and "infinite" or "no value" is not a valid option.
With each layer, if you don't set it, the layer before is interrogated, with an ultimate sane (for memory) default setting on WebSocketPolicy.

Note also, that text message size limit only applies to ...

1. Per frame maximum buffer size
2. Whole message delivery buffer size

It does not apply to streaming message delivery. (but using streaming message delivery introduces more threading demands)

**Comment by fvaleri** [comment]
Thanks @joakime , my problem is that `maxTextMessageBufferSize` isn't initialized in `WebSocketServlet.init`, so I can't even pass an invalid value.

**Comment by joakime** [comment]
Since `WebSocketServlet` is for initializing a WebSocket Endpoint with a focus on receiving messages, controlling the write behaviors hasn't historically been done via init parameters.

The setting `maxTextMessageBufferSize` can still be controlled by either the WebSocketServlet or the Session.

``` java
    public class MyWebSocketServlet extends WebSocketServlet
    {
        @Override
        public void configure(WebSocketServletFactory factory)
        {
            factory.getPolicy().setMaxTextMessageBufferSize(4 * 1024 * 1024);
            factory.getExtensionFactory().unregister("permessage-deflate");
            factory.setCreator(new MyWebSocketCreator());
        }
    }
```

or within the the Session

``` java
@WebSocket
public class MyWebSocket
{
    @OnWebSocketConnect
    public void onConnect(Session session)
    {
        session.getPolicy().setMaxTextMessageBufferSize(4 * 1024 * 1024);
    }
}
```

Of note, you shouldn't set this value to something higher then your network's interface's MTU, you'll just waste memory and gain no extra benefit on the higher value.

``` java
    public static void main(String[] args) throws SocketException
    {
        Collection<NetworkInterface> ifaces = Collections.list(NetworkInterface.getNetworkInterfaces());

        for (NetworkInterface iface : ifaces)
        {
            System.out.printf("iface: %s - MTU=%d%n", iface, iface.getMTU());
        }
    }
```

**Comment by fvaleri** [comment]
Thanks @joakime, now I see why it is not initialized in WebSocket Servlet.
Really appreciate your answer.
