### ISSUE TITLE
The Page is not redirected Properly issue 

### ISSUE THREAD

**Issue by devmradul** [eclipse/jetty.project#4119]
When i hit the application URL from the browser its showing the error as "The Page is not redirected properly" and multiple request for login.jsp page is trigged.

Please help me to resolve the issue.

Note: Upgrading Jetty version 6 to version 9.4.15

**Comment by sbordet** [comment]
Your application is likely redirecting to the same URI over and over.

**Comment by devmradul** [comment]
How can we resolve the issue ?. Issue arise while doing upgradation from jetty v6 to jetty v9.4.15.

**Comment by joakime** [comment]
@devmradul start by watching the network traffic in your browser's inspection panel.
Then check your code for the origin of each 302 redirect you see (look at the `Location` header in your 302 redirect responses)
That will tell you what you need to address.

**Comment by janbartel** [comment]
Advice has been given as to how to approach pinpointing the problem. I'm closing this issue for now, as there is no identifiable problem in jetty. For more support in transitioning from jetty-6 to jetty-9 there is the online documentation, and also the jetty-users@eclipse.org mailing list.
