### ISSUE TITLE
Clarify ServletContextListener.contextDestroyed

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#412]
See [servlet-spec-152](https://java.net/jira/browse/SERVLET_SPEC-152)

**Comment by joakime** [comment]
New location of Servlet Spec reference is eclipse-ee4j/servlet-api#152

**Comment by janbartel** [comment]
As the original servlet spec issue is still open, we should keep this corresponding jetty issue open.

**Comment by joakime** [comment]
Closing this issue.
If this becomes a change we need to make, we'll just open a new issue.
