### ISSUE TITLE
QueuedThreadPool should support ThreadFactory behaviors

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4121]
The JVM class [`java.util.concurrent.ThreadFactory`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ThreadFactory.html) was introduced in Java 1.5 and the default Executors in Java support it as well.

@sbordet proposes that we have `QueuedThreadPool` implement `java.util.concurrent.ThreadFactory`, but also allow the constructor of `QueuedThreadPool` have an optional `ThreadFactory` that can be passed in ([similar to how the Executors themselves operate](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html#%3Cinit%3E(int,int,long,java.util.concurrent.TimeUnit,java.util.concurrent.BlockingQueue,java.util.concurrent.ThreadFactory)))

We should also move the configuration of the new thread ....

https://github.com/eclipse/jetty.project/blob/ba728eee5d9e8cfd3b7449b1246546ca2306bb25/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L633-L638

... into the QTP.newThread(Runnable) ...

https://github.com/eclipse/jetty.project/blob/ba728eee5d9e8cfd3b7449b1246546ca2306bb25/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L666-L669

**Comment by joakime** [comment]
The fix in PR #4146 is only a half fix.
I'll submit a followup PR for the rest.

**Comment by joakime** [comment]
Opened PR #4149 (currently in draft status as I work on unit tests)

**Comment by josephlbarnett** [comment]
FYI, by making the protected `newThread` method public, there is some backwards incompatibility here, not sure if that was known/intended.  see linked jetty bug for example.

**Comment by joakime** [comment]
The change was intended.
The QueuedThreadPool constructor takes a ThreadPool now, and will use it.

**Comment by gregw** [comment]
@josephlbarnett to be precise... the change to use the ThreadFactory API was intended.... that fact that this change breaks backwards compatibility was an unintended consequence.  In retrospect we should not have broken that in a point release, but it is a good change and it is out now... we'd cause more disruption I think by reverting.

**Comment by NielsDoucet** [comment]
@gregw Currently this causes a bug for anyone using the spring-boot-dependencies bom as a baseline for dependency management. See https://github.com/spring-projects/spring-boot/issues/19769.
Is there any way this situation can be improved? Perhaps a special release without the breaking api?

**Comment by joakime** [comment]
We already have large projects using this new feature (as it was requested by them).

**Comment by NielsDoucet** [comment]
I understand. As highlighted in the spring-boot ticket linked above, spring-boot clearly also wanted this and other new features, but maybe you have some way to cut a special version of the 9.4.24 release, which rolls back this breaking api change only.

The impact is rather big, as any project using spring boot version 2.2.1+ to drive their dependency management (default behaviour when using their maven or gradle plugin) will automatically get their versions managed to this broken combination of jetty and jersey.

**Comment by joakime** [comment]
We are about to release 9.4.26 to address issues discovered in 9.4.24 and 9.4.25

Jersey is the reason for the 9.4.26 release due to issue #4461, they will be upgrading to 9.4.26.

**Comment by joakime** [comment]
@NielsDoucet other large projects that use Jersey have been able to use Jetty 9.4.24 and 9.4.25 without a similar issue to spring-boot.
Why is this unique to spring-boot?

**Comment by wilkinsona** [comment]
I don't believe it is unique to Spring Boot. As I understand it, it's a problem for anyone trying to use Jersey 2.29.x with Jetty 9.4.22 and later when Jersey's responsible for creating the Jetty instance. As shown in the Boot issue referenced above (https://github.com/spring-projects/spring-boot/issues/19769), one way to do that is by using Jersey's test framework. Spring Boot users who aren't using Jersey's test framework may not be affected at all as Boot will create the Jetty instance and configure Jersey to run on top of it. My understanding is that will take Jersey's `org.glassfish.jersey.jetty.JettyHttpContainerFactory$JettyConnectorThreadPool` out of the picture so the breaking change to the visibility of `newThread` won't cause a problem.
