### ISSUE TITLE
Bad start.jar for 9.4.14+

### ISSUE THREAD

**Issue by vmassol** [eclipse/jetty.project#4127]
Hi there,

In XWiki we depend on the `org.eclipse.jetty:jetty-start` JAR artifact and rename it to start.jar when we create [our jetty distribution](https://github.com/xwiki/xwiki-platform/blob/06e278907a5d8405adbe1b6b2db4deb7a0b6f914/xwiki-platform-tools/xwiki-platform-tool-jetty/xwiki-platform-tool-jetty-resources/src/main/assembly/distribution.xml#L35). However, when using it we're getting:

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ManifestUtils
	at org.eclipse.jetty.start.StartArgs.<clinit>(StartArgs.java:70)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:292)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.ManifestUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

I tested this with Jetty 9.4.14.v20181114 and 9.4.20.v20190813.

However when downloading the official Jetty distribution, the `start.jar` there works fine. Actually, if I replace the XWiki distribution `start.jar` by this one, it starts working.

So two things I don't understand:
1) Why is the `jetty-start-9.4.14.v20181114.jar` not good (it's 151788 bytes in size)
2) Where is the `start.jar` inside the `jetty-distribution-9.4.14.v20181114.zip` coming from (it's 160625 bytes in size).

Thanks a lot!
-Vincent

PS: Issue on the XWiki side is at https://jira.xwiki.org/browse/XWIKI-15155

**Comment by joakime** [comment]
jetty-start (the artifact on maven central) has a dependency on jetty-util starting in 9.4.9.v20180320

There is a shaded version at ...

``` xml
<dependency>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-start</artifactId>
  <version>9.4.20.v20190813</version>
  <classifier>shaded</classifier>
  <type>jar</type>
</dependency>
```

The [`jetty-home` artifact](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/9.4.20.v20190813/) uses the shaded version.

_Note:_ `jetty-distribution` == `jetty-home` + demo-base + documentation.  You might want to consider just using jetty-home tarball/zip instead for your XWiki.

``` xml
<dependency>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-home</artifactId>
  <version>9.4.20.v20190813</version>
  <type>zip</type>
</dependency>
```

**Comment by vmassol** [comment]
Thanks a lot @joakime ! 

> Note: jetty-distribution == jetty-home + demo-base + documentation. You might want to consider just using jetty-home tarball/zip instead for your XWiki.

Yes that would be an idea. However, I think we have a better control of the jetty distribution we package XWiki with, just including what's needed to run XWiki. We could do it the other way around and depend on `jetty-home` and remove things but I think we would risk not removing new things added by Jetty and that we don't need. Now it's true that the downside of our approach is that when there are changes in Jetty we need to adapt.

Thanks a lot

**Comment by vmassol** [comment]
FTR it's working fine when using the shaded version.
