### ISSUE TITLE
Should be possible to use OIDC without metadata

### ISSUE THREAD

**Issue by travisspencer** [eclipse/jetty.project#4132]
The exposure of OpenID Connect metadata to a client (an RP) isn't required by the spec. Some OpenID Connect Providers (OP) do not support this. Even some that do support this will not expose it to clients. Even when they do, the client may know the token and authorization endpoints at configuration time, avoiding the need to make an HTTP request at run-time to get something that's already known. 

For all these reasons, two optional configuration settings should be added to the new OpenID module that allows the admin to configure the token and authorization endpoint. When they are configured, the metadata should not be fetched.

**Comment by lachlan-roberts** [comment]
The token and authorization endpoints can now be configured since PR #4133, this will allow use with OIDC providers which do not supply metadata.
