### ISSUE TITLE
Audience of ID token may be an array casing Openid auth to fail

### ISSUE THREAD

**Issue by travisspencer** [eclipse/jetty.project#4134]
OpenID Connect says this about the `aud` claim of an ID token:

> aud
>     REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string. 

This means that an ID token may contain multiple values for the `aud` claim, like this one:

`eyJraWQiOiIxNTU1OTM0ODQ3IiwieDV0IjoiOWdCOW9zRldSRHRSMkhtNGNmVnJnWTBGcmZRIiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoicS01VlAwc0F6V2NOblI2V19CNV96QSIsImRlbGVnYXRpb25faWQiOiJjYTM5OGVjMi0xYjhkLTQxMDQtYjdjNC1mMzY5ZDY5NTQ0MDQiLCJhY3IiOiJ1cm46c2U6Y3VyaXR5OmF1dGhlbnRpY2F0aW9uOmh0bWwtZm9ybTpodG1sLXByaW1hcnkiLCJzX2hhc2giOiJrbWVUYVoxZkpJVWREaUFDNHY5RDFnIiwiYXpwIjoiamV0dHktdGVzdCIsImF1dGhfdGltZSI6MTU2OTY4NTYyNSwiZXhwIjoxNTY5Njg5MjI2LCJuYmYiOjE1Njk2ODU2MjYsImp0aSI6ImUxN2M5NDJmLWUwZjQtNDhkOS04YjM1LTYzOTY2ZTJiOGJmYiIsImlzcyI6Imh0dHBzOi8vbm9yZGljYXBpcy5jdXJpdHkuaW8vfiIsImF1ZCI6WyJqZXR0eS10ZXN0Iiwib3RoZXIiXSwic3ViIjoidHNwZW5jZXIiLCJpYXQiOjE1Njk2ODU2MjYsInB1cnBvc2UiOiJpZCJ9.CxYFrors4MkxaRHs6ul7Qb_E17LJ2OXJacQrsLf-3fYfbWHejKqZ3Zz-Aoi8klvPGIXQb6ciQHwO8oQRo-ttaRdK1w9D5HCNcveLplyrELWInYdLHJfhEYB_Yz0Xsu9slBwebJ2fYYhl2fu6macYoI7J4OgLcFPHbDSJNaSLvz_JhmjGXmY1rU7Dj6w9wyKRZQSWmS_GIM4G06AIV5kWvicprUjUZicXUn4qNhog6N13gXLCvh2b9PiFXO2T-hMLwx5ERKHBrHqLBF8Sc7eV6oMSMIw8mGYfnwq3yg5B0jxrZtFwyjonZWfkh9L4tghnX8ZrY-jBV_jSnAgiSouilw`

This causes an error in the OpenID login module though because it's assumed to be only a string.

**Comment by lachlan-roberts** [comment]
With PR #4135 we are now handling validation with multiple audience claims.
