### ISSUE TITLE
Impossible to use wildcards in IP addresses to configure virtual hosts

### ISSUE THREAD

**Issue by gouessej** [eclipse/jetty.project#4137]
Hello

When I want to access my website from my local network, I have to write something like this:
```
<Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>192.168.1.10</Item>
      <Item>192.168.1.11</Item>
      <Item>192.168.1.12</Item>
      <Item>192.168.1.13</Item>
    </Array>
  </Set>
```

Actually, there are lots of possible addresses in the range [192.168.1.10, 192.168.1.255].

When I tried that, it had no effect:
```
<Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>192.168.1.*</Item>
    </Array>
  </Set>
```

Is there another mean to obtain the same result without having to enter more than 200 IP addresses?

**Comment by gregw** [comment]
This is not something our virutal host mechanism currently supports.
We do support * wild card, but only for `*.domain.name` style matches.

Any solution would need to handle IPv6 as well as simple IPv4 examples.
You can probably do something using our `InetAddressSet` and overriding the `ContextHandler.checkVirtualHost` method.

Another better solution would be to have a extra connector that only listens on the local network interface and then you use `'@connectorname` as a virtual host to make a context accept requests from that connector.

**Comment by gouessej** [comment]
I've modified the setting of my residential gateway in order to get a static private IP address for my low-energy server so that I don't have to enter all possible IP addresses. Thank you anyway. Supporting 0.0.0.0 and its IPv6 equivalent would have been useful in this case too.

**Comment by joakime** [comment]
Sounds like you really just wanted the `InetAccessHandler` to limit the IP's that could access your server. 
Which supports plain InetAddress definitions: simple single address, address/CIDR, and address-address (range).

**Comment by gouessej** [comment]
@joakime Thank you, I'll try your suggestion:
[example](https://github.com/nddipiazza/jetty.project/blob/c2cf8ee78954ea5bfcf809237a9130e268168c7f/jetty-server/src/main/config/etc/jetty-inetaccess.xml)

I have to use a more recent version of Jetty first, shame on me.
