### ISSUE TITLE
OpenID module should use HttpClient instead of HttpURLConnection

### ISSUE THREAD

**Issue by travisspencer** [eclipse/jetty.project#4138]
The new OpenID Connect login module should use the Jetty HttpClient instead of HttpURLConnection when calling to various endpoints of the OpenID Connect Provider (e.g., the token and metadata endpoints and perhaps others in the future like WebFinger). There are many reasons for this, but some include:

* Async requests
* Possible to configure client-side thread-pool (names and size e.g.)
* Ability to customize key stores (for mutual TLS)
* Possibility to configure trust anchors (helpful when the OP uses a self-signed cert or one not signed by a CA in the JVM)
* Calling the OP might require proxy authentication 
* A client-side connection pool will be more performant and the Jetty HttpClient makes this OOTB

**Comment by travisspencer** [comment]
I have implemented this, but I need PRs #4134, #4133, #4132, and #4131 merged first. Otherwise, there's a lot of conflicts.

**Comment by gregw** [comment]
Perhaps share the thread pool of the server to keep impact small
