### ISSUE TITLE
Warning: CompressExtension: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by ansf** [eclipse/jetty.project#4140]
Hi,

we are using jetty (9.4.20) as a websocket backend for our mobile (web) app. We are seeing quite a lot of these warnings in our logs.
Can you help us understand if this is likely a problem with our implementation (server / client) or can we safely ignore this warning?

Thank you!

```
org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension: java.nio.channels.ClosedChannelException at
org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:109) at
org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:514) at
org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextOutgoingFrame(AbstractExtension.java:155) at
org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextOutgoingFrame(PerMessageDeflateExtension.java:123) at
org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.access$1100(CompressExtension.java:44) at
org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.compress(CompressExtension.java:591) at
org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.deflate(CompressExtension.java:488) at
org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.process(CompressExtension.java:468) at
org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) at
org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) at
org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.outgoingFrame(CompressExtension.java:244) at
org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:400) at
org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) at
org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) at
org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:277) at
org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:306) at
org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame(WebSocketRemoteEndpoint.java:240) at
org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendStringByFuture(WebSocketRemoteEndpoint.java:403) at
org.eclipse.jetty.websocket.jsr356.AbstractJsrRemote.sendObjectViaFuture(AbstractJsrRemote.java:125) at
org.eclipse.jetty.websocket.jsr356.JsrAsyncRemote.sendObject(JsrAsyncRemote.java:84) at
...
```

**Comment by lachlan-roberts** [comment]
@ansf it looks like you are trying to send frames after the websocket has already been closed.

You are notified of the websocket close through the websocket `onClose()` and `onError()`, if you send anything after this the send will fail.

**Comment by ansf** [comment]
@lachlan-roberts thank you for having a look! 👍 

you are probably right with your assumption. we will fix it in our code.

**Comment by fquirin** [comment]
Just adding a little info that helped me when I faced the same error:

If you close a session gracefully (`Session.close()`) then the `.isOpen()` check will remain true until the server/client confirmation was received meaning you cannot use this to prevent further messages to the same session right after the close request.
I added an additional property 'isSessionClosing' to the parent class (User in my case) and set this to 'true' to prevent any further messages.

**Comment by lachlan-roberts** [comment]
> If you close a session gracefully (Session.close()) then the .isOpen() check will remain true until the server/client confirmation was received meaning you cannot use this to prevent further messages to the same session right after the close request.

This may be true of Jetty 9.4 but in Jetty-10+ the behaviour of this method has been changed, `Session.isOpen()` now returns true only if frames can be sent, so after calling `Session.close()`, `isOpen()` will return false.

**Comment by fquirin** [comment]
Good to know ^^
