### ISSUE TITLE
OSGi - Install Jetty 9.4.20.v20190813 on Eclipse 2019-09

### ISSUE THREAD

**Issue by ferr0r** [eclipse/jetty.project#4155]
Hello, guys!

I catch an error, that I can't resolve.

I download *Jetty-bundles-repository-9.4.20.v20190813*.zip from *https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/*

I download *Eclipse IDE for Java Developer 2019-09 R* from eclipse.org.

Now I try to install Jetty on that Eclipse and get error:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Jetty - Bundles: all the jetty bundles 9.4.20.v20190813 (org.eclipse.jetty.bundles.f.feature.group 9.4.20.v20190813)
  Missing requirement: Jetty :: Servlet Annotations 9.4.20.v20190813 (org.eclipse.jetty.annotations 9.4.20.v20190813) requires 'java.package; javax.annotation [1.3.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Jetty - Bundles: all the jetty bundles 9.4.20.v20190813 (org.eclipse.jetty.bundles.f.feature.group 9.4.20.v20190813)
    To: org.eclipse.equinox.p2.iu; org.eclipse.jetty.annotations [9.4.20.v20190813,9.4.20.v20190813]
```	
I found *javax.annotation-api-1.3.2* on Maven Central, put it in *plugins* dir and write about bundle in configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
`javax.annotation-api,1.3.2,plugins/javax.annotation-api_1.3.2.jar,4,false`

Start Eclipse and in Installation details i see, that OSGI load this bundle:
`javax.annotation-api (1.3.2) "javax.annotation API" [Resolved]`

But this doesn't help, the error remained.

So i have a question: how can I install one of the last version of Jetty on one of the last version of Eclipse?

**Comment by CDerksen** [comment]
Hi There!

I have a similar problem defining my target platform with the p2 repository of jetty (http://download.eclipse.org/jetty/updates/jetty-bundles-9.x) with version 9,4.21.

After I added the Jetty update-site in the target editor, the following error message occurs:
![JettyTargetPlatformError](https://user-images.githubusercontent.com/29704527/66512464-4cdf0d80-ead9-11e9-845a-b532ab7b7715.png)

Searching in available repositories, I only could find the mentioned javax.annotation bundle in the Orbit repository, but there version 1.2 is the latest available one and the error asks for v1.3 - v2.0.

What to do to resolve this problem and get the target platform work ?

Thanks in advance

**Comment by ferr0r** [comment]
I found a workaround!

I create bundle **bundle1**. Put into these libs:
1. el-api.jar
2. jasper.jar
3. javax.annotation-api-1.3.2.jar
4. javax.transaction-api-1.3.jar
5. jsp-api.jar
6. tomcat-juli-8.5.46.jar
7. tomcat-util-scan.jar
8. websocket-api.jar

In MANIFEST-MF export packages:

1. javax.annotation;version="1.3.2",
2. javax.annotation.security;version="1.3.2",
3. javax.annotation.sql;version="1.3.2",
4. javax.el;version="3.0.0",
5. javax.servlet.jsp;version="2.3.0",
6. javax.servlet.jsp.el;version="2.3.0",
7. javax.servlet.jsp.resources;version="2.3.0",
8. javax.servlet.jsp.tagext;version="2.3.0",
9. javax.transaction;version="1.1.0",
10. javax.websocket;version="1.0.0",
11. javax.websocket.server;version="1.0.0",
12. org.apache.jasper.servlet;version="8.5.40",
13. org.apache.juli.logging;version="8.5.40",
14. org.apache.tomcat.util.descriptor.tld;version="8.5.40"

Create feature **feature1**. Put bundle1 into.
Create update site. Put feature1 into. Build it.

In the **Install new software** dialog add my update site, click **Contact all update sites during install to find required software**.
After that select Jetty update site and Jetty installs. But I don't understand how to work with it. I assume that i can select new Jetty in Jetty Webapp, but not.

So I can install it but I don't understand how to use it.

**Comment by janbartel** [comment]
The osgi bundles has never included any of the 3rd party dependencies, we assume that you will either already have them installed in your environment, or will install them. I'll close this issue.
