### ISSUE TITLE
Spelling mistakes in the very beginning of the section "Aliased Files and Symbolic links"

### ISSUE THREAD

**Issue by gouessej** [eclipse/jetty.project#4160]
Hello

I think that I've found some spelling mistakes [here](https://www.eclipse.org/jetty/documentation/current/serving-aliased-files.html):

> Web applications will often serve**r** static content from the file system provided by the operating system running underneath the JVM. However because file systems often implement multiple aliased names for the same file, then security constraints and other servlet URI space mappings **my** inadvertently be bypassed by aliases.

I'd rather write:

> Web applications will often serve static content from the file system provided by the operating system running underneath the JVM. However, because file systems often implement multiple aliased names for the same file, then security constraints and other servlet URI space mappings may inadvertently be bypassed by aliases.

I'm not a native speaker, please let me know whether I'm completely wrong.

**Comment by sbordet** [comment]
@gouessej you are correct. Willing to issue a PR for this issue? Thanks!

**Comment by gouessej** [comment]
@sbordet Done: https://github.com/eclipse/jetty.project/pull/4162

I just have to fix something about intellectual property :s

**Comment by gouessej** [comment]
Fixed by this pull request: https://github.com/eclipse/jetty.project/pull/4187
