### ISSUE TITLE
Investigate why java holds onto references for org.eclipse.jetty.server.HttpChannel$SendCallback so long?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4179]
A simple heap dump of a running server shows a lot of references to `org.eclipse.jetty.server.HttpChannel$SendCallback`.

Why are millions of instances of this class still present even when the server eventually reaches idle and no client connections are active?

**Comment by sbordet** [comment]
FTR the heap dump had 2.4M `HttpChannel$SendCallback` objects, of which only 1 was strongly reachable.

**Comment by gregw** [comment]
@joakime is it possible to retest anyway to check if #4180 reduced the number of weakly held sendCallbacks ?
