### ISSUE TITLE
Javax websocket server impl does not expose all required services as OSGi capabilities

### ISSUE THREAD

**Issue by rocketraman** [eclipse/jetty.project#418]
The jetty-websocket/javax-websocket-server-impl jar file does not expose the `osgi.serviceloader=javax.websocket.server.ServerEndpointConfig$Configurator` capability. This makes it unusable in an OSGi environment which uses the `ServiceLoader` mechnism to load the `org.eclipse.jetty.websocket.jsr356.server.BasicServerEndpointConfigurator` class.

Pull request forthcoming...

**Comment by joakime** [comment]
*bump* (where is the Eclipse IP check service?)
