### ISSUE TITLE
Jetty hangs after thread blocked in SharedBlockingCallback.block() called by HttpOutput.close

### ISSUE THREAD

**Issue by cztomek** [eclipse/jetty.project#4190]
Hi, this started happening on and off after we migrated from 9.4.8 to 9.4.21.

The entire HTTP stack is blocked - no new requests can be served.
After calling interruptThread() on the thread that is blocked on SharedBlockingCallback.block() the server works back again.

[Jetty9.4.21-blocked-jettydump.txt](https://github.com/eclipse/jetty.project/files/3725005/Jetty9.4.21-blocked-jettydump.txt)
[Jetty9.4.21-blocked-treaddump.txt](https://github.com/eclipse/jetty.project/files/3725010/Jetty9.4.21-blocked-treaddump.txt)

**Comment by sbordet** [comment]
Good catch, it's a regression introduced by #3806. Working on a test case and fix. Thanks!

**Comment by sbordet** [comment]
@cztomek would you be able to build Jetty and try the code in PR #4200 to see if the fix works for you?

**Comment by cztomek** [comment]
@sbordet Thx for a swift action. I can try it out in a few days after our test environment is freed. I don't have strict scenario to reproduce this case but it reared its ugly head daily so after a couple of days it should safe to confirm the upshot.

**Comment by sbordet** [comment]
@cztomek thanks, let us know as soon as you can - we are about to cut a release.
