### ISSUE TITLE
Increase GzipHandler minGzipSize default value

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4191]
While working Issue #4188 it was discovered that any minGzipValue below 23 will produce more bytes then the size of the content being returned.

Here's a breakdown of a Servlet producing an array of bytes all of the same value (maximally compressible content), and the resulting compressed GzipHandler size of bytes.

| Servlet Produced Bytes | GzipHandler Produced Bytes | Compression Is Better |
| ------------------------------- | --------------------------------------- | ----------------------------- |
| 0 | 20 |  :x: (ugly) |
| 1 | 21 | :x: |
| 2 | 22 | :x: |
| 3 | 23 | :x: |
| 4 | 23 | :x: |
| 5 | 23 | :x: |
| 10 | 23 | :x: |
| 15 | 23 | :x: |
| 16 | 23 | :x: |
| 20 | 23 | :x: |
| 21 | 23 | :x: |
| 22 | 23 | :x: |
| 23 | 23 | :heavy_minus_sign: (break-even) |
| 24 | 23 | :heavy_check_mark: |
| 25 | 23 | :heavy_check_mark: |
| 26 | 23 | :heavy_check_mark: |
| 27 | 23 | :heavy_check_mark: |
| 50 | 24 | :heavy_check_mark: |
| 100 | 24 | :heavy_check_mark: |
| 300 | 25 | :heavy_check_mark: |
| 500 | 26 | :heavy_check_mark: |

I propose that the default `GzipHandler.setMinGzipSize(int)` should be 23 by default, and never allow users to set a size smaller then 23.

**Comment by sbordet** [comment]
I have doubts that 23 is the even for _every_ payload.
The test goes for a best case of an array with all the same characters, but what if it's rather some less compressible content?
If that's correct, then perhaps rather than trying we should look at the gzip format and derive from that the theoretical minimum. I'm sure someone has done it already and can be looked up.

**Comment by joakime** [comment]
There's really 2 issues here:

1. Why are we compressing 0 bytes of input data?
2. When does the compressed output actually benefit in bytes saved from the input data?

What I've learned:

* For all input data of 23 bytes _or fewer_ there's no benefit, not even in the best case scenario.
* Our current default minimum is 16 bytes
* Our current configurable minimum is 0 bytes

I hoped to address the 3 things learned, and both of the issues above.

**Comment by joakime** [comment]
I went down this path as it was hinted that Issue #4188 could (possibly) be due to small configurations.
And I had hit similar issues on the permessage-deflate implementation side, when dealing with small inputs, small buffers, and SYNC_FLUSH.
Even wrote a stackoverflow question about it - https://stackoverflow.com/questions/31861983/deflater-deflate-and-small-output-buffers
(Answered by the man Mark Adler himself)
And that one spawned a JDK bug report at https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8133170

**Comment by gregw** [comment]
I would be fine with changing default to 32 and producing a warning if somebody tries to set it smaller than 23.  Note we should still allow it as some might have clients that can only handle gzipped responses.
However, it may be worthwhile to throw an IAE if the buffer size is ever set to < 32

**Comment by joakime** [comment]
Closing as PR #4192 was merged.
