### ISSUE TITLE
Issue with Http2 Server on Java 8

### ISSUE THREAD

**Issue by gopal229** [eclipse/jetty.project#4199]
I m using Jetty 9.4.21 to build Http2 Server with SSL which is running on Java 8. 

I m getting the below error when client is trying to connect to the server

java.lang.IllegalStateException: Connection rejected: No ALPN Processor for sun.security.ssl.SSLEngineImpl from [o.eclipse.jetty.alpn.conscrypt.server.ConscryptServerALPNProcessor@2814b525]

I followed the instructions in https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-conscrypt and included 'jetty-alpn-conscrypt-server' and 'org.conscrypt:conscrypt-openjdk-uber' in the classpath.

I m building SslContextFactory using SslContext 

 SslContextFactory buildSslContextFactory() throws Exception {
    SslContextFactory sslContextFactory = new SslContextFactory.Server();
    sslContextFactory.setSslContext(SSLUtils.getTlsContext());
//    sslContextFactory.setKeyStore(SSLUtils.buildKeyStore());
//    sslContextFactory.setKeyStorePassword("test");
    sslContextFactory.setIncludeCipherSuites(SSLUtils.getCipherSuites());
    sslContextFactory.setIncludeProtocols(SSLUtils.getSecureProtocols());
    Security.addProvider(new OpenSSLProvider());
    sslContextFactory.setProvider("Conscrypt");
    sslContextFactory.setCipherComparator(HTTP2Cipher.COMPARATOR);
    return sslContextFactory;
  }

Instead of SslContext if I set KeyStore then I m not seeing an issue. The problem seems to be only with SslContext. I would like to use SslContext as we have custom certificate verification logic.

After googling a bit I added 'Security.insertProviderAt(new OpenSSLProvider(), 1);' at the start of the application and it started working with SslContext. I can't do this in my production application.

More details in https://stackoverflow.com/questions/58378276/jetty-http2-server-is-not-working-on-java-8

**Comment by sbordet** [comment]
The problem is that `SSLUtils` very likely uses the JDK TLS implementation, not Conscrypt, to create SSLEngine instances.

As you can see from the error, the SSLEngine is `sun.security.ssl.SSLEngineImpl`, not `org.conscrypt.ConscryptEngine`.

I guess the problem is `SSLUtils` that does not take into account different providers, and only works with the first one - that's why if you insert Conscrypt in first position it works.
