### ISSUE TITLE
Regression in Jetty 9.4.21: 304 response with Content-Length fails, not conform to RFC7230

### ISSUE THREAD

**Issue by sspi** [eclipse/jetty.project#4208]
Since Jetty 9.4.21, a 304 response with Content-Length in headers fails in class org.eclipse.jetty.server.HttpChannel and throws "insufficient content written".

But https://tools.ietf.org/html/rfc7230#section-3.3.2 explicitly says it is allowed:
   A server MAY send a Content-Length header field in a 304 (Not
   Modified) response to a conditional GET request (Section 4.1 of
   [RFC7232]);

In Jetty 9.4.20 the 304 response status shortcuts this isContentComplete() check.

**Comment by gregw** [comment]
Can you please give us the actual stack generated from the throw

**Comment by sspi** [comment]
In my case response is not already commited, the server emit `_response.sendError(HttpStatus.INTERNAL_SERVER_ERROR_500, "insufficient content written");` at org.eclipse.jetty.server.HttpChannel l516

With a breakpoint at this line, I have:

```Thread [qtp2058135834-29] (Suspended (breakpoint at line 516 in HttpChannel))	
	HttpChannelOverHttp(HttpChannel).handle() line: 516	
	HttpConnection.onFillable() line: 268	
	AbstractConnection$ReadCallback.succeeded() line: 311	
	AbstractEndPoint$1(FillInterest).fillable() line: 103	
	ChannelEndPoint$2.run() line: 117	
	EatWhatYouKill.runTask(Runnable) line: 336	
	EatWhatYouKill.doProduce(boolean) line: 313	
	EatWhatYouKill.tryProduce(boolean) line: 171	
	EatWhatYouKill.run() line: 129	
	ReservedThreadExecutor$ReservedThread.run() line: 367	
	QueuedThreadPool.runJob(Runnable) line: 782	
	QueuedThreadPool$Runner.run() line: 914	
	Thread.run() line: 748	
```

**Comment by sspi** [comment]
A simple correction could be at org.eclipse.jetty.server.HttpChannel l510:

```java
if (!_request.isHead() && _response.getStatus()!=HttpStatus.NOT_MODIFIED_304 && !_response.isContentComplete(_response.getHttpOutput().getWritten()))

```

**Comment by gregw** [comment]
@sspi strangely enough that simple correction is not enough for me as I still get an exception thrown out of the generator.... however I think I have a fix for that too plus some tests.  Stand by for a PR...

**Comment by joakime** [comment]
PR #4211 opened
