### ISSUE TITLE
Unused TLS connection is not closed in Java 11

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4209]
A client establishes a TCP connection to be used with the TLS protocol, but then it never send any bytes on that connection (not even the TLS `ClientHello`).

The server idle times out the connection and `SSLEngine.closeOutbound()` is called from `shutdownOutput()`.
In Java 8 this results in the SSLEngine state to remain in `NOT_HANDSHAKING`, while in Java 11+ this results in `NEED_UNWRAP`.

Since we are trying to gently close the connection (because of the idle timeout), we expect that the call to `closeOutbound()` generates the TLS `close_notify` message and therefore a `flush()` is required.

Calling `flush()` behaves differently because the `SSLEngine` state is different.
In Java 8 it calls `wrap()`, which produces 0 bytes and result `CLOSED`, which causes a network `FIN`.
In Java 11 it calls `fill()`, which reads 0 from the network, call `unwrap()` which produces 0 bytes and a `BUFFER_UNDERFLOW` result, therefore never sending a network `FIN`.

In Java 11, nothing is sent to the client: neither the `close_notify` nor the `FIN`, so the connection remains in the pool and may be used for other requests.

**Comment by sbordet** [comment]
PR #4210.

**Comment by jingke** [comment]
@sbordet recently we found the jetty-client library also encounter some TLS connection was closed from client side due to this change when fill() encounter netFilled == -1. Do you think this is only work for side?

>                             // Workaround for Java 11 behavior.
                            if (netFilled < 0 && isHandshakeInitial() && BufferUtil.isEmpty(_encryptedInput))
                                closeInbound();

**Comment by sbordet** [comment]
@jingke please open a new issue.
Do you have a reproducible test case?
