### ISSUE TITLE
JSessionId in Redirect URL

### ISSUE THREAD

**Issue by jd-carroll** [eclipse/jetty.project#421]
I have a spring web app running in a Jetty Container [jetty-all-9.0.0.v20130308.jar] --> Yes I know, I see how old our version is, but it's out of my hands. (Spring version 3.2.13)

For the web app, authentication happens through a URL redirect from Spring Security.  (It works where the app redirects to the auth server, which then redirects back to the app server with the appropriate cookie).

When the incoming request is redirected to the auth server, I'm seeing a `jsessionid` in the redirect url.  The incoming url will look something like:
```
http://server-name.company.com:14470/context/path/to/rest/endpoint
```
And the redirect url will look something like:
```
https://auth-server-name.company.com/authenticate/encdefault.asp;jsessionid=5c362r3hvcuk1ho2frvnyz671?location=http%3A%2F%2Fserver-name.company.com%3A14470%2Fcontext%2Fpath%2Fto%2Frest%2Fendpoint
```

The issue is the jsessionid encoded in the redirect url:
```
;jsessionid=5c362r3hvcuk1ho2frvnyz671
```

When I deploy the same war file on Tomcat, I do not see the jsessionid in the redirect url.  

Is there something in the Jetty code base that is creating this jsessionid?  If so, how am I able to remove that on the out-going redirect?

**Comment by janbartel** [comment]
Have you tried setting the context init param
"org.eclipse.jetty.servlet.CheckingRemoteSessionIdEncoding" to "true"? IIRC
if that is true and the url being encoded is a remote host then the
jsessionid won't be encoded.

Jan

On 10 March 2016 at 22:33, Joseph Carroll <notifications@github.com> wrote:

> I have a spring web app running in a Jetty Container
> [jetty-all-9.0.0.v20130308.jar] --> Yes I know, I see how old our version
> is, but it's out of my hands. (Spring version 3.2.13)
>
> For the web app, authentication happens through a URL redirect from Spring
> Security. (It works where the app redirects to the auth server, which then
> redirects back to the app server with the appropriate cookie).
>
> When the incoming request is redirected to the auth server, I'm seeing a
> jsessionid in the redirect url. The incoming url will look something like:
>
> http://server-name.company.com:14470/context/path/to/rest/endpoint
>
> And the redirect url will look something like:
>
> https://auth-server-name.company.com/authenticate/encdefault.asp;jsessionid=5c362r3hvcuk1ho2frvnyz671?location=http%3A%2F%2Fserver-name.company.com%3A14470%2Fcontext%2Fpath%2Fto%2Frest%2Fendpoint
>
> The issue is the jsessionid encoded in the redirect url:
>
> ;jsessionid=5c362r3hvcuk1ho2frvnyz671
>
> When I deploy the same war file on Tomcat, I do not see the jsessionid in
> the redirect url.
>
> Is there something in the Jetty code base that is creating this
> jsessionid? If so, how am I able to remove that on the out-going redirect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipse/jetty.project/issues/421>.
>



-- 
Jan Bartel <janb@webtide.com>
www.webtide.com
*Expert assistance from the creators of Jetty and CometD*

**Comment by gregw** [comment]
Also Jetty checks to see if there is a session cookie (even an invalid one), if there is then it knows cookies are supported and will not encode the jsessionid in the URL.

**Comment by jd-carroll** [comment]
:+1: Adding the following worked:
```
    <context-param>
      <param-name>org.eclipse.jetty.servlet.CheckingRemoteSessionIdEncoding</param-name>
      <param-value>true</param-value>
    </context-param>
```

Should I be concerned about any other impacts outside of this issue?

**Comment by joakime** [comment]
Closing
