### ISSUE TITLE
extraClasspath - Not working in Jetty 9.4.20.v20190813

### ISSUE THREAD

**Issue by Deepak-D** [eclipse/jetty.project#4212]
Setting **extraClasspath** in context xml is not working in **Jetty 9.4.20.v20190813**. 404 Not Found - problem accessing the REST call. No jetty logs describing the error.

Here is how I use context xml for mywebapp

```xml
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/mywebapp/</Set>
  <Set name="war"><Property name="jetty.webapps" default="."/>/mywebapp.war</Set>
  <Call name="setInitParameter">
    <Arg>org.eclipse.jetty.jsp.precompiled</Arg>
    <Arg>true</Arg>
  </Call>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>@sslConnector</Item>
      <Item>@httpConnector</Item>
    </Array>
  </Set>
  <Set name="extraClasspath">
    ../myJar.jar
  </Set>
</Configure>
```

**Note: Previously, we were using Jetty 9.4.9.v20180320 and the above setup was working fine.**

Also, I'm not sure as this problem is because of **extraClasspath**.

Any help would be appreciated!

**Comment by joakime** [comment]
non-absolute / relative paths are always a bad idea.

You should prefix that with a known path or path property.

Some thoughts ...

* Use `jetty.webapps` (path) property (like you did in the `<Set name="war">`)
* Use `jetty.base` (path) property.

Try this instead (assuming the jar is in your `${jetty.base}` directory) ...

``` xml
  <Set name="extraClasspath">
    <Property name="jetty.base"/>/myJar.jar
  </Set>
```

**Comment by janbartel** [comment]
There's really not enough information to go on in this report. Turn on debug logging to see more jetty output, and also try @joakime's suggestion.

**Comment by Deepak-D** [comment]
Thanks for getting back to me!

FYI, I have my environment variable **JETTY_BASE** for jetty base directory and I tried to invoke this for **extraClasspath** configuration in my context xml using **SystemProperty** but some how **'null'** is added right after mt-base. For example, let say E:\jetty\mt-base is my value of the environment variable JETTY_BASE, I tried below

```
<Set name="extraClasspath">
    <SystemProperty name="JETTY_BASE"/>/myJar.jar
</Set>
```
Jetty log says it couldn't find myJar.jar. Then I looked into the directory path and this turned out to be **E:\jetty\mt-base\null/myJar.jar**. I'm not sure how this null is appending at the end of system property value E:\jetty\mt-base.

Anyways, I will try above two suggestions and get back to you.
