### ISSUE TITLE
Jetty-osgi-alpn package is empty.

### ISSUE THREAD

**Issue by smatei** [eclipse/jetty.project#422]
I could not find the ALPN class referenced in the Jetty http2 package. The osgi-alpn packages are empty

http://central.maven.org/maven2/org/eclipse/jetty/osgi/jetty-osgi-alpn/9.3.7.v20160115/jetty-osgi-alpn-9.3.7.v20160115-sources.jar
http://central.maven.org/maven2/org/eclipse/jetty/osgi/jetty-osgi-alpn/9.3.7.v20160115/jetty-osgi-alpn-9.3.7.v20160115.jar

Where can I find it?

**Comment by smatei** [comment]
Found it here

http://mvnrepository.com/artifact/org.eclipse.jetty.alpn/alpn-api/1.0.0

**Comment by sbordet** [comment]
That is a pretty old version, see here instead: http://search.maven.org/#search|gav|1|g%3A%22org.eclipse.jetty.alpn%22%20AND%20a%3A%22alpn-api%22
