### ISSUE TITLE
start.jar fails to work as documented when not run from jetty.home

### ISSUE THREAD

**Issue by mjog** [eclipse/jetty.project#4220]
The [documentation](https://www.eclipse.org/jetty/documentation/current/startup-base-and-home.html) (the very last section of that page) suggests running Jetty from the `jetty.base` dir and it will discover `jetty.home` based on the location of start.jar, however this is not working for me when I start it with an XML config file:

```
mjog@blanchefort:~/my-project$ java -jar ~/.local/jetty-distribution-9.4.21.v20190926/start.jar etc/jetty-config-dev.xml 
ERROR : Nothing to start, exiting ...

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
mjog@blanchefort:~/my-project$ ls etc/jetty-config-dev.xml 
etc/jetty-config-dev.xml
mjog@blanchefort:~/my-project$ 
```

Jetty does start fine if run from `jetty.home` and providing an absolute path to the XML config, however that breaks the relative paths in the config file.

**Comment by janbartel** [comment]
This is working for me. 

I made a new base directory called` my-base` in `/tmp`. 
I created an empty file in` my-base/goo/foo.xml`.
I did `java -jar ~/src/jetty-eclipse/jetty-9.4.x/jetty-distribution/target/distribution/start.jar --add-to-startd=server,http,webapp,deploy` from` /tmp/my-base`.
I then did `java -jar ~/src/jetty-eclipse/jetty-9.4.x/jetty-distribution/target/distribution/start.jar goo/foo.xml`.
Output is as expected with an empty file:
```
2019-10-19 12:33:18.320:INFO::main: Logging initialized @527ms to org.eclipse.jetty.util.log.StdErrLog
2019-10-19 12:33:18.555:WARN:oejx.XmlParser:main: FATAL@null line:1 col:1 : org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```

Try using `java -jar <start-jar-parent-dir>/start.jar --dry-run` to see what your command line looks like, and ensure that your base directory has the correct modules enabled.

**Comment by gregw** [comment]
Is your directory really a base dir?  Does it have a start.ini or a start.d?

Try running:
```
java -jar ~/.local/jetty-distribution-9.4.21.v20190926/start.jar --create-startd --add-to-start=server
```
just once, and that should make it able to find something to start

**Comment by mjog** [comment]
> Is your directory really a base dir? Does it have a start.ini or a start.d?

It's the base directory for the source for a project, so no it doesn't have those files.

> Try running:
> 
> ```
> java -jar ~/.local/jetty-distribution-9.4.21.v20190926/start.jar --create-startd --add-to-start=server
> ```
> 
> just once, and that should make it able to find something to start

I'm passing it configuration on the command line by `etc/jetty-config-dev.xml`, and I'd rather do that than litter the project's source tree with tooling artifacts. The CLI help given by start.jar indicates this should work:

```
Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
```

**Comment by gregw** [comment]
You still need at least one module to build the classpath. Try:
```
java -jar ~/.local/jetty-distribution-9.4.21.v20190926/start.jar --module=server etc/jetty-config-dev.xml
```

**Comment by mjog** [comment]
Thanks, that worked. Might be good to update the docs along those lines?
