### ISSUE TITLE
clean up redirect code calculation for OpenIdAuthenticator

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#4236]
When doing redirects in the openid module, we do a calculation of what redirect code to use. 

```java
int redirectCode = (baseRequest.getHttpVersion().getVersion() < HttpVersion.HTTP_1_1.getVersion() 
    ? HttpServletResponse.SC_MOVED_TEMPORARILY : HttpServletResponse.SC_SEE_OTHER);
baseResponse.sendRedirect(redirectCode, URIUtil.addPaths(request.getContextPath(), _errorPage));
```

Is the redirect code calculation really necessary? If so, then it should be in a utility method.

**Comment by travisspencer** [comment]
We should always redirect back to the RP using a 303 if we can. That isn't supported by HTTP 1.0 though, so the condition is good. For a rational of why 303 should always be used, see https://blog.acolyer.org/2016/11/07/a-comprehensive-formal-security-analysis-of-oauth-2-0/ and https://sec.uni-stuttgart.de/_media/publications/FettKuestersSchmitz-CCS-2016.pdf

**Comment by lachlan-roberts** [comment]
@travisspencer Interesting read thanks. Seems to me like using the 302 in the case of HTTP 1.0 is still bad as the POST request may be redirected to the RP. Maybe we should only allow use of this with HTTP/1.1 or greater and only send 303's which will always change the method to GET.

**Comment by travisspencer** [comment]
I highly doubt that anyone is building a 1.0 HTTP web app ATM and adding support for OIDC, so I think that's OK. Alternatively, we could warn on 1.0 and use 302.
