### ISSUE TITLE
9.4.21 introduces invalid json error response from ErrorHandler

### ISSUE THREAD

**Issue by gbrehmer** [eclipse/jetty.project#4243]
https://github.com/eclipse/jetty.project/blob/bde86467f4e5df595773ab11ed5e80c615b741f3/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L430

generated json has missing quotes ("keys") and invalid comma after last value (in both cases, if cause exists or if cause is null)

**Comment by joakime** [comment]
great.
and we *JUST* released 9.4.22.v20191022

**Comment by olamy** [comment]
pr #4249
