### ISSUE TITLE
Jetty server idle timeout seems not correctly enforced

### ISSUE THREAD

**Issue by nhenneaux** [eclipse/jetty.project#4246]
I am not able to use the idle timeout so that the server stops the processing after this timeout.

I have reproduced using a [simple project](https://github.com/nhenneaux/jersey-http2-jetty-connector/pull/22) and a sleep inside the server side of `1s` while the idle timeout is configured to `100ms`.

I have tried to use the methods `org.eclipse.jetty.server.ServerConnector#setIdleTimeout`, `org.eclipse.jetty.server.HttpConfiguration#setIdleTimeout` and `org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory#setStreamIdleTimeout` but none has the expected behavior.

I am using latest Jetty `9.4.22.v20191022` and tested on OpenJDK 8-13.

Could you tell me if I am missing something or if there is a bug inside Jetty?

**Comment by joakime** [comment]
Do you have a "simple" project that doesn't use Jersey?

**Comment by nhenneaux** [comment]
Any reason why it would make a difference ?

**Comment by joakime** [comment]
Isolate Jetty, don't bring in other libraries.
Demonstrate that the issue is in Jetty, not the other libraries.

Your simple project is actually quite complex.
There's no information on what features of the Servlet spec are in use with your project.
Example: if the Async processing features are used (there's no indication in your project what parts of the servlet spec are in use), then the connection idle timeout is superceded, as mandated by Servlet spec.

**Comment by sbordet** [comment]
@nhenneaux you are setting a 100 ms idle timeout, but then inside the REST service, which is called from a Servlet, you sleep for 1000 ms.
The Servlet Specification mandates that idle timeouts are ignored while a thread is dispatched to the Servlet and not doing I/O.
In your project you have a blocking case, but the same applies if you have asynchronous processing of the request (i.e. you called `request.startAsync()`).

**Comment by nhenneaux** [comment]
Thanks @sbordet for your answer.

It means the idle timeout is triggered if the Servlet is doing IO or I missed something ?

I have tried with this implementation without success.
```
@GET
    @Path("pingWithSleep")
    public long pingWithSleep(@QueryParam("sleepTimeInMilliseconds") long sleepTimeInMilliseconds) {
        long start = System.currentTimeMillis();
        long counter = 0;
        while ( System.currentTimeMillis()-start < sleepTimeInMilliseconds) {
            counter++;
        }
        System.out.println(counter);
        return sleepTimeInMilliseconds;
    }
```
I also tried doing FS operation without success. 
```
@GET
    @Path("pingWithSleep")
    public long pingWithSleep(@QueryParam("sleepTimeInMilliseconds") long sleepTimeInMilliseconds) throws IOException {
        long start = System.currentTimeMillis();
        long counter = 0;
        while (System.currentTimeMillis() - start < sleepTimeInMilliseconds) {
            counter++;
            final java.nio.file.Path tempFile = Files.createTempFile("pingWithSleep", "tmp");
            final byte[] bytes = new byte[10_000];
            ThreadLocalRandom.current().nextBytes(bytes);
            Files.write(tempFile, bytes);
            Files.delete(tempFile);
        }
        System.out.println(counter);
        return sleepTimeInMilliseconds;
    }
```

I think I am missing something ?

Do you know if there is another way to limit the processing time on server side ?

**Comment by sbordet** [comment]
Sorry, by I/O I mean request/response I/O.

So if you are blocked in `ServletInputStream.read()` or `ServletOutputStream.write()` then the idle timeout will apply.

If you are (like your examples) within methods called from `Servlet.service()` and not doing Servlet I/O, then the idle timeout does not apply as per the Servlet Specification.
