### ISSUE TITLE
Cookie security attributes are going to mandated by Google Chrome

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4247]
See https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

Also the feedback at https://github.com/eclipse/jetty.project/issues/3040#issuecomment-546981764

We need to have a solution for the following:

* Web Apps using the Servlet Cookie API.
* Session Cookies created by Jetty.
* Http Client Cookie usage / behaviors?

**Comment by joakime** [comment]
For Session Cookies, we need to support a configuration for the `SameSite` attribute.

* Not Present
* `SameSite=None`
* `SameSite=Lax`
* `SameSite=Strict`

**Comment by blop** [comment]
Work is being done also on the servlet-api https://github.com/eclipse-ee4j/servlet-api/issues/175

**Comment by joakime** [comment]
Opened PR #4271

**Comment by gregw** [comment]
Note that to use sameSite cookies for  the session cookie, you can activate using web.xml (and STRICT/LAX/NONE in the comment):
```xml
  <session-config>
    <cookie-config>
      <comment>__SAME_SITE_STRICT__</comment>
    </cookie-config>
  </session-config>
```

**Comment by gregw** [comment]
I think we need to do more on this issue. Considering that [Chrome will soon ignore cookies without Same-Site](https://www.chromestatus.com/feature/5088147346030592), then it is not sufficient just to allow applications to specify Same-Site if they wish.  We need the ability to add the attribute to cookies created by existing code - ie the container needs to be able to set a default other than null

**Comment by gregw** [comment]
See also https://github.com/eclipse-ee4j/servlet-api/pull/271

**Comment by janbartel** [comment]
The samesite  attribute can now be set via a context default value. Thus, the samesite attribute will be present if it is either set explicitly, or there is a default value set for the context. According to the documentation links provided on this issue, chrome will use a default value of LAX if no samesite value is present in a cookie.
