### ISSUE TITLE
Http 2.0 clients cannot upgrade protocol in 9.4.22 release

### ISSUE THREAD

**Issue by tdanylchuk** [eclipse/jetty.project#4251]
Given:
Java 11 client with HTTP/2.0 protocol set 

When:
Calling jetty server with ```HTTP2CServerConnectionFactory``` 

Expected result:
HTTP 2.0 clients communicates with jetty via HTTP/2.0 protocol

Actual result:
HTTP 2.0 clients communicates with jetty via HTTP/1.1 protocol

Affected version
9.4.22

Investigation:
After change https://github.com/eclipse/jetty.project/commit/22f0cdde29a92cdc3326c07cd41d1c37b47467fd
Settings parser has been broken, more - https://github.com/eclipse/jetty.project/commit/22f0cdde29a92cdc3326c07cd41d1c37b47467fd#r35725542

**Comment by sbordet** [comment]
PR #4261.
