### ISSUE TITLE
Releases jetty

### ISSUE THREAD

**Issue by wheestermanstoyota** [eclipse/jetty.project#4252]
What is the release schema for Jetty?

- New fix- feature every n months (ex 9.4.20 - 9.4.21 - 9.4.22 - ....?
- New major release (9.4 --> 9.5)?  
- New major release (9.x --> 10.x)?  

Regards
Walter

**Comment by joakime** [comment]
The syntax (since around the year 1995) is `<servlet_support_version>.<major_version>.<minor_version>`

Where `servlet_support_version` is ...

* 7 is Servlet 2.4
* 8 is Servlet 3.0
* 9 is Servlet 3.1
* 10 is Servlet 4.0
