### ISSUE TITLE
How do I use Http2Client with a proxy?

### ISSUE THREAD

**Issue by smatei** [eclipse/jetty.project#426]
Hi,

I have run my first jetty http2 client example.

`HTTP2Client client = new HTTP2Client();    
    SslContextFactory sslContextFactory = new SslContextFactory();
    client.addBean(sslContextFactory);
    client.start();

    String host = "www.google.ro";
    String path = "?gws_rd=cr&ei=I5jmVsiYHuir6ATapLfYDA";
    int port = 443;

    FuturePromise<Session> sessionPromise = new FuturePromise<>();
    client.connect(sslContextFactory, new InetSocketAddress(host, port), new ServerSessionListener.Adapter(), sessionPromise);
    Session session = sessionPromise.get(30, TimeUnit.SECONDS);

    HttpFields requestFields = new HttpFields();
    requestFields.put("User-Agent", "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0");
    MetaData.Request metaData = new MetaData.Request("GET", new HttpURI("https://" + host + ":" + port + "/" + path), HttpVersion.HTTP_2, requestFields);
    HeadersFrame headersFrame = new HeadersFrame(metaData, null, true);
    final Phaser phaser = new Phaser(2);
    session.newStream(headersFrame, new Promise.Adapter<>(), new Stream.Listener.Adapter()
    {
        @Override
        public void onHeaders(Stream stream, HeadersFrame frame)
        {
            System.err.println(frame);
            if (frame.isEndStream())
                phaser.arrive();
        }

        @Override
        public void onData(Stream stream, DataFrame frame, Callback callback)
        {   
          byte[] bytes = new byte[frame.getData().remaining()];
          frame.getData().get(bytes);
          System.out.println("[" + stream.getId() + "] DATA " + new String(bytes));
          
            System.err.println(frame);
            callback.succeeded();
            if (frame.isEndStream())
                phaser.arrive();
            
            
        }

        @Override
        public Stream.Listener onPush(Stream stream, PushPromiseFrame frame)
        {
            System.err.println(frame);
            phaser.register();
            return this;
        }
    });

    phaser.awaitAdvanceInterruptibly(phaser.arrive(), 30, TimeUnit.SECONDS);

    client.stop();`

Now I need to run it through a web proxy server (usual squid). How do I run it? I did not fund any example.

Best Regards,
Stefan Matei

**Comment by sbordet** [comment]
In order to perform a HTTP request through a forward proxy, you may want to use `HttpClient`, not the lower-level `HTTP2Client`, because it provides an nicer API to set the proxy details.
See http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/client/HttpClient.html#getProxyConfiguration--

If you really need to use `HTTP2Client`, see https://github.com/eclipse/jetty.project/blob/master/jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/ProxyTest.java.

Be aware of #250, which is not yet implemented.

**Comment by smatei** [comment]
Hi Simone,

Thank you for this example.

It would be nice to use HttpClient with a setting (http1.0, http1.1, http2) that would transparently use the lower level implementation (in this case HTTP2Client). Would this be possible?

I really need a http2 java client library that can work with a proxy server. An alternative would be to use curl with http2 (curl+nghttp2), but I would rather have it in java (our workers are java).

Stefan Matei

**Comment by sbordet** [comment]
Unfortunately the switch of the transport at runtime is not implemented, so it won't be possible to change the transport based on the HTTP version of the request.
If you meant a static switch - set at beginning and not changing, you already have it (passing in the transport).

You should have no problems using `HttpClient` with HTTP/2 and a forward proxy.

Let us know if you succeed !

**Comment by smatei** [comment]
Hi Simone,

I did try to connect using the HttpClient through a proxy, I and run into the bug

https://github.com/eclipse/jetty.project/issues/408

I will try to get your fix and run it again. 

Can you please tell me how to set http2 in my code? That is tunnel a http2 connection through a http1.0 proxy connection (high level)?

`SslContextFactory sslContextFactory = new SslContextFactory();
HttpClient client = new HttpClient(sslContextFactory);
ProxyConfiguration proxyConfig = client.getProxyConfiguration();
HttpProxy proxy = new HttpProxy(new Origin.Address(proxyHost, proxyPort), true);
client.getAuthenticationStore().addAuthentication(new BasicAuthentication(new URI("https://" + proxyHost), "Proxy", user, password));
proxyConfig.getProxies().add(proxy);
client.start();
ContentResponse res = client.GET("https://www.google.com");
System.out.println(res.getStatus());
System.out.println(res.getContentAsString());
client.stop();`

Stefan Matei

**Comment by sbordet** [comment]
@smatei because you are targeting `https` servers, you will need #250 which is not implemented yet.
If you target `http` servers, the latest code (with the fix for #408) should work fine.

**Comment by smatei** [comment]
Hi Simone,

I successfully used OkHttpClient. I will check  jetty again when you implement the https connect.

Thanks for your  help.
Stefan Matei
