### ISSUE TITLE
WebSocketClient should not modify HttpClient idle timeout.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4262]
The WebSocketClient should not modify the internal HttpClient idle timeout directly.
Instead, the WebSocketClient should apply the Idle Timeout per request, leaving the HttpClient configured idle timeout alone.

**Comment by joakime** [comment]
The current implementation in Jetty 9.4.22 would modify a shared HttpClient, which is not ideal.

**Comment by sbordet** [comment]
@joakime what's the reason for this?

`WebSocketClient` and `HttpClient` share most if not all configuration, and having a single exception does not seem right.

That `WebSocketClient.setIdleTimeout()` delegates to `HttpClient.setIdleTimeout()` seems correct to me. Why it is not ideal?

**Comment by lachlan-roberts** [comment]
@sbordet the weird thing to me about this one is that `WebSocketClient.setIdleTimeout()` delegates to both the `WebSocketPolicy` and the `HttpClient`. If someone provided a shared `HttpClient` they may have only wanted to set it on the policy without changing the `HttpClient`.

To set it only on the WebSocket idleTimeout you could use `getPolicy()` but this is also removed in jetty-10 so you would need to do something like this.
```java
long httpClientIdleTimeout = getHttpClient().getIdleTimeout();
webSocketClient.setMaxIdleTimeout(idleTimeout);
getHttpClient().setIdleTimeout(httpClientIdleTimeout);
```

**Comment by sbordet** [comment]
@lachlan-roberts the use case of sharing a `HttpClient` with a `WebSocketClient`, but then wanting the `WebSocketClient` have different settings is for me, unrealistic.

Sure it is _possible_ but I would not complicate things for something that nobody uses.

Can you detail a realistic use case where you have the `HttpClient` used for HTTP request _concurrently_ with a `WebSocketClient` using also that `HttpClient` to make WebSocket requests, _and_ wanting a different configuration?

Just use 2 different `HttpClient`s.

**Comment by lachlan-roberts** [comment]
I don't have a specific use case in mind, I just thought it would be something you might want to do to minimise the impact of creating another `HttpClient`. The idleTimeout specifically for websocket can be set in other places like in onOpen, so if the solution is to just use two `HttpClients` that's fine with me.

**Comment by lachlan-roberts** [comment]
@joakime do you still think anything needs to be done for this or can it be closed?

**Comment by joakime** [comment]
Multiple HttpClients can only get you so far.
If you have multiple webapps, each with their own HttpClient and WebSocketClient you now have an exponential growth of its sub-components (as one example, consider the impact of each one with their own ThreadPool)
For those users that have complex scenarios, having the option to reuse HttpClient and/or sub-components of HttpClient is ideal.

That being said, I think that IdleTimeout on WebSocket should be supported the same way as it is on HttpClient.

_There's the default configuration that the Client has and is applied to all new connections, and an optional configuration per request._

Right now, I don't believe we have that optional behavior per request.
If we need it, we can easily add it to the Jetty WebSocket Client's Request object.

But for `javax.websocket`, we have no such facility at the Request level (before the onOpen).

on `javax.websocket` we have the following "timeout" settings.

 * [`javax.websocket.WebSocketContainer.setDefaultMaxSessionIdleTimeout(long)`](https://docs.oracle.com/javaee/7/api/javax/websocket/WebSocketContainer.html#setDefaultMaxSessionIdleTimeout-long-) - post-onopen default idle timeout.  Applied to all new `Session` instances.
 * [`javax.websocket.WebSocketContainer.setAsyncSendTimeout(long)`](https://docs.oracle.com/javaee/7/api/javax/websocket/WebSocketContainer.html#setAsyncSendTimeout-long-)) - per-async-send default timeout.  Applied to all new `RemoteEndpoint.Async` instances.
 * [`javax.websocket.Session.setMaxIdleTimeout(long)`](https://docs.oracle.com/javaee/7/api/javax/websocket/Session.html#setMaxIdleTimeout-long-) - post-onopen max idle timeout for a specific `Session`
 * [`javax.websocket.RemoteEndpoint.Async.setSendTimeout(long)`](https://docs.oracle.com/javaee/7/api/javax/websocket/RemoteEndpoint.Async.html#setSendTimeout-long-) - per-async-send timeout for a specific `RemoteEndpoint.Async`

So, with `javax.websocket` we have Idle Timeout support at the default (container) level, and at the per session level.
We also have an async send timeout, which is unique to `javax.websocket.RemoteEndpoint.Async` usage.
But we don't have ...
 * A connect timeout. - this is a configuration that HttpClient already supports.
 * A idle timeout configuration that can be applied before the `onOpen` event. (slotting into the period of time between when the upgrade request is initiated and a successful upgrade handshake has been sent/received). - the HttpClient's own Request object supports this very well.

Should we worry about connect timeout and pre-onopen idle timeout?
Part of me says yes (its a good thing to attempt to support for our users), part of me says no (javax.websocket is too simple and is lacking this basic concept).
