### ISSUE TITLE
ServerTimeoutsTest is flaky

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4274]
This is a frequent flaky failure:
```
java.lang.NullPointerException
	at org.eclipse.jetty.http.client.ServerTimeoutsTest.testAsyncWriteIdleTimeoutFires(ServerTimeoutsTest.java:608)
```

**Comment by lachlan-roberts** [comment]
So it looks like we're getting a HTTP/2 stream reset which eventually goes to `HttpReceiver.cleanup()` which nulls out all the fields of `HttpReceiver`. Later on we succeed the callbacks for the data we received which ends up back in `HttpReceiver` which now has null fields.

**Comment by lachlan-roberts** [comment]
Closing as this failure hasn't occurred in a long time.
