### ISSUE TITLE
Add cluster-wide Session Metrics for jetty-hazelcast

### ISSUE THREAD

**Issue by yogeshrao** [eclipse/jetty.project#4276]
We are using Jetty 9.3.x with Hazelcast-Jetty-Sessionmanager for Jetty 9. I noticed metrics emitted by Hazelcast Session Manager is limited to the JVM and does not consider sessions available across cluster.

This behavior seems to be originating from org.eclipse.jetty.nosql.NoSqlSessionManager which is extending org.eclipse.jetty.server.session.AbstractSessionManager, this class has embedded logic to use org.eclipse.jetty.util.statistic.CounterStatistic and org.eclipse.jetty.util.statistic.SampleStatistic. These Statistics information models do provide support for cluster and are very JVM specific.

I believe Session Metrics exposed when using Hazelcast Jetty Session Manager should be cluster based than JVM based. In order to fix this behavior the above needs to change.

I also noticed the source is still part of hazelcast / Hazelcast-Jetty-Sessionmanager github repo and has been included as dependency.

Let me know if contributions are welcome, will be happy to send a pull request across for Jetty 9.4.x. 

Post fix We can think of upgrading to 9.4.x version from 9.3.x

Version Details :-
Jetty - 9.3.x
JDK - 1.8.x
Hazelcast - 3.10.4
Hazelcast-Jetty-SessionManager - 1.0.2

Regards,
-Yogesh

**Comment by sbordet** [comment]
@yogeshrao contributions are very welcome.
Please make sure you comply with the [contribution guidelines](https://www.eclipse.org/jetty/documentation/current/contributing-patches.html).
See also https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md.

**Comment by janbartel** [comment]
@yogeshrao as jetty-9.3 has been superceded by jetty-9.4, any work you would like to contribute should focus on jetty-9.4.

Also, as the existing statistics have had the clear meaning of being node/context based for many years, at this point I don't think we should change that meaning just for the hazelcast session manager, but instead introduce some new statistic for the clustered metrics.

**Comment by olamy** [comment]
@yogeshrao please note now 9.4.x onward jetty-hazelcast module is part of main source code repository.

**Comment by yogeshrao** [comment]
@janbartel noted that the focus needs to be on jetty-9.4 as jetty 9.3 is using Hazelcast-Jetty-SessionManager as depedency. I also agree existing statistics  should not be changed as its more node/context  based and introduce something more generic for clustered nodes.

@olamy  - noted.
