### ISSUE TITLE
Review HttpParser handling in case of no content

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4282]
`HttpParser` behaves differently in emitting the "messageComplete" event, depending on whether there is content or not.

In case there is content, and it's the last chunk, returning `true` from the `content()` handler makes the parser stop, so that the `contentComplete` and `messageComplete` events are not delivered until the parser is resumed.

In case there is no content, returning true from the `headerComplete()` handler is basically ignored and the `contentComplete` and `messageComplete` events are delivered.

This difference is important because now we have a demand mechanism (at least in `HttpClient`), where if there is no demand for a response without content, the response is completed anyway.

By contrast, the HTTP/2 handling honors the return value of the "headersComplete" event and does not proceed until there is demand.

@gregw thoughts?

**Comment by gregw** [comment]
The example I think is key is a chunked empty message vs a known empty message.   Both are empty, yet returning true from headerComplete can hold up the chunked one, but not the known one.

So yes, I think we need to consider the return of headerComplete and if true not deliver the following events.    I think there are probably a few places in the parser where events are strung together like that.
But let's make this a Jetty-10 thing.

**Comment by sbordet** [comment]
@gregw why are we continuing parsing _after_ a response for white space?
https://github.com/eclipse/jetty.project/blob/jetty-9.4.22.v20191022/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java#L1532

The logic is not the same a parsing _before_ a request/response: in this latter case a `SP` will cause a failure, while in the former case it won't.

Also, it causes a difference between returning `true` or `false` from `messageComplete`: when returning `true` that code is not executed so a `SP` will fail the next parsing; when returning `false` that code is executed and eats the `SP` so the next parsing is not failed.

**Comment by gregw** [comment]
Because we need to keep consuming to get to a -1 and some clients send white space after a request and if we don't parse/consume then we don't see the EOF in response,
