### ISSUE TITLE
Possible NullPointerException in Main.java when stopped from command line

### ISSUE THREAD

**Issue by bschwarzent** [eclipse/jetty.project#4284]
When Jetty is started from the command line (i.e. via the _main_ method), the member `jsvcStartArgs` in [org.eclipse.jetty.start.Main](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-start/src/main/java/org/eclipse/jetty/start/Main.java) is not initialized. Unfortunately, inside the _stop()_ method, this member's methods are accessed without null check [here](https://github.com/eclipse/jetty.project/blob/82f804af916dce90c595d48c6ebc7ac1e815d32d/jetty-start/src/main/java/org/eclipse/jetty/start/Main.java#L606) and [here](https://github.com/eclipse/jetty.project/blob/82f804af916dce90c595d48c6ebc7ac1e815d32d/jetty-start/src/main/java/org/eclipse/jetty/start/Main.java#L610)!

This results in a `NullPointerException` when a `SocketTimeoutException` or a `ConnectException` occurs during _stop()_. The NPE is logged, but the original exception is lost.

```
Jetty 9.4.5.v20170502 is stopping...
java.lang.NullPointerException
	at org.eclipse.jetty.start.Main.stop(Main.java:613)
	at org.eclipse.jetty.start.Main.stop(Main.java:553)
	at org.eclipse.jetty.start.Main.doStop(Main.java:541)
	at org.eclipse.jetty.start.Main.start(Main.java:417)
	at org.eclipse.jetty.start.Main.main(Main.java:78)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

Expected behavior:
The member `jsvcStartArgs` should be initialized properly or the exception handlers should perform a null check before accessing its methods.

**Comment by gregw** [comment]
Thanks for the report. a fix has been pushed.
