### ISSUE TITLE
QueuedThreadPool creates threads with same name

### ISSUE THREAD

**Issue by eagleshine** [eclipse/jetty.project#4285]
Here is an example of the thread name:
```
qtp1145391264-5
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-6
qtp1145391264-7
qtp1145391264-7
qtp1145391264-7
qtp1145391264-7
qtp1145391264-7
```
The jetty version is: 9.4.19.v20190610

**Comment by joakime** [comment]
How did you produce that list of thread names?
What version of Jetty?
and what version of Java?

Capture a standard java threaddump while your app is running.  
Does that report duplicate thread names?

Also perform the verification via JMX?

**Comment by gregw** [comment]
The QTP naming mechanism is just putting a prefix onto the existing Thread.getId() mechanism, which is allocated by a synchronised `++` on a static field.  Are you sure it is not just the same thread being reused?

**Comment by eagleshine** [comment]
Ah, my bad. Looks like the Linux kernel truncated the thread name.
