### ISSUE TITLE
Unable to create WebSocket connect if the query string of the URL has % symbol.

### ISSUE THREAD

**Issue by gluxhappy** [eclipse/jetty.project#4296]
Unable to create WebSocket connect if the query string of the URL has % symbol.

https://github.com/eclipse/jetty.project/blob/4f98bf0f2e79c0f28afce52291aa059ca4f660cd/jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java#L160

Result of ```uri.getQuery()```  is a string decoded already. Invocation of ```UrlEncoded.decodeTo()``` causes it decoded twice.  When there is a % symbol (escape char for URL encoding), you will get the wrong result or an exception. 

Doc of ```URI.getQuery()```, already decoded.
https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getQuery() 
```java
public String getQuery() {
    if ((decodedQuery == null) && (query != null))
        decodedQuery = decode(query);
    return decodedQuery;
}
```

**Comment by joakime** [comment]
Opened PR #4300
