### ISSUE TITLE
SelectorManager: Random close error 

### ISSUE THREAD

**Issue by jknack** [eclipse/jetty.project#4297]
I do see some random close errors generated by SelectorManager.

```
java.io.IOException: Close org.eclipse.jetty.server.HttpConnection$SendCallback@5aa2a752[PROCESSING][i=HTTP/1.1{s=200,h=4,cl=-1},cb=org.eclipse.jetty.server.HttpChannel$SendCallback@1fa03262] in state PROCESSING
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:428)
	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:518)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:957)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
```

Response is generated OK, just sometimes got this error on logs (this is the whole stacktrace).

jetty: 9.4.20
jvm: 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10

**Comment by gregw** [comment]
Not much we can say about just that stack trace without more background info.
What kind of requests are you serving? Big? Little? Static? Dynamic?  Async? Blocking? OutputStream? Writer? Known Content-Length? Chunked? HTTP/1.0? HTTP/1.1? HTTP/2?
How does your app expect closes? at the end of a request? Was it due to a timeout? Was it initialised by the client?

**Comment by jknack** [comment]
Little (14 bytes), I don't set content-length bc Jetty does it in this case.

Issue is generated randomly while using the async version of HttpOutput.sendContent:

```
HttpOutput sender = response.getHttpOutput();
sender.sendContent(data, this);
```

The callback checks for non-null exceptions and log them:

```
failure(Throwable x) {
   if (x != null) {
    log.error("exception found while sending response", x);
   }
}
```

NOTE: The blocking version `sendContent(data)` doesn't generate this error. 

Async or blocking version the response in both cases are received OK by client, just got that random exception on logs while using async.

**Comment by sbordet** [comment]
@jknack can you please try 9.4.26 or later? We have fixed #4461 that may be related.

**Comment by jknack** [comment]
Still see it. Will look again and try to give you more details

**Comment by gregw** [comment]
@jknack are you still seeing this? If so, what release are you on now?
Can you tell us more about how your response was generated? Can you show us the response headers?  Perhaps get a wireshark trace?
