### ISSUE TITLE
PrintWriter or OutputStream in Handlers is very slow

### ISSUE THREAD

**Issue by Bradeskojest** [eclipse/jetty.project#4298]
We have a code that retrieves from the database in `73ms` (776538 bytes), and then writes it to the `PrintWriter` as in the following [Hello Handler example](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/HelloHandler.java). It spends `14556ms` int `.write()` function which seems excessive.

Is there anything that I am missing out from the example, such us buffering or increasing the buffer? If this is so, it would be good to improve the default example.

I couldn't find any documentation on how to improve the performance of responding to larger requests.

**Comment by joakime** [comment]
The default servlet `PrintWriter` is blocking behavior with squelched exceptions / errors (you have to use `.checkError()` to see if there is a problem after each usage of `PrintWriter`).  That means each write() call must wait for completion before continuing execution, even if the network / connection / socket is saturated and has to wait to actually write in that moment.

If you switch to using `HttpServletRequest.getOutputStream()` and use the Servlet Async I/O features, then you'll spend less time in network write, as it's only used when it's possible to write to the network, not holding a thread when it's not possible to write.

The time spent can also be impacted by the existence (or not) of `GzipHandler` performing compression on the outgoing body content.

The time you see on the database side is very likely only for obtaining a reference to the records in the database, and don't include the actual fetch of that data to the local thread.  Did you time that separately?

Without a code example where everything is in the mix (database, with data, the database fetch/query, the read of the records, the write of the response body, etc) there's nothing more to say, as it's all speculation from here on out.

If you look at static file serving on Jetty, you'll see that an 800k file can be served in under 200ms.

**Comment by sbordet** [comment]
@Bradeskojest very likely it's the client that is slow reading.

**Comment by Bradeskojest** [comment]
Hi. Thanks. Im not sure what could be going on.

The DB part is already written in `StringJoiner json = new StringJoiner(",", "[", "]");` at the point I measure the time:

1. DB Query + ResultSet scan + write results into StringJoiner = 73ms
2. String temp = stringJoiner.toString() = 1ms
3. (StringWriter) out.write(temp) blocks for the rest = 14556 - 73 -1 ms
That is the gist of the code. There is no GzipHandler, I just quickly extended the HelloHandler example:
` server.setHandler(new APIHandler(dbsource));`

I will experiment some more with `.checkError`, `GzipHandler` and `OutputStream`

**Comment by Bradeskojest** [comment]
@sbordet,
So far it looks like it's the client. iOS = 25s for the same query vs Postman = 0.7s. Looks like it had bad LTE connectivity. Once I switched to the same wifi as Postman, the speed is compare-able.

So the solution would be to use `async HttpServletRequest.getOutputStream()`? Is there anything else that could be done on the Jetty side to not get influenced by slow clients so much?

Thank you!

**Comment by sbordet** [comment]
Blocked threads on the server are a scalability issue - many connections make request, they all block, you run out of threads, more requests cannot be handled until the others unblock.

Async I/O will help a great deal with (read: solve) this problem.
The async I/O code is more difficult to write, but well worth it.

On the Jetty side we have async I/O APIs in `HttpOutput`, which you can obtain by casting `response.getOutputStream()`.

**Comment by Bradeskojest** [comment]
Ok, Thank you! Will implement it this way. Closing this issue, since the problem was identified and there is a solution in the comments.
