### ISSUE TITLE
Demand beforeContent is not forwarded

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4301]
`Request.onResponseContentDemanded(...)` wraps the given listener but does not forward the default method `onBeforeContent(...)`.

Also, test cases for when `onBeforeContent(...)` does not demand are missing.

**Comment by sbordet** [comment]
Note that this needs to be resolved for https://github.com/jetty-project/jetty-reactive-httpclient.

**Comment by sbordet** [comment]
This issue is also related to #4282, also necessary for the reactive HTTP client.

**Comment by joakime** [comment]
Opened PR #4302
