### ISSUE TITLE
maxFormContentSize Server attributes are not being used with Context

### ISSUE THREAD

**Issue by TomaszGaweda** [eclipse/jetty.project#4311]
Hi,

I've upgraded maven-jetty-plugin from 9.4.19.v20190610 to the newest release, however sometimes my queries ended with HTTP 400.

I found out, that this version is the latest version that does not ignore `org.eclipse.jetty.server.Request.maxFormContentSize` attribute. Starting from 9.4.20.v20190813, this attribute is ignored.

My jetty.xml:

```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure id="Server" class="org.eclipse.jetty.server.Server">
	<New id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
		<Set name="requestHeaderSize">65536</Set>
	</New>
	<Call name="addConnector">
		<Arg>
			<New class="org.eclipse.jetty.server.ServerConnector">
				<Arg name="server"><Ref refid="Server" /></Arg>
				<Arg name="factories">
					<Array type="org.eclipse.jetty.server.ConnectionFactory">
						<Item>
							<New class="org.eclipse.jetty.server.HttpConnectionFactory">
								<Arg name="config"><Ref refid="httpConfig" /></Arg>
							</New>
						</Item>
					</Array>
				</Arg>
				<Set name="host"><SystemProperty name="jetty.http.host" /></Set>
				<Set name="port"><SystemProperty name="jetty.http.port" default="8888" /></Set>
			</New>
		</Arg>
	</Call>
	<Call name="setAttribute">
		<Arg>org.eclipse.jetty.server.Request.maxFormContentSize</Arg>
		<Arg>104857600</Arg>
	</Call>
	<Call name="setAttribute">
		<Arg>org.eclipse.jetty.server.Request.maxFormKeys</Arg>
		<Arg>2000</Arg>
	</Call>
</Configure>
```

I suspect this PR to broke the behaviour: https://github.com/eclipse/jetty.project/commit/2e2cde69e918993d21e9231af03c183c28528b5b

If it's intended change, then documentation should be changed to point out the breaking change.

**Comment by joakime** [comment]
``` xml
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
```

That's the DTD for Jetty 7 and Jetty 8.

Use:

``` xml
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_9_3.dtd">
```

The settings for "Max Form Content Size" belong to the Context (a deployed webapp).
This configurable setting also only applies to non-multipart form usages.
The "Max Form Content Size" value is also only enforced once one of the `HttpServletRequest.getParameter*()` methods are called.

If the Request is submitted with `Content-Type: multipart/form-data` then you have to use the Servlet specific [`javax.servlet.annotation.MultipartConfig`](https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/MultipartConfig.html) (or equivalent `WEB-INF/web.xml` descriptor xml elements) to configure it.

The pasted `jetty.xml` is incomplete.
Why are you attempting to customizing the entire `jetty.xml` anyway?

If you just want to configure the `requestHeaderSize`, then set the `jetty.httpConfig.requestHeaderSize` property to the value you need.

Example:

``` plain
[mybase]$ cat start.ini
--module=deploy
--module=http
jetty.httpConfig.requestHeaderSize=65536
```

The two attributes on Server [`org.eclipse.jetty.server.Request.maxFormContentSize`, and `org.eclipse.jetty.server.Request.maxFormKeys`] were for no-context usages of max form content and keys.

For context based ones, please use the Context specific options (this is the recommended technique).

Example:

``` plain
[mybase]$ ls -la
total 16
drwxr-xr-x  3 joakim joakim 4096 Nov 13 12:53 ./
drwxr-xr-x 13 joakim joakim 4096 Nov 13 08:08 ../
-rw-r--r--  1 joakim joakim   31 Nov 13 12:53 start.ini
drwxr-xr-x  2 joakim joakim 4096 Nov 13 12:53 webapps/

[mybase]$ tree
.
├── start.ini
└── webapps
    ├── ROOT.war
    └── ROOT.xml

1 directory, 3 files
[mybase]$ cat start.ini 
--module=deploy
--module=http

[mybase]$ cat webapps/ROOT.xml 
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure id="root-webapp" class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war"><Property name="jetty.webapps" default="."/>/ROOT.war</Set>

  <Set name="maxFormContentSize">100200300</Set>
  <Set name="maxFormKeys">2000</Set>
</Configure>
```

If you still need server-wide settings, use the system properties instead.

``` plain
[mybase]$ cat start.ini 
--module=deploy
--module=http

-Dorg.eclipse.jetty.server.Request.maxFormContentSize=111333555
-Dorg.eclipse.jetty.server.Request.maxFormKeys=3000
```
