### ISSUE TITLE
test failure: jetty-run-forked-mojo-it

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#4312]
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/1297/testReport/junit/org.eclipse.jetty.maven.its/jetty-run-forked-mojo-it/Parallel_Stage___Build___Test___JDK11___jetty_run_forked_mojo_it/

**Comment by janbartel** [comment]
I'm going to close this issue for now: I don't think it was a failing in the jetty-run-forked-mojo-it test, it could have been a jenkins hiccup or restart. It doesn't seem to have happened again (there's been 40 builds since then). If it does re-occur, reopen this issue.
