### ISSUE TITLE
alt-formats build for jetty-documentation does not work

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4313]
**10.0.x**

The profile for alt-formats is broken on jetty-10.0.x. Here's the stacktrace:

Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/1.7.27/jruby-complete-1.7.27.jar (25 MB at 1.3 MB/s)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.ChannelDescriptor (file:/home/janb/.m2/repository/org/jruby/jruby-complete/1.7.27/jruby-complete-1.7.27.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.ChannelDescriptor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
io/console on JRuby shells out to stty for most operations
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.138 s
[INFO] Finished at: 2019-11-14T16:04:25+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc (quickstart-guide) on project jetty-documentation: Execution quickstart-guide of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc failed: An API incompatibility was encountered while executing org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc: java.lang.NoSuchMethodError: org.jruby.RubyModule.callMethod(Ljava/lang/String;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/janb/.m2/repository/org/asciidoctor/asciidoctor-maven-plugin/1.5.7.1/asciidoctor-maven-plugin-1.5.7.1.jar
[ERROR] urls[1] = file:/home/janb/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar
[ERROR] urls[2] = file:/home/janb/.m2/repository/org/asciidoctor/asciidoctorj-epub3/1.5.0-alpha.8.1/asciidoctorj-epub3-1.5.0-alpha.8.1.jar
[ERROR] urls[3] = file:/home/janb/.m2/repository/org/jruby/jruby-complete/1.7.27/jruby-complete-1.7.27.jar
[ERROR] urls[4] = file:/home/janb/.m2/repository/org/asciidoctor/asciidoctorj/1.5.8.1/asciidoctorj-1.5.8.1.jar
[ERROR] urls[5] = file:/home/janb/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.jar
[ERROR] urls[6] = file:/home/janb/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[7] = file:/home/janb/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[8] = file:/home/janb/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[9] = file:/home/janb/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[10] = file:/home/janb/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[11] = file:/home/janb/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/home/janb/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/home/janb/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.jar
[ERROR] urls[14] = file:/home/janb/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
[ERROR] urls[15] = file:/home/janb/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[16] = file:/home/janb/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[17] = file:/home/janb/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.22/plexus-interpolation-1.22.jar
[ERROR] urls[18] = file:/home/janb/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.23/plexus-utils-3.0.23.jar
[ERROR] urls[19] = file:/home/janb/.m2/repository/io/netty/netty-codec-http/4.0.38.Final/netty-codec-http-4.0.38.Final.jar
[ERROR] urls[20] = file:/home/janb/.m2/repository/io/netty/netty-codec/4.0.38.Final/netty-codec-4.0.38.Final.jar
[ERROR] urls[21] = file:/home/janb/.m2/repository/io/netty/netty-transport/4.0.38.Final/netty-transport-4.0.38.Final.jar
[ERROR] urls[22] = file:/home/janb/.m2/repository/io/netty/netty-handler/4.0.38.Final/netty-handler-4.0.38.Final.jar
[ERROR] urls[23] = file:/home/janb/.m2/repository/io/netty/netty-buffer/4.0.38.Final/netty-buffer-4.0.38.Final.jar
[ERROR] urls[24] = file:/home/janb/.m2/repository/io/netty/netty-common/4.0.38.Final/netty-common-4.0.38.Final.jar
[ERROR] urls[25] = file:/home/janb/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar
[ERROR] urls[26] = file:/home/janb/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.jar
[ERROR] urls[27] = file:/home/janb/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.jar
[ERROR] urls[28] = file:/home/janb/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[29] = file:/home/janb/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[30] = file:/home/janb/.m2/repository/org/apache/httpcomponents/httpclient/4.0.2/httpclient-4.0.2.jar
[ERROR] urls[31] = file:/home/janb/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[32] = file:/home/janb/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar
[ERROR] urls[33] = file:/home/janb/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar
[ERROR] urls[34] = file:/home/janb/.m2/repository/xmlunit/xmlunit/1.5/xmlunit-1.5.jar
[ERROR] urls[35] = file:/home/janb/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[36] = file:/home/janb/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.eclipse.jetty:jetty-documentation:10.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------

**Comment by sbordet** [comment]
I'll probably remove this profile for now, as we want the web side online, and the rest can be done later, if really needs.

**Comment by gregw** [comment]
Closing as documentation is under significant reworking.
