### ISSUE TITLE
Jetty server socket implementation for sync/ack

### ISSUE THREAD

**Issue by garan82** [eclipse/jetty.project#4314]
**Jetty version**
9.4.18.v20190429

**Java version**
1.8

**Question**
I'm using dropwizard (with jetty) to build rest APIs. I ran into some issue where server has many open sockets, specifically its receives SYNC and sends SYNC_ACK but never got ACK from clients. I want to add more debug log around that logic but couldn't find that implementation in Jetty, can someone please point me to the right source? Thanks.

**Comment by garan82** [comment]
Also, is it possible to retrieve all open server sockets in Jetty as well as their states?

**Comment by sbordet** [comment]
@garan82 it's the OS that sends `SYN` and `ACK`, so the JVM and Jetty have no control on that.

If the client sends a `SYN` but not the `ACK`, it's quite likely an attack known as [`SYN` flooding](https://en.wikipedia.org/wiki/SYN_flood).

There is no way to debug further this from Java, you have to rely on network traces or other OS tools.

You can dump all _connected_ sockets and their Jetty state using Jetty's [JMX dump](https://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html).

**Comment by garan82** [comment]
Thank you.
