### ISSUE TITLE
Review HTTP/2 DATA frame queueing

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4318]
**Jetty version**
10.0.0

**Java version**
11

**Description**
With the resolution of #3951, `HTTP2Stream` now queues `DATA` frames up to the flow control window size, and delivers them to listeners only if there is demand.

Before #3951, `HTTP2Stream` was delivering `DATA` frames to listeners immediately, so the queuing was happening in 2 places: either `HttpInput` for normal HTTP requests, or `HTTP2StreamEndPoint` in case of `CONNECT` requests.

I think we can remove the queuing from both `HttpInput` and `HTTP2StreamEndPoint`.

For `HttpInput` we need to consider the effects with HTTP/1.1, which I already think it overrides `HttpInput` in all the relevant places to not use its queuing features.

@gregw thoughts?

**Comment by gregw** [comment]
Correct, the queueing in HttpInput is only there for H2 so if it is not needed, we can probably substantially simplify HttpInput. 

For h1, there is a produce API mechanism that could be adapted to take from a queue?

**Comment by sbordet** [comment]
Fixed in 10.0.0 via #4556.
