### ISSUE TITLE
Classpath test in test servlet spec webapp broken

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4328]
**Jetty version**
9.4.23
**Java version**
any
**OS type/version**
any
**Description**

Commit b455b8abcceae586054b09a45f840a10f1e6f3b0 removed the dependency needed by the `com.acme.test.ClassLoaderServlet` test, so the test fails.
The test either needs to be moved to a custom webapp or some other way of testing the class path conditioning setup.

**Comment by joakime** [comment]
Opened PR #4332 (with test-distribution test and alternate pom.xml for including jetty-util-9.3.0.RC0 **without** contaminating the rest of the project's dependency convergence)
