### ISSUE TITLE
MultipartFilter charset handling

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#433]
There is something wrong with the handling of charsets as parameters in Multipart filter.

This has been wrong for some time, but the unit test was not checking the response code and the assert failure exception from the unit test has been ignored because of all the other exceptions there that are ignored (see #431 for the fix for that).  Work on #431 has cleaned up the unit test to at least pass with the current behaviour, but I am not sure it is the correct behaviour.

From 9.3.8 (prior to #431 commits) the unit test [testWithCharSet](https://github.com/eclipse/jetty.project/blob/jetty-9.3.8.v20160314/jetty-servlets/src/test/java/org/eclipse/jetty/servlets/MultipartFilterTest.java#L868) send a POST with a part encoded in UTF-8

The [servlet asserted](https://github.com/eclipse/jetty.project/blob/jetty-9.3.8.v20160314/jetty-servlets/src/test/java/org/eclipse/jetty/servlets/MultipartFilterTest.java#L854) that the value of the "ttt" request parameter was the decoded string - which it is not!!   

The assert failed and was logged, and a 500 response returned.  But the unit test did [not check the response code](https://github.com/eclipse/jetty.project/blob/jetty-9.3.8.v20160314/jetty-servlets/src/test/java/org/eclipse/jetty/servlets/MultipartFilterTest.java#L895)!

The commit with #431 to 9.3.x has updated the [servlet asserts](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlets/src/test/java/org/eclipse/jetty/servlets/MultipartFilterTest.java#L871) to check for the expected behaviour and the response code is now tested.

However, I think the original assert should still be applicable!  The problem I think is in the handling of parts without a filename.

For a part that is not buffered in a File, it's bytes are [stored as a byte array](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/MultiPartFilter.java#L197) in the param map and then the request wrapper is used to [convert them to a string](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/MultiPartFilter.java#L278), potentially using any charset

However, if due to configuration, the part is [buffered in a File, but does not have a filename](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/MultiPartFilter.java#L183) (#431 added the filename), then the File is stored as a request attribute, but the parameter is not set and the content type is not communicated to the application!

Ideally the request wrapper should also deal with this case.  The content type needs to be stored and the content retrieved from the File and converted to a string (more or less how the new unit test does) IF somebody attempts to access such parts via parameters.

**Comment by joakime** [comment]
This has been fixed in Issue #2398
