### ISSUE TITLE
sending WebSocket frames modifies the payload ByteBuffer

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#4341]
**Jetty version**
9.4.x and 10.0.x

**Description**
Sending a WebSocket message/frame using a ByteBuffer will modify the original buffer and change the position. After a send operation the buffer should remain unmodified.

**Comment by lachlan-roberts** [comment]
@gregw do you think this is something I should fix in Jetty 9.4 as well?

**Comment by gregw** [comment]
No.
