### ISSUE TITLE
All the documents and examples need to be updated

### ISSUE THREAD

**Issue by beibm** [eclipse/jetty.project#4345]
**Jetty version** 9.4.20
**Description**
In documents and examples
`int port = ExampleUtil.getPort(args, "jetty.http.port", 8080);
 int securePort = ExampleUtil.getPort(args, "jetty.https.port", 8443);
 Server server = createServer(port, securePort, true);
// Start the server
 server.start();
 server.join();
`
but，in version 9.4.20, the org.eclipse.jetty.server.Server's Method is 
`protected void start(LifeCycle l) throws Exception{}`

**Comment by olamy** [comment]
there is definitely a `void start() ` inherited from `AbstractLifeCycle` see [https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/org/eclipse/jetty/util/component/AbstractLifeCycle.html#start()](https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/org/eclipse/jetty/util/component/AbstractLifeCycle.html#start()) and Server inherits this class see [https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/org/eclipse/jetty/server/Server.html](https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/org/eclipse/jetty/server/Server.html)
