### ISSUE TITLE
Jetty 10 WebSocket writeTimeout is being used for Frames and not Messages

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#4347]
**Jetty version**
10.0.x

**Description**
The WebSocket writeTimeout is described in the javadoc of `javax.websocket.RemoteEndpoint.Async#getSendTimeout` as  
> the number of milliseconds the implementation will timeout attempting to send a websocket message

Our implementation of this is a timeout for sending each WebSocket frame and not for each message.

If the writeTimeout was 500ms and a large message was sent, this could be fragmented into 1000 frames which each take 250ms to send. So we spent 250 seconds to send the message when it should have timed out at after 500ms.

**Comment by joakime** [comment]
I don't see this difference as important.

If you cannot complete the message due to a specific frame send idle timeout, it's the same end result IMO.
