### ISSUE TITLE
Deprecated MultiPartInputStreamParser still used in jetty-server (MultiPartsUtilParser) but OSGi ExportPackage suppressed

### ISSUE THREAD

**Issue by domagojcc** [eclipse/jetty.project#4350]
**Jetty version**
9.4.x branch

**Java version**
any

**OS type/version**
any

**Description**
There is still a direct reference to the deprecated org.eclipse.jetty.util.MultiPartInputStreamParser.MultiPartInputStreamParser (jetty-util) in  org.eclipse.jetty.server.MultiParts.MultiPartsUtilParser.MultiPartsUtilParser (jetty-server). The issue is that the export of MultiPartInputStreamParser is explicitely excluded in the ExportPackage clause of the jetty-util bundle, making it impossible to use MultiParts in MultiPartFormDataCompliance.LEGACY mode in an OSGi environment (class loading error).

Either MultiParts.MultiPartsUtilParser code must be rewritten not to use the deprecated class, or the exclusion in the ExportPackage clause must be taken back until the code is refactored.

**Comment by joakime** [comment]
Why can't option 3 be use `MultiPartFormDataCompliance.RFC7578` on OSGi?

**Comment by joakime** [comment]
Or option 4 be that the default is `MultiPartFormDataCompliance.RFC7578` from here on out?

**Comment by domagojcc** [comment]
Having a useful workaround may make the priority lower but it is still a bug.

**Comment by domagojcc** [comment]
And of course, having a working default setting would certainly be better, so thumb up for option 4 independenty of the original issue.

**Comment by janbartel** [comment]
Fix checked in for jetty-9.4.25. Jetty-10 is unaffected.
