### ISSUE TITLE
Questions about the new jetty.service systemd file

### ISSUE THREAD

**Issue by Gregory-N-able** [eclipse/jetty.project#4352]
**Jetty version**
9.4.24

**Java version**
1.8.0_201

**OS type/version**
CentOS 7.7 x86_64

**Description**
I'm glad to see a systemD service file has been added to Jetty, but as I have been rebuilding and bundling jetty with custom changes, and a systemd .service file, I do have some questions about some of the assumptions in the new file, and some suggestions.

First, in [Issue 1485](https://github.com/eclipse/jetty.project/issues/1485) there was talk about the need to add the "SuccessExitStatus=" line to the file, but it is missing in the merged PR. You will want to do something like "SuccessExitStatus=0 130 143".

Second, by default, jetty doesn't install the initscripts. I believe this is added by Fedora and Red Hat upstream of CentOS, and possibly the the OS developers for other flavours. Therefore, assuming the initscripts will be present is not a safe assumption. Also, it is not a safe assumption to assume that the /etc/init.d/ folder will be present in the future. The way we created our systemd service definition file we are directly calling the "jetty.sh" script in the "${JETTY_HOME}/bin/" folder.

Assuming you want systemd to keep jetty running in the event of a crash, you will want to add "Restart=always". If you want a delay for Java to finish cleanup, also add "RestartSec=20s". On some VMs, if you are not running an entropy generating daemon, Jetty with TLS enabled can take longer than the 2 minute timeout systemd defaults to. You will want to add a line like "TimeoutSec=10min". You may also want to add a directive on how to kill jetty if the system needs to, "KillMode=process".

On the pid file issue that was discussed [Issue 1485](https://github.com/eclipse/jetty.project/issues/1485), The reason for the issues is you were starting Jetty as the jetty user. The /run/ folder is a tmpfs mount created every boot by systemd, which sets the permissions to "root:root" and "0755". This means, you need to run the jetty service as root to start, then use the setuid feature to pivot to the restricted user it needs to actually run under. We ran into this issue and it drove us crazy as we would set the permissions on "/run/" to allow the unprivileged user, only to have problems starting Jetty on the next boot. Looking at the "/jetty-home/src/main/resources/bin/jetty.sh" script, we can see if the value is not defined, it looks in "/var/run/jetty/", "/usr/var/run/jetty/", "$JETTY_BASE/jetty/", and "/tmp/jetty/" for a place to put the pid:

`JETTY_RUN=$(findDirectory -w /var/run /usr/var/run $JETTY_BASE /tmp)/jetty`

On CentOS 7 at least, "/var/run" is a symlink to "/run", which is that tmpfs mount with the "root:root" permissions set. As a result, "$JETTY_RUN" will try to use "/var/run/jett/jetty.pid", but due to permissions, it cannot create this file (unless the service is run as root). The workaround of putting the PID in your base folder works, but this is not a standard location for jetty, so again does not translate across linux flavours.

I think the solution here is to allow the systemd file to run as root, and add setuid=jetty to the default jetty config file, so jetty can start under root (in the systemd .service file) for systemd to establish it's control files, then switch to the unprivileged user for the actual process running the web server (you end up with a service jetty process running as root which spawns a child worker process to handles the web service). In systemd this isn't really an issue because of the use of control groups. The PID file tracks the parent Jetty process running as root, but any action you take on the parent process (kill, sigint, sigterm, etc) gets applied to the child processes as well (i.e. if you "kill -9 <jetty PID>", it kills the parent process (running as root), but then the systemd control groups kicks in and prevents the zombie process by killing all processes in the control group (this gave us much trouble as our appliance upgrades are triggered by our admin webapp, but the upgrade restarts the jetty service, which resulted in systemd killing the upgrade as well).

So what you end up with is a" jetty.service" file that looks similar to (assuming you put jetty in "/opt/jetty/"):
```
[Unit]
Description=Jetty Web Application Server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
SuccessExitStatus=0 130 143
Type=forking
PIDFile=/run/jetty.pid
Restart=always
RestartSec=20s
TimeoutSec=10min
ExecStart=/opt/jetty/bin/jetty.sh start
ExecStop=/opt/jetty/bin/jetty.sh stop
ExecReload=/opt/jetty/bin/jetty.sh restart
KillMode=process

[Install]
WantedBy=multi-user.target

```

**Comment by gregw** [comment]
@joakime can you look at this. thanks in advance

**Comment by joakime** [comment]
Using setuid as a default behavior introduces a host of other site effects that cannot be worked around in a generic way.
Example: logging starts logging and the log file is owned by root:root, then setuid kicks in, and now logging fails to work.

**Comment by joakime** [comment]
Regarding `SuccessExitStatus` ...

In `jetty.sh` we have ...
 * `exit` - for success and NO_START behaviors
 * `exit 0` - for success 
 * `exit 1` - usage or environment errors


In start.jar we have `System.exit()` with values ...
* `0` for success (seen when forked JVM dies)
* `-1` for failure with start logging
* `-2` for failure with invoking main class (means you have a bad classpath and/or jetty-home archive in use)
* `-4` for failure to issue the `stop` event to the running Jetty instance
* `-5` for a bad command line argument
* `-6` for a bad module graph situation
* `-7` for a failure when attempting to use the provided STOP keys to stop the running jetty
* `-9` for an unknown failure to start jetty (or stop jetty)

Then there's the OS level stop codes.
* `130` is for Script terminated by Control-C (which is a harsh closure and not following the jetty.sh guidelines)
* `143` would be fatal + TERM signal (the `128` for "fatal" + 15 for the signal).

I don't see 130 or 143 as valid values for "Success" (in this generic shell script)

**Comment by joakime** [comment]
While this is all good detail about having success with the systemd `jetty.service` file, I see this more as great guidelines for documentation than what we put in our generic `jetty.sh` script file that we ship with.

@WalkerWatch what do you think?  Could this be useful for documentation?

**Comment by Gregory-N-able** [comment]
> Using setuid as a default behavior introduces a host of other site effects that cannot be worked around in a generic way.
> Example: logging starts logging and the log file is owned by root:root, then setuid kicks in, and now logging fails to work.

Actually, because the parent process in the cgroup is owned by root, logging still works fine:

_**-rw-r--r-- 1 root root  9282214 Jun 18 17:00 console.log
-rw-r--r-- 1 root root    40982 Jun 18 17:19 gc.log
-rw-r--r-- 1 root root    10558 Mar 17 15:39 gc.log.1
-rw-r--r-- 1 root root   989150 Mar 17 15:24 gc.log.4
-rw-r--r-- 1 root root     6050 Jun 16 15:49 jetty-debug.log
-rw-r--r-- 1 root root     1045 Jun 16 15:49 jetty-start.log
-rw-rw-r-- 1 root jetty  471003 Jun 13 13:29 request.1.log.gz
-rw-rw-r-- 1 root jetty  460657 Jun  4 22:39 request.2.log.gz
-rw-rw-r-- 1 root jetty  474927 May 29 09:59 request.3.log.gz
-rw-rw-r-- 1 root jetty  473227 May 21 10:40 request.4.log.gz
-rw-rw-r-- 1 root jetty  457008 May 13 21:39 request.5.log.gz
-rw-rw-r-- 1 root jetty 6703069 Jun 18 17:25 request.log**_

From 'ps faux':

_**jetty      1381  0.6 46.3 2947552 909100 ?      Sl   Jun16  19:56 /usr/java/current/bin/java -server -XX:+UseG1GC -XX:+AlwaysPreTouch -Xmx670m -Xms191m -XX:MetaspaceSize=95m -DmanagerHome=/opt/web/webapps/bosh/WEB-INF/ -Djava.awt.headless=true -Dlog4j.configuration=file:/opt/web/webapps/ROOT/WEB-INF/classes/log4j.properties -Dorg.apache.commons.logging.LogFactory=org.apache.commons.logging.impl.LogFactoryImpl -Djava.security.egd=file:/dev/urandom -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Daxis.ServerConfigFile=/com/web/api/server-config.wsdd -Xss256K -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -Xloggc:/var/log/jetty/gc.log -XX:-TraceClassUnloading -XX:-OmitStackTraceInFastThrow -Dnetworkaddress.cache.ttl=60 -Djdk.tls.ephemeralDHKeySize=2048 -Djetty.home=/opt/jetty -Djetty.base=/opt/web -Djava.io.tmpdir=/opt/web/tmp -jar /opt/jetty/start.jar start-log-file=/var/log/jetty/jetty-start.log jetty.state=/opt/web/jetty.state jetty-started.xml**_

**Comment by Gregory-N-able** [comment]
> Regarding `SuccessExitStatus` ...
> 
> In `jetty.sh` we have ...
> 
>     * `exit` - for success and NO_START behaviors
> 
>     * `exit 0` - for success
> 
>     * `exit 1` - usage or environment errors
> 
> 
> In start.jar we have `System.exit()` with values ...
> 
>     * `0` for success (seen when forked JVM dies)
> 
>     * `-1` for failure with start logging
> 
>     * `-2` for failure with invoking main class (means you have a bad classpath and/or jetty-home archive in use)
> 
>     * `-4` for failure to issue the `stop` event to the running Jetty instance
> 
>     * `-5` for a bad command line argument
> 
>     * `-6` for a bad module graph situation
> 
>     * `-7` for a failure when attempting to use the provided STOP keys to stop the running jetty
> 
>     * `-9` for an unknown failure to start jetty (or stop jetty)
> 
> 
> Then there's the OS level stop codes.
> 
>     * `130` is for Script terminated by Control-C (which is a harsh closure and not following the jetty.sh guidelines)
> 
>     * `143` would be fatal + TERM signal (the `128` for "fatal" + 15 for the signal).
> 
> 
> I don't see 130 or 143 as valid values for "Success" (in this generic shell script)

You are assuming the shell is getting your return/exit codes directly. Unfortunately your return/exit codes are getting received by the JVM, which then exits with non-standard exit codes. Took me a bit to figure that one out and add the success codes to the systemd file.

**Comment by Gregory-N-able** [comment]
At the end of the day, shipping with a generalized jetty.service file is the best option. If an end user is running into some of these issues, like 143 being a successful exit code, they can always write a systemd override file to configure additional functionality (jetty.service.d/override.conf). https://www.freedesktop.org/software/systemd/man/systemd.unit.html
