### ISSUE TITLE
TLS handshake bloated due to unnecessary anchor certificate inclusion

### ISSUE THREAD

**Issue by andrepa** [eclipse/jetty.project#4353]
**Jetty version** 9.4.24.v20191120

**Java version** OpenJDK 13

**OS type/version** Linux/Ubuntu 18.04.3 LTS

**Description**

When jetty performs a TLS handshake, it includes the root/anchor certificate. This is unnecessary, because the browser will have that root certificate in its trust store already, so it doesn't need the server to send it. (See SSL/TLS standard, section 7.4.2, as documented here: https://security.stackexchange.com/q/24561)

The ssllabs.com test highlights this as an issue by displaying the "Chain issues - Contains anchor" warning, indicating that the root certificate is unnecessarily present.

Not only does including the root certificate result in a larger handshake, but there is apparently an outsized performance impact.

> Because of TCP Slow Start, the first bytes on a connection are the most expensive (slowest). Hence it makes sense to minimize the size of the handshake, so that HTTP bytes can start flowing as soon as possible. (see https://discussions.qualys.com/thread/11234#comment-21129)

Please could you consider preventing jetty from unnecessarily sending the anchor certificate in order to improve handshake latency.

**Comment by sbordet** [comment]
Jetty does not send the certificates, these are sent by the TLS implementation of the JDK you are using.

We will look if there is an option to tell the JDK to not send the anchor certificate.

**Comment by joakime** [comment]
The warning from ssllabs.com "Chain issues - Contains anchor" does not manifest for other known installations of Jetty 9.4.24.v20191120.
Example: https://webtide.com/ - https://www.ssllabs.com/ssltest/analyze.html?d=webtide.com

Perhaps this is more of an issue with a keystore that isn't quite right?

**Comment by sbordet** [comment]
@andrepa so I could not find any option to restrict what the JDK sends, it takes what's in the keystore.

This is not a Jetty issue, so closing it.
