### ISSUE TITLE
High memory usage by Jetty Session objects resulting in large GC pauses in jetty-9.4.11.v20180605

### ISSUE THREAD

**Issue by skpaterya** [eclipse/jetty.project#4362]
**Jetty version**
jetty-9.4.11.v20180605
 
**Java version**
java version "1.8.0_212"
 
**OS type/version**
Red Hat Enterprise Linux Server release 7.4 (Maipo)
 
**Description** 
After the upgrade from jetty-9.3.9.v20160617 to jetty-9.4.11.v20180605 we have observed a sudden increase in the heap memory usage of the our application. Since we are running jetty as an embedded component within our application the increase in the memory usage by the Session objects in OldGen area result in Full GC with huge GC pauses resulting in stalling the whole application.

Following are the memory usage from the GC logs at 1st and 22nd GCs where there is a linear increase in the memory usage by the Session and it's related objects. For example SessionData usage is increasing from 353 MB to 486.9 MB.

After the first big GC pause heap is never recovered and resulted in a cascading full GCs with huge GC pauses.

At 1st GC with 30.72 seconds of GC pause and reaching 8 GBs of allocated max heap and 6 GBs of OldGen:
2019-09-30T04:48:27.084+0530: 25841.673: [Full GC (Allocation Failure) 2019-09-30T04:48:27.084+0530: 25841.673: [Class Histogram (before full gc): 
 num     #instances         #bytes  class name
----------------------------------------------
   1:      11805064     1547168544  [C
   2:       7722935      494267840  java.util.concurrent.ConcurrentHashMap
   3:      11866712      379734784  java.util.concurrent.ConcurrentHashMap$Node
   4:       3861427      378179680  [Ljava.util.concurrent.ConcurrentHashMap$Node;
   5:       3860818      370638528  org.eclipse.jetty.server.session.SessionData
   6:      11803120      283274880  java.lang.String
   7:       3860818      185319264  org.eclipse.jetty.server.session.Session
   8:       7622315      182935560  java.util.concurrent.ConcurrentHashMap$KeySetView
   9:       3863723      123639136  java.util.concurrent.locks.ReentrantLock$NonfairSync
  10:       3860818      123546176  org.eclipse.equinox.http.servlet.internal.servlet.HttpSessionAdaptor
  11:       3860818      123546176  org.eclipse.jetty.server.session.Session$SessionInactivityTimer
  12:       3860818      123546176  org.eclipse.jetty.server.session.Session$SessionInactivityTimer$1
  13:       3860905       92661720  java.util.Collections$SetFromMap
  14:       3860868       92660832  org.eclipse.jetty.util.thread.Locker
  15:       3964576       63433216  java.util.concurrent.atomic.AtomicReference
  16:       3863527       61816432  java.util.concurrent.locks.ReentrantLock
  17:       3860868       61773888  org.eclipse.jetty.util.thread.Locker$Lock
  18:          7281       17695752  [B
  19:        284413        9101216  java.util.HashMap$Node
  20:          7593        7471632  [I
  21:         99575        7169400  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask
  22:         40664        6951040  [Ljava.lang.Object;
  23:         26862        3766896  [Ljava.util.HashMap$Node;
  24:         99460        3182720  org.eclipse.jetty.io.CyclicTimeout$Wakeup
  25:         99480        2387520  java.util.concurrent.Executors$RunnableAdapter
  26:         99461        2387064  org.eclipse.jetty.io.CyclicTimeout$Timeout
  27:         34101        1636848  java.util.HashMap
  28:         99467        1591472  org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask
  29:           416        1580032  [Ljava.nio.channels.SelectionKey;
  30:         10708        1201616  java.lang.Class
  
At 22nd GC:
2019-09-30T07:41:31.315+0530: 36225.904: [Full GC (Allocation Failure) 2019-09-30T07:41:31.315+0530: 36225.904: [Class Histogram (before full gc): 
 num     #instances         #bytes  class name
----------------------------------------------
   1:      16283541     2130591368  [C
   2:      10638613      680871232  java.util.concurrent.ConcurrentHashMap
   3:      16092794      514969408  java.util.concurrent.ConcurrentHashMap$Node
   4:       5318655      510590880  org.eclipse.jetty.server.session.SessionData
   5:       5319274      494824528  [Ljava.util.concurrent.ConcurrentHashMap$Node;
   6:      16281564      390757536  java.lang.String
   7:       5318655      255295440  org.eclipse.jetty.server.session.Session
   8:      10554632      253311168  java.util.concurrent.ConcurrentHashMap$KeySetView
   9:       5321717      170294944  java.util.concurrent.locks.ReentrantLock$NonfairSync
  10:       5318655      170196960  org.eclipse.equinox.http.servlet.internal.servlet.HttpSessionAdaptor
  11:       5318655      170196960  org.eclipse.jetty.server.session.Session$SessionInactivityTimer
  12:       5318655      170196960  org.eclipse.jetty.server.session.Session$SessionInactivityTimer$1
  13:       5318742      127649808  java.util.Collections$SetFromMap
  14:       5318707      127648968  org.eclipse.jetty.util.thread.Locker
  15:       5362781       85804496  java.util.concurrent.atomic.AtomicReference
  16:       5321521       85144336  java.util.concurrent.locks.ReentrantLock
  17:       5318707       85099312  org.eclipse.jetty.util.thread.Locker$Lock
  18:          7667       17932304  [B
  19:        292943        9374176  java.util.HashMap$Node
  20:         46557        7693808  [Ljava.lang.Object;
  21:         28472        3905360  [Ljava.util.HashMap$Node;
  22:         39918        2874096  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask
  23:         37235        1787280  java.util.HashMap
  24:           417        1580064  [Ljava.nio.channels.SelectionKey;
  25:         39801        1273632  org.eclipse.jetty.io.CyclicTimeout$Wakeup
  26:         10104        1231976  [I
  27:         10833        1214712  java.lang.Class
  28:         39824         955776  java.util.concurrent.Executors$RunnableAdapter
  29:         39802         955248  org.eclipse.jetty.io.CyclicTimeout$Timeout
  30:          1326         880464  com.datastax.shaded.netty.util.internal.MpscArrayQueue  
  
Attached is the GC report with memory usage pattern and the GC puase for your reference.  
[GC Report.pdf](https://github.com/eclipse/jetty.project/files/3890203/GC.Report.pdf)

**Comment by gregw** [comment]
Is it possible for you to try a recent release? eg jetty-9.4.24?
Also can you give us some background on what kind of traffic this server is getting, how do you use your sessions and what data do you put in the sessions. Any other special features of jetty used?

**Comment by janbartel** [comment]
Please also post your (santized) code for your session configuration.

**Comment by janbartel** [comment]
@skpaterya you need to provide more information about how your application uses sessions in jetty 9.4, and what your configuration was for sessions in jetty-9.3.

There have been no reported increases in memory usage with the session implementation in jetty-9.4, so more than likely the problem is in the application or non-optimal configuration settings.

**Comment by WalkerWatch** [comment]
Closing this for now. Can reopen if @skpaterya provides requisite information.
