### ISSUE TITLE
jetty-maven-plugin no longer processes supplied context.xml-file.

### ISSUE THREAD

**Issue by hareve** [eclipse/jetty.project#4363]
**Jetty version**
9.4.23.v20191118

**Java version**
1.8.0_232

**OS type/version**
Linux Fedora 31

**Description**
 #4239 removed line 526 in jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java: xmlConfiguration.configure(webApp);. This causes custom context.xml-files to stop working when using jetty-maven-plugin.

**Comment by joakime** [comment]
Link to removed line.

https://github.com/eclipse/jetty.project/commit/aefbdfca587277bc3d27a7e0b8faff3eb0ba4d05#diff-ff02a462f6cc50644669e515c691229dL526

**Comment by janbartel** [comment]
Fix checked in for jetty-9.4.25.
