### ISSUE TITLE
Can't set maxFormContentSize

### ISSUE THREAD

**Issue by aarrsseni** [eclipse/jetty.project#4373]
**9.4.24.v20191120**

**openjdk11**

**macOS**

User defined value of maxFormContentSize will be ignored.
org.eclipse.jetty.server.handler.ContextHandler set value of maxFormContentSize to default:
`_maxFormContentSize = Integer.getInteger(MAX_FORM_CONTENT_SIZE_KEY, DEFAULT_MAX_FORM_CONTENT_SIZE)`
In org.eclipse.jetty.server.Request if context is not equal to null, lookup for attributes won't be called.
```
 if (_context != null)
            {
                ContextHandler contextHandler = _context.getContextHandler();
                maxFormContentSize = contextHandler.getMaxFormContentSize();
                maxFormKeys = contextHandler.getMaxFormKeys();
            }
            else
            {
                maxFormContentSize = lookupServerAttribute(ContextHandler.MAX_FORM_CONTENT_SIZE_KEY, maxFormContentSize);
                maxFormKeys = lookupServerAttribute(ContextHandler.MAX_FORM_KEYS_KEY, maxFormKeys);
            }
```
And the user defined value will be ignored.

**Comment by sbordet** [comment]
This is by design. You want to set the max form content size on a per-context basis - the lookup as a server attribute is just a rare fallback for those cases where there is no context (some non-typical Jetty embedded usage).

**Comment by joakime** [comment]
Duplicate of #4311

**Comment by joakime** [comment]
See https://github.com/eclipse/jetty.project/issues/4311#issuecomment-553551985 for details on how to configure `maxFormContentSize`

**Comment by joakime** [comment]
Reopening.

The server configuration facility could still exist.
But, only in this fashion...

1. Server attributes set at LifeCycle startup.
2. When each ContextHandler is initialized for the first time it does the following to initialize it's configuration for form max sizes.
   a. If context values are set, use those.
   b. If server attributes are set, use those as default values.
   c. Use context handler default values.
