### ISSUE TITLE
Support http2 connector for jetty maven plugin

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4387]
**jetty-10**

There is a pom-only way to configure a http connector for the jetty-maven-plugin. It would be nice to have this for a http2 connector as well.

**Comment by sbordet** [comment]
For HTTP/2 we would need to setup a `SslContextFactory` with a `KeyStore`, and then TLS and then HTTP/2, so it'll be quite some work.

Delaying after Jetty 10.0.0.
