### ISSUE TITLE
Jetty server spins on incomplete request due to delayed dispatch until content

### ISSUE THREAD

**Issue by Marco85Li** [eclipse/jetty.project#4411]
**Jetty version**
9.4.24.v20191120

The issue is also reproducible with 9.4.18 and 9.4.20

**Java version**
jdk1.8.0_172 Oracle

**OS type/version**
Windows 7

The issue is also reproducible with RedHat

**Description**

The Jetty server starts to consume high CPU until server restart.

1. A client sends a POST request with all headers including content length but no actual body to a valid target URL. The target URL is handled by a servlet in async mode using a javax.servlet.ReadListener
2. The jetty.http.idleTimeout expires before any bytes of the request body are received.
3. The client starts to send the body before another Idle timeout expires.
4. The server starts spinning selecting the connection socket for reading without actually reading anything.

The issue is reproducible with the distributed Jetty server (version 9.4.24) by installing the attached webapp and running the following client sample.

NOTE:
If the client starts sending data after the idle timeout expires again (after 2 * idleTimeout), the problem does not occure. When the idle timeout expirse the second time, the ReadListener is notified with an onError event.

Questions:
1. Why isn't doPost called immediately after the header have been received?
2. Why isn't on error called after the first idle timeout expires?
3. Why does it take two idle timeouts to expire for the HttpConnection to be cleared?

We noticed this problem occurring with a CometD application in long-poll mode and misbehaving clients taking a long time to send the body of the meta/connect request.

Misbehaving client code follows
[JettyServerIssueAnalysis.log](https://github.com/eclipse/jetty.project/files/3945415/JettyServerIssueAnalysis.log)
[hello-world-war.zip](https://github.com/eclipse/jetty.project/files/3945448/hello-world-war.zip)

``` java
package com.test;

import java.io.IOException;

import javax.servlet.AsyncContext;
import javax.servlet.ReadListener;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet
public class TestServlet extends HttpServlet {

    private static final long serialVersionUID = -8683120971968625920L;

    @Override
    protected void doPost(HttpServletRequest req, final HttpServletResponse resp) throws ServletException, IOException {
        System.err.println("------------- POST ARRIVED -------------");
        Thread.dumpStack();
        
        final AsyncContext asyncContext = req.startAsync(req, resp);
        asyncContext.setTimeout(0);
        req.getInputStream().setReadListener(new ReadListener() {
            
            public void onError(Throwable t) {
                int responseCode = HttpServletResponse.SC_INTERNAL_SERVER_ERROR;
                System.err.println("------------- POST ERROR -------------");
                Thread.dumpStack();
                System.err.println("------------- POST EXCEPTION -------------");
                t.printStackTrace();
                System.err.println("------------- POST ERROR HANDLING -------------");
                
                try {
                    resp.setStatus(responseCode);
                } catch (Exception x) {
                    System.err.println("------------- Could not send " + responseCode + " response");
                    x.printStackTrace();
                } finally {
                    try {
                        if (asyncContext != null) {
                            asyncContext.complete();
                        }
                    } catch (Exception x) {
                        System.err.println("------------- Could not complete " + responseCode + " response");
                        x.printStackTrace();
                    }
                }
                
                System.err.println("------------- POST ERROR COMPLETED -------------");
                
            }
            
            public void onDataAvailable() throws IOException {
                System.err.println("------------- POST DATA AVAILABLE -------------");
                
            }
            
            public void onAllDataRead() throws IOException {
                System.err.println("------------- POST DATA READ -------------");
                
            }
        });
    }
}
```

``` java
package test;

import java.nio.charset.StandardCharsets;

import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.api.Request;
import org.eclipse.jetty.client.api.Response.CompleteListener;
import org.eclipse.jetty.client.api.Result;
import org.eclipse.jetty.client.util.OutputStreamContentProvider;
import org.eclipse.jetty.http.HttpMethod;
import org.eclipse.jetty.http.HttpVersion;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class JettyHighCpuBug {

    private static final Logger log = LoggerFactory.getLogger(JettyHighCpuBug.class);
    
    private static final long SERVER_IDLE_TIMEOUT_MS = 30000;
    private static final String CONTENT = "[{\"key\":\"value\"}]";
    
    public static void main(String[] args) throws Exception {
        log.info("START");
        
        HttpClient httpClient = new HttpClient();

        httpClient.start();
        
        Request request = httpClient.newRequest("http://localhost:9999/hello/mytest");
        request.method(HttpMethod.POST);
        request.version(HttpVersion.HTTP_1_1);
        request.accept("*/*");
        request.agent("Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko");
        
        OutputStreamContentProvider content = new OutputStreamContentProvider() {
            @Override
            public long getLength() {
                return CONTENT.length();
            }
        };
        
        request.content(content, "application/json;charset=UTF-8");
        
        log.info("SEND REQUEST HEADERS");
        request.send(new CompleteListener() {
            
            @Override
            public void onComplete(Result result) {
                log.info("RESPONSE BODY");
            }
        });
        
        log.info("WAIT TIMEOUT");
        // Reproduce misbehaving client behavior
        Thread.sleep(SERVER_IDLE_TIMEOUT_MS + 10000);
        log.info("RESUME FROM TIMEOUT");
        
        log.info("SEND REQUEST BODY");
        content.getOutputStream().write(CONTENT.getBytes(StandardCharsets.UTF_8));
        
        httpClient.stop();
    }
}
```

**Comment by joakime** [comment]
Do you have `HttpConfiguration.setDelayDispatchUntilContent(boolean)` set?
If so, to what value?

**Comment by Marco85Li** [comment]
The distributed Jetty server doesn't change the default value of the above setting.
Despite the Javadoc documentation , it's default value is `true`.

HttpConfiguration.java
``
 @param delay if true, delay the application dispatch until content is available (default false)
``

Changing it to false seems to fix the issue:
1. the ``doPost`` servlet is now called immediately after all headers are received;
2. the ``onError`` event is raised on idle timeout;
3. the server answer with 500 Server error.

The fix seems to work also in the original web application that uses CometD: the ``AsyncJSONTransport::AbstractReader#onError`` method is called on idle timeout.

Can you confirm that it is fine to set the setDelayDispatchUntilContent setting to false on a CometD application? The server handles both long-poll and websocket client connections.

**Comment by joakime** [comment]
> The distributed Jetty server doesn't change the default value of the above setting.
> Despite the Javadoc documentation , it's default value is `true`.

OK, Good catch, that documentation problem needs to be addressed.

**Comment by joakime** [comment]
The default was changed to true in commit 504ff73d03cc87ea9f0e410805f2d31479f15601 (for Jetty 9.3.0 release), without much explanation as to why.

**Comment by sbordet** [comment]
The reason to have `delayDispatchUntilContent=true` by default is that it avoids that application immediately block the thread waiting for content.
When set to `true`, Jetty will read the HTTP headers and then wait threadlessly for the content to arrive, while when set to `false` Jetty will call the application which will typically perform a blocking `read()` and block there until content arrives.
It's an optimization and a big one for scalability.
I'm looking at why we spin.

**Comment by sbordet** [comment]
I can reproduce the issue, stay tuned for a fix.

**Comment by joakime** [comment]
Opened PR #4412
