### ISSUE TITLE
dynamically set wantClientAuth and needClientAuth in ssl context factory

### ISSUE THREAD

**Issue by garan82** [eclipse/jetty.project#4413]
**Jetty version**
jetty-util-9.4.11.v20180605
**Java version**
8
**Question**
We are using Jetty with DropWizard. We plan to have a single connector to serve both https & mTLS traffic. As such, we want to dynamically enable/disable `wantClientAuth` and `needClientAuth` in ssl context factory. Is there a simple way to do so, I feel it's unsafe and unmaintainable to create a copy of Jetty SslContextFactory and make change on top of that. Thanks.

**Comment by sbordet** [comment]
How do you know when you want to enable `wantClientAuth`? By client IP?

Generally speaking, the setting on `SslContextFactory` is a coarse one that is copied to all `SSLEngine`s created from it.

If you wan to customize only a particular connection (e.g. by client IP), then you just call `SSLEngine.setWantClientAuth(true)` on the `SSLEngine` associated to that connection.
That can be easily done by overriding `SslContextFactory.customize(SSLEngine)`.

**Comment by garan82** [comment]
Yes I want to customize for some type of connection (based on request headers). Let me play around with `SslContextFactory.customize(SSLEngine)` and see. Thank you.

**Comment by garan82** [comment]
@sbordet is it possible to access to request headers from SslContextFactory, I don't see it.

**Comment by sbordet** [comment]
@garan82 the TLS handshake where the server requires the client certificate (or not) happen way before any HTTP request that you may _later_ send on that (now encrypted) connection.

As such, you cannot use HTTP request headers to decide whether you want TLS client authentication - you have to rely on the client IP address.

**Comment by garan82** [comment]
Thank you. We'll create 2 connectors instead of trying to use 1 for both https & mtls then.

**Comment by garan82** [comment]
@sbordet reopen as I have more questions, sorry :( Main reason we want to use request header is to get the host header. But if we can get the host in a different way at SSL Handshake, that should be sufficient as well. For SNI, client should present the host name at SSL handshake, right? Is there a way to get this from SSL Context Factory?

**Comment by garan82** [comment]
For a second thought, I think the host in SNI call is present during SSL handshake but not before, so it probably won't work.

**Comment by sbordet** [comment]
The SNI information is present in the first TLS message sent by the client (the `ClientHello`) so it's kind of immediately available.

However, that is the the _server_ name.

How do you force a client that must use client certificate authentication to use the server host name that is configured to require client certificate authentication?
The client can just use another server host or the "open" server host name and bypass authentication, no?

**Comment by garan82** [comment]
Yes, they can fake another server name in SNI. In our design, a valid request will include host in request headers, along with some digital signature for the headers/body. If we can get host from SNI, and decide to enable/disable client cert validation for SSL handshake. And once SSL handshake succeeds, we confirm again at later point if host from SNI is the same as the one provided in request header, that is good enough or am I wrong?

**Comment by sbordet** [comment]
If they can fake the SNI host, I guess they can also fake the HTTP header, no?
Consider a new user of your system (with only access to `auth.domain.com`) pretending to be an admin, or something similar.

I never tried to update the `SSLEngine` configuration in the middle of the TLS handshake.
The JDK does not have APIs to extract the SNI name from the `ClientHello`.
The JDK implementation will call Jetty at a certain point with the SNI name. Whether at that point is possible to change the `SSLEngine` configuration to `needClientAuth` I don't know.
Did you try (you don't have to use Jetty for this test)?

Two connectors is definitely the simplest configuration, but again the client can change the port and use the open connector when it should use the authenticated one.

**Comment by sbordet** [comment]
Closing as answered, reopen if you have more questions.
