### ISSUE TITLE
GZipHandler not excluding inflation for specified paths

### ISSUE THREAD

**Issue by Auo** [eclipse/jetty.project#4414]
**Jetty version**
9.4.24.v20191120

**Java version**
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)

**OS type/version**
macOS Catalina 
version 10.15.1

**Description**
`GZipHandler::addExcludedPaths` does not exclude inflation for specified paths when `GZipHandler::setInflateBufferSize` has been set.

A new method, `addExcludedInflationPaths` would be very useful or to make sure the paths from `addExcludedPaths` also apply when checking if the request should be inflated.

**Usecase**
We want to inflate requests on certain paths, but on other paths we want to handle the inflation ourselves.

Thanks!

**Comment by sbordet** [comment]
@lachlan-roberts isn't this feature present already?

**Comment by joakime** [comment]
Current `GzipHandler` in Jetty 10 and 11 will always inflate if the request contains `Content-Encoding: gzip` header.
There's no filtering/include/exclude for inflation for anything (path, method, mime-type, etc)
