### ISSUE TITLE
Implement ServletContext.get/setRequestCharacterEncoding and ServletContext.get/setResponseCharacterEncoding

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4434]
**Jetty 10**
Servlet 4.0

**Comment by joakime** [comment]
This is related to issue #2995 right?

**Comment by janbartel** [comment]
PR #4455 opened.

**Comment by janbartel** [comment]
@joakime oops, this is a duplicate of #2995, but as I've used this issue number in the PR, I'll have to keep this issue and close the older one.
