### ISSUE TITLE
SessionHandler not able to recover jsessionid from url

### ISSUE THREAD

**Issue by jivkoto** [eclipse/jetty.project#4437]
**Jetty version**
Jetty 9.4.24

**Java version**
java 8

**OS type/version**
MacOS Mojave 10.14.6 

**Description**
For some of my requests I am setting the jsessionid in the url as I can't use cookies. The whole url is looking like:

```
http://localhost:8080/in/trains?jsessionid=YjJkNTExYjtNjMzNi00ZGJhLTk1ZmMtMWMwYTA5ZWQ0MDBm
```
The result is that the the session is not recovered.

I particularly did some findings that want to highlight

1. Bad implementation in org.eclipse.jetty.server.session.SessionHandler
SessionHandler is not able to correctly read the jssessionId from the url. (lines 1682-1691)
```java
        //try getting id from a url
        if (isUsingURLs() && (requestedSessionId == null))
        {
            String uri = request.getRequestURI();
            String prefix = getSessionIdPathParameterNamePrefix();
            if (prefix != null)
            {
                int s = uri.indexOf(prefix);
                if (s >= 0)
                {
```
The first problem is that url is constructed from request.getRequestURI();. getRequestURI will return only "/in/trains" and not the query part where the parameter is placed. 

2. The second problem is that getSessionIdPathParameterNamePrefix(); will return the value constructed in (line 178-179) which is ";jsessionid="!
``` java
    protected String _sessionIdPathParameterName = __DefaultSessionIdPathParameterName;
    protected String _sessionIdPathParameterNamePrefix = ";" + _sessionIdPathParameterName + "=";
```
So if I actually want my jsessionid to be read as part of the request my request should look like:

```
http://localhost:8080/in/trains?;jsessionid=YjJkNTExYjtNjMzNi00ZGJhLTk1ZmMtMWMwYTA5ZWQ0MDBm
```
Which is kind of strange construct.

**Comment by joakime** [comment]
The use of `/in/trains;jessionid=<blah>` is the format that it takes. (a jsessionid is never a query parameter)
This syntax is known as a URL path parameter. - https://tools.ietf.org/html/rfc3986#section-3.3

As for the ways a Servlet container can be configured to read sessions, there's the SessionTrackingMode.

https://docs.oracle.com/javaee/7/api/javax/servlet/SessionTrackingMode.html

From there, you can see there are only 3 tracking modes available to you.

* `COOKIE` - that's obvious, and is populated with a `Set-Cookie` response header which is returned as a `Cookie` request header.
* `SSL` - this is done via associating the SSL  session to the servlet session
* `URL` - this is tracked via the `jesssionid` path parameter on the URL (not the query)

**Comment by jivkoto** [comment]
With the clarification it makes sense. Also pics it up correctly. 
It was my wrong assumption that SessionTrackingMode.URL was for query param even though the java doc was not clear where exactly in the URL should be placed. (Probably the spec is more clear).
Thank you for the clarification.
