### ISSUE TITLE
Why is 10.0.0.alpha1 marked as a release version?

### ISSUE THREAD

**Issue by lasiltan** [eclipse/jetty.project#4439]
**Jetty version**
10.0.0.alpha1

**Java version**
11.0.2

**Question**
Why is 10.0.0.alpha1 - clearly an alpha version - marked as a release version in maven: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/maven-metadata.xml? This is seriously annoying for anyone using an automated dependency updater.

**Comment by sbordet** [comment]
The `release` element is updated by Maven every time a non SNAPSHOT artifact is deployed.

10.0.0.alpha1 is a "release" for those that want to use/test Jetty 10 and consume artifacts from Maven Central. We currently run one of our websites on it.
