### ISSUE TITLE
typo Limiting Load in jetty docs

### ISSUE THREAD

**Issue by Park-Jongseok** [eclipse/jetty.project#4445]
- Merry Christmas. :santa:

- typo
  - [jetty docs - Limiting Load](https://www.eclipse.org/jetty/documentation/9.4.24.v20191120/limit-load.html)'s LowResourcesMonitor on the sixth line

- Before modification
  - https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/org/eclipse/jetty/server/LowResourcesMonitor.html

- After modification
  - https://www.eclipse.org/jetty/javadoc/9.4.24.v20191120/org/eclipse/jetty/server/LowResourceMonitor.html

- 404 error is occurred! Maybe it's because the class name have `S`.

- Thank you for making a good server!

**Comment by sbordet** [comment]
@PARK-JONGSEOK, thanks!
