### ISSUE TITLE
Proxy Servlet start processing request but times out after 60 seconds

### ISSUE THREAD

**Issue by kompaktkikare** [eclipse/jetty.project#4448]
Jetty version: 9.4.7.v20170914

Java version: 1.8.0_212

OS: Red Hat 7.4

Hi,
We have experienced a problem where our proxy servlets (extending ProxyServlet) running in an embedded Jetty, started to time out. The FW log showed that the request where never sent from the server running the proxy servlet to the backend service.
The proxy servlet where always able to start processing the incoming client request, but they timed out after 60 seconds resulting in a 504 response to the client.
The rest of Jetty remained functional, serving static content and maintaining user web socket connections
After a restart of the process the proxy servlets where fully functional again.

We have never experienced this problem before and are not able to reproduce it without modifying the code and comment out the request from being sent.

It would be much appreciated to get some new ideas on how to reproduce or if the problem has been seen before.

**Comment by sbordet** [comment]
First of all, try to upgrade to Jetty 9.4.25 and see if the problem reproduces.

Next, we need some evidence of the problem. Please enable DEBUG logging, reproduce the problem and attach the DEBUG logs to this issue. See https://www.eclipse.org/jetty/documentation/current/configuring-logging.html.

We are not aware of any problem in `ProxyServlet` and we have plenty of users using it.

There is a chance that your code modifications introduced the issue, but without looking at the code we cannot tell. I would recommend that you take out your modifications and see if the problem still exist.

Probably the best approach for you would be to run an example request through an unmodified `ProxyServlet` with DEBUG logging; then run a request through your modified code with DEBUG logging and then compare the logs to see where the difference is.

**Comment by kompaktkikare** [comment]
Thanks,
This problem happened once more in production, with more debug logging we saw that the SocketAddressResolver task where put on the queue, but did never run.
-D-(QueuedThreadPool) - queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$84/210474732@44521aaa

The closest we have come to reproduce the issue, was to reduce the number of maxThreads. The big difference from production is when reproducing this locally is that the issue is reproduced from start, while in production this does only occur after several hours after the process has been started.

**Comment by sbordet** [comment]
What you describe is a typical case where you run out of thread pool threads because they are blocked in some blocking operation.

Take a JVM thread dump and you will see where the threads are blocked.

**Comment by sbordet** [comment]
Closing as no further information was provided.
