### ISSUE TITLE
ExecutorThreadPool reject strategy not effect when queue config more than one.

### ISSUE THREAD

**Issue by SingASongForU** [eclipse/jetty.project#4457]
jetty.project-jetty-9.4.15.v20190215
JDK8
SUSE LINUX 

When use this to create a jetty server,I find a strange problem.This is the codes(workThreads is a standard java threadpool with rejectedHandler like ThreadPoolExecutor.AbortPolicy):

``` java
ExecutorThreadPool threadPool = new ExecutorThreadPool(workThreads);
Server server = new Server(threadPool);
```

when worktheads queue configure as one(the max queue number is one),everything seemed to be ok.The jetty server will reject new request when the threadpool and queue is full. But when configure more than one(the max queue number is two or larger),jetty get stuck without any logs,when I debug,I fing the new request even not go into the org.eclipse.jetty.util.thread.ExecutorThreadPool's execute method,so jetty can not reject new request with AbortPolicy.

When I use this code:
``` java
QueuedThreadPool queuedThreadPool=new QueuedThreadPool(getDefinition().getMaxThreads(),
						getDefinition().getMinThreads(),
						getDefinition().getKeepAliveTime(),
						new LinkedBlockingQueue<Runnable>(getDefinition().getQueueSize()));
Server server = new Server(threadPool);
```

Reject policy always works good when I configure queue one or more than one.
Please help me~I just don't know if my code is wrong or jetty exist this bug.Thanks a lot.

**Comment by joakime** [comment]
An ExecutorThreadPool of only 1 max queue will never work.

Why are you wanting this kind of config?

**Comment by SingASongForU** [comment]
> An ExecutorThreadPool of only 1 max queue will never work.
> 
> Why are you wanting this kind of config?

When use ExecutorThreadPool ,the fact is only 1 max queue worked well，when 2 or larger，the reject handler didn‘t work.And even not go into the method org.eclipse.jetty.util.thread.ExecutorThreadPool.execute .Such as:
when construct my workThreads,use
BlockingQueue<Runnable> workQueue = new LinkedBlockingQueue<Runnable>(1);
AbortPolicy worked well.
but use
BlockingQueue<Runnable> workQueue = new LinkedBlockingQueue<Runnable>(2);
AbortPolicy didn't work.

I found this problem when I try to test my jetty server with big request pressure.I found sometimes the jetty server will stuck , caused by AbortPolicy not effect.Strangely,when I change the number of workQueue, it made difference.

Thanks for answer my question.But what you say maybe just opposite of my description...



My workThreads coding like this:
		BlockingQueue<Runnable> workQueue = new LinkedBlockingQueue<Runnable>(queueSize);
		ThreadPoolExecutor executor = null;
		if (rejectedHandler != null) {
			executor = new  java.util.concurrent.ThreadPoolExecutor(definition.getMinSize(), 
					definition.getMaxSize(), keepAliveTime, TimeUnit.SECONDS, 
					workQueue, new NamedThreadFactory(workThreadsName), rejectedHandler);

**Comment by sbordet** [comment]
@SingASongForU we do not support bounded queues and likely won't support them in the future, as that would complicate the code a lot for only very marginal cases.

FTR you don't test a server for "big request pressure" by limiting the executor queue. You want to have a look at load test frameworks and tune the thread sizes instead.

**Comment by SingASongForU** [comment]
> @SingASongForU we do not support bounded queues and likely won't support them in the future, as that would complicate the code a lot for only very marginal cases.
> 
> FTR you don't test a server for "big request pressure" by limiting the executor queue. You want to have a look at load test frameworks and tune the thread sizes instead.

Thank you very much. My manager ask me to use QueuedThreadPool instead.
