### ISSUE TITLE
Provide override for compliance mode violations

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#447]
When there is a compliance mode violation, call a method that can be overridden to allow for customized logging of the violation.

Allowing a developer to extract extra information from the raw Request / Response objects to help identify the incoming problematic client.

**Comment by joakime** [comment]
Something to worry about: if the request is bad enough to trigger the violation, does the request object exist?

**Comment by gregw** [comment]
Closed as duplicate of #448
