### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by raccoon1515** [eclipse/jetty.project#4473]
**Jetty version** 9.4.20.v20190813
**Java version** 1.8.0_201
**OS** Ubuntu 18.04.3 LTS (Bionic Beaver)

**Stacktrace:**
> 2019-12-23T09:18:58,597 [qtp1702940637-19-acceptor-0@339ac900-ServerConnector@4f74980d{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}] WARN  AbstractConnector AbstractConnector.handleAcceptFailure(line:599). 
> java.io.IOException: Too many open files
> 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_222]
> 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_222]
> 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_222]
> 	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385) ~[jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
> 	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:664) [jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

The number of fd is increasing. Netstat shows 613 open connections. Lsof shows total 4250 files.

> java    5086 apb 3313u     IPv4           15306277      0t0      TCP 10.184.14.44:8090->10.230.109.165:39706 (ESTABLISHED)
java    5086 apb 3314u     sock                0,8      0t0  8799042 protocol: TCP
java    5086 apb 3315u     IPv4           15298364      0t0      TCP 10.184.14.44:8090->10.230.48.95:47173 (ESTABLISHED)
java    5086 apb 3316u     sock                0,8      0t0 10040260 protocol: TCP
java    5086 apb 3317u     sock                0,8      0t0  9427901 protocol: TCP
java    5086 apb 3318u     sock                0,8      0t0  8477043 protocol: TCP
java    5086 apb 3319u     IPv4           15360584      0t0      TCP 10.184.14.44:8090->10.230.16.224:46865 (ESTABLISHED)
java    5086 apb 3320u     sock                0,8      0t0 11300680 protocol: TCP
java    5086 apb 3321u     sock                0,8      0t0  8479591 protocol: TCP
java    5086 apb 3322u     sock                0,8      0t0  9162611 protocol: TCP
java    5086 apb 3323u     sock                0,8      0t0  9581068 protocol: TCP
java    5086 apb 3324u     sock                0,8      0t0  9887614 protocol: TCP
java    5086 apb 3325u     sock                0,8      0t0  9162614 protocol: TCP

`cat lsof.log | grep ESTABLISHED | wc -l`
`613`

`cat lsof.log | grep sock | wc -l`
`3332`

The nubmer of lines like `java    5086 apb 3320u     sock                0,8      0t0 11300680 protocol: TCP` is increasing.

**Comment by sbordet** [comment]
@raccoon1515 that the number of file descriptor is increasing can be totally normal.

If you open one connection and count the number of open FDs, when you open another connection, the number of FDs increases.

Without a reproducible test case, where we see/describe exactly what you are doing, your report can be completely normal.

You also appear to have a misconfigured server - you never want to see "Too many open files".

**Comment by raccoon1515** [comment]
We have scheduled job, which closes open sockets every hour. But I see sockets stay opened and the number of file descriptors increases.

ServerEndpoint class:

```
@ServerEndpoint(
        value = "/broad",
)
public class ServiceEndpoint {
    ...

    @OnError
    public void onError(Session session, Throwable t) {
        session.close(new CloseReason(CloseReason.CloseCodes.CLOSED_ABNORMALLY, "Session Closed"));
    }
}
```

**Comment by sbordet** [comment]
@raccoon1515 we need a reproducible case that we can try ourselves. Write it, zip it, attach it to this issue.

**Comment by raccoon1515** [comment]
@sbordet 
[FDLeakReproduce.zip](https://github.com/eclipse/jetty.project/files/4085179/FDLeakReproduce.zip)

Also, we have a next log:

> 2019-12-23T09:14:03,287 [qtp1702940637-1344] WARN  JsrAnnotatedEventDriver JsrAnnotatedEventDriver.onError(line:206). Unable to call onError with cause
> org.eclipse.jetty.io.EofException: null
>     at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:283) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) [jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) [jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:264) [websocket-common-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:193) [websocket-common-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:516) [websocket-common-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:184) [websocket-common-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:458) [websocket-common-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:428) [websocket-common-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
>     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
> Caused by: java.io.IOException: Broken pipe
>     at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.8.0_222]
>     at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.8.0_222]
>     at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_222]
>     at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_222]
>     at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
>     ... 22 more
> 2019-12-23T09:14:03,287 [qtp1702940637-1344] WARN  JsrAnnotatedEventDriver JsrAnnotatedEventDriver.onError(line:207). Call to onError resulted in exception
> java.lang.NullPointerException: null

**Comment by sbordet** [comment]
Tried your code, started the server, started the client, and then monitored the server's number of file descriptors via JMC (MBean `java.lang:type=OperatingSystem,name=OpenFileDescriptorCount`), and it is a constant at 73 on my computer.

Closing as non reproducible.

**Comment by raccoon1515** [comment]
What means this lines? Is socket still open or closed?
`
java 5086 apb 3316u sock 0,8 0t0 10040260 protocol: TCP
`
Will socket close if `@OnError` method has failed to execute?

**Comment by sbordet** [comment]
In case of errors or orderly closes, Jetty will close the TCP connection.

Again, there are a million cases that may happen when handling errors and closes so it may be possible that we don't close the TCP connection in rare edge cases, but so far we are not aware of any leak.
