### ISSUE TITLE
Jetty 9.4.25 stops responding after a few hours

### ISSUE THREAD

**Issue by japgolly** [eclipse/jetty.project#4476]
**Jetty version**
9.4.25.v20191220

**Java version**
OpenJDK 64-Bit GraalVM CE 19.2.1

**OS type/version**
Both on AWS using Amazon ECS-optimised Linux, and at home running Arch Linux.

**Description**
I have a single webapp that I serve with Jetty. Using 9.4.25 everything is fine but then after around 2 hours or so it stops responding. It's consistent too in that each time its restarted, it gets in to the same state, over and over again. Downgrading Jetty to 9.4.24, making no other changes, resolves the issue for me.

It looks to me that all threads are getting stuck blocking during `HttpOutput.close` which might make sense as there seemed to be a lot of change to `HttpOutput` since 9.4.24.

I've captured the following:
* [jetty config](https://github.com/japgolly/misc/blob/jetty_9_4_25_bug/config.txt)
* [debug logs](https://github.com/japgolly/misc/blob/jetty_9_4_25_bug/jetty.log)
* [jstack trace](https://github.com/japgolly/misc/blob/jetty_9_4_25_bug/jstack.txt)

**Comment by sbordet** [comment]
@japgolly you may be hitting a variant of #4461. Would you be able to try the current `jetty-9.4.x` branch and see if it works for you?

```
$ git clone https://github.com/eclipse/jetty.project.git
$ cd jetty.project
$ git checkout jetty-9.4.x
$ mvn clean install -DskipTests
```

**Comment by japgolly** [comment]
Hi @sbordet. I tried it and the problem no longer occurs. Looks like it's already fixed! Nice work!

I'll close this now. Cheers
