### ISSUE TITLE
Set value for maven.repo.uri

### ISSUE THREAD

**Issue by manikantannaren** [eclipse/jetty.project#4480]
**Jetty version**
9.4.9
**Java version**
Java 8
**Question**
I am trying to add logback to jetty and using the command ```java -jar ../start.jar --add-to-start=logging-logback --approve-all-licenses```

With the change of maven repo to https and central.maven.org is not longer functional, i would like to set the value maven.repo.uri=https://repo1.maven.org/maven2/

BTW the doc says "https://repo1.maven.org/maven2/" is the default, but when I execute the above command, the trace says it is trying to contact central.maven.org
```DOWNLD: http://central.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar to ${jetty.base}/lib/logback/logback-core-1.2.3.jar
java.io.IOException: URL GET Failure [501/HTTPS Required] on http://central.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
	at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:146)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.create(MavenLocalRepoFileInitializer.java:131)
	at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:280)
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:319)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:246)
	at org.eclipse.jetty.start.Main.start(Main.java:435)
	at org.eclipse.jetty.start.Main.main(Main.java:77)```

So the question: where do I set the property maven.repo.uri?

**Comment by joakime** [comment]
`maven.repo.uri` is a java system property.

The change from `central.maven.org` to `repo1.maven.org` occurred in commit https://github.com/eclipse/jetty.project/commit/07b336751938f0a104d08d1b90b4614d774fb665 as part of Issue #2472
Which was first available in Jetty 9.4.11.v20180605

Please be aware of the security reports on Jetty, as you should not be using a version of Jetty that old.
https://www.eclipse.org/jetty/security-reports.html

**Comment by manikantannaren** [comment]
@joakime Thanks for the response
I understand the concern you raised about a dated version. And I am moving to latest version.
For now I need a quick fix for my issue. setting the java system property seems to not work
I did this `java -Dmaven.repo.uri=https://repo1.maven.org/maven2/ -jar start.jar --add-to-start=logging-logback --approve-all-licenses`
It still tries with central.maven.org

```DOWNLD: http://central.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar to ${jetty.base}/lib/logback/logback-core-1.2.3.jar
java.io.IOException: URL GET Failure [501/HTTPS Required] on http://central.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
	at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:146)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileIni```

But list-config command correctly shows the property being set
```Properties:
-----------
 jetty.webapp.addServerClasses = ${jetty.base.uri}/lib/slf4j/,${jetty.base.uri}/lib/logback/
 logback.version = 1.2.3
 maven.repo.uri = https://repo1.maven.org/maven2
 slf4j.version = 1.7.25
```

**Comment by joakime** [comment]
The property `maven.repo.uri` was introduced via Issue #2403 - first appeared in Jetty release 9.4.10.v20180503

**Comment by bruceGordon** [comment]
Likewise I am seeing this issue after HTTP Central Maven access disabled.
Can anyone provide the exact command line syntax to overcome this issue(I am using a docker image with jetty 9.4.26)

DOWNLD: http://central.maven.org/maven2/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar to ${jetty.base}/lib/org/apache/commons/commons-pool2/commons-pool2-2.4.2.jar
2020-01-28 11:57:05.936  [0m[91mjava.io.IOException: URL GET Failure [501/HTTPS Required] on http://central.maven.org/maven2/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar
