### ISSUE TITLE
Jetty 9.3 distribution contains insecure http URLs within ALPN modules

### ISSUE THREAD

**Issue by esmailsh** [eclipse/jetty.project#4485]
**Jetty version** 9.3.27.v20190418

**Java version** 8u121

**Description** 
The The Central Maven Repository (https://blog.sonatype.com/central-repository-moving-to-https) is updating to https and when pulling and building jetty from: (https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.3.27.v20190418/jetty-distribution-9.3.27.v20190418.zip) the ALPN module pulls from `http://central ` which then fails. The update URL should be https://repo1.

**Comment by sbordet** [comment]
Is there a reason you are still using 9.3.x, since 9.4.x is the current stable release?

**Comment by esmailsh** [comment]
9.3x release is still being supported by jetty and it's a big change for us now to move from 9.3 to 9.4. But we're planning to upgrade but not right now (in afew months). We resolved this this issue by replacing the references 'http://central.' with 'https://repo1.'

**Comment by sbordet** [comment]
ALPN modules in Jetty 9.4.x now use the `maven://` scheme which defaults to `https://repo1.maven.org/maven2/`.
