### ISSUE TITLE
Review ReservedThreadExecutor's concurrency model

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#4495]
`ReservedThreadExecutor`'s `tryExecute()` method look suspiciously costly when you consider a machine with many cores.

Both the `ConcurrentLinkedDeque.pollFirst()` and `ReservedThread.offer()` calls don't look like they would perform too well in a highly concurrent environment.

**Comment by gregw** [comment]
The reserved thread executor needs to do two things:
1) take a reserved thread off a stack of reserved threads.
2) pass a task to that reserved thread to execute.

The `ConcurrentLinkedDeque` is used to implement the stack.  I had hoped it's concurrent nature would mean that it does scale whell in highly concurrent enviroments (ie lots of cores).  If `ConcurrentLinkedDeque` is not a scalable datastructure, then we need to find something else with stack semantics that does scale.   Note that FIFO queue semantics is not desirable as we want to take the most recently active thread as we believe it will most likely be on a core with hot caches.... although that premise is not tested and it may be that a threads path through the reserved executor will result in a change of core more often than not... so perhaps experimenting with a pure queue model is worthwhile?

The `ReservedThread.offer()` is implemented using standard `ReentrantLock` and `Condition` for the reserved thread to await for a task to be handed to it.  This should never be highly contended with only the reserved thread ever waiting on it's own condition and only a single other thread signalling that condition.  In a highly concurrent environment, it may be that 'offer' is called serially by many different cores, but it will never be called in parallel.   I really don't see why this data structure is suffering in a many core environment, specially nothing that explains the large spin time apparent in the flame graph.  Perhaps an `Exchanger<Runnable>` might be better optimized? But ultimately is uses much the same `LockSupport` as do `Condition`s

To proceed, I think we need to:
  + seek some flame graph data from other high core deployments to see if the results we have seen are universal or particular
  + write a load test for ReservedThreadExecutor that can reproduce the bad flame graph

**Comment by sbordet** [comment]
Just as a reminder, we discussed in the past that the logic in `ReservedThreadExecutor` has a lot in common with `SynchronousQueue`, so perhaps we really need to review whether we could use that rather than managing our own locks and queues, etc.

**Comment by gregw** [comment]
`SynchronousQueue` is a much better data structure to use than my suggestion of `Exchanger`.  
I'll prepare a PR to use that instead of a `Condition`, but it doesn't help us with the stack.

**Comment by gregw** [comment]
@lorban @sbordet See #4499 - we should have done that ages ago just for code simplicity.
Now let me think really hard if we really need a stack (== Deque)....

**Comment by sbordet** [comment]
@lorban do you have more thoughts about this issue?

**Comment by lorban** [comment]
@sbordet I wonder if the `ConcurrentLinkedDeque` `_stack` could be replaced by a `Pool`.

**Comment by gregw** [comment]
@lorban I don't think Pool is suitable as it expects number of entries that are taken from and put back into the pool.
The RTE is more like a quota, with a limit on the number of threads that can be waiting for a tryExecute, but those threads themselves are taken from the larger threadpool.   Once a reserved thread is given a task, it is no longer reserved and not counted in the RTE. The only thing special about it is that it will try to become a reserved thread again once it's task is complete.

**Comment by gregw** [comment]
By coincidence we have just started looking at this as it went stale.
WIP in experiment/jetty-12.0.x/reservedThreadExecutor

**Comment by gregw** [comment]
See #11498
