### ISSUE TITLE
Jetty 9.4 + - causing 401 issue especially in Production intermediately

### ISSUE THREAD

**Issue by deebaprithy** [eclipse/jetty.project#4500]
test

**Comment by olamy** [comment]
Can we have a more complete stack trace? The attached one doesn't show any issue with Jetty.

**Comment by gregw** [comment]
Strangely enough I can see a full stack trace in the notification email, but not here????
The full stack trace indicates that you are running Tomcat and not Jetty!!!

**Comment by deebaprithy** [comment]
[401_Unauthorized_Issue.txt](https://github.com/eclipse/jetty.project/files/4099134/401_Unauthorized_Issue.txt
sorry for delayed response, PFA the complete log

**Comment by jmcc0nn3ll** [comment]
@deebaprithy could you reach out to me at jesse@webtide.com please?
