### ISSUE TITLE
Review the need for SharedBlockingCallback in jetty-10

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4501]
The class `SharedBlockingCallback` is used as follows:
```java 
 try(Blocker blocker = sharedBlockingCallback.acquire())
 {
     someAsyncCall(args, blocker);
     blocker.block();
 }
```
Which does the following:
 + mutually excludes threads from entering the try block as only a single `Blocker` can be acquired
 + provides a Blocker instance which is essentially a `FutureCallback`
 + can optionally implement a maximum blocking timeout to prevent threads blockinmg forever if the callback is faulty

There are several possible problems with this:
 + it is not clear if mutual exclusion is really necessary in all usages, as the async method should also be able to resolve simultaneous calls.
 + if mutual exclusion is necessary, then it can be more efficiently achieved with a synchronized block rather than the more costly Lock and Condition mechanism used.
 + The cost of acquiring a shared Blocker is probably on par with the cost of creating a disposable FutureCallback
 + The PR #4472 includes a simpler BlockingCallback class that can also implement the max timeout.

Thus we should evaluate removing `SharedBlockingCallback` from jetty-10 or at least reducing its usage.

**Comment by gregw** [comment]
@sbordet @lorban I think this is probably a good idea to do?

**Comment by sbordet** [comment]
The main reason for `SharedBlockingCallback` was that the `Blocker` instance returned was allocated once, and then reused over and over, thus saving the allocation of the `Callback` required by the async call.

> The cost of acquiring a shared Blocker is probably on par with the cost of creating a disposable FutureCallback

The opposite of this statement was the reason to create `SharedBlockingCallback`.

To achieve the same, one would need a `j.u.l.Lock`, and a reusable `BlockingCallback` stored as field that can be reset (or autoresets when it's completed).

That is almost what `SharedBlockingCallback` is, apart that we don't use `await()/signalAll()` like `SharedBlockingCallback` does.

I think the pair `j.u.l.Lock` + `BlockingCallback` is simpler code to maintain than `SharedBlockingCallback`, so I'd go for simpler.

I would also try to see if `FutureCallback` and `BlockingCallback` can be merged into one.

**Comment by gregw** [comment]
Plus I think that in many cases we really don't need the `j.u.l.Lock` anyway, so we can just replace `SBCB` with a `FutureCallback` with `BlockingCallback` features added.

**Comment by lachlan-roberts** [comment]
@gregw SharedBlockingCallback usages in jetty-10 websocket have been replaced with FutureCallback. Now the only usage that remains is in `HttpOutput`.

**Comment by lorban** [comment]
Sorry for being late to the party, but I also agree that `SharedBlockingCallback` is trying to do too much. `FutureCallback` is a much simpler and more elegant mechanism and it should be used instead of `SharedBlockingCallback`.

**Comment by gregw** [comment]
Removing this from 10.0.0 project.   Once HttpInput refactor is in, we can look at review/simplification of HttpOutput to remove last usage of this class.
