### ISSUE TITLE
Windows authentication in jetty web socket client API

### ISSUE THREAD

**Issue by jijomonac** [eclipse/jetty.project#4503]
I am trying to create java standalone websocket client application using Jetty websocket client API. It is working fine with basic authentication. Is there a way to use windows authentication (Active directory)?

**Comment by sbordet** [comment]
`HttpClient` supports SPNEGO authentication, so it's just a matter of properly configuring `HttpClient`.

See examples at: https://github.com/eclipse/jetty.project/blob/jetty-9.4.26.v20200117/jetty-client/src/test/java/org/eclipse/jetty/client/util/SPNEGOAuthenticationTest.java

Once you have a configured HttpClient, you can pass it to WebSocketClient that will use it for the HTTP/1.1 upgrade to WebSocket.
