### ISSUE TITLE
X-Forwarded-Server header overwrites X-Forwarded-Host

### ISSUE THREAD

**Issue by LOCwalker** [eclipse/jetty.project#4504]
**Jetty version**
9.4.24

**Description**
Hi,

we recently upgraded from 9.4.18 to 9.4.24 and noticed that our URLs broke because the X-Forwarded-* headers are handled slightly differently in the latter version.
Our application is deployed behind a CDN (Fastly) and they set X-Forwarded-Server headers containing the host names of their proxies. Our application thus receives headers like this:
X-Forwarded-Server: cache-01
X-Forwarded-Host: example.com

In 9.4.18, ServletRequest.getServerName() would result in "example.com", which is the desired behavior.
However, in 9.4.24, the result is "cache-01" because ForwardedRequestCustomizer essentially loops through the HTTP headers in the order the client sent them and the first entry wins and sets the host field.
This behavior is especially bad because the result depends on the order of the headers, which according to https://tools.ietf.org/html/rfc2616 should not be the case.
The X-Forwarded-Server header is a bit obscure from my understanding (could not find anything official on it) and it should not have precedence over the X-Forwarded-Host header.
The previous implementation did a much better job at this, can we get this fixed?

[Buggy behavior](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L378) vs [how it was before](https://github.com/eclipse/jetty.project/blob/e3c8546667aca1ee0247dfc4154a6e7189a23c81/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L384).

A test somewhat like this in CheckReverseProxyHeadersTest.java should indicate the problem cleary:

```java
        // ProxyPass from example.com to localhost:8080 with reverse (X-Forwarded-Server, X-Forwarded-Host) order
        // the X-Forwarded-Host header should have precedence
        testRequest("Host: localhost:8080\n" +
                "X-Forwarded-Server: cdn.com\n" +
                "X-Forwarded-Host: example.com\n" +
                "X-Forwarded-Proto: https", request ->
        {
            assertEquals("example.com", request.getServerName());
            assertTrue(request.isSecure());
        });
```

**Comment by gregw** [comment]
As you say, the definition of `X-Forwarded-Server` is kind of confused.
For now I suggest  a work around of disabling that header with `customizer.setForwardedServerHeader(null)`

I'll consider if/how we can add precedence in the next release.

**Comment by LOCwalker** [comment]
Thanks, the proposed fix works for me! The workaround (calling `forwardedRequestCustomizer.setForwardedServerHeader(null);`) is of course also viable but depending on the meta framework used to bootstrap jetty, it is not necessarily straight forward to do.
