### ISSUE TITLE
Servlet 4 metadata-complete=true should skip introspection of annotations

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4506]
**jetty-10**

https://github.com/eclipse-ee4j/servlet-api/issues/144

Servlet Spec 4, Changes Since 3.1, pg A-203:

> Clarify metadata-complete in Section 8.1, “Annotations and pluggability”.

This clarification states that if metadata-complete==true, any annotation that has an equivalent in web.xml must be _ignored_. This includes all annotations for which jetty introspects on a servlet, filter or listener such as PostConstruct, PreDestroy, Resource, Resources, DeclaresRoles, ServletSecurity, MultipartConfig.

**Comment by olamy** [comment]
related to #4234?

**Comment by janbartel** [comment]
@olamy yes I believe so. Your issue states that if metadata-complete==true, then ServletSecurity should never be processed. According to the new wording of the servlet spec, that isn't true - when you programmatically add a servlet using the ServletContext.createServlet methods, then you always have to introspect it for ServletSecurity/Multipart/PostConstruct/PreDestroy etc annotations regardless of what metadata-complete says. My reading of the spec is:

1. web.xml metadata-complete==true: no discovered annotations, no introspection on descriptor defined servlets/filters/listeners but yes on programmatically created servlets/filters/listeners

2. web.xml metadata-complete==false, web-fragment.xml metadata-complete==true: no scan for discovered annotations on that fragment jar, no introspection on servlets/filters/listeners defined in that descriptor but yes on programmatically created servlets/filters/listeners.

3. web.xml metadata-complete==false, web-fragment.xml metadata-complete==false or no fragment descriptor:  scan for discovered annotations on that fragment jar, introspect servlets/filters/listeners defined via annotation or descriptor or programatically.

This issue is for cases 1 && 2: we have been introspecting servlets/filters/listeners defined in web.xml or web-fragment.xml with metadata-complete==true.
