### ISSUE TITLE
Servlet 4 Verify clarification of AsyncContext complete and dispatch

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4508]
**jetty-10**

Servlet Spec, Changes Since 3.1, pg A-204

> Clarify the behaviors of complete and dispatch in AsyncContext before the
> container-initiated dispatch that called startAsync has returned to the container.
> See Section , “AsyncContext” on page 2-13.

Verify that Jetty implements the clarification.

**Comment by gregw** [comment]
If any of the dispatch methods are called before the container-initiated dispatch
that called startAsync has returned to the container, the following conditions
must hold during that time between the invocation of dispatch and the return
of control to the container:
  * any dispatch invocations invoked during that time will not take effect until after the container-initiated dispatch has returned to the container.
  * any AsyncListener.onComplete(AsyncEvent), AsyncListener.onTimeout(AsyncEvent) and AsyncListener.onError(AsyncEvent) invocations will also be delayed until after the container-initiated dispatch has returned to the container.
  * any calls to request.isAsyncStarted() must return true until after the container-initiated dispatch has returned to the container.

**Comment by gregw** [comment]
I believe all of these conditions hold true.  We don't have a test for `isAsyncStarted()`, but the code is:
```java
            if (_state == State.HANDLING)
                return _requestState != RequestState.BLOCKING;
            return _requestState == RequestState.ASYNC || _requestState == RequestState.EXPIRING;
```
This while the request is dispatched (state==HANDLING) all async requests return true.
