### ISSUE TITLE
Enabling debug log throws NullPointer Exception

### ISSUE THREAD

**Issue by Amarendraar23** [eclipse/jetty.project#4524]
Jetty version = 9.4.26

Java version = IBM Jdk 1.8

OS type/version = RHEL 7.3

I enabled debug logs by adding the below options to jvm args.

> -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog -Dorg.eclipse.jetty.LEVEL=DEBUG

This throws Nullpointer exceptions whenever i try to access a ssl enabled page hosted on the jetty server.

Attaching the jetty logs here

[jetty.log.D20200129.T050713.zip](https://github.com/eclipse/jetty.project/files/4127380/jetty.log.D20200129.T050713.zip)

**Comment by sbordet** [comment]
The logs show 2 places where the NPE happens: `SslConnection:902` and `SslConnection:1317`.
For 9.4.26, those 2 lines are accessing field `LOG` which is `static final` and it is initialized.
I have no idea how you can get a NPE, unless it's a JVM bug.

**Comment by joakime** [comment]
Since the errors are on SSL, I think this is related to Issue #2921 and IBM's decision to NOT use RFC Standard Cipher Names.

**Comment by gregw** [comment]
Unable to replicate
