### ISSUE TITLE
Java RESTful Web Service return 404 error with jetty-maven-plugin: version problem?

### ISSUE THREAD

**Issue by andreabazerla** [eclipse/jetty.project#4525]
**Jetty version: 9.4.25.v20191220**

**Java version: 1.8.0_232**

**OS type/version: Linux Ubuntu 19.10**

Java Restful Web Service return 404 error, but it works with jetty maven plugin version 9.3.11.v20160721: why? Thanks

**Comment by janbartel** [comment]
@andreabazerla there's really not enough information here to be able to help you. 

Does it work with jetty-maven-plugin 9.4.25?
How is the configuration different between the plugin and running it in the distro?
What is the url that you use with the plugin vs with the distro?

**Comment by andreabazerla** [comment]
> @andreabazerla there's really not enough information here to be able to help you.
> 
> Does it work with jetty-maven-plugin 9.4.25?
> How is the configuration different between the plugin and running it in the distro?
> What is the url that you use with the plugin vs with the distro?

No, it doesn't work with the last version 9.4.25.v20191220 but with 9.3.11.v20160721 yes it works.

My program that I'm using is a simple Hello World RESTful Web Service in Java with jetty-maven-plugin.

The URL for testing it is a simple localhost:8080/api/test/...; with last version it doesn't work.

I'm following this italian tutorial, nothing in particular: https://www.html.it/guide/restful-web-services-in-java-con-jersey/

**Comment by andreabazerla** [comment]
SOLVED

I need to delete web.xml with my configuration via ResourceConfig extension class.
