### ISSUE TITLE
Experiment having jar with shaded classes relocated to jakartaee

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#4526]
the build will produce normal jar and same jar with relocating javax.servlet classes to the new namespace.
Still to figure out how to do it for jetty-home (tar.gz distribution) etc...

**Comment by jmcc0nn3ll** [comment]
Thinking a bit more about this approach.

What is stopping us from having the jetty-home artifact pulling the jetty javax.* artifacts and jakartaee.* shaded artifacts into separate lib directories, and then using the start.jar to toggle one or the other sets of jetty artifacts enabling either servlet 4.0 or servlet 5.0 packages?

That gives us one downloadable container for end users that they can choose which servlet package namespace they want to leverage?

**Comment by gregw** [comment]
@jmcc0nn3ll I think the problem is that we will need to shade almost every one of our jars above jetty-server so we will pretty much end up with:
```text
lib
 +- jetty-util-10.jar
 +- jetty-http-10.jar
 +- ee8
 |  +- servlet-api-4.0.jar
 |  +- jetty-server-10.jar
 |  +- jetty-xyz-10.jar
 +- ee9
    +- servlet-api-5.0.jar
    +- jetty-server-10-jakarta.jar
    +- jetty-xyz-10-jakarta.jar
```

It could be done, but I'm dubious is doubling our download size is worth avoiding jetty-home-10 and jetty-home-jarkarta-10 as two artefacts.
But worth considering both options.

**Comment by jmcc0nn3ll** [comment]
Well, I don't think download size is truly that important anymore, and this would be only until we roll a Jetty 11 that would be strictly the jakartaee.* space.

We could label it experimental in jetty-home and make use of [download] I guess.

**Comment by olamy** [comment]
we will have to almost shade everything.. (except jetty-util, jetty-http, jetty-io, ?)
maybe we can have at the beginning a jakartaee module so users who want to try it will have to install it (jars will be downloaded as well) and I guess this module will need to have a special treatment when starting.
?

**Comment by gregw** [comment]
Having a module is a good idea - specially as we can have mutually exclusive modules and can give a clear error message if they try to enable both javax and jakarta APIs (with javax being enabled by default initially).

Also good idea to have the jakarta module initially get its jars by downloading.  Once there is significant demand, we can include them.

**Comment by olamy** [comment]
bad size of this:
- pom of shaded will be very wrong (users will have a ton of xml to write)
- osgi manifest might be wrong in the shaded jar
