### ISSUE TITLE
On Jetty 9.4.26 maven.repo.uri is not taking effect

### ISSUE THREAD

**Issue by bruceGordon** [eclipse/jetty.project#4532]
Docker Image FROM jetty:9.4.26

RUN java  -Dmaven.repo.uri=https://repo1.maven.org/maven2/ -jar "$JETTY_HOME/start.jar"  --add-to-start=session-store-redis-remote,https

Error : - java.io.IOException: URL GET Failure [501/HTTPS Required] on http://central.maven.org/maven2/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar

**Comment by gregw** [comment]
I can't reproduce with a jetty module. eg:
```
docker run -it --rm jetty:9.4.26 java -Dmaven.repo.uri=http://unknown.example.com/ -jar /usr/local/jetty/start.jar --add-to-start=unixsocket
```
correctly fails as URI is unknown and the following works:
```
run -it --rm jetty:9.4.26 java -Dmaven.repo.uri=https://repo1.maven.org/maven2/ -jar /usr/local/jetty/start.jar --add-to-start=unixsocket
```

Can you provide session-store-redis-remote.mod ?

**Comment by joakime** [comment]
`session-store-redis-remote.mod` is using using a hardcoded `http://central.maven.org/...`

https://github.com/cloudbees/jetty-redis/blob/master/src/main/config/modules/session-store-redis-remote.mod
