### ISSUE TITLE
DoSFilter does not send an error status code when closing a connection, because of timeout

### ISSUE THREAD

**Issue by vrotaru-hpe** [eclipse/jetty.project#454]
Hi, guys, we are using Jetty and we have this issue, that the Jetty returns a 200 OK status code on a login form when the login fails after an unusually long timeout (30 seconds).

This was quite unexpected. ```DoSFilter``` just adds a header "Connection: Close" and shutdowns the connection. A 503 **Service Unavailable** seems a better option.

> The 503 (Service Unavailable) status code indicates that the server
   is currently unable to handle the request due to a temporary overload
   or scheduled maintenance, which will likely be alleviated after some
   delay.

I've put up a small project [dos-filter-example](https://github.com/vrotaru-hpe/dos-filter-example) demonstrating this behavior. If this is indeed a bug, it would be quite easy to contribute a fix.

But first, and foremost, I need to know that this is bug, and not expected behavior

**Comment by NickGushchin** [comment]
Faced same behavior, can anyone review this bug?

**Comment by sbordet** [comment]
I agree it's a bug, it should not return `200`.

Simple workaround is to override `closeConnection(..)` and customize the response status.

Probably the best solution would be to call `sendError(..)` like we do for other cases in `DoSFilter`.

Note to self: the test cases are a mess, they badly need some tough love.

**Comment by vrotaru-hpe** [comment]
That was fast. Thanks guys.
