### ISSUE TITLE
ProxyConnectionFactory should not ignore TLVs

### ISSUE THREAD

**Issue by jjspiegel** [eclipse/jetty.project#4540]
**Jetty version**
master

**Java version**
all

**OS type/version**
all

**Description**
In version 2 of the proxy protocol, it allows for application-specific TLV types:
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

See section 2.2.7.  Basically the type code in range  0xE0..0xEF gets associated with an arbitrary block of bytes.  

Currently it appears these custom TLVs are being ignored:
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java#L545

I think ideally these custom TLVs should be accessible by the underlying connection.  For example, proxyEndPoint could simply maintain a map from type -> byte[].  e.g. 

  default:
      proxyEndPoint.setTLV(type, value);

Or perhaps it could even reuse setAttribute() for this if it treats the type code as a string. 

There should be an associated getter or reader that the downstream Connection can invoke.  e.g.

    byte[] value = proxyEndPoint.getTLV(type)

**Comment by sbordet** [comment]
@gregw this pairs with the new enhancement we did on the client in #4421. 

What would be the best way to expose the TLV data?
Finding the `ProxyEndPoint` may be difficult (e.g. `SocketChannelEndPoint -> ProxyEndPoint -> DecryptedEndPoint -> HTTP2StreamEndPoint`), unless we introduce a "wrapper" `EndPoint.Wrapper` interface that can easily unwrap `EndPoint`s.

@jjspiegel is willing to produce a PR, but we need a good way to expose the TLV data.

**Comment by sbordet** [comment]
Or perhaps a bean listener that is invoked for TLV events?

**Comment by jjspiegel** [comment]
For my purposes, I think the next Connection in the chain will always be the one consuming the TLVs.  But I understand you need to do this in a way that is broadly applicable.  

I expect one common use case of these attributes is to do some sort of validation. In particular, I plan to close the connection if an attribute sent by the load balancer is not in some backend whitelist.  I'm not sure if this helps determine the best way to expose the TLV data...

**Comment by sbordet** [comment]
> In particular, I plan to close the connection if an attribute sent by the load balancer is not in some backend whitelist.

Where do you have this logic?

Is it in some Jetty `Handler`, or are you using Jetty embedded, so that you have access to Jetty APIs to close the connection?

Is it in some Servlet where you want to add `Connection: close` to the response?

**Comment by jjspiegel** [comment]
I'm using a custom ConnectionFactory/Connection (not http).  I haven't tried to make this validation yet but the thought was to check it in ConnectionFactory#newConnection.

i.e. inside this call:
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java#L604

If validation fails, I guess in theory I could close the EndPoint before the Connection object is even instantiated?

**Comment by sbordet** [comment]
> If validation fails, I guess in theory I could close the EndPoint before the Connection object is even instantiated?

Correct, although the client will have no idea why it has been closed (unless before closing you write a failure message).

**Comment by jjspiegel** [comment]
Yes, good point.  I need to think about that.

**Comment by jjspiegel** [comment]
I guess with your Wrapper idea, nested EndPoints would need to do something like this?
   
```
  while (true) {
      if (endPoint instanceof ProxyEndPoint) {
         ... do something ...
         break;
      } else if (endPoint instanceof Wrapper) {
         endPoint = ((Wrapper)endPoint).unwrap();
      }  else {
         break;
      }
  }
```

**Comment by sbordet** [comment]
Correct.
