### ISSUE TITLE
servlet context root mapping incorrect

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4542]
As per the testing in https://github.com/eclipse-ee4j/servlet-api/issues/300 we are incorrectly setting the pathInfo for context root matched requests

**Comment by gregw** [comment]
@olamy can you look to see if there is a TCK test for this and are we passing or not?  Please comment on the servlet-api thread with any relevant findings.

**Comment by olamy** [comment]
@gregw I cannot find anything for this in the TCK tests

**Comment by gregw** [comment]
OK, so we need to write our own test for this and then fix the behaviour.  @joakime do you want to have a go at this as I think the PathMapping stuff was last touched by you?

**Comment by joakime** [comment]
I'll give it a shot. :-)

**Comment by gregw** [comment]
I want to work on something fixable for a bit.... so I'll take this one back.
