### ISSUE TITLE
How to Load HTTP/HTTPS Connectors Prior to Deployment of  Applications ?

### ISSUE THREAD

**Issue by gopikrishnayaramothu** [eclipse/jetty.project#4545]
version -> jetty-distribution-9.4.12.v20180830

the main issue we are facing is http connectors are not being created prior to deploy of applications. is there any possibility to create connectors first and then deploy the applications ?

**Comment by joakime** [comment]
The default behavior is ...

1. Connectors created. (initialized)
2. Connectors opened. (bound to interface / port)
3. All other components started. (such as your webapp being deployed)
4. Connectors started. (accepting connections)

What specifically isn't working?

**Comment by gopikrishnayaramothu** [comment]
Thanks for reply.
Connectors are being created post deployment of all applications under webapps folders. Is there any possible option to create connectors prior to deployment action ?

**Comment by gregw** [comment]
The reason for starting the connectors last is to now allow any requests to be accepted that would return a 404 or 503.
Starting connectors first creates such a window in which requests can be received but there are no apps to handle them.

you are free to call start() directly on the connectors yourself if you wish.

**Comment by gopikrishnayaramothu** [comment]
thanks for the update :) closing the issue
