### ISSUE TITLE
XmlConfiguration constructor selection based on number of arguments

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4550]
**Jetty version**
9.4.x, 10.0.x

**Java version**
Perc Virtual Machine

See comment on #4086 regarding arguments

**Comment by sbordet** [comment]
@gregw what's this issue about? The link to the issue seems wrong.

**Comment by joakime** [comment]
Reopening as 9.4.27 version on PR #4553 is not merged yet.
