### ISSUE TITLE
Jetty Startup Time 

### ISSUE THREAD

**Issue by gopikrishnayaramothu** [eclipse/jetty.project#4551]
we are using jetty 9.4 version. we are deploying over 20 applications and jetty is taking around 5-10 minutes to deploy all the applications . is there any way to reduce the start up time ?

**Comment by olamy** [comment]
maybe you could use user mailing list for questions? https://www.eclipse.org/jetty/mailinglists.html

**Comment by sbordet** [comment]
@gopikrishnayaramothu Jetty itself starts in few milliseconds.
Likely what is taking time are the applications that take a long time to start up, for example because they do annotation scanning or even JDBC queries.
You need first to figure out what it is taking time to startup in your applications.

**Comment by olamy** [comment]
@gopikrishnayaramothu try to isolate which application takes more time. Annotation scanning can be time consuming (especially for war with a lot of classes/.jar files) looks at the  logs `Annotation scanning elapsed time=...ms`

**Comment by jmcc0nn3ll** [comment]
Regarding startup speed directly, there is a mechanism in Jetty that will allow you to chop out a lot of the normal startup activities called Quickstart.

https://www.eclipse.org/jetty/documentation/9.4.x/quickstart-webapp.html

If it is annotation and classloader scanning sorts of activities that are behind your slow startup then this can help ameliorate  them.

**Comment by janbartel** [comment]
The question seems to have been addressed, so I'll close this issue.
