### ISSUE TITLE
build a simple InboundJaxrsResponse object

### ISSUE THREAD

**Issue by garan82** [eclipse/jetty.project#4560]
**Jetty version**
jersey-client 2.27

**Java version**
1.8

**Question**
We have some code which works as follow.

    try {
        Response resp = someApiCall(...)
        return modify(resp);
    } catch (Exception e) {
        ...
        Response resp = Response.status(Response.Status.INTERNAL_SERVER_ERROR).build();
        return modify(resp);
    }

`modify(Response)` performs a few things that may call `readEntity()` or similar methods only available on InboundJaxrsResponse but not OutboundJaxrsResponse. However, `Response.status(Response.Status.INTERNAL_SERVER_ERROR).build()` returns OutboundJaxrsResponse. Is there a simple way to construct InboundJaxrsResponse object with response status code while everything else can be empty?

**Comment by olamy** [comment]
@garan82 any sample project on github?

**Comment by olamy** [comment]
not really related to Jetty
