### ISSUE TITLE
Jetty logging supporting Throwable as last argument

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4567]
**Jetty version**
10.0.x

**Description**
Like other logging frameworks, would be handy if Jetty logging (`StdErrLog`) could detect whether the last argument is a `Throwable` and if so print its stack trace.

In this way one could write:

```
logger.debug("Log {}", this, new Throwable());
```

rather than:

```
logger.debug("Log " + this, new Throwable())
```

**Comment by sbordet** [comment]
@joakime perhaps we can review the API and completely drop those that have an explicit `Throwable` last parameter, keeping just `Object...`?

**Comment by joakime** [comment]
Some other logging APIs.  (they actually use `Throwable` as the last argument)

* https://logging.apache.org/log4j/2.x/log4j-api/apidocs/index.html
* http://www.slf4j.org/apidocs/org/slf4j/Logger.html

**Comment by sbordet** [comment]
> Some other logging APIs. (they actually use Throwable as the last argument)

Yes, but there is no need to if you probe the last argument. One API only (`Object...`) does everything is needed.

**Comment by gregw** [comment]
If we are changing logging, should we switch to String.format style rather than {} style?

**Comment by joakime** [comment]
The `{}` style is the facade API that all loggers use, not just `StdErrLog`, but also `Slf4jLog` and `JavaUtilLog`

**Comment by joakime** [comment]
If we are entertaining the cleanup of the logging API, how about we just drop all of Jetty logging and use `slf4j-api` everywhere.
We could then just implement a slf4j-impl that is our StdErr output (a `JettyStdErrSlf4jImpl` which does our formatted output)?

I think this is a good direction to go, and should also have a positive impact (simplifying) on our jetty-home logging modules.

**Comment by olamy** [comment]
@joakime good idea! worth to try but no more LOG.ignore?

**Comment by joakime** [comment]
# Proposal

## Drop org.eclipse.jetty.util.log

The entire package `org.eclipse.jetty.util.log` is deleted

## Create jetty-slf4j-impl module

A new module called `jetty-slf4j-impl` is created.

This module performs the equivalent to Jetty's StdErrLog.

* Same output formatting as `StdErrLog` in 9.x
* Supports `jetty-logging.properties` for configuring logging levels

It has a `META-INF/services/org.slf4j.spi.SLF4JServiceProvider`

A package space of org.eclipse.jetty.logging
A JPMS of jetty-logging ?

This new module would be included as a `<scope>test</scope>`
across the other Jetty modules that need it for testing.

## Migrate logging properties

Existing properties

* `org.eclipse.jetty.util.log.class` (classname, default "org.eclipse.jetty.util.log.Slf4jLog") - use to select the logger
* `org.eclipse.jetty.util.log.announce` (boolean, default "true") - used to control announcement text `"Logging to {} via {}"`
* `org.eclipse.jetty.util.log.IGNORED` (boolean, default "false") - used to control if Log.ignored() should be shown or not
* `org.eclipse.jetty.util.log.StdErrLog.TAG_PAD` (number, default "0") - used for minimum padding width of the Thread.name
* `org.eclipse.jetty.util.log.SOURCE` (boolean, default "false") - used as default for showing of source (filename and line number) in stacktraces
* `org.eclipse.jetty.util.log.stderr.SOURCE` (boolean, default "false") - used for showing of source (filename and line number) in stacktraces
* `org.eclipse.jetty.util.log.stderr.LONG` (boolean, default "false") - used for condensing the logger name package
* `org.eclipse.jetty.util.log.stderr.ESCAPE` (boolean, default "true") - used for escaping the output of the logger message.

Dropped properties

* `org.eclipse.jetty.util.log.class` - controlled by slf4j-api now
* `org.eclipse.jetty.util.log.announce` - controlled by slf4j-api now
* `org.eclipse.jetty.util.log.SOURCE` - we only have 1 logger now.

Renamed properties

* `org.eclipse.jetty.logging.IGNORED` (boolean, default "true") - used to control if Log.ignored() should be shown or not
* `org.eclipse.jetty.logging.THREAD_PADDING` (number, default "0") - used for minimum padding width of the Thread.name
* `org.eclipse.jetty.logging.SOURCE` (boolean, default "false") - used for showing of source (filename and line number) in stacktraces
* `org.eclipse.jetty.logging.NAME_CONDENSE` (boolean, default "true") - used for condensing the logger name package
* `org.eclipse.jetty.logging.MESSAGE_ESCAPE` (boolean, default "true") - used for escaping the output of the logger message

## Migrate source to use slf4j

Migrate code from ...

``` java
import org.eclipse.jetty.util.log.Log;
import org.eclipse.jetty.util.log.Logger;

private static final Logger LOG = Log.getLogger(DoSFilter.class);
```

... to ...

``` java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

private static final Logger LOG = LoggerFactory.getLogger(DoSFilter.class);
```

The usage of `Log.ignore(Throwable)` would need to be migrated as well.

``` java
LOG.trace("IGNORED", cause);
```

The `org.eclipse.jetty.util.StacklessLogging` would be moved to
`org.eclipse.jetty.logging.StacklessLogging` (in the new `jetty-slf4j-impl` 
module) to provide the same behaviors as before for testing.

## New logging modules for jetty-home

The existing logging modules in Jetty 9.4.x are ...

* console-capture.mod
* jcl-slf4j.mod
* jul-impl.mod
* jul-slf4j.mod
* log4j2-api.mod
* log4j2-impl.mod
* log4j2-slf4j.mod
* log4j-impl.mod
* logback-impl.mod
* logging-jetty.mod
* logging-jul.mod
* logging-log4j.mod
* logging-log4j2.mod
* logging-logback.mod
* logging-slf4j.mod
* slf4j-api.mod
* slf4j-jul.mod
* slf4j-log4j.mod
* slf4j-log4j2.mod
* slf4j-logback.mod
* slf4j-simple-impl.mod

We would simplify this a great deal to just ...

* console-capture.mod
* logging-jetty.mod
* logging-jul.mod
* logging-log4j.mod
* logging-log4j2.mod
* logging-logback.mod

Where each logging module captures all logging implementations
via the various slf4j bridge jars, and enables the appropriate
slf4j implementation jar based on your logging module selection.

The new modules would also no longer force a forking of a JVM.

**Comment by jmcc0nn3ll** [comment]
Any special configuration challenges to capturing and directing webapp logging?

**Comment by sbordet** [comment]
Had a look at `System.Logger` APIs, whether we can use those instead of SLF4J now that they are in JDK 11.

But no, they lack features like MDC and the APIs require to pass a `Level` as first parameter (`log(DEBUG, ...)` rather than `debug(...)`) - not ideal.

I think the big overhaul of the logging would be a good change, but for Jetty 12.

For Jetty 10, probing just the last parameter should be simple and small enough.

**Comment by joakime** [comment]
> Any special configuration challenges to capturing and directing webapp logging?

It would just be a configuration of the `WebAppContext` / `WebAppClassLoader` and its `ClasspathPattern` (Server & System) to support that.
We could have that be a module / configuration as well. something called `webapp-centralized-logging`

**Comment by gregw** [comment]
I like the proposed change to direct use of log4j, but I don't think we can go directly there without deprecating the existing mechanism.

However, I do think within 10/11 we can change to using log4j directly and deprecate the old API, then 12 we can remove the old API.  Means we still have some module complexity for a while.. at least in the naming, but the contents should become simpler.   If we do it this way, no need to hold up 10.0.0 for this to be implemented.    

So let's just go with sniffing the last param for now.

**Comment by joakime** [comment]
log4j1 is not very performant and is abandoned now.
log4j2 is too bleeding edge, is still unstable, and has a history of JVM hanging issues.

Opened PR #4570 for the last argument sniffing for Throwable.

The time needed to make the change in the Proposal is only about 2 days.

**Comment by joakime** [comment]
Opened Issue #4572 to track the larger Proposal separately

**Comment by gregw** [comment]
ooops did I say log4j,  I meant slf4j!  slf4j is just a facade like our own Logging API, so it essentially gives us the same flexibility, but with less complexity at the small cost of an API jar dependency.

**Comment by joakime** [comment]
Reopening for Jetty 9.4.x too

**Comment by joakime** [comment]
PR #3596 merged.
