### ISSUE TITLE
[Report] ServletHandler.addServletWithMapping Error

### ISSUE THREAD

**Issue by ideatuples** [eclipse/jetty.project#4574]
**Jetty version**
9.4.26.v20200117

**Java version**
JDK 11 (Amazon Corretto)

**OS type/version**
Ubuntu 18.04.3 LTS

**Description**
Hi Eclipse.Jetty,

I have been trying to configure with XML for DefaultServlet.
So, I added a file which name is 'jetty-test.xml' in $JETTY_BASE/etc

But I found that adding servlet to ServletHandler with Servlet object argument is failed.

`public ServletHolder addServlet​(java.lang.Class<? extends javax.servlet.Servlet> servlet, java.lang.String pathSpec)`

I got an error message when I started the server 'NoSuchMethodException'

Whereas, calling the method 'addServlet' with String type argument works very well.

I, hereby, request you to investigate the method works properly.

Thank you

**Comment by sbordet** [comment]
@ideatuples you probably have a problem in your XML, which you don't show.

> I, hereby, request you to investigate the method works properly.

The method works properly and we have tests that confirm this.

**Comment by ideatuples** [comment]
Hi sbordet, 

For the clarification of the problem, I attached 2 log files here.

[jetty-test1.log](https://github.com/eclipse/jetty.project/files/4209856/jetty-test1.log)
< File 1. _SevletContextHandler.addServlet​(java.lang.Class<? extends javax.servlet.Servlet> servlet, java.lang.String pathSpec)_ >
[jetty-test2.log](https://github.com/eclipse/jetty.project/files/4209859/jetty-test2.log)
< File 2. _ServletContextHandler.addServlet​(java.lang.String className, java.lang.String pathSpec)_ >

As you can see, jetty-test1.log got the exception NoSuchMethodException and jetty-test2.log has no problem.

The only difference between 2 files is the data type of first argument _class or String_ nothing more.

I already knew that there is no fault on your jetty main source codes in Java.

But, what I wanted you to investigate was about the integrity between the source codes in Java and the XML configuration engine (including XML schema).

Thank you

Postscript: I would like to upload 2 XML configuration files, but GitHub doesn't let me upload them.

**Comment by sbordet** [comment]
> But, what I wanted you to investigate was about the integrity between the source codes in Java and the XML configuration engine (including XML schema).

There is nothing to investigate. We read the XML file and invoke Java code.
The error you get it's because you have a problem in your XML.

> Postscript: I would like to upload 2 XML configuration files, but GitHub doesn't let me upload them.

Just copy/paste them in a comment, redacting sensitive information.

**Comment by ideatuples** [comment]
Hi sbordet,
Here is the config files and I hope you to change the extention from .txt to .xml and run one by one.

The only difference between 2 files is data type as I said.

[jetty-test1.txt](https://github.com/eclipse/jetty.project/files/4210380/jetty-test1.txt)
[jetty-test2.txt](https://github.com/eclipse/jetty.project/files/4210381/jetty-test2.txt)

Ah.. Plus..
I did try to turn on proxy feature with jetty-proxy.xml (non-modified) but didn't work at all.
But.. I added proxy.mod (non-modified) to start.d directory and it works fine..

Why? I don't know..

I just did consent that you gave configuration files that works properly whether it is XML formatted or mod extension formatted.

That is all I did try.

Thank you

**Comment by sbordet** [comment]
@ideatuples I don't understand.

You have one wrong XML file and you complain that it does not work. 
Well, it does not work because it's wrong, as it tries to pass a Servlet _instance_ where a _class_ is required. 

Then you have one correct XML file and it works.
Well, it works because it's correct, as it passes a String to the overloaded version of `addServlet` that takes a String as first parameter.

>  I did try to turn on proxy feature with jetty-proxy.xml (non-modified) but didn't work at all.

"didn't work at all" is too little information to help you. 
I can assure you that it works, so you probably have something else wrong in your configuration.

**Comment by ideatuples** [comment]
Hi Simone,

Have you checked out _ServletContextHandler.addServlet_ method signature in the API document?

According to API doc ([ServletContextHandler](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/servlet/ServletContextHandler.html)), 

`public ServletHolder addServlet​(java.lang.Class<? extends javax.servlet.Servlet> servlet, java.lang.String pathSpec)`

is completely legal and it is equivalent to 

`public ServletHolder addServlet​(java.lang.String className, java.lang.String pathSpec)`

Also, 

`public void addServlet​(ServletHolder servlet, java.lang.String pathSpec)`

Correct?

In _jetty-test1.xml_, Line 30-37 should have same effect as Line 30-33 in _jetty-test2.xml_.

My point is why hasn't it worked with jetty-test1.xml but jetty-test2.xml?

Thank you

**Comment by sbordet** [comment]
> In jetty-test1.xml, Line 30-37 should have same effect as Line 30-33 in jetty-test2.xml.

As I have already said, in `jetty-test1.xml` you are creating a new _instance_ via the element `<New>`.
The method signature takes a `Class`.

**Comment by ideatuples** [comment]
Hi Simone, 

So.. you mean that it is a dynamic class loading and ServletHolder is a helper class for that purpose and it is encouraged to use ServletHolder rather than the dynamic class loading if there is a servlet exists

That's why 2 other addServlet methods has return value which type is ServletHolder.

OK.. I got it.

Thank you

**Comment by sbordet** [comment]
Please close the issue if it's resolved.

**Comment by ideatuples** [comment]
OK.. The case is now closed..

Thank you for the answer that made me stay up at night.
