### ISSUE TITLE
Servlet 4.0 and 5.0 support in Jetty-10/11/12?

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4578]
This issue has been opened to discuss the possibility of supporting both Servlet 4.0 and 5.0 in the jetty-10 release (edit: now probably the Jetty-12 release)

**Comment by gregw** [comment]
Currently the core of jetty is dependent on the `javax.*` servlet-api in a way that is best illustrated with the main signature of the [`Handler`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/Handler.java#L69) class:
```java
    public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)
        throws IOException, ServletException;
```

This API passes both the core jetty request (called `baseRequest` throughout the code) and the servlet-api version of the `request` (potentially wrapped by application).  The core jetty response is always obtainable from the `baseRequest` but the servlet-api version of the response is also passed in as it may also be wrapped by the application.

It so happens that the `baseRequest` implements `HttpServletRequest` so we can often just cast between these two views of the request.  However, because wrapping may be applied we don't actually cast that often and the code mostly makes a distinction between working with the mutable server view of the request and the less mutable API view of the request. Utility methods are used to convert to and from so that wrappers can be handled.

Thus while the core of jetty is now dependent on the javax.servlet.* API it is not really architecturally bound to it, as the distinction is already made between jetty request and possibly wrapped API request.  Thus it is a small step to take to consider the possibly wrapped javax API request to be an always wrapped jakarta API request, even if the base request remains dependent on javax.* APIs

Thus I proposed the following path to support Jakarta APIs:
1. Create a new  jetty Handler API that does not explicityly use the `javax.servlet.*` nor `jakarta.sevlet.*` request/response in it's signature. Instead the base jetty request/response will be augmented with the ability to carry loosey typed wrapper(s).   Initially this new Handler API will still be indirectly dependent on `javax.servlet.*` because the jetty request implements it.
2. Implement the ability to add a tree of new Handlers as a branch of an old Handler tree.  This will probably be done at the ContextHandler level, so it will be possible to have a context that is implemented only with newHandlers.
3. Create new versions of ServletHandler, SessionHandler, SecurityHandler, WebAppContext that are based on the new Handler, but using the `jakarta.servlet.*` APIs.  This will mostly be a copy/paste/edit job, but some cleanup can probably be done as the new code will never need to deploy a 2.4 webapp (for example).   With this, we would have a jetty-10 that could run both servlet 4.0 and 5.0.   Servlet 4.0 would run exactly as in jetty-9, whilst Servlet-5.0 would always go via a new Handler and the base request would always be wrapped with an api request. Cross context dispatch from 4.0 to 5.0 would either not be supported or only supported if there are no application wrappers.
4. In future, jetty-11 would completely replace the old Handler with the new Handler tree and the core jetty request would no longer implement either javax nor jakarta APIs.  There would always be the distnction between the base request implementing the jetty mutable API and an API wrapper of that request.  Hopefully this would allow major simplification of the core request and the complexities of the the individual APIs would be moved to the wrappers.

**Comment by gregw** [comment]
Key to this approach working is that we need a good reimagining of the `Handler` API and contract.  So the first question is What should it be called?  If we are to run with both new and old `Handler`s it would be good to have an easy way to distinguish between them, but I can't think of any good pairings and all of the following are BAD:
   - `NewHandler`
   - `Handler2`
   - `HandlerNT`
   - `Processor`
   - `Valve`
   - `Handler2`

So I'm currently left with just the verbose `RequestHandler`???

This raises the possibility of an alternate path:  
 1. release jetty-10 as is with just Servlet-4.0 support
 2. release jetty-11 with the new handler architecture and both 4.0 and 5.0 support that would replace jetty-10

The viability of this path depends a lot on the risk/complexity/time needed to implenent the new handler API for all of jetty. So the next few comments will discuss the new Handler API and contract

**Comment by gregw** [comment]
The key features that need to be considered in a new Handler API include:

Wrapping:
------------
If the wrapper is not passed in the handle signature, then we need CRUD mechanisms for the wrappers.  Note that there are serveral types of wrappers:
 + API wrappers that will wrap jetty requests, responses, contexts, etc. as one API or another.
 + API adaptors that will wrap application supplied Listeners to jetty Listeners... potentially Filters and Servlets could also be wrapped to appear as new Handlers?
 + Application wrappers for request and responses only that are passed into dispatchers and startAsync.

It may be simplest to just handle a single wrapper that is instantiated as an API wrapper, but may be later replaced with an Application wrapper with specific actions.  However it may be more precise and flexible to separately track the concept of an API wrapper vs an Application wrapper.

Target
------
Do we really need target as a separate arg to request?  It is really only used for named dispatches, which is really an API concern and could be dealt with in the request API wrapper or even as an request attribute.

Scopping:
-----------
Whilst revisting the Handlers, we should reconsider the ScopedHandler mechanism that was retrofitted to Handlers when we could not significantly change the API.  Currently the API is:
```java
    public void doScope(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)
        throws IOException, ServletException
    {
        nextScope(target, baseRequest, request, response);
    }
```

At the very least this should be changed to:

```java
    public void doScope(Request baseRequest, Scope scope)
        throws IOException, ServletException
    {
        scope.doScope(baseRequest, request);
    }
```
Other questions:
 + Should all `Handler`s be scoped handlers?
 + Should the deep stack approach be replaced with separate `enterScope` and `exitScope` calls?

Handled
---------
The `Request.setHandled(boolean)` method should probably be replaced with a boolean return from the `handle` method.  The problem with a boolean on the request is that it can be difficult to distinguish between an async handling and a called handler

**Comment by gregw** [comment]
Note about Application wrappers is that the spec requires that any wrapper passed in to a dispatcher is provided as the instance to the target resource.  Thus a wrapped request/response cannot be wrapped by the container to adapt the API, thus it is impossible to do cross context dispatch (which was a really bad idea in the first place)!

**Comment by gregw** [comment]
OK first handler experiment on removing target... yes it is best as a separate argument.

There are two primary cases where the target of the handling is completely different from the paths returned by the request:
 + `Dispatcher.include` where the request paths are unchanged, but servlet spec attributes are set with the include path - these attributes will now be in javax and jakarta variants
 +  named dispatches, where the target is a servlet name and URI matching does not apply

So while it is a complication that is very spec dependent, I think we should leave target in our handler signature... perhaps with improved javadoc to say that it will either be:
 + the full decoded URI path when outside of a context
 + the decoded path within a context when within a context
 + a resource name if it doesn't start with '/'

**Comment by janbartel** [comment]
As for names for the "new" Handler interface, it's almost impossible to find one! I don't like any of the following either:

- Manager
- Coordinator
- Visitor
- Mediator
- NeutralHandler
- AgnosticHandler

Maybe we should rename Handler in jetty-10 to something else, and call the new one "Handler"??!

Note that it won't just be the Handler level that needs to be independent of the javax. and jakarta. namespaces, here's just a couple of examples:  

- in session processing, both the Session class and the SessionCache interface use the HttpServletRequest
- many of the classes and interfaces in jetty-security module refer to javax.servlet classes/interfaces

**Comment by sbordet** [comment]
Why `Processor` is bad? It's what is does, it processes the HTTP request.

`HttpHandler`?

Just a reminder that `target` is also a `host:port` in case of CONNECT, and could be `*` in case of OPTIONS and PRI.

**Comment by jmcc0nn3ll** [comment]
Rode? The nautical term for a cable or chain that connects the anchor to the boat or ship.

Shank, Stem, Anchor, something fun.

**Comment by gregw** [comment]
I'm now more inclined to change the Handler contract for the whole server.  I'm given that a go in a branch and will make a draft PR soon.
So far it is not very invasive... just ubiquitous.  But worth it if we can avoid needless name duplication and better prepare for the future.

**Comment by gregw** [comment]
Summary of discussions so far:

Versions
-----------
Jetty Version | Servlet 4.0 (javax.*) | Servlet 5.0 (jakarta.*) | comment | release prospects
------------ | ------------- | -- | -- | --
10 | Yes | No | Almost ready to go | ASAP
11 | No | Yes | Simple rename of 10 | Soon after 10 if needed
12 | Yes | Yes | Needs significant work | 3 to 6 months if possible

This issue is primarily about discussion if 12 is possible.

jetty-server
--------------
+ Currently has support for dispatchers and DispatchType.  There is an argument to say that neither is needed at the server level and only need to be introduced in servlet layer.
+ ErrorHandler - is already messy and needs refactoring anyway.  PageMapping needs to be deferred to api layers but without dependencies on attribute names nor API.
+ ResourceService - needs to be refactored so that wrapping of output stream and interception of headers can be done without preventing efficient async serving of content.
+ HandlerCollection - should be HandlerList in many situations.  Let's do it and remove the current hack in HandlerCollection.

**Comment by gregw** [comment]
Thought bubble time..... 

one of the worst things about the servlet spec is that it both allows application wrapping of the request object, but also insists that the container doesn't wrap in order to do things like `RequestDispatcher.forward`.  A forward needs to mutate the following attributes of the request:
   + requestURI and variants
   + contextPath, servletPath and pathInfo
   + query string
   + The parameter map (if there was a query string)
   + the attribute map (with at least 5 special attributes set)

Then after the dispatch, all these values need to be reset to the original values.    This would be super easy to do with a request wrapper, that substitutes/merges the values only if the getters are called and then the wrapper is discarded after the forward is complete.    However, this cannot be done because the API also insists that if an application wraps the request, then the same instance of the wrapper will be delivered to the target servlet and may be down cast to the wrapper class.    Thus we've been forced to implement an architecture where our primary request class is mutable and we actually change all those values and then revert them after the forward.

However, if we are going to a API neutral request class, that will always need to be wrapped by an API class, then this gives us the opportunity to consider having an immutable request object, that once created contains the original values as they were read off the wire and they cannot be changed.  The server could then work as follows:
 1. A request `R` is received and created.
 2. It may be customised by the ForwardedRequestCustomizer, which would need to wrap it to change host, address protocol etc. fields so the request would now be `C(R)`
 3. It may be customised by the SecureRequestCustomizer, but this just sets attributes so no wrapping is needed. Attributes a passed by the wrapper to original request so it is now `C(R')`
 4. maybe we have the rewrite handler installed, and it may also want to mutate the request, perhaps with multiple rules.  So one mutating rule applied the request would be `C(F(R'))`
 5. Ultimately the request is passed to a servlet context, where it is wrapped by an Servlet API wrapper as `S(W(C(R')))` and passed to the servlet
 6. A filter/servlet may wrap the request with an application wrapper: `A(S(W(C(R`))))`
 7. A filter/servlet may forward the request with a `RequestDispatcher`, we implement this by inserting a forward wrapper `F` underneath the api wrapper `S` So the result is `A(S(F(W(C(R`)))))`, which preserves the application wrapper as the outermost wrapper
 8. After the forward, the forward wrapper is removed and the request reverts to `A(S(W(C(R`))))`
 9. After the response is generated, we log the request using `R` and ignore any of the wrappers.... however we may need API aware logger that can retrieve some values from some API wrappers

Being immutable can greatly simplify much of the code, avoid async races (when other threads look at a mutating request class) and improve efficiency at some cost in garbage.  The most frequent case is going to be handling a request like `S(R)` or maybe `S(C(R))`.  However the danger is that we could get some very deep wrappings if lots of rewrite rules applied and/or we were very strict with what we mean by mutating a request.     Obviously request attributes are not mutations - but what about Sessions? Authentication?    I think the rule is, stuff that came over the network is immutable - so method, URI, headers etc. but server interpretations of those: target, session, authentication, attributes etc. are still mutable on the request.

I don't propose we go big bang towards that architecture, but as we rework the core dispatcher to be API neutral we can think about it and try the wrap under approach.  If that works then we can try making aspects of the request immutable.

**Comment by sbordet** [comment]
@gregw another thought: the previous `Handler` design was based on the fact that requests were synchronous. This allowed the use of `try/finally` idioms in many places, where in the `finally` we were doing cleanup work.

But with async processing of requests, the `finally` had to become more complicated.

Is it worth to design the new Handler to be asynchronous by default, so that the `finally` are replaced by some (possibly) asynchronous callback method?

**Comment by gregw** [comment]
@sbordet at the very least we need better support for async completion as the logic in finally blocks can be rather convoluted.
However, I do think the scoping nature of the try/finally calling hierarchy of the existing handlers is meaningful in an async environment, as it allows a thread to be annointed with thread locals, classloaders, etc. in an extensible way.   Hmmm but perhaps we need to make that scoping easier for async callbacks to perform - currently we have support only at the context level.

**Comment by darmbrust** [comment]
Is this still a plan for jetty 12?  I'm guessing that supporting javax.* and jakarta.* is still in the 3-6 month out range?  I've been testing with 11, trying to update some code... but sort of a mess, when many projects are ignoring that the rename even happened, so I've ended up with a mixed code base.  Anyone aware of a codebase that can present javax code as jakarta code?  I've seen the project tomcat references for changing a war file after its built, but I want to keep using jetty for tests, etc, and have it work without building the war first.

**Comment by gregw** [comment]
@darmbrust We are a few weeks (at most) away from having jetty-10.0.0 (servlet 4.0) and jetty-11.0.0(servlet 5.0) releases.

We have not yet got any firm plans for a jetty-12, least not committing to supporting both javax and jakarta namespaces... even if we did, it would likely not be within the same context... and no matter what history tells us it is much more than 3-6 months away. 

Plus we'd really like to spend the next year working on features, performance, scaling, etc. rather than just renaming!

What projects have not even started renaming? Have you tried shading their jars to the new namespace?

cheers

**Comment by stolsvik** [comment]
I'd just want to chime in with a comment from a user: This sounds _very_ promising. I've been looking at the rename with dread, we have literally tons of projects using the Servlet API, we have several common libraries that also use and expose the Servlet API, and the prospect of having to also make two distinct versions of all these, and the update paths - I feared that we'd have to stay on Jetty 9-10 for decades! The first thing I wondered when I saw the 10/11 divide was why it wasn't possible to make a solution to handle both of the APIs instead? So, yes, _please_ make this happen!

**Comment by joakime** [comment]
> I feared that we'd have to stay on Jetty 9-10 for decades! 

That's incredibly unlikely, the technologies of the open internet move far faster than that.
I predict that you will reach a point in the next 6 years where the browsers and protocols have moved at such a pace that your old code is no longer viable, and you have no options that will let you fix your code with the `javax.<spec>` technologies.

Jetty has multiple versions supported right now.
From : https://www.eclipse.org/lists/jakartaee-tck-dev/msg01186.html

> Jetty 9.4.x - Supports Java EE 7 / Servlet 3.1 / javax.servlet / Java 8 - support until Java 8 interest dies out (that means drop dead final possible year is 2030 which is the same end year as the super expensive support contracts from oracle/azul/etc)
> Jetty 10.0.x - Supports Jakarta EE 8 / Servlet 4.0 / javax.servlet / Java 11 - this is our active mainline development branch.
> Jetty 11.0.x - Supports Jakarta EE 9 / Servlet 5.0 / jakarta.servlet / Java 11 - this is our jakarta.* namespace branch, and is essentially in lockstep release/change/merge wise with Jetty 10.0.x
> Future:
> Jetty 12.0.x - Supports Jakarta EE 10 / Servlet ?? / jakarta.servlet / Java ??

@stolsvik Here's a small example of the problem: any solution would mean each context would be tied to either javax.servlet OR jakarta.servlet, not allowing cross-context dispatch, which is mandated by the Servlet spec for support.  This means javax.servlet.RequestDispatcher would be neutered and non-functional outside of the specific context. There's also the fact that HttpSession (and it's contents) would be limited to exactly 1 context, always.  No more shared Session management at the server level.

Then there's the legal aspect, once we moved to Jakarta EE 9 (which is where Jakarta Servlet 5.0 was introduced), we were no longer legally allowed to use "javax" anywhere (not in classes, not in attribute names, not in javadoc, not in xsds, not in java namespaces, not in the API, not even in the spec document itself) - blame the Oracle lawyers for this one.

The old `javax.servlet` is dead (legally speaking), _there will never be another update on that namespace_, you can either wait for the tooling to catch up and make the transition to `jakarta.<spec>` easier for you, or you can migrate your projects to the new namespace manually (not as difficult as it seems, many 3rd party libraries have either already done this, or are actively doing it, and those that are not doing it need to be reminded that the "big bang" has happened, either they update or they get left behind).

**Comment by stolsvik** [comment]
>Here's a small example of the problem: any solution would mean each context would be tied to either javax.servlet OR jakarta.servlet, not allowing cross-context dispatch, which is mandated by the Servlet spec for support. This means javax.servlet.RequestDispatcher would be neutered and non-functional outside of the specific context. There's also the fact that HttpSession (and it's contents) would be limited to exactly 1 context, always. No more shared Session management at the server level.

Interestingly, none of those problems would affect me at all. And I believe this holds for _very_ many users of Jetty and Tomcat and others. Think about Spring Boot. All of our projects runs on a "home cooked" variant of the concepts of Spring boot, i.e. "single executable war file".

Also, Servlet 4 - which pretty much no user has even looked at yet (and Servlet 5 is just a Jakarta rename, isn't it?) would be sufficient for quite a while.

Thus, if it was possible, it would be awesome if Jetty (11,) 12, 13, 14 .. could support the Servlet 4 API _as long as possible_, in addition to the absurd forced rename. So, if e.g. Jetty 15 supported Jakarta EE 13, (Jakarta) Servlet 7, but _also_ Servlet 4, I believe you'd have a fantastic solution for quite some years.

> not allowing cross-context dispatch, which is mandated by the Servlet spec for support.

If you would be _legally_ unable to violate that, another option could be that you had a switch for the entire instance. _Either_ it ran as Servlet 4, _or_ Servlet 5++. That flag could, as a convenience, be auto-chosen based on the "first deployed war".

**Comment by gregw** [comment]
We are planning on supporting servlet 4.0 and 5.0 for some time.... just not in the same server.

**Comment by joakime** [comment]
Closing, Jetty 12 now has "environments" that allows deploying webapps based on different environments on the same Jetty instance.

Jetty Environment ID | Servlet | EE
--- | --- | ---
`ee8` | javax.servlet 4.x | Java EE 8
`ee9` | jakarta.servlet 5.x | Jakarta EE 9
`ee10` | jakarta.servlet 6.x | Jakarta EE 10
