### ISSUE TITLE
Update quality list handling

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#458]
Update the quality list implementation and move to HttpField class: https://github.com/eclipse/jetty.project/blob/master/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java#L819-L866

**Comment by joakime** [comment]
Closing as commit c768828703ac25b8bcba08c74658d6c1775d03a2 introduced `QuotedQualityCSV` and `QuotedCSV`
