### ISSUE TITLE
Add URI mapping to InetAccessHandler

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4598]
InetAccessHandler was added in #882, but lacks the URI mapping support that exists in IPAccessHandler

**Comment by gregw** [comment]
Note also that InetAccessHandler has connector name and InetAddress matching, but doesn't use the correct logic from IncludeExcludeSet.matchCombined - so some work is needed... specially if a third include/exclude set is added.

The logic has to be ((NoIncludes || (included by one set)) && (excluded by no sets))

**Comment by gregw** [comment]
@lachlan-roberts have a go at this!

**Comment by joakime** [comment]
Reasoning for this decision was briefly mentioned in Issue #1072 and an alternate solution was proposed by @sbordet
