### ISSUE TITLE
Review DateCache for performance

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4605]
StdErrLog uses DateCache and separately handles the ms.  So why can't we depend on jetty-util?      I know it is a very old class.... but when it was introduced it was VERY beneficial.  If we are doing full logging, we can avoid thousands of time formats per second - well worth it!

_Originally posted by @gregw in https://github.com/eclipse/jetty.project/pull/4601_

We should do some tests for performance on this venerable class, now that Jetty 10 is Java 11+

**Comment by gregw** [comment]
I'm pretty sure that we will still find this class worthwhile in cases were we do hundreds or thousands of formats per second.   So I don't think it needs to be reviewed for efficiency.  Perhaps it's API and implementation can be updated a bit

**Comment by joakime** [comment]
This is a historical class.

It existed well before the new date time APIs in Java 8.
Those original classes were slow, expensive to create and use, and were not thread safe ([even causing performance issues on heavy use](https://stackoverflow.com/questions/22098904/how-to-improve-performance-of-simpledateformat-wrapped-in-threadlocal))

The new Java 8 APIs for Date / Time are [6x faster then the original date time APIs](https://madhuraoakblog.wordpress.com/2017/06/08/performance-improvement-with-date-time-api-of-java-8/) and do much of what we are doing in the DateCache already.
Even for the use case of "thousands of formats per second".

**Comment by gregw** [comment]
Maybe - but that is a premise you must prove before taking out usages of DateCache rather than something we need  to disprove to argue to reinstate optimisations that have bin in place for decades!

**Comment by joakime** [comment]
Agreed, data is important here.

**Comment by gregw** [comment]
I think DateCache is fine as is.  If we are serving 10,000 requests per second, then it will always be better to do a single date format per second than 10,000 identical formats.  
We can review if DateCache ever shows up on a flame graph or we are changing code that calls it.
