### ISSUE TITLE
Jetty reaching out to w3.org for schema definitions

### ISSUE THREAD

**Issue by manishpandeyhere** [eclipse/jetty.project#4608]
**Jetty version**
9.4.12
**Java version**
java-1.8.0-openjdk-1.8.0.212.x86_64
**OS type/version**
Centos 7.2
**Description**

Firewall blocked 7 outbound connections from storage's IP to the IP 128.30.52.100 on port 80 on the 30th October between 11:30 and 11:30 EST

https://nimblestorage--c.na97.content.force.com/servlet/servlet.FileDownload?file=00P2H00001IoYW9

- Further checks on LAB arrays suggested that DNS www.w3.org and hans-moleman.w3.org which belongs to "Massachusetts Institute of Technology (mit.edu)", are found on many files.

find . -type f -iname "*.xml" -exec grep "w3.org" {} +

nimble-tvl-1-A:/# find . -type f -iname "*.xml" -exec grep "w3.org" {} +
./opt/jetty/webapps.vasa/vasa/WEB-INF/web.xml:
./opt/jetty/webapps.vasa/vasa/WEB-INF/cxf-servlet.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/webapps.vasa/container-provider/WEB-INF/web.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/etc/webdefault.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/etc/webdefault-nimble.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/etc/webdefault-nimble-vasa.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/webapps/vmware-perfmetrics/WEB-INF/web.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/webapps/plugin/WEB-INF/web.xml:
./opt/jetty/webapps/npm-hostservice/WEB-INF/web.xml:
./opt/jetty/webapps/rest/WEB-INF/web.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
./opt/jetty/webapps/api/WEB-INF/web.xml: xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

Customer has a security concern, that Jetty reach out to w3.org for schema definitions. 

Questions:
A. Can we understand why it does so?And is it a security risk? 
B. Did this start happening only from Jetty 9.4.12 onwards?

**Comment by joakime** [comment]
I just set my `/etc/hosts` entry to a bogus ip for `www.w3.org` and tried the demo-base tests with success.
I was expecting warnings, errors, etc...

```
$ grep w3.org /etc/hosts
192.168.1.5  www.w3.org   
```

Note: on my network, there is nothing using 192.168.1.5

Are you perhaps replacing your xml parser on your environment?  (this was a common practice long ago, and is no longer recommended)

**Comment by manishpandeyhere** [comment]
Sorry for delay!

If i understand your question correctly. you ask if we have replaced parser offlate to parse the nimble-vasa.xml.
We have not done so, in fact that is a configuration that we give to jetty and if I am not wrong Jettyu uses its parser to parse the config.

By the way, Can i please ask , how is this question related to Jetty reaching out to  w3 for validations DTD?

**Comment by joakime** [comment]
The XML parser can come from the JVM, or from a library (like Apache Xerces).

The loading of XML should be using our **XML Catalog** for Servlet and related specs to load the XML / DTD / XSDs from information present in the classloader or filesystem (never the network).

See: https://github.com/eclipse/jetty.toolchain/blob/master/jetty-schemas/src/main/resources/javax/servlet/catalog.xml

But for `w3.org`, that would be more fundamental lookups of the basics for XML (like _XMLSchema_), that the JVM XML parser uses it's own catalog for.

For loading things like ...

**Maven Project**

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```

or **Servlet Web Fragments**

``` xml
<web-fragment 
   xmlns="http://java.sun.com/xml/ns/javaee" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-fragment_3_0.xsd" 
   version="3.0"> 
```

or the **Servlet Web Descriptor**

Old Servlet 2.5 example

``` xml
<web-app 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns="http://java.sun.com/xml/ns/javaee" 
   xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" 
   xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" 
   id="WebApp_ID" 
   version="2.5">
```

Servlet 3.1 example

``` xml
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
```

If you are not using the JVM XML parser (for example, you have Xerces present in your classpath) then there's probably other configuration you need to do for that alternate XML parser to know how/where to load its content from (other then the network).

**Comment by manishpandeyhere** [comment]
Thanks!,

One of our customers have a problem as Jetty is reaching out to w3 on the network.

"But for w3.org, that would be more fundamental lookups of the basics for XML (like XMLSchema), that the JVM XML parser uses it's own catalog for."

Are you suggesting that changing configuration to point to file system, from where it loads the content , will stop the lookups happening to w3.org.Or are you suggesting that w3 lookups for basic xml would still happen regardless?

Please note the concern that we are trying to address is lookup of w3.org.Can you please help clarify?
