### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by kaifeng-h** [eclipse/jetty.project#4619]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 12 inconsistent libraries and 3 false consistent libraries.

Take org.apache.derby:derbytools for example, this library is declared as version 10.4.1.3 in tests/test-loginservice, 10.12.1.1 in tests/test-sessions/test-jdbc-sessions and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take org.apache.derby:derbytools for example, if we harmonize all the library versions into 10.14.2.0. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table is listed below. It shows the overall harmonization effort by modules. The columns represents the number of library APIs and API calls(NA,NAC), deleted APIs and API calls(NDA,NDAC) as well as modified API and API calls(NMA,NMAC). Modified APIs refers to those APIs whose call graph is not the same as previous version. Take the first row for example, if upgrading the library into version 10.14.2.0. Given that 1 APIs is used in module tests/test-loginservice, 0 of them is deleted in a recommended version(which will throw a NoMethodFoundError unless re-compiling the project),  1 of them is regarded as modified which could break the former API contract.

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|tests/test-loginservice|1(1)|0(0)|1(1)|
|2|tests/test-sessions/test-jdbc-sessions|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. The table is listed below. 

|Module|File|Type|API|
|-|-|-|-|
|tests/test-loginservice|tests/test-loginservice/src/test/java/org/eclipse/jetty/DatabaseLoginServiceTestServer.java|modify|org.apache.derby.tools.ij.runScript(java.sql.Connection,java.io.InputStream,java.lang.String,java.io.OutputStream,java.lang.String)|

As for false consistency, take org.slf4j slf4j-jdk14 jar for example. The library is declared in version 1.7.25 in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[eclipse jetty.project.pdf](https://github.com/eclipse/jetty.project/files/4270529/eclipse.jetty.project.pdf)

**Comment by olamy** [comment]
thanks for the notice.
Please note all those librairies are used in test scope only.
But anyway we will fix this.

**Comment by kaifeng-h** [comment]
Thanks for that.

**Comment by olamy** [comment]
done with https://github.com/eclipse/jetty.project/commit/3a8b45d20c35ed77fc66d582d7d453f3e2b9276a
