### ISSUE TITLE
Using console-capture with StdErrLog results in empty log file

### ISSUE THREAD

**Issue by TezzerFX** [eclipse/jetty.project#4620]
The "jetty.console-capture.dir" was set and the server created the ...jetty.log file on launch, but the log messages were still being written to the console's Stderr and Stdout. As a workaround I replaced the
StdErrLog.class in the jetty-util-9.4.27.v20200227.jar with the version from jetty-util-9.4.26.v20200117.jar which restored the 9.4.26 behavior, writing the messages to the log file as per the 9.4.27 documentation.

**Comment by joakime** [comment]
Interesting ...

**Comment by joakime** [comment]
A minimal fix to `console-capture.xml` can be found at in commit 6bf868e03b5982aa067238b1c8cd6dbaf1f4580d

https://github.com/eclipse/jetty.project/blob/6bf868e03b5982aa067238b1c8cd6dbaf1f4580d/jetty-util/src/main/config/etc/console-capture.xml#L20-L23

Line 21

**Comment by joakime** [comment]
Opened PR #4630

**Comment by joakime** [comment]
The minimal fix to `console-capture.xml` (in commit 6bf868e03b5982aa067238b1c8cd6dbaf1f4580d) would make `console-capture` dependent on StdErrLog, which it historically hasn't been.

So the behaviors of StdErrLog with regards to alternate PrintStream has been restored, allowing console-capture to do it's thing.

**Comment by TezzerFX** [comment]
Thanks Joakim, that did the trick... Prior to the quick fix there was warning message
`"...WARN:oejx.XmlConfiguration:main: Ignored arg: <Arg name="threadpool"><Ref refid="threadPool"/></Arg>",` what was that about?

**Comment by joakime** [comment]
@TezzerFX opened Issue #4631 about the WARN on threadpool.  It's harmless, and works in spite of the warning message, but still needs to be fixed (in PR #4632)

**Comment by joakime** [comment]
Merged PR #4630

**Comment by joakime** [comment]
This fix didn't get merged to Jetty 10.0.x properly.
