### ISSUE TITLE
How to WebSocketClient resource usage?

### ISSUE THREAD

**Issue by TheWizz** [eclipse/jetty.project#4637]
Jetty version: 9.4.18.v20190429

Java version: 1.8-202

I'm using the WebSocketClient. Things works fine. However, profiling this shows a significant number of threads (almost 10) being started for each new WebSocketClient. This is the code I use to open a connection:

```
Socker(String url, int maxMsgBytes, Map<String, String> headers) throws Exception {
	URI uri = URI.create(url);
	ClientUpgradeRequest upgradeRequest = new ClientUpgradeRequest();
	headers.forEach((key, value) -> upgradeRequest.setHeader(key, value));
	http = new HttpClient(mSSLFact);
	client = new WebSocketClient(http);
	client.setMaxTextMessageBufferSize(maxMsgBytes);
	http.start();
	client.start();
	client.connect(this, uri, upgradeRequest);
}
```

Is there anything I can do to reduce the number of threads being created for each websocket client opened? E.g., can any of the allocated resources be "shared" across multiple clients, thereby reducing overall resource consumption for multiple simultaneous websocket client connections. Or am I doing anything that seems unnecessary, that may cause excessive thread creation?

-JM

**Comment by joakime** [comment]
Create 1 (and only 1) `WebSocketClient` (and `HttpClient`) for the life of the JVM, then use it connect to any number of remote endpoints with any combination of local endpoint implementations.

Think of the WebSocketClient and HttpClient like a web browser, and each .connect() a tab in that web browser.
You don't force a new web browser instance (and all of it's resources) for each web page you open, right?

The threads created are to manage things like the java.nio selector, and the physical connection, and dispatched calls if using streaming APIs for read.
You'll have a number of selector threads, that won't grow no matter how many active connections you have.
You'll have a thread for each physical connection.

**Comment by TheWizz** [comment]
Thanks. That sounds like a good plan. If I need a unique set of headers per request, then I'd still need to instanciate a unique ClientUpgradeRequest for each request. But perhaps that's not a heavy operation, and would be quite OK. Presumably it's the HttpClient and WebSocketClient that are the heavy hitters here, right?

-JM

**Comment by joakime** [comment]
Yes, the WebSocketClient and HttpClient are heavyweight components, it's not wise to constantly create/start/use/stop/gc each of them.

**Comment by TheWizz** [comment]
Thanks for confirming. Will I need to take any explicit steps to stop those components' lifecycles at shutdown, or will they "register themselves" somehow so that stopping of Jetty during server shutdown automatically stops those too?

-JM

**Comment by joakime** [comment]
The components are just threads.
Your threading model and decisions are ultimately going to determine how those components behave at shutdown.
You can, alternately, just `.stop()` the components on your own too.
Or you can register `Runtime.getRuntime().addShutdownHook(new MyRuntimeShutdownImpl());` to do that work for you.

**Comment by TheWizz** [comment]
Sorry to resurrect this thread. What if I want to have different setMaxTextMessageBufferSize for different websockets? Then I can't share the WebSocketClient, as this setting is on the WebSocketClient. Perhaps I can still share the underlying HttpClient, and that would save some overhead?

-JM

**Comment by joakime** [comment]
If you have questions, its best to either [open a new question](https://github.com/eclipse/jetty.project/issues/new/choose), [ask on stackoverflow](https://stackoverflow.com/questions/tagged/embedded-jetty), or to use the [jetty-users mailing list](https://accounts.eclipse.org/mailing-list/jetty-users).

The short answer to your question.

WebSocketClient is just the default value.
The Session is also used (configure it there in onOpen [via the WebSocketPolicy on the Session](https://github.com/eclipse/jetty.project/blob/jetty-9.4.27.v20200227/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/Session.java#L110)).
Or if you [declare a value on your `@WebSocket` annotations](https://github.com/eclipse/jetty.project/blob/jetty-9.4.27.v20200227/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/WebSocket.java#L44) then that value is used as the default (not the WebSocketClient).
