### ISSUE TITLE
Improve reporting of SSLHandshakeException

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#464]
`SSLHandshakeException`s are a bit special in that they report some important information (e.g. no ciphers in common, wrong certificate, etc.) that are useful to applications.

Jetty should try its best to report `SSLHandshakeException`s as is, so that the client or the server can rely on them if they get thrown, rather than getting them wrapped into other exceptions, or lost because other exceptions got thrown in their place.

**Comment by johngmyers** [comment]
Per #444, this regressed in 9.3.8. The catch block in `SSLConnection.fill(ByteBuffer)`, which does a `close()`, which throws a `ClosedChannelException`, losing the original exception.

**Comment by gregw** [comment]
@johngmyers I think we need to tunnel the original exception through the close calls so that it can be added as a cause to the `ClosedChannelException`, because strictly speaking the operation is not excepting because of the original exception, it is excepting because the handling of the original exception chose to close the connection.

**Comment by dekellum** [comment]
Hi Guys, I'm seeing a ClosedChannelException as well with 9.3.8 via default config, simple HttpClient request for the following publicly accessible URL:

https://ecf.scb.uscourts.gov/cgi-bin/rss_outside.pl

Note however that this works without any error for me on 9.3.6, so the ClosedChannelException on 9.3.8 might be masking a more fundamental regression (e.g HTTPS access failing here)?  Could you please comment on what might have changed/regressed in these recent patch releases?  Also I'm happy to file a new report if that's more appropriate.  Didn't want to start there if it was going to be interpreted as a duplicate.

**Comment by johngmyers** [comment]
I believe this regression was caused by d36e586

**Comment by sbordet** [comment]
See also #574.
