### ISSUE TITLE
org.eclipse.jetty.util.thread.ShutdownThread._thread potential memory leak

### ISSUE THREAD

**Issue by itselov** [eclipse/jetty.project#4640]
**Jetty version**
9.4.25.v20191220

**Java version**
java-1.8.0-openjdk-1.8.0.232.b09

**OS type/version**
Linux 2.6.32-573.22.1.el6.x86_64

**Description**
We performed load testing of our application (REST API Server) in lab and found that right after load test ends heap size increased almost twice and kept on same level.

We gather heap dump and found that almost half of heap consumed by org.eclipse.jetty.util.thread.ShutdownThread._thread.

Heap dump is too large to upload, so attaching link to dropbox:
https://www.dropbox.com/s/dx4fho9cazgj6hm/dump.hprof%202.zip?dl=0

Also link to heap dump analyzer report:
https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMC8wMy80Ly0tZHVtcC5ocHJvZi56aXAtMjEtMTMtMjAuanNvbi0t

I have similar symptoms on prod environment, but on bigger scale. Can share heap dump from it too if needed.

Can it be memory leak?

**Comment by joakime** [comment]
This is likely fixed in Jetty 9.4.26.v20200117 as a result of Issue #4575

The current stable release is 9.4.27.v20200227, please try with that version.

**Comment by itselov** [comment]
@joakime, thx for quick response.
Will try 9.4.27.v20200227 soon.

For the sake of experiment we downgrade our lab from OpenJDK (java-1.8.0-openjdk-1.8.0.232.b09) to Oracle JDK (jdk1.8.0_192-amd64) and issue no longer reproducible.

Can it be platform dependent?
