### ISSUE TITLE
Empty "X-Forwarded-Port" header results in NumberFormatException

### ISSUE THREAD

**Issue by poochiethecat** [eclipse/jetty.project#4645]
**Jetty version**
9.4.25.v20191220
**Java version**
OpenJDK build 1.8.0_232-09
**OS type/version**
Linux 4.15.0-74-generic #83~16.04.1-Ubuntu
**Description**
If the "X-Forwarded-Port" header is present but empty, a NumberFormatException is thrown:

`java.lang.NumberFormatException: For input string: ""`

This is likely not a correct state for the headers, but it would be nice to at least have a more descriptive error message.

Unfortunately there is no way for me to influence the header value that I receive, so any workarounds for this would be appreciated as well.

**Comment by lachlan-roberts** [comment]
@poochiethecat we have decided it would be best to throw `BadMessageException`and return a 400 status code if a bad or empty port was provided in this header.

If you want a workaround to ignore this header you could configure a `HttpConfiguration.Customizer` such as [RewriteCustomizer](https://www.eclipse.org/jetty/javadoc/9.4.27.v20200227/org/eclipse/jetty/rewrite/RewriteCustomizer.html) in front of your `ForwardedRequestCustomizer`, you could use `HeaderRule` to apply some change to the empty header.

**Comment by lachlan-roberts** [comment]
Fixed with PR #4648.
