### ISSUE TITLE
How do you use HTTP2Client send to POST parameters?

### ISSUE THREAD

**Issue by pedro-abundio-wang** [eclipse/jetty.project#4653]
**Jetty version**
9.3.3.v20150827
**Java version**
JDK 8u121
**OS type/version**

**Description**
How to post parameter using http2client

i have reading example code like :

https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/http2/client/HTTP2Client.html

and i want to know post parameter and i can receive those parameter in http2 server like 

request.getParameter("key")

can you provide any example code for me?

thanks a lot

**Comment by pedro-abundio-wang** [comment]
client code:

	public void post(String host, int port, String uri, String params) throws Exception{

        // Create and start HTTP2Client
        HTTP2Client http2Client = new HTTP2Client();
        SslContextFactory sslContextFactory = new SslContextFactory(true);
        http2Client.addBean(sslContextFactory);
        http2Client.start();

        // Connect to host
        FuturePromise<Session> sessionFuturePromise = new FuturePromise<>();
        http2Client.connect(sslContextFactory, new InetSocketAddress(host, port),
                new ServerSessionListener.Adapter(), sessionFuturePromise);

        // Obtain the client Session object.
        Session session = sessionFuturePromise.get(5, TimeUnit.SECONDS);

        // Prepare the HTTP request headers.
        HttpFields requestFields = new HttpFields();

        // Prepare the HTTP request object.
        MetaData.Request request = new MetaData.Request("POST", new HttpURI("https://" + host + ":" + port + "/" + uri),
                HttpVersion.HTTP_2, requestFields);



        // Create the HTTP/2 HEADERS frame representing the HTTP request.
        HeadersFrame headersFrame = new HeadersFrame(0, request, null, true);

        // Prepare the listener to receive the HTTP response frames.

        Stream.Listener responseListener = new Stream.Listener.Adapter()
        {
            @Override
            public void onHeaders(Stream stream, HeadersFrame frame)
            {
                System.out.println(frame);
            }

            @Override
            public void onData(Stream stream, DataFrame frame, Callback callback)
            {
                System.out.println(frame);
                callback.succeeded();
            }
        };

        // Send the HEADERS frame to create a stream
        FuturePromise<Stream> streamFuturePromise = new FuturePromise<>();
        session.newStream(headersFrame, streamFuturePromise, responseListener);
        Stream stream = streamFuturePromise.get(5, TimeUnit.SECONDS);

        // Use the Stream object to send request content, if any, using a DATA frame.
        ByteBuffer content = ByteBuffer.wrap(params.getBytes());
        DataFrame requestContent = new DataFrame(stream.getId(), content, true);
        stream.data(requestContent, Callback.NOOP);

        // Thread.sleep(TimeUnit.SECONDS.toMillis(20));

        http2Client.stop();
    }

server code :

        switch (request.getMethod()) {
            case "POST":
                handlePost(request, response);
                break;
        }	

when i call http request method like 

request.getParameters() returns nothing

**Comment by sbordet** [comment]
Use `HttpClient`:

```java
// Use the HTTP/2 transport.
HttpClient client = new HttpClient(new HttpClientTransportOverHTTP2(new HTTP2Client()), new SslContextFactory.Client());
client.start();

// Add fields.
Fields fields = new Fields();
fields.put("key", "value");

// Send request.
ContentResponse response = client.POST("https://localhost:8080/path")
    .content(new FormContentProvider(fields))
    .send();
```
