### ISSUE TITLE
Configure_10_0.dtd should be validated in jetty-xml

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4657]
Starting in Jetty 10.x we should enable XML+DTD validation in jetty-xml to present warning when the XML violates the DTD rules.

This validation exists, but is currently false in Jetty 9.4.x

**Comment by gregw** [comment]
Currently the parser defaults to validating if 
`SAXParserFactory.newInstance().getClass().toString().startsWith("org.apache.xerces.")`

But it appears that the current implementation provided by the JVM is `com.sun.org.apache.xerces.`
