### ISSUE TITLE
Jetty XML should fail if there is a `<Arg>` misplaced

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4658]
I would like to see a test where there is a `Arg` misplaced, as below, so that we define in a test how we should behave.

```xml
<Configure ...>
  <Arg>...</Arg>
  <New ...>...</New>
  <Arg>...</Arg>
</Configure>
```

_Originally posted by @sbordet in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzgyNjQxOTQ3/pull_requests/unread_timeline_

**Comment by gregw** [comment]
Note that will currently fail with an ISE saying the "Arg was not skipped" - so I think the action is good, but the message could be improved.

**Comment by joakime** [comment]
Seems to be addressed already.
