### ISSUE TITLE
Jetty 9.4.21+ calls ServletContextListener.contextDestroyed() too early

### ISSUE THREAD

**Issue by jeffrey-easyesi** [eclipse/jetty.project#4662]
**Jetty version**
9.4.26.v20200117
**Java version**
OpenJDK 1.8.0_242
**OS type/version**
Ubuntu 18.04
**Description**
We have a web application using Jetty's WebAppContext. It uses a javax.servlet.ServletContextListener class provided by Spring (ContextLoaderListener) to create the main Spring container, which is depended upon by various Filters, Servlets, and a custom SessionCache.

Up to Jetty 9.4.20, when stopping the server, the SessionCache is shut down first, then Filters, then Servlets, and finally the ServletContextListener. However, after https://github.com/eclipse/jetty.project/pull/4083 the ServletContextListener is shut down first, which breaks the other components' shutdowns as the Spring container they depend on is already gone.

This new behavior contradicts the [ServletContextListener.contextDestroyed javadoc](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextListener.html): "All servlets and filters will have been destroyed before any ServletContextListeners are notified of context destruction."

**Comment by janbartel** [comment]
Yes, I think your analysis is correct and the ServletContextListener.contextDestroyed methods are being called before the filters and servlets are destroyed. Working on a fix.

**Comment by gregw** [comment]
Here is an interaction diagram of our horrendously complex start/stop sequence, indicating where the mistake is and how we think it should be fixed.    This seriously needs to be simplified in a future major release!

![cdraw](https://user-images.githubusercontent.com/70829/76522663-3f9ec400-6467-11ea-8eb6-09a3490482ee.png)

**Comment by janbartel** [comment]
Fixed for 9.4.28.
