### ISSUE TITLE
Short reads break form-data multipart parsing

### ISSUE THREAD

**Issue by rhuitl** [eclipse/jetty.project#4673]
**Jetty version**
9.4.27

**Java version**
11, 13

**OS type/version**
Linux, MacOS

**Description**
The parsing of form-data multipart requests is broken in Jetty 9.4.27 (and probably earlier) when data cannot be read fast enough.

In my production setup, the problem occurs with requests where the multipart boundary stretches across the 1346 bytes that were available when the parser reads data for the first time. The problem is quite hard to reproduce reliably in production, as it depends on how fast data is sent to the server. It probably also depends on how packets are fragmented on the TCP/IP level.

The difference between a working attempt and a non-working one is whether the multipart request can be read all at once (first two log lines) or whether it got fragmented (second two log lines):

```
INFO:oejh.MultiPartParser: parse up to 2692, last false, data: java.nio.HeapByteBuffer[pos=0 lim=2692 cap=16384]
INFO:oejh.MultiPartParser: parse up to 1346, last false, data: java.nio.HeapByteBuffer[pos=0 lim=1346 cap=16384]
```
```
INFO:oejh.MultiPartParser: parse up to 1346, last false, data: java.nio.HeapByteBuffer[pos=0 lim=1346 cap=16384]
INFO:oejh.MultiPartParser: parse up to 2692, last false, data: java.nio.HeapByteBuffer[pos=0 lim=2692 cap=16384]
```

While writing a test case for this issue, I noticed that I had to return 0 bytes after simulating a short read, otherwise the problem would not occur.

Both the new `org.eclipse.jetty.http.MultiPartFormInputStream` and the old `org.eclipse.jetty.util.MultiPartInputStreamParser` are affected by this issue.

I created a test that reproduces this problem with `MultiPartFormInputStream`. The test output shows that the entire next part, including the multipart boundary, leaks into the content of the previous part.

https://gist.github.com/rhuitl/cbeeada5dfdb7dac9bc89e65cf38d349

```
FragmentingByteArrayInputStream#read([B@3444d69d, 0, 16384)
Reading not 16384 but up to 130
FragmentingByteArrayInputStream#read([B@3444d69d, 130, 16254)
Returning no data (simulating slow client)
2020-03-15 17:01:13.533:INFO:oejh.MultiPartParser:main: parse up to 130, last false, data: java.nio.HeapByteBuffer[pos=0 lim=130 cap=16384]
FragmentingByteArrayInputStream#read([B@3444d69d, 0, 16384)
Reading not 16384 but up to 130
2020-03-15 17:01:13.542:INFO:oejh.MultiPartParser:main: parse up to 112, last false, data: java.nio.HeapByteBuffer[pos=0 lim=112 cap=16384]
FragmentingByteArrayInputStream#read([B@3444d69d, 0, 16384)
Returning no data (simulating slow client)
FragmentingByteArrayInputStream#read([B@3444d69d, 0, 16384)
Reading not 16384 but up to 130
2020-03-15 17:01:13.542:INFO:oejh.MultiPartParser:main: parse up to 0, last true, data: java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]


java.lang.AssertionError: 
Expected: is "value1"
     but: was "value1\r\n------WebKitFormBoundaryhXfFAMfUnUKhmqT8\r\nContent-Disposition: form-data; name=\"field2\"\r\n\r\nvalue2"
```

**Comment by lachlan-roberts** [comment]
@rhuitl thanks for reporting this. We now have a fix for this merged into the jetty-9.4.x branch (#4680), and this will available in the 9.4.28 release.

**Comment by rhuitl** [comment]
Thanks @lachlan-roberts! As far as I can see, only the new `MultiPartFormInputStream` (RFC7578 compliant) implementation is using `SearchPattern`, the old legacy (but still default) `MultiPartInputStreamParser` does not. Just want to confirm that this is not an oversight on my end, because I'd have to make adjustments to use the new implementation then.

**Comment by lachlan-roberts** [comment]
@rhuitl yes that's correct, you will have to update your code to use `MultiPartFormDataCompliance.RFC7578` to get the fix for this. 

In Jetty-10 the LEGACY version has been removed completely, and there are also some other known issues with it, so I would recommend updating to use the new version anyway.
