### ISSUE TITLE
jetty-util must not depend on jetty-slf4j-impl

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4685]
**Jetty version**
10.0.x

**Description**
`jetty-util`'s POM has a dependency on `jetty-slf4j-impl`.

This is wrong because embedded application that use `jetty-util` but also SLF4J with another binding (e.g. LogBack) will now have 2 bindings in the classpath and the logging system won't be configured properly.

The `module-info.java` is correct since it only requires the SLF4J API.

The `jetty-util` POM needs to be modified to make the `jetty-slf4j-impl` in scope `test` (because `StacklessLogging` is used in tests).

**Comment by joakime** [comment]
Should I include `jetty-slf4j-impl` in `jetty-all`?

**Comment by sbordet** [comment]
Is `jetty-all` still a thing in 10? I thought we were removing it.
