### ISSUE TITLE
Allow DistributionTester to work with log files, not just System.err

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4690]
**Jetty version**
10.0.0

**Description**
The current `DistributionTester` checks on progress of the actions against the Distribution by looking at the output on System.err

But if we want to test logging behaviors, such as `console-capture` or `log4j1` with a log file, then we cannot use the `DistributionTester` as it is today.
Being able to give the `DistributionTester` a log file to interrogate would be a great alternate choice for testing logging.

**Comment by olamy** [comment]
PR https://github.com/eclipse/jetty.project/pull/4703
