### ISSUE TITLE
Use MethodHandles.lookup() consistently in WebSocket code

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4691]
**Jetty version**
10.0.x

**Description**
Usage of `MethodHandles.lookup()` and all its variants needs to be done consistently in WebSocket classes.

Particular care must be taken when method handles are looked up in application classes - usage of `MethodHandles.publicLookup().in(...)` is probably best in that case as we want to separate the various lookups for every webapp with a different class loader.

For implementation usages of method handles, it must be explicitly stated so.

I would like to see 2 utility methods (even duplicated between the javax and the jetty implementation) that clearly state what is the lookup used for, and why one API is used over another (e.g. `MethodHandles.lookup()` vs `MethodHandles.publicLookup().in(...)`).

**Comment by lachlan-roberts** [comment]
fixed in PR #4694
