### ISSUE TITLE
Version 9.4.25 breaks binary compatibility by renaming Response.closeOutput()

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#4693]
**Jetty version**
9.4.25.v20191220

**Description**
Version 9.4.24.v20191120 contains `org.eclipse.jetty.server.Response.closeOutput`. Version 9.4.25.v20191220 removes it. The method was never deprecated and the changelog did not mention this change.

Consequently, downstream packages fail at runtime:

```
java.lang.NoSuchMethodError: 'void org.eclipse.jetty.server.Response.closeOutput()'
	at org.glassfish.jersey.jetty.JettyHttpContainer$ResponseWriter.commit(JettyHttpContainer.java:326)
[...]
```

Consider restoring this method or at the very least documenting a migration path.

**Comment by cowwoc** [comment]
I tracked this down to https://github.com/eclipse/jetty.project/commit/c5acf965067478784b54e2d241ec58fdb0b2c9fe#diff-03fcd9b9e322e2bb4fdb46f2bbea27b3 which renamed the method from `closeOutput()` to `completeOutput()`. Consider restoring the original method, deprecating it, and delegating to the new method name.

**Comment by gregw** [comment]
Sorry about that  - we don't really have a good boundary of what are internal methods and are thus changeable in a dot release.   Obviously we got it wrong on this one.
Reverted.

**Comment by joakime** [comment]
Out of curiosity, can you explain why are you using `Response.closeOutput()`?
I ask, as there might be a much more reasonable API choice for you to accomplish the same end goal (and more properly).

**Comment by cowwoc** [comment]
@gregw No worries.
@joakime I'm just a user of the jersey library. I'm not sure why the author chose to use that method. Sorry I couldn't be of more help. I suggest asking at https://github.com/eclipse-ee4j/jersey/

**Comment by joakime** [comment]
Here's the Jersey usage ...

https://github.com/eclipse-ee4j/jersey/blob/master/containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpContainer.java#L323-L335

That seems wrong to me.
@gregw perhaps we need to file an issue at Jersey about that.

**Comment by joakime** [comment]
Wow, Jersey is even using `org.eclipse.jetty.continuation.Continuation`!
