### ISSUE TITLE
RST_STREAM is set to HTTP2 requests when connection is not available between the client and server.

### ISSUE THREAD

**Issue by ManiMozhiGayathri** [eclipse/jetty.project#4696]
Jetty Version : 9.4.19
Java version : Java 8
Description : When the client IP is down for few minutes and once its up and running all the requests generated in the downtime has rst_stream been set in the requests. Why is this happening and how to not have rst_stream been added to the requests during the downtime.

**Comment by sbordet** [comment]
HTTP/2 is based on TCP, so if your TCP connection is down while you have outstanding requests, the server won't be able to send back responses, so the requests will fail. 
If the request is trying to be sent while the client has no network access, well then the request fails to be sent and it's failed.

Why are you surprised that if you don't have a network your requests fail?

**Comment by ManiMozhiGayathri** [comment]
HTTP2 client Application is sending requests every 30 seconds and if the server connection is down for 2 minutes all the requests are getting accumulated and then been sent with RST_STREAM instead I would want the requests to removed after conection timeout.

Though server can process multiple requests with RST_STREAM, I dont want to send the request with RST_STREAM and only would like to have the latest requests sent from client. Client Application has connection timeout as 2 seconds and idle timeout as 30 seconds.

**Comment by sbordet** [comment]
Sorry, you first said that it was the client IP down, but now it's the server that is down.
You are not specifying if you are using the Jetty client, or the Jetty server, or both.

Requests are not "sent with RST_STREAM", so I don't understand what you mean there.

Please provide a way for us to reproduce the problem with actual code.
Alternatively, provide both client and server DEBUG logs.

**Comment by ManiMozhiGayathri** [comment]
Client Server Details : Jetty HTTP2 Client and Tomcat/anyother Server.

Client side configurations - > Connection timeout 2 seconds, Idle timeout -> 30 seconds.

Step to reproduce :
1. Client is sending  http requests every 30 seconds.
2. Start collecting pcap.
3. Do ifconfig down for 2 minutes in Client side.
4. Do ifconfig up.

If we see in pcap 3 requests with RST_STREAM and one request with proper actual 4th request.
But why are we sending RST_Stream, if connection timeout/idle happens , remaining 3 shouldn't send ,only 4th request needs to be sent.

Can RST_STREAMS be processed by server ?
When new Connection will be created at jetty http2 client end after the connection timeout?

**Comment by sbordet** [comment]
Sorry it's still not clear what you are doing, what you are seeing and what you expect to see instead.
If you see a RST_STREAM frame, it means that your connection is not down like you think it is.

Please client DEBUG logs and pcap (only if it's decrypted or can be decrypted).

**Comment by ManiMozhiGayathri** [comment]
From the client side we are bringing the network interface down. Post which the requests generated from client side are having rst_stream in their requests.
Which we do not want to be present in the request from client.

Please find the pcap image for you reference.

![CapturedPcap](https://user-images.githubusercontent.com/62544342/77406834-402a4980-6ddb-11ea-92e3-ffaa0169d618.jpg)

Below are few queries : 
When network interface is down for few minutes and once interface up post which , why we are still sending old messages with RST_STREAM ?
When will RST_STREAM be sent in requests from the client ?
what happens when connection timeout or idle timeout occurs in client side ?
Would that create new connection on connection timeout or idle timeout ?

**Comment by sbordet** [comment]
Sorry, I cannot understand who's sending the RST_STREAM. To me it seems that your client interface is not down, the client is sending requests, but the server rejects them with a RST_STREAM.
Please look in the pcap for the source IP/port pair to understand who's sending what.

DEBUG logs?

**Comment by ManiMozhiGayathri** [comment]
I don't have the debug level logs. But could you provide answers for below queries.

When will RST_STREAM be sent in requests from the client ?
What happens when connection timeout or idle timeout occurs in client side ?
Would that create new connection on connection timeout or idle timeout ?

**Comment by sbordet** [comment]
> When will RST_STREAM be sent in requests from the client ?

In a few number of situations, due to a number of reasons.

> What happens when connection timeout or idle timeout occurs in client side ?

The in-flight requests are canceled via a RST_STREAM, and a GOAWAY is sent to the server.

>  Would that create new connection on connection timeout or idle timeout ?

I don't understand this one.

> I don't have the debug level logs.

They will show _exactly_ what's going on, saving us both a lot of time.

**Comment by sbordet** [comment]
Closing as no further information was provided.
