### ISSUE TITLE
_systemClasses is not consistent

### ISSUE THREAD

**Issue by dsyzhu** [eclipse/jetty.project#4715]
When we try to add custom system classes sometimes _systemClasses is set to our class pattern set, sometimes is set to default value provided by jetty because getServer() sometimes return null.

https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L806

**Comment by joakime** [comment]
Jetty 9.3.x is deprecated and no longer supported - https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

But anyway, the Server is the home for the default system classes declaration.

If you use WebAppContext, do yourself a favor and add things to embedded jetty in the following order ...

1. Create the `Server` object
2. Add a `HandlerList` (or any other `HandlerCollection` implementation, such as `ContextHandlerCollection`) to `Server.setHandler()`
3. Create your `WebAppContext`
4. Add your `WebAppContext` to the `HandlerList`
5. Configure your `WebAppContext`
6. Start your server. (aka `Server.start()`)

**Comment by dsyzhu** [comment]
@joakime ,

Thanks for your prompt reply.

We don't use embedded jetty. For non-embedded case what shall we do?

Thanks

**Comment by joakime** [comment]
If you are not using embedded jetty, then you'll need to be very detailed and clear about what you are actually doing.
As your question about system classes is typically an embedded jetty use case.

Please provide details on how you are using jetty and why you want to mess around with system classes.

**Comment by dsyzhu** [comment]
We use standard non-embedded method. war file are expanded to /webapps/ROOT folder where our app is. For certain apis we want to use our apis under /WEB-INF/lib, not from those provided by Jetty. For those apis we want to block try parent classloader. So need to manipulate _systemClasses https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L454


Let me know if you need more details.
Thanks

**Comment by joakime** [comment]
:warning: :bangbang: **Jetty 9.3.x is deprecated and no longer supported.** :bangbang: :warning: 

https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

First, upgrade to a supported version of Jetty.

----

You need to be detailed, how did you setup your `${jetty.base}`, how are your deploying your webapp (which Deployment management do you have setup), what configuration of the `${jetty.base}` do you have? what configuration of the webapp do you have? what classes are you attempting to manipulate? how are you attempting to manipulate the webapp to control them? what do your logs say? give details.  filenames, `--list-config` output, directory names, contents of xmls, contents of inis, etc.

**Comment by dsyzhu** [comment]
This part of code is not changed in 9.4. Do you mean actually getServer() should never return null? If it returns null there is something wrong with other part of our configuration?

Thanks

**Comment by janbartel** [comment]
Can you please post how you're trying to set the systemClasses?

**Comment by dsyzhu** [comment]
Thanks. 

Understand jetty 9.3 is deprecated. We have moved away from jetty 9.3. If we find same issue in jetty 9.4 will create a new ticket for jetty 9.4. Closing this ticket.
