### ISSUE TITLE
Use LongAdder rather than AtomicLong for statistics

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#472]
http://psy-lob-saw.blogspot.com.au/2014/06/jdk8-update-on-scalable-counters.html

**Comment by gregw** [comment]
Actually this is going to be more complex than first thought because use the semantics of AtomicLong in many places to calculate values like maximums.  For example our CounterStatistics class does the following for an increment:
````java
   void add(long delta)
   {
     long current = _current.addAndGet(delta);
     if (delta>0)
     {
       _total.addAndGet(delta);
        long max = _max.get();
        while (current > max)
        {
            if (_max.compareAndSet(max, current))
                break;
            max = _max.get();
        }
   }
````
With that semantic, only the _total field can be easily changed to a LongAdder.  The _current field does a get after the add, which negates the point of LongAdder write mostly algorithm.   Also max needs compare and set operation.

So we have to research if there are better ways of obtaining max value for these statistics.   However there may be some value in converting at least the totals to LongAdders.  Plus there are other stats in the StatsHandler that do not have maximums or other such semantics.

**Comment by gregw** [comment]
Have asked for wisdom from [stackoverflow](http://stackoverflow.com/questions/36346670/using-longadder-to-calculate-a-max-value-for-a-statistical-counter)

**Comment by sbordet** [comment]
I'm not sure about this. `LongAdder` allocates, something that Nitsan's benchmark does not measure.

**Comment by gregw** [comment]
@sbordet hence the very unlike me approach of creating a branch.  But isn't think allocation only an array of thread hashes?  Or does it allocated continually??? I'll have a look at the source code....

**Comment by sbordet** [comment]
I think it allocates only when contention is high, so perhaps not that bad, but we need to verify.

**Comment by gregw** [comment]
So the allocation is describes as follows:
````
     * Table entries are of class Cell; a variant of AtomicLong padded
     * (via @sun.misc.Contended) to reduce cache contention.
...
     * In part because Cells are relatively large, we avoid creating
     * them until they are needed.  When there is no contention, all
     * updates are made to the base field.  Upon first contention (a
     * failed CAS on base update), the table is initialized to size 2.
     * The table size is doubled upon further contention until
     * reaching the nearest power of two greater than or equal to the
     * number of CPUS. Table slots remain empty (null) until they are
     * needed.
````

So for long lived LongAdders like these, they will grow initially with contention until they are either large enough or hit the size limit.  After that, there should be no ongoing allocations.

Stats are optional, so can be left out on memory constrained machines.

**Comment by gregw** [comment]
Merged
