### ISSUE TITLE
Get env variables in PHP scripts served through FastCGIProxyServlet

### ISSUE THREAD

**Issue by afarber** [eclipse/jetty.project#4735]
**Jetty version**
9.4.27.v20200227
**Java version**
1.8.0_91
**OS type/version**
CentOS Linux 7.7.1908
**Description**

Please add a possibility to set environment variables in PHP scripts [served through FastCGI](https://www.eclipse.org/jetty/documentation/9.4.27.v20200227/configuring-fastcgi.html).

As suggested by Simone Bordet in [a mail at jetty-users](https://www.eclipse.org/lists/jetty-users/msg09435.html):

> It is common, however, to pass FastCGI variables along with the
request, and these can be retrieved in PHP via e.g.
$_SERVER['COUNTRY'] or getenv('COUNTRY') but *not* $_ENV['COUNTRY'].

> What we can do is to allow to configure init-param names in
FastCGIProxyServlet, and then we can read those names and forward them
to PHP.

> Something like:

```
<Call name="setInitParameter">
  <Arg>envNames</Arg>
  <Arg>COUNTRY, DOMAIN, ...</Arg>
</Call>
```

> and we call System.getenv("COUNTRY"), etc.

**Comment by sbordet** [comment]
@afarber can you please try branch `jetty-9.4.x-4735-env_variables_fcgi`?

**Comment by afarber** [comment]
In order to test the change I have checked out the branch:

```
git checkout remotes/origin/jetty-9.4.x-4735-env_variables_fcgi
```

but there is no start.jar file there. How would I build it please?

On my CentOS 7 server I usually run Jetty this way (through the file  /etc/systemd/system/jetty-en.service):

```
ExecStart=/usr/bin/java -Djdbc.drivers=org.postgresql.Driver -jar /usr/share/java/jetty-distribution-9.4.27.v20200227/start.jar jetty.home=/usr/share/java/jetty-distribution-9.4.27.v20200227 jetty.base=/var/www/jetty-base-en jetty.http.host=127.0.0.1 jetty.http.port=8082
```

**Comment by sbordet** [comment]
You need Maven to build Jetty.

```
$ git checkout jetty-9.4.x-4735-env_variables_fcgi
$ mvn clean install -DskipTests
```

Now you have a Jetty 9.4.28-SNAPSHOT distribution in `jetty-distribution/target`.

Uncompress it in `/usr/share/java/jetty-distribution-9.4.28-SNAPSHOT` and use the same command line above, but pointing to the new distribution.

**Comment by afarber** [comment]
Thank you. Unfortunately, I get this build failure:

[build-jetty.txt](https://github.com/eclipse/jetty.project/files/4427704/build-jetty.txt)

Also unsuccessfully tried `mvn clean install -DskipTests -Dmaven.test.skip=true`

I have searched and it seems to be caused by the CentOS 7 Linux coming with the older Maven version: **Apache Maven 3.0.5 (Red Hat 3.0.5-17)**

However I have also found a possible workaround for it here:

https://issues.apache.org/jira/browse/SUREFIRE-1628

Can you Simone or Joakim "fix it by instantiating LocationManager instead of injecting it in the class AbstractSurefireMojo" in the same branch? Then I will pull your change and try it on my server.

**Comment by sbordet** [comment]
Just update Maven.
Download the latest version from http://maven.apache.org/.
Then use explicitly that version to build Jetty.

**Comment by afarber** [comment]
Ok, updating Maven has helped, but the $_SERVER['COUNTRY'] is missing:

![image](https://user-images.githubusercontent.com/1884458/78373724-42568a00-75cb-11ea-8b86-95ea19729ab2.png)

eventhough I have in my /etc/systemd/system/jetty-en.service:

```
[Service]
Environment=STRINGS=en
Environment=COUNTRY=en
Environment=DOMAIN=wordsbyfarber.com
ExecStart=/usr/bin/java -Djdbc.drivers=org.postgresql.Driver -jar /usr/share/java/jetty-distribution-9.4.28-SNAPSHOT/start.jar jetty.home=/usr/share/java/jetty-distribution-9.4.28-SNAPSHOT jetty.base=/var/www/jetty-base-en jetty.http.host=127.0.0.1 jetty.http.port=8082
```

And my PHP script just perform print_r($_SERVER);

**Comment by sbordet** [comment]
Did you configure `FastCGIProxyServlet`?

```xml
<Call name="setInitParameter">
    <Arg>fastCGI.envNames</Arg>
    <Arg>COUNTRY</Arg>
</Call>
```

**Comment by afarber** [comment]
Well, Simone... then it works :-)

![image](https://user-images.githubusercontent.com/1884458/78375482-23f18e00-75cd-11ea-9ba8-51c4964ee2e6.png)

**Comment by sbordet** [comment]
@afarber thanks for confirming.
You can pass in a comma-separated list of environment variable names that will be forwarded to the FastCGI process.
