### ISSUE TITLE
Update Import-Package version start ranges

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4736]
For this and the other range issues you've raised we need to address this in another PR, not this one. If you're happy with the changes to enable jetty-slf4j-impl to work in osgi, please give this issue the thumbs up and open new issue to bump up osgi servlet/jsp api versions.

_Originally posted by @janbartel in https://github.com/eclipse/jetty.project/pull/4684_

**Comment by janbartel** [comment]
Raised PR #4963 

I've removed the explicit numbering for the frequently updated imports and used variable expansion instead: it should make jetty-10 and 11 easier to handle too.
