### ISSUE TITLE
"404: Not Found" for files used when configure logging module to jetty 

### ISSUE THREAD

**Issue by ZeloBox** [eclipse/jetty.project#4745]
Jetty when trying to add configure new added modules(logging and webapp-logging) does not find the files referenced in these modules.

**Jetty version**
0:      1.4.1.v201005082020 | ${jetty.home}/lib/mail/javax.mail.glassfish-1.4.1.v201005082020.jar
 1:                   5.11.4 | ${jetty.home}/lib/ext/activemq-client-5.11.4.jar
 2:                    1.0.1 | ${jetty.home}/lib/ext/geronimo-j2ee-management_1.1_spec-1.0.1.jar
 3:                  1.4.192 | ${jetty.home}/lib/ext/h2-1.4.192.jar
 4:                     1.11 | ${jetty.home}/lib/ext/hawtbuf-1.11.jar
 5:                   2.4.13 | ${jetty.home}/lib/ext/HikariCP-java7-2.4.13.jar
 6:                1.1-rev-1 | ${jetty.home}/lib/ext/jms-api-1.1-rev-1.jar
 7:                    1.1.7 | ${jetty.home}/lib/ext/lib/logback/logback-classic-1.1.7.jar
 8:                    1.1.7 | ${jetty.home}/lib/ext/lib/logback/logback-core-1.1.7.jar
 9:                   1.7.21 | ${jetty.home}/lib/ext/lib/slf4j/slf4j-api-1.7.21.jar
10:                    1.2.3 | ${jetty.home}/lib/ext/logback-classic-1.2.3.jar
11:                    1.2.3 | ${jetty.home}/lib/ext/logback-core-1.2.3.jar
12:                   1.7.25 | ${jetty.home}/lib/ext/slf4j-api-1.7.25.jar
13:                    (dir) | ${jetty.base}/resources
14:                    3.1.0 | ${jetty.home}/lib/servlet-api-3.1.jar
15:                 3.1.0.M0 | ${jetty.home}/lib/jetty-schemas-3.1.jar
16:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-http-9.4.27.v20200227.jar
17:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-server-9.4.27.v20200227.jar
18:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-xml-9.4.27.v20200227.jar
19:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-util-9.4.27.v20200227.jar
20:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-io-9.4.27.v20200227.jar
21:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-jndi-9.4.27.v20200227.jar
22:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-security-9.4.27.v20200227.jar
23:                      1.3 | ${jetty.home}/lib/transactions/javax.transaction-api-1.3.jar
24:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-servlet-9.4.27.v20200227.jar
25:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-webapp-9.4.27.v20200227.jar
26:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-plus-9.4.27.v20200227.jar
27:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-annotations-9.4.27.v20200227.jar
28:                      7.2 | ${jetty.home}/lib/annotations/asm-7.2.jar
29:                      7.2 | ${jetty.home}/lib/annotations/asm-analysis-7.2.jar
30:                      7.2 | ${jetty.home}/lib/annotations/asm-commons-7.2.jar
31:                      7.2 | ${jetty.home}/lib/annotations/asm-tree-7.2.jar
32:                      1.3 | ${jetty.home}/lib/annotations/javax.annotation-api-1.3.jar
33:    3.19.0.v20190903-0936 | ${jetty.home}/lib/apache-jsp/org.eclipse.jdt.ecj-3.19.0.jar
34:         9.4.27.v20200227 | ${jetty.home}/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.4.27.v20200227.jar
35:                   8.5.49 | ${jetty.home}/lib/apache-jsp/org.mortbay.jasper.apache-el-8.5.49.jar
36:                   8.5.49 | ${jetty.home}/lib/apache-jsp/org.mortbay.jasper.apache-jsp-8.5.49.jar
37:                    1.2.5 | ${jetty.home}/lib/apache-jstl/org.apache.taglibs.taglibs-standard-impl-1.2.5.jar
38:                    1.2.5 | ${jetty.home}/lib/apache-jstl/org.apache.taglibs.taglibs-standard-spec-1.2.5.jar
39:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-client-9.4.27.v20200227.jar
40:         9.4.27.v20200227 | ${jetty.home}/lib/jetty-deploy-9.4.27.v20200227.jar
41:                      1.0 | ${jetty.home}/lib/websocket/javax.websocket-api-1.0.jar
42:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/javax-websocket-client-impl-9.4.27.v20200227.jar
43:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/javax-websocket-server-impl-9.4.27.v20200227.jar
44:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/websocket-api-9.4.27.v20200227.jar
45:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/websocket-client-9.4.27.v20200227.jar
46:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/websocket-common-9.4.27.v20200227.jar
47:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/websocket-server-9.4.27.v20200227.jar
48:         9.4.27.v20200227 | ${jetty.home}/lib/websocket/websocket-servlet-9.4.27.v20200227.jar

**Java version**
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**OS type/version**
Linux 361d878dbc09 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
docker Image 
jetty:9.4-jre8

>**_cat /etc/os-release_**

> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> NAME="Debian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

**Description**
After install net modules into modules directory by sucessfully finished command:
_mkdir -p /var/lib/jetty/modules
cd modules
curl -O https://raw.githubusercontent.com/jetty-project/logging-modules/master/centralized/webapp-logging.mod
curl -O https://raw.githubusercontent.com/jetty-project/logging-modules/master/capture-all/logging.mod_

jetty@361d878dbc09:/var/lib/jetty$ _ls -la  modules_

> total 16
> drwxr-xr-x 2 jetty jetty 4096 Apr  2 12:17 .
> drwxr-xr-x 1 jetty jetty 4096 Apr  2 11:13 ..
> -rw-r--r-- 1 jetty jetty 1420 Apr  2 11:13 logging.mod
> -rw-r--r-- 1 jetty jetty  661 Apr  2 11:13 webapp-logging.mod

When I try to add module described in the documentation I got the following errors:
_jetty@361d878dbc09:/var/lib/jetty$  java  -jar ${JETTY_HOME}/start.jar --add-to-start=logging,webapp-logging_
I got the following errors:

> WARN  : Deprecated [name] used in ${jetty.base}/modules/webapp-logging.mod
> INFO  : logging already enabled by [${jetty.base}/start.d/logging.ini]
> INFO  : webapp-logging already enabled by [${jetty.base}/start.d/webapp-logging.ini]
> DOWNLD: http://central.maven.org/maven2/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.jar to ${jetty.base}/lib/logging/slf4j-api-1.6.6.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> DOWNLD: http://central.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.6.6/log4j-over-slf4j-1.6.6.jar to ${jetty.base}/lib/logging/log4j-over-slf4j-1.6.6.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> DOWNLD: http://central.maven.org/maven2/org/slf4j/jul-to-slf4j/1.6.6/jul-to-slf4j-1.6.6.jar to ${jetty.base}/lib/logging/jul-to-slf4j-1.6.6.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> DOWNLD: http://central.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.6.6/jcl-over-slf4j-1.6.6.jar to ${jetty.base}/lib/logging/jcl-over-slf4j-1.6.6.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> DOWNLD: http://central.maven.org/maven2/ch/qos/logback/logback-core/1.0.7/logback-core-1.0.7.jar to ${jetty.base}/lib/logging/logback-core-1.0.7.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> DOWNLD: http://central.maven.org/maven2/ch/qos/logback/logback-classic/1.0.7/logback-classic-1.0.7.jar to ${jetty.base}/lib/logging/logback-classic-1.0.7.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> DOWNLD: http://central.maven.org/maven2/org/eclipse/jetty/jetty-webapp-logging/9.0.0/jetty-webapp-logging-9.0.0.jar to ${jetty.base}/lib/webapp-logging/jetty-webapp-logging-9.0.0.jar
> java.net.UnknownHostException: central.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:607)
>         at java.net.Socket.connect(Socket.java:556)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
>         at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:139)
>         at org.eclipse.jetty.start.fileinits.UriFileInitializer.create(UriFileInitializer.java:47)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> WARN  : Failed to process all file resources.
>  - [UnknownHostException] central.maven.org - lib/logging/slf4j-api-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/log4j-over-slf4j-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/jul-to-slf4j-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/jcl-over-slf4j-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/logback-core-1.0.7.jar
>  - [UnknownHostException] central.maven.org - lib/logging/logback-classic-1.0.7.jar
>  - [UnknownHostException] central.maven.org - lib/webapp-logging/jetty-webapp-logging-9.0.0.jar
> java.lang.RuntimeException: Failed to process all file resources.
>  - [UnknownHostException] central.maven.org - lib/logging/slf4j-api-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/log4j-over-slf4j-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/jul-to-slf4j-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/jcl-over-slf4j-1.6.6.jar
>  - [UnknownHostException] central.maven.org - lib/logging/logback-core-1.0.7.jar
>  - [UnknownHostException] central.maven.org - lib/logging/logback-classic-1.0.7.jar
>  - [UnknownHostException] central.maven.org - lib/webapp-logging/jetty-webapp-logging-9.0.0.jar
>         at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:342)
>         at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
>         at org.eclipse.jetty.start.Main.start(Main.java:440)
>         at org.eclipse.jetty.start.Main.main(Main.java:77)
> 
> Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
>        java -jar $JETTY_HOME/start.jar --help  # for more information
> 

**Documentation:** https://www.eclipse.org/jetty/documentation/current/example-logging-logback-centralized.html

**Comment by joakime** [comment]
Can you please use `java -Dmaven.repo.uri=https://repo1.maven.org/maven2/ -jar $JETTY_HOME/start.jar ...` and see if it makes a difference for you?

**Comment by joakime** [comment]
Ah, switch from jetty-webapp-logging 9.0.0 to `9.4.20.v20190813`.

The old 9.0.0 version had a hardcoded `http://central.maven.org/` in it, the new version uses the `maven://` scheme to be more intelligent.

**Comment by ZeloBox** [comment]
> Ah, switch from jetty-webapp-logging 9.0.0 to `9.4.20.v20190813`.
> 
> The old 9.0.0 version had a hardcoded `http://central.maven.org/` in it, the new version uses the `maven://` scheme to be more intelligent.

I'am confused. How I can  switch  jetty-webapp-logging to 9.0.0 to 9.4.20.v20190813?

**Comment by joakime** [comment]
Making this a documentation issue.
PR forthcoming ...

**Comment by ZeloBox** [comment]
Thank you, Joakim!
In addition to the fact that the above errors occurred, if you put the missing libraries, you still do not get the xml files specified in the modules:
in logging.mod:
_https://raw.githubusercontent.com/jetty-project/logging-modules/master/capture-all/logback.xml|resources/logback.xml
https://raw.githubusercontent.com/jetty-project/logging-modules/master/capture-all/jetty-logging.properties|resources/jetty-logging.properties
https://raw.githubusercontent.com/jetty-project/logging-modules/master/capture-all/jetty-logging.xml|etc/jetty-logging.xml_

in webapp-logging.mod:
_https://raw.githubusercontent.com/jetty-project/jetty-webapp-logging/master/src/main/config/etc/jetty-webapp-logging.xml|etc/jetty-webapp-logging.xml
https://raw.githubusercontent.com/jetty-project/jetty-webapp-logging/master/src/main/config/etc/jetty-mdc-handler.xml|etc/jetty-mdc-handler.xml_

for all these files I also got 404: Not Found

Fix also this URL-s to valid, please.

**Comment by joakime** [comment]
Updated documentation in PR #4748

**Comment by joakime** [comment]
Merged PR #4748
