### ISSUE TITLE
HTTP2 Jetty Server does not send back content-length

### ISSUE THREAD

**Issue by CaoManhDat** [eclipse/jetty.project#4764]
**Jetty version** 9.4.24.v20191120

**Java version** Java 11

**Question** On requesting to a plain text HTTP2 (h2c) Jetty Server, the response doesn't include content-length in the header. But with that same server on requesting using HTTP/1.1, the server does return content-legth.
I understand that content-length is not required for HTTP2 protocol. But it will be very helpful for client for handling the response if content-length is available. So do Jetty have any configuration to enforce server to return content-length in the header?

**Comment by sbordet** [comment]
You are correct that currently we don't add the `Content-Length` header if we know in advance the total content length.

Can you expand on how this header will be useful to a HTTP/2 client?

**Comment by CaoManhDat** [comment]
Few examples 
* use it for `BufferingResponseListener`, so it can know exactly how much memory it needs to allocate.
* in my case we need to choose wether to use `BufferingResponseListener` (which doesn't need to spin a new thread to wait for data from other's side) or `InputStreamResponseListener`
* same idea from http2 spec community: https://github.com/http2/http2-spec/issues/558

**Comment by CaoManhDat** [comment]
Thanks!
