### ISSUE TITLE
Review GzipHandler inside ServletContextHandler

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4765]
**Jetty version**
10.0.x

**Description**
`ServletContextHandler` has direct support for `GzipHandler`, apparently for the only reason to organize the internal `Handler`s in this way: `session -> security -> gzip -> servlet`.

However, there is no apparent reason to have `GzipHandler` part of `ServletContextHandler`.

A configuration like this: `GzipHandler -> ServletContextHandler` seems to work perfectly fine, and it's more in line with how you would use `GzipHandler` with others `ContextHandler`s.

@gregw @joakime what am I missing?

Can `GzipHandler` be removed from `ServletContextHandler`?

**Comment by gregw** [comment]
I believe this is a hangover from before we had the interceptor mechanism.
