### ISSUE TITLE
Jetty client hangs if sending same request twice

### ISSUE THREAD

**Issue by sobimibos** [eclipse/jetty.project#4784]
Jetty version 9.4.28

Java version 1.8_241

Various

After upgrading from jetty 9.4.20 to 9.4.28 we noticed, that the jetty client hangs, if you send the same Request more than once. This behaviour was not seen with the 9.4.20 version.
We noticed this in a unit test which sends a GET request to a test server, which is expected to respond only once with 200:

```
        Request request = httpClient.newRequest(url).method(HttpMethod.GET)

        ContentResponse response = request.send();

        assertThat("The response status was not as expected", response.getStatus(), is(HttpStatus.OK_200));

        response = request.send(); // here it hangs now

        assertThat("The response status was not as expected", response.getStatus(), is(HttpStatus.NOT_FOUND_404));

```
The httpClient is created simply with:

```
        httpClient = new HttpClient();
        httpClient.start();

```

Recreating a new request with the same url before the second send fixes this issue. But it is intended, that requests now can only be sent once?

**Comment by joakime** [comment]
The `Request` object is not reusable.

It cannot be reused for another request, you should create a new Request object for each new request you want to send.

**Comment by joakime** [comment]
Answered about Request object is not reusable.
