### ISSUE TITLE
Make org.eclipse.jetty.client.HttpRequest's host name writable

### ISSUE THREAD

**Issue by garydgregory** [eclipse/jetty.project#4787]
**Jetty version**

9.4.28.v20200408

**Java version**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**OS type/version**

Microsoft Windows [Version 10.0.16299.1747]

**Description**

At work, I have a subclass of `org.eclipse.jetty.proxy.AsyncMiddleManServlet` which can be configured as a reverse proxy to "edit" requests as they are processed. In some cases, we must redirect a given request on the fly to a different host, to do so, we currently use Java reflection to edit the `host` field of a `org.eclipse.jetty.client.HttpRequest` instance.

In order to avoid using reflection, the PR https://github.com/eclipse/jetty.project/pull/4786 adds a mutator method to `org.eclipse.jetty.client.HttpRequest` and makes it available in the interface `org.eclipse.jetty.client.api.Request`.

**Comment by joakime** [comment]
Usually this is accomplished by overriding the `rewriteTarget` method on `AsyncMiddleManServlet`.

https://github.com/eclipse/jetty.project/blob/ab228fde9e55e9164c738d7fa121f8ac5acd51c9/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L416

Can you explain why this isn't an option for you?

**Comment by sbordet** [comment]
Also, override `AsyncMiddleManServlet.copyRequestHeaders(...)`: call `super` and then `Request.header(HOST, yourHost)`.

**Comment by garydgregory** [comment]
We want to perform transformations on ALL aspects (headers, URI, and body) of a request from one Jetty location.
Our servlet overrides `org.eclipse.jetty.proxy.AsyncMiddleManServlet.newClientRequestContentTransformer(HttpServletRequest, Request)` to perform processing as written in an external configuration file where we define and apply transformations like "If a request to foo1.com arrives with a query parameter foo1 equals to bar1 and a body like text1 and a header h1 equals to bar1, then forward that request to foo2.com with a query parameter foo2 equals to bar2 and a body like text2 with header h1 equals to bar2, and if there is a header called remove-me, then remove that header before passing the request to the origin server." and so on. The method `newClientRequestContentTransformer()` is designed to perform transformations on the body, so that's the perfect hook for our servlet. Therefore, our policy engine, already quite complex, is designed to hook into `newClientRequestContentTransformer()`; it would not work for us to rewrite our whole software to split processing policies from a single Jetty hook (`newClientRequestContentTransformer()`) to three different Jetty hooks (`rewriteTarget()`, `copyRequestHeaders`, `newClientRequestContentTransformer()`). The proposed solution IMO is the simplest and least disrupting.

**Comment by sbordet** [comment]
> The proposed solution IMO is the simplest and least disrupting.

Nope.

Why can't you modify the `proxyRequest` that is passed in to `newClientRequestContentTransformer()`?

**Comment by sbordet** [comment]
Ah, it's the URI host you want to modify, not the `Host` header.

**Comment by garydgregory** [comment]
> Ah, it's the URI host you want to modify, not the `Host` header.

Right, I want to overwrite the host name to the origin server which is stored in the `HttpRequest`.

**Comment by sbordet** [comment]
@garydgregory can you try out PR #4791?

**Comment by garydgregory** [comment]
@sbordet 
It works like a charm :-)
I checked out your branch and built it skipping the tests, updated my POM and my integration test, and it worked :-)
Might this make it in 9.4.29?
Thank you,
Gary
