### ISSUE TITLE
Possible Memory Leak since 9.4.28

### ISSUE THREAD

**Issue by gbrehmer** [eclipse/jetty.project#4792]
**Jetty version**
9.4.28

**Java version**
1.8.0_242 openjdk

**OS type/version**
Ubuntu 16.04.6

**Description**
Probably with update to 9.4.28 we got a new memory leakage problem:

![image](https://user-images.githubusercontent.com/1201680/79701925-347a5780-82a1-11ea-9a12-758fec84ab9b.png)

the JarFileResource contains links to static resources from WAR file. Or is this a normal behavior?

**Comment by sbordet** [comment]
If the reference links only go through `Finalizer` then the object is finalizable and will be cleared up eventually by the GC.

Can you verify this?

Also, can you do a full GC 3-4 times (it takes multiple passes for a GC to reclaim finalizable objects, and also depends on the GC algorithm) and see if the `Finalizer` are gone?

**Comment by gbrehmer** [comment]
you're right, my fault, gc runs were the last days more rarely and it filled up always almost to max in contrast to the behavior before last deployment
