### ISSUE TITLE
Introduce a HttpConfiguration.getBaseResponseHttpFields() concept

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4795]
Will this eventually mean we'll have a `HttpConfiguration.getBaseResponseHttpFields()` that provides the baseline response fields for the connectors that the configuration belongs to?

(With things like `Server: Jetty 10.0.x` already present in it?)

_Originally posted by @joakime in https://github.com/eclipse/jetty.project/pull/4777#issuecomment-616733787_

**Comment by gregw** [comment]
Good idea... but no time for 10.0.0
