### ISSUE TITLE
Repackaged javax.annotation and javax.websocket OSGi manifest problems

### ISSUE THREAD

**Issue by sdybiec** [eclipse/jetty.project#4797]
9.3.28
Java 8
Windows

1. When attempting to use the javax.annotation jar included with the 9.3.28 distribution in an OSGi context, Eclipse/Equinox cannot resolve it as a dependency. The OSGi manifest exports the javax.annotation packages as expected, but strangely it also imports those same packages. This breaks the Eclipse/Equinox bundle dependency mechanism, preventing the application from resolving bundles that require annotations.  If the 'Import-Package" clause is removed, it works as expected. Same problem occurs with Java 11.

I removed this line from the MANIFEST: 

```Import-Package: javax.annotation;version="1.2",javax.annotation.security;version="1.2",javax.annotation.sql;version="1.2"```

and everything worked.

2. The repackaged javas.websocket MANIFEST has a different problem. It's missing the following line:

```Require-Capability: osgi.serviceloader;filter:="(osgi.serviceloader=javax.websocket.server.ServerEndpointConfig$Configurator)";cardinality:=multiple,osgi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)"```

I added this and websockets now work.

With these changes and some creativity with OSGi start levels, I now have a fully functional Jetty working with annotations, websocket, JSP and JSTL in OSGi.

**Comment by janbartel** [comment]
It's not always possible to use the 3rd party jars from the distro with OSGi. If you take a look at the repo in jetty-osgi/test-jetty-osgi, you can see the versions of these jars that we use with the OSGi tests. In some cases we have had to use the Pax wrapbundle facility to patch these 3rd party jars on-the-fly to get the tests to work.  

As these are 3rd party jars, it's not possible for jetty to fix them.

**Comment by sdybiec** [comment]
Jetty claims to work with OSGi, and the documentation specifically says that annotations should be enabled: 

> "We strongly recommend that you also deploy the annotation-related jars also, as the Servlet 
> Specification increasingly relies on annotations for functionality."

The documentation also indicates that websockets will work with OSGi, but SPI Fly won't ever allow the ServiceLoader to find the implementation of 'javax.websocket.server.ServerEndpointConfig$Configurator' in Jetty's websocket jar unless the 'Require-Capability' is added to the javax.websocket jar: 

> "You must also install the Apache Aries SPI Fly bundles as many parts of Jetty - for example ALPN, 
> websocket, annotations - use the ServiceLoader mechanism, which requires an OSGi Service 
> Loader Mediator like SPI Fly"

https://www.eclipse.org/jetty/documentation/current/framework-jetty-osgi.html

I know several projects that repackage javax.* packages for their runtimes.  Either these jars should be fixed or the documentation updated to say that annotations and websockets won't work in OSGi with Jetty's out-of-the-box distribution.

**Comment by joakime** [comment]
I opened an issue at https://github.com/eclipse/jetty.toolchain/issues/31 for the javax.websocket missing ServiceLoader entry on OSGi. (PR https://github.com/eclipse/jetty.toolchain/pull/32)

Upgrading our javax.annotation from 1.3 to 1.3.5 will bring in the following META-INF/MANIFEST.MF

https://search.maven.org/artifact/jakarta.annotation/jakarta.annotation-api/1.3.5/jar

```
Manifest-Version: 1.0
Bundle-Description: Jakarta Annotations API
Automatic-Module-Name: java.annotation
Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.
 org/software/classpath/license.html
Bundle-SymbolicName: jakarta.annotation-api
Implementation-Version: 1.3.5
Built-By: default
Bnd-LastModified: 1564744140223
Bundle-ManifestVersion: 2
Specification-Vendor: Eclipse Foundation
Implementation-Vendor-Id: org.glassfish
Bundle-DocURL: https://www.eclipse.org
Bundle-Vendor: Eclipse Foundation
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.2.0.201903051501
Implementation-Vendor: Eclipse Foundation
Export-Package: javax.annotation.security;version="1.3.5",javax.annota
 tion.sql;version="1.3.5",javax.annotation;version="1.3.5"
Bundle-Name: Jakarta Annotations API
Bundle-Version: 1.3.5
Extension-Name: jakarta.annotation
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_202
Specification-Version: 1.3
```

**Comment by sdybiec** [comment]
Thanks. Another option for websocket is creating a fragment bundle with the Require-Capability hosted by the javax.websocket jar.

**Comment by janbartel** [comment]
@sdybiec great that you have an osgi deployment working.

To expand on my previous reply, which was a bit limited by my ability to swipe out a reply on a mobile.

As far as the javax.annotation-api 1.2 jar goes, that is exactly the jar that we deploy into eclipse during our osgi testing. The manifest that it contains works fine and is in accordance with standard osgi practice. It was/is considered 'good practice' in the osgi world to import what you export, and some automatic manifest generators will, by default, generate such headers. See for example https://felix.apache.org/documentation/tutorials-examples-and-presentations/apache-felix-osgi-faq.html#should-a-bundle-import-its-own-exported-packages.  Note that javax.annotation-api is a jar that was produced under the auspices of the JavaEE spec group, and will in the future be produced by the Jakarta spec group, so future versions as Joakim pointed out may well differ in the manifest contents.

For jetty-9.3 we didn't have an osgi test of javax websocket, but in jetty-9.4 we do. That test does the following to add some osgi manifest headers that were at some point missing from the javax websocket api jar:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJavaxWebSocket.java#L118
The test seems to be working, so I don't understand why in your environment it would be necessary to add a different header instead for the ServiceLoader class - we will investigate that. It would be helpful if you could poinpoint what you are doing in your deployment that is different from our osgi javax websocket test.

Finally, I urge you to upgrade to jetty-9.4 if possible, as there are more osgi tests to assure you that jetty in fact does work in osgi, including both jetty websocket and javax websocket. I think the documentation is correct insofar as it is based on our osgi test deployments, and identifies which jars you will need to substitute in the osgi environment (javax.annotation-api isn't one of them), but it's always worth revisiting the documentation so we will take another look at that (although only for the 9.4 release).

**Comment by janbartel** [comment]
Websocket manifest was updated via https://github.com/eclipse/jetty.toolchain/pull/32
