### ISSUE TITLE
WebSocket DistributionTests failure on JDK14

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#4800]
**Jetty version**
10.0.x

**Java version**
OpenJDK 14.0.1

**Description**
Test failure for `DistributionTests.testSimpleWebAppWithWebsocket()`:
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-10.0.x/995/tests
> 2020-04-21 15:21:16.205:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: java.lang.LinkageError: loader constraint violation: when resolving method 'void org.eclipse.jetty.tests.webapp.websocket.bad.BadOnOpenServerEndpoint.onOpen(javax.websocket.Session, org.eclipse.jetty.tests.webapp.websocket.bad.StringSequence)' the class loader 'bootstrap' of the current class, java/lang/Object, and the class loader org.eclipse.jetty.webapp.WebAppClassLoader @235a0c16 for the method's defining class, org/eclipse/jetty/tests/webapp/websocket/bad/BadOnOpenServerEndpoint, have different Class objects for the type org/eclipse/jetty/tests/webapp/websocket/bad/StringSequence used in the signature (java.lang.Object is in module java.base of loader 'bootstrap'; org.eclipse.jetty.tests.webapp.websocket.bad.BadOnOpenServerEndpoint is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @235a0c16, parent loader org.eclipse.jetty.start.Classpath$Loader @e6ea0c6)

**Comment by sbordet** [comment]
See also: https://bugs.openjdk.java.net/browse/JDK-8244090 and discussion: https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-April/066089.html

**Comment by lachlan-roberts** [comment]
The failing test has been disabled on JDK 14, now waiting on https://bugs.openjdk.java.net/browse/JDK-8244090 to get a workaround or fix for this issue.

**Comment by joakime** [comment]
@lachlan-roberts looks like bug https://bugs.openjdk.java.net/browse/JDK-8244090 was fixed in JDK16, do we still need this issue open?

**Comment by lachlan-roberts** [comment]
Yep fixed in JDK16 so closing this issue.
