### ISSUE TITLE
Request.getScheme() always return `http`

### ISSUE THREAD

**Issue by IndiscriminateCoding** [eclipse/jetty.project#4805]
**Jetty version**
9.4.28.v20200408

**Java version**
OpenJDK11

**OS type/version**
Ubuntu Linux 16.04

**Description**
`Request.getScheme()` and `Request.getRequestURL()` always return **http**, even when using SSL connector.

**Comment by sbordet** [comment]
@IndiscriminateCoding show your configuration. Do you configure `SecureRequestCustomizer`?

**Comment by IndiscriminateCoding** [comment]
@sbordet no, I wasn't using `SecureRequestCustomizer`. I tried with it enabled and now it correctly shows **https**. Is it always required when using https?

**Comment by joakime** [comment]
@IndiscriminateCoding there are 2 Customizers for setting up many Request features based on "is it secure" or not.

1. For direct connections from clients, the `SecureRequestCustomizer` handles setting up these "is it secure" features.
2. For front end terminated SSL/TLS (like a load balancer), the `ForwardedRequestCustomizer` does the job that `SecureRequestCustomizer` does.

Some "is it secure" features of the Request ...

Both do:
* `isSecure()` - boolean telling you if it was secure or not
* `getScheme()` - String telling you the scheme

SecureRequestCustomizer also does:
* `getAttribute("javax.servlet.request.X509Certificate")` - array of `java.security.cert.X509Certificate`
* `getAttribute("javax.servlet.request.cipher_suite")` - String representing the cipher suite used
* `getAttribute("javax.servlet.request.key_size")` - Integer representing the key size
* `getAttribute("javax.servlet.request.ssl_session_id")` - String representing the SSL Session ID
* `getAttribute("org.eclipse.jetty.servlet.request.ssl_session")` - the `javax.net.ssl.SSLSession` in use

ForwardRequestCustomizer also does:
* `getHttpURI()` - updated authority section based on forwarding headers
* `getMetaData().getURI()` - updates authority section based on forwarding headers
* `getRequestURL()` - updates authority section based on forwarding headers
* `getRemoteAddr()` - updated based on forwarding headers
* `getRemoteHost()` - updated based on forwarding headers
* `getRemotePort()` - updated based on forwarding headers


When using the `jetty-home` tarball (or the older `jetty-distribution` tarball), the `SecureRequestCustomizer` is added if you have ssl enabled.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.28.v20200408/jetty-server/src/main/config/etc/jetty-ssl.xml

**Comment by IndiscriminateCoding** [comment]
@joakime got it, thanks for detailed answer! I'm closing the issue
