### ISSUE TITLE
Does LdapLoginModule support StartTLS?

### ISSUE THREAD

**Issue by chuck-confluent** [eclipse/jetty.project#4807]
**Jetty version**
N/A

**Java version**
11.0.7

**Question**
Does `org.eclipse.jetty.jaas.spi.LdapLoginModule` support StartTLS? I am using Apache Directory Service, and [the docs](https://directory.apache.org/apacheds/basic-ug/3.3-enabling-ssl.html#transport-layer-security-and-ldap) say that LDAPS is considered deprecated and to use the StartTLS option instead. I am using software that connects to the LDAP server via the Jetty `LdapLoginModule` and I'd like to know beforehand whether using StartTLS will be a problem. Thank you!

**Comment by joakime** [comment]
The `LdapLoginModule` uses `javax.naming.directory.InitialDirContext` to establish the context to the LDAP server.

The `contextFactory` and/or environment you give it should determine how it connects to that LDAP server. (including the StartTLS features you are looking for).

For Apache Directory Service, look into `tc.startTLS.LdapTlsContextFactory`
