### ISSUE TITLE
Documentation for JettyJspServlet init-params table is mangled

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4817]
**Jetty version**
Jetty 9.4.x

**Description**

See table Table 8.1. Understanding Apache JspServlet Parameters
https://www.eclipse.org/jetty/documentation/current/configuring-jsp.html#compiling-jsps

About 1/3 down the columns are shifted left by one, and once again even further down.

**Comment by janbartel** [comment]
Fixed.
