### ISSUE TITLE
[jetty-osgi] The CCL while parsing the xml files should be set to a combination of Jetty and Bundle-Classloader

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#482]
When referncing custom Classes in the XML files these currently fails with CNF-Exception since the Context-Classloader is set to jetty-boot. It should fallback to the bundle of the cfg-files if any is given. I'll try to contribute a Pull-Request that shows a minimal work-around the next days.

**Comment by janbartel** [comment]
Pull request merged (also had to fix the jetty xml config file).
