### ISSUE TITLE
jetty-client : upon timeout, how to know if server was too slow, or if request was queued too long?

### ISSUE THREAD

**Issue by mofleury** [eclipse/jetty.project#4827]
**Jetty version**
9.4.24.v20191120

**Java version**
1.8.0_172, should not matter

**Question**
Jetty client is very good at handling NIO and timeouts, but there is one thing that is causing us headaches at the moment : when a request times out because the response was not received before the read timeout has elapsed, the exception that we receive in the stack trace has a root cause "Total timeout {x} ms elapsed". This is good, but when troubleshooting production, it is not always enough. In particular, in case of high loads, we don't know if the server was too slow to respond, or if the request timed out while in the queue, and never reached the server. This information is crucial for us in order to correctly troubleshoot the issue.

We can get some information by enabling debug logs of org.eclipse.jetty.client.HttpExchange, because the logging is different in each case, but it is not a practical solution for production usage... The code that generates this is in org.eclipse.jetty.client.HttpExchange#abort
```
// Case #1: exchange was in the destination queue.
        if (destination.remove(this))
        {
            if (LOG.isDebugEnabled())
                LOG.debug("Aborting while queued {}: {}", this, failure);
            notifyFailureComplete(failure);
            return true;
        }

        HttpChannel channel = getHttpChannel();
        if (channel == null)
        {
            // Case #2: exchange was not yet associated.
            // Because this exchange is failed, when associate() is called
            // it will return false, and the caller will dispose the channel.
            if (LOG.isDebugEnabled())
                LOG.debug("Aborted before association {}: {}", this, failure);
            notifyFailureComplete(failure);
            return true;
        }

        // Case #3: exchange was already associated.
        boolean aborted = channel.abort(this, abortRequest ? failure : null, abortResponse ? failure : null);
        if (LOG.isDebugEnabled())
            LOG.debug("Aborted ({}) while active {}: {}", aborted, this, failure);
```
What I would like is that somewhere in the stack trace, we have sufficient information to know if we are in case 1, 2 or 3.

Is there a way to do that without changes to the source code? I tried to find some extension point in the source code that I could use for this, but was not able to find any.

Given how important this is to us, I am willing to work on a Pull Request to implement the necessary change (for example wrap the exception to add more details), do you have a suggestion on the best way to tackle this problem?

Thank you!

**Comment by sbordet** [comment]
@mofleury I think you can already do what you want:

```java
httpClient.newRequest(host, port)
  .onRequestCommit(r -> r.attribute("committed", true))
  ...
  .send(...);
```

When you get a failure due to the total timeout exception, you can query the request attribute to know whether the request was committed (i.e. sent over the network) or not.

**Comment by mofleury** [comment]
that looks very promising, thank you for the quick response! I'll experiment with this option, and will let you know if it is sufficient for my need asap.

**Comment by mofleury** [comment]
Your trick helped a lot, I can now detect these cases, and provide information in the stacktrace of the error. In case you are interested, my solution looks like this : 
```
httpClient = new HttpClient(transport, sslContextFactory) {

			// enhancing client to know if requests were sent to server
			// see https://github.com/eclipse/jetty.project/issues/4827
			@Override
			public Request newRequest(URI uri) {
				Request request = super.newRequest(uri);

				AtomicBoolean requestSent = new AtomicBoolean(false);

				request.onRequestCommit(request1 -> requestSent.set(true));

				request.onResponseFailure((response, failure) -> {
					if (!requestSent.get()) {
						failure.addSuppressed(
								new IllegalStateException("Request was not sent to server, there must be too many calls queued : " + request));
					}
				});

				return request;
			}
		};
```

I had to subclass the client to be able to inject the bahaviour into the JAX-RS JettyConnector, and use a suppressed exception to attach information to the failure ; both of these tricks are not very nice, but they get the job done. I would love to see something in the standard error processing that provides this information and remove these hacks, but it will do for now.

If you have suggestions to improve this solution, I'm interested :)

Thank you for your help!

**Comment by sbordet** [comment]
@mofleury I would ask the JAX-RS JettyConnector to expose an overridable method (or setting a function) to allow to easily customize the request, so you would override/set the JAX-RS JettyConnector rather than Jetty's `HttpClient`.
