### ISSUE TITLE
Make PROXY protocol local address optional

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4842]
**Jetty version**
9.4.x

**Description**
In a setup where client C talks to a server S via a proxy P, and the proxy uses the PROXY protocol towards the server, it may be desirable that the local address is not overridden.

Given:

`C_ip:port -> P_server_ip:port -> P_client_ip:port -> S_ip:port`

In the typical case with the PROXY protocol, the application on the server sees `remote=C_ip:port` and `local=P_server_ip:port`.

However, there are cases where this is desired instead: `remote=C_ip:port` and `local=S_ip:port`.

`ProxyConnectionFactory` could perhaps be enhanced to optionally discard the PROXY protocol data that ends up, on the server, as the `local` address.

**Comment by sbordet** [comment]
I think the best would be to expose all the information, somehow.
So perhaps keep the current behavior, and expose `P_client_ip:port` and `S_ip:port`.
This needs to work with TLS too.

@lorban please explore whether it's possible to use a request customizer (`HttpConfiguration.Customizer`) to implement this.

**Comment by sbordet** [comment]
@gregw how do you think this should be implemented?
Request attribute?
HTTP header similar to X-Forwarded-*?
Other?

**Comment by lorban** [comment]
Following our discussion, we're going for the request attributes.

**Comment by joakime** [comment]
Merged PR #4849 into `jetty-9.4.x`
