### ISSUE TITLE
Proxy protocol v2 mistakenly ignores address length when LOCAL command is specified

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#4843]
**Jetty version**
9.4.27

**Java version**
11.0.7

**OS type/version**
Linux

**Description**
Jetty does not correctly process a proxy-protocol v2 header when the command is LOCAL and the header's address length field is non-zero.

**Comment by joakime** [comment]
PR #4844 merged into `jetty-9.4.x`
