### ISSUE TITLE
Unexpected message - WARN AnnotationParser: Unrecognized ASM version, assuming ASM7

### ISSUE THREAD

**Issue by mrsladek** [eclipse/jetty.project#4846]
Jetty (9.4.28.v20200408) on Java 11

Jetty seems to be emitting an warning at startup:
WARN AnnotationParser: Unrecognized ASM version, assuming ASM7

We have ASM version 8.0.1 in our project classpath.
When downgrading to version 7.0 the warning dissapears.
Is this behaviour intended?

**Comment by janbartel** [comment]
This is expected: we currently ship with asm 7.2.  When you interact with asm, you have to pass in the expected api compatibility level, so far we support up to asm-7 compatibility. This log message is just saying that we parsed the version of asm from the manifest, but didn't recognize it (as we currently recognize only up to version 7). We will pass in api compatibility level 7 to the asm parser, which is capable of parsing code up to jdk 14, so if you're using jdk11, you should be fine.

I'll close the bug for now, please do reopen if you have further concerns.
