### ISSUE TITLE
Introduce socket configuration properties in Jetty XML files

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4847]
**Jetty version**
9.4.x

**Description**
It would be great if `jetty-http.xml` and `jetty-ssl.xml` have additional configuration properties for the common socket configuration parameters, in particular:

* tcpNoDelay
* rcvBufferSize
* sndBufferSize
* reuseAddress

Other parameters such as `keepAlive`, `soTimeout`, `OOBInline` are much less common, so they can be set by subclassing `ServerConnector`.

**Comment by joakime** [comment]
PR #4856 Merged.
