### ISSUE TITLE
Jetty HttpClient get remote IP address

### ISSUE THREAD

**Issue by josepowera** [eclipse/jetty.project#4853]
**Question**

When using Jetty HttpClient we connect to remote server via full URL using DNS name.   
example: https://www.cnn.com/robots.txt

However for Tracing of have to get remote server IP after resolve was completed. That means that we need real IP address of www.cnn.com where Connection was established: 123.123.123.123.  or at least where Connection tryed but failed to establish.

Is there any simple way to get this data using Jetty HttpClient / Jetty HttpClient Listeners?

probably we are looking at SocketAddress[i]
https://github.com/eclipse/jetty.project/blob/2e1c01ac8cff84f988d68f68f55b3e95d77ade5c/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java#L594

or getRemoteAddress() in
https://github.com/eclipse/jetty.project/blob/2e1c01ac8cff84f988d68f68f55b3e95d77ade5c/jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpConnectionOverHTTP.java#L249

**Comment by sbordet** [comment]
If there is a forward proxy, what address to you want to see, the proxy where the client connects to, or the server where the proxy connects to?

**Comment by josepowera** [comment]
HttpClient connects directly to final server (no intermediate forward proxy on our end). We are still at protocol HTTP/1.1 for this case.

If we used proxy (that we don't!) , it makes sense to get proxy server address (next upstream that you connect to)...   Same

**Comment by sbordet** [comment]
You see how this gets complicated really soon.

What you want to "trace" is application specific, so perhaps you want to do it in the application.
You get `www.cnn.com`, you resolve it to an IP, you trace it, and then you use the IP in `HttpClient`.
How does it sound?

**Comment by josepowera** [comment]
With tracing I mean Zipkin/Jaeger style...  What we wanted is to add remote IP to attributes in Jaeger span.

Something like in https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/HttpRequestListener.java

We used manual Resolve before httpclient.Send, until most sites moved to Https and than we had to remove this (some problem with SSL when we Resolved and changed URL to IP http://123.123.123.123/robots.txt and manually added HttpHeader for hostname.

**Comment by joakime** [comment]
Doing the resolve to IP, connect via IP, using `Host` header for the machine name seems like it wouldn't be very SNI friendly.

**Comment by sbordet** [comment]
@josepowera the class you linked does nothing more than forwarding to another class.

I fail to understand how IP addresses are related to sites moving to `https`?

**Comment by joakime** [comment]
No further information provided.
Closing
