### ISSUE TITLE
Review HttpFields API consistency

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4859]
**Jetty version**
10

**Description**
Consider adding frequently used `HttpFields.addIfAbsent()`, `addIfNotNull()`.
Review `add*()` methods because in some cases for null values are noop, sometimes they throw etc.
Stick with strict APIs for `HttpFields`, and eventually implement throws in `Request`/`Response`.

**Comment by joakime** [comment]
PR #4845 merged.
