### ISSUE TITLE
Combine `AttributesMap` and `Attributes.Wrapper`

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4861]
We have previous identified that creating a map to hold request attributes can be a source of unnecessary garbage for simple requests that don't need attributes.  We now have two mechanism for dealing with this:

1. The `AttributesMap` class, which is itself lazily created, has an `AtomicReference` to the actual map used, which is only created if an attribute is set.
2. The `Attributes.Wrapper` class has recently been added to allow the `Attributes` of a request to be wrapped rather than set, thus using fields for special attributes rather than creating the lazy map.

These approaches have worked well, simplifying code and reducing garbage.... except they are not complete. @lorban has identified that the async attributes created in `startAsync` are still a source of some garbage, but when @lachlan-roberts attempted to implement the wrapping mechanism for them (https://github.com/eclipse/jetty.project/pull/4851/commits/08e713d8498d1eebad3a88eac5b71bae1f6343cc), a problem was identified.      The wrapping works for dispatch, because attributes are wrapped during the dispatch and then removed after the dispatch - thus the chain of wrappers can act as a stack with extra wrappers being popped on and off.     

But for async, once started, the attributes are left set, so if they are set during a dispatch (Eg. a forward), then they will wrap the dispatch attributes and when the dispatch is over the old attributes pre-forward will be replaced and the async attributes lost.  

This could be fixed by allowing some wrap under semantic, but that would be a third mechanism to do the same thing!

Instead I think we should do the following:
- Change `AttributesMap` to have an internal, initially empty list/queue of `Attributes` instances.
- Lookup for attributes are implemented in `AttributesMap` by iterating of the list/queue until a non null value is found (or perhaps allows a NULL poison pill value to do non destructive deletes).
- If a set is done on the attributes... then I have not thought out exactly how that could be handled as currently set does not return anything to say it was handled... but ultimately we again try all the `Attributes` instances in the list/queue and if none accept the set, then a hashmap instance if `Attributes` is put onto the end of the queue (replacing the original lazy creation).  We probably need to change `Attributes` interface for this... or perhaps have a sub interface with the required set signature.
- Remove the `Attributes.Wrapper` mechanism.  Current usages would be converted to adding a special `Attributes` instance to the `AttributesMap`'s list/queue.  This can be left there (as in `SecureRequestCustomizer` and `startAsync()`, or the instance can be later removed (as for dispatch), even if no longer on top of the "stack"
- I think having a lazily created `AttributesMap` that then lazily creates the actual map is a bit too much.   So I think we can make `AttributesMap` a final field on `Request` and just initialise it once.... specially as we are now always recycling requests even for HTTP2, so the instance will be reused for persistent connections.
 
This might be able to be done in 9.4, but prime target is 10/11

**Comment by gregw** [comment]
@lachlan-roberts @lorban , you have both worked in this area recently.  Can you team up to implement this? Either pair program or author/review, your call.

**Comment by gregw** [comment]
Oh and feel free to come up with a better solution!

**Comment by lachlan-roberts** [comment]
We have decided against the larger refactor of `AttributesMap` for now, instead changes from PR #4861 allow us to add an `AsyncAttributes` class to the request which stores the async attributes as fields instead of using the `AttributesMap` and producing extra garbage.
