### ISSUE TITLE
Is there any way to create a custom Client Certificate authenticator for Jetty, the same way you can configure a custom JAAS LoginModule?

### ISSUE THREAD

**Issue by dattasid** [eclipse/jetty.project#4866]
**Jetty version**
9.4.28
**Java version**
1.8.0
**Question**
Is there any way to create a custom Client Certificate authenticator for Jetty? Or maybe a custom Certificate to user name mapper ?

**Comment by sbordet** [comment]
Please detail much better your question. A simple code snippet with pseudo-code would help.
