### ISSUE TITLE
JDK 9 build compatibility

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#487]
Project Jigsaw (JDK 9 modules) has been integrated in the JDK 9 snapshots since JDK 9 b111.

Jetty must be able to at least compile under JDK 9, and eventually run the test suite.

Currently there are a number of road blocks, in particular:
- JDK 9 changed the format of the `java.version` system property from e.g. `1.8.0_77` to `9-ea`, see http://openjdk.java.net/jeps/223.
- Maven plugins needs to be released with JDK 9 support, in particular the `maven-jar-plugin` (see https://issues.apache.org/jira/browse/MJAR-205), the `maven-war-plugin` (failing with a similar problem as the `maven-jar-plugin` but I could not find any issue related to JDK 9 integration), the `maven-clirr-plugin` and possibly others.
- A JDK 9 implementation of ALPN. While this can be in its own module, the other modules that depend on ALPN need to be able to select the ALPN implementation at runtime: `jetty-alpn-parent`, `http2-alpn-tests`, `http2-http-client-transport`, `test-http-client-transport`. See also #486.

**Comment by sbordet** [comment]
Maven WAR plugin issue: https://issues.apache.org/jira/browse/MWAR-387

**Comment by sbordet** [comment]
### Build
Once the relevant Maven plugins are updated, it is fairly easy to enable profiles for JDK 8 that will use `alpn-boot` for the modules that depend on it (listed above).

### Runtime
At runtime we need dynamic module selection based on whether the JDK is 8 or 9.
Turns out that class `StartArgs` injects property `java.version.major` that we can use.
So at runtime, module `http2` will depend on module `alpn`; module `alpn` will depend on `alpn-${java.version.major}`; module `alpn-8` will depend on `alpn-impl-${java.version}`; module `alpn-9` will depend on `alpn-impl-java` which will contain a JDK 9 ALPN implementation.

**Comment by sbordet** [comment]
Build part has been fixed.

Runtime part moved to #486.

**Comment by sbordet** [comment]
Building with JDK 9 also required update of the Maven Assembly Plugin, see https://issues.apache.org/jira/browse/MASSEMBLY-808.

**Comment by joakime** [comment]
jdk9 is available on jenkins now

**Comment by sbordet** [comment]
We can't depend on SNAPSHOT versions of the plugins, so we need to keep this issue open until solved.

Maven WAR Plugin 3.0.0 has been released.

The Maven Assembly Plugin also needs to be at 3.0.0, but it has not been released yet.

**Comment by sbordet** [comment]
JaCoCo needs at least version 0.7.8.

**Comment by sbordet** [comment]
The Maven Assembly Plugin 3.0.0 has been released, but the Maven WAR Plugin still has issues, in particular https://issues.apache.org/jira/browse/MWAR-397.

However, the issue can be worked around using `--add-opens` as specified in MWAR-397.

**Comment by sbordet** [comment]
Current status is that it is possible to build Jetty with JDK 9, as long as the workaround for MWAR-397 is applied.

**Comment by namannigam** [comment]
@sbordet https://issues.apache.org/jira/browse/MWAR-387 is currently Closed. Does that mean we can build Jetty with JDK9 without any workaround?

**Comment by sbordet** [comment]
@namannigam that is correct, Jetty builds fine with JDK 9 - although we still have a few test failures that we're working on fixing.

If you want to build Jetty with JDK 9 and skip test execution:

```
mvn clean install -DskipTests
```

**Comment by namannigam** [comment]
@sbordet I can see https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.7.RC0 consisting of 
> 487 JDK 9 build compatibility
Shall I still try and build jetty independently skipping tests?

**Comment by sbordet** [comment]
You can use 9.4.7.RC0 if you want. It's the first Jetty release built with JDK 9.

**Comment by namannigam** [comment]
Facing an issue using that combination(9.4.7.RC0 + jdk9) what's the correct place to share them?

**Comment by sbordet** [comment]
Please open a new issue.

**Comment by namannigam** [comment]
@sbordet Do take a look at #1758

**Comment by sbordet** [comment]
We now get full clean builds with JDK 9, so this bug can be closed.
