### ISSUE TITLE
Improve WebSocket configurability

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#488]
`WebSocketPolicy` has a number of properties, whose setters impose too strict checks on the values.

For example, `WebSocketPolicy.assertValidTextMessageSize()` seem to allow to skip the check when `WebSocketPolicy.maxTextMessageSize <= 0`, but unfortunately it is impossible to set a negative value for `maxTextMessageSize` because of the strict checks on the setter method.

IMHO the setter methods checks should be removed (all of them), and account for possible values where the value is actually used.

**Comment by gregw** [comment]
whilst on the subject of configuring WebSockets,    I have long thought that we should investigate if such configuration (or at least default configuration if it can be overridden by application) should be set on a WebSocketConnectionFactory that is added to the ServerConnector.

This would make Websockets follow the same configuration pattern we use for HTTP, HTTP/2, FCGI, as all these connection types are configured via factories on the connector.

I understand that there may well be differences, but I'd like to hang this out there as an aspirational target... either for 9.4 or 10.0

**Comment by joakime** [comment]
These configurations have two levels.

The default, and the endpoint specific.

For jetty native websockets, the defaults are most often used, but can be overridden per endpoint, and even per subprotocol.
For JSR356, the defaults are rarely used, as each endpoint configuration pretty much forces a value.  The configurators can always override them during endpoint creation as well.

Also, when you encounter a webapp that had more than one websockets endpoint, they are very often using different configurations.

Having this on the connector would only serve to set what the server wide defaults are.

**Comment by joakime** [comment]
The other problem with connector based configuration of websocket is the need to coordinate with the webapp for websocket (something we don't currently do for HTTP, HTTP/2, or FCGI)
