### ISSUE TITLE
setCookie() must not change the headers in a response during an include

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4885]
**9.4**

Servlet Spec 4.0 Section 9.3 The Include Method:

> It cannot set headers or call any method that affects the headers of the response, with
> the exception of the HttpServletRequest.getSession() and
> HttpServletRequest.getSession(boolean) methods. 

Whilst we handle the session correctly, the generic Response.addCookie() method is not protected.

**Comment by joakime** [comment]
Wow, how long has this been true in the Servlet spec?
And is this something we should have back in `jetty-9.4.x`?

Perhaps `jetty-9.4.x` could at least warn users when they do this that the behavior in Jetty is deprecated and will be changed in a future version of Jetty?

**Comment by janbartel** [comment]
I've already targeted this issue at 9.4.30 as this text has been present at least as far back as servlet 3.1 spec.
