### ISSUE TITLE
update version of org.apache.aries.spifly.dynamic.bundle on document for jetty-9.4.23.v20191118

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#4887]
**Jetty version**
jetty-9.4.23.v20191118 and up

**Java version**
13 and up

**Description**
#3869 to support jdk-13 but org.apache.aries.spifly.dynamic.bundle-1.2.jar not ready for 13

so should update document to point to 1.2.4

**Comment by olamy** [comment]
done thanks for the report!
