### ISSUE TITLE
WebAppContext serverClasses list cannot be modified from within xml config

### ISSUE THREAD

**Issue by annorax** [eclipse/jetty.project#490]
I tried using `addServerClass()`, `prependServerClass()` and `setServerClasses()` to manipulate the server class list from within jetty-web.xml but it wouldn't budge. Almost as though it's immutable.

The docs, however, [clearly state](http://www.eclipse.org/jetty/documentation/current/jetty-classloading.html) that this list *can* be manipulated, and indeed why else would these methods exist.

I then went to the code and saw that this is intentional - a comment in the implementation of JettyWebXmlConfiguration says:

    No server classes while configuring

... this class saves a snapshot of the list before applying the xml config and then restores it later, overriding any changes that the xml config makes.

But why? And how / when else would I change the server class list? By the time I have programmatic access to the WebAppContext, my app has been loaded, and it's too late - the NoClassDefFoundError has already been thrown.

I really need this in order to let one of my dependencies "see" the package `org.eclipse.jetty.ssl`, which is hidden by default due to the default server class pattern `org.eclipse.jetty.`.

**Comment by janbartel** [comment]
@annorax yes the list can be manipulated, but as it turns out, only **externally** to the webapp. So the workaround for you is to set it up in a context xml file, which is applied _before_ the webapp is started/starting.

Note that in the master branch of jetty (ie jetty-9.4 and beyond) we are looking at removing the necessity for manual manipulation of the server and system classpaths, as they are error prone and difficult to understand.

**Comment by annorax** [comment]
What woule be the alternative, then, to this error prone approach? Which
other recourse is there for a person in my situation, who has an in-app
dependency on a server-class-listed jar?
On Apr 7, 2016 1:38 AM, "Jan Bartel" <notifications@github.com> wrote:

@annorax <https://github.com/annorax> yes the list can be manipulated, but
as it turns out, only *externally* to the webapp. So the workaround for you
is to set it up in a context xml file, which is applied *before* the webapp
is started/starting.

Note that in the master branch of jetty (ie jetty-9.4 and beyond) we are
looking at removing the necessity for manual manipulation of the server and
system classpaths, as they are error prone and difficult to understand.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/eclipse/jetty.project/issues/490#issuecomment-206598994>

**Comment by gregw** [comment]
Annorax,

in the future (see the 9.4.x-Feature) branch, we are looking at using a
ServiceLoader mechanism to avoid any need to call setServerClasses.

But for 9.3.x, I agree that this is a bug - albeit one that is hard to fix.
   Hence Jan was suggesting a work around of putting the classpath
configuration in a context XML file:
https://www.eclipse.org/jetty/documentation/current/configuring-specific-webapp-deployment.html

We will look at fixing this bug in 9.3.x, but I think that any solution
will only be partial.  The mechanism is over complex and best to avoid in
future.... not that helps you much now.

regards







On 7 April 2016 at 14:20, annorax <notifications@github.com> wrote:

> What woule be the alternative, then, to this error prone approach? Which
> other recourse is there for a person in my situation, who has an in-app
> dependency on a server-class-listed jar?
> On Apr 7, 2016 1:38 AM, "Jan Bartel" <notifications@github.com> wrote:
>
> @annorax <https://github.com/annorax> yes the list can be manipulated, but
> as it turns out, only *externally* to the webapp. So the workaround for you
> is to set it up in a context xml file, which is applied *before* the webapp
> is started/starting.
>
> Note that in the master branch of jetty (ie jetty-9.4 and beyond) we are
> looking at removing the necessity for manual manipulation of the server and
> system classpaths, as they are error prone and difficult to understand.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/eclipse/jetty.project/issues/490#issuecomment-206598994
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipse/jetty.project/issues/490#issuecomment-206690682>
>



-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by gregw** [comment]
Actually.... following a suggestion from @janbartel , have come up with a pretty good fix.  Now pushed and it would be great if you could test.

**Comment by annorax** [comment]
@gregw, thanks! I'll wait for the next snapshot jar to go up, grab it, run the test and let you know.

**Comment by annorax** [comment]
@gregw and @janbartel: the fix is working for me. This lets me keep my app's config self-contained and is much more convenient than setting up a context xml file just for this. Thanks!

**Comment by gregw** [comment]
Note that when I merged the fix into the master branch, it turned out that I had already fixed this problem there (a slightly different way).    The two different approaches should be transparent to jetty-web.xml, so just noting for posterity that d9bfc8b was kind of wiped out when merged to master.
