### ISSUE TITLE
Error during WebSocket handshake in Chrome

### ISSUE THREAD

**Issue by lucaro** [eclipse/jetty.project#4900]
**Jetty version**

jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95

**Java version**

 jvm 11.0.6+8-b765.40

**OS type/version**

Windows 10 version 19.09

**Description**

(Note: I first posted this issue in the Javalin project since I observed it in that context, see https://github.com/tipsy/javalin/issues/975. Some further investigation indicated however that the issue is independent of Javalin, so I'm posting it here again.)

The problem is that I'm unable to establish a wss connection to a javalin endpoint using Chrome. Wss works as expected in Firefox and http, https and ws connections work without any issue in both browsers. Chrome does however always return the following error message: `Error during WebSocket handshake: Invalid status line`

The error is independent of the used keystore, I tried it with a self-signed cert via localhost and via a cert validated through Let's Encrypt and a proper domain, both with the exact same behavior. It works fine without SSL. It also does not work without HTTP2 and with SSL, the other way around is not testable since Chrome does not do HTTP2 over unencrypted connections. The error does however change to `Connection closed before receiving a handshake response` when not using HTTP2. Below is a minimal working example (in Kotlin) to reproduce the problem. I used https://www.websocket.org/echo.html to test the websocket.

```kotlin

import org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory
import org.eclipse.jetty.http2.HTTP2Cipher
import org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory
import org.eclipse.jetty.server.*
import org.eclipse.jetty.util.ssl.SslContextFactory
import org.eclipse.jetty.websocket.api.Session
import org.eclipse.jetty.websocket.api.annotations.*
import org.eclipse.jetty.websocket.server.WebSocketHandler
import org.eclipse.jetty.websocket.servlet.WebSocketServletFactory
import java.io.IOException


object WSTestJetty {

    @JvmStatic
    fun main(args: Array<String>) {

        val server = setupHttpServer()
        val wsHandler: WebSocketHandler = object : WebSocketHandler() {
            override fun configure(factory: WebSocketServletFactory) {
                factory.register(MyWebSocketHandler::class.java)
            }
        }
        server.handler = wsHandler
        server.start()
        server.join()

    }

    private fun setupHttpServer(): Server {

        val httpConfig = HttpConfiguration().apply {
            sendServerVersion = false
            sendXPoweredBy = false
            secureScheme = "https"
            securePort = 443
        }

        val httpsConfig = HttpConfiguration(httpConfig).apply {
            addCustomizer(SecureRequestCustomizer())
        }

        val alpn = ALPNServerConnectionFactory().apply {
            defaultProtocol = "http" //"h2"
        }

        val sslContextFactory = SslContextFactory.Server().apply {
            keyStorePath = "keystore.jks"
            setKeyStorePassword("password")
            //cipherComparator = HTTP2Cipher.COMPARATOR
            provider = "Conscrypt"
        }

        val ssl = SslConnectionFactory(sslContextFactory, alpn.protocol)

        val http2 = HTTP2ServerConnectionFactory(httpsConfig)

        val fallback = HttpConnectionFactory(httpsConfig)


        return Server().apply {

            addConnector(ServerConnector(server, HttpConnectionFactory(httpConfig), HTTP2ServerConnectionFactory(httpConfig)).apply {
                port = 80
            })

            addConnector(ServerConnector(server, ssl, alpn, http2, fallback).apply {
                port = 443
            })
        }
    }
}

@WebSocket
class MyWebSocketHandler {
    @OnWebSocketClose
    fun onClose(statusCode: Int, reason: String) {
        println("Close: statusCode=$statusCode, reason=$reason")
    }

    @OnWebSocketError
    fun onError(t: Throwable) {
        println("Error: " + t.message)
    }

    @OnWebSocketConnect
    fun onConnect(session: Session) {
        println("Connect: ${session.remoteAddress.address}")
        try {
            session.getRemote().sendString("Hello Webbrowser")
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }

    @OnWebSocketMessage
    fun onMessage(message: String) {
        println("Message: $message")
    }
}

```

**Comment by joakime** [comment]
Bootstrapping WebSocket over HTTP/2 ([RFC8441](https://tools.ietf.org/html/rfc8441)) was added to Jetty 10.0.x

See https://github.com/eclipse/jetty.project/issues/3537

Jetty 10.0.0.alpha2 contains support for WebSocket over HTTP/2.

Jetty 9.4.x does not.

**Comment by lucaro** [comment]
Thanks for the quick response. The problem does however also occur when HTTP/2 is not used, Chrome then replies with `Connection closed before receiving a handshake response`.

**Comment by lucaro** [comment]
Thanks for the quick reply, explicitly setting the protocol to `http/1.1` appears to have solved the problem.
