### ISSUE TITLE
Do not assume gzip acceptable for HTTP/2

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#491]
The Accept-Encoding header is explicitly not checked by the [GzipHandler](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java#L263-L280).  I believe this can be traced back to a SPDY specification issue [coded into the SPDY connection factory](https://github.com/eclipse/jetty.project/blob/d9ada8a1eb3b5b6c65f43885bf557692a8ce94eb/jetty-spdy/spdy-http-server/src/main/java/org/eclipse/jetty/spdy/server/http/HTTPSPDYServerConnectionFactory.java#L100-L107) .

**Comment by gregw** [comment]
@sbordet can you confirm this is OK?

**Comment by sbordet** [comment]
The change is correct, HTTP/2 does not require user-agents to support gzip. SPDY did because HTTP header compression was based on gzip, but HTTP/2 uses hpack.
