### ISSUE TITLE
HttpClient: HttpCookieStore.Empty prevents sending cookies

### ISSUE THREAD

**Issue by qtxo** [eclipse/jetty.project#4929]
**Jetty version**
9.4.29.v20200521

**Java version**
11.0.7 (irrelevant)

**OS type/version**
Windows 10 (irrelevant)

**Description**

My custom `AbstractProxyServlet` modifies some cookie from the client to be consumed in the target backend but a recent commit cac5ada73443e79144d0a01270a62d7a89d881f5 breaks that functionality, the line https://github.com/eclipse/jetty.project/blob/cac5ada73443e79144d0a01270a62d7a89d881f5/jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java#L191-L203 introduces a check to ignore ALL cookies including the request ones when the `CookieStore` is `HttpCookieStore.Empty` which is set unconditionally in https://github.com/eclipse/jetty.project/blob/jetty-9.4.29.v20200521/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L285-L286, and there is no way to set other CookieStore.

In all recent versions until this one the request cookies work because there is no check. My expectation is that the Empty cookie store is used to avoid storing cookies set from the backend and the proper check would make more sense in the line 195 just to prevent executing the next line `cookies = convertCookies(HttpCookieStore.matchPath(uri, cookieStore.get(uri)), null);`

If this makes sense I can provide a pull request.

**Comment by sbordet** [comment]
@qtxo good catch, sorry for this regression.
The reason for the additional check was to save the call to `request.getURI()`.
We'll rearrange the code to consider request cookies and add a test case.
Thanks!
