### ISSUE TITLE
acceptorQueueSize [sic] - Documentation and http.ini examples have incorrect parameter name

### ISSUE THREAD

**Issue by huntharo** [eclipse/jetty.project#4939]
**Jetty version**

9.4.29.v20200521 (and probably many others)

**Java version**

Any

**OS type/version**

Any

**Description**

Documentation / ini file references for `acceptQueueSize` configuration are incorrectly listed as `accept[or]QueueSize` - Setting `acceptorQueueSize` has no effect while setting `acceptQueueSize` works as intended.

##### Source References

https://github.com/eclipse/jetty.project/search?q=acceptorQueueSize&unscoped_q=acceptorQueueSize

![image](https://user-images.githubusercontent.com/5617868/83779502-05098980-a65a-11ea-85f4-4e69430aaea8.png)

##### Documentation Reference

https://www.eclipse.org/jetty/documentation/current/configuring-connectors.html

![image](https://user-images.githubusercontent.com/5617868/83779825-6af61100-a65a-11ea-8f94-d7d2162228e2.png)

##### Jetty Download - Demo-Base - Example http.ini Reference

![image](https://user-images.githubusercontent.com/5617868/83780085-b4466080-a65a-11ea-9840-39622147bf37.png)

##### Testing Instructions

- Mac
  - Base-case: `java -jar ../start.jar -Djetty.port=8000 -Djetty.http.acceptorQueueSize=100`
    - Get Listen Queue Depth: `netstat -Lan | grep 8000`
    - Expected: `0/0/100`
    - Actual: `0/0/50`
  - Fixed-case: `java -jar ../start.jar -Djetty.port=8000 -Djetty.http.acceptQueueSize=100`
    - Get Listen Queue Depth: `netstat -Lan | grep 8000`
    - Expected == Actual: `0/0/100`
- Linux
  - Base-case: `java -jar ../start.jar -Djetty.port=8000 -Djetty.http.acceptorQueueSize=100`
    - Get Listen Queue Depth: `ss -l | egrep 'Netid|:8000'`
    - Expected: `Recv-Q: 0, Send-Q: 100` (Recv-Q == current depth, Send-Q == configured depth)
    - Actual: `Recv-Q: 0, Send-Q: 50` (Recv-Q == current depth, Send-Q == configured depth)
  - Fixed-case: `java -jar ../start.jar -Djetty.port=8000 -Djetty.http.acceptQueueSize=100`
    - Get Listen Queue Depth: `ss -l | egrep 'Netid|:8000'`
    - Expected == Actual: `Recv-Q: 0, Send-Q: 100` (Recv-Q == current depth, Send-Q == configured depth)

**Comment by WalkerWatch** [comment]
@huntharo Thank you for the extremely well detailed report. I will get this fixed for the next release.

**Comment by joakime** [comment]
Typo fix merged into `jetty-9.4.x`.
