### ISSUE TITLE
InvalidAlgorithmParameterException: ManagerFactoryParameters not supported

### ISSUE THREAD

**Issue by NageshSoni** [eclipse/jetty.project#4947]
Jetty version
9.4.24.v20191120

Java version
1.8

Question
I have configured SSL in my client as below:

SslContextFactory sslContextFactory = new SslContextFactory.Client();
sslContextFactory.setProvider("Conscrypt"); 
if (!endpointIdentification)
{
    sslContextFactory.setEndpointIdentificationAlgorithm(null);
}
sslContextFactory.setTrustStorePath(certificateLocation);
sslContextFactory.setTrustStorePassword(certificatePassword);
//below parameter set to validate expiry of certificate while SSL handshake
sslContextFactory.setValidatePeerCerts(true);

I am getting this exception while starting my client.
InvalidAlgorithmParameterException: ManagerFactoryParameters not supported

**Comment by joakime** [comment]
Please include the entire stacktrace.

Also what does this return? (after you start your client).

``` java
System.err.println("Trust Manager Factory Algorithm: " + Security.getProperty("ssl.TrustManagerFactory.algorithm"));
```

Looking at the Conscrypt code, it looks like you are trying to use `PKIX` with Conscrypt.
That's not supported by Conscrypt.

**Comment by NageshSoni** [comment]
StackTrace:

java.security.InvalidAlgorithmParameterException: ManagerFactoryParameters not supported
	at org.conscrypt.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:273)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getTrustManagers(SslContextFactory.java:1287)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:375)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)


Output of : System.err.println("Trust Manager Factory Algorithm: " + Security.getProperty("ssl.TrustManagerFactory.algorithm")); is as below

Trust Manager Factory Algorithm: PKIX

And above exception is coming after setting below parameter in SslContextFactory

sslContextFactory.setValidatePeerCerts(true);

I am setting above parameter to get SSL handshake exception when certificate expires. 

keytool -genkey -v -keystore keystore -storetype pkcs12

keytool -export -alias mykey -storepass password -file test.cer -keystore keystore

keytool -import -trustcacerts -file test.cer -keystore truststore

I am setting above generated truststore in SslContextFactory.

**Comment by NageshSoni** [comment]
How can I check certificate validity in Jetty client during SSL handshake?

**Comment by sbordet** [comment]
> How can I check certificate validity in Jetty client during SSL handshake?

If the server certificate is properly signed by a CA, this is done automatically with the default configuration (`EndpointIdentificationAlgorithm="HTTPS"`) and you don't need to do anything.

If you disable `EndpointIdentificationAlgorithm`, then you have the option to set a `HostnameVerifier` in `SslContextFactory.Client` (read the javadocs).

If that does not work, it's probably a Conscrypt issue.

In particular the combination `validatePeerCerts=true && PKIX` is not supported by Conscrypt.
