### ISSUE TITLE
getting 404 after upgrading jetty

### ISSUE THREAD

**Issue by LirazRom** [eclipse/jetty.project#4951]
**Jetty version**
9.4.29.v20200521
**Java version**
8
**Question**
I have upgraded jetty servlet to 9.4.29.v20200521 from 9.2.13.v20150730
i am using resteasy. After the upgrade for every call I am getting 404
what need to be changed?

**Comment by gregw** [comment]
@LirazRom You have not provided us with enough information.
How are you deploying? Webapp or embedded?  Are you using a jetty-base?
Is there anything in the logging of interest?
Can you run with debug on?
Can you get a server dump after starting etc.

**Comment by LirazRom** [comment]
Hi
I am running with scala it is webapp
in the logging there is nothing - i see it load the ciphers and every thing
how can i run with debug on?

**Comment by joakime** [comment]
In your scala code, find the instantiated `Server` object and call the method `.setDumpAfterStart(true);` before you call `.start();`

That should produce a dump of the state of the server, copy/paste that into this issue, we can tell you what the server sees and is doing from that.

**Comment by janbartel** [comment]
@LirazRom if your question has been answered, please close the issue.
