### ISSUE TITLE
Simplify ability to get Byte Counts about requests

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4954]
**Jetty version**
9.4.29

**Description**
There are several techniques used by web projects to collect information about byte counts.

Most are based on using the Servlet API.
The most common technique being ...
1. Create a Filter
2. Have Filter create a HttpServletRequestWrapper and HttpServletResponseWrapper.
3. Any stream access is wrapped (HttpServletRequest.getInputStream(), HttpServletRequest.getReader(), HttpServletResponse.getOutputStream(), HttpServletResponse.getWriter())
4. When dispatch returns to the Filter the number of bytes that have gone through the stream is the "byte count" used for whatever purpose the developer needs.

This has a few flaw.

 * Unable to get HTTP Request Header size
 * Unable to get HTTP Response Header size
 * GzipHandler changes the "API Bytes" to "Network Bytes", which there's no Servlet API for
 * Chunked Transfer-Encoding uses more bytes on the network then the API shows
 * Complicates using the Servlet 3.1 Async I/O featureset.

Internally, the Jetty implementation is keeping track of these numbers already in the various HttpInput, HttpOutput, and HttpConnection classes.
Writing a HttpChannel.Listener for the ServerConnector is one way to utilize these numbers at the appropriate times.
However, some of the numbers have no accessors in the Jetty API.
And the nuances of the HttpChannel.Listener events and Request / Response lifecycle (recycling for example) can complicate writing such a layer against Jetty.

I propose we add a simple API to allow developers to hook into the "Request Complete" event to get the list of byte counts for every request (even those that don't go to a context).
This simple API can also be used as a demonstration on using the HttpChannel.Listener properly.

**Comment by snago** [comment]
I would still be interested in some API for this.
Now we estimate request/response size in our application by adding up lengths of method, uri, headers, etc.
Would be nice to be able to get the correct sizes.

**Comment by gregw** [comment]
@joakime I don't understand what is being suggested here?   If applications have access to the jetty APIs, then we already provide listeners and API to get bytes written  by connection and by request/response.
If applications don't have access to the jetty APIs, then how is adding a new listener going to help?
