### ISSUE TITLE
Missing HttpChannel.Listener.onResponseTrailers(Request) 

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4956]
**Jetty version**
9.4.29

**Description**
In the process of implementing ByteCount API for Issue #4954 it was discovered that there is no **Response** equivalent for the `HttpChannel.Listener.onRequestTrailer(Request request)` method.

https://github.com/eclipse/jetty.project/blob/77c232aed8a45c818fd27232278d9f95a021095e/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L1095-L1102

We should add a `HttpChannel.Listener.onResponse(Request request)` method.

**Comment by sbordet** [comment]
@lorban can you check what's the status of this issue in Jetty 12?

**Comment by lorban** [comment]
The [12.0.x EventsHandler](https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java) has a `void onResponseTrailersComplete(Request request, HttpFields trailers)` event that should cover this.
