### ISSUE TITLE
Jetty Client sending Http/2 HEADERS Frame but not DATA Frame

### ISSUE THREAD

**Issue by vidit1578756** [eclipse/jetty.project#4958]
Jetty version : 9.4.27.v20200227
Java version: 14

Description:
[jetty-client.txt](https://github.com/eclipse/jetty.project/files/4757035/jetty-client.txt)

Hello everyone,

We are doing load testing by using jetty client to send request to HTTP/2 server.

We observed that for some requests, client is not sending DATA Frame but only sending HEADERS frame.
We have set request timeout value as 1 sec. So what happens is client sends HEADERS Frame and request times out after 1 sec but it never sends DATA Frame.

This does not happen for every request but happens intermittently.

I have attached client dump which you can look.

**Comment by sbordet** [comment]
There is nothing evidently wrong from the client dump - the client seems just idle.

A request timeout of 1 second for load testing is typically too aggressive.

I don't see any evidence that we don't send DATA frames: all `HTTP2Flusher` instances are `IDLE` and with zero entries in the queue.

I suspect you have some other problem in your load testing, perhaps the server is not responding fast enough?

**Comment by vidit1578756** [comment]
[no-data-frame.zip](https://github.com/eclipse/jetty.project/files/4757502/no-data-frame.zip)

we are sending 4K MPS to 8 server Ips. We are using jetty client round robin connection pool. We set the connections per Ip as 4 , so it will establish 32 connections acorss 8 server Ips. we customized connectionsPerDestination as ConnectionsPerIP and override the round robin connection pool to handle this.

**Attached is the Pcap showing outgoing request from Jetty client to one Server IP (out of 8)**

you can check the DATA frame missing case with filter http2.streamid==6477 in wireshark. Stream id "6477" onwards, this issue becomes prominent.

ip of jetty client is 10.233.88.157.

Server response time is within 10ms. we did not capture the response in pcap because of size issues.

Thanks,

**Comment by sbordet** [comment]
I don't see a single WINDOW_UPDATE frame in the capture you attached.

If that's the case, the client stops sending DATA frames because the flow control window is exhausted, as expected.

It could also be that the client exhausts the flow control window and because you have a too short timeout, the WINDOW_UPDATE does not arrive on the client in time.

Do you have DEBUG logs?

> we customized connectionsPerDestination as ConnectionsPerIP and override the round robin connection pool to handle this.

Can you detail why you need to do this? 
Different IP addresses will create different `Destination` objects so you should not need any customization.

**Comment by vidit1578756** [comment]
Http/2 Server sets Window size as 256MB in initial WINDOW_UPDATE. if we consider the case of flow control, We still have buffer left to send data in Session. In the dump shared also the Send Window size is larger than request content (500bytes). And stall time also showed as 0ms in log.

We needed to customize connection pool as we need to configure connections per IP not per Destination (in our deployment each Destination translates to 8 IPs).

**Comment by sbordet** [comment]
I cannot see anything wrong about Jetty from the information you sent so far.

I don't know why the DATA frames are not sent, could be that your application doesn't send them or could be a Jetty bug, could be something else (e.g. a bug in Reactor that you seem to be using).

The only other way to figure this out are DEBUG logs.

> We needed to customize connection pool as we need to configure connections per IP not per Destination (in our deployment each Destination translates to 8 IPs).

Just be aware that you can use a request _tag_ to differentiate destinations.
I'm not sure they could be applied to your case, but if so you will save unnecessary customizations.
For example: `httpClient.newRequest("host", port).tag("ip1").send(...)`.

**Comment by sbordet** [comment]
@vidit1578756 did you figure out the issue?

**Comment by vidit1578756** [comment]
Hi @sbordet ,

we found that the load testing tool (vegeta in our case) was sending DATA and HEADER frame at a delay of more than 1 second when 1K TPS is sent on 1 connection. This caused the jetty-client to time-out at our node because  it subscribes for the content but never receives it with in 1 sec.

Request timeout at jetty was 1 sec. 

Thanks,
