### ISSUE TITLE
regression: passing ;jsessionid= in URL does not return Set-Cookie with a JSESSIONID since 9.4.25.v20191220

### ISSUE THREAD

**Issue by RangerRick** [eclipse/jetty.project#4960]
**Jetty version**

9.4.25.v20191220 through 9.4.29.v20200521

**Java version**

multiple versions, recent tests on 1.8.0_201

**OS type/version**

Linux (Ubuntu 18.04)

**Description**

We embed Jetty in [OpenNMS](https://www.opennms.org/).  I recently bumped our embedded version from 9.4.18 to 9.4.29 and noticed a failure in [one of our tests](https://github.com/OpenNMS/opennms/blob/develop/smoke-test/src/test/java/org/opennms/smoketest/WebappIT.java#L107).  (When a session ID is set, we turn off caching for some URLs with [a filter](https://github.com/OpenNMS/opennms/blob/develop/opennms-webapp/src/main/java/org/opennms/web/security/JSessionIdNoCacheFilter.java).)

The expectation is that if we pass a session ID on the URL at login, it will come back to in the response as a `Set-Cookie:` header.  Our filter then sees that in the outgoing response and acts on it.

After doing a bisect of sorts, I found that the `Set-Cookie:` with a session ID is set when we use `9.4.24.v20191120` but fails when we use `9.4.25.v20191220`.

I did some looking through diffs to figure out why that may be, but nothing jumps out at me.

**Comment by janbartel** [comment]
@RangerRick just to make sure we're on the same page here: if there is a valid session id on the url, then there will never be a Set-Cookie header on the response _unless_ the session id changes during the handling of that request.

I can't reproduce a problem:  I see a jsessionid in the url, and then if the sessionid changes (eg the session was invalidated and a new one created or the session id was programmatically changed etc) then I see the Set-Cookie JSESSIONID on the outbound response. My test methodology was to use the standard test jetty webapp and disable cookies on  my browser; I then hit the http://localhost:8080/test/session/ url to create a session; then I hit http://localhost:8080/test/dump/auth/admin/info to try and access a protected resource which does a form login and generates a new sessionid; I see the Set-Cookie JSESSIONID header as expected.

I haven't yet found any code changes between 9.4.24 and 9.4.25 that could cause a problem.

Can you describe exactly your test setup and ideally capture the http dialog, and/or enable DEBUG level logging for org.eclipse.jetty.server.session ?

**Comment by RangerRick** [comment]
@janbartel It is quite possible that our filter is Doin' It Rong, and I should just be checking the session in the request some other way, but the behavior definitely did change between the two Jetty versions.

If you look at [the test](https://github.com/OpenNMS/opennms/blob/develop/smoke-test/src/test/java/org/opennms/smoketest/WebappIT.java#L107) it first makes an un-sessioned request to a deep link in our webapp, to extract the session ID.  Then it makes an entirely new request, passing that same session ID, and attempts to confirm that the `Cache-Control` header has been set by our filter.

[The filter](https://github.com/OpenNMS/opennms/blob/develop/opennms-webapp/src/main/java/org/opennms/web/security/JSessionIdNoCacheFilter.java) decides whether to add that `Cache-Control` header based on whether the response has a `Set-Cookie` header.

```
        boolean cacheControlHeaderNeeded = false;
        Collection<String> cookies = response.getHeaders("Set-Cookie");

        // check for session id in cookies
        for( String cookie : cookies) {
            if(cookie.contains(sessionIdName)){
                cacheControlHeaderNeeded = true;
                break;
            }
        }
```

Like I said, perhaps there's a better way to check for whether the request already has a session, and thus doesn't need to check the header specifically.  I didn't write the filter code, I just understand it was put in as a security measure to confirm that session IDs aren't leaked through browser caching.  Maybe it was previously a bug that Jetty was _always_ passing `Set-Cookie` in this case so it worked for us, and the recent improvements to session invalidation fixed that.

**Comment by joakime** [comment]
> perhaps there's a better way to check for whether the request already has a session, and thus doesn't need to check the header specifically.

There's an Servlet API for that.

Use `HttpServletRequest.getSession(false)` - you ask for the current session, and tell it to not create one if it doesn't exist.

See: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getSession-boolean-

Your code snippet would then be replace by 1 line ...

``` java
boolean cacheControlHeaderNeeded = request.getSession(false) != null;
```

**Comment by joakime** [comment]
Also, there is no relationship between the HTTP Response header `Set-Cookie` and the cache control headers.

The cache control headers only apply to the body content of the response.
The `Set-Cookie` response header is not part of the body.

However, if you have URL based Session IDs then caching a response is a no-no, as the response body contains session specific content (namely URLs with session ids in them).

**Comment by joakime** [comment]
One more note, while the Servlet spec has the ability to have Session IDs in URLs.
This is in practice a bad idea.

It leads to the OWASP defined Session Fixation attacks (a whole category of vulnerabilities)
https://owasp.org/www-community/attacks/Session_fixation

3 specific vulnerabilities defined under the umbrella for Session Fixation are also
part of the Top 10 vulnerabilities list.
https://owasp.org/www-project-top-ten/

**Comment by janbartel** [comment]
@RangerRick I've had a look at your filter, but I'm still not clear on the exact sequence of what is happening. The description of when you're expecting a Set-Cookie with the session id in it is at odds with what I see in our tests. 

Can you run your test but with jetty DEBUG log level for "org.eclipse.jetty.server.session" package and post it please?

**Comment by RangerRick** [comment]
Yeah, I honestly don't know how it would have changed (nor why the test was written in that specific way), only that it failed if I switched out dependencies and passed if I went back to 9.4.24 or older.

That said, I've gone ahead and changed the implementation to check `request.getSession(false)` and everything behaves as expected; I think the only real point of the test was to make sure that URL-based sessions would be "upgraded" so as long as the session shows in the request, it should be all we need.  I'm cool with just closing this as "don't do that."  :D

**Comment by janbartel** [comment]
@RangerRick ok, I'll take you at your word - I'm closing the issue, so "don't do that" :)
