### ISSUE TITLE
Review OSGI version rules in enforcer plugin

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#4962]
**Jetty version**
11.0.0-alpha0

**Description**
Investigate why the version enforcer rules didn't reject `11.0.0-alpha0` for violating the OSGi version rules during the release process.
The "-" (dash char) is not allowed in the 3rd section per OSGi rules (it's only allowed for the 4th section)

**Comment by joakime** [comment]
A proper version string should have been using only "." (dot) resulting in `11.0.0.alpha0` as a valid string that OSGi likes.

**Comment by olamy** [comment]
I did some tests and the enforcer rule is definitely working.
I don't remember what I did exactly during the release of `11.0.0-alpha0`... maybe something failed  and I wanted to do a quick deployed and I skipped few things such enforcer etc...
