### ISSUE TITLE
WINDOW_UPDATE for locally failed stream should not close the HTTP/2 session

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4965]
**Jetty version**
9.4.30

**Description**
A stream is sending content to the server.

If the content is large, it is possible that some content is sent to the server, but too slowly so that the stream is failed on the client due to e.g. total timeout and removed from the session (and sending a RST_STREAM to the server).

The server consumes the content and sends back a WINDOW_UPDATE to the client.

When the WINDOW_UPDATE arrives on the client, it does not find the correspondent stream, and that causes a session failure, which kills all other streams on that session.

Care must be taken at handling the WINDOW_UPDATE, because the specification mandates that a WINDOW_UPDATE for an IDLE stream must be treated as a session error (section 5.1).

**Comment by janbartel** [comment]
@sbordet what kind of session is this? Http2? Can you update the title of the issue to be more specific?

**Comment by sbordet** [comment]
Fixed.
