### ISSUE TITLE
Default ExcludeCipherSuites in SslContextFactory causing HTTPS requests to fail with ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by annorax** [eclipse/jetty.project#497]
I upgraded from 9.3.7.v20160115 to 9.3.8.v20160314 and suddenly almost all my https requests were failing with ERR_SSL_PROTOCOL_ERROR on both Chrome and Firefox.

Reverted and all was working. Eventually I pinned it down to a change in the default bundled config file `jetty-ssl-context.xml` - in 9.3.8.v20160314 you removed a config entry that overrides the hard-coded default ExcludeCipherSuites with something else.

I went deeper, and it turns out that this config entry was only masking the issue. The commit that actually introduced the issue was https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb, which modified the hard-coded default ExcludeCipherSuites in SslContextFactory in order to mitigate SLOTH vulnerability.

The outcome of said commit is that instead of using AES_256_CBC with HMAC-SHA1 message authentication (when ExcludeCipherSuites is emptied) jetty is now inclined to use AES_128_GCM *without* HMAC-SHA1 message authentication (due to the new ExcludeCipherSuites list inttroduced in https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb). This causes most requests to fail (I'm not sure why).

The workaround I'm currently using is setting ExcludeCipherSuites to an empty list, but that is of course far from ideal.

**Comment by gregw** [comment]
Running the 9.3.8 on JRE 1.8.0_40  with a default SslContextFactory I get the follow protocols and ciphers:
````
[TLSv1, TLSv1.1, TLSv1.2]
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
TLS_ECDH_ECDSA_WITH_RC4_128_SHA
TLS_EMPTY_RENEGOTIATION_INFO_SCSV
````

Do you get similar (this is reported by org.eclipse.jetty.util.ssl.SslContextFactoryTest.testSLOTH()) ?

Which exact cipher are you having an issue with?  which cipher do you think should be in the list that is not?

**Comment by gregw** [comment]
... and to do as I say.... after updating my dev environment to 1.8.0_u77 I get:
````
[TLSv1, TLSv1.1, TLSv1.2]
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
TLS_EMPTY_RENEGOTIATION_INFO_SCSV
````

**Comment by laeubi** [comment]
Wouldn't it be a way of migration to keep the defaults in the Major-Version (or at least Minor Version!) and just add a warning log-output about insecure cipher suites? That way one would be able to set it manually if desired and will be warned that the default changes in the next version.
I think most people would not exspect a semantic change in a micro version release that breaks existing code!

**Comment by joakime** [comment]
We have to air on the side of security, and if you look at your Jetty 9.3.8 [jetty-ssl-context.xml](https://github.com/eclipse/jetty.project/blob/jetty-9.3.8.v20160314/jetty-server/src/main/config/etc/jetty-ssl-context.xml#L20-L22) you'll see the following comment ...

> To configure Includes / Excludes for Cipher Suites or Protocols see tweak-ssl.xml example at 
> https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html#configuring-sslcontextfactory-cipherSuites

That shows you how to setup a `${jetty.base}/etc/tweak-ssl.xml` that you can tweak to make your specific environment less secure.  

Note: a future release of the Java JVM will also likely mark all SHA-0 (aka SHA), SHA-1, and MD5 as insecure when used in combination with RSA. (There are many Ciphers and Protocols disabled in the JVM now as insecure)

Also note: The future of the open web is in the current specs, and if you look at the TLS spec updates (even for 1.0 and 1.1!) and the HTTP/2 spec, you'll see a blacklists for insecure protocols and ciphers.  These lists are not static and continue to evolve as new vulnerabilities are discovered.   The HTTP/2 & TLS/1.2 protocol specs even have language that we (as a server or client) MUST reject all protocols and ciphers on these blacklists.

We release based on published specs and industry recommendations, but also allow you to undo these configurations.

**Comment by annorax** [comment]
@gregw - I'm running OpenJDK 1.8.0_u72 on Ubuntu, and my cipher list contains your and adds some ciphers to it (this is the default config):
```
[TLSv1, TLSv1.1, TLSv1.2]
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
TLS_DHE_DSS_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
TLS_EMPTY_RENEGOTIATION_INFO_SCSV
```

**Comment by annorax** [comment]
When applying my workaround (i.e. when removing the filters that were updated in https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb), the following cipher suites are added to the list:

```
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
SSL_RSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
```

**Comment by annorax** [comment]
I just tried to filter out all AES_128 ciphers, on top of what's filtered out under the default configuration. That leaves plenty of ciphers in the list, but strangely now *all TLS requests fail* with the error net::ERR_CONNECTION_CLOSED appearing in Chrome's console.

Why won't HTTPS work with anything but TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA? Could it have something to do with my certificate? Could it be somehow restricted to a specific cipher suite or a handful of them?

**Comment by annorax** [comment]
I figured out the ERR_SSL_PROTOCOL_ERROR issue and it had nothing to do with Jetty after all. 

Apparently my JDK installation (OpenJDK 8 backport for Ubuntu 14.04) contains providers for some of the cipher suites that it lists as "supported" (namely the ones blacklisted by Jetty) while lacking encryption providers for others (namely the ones *not* blacklisted Jetty). I'm just lucky that way.

I addressed this by (dynamically) [installing the bouncy castle provider](http://www.bouncycastle.org/wiki/display/JA1/Provider+Installation) during the servlet's init, and now all is well even while running Jetty's default cipher filter.

**Comment by ksperling** [comment]
The change in 0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb seems dubious to me in terms of actually doing anything to prevent the SLOTH attack (Just commented on this at https://bugs.eclipse.org/bugs/show_bug.cgi?id=485714 but apparently that bug tracker is no longer actively used).

Quoting from http://www.mitls.org/pages/attacks/SLOTH: "**Note the signature algorithm is not related to the chosen ciphersuite**"

The signature algorithms to which SLOTH relates are communicated in the TLS 1.2 "signature_algorithms" extension in the ClientHello message, and are independent of the cipher suites. 

So unless I'm completely mistaken, the addition of `^.*_RSA_.*_(MD5|SHA|SHA1)$` to the excluded cipher suites has no impact on the SLOTH vulnerability. The correct way to address is by upgrading the JRE (http://www.oracle.com/technetwork/java/javase/8all-relnotes-2226344.html JDK-8144773), or possible by adding `MD5withRSA` to `jdk.tls.disabledAlgorithms`, but I'm not sure that's something Jetty should do by default.

What the change does seem to do is prevent various clients from connecting (in my case any pre 5.0 Android clients). Could you please review if the exclusion of all RSA+MD5/SHA1 cipher suites is really appropriate, especially if a list of ciphers to use has been configured explicitly.

**Comment by joakime** [comment]
@ksperling the SSLContextFactory operates in Excludes wins over Includes.

If you explicitly configure the specific cipher suites you want, then you'll want to **also** configure the excludes to be what you want them to be.

**Comment by ksperling** [comment]
@joakime yes, that's what I'm doing at the moment, even though it's turned into a bit of a hacky workaround (I'm using Jetty embedded via spring-boot, and it passes through configuration into includedCipherSuits but leaves the excluded ones untouched. Maybe that can be addressed on their end.)

I do think default-excluding all SHA/SHA1 suites is somewhat over the top, especially if SLOTH is the justification.
