### ISSUE TITLE
Jetty HTTP/2 should not send Transfer-Encoding

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#4970]
As you folks know, I have built a Jetty server, that I connect to with HTTP/2. As you folks know I have had a few problems with this (one big one). The problem was that the Jetty server was sending back a header with 'Transfer-Encoding' in it. This made Chrome (but only Chrome) very mad and caused all sorts of errors. I resolved this problem, but not sending the 'Transfer-Encoding' header back to the Browser client. This worked like a charm. 

However, the problem came back. Now it appears that Jetty is sending back a header with 'transfer-encoding' in it. Note the case change. My code only detected the first case, not the second. So a failure occurred. 

Of course, I don't really know where the 'transfer-encoding' header actually came from (originally). Perhaps it was Jetty, perhaps not. In any case, I thought I should notify you folks.

**Comment by sbordet** [comment]
Do you have a network trace, or debug logs, or something we look at?

**Comment by joakime** [comment]
This was opened before as Issue #3904 and refined in Issue #3956, which resulted in PR #4069, which was fixed in Jetty release version 9.4.21.v20190926

**Comment by pschaeffer** [comment]
I am sending two files which show the problem. However, I think joakime is correct. The problem was (apparently) fixed in a later release of Jetty (9.4.21?). This would make sense because I am running 9.4.18.

**Comment by pschaeffer** [comment]
<img width="524" alt="Capture" src="https://user-images.githubusercontent.com/3717450/84773058-77a32f00-afa1-11ea-8ebd-9abc5837ce6f.PNG">

**Comment by pschaeffer** [comment]
[chrome-net-export-log.zip](https://github.com/eclipse/jetty.project/files/4786513/chrome-net-export-log.zip)

**Comment by pschaeffer** [comment]
Thanks folks. I do have one additional comment/observation/question. Jetty has an API called "getHeader" for requests. The API takes a Java string as a header name. Is the API case insensitive? My reading of the standards is that HTTP header names are meant to be case insensitive. Is this true? Does Jetty follow this standard? I tried to figure this out from the source code and failed.

**Comment by sbordet** [comment]
> My reading of the standards is that HTTP header names are meant to be case insensitive. Is this true? Does Jetty follow this standard?

Yes and yes.

**Comment by sbordet** [comment]
Can we close the issue, since it's fixed?

**Comment by joakime** [comment]
> I am sending two files which show the problem. However, I think joakime is correct. The problem was (apparently) fixed in a later release of Jetty (9.4.21?). This would make sense because I am running 9.4.18.

9.4.18 is subject to several security notices (Many of which are HTTP/2 specific)
https://www.eclipse.org/jetty/security-reports.html

Jetty 9.4.30.v20200611 was just released (btw), if you are upgrading, go to that version.

**Comment by joakime** [comment]
Closing as this is a duplicate report for issue #3904
