### ISSUE TITLE
Why use HttpClient with the HTTP/2 transport instead of Http2Client

### ISSUE THREAD

**Issue by SushmaReddyLoka** [eclipse/jetty.project#4973]
https://github.com/eclipse/jetty.project/issues/4653 , in this post its suggested to use HttpClient by using http/2 transport, any reason for using it this way instead of Http2Client ?

**Comment by sbordet** [comment]
`HTTP2Client` is very low level and deals with HTTP/2 details such as frames and streams and sessions.

`HttpClient` deals with high level HTTP semantic - `GET`s, `POST`s, parameters, request and response content, redirects, connection pooling, authentication, proxying, etc.
