### ISSUE TITLE
HttpClient async content throws NPE in DEBUG log 

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#4976]
**Jetty version**
9.4.30

**Description**
Similar to #4082.

The problem happens when `parser.parseNext()` returns `true` due to the application processing the content asynchronously.

When `true` is returned, another thread is scheduled to resume the fill+parse, which may fill `0` and null out the `networkBuffer` field.

The original thread now tries to access the `networkBuffer` field in the DEBUG log and the NPE is thrown.

**Comment by shamsimam** [comment]
The NPE can also be thrown when debug logging is disabled from https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java#L185
