### ISSUE TITLE
How Can I Get the Thread Name

### ISSUE THREAD

**Issue by pschaeffer** [eclipse/jetty.project#4979]
The Jetty log (my log) has entries like 
2020-06-18 03:41:21,578 [qtp1095352419-126] INFO  com.headlamp.HDLmJetty  - HandleProxy() Request Original URI - /
in it.
Does Jetty have an API where I can get the qtp1095352419 string? What is this string properly called? Is this a request property? A response property?
Thank you
Peter Schaeffer

**Comment by lachlan-roberts** [comment]
This is just the name of the `ThreadPool`, the "qtp" part is short for Jetty's `QueuedThreadPool`.
You can even just configure the name yourself to whatever you want.

If you're using embedded just set your named thread pool on the `Server`, otherwise you can can do the same through XML configuration.

**Comment by joakime** [comment]
For embedded Jetty it would look like this ...

``` java
        QueuedThreadPool serverExecutor = new QueuedThreadPool();
        serverExecutor.setName("server");
        server = new Server(serverExecutor);
```

**Comment by pschaeffer** [comment]
Thanks folks,
I appreciate that the 'qtp1095352419' part is really just the thread pool name and that I could get it and set it. Apparently, 'qtp' is a default prefix derived from 'Queued Thread Pool' which makes sense. What I am trying to get (find a way to obtain) is actually the full 'qtp1095352419-126' name or perhaps just the '126' suffix. My guess is that the '126' suffix somehow identifies the thread in the thread pool that generated the log request. Of course, I am not sure that the '126' suffix means what I think it means. I have noticed that the suffix is not constant over time. I see values like 'main' (during startup), '17', '15', '33', etc. in the log. 
Thank you
Peter Schaeffer

**Comment by sbordet** [comment]
@pschaeffer you get the thread name via `Thread.getName()`.

`126` is the thread ID, from `Thread.getId()`.

**Comment by joakime** [comment]
Each "name" you see in the logs (it's actually more like what sbordet says `${thread.name}-${thread.id}`) represents a unique thread that is producing that log entry.

Said another way ... `qtp1095352419-126` can be broken down like this ...

`qtp` is the prefix that a default configuration of `QueuedThreadPool` defines.
the `1095352419` is the unique identity hashcode() for the `QueuedThreadPool` and remains the same value for the lifetime of that `QueuedThreadPool` (which is typically the same as the lifetime of the JVM).
These 2 values are what becomes the [`Thread.getName()`](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#getName--)

You can see the default prefix + hashcode default value set in code like this ...
https://github.com/eclipse/jetty.project/blob/jetty-9.4.30.v20200611/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L72
https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L72

the `-126` is the suffix added to the thread identifying a specific thread.id being tracked by the `QueuedThreadPool`, it is assigned by the JVM and we are not in control of it.
See [`Thread.getId()`](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#getId--) for what it means.

**Comment by pschaeffer** [comment]
Thank you folks.
All of my questions have been answered.
