### ISSUE TITLE
is there any way to give weight to each connection, so that load is distributed between multiple connection as per there weight.

### ISSUE THREAD

**Issue by navalgoyal** [eclipse/jetty.project#4983]
**Jetty version**
9.4.24

**Java version**
Java 1.8

**Question**
I want to create multiple connection between Jetty Client and HTTP Server. Each Connection have own weight. These connections will work as load balancer. Each connection has there own weight. Request will send based on there weight. The Connection having maximum weight will serve maximum request. For Example for there are 2 connection with weight 80 and 20 than 80% request would go to connection 1 where 20 would go to other connection.

is there any way to achieve this behavior using Jetty Client??

**Comment by sbordet** [comment]
I'm not sure it makes much sense.

`request1` will be assigned to `connection1` which has weight 80. `request1` takes a lot of time to be processed.

While request1 is being processed, `request2` to `request100` are sent, and they cannot use `connection1`, so they will end up in `connection2`.
`request2` to `request100` are quick to be processed and all finish before `request1` is finished.

Now you have a case where the connection with weight 20 has processed 99 request, while the one with weight 80 has processed only 1.

**Comment by janbartel** [comment]
@navalgoyal if your question has been answered, please close this issue.
