### ISSUE TITLE
Why Http/2 Client mandate use of ALPN

### ISSUE THREAD

**Issue by SushmaReddyLoka** [eclipse/jetty.project#4984]
https://stackoverflow.com/questions/34823433/does-apache-or-some-other-client-java-implementation-support-http-2, here it is mentioned that 

"Jetty's provides two HTTP/2 Java client APIs. Both require Java 8 and the mandatory use of the ALPN, as explained here." ,
 But why would we need ALPN always ? Will it be needed even on clear text TCP ?

**Comment by sbordet** [comment]
ALPN is not needed for clear-text HTTP/2.

**Comment by sbordet** [comment]
Closing as answered.
