### ISSUE TITLE
How to 'unwrap the ServletContext facade until we reach Jetty's ContextHandler'?

### ISSUE THREAD

**Issue by ManuelMall** [eclipse/jetty.project#4986]
**Question**
We are running Jetty within Equinox as OSGi HttpServer. Trying to serve some static content (outside of our OSGi bundles). Defined the required extension

```
   <extension
         point="org.eclipse.equinox.http.registry.servlets">
      <servlet
            alias="/something"
            class="org.eclipse.jetty.servlet.DefaultServlet"
            load-on-startup="true">
         <init-param
               name="dirAllowed"
               value="true">
         </init-param>
         <init-param
               name="resourceBase"
               value="...">
         </init-param>
      </servlet>
   </extension>
```
And getting the error

```
java.lang.IllegalArgumentException: The servletContext ServletContext@o.e.j.s.ServletContextHandler@1da05852{/,null,AVAILABLE} com.sun.proxy.$Proxy68 is not org.eclipse.jetty.server.handler.ContextHandler$Context
	at org.eclipse.jetty.servlet.DefaultServlet.initContextHandler(DefaultServlet.java:365)
	at org.eclipse.jetty.servlet.DefaultServlet.init(DefaultServlet.java:169)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.initializeDelegate(ServletManager.java:198)
```
There is a Jacdoc note on the `initContextHandler` method saying

```
     * In the case where the DefaultServlet is deployed on the HttpService it is likely that
     * this method needs to be overwritten to unwrap the ServletContext facade until we reach
     * the original jetty's ContextHandler.
```

I tried to do that but really struggle how to 'unwrap' the `Proxy` object created by the Equinox runtime for the `ServletContext`.
Looking for any suggestions how to do that?

Thanks

**Comment by janbartel** [comment]
@ManuelMall I think you might have to ask someone with a lot more Equinox experience, maybe @guw might be able to help?

It seems to me that the exception you're seeing indicates that the Proxy does not implement ContextHandler.Context, just javax.servlet.ServletContext, so there might not be a way to recover a ContextHandler.Context.

I found this post: https://stackoverflow.com/questions/11826853/setting-custom-response-headers-for-static-resources-served-in-osgi-environment  which kind of implies that there may also be more difficulties to also overcome.

**Comment by ManuelMall** [comment]
@janbartel Thanks for your response. Found a solution that works but it is very ugly as it depends on the implementation details of the ServletContext proxy object constructed by Equinox and requires a three deep nested forced field access using Java reflection. One would have hoped it to be is easier to serve static content.

```java
public class StaticContentServlet extends DefaultServlet {

  private static final Logger LOG = LoggerFactory.getLogger(StaticContentServlet.class);

  @Override
  protected ContextHandler initContextHandler(final ServletContext servletContext) {
    final ContextHandler.Context scontext = ContextHandler.getCurrentContext();
    if (scontext == null) {
      if (servletContext instanceof Proxy) {
        // This is very ugly and relies on the details of the underlying implementation,
        // but somehow we need to get to the Jetty provided servlet context. 
        try {
          final InvocationHandler ih = Proxy.getInvocationHandler(servletContext);
          final Object superClass = FieldUtils.readField(ih, "this$0", true);
          final Object proxyContext = FieldUtils.readField(superClass, "proxyContext", true);
          final Object servletCtx = FieldUtils.readField(proxyContext, "servletContext", true);
          if (servletCtx instanceof ServletContext) {
            return super.initContextHandler((ServletContext)servletCtx);
          }
        } catch (SecurityException | IllegalArgumentException | IllegalAccessException e) {
          LOG.error("Problem unwrapping " + servletContext, e);
        }
      }
    }
    return super.initContextHandler(servletContext);
  }
}
```

**Comment by guw** [comment]
@ManuelMall The code looks odd. It's missing an:
```
        else
            return ContextHandler.getCurrentContext().getContextHandler();
```

I also wonder why the context would be null. Does the Equinox HttpService spawn threads?

You may also want to submit a PR to Equinox to make unwrapping easier. AFAIK there should be only one context in the Jetty based Equinox HttpService implementation, you could also try grabbing it with a JettyCustomizer.

**Comment by ManuelMall** [comment]
@guw The missing `else` bit is handled in the super class method invocation. And yes, `ContextHandler.getCurrentContext()` is returning `null`. And also yes to the separate thread. AFAICT from the stack trace there is no Jetty class involved at all. I will have a look at the JettyCustomiser suggestion and a PR for Equinox. Thanks

**Comment by janbartel** [comment]
@ManuelMall I think the standard Equinox stuff comes with the ability to serve static content, but I'm not sure how sophisticated it is.

**Comment by ManuelMall** [comment]
@janbartel As far as I understand the built-in mechanisms can only serve content from within OSGi bundles, not external content. External content needs some form of customisation, e.g. a custom HttpContext I saw suggested somewhere.
