### ISSUE TITLE
Make FilterMapping more sophisticated 

### ISSUE THREAD

**Issue by jokyjang** [eclipse/jetty.project#4992]
**Jetty version**
all

**Java version**
all

**Question**
The current FilterMapping only supports one wildcard '\*' match (see below link). I have path something like /api/a/\*/b/\*, both wirdcards in this case are path parameters. Is there anyway I can do that?

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/FilterMapping.java#L141

**Comment by joakime** [comment]
The reason for this limitation is the Servlet spec.
Currently this kind of complex `url-pattern` is not supported by the Servlet spec.
Consider asking for such a feature at https://github.com/eclipse-ee4j/servlet-api

**Comment by janbartel** [comment]
@jokyjang as @joakime says, FilterMapping is constrained by the servlet specification for filter mapping patterns. Maybe you can step outside of the servlet specification and look at using or extending the jetty api to accomplish what you would like to do.
