### ISSUE TITLE
Jett HTTP Client timing out even after receving response from server

### ISSUE THREAD

**Issue by kiranmaiem** [eclipse/jetty.project#4993]
**9.4.30 HTTP Client**

**Open JDK 14**

**Linux**

**We have a Spring web flux application where it receives a HTTP2 request and send out to other hop using Jetty HTTP2 Client.
Under 100 TPS load, some of the requests are timing out at Jetty client, complaining that it did not receive response from server.
We captured the network traces and confirmed that server is sending response within few milli seconds but jetty timing out the request after 5 seconds ( we set the request time out as 5 sec)

Attached are logs and Pcap file related to the issue.

Request with URI "npcf-smpolicycontrol/v1/sm-policies/87dd349f-0f9b-4740-b3ab-e0ba8418dca5/update" has this issue. Log file can be searched for this string.

In Pcap file "http2 && tcp.port == 43602 && http2.streamid == 1835" filter will show the request and response between Jetty client and server **
[pcf-perf-1.7.2.zip](https://github.com/eclipse/jetty.project/files/4823231/pcf-perf-1.7.2.zip)

**Comment by sbordet** [comment]
Unfortunately there is not enough logging to understand what's going on.
The pcap looks fine from the framing point of view - the body is 2 empty JSON objects.
Flow control windows are not exhausted.

Could be that your client just ran out of threads and no threads were available for those 5 seconds, so the request timed out.

Can you please enable DEBUG logging for `org.eclipse.jetty`?

**Comment by kiranmaiem** [comment]
we have enabled DEBUG level at jetty package and the log file i have attached has the jetty DEBUG logs. Can you let me know what more need to enabled to capture logs?

**Comment by sbordet** [comment]
The attached log file does not have DEBUG enabled for `org.eclipse.jetty`, but for something else called `ocpm.cne.gateway.jettyclient.*` which is not enough to understand whether there is a problem in Jetty.

From what I can tell from the logs, no Jetty code is actually running - only something else that looks like Jetty but it's on a different package and could be totally different source code.

Will also be great if you can avoid logs in JSON - pretty unreadable.

**Comment by kiranmaiem** [comment]
ok i will recheck the log levels and remove json formatting of log messages. Will upload the logs again.
