### ISSUE TITLE
Callback notification when a connection is opened / closed in HTTPClient 

### ISSUE THREAD

**Issue by Arshiya95** [eclipse/jetty.project#4995]
**Jetty version**
9.4.19.v20190610

**Java version**
1.8

**Question**
Is it possible to get callback notification when a connection is opened / closed in HTTPClient ?

**Comment by sbordet** [comment]
>  Is it possible to get callback notification when a connection is opened / closed in HTTPClient ?

Yes, like that:

```java
httpClient.addBean(new org.eclipse.jetty.io.Connection.Listener() {
  public void onOpened(org.eclipse.jetty.io.Connection connection) {
  }
  public void onClosed(org.eclipse.jetty.io.Connection connection) {
  }
});
```

**Comment by sbordet** [comment]
Closing as answered.
