### ISSUE TITLE
 Warning log printed when debug is enabled in AbstractLifecycle.java

### ISSUE THREAD

**Issue by Arshiya95** [eclipse/jetty.project#4996]
**Jetty version**
jetty-util-9.4.30.v20200611

**Java version**
1.8

**OS type/version**
Linux

**Description**
Under class org.eclipse.jetty.util.component.AbstractLifecycle.java setFailed(), there is a warning log printed when debug is enabled:

        if(LOG.isDebugEnabled())
            LOG.warn((new StringBuilder()).append("FAILED ").append(this).append(": ").append(th).toString(), th);

**Comment by joakime** [comment]
This is not the only place we do this behavior.

The line of code mentioned by the OP

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java#L230-L234

Other places were do this too.

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationParser.java#L867-L868

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L593-L594

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L489-L490

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L338-L339

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java#L840-L844

https://github.com/eclipse/jetty.project/blob/1b59672b7f668b8a421690154b98b4b2b03f254b/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java#L877-L881

**Comment by joakime** [comment]
Most of the cases I found are not really a bug / issue.
But we should review them anyway, as some things have changed over the years.
An example would be when the developer separated the message and the throwable (like in the ServletHolder).
That's no longer needed (and can produce throwables far away from the message in the actual log output)

**Comment by janbartel** [comment]
The work in progress is being done on jetty-10.0.x, as any changes to the logging are too hard to port forward.
