### ISSUE TITLE
Jetty thread hung on TCP port

### ISSUE THREAD

**Issue by hitenny** [eclipse/jetty.project#4998]
We are using embedded Jetty server version `9.4.6.v20170531` in our Java server. When we run WebSocket tests using JMeter, the server hangs when it reaches 4000 websocket connections.

`QueuedThreadPool configuration maxThreads = 100`

Upon checking process, it was stuck; ie the websocket port was not responding. Server was unable to process data from the port. There were items in the TCP recv Q. 
jstack is attached

[Jetty-hang-jstack.txt](https://github.com/eclipse/jetty.project/files/4827231/Jetty-hang-jstack.txt)

**Comment by sbordet** [comment]
All the Jetty threads in the stack dump are idle in the `QueuedThreadPool`, so the dump shows that Jetty was completely idle as if no connection was made to it.

It is likely that your client cannot keep up with the load test - happens almost all the times. 

There is a thread handling an accept failure, so you may have more information in the server logs - could be that your server is underconfigured and ran out of file descriptors.

**Comment by joakime** [comment]
Not sure how you expect to handle 4000 concurrent websocket connections with a maxThreads of 100.

Also, upgrade to a more recent version of Jetty.
9.4.6.v20170531 is old and subject to several security issues now.
https://www.eclipse.org/jetty/security-reports.html

Consider using version 9.4.30.v20200611 has MANY improvements, including WebSocket.

**Comment by hitenny** [comment]
@sbordet I think the client getting stuck is out of question here. Once the issue is reproduced, I checked the websocket port using `telnet` and it was not responding. Health check from Loadbalancer to the TCP port failed which means port is hung. recvQ having non-zero items shows that server is not receiving. All these data point that the server is at problem.

@joakime I saw your note in SO that 100 threads could handle upto 40000 connections. We are talking about 1/10th of it.

**Comment by sbordet** [comment]
@hitenny as I said, there is evidence that there is an accepting error on the server.

That does not mean it's a Jetty issue - could just be the server OS being misconfigured.

Please post the server logs - there should be evidence of the accepting error.

**Comment by joakime** [comment]
> @joakime I saw your note in SO that 100 threads could handle upto 40000 connections. We are talking about 1/10th of it.

I don't recall making that kind of statement.
Those kinds of numbers would only apply to Servlets that exclusively use Async I/O. (it would never apply to Websocket)

I'm happy that you did your research first, and I'm quite active on Stackoverflow.
But here's an example of the kind of statement i've made about Threads and tuning on Stackoverflow.
https://stackoverflow.com/questions/44046685/jetty-where-are-my-five-threads

**Comment by hitenny** [comment]
@sbordet By OS misconfiguration do you mean not enough file handles? But in that case I should start getting errors instead of service being stuck. 

@joakime Here is the link I referred where you answered about threads. https://stackoverflow.com/questions/29307949/determine-maximum-websockets-jetty-will-open

If that's wrong, on what basis I should choose thread pool size.

**Comment by joakime** [comment]
I updated that 5 year old answer. (which was based on a version of Jetty 3 major versions ago, a version that is now EOL).

Thread Pool Max Size is based on many factors.
The answer at https://stackoverflow.com/questions/44046685/jetty-where-are-my-five-threads covers the basics, the high level.

The best way to figure out your sizing needs is ...
1) Start with default values
2) Monitor the Thread usage via JMX using something like jmc or jconsole (comes with JVM)
  This means monitoring the Thread usage at the JVM level, and even using the QueuedThreadPool specific values (in JMX) for seeing details on how well the QueuedThreadPool is performing (there's lots of values, look for things like the queue size or idle thread count as a starting point)
3) Test the entirety of your application, all features, all kinds of usages. (as different technology choices and libraries will have an impact on your thread usage)
4) The thread usage you see in JMX tells you the truth about your application for the level of testing you just did.
5) Now do it again, but with a load testing scenario (make sure it's a valid load test that uses multiple clients from different machines and tests a majority of your application. not 1 client, or on the same computer, or against a small handful of endpoints).
6) This load test will show you what you threading demands are under load.  That's another data point.
7) After you have these values, do the math on what you expect is normal.
8) Continue to monitor your OS and JVM resources (memory, cpu, filesystem, I/O, threads, GarbageCollection, etc) in production, as you will likely have to adjust them over time.

This is how every devops group figures out how to size their resources now and in the future.
Guessing at it, without real usage numbers, almost always winds up with wrong values that impacts behavior, stability, and performance (especially it the change is to reduce the default values!).

**Comment by sbordet** [comment]
> By OS misconfiguration do you mean not enough file handles? But in that case I should start getting errors instead of service being stuck.

How would we know? We asked multiple times for the server logs, but nothing so far.
We need evidence, otherwise we cannot help you.

**Comment by sbordet** [comment]
Closing as no further information was provided.
