### ISSUE TITLE
[jetty-osgi] Upgrade to at least OSGi R4.3

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#500]
Jetty requires Java 8 so there should be no real impact on upgrading to OSGi R4.3 that supports generics.

Also 4.3 adds some new ways to introspect wirings between bundles in a standard way.

**Comment by laeubi** [comment]
This would require Equinox 3.7.1 and org.eclipse.osgi.services 3.3.0.v20110513 but this seems not to be avaiable in the maven repros... an alternative seems to not use eclipse.services but the compendium jars.

Any comments?

**Comment by laeubi** [comment]
Okay it seems atleast Equinox 3.8 is needed due to a bug with the jar (see for example http://stackoverflow.com/questions/13926960/code-compiles-in-eclipse-but-not-through-command-prompt/13928948) that is also not avaiable ...

**Comment by joakime** [comment]
Jetty 9.4.x is on OSGi 3.6.0

https://github.com/eclipse/jetty.project/blob/7bc5e6e33a92fe1e07ced9239f517e10d9e5410d/jetty-osgi/pom.xml#L17-L24

And 3.7.1 exists on maven central ...

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.osgi%22%20AND%20a%3A%22org.eclipse.osgi%22

Closing as unable to upgrade to 4.3 due to unavailable/missing dependencies.

**Comment by laeubi** [comment]
The purpose of this ticket is to upgrade the jetty-module so why is it closed with a comment that jetty uses an older version... I'm confused!

**Comment by joakime** [comment]
Where can we find OSGi 4.3 (on maven central)? - its been a year, only 3.7 is available.

Feel free to submit a PR to make this upgrade happen.

**Comment by laeubi** [comment]
Okay, to clear this a bit: Even though the property is named OSGi version it is in fact the Equinox version!
The different versions can be found here: https://mvnrepository.com/artifact/org.eclipse.tycho/org.eclipse.osgi
We would need at least Equinix 3.8.x (what implements OSGi R4.3)

**Comment by laeubi** [comment]
I'll try to provide a PR in the next weeks...

**Comment by joakime** [comment]
Do not use mvnrepository.com its a known source of misleading (referencing content that exist at repositories that are not central.maven.org) and incorrect information (it often has artifacts and versions that are either not present on central.maven.org or not present on mvnrepository.com).

The official http://search.maven.org is canonical source for content on entire central maven repository network.

Your search: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.tycho%22%20AND%20a%3A%22org.eclipse.osgi%22

**Comment by joakime** [comment]
Note: we do not reference tycho as dependency, as we run on many osgi containers.

https://github.com/eclipse/jetty.project/search?utf8=%E2%9C%93&q=tycho&type=

So keep the PR non-tycho specific please.

**Comment by janbartel** [comment]
@laeubi  in your PR, it would be fine to change jetty-osgi pom.xml to use a different osgi api provider -doesn't have to be eclipse -  that has support for more recent osgi api version.  However, we would also need to change away from the use of equinox for the test-jetty-osgi pom.xml.  These equinox jars are updated very seldom in maven central, so going for a different provider is probably a good idea. I had a bit of a try with using felix container for the tests instead, but a whole rash of new issues popped up - but feel free to use a different container in your PR.

**Comment by olamy** [comment]
@laeubi still interested by this?

**Comment by laeubi** [comment]
@olamy If jetty still uses this old API of course this is still valid.

**Comment by joakime** [comment]
Looks like Eclipse OSGi Services is on a different maven coordinate now.

See: https://search.maven.org/artifact/org.eclipse.platform/org.eclipse.osgi.services  (for Eclipse OSGi Services 4.2.0)

**Comment by joakime** [comment]
I cannot find a version of the eclipse osgi services for 4.3 on maven central.

If the dependency isn't on maven central, we cannot use it.

_Even if a P2 repository exists on eclipse.org._

**Comment by joakime** [comment]
Probably something we should upgrade for Jetty 10 or Jetty 11.
