### ISSUE TITLE
NPE from Server.dump of FilterMapping

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5000]
**Jetty version**
9.4.30

**OS**
Jetty on Docker

**Description**
Not sure how to replicate (yet).

This occurs deep within a `Server.dump()` while attempting to list `FilterMappings`.

```
[STDOUT] |     |     |     |  |  +> Exception in thread "main" java.lang.NullPointerException 
[STDOUT] 	at org.eclipse.jetty.servlet.FilterMapping.appliesTo(FilterMapping.java:157) 
[STDOUT] 	at org.eclipse.jetty.servlet.FilterMapping.appliesTo(FilterMapping.java:163) 
[STDOUT] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) 
[STDOUT] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) 
[STDOUT] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) 
[STDOUT] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) 
[STDOUT] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) 
[STDOUT] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
[STDOUT] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) 
[STDOUT] 	at org.eclipse.jetty.servlet.FilterMapping.toString(FilterMapping.java:310) 
[STDOUT] 	at java.base/java.lang.String.valueOf(String.java:2951) 
[STDOUT] 	at org.eclipse.jetty.servlet.FilterMapping.dump(FilterMapping.java:317) 
[STDOUT] 	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:179) 
[STDOUT] 	at org.eclipse.jetty.util.component.DumpableCollection.dump(DumpableCollection.java:57) 
[STDOUT] 	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:179) 
```

**Comment by gregw** [comment]
I'm guessing we may be dumping while a filter is being added/started/stopped???

**Comment by joakime** [comment]
Looks like the NPE is from the `_holder` being null.

https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/FilterMapping.java#L154-L159

Not sure how that can be null.

Should probably add a `Objects.requireNonNull(holder);` to `.setFilterHolder(FilterHolder)` for API sanity reasons.

https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/FilterMapping.java#L255-L259

**Comment by janbartel** [comment]
That is very weird. It looks like a FilterMapping has been declared for a filter name that is not defined as a Filter anywhere. We only match up the FilterHolder to the FilterMapping in ServletHandler.doStart(), so maybe server.dump() is being called before the ServletHandler has started?  The fix is probably at line 155 in FilterMapping in appliesTo(int) method: we should check if the _holder is null.

**Comment by joakime** [comment]
Some notes about the origin of this issue (from the person that reported it to me).

The NPE occurs on a webapp ...
 * using Google Guice to register all of the Servlets and Filters via the `com.google.inject.servlet.GuiceFilter`
 * the `WEB-INF/web.xml` only has the `com.google.inject.servlet.GuiceFilter` with a mapping to `/*`
 * the Servlets and Filters have no Servlet annotations (only Guice/Inject annotations)
 * the webapp is deployed via normal `jetty-deploy` looking at a `${jetty.base}/webapps/ROOT/` (exploded war) directory.
 * there is no `${jetty.base}/webapps/ROOT.xml` deployment XML.
 * the jetty start property `jetty.server.dumpAfterStart=true` is set.

**Comment by janbartel** [comment]
Fixed.
