### ISSUE TITLE
Hot deployment of WARs on an embedded jetty server

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#5007]
**Jetty version** - 9.4.30.v20200611

**Java version** - jdk1.8.0_201

I am using the below code to deploy a war on an embedded jetty server:

        Server server = new Server();
        WebAppContext webapp = new WebAppContext();
        webapp.setContextPath("/http1");
        File warFile = new File("C:\\JettyWar\\http1.war");
        webapp.setWar(warFile.getAbsolutePath());
        server.setHandler(webapp);

        ServerConnector http2Connector = new ServerConnector(server, new HTTP2ServerConnectionFactory(http_config));
        server.addConnector(http2Connector);
        server.start();
This works fine.

**But my requirement is to deploy/undeploy multiple wars multiple times on an already running Jetty server**.
e.g. 
server.start();
WebAppContext webapp = new WebAppContext();
webapp.setContextPath("/http1");
webapp.setWar(new File("C:\\JettyWar\\http1.war").getAbsolutePath());
server.setHandler(webapp);

**Butwhen I try to add a webapp handler after server.start(), I get the below exception**:

Exception in thread "main" java.lang.IllegalStateException: STARTED
	at org.eclipse.jetty.server.handler.HandlerWrapper.setHandler(HandlerWrapper.java:77)
	at de.consol.labs.h2c.examples.server.Http2ServerWar.main(Http2ServerWar.java:72)

Is there any other way by which I can achieve this hot deployment/undeployment of multiple wars on an embedded Jetty server.

**Comment by joakime** [comment]
You need to use a Handler Tree. (a mix of Handler, HandlerWrapper, and HandlerCollection to suite your needs).

Example:

``` java
Server server = new Server();

HandlerList handlers = new HandlerList();
server.setHandler(handlers);

WebAppContext webappA = new WebAppContext();
// init webappA
handlers.addHandler(webappA);

WebAppContext webappB = new WebAppContext();
// init webappB
handlers.addHandler(webappB);

server.start();
```

But this is also direct assignment of Wars to the handler list, and does not support hot deploy of wars.

For hot deploy of webapps (wars are included in this), you need to use the DeploymentManager and a ContextHandlerCollection.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.30.v20200611/examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java
For a working example that uses a `DeploymentManager` connected to a `ContextHandlerCollection` being managed by a `WebAppProvider` that is configured to look in a specific directory for webapps to deploy.

**Comment by prateekkohli2112** [comment]
Thanks @joakime for the quick response.

Just 1 more doubt, would DeploymentManager restart already running contexts?

**Comment by joakime** [comment]
DeploymentManager is capable of moving apps through the lifecycle of start/stop/etc.
The WebAppProvider is responsible for detecting a change in the webapp and requesting the DeploymentManager to move the app through the lifecycle.

See API docs ...

* https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/deploy/DeploymentManager.html
* https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/deploy/AppLifeCycle.html

**Comment by janbartel** [comment]
@prateekkohli2112 if your question has been adequately answered, could you close the issue?

**Comment by prateekkohli2112** [comment]
Sorry for the late response.

I just wanted to ask if I redeploy 1 app using DeploymentManager, would it restart the other apps as well on that jetty instance?

**Comment by joakime** [comment]
@prateekkohli2112 hot deployment (as triggered by a filesystem change), or even manual deployment (using the DeploymentManager directly), is always on 1 app at a time.

**Comment by prateekkohli2112** [comment]
Thanks @joakime.
