### ISSUE TITLE
Bundle-ClassPath and lib place on WEB-INF/lib make classpath duplicate

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#5013]
**Jetty version**
9.4.x
**Java version**
jdk-13
**OS type/version**
linux
**Description**
deploy jetty as osgi on equinox
deploy a webapp as WebAppContext
webapp is osgi bundle with Bundle-ClassPath for a library place on WEB-INF/lib/

so that library exists on two classpath, 
one is normal Bundle-ClassPath
other is jar classpath add by bellow code on class org.eclipse.jetty.webapp.WebInfConfiguration

```java
        // Add WEB-INF classes and lib classpaths
        if (webInf != null && webInf.isDirectory() && context.getClassLoader() instanceof WebAppClassLoader)
        {
            // Look for classes directory
            Resource classes = webInf.addPath("classes/");
            if (classes.exists())
                ((WebAppClassLoader)context.getClassLoader()).addClassPath(classes);

            // Look for jars
            Resource lib = webInf.addPath("lib/");
            if (lib.exists() || lib.isDirectory())
                ((WebAppClassLoader)context.getClassLoader()).addJars(lib);
        }
```

**Comment by hieplq** [comment]
i prepare project for reproduce https://github.com/hieplq/vn.duplicate.classpath/tree/jetty-5013

**Comment by hieplq** [comment]
===  bellow is wrong report, i just not yet delete WEB-INF/lib ===
i do work-around by don't put lib inside WEB-INF, i move lib to root folder of plugin
on run time (eclipse) it's it resolve issue
but when i run binary, when jetty deploy my webapp bundle to temp folder, it move lib back to WEB-INF

**Comment by janbartel** [comment]
@hieplq I think we expect that `WEB-INF/` will just contain `classes/` for a web bundle, as any jars would be deployed as bundles within the osgi container instead. I'll have a look and make sure that we can support the scenario where the jars have been included in WEB-INF/lib instead, and/or appear on the Bundle-Classpath.

**Comment by janbartel** [comment]
Raised PR #5034.

**Comment by janbartel** [comment]
Fix merged.
