### ISSUE TITLE
IOException thrown in the handler prevents other handlers from being executed

### ISSUE THREAD

**Issue by Illapikov** [eclipse/jetty.project#5015]
**Jetty version**
9.4.29

**Java version**
11.0.3

**Question**
We have a service utilising Jetty and Spring Boot.
Everything was working fine until recently we started receiving `EofException` and `IOException` in the controller due to the clients abruptly closing the connection.
While neither` EofException` nor `IOException` being an issue to our exception handling we noticed that we are missing access log entries for requests that ended up with these exceptions.

Our logging is Logback based and we use `HandlerCollection` to add an extra logging handler.

```
    @Bean
    public JettyServerCustomizer accessLogsCustomizer() {
        return server -> {
            final HandlerCollection handlers = new HandlerCollection(server.getHandlers());

            final RequestLogImpl rli = new RequestLogImpl();
            rli.setResource("/logback-access.xml");
            rli.setQuiet(false);
            rli.start();

            final RequestLogHandler reqLogs = new RequestLogHandler();
            reqLogs.setServer(server);
            reqLogs.setRequestLog(rli);

            handlers.addHandler(reqLogs);

            server.setHandler(handlers);
        };
    }
```

So, the question being why are we missing access log entries when `IOException` is thrown?

**Comment by joakime** [comment]
Lets start with simplifying that code a bit.

``` java
    @Bean
    public JettyServerCustomizer accessLogsCustomizer() {
        return server -> {
            final RequestLogImpl rli = new RequestLogImpl();
            rli.setResource("/logback-access.xml");
            rli.setQuiet(false);
            rli.start();
            server.setRequestLog(rli);
        };
    }
```

Not relying on `RequestLogHandler` is bound to improve things (you'll get access logs for more types of requests now, even for requests that don't belong to a context).

Also note that Jetty's CustomRequestLog is on par (and in many cases better) then logback access.
Just connect the `CustomRequestLog` to the `Slf4jRequestLogWriter` and you'll have the same end result (request logs going to your logback locations).

**Comment by joakime** [comment]
The EofException, EOFException, and IOException could be caught by the springboot controller in a such a way that it doesn't let Jetty see that failure.
You are probably seeing the access log entry, but it doesn't indicate an error, as SpringBoot attempted to work around it (with varying degrees of success)

**Comment by Illapikov** [comment]
Thank you for your swift response, @joakime 

I did refactor the code as you've kindly suggested and the issue I've experienced is now gone.

I've did a small and naive source code research and found out that Spring does not wrap `IOException` (as well as `EofException` and I would assume all exceptions nested from `IOException`) with `NestedServletException`.

Therefore, `HandlerCollection` aborts handling and re-throws `IOException` in this code block:
```
            for (Handler handler : handlers._handlers)
            {
                try
                {
                    handler.handle(target, baseRequest, request, response);
                }
                catch (IOException | RuntimeException e)
                {
                    throw e;
                }
                catch (Exception e)
                {
                    if (mex == null)
                        mex = new MultiException();
                    mex.add(e);
                }
            }
```

While the mystery of a missing logs is solved there is another question I'm asking myself: what is the different between our request logs approach with a handler and your's with `server.setRequestLog(rli);`?

**Comment by janbartel** [comment]
RequestLogHandler is for use when you want different request logging for _another_ handler/context etc. Setting the RequestLog directly on the server means it will be used for all contexts/handlers.
