### ISSUE TITLE
Remove RequestLogHandler in favor of server.setRequestLog(RequestLog) in Jetty 10+

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5017]
**Jetty version**
Jetty 10.0.x

**Description**
Now that `server.setRequestLog(RequestLog)` exists and performs much better, I would like to remove the `RequestLogHandler` entirely from Jetty 10 onwards.

And possibly deprecate `RequestLogHandler` in Jetty 9.4.x as well. (pointing to `server.setRequestLog(RequestLog)` as the suggested replacement).

**Comment by joakime** [comment]
I was motivated to suggest this from the discussion on Issue #5015

**Comment by gregw** [comment]
Still needed for logging for a specific context.... but perhaps that can be solved some other way?
But not needed for 10.0.0
