### ISSUE TITLE
Cannot serve files symbolically linked in Windows

### ISSUE THREAD

**Issue by Binary-L0G1C** [eclipse/jetty.project#502]
This may be related to #261 

Using 9.3.8.v20160314
Previous (working): 9.2.15.v20160210
Code: https://github.com/Binary-L0G1C/base-spring-webapp
- this still had the working version in the pom.  You can change it to 9.3.8.v20160314

I access my project (through eclipse (IDE) or through command line) through a windows symlink.  With version 9.2 it worked fine but 9.3 returns 404 errors when accessing my static files. (my dynamic json still works fine).  
Putting on debug logging and debug stepping, I traced the issue to this code in org.eclipse.jetty.server.handler.ResourceHandler:

```
  Resource r = base.addPath(path);
  if (r!=null && r.isAlias() && (_context==null || !_context.checkAlias(path, r)))
  {
      if (LOG.isDebugEnabled())
          LOG.debug("resource={} alias={}",r,r.getAlias());
                return null;
  }
  return r;
```

At this point the _context is null.  r successfully points to the requested file.  
If it is symlinked it now returns null.  (while cryptically logging out the corect path to the resource and the alias of the requested file). Sure enough when I went and opened my project directly without using the symlink, everything worked perfect.

I looked what was happening in 9.2.  That code above hasn't changed but r.isAlias() used to return null.  (I am assuming it wasn't working for windows symlinks but now it is.).  
I am assuming this code has something to do with whether it is ok to follow symlinks or not.  The weird part though is that my code just references a relative path that has no symlinks.  The full path to where the project itself lives can (optionally) go through the symlink.  But now when you do this, it just gives 404s.

**Comment by joakime** [comment]
Can you detail how you setup your windows environment, esp with regards to the symlink.

Please detail your FileSystem types too (its important, as different windows filesystems handle symlinks differently)

**Comment by Binary-L0G1C** [comment]
Hi.  Thanks for the the quick response.

Here is the exact configuration when I was trying to run it.
I am running Windows 7 (Ultimate) standard install.  I have two drives in my system, both NTFS.
My windows home directory is C:\Users\David.  In here I have a symlink directory called 'workspace' which links to a directory on my D drive.  In that directory I have all my programming projects including the one in question.  I normally just access everything through C:\Users\David\workspace\whatever (Linux symlink habits >_<)

I tried a few more things (like having the symlink on the same drive) but all acted the same (produced 404s).  

Even if there was no symlink at all involved, and in my java app I simply referenced the static content via the string './src/main/webapp/logiclodge-webapp/' instead of 'src/main/webapp/logiclodge-webapp/' (notice the dot) it would also fail (works in 9.2) with hasAlias being true (even though there IS no symlink this time) and the log saying:
`resource=D:/.../workspace/base-spring-webapp/src/main/webapp/logiclodge-webapp alias=D:/.../workspace/base-spring-webapp/./src/main/webapp/logiclodge-webapp`
(again notice the dot).  I think this may have to do with this issue: #261

Let me know if there is anything else you need info on or want me to try.  I can try some things on my Linux box too if you want.

~David

**Comment by joakime** [comment]
How did you create the symlink?
We need the exact syntax you used.

**Comment by joakime** [comment]
We ask this, as we've seen a large variety of misinterpretation of "symlink" on Windows (eg: shortcuts vs hard links vs symbolic links vs junction points), so we need to be precise on what mechanism you are using to set up the symlink you are concerned about.

**Comment by Binary-L0G1C** [comment]
mklink /D workspace "D:/path/to/workspace"

C:\Users\David>dir
 Volume in drive C has no label.
 Volume Serial Number is xxx

 Directory of C:\Users\David

2016-03-15  01:24 AM    <DIR>          .
2016-03-15  01:24 AM    <DIR>          ..
...
2015-06-28  05:22 PM    <SYMLINKD>     workspace [D:\path\to\workspace]
              xx File(s)         xxx bytes
              xx Dir(s)  xxx bytes free

C:\Users\David>

**Comment by dentrw** [comment]
I have the exact same problem. Junction.  Can not show the dos output as it is proprietary.  I am using jetty 9.4.25.v20191220.

**Comment by joakime** [comment]
The `org.eclipse.jetty.server.SameFileAliasChecker` should work with these kinds of setups.
Please try adding that alias checker to your context.

``` java
context.addAliasChecker(new SameFileAliasChecker());
```

**Comment by joakime** [comment]
Tests on Windows 10 using `mklink /D <name> <dest>` work if using the `SameFileAliasChecker`.

**Comment by joakime** [comment]
Closing as `SameFileAliasChecker` works.
