### ISSUE TITLE
Cleanup ServletHandler, specifically with respect to making filter chains more extensible

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5022]
**Jetty version**
9.4.30

**Description**
The ServletHandler has a method for overriding a CachedChain via the newCachedChain() method.

https://github.com/eclipse/jetty.project/blob/ae43b70a9f8907b8a2444f051bebab60f4a9162c/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java#L826-L836

But this cannot be used, as the `CachedChain` inner class is protected.

This method is only called from `ServletHandler.getFilterChain()`.

https://github.com/eclipse/jetty.project/blob/ae43b70a9f8907b8a2444f051bebab60f4a9162c/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java#L636-L637

There is also a missing related method for non-cached that should be created in ServletHandler.

``` java
public Chain newChain(Request baseRequest, List<FilterHolder> filters, ServletHolder servletHolder)
```

Which is used in `getFilterChain()`

https://github.com/eclipse/jetty.project/blob/ae43b70a9f8907b8a2444f051bebab60f4a9162c/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java#L660-L661

**Comment by gregw** [comment]
@joakime does the `newCachedChain` method need to return a `CachedChain`?  Can it just return a `FilterChain` ?

**Comment by gregw** [comment]
If we are going to expose more of this API.... we need to clean it up... in fact this whole class needs a bit of a  refresh.... changing title!
