### ISSUE TITLE
Jetty documentation link is broken for 9.3.28

### ISSUE THREAD

**Issue by smirandamedallia** [eclipse/jetty.project#5027]
**Description**
Navigating to page: https://www.eclipse.org/jetty/previousversions.html
Displays older versions of docs but clicking on `9.3.28.v20191105` docs link 
https://www.eclipse.org/jetty/documentation/9.3.28.v20191105 results in a 404

**Comment by WalkerWatch** [comment]
I erroneously removed the 9.3 references in https://github.com/eclipse/jetty.website/commit/8f67169fa9c4584eac23c357e76dc21dd4d6417c forgetting we generated that documentation on the fly. Checking in a fix now. In the mean time you can grab the documentation from [Maven Central](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-documentation/9.3.28.v20191105/).

**Comment by WalkerWatch** [comment]
Fix checked in at https://github.com/eclipse/jetty.website/commit/30e681c337d6ba6412d9024ebadbe9e0c867fbea

Note: It will take some time to build and publish.
