### ISSUE TITLE
LogbackServletContainerInitializer fails to produce log output we call DeploymentManager.removeApp()

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5035]
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
** logback version**
1.7.25
**OS type/version**
windows
**Description**

【title】:We configured logback, and then when the application stops, the log will not be output

【We Debug】：
1、First，I hava a Helloword Test War Used Servlet 2.3，Just one Picture. And Web.xml
```
<!DOCTYPE web-app PUBLIC
 "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
 "http://java.sun.com/dtd/web-app_2_3.dtd" >

<web-app>
  <display-name>Archetype Created Web Application</display-name>
</web-app>

```
2、When the application is initialized

![image](https://user-images.githubusercontent.com/33625419/87009446-c1291780-c1f7-11ea-8363-0371605bed15.png)

![image](https://user-images.githubusercontent.com/33625419/87009354-a22a8580-c1f7-11ea-8d2d-6c4e5709659e.png)

![image](https://user-images.githubusercontent.com/33625419/87010041-94c1cb00-c1f8-11ea-9aea-be7c1d909006.png)

**Comment by olamy** [comment]
Can you provide any error message you have?
When you say `We configured logback` what do you mean exactly? 
Do you refer to https://www.eclipse.org/jetty/documentation/current/configuring-logging-modules.html#example-logging-logback?

**Comment by james-z-repo** [comment]
sorry, There is no error message in this bug, just no log output。
We configured logback：this mean , we add this module(--module=logging-logback) in start.ini

**Comment by joakime** [comment]
> ``` xml
> <!DOCTYPE web-app PUBLIC
>  "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
>  "http://java.sun.com/dtd/web-app_2_3.dtd" >
> ```

This needs to be at least WebApp 3.0.

ServletContainerInitializer was introduced in Servlet 3.0

https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContainerInitializer.html

**Comment by james-z-repo** [comment]
yes，I know the WebApp needs to be at least WebApp 3.0.
But, I think, This bug is not related to webApp Version
![image](https://user-images.githubusercontent.com/33625419/87036057-cfd5f580-c21c-11ea-84dd-3e3d8715627d.png)

To prove this, I recalibrated the application:
1. Application A: A simple HelloWorld, webapp version > 3
2. Application B: A simple folder with an HTML inside

I debug App A && App B，both like this

![image](https://user-images.githubusercontent.com/33625419/87037429-c8175080-c21e-11ea-99a4-7977969da311.png)

![image](https://user-images.githubusercontent.com/33625419/87037455-d1a0b880-c21e-11ea-9896-7644a91154e6.png)

And then the Logback of Jetty is put in the Listeners to the app, and when you stop the app， it will destroy the Jetty log, so jetty can't print the log

**Comment by janbartel** [comment]
@zhengshundong01  let me re-iterate my comment from the other issue you opened in #5036 : it appears that you ALSO have the logback jars inside your webapp.  They should only be on the container classpath.

**Comment by janbartel** [comment]
@zhengshundong01 I'm closing this issue as there hasn't been any activity on it for a month, so I assume the advice given has resolved the problem. If not, then please reopen, and provide a full list of jars that are on the container path and webapp path (use dumpAfterStart=true in server.ini) and full DEBUG logs.
