### ISSUE TITLE
How are old jetty request log files deleted?

### ISSUE THREAD

**Issue by sirishaPydi** [eclipse/jetty.project#5037]
Jetty-version : 9.4.21

Java version: Java8

Our application uses instance of jetty to run its services on windows. Each service is configured to have its own start.d/*.ini with the modules it needs and jetty-requestlog is common for all of them. 
--module=requestlog in ini file.
These request logs are created in service folder > logs.
      
The logs are created with the default file pattern and are good. We would like to retain the request logs collected the past seven(7) days (instead of default 90 days) and edited file: _jetty\etc\jetty-requestlog.xml to include:
`<Set name="retainDays"><Property name="jetty.requestlog.retainDays" deprecated="requestlog.retain" default="7"/></Set> `

However, after a restart of the Windows Server, all the older request logs remained in folder.

Question: what method/procedure should be used to ensure only the past seven(7) days of request log files are retained?

**Comment by joakime** [comment]
`retainDays` is evaluated during "delete older files" event.

The "delete older files" event is triggered once a day at midnight.

**Comment by sirishaPydi** [comment]
Seems like the event is not triggered by itself as I see the logs files untouched even after a day. Could you please guide us if we are missing something?

**Comment by sirishaPydi** [comment]
Adding the below line in ini file along with --module=requestlog has deleted all old request logs keeping the current date's log alone.
  jetty.requestlog.retainDays=1
As you mentioned, we had to leave it overnight for the event to get triggered. 
Thank you
