### ISSUE TITLE
Unable to use TLSv1 & TLSv1.1 with Java 8

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#5039]
**9.4.24.v20191120**

**jdk1.8.0_201**

I am trying to run my application on TLSv1.1, but I get SSLHandshakeFailure Exception.

I am using the below code to enable TLSv1.1 in Jetty Server:

        SslContextFactory sslContextFactory = new SslContextFactory.Server();
        Security.addProvider(new OpenSSLProvider());
        sslContextFactory.setProvider("Conscrypt");
        sslContextFactory.setKeyStorePath(parameters.getKeyStoreFile());
        sslContextFactory.setKeyStorePassword(parameters.getKeyStorePassword());
        sslContextFactory.setIncludeProtocols("TLSv1.1");
        **sslContextFactory.setExcludeCipherSuites("^.*_(MD5|SHA|SHA1)$");**

Below is the dump for server:

```
+= SslConnectionFactory@b90306f{SSL->alpn} - STARTED
|  |  += Server@32e671b4[provider=Conscrypt,keyStore=file:///C:/SBI/sbi-fe.keystore,trustStore=null] - STARTED
|  |     +> trustAll=false
|  |     +> Protocol Selections
|  |     |  +> Enabled size=1
|  |     |  |  +> TLSv1.1
|  |     |  +> Disabled size=4
|  |     |     +> SSLv2Hello - ConfigExcluded:'SSLv2Hello', ConfigIncluded:NotSelected
|  |     |     +> SSLv3 - ConfigExcluded:'SSLv3', ConfigIncluded:NotSelected JVM:disabled
|  |     |     +> TLSv1 - ConfigIncluded:NotSelected
|  |     |     +> TLSv1.2 - ConfigIncluded:NotSelected
|  |     +> Cipher Suite Selections
|  |        +> Enabled size=28
|  |        |  +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
|  |        |  +> TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
|  |        |  +> TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
|  |        |  +> TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
|  |        |  +> TLS_RSA_WITH_AES_128_CBC_SHA256
|  |        |  +> TLS_RSA_WITH_AES_128_GCM_SHA256
|  |        |  +> TLS_RSA_WITH_AES_256_CBC_SHA256
|  |        |  +> TLS_RSA_WITH_AES_256_GCM_SHA384
|  |        +> Disabled size=14
|  |           +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|  |           +> TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
```

Below are the selected ciphers:

2020-07-09 18:34:48.056:DBUG:oejus.SslContextFactory:pool-4-thread-7: Selected Ciphers   [TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_EMPTY_RENEGOTIATION_INFO_SCSV] of [TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_PSK_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_PSK_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_FALLBACK_SCSV]

I get the below error:
DecryptedEndPoint@10678872{/127.0.0.1:49297<->/127.0.0.1:1091,OPEN,fill=-,flush=-,to=31/8000} stored fill exception
javax.net.ssl.SSLHandshakeException: Read error: ssl=0000000020E5D5E8: Failure in SSL library, usually a protocol error|error:100000b8:SSL routines:OPENSSL_internal:NO_SHARED_CIPHER (..\ssl\handshake_server.cc:650 00007FFA9F0273E0:0x00000000)

TLSv1.2 & TLSv1.3 work fine, but I am unable to run my application on TLSv1 & TLSv1.1

Is TLSv1/TLSv1.1 not supported in Jetty or do I need to add any cipher in java or am I missing something else?

**Comment by sbordet** [comment]
TLSv1.0 and TLSv1.1 are vulnerable and deprecated, they are not used for security reasons.
And it's not only the TLS protocol version but also the ciphers that they use that are weak/unsecure.

If you really want to use them you need to enable the TLS protocol *and* enable the ciphers that are by default excluded because they are old/weak/unsecure.

The error explicitly reports that: `SSL routines:OPENSSL_internal:NO_SHARED_CIPHER` - it means the client and the server did not have a single cipher in common to use.

Either upgrade your server to TLSv1.3, or you must downgrade your client (protocol and ciphers).

**Comment by joakime** [comment]
The exclusion line you highlighted ...

``` java
sslContextFactory.setExcludeCipherSuites("^.*_(MD5|SHA|SHA1)$");
```

is the same one that is present on the default exclusion list ...

https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L123-L138

TLSv1 and TLSv1.1 are supported by both older versions of Java and all versions of Jetty, but not with a default (unconfigured) SslContextFactory.

The default `SslContextFactory` excludes known weak / insecure cipher suites, which unfortunately means that your combination of version of Java and your specific SslContextFactory configuration has effectively removed all of the cipher suites (from your supported/available list in your JVM) for TLSv1 and TLSv1.1 to work. (your "selected" list of cipher suites pretty much means you only have support for TLS 1.2 and above)

Know that the industry as a whole has deemed SSLv3, TLS 1.0, and TLS 1.1 to all be insecure.
The entire industry strongly recommends to not use TLS 1.0 and TLS 1.1.
So much so, that in the first 3 months of 2019, *ALL* browser vendors have deprecated support for TLS 1.0 and TLS 1.1.
Also, the Oracle Cryptographic Roadmap has 2021 for disabling TLS 1.0 and TLS 1.1 across the board for Java 7, Java 8, Java 11, and all other future LTS releases of the JDK/JVM.
See: https://java.com/en/jre-jdk-cryptoroadmap.html

**Comment by prateekkohli2112** [comment]
Thanks for the quick response.

Will surely consider upgrading our server to TLSv1.2/TLSv1.3.

But as of now is there any way I can configure my client to support TLSv1/TLSv1.1 as well.

**Comment by sbordet** [comment]
> But as of now is there any way I can configure my client to support TLSv1/TLSv1.1 as well.

Configure your client with ciphers that are weak/unsecure, but supported by TLSv1.1.
How to do that depends on your client. The ciphers also depend on your client.

**Comment by prateekkohli2112** [comment]
I am using Jetty Client 9.4.24.v20191120 with Java jdk1.8.0_201.

So both my client and server are Jetty.

I tried ciphers like TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA and some others as well, but they are added in the blacklist ciphers list present in HTTP2Cipher class.

Would you be able to suggest any cipher for TLSv1/TLSv1.1 which would be supported by both Jetty client and server.

**Comment by sbordet** [comment]
```java
SslContextFactory.Client sslClient = new SslContextFactory.Client();

// The following line excludes no cipher, i.e. allows them all.
sslClient.setExcludeCipherSuites();
```

If you want to use HTTP/2, you must use TLSv1.2 and strong ciphers - otherwise you need to override methods to customize the HTTP/2 configuration.

**Comment by prateekkohli2112** [comment]
Thanks @sbordet & @joakime
