### ISSUE TITLE
org.eclipse.jetty.osgi-servlet-api missing osgi.contract=JavaServlet"

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#5041]
**Jetty version**
9.4.30
**Description**
On jetty document, servlet bundle advice is org.eclipse.jetty.osgi-servlet-api from Mort Bay Consulting
but this bundle missing "Provide-Capability: osgi.contract; osgi.contract=JavaServlet"
follow https://www.osgi.org/portable-java-contract-definitions/

i'm not sure this bundle still maintain, so advice to modify document to use org.apache.felix.http.servlet-api

**Comment by janbartel** [comment]
@hieplq I've updated the documentation to reference the bundle you suggest for jetty-9.4: as the org.eclipse.jetty.osgi-servlet-api bundle is no longer maintained, it is too hard to add contract header. But I'll see if it can be done for the servlet api bundles used by jetty-10 and jetty-11.

**Comment by janbartel** [comment]
PR #5049 to update the 9.4 osgi doco.

**Comment by hieplq** [comment]
sorry org.apache.felix.http.servlet-api get other issue. it don't export javax.servlet.resources

**Comment by janbartel** [comment]
@hieplq ok, I thought you had tested it. I've dropped the PR. I'll close this issue, and create another one to add the header to the servlet api bundles used by jetty-10 and jetty-11 instead.

**Comment by janbartel** [comment]
Raised https://github.com/eclipse/jetty.toolchain/issues/33

**Comment by hieplq** [comment]
i tested on minimal profile (jetty + felix console + org.apache.felix.http.servlet-api)
but on my big project idempiere, i saw some other jetty bundle import it (javax.servlet.resources)
sorry by later update
