### ISSUE TITLE
Update asm dependency version

### ISSUE THREAD

**Issue by jayanderson** [eclipse/jetty.project#505]
http://asm.ow2.org/history.html

The version being used is 5.0.1. The latest 5.0.x version is 5.0.4. (latest version is 5.1)

For a project I'm working on I mostly want to get rid of dependency convergence issues (https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html). For now I'm excluding the version from jetty since it's older. This is a low priority issue, but it'd be nice to have if it doesn't cause other issues.

**Comment by janbartel** [comment]
I've opened CQs at Eclipse to get approval to update the asm libraries in Jetty. Hopefully just a matter of time before approval is given.

**Comment by abrin** [comment]
This is an issue with the jetty-maven-plugin too.

**Comment by janbartel** [comment]
Updated jetty-9.4.x and master to asm-5.1
