### ISSUE TITLE
Are Jetty-7.6.0.RC4, Jetty 8.1.4 and Jetty 9.4.28 support the SSL3.0, TLS1.3 and IPv6 protocols?

### ISSUE THREAD

**Issue by kaushik-piparotar** [eclipse/jetty.project#5050]

**Comment by sbordet** [comment]
Jetty 7 and 8 are End-Of-Life.

Jetty 9.4.x supports IPv6 and, when run with Java 11 or later, TLS 1.3.

SSL 3.0 is a vulnerable protocol and it's disabled by default in all modern implementations.

**Comment by joakime** [comment]
@kaushik-piparotar just to add to what @sbordet pointed out. 

Both Jetty 7 and Jetty 8 series are EOL (End of Life).

See https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

And using those version are also subject to various security report

https://www.eclipse.org/jetty/security-reports.html

When it comes to what Java supports crypto wise (in the past, now, and also planned changes in the future), see the Oracle Crypto Roadmap.

https://java.com/en/jre-jdk-cryptoroadmap.html
