### ISSUE TITLE
`javax.servlet.include.context_path` attribute on root context. should be empty string, but is `"/"`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5057]
By the way - I don't have test yet, but when checking Jetty / Tomcat / Undertow, I saw that Jetty sets wrong value to `javax.servlet.include.context_path` attribute when using root context. should be empty string, but is `"/"`. I can think about PR later, but maybe already you have idea if it's wrong? (Undertow and Tomcat set it to `""`).

_Originally posted by @grgrzybek in https://github.com/eclipse/jetty.project/pull/5026#issuecomment-659326117_

**Comment by grgrzybek** [comment]
Thanks!

**Comment by joakime** [comment]
I'm frankly a bit surprised that the servlet tck doesn't have a testcase for this.

**Comment by janbartel** [comment]
The tck seems to use the context root `/servlet_spec_requestdispatcher_web` for the tests:   https://github.com/eclipse-ee4j/jakartaee-tck/blob/8.0.2/src/com/sun/ts/tests/servlet/spec/requestdispatcher/URLClient.java#L46

**Comment by grgrzybek** [comment]
Ah - so the TCK test for root context is missing.
I'm glad we can finally (after moving to Eclipse) see the TCKs ;)

**Comment by joakime** [comment]
PR #5057 is merged

**Comment by tarator** [comment]
Should this already be fixrd in Jetty 10.0.0? I'm using the Jetty 10 Java package together with Spring. Calling `request.getContextPath()` still returns a "/" instead of an empty string as expected. is there a setting I could use?
