### ISSUE TITLE
Welcome files should handle null paths

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#506]
It is an option to not redirect the URI /contextPath to /contextPath/
If this option is enabled, then welcome file mapping should still work for the context root. 
See [google appengine issue](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/210) for context.

**Comment by gregw** [comment]
Hmmm appears to work for null mappings.  Perhaps not JSPs....

**Comment by janbartel** [comment]
I've checked this on both jetty 9.3.x and jetty-9.2.x with an index.jsp file. With context.setAllowNullPathInfo(true), an index.jsp file is served up as expected for a url such as http://localhost:8080/test
