### ISSUE TITLE
Server is not responding back to a long running request

### ISSUE THREAD

**Issue by Thiru-Arasu** [eclipse/jetty.project#5061]
**Jetty version**
9.4.30.v20200611

**Java version**
1.8

**Question**
We have developed a simple web application server for doing file upload. The server works perfectly and client too gets ack immediately when a less amount of request comes, whereas if request count gets increased then the server is taking a long time to finish a work and responding back to client as well. So if a request takes a long time to get completed, the client will not receive any response further from server; it is waiting for infinity.  

even I have set idle timeout also but it does work.

**Comment by janbartel** [comment]
@Thiru-Arasu  there's not really enough information in this question to diagnose your problem. 

Have you tried issuing a request for a very small, simple static resource to test whether the server is still responsive to other requests that don't involve file uploads? Have you tried taking a thread dump to see what the threads are doing? Have you sized your thread pool correctly? Do you see any log messages about low thread availability?

**Comment by gregw** [comment]
I'm sorry but there is not enough info in your post to really say very much.

However, note that the idle timeout does not apply when a request is dispatched to a filter/servlet.  The spec allows a servlet to take an infinite amount of time to complete, even if the underlying connection times out underneath.

So you need to find out what is happening when you have more requests on the server.  Are the requests taking infinite time or just a very long time.  There is a big difference between the two.  Infinite time suggests a dead lock or similar failure.  A long time can just be contention on a shared resource.

The best way to diagnose is to obtain several JVM thread dumps while the server is not responding.  Also using JMX to get a j[etty dump](https://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html) would be very handy.

**Comment by Thiru-Arasu** [comment]
Thank you so much for swift response!
Here, I have added code for how did I configured thread pool.

**QueuedThreadPool threadPool = new QueuedThreadPool();
threadPool.setMaxThreads(500);
threadPool.setMinThreads(50);
threadPool.setDetailedDump(true);**

for workaround, I have reproduced the issue using  the method thread.sleep().  I have set the sleep count is 1000000. I observed the same issue for this request also. 

Here, I have attached a sample thread dump
https://gist.github.com/Thiru-Arasu/8cd2aa7e1c2c619f344d0dddbc4095e7

**Comment by joakime** [comment]
@Thiru-Arasu the "jetty dump" is not a thread dump.

Please follow the instructions on the link that @gregw provided, the jetty dump will produce a state of the server represented by a tree (using ascii).
That tree is what we are looking for.  (also, the setting `threadPoo.setDetailedDump(true)` impacts the output of the jetty dump by producing more information about the threadpool, it has no impact on a traditional java thread dump)

**Comment by Thiru-Arasu** [comment]
Thank you.
I have updated in the same link "jetty dump" logs

**Comment by janbartel** [comment]
@Thiru-Arasu nothing unusual in those thread dumps:  during request processing you see about 10 threads inside the application code doing a Thread.sleep(), but plenty of threads in the thread pool are waiting to serve requests.  You should look at your real application code to determine where the delay in handling might be. Do thread dumps during one of these busy times and see where the threads are in the code. You can also get a trace of the http conversation between browser and client (eg with something like wireshark) and trace the flow there.  So far there is nothing to indicate any issue with jetty, more than likely this is contention in the application for some shared or slow resource, which a code inspection coupled with judicious thread dumps should help you to pinpoint.
