### ISSUE TITLE
Error org.eclipse.jetty.io.EofException  using Kotlin coroutine

### ISSUE THREAD

**Issue by rodrigodevelms** [eclipse/jetty.project#5063]
**Jetty version**
jetty-alpn-openjdk8-client 9.4.24.v20191120
**Java version**
11 (Using with kotlin 1.3.7)
**Question**
Hi all. 
I created a function to know if a service is up / down. Like elasticsearch for example.

```
suspend fun checkStatus(
  target: Target,
  login: String,
  passwordLogin: String,
  url: String
) {
  runCatching {
    when (target) {
      Target.Elasticsearch -> {
        val client = HttpClient(Jetty) {
          install(Auth) {
            basic {
              username = login
              password = passwordLogin
            }
          }
        }
        client.get<String>(url)
      }
    }
  }.onFailure {
    it.printStackTrace()
    throw it
  }
}
```

but i'm getting this error:
org.eclipse.jetty.io.EofException
Caused by: java.nio.channels.AsynchronousCloseException
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263)

I found something about it here: https://github.com/eclipse/jetty.project/issues/1445 (in sbordet anwser). but it did not work.

could someone help me?

**Comment by sbordet** [comment]
You are using Java 11, so you don't need `jetty-alpn-openjdk8-client`, because that is for Java 8. Remove it.

Use `jetty-alpn-java-client` instead, which is valid for Java 11 and later.

**Comment by sbordet** [comment]
Closing as answered.
