### ISSUE TITLE
Consider avoiding using ${conscrypt.version} and "non-standard" properties in a pom.xml

### ISSUE THREAD

**Issue by pombredanne** [eclipse/jetty.project#5072]
See https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-alpn/jetty-alpn-conscrypt-server/pom.xml#L21
The POM will end up on Maven central as https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-alpn-conscrypt-server/10.0.0-alpha0/jetty-alpn-conscrypt-server-10.0.0-alpha0.pom but then it has no notion of what variables were used at build time.
So when I read the POM for static dependencies analysis with my tools, https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/maven.py I get a really hard time to get proper data.
The only way would be to get the parent of the parent POM, eg. https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/pom.xml which may not be available and I may not be able to make network calls from an air-gapped envt. 

I reckon that is likely very low on your priorities list but that would be super nice if there something that could be done there

**Comment by sbordet** [comment]
No. 

Copying the same version in N different POMs is recipe for inconsistent values. 

Now we just update the value in the variable and we are consistent.

Consider updating your tools to read recursively the parent POMs.

**Comment by pombredanne** [comment]
Fair enough. But you should not assume that the parent POM is always on hand as it is typically not the case (such as inside a shaded uberjar). In most cases when looking at some app, the parents are not handy, nor is a property file

**Comment by joakime** [comment]
That scancode toolkit isn't resolving the Maven effective pom properly.

A single pom is never considered effective to make decisions off of.
You have to resolve the pom against it's pom hierarchy (if you want sane dependencies) **and** the version of maven you are resolving it against (if you want sane plugins and their dependencies).

Consider using something like https://maven.apache.org/resolver/
