### ISSUE TITLE
TLSv1.3 support in eclipse jetty with Java8 (8u261 b12)

### ISSUE THREAD

**Issue by karthickm512** [eclipse/jetty.project#5073]
**Jetty version**
Eclipse Jetty version 9.3.x

**Java version**
Java8 8u261 b12

**Question**
Does the Org.Eclipse.Jetty 9.3.x support TLSv1.3 in Java8 (8u261 b12)? We use pax-web.
Oracle released the support of TLSv1.3 in Java8 on July-14-2020 (https://www.oracle.com/java/technologies/javase/8u261-relnotes.html). Which version of Jetty/pax-web supports this TLS version with Java 8 configured?

**Comment by joakime** [comment]
Jetty 9.3.x is missing 2 things you might stumble into.

In Java 8u251 Oracle backported the ALPN support from Java 9+ into Java 8.
This ALPN support layer only works with 9.4.28.v20200408 or newer (see Issue #4443)

In Java 8u261 Oracle backported the TLS 1.3 features from Java 11+ into Java 8.
This TLS 1.3 support layer only works with 9.4.12.v20180830 or newer (see Issue #2711)

**Comment by karthickm512** [comment]
Thanks for the quick response. Is there any plans for you to backport the necessary modules from Jetty 9.4.x to 9.3.x ?

**Comment by joakime** [comment]
Jetty 9.3.x is no longer supported.

See: https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

We maintain at most 3 versions of Jetty.

Which currently is: 9.4.x, 10.0.x, and 11.0.x
