### ISSUE TITLE
:authority header for IPv6 address not having square brackets 

### ISSUE THREAD

**Issue by lubinson** [eclipse/jetty.project#5079]
**Jetty version**
9.4.30.v20200611
**Java version**
11
**OS type/version**

**Description**
The :authority header Jetty Http Client send out for IPv6 endpoint is
`:authority: 2356:0102:3238:3876:1122:2232:4321:80`
As per the IPv6 host literal the value should be 
```[2356:0102:3238:3876:1122:2232:4321]:80```

**Comment by sbordet** [comment]
> As per the IPv6 host literal the value should be bracketed

AFAIK, the square brackets for IPv6 addresses are only needed in URIs.

I'm not aware of the IETF IPv6 specification to mandate square brackets and I don't think they should be sent in the HTTP/2 `:authority` pseudo header.

I know of HTTP/2 deployments over IPv6 and we have not had reports of problems for lack of square brackets in `:authority`.

Do you have any authoritative reference or interoperability issue that confirms the problem?

**Comment by joakime** [comment]
What does curl produce when you force http2 and ipv6?

```
curl -vvvv --http2 --ipv6 ...
```

**Comment by lubinson** [comment]
@sbordet 

Thanks for your response. 
Please refer  [https://tools.ietf.org/html/rfc7540#section-8.1.2.3](https://tools.ietf.org/html/rfc7540#section-8.1.2.3)  for the `:authority` header definition and it refer to the [https://tools.ietf.org/html/rfc3986#section-3.2](https://tools.ietf.org/html/rfc3986#section-3.2) for Authority definition and [https://tools.ietf.org/html/rfc3986#section-3.2.2](https://tools.ietf.org/html/rfc3986#section-3.2.2) for the Host segment in the Authority which the Host format as:
`IP-literal = "[" ( IPv6address / IPvFuture  ) "]"`

**Comment by sbordet** [comment]
I verified that `curl` sends `:authority` with value `[::1]:8080`.
The server is able to parse that correctly through class `HostPort`, which accepts also IPv6 without brackets.

The client should also take into account `CONNECT` requests that have an authority request-target, and take into account the behavior mandated by RFC 8441.

**Comment by sbordet** [comment]
See #1503.
