### ISSUE TITLE
Improve exceptions during graceful shutdown failure

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#508]
A graceful shutdown failure does not report either the timeout nor the component that was being waited on.   The exception thrown from stop needs to be a lot clearer what has occurred.

**Comment by gregw** [comment]
Note also that the StatisticsHandler should have optional graceful shutdown behaviour, as it should not be necessary to turn off all graceful shutdown just to avoid stats graceful shutdown.

**Comment by sbordet** [comment]
Closing this in favor of #4321.
