### ISSUE TITLE
Convert synchronized usages to AutoLock

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5083]
**Jetty version**
10.0.x

**Description**
To be more Loom friendly we need the usages of `synchronized` to be converted to use `java.util.locks.Lock` or, better, Jetty's `AutoLock`.

This would allow early testing of Loom prototypes on a more fair basis.

**Comment by sbordet** [comment]
This issue is under the Loom umbrella issue #5078.

**Comment by gregw** [comment]
But this change needs to stand on it's own merits rather than be justified by Loom.

**Comment by sbordet** [comment]
@gregw this change has already improved locking in few places, clarified others and spun off #5081 and #5086.

Overall it is a good cleanup, but obviously getting rid of all `synchronized` is much more than just fixing a few things.
However, we would not have found the few things if we did not do this review :smiley:
