### ISSUE TITLE
Big performance Dip with TLS when using Jetty Client and Server Http2

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#5085]
**9.4.24.v20191120**

**jdk1.8.0_221**

We are using Jetty Server and Jetty Client for HTTP2 communication.

When we use it without TLS(HTTP) we get around 30500 TPS(Transactions per second) performance with all the default values.

But when we enable SSL(HTTPS) in the same setup which is using conscrypt at both Client and Server end, the TPS dips to almost 8500.

As we did not change any configuration while using HTTPS, so is this big dip expected.

If yes, is there any way we can increase the performance with HTTPS as well?

**Comment by sbordet** [comment]
The performance dip is expected from clear-text to encrypted.

The JDK TLS implementation is known to be quite slow and memory hungry and that is why we typically recommend offloading to load balancers or proxies.

If you want to do TLS in the JVM, you can try the `Conscrypt` provider for better performance, see https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html#conscrypt.

**Comment by prateekkohli2112** [comment]
I am already using Conscrypt in my Jetty Client and server.

I was surely expecting some dip, but 30000(HTTP) to 8000(HTTPS) is huge.

**Comment by sbordet** [comment]
What TLS protocol version are you using, and what cipher has been negotiated?

Also, make sure you use persistent connections. Open the connections once, and then keep them open, reusing them for many requests.

The initial TLS handshake is the most expensive operation in TLS, so if you close connections often you will have a big performance impact.

**Comment by prateekkohli2112** [comment]
Protocol : TLSv1.3
Cipher Suite: TLS_CHACHA20_POLY1305_SHA256

We are not closing the connection. A connection will be used as long as it is not closed by jetty.

**Comment by sbordet** [comment]
If you are already using Conscrypt, then TLS is done natively in C and you are as fast as Apache httpd or Nginx or similar.
I would double check that you are not closing connections unexpectedly because that would explain the big difference.

Other than that, it really depends on your load test setup and how you measure things - it's easy to get load tests wrong.

**Comment by prateekkohli2112** [comment]
Do you think upgrading to Jetty 9.4.30.v20200611 can help?

CPU and the memory consumption for both client and server are very low.

**Comment by sbordet** [comment]
@prateekkohli2112 upgrading is always good as you get both performance improvements and fixes.

Whether it helps for your case depends on your case, so you have to measure.

**Comment by joakime** [comment]
Some general advice.

The performance of `/dev/random` and `/dev/urandom` has an impact on your encryption performance. (on linux, there's many different options for configuring both the PRNG that the OS uses and the PRNG that Java itself uses)

Don't run your load/performance tests entirely on the same machine.

Move your clients off to a different machine, and makes sure you have multiple physical client machines for your server.
Depending on your load test you might be able to get away with as little as 4 client machines (each running multiple client connections) for each server, but sometimes you might need more to adequately test the server performance.  (if adding more clients makes no impact on server performance or server utilization, then I would suspect a slow PRNG implementation is in use)

Monitor your network utilization as well, make sure you are not hitting some kind of limit on the network.

Might try using a different cipher suite too.
While `TLS_CHACHA20_POLY1305_SHA256` is generally regarded as a good performing cipher suite, but there could be other cipher suites that perform better on your specific hardware / OS combo.

**Comment by prateekkohli2112** [comment]
The performance increased from 8500 to 25000 as I decreased my maxConcurrentStreams from 128 to 20.

**Comment by sbordet** [comment]
Closing as this seems a configuration issue in OP load testing.
