### ISSUE TITLE
Review ContextHandler locking

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5088]
Spawned by #5083.

**Jetty version**
9.4.x

**Description**
`ContextHandler` uses a mix of `synchronized` modifiers and `synchronized (this)` inside methods that is difficult to reconcile.

Furthermore, it has a `setClassLoader()` method that allow to arbitrarily change the `_classLoader` field but the rest of the code does not protect with a lock this field, nor it reads the field only once.
For example, `loadClass()`, `handle()`, `addListener()`, etc. reference the `_classLoader` field multiple times and the field may change between the references.

Also, `handle()` could have an improved logic.
In `handle()`, in the `finally` block, rather than checking on `oldClassLoader` the check should be done symmetrically on `_classLoader` like the code before the `try` does and like `doStart()` does.

Also, `setAvailable()` is locked, but `isAvailable()` is not. In general, `_availability` is not correctly locked.

**Comment by joakime** [comment]
I vote that `.setClassLoader(ClassLoader)` should not be allowed after the `ContextHandler` is started/running.

Changing the classloader after some classes have been loaded cannot lead to good things.
