### ISSUE TITLE
Review UrlEncoded locking

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5093]
Spawned by #5083.

**Jetty version**
9.4.x

**Description**
`UrlEncoded` needs a serious review.

It is used almost only for its `static` methods, however is itself a `MultiMap` and can decode a query string into itself, which is only used in tests.

The `static` methods return void but require a `MultiMap` parameter that is always created anew, but it is used as a lock inside the `UrlEncoded` methods, which is completely unnecessary.

The whole locking of this class should be removed, and the `static` methods of this class should return a `MultiMap` or a `Map`.

Also, it should just be a static utility class, rather than inheriting from `MultiMap`.

**Comment by gregw** [comment]
I'll target this for 10 as it may be significant
