### ISSUE TITLE
using JettyWebSocketServlet without having a WebSocketUpgradeFilter

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#5096]
**Jetty version**
10.0.x

**Description**
The `WebSocketUpgradeFilter` is added automatically by the `JettyWebSocketServletContainerInitializer` but the filter is not required if websocket upgrades are being done by a `JettyWebSocketServlet`.

There should be some option to not automatically create this this in the `JettyWebSocketServerContainer`.

**Comment by joakime** [comment]
This hints at a lazy initialized `WebSocketUpgradeFilter`.

Some things to consider ...

* The `JettyWebSocketServerContainer` can be accessed by the application, and it can use `.addMapping()` at any time.
* The `WebSocketUpgradeFilter` should be the first filter in the chain, if we create it.
* The `WebSocketUpgradeFilter` can be added by the application (such as in the `WEB-INF/web.xml`), and we should use that one if present. (cometd is a good example of this usage pattern)

Perhaps we should have a more fundamental component, built into `ServletContextHandler`, the `UpgradeHandler` (fitting into the same role as `ServletHandler`)?
