### ISSUE TITLE
Add serialVersionUID in all Serializable classes

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5100]
We should make this change for all of our Serializable classes.

https://product.hubspot.com/blog/java-11-dont-rely-on-generated-serialversionuid

_Originally posted by @joakime in https://github.com/eclipse/jetty.project/pull/5084#discussion_r462323200_

**Comment by gregw** [comment]
We also should review which classes need to be serializable.   In the dark ages, the entire Jetty server was Serializable, so you could save a server with all it's configuration!    I think this was even used by some.    But it has long ago ceased to be meaningful or to actually work.    So there are probably a few classes left over that don't need to be Serializable and then they probably have some fields marked as transient that do not need to be so.
