### ISSUE TITLE
Improve SessionTracker scalability

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5108]
**Jetty version**
9.4.26 and later

**Description**
`SessionTracker` holds a list of session in a `COWAList`.

Unfortunately it's a singleton-like object, so if an application opens and closes WebSocket connections at a high rate, it becomes a bottleneck because of lock contention.

**Comment by joakime** [comment]
IIRC, The SessionTracker has a few purposes.

1. To avoid the `addBean()` `removeBean()` contention of the previous impl (and `dump()` issues)
2. Holds the collection of open Sessions to allow for proper graceful shutdown.
3. To satisfy the needs of [`javax.websocket.Session.getOpenSessions()`](https://docs.oracle.com/javaee/7/api/javax/websocket/Session.html#getOpenSessions--)

While 1 and 2 can be solved in ways that don't need to use the Collections objects, the need in point 3 means the the ability to at least return a `Set<Session>` when asked.

**Comment by sbordet** [comment]
@joakime do we only need it for the JSR implementation, or also the Jetty APIs have a similar method?

We can use a more efficient data structure as `getOpenSessions()` is not called that often, so that we do not pay the price every time a connection is opened/closed.

**Comment by lachlan-roberts** [comment]
@sbordet the Jetty WebSocket API does have similar methods as well.

**Comment by lachlan-roberts** [comment]
PR #5109 fixes the scalability issue by using a set derived from `ConcurrentHashMap` instead of the `CopyOnWriteArraySet`. 
This has been merged into the 9.4.x branch and will be available in a 9.4.32 release.
