### ISSUE TITLE
JavaUtilLog does not inherit level

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#511]
When using the JavaIUtilLog the log level does not appear to be inherited correctly.

if we create a jetty log at `com.example.FooBar` then we can see debug output with a `logging.properties' file that includes `com.example.FooBar.level=FINE`, but if the file contains only `com.example.level=FINE` then no debug output is produced.

**Comment by joakime** [comment]
Created a small test project at [joakime/jul-bug-511] and it seems to work as expected.

`com.example.jetty.FooBar` emits Jetty log events on debug, info, and warn.
The `FooBarTest` executes the `FooBar` class.

 * Jetty Log is initialized
  * jetty-logging.properties is loaded
  * JavaUtilLog is configured during init
  * java.util.logging is configured during init
 * Using `com.example.jetty.FooBar.level=FINE` works
 * Using `com.example.jetty.level=FINE` works as well

**Comment by gregw** [comment]
Hmmm was not working for me in https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime,  I will chase down the difference.

**Comment by joakime** [comment]
Not reproducible. closing
