### ISSUE TITLE
Change WebSocketRemoteEndpoint private method to protected that allow user directly send ByteBuffer as TextFrame to client

### ISSUE THREAD

**Issue by leonchen83** [eclipse/jetty.project#5113]
**Jetty version**
jetty-9.4.x
**Java version**
jdk 1.8
**Question**
Change WebSocketRemoteEndpoint private method to protected that allow user directly send ByteBuffer as TextFrame to client

we want send bytebuffer as TextFrame directly. for example
```
public class XWebSocketRemoteEndpoint extends WebSocketRemoteEndpoint {
	
	public XWebSocketRemoteEndpoint(LogicalConnection connection, OutgoingFrames outgoing) {
		super(connection, outgoing);
	}
	
	public XWebSocketRemoteEndpoint(LogicalConnection connection, OutgoingFrames outgoing, BatchMode batchMode) {
		super(connection, outgoing, batchMode);
	}
	
	public void sendString(ByteBuffer text) throws IOException
	{
		lockMsg(MsgType.BLOCKING);
		try
		{
			WebSocketFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendString with {}", BufferUtil.toDetailString(frame.getPayload()));
			}
			blockingWrite(frame);
		}
		finally
		{
			unlockMsg(MsgType.BLOCKING);
		}
	}

	public void sendString(ByteBuffer text) throws IOException
	{
		lockMsg(MsgType.BLOCKING);
		try
		{
			WebSocketFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendString with {}", BufferUtil.toDetailString(frame.getPayload()));
			}
			blockingWrite(frame);
		}
		finally
		{
			unlockMsg(MsgType.BLOCKING);
		}
	}

	public Future<Void> sendStringByFuture(ByteBuffer text)
	{
		lockMsg(MsgType.ASYNC);
		try
		{
			TextFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendStringByFuture with {}", BufferUtil.toDetailString(frame.getPayload()));
			}
			return sendAsyncFrame(frame);
		}
		finally
		{
			unlockMsg(MsgType.ASYNC);
		}
	}

	public void sendString(ByteBuffer text, WriteCallback callback)
	{
		lockMsg(MsgType.ASYNC);
		try
		{
			TextFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendString({},{})", BufferUtil.toDetailString(frame.getPayload()), callback);
			}
			uncheckedSendFrame(frame, callback == null ? NOOP_CALLBACK : callback);
		}
		finally
		{
			unlockMsg(MsgType.ASYNC);
		}
	}
}
```
add an extra method `public void sendString(ByteBuffer text)` to avoid create new string and avoid byte array copy, 
and we know that `ByteBuffer` contains utf-8 byte array.
so could jetty change `private` method to `protected` that allow us to extension this class?

**Comment by leonchen83** [comment]
in our scenario we push to client many tiny json message like `{"event":"QUOTE","data":[["1215235156379296277",3,16842753,"1596441319629","105.915","105.914"]["1215235156018585109",5,16842770,"1596441319586","1.19985","1.19984"],["1215235157620820501",5,16842780,"1596441319777","1.07343","1.07342"]]}`

1. we first use jackson to serialize Java Object to json byte array
```
ObjectMapper mapper = new ObjectMapper();
// return UTF-8 byte array
byte[] bytes = mapper.writeValueAsBytes(); 
```
2. then we create spring `TextMessage`  via `public TextMessage(byte[] payload)`

3. finally we send this TextMessage to jetty and convert TextFrame to push to client 

after we use [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) to profile memory allocation above process 
found that when we construct `String` object that need additional array copy, UTF-8 endcoding and outside [TLAB](https://dzone.com/articles/thread-local-allocation-buffers) space . then we want a method that directly to send `ByteBuffer` as `TextFrame` to client. and we know that `ByteBuffer` contains utf-8 byte array.

for now we send `BinaryFrame` to clinet instead of `TextFrame`, but this need client to encode and decode `BinaryFrame` although it's utf-8 binary frame.

so we want to change the private method to protected method that extension this class to fit our needs.

**Comment by leonchen83** [comment]
related pr [#5112](https://github.com/eclipse/jetty.project/pull/5112), [#5110](https://github.com/eclipse/jetty.project/pull/5110)

**Comment by joakime** [comment]
Sending raw ByteBuffer as a TEXT frame is in violation of the WebSocket protocol.
Per spec, we (the implementation) MUST validate the buffer to be UTF-8 compliant before we send it.

> after we use [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) to profile memory allocation above process
> found that when we construct` String` object that need additional array copy, UTF-8 endcoding and outside [TLAB](https://dzone.com/articles/thread-local-allocation-buffers) space . then we want a method that directly to send `ByteBuffer` as `TextFrame` to client. and we know that `ByteBuffer` contains utf-8 byte array.

Yes, this is exactly how all implementations of the websocket spec are supposed to function.
The implementation of the websocket spec MUST validate the buffer before sending, and not trust the application.
The implementation MUST also validate the buffer again when it receives it, and if in violation it MUST close the connection with status code 1007.

You have this validation step on send and receive on every websocket implementation in existence.

That's the side effect of using TEXT messages.
If you don't want this, then use BYTE messages exclusively.

Also, if you are just doing this to avoid an array copy, know that things like the `permessage-deflate` extension will cause another array copy.

Your choice of using Spring's `TextMessage(byte[])` is causing a lot of back and forth between byte > Utf8Appendable > String > getBytes(UTF_8) > ByteBuffer.

Use Spring's `TextMessage(String)` and you go String > getBytes(UTF_8) > ByteBuffer

Now, that being said.
I would be open to having the API be `java.nio.CharBuffer`, but never `ByteBuffer` or `byte[]`.
Which would leave us with a simple `ByteBuffer rawFramePayloadBeforeMaskingAndExtensions = java.nio.charset.StandardCharsets.UTF_8.encode(CharBuffer)`

**Comment by joakime** [comment]
Here's a testcase for you to noodle through, to demonstrate the problems with allowing [`TextMessage(byte[])`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/socket/TextMessage.html#TextMessage-byte:A-)

``` java
package unicode.nio;

import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CharsetEncoder;
import java.nio.charset.CodingErrorAction;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import org.eclipse.jetty.toolchain.test.Hex;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class BadUtf8SequencesTest
{
    public static Stream<Arguments> utfSequences()
    {
        List<byte[]> data = new ArrayList<>();

        // - differently unicode fragmented
        data.add(Hex.asByteArray("CEBAE1BDB9CF83CEBCCEB5EDA080656469746564"));
        // - partial/incomplete multi-byte code points
        data.add(Hex.asByteArray("CE"));
        data.add(Hex.asByteArray("CEBAE1"));
        data.add(Hex.asByteArray("CEBAE1BD"));
        data.add(Hex.asByteArray("CEBAE1BDB9CF"));
        data.add(Hex.asByteArray("CEBAE1BDB9CF83CE"));
        data.add(Hex.asByteArray("CEBAE1BDB9CF83CEBCCE"));
        // - first possible sequence length 5/6 (invalid code points)
        data.add(Hex.asByteArray("F888808080"));
        data.add(Hex.asByteArray("FC8480808080"));
        // - last possible sequence length (invalid code points)
        data.add(Hex.asByteArray("F7BFBFBF"));
        data.add(Hex.asByteArray("FBBFBFBFBF"));
        data.add(Hex.asByteArray("FDBFBFBFBFBF"));
        // - other boundary conditions
        data.add(Hex.asByteArray("F4908080"));
        // - unexpected continuation bytes
        data.add(Hex.asByteArray("80"));
        data.add(Hex.asByteArray("BF"));
        data.add(Hex.asByteArray("80BF"));
        data.add(Hex.asByteArray("80BF80"));
        data.add(Hex.asByteArray("80BF80BF"));
        data.add(Hex.asByteArray("80BF80BF80"));
        data.add(Hex.asByteArray("80BF80BF80BF"));
        data.add(Hex.asByteArray("808182838485868788898A8B8C8D8E8F909192939495969798999A9B9C9D9E9" +
            "FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBE"
        ));
        // - lonely start characters
        data.add(Hex.asByteArray("C020C120C220C320C420C520C620C720C820C920CA20CB20CC20CD20CE20CF2" +
            "0D020D120D220D320D420D520D620D720D820D920DA20DB20DC20DD20DE20"
        ));
        data.add(Hex.asByteArray("E020E120E220E320E420E520E620E720E820E920EA20EB20EC20ED20EE20"));
        data.add(Hex.asByteArray("F020F120F220F320F420F520F620"));
        data.add(Hex.asByteArray("F820F920FA20"));
        data.add(Hex.asByteArray("FC20"));
        // - sequences with last continuation byte missing
        data.add(Hex.asByteArray("C0"));
        data.add(Hex.asByteArray("E080"));
        data.add(Hex.asByteArray("F08080"));
        data.add(Hex.asByteArray("F8808080"));
        data.add(Hex.asByteArray("FC80808080"));
        data.add(Hex.asByteArray("DF"));
        data.add(Hex.asByteArray("EFBF"));
        data.add(Hex.asByteArray("F7BFBF"));
        data.add(Hex.asByteArray("FBBFBFBF"));
        data.add(Hex.asByteArray("FDBFBFBFBF"));
        // - concatenation of incomplete sequences
        data.add(Hex.asByteArray("C0E080F08080F8808080FC80808080DFEFBFF7BFBFFBBFBFBFFDBFBFBFBF"));
        // - impossible bytes
        data.add(Hex.asByteArray("FE"));
        data.add(Hex.asByteArray("FF"));
        data.add(Hex.asByteArray("FEFEFFFF"));
        // - overlong ascii characters
        data.add(Hex.asByteArray("C0AF"));
        data.add(Hex.asByteArray("E080AF"));
        data.add(Hex.asByteArray("F08080AF"));
        data.add(Hex.asByteArray("F8808080AF"));
        data.add(Hex.asByteArray("FC80808080AF"));
        // - maximum overlong sequences
        data.add(Hex.asByteArray("C1BF"));
        data.add(Hex.asByteArray("E09FBF"));
        data.add(Hex.asByteArray("F08FBFBF"));
        data.add(Hex.asByteArray("F887BFBFBF"));
        data.add(Hex.asByteArray("FC83BFBFBFBF"));
        // - overlong representation of NUL character
        data.add(Hex.asByteArray("C080"));
        data.add(Hex.asByteArray("E08080"));
        data.add(Hex.asByteArray("F0808080"));
        data.add(Hex.asByteArray("F880808080"));
        data.add(Hex.asByteArray("FC8080808080"));
        // - single UTF-16 surrogates
        data.add(Hex.asByteArray("EDA080"));
        data.add(Hex.asByteArray("EDADBF"));
        data.add(Hex.asByteArray("EDAE80"));
        data.add(Hex.asByteArray("EDAFBF"));
        data.add(Hex.asByteArray("EDB080"));
        data.add(Hex.asByteArray("EDBE80"));
        data.add(Hex.asByteArray("EDBFBF"));
        // - paired UTF-16 surrogates
        data.add(Hex.asByteArray("EDA080EDB080"));
        data.add(Hex.asByteArray("EDA080EDBFBF"));
        data.add(Hex.asByteArray("EDADBFEDB080"));
        data.add(Hex.asByteArray("EDADBFEDBFBF"));
        data.add(Hex.asByteArray("EDAE80EDB080"));
        data.add(Hex.asByteArray("EDAE80EDBFBF"));
        data.add(Hex.asByteArray("EDAFBFEDB080"));
        data.add(Hex.asByteArray("EDAFBFEDBFBF"));

        return data.stream().map(Arguments::of);
    }

    @ParameterizedTest
    @MethodSource("utfSequences")
    public void assertBadTextPayload(byte[] buffer) throws Exception
    {
        CharsetDecoder decoder = UTF_8.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT);

        CharBuffer cbuf = decoder.decode(ByteBuffer.wrap(buffer));

        CharsetEncoder encoder = UTF_8.newEncoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT);

        ByteBuffer rawPayloadBytesBeforeMaskingAndExtensions = encoder.encode(cbuf);

        String originalHex = Hex.asHex(buffer);
        String resultingHex = Hex.asHex(rawPayloadBytesBeforeMaskingAndExtensions);
        assertEquals(originalHex, resultingHex);
    }
}
```

Incidentally, about 90% of the above sequences are actually part of the websocket spec protocol and api tests. (eg: on the client tests they fail if attempted to be sent, and trigger a 1007 close status if received)

**Comment by lachlan-roberts** [comment]
@joakime it would be possible to do the validation step to check the `ByteBuffer` contains valid UTF-8 without doing the conversion to string and back.

**Comment by joakime** [comment]
@lachlan-roberts for whole message sends probably, partial message sends would need to hold the prior incomplete sequences.
and we'd need to keep the utf-8 check code up to date with the updates in the unicode spec and what is supported by the jvm. (eg: java 8 supports less then java 11)

When we keep the API as using String, even with the partial sends, it's actually not possible to have incomplete utf-8 sequences in the String object.

**Comment by lachlan-roberts** [comment]
@joakime There is some code in Jetty 10 websockets which does this in `ValidationExtension`, it uses `NullAppendable` which extends `Utf8Appendable` but discards all bytes. This validates the UTF-8 in websocket TEXT messages and can do partial UTF-8 sequences split over multiple frames.

Maybe this is not worth polluting the API with as we'd have to add 4 methods, when we already have the `String` versions. But could possibly see some performance improvements for this case.
```java
void sendPartialText(ByteBuffer fragment, boolean isLast)
void sendText(ByteBuffer buffer) throws IOException;
Future<Void> sendTextByFuture(ByteBuffer buffer);
void sendText(ByteBuffer buffer, WriteCallback callback);
```

**Comment by joakime** [comment]
Instead of exposing all of the internal machinations / methods you do in PR #5112 perhaps a different API is in order?

_It should be noted that starting in Jetty-10, there's another API lower then the "Jetty WebSocket API" you see in Jetty-9.
There's a "WebSocket Core API" where you can do all sorts of things at a very low level, including inventing Frames out of thin air._

In Jetty-9, a "FrameRemoteEndpoint" is probably in order, to allow usage of the API at the frame level with only 1 method.

``` java
public void uncheckedSendFrame(Frame frame, WriteCallback callback);
```

Using this API should be a "Switch" meaning, you either use this, or the formal API, never both.
Similar to how the Servlet API doesn't allow you to use OutputStream and Writer at the same time.

**Comment by leonchen83** [comment]
for now we work around with java reflection API as following. but I think it's not a good way to do this.
```
public class XWebSocketEndpoint extends WebSocketRemoteEndpoint {

	public XWebSocketEndpoint(LogicalConnection a, OutgoingFrames b) {
		super(a, b);
	}
	
	public XWebSocketEndpoint(LogicalConnection a, OutgoingFrames b, BatchMode c) {
		super(a, b, c);
	}

	public void sendString(ByteBuffer v, WriteCallback w) {
		if(INITIALIZD) {
			this.invoke(LOCK, ASYNC); 
			try {
				this.uncheckedSendFrame(new TextFrame().setPayload(v), w);
			} finally { 
				this.invoke(UNLOCK, ASYNC); 
			} 
		} else {
			// fallback
			String a = new String( v.array(), v.position(), v.remaining() );
			this.sendString(a, w);
		}
	}

	protected void invoke (final Method method, final Object[] args) {
		try {
			method.invoke(this, args);
		} catch(IllegalAccessException | IllegalArgumentException t) {
			throw new AssertionException(t);
		} catch (InvocationTargetException t) {
			final RuntimeException rethrow = (RuntimeException)t.getCause(); throw rethrow;
		}
	}
	
	private static volatile boolean INITIALIZD = false;
	private static final Object[] ASYNC = new Object[1]; 
	private static Method LOCK, UNLOCK;
	static {
		try {
			//
			for (Method v : WebSocketRemoteEndpoint.class.getDeclaredMethods ()) {
				if (v.getName().equals("lockMsg")) { LOCK = v; LOCK.setAccessible(true); }
				if (v.getName().equals("unlockMsg")) { UNLOCK = v; UNLOCK.setAccessible(true); }
			}
			
			//
			Class<Enum<?>> type = null;
			Class<?>[] clazz = WebSocketRemoteEndpoint.class.getDeclaredClasses();
			for (Class<?> v : clazz) if(v.getName().endsWith("MsgType")) type = Objects.cast(v);
			if (type != null) for(final Object v : type.getEnumConstants()) {
				Enum<?> value = Objects.cast(v); if ("ASYNC".equals(value.name())) ASYNC[0] = v;
			}
			
			//
			INITIALIZD = LOCK != null && UNLOCK != null && ASYNC[0] != null;
		} catch(Throwable cause) {
		}
	}
}
```

```
public class XRemoteEndpointFactory implements RemoteEndpointFactory {
	
	@Override
	public RemoteEndpoint newRemoteEndpoint(
		final LogicalConnection connection, final OutgoingFrames outgoing, final BatchMode mode) {
		final XWebSocketEndpoint r = new XWebSocketEndpoint(connection, outgoing, mode); return r;
	}
}
```

register java SPI
```
META-INF/services/org.eclipse.jetty.websocket.common.RemoteEndpointFactory

xx.xxxxx.xxxxxxx.XRemoteEndpointFactory
```

**Comment by leonchen83** [comment]
@lachlan-roberts 
could we directly invoke `public void uncheckedSendFrame(Frame frame, WriteCallback callback)` without invoke `lockMsg` and `unlockMsg` ? is there any risk to do so ?

**Comment by gregw** [comment]
Can we step back a bit from this issue, as I think we are trying to fix the wrong thing.   The suggested "solution" to allow unchecked frames to be sent is not the only solution to the problem... which was too much data copying when sending their frame.

So the problem we want to solve is how can we send a java object (that can be serialised with jackson to json) with minimal copying, maximum throughput and minimum latency... without breaking the API. 
If possible without trusting user that they have done a good UTF-8 conversion. This is a good problem for us to solve and maintain into the future.

However, in this case, I do think the conversion of Object->json->bytearray->SpringFrame->Jetty is probably mostly responsible for the copying.  I'm not sure what value spring is adding here, also why not get the json with `writeValueAsString` and then just send that as a text message?

So let's review to see what is the best way to do this in Jetty-10 (our future) and then see what is the absolute best we can do to send an object as json over websocket with minimal copying.  That's a good challenge for you @lachlan-roberts.    Then when we know what is optimal, we can see if we can mimic that API back in 9.4.x.... or push the OP to update to 10???

**Comment by joakime** [comment]
There's also the option to use Writer ...

Which skips 3 layers in Jackson, and 2 layers in jetty.

``` java
@OnWebSocketConnect
public void onOpen(Session session) throws IOException
{
    FooObject foo = getFooObjectForSession(session);
    
    try(MessageWriter writer = new MessageWriter((WebSocketSession)session))
    {
        ObjectMapper mapper = new ObjectMapper();
        mapper.writeValue(writer, foo);
    }
}
```

**Comment by leonchen83** [comment]
@joakime 
thanks. that's helpful

**Comment by leonchen83** [comment]
I will close this issue and related pr
