### ISSUE TITLE
Jetty configuration directive to limit tcp connections accepted? 

### ISSUE THREAD

**Issue by s0j0urn** [eclipse/jetty.project#512]
I am looking through the documentation to find out the configuration direction which may control the number of TCP connection that can be handled at once by jetty. 

Just for confirmation, is it controlled through acceptQueueSize?

**Comment by sbordet** [comment]
Client or server ?

**Comment by s0j0urn** [comment]
@sbordet 

On client we have setMaxConnectionsPerDestination.

I would like to know at server end.

**Comment by sbordet** [comment]
You want to set the property `jetty.http.acceptQueueSize` for clear-text connectors and/or `jetty.ssl.acceptQueueSize` for TLS connectors.

You also want to read [this detailed explanation](http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html) of how the accept queue works.

**Comment by gregw** [comment]
@s0j0urn  On server side there is the low resources monitor and DoSFilter. See https://www.eclipse.org/jetty/documentation/current/limit-load.html

**Comment by s0j0urn** [comment]
Thank you @gregw and @sbordet .
That was really helpful :)
