### ISSUE TITLE
Add if (LOG.isDebugEnabled()) in CompressExtension.decompress

### ISSUE THREAD

**Issue by leonchen83** [eclipse/jetty.project#5121]
**Jetty version**
jetty-9.4.x
**Java version**
java 1.8.u202
**Question**
jetty should add `if (LOG.isDebugEnabled())` in `CompressExtension.decompress` method befor `LOG.debug`
we profile memory allocation and found that `LOG.debug("Decompress: read 0 {}", toDetail(inflater)); break;` cosume some of memory as bellow
<img width="1104" alt="2020-08-05-7 29 44" src="https://user-images.githubusercontent.com/5235764/89488844-983a7900-d7db-11ea-92c7-012cf6f132d8.png">

**Comment by lachlan-roberts** [comment]
Yeah you're right, these debug logs should be guarded with the `LOG.isDebugEnabled()` check.
I will put up a PR to fix this.

**Comment by lachlan-roberts** [comment]
I'm going to reopen this issue until the PR gets merged.

**Comment by janbartel** [comment]
Merged for 9.4.32 and above.
