### ISSUE TITLE
Provide a dummy SessionHandler to disable container session management

### ISSUE THREAD

**Issue by quaff** [eclipse/jetty.project#5124]
Sometimes we implement session management by wrapping `HttpServletRequest` in application, so It's reasonable that jetty could provide such as this:
```
WebAppContext context = new WebAppContext();
context.setSessionHandler(new DummySessionHandler());
```
or provide a option at context or server level to disable session
```
context.disableSessionManagement();
```

**Comment by joakime** [comment]
If you are using embedded-jetty, why not just use `ServletContextHandler` instead of the `WebAppContext` (which mandates SESSION features)?

``` java
ServletContextHandler context = new ServletContextHandler(ServletContextHandler.NO_SESSIONS);
context.setContextPath("/");
// .. the rest of the initialization.
```

**Comment by quaff** [comment]
> If you are using embedded-jetty, why not just use `ServletContextHandler` instead of the `WebAppContext` (which mandates SESSION features)?
> 
> ```java
> ServletContextHandler context = new ServletContextHandler(ServletContextHandler.NO_SESSIONS);
> context.setContextPath("/");
> // .. the rest of the initialization.
> ```

I'm embedding jetty to war and deploy it self via `java -jar ROOT.war`, I need `WebAppContext::setWar`.

**Comment by quaff** [comment]
It's applicable even not using embedded-jetty.

**Comment by quaff** [comment]
Resolved by 
```java
WebAppContext context = new WebAppContext(null, new ConstraintSecurityHandler(), new ServletHandler(), new ErrorPageErrorHandler());
```
