### ISSUE TITLE
NoClassDefFoundError on a web service

### ISSUE THREAD

**Issue by ajoy75** [eclipse/jetty.project#513]
Hi, 

We have a set of web services deployed in a jetty web server on a Linux server and they have been working fine for quite some time now. Recently we are observing a strange issue which forced us to restart the server manually. The server has been running continuously from 23 Mar 2016 and on 13 Apr 2016, it started giving an error on a particular web service operation. The error log is as follows: 

{"@timestamp":"2016-04-13T15:26:49.480+01:00","@version":1,"message":"SQL query execution start","logger_name":"com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl","thread_name":"qtp1622006612-47990","level":"INFO","level_value":20000,"path":"/SecurityService/","query":"","url":"/SecurityService/","requestId":null,"operationName":"User Authentication","sessionId":null,"message":"SQL query execution start","parameters":232460,"SQL":"{call AGENCY_PORTAL_UTIL_PKG. SP_USER_LOGIN_REQUEST_RESPONSE(?, ?)}"}
{"@timestamp":"2016-04-13T15:26:49.925+01:00","@version":1,"message":"SQL query execution end","logger_name":"com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl","thread_name":"qtp1622006612-47990","level":"INFO","level_value":20000,"path":"/SecurityService/","query":"","url":"/SecurityService/","requestId":null,"operationName":"User Authentication","sessionId":null,"message":"SQL query execution end","parameters":232460,"numberOfResults":"0","SQL":"{call AGENCY_PORTAL_UTIL_PKG. SP_USER_LOGIN_REQUEST_RESPONSE(?, ?)}","elapsedTime":445}
{"@timestamp":"2016-04-13T15:26:49.947+01:00","@version":1,"message":"Forwarding to error page from request [/] due to exception [com/c4/ws/security/server/domain/ResponseUnmarshaller]","logger_name":"org.springframework.boot.context.web.ErrorPageFilter","thread_name":"qtp1622006612-47990","level":"ERROR","level_value":40000,"stack_trace":"java.lang.NoClassDefFoundError: com/c4/ws/security/server/domain/ResponseUnmarshaller\n\tat com.c4.ws.security.server.domain.UserAuthenticationServiceBean.getUserAuthenticationDetails(UserAuthenticationServiceBean.java:105) ~[classes/:na]\n\tat com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl.apAuthOperation(UserAuthenticationServiceImpl.java:40) ~[classes/:na]\n\tat sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]\n\tat java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]\n\tat org.springframework.ws.server.endpoint.MethodEndpoint.invoke(MethodEndpoint.java:134) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.endpoint.adapter.DefaultMethodEndpointAdapter.invokeInternal(DefaultMethodEndpointAdapter.java:291) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.endpoint.adapter.AbstractMethodEndpointAdapter.invoke(AbstractMethodEndpointAdapter.java:55) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.MessageDispatcher.dispatch(MessageDispatcher.java:236) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.MessageDispatcher.receive(MessageDispatcher.java:176) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:89) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.transport.http.WebServiceMessageReceiverHandlerAdapter.handle(WebServiceMessageReceiverHandlerAdapter.java:61) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.transport.http.MessageDispatcherServlet.doService(MessageDispatcherServlet.java:293) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[servlet-api-3.1.jar:3.1.0]\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) ~[na:na]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:116) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:60) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:91) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:109) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]\n","path":"/SecurityService/","query":"","url":"/SecurityService/"}
ERROR:  'Premature end of file.'
mapHeaders.getAllAttributes()===null
{"@timestamp":"2016-04-13T15:27:24.721+01:00","@version":1,"message":"Inbound request start","logger_name":"com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl","thread_name":"qtp1622006612-48068","level":"INFO","level_value":20000,"path":"/SecurityService/","query":"","url":"/SecurityService/","request":{"path":"/SecurityService/","method":"POST","requestId":null,"query":"","operationName":"9adfe11a-b50a-4d82-b8b9-823229dd924e","sessionId":null,"parameters":null,"url":"/SecurityService/"},"message":"Inbound request start"}
{"@timestamp":"2016-04-13T15:27:24.721+01:00","@version":1,"message":"SQL query execution start","logger_name":"com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl","thread_name":"qtp1622006612-48068","level":"INFO","level_value":20000,"path":"/SecurityService/","query":"","url":"/SecurityService/","requestId":null,"operationName":"User Authentication","sessionId":null,"message":"SQL query execution start","parameters":232460,"SQL":"{call AGENCY_PORTAL_UTIL_PKG. SP_USER_LOGIN_REQUEST_RESPONSE(?, ?)}"}
{"@timestamp":"2016-04-13T15:27:24.761+01:00","@version":1,"message":"SQL query execution end","logger_name":"com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl","thread_name":"qtp1622006612-48068","level":"INFO","level_value":20000,"path":"/SecurityService/","query":"","url":"/SecurityService/","requestId":null,"operationName":"User Authentication","sessionId":null,"message":"SQL query execution end","parameters":232460,"numberOfResults":"0","SQL":"{call AGENCY_PORTAL_UTIL_PKG. SP_USER_LOGIN_REQUEST_RESPONSE(?, ?)}","elapsedTime":40}
{"@timestamp":"2016-04-13T15:27:24.766+01:00","@version":1,"message":"Forwarding to error page from request [/] due to exception [com/c4/ws/security/server/domain/ResponseUnmarshaller]","logger_name":"org.springframework.boot.context.web.ErrorPageFilter","thread_name":"qtp1622006612-48068","level":"ERROR","level_value":40000,"stack_trace":"java.lang.NoClassDefFoundError: com/c4/ws/security/server/domain/ResponseUnmarshaller\n\tat com.c4.ws.security.server.domain.UserAuthenticationServiceBean.getUserAuthenticationDetails(UserAuthenticationServiceBean.java:105) ~[classes/:na]\n\tat com.c4.ws.security.server.endpoints.UserAuthenticationServiceImpl.apAuthOperation(UserAuthenticationServiceImpl.java:40) ~[classes/:na]\n\tat sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]\n\tat java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]\n\tat org.springframework.ws.server.endpoint.MethodEndpoint.invoke(MethodEndpoint.java:134) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.endpoint.adapter.DefaultMethodEndpointAdapter.invokeInternal(DefaultMethodEndpointAdapter.java:291) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.endpoint.adapter.AbstractMethodEndpointAdapter.invoke(AbstractMethodEndpointAdapter.java:55) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.MessageDispatcher.dispatch(MessageDispatcher.java:236) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.server.MessageDispatcher.receive(MessageDispatcher.java:176) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:89) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.transport.http.WebServiceMessageReceiverHandlerAdapter.handle(WebServiceMessageReceiverHandlerAdapter.java:61) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.ws.transport.http.MessageDispatcherServlet.doService(MessageDispatcherServlet.java:293) ~[spring-ws-core-2.2.1.RELEASE.jar:2.2.1.RELEASE]\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[servlet-api-3.1.jar:3.1.0]\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) ~[na:na]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:116) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:60) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:91) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]\n\tat org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:109) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]\n\tat java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]\n","path":"/SecurityService/","query":"","url":"/SecurityService/"}
ERROR:  'Premature end of file.'

Could you please help us investigate, what might have caused this to happen suddenly.

Appreciate your help.

Thanks in advance,
Ajoy.

**Comment by joakime** [comment]
Your unmarshaller had an error java.lang.NoClassDefFoundError: com/c4/ws/security/server/domain/ResponseUnmarshaller

I don't see how this is a Jetty error?

Are you running on Unix, with jetty-distribution perhaps?
If so, make sure you don't use the system temp directory (aka `/tmp`) as many unix systems will clean up that directory periodically (which a long running webapp not appreciate)

**Comment by ajoy75** [comment]
Yes, it was running on a Linux server. Thanks for your input, will check the config and change it accordingly..
