### ISSUE TITLE
Improve MultiPartFormInputStream behavior and testing 

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5132]
**Jetty version**
9.4.31

**Java version**
All

**OS type/version**
All (with particular emphasis on Windows)

**Description**
The current implementation of MultiPartFormInputStream is messy (from years of partial improvements).

This issue is to cleanup the MultiPartFormInputStream by starting with more testing of behaviors and then general cleanup to make the code easier to maintain and understand.

**Comment by gregw** [comment]
@lachlan-roberts hasn't this already been substantially done?   We have an old impl for backwards compatibility and a new impl that is cleaned up?

**Comment by sbordet** [comment]
@lachlan-roberts please confirm this has been fixed?

**Comment by lachlan-roberts** [comment]
@sbordet We have cleaned up and improved `MultiPartInputStreamParser` to a new class `MultiPartFormInputStream`. But this issue is against the new `MultiPartFormInputStream` class. 

@joakime can you be more specific of what still needs to be cleaned up in the new impl.
