### ISSUE TITLE
How does Jetty skip multiple JAR scans

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5140]
**Jetty version**
9.4.19
**Java version**
jdk8
**Question**
How does Jetty skip multiple JAR scans，like tomcat：tomcat.util.scan.DefaultJarScanner.jarsToSkip=bcprov*.jar
Jetty started scanning incorrectly because some of the jars in our project were jar obfuscations

**Comment by janbartel** [comment]
@zhengshundong01  jetty will scan all of the jars in your WEB-INF/lib, unless you tell it not to. You do this by setting the context attribute `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern`. Here is the link to the documentation on using annotations in jetty, which discusses how to limit which jars are scanned: https://www.eclipse.org/jetty/documentation/9.4.31.v20200723/using-annotations.html
