### ISSUE TITLE
Remove Powered by Jetty in 404 And 503

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5145]
**Jetty version**
jetty-7.6.0.v20120127
**Java version**
JDK7
**Question**

![image](https://user-images.githubusercontent.com/33625419/90103946-f9cb8c00-dd75-11ea-897a-572342a14c5a.png)

Our client wants to remove this field. What should I do?

**Comment by olamy** [comment]
You must configure a different error handler look https://www.eclipse.org/jetty/documentation/current/custom-error-pages.html
hth

**Comment by janbartel** [comment]
For the 404, that means no context matched and handled the request. You need to look at Jetty's DefaultHandler, doco here: https://www.eclipse.org/jetty/documentation/9.4.31.v20200723/default-handler.html. For the 503 you can configure your own error page as olamy says, and you can also set the following property in server.ini to prevent jetty writing out the powered by message on the pages where you don't have a custom error page:  `jetty.httpConfig.sendServerVersion=false`

**Comment by joakime** [comment]
Jetty 7.x is EOL (End of Life) and unsupported, as of November 2014.

https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

Be aware of the security reports you are subject to with this unsupported version of Jetty.

https://www.eclipse.org/jetty/security-reports.html
