### ISSUE TITLE
Zero connection timeout is not supported in HTTP client with non-blocking connect

### ISSUE THREAD

**Issue by olegmoz** [eclipse/jetty.project#5150]
Jetty version: `org.eclipse.jetty:jetty-client:9.4.30.v20200611`
Java version: `1.8`
OS: `Windows 10`

I am trying to set infinite connection timeout in `HttpClient` by setting it's connection timeout to zero value. The setting does makes connection timeout infinite in blocking mode (`HttpClient.setConnectBlocking(true)`) and makes connections fail with timeout exception in non-blocking mode (`HttpClient.setConnectBlocking(true)`).

Example:
```java
HttpClient client = new HttpClient();
client.setConnectBlocking(false);
client.setConnectTimeout(0);
client.newRequest(...).send(); // fails with SocketTimeoutException()
```

The reason seems to be no special handling for zero value in `ManagedSelector.Connect` constructor, see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L892

**Comment by sbordet** [comment]
Fixed by #5151.
