### ISSUE TITLE
Does Jetty support JMS、JCA1.7?

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5163]
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
**Question**
I can't find JMS、JCA in this page：https://www.eclipse.org/jetty/documentation/current/jetty-javaee.html
Does Jetty support JMS、JCA1.7?

If yes, how should I use it?

thanks

**Comment by olamy** [comment]
Please have a look here https://www.eclipse.org/jetty/documentation/current/jndi-configuration.html#configuring-jms-queues-topics-connectionfactories
JMS, JCA are app server features so Jetty do not support this out of the box.
