### ISSUE TITLE
Servlet Serializable in Jetty

### ISSUE THREAD

**Issue by pkcs11newbie** [eclipse/jetty.project#5169]
Hello

Jetty version: 9.4.26
Java version: OpenJDK11

I have a coverity issue (CID 414118 Se: Incorrect definition of Serializable class (FB.SE_BAD_FIELD)) in our jetty embedded server application that I'm looking for help.

Excerpts of our code:
Servlet handled by jetty :

``` java
                        ServletContextHandler context = new ServletContextHandler( ServletContextHandler.SESSIONS );
                        context.setContextPath( "/" );
                        ((Server) lifeCycle).setHandler( context );
                        context.addServlet(
                            new ServletHolder( new KeyManagerServlet( keyManagerService ) ),
                            "/*" );
```

servlet code: 

``` java
public class KeyManagerServlet extends `HttpServlet`
{
        private KeyManagerService keyManagerService = null; // FB.SE_BAD_FIELD
        public KeyManagerServlet( KeyManagerService keyManagerService )
        {  ... }
}
```

I could resolve this issue by marking the field as transient. However, I would appreciate if I could get some understanding of inner working of jetty's handling of servlets, which will help me decide if I can ignore this coverity issue or add transient flag.

Thanks..

**Comment by joakime** [comment]
Ignore it.

Configure Coverity to exclude the Serializable check for anything based on `javax.servlet.GenericServlet`.

Technically, per some very old Servlet spec, the Servlet Container is allowed to passivate the Servlet object to disk.
This is never done by Jetty, and I don't think there's a modern Servlet container out there that still does this odd quirk of the Servlet spec.
It's legacy baggage, and has no value, or use, anymore.

**Comment by pkcs11newbie** [comment]
Thank you for confirming.
