### ISSUE TITLE
GzipHandler Vary head should be configurable

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5171]
**Jetty version**
9.4.31

**Description**
The current implementation of the `GzipHandler` produces a `Vary` response header.
It only has 2 possible values depending on User-Agent configuration.

* `Vary: Accept-Encoding, User-Agent` (if there are User-Agent configurations present in the GzipHandler)
* `Vary: Accept-Encoding` (if there are no User-Agent configurations present in the GzipHandler)

There has been an expressed interest in being able to configure the `Vary` header.

At minimum, the ability to turn off the `User-Agent` portion, even if the User-Agent configurations are present on the GzipHandler.

But it might make sense to just make that field entirely configurable with any value.

Perhaps even allowing a null value to mean don't produce the header at all.

**Comment by gregw** [comment]
I also wonder if it is time to just drop the default configuration to exclude MSIE6.  It is beyond wasteful to make literally billions of checks for user agent when that is only necessary to help an ancient broken browser.

I'm not sure that just lying about the user-agent pattern is the correct thing to do?

**Comment by gregw** [comment]
Alternately, in jetty-10, we could just entirely remove the User-Agent handling from GzipHandler.  Instead we could have an optional rewrite and/or customiser that removes Accept-Encoding from MSIE6.

We already have MsieSslRule, so in 10, let's replace that with MsieRule that does both the accept encoding fiddle and the ssl keep alive fiddle.   Perhaps we should then have a msie module that depends on rewrite and mixes in this rule.
