### ISSUE TITLE
Adding custom handler throws ClassNotFoundException

### ISSUE THREAD

**Issue by calvincodes** [eclipse/jetty.project#5172]
**Jetty version**
9.4.29.v20200521

**Java version**
1.8.0

**Description**

While injecting a custom handler (`extends AbstractHandler`), `--list-config` displays the handler on the classpath, but upon starting Jetty `ClassNotFoundException` is thrown.

There are two ways I have tried this.

1. Writing the handler class (`CustomHandlerWarPackaged`) in a module which is packaged as a `war`, and then passing the `target/classes` directory of this module to jetty using `--lib` parameter.
 * [`--list-config` and error details for `war` packaged run](https://github.com/calvincodes/custom-handler-jetty/tree/v1.1.original.issue#running-with-handler-written-in-war-packaged-module)
2. Writing the handler class (`CustomHandlerJarPackaged`) in a module which is packaged as a `jar`, and then copying the jar in `/lib/ext/ directory` within `jetty-base` directory.
 * [`--list-config` and error details for `jar` packaged run](https://github.com/calvincodes/custom-handler-jetty/tree/v1.1.original.issue#running-with-handler-written-in-jar-packaged-module)

Both the cases show correct config but throw exceptions on jetty startup.

Here's a [GitHub repo](https://github.com/calvincodes/custom-handler-jetty/tree/v1.1.original.issue) which reproduces both these issues. I have also added the output of `--list-config` and the error details in its README.

**Comment by lachlan-roberts** [comment]
@calvincodes your second example where you have with the jar in `jetty-base/lib/ext/`, you are not getting the `ClassNotFoundException`. You are getting an error that `Server` does not have a method called `insertHandler` which takes the type you are giving it, that method needs to take a `HandlerWrapper`. If you use `setHandler` instead it should work.

**Comment by lachlan-roberts** [comment]
And for the first example where you add to the server classpath with a `--lib` parameter, it should work if you just use 
`--lib=target/classes/` instead of `--lib=target/classes/com/github/calvincodes`.

But you will run into the same issue as the other example unless you either change `CustomHandlerJarPackaged` to extend `HandlerWrapper` or to use `Server.setHandler()` instead.

**Comment by calvincodes** [comment]
@lachlan-roberts Thanks a lot for your feedback. Your suggested changes fixed the issue and the server is starting now. I had been struggling with this for a while. Let me update my repo also with the fix.

[Suggest]: I could not find proper examples of creating and injecting such a custom handler via XML. It would be great to have them. (I would love to contribute to creating these examples.)

**Comment by lachlan-roberts** [comment]
@calvincodes glad to help, I will go ahead and close this this issue if it is working now.

If you wanted to open a PR to improve the documentation around adding custom handlers with XML it would be welcome. It seems a new section in [writing-custom-handler.adoc](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-documentation/src/main/asciidoc/development/handlers/writing-custom-handlers.adoc) would be a good place for it.
