### ISSUE TITLE
Packaging a Jetty app as an uber-jar in production: recommended or not?

### ISSUE THREAD

**Issue by hariso** [eclipse/jetty.project#520]
Hi everyone!

First off: thanks for this uber-great project!

The [docs](http://www.eclipse.org/jetty/documentation/current/runner.html) mention a way of running a Jetty app, without a Jetty installation, by using a command like `java -jar jetty-runner.jar simple.war`. Even though it is possible to package a Jetty app as a uber-jar, using maven-shade-plugin, it is not mentioned in the docs. Does it mean it's not recommended for a reason or there is not special reason for that?

Thanks!

Haris

**Comment by jmcc0nn3ll** [comment]
It is a fine way to do it, we just have never put together documentation on it since the usage and needs varies so wildly. 

I am in the process of moving the documentation into this repo so it is closer and more bound to the code itself and we would be happy to review documentation along these lines!

**Comment by hariso** [comment]
Thanks a lot, I look forward to seeing it, and possibly contributing!

**Comment by joakime** [comment]
There are 2 uber-jar approaches we've created examples for.

 * [jetty-project/embedded-jetty-live-war](https://github.com/jetty-project/embedded-jetty-live-war) - building a WAR file that is self-executable and deployable into a container.
 * [jetty-project/embedded-jetty-uber-jar](https://github.com/jetty-project/embedded-jetty-uber-jar) - building a single JAR with the contents needed to run Jetty and your webapp.
