### ISSUE TITLE
Does Jetty support Double certificates?

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5207]
**Jetty version**
9.4.19.v20190610
**Java version**
JDK8
**Question**
Does Jetty support Double certificates?

Dual certificate refers to signing certificate and encryption certificate, not client authentication

**Comment by sbordet** [comment]
I'm afraid you have to be more specific: can you please clarify with an example what you exactly mean with "double certificates"?.

Jetty fully supports TLS, up to version 1.3.

If you need to use certificates for other things such as digital signatures and such, you have to write your own logic, which may be integrated in Jetty (for example to trigger for every request).

**Comment by sbordet** [comment]
Closing as no further details have been provided.
