### ISSUE TITLE
500 jetty responses

### ISSUE THREAD

**Issue by maugomez77** [eclipse/jetty.project#5209]
**Jetty version**
9.4.29.v20200521

**Java version**
openjdk version "11.0.5" 2019-10-15 LTS

**OS type/version**
Linux rn-aosd-d00-lapp01.rno.apple.com 3.10.0-1127.8.2.el7.x86_64 #1 SMP Wed May 13 17:48:48 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description**
My jetty is behind a load balancer.

All calls works perfectly if i hit directly one instance

But there are failing if i hit via load balancer with 500

any clue that would be the problem ?

here some logs i enable, but nothing useful there:

{
  “method” = “javaLogback”;
  “name” = “org.eclipse.jetty”;
  “level” = “DEBUG”;
}

**Comment by maugomez77** [comment]
What other info is required here @joakime ?

**Comment by joakime** [comment]
There's not enough information to troubleshoot this.

Who are you getting the 500 from?
The load balancer? 
If so, then it's likely a misconfiguration on your load balancer.

Or the Jetty instance?
Then your logs and HTTP responses will tell you why.

**Comment by maugomez77** [comment]
but how can i debug the method that the load balancer is sending back to jetty?.

previous binary with jetty works perfectly, new binary does not work, how can i see the debug level from jetty as a start point ?

**Comment by maugomez77** [comment]
17.150.217.226 - - [27/Aug/2020:12:12:33 -0700] "GET /8021/fragment/v1/retrieveFragmentKeysForVersion?version=test-impl HTTP/1.1" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"


that from nginx reporting 500, logs in jetty does not show anything

**Comment by joakime** [comment]
If the logs in Jetty do not show anything, then it's likely that the request never even reached Jetty.
Do the access/request logs on Jetty even show a request being processed?

**Comment by joakime** [comment]
Might want to look into the "upstream logs" on nginx as well.

https://www.nginx.com/blog/logging-upstream-nginx-traffic-cdn77/
