### ISSUE TITLE
Servlet HEAD doesn't support content-length over Integer.MAX_VALUE

### ISSUE THREAD

**Issue by ebremer** [eclipse/jetty.project#5214]
9.4.31.v20200723

(build 11.0.8+10-jvmci-20.2-b03

Windows 10

When doing a HEAD request to retrieve file size using Jetty, anything one byte or more over 2^31 returns Content-Length: 0.

**Comment by gregw** [comment]
Can your server serve that resource if it is a GET request?   Does it return with a content-length or chunked or connection:close ?

**Comment by ebremer** [comment]
It works when doing a GET with the Content-Length being correct.

GET REQUEST
Request Headers ============================
GET /image.svs HTTP/1.1
Host: localhost:8899
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Referer: http://localhost:8899/
Cookie: JSESSIONID=node0d0en4zp25hsb6cfws341jgmx0.node0; _ga=GA1.1.2146752974.1598712787
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache


Response Headers ============================
HTTP/1.1 200 OK
Date: Mon, 31 Aug 2020 14:06:58 GMT
Last-Modified: Mon, 31 Aug 2020 13:30:15 GMT
Accept-Ranges: bytes
Content-Length: 4085552795
Server: Jetty(9.4.31.v20200723)


HEAD REQUEST
Request Headers ============================
HEAD /image.svs HTTP/1.1
Host: localhost:8899
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Referer: http://localhost:8899/
Cookie: JSESSIONID=node0d0en4zp25hsb6cfws341jgmx0.node0; _ga=GA1.1.2146752974.1598712787
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache

Response Headers ============================
HTTP/1.1 200 OK
Date: Mon, 31 Aug 2020 14:11:00 GMT
Last-Modified: Mon, 31 Aug 2020 13:30:15 GMT
Accept-Ranges: bytes
Content-Length: 0
Server: Jetty(9.4.31.v20200723)

**Comment by joakime** [comment]
Just tested this on Linux.

It fails on Linux as well. for 4GB and 10GB files from DefaultServlet. (See commit 116871362bf41115bda3522d244112d5dae2fba1)
Looking into it.

**Comment by joakime** [comment]
This is a bug in the servlet-api layer.

When the HEAD request arrives to `javax.servlet.http.HttpServlet.service(HttpServletRequest, HttpServletResponse)` the servlet API will create a
`javax.servlet.http.HttpServlet$NoResponseBody` (HttpServletResponseWrapper) to handle this request.
But that implementation is limited to `int` values on Content-Length.

@gregw the branch `jetty-9.4.x-5214-head-huge-static` has the testcase that can repllicate.

Do we want to fork/fix the servlet-api?
Or handle HEAD requests entirely within the Jetty layer now?

**Comment by joakime** [comment]
Opened PR #5215

**Comment by ebremer** [comment]
tested with PR for jetty-9.4.x-5214-head-huge-static and it works!

**Comment by joakime** [comment]
@ebremer great news!  thanks for the feedback.

**Comment by joakime** [comment]
PR #5215 merged.
