### ISSUE TITLE
Review RoundRobinConnectionPool

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5217]
**Jetty version**
9.4.x

**Description**
With the work of #4975 and #5147 `RoundRobinConnectionPool` has received some attention, but could be improved.

Add javadocs and describe the peculiar behavior of round robin in detail.
Make tests less likely to fail.

**Comment by gregw** [comment]
Repoen for #5218

**Comment by joakime** [comment]
PR #5218 merged.
