### ISSUE TITLE
WebSocket documentation in Jetty 10

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#5229]
**Jetty version**
10.0.x

**Description**
Write the documentation for websocket in jetty-10.

This should be split into different sections for each API.

- Client
    - Jetty
    - Javax
    - Core

- Server
    - Jetty
    - Javax
    - Core

**Comment by jflebeau** [comment]
Any eta?

**Comment by lachlan-roberts** [comment]
@jflebeau in the 10.0.x branch we now have:
- Operations Guide documentation for websocket
- Programming Guide for the websocket client.
- Migration guide for websocket for Jetty 9.4 -> 10

The websocket server section of the programming guide is still a work in progress. However you can find out what you need to know by looking at the 9.4 documentation and then the migration guide.

You wont be able to see the documentation at https://www.eclipse.org/jetty/documentation until the `10.0.3` release is out, this should be released in the next few days.

If you want to see the documentation now you can build the project with 
```
mvn clean install -DskipTests
```
and you will find the documentation at  `documentation/jetty-documentation/target/html/index.html`.
