### ISSUE TITLE
jetty distribution + jsf/myfaces: registration via .tld file

### ISSUE THREAD

**Issue by 38leinaD** [eclipse/jetty.project#5244]
Hi,
(Sorry if this is a duplicate: i tried to post on the jetty-users mailing list, but already in the past, my mail did not seem to get through.)
I am using the jetty distribution 9.4.29.v20200521 with some javaee dependencies like cdi/weld, jsf/myfaces in lib/ext.
Unfortunately, I am getting when starting my application:

java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure that you properly include all configuration settings necessary for a basic faces application and that all the necessary libs are included. Also check the logging output of your web application and your container for any exceptions!|If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.|A typical config looks like this;|<listener>|  <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>|</listener>|
	at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:305)
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:225)
	at javax.faces.webapp.FacesServlet.init(FacesServlet.java:115)
	at org.eclipse.jetty.servlet.ServletHolder$WrapperServlet.init(ServletHolder.java:1289)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:413)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)

I have read this: https://jsflive.wordpress.com/2012/08/19/jsf-2-on-jetty-8/ which basically describes the exact issue in the context of using embeeded jetty. So, when actually setting the listener of myfaces in the web.xml my application starts and all is fine. 
So, this definively gave me a hint in the right direction. But, ideally i do not want to hard-code this in my web.xml or provide an override for my web.xml.
Rather, I would like to understand better why it is failing for me, because if i read the documentation (https://www.eclipse.org/jetty/documentation/current/configuring-jsp.html#using-jsf-taglibs) it should be working without doing anything special.
I have myfaces under lib/ext, myfaces contains a .tld-file under META-INF and the .tld-file contains the <listener>..</listener> config i want.
So, my question is what could be the reason this does not just work. I also have the jsp and jstl features enabled (i can see when starting with --list-config / --list-modules that the modules are active and the jars are on the classpath).

I also enabled DEBUG level logging for org.eclipse.jetty.apache.jasper and do not see any output. I guess i would have expected output printed from here https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/apache-jsp/src/main/java/org/eclipse/jetty/apache/jsp/JettyJasperInitializer.java!?
Does this give some indication regarding the problem?

Thanks,
Daniel

**Comment by joakime** [comment]
Does your JSF implementation have a ServletContainerInitializer that it expects to be run?
If so, does your embedded-jetty code have the necessary setup to allow that ServletContainerInitializer to be found and executed?

**Comment by 38leinaD** [comment]
> Does your JSF implementation have a ServletContainerInitializer that it expects to be run?

Yes, it seems to have one: https://github.com/apache/myfaces/blob/714b0add67f4e853a9b831d4fc8250da74190d40/impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java
But, based on what i read, i was under the impression that this ServletContextListener is what needs to be invoked/registered: https://github.com/apache/myfaces/blob/714b0add67f4e853a9b831d4fc8250da74190d40/impl/src/main/java/org/apache/myfaces/webapp/StartupServletContextListener.java
And according to what i read, this normally happens via the .tld file contained in the myfaces.jar.

> If so, does your embedded-jetty code have the necessary setup to allow that ServletContainerInitializer to be found and executed?

For sure not, because i was under the impression that "self-registration" should happen based on the StartupServletContextListener. I am also not using the embeeded jetty but the distribution. So, how would i do this in the jetty distribution? Via the jetty xml? Can you provide me a hint and let me know your understanding why StartupServletContextListener is not the right way and why it does not get registered via the tld-file?

**Comment by joakime** [comment]
OK, lets start over ...
Are you having this issue with standalone `jetty-home` (or the older `jetty-distribution`)?
Or are you having this issue with embedded Jetty?

You seem to want some kind of auto-registration of the apache-myfaces components.
That's typically done with either a `ServletContainerInitializer` or a web-fragment.

Check your apache-myfaces jar files.

* For ServletContainerInitializer, look for a `META-INF/services/javax.servlet.ServletContainerInitializer` file.
* For web fragments, look for a `META-INF/web-fragment.xml` file.

If your apache-myfaces jar files don't have those files, then there's no auto-registration option setup for them, and you'll need to manually add whatever components they need/want (such as the Listener you mentioned).

If you are using embedded-jetty, then there's Jetty Configuration objects you need to ensure you have enabled, in order to have those auto-registration components kick in and do their thing.

**Comment by 38leinaD** [comment]
Ok, let me try to answer your questions:

> Are you having this issue with standalone jetty-home (or the older jetty-distribution)?

I not sure i understand what is the "standalone jetty home". I am using the jetty distribution package (org.eclipse.jetty:jetty-distribution:9.4.29.v20200521@zip); i unzip it; it is my jetty.home.

> Or are you having this issue with embedded Jetty?

No embeeded jetty.

> You seem to want some kind of auto-registration of the apache-myfaces components.
> That's typically done with either a ServletContainerInitializer or a web-fragment.

Yes, that is what i want. Again, this is basically what is described here also: https://jsflive.wordpress.com/2012/08/19/jsf-2-on-jetty-8/
According to this, it was working in the past and he resolved the issue by providing a web.xml override like this: https://github.com/jsflive/jsf-jetty-8/blob/master/src/main/jetty/override-myfaces-web.xml
But I would like to understand better why this is need or if I can get the auto-registration working again.

Maybe @tandraschko can ship in and give his opinion also.

> For ServletContainerInitializer, look for a META-INF/services/javax.servlet.ServletContainerInitializer file.
Yes, it contains such a file: https://github.com/apache/myfaces/blob/myfaces-core-module-2.2.13/impl/src/main/java/org/apache/myfaces/ee6/MyFacesContainerInitializer.java

So, you are saying this mechanism should do the "auto-registration" in jetty? Because it seems not to work.

**Comment by janbartel** [comment]
@38leinaD probably you have not told jetty that you have jar files on the container classpath that contain tlds that need to be scanned.  We do not scan every jar on the container classpath because this would take far too long, we only scan a selection of jars, as determined by the setting of the context attribute "org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern".  By default, the pattern is set to ".*/jetty-servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/org.apache.taglibs.taglibs-standard-impl-.*\.jar$". You should take a look at this page in the doco here for info on how to set the containerIncludeJarPattern attribute: https://www.eclipse.org/jetty/documentation/9.4.31.v20200723/configuring-webapps.html#container-include-jar-pattern

**Comment by tandraschko** [comment]
In MyFaces we have both: a ServletContainerInitializer and a web-fragment with the StartupServletContextListener.

**Comment by 38leinaD** [comment]
> @38leinaD probably you have not told jetty that you have jar files on the container classpath that contain tlds that need to be scanned. We do not scan every jar on the container classpath because this would take far too long, we only scan a selection of jars, as determined by the setting of the context attribute "org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern". By default, the pattern is set to "._/jetty-servlet-api-[^/]_.jar$|._/javax.servlet.jsp.jstl-._.jar$|._/org.apache.taglibs.taglibs-standard-impl-._.jar$". You should take a look at this page in the doco here for info on how to set the containerIncludeJarPattern attribute: https://www.eclipse.org/jetty/documentation/9.4.31.v20200723/configuring-webapps.html#container-include-jar-pattern

Ahhh. Now we are getting closer! I only read this page: https://www.eclipse.org/jetty/documentation/current/configuring-jsp.html#using-jstl-taglibs-for-jetty7-jetty8
And I understood it as an opt-in feature and by default it scans the whole classpath; seems like it is the opposite. I will look into it tomorrow and try it out.

Thanks!

**Comment by 38leinaD** [comment]
It is working perfectly now after i adjusted my jetty xml:

```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
<Call name="setAttribute">
        <!-- Add myfaces-impl.jar for activation of JSF -->
        <Arg>org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern</Arg>
        <Arg>./jetty-servlet-api-[^/].jar$|./javax.servlet.jsp.jstl-..jar$|./org.apache.taglibs.taglibs-standard-impl-..jar$|.*/myfaces-impl-.*.jar$</Arg>
    </Call>
</Configure>
```

Thanks,
Daniel
