### ISSUE TITLE
GzipDefaultServletTest test failures in jetty-10.0.x

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5245]
**jetty 10.0.x**

See the CI test failures for the GzipDefaultServletTest here: 
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-10.0.x-2609-add-graceperiod-filesessiondatastore/1/tests

**Comment by joakime** [comment]
Does your branch have commit feb859e0e902b950f1cbaa94f5249e86ad86746b ? (that fixed a recent GzipDefaultServletTest issue?)

**Comment by janbartel** [comment]
@joakime the branch claims to be up-to-date with head of jetty-10.0.x

**Comment by janbartel** [comment]
Issue is apparently fixed.
