### ISSUE TITLE
How to get Jetty server and Jetty client to talk on same computer without using a socket?

### ISSUE THREAD

**Issue by ebremer** [eclipse/jetty.project#5252]
**Jetty version**
Latest supported

**Java version**
Latest supported

**Question**

Is it possible to get a Jetty client and a Jetty server on the same computer to talk to each other without using a socket?  I know they will nicely over localhost and the port the Jetty server is set to listen on, but for various reasons, I would like to eliminate the socket for same-computer use.

**Comment by joakime** [comment]
The server can run a `LocalConnector` that requires you to access the LocalConnector instance and then send / receive raw bytebuffers to the container (for requests and responses).
But the client has no such mode of operation.
You could use the HttpTester facilities to create requests and parse responses.

**Comment by ebremer** [comment]
Thanks, I will try it out!

**Comment by joakime** [comment]
Take a look at the unit tests in Jetty, search for LocalConnector and HttpTester and you'll find many examples.

Example: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
