### ISSUE TITLE
Short list of Jetty modules

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5254]
**Jetty version**
10.0.x

**Description**
Would be great if users could explore what modules are available in a fresh install of Jetty:

```
java -jar $JETTY_HOME/start.jar --show-modules
```

where `--show-modules` produces a shorter output rather than the current 799 :open_mouth: lines of output, where the modules available are completely lost in the amount of other information.

The output of `--show-modules` would be something like:

```
Module: alpn 
Module: annotations 
Module: apache-jsp 
Module: apache-jstl 
Module: bytebufferpool 
Module: client 
Module: decorate 
Module: deploy 
Module: fcgi 
...
```

Maybe with a short description.

**Comment by gregw** [comment]
We already have --list-modules, which has descriptions, dependencies etc plus a filtering mechanism

**Comment by gregw** [comment]
i wouldn't object to making "show" a synonym for "list" in all our options.... plus "--add" should be the same as "--add-to-start"

**Comment by sbordet** [comment]
@gregw `--list-modules` produces 800 lines of output.

**Comment by janbartel** [comment]
I find it confusing to have both --show-xxx and --list-xxx. Also to me --show-xxx implies more detailed info than --list-xxx. How about we keep just --list-modules and either add --verbose or alternatively --quiet to change the amount of info output??

**Comment by gregw** [comment]
Then let's improve the format of `--list-modules`, with the default being more compact, perhaps leaving out the dependencies.
Maybe we then have a `--show-module=name,name,....`  that shows the full details of the given modules?

**Comment by sbordet** [comment]
Any solution would work for me.

My point is that a user would probably like to see the list of available modules to glance interesting ones: 

> oh, hey, there is a `statistics` module, and look, a `rewrite` module too!

**Comment by gregw** [comment]
OK - I'll do this one.

**Comment by gregw** [comment]
@WalkerWatch #5257 included an update to the module descriptions... but can you review them in a new PR to improve the voice of them.
