### ISSUE TITLE
Cleanup Jetty 10 Start

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5256]
**Jetty version**
10.0.0

**Description**
Some changes discussed.

1. Change `--list-modules` shows a single line for each module. (the name and the first line of description)
2. Add `--show-modules` for the full / detailed module list 
3. Deprecate `--create-startd` (show warning)
4. The behavior of `--create-startd` is set to default mode, creating files in `${jetty.base}/start.d/` by default.
5. Create new `--create-start-ini` to force older operation in `start.ini`
6. Add new `--add-modules=<name>,<name>` option (plural form)
7. The `start.d` vs `start.ini` default mode is dependent on the existence of `start.ini` (if it exists, the `--add-modules=<name>` default to adding to `start.ini`, otherwise it uses the new default of `start.d`)

**Comment by sbordet** [comment]
@gregw we have `add-modules` already in the `[jpms]` directive in a `*.mod` file.
How about `--enable-modules` instead?

**Comment by gregw** [comment]
I think we need the word `--add` in there some where to distinguish between `--module=foo` which enables module foo for this run vs `--add=foo` which persistently adds the module to the base for all future runs.  

If there is already a `--add-modules`, then I think we go with just `-add` as an abbreviation of either `--add-to-start` or `--add-to-startd`, whichever is in-use or the default.

**Comment by sbordet** [comment]
@gregw however, both in the documentation and in the output of the command:

```
INFO  : server          transitively enabled, ini template available with --add-to-start=server
INFO  : logging-jetty   transitively enabled
INFO  : http            initialized in ${jetty.base}/start.d/http.ini
INFO  : resources       transitively enabled
INFO  : threadpool      transitively enabled, ini template available with --add-to-start=threadpool
INFO  : logging/slf4j   dynamic dependency of logging-jetty
INFO  : bytebufferpool  transitively enabled, ini template available with --add-to-start=bytebufferpool
MKDIR : ${jetty.base}/resources
COPY  : ${jetty.home}/modules/logging/jetty/resources/jetty-logging.properties to ${jetty.base}/resources/jetty-logging.properties
INFO  : Base directory was modified
```
The word "enabled" is mentioned multiple times - it's exactly what we do, we enable the module permanently.

**Comment by gregw** [comment]
1. and 2. are done in #5257
