### ISSUE TITLE
Introduce jetty-home contamination warning

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5263]
**Jetty version**
10.0.x

**Description**
In light of the changes coming for Issue #5256
We should move the `home-base-warning` module (xml, and class too) into start.jar itself now.

Warn when attempting to modify the jetty-home directory.
New command line option to bypass this contamination.

**Comment by gregw** [comment]
I will implement this.  I think it is sufficient to do this when automatically creating a start.d directory.
