### ISSUE TITLE
Create demo module

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5264]
**Jetty version**
10.0.x

**Description**
In light of the changes for Issue #5256, we need to migrate the existing demo-base to a new `demo` module.

This should probably exist in the `/examples/demo-module/` directory in source control.

It might make sense to also have the individual test webapps be modules themselves that the new `demo` module just depends on.
It could make adding a test webapp for request dump only purposes quite handy.

We should review the maven coordinates of all of the test webapps, as some of them are not aligned properly.

**Comment by gregw** [comment]
We already have a `demo.mod` that configures the demo, so i think that just needs to be moved to somewhere that can be pulled into the standard modules of jetty-home and the mod file modified to pull in the webapps and config files needed either from a `demo.d` and/or from maven
