### ISSUE TITLE
WARN Ignoring eviction setting: 0

### ISSUE THREAD

**Issue by rymsha** [eclipse/jetty.project#5268]
**Jetty version**

9.4.31.v20200723

**Java version**

11

**OS type/version**

any

**Description**

When `NullSessionCacheFactory` is in use, there is always a warring in logs
> WARN  org.eclipse.jetty.server.session - Ignoring eviction setting: 0

There reason for this is that `AbstractSessionCacheFactory` (super class for `NullSessionCacheFactory`) always calls `setEvictionPolicy`
```
    @Override
    public SessionCache getSessionCache(SessionHandler handler)
    {
        SessionCache cache = newSessionCache(handler);
        cache.setEvictionPolicy(getEvictionPolicy());
```

IMO Log level should be `debug` at most.

**Comment by janbartel** [comment]
Thanks for the issue, I've raised https://github.com/eclipse/jetty.project/pull/5270

**Comment by janbartel** [comment]
Fixed, thanks.
