### ISSUE TITLE
Move async-rest webapp from examples/ to tests/test-webapps/

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5277]
**Jetty version**
10.0.x

**Description**
The `async-rest` webapp is the only one that remains under `examples/`, so it should be moved under `tests/test-webapps`.
Also, it should be deployed to Maven Central to help with the documentation (we have an example to `curl` and deploy).

**Comment by gregw** [comment]
It is an example so having it in an example directory makes sense.

I agree it should be in maven central and we should have a `demo-async-rest.mod` modules that downloads and deploys it to a jetty-base (all our demos should be deployed that way rather than with curl).

**Comment by janbartel** [comment]
Looks like async-rest is in demos and is upload to central, so I'm closing this issue.
