### ISSUE TITLE
Introduce a "work" module

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5282]
**Jetty version**
10.0.x

**Description**
The new `work` module should be introduced so that when enabled, it creates the `$JETTY_BASE/work` directory.
It needs to be explicitly enabled, because its behavior, to persist web application unpacked resources, may not be wanted.

**Comment by gregw** [comment]
Fixed by afe5044d8c313906ef62f971a9f1fc8dcce5be2c
