### ISSUE TITLE
Start property for non standard JRE versions

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#529]
The 16.04 LTS release of ubuntu comes with it's own version of the JDK:
````shell
$ java -version
openjdk version "1.8.0_03-Ubuntu"
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)
````

This breaks ALPN in the standard release as we have no matching version for it.

**Comment by sbordet** [comment]
@gregw there never was an Oracle version of JDK 8 at version `1.8.0_03`. The first available after `1.8.0` was `1.8.0_05`.

I don't see how Ubuntu picking a random tag, build OpenJDK and shipping it makes it a valid release.

At least when it is in sync with Oracle releases we know that that particular build passed the Oracle tests to make the release "blessed".

[Zulu](https://www.azul.com/products/zulu/), the other certified version of OpenJDK, follows the same tags that Oracle "blesses".

I don't think we should support these non-standard releases. Ubuntu should follow the Oracle/Zulu tags.

**Comment by gregw** [comment]
I agree it is a crazy version number, specially as it is really 8u77 and just reports as 03.

I'm not sure we are able to ignore such non standard releases.  I think we need at least a better error handling mechanism... if not a good heuristic algorithm to work out what the effective version is.

This is kind of like when IE exploder started using mozilla as it's user-agent version!!!

**Comment by gregw** [comment]
I think out assumption that we can strip off the -whatever is now wrong.  In two versions ubuntu will be 1.8.0_05-Ubuntu and when we strip, it will match the wrong openjdk version!

Blah!  what a mess!

**Comment by sbordet** [comment]
@joakime can you please verify how is the Java version named if you install OpenJDK from Fedora's RPM repository ?

IMHO we should 1) file a bug to Ubuntu to not screw the Java version, and 2) improve our error handling in case of wrong versions or linkage errors.

**Comment by joakime** [comment]
From this Fedora-23 installation:

```
$ ls -la /usr/lib/jvm/
total 28
drwxr-xr-x.  5 root root  4096 Apr 14 15:40 .
dr-xr-xr-x. 59 root root 12288 Apr 14 15:40 ..
drwxr-xr-x.  3 root root  4096 Mar 24 07:50 java-1.8.0-openjdk-1.8.0.77-1.b03.fc23.x86_64
lrwxrwxrwx.  1 root root    21 Apr 14 15:40 jre -> /etc/alternatives/jre
lrwxrwxrwx.  1 root root    27 Apr 14 15:40 jre-1.8.0 -> /etc/alternatives/jre_1.8.0
lrwxrwxrwx.  1 root root    35 Apr 14 15:40 jre-1.8.0-openjdk -> /etc/alternatives/jre_1.8.0_openjdk
lrwxrwxrwx.  1 root root    49 Mar 24 07:49 jre-1.8.0-openjdk-1.8.0.77-1.b03.fc23.x86_64 -> java-1.8.0-openjdk-1.8.0.77-1.b03.fc23.x86_64/jre
lrwxrwxrwx.  1 root root    29 Apr 14 15:40 jre-openjdk -> /etc/alternatives/jre_openjdk
```

Every one resolves as ...
```
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by gregw** [comment]
see https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1550244

**Comment by gregw** [comment]
So this looks like a ubuntu bug that will be fixed!  
However, in my testing I've noticed another issue that convert 1.8.0_03 to 1.8.0_3   I'm not entirely sure we should do that?
