### ISSUE TITLE
Programmatically set jetty-web.xml

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5290]
**Jetty version**
10.0.x

**Description**
Would be good if there is a possibility to programmatically set a Jetty context XML file that is run _after_ the processing of `web.xml`.
The use case would be for the deployer of a web application to be able to add or override `init-param`s that depend on the deployment (e.g. the host, the timezone, the geographical location, the language, etc.).

Currently this mechanism exists, but it's hardcoded to look for the `WEB-INF/jetty-web.xml` file in the `*.war`.

The idea would be to introduce `ContextHandler.setPostProcessXML(Resource r)`, with the semantic that is the resource is present, it is processed as last step in the web application configuration.

**Comment by joakime** [comment]
The DeploymentManager has a context attributes configuration that will apply the context attributes for all deployed apps.

**Comment by joakime** [comment]
> (e.g. the host, the timezone, the geographical location, the language, etc.)

Those would also be great subjects for server level JNDI configuration that the webapp just uses.

**Comment by janbartel** [comment]
@sbordet if it's just some params, then they can use an override-web.xml file to set ``<context-param>``s for them. You use `WebAppContext.setOverrideDescriptor(String) `or `WebAppContext.setOverrideDescriptors(List<String>) ` to give the location of the override-web.xml file, which is normally external to the war.
