### ISSUE TITLE
After upgrade from JDK 8.0.241 to JDK 8.0.261 Http2 client is not working. Throwing Timeout error

### ISSUE THREAD

**Issue by erstaae** [eclipse/jetty.project#5297]
Jetty version : 9.4.19

Java version :jdk 8.0.261

OS type/version :Red hat 7

Description  : After upgrade of JDK 8.0.261, our http2 client is not working. its unable to send the request and getting timeout error.
Got an exception java.util.concurrent.TimeoutException: 

Hence, we tried to upgrade jetty 9.4.28 and tried both by removing and adding alpn bootpath. only when the alpn boot path is added its working. otherwise its failing as No Client ALPN Processor.

I noticed in 9.4.28 document, it is mentioned that for 9.4.28 jetty version alpn-boot jar is not required. 
![jetty_jar_name](https://user-images.githubusercontent.com/71491090/93584298-bd1d3100-f9c2-11ea-8ca1-0d904aac138c.jpg)
please let us know your input.

**Comment by sbordet** [comment]
Read https://webtide.com/jetty-alpn-java-8u252/.

If still does not work, we need details about the error (stack traces, etc.).

**Comment by joakime** [comment]
Would recommend upgrading to 9.4.31, as 9.4.28 is subject to several security reports - https://www.eclipse.org/jetty/security-reports.html

**Comment by erstaae** [comment]
> Read https://webtide.com/jetty-alpn-java-8u252/.
> If still does not work, we need details about the error (stack traces, etc.).

**Comment by erstaae** [comment]
I tested 9.4.31 without alpn. it is working fine. I want to just know any fix has been on 9.4.28 related to it.

**Comment by sbordet** [comment]
Related to what? It turned out there was no issue at all, so you need to be more specific.

**Comment by erstaae** [comment]
In 9.4.28, i tested without alpn-boot and it is not working. But when I upgrade to 9.4.31 it is working fine. Hence I thought to ask if any changes related to alpn-boot is wne in.

**Comment by sbordet** [comment]
We thoroughly tested 9.4.28.
Nothing has changed regarding ALPN between 9.4.28 and 9.4.31.
"Not working" is not enough information, so please be more specific.
