### ISSUE TITLE
Unable to use custom threadPool in jetty 9 with jetty.xml

### ISSUE THREAD

**Issue by krasinski** [eclipse/jetty.project#530]
I'm unable to use custom thread pool in jetty9 with jetty.xml.
[Documentation](http://www.eclipse.org/jetty/documentation/current/reference-section.html#jetty-xml-set) shows example of setting threadpool manually:
```
<Configure id="server" class="org.eclipse.jetty.server.Server"> 
  <Set name="threadPool">  
    <New class="org.eclipse.jetty.util.thread.QueuedThreadPool">
      <Set name="minThreads">10</Set>
      <Set name="maxThreads">1000</Set>
    </New>
  </Set>
</Configure>
```
Setter for threadPool in org.eclipse.jetty.server.Server doesn't exist, so it doesn't work.
However - there's a constructor allowing to use own threadPool - is there a way to use it with jetty.xml configuration? I couldn't find one.

**Comment by sbordet** [comment]
```xml
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Arg name="threadpool">
    <New id="threadpool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
      <Set name="minThreads">10</Set>
      <Set name="maxThreads">1000</Set>
    </New>
  </Arg>
  ...
</Configure>
```

Note the use of `<Arg>` to specify the `Server` constructor parameter.

**Comment by krasinski** [comment]
I tried it but it didn't work because of my mistake - I was trying to call "New" before "Arg" and then feed this new object into custom threadpool by "Ref". Docs/Stacktrace didn't metion that "Arg" should be the first tag. I'll try to make some PR's to the docs of this feature in few days to make them up-to-date.
Thanks.
