### ISSUE TITLE
HTTP/2 with HttpServletRequest.getHeader("Host") returns null on Jetty 10, but a valid value on Jetty 9

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5304]
**Jetty version**
10.0.x

**Description**
If you make an HTTP/2 request, and then in your servlet you use `HttpServletRequest.getHeader("Host")` the value is null on Jetty 10.
But it returns a value on Jetty 9.

**Screenshot of Jetty 9** (notice the "Host" header in the enumerated headers)

![jetty-9-chrome-http2-authority-header](https://user-images.githubusercontent.com/191721/93797993-8fbec600-fc02-11ea-9948-ef585f1d01a8.png)

**Screenshot of Jetty 10** (no "Host" header in the enumerated headers)

![jetty-10-chrome-http2-authority-header](https://user-images.githubusercontent.com/191721/93798013-95b4a700-fc02-11ea-82be-b53ff47bfa3a.png)

**Comment by gregw** [comment]
I don't think we should always add a Host header for HTTP/2, as that is a lot of wasted work for apps that don't use the Host header.   Instead we could either write an optional customizer and/or rewrite rule that will add a Host header from the authority of a HTTP/2 request

**Comment by joakime** [comment]
Note (to others that read this) that to get the authority from the `HttpServletRequest`, you can use the existing methods ...

* `HttpServletRequest.getServerName()`
* `HttpServletRequest.getServerPort()`

See: https://github.com/eclipse-ee4j/servlet-api/blob/4.0.4-RELEASE/api/src/main/java/javax/servlet/ServletRequest.java#L214-L228

**Comment by joakime** [comment]
We could probably improve the `HostHeaderCustomizer` to set the `Host` header too.

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/HostHeaderCustomizer.java

**Comment by joakime** [comment]
@gregw I think we should have a module to enable the `HostHeaderCustomizer` for `http2` on jetty-home.
