### ISSUE TITLE
Default jetty.*.acceptors should be 1

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5306]
**Jetty version**
10.0.x

**Description**
Given that connections are more and more persistent (due to protocols keeping them open for performance reasons), and many many cores, I think the current heuristic is too generous (up to 23 cores yields 2, up to 31 cores yields 3, more yields 4), and a fixed heuristic of `1` is plenty enough.

**Comment by gregw** [comment]
I think I'd prefer 0 to be the default so we can do async accepting.

**Comment by gregw** [comment]
I'm bumping this to 10.0.1 so we can better evaluate impacts

**Comment by sbordet** [comment]
@gregw I wrote a non-JMH benchmark, 1 selector, HTTP/1.0-style requests, with these times to complete all requests (sent sequentially in each thread):

```
0 acceptors, 8 threads, 4096 requests each, time = 1908 ms
0 acceptors, 8 threads, 4096 requests each, time = 1909 ms
0 acceptors, 8 threads, 4096 requests each, time = 1911 ms
0 acceptors, 8 threads, 4096 requests each, time = 1912 ms
0 acceptors, 8 threads, 4096 requests each, time = 1913 ms
0 acceptors, 8 threads, 4096 requests each, time = 1915 ms
0 acceptors, 8 threads, 4096 requests each, time = 1915 ms
0 acceptors, 8 threads, 4096 requests each, time = 1916 ms
avg selected keys = 3.310, selects = 22611

1 acceptors, 8 threads, 4096 requests each, time = 1735 ms
1 acceptors, 8 threads, 4096 requests each, time = 1742 ms
1 acceptors, 8 threads, 4096 requests each, time = 1744 ms
1 acceptors, 8 threads, 4096 requests each, time = 1744 ms
1 acceptors, 8 threads, 4096 requests each, time = 1746 ms
1 acceptors, 8 threads, 4096 requests each, time = 1748 ms
1 acceptors, 8 threads, 4096 requests each, time = 1748 ms
1 acceptors, 8 threads, 4096 requests each, time = 1753 ms
avg selected keys = 2.684, selects = 24416
```

I think `1` is a better default value, and it also keep better backwards compatibility (as we are currently using a non-zero value).
We are going to block just 1 thread (the acceptor thread), so no big issues there.

If people prefer non-blocking accepts, it is possible to configure `0`.
