### ISSUE TITLE
Extract httpConfig and scheduler configuration out of jetty.xml

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5308]
**Jetty version**
10.0.x

**Description**
I guess for historical reasons, `jetty.xml` contains `HttpConfiguration` configuration, which should instead be factored out into its own module.

Similarly, the scheduler configuration should be factored out, like it has already been done for the thread pool and the bytebuffer pool.

**Comment by gregw** [comment]
@sbordet I bumped this to 12.1 (but we should still hurry to do this soon)

**Comment by sbordet** [comment]
Completed by #12594.
