### ISSUE TITLE
Websocket connection closes with closure code 1011 and closure reason EoFException

### ISSUE THREAD

**Issue by bala-sundhar** [eclipse/jetty.project#5314]
**Jetty version**
9.4.31.v20200723 (Recently upgraded from 9.4.6.v20170531)

**Java version**
openjdk version "1.8.0_265"

**Question**
We are using jetty as our websocket server. Recently upgraded the version to the one mentioned above.

Sample (truncated) logs :

9/21/209:02:09.015 PM | INFO  \| 2020-09-21 21:02:09,015 \| qtp1663166483-132 \|  [WsListener::onWebSocketClose::70]    wsSessionIdentifier=gSN4v/vB/lmviGlDL75K08Obqq8=; **closureCode=1011; closureReason="EofException";** 

  | 9/21/209:02:09.015 PM | ERROR \| 2020-09-21 21:02:09,015 \| qtp1663166483-132 \|  [WsListener::onWebSocketError::146]  wsSessionIdentifier=gSN4v/vB/lmviGlDL75K08Obqq8=; errorReason="null"; \|

I have observed this during certain high load periods.

Can you help me understand this closureReason: EofException. Also, any tips on reproducing this in a development environment.

**Additional Info** : Also observed  "Too many open files" at the same time interval but not always

(Also I do not remember seeing this on the earlier version - I am not sure though)

Thanks,
Bala

**Comment by joakime** [comment]
Usually an `EofException` points to a connection that was closed.

The stacktraces would tell us more about the nature of the specific EofException you are encountering.

**Comment by lachlan-roberts** [comment]
@bala-sundhar You could get a `EofException` in the case that the underlying connection was closed before the websocket close handshake could complete. Likely that it was writing a frame at the time and `EndPoint.flush()` threw `EofException`. You can look at the stacktrace from your `onWebSocketError` method to be sure.

**Comment by lachlan-roberts** [comment]
Question answered, closing issue.
