### ISSUE TITLE
Jetty 10 build does not use `webapp_4_0.xsd` XSD declaration as found in servlet spec

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5319]
Oddly, no other web descriptor in `jetty-10.0.x` uses the correct XML intro.

From: https://javaee.github.io/servlet-spec/downloads/servlet-4.0/servlet-4_0_FINAL.pdf

``` xml
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee webapp_4_0.xsd"
version="4.0">
```

Changing this for `demo-jetty-override-web.xml` breaks things.
Lets work this out in a different PR.

_Originally posted by @joakime in https://github.com/eclipse/jetty.project/pull/5292#discussion_r493812536_

**Comment by janbartel** [comment]
The web.xml schemas have _always_ been named web-app_x_y.xsd  .... even web-app_x_y.dtd.

**Comment by gregw** [comment]
added support for the WRONG xsd coords with c26eef418cd485432f8af9a94e62553c84c5a527
