### ISSUE TITLE
Websocket - PerMessageDeflateExtension Limit to 8KBytes

### ISSUE THREAD

**Issue by Marco85Li** [eclipse/jetty.project#533]
Hi all,

I'm using CometD through web socket connections and on Google Chrome I can see that frames larger than 8 KB are truncated (I used the network debug tool of Chrome to analyze the content of the decompressed frames).
I configured ws.maxMessageSize to 1 MB to stress this case.
The same configuration doesn't create any problem on Internet Explorer or using the Java client.

Disabling server side PerMessageDeflateExtension all works perfectly.

I investigated a bit in the Jetty PerMessageDeflateExtension (CompressExtension) code and I found several buffers limited to 8 KB.
Can this be the root cause of the issue that I'm experiencing?

I'm using a branch based on Jetty 9.3.7: https://github.com/eclipse/jetty.project/tree/bugs/388
Chrome version 49.0.2623.112 m

Marco

**Comment by joakime** [comment]
Use official Jetty 9.3.7 or Jetty 9.3.8, don't use that [bugs/388](https://github.com/eclipse/jetty.project/tree/bugs/388) branch.

**Comment by tbartley** [comment]
I'm seeing this as well. I'm yet to identifier a reliable set of reproduction steps for it. Initially I thought it was the per message deflate extension too - taking it out of the picture seemed to resolve it - but then turns out we were still seeing it even with permessage-deflate disabled.

The way this seems to manifest for us is that we send messages from server to client and the client sees them truncated at some multiple of 8k. Fortunately we had a kind of chunking protocol of our own above the websocket so we wound down our chunk size to < 8k and that seems to have worked around the issue.

I'm under a bit of deadline pressure at the moment but hope to spend some time next week hopefully getting a reliable reproduction. I'm running 9.3.11.

**Comment by joakime** [comment]
HTTP/1.1 chunking has nothing to do with WebSocket.

Are you talking about WebSocket fragmentation?
If so, how are you controlling that with the Jetty WebSocket API (or JSR356 API)?

**Comment by tbartley** [comment]
Sorry for the confusion. We are performing our own chunking above the websocket layer.

**Comment by joakime** [comment]
The only API with a limited amount of control of the websocket fragmentation is the partial send/receive APIs.

Note: the JSR356 spec states that the implementation is ultimately in control of the fragmentation, even those APIs have no guarantee for controlling the fragmentation.

But if you have any websocket extensions active, you no longer have fragmentation control.
The extensions are free to aggregate / fragment the to suit the needs of the extension.

In the future, when WebSocket over HTTP/2 is a reality, the fragmentation is controlled by the HTTP/2 protocol and its window updates / flow control, you will have no control over it.

The efforts you have made to control this fragmentation are short lived at best.

**Comment by tbartley** [comment]
But I need to send messages larger than max message size (which I am currently setting to 8000 to work around this issue)?

There seems to be no alternative to having higher level fragmentation of payloads since browsers appear not support sending/receiving partial messages? And I need to talk to browsers.

Maybe I'm misunderstanding something. If there is an alternative I would be delighted to discover it, believe me.

**Comment by joakime** [comment]
A websocket message is 1..n frames.
How the frames are split is called the fragmentation of a message.
A frame has a size limit, which is massive, but a message does not.

@oberstet on stackoverflow has [a splendid explanation of this].(http://stackoverflow.com/a/13011241/775715)

A message of 8k isn't that remarkable.

We have testcases that send 40MB messages (as single frames, a handful of frames, lots of small frames, lots of varying frame sizes, many frames with interspersed control frames, etc)

We pass the entire industry standard [autobahn websocket testsuite](http://autobahn.ws/testsuite/) (we test all 4 websocket components in websocket: jetty native websocket client, jetty jsr356 client, jetty native websocket server, and jetty jsr356 server)

**Comment by joakime** [comment]
Sending / Receiving whole messages at 8k should be easy for a browser to handle.

Browser very much support receiving highly fragmented websocket messages, that's part of the websocket spec (and we have manual tests we use to exercise this concept on any browser of our choice).

The WebSocket API on the browser, on the other hand, does not support sending partial messages, nor does it support receiving partial message events.  As the API is focused on the messaging, not the protocol.

**Comment by tbartley** [comment]
So - I want to send messages larger than 8k - maybe 200k - maybe 5mb - maybe more - i don't really control it. I can't see how to do that if the max message size is only 8k. This issue aside I don't think setting max message size to 5mb (or some guess bigger than that that I hope but don't know for sure is right) is the right answer - maybe I'm wrong. Certainly I'm new to this so am happy to be educated of a better approach.

**Comment by sbordet** [comment]
@tbartley you can't control the client side (browser) regarding the max message size or the partial/splitting mechanism, so you have to implement your own protocol on top of websocket to split the message at send time and join the parts at arrival time.

You said you already have such protocol, so you should be good.

On the other hand, sending such large messages via WebSocket seems weird, certainly a bit on the  edge for a use case.
You can perhaps achieve better results if the messages can be requested via HTTP: WebSocket sends an unsolicited message to the client with an URL and then the large message is downloaded via HTTP.
If the message is not unsolicited (i.e. you send a WebSocket message that is replied with the large message), then HTTP is probably better.

If you have to send large messages from the client (browser), then use HTTP.

**Comment by jared2501** [comment]
Ran into this. An 8KB limit in 2018 is pretty unfortunate. We use websockets + protobufjs for a high performance RPC that allows server-streaming responses in both the browser and react-native. 

Considering that compression works better on larger chunks of similar data, by limiting the maximum message size with permessage-delfate enabled to 8KB is rather limiting.

**Comment by joakime** [comment]
@jared2501 permessage-deflate only use the 8k buffers for the deflate/inflate processing buffers.

For inflate (incoming frames), there's still a ByteAccumulator for collecting the decompressed buffers to form the entire message in.
Once the the entire message is collected, its delivered to your websocket endpoint as a whole message.
In these situations the various WebSocket Container and WebSocket Session configurations on max message size and max buffer size kicks in.

For deflate (outgoing frames), the 8k buffer is what the compressed contents go into, generating a data frame of websocket to be sent.
1..n frames make up a websocket message.

**Comment by joakime** [comment]
@jared2501 if you have an example / demo project that shows this 8k websocket limit (please use the latest stable Jetty release) that would be swell (also, open a new issue please).

**Comment by jared2501** [comment]
Hey @joakime, yeah I understand that a websocket message consists of 1..n frames, and according [rfc7692 s6](https://tools.ietf.org/html/rfc7692#section-6) a valid implementation should buffer frames until a full messages is availible. However, I'm seeing 8KB messages in my 67.0.3396.87 connection to my jetty 9.4.9.v20180320. When I disable permessage-deflate, I can see larger messages. I can attempt a minimal repro sometime.
