### ISSUE TITLE
org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by liwei2015cd** [eclipse/jetty.project#5355]
Jetty version: 9.4.27
Java version: 1.8
Jvm options: -Xms2048m -Xmx2048m
Description: This exception is thrown when uploading a large file： 
         org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.lang.OutOfMemoryError: Java heap space

**Comment by joakime** [comment]
Not enough information to work with.

What was your stacktrace?
What was your Multipart configuration?
What did the data look like?
