### ISSUE TITLE
jetty-documentation JXURL should point to github tagged contents, not maven XREF

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5359]
**Jetty version**
9.4.x

**Description**
Currently the jetty-documentation has references to maven xref results like this ...

``` xml
<JDURL>https://eclipse.org/jetty/javadoc/${javadoc.version}</JDURL>
<JXURL>http://download.eclipse.org/jetty/stable-9/xref</JXURL>
```

it should probably be like ...

``` xml
<JDURL>https://eclipse.org/jetty/javadoc/${javadoc.version}</JDURL>
<JXURL>https://github.com/eclipse/jetty.project/tree/${jetty.version}</JXURL>
```

**Comment by WalkerWatch** [comment]
@joakime I can't find any actual usages of this outside the pom. I think we would be safe to remove it altogether, at least in Jetty 9. @sbordet thoughts?
