### ISSUE TITLE
Unpacked web fragments aren't registered properly 

### ISSUE THREAD

**Issue by vsfalexanderpilch** [eclipse/jetty.project#536]
We're using an embedded jetty in eclipse, which picks up all the webapps and web fragments from within eclipse projects. Jetty is just run as a simple java application and the required dependencies are provided by m2e. This is working fine so far, but web fragments which are part of the workspace won't get registered. The reason probably is that those aren't packaged as a jar. Basically just the target folder gets added to the classpath.

Our workaround is to manually reregister all fragments available (see WebFragmentRegistrationConfiguration.java in sample.zip). The JettyStarter.java is in there as well and also provided for completeness.

[sample.zip](https://github.com/eclipse/jetty.project/files/242097/sample.zip)

The affected version was 9.3.9.M1

**Comment by janbartel** [comment]
@vsfalexanderpilch  can you show me a log trace with jetty logging for org.eclipse.jetty.webapp.LEVEL=DEBUG?  And also could you print out the container classpath on the log as well please.  

I have a dim memory that the eclipse classloader isn't a URLClassloader, so it wasn't possible to interrogate it for its urls ... 

According to the code, if you've set the CONTAINER_JAR_PATTERN to something that matches all of the directories in which you expect to find a META-INF/web-fragment.xml file, then we should find them, and then MetaInfConfiguration should look into them correctly - it already has code in there to handle looking into either a .jar or a plain old dir.

**Comment by janbartel** [comment]
This issue is relevant for the eclipse urlclassloader thing: https://bugs.eclipse.org/bugs/show_bug.cgi?id=342972

**Comment by janbartel** [comment]
@vsfalexanderpilch  see  http://www.eclipse.org/jetty/documentation/9.3.x/configuring-webapps.html#container-include-jar-pattern

**Comment by janbartel** [comment]
@vsfalexanderpilch do you have the info requested?

**Comment by joakime** [comment]
No information provided. closing.
