### ISSUE TITLE
Some elements do not have an origin attribute in quickstart-web.xml

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5361]
**Jetty-9.4**

o.e.j.annotations.WebListenerAnnotation class does not set the metadata origin. This means that the `origin` attribute will be skipped in quickstart-web.xml.

o.e.j.annotations.ServletAnnotation does not set the metadata origin for servlet-mappings in the annotation, thus the `origin` attribute will be missing in quickstart-web.xml.

o.e.j.annotations.FilterAnnotation does not set the metadata origin for filter-mappings in the annotation, thus the `origin` attribute will be missing in quickstart-web.xml.

**Comment by joakime** [comment]
@janbartel are you fixing this for the 9.4.32 release?

**Comment by janbartel** [comment]
@joakime no, it's not critical for 9.4.32.

**Comment by janbartel** [comment]
Some other things I'm recording here:

* Quickstart generator doesn't generate `origin` for filter-mappings at all
* Quickstart generates an `origin` only for the top-level of servlet-mappings, although technically each mapping could come from a different descriptor
* `origin` is missing from welcome-file-list
* `origin` is missing from  security-role
* `origin` missing from env-entry
* `origin` missing from session-config

**Comment by janbartel** [comment]
There are too many changes to attend to all of these in jetty-9.4. I'm just going to fix the missing `origin` for WebListener annotation, and then create another branch off jetty-10 to attend to the rest of them.

**Comment by janbartel** [comment]
See #5373 :  I'm leaving off the origin of the `session-config` element because of the confusion between programmatic/context xml origin and descriptor origin. When #5373 is resolved, maybe revisit the origin generation for quickstart.
