### ISSUE TITLE
Unable to get KeyManagerFactory instance for algorithm [SunX509] on provider [Conscrypt]

### ISSUE THREAD

**Issue by petregeorgee** [eclipse/jetty.project#5369]
**jetty-distribution-9.4.31.v20200723**

**openjdk version "11.0.8" 2020-07-14 / oracle jdk 11**

**ubuntu 20.04**

**I've run the steps described on the official jetty documentation :https://www.eclipse.org/jetty/documentation/9.4.31.v20200723/jetty-ssl-distribution.html. but with no success..

Steps to recreate:

    java -jar start.jar --create-startd --add-to-start=ssl
    java -jar start.jar --add-to-start=ssl,conscrypt
    java -jar start.jar --add-to-startd=ssl,https

Update start.d/ssl.ini with the values:

--module=ssl
jetty.ssl.host=0.0.0.0
jetty.ssl.port=8583
jetty.sslContext.keyStorePath=etc/keystore
jetty.sslContext.trustStorePath=etc/keystore
jetty.sslContext.keyStorePassword=OBF:
jetty.sslContext.keyManagerPassword=OBF:
jetty.sslContext.trustStorePassword=OBF:
 #Enable client certificate authentication.
jetty.sslContext.needClientAuth=true

For generating the keystore I followed the steps:

openssl genrsa -des3 -out jetty.key
openssl req -new -x509 -key jetty.key -out jetty.crt
keytool -keystore keystore -import -alias jetty -file jetty.crt -trustcacerts
openssl req -new -key jetty.key -out jetty.csr
openssl pkcs12 -inkey jetty.key -in jetty.crt -export -out jetty.pkcs12
keytool -importkeystore -srckeystore jetty.pkcs12 -srcstoretype PKCS12 -destkeystore keystore

As last step I've obfuscated the password and updated it into start.d/ssl.ini file.

ISSUE

I'm facing with an error which say something like

2020-09-28 13:51:46.896:INFO::main: Logging initialized @523ms to org.eclipse.jetty.util.log.StdErrLog
2020-09-28 13:51:47.387:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
2020-09-28 13:51:47.414:INFO:oejs.Server:main: jetty-9.4.31.v20200723; built: 2020-07-23T17:57:36.812Z; git: 450ba27947e13e66baa8cd1ce7e85a4461cacc1d; jvm 11.0.8+10-LTS
2020-09-28 13:51:47.460:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/jetty-distribution-9.4.31.v20200723/webapps/] at interval 1
2020-09-28 13:51:47.796:INFO:oejus.SslContextFactory:main: x509=X509@6853425f(jetty,h=[jettyhttp2sample.organicdesign.org],w=[]) for Server@5a9f4771[provider=Conscrypt,keyStore=file:///opt/jetty-distribution-9.4.31.v20200723/etc/keystore,trustStore=file:///opt/jetty-distribution-9.4.31.v20200723/etc/keystore]
**2020-09-28 13:51:47.799:INFO:oejus.SslContextFactory:main: Unable to get KeyManagerFactory instance for algorithm [SunX509] on provider [Conscrypt], using default**
2020-09-28 13:51:47.882:INFO:oejs.AbstractConnector:main: Started ServerConnector@46c1a1fc{SSL, (ssl, http/1.1)}{localhost:8443}
2020-09-28 13:51:47.886:INFO:oejs.AbstractConnector:main: Started ServerConnector@7b205dbd{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-09-28 13:51:47.887:INFO:oejs.Server:main: Started @1514ms

Unable to get KeyManagerFactory instance for algorithm [SunX509] on provider [Conscrypt], using default

How should I resolve this kind of issue? 

Thank you**

**Comment by joakime** [comment]
The `KeyManagerFactory` is created by using [`javax.net.ssl.KeyManagerFactory.getInstance(String algorithm, String provider)`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/KeyManagerFactory.html#getInstance-java.lang.String-java.lang.String-)

The `algorithm` is a String populated from using [`javax.net.ssl.KeyManagerFactory.getDefaultAlgorithm()`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/KeyManagerFactory.html#getDefaultAlgorithm--), which on your system defaults to `SunX509`.

The `provider` comes from the conscrypt libraries you are using, which on your system is `Conscrypt`.

An attempt is made to use that algorithm (`SunX509`) against the provider (`Conscrypt`) and conscrypt doesn't like it.
So the implementation makes note of this and performs a provider-less request using [`javax.net.ssl.KeyManagerFactory.getInstance(String algorithm)`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/KeyManagerFactory.html#getInstance-java.lang.String-).

The message you are getting is merely an informational message, and not a warning or error.

This fallback is valid in many alternate Provider scenarios, where the provider itself doesn't implement the algorithm, but instead relies on the JVM default implementation.

You can see this in the code ...

https://github.com/eclipse/jetty.project/blob/450ba27947e13e66baa8cd1ce7e85a4461cacc1d/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1789-L1810

**Comment by petregeorgee** [comment]
Hello Joakime, 
Thank you for your answer. In the meantime, I was able to detect the real problem. 

Setting the **jetty.sslContext.needClientAuth** to true, breaks my SSL configuration. Where should I found more information about that property and how to configure jetty in order to make it work?

**Comment by joakime** [comment]
**needClientAuth** requires your clients to send client certificates in order for the low level TLS/SSL connection to be established properly (if the client doesn't sent a client certificate, or one that isn't recognized by the server, then the connection is closed by the TLS/SSL layer in Java itself, Jetty is not involved in this decision).
