### ISSUE TITLE
How to enable websocket requests in access logs in jetty

### ISSUE THREAD

**Issue by sagarikat-26** [eclipse/jetty.project#5375]
**Jetty version**
9.4.31
**Java version**
1.8
**Question**

How do we enable websocket requests in access logs ?
i have enabled request log module in jetty but that captures  only http requests , how do i capture the wss requests in my access logs ?

**Comment by joakime** [comment]
How did you enable request logs? (there's about a dozen different ways)
If you did nothing more then just enable the `requestlog` module, that's a sufficient answer, but we really need to know this detail.

**Comment by joakime** [comment]
Also, are you asking about access logging the HTTP/1.1 GET request which upgrades to websocket? 
or something else, like the websocket framing/messaging?

**Comment by lachlan-roberts** [comment]
@sagarika-hp there is currently no equivalent of the `RequestLog` to log websocket frames/messages, you should however be able to see the HTTP/1.1 upgrade request and response in the http request log.

If you want logging about the websocket messages received you could do some logging inside your application with the websocket endpoint. 

Or it should be possible to implement this with an internal websocket extension. You can see an example of an internal extension in the 9.4.x branch with the `@frame-capture` extension. The `@` in the extension name makes it an internal extension and is not part of the upgrade negotiation and is just set by the server.  See [FrameCaptureExtension.java](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/FrameCaptureExtension.java) for an example.

**Comment by sagarikat-26** [comment]
@lachlan-roberts  this answers my question, thank you for the help .
