### ISSUE TITLE
How do Weld and Jetty integrate regarding logging? Want to set DEBUG loglevel for Weld.

### ISSUE THREAD

**Issue by 38leinaD** [eclipse/jetty.project#5376]
**Jetty version**
9.4.29.v20200521

**Java version**
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**Question**
I am using the jetty distribution and have weld 3.1.1.Final in the lib/ext folder as CDI implementation. My webapp is deployed on jetty and all is working fine in regards to CDI. I also see Weld log messages with level INFO and above in the StdErr. But i am not able to get the log-level for Weld up to Debug.

I have tried to set it like this with  no success:
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog -Dorg.jboss.weld.LEVEL=DEBUG

I have read here that Weld can be configured using jetty logging: https://weld.cdi-spec.org/documentation/#7
But it seems not to work; so i am wondering how it is supposed to work. Weld is using jboss logging internally and it can internally dispatch logging to these implementations: https://weld.cdi-spec.org/documentation/#10
There is no mention of jetty logging on there side. So, i am wondering if jetty logging is doing anything special to integrate with jboss logging. How is this supposed to work? Does jetty provide a jboss logging-compatible implementation? At least i cannot see anything like it in the jetty repo...

Maybe someone can give me a nudge in the right direction. I assume i am missing something or making a basic mistake...

Thanks,
Daniel

**Comment by 38leinaD** [comment]
I have now been able to get the DEBUG output from Weld when configuring regular java.util.logging. So, in my case, jboss logging falls back to what is listed here (https://weld.cdi-spec.org/documentation/#10) as JDK Logging.
So, my question remains: Any idea what is needed to get jboss logging use jetty logging as it's logging implementation? The weld site here hints that this should work (https://weld.cdi-spec.org/documentation/#7) but i am wondering if jetty itself actually has any facilities to integrate with jboss logging.
cc @dmlloyd

**Comment by joakime** [comment]
You need to switch Jetty to using slf4j-api (note that Jetty 10 has switched to slf4j-api and no longer has a custom logging facade).

You start by having Jetty emit to it's Slf4jLog implementation.
Which in turn sends the logging events to slf4j-api.

From there, you have several dozens configurations to choose from.

Example 1:

* Weld emits to java.util.logging
* You have jul-to-slf4j.jar present and it routes java.util.logging events slf4j-api
* You have logback (a slf4j implementation) filtering / writing events to the console (and/or file/disk).

Example 2:

* Weld emits to java.util.logging
* You have sfl4j-to-jul present that accepts slf4j-api events and writes them to java.util.logging
* You have java.util.logging setup to filter / write events to the console (and/or file/disk)

There are many options here, where you capture/route the events to a single final logging implementation / config.
This final logging implementation / config could even be log4j 1, log4j 2, something custom, etc ...

**Comment by 38leinaD** [comment]
Thanks! That makes sense. For some reason, i read the weld page as if this should work "automagically" by just doing -Dorg.jboss.weld.LEVEL=DEBUG.
I will look into it.
