### ISSUE TITLE
Better handling for wrong SNI

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5379]
**Jetty version**
9.4.x

**Description**
When the client sends a wrong SNI, and `jetty.ssl.sniHostCheck=true` Jetty should return a 400, but it returns 200.

**Comment by sbordet** [comment]
@gregw strengthening the verifications when `jetty.ssl.sniHostCheck=true` fails a few tests that use a bogus certificate that has no CN and no SAN.

I don't think we should support bogus certificates like that, so I'm for do the strengthening and fix the tests.
WDYT?

**Comment by joakime** [comment]
The 400 is returned from the SecureRequestCustomizer.  Is that present?

https://github.com/eclipse/jetty.project/blob/a76702baea01186d6349e62e4045968507e66649/jetty-server/src/main/java/org/eclipse/jetty/server/SecureRequestCustomizer.java#L246-L268

There's also a SNI check in SslContextFactory.Server

https://github.com/eclipse/jetty.project/blob/338ada6076ce454afeb10a88bc63e51dfb8c6dad/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L2146-L2158
