### ISSUE TITLE
ResourceHandler serving directory listing as json

### ISSUE THREAD

**Issue by brianfromoregon** [eclipse/jetty.project#539]
A feature request (or let me know if already possible!) for ResourceHandler to return directory listings as json instead of html to clients who request application/json.

**Comment by gregw** [comment]
It is not currently supported.

The place to look at this is the ResourceService#sendDirectory method.    It should be possible to override that method to change how directories are served... however this is only a recently added class (common to DefaultServlet and ResourceHandler), so I'm not sure we have had any use-cases that extend it yet.... so it looks like we need to provide you with a different constructor to extend it, specially in ResourceHandler.

This we will definitely do

**Comment by gregw** [comment]
I've pushed a change to the 9.4.x branch that makes the ResourceService easily pluggable in the ResourceHandler.   It would be good if you could test if this works for your requirement.

If you were using servlets, I would suggest that we used a named dispatcher for to send directory listing requests to your own content generation, but that wont work for ResourceHandler, which is simple to extend yourself.
