### ISSUE TITLE
Quickstart injects objects from a metadata-complete web fragment.

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5399]
**jetty-10**

Because when we generate a quickstart-web.xml, we lose the origin of the servlets/filters/listeners, when starting via quickstart, it is possible for a servlet/filter/listener to be injected or have its post-construct/pre-destroy listeners called from annotations even though it was originally declared in a web-fragment.xml that was metadata-complete.  Note this does not affect servlets/filters/listeners that are declared in a metadata-complete web.xml.

**Comment by janbartel** [comment]
Keep open for investigation.

**Comment by joakime** [comment]
Move to 10.0.9 release?

**Comment by janbartel** [comment]
To add more explanation to the above:

If a servlet/filter/listener is declared in a `metadata-complete` web fragment, when `quickstart-web.xml` is generated, we don't save the `metadata-complete` information for the fragment. A `quickstart-web.xml` is only `metadata-complete` if the `web.xml` is. This means that when it comes time to introspect the servlet/filter/listener for it's non-discovered annotations (eg `PostConstruct`, `PreDestroy`, `Resource` etc etc) we don't know that the object was in a `metadata-complete` fragment, so we honour any annotations found.  Note that this is only a problem if a fragment is _both_ `metadata-complete` _and_ has introspectable annotations on it's servlets/filters/listeners.
