### ISSUE TITLE
Move jetty-http-tools under the project root

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5401]
**Jetty version**
10.0.x

**Description**
`HttpTester` is a useful tool to test HTTP requests/responses.

In Jetty 9.4.x, this was available in `jetty-http` with the classifier `tests`.

In Jetty 10.0.x it's not deployed to Maven Central because it's under `$JETTY_ROOT/tests/`, but would be great if it is available again in Central for other projects such as CometD to use it.

**Comment by sbordet** [comment]
Remember to add a `module-info.java` for it, likely just `requires transitive org.eclipse.jetty.http`.

**Comment by joakime** [comment]
Opened PR #5402
