### ISSUE TITLE
How does this version customize its ErrorHandler?

### ISSUE THREAD

**Issue by daizhijie395** [eclipse/jetty.project#5414]
**Jetty version**
9.4.19.v20190610

**Java version**
jdk1.8

**Question**
How does this version customize its ErrorHandler?
https://www.eclipse.org/jetty/documentation/current/custom-error-pages.html
The method in the document is not available.
Because when creating WebAppContext, the ErrorPagErrrorHandler is created as the ErrorHandler.
public WebAppContext()
{
    this(null,null,null,null,null,new ErrorPageErrorHandler(),SESSIONS|SECURITY);
 }
Besides modifying webapp-common.xml, is there any other way to make it work?

**Comment by lachlan-roberts** [comment]
@daizhijie395 what happened when you tried the approaches described in the documentation?

You can define the error pages in `web.xml`, or configure the existing `ErrorPageErrorHandler`.

 Or you could set your own `ErrorHandler` on the `WebAppContext` in `jetty-web.xml` and configure it how you like:
```xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="errorHandler">
    <New class="com.acme.handler.MyErrorHandler"/>
  </Set>
</Configure>
```

**Comment by joakime** [comment]
If all you want is custom error pages, you don't need a custom ErrorHandler.

Just use the web descriptor (`WEB-INF/web.xml`) elements already built in to specify the behavior.

Example of how to trigger a custom dispatch on a particular response status code.

``` xml
<web-app ...>
    <error-page>
        <error-code>404</error-code>
        <location>/myerror.html</location>
    </error-page>
</web-app>
```

Based on an unhandled Throwable / Exception type

``` xml
<web-app ...>
    <error-page>
        <exception-type>java.io.IOException</exception-type>
        <location>/IOException.jsp</location>
    </error-page>
</web-app>
```

General catch all if no specific `<error-page>` is configured.

``` xml
<web-app ...>
    <error-page>
        <location>/GeneralErrorServlet</location>
    </error-page>
</web-app>
```

You can have as many `<error-page>` entries as you want.

Notice that the `<location>` can be anything that can be served by the webapp, including servlets, jsps, and even static pages.

If you decide to handle the error in your own servlet, know that you will receive a [`DispatcherType.ERROR`](https://docs.oracle.com/javaee/7/api/javax/servlet/DispatcherType.html#ERROR) dispatch (see [`HttpServletRequest.getDispatcherType()`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getDispatcherType--)), and the original request details will be contained in several [`HttpServletRequest.getAttribute(keyname)`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getAttribute-java.lang.String-) locations.

See [`RequestDispatcher.ERROR_*`](https://docs.oracle.com/javaee/7/api/javax/servlet/RequestDispatcher.html) constants for more details.
