### ISSUE TITLE
Custom Connection Pool not working after jetty upgrade

### ISSUE THREAD

**Issue by navalgoyal** [eclipse/jetty.project#5416]
**Jetty version**
9.4.31v20200723

**Java version**
Java 1.8.0_261

**OS type/version**
Any

**Description**
We have implemented Custom Connection Pool to support weight based and priority based connection pool. We have developed those custom pool in Jetty 9.4.24 version and those were working fine with that version. recently we have upgraded on jetty version 9.4.31 and now those custom pool is not working. 

I suspect this is due to changes HttpDestination class. Previously multiple threads are trying to send the request if connection pool not able to return the connection but now if a only one thread is trying to send request and if it is not able to send request than it only wait for request timeout.

I guess it should be backward compatible where custom written pool should not break.

**Comment by sbordet** [comment]
"is not working" is not enough information to help you.

Write a test case that we can reproduce and attach it here.

**Comment by navalgoyal** [comment]
``` java
public class WeightedConnectionPoolWithStreamId extends AbstractConnectionPool implements Multiplexable
{
    private final List<Entry> entries;
    private final List<Integer> connectionWeights;
    private int maxMultiplex;
    private int maxStreamsPerConnection;
    private Map<Connection, Entry> expiredConnections;
    private int maxConnections;
    private int streamsExhaustionIdleTimeout;
    private Random random = new Random();
    private final ReentrantLock lock = new ReentrantLock();

    public WeightedConnectionPoolWithStreamId(HttpDestination destination, Callback requester, int maxMultiplex,
        int maxStreamsPerConnection, List<Integer> weightsList, int streamsExhaustionIdleTimeout)
    {
        super(destination, weightsList.size(), requester);
        this.entries = new ArrayList<>(maxConnections);
        this.maxConnections = weightsList.size();
        this.expiredConnections = new HashMap<>();
        this.connectionWeights = weightsList;
        this.maxStreamsPerConnection = maxStreamsPerConnection;
        this.maxMultiplex = maxMultiplex;
        this.expiredConnections = new HashMap<>();
        this.streamsExhaustionIdleTimeout = streamsExhaustionIdleTimeout;

        Collections.sort(connectionWeights, Collections.reverseOrder());
        for (int i = 0; i < maxConnections; i++)
        {
            entries.add(new Entry(connectionWeights.get(i)));
        }
    }

    protected void lock()
    {
        lock.lock();
    }

    protected void unlock()
    {
        lock.unlock();
    }

    @ManagedAttribute (value = "The max streams per connection", readonly = true)
    public int getMaxStreamsPerConnection()
    {
        return maxStreamsPerConnection;
    }

    @ManagedAttribute (value = "The number of expired connections", readonly = true)
    public int getExpiredConnectionCount()
    {
        lock();
        try
        {
            return expiredConnections.size();
        }
        finally
        {
            unlock();
        }
    }

    @Override
    public int getMaxMultiplex()
    {
        lock();
        try
        {
            return maxMultiplex;
        }
        finally
        {
            unlock();
        }
    }

    @Override
    public void setMaxMultiplex(int maxMultiplex)
    {
        lock();
        try
        {
            this.maxMultiplex = maxMultiplex;
        }
        finally
        {
            unlock();
        }
    }

    @Override
    protected void onCreated(Connection connection)
    {
        lock();
        try
        {
            for (Entry entry : entries)
            {
                if (entry.connection == null && entry.toBeReassigned)
                {
                    entry.connection = connection;
                    entry.toBeReassigned = false;
                    break;
                }
            }
        }
        finally
        {
            unlock();
        }
        idle(connection, false);
    }

    @Override
    protected Connection activate()
    {
        Connection connection = null;
        Entry entry;
        lock();
        try
        {
            int index = 0;
            int capacity = getMaxConnectionCount();
            List<Integer> weightsListCopy = new ArrayList<>(connectionWeights);
            while (index < capacity)
            {
                int position = getConnectionPosition(weightsListCopy);
                entry = entries.get(position);

                if (entry.connection == null)
                {
                    return null;
                }
                if (entry.active < getMaxMultiplex())
                {
                    ++entry.active;
                    ++entry.used;
                    connection = entry.connection;
                    if (entry.used == maxStreamsPerConnection)
                    {
                        Entry tempEntry = new Entry(entry.weight);
                        tempEntry.connection = connection;
                        tempEntry.active = entry.active;
                        tempEntry.used = entry.used;
                        expiredConnections.put(connection, tempEntry);
                        remove(connection);
                    }
                    break;
                }
                weightsListCopy.set(position, 0);
                ++index;
            }
        }
        finally
        {
            unlock();
        }
        return connection == null ? null : active(connection);
    }

    private int getConnectionPosition(List<Integer> listOfWeights)
    {
        int sumOfWeights = listOfWeights.stream().mapToInt(Integer::intValue).sum();
        int randomInt = random.nextInt(sumOfWeights);
        int i;
        for (i = 0; i < maxConnections; i++)
        {
            if (randomInt < listOfWeights.get(i))
            {
                break;
            }
            randomInt -= listOfWeights.get(i);
        }
        return i;
    }

    @Override
    public boolean isActive(Connection connection)
    {
        lock();
        try
        {
            for (Entry entry : entries)
            {
                if (entry.connection == connection)
                {
                    return entry.active > 0;
                }
            }
            if (expiredConnections.containsKey(connection))
            {
                return expiredConnections.get(connection).active > 0;
            }
        }
        finally
        {
            unlock();
        }
        return false;
    }

    @Override
    public boolean release(Connection connection)
    {
        boolean found = false;
        boolean idle = false;
        lock();
        try
        {
            for (Entry entry : entries)
            {
                if (entry.connection == connection)
                {
                    found = true;
                    int active = --entry.active;
                    idle = active == 0;
                    break;
                }
            }

            if (!found && !expiredConnections.containsKey(connection))
            {
                return false;
            }
            if (expiredConnections.containsKey(connection))
            {
                Entry entry = expiredConnections.get(connection);
                --entry.active;
                if (entry.active == 0)
                {
                    HttpConnectionOverHTTP2 conn = (HttpConnectionOverHTTP2) connection;
                    HTTP2ClientSession http2Session = (HTTP2ClientSession) conn.getSession();
                    http2Session.getEndPoint().setIdleTimeout(streamsExhaustionIdleTimeout);
                    expiredConnections.remove(connection);
                    return true;
                }
            }
        }
        finally
        {
            unlock();
        }

        released(connection);
        if (idle)
        {
            return idle(connection, isClosed());
        }
        return true;
    }

    @Override
    public boolean remove(Connection connection)
    {
        boolean found = false;
        lock();
        try
        {
            for (Entry entry : entries)
            {
                if (entry.connection == connection)
                {
                    found = true;
                    swapConnections(entries, entry);
                    break;
                }
            }
        }
        finally
        {
            unlock();
        }
        if (found)
        {
            released(connection);
            removed(connection);
        }
        return found;
    }

    private void swapConnections(List<Entry> entriesList, Entry removedEntry)
    {
        for (int i = entriesList.indexOf(removedEntry) + 1; i < maxConnections; i++)
        {
            entriesList.get(i - 1).connection = entriesList.get(i).connection;
            entriesList.get(i - 1).used = entriesList.get(i).used;
            entriesList.get(i - 1).active = entriesList.get(i).active;
        }
        entriesList.get(maxConnections - 1).reset();
    }

    @Override
    public void dump(Appendable out, String indent) throws IOException
    {
        List<Entry> connections;
        lock();
        try
        {
            connections = new ArrayList<>(entries);
            connections.addAll(expiredConnections.values());
        }
        finally
        {
            unlock();
        }
        Dumpable.dumpObjects(out, indent, out, connections);
    }

    @Override
    public String toString()
    {
        int present = 0;
        int active = 0;
        lock();
        try
        {
            for (Entry entry : entries)
            {
                if (entry.connection != null)
                {
                    ++present;
                    if (entry.active > 0)
                        ++active;
                }
            }
        }
        finally
        {
            unlock();
        }
        return String.format("%s@%x[c=%d/%d/%d,a=%d,ex=%d]",
            getClass().getSimpleName(),
            hashCode(),
            getPendingConnectionCount(),
            present,
            getMaxConnectionCount(),
            active,
            expiredConnections.size());
    }

    private static class Entry
    {
        private Connection connection;
        private int active;
        private long used;
        private int weight;
        private boolean toBeReassigned = true;

        public Entry(int weight)
        {
            this.weight = weight;
        }

        private void reset()
        {
            connection = null;
            active = 0;
            used = 0;
            toBeReassigned = true;
        }

        @Override
        public String toString()
        {
            return String.format("{u=%d,a=%d,c=%s}", used, active, connection);
        }
    }
```

**Comment by joakime** [comment]
How do you use that code?
What do you test it against?
How do you test it?
What happens?
Do you have any stacktraces?
And debug logs?
Any details on what actually happens vs what you expect to happen?

**Comment by navalgoyal** [comment]
How do you use that code?
We configured this Connection Pool in Http2 Connection Factory

We have activities where Jetty Server is used to accept request and then we send to Jetty client which again send to another Jetty server to test this scenario.

we do send load using simulator to send traffic.

with the 9.4.24 version this code is working fine and no error observed where with the 9.4.31 same code gives error after some time. Request is getting timeout.

since this issue occurred with load test completed stack trace is not available as of now.

our analysis say previously multiple thread tries to send request if one thread is not able to send dur to connection not returned from connection then it present in the exchange and after some time another thread again get request from exchange and try to send again but now if conncetion pool not returned connection due to maxmultiplex or any other reason than it never send again and request is getting timeout after configurable time.

we have tested with 9.4.24 and it was working fine but after upgrade to 9.4.31 it is giving problem after some time.

**Comment by joakime** [comment]
It is unclear what that implementation of yours is trying to do.

Also, why are you using entries and ids and all that rigmarole?  That entire layer appears to be thread unsafe.

Perhaps you can simplify that class a great deal by using the existing "Tag" concepts.
The Request can have a "tag" object associated with it. (see `HttpRequest.setTag(Object)`)
The lookup of the connection will use the `HttpDestination` which must match the `Origin` (matching against the same tag) to find the `Connection` from the pool to use.
Many people use this "tag" feature to section off or group their requests across specific connections within a connection pool.

Also, [9.4.32.v20200930](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.32.v20200930) is available.

It contains several client and HTTP/2 related fixes.
Can you try your load test with that version?

**Comment by navalgoyal** [comment]
@joakime we want to multiple connection with the same destination. As in the current jetty implementation we have Round Robin, Multiple Connection pool we are implementing the Weighted Connection pool where we have assigned the weighted to each connection and through the Random API we calculate the weight and send the request to that connection. So that Maximum weight connection would serve more request then other available connections.

We have also implemented max stream per connection support so if any connection have served the it's maximum stream than it closes connection and new connection would be created which will come as lowest wait where existing connection swap there weights to serve the current requests. 

as current release has lot of changes related to the pool i am not sure if this algorithm will work there. 

but this code was working with 9.4.24 where not working with 9.4.31. Just looking for what has changed in between....

**Comment by joakime** [comment]
> @joakime we want to multiple connection with the same destination. As in the current jetty implementation we have Round Robin, Multiple Connection pool we are implementing the Weighted Connection pool where we have assigned the weighted to each connection and through the Random API we calculate the weight and send the request to that connection. So that Maximum weight connection would serve more request then other available connections.

Then make the HttpRequest "Tag" the weight, use an Integer.
Limit to a few numbers, like 100, 75, 50, 25, 0, and you can get the weight features you want.

> We have also implemented max stream per connection support so if any connection have served the it's maximum stream than it closes connection and new connection would be created which will come as lowest wait where existing connection swap there weights to serve the current requests.

So basically maximum number of requests per connection?  
That's built in, see PR #4975  
See: https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/client/MultiplexConnectionPool.html#setMaxUsageCount(int)

> as current release has lot of changes related to the pool i am not sure if this algorithm will work there.

Yes, as there were several important bugs related to the connection pools.  Such as improper connection establishment (eg: multiple connections established, only 1 was used).

> but this code was working with 9.4.24 where not working with 9.4.31. Just looking for what has changed in between....

That's unfortunate.

**Comment by navalgoyal** [comment]
@

> Then make the HttpRequest "Tag" the weight, use an Integer.
> Limit to a few numbers, like 100, 75, 50, 25, 0, and you can get the weight features you want.

Good if you can give some reference as we have user configurable weight for each connection. user can configure maximum 10 weights. 

e.g user can give 10,10,10,10,10,10,10,10,10,10. here maximum 10 connection would be created and each is equal weight and through random number we are choosing the connection to send request.

**Comment by navalgoyal** [comment]
@joakime Correct me if i am wrong.. Tag will be used to send Http Request when multiple destination is available but i am not sure it will also work if single destination has multiple connection and we need to choose a connection from those available connections.

**Comment by sbordet** [comment]
We have implemented usage count, so now you can use the built-in version rather than your own.

As for tags, they will create a different `HttpDestination` object with a separate `ConnectionPool`, but to the same server host and port.

I'm afraid you think weights are a good idea, but likely they are not. 

In the connection pool rework we have done, it was evident that "round-robin" is impossible to implement and it's basically no different than "random" - that's why I doubt that weights will be any different from random as well, and likely cause performance issues.

Tags are probably your best bet to implement "weights", rather than a custom connection pool.

Say you have 2 weights, `w0` and `w1` where `w1=2*w0`. Their sum must be equal to the full probability so `w0+w1=1.0`.
When you pick a random number, interval `0.0-0.33` maps to `w0` and the rest `0.33-1.0` maps to `w1`.
When you need to send a request, you pick a random number (say `0.54`), from the number you go to the tag name (in this case, `w1`), you tag the request and it will be sent by the tagged destination.

If you want to have just 1 connection per tag, you can have it so by configuring the max connections per destination.
However, be aware that you may run into performance issues if you run out of connections (or streams) for a specific tag - requests will be queued into the higher weight tag even if other tags will be free to send.

**Comment by sbordet** [comment]
@navalgoyal care to say what solution did you choose, so others may benefit from your experience? Thanks!

**Comment by navalgoyal** [comment]
@sbordet as API level calling of acquire method is changed. Now i need to implement `acquire(boolean create)` in our custom connection pool classes. as we are taking care of connection management for our algorithm so we simply call `super.acquire(true); `inside method implementation.
