### ISSUE TITLE
NPE during HttpConnection$Content.succeeded()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#543]
Investigate cause (and possibly fix) a NPE reported at Atmosphere/atmosphere#2154 which is holding up Jetty 9.3 integration at Atmosphere/atmosphere#1998

```
Caused by: java.lang.NullPointerException
    at org.eclipse.jetty.server.HttpConnection$Content.succeeded(HttpConnection.java:586)
    at org.eclipse.jetty.server.HttpInput.pollContent(HttpInput.java:205)
    at org.eclipse.jetty.server.HttpInput.nextContent(HttpInput.java:183)
    at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:145)
    at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:129)
    at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:538)
    at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:674)
    at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:480)
    at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:412)
    at org.eclipse.jetty.server.Request.extractParameters(Request.java:364)
    at org.eclipse.jetty.server.Request.getParameter(Request.java:958)
    at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)
    at com.vaadin.server.communication.ServletUIInitHandler.isUIInitRequest(ServletUIInitHandler.java:30)
```

**Comment by Artur-** [comment]
Test: https://github.com/Artur-/jetty93-npe
`mvn clean install jetty:run`
Open localhost:8080/ and refresh three times

Turns out it is unrelated to Atmosphere

Works with Jetty 9.3.1.
Broken with 9.3.2.v20150730 and newer

**Comment by joakime** [comment]
@Artur- I need an accurate stacktrace and version match, can you paste the stacktrace from the 9.3.2 failure?

**Comment by joakime** [comment]
Also note, there's been a number of bug fixes in HTTP parsing and connection handling in general showing up in Jetty 9.3.7 and 9.3.8

**Comment by joakime** [comment]
Your test project does not fail for me.

**Comment by Artur-** [comment]
Did you test with Chrome or something else? Not sure if it matters but I tested only with Chrome.

**Comment by joakime** [comment]
Used Chrome 50.0.2661.75 (64-bit), and FireFox 45.0.1

Tested on Linux Fedora-23 and OSX 10.10.5
Using Java 1.8.0_72 for server execution (it was the common version between OSX & Linux)

These combinations:
 1. OSX Chrome Client -> OSX Server
 2. OSX Chrome Client -> Linux Server
 3. OSX Firefox Client -> OSX Server
 4. OSX Firefox Client -> Linux Server
 5. Linux Chrome Client -> OSX Server
 6. Linux Chrome Client -> Linux Server
 7. Linux Firefox Client -> OSX Server
 8. Linux Firefox Client -> Linux Server

**Comment by Artur-** [comment]
So far it seems it can only be reproduced on my machine...

This is on OS X 10.11.4 (15E65) Java(TM) SE Runtime Environment (build 1.8.0-b126) and Jetty 9.3.9.M1 run from Eclipse using jetty:run. The browser does not seem to matter, used Chrome 50.0.2661.86 (64-bit)

```
Thread [qtp1798180728-19] (Suspended (exception NullPointerException))	
	owns: ArrayQueue  (id=384)	
	owns: MultiMap  (id=385)	
	HttpInput$EofContent(HttpConnection$Content).succeeded() line: 531	
	HttpInputOverHTTP(HttpInput).pollContent() line: 203	
	HttpInputOverHTTP(HttpInput).nextContent() line: 181	
	HttpInputOverHTTP(HttpInput).read(byte[], int, int) line: 143	
	HttpInputOverHTTP(HttpInput).read() line: 127	
	UrlEncoded.decodeUtf8To(InputStream, MultiMap<String>, int, int) line: 538	
	UrlEncoded.decodeTo(InputStream, MultiMap<String>, String, int, int) line: 674	
	Request.extractFormParameters(MultiMap<String>) line: 479	
	Request.extractContentParameters() line: 411	
	Request.extractParameters() line: 363	
	Request.getParameter(String) line: 989	
	VaadinServletRequest(ServletRequestWrapper).getParameter(String) line: 194	
	ServletUIInitHandler.isUIInitRequest(VaadinRequest) line: 28	
	VaadinServletService.requestCanCreateSession(VaadinRequest) line: 152	
	VaadinServletService(VaadinService).findOrCreateVaadinSession(VaadinRequest) line: 657	
	VaadinServletService(VaadinService).findVaadinSession(VaadinRequest) line: 527	
	VaadinServletService(VaadinService).handleRequest(VaadinRequest, VaadinResponse) line: 1403	
	HelloUI$HelloUIServlet(VaadinServlet).service(HttpServletRequest, HttpServletResponse) line: 364	
	HelloUI$HelloUIServlet(HttpServlet).service(ServletRequest, ServletResponse) line: 790	
	ServletHolder.handle(Request, ServletRequest, ServletResponse) line: 816	
	ServletHandler.doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 583	
	ServletHandler(ScopedHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 143	
	ConstraintSecurityHandler(SecurityHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 548	
	SessionHandler.doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 226	
	JettyWebAppContext(ContextHandler).doHandle(String, Request, HttpServletRequest, HttpServletResponse) line: 1114	
	ServletHandler.doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 511	
	SessionHandler.doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 185	
	JettyWebAppContext(ContextHandler).doScope(String, Request, HttpServletRequest, HttpServletResponse) line: 1048	
	JettyWebAppContext(ScopedHandler).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 141	
	ContextHandlerCollection.handle(String, Request, HttpServletRequest, HttpServletResponse) line: 213	
	HandlerCollection.handle(String, Request, HttpServletRequest, HttpServletResponse) line: 109	
	Server(HandlerWrapper).handle(String, Request, HttpServletRequest, HttpServletResponse) line: 119	
	Server.handle(HttpChannel) line: 517	
	HttpChannelOverHttp(HttpChannel).handle() line: 302	
	HttpConnection.onFillable() line: 242	
	AbstractConnection$ReadCallback.succeeded() line: 245	
	AbstractEndPoint$1(FillInterest).fillable() line: 95	
	SelectChannelEndPoint$2.run() line: 75	
	ExecuteProduceConsume.produceAndRun() line: 213	
	ExecuteProduceConsume.run() line: 147	
	QueuedThreadPool.runJob(Runnable) line: 654	
	QueuedThreadPool$3.run() line: 572	
	Thread.run() line: 744	

```

**Comment by joakime** [comment]
That stacktrace is not for Jetty 9.3.9.M1

Here's the link to [HttpInput line 531 on Jetty 9.3.9.M1](https://github.com/eclipse/jetty.project/blob/jetty-9.3.9.M1/jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java#L531)

The `HttpInput$EofContent` is derived from `HttpInput$PoisonPillContent` which is derived from `Content` which is a `Callback` (and all of those don't line up with your stacktrace's line numbers)

In Jetty 9.3.9.M1, none of those have an implementation of `succeeded()` (they are all empty methods, as `EofContent` has no success state.  An empty method cannot trigger a NPE)

Is that Java 1.8.0 (no updates?), as in the first release in 2014?

There's been many nio bugs fixed in the 1.8 series since the first release.

Can you please :

 1. Ensure you are running 1 and only 1 version of Jetty for all of your Jetty jars, then double check the version numbers.  Consider using version `9.3.8.v20160314` (as that is the most recent stable release)
 2. Upgrade your Java VM to something that isn't expired. ([Java 1.8.0-b126 expired May 15, 2014](http://www.oracle.com/technetwork/java/javase/8-relnotes-2226341.html))
 2. Capture a stacktrace again (sorry)
 3. Report back the details.

**Comment by Artur-** [comment]
Sorry, that was 9.3.2

**Comment by Artur-** [comment]
Excellent catch. For some reason I had an ancient Java version configured on the machine. Running with  the latest for Mac (build 1.8.0_91-b14) fixes the issue. Sorry for the noise, explains why nobody else could reproduce it.

**Comment by joakime** [comment]
Fair enough, closing this issue then.
