### ISSUE TITLE
ForwardingRequestCustomizer can change request.metadata even if there are no Forwarding headers present

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5437]
**Jetty version**
9.4.32.v20200930

**Description**

Originally spotted by @bentmann on commit https://github.com/eclipse/jetty.project/commit/ac42cbd1436f6a161ef03e1ca7f9c4a2bf686933#r43135647

The `ForwardingRequestCustomizer` can change request.metadata even if there are no Forwarding headers present.

The example given is a Request with ...

* No Forwarding headers.
* An absolute Request URI in the HTTP request line.  `GET https://localhost:12345`
* ForwardingRequestCustomizer impacts the proto / scheme of the request.metadata.
* SecureRequestCustomizer runs and doesn't see the correct proto / scheme and fails to run also.

**Comment by joakime** [comment]
This was addressed in the changes from PR #5419 already.

**Comment by bentmann** [comment]
> This was addressed in the changes from PR #5419 already.

Looking at said PR, I don't see how this would resolve the issue:
- https://github.com/eclipse/jetty.project/blob/c2266fdd63dea082dc83fc2ab031867d1d83ecc9/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L496 starts by setting `port = -1`
- next https://github.com/eclipse/jetty.project/blob/c2266fdd63dea082dc83fc2ab031867d1d83ecc9/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L511..L513 sets `port = requestURI.getPort()`
- and with the request port equaling the secure server port, https://github.com/eclipse/jetty.project/blob/c2266fdd63dea082dc83fc2ab031867d1d83ecc9/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L528..L531 still changes the request metadata

Nothing in the above flow is triggered by any Forwarded headers, no?

AFAICT, the additional tests in that PR are also all employing some Forwarded header, but no test cases matches the scenario from this issue.

**Comment by gregw** [comment]
@joakim I think Issues/PRs have got crossed.   
This issue will be addressed by #5445 not #5419

**Comment by joakime** [comment]
PR #5445 merged (which fixes this)
