### ISSUE TITLE
Request without Host header fails with NullPointerException in ForwardedRequestCustomizer

### ISSUE THREAD

**Issue by oyvindhorneland** [eclipse/jetty.project#5443]
**Jetty version**
9.4.32.v20200930

**Java version**
11

**OS type/version**
Red Hat Enterprise Linux Server 7

**Description**
Requests (Healthcheck probes) using HTTP/1.0 without Host header started to fail after upgrade from 9.4.31.v20200723 to 9.4.32.v20200930 with http-forwarded module enabled.

Steps to reproduce:

1. Vanilla distribution 9.4.32.v20200930.
2. Add _--module=http-forwarded_ to start.ini.
3. Start jetty.
4. _curl "http://localhost:8080/" --http1.0 -H 'Host:' -v_

Same test with 9.4.31.v20200723 does not fail.

[NPE_ForwardedRequestCustomizer.txt](https://github.com/eclipse/jetty.project/files/5370253/NPE_ForwardedRequestCustomizer.txt)

**Comment by joakime** [comment]
This kind of overlaps with #5437 ...
It's where ForwardingRequestCustomizer still does things, even though the Forwarding headers might not be present.
The failure in this specific case is due to request.metadata not being filled out by the time ForwardingRequestCustomizer runs.

**Comment by joakime** [comment]
Opened PR #5445

**Comment by joakime** [comment]
PR #5445 merged (which fixes this)

**Comment by oyvindhorneland** [comment]
Impressive! :+1:
