### ISSUE TITLE
deploy-jndi.adoc is incorrect

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5444]
**Jetty 10**

The deploy/deploy-jndi.adoc file contains incorrect information. 

>The JNDI entry must be _defined_ in the Jetty context XML file, for example:

The JNDI entry does not _need_ to be defined in a context XML file, it _can_ be defined there, or in a WEB-INF/jetty-env.xml file instead. It is a matter of preference whether you decide to put an entry in an external configuration file, or in one that is inside the webapp (although see the next point about the visibility of classes referred to by context XML files).

>Class `com.mysql.cj.jdbc.MysqlConnectionPoolDataSource` is present in the MySQL JDBC driver file, `mysql-connector-java-<version>.jar`, which must be available to the web application.
>File `mysql-connector-java-<version>.jar` must be either present in `WEB-INF/lib`, or in the Jetty server class-path.

For the example given, which is a context XML file, the jar containing the class _must_ in fact be on the server's classpath and _not_ on the webapp's classpath because at the time the context XML file is interpreted, the webapp's classpath is not computed. If the class exists only inside the webapp, you _must_  put your JNDI declaration in a WEB-INF/jetty-env.xml file which has the webapp's classpath available to it.

**Comment by sbordet** [comment]
@janbartel ok, then we need to explain before how the various overriding files work, and reference the overriding mechanism from the JNDI docs.

**Comment by janbartel** [comment]
Maybe you should just link from the deploy documentation into the jndi documentation instead?

**Comment by janbartel** [comment]
Fixed.
