### ISSUE TITLE
Parameter values of content-type headers must not be cached.

### ISSUE THREAD

**Issue by michael-simons** [eclipse/jetty.project#5446]
**Jetty version**

9.4.30.v20200611

**Java version**

JDK 11

**Question**

Given the following Java Code, simple Jetty Server, not having any handlers, but only the request log:

```java
import org.eclipse.jetty.http.HttpHeader;
import org.eclipse.jetty.http.HttpParser;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class Peng
{
    public static void main( String... a ) throws Exception
    {

        var context = new ServletContextHandler( ServletContextHandler.SESSIONS );
        context.setContextPath( "/" );

        var jettyServer = new Server( 7921 );

        jettyServer.setHandler( context );
        jettyServer.setRequestLog(
                ( request, response ) -> System.out.println( "Accept reaching server " + request.getHeader( "ACCEPT" ) ) );

        try
        {
            jettyServer.start();
            var client = HttpClient.newHttpClient();
            for ( String s : new String[]{"a", "true", "A", "TRUE"} )
            {
                var accept = "application/json;foo=" + s;
                System.out.println( "With accept " + accept );
                var builder1 = HttpRequest
                        .newBuilder( URI.create( "http://localhost:7921" ) )
                        .header( "ACCEPT", accept )
                        .GET()
                        .build();
                client.send( builder1, HttpResponse.BodyHandlers.discarding() )
                      .statusCode();
             /*
                HttpHeader.CACHE.clear();
                HttpParser.CACHE.clear();
                
              */
            }
        }
        finally
        {
            jettyServer.stop();
        }
    }
}
```

I would expect the following output

```
With accept application/json;foo=a
Accept reaching server application/json;foo=a
With accept application/json;foo=true
Accept reaching server application/json;foo=true
With accept application/json;foo=A
Accept reaching server application/json;foo=A
With accept application/json;foo=TRUE
Accept reaching server application/json;foo=TRUE
```

But apparently the accept type including it's parameters are cached:

```
With accept application/json;foo=a
Accept reaching server application/json;foo=a
With accept application/json;foo=true
Accept reaching server application/json;foo=true
With accept application/json;foo=A
Accept reaching server application/json;foo=a
With accept application/json;foo=TRUE
Accept reaching server application/json;foo=true
```

While I do think that this is totally okay for type and subtype, I think it's wrong to assume that the parameters *values* are case insensitive. 

For comparison:

https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

> The type, subtype, and parameter names are not case sensitive. For example, TEXT, Text, and TeXt are all equivalent. Parameter values are normally case sensitive, but certain parameters are interpreted to be case- insensitive, depending on the intended use. 

While I could live with `TRUE` being cached as `true`, this is rather not acceptable for arbitrary strings.

**Comment by joakime** [comment]
You can turn off the various header caches with HttpCompliance features.

Here's a replacement for your Server initialization ...

``` java
System.setProperty(HttpCompliance.class.getName() + "CUSTOM0", "RFC7230,-METHOD_CASE_SENSITIVE,-FIELD_NAME_CASE_INSENSITIVE,-CASE_INSENSITIVE_FIELD_VALUE_CACHE");
var jettyServer = new Server();
var config = new HttpConfiguration();
var connectionFactory = new HttpConnectionFactory(config, HttpCompliance.CUSTOM0);
var connector = new ServerConnector(jettyServer, connectionFactory);
connector.setPort(7921);
jettyServer.addConnector(connector);
```

That means it customizes the HttpCompliance setting.

* Starts with spec `RFC7230`
* Removes the `METHOD_CASE_SENSITIVE` compliance setting. (now HTTP methods are whatever case they are sent, not forced to uppercase per spec)
* Removes the `FIELD_NAME_CASE_INSENSITIVE` compliance setting. (now similar field names with different cases are different fields, not forced to be case insensitive per spec)
* Removes the `CASE_INSENSITIVE_FIELD_VALUE_CACHE` compliance setting. (now field values are not cached to save on GC churn, not cached to be the same as the first occurrence reducing pointless String creation and GC pressure)

**Comment by michael-simons** [comment]
That is an awesome response, thank you very much.

It works for my reproducer, let's see if I can find I way to bring it into "the real thing".

**Comment by joakime** [comment]
Be aware that some of the compliance settings I mentioned cannot be changed for newer HTTP versions (like HTTP/2 or HTTP/3). (or if your request goes through an intermediary that uses that newer HTTP version, such as a proxy / firewall / load balancer / etc)

_Example: in HTTP/2 the method name MUST be upper-case, and the field-name MUST be lower-case, always, otherwise it's a malformed header resulting in an error at the protocol level._

I was curious how long this Header Value cache has been present.
It's present all the way back to Eclipse Jetty 7.0.0 (released 2009).

So I went further back.
All releases of Jetty 6 from codehaus.org have it and have it enabled by default.

Jetty 5.1.0 from mortbay (Nov 2004), Yep, it is present there, and defaulted to on.

Jetty 4.1.1 from mortbay (Sept 2002), Yep, still present there, and still defaulted to on.

The oldest copy of Jetty I have access to is Jetty 3.1.4 (released Nov 2001).
The Header Value Cache was not present then.

OK, too far back, but when was it added?
Ah! it was added in Jetty 4.1.0RC2 (released Aug 2002).
Yup, been there a while, without incident or complaint.

**Comment by michael-simons** [comment]
Haha :) No accident happened yet, but a test that I couldn't make fail as I never got the parameter in a different format into my handler.
I'm especially looking at parameter *values*. 
(And fwiw I still do think that they should be cached in a case sensitive way).

I'm doing fine with me adding a good ol' cache buster to the parameters of the accept header in my test (read `var cacheBuster = ";cacheBuster=" + ThreadLocalRandom.current().nextLong();`), I won't be able to rewrite our setup to specify the compliance class.

Edit:
I want to have `application/json;foo=a` access to parameter `foo` of the mime type that gives me `a`.
with  `application/json;foo=A` I want parameter `foo` to give me `A`.

**Comment by joakime** [comment]
In your examples 

```
Content-Type: application/json;foo=a
Content-Type: application/json;foo=A
```

Those are considered "equivalent" media types, and are not different per spec.

In fact, all of the following are equivalent.

```
Content-Type: application/json;foo=a
Content-Type: application/JSON; FOO=a
Content-Type: application/json;foo=A
Content-Type: application/json; foo=A
Content-Type: application/json; Foo=a
Content-Type: application/json;foo="A"
```

A harsh interpretation would say that you having intentionally different behavior is in a violation of the RFC7230 spec.

See: 
* https://tools.ietf.org/html/rfc7231#section-3.1.1.5 - Content-Type definition
* https://tools.ietf.org/html/rfc7231#section-3.1.1.1 - Media-Type definition

**Comment by michael-simons** [comment]
Well that's the reason I raised this more as a question, not an issue.
Anyway, in my book equals and equivalent are equivalent but not equals. And while the media type is equivalent, the parameters (or the meaning the might convey) are certainly not.

From the links you so kindly provided:

>  The type, subtype, and parameter name tokens are case-insensitive.
   Parameter values might or might not be case-sensitive, depending on
   the semantics of the parameter name.  The presence or absence of a
   parameter might be significant to the processing of a media-type,
   depending on its definition within the media type registry.

**Comment by michael-simons** [comment]
And for the funniest part in that discussion now is the fact that the value is - also in our use case - totally case insensitive but to assert that *equivalence* I must have a way to pass them through Jetty in a case sensitive way, which you kindly provided.

**Comment by janbartel** [comment]
@michael-simons from the looks of the discussion, I think your question has been answered, so I'll close the issue. Feel free to reopen if you think it's not been adequately addressed.

**Comment by michael-simons** [comment]
Thanks for asking, @janbartel. Yes, we added a good, old cache busting parameter ;)
