### ISSUE TITLE
Review HTTP2StreamEndPoint and websocket onOpen

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#5447]
The [HTTP2StreamEndPoint](https://github.com/eclipse/jetty.project/blob/jetty-10.0.0.beta2/jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java#L43) class needs to be reviewed in how it works with websocket onOpen.

The class bridged the difference between the jetty Endpoint async API (`fill` and `fillInterested` calls) to the reactive style of HTTP2 (`demand` and `onData` callback).  However the current implementation is not contained wholly withing the class, as it needs [`prepareUpgrade`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.0.beta2/jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java#L361) to do the initial demand.   Subsequent demands are done when the last demand is consumed (or soon will be when [this](https://github.com/lorban/jetty.project/commit/273213e8df4f438bf853787ec932e22424e7fe8b#diff-5985274680e408b8d59827ccd81d3358129d0a8a03fe425d516947a817826058R224) is merged).

It would be far better if all the calls to demand were handled entirely within HTTP2StreamEndPoint.  However to make that work, then WebsocketConnection would need to do a `fillInterested` call from within its `onOpen`... which apparently it does not.

**Comment by lachlan-roberts** [comment]
> It would be far better if all the calls to demand were handled entirely within HTTP2StreamEndPoint. However to make that work, then WebsocketConnection would need to do a fillInterested call from within its onOpen... which apparently it does not.

The `WebSocketConnection` will eventually do `fillInterested()` call from within its `onOpen`. It will call the `WebSocketCoreSession.onOpen` which will demand a WebSocket frame, the demand will fillAndParse, read 0 bytes and then register as fill interested.
