### ISSUE TITLE
Request error context is not reset

### ISSUE THREAD

**Issue by kh4mell** [eclipse/jetty.project#5454]
**Jetty 9.4.22.v20191022**

**Java openjdk 11.0.8 2020-07-14 LTS**

**OS CentOS Linux 7**

I'm using jetty with pax-web 7.2.14 (Karaf 4.2.8).
I created bundle fragment and registered custom error handler using jetty.xml:

```
   <Configure id="Server" class="org.eclipse.jetty.server.Server">
      ...
        <Call name="setErrorHandler">
            <Arg>
                <New class="com.company.jetty.error.handler.ServerErrorPageHandler"/>
            </Arg>
        </Call>
       ....
   </Configure>
```
In most cases it works correctly, however there is a race condition: sometimes I receive default jetty error page.

Scenario:
* Access non-existing context-path (no application registed for the context-path): `GET /applications/application/999999`

Expected:
* Error page generated by  `com.company.jetty.error.handler.ServerErrorPageHandler` is returned

Actual:
* Error page generated by `org.eclipse.jetty.servlet.ErrorPageErrorHandler` is returned.

During debugging I noticed that `org.eclipse.jetty.server.Request#_errorContext` is not null while `org.eclipse.jetty.server.Request#_context` and `org.eclipse.jetty.server.Request#_contextPath` are null. 
Path of the `_errorContext` is a random path of the one of registered applications (it's not  /applications/application/999999 but for example /platform/api).

There is no `_errorContext` cleanup in `org.eclipse.jetty.server.Request#setContext` method.

```
    public void setContext(Context context)
    {
        _newContext = _context != context;
        if (context == null)
            _context = null;
        else
        {
            _context = context;
            _errorContext = context;
        }
    }
```

Is there a defect with `_errorContext` cleanup?

**Comment by gregw** [comment]
Thanks for the report.  The issue is not a race, simply that we do not reset the errorContext when a request is recycled.   This is normally not a problem as errors frequently close the connection and thus the request is not recycled.  But it can be reused in some circumstances and I have reproduced and fixed.  PR coming....
