### ISSUE TITLE
StatisticsHandler broken for async applications

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5493]
**Jetty version**
10.0.x

**Description**
In Jetty 10, `StatisticsHandler.handle()` has a `finally` block where it flushes the response if `_shutdown != null`, which is always true (unless stopped).

This is bad because async applications get their response flushed (with all the headers) before they even get a chance to add headers.

**Comment by gregw** [comment]
The test should at least be: `if (shutdown != null && shutdown.isShutdown())`,  but I don't understand why we need the flush buffer at all... nor how this current code is not failing some test or other?

**Comment by lachlan-roberts** [comment]
Fixed with PR #5517.
