### ISSUE TITLE
Add integration test for jetty maven plugin using war overlays

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5522]
**Jetty 10.0.x**

Running a webapp (cometd) that has overlays in it with 9.4, the following list of resources representing the overlays is shown:

> 0 = {org.eclipse.jetty.util.resource.PathResource@5841} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-dojo-5_0_3-SNAPSHOT_war/WEB-INF/classes/"
> 1 = {org.eclipse.jetty.util.resource.PathResource@5849} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-jquery-5_0_3-SNAPSHOT_war/WEB-INF/classes/"
> 2 = {org.eclipse.jetty.util.resource.PathResource@5850} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-angular-5_0_3-SNAPSHOT_war/WEB-INF/classes/"
> 3 = {org.eclipse.jetty.util.resource.PathResource@5851} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-examples-dojo-5_0_3-SNAPSHOT_war/WEB-INF/classes/"
> 4 = {org.eclipse.jetty.util.resource.PathResource@5852} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-examples-jquery-5_0_3-SNAPSHOT_war/WEB-INF/classes/"
> 5 = {org.eclipse.jetty.util.resource.PathResource@5853} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-examples-angular-5_0_3-SNAPSHOT_war/WEB-INF/classes/"
> 6 = {org.eclipse.jetty.util.resource.PathResource@5854} "file:///home/simon/opensource/cometd/cometd5/cometd-demo/target/jetty_overlays/cometd-javascript-examples-vanilla-5_0_3-SNAPSHOT_war/WEB-INF/classes/"

But running with jetty-10.0.x head, there is an extra resource:

> 0 = {org.eclipse.jetty.util.resource.PathResource@6157} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/src/main/webapp/WEB-INF/classes/"
> 1 = {org.eclipse.jetty.util.resource.PathResource@6176} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-dojo-6_0_0-SNAPSHOT_war/WEB-INF/classes/"
> 2 = {org.eclipse.jetty.util.resource.PathResource@6177} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-jquery-6_0_0-SNAPSHOT_war/WEB-INF/classes/"
> 3 = {org.eclipse.jetty.util.resource.PathResource@6178} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-angular-6_0_0-SNAPSHOT_war/WEB-INF/classes/"
> 4 = {org.eclipse.jetty.util.resource.PathResource@6179} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-dojo-6_0_0-SNAPSHOT_war/WEB-INF/classes/"
> 5 = {org.eclipse.jetty.util.resource.PathResource@6180} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-jquery-6_0_0-SNAPSHOT_war/WEB-INF/classes/"
> 6 = {org.eclipse.jetty.util.resource.PathResource@6181} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-angular-6_0_0-SNAPSHOT_war/WEB-INF/classes/"
> 7 = {org.eclipse.jetty.util.resource.PathResource@6182} "file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-vanilla-6_0_0-SNAPSHOT_war/WEB-INF/classes/"

The plugin should not be looking in the `src` directory for `classes`.

**Comment by janbartel** [comment]
This is actually caused by the changes to the ResourceCollection class, that is being looked at in #5521 

I'm leaving this issue open, as we want to try and add an integration test for the jetty maven plugin that uses overlays (that tweaks the ResourceCollection changes), but are having difficulty due to the way in which the integration tests are run, and the way overlays work. Work is being done in the branch https://github.com/eclipse/jetty.project/tree/jetty-10.0.x-add-plugin-overlay-test.

I'm changing the title of this issue to reflect the work on the overlay integration test, and not the symptom that was reported of the extra resource in the ResourceCollection representing the base Resource for the webapp.

**Comment by sbordet** [comment]
@janbartel is this still an issue?
