### ISSUE TITLE
Abort HttpChannel if response has wrong content-length

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#553]
If a request handler incorrectly sets a content-length, the channel should be aborted if more or less data is actually written.

**Comment by joakime** [comment]
This applies to both over / under scenarios of actual content sent.

**Comment by joakime** [comment]
A log event (debug level?) should be present to indicate that the abort was done for this content-length mismatch reason.

**Comment by gregw** [comment]
duplicated by #1045
