### ISSUE TITLE
Consider documenting Jersey + CDI + Jetty

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse/jetty.project#5534]
**Jetty version**
9.4.33.v20201020

**Java version**
OpenJDK 12

**OS type/version**
Debian stable

**Description**
It is unclear to me how to enable both Jersey and CDI (using Weld) in a Jetty embedded configuration.

The documentation currently does not mention how to use Jersey inside a Jetty server (embedded). Of course, one could say that it is a duty of Jersey to document how to embed it into Jetty, and it is indeed very briefly mentioned in [their documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/deployment.html#d0e3345). 
But, some subtelty is involved if wanted to configure the Jetty server with more than just a basic Jersey handler.

So far I managed to get Jersey working inside Jetty with:
```
HandlerList handlers = new HandlerList();
JettyHttpContainer jerseyHandler = ContainerFactory.createContainer(JettyHttpContainer.class, new MyJaxRsApp());
handlers.addHandler(jerseyHandler);
server.setHandler(handlers);
```
(skipping another handlers that I configure alongside Jersey).

On the other hand, I have managed (with quite some help from the team here) to get Jetty to work with CDI using Weld, with a simple, old-school servlet. Everything I want works in that servlet, from @Inject to JTA @Transactional managed methods. This involves the following code:
```
servletHandler.addBean(new ServletContextHandler.Initializer(servletHandler, new CdiServletContainerInitializer()));
servletHandler.addBean(new ServletContextHandler.Initializer(servletHandler, new EnhancedListener()));
```
If possible, I’d like to leverage this and make it available to the Jersey resources as well.

Reading [their documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/cdi.support.html#cdi.support.request.scope.binding), it seems that good news awaits. If I understand it correctly, Jersey is supposed to simply behave as a servlet inside the Jetty container, and thus should happily use whatever support the Jetty container provides for @RequestScoped managed beans and CDI: “Jersey application must be deployed as a Servlet, where the underlying Servlet container has CDI integrated already and CDI container bootstrapped properly”.

BUT, the question is: how can I integrate Jersey as a normal servlet in Jetty? Or, more generally, how can I enable both Jersey and CDI in my Jetty embedded configuration?

Currently, the code I use to enable CDI (using Weld) requires a `ServletContextHandler`. My Jersey handler is a `JettyHttpContainer`, which is only an `AbstractHandler`, not a `ServletContextHandler`.

I am aware that several mechanisms are available to integrate Weld to Jetty, but it is unclear to me whether any of those is supposed to work with the Jersey handler as declared above.

Should I change the way I integrate Weld into Jetty? Should I change the way I integrate Jersey into Jetty? Both? Any help would be much appreciated.

**Comment by joakime** [comment]
> `servletHandler.addBean(....)`

If that is a raw ServletHandler, then you are doing things improperly.

> ```
> HandlerList handlers = new HandlerList();
> JettyHttpContainer jerseyHandler = ContainerFactory.createContainer(JettyHttpContainer.class, new MyJaxRsApp());
> handlers.addHandler(jerseyHandler);
> server.setHandler(handlers);
> ```

That handler would never cooperate with anything other then itself.

> The documentation currently does not mention how to use Jersey inside a Jetty server (embedded).

This is correct, and it would be out of scope for the Jetty project.
We don't generally go around documenting how to use other projects.

As an example, let me comment to this in your question ...

> Reading their documentation, it seems that good news awaits. If I understand it correctly, Jersey is supposed to simply behave as a servlet inside the Jetty container, and thus should happily use whatever support the Jetty container provides for @RequestScoped managed beans and CDI: “Jersey application must be deployed as a Servlet, where the underlying Servlet container has CDI integrated already and CDI container bootstrapped properly”.

That's not something that Jetty does.  

Jetty doesn't know about, look for, or even care about `@RequestScoped`, that is something that only Weld does.
Weld loads itself via the standard `javax.servlet.ServletContainerInitializer`, the only wrinkle when using embedded Jetty is that you have no automatic execution of `javax.servlet.ServletContainerInitializer` references, as there's no bytecode scanning, that' what your example code with the addBeans is doing, making sure that the the SCI's are being loaded)

---

Now, back to your root question.

First, create a `ServletContextHandler`, as you will need a proper `ServletContext` to tie all of this together.

Having separate ServletHandler, Weld, and Jersey is just making them not cooperate, there's nothing tying them together.
You need that `ServletContext` as the central point for everything to cooperate.

Next, resist the urge to make Jersey sit on the url-patterns of `"/"` or `"/*"`, as that effectively makes Jersey the only thing that answers all requests (normal, include, error, static resources, upgrades, etc...), as that's not what you want here.   Yes I realize all of the Jersey examples do this, but it's wrong for your use case.  choose something sane, like `"/api/*"` or `"/rest/*"` instead.

**Comment by oliviercailloux** [comment]
> We don't generally go around documenting how to use other projects.
> As an example, let me comment to this in your question ...

Thanks a lot! I think such an example might benefit many users, as I suspect Jersey + Jetty is a common case.

> If that is a raw ServletHandler, then you are doing things improperly.

`servletHander` is not a raw ServletHandler. The more complete sample is as follows. I have cut my code for clarity, but probably a bit too much, sorry.
```
ServletContextHandler servletHandler = new ServletContextHandler();
servletHandler.setContextPath("/api");
servletHandler.addServlet(ItemServlet.class, "/servlet");
```
Using this `servletHandler` (which is a `ServletContextHandler`), I am able to make Jetty cooperate with Weld to provide CDI functionality. This is tested, and works.

> That's not something that Jetty does.
> Jetty doesn't know about, look for, or even care about @RequestScoped, that is something that only Weld does.

Well, I think we agree here, I meant precisely that Jetty *plus Weld* do the job properly (thanks to the cooperation between Jetty and Weld, as mentioned above), hence me trying to make Jersey benefit from these functionalities as well.

> Having separate ServletHandler, Weld, and Jersey is just making them not cooperate, there's nothing tying them together.
> You need that ServletContext as the central point for everything to cooperate.

Sure. As mentioned, I can make Weld and Jersey cooperate (through the `ServletContextHandler servletHandler`). The missing bit is Jersey. I only know how to instanciate it using `JettyHttpContainer jerseyHandler = ContainerFactory.createContainer(JettyHttpContainer.class, new MyJaxRsApp());`, but I am unable to find how to make it interact with a `ServletContextHandler`; hence, my question. 

> Next, resist the urge to make Jersey sit on the url-patterns of "/" or "/*", as that effectively makes Jersey the only thing that answers all requests (normal, include, error, static resources, upgrades, etc...), as that's not what you want here. Yes I realize all of the Jersey examples do this, but it's wrong for your use case. choose something sane, like "/api/*" or "/rest/*" instead.

Fully agreed. This is also something I was wondering how to do, and I suppose the solution is the same as for my original question, that is, find how to integrate Jersey properly to Jetty. 

The closer I get is by reading their section [4.7.2. Servlet 3.x Container](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/deployment.html#deployment.servlet.3) and trying: `servletHandler.addServlet("io.github.oliviercailloux.jetty.MyJaxRsApp", "/test");`, but I expect this to not work as the addServlet methods generally expect a `Servlet`, and a JAX-RS Application is not a `Servlet`. Indeed, this yields `Exception in thread "main" javax.servlet.UnavailableException: Servlet class io.github.oliviercailloux.jetty.MyJaxRsApp is not a javax.servlet.Servlet`.

I agree that the examples in the Jersey documentation about integration with Jetty are quite imperfect. If someone from the Jetty project would be kind enough to point me in the right direction, that would be great.
