### ISSUE TITLE
StatisticsServlet output is not valid

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5539]
**Jetty version**
9.4.33.v20201020

**Description**
The XML produced by the StatisticsServlet is not sane.

https://github.com/eclipse/jetty.project/blob/ed1b165fa6218fb2ef1c33165796eb4f97bfc898/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/StatisticsServlet.java#L205

Should probably also support output in json at least as well.

**Comment by gregw** [comment]
I've pushed a quick fix with f21c606.
Reopen (or new issue) if you want better generation and/or json

**Comment by joakime** [comment]
Reopening, as your fix is incomplete.
There's more XML issues then the 1 line identified by this issue.
The testing for well formed XML is also not present. (which would have shown the other issues as well)

**Comment by joakime** [comment]
I have a more comprehensive fix in the works.
PR will be forthcoming.

**Comment by joakime** [comment]
Merged in PR #5560, and is available on jetty version 9.4.35.v20201120
