### ISSUE TITLE
Do not commit response before default sized buffer is filled

### ISSUE THREAD

**Issue by vobarian** [eclipse/jetty.project#554]
When `ServletResponse.setBufferSize` has *not* been called, the response may be committed before the number of bytes returned by `ServletResponse.getBufferSize` (i.e., the default buffer size) has been written. Interestingly, this appears to be correlated to how big the calls to `ServletOutputStream.write` are. The threshold appears to be 8192.

Here is a test Servlet with some sample input and output below.

```java
package test;

import java.io.IOException;
import java.io.OutputStream;
import java.util.Arrays;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/WhenCommit")
public class WhenCommit extends HttpServlet {
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		int bytesPerWrite = Integer.parseInt(req.getParameter("bytesPerWrite"));
		if (bytesPerWrite < 1 || bytesPerWrite > 100000) {
			resp.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		}

		resp.setContentType("text/plain");

		// Seems to work OK if buffer size set explicitly
		//resp.setBufferSize(resp.getBufferSize());

		System.out.println("Buffer size: " + resp.getBufferSize());

		byte[] buf = new byte[bytesPerWrite];
		Arrays.fill(buf, (byte)'a');

		OutputStream out = resp.getOutputStream();
		int written = 0;
		while (!resp.isCommitted()) {
			out.write(buf);
			written += buf.length;
		}

		System.out.println("Committed after " + written + " bytes");
	}
}
```

### Writing the response 8192 bytes per write or less works as expected:
GET http://localhost:8080/ServletTest/WhenCommit?bytesPerWrite=8192
Buffer size: 32768
Committed after 32768 bytes
GET http://localhost:8080/ServletTest/WhenCommit?bytesPerWrite=1
Buffer size: 32768
Committed after 32768 bytes
GET http://localhost:8080/ServletTest/WhenCommit?bytesPerWrite=17
Buffer size: 32768
Committed after 32776 bytes

### Writing the response above 8192 bytes per write causes the response to be committed after the first write:
GET http://localhost:8080/ServletTest/WhenCommit?bytesPerWrite=8193
Buffer size: 32768
Committed after 8193 bytes
GET http://localhost:8080/ServletTest/WhenCommit?bytesPerWrite=10000
Buffer size: 32768
Committed after 10000 bytes

Tested on jetty-9.3.8.v20160314 and jetty-9.2.10.v20150310.

**Comment by gregw** [comment]
This is by design!

If setBufferSize has not been called, then the container gives no guarantee to the application about how much data will be buffered nor when a commit may occur.

If it has not been called, jetty uses the size of the write to determine if it is worthwhile to aggregate the data (with the cost of a copy) or to write it directly and thus avoid the copy.   The heuristic we have chosen for this decision is 25% of the configured buffer size.

So if the first write is larger than configured buffer size/4, we assume that the application is doing its own buffering and there is no need to impose another aggregate buffer and copy in the output path.  The data is directly written to the lower levels of jetty saving both memory and cycles.

Does this behaviour cause a problem?  If so, the simple solution is for the application to call `setBufferSize`

**Comment by vobarian** [comment]
Thank you for explaining. It has not caused me a problem yet per se; I was just working on a content injection filter and was trying to precisely replicate the buffering behavior of the container from the client's perspective and this was unexpected.

I acknowledge that the Servlet spec does not explicitly constrain the commit behavior in relation to `getBufferSize`. It's just kind of confusing because one usually expects a get/set pair of methods to be symmetric, such that x.setX(x.getX()) is a no-op. Reading the spec and Javadoc gives the impression that there is a definite buffer size which is involved in determining when the response is committed. It could also be argued that `getBufferSize` produces a misleading return value because the spec (v. 3.1, sec. 5.1) states "If no buffering is being used, this method must return the int value of 0 (zero)." According to your description, Jetty basically hasn't decided at the beginning whether or not buffering will be used, so this scenario really isn't covered by the spec.

Anyway, I will just work around it. The spec is somewhat ambiguous, and I understand the argument for efficiency. And I assume nobody has complained about it before, so I'm fine with it being closed.
