### ISSUE TITLE
MBean name for org.eclipse.jetty.util.thread.QueuedThreadPool

### ISSUE THREAD

**Issue by annappa** [eclipse/jetty.project#5558]
**9.4.18**

**JDK 1.8**

We have configured multiple server connectors with different threadpool each with a different name. MBeans of QueuedThreadPool are getting created with the dynamic names. It has a dynamic param like context=.  Mbean name is like org.eclipse.jetty.util.thread:context=HTTP/1.1@3cbbc1e0,id=0,type=queuedthreadpool. We have requirement of mapping each MBean attribute to some metric value in an xml file. Since Mbean name is dynmic because of context value, we are not able to give the MBean name. Can someone please help us how to give some custom MBean name to QueuedThreadPool?

**Comment by sbordet** [comment]
@annappa if the tool you're using to map attributes supports querying MBeans, then you can easily exclude the context.

Rather than hitting the `ObjectName` precisely, you can use:

```java
MBeanServer.queryMBeans(new ObjectName("org.eclipse.jetty.util.thread:type=queuedthreadpool,*"), null)
```

That will return the list of thread pools registered as MBeans.

**Comment by annappa** [comment]
@sbordet Thanks for the quick reply. We are using pcp parfait tool and we are configuring MBeans in an xml file. I don't think so we have an option to mention the query. I will check on that. But can't we give some custom name to threadpool mbeans? We have given a different name to each pool using **threadPool.setName(name);**. This name is being used for thread names. Similar way, can't we give some unique name to threadpool MBean, so that we can refer it directly?

**Comment by sbordet** [comment]
Another solution would be to subclass, without changes, `QueuedThreadPool`, and then use your subclass instead of the out-of-the-box Jetty one:

```java
package com.annappa;

public class MyQueuedThreadPool extends QueuedThreadPool {
  // just the constructors
}
```

Then you create this class:

```java
package com.annappa.jmx;

public class MyQueuedThreadPoolMBean extends ObjectMBean {
   public MyQueuedThreadPoolMBean(Object object) {
    super(object);
  }

  @Override
  public ObjectName getObjectName() {
    // return the objectName you want.
  }
}
```

Note how the class is in the `*.jmx` package and has the same name as your subclass plus `MBean` at the end.
Jetty will look for this class and use it instead of the standard one.

**Comment by annappa** [comment]
@sbordet Thanks. Was able to give custom object name to  QueuedThreadPool MBeans after creating the subclasses as you suggested above.
