### ISSUE TITLE
port not getting released on jetty restart

### ISSUE THREAD

**Issue by sagarikat-26** [eclipse/jetty.project#5561]
**Jetty version**
    9.4.31v
**Java version**
1.8
**OS type/version**
linux
**Description**

we have 2 ports running, jetty comes up on port 80 and we use port 8080 for http connections used by ioreactor , During restart of jetty the java process is getting killed but the port 8080 is not getting released immediately as a result jetty comes up but the ioreactor is giving a bind exception. Is there a specific reason why jetty takes time to release the port?

**Comment by sbordet** [comment]
By your description, it's `ioreactor` that is not releasing the port, not Jetty.
