### ISSUE TITLE
How does Hibernate support Jetty JPA

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5564]
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
**Question**

How does Hibernate support Jetty JPA?

Could you please give us a demo?

**Comment by joakime** [comment]
There's no such thing as "Jetty JPA".

Jetty does not manage, make, or have a JPA provider.

Your choice of JPA provider jar, included with your webapp, determines the JPA behavior you have.

**Comment by joakime** [comment]
Also, upgrade your version of Jetty.
You are subject to several security advisories.

https://www.eclipse.org/jetty/security-reports.html

**Comment by zhengshundong01** [comment]
em...I didn't make my question clear. Our application is deployed in Jetty and USES JPA, but Jetty hasn't scanned @Persistencecontext or persistence.xml. There are no JPA packages in my application. How can I configure Jetty to support my application?

**Comment by james-z-repo** [comment]
> There's no such thing as "Jetty JPA".
> 
> Jetty does not manage, make, or have a JPA provider.
> 
> Your choice of JPA provider jar, included with your webapp, determines the JPA behavior you have.

em...I didn't make my question clear. Our application is deployed in Jetty and USES JPA, but Jetty hasn't scanned @Persistencecontext or persistence.xml. There are no JPA packages in my application. How can I configure Jetty to support my application?

**Comment by joakime** [comment]
> em...I didn't make my question clear. Our application is deployed in Jetty and USES JPA, but Jetty hasn't scanned @Persistencecontext or persistence.xml. There are no JPA packages in my application. How can I configure Jetty to support my application?

There's nothing in Jetty that is involved in setting up, using, configuring, executing, referencing, etc ... for JPA.
That's solely the responsibility of the 3rd party jars that you add to your WebApp for either JPA or CDI.

* https://github.com/eclipse/jetty.project/search?q=PersistenceContext
* https://github.com/eclipse/jetty.project/search?q=%22persistence.xml%22

The scanning for annotations in JPA (or CDI, or Hibernate, or Spring, etc..) is the responsibility of that 3rd party library, Jetty is not involved.
