### ISSUE TITLE
New Docker Hub rate limiting restrictions.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#5573]
**Description**

> Beginning November 2, 2020, progressive enforcement of rate limits for anonymous and authenticated Docker Hub usage goes into effect. This means that anonymous and free Docker Hub users will have usage restrictions gradually placed on container image pull requests.

> The rate limits will be progressively lowered to a final state of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts. Image requests exceeding these limits will be denied until the six hour window elapses.

We should review our current image rate usage to see if we are approaching the 100 limit.
https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/

If we are approaching this limit we should consider applying for the program for Open Source projects to get continued free access and freedom from restrictions for their communities and their users.
https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

**Comment by sbordet** [comment]
@lachlan-roberts I would say apply for the open source program.

**Comment by olamy** [comment]
+1 to apply
