### ISSUE TITLE
Jetty CORS filter in in JBOSS EAP 6.4 (Java 8) 

### ISSUE THREAD

**Issue by evgenysavostyanov** [eclipse/jetty.project#5577]
**Jetty version**
jetty-servlets-9.4.34.v20201102
**Java version**
8
**OS type/version**
Red Hat Linux Operating Server
**Description**

We are trying to implement the jetty CORS filter in in JBOSS EAP 6.4 (Java 8) described in this article: https://access.redhat.com/solutions/344163#comments
Does it require a module with dependencies for the jetty-servlets.jar? We tried to implement the module approach, placed the module.xml and the jar in the classpath for modules, added and packed jboss deployment structure xml in the .ear, but keep getting the ClassNotFoundException error, please see the stack trace below.

2020-11-05 15:41:26,386 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014612: Operation ("add") failed - address: ([("deployment" => "prpc_j2ee14_jboss61JBM.ear")]) - failure description: { "JBAS014671: Failed services" => {"jboss.deployment.subunit.\"prpc_j2ee14_jboss61JBM.ear\".\"prweb.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.subunit.\"prpc_j2ee14_jboss61JBM.ear\".\"prweb .war\".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of subdeployment \"prweb.war\" of deployment \"prpc_j2ee14_jboss61JBM.ear\" Caused by: java.lang.RuntimeException: JBAS018757: Error getting reflective information for class org.eclipse.jetty.servlets.CrossOriginFilter with ClassLoader ModuleClassLoader for Module \"deployment.prpc_j2ee14_jboss61JBM.ear.prwe b.war:main\" from Service Module Loader Caused by: java.lang.NoClassDefFoundError: Lorg/eclipse/jetty/util/log/Logger; Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.log.Logger from [Module \"deployment.prpc_j2ee14_jboss61JBM.ear.prweb.war:main\" from Service Module Loader]"}, "JBAS014771: Services with missing/unavailable dependencies" => [

Could you, please, provide a detailed guide how to enable the jetty CORS filter in JBOSS EAP 6.4 (Java 8) with xml files examples?

**Comment by joakime** [comment]
Yes, it would require `jetty-servlets.jar`, and `jetty-util.jar` to use as-is.

That's because it depends on the following ...

https://github.com/eclipse/jetty.project/blob/e46af88704a893fc12cb0e3bf46e2c7b48a009e7/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java#L40-L42

You might be better off just copy/pasting it into your own project, and finding alternative techniques for the StringUtil and Jetty Logging Facade.

**Comment by evgenysavostyanov** [comment]
Thank you, @joakime . We will add the dependencies to these classes in our module configuration and try again. Will provide an update once done.

**Comment by evgenysavostyanov** [comment]
I added the above mentioned jars as dependencies and the server started up successfully. However, the recent penetration test revealed that the server still accepts requests from all origins, so the filter does not work as expected. Below is the current filter configuration in web.xml on JBOSS. Please, advise on what we did wrong here.

``` xml
        <filter>
                <filter-name>cross-origin</filter-name>
                <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
        <init-param>
                <param-name>allowedOrigins</param-name>
                <param-value>*.srv.xxxxx,*.xxxxx.de.xxxxx,*.devweb.xxxxx,*.xxxxx.com</param-value>
        </init-param>
        <init-param>
                <param-name>allowedMethods</param-name>
                <param-value>*</param-value>
        </init-param>
        <init-param>
                <param-name>allowedHeaders</param-name>
                <param-value>*</param-value>
        </init-param>
        </filter>
        <filter-mapping>
                <filter-name>cross-origin</filter-name>
                <url-pattern>/*</url-pattern>
        </filter-mapping>  
```

**Comment by joakime** [comment]
Since this is a Filter, it will only produce the CORS headers on requests that go to that webapp.

Other requests, not destined for that webapp would not have those CORS headers.
It's common for penetration testing tools to use a variety of requests that can often result in requests that do not go through your webapp.

**Comment by evgenysavostyanov** [comment]
Thanks for your prompt response @joakime . To be more specific, below is the direct webapp request I just sent using OWASP ZAP tool and the response it got from the webapp, I do not see any CORS headers in it, though the pentester did get them somehow. Any further ideas or suggestions?

**Request from ZAP**
```
GET https://slaxxxxx.srv.xxxxx:15252/prweb HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:24.0) Gecko/20100101 Firefox/24.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Referer: http://example.foo/CORSexample1.html
Origin: http://example.foo
Connection: keep-alive
Content-Length: 0
Host: slaxxxxx.srv.xxxxx:15252
Cookie: Pega-RULES={atn}e3ByfWRYc1p1OTB5d3dic25HeW9lam9BRHgwWG1LWGlESU10Yy9TQ0ZuVU00UnRYbSsrL3h3V1hLTHcyQUJSVlFrcnkyNlRvdml5Qm0xMVQKczNEbUxnK1dqdz09; JSESSIONID=88zBu8b4BQzy8eYF-3NW9IJq.alz-eu-ace_test_sv_eap_gps-sit-07_pegaprpc_01
```
**Response to ZAP**
```
HTTP/1.1 200 OK
SET-COOKIE: Pega-RULES={atn}e3ByfWV0bUNQaHlHb1dES3pwM1ZQb0dMR1poNERERDVKUnZyc0J2dWE4ckZSUVBueSsvOUxNeEpzNTM5UzY2TmxRTC8zTEYzUWlyMm9PMm0KTVBhZE1nUzhIdz09; Path=/prweb; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: no-sniff
X-XSS-Protection: 1;mode=block
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 31335
Date: Wed, 23 Dec 2020 15:10:14 GMT
Server: xxxxx JBoss
```
**Response that the pentester reported**
```
HTTP/1.1 200 OK
2 X-Atmosphere-first-request: true
3 X-Atmosphere-tracking-id: a0d0fc86-2ea8-4023-ab01-599fbcce9a4d
4 Access-Control-Allow-Origin: https://malicioussite.com
5 Access-Control-Expose-Headers: X-Atmosphere-tracking-id, X-Heartbeat-Server
6 Access-Control-Allow-Credentials: true
7 Expires: -1
8 Cache-Control: no-store, no-cache, must-revalidate
9 Pragma: no-cache
10 Content-Length: 0
11 Date: Fri, 13 Nov 2020 05:50:51 GMT
12 Server: xxxxx JBoss
```

**Comment by evgenysavostyanov** [comment]
Ok, I was able to find the request that is returning Access-Control-Allow-Origin and Access-Control-Allow-Credentials response headers, it is coming from a specific servlet of our web application, please see below. Well, we can remove this servlet to solve the CORS issue, but I am wondering why the jetty filter with the above-mentioned configuration did not solve it for us...

**Request**
```
GET https://slaxxxxx.srv.xxxxx:15252/prweb/PRPushServlet/!@ff289324ffb7df66279bfb5c18340ad1!?PZSRVRPSH=true&portalName=Developer&X-Atmosphere-tracking-id=6a46b12c-2eec-442c-9ae3-51bbea1d7494&X-Atmosphere-Framework=2.3.1-javascript&X-Atmosphere-Transport=polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson&_=1608805260328 HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:24.0) Gecko/20100101 Firefox/24.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Referer: http://example.foo/CORSexample1.html
Origin: http://example.foo
Connection: keep-alive
Content-Length: 0
Host: xxxxx.srv.xxxxx:15252
Cookie: Pega-RULES={atn}e3ByfWV0bUNQaHlHb1dES3pwM1ZQb0dMR1poNERERDVKUnZyc0J2dWE4ckZSUVBueSsvOUxNeEpzNTM5UzY2TmxRTC8zTEYzUWlyMm9PMm0KTVBhZE1nUzhIdz09; JSESSIONID=U7ScrbQ2o7ttnR38fNe-1KKf.alz-eu-ace_test_sv_eap_gps-sit-07_pegaprpc_01
```
**Response**
```
HTTP/1.1 200 OK
X-Atmosphere-tracking-id: 6a46b12c-2eec-442c-9ae3-51bbea1d7494
Access-Control-Allow-Origin: http://example.foo
Access-Control-Expose-Headers: X-Atmosphere-tracking-id, X-Heartbeat-Server
Access-Control-Allow-Credentials: true
Expires: -1
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 0
Date: Thu, 24 Dec 2020 10:36:53 GMT
Server: xxxxx JBoss
```

**Comment by sbordet** [comment]
@evgenysavostyanov I'm not sure I understand what is the problem. You said you were not getting CORS headers, but then you report the Atmosphere request that has them.

`CrossOriginFilter` simply adds the headers required by the CORS specification, and then forwards the request to the application.
The application can therefore examine the added headers and add/modify/remove them.

`CrossOriginFilter` does not do any access control: it does not return non-200 status codes just because the origin is not allowed (or similar conditions).

It is up to the client to enforce cross-origin rules and "deny" the request (like browsers do).
A pentesting tool should do those checks as well, it cannot just rely on the response status code.

Having said that, have you checked that the Atmosphere Servlet does not do its own cross-origin handling, completely overwriting what done by the `CrossOriginFilter`?

Otherwise please state exactly what you are doing, what you expect to happen and what you get instead.

**Comment by evgenysavostyanov** [comment]
Thanks for your response @sbordet. I was trying to implement the full-fledged CORS policy that only allows requests from specified domains, their sub-domains and blocks requests from origins not specified as allowed using jetty's `CrossOriginFilter`. 

If your `CrossOriginFilter` does not enforce cross-origin rules but simply adds the headers as stated above, then perhaps my understanding of its capabilities was wrong and I apologize for that.

Atmosphere Servlet was adding CORS headers even before I configured your `CrossOriginFilter`, all the other servlets of our webapp were not adding these headers before `CrossOriginFilter` was configured and after it was configured as well, so it looks like its configuration had no impact whatsoever - this is what surprised me the most and I was wondering what exactly I did wrong there.

Anyway, I found another CORS filter from a different vendor, which does the job of rejecting requests from origins that are not on the "allowed list", so we can close this issue now. **Thanks to the whole jetty team for your support!** Happy Holidays!

**Comment by sbordet** [comment]
FTR we chose to not have the approach where the filter is blocking requests for the reason that an application can perform more dynamic checks and update the CORS headers following a more dynamic logic that would be difficult to embed in a filter.

Also, CORS is a _client-side_ mechanism. It is perfectly fine for a Java HTTP client to perform cross-origin requests and have them fulfilled while the same request could be a security hazard for a browser.

Having said that, if you're happy with the vendor filter you're using now, great :)
