### ISSUE TITLE
HTTP/2 server hangs when thread pool is low on threads

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#558]
HTTP/2 is quite different with respect to HTTP/1 in handling requests when the thread pool is low on threads.

The thread pool goes low on threads when threads are blocked in application code in two ways: read blocked (waiting for more data from the client) and write blocked (waiting for the client to read data).

In HTTP/1, Jetty avoids to block the selector thread with two mechanisms. The first is to  switch the `ExecutionStrategy` from `ExecuteProduceConsume` to `ProduceExecuteConsume`.
The second mechanism has to do with the way a HTTP/1 connection blocks. 
If it is write blocked, it means it is TCP congested, so the selector thread just performs a non-blocking write (if it completes the write it notifies the callback, which will unblock the blocked thread) and then returns to select.
Blocked reads schedule read interest with a special, non-blocking, callback. Upon a read event, Jetty detects that the read callback is non-blocking and invokes it directly from the selector thread. The callback just wakes up the blocked thread, which will read from the connection.
In this way the last thread (the selector thread) never gets blocked.

In HTTP/2 things are more complicated.
A write blocks because the session send flow control window went to zero. The only way to unblock it is to read `WINDOW_UPDATE` frames from the network. However, reading from the network could cause the read of a new request which, if handled, could block and therefore block the last thread.
Therefore new requests _could_ be queued but `WINDOW_UPDATE` frames and `DATA` frames for existing requests should be processed in a non-blocking way.
A read blocks because the session receive flow control window went to zero. The only way to unblock it is to consume data that has been queued so that a `WINDOW_UPDATE` frame is sent to the data sender. If there is no data queued, for the blocked requests, Jetty has to either wait for data for those requests, pass it to the application that will consume it, or consume other data.
However, there can be a situation where `requestA` is blocked, but the sender sends `requestB` and data for `requestB` that exhaust the session receive flow control window. If `requestB` is not handled (but queued instead), then its data is never consumed, and the session receive flow control window remains at zero.
It is necessary that the read from the HTTP/2 connection never gets blocked, and it is necessary to refuse new requests when in low threads mode, since they cannot be queued for the reasons explained above.
Request refusal must make sure that the data that comes with it is consumed so that the session receive flow control window can be enlarged.

**Comment by sbordet** [comment]
A further observation is that for HTTP/1 one last thread is enough to keep the server going. 

For HTTP/2, at least one thread plus one thread per connection  are needed. The selector thread will dispatch (in low threads mode) the call to `HTTP2Connection.onFillable()` that _must_ run. 

We should investigate whether it would be possible to register for read interest with a non-blocking callback.

**Comment by gregw** [comment]
If we can reliably detect low threads (see #557) then I think HTTP/2 can live with a similar strategy switching technique - normally it will be EPC strategy, where a thread that calls `HTTP2Connection.onFillable()` may be used to handle a read/parsed frame and thus may block;  but if we are low on threads, then we switch to PEC so a single thread may be used to: select the connection; call onFillable (no saying it is non-blocking); read/parse frames; handle any window update frames; queue any data frames for already blocked HttpInputs;  dispatch the handling of all other frames.

The issue here is still that the last thread may still read a Data frame for a stream that is not already blocked on HttpInput, so it will need a dispatch, but if that Data frame is consuming flow control window of other already blocked streams, then we can dead lock - but this is a HTTP/2 problem not a jetty problem - it suggests that we should have very large connection flow control windows if we are low on threads.

**Comment by sbordet** [comment]
@gregw 

about receiving a request with a `DATA` frame that consumes the session receive flow control window, I don't think it's a HTTP/2 problem.
The client does not know that the server is otherwise overwhelmed.
The server should just reject that request rather than trying to handle it, unless it can handle it in a non-blocking way.
Since we cannot guarantee that a request can be handled in a non-blocking way (because we call application code), we _must_ reject it.

I have committed with 1fc4086 the rejection of requests when in low threads.
However, this is not enabled by default. `SmallThreadPoolLoadTest` shows how to configure `ExecuteProduceConsume` to reject tasks.

What we need is a policy to enable such rejection in an easily configurable way.
We want HTTP/2's `ExecuteProduceConsume` to reject the tasks, but not `SelectorManager`'s.
Perhaps we want to subclass `ExecuteProduceConsume` in `AbstractHTTP2ServerConnectionFactory`, add the rejection code in the subclass, and provide the subclass as the default HTTP/2 `ExecutionStrategy`.

Thoughts ?

**Comment by sbordet** [comment]
`ExecuteProduceConsume` is now handling the task rejection itself.

**Comment by gregw** [comment]
The fixes broke the testEPCExitsLowThreadsMode unit test!
