### ISSUE TITLE
Downloading all the jars

### ISSUE THREAD

**Issue by shaifulcse** [eclipse/jetty.project#5580]
I am building fan network for different open source projects: Jetty is one of them. For that, I need to collect all the jars first. 
I have cloned the source code (checkedout to 4c5d0319b108afdf448b5585e0347227b702f08c) and trying to get all the dependency jars with the command: 
`mvn dependency:copy-dependencies`

This command works for two other projects. But for Jetty it's not working. The following command also fails:
`mvn clean install -Dmaven.test.skip=true
` 
```
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.513 s
[INFO] Finished at: 2020-11-07T12:18:36-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jetty-servlets: Could not resolve dependencies for project org.eclipse.jetty:jetty-servlets:jar:9.3.12-SNAPSHOT: Could not find artifact org.eclipse.jetty:jetty-servlet:jar:tests:9.3.12-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jetty-servlets


```

Any help would be highly appreciated.

**Comment by sbordet** [comment]
You say you have checked out 4c5d031, which is an interim commit from August 2016.

Check out, instead, a valid release tag such as `jetty-10.0.0.beta3` and all will be good.

**Comment by joakime** [comment]
> [ERROR] Failed to execute goal on project jetty-servlets: Could not resolve dependencies for project org.eclipse.jetty:jetty-servlets:jar:9.3.12-SNAPSHOT: Could not find artifact org.eclipse.jetty:jetty-servlet:jar:tests:9.3.12-SNAPSHOT -> [Help 1]

That's attempting to access a `<classifier>tests</classifier>` artifact.

But your command line has `-Dmaven.test.skip=true`, which skips the compilation and execution of tests.  
Switch from `-Dmaven.test.skip=true` to `-DskipTests` instead, that will still allow the tests to compile and package, but doesn't execute the tests.

See https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html for the documented difference.

**Comment by shaifulcse** [comment]
Even with that, it failed. And when I do 

Failed to execute goal on project jetty-util: Could not resolve dependencies for project org.eclipse.jetty:jetty-util:jar:10.0.0-SNAPSHOT: Could not find artifact org.eclipse.jetty:jetty-slf4j-impl:jar:10.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jetty-util

**Comment by joakime** [comment]
You switched from Jetty 9.x to 10.x

Did you mean to do that?
If you want to stick with Jetty 10.x, then use Java 11+, Maven 3.6.x, and `mvn clean install -DskipTests` from the root of the project.
