### ISSUE TITLE
Implement minimal support for Servlet upgrade method

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#5596]
We currently do no support the servlet 4.0 upgrade method, so we cannot completely pass the TCK tests.
We should do a minimal implementation to pass these tests.

**Comment by gregw** [comment]
The reason we have not implemented update to date is that for all specific usages (eg websocket upgrade) it is far more efficient to upgrade to a specific Connection implementation that links through to a specific API for the new protocol.

However, the servlet upgrade mechanism requires that a `ServletInputStream` and `ServletOutputStream` are provided to the `HttpUpgradeHandler`, which implies that much/most/all of the `HttpInput` mechanism needs to be retained so that async IO can be supported.  So we have several choices:

 + continue to not support it as a silly idea
 + handle the upgrade as we normally do by entirely replacing the `Connection`, but in that case we will need to provide new implementations of `ServletInputStream` and `ServletOutputStream`, including async IO!
 + replace the `Connection` with one that wraps the existing `HttpChannel` or `HttpConnection` and it will feed/take the data streams unaltered to/from the real connection whilst allowing the existing `HttpInput` implementation to do it's work.
 + replace the `Connection` with one that flows data directly to/from an interceptor installed into the HttpInput. The `HttpChannel` remains, but is not connected to an endpoint nor the HttpInput.  
 + Something I've not thought of.

None of these are optimal.  So we need to find the best of bad choices.

**Comment by janbartel** [comment]
@lorban can you link this to the PR and then close this issue?
