### ISSUE TITLE
Allow to configure HttpClient request authority

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5633]
**Jetty version**
9.4.x

**Description**
When `HttpClient` is used in a proxy, it may connect to backend servers using a destination that is different from the authority that the remote client used.

For example, the `HttpClient` in the proxy may choose to connect to the backend server at `1.2.3.4:5678` while the client sent the request to `foo.bar.com:80`.

Would be great to be able to specify the `authority` of the request independently from the destination, along these lines:

```java
httpClient.newRequest("1.2.3.4", 5678)
  .authority("foo.bar.com:80")
  ...
```

**Comment by sbordet** [comment]
For HTTP/2 this has a direct translation to the `:authority` pseudo header.

For HTTP/1.1 should the authority be used as the `Host` header? @gregw thoughts?

**Comment by joakime** [comment]
+1 for having the `Host` header in HTTP/1.1 be the authority.

**Comment by moscicky** [comment]
@sbordet could you provide hints how to set :authority pseudo header with jetty client (v12)? My requests are proxied by envoy and it expects the :authority header to contains desired destination.

Your inital comment mentions a `authority` builder like method but the linked PR contains HttpDestination api

**Comment by joakime** [comment]
@moscicky Jetty 9 (what this Issue is for) is now at End of Community Support.
You should be using Jetty 12 at this point in time.

* #10485 
* #7958 

Also, please don't resurrect old issues.
If you have question, and it's on a supported version of Jetty, please open a new Issue (under the question category).
