### ISSUE TITLE
Remove all profiles for session tests

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5644]
Now that all session tests can be run without needing any local installs of anything, we should remove profiles that turn off testing:  session testing should be executed whenever tests are executed.

**Comment by olamy** [comment]
you want to run all remote-session-test per default? the build might be long
the only local install is `docker`

**Comment by janbartel** [comment]
I think that we should use profiles only very rarely, otherwise we risk forgetting to turn them on or off during ci or release builds. We need to be very sure about what is actually being built so we can have confidence in the builds.

So, I'm in favour of executing _all_ tests in the test phase: if that needs an install of docker, I'm fine with that. I assume @sbordet will disagree?

**Comment by olamy** [comment]
maybe we could have a profile not activated per default to skip those long tests (autobahn tests are very long as well)

**Comment by olamy** [comment]
#5703

**Comment by olamy** [comment]
done
