### ISSUE TITLE
Backport graceful HTTP2Session shutdown

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5645]
**Jetty version**
9.4.x

**Description**
In light of the work for #5310, the work for #2788 should be backported from Jetty 10 to Jetty 9.4, so that both share the same code for session closing protocol.

**Comment by sbordet** [comment]
@gregw do you think we should do this backport?
It's a rather big change and we have slowly moving to 9.4.x being maintenance only.
As such, I'm inclined to _not_ backport and close this issue.

**Comment by gregw** [comment]
I think we can wait and see.  If we get reports of this being a problem for users who cannot upgrade, then we can consider

**Comment by sbordet** [comment]
Closing as implemented in Jetty 10.
If needed, another issue can be opened.
