### ISSUE TITLE
Update osgi test dependencies

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5675]
Update the following osgi test dependencies:

biz.aQute.bnd bndlib 5.2.0
org.ops4j.pax.tinybundles tinybundles 3.0.0
org.ops4j.pax.url pax-url-wrap  2.6.2
org.ops4j.pax.url pax-url-aether 2.6.2

**Comment by bustergene83** [comment]
> `        {
            //ensure file will always be unique by appending random digits
            tmpDir = File.createTempFile(temp, ".dir", parent);
            //delete the file that was created
            tmpDir.delete();
            //and make a directory of the same name
            tmpDir.mkdirs();
        }`

**Comment by janbartel** [comment]
Fixed via #5676
