### ISSUE TITLE
No way to see which modules are enabled for the distro

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5680]
**jetty-10.0.x**

Why is it no longer possible to list which modules have been enabled (and whether they are transitively or explicitly enabled) for the distro?

**Comment by sbordet** [comment]
@janbartel `java -jar start.jar --list-modules` from the `$JETTY_BASE` does not work for you?

**Comment by joakime** [comment]
the `--list-config` also shows it (at the top) in Jetty 10.

**Comment by janbartel** [comment]
@sbordet --list-modules lists all modules, not those that are enabled.

@joakime not according to --help:

```
  --list-config    List the resolved configuration that will be used to
                   start Jetty.
                   Output includes:
                     o  Java Environment
                     o  Jetty Environment
                     o  JVM Arguments
                     o  Properties
                     o  Server Classpath
                     o  Server XML Configuration
```
