### ISSUE TITLE
Documentation: cache files in documentation artifacts

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#5690]
**Jetty version** 10, 11

**Java version** n/a

**OS type/version** n/a

**Description**
Noticed some cache files in the documentation artifacts for 10 and 11.  I think they stem from the automatic generation based on those flow diagrams we added a while back. I suspect we can filter these out in the assembly descriptor.

	modified:   documentation/jetty-10/operations-guide/.asciidoctor/diagram/diag-2830e38460d606111888c5df2a645163.png.cache
	modified:   documentation/jetty-10/operations-guide/.asciidoctor/diagram/diag-70817cc5c7137abc9759cdcd3edbb658.png.cache
	modified:   documentation/jetty-10/operations-guide/.asciidoctor/diagram/diag-7387dfbb6f9fb9cfa951a697aca488a8.png.cache
	modified:   documentation/jetty-10/operations-guide/.asciidoctor/diagram/diag-8a7fb4bb9c84453a4bf01a24558e8026.png.cache
	modified:   documentation/jetty-10/operations-guide/.asciidoctor/diagram/diag-e2488cc783b3434076c5a44ee7f19a2b.png.cache
	modified:   documentation/jetty-10/operations-guide/diag-2830e38460d606111888c5df2a645163.png

**Comment by sbordet** [comment]
Why do you want to filter them out? What is the problem with these files?

**Comment by jmcc0nn3ll** [comment]
They are an artifact of construction aren't they? or are they actually used in the final rendering.  If they are not transitory and are part of the final product then we can just close this out. It just caught me off guard when I saw '.' directories in the zip file.

**Comment by sbordet** [comment]
They are used in the final rendering.
