### ISSUE TITLE
URIUtil.encodePath does not always encode utf8 chars

### ISSUE THREAD

**Issue by fbuecklers** [eclipse/jetty.project#570]
If you call the method with an StringBuilder or you encode a path where one of the special chars %, ..., ] comes before an utf8 char, utf8 encoding will not be applied to to the complete path:

```
URIUtil.encodePath("testö /_#<>ß{33}$€.html") // -> correctly encodes to
// test%C3%B6%20/_%23%3C%3E%C3%9F{33}$%E2%82%AC.html

URIUtil.encodePath("test ö /_#<>ß{33}$€.html") // -> incorrectly encodes to
// test%20ö%20/_%23%3C%3Eß{33}$€.html
```

Note that i just add a space behind "test" in the string.
I think that is really a critical issue since this method is used on many places.

**Comment by gregw** [comment]
I think we just found and fixed that bug separately... checking now...

**Comment by gregw** [comment]
It had been found and fixed in another branch, but not merged.   Merged now and a test harness added.
Thanks!
