### ISSUE TITLE
Update to infinispan 11.0.x

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5711]
**Jetty version**
Jetty 10.x

**Description**
As discovered by @dependabot https://github.com/eclipse/jetty.project/pull/5699

Infinispan that Jetty is using is 9.4.8.Final, but version 11.0.5.Final is available.

@janbartel [pointed out](https://github.com/eclipse/jetty.project/pull/5699#issuecomment-732248186) that this update would need code changes and updated `*.mod` files, and would need to be done manually.

**Comment by olamy** [comment]
some work started here https://github.com/eclipse/jetty.project/pull/6057

**Comment by olamy** [comment]
see #6687
