### ISSUE TITLE
Javadoc on release for Jetty 9

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#5721]
**Jetty version**
9

**Java version**
n/a

**OS type/version**
n/a

**Description**
There should be a jetty-documentation-9.4.x-javadoc.jar classified artifact deployed in the same way Jetty 10 and Jetty 11 have.  This makes scripting deployments to the website much easier.

**Comment by jmcc0nn3ll** [comment]
@olamy If memory serves this was something you got in place for 10 and 11, is there anything preventing us from doing this for 9, maybe java or plugin related?

**Comment by olamy** [comment]
@jmcc0nn3ll do you mean a jar file containing the generated documentation or an aggregated javadoc jar?

**Comment by jmcc0nn3ll** [comment]
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-documentation/10.0.0.beta3/

Like the javadoc classified artifact in there, same location only for Jetty 9. This is pulled down and dumped to the eclipse jetty website that I have been updating and automating.

**Comment by jmcc0nn3ll** [comment]
crossed wires issue, closing
