### ISSUE TITLE
Review Preventers

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5725]
**Jetty version**
10.0.x

**Description**
There are a number of "preventers" that are supposed to avoid classloader leaks.

Some of them are now invalid since either the issue has been solved in OpenJDK or the classes/fields they were doing heavy reflection on have been renamed/moved.

All of them need a review and possibly be moved to a different module to avoid polluting the `jetty-util` `module-info.java` with `requires static`.

**Comment by sbordet** [comment]
See also #1923.

**Comment by janbartel** [comment]
In jetty-9.4, many of them can be marked as Deprecated, as they were fixed for eg jdk8. I think in jetty-10 we can remove them.

**Comment by janbartel** [comment]
Fixed by #5839
