### ISSUE TITLE
What's the use of the reserved thread?

### ISSUE THREAD

**Issue by daizhijie395** [eclipse/jetty.project#5733]
**Jetty version**
9.4.19

**Java version**
1.8

**Question**
What's the use of the reserved thread? Why don't you use normal threads to handle blocking tasks?

**Comment by sbordet** [comment]
Because we need to know if there is a thread that can run a blocking task. This is critical for our HTTP/2 implementation.
We cannot just queue a task and hope some thread will run it, because there may be no threads to run it.
