### ISSUE TITLE
Make http client read buffer max size configurable

### ISSUE THREAD

**Issue by cen1** [eclipse/jetty.project#5746]
**Jetty version**
9.x
**Java version**
Any
**OS type/version**
Any
**Description**
Right now, max size of the read buffer for jetty http client is hardcoded to 2MB in BufferingResponseListener/FutureResponseListener. My feature request would be to not have this harcdoded but to be able to configure it via HttpClient setter method like any other (timeouts etc). This would make it much easier to apply all the needed client settings when building an instance of jax-rs client for example, instead of needing to define additional configuration options downstream and applying the config at request time which is very late.

Proposal:
- add field and get/setMaxReadBufferSize in HttpClient and use this setting in *ResponseListener code instead of hardcoded 2MB limit.

If there are no special cases where this could be problematic (thread safety?) I could even try to write a patch, because it does not seem to be too complicated of a task. Any additional pointers where and how to implement this are welcome.

**Comment by sbordet** [comment]
It's not hardcoded.

```java
Request request = ...

FutureResponseListener listener = new FutureResponseListener(request, theMaxLengthYouWant);

// Alternatively:

request.send(new BufferingResponseListener(theMaxLengthYouWant) {
  public void onComplete(Result result) {
    ...
  }
});
```

This is something that depends on each request, so having a setter in `HttpClient` is not ideal.

**Comment by joakime** [comment]
Out of curiosity, what is the problem you are encountering?
Seeing as jetty-client can read a response in a myriad of ways, from buffered, to streaming, to nio ByteBuffers, and even automatic routing to filesystem, etc..   What do you feel is missing?

**Comment by cen1** [comment]
The config option would simply override the _default_ no-args constructor value so it is not really relavant to a single request. Basically, I would replace `2 * 1024 * 1024` with the client option which would still be `2 * 1024 * 1024` if not set by the user.

The way I came to this is a rather long path.

In JavaEE JAX-RS client instantiation, specifically Jersey implementation which we use in the framework, you would write a Producer that produces an instance of a jax-rs Client. Producer is executed only once in applicaton lifecycle (if ApplicationScoped) and the Client is configured inside that producer. Things such as timeouts, header/payload modifiers, filters etc are usually configured and register there. 
One of the options when building the client is to also choose which http client implementation you want to use under the hood. In Jersey specifically, you could use HttpUrlConnectorProvider for java.net or JettyConnectorProvider which uses jetty client implemenation.
Now there is a question how do you configure the http client implementation if you really need to go into specifics. In case of jetty, Jersey added some extra properties like disabling cookies, basic auth.. but only [a few of them](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest/jersey/org/glassfish/jersey/jetty/connector/JettyClientProperties.html), and these can be registered via jax-rs standard api with `.property`. Jersey will internally map these properties to the jetty HttpClient instance.

Mapping every jetty config option like this is not really scalable and since users eventually wanted to configure HttpClient further, Jersey simply exposed the Jetty Connector API  so the developer can access the raw HttpClient (provide a supplier basically) and configure it freely without being bound to what Jersey exposes via properties.

Finally, the problem is that this default buffer size is not configurable until request time so as it stands, not configurable through Jersey by either custom property or HttpClient supplier. So I have come down to two options how to make this work.

1. Add a new Jersey-jetty property which can be registered via jax-rs API and use this property to instantiate FutureResponseListener with this config value per request. This requires patch in Jersey connector code which I did a rough test and is workable but not truely desirable. It makes custom properties more powerful than providing your own instance of HttpClient which is weird.
2. Make this configurable on HttpClient level in jetty. No custom properties needed, no changes in Jersey, if someone wants to change the value they just provide their own HttpClient supplier configured as they wish.

**Comment by sbordet** [comment]
I'm reluctant to add this property because when you use `HttpClient` asynchronously, it won't get used at all.

It's really a property of a particular way of receiving responses, which is not even the encouraged way.

Would not be better to ask Jersey to have an additional customization hook to customize requests, like you can do with the `HttpClient` instance?

> It makes custom properties more powerful than providing your own instance of HttpClient which is weird.

Not sure I follow this? Seems a viable alternative approach to me, in absence of a specific request hook.

**Comment by cen1** [comment]
I have not yet looked at the async path to be honest, I need to do that. Exposing request customizer sounds like an interesting idea. I will experiment on Jersey side to see how that would look. I'll get back when I have some sample patches.

**Comment by cen1** [comment]
Solving downstream.
