### ISSUE TITLE
httpConnector in jetty-http.xml should have a default name instead of null

### ISSUE THREAD

**Issue by nddipiazza** [eclipse/jetty.project#5753]
**Jetty version**

9.4.x latest

**Java version**

all

**OS type/version**

all

**Description**

It would be very nice if the default `jetty-http.xml` where the `httpConnector` is configured if it would have:
`<Set name="name">http</Set>`

So that there is a default name on the httpConnector of `http`. This helps with IP Access so you can use the includeConnectors/excludeConnectors feature easier. 

Instead, by default the name is `null`.

**Comment by joakime** [comment]
That would complicate virtualhost setups on contexts that want all connectors.

Here's how to configure it for your Jetty base.

Add these 2 files to your `${jetty.base}` ...

## ${jetty.base}/etc/http-name.xml

``` xml
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<!-- Tweak Http ServerConnector Name -->
<Configure id="httpConnector" class="org.eclipse.jetty.server.ServerConnector">
  <Set name="name">http</Set>
</Configure>
```

## ${jetty.base}/start.d/http-name.ini

```
etc/jetty-name.xml
```

**Comment by nddipiazza** [comment]
yep that's what I'm doing now. that's fair enough
