### ISSUE TITLE
Jetty 10 should use jakarta maven coordinates for specs

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5754]
**Jetty version**
10.0.x 

**Description**
Currently the `jetty-10.0.x` branch has the following dependency references ...

```
[INFO]    javax.servlet:javax.servlet-api:jar:4.0.1:provided -- module javax.servlet.api (auto)
[INFO]    javax.servlet.jsp:jsp-api:jar:2.2:provided -- module jsp.api (auto)
[INFO]    javax.servlet:jstl:jar:1.2:provided -- module jstl (auto)
```

We should strive to migrate our dependencies to the ones within the jakarta ee 8 maven coordinates. (which still use the `javax.` namespace internally)

Example:

* https://search.maven.org/artifact/jakarta.servlet/jakarta.servlet-api/4.0.4/jar
* https://search.maven.org/artifact/jakarta.servlet.jsp/jakarta.servlet.jsp-api/2.3.6/jar
* https://search.maven.org/artifact/jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api/1.2.7/jar

**Comment by janbartel** [comment]
Is there a big motivation for doing this? Presumably jakarta is never going to release another set of jars with the javax.* package, and neither is anyone else. AFAIK the jakarta release of the javax.* packages also was not supposed to change anything, so we're not even getting any bugfixes etc? Happy to do this if there's a good reason, I'm just struggling to see what it is?

**Comment by jmcc0nn3ll** [comment]
Isn't artifact licensing the primary concern here?

**Comment by joakime** [comment]
There's also the maven coordinate conflict resolution aspect as well. (for those developers that consume our artifacts from maven central)

**Comment by joakime** [comment]
Here's the breakdown of Servlet 4.0 ...

```
$ cd tmp
$ mkdir lic
$ cd lic

$ cp ~/.m2/repository/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar .
$ cp ~/.m2/repository/jakarta/servlet/jakarta.servlet-api/4.0.2/jakarta.servlet-api-4.0.2.jar .

$ mkdir javax
$ cd javax/
$ jar -xf ../javax.servlet-api-4.0.1.jar 
$ grep -iR "apache license" *
$ grep -iR "EPL" *
$ grep -iR "CDDL" *
$ grep -iR "GPL" *

 - META-INF/LICENSE.TXT
   CDDL
   GPL 2.0 + Classpath Exception
 - HTML + Properties + Resource
   Apache 2.0

$ mkdir jakarta
$ cd jakarta/
$ jar -xf ../jakarta.servlet-api-4.0.2.jar 
$ cd ../javax/
$ grep -iR "apache license" *
$ grep -iR "EPL" *
$ grep -iR "CDDL" *
$ grep -iR "GPL" *

 - META-INF/LICENSE.md
   EPL 2.0
   GPL 2.0 + Classpath Exception
 - META-INF/NOTICE.md
   EPL 2.0
   GPL 2.0 + Classpath Exception
 - HTML + Properties + Resource
   Apache 2.0

$ grep SPDX -RHin *
javax/servlet/annotation/package.html:15:    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
javax/servlet/descriptor/package.html:18:    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
META-INF/maven/jakarta.servlet/jakarta.servlet-api/pom.xml:17:    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
META-INF/NOTICE.md:28:SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
```

So that means ...

* Jakarta Servlet 4.0
   - Source code + Classes are EPL 2.0 + GPL 2.0 w/Classpath Exception
   - Resource files (`*.html`, `*.properties`, and javadoc) are Apache 2.0
   - Properly SPDX registered
* Javax Servlet 4.0
  - Source code + Classes are CDDL + GPL 2.0 w/Classpath Exception
  - Resource files (`*.html`, `*.properties`, and javadoc) are Apache 2.0
  - NOT SPDX tagged (this breaks much tooling around license validation from many parties, from github itself, to blackduck, whitesource, renovate, various IDEs, etc...)


Differences of note:
  * CDDL in old (javax), replaced with EPL 2.0 in new (jakarta)
  * SPDX tags

**Comment by janbartel** [comment]
OK, but my question remains:   don't we already have permission for these licences?

Also, if we change to dependencies on the (equally) dead-end `jakarta.*`  artifacts, how many people who use jetty will be changing to them? Won't it create more confusion for developers who will have jetty introducing dependencies on `jakarta.*` artifacts while their poms will have dependencies on `javax.*` artifacts introducing class duplication?

**Comment by joakime** [comment]
The `jakarta` artifacts are not a dead end.

There's a few specs talking about point releases for features on Jakarta EE 8 already.

Example: The Jakarta Servlet 4.x spec has a discussion on doing a 4.1 release because `Same-Site` cookie issue.

**Comment by gregw** [comment]
@jmcc0nn3ll I don't think licensing is an issue here.  These are all provided dependencies which we do not distribute.  The only servlet-api that we distribute is the one we build with schemas and JPMS extras.  That one already takes the schemas from Jakarta and I'm happy for it to also take the source from there.

This instead is about what API we some artefacts depend on that must be provided by somebody else (which in most cases is us providing our own servlet-api jar).

The risk of causing dependent projects to get double servlet-api jars is non-zero (either way) and is just another aspect of name-a-geddon impacts.... however our usage is mostly in demo and test classes... which I kind of would prefer we made depend on our servlet-api anyway.   

We do have uses in the maven plugin and gcloud stuff - we should probably follow the lead of those dependencies and switch to jakarta only when they do, else we risk the double jar... although provided probably helps with it.

Let's think about this one for a bit as I don't think it is urgent and there is scope for us to make name-a-geddon worse if we get it wrong.

**Comment by jmcc0nn3ll** [comment]
@gregw I think it is a licensing issue though, if for no other reason then what Joakim referenced with potential updates to the specification.  Beyond that though, companies are having to deal with tracking licenses and we should strive to make ourselves as little an issue as possible and running with no longer relevant servlet licenses does not serve that goal. The old javax artifacts are dead, there is no life in them any longer, everything has been turned over to the Eclipse Foundation so we shouldn't be using them at all, it is a surprise to me that we apparently did with Jetty 10.  The future exists in jakartaee so it only makes sense for us to source the materials for Jetty 10 and Jetty 11 from the active namespaces.  I really think we should try to live off of official servlet api jars as well, rolling our own opens the door for user lock in behavior which should not be our intent.

**Comment by gregw** [comment]
I agree that if jakarta can release a usable servlet-api, then we should use it directly.   But we will see if JPMS and schemas can actually be included.... remember what they can do with javax artifacts is very limited.

Until that point, why don't we just switch everything to point to our servlet-api?

**Comment by jmcc0nn3ll** [comment]
As long as ours embraces and extends from the jakartaee artifact I am fine with that.

**Comment by olamy** [comment]
we can close this as `jetty-servlet-api` is using `jakarta`:
```
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>4.0.3</version>
```
