### ISSUE TITLE
How to config http timeout

### ISSUE THREAD

**Issue by q37381** [eclipse/jetty.project#5758]
**Jetty version**
9.2.6
**Java version**
8
**Question**
some request take much time, i want to make it response within 15 seconds,and now it response within 90 seconds because nginx config.
it does not work:
(Set name="idleTimeout"   Property name="jetty.http.timeout" default="20000"    Set)

**Comment by lachlan-roberts** [comment]
Jetty 9.2 is EOL, you should really be upgrading to at least Jetty 9.4.35.

You can set the `jetty.http.idleTimeout` property in the `http.ini` file or you can set it directly on the command line:
```
java -jar $JETTY_HOME/start.jar jetty.http.idleTimeout=15000 
```

**Comment by q37381** [comment]
> Jetty 9.2 is EOL, you should really be upgrading to at least Jetty 9.4.35.
> 
> You can set the `jetty.http.idleTimeout` property in the `http.ini` file or you can set it directly on the command line:
> 
> ```
> java -jar $JETTY_HOME/start.jar jetty.http.idleTimeout=15000 
> ```
