### ISSUE TITLE
Homepage needs update for new Jetty 10 / 11 releases

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5766]
The Jetty homepage at https://www.eclipse.org/jetty/

has the following text that needs updating ...

> The current recommended version for use is Jetty 9 which can be obtained on the Jetty Downloads page. Also available are the latest maintenance releases of Jetty 8 and Jetty 7,

**Comment by oleg-nenashev** [comment]
Thanks for the new release! It would be also great if the page sets expectation about Jetty 9.x EoL. IIUC there are no plans to do it anytime soon, but I was unable to find an official confirmation in the docs.

**Comment by WalkerWatch** [comment]
@oleg-nenashev We have no plans to EoL Jetty 9 for the foreseeable future as it provides support for Java 8. We will communicate to the community when we have something in plans for it.

**Comment by WalkerWatch** [comment]
Updated in https://github.com/eclipse/jetty.website/commit/aa94a4f8cd750e4c8a0ec8e7772d17db829953c4

**Comment by oleg-nenashev** [comment]
Thanks for the clarification!
