### ISSUE TITLE
Websocket annotation on AnnotatedConfigEndpoint class

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5774]
jetty-11

In the code below, Eclipse flags the use of the private non-static fields (idleTimeout, maxMessageSize, maxMessageSize, inputBufferSize) of the enclosing class (ClientConfigTest)  as illegal because those fields are not static.

 ```
   @WebSocket(idleTimeout = idleTimeout, maxTextMessageSize = maxMessageSize, maxBinaryMessageSize = maxMessageSize, inputBufferSize = inputBufferSize, batchMode = BatchMode.ON)
    public class AnnotatedConfigEndpoint extends EventSocket
    {
    }
```

**Comment by janbartel** [comment]
@lachlan-roberts Eclipse seems to think this is a problem, can you investigate?

**Comment by janbartel** [comment]
BTW, it's the same error for jetty-10

**Comment by joakime** [comment]
To be clear, Eclipse is complaining about the `ClientConfigTest` final fields not being `static`.

https://github.com/eclipse/jetty.project/blob/aabe5ceee26971beb57d399a1424b8274ee6f4ef/jetty-websocket/websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientConfigTest.java#L65-L67

As Eclipse expects that if you use an annotation, the values are actually constants. (requires them to be `final static`).

**Comment by lachlan-roberts** [comment]
I don't think this is actually a problem as the `AnnotatedConfigEndpoint` class is not static either so it should work. Either way I will make a PR to clean it up and make all of the fields and classes used for this `static`.
