### ISSUE TITLE
[HTTP/2 Request] NullPointerException in MetaData

### ISSUE THREAD

**Issue by pizzqc** [eclipse/jetty.project#578]
Using: Jetty &  http2-server build: 9.3.8.v20160314

I am currently writing a Stub for APNS HTTP/2 testing and went across the following NPE when we received a request from Pushy (Library to send push notification to APNS).

See attached DEBUG log from Jetty.

When running in DEBUG, I can see that those request (Pushy notification) don't have the `HostPortHttpField` initialized leading to a NPE when doing `hostPort.getHost()` or `hostPort.getPort` inside MetaData.class

I looked into the Pushy code and they are using Netty under the hood but aren't setting the headers `:authority` which I believe might be the reason why those objects end-up `null` in Jetty.

Thanks a lot of your support and the addition of HTTP/2.

/Antoine
[Jetty-Error-Debug.txt](https://github.com/eclipse/jetty.project/files/270597/Jetty-Error-Debug.txt)

**Comment by sbordet** [comment]
@pizzqc your analysis is correct.

[RFC 7540](http://tools.ietf.org/html/rfc7540) states that [clients `SHOULD` send](http://tools.ietf.org/html/rfc7540#section-8.1.2.3) the `:authority` field.

The lack of this field will break virtual hosts and conversion to HTTP/1.1, so I think that Pushy should be updated to include this field.
