### ISSUE TITLE
Revisit Statistics classes

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5786]
**Jetty version**
9.4.x

**Description**
`MonitoredQueuedThreadPool` uses a number of statistics classes to record various properties.

`MonitoredQueuedThreadPool.getTasks()` is wrong, it should call `taskLatencyStats.getCount()` not `taskLatencyStats.getTotal()`.

Also, replace `Atomic*` with `LongAdder`.

Stop using deprecated `SampleStatistic.set()` method.

**Comment by rk1165** [comment]
Hi @sbordet,
I didn't get this part - "Also, replace Atomic* with LongAdder." I tried searching for Atomic in MonitoredQueuedThreadPool class but couldn't find any reference.

**Comment by sbordet** [comment]
@rk1165 sorry the replacement of `Atomic*` with `LongAdder` has already been done in #2288 -- ignore it.

However, please do fix `getTasks()` and replace usages of deprecated `set()` methods.

Work from branch `jetty-9.4.x`.

Thanks!

**Comment by rk1165** [comment]
@sbordet 
Created the following PR #5825 
Please review.

**Comment by sbordet** [comment]
Thanks @rk1165!
