### ISSUE TITLE
Fix for Bug 475546 reverted on 9.4 onward

### ISSUE THREAD

**Issue by zregvart** [eclipse/jetty.project#5793]
**Jetty version**
I'm using 9.4.35.v20201120, I see that the issue is present on versions [9.4.x](https://github.com/eclipse/jetty.project/blob/ea621cea9b5cc67ee5efc2608b6e913fa64a504b/jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java), [10.0.x](https://github.com/eclipse/jetty.project/blob/1753dec7205784025fbe4d01af4ba9de2b134bfb/jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java) and [11.0.x](https://github.com/eclipse/jetty.project/blob/04b893bf2ca6b2b5ca18f642615aef4578f266b6/jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java) by looking at the state of the source code currently.

**Java version**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode, sharing)

**OS type/version**

Linux, Fedora 33, kernel 5.9.10-200.fc33.x86_64 (not important for this issue)

**Description**

A fix was delivered for [bug #475546](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475546) in b1b569bd231e5d9c379e6970a1a1b585b0daeb8b and has been reverted on 9.4.x with 1311052b1550a91ad71382724dd057ca47573baf. The same issue in [bug #475546](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475546) can be reproduced on 9.4.35.v20201120.

To restate the problem, using HTTP proxy tunnelling via `CONNECT` fails with `java.nio.channels.ClosedChannelException` due to inadvertently closed connection by Jetty HTTP client.

**Comment by joakime** [comment]
This is something different.

The test introduced by the original fix `HttpClienTest.testCONNECTWithHTTP10()` (b1b569bd231e5d9c379e6970a1a1b585b0daeb8b)

That test is still present on Jetty 9.4.34, and the code it introduced has changed has evolved many times over the years.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.35.v20201120/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java#L1569-L1572

The original bug filed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=475546 is not reproducible on Jetty 9.4.35 as it currently stands.

At this point we need to see logs of this happening for you, debug logs would be swell.

**Comment by zregvart** [comment]
@joakime thanks for quick response, this is the code I test with:

```java
package com.github.zregvart;

import java.util.List;

import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.HttpProxy;
import org.eclipse.jetty.client.Origin;
import org.eclipse.jetty.client.ProxyConfiguration;
import org.eclipse.jetty.client.api.ContentResponse;
import org.eclipse.jetty.client.api.Request;
import org.eclipse.jetty.util.ssl.SslContextFactory;

public class Client {

    public static void main(final String[] args) throws Exception {
        final SslContextFactory ssl = new SslContextFactory.Client(true);
        final HttpClient client = new HttpClient(ssl);

        final ProxyConfiguration proxyConfiguration = client.getProxyConfiguration();
        final List<ProxyConfiguration.Proxy> proxies = proxyConfiguration.getProxies();
        proxies.add(new HttpProxy(new Origin.Address("localhost", 8866), false));

        client.start();

        try {
            final Request request = client.newRequest("https://www.google.com");

            final ContentResponse response = request.send();

            System.out.println(response.getContentAsString());

        } finally {
            client.stop();
        }
    }
}
```

And this is the debug log: [jetty-debug.log](https://github.com/eclipse/jetty.project/files/5675417/jetty-debug.log). I just noticed that for, whatever reason, the proxy is responding with `Connection: close` header, this could be a bug in the proxy I use (Fiddler). So that prompted me to test with Squid instead, and it doesn't exhibit issue.

Seems that I'm wrong on this, and that the proxy in question is the culprit for the issue I'm seeing. I'm going to close this, sorry for the noise.
