### ISSUE TITLE
ServerConnector leaks closed sockets which can lead to file descriptor exhaustion

### ISSUE THREAD

**Issue by joewitt** [eclipse/jetty.project#5794]
**Jetty version**
9.4.35.v20201120 and older
**Java version**
OpenJDK Runtime Environment (build 1.8.0_272-b10) and others
**OS type/version**
OSX and Linux
**Description**
The ServerConnector class in openAcceptChannel creates a local variable which is an opened server socket channel.  Then when attempting to bind to the specified port, if there is an exception, it will throw a new exception and not clean up the created channel/resource.  The fix is to ensure that in the event of a bind exception the serverChannel is properly closed before throwing the exception back to the caller.  Without this change the socket will be in a CLOSED state and a file descriptor held for it for the remainder of the life of the process.

**Comment by gregw** [comment]
#5802 modified to be based on #5797 and both now merged.  thanks @joewitt
