### ISSUE TITLE
Jetty 10+ Documentation missing versions table

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5808]
**Jetty version**
Jetty 10 and Jetty 11

**Description**
The old Jetty versions table is missing from the new documentation.
We need that back, and in way that is linkable.

Example of old table - https://www.eclipse.org/jetty/documentation/jetty-9/index.html#what-jetty-version

**Comment by WalkerWatch** [comment]
@joakime Why explicitly in the documentation. This information exists on the homepage of the Jetty project to some degree but the table itself lives on the [Downloads](https://www.eclipse.org/jetty/download.php) page in full.

I believe it was @sbordet who wanted to clean out some of the intro stuff to the docs. That said, we can add it back in if the consensus agrees.
