### ISSUE TITLE
Stack trace for 500 error when response header is hidden in DEBUG. Why is that?

### ISSUE THREAD

**Issue by 1lolbus1** [eclipse/jetty.project#5809]
**Jetty version**

9.4.34.v20201102

**Java version**

Java 8

**Question**

We were seeing some 500 response errors coming from our server despite having the transaction execute successfully on our backend. Confused, we dug in to see what could be causing the issue. Nothing in our log, I thought maybe we were swallowing stack traces somewhere however it seems that this is the case for Jetty when a response header is too large - the stack trace produced by this is only visible in a DEBUG statement ([code here](https://github.com/eclipse/jetty.project/blob/2662be0a05e14fad80defd722bc191ba201c5e8b/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L1331)). Is this expected behaviour? I feel like this ought to be an ERROR message instead of a debug message. Could I get some clarity as to _why_ this is a DEBUG?

Thanks!

**Comment by janbartel** [comment]
@1lolbus1 connection failure is really frequent for many reasons (mobile loses wifi/4g, user closes browser/window/laptop lid etc etc) so the log would be absolutely full up with very noisy stack traces.

**Comment by gregw** [comment]
Actually, if it is possible to differentiate between remote failures (eg a connection being closed) vs a bad application action (eg response headers too big), then we should log the later at warn level.  Reopening to have a look....
