### ISSUE TITLE
JMX-ify Scheduler implementations

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5816]
**Jetty version**
9.4.x

**Description**
`Scheduler` implementations lack JMX annotations.
Would be useful to know the scheduler name, the number of scheduler threads, whether it is daemon, etc.

**Comment by rk1165** [comment]
Hi @sbordet ,
How can I work on this, can you please guide me?
I have already cloned the project, signed the contributor agreement and subscribed to the mailing list. Is there anything else I need to do?

Also, please let me know if there's any prerequisite I need to read up or anything.

**Comment by sbordet** [comment]
@rk1165 thanks for volunteering!

Please read the contributor guidelines: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md

In particular you have to make sure your commits are signed-off (the other requirement was the ECA, but you already signed it).

Then please have a look at how `QueuedThreadPool` is annotated with Jetty JMX annotations, and do something similar for `ScheduledExecutorScheduler`.

Please work against the `jetty-9.4.x` branch, make your changes, and then issue a pull request, electing me as a reviewer.

Let me know here if you need more help. Thanks!

**Comment by rk1165** [comment]
Hi, @sbordet 
I made the aforementioned changes and raised the following PR #5821 
Can you please review?
