### ISSUE TITLE
Provide more filtering for CustomRequestLog

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5817]
**Jetty version**
9.4.35+

**Description**
The current `CustomRequestLog` has only 1 filter option, which is the request uri path.

Provide more filtering options.

* Response status code (very useful)
* Content-Type (can narrow down specific behaviors)
* User-Agent (can identify specific user agents you are interested in)

I think just supporting a `BiPredicate<Request,Response>` on `CustomRequestLog` which is used in `.log(Request,Response)` should be the maximally flexible option.
Complex rules can be done with BiPredicate composition (`.and()`, `.or()`, and `.not()`) or with custom `BiPredicate` behaviors.

**Comment by rk1165** [comment]
Hi @joakime ,
I followed the class and method you mentioned. How do I start working on it, can you please help me? 
I have already cloned the project, signed the contributor agreement and subscribed to the mailing list. Is there anything else I need to do?
Also, please let me know if there's any prerequisite I need to read up or anything.

**Comment by lachlan-roberts** [comment]
@rk1165 there's no prerequisites other than signing the ECA. If you want to help out and work on this you can implement this feature on your branch, write some junit tests for it, then you can create a pull request to the `jetty-9.4.x` branch. You should sign your commits with the email you used to sign the ECA. Then the PR will be reviewed and merged if it is approved and passes all the tests.
