### ISSUE TITLE
Prevent Invalid Headers Being Relayed

### ISSUE THREAD

**Issue by JohnnyPendlebury** [eclipse/jetty.project#5822]
**Jetty version**
 9.4.15.v20190215

**Java version** 
11

**Question**

Using Jetty Client I notice that compressed responses from a server are automatically decompressed. However, the CONTENT-ENCODING header still contains GZIP. In a situation such as proxied requests how can the service using Jett Client remove invalid headers to prevent relaying them to its own client?

Thanks in advance
J

**Comment by sbordet** [comment]
Not sure I understand.

If you use `HttpClient` in a proxy, you want to disable gzip, cookie handling, etc. See for example:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.35.v20201120/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L278

Even if you don't do what above, you get the response headers and the response content from the remote server, and you can decide what to send back to the remote client, possibly recompressing the content, and updating the headers, etc.
It is all in your hands, `HttpClient` does not know it's being used in a proxy.

**Comment by joakime** [comment]
The key line to disable the automatic decompression is ...

https://github.com/eclipse/jetty.project/blob/bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L338-L339

**Comment by JohnnyPendlebury** [comment]
Thanks all,

That seems like a reasonable solution to the issue, to allow a proxy to simply forward the CONTENT-ENCODING header as is.

Thanks again,
J

**Comment by janbartel** [comment]
Closing the issue as the OP reports the question has been satisfactorily answered.
