### ISSUE TITLE
Jetty-util contains wrong Import-Package

### ISSUE THREAD

**Issue by akurtakov** [eclipse/jetty.project#5830]
**Jetty version**
10.0.0

**Java version**
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode, sharing)

**OS type/version**
Fedora 33

**Description**
Trying to use jetty-util in osgi context fails to resolve with:
[ERROR]   Missing requirement: org.eclipse.jetty.util 10.0.0 requires 'java.package; com.sun.nio.file 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.help.feature.group 2.3.500.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.jetty.util 0.0.0

Import-Package: com.sun.nio.file,javax.imageio,javax.naming.ldap,javax.n
 et.ssl,javax.security.auth.x500,javax.xml.parsers,org.eclipse.jetty.uti
 l,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,or
 g.eclipse.jetty.util.resource,org.eclipse.jetty.util.security,org.eclip
 se.jetty.util.statistic,org.eclipse.jetty.util.thread,org.slf4j;version
 ="[2.0.0,3)" 
the com.sun.nio.file import-package looks needless in fully modularized system.

**Comment by janbartel** [comment]
@akurtakov thanks for the report. That is very odd, I cannot see why the maven-bundle-plugin is producing an Import-Package statement for "com.sun.nio.file", I'll look into it.  I do note though that our osgi tests don't fail when we deploy jetty-util, so there must be something different about our environments, any clue what it could be?

**Comment by akurtakov** [comment]
My guess would be that the target platform you run your osgi tests against contains a.jre.javase IU for older Java version and thus contains the com.sun.nio.file package.

**Comment by janbartel** [comment]
@akurtakov I've narrowed this down to this line in `org.eclipse.jetty.util.PathWatcher`:

`Class<?> c = Class.forName("com.sun.nio.file.SensitivityWatchEventModifier");`

That seems to cause the maven-bundle-plugin to generate the `Import-Package` statement for `com.sun.io.file`. Interestingly, there's a `Class.forName` a couple of lines above that does _not_ generate an `Import-Package`:

` Class<?> pollingWatchServiceClass = Class.forName("sun.nio.fs.PollingWatchService", false, cl);`

I'm assuming that `maven-bundle-plugin` is looking for the single arg version of `Class.forName` only. I'm checking if we really need to call the single-arg version, or whether we can call the 3 arg method instead.

**Comment by janbartel** [comment]
Raised PR #5838

**Comment by akurtakov** [comment]
Will this land in Jetty 10 branch too?

**Comment by sbordet** [comment]
@akurtakov yes we merge from branch `jetty-9.4.x` forward to Jetty 10 and 11.

**Comment by janbartel** [comment]
Fixed by #5838.
