### ISSUE TITLE
Changing the HTTP response code during the hot deploy new war/jar process

### ISSUE THREAD

**Issue by Kristianusr** [eclipse/jetty.project#5831]
During the ‘hot deployment’ jetty process when a new war / jar package is deployed, it returns an HTTP ‘_503 Service Unavailable_’ message, which suggests that the Jetty server is down or out of order.
Some of the tools for monitoring http websites, in case of receiving the 503 message alerts about the service failure.

From the functional point of view it would be more appropriate to return the HTTP ‘_404 Not Found_’, which indicates that the browser was able to communicate with a given server and the server could not find what was requested but may be available in the future.

link to the documentation:
[(https://www.eclipse.org/jetty/documentation/jetty-9/index.html#hot-deployment)]

**Comment by gregw** [comment]
Why do you think a 404 is more appropriate?    That suggests that the target of the URL was not found and gives no hint that the server might be able to serve that URL in future.    The service has been found, it has just not yet been started so it is unavailable, but it may become available, so a 503 appears to be the appropriate response.

Having said that, we only respond with a 503 from a context if it has had a problem starting, so something else must be going on for you to see a 503.  Can you give us more details of exactly the state of your server and application and perhaps some debugging to show where the 503 is coming from.   It may be that your application itself is throwing an UnavailableException or that some other jetty mechanism (eg graceful shutdown) is involved.

**Comment by Kristianusr** [comment]
Sorry for the little confusion. You're right.

Let's assume the server is running in standalone mode on Linux machine.
During hot-deployment, the server returns the http 404 code, and it would be better if it returned the http 50x code, informing that the service is unavailable at the moment. In the first message I wrote the opposite case.

When we have a service that sends HTTP requests to the Jetty server and parses the results, it would be more advantageous to get the information that the server is not available at the moment than returning that the server page is not found. If we assume that a given servlet returns content of a certain type or does not return it in inches. In this case, the client could switch to the backup server jetty using the normal failover mechanism. Returning a 40x error may suggest an url error.

An error of 50x types suggests that the server is not available.
For example, if you turn off server jetty then the linux machine returns a 50x error.
HTTP/1.1 502 - Connection Failed
‘System.Net.Sockets.SocketException No connection could be made because the target machine actively refused it’.

In the case of the embedded server (uber jar), we simply restart the whole server and in this case a 50x error is returned. 

Changing this unify the behavior of the Jetty server, regardless of whether it is standalone or built-in.

Proposed change:
--- jetty-server/src/main/java/org/eclipse/jetty/server/handler/DefaultHandler.java
+++ jetty-server/src/main/java/org/eclipse/jetty/server/handler/DefaultHandler.java
@@ -117,7 +117,7 @@
 
   if (!_showContexts || !HttpMethod.GET.is(method) || !request.getRequestURI().equals("/"))
  {
---  response.sendError(HttpServletResponse.SC_NOT_FOUND);
+++  response.sendError(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
         return;
  }

**Comment by sbordet** [comment]
@gregw @janbartel is it ok to let this issue be closed, or does it need some work?

**Comment by janbartel** [comment]
I think it should be closed. It's not appropriate for the DefaultHandler to always return `503` if it didn't find a context to match the url. I think the OP could create their own `DefaultHandler` to do as they wish.
