### ISSUE TITLE
Use UTF-8 encoding for client basic auth if requested

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#5845]
**Jetty version**: 9.4.35.v20201120
**Java version**: AdoptOpenJDK 11.0.9
**OS type/version**: Windows 10 64 bit

**Description**
When using the `HttpClient` with basic authentication, Jetty always encodes the credentials using ISO 8859:
https://github.com/eclipse/jetty.project/blob/cbdfaaa335904a7ecc2a7b20208de00f798a5e04/jetty-client/src/main/java/org/eclipse/jetty/client/util/BasicAuthentication.java#L89

While this is fine for a default charset, servers can use a special `charset` parameter of the `WWW-Authenticate` header to tell the client to encode the credentials using UTF-8, as specified here: https://tools.ietf.org/html/rfc7617#section-2.1

For being able to connect to servers that expect UTF-8, Jetty should honor the `charset` parameter.
Additionally, it should be possible to specify UTF-8 encoding when authenticating preemptively, e.g. by passing a `Charset` to the constructor of `BasicResult`.

**Comment by sbordet** [comment]
@mperktold can you try branch `jetty-9.4.x-5845-basic_auth_charset` to see if it works for you?

**Comment by mperktold** [comment]
@sbordet works fine, thanks! 👍
