### ISSUE TITLE
Behavior of after-response exceptions

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#585]
When a webapp has a chain of filters, it may happen this case:
- FilterA is traversed inwards
- FilterB sends a redirect using Servlet's API `sendRedirect()` and returns
- Filter A is traversed outwards, and throws an exception

Currently, for HTTP/1.1, Jetty catches the exception, sees that the response is committed and closes the connection. 
This is bad because the client received a full response (the 302) without any indication that the server will close it, and it is entitled to reused that connection (for example by using it to follow the 302). However, because the server closed the connection, it will never received the next request, which will just die on the client. 

This issue is about how this case is interpreted by the Servlet specification, if at all.

Is `sendRedirect()` an API that only returns when the whole response is completed, or can it write content asynchronously ?

Should the container detect when a response has already been **fully** sent to the client, and ignore exceptions that may happen later ?

What if there is a page error handler ? Should it run anyway, or the exception just be ignored ?

What if FilterB is a Servlet and writes content asynchronously ?

If the response is only committed but not completed, what should the container do ?

Is this something that the container should not worry about, but the client should handle ?

**Comment by sbordet** [comment]
@gregw, when you have time, let's review this together.

**Comment by gregw** [comment]
This really had nothing to do with filters. The question is should we abort on an exception if the response is committed. 

Http2 and http1.1 chunked responses can indicate abnormal termination after commit,  but http1 cannot. 

None can indicate abnormal termination after the response is completed. 

Perhaps we should only abort if the response is committed but not complete. If it is complete then we should probably just log and ignore.

**Comment by sbordet** [comment]
@gregw 

so you would be fine to have a `Response.isComplete()` that we can use when we catch exceptions.
Algorithm would be (if there is no error page, send the 500):

- `committed && completed` => don't invoke page error mechanism, keep connection open
- `committed && !completed` => don't invoke page error mechanism, close connection.
- `!committed && !completed` => invoke page error mechanism 

What if the request is still uploading ?

**Comment by gregw** [comment]
looks good to me - but say abort transport rather than close connection.... might just be a reset stream

Ignore request state, even if it is still upoading, the client might think it is complete and it may be entirely in buffers if the server does not consume, then we might abort on the grounds of unconsumed input elsewhere, so that case is probably already handled.

**Comment by gregw** [comment]
I've had a look at doing this, but it is rather evasive.     The code that calls the abort() method on an error does not have access to the completeness status of the response - certainly not in a transport independent way.  There is also code that is clearing HTTP<2 persistence on errors that needs to be investigated.

So I'm less keen on changing anything here... maybe in 9.4.x where I could add an extra method on HttpTransport or change the contract of abort.

Fundamentally the server is allowed to close a connection at any time, so really the client needs to deal with this.

**Comment by joakime** [comment]
@gregw wasn't this handled with PR #3912 ?

**Comment by gregw** [comment]
yes
