### ISSUE TITLE
NPE at WebSocketSession.java,     public Principal getUserPrincipal() method

### ISSUE THREAD

**Issue by padisah** [eclipse/jetty.project#5850]
**Jetty version**
10.0
**Java version**
11.0
**OS type/version**
Xubuntu 20.04
**Description**

the     WebSocketSession.getUserPrincipal reads for **this.frameHandler.getUpgradeRequest()**
but the JavaxWebSocketFrameHandler.upgradeRequest is null

the setter for upgradeRequest has no reference, and in my debugging, it wasn't called
the method JavaxWebSocketFrameHandlerFactory.newJavaxWebSocketFrameHandler

[https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java#L116](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java#L116)

... creates the JavaxWebSocketFrameHandler instance, without setting the upgradeRequest to it, while it receives as a parameter

The actual issue we are facing is that after upgrade from 9.4 jetty to 10.0 jetty, there is a nullpointer exception in a series of Vaadin applications. The error was present with Vaadin 8, Vaadin 14, and Vaadin 18, latest minor versions.

The Vaadin exception occures on first pageload, or login attempts.
I didn't find resources yet on Vaadin jetty upgrades yet, this is quite new, probably few people tried it yet.

**Comment by lachlan-roberts** [comment]
@padisah this has now been fixed in the 10.0.x branch, the fix will be available in a `10.0.1` release.
