### ISSUE TITLE
org.eclipse.jetty.websocket.servlet.WebSocketServlet cleanup

### ISSUE THREAD

**Issue by VasilVasilev93** [eclipse/jetty.project#5851]
**Jetty version**
9.4.30.v20200611

**Description**
Hello and happy new year, wish you all the best!
Ater using `websocket-servlet` in osgi environment, I found that a single instance of `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory` always remains in memory after uninstall of the bundle jar. Looking at the code it seems that the factory object is not getting removed from the context's attributes map. Inside the `init` method:
`ctx.setAttribute(WebSocketServletFactory.class.getName(), factory);`

In the `destroy` method only `factory.stop();` gets called. If we also remove it from the context's attributes map, the object gets cleaned up. We have that fixed in our product, but I wonder if it's intended or a miss.

**Comment by lachlan-roberts** [comment]
I think the ServletContext attributes should be cleared when the context is stopped, so if you're getting to `destroy` then the attributes should be cleared shortly after. @janbartel any idea why this would be happening?

Your suggested cleanup sounds reasonable so I will put a PR up for this, thanks.

**Comment by lachlan-roberts** [comment]
We now remove the `WebSocketServletFactory` ServletContext attribute in the `destroy` method.
