### ISSUE TITLE
Upgrade response stored by the WebSocketSession is recycled.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#5865]
**Jetty version**
10.0.x

**Description**
The `UpgradeResponse` stored by the `WebSocketSession` is recycled by Jetty after the websocket upgrade.
At the point where the upgrade response is committed we need to copy the correct response details so we can store them in the `WebSocketSession`.

**Comment by gregw** [comment]
I think `UpgradeResponse` should be like `UpgradeRequest` and NEVER have a reference to the `HttpServletResponse`.   The whole point of these classes is to break that dependency so that they can exist beyond the lifecycle of the request/response.

**Comment by lachlan-roberts** [comment]
@gregw on the server the `UpgradeResponse` is also used in the negotiation and allows you to set different extensions and headers in the response which is sent back to the client.

**Comment by gregw** [comment]
@lachlan-roberts, sure, but can't it do that without a reference to the real response.  Remember everything and then when the real response is sent, they are taken from the upgrade response?
