### ISSUE TITLE
Improve JMX support for Jetty logging

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5872]
**Jetty version**
10.0.x

**Description**
Since the Jetty Logging is initialized before anything else, it cannot rely on Jetty JMX annotations.

However, it would be great if JMX support is improved (for example by specifying parameter names to operations like `JettyLoggerFactoryMBean.setLoggerLevel(String, String)`.

JMX has a basic support for annotations via `java.management.DescriptorKey`, which IIUC looks for a key in a resource bundle properties file -- may not be that bad for this once-only need.

**Comment by joakime** [comment]
We merged this into Jetty 10.x as part of PR #5876
I think this is done.
