### ISSUE TITLE
FileSystemResourceTest.testAccessUniCodeFile fails on *nix when LANG env var does not contain some UTF flavor

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#5883]
**Jetty version**
9.4.x, 10.0.x, 11.0.x

**Java version**
1.8, 11, probably newer ones too

**OS type/version**
Linux, probably all other *nix flavors too

**Description**
When the LANG env var is absent or is set to "C" the JVM is unable to read files that contain non-ASCII characters in their name.  Since FileSystemResourceTest.testAccessUniCodeFile tests exactly this behavior, the build should make sure that the environment is properly set to make sure it won't fail on a mis-configured machine.

**Comment by joakime** [comment]
I can think of 2 approaches to this ...

1. add an assumption on the exception from file create is probably enough to skip the test if the runtime (jvm and/or filesystem) doesn't support it.
2. make this more generic with a new `void assumeRuntimeSupportsUTF8()` method that is called at the start of each test method that needs UTF8 support?

**Comment by lorban** [comment]
MacOS Catalina 10.15.7 seems to be totally unaffected by the contents of the LANG env variable: the test passes no matter what that env variable is set to.

**Comment by joakime** [comment]
Be aware of ...

https://github.com/eclipse/jetty.project/blob/bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb/jetty-server/src/main/java/org/eclipse/jetty/server/SameFileAliasChecker.java#L43-L45

**Comment by lorban** [comment]
@joakime Your proposal of adding some assumptions in the junit tests themselves sounds appealing, but I can't think of a way to make that happen in java code as it seems that it's the JVM's internal conversion of java to C strings using libc that is the culprit here.

**Comment by lorban** [comment]
Note that `LC_ALL` and `LC_CTYPE` can also impact this test, and they take precedence over `LANG` according to https://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html

**Comment by lorban** [comment]
Windows completely ignores these env variables, the test passes no matter what these env variables are set to.
