### ISSUE TITLE
Limit usage of HTTP/2 connections

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5888]
**Jetty version**
9.4.x

**Description**
HTTP/2 connections have an implicit max usage count determined by the fact that stream ids can go up to `2^31-1` and cannot be negative.

As such, the HTTP/2 client connection pool should default to close connections as they reach that limit (or maybe just before that).

**Comment by lorban** [comment]
@sbordet I've submitted a draft PR that enforces such limitation in `HttpClientTransportOverHTTP2`. Did you have something more sophisticated in mind?

**Comment by sbordet** [comment]
@lorban streams are incremented by 2, so it should be something like `(2^31-1)/2` as the max usage count.
And we have to make sure that we don't accidentally go off-by-one (i.e. use the stream one more time that would produce a stream id of `2^31`).

`2^31-1 = 2147483647`

On the client, stream usage `N` produces stream id `N*2-1`, so we _should_ be safe with `N=1073741823`.
However, we need to take into account HTTP upgrades which have an implicit stream id of 1 -- not sure how that is counted.

On the server, stream usage `N` produces stream id `N*2`, so we _should_ be safe with `N=1073741823`.

I would probably be on the safe side and stay at `N=1073741822` or perhaps even less.

On the client, it's easy to set this value on the `Pool`.

On the server, though, there is no `Pool` so we need to explore some other mechanism to enforce this.

There are 2 choices for the server:
. stop pushing without closing the connection.
. gracefully close the connection so the client is forced to open a new one.

I'd go with the simpler, which I feel is stop pushing -- after all it's unlikely that the server pushes 1 billion resources to the client through the same connection (although it's possible).

We need test cases for the server case (I think the client case is already covered in the `Pool` tests).

**Comment by sbordet** [comment]
@lorban status of this issue?

**Comment by lorban** [comment]
@sbordet enforcing (and testing) this on the server is far from trivial so the balance between the benefits vs the required effort has been negative so far.

**Comment by sbordet** [comment]
@lorban I don't think it's that difficult. Can you detail?
BTW, don't we do this already for HTTP/3 as well?
