### ISSUE TITLE
jetty how to config useBodyEncodingForURI and URIEncoding

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5890]
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
**Question**

i hava a war deploy in tomcat:

<Connector URIEncoding="UTF-8" connectionTimeout="20000" port="8090" protocol="HTTP/1.1" redirectPort="8443" useBodyEncodingForURI="true"/>

but, in jetty, i don't know how to config useBodyEncodingForURI and URIEncoding

**Comment by joakime** [comment]
We don't know what those configuration values are intended to do.
Can you explain?

**Comment by james-z-repo** [comment]
How does jetty allow unsafe characters ？

I have a request under ie that contains Chinese parameters, but ie can't specially convert characters. My request was returned to 400

http://localhost:8080/example/jsp/jndiTest.jsp?name=任务中心

in tomcat i can configure this, in jetty how to configre?
```
tomcat.util.http.parser.HttpParser.requestTargetAllow=|{
```


I have another question， Can jetty dynamically parse request parameters according to the character encoding of contenttype in the request?
i see org.eclipse.jetty.server.Request decoding can only be setQueryEncoding， not dynamically

**Comment by sbordet** [comment]
As per specification, query parameter values must be URL-encoded, so it must be:

`jndiTest.jsp?name=%E4%BB%BB%E5%8A%A1%E4%B8%AD%E5%BF%83`.

To support your use case, you can do this:

```java
protected void service(HttpServletRequest req, HttpServletResponse resp) {
    // First, set the attribute.
    req.setAttribute("org.eclipse.jetty.server.Request.queryEncoding", "UTF-8");

    // Then, get the parameter.
    String name = req.getParameter("name");
}
```

This works as long as the client (browser or other) sent the URI with the proper format, and this is not always the case.
For example, from HTML you have to set `accept-charset` attribute explicitly.

Your best long term solution is to avoid these URL and follow the standard by URL-encoding parameter values.
From JavaScript you can use function `encodeURIComponent()`.

**Comment by joakime** [comment]
IIRC, When you move to HTTP/2 or HTTP/3 you will no longer be able to send that badly formatted URL/URI query section.

Also note, that just because your browser shows those characters in it's location bar does not mean it sent those character in the raw.
Nearly all browsers will convert unicode characters to UTF-8 before sending to the destination server, but will present the unicode glyphs on the location bar.
