### ISSUE TITLE
build-resources module does not specify source encoding

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#5891]
**Jetty version**
9.4.x

**Description**

The `build-resources` module does not inherit from any other module and lacks the following maven property:

```
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```

which makes maven log this classic warning:

```
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
```

**Comment by sbordet** [comment]
@joakime is there a reason `build-resources` does not inherit from the parent POM?

**Comment by joakime** [comment]
@sbordet it cannot inherit the parent, as the parent needs/has a dependency on, build-resources.

**Comment by sbordet** [comment]
@joakime `build-resources` is a module of the main POM, which therefore cannot have a dependency on it (otherwise it would be cyclic).
