### ISSUE TITLE
Normalized IPv6 port changes is a breaking change in the format of the string literals

### ISSUE THREAD

**Issue by hilts-vaughan** [eclipse/jetty.project#5899]
**Jetty version**

9.4+

**Java version**
Any

**OS type/version**
Any

**Description**

Per https://github.com/eclipse/jetty.project/pull/5128, a change was made to add square brackets for :authority which would be spec complaint. However, anyone that calls `getRemoteAddr` (including a servlet wrapper or some other client) now gets this value too since it's non-conditional and lower level. This means that clients of this will get back bracketed values when they did not use to. 

This seems to be a side-effect not in line with the commit name; is this breaking change intentional? This is troublesome for example, because, Guava's `INetAddresses::forString` (https://guava.dev/releases/19.0/api/docs/com/google/common/net/InetAddresses.html#forString(java.lang.String)) does not handle these by default and so code updating Jetty will break because of this if they're just piping the data into `forString`

**Comment by hilts-vaughan** [comment]
https://github.com/eclipse/jetty.project/issues/1503#issuecomment-760222131

There appears to be some talk about this recently.

**Comment by hilts-vaughan** [comment]
I also suspect that this decision would matter less if one of the more popular libraries being used (Guava) just supports both out of the box, so perhaps that is the route to take.

**Comment by lachlan-roberts** [comment]
You can now customize how `getRemoteAddr` is formatted by overriding the `newConnection()` method on `HttpConnectionFactory`. The default implementation of `HttpChannel.formatAddrOrHost` will normalize the address with `HostPort.normalizeHost(addr)` by adding the square brackets, so you can manually override this to not do that.

```java
@Override
public Connection newConnection(Connector connector, EndPoint endPoint)
{
    HttpConnection conn = new HttpConnection(getHttpConfiguration(), connector, endPoint, getHttpCompliance(), isRecordHttpComplianceViolations())
    {
        @Override
        protected HttpChannelOverHttp newHttpChannel()
        {
            return new HttpChannelOverHttp(this, getConnector(), getHttpConfiguration(), getEndPoint(), this)
            {
                @Override
                protected String formatAddrOrHost(String addr)
                {
                    return addr;
                }
            };
        }
    };

    return configure(conn, connector, endPoint);
}
```
