### ISSUE TITLE
Jetty ssl KeyStorePath and TrustStorePath still doesn't work with absolute path

### ISSUE THREAD

**Issue by wass9085** [eclipse/jetty.project#5905]
**Jetty version** 
9.4.36.v20210114

**Java version**
zulu11.39.15

**OS type/version**
windows

**Description**
I updated jetty to 9.4.36.v20210114. During testing, I still get same error with keystorepath.

Illustration:
![image](https://user-images.githubusercontent.com/8788364/105443812-3effbe00-5c32-11eb-8e20-8e050fe51dde.png)

This is an example of my jetty-ssl-context.xml file:
`<Set name="KeyStorePath">
    <Property name="jetty.sslContext.keyStoreAbsolutePath">
      <Default>
        <Property name="jetty.base" default="." />/<Property name="jetty.sslContext.keyStorePath" deprecated="jetty.keystore" 
              default="D:/workdir/uxxx/rxxxy_jetty_9.4.35.v20201120/out/rt/key_manager_server/ssl/server.jks"/>
      </Default>
    </Property>
</Set>`

**Comment by wass9085** [comment]
`<Set name="KeyStorePath">
    <Property name="jetty.sslContext.keyStoreAbsolutePath">
      <Default>
        <Property name="jetty.base" default="." />/<Property name="jetty.sslContext.keyStorePath" deprecated="jetty.keystore" default="D:/workdir/devunits/rc6svy_jetty_9.4.35.v20201120/out/rt/key_manager_server/ssl/server.jks"/>
      </Default>
    </Property>
  </Set>`

**Comment by sbordet** [comment]
@wass9085 can you try without `./` at the beginning?

**Comment by wass9085** [comment]
Hi  @sbordet removing the ./ fixed the issue for me. However, we didn't experience this issue in the in jetty versions before  **9.4.34.v20201102** . Basically, what I am asking is what changed, in jetty 9.4.34.v20201102 that we now need to remove the ./

**Comment by sbordet** [comment]
@wass9085 you are setting the absolute path as the default for the `jetty.sslContext.keyStorePath`, which is the relative one.

Do not modify XML files.

Instead, modify `ssl.ini` and set the property:

```
jetty.sslContext.keyStoreAbsolutePath=D:/workdir/uxxx/rxxxy_jetty_9.4.35.v20201120/out/rt/key_manager_server/ssl/server.jks
```
