### ISSUE TITLE
Lots of ClassNotFoundException for jmx.ObjectMBeanContainer on Jetty startup

### ISSUE THREAD

**Issue by ThiyagarajanManivannan** [eclipse/jetty.project#5907]
**Jetty version**
9.3.21.v20170918
**Java version**
openjdk version "1.8.0_222"

**OS type/version**
Description: Red Hat Enterprise Linux Server release 7.7 (Maipo)
Release: 7.7
Codename: Maipo

**Description**
In our Restful service we use Jetty server of version 9.3.21.v20170918 (Java version : jdk1.8.0_222).
When we continuously send HTTP2 Request towards the server using HTTP2 Simulator client . We could observe lot of exceptions of ClassNotFoundException for jmx.ObjectMBeanContainer on Jetty startup in Java Flight Recorder.
This impacts the performance of the system, Do you have any suggestions why the exception is thrown?

**Comment by ThiyagarajanManivannan** [comment]
[JFR.zip](https://github.com/eclipse/jetty.project/files/5855309/JFR.zip)
JFR attached for ClassNotFoundException

**Comment by sbordet** [comment]
Please upgrade to the latest Jetty 9.4.x as the Jetty JMX support has been optimized.
