### ISSUE TITLE
Missing jar files in Eclipse hosted P2 repository

### ISSUE THREAD

**Issue by robertofelgin** [eclipse/jetty.project#5913]
Starting with 9.4.35, there are 3 missing jars from the Jetty osgi bundle. The source jar files are there but not the compiled versions.

- org.eclipse.jetty.apache-jsp
- org.eclipse.jetty.osgi.boot.jsp
- org.eclipse.jetty.security.jaspi

Downloading from 
http://www.eclipse.org/downloads/download.php?file=/jetty/updates/jetty-bundles-9.x/9.4.36.v20210114/Jetty-bundles-repository-9.4.36.v20210114.zip

I'm assuming this is a packaging oversight?

**Comment by joakime** [comment]
We don't create/manage the Eclipse P2 repositories you are using.

Those P2 repositories are managed by the Eclipse IDE folks for specific usage of the Help System within the Eclipse IDE. 
(The help system doesn't need/use apache-jsp, osgi-boot, or jaspi)

Of note, the work on Eclipse Tycho and the build system means that even those P2 repositories are going away in the near future.
In favor of using the same Global Repository System that many build systems (maven, gradle, ivy, kotlin, scala, grape, buildr, bazel, etc) currently use.

You should either build and maintain the P2 repositories you need, or migrate to the Tycho build techniques.
