### ISSUE TITLE
Maven jetty:run automatic restarting at simple client's URL request

### ISSUE THREAD

**Issue by robozb** [eclipse/jetty.project#5914]
Jetty version:
9.4.36.v20210114

Java version:
jdk1.8.0_261

OS type/version:
Win10 - 1909

If I use maven jetty:run, a client can trigger the automatic restart of the jetty server with a socket connection, with a simple URL openStream. I don't understand why, because with a simple browser request the restart doesn't happen. The restart can cause that the server is unavailable. 

Maven plugin: jetty:run
---------------------------

``` xml

            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.4.36.v20210114</version>
                <configuration>
                    <scanIntervalSeconds>5</scanIntervalSeconds>      
                    <webApp>
                        <contextPath>
                            /pmszerver
                        </contextPath>
                    </webApp>
                    <httpConnector>
                        <port>80</port>
                    </httpConnector>                    
                </configuration>
            </plugin>
```

Java simple URL request: 
----------------------------

``` java
import java.net.URL;
import java.util.Scanner;

public class NewClass {
    public static void main(String[] args) throws Exception {
        
        String out = new Scanner(new URL("http://localhost/pmszerver/Szimpla?p1=23").openStream(), "UTF-8").useDelimiter("\\A").next();
        System.out.println(out);

    }
}
```

**Comment by joakime** [comment]
What is this `Scanner` class you are using?

**Comment by robozb** [comment]
I updated my first post, thanks!

**Comment by janbartel** [comment]
@robozb  without knowing what the Scanner class is doing, it's impossible to say. Perhaps you could try capturing the http dialog with wireshark or something similar to see what requests are being sent and what responses are generated.  

For maven jetty:run, the only files we monitor that could cause a restart are:

+ pom.xml
+ web.xml, web-default.xml, web-override.xml, jetty-env.xml, jetty-web.xml
+  the dependencies
+ the test classes, if you've configured the plugin to include test classes
+ the webapps' classes
+ the WEB-INF/lib dir if it exists
+ any scan targets you've explicitly configured

Maybe the Scanner class is creating a file in WEB-INF/lib?

**Comment by robozb** [comment]
Dear Janbartel! 

I use Netbeans 12.0. OK, I'll check the details again. This is very interesting, I used simple HTTP requests with java URL class or Apache HTTP client, and all the time something triggers Jetty to restart. I guess something wrong in the same jvm, but I tried it with a parallel IDE (Netbeans 11 or 12.2, client and server in different IDE) as well with the same result. 

Thanks: Beci

**Comment by robozb** [comment]
In Eclipse I don't experience the problem, but if the server is in eclipse and the client in Netbeans the Jetty restart automatically itself at a simple HTTP request. The Netbeans run output is: 

`cd C:\Users\Beci\Desktop\TMP\TesztHTTPClient; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_261" cmd /c "\"C:\\Program Files\\NetBeans-12.0\\netbeans\\java\\maven\\bin\\mvn.cmd\" -Dexec.args=\"-classpath %classpath com.mycompany.teszthttpclient.NewClass\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_261\\bin\\java.exe\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans-12.0\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 --errors -e org.codehaus.mojo:exec-maven-plugin:1.5.0:exec"
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Error stacktraces are turned on.
Scanning for projects...

-------------------< com.mycompany:TesztHTTPClient >--------------------
Building TesztHTTPClient 1.0-SNAPSHOT
--------------------------------[ jar ]---------------------------------

--- exec-maven-plugin:1.5.0:exec (default-cli) @ TesztHTTPClient ---
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  1.068 s
Finished at: 2021-01-28T13:54:27+01:00
------------------------------------------------------------------------`

**Comment by janbartel** [comment]
@robozb have you diagnosed this, or do you have any further info on this?

**Comment by janbartel** [comment]
@robozb any info or can this be closed?

**Comment by robozb** [comment]
Sorry but i didn't have enough time for analyze this

**Comment by janbartel** [comment]
Closing due to lack of any further info after more than 12 months. As jetty-9 is EOL, if any further info becomes available, it must pertain to jetty-10 or above.
