### ISSUE TITLE
Review property precedence in start mechanism

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5915]
**Jetty version**
9.4.x

**Description**
A `$JETTY_BASE/modules/foo.mod` with an `[ini]` section that specifies a property is not overwritten neither by the correspondent `$JETTY_BASE/start.d/foo.ini`, nor by an explicit command line property.

**Comment by gregw** [comment]
Are you sure?  Properties are well ordered and we even use += and ?= operators that rely on ordering to work.

But to contradict myself, perhaps [ini] sections are intended to be durable, else they would be in a [ini-template] ???

**Comment by sbordet** [comment]
Duplicate of #6017.
