### ISSUE TITLE
Provide a Healthcheck Module

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#5920]
**Jetty version** Jetty 10+

**Java version** N/A

**OS type/version** N/A

**Description**

I wonder if it makes sense for us to offer a healthcheck module along the lines of this Informational RFC

https://tools.ietf.org/html/draft-inadarei-api-health-check-05

Something like the example below, much like elements of the output from the statistics handler but formatted to this convention and put under a more standard url.  While the specification is just informational, it does have implementations in some other languages and it some discussions under the issues.  We could add a couple of nested urls as well so the default response is pared down and more succinct.  Could also offer more response options suitable for load balancers and things like that.  If we wired it up as a module it could be activated from commandline and configuration fiddled in the normal fashion.  I haven't seen other rfcs of the like but something more common might exist.

https://github.com/inadarei/rfc-healthcheck

Thoughts?
 

>  GET .well-known/health HTTP/1.1
 >  Host: webtide.com
  >   Accept: application/health+json

 >    HTTP/1.1 200 OK
 >   Content-Type: application/health+json
 >    Cache-Control: max-age=3600
 >    Connection: close
 >  {
     "status": "pass",
     "version": "10",
     "releaseId": "10.0.1",
     "notes": [""],
     "output": "",
     "serviceId": "<unique-uuid>",
     "description": "health of jetty service",
     "checks": {
       "jetty:avgResponseTime": [
         {
           "componentId": "statistic-avg-response-time",
           "componentType": "statistic",
           "observedValue": 250,
           "observedUnit": "ms",
           "status": "pass",
           "affectedEndpoints" : [],
           "time": "2018-01-17T03:36:48Z",
           "output": ""
         }
       ],
       "jetty:connections": [
         {
           "componentId": "statistic-open-connections",
           "componentType": "statistic",
           "observedValue": 75,
           "status": "warn",
           "time": "2018-01-17T03:36:48Z",
           "output": "",
           "links": {}
         }
       ],
       "uptime": [
         {
           "componentType": "system",
           "observedValue": 1209600.245,
           "observedUnit": "s",
           "status": "pass",
           "time": "2018-01-17T03:36:48Z"
         }
       ],
       "cpu:utilization": [
         {
           "componentId": "jdk-cpu-0",
           "node": 1,
           "componentType": "system",
           "observedValue": 85,
           "observedUnit": "percent",
           "status": "warn",
           "time": "2018-01-17T03:36:48Z",
           "output": ""
         },
         {
           "componentId": "jdk-cpu-2",
           "node": 2,
           "componentType": "system",
           "observedValue": 35,
           "observedUnit": "percent",
           "status": "pass",
           "time": "2018-01-17T03:36:48Z",
           "output": ""
         }
       ],

**Comment by joakime** [comment]
Also, "health check" is an existing EE standard used in MicroProfile.

* https://projects.eclipse.org/projects/technology.microprofile
* https://microprofile.io/
* https://github.com/eclipse/microprofile-health/releases/tag/3.0

**Comment by jmcc0nn3ll** [comment]
Right, that is mentioned somewhere in one of the issues I was reading through on the github project.  I have noticed the concept on the rise recently, or I have just been reading more things in related areas, which is what prompted me to look around for some sort of standard.
