### ISSUE TITLE
Jetty 10.0.0 cannot be used with a production-ready version of Logback

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#5943]
**Jetty version**

10.0.0

**Java version**

11.0.7

**OS type/version**

All

**Description**

I am trying to add support for Jetty 10 to Spring Boot. Our default logging system is Logback and we use the latest production-ready version of Logback which, at the time of writing, is 1.2.3. Unfortunately, this does not work with Jetty 10 due to its dependency on an alpha of the SLF4J 2.0 API which requires an alpha of Logback 1.3. Attempting to use Logback 1.2.3 results in some errors on startup:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/awilkinson/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

Could you please consider supporting SLFJ 1.7 to avoid the need for alpha-quality dependencies?

**Comment by joakime** [comment]
SLF4J 1.7 does not support JPMS, which is one of our focuses on Jetty 10+.

SLF4J 2.0 does.

**Comment by joakime** [comment]
The slf4j-api is stable.
If you don't need jpms, then swap the slf4j-api-2.x.jar on the server for slf4j-api-1.7.x.jar and use your logback-classic-1.2.3.jar instead.
If you need jpms, then you have to use slf4j-api-2.x.jar (as slf4j-api-1.7.x.jars are not compatible)

**Comment by wilkinsona** [comment]
Comparing the 1.7 API and the 2.0 API, I don't believe it is stable. For example, [`Logger`](https://github.com/qos-ch/slf4j/blob/e2c29c81df6fb405a3c5a6dfd1cf28ba26a7c1d6/slf4j-api/src/main/java/org/slf4j/Logger.java) has 6 methods (at the time of writing) that are new in 2.0.

If Jetty isn't using any of the new in 2.0 methods then downgrading to 1.7.x should work but it makes me a little wary of compatibility problems in the future. Perhaps it would be safer to compile against 1.7.x and to use 2.x at runtime only when JPMS is in the picture? This would also avoid users getting alpha dependencies on their classpath by default.

**Comment by joakime** [comment]
The new 2.0 APIs in slf4j-api-2.x.jar are part of the fluent APIs introduced in the 2.x series.
We do not use the fluent slf4j API in Jetty (mainly due to lack of support in other tooling, the ides, checkstyle, errorprone, spotbugs, etc.. which incorrectly flags use of the fluent API as a bug in logging)

**Comment by joakime** [comment]
Experiments in other projects have indicated that using the fluent slf4j API is more memory intensive (lots more garbage created).
We'll be unlikely to use the fluent API in the future for that reason alone.

**Comment by wilkinsona** [comment]
Thanks, @joakime. We'll downgrade SLF4J to 1.7.x.
