### ISSUE TITLE
Introduce alias --files for --download

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5944]
**Jetty version**
10.0.x

**Description**
Command line option `--download` does what the `[files]` section does, so it should be aliased to `--files`.

**Comment by joakime** [comment]
The syntax would be `--file=<arg>` where arg is actually defined in `FileArg` class.

https://github.com/eclipse/jetty.project/blob/4c67b886a4f3ef61392a1cf70184105949b15c88/jetty-start/src/main/java/org/eclipse/jetty/start/FileArg.java#L40-L47

**Comment by joakime** [comment]
We need another example for `maven:<groupId>:<artifactId>` style uris too.

See:

https://github.com/eclipse/jetty.project/blob/4c67b886a4f3ef61392a1cf70184105949b15c88/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializer.java#L35-L42

**Comment by joakime** [comment]
Not sure we want to attempt to support comma delim `--files=<arg>(,<arg>)*` syntax here.
What if the filename has a comma?
You want a file called `resources/foo,bar.xml` to be present.

`--files=resources/foo,bar.xml` ?
