### ISSUE TITLE
Introduce alias for --include-jetty-dir

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5946]
**Jetty version**
10.0.x

**Description**
`--include-jetty-dir` effectively specifies a `JETTY_BASE` with less priority than the current `JETTY_BASE`.
Rename to `--parent-base-dir`, maybe?

**Comment by gregw** [comment]
I don't like parent as it is unclear if parents have more or less priority.
How about `--base-base-dir` or `--default-base-dir` or `--add-base-dir` or `--extra-base-dir` ?
