### ISSUE TITLE
-Dn?=v in *.ini file leaks n? system property

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5948]
**Jetty version**
10.0.x

**Description**
Adding `-Dfoo?=bar` in an `*.ini` file or on the command line produces a system property with name `foo` but also a system property with name `foo?`, which should not be there.

**Comment by joakime** [comment]
This probably true for Jetty 9.4.x too.

**Comment by joakime** [comment]
Fixed in issue #6017
