### ISSUE TITLE
Error while using QuickStartWebApp

### ISSUE THREAD

**Issue by vitormcruz** [eclipse/jetty.project#5955]
**Jetty version**
jetty-9.4.36.v20210114

**Java version**
8

**OS type/version**
Windows 10

**Description**
Trying to use QuickStartWebApp, I have put the following in my /WEB-INF/jetty-web.xml:

```
<Configure class="org.eclipse.jetty.quickstart.QuickStartWebApp">
    <Set name="autoPreconfigure">true</Set>
</Configure>
```

but I got the following error while starting up the server:

```
2021-02-08 12:25:52,116] Artifact payroll-groovy:war: Artifact is being deployed, please wait...
2401 [Scanner-1] WARN  o.e.jetty.xml.XmlConfiguration - Config error at <Set name="autoPreconfigure">true</Set> 
2402 [Scanner-1] WARN  o.e.jetty.deploy.DeploymentManager - Unable to reach node goal: started 
java.lang.NoSuchMethodException: class org.eclipse.jetty.webapp.WebAppContext.setAutoPreconfigure(class java.lang.String)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:742)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.createContextHandler(WebAppProvider.java:299)
	at org.eclipse.jetty.deploy.App.getContextHandler(App.java:99)
	at org.eclipse.jetty.deploy.bindings.StandardDeployer.processBinding(StandardDeployer.java:39)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:517)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:157)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:785)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:754)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
	at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:558)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	Suppressed: java.lang.NoSuchMethodException: org.eclipse.jetty.webapp.WebAppContext.setAutoPreconfigure(java.lang.String)
		at java.lang.Class.getMethod(Class.java:1786)
		at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:601)
		... 18 common frames omitted
	Suppressed: java.lang.NoSuchFieldException: TYPE
		at java.lang.Class.getField(Class.java:1703)
		at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:614)
		... 18 common frames omitted
	Suppressed: java.lang.NoSuchFieldException: autoPreconfigure
		at java.lang.Class.getField(Class.java:1703)
		at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:629)
		... 18 common frames omitted

```

Seems to it is not applying the configuration, as it tries to setAutoPreconfigure in WebAppContext instead of QuickStartWebApp.

**Comment by joakime** [comment]
The `/WEB-INF/jetty-web.xml` is an inappropriate place to use `org.eclipse.jetty.quickstart.QuickStartWebApp` as this file is read far too late in the process for the WebApp.

It's recommended to use the XML deployable in your `${jetty.base}/webapps/<name>.xml` to use that `org.eclipse.jetty.quickstart.QuickStartWebApp`.
If you don't do this, then the webapp is deployed using a `org.eclipse.jetty.webapp.WebAppContext` by default, which doesn't have the `.setAutoPreconfigure` method.

**Comment by vitormcruz** [comment]
So it isn't possible to configure the context class from the `/WEB-INF/jetty-web.xml`? Is this an expected behavior? 

That means I cannot use quick start with with jetty maven plugin? I could only find a property to configure it to find jetty-web.xml, if that wont work I cannot use quick start with the plugin?

**Comment by joakime** [comment]
The `<jettyXml>` configuration option in the `jetty-maven-plugin` is the equivalent to the context deployable XML.  Use that.

So a few notes about your setup.

~Striking that original "first" comment, I got my reviews mixed up.~

Why are you using QuickStart with jetty-maven-plugin?
If you are building your war every time (like what the jetty-maven-plugin is designed to do), then the quickstart adds nothing for you. (you are just moving the goalposts from runtime to build time with no net gain in performance).
That's a really wonky setup that we don't understand.
If you are using jetty-maven-plugin for production, then red-flags all around, as you are abusing the role jetty-maven-plugin serves (development time only) and opening up your application to many vulnerabilities due to the way the maven classloader works.    This maven classloader also impacts the quickstart process, be aware of that!

**Comment by vitormcruz** [comment]
Actually, I just bumped at QuickStart in the docs while trying to make Jetty do not scan my classpath for servlet 3.1 annotations, but was unable to make it work.

> If you are building your war every time (like what the jetty-maven-plugin is designed to do), then the quick start adds nothing for you. (you are just moving the goalposts from runtime to build time with no net gain in performance).
> That's a really wonky setup that we don't understand.

Maybe I understand wrongly what quicksetup does to me? I figured that it bypasses scanning and uses the quickstart-web.xml as an effective web.xml, so I could generate quickstart-web.xml once in a while, since actual servlet configuration changes happens only seldom, and it wouldn't matter if I build my war every time since I wouldn't generate my quickstart-web.xml every time. Are my assumption on quickstart incorrect?

I have seen setups that take about an hour to start locally just because of such classpath scanning (a bunch of scanning actually...). Another interesting result of using quickstart-web.xml is that you can remove or avoid unintended classes loading. So I figured I could use this setup locally using the plugin and configure a docker image accordingly to use that same scheme in production.

If, however, maven classloader impacts quickstart processes I am not sure if that could be used, since it is important to keep consistency between different deployments.

**Comment by joakime** [comment]
> Maybe I understand wrongly what quicksetup does to me? I figured that it bypasses scanning and uses the quickstart-web.xml as an effective web.xml, so I could generate quickstart-web.xml once in a while, since actual servlet configuration changes happens only seldom, and it wouldn't matter if I build my war every time since I wouldn't generate my quickstart-web.xml every time. Are my assumption on quickstart incorrect?

There's 2 parts for quickstart.

1. [Build Time] The generation of the `WEB-INF/quickstart-web.xml`, which will still scan the files, start jetty, and record the state of the "fully started" webapp.
2. [Deployment Time] The use of `org.eclipse.jetty.quickstart.QuickStartWebApp` which will read this `WEB-INF/quickstart-web.xml` and skips the scanning of jars and what not in order to start the webapp's initialization phase as quickly as possible.

Using jetty-maven-plugin means you are doing step 1 every time.

> I have seen setups that take about an hour to start locally just because of such classpath scanning (a bunch of scanning actually...). Another interesting result of using quickstart-web.xml is that you can remove or avoid unintended classes loading. So I figured I could use this setup locally using the plugin and configure a docker image accordingly to use that same scheme in production.

Another approach, If you know what needs to be scanned in your webapp (JAR wise), then you can limit the scope of the scan using the `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern` attribute to only scan jars that match that regex pattern (tip, you can use `|` to give multiple patterns for the match).

``` xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">

    <Call name="setAttribute">
      <Arg>org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern</Arg>
      <Arg>.*/spring-[^/]*\.jar$</Arg>
    </Call>

</Configure>
```

**Comment by vitormcruz** [comment]
> Using jetty-maven-plugin means you are doing step 1 every time.

The documentation led me to think that step 1 don't need to execute every time:

```
autoPreconfigure

    (true/false). If true, the first time the webapp is run, the WEB-INF/quickstart-web.xml is generated 
BEFORE the webapp is deployed. Subsequent runs use the previously generated quickstart file.

```

Then, I think I could run once with this property set to true, store the generated quickstart-web.xml into project and set `autoPreconfigure` to false in production. Also, "Pre-generating the quickstart-web.xml" section suggests this is possible, it is not?


I already explored how to make Jetty ignore scanning — although I could not make it work completely (https://stackoverflow.com/questions/66094778/avoid-classpath-class-scanning-in-jetty-in-addition-to-jars) — but when I saw QuickStart I thought it would be a better approach.

I tried using jettyXml on jetty-plugin and configure quickstart on context xml, but it wont work, but I am not sure whether to continue in this line of action face your comments.

**Comment by joakime** [comment]
The `autoPreconfigure` means that if the `WEB-INF/quickstart-web.xml` doesn't exist, it's created and added to the webapp.
This still requires the use of `org.eclipse.jetty.quickstart.QuickStartWebApp` base in the XML deployable.

> I already explored how to make Jetty ignore scanning — although I could not make it work completely (https://stackoverflow.com/questions/66094778/avoid-classpath-class-scanning-in-jetty-in-addition-to-jars) — but when I saw QuickStart I thought it would be a better approach.
>
> I tried using jettyXml on jetty-plugin and configure quickstart on context xml, but it wont work, but I am not sure whether to continue in this line of action face your comments.

I took a look at that question, the problem they are having is that they attempted to use the property in the `jetty-web.xml` which is far too late in the configuration process for that attribute to take effect. 
That property needs to exist in the XML deployable, at the beginning of the deployment process.
The same stage as your use of `org.eclipse.jetty.quickstart.QuickStartWebApp`.
In other words, both approaches mean you configure the WebApp at the start of the deployment, not deep into the middle of the deployment (aka `jetty-web.xml`).

So this is the process (that you can discover with the Jetty Server state dump facilities) - https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-server-dump

Example (trimmed) output of dump after start option ...

```
[myappbase]$ java -jar ~/code/jetty/distros/jetty-home-9.4.36.v20210114/start.jar jetty.server.dumpAfterStart=true
2021-02-09 08:24:11.150:INFO::main: Logging initialized @385ms to org.eclipse.jetty.util.log.StdErrLog
2021-02-09 08:24:11.400:INFO:oejs.Server:main: jetty-9.4.36.v20210114; built: 2021-01-14T16:44:28.689Z; git: 238ec6997c7806b055319a6d11f8ae7564adc0de; jvm 11.0.10+9
2021-02-09 08:24:11.413:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/joakim/code/jetty/distros/bases/myappbase/webapps/] at interval 1
2021-02-09 08:24:11.436:INFO:oejs.AbstractConnector:main: Started ServerConnector@24688f3a{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
Server@53ce1329{STARTING}[9.4.36.v20210114] - STARTING
+= QueuedThreadPool[qtp817348612]@30b7c004{STARTED,10<=16<=200,i=0,r=20,q=0}[ReservedThreadExecutor@413d1baf{s=0/20,p=0}] - STARTED
...(snip)...
+= HandlerCollection@3590fc5b{STARTED} - STARTED
|  += ContextHandlerCollection@5f683daf{STARTED} - STARTED
|  |  += o.e.j.w.WebAppContext@5890e879{root,/,file:///home/joakim/code/jetty/distros/bases/myappbase/webapps/root/,AVAILABLE}{/home/joakim/code/jetty/distros/bases/myappbase/webapps/root} - STARTED
...(snip)...
|  |     +> Configurations /root/@71075444 size=8
|  |     |  +> org.eclipse.jetty.webapp.WebInfConfiguration@1458ed9c
|  |     |  +> org.eclipse.jetty.webapp.WebXmlConfiguration@10a9d961
|  |     |  +> org.eclipse.jetty.webapp.MetaInfConfiguration@130e116b
|  |     |  +> org.eclipse.jetty.webapp.FragmentConfiguration@e383572
|  |     |  +> org.eclipse.jetty.plus.webapp.EnvConfiguration@5ddf0d24
|  |     |  +> org.eclipse.jetty.plus.webapp.PlusConfiguration@6f7923a5
|  |     |  +> org.eclipse.jetty.annotations.AnnotationConfiguration@363a52f
|  |     |  +> org.eclipse.jetty.webapp.JettyWebXmlConfiguration@60856961
|  |     +> Handler attributes root@5890e879 size=3
...(snip)...
```

You can see from the above the following behavior ...

1. The `.../webapps/root/` exploded webapp is created as a `o.e.j.w.WebAppContext` (shortened form of `org.eclipse.jetty.webapp.WebAppContext`) on contextPath `/`
2. The Configurations are executed in order ...
  a. `org.eclipse.jetty.webapp.WebInfConfiguration` - this loads the `WEB-INF/` based information from the webapp
  b. `org.eclipse.jetty.webapp.WebXmlConfiguration` - this loads the `WEB-INF/web.xml` based information from the webapp
  c. `org.eclipse.jetty.webapp.MetaInfConfiguration` - this loads the various `META-INF` based stuff from the webapp (tls, resources, fragments, etc)
  d. `org.eclipse.jetty.webapp.FragmentConfiguration` - this load the web-fragment's found in the webapp
  e. `org.eclipse.jetty.plus.webapp.EnvConfiguration` - this loads the JNDI `java:comp/env` based webapp stuff from `WEB-INF/jetty-env.xml`
  f. `org.eclipse.jetty.plus.webapp.PlusConfiguration` - this loads the JNDI `java:comp` entries from the webapp
  g. `org.eclipse.jetty.annotations.AnnotationConfiguration` - this loads the servlet components defined by annotations (and also the `ServletContainerInitializer`)
  h. `org.eclipse.jetty.webapp.JettyWebXmlConfiguration` - this loads the `WEB-INF/jetty-web.xml`

What's happening is that the `WEB-INF/jetty-web.xml` is loaded far too late to have any impact on step 1 or step 2.g (the parts of the deployment you are attempting to impact).
Think of the `WEB-INF/jetty-web.xml` as a configure of things AFTER the servlet spec has had it's go.

What you want to do is improve deployment timing, by tweaking the bytecode scanning.

Before you dig into the options listed below, I encourage you to analyze your `WEB-INF/lib/*.jar` contents.
If you have jars with `META-INF/resources/` (as seen in many javascript libs) consider adjusting your build to overlay those into your webapp, and not put them as jars in the `WEB-INF/lib/`, this will improve things in regards to deployment time in a very noticeable way (and if your resources overlap, you eliminate the inherit classloader uncertainty that has caused so many problems with users of `META-INF/resources` in the past by designating at build time what the the order of unpacking should be for the truth in resources)

Ok, if you are here, you have two basic choices, both are configurations at step 1 in the above behavior list.

**Choice 1: use quickstart features.**

https://www.eclipse.org/jetty/documentation/jetty-9/index.html#quickstart-webapp

  - generate the `WEB-INF/quickstart-web.xml` at build time (IMPORTANT STEP!)
    See: https://www.eclipse.org/jetty/documentation/jetty-9/index.html#_pre_generating_the_quickstart_web_xml_file
  - configure your WebApp via the XML deployable to use the `org.eclipse.jetty.quickstart.QuickStartWebApp` feature
    - you can do this with `jetty-maven-plugin` and the `<jettyXml>` option.
    - you can do this with the standard `${jetty.home}` and `${jetty.base}` split with a file in `${jetty.base}/webapps/<name>.xml`

Example XML deployable for QuickStart
``` xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.quickstart.QuickStartWebApp">
  <Set name="contextPath">/app</Set>
  <Set name="war"><Property name="jetty.webapps" default="."/>/application.war</Set>
</Configure>
```

**Choice 2: tune jar scanning in webapp.**

This is the technique documented by the `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern`.  

https://www.eclipse.org/jetty/documentation/jetty-9/index.html#web-inf-include-jar-pattern

This is configured at the start of the deployment process.

Either as an XML deployable (maximally effective, and works across normal deployments, and `jetty-maven-plugin` deployments).

``` xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/app</Set>
  <Set name="war"><Property name="jetty.webapps" default="."/>/application.war</Set>
  <Call name="setAttribute">
    <Arg>org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern</Arg>
    <Arg>.*/spring-[^/]*\.jar$</Arg>
  </Call>
</Configure>
```

You can also configure this in the `jetty-maven-plugin` to only impact development time, but use this one with caution, because if you don't have the same pattern in production then you can easily have different behaviors where development time DOES NOT use an annotation or resource, but production does.

See https://www.eclipse.org/jetty/documentation/jetty-9/index.html#configuring-your-webapp 
Look at the the `<webInfIncludeJarPattern>` configuration option.

**Comment by janbartel** [comment]
@vitormcruz  take a look at the jetty-maven-plugin documentation here: https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-maven-plugin

We have the maven goal "effective-web-xml" ie mvn jetty:effective-web-xml  which will generate a complete web.xml that can be used with the quickstart feature. But, as the documentation says, the jetty-maven-plugin is not designed for use with the quickstart feature:   so you can use the effective-web-xml goal to generate a file that can be read by the quickstart feature enabled in the distribution (or embedded).

It is also very useful to set the https://www.eclipse.org/jetty/documentation/jetty-9/index.html#web-inf-include-jar-pattern to reduce the amount of jars that need to be scanned.

BTW I assume you actually do need to do the scanning, and that you can't put metadata-complete=true in your web.xml?

**Comment by vitormcruz** [comment]
> I took a look at that question, the problem they are having is that they attempted to use the property in the jetty-web.xml which is far too late in the configuration process for that attribute to take effect.

I have made that question :) I did all that was described there and read all the documentation on classpath inclusion and exclusion and about quick start.

> That property needs to exist in the XML deployable, at the beginning of the deployment process.

This is a little counterintuitive for me, being jetty-web.xml a configuration file I expected the latter applied configuration to overlap those first applied. Anyway, I did created a \<name\>.xml into webapp like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">

    <Set name="contextPath">/</Set>
	<Set name="war"><Property name="jetty.webapps" default="."/>/ROOT.war</Set>	

    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern</Arg>
        <Arg>.\A</Arg>
    </Call>

    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern</Arg>
        <Arg>.\A</Arg>
    </Call>
</Configure>
```
It should ignore all classpath scanning now that configuration is being applied in the beginning of the deployment process, but it happens just as related in the stackoverflow question: Classes from classes dir are still being scanned, only jars gets ignored, and even that happens only if I add the ContainerIncludeJarPattern config, which, by the docs, shouldn't be needed. I didn't understand why those classes are scanned, so I gave a look in the code, and it seems that this specific scanning is set no matter what is configured in those attributes:

AnnotationConfiguration(345)
```
if (!_discoverableAnnotationHandlers.isEmpty() || 
    _classInheritanceHandler != null || !_containerInitializerAnnotationHandlers.isEmpty())
            scanForAnnotations(context);
```

If that works, I shouldn't need to use quick start. Nevertheless I am still giving a look into QuickStart, I will report back if it works.

**Comment by janbartel** [comment]
@vitormcruz  scanning takes place if web.xml is not metadatacomplete, OR if there is a ServletContainerInitializer on the classpath that has a non-empty `@HandlesTypes` annotation OR if you are using the jetty specific mechanism to force discovery.

If scanning is to take place, the following files are scanned:

* everything in `WEB-INF/classes`
* only those jars from the server's classpath that match `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` or none if that pattern is not specified
* all the jars from WEB-INF/lib, or those that match `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern` if specified

If you turn on DEBUG logging for org.eclipse.jetty.annotations you will see exactly which jars have been selected for scanning.

**Comment by vitormcruz** [comment]
> If you turn on DEBUG logging for org.eclipse.jetty.annotations you will see exactly which jars have been selected for scanning.

That is what I have made, and AnnotationParser still reports scanning. When I use both:
```

    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern</Arg>
        <Arg>.\A</Arg>
    </Call>

    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern</Arg>
        <Arg>.\A</Arg>
    </Call>
```

Then jar scanning is ceased, but `WEB-INF/classes` still happens.

> only those jars from the server's classpath that match org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern or none if that pattern is not specified

I am doing something wrong, or this isn't holding true.

**Comment by joakime** [comment]
To state what @janbartel said, but in a different way, there are 3 categories being searched...

1. Container - controlled by `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern`
2. WebApp's `WEB-INF/classes` - controlled by metadata complete, OR if there is a ServletContainerIntiailizer on the classpath that has a non-empty @HandlesType, OR if you are using jetty specific mechanism to force discovery.
3. WebApp's `WEB-INF/lib/*.jar` - controlled by `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern`

Looks like you have 1 (the Container) and 3 (the WebInf Include) done correctly.  What have you done for 2 (WebInf Classes)?

**Comment by joakime** [comment]
Out of curiosity, your requirements for not scanning is counter to the philosophy behind a WebApp deployable, which focuses on discovery.

Have you considered not using a formal Servlet WebApp deployment? (or is this a requirement outside of what's happened in this discussion so far?)
Perhaps going with a statically defined ServletContextHandler within an Embedded Jetty?  (you have 100% control over the resulting context this way, without sacrificing the use of the Servlet API and associated libraries.  you still have servlets, filters, a ServletContext, etc.  But you don't have an isolated classloader, no annotation scanning, no war file, etc).

**Comment by vitormcruz** [comment]
> Looks like you have 1 (the Container) and 3 (the WebInf Include) done correctly. What have you done for 2 (WebInf Classes)?

Yes, I forgot to put here my web.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1"
         metadata-complete="true">

<absolute-ordering/>

</web-app>
```

> WebApp's WEB-INF/classes - controlled by metadata complete, OR if there is a ServletContainerIntiailizer on the classpath that has a non-empty @HandlesType, OR if you are using jetty specific mechanism to force discovery.

`metada-complete` is true, `absolute-ordering` is empty. There is a ServletContainerInitializer with a non empty @HandleTypes from a 3rd part framework on my classpath, how does Jetty finds that out before doing the actual scanning? Don't it need scanning to look for such Servlet?

**Comment by janbartel** [comment]
@vitormcruz ServletContainerInitializers are loaded via the ServiceLoader mechanism, not scanning.  All SCIs on the classpath will be found. This page describes how you can select which to use and how to order them: 
  https://www.eclipse.org/jetty/documentation/jetty-9/index.html#using-annotations.

**Comment by vitormcruz** [comment]
> Out of curiosity, your requirements for not scanning is counter to the philosophy behind a WebApp deployable, which focuses on discovery.

More or less. I dislike the discovery philosophy a little bit, but the actual problem is control. For example, I prefer to declare my spring beans programmatically, but it is fine to use annotations if I can define at least which packages should be scanned. Some big applications using Spring and servlet annotations features can be severely impacted by the scanning mechanism. Last year I helped improve the performance of such an application that had this problem with Spring scanning — it's WEB-INF/classes size was solely responsible by the decrease of performance. Since then I had looking for ways to limit scanning in servlet servers, it is surprisingly harder than I first thought.... 

> Have you considered not using a formal Servlet WebApp deployment? (or is this a requirement outside of what's happened in this discussion so far?)

Yes, but some frameworks are already providing only servlet discovery as option of use, so it would be nice to know how to selectively tell the server wich jars or dirs it should scanning, that way I can have the discoverability but greatly mitigate performance problems.

> Perhaps going with a statically defined ServletContextHandler within an Embedded Jetty? (you have 100% control over the resulting context this way, without sacrificing the use of the Servlet API and associated libraries. you still have servlets, filters, a ServletContext, etc. But you don't have an isolated classloader, no annotation scanning, no war file, etc).
 
I have tried.... but I was not very successful. I had problems instantiating 3rd part Servlets using `ServletContextHandler`, session problems, classload nullpointer... I figured `ServletContextHandler` is `WebAppContext` minus minus, and that I should add stuff to it, but it started to become complicated, there was less information about this and so I gave up :(

**Comment by joakime** [comment]
> > Out of curiosity, your requirements for not scanning is counter to the philosophy behind a WebApp deployable, which focuses on discovery.
> 
> More or less. I dislike the discovery philosophy a little bit, but the actual problem is control. For example, I prefer to declare my spring beans programmatically, but it is fine to use annotations if I can define at least which packages should be scanned. Some big applications using Spring and servlet annotations features can be severely impacted by the scanning mechanism. Last year I helped improve the performance of such an application that had this problem with Spring scanning — it's WEB-INF/classes size was solely responsible by the decrease of performance. Since then I had looking for ways to limit scanning in servlet servers, it is surprisingly harder than I first thought....

I'm still curious what kind of webapp you have that it takes minutes to deploy?

I test with a stupid large war (war is 909MB, with 518 jars in WEB-INF/lib, totaling 926,685 entries across the jar files) a few times a year to verify scanning behavior.
A full deploy of that war takes about 3 seconds for me.

**Comment by vitormcruz** [comment]
@janbartel 

> @vitormcruz ServletContainerInitializers are loaded via the ServiceLoader mechanism, not scanning. All SCIs on the classpath will be found. This page describes how you can select which to use and how to order them:
> https://www.eclipse.org/jetty/documentation/jetty-9/index.html#using-annotations.

It is odd that containers jars are scanned and I can only prevent it by defining the `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern`, which by the documentation shouldn't be needed as no scans of the containers should be made.

This loading scheme is from servlet specification, yes? It is very confusing and I have seen something similar on Tomcat.

**Comment by vitormcruz** [comment]
@janbartel Oh!!! `org.eclipse.jetty.containerInitializerExclusionPattern`did the trick for ServiceLoader mechanism!!! Thanks!

**Comment by vitormcruz** [comment]
> 
> 
> > > Out of curiosity, your requirements for not scanning is counter to the philosophy behind a WebApp deployable, which focuses on discovery.
> > 
> > 
> > More or less. I dislike the discovery philosophy a little bit, but the actual problem is control. For example, I prefer to declare my spring beans programmatically, but it is fine to use annotations if I can define at least which packages should be scanned. Some big applications using Spring and servlet annotations features can be severely impacted by the scanning mechanism. Last year I helped improve the performance of such an application that had this problem with Spring scanning — it's WEB-INF/classes size was solely responsible by the decrease of performance. Since then I had looking for ways to limit scanning in servlet servers, it is surprisingly harder than I first thought....
> 
> I'm still curious what kind of webapp you have that it takes minutes to deploy?
> 
> I test with a stupid large war (war is 909MB, with 518 jars in WEB-INF/lib, totaling 926,685 entries across the jar files) a few times a year to verify scanning behavior.
> A full deploy of that war takes about 3 seconds for me.

Don't get near this actually, the webapp I was talking about had about 200 Mb and about 10k files (WEB-INF/classes). In that case spring scanning was taking minutes to execute, and that would vary wildly across developer machines (some had better machines, whiles others not). Many things added to the final loading time: scanning, loading stuf, queries etc.

**Comment by vitormcruz** [comment]
Quickstart worked using webapp/<name>.xml, so if quickstart is not expected to work on jetty-web.xml then this bug can be closed.

Disabling classpath scan worked with the following xml both on jetty-web.xml or webapp/<name>.xml (in this case, setting the war file is necessary).

```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">

    <Set name="contextPath">/</Set>

    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern</Arg>
        <Arg>.\A</Arg>
    </Call>

    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern</Arg>
        <Arg>.\A</Arg>
    </Call>

	<Call name="setAttribute">
        <Arg>org.eclipse.jetty.containerInitializerExclusionPattern</Arg>
        <Arg>.*</Arg>
    </Call>
</Configure>
```

I was able to turn off/on scanning completely. Selective scanning, on the other hand, is harder to make correctly, and since metadata-complete must be false, at least META-INF/classes will be scanned. 

I believe it is easier to use scanning on and, if neded, use quickstart. Thankyou very much @joakime  and @janbartel!

**Comment by joakime** [comment]
Glad you reach the goal you were looking for.
Feel free to close the issue.
