### ISSUE TITLE
Don't send Content-Length on HEAD requests for chunked responses

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#596]
If a request is made to a resource that would result in a chunked transfer encoding, there is no `Content-Length` header in the response.   This lack of `Content-Length` header should also be missing from a `HEAD` request to the same resource.

Current implementation adds a `Content-Length: 0` in this situation erroneously.

https://tools.ietf.org/html/rfc7231#section-4.3.2

```
   The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response (i.e., the response terminates at
   the end of the header section).  The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted.  This method can be used for obtaining
   metadata about the selected representation without transferring the
   representation data and is often used for testing hypertext links for
   validity, accessibility, and recent modification.
```

**Comment by joakime** [comment]
This was reported on stackoverflow by user [mntgoat](http://stackoverflow.com/users/704836/mntgoat)

http://stackoverflow.com/questions/37419015/is-there-a-way-to-prevent-jetty-from-sending-a-content-length-header-on-head-req

**Comment by gregw** [comment]
Added a test harness that demonstrates correct behaviour.  Closing for now, please reopen if you have more info about this.
