### ISSUE TITLE
Include EFTL License for TCK

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#5968]
**Jetty version**
11.0.X

For TCK certification we must produce final binaries with the EFTL license according to [guidelines here](https://jakarta.ee/committees/specification/tckprocess/).

`Projects MUST produce a final candidate binary that includes the EFTL license. The Jakarta EE Specification Committee will sign and promote project TCK binary for distribution via Eclipse infrastructure on final approval.`

The text of the license can be [found here.](https://www.eclipse.org/legal/tck.php)

@joakime As license czar is this something you can help with?

**Comment by joakime** [comment]
IIRC the EFTL license is for those projects that implement the TCK, such as ...

* https://github.com/eclipse-ee4j/servlet-api
* https://github.com/eclipse-ee4j/websocket-api

**Comment by joakime** [comment]
I think we need to file something more along the lines of what the Tyrus project filed against the websocket spec.

Example: https://github.com/eclipse-ee4j/websocket-api/issues/361

**Comment by jmcc0nn3ll** [comment]
Agreed, the guidelines linked indicate we have to we have to make a statement accepting the terms of the EFTL in the certification request but I think you are right that the EFTL requirement is in a different part of the guidelines related to the TCK themselves.

**Comment by WalkerWatch** [comment]
Sounds good to me, perhaps I just misread.
