### ISSUE TITLE
Can multiple context paths behave the same as a single context path?

### ISSUE THREAD

**Issue by mattnelson** [eclipse/jetty.project#5984]
**Jetty version**
9.4.36.v20210114 via dropwizard-1.3.29

**Java version**
8/11

**Question**

I have a scenario where I want to have a resource available on multiple context paths as well the root.
For example, I want `/alias1/link`, `/alias2/link`, and `/link` to all be served by the same jaxrs resource. I've tried a few different approaches from the below examples, but I haven't quite been able to get it working across filters and with `@Context UriInfo` containing the full UriInfo in the same way it does with a traditional context path.
https://github.com/eclipse/jetty.project/blob/jetty-9.4.36.v20210114/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyContexts.java
https://github.com/eclipse/jetty.project/blob/jetty-9.4.36.v20210114/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyHandlers.java
https://github.com/eclipse/jetty.project/blob/jetty-9.4.36.v20210114/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyServletContexts.java

Tried using a filter to dispatch a forward on the root `/link`, the filters execute, but the UriInfo no longer contains the context path of the original request.

Tried adding extra `ServletMapping`s which restores the full path in the UriInfo, but now the filters no longer execute. I can get the filters to execute by adding additional filter mappings for each of the aliases. This is the best option I've discovered thus far, but am hoping that there is a simpler option I haven't found yet.

Tried a few other approaches with `HandlerWrapper` and `ContextHandler`, but ran into a handler loop exception and what I think may be a lifecycle ordering issue with dropwizard trying to setHandler before the server has been constructed/started.

Looking for guidance if what I want is possible and/or some other ideas to explore.

Created a minimal sandbox project where I've been testing out the ideas.
https://github.com/mattnelson/dropwizard-sandbox

**Comment by sbordet** [comment]
@mattnelson have you tried using the `RewriteHandler` to rewrite `/aliasN/link` to just `/link`?

**Comment by mattnelson** [comment]
> Tried adding extra `ServletMapping`s which restores the full path in the UriInfo, but now the filters no longer execute. I can get the filters to execute by adding additional filter mappings for each of the aliases. This is the best option I've discovered thus far, but am hoping that there is a simpler option I haven't found yet.

After quite a bit more trial and error this seemed to be the only solution I could get working in time I had available.
