### ISSUE TITLE
A new method to optimize finding bytes performance

### ISSUE THREAD

**Issue by leonchen83** [eclipse/jetty.project#5985]
**Jetty version**
9.x, 10.x
**Java version**
jdk 11
**Question**

[https://richardstartin.github.io/posts/finding-bytes](https://richardstartin.github.io/posts/finding-bytes)
could jetty use above method to optimize header paser?

**Comment by gregw** [comment]
The article is interesting, but I don't think we can apply it.   We very rarely scan ahead looking for a specific byte without also doing other work along the way... even if that is converting bytes to characters.   Finding a CRLF in a buffer only gives us a span of bytes and something still needs to iterate over those bytes, either matching them in a Trie or converting them into characters.   So our current approach of matching/converting as we go is probably OK.   Of course if we can do a long lookup and go directly to the result without further iteration, then that is a big win.  We are doing that on the request/response line.
