### ISSUE TITLE
Diagnose Linux oom killer with 30K websocket sessions

### ISSUE THREAD

**Issue by qtxo** [eclipse/jetty.project#5997]
Linux oom killer with 30K websocket sessions

**Jetty version**
9.4.34.v20201102

**Java version**
11.0.7+10

**Question**

CentOS 7 with 7.5GB of RAM running app in JVM started with -Xmx3g sometimes is killed by oom killer when a high number of WS sessions are connected, no other HTTP requests are handled and there are no other significant processes running.

The WS app code uses Jsr annotations and receives mostly small JSON data (90% of data flows client to server)
 
I would like to know if Jetty is using or depending on some sort of native memory buffers that can lead to memory exhaustion. For example, if all the Jetty threads are reading data in all connections using Java objects, we could observe OOME instead.

What can I do to diagnose where all the native memory is being held?
 
Thanks

**Comment by sbordet** [comment]
The Jetty WebSocket implementation does use direct buffers to read/write from the network; however, it is configurable whether to use direct or heap buffers.

I did a simple test and measured that 30k WebSocket connections occupy around 400 MiB.
Jetty uses a `ByteBufferPool` which should constrain the memory used for buffers -- my simple test shows that only few KiB are retained by the `ByteBufferPool`.

You may be running into gzip issues (takes a while for gzip native handles to be GCed) if the WebSocket connections negotiate the "per-message deflate" extension.
You may try to disable it and see if there are changes.

Enable JMX and verify that Jetty's `ByteBufferPool` is not retaining too much memory.

See also Native Memory Tracking:
https://docs.oracle.com/javase/8/docs/technotes/guides/vm/nmt-8.html

Please report back your findings. Thanks!

**Comment by stolsvik** [comment]
@sbordet Just stumbled across this issue, and read the comment _"You may be running into gzip issues (takes a while for gzip native handles to be GCed) if the WebSocket connections negotiate the "per-message deflate" extension."_, and thought I could mention that I have been pondering the same issue for my own library, and have recently implemented a "hack" that I .. well .. _hope_ gives some effect here:

https://github.com/stolsvik/mats/blob/02c11bcb18e2db946a5f361c021fdd9d02d8c508/mats-serial-json/src/main/java/com/stolsvik/mats/serial/json/MatsSerializerJson.java#L404-L543

Notice two things: Both the `Inflater/Deflater.end()` methods, which evidently release off-heap resources. But the idea that `Inflators` and `Deflators` employs `finalize()` to handle off-heap GC always bothered me (implementing `finalize()` _ensures_ that the GC must do two passes over an object to release it), so I have been thinking for years to implement a lock-free stack of these objects, arguing in my head that the number of such instances will at any rate be limited by the number of Servlet container threads in use - and probably in reality be using way fewer. And I just implemented it, but not really sure if it is for measurable gain..!

**Comment by lachlan-roberts** [comment]
@stolsvik we have also run into this issue previously and have since implemented pooling for Inflaters and Deflaters in Jetty 9.4 and 10  (see issue https://github.com/eclipse/jetty.project/issues/300).
