### ISSUE TITLE
mvn test failed - XmlParserTest.testXmlParser - Connect Connection timed out

### ISSUE THREAD

**Issue by simon28li** [eclipse/jetty.project#6004]
**Jetty version**
9.4.31.v20200723
**Java version**
1.8.0_191-b12
**OS type/version**
centos 8.0
**Description**
The error of executing mvn test after compilation is as follows：
> >>
```
[INFO] Running org.eclipse.jetty.xml.XmlAppendableTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.eclipse.jetty.xml.XmlAppendableTest
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /tmp/root/spack-stage/spack-stage-jetty-project-9.4.31.v20200723-7n6dmzqth4zyevt7ri74lgakat2xxdbe/spack-src/jetty-xml/target/surefire-reports/2021-02-24T16-47-18_345-jvmRun1.dumpstream
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   XmlParserTest.testXmlParser:40 » Connect Connection timed out (Connection time...
[INFO]
[ERROR] Tests run: 95, Failures: 0, Errors: 1, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jetty :: Project 9.4.31.v20200723:
[INFO]
[INFO] Jetty :: Build Resources ........................... SUCCESS [  0.488 s]
[INFO] Jetty :: Project ................................... SUCCESS [  3.048 s]
[INFO] Jetty :: Utilities ................................. SUCCESS [02:23 min]
[INFO] Jetty :: IO Utility ................................ SUCCESS [01:06 min]
[INFO] Jetty :: Http Utility .............................. SUCCESS [02:27 min]
[INFO] Jetty :: XML utilities ............................. FAILURE [02:18 min]
[INFO] Jetty :: JMX Management ............................ SKIPPED
[INFO] Jetty :: Utilities :: Ajax(JSON) ................... SKIPPED
```
Can you give me some help?

**Comment by janbartel** [comment]
Try running the build with debug enabled for org.eclipse.jetty.xml (you might need to edit the $MVN_HOME/conf/logging/simplelogger.properties to enable logging for that package).

Also, just to point out that jetty is now at 9.4.37 so you might want to upgrade.

**Comment by joakime** [comment]
> XmlParserTest.testXmlParser:40 » Connect Connection timed out (Connection time...

Connection timeout?
There shouldn't be any attempt to connect to a remote server from the XmlParser (unless you are running on a JVM that doesn't have it's Xml catalog set properly)

**Comment by simon28li** [comment]
> > XmlParserTest.testXmlParser:40 » Connect Connection timed out (Connection time...
> 
> Connection timeout?
> There shouldn't be any attempt to connect to a remote server from the XmlParser (unless you are running on a JVM that doesn't have it's Xml catalog set properly)

@joakime 
yes，I execute it on the JVM. How do I set up the XML catalog

**Comment by simon28li** [comment]
> 9.4.37



> Try running the build with debug enabled for org.eclipse.jetty.xml (you might need to edit the $MVN_HOME/conf/logging/simplelogger.properties to enable logging for that package).
> 
> Also, just to point out that jetty is now at 9.4.37 so you might want to upgrade.

@janbartel 

> Try running the build with debug enabled for org.eclipse.jetty.xml (you might need to edit the $MVN_HOME/conf/logging/simplelogger.properties to enable logging for that package).
> 
> Also, just to point out that jetty is now at 9.4.37 so you might want to upgrade.

@janbartel 
Unfortunately, I tried to upgrade to 9.4.37.v20210219, but the problem still recurred.

**Comment by janbartel** [comment]
@simon28li I think I see the problem:  we aren't aliasing the config_9_3.dtd for the parser so it's trying to get it from the network. To test out my theory, try applying the trivially simple patch (generated with diff, but with a .txt suffix to keep github happy) I'm attaching and rerun the test.
[fix.txt](https://github.com/eclipse/jetty.project/files/6042438/fix.txt)

**Comment by janbartel** [comment]
@simon28li  I'm pretty sure the issue was the redirect for the configure_9_3.dtd, so I'm closing this issue after the commit of pr #6015. If there is still a problem, please reopen and provide more detailed information.
