### ISSUE TITLE
How to set mutiple TLS Protocol version for jetty http server in version 9.4.26

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#6013]
**9.4.26**

**Java version - JDK 8 SR6 FP 20**

**I am struggling to find doc, for setting different TLS protocol versions using SslContextFactory.setProtocol**

I see it doenst take arraylist, then how do we set range say, tls1.1-tls1.2?

**Comment by 4devwithgit** [comment]
This is in java

**Comment by joakime** [comment]
> JDK 8 SR6 FP 20

What JVM is that? I don't recognize it.

As for the TLS protocols, those are managed by the SslContextFactory IncludeProtocols and ExcludeProtocols.

Tip: exclude wins over include, always, so be mindful.

The techniques described in https://www.eclipse.org/jetty/documentation/jetty-9/index.php#configuring-sslcontextfactory-cipherSuites are what you are looking for.

You'll still use the `tweak-ssl.xml` concept, but instead of focusing on Cipher Suites, you'll focus on Protocols (the IncludeProtocols and ExcludeProtocols).
Don't forget to use the state dump features to troubleshoot your configuration.

**Comment by joakime** [comment]
> 9.4.26

9.4.26 is subject to several [security advisories](https://www.eclipse.org/jetty/security_reports.php), you should consider upgrading.

**Comment by 4devwithgit** [comment]
Java details

jdk/bin/java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3-20160428_01(SR3))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20160427_301573 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160427_1620_B301573
JIT  - tr.r14.java.green_20160329_114288
GC   - R28_Java8_SR3_20160427_1620_B301573_CMPRSS
J9CL - 20160427_301573)
JCL - 20160421_01 based on Oracle jdk8u91-b14

**Comment by joakime** [comment]
Ah IBM JVM.

You have a lot more work ahead of you than any other non-IBM JVM user.

Why?

IBM has made a decision (that we do not agree with) to not use industry standard naming for their TLS internal names (for extensions and values within various extensions), TLS Protocols (high level support), and TLS Cipher Suites.
They have their own naming for each of them, not using the RFC and [IANA specific names](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml).

Note that the OpenJDK pretty much mandates that all JVMs use the IETF/RFC and IANA registered name and values. (IBM chose not to)

You'll need to investigate the documentation of your specific JVM to learn what their names are.
Then you'll need to clear out all of the default exclusions in SslContextFactory (both protocols and cipher suites)
Next, you'll need to define the specific list of protocols in the IncludeProtocols using the IBM specific names.
Next, you'll need to define the specific list of cipher suites in the IncludeCipherSuites using the IBM specific names.

And this configuration is not durable, and will need to be update every time your update your JVM.

**Comment by joakime** [comment]
Oh, since you are doing SSL/TLS, make sure you honor the JVM version specific expiration dates, as the various SSL/TLS databases (for jvm keystores/truststores, it's CAs, rejected certificates, jvm level CRL/DP database, jvm level OSCP database. etc) are updated frequently and have the ability to impact your client's experience with SSL/TLS negatively if you don't keep up to date.

**Comment by 4devwithgit** [comment]
Thanks for the details.

**Comment by 4devwithgit** [comment]
I need one clairifcation,

The code is using just SSLContextFactory for setting up all the SSL and keystore parameters, and I dont see SSLEngine in use,

For example, its like this,
---------------------------------------------------------------------------------------------------------------------
		SslContextFactory factory = new SCISslContextFactory(certMap,cipherStrength,sysCertName);
		String alias =	com.sterlingcommerce.security.util.SecurityUtil.makeXMLSafeGUID(pki.getObjectID());
		factory.setCertAlias(sysCertName);
		factory.setEndpointIdentificationAlgorithm(null);
		factory.setExcludeCipherSuites("");

		factory.setKeyStoreProvider(pki.getKeyStoreProvider());
		factory.setKeyStoreType(pki.getKeyStoreType());
		if (certMap != null && !certMap.isEmpty()) {
			//factory.caCertNames = new StringTokenizer(certNames, ",");
			factory.setWantClientAuth(true);
			factory.setNeedClientAuth(true);

		} else {
			factory.setWantClientAuth(false);
			factory.setNeedClientAuth(false);
		}
---------------------------------------------------------------------------------------------------------------------
So, I believe we need to introduce SSLEngine here? How to do that? My understanding is that, we need to define it with setEnabledProtocols with SSLEngine,

    setIncludeProtocols
    public void setIncludeProtocols​(java.lang.String... protocols)
    You can either use the exact Protocol name or a a regular expression.
    Parameters:
        protocols - The array of protocol name patterns to include in **SSLEngine.setEnabledProtocols(String[])**



Thanks

**Comment by 4devwithgit** [comment]
Can you please help me with above query?

Thanks

**Comment by sbordet** [comment]
> The code is using just SSLContextFactory for setting up all the SSL and keystore parameters, and I dont see SSLEngine in use,

That is exactly what the factory is meant to do. Once an `SSLEngine` is requested to the `SslContextFactory` it will be configured appropriately from the factory configuration.

**Comment by 4devwithgit** [comment]
I am looking for some code samples to create SSLEngine from SslContextFactory, because I am getting NPE, for below code during https connection.

SSLContext sslContext = factory.getSslContext();
SSLEngine sslEngine = sslContext.createSSLEngine("X.x.x.x", 11111);

String[] tlsVersions = {"TLSv1.1", "TLSv1.2"};
sslEngine.setEnabledProtocols(tlsVersions);

**Comment by sbordet** [comment]
Stack trace? Did you remember to `start()` the `SslContextFactory`?
Why do you need to create `SSLEngine` instances yourself?

**Comment by 4devwithgit** [comment]
without having SSLEngine , how do we set the tls protocols? Or how do we specify the tls protocol range with SslContextFactory directly without creating SSLEngine?

**Comment by sbordet** [comment]
```java
SslContextFactory.Server ssl = new SslContextFactory.Server();
ssl.setIncludeProtocols("TLSv1.2", "TLSv1.3");
```

**Comment by 4devwithgit** [comment]
thanks @sbordet will try it.

**Comment by joakime** [comment]
The IncludeProtocols configuration was pointed out in comment https://github.com/eclipse/jetty.project/issues/6013#issuecomment-785926775
