### ISSUE TITLE
Websocket permessage-deflate compression level should be configurable

### ISSUE THREAD

**Issue by JonathanLennox** [eclipse/jetty.project#6016]
**Jetty version**
9.4.35

**Java version**
1.8

**OS type/version**
Linux/x86_64

**Description**
When Jetty negotiates the permessage-deflate extension for websockets, the compressionLevel used is hard-coded to be `Deflater.DEFAULT_COMPRESSION`.

There should be an API that lets a user of Jetty Websockets can configure this, so they can make the CPU vs. Bandwidth trade-off appropriate for their application.

**Comment by joakime** [comment]
This is possible on Jetty 10+

The `ServletContext` Attribute `jetty.websocket.deflater` can be pre-populated with any `org.eclipse.jetty.util.compression.DeflaterPool` configuration you want to use.

**Comment by lachlan-roberts** [comment]
Closing as this is implemented for Jetty 10+.

A custom `DeflaterPool` can be set as a `ServletContext` attribute at `jetty.websocket.deflater`, or one can be set as a bean on the `Server` and all contexts will use it if there is none on the `ServletContext` attribute.
