### ISSUE TITLE
Jetty 11 returns "/" as context path when deployed in ROOT context. It should return an empty string.

### ISSUE THREAD

**Issue by tarator** [eclipse/jetty.project#6028]
**Jetty version**: 11.0.1

**Java version**: OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)

**OS type/version**: Ubuntu Budgie 20.04.1

**Description**
When a WAR-File is deployed in ROOT Context Path of Jetty 11 the method `getContextPath()` returns the String `/` (slash).
It should return an empty String since context path's shouldn't end with a `/`

Jetty Versions <10 return an empty string as expected.

It seems this has also been a problem in Jetty 9, but has been fixed there: see #5057

**Comment by tarator** [comment]
Duplicate of #5057

**Comment by joakime** [comment]
Seems that we have test cases for the `.getContextPath()` during `DispatcherType.INCLUDE` (which was added by issue #5057), but not normal REQUEST dispatch.

**Comment by joakime** [comment]
PR #6030 opened with testcase for Jetty 10 (it works there, but the OP says so anyway)

**Comment by joakime** [comment]
Opened PR #6032 for Jetty 11 with testcase.  
This works as expected.

**Comment by janbartel** [comment]
I can't replicate this with jetty-11.

Are you sure the request is not being wrapped?

**Comment by gregw** [comment]
I think there might be a difference `ContextHandler.getContextPath()` and `ContextHandler.getServletContext().getContextPath()`
I think the former will return what the context is configured as (eg "/" or "/foo"), but the later returns what the servlet spec wants (ie "" for root).

**Comment by joakime** [comment]
You can test this with the `Dump` servlet in the `demo-jetty.war` as well.

Setup ...

```
$ mkdir demo-base
$ cd demo-base
$ java -jar /opt/jetty-home-11.0.1/start.jar --add-module=http,deploy,demo-jetty
$ cd webapps
$ rm -rf demo-jetty.d demo-jetty.xml
$ mv demo-jetty.war ROOT.war
$ cd ..
$ java -jar /opt/jetty-home-11.0.1/start.jar
```

Then open `http://localhost:8080/dump/info` in your browser.
The `getContextPath()` returns an empty string.
