### ISSUE TITLE
Need EJB example

### ISSUE THREAD

**Issue by khajavi** [eclipse/jetty.project#603]
Any one could write simple jett ejb example, and add it to project?

**Comment by joakime** [comment]
Jetty has no EJB Support, sorry.

**Comment by joakime** [comment]
If you want EJB support, you will have to use a 3rd party library that adds the support for your specific webapp.

**Comment by khajavi** [comment]
Can I use OpenEJB with Jetty?

On Tue, May 31, 2016 at 2:05 AM, Joakim Erdfelt <notifications@github.com>
wrote:

> If you want EJB support, you will have to use a 3rd party library that
> adds the support for your specific webapp.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipse/jetty.project/issues/603#issuecomment-222557135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAOZxmpVvnAxtsXxg7gndL8ID-eRoFwBks5qG1gEgaJpZM4IqBbc>
> .
>



-- 
﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.

**Comment by jmcc0nn3ll** [comment]
You can give this integration a whirl if you like.

https://github.com/jetty-project/jetty-ejb
