### ISSUE TITLE
How to save a received HTTP Post in the server

### ISSUE THREAD

**Issue by Silhim** [eclipse/jetty.project#6039]
**Jetty version**
11.0.0 via Maven

**Java version: **
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

**Question**
Hello, I'm very new to Jetty and I'm trying to develop an embedded Jetty Server with a REST API.
I need to receive HTTP Posts to my server and save the posts in the server (in our context the HTTP Posts will contain JSONs and Strings).  The Strings will be IP addresses and for every received IP address I need to create a new context, like this: mainsite/gateway/newIP1, if newIP1 just came in. If newIP2 comes in, I need to create mainsite/gateway/newIP2.
Right now I'm just using handlers in a HandlerCollection, but I don't know how the server can receive the HTTP Posts that the handler receives. Is there a way to do this?

Best regards,
Jonas

**Comment by sbordet** [comment]
Seems overcomplicated to me.

Why can't you just use a single handler with a map lookup for the IP address?
