### ISSUE TITLE
ServletContainerInitializer's HandlesTypes might do too shallow analysis of interface implementation?

### ISSUE THREAD

**Issue by stolsvik** [eclipse/jetty.project#6040]
**Jetty version**
9.4.38.v20210224

**Java version**
jdk-11.0.9+11

**OS type/version**
Ubuntu 20.04.2 LTS

**Description**
(Got a very weird situation here. I've found a workaround, but if this is reproducible and possibly bites other people, it might be worth looking into.)

I am programmatically creating the Jetty Server, creation method at end.

Trying to employ the Spring `AbstractAnnotationConfigDispatcherServletInitializer`, which is a WebApplicationInitializer (layered a bit through `extends AbstractDispatcherServletInitializer`, which `extends AbstractContextLoaderInitializer`, which `implements WebApplicationInitializer`).

So, I create a class `TestInitializer`, extending that class (I am now 4 levels "above" the WebApplicationInitializer).

The idea of Spring is that `SpringServletContainerInitializer` implements the Servlet SPI `ServletContainerInitializer`. This class is annotated with `@HandlesTypes(WebApplicationInitializer.class)` and effectively just "forwards" the `onStartup(...)` invocation to any `WebApplicationInitializers` that Jetty feeds it based on the HandlesType. The point is that the Servlet spec is an SPI solution, requiring the class to be specified in META-INF, while the Spring variant just gets any instances residing on the classpath that implements the WebApplicationInitalizer interface, supplied by the Servlet Container - and forwards the container initialization. Very nice, albeit a bit scary.

However, from the logs, I get this:
`DEBUG org.eclipse.jetty.annotations.ServletContainerInitializersStarter - Calling ServletContainerInitializer org.springframework.web.SpringServletContainerInitializer`
`INFO org.eclipse.jetty.server.handler.ContextHandler.ROOT - No Spring WebApplicationInitializer types detected on classpath`

(The reason for that coming on a logger of Eclipse is that it employs the `servletContext.log(..)`..)

After quite a long time of pondering, I created my own direct-implementation of `WebApplicationInitializer`. And lo and behold, _that_ class is found and invoked by the `SpringServletContainerInitializer`.

Thus, on a whim, I changed my class as such:
`public class TestInitializer extends AbstractAnnotationConfigDispatcherServletInitializer implements WebApplicationInitializer`
.. do note the **absurdly redundant** `implements WebApplicationInitializer`.

.. and yes, now it loads!! That is literally the only change between not being picked up, and being picked up.

_Might the Jetty classpath scanning not go deep enough wrt. subtyping?_

PS: Method that creates the Jetty Server:
```
    public static Server createServer(int port) {
        WebAppContext webAppContext = new WebAppContext();
        webAppContext.setContextPath("/");
        webAppContext.setBaseResource(Resource.newClassPathResource("webapp"));
        // If any problems starting context, then let exception through so that we can exit.
        webAppContext.setThrowUnavailableOnStartupException(true);
        // Store the port number this server shall run under in the ServletContext.
        webAppContext.getServletContext().setAttribute(CONTEXT_ATTRIBUTE_PORTNUMBER, port);

        // Override the default configurations, stripping down and adding AnnotationConfiguration.
        // https://www.eclipse.org/jetty/documentation/9.4.x/configuring-webapps.html
        // Note: The default resides in WebAppContext.DEFAULT_CONFIGURATION_CLASSES
        webAppContext.setConfigurations(new Configuration[]{
                // new WebInfConfiguration(),
                new WebXmlConfiguration(), // Evidently adds the DefaultServlet, as otherwise no read of "/webapp/"
                // new MetaInfConfiguration(),
                // new FragmentConfiguration(),
                new AnnotationConfiguration() // Adds Servlet annotation processing.
        });

        // :: Get Jetty to Scan project classes too: https://stackoverflow.com/a/26220672/39334
        // Find location for current classes
        URL classesLocation = ServerX.class.getProtectionDomain().getCodeSource().getLocation();
        // Set this location to be scanned.
        webAppContext.getMetaData().setWebInfClassesDirs(Collections.singletonList(Resource.newResource(
                classesLocation)));

        // Create the actual Jetty Server
        Server server = new Server(port);

        // Add StatisticsHandler (to enable graceful shutdown), put in the WebApp Context
        StatisticsHandler stats = new StatisticsHandler();
        stats.setHandler(webAppContext);
        server.setHandler(stats);

        // Add a Jetty Lifecycle Listener to cleanly shut down the MatsSocketServer.
        server.addLifeCycleListener(new AbstractLifeCycleListener() {
            @Override
            public void lifeCycleStopping(LifeCycle event) {
                log.info("===== STOP! ===========================================");
            }
        });

        // :: Graceful shutdown
        server.setStopTimeout(1000);
        server.setStopAtShutdown(true);
        return server;
    }
```

PPS: It hit me that it could maybe be because I am using Groovy joint compilation, and the class files was maybe a bit off, but I changed over to use pure javac, and it still behaves like this.

**Comment by janbartel** [comment]
The class inheritance scanning is tested and certainly scans all the way back to (but not including) java.lang.Object, and correctly establishes the inheritance hierarchy.

I think the problem likely lies in the setup you're doing on the WebAppContext as regards the webapp's classpath. As you're running embedded, effectively the container classpath === the runtime path. Then you've set the WebAppContext webInfClassesDir to be the also the runtimeclasspath? Not sure what ServerX is or where it is located in your app, or what the relationship of that class is to where your WebApplicationInitializer implementation class is located?  It could be that effectively your container classpath and webapp classpath are duplicates: you can have a situation that a class that is on the server's classpath needs to access a class that has been loaded by the webapp's classloader and thus can't see it. Also be aware that the webapp classloader (`o.e.j.webapp.WebAppClassLoader`) hides various classes that are considered to be on the server's classpath from the webapp's classloader, so you may be running into trouble there.

Take a look at the example of an embedded setup here, it may potentially be useful: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ServerWithAnnotations.java

Then I suggest you look in your DEBUG for evidence that your WebApplicationInitializer class is being parsed: you should see output like `"Scanning class blah"`.

Then I suggest you call `server.setDumpAfterStart(true) `and look at the container and webapp classpaths and see if they are reasonable and not overlapping.

Also take a look at the `o.e.j.plus.annotation.ContainerInitializer `class: that is where all the work is done of finding all the appropriate `@HandlesTypes` for a given ServletContainerInitializer: you might find it best to run in debug mode and put a breakpoint in the r`esoveClasses()` method to see the full class hierarchy map that has been scanned.

**Comment by stolsvik** [comment]
Quick reply here, while pondering whether to delve further down into this.

ServerX is that very class the `createServer()` method is defined in, which contains the `public static void main` method to start Jetty. The `TestInitializer` class is laying directly beside it - and the Spring jars are on the classpath.

I need to do the `setWebInfClassesDirs(..)` to get this to work when jamming both my classes (including any `@WebServlets` and similar), and the Spring jars onto the same classpath, e.g. `java -classpath /home/endre/classes;/home/endre/jars/spring.jar` etc. As also is done when running this from inside IntellJ.

The DEBUG log line "Scanning class .." shows my class both with, and without `implements WebApplicationInitializer`.

When in debug, stopping at `resolveClasses()`, if it implements WebApplicationInitializer, it is included in the classMap as value under the key `org.springframework.web.WebApplicationInitializer`, while if it does not implement it, it is not included in that key (it is not there).

The example you linked to doesn't seem to include any other magic to solve this problem?

Note that the setup I showed here actually works just fine - with the caveat that I as mentioned need to "force" the `TestInitializer` to implement `WebApplicationInitializer`, even though it obviously already does (!) by way of the inheritance hierarchy.

I understand that the classloader issues you mention can be the culprit here. But is there then no sane way to get this to work, outside of the `setWebInfClassesDirs()`? (If I do not set that, the AnnotationParser doesn't find _any_ of my own classes).

Edit: A bit more: When running the classpath scanning, the ClassInheritanceHandler shows different results with and without that "implements". If I do have it, the `_inheritanceMap` have keys for both `org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer` and `org.springframework.web.WebApplicationInitializer`, which both contains my class, while if I do not have that implements, only the former is present and have my class as value. That is kinda obvious in that this is what my class directly extends and implements - but I guess it means that the ClassInheritanceHandler "doesn't see" the Spring jars, and thus cannot traverse into the classes? Another pointer to that is that the class hierarchy here is larger (there are several levels, as mentioned in OP), and I guess there should really have been several more such keys in that inheritanceMap? This means that the ClassInheritanceHandler isn't traversing into those Spring classes at all, _but the ClassLoader that actually runs my code can load them (since it works just fine)._ **There is thus evidently a discrepancy between the classpath scanning mechanism, and the actual ClassLoader that runs the code.**

**Comment by janbartel** [comment]
@stolsvik you've told jetty that the spring jar is on the _container_ classpath, and your implementation classes are on the _webapp_ classpath.  By default, as per the doco, jetty scans almost nothing from the _container_ classpath, but everything from the _webapp_ classpath.  So, jetty is not scanning the spring jar to find the `WebApplicationInitializer` class and thus will not have a key for it in the class `inheritanceMap`. If you explicitly make your impl class implement `WebApplicationInitializer`, then when we scan your impl, we find the `WebApplicationInitializer` and thus put its key in the map.

There are 3 alternative solutions:

1. Put your spring jar into the _webapp_ classpath:  `webAppContext.getMetaData().addWebInfJar(spring-jar-as-Resource)`
2. Leave your spring jar on the server classpath, and tell jetty that it should be scanned:  `context.getMetaData().addContainerResource(spring-jar-as-Resource)`
3. Remove the _webapp_ classpath, have everything effectively on the _container_ classpath, and tell jetty which container resources to scan: `context.getMetaData().addContainerResource(spring-jar-as-Resource)` and `context.getMetaData().addContainerResource(impl-classes-dir-as-Resource)`

**Comment by stolsvik** [comment]
Oh. Thanks.

That was a very different way of handling this than I thought. I assumed that you scan the classes that I have pointed to, and resolve them "all the way" (i.e. inheritance and such), and build up that map from that - as the actual ClassLoader pretty much does it, right? What you do is to scan what I have pointed to, and _only_ that, building up the map from that.

I can see that in a "spec compliant situation", with a proper WAR-layout clearly dividing the webapps ClassLoader and container, the result should be identical one way or the other.

This was quite illogical to me - that is, not following the inheritance paths to their end as the classes here in question clearly specify. My resulting code _works_ for most practical purposes, it is a "nice setup" from a programmatic perspective, _except_ that the classpath scanning of Jetty simply does not seems to work: The class obviously is instanceof `WebApplicationInitializer`, there is no `ClassNotFoundException` or similar when the code starts (i.e. the classloading works), _even the `SpringServletContainerInitializer` is actually found and run by Jetty_ - but the end result "just doesn't work".
What is the benefit of this? Scanning the entire Spring.jar's classes would in this case be much more work than just scanning the classes I've pointed to, but following their inheritances.

Thanks for the 3 alternatives. But, as all of them require me to supply `spring-jar-as-Resource`, this makes things rather much more complicated: I will now have to find all jars that java was invoked with, and supply them. There is, AFAIK, not a simple way to do this. _(I now tried all your three solutions, and they all work. I needed to add two Spring jars, using the `<reference class>.class.getProtectionDomain().getCodeSource().getLocation()` trick. It is then obviously simpler to have that class (illogically) directly implement `WebApplicationInitializer`, which also results in much less class scanning)._

Is it not possible to tell Jetty to just drop the division, and treat everything as if it was on the webapp classpath? Or that there was no such division at all, i.e. just the java classpath? Hmm, just tried the `webAppContext.setParentLoaderPriority(true)` too, but that didn't cut it either - the classpath scanning is evidently utterly isolated from what the JVM will actually read and exectute. I can't shake the feeling that this is very hard to understand the rationale for: If the class is found, and it extends a different class - which again extends a class - and the actual running of the class honors this (i.e. the actual classloader sees and loads those classes), it makes zero sense that the classpath scanning _does not_ honor that very same inheritance.

_(PS: Googling for documentation for Jetty is a pain in the ass these days. Most links, from most sources, are dead. Either you come to the Webtide page, or the division of Jetty 9, 10, 11 have evidently resulted in many links instead of going directly to where you should, now drops the path and shows you the selection between those versions instead. Here's one example, but there are tons: https://stackoverflow.com/a/39669575/39334. Here's another: Google for "ContainerIncludeJarPattern". Then click the first link. After a redirect, you end up on http://www.eclipse.org/jetty/documentation.php, loosing all context)_

**Comment by janbartel** [comment]
Remember that  annotation scanning is not, and should not be done by loading classes off the classpath, but by scanning the `.class` files themselves. Thus, we look at the container classpath and all its parents trying to find urls of its jars/dirs etc - this can be tricky when classloaders in the hierarchy are not URLClassloaders.  We don't examine every container classpath jar/dir for annotation scanning because typically there are very very few applicable and it would be a huge waste of time. For running with the jetty distro, we use the context attribute `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` to indicate patterns of jars/dirs on the container classpath that _should_ be scanned, ignoring the others to save time. The spec requires us to _always_ scan the webapp's `WEB-INF/classes` and `WEB-INF/lib` (or their equivalents) - but we also allow you to control that and save time by specifying the attribute `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern`  as a pattern of the only jars/dirs that should be scanned. Note that we don't use the webapp's classloader to find the urls that should be scanned because a) jetty usually has to _construct_ the webapp's classpath (by finding WEB-INF/lib, classes and extraclasses)  and b) it is possible that the webapp's classloader is explicitly set on WebAppContext, and it might not be a URLClassloader.  Even if we did try and scrape them out of the webapp's classloader, we would do that in o.e.j.w.WebInfConfiguration, which is not a class you're using, so you'd still need to do the scraping yourself and tell jetty which webapp jars you want examined.

No need to Google for documentation, the link is right here: https://www.eclipse.org/jetty/documentation.php and linked off jetty's homepage at Eclipse:  https://www.eclipse.org/jetty/

**Comment by stolsvik** [comment]
Okay, so then, in addition to your three solutions, this was the one that I actually was looking for all the time?

```
        // Override the default configurations, stripping down and adding AnnotationConfiguration.
        // https://www.eclipse.org/jetty/documentation/9.4.x/configuring-webapps.html
        // Note: The default resides in WebAppContext.DEFAULT_CONFIGURATION_CLASSES
        webAppContext.setConfigurations(new Configuration[]{
                new WebInfConfiguration(),
                new WebXmlConfiguration(), // Evidently adds the DefaultServlet, as otherwise no read of "/webapp/"
                // new MetaInfConfiguration(),
                // new FragmentConfiguration(),
                new AnnotationConfiguration() // Adds Servlet annotation processing.
        });

        webAppContext.setAttribute(WebInfConfiguration.CONTAINER_JAR_PATTERN, ".*");
```

The pattern not having been tailored for speed quite yet, but still - this is exactly what I was expecting from the start..
_Edit, just for future reference: Here's a better pattern that accomplishes the exact goal: Including classes from the build dir, and the two needed spring-jars: spring-web..jar and spring-webmvc..jar:         `webAppContext.setAttribute(WebInfConfiguration.CONTAINER_JAR_PATTERN, ".*/classes/.*|.*spring-web.*\\.jar");`_


Wrt. classpath scanning, you should look into this library: https://github.com/classgraph/classgraph
It is damn fast, handles jigsaw (modules), and have ways to look for exactly what you need.

Wrt. to following inheritance, without actually loading the classes: Yes, you could have done that, could you not? If you did not find the referenced classes using the resource loading from the webapp classloader, you could then try to see if you found it using the container classloader, thus avoiding the absurdity where a class _definitely_ is instanceof an interface, but Jetty "refuses" to find it, even though when actually running the code, Java/Jetty finds them just fine. That would in this case also be much faster, as you got the "root interest classes" specified, but if these classes referenced other classes, you'd follow the hierarchy of those, but also _only_ those - instead of as now having to load all classes in all the found jars.

Wrt. to the ContainerIncludeJarPattern: Is this then to be understood as "Also Include These Jars From Container Classpath When Doing WebApp Class Scanning"? A little JavaDoc on those constants would have been awesome.

Wrt. to documentation: I would advice against ignorning Google as an entry to find documentation, not only from the canonical sources but also things like StackOverflow etc. Breaking existing links from the entire internet should be avoided. E.g. the Spring project evidently tries to keep things "perma-linkable", which is of great benefit to us users/developers.

Thanks a lot for solving this for me!

**Comment by joakime** [comment]
> The pattern not having been tailored for speed quite yet, but still - this is exactly what I was expecting from the start..

If you value startup speed, look into the build-time `WEB-INF/quickstart-web.xml` generation and the runtime [QuickStartWebApp](https://github.com/eclipse/jetty.project/blob/jetty-9.4.38.v20210224/jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartWebApp.java) instead of the `WebAppContext`

https://www.eclipse.org/jetty/documentation/jetty-9/index.html#quickstart-webapp

> Wrt. classpath scanning, you should look into this library: https://github.com/classgraph/classgraph
> It is damn fast, handles jigsaw (modules), and have ways to look for exactly what you need.

We have, and we cannot use it without serious modifications of classgraph to support the Servlet spec requirements.

There's been a few aborted attempts at other projects to define an embedded class information metadata within jar files for all projects to use.
Servlet, CDI, Spring, Plexus, etc ...

Those groups all have unique requirements that nobody can agree on to form a single set of features to satisfy everyone.

> Wrt. to the ContainerIncludeJarPattern: Is this then to be understood as "Also Include These Jars From Container Classpath When Doing WebApp Class Scanning"? A little JavaDoc on those constants would have been awesome.

Documented at https://www.eclipse.org/jetty/documentation/jetty-9/index.php#container-include-jar-pattern

> Wrt. to documentation: I would advice against ignorning Google as an entry to find documentation, not only from the canonical sources but also things like StackOverflow etc. Breaking existing links from the entire internet should be avoided. E.g. the Spring project evidently tries to keep things "perma-linkable", which is of great benefit to us users/developers.

You can blame Eclipse policy for this, they do not want all of the documentation for all versions to be live on their website forever.
They force an archiving off to archive.eclipse.org for projects versions that are not current.

**Comment by janbartel** [comment]
Great that you've got a solution that's working. I'll go ahead and close the issue now.

**Comment by stolsvik** [comment]
Maybe not a bug wrt. how you have specified this to work, but it is very non-intuitive and makes it even harder than necessary to understand how to configure and use Jetty - it often feels like "hammer all kinds of buttons, googling hard, until it suddenly works". Googling for this problem should give a clear indication of that.

I'd still argue that you could have done something with this:

_Wrt. to following inheritance, without actually loading the classes: If you did not find the inheritance-referenced classes using the resource loading from the webapp classloader, you could then try to see if you found it by asking the container classloader to load the resource, thus avoiding the absurdity where a class definitely is instanceof an interface, but Jetty "refuses" to find it, even though when actually running the code, Java/Jetty finds them just fine._

**Comment by janbartel** [comment]
According to the servlet spec, the classpath and the path of what gets scanned for annotations is very much different: for example when looking for annotations you must exclude class files that originate in a jar that has been excluded by an ordering in web.xml, regardless of whether it is on the classpath or not.

I think you kind of snookered yourself at the outset by commenting out WebInfConfiguration, and then explicitly (and artificially) slicing and dicing your classpath into container and server resources for scanning. The majority of folks who use a fully embedded setup don't slice and dice, everything is on the container classpath and they use the pattern `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` to control what gets scanned. So a single line of code is IMHO very little configuration to deal with annotations which are ridiculously complex in the servlet world.

I hear you on the documentation - all I can say is that we are in the process of overhauling the docs for jetty-10. The info for jetty-9 on annotations has been subsumed into the Operations Guide. I'll look at adding a new section to the new Programming Guide to specifically deal with annotations in an embedded environment.
