### ISSUE TITLE
How to use Jetty HTTP2 Client on GAE Standard Environment

### ISSUE THREAD

**Issue by gbdslmad** [eclipse/jetty.project#6042]
**Jetty version**
Jetty 9.4.7.v20170914.

**Java version**
1.8.0.181

**Question**

I recently [posted a question](https://stackoverflow.com/questions/66397271/problems-running-jetty-http2-on-google-app-engine?noredirect=1#comment117407298_66397271) on Stackoverflow detailing problems we encountered when attempting to run jetty & HTTP2 on Google App Engine. I was advised to pose the question to this GitHub forum.

Our basic question is _Does Google Application Engine Standard Environment support Jetty HTTP/2 (including ALPN support)?_

If the answer to the above question is Yes, does anyone know how can this be achieved?

When running locally it runs successfully.
Our local JVM version is 1.8.0.261. We are currently using Jetty 9.4.7.v20170914. (It also works using the latest jetty version 9.4.38.v20210224.) Essentially we use Jetty client libraries to be able to perform HTTP/2 communication.

However when we upload the application to the Google server it fails - java.lang.IllegalStateException: No Client ALPNProcessors!

The remote jvm declares itself as jvm version = 1.8.0.181. Again we are using Jetty 9.4.7.v20170914. (See GAE Java Release Notes https://cloud.google.com/appengine/docs/standard/java/release-notes.) 

We also provide org.mortbay.jetty.alpn.boot version 8.1.12.v20180117.

Note we have tried our best to apply the recommendations in https://webtide.com/jetty-alpn-java-8u252/. However we do not understand how we can perform the recommendation below extracted from this document, in a GAE context. On GAE we don't know how to modify the command line as suggested in the document. 

"For an application that is still using an OpenJDK version prior to 8u252, the typical command line requires the alpn-boot jar in the bootclasspath and a library that uses the Jetty ALPN APIs (here as an example, jetty-alpn-openjdk8-server) in the classpath:
/opt/openjdk-8u242/bin/java -Xbootclasspath/p:/path/to/alpn-boot-8.1.13.v20181017.jar -classpath jetty-alpn-openjdk8-server-9.4.27.v20200227:..."

**Comment by gregw** [comment]
When running applications on GAE Standard, the HTTP connection (either HTTP1, HTTP2 or now draft versions of HTTP3) is terminated well before the server that the application is running on.   The application will see only a HTTP request, but that might not be actually carried over any actual HTTP protocol over it's entire path through the google infrastructure.

So the answer is that HTTP/2 should be supported, but not "Jetty HTTP/2".  Ie you will not be using the Jetty HTTP2 implementation, rather the Google one.

However, the fact that you say you are picking the jetty version to run, suggests to me that you are not actually using GAE Standard, but on GAE Flex, in which you deploy and image that contains the jetty server.  In this case, the requests are delivered (at least over the final hop) via HTTP/1 and HTTP/2 is not available.   However, as SSL is offloaded to google infrastructure, then it is possible that HTTP/2 connections will also be accepted and just translated to HTTP/1 when delivered to the Flex instance.   Have you checked your browser to see exactly what version is being used?

**Comment by gbdslmad** [comment]
Hi gregw. Thank you for your swift response. 

We are definitely using GAE standard environment, not flex. We are also acting as an HTTP2 client. Our requirement is to submit an HTTP2 request to the Apple APNS (push notifications) server. This will demand HTTP2 from 31st March 2021.

Please can you explain how we could use the Google Jetty HTTP2 implementation within GAE Standard?

Regards, Michael

**Comment by gregw** [comment]
@sbordet Can  you comment here.  What versions of java 8 is needed so that our HTTP2 client can be used without the need to put ALPN jars onto the boot path.
@gbdslmad If  you can upgrade your deployment to us java11 (see https://cloud.google.com/appengine/docs/standard/java11/java-differences) then I believe that ALPN will not be needed (again @sbordet  can you confirm?)

**Comment by joakime** [comment]
For HTTP2 Client, without alpn on bootclasspath, you'll need Java 8u252 or better.
See: https://webtide.com/jetty-alpn-java-8u252/

**Comment by joakime** [comment]
With GAE Standard you have no fine toothed control over the specific JVM you are using.

You just have `<runtime>java8</runtime>` or `<runtime>java11</runtime>` in your `appengine-web.xml`
You are at the mercy of the deployment of that specific location on what specific JVM update within 8/11 is actually used for your webapp.

Would recommend either moving to `<runtime>java11</runtime>` or GAE Flex to solve for your issue.

Staying with `<runtime>java8</runtime>` means you have no control over the JVM black box, which you need to control for success with HTTP/2 + ALPN on Java8 (no matter who's HTTP/2 implementation you choose to use, as you either have to XBootClasspath the SSL layer or use the built-in SSL layer introduced in 8u252).
