### ISSUE TITLE
Rewrite module has broken config in Jetty 10 and 11

### ISSUE THREAD

**Issue by boughtonp** [eclipse/jetty.project#6044]
**Jetty version**
10.0.1

**Java version**
11

**OS type/version**
n/a

**Description**
Enabling rewrite module on Jetty 10/11 complains about missing etc/rewrite-rules.xml

With a simplified start.ini of:

	--module=deploy
	--module=http
	--module=rewrite

I get the following:

	$ java11 -jar ../jetty-home-10.0.1/start.jar
	java.io.IOException: Cannot read file: etc/rewrite-rules.xml
	        at org.eclipse.jetty.start.StartArgs.addUniqueXmlFile(StartArgs.java:262)
	        at org.eclipse.jetty.start.StartArgs.expandModules(StartArgs.java:575)
	        at org.eclipse.jetty.start.Main.processCommandLine(Main.java:358)
	        at org.eclipse.jetty.start.Main.main(Main.java:71)
	
	Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
	       java -jar $JETTY_HOME/start.jar --help  # for more information

Same occurs on 10.0.0 and 11.0.0 (haven't tested 11.0.1 but assume the same issue there)

Commenting the relevant line in `jetty-home-10.0.1/modules/rewrite.mod` allows Jetty to start with no other issues.

**Comment by joakime** [comment]
You just created a start.ini and didn't use the tooling.

Example using the tooling.

```
[joakim@hyperion bases]$ mkdir rewrite-base
[joakim@hyperion bases]$ cd rewrite-base/
[joakim@hyperion rewrite-base]$ java -jar ~/code/jetty/distros/jetty-home-10.0.1/start.jar --add-module=rewrite,http
INFO  : mkdir ${jetty.base}/start.d
INFO  : server          transitively enabled, ini template available with --add-module=server
INFO  : logging-jetty   transitively enabled
INFO  : resources       transitively enabled
INFO  : http            initialized in ${jetty.base}/start.d/http.ini
INFO  : threadpool      transitively enabled, ini template available with --add-module=threadpool
INFO  : rewrite         initialized in ${jetty.base}/start.d/rewrite.ini
INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-jetty
INFO  : logging/slf4j   dynamic dependency of logging-jetty
INFO  : bytebufferpool  transitively enabled, ini template available with --add-module=bytebufferpool
INFO  : mkdir ${jetty.base}/resources
INFO  : copy ${jetty.home}/modules/logging/jetty/resources/jetty-logging.properties to ${jetty.base}/resources/jetty-logging.properties
INFO  : mkdir ${jetty.base}/etc
INFO  : copy ${jetty.home}/modules/rewrite/rewrite-rules.xml to ${jetty.base}/etc/rewrite-rules.xml
INFO  : Base directory was modified
[joakim@hyperion rewrite-base]$ tree
.
├── etc
│   └── rewrite-rules.xml
├── resources
│   └── jetty-logging.properties
└── start.d
    ├── http.ini
    └── rewrite.ini

3 directories, 4 files
```

Using `--add-module=<module>` will create files, directories, download missing jars, etc...

Since you went the advanced route and just defined the modules manually, you are on the hook to manually perform the same steps that the `--add-module` would have done for you.
In other words, it's up to you to create the `etc/rewrite-rules.xml` to suit your needs if you choose to add modules manually.

**Comment by boughtonp** [comment]
It was not necessary to use `--add-module` to enable `rewrite` in previous versions of Jetty.

Given that `modules/rewrite/rewrite-rules.xml` is merely a series of commented-out example rules, I don't see why it should be required to be copied for the module to work?

**Comment by joakime** [comment]
The fact that `--create-files` doesn't work here is interesting.
The `--create-files` concern is likely related to Issue #6049

**Comment by janbartel** [comment]
Seems like the issue has been addressed, and using --add-module=rewrite is the right way to go. If you still have concerns please reopen.
