### ISSUE TITLE
Incorrect Jetty 10/11 source links on download page

### ISSUE THREAD

**Issue by boughtonp** [eclipse/jetty.project#6045]
On http://www.eclipse.org/jetty/download.php there are "source" links for each version.

The 9.4 links work fine, but the 10 link goes to `https://github.com/eclipse/jetty.project/tree/10.0.1`  when it should be `https://github.com/eclipse/jetty.project/tree/jetty-10.0.1` (i.e. missing `jetty-` prefix to version), and same issue for 11.

**Comment by joakime** [comment]
The syntax should probably be `https://github.com/eclipse/jetty.project/releases/tag/<tag>` instead.

Examples:
* https://github.com/eclipse/jetty.project/releases/tag/jetty-10.0.1
* https://github.com/eclipse/jetty.project/releases/tag/jetty-11.0.1

**Comment by WalkerWatch** [comment]
This has been fixed on the site and will be updated when it builds next. Flagging this as documentation.

https://git.eclipse.org/c/www.eclipse.org/jetty.git/commit/?id=7796d2e48fdc6307f730d31004c03cc3d179cc13
