### ISSUE TITLE
Add buffer cleaner APIs to BufferUtil

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6046]
**Jetty version**
10.0.x

**Description**
With Java 11 there is a `Cleaner` API available to quickly reclaim direct/mapped buffers.

We should use `BufferUtil` to allocate a static `java.lang.ref.Cleaner`, and expose `register()` and `clean()` APIs to be used where necessary.

Candidates are:

* `AfterContentTransformer`
* `FileBufferedResponseHandler`
* `CachedContentFactory`
* `DataRateLimitedServlet`

**Comment by lachlan-roberts** [comment]
Looks like this is not going to be possible. The `Cleaner` API won't actually unmap the buffer, it only invokes a Runnable when the buffer becomes phantom reachable.

The only way to do this is to use reflection to get the internal cleaner on `java.nio.DirectByteBuffer`. This has to be done differently between Java 8 and Java 9+. This also doesn't work with JPMS modules.

**Comment by sbordet** [comment]
I'm so disappointed, I really hoped that `Cleaner` would return a `Cleanable` that would free the native memory of direct and mapped `ByteBuffer`s, but that's not the case, unfortunately.
