### ISSUE TITLE
ALPN negotiation failing for HTTP/1.1 when HTTP/2 is enabled

### ISSUE THREAD

**Issue by mcslr** [eclipse/jetty.project#6058]
**Jetty version**
9.4.35.v20201120

**Java version**
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

**OS type/version**
Linux Ubuntu 18.04
macOS Catalina 10.15.3

**Description**

Hi everyone,

I have [dropwizard](https://github.com/dropwizard/dropwizard) service with [HTTP/2 connector](https://www.dropwizard.io/en/latest/manual/configuration.html?highlight=connector#http-2-over-tls) enabled.

> INFO  [2021-03-11 12:09:44,766] org.eclipse.jetty.server.AbstractConnector: Started application@6ac9b66b{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:443}

Connecting via http/2 or http/1.1 works perfectly fine, however http/1.1 + ALPN fails. 

```bash
curl --http2 https://myserviceblabla.com
```
Is OK.

```bash
curl --http1.1 --no-alpn https://myserviceblabla.com
```
Is OK.

```bash
curl --http1.1 https://myserviceblabla.com
```
Fails with cryptic OpenSSL error.

Enabling logging level to DEBUG showed:
> DEBUG [2021-03-11 12:59:03,759] org.eclipse.jetty.alpn.server.ALPNServerConnection: Could not negotiate protocol from client[http/1.1] and server[h2, h2-17] on DecryptedEndPoint@1a4ebfe5{l=/127.0.0.1:443,r=/127.0.0.1:58014,OPEN,fill=-,flush=-,to=40/30000}

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnection.java#L85

After looking a bit more at code I know where the problem is.
https://github.com/dropwizard/dropwizard/blob/v2.0.17/dropwizard-http2/src/main/java/io/dropwizard/http2/Http2ConnectorFactory.java#L111#L112

`ALPNServerConnectionFactory` is constructed with ""h2" and ""h2-17", "http/1.1" is set as default. They are however never "merged" together in `ALPNServerConnection` and that's why selection fails.

Is this jetty bug or dropwizard does not use `ALPNServerConnectionFactory` API correctly? Or perhaps I am missing something?

Thanks!

**Comment by sbordet** [comment]
DropWizard does not use the `ALPNServerConnectionFactory` correctly.

What is passed to the constructor is the list of ALPN protocols that will be negotiated.

Using the `ALPNServerConnectionFactory` no-args constructor will derive the list from all available `ConnectionFactory`s registered with the connector, which will include HTTP/1.1.

**Comment by joschi** [comment]
@sbordet Thanks for the pointer!

Would you have a suggestion how to configure a Jetty `HttpClient` to use ALPN but force selecting HTTP/1.1, similar to how `curl --http1.1 https://example.com/` would perform?

I've tested it manually in https://github.com/dropwizard/dropwizard/pull/3786, but didn't find a way to reproduce this behavior with `HttpClient`, `HttpClientTransportOverHTTP2`, and `HTTP2Client`.

**Comment by sbordet** [comment]
@joschi in Jetty 9.4.x you can configure the client to use just one transport at a time. Either HTTP/1.1, or HTTP/2.

You do so by passing the specific transport to `HttpClient`. If you pass `HttpClientTransportOverHTTP2`, then `HttpClient` only speaks HTTP/2.

You can have 2 `HttpClient`s configured one with the HTTP/1.1 transport and the other with the HTTP/2 transport.

In Jetty 10 we have solved this issue by having a dynamic transport that can speak multiple protocols, see https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-client-http-transport-dynamic.

If you can move to Jetty 10/11, you will have that available (maybe for the next major version of DW).

**Comment by joschi** [comment]
> If you can move to Jetty 10/11, you will have that available (maybe for the next major version of DW).

Yes, it's planned for Dropwizard 3.0.x. I was hoping to be able to verify it in Dropwizard 2.x with Jetty 9.4.x too, but for now manual verification will have to suffice.

Thanks! 😄

**Comment by sbordet** [comment]
@joschi as I said, automatic verification in a test is possible with 2 `HttpClient` instances, should not be a big issue (let us know if it is).

As for DW 3.0.x, are you planning to skip Jetty 10 (and `javax.*`) to going straight to Jetty 11 (and `jakarta.*`)? Just curious.

**Comment by joschi** [comment]
@sbordet We're using two HTTP clients in our tests:
https://github.com/dropwizard/dropwizard/blob/f544c025c8d62db8463c8e6e680102f4c90ae6c2/dropwizard-http2/src/test/java/io/dropwizard/http2/AbstractHttp2Test.java#L41-L45

But as far as I could see, the HTTP/1.1 client (`http1Client` in the example) wouldn't use ALPN to negotiate the protocol.



> As for DW 3.0.x, are you planning to skip Jetty 10 (and `javax.*`) to going straight to Jetty 11 (and `jakarta.*`)? Just curious.

We're planning to go directly to the Jakarta namespace.

**Comment by sbordet** [comment]
> But as far as I could see, the HTTP/1.1 client (http1Client in the example) wouldn't use ALPN to negotiate the protocol.

That is correct in Jetty 9.4.x. Jetty 10+ would.

**Comment by joschi** [comment]
@sbordet Got it. thanks for all your help! 😃
