### ISSUE TITLE
Glassfish mail implementation replacement

### ISSUE THREAD

**Issue by sergiuhlihor** [eclipse/jetty.project#6061]
The current Jetty-All artefact depends on javax.mail.glassfish version 1.4.1.v201005082020, which looks to be an implementation of javax.mail version 1.4.1. 

The API itself is now under jakarta.mail and the latest version is 2.0.0  which is slightly different than 1.x.x version. This makes the usage of both API versions in a project problematic. Would be worth to investigate if whole dependency could be replaced by the newer API and implementation, thus keeping dependencies up to date.
https://mvnrepository.com/artifact/jakarta.mail/jakarta.mail-api/2.0.0
https://mvnrepository.com/artifact/com.sun.mail/jakarta.mail/2.0.0

**Comment by joakime** [comment]
jetty-all is not, and cannot contain all of Jetty.
jetty-all is not meant to be used by build tooling, it only exists as a documentation feature to demonstrate simple (as in 1 class) embedded usage.

See https://www.eclipse.org//lists/jetty-users/msg06030.html

It has been fully removed in Jetty 10+

If the the glassfish mail impl is present in jetty-all, I would consider that a high priority bug, as we are not allowed to include non-eclipse classes within jetty-all.

**Comment by joakime** [comment]
Also, jakarta-mail-api 2.0.0 is for Jakarta EE 9+, as it contains the "big bang" namespace change from `javax.mail` to `jakarta.mail`.

The jakarta-mail 2.0.0 artifact would only be compatible with Jetty 11+.

```
$ curl -O https://repo1.maven.org/maven2/jakarta/mail/jakarta.mail-api/2.0.0/jakarta.mail-api-2.0.0.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  213k  100  213k    0     0   787k      0 --:--:-- --:--:-- --:--:--  787k
$ jar -tvf jakarta.mail-api-2.0.0.jar | grep jakarta
     0 Thu Aug 13 09:40:38 CDT 2020 jakarta/
     0 Thu Aug 13 09:41:12 CDT 2020 jakarta/mail/
     0 Thu Aug 13 09:40:40 CDT 2020 jakarta/mail/util/
     0 Thu Aug 13 09:41:12 CDT 2020 jakarta/mail/internet/
...
```

**Comment by joakime** [comment]
Just checked the jetty-all artifact from `9.4.38.v20210224`, glassfish and javax.mail are not present.
No work needs to be done here.

**Comment by sergiuhlihor** [comment]
We are managing dependecies with Gradle and according to it (gradle dependencies), it is there (leaving aside the fact that we are actually using jetty-all and not only what we need). Here is what I see with gradle:
|    |    +--- org.eclipse.jetty.aggregate:jetty-all:9.4.38.v20210224
|    |    |    +--- org.eclipse.jetty:jetty-client:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-http:9.4.38.v20210224
|    |    |    |    |    +--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    |    \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224
|    |    |    |    |         \--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty:jetty-deploy:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-webapp:9.4.38.v20210224
|    |    |    |    |    +--- org.eclipse.jetty:jetty-xml:9.4.38.v20210224
|    |    |    |    |    |    \--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    |    \--- org.eclipse.jetty:jetty-servlet:9.4.38.v20210224
|    |    |    |    |         +--- org.eclipse.jetty:jetty-security:9.4.38.v20210224
|    |    |    |    |         |    \--- org.eclipse.jetty:jetty-server:9.4.38.v20210224
|    |    |    |    |         |         +--- javax.servlet:javax.servlet-api:3.1.0 -> 4.0.1
|    |    |    |    |         |         +--- org.eclipse.jetty:jetty-http:9.4.38.v20210224 (*)
|    |    |    |    |         |         \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    |    |         \--- org.eclipse.jetty:jetty-util-ajax:9.4.38.v20210224
|    |    |    |    |              \--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    \--- org.eclipse.jetty:jetty-xml:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty:jetty-jmx:9.4.38.v20210224
|    |    |    |    \--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    +--- org.eclipse.jetty:jetty-plus:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-webapp:9.4.38.v20210224 (*)
|    |    |    |    \--- org.eclipse.jetty:jetty-jndi:9.4.38.v20210224
|    |    |    |         \--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    +--- org.eclipse.jetty:jetty-annotations:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-plus:9.4.38.v20210224 (*)
|    |    |    |    +--- org.eclipse.jetty:jetty-webapp:9.4.38.v20210224 (*)
|    |    |    |    +--- javax.annotation:javax.annotation-api:1.3.2
|    |    |    |    +--- org.ow2.asm:asm:9.0
|    |    |    |    \--- org.ow2.asm:asm-commons:9.0
|    |    |    |         +--- org.ow2.asm:asm:9.0
|    |    |    |         +--- org.ow2.asm:asm-tree:9.0
|    |    |    |         |    \--- org.ow2.asm:asm:9.0
|    |    |    |         \--- org.ow2.asm:asm-analysis:9.0
|    |    |    |              \--- org.ow2.asm:asm-tree:9.0 (*)
|    |    |    +--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    +--- org.eclipse.jetty:jetty-jaspi:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-security:9.4.38.v20210224 (*)
|    |    |    |    \--- org.eclipse.jetty.orbit:javax.security.auth.message:1.0.0.v201108011116
|    |    |    +--- org.eclipse.jetty:jetty-jndi:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty:jetty-rewrite:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-server:9.4.38.v20210224 (*)
|    |    |    |    \--- javax.servlet:javax.servlet-api:3.1.0 -> 4.0.1
|    |    |    +--- org.eclipse.jetty:jetty-servlets:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-continuation:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-http:9.4.38.v20210224 (*)
|    |    |    |    +--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty:jetty-quickstart:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-webapp:9.4.38.v20210224 (*)
|    |    |    |    +--- org.eclipse.jetty:jetty-jmx:9.4.38.v20210224 (*)
|    |    |    |    +--- org.eclipse.jetty:jetty-plus:9.4.38.v20210224 (*)
|    |    |    |    +--- org.eclipse.jetty:jetty-annotations:9.4.38.v20210224 (*)
|    |    |    |    \--- javax.transaction:javax.transaction-api:1.3
|    |    |    +--- org.eclipse.jetty.websocket:websocket-servlet:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty.websocket:websocket-api:9.4.38.v20210224
|    |    |    |    \--- javax.servlet:javax.servlet-api:3.1.0 -> 4.0.1
|    |    |    +--- org.eclipse.jetty.websocket:javax-websocket-server-impl:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty:jetty-annotations:9.4.38.v20210224 (*)
|    |    |    |    +--- org.eclipse.jetty.websocket:javax-websocket-client-impl:9.4.38.v20210224
|    |    |    |    |    +--- org.eclipse.jetty.websocket:websocket-client:9.4.38.v20210224
|    |    |    |    |    |    +--- org.eclipse.jetty:jetty-client:9.4.38.v20210224 (*)
|    |    |    |    |    |    +--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    |    |    +--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    |    |    |    \--- org.eclipse.jetty.websocket:websocket-common:9.4.38.v20210224
|    |    |    |    |    |         +--- org.eclipse.jetty.websocket:websocket-api:9.4.38.v20210224
|    |    |    |    |    |         +--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    |    |         \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    |    |    \--- javax.websocket:javax.websocket-client-api:1.0
|    |    |    |    +--- org.eclipse.jetty.websocket:websocket-server:9.4.38.v20210224
|    |    |    |    |    +--- org.eclipse.jetty.websocket:websocket-common:9.4.38.v20210224 (*)
|    |    |    |    |    +--- org.eclipse.jetty.websocket:websocket-client:9.4.38.v20210224 (*)
|    |    |    |    |    +--- org.eclipse.jetty.websocket:websocket-servlet:9.4.38.v20210224 (*)
|    |    |    |    |    +--- org.eclipse.jetty:jetty-servlet:9.4.38.v20210224 (*)
|    |    |    |    |    \--- org.eclipse.jetty:jetty-http:9.4.38.v20210224 (*)
|    |    |    |    \--- javax.websocket:javax.websocket-api:1.0
|    |    |    +--- org.eclipse.jetty.websocket:websocket-client:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty:jetty-alpn-client:9.4.38.v20210224
|    |    |    |    \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty.http2:http2-server:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty.http2:http2-common:9.4.38.v20210224
|    |    |    |    |    \--- org.eclipse.jetty.http2:http2-hpack:9.4.38.v20210224
|    |    |    |    |         +--- org.eclipse.jetty:jetty-util:9.4.38.v20210224
|    |    |    |    |         +--- org.eclipse.jetty:jetty-http:9.4.38.v20210224 (*)
|    |    |    |    |         \--- org.eclipse.jetty:jetty-io:9.4.38.v20210224 (*)
|    |    |    |    \--- org.eclipse.jetty:jetty-server:9.4.38.v20210224 (*)
|    |    |    +--- org.eclipse.jetty.http2:http2-client:9.4.38.v20210224
|    |    |    |    +--- org.eclipse.jetty.http2:http2-common:9.4.38.v20210224 (*)
|    |    |    |    \--- org.eclipse.jetty:jetty-alpn-client:9.4.38.v20210224 (*)
|    |    |    +--- javax.websocket:javax.websocket-api:1.0
|    |    |    +--- javax.servlet:javax.servlet-api:3.1.0 -> 4.0.1
|    |    |    +--- **org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020**
|    |    |    |    \--- org.eclipse.jetty.orbit:javax.activation:1.1.0.v201105071233
|    |    |    \--- org.slf4j:slf4j-api:1.7.30

**Comment by joakime** [comment]
For Jetty 9.x on Java EE 7 / Servlet 3.1, you have only 2 options (the official jar, or our orbit jar), both on the same version.

Glassfish Mail 1.4.1 - https://search.maven.org/artifact/org.glassfish.api/mail

There are no other versions available.

**Comment by janbartel** [comment]
@sergiuhlihor some of the jetty 9.4.x poms do reference glassfish javax.mail, but _only_ to compile against. We stopped distributing the javax.mail jars with jetty as it was getting too complex:  the philosophy of the oracle guys was to put the api and the impl in the _same_ jar, rather than keeping them separate.  So now, for example, you will see that the jetty-jndi/pom.xml references the glassfish javax.mail jar only as a compile-time requirement.  Similarly, the jetty-osgi tests use the glassfish javax.mail jar because it was the only one with an appropriate osgi header at the time.  Things are different in jetty-10, and particularly jetty-11 which is in the jakarta.* namespace.

**Comment by sergiuhlihor** [comment]
Ok, thanks for clarification! I think it all looked confusing because in development environment this dependency is pulled and referenced, then gradle dependencies was showing it. We will switch to individual jars as needed.
