### ISSUE TITLE
Is there a way to lend on a single Jetty version for Spring Boot and Wiremock projects?

### ISSUE THREAD

**Issue by ChameleonTartu** [eclipse/jetty.project#6065]
**Jetty version**
9.2.28.v20190418
9.4.38.v20210224

**Java version**
11.0.9-amzn

**Question**
I have trouble making Spring Boot 2.4.3 and Wiremock 2.27.2 to work together as they contain incompatible jetty versions stated above. Is there a way to fix this?

I posted [StackOverflow QA](https://stackoverflow.com/questions/66641334/how-to-resolve-nested-exception-is-java-lang-noclassdeffounderror-org-eclipse-j) but I cannot find a solution. Could you advice how to make it work?

**Comment by joakime** [comment]
Use the `jetty-bom` in your build tooling.

https://search.maven.org/artifact/org.eclipse.jetty/jetty-bom

That will align the versions to a single one.

**Comment by joakime** [comment]
Also, make sure you are using the `java8` versionset for Wiremock - https://github.com/tomakehurst/wiremock/blob/2.27.2/build.gradle#L49-L56

For example, if you are using maven, use the `wiremock-jre8` release ... 

https://search.maven.org/artifact/com.github.tomakehurst/wiremock-jre8/2.27.2/pom

**Comment by ChameleonTartu** [comment]
@joakime Thank you for the answer! It helped a lot!
