### ISSUE TITLE
Jetty 10 WebSocket operations guide documentation had disappeared.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#6071]
**Jetty version**
10.0.x

**Description**
The Operations Guide websocket documentation introduced in PR #5806 has been somehow removed from the code base and is not present in the 10.0.1 release.

**Comment by lachlan-roberts** [comment]
@sbordet I think this was done in commit 480767a03bd3431be4a82355a6cfda0521849df5, the file was renamed to `protocols-websocket.adoc`, but maybe some of the links weren't changed properly.

**Comment by jflebeau** [comment]
Still wondering when the doc for websockets will be available here : https://www.eclipse.org/jetty/documentation/jetty-10/programming_guide.php
