### ISSUE TITLE
HTTPS calls from browser fail but work from POSTMAN/curl

### ISSUE THREAD

**Issue by parmindersk** [eclipse/jetty.project#6077]
**Jetty version**
11.0.1
**Java version**
11
**Question**
I'm run an embedded Jetty server based on [this code][1]. 

HTTP calls work totally fine. HTTPS calls from POSTMAN/curl work fine. However, when opening the page from Chrome I always get ERR_CONNECTION_CLOSED and nothing loads. Other browsers also do not load the page. The certificate is valid. 

Is this a known issue? Also, how do I enable logging to see what exactly is going on? I use log4j2 for logging and added the following when running but I see no logs.

`-Dorg.eclipse.jetty.LEVEL=TRACE`

  [1]: https://github.com/eclipse/jetty.project/blob/jetty-9.4.5.v20170502/examples/embedded/src/main/java/org/eclipse/jetty/embedded/Http2Server.java

**Comment by gregw** [comment]
Can you try running with `-Djavax.net.debug=all` as that may tell us why the connection is being rejected.
It could be a TLS version issue.

**Comment by parmindersk** [comment]
@gregw  I see a lot of logging now. What do I look for? Log from 1 transaction attached. 

[dbg.log](https://github.com/eclipse/jetty.project/files/6178771/dbg.log)

**Comment by gregw** [comment]
So I just tried the Http2Server code from both 9 and 10 branches with the keystore that is provided. Both worked fine with Chrome.
Can you verify that it works for you if you use the same keystore?

I looked briefly at your dbg.log, but can't see anything obvious other than several retries.  Perhaps compare to a successful connect from curl?

**Comment by parmindersk** [comment]
@gregw  even with self signed cert it's the same issue. Whenever it fails, I see the following statements at the end. 

javax.net.ssl|ALL|12|qtp1486726131-18|2021-03-22 21:27:51.764 EDT|SSLEngineImpl.java:743|Closing outbound of SSLEngine
javax.net.ssl|WARNING|12|qtp1486726131-18|2021-03-22 21:27:51.765 EDT|SSLEngineOutputRecord.java:168|outbound has closed, ignore outbound application data

**Comment by gregw** [comment]
Can you try with some different JVMs?  try 14 and/or 8. Also update your 11 if it is not recent.

**Comment by parmindersk** [comment]
I'll try that. Something interesting - it works from Eclipse. When I build it and run as an executable JAR from command line it doesn't. Eclipse and my system use the same Java. Could be something classpath too?

**Comment by parmindersk** [comment]
Update Java. That didn't work either.
