### ISSUE TITLE
JSSE wrapper for OpenSSL

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6079]
Make OpenSSL available via a JSSE wrapper for fast SSL

**Comment by sbordet** [comment]
Java 16 has better native integration via the Panama project (under incubation, but still), see https://openjdk.java.net/jeps/389 and https://openjdk.java.net/jeps/393

**Comment by sbordet** [comment]
@gregw why this?

Wrapping OpenSSL with JSSE is a monumental work (look at Conscrypt).

Conscrypt is a OpenSSL fork so would not that be enough?

**Comment by sbordet** [comment]
Closing as this would be a large effort, and Conscrypt is already providing a similar solution, although based on BoringSSL which is a fork of OpenSSL.
