### ISSUE TITLE
jetty-cdi is missing from jetty-bom

### ISSUE THREAD

**Issue by rdicroce** [eclipse/jetty.project#6098]
**Jetty version**
10.0.1

**Java version**
11.0.8

**OS type/version**
Windows 10 Pro 20H2

**Description**
The title says it all. jetty-cdi is missing from jetty-bom and should be added.

**Comment by olamy** [comment]
fixed by https://github.com/eclipse/jetty.project/commit/3c9de65b96ed70b8f9ab003ecf8a17bb0c30ccdf
