### ISSUE TITLE
HttpClientRedirectTest/testRedirectWithWrongScheme test failing in CI

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#610]
[CI failure 0](http://ci.webtide.net:9099/job/jetty-9.4.x/org.eclipse.jetty$jetty-client/47/testReport/junit/org.eclipse.jetty.client/HttpClientRedirectTest/testRedirectWithWrongScheme_0_/)

[CI failure 1](http://ci.webtide.net:9099/job/jetty-9.4.x/org.eclipse.jetty$jetty-client/47/testReport/junit/org.eclipse.jetty.client/HttpClientRedirectTest/testRedirectWithWrongScheme_1_/)

**Comment by gregw** [comment]
Oh this test actually failed in 9.4.x not 9.3.x, so I've ignored it in the wrong branch.

**Comment by sbordet** [comment]
I don't see this failing anymore, so closing.
