### ISSUE TITLE
HttpConnection.getBytesIn() incorrect for requests with chunked content 

### ISSUE THREAD

**Issue by bjorncs** [eclipse/jetty.project#6105]
**Jetty version**
9.4.38.v20210224

**Java version**
11.0.7+10

**OS type/version**
MacOS 10.15.7

**Description**
`HttpConnection.bytesIn` is only aggregated when `fillRequestBuffer()` is called from `onFillable()`, not from `fillAndParseForContent()`. The result is that `HttpConnection.getBytesIn()` reports a value lower than than the actual number of bytes filled. I have been able to reproduce this for POST requests using chunked encoding.

**Comment by sbordet** [comment]
@bjorncs thanks for the report, we'll work on the Jetty issue.
How urgent is this for you?

**Comment by bjorncs** [comment]
It's not a blocker - we only use the value for logging purposes at the moment.

**Comment by sbordet** [comment]
@bjorncs can you try the code in PR #6108?

**Comment by joakime** [comment]
Closing, as PR #6108 was merged.
