### ISSUE TITLE
WebAppClassLoader.getResource() can't find resource when the res is not in WEB-INF/classes

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#6117]
**Jetty version**
9.4.34.v20201102
**Java version**
1.8
**Question**
mycode：
```
@Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // can't find the resource when i use path like '../'， there will get null
        Object o = this.getClass().getClassLoader().getResource("../../zsd.json");
       // my current resource path is WEB-INF/classes/
        Object o2 = this.getClass().getClassLoader().getResource(".");

        response.setContentType("text/html");
        ServletOutputStream out = response.getOutputStream();
        out.println("<html>");
        out.println("<h1>Servlet Example</h1>");
        out.println("<hr>");
        out.println("<h3>Hello World Servlet</h3>");
        out.println("<h3>o" + o + "</h3>");
        out.println("<h3>o2" + o2 + "</h3>");
        out.println("<hr>");
        out.println("<a href=\"" + request.getContextPath() +"/\">Main Menu</a>");
        out.println("</html>");
        out.close();
        try {
            Thread.sleep(200);
        } catch (InterruptedException e) {
            getServletContext().log("exception", e);
            Thread.currentThread().interrupt();
        }
    }
```

![image](https://user-images.githubusercontent.com/33625419/112940952-72922380-9160-11eb-9444-dd4e0871adc4.png)

【Question】
1、why i can't get resource when the resource is not in "WEB-INF/classes"?
2、If I don't change the location of the JSON file, what should I do to get the resource?

**Comment by james-z-repo** [comment]
i try to used tomcat/tomee，them rewrite findResource to find resource when res is not in WEB-INF/classes，Will jetty consider changing this？

![image](https://user-images.githubusercontent.com/33625419/112951954-7fb60f00-916e-11eb-8cb3-85ec4e01d5d5.png)

**Comment by joakime** [comment]
If you want to reference content within your WAR / WebApp, don't use the ClassLoader.
Use the methods on `javax.servlet.ServletContext` instead.

If you want a reference to `zsd.json` as a URL on your local filesystem use (Note: this URL could even point to content within a zipfs or jarfs) ...

``` java
URL url = request.getServletContext().getResource("/zsd.json");
```

If you want a reference to `zsd.json` as a String path reference use (Note: this can even point to virtual exploded/expanded locations) ...

``` java
String path = request.getServletContext().getRealPath("/zsd.json");
```

**Comment by joakime** [comment]
> 1. why i can't get resource when the resource is not in "WEB-INF/classes"?

The `WEB-INF/classes` directory is a ClassLoader root reference.
It could be the zipfs or jarfs location within your WAR. (as zipfs or jarfs, there is nothing "above" it, so references to "../" fail)
Or it could be the exploded work directory location. (servlet spec sometimes calls this the virtual location)
Note that the container is free to move content around to suit its needs.
Exposed content (what's in the root of your WAR that is _not within_ `WEB-INF/*`) vs secured content (what is in `WEB-INF/*`) is often treated separately.
Using the `ServletContext` APIs will ensure you can reference the content in your WAR file that you need at all times where the ServletContext is initialized (even if the container uses virtual/work/temp directories to manage things)

**Comment by janbartel** [comment]
Closing as the question has been answered.
