### ISSUE TITLE
adding websocket endpoints programmatically (via ServerContainer.addEndpoint) does not work

### ISSUE THREAD

**Issue by morgwai** [eclipse/jetty.project#6130]
**Jetty version**
10.0.2

**Java version**
openjdk-11

**OS type/version**
ubuntu-18.0.4

**Description**

adding websocket endpoints programmatically (via ServerContainer.addEndpoint) does not work:

ServletContextListener:

```java
	public void contextInitialized(ServletContextEvent event) {
		try {
			var container = ((ServerContainer) event.getServletContext().getAttribute(
				"javax.websocket.server.ServerContainer"));
			container.addEndpoint(
				ServerEndpointConfig.Builder.create(EchoEndpoint.class, "/websocket/echo").build());
		} catch (Exception e) {
			System.err.println("adding endpoint failed: " + e);
		}
	}
```
endpoint:
```java
//@ServerEndpoint("/websocket/echo")
public class EchoEndpoint {

	Session session;

	public EchoEndpoint() { System.out.println("new endpoint instance created"); }

	@OnOpen
	public void onOpen(Session session) {
		System.out.println("new session opened: " + session.getId());
		this.session = session;
		session.setMaxIdleTimeout(5l * 60l * 1000l);
	}

	@OnMessage
	public void onMessage(String message) { session.getAsyncRemote().sendText(message); }
}
```

each time the browser app attempts to open a websocket, the container will create a new endpoint instance (`new endpoint instance created` message from the constructor will appear on the console), but the `onOpen` method will not get called (the message from the method does not appear on the console) and the server will close the socket immediately. no sign of any exception stacktrace on the console.

However, if the `@ServerEndpoint` annotation is uncommented at the top of the `EchoEndpoint` and the `ServletContextListener` is removed, then everything works ok.

on Tomcat the app works ok in both cases

you can see the whole app at https://github.com/morgwai/jetty-websocket

**Comment by joakime** [comment]
> ``` java
> //@ServerEndpoint("/websocket/echo")
> ```

That won't work as a comment.
That annotation is specified to be declared as a formal annotation for a ElementType.TYPE.

See https://github.com/eclipse-ee4j/websocket-api/blob/1.1.2-RELEASE/api/server/src/main/java/javax/websocket/server/ServerEndpoint.java#L55-L57
``` java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface ServerEndpoint {
```

Also, you edited out the import statements that are crucial to troubleshoot this issue.

> you can see the whole app at https://github.com/morgwai/jetty-websocket

This fails the WebSocket TCK, Jetty, Tyrus, and Payara as well.
Simply uncommenting the `@ServerEndpoint` fixes it for Jetty, Tyrus, and Payara.

> on Tomcat the app works ok in both cases

Tomcat has a bug, this is not supported by the websocket spec.

**Comment by morgwai** [comment]
please see inlined below:

On 04/04/2021 19:30, Joakim Erdfelt wrote:
>     //@ServerEndpoint("/websocket/echo")
> 
> That won't work as a comment.
> That annotation is specified to be declared as a formal annotation for a ElementType.TYPE.
> 
> See https://github.com/eclipse-ee4j/websocket-api/blob/1.1.2-RELEASE/api/server/src/main/java/javax/websocket/server/ServerEndpoint.java#L55-L57
> 
> @Retention(RetentionPolicy.RUNTIME)
> @Target(ElementType.TYPE)
> public @interface ServerEndpoint {
 
I've removed the whole line: the effect is exactly the same.



> Also, you edited out the import statements that are crucial to troubleshoot this issue.

what are you referring to? I'll be happy to provide more info, but there's not much there...


> 
>     you can see the whole app at https://github.com/morgwai/jetty-websocket
> 
> This fails the WebSocket TCK, Jetty, Tyrus, and Payara as well.
> Simply uncommenting the |@ServerEndpoint| fixes it for Jetty, Tyrus, and Payara.
> 
>     on Tomcat the app works ok in both cases
> 
> Tomcat has a bug, this is not supported by the websocket spec.

Could you please specify what exactly is not supported by the spec? I don't follow.

Many thanks!

**Comment by joakime** [comment]
A commented line and no line are exactly the same. 
It is an invalid endpoint, and will not be added.

You need to use the java annotations properly.
No comment.
It must be present.
It's an annotation, not a javadoc @tag (which is not the same thing)

See the examples of the 2 ways to receive a message in the spec doc.

https://github.com/eclipse-ee4j/websocket-api/blob/master/spec/src/main/asciidoc/WebSocket.adoc#214-sending-messages

You are attempting to use the second option, the annotation, not the first option which is a MessageHandler.

**Comment by morgwai** [comment]
ah, so you mean that the according to the spec, even Endpoints added programmatically need to be annotated, correct?  That's weird as calling  `ServerContainer.addEndpoint(Class)` will not have any effect actually as a given Endpoint would be added anyway as a result of annotation scanning by the container...
Anyway, in such case this issue is invalid: I'm closing it.
Thanks for your help and sorry for bothering unnecessarily  ;-)

**Comment by morgwai** [comment]
btw: the `//@ServerEndpoint("/websocket/echo")` was not intended to work as a javadoc tag: it was left there as a commented code that was not supposed to have any effect, to easier explain that configuring the endpoint just by uncommenting this line  and disabling any code `ServletContextListener` makes it work (as to prove that the code in the Endpoint works)
