### ISSUE TITLE
Report total number of keys in SelectorManager

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6140]
**Jetty version**
10.0.x

**Description**
For server with a large number of selectors, would be great if `SelectorManager` returns the total number of keys.
Currently each `ManagedSelector` reports its total keys, but the sum of all of them is missing from JMX.

**Comment by strogiyotec** [comment]
@sbordet I made a PR that adds this new JMX propery
https://github.com/eclipse/jetty.project/pull/9869
Please take a look
