### ISSUE TITLE
How to enable the PUT and DELETE methods in jetty embedded? 

### ISSUE THREAD

**Issue by ameti** [eclipse/jetty.project#6146]
**Jetty version**
Jetty(9.4.31.v20200723)
**Java version**
8
**Question**
How do I enable the PUT and DELETE methods in jetty embedded? 
I am currently getting 405 responses

**Comment by joakime** [comment]
Standard Servlet Spec behaviors.

Implement [`HttpServlet.doPut(HttpServletRequest, HttpServletResponse)`](https://github.com/eclipse-ee4j/servlet-api/blob/4.0.4-RELEASE/api/src/main/java/javax/servlet/http/HttpServlet.java#L247-L279) and [`HttpServlet.doDelete(HttpServletRequest, HttpServletResponse)`](https://github.com/eclipse-ee4j/servlet-api/blob/4.0.4-RELEASE/api/src/main/java/javax/servlet/http/HttpServlet.java#L281-L306) in your Servlet code.

Make sure your implementation DOES NOT call `super.doPut(HttpServletRequest, HttpServletResponse)` or `super.doDelete(HttpServletRequest, HttpServletResponse)`.

**Comment by ameti** [comment]
Thank you for fast response. I actually did implement those methods.
Is the default jetty configuration to actually allow these methods?

**Comment by ameti** [comment]
Thank you!
