### ISSUE TITLE
Use recognizable process names (for monitoring tools such as jps)

### ISSUE THREAD

**Issue by jthywiss** [eclipse/jetty.project#615]
Currently, monitoring tools ([jps](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jps.html), as a simple example) report Jetty's process name as "start" (or, in the case when start forks a new JVM, "XmlConfiguration").  "Twould be nice if this were somewhat more recognizable as a Jetty server process.

These tools derive the process name from either: 1) the `main` method's class name, or 2) the JAR name.

Proposed change:
1. Rename `start.jar` to `jetty-start.jar`.
2. Rename (non-test) classes with main methods that run the server to start with "`Jetty`".  If this is too much of a breaking change, add a facade class named "`JettyX`" for class "`X`", and call `JettyX.main` instead of `X.main`.

**Comment by joakime** [comment]
To fix the process named `start` we would need to rename the `start.jar` (which isn't going to happen)

The startup configuration that uses `XmlConfiguration` is just one of many possible choices, its not the only choice.

If you want a custom startup, create your own and set the `-Djetty.start=com.company.CustomStartup`

If you use linux services to initialize jetty, use its pid file to know what's what.

`jps` supports long form display too.

    $ jps -v

**Comment by gregw** [comment]
We are definitely not going to rename start.jar!
But I guess we could do a 
````
class JettyServer extends XmlConfiguration {}
````
But as Joakim says, start can start anything....
