### ISSUE TITLE
Ways to find current queue Size

### ISSUE THREAD

**Issue by christancorp** [eclipse/jetty.project#6151]
Hi,

Understand we can set maximum number of request in a client using setMaxRequestsQueuedPerDestination.

Is there anyway to find out how many request currently in queue already? Sorry if this is a repeated question.

Thanks.

**Comment by sbordet** [comment]
The maximum number of requests is _per destination_; there is currently no direct getter for the total number of requests for all destinations.

This number is typically very volatile: the moment you read it, it's already stale.

You can use a `Request.QueuedListener` and `Request.BeginListener` to know respectively when a request is queued and when it is dequeued.

`Request` listeners can be added to `HttpClient` via `HttpClient.getRequestListeners().add(...)` if you want them to trigger for every request, or to the `Request` itself via `Request.onRequestXYZ(...)`.

**Comment by christancorp** [comment]
Hi @sbordet ,

Thanks for the answer, it helps is there anyway to retrieve the queued list? That might help as well.

Thanks in advance.

**Comment by sbordet** [comment]
> is there anyway to retrieve the queued list?

Why you want to do that?
I ask because if you explain your problem, there may be already existing solutions that don't require accessing the queue of requests.
Please explain your problem first, and why you think accessing the queue would be a solution.

**Comment by christancorp** [comment]
Hi @sbordet ,

Sure, trying to solve an issue when the app is being close but there is still some number of request queued in the jetty client but not complete yet.

If can want to retrieve the queued list and log it somewhere so user can retry later.

Thanks.

**Comment by sbordet** [comment]
> trying to solve an issue when the app is being close but there is still some number of request queued in the jetty client but not complete yet.

These queued requests will be failed as you call `HttpClient.stop()`.
So if you are closing the application, make sure you stop the `HttpClient`.

As for retrying them later, the application will be notified of requests that are failed, so it will be able to save enough information to retry them later.

I don't see any need to access the request queue in your case.

**Comment by janbartel** [comment]
@christancorp seems like you have enough information now to answer your initial question, so I'll close this issue. If you need more help, please reopen with more detailed info.
