### ISSUE TITLE
10.0.x: Perf regression in HttpInput.consumeAll()

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#6157]
**Jetty version**
10.0.x (all versions impacted)

**Description**
During the `HttpInput` refactoring that happened between 9.4.x and 10.0.x, a few harmless minor things were changed. Among those, the `HttpInput.consumeAll()` method used to succeed unconsumed content in 9.4.x while in 10.0.x unconsumed content is now failed.

This is pretty much equivalent in practice, even if the 10.0.x behavior is 'more correct' stricto sensu. except that failing content requires passing an exception instance.

This is exactly where the problem lies: in 10.0.x, `HttpInput.consumeAll()` creates a new `IOException` instance unconditionally. Since this method is on the fast path and creating an exception isn't cheap because of the stack trace collection, there's a visible perf difference between the two versions.

**Comment by lorban** [comment]
Here's a flame graph that clearly shows instantiating that exception isn't negligible: [flame graph.zip](https://github.com/eclipse/jetty.project/files/6296304/flame.graph.zip)

**Comment by gregw** [comment]
Ouch!  It is not exactly trivial to fix as failCurrentContent is always called and always sets the raw and transformed content to an error content wrapping the exception.   Perhaps it can be EOF ???  I've got a branch I'll push but I don't really like it.  Either  way, we want this fixed for next release.

**Comment by lorban** [comment]
@gregw why not simply using a statically allocated exception in `consumeAll`?

**Comment by gregw** [comment]
@lorban I'm not a huge fan of a static throwable, as it doesn't really tell you much.  But it is better than making a throwable we don't need. This PR is also a bit complex, so maybe a static is best.

Anyway, as I'm away, I'll let you fix this one as you see fit.
