### ISSUE TITLE
BadMessageException may lead to inconsistent error handling

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#6158]
**Jetty version**
10.0.2

**Description**

As demonstrated in #6132, when `BadMessageException` is thrown the error handling is a bit inconsistent which leads in that case to an `IllegalStateException` being thrown in the error handling, leading to an error in the error path that blurs the real root cause and forces an abort of the connection.

The culprit seems to be in `HttpChannel.onBadMessage()` which seems to replicate the `HttpChannelState` `handle` / `unhandle` mechanism with some assumptions that aren't always true. This needs to be carefully analyzed and cleaned up.

During the preliminary evaluation of this issue, another potential problem was discovered: `HttpChannel.onBadMessage()` may call the blocking `sendResponse()` method which may hold onto a thread for the duration of the error handling. This sounds undesirable.

**Comment by gregw** [comment]
Whilst looking at `BadMessageException`, I think there are a few instances where we can throw that to the application even though the signature of the method supports IOException.

I think we should consider having a `BadMessage` interface and then both `BadMessageException extends RuntimeExceptions`  and `BadMessageIOException extends IOExeption`.  We should use the later where possible and have utility methods for casting/converting between them.

**Comment by joakime** [comment]
IMO, the `BadMessageException` does make sense when using the `HttpServletRequest.getParameter()` methods against bad request body content.

Perhaps it could be an IOException with a cause that's a BadMessageException?
