### ISSUE TITLE
Improve handling of unconsumed content

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6168]
**Jetty version**
9.4.x

**Description**
The case of unconsumed content, and `HttpInput.Interceptor` throwing an exception, should be handled better.
In particular, make sure that exceptions thrown by the interceptor are correctly handled.

**Comment by sbordet** [comment]
See also #6167.

**Comment by gregw** [comment]
Also, whilst doing a consumeAll, the interceptors should not be called as that can waste CPU and memory.
