### ISSUE TITLE
Minimum Java version support for home modules

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#6172]
**Jetty version**
Jetty 10 - Jetty 11

**Java version**
Java 16+

**OS type/version**
N/A

**Description**
Now that additional features are really starting to show up in incremental releases of Java releases, we should have a mechanism in our module system that allows for a minimum java version for the enabling and execution of a module.  On the enabling side we should test the java version and fail if it isn't sufficient to enable. On the execution side we should fail the start up if the module is enabled but the executing java version is not sufficient indicating the user setup the base with one java version and tried to start it with another one that doesn't carry the feature.  

This would require updates to the documentation as well.

**Comment by sbordet** [comment]
Rather than a new section in `*.mod` files, we can use the "runtime feature" introduced in #5492 that we currently use in Jetty 9.4.x for ALPN, where we have `alpn-available-[true|false].mod` files.
