### ISSUE TITLE
From the code, Jetty reloads both the keystore and truststore when the keystore changes. Can I depend on this behavior ?

### ISSUE THREAD

**Issue by dattasid** [eclipse/jetty.project#6179]
**Jetty version**
10.0
**Java version**
8
**Question**
As in, this behavior will persist across future versions of Jetty? That would make sense as the updated keystore may depend on updated truststore and validate certs might be on.

**Comment by sbordet** [comment]
I think you can rely on this behavior. 
If we will ever introduce separate reloads for KeyStore and TrustStore, I guess we will keep the "reload both" option anyway.

**Comment by joakime** [comment]
How are you using Jetty 10 with Java 8?

**Comment by sbordet** [comment]
Closing as answered.
