### ISSUE TITLE
Memory Leaking when restarting Embedded Jetty Restarting

### ISSUE THREAD

**Issue by visgans** [eclipse/jetty.project#6183]
There is memory leak happening when restarting embedded jetty server v9.4.31. we tried to do the cleanup but the leak still exists. I found out that the leak is happening in jetty components. As we are using Jar library in android application so garbage collection for embedded jetty components are not properly handled. When i isolate jetty server and run the application means the memory leak is zero. After 100 iterations of restart jetty server we got almost 300000 bytes of leaks

**Comment by lachlan-roberts** [comment]
@visgans Can you give a Jetty server dump before and after restarting?
See https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-server-dump

**Comment by visgans** [comment]
[Jetty_Server_start_stop_Dump.txt](https://github.com/eclipse/jetty.project/files/6347902/Jetty_Server_start_stop_Dump.txt)

**Comment by visgans** [comment]
@lachlan-roberts added dumps in text file

**Comment by janbartel** [comment]
@visgans you're a few versions of jetty behind - we're about to release jetty 9.4.41, so you should upgrade to that, or at least 9.4.40.  Also it would be helpful if you have access to some kind of heap dump analysis tool to show where the references are being held.

**Comment by janbartel** [comment]
@visgans it could be related to https://github.com/eclipse/jetty.project/pull/6218. Can you confirm with a memory analyzer tool?
