### ISSUE TITLE
Missing call to setPattern in RewritePatternRule constructor

### ISSUE THREAD

**Issue by pkwarren** [eclipse/jetty.project#620]
https://github.com/eclipse/jetty.project/blob/e79c4d582bbbdebb950765010580c191a7efd73c/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewritePatternRule.java#L46-L51

There is no call to `super(pattern)` or `setPattern` so the passed in `pattern` parameter is unused. The same issue also appears to affect the ResponsePatternRule class.

**Comment by gregw** [comment]
Thanks for pointing this out!
