### ISSUE TITLE
Support stopping deployment on context failure during startup

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#6219]
**Jetty version**

Jetty 10/11

**Description**

Currently when you try and load a webapp for something on the wrong side of the big bang, the way you realize is a handful of exceptions related to class not found for things like servlet Filter, which can be quite far back in the startup log, with the server still up and running regardless.

I wonder if we can improve this experience for users at all, either by outright failing the startup with a clear message stating the issue, or perhaps a startup option for the distribution that crawls through your webapp and calls attention to issues? Both? I have seen @joakime on the lists correcting people trying to run the wrong version of Jetty for their applications and perhaps it could be useful to just have a command we can respond with that will clearly articulate to the user what the source of the problem is, which jar files they have in their war that are problematic, etc.

I question the value to allowing startup when such a gross error is active, that got me thinking of having --strict and --relaxed modes on startup, with --strict being default and terminating upon exceptions detected on startup, that could help with automated deployment tooling that see successful startup regardless of actually being deployed.

Thoughts?

**Comment by joakime** [comment]
If you attempt to deploy a webapp that uses/needs `javax.servlet` on Jetty 11 that war winds up as Unavailable.

There is already behavior for Unavailable to allow the server to fail startup if any webapp is unavailable.
I believe the default is to allow the server to still be running.

See: [WebAppContext.setThrowUnavailableOnStartupException(boolean throwIfStartupException)](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L1287)

**Comment by jmcc0nn3ll** [comment]
How about jakarta on Jetty-10, same deal?

**Comment by joakime** [comment]
Same. `jakarta.servlet` on Jetty 10 is the same behavior.

**Comment by jmcc0nn3ll** [comment]
This should be exposed to the ini and module system better then it looks like it is and documented. 

By default you can run webapps w/o having to explicitly adding the webapp module which in of itself is a bit questionable, but once you add the module we ought to be able to configure this behavior in the `jetty-webapp.xml` file by toggling a property in the `start.d/webapp.ini` file.

However, this feels like it ought to be a setting on the deployment manager since that is the system that you would expect to govern such things.

`jetty.deploy.exitOnWebappUnavailable = true`

Anyway, I can make a PR for to expose this to the `webapp` module.

**Comment by sbordet** [comment]
I don't think you want to exit if the deployment of a new webapp fails.
Better logging for `jakarta` vs `javax` yes, but that is all.
Plus how would this work embedded?

**Comment by jmcc0nn3ll** [comment]
The option to halt already exists and can be configured in a web.xml for a specific webapp, all this does is allow that setting to be broadly enabled to all webapps through the webapp provider.

This has no bearing on embedded, if you wanted similar behavior there and were using the WebAppProvider then you would call the same set* method, or if you wanted on the WebAppContext you would just call the existing method.

**Comment by jmcc0nn3ll** [comment]
IE, turns out this is existing functionality that just hadn't been exposed in a broadly useful fashion, defaults have been respected (though I sort of disagree with them).  I will fix the issue title to better reflect things now that I know about them, thanks @joakime!

If/When this is merged we'll need docs updated @WalkerWatch

**Comment by jmcc0nn3ll** [comment]
Turns out there is an existing feature that will solve this another way.
