### ISSUE TITLE
make jetty-jspc-maven-plugin @threadSafe

### ISSUE THREAD

**Issue by gbo80** [eclipse/jetty.project#6224]
**Jetty version**
9.x, 10.x, 11.x

**Description**
Running the jetty-jspc-maven-plugin in a maven build that uses multiple threads (e.g. "mvn -T1C ...") works (so far I found no problems), but I get a warning that the plugin is not @threadSafe.
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in my-web:
[WARNING] org.eclipse.jetty:jetty-jspc-maven-plugin:9.4.40.v20210413
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```
**Question**
Do we have to expect problems when running a multi-module project that contains multiple web projects with multiple threads?
We use the JSP precompiler in the maven build only for detecting compilation problems while building.
We do not use the precompiled JSPs in production.

**Change request**
Please make the plugin @threadSafe.

Thanks
Günther

**Comment by janbartel** [comment]
@gbo80 I don't anticipate that you will have any threading issues with the jetty-jspc-maven-plugin, but we'll look at adding the appropriate annotation to the plugin.

**Comment by gbo80** [comment]
Thank you very much!

**Comment by olamy** [comment]
pr merged https://github.com/eclipse/jetty.project/commit/04e5c4e07716f0fe76a8707fa5b49e9ff9fb4d9c

**Comment by trajano** [comment]
Can this be re-openned as Jetty 9.4.x still marks it as not-thread-safe

**Comment by olamy** [comment]
@trajano please read here https://github.com/jetty/jetty.project/issues/7958 regarding 9.4.x support
