### ISSUE TITLE
After upgrading jetty to 9.4.38 our log is floaded a lot of messages "2021/05/05 06:16:45 | 2021-05-05 06:16:44.650:WARN:oejs.HttpConnection:qtp676765127-4057: HttpConnection@4add1f37::DecryptedEndPoint@2c987239{l=/10.211.40.50:8443,r=/10.211.48.45:37168,OPEN,fill=-,flush=-,to=0/30000} fill with unconsumed content!"

### ISSUE THREAD

**Issue by shimon-cherny** [eclipse/jetty.project#6234]
9.4.38

Java version 8

Centos 7.6

After upgrading jetty to 9.4.38 our log is floaded a lot of messages "2021/05/05 06:16:45 | 2021-05-05 06:16:44.650:WARN:oejs.HttpConnection:qtp676765127-4057: HttpConnection@4add1f37::DecryptedEndPoint@2c987239{l=/10.211.40.50:8443,r=/10.211.48.45:37168,OPEN,fill=-,flush=-,to=0/30000} fill with unconsumed content!"

There are a lot of messages in the log of these type.

Please advise.

We have upgraded from 9.4.24

**Comment by sbordet** [comment]
You are probably hitting #6121.
Please upgrade to 9.4.40 and report if that fixed the problem for you.

**Comment by shimon-cherny** [comment]
On it. Thank you.
Is there some specific case i should be checking?
Also what is the impact on the end users here and what flow might have caused it?

**Comment by sbordet** [comment]
> Is there some specific case i should be checking?

Not sure what you mean here.

> Also what is the impact on the end users here and what flow might have caused it?

I don't understand this one either?

**Comment by shimon-cherny** [comment]
>  Is there some specific case i should be checking?

What kind of request, payload might have caused that so we can may be mitigate the issue until the patch is applied.
As well not sure it will resolve the issue eventually...

>  Also what is the impact on the end users here and what flow might have caused it?

I am asking if besides this printout in the log there is a request failure or thread infinite loop that will impact end users?

**Comment by sbordet** [comment]
See also #6168.

**Comment by shimon-cherny** [comment]
So my question how can i reproduce\imitate the case of unconsumed content?

**Comment by sbordet** [comment]
> So my question how can i reproduce\imitate the case of unconsumed content?

Why you want to do that? You can look at the fix and related test cases if you want to reproduce.
Upgrading to Jetty 9.4.40 should solve your issue.

**Comment by sbordet** [comment]
Just to be clear, I don't know how you can reproduce your issue, nor I have any idea of the impacts on your end users (how can I possibly know?).

You have provided zero information about your system, the load, the type of requests/responses, etc.

Your issue _looks like_ another couple that we fixed meanwhile, but may be something different, and I said that you may be _probably_ hitting one of the solved issues.

So upgrading to 9.4.40 and reporting back is a good way to go -- it will confirm that you were hitting one of the existing issues, and that the fixes for those also work for you.

If you upgrade and still have the problem, then it is a new issue and we need more information.

**Comment by shimon-cherny** [comment]
Thanks it worked!

**Comment by sbordet** [comment]
@shimon-cherny thanks for the feedback!
