### ISSUE TITLE
JspcMojo overrides user configuration

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#6235]
discussion from https://github.com/eclipse/jetty.project/pull/6230#discussion_r624982269

Given the following configuration:
```
<configuration>
  <jspc>
    <webXmlInclude>foo/bar/blabla.xml</webXmlInclude>
    few other attributes
  </jspc>
</configuration>
```

At the end the value used for jspc.webXmlInclude will be ${basedir}/target/webfrag.xml because we always override with mojo field.

**Comment by janbartel** [comment]
If you can only set these values if they haven't already been set, that would be fine. However, you'll have to look at the base JspC class to work out if they already have default values, which would mean that approach won't work.

**Comment by janbartel** [comment]
So the mojo explicitly sets the following variables, that could potentially override a user setting on the `jspc` object directly in the pom:

- `webXmlInclude` (String)
- `uriRoot` (String)
- `outputDir` (String)
-  `sourceVersion` (String)
- `targetVersion` (String)
- `compile` (boolean)
- `jspFiles` (CSV)

For the String variables, I think these are null in the `JspC` class by default, so the plugin could do a null check and only set them explicitly if they're null.

For the `jspFiles` there is no getter in the `JspC` class, so not possible to do any checks before our mojo sets the jsps to compile.

For the `compile` variable the default in the `JspC` class is `false`, but I'm not really interested in letting people supply a value of `false` which would negate the whole purpose of the plugin ;)
