### ISSUE TITLE
What is the correct way to set up CLIENT-CERT authentication in standalone Jetty?

### ISSUE THREAD

**Issue by dattasid** [eclipse/jetty.project#6256]
**Jetty version**
9

**Java version**
1.8+

**Question**
I want to set up CLIENT-CERT authentication.

Standalone Jetty as in not embedded Jetty. I want to configure using the XML/ini files.

Additionally, how do I override the Default Client Cert authenticator with my own? Does Jetty have the concept of Certificate to username mappers ?

**Comment by sbordet** [comment]
See work done in #5933, available in Jetty 10.
