### ISSUE TITLE
Being able to set tempDirectory for jetty-runner.jar

### ISSUE THREAD

**Issue by jama707** [eclipse/jetty.project#626]
Is there any way to set tempDirectory from command-line instead of xml configuration?

Right now I set it with  `<Set name="tempDirectory">/some/temp/path</Set>` . Is there any way i can pass this path from console without using xml?

**Comment by gregw** [comment]
Note the use of the standard ` java.io.tmpdir` System property documented [here](https://www.eclipse.org/jetty/documentation/9.3.x/ref-temporary-directories.html).

**Comment by jama707** [comment]
Thanks, but it's gonna change it for all other Java processes as well. I was trying to set it for Jetty's Java process.

**Comment by sbordet** [comment]
Setting a system property for one JVM only changes it for that JVM. Other JVM processes remain unchanged.
