### ISSUE TITLE
MacOS allows binding to used port

### ISSUE THREAD

**Issue by tresf** [eclipse/jetty.project#6266]
**Note:** Initially, I wasn't sure whether to post this as a question or as a bug.  Since this has been [asked elsewhere](https://stackoverflow.com/q/9614628/3196753), I thought it was something I was doing wrong, but the more I experiment, the more I feel the behavior is incorrect.

**Jetty version**
```
9.4.40
```

**Java version/vendor** `(use: java -version)`
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment Zulu15.29+15-CA (build 15.0.2+7)
OpenJDK 64-Bit Server VM Zulu15.29+15-CA (build 15.0.2+7, mixed mode)
```

```
file /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java
 /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java: Mach-O 64-bit executable arm64
```

**OS type/version**
```
MacOS Big Sur 11.2.3 (20D91)
Apple M1 Chip (aarch64/ARM64)
```

**Description**

When Jetty is instructed to bind to a port, it succeeds if that port is already bound to PHP (or see below for Python example).

* Expected result:
   * :white_check_mark: Jetty should throw exception that the port is in use.
   ```diff
   e.g.
   - Exception in thread "main" java.io.IOException: Failed to bind to /0.0.0.0:9999
      ... 
   - Caused by: java.net.BindException: Address already in use
   ```
* Actual result:
   * :no_entry_sign: Jetty starts up, does not throw exception.  Oddly, it **is available** at the port specified.  How?

Steps to reproduce:

1. Using php, start a local webserver on port 9999:
   ```bash
   echo "<h1>Hello from php</h1>" > /tmp/index.php && php -S "0.0.0.0:9999" -t /tmp
   ```

2. Visit http://localhost:9999, ensure it's working.
3. Run the following Jetty code to start a service on the same port.
   ```java
    import org.eclipse.jetty.server.*;
    import org.eclipse.jetty.servlet.ServletContextHandler;
    
    public class BindPort {
        public static void main(String ... args) throws Throwable {
            Server server = new Server();
            ServerConnector connector = new ServerConnector(server);
            connector.setPort(9999);
            connector.setHost("0.0.0.0");
            server.setConnectors(new Connector[] {connector});
            ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
            server.setHandler(context);
            server.setStopAtShutdown(true);
            server.start();
            System.out.println("Started listening on " + connector.getHost() + ":" + connector.getPort());
        }
    }
   ```

**Comment by tresf** [comment]
I believe this is a nuance with PHP's limited `-S` option, it must underlyingly set `SO_REUSEADDR` to true, allowing Jetty to take the port (as it should).  I'll use another technique to bind the port with `SO_REUSEADDR` to false and reopen if the bug still exists.

**Comment by tresf** [comment]
Reopening... Reproduced with Python as well... `connector.setReuseAddress(false);` seem to have no affect.

```py
import socket
import sys

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 0)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 0)
#                                                       ^---- THIS SHOULD PREVENT REUSE

# Bind the socket to the port
server_address = ('0.0.0.0', 9999)
print >>sys.stderr, 'starting up on %s port %s' % server_address
sock.bind(server_address)

# Listen for incoming connections
sock.listen(1)

while True:
    # Wait for a connection
    print >>sys.stderr, 'waiting for a connection'
    connection, client_address = sock.accept()
```

**Comment by joakime** [comment]
You can check with dtrace on OSX to see if reuseaddr is active or not.

https://stackoverflow.com/questions/13726975/why-does-os-x-allow-listening-on-the-same-tcp-port-twice

**Comment by tresf** [comment]
@joakime thanks kindly.  Please excuse my inexperience with `dtrace`, I'm unsure how I should be using this tool to verify what the linked S.O article describes.  Here's some one-liners I was able to find online: http://www.brendangregg.com/DTrace/dtrace_oneliners.txt

**Comment by joakime** [comment]
@tresf if you can replicate the condition on your OSX with the stackoverflow example, then it's not a Jetty issue.

Also, you can turn of reuseAddress on Jetty's ServerConnector easily.

``` java
ServerConnector connector = new ServerConnector(server);
connector.setReuseAddress(false);
connector.setPort(9999);
connector.setHost("0.0.0.0");
```

https://github.com/eclipse/jetty.project/blob/jetty-9.4.40.v20210413/jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java#L495-L502

**Comment by tresf** [comment]
> it's not a Jetty issue.

Right, I was aware of this originally which is why I clarified:

> I wasn't sure whether to post this as a question or as a bug.

> ```java
> connector.setReuseAddress(false);
> ```


Per https://github.com/eclipse/jetty.project/issues/6266#issuecomment-839933836, quoting:

> `connector.setReuseAddress(false);` seem to have no affect.

... however I was hoping to receive some assistance with [this advise](https://github.com/eclipse/jetty.project/issues/6266#issuecomment-839941916), quoting: 

> You can check with dtrace on OSX to see if reuseaddr is active or not.
> https://stackoverflow.com/questions/13726975/why-does-os-x-allow-listening-on-the-same-tcp-port-twice

I'm not sure how to confirm this, and I'm sure others experiencing the same issue will be eager to know as well.

**Comment by tresf** [comment]
I'm going to close this out but if someone can shed some light on why neither Python nor PHP honors the reuse address/reuse port settings I think it will help users of the Jetty library / Java developers understand what to expect in regards to port binding.

**Comment by chylek-qr** [comment]
Is there any known workaround? Just ran into this issue where a JacORB program was already running on the same port as Jetty, so all HTTP requests were getting garbled output. `setReuseAddress(false)` also has no effect.
```java
var connector = new ServerConnector(server);
connector.setReuseAddress(false);
connector.setPort(restPort);
```

**Comment by joakime** [comment]
@chylek-qr this issue is for a version of Jetty (9.4.40) which is now at End of Community Support.

* #7958 

If you experience this with a supported version of Jetty (versions 10, 11, or 12), please open a new issue.
