### ISSUE TITLE
Use only start.ini or start.d, not both

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#627]
Make `--add-to-start` look for a start.d directory and if it exists then use it (equivalent to using `--add-to-startd`)

If `start.ini` exists then it is a UsageError to use `--add-to-startd`

Generate warning if both `start.ini` and `start.d` pre-exist

**Comment by gregw** [comment]
@jmcc0nn3ll I've implemented the --add-to-start changes, which meant I had to update the jetty-distribution.   Can you check I've got that right.

**Comment by jmcc0nn3ll** [comment]
aye, will review all that tomorrow

**Comment by jmcc0nn3ll** [comment]
initial testing seems to be good, closing this out with the new jetty-home/jetty-distribution/demo-base setup in place on 9.4.x and master

**Comment by WalkerWatch** [comment]
@gregw Do we want to deprecate --add-to-startd in Jetty 10 (or sooner)? I imagine it will not be needed going forward but that some users will have grown use to it.

**Comment by gregw** [comment]
@WalkerWatch difficult question.     With the unified approach, then essentially all we really need is `--addpto-start=...`.   However, without `--add-to-startd=...` there is no way to create a `start.d` directory from the command line.    We create other optional base directories (eg `webapps`, `etc`, `resources`) as needed, so requiring `start.d` to be created manually is a bit orthogonal.   We can't create it with module (as we do other directories) as it is too late once we start enabling modules.

So perhaps we need a new option `--startd` that creates the `start.d` directory and moves any existing `${jetty.base}/start.ini` file to `${jetty.base}/start.d/start.ini` to be a sibling of any other ini files created by subsequent `--add-to-start` modules?

If starting from scratch, I think that option would be best.   But I'm 50:50 on just keeping `--add-to-startd` vs introducing a new option.      Hmm thinking about it again perhaps I'm 75:25 for adding the `--startd` option, as that gives us a logical place to describe `start.d` behaviour and then everywhere else can just say `--add-to-start` without any nuance.

We could do this in 9.4.x, with a deprecated warning, then remove support in 10.x

thoughts?

**Comment by WalkerWatch** [comment]
@gregw Assuming we went with the `--startd` command and moved `start.ini` into the `${jetty.base}/start.d/` directory, how would that affect ini order precedence, or is that a valid concern?

That said, I do like the idea of `--startd`, but I can see keeping around the legacy `--add-to-startd` for usability. 9.4.x seems a good place to put this in, and 10.x is logical for removal if we decide to go that route.

**Comment by gregw** [comment]
@WalkerWatch the magic of the module system is that it is not dependent on the order that you enable modules.        Other stuff that is put into ini files (eg if you add XML files directly to an ini file) can be order dependent... but if you have order dependencies don't do that - put it in a module.  We don't

Ini files that just enable modules and set properties - so they are order independent.

I'll implement `--startd` in the next week... unless I hear objections first.

**Comment by jmcc0nn3ll** [comment]
--add-to-start=foo will create a start.ini file

I think I prefer keeping around --add-to-startd=foo creating the start.d directory and the foo.ini file, seems for consistent to me then adding another command line option.

Honestly, you are in an empty jetty.base directory and the first decision you are confronted with is 'so I use start.ini or start.d configuration' and keeping that the way we have it makes a lot of sense to me.

--add-to-start=foo being contextually aware of the configuration environment seems like a useful feature on top of the existing options...and maybe feels like a problem documentation can be crafted to solve.

We do have a --create-files option that could also prompt for configuration style perhaps?

**Comment by gregw** [comment]
@jmcc0nn3ll using `--add-to-start=foo` will not create a start.ini file if the `start.d` directory already exists.

The problem with relying on `--add-to-startd=foo` is that it makes every single example we do conditional.  I think we just want `-add-to-start=foo` then not have to explain the difference.     

How about we call the new option `--create-startd`, which is pretty self explanatory (and matches `--create-files`)?

**Comment by jmcc0nn3ll** [comment]
@gregw sure, my point was on a _bare_ jetty.base both --add-to-start and --add-to-startd would create their necessary bits and fobs, which is consistent and a good thing.  It is only --add-to-start that will contextually enable a module based on the presence of one or the other option which can be viewed as a convenience measure.  My point is that letting --add-to-startd linger around in its current form would be fine, it is clear about what is does, it is consistent in form and feature to --add-to-start and we wouldn't need to add another command line option that masks a 'mkdir' command.  But then windows....so ok, talked myself into a --create-startd directory for scripting ease.

**Comment by gregw** [comment]
I've added --create-startd

Interestingly enough,  with that renaming we no longer really need the long "--add-to-start="  and can just have "--add="

I think that it is obvious enough what is being added to in something like:
```
java -jar $JETTY_HOME/start.jar --add=http,deploy
```

So currently I have created --add as a synonym for --add-to-start . -add-to-startd is deprecated and gives a warning.
