### ISSUE TITLE
IOException: Unable to open root Jar file ... MetaInfConfiguration.getTlds(MetaInfConfiguration.java:406) with Spring boot loader + WebAppContext + non-expanded war 

### ISSUE THREAD

**Issue by rbygrave** [eclipse/jetty.project#628]
When using jetty-webapp 9.3.9.v20160517  with WebAppContext in a spring boot loader war (spring boot loader 1.3.5.RELEASE) with a non-expanded war I'm seeing an exception on startup at .MetaInfConfiguration.getTlds(MetaInfConfiguration.java:406).

java.io.IOException: Unable to open root Jar file 'jar:file:///home/rob/github/examples/example-basic-web/target/example-basic-web-1.1-SNAPSHOT.war'
        at org.springframework.boot.loader.jar.Handler.getRootJarFile(Handler.java:169)
        at org.springframework.boot.loader.jar.Handler.getRootJarFileFromUrl(Handler.java:150)
        at org.springframework.boot.loader.jar.Handler.openConnection(Handler.java:91)
        at java.net.URL.openConnection(URL.java:972)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:406)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:326)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:143)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:94)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:411)

## Suggested issue

The issue seems to be in the URL created in getTlds() always prefixes "jar:" to the uri (as shown below). In my setup with spring boot loader and non expanded war the uri passed into getTlds() already has the "jar:" prefix ... so the string constructed for new URL is actually of the form:

`jar:jar:<some jar!/`

... and the `jar:jar:` prefix is the problem and spring boot loader fails to load this URL

```java
    public Collection<URL> getTlds (URI uri) throws IOException
    {
        HashSet<URL> tlds = new HashSet<URL>();
        
        URL url = new URL("jar:"+uri+"!/"); // MY PROBLEM HERE ... 
                                         // ... as uri.toString() already has "jar:" prefix
```

## Proposed fix:

The proposed fix is to only prepend "jar:" if uri.toString() does not already have that prefix.  The code changes below fix this issue for me.

```java
        String jarUri = uriJarPrefix(uri);
        URL url = new URL(jarUri);
```

```java
    private String uriJarPrefix(URI uri) {

        String uriString = uri.toString();
        if (uriString.startsWith("jar:")) {
            return uriString + "!/"; // Effectively fixes my issue ... 
        } else {
            return "jar:"+uriString+"!/";
        }
    }
```

Applying the changes above such that the "jar:" prefix is only appended when it does not already exist fixes the issue for me and webapp starts correctly.

I am looking to prepare a pull request.

**Comment by janbartel** [comment]
@rbygrave thanks for the pull request. Before I apply it, I just want to make sure I properly understand the issue. Can you explain why none of the other MetaInfConfiguration.scanXXX methods fail when using spring boot loader? I know they use jetty's Resource class instead, with lines like:

Resource.newResource("jar:"+uri+"!/META-INF/web-fragment.xml");

So presumably that would actually be jar:jar too, which jetty wouldn't natively support.

thanks,
Jan

**Comment by rbygrave** [comment]
Good point.

Using the debugger I see it is going into line 184 (!/META-INF/resources) and 255 (!META-INF/web-fragments.xml)

In the case of line 184 ... the resourceDir has jar:jar: ... but then goes to line 187 and into resourceDir.exists() which checks the URLConnection (which fails with an error which is ignored - we expect that) and so resourceDir.exists() returns false. So debugging then steps into line 189 to close the resource (and there is no error).

The same for webFrag ... line 255.  That ends up in line 259 because the webFrag jar:jar: blah does not exist  (webFrag.exists() returns false on line 257).

So yes, the scanForResources() and scanForFragment() have a similar problem in that they don't find anything due to the jar:jar: prefix but they don't error per say (and I didn't notice as I haven't needed them).

I think I should go ahead and fix that (with another commit).

**Comment by rbygrave** [comment]
Ok Jan. That last commit addresses the issue for scanForResources() and scanForWebFragments() so I think that is all good now.

I haven't come up with a good mechanism for testing this per say apart from building my full war (with spring boot loader mechanism etc).  I have stepped through with the debugger (and webFrag.exists() etc return false because those resources don't exist in my war).

Cheers, Rob.

**Comment by janbartel** [comment]
Thanks Rob I've applied your pull request for jetty-9.3, jetty-9.4 and jetty-10.

**Comment by rbygrave** [comment]
Awesome thanks.

IOU some documentation on this approach to embedded Jetty / Runnable war
using Spring boot loader (without any other Spring stuff, just the boot
loader with "layout WAR").  Well, I like the approach relative to maven
overlays anyway.  I'll start a discussion on the jetty users mailing list
once 9.3.10 rolls out and point people to an example and docs and see what
unfolds.

Thanks again, Rob.
