### ISSUE TITLE
SecuredRedirectHandler should probably redirect with 301

### ISSUE THREAD

**Issue by mbien** [eclipse/jetty.project#6282]
**Jetty version**
10.0

**Description**
The status code used by SecuredRedirectHandler isn't configurable and currently redirects with 302. If there is no redirect handler set, jetty seems to redirect with 303 by default if the transport-guarantee is set to confidential in web.xml. (some services like the http-01 domain validation challenge used by letsencrypt are not following 303 redirects anymore)

Plain text http is slowly going away in the modern web and the recommended way to redirect from http to https is via 301 - permanently moved.

Consider making 301 the default for SecuredRedirectHandler, or allow it to be configured.

**Comment by gregw** [comment]
@mbien do you have any links to RFC's or other recommendations for using 301 rather than 302 or 303?
Currently without the handler, our ConstraintSecurityHandler will use 302 for HTTP/1.0 and 303 otherwise.

I have no issue making this more configurable, but changing default to 301 doesn't feel correct

**Comment by mbien** [comment]
@gregw i don't have official sources which recommend 301 for https redirects. Its more of a best practice for sites which only serve https. (basically all new sites)

```
curl --head github.com
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://github.com/

curl --head youtube.com
HTTP/1.1 301 Moved Permanently
Content-Type: application/binary
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Mon, 17 May 2021 03:36:35 GMT
Location: https://youtube.com/
...
curl --head mozilla.com
HTTP/1.1 308 Permanent Redirect
Date: Mon, 17 May 2021 03:41:33 GMT
Content-Type: text/html
Content-Length: 164
Connection: keep-alive
Location: https://mozilla.com/
...
// 308 is very similar to 301
```
301 will tell the client that it wants to be only reached under the new (https) url in future. Browsers will cache that and also update bookmarks etc which makes sense for sites only serving https. (https://datatracker.ietf.org/doc/html/rfc2616#section-10.3.2)

I don't have strong feelings regarding the default. But having it configurable would be nice :) I wrote my own SecuredRedirectHandler which does only 301, since I haven't found any other way to achieve this with jetty.
