### ISSUE TITLE
Treat empty path segments are ambiguous.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#6302]
**Description**

Empty path segments `//` should be treated as ambiguous by `HttpUri`.

**Comment by lachlan-roberts** [comment]
@sbordet Do we want this change brought back to 9.4.x as well?

If so it should not be "linked" to PR #6304 which will close this when it is merged.
And this should also be assigned the to `9.4.43` project so it is not forgotten.

**Comment by sbordet** [comment]
> @sbordet Do we want this change brought back to 9.4.x as well?

I think so, but I'll let @gregw decide.

We do have "ambiguous" handling in 9.4.x, just different, right?

**Comment by gregw** [comment]
hmmm it is kind of a new feature.... not entirely sure we need it in 9.  Historically we have broken more things than we fixed when we have done such changes.
So I'm inclined to at least see how the feature plays out in 10 before moving it to 9.
