### ISSUE TITLE
SLOTH Fix Incomplete

### ISSUE THREAD

**Issue by jrchamp** [eclipse/jetty.project#631]
The SLOTH article indicates that ECDSA-SHA1 and DSA-SHA1 are also affected: https://www.mitls.org/pages/attacks/SLOTH

From @gregw on #497:

> [TLSv1, TLSv1.1, TLSv1.2]
> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
> TLS_RSA_WITH_AES_128_CBC_SHA256
> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
> TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
> TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
> TLS_DHE_DSS_WITH_AES_128_CBC_SHA
> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> TLS_RSA_WITH_AES_128_GCM_SHA256
> TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
> TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
> TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
> TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
> TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
> TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
> SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
> TLS_EMPTY_RENEGOTIATION_INFO_SCSV

It seems odd that the following ciphers are not removed by the SLOTH fix https://github.com/eclipse/jetty.project/commit/0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA

Thoughts?

**Comment by gregw** [comment]
Sorry for slow response,

My understanding is that only RSA cyphers are vulnerable and hence we filter for `^.*_RSA_.*_(MD5|SHA|SHA1)$`

Re-reading, I'm not so sure it is RSA only? @joakime @sbordet your thoughts?

**Comment by jrchamp** [comment]
Correct, RSA/DSA/ECDSA, the key does not matter. From the article:
> [...] get rid of MD5 and SHA1 in all your protocol configurations.

This would make the filter: ``^.*_(MD5|SHA|SHA1)$``

**Comment by joakime** [comment]
Looks like openssl only disabled RSA+MD5
https://github.com/openssl/openssl/commit/45473632c54947859a731dfe2db087c002ef7aa7

**Comment by joakime** [comment]
Some quick tests against the cipher lists before and after greg's 21a618e commit show no change in the advertised cipher suites on Java 1.8u92.

@gregw please be careful with your commit message syntax, your commit will not be picked up by the version text processing.

Considering this issue closed.
