### ISSUE TITLE
JMX tests rely on fixed port

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#632]
The jmx-webapp-it integration tests rely on starting a jetty distro on a fixed port. This can conflict with the local environment. Test needs to use a random available port.

**Comment by janbartel** [comment]
Fix in jetty-9.3.x, jetty-9.4.x and master.

**Comment by joakime** [comment]
Moving from an integration test of jetty-distribution to embedded jetty actually doesn't cover the regression that this testcase was created for.

We need to find a solution that uses an unpacked jetty-distribution.

**Comment by joakime** [comment]
This particular testcase needs to stay as a jetty-distribution based integration test.

**Comment by janbartel** [comment]
I don't understand what you mean. The test checks jmx functionality - whether attributes can be retrieved etc. The tests themselves remain pure jmx, no knowledge of how jetty is started. Perhaps you are wanting to test the distribution itself,  and if so then we should have a separate set of unit tests for that.

**Comment by janbartel** [comment]
If we need some distribution-based tests, then lets create a separate issue for that.
