### ISSUE TITLE
Use `RetainableByteBuffer` in `HttpConnection`

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6322]
The `org.eclipse.jetty.server.HttpConnection`  class should use `org.eclipse.jetty.io.RetainableByteBuffer` rather than it's own reference counting of buffers.  This will eventually allow a more efficient buffer pool abstraction to be used that provides `RetainableByteBuffers` directly.

**Comment by gregw** [comment]
@lorban Simone suggested that we do this.   I had a quick look at the input side at least looks achievable, so I thought I'd punt to you with your HttpInput experience.     I think it can be done entirely in `HttpConnection` since every increment of the reference counter is done by calling newContent, so the Content itself can do the retain and release.   I've not yet looked at the output side.

**Comment by sbordet** [comment]
@gregw I don't think the output side is involved at all, as `RetainableByteBuffer` is only for the input side.
By using it, we will make all protocol implementations homogeneous and we could pool them more efficiently.

On the output side, all implementations currently rely on pooled "naked" `ByteBuffer`s but I'm not sure how much better we can do considering that we have to wrap `byte[]` most of the times.

**Comment by gregw** [comment]
Once the next release is out, we need to ask for a few ByteBufferPool dumps from real deployments so we can plot histograms of buffer sizes in the pool.
