### ISSUE TITLE
How can I get the same JSESSIONID that is returned in the cookie through HttpSession.getId()?

### ISSUE THREAD

**Issue by bbergquist0930** [eclipse/jetty.project#6331]
**Jetty version 9.4**

**Java version 11**

**How can I get the same JSESSIONID that is returned in the cookie through HttpSession.getId()?**

I have a REST endpoint that is doing programmatic JAAS login and returning the JSESSIONID via a JSON body.   The JSESSIONID that I retrieve getting the HttpSession and using the `getId` method does not return the extended session ID is adorned with the worker name that is being placed in the cookie.  

For now I check and cast the HttpSession to a Jetty Session and then access the `getExtendedId` method but I am wondering why Jetty could not just return that from the call to `getId`?

Or should it not matter?  I have not followed through the code but what happens if the REST client issues a subsequent request with a JSESSIONID that is not adorned with the worker name?

**Comment by joakime** [comment]
There's nothing in the session handling in Jetty that could handle a JSESSIONID included in the json body of the request or the response (we simply do not look there).

Since what you are attempting to do is not defined in the Servlet spec or the JAAS spec, I would suggest you either consider making a formal JSON Session Handling layer in Jetty or JAAS (difficult, but possible), or using the Jetty Session object through casting like you are doing currently (easy).

Out of curiosity, how are you using Jetty's JAAS support in a such a way that the JSESSIONID is even in a JSON body anywhere?

**Comment by gregw** [comment]
The reason the worker name is not included is that it is not considered part of the id, it is only a routing hint. Ie if the load balancer routes the wrong worker name to a worker node then it doesn't matter. 

Applications should equally not care and should ignore the worker name. They need not generate a worker name in a link... It they can use the methods provided in the API that will correctly add the session to uri

**Comment by janbartel** [comment]
I don't really understand your scenario, but as you are in charge of configuring the jetty server side, why don't you just put the workerId you've configured into a system property so you can access it in your application?

**Comment by bbergquist0930** [comment]
> There's nothing in the session handling in Jetty that could handle a JSESSIONID included in the json body of the request or the response (we simply do not look there).
> 
> Since what you are attempting to do is not defined in the Servlet spec or the JAAS spec, I would suggest you either consider making a formal JSON Session Handling layer in Jetty or JAAS (difficult, but possible), or using the Jetty Session object through casting like you are doing currently (easy).
> 
> Out of curiosity, how are you using Jetty's JAAS support in a such a way that the JSESSIONID is even in a JSON body anywhere?

There is an Angular 10 application (using HTTP and not HTTPS right now) that needs to login to the server.   The Web application is setup to use FORM authentication and while I can login with `curl` with no issue using POST to `j_security_check`, the Angular application cannot.   The Angular application is not local so a CORS filter is setup to provide the proper CORS headers in the response however the filter is not be invoked when POST'ing to `j_security_check` and the CORS headers are not in the response after a successful login.  This triggers an error in the browser.

As a work around, we have implemented a `login` REST endpoint that the Angular application can use to authenticate and get back in the response a JSON object in the body containing the JSESSIONID and other credential information needed for subsequent requests.   The other requests that the Angular application uses can set the JSESSIONID cookie and other credential information in the headers with no issue. 

When I compared what JSESSIONID was being returned in the cookie for a normal FORM authentication using the configured login page verses what I was able to get via the `HttpSession.getId()` that is where I saw the discrepancy.   I am new to Jetty and knowing that this application can be run in a multi-node clustered environment (the application is ONOS https://wiki.onosproject.org/display/ONOS/ONOS), I do not know if not having he appendage of the worker name to the JSESSIONID would cause and issue.  

I did work around it as I said however I wanted to ask the question to get more information.   The use case is then having an alternative login to mechanism that can provide the same information that would be returned by a FORM login hitting `j_security_check`.

**Comment by bbergquist0930** [comment]
> The reason the worker name is not included is that it is not considered part of the id, it is only a routing hint. Ie if the load balancer routes the wrong worker name to a worker node then it doesn't matter.
> 
> Applications should equally not care and should ignore the worker name. They need not generate a worker name in a link... It they can use the methods provided in the API that will correctly add the session to uri

This is the key information I think that I needed.

**Comment by janbartel** [comment]
Closing the issue as I think the question has been answered.
