### ISSUE TITLE
File descriptor leak after EofException

### ISSUE THREAD

**Issue by snikic** [eclipse/jetty.project#634]
Hi,

we experience sporadic file descriptor leaks on our Jetty servers.
We currently use Jetty 9.3.8.v20160314.

Our app runs smoothly for days, and suddenly the file descriptor count starts increasing by roughly 2 files per second, until we hit our open-file-limit of 32.000 after a few hours.

`lsof - c java` shows thousands of TCP connections in CLOSE_WAIT status at that time.

In our logs, we found Broken pipe / Websocket errors right before the file descriptor count starts increasing. I understand that these exceptions are expected whenever a client suddenly closes the connection, however, something seems to go very bad afterwards. No more exceptions are thrown afterwards until the server gets unresponsive due to the open file limit.

We did not find a way to reliably reproduce this issue locally until now.

As you can see in the logs, our application builds up on the CometD framework (version 3.0.5). 

Any help would be much appreciated.

![exception](https://cloud.githubusercontent.com/assets/2975674/15967732/2a1ccc8e-2f29-11e6-9d21-f53c2dd0e0c3.png)
![exception 2](https://cloud.githubusercontent.com/assets/2975674/15967740/2dcff50e-2f29-11e6-8eb5-8dd97d21b3cf.png)

**Comment by sbordet** [comment]
How do you reliably reproduce the issue so that we can reproduce it ourselves and fix it ?

**Comment by snikic** [comment]
Hi Simone,

thanks for the fast response. I tried hard, but i could not reproduce the issue locally or in our QA environment, it just happens every few days in our production environment.

However, usually we detect the increase of the file descriptors before the system becomes unresponsive,  so there would be a chance to do some diagnostics on the running system. Do you have any guidance what to look out for? 

We can also tweak the log level for specific jetty / cometd packages in our production environment. Could you give me a recommendation which packages are most promising to trace down the issue?

Thanks

**Comment by sbordet** [comment]
You want to enable JMX for the server, and take a server dump (i.e. invoke the `dump()` operation on the MBean corresponding to the `org.eclipse.jetty.server.Server` instance).
The server dump shows in what states the connections are, so we get a confirmation that there is a leak.

Along with that, please also take a JVM thread dump. It will show if there are threads blocked in some I/O operation.

Attach both here.

**Comment by ElveElve** [comment]
Hello,

We're currently experiencing the same issue, with jetty 9.3.6.x and CometD 3.0.x

The issue occurs the same way as the @snikic described. The server runs smoothly, then under some heavy load (a DDoS for example) it starts piling up the CLOSE_WAIT's. Previously, under CometD 2.7.x and jetty 9.1.x these CLOSE_WAIT's would pile up, then gradually 'die out' untill the server becomes responsive again. Currently these just pile up to whatever is allowed, never going down.

Example given:

 netstat -anp |grep :80 | awk '{print $6}' | cut -d: -f1 | sort | uniq -c | sort -n
      1 LISTEN
     19 FIN_WAIT2
     32 SYN_RECV
   2534 ESTABLISHED
  49525 CLOSE_WAIT

I've just restarted our services, but will take a thread dump once the issue reoccurs.

Let me know if there is anything else that can be done.

Michael.

**Comment by joakime** [comment]
@sbordet  Isn't Jetty 9.3 only supported with CometD 3.1.x ? (I could be wrong)

@ElveElve can you use a more recent version of Jetty 9.3.x please.  There's been some useful fixes in the more recent releases of Jetty surrounding Async behavior that you could be tripping over.

**Comment by sbordet** [comment]
@joakime CLOSE_WAIT is a problem that I think is independent of CometD: client closed, but the server did not.

We need to check in what state is the server when there are a lot of CLOSE_WAIT around (well, perhaps not 50k or the dump will be huge - but better huge than nothing).

Need the [Server dump](https://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html).

**Comment by ElveElve** [comment]
Hello,

I've enabled the Server dump on our production server just now. As soon as the issue reoccurs, i'll post the dump here.

Michael.

**Comment by ElveElve** [comment]
Hello,

The issue on our production server has occured today. I've taken the jetty dump/jetty thread dump, but no JVM dump.

Please have a look at the attached files for both startup and shutdown logs.

[echat_jetty_dump_startup.txt](https://github.com/eclipse/jetty.project/files/346728/echat_jetty_dump_startup.txt)

[echat_jetty_dump_shutdown.txt](https://github.com/eclipse/jetty.project/files/346729/echat_jetty_dump_shutdown.txt)

**Comment by ElveElve** [comment]
Hello,

The issue reappeared again, can confirm lots (all?) threads from the pool have been consumed on this:

 |   +- 1099 qtp250075633-1099 WAITING
 |   |   +- sun.misc.Unsafe.park(Native Method)
 |   |   +- java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 |   |   +- java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 |   |   +- org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
 |   |   +- org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:164)
 |   |   +- org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:413)
 |   |   +- java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
 |   |   +- org.eclipse.jetty.server.Utf8HttpWriter.write(Utf8HttpWriter.java:183)
 |   |   +- org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:203)
 |   |   +- org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:275)
 |   |   +- java.io.PrintWriter.write(PrintWriter.java:426)
 |   |   +- org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:109)
 |   |   +- org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:326)
 |   |   +- java.io.Writer.write(Writer.java:157)
 |   |   +- org.apache.jasper.runtime.JspWriterImpl.print(JspWriterImpl.java:461)
 |   |   +- org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:155)
 |   |   +- org.apache.jsp.WEB_002dINF.components.website.chatroom.chatroom_jsp._jspx_meth_c_005fimport_005f6(chatroom_jsp.java:855)
 |   |   +- org.apache.jsp.WEB_002dINF.components.website.chatroom.chatroom_jsp._jspService(chatroom_jsp.java:525)
 |   |   +- org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
 |   |   +- javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
 |   |   +- org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
 |   |   +- org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
 |   |   +- org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
 |   |   +- org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
 |   |   +- javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
 |   |   +- org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
 |   |   +- org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
 |   |   +- org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
 |   |   +- org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
 |   |   +- org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
 |   |   +- org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
 |   |   +- org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
 |   |   +- org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
 |   |   +- org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
 |   |   +- org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
 |   |   +- org.eclipse.jetty.server.Dispatcher.include(Dispatcher.java:117)
 |   |   +- org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934)
 |   |   +- org.apache.jsp.room_jsp._jspService(room_jsp.java:232)
 |   |   +- org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
 |   |   +- javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
 |   |   +- org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
 |   |   +- org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
 |   |   +- org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
 |   |   +- org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
 |   |   +- javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
 |   |   +- org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
 |   |   +- org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
 |   |   +- org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
 |   |   +- org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
 |   |   +- org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
 |   |   +- org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
 |   |   +- org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
 |   |   +- org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
 |   |   +- org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
 |   |   +- org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
 |   |   +- org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
 |   |   +- org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
 |   |   +- org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
 |   |   +- org.eclipse.jetty.server.Server.handle(Server.java:517)
 |   |   +- org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
 |   |   +- org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
 |   |   +- org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
 |   |   +- org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
 |   |   +- org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
 |   |   +- org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
 |   |   +- java.lang.Thread.run(Thread.java:745)


I think  the issue never occured on jetty 8.x, when the glassfish JSP engine was the default, 90% positive about this, was long time ago.

Please be aware that the 'waiting' occurs only on the same .jsp page (in this case chatroom.jsp)

Let me know if there is anything that can be done, and if there is any intermediate fix to this.

Michael.

**Comment by ElveElve** [comment]
Hello,

We have upgraded jetty to 9.3.10 and the issue has gone away.

We have not had even a single instance of the aforementioned issue. Also, the performance of the server has returned back to normal - average of 800 users online, while when this bug was in place, the server would peak at 700 then slowly degrade over time and then would hang with the error.

For anyone having the similar issue either user jetty 8.x which relies on continuations (discouraged) or upgrade to 9.3.10

Cheers,

Michael.

**Comment by zhan849** [comment]
Hey, we were using jetty9.3.15.v20161220, and we also experienced socket leak problem. However, we did not see any Java exception pointed out :(

I did a strace on the server process and from the snippet we can see that it is consistent that after writing HTTP header, the second write of http body fails, with EPIPE, and the socket was not closed (I changed information related to our business with xxx).

There might be some mis-behaviored clients, but I think this error should be handled on server side and if there is EPIPE, we should close the socket and throw proper exception to upper layer

```
[pid 29359] write(6230, "HTTP/1.1 200 OK\r\nServer: Restlet-Framework/2.2.1\r\nDate: Tue, 02 "..., 181) = 181
[pid 29359] write(6230, "xxxx ResponseBody xxxx"..., 8192) = -1 EPIPE (Broken pipe)
[pid 29359] --- SIGPIPE (Broken pipe) @ 0 (0) ---
[pid 29359] rt_sigreturn(0xd)           = -1 EPIPE (Broken pipe)
[pid 29359] accept(425, {sa_family=AF_INET6, sin6_port=htons(34093), inet_pton(AF_INET6, "::ffff:10.132.145.122", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 6231
[pid 29359] fcntl(6231, F_GETFL)        = 0x2 (flags O_RDWR)
[pid 29359] getsockname(6231, {sa_family=AF_INET6, sin6_port=htons(12924), inet_pton(AF_INET6, "::ffff:10.132.42.29", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
[pid 29359] getsockname(6231, {sa_family=AF_INET6, sin6_port=htons(12924), inet_pton(AF_INET6, "::ffff:10.132.42.29", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
[pid 29359] fcntl(6231, F_GETFL)        = 0x2 (flags O_RDWR)
--
[pid 29319] read(421,  <unfinished ...>
[pid 29319] <... read resumed> "\0\0\2@", 4) = 4
[pid 29319] read(421,  <unfinished ...>
[pid 29319] <... read resumed> "\0\20T#\0\0\0+f\314\312\375\0\0\0\0\0\0\1\350{\n  \"id\" : \"lva1-app18619.prod.linkedin.com_"..., 576) = 576
[pid 29359] write(6231, "HTTP/1.1 200 OK\r\nServer: Restlet-Framework/2.2.1\r\nDate: Tue, 02 "..., 181) = 181
[pid 29359] write(6231, "xxxx ResponseBody xxxx"..., 8192) = -1 EPIPE (Broken pipe)
[pid 29359] --- SIGPIPE (Broken pipe) @ 0 (0) ---
[pid 29359] rt_sigreturn(0xd)           = -1 EPIPE (Broken pipe)
[pid 29359] accept(425, {sa_family=AF_INET6, sin6_port=htons(43999), inet_pton(AF_INET6, "::ffff:10.132.146.190", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 6232
[pid 29359] fcntl(6232, F_GETFL)        = 0x2 (flags O_RDWR)
[pid 29359] getsockname(6232, {sa_family=AF_INET6, sin6_port=htons(12924), inet_pton(AF_INET6, "::ffff:10.132.42.29", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
[pid 29359] getsockname(6232, {sa_family=AF_INET6, sin6_port=htons(12924), inet_pton(AF_INET6, "::ffff:10.132.42.29", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
[pid 29359] fcntl(6232, F_GETFL)        = 0x2 (flags O_RDWR)
```

@joakime any suggestions? shall i open a new bug or re-open this one?

**Comment by gregw** [comment]
@zhan849 please open a new issue for this.

It would also be really valuable to know how your responses are being written as it is a little strange that there are two writes as jetty normally will do a gather write of header and body together.  Perhaps a little servlet that demonstrates the problem (or at least suffers from the same problem if it get's an EPIPE)

**Comment by gregw** [comment]
@zhan849 we definitely need more information about how you have setup your server. Doing my own experiments with strace I see the responses written as:
```
[pid 21172] writev(46, [{iov_base="HTTP/1.1 200 OK\r\nDate: Tue, 09 J"..., iov_len=146}, {iov_base="<h1>Hello World</h1>\n", iov_len=21}], 2 <unfinished ...>
```
which is a gather write.  So you have something in your setup that is causing different write behaviour, so I need to know that before I can try to reproduce an error on your second write.

**Comment by gregw** [comment]
Doing some more experiments.... if I flush the headers before writing the body I can get the double writes and a normal transaction in strace looks like:
```
[pid 23626] read(49, "GET / HTTP/1.0\n\n", 8192) = 16
[pid 23626] write(49, "HTTP/1.1 200 OK\r\nDate: Tue, 09 J"..., 107) = 107
[pid 23626] write(49, "123456789\n", 10) = 10
[pid 23626] shutdown(49, SHUT_WR)       = 0
[pid 23626] read(49, "", 8192)          = 0
[pid 23626] dup2(48, 49)                = 49
```
The closing conversation is interesting, we do a shutdown to half close the connection, read to give a chance for the client to respond and then use the `dup2` call to close the connection.  No idea what happens to the 'duplicated' FD 48???  But anyway, that's a normal conversation.

If I hack our EndPoint to throw a simulated EPIPE on the second write I get:
```
[pid 24297] read(47, "GET / HTTP/1.0\n\n", 8192) = 16
[pid 24297] write(47, "HTTP/1.1 200 OK\r\nDate: Tue, 09 J"..., 107) = 107
[pid 24297] dup2(48, 47)                = 47
```
which looks like the close is still happening OK with the `dup2`

Anyway - I can't see anything immediately wrong with Jetty's handling, so please open a new issue and give us as much info as you can to reproduce. Also can you try 9.4 ?
