### ISSUE TITLE
The index ID of the request header that Jetty sent to Tomcat was not found in the index table on the Tomcat side

### ISSUE THREAD

**Issue by qingdaoheze** [eclipse/jetty.project#6341]
**Jetty version**
9.4.41.v20210516

**Tomcat version**
9.0.45

**Java version/vendor** `(use: java -version)`
JDK1.8

**OS type/version**
Centos 7

**Description**
I use jetty http client to call tomcat server in h2c protocol. I encountered the following exception after running about 8 hours.
**It seems the header tables are not sync between jetty and tomcat.**

```java
java.lang.NullPointerException
at org.apache.coyote.http2.HpackDecoder.handleIndex(HpackDecoder.java:267)
at org.apache.coyote.http2.HpackDecoder.decode(HpackDecoder.java:109)
at org.apache.coyote.http2.Http2Parser.readHeaderPayload(Http2Parser.java:486)
at org.apache.coyote.http2.Http2Parser.readHeadersFrame(Http2Parser.java:270)
at org.apache.coyote.http2.Http2AsyncParser$FrameCompletionHandler.completed(Http2AsyncParser.java:251)
at org.apache.coyote.http2.Http2AsyncParser$FrameCompletionHandler.completed(Http2AsyncParser.java:164)
at org.apache.tomcat.util.net.SocketWrapperBase$VectoredIOCompletionHandler.completed(SocketWrapperBase.java:1089)
at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper$NioOperationState.run(NioEndpoint.java:1621)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:829)
```
The tomcat source code is as bellow. 
![image](https://user-images.githubusercontent.com/11375765/120353804-83177380-c334-11eb-80c9-8caa0aeb529e.png)

**Comment by joakime** [comment]
Tomcat 9.0.45 is chasing some HPACK issues at the moment (as a result of discussion on #6333)

https://bz.apache.org/bugzilla/show_bug.cgi?id=65340

**Comment by qingdaoheze** [comment]
@joakime The tomcat bug you mentioned above has been confirmed. Its root cause is header parse error. When I expanded the headerByteBuffer, it will be fine. The two issues are different, please help check it. Because the jetty issue occurred when I have expanded the size of headerByteBuffer to a big enough  value.

https://bz.apache.org/bugzilla/show_bug.cgi?id=65340

**Comment by joakime** [comment]
I do not understand your update.

Is the fix on the tomcat side fixing both issues (this one and #6333)?
Have you filed an issue on the tomcat side for this as well?

**Comment by linking12** [comment]
> I do not understand your update.
> 
> Is the fix on the tomcat side fixing both issues (this one and #6333)?
> Have you filed an issue on the tomcat side for this as well?

we do not sue to fix this issue when tomcat fixed decode fixed. but we have make all of header do not index by hpack to make this issue not happen;

in jetty org.eclipse.jetty.http2.hpack.HpackEncoder, we make some change like netty Sensitivity :

```
 else if (fieldSize >= _context.getMaxDynamicTableSize() || header == HttpHeader.CONTENT_LENGTH && !"0".equals(field.getValue()))
                {
                    // The field is too large or a non zero content length, so do not index.
                    indexed = false;
                    encodeName(buffer, (byte)0x00, 4, header.asString(), name);
                    encodeValue(buffer, true, field.getValue());
                    if (_debug)
                        encoding = "Lit" +
                            ((name == null) ? "HuffN" : "IdxNS" + (1 + NBitInteger.octectsNeeded(4, _context.index(name)))) +
                            "HuffV!Idx";
                }
                else
                {
                    // // indexed
                    // indexed = true;
                    // boolean huffman = !DO_NOT_HUFFMAN.contains(header);
                    // encodeName(buffer, (byte) 0x40, 6, header.asString(), name);
                    // encodeValue(buffer, huffman, field.getValue());
                    // if (_debug)
                    // encoding = ((name == null) ? "LitHuffN" : ("LitIdxN" + (name.isStatic() ? "S" : "") + (1 +
                    // NBitInteger.octectsNeeded(6, _context.index(name))))) +
                    // (huffman ? "HuffVIdx" : "LitVIdx");
                    
                    // Still not indexed
                    indexed = false;
                    boolean huffman = !DO_NOT_HUFFMAN.contains(header);
                    encodeName(buffer, (byte)0x00, 4, header.asString(), name);
                    encodeValue(buffer, huffman, field.getValue());
                    if (_debug)
                        encoding = ((name == null) ? "LitHuffN" : ("LitIdxN" + (name.isStatic() ? "S" : "") + (1 + NBitInteger.octectsNeeded(4, _context.index(name))))) +
                            (huffman ? "HuffV!Idx" : "LitV!Idx");
                }
```

i suggest there is configuration to do index or not index in hpack, this configuration  maked decision by user, do not automatic

**Comment by sbordet** [comment]
> i suggest there is configuration to do index or not index in hpack, this configuration maked decision by user, do not automatic

If you don't want to index, set the `maxDynamicTableSize` to 0, for example: `HTTP2Client.setMaxDynamicTableSize(0)`.

**Comment by qingdaoheze** [comment]
I had submitted the same issue in tomcat, please check it:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65350

**Comment by joakime** [comment]
At this point a reproducer or complete debug logs (for both Jetty and Tomcat) will be needed to proceed further.

**Comment by linking12** [comment]
> > i suggest there is configuration to do index or not index in hpack, this configuration maked decision by user, do not automatic
> 
> If you don't want to index, set the `maxDynamicTableSize` to 0, for example: `HTTP2Client.setMaxDynamicTableSize(0)`.

nice, thanks!
