### ISSUE TITLE
Stale Pull Request automation

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6343]
We need to automate handling of stale pull requests.

I would like to see something that:
 + PRs that are not draft but that do not have a open project assigned are either:
    - Assigned to the "current" project?
    - Closed?
    - Commented on with a warning?
 + draft PRs that have not been updated for 2 weeks are marked as stale
 + stale PRs that have not been updated for 2 weeks are closed.

**Comment by gregw** [comment]
@olamy @joakime, I'm not sure who is best to do this, so I've assigned you both.

**Comment by olamy** [comment]
@joakime we could use the "official" github actions https://github.com/actions/stale
and btw use for the current issues stale mechanism to have a single source of configuration.
WDYT?

**Comment by gregw** [comment]
@olamy The standard stale action is a good start.  But we also need an action to check for non-draft issues without a project assigned.

**Comment by olamy** [comment]
@gregw ok so this need some home made development. I can do that as well

**Comment by lachlan-roberts** [comment]
> But we also need an action to check for non-draft issues without a project assigned.

What about PRs that are not important to get into a specific release. Like cleanup PRs or new features or improvements which no one is waiting on.

Maybe we should have a label something that we could assign to a PR to indicate that it does not need to be in the next release.

**Comment by gregw** [comment]
@lachlan-roberts then they can either be assigned to a following release (we can have multiple defined) or they should be draft PRs

**Comment by laeubi** [comment]
To be honest I find any "autoclosing" not polite and making me upset given that I have invest (free) time to think about it, create/propose a fix and then this effort is simply discard (requiring additional effort to prevent this)...

So instead of setting up automatic 'cleanups' it would be more valuable to use that time to getting PRs done, if it is shows that a PR is not needed or the author is not responsive anymore it could still be closed with a reasonable explanation.

**Comment by gregw** [comment]
I think it is also in polite to allow a PR to sit unresolved for a long period.

But I guess stale automation can't know if it is stale because the OP has not responded or if the committers have not acted.

**Comment by olamy** [comment]
> > But we also need an action to check for non-draft issues without a project assigned.
> 
> What about PRs that are not important to get into a specific release. Like cleanup PRs or new features or improvements which no one is waiting on.
> 
> Maybe we should have a label something that we could assign to a PR to indicate that it does not need to be in the next release.

Agree with @lachlan-roberts. what about long standing PR such fix websocket TCK which takes time or PR depending on external such the one I have with Hazelcast? 
Using a label would be good?
Maybe we should even not touch draft PR as they are not to consider as ready/finished?

**Comment by laeubi** [comment]
> Maybe we should even not touch draft PR as they are not to consider as ready/finished?

I really wonder then whats the point of this change ... if the PR is ready/finished there is no point in closing it, if to prevent auto-closing people start creating draft requests instead nothing is gained ... :-)

**Comment by gregw** [comment]
The main point is to not let PR sit untouched for long times or until days before a release cycle. We need to do something to provoke busy developers to find time to progress the PRs.  Sending reminder emails is not sufficient as we all get too many emails as is.

The indication with issues is that the "threat" implied by the store label is enough to get some eyeballs on the issues... since if we let them closer they are closed.... Even if that action is just too remover the stale label.

**Comment by olamy** [comment]
fixed
