### ISSUE TITLE
Issue with UI loading with jetty 9.4.39

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#6360]
**Jetty version**- 9.4.39

**Java version/vendor** `(use: java -version)`
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 8.0.6.20 - pxa6480sr6fp20-20201120_02(SR6 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201102_458768 (JIT enabled, AOT enabled)
OpenJ9   - 5b31a42
OMR      - 6ad3a34
IBM      - b7e48f4)
JCL - 20201119_01 based on Oracle jdk8u271-b09

**OS type/version** -Linux RHEL

**Description**

Issue with UI

org.eclipse.jetty.io.EofException: Early EOF
at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1187)
at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1175)
at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:333)
at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:270)
at javax.servlet.ServletInputStream.readLine(ServletInputStream.java:134)
at com.sterlingcommerce.woodstock.ui.Wizard.getActivity(Wizard.java:1462

**Comment by sbordet** [comment]
Not enough information.

The stack trace shows a client that closed the connection, so not a Jetty issue.

**Comment by 4devwithgit** [comment]
We also tried using the flag as seen in other post,
-Djsse.SSLEngine.acceptLargeFragments=true
But, we didnt see any change in behavior, and it continued to show the issue.

There were issues enabling the jetty log, so at the moment we are trying to get more details.  Can you please copy my colleague to the thread, michael.conners@precisely.com ? 
Thanks

**Comment by joakime** [comment]
@4devwithgit if you think you are subject to the large fragment issue, then upgrade to 9.4.40 (or the newer 9.4.41)

**Comment by joakime** [comment]
This was addressed in Issue #6759  (it's a bug in sterlingcommerce's PsSelector)
