### ISSUE TITLE
Jetty 9.3.21.v20170918 memory leak from JMX

### ISSUE THREAD

**Issue by harish0816** [eclipse/jetty.project#6363]
**Jetty version**
9.3.21.v20170918

**System and Java version**
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b32)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b32, mixed mode)

Container: Apache Karaf 4.1.4
Protocol: HTTP/2

**Description**
During stability test, there was continuous traffic loss and we suspected it to memory leak. On analyzing heap dump , we noticed there is a leakage of jmx objects pointing to jetty. 

We also realized that the certificates was already expired. However, the issue still persisted even after having valid certificate in place.

We see there is a leakage from "org.eclipse.jetty.jmx" when certificates expire, which cause the node to never recover. Memory was not cleared even after a full (stop-the-world) GC was executed.

![jetty memory leak](https://user-images.githubusercontent.com/50336461/120811009-2fda3680-c569-11eb-939e-3eedbb879723.PNG)

PS: We don't have explicit jetty-jmx.xml under /etc, also would like to know if there are options to configure to stop exposing jetty MBeans.

**Comment by joakime** [comment]
Jetty 9.3.21.v20170918 is EOL End Of Life.

See: https://www.eclipse.org/jetty/download.php#version-table

The Jetty 9.4.x is still supported, please update to that at least.

**Comment by harish0816** [comment]
@joakime  Thanks for the reply. I understand that we are way behind. We do have plans to update, but not at least in this year. Meanwhile, I want to know if we have an API /configurations to stop Jetty from exposing MBeans. As I had already mentioned, we don't explicitly have /etc/jetty-jmx.xml.

I was also wondering if you have observed this issue before or might know what could have caused this ?  Also, can we be sure that stepping up Jetty could solve the issue ?

**Comment by sbordet** [comment]
There is no evidence of leakage: when you register an MBean and you take a heap dump, the MBean will show like in the image you have attached in your comment.
But that does not mean there is a memory leak.
Why do you think there is a memory leak?

If you're not using a `jetty-jmx.xml` you (or the library that you are using, that in turn use Jetty) are probably using Jetty's `MBeanContainer` in the code to expose MBeans.

At this point, you should either fix your code or ask the library maintainers to make that code configurable.

**Comment by harish0816** [comment]
Yes the "pax-web" feature in karaf internally creates jetty's MBeanContainer, and apart from this, we don't create any Jetty MBeans in our code.

Well, the reason for leak is that "com.sun.jmx.mbeanserver.JmxMBeanServer" holds ~2.5G of retained heap, and I see Jetty MBeans referencing it.

**Comment by sbordet** [comment]
The `org.eclipse.jetty.jmx.ObjectMBean` instances from your picture above show that they occupy 960 bytes, if I read that correctly.

To go from there to 2.6 GiB either you have millions of them, or something else is eating up that memory.

If you have millions instances, then you have to explain in details what you're doing.
Could be that MBeans are not unregistered properly and a "redeploy" creates new ones.
But you don't say.

If you don't need them, disable their creation from "pax-web".
If you can't disable them from "pax-web", ask them to make it configurable.

Note that since `MBeanContainer is itself an MBean`, you can call its `destroy()` method via JMX to unregister all MBeans.

**Comment by harish0816** [comment]
Thanks. I will check the possibility on pax-web. Meanwhile, I'm just trying to understand the problem better. Here are some more snippets.
Jetty-jmx view, where you can see the entry of "org.eclipse.jetty.jmx" (K,V) seem to consume more. Any reasons for that ?

<img width="498" alt="jetty jmx1" src="https://user-images.githubusercontent.com/50336461/121134846-82f60700-c851-11eb-8083-390d0207be66.PNG">

More expanded view of the same.

<img width="497" alt="jetty jmx with ssl alpn" src="https://user-images.githubusercontent.com/50336461/121133334-d404fb80-c84f-11eb-8c24-3ca88784b08a.PNG">

Let me know what specific details you are looking for and I can share the same.

**Comment by sbordet** [comment]
The Map has 1354507 entries, quite many.
Are they all Jetty MBeans?
If so, are you deploying/undeploying web applications in a loop or something similar?

**Comment by harish0816** [comment]
Well, I looked into top 20 entries, and it's all Jetty MBeans, and definitely feel rest are all the same too. But if I'm right, org.eclipse.jetty.jmx can map only to Jetty MBeans , or is there a possibility that it can map to different values ?
And No, there was no deploy/undeploy happened.

**Comment by sbordet** [comment]
There is not much we can do.

Somehow you are registering almost 1.5 millions MBeans, and it's not Jetty doing that, it must be some loop in your code or in some library you use.

Try to perform a Jetty Server dump: https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-troubleshooting-dump

The Jetty server dump will be enormous in size as it has to dump all those MBeans.
But if you can get it, it should show if there a lot of MBeans of the same type.

Other than that, use a debugger to figure out what MBeans get registered.

I don't think this is a Jetty issue, it's just some application or library misbehavior that you need to troubleshoot.

**Comment by joakime** [comment]
> The Jetty server dump will be enormous in size as it has to dump all those MBeans.
> But if you can get it, it should show if there a lot of MBeans of the same type.

Note that the Jetty Server Dump is not a heapdump.
Use https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-server-dump

If that Jetty Server dump is sane, and your jmx still isn't, then that points at pax-web doing multiple jetty startups / deployments without clearing out old ones.
That would be a pax-web issue.

**Comment by harish0816** [comment]
Late update. We were able to blacklist (i.e. remove) jetty jmx bundle in karaf as it is of no use to us. 

Thanks for the swift support. Much appreciated !!
