### ISSUE TITLE
AsyncMiddleManServlet getInputStream

### ISSUE THREAD

**Issue by swtseaman** [eclipse/jetty.project#6365]
**Jetty version**
9.4.34.v20201102
**Java version**
1.8.0_171
**Question**
Because to read the post content, you need to read the InputStream of HttpServletRequest, but this can only be read once; Then when forwarding, the request content is lost;
So we use the httpservletrequestwrapper wrapper to cache the stream and read it repeatedly;
However, after using the wrapper, asyncmiddlemanservlet does not even forward and does not respond to the request. After a while, there will be an unexpected timeout of java.util.concurrent.timeoutexception: idle timeout expired: 300000 / 300000 ms

**Comment by swtseaman** [comment]
```
public class MiddleHttpServletRequest extends HttpServletRequestWrapper {

    private byte[] body;

    /**
     * Constructs a request object wrapping the given request.
     *
     * @param request
     * @throws IllegalArgumentException if the request is null
     */
    public MiddleHttpServletRequest(HttpServletRequest request) throws IOException {
        super(request);
        body = Streams.readBytesAndClose(request.getInputStream());
    }

    @Override
    public BufferedReader getReader() throws IOException {
        return new BufferedReader(new InputStreamReader(getInputStream()));
    }

    @Override
    public ServletInputStream getInputStream() throws IOException {
        return new ServletInputStreamWrapper(body);
    }
}
```

**Comment by swtseaman** [comment]
```
public class ServletInputStreamWrapper extends ServletInputStream {

    private byte[] data;
    private int idx = 0;

    public ServletInputStreamWrapper(byte[] data) {
        if(data == null) {
            data = new byte[0];
        }
        this.data = data;
    }

    @Override
    public int read() throws IOException {
        if(idx == data.length) {
            return -1;
        }
        return data[idx++] & 0xff;
    }

    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean isReady() {
        return true;
    }

    @Override
    public void setReadListener(ReadListener readListener) {

    }
}
```

**Comment by swtseaman** [comment]
```
clientRequest = new MiddleHttpServletRequest(clientRequest);
super.service(clientRequest, proxyResponse);
```

**Comment by swtseaman** [comment]
The above is the implementation code. If the clientrequest is not packaged, it will not work. I don't know why

**Comment by joakime** [comment]
The only way supported for modifying either the request (from the client) or the response (from the server) is via the `ContentTransformer` interface ([which is how it's documented in the `AsyncMiddleManServlet`](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/proxy/AsyncMiddleManServlet.ContentTransformer.html#transform(java.nio.ByteBuffer,boolean,java.util.List)))

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.41.v20210516/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AsyncMiddleManServlet.java#L680-L743

https://github.com/eclipse/jetty.project/blob/98607f93c7833e7dc59489b13f3cb0a114fb9f4c/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AsyncMiddleManServlet.java#L680-L743

No other technique is supported by the `AsyncMiddleManServlet`.

Note that there is a [`AfterContentTransformer`](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/proxy/AfterContentTransformer.html) implementation provided by `AsyncMiddleManServlet` that you might want to use to simplify your efforts.

**Comment by swtseaman** [comment]
thank! I customize a requestcontenttransformer, and I get the input content; But it happens after rewritetarget; I want to get the input before rewritetarget. I need to select the target address according to different input contents; I don't know if there is any other way

**Comment by swtseaman** [comment]
> The only way supported for modifying either the request (from the client) or the response (from the server) is via the `ContentTransformer` interface ([which is how it's documented in the `AsyncMiddleManServlet`](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/proxy/AsyncMiddleManServlet.ContentTransformer.html#transform(java.nio.ByteBuffer,boolean,java.util.List)))
> 
> See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.41.v20210516/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AsyncMiddleManServlet.java#L680-L743
> 
> https://github.com/eclipse/jetty.project/blob/98607f93c7833e7dc59489b13f3cb0a114fb9f4c/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AsyncMiddleManServlet.java#L680-L743
> 
> No other technique is supported by the `AsyncMiddleManServlet`.
> 
> Note that there is a [`AfterContentTransformer`](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/proxy/AfterContentTransformer.html) implementation provided by `AsyncMiddleManServlet` that you might want to use to simplify your efforts.

I just need to read, I don't need to modify, I want to get the input before rewritetarget.

**Comment by swtseaman** [comment]
After getting the data, you can modify the host and port of the request. It's ready to come. Thank you!
