### ISSUE TITLE
Jetty 12 architecture musings.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6367]
This issue is for general musings and discussions about what could become the architecture for Jetty-12. 
A starting point is some of the ideas raised in the [less is more](https://webtide.com/less-is-more-servlet-api/)blog.  Specifically I'd like to explore the ramifications and pros/cons of:
 a) No cross context request (once a request is in a context/sessionManager/securityManager it is always in that space)
 b) Immutable requests

**Comment by gregw** [comment]
this is a WIP enumerating all the current mutations done on a request.  The methods are listed in approximately execution order:

Caller | Mutation | Finally unset
------ | ------------ | -------------
HttpChannel.onRequest |   setMetaData; setSecure  |  -
SecureRequestCustomizer |  setHttpURI; _setAttributes_; setSecure | -
ForwardedRequestCustomizer | setHttpURI; setSecure; _setRemoteAddr_; setHttpFields;  | -
ProxyCustomizer | _setAttributes_ | -
RewiteCustomizer | * | -
ContextHandler.doScope | setContext; | setContext;
SessionHandler.doScope | setSession; setSessionManager ; enterSession; setRequestSessionId; _setRequestSessionIdFromCookie_ |  setSession; setSessionManager ; 
ServletHandler.doScope | _setServletPathMapping_; setUserIdentityScope | _setServletPathMapping_; setUserIdentityScope
SecurityHandler.handle | setAuthentication ; setMethod ; |
ServletHolder.service; FilterHolder.doFilter | _setAsyncSupported_ | _setAsyncSupported_
RequestDispatcher.forward | _setDispatcherType_; _setAttributes_; setHttpURI; setContext; _setServletPathMapping_; mergeQueryParameters;  GOTO ContextHandler.doScope | setHttpURI; setContext; _setServletPathMapping_; setQueryParameters; resetParameters; _setAttributes_; _setDispatcherType_
Request.startAsync | _setAsyncAttributes_ |
Server.handleAsync | setHttpURI; mergeQueryParameters; setContext; | setHttpURI; setQueryParameters; setContext;

That is a lot of individual mutations, even if we don't do forwarding and/or async request handling!  The methods indicated in italics are purely speculative mutations - ie ones that set up data that is unlikely to be used eg forwarded request attributes.

Let's now look what happens if we get rid of cross context dispatch, so that once a context is associated with a request, it can never be changed. That request will always be for that context and if you want to access another context then another request has to be made. This like session managers can be recovered from the context rather than explicitly set. We also no longer need to keep a list of sessions from different contexts associated with the request:

Caller | Mutation | Finally unset
------ | ------------ | -------------
HttpChannel.onRequest |   setMetaData; setSecure  |  
SecureRequestCustomizer |  setHttpURI; _setAttributes_; setSecure | 
ForwardedRequestCustomizer | setHttpURI; setSecure; _setRemoteAddr_; setHttpFields;  | 
ProxyCustomizer | _setAttributes_ | 
RewiteCustomizer | * | 
ContextHandler.doScope | setContext; | 
SessionHandler.doScope | enterSession; setRequestSessionId; _setRequestSessionIdFromCookie_ |  
ServletHandler.doScope | _setServletPathMapping_; setUserIdentityScope | _setServletPathMapping_; setUserIdentityScope
SecurityHandler.handle | setAuthentication ; setMethod ; |
ServletHolder.service; FilterHolder.doFilter | _setAsyncSupported_ | _setAsyncSupported_
RequestDispatcher.forward | _setDispatcherType_; _setAttributes_; setHttpURI; _setServletPathMapping_; mergeQueryParameters;  GOTO ServletHandler.doScope | setHttpURI; _setServletPathMapping_; setQueryParameters; resetParameters; _setAttributes_; _setDispatcherType_
Request.startAsync | _setAsyncAttributes_ | 
Server.handleAsync | setHttpURI; mergeQueryParameters; | setHttpURI; setQueryParameters; 

Let's now look what happens if we get rid of wrapper object identity. Letting the container wrap request, so that setters do not need to be unset, only wrappers discarded. Also speculative attributes do not need to be set as they can be calculated by the wrapper if they are ever needed.

Caller | Mutation | Finally unset
------ | ------------ | -------------
HttpChannel.onRequest |   setMetaData; setSecure  | 
SecureRequestCustomizer |  setHttpURI; _setAttributes_; setSecure | 
ForwardedRequestCustomizer | setHttpURI; setSecure; _setRemoteAddr_; setHttpFields;  | 
ProxyCustomizer | _setAttributes_ | 
RewiteCustomizer | * | 
ContextHandler.doScope | setContext; | 
SessionHandler.doScope | enterSession; setRequestSessionId; _setRequestSessionIdFromCookie_ |  
ServletHandler.doScope | _setServletPathMapping_; setUserIdentityScope | 
SecurityHandler.handle | setAuthentication ; setMethod ; |
ServletHolder.service; FilterHolder.doFilter | _setAsyncSupported_ |
RequestDispatcher.forward | _setDispatcherType_; _setAttributes_; setHttpURI; _setServletPathMapping_; mergeQueryParameters;  GOTO ServletHandler.doScope | 
Request.startAsync |  | 
Server.handleAsync | setHttpURI; mergeQueryParameters; |

We can now consider converting all/some of the remaining setters to wrappers, also calculating some speculative values only if called:

Caller | Mutation | Finally unset
------ | ------------ | -------------
HttpChannel.onRequest |   setMetaData; setSecure  | 
SecureRequestCustomizer |  SecureRequestWrapper | 
ForwardedRequestCustomizer | ForwardedRequestWrapper;  | 
ProxyCustomizer | ProxiedRequestWrapper | 
RewiteCustomizer | RewrittenRequestWrapper | 
ContextHandler.doScope | ContextRequestWrapper | 
SessionHandler.doScope | SessionRequestWrapper |  
ServletHandler.doScope | ServletRequestWrapper | 
SecurityHandler.handle | SecurityRequestWrapper |
ServletHolder.service; FilterHolder.doFilter |  |
RequestDispatcher.forward | ForwardedRequestWrapper;  GOTO ServletHandler.doScope | 
Request.startAsync |  | 
Server.handleAsync | AsyncRequestWrapper; |

That is looking better but now the concern is that the request may be wrapped very deeply.  For many request methods, the wrapper impl will just be a deligation to a final field, so it will be well optimized, but there still may be a significant cost for a SSL Forwarded Proxied Rewritten Forward Async request that may end up with 10 wrappers on the request.

However, I think the number of wrappers can be itself optimized.  Firstly, the doScope mechanism is a bit complex and artificial, existing really only to allow try/finally to be used to set then unset mutations on the request.  If we are seldom mutating and never unsetting, then the doScope mechanism can be reworked so that it is the context that calculates a single wrapper that has context, session, security and servlet elements added.   The trick will be that we still want to support contexts that don't know about servlets etc. But we already have the ContextHandler -> ServletContextHandler -> WebAppContext hierarchy which can be mirrored in a wrapper hierarchy.       We could potentially do a similar thing of combining the capabilities of Secure/Forwarded/Proxy Customizers - although we might lose some modularity there.

Caller | Mutation | Finally unset
------ | ------------ | -------------
HttpChannel.onRequest |   setMetaData  | 
SecureRequestCustomizer ; ForwardedRequestCustomizer ; ProxyCustomizer  |  ForwardedRequestWrapper | 
RewiteCustomizer | RewrittenRequestWrapper | 
ContextHandler.handle | ContextRequestWrapper | 
RequestDispatcher.forward | ForwardedRequestWrapper;  GOTO ServletHandler.handle | 
Server.handleAsync | AsyncRequestWrapper; |

At this point, an immutable request is looking plausible. The setMetaData moves to the request constructor and we wrap: one or twice to customize; once at the context; once to forward or go async

**Comment by sbordet** [comment]
@gregw not sure about immutable requests... I think the API offered should be immutable, but the implementation is mutable, but always done from a single thread -- the latter should come natural to do and completes before calling application code, guaranteeing thread safety.

**Comment by joakime** [comment]
Is the separation of jakarta.servlet out from core into a webapp/servlet specific layer still on the radar?
If so, have we thought about what the session management and Configuration would look like?

**Comment by jmcc0nn3ll** [comment]
I think a feature for 12 should be the ability to deploy both javax and jakarta servlets, without that feature it will be hard to make the case to EOL 10 and 11 when the time comes. How it comes to pass architecturally surely impacts the request flow described above.

**Comment by gregw** [comment]
@sbordet  I'm going to finish my analysis of where we mutate the request and why, then see how removing cross context dispatch and wrapped object identity features will change that, leaving us with exactly what we have to mutate.   At that point, we can decide if a fully immutable request is workable, or if it needs to be a little mutable under the covers.   My current intention is that the HttpChannel instance will remain a pooled object that is mutable, but that for each cycle we will wrap it with new request instance that is immutable (but may itself be wrapped to change values or API).   The request will be disposed of each cycle to avoid async and lifecycle races.  We already do some mutations on the HttpChannel rather than the request (eg RequestLog), so that may be an approach to get to a truly simple immutable request wrapper that essentially has 2 final fields: Metadata.Request & HttpChannel.     But let me finish the WIP of enumerating the mutations and how they will change with removed features.

@jmcc0nn3ll it is the cross context dispatch plus wrapper object identity feature that makes running javax and jakarta in the same container practically impossible. Unless the container can wrap over request, we can't easily change the API on top of it.

@joakime The intention is to have a core API that can be wrapped to both javax and jarkata.  If that core API happens to be a simpler servlet-api-6.0 then great.   If we have to come up with our own subset, then musts be.       First steps are to do the work to simplify and get to the point where we can wrap request into different APIs. Then come up with core simple API. Then see if there is interest in standardizing that.

**Comment by gregw** [comment]
@sbordet @joakime @jmcc0nn3ll I've done some more work on the mutability analysis and edited my first comment with my ideas of how to get to an immutable wrapped request architecture.    There is a bit of a challenge of how to preserve modularity - ie making context, sessions, security and servlets all optional could be done easily with 4 wrappers; or with total loss of modularity with 1 wrapper; or with goldilocks modularity of 1 wrapper of a type selected from context only, context and servlet or context, servlet and webapp wrapper types.     I don't think you need to full 16 possible wrapper types, just one that knows nothing; one that knows just about contexts and one that can know about contexts, servlet, sessions & security.... or we can just live with multiple wrappers.

@lorban @sbordet do you know how optimized a deligation to a final field can be?  Ie what is the cost of 10 do nothing wrappers on a method invocation?

**Comment by gregw** [comment]
@janbartel can you comment on the simplifications for seasons if a request can only ever be in one context?  Could session ids still be shared between contexts that are directly requested rather than forwarded?

**Comment by janbartel** [comment]
If a request can only ever be in one context, then that will reduce some of the complexity of the SessionHandler and a bit of the SessionCache and we should not need to keep the list of sessions from all the contexts visited during request handling in the Request.

But, allowing the same session id to be reused between contexts still leaves complexity in the SessionIdManager regarding the management of the lifecycle of shared sessionids:  can a requested session id only be used if it is in use by another context?; when a session is destroyed in one context does that require that all other sessions with the same id are destroyed in all contexts?; if a session id is renewed in one context, does that id change propagate to all contexts?

**Comment by lorban** [comment]
@gregw The JIT can optimize do-nothing wrappers to their no-wrapper
equivalent in theory. In practice, that's going to depend on a million
ancillaries.
My gut feeling is that if you have many wrappers you risk hitting some
threshold somewhere that will make the JIT bail out because the code is
deemed too large or too complex.

**Comment by jmcc0nn3ll** [comment]
@gregw I don't know that we necessarily need to or should cross spec dispatch, but once we have the ability to deploy both specifications we are able to merge 10 and 11 into a single release and cut out the lockstep releases of those two releases.  Any release of 12 should really absolve us of having to maintain 10 and 11 at the same time.

Architecturally in its most complex state, it could be as 'simple' as spinning up 2 Server instances with different classloaders osgi or jpmslike, each with their own servlet-implementation. Plop an Server instance in front of it with a Proxy servlet and you can handle both sorts of deployments with one jvm.  That would only be for users that require both inside the same jvm, having two different bases with different servlet-apis that are able to point to the same jetty 12 distribution is probably the most likely situation.  Just that functionality alone would let us close out 10 and 11 and get back down to 2 active release branches.

**Comment by joakime** [comment]
> @gregw The JIT can optimize do-nothing wrappers to their no-wrapper equivalent in theory. In practice, that's going to depend on a million ancillaries. My gut feeling is that if you have many wrappers you risk hitting some threshold somewhere that will make the JIT bail out because the code is deemed too large or too complex.

@lorban and we want to keep the stacks small for the eventual future with Loom threads :smile:

**Comment by gregw** [comment]
Getting rid of the doScope mechanism will substantially reduce most of our stacks

**Comment by gregw** [comment]
I've had a bit of an experiment and too now think that it wont work well to have a rigorous immutable request and do all mutations with wrappers.

Let's look again above at the mutations a done with cross context dispatch removed, we can see that most of the mutations are set once and never change again.   It is almost like we should consider the jetty Request class like a Builder pattern for the immutable `HttpServletRequest` class. I now think we should get rid of the Scoped handler and just change the main Handler signature to:
```java
    boolean scope(Request baseRequest);
    boolean handle(HttpServletRequest request, HttpServletResponse response)
        throws IOException, ServletException;
```

Then when a request is received it will call the scope hierarchy once and only once to do:

Caller | Mutation 
------ | ------------ 
HttpChannel.onRequest |   setMetaData; setSecure  
SecureRequestCustomizer |  setHttpURI; _setAttributes_; setSecure 
ForwardedRequestCustomizer | setHttpURI; setSecure; _setRemoteAddr_; setHttpFields; 
ProxyCustomizer | _setAttributes_ 
RewiteCustomizer | * 
ContextHandler.scope | setContext; 
GzipHandler.scope |  baseRequest.getHttpInput().addInterceptor
SessionHandler.scope | setRequestSessionId; _setRequestSessionIdFromCookie_ 
SecurityHandler.scope | setAuthentication 
ServletHandler.scope | _setServletPathMapping_; setUserIdentityScope |

Then for each dispatch of the request (initial, async, etc) wrappers will be used IFF the following mutations are needed:

Caller | Wrapper For 
------ | ------------
SecurityHandler.handle | setMethod ; 
ServletHolder.service; FilterHolder.doFilter | _setAsyncSupported_
RequestDispatcher.forward | _setDispatcherType_; _setAttributes_; setHttpURI; _setServletPathMapping_; mergeQueryParameters;  GOTO ServletHandler.handle
Request.startAsync | _setAsyncAttributes_ 
Server.handleAsync | setHttpURI; mergeQueryParameters;

Note that I think we can do away with the target field, which was really only there a partial duplication of the path plus named servlets.   Currently the `setUserIdentityScope` actually sets the servlet holder, so we can do named dispatches by adding a different holder in a wrapper, so perhaps that turns into an explicit `setServletHolder`?

Because the `handle` method does not need to mutate (and only occassionally wrap), then it can be passed in just the `HttpServletRequest` instance and not the `Request` instance.   Note that it now returns a boolean rather than calling `baseRequest.setHandled` to indicate the request has been handled (and scope returns a boolean to indicate the request has been accepted and scoped).

Then the next question is is the initial `HttpServletRequest` just the instance of `Request` or is it always a wrapper. The argument for the instance is that you don't need to create the wrapper, but the wrapper should now be very cheap and has the benefits of:
 1. Can link to the `Request` instance with a reference that is broken at the end of the cycle, allowing the expensive inner `Request` to be recycled, but the cheap `HttpServletRequest` to be held by bad references in the application.
 2. You can have different API wrappers: `javax` and `jakarta`
 3. If the spec doesn't change to avoid Object Identity (which it will never do for javax) then a wrap under paradigm can be implemented to insert a dispatch specific wrapper between the `Request` and the `HttpServletRequest`

However, whilst 2. and 3. sound attractive, I'm a bit dubious they are worth it.  We will have the core `HttpChannel`, `HttpInput`, `HttpOutput` and `Request`/`Response` classes in common, but the handlers would all have to be different with `javax` and `jakartata` versions all handlers.  Worst still, if the semantics changes in `jakarta` 6.0, then much of that is implemented in the common `HttpChannel` etc. classes, so it will be hard for them to serve both semantics.

I think that reason 1. above is sufficient reason to do the initial wrapping.

To support `javax` in a `jakarta` container, I think the best thing to do is to add a new `JakartaServletConnector` to jetty-10.  This will use the `jakarta` servlet API to implement a connector into jetty-10's `javax` servlet container.    This is similar to what we did when continuations first came out and were needed by weblogic and websphere.  We were able to make an instance of jetty run entirely within a webapp context.    That was a bit expensive, but with jetty, we can make a very lightweight servlet context in jetty-11 (no security, no session, etc.) which will just be enough to invoke the jetty-10 container. Thus a jetty-11 server will be able to deploy either `jakarta` or `javax` applications.     This does not need to wait for jetty-12, which instead can be focused on the simplicity of a new servlet-6.0 API.  Ultimately jetty-12 would be able to deploy either servlet 4.0, 5.0 and 6.0 applications this way.

**Comment by gregw** [comment]
See #6469

**Comment by gregw** [comment]
@sbordet , @janbartel, @lorban, @joakime, @lachlan-roberts, @olamy, @jmcc0nn3ll 

The servlet-api has accepted the [removal of Object Wrapper Indentity](https://github.com/eclipse-ee4j/servlet-api/pull/413)(OWI), which is a big win for reducing complexity in jetty-12... but might give us a bit more work to do!

The primary driver for removing OWI is to avoid races of async handlers accessing the request object.  Previous, because we were required to keep OWI, it was not possible to wrap a request object to change paths etc. when doing a dispatch.  This meant that the underlying request object needed to mutate when dispatched and then mutate back when the dispatch returned, causing an intrinsic race with any async thread looking at the request as methods like `getContext`, `getServletPath`, `getPathInfo`, `isUserInRole` and others could change depending on when they were called.

From servlet 6.0, not only will OWI identity not be required, but the request/response objects visible during a dispatch must be durable, ie not change after the dispatch returns.  This basically mandates that dispatch be implemented with wrappers rather than with mutable requests.     This will be a good simplification in itself, but we need to look further to see how it might allow some more fundamental changes in the architecture of jetty-12.

So firstly, let's consider how the OWI has influenced the jetty architecture in the first place!

Jetty has a tree of handlers that have a signature like:
```
interface Handler
{
    public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response);
}
```
First thing to note here is that not only do we pass the jetty `baseRequest`, but we pass the `HttpServletRequest` as well.  The primary reason for this was OWI, as we needed to carry the applications wrappers back through `ContextHandler`, `SessionHandler`, `SecurityHandler` and then `ServletHandler`.   Because we were already dependent on the servlet-api for this core API, we also made `Request` implement `HttpServletRequest` so it could be used unwrapped in the majority of cases.

Another huge impact was that because OWI required the request to be mutated, we did that in the handlers in steps.  So the `RewriteHandler` might change the request, then a `ContextHandler` would strip the context path off the front of the pathInfo, then the `SessionHandler` would add a session object (or at least a link to a session manager) and finally the `ServletHandler` would split the servletPath off the front of the `pathInfo`.   We do all these mutations on the way into the handler tree and then undo all (actually most) of them on the way out... which was fine until we had async servlets that might enter the stack multiple times, so we have to redo and undo those same mutations multiple times (except in the rare case of cross context dispatch, when they are redone but differently).

Worse yet, extra behaviors were added the the servlet spec that required action in the context and security level that knew about which servlet was mapped.   So we then had to add the ScopedHandler concept, so our calling stack would look like:
```
ContextHandler.handle -> 
  SessionHandler.doScope -> 
    SecurityHandler.doScope -> 
      ServletHandler.doScope -> 
        ContextHandler.doHandle->
          SessionHandler.doHandle->
            SecurityHandler.doHandler->
              ServletHandler.doHandler->
                Servlet.service
```
which also has to be done on every dispatch (so potentially several times for an async request).


So does the demise of OWI mean that we don't need all this complexity???  Well I think we can definitely reduce some complexity, but perhaps not entirely.

Let's consider how we might implement a handler API that not only avoids this wrapping complexity, but is independent of the servlet-api (so jetty-12 can run multiple versions).
It might look something like:


```
interface Handler
{
    public Request scope(MetaData.Request request);
    public boolean handle(Request request);
}
```
So we will still need a scoping method so we can identify which context and which resources within the context is the target of the request.  If the Request is to primarily immutable, this could be a factory method kind of like I have shown... but it is hard to achieve that split over multiple handlers.  Perhaps the request will need to be initially mutable and then frozen after the return from scope (may work better with a recycled request)?  More thought needed there, but the idea is that we do a single scoping action to get the Request object targeted at a specific resource (mapped to context, filters and servlet).   We do this only once for a request cycle to get a mostly immutable (in terms of paths / target) request. Any dispatching to different resources will require the Request to be wrapped rather than mutated.

Once scoped, the server will call handle once per dispatch, which will use the info from the previous scope call to route the handling to the next handler/filter/servlet.   Note that we no longer handle from within the calling context of scope, because we never unscope a request.

So let's walk through the handling of a request in the new API.
 + We can't have a RewriteHandler as the request is mostly immutable. Rewrite will have to be done during Customization or scoping. Again issue of if this is a mutable phase of the request or on the meta-data before a immutable request is created.
 + `ContextHandlerCollection` will have picked the context during scoping, so in handle it simply needs to lookup the context and pass the request on to the `ContextHandler`
 + The `ContextHandler` will have set the contextPath during scope. During handle, before/after calling the nested handlers,  it needs to call some servlet-api listener events. These can't be called directly without depending on the servlet-api, but we can simply wrap servlet listeners to look like our own listeners.
 + It will be very difficult for the `SessionHandler` to do it's job independent of the servlet-api as the Session itself is an API class, as are the listeners and event handlers that need to be called on activation, passivation, invalidation, bind, unbind etc.   At least we have the concept of `SessionData` and `SessionDataStore` that are substantially independent of the servlet-api, so perhaps we can just add the store at this level, then wrap that in the servlet handler layer.  But the problem we'd have to move all the listener/even stuff to the wrapping layer.
 + At the `ServletHandler` level  we can finally wrap the jetty request/reponse with servlet-api request/response wrappers, then dispatch to filters and ultimately the servlet. What happens next depends on how the filters/servlets work:
   * For normal blocking servlet, the response will be generated and everything will be complete.  There is a small question of should the wrapper objects be recycled if we recycle the core request, but there is no guarantee the next request on a connection will go to the same context, and thus might end up at a different version of the servlet spec.  Probably need to review all recycling. 
   * For a `RequestDispatcher` to the same context, the ServletRequest/ServletResponse can be directly wrapped with new servlet-api wrappers and dispatch directly back to the `ServletHandler`.
   * For a `RequestDispatcher` to a different context the ServletRequest/ServletResponse will need to be wrapped to look like core request/response and dispatched to the new `ContextHandler`. New session data may be added to the wrapper and then ultimately new servlet-api wrappers added.  This wont be very efficient, but I don't care much for cross context dispatch. 
   * For an async servlet, when it is dispatched back to the same servlet, we currently run the request through all the handlers again.  But perhaps we can now dispatch directly to the ServletHandler, but then how does that relate to non-servlet async dispatches?   Currently async dispatch/completion is done via the servlet-api AsyncContext, so we'll need a jetty equivalent...  `AsyncContextState` is a wrapper anyway, so that is probably simple.
   * For an async dispatch to a different servlet in the same context, it will need to be wrapped like for a `RequestDispatcher` to a servlet in the same context
   * For an async dispatch to a different servlet in a different context, it will need to be wrapped like for a `RequestDispatcher` to a servlet in a different context and dispatched back to the `ContextHandler`

So it looks at least plausible that we can do servlet 6.0 with a servlet-api independent core.

BUT 

How would we then run a context that was servlet 5.0 in the same server?   Several options:
1. Implement it the same way, without OWI. It will not pass the TCK for 5.0, but many/most apps will work.
2. From the `ContextHandler` onwards revert to jetty-10 handlers... although I'm not sure that will work for async.
3. Use jetty-nested approach 


Final Point for this comment....

What should the core request/response API look like?   We already have too many different layers of abstraction (see h3 overview in #6765), so we don't want to add any more.   We also don't want a fat interface like the current request.   Thus I think we want to be close to something like one of our existing layers - or perhaps we look at the layer that is developing in jetty-nested https://github.com/eclipse/jetty.project/blob/7b1ee5bb1bd12ff9ca16524d0bde25fc5dd56845/jetty-nested/jetty-nested-impl/src/main/java/org/eclipse/jetty/nested/NestedRequestResponse.java#L21 
Better yet we come up with an abstraction that works for our core request/response that is also perfect for h2/h3 and jetty-nested.

**Comment by gregw** [comment]
Another important issue is going to be naming.     Currently we have modules like `jetty-servlet`, `jetty-annotation`, `jetty-webapp` that are all implicitly versioned against the servlet-api by the version of jetty.

If we go the jetty-nested approach, we can keep this as we end up just saying that a context is a jetty-10, jetty-11 or jetty-12 context and the classloader has different versions of each module within each context.

However, if we go for the agnostic jetty request/handler API, then we will need to distinguish matched sets of modules and classes.   To distinguish the names we could:

- use jetty version:   `org.eclipse.jetty12.servlet.ServletHandler`, but that doesn't really work for existing jetty 10, 11 releases.
- use servlet version extension `org.eclipse.jetty.servlet6.ServletHandler`, but then that doesn't match that well with other modules like `org.eclipse.jetty.webapp6.WebAppContext`
- use servlet version as a package scope: `org.eclipse.jetty.servlet6.servlet.ServletHandler` and `org.eclipse.jetty.servlet6.webapp.WebAppContext`
- use ee version as a package scope:   `org.eclipse.jetty.ee8.servlet.ServletHandler` and `org.eclipse.jetty.ee8.webapp.WebAppContext`

Currently I see a need for api versions in the one server for:
 + EE8 + Servlet 4.0 (javax)
 + EE9 + Servlet 5.0 (jakarta with deprecated)
 + EE? + Servlet 6.0 (jakarta)

**Comment by janbartel** [comment]
> * use ee version as a package scope:   `org.eclipse.jetty.ee8.servlet.ServletHandler` and `org.eclipse.jetty.ee8.webapp.WebAppContext`

If we wind up going this route, IMHO this is the best option.

**Comment by gregw** [comment]
@joakime if you want to make the case that we should get rid of `org.eclipse.jetty.util.Resource` and just use `Path` instead... then now is the time to make that case!

**Comment by gregw** [comment]
Below is a thought bubble of what a core Request/Response could look like.

This is orthogonal to any handling of the request/response so there are no methods like startAsync etc. as they are all something a handling layer might wrap around this.  This idea is that a connector/connection can provide implementations of these instead of talking to HttpChannel/HttpTransport.     These requests would then be routed through handlers and more semantics layered on top with wrappers and/or attributes.

```java
public interface HttpRequest extends Attributes
{
    String getId();
    Connection getConnection();
    String getScheme();
    String getMethod();
    HttpURI getURI();
    setContext(Context context);
    Context getContext();
    HttpFields.Immutable getHttpFields();
    long getContentLength();
    boolean isReady(Runnable onReady);
    Content read() throws IOException;
    void onTrailers(Consumer<HttpFields> onTrailers);
    void onComplete(Callback onComplete);

    interface Connection extends Attributes
    {
        String getId();
        String getProtocol();
        boolean isSecure();
        SocketAddress getRemote();
        SocketAddress getLocal();
        void onClose(Callback onClose);
    }

    interface Context extends Attributes
    {
        String getContextPath();
        ClassLoader getClassLoader();
        Path getResourceBase();
        Path getResource(String pathInContext);
    }

    interface Content
    {
        ByteBuffer getByteBuffer();
        void release();
    }
}

interface HttpResponse
{
    int getCode();
    void setCode(int code);
    HttpFields.Mutable getHttpFields();
    HttpFields.Mutable getTrailers();
    boolean isReady(Runnable isReady);
    int write(ByteBuffer content, boolean last) throws IOException;

    void onCommit(Runnable onCommit);
}
```

IO interceptors (eg gzip) could either be done with an explicit interceptor API or by just wrapping request/response as these are now simple enough.
rewrite can also be done with wrapping, although wrapping HttpFields needs some thought.

EDIT:
Actually, we probably don't need the Context stuff on the Connector level stuff.

Then I'm thinking that the Handler interface should just always be async, so we don't need to scope:
```java
interface HttpHandler
{
    boolean handle(HttpRequest request, HttpResponse response);
}
```
If true is returned, then we know something will handle the request and generate the response... perhaps not yet, but eventually.

**Comment by gregw** [comment]
My ideas have progressed a lot in the last few days.  Here is my current thinking about API contracts:
```java
// The following interfaces represent the contract between connection and HTTP handling,

/** The Channel interface here just represents the methods of the HttpChannel
 * that are of interest to the connection/protocol layer.
 * Note how Runnables are returned to indicate that further work is needed. These 
 * can be given to an ExecutionStrategy instead of calling known methods like HttpChannel.handle().
 */
interface HttpChannel
{
    HttpChannel newHttpChannel(HttpTransport transport);
    HttpTransport getTransport();
    Runnable onRequest(Stream stream);
    Runnable onRequestComplete(HttpFields onTrailers);
    Runnable onTransportComplete(Throwable failure);
}

/**
 * The existing HttpTransport interface has been augmented with more metadata
 * about the Connection (rather than a direct dependence on the Connection class).
 * However, some methods have been spun out into the new Stream interface that
 * more correctly relates to the multiple request cycles a transport may be used for.
 */
interface HttpTransport
{
    String getId();
    String getProtocol();
    boolean isSecure();
    SocketAddress getRemote();
    SocketAddress getLocal();

    void upgrade(org.eclipse.jetty.io.Connection connection);

    void complete(Throwable failure);
    boolean isComplete();
    void whenComplete(BiConsumer<HttpTransport, Throwable> onComplete);
}

/**
 * This is a new API that has been factored out of the HttpTransport API.
 * It represents the calls the Channel and above) make on the Transport for a
 * single request/response cycle.   The Stream (perhaps not best nam) is itself a
 * call back that is used to indicate when the request cycle is complete (rather than
 * returning from a Handler)
 */
interface Stream extends Callback
{
    MetaData.Request getMetaData();
    Content read();
    void needContent(Supplier<Runnable> onContentAvailable);

    void send(MetaData.Response response, Content content, Callback callback);

    boolean isPushSupported();
    void push(MetaData.Request request);

    boolean isComplete();
    void whenComplete(BiConsumer<Stream, Throwable> onComplete);
}

/**
 * The Content abstract is based on what is already used in several places.
 * It allows EOF and Error flows to be unified with content data. This allows
 * the semantics of multiple methods like flush, close, onError, etc. to be
 * included in the read/write APIs.
 */
interface Content
{
    ByteBuffer getByteBuffer();
    void release();
    boolean isLast();

    interface Error extends Content
    {
        Throwable getReason();
    }
}

// The following interfaces are for the contract between the server and handlers

/**
 * The handler API is now asynchronous. If it returns true, then some handler has taken
 * responsibility for calling {@link HttpRequest#succeeded()} or {@link HttpRequest#failed(Throwable)}
 */
interface Handler
{
    boolean handle(HttpRequest request, HttpResponse response);
}

/**
 * Request is the absolute minimum to efficiently communicate a request.
 * At this level, there is no concept of context or scoping, so that is a
 * matter for higher level handlers and perhaps wrapping of these request/responses.
 */
interface HttpRequest extends Attributes, Callback
{
    String getId();
    HttpTransport getTransport();
    MetaData.Request getMetaData();
    Content read();
    void needContent(Runnable onContentAvailable);
    void onTrailers(Consumer<HttpFields> onTrailers);
    void whenComplete(BiConsumer<HttpRequest, Throwable> onComplete);
}

/**
 * Response is the absolute minimum to efficiently communicate a request.
 */
interface HttpResponse
{
    int getCode();
    void setCode(int code);
    HttpFields.Mutable getHttpFields();
    HttpFields.Mutable getTrailers();
    void write(ByteBuffer content, boolean last, Callback callback);
    void push(MetaData.Request request);
    void whenCommit(BiConsumer<HttpRequest, HttpResponse> onCommit);
    boolean isCommitted();
    void reset();
}
```

@lachlan-roberts how does this match up semantics with your nested Request/Response?

**Comment by gregw** [comment]
Here is how the API above could work 
![diagram-18182388981118054928](https://user-images.githubusercontent.com/70829/137565426-50ce6ce9-4b9f-4462-94d7-eb6a44414472.png)

**Comment by gregw** [comment]
@janbartel Note that the API's etc. I've outlined above are now below the level of scoping and dealing with servlet container concerns etc.   If we can convince the likes of @sbordet that something like the above is the way to go for the contract with the protocol layer, then we need to start focusing on how such request/responses can be wrapped to provide contexts, scoping, sessions, etc.
Note also that this is well below the concepts @lorban introduced in HttpInput, as there is no input/output stream in these APIs.... but hopefully APIs that do need an InputStream will be able to leverage our existing HttpInput work reimplemented on top of this API.     @lachlan-roberts also look at this with your jetty-nested eyes.... could you take these request/response objects and feed them back in below another HttpChannel?

**Comment by joakime** [comment]
The ContextHandler with 2 ClassLoaders makes sense.

The Context Classloader Layer should be the WebApp itself.

The API Classloader Layer should be "Jakarta EE ##" (Servlet, WebSocket, JSP, EL, CDI that all works together)
_(I kinda think of this "API Layer" as a "WebApp Specific Server/System Classloader")_

Couldn't this "API Layer" be a Handler.Wrapper as well? (`ScopedClassLoaderHandlerWrapper`? `ScopedApiHandlerWrapper`? )
This layer is likely to also contain extra things like EE specific Database jars, and what about JNDI? Is that on this layer?

We might want to break down the code in git like this ...

``` 
     /jakarta-ee/
                 8/
                   servlet-4/
                   websocket-1.1/
                   jsp-2.4/
                 9/
                   servlet-5/
                   websocket-2/
                   jsp-2.6/
                 10/
                   servlet-6/
                   websocket-3/
```

The module system will be interesting in this reality.
As `--module=websocket` is vague now.
Would `--module=javax.websocket` make sense? 
or `--module=websocket-ee8, websocket-ee9` or `--module=websocket-1.1, websocket-2.0`?

Our naming has been traditionally `--module=<technology>`.
Now we need to specify EE support `--module=ee-<ver>` at a minimum.
And then specific technology within that EE level `--module=ee-<ver>-<technology>`.
Do we want aliases or composite modules now? eg: `--module=annotations` which enables ee specific versions based on the `--module=ee-<ver>` enabled as well?

Could we have the list of modules and the API layer be smart based on the webapp being deployed?
`start.jar --add-modules-based-on-webapp=mycorp.war` ? (I imagine an asm based analysis could work easily here, with a static mapping file in our jars with `<classname>=<module>` that point to the module required)
This would also eliminate the need to write all of the `enable.<feature>` configuration stuff we have in current Jetty (for things like websocket).

We could even have some kind of API classloader configuration in the `${jetty.base}/webapps/mycorp.xml` that says what the API layer should look like for that specific webapp.

**Comment by joakime** [comment]
I'd like to start a "New in Jetty 12" page in the jetty-documentation that we can add concepts we've changed from Jetty 11.
Would make a good announcement / blog topic too.

**Comment by gregw** [comment]
I'm closing this as we are now doing real jetty12 development and musings are best done in the PRs
