### ISSUE TITLE
Need test infrastructure to enable testing of all jetty modules

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6373]
Currently we have a few tests that exercise the distro in` tests/test-distribution` but I think we need to either augment it, or create a separate project whereby a CI job could just endlessly enable and test each of our jetty modules. That would be the only way to check that a module is actually working as expected. We would need to check:
* syntax of `.xml `files and `.mod` files 
* that each module can actually be enabled
* setting of each property in a `.ini` file
* function of properties set in a `.ini` file

**Comment by joakime** [comment]
Is it just testing to see if the module can be enabled?
I would expect that we should also start the jetty.base too, right?

If so, what do we do with those configurations that require other infrastructure? (gcloud, gcloud-datastore, hazelcast, hawtio, fcgi, infinispan, jminix, jamon, jolokia, mongo, unixsocket, flight-recorder, etc...)
Most can be done with some effort and creative use of docker, but what about things like gcloud-datastore? which would need to be run on gcloud?

**Comment by janbartel** [comment]
Well, it should be testing that the module can be enabled, and then that the module actually works.

**Comment by olamy** [comment]
with the help of this https://github.com/eclipse/jetty.project/pull/6516 we can reuse that for different session storage.
but other modules are a bit different.

**Comment by olamy** [comment]
@janbartel what should be the target for this 10.0.x or even 9.4.x?

**Comment by joakime** [comment]
Perhaps something like what was done for testing the logging modules?

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/LoggingOptionsTests.java

**Comment by olamy** [comment]
Not sure as some mod have very specific needs. In the case of sessions we might need something abstract and different external resources start (jdbc, infinispan, memcached etc..)
