### ISSUE TITLE
Always check XML `Set` elements with `property` attribute

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6375]
**Target Jetty version(s)**

>= 10.0.x

**Enhancement Description**

Since jetty-10, the XML `Set` element could have a property attribute that only does the set if the property is set.  The problem with this is that the code may change and we do not detect that the XML is now wrong unless somebody attempts to set that property.   The `XmlConfiguration` class should be change to always check that at least one setter exists for a `Set` element with a `property` attribute.

**Comment by janbartel** [comment]
@gregw also, the documentation needs updating for the `Set` element, because it doesn't mention the `property` attribute at all. See https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-xml-syntax-set
