### ISSUE TITLE
Make jetty-10/11 work against slf4j-api 1.7.30 in addition to 2.0.0

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6385]
**jetty10/11**

Currently, jetty builds against, and distributes slf4j-api version 2.0.0-alpha1. However, we have some users who need to run against the same slf4j version as older releases, which was slf4j-api 1.7.30.

We should modify the jetty-slf4j-logging implementation to also work against 1.7.30, build against 1.7.30, but distribute 2.0.0-alpha1 with jetty.home.

**Comment by janbartel** [comment]
@joakime comments?

**Comment by olamy** [comment]
@joakime our `org.slf4j.spi.SLF4JServiceProvider` implementation in a separate module?

**Comment by joakime** [comment]
I think this is doable on the jetty-slf4j-logging side.
Have to be careful with the jpms testing stuff though.

**Comment by sbordet** [comment]
Do we still need to support this?

**Comment by joakime** [comment]
No, just downgrading your slf4j-api version that you use with jetty is sufficient.
There's no code changes necessary.
