### ISSUE TITLE
Review osgi manifests within Jetty 10

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6394]
**Jetty version**
10.0.5

**Description**
During the work for the slf4j osgi manifest on PR #6381 it was noticed that some other osgi manifest entries are a bit out of date and should be reviewed.

https://github.com/eclipse/jetty.project/blob/6dea0251c2a4948578092db1c81e0d33b06f95b9/jetty-annotations/pom.xml#L33

We are at ASM 9 on Jetty 10

https://github.com/eclipse/jetty.project/blob/6dea0251c2a4948578092db1c81e0d33b06f95b9/jetty-osgi/test-jetty-osgi-context/pom.xml#L78-L79

and

https://github.com/eclipse/jetty.project/blob/6dea0251c2a4948578092db1c81e0d33b06f95b9/jetty-osgi/test-jetty-osgi-server/pom.xml#L70-L71

We are at Javax Servlet 4 on Jetty 10

**Comment by janbartel** [comment]
The jetty-annotations pom could be updated to a minimum of asm 9, but the other 2 are test webapps so ok to leave at a minimum of 3.1 but could be updated to a max version of 5.
