### ISSUE TITLE
Jetty pre-emptive proxy authentication

### ISSUE THREAD

**Issue by tejas-ambekar** [eclipse/jetty.project#6405]
**Jetty version - 9.4.18**

**Java version - 8**

I am trying to do pre-emptive proxy authentication with below code. However, I am getting 407 error code in return.

``` java
AuthenticationStore authStore = client.getAuthenticationStore();
if(proxyResource != null){
					ProxyConfiguration proxyConfig = client.getProxyConfiguration();
					HttpProxy proxy = new HttpProxy(proxyResource.getProxyHost(), Integer.valueOf(proxyResource.getProxyPort()));

					if(proxyConfig == null) {
						proxyConfig = new ProxyConfiguration();

					}
					// add the new proxy to the list of proxies already registered
					proxyConfig.getProxies().add(proxy);
				}
URI proxyURI = new URI("http://"+proxyResource.getProxyHost()+":"+proxyResource.getProxyPort());
authStore.addAuthenticationResult(new BasicAuthentication.BasicResult(proxyURI, "user", "password"));

client.start();
```

Am I missing something here? I am using HttpClient and HttpProxy implementation?
Can someone please help with this?

**Comment by joakime** [comment]
First, and most important: Upgrade your version of Jetty.

It is old, and doesn't contain many fixes for your scenario (along with [various security fixes](https://www.eclipse.org/jetty/security_reports.php), and [other bugs](https://github.com/eclipse/jetty.project/blob/jetty-9.4.42.v20210604/VERSION.txt))

If you have to stick with Java 8, then use [Jetty 9.4.42.v20210604](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.42.v20210604).  
Otherwise, if you are using Java 11+, then use Jetty 10.0.5. (even more improvements!)

Lastly, when you are upgraded, use `AuthenticationStore.addAuthentication(BasicAuthentication)`, _not_ `AuthenticationResult`.

See: https://www.eclipse.org/jetty/documentation/jetty-9/index.html#http-client-proxy-authentication

**Comment by sbordet** [comment]
Please look at the Jetty 10.0.x documentation, which is valid also for 9.4.x:
https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-client-http-proxy-authentication

**Comment by tejas-ambekar** [comment]
Thanks @joakime @sbordet for the quick response.

I have tried with `AuthenticationStore.addAuthentication(BasicAuthentication)` as well. I am seeing the same behavior i.e. 407 code.
Is there something else I can check? perhaps on the proxy server side?
Thanks in advance..

**Comment by sbordet** [comment]
@tejas-ambekar please enable DEBUG logging on the client.
Could just be that you put in the wrong password.

Alternatively, look at the proxy logs: it should tell you why it sent back a 407.

**Comment by tejas-ambekar** [comment]
Thanks @sbordet 
Will try the things you suggested.

One more thing, as per my understanding of the docs, the httpClient will take care of the 407 error code? (As long as above code is there)
I do not have to handle that i.e. making another request with auth header and credentials (via own code)..Is this understanding correct?
or am I missing something here?

Thanks in advance..

**Comment by firoj07** [comment]
IETF BCP 79
BCP
5378 3978
4748 RACc NON

रवि, 13 जून 2021, 21:53 को tejas-ambekar ***@***.***> ने लिखा:

**Comment by sbordet** [comment]
> One more thing, as per my understanding of the docs, the httpClient will take care of the 407 error code?

Read carefully the documentation.

`HttpClient`, upon receiving a 407, will continue the conversation with the server if there is an `Authentication` available.
If not, it will yield the 407 to the application, as there is nothing more that it can do to proceed with the conversation.

**Comment by tejas-ambekar** [comment]
Thanks a lot for your help @sbordet

**Comment by joakime** [comment]
Can we close this question?

**Comment by janbartel** [comment]
I am assuming that due to lack of further comment by the OP that this issue can be closed.
