### ISSUE TITLE
Ensure Jetty IO uses SocketAddress instead of InetSocketAddress

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6410]
**Target Jetty version(s)**
10.0.x

**Enhancement Description**
In preparation for support of Unix Domain Sockets, introduced in Java 16 and handled in #6043, many Jetty I/O classes should be changed to return/use `SocketAddress` instead of `InetSocketAddress`.

As this is a quite large change that is better done separately.

**Comment by joakime** [comment]
This is related to Issue #2134
