### ISSUE TITLE
Bad and/or missing Require-Capability for osgi.serviceloader

### ISSUE THREAD

**Issue by flaviodonze** [eclipse/jetty.project#6418]
**Jetty version(s)**
Jetty Version 10.0.5

**Java version/vendor** `(use: java -version)`
jdk16.0.1

**OS type/version**
Windows 10

**Description**
I'm trying to migrate our embedded jetty 9.4.x to jetty 10.0.5. I'm having a couple of OSGi and dependency issues. <br/>
To isolate the problem I created a simple OSGi Launch in Eclipse, having a couple bundles:

	<setEntry value="jakarta.servlet-api@default:default"/>
	<setEntry value="org.apache.aries.spifly.dynamic.bundle@default:default"/>
	<setEntry value="org.apache.felix.gogo.runtime@default:default"/>
	<setEntry value="org.apache.felix.gogo.shell@default:default"/>
	<setEntry value="org.eclipse.equinox.console@default:default"/>
	<setEntry value="org.eclipse.jetty.http*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.io*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.security*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.server*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.servlet*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.util*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.webapp*10.0.5@default:default"/>
	<setEntry value="org.eclipse.jetty.xml*10.0.5@default:default"/>
	<setEntry value="org.eclipse.osgi.services@default:default"/>
	<setEntry value="org.eclipse.osgi.util@default:default"/>
	<setEntry value="org.eclipse.osgi@-1:true"/>
	<setEntry value="org.objectweb.asm.commons@default:default"/>
	<setEntry value="org.objectweb.asm.tree.analysis@default:default"/>
	<setEntry value="org.objectweb.asm.tree@default:default"/>
	<setEntry value="org.objectweb.asm.util@default:default"/>
	<setEntry value="org.objectweb.asm@default:default"/>
	<setEntry value="slf4j.api*2.0.0.alpha1@default:default"/>

If I launch this settings I get the following validation error:
Require-Capability: osgi.serviceloader; filter:=“(osgi.serviceloader=org.eclipse.jetty.webapp.Configuration)”
PrintScreen: https://stackoverflow.com/questions/68004496/jetty-10-require-capability-osgi-serviceloader-filter-osgi-serviceloader-o

**Comment by joakime** [comment]
You don't seem to be using any component / bundle that has a `META-INF/services/org.eclipse.jetty.webapp.Configuration` service entry.

```
[jetty-10.0.x]$ find . -name "org.eclipse.jetty.webapp.Configuration"
./jetty-plus/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-cdi/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-osgi/jetty-osgi-boot/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-maven-plugin/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-ant/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-webapp/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-quickstart/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-websocket/websocket-javax-server/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-websocket/websocket-jetty-client/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-websocket/websocket-jetty-server/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
./jetty-annotations/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
```

If you add such an entry, does the error/warning go away? (eg: add `jetty-annotations-<ver>.jar`)

**Comment by flaviodonze** [comment]
That is the strange thing, actually `<setEntry value="org.eclipse.jetty.webapp*10.0.5@default:default"/>` contains the entry:
`./jetty-webapp/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration`
But also `org.eclipse.jetty.webapp` causes the validation exception.

**Comment by janbartel** [comment]
I've been able to reproduce the problem, investigating further.

**Comment by janbartel** [comment]
Yup, that there is a genuine bug. Fixing, see PR #6422
