### ISSUE TITLE
Document how to take a Server dump via JMX

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#642]
We should have a section in the documentation that shows how to take a `Server` dump via JMX.

Perhaps it would be good to replace the section about JConsole with a similar based on JMC.

**Comment by gregw** [comment]
We probably need to have a section of all the debugging techniques - dump on start, dump on exit, jmx dump, thread dumps, logging etc.

**Comment by WalkerWatch** [comment]
@sbordet @gregw We have some of the information on this already documented, albeit in likely [the wrong chapter.](https://www.eclipse.org/jetty/documentation/current/jetty-dump-tool.html). I moved it as part of #576 (in regards to #549) as it was not correctly converted to asciidoc originally.

**Comment by gregw** [comment]
LGTM
