### ISSUE TITLE
manage (remove) response headers easily

### ISSUE THREAD

**Issue by r-jo** [eclipse/jetty.project#6427]
**Target Jetty version(s)**
as many as possible :)

**Enhancement Description**

Hi!
I use embedded jetty 9.4.35
I was wondering how to remove response headers like date or server via API... I found a solution only for configuration files and I came up with an own somewhat cumbersome solution that seems to work.

Still, I would love to have a feature like server.setSendDateHeader(false) and server.setSendServerVersion(false).
I guess (no expert here) there is normally one connector with one connection factory... if not, these methods could throw or simply be skipped with reason logged.

For now I came up with following. Also, I wonder if it is OK and if it is the simplest way to achieve it via API. If it is, something like this could be officialy used.

private static void removeDateAndServerResponseHeaders(Server server) {
        HttpConnectionFactory hcf = (HttpConnectionFactory) server.getConnectors()[0].getConnectionFactories().iterator().next();
        hcf.getHttpConfiguration().setSendDateHeader(false);
        hcf.getHttpConfiguration().setSendServerVersion(false);
    }

Thanks a lot for your time!

**Comment by joakime** [comment]
It would be easier to set the HttpConfiguration when you create the ServerConnector instead of iterating them after the fact, pulling out the ConnectionFactory, then pulling out the HttpConfiguration, to then configure it.

Example from https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java

Setting the `HttpConfiguration`

https://github.com/eclipse/jetty.project/blob/265886543ff197b1d6a60ec994162bd6cbf0a06d/examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java#L93-L102

Then create and add the `ServerConnector`

https://github.com/eclipse/jetty.project/blob/265886543ff197b1d6a60ec994162bd6cbf0a06d/examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java#L116-L120

**Comment by joakime** [comment]
Note that your code also has a bug in that it doesn't take in consideration ServerConnectors with multiple ConnectionFactory instances (which is common for https and http/2).

This fixes your bug.

``` java
server.getContainedBeans(HttpConfiguration.class).forEach((httpConfiguration) -> {
    httpConfiguration.setSendServerVersion(false);
    httpConfiguration.setSendDateHeader(false);
});
```

**Comment by r-jo** [comment]
Hi!
Thanks a lot for your reply! Now I use your suggested iterating solution.

Before I commented, I found something like you added in your first comment (the direct method). It seemed a bit frightening and overkill to me who is not really familiar with jetty (in Google App Engine now I have to do it myself).

Until now, I did not create HttpConfiguration or ServerConnector directly, I used the code below where I guess along the way defaults of these two configurations are created. Is it bad practice, would you recommend to create everything myself?

        WebAppContext webAppContext = new WebAppContext();
        URL webAppDir = Thread.currentThread().getContextClassLoader().getResource("files");
        webAppContext.setResourceBase(webAppDir.toURI().toString());
        //adding servlets...
        int port = Integer.parseInt(System.getenv().getOrDefault("PORT", "8080"));
        Server server = new Server(port);
        server.setHandler(webAppContext);
        removeDateAndServerResponseHeaders(server);
        server.start();
        server.join();

Your second solution (indirect, ex post way) seems much easier and professional, I do not think we need api enhancement the way I suggested. It is easy enough to grab httpConfiguration(s).

However, if I followed your first solution (direct, ex ante way) it may be valuable (for amateurs like me) to have a static "constructor" for such classes like HttpConfiguration. Like HttpConfiguration httpConfig = HttpConfiguration.newDefault(); which would set default values like in your first comment or like they are set implicitly if someone does like I did in my above code.

Thanks again!

**Comment by r-jo** [comment]
Ok I checked the source code and there seem to be default values so no need for static newDefault() (then after HttpConfiguration httpConfig = new HttpConfiguration() I guess we do not need to set some of these values again).

```
public class HttpConfiguration
        {
            public static final String SERVER_VERSION = "Jetty(" + Jetty.VERSION + ")";

            private List<Customizer> _customizers=new CopyOnWriteArrayList<>();
            private int _outputBufferSize=32*1024;
            private int _outputAggregationSize=_outputBufferSize/4;
            private int _requestHeaderSize=8*1024;
            private int _responseHeaderSize=8*1024;
            private int _headerCacheSize=512;
            private int _securePort;
            private String _secureScheme = HttpScheme.HTTPS.asString();
            private boolean _sendServerVersion = true;
            private boolean _sendXPoweredBy = false;
            private boolean _sendDateHeader = true;
            private boolean _delayDispatchUntilContent = false;
```

**Comment by joakime** [comment]
If you are using GAE you are stuck, and this effort is wasted.

You don't have access to the ServerConnector on GAE (it's protected, your code is not allowed to modify it when on the GAE platform).
The GAE Jetty ServerConnector will specifically force on the server version true, and disable the date header with false.
And then the requests and responses actually go through the Google Front End (GFE) which also forces various googly behaviors outside of your running GAE instance (like changing the server version text on responses).

**Comment by joakime** [comment]
Look around github, the majority of developers using Jetty will use the ServerConnector + HttpConfiguration, not the shorthand port in the Server constructor.

**Comment by r-jo** [comment]
Thanks!
I will check it out and I will probably move to the straightforward ServerConnector + HttpConfiguration solution. I need some more time to read about.

GAE has changed from java8. I use java11 with app engine standard and I create a so called fat jar (or uber jar) with embedded jetty. This runs beautifully on localhost and then I practically upload the fat jar and an app.yaml configuration file and it will run on their servers as it is. I guess I have complete "power" over jetty now.

The only thing is Google Frontend... they do add googly stuff before and after and they switch response headers like the server one from jettyxyz to "Google Frontend". Even if there is no response header leaving jetty, they add 5 extra... I have just started a conversation about it because they are also billed as outgoing bandwidth...

I hope it will be possible in the future to send less response headers and then it is good that I can make jetty skip them. The Date header seems to be practically a MUST according to http/1.1 specs but at least the server header would be great to skip.

Also, I wanted to test what Google Frontend does once I send zero response headers, so not a waste of effort :) It is also great that I am forced to learn more about jetty :)

Thanks for your effort!
I guess this can be closed, then. Who is supposed to close these threads? I am not really active in forums and I dont know the protocol :)

**Comment by r-jo** [comment]
Ok I close it.

So no feature enhancement is needed. Best define your own http configuration and server connector and initiate server this way. Then it is possible to use httpConfiguaration.setSendServerVersion(false) and so on. And if you want to access it afterwards, use something like:

server.getContainedBeans(HttpConfiguration.class).forEach((httpConfiguration) -> {
    httpConfiguration.setSendServerVersion(false);
    httpConfiguration.setSendDateHeader(false);
});

**Comment by sbordet** [comment]
@szasamasa you don't need to iterate over the `HttpConfiguration`, unless you don't control them.

But if you control their creation, just create one instance and pass it to all `ConnectionFactory` instances:

```java
HttpConfiguration httpConfig = new HttpConfiguration();
httpConfig.setSendServerVersion(false);
...

Server server = new Server();

HttpConnectionFactory http11 = new HttpConnectionFactory(httpConfig);
HTTP2CServerConnectionFactory h2c = new HTTP2CServerConnectionFactory(httpConfig);

ServerConnector connector = new ServerConnector(server, 1, 1, http11, h2c);
```

**Comment by r-jo** [comment]
Hey!
Thanks for your input! You are both very kind.

I re-coded my class according to your suggestions. It seems to be working. Now only the Date response header leaves jetty, not server. In addition, now I can change any httpConfiguration or serverConnector parameters in a straightforward way in the future if I have to. So: "this is the way" :)

I share the current state of my code for future people who might have had similar questions.
Feel free to criticise anything! (in the future I will still iterate on the code, read more jetty documentation etc.)


public class StartWebServer {
    private static final Logger logger = Logger.getLogger(StartWebServer.class.getName());
    static {
        logger.setLevel(Level.INFO);
    }

    public static void main(String[] args) throws Exception {
        logger.log(Level.INFO, "max heap memory: {0}b", Runtime.getRuntime().maxMemory());

        Server server = new Server();
        WebAppContext webAppContext = createWebAppContext();
        server.setHandler(webAppContext);
        ServerConnector serverConnector = createServerConnector(server);
        server.addConnector(serverConnector);
        server.start();
        server.join();
    }

    private static WebAppContext createWebAppContext() throws URISyntaxException {
        WebAppContext webAppContext = new WebAppContext();
        setResourcePath(webAppContext);
        addFilters(webAppContext);
        addServletMappings(webAppContext);

        return webAppContext;
    }

    private static ServerConnector createServerConnector(Server server) {
        HttpConfiguration httpConfiguration = new HttpConfiguration();
        httpConfiguration.setSendServerVersion(false);
        ServerConnector serverConnector = new ServerConnector(server, new HttpConnectionFactory(httpConfiguration));
        int port = Integer.parseInt(System.getenv().getOrDefault("PORT", "8080"));
        serverConnector.setPort(port);

        return serverConnector;
    }

    private static void setResourcePath(WebAppContext webAppContext) throws URISyntaxException {
        URL webAppDir = Thread.currentThread().getContextClassLoader().getResource("files");
        //todo if webAppDir null, try some other method to get it...
        //noinspection ConstantConditions
        webAppContext.setResourceBase(webAppDir.toURI().toString());
    }

    private static void addFilters(WebAppContext webAppContext) {
        webAppContext.addFilter(ValidRequestHeader.class, "/*", EnumSet.of(REQUEST));
    }

    private static void addServletMappings(WebAppContext webAppContext) {
        webAppContext.addServlet(Index.class, "/");
        //...add other servlet mappings

        logger.log(Level.INFO, "servlet mappings: {0}", webAppContext.getServletHandler().getServletMappings());
    }
}
