### ISSUE TITLE
Flakey test org.eclipse.jetty.websocket.jakarta.tests.server.SessionTest.testRequestUriEndpointBasic

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6437]
**jetty-11.0.x*

Failed in jenkins 
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-11.0.x-6394-port/1/pipeline

**Comment by lachlan-roberts** [comment]
@janbartel do you have the log for this failure, or just the stacktrace? I can't load that page in jenkins and I cannot reproduce locally after running the test on repeat.

**Comment by janbartel** [comment]
No sorry, I don't have any other info - looks like when the PR got merged and the branch was deleted the CI runs were too.

**Comment by lachlan-roberts** [comment]
Closing as no info available on the failure and cannot reproduce.
Will re-open issue if the failure occurs again.
