### ISSUE TITLE
Modules for enabling logging

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#644]
should be able to do 

```
java -jar $JETTY_HOME/start.jar --add-to-start=slf4j-simple
```

**Comment by gregw** [comment]
I have added/updated modules for:
- logging
- slf4j-api
- slf4j-simple
- slf4j-log4j
- java-util-logging.mod
- log4j
- log4j-log4j2
- log4j2-api
- log4j2-core
- log4j2-slf4j

This is going to need a bit of explaining, good documentation and perhaps some renaming (slf4j to slf4j-logging?)

The `logging`, `slf4j-xxx` and `java-util-logging` all provide the logging capability, that means that they plug into the jetty logging mechanism and receive our logs.  The `log4j` (version 1.2) and `log4j2` modules do not provide logging capability, ie they do not directly plug into our logging and need to be adapted (or used independently).  Also the logging module is not exactly orthogonal - it configures the default jetty log to go to a file logger and also captures stderr/stdout.  It may need to be broken up.

So the following are all valid module combinations to enable logging:
- `--add-to-start=logging`
- `--add-to-start=java-util-logging`
- `--add-to-start=slf4j-simple`
- `--add-to-start=log4j-log4j2,log4j2-slf4j,slf4j-simple`
- `--add-to-start=slf4j-log4j,log4j`
- `--add-to-start=slf4j-log4j,log4j-log4j2,log4j2-core`

I think adding renaming to slf4j-simple-logging and slf4j-log4j-logging  might make it clearer which modules actually take jetty logs?  So this list would become:

- `--add-to-start=logging`
- `--add-to-start=java-util-logging`
- `--add-to-start=slf4j-simple-logging`
- `--add-to-start=log4j-log4j2,log4j2-slf4j,slf4j-simple-logging`
- `--add-to-start=slf4j-log4-loggingj,log4j`
- `--add-to-start=slf4j-log4j-logging,log4j-log4j2,log4j2-core`

The logging indicates where the jetty instrumentation enters the chain of loggers.

This has been a good test of the new 9.4.x alternate module mechanism as it tries to give good error messages about either missing modules or duplicate capabilities.   More testing needed!

Also I have updated the module file mechanism so we can copy template config files for log4j and log4j2 from `modules/log4j/log4j.properties` etc. This is better than having unused config files in the raw distro waiting for a module to be enabled.

@WalkerWatch Can you start thinking about documenting this.  Also a lot more testing would be beneficial.  Your thoughts on the -logging naming and other naming would be appreciated?  should log4j be renamed log4j12 ?

@joakime Can you add in a logback module - I think it will provide slf4j-api and log4j-api?  but I'm not sure.  Also it might need to be broken up into multiple modules? etc.

Anyway, consider this a work in progress

**Comment by jmcc0nn3ll** [comment]
Greg, I just ran across an issue with this in the demo-base on master with your --add-to-start changes

[demo-base]> java -jar ../start.jar --add-to-start=requestlog 

I only have a start.d directory and it ended up making a start.ini with the request log info in it.

**Comment by joakime** [comment]
This seems quite awkward as implemented.

And @WalkerWatch will be documenting a large chunk of what slf4j already has documented.

**Comment by joakime** [comment]
so, the following are mutually exclusive ...

 * if jul-to-slf4j don't install slf4j-jul
 * if jcl-to-slf4j don't install slf4j-jcl or commons-logging
 * if log4j-to-slf4j don't install slf4j-log4j or log4j

This is quite complicated for the module system.

This should be simplified a great deal ...

The output / appender / configuration side

 * logging-jetty (jetty's StdErrLog + etc/logging.xml capture of System.out & System.err)
 * logging-log4j (slf4j-api + log4j + resources/log4j.xml)
 * logging-logback (slf4j-api + logback-core + logback-classic + resources/logback.xml)
 * logging-jul (slf4j-api + slf4j-jdk14 + resources/logging.properties)

The capture side

 * logging-capture-jul (jul-to-slf4j + **(not)** logging-jul)
 * logging-capture-log4j (log4j-over-slf4j + **(not)** logging-log4j)
 * logging-capture-commons-logging (jcl-over-slf4j)

Optional behavior side

 * logging-centralized (deployment manager binding for forced server side logging)
 * requestlog-logback (using slf4j for requestlog)

Thinking about this more, our start.jar mechanism will have to be FAR MORE intelligent with its dependencies to ensure that another module doesn't pull in things like log4j or commons-logging on its own, otherwise this will result in a bad configuration.  

Lets hold off on this till Jetty 10 and the eventual mavenization of the start.jar libs

**Comment by joakime** [comment]
some cross-module concerns:

if `slf4j` is used, then the `gcloud-session.mod` should not download `commons-logging.jar` and use `jcl-slf4j.jar` instead.

if `infinispan.mod` is used, then the `jboss-logging.jar` will detect the presence of `log4j` and use it on some of those configurations.

**Comment by janbartel** [comment]
It would be good if we could work through any concerns in time for jetty-9.4 milestone release, as the new session support for memcached has a dependency on slf4j, and therefore is difficult to deploy easily without some sort of logging module support.

**Comment by joakime** [comment]
Other current examples:

* `hawtio` uses: `commons-logging`, and `slf4j` (older version), `slf4j-log4j12`, and `log4j` as well.
* `jamon` uses: `log4j` and manages it for its own reasons (so if `jamon` is used, `log4j` at the server side is forbidden)
* `jminix` uses: `commons-logging`
* `jolokia` uses: `java.util.logging` and expects to manage the root context & handlers itself (so if `jamon` is used, any `java.util.logging` option is forbidden on server side)

**Comment by joakime** [comment]
@janbartel this can be done, but would require introducing `aether` to start.jar to download and manage the maven dependencies (and graph) properly.

**Comment by joakime** [comment]
To review, we have the following requirements here ...

 * Need new logging modules for output / configuration [1 choice only]
 * Need new logging modules for event capture [0..n choices]
 * Need new logging for optional logging behavior (forced centralization & requestlog) [0..n choices, auto enable slf4j options if used, logging-jetty not allowed]
 * Need new start.jar behavior for knowledge about logging exclusions
 * Need new start.jar behavior for aether based dependency resolution
  * each jetty module should be treated in aether as an individual maven module
  * logging dependencies need reactor wide exclusions
  * jetty logging modules should be higher priority (closer to root) then all other jetty modules
 * jetty logging modules need better mutual exclusions concepts

**Comment by joakime** [comment]
Oh, and the existing `etc/jetty-logging.xml` which captures and redirects System.out and System.err to the rolling file output can *only* exist for the proposed `logging-jetty` module (should probably rename that xml to something more clear to its purpose)

**Comment by joakime** [comment]
@janbartel if you want a quick fix for Jetty 9.4, we can make it only support slf4j + logback and be done with it.   Leaving the more intelligent approach for Jetty 10.x

**Comment by gregw** [comment]
Hmmm i think you are over complicating this.  These are just some modules to download and configure the most common logging setups.  They are working well enough workout using extensive other modules. 

We already have other modules that are pulling in logging impls so we have po
tential for conflict. 

This setup allows those modules to just depend on the api they need and we can use other modules to provide the impl. There is already the split between collection (api) and handling (impl)

**Comment by gregw** [comment]
Note also that so long as we make modules depend only on apis then we can mix multiple logging mechanisms and use the bridges to unify then.  The modules I've written make this possible already. But i need to add commons logging as well to handle all the modules we currently have.

**Comment by gregw** [comment]
I agree that renaming is needed to make all these modules clear.  But now that the module system already has the capability of preventing most bad combinations.  Eg if you enable the existing logging module it provides the logging capability and will prevent other logging modules from being enabled with a reasonable error message. 

Hmm might need to move the capability provides from the api to the impl? 

Anyway we have most of the features needed and we are already past the point that we should help resolve logging conflicts.

**Comment by gregw** [comment]
@jmcc0n3ll will have a look at start problem.  I'll reopen the other issue for it.

**Comment by gregw** [comment]
@joakime back at a proper key board so i can respond more precisely to your points.    I think all your concerns are good ones, but I think what I've implemented actually mostly addresses them:

> following are mutually exclusive ...

Module system now handles mutually exclusive capabilities.    A modules can say it provides a capability (eg `logging`) and only a single module that provides that capability can be enabled.  If you try to enable another, then you get a clear error message saying what the capability is and what module already provides it and where it is enabled.

Similarly, if a module depends on a capability (eg slf4j-impl) and one is not yet enabled, then you get an error message telling you all the known modules that do provide that capability.

This mechanism was already implemented as it was needed for all the alternate session managers and data stores.

> The output / appender / configuration side
>  ...
> The capture side

The modules are already broken up in this fashion, although perhaps the naming could be clearer.  So for example `slf4j-api` is just the capture side and you have a choice of `slf4j-simple` or `slf4j-log4j` as the output/appender/configuration side of things.

This works the same for log4j2, but is a little harder for log4j (1.2) where the API is not separated from the impl.

> Optional behavior side

Again, this is already provided... but may need clearer names and more modules.     The `log4j-log4j2` API bridge is an example of an optional modules.      These just need to be added with the right dependencies on API and/or impls that are needed.

> Thinking about this more, our start.jar mechanism will have to be FAR MORE intelligent with its dependencies to ensure that another module doesn't pull in things like log4j or commons-logging on its own, otherwise this will result in a bad configuration.

I believe we already have the capability with the provides mechanism described above.   We just have to update the other modules to stop them pulling in logging jars themselves and instead make them depend on the logging APIs that they need.    The module mechanism will then tell them the available modules that will provide the impls that they need.

> Lets hold off on this till Jetty 10 and the eventual mavenization of the start.jar libs

I think we have to do this in 9.4 because we are already having issues with modules that conflict on logging mechanisms.

What think we should hold off for 10.x is the proper dependency mechanism.   Currently in 9.4.x you have to list all the dependencies in `[files]` clauses and there are no transient dependencies.... unless you deliberately exclude one (eg logging) and instead depend on a module that itself provides the jars needed via `[files]` clauses or their own transient dependencies.         We are already doing this, all that is really new is the ability to declare a provided feature by name and the fact that I've created some logging modules that can use this.

Note also, that using these modules is not compulsory in any way.  We should definitely document how you can provide your own logging setup with it's own jars etc.  This is best bundled up in your own module and it should declare that it `[provides]logging` so that it prevents a custom logging setup and one of the provided ones being enabled together.

**Comment by gregw** [comment]
I'm wondering if it would be simpler to factor out the jetty logging mechanism from the modules that provide logging implementations.

So I could remove the `[provides]logging` from all the modules defined so far, and none of them would set the `org.eclipse.jetty.util.log.class` system property to force jetty to use a particular implementation.  Thus these new modules defines will simple fetch jars for the classpath and advertise which impl and apis they provide.

I could then define `jetty-logging`, `jetty-jul` and `jetty-slf4j` modules that actually picks which of these are used by jetty for logging.    I think this makes module sequences read a lot better:

`--add-to-start=jetty-slf4j,sl4j-log4j,log4j-log4j2,log4j2-core`  describes the path of logging from jetty to slf4j, to log4j (v1.2), to log4j2 which finally uses its core logging to do the actual logging.

It is more modules, but avoids the confusion of some logging modules (slf4j and jul) that plug into jetty logging automagically vs other modules (log4j, jcl) that can be on the classpath but are not used by jetty unless there is an adaptor.

**Comment by gregw** [comment]
I've fleshed out these modules and implemented some of my thought bubbles above.     To demonstrate how the module system is protecting us from making a big mess of things I have recorded a [video](https://vimeo.com/171054415) to show the mechanism in action.

I think it is a lot clearer moving the jetty-xxx modules out of the other modules.   I'm still missing a lot of options and bridges.... and the log4j2.properties configuration is not working.

**Comment by joakime** [comment]
`slf4j` is an implementation detail, we should minimize the use of that in the names of the modules like that.

The module names we ship shouldn't include implementation details.

The most important aspect of the module name is its purpose (or role).  so `logging` should be at the start of the name.

Example: We will never ship alternatives for `logging-log4j`.  Our internal implementation would be jetty's slf4j configuration + slf4j-api.jar + slf4j-log4j.jar + log4j.jar

We could specify a few `[provides]` to ensure the classpath doesn't get out of wack.

Examples:

`logging-log4j.mod` could have:

    [depends]
    logging-slf4j

    [files]
    ...|lib/logging/slf4j-log4j12.jar
    ...|lib/logging/log4j.jar
    resources/log4j.xml

    [provides]
    org.slf4j.impl.StaticLoggerBinder
    org.apache.log4j.Logger

`logging-slf4j.mod` could have:

    [provides]
    org.eclipse.jetty.util.log.Logger
    org.slf4j.Logger

    [files]
    ...|lib/logging/slf4j-api.jar
    ...|resources/jetty-logging.properties

and `logging-capture-commons-logging.mod` has:

    [depends]
    logging-slf4j

    [files]
    ..|lib/logging/jcl-over-slf4j.jar

    [provides]
    org.apache.commons.logging.LogFactory
    org.apache.commons.logging.Log
    
This `[provides]` nuance can be utilized by the `start.jar` mechanism for some level of sanity checking the environment.

I see it having 3 levels of checks.

 * Skipped / No Check
  * Only available via optional command line `--skip-provides-check`
 * Default Check
  * Check that there is only 1 module with a specific `[provides]` entry enabled (more than 1 is an error that needs to be corrected)
  * Ensure that there is only 1 instance of the `[provides]` resource (classname) in the as-built server classpath, if there is more then one, its a conflict and needs to be fixed. (this is especially true for `commons-logging`!)
 * Deep / Full Check
  * Only performed on `--list-config` execution (can be prevented with above `--skip-provides-check` if so desired)
  * Will ensure that there is only 1 instance of each class in the defined server classpath (this will also catch other bad setups we've seen with jsp / jfaces / jersey / cdi / jdbc / dbs / etc ...)

**Comment by gregw** [comment]
I think prepending `logging-` to all these module names might be a good idea, as names like `jul-` `jcl-` might not be immediately obvious to all.  Although it is pretty verbose.

I don't agree that slf4j is an implementation detail.     It adds the slf4j API to the classpath, which then may or may not be used by jetty and may or may be used by the application.       It is the jetty-slf4j module that activates the mapping of jetty logging to slf4j.   

It is tempting to think that in a chain of loggers, the intermediaries are implementation details.  Except that they may be directly used by components and/or applications.   So we are not really in a position to know/decide if they are implementation (ie just needed to map us to another logging mechanism) or part of the solution (directly used).    Thus I think the naming I've used that makes all the mappings explicit is the best to go with.

To use your example (but without the `logging-` prefixes for now, if somebody juest enabled `log4j`, then all that would do is put the log4j v1.2 API and implementation on the classpath.   That might be directly used by the application entirely independently of jetty logging.      If they want to unify logging, then they need to map `jetty-logging` to `log4j`.  However we currently do not provide a 'jetty-log4j' module (nor do we plan to, so the solution is to go via slf4j enable:
```
--add-to-start=jetty-slf4j,slf4j-log4j,log4j
```

So in this case, it is an implementation detail, but as I said above it may also be that they need to unify components that use slf4j directly with ones that use log4j.       They also have the option of going the other direction and putting all log4j into slf4j:
```
--add-to-start=jetty-slf4j,slf4j-simple,log4j-slf4j
```

Currently you cannot skip the `[provides]` checking.   In order for start.jar to function, all dependencies must be satisfied with 1 and only 1 capability provider.  So the default checks you describe are already performed by every run of start.jar.  That's implemented now.

The deep/full check is a good idea, but perhaps not on --list-config.  It may need a --check-classpath as it could be an expensive n^2 operation.  It needs to check a class for each jar is not available in any other jar.   Technically we probably need to check every class in every jar - but I think that would take way too long.  So checking 1 class per jar would detect bad classpaths so long as there are not different packagings of classes into jars.    Perhaps we need both a deep and VERY deep check?

I'm not sure I fully understand your `[provides]` example?   The modules as I defined them already do as much but just use the capability names like `slf4j-api`, `log4j2-api`, `slf4j-impl` etc.      I think this is sufficient and we don't need to start using classnames as capability names

I definitely do not like fixed purpose modules like your proposed `logging-capture-commons-logging.mod`  as that assumes the reason jcl is being added to the classpath.   It might be added to be used entirely independently of our logging.      That is why we need some modules that provide API (the ability to capture logs) and alternate impls (the ability to either log an API or map it into another log API).   These modules can then be assembled in lots of different ways.

**Comment by joakime** [comment]
Drop `slf4j-simple` that's only for unit testing, that should not be a module or something that is active during `jetty-distribution`

**Comment by gregw** [comment]
What is the slf4j impl that I should replace it with?  ie what impl can handle logs itself without another logging mechanism?

**Comment by gregw** [comment]
I added a `jetty-log4j` module that just depends on `jetty-slf4j` & `slf4j-log4j`, so users can make that bridge without having to explicitly ask for slf4j

**Comment by gregw** [comment]
I'm pretty happy with these now.

**Comment by WalkerWatch** [comment]
Having this kept open for now so I can track it for documentation.
