### ISSUE TITLE
Flakey test SslBytesServerTest.testHandshakeWithResumedSessionThenClose

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6443]
**Jetty 11.0.x**

This test is failing in my branch for PR #6428 - needless to say that PR does not change anything related to this test.

**Comment by lorban** [comment]
This test is also flakey in 9.4.x and 10.0.x.

**Comment by lorban** [comment]
Seems to be due to a too strict / outdated interpretation of the TLS spec by this test.
