### ISSUE TITLE
Request#getServletPath() returns null for ROOT mapping

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipse/jetty.project#6451]
**Jetty version(s)**
10.0.5

**Java version/vendor** `(use: java -version)`
Java 11

**OS type/version**
Windows 10 x64 21H1

**Description**
Using:
```
 <servlet-mapping>
    <servlet-name>rwtServlet</servlet-name>
    <url-pattern></url-pattern>
  </servlet-mapping>
```
with empty "url-pattern" will register the servlet at root path. In this case Request#getServletPath() should return empty string like in Jetty 9.4.x., but with Jetty 10.x it returns null. Probably the issue is introduced by the new class ServletPathMapping. When pathInContext is null the _servletPath is set to null as well.

**Comment by joakime** [comment]
Opened PR #6452
