### ISSUE TITLE
Wrong files/lib definitions in certain *-capture.mod files?

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse/jetty.project#6464]
**Jetty version(s)**
- 10.x
- 11.x

**Description**

I just tried to create a jetty-base using all of the logging *-capture modules and ended up with a jar file on the root of jetty-base. That seemed weird so I looked into the files and found the following sections which seem to be broken.

---

https://github.com/eclipse/jetty.project/blob/dc21b2d73cafd78a56e8e532cf50863739bd7027/jetty-home/src/main/resources/modules/logging-jcl-capture.mod#L16-L20

The file should be downloaded to `lib/logging/jcl-over-slf4j-${slf4j.version}.jar`, right?

---

https://github.com/eclipse/jetty.project/blob/dc21b2d73cafd78a56e8e532cf50863739bd7027/jetty-home/src/main/resources/modules/logging-log4j1-capture.mod#L16-L20

Here `jcl-over-slf4j-${slf4j.version}.jar ` is also downloaded to the root of jetty-base but `lib/logging/log4j-to-slf4j-${slf4j.version}.jar` is put on classpath. So `log4j-to-slf4j-${slf4j.version}.jar` should have been downloaded in the first place and put into `lib/logging/`, right?

**Comment by janbartel** [comment]
Yup, looks like a bug to me - shouldn't be any jars in `$jetty.base` top level, and the `logging-log4j1-capture.mod` should download` log4j-to-slf4j-${slf4j.version}.jar`.

**Comment by joakime** [comment]
I'll take this and get a PR put up today.

**Comment by jnehlmeier** [comment]
> Yup, looks like a bug to me - shouldn't be any jars in `$jetty.base` top level, and the `logging-log4j1-capture.mod` should download` log4j-to-slf4j-${slf4j.version}.jar`.

Just looked at slf4j and the correct one should be `maven://org.slf4j/log4j-over-slf4j/${slf4j.version}`. 

There is also a `log4j-to-slf4j` library provided by log4j itself, but that uses a different version, see: https://search.maven.org/artifact/org.apache.logging.log4j/log4j-to-slf4j/2.14.1/jar

**Comment by joakime** [comment]
Opened PR #6465 with fix (and new distribution tests)
