### ISSUE TITLE
Improve alias checking in PathResource

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6473]
**Target Jetty version(s)**
9.10,11

**Enhancement Description**

Currently multiple calls to canonicalPath are done, which is inefficient repeat scanning. Include normalization in alias checks, as was previously done in FileResource, so that only a single normalization pass is needed.

**Comment by lachlan-roberts** [comment]
This is done in both the 9.4.43 project and the 10.0.6/11.0.6 project so I think this issue can be closed.
