### ISSUE TITLE
Support %u<4-digit-hex> encoding for path parameter values

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#6479]
**Target Jetty version(s)**
10

**Enhancement Description**
There was a proposal to support `%u<4-digit-hex>` as encoding for unicode codepoints, but it was rejected (https://en.wikipedia.org/wiki/Percent-encoding#Non-standard_implementations).

However, it may still be possible to encounter such encoding, and we need to be prepared to either parse or completely ignore it (but not err on it).

For example, to encode the `€` character with the rejected proposal: `%u20AC`.

However, the correct way to encode the euro character would be to convert to UTF-8 and then encode the bytes: `%E2%82%AC`.

This would only apply to query parameter values, and `application/x-www-form-urlencoded` form parameter values.

**Comment by gregw** [comment]
The only use that Jetty makes for path parameters (themselves a now totally un-standardized concept) is to: a) strip them from decoded path URI strings; b) use a trailing path parameter as an opaque session ID comprised on non-reserved characters (`Long.toString(r, 36)`).

In neither case does jetty require the parameter to either be encoded or decoded.

Furthermore, we never make our extracted version of the parameter available to the application.  Any application that wishes to use path parameters must access the raw URI and perform its own parsing, extraction and possible decoding of the parameter.   Even if an embedded usage of jetty accesses the HttpURI class to call our internal `getParameter()` method, the result of that is encoded and we do not decode for the application.

For query parameters, there has never been support for `%u` encodings and there is no standard to support them.  Currently an application can ask for the non decoded query string and perform it's own decoding, or it can access request parameters, in which case Jetty will do the decoding according to the standards that do not include support for `%u`.  Any such encoded query strings will be treated exceptionally by jetty if we are asked to decode.   I don't believe we should add support for `%u` encoding here either.

**Comment by sbordet** [comment]
Will not be supported.
