### ISSUE TITLE
URIUtil.canonicalPath() should not decode all pct-encoded values

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6482]
**Jetty version(s)**
All

**Description**
Per https://datatracker.ietf.org/doc/html/rfc3986#section-2.3

The unreserved characters, when encountered in pct-encoded form, should not be decoded.

That means the following should not be decoded by canonicalPath()

Desc | Codes
---- | ----
ALPHA | `%41`-`%5A` and `%61`-`%7A`
DIGIT | `%30`-`%39`
hyphen | `%2D`
period | `%2E`
underscore | `%5F`
tilde | `%7E`

Which means we are decoding too much.

If we have a constrained resource at say `/foo/*`, and a request for `/%66oo/content` (hex `0x66` is lower case `f`) that should never match `/foo/*` nor should it ever return content in the WAR/WebApp that actually starts with `/foo/`.

This also has an impact on ambiguous path work recently done, as the existence of `/%2e%2e/` should not be decoded.
That should resolve to a path in the WAR/WebApp with the actual 6 characters `%2e%2e`.

**Comment by gregw** [comment]
I think you are more reading that section. To me it says that unreserved characters should not needlessly be encoded and Matt be decided at any time. It does not restrict the encoding of reserved characters other than in the next section where it says deciding should only be done once

**Comment by gregw** [comment]
From the section above:
> URI producing applications should percent-encode data octets that correspond to characters in the reserved set unless these characters are specifically allowed by the URI scheme to represent data in that component. 

So I think it is clear that reserved characters can be encoded and should thus be decoded.   Section 2.3 is about making comparison simpler by avoiding needless encoding of non reserved characters:

 > For consistency, percent-encoded octets in the ranges of <not reserved characters> should not be created by URI producers 

Section 2.4 is about the danger of double decoding and how URI parsing must be done before decode, which we do.

I think we are correctly implementing this part of the specification.   Our only deviation is that we perform an normalization after decoded, to further reduce double decode issues at the expense of not allowing some essiteric segments to be passed as part of a decoded path (eg ".." can be a valid segment if encoded, but not in our implementation).
