### ISSUE TITLE
Expose ServletHolder getter in ServletHandler$ChainEnd for auditing libraries to use

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6487]
**Jetty version(s)**
9.4.42

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
If an audit library wants to hook into the `FilterChain` of the `ServletHandler`, they use the new APIs such as `ServletHandler.newFilterChain(FilterHolder filterHolder, FilterChain chain)` introduced in Issue #5022

However accessing the `ServletHolder` isn't that easy, and you have to resort to reflection trickery to access it.

We should expose the `ServletHolder` as a formal API.

**Comment by gregw** [comment]
@joakime I'm closing this as both PRs are merged.

**Comment by joakime** [comment]
@gregw any reason why Chain and ChainEnd are still private?

**Comment by gregw** [comment]
@joakime well the question really should be put the other way.  What is the reason for not having them private?
I guess they could be made protected so they are available to extensions, but they probably need better names if they are to be exposed... maybe:  `FilterChainLink` and `FilterChainTarget`

**Comment by joakime** [comment]
@gregw to allow people to implement the `newFilterChain()` properly, and actually be able to call this `.getServletHolder()` that the associated PRs were all about.

**Comment by gregw** [comment]
@joakime developers that implement `newFilterChain()` can do so without use of our utility classes for creating links in the chain and a termination.    However, I have no issue with making our utility classes available as protected classes, so long as we think about the names a bit more.
