### ISSUE TITLE
Replace SameFileAliasChecker

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6497]
**Target Jetty version(s)**
9.4.x+

**Enhancement Description**
The current SameFileAliasChecker is almost a no-op based on changes before it is called.

We should address the 2 common usages.

1. Case Insensitive aliases - for windows requests (ala `/index.html` vs `/INDEX.HTML`)
2. FileSystem Normalization - for OSX and ZFS based filessytems that treat UTF-8 encoding differently on request vs storage.

**Comment by lachlan-roberts** [comment]
The documentation should be also updated to explain why you should not use `SameFileAliasChecker` or `ApproveAliases` unless you are sure of what you are doing.

**Comment by lachlan-roberts** [comment]
I think this needs to be done in 9.4 as well.

**Comment by joakime** [comment]
This is fully merged in 9.4.x and 10.0.x onwards

**Comment by lachlan-roberts** [comment]
Has not been ported to `9.4.x` yet.

**Comment by joakime** [comment]
> Has not been ported to `9.4.x` yet.

Then what was PR #6540 for?

**Comment by lachlan-roberts** [comment]
That was the original PR that was for `9.4.x`, however it was not merged and was closed. We instead developed a fix for the `10.0.x`/`11.0.x` branches (#6681) and the plan was to port a minimal fix back to `9.4.x`.
