### ISSUE TITLE
Resource.addPath() should enforce child path references.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6498]
**Target Jetty version(s)**
9.4.x+

**Enhancement Description**
All uses of Resource.addPath(String) should enforce that the requested child resource is always within the Resource, never navigating out of the Resource.

**Comment by joakime** [comment]
@gregw I think this change should go into Jetty 10+ (no change in Jetty 9) wdyt?

**Comment by gregw** [comment]
Reserve judgement until i see pr
