### ISSUE TITLE
Error page has HTML error when writePoweredBy is enabled.

### ISSUE THREAD

**Issue by gencarnacao** [eclipse/jetty.project#6520]
**Jetty version(s)**
At least since 9.4.x

**Description**
The footer of the page, containing the "Powered By" line has an incorrect closing html tag. This causes issues when trying to parse the file automatically although visually in browsers this is undetectable.

**How to reproduce?**
With the Powered By footer enabled, trigger any error page (easiest is 404). I detected this on a running Jenkins installation while trying to access the jobs api of a non-existent job.

https://github.com/eclipse/jetty.project/blob/9d6db9e0986b352e54c7a03a3a1564179b69e10d/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L400

I can avoid the problem by setting the 'Accept' header to 'application/json' which then returns a correct payload and is parseable.

**Comment by sbordet** [comment]
@gencarnacao as the fix is trivial, would you be interested in issuing a PR to fix it?

**Comment by joakime** [comment]
We validate that the JSON error output is sane in our ErrorHandlerTest.
Perhaps we should do the same with the HTML (we should be generating XHTML compliant output) and the XML output too.

**Comment by gencarnacao** [comment]
@sbordet I tried. There should be a PR pending. Somewhere.

**Comment by joakime** [comment]
Opened proper fix (with testcase to verify output format validitiy) as PR #6525

**Comment by gencarnacao** [comment]
Saw the PR, unless I misundertood I think there is a typo. 
You modified the opening `<hr>` tag not the closing `<hr/>` one which should be `</hr>.`

**Comment by joakime** [comment]
The `<hr>` element (aka the "Horizontal Rule") has no body.

So this is invalid: `<hr>body</hr>`
but this is not: `<hr/>body<hr/>`.

While in strict HTML5 you don't have to close the `<hr>` element, you do have to close it if you want to conform with XHTML.
