### ISSUE TITLE
Missing <Arg> should either throw xml parse error or succeed

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6531]
**Jetty 9.4.x **

There is no error from the xml parser with a construct like:

```xml
  <Get name="systemClasspathPattern">
      <Call name="add">-javax.mail.</Call>
  </Get>
```
The above snippet is missing `<Arg>` inside the `<Call>` statement. 

When the above statement is executed, there is no error, but neither does the `add(String)` method appear to be executed.

**Comment by gregw** [comment]
Actually, when writing a test for this I discovered that DTD validation should find such problems, so I don't think we want to duplicate the validation.
