### ISSUE TITLE
Jetty 9.3 ServletContext.getResourceAsStream("/") returns an unusable stream

### ISSUE THREAD

**Issue by Artur-** [eclipse/jetty.project#654]
With Jetty 9.2.x ```ServletContext.getResourceAsStream("/")```returns null
With Jetty 9.3.x ```ServletContext.getResourceAsStream("/")```returns an InputStream which throws an IOException if you try to read it: `java.io.IOException: Is a directory`

Wildfly 10 and Tomcat 8 seems to agree with Jetty 9.2.

**Comment by joakime** [comment]
The relevant Javadoc.

http://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html#getResourceAsStream-java.lang.String-

A Resource in this sense is muddy, as "Resource" has 2 definitions at this point.  

 * A Java Classpath Resource - in this case its null
 * An HTTP Resource - in this case its valid (but has no content in the context of a stream)

Extreme Example: Depending on configuration of the server (produce-file-listing), and the `Accept` header on the request, the implementation of `.getResourceAsStream("/")` could even serve that as an HTML directory listing. (thankfully we don't do that!)

Either way, this still smells like a behavior bug in Jetty 9.3.x, but I'll let the Servlet spec group participants on our side comment more authoritatively.

**Comment by joakime** [comment]
Opened PR #655 for this, to let the SME's decide if this is appropriate.

**Comment by gregw** [comment]
@joakime I see you closed your PR.... but I don't think it is a bad approach (although should probably do and exists test as well like getResource(String) does).      However it is probably worthwhile investigating how 9.2.x was excluding directories...  

I will have a look later today.... unless you are keen to follow up (in which case assign this issue back to yourself).

**Comment by joakime** [comment]
So it looks like Jetty 9.2 (and earlier) used a Resource.getInputStream() implementation that would trigger an IOException on-construction vs on-first-access.

Jetty 9.2 and earlier used `java.io.FileInputStream(File)` which had the on-construction behavior.

Jetty 9.3 and onward uses `java.nio.file.Files.newInputStream(Path, OpenOptions[])` which has the on-first-access behavior.

This nuance means that the [`ContextHandler.getResourceAsStream(String)`](https://github.com/eclipse/jetty.project/blob/78c9010400a7ecac3986fbd3f4fc7fc0380aa5d0/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L2117-L2133) implementation cannot catch the on-construction based Exception and it flows out as a `InputStream` instead.

Changing the behavior of `PathResource.getInputStream()` to behave the same way, as well as adding the `Resource.isDirectory()` check back into `ContextHandler.getResourceAsStream(String)` to prevent creation of the `InputStream` in the first place.
