### ISSUE TITLE
image/webp MIME type support

### ISSUE THREAD

**Issue by ofrias** [eclipse/jetty.project#6545]
**Jetty version(s)**
 10.0.6

**Java version/vendor**
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**OS type/version**
 Ubuntu 20.04.2 LTS

**Description**
image/webp is not registered as a MIME type

**How to reproduce?**
Deploy any .webp image and check that it is served without any MIME type.

**Comment by joakime** [comment]
Typically, if you want an extra mime-type over what comes with the container you can ...

1. manually specify it on your response `Content-Type` header.
2. customize the `org.eclipse.jetty.http.MimeTypes` within your `ContextHandler` (or `ServletContextHandler` or `WebAppContext`) with the `.getMimeTypes()` access (be sure to think about how `charset` for the mime-type operates, and also how it should be handled in the HTTP conversation: indicate if the mime-type is inferred, assumed, or normal)
3. specify the mime-type in your `WEB-INF/web.xml` 

``` xml
  <mime-mapping>
    <extension>webp</extension>
    <mime-type>image/webp</mime-type>
  </mime-mapping>
```

That being said, webp is a common enough type that we should consider adding it to the container's default list.

Do you have an authoritative list of the mime-type definitions? (eg: from a spec document)
We would be interested in knowing the official mime-type name, any filename extensions, any charset restrictions for that mime-type (unlikely for `image/*` based types), and if the mime-type is inferred, assumed, or normal when used in the HTTP conversation.

**Comment by ofrias** [comment]
It looks like `image/webp` is not yet in [the official mime-types list](https://www.iana.org/assignments/media-types/media-types.xhtml#image).

Currently we are using option 3 of your list, but it looks like `GzipHandler` constructor is not using our configuration because Jetty applies gzip compression to our .webp files.

This code from `GzipHandler` constructor is not working for us (I assume `MimeTypes.getKnownMimeTypes()` does not contain the mime-types defined at `web.xml`, or at least not at `GzipHandler` constructor execution time):

```
for (String type : MimeTypes.getKnownMimeTypes())
        {
            if ("image/svg+xml".equals(type))
                _paths.exclude("*.svgz");
            else if (type.startsWith("image/") ||
                type.startsWith("audio/") ||
                type.startsWith("video/"))
                _mimeTypes.exclude(type);
        }

```

**Comment by ofrias** [comment]
Both Chrome and Firefox include `image/webp` in their `content-type` request header when requesting a .webp image.  So it is already being used although it is not in the official list yet.

**Comment by joakime** [comment]
Some resources about webp ...

* https://developers.google.com/speed/webp - official webp home page
* https://developers.google.com/speed/webp/faq#server-side_content_negotiation_via_accept_headers - indicates that `image/webp` is the content negotiation type
* https://chromium.googlesource.com/webm/libwebp - official webp source repository
* https://github.com/webmproject/libwebp/ - mirror of the official webp source repository
* https://caniuse.com/webp - list of browsers that support webp

I think we should make sure we support vp8 as well, as they are related.

**Comment by joakime** [comment]
A previous person asking the same question as me in the webp mailing lists ...

https://groups.google.com/a/webmproject.org/g/webp-discuss/c/FAaCCW5E__w/m/iCtF8H_UYt8J

**Comment by joakime** [comment]
Opened PR #6548

**Comment by janbartel** [comment]
Looks like the default mimetype list has been updated with the ones you were interested in. 

However, I think Jetty could do a better job of integrating custom mimetypes from web.xml with the GzipHandler, so I've opened #6637
