### ISSUE TITLE
Review usage of Authentication.UNAUTHENTICATED in SecurityHandler

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#6553]
Review usage of `Authentication.UNAUTHENTICATED` in `SecurityHandler`.

The `JaspiAuthenticator` may return this in the case that it did not receive a `Principal` to use and returning `UNAUTHENTICATED` the request to continue through the `SecurityHandler` even if authentication was mandatory.

I think we may need to add a case in `SecurityHandler.handle` for:
```java
else if ((authentication == Authentication.UNAUTHENTICATED) && isAuthMandatory)
{
    response.sendError(HttpServletResponse.SC_FORBIDDEN, "unauthenticated");
    baseRequest.setHandled(true);
}
```

**Comment by janbartel** [comment]
Looks good - PR?
