### ISSUE TITLE
HttpOutput.write(ByteBuffer buffer)

### ISSUE THREAD

**Issue by MacX19** [eclipse/jetty.project#6562]
**Jetty version** 9.4.43

**Java version** 1.8.0_261

**Question**
I am using the methods `HttpOutput.write(ByteBuffer buffer)` and `HttpOutput.write(byte[] b, int off, int len)` to send the response. Also I am using GzipHandler. I am testing with the same response data. When I use the `write(byte[] b, int off, int len)` method, the _Content-Length_ header is set in the response. When I use the `write(ByteBuffer buffer)` method, the _Transfer-Encoding: chunked_ header is set in the response. I only call the method once. I suspect the `last` variable is not being set correctly. Could this be just a misprint?

`HttpOutput.write(int b)`:
https://github.com/eclipse/jetty.project/blob/735e97d5c7e41a39e759a5d76e45f0b5c1226209/jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java#L1002
`HttpOutput.write(byte[] b, int off, int len)`:
https://github.com/eclipse/jetty.project/blob/735e97d5c7e41a39e759a5d76e45f0b5c1226209/jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java#L796
`HttpOutput.write(ByteBuffer buffer)`:
https://github.com/eclipse/jetty.project/blob/735e97d5c7e41a39e759a5d76e45f0b5c1226209/jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java#L926

**Comment by gregw** [comment]
It is indeed a buglet!   Thanks for noticing and your diagnosis!
Reproduced with some extra tests and `s/_written/written/` fixes those tests.  But I've found a couple of other semi-related issues, so doing some more testing and improving code coverage. Standby...
