### ISSUE TITLE
how to deploy jxadf

### ISSUE THREAD

**Issue by xiemn** [eclipse/jetty.project#657]
How to deploy open source platform [ jxadf](https://github.com/wmzsoft/JXADF) in the jetty?

**Comment by gregw** [comment]
Sorry, but I don't know what the jxadf platform is and cannot read the japanese(?) website.

Perhaps you should ask the jxadf folks how to deploy?    We'd be happy to answer any of their questions if they want to ask here.

**Comment by joakime** [comment]
@gregw looks like jxadf is an OSGi based toolkit for rapid web development.

Closing as invalid for this issue tracker.
