### ISSUE TITLE
Review all Configuration classes and move to appropriate modules where possible

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6570]
**jetty-10.0.x/jetty-11.0.x**

Many Configuration classes for all kinds of integrations have been swept into the jetty-webapp module:  jaas, jndi, jsp, jmx to name a few. However, the ideal situation is that these Configuration classes reside in their _own_ module.  Sometimes this might not be possible due to circular dependencies, however we should review these and move Configurations where it is possible to avoid polluting the jetty-webapp module.

**Comment by gregw** [comment]
If a module depends on `jetty-webapp`, then it should contain it's own `Configuration`s
If `jetty-webapp` depends on the module, then `jetty-webapp` will need to contain the `Configuration` on it's behalf.
If neither of the above applies, then the module can have an optional dependency on `jetty-webapp` and contain it's own `Configuration`s.

This is the point when @joakime and @sbordet  and @olamy tell me that optional dependencies never work the way I think they do.

**Comment by sbordet** [comment]
@janbartel unfortunately the `Configuration` class is in `jetty-webapp`, so you can't make more generic modules such as jaas, jndi, jmx to depend on webapp.

So the implementation for those must be in the webapp module (what @gregw says above).

**Comment by joakime** [comment]
@sbordet @gregw yet we successfully do that for some `Configuration` classes now.

We have 3 in websocket that disprove this absolutism.

**Comment by joakime** [comment]
I completely agree with @janbartel and want to see those implementations of Configuration (and their associated service files) in the correct places.

**Comment by joakime** [comment]
One of the more complicated examples brought up by @sbordet is `JmxConfiguration`.

Which exists in `jetty-webapp`, along with it's services file (which is the wrong place).
But if you move `JmxConfiguration` to `jetty-jmx`, then you'll create a dependency from `jetty-jmx` to `jetty-webapp`, which causes a cyclic dependency issue.

```
$ mvn validate
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eclipse.jetty:jetty-jmx:jar:10.0.7-SNAPSHOT
[WARNING] 'dependencies.dependency.scope' for org.eclipse.jetty:jetty-webapp:jar must be one of [provided, compile, runtime, test, system] but is 'optional'. @ line 37, column 14
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.eclipse.jetty:jetty-webapp:10.0.7-SNAPSHOT'}' 
and 'Vertex{label='org.eclipse.jetty:jetty-servlet:10.0.7-SNAPSHOT'}' introduces to cycle in the graph org.eclipse.jetty:jetty-servlet:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-security:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-server:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-http:10.0.7-SNAPSHOT
--> org.eclipse.jetty:jetty-io:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-jmx:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-webapp:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-servlet:10.0.7-SNAPSHOT @ 
[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.eclipse.jetty:jetty-webapp:10.0.7-SNAPSHOT'}' 
and 'Vertex{label='org.eclipse.jetty:jetty-servlet:10.0.7-SNAPSHOT'}' introduces to cycle in the graph org.eclipse.jetty:jetty-servlet:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-security:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-server:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-http:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-io:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-jmx:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-webapp:10.0.7-SNAPSHOT 
--> org.eclipse.jetty:jetty-servlet:10.0.7-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectCycleException

```

**Comment by lachlan-roberts** [comment]
> unfortunately the Configuration class is in jetty-webapp, so you can't make more generic modules such as jaas, jndi, jmx to depend on webapp.

When doing the `JaspiConfiguration` class I was able to keep this in `jetty-jaspi` module and only have an optional dependency on `jetty-webapp`. I think this is also possible for some of the other configurations currently in `jetty-webapp` like the `JaasConfiguration`.

**Comment by janbartel** [comment]
@gregw, @joakime @sbordet not to concentrate on jmx, but as it has entered the discussion ... there is _no_ reason for the dependency of `jetty-webapp` on `jetty-jmx`.  No code in `jetty-webapp` has any `import` statements for `org.eclipse.jetty.jmx`. It is in fact only a `test` dependency, and when it is removed `jetty-webapp` builds without any errors. So I see no reason to maintain a dependency `jetty-webapp -> jetty-jmx` and this could in fact be made an `<optional>` dependency the other way around.

**Comment by sbordet** [comment]
@janbartel it's the other way around: if we move `JmxConfiguration` to `jetty-jmx` we have problems. 
So it needs to remain in `jetty-webapp`.

**Comment by janbartel** [comment]
Further info:

Whilst it is possible to use the maven `<optional>true</optional>` dependency to create a module that does not require another downstream module to use `jetty-webapp`, it is not possible to do the same with `module-info.java`.  Making `jetty-webapp` a `requires static` is fine, but you cannot then declare the `Configuration` class as a service via a `provides Configuration with MyConfiguration`. So in short, maven would be fine, but jpms is not fine.

**Comment by janbartel** [comment]
I think the only way of proceeding is to do some refactoring, involving moving some or all of the Configuration class and associated concepts into `jetty-util` (which avoids any circular dependencies). Probably this refactoring would be too much for jetty-10/11 and should be pursued in an experimental branch.

**Comment by sbordet** [comment]
> I think the only way of proceeding is to do some refactoring, involving moving some or all of the Configuration class and associated concepts into `jetty-util`.

I fail to understand why? 

I don't see any difference having the `Configuration` subclasses in `jetty-webapp`, and I think moving `Configuration` to `jetty-util` is wrong, as `Configuration` is a webapp specific concept.

I also fail to understand what the problem is? 
The current status is optimal, and I don't see any reason to move things around?

**Comment by gregw** [comment]
@sbordet The issue is for modules like jndi. It doesn't depend on webapp and could be used without it. Ideally it would contain it's open JndiConfiguration as an optional dependency on webapp. But as Jan explained jpms does not allow that.

**Comment by janbartel** [comment]
@sbordet the problem is:
+ some `Configurations` cannot currently reside inside the module they configure which would be the natural situation maintaining encapsulation
+ undeploying these modules therefore does not also remove their `Configuration`
+ these `Configurations` have to introduce workarounds like checking for one of their module's classes on the classpath to know if they are enabled or not
+ the `jetty-webapp` module is made fatter by having these unrelated `Configurations` in them
+ it's not clear for a programmer creating a new `Configuration` that only conditions the classpath - but which could depend on `jetty-webapp`-  whether or not they should put it in `jetty-webapp` along with the majority of the other `Configurations

The optimum situation would be that a `Configuration` is contained within the module whose operation it conditions.
