### ISSUE TITLE
jetty Selector threads is Always runable status resul in no available threads

### ISSUE THREAD

**Issue by zhangforbai** [eclipse/jetty.project#6580]
![image](https://user-images.githubusercontent.com/49714074/127953717-2d1329f3-82ca-4be9-8e12-d6c55ded1c55.png)
![image](https://user-images.githubusercontent.com/49714074/127953784-772b639d-ed91-4478-b110-9150cf8d3592.png)
fixed 4 thread .

**Comment by zhangforbai** [comment]
hallo Mr.@sbordet could you pls help cc ?

**Comment by zhangforbai** [comment]
the version is 9.4.11.v20280605

**Comment by lachlan-roberts** [comment]
@zhangforbai that version is quite old, can you try upgrading to `9.4.43.v20210629` and see if you have the same problems.

**Comment by zhangforbai** [comment]
> @zhangforbai that version is quite old, can you try upgrading to `9.4.43.v20210629` and see if you have the same problems.

ok , I'll try .

**Comment by sbordet** [comment]
@zhangforbai the acceptor thread blocked in `accept0()` and the selector threads blocked in `epollWait()` is a completely normal and expected condition.
They are reported as RUNNABLE by the JVM and that's normal too.

Your problem is that you have a thread pool that is too small: 4 threads are way too few, why did you configure it in this way?

Jetty's default is 200 threads, and they will only be created if necessary.
Stick with the defaults and you will be good.

**Comment by zhangforbai** [comment]
> @zhangforbai the acceptor thread blocked in `accept0()` and the selector threads blocked in `epollWait()` is a completely normal and expected condition.
> They are reported as RUNNABLE by the JVM and that's normal too.
> 
> Your problem is that you have a thread pool that is too small: 4 threads are way too few, why did you configure it in this way?
> 
> Jetty's default is 200 threads, and they will only be created if necessary.
> Stick with the defaults and you will be good.

but we use 4 threads are normal 
<html>
<body>


previous |  
-- | --


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by zhangforbai** [comment]
> @zhangforbai the acceptor thread blocked in `accept0()` and the selector threads blocked in `epollWait()` is a completely normal and expected condition.
> They are reported as RUNNABLE by the JVM and that's normal too.
> 
> Your problem is that you have a thread pool that is too small: 4 threads are way too few, why did you configure it in this way?
> 
> Jetty's default is 200 threads, and they will only be created if necessary.
> Stick with the defaults and you will be good.

but we use 4 threads are normal previou ， but one day , the threads are all  reported as RUNNABLE and there are no threads can process the request . and the normal state of the thred is wait on condition by test .
![image](https://user-images.githubusercontent.com/49714074/127998915-ea45a844-49a8-4ab5-a62b-bd7de4cdb86a.png)

**Comment by zhangforbai** [comment]
> > @zhangforbai the acceptor thread blocked in `accept0()` and the selector threads blocked in `epollWait()` is a completely normal and expected condition.
> > They are reported as RUNNABLE by the JVM and that's normal too.
> > Your problem is that you have a thread pool that is too small: 4 threads are way too few, why did you configure it in this way?
> > Jetty's default is 200 threads, and they will only be created if necessary.
> > Stick with the defaults and you will be good.
> 
> but we use 4 threads are normal previou ， but one day , the threads are all reported as RUNNABLE and there are no threads can process the request . and the normal state of the thred is wait on condition by test .
> ![image](https://user-images.githubusercontent.com/49714074/127998915-ea45a844-49a8-4ab5-a62b-bd7de4cdb86a.png)

this problem is the threads are reported as RUNNABLE all the time . and cat process the request .

**Comment by zhangforbai** [comment]
The scenario of this problem is that we use 5 threads in the production env almost 1 years and never meet the prolem . but the can't process the request at  15/07/2021 , and there are no threads can process . we try restarted the service and linux but no effect。   so we change the server , use  the same code and Configuration ， the new server can process the requset . 
![image](https://user-images.githubusercontent.com/49714074/128001054-be72035a-c6b7-4c90-bb6d-15d87622a844.png)
![image](https://user-images.githubusercontent.com/49714074/128001227-75d35264-38ea-4154-929f-f0ec597a208c.png)

**Comment by zhangforbai** [comment]
@sbordet could you pls cc? I think there sitll have some prolems .

**Comment by sbordet** [comment]
@zhangforbai 4-5 threads for a server is not a wise choice. 
How it worked before, I have no idea, probably just luck, or some different configuration.

There is no need whatsoever to restrict the number of threads.
Use the default and you will be good.

Please also read the section about what is an acceptor thread and a selector thread, and if necessary configure those.
https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-http-acceptors
https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-http-selectors

**Comment by zhangforbai** [comment]
> @zhangforbai 4-5 threads for a server is not a wise choice.
> How it worked before, I have no idea, probably just luck, or some different configuration.
> 
> There is no need whatsoever to restrict the number of threads.
> Use the default and you will be good.
> 
> Please also read the section about what is an acceptor thread and a selector thread, and if necessary configure those.
> https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-http-acceptors
> https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-module-http-selectors

ok , many thx !
