### ISSUE TITLE
CORS error when trying request Options

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#6587]
**9.4.39**

**Java version** - JDK8

**Question** -  With jetty 6.1.26, CORS was working for customer in the default config. However, when they shifted to our product which is using 9.4.39 jetty, its not working. So, was it default skipped to check CORS in 6.1.26? We have to explicitly enable it in 9.X? 
https://www.eclipse.org/jetty/documentation/jetty-9/index.html#cross-origin-filter

Thanks
Dev

**Comment by sbordet** [comment]
>  its not working

It's very little information to help you out.

The CORS filter is working fine, so you need to provide evidence of what you say.

**Comment by 4devwithgit** [comment]
Basic question is, was CORS filter not there in jetty 6.1.26?

**Comment by sbordet** [comment]
> Basic question is, was CORS filter not there in jetty 6.1.26?

I don't think the `CrossOriginFilter` was implemented for Jetty 6.
It was first introduced in Jetty 7.0.0.RC2.

**Comment by 4devwithgit** [comment]
ok, thanks for the quick response. Please close this request.

**Comment by joakime** [comment]
Jetty 6.1.26 code is archived at ...

https://github.com/jetty-project/codehaus-jetty6/tree/jetty-6.1.26/

A search for `Access-Control-Allow-Origin` in the archive produces nothing ...

https://github.com/jetty-project/codehaus-jetty6/search?q=Access-Control-Allow-Origin

And just for completeness, here's what the same search looks like in this active repository (for Jetty 9, 10, 11)

https://github.com/eclipse/jetty.project/search?q=Access-Control-Allow-Origin
