### ISSUE TITLE
Fail to upgrade jetty to 9.4.43.v20210629

### ISSUE THREAD

**Issue by zjffdu** [eclipse/jetty.project#6592]
**Jetty version(s)**

9.4.43.v20210629

**Java version/vendor** `(use: java -version)`

Java(TM) SE Runtime Environment (build 1.8.0_211-b12)

**OS type/version**

Mac OS

**Description**

I used `9.4.31.v20200723`, and it works very well. But after I upgrade to `9.4.43.v20210629`, my web app fails to start. Here's the error I see in log:

```
 WARN [2021-08-09 12:23:28,043] ({main} WebAppContext.java[doStart]:533) - Failed startup of context o.e.j.w.WebAppContext@75f95314{zeppelin-web,/,file:///Users/jzhang/github/zeppelin/zeppelin-web/dist/,UNAVAILABLE}
java.lang.IllegalStateException
    at org.eclipse.jetty.servlet.ServletHolder.setClassFrom(ServletHolder.java:300)
    at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:347)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
    at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:730)
    at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
```

**How to reproduce?**

**Comment by gregw** [comment]
That exception indicates that a class is already set for a servlet holder that has a jsp-file element.

Can you confirm if your web.xml has any servlets with a jsp-file element? If so, do they also have a servlet-class element?

**Comment by zjffdu** [comment]
@gregw Here's the servlet config in my web.xml

```
<servlet>
    <servlet-name>default</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
      <param-name>jersey.config.server.provider.packages</param-name>
      <param-value>org.apache.zeppelin.rest</param-value>
    </init-param>
   <load-on-startup>1</load-on-startup>
</servlet>
```

**Comment by gregw** [comment]
@zjffdu there must be another servlet somewhere because your exception is definitely from the handling of a `jsp-file`.
Hmmm we could have logged the failed servlet better.

Can you run with full jetty debug turned on and attach the log?

**Comment by joakime** [comment]
@gregw he redefined the default servlet to some other servlet-class.

@zjffdu please (temporarily) change your `<servlet-name>default</servlet-name>` to something else, like `<servlet-name>xdefault</servlet-name>` and try again.
As the name "default" is a reserved name for the servlet spec implementations to use for handling static file serving and errors.

**Comment by janbartel** [comment]
@zjffdu also please describe your environment in terms of are you running embedded or with the distro, how do you configure your servlets (web.xml, web-fragment.xml, custom webdefault.xml etc). You should be able to replace the servlet with the existing name of "default" (which is the jetty DefaultServlet, configured in webdefault.xml), but it would be interesting if you do as @joakime suggests and temporarily rename it.

**Comment by zjffdu** [comment]
@joakime @janbartel  change `default` to `xdefault` doesn't work, same error as before. BTW I am using jetty as embedded web server.

**Comment by joakime** [comment]
@zjffdu there's not enough information left from your original question to help.
Is this project somewhere public we can look at it?
Or can you replicate this in a smaller project? 
Or give us details on how you configure both your Jetty `Server` and your `WebAppContext` in your embedded code?

**Comment by zjffdu** [comment]
@joakime Here's our project https://github.com/apache/zeppelin and PR for upgrading jetty https://github.com/apache/zeppelin/pull/4160

**Comment by joakime** [comment]
@zjffdu cool.  I'll clone it and check out the PR ...
Wow, big project!

**Comment by joakime** [comment]
btw, your project doesn't compile with newer versions of Maven (i'm using 3.8.1) due to the use of `http://` instead of the mandatory `https://` that newer versions of maven require.  This is a maven CVE that was fixed in a newer `org.apache:apache` parent pom.

See: https://github.com/joakime/zeppelin/commit/34d59c7442aafccce7947ebd6210b4ee80fcf66b

Also, how do you compile this monster?
It's not a strict maven project, and seems to be build piece-meal based on your [`.github/workflows/core.yml`](https://github.com/apache/zeppelin/blob/master/.github/workflows/core.yml)

It also has dependencies that just don't exist.

```
$ $ mvn install -Pbuild-distr -DskipRat -DskipTests -pl zeppelin-server,zeppelin-web,spark-submit,spark/spark-dependencies,markdown,angular,shell -am -Phelium-dev -Pexamples
...(snip)...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.353 s
[INFO] Finished at: 2021-08-12T11:52:20-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spark-shims: Could not resolve dependencies for project org.apache.zeppelin:spark-shims:jar:0.10.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.zeppelin:zeppelin-interpreter-shaded:jar:0.10.0-SNAPSHOT, jdk.tools:jdk.tools:jar:1.6, org.apache.zeppelin:zeppelin-interpreter:jar:0.10.0-SNAPSHOT, org.apache.zeppelin:zeppelin-common:jar:0.10.0-SNAPSHOT: org.apache.zeppelin:zeppelin-interpreter-shaded:jar:0.10.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of oss-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :spark-shims
```

What's the command line I should use to build up to the Jetty layer?
Using [the documented](https://zeppelin.apache.org/docs/latest/setup/basics/how_to_build.html) `mvn clean package -DskipTests` results in the inability to find various non-existent dependencies (like `jdk.tools:jdk.tools:1.6`) or numerous scala-library failures related to "error while loading package".
And what's the command line and/or test case to use to test the load Jetty in Zeppelin?

**Comment by joakime** [comment]
Some thoughts on a review of [ZepplinServer.java](https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java)

---

Don't use `WebAppContext.setParentLoaderPriority(true);`

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L583

Use the `WebAppContext.setExtraClasspath(String)` with the specific jars you want the webapp to use.
Don't break the WebApp Classloader Isolation, you'll just cause more problems then you want to deal with.

---

This is not a proper setup for the DefaultServlet.

``` java
webApp.addServlet(new ServletHolder(setupServlet(webApp, conf)), "/*");
```

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L594

The `DefaultServlet` must have the `<servlet-name>` "default" and must be on the url-pattern `/` (no splat or glob) (this is mandated by the Servlet Spec)

The way this is currently declared means you will wind up with multiple `DefaultServlet` implementations.
add a `server.setDumpAfterStart(true);` before your `server.start();` call, and you'll see what I mean.

Your customization on the `DefaultServlet` can be handled easier by just having a `IndexHtmlServlet` mapped to the url-pattern `/index.html`

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L605-L641

You can then access the index.html contents present in the WAR file with `ServletContext.getResource("/index.html")`
Your customization of the `DefaultServlet` isn't even done properly, as it doesn't take into account the `ResourceService` behaviors, or caches, or compression, or etags, nor the API contract changes on `ResourceFactory`.

---

The raw / unconfigured SessionHandler you have going on is invalid.

``` java
webapp.setSessionHandler(new SessionHandler());
```

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L550

All WebAppContext's have a SessionHandler properly configured, remove or fix that line to do the right thing with a proper Session setup.

---

Don't use .setForcedPath("rest"), that's not what that method is for, that method exists for JSP definitions from the `WEB-INF/web.xml` `<jsp-file>` definition.  (This is the likely reason for your issue btw)

``` java
servletHolder.setForcedPath("rest");
```

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L549

---

You cannot change the Jetty server version text on HttpGenerator like you are doing (those are static final fields).

``` java
      if (conf.getJettyName() != null) {
        org.eclipse.jetty.http.HttpGenerator.setJettyVersion(conf.getJettyName());
      }
```

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L258-L260

Changing the Server response header is not a use case we support.
We only support turning on/off the header in the HttpConfiguration.setSendServerVersion(boolean) and HttpConfiguration.setSendXPoweredBy(boolean)

If you want a custom Server response header, consider instead using a custom `HttpChannel.Listener.onResponseBegin(Request)` to set it just before the response is committed, that way it will be present in all situations, including 400 Bad Request scenarios.

---

The process you have for IDE usage is a bit awkward.

``` java
    // when zeppelin is started inside of ide (especially for eclipse)
    // for graceful shutdown, input any key in console window
    if (System.getenv("ZEPPELIN_IDENT_STRING") == null) {
      try {
        System.in.read();
      } catch (IOException e) {
        LOG.error("Exception in ZeppelinServer while main ", e);
      }
      System.exit(0);
    }

    jettyWebServer.join();
```

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L279-L290

Don't use System.exit(0), as this isn't graceful.  Use `server.stop();`, but only if you have the `server.setStopTimeout(int)` set to a positive value (in milliseconds) for the graceful stop to act.
If you want graceful stop for connectors and connections, you might also need the StatisticsHandler or StatisticsServlet present.

**Comment by joakime** [comment]
There are many examples of `WEB-INF/web.xml` that attempt to redefine the "default" servlet.

``` xml
	<servlet>
		<servlet-name>default</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
      <param-name>jersey.config.server.provider.packages</param-name>
      <param-value>org.apache.zeppelin.rest</param-value>
    </init-param>

		<load-on-startup>1</load-on-startup>
	</servlet>
```

* zeppelin/zeppelin-web-angular/WEB-INF/web.xml
* zeppelin/zeppelin-web/dist/WEB-INF/web.xml
* zeppelin/zeppelin-web/src/WEB-INF/web.xml

Change all of these to use a name other than `<servlet-name>default</servlet-name>` as jersey cannot be a the Servlet Spec mandated Default Servlet.
The way you have the currently defined, you are getting tons of init-param and other configuration shoved down into jersey from the Servlet spec and Jetty due to it simply being named "default".  All errors are going through it as well because you have it named "default".. Your configuration for things like `<error-page>` in the same descriptor will never be used as you have taken over the role of the "default" servlet by simply naming it "default".

Think of it as a reserved word.  Jetty has two servlet name reserved words: `default` (Servlet Spec) and `jsp` (Jsp Spec).  Don't use those unless you are going to satisfy everything that being those spec names implies.

**Comment by janbartel** [comment]
@zjffdu is this issue closeable?

**Comment by zjffdu** [comment]
@janbartel  I don't have time to verify the above solution, let me try it asap

**Comment by zjffdu** [comment]
> ```
> <servlet-name>default</servlet-name>
> ```

@joakime I update the `web.xml`, but still doesn't work.  Here's error I can see

```
 WARN [2021-08-24 17:04:16,473] ({main} WebAppContext.java[doStart]:533) - Failed startup of context o.e.j.w.WebAppContext@75f95314{zeppelin-web,/,file:///Users/jzhang/github/zeppelin/zeppelin-web/dist/,UNAVAILABLE}
java.lang.IllegalStateException
    at org.eclipse.jetty.servlet.ServletHolder.setClassFrom(ServletHolder.java:300)
    at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:347)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
    at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:730)
    at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)

```

**Comment by joakime** [comment]
@zjffdu did you address the other things in comment https://github.com/eclipse/jetty.project/issues/6592#issuecomment-897877018 ?

As that stacktrace tells me you haven't.

The stacktrace tells me you are still using `.setForcedPath("rest")`, that's not what that method is for, that method exists solely for JSP definitions from the `WEB-INF/web.xml` `<jsp-file>` definition.

``` java
servletHolder.setForcedPath("rest");
```

https://github.com/apache/zeppelin/blob/100cdb6021f3f8132ca9b3ed3beff507125cce78/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L549

Your code has many warts with it's usage of Jetty, you'll need to address them all.

**Comment by jongyoul** [comment]
It's awesome. I wanted to refactor and make ZeppelinServer clearly but didn't have much knowledge about Jetty itself. Thank you for all of your considerate reviews. I'll fix some issues reviewed. cc/ @zjffdu

**Comment by joakime** [comment]
Fixed in https://github.com/apache/zeppelin/pull/4385
