### ISSUE TITLE
Need to get Jetty integrated with osgi

### ISSUE THREAD

**Issue by CrazyCoder80** [eclipse/jetty.project#6594]
**Jetty version** 9.4.40.v20210413 Embedded

**Java version** Java 11

**Question** We are using embedded to host various webApps and several webApps are developed by our vendors and we dont have control on the various dependencies used by these vendors and we run into class loading issues. To counter this we are planning to use OSGI to deploy the webApps as bundles. 
So far 
1.) We have have bundled the webApp using the **maven-bundle-plugin** 
2.) We are also using jetty-osgi-boot.jar

But I am landing in all sort of issues. Require your help in getting the right approach to get this done. I could not find sufficient documentation that could help me achieve this. If you could help me with this would be great. Also attaching the code for your reference. Am I doing something wrong?

[Code.zip](https://github.com/eclipse/jetty.project/files/6956283/Code.zip)

http://localhost:2421/WebApplication

**Comment by joakime** [comment]
Going from traditional WebApp deployment with traditional Servlet classloader isolation and behavior to OSGi, is making your problem space actually much larger and far more complicated.  

Keep in mind that OSGi will only be used for the server level, and not at or within the WebAppContext.  All of the behaviors of the WebAppClassloader which are troubling you now will still trouble you.

I would encourage you to properly configure your embedded server, and WebAppContext's with an eye on what you allow to be exposed between the server classloader and the various webapp classloaders.  You have some very powerful features available to you in the WebAppClassloader and it's ClasspathPatterns (include/exclude).

Start with NOT using .setParentLoaderPriority() on the WebAppContext.  Leave it at default.
Next, look at your WebAppContext and it's WebAppClassloader, make sure it's include/excludes for system and server ClasspathPattern's make sense for what you want to expose from the server classloader, and what you want to force that the webapp uses from the server classloader, and what you never want the webapp to never overload or replace from the server classloader.

**Comment by janbartel** [comment]
@CrazyCoder80 I don't think osgi is going to be the panacea for you. As the jetty osgi infrastructure will also look inside wars deployed as osgi bundles to find WEB-INF/lib, if your fundamental problem is that webapps have poorly controlled WEB-INF/lib jars then this will also carry over to the osgi environment: a webapp that fails to deploy outside of osgi is also unlikely to deploy inside of osgi. As @joakime says, it would be worthwhile to try and  configure your embedded jetty environment to be able to properly isolate these webapps (definitely using the default webapp classloading _not_ parent first).

**Comment by janbartel** [comment]
@CrazyCoder80 ?

**Comment by CrazyCoder80** [comment]
@janbartel As recommended by you we are not going ahead with the osgi approach. We are now trying to configure jetty to isolate the webapps.
Thanks you guys for your help and guidance.
