### ISSUE TITLE
NullPointerException in Request.getParameter: _parameters is null

### ISSUE THREAD

**Issue by oyvindhorneland** [eclipse/jetty.project#660]
**Version**: 9.3.9.v20160517 and 9.3.10.v20160621

**Problem**: Encountering a NullPointerException when the first servlet filter tries to invoke request.getParameter for a POST request. 

Debug in Request class shows that 

- `_parameters` is null in Request.java:961. 
- `_queryParameters` is an empty list
- `_contentParameters` is null

Since `_queryParameters` is an empty list, `restoreParameters()` assigns `_parameters=_contentParameters`, which is in this case is null. If I manually in debug mode execute `extractContentParameters()`, `_contentParameters` is populated and the NullPointer is then avoided.

**Stacktrace**:
```
java.lang.NullPointerException
	at org.eclipse.jetty.server.Request.getParameter(Request.java:961)
	at com.iknowbase.logging.http.RequestEntryFilter.getConversationId(RequestEntryFilter.java:131)
	at com.iknowbase.logging.http.RequestEntryFilter.doFilterInternal(RequestEntryFilter.java:70)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:397)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:201)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joakime** [comment]
Can you detail what your POST request looks like? (the structure of the HTTP Request is what's important for us.  Feel free to capture the raw HTTP request and include it here in a comment)

Also, what do the 2 Filters in your stacktrace do exactly? 

 * do any of them attempt to access `request.getInputStream()` or `request.getReader()`?
 * do any of them wrap the request object?

**Comment by oyvindhorneland** [comment]
The POST request is:

```
POST /ikbInstant/ikb$service/v1/publish HTTP/1.1
Host: [REMOVED]
Connection: keep-alive
Content-Length: 95
Accept: application/json, text/javascript, */*; q=0.01
Origin: https://[REMOVED]
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://[REMOVED]
Accept-Encoding: gzip, deflate, br
Accept-Language: nb-NO,nb;q=0.8,no;q=0.6,nn;q=0.4,en-US;q=0.2,en;q=0.2
Cookie: IKBSESSION=[REMOVED]
```

With Form data:
```
topic:%2FSYSTEST%2FInstant%2FHTTP%2F6%3FmessageFormat%3DIKB%26userList%3Dtrue
message:messagetest6
```

The filter (RequestEntryFilter called by Spring's OncePerRequestFilter) reads headers and parameters and registers info in MDC for logging purposes. The specific call that fails is:
```
req.getParameter("X-Atmosphere-tracking-id")
```
The filter does not access request.getInputStream or request.getReader, nor does it or OncePerRequestFilter wrap Request. 

The parameter the filter is looking for is not present in the request and it is expected to get a null response.

**Comment by joakime** [comment]
@oyvindhorneland I was unable to replicate your issue, but I did check in a simplification of that process,can you test the latest changes for Jetty 9.3.x? see if this is more sane to you?

**Comment by joakime** [comment]
@gregw can you validate this commit please?

**Comment by oyvindhorneland** [comment]
@joakime Thanks! I'll try to reproduce with the latest commit. Note that when I was debugging the issue, it seemed like the Request object was missing a call to extractContentParameters, since a call to that method added content to _contentParameters and thus avoided the NPE. I believe your commit does not resolve that particular issue (when _contentParameters is null) and although it will not throw a NPE, the content it could have provided is not extracted fro mthe Request.

Meanwhile I've been trying to reproduce the issue and the exact same POST request that fails (during a more complex scenario involving Atmosphere subscribers) does not fail when replayed using Fiddler without all the other stuff going on. Not sure what that really means since I would expect the exact same request to reproduce the problem, but perhaps there is some underlying recycling issue for Request objects that makes the next request fail and perhaps it has something to do with Atmopshere as well... Don't know at this point.

**Comment by gregw** [comment]
@joakime I think this fix is wrong.    The NO_PARAMS is a special value above and beyond just having no values in it.   We need to retore the parameters as they were before, not create a new map that just happens to have the same content.

**Comment by gregw** [comment]
@oyvindhorneland I agree with your suspicion that the underlying problem is about why _contentParameters is null.     How can that be so if parameters have been extracted?

We do have a setter, but nothing is calling that.

Thus we really need to work out how _paramsExtracted could be true, yet _contentParameters is null?

I can see a lot of code that can be cleaned up in this area, but don't wish to change it until we know more about what is going on. 

@joakime I'm going to revert your commit for now.

**Comment by gregw** [comment]
@oyvindhorneland I'm struggling to see how this can be reproduced... unless something is calling recycle on the request.    Is there any async processing going on?

**Comment by oyvindhorneland** [comment]
@gregw Yes, I'm using Atmosphere with long-polling. I can reproduce the issue when long-polling clients are connected, so it might very well be some conflict here. https://github.com/Atmosphere/atmosphere/issues/1998 looks a bit similar and although that issue concerns WebSocket and session, I'm using the same org.atmosphere.container.Jetty9AsyncSupportWithWebSocket for long polling without Atmosphere's session support.

Atmosphere runtime version: 2.3.4

Attaching a screenshot from the debug stack and Request object when the error has occurred. Might be of some use.:
![image](https://cloud.githubusercontent.com/assets/1670211/16293642/cc3b6772-391b-11e6-8a75-afb085219d86.png)

**Comment by gregw** [comment]
@oyvindhorneland thanks for that!   That shows that it is not concurrent recycle.  I think the problem is an AsyncContext.dispatch(path?query).   I think I can see how to reproduce... trying now....

**Comment by gregw** [comment]
@oyvindhorneland No luck.  I get work out how to get _parameters==null after they have been extracted, but I can't see how to get _contentParameters to also be null.

Do you know if atmosphere or anything calls setContentParameters?  Can you try putting a break point in there?

**Comment by oyvindhorneland** [comment]
@gregw setContentParameters is never called. Digging...

**Comment by oyvindhorneland** [comment]
Request.recycle() is called from an async context as shown in the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/1670211/16295809/28b6c25a-3929-11e6-92c2-f3796de691cf.png)

The same Request object is reused afterwards for a POST that fails.

Do you see anything here that I should investigate further?

**Comment by oyvindhorneland** [comment]
It seems this issue can only be reproduced when i use the combination of Atmosphere with session support off and also enabled Spring Session (for the rest of the application). I can't reproduce if I turn Spring Session off or turn Atmosphere Session support on. 

With the problematic combination I see a different NullPointer happening in Jetty's Request object: When the async request completes, Atmosphere tries to inspect the session (even if session support is disabled) and fails (see stacktrace below). The next request on the same HttpChannel with the same Request object fails with the NullPointer described in the previous posts.

`java.lang.NullPointerException
	at org.eclipse.jetty.server.Request.extractQueryParameters(Request.java:372)
	at org.eclipse.jetty.server.Request.restoreParameters(Request.java:1013)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:960)
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)
	at org.springframework.session.web.http.CookieHttpSessionStrategy.getCurrentSessionAlias(CookieHttpSessionStrategy.java:165)
	at org.springframework.session.web.http.CookieHttpSessionStrategy.getRequestedSessionId(CookieHttpSessionStrategy.java:157)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSessionId(SessionRepositoryFilter.java:395)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:340)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:214)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)
	at org.atmosphere.cpr.AtmosphereRequest.getSession(AtmosphereRequest.java:805)
	at org.atmosphere.cpr.SessionTimeoutSupport.restoreTimeout(SessionTimeoutSupport.java:69)
	at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:822)
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:478)
	at org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:313)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:174)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:108)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:170)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2262)
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:190)
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:176)
`
This prevents Atmopshere from finishing cleanup for the async request. This error was logged on debug in Atmosphere, so I didn't notice it before.


So it seems that if an error occurs during Atmosphere's cleanup, the Request object on HttpChannel is not properly recycled and the next request is affected.

I can for my specific application see if I can use any of the combinations that doesn't reproduce the problem or dig further into Atmosphere and try to apply a fix for this combination.

Would it be possible for Jetty to ensure the Request object is properly recycled before using it for a new request? Would be more robust, but it's also just compensating for the real problem and might add too much overhead. I can see the problem coming with a custom jetty handler:
![image](https://cloud.githubusercontent.com/assets/1670211/16300059/145fb5a4-393e-11e6-8299-338bdf29b112.png)

**Comment by joakime** [comment]
@gregw please add some tests that show this forwarding behavior that required the NO_PARAMS logic. (we currently have no such tests)

**Comment by sbordet** [comment]
@oyvindhorneland Do you have the code for the last screenshot ? You seemed to be able to reproduce it without Atmosphere, Spring, etc. so that would be a valuable test case for us. Thanks !

**Comment by oyvindhorneland** [comment]
@sbordet The state shown in the last screenshot cannot be reproduced without Atmosphere+++ (or at least I haven't been able to so far). It shows the next intercepted request that will fail once the filter eventually calls getParameter, since the Request object has been ruined.

**Comment by oyvindhorneland** [comment]
I'll dig into the NullPointer in extractQueryParameters(Request.java:372) to try to determine why _metadata is null here in the first place. Even if Atmosphere checks for a parameter, we shouldn't get a NullPointer in extractQueryParameters.

**Comment by sbordet** [comment]
@oyvindhorneland 

Can you please try to use Jetty 9.3.11.M0 and tell us if you still hit the problem ?

If yes, you should log the thread and the stack trace that calls `Request.recycle()` - although that would require to modify the Jetty sources and recompile it. Can you do it ? If not we can help.
Add a line:

`LOG.info("recycle", new Throwable());`

inside `Request.recycle()`.

**Comment by oyvindhorneland** [comment]
@sbordet Still the same problem with 9.3.11.M0.

Attached (long) stack traces for 
* stacktrace.txt: recycle calls until _metadata is null in extractQueryParameters, the last one being the stacktrace for extractQueryParameters.
* stacktrace2.txt: recycle class until the issue is detected in my custom jetty handler (_paramsExtracted is true, but both _queryParameters and _contentParameters is null)

[stacktrace.txt](https://github.com/eclipse/jetty.project/files/329960/stacktrace.txt)
[stacktrace2.txt](https://github.com/eclipse/jetty.project/files/329968/stacktrace2.txt)

**Comment by oyvindhorneland** [comment]
I've used a wrapper to suppress the request.getSession(boolean) call triggered during Atmosphere's cleanup (SessionTimeoutSupport.restoreTimeout), and the NPE in extractQueryParameters is avoided and I can no longer reproduce any of the reported NPE issues. 

This enforces the theory that a failure in Atmosphere's cleanup may lead to a dirty Request object for the next request. 

The failure during cleanup occurs when the Request object is already in a recycled/empty state (_metadata is null). In stacktrace.txt you'll see that the request is recycled twice for the same request:

1. First when the long polling connection is resumed (2016-06-23 14:45:05.240)
`at org.atmosphere.cpr.AtmosphereResourceImpl.resume(AtmosphereResourceImpl.java:296)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.postStateChange(AbstractReflectorAtmosphereHandler.java:219)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:162)`

2. Second when the OnDisconnectInterceptor kicks in (2016-06-23 14:45:06.084)
`at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:811)
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:478)
	at org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:77)
`

I've yet to check why OnDisconnectInterceptor kicks in and if this is a configuration error in the test I'm using to reproduce the issue, but whatever the reason, it seems Atmosphere hangs on to the Request for too long. But I probably don't need to bother you guys about the Atmosphere details :)

--
So for Jetty's part in all this: Since it seems to be a failure outside Jetty, I'm not sure that there is anything here you need to fix, but Jetty could perhaps:

1. do a null check on _metadata in extractQueryParameters (the NPE that disrupts Atmosphere's cleanup would be avoided)
2. do a null check on _parameters in getParameter (avoid NPE, but then what?)
3. check if the Request has already been recycled when recycle is called (not sure if it would bring anything significant to this issue, though)
4. check if the Request is properly recycled before using it for a new request (but this might be unwanted overhead)

, but I guess if code outside Jetty hangs on to the Request object for too long, it really doesn't matter what you do since it might interfere at any time after the Request is eligible for reuse. Of course an option might be to not reuse the Request object, but I assume that is rather fundamental and not something you would want to change.

Any thoughts or suggestions?


Thank you all for your quick response to this issue. Much appreciated!

**Comment by sbordet** [comment]
@oyvindhorneland, great analysis !

We have a lot to work on, so we'll analyze your data and get back to you.

Thanks !

**Comment by gregw** [comment]
@oyvindhorneland thanks for the great analysis.

Jetty does attempt to protect against these kind of late calls to AsyncContext methods.  Specifically the AsyncContext instance we pass to the application is a one use instance with a volatile reference to the reusable HttpChannelState.    The volatile is cleared when the request is recycled or the async cycle is completed.

However, in this case, I think it is more that the late calls are to arbitrary request methods, which can throw NPEs and thus mess up other error handling.

So we can look at our code and try to better protect against such NPE resulting from an unexpected recycle, but that is difficult to achieve entirely without putting in synchronization or volatiles. 

We have considered not recycling request objects, but they are pretty fat objects with a lot of machinery in them - complex state object, async contexts, complex in/out streams etc.    To throw all that away on each request will generate a lot of garbage.       Now years ago it was a no brainer to avoid such garbage.... now it could be that modern GC algorithms favour short lived or long lived objects, but do not appreciate medium life objects like a recycled request....  So it is something we should re-evaluate, but it would be a big decision to make and something more likely to be put into 10.x rather than 9.4.x       Note that it is rather easy to install a filter that always wraps and throws the wrapper away, so that can help protect against and/or detect such issues... perhaps we should offer that as an option.

**Comment by gregw** [comment]
@joakime I still can't work out if the NO_PARAM stuff is a token that will affect behaviour (which thus could be tested) or if it is just an optimization to avoid creating tables.       So that in itself is bad... code to complex to work out what it does.   At the very least this needs more code comments, and perhaps some simplification.

The difficulty with the NPE protection, is that in this case we need to protect against parallel execution of other calls - which are probably illegal, but we want to fail as nicely as we can - but without going to volatiles and synchronization.    I have some ideas, which I will test out shortly.... standby.

**Comment by sbordet** [comment]
@oyvindhorneland, no dice.

The recycle stack traces you attached show that the request object is indeed completed twice.
However, the `AsyncContext` object is created anew after each recycle, so the fact that is can complete twice means that there are 2 different `AsyncContext` objects, which means these are really 2 different requests.

Furthermore, the timings are far apart, so it's not really a race condition between two threads.

I see you are using an old version of Atmosphere (2.3.4), if you update to 2.4.4 you still see the problem ?

**Comment by oyvindhorneland** [comment]
@sbordet I see that the test that fails is executing like this

Step 1. Req#1: Atmosphere long polling handshake (GET) with immediate response from server
Step 2. Req#2: Atmosphere long polling wait for message (GET)
Step 3. Req#3: Publish a message (POST)
Step 4. Req#2: Atmosphere receive message from Req#3
Step 5. Req#4: Atmosphere long polling wait for message (GET)
Step 6. Req#5: Atmosphere close (by request from client after message has been receiced) (GET)
Step 7. Req#4: Atmosphere long polling connection is closed.

.. and the next tests follow the same logic (with different config options and Atmosphere broadcasters). Req#5 is intercepted by Atmosphere's OnDisconnectInterceptor.

From the stacktraces it looked like the request resumed in Step 4 (recycle) and the request terminated in Step 6 (recycle) was the same and that Step 6 failed with NullPointer in extractQueryParameters. Step 6 is really a different request (Req#5 trying to close Req#4) and when the interceptor detects the close request it looks up the AtmosphereResource with the ID specified in the close request and tries to close the suspended request.

Note I've only seen issues for this exact test and the application in "normal use" appears to work just fine.

Hmmm.. I need to take a look at what's happening when the OnDisconnectInterceptor executes and the objects (including Jetty's Request object) it's retrieving from the looked up AtmosphereResource.

I'll take a look at 2.4.4, but I believe there's a compatibility issue there that I need to address first before I can retest on that version.

**Comment by oyvindhorneland** [comment]
Same issue with Atmosphere 2.4.4.

**Comment by oyvindhorneland** [comment]
In AtmosphereResourceImpl.cancel() in https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.4.x/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResourceImpl.java#806 `asyncSupport.complete(this)` is executed, which completes and recycles the Request. However AtmosphereResourceImpl.cancel() still has logic to perform, including the problematic SessionTimeoutSupport.restoreTimeout(req) that with Spring Session triggers request.getParameter on the recycled Request.

I don't know the reasoning for asyncSupport.complete(this) to be executed while there is still work to be done for cleaning up the request and I probably need to discuss this with the Atmosphere devs, but what is your take on this (recommendation or comments)?

**Comment by sbordet** [comment]
@oyvindhorneland I was able to reproduce the NPE without Atmosphere. Standby for detailed analysis.

**Comment by sbordet** [comment]
@oyvindhorneland the issue can be reproduce in this way:

```java
@Override
public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
{
    baseRequest.setHandled(true);
    new Thread(() ->
    {
        try
        {
            Thread.sleep(500);

            request.getParameter("foo");
        }
        catch (InterruptedException x)
        {
            x.printStackTrace();
        }
    }).start();
}
```

That is, the `request` object is utilized _after_ it has been recycled.
The sleep is important, otherwise the new thread could run before `recycle()` is called and avoid the NPE.

Note that the NPE happens with the code before @gregw's commit cfe5abf.
After that commit, `request.getParameter("foo")` returns `null` without errors - however, we need to discuss whether this is appropriate.

@oyvindhorneland, it would be great to confirm if this is what Atmosphere does, i.e. using a request object in a different thread after the original request thread is returned to the container.
If that's the case, it's definitely an Atmosphere bug.

Having said that, we have some discussion/homework to do to improve how we respond to this particular use case. We will keep this issue posted on the outcomes of the discussion.

**Comment by oyvindhorneland** [comment]
@sbordet Great news! 

Since the OnDisconnectInterceptor (invoked due to an new incoming close request) is trying to complete a separate existing suspended request, we definitely have two separate threads operating on the same request. And the OnDisconnectInterceptor is not quite done accessing the suspended request when `asyncSupport.complete()` is called.

As far as I understand this, the OnDisconnectInterceptor could still be used like this as long as it did not access the request after `asyncSupport.complete()` was called. Must also make sure that the previously suspended request does not have any lifecycle code or something that operates on the request object after `asyncSupport.complete()`.

I see @joakime just registered an issue with Atmosphere, so it'll be interesting to follow that one as well.

**Comment by oyvindhorneland** [comment]
.. it's also critical that the OnDisconnectInterceptor makes absolutely sure that the request it's operating on still belongs to the suspended atmosphere resource. Since they're separate threads, you could probably enter a situation where the OnDisconnectInterceptor starts to process the incoming close request, the suspended request resumes on some other event, and then OnDisconnectInterceptor continues to access the request object that no longer belongs to a suspended request. Scary stuff.

**Comment by sbordet** [comment]
Current status is that @gregw's commit gets rid of the NPE, although it would return `null` (or possibly the next request's parameter).

The servlet specification states (section 3.12) that:

> The developer must be aware that maintaining references to request objects
> for which startAsync has not been called outside the scope described above 
> is not recommended as it may have indeterminate results.

So the situation has been considered in the specification and allowed "intedermined results" which basically means anything.

What we can do is to enhance the DebugHandler (#670) to wrap the `HttpServletRequest` in a way similar to what we do with `AsyncContext` so that these "usage after recycle" are caught more clearly.

**Comment by oyvindhorneland** [comment]
Thank you for the update. This sounds good and a log for this scenario is likely to be very useful.

**Comment by sbordet** [comment]
@oyvindhorneland if you have a confirmation that this is an Atmosphere bug, we can close this issue.

**Comment by oyvindhorneland** [comment]
@sbordet I believe the information we have is sufficient confirmation. Via OnDisconnectInterceptor the request object for a different suspended request is accessed after it has been completed. Closing this issue.
