### ISSUE TITLE
Support zstandard encoded request/response content

### ISSUE THREAD

**Issue by bjorncs** [eclipse/jetty.project#6600]
From https://facebook.github.io/zstd/:

> Zstandard is a fast compression algorithm, providing high compression ratios. It also offers a special mode for small data, called dictionary compression. The reference library offers a very wide range of speed / compression trade-off, and is backed by an extremely fast decoder (see benchmarks below). Zstandard library is provided as open source software using a BSD license. Its format is stable and published as IETF RFC 8878.

Zstandard has improved performance/compression ratio over gzip. It's already supported by some HTTP clients (e.g curl https://daniel.haxx.se/blog/2020/08/19/curl-7-72-0-more-compression/).

**Comment by joakime** [comment]
Note, there is a 100% java implementation of zstd available at ...

https://github.com/airlift/aircompressor/tree/master/src/main/java/io/airlift/compress/zstd

Which is Apache 2.0 licensed - https://github.com/airlift/aircompressor/blob/master/license.txt

Available on maven central at https://search.maven.org/artifact/io.airlift/aircompressor

**Comment by Mahdi-Seeker** [comment]
Any progress on this issue?

**Comment by joakime** [comment]
Spec is at https://www.rfc-editor.org/rfc/rfc8878

This labeled as a "low priority" and "help wanted".

Do you even know of any 100% Java based implementations of this spec that can do compression & decompression?

**Comment by georgew5656** [comment]
It looks like the airlift package you posted above will work. Are you still open to taking contributions on this? I can try to take a look.

**Comment by joakime** [comment]
@georgew5656 go for it, base your work on branch `jetty-10.0.x` please, we'll handle the merging to other branches from there (once approved).

**Comment by arsenalzp** [comment]
Hello,
Is this issue still valid and waiting for implementation?

**Comment by joakime** [comment]
Jetty 12.1.0 has a new CompressionHandler that supports zstandard, brotli, and gzip.

**Comment by joakime** [comment]
The 12.1.0.alpha0 release has a version of that implementation right now.

See: https://repo1.maven.org/maven2/org/eclipse/jetty/compression/

Note: the implementation in 12.1.0.alpha0 is experimental at this point in time.
The API isn't fully settled on it.
Feedback would be welcome.

**Comment by joakime** [comment]
Implemented as part of PR

* #12075

**Comment by bjorncs** [comment]
@joakime Do you have a rough timeline for 12.1 GA?

**Comment by sbordet** [comment]
@bjorncs we don't have a timeline yet, but we're working to be as soon as possible.
Likely not before April at this point.
