### ISSUE TITLE
Publish some artifacts jarsigned with Eclipse certifiacte

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/jetty.project#6612]
**Enhancement Description**
The Eclipse Simultaneous release currently requires that content (jars) it ships is jarsigned with the Eclipse certificate. Eclipse Platform heavily relies on Jetty artifacts. Currently, Platform used to alter and sign the p2 artifacts; but that can be error prone.
Jetty doesn't sign its artifacts for some compatibility reasons with some deployments. Fine.
It would be nice of for each artifact, the Jetty project were providing a signed version; I imagine it could just be another artifact attached with the GAV but with the "-signed" classifier. Then Platform should be able simply declare those as dependencies in its pom and get access to those Jetty official and signed artifacts without post-processing them.

**Comment by joakime** [comment]
This is a requirement for Eclipse, and has been brought up before for Eclipse Jetty. (in mailing lists, bugzilla, phone discussions, issues, etc over the years).  

If we cryptographically sign our Jars, we've just created a compatibility mess for other consumers of the Eclipse Jetty jars that rely on runtime modification of the Eclipse Jetty classes (for audit reasons, for metrics reasons, etc).   These same consumers are happy with the external cryptographic signature to verify that jar. (the separate asc signatures and pgp/gnupg/gpg verification against the [/KEYS.txt](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/KEYS.txt) in our repo)

Is it possible (yet) to jarsign _without_ the `META-INF/MANIFEST.MF` entries for each class in the jar?

Note: we don't use Eclipse infrastructure to build Eclipse Jetty, or release Eclipse Jetty, and this has been a source of issues in the past. (we are often too bleeding edge for the Eclipse Infrastructure tools).  In the past, the Eclipse jarsigning process requires us to use Eclipse Infrastructure, which wasn't possible for our release.

**Comment by laeubi** [comment]
> Is it possible (yet) to jarsign _without_ the `META-INF/MANIFEST.MF` entries for each class in the jar?

I think this is the whole point of code-signing, as it allows to verify (and restrict!) code at runtime, while a signature/hash of the jar itself only can be used with exactly that artifact (e.g. requires file access to it!).

Anyways it seems that code-signing has never get its way into common deployment scenarios and can't hold its claims for providing some way of trust in a world that evolve fast ...

So I think it would be crucial to first elaborate what we want to archive, if we just wan't to make sure the jar is not tapered, one could even omit ASC signatures at all and use the P2 metadata as a "key-server", as those contain the sha-256 hashes, so one could always check against the eclipse-p2 repository (if he trust eclipse...) that the hash matches and his copy is the same as the one published there once.

I think this is how the mirrors work, one downloads the meta-data from the "trusted" source but the actual jar is fetched from an (untrusted) mirror and then the hash is compared with the trusted metadata....

**Comment by laeubi** [comment]
>  consumers of the Eclipse Jetty jars that rely on runtime modification of the Eclipse Jetty classes (for audit reasons, for metrics reasons, etc).

btw this is what code-signing should protect users against, so its perfectly reasonable that this is not possible when using it.

**Comment by joakime** [comment]
Here's a small example of a code signing issue that doesn't require runtime bytecode manipulation to trigger.

Jetty server (lets call it version 10.9.9) with traditionally signed jars.
A webapp is deployed that has jetty jars in its `WEB-INF/lib` but at version 10.0.6. (there are many examples of this, proxy, DoSFilter, QoSFilter, WebSocket client, HttpClient, etc)
The use of those webapp classes on different versions of the jetty jars across the WebAppClassloader triggers the signature violation errors.

This is such a common issue that various cloud providers will put in extra effort to work around this.
Some strip class signatures from jars on deployment, or force custom classloaders without signature validation, or even custom JDKs without signature validation, just to get around it.

**Comment by laeubi** [comment]
That's what I mean with "it seems that code-signing has never get its way into common deployment scenarios" as this also indicates some kind of problem/vulnerability and might have security impacts. Anyways I would consider something like " strip class signatures from jars" if it is absolutely required and the security implications are clear I fully understand  that this is not realistic in most scenarios and people just "want it to work".

**Comment by janbartel** [comment]
@joakime the suggestion was to publish _additional_ artifacts with the classifier `-signed`. If these are additional jars, then they can't affect users of the "normal" jars, so are there other factors that mitigate against us releasing these additional signed artifacts?

**Comment by laeubi** [comment]
@janbartel if I understand correctly this would require to build+deploy on eclipse-infra whats seems problematic as jetty requires special setup. Beside that, I don't think its a good idea to publish the same artifact twice just to sign it for one consumer... it could then simply be singed on eclipse-platform side if required (I have opened https://github.com/eclipse-cbi/org.eclipse.cbi/issues/53 for this case).

**Comment by janbartel** [comment]
@laeubi thanks, those were the datapoints I was missing.
