### ISSUE TITLE
Remove outdated profiles from the pom

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#6613]
In https://github.com/eclipse/jetty.project/issues/6612#issuecomment-898413539 it was mentioned that eclipse-infra is not used anymore and signing is not applied.

I think the sections in the pom referencing the eclipse cbi should be removed then, e.g.

https://github.com/eclipse/jetty.project/blob/324fe5e3ee97c76d0db6125cfdedaf1008269196/pom.xml#L1546

**Comment by joakime** [comment]
@laeubi that was added by @rgrunber in PR #2786 for other Eclipse projects that want to build Jetty for their own purposes. (P2 repository building for equinox IIRC)

**Comment by laeubi** [comment]
@rgrunber @akurtakov is this actually used anymore? Just wondering....

**Comment by akurtakov** [comment]
Not AFAICT. Old way was rebuilding jars from source which is totally undesired .

**Comment by rgrunber** [comment]
It was used in https://ci.eclipse.org/jetty/job/jetty-rt-bundles-9/ . If that is no longer in use, then it can be removed.
