### ISSUE TITLE
Getting `Unconsumed Content` on every request even though I'm consuming all content to the best of my knowledge.

### ISSUE THREAD

**Issue by donvi-bz** [eclipse/jetty.project#6614]
**Jetty version** 
11.0.6
**Java version** 
11
**Question**
How do I properly consume all content? / What am I doing wrong?
**Background**
I'm attempting to make a lightweight webhook handler to connect two services together (one has APIs for multiple programming languages, the other is sort of forcing me to receive webhooks or add minutes of delay and use a REST API) and for some reason the service sending out the webhook requests keeps saying that the messages failed even though my service always receives the data. I've been trying to figure out the problem, and believe that this `Unconsumed Content` exception may be core part of my issue. 
Its worth noting that in this example I specifically send a response code of 200 and give a body, but I've tried codes 200, 201, and 204, and tried with and without a body.  

My code for the most part looks like this: 
```java
    @Override
    public void handle(
        String target,
        Request baseRequest,
        HttpServletRequest request,
        HttpServletResponse response
    )
    throws IOException {
        response.setContentType("application/json;charset=utf-8");
        response.addHeader("Connection", "keep-alive");
        byte[] content = "{\"potato\":false}".getBytes(StandardCharsets.UTF_8);
        response.getOutputStream().write(content);
        response.addHeader("Content-Length", Integer.toString(content.length));
        JsonNode json = objectMapper.readTree(
            request.getInputStream().readAllBytes()
        );


        response.setStatus(HttpServletResponse.SC_OK);
        baseRequest.setHandled(true);
        System.out.println(json.toString());
        request.getInputStream().close();
        response.getOutputStream().close();
    }
```
and the exception I'm specifically asking about looks like this
```
java.io.IOException: Unconsumed content
	at org.eclipse.jetty.server.AsyncContentProducer.consumeAll(AsyncContentProducer.java:168)
	at org.eclipse.jetty.server.BlockingContentProducer.consumeAll(BlockingContentProducer.java:85)
	at org.eclipse.jetty.server.HttpInput.consumeAll(HttpInput.java:155)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:439)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:872)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:386)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Edit-clarification: The wireshark part is from the service contacting the webhook, not from my tests with curl
Not sure if this is useful, but this is what the traffic looks like in wireshark: ![wireshark traffic](https://i.stack.imgur.com/55Jyj.png)
Then since more info is always good, here is the [full code](https://pastebin.com/RZF1h1U8), my [pom.xml](https://pastebin.com/PZCC980X), and the [full output](https://pastebin.com/raw/SAqKQvGq).   

I put this as a question because I think its more than likely that I'm just doing something wrong, but it does feel like something somewhere is acting incorrectly.

**Comment by joakime** [comment]
How are you sending the request?

You mentioned `curl` on the stackoverflow question, can you show us your version of curl and what your command line is?

You can add `curl -vvv <rest of command line>` to show some DEBUG on the curl side.
It might reveal something interesting and useful.

_(This is not your issue btw, but something I noticed)_

``` java
response.addHeader("Connection", "keep-alive");
```

Are you exclusively using HTTP/1.0 and never HTTP/1.1 ?
The wireshark image shows you are using HTTP/1.1.
That line does nothing in HTTP/1.1, as the `keep-alive` token has no meaning to HTTP/1.1, which is persistent by default.
Remove that whole line.

**Comment by donvi-bz** [comment]
Whoops, that  `response.addHeader("Connection", "keep-alive");` was from my end-of-the-day just try random stuff. I'm not sure that had much of an effect on it. Also, another silly mistake on my end, I was testing both from linux and from windows and what I was using to test was this:
```
curl http://10.193.8.73:8701/kafka/ditto-in.recycler -METHOD POST -BODY '{"value":2}
``` 
in **PowerShell** (whoops).  Sending the equivalent from Ubuntu though gives me a similar Unconsumed Content exception, ~~but no timeout exception at the end~~.  I'm going to take out the line you mentioned, then test again from windows and from ubuntu.

**Comment by donvi-bz** [comment]
Okay, so the keep alive header was removed, I restarted the server, added a bunch of blank lines in the middle of the debug output, then ran the command mentioned above in powershell, then added another large group of blank lines, then ran/recieved this in Ubuntu:
```
main@Topae:~$ curl http://10.193.8.73:8701/kafka/ditto-in.recycler -d '{"value":2}' -vvv
*   Trying 10.193.8.73:8701...
* TCP_NODELAY set
* Connected to 10.193.8.73 (10.193.8.73) port 8701 (#0)
> POST /kafka/ditto-in.recycler HTTP/1.1
> Host: 10.193.8.73:8701
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 11
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 11 out of 11 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 13 Aug 2021 14:35:17 GMT
< Content-Type: application/json;charset=utf-8
< Content-Length: 16
< Server: Jetty(11.0.6)
<
* Connection #0 to host 10.193.8.73 left intact
{"potato":false}
```
Here is the [new output](https://pastebin.com/raw/nXhJWsz3).

**Comment by donvi-bz** [comment]
Since I hadn't been able to get anywhere further with this approach, I decided to implement my webhook listener a third time, and this time switch languages (I went to JS). The newest version functioned basically identically to the last two versions I made (the jetty one being attempt 2) and it looked *almost* identical in wireshark, but the same service thats been sending the requests still says it doesn't work.

I'm fairly certain at this point that the true issue I'm dealing with is within the service sending the webhooks, and most of the stuff I've been looking into here probably doesn't really matter. I still am curious about why I was getting the `Unconsumed Content` error here and if it even is important, but its not *too* important to me and I won't mind if you guys close this issue if there's not much to say/do here.

**Comment by ritzow** [comment]
I'm not sure if what I've encountered is related. When I have DEBUG logging enabled, Jetty is creating an IOException with "Unconsumed content" even after consuming all content. It seems like many internal Jetty methods call consumeAll on HttpInput or AsyncContentProducer despite consumeAll being guaranteed to produce this DEBUG message. It seems like this is all intentional but it's a really weird DEBUG message to get when there is no unconsumed content. I think it's just to help developers find where consumeAll is being called or something? You won't get this exception if you don't DEBUG logging enabled.

This is the org.eclipse.jetty.server.AsyncContentProducer implementation in question:

```java
@Override
public boolean consumeAll()
{
    assertLocked();
    Throwable x = UNCONSUMED_CONTENT_EXCEPTION;
    if (LOG.isDebugEnabled())
    {
        x = new IOException("Unconsumed content");
        LOG.debug("consumeAll {}", this, x);
    }
    failCurrentContent(x);
    // A specific HttpChannel mechanism must be used as the following code
    // does not guarantee that the channel will synchronously deliver all
    // content it already contains:
    //   while (true)
    //   {
    //       HttpInput.Content content = _httpChannel.produceContent();
    //       ...
    //   }
    // as the HttpChannel's produceContent() contract makes no such promise;
    // for instance the H2 implementation calls Stream.demand() that may
    // deliver the content asynchronously. Tests in StreamResetTest cover this.
    boolean atEof = _httpChannel.failAllContent(x);
    if (LOG.isDebugEnabled())
        LOG.debug("failed all content of http channel EOF={} {}", atEof, this);
    return atEof;
}
```

This is probably normal but 🤷‍♂️. Kind of a bad practice in my opinion if it is. I guess I need to see if there's a way to prevent consumeAll from being called at all, but all the methods I've checked seem to just call it unconditionally, and it's guaranteed to "fail" the channel. `HttpChannel.handle` seems to unconditionally call it when in the TERMINATED state. So I guess you have to prevent `HttpChannel.handle` from being called when it is TERMINATED. 🤷‍♂️

**Comment by sbordet** [comment]
> I think it's just to help developers find where consumeAll is being called or something?

Correct.

It's just a DEBUG log, you can ignore it.
