### ISSUE TITLE
SpringFramework 5 taglibs are not loading using Jetty 10.0.1

### ISSUE THREAD

**Issue by anishsharma91** [eclipse/jetty.project#6619]
HTTP ERROR 500 org.apache.jasper.jasperException : line[3] column[0], The absolute URI : [http://www.springframework.org/tags] cannot be resolved in either web.xml or the jar files deployed with the application.

This is the error showing on the screen while loading the application.
I am including the spring 5 taglibs in my jsp which is not loading 

<%@ taglib prefix = "spring" uri ="http://www.springframework.org/tags" %>

NOTE : The application was working fine before with spring 4 and jetty server 8... 
I have migrated the application to spring 5.3.2 and using jettty server 10.0.1 for deployment.

Kindly help me to resolve the issue.

Thank you so much.

**Comment by olamy** [comment]
Hi
Do you have any sample project we could use to reproduce?
Are you using an embedded application or jetty distribution?
Do you have the same issue when using jetty 9,4.x?

Thanks
Olivier

On Sun, Aug 15, 2021 at 2:15 PM anishsharma91 ***@***.***> wrote:
>
> HTTP ERROR 500 org.apache.jasper.jasperException : line[3] column[0], The absolute URI : [http://www.springframework.org/tags] cannot be resolved in either web.xml or the jar files deployed with the application.
>
> This is the error showing on the screen while loading the application.
> I am including the spring 5 taglibs in my jsp which is not loading
>
> <%@ taglib prefix = "spring" uri ="http://www.springframework.org/tags" %>
>
> NOTE : The application was working fine before with spring 4 and jetty server 8...
> I have migrated the application to spring 5.3.2 and using jettty server 10.0.1 for deployment.
>
> Kindly help me to resolve the issue.
>
> Thank you so much.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Olivier

**Comment by joakime** [comment]
Perhaps you are being hit by this?
https://stackoverflow.com/a/4222768

What spring dependencies do you have in your new war file's WEB-INF/lib/ directory?

Make sure you have the `annotations` module enabled (if using the `jetty-home`/`jetty-base` concepts)

**Comment by anishsharma91** [comment]
Hi @olamy @joakime 
Thank you so much for your response.

This issue is fixed now. The problem was that the application was not able to load taglibs of spring using  uri ="http://www.springframework.org/tags"
so I downloaded the spring.tld file from the respective jar and placed to webapp/WEB-INF location and included the taglibs like this : <%@ taglib prefix = "spring" uri ="/WEB-INF/spring.tld" %>

As application have the jar available to using all the tags defined in spring.tld, The application is working fine.

Thank you for help.

**Comment by janbartel** [comment]
@anishsharma91 if the spring 5 jar is on the container's classpath, then you would need to set the `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern` with the name of the jar in order for jetty to know it contains tlds that need to be loaded - there is an example here: https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-javaserver-faces-taglibs.  If the spring 5 jar is included inside your WEB-INF/lib then there should be no need to do anything. Repeat - you should _not_ need to extract the taglib from the spring 5 jar.

**Comment by janbartel** [comment]
@anishsharma91 I'll close this issue for now - if you want to change your webapp to _not_ extract the taglibs, then please reopen and provide: where the spring 5 jar is located (on server classpath or WEB-INF/lib) and jetty log output with DEBUG enabled for `org.eclipse.jetty.webapp`.
