### ISSUE TITLE
Javax websocket api: Pong message handler called upon receipt of Ping message

### ISSUE THREAD

**Issue by dereszet** [eclipse/jetty.project#662]
In the class JsrEndpointEventDriver, the method "onPing(ByteBuffer buffer)" delegates to onPongMessage(Byteuffer buffer).
Because of that it is not possible for a user of the javax websocket api to differentiate between Pongs received in response to a Ping and incoming Ping messages, that the Endpoint responds to automatically (and therefore do not need to be handled manually). 
The JSR-356 API does not include any way to handle pings manually.

**Comment by joakime** [comment]
That is absolutely correct.

The JSR356 implementation handles control frames on its own.

Eg:
 * The implementation will automatically respond to PING with a PONG at the next Frame boundary.
 * The implementation will automatically respond to a remote CLOSE frame (if the local endpoint hasn't already started the Close Handshake itself with a `close()` call) after the last message frame in the outgoing queue (Frame fin==true).

The JSR356 Pong handling can be described as the following.

 * You can use `javax.websocket.Session.addMessageHandler(new MyPongHandler())` which implements `javax.websocket.MessageHandler.Whole<PongMessage>`
 * You can use `@OnMessage public void onPong(PongMessage pong)` if using an annotated Endpoint.
 * When a Pong Frame (opcode==10) is received, it notifies the above message  handlers.
 * When a Ping Frame (opcode==9) is received, it is automatically handled by the implementation by sending a Pong with the same payload as the Ping it just received.

As for the extra step that Jetty takes by exposing a received PING Frame via the same message handlers, that could be viewed as a violation of the JSR356 spec, and should be evaluated more closely.

**Comment by joakime** [comment]
This has been corrected in the work for Issue #207
