### ISSUE TITLE
Flakey infinispan session test on 9.4 CI

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#6626]
**Jetty version(s)**

9

**Description**

Infinispan session tests are not exiting cleanly and failing after 1h on CI.
See this [CI](https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x-6624-disable-ipv6-test/2/pipeline) timeout.
```

**Comment by janbartel** [comment]
@olamy  any ideas? I don't see those tests failing on the 9.4.x branch at all ...

**Comment by olamy** [comment]
@janbartel ? this one is 9.4 :)

**Comment by olamy** [comment]
it's strange because the logs says:
```
INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.106 s - in org.eclipse.jetty.server.session.ClusteredSessionScavengingTest

[INFO] 

[INFO] Results:

[INFO] 

[INFO] Tests run: 44, Failures: 0, Errors: 0, Skipped: 0
```
as if all the tests were executed.

**Comment by gregw** [comment]
@olamy i think it was a timeout after 1h. So no tests failed. It just didn't complete.

**Comment by olamy** [comment]
yup number of tests not correct

**Comment by janbartel** [comment]
I haven't seen this problem again on the CI system. I think it was some kind of hiccup in CI. I'm going to close this issue for now, but will re-open if it occurs again.
