### ISSUE TITLE
Does jetty-jaas-9.4.38.v20210224.jar supports LDAP communication using StartTLS ?

### ISSUE THREAD

**Issue by hugocabaco** [eclipse/jetty.project#6632]
**Jetty version**
jetty-jaas-9.4.38.v20210224.jar

**Java version**
openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)

**Question**
We are using jetty-jaas-9.4.38.v20210224.jar and we are having issues connecting to an LDAP server that only supports StartTLS as a security policy (so no unsecure nor ldaps is allowed).

We noticed that there are options like useLdaps="true" to use ldaps but there is no option for StartTLS.

If StartTLS is in fact supported, what configurations should we set on the ldap-loginModule.conf ?
From witch version of jetty-jaas StartTLS it is supported?
Are there any other parameters or java arguments to setup to make StartTLS connection to LDAP work?

**Comment by olamy** [comment]
actually it is not supported.
would you be interested to contribute or sponsor such new feature?

**Comment by sbordet** [comment]
This is actually supported by the JDK, see https://docs.oracle.com/javase/jndi/tutorial/ldap/ext/starttls.html.
