### ISSUE TITLE
A custom mimetype should be able to be excluded from gzip

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6637]
**9.4 onwards **

Currently, if a new mimetype is specified in web.xml it is not able to be excluded from the GzipHandler. It should be possible for custom mimetypes defined in web.xml to be able to be excluded from being gzipped.

Related to: #6545

**Comment by joakime** [comment]
I think this is a duplicate of issue #6544 

The fix and testcase are in PR #6550

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java#L827-L870

It was not backported to Jetty 9.4.x, as it has no ability to include/exclude by mime-type, that's a new feature introduced for Jetty 10.0.x

**Comment by janbartel** [comment]
@joakime ok, so then this needs to become a documentation exercise, as I don't see any info on how to exclude mimetypes (including ones that have been added from web.xml) from the GzipHandler.

**Comment by joakime** [comment]
Fixed in PR #6550
