### ISSUE TITLE
WebSocket handling of Connection: upgrade,close.

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6642]
**Jetty version(s)**
Jetty 10+

**Description**
In Jetty 9.4.x, there was a test for bad client `Connection` headers.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/FirefoxTest.java

This concept needs to be restored in a new testcase on the Jetty WebSocket rewrite.

Two test cases need to be tested and ensured that they work.

The "Firefox" case. of `Connection: keep-alive, Upgrade`

```
GET /socket/ HTTP/1.1
Host: example.com:8080
Upgrade: websocket
Connection: keep-alive, Upgrade
Sec-WebSocket-Key: 9Y7WzchJwKR72PHdKrf7Mg==
Sec-WebSocket-Protocol: chat
Sec-WebSocket-Version: 13
```

And the "iPhone" and "Proxy/Load Balancer" case of `Connection: close, Upgrade`

```
GET /socket/ HTTP/1.1
Host: example.com:8080
Upgrade: websocket
Connection: close, Upgrade
Sec-WebSocket-Key: 9Y7WzchJwKR72PHdKrf7Mg==
Sec-WebSocket-Protocol: chat
Sec-WebSocket-Version: 13
```

**Comment by lachlan-roberts** [comment]
@joakime what are we supposed to do in the case of `Connection: close, Upgrade`? 
Are we supposed to ignore the `close` part and keep the connection open to be used by websocket.

We don't even support this case in 9.4.

**Comment by joakime** [comment]
> @joakime what are we supposed to do in the case of `Connection: close, Upgrade`?
> Are we supposed to ignore the `close` part and keep the connection open to be used by websocket.
> 
> We don't even support this case in 9.4.

I'm not 100% sure what the behavior should be here.

On one hand, it wouldn't be too hard to argue that "close" is only for HTTP layer, once the connection is upgraded, the "close" behavior should no longer take effect.

On the other hand, the transition from HTTP to WebSocket is an HTTP Response with an upgraded connection. (the websocket handshake)

But I believe that's just a side effect of websocket on HTTP/1.1, is this HTTP response still a thing in HTTP/2?

@gregw what do you think?

**Comment by joakime** [comment]
You could argue that `Connection: closed` is also only for controlling HTTP persistence on HTTP/1.1, which an upgraded connection doesn't participate in anyway.
