### ISSUE TITLE
How Can modify header value in intial request in Request class  or HttpChannel in  Websocket server - Jetty11

### ISSUE THREAD

**Issue by ssk512** [eclipse/jetty.project#6645]
**Jetty version** :11

**Java version** :11

**Question**
How Can modify header value in intial request in Request class  or HttpChannel in Websocket server

**Comment by lachlan-roberts** [comment]
I'm assuming this is related to https://github.com/jetty-project/embedded-jetty-websocket-examples/issues/58, and you are trying to work around the fact that the client is sending `Connection: close, Upgrade` header which is closing the underlying connection after it has been upgraded to websocket.

I don't know how to workaround this other than removing the `close` from the header on the client side. I experimented with removing it with the `RewriteHandler` but its too late and the connection is still closed. @gregw any ideas?

**Comment by lachlan-roberts** [comment]
@ssk512 we are working on this for issue #6642 and have a PR up to fix this in Jetty-10/11 (see #6657).

**Comment by ssk512** [comment]
@lachlan-roberts  Thanks for update, please let me know once it ready

**Comment by lachlan-roberts** [comment]
This has been fixed in the current `10.0.x`/`11.0.x` branches and will be available in the next releases `10.0.7`/`11.0.7`.
