### ISSUE TITLE
request logs are not getting deleted

### ISSUE THREAD

**Issue by darsh221** [eclipse/jetty.project#665]
I'm trying  to setup log rotation and deletion for jetty request log.

I have following  jetty-requestlog.xml under jetty_base/etc

Haven't enabled the jetty request log module in the start.ini file.
I'm passing jetty-requestlog.xml as an argument start.jar. 
Logs are getting rotated every night but deletion is not happening

```
<Configure id="Server" class="org.eclipse.jetty.server.Server">
<Set name="RequestLog">
    <New id="RequestLog" class="org.eclipse.jetty.server.AsyncNCSARequestLog">
    <Set name="filename">/var/log/jetty/yyyy_mm_dd.request.log</Set>
      <Set name="append">true</Set>
      <Set name="extended">false</Set>
      <Set name="LogTimeZone">GMT</Set>
      <Set name="retainDays">1</Set>
    </New>
  </Set>
</Configure>
```

**Comment by sbordet** [comment]
How is this issue different from #664 ?

**Comment by darsh221** [comment]
Both are same.Sorry I accidentally created duplicate issue. Closed the other one.

**Comment by darsh221** [comment]
Hi, I tested this again and I see log files are getting deleted. If retainDays is set to 1 then, at any given time there will be 2 log files. One for the current day and other for last day.I somehow thought it will be just 1 log file.

**Comment by joakime** [comment]
You can always use the [`Slf4jRequestLog`](http://download.eclipse.org/jetty/9.3.10.v20160621/apidocs/org/eclipse/jetty/server/Slf4jRequestLog.html) implementation to emit request log lines as formal logging events on the slf4j logging stack (use any supported logging framework under it: logback, log4j, java.util.logging, etc).

From there you can configure the log file appending, rotation, filtering, compression, etc to your heart content.
