### ISSUE TITLE
Can debug logging be enabled at runtime?

### ISSUE THREAD

**Issue by dwoznicki** [eclipse/jetty.project#6650]
**Jetty version**
9.4.39.v20210325

**Java version**
openjdk version "11.0.11" 2021-04-20

**Question**
I'm encountering a very difficult to reproduce bug with my web server, and I'd like to be able to quickly turn on debug logging when it occurs (and then turn it back off again as the debug log tends to fill up the disk).

I've tried

```java
Map<String, Logger> loggers = Log.getLoggers();
for (Logger logger : loggers.values()) {
    logger.setDebugEnabled(true);
}
```

but the calls duly warn that `setDebugEnabled not implemented`. Is there another way I could turn debug logging on and off at runtime?

**Comment by olamy** [comment]
using jetty logger it's not possible. 
Maybe (not tested) if you use slf4j implementations such Log4j(1/2) or logback you can try those implementations specifics to change dynamically logging level.

**Comment by gregw** [comment]
The StdErrLog is a JMX MBean, so it should be possible to control logging via JMX... let me test....

**Comment by gregw** [comment]
If you run with JMX enable, you can use jconsole to access `org.eclipse.jetty.util.log:type=stderrlog,id=0` and set the `debugEnabled` attribute to true.
There are also java.util.logging mbeans, so you can also direct logging to jul and use their bean for more fine grained control.

**Comment by sbordet** [comment]
This is documented here:
https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-troubleshooting-logging

We appreciate feedback for the documentation, so if you think that section could be improved, let us know.

**Comment by olamy** [comment]
oh jmx is so magic :)

**Comment by joakime** [comment]
Jetty 10 logging is based on slf4j, and ships with it's own `jetty-slf4j-impl` which is also controllable via JMX at runtime.

**Comment by dwoznicki** [comment]
> This is documented here:
https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-troubleshooting-logging
>
> We appreciate feedback for the documentation, so if you think that section could be improved, let us know.

Aha, this is precisely what I was looking for (specifically, the "Enabling DEBUG Logging for SubPackages" section looks very promising). Here are some thoughts:

- This exactly addresses my problem, but I didn't know how to find it. This one is probably on me.
- I'm not really familiar with JMX, so looking at the docs, my initial reaction is that I wish there was a code snippet showing how to change the log level in Java (if it is indeed possible without jconsole).
- I don't see a similar section in the Jetty 9 documentation, so I'm guessing this is a new feature in 10/11. Time to upgrade :slightly_smiling_face:

**Comment by dwoznicki** [comment]
Okay, I think I've found a solution to my problem.

I attempted to change the log level using the JMX solution above, which required by to download and install the latest [`jetty-slf4j-impl`](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-slf4j-impl) JAR file. However, my project uses logback as the logging provider, so of course it didn't work because slf4j doesn't accept two logging backend implementations.

It was at this point that I realized that I could use logback to configure the Jetty loggers (as originally recommended by @olamy). For anyone who's curious, here's the relevant code snippet.

```java
// Imports
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.FileAppender;
import org.slf4j.LoggerFactory;

// Snippet
LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
// Use a different logging pattern for Jetty debug logs.
PatternLayoutEncoder encoder = new PatternLayoutEncoder();
encoder.setPattern("%d{ISO8601} %-5level [%thread] [%logger:%line] - %msg%n");
encoder.setContext(context);
encoder.start();
// Append debug logs /tmp/jetty-debug.log file.
FileAppender<ILoggingEvent> fileAppender = new FileAppender<>();
fileAppender.setName("jetty-debug-log-appender");
fileAppender.setFile("/tmp/jetty-debug.log");
fileAppender.setEncoder(encoder);
fileAppender.setAppend(true);
fileAppender.setContext(context);
fileAppender.start();                                                                      
// Change the logger name to "org.eclipse.jetty.http2", etc. for more fine grained control.
Logger logger = (Logger) LoggerFactory.getLogger("org.eclipse.jetty");
logger.addAppender(fileAppender);
// Prevent this logger from also appending logs to the root log file.
logger.setAdditive(false);
```
