### ISSUE TITLE
ServerUpgradeRequest.getCookies() can throws NullPointerException

### ISSUE THREAD

**Issue by EricBlanquer** [eclipse/jetty.project#6654]
https://github.com/eclipse/jetty.project/blob/b2c420a124392b3e79a6abf263ec00f51e387409/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java#L93

Hi,
request.getCookies() can be null and this code can throws a NullPointerException

**Comment by joakime** [comment]
Not a bug in Jetty 9.4.x

https://github.com/eclipse/jetty.project/blob/jetty-9.4.43.v20210629/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeRequest.java#L99-L117

https://github.com/eclipse/jetty.project/blob/526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeRequest.java#L99-L117

This exists as a bug in Jetty 10.x and Jetty 11.x

**Comment by joakime** [comment]
Opened PR #6655
