### ISSUE TITLE
ServerConnector.setPort doesn't exist

### ISSUE THREAD

**Issue by alex73** [eclipse/jetty.project#6664]
**Jetty version(s)**
Jetty 10

**Description**
From https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html :

// The clear-text connector.
ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory(httpConfig));
connector.setPort(8080);

**Comment by olamy** [comment]
Did you try to compile the code? 
Look at the javadoc here https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/server/ServerConnector.html 
It's an inherited method from `AbstractNetworkConnector` https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/server/AbstractNetworkConnector.html

**Comment by alex73** [comment]
I was not able to compile some hours ago, but it works now. Sorry, probably it was wrong import. Fixed
