### ISSUE TITLE
Enhance DebugHandler to catch use-after-recycle

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#670]
`DebugHandler` could be enhanced to wrap `HttpServletRequest` (the 3rd parameter to `handle()` not Jetty's `Request` object that is passed as 2nd parameter) in a way similar to what we do in `AsyncContextState` to catch those cases where the request is used after it is being recycled.

See also #660.

**Comment by gregw** [comment]
Note that DebugHandler is currently deprecated in favour of DebugListener.   I think that decision needs to be reviewed as debugging from a listener does appear to have some sequencing issues (with respect to other listeners) and also does not allow this kind of wrapping.

I think a combined approach may well be best.

**Comment by sbordet** [comment]
Perhaps still worth it to keep this open.
