### ISSUE TITLE
Allow logging configuration announcement to be programmatically disabled

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#672]
Currently, when you have logging enabled, it will announce the logging configuration on startup.

Eg: The default behavior (StdErrLog at INFO level)

```
2016-06-28 11:26:31.687:INFO::main: Logging initialized @381ms
```

Eg: configured for slf4j
```
138  [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog 
142  [main] INFO  org.eclipse.jetty.util.log - Logging initialized @429ms 
```

It would be nice if these announcement can be configured away for libraries that want to use jetty dependencies, but don't have the ability to dictate a logging framework (being as they are libraries).

**Comment by sbordet** [comment]
@joakime those lines are already emitted using the logging _implementation_, so I would just log those at DEBUG level. 

If one wants to know what implementation it is using, it just tunes the right logging category.

**Comment by joakime** [comment]
Adding `Log.getProperties()` method for generic usage to programmatically configure the `Log` before use, as well as a new logging property `org.eclipse.jetty.util.log.announce` (boolean) to enable/disable the announcement of logging configuration (defaults to true to maintain backward compat)

> Bonus: this property can also be specified in the `jetty-logging.properties` file

Usage:
```
Log.getProperties().setProperty("org.eclipse.jetty.util.log.announce", "false");
```

**Comment by gregw** [comment]
rather than true/false, should this property be a level?   Hmm makes no sense having it as a WARN.  Anyway just a thought.

**Comment by cowwoc** [comment]
Be sure to break backwards compatibility in a future release (use a DEBUG logging level instead) because having to stuff `Log.getProperties().setProperty("org.eclipse.jetty.util.log.announce", "false");` in a `static` block all over my code (main, test, etc) is rather annoying. I'd rather centralize it in a single place where I set my logging level. That configuration gets reused everywhere automatically.
