### ISSUE TITLE
Loglatency logs either 1 or 0

### ISSUE THREAD

**Issue by rushilgupta** [eclipse/jetty.project#674]
Hey guys,
I have been using NCSARequestLog to log requests that make it to jetty server. I am configuring jetty server as follows:
`
	
	{

		QueuedThreadPool qtp = new QueuedThreadPool( 12, 4 );

		_server = new Server( qtp );

		ServerConnector scc = new ServerConnector( _server );

		scc.setAcceptQueueSize( 2 );

		scc.setPort( port );
		_server.addConnector( scc );
		RequestLogHandler requestLogHandler = new RequestLogHandler();
		NCSARequestLog requestLog = new NCSARequestLog( logPath );
		requestLog.setLogLatency( true );
		requestLog.setRetainDays( 7 );
		requestLog.setAppend( true );
		requestLog.setLogTimeZone( "GMT" );
		requestLogHandler.setRequestLog( requestLog );
		_handlers.addHandler( requestLogHandler );
	}`
The issue is that in the logs latency is logged as either 0 or 1 (I am pretty sure response time is atleast 10 ms). Am I missing something?
I am using jetty9.1.0.

**Comment by gregw** [comment]
How are you measuring response time?  is that 10ms including the network?

The logged latency is just the time from when the request was first handled until handling is complete. For many trivial requests this is a very short time.    

Please re-open if you can definitely tell that it is getting it wrong.
