### ISSUE TITLE
https://github.com/eclipse/jetty.project/pull/6588#discussion_r683850125Also is the icb really the right object?  Surely it should be the buffer?   icb doesn't even have a reference to the buffer.

### ISSUE THREAD

**Issue by firoj07** [eclipse/jetty.project#6774]
Also is the icb really the right object?  Surely it should be the buffer?   icb doesn't even have a reference to the buffer.

_Originally posted by @gregw in https://github.com/eclipse/jetty.project/pull/6588#discussion_r683851012_

**Comment by firoj07** [comment]
https://github.com/eclipse/jetty.project/issues/6774#issue-994451301

**Comment by firoj07** [comment]
Do your job well and whatever it is, work with everyone's consent you think it is not

**Comment by lachlan-roberts** [comment]
Feel free to comment directly on PR #6588 if you have any comments or concerns regarding those changes.
