### ISSUE TITLE
Correct quickstart documentation

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#679]
The doc for quickstart  shows the use of the jetty-all-uber.jar.  However, this is probably not ideal because:  a) it contains some classes that a user does not need in their environment, but that will be discovered by quickstart and configured into the generated quickstart-web.xml (eg websocket)   b)  it does not contain any of the supporting classes for eg annotation scanning (asm) nor jsp.

**Comment by WalkerWatch** [comment]
@janbartel More than happy to get this updated. Based on #682 what is our recommended approach going forward for this?

**Comment by janbartel** [comment]
@WalkerWatch the jetty-all-uber.jar isn't recommended for use at all: it was purely to make references from the documentation work properly.

I think the best way to do it is as described in the section above it "Setting up Quickstart".  We could remove the "Preconfiguring Quickstart" section and replace it with some other sections covering other means of using jetty, eg embedded.  For that section, folks should use whatever build tool they're using with jetty  to invoke the PreconfigureQuickStartWar class.  That way, their tool should already be configured with the minimally correct set of dependencies for their needs.

You could also put a link in to the section on the jetty maven plugin's run:effective-web-xml goal, which is in fact doing a quickstart generation. However, there needs to be a caveat in there that the jetty maven plugin will have other stuff on its classpath (like websocket and jsp), which may not in fact be needed by the webapp.

**Comment by WalkerWatch** [comment]
@janbartel I've removed the section for now and will work on getting replacement pieces in.

**Comment by WalkerWatch** [comment]
Tracking updates on this in #896
