### ISSUE TITLE
Web fragment loading from directories does not work

### ISSUE THREAD

**Issue by phax** [eclipse/jetty.project#680]
I'm using embedded Jetty 9.3.10 and trying to load a web-fragment that is contained in a different project.
The classpath contains the other project as a directory and therefore it ends in the `MetaData._webInfClasses` member.
`MetaInfConfiguration.preConfigure` only checks the "container resources" and the "webInfJars" but not the "webInfClasses".

Please scan the webInfClasses for fragments as well.

My solution is to create an extended class for configuration:
```java
public class MetaInfConfigurationExt extends MetaInfConfiguration
{
  @Override
  public void preConfigure (final WebAppContext context) throws Exception
  {
    super.preConfigure (context);
    scanJars (context, context.getMetaData ().getWebInfClassesDirs (), false);
  }
}
```

**Comment by janbartel** [comment]
@phax  how are you running this? Is this with the jetty maven plugin? Or embedded, or with a distro? Or something else? I'd like to understand how this "project" is winding up as a dir on WEB-INF classes instead of WEB-INF lib.

**Comment by phax** [comment]
Hi!
When using Eclipse with the m2e plugin, it resolves Maven SNAPSHOT projects in the same Eclipse workspace with the current working directories and not with the latest JAR files. That's why the classpath contains their respective "target" directories (and for the other referenced projects the JAR files are loaded from the Maven repository path and not from `WEB-INF/lib`).

I'm using Jetty in embedded mode. See https://github.com/phax/ph-oton/blob/master/ph-oton-jetty/src/main/java/com/helger/photon/jetty/JettyStarter.java on how I start it.

I just it to test web applications standalone ion the fly".

Additionally I noted, that the web-fragments are only loaded, if I add all the JARs and directories into the "extra classpath" of the context.

hth

**Comment by janbartel** [comment]
@phax I think you should be able to use the ContainerIncludeJarPattern to control which jars and dirs from the equivalent of the container's classpath will be examined for fragments.  See http://www.eclipse.org/jetty/documentation/9.3.x/configuring-webapps.html#container-include-jar-pattern

BTW in your list of Configurations, you should put AnnotationConfiguration BEFORE JettyWebXmlConfiguration (not the cause of the problem here, but definitely not correct either).

regards
Jan

**Comment by janbartel** [comment]
Similar to issue #536.

**Comment by phax** [comment]
Thanks for the hints. I will investigate this :)

**Comment by phax** [comment]
Works fine - thanks for your help!

**Comment by facboy** [comment]
I still find that this doesn't work properly, in Metadata.resolve it first looks at the webInfJars resources, and then for each of those resources it looks for its fragment descriptors and processes them.  The containerIncludeJars are not in webInfJars, they are in containerResources and so the fragments are ignored.
