### ISSUE TITLE
Update Felix version

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6801]
**Jetty version(s)**
9.4.x, 10.0.x, 11.0.x

**Description**
We are currently using `org.apache.felix.framework` 6.0.3.
The current version is 7.0.1

Our felix maven plugins are also on odd/old versions that need review.

This is a major version update and will require some work.

**Comment by janbartel** [comment]
For jetty-10 and jetty-11:

Already up-to-date with org.apache.felix.framework 7.0.1.
org.apache.felix:maven-bundle-plugin is at 5.1.1, latest version is 5.1.2 - surely dependabot will find that.


For jetty-9.4:
org.apache.felix.framework is at 6.0.3, latest is 7.0.1
org.apache.felix:maven-bundle-plugin is at 3.5.1, latest version is 5.1.2

I'm not convinced of the utility of the test-felix-webapp (that uses the org.apache.felix.framework). All it does is start jetty and start an embedded felix instance, doesn't deploy anything to the felix instance nor interact with it in any way. All we are testing is that an embedded felix instance can be started from a webapp.

**Comment by joakime** [comment]
The `test-felix-webapp` exists because a weird felix and WebAppClassLoader interaction that can lead to a stackoverflow exception (from Issue #3700).

It happens because felix uses URL Protocol Handlers on the URL class to handle it's bundles, which causes a crazy catch-22 on the WebAppClassLoader.
