### ISSUE TITLE
Missing p2 repo for Jetty 10.0.x. This is needed for eclipse users with Eclipse platform v4.20. please publish it.

### ISSUE THREAD

**Issue by rrimmana** [eclipse/jetty.project#6817]
**Jetty version(s)**

**Java version/vendor** `(use: java -version)`

**OS type/version**

**Description**

**How to reproduce?**

**Comment by joakime** [comment]
See PR #6404

**Comment by joakime** [comment]
We don't create/manage the Eclipse P2 repositories you are using.

Those P2 repositories are managed by the Eclipse IDE folks for specific usage of the Help System within the Eclipse IDE.
(The help system doesn't need/use apache-jsp, osgi-boot, or jaspi to name a few of our artifacts)
The use of the P2 repositories at Eclipse is not for general purpose use by users.

Of note, the work on Eclipse Tycho and the build system means that even those P2 repositories are going away in the near future. 
In favor of using the same Global Repository System that many build systems (maven, gradle, ivy, kotlin, scala, grape, buildr, bazel, etc) currently use.
This what PR #6404 is bringing to the table.

You have 2 choices.

1. Build and maintain your own P2 repositories on your own infrastructure with what you need.
2. Migrate away from P2 to the new Tycho build techniques.
