### ISSUE TITLE
9.4.x upgrade maven-bundle-plugin 5.1.2 (or more)

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#6832]
The branch 9.4.x is still using 3.5.1 version of the plugin.
This update works with jdk11 and jdk17 but not with jdk 1.8

**Comment by joakime** [comment]
Is there a newer version of maven-bundle-plugin in the 3.x range we can use instead? (one still compatible with jdk 8)

**Comment by olamy** [comment]
nope it's 3.5.1 -> 4.0.0
