### ISSUE TITLE
HttpClient proxies (HttpProxy and Socks4Proxy) do not support authentication

### ISSUE THREAD

**Issue by brettwooldridge** [eclipse/jetty.project#684]
There appears to be no support for proxies that require authentication.  It would be great if ``ProxyConfiguration.Proxy`` defined username and password accessors, and if the provided implementations utilize them.

We're in the unfortunate position of having converted a large chuck of code from Apache HttpClient over to Jetty's, only to have the requirement come up for authentication.

**Comment by sbordet** [comment]
`HttpClient` does support proxy authentication, it is enough to add a `HttpProxy` with the URL of the proxy (not of the server).

We will definitely improve the documentation, but the feature is present.

**Comment by sbordet** [comment]
Documentation improved.
