### ISSUE TITLE
Reversed "sessionAttribute.isEmpty()" test in SecureRequestCustomizer prevents the SSLSession attribute from being set

### ISSUE THREAD

**Issue by Zalathar** [eclipse/jetty.project#685]
It looks like the code in [SecureRequestCustomizer](https://github.com/eclipse/jetty.project/blob/jetty-9.3.10.v20160621/jetty-server/src/main/java/org/eclipse/jetty/server/SecureRequestCustomizer.java) is trying to set the SSLSession attribute only if an attribute name is available, but instead it ends up setting the attribute only if the attribute name is empty.

**Comment by gregw** [comment]
hmmm obviously need a unit test for that!
