### ISSUE TITLE
Large amount of warn entries for "fill with unconsumed content" generated by Jetty

### ISSUE THREAD

**Issue by ssmogos** [eclipse/jetty.project#6866]
**Jetty version(s)**
9.4.39.v20210325

**Java version/vendor** `(use: java -version)`
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

**OS type/version**
Docker container with base image:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Description**
Single container was generating about 8k warn entries per second due to jetty. The service was still processing requests when this issue was happening.

**How to reproduce?**
Could not reproduce the problem. 
We noticed the issue happening in our cluster, taken thread dumps and exported metrics, then restarted the pod. Problem stopped happening after the restart.

***Attached thread dumps:***
[td1.txt](https://github.com/eclipse/jetty.project/files/7188050/td1.txt)

***Logged entries were***:
```
{"version":"1.0.0","timestamp":1631592487466,"deployment":"*****","environment":"qa","trcbltPartitionId":"****","instanceId":"****","service":{"name":"****","version":"1.80.0","hostname":"****-7994657dd4-q9zqk"},"log":{"thread":"dw-29100","message":"HttpConnection@c62b85e::SocketChannelEndPoint@7bcd3b41{l=/10.73.22.170:9080,r=/10.73.8.241:54204,OPEN,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}->HttpConnection@c62b85e[p=HttpParser{s=CLOSE,23254 of -1},g=HttpGenerator@3079cb8f{s=START}]=>HttpChannelOverHttp@74c3a240{s=HttpChannelState@611d706c{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=11,c=false/false,a=IDLE,uri=null,age=0} fill with unconsumed content!","level":"WARN","logger":"org.eclipse.jetty.server.HttpConnection"}}

{"version":"1.0.0","timestamp":1631592487466,"deployment":"*****","environment":"qa","trcbltPartitionId":"****","instanceId":"****","service":{"name":"****","version":"1.80.0","hostname":"****-7994657dd4-q9zqk"},"log":{"thread":"dw-28741","message":"HttpConnection@47dc2b28::SocketChannelEndPoint@79214264{l=/10.73.22.170:9080,r=/10.73.21.84:44258,OPEN,fill=-,flush=-,to=0/30000}{io=1/0,kio=1,kro=1}->HttpConnection@47dc2b28[p=HttpParser{s=CLOSE,23261 of -1},g=HttpGenerator@43e3a70b{s=START}]=>HttpChannelOverHttp@6e12113{s=HttpChannelState@118e4da0{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=18,c=false/false,a=IDLE,uri=null,age=0} fill with unconsumed content!","level":"WARN","logger":"org.eclipse.jetty.server.HttpConnection"}}
```

***Metrics***
```
"org.eclipse.jetty.util.thread.QueuedThreadPool.dw-admin.jobs":
        {
            "value": 0
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw-admin.jobs-queue-utilization":
        {
            "value": 0.0
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw-admin.size":
        {
            "value": 6
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw-admin.utilization":
        {
            "value": 0.6666666666666666
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw-admin.utilization-max":
        {
            "value": 0.0625
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw.jobs":
        {
            "value": 0
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw.jobs-queue-utilization":
        {
            "value": 0.0
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw.size":
        {
            "value": 301
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization":
        {
            "value": 0.016611295681063124
        },
        "org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization-max":
        {
            "value": 0.0048828125
        },

"counters":
    {
        "io.dropwizard.jersey.errors.EofExceptionWriterInterceptor.eof-exceptions":
        {
            "count": 0
        },
        "io.dropwizard.jetty.MutableServletContextHandler.active-dispatches":
        {
            "count": 0
        },
        "io.dropwizard.jetty.MutableServletContextHandler.active-requests":
        {
            "count": 0
        },
        "io.dropwizard.jetty.MutableServletContextHandler.active-suspended":
        {
            "count": 0
        }
    },

"io.dropwizard.jetty.MutableServletContextHandler.async-dispatches":
        {
            "count": 0,
            "m15_rate": 0.0,
            "m1_rate": 0.0,
            "m5_rate": 0.0,
            "mean_rate": 0.0,
            "units": "events/second"
        },
        "io.dropwizard.jetty.MutableServletContextHandler.async-timeouts":
        {
            "count": 0,
            "m15_rate": 0.0,
            "m1_rate": 0.0,
            "m5_rate": 0.0,
            "mean_rate": 0.0,
            "units": "events/second"
        }

``` 

We have not seen this problem again in any of our environments and also we did not have logs back enough to know when it started happening (to look into possible triggers).
Do you have any idea on what might have caused this problem? Maybe there is a possible fix in newer jetty version?

**Comment by joakime** [comment]
You have a server/servlet/endpoint that isn't reading all of the content being sent by the clients.

This is a bad thing, as you break the HTTP/1.1 connection persistence doing that.
You should read all of the content that is being sent on the HTTP Request level.
If you don't read the request content, the connection cannot remain persistent and MUST be closed (per spec).

For REST endpoints, you should set them up to read all of the content, even if the document (json, xml, etc) is technically closed or done.
Depending on your choice of REST library, and document parsing libraries, there are various ways to configure them to read to EOF (inputstream read to -1).
While in most cases the extra content is harmless whitespace, there are also bad clients that will accidentally send extra document data after the first document (this is a bug in the client), and there are also nefarious clients that will send extra content in the hopes of triggering some kind of request smuggling attack.  
Once you configure your REST server properly, these non-whitespace issues (bad clients and nefarious clients) will suddenly be highlighted for you in your logs (which you then need to address).

**Comment by joakime** [comment]
Version: 9.4.39.v20210325

You should also upgrade, as you are using a vulnerable version.
See: https://www.eclipse.org/jetty/security_reports.php

**Comment by ssmogos** [comment]
thanks a lot @joakime for the quick response. (we're in the process of updating jetty as well for the reasons that you mentioned).

We're using dropwizard 2.x and as far as I've tried to google this, I could not find options for such configuration. But I'm probably searching for the wrong thing.
Do you happen to have some examples/references at hand on how this is configured on some rest libraries? Also, any reference to a script/test that can be used to reproduce such issue? That would help us a lot to dig further into this issue.
