### ISSUE TITLE
Drop support for http2 drafts

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#689]
Remove support for the http2 drafts, or at least may them not supported by default.

**Comment by gregw** [comment]
I've done this in 9.4.x, but would like it reviewed in as much as should we totally remove support or just have it off by default?

**Comment by gregw** [comment]
@travisspencer I've made the concrete constructors public.  Thanks for the other code review.

**Comment by joakime** [comment]
Closing, as this seems completed.
