### ISSUE TITLE
Review `HttpField.contains(String)` for case insensitive behavior

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6892]
**Jetty version(s)**
9.4.x thru 11.0.x

**Description**
As part of the review of PR #6886 it was discovered that `HttpField.contains(String)` should probably not be case insensitive. (see https://github.com/eclipse/jetty.project/pull/6886#discussion_r713831344)

**Comment by gregw** [comment]
Also the contains methods in org.eclipse.jetty.http.tools.matchers.HttpFieldsMatchers#containsHeaderValue(java.lang.String, java.lang.String) need similar review and potentially have an exact match option added.

**Comment by gregw** [comment]
RFC 9110 defines case-sensitivity for header values on a case by case basis, although the majority are defined as case-insensitive (I can only see etags having a case sensitive specification). 
The javadoc of the contains method clearly states that it is case-insensitive, so this matches the most common usage.  Etags do not appear to use this method.
No further change is requuired.
