### ISSUE TITLE
No response of Magic from Http2 server, client still sends requests

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#6896]
9.4.43.v20210629

jdk1.8.0_261

What would be the behavior of Jetty client when it sends the MAGIC frame, but server does not respond with HTTP2 Settings frame in the initial handshake.

In our case, we can see a connection established at TCP level and client is trying to send requests on that connection.

Would the client wait indefinitely for the settings frame or will it retry after a certain timeout?

Below is the screenshot of snoops, server does not respond to magic:

<img width="773" alt="snoop" src="https://user-images.githubusercontent.com/17244992/134463744-5b6ce30d-78df-4b53-9c0c-49421d6f5e4e.png">

**Comment by sbordet** [comment]
We expect the server to reply correctly with the HTTP/2 server preface.
If that does not happen and the connection goes idle, the idle timeout on the client will kick in and close the connection.

**Comment by prateekkohli2112** [comment]
I read below statement in HTTP2 RFC:

### If the sender of a SETTINGS frame does not receive an acknowledgement within a reasonable amount of time, it MAY issue a connection error (Section 5.4.1) of type SETTINGS_TIMEOUT.

But it is not happening in Jetty client.

In case of idle timeout GOAWAY frame will be sent, but no SETTINGS_TIMEOUT frame.

**Comment by sbordet** [comment]
@prateekkohli2112 it's specified as a `MAY`, see https://datatracker.ietf.org/doc/html/rfc2119.

We do not do this timeout because we have another timeout, the idle timeout, that achieves the same: it eventually closes the connection.
