### ISSUE TITLE
Enable codeql on eclipse/jetty.project

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6925]
**Target Jetty version(s)**
All active branches

**Enhancement Description**
We should add a `.github/workflows/codeql-analysis.yml` to allow codeql to run against our active branches.

For example configuration see: https://github.com/github/codeql-action

Per an old (now closed) issue (https://github.com/github/codeql/issues/5235) the maven command line used for the codeql autobuild is ...

```
mvn clean package -f "pom.xml" -B -V -e \
  -Dfindbugs.skip \
  -Dcheckstyle.skip \
  -Dpmd.skip=true \
  -Denforcer.skip \
  -Dmaven.javadoc.skip \
  -DskipTests \
  -Dmaven.test.skip.exec \
  -Dlicense.skip=true \
  -Drat.skip=true
```

That should allow the codeql to run in about 15 minutes per github event (that we want to hook into).

**Comment by olamy** [comment]
https://github.com/eclipse/jetty.project/pull/6500
