### ISSUE TITLE
Jetty 9.4.x is in maintenance mode.

### ISSUE THREAD

**Issue by firoj07** [eclipse/jetty.project#6927]
Jetty 9.4.x is in maintenance mode.
It is taking bug fixes and security fixes at the moment, not new functionality.

Active branches for new functionality is Jetty 10.0.x and Jetty 11.0.x.

If you want Servlet 4.0 behavior you have to be using Jetty 10.0.x (which supports Servlet 4.0).
Jetty 9.4.x is for Servlet 3.1.0.

Also note that `javax.servlet.*` is dead, you should move to `jakarta.servlet.*` if you are doing new development.

_Originally posted by @joakime in https://github.com/eclipse/jetty.project/issues/6917#issuecomment-925995760_

**Comment by joakime** [comment]
Spam. Closing.
