### ISSUE TITLE
How Jetty handles class data sharing

### ISSUE THREAD

**Issue by abhishekm-egain** [eclipse/jetty.project#6934]
**Jetty version**
jetty-10.0.6 - 29 June 2021

**Java version**
OPENJDK 13.0.2

**Question**
We  are passing Class data sharing files with JVM Attribute:  -XX:SharedArchiveFile=c:\jsa\ApplicationClassData.jsa while starting the jetty.  We noticed that able to load the classes from the JSA file. 
We are trying to follow the jetty code, which is responsible to use JSA File. 
Can someone please provide some pointers for the same.

Thanks in advance.

**Comment by sbordet** [comment]
I'm afraid is it not clear what you are doing, nor what you are trying to achieve.

Jetty is not responsible to use the JSA file. The JVM loads the JSA file.

**Comment by abhishekm-egain** [comment]
Hi @sbordet , 

Thanks for your response. trying to re-phrase the question.
While starting jetty server, we are using following command.

### With Jetty: 
java -XX:SharedArchiveFile=c:\jsa\ApplicationClassData.jsa -jar {JETTY_HOME}\start.jar --lib=c:\jars\main.jar

- main.jar has references of other jars in its manifest file.
- ApplicationClassData.jsa contains the references of classes from all jars (including the classes from jars in manifest)  
 
**Observation:** In this case, jvm is able to load the all classes from the jsa file.

### Without Jetty
when i am using same approach in standalone JVM invocation,
 java -XX:SharedArchiveFile=c:\jsa\ApplicationClassData.jsa -classpath c:\jars\main.jar  com.example.MainClassFromLib
**Observation:** in this case, JVM is **NOT** loading the classes from jsa file.
 
To ensure that, in standalone JVM can also successfully load the files from JSA, want to understand, how jetty is managing to load the jsa file successfully.
I assume that Jetty is loading the --lib in different way, in comparison to -classpath attribute of jdk. 
Want to understand, how Jetty is using --lib attribute, how main.jar and other jars from manifest are used in jetty.

Hope, that clarifies , what we are trying to achieve.


Thanks

**Comment by sbordet** [comment]
Sorry, I still don't understand.

If everything works with Jetty, then great.

The other case without Jetty we have no idea what classes you use and what you are doing, so we cannot help.

**Comment by joakime** [comment]
Note that `-jar {JETTY_HOME}\start.jar` could fork a new JVM depending on your configuration in your `${jetty.base}`.
In the working case you might _not_ have a `-XX:SharedArchiveFile` argument actually present on the JVM that is in use.

**Comment by joakime** [comment]
Make sure you always use `-Xshare:on` with `-XX:SharedArchiveFile=<path>` and don't leave it at "auto", that way you'll discover issues with your JVM startup faster.
You can also check the flags in use by the running JVM (using the pid of the JVM) to know what's actually in use (`jinfo -flags <pid>`), this result might surprise you.

Anyway, this doesn't seem to be a Jetty issue, so I'm going to close this issue.
