### ISSUE TITLE
Deprecate LocalConnector.getResponses() in favor of using .getResponse()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#695]
The current implementation of `LocalConnector.getResponses()` does a few hokey things related to detecting when a connection is done / closed / no more requests.

The better `.getResponse()` method is simpler and doesn't contain this extra logic that is slowing down tests and producing rogue errors.

**Comment by gregw** [comment]
this is ongoing replacement of a deprecated API.  No need for an open issue.
