### ISSUE TITLE
Bundle-RequiredExecutionEnvironment of org.eclipse.jetty.alpn.api so limit

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#702]
bundle org.eclipse.jetty.alpn.api at latest version 1.1.2.v20150522 have value of Bundle-RequiredExecutionEnvironment is J2SE-1.7
I can't find out this environment when use eclipse. so if i set my run-time environment to JavaSE-1.7 or JavaSE-1.8 both isn't satisfied to J2SE-1.7
please also add JavaSE-1.8, J2SE-1.7 to RequiredExecutionEnvironment

**Comment by sbordet** [comment]
Reassigning to OSGi sensei @janbartel.

**Comment by janbartel** [comment]
@sbordet I'm assigning this issue back to you for some info:

This is still the repo for the alpn-api, correct?: https://git.eclipse.org/c/jetty/org.eclipse.jetty.alpn.git/tree/pom.xml

The compiler plugin needs to be updated to 1.8, correct?

What's the min version that the enforcer plugin needs to be updated to?

Or does this project need to be branched to maintain a jdk1.7 version, and make master jdk1.8?

Assign this issue back to me when you've supplied the info and I will also update the manifest generating bits (for the correct minimum execution environment, and the copyright message too).

**Comment by sbordet** [comment]
@janbartel, the repo for ALPN-API is not at Eclipse, it's https://github.com/eclipse/jetty.alpn.api.

The Maven Compiler Plugin configuration can be updated to 1.8, since ALPN is not supported for JDK 7, so no need to make branches either.

**Comment by janbartel** [comment]
alpn-api manifest updated and released as 1.1.3.v20160715

I will also update jetty-9.3 and above.

**Comment by janbartel** [comment]
Reassigning back to Simone:  I released alpn-api 1.1.3.v20160715.

Looks like we need to update and rerelease the boot jar project and also update the main jetty pom.xml with the new version of both the alpn-api and the boot jar: I don't know what version of the boot jar goes with what version of the jdk, so can you do both of those things?

**Comment by sbordet** [comment]
@hieplq @janbartel now that I think of this, I am a bit confused about why this change was needed.

ALPN-API is a library that can be referenced for compilation, but always in scope `provided`.
At runtime the `alpn-api-<version>.jar` is never actually referenced because it is shaded into `alpn-boot` and in the bootclasspath, so it's pretty much like a JDK class.

**Comment by hieplq** [comment]
@sbordet, you are right. i can run from eclipse without this plug-in. thanks for figure out.

**Comment by hieplq** [comment]
before i have to active this bundle, 
it's my wrong solution for issue https://github.com/eclipse/jetty.project/issues/263
now everything is ok. thanks again, 
you can help me close this issue if you see it isn't need to fix.

**Comment by sbordet** [comment]
@hieplq I don't understand if you are ok _before_ or _after_ the change that @janbartel did.

@janbartel is your change worth to keep ? Is it a correct change anyway, even though perhaps not needed ? If so, I'll roll it in the next ALPN.

**Comment by hieplq** [comment]
before i use 9.3.7 and i encounter issue #263 
i get a wrong solution by active alpn.api, and modify it to export
after janbartel fixed  #263, everything can work well without active alpn.api (because now jetty-alpn-server can get package from jetty-osgi-alpn)
but i don't know it, i still active alpn.api, so i get issue report here.
now i just inactive alpn.api to get everything correct.

**Comment by sbordet** [comment]
@janbartel can you please answer my question above ?

**Comment by janbartel** [comment]
Well, if it's true that alpn requres jdk1.8, then the changes to the manifest are useful.

**Comment by hieplq** [comment]
sorry for comeback this issue.
i convert my project to use tycho and i get issue with this plugin.

tycho said:

> [ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/hieplq/.m2/repository/p2/osgi/bundle/org.eclipse.jetty.alpn.api/9.3.8/org.eclipse.jetty.alpn.api-9.3.8.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'J2SE-1.7' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/hieplq/.m2/repository/p2/osgi/bundle/org.eclipse.jetty.alpn.api/9.3.8/org.eclipse.jetty.alpn.api-9.3.8.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'J2SE-1.7'
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

i guess J2SE-1.7 is incorrect value, it should is JavaSE-1.7

**Comment by hieplq** [comment]
this is list of supported environment
http://wiki.eclipse.org/Execution_Environments#Standard_Execution_Environments

**Comment by joakime** [comment]
Where did you get alpn-api 9.3.8 from?
There's no such release ...
http://central.maven.org/maven2/org/eclipse/jetty/alpn/alpn-api/

Also, any Jetty 9.3.x series artifact would be Java 8+ anyway.

**Comment by janbartel** [comment]
@hieplq  the changes I did for #263 are only applicable from 9.3.9 onwards. In any case, you shouldn't need the alpn-api, as it should be supplied by the boot jar.  Try again using jetty-9.3.9 artifacts, and a proper dependency on the boot jar. Take a look at the osgi alpn unit test to see how to set that up:  https://github.com/eclipse/jetty.project/tree/jetty-9.3.x/jetty-osgi/test-jetty-osgi

**Comment by hieplq** [comment]
sorry it's my fault. i use old version modify by me.

but i find out same issue for jetty-schemas 4.0.0

it have "Bundle-RequiredExecutionEnvironment: J2SE-1.7" it should is JavaSE-1.7

**Comment by janbartel** [comment]
@hieplq  actually you don't deploy the jetty-schemas bundle in osgi. Use instead the http://central.maven.org/maven2/org/eclipse/jetty/toolchain/jetty-osgi-servlet-api/4.0.0/jetty-osgi-servlet-api-4.0.0.jar, which contains the schemas AND the api classes.  That's listed in the doco for using jetty in osgi here: https://www.eclipse.org/jetty/documentation/9.4.8.v20171121/framework-jetty-osgi.html.

I'll fix up the jetty-schemas bundle just-in-case.

BTW if you notice any other problems with other jars, please open a fresh issue ;)
