### ISSUE TITLE
Lots of Session tests seem to be flaky.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#7034]
**Description**
Lots of Session tests seem to be flaky, particularly the "remote" tests.
Here are some examples I have collected after looking back though some recent test failures:

**RemoteClusteredInvalidationSessionTest, RemoteClusteredSessionScavengingTest, RemoteInfinispanSessionDataStoreTest, RemoteInfinispanSessionDataStoreTest**
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-7000/3/tests
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-7029/2/tests

**CachingSessionDataStoreTest**
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-6954/8/tests

**org.eclipse.jetty.server.session.infinispan.RemoteQueryManagerTest**
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-10.0.x/1137/tests
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-7028/2/tests

**Comment by janbartel** [comment]
The CachingSessionDataStoreTest was some kind of transient docker problem with ports:

> 2021-10-24 22:05:11.522:INFO :memcached:main: Creating container for image: memcached:1.6.6
> 2021-10-24 22:05:11.557:INFO :memcached:main: Starting container with ID: 9f14f69286385bbb245c809c4beeb5f03e0869d5720ccca80a88f4bd7378f26a
> 2021-10-24 22:05:12.032:INFO :memcached:main: Container memcached:1.6.6 is starting: 9f14f69286385bbb245c809c4beeb5f03e0869d5720ccca80a88f4bd7378f26a
> 2021-10-24 22:05:12.237:ERROR:memcached:main: Could not start container
> org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [53732] should be listening)

@olamy is there something that could be improved in the test-container setup for memcached?

For the other tests, they are all remote infinispan session tests.  These seem to have become a little flakey since the upgrade to infinispan and or docker test containers.  I will take a closer look into them.

**Comment by olamy** [comment]
I need to review some code because not sure we cleanup correctly resources.
I will try to change some k8s setup as well.

**Comment by janbartel** [comment]
See #7066

**Comment by janbartel** [comment]
Fixed via #7066

**Comment by olamy** [comment]
still happening

**Comment by janbartel** [comment]
Attaching relevant log files from a local successful run vs a failed jenkins run. Note the warnings from infinispan about losing contact with a node just prior to the test failure. This failure is never seen in a local environment without jenkins/kubernetes etc.

[infinispan-jenkins-fail.txt](https://github.com/eclipse/jetty.project/files/7550557/infinispan-jenkins-fail.txt)
[infinispan-local-success.txt](https://github.com/eclipse/jetty.project/files/7550558/infinispan-local-success.txt)

**Comment by olamy** [comment]
@janbartel see #7122
