### ISSUE TITLE
Can't run jdeps

### ISSUE THREAD

**Issue by brunoborges** [eclipse/jetty.project#7044]
**Jetty version(s)**
11.0.7

**Java version/vendor** `(use: java -version)`
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Microsoft-26987 (build 17+35)
OpenJDK 64-Bit Server VM Microsoft-26987 (build 17+35, mixed mode, sharing)

**OS type/version**
Linux/Ubuntu (Focal)

**Description**
jdeps fails with the following output, when analyzing a jar-with-dependencies of a hello world Jetty app:

```bash
$ jdeps --print-module-deps --ignore-missing-deps target/jetty11-1.0-SNAPSHOT-jar-with-dependencies.jar 
Exception in thread "main" java.lang.module.FindException: Module org.slf4j not found, required by org.eclipse.jetty.server
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```

**How to reproduce?**
Source code available at:  https://github.com/brunoborges/jetty-11-bug-jdeps

**Comment by sormuras** [comment]
My intial guess: `jetty11-1.0-SNAPSHOT-jar-with-dependencies.jar` contains a module descriptor named `org.eclipse.jetty.server` that in turn contains a directive reading `requires org.slf4j;`. And module `org.slf4j` is not observable.

- Should `--ignore-missing-deps` bypass this? Perhaps.
- What happens if you provide `org.slf4j` via `--module-path` to `jdeps`?

**Comment by brunoborges** [comment]
`org.slf4j` is a required transitive package: https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-server/src/main/java/module-info.java#L18

Not sure how to test the second part.

**Comment by sormuras** [comment]
Try s/t like: `jdeps --module-path PATH/TO/slf4...jar[:|;]OTHERS --print-module-deps ...`

**Comment by sormuras** [comment]
Running `mvn verify` on @brunoborges reproducer repo https://github.com/brunoborges/jetty-11-bug-jdeps and then:

`java --module-path target --describe-module org.eclipse.jetty.server`

yields:

```
org.eclipse.jetty.server@11.0.7 file:///workspaces/jetty-11-bug-jdeps/target/jetty11-1.0-SNAPSHOT-jar-with-dependencies.jar
exports org.eclipse.jetty.server
exports org.eclipse.jetty.server.handler
exports org.eclipse.jetty.server.handler.gzip
exports org.eclipse.jetty.server.session
requires org.eclipse.jetty.jmx static
requires org.slf4j transitive
requires java.base mandated
requires jetty.servlet.api transitive
requires org.eclipse.jetty.http transitive
requires java.sql static
requires java.naming static
qualified exports org.eclipse.jetty.server.handler.jmx to org.eclipse.jetty.jmx
qualified exports org.eclipse.jetty.server.jmx to org.eclipse.jetty.jmx
contains org.eclipse.jetty
contains org.eclipse.jetty.server.resource
```

**Comment by mlchung** [comment]
`requires transitive` is not an optional dependency at runtime; it's implied readability.   Hence, since slf4j cannot be found, so the module resolution fails.

**Comment by sormuras** [comment]
Are all the following modules shadowed into the `jetty11-1.0-SNAPSHOT-jar-with-dependencies.jar` file?

```
requires org.slf4j transitive
requires jetty.servlet.api transitive
requires org.eclipse.jetty.http transitive
```

If yes, you need to remove those from the module descriptor.

**Comment by brunoborges** [comment]
@sormuras I don't know if they are or not. I'd have to dig in. But I was also hoping folks from jetty team could take a look at this.

**Comment by sbordet** [comment]
I have to say that I'm at a loss at understanding what the problem is...

The `org.eclipse.jetty.server` module declares `requires transitive org.slf4j`. That should be enough for `jdeps`.

@brunoborges can you simplify your project to not use `jar-with-dependencies` and a proper `module-info.java`?
Not sure what you're trying to accomplish with your project?

**Comment by sormuras** [comment]
That are good points and questions, Simone.

What-ever Bruno is up to, I think that `jetty11-1.0-SNAPSHOT-jar-with-dependencies.jar` shoud not (read: must not) contain a `module-info.class` at all. Assuming that it contains all required 3rd-party deps within itself, there's no need to require any external module and having a module descriptor in such an uber-JAR only confuses users and tools.

**Comment by janbartel** [comment]
If you look at the uber jar that is built by this project, it contains this file:

` inflated: META-INF/versions/9/module-info.class`

If you look at the contents of that module-info you get:

```Compiled from "module-info.java"
module org.slf4j@2.0.0-alpha5 {
  requires java.base;
  exports org.slf4j;
  exports org.slf4j.spi;
  exports org.slf4j.event;
  exports org.slf4j.helpers;
  uses org.slf4j.spi.SLF4JServiceProvider;
}
```

This is the module-info from the slf4j-api jar, which is a multi-version jar.

The assembly plugin should either skip it or be configured not to copy it into the uber jar.
