### ISSUE TITLE
`test-keystore.p12` is no longer packaged in jetty-home

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7062]
**Jetty version(s)**
10.0.7

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**

When enabling the `test-keystore` module, the actual test keystore is not put into place.
In fact, it's not even present in the `jetty-home` artifact to be able to be put into place.

The `test-keystore.mod` refers to it like this ...

https://github.com/eclipse/jetty.project/blob/da8a4553af9dd84080931fa0f8c678cd2d60f3d9/jetty-keystore/src/main/config/modules/test-keystore.mod#L24-L29

The file does exist, and is in the appropriate `src/main/config` tree.

https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/config/modules/test-keystore/test-keystore.p12

**How to reproduce?**

```
[bases]$ mkdir ssl10test
[bases]$ cd ssl10test/
[ssl10test]$ java -jar ../../jetty-home-10.0.7/start.jar --add-modules=https,test-keystore
INFO  : mkdir ${jetty.base}/start.d
INFO  : server          transitively enabled, ini template available with --add-module=server
INFO  : logging-jetty   transitively enabled
INFO  : test-keystore   initialized in ${jetty.base}/start.d/test-keystore.ini
INFO  : resources       transitively enabled
INFO  : https           initialized in ${jetty.base}/start.d/https.ini
INFO  : ssl             transitively enabled, ini template available with --add-module=ssl
INFO  : threadpool      transitively enabled, ini template available with --add-module=threadpool
INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-jetty
INFO  : logging/slf4j   dynamic dependency of logging-jetty
INFO  : bytebufferpool  transitively enabled, ini template available with --add-module=bytebufferpool
INFO  : mkdir ${jetty.base}/resources
INFO  : copy ${jetty.home}/modules/logging/jetty/resources/jetty-logging.properties to ${jetty.base}/resources/jetty-logging.properties
INFO  : mkdir ${jetty.base}/lib/bouncycastle
INFO  : copy /home/joakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.62/bcpkix-jdk15on-1.62.jar to ${jetty.base}/lib/bouncycastle/bcpkix-jdk15on-1.62.jar
INFO  : copy /home/joakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.62/bcprov-jdk15on-1.62.jar to ${jetty.base}/lib/bouncycastle/bcprov-jdk15on-1.62.jar
INFO  : Base directory was modified
[ssl10test]$ tree -F
.
├── lib/
│   └── bouncycastle/
│       ├── bcpkix-jdk15on-1.62.jar
│       └── bcprov-jdk15on-1.62.jar
├── resources/
│   └── jetty-logging.properties
└── start.d/
    ├── https.ini
    └── test-keystore.ini

4 directories, 5 files
```

Notice that `etc/test-keystore.p12` is missing.

**Comment by lachlan-roberts** [comment]
@joakime the `test-keystore` module generates a test keystore when the server is started and deletes on exit. It uses the properties from the ini file to generate the keystore.

I just tested this and it is still working as expected.

**Comment by janbartel** [comment]
Closing the issue as according to @lachlan-roberts everything is working as expected.

**Comment by joakime** [comment]
Reopening, as we should delete the file in source ...

https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/config/modules/test-keystore/test-keystore.p12
