### ISSUE TITLE
SslContextFactory: newSslServerSocket/newSslSocket/doStart are not customized

### ISSUE THREAD

**Issue by ramoas** [eclipse/jetty.project#708]
In Jetty 9. Just compare them to the method "customize(SSLEngine sslEngine)."

Yes, the missing params can be set by the caller on the socket after each call returns, but I think consistency is expected and warranted.

From history, it looks like these two functions have been inconsistent with customize ever since customize was changed to use SSLParameters when Java 1.7 support was dropped.

**Comment by sbordet** [comment]
What "missing params" are you referring to ? 

Can you make an example of what does not work, what is the expected result you would like, and what is the result you get instead ?

We know that ciphers order is respected, otherwise HTTP/2 will not work.

**Comment by ramoas** [comment]
I am not using HTTP/2 yet.  Have you tested cipher order with code that uses SslContextFactory and vanilla HTTPS?

Look at references to _useCipherSuitesOrder in SslContextFactory.java: https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java

Other than the getters/setters, notice that _useCipherSuitesOrder is only read in customize:
https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1578

customize is only called directly by these two newSSLEngine variants:
(1) https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1521

(2) https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1539

Thus, if code does not call customize or set the configuration separately, then the underlying SSL context will not be configured to honor cipher order as well as the other parameters being set in customize, namely endpoint identification and SNI matchers:
https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1577-L1584

newSslServerSocket does not call customize or set the configuration separately:
https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1467-L1487

newSslSocket does not call customize or set the configuration separately:
https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1489-L1506

Hence, depending on whether code uses SSLEngine or newSslServerSocket and/or newSslSocket, you get different SSL configuration / behavior.  This divergence in functionality was introduced in this commit:
https://github.com/eclipse/jetty.project/commit/c5e4abd792e7ed3f5e086d9835b25c5b93afe3d5

I maintain this divergence is not intended, let alone desirable, and should therefore be corrected.  If I go through the trouble of configuring the SslContextFactory, then I expect all the SSL objects produced by the factory to be consistently configured regardless of whether I use the engine or socket production methods.

Additionally, I just realized that doStart has recently been broken in this commit:
https://github.com/eclipse/jetty.project/commit/bd27e7d2d480949b32ad6abfbda0c24e6042c1e3

Previously, doStart would call newSSLEngine, which would call customize as noted above, resulting in honoring configuration like cipher order.  Now, however, the context is being created directly in doStart; thus, the other configuration will not be set on the underlying SSLContext.  I can create a separate issue for doStart if you prefer, but the theme of the complaint is the same.

I suggest re-factoring the code so that doStart / newSSLEngine / newSslServerSocket / newSslSocket call a common function like customize so that the SSL configuration can all be done in one place.  That way, the various methods will not accidentally diverge if/when additional configuration is introduced in the future.

BACKGROUND: I am coming from Jetty 8 (w/Java 8 and an OSGI container), and I had to extend SslContextFactory in order to override the customize function in order to honor things like cipher order for vanilla HTTPS.  I will eventually be upgrading to Jetty 9, so I wanted to understand its behaviors to know what code I can throw out.  In reviewing the code, I noticed all these discrepancies.

Hopefully, that's clearer.  If not, let me know, and I'll try again.

**Comment by gregw** [comment]
@ramoas thanks for the detail explanation.  Digesting that now....

**Comment by ramoas** [comment]
@gregw I just saw that you changed the title.  Please note that doStart has also lost its customization.  Are you going to create a separate issue for doStart?  If not, I suggest changing the title to "SslContextFactory: doStart / newSslServerSocket / newSslSocket are not customized"

**Comment by gregw** [comment]
@ramoas,  I'm just building/testing with a patch that introduces customize(SslParameters) which is used everywhere.    I just included doStart in the title... although it is a little different as the usage in do start derives some of the parameters that are subsequently set in customize, I have made customize aware of that.        I'll commit after a clean build.

**Comment by ramoas** [comment]
@gregw Sounds good.  That's inline with what I was thinking.

**Comment by gregw** [comment]
hmmm full build failed, but with a known unrelated instability.    So please review the pushed fix.

**Comment by ramoas** [comment]
@gregw, I've been reviewing.

The only line I do not understand is in doStart:
https://github.com/eclipse/jetty.project/blob/45bbde408faf0a2b1fcd9f847f591c1c312f502c/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L403

I just added a note on that line.  Basically, shouldn't that line come after selecting the protocols and ciphers?  If not, then I don't see how the SSLContext in doStart will end up with customized protocols and ciphers.

I would expect there could be some unit tests failures depending on the test coverage.  For example, newSslServerSocket / newSslSocket could now fail with different cipher order.

**Comment by ramoas** [comment]
@gregw I added another note to the commit.  In doStart, you can do away entirely with creating an SSLEngine and just grab the enabled ciphers / protocols from context.getDefaultSSLParameters() and the available ciphers / protocols from context.getSupportedSSLParameters().

**Comment by ramoas** [comment]
@gregw See notes in https://github.com/eclipse/jetty.project/commit/35a64828fb0967baabb3280ca1e046ce828999a6 for one bug fix and two minor suggestions.

See the new note in https://github.com/eclipse/jetty.project/commit/45bbde408faf0a2b1fcd9f847f591c1c312f502c for some suggestions regarding unit testing.

Thanks for diving into this.
