### ISSUE TITLE
jetty disable sslv3

### ISSUE THREAD

**Issue by sli4** [eclipse/jetty.project#709]
when I configure https for my jetty server, I met a problem about sslv3 (ERR_SSL_VERSION_OR_CIPHER_MISMATCH). And I configure the jetty-ssl-context.xml according to the official reference (http://www.eclipse.org/jetty/documentation/current/configuring-ssl.html), but the sslv3 problem still exist. Please help me to solve the problem ! Thanks very much!

**Comment by joakime** [comment]
Have you enabled SSLv3 on your JVM? (In Java 8 it is disabled by default)

**Comment by lkoniecki** [comment]
Can you post you Jetty configuration?

**Comment by SatyaCMarivada** [comment]
Hi, Did you happen to find a solution? I am facing the same issue. Thanks

**Comment by joakime** [comment]
SSLv3 is disabled by default on Jetty and is also disabled in the OpenJDK JVM as well.  

As of Jan 1, 2017.  All SHA0 and SHA1 ciphers (needed by SSLv3) are now also rejected by all browsers.

Closing this issue, as there are many things now disabling SSLv3

Test your setup with https://www.ssllabs.com/ssltest/ and you'll see the true and complete state of your configuration.
