### ISSUE TITLE
Add SOCKS5 support

### ISSUE THREAD

**Issue by ghost** [eclipse/jetty.project#7091]
**Target Jetty version(s)**
We are currently using the jetty websocket 10 using SOCKS4 proxy.
**Enhancement Description**
We need to support in the feature websocket via SOCKS5 proxy. 
Would it be possible to have the SOCKS5 version in the next release of jetty?

**Comment by joakime** [comment]
The spec for SOCKS5 can be found at https://datatracker.ietf.org/doc/html/rfc1928

This would be a low priority for us at the moment, as we are focused on HTTP/3 and Jetty 12 with Servlet 6.

We'll happily take a PR to add SOCKS5 support to Jetty 10.
