### ISSUE TITLE
Timeout with Expect 100 continue when using ProxyServlet

### ISSUE THREAD

**Issue by dejpec** [eclipse/jetty.project#7117]
**Jetty version**
9.4.43, 9.4.44

**Java version**
OpenJDK 11

**OS type/version**
Windows 10

**Description**
I am using embedded jetty version 9.4.43 and use ProxyServlet to reverse proxy requests to the server.
A servlet behind this proxy which reads all lines causes a timeout when Expect: 100-continue is set.
If servlet reads all bytes binary it works. Whithout reverse proxy the servlet works also.
This [Example](https://github.com/dejpec/dejpec/blob/main/jetty_problems/Expect100Timeout.java) shows the problem.

**Comment by sbordet** [comment]
Thank you for the reproducer, it is a bug: since we recycle the reader, we don't execute the code to send the 100 continue for the second request.
