### ISSUE TITLE
Jetty Server stops responding after some time

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#7120]
**Jetty version(s)**
9.4.43

**Java version/vendor** `(use: java -version)`
1.8.261

**OS type/version**
Linux

**Description**
Jetty server gets stuck for some time and recovers automatically and gets stuck again.

Please find attached the thread dump at the time of the issue.

**SBI F-E-2081-pool -> Jetty server threads**

**How to reproduce?**
Usually happens when we send requests to Jetty server from jetty client having many threads(16000).

[IssueThreadDump.txt](https://github.com/eclipse/jetty.project/files/7543809/IssueThreadDump.txt)

**Comment by sbordet** [comment]
What's your server-side thread pool configuration?
What's your server-side idle timeout?

You have 190 server threads blocked in writes.

This means that the client is not reading what the server is sending, so now you have to wait the idle timeout (or the client to read) to unblock those blocked writes.

16000 threads on the client is probably an indication that you're doing some load test, and doing it wrong: such an overloaded client cannot cope with the load that the server is sending back.

Can you also take a server *dump* as explained here: https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-server-dump.

**Comment by prateekkohli2112** [comment]
What's your server-side thread pool configuration? - Max threads 200, default values for other parameters
What's your server-side idle timeout? - default

I think what you mentioned about client overloading was right as we can see **TCP Zero Window** packets from client side in our snoops.
But we can also observed some **TCP Zero Window** from server side and all the threads in server are now in waiting state.

Attaching snoops and server dump for your reference.

If our theory of client overloading is correct and it cannot receive more packets from server because the TCP window is zero, we assume that client does not enough n/w threads to clear the TCP buffer. Is our assumption correct and how should we configure it to prevent this overloading?

I would also like to mention that we are debugging a latency scenario from server where a 7 sec latency is possible in a short burst.
[Server Dump.txt](https://github.com/eclipse/jetty.project/files/7607545/Server.Dump.txt)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/17244992/143555259-be5c6fab-f4d9-43c4-8cfa-cc3d7f57538e.png)

**Comment by sbordet** [comment]
@prateekkohli2112 this seems just a badly setup load test.

You have configured each HTTP/2 session with 2500 streams, which is just an unrealistic scenario. 
You will never configure a server like that.
Whatever number you get out of it, it will be completely meaningless, as real world scenarios will be entirely different.

Furthermore, with 2500 streams per connection, you are likely to cause TCP congestion, like you found in the network trace, and the server dump shows that there is no problem with HTTP/2 flow control, as you have also enlarged the flow control windows.

It all boils down to the client being completely overwhelmed by the load.

Please read about how to setup some load generation here:
https://github.com/jetty-project/jetty-load-generator

Also, read this blog:
https://webtide.com/the-jetty-performance-effort/

From the blog above, you will see that we needed 4 powerful client machines just to make the server notice the load.
If you use just one client machine, you will always be constrained by the client.

**Comment by prateekkohli2112** [comment]
We understand that this has to be a limitation on the client side. But we are not just testing Jetty server but a pipeline having Jetty server and client as attached in a picture below.

![pipeline](https://user-images.githubusercontent.com/17244992/143984575-60c52253-a7ed-4af6-ae36-d6a334cf71a9.png)

In such a pipeline without latency we are able to achieve the expected throughput which is not too high(~8000) and on the same environment the expectation was that with async we will be able to get the same throughput with a 7 sec latency.

And we can see that obviously the threads are not the issue now, and we also do not understand why n/w would be an issue as input and output rate is same as it is without latency.

Also, after reading your reply we understood that why high number of streams could be an issue, so we changed it to 250 streams per connection. But since the latency is 7 seconds so we had to increase the number of connections to 300.

Now we could see that after a certain throughput the destination queue just keeps on increasing and no request is sent towards the jetty server. Client opens all 300 connections and from the pool's dump we can see that almost all connections are either EOF or goaway. So any insights of what could be the reason. Attaching pool dump for your reference.
[Pools Dump.txt](https://github.com/eclipse/jetty.project/files/7622873/Pools.Dump.txt)

**Comment by sbordet** [comment]
> In such a pipeline without latency we are able to achieve the expected throughput which is not too high(~8000) and on the same environment the expectation was that with async we will be able to get the same throughput with a 7 sec latency.

Your expectations are wrong. If you inject a 7 s latency on a system that can do 8k requests/s, you need to buffer 56k requests before receiving the first response.
With only 300 connections, you now have a completely different system from before, with queueing happening everywhere: on the client, on the TCP connection, on the server in multiple places, etc.
The system will just behave differently as queues will drain at different rates.

Regarding the `Pool` dump, seems to me that you're hitting this issue: #7157.

If you can try the latest code with the fix for #7157 would be great.
