### ISSUE TITLE
Jetty 9 doc issue - WebSocket message size

### ISSUE THREAD

**Issue by ArfyFR** [eclipse/jetty.project#7121]
**Jetty version(s)**
9

**Description**
In WebSocket Introduction I can read:
_A single message in WebSocket can be of **any size** (the underlying framing however does have a single frame limit of 63-bits). There can be an unlimited number of messages sent. Messages are sent sequentially, the base protocol does not support interleaved messages._
Link: https://www.eclipse.org/jetty/documentation/jetty-9/index.html#websocket-intro

But by default it seems to be max 64Ko (and may be modified with Annotation 
`@WebSocket(maxTextMessageSize = 64 * 1024)
`
or with Session:
```
javax.websocket.Session.setMaxBinaryMessageBufferSize(int)
javax.websocket.Session.setMaxTextMessageBufferSize(int)
```

I think it should be written that there is a default 64Ko limit.

I also checked Jetty 10 documentation: exemples are set with a 1Mo limit, but I think there is also a default one.

**Comment by lachlan-roberts** [comment]
> A single message in WebSocket can be of any size (the underlying framing however does have a single frame limit of 63-bits). There can be an unlimited number of messages sent. Messages are sent sequentially, the base protocol does not support interleaved messages.

This section is talking about the WebSocket protocol and not related to the settings from the JSR-356 (javax.websocket) API. The protocol itself defines no limits on the overall message size.

> I also checked Jetty 10 documentation: exemples are set with a 1Mo limit, but I think there is also a default one.

This is to demonstrate how you can set the value to something other than the default.

**Comment by lachlan-roberts** [comment]
But I think it would be beneficial to have a section describing settings like this and their default values. In Jetty 10-11  we have the [`WebSocketConstants`](https://github.com/eclipse/jetty.project/blob/dd0613193cae9f95d7b042c79765cf552f29eef4/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConstants.java) class which defines the default values used for both the Jetty WS API and JSR-356 API. For 9.4 these defaults come from [`WebSocketPolicy`](https://github.com/eclipse/jetty.project/blob/4a497cd863fd7dbfe4a518b24b7a1b0077e67488/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java).
