### ISSUE TITLE
JasperException: PWC6349

### ISSUE THREAD

**Issue by yuandongjie** [eclipse/jetty.project#7127]

**Comment by sbordet** [comment]
Honestly, too little information, don't you think?

**Comment by janbartel** [comment]
@yuandongjie you must be using jetty-9.3 or earlier. Have a look at this issue: https://github.com/jetty-project/embedded-jetty-jsp/issues/6  and also please read the jetty documentation regarding jsp that matches your jetty version.

**Comment by janbartel** [comment]
Closing.
