### ISSUE TITLE
Jetty 9.3.10 doesn't use configured CBC Cipher Suites

### ISSUE THREAD

**Issue by lkoniecki** [eclipse/jetty.project#713]
I've upgraded Jetty from version 9.3.6 to version 9.3.10. I have the following SSL configuration:

	<Set name="IncludeCipherSuites">
		<Array type="String">
			<Item>SSL_RSA_WITH_3DES_EDE_CBC_SHA</Item>
			<Item>TLS_RSA_WITH_AES_128_CBC_SHA</Item>
			<Item>TLS_RSA_WITH_AES_256_CBC_SHA</Item>
			<Item>TLS_RSA_WITH_AES_128_GCM_SHA256</Item>
			<Item>TLS_RSA_WITH_AES_256_GCM_SHA384</Item>
		</Array>
	</Set>
	<Set name="IncludeProtocols">
		<Array type="String">
			<Item>TLSv1.1</Item> 
			<Item>TLSv1.2</Item>
			<Item>SSLv2Hello</Item>
		</Array>
	</Set> 

After upgrade only AES128-GCM-SHA256 Cipher Suite is reported by the testssl (test server doesn't have Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files applied so SHA384 will not be used).

> --> Testing all locally available 181 ciphers against the server, ordered by encryption strength
>
> Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits
>
> x9c     AES128-GCM-SHA256              RSA        AESGCM     128

**Comment by sbordet** [comment]
Excluded ciphers have precedence over included ciphers.

In Jetty 9.3.7 we have excluded by default a number of vulnerable ciphers that likely include your CBC ciphers.

If you still want to use those vulnerable ciphers and protocols, you have to reset the exclude list by calling:

```java
// No parameter means empty list of excluded ciphers.
sslContextFactory.setExcludeCipherSuites();
```
