### ISSUE TITLE
Use Charset instead of encoding string where possible

### ISSUE THREAD

**Issue by mperktold** [eclipse/jetty.project#7131]
**Target Jetty version(s)**
Jetty 10.0.x

**Enhancement Description**
We've noticed a few places where a string charset is passed to a JDK method even if it would be possible to directly use a Charset instead:
- [HttpRequest#urlEncode](https://github.com/eclipse/jetty.project/blob/ec3d7dbe92532cfdbb719cb7b736ad115aea40e5/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java#L916)
- [HttpRequest#urlDecode](https://github.com/eclipse/jetty.project/blob/ec3d7dbe92532cfdbb719cb7b736ad115aea40e5/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java#L947)
- [FormRequestContent#encode](https://github.com/eclipse/jetty.project/blob/ec3d7dbe92532cfdbb719cb7b736ad115aea40e5/jetty-client/src/main/java/org/eclipse/jetty/client/util/FormRequestContent.java#L66)

Maybe there are some more, but those are the ones we found.

This is more of an observation rather than a feature request.

Also, the corresponding overloads accepting a Charset are only available since Java 10, which is fine for Jetty 10 but not for Jetty 9, so please decide for yourself whether this is worthwhile.

**Comment by joakime** [comment]
Opened as PR #7137

**Comment by joakime** [comment]
Merged into `jetty-10.0.x` and `jetty-11.0.x`
