### ISSUE TITLE
Bundle org.eclipse.jetty.apache-jsp is not available in the p2 repository

### ISSUE THREAD

**Issue by lkoniecki** [eclipse/jetty.project#714]
Hello,

Currently Jetty p2 repository (e.g. http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.3.10.v20160621/plugins/) does not contain apache-jsp library, which is required if you want to enable JSP support.

Standalone Jetty distribution contain that implementation and that it’s version is in sync with the Jetty version (e.g. for the Jetty 9.3.10: org.eclipse.jetty.apache-jsp-9.3.10.v20160621.jar).

**Comment by janbartel** [comment]
I added the apache-jsp bundle to the p2 build and regenerated it. So the bundle should be in there now. If not, please reopen this issue.
