### ISSUE TITLE
ClientConnector is not registered as a bean what results in a NullPointerException

### ISSUE THREAD

**Issue by amsmax** [eclipse/jetty.project#7140]
**Jetty version(s)**
10.0.7

**Java version/vendor** `(use: java -version)`
11.0.12

**OS type/version**
Ubuntu 20.04.1

**Description**
NullPointerException occurs when an SSLContext is added to an HTTPClient. While creating the HTTPClient a ClientConnector is created but this ClientConnector is not registered as a managed bean.

**How to reproduce?**
SSLContext sslContext = SSLContext.getDefault();

HttpClient httpClient = new HttpClient();
httpClient.getSslContextFactory().setSslContext(sslContext);

**Comment by sbordet** [comment]
The `SslContextFactory` is initialized when `HttpClient` -- and therefore `ClientConnector` -- is started.
This is to allow to set the `SslContextFactory` on `ClientConnector` in case of advanced configuration.

Do this instead:

```java
HttpClient httpClient = new HttpClient();
httpClient.start();
httpClient.getSslContextFactory().setSslContext(SSLContext.getDefault());
```

Or, if you want to use a more advanced configuration:

```java
SslContextFactory.Client sslContextFactory = new SslContextFactory.Client();
sslContextFactory.setSslContext(SSLContext.getDefault());

ClientConnector clientConnector = new ClientConnector();
clientConnector.setSslContextFactory(sslContextFactory);

HttpClient httpClient = new HttpClient(new HttpClientTransportOverHTTP(clientConnector));
```
