### ISSUE TITLE
Improve documentation about HTTPClient and HTTP/2

### ISSUE THREAD

**Issue by amsmax** [eclipse/jetty.project#7141]
**Target Jetty version(s)**
10.0.7

**Enhancement Description**
The [documentation](https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-client) describes the following:

_The High-Level HTTP Client Library for HTTP/1.1, HTTP/2 and FastCGI_

It looks like if the HTTPClient can do HTTP/2 calls but if I'm not mistaken the low level HTTP2Client is still required. The only example I could find is the following:

```
// The HTTP2Client powers the HTTP/2 transport.
HTTP2Client h2Client = new HTTP2Client();
h2Client.setInitialSessionRecvWindow(64 * 1024 * 1024);

// Create and configure the HTTP/2 transport.
HttpClientTransportOverHTTP2 transport = new HttpClientTransportOverHTTP2(h2Client);
transport.setUseALPN(true);

HttpClient client = new HttpClient(transport);
client.start();

```
It took me a long time to figure this out.

**Comment by sbordet** [comment]
In the [HTTP client documentation](https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-client-http), the 4th paragraph talks about the different transport:

"Jetty’s HTTP client supports different transports: HTTP/1.1, FastCGI and HTTP/2."

The words "different transports" are a link to the pluggable transport section, where you can find the snippet that you reported.
So it's enough to click on the link.

Also, looking at the table of content on the left, it shows the "HttpClient Pluggable Transport" section.

I'm open to suggestions to make this easier to find, but I can't think of anything simpler than clicking on a link.
Do you have suggestions?

**Comment by amsmax** [comment]
I was expecting something like:
HttpClient httpClient = new HttpClient();
httpClient.setProtocol(H2)
It feels a little bit strange that two 'HttpClients'  are needed HttpClient and HTTP2Client. It is now all clear to me.

My goal is to use Jetty in a Spring WebClient. Some background information. Spring offers the class RestTemplate to do blocking calls to backend services. This RestTemplate is now in maintenance mode and will probably deprecated. The Spring WebClient replaces the RestTemplate. WebClient can be used with Jetty, Netty (default) or Apache. Spring recommends to use the same stack for the web server and for the HTTP Client because resources are shared. There are two options, use Netty for the web server and client or Jetty. Netty is based on Spring WebFlux, Jetty can be used in Spring MVC. I expect that most people will stick to Spring MVC because that is much simpler to use.

Maybe it is an idea to describe, give examples, how the Jetty HttpCient can be configured with Spring WebClient. On the other hand I can also imagine that you don't want to mention other libraries on your page.

**Comment by sbordet** [comment]
Closing, as there is a rework of the documentation for the new website, with searchable features, and new documentation that comes with the work of #8979.
