### ISSUE TITLE
404 in API documentation

### ISSUE THREAD

**Issue by amsmax** [eclipse/jetty.project#7164]
**Jetty version(s)**
Jetty 10

**Java version/vendor** `(use: java -version)`
not applicable

**OS type/version**
Ubuntu with Chrome Browser

**Description**
Search functionality in online API doesn't work fully. Sometimes it results in a 404.

**How to reproduce?**
- Go to https://www.eclipse.org/jetty/javadoc/jetty-10/index.html?overview-summary.html.
- Search for ClientConnector
- Click on the result
- 404

**Comment by sbordet** [comment]
@jmcc0nn3ll we need to update the script that uploads the javadocs to the website to take the javadocs built with Java 17, not Java 11.

It's a javadoc issue that was fixed in Java 12.

**Comment by lachlan-roberts** [comment]
Fixed.
