### ISSUE TITLE
Jetty rewrites header values breaking AWS signatures

### ISSUE THREAD

**Issue by cstamas** [eclipse/jetty.project#7168]
**Jetty version(s)**
Tested 9.4.41 (version s3proxy uses) but locally same behaviour with 9.4.44

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

**OS type/version**
Linux Mint 20.2 kernel 5.4.0-90-generic

**Description**
Seems Jetty is replacing value of Content-Type from client HTTP request, thus making header (sent by client) as
```
text/plain; charset=utf-8
```
into
```
text/plain; charset=UTF-8
```
While this does not seem biggie, it breaks AWS v2 and v4 signatures, hence requests using content-type that are added to HttpParser CACHE (well, tested for text/plain only, other s3proxy UTs uses not-so-common content types like audio etc not present in Jetty HttpParser CACHE) are doomed to fail due this: SignatureDoesNotMatch error from s3proxy. 
Reason is simple: AWS client will create canonical headers containing "utf-8" while s3proxy does same but will use "UTF-8" and hence resulting signature will be different.

**How to reproduce?**
Jetty UT https://github.com/eclipse/jetty.project/pull/7169
S3Proxy UT https://github.com/gaul/s3proxy/pull/394

Links
S3Proxy issue https://github.com/gaul/s3proxy/issues/392
UT for S3Proxy reproducing issue https://github.com/gaul/s3proxy/pull/394

**Comment by cstamas** [comment]
Created Jetty UT that demonstrates the issue: https://github.com/eclipse/jetty.project/pull/7169

**Comment by joakime** [comment]
Considering that the https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/ is still a a draft and every revision on it introduces more and more "but this field is also case insensitive", I bet this is yet another situation just like this. (All mime-type and charset usage in any http field is case-insensitive already per the HTTP/1.x specs)

The translation of the HTTP Fields from HTTP/1.1 to HTTP/2 (done by many intermediaries) would also make signature validation nigh impossible.
Plenty of discussion on these issues on http-bis mailing list.

You could probably disable the HttpParser CACHE, but that would just skyrocket your GC.

**Comment by cstamas** [comment]
Disabling CACHE for our use case of s3proxy would work (we use it in ITs as "upstream"), but would not fix s3proxy issue.

But re "All mime-type and charset usage in any http field is case-insensitive already per the HTTP/1.x specs", if so, then why is Jetty altering valid "utf-8" to (another valid) "UTF-8"? (Especially as lower case one is also in cache https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java#L226 )

**Comment by michael-o** [comment]
@cstamas Let me guess: It uses Java's `Charset` class which will generate an uppercase to string representation of the parsed value. Note that Apache HttpClient does the same.

**Comment by cstamas** [comment]
No, on cliend side guava is used, and guava defines mediatype with lowercase. So that is signed, but while it arrives to s3proxy (that is a jetty handler) it becomes uppercase 😞

**Comment by michael-o** [comment]
The you need a canoncial representation otherwise this will not work.

**Comment by janbartel** [comment]
See comment over at https://github.com/gaul/s3proxy/issues/392

**Comment by janbartel** [comment]
Issue fixed over at https://github.com/gaul/s3proxy/issues/392
