### ISSUE TITLE
JNR/UnixSocket connect does not release?

### ISSUE THREAD

**Issue by mjs8002** [eclipse/jetty.project#7187]
**Jetty version(s)**
9.4.43.v20210629
**Java version/vendor** `(use: java -version)`
1.8
**OS type/version**
linux
**Description**
_Do not report security issues here! See [Jetty Security Reports](https://www.eclipse.org/jetty/security_reports.php)._
we use HttpClientTransportOverUnixSockets
send request such as ：
  HttpClientTransportOverUnixSockets transport = new HttpClientTransportOverUnixSockets(getSocketPath());
            clientUds = new HttpClient(transport, null);
            transport.setHttpClient(clientUds);
send：
  ...
  request = client.newRequest(servicePath);
  ...
  FutureResponseListener listener = new FutureResponseListener(request, bodysize);
            request.send(listener);
            ContentResponse response = listener.get(timeout, TimeUnit.MILLISECONDS);
            Map<String, String> rspMap = new HashMap<String, String>();
            rspMap.put("contentEncoding", response.getEncoding());
            rspMap.put("contentType", response.getMediaType());
            rspMap.put("streamAsString", response.getContentAsString());
            return buildRestfulResponse(response.getStatus(), response.getHeaders(), response.getContent(), rspMap);
however we find in HttpDestination we debug :
![20211201-150806(WeLinkPC)](https://user-images.githubusercontent.com/41276528/144187920-4c111e16-bf7b-4575-991c-f05e42050829.png)
in the connectionpool  connect timeout but canot ralease when the pool is fulled we canot send any request

**How to reproduce?**

**Comment by mjs8002** [comment]
![image](https://user-images.githubusercontent.com/41276528/144189557-5f67cc4e-641f-4dab-8d2a-004022dc5a04.png)

we find the warn in log

**Comment by sbordet** [comment]
Support for Unix-Domain sockets via `jetty-unixsocket` and related modules is experimental and deprecated (see #7109).

I recommend that you switch to Java 16 or later and use OpenJDK Unix-Domain support, which is supported in Jetty 10 via the `jetty-unixdomain` modules.

**Comment by joakime** [comment]
@sbordet what's the OpenJDK Unix-Domain replacement for HttpClient's HttpClientTransportOverUnixSockets?

**Comment by mjs8002** [comment]
> Support for Unix-Domain sockets via `jetty-unixsocket` and related modules is experimental and deprecated (see #7109).
> 
> I recommend that you switch to Java 16 or later and use OpenJDK Unix-Domain support, which is supported in Jetty 10 via the `jetty-unixdomain` modules.

@sbordet Is there a good solution on jetty 9?

**Comment by sbordet** [comment]
Unfortunately no, JNR is not stable enough and now that support for Unix-Domain landed in the JDK I don't think we will try and chase down bugs in JNR.

Note that using Jetty 10's `HttpClient` is probably just a drop in replacement for Jetty 9's `HttpClient`, so I recommend that you upgrade - you will probably have to change very little in your client application.
