### ISSUE TITLE
asciiToLowerCase nullpointer

### ISSUE THREAD

**Issue by xzxevil** [eclipse/jetty.project#720]
hello 

Here is a crash stack trace.

Caused by java.lang.NullPointerException
       at org.eclipse.jetty.util.StringUtil.asciiToLowerCase(SourceFile:106)
       at org.eclipse.jetty.http.MimeTypes.(SourceFile)
       at org.eclipse.jetty.server.handler.ContextHandler.doStart(SourceFile:711)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(SourceFile:64)
       at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(SourceFile:95)
       at org.eclipse.jetty.server.Server.doStart(SourceFile:282)
       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(SourceFile:64)
       at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.startIfNotRunning(SourceFile:141)
       at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl.run(SourceFile:92)

Which was caused by null pointer, In source code below, param ext may be null, so the crash occurred. Can you please take a look of this issue?

```
            ResourceBundle mime = ResourceBundle.getBundle("org/eclipse/jetty/http/mime");
            Enumeration i = mime.getKeys();
            while(i.hasMoreElements())
            {
                String ext = (String)i.nextElement();
                String m = mime.getString(ext);
                __dftMimeMap.put(StringUtil.asciiToLowerCase(ext),normalizeMimeType(m));
            }
```

**Comment by janbartel** [comment]
I added a check for  null in StringUtil.asciiToLowerCase() method.

However, I still can't see how there could be a null key in the mimetypes loaded from the mime.properties?

**Comment by zayass** [comment]
We have same issue on android with version 8.1.8
but line 106 it is not null input parameter
if input is null NullPointerException was attempt earlier on line 86

https://github.com/eclipse/jetty.project/blob/00ed5498988062d768ee306da708d338a96253dc/jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java#L106


same issue http://stackoverflow.com/questions/31769747/how-to-checkout-jetty-util-jetty-util-8-1-17-v20150415-from-git with line 106 android and cling

**Comment by asamoylenko** [comment]
We are experiencing exactly the same issue and I don't see how this check for null fixes it. I mean it DOES cover the case when parameter is null, but doesn't fix the issue. Most likely @xzxevil uses Jetty 8.1.8.v20121106 like we do.
```java
    /**
     * fast lower case conversion. Only works on ascii (not unicode)
     * @param s the string to convert
     * @return a lower case version of s
     */
    public static String asciiToLowerCase(String s)
    {
        char[] c = null;
        int i=s.length();

        // look for first conversion
        while (i-->0)
        {
            char c1=s.charAt(i);
            if (c1<=127)
            {
                char c2=lowercases[c1];
                if (c1!=c2)
                {
                    c=s.toCharArray();
                    c[i]=c2;
                    break;
                }
            }
        }

        while (i-->0)
        {
            if(c[i]<=127)
                c[i] = lowercases[c[i]];
        }
        
        return c==null?s:new String(c);
    }
```
where 106th line is ```if(c[i]<=127)``` and I have no idea how ```c``` can be null there.
Nevertheless crash reports are keep on arriving :/
