### ISSUE TITLE
Jetty Client HTTP2 Ping timeout

### ISSUE THREAD

**Issue by idikshit** [eclipse/jetty.project#7206]
**Jetty version**
9.4.42.v20210604

**Java version**
17

**Question**
Hi, we are using jetty client Http2 PING functionality in our project. Is there a way to configure timeout for Http2 PING, if not what is the default duration after which Http2 ping fails if the timeout value is not set? Thank you in advance !

**Comment by sbordet** [comment]
Applications, if they need to, should setup a timeout in case they don't receive a PING reply.
This is typically fairly easy to setup, since `HTTP2Client` exposes a `Scheduler` that can be used to setup a timeout task.

**Comment by idikshit** [comment]
Thanks @sbordet. What would be the default timeout value if timeout is not set/ not provided?

**Comment by sbordet** [comment]
There is no timeout for PING frames.
If you want a timeout for PING frames you have to implement it yourself.

The only timeout enforced by Jetty is when the whole connection goes idle, i.e. the idle timeout, which causes the connection to be closed.

**Comment by janbartel** [comment]
Closing as the question seems to have been answered.
