### ISSUE TITLE
Wich Jetty Reactive Client to use in Springboot WebClient with Jetty 10.0.7

### ISSUE THREAD

**Issue by amsmax** [eclipse/jetty.project#7211]
**Jetty version**
10.0.7

**Java version**
11.0.11

**Question**
I'm using Spring boot with Jetty 10.0.7. I want to use the Spring boot WebClient for doing calls to the backend. Which Jetty reactive client version do I need to use? 
I read [here](https://webtide.com/reactive-httpclient-1-1-5-2-0-0-and-3-0-0/) that version 2.0.0 is not compatible with Spring WebFlux but regarding this blog version 2.x.x is the version for Jetty 10.

**Comment by sbordet** [comment]
Have you actually tried? 

I ask because it seems that Spring Boot's `WebClient` depends on version 3.0.x, which should be practically identical to 2.0.x.
This means that Spring has updated the API usage since the blog from one year ago.

**Comment by amsmax** [comment]
Yes, I tried version 1.1.10, 2.0.4 and 3.0.4. They are all working. Springboot 2.5.7 comes default with version 1.1.10. I guess the cause of this is that Jetty 9 is the default version in Springboot 2.5.7. Version 3.0.4 will be the default version in the coming Spring framework 6 / Spring boot 3. I think for now I need to use 2.0.4.

**Comment by sbordet** [comment]
You can use 2.0.x if you use Java >= 11.
If you use Java < 11, then you have to use 1.1.x.

**Comment by janbartel** [comment]
Closing as it seems question has been answered.
