### ISSUE TITLE
Provide a private way to report security issues

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#725]
Creating security issues here is a little too public.  The ability to lock and issue is often too late and may just draw attention to the problem.

We need a way for security issues to be reported that is easily visible/findable from here (at least listed in the guidelines above).

**Comment by jmcc0nn3ll** [comment]
I have pinged the security@eclipse.org mailing list which I believe is supposed to have a policy on this.  I'll update here when I have a response and we can update the documentation accordingly, @WalkerWatch bug me if you don't hear back on this for a spell.

**Comment by joakime** [comment]
There's a unofficial discussion between the community and github about private issues (and pull requests) at isaacs/github#37

**Comment by jmcc0nn3ll** [comment]
Since there is no path to getting GitHub Issues doing this anytime soon I added a page to the documentation on reporting security issues to security@webtide.com and security@eclipse.org (which can be slower to get feedback from).
