### ISSUE TITLE
It is necessary to set MAX_CAPACITY to ArrayTernaryTrie/ArrayTrie

### ISSUE THREAD

**Issue by tinswzy** [eclipse/jetty.project#7271]
**Jetty version(s)**
9.3+, 9.4+

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
It is necessary to backport MAX_CAPACITY bugfix to ArrayTernaryTrie/ArrayTrie，as there are still many mainstream projects using jetty9.x. 
In 9.x, the ContextHandlerCollection uses the ArrayTernaryTrie data structure by default. The data types of  _rows&_tree in ArrayTernaryTrie are char/char[]. Their capacity is limited, otherwise routing bugs will occur if the value is exceeded.

**How to reproduce?**
@Test
public void testArrayTernaryTrieBug() throws Exception
{
    Trie<String> trie = new ArrayTernaryTrie<>(false,400000);

    // put root path
    boolean success = trie.put("","/");
    assertTrue(success);
    String bestUrl = trie.get("/",1,0);
    assertEquals("/",bestUrl);

    // put a large path or many paths
    char[] c1 = new char[65535];
    Arrays.fill(c1,'a');
    success = trie.put(new String(c1),"/"+new String(c1));
    // expect put failed, but now it success
    assertFalse(success);

    bestUrl = trie.get("/",1,0);
    assertEquals("/",bestUrl);
}

**Comment by sbordet** [comment]
Fixed by #7405.
