### ISSUE TITLE
Interceptors don't get destroyed in HttpInput

### ISSUE THREAD

**Issue by winne42** [eclipse/jetty.project#7280]
**Jetty version(s)**
10.x and 11.x

**Java version/vendor**
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

**OS type/version**
Windows 10 20H2, 64 bit

**Description**
When migrating our product from Jetty 9.4 to 11.0, we noticed that our custom interceptors were not destroyed any more. Between Jetty 9.4 and 10.x/11.x, it is obvious that a lot of code from `HttpInput.recycle()` (that did the trick before) has vanished:

![image](https://user-images.githubusercontent.com/21171796/146014183-1f53ffcb-43ca-4f61-9974-603d29d2545b.png)

This happened during a large refactoring of `HttpInput` starting with PR #4556. Maybe @lorban , @sbordet or @gregw know more? Is this an oversight or has the lifecycle of interceptors somehow changed? Are we the only ones who have this problem?

In our case, this solved the problem (but we don't know enough about Jetty to be sure this doesn't break something else):

```
    public void recycle()
    {
        try (var ignored = _contentProducer.lock()) {
            if (LOG.isDebugEnabled())
                LOG.debug("recycle {}", this);
            Interceptor interceptor = _contentProducer.getInterceptor();
            if (interceptor instanceof Destroyable) {
                ((Destroyable) interceptor).destroy();
            }
        }
    }

```

**How to reproduce?**
For both Jetty 9.4 and 11.0, `HttpInput.recycle()` is on a call-chain triggered by `HttpConnection.onCompleted()`.

**Comment by lorban** [comment]
This is an oversight, since 9.4 checks that `Destroyable` interceptors should be destroyed then 10.0 and 11.0 should too. I'm going to add the missing bits of code and tests shortly.

Thanks for the report!

**Comment by lorban** [comment]
Also see https://github.com/eclipse/jetty.project/issues/7284
