### ISSUE TITLE
EOFs are not passed to interceptors any more - shouldn't they?

### ISSUE THREAD

**Issue by winne42** [eclipse/jetty.project#7281]
**Jetty version(s)**
10.x, 11.x

**Java version/vendor**
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

**OS type/version**
Windows 10 20H2, 64 bit

**Description**
Starting with the overhaul of `HttpInput` in PR #4556, EOFs are not passed to interceptors any more. The author was obviously also unsure whether this is a good idea, see `AsyncContentProducer.nextTransformedContent()`:
```
// TODO does EOF need to be passed to the interceptors?
```
So custom interceptors cannot react to EOF any more - which we have seen in use by an OSS library based on Jetty 9.4.

If one *would* pass EOF to the interceptors, this would require a small change in `GzipHttpInputInterceptor.readFrom()`, because it tries `getByteBuffer()` without a guard --> `IllegalStateException` in case of `SpecialContent`. For Comparison: In Jetty 9.4, `EofContent` had a `BufferUtil.EMPTY_BUFFER`, so `getByteBuffer()` worked like a charm.

Shouldn't custom interceptors be able to react to EOF nowadays?
This should at least be clarified in a detailed comment instead of the TODO comment.

**How to reproduce?**
Set a breakpoint next to the TODO comment in `AsyncContentProducer.nextTransformedContent()`.

**Comment by lorban** [comment]
Should EOF be passed to interceptors or not has been left, as you have noticed, as an open question.

It would be very interesting for us to have a look at external implementations of `HttpInput.Interceptor`, could you please point to where we can find some? This would certainly help finally making up or mind on this matter.

But even if we were to restore passing EOF to interceptors, those Content instances would certainly keep their behavior of throwing `IllegalStateException` when `getByteBuffer()` is called.

@gregw I think you were the one unsure about EOF and interceptors as IIRC you considered that protocols should be self-contained (i.e.: know its content length) like gzip is.

**Comment by winne42** [comment]
Thanks for the super quick reply! I found the problem here: https://gitlab.com/sdc-suite/sdc-ri/-/blob/develop/dpws/src/main/java/org/somda/sdc/dpws/http/jetty/CommunicationLogInputInterceptor.java

Don't know whether this makes any sense, you are the experts ;-)

**Comment by sbordet** [comment]
I'm leaning towards passing EOF to the interceptor, for use cases such as forwarding the content to a file or to another HTTP request, and close the file or request as soon as possible.

It's quite easy to test for `content.isEof()` although all implementations should be changed.
However, if we pass `EofContent` to the interceptor, we should return the empty buffer from `getByteBuffer()`, otherwise we are breaking all the implementations.

**Comment by joakime** [comment]
> Thanks for the super quick reply! I found the problem here: https://gitlab.com/sdc-suite/sdc-ri/-/blob/develop/dpws/src/main/java/org/somda/sdc/dpws/http/jetty/CommunicationLogInputInterceptor.java
> 
> Don't know whether this makes any sense, you are the experts ;-)

``` java
        // rewind the bytebuffer we just went through
        content.getByteBuffer().position(oldPosition);
```

You could grab a ByteBuffer slice with [`ByteBuffer.slice()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html#slice()) before you work with it and the the position/limit/capacity/mark/byte-order changes in your code wont change on the original ByteBuffer. (same underlying array is used, so be careful with changes to the content)

**Comment by lorban** [comment]
I am personally torn between passing the EOF content or not, but slightly leaning towards the option of _not_ passing it and clearly documenting the `Interceptor` contract as such.

AFAICT, your Interceptor implementation could do without the EOF content much like Jetty's `GzipHttpInputInterceptor` at least now that #7280 is fixed, you could let `destroy()` close your `OutputStream` without the need to rely on EOF.

**Comment by winne42** [comment]
I don't know what others may want to do with EOF in their interceptors. You are right, in "our" case, `destroy()` seems to be sufficient (if it is guaranteed that `destroy` is always called).

> clearly documenting the Interceptor contract as such.

That would be great, thx!

**Comment by gregw** [comment]
I think EOF should be sent through interceptors

**Comment by lorban** [comment]
I submitted a PR that makes `ContentProvider` implementations pass special content instances to the interceptor, as @gregw convinced me this is the way we want to go.

Regarding the `Content.getByteBuffer()` contract, it has been documented as such since 10.0.0: _Get the wrapped byte buffer. Throws IllegalStateException if the content is special._ so any preexisting code that calls `getByteBuffer()` without checking the special flag first is at breach of the existing API contract.

**Comment by lorban** [comment]
@winne42 would it be possible for you to build the linked PR and give that build a try?

I would recommend you to modify your `Interceptor` to look something like the following, both to handle the special content flag as well as using the EOF flag as a hint to close your logger stream asap:

```java
@Override
public HttpInput.Content readFrom(HttpInput.Content content) {
    if (!content.isSpecial()) {
        // write the contents somewhere else
        writeToCommlogStream(content.getByteBuffer().duplicate());
    }
    if (content.isEof()) {
        // close the commlogStream asap, but beware: commlogStream.close() could be called many times
        // including at least once here, plus once in destroy().
        commlogStream.close();
    }
    return content;
}
```

**Comment by gregw** [comment]
I think this read better and should work just as well:
```java
@Override
public HttpInput.Content readFrom(HttpInput.Content content) {
    if (content.hasContent()) {
        // write the contents somewhere else
        writeToCommlogStream(content.getByteBuffer().duplicate());
    }
    if (content.isEof()) {
        // close the commlogStream asap, but beware: commlogStream.close() could be called many times
        // including at least once here, plus once in destroy().
        commlogStream.close();
    }
    return content;
}
```
Note that it is possible for a content to both have content and be EOF.

**Comment by winne42** [comment]
You guys are just amazingly responsive and helpful, thanks! 👍 👍 👍 

@lorban I am on vacation already and probably won't have time before next years to try, sorry. But if it works with `GzipHttpInputInterceptor`, I don't see any reason why it shouldn't work for everybody else.

Thank you @lorban , @gregw , @sbordet , @joakime for also putting thoughts in the documentation! This will certainly help many folks. Maybe you could also make JavaDoc on `HttpInput.isSpecial()` more meaningful? What exactly is/could be "special" content? (and maybe also mention the relation to `hasContent()`)
