### ISSUE TITLE
Deprecate log4j 1.x support

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7297]
**Jetty version(s)**
9+

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
Alll

**Description**
Log4j 1.x was EOL in August 2015.

While we have no direct dependencies on log4j 1.x within our project, we do have modules across our 3 active versions of Jetty that have log4j 1.x options.

I propose we drop log4j 1.x entirely, modules and all.
If a user wants to continue to use log4j 1.x they have to manually add it, no module convenience anymore.

**Comment by lachlan-roberts** [comment]
I don't think we can just remove the module without breaking existing usages that are relying on the mod file. 
We could just deprecate it in 9-11 and then remove the module in Jetty 12?

**Comment by sbordet** [comment]
We have a [deprecated] feature in modules now... I agree that the module should not be removed entirely.

**Comment by joakime** [comment]
Fair enough.
I'm going to move log4j 1.x support versioning OUT of the pom.xml and totally within the module (which I'll flag as deprecated too).

Do we warn users if they are have an previously not-deprecated module enabled on next startup?

**Comment by sbordet** [comment]
> Do we warn users if they are have an previously not-deprecated module enabled on next startup?

Deprecated modules are already logged at WARN level on startup.

**Comment by joakime** [comment]
I have moved it out of the main pom in Jetty 9.4.x.
Need to make a new PR for Jetty 10+

**Comment by joakime** [comment]
Completed in PR #7353
