### ISSUE TITLE
MavenLocalRepoFileInitializerTest#testDownloadSnapshotRepo depends on possible missing external resources

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#7315]
the test MavenLocalRepoFileInitializerTest#testDownloadSnapshotRepo depends on downloading snapshot jars from https://oss.sonatype.org/content/repositories/jetty-snapshots/ with hardcoded version `10.0.0-SNAPSHOT`.
the test should be rewrite to use https://www.mojohaus.org/mrm/mrm-maven-plugin/ and download current installed version.

**Comment by joakime** [comment]
The whole point of that test is to ensure that the start.jar follows maven convention for snapshot metadata.

**Comment by joakime** [comment]
We've filed an issue with oss.sonatype.org btw to address the missing jetty-snapshots repo

**Comment by joakime** [comment]
oss-sonatype has restored the missing jetty-snapshots repo

**Comment by olamy** [comment]
need to be fixed as after a cleanup of snapshots in oss.sonatype.org builds are now failing

**Comment by joakime** [comment]
We should probably look into having a `repo.webtide.net` that is publicly exposed and has our SNAPSHOTS on it.

@jmcc0nn3ll thoughts?

**Comment by joakime** [comment]
I'm reopening this.
We should either find a reliable way to still perform this test, or remove it.

**Comment by olamy** [comment]
I would prefer to use https://github.com/mojohaus/mrm which local installed snapshots as part of the build.
no need of external resource.
No urgent for now but need to be done.

**Comment by joakime** [comment]
Closing, as we haven't seen this issue in quite a while.
