### ISSUE TITLE
Flakey test in HttpClient RoundRobinConnectionPoolTest

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#7318]
**jetty-10.0.x**

> Running org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest.testMultiplexWithMaxUsage([6] FCGI)
> 2021-12-21 05:23:27.800:INFO :oejs.Server:main: jetty-10.0.8-SNAPSHOT; built: 2021-12-21T04:12:01.659Z; git: f849b8f6a5e1f17a36e273dfa1fb1421e2e97ac9; jvm 11.0.13+8
> 2021-12-21 05:23:27.804:INFO :oejs.AbstractConnector:main: Started ServerConnector@60fe0da9{fcgi/1.0, (fcgi/1.0)}{0.0.0.0:44753}
> 2021-12-21 05:23:27.804:INFO :oejs.Server:main: Started Server@3475f9dc{STARTING}[10.0.8-SNAPSHOT,sto=0] @833175ms
> 2021-12-21 05:23:27.812:INFO :oejs.Server:main: Stopped Server@3475f9dc{STOPPING}[10.0.8-SNAPSHOT,sto=0]
> 2021-12-21 05:23:27.812:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@60fe0da9{fcgi/1.0, (fcgi/1.0)}{0.0.0.0:0}
> Running org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest.testMultiplexWithMaxUsage([7] UNIX_DOMAIN)
> [ERROR] Tests run: 21, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 6.327 s <<< FAILURE! - in org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest
> [ERROR] org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest.testMultiplexWithMaxUsage(Transport)[5]  Time elapsed: 0.772 s  <<< FAILURE!
> java.lang.AssertionError: 
> [59254, 34711, 59254, 59254, 48870, 34711, 34711, 54265, 48870, 48870, 54265, 54265, 47029, 47029, 54232, 56236, 56236, 56236, 45679, 54232, 54232, 47029, 45679, 45679, 59254, 53975, 59254, 59254, 53975, 40022, 53975, 47914, 47914, 47914, 40022, 40022, 56399, 46173, 56399, 56399, 46173, 48873, 46173, 45695, 48873, 48873, 45695, 45695]
> Expected: a value less than or equal to <15>
>      but: <16> was greater than <15>
> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
> 	at org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest.testMultiplexWithMaxUsage(RoundRobinConnectionPoolTest.java:261)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by lorban** [comment]
The problem is that some port is used 6 times while a connection should only be used at most 3 times:
```
port   count
59254  6 
34711  3 
48870  3 
54265  3 
47029  3 
56236  3 
54232  3 
45679  3 
53975  3 
47914  3 
40022  3 
56399  3 
46173  3 
48873  3 
45695  3
```

But since this test only fails with H3 that uses UDP instead of TCP, there is nothing preventing a port to be reused as soon as the connection over it is closed. This means that the result above where port 59254 was used 6 times could be due to the port being reused by the OS for two distinct connections.
