### ISSUE TITLE
Add jetty-documentation into jetty distribution under demo-base

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#732]
we should have the generated jetty-documentation available under the demo-base so it is easy for people to have a local browsable copy of the documentation

**Comment by WalkerWatch** [comment]
@jmcc0nn3ll Were you thinking of doing this as a PDF or HTML generation?

**Comment by joakime** [comment]
I vote for HTML, as its generally more accessible, and also searchable via command line.

People searching for concepts with grep, for example, will see hits in the documentation about the concept as well, giving clues to the role of that documentation based on its filename.

**Comment by jmcc0nn3ll** [comment]
html, mounting it via the resourcehandler or defaultservlet

we still have a fair amount of work to get the pdf generation clean, i figure I'll look at wiring up proper epub at that time as well
