### ISSUE TITLE
Rework HttpInput.Interceptor contract

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#7326]
**Target Jetty version(s)**
12.0.x

**Enhancement Description**
The current `HttpInput.Interceptor` contract was too loosely defined during its inception and grew to something very convoluted and barely maintainable despite a simple original requirement. Ideally, this should be reworked by breaking the existing contract and proposing a much saner one.

For the simple idea of _give me some content and I'll return a modified one_ here is what the implementation must account for:

* managing the lifecycle of the content produced by the channel
* managing the lifecycle of the content produced by the interceptor
* both of the above can be the same instance
* the interceptor does not have to read all the content it is given in a single shot
* the interceptor can return null to signify it did not generate any content from what it accepted to read of the given content
* the interceptor can return a special content from a normal content
* the interceptor can return a normal content from a special content

An example of of a requirement that seems straightforward at first but has tremendous impact on the implementation is the following sentence in the `Interceptor.readFrom()` javadoc: *There is no requirement that all the data is consumed by the interceptor*.

This simple sentence has a massive implementation impact as it implicitly means that the responsibility of lifecycling the passed content is in the hands of the caller, as well as the lifecycle of the returned content while at the same time it is implicitly assumed that the passed content instance can simply be returned. This creates a suite of special cases that every combination of the entries in the list above makes larger and more complex to maintain.

**Comment by sbordet** [comment]
#9038 removed the `HttpInput.Interceptor` class from the EE10 implementation.
