### ISSUE TITLE
jetty-slf4j-impl missing from BOM

### ISSUE THREAD

**Issue by mleegwt** [eclipse/jetty.project#7327]
**Jetty version(s)**
Jetty 10 and 11

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
The package jetty-slf4j-impl is missing from the BOM.

**How to reproduce?**
Check the pom.xml in the jetty-bom project.

**Comment by joakime** [comment]
Opened PR #7328 - reviewed all maven modules in our build and added the missing entries.
