### ISSUE TITLE
Response does not allow setCharacterEncoding to be called after getOutputStream

### ISSUE THREAD

**Issue by guw** [eclipse/jetty.project#733]
I was debugging a failing encoding test that seems to work with Jetty 8 but fails with Jetty 9. I traced the issue down to the client side falling back to decoding the data with ISO default instead of UTF-8. The reason for that is missing charset information on the mime type.

Debugging the server I noticed that we do call `Response.getOutputStream` before `Response.setCharacterEncoding`.

Reading through the JavaDoc of `Response.setCharacterEncoding` I noticed that this use case should be fine. It says:

> This method can be called repeatedly to change the character encoding. This method has no effect if it is called after `getWriter` has been called or after the response has been committed.

As we do not call `getWriter` but `getOutputStream` we should be good and Jetty should set the encoding properly.

**Comment by guw** [comment]
I believe the check in `setCharacterEncoding` is too strict. It should allow changing the encoding when `_outputType == OutputType.STREAM || _outputType == OutputType.NONE`.

**Comment by joakime** [comment]
As long as you don't write, flush, append, or close the stream from `getOutputStream()` before using `setCharacterEncoding()` then it seems like it should be supported.

**Comment by guw** [comment]
Nope. That doesn't work. As soon as one calls `getOutputStream` `_outputType` will be set to `STREAM` ([line 836](https://github.com/eclipse/jetty.project/blob/a1cc30c751e886db397813855cb9e792bbfd893d/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L836)). This prevents `setCharacterEncoding` from doing anything ([line 988](https://github.com/eclipse/jetty.project/blob/a1cc30c751e886db397813855cb9e792bbfd893d/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L988)).

**Comment by gregw** [comment]
Fixed with a _outputType!-OutputType.WRITER, which perfectly matches the javadoc.
Added unit tests
