### ISSUE TITLE
Large WebSocket payloads with permessage-deflate hang on 10.0.7 

### ISSUE THREAD

**Issue by SerCeMan** [eclipse/jetty.project#7351]
**Jetty version(s)**

10.0.7

**Java version/vendor** `(use: java -version)`

openjdk version "11.0.13" 2021-10-19 LTS

**OS type/version**

MacOS/Linux

**Description**

Starting from 10.0.7, large WebSocket messages hang when the WebSocket connection is initiated with the `permessage-deflate` extension. The "hanging" behaviour is only observed starting from 10.0.7, and the code works correctly on other 10.0.x and 9.4.x versions. The [`jetty-10.0.7-websocket-permessage-deflate`](https://github.com/SerCeMan/jetty-10.0.7-websocket-permessage-deflate) can help to reproduce the issue, the test that sends a single payload never completes. 

```java
    @Test
    void testDeflate() throws Exception {
        var client = new WebSocketClient();
        client.setMaxBinaryMessageSize(5 * 1024 * 1024);
        client.start();
        var latch = new CountDownLatch(1);
        var req = new ClientUpgradeRequest();
        req.addExtensions("permessage-deflate");
        var session = client.connect(new Socket(latch), URI.create("ws://localhost:8083/ws"), req).get();
        latch.await(3, TimeUnit.SECONDS);
        session.close();
    }
```

Removing the extension from the test, or changing the jetty version from `10.0.7` to `10.0.6` in [build.gradle](https://github.com/SerCeMan/jetty-10.0.7-websocket-permessage-deflate/blob/master/build.gradle#L16-L17) makes the test pass. 

From what I understand, the test fails on `10.0.7` when the message size exceeds `PerMessageDeflateExtension#DEFAULT_BUF_SIZE`.

**How to reproduce?**

The reproducer project: https://github.com/SerCeMan/jetty-10.0.7-websocket-permessage-deflate.

**Comment by lachlan-roberts** [comment]
@SerCeMan Thanks for the report and the reproducer, very strange that we didn't already have a failing test to reproduce this.

It is caused by an interaction between the changes from PR https://github.com/eclipse/jetty.project/pull/6635 and the iterating callback from `PerMessageDeflateExtension`. We are looking at a solution to fix this now and hopefully get this into the 10.0.8 release which will be soon.
