### ISSUE TITLE
How to decide on maxRequests in QoSFilter?

### ISSUE THREAD

**Issue by NageshSoni** [eclipse/jetty.project#7371]
Jetty version - 9.4.43.v20210629

Java version - 1.8.0_201

While implementing the QoSFilter I read in Java Doc of QoSFilter that this filter could be deployed with a maxRequest limit slightly smaller than the containers thread pool.
How to decide the maxRequests based on my throughput and connector threads?

Sample Implementation of QoSFilter:

```java
public class PriorityFilter extends QoSFilter {

    @Override
    public void init(FilterConfig filterConfig) {
        super.init(filterConfig);
        setMaxRequests(5);
        setSuspendMs(51000);
    }


    @Override
    protected int getPriority(ServletRequest request) {
        HttpServletRequest servletRequest = (HttpServletRequest) request;
        System.out.println("getPriority " + Integer.parseInt(servletRequest.getHeader("priority")));
        return Integer.parseInt(servletRequest.getHeader("priority"));
    }
}
```

**Comment by sbordet** [comment]
If your requests are processed by blocking code, then you typically want to have `QoSFilter.maxRequests < QueuedThreadPool.maxThreads` to cover the worst case, where `maxRequests` threads are blocked, but you have a few threads left to process incoming requests until they hit the `QoSFilter` where they are either suspended or rejected.

`QoSFilter.maxRequests` indicates the max number of concurrent requests that `QoSFilter` allows to be processed, so it is only loosely related to the throughput.

For example, if you have `QoSFilter.maxRequests=5`, but each request is taking only 1 ms, you can have a throughput of 5000 request/s; if each request is taking 1 s, you can only have a throughput of 5 requests/s.
In both cases you can only have 5 concurrent requests.

**Comment by NageshSoni** [comment]
While your experiments when your requests were processed by blocking code, then How much was QoSFilter.maxRequests less than QueuedThreadPool.maxThreads to achieve a particular TPS?

**Comment by sbordet** [comment]
As I said, that depends on your application. You have to try and see.

**Comment by NageshSoni** [comment]
I am implementing the below scenario:
Max threads in QueuedThreadPool: 200
Reserved threads in QueuedThreadPool: 180
maxRequests in QoS Filter: 180
Latency for request: 5 sec

Initially 180 requests are sent and after 1 second another 180 requests are sent.

For initial 180 requests all the reserved threads are available. But after serving the initial 180 request, it took around 1 minute to free all reserved threads.

Please let me know what could be the problem that it took around 1 minute to free all reserved threads.

Please find below the graph of the availableReservedThreads for the above scenario.

![image](https://user-images.githubusercontent.com/49056975/152999794-8ff423a6-0590-47e9-8011-b4c17a070480.png)

**Comment by sbordet** [comment]
@NageshSoni this is how reserved thread works.

Why do you expect the reserved thread to be freed? 

After the first batch of 180 requests has been served (after about 5 seconds), they will be readily available to handle the second batch of 180 requests.
