### ISSUE TITLE
How to write context.xml in jetty 9/10?

### ISSUE THREAD

**Issue by avin15cs** [eclipse/jetty.project#7372]
Jetty Version: 9.4.44.v20210927

Java Version: java-11-openjdk-11.0.7.10_windows_redhat
My application uses embedded  jetty 6 and now we are upgrading it to jetty 9. I had few queries regarding which, I had raised it in stackoverflow:
https://stackoverflow.com/questions/69907675/is-this-correct-way-of-adding-contexts-in-jetty-9-and-10
 Firstly, Thank you so much Joakim for helping me out on this.
 
I had few more queries on this, for which I needed help. In context.xml, which you had shared:
```
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.FileProxyServlet</Arg>
          <Arg>/resource/</Arg>
          <Call name="setInitParameter">
            <Arg>fileContentBase</Arg>
            <Arg><SystemProperty name="jetty.base" default="."/>/../../resource/</Arg>
          </Call> 
```
I have created resource directory as you had mentioned in comment, but whenever I hit this URL http://localhost:9096/cts/resource/ , I get below response:
_This site can’t be reached. The webpage at http://localhost:9096/cts/resource/ might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE_
And through Postman, I got this response: 
```
	<h2>HTTP ERROR 500 insufficient content written</h2>
	<table>
		<tr>
			<th>URI:</th>
			<td>/cts/resource/</td>
		</tr>
		<tr>
			<th>STATUS:</th>
			<td>500</td>
		</tr>
		<tr>
			<th>MESSAGE:</th>
			<td>insufficient content written</td>
		</tr>
		<tr>
			<th>SERVLET:</th>
			<td>com.documentum.cts.webservices.remote.FileProxyServlet-61cbad07</td>
		</tr>
```

What has gone wrong here?
Just to add on, Somehow i dont understand how, but One which I had proposed context.xml in above stackoverflow question, when I use i.e:

```
    <New class="org.eclipse.jetty.servlet.ServletContextHandler">
        <Arg>
            <Ref id="Contexts"/>
        </Arg>
        <Arg>/cts/resource</Arg>
        <Set name="resourceBase">
            <SystemProperty name="jetty.base" default="."/>/../resource/</Set>
        <Call name="addServlet">
            <Arg>com.docu.cts.webservices.remote.FileProxyServlet</Arg>
            <Arg>/</Arg>
        </Call>
    </New>
```
I am getting server Ok response, which is pretty weird.

**Comment by sbordet** [comment]
> HTTP ERROR 500 insufficient content written

This means that your application, probably `FileProxyServlet` has declared a `Content-Length` header that does not match the actual size of bytes written.

For example:

```java
void service(HttpServletRequest request, HttpServletResponse response) {
  response.setContentLength(2);
  response.getOutputStream().write(new byte[1]);
}
```

It may be possible that the file is stored with one encoding (e.g. UTF-8), but you write it back as ISO-8859-1.

**Comment by avin15cs** [comment]
Hi @sbordet,

What could be the solution for this? Please find my FileProxyServlet class.

[FileProxyServlet.txt](https://github.com/eclipse/jetty.project/files/7846708/FileProxyServlet.txt)

**Comment by sbordet** [comment]
`FileProxyServlet` code is wrong. 
Simplest is to remove the call `resp.setContentLength( (int)theFile.length() );`.

**Comment by avin15cs** [comment]
Hi @sbordet ,

That worked, thanks!

**Comment by avin15cs** [comment]
Hi @sbordet ,
I am facing new issue now due to above change.
 
 For this servlet:
 ```
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.FileProxyServlet</Arg>
          <Arg>/output/*</Arg>
          <Call name="setInitParameter">
            <Arg>fileContentBase</Arg>
            <Arg><Property name="documentum.cache.dir" default="." />/</Arg>
          </Call>
        </Call>

```
where `documentum.cache.dir=C:/cache`

on hitting the link:
http://localhost:9096/cts/output/hello.txt 

It always downloads file with 0 size, though actual file is available under directory cache. Not sure, what has gone wrong!

**Comment by avin15cs** [comment]
Do I need to add anything more in my context.xml Or do I need to add anything in FileProxyServlet(I have shared above) so that actual file gets downloaded?
