### ISSUE TITLE
Migrating from ancient jetty

### ISSUE THREAD

**Issue by XakepSDK** [eclipse/jetty.project#7378]
**Jetty version**
to 9.4

**Java version**
to 1.8

**Question**
I am migrating ancient service from old jetty to newer to support at least Java 8 VM.
Project uses spring and configures jetty using xml files.

There are calls to `ServletContextHandler#addFilter`
In old jetty, `addFilter` accepts `FilterHolder holder, String pathSpec, int dispatches`
In new jetty, `addFilter` accepts `FilterHolder holder, String pathSpec, EnumSet<DispatcherType> dispatches`

What `DispatcherType` is equivalent of `0` dispatches in old jetty?

**Comment by sbordet** [comment]
The value `null` for the `EnumSet` provides the default dispatch mode, so `addFilter(holder, path, null)` is equivalent.

**Comment by XakepSDK** [comment]
Thanks!
