### ISSUE TITLE
Change scope of maven plugin dependencies

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#7408]
**jetty-10.0.x**

Building the jetty-maven-plugin shows this error info:

> INFO] --- maven-plugin-plugin:3.6.2:helpmojo (exec-plugin-doc) @ jetty-maven-plugin ---
> [ERROR] 
> 
> Maven dependencies of Maven Plugins should be in provided scope.
> Please make sure that all your dependencies declared in POM whose group ID is
> org.apache.maven have set '<scope>provided</scope>' as well.
> In the future this error will break the build.
> 
> The following dependencies are in wrong scope:
>  * org.apache.maven:maven-plugin-api:jar:3.8.4:compile
>  * org.apache.maven:maven-model:jar:3.8.4:compile
>  * org.apache.maven:maven-artifact:jar:3.8.4:compile
>  * org.apache.maven:maven-core:jar:3.8.4:compile
>  * org.apache.maven:maven-settings:jar:3.8.4:compile
>  * org.apache.maven:maven-settings-builder:jar:3.8.4:compile
>  * org.apache.maven:maven-builder-support:jar:3.8.4:compile
>  * org.apache.maven:maven-repository-metadata:jar:3.8.4:compile
>  * org.apache.maven:maven-model-builder:jar:3.8.4:compile
>  * org.apache.maven:maven-resolver-provider:jar:3.8.4:compile
> 
> Please fix your build!

and

> [INFO] --- maven-plugin-plugin:3.6.2:descriptor (default-descriptor) @ jetty-maven-plugin ---
> [ERROR] 
> 
> Maven dependencies of Maven Plugins should be in provided scope.
> Please make sure that all your dependencies declared in POM whose group ID is
> org.apache.maven have set '<scope>provided</scope>' as well.
> In the future this error will break the build.
> 
> The following dependencies are in wrong scope:
>  * org.apache.maven:maven-plugin-api:jar:3.8.4:compile
>  * org.apache.maven:maven-model:jar:3.8.4:compile
>  * org.apache.maven:maven-artifact:jar:3.8.4:compile
>  * org.apache.maven:maven-core:jar:3.8.4:compile
>  * org.apache.maven:maven-settings:jar:3.8.4:compile
>  * org.apache.maven:maven-settings-builder:jar:3.8.4:compile
>  * org.apache.maven:maven-builder-support:jar:3.8.4:compile
>  * org.apache.maven:maven-repository-metadata:jar:3.8.4:compile
>  * org.apache.maven:maven-model-builder:jar:3.8.4:compile
>  * org.apache.maven:maven-resolver-provider:jar:3.8.4:compile
> 
> Please fix your build!

**Comment by janbartel** [comment]
Also applies to jetty-9.4.x, and jetty-11.0.x.

**Comment by janbartel** [comment]
@olamy can you take a look at this one? I tried locally changing the dependencies with `org.apache.maven` gid to `provided` for the jetty-maven-plugin pom.xml, but the build still complained that:

> Maven dependencies of Maven Plugins should be in provided scope.
> Please make sure that all your dependencies declared in POM whose group ID is
> org.apache.maven have set '<scope>provided</scope>' as well.
> In the future this error will break the build.
> 
> The following dependencies are in wrong scope:
>  * org.apache.maven:maven-model:jar:3.8.4:compile
>  * org.apache.maven:maven-settings:jar:3.8.4:compile
> 
> Please fix your build!

But those dependencies are are transitive of the `org.apache.maven.maven-core` artifact, which is itself `provided`. Qu'est-ce qui se passe?!

**Comment by olamy** [comment]
fixed
