### ISSUE TITLE
Jetty Apache JSP 9.4

### ISSUE THREAD

**Issue by XakepSDK** [eclipse/jetty.project#7409]
**Jetty version**
9.4.44.v20210927
**Java version**
1.8

**Question**
I'm upgrading from mortbay to eclipse jetty.
My project uses JSP.
I added apache-jsp dependency from jetty

When i run my application and open main page, this error is thrown:
```
Caused by: java.lang.NullPointerException
	at org.apache.jasper.JspCompilationContext.getTldResourcePath(JspCompilationContext.java:563)
```
I found that `org.apache.jasper.servlet.JasperInitializer` should be invoked in order to `getTldResourcePath` work properly. So `TldCache` is not null and error is not thrown.

Some googling suggested that this class should be loaded automatically with Java SPI, but i haven't found SPI config file in `META-INF/services`

How do i solve this issue?

My dependencies:
```xml
<jetty.version>9.4.44.v20210927</jetty.version>

<!-- Servlet container -->
<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server -->
<dependency>
	<groupId>org.eclipse.jetty</groupId>
	<artifactId>jetty-server</artifactId>
	<version>${jetty.version}</version>
</dependency>
<!-- JSP -->
<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/apache-jsp -->
<dependency>
	<groupId>org.eclipse.jetty</groupId>
	<artifactId>apache-jsp</artifactId>
	<version>${jetty.version}</version>
</dependency>
<!-- JSTL -->
<dependency>
	<groupId>org.eclipse.jetty</groupId>
	<artifactId>apache-jstl</artifactId>
	<version>${jetty.version}</version>
</dependency>
```

**Comment by XakepSDK** [comment]
This is solution to my issue:
https://www.eclipse.org/jetty/documentation/jetty-9/index.html#embedded-examples

**Comment by joakime** [comment]
We also have embedded-jetty-jsp example project at
https://github.com/jetty-project/embedded-jetty-jsp

There are branches for the major versions of Jetty showing how to manage JSP on embedded Jetty.
