### ISSUE TITLE
Jetty maven plugin configured from jetty.base

### ISSUE THREAD

**Issue by UnsungHero97** [eclipse/jetty.project#741]
Is there a recommended way to update `${jetty.base}` with custom values and settings? Should all configuration happen only in `${jetty.base}/start.ini`, or only in `${jetty.base}/start.d/*.ini`, or only in `${jetty.base}/etc/*.xml`, or a mixture of all?

**Comment by WalkerWatch** [comment]
The recommended usage is to perform the configuration either in `${jetty.base}/start.ini` **OR** `${jetty.base}/start.d/*.ini` but **not both**. Doing so can lead to crossed wires and leave you with lots of issues. 

I am working on making this clearer in the documentation, and we are restructuring the Jetty distribution to help alleviate some of this confusion in Jetty 9.4. If you are a new user to Jetty, I would personally recommend managing your configuration in separate ini files in the ${jetty.base}/start.d/ directory. This approach helps compartmentalize your setup and reduces time sorting through a large `${jetty.base}/start.ini` file. That said, the choice is completely up to you.

In regards to editing XML files, it is generally not needed. Jetty 9.1 introduced the module system which you can read more about [here](https://www.eclipse.org/jetty/documentation/9.3.x/startup-modules.html). Basically, modules themselves reference properties in the XML files which can be configured. When a module is activated it creates an ini file (or appends to start.ini) all the properties that can be set. 

If you have any additional questions, please let me know.

**Comment by UnsungHero97** [comment]
That certainly clears up some confusion, thanks! I'm looking forward to more clarity on this topic in the docs. I like the idea of `${jetty.base}/start.d/*.ini` being the place for custom configuration; much easier than XML. I do have a follow-up question regarding my current use case.

My production server runs Jetty as outlined in the docs. However, during development, I tend to run Jetty from IntelliJ via the `jetty-maven-plugin`. Doing so requires configuring Jetty in the `pom.xml` file, and I haven't been able to figure out how to use `${jetty.base}/start.d/*.ini` config files for this use case. At the moment, I'm stuck maintaining the `${jetty.base}/start.d/*.ini` files for production, but also duplicating the logic in XML config files that I can reference in `pom.xml` for development. Not ideal.

Any suggestions?

**Comment by gregw** [comment]
@UnsungHero97, the jetty maven plugin predates the existance of jetty-base or ini files.    Now that we have them, it is indeed a good question.... can the plugin be configured from a jetty-base rather than in XML?

This could be difficult to achieve, but I have turned this issue into a feature request so we can consider it... probably for 9.4.x if not 10.0.x

**Comment by gregw** [comment]
@janbartel your thoughts?

**Comment by joakime** [comment]
To accomplish this the `jetty-maven-plugin` would need to know and/or configure for the `jetty.home` directory.

We can borrow the pattern used in the `cargo-maven-plugin` on how they handle this sort of distribution directory configuration.

You can also do the opposite in a far easier way, just make your project a `jetty.base` and stick a `start.ini` in it skipping the need for `jetty-maven-plugin` entirely.

**Comment by nosknut** [comment]
Can someone please tell me where on my computer the jetty.base file is stored?

**Comment by joakime** [comment]
"jetty.base" is not a file, its a directory, one that you create.

Example:

```
$ mkdir /opt/web/mybase
$ cd /opt/web/mybase

# Enable a few modules
$ java -jar /opt/jetty/jetty-home-9.4.11.v20180605/start.jar --add-to-start=http,deploy,webapp,websocket
INFO  : webapp          initialized in ${jetty.base}/start.ini
INFO  : server          transitively enabled, ini template available with --add-to-start=server
INFO  : mail            transitively enabled
INFO  : servlet         transitively enabled
INFO  : annotations     transitively enabled
INFO  : transactions    transitively enabled
INFO  : threadpool      transitively enabled, ini template available with --add-to-start=threadpool
INFO  : plus            transitively enabled
INFO  : deploy          initialized in ${jetty.base}/start.ini
INFO  : security        transitively enabled
INFO  : websocket       initialized in ${jetty.base}/start.ini
INFO  : jndi            transitively enabled
INFO  : http            initialized in ${jetty.base}/start.ini
INFO  : client          transitively enabled
MKDIR : ${jetty.base}/webapps
INFO  : Base directory was modified

# Start Jetty
$ java -jar /opt/jetty/jetty-home-9.4.11.v20180605/start.jar
2018-07-11 10:44:32.706:INFO::main: Logging initialized @2928ms to org.eclipse.jetty.util.log.StdErrLog
2018-07-11 10:44:33.056:INFO:oejs.Server:main: jetty-9.4.11.v20180605; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 9+181
2018-07-11 10:44:33.070:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/web/mybase/webapps/] at interval 1
2018-07-11 10:44:33.098:INFO:oejs.AbstractConnector:main: Started ServerConnector@350aac89{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-07-11 10:44:33.099:INFO:oejs.Server:main: Started @3321ms
```

The jetty-home ships with many modules that you can enable, to see the list ...

```
$ cd /opt/web/mybase
$ java -jar /opt/jetty/jetty-home-9.4.11.v20180605/start.jar --list-modules
```

To see the active configuration ...

```
$ cd /opt/web/mybase
$ java -jar /opt/jetty/jetty-home-9.4.11.v20180605/start.jar --list-config
```

**Comment by janbartel** [comment]
I think this use case is now covered by the mvn jetty:run-distro goal.
