### ISSUE TITLE
QoSFilter.setMaxRequests throws NullPointerException

### ISSUE THREAD

**Issue by bu3** [eclipse/jetty.project#7414]
**Jetty version(s)**
9.4.44
**Java version/vendor** `(use: java -version)`
openjdk version "11.0.10" 2021-01-19 LTS

**OS type/version**
macOS 11.6.2

**Description**
I'm trying to use the QosFilter into an existing Spring application but if I try to tune the filter calling `setMaxRequests` at configuration time, it throws the following NullPointer exception:
```
Caused by: java.lang.NullPointerException: null
	at org.eclipse.jetty.servlets.QoSFilter.setMaxRequests(QoSFilter.java:351)
```
this is the code I'm using to create a Spring Bean with the QosFilter:
```
@Bean
public QoSFilter sfdcJettyQualityOfServiceFilter(MyQoSProperties properties) {
    QoSFilter qoSFilter = new QoSFilter();
    qoSFilter.setSuspendMs(properties.getSuspendMs());
    qoSFilter.setWaitMs(properties.getWaitMs());
    qoSFilter.setMaxRequests(properties.getMaxRequests());

    return qoSFilter;
}
```
I think it blows up because `QosFilter.init()` method has not been called yet at that stage and the private property `_passes` is null [here](https://github.com/eclipse/jetty.project/blob/25306366d4b5d2cdea3eea07861a5d3d145683d6/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/QoSFilter.java#L345).

**How to reproduce?**
- creating a SpringBoot application and trying to load the QosFilter in a `@Configuration` annotated class

**Comment by janbartel** [comment]
@bu3  thanks for the report we'll take a look. In the meanwhile, as a workaround, I note that all our unit tests set these properties by calling `setInitParam`, eg:

``` java
        FilterHolder holder = new FilterHolder(QoSFilter.class);
        holder.setInitParameter(QoSFilter.MAX_REQUESTS_INIT_PARAM, x);
```

**Comment by bu3** [comment]
Nice! I will give it a try. Thanks a million @janbartel
