### ISSUE TITLE
Jetty-12 Handler.handle boolean return?

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7424]
**Jetty version**
12

**Question**

The current proposed signature for a `Handler` in jetty-12 is:
```java
    boolean handle(Request request, Response response) throws Exception;
```
Where the `Request` class extends `Callback` and is used to asynchronously signal success or failure of handling the request.   The boolean return is used only to indicate that this handler will be handling the request and has undertaken to call `succeeded()` or `fail(x)`.

This allows us to keep a `Handler` structure similar to Jetty<=11 like:
```
 server
   +- StatsHandler
   |     +- ContextHandlerCollection
   |           +- ContextA
   |           |     +- SomeHandler
   |           +- ContextB
   |                 +- SessionHandler
   |                       +- ServletHandler
   +- ErrorHandler
```
The boolean return allows:
 + The `Server` to know that no `Handler` has accepted the request, and thus it needs to call the `ErrorHandler` to generate a 404.
 + The  `ContextHandlerCollection` to know if a context has accepted the request (by contextPath, virtual host and/or connector name)

The problem with this approach is what if the Handler needs to wait for something (eg external DB) to decide if it will handle the request or not?
If the handler blocks waiting to know if it will return true or not, then it will block all the handling.

Now currently, this is not a huge problem as we invoke handle with a blocking invokcation anyway, as it might be a ServletHandler that calls a servlet that blocks in the normal IO.   So whilst it will often be invoked with a selector thread, it will never be invoked with the last selector thread. Thus blocking will not block the server.

So two questions:
 1) Do we need to fix this?
 2) How do we fix this?

**Comment by gregw** [comment]
@sbordet @lorban @joakime @lachlan-roberts @janbartel @olamy thoughts?

**Comment by gregw** [comment]
We can't just create any method like `boolean Handler.accept(Request request)` as that creates the same problem, just in a different method.

**Option 1**
To avoid blocking, we need to allow boolean to be delivered later, so perhaps something like:
```java
interface Handler
{
    void handle(Consumer<Boolean> handled, Request request, Response response) throws Exception;
}
```

This would allow a handler to delay accepting/refusing a request.  The request would not be offered to the next handler until a false was consumed. If a true is consumed, then the request is not offered to anymore handlers.

This does open the possibility of a request being succeeded/failed before the handled consumer is set, but that's no different to the current succeeded/failed before returning.
There is also the bad state of the request being succeeded/failed, but the handled consumer is given false.... but again that is an issue that already exists as false can be returned and the request succeeded.

**Option 2**
So how about this. Rather than `Request implements Callback` we could have `Request implements Supplier<Callback>`.  A handler would indicate that it accepts handling of a request by calling `Supplier.get()` to access the Callback.  This way, the handler cannot succeed/fail the request without first accepting it.

Hmmm but it doesn't help with the original problem, if the handler needs to wait for a remote answer to decide if it should handle or not, then it needs to delay calling `Supplier.get()` until it knows, and then that API gives the handler no way to asynchronously say that it will not handle the request.

**Option 3**
We need some way for the handler to asynchronously say Yes or No to handling the request, and only be given the Callback in the case that is says yes.   So maybe there is a `Function<Boolean, Callback>` either passed to the handler or as part of the request, that is called with true or false.  Passing false always gives a false return and the server/handler then continues to call other handlers. Passing true will return the Callback to use to succeed/fail the request.          This has the right handler semantic, but now the problem comes with the separate callback, as the handler may with to accept the request but then pass it onto other handlers.  In this case the handler signature doesn't allow the callback to be passed unless we do the whole `Function<Boolean, Callback>` shuffle again.     I have tried separating the callback from the request before and I didn't find a way of doing that elegantly 

**Option 4**
The request can continue to be a callback, but it is only activated once the request is accepted.  Handlers will have to call `request.accept(boolean)`.... but then for nested handlers, does each level have to do that call?  

**My current conslusion**
I don't like any of the options.... I'm not sure we really need to fix this but it would be nice to solve the callback completion with a false return paradox.

thoughts and/or suggestions?

**Comment by sbordet** [comment]
@lorban and I brainstormed the following:

```java
public interface AsyncHandler
{
    // The CF can also be a Consumer<Boolean> or similar.
    void accept(Request message, CompletableFuture<Boolean> handle);
    void handle(Exchange exchange);
}

public class Exchange implements Callback
{
    public Exchange(Request request, Response response)
    {
    }
    ...
}
```
The idea is to split the "accept" of the request and its `boolean` return value from the actual handling into 2 methods in `AsyncHandler`.

Also, use `Exchange` to separate the `Request` from the `Callback`, so that it's much easier to just wrap the callback without having to wrap the whole request, with static utility methods such as `Exchange.from(exchange, Callback.from(...));

#### Pros 
We can implement the async `boolean` decision to handle or not.
It solves the "wrong return paradox", as `handle()` is only invoked when the return value is true.
API seems clean enough and minimal.

#### Cons
- Looping over the list of handlers goes from a plain `for` loop to something more complicated that uses capturing lambdas and an `AtomicReference` state machine -- JIT won't understand it and won't apply usual optimization such as loop unrolling, etc.
- The implementation is more complicated to follow as it is based on callbacks rather than sequential, top-to-bottom code.

### Is it worth it?
It all boils down to whether it's worth or not. 99% of the times, it would be possible to return the `boolean` without blocking.
in the 1%, @lorban suggested that it may be possible to have an outermost `AsyncHandlerContainer` that returns true immediately, and it will e.g. spawn a new thread to process its children, and if they all return false, it can produce a 404.
Still blocking, though, although in a different thread.

If `AsyncHandlerContainer` has more knowledge about its children, it can ask them whether they will accept before calling `handle()` so it would be possible for a child handler implementation to implement the boolean return value asynchronously, remember it, and return it when its `handle()` is called (these children will have an API similar to the proposed new `AsyncHandler` API above).
`AsyncHandlerContainer` would allow to be fully async, but without having to pay the cost (capturing lambdas, async-state-machine loop) in the server implementation (just in`AsyncHandlerContainer`).

However, if the Jetty 12 design proceeds with the boolean return value, and later we have to change it to be fully async, it will be difficult (but possible) to retrofit the implementation and it will be a large effort to change the implementation accordingly (I did that for CometD).
It would be best to take this decision sooner rather than later.
Sticking with the boolean return value for handle means that we retain the "wrong return paradox" problem, but again it only happens in a very small percentage of cases (although it does highlight an API smell).
Splitting accept and handle is still possible in the boolean return value case for accept, and it will solve the "wrong return paradox".

### Takeaways
I think `Exchange` is a good abstraction that can be used in both models.

It may be possible to keep the implementation simple (boolean return and `for` loop) and confine async handlers into a last-in-the-list `AsyncHandlerContainer` which manages many `AsyncHandler` children (where the last is always a 404 `AsyncHandler`).
It won't be possible to manage more than 1 of such `AsyncHandlerContainer`, since the first will always return true and the second will never be invoked.

**Comment by gregw** [comment]
The `Exchange` is an idea worth trying out... but it does have an extra CON.  You can't just wrap the request or the response, as you will also have to wrap/recreate the exchange to return the wrapped request, so in essence you will always be wrapping the callback anyway, but with an extra object.   Still worthwhile playing with.

I agree that the calling tree of accept is rather complex.

How about if the 1% of handlers that need to block before returning true, just return true and if the answer comes back no, then we give them an easy way to redispatch the request to the whole(or part) of the handler tree, but this time they themselves return false if they see the request again.

**Comment by gregw** [comment]
Latest ideas from call are:

```java
interface Handler
{
    boolean accept(MetaData.Request request);
    void handle(Request request, Response response) throws Exception;
}
```

The other idea that came out of the call was to not have the `Content.Provider` interface as part of request, and instead have it obtainable from a method on the request:
```java
interface Request
{
    //...
   Content.Provider getContentProvider(Runnable onContentAvailable);
}
```
We need to work out if this really is a getter - ie can it be called multiple times and the Runnable changed?

Finally similar discussion about doing:

```java
interface Handler
{
    boolean accept(MetaData.Request request);
    void handle(Request request, Response response, Callback callback) throws Exception;
}
```

All worthy to be experimented with.

**Comment by gregw** [comment]
@sbordet @lorban I'm looking at implementing:
```java
interface Handler
{
    boolean accept(MetaData.Request request, ConnectionMetaData connection);
    void handle(Request request, Response response) throws Exception;
}
```

And it is mostly working out OK.  However, the main issue I have is how can a handler like `ContextHandlerCollection` remember it's decision from between the call to `accept` and the call to `handle`?  The `ContextHandlerCollection` does a bit of work with context path and host to select a "branch" of `ContextHandlers`, that it tries in turn until one returns true (after confirming contextpath, virtual host, connector name and possibly other criteria).     So that is trivial to move to an `accept` method, and the args suggested above are sufficient.   But we don't want to have to repeat that work on the call to `handle` as it is non-trivial and a waste of time to do it twice.     We could store the chosen handler as a request attribute, but that still feels like an unnecessary hash set and lookup (remember we went to a lot of effort to avoid creating the attribute map in the first place as most requests don't need it).

I've thought about returning the selected handler from `accept`, but that doesn't work with wrapping as intermediary handlers need to be given the opportunity to wrap the request/response (eg for stats or gzip etc.)

Any other ideas?


Perhaps keeping a single method with void return, but stateful access to the `Callback` from the request, rather than the request being a `Callback`:

```java
interface Request
{
    Callback willHandle();
    boolean isHandled();
}

interface Handler
{
    void handle(Request request, Response response) throws Exception;
}
```

So I might give that a go first..... but if you have any other suggestions (even if just better names that "willHandle") please say.

**Comment by gregw** [comment]
@lorban @sbordet this last options works pretty well... but perhaps needs some work or at least some renaming.    Let's continue discussion of that option in the PR: #7437

**Comment by gregw** [comment]
Informal feedback from @sbordet on #7437 is "yeah but naaaah!" :(

So we either have to live with what we've got.... or accept the definciencies of #7437..... or come up with something else.

The key impediment of something else is the cost of finding a handler in the fully asynchronous acceptance style and of making async accpeetance work well with request/response wrapping.     The search for a handler for a request needs to be very efficient and can't be based on creating and checking completable futures for each and every check.    It needs to perform really efficiently in the cases of accepting a request or rejecting a request.  It can be a little less efficient in the case of "maybe" (i.e. might accept the request but needs to think about it).

Perhaps a tri-state return would work: Accept/Reject/Maybe, with the expensive async synchronization mechanism only be created and checked in the case of a `Maybe`?

Or we just live with either of the non-async approaches and make it easy for a hander to accept a request, but then to decide to re-run it if it later decides it cannot handle it.

**Comment by gregw** [comment]
@lorban @sbordet another idea.

We could make `Response implements Callback` and then make the response only available if a handler accepts a request.  So in the simple form:

```java
    public void handle(Request request) throws Exception
    {
        Response response = request.accept();
        response.setStatus(200);
        response.setContentType(MimeTypes.Type.TEXT_PLAIN_UTF_8.asString());
        response.write(true, response, BufferUtil.toBuffer("Hello"));
    }
```

We could then have an alternate method that would allow for a future accept/reject like:
```java
    interface FutureAccept
    {
        Response accept();
        void reject();
    }

    public void handle(Request request) throws Exception
    {
        FutureAccept accepting = request.futureAccept();
        
        Callback callback = Callback.from(
            () ->
            {
                Response response = accepting.accept();
                response.setStatus(200);
                response.setContentType(MimeTypes.Type.TEXT_PLAIN_UTF_8.asString());
                response.write(true, response, BufferUtil.toBuffer("Hello"));
            },
            t -> accepting.reject()
        );
        
        someAsyncProcess(callback);
    }
```

if a handler calls future callback, then internally a CompletableFuture would be created and further iteration looking for another handler would only be done if reject is called.

Still a lot of work for very little gain.

**Comment by gregw** [comment]
@simone, @lorban, Lot's of good progress made on this subject, both in my branch (now jetty-12.0.x) and Simone's branch.   I think we are converging on some good ideas/compromises, but still a little way to go.   So I thought a summary if the ideas/issues here would be worthwhile.

From the jetty-12-ng-sbordet branch we have:

```java
interface IncomingRequest extends Attributes
{
}

interface Incoming extends IncomingRequest
{
    void accept(Processor processor) throws Exception;
    boolean isAccepted();
}

interface Request extends IncomingRequest, Callback, Executor, Content.Provider
{
}

interface Processor
{
    void process(Request request, Response response) throws Exception;
}

interface Handler extends LifeCycle, Destroyable
{
    void accept(Incoming request) throws Exception;
}
```

For me, the goodness in that branch is that accept takes a `Processor`, so the semantic of delayed processing (needed if we wait for input, or read form/multipart async before handling) is much better supported and separated from the accept step.

However, there is also badness:

 + Naming needs work Processors are really Handlers, but yeah let's get the concepts right first and then look at the names.
 + Too many similar classes: `Request`, `Incoming` and `IncomingRequest` share too many methods
 + Too many classes.
 + Wrappers get lost.  Specifically, any wrapping of `Incoming` done by a chain of `accept(Incoming)` calls will be lost once the accept is called, so that the `Processor` is going to be called with the unwrapped `Request` and any wrapping done on the `Incoming` will need to be done again.  There is also a little bit of wierdness with processing lambdas that might see/capture a wrapped request which is different to the base request passed into the process call.  I think this is the biggest problem that needs to be fixed with this approach.
 + `Request` still is-a `Callback`. See latest jetty-12.0.x branch with the `Callback` moved to the response, which works better.... but maybe it should be entirely separate or in an `Exchange` class.

The other goodness is that perhaps something like `Processor` can be used to clean up demand API.... but let's defer that until we have a better idea here.


So the current jetty-12.0.x branch has:
```java
interface Handler extends LifeCycle, Destroyable
{
    void handle(Request request) throws Exception;
}

interface Request extends Attributes, Executor, Content.Provider
{
    Response accept();
}

interface Response
{
    Callback getCallback();
}
```

This has the goodness that:

+ `Response` and `Callback` are only accessible after `accept()`.  
+ because their is no callback to process, the wrapped request doesn't need to be captured nor passed to anybody, it is just there already to be used.
+ response wrapping happens naturally at the right time, so the response wrapper is not lost.

However, it has the badness of:

 + the `Content.Provider` methods are available on `Request` during accept.  They are actually disabled at that point, but still would be better to not make them available.
 + the delay handling semantic is not well supported, as the handler can start handling immediately after calling `accept()` rather than waiting for a callback that can be intercepted and delayed etc.

I can forgive the first badness.... but the second feels like it should be fixed and perhaps we can fix the first issue as well.   I think the solution is something like `accept(Processor)` from jetty-12-ng-sbordet,  but not exactly that.

So let's break things down into all the basic components and see if we can re-assemble them into something with all the goodness and none of the badness.  Let's start with a very basic immutable request:
```java
interface Request extends Attributes
{
}
```
This is the immutable request, with the only stateful aspect being the Attributes that can be attached to it.   It is not a `Content.Provider`, so no input methods. It is not an `Executor` because it is not used to handle, thus no scoping is needed.   The request exposes the data from `MetaData.Request` and `ConnectionMetaData`.   Perhaps it could be `Request extends MetaData.Request` ????   Anyway,  If you want to change/rewrite the request, then you have to wrap it.  Once wrapped we need to keep hold of that wrapped request to pass to any processor.

It is this base request that we should offer to handlers (I think the name `offer(Request)` is better than `handle(Request)`:
```java
interface Handler
{
    void offer(Request request);
}
```
But we need something to accept the offer on.  We could add an accept method to `Request` (as in current branch), but then it is in the API for all later phases that don't need it.   Or alternately we could just return the `Processor`,  giving each handler a chance to wrap it on the way back,  but then we again lose the wrapped `Request`.      In order to not lose the wrapped request, I think we need something like:
```java
interface Handler
{
    void offer(Request request, BiConsumer<Request,Processor> acceptor);
}
```

This is not that nice in some circumstance as both the request and the acceptor might need to be wrapped (eg ContextHandler), but that might be a minority of cases?   So let's go on anyway.

So what does the Processor need to process the request?   I think broken down to the simplest components we could have something like:
```java
interface Processor
{
    void process(Request request, Content.Producer content, Response response, Executor executor, Callback callback)
}
```
Actually to be symmetric we could factor out the write methods from `Response` into some kind of `Content.Consumer`, but let's not get too crazy with our deconstruction just yet.  In fact we could probably do some reconstruction at this point with something like:

```java
interface Exchange extends Content.Producer, Executor, Callback
{
    Request getRequest();
    Response getResponse();
}

interface Processor
{
    void process(Exchange exchange)
}
```

There are lots of variations of the `Exchange` theme, but I think you get the idea.. the call to process somehow makes everything else needed available.


I don't love the `BiConsumer`, but if we want to callback a processor and not lose the wrapped request, I don't see the alternative.... unless we give up and always capture the request and not pass it at all in the process:

```java
interface Request extends Attributes
{
}

interface Handler
{
    Processor offer(Request request);
}

interface Processor
{
    void process(Content.Producer content, Response response, Executor executor, Callback callback)
}
```
So if the request is needed in process, then it has to be captured.

**Comment by gregw** [comment]
So in summary, there are two approaches, neither perfect:

**Handler is passed immutable request and calls accept that returns the mutable stuff** (ie `interface Request { Response accept(); }`). This has the PROS:
   + handling can commence immediately after call to accept, using wrapped request and response.
   + no need to rescope a process callback to a context

But it has the CONS:
   - additional methods on `Request` that are not suitable for all phases of handling.
   - clumsy to do delayed processing as it has to instead look like delayed acceptance.

**Handler is offered immutable request and provides a Processor that is called with the mutable stuff** (ie `void accept(Processor processor)`). This has the PROS:
  + API can be made appropriate for all phases.
  + delayed processing semantic works really nicely

But it has the CONS:
  + Wrapped request can be lost. Needs clumsy BiConsumer to capture wrapper.
  + Context needs to be reestablished on process call

**Comment by gregw** [comment]
More thoughts... let's look at this from the other side, ie the handler implementation.

Currently a simple handler is like:
```java
void handle(Request request)
{
    Response response = request.accept();
    Content content = request.readContent();
    Callback callback = response.getCallback();
    // generate response
    callback.succeeded();
}
```

This is nice and simple.  The response can be generated directly after the accept, in the same scope, with the same classloader, looking at the same wrapped request. BUT, the handling can't be delayed externally without blocking (eg in accept), and the read API is available before accept, even if disabled.

The later problem could be solved with an Exchange class like:

```java
void handle(Request request)
{
    Exchange exchange = request.accept();
    Content content = exchange.readContent();
    Response response = exchange.getResponse();
    Callback callback = exchange.getCallback();
    // generate response
    callback.succeeded();
}
```

But that still doesn't allow the processing to be delayed.

The alternative in @sbordet branch looks like:


```java
void handle(Incoming request)
{
    request.accept((req, res) ->
    {
        Content content = req.readContent();
        Callback callback = res.getCallback();
        // generate response
        callback.succeeded();
    }
}
```

So the lambda allows for the processing to be delayed and the handler reads pretty well.  BUT, any wrapping done on the `Incoming request` is lost and the lambda can "see" both `request` and `req`, potentially causing confusion as they are slightly different classes and could be wrapped differently.  Also, more work needs to be done to ensure context is established on the callback to the lambda.

Maybe we just give up and always capture like :

```java
void handle(Incoming request)
{
    request.accept(() ->
    {
        Content content = request.readContent();
        Response response = request.getResponse();
        Callback callback = response.getCallback();
        // generate response
        callback.succeeded();
    }
}
```

The context will still need to be established twice, but there will not be 2 versions of the request that both need to be wrapped.

**Comment by sbordet** [comment]
The latter would still have the problem of exposing read APIs before `accept()`, and forces an always capturing lambda.

**Comment by sbordet** [comment]
Is there a valid use case where wrapping of `Incoming` should be carried over in the handling? Why would a `Handler` need to modify e.g. the headers _before_ accepting? In fact, in my branch the wrapping of `Incoming` is only necessary to enable the wrapping of `Request` at handling time.

Apart naming and many classes (which however are necessary to isolate behaviors), I don't think there is a problem with wrapping, as the wrapping of `Incoming` is just an enabler for later wrapping of `Request`, not something you want to carry over.

See for example `RewriteHandler` in my branch.

**Comment by gregw** [comment]
@sbordet there are many use-cases to wrap before accepting:
 + A context handler will wrap to alter the path, so it's contained handlers can match on it
 + GzipHandler should wrap to change the headers so that down stream handlers known that IF they accept and read content, it will not be gzipped.
 + A rewrite handler does exactly that - rewites the request to change who might handle it.

Even if there were not reasons to wrap incoming, I believe it is confusing to have two versions of the request that may have been wrapped differently, both available to the lambda (one of them by capture).

**Comment by sbordet** [comment]
@gregw good point, I see now there are legit cases to wrap with modification before `accept()`.

However, who does that has access to the modifications, so:

```java
class RewriteHandler extends Handler.Abstract
{
    @Override
    public void accept(Incoming request) throws Exception
    {
        HttpURI.Immutable newURI = HttpURI.build(request.getHttpURI()).path("/new").asImmutable();
        super.accept(new RewriteIncoming(request, newURI));
    }

    private class RewriteIncoming extends Incoming.Wrapper
    {
        private final HttpURI.Immutable newURI;

        private RewriteIncoming(Incoming delegate, HttpURI.Immutable newURI)
        {
            super(delegate);
            this.newURI = newURI;
        }

        @Override
        public HttpURI getHttpURI()
        {
            return newURI;
        }

        @Override
        public void accept(Processor processor) throws Exception
        {
            getWrapped().accept((rq, rs) ->
            {
                processor.process(new Request.Wrapper(rq)
                {
                    @Override
                    public HttpURI getHttpURI()
                    {
                        return newURI;
                    }
                }, rs);
            });
        }
    }
}
```

Yes there is a double wrapping, but it's accessible.

Alternatively, if the only difference between an incoming request and a handling request is the access to the content, we can offer a constructor: `Request.Wrapper(IncomingRequest.Wrapper r, Content.Provider p)`, so we can pass the wrapped incoming... but yes, with this constructor the wrappers are confusing.

**Comment by gregw** [comment]
After the call this morning, @sbordet and I decided that we both don't hate the `BiConsumer<Request, Processor>` approach above.... at least not enough to not give it a go.  So I'll try an implementation over the next few days.

**Comment by gregw** [comment]
See #7566 for an attempt at this.   Mostly working, but I don't really like it.

**Comment by gregw** [comment]
Note that there are two things we are trying to fix here:  A) remove IO methods from Request that are not active before accept and B) elegant way to delay processing after a request has been accepted.

#7566 does both, but it is primarily about B. 

The current HEAD of 12.0.x could easily by made to solve A by make `accept` return an `Exchange` rather than a `Response`.... but I just don't see A as that big of a deal.

**Comment by sbordet** [comment]
> See https://github.com/eclipse/jetty.project/pull/7566 for an attempt at this. Mostly working, but I don't really like it.

What you don't like?

**Comment by gregw** [comment]
@sbordet the code is really hard to read and understand. You get a calling frame into nested handlers that can have 0 or more request wrappers plus 0 or more acceptor wrappers that then have a calling stack back out via the nested acceptor wrappers, each potentially applying a processor wrapper that then had a calling stack back through the processors, each may potentially wrap the exchange, probably so it can just wrap the response and/or callback

**Comment by gregw** [comment]
Oops wrong button.
When you get a line of code that has four  lambdas and two explicit wrappers, then it is getting tooooooo complex.

It is technically correct and i can't fault the model. But i think the tail is wagging the dog. We are letting the 1% case make the 99% more complex and difficult.

**Comment by joakime** [comment]
@gregw this can be closed now, right?

**Comment by gregw** [comment]
yes
