### ISSUE TITLE
ConstraintSecurityHandler response code  to be 403 or 405?

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#7425]
Jetty version - 9.4.26

Java version - IBM JDK8

Question
We have enabled ConstraintSecurityHandler for TRACE and MOVE for http uris. So, when this method is hit, what should be the response code, 403 or 405? Or it is left to the implementation?

**Comment by 4devwithgit** [comment]
@joakime Any info about this? Thanks!

**Comment by janbartel** [comment]
The http spec says that for `TRACE` the server should respond with the body of the request in a 200 response: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html.

`MOVE` is not part of http1.1 - maybe the webdav spec can help you out.

**Comment by 4devwithgit** [comment]
Yeah, and if we want to block the TRACE (or some specific method), I understand we have to defined Constraint, ConstraintMapping and ConstraintSecurityHandler. However, when we are doing this, its giving the response code of 403, not 405. How to control that? This is the specific question I have.
I see a helpful link, but doesnt answer it completely. 
https://stackoverflow.com/questions/29348328/java-embedded-jetty-is-accepting-http-trace-method/70799903#70799903

For example, in the below requests, it returns 403 not 405,
curl -v --insecure -X TRACE  http://xyz.com:14033/hello    
* About to connect() to xyz.com port 14033 (#0)
*   Trying 10.10.10.10...
* Connected to xyz.com (10.10.10.10) port 14033 (#0)
> TRACE /hello HTTP/1.1
> User-Agent: curl/7.29.0
> Host: xyz.com:14033
> Accept: */*
> 
< **HTTP/1.1 403 Forbidden**
< Content-Length: 0
< 
* Connection #0 to host xyz.com left intact

**Comment by joakime** [comment]
If you just want to reject specific methods, regardless of which context gets them, use an `HttpConfiguration.Customizer`.

``` java
package jetty;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.EnumSet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.eclipse.jetty.http.HttpMethod;
import org.eclipse.jetty.http.HttpStatus;
import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.server.HttpConnectionFactory;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.handler.AbstractHandler;
import org.eclipse.jetty.server.handler.DefaultHandler;
import org.eclipse.jetty.server.handler.HandlerList;

public class RejectHttpMethodsDemo
{
    public static class BanHttpMethods implements HttpConfiguration.Customizer
    {
        private final EnumSet<HttpMethod> bannedMethods;

        public BanHttpMethods(EnumSet<HttpMethod> bannedMethods)
        {
            this.bannedMethods = bannedMethods;
        }

        @Override
        public void customize(Connector connector, HttpConfiguration channelConfig, Request request)
        {
            HttpMethod httpMethod = HttpMethod.fromString(request.getMethod());
            if (bannedMethods.contains(httpMethod))
            {
                request.setHandled(true);
                request.getResponse().setStatus(HttpStatus.METHOD_NOT_ALLOWED_405);
            }
        }
    }

    public static void main(String[] args) throws Exception
    {
        Server server = new Server();

        HttpConfiguration httpConfig = new HttpConfiguration();
        httpConfig.addCustomizer(new BanHttpMethods(EnumSet.of(HttpMethod.TRACE, HttpMethod.MOVE)));
        ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory(httpConfig));
        connector.setPort(9090);
        server.addConnector(connector);

        HandlerList handlers = new HandlerList();
        handlers.addHandler(new AbstractHandler()
        {
            @Override
            public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
            {
                baseRequest.setHandled(true);
                response.setCharacterEncoding("utf-8");
                response.setContentType("text/plain");
                response.getWriter().printf("Hello, You asked to %s %s, that is all%n", baseRequest.getMethod(), baseRequest.getRequestURI());
            }
        });
        handlers.addHandler(new DefaultHandler());

        server.setHandler(handlers);
        server.start();

        try
        {
            HttpClient httpClient = HttpClient.newHttpClient();

            demoRequest(httpClient, server.getURI().resolve("/apple"), "GET");
            demoRequest(httpClient, server.getURI().resolve("/banana"), "TRACE");
            demoRequest(httpClient, server.getURI().resolve("/cherry"), "MOVE");
        }
        catch (Throwable t)
        {
            t.printStackTrace();
        }
        finally
        {
            server.stop();
        }
    }

    private static void demoRequest(HttpClient httpClient, URI path, String method)
    {
        try
        {
            HttpRequest httpRequest = HttpRequest.newBuilder(path)
                .method(method, HttpRequest.BodyPublishers.noBody())
                .build();
            HttpResponse<String> httpResponse = httpClient.send(httpRequest, HttpResponse.BodyHandlers.ofString());
            System.out.printf("HTTP %s %s Response Status: %d%n", httpRequest.method(), httpRequest.uri(), httpResponse.statusCode());
            System.out.println(httpResponse.body());
        }
        catch (IOException | InterruptedException e)
        {
            e.printStackTrace();
        }
    }
}
```

**Comment by janbartel** [comment]
@4devwithgit I can't really comment because you haven't shown the code where you set up the constraints. Perhaps you are seeing the 403 because you have configured that authentication is required, but you have configured no roles. That equates to a 403 response.

**Comment by 4devwithgit** [comment]
Thanks @janbartel .

Below is the code snippet where constraint is added. With role, I suppose you are referring to the, constraint.setRoles(new String[] { "" }); Is this mandatory?

``` java
private ConstraintSecurityHandler addConstraints(ConstraintSecurityHandler csh) {
		//TODO Read all http properties from disk on instantiation of the class
		Properties properties = Manager.getPropertiesFromDisk(PSHttpConstants.HTTP_PROPERTIES_FILENAME);

		Constraint c = new Constraint();
		c.setAuthenticate(true);

		String method = null;
		int i = 1;
		while((method = properties.getProperty(FORBIDDEN_METHOD_PROPERTY + "." + i)) != null) {
			ConstraintMapping cm = new ConstraintMapping();
			cm.setConstraint(c);

			String path = properties.getProperty(FORBIDDEN_METHOD_PROPERTY + "." + i + "." + FORBIDDEN_METHOD_PATH_PROPERTY);

			if(path !=null) {
				if (LOG.debug) {
					LOG.logDebug(CLASS_NAME + ".addConstraints() - Forbidden HTTP method " + method + " at " + path + " to " + this);
				}
				cm.setMethod(method);
				cm.setPathSpec(path);
			}
			else {
				if (LOG.debug) {
					LOG.logDebug(CLASS_NAME + ".addConstraints() - Forbidden HTTP method " + method + " to " + this);
				}
				cm.setMethod(method);
				cm.setPathSpec("/*");
			}
			i++;
			csh.addConstraintMapping(cm);
		}

		return csh;
```

**Comment by janbartel** [comment]
@4devwithgit you have said that the `Constraint` requires authentication, but named no `roles` that are permitted. The servlet spec, pg 13-106, section 13.8.4:

> The authentication characteristics of the request must satisfy any authentication
> and role requirements defined by the constraints. If this rule is not satisfied
> because access has been precluded (by an authorization constraint naming no
> roles), the request shall be rejected as forbidden and a 403 (SC_FORBIDDEN)
> status code shall be returned to the user. If access is restricted to permitted roles
> and the request has not been authenticated, the request shall be rejected as
> unauthorized and a 401 (SC_UNAUTHORIZED) status code shall be returned to
> cause authentication. If access is restricted to permitted roles and the
> authentication identity of the request is not a member of any of these roles, the
> request shall be rejected as forbidden and a 403 (SC_FORBIDDEN) status code
> shall be returned to the user.

**Comment by 4devwithgit** [comment]
@janbartel Thanks for the feedback.
I did test with the below code, with "setRoles" call
		Constraint c = new Constraint();
		**c.setRoles(new String[] { "" });**
		c.setAuthenticate(true);
But still, it doesnt change anything for me, and continues to return 403 code for TRACE.

**Comment by 4devwithgit** [comment]
> If you just want to reject specific methods, regardless of which context gets them, use an `HttpConfiguration.Customizer`.
> 
> ```java
> package jetty;
> 
> import java.io.IOException;
> import java.net.URI;
> import java.net.http.HttpClient;
> import java.net.http.HttpRequest;
> import java.net.http.HttpResponse;
> import java.util.EnumSet;
> import javax.servlet.ServletException;
> import javax.servlet.http.HttpServletRequest;
> import javax.servlet.http.HttpServletResponse;
> 
> import org.eclipse.jetty.http.HttpMethod;
> import org.eclipse.jetty.http.HttpStatus;
> import org.eclipse.jetty.server.Connector;
> import org.eclipse.jetty.server.HttpConfiguration;
> import org.eclipse.jetty.server.HttpConnectionFactory;
> import org.eclipse.jetty.server.Request;
> import org.eclipse.jetty.server.Server;
> import org.eclipse.jetty.server.ServerConnector;
> import org.eclipse.jetty.server.handler.AbstractHandler;
> import org.eclipse.jetty.server.handler.DefaultHandler;
> import org.eclipse.jetty.server.handler.HandlerList;
> 
> public class RejectHttpMethodsDemo
> {
>     public static class BanHttpMethods implements HttpConfiguration.Customizer
>     {
>         private final EnumSet<HttpMethod> bannedMethods;
> 
>         public BanHttpMethods(EnumSet<HttpMethod> bannedMethods)
>         {
>             this.bannedMethods = bannedMethods;
>         }
> 
>         @Override
>         public void customize(Connector connector, HttpConfiguration channelConfig, Request request)
>         {
>             HttpMethod httpMethod = HttpMethod.fromString(request.getMethod());
>             if (bannedMethods.contains(httpMethod))
>             {
>                 request.setHandled(true);
>                 request.getResponse().setStatus(HttpStatus.METHOD_NOT_ALLOWED_405);
>             }
>         }
>     }
> 
>     public static void main(String[] args) throws Exception
>     {
>         Server server = new Server();
> 
>         HttpConfiguration httpConfig = new HttpConfiguration();
>         httpConfig.addCustomizer(new BanHttpMethods(EnumSet.of(HttpMethod.TRACE, HttpMethod.MOVE)));
>         ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory(httpConfig));
>         connector.setPort(9090);
>         server.addConnector(connector);
> 
>         HandlerList handlers = new HandlerList();
>         handlers.addHandler(new AbstractHandler()
>         {
>             @Override
>             public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
>             {
>                 baseRequest.setHandled(true);
>                 response.setCharacterEncoding("utf-8");
>                 response.setContentType("text/plain");
>                 response.getWriter().printf("Hello, You asked to %s %s, that is all%n", baseRequest.getMethod(), baseRequest.getRequestURI());
>             }
>         });
>         handlers.addHandler(new DefaultHandler());
> 
>         server.setHandler(handlers);
>         server.start();
> 
>         try
>         {
>             HttpClient httpClient = HttpClient.newHttpClient();
> 
>             demoRequest(httpClient, server.getURI().resolve("/apple"), "GET");
>             demoRequest(httpClient, server.getURI().resolve("/banana"), "TRACE");
>             demoRequest(httpClient, server.getURI().resolve("/cherry"), "MOVE");
>         }
>         catch (Throwable t)
>         {
>             t.printStackTrace();
>         }
>         finally
>         {
>             server.stop();
>         }
>     }
> 
>     private static void demoRequest(HttpClient httpClient, URI path, String method)
>     {
>         try
>         {
>             HttpRequest httpRequest = HttpRequest.newBuilder(path)
>                 .method(method, HttpRequest.BodyPublishers.noBody())
>                 .build();
>             HttpResponse<String> httpResponse = httpClient.send(httpRequest, HttpResponse.BodyHandlers.ofString());
>             System.out.printf("HTTP %s %s Response Status: %d%n", httpRequest.method(), httpRequest.uri(), httpResponse.statusCode());
>             System.out.println(httpResponse.body());
>         }
>         catch (IOException | InterruptedException e)
>         {
>             e.printStackTrace();
>         }
>     }
> }
> ```

Thanks @joakime this is working.

**Comment by 4devwithgit** [comment]
@joakime @janbartel 

So, I can change the current implementation from ConstraintSecurityHandler to using HttpConfiguration.Customizer.

1) Will this impact anything?
2) With Constraints, the methods which we were restricting was customizable/dynamic, as the methods were read from the property file, and customer can write his required method for the constraint restriction which will be add to the Constraint List. However, with HttpConfiguration.Customizer, how can I make it customizable for any methods as it takes **Enum**, where enum uses static declarations?

**Comment by 4devwithgit** [comment]
@janbartel 

So, we didnt yet get to the root of issuing 405 Vs 403. You told about "roles", but it made no difference with or without it.

Regards

**Comment by joakime** [comment]
I chose Enum as we have the HttpMethod enum already, and it handles all of the case-insensitive comparison logic built-in.

You can use Strings and skip the Enum/EnumSet/HttpMethod classes entirely if you wish, just make sure you handle the comparison properly.

The code for ConstaintSecurityHandler has only 1 .sendError(403) and no .setStatus(int) calls.
Just for the record, 405 (Method Not Allowed) will never be produced from a Constraint based rule, you'll only ever see a 403 (Forbidden).

**Comment by janbartel** [comment]
Well, you have configured that the only role that is permitted for those methods is `empty string`. Is the user that you're testing with configured as being in the role `empty string`? Probably not. Test with a proper role name, or use the special role name defined by the spec of `**` that means any authenticated user.


> @janbartel
> 
> So, we didnt yet get to the root of issuing 405 Vs 403. You told about "roles", but it made no difference with or without it.
> 
> Regards

**Comment by 4devwithgit** [comment]
Thanks @joakime , @janbartel  Its clear now. I am moving away from  ConstaintSecurityHandler and using HTTP addCustomizer to block the required methods, and its working for us.
Regards
Dev
