### ISSUE TITLE
Jetty-12 Content.Provider API discussion

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7432]
**Jetty version**
12

**Question**

Currently the proposed API for `Content.Provider` and Request are:
```java
interface Content
{
    interface Provider
    {
        Content readContent();
        void demandContent(Runnable onContentAvailable);
    }
}

interface Request extends Content.Provider
{
    // ...
}
```

There is some dislike of the `onContentAvailable` being passed on every call to demand.    This issue is to discuss alternatives.

**Comment by gregw** [comment]
@lorban @sbordet On the call today you suggested changing the API to:
```java
interface Content
{
    interface Provider
    {
        Content readContent();
        void demandContent();
    }
}

interface Request extends Content.Provider
{
    // ...
    Content.Provider getContentProvider(Runnable onContentAvailable);
}
```

This initially looks really attractive....  but there is kind of a "race" condition in that API.  The passed `Runnable` needs to be written in terms of a `Content.Runnable` which it does not have until the `getContentProvider`.  So you can't write code like:
```java
void dumpRequestContent(Request request)
{
    Content.Provider provider;
    Runnable dumper = () ->
    {
        while(true)
        {
            Content content = provider.readContent();
            if (content == null)
            {
                provider.demandContent();
                return;
            }
           System.err.println(content);
           content.release();
           if (content.isLast())
             break;
        }
    }
    provider = request.getContentProvider(dumper);
    dumper.run();
}
```
This does not compile because provider is not initialzed in the dumper.

It can kind of be fixed with an AtomicReference like:
```java
void dumpRequestContent(Request request)
{
    AtomicReference<Content.Provider> providerRef = new AtomicReference<>();;
    Runnable dumper = () ->
    {
        Content.Provider provider = providerRef.get();
        Objects.assertNonNull(provider);
        while(true)
        {
            Content content = provider.readContent();
            if (content == null)
            {
                provider.demandContent();
                return;
            }
           System.err.println(content);
           content.release();
           if (content.isLast())
             break;
        }
    }
    providerRef.set(request.getContentProvider(dumper));
    dumper.run();
}
```

But that feels kind of ugly and is unnecessary dereferencing. 

thoughts?

**Comment by sbordet** [comment]
Don't use a `Runnable`, but a `Consumer<Provider>`:

```java
void dumpRequestContent(Request request)
{
    // Don't return the Provider, just feed the Consumer with it.
    // Could also be a BiConsumer<Request, Provider> to avoid capturing the Request in the lambda.
    request.content(provider -> dump(provider));
}

void dump(Provider provider) 
{
    while(true)
    {
        Content content = provider.readContent();
        if (content == null)
        {
            provider.demandContent();
            return;
        }
       System.err.println(content);
       content.release();
       if (content.isLast())
         break;
    }
}
```

**Comment by gregw** [comment]
@sbordet @lorban I've made a reasonable start at making this change and you can see my progress [here](https://github.com/eclipse/jetty.project/compare/jetty-12.0.x...jetty-12.0.x-7432-noargs-demand?expand=1).

Good news is that I think it can be made to work.   Bad news is that I don't think it is either worth it, nor efficient to do so.

The change I've been working on is best summed up with:
```java
public interface Content
{
    ByteBuffer getByteBuffer();
    boolean isSpecial();
    void release();
    boolean isLast();

    interface Producer
    {
        Content readContent();

        void demandContent();
    }

    interface Provider
    {
        void content(Consumer<Producer> provider);
    }

    abstract class Processor implements Provider
    {
        protected Processor(Provider provider)
        {
            provider.content(this::onContentAvailable);
        }

        protected abstract void onContentAvailable(Content.Producer producer);
    }
```

With `Request` is a `Content.Provider` so it will pass a `Content.Producer` to any consumer passed to `content(Consumer<Content.Produce>)`, firstly on an initial call within the scope of `content` and then again once content is available and `demandContent()` has been called.    It does not work to delay the initial call to when content first arrives, as we then cannot implement `int available()` style APIs as we cannot read until demand has been met. 

So first thing is that it is a lot more confusing to work with the extra concept of a `Producer` and a `Provider`.  Perhaps better names could help, but you end up quickly in Content.ProviderProvider land!

But the main problem is that it does not actually solve the problem.  All the sanity checks that were previously needed in `demandContent(Runnable)` to ensure it wasn't called at the wrong time or with contradictory arguments still exist.  This just moves the problem to `content(Consumer<Content.Producer>)` which now has to do precisely the same checks.    But it only needs to be called once I hear you say/type already!!!   Well a) we'd still need checks to make sure it is only called once; and b) that's not actually true.  It turns out that we have at least 2 use-cases where we need multiple/different callers to `content(Consumer<Content.Producer>)`:
 1. We need to have a `consumeAll` semantic, which previously could just loop calling `readContent()` until it gets a null or EOF, which could happen regardless of any demand state.   Now we have to create a consumer, call `content(Consumer<Content.Producer>)`, deal with any ISEs due to existing demand and then finally loop on `readContent` looking for null or EOF.  This needs to happen after other content consumers, so we need to call `content(Consumer<Content.Producer>)` at least twice with different consumers.
 2. We have moved the delay dispatch until content is available from being in every connector type, to being a handler.  Previously, the handler could just `demandContent(Runnable)` and once the runnable is called it would call it's nested handlers.  This now has to create a consumer, that is called once with the producer on which we then call `demandContent` so that when the consumer is called a second time it can finally call the handler.   A lot more complex and another example of the need to call `content(Consumer<Content.Producer>)` at least twice with different consumers.

It will also create a lot more garbage as using a `Consumer<Content.Producer>` instead of a `Runnable` means that we now frequently need a capturing lambda rather than just using the reference.  In some places we need captureing lambdas that themselves create capturing lambdas:
1. We used to be able to pass the `Runnable` directly to executors like `return serializedExecutor.offer(onContentAvailable)`, but now we need to do `return serialziedExecutor(() -> onContentAvailable.accept(provider)`
2. When calling back to anything originating from within a context, we need to establish the context classloader and any other ThreadLocal magic associated with the context.   Previously, this was done in the request wrapper (which the context does anyway to set contextPath etc.) with `void demandContent(Runnable oca) { super.demandContent(() -> _context.run(oca)) }`.  Now we have to extend the `content` method to wrap the passed consumer that does the context scoping: `void content(Consumer<Content.Producer> oca) { super.content(p -> _context.run(() -> oca.accept(p)));}`

It is also more difficult to wrap requests in a way to disable content.   For example, when invoking an error handler, we wrap the request so that content is not accessible.   Previously that could be done simply and statelessly with `readContent()` returning null and `demandContent(Runnable)` simply invoking the passed Runnable.   Now we have to extend `content` to create a stateful `Provider` that will remember the passed consumer so that when it creates a nested `Provider` can invoke the remember consumer. It works but is more objects and more complexity.

**Conclusion**
 + it doesn't solve the problem, it just moves it to a different method 
 + it is somewhat more complex and confusing, as there are just more concepts, more state, more fields, more objects and more moving parts.
 + It will generate more garbage do to the need for wrapping requests to wrap consumers to wrap producers, plus more capturing lambdas etc.

Whilst there were some parts of the code that were indeed simpler/nicer, on balance I see no benefit and lots of down side.      This is my third attempt to create a no-args `demandContent` call.   For me, this is a dead end and I don't how any other approach can success whilst there is the need for different consumers of content from the one request.    I feel I've given this a good crack, and it has only served to re-enforce that `demandContent(Runnable)` is a reasonable solution. So I'm not going to invest any more time in this, but feel free to pick up this branch (or make another) to find a way to make it work.

**Comment by gregw** [comment]
closing as progress has been made and further comments/issues will come out of review
