### ISSUE TITLE
Memory leak with uplifted jetty version from 9.4.43.v20210629 to 11.0.7

### ISSUE THREAD

**Issue by techdeba901** [eclipse/jetty.project#7436]
**Jetty version(s)**
11.0.7
**Java version/vendor** `(use: java -version)`
17.0.1
**Spring boot version(s)**
2.6.2
**OS type/version**
Linux
**Description**
When jetty version is uplifted  from 9.4.43.v20210629 to 11.0.7, I overserved memory consumption of java application grows very fast and eventually dies because of OOM. So downgrading jetty version to 9.4.43.v20210629 fixes the problem.

Any pointers on how this issue can be debugged?

**Code Snippet**

``` java
private WebClient destWebClient;

@PostConstruct
	public void init() {
		SslContextFactory sslContextFactory = new SslContextFactory.Client(true);
		ClientConnector clientConnector= new ClientConnector();
		clientConnector.setSslContextFactory((SslContextFactory.Client) sslContextFactory);
		HTTP2Client http2Client = new HTTP2Client();
		http2Client.setMaxConcurrentPushedStreams(1000);
		HttpClientTransportOverHTTP2 transport = new HttpClientTransportOverHTTP2(http2Client);
		transport.setUseALPN(false);
		transport.updateBean(transport.getBean(ClientConnector.class), clientConnector);
		this.httpClient = new HttpClient(transport);
		this.httpClient.setIdleTimeout(600000);

		this.httpClient.setMaxRequestsQueuedPerDestination(5000);
		this.httpClient.setMaxConnectionsPerDestination(4);
		this.httpClient.setFollowRedirects(false);
		this.httpClient.setRemoveIdleDestinations(true);
		this.httpClient.getRequestListeners().add(new JettyClientRequestMetrics());
		try {
			httpClient.start();
		} catch (Exception e) {
			e.printStackTrace();
		}
		ClientHttpConnector httpConnector = new JettyClientHttpConnector(httpClient);
		this.destWebClient = WebClient.builder().clientConnector(httpConnector).baseUrl(extUrl).build();
	}
```
	
Following API is used to send the message

``` java
			Mono<ResponseEntity<byte[]>> MonoRsp = destWebClient
				.method(HttpMethod.resolve(contextData.getRequestEntity().getMethod().name())).uri(uri)
				.headers(hdrs -> hdrs.addAll(httpHeaaders))
				.body(BodyInserters.fromValue(body)).retrieve().toEntity(byte[].class)
				.timeout(Duration.ofMillis(perTryTimeout.getTimeMillis()))
				.onErrorResume(Throwable.class, throwable -> {
					Mono<ResponseEntity<byte[]>> rsp = Mono.just(handleError(throwable, contextData));
					return rsp;
				}).doOnCancel(() -> logger.info("Dest Request transaction has been Canceled"))
				.publishOn(Schedulers.fromExecutor(testExecutor));
```

**Comment by joakime** [comment]
Is this easy to replicate?

Two things ...

1. Try 11.0.8-SNAPSHOT available from the snapshot repository https://oss.sonatype.org/content/repositories/jetty-snapshots/
    There is a lot of updates due for release 11.0.8, perhaps one of them has helped you already.

and/or

2. Capture a heap dump when it's in the excessive memory usage mode and then analyze the dump to see what is using all of the memory.

**Comment by techdeba901** [comment]
I collected heap dump after reproducing the issue and jetty client is one of the highest contributor in memory usage.
Please find screenshots below. 

![image (1)](https://user-images.githubusercontent.com/87752557/150793877-6919fd3d-5465-4c34-8159-fa49b49c98de.png)
![image (2)](https://user-images.githubusercontent.com/87752557/150793886-9339a6b2-7e6e-4207-b773-1e7e61bb9b24.png)
![image](https://user-images.githubusercontent.com/87752557/150793892-688f9f14-ed5a-49d7-b1f7-73802a2fa0d2.png)

I tried with 11.0.8-SNAPSHOT version, but I faced the same memory leak issue.

Is there any other way to find out why this memory leak is happening?

**Comment by sbordet** [comment]
The images you posted show 17 connections occupying a mere 7 MiB, and looks a completely normal state in case you have opened 17 connections to the server and sending requests over those, so I don't see any evidence of memory leak?
Those connections are in use and so are not leaked.

You are not going to OOM for just 7 MiB, unless you have other major problems not related to Jetty.

Please take also a server dump when your system goes OOM, as explained here: https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-troubleshooting-dump.

**Comment by techdeba901** [comment]
**(I am not using jetty server only jetty reactive client is used)**

ClientHttpConnector httpConnector = new JettyClientHttpConnector(httpClient);
WebClient destWebClient= WebClient.builder().clientConnector(httpConnector).baseUrl(extUrl).build();

I had configured maxConcurrentPushedStreams and maxConnectionsPerDestination set to 1000  and 4 respectively. 

HTTP2Client http2Client = new HTTP2Client();
http2Client.setMaxConcurrentPushedStreams(1000);

HttpClientTransportOverHTTP2 transport = new HttpClientTransportOverHTTP2(http2Client);
transport.setUseALPN(false);
HttpClient httpClient = new HttpClient(transport);
this.httpClient.setMaxConnectionsPerDestination(4);

It is showing only 17 connections in the screenshot but actually the list is very high. Meaning too many connections are getting created towards the recipient. Total 6 destination FQDNs are used for testing. Hence per jetty client application only 4*6=24 connections should be created. Is this correct understanding ?
 
Moreover, all http2 requests are responded with success immediately from the stub(recipient) and there is no failure or delay in response.

Looks like this increased number of connections causing high memory consumption? Could you please explain why so many connections are getting created ?

The same traffic run with same setup and application, but only jetty client version downgraded to 9.4.43.v20210629 does not cause rise in memory consumption at all.

**Comment by sbordet** [comment]
Can you please take an `HttpClient` dump?

You should cause the faulty state, and then trigger a call to `HttpClient.dump()` or `HttpClient.dumpStdErr()` and report the dump in this issue.

It is correct that if you use `maxConnectionsPerDestination=4` and only 6 domains then you should have 24 total connections. This may vary depending on protocol negotiations but the number should be small.
Unfortunately, so far there is no evidence of what you are saying, so that is why the `HttpClient` dump is important.

Double check your application, as we have tests that prove that we do not open more connections than specified. You may have hit a corner case, so again the `HttpClient` dump will show what's going on.

@lorban rings a bell to you?

**Comment by lorban** [comment]
No, there is nothing I can see that looks suspicious. A `HttpClient` dump would certainly help figuring out what's going on, but sharing your heap dump (if you can) could be helpful too.

**Comment by techdeba901** [comment]
This is the httpclient  dump collected from the application. I have attached it.
[http-dump.txt](https://github.com/eclipse/jetty.project/files/7949941/http-dump.txt)

**Comment by sbordet** [comment]
The `HttpClient` dump shows that the client is bombed with a large number of requests that it tries to send to backend destinations that are slow to process the requests.

Each destination has a max of 4 connections only, each with 250 multiplexed HTTP/2 requests, so the destination has to handle 1000 concurrent requests and it probably cannot.

This makes the client queue up requests (about 3 k for each destination), so the memory blows up.
It's not much a memory leak but more an overloaded client.

From the dump it just seems an overloaded client, and 9.4.x would not behave any different than 11.0.7.

However, you may have hit a corner case, so is this reproducible?
Are you sure it's not the destination server that it is being slow and that happened to be when you switched Jetty version?

What's the throughput with 9.4.x and what with 11?

**Comment by bp1990** [comment]
[http-dmp3.txt](https://github.com/eclipse/jetty.project/files/8439083/http-dmp3.txt)

We tried updating Jetty to 11.0.8 and sent requests to two servers(test1.com and test4.com) at the rate of 3K and collected the http dumps(attached) on OOM. We even tried to use -XX:+HeapDumpOnOutOfMemoryError and -XX:ErrorFile to collect the heap dump and error log, but we didn't get any logs in it. The other way we tried was to collect the heap dump using Jprofiler. Please suggest the right way to analyse this issue and help us find the cause for memory leak.

**Comment by sbordet** [comment]
The dump above shows a perfectly normal, idle, `HttpClient` with 1 destination that has 4 connections, that have been used each for ~2.5M requests (so a total of ~10M requests).

The associated `ByteBufferPool` shows no leaks.

I don't see the large number of connections that you are reporting, so we need more evidence from you that there is a problem.

So far, I still don't see any problem.
