### ISSUE TITLE
ContextHandler.getAliasChecks() breaks Spring Boot

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#7440]
**Jetty version(s)**
9.4.45

**Description**
In 9.4.44, `ContextHandler.getAliasChecks()` returned a mutable collection, and Spring Boot's `JettyServletWebServerFactory` was calling `ContextHandler.getAliasChecks().clear()` -- instead of `ContextHandler.clearAliasChecks()`.

In 9.4.45, the collection returned by `getAliasChecks()` is now immutable, so `clear()` now throws `UnsupportedOperationException`.

**Comment by sbordet** [comment]
@lachlan-roberts `getAliasChecks()` returns an immutable collection from the work on #7059 in commit (e0beeea4803d8f2750386652402e122cb9ccf4aa).

I would revert it back to a mutable collection only in 9.4.x (keep it immutable in 10.0.x+), unless there are strong reasons against.
We should also file a PR to Spring Boot to use `clearAliasChecks()` instead.

@joakime thoughts?

**Comment by joakime** [comment]
I agree, lets not break the API for spring-boot on Jetty 9.

**Comment by olamy** [comment]
done here https://github.com/spring-projects/spring-boot/issues/29552

**Comment by gregw** [comment]
Can we add something to our pre-release checks to avoid breaking spring in future?

**Comment by olamy** [comment]
we have one once release is staged maybe a weekly/nightly build to test our snapshots against spring?

**Comment by joakime** [comment]
@gregw the pre-release checks (namely the cometd build+test) is how this was discovered.

**Comment by joakime** [comment]
The change on the spring side was merged in PR spring-projects/spring-boot#29555

**Comment by sbordet** [comment]
Fixed by #7443.
