### ISSUE TITLE
How to write multiple contexts in a single context.xml?

### ISSUE THREAD

**Issue by avin15cs** [eclipse/jetty.project#7442]
**Jetty version**
9.4
**Java version**
Open JDK 11.0.7
**Question**
Hi, 
I want to write separate contextHandler for each context in a single context.xml file. Currently my context.xml has following:
```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
  <Call name="addHandler">
    <Arg>
      <New class="org.eclipse.jetty.servlet.ServletContextHandler">
        <Set name="contextPath">/cts</Set>
        <Set name="resourceBase"><Property name="jetty.base" default="." />/</Set>
        <Set name="sessionHandler">
          <New class="org.eclipse.jetty.server.session.SessionHandler"/>
        </Set>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.TransformationServlet</Arg>
          <Arg>/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.MonitorServlet</Arg>
          <Arg>/monitor/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.BlazonJobServlet</Arg>
          <Arg>/blazon/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.CapabilityServlet</Arg>
          <Arg>/getCapabilities/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.CanExecuteServlet</Arg>
          <Arg>/canExecute/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.GetOccupancyServlet</Arg>
          <Arg>/getOccupancy/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.CleanupJobServlet</Arg>
          <Arg>/delete/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.FileProxyServlet</Arg>
          <Arg>/output/*</Arg>
          <Call name="setInitParameter">
            <Arg>fileContentBase</Arg>
            <Arg><Property name="jetty.base" default="." />/../cache/</Arg>
          </Call>
        </Call>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.FileProxyServlet</Arg>
          <Arg>/resource/*</Arg>
          <Call name="setInitParameter">
            <Arg>fileContentBase</Arg>
            <Arg><Property name="jetty.base" default="." />/../resource/</Arg>
          </Call>
        </Call>
      </New>
    </Arg>
  </Call>
</Configure>
```

I want to write something like:
```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
  <Call name="addHandler">
    <Arg>
      <New class="org.eclipse.jetty.servlet.ServletContextHandler">
        <Set name="contextPath">/cts</Set>
        <Set name="resourceBase"><Property name="jetty.base" default="." />/</Set>
        <Set name="sessionHandler">
          <New class="org.eclipse.jetty.server.session.SessionHandler"/>
        </Set>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.TransformationServlet</Arg>
          <Arg>/</Arg>
        </Call>
      </New>
      <New class="org.eclipse.jetty.servlet.ServletContextHandler">
        <Set name="contextPath">/cts/monitor</Set>
        <Set name="resourceBase"><Property name="jetty.base" default="." />/</Set>
        <Set name="sessionHandler">
          <New class="org.eclipse.jetty.server.session.SessionHandler"/>
        </Set>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.MonitorServlet</Arg>
          <Arg>/</Arg>
        </Call>
      </New>
      <New class="org.eclipse.jetty.servlet.ServletContextHandler">
        <Set name="contextPath">/cts/output</Set>
        <Set name="resourceBase"><Property name="jetty.base" default="." />/../cache/</Set>
        <Set name="sessionHandler">
          <New class="org.eclipse.jetty.server.session.SessionHandler"/>
        </Set>
        <Call name="addServlet">
          <Arg>com.documentum.cts.webservices.remote.FileProxyServlet</Arg>
          <Arg>/</Arg>
        </Call>
      </New>
    </Arg>
  </Call>
</Configure>
```

I know above declaration is wrong, I am looking for correct one a

**Comment by joakime** [comment]
``` xml
<Set name="contextPath">/cts/monitor</Set>
```

Deep context paths are not supported.
That only resolves as `/cts`.

Use a `ServletContextHandler` properly and use url-patterns for those second level paths.

The only other option you have is to ditch Servlet entirely and use straight Jetty handlers.
Which means you don't have Sessions (that's a Servlet concept, which also depends on single level context paths)

**Comment by janbartel** [comment]
@avin15cs I don't know if it's your terminology or how you are really trying to use this xml file, but what you have there is _not_ what jetty calls a context xml file. A jetty context xml file applies to only a _single_ context. If you want to operate on a `ContextHandlerCollection`, that is normally configured by a _server_ xml file. See for example https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/config/etc/jetty.xml.  If you're not using the standard jetty mechanisms and you are writing embedded code, then you can call the file in which you define your `ContextHandlerCollection` anything you like, but it will confuse the heck out of those familiar with jetty. 

Also, for the example of how you would like to define your multiple contexts, you're missing a `<Call name="addHandler">` prior to each `<New class="org.eclipse.jetty.servlet.ServletContextHandler">`.

**Comment by avin15cs** [comment]
Hi @joakime ,

> The only other option you have is to ditch Servlet entirely and use straight Jetty handlers.

Can you tell more about it? How can I implement in my use case? Just trying to figure out which one could be better!

**Comment by joakime** [comment]
@avin15cs Before you consider this change ...

You will have no support for Servlet concepts, features, or APIs in the way you expect.

* No usage of 3rd party libraries based on Servlet (you have countless libraries in this space, all of them will not work with Handlers)
* No Sessions, no HttpSession (these are Servlet concepts, and your example code shows that you need this, so contemplate this gotcha before spending time switching your code)
* No built-in Authn or Authz (that's a Servlet concept, you'll be responsible for handling all of the HTTP auth logic if you need it)
* Built-in context path logic is identical to Servlet context path logic (no deep context paths, if you need deep paths, you'll have to implement it in your handlers)

### Quick primer on Handler ...

The `Server` has a `Server.setHandler(Handler)` method.

It's up to you to create a Handler tree that suits your needs.
You have ...

* [`Handler`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/java/org/eclipse/jetty/server/Handler.java) the main interface
* [`HandlerWrapper`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/java/org/eclipse/jetty/server/handler/HandlerWrapper.java) a handler that executes then executes another wrapped handler
* [`HandlerCollection`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/java/org/eclipse/jetty/server/handler/HandlerCollection.java) an unorganized set of handlers that are executed one after another until one handler says it has handled the request
* [`HandlerList`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/java/org/eclipse/jetty/server/handler/HandlerList.java) an organized list of handlers that are executed in the order you specify until one handler says it has handled the request

You can extend from [`AbstractHandler`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.7/jetty-server/src/main/java/org/eclipse/jetty/server/handler/AbstractHandler.java) to make things a bit easier for your endpoints.
It's up to your handler to test the `target` (String that represents the path being requested), to know if your handler is the one that should act on the request.
You then handle the request, produce a response, and use `Request.setHandled(true);` to tell the Handler tree to quit executing other handlers.

**Comment by janbartel** [comment]
@avin15cs your original post looks totally fine. You don't say why you want to split each of these servlets out into their own context? As Joakim says, you can't have deep context paths. So, if you have specific reasons for needing to split into multiple contexts, they all need unique context paths, eg `/monitor`, `/output` etc etc. To maintain backward compatibility with urls, you could look at using the `RewriteHandler` to transform `/cts/monitor` on an inbound request to `/monitor`. See https://www.eclipse.org/jetty/documentation/jetty-9/index.html#rewrite-handler
