### ISSUE TITLE
README.TXT and README.md

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#745]
The project currently has both a README.TXT and README.md with different contents.   We should either:
- have one or the other
- rename the README.TXT to BUILDING.TXT
- link one from the other.

My preference would be just to delete the README.TXT and to put its contents into README.md

**Comment by jmcc0nn3ll** [comment]
+1 for removing readme.txt

**Comment by gregw** [comment]
@WalkerWatch I deleted README.TXT and moved content to README.md
I'll leave open as I think the text needs to be checked.

**Comment by WalkerWatch** [comment]
This was resolved by #748, but I forgot to call it out in the commit.
