### ISSUE TITLE
Transient 400: Bad Request responses

### ISSUE THREAD

**Issue by gonphsn** [eclipse/jetty.project#7496]
jetty-9.4.45.v20220128 Compact 3 (Not yet released)

java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Zulu 8.60.0.22-SA-qnx_aarch32hf) (build 1.8.0_322-b06, profile compact3)
OpenJDK Client VM (Zulu 8.60.0.22-SA-qnx_aarch32hf) (build 25.322-b06, mixed mode)

QNX 7.0 ARMLEv7

I understand that this version is not yet released, but I have done some early testing against the 9.4.45.v20220128 tag made yesterday in anticipation of adopting the release as soon as it is made available. I am seeing a substantial regression in our application behavior where a 400 Bad Request response is being returned intermittently. The only change in our runtime environment is that the 9.4.45 Jetty version (jetty-all-compact3-9.4.45.v20220128.jar) replaces the 9.4.44 Jetty version (jetty-all-compact3-9.4.44.v20210927.jar) in our classpath. Sometimes the request goes through normally (200 response), and other times the page fails to load, or partially loads (with 400 response). The page always loads normally with 9.4.44.

The request in question is HTTP so no HTTPS/TLS negotiation is a factor.

I apologize that this description is vague, and that this 9.4.45 version might not be released yet if still a work-in-progress, but I wanted to provide early feedback to see if this change in behavior rings any bells about what may have changed between 9.4.44 and 9.4.45.20220128 that might bring about this behavior (and prevent our uptake of 9.4.45). Is there any particular release note I should be paying attention to that might require change in our application configuration? We've been using the 9.4.X branch since 9.4.26 and have not seen this type of behavior until testing with recent 9.4.45.

Thanks, please let me know if you have any questions that might help me clarify this behavior.

**Comment by joakime** [comment]
Wow! a compact3 user!

You'll have to tell us why you chose that model of release.
The Jetty 10+ releases have dropped the compact3 profile build (mainly because the newer JVMs no longer support it)

It is curious this 400 error, but without more detail we cannot hazard a guess on why you are seeing it.

Can you capture some passing and failing requests with wireshark and see what it tells you? (if you can share the wireshark capture with us that would be greatly appreciated)

**Comment by gonphsn** [comment]
Thanks for the quick reply.

Yes, our runtime environment is compact3 due to legacy resource limitations. Those restrictions should not exist in environments where we intend to deploy Jetty 10.X/11.X so dropping support for it should not be a problem for us. We have previously seen some maven issues with the -Pcompact3 build process including some jars/resources that are not used/available but otherwise the compact3 environment has never presented any serious runtime issues for us (like this 400 behavior).

I was hopeful that the behavior might clue the team into anything significant that may have changed specifically between 9.4.44 / 9.4.45 to bring about this 400 response, but I will follow up with the requested resources with our support channel, thanks!

**Comment by joakime** [comment]
The list of changes ...

https://github.com/eclipse/jetty.project/compare/jetty-9.4.44.v20210927...jetty-9.4.45.v20220128

See the tag for a list of issues resolved with this release.

https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.45.v20220128

There's only 2 changes in 9.4.45 that I think could be impacting you.
Both are cleanup of HTTP Spec violations.

One is when invalid UTF-8 sequences are used (in the HTTP request line, or in url form encoded content.)
The other is when ambiguous paths are used (eg `/a/path/%2e%2e/here`), this is not possible to resolve/normalize at the container level, it's ambiguous and would need to be passed into the webapp as-is.

Do you have any errors or warnings showing up on the server side logging that could help?

**Comment by gonphsn** [comment]
Thank you - I will review those commits today and report. The URI encoding change certainly looks interesting considering that we have | and ^ characters encoded in this URI, but reverting that specific commit did not result in restoring correct behavior. I will start cherry picking the commits from 9.4.44 -> 9.4.45 and let you know which specific item caused this behavior. Thanks!

**Comment by joakime** [comment]
Consider using `git bisect` first, to see which commit the behavior starts to change for you.

**Comment by joakime** [comment]
> The URI encoding change certainly looks interesting considering that we have | and ^ characters encoded in this URI,

If they are pct-encoded, these would not be a problem or cause a change in behavior from 9.4.44 to 9.4.45.

**Comment by gonphsn** [comment]
> Consider using git bisect first, to see which commit the behavior starts to change for you.

Yes, that is my process. I was misusing terms.

> If they are pct-encoded, these would not be a problem or cause a change in behavior from 9.4.44 to 9.4.45.

That is my observation as well - they are encoded to %7C and %5E.

**Comment by gonphsn** [comment]
I have completed my bisect exercise and it concludes that the issue:

[It is necessary to set MAX_CAPACITY to ArrayTernaryTrie/ArrayTrie #7271](https://github.com/eclipse/jetty.project/issues/7271)

is the merge/commit (c5cb1c1c24b2601e09225931778da8f856d19693) responsible for the behavior in our application. While I am not certain if this improper behavior is resulting from API misuse on our part, I am very certain that the behavior is not present prior to that merge on the 9.4.X branch.

Backing out that commit from the head of 9.4.45 restores the normal function of our application. 

Does this observation suggest any changes we should make to our application or jetty integration to adapt to this capacity checking? Thanks again for your direction.

**Comment by joakime** [comment]
@lorban heads up, this is your commit.

@gonphsn do you have any way for us to replicate this?
Or at least a wireshark capture that shows it being replicated?

**Comment by joakime** [comment]
Mis-click on close (sorry).

**Comment by gonphsn** [comment]
I have sent along a packet capture to our support contact, please let me know if there were any issues on the attachment. Thanks!

**Comment by gregw** [comment]
Any chance of running Jetty with DEBUG log turned on.  I'm trying to think how a usage of a Trie can turn into a 400?   I can only guess that it is causing problems with HTTP parsing? Debug would help

**Comment by gonphsn** [comment]
For what it is worth, we don't use/import the Trie / ArrayTrie / ArrayTernaryTrie classes anywhere for custom usage in our application. I presume the Trie usage / problem is occurring internally to jetty-all-compact3-9.4.45.v20220128.jar.

I would be happy to provide DEBUG logs but at that level the output has become so verbose that it is making the page load take > 1 hour so far.

**Comment by gregw** [comment]
@gonphsn  Can you just do logging at the level of org.eclipse.jetty.http and org.eclipse.jetty.server       ?

The fact that it is a 400 means that it is almost certainly something to do with our internal usage of tries when parsing HTTP

**Comment by joakime** [comment]
@gonphsn what is your `HttpConfiguration.getHttpCompliance()` configuration?

``` java
HttpCompliance httpCompliance = _connector.getBean(HttpConnectionFactory.class).getHttpCompliance();
System.out.println("HttpCompliance is " + httpCompliance + " (" + httpCompliance.sections() + ")");
```

**Comment by gregw** [comment]
@lorban I have found the issue I think.  If we restrict the size of the request header cache, so that it eventually fills up, then we get a failure on a subsequent lookup!

```
java.lang.ArrayIndexOutOfBoundsException: Index 201 out of bounds for length 201
	at org.eclipse.jetty.util.ArrayTernaryTrie.getBest(ArrayTernaryTrie.java:412)
	at org.eclipse.jetty.util.ArrayTernaryTrie.getBest(ArrayTernaryTrie.java:377)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1276)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1538)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:381)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:265)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
< HTTP/1.1 400 Bad Request
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 54
< Connection: close
< Server: Jetty(9.4.45-SNAPSHOT)
```

We need to be able to fill up these Tries and then still be able to lookup the headers!

**Comment by gregw** [comment]
@lorban here is a branch with a test that shows the issue: https://github.com/eclipse/jetty.project/compare/jetty-9.4.x-7496-Trie-Overflow?expand=1

**Comment by gregw** [comment]
@lorban and this is a problem in 10/11 as well: https://github.com/eclipse/jetty.project/compare/jetty-10.0.x-7496-Trie-Overflow?expand=1
here is a better link to the test in 9: https://github.com/eclipse/jetty.project/compare/jetty-9.4.x...jetty-9.4.x-7496-Trie-Overflow?expand=1

**Comment by gonphsn** [comment]
@gregw I will test out this jetty-9.4.x-7496-Trie-Overflow branch and report, need about an hour.
@joakime I will provide compliance information at that that same time.

**Comment by joakime** [comment]
@gonphsn hold off on both requests atm.
The HttpCompliance details are no longer needed.
And @lorban is testing fixes to Trie in another branch atm.

**Comment by gonphsn** [comment]
@joakime Too late! But I will test again when you give the all clear.

`HttpCompliance is RFC7230 ([CASE_INSENSITIVE_FIELD_VALUE_CACHE, METHOD_CASE_SENSITIVE, FIELD_COLON, FIELD_NAME_CASE_INSENSITIVE, NO_WS_AFTER_FIELD_NAME, NO_FIELD_FOLDING, NO_HTTP_0_9, TRANSFER_ENCODING_WITH_CONTENT_LENGTH, MULTIPLE_CONTENT_LENGTHS, NO_AMBIGUOUS_PATH_PARAMETERS])`

Testing my application with merge from commit 3de6e02172549cf48326d4aff940f2e83678277c shows that no 400 Bad Request responses have occurred, so looking much better.

Please let me know if you require anything further, thanks!

**Comment by lorban** [comment]
@gonphsn You can try the `jetty-9.4.x-7496-Trie-Overflow` branch now if you wish, it should contain the final fix.

**Comment by gonphsn** [comment]
@lorban Testing from 0716b5e17e90cb38c92d7314bbfe689fce34457e looks good for both HTTP and HTTPS load tests. Thanks!

**Comment by gonphsn** [comment]
I've tested again at the commit 09f489922c5e93f297e932c3440492a7de748063 and everything still looks good. Let me know if you require anything else from us to complete this issue. Thanks!

**Comment by lorban** [comment]
@gonphsn There is nothing more to do, we consider this issue closed.

Thank you very much for the report and your feedback!

**Comment by canon-CMI-jeffrey-brydges** [comment]
Recently upgraded to jetty-9.4.45.v20220128 to get the ALPN fix, but believe I am running into this issue. This does not happen in 9.4.44.

```2022-02-11 09:12:13,507,DEBUG,org.eclipse.jetty.http.HttpParser - [qtp848102479-250]  [::] Parse exception: HttpParser{s=HEADER,0 of -1} for HttpChannelOverHttp@2bef0009{s=HttpChannelState@46d6747c{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=0,c=false/false,a=IDLE,uri=null,age=0}
org.eclipse.jetty.http.BadMessageException: 400: Bad Request
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1640) [jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:381) [jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:265) [jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: Capacity 131072 > 65534
	at org.eclipse.jetty.util.ArrayTernaryTrie.<init>(ArrayTernaryTrie.java:151) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.ArrayTernaryTrie.<init>(ArrayTernaryTrie.java:133) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:1077) ~[jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1258) ~[jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1528) [jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	... 12 more```

**Comment by joakime** [comment]
@jeffreyb-canon I opened a new issue #7569 for this.
