### ISSUE TITLE
Issue while migrating from Jetty 6 to 9

### ISSUE THREAD

**Issue by avin15cs** [eclipse/jetty.project#7504]
**Jetty version**
9.4
**Java version**
11
**Question**
In jetty 6, when `/cts` context is called(TransformationServlet.java servlet), it picks up directory location from` /cts/output `and` /cts/resource` contexts through code:
```
 
            OUTPUT_DIR = config.getServletContext().getContext("/cts/output").getRealPath("/");
            RESOURCE_DIR = config.getServletContext().getContext("/cts/resource").getRealPath("/");

```
How can I achieve something similar using jetty9. 
One way would be adding both directory under `/cts` context using fileContentBase, but I was looking for better solution(if possible)

From **jetty.xml of Jetty 6**:
```
	<New class="org.mortbay.jetty.servlet.Context">
		<Arg>
			<Ref id="Contexts"/>
		</Arg>
		<Arg>/cts</Arg>
		<Set name="resourceBase">
			<SystemProperty name="jetty.home" default="."/>/</Set>
		<Set name="sessionHandler">
			<New class="org.mortbay.jetty.servlet.SessionHandler"/>
		</Set>
		<Call name="addServlet">
			<Arg>com.Test.TransformationServlet</Arg>
			<Arg>/</Arg>
		</Call>
	</New>
	<New class="org.mortbay.jetty.servlet.Context">
		<Arg>
			<Ref id="Contexts"/>
		</Arg>
		<Arg>/cts/output</Arg>
		<Set name="resourceBase">
			<SystemProperty name="jetty.home" default="."/>/../cache/</Set>
		<Call name="addServlet">
			<Arg>com.Test.FileProxyServlet</Arg>
			<Arg>/</Arg>
		</Call>
	</New>
	<New class="org.mortbay.jetty.servlet.Context">
		<Arg>
			<Ref id="Contexts"/>
		</Arg>
		<Arg>/cts/resource</Arg>
		<Set name="resourceBase">
			<SystemProperty name="jetty.home" default="."/>/../resource/</Set>
		<Call name="addServlet">
			<Arg>com.Test.FileProxyServlet</Arg>
			<Arg>/</Arg>
		</Call>
	</New>
```

Current context.xml:

```
        <Call name="addServlet">
          <Arg>com.Test.TransformationServlet</Arg>
          <Arg>/*</Arg>
        </Call>
        <Call name="addServlet">
          <Arg>com.Test.FileProxyServlet</Arg>
          <Arg>/output/*</Arg>
          <Call name="setInitParameter">
            <Arg>fileContentBase</Arg>
            <Arg><Property name="documentum.cache.dir" default="." />/</Arg>
          </Call>
        </Call>
        <Call name="addServlet">
          <Arg>com.Test.FileProxyServlet</Arg>
          <Arg>/resource/*</Arg>
          <Call name="setInitParameter">
            <Arg>fileContentBase</Arg>
            <Arg><Property name="documentum.resource.dir" default="." />/</Arg>
          </Call>
        </Call>
```

Hi @joakime ,
Can you please help me out here?

**Comment by joakime** [comment]
Your code from Jetty 6 was using the Servlet API improperly.

``` java
config.getServletContext().getContext("/cts/output").getRealPath("/")
```

The use of `ServletContext.getRealPath(String path)` is never guaranteed to point to a path you expect.
The `path` in that method is a "virtual path" and is a reference to a resource as seen by an HTTP client.
It can easily be a temporary directory (most common scenario), or a path deep in a jar file/war file (if war/webapp is not exploded), or the resource being referenced points to a `META-INF/resources` tree, and rarely ever a file system path related to your jetty.base.

See [`javax.servlet.ServletContext.getRealPath(String path)`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html#getRealPath-java.lang.String-) javadoc.

The old Jetty 6 Servlet Javadoc also pretty much says the same thing (with the only difference being that there is no mention of the `META-INF/resources` behavior).
https://docs.oracle.com/javaee/5/api/javax/servlet/ServletContext.html#getRealPath(java.lang.String)

Your example code essentially does this ...

First the 2 pieces of information are normalized into a path.
ServletContext "/cts/output" (this is an invalid context-path btw, deep paths are totally not supported)
Resource Path "/" (this is a resource request to a directory)
Which results in "/cts/output/"

An HTTP `GET /cts/output/` returns a piece of static content.
What is the Real Path to that HTTP resource path (static? dynamic servlet? etc?)?
First it checks the ServletContext for a url-pattern that matches the requested resource.
If it's a Servlet you'll get the RealPath to the Servlet.
Next it checks the ServletContext baseResource path and tacks on the context-specific-path portion of the request (the part after the context-path), then applies welcome-file logic, and returns that content.
This is the content that is being evaluated for `ServletContext.getRealPath(String)`

Using `.getRealPath(String)` on a directory is not supported in the way you are expecting.

The proper way to handle this is in the answer at https://github.com/eclipse/jetty.project/issues/7420#issuecomment-1024242066

**Comment by joakime** [comment]
@avin15cs  Can we close this issue?
