### ISSUE TITLE
Remove usages of ArrayQueue

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#751]
There are some suspicions of a bug in ArrayQueue, although it cannot be reproduced.
Eitherway, maintaining our own data structure is undesirable, so we should remove usage.

**Comment by sbordet** [comment]
I removed most usages in 9.3.x, only left the usages related to `XmlConfiguration`, where a list of items in XML could have been added into an `ArrayQueue`.

In 9.4.x the class has been completely removed.
