### ISSUE TITLE
Typo in AnnotationConfiguration

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#7523]
**Jetty version(s)**
10.0.x

**Description**
`AnnotationConfiguration` does:

```java
protectAndExpose("org.eclipse.jetty.util.annotations.")
```

However, package `org.eclipse.jetty.util.annotations.` does not exist.

Either `org.eclipse.jetty.annotations.` or `org.eclipse.jetty.util.annotation.`.

**Comment by sbordet** [comment]
@joakime you were the last to touch this statement. Thoughts?

**Comment by joakime** [comment]
My commit might have been a checkstyle or format commit.

This needs to be fixed.

**Comment by sbordet** [comment]
@joakime which one is it? I doubt it's `o.e.j.util.annotation` and I don't see why we need to expose `o.e.j.annotations`?
See also #7524.
