### ISSUE TITLE
Fix ClassLoaderServlet test

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#7531]
`>= jetty-9`

Test produces an exception on jetty9, but is largely commented out on jetty-10,  with a note to uncomment after `jetty-9.4.19`.

**Comment by joakime** [comment]
This was changed as part of PR #4332 originally.

We should either not use `jetty-util` as the test dependency for this ClassLoaderTest, or isolate this change to the dependency tree within tests only, and not let it spill out into the rest of the jetty reactor breaking the release process.

**Comment by janbartel** [comment]
Had a go at reinstating this in PRs #7565 and #7564 but after a great deal of discussion it seems like the fix is too difficult/complicated to achieve in the short term, so this is going onto the backburner.
