### ISSUE TITLE
Use official maven wrapper

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7537]
**Target Jetty version(s)**

Jetty 9+

**Enhancement Description**

Now that the maven wrapper is official, should we use it in our own branch builds?
This could prove useful as we need to maintain different versions of maven across Jetty 9 (for Java 8 support) thru Jetty 12 (for Java 17 support)

* https://maven.apache.org/wrapper/
* https://github.com/apache/maven-wrapper

**Comment by olamy** [comment]
why not that would fix some upgrade.
 but I personally `mvnd` so I need to add a `mvndw` as well :)
