### ISSUE TITLE
NPE in CachedContentFactory if DEBUG enabled

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#754]
if DEBUG log level is enabled, and there is no precompressed content for a static resource line the CachedContentFactory.toString() method throws a NullPointerException (because _precompressed is null).

**Comment by j-white** [comment]
I just ran into this one too:

`java.lang.NullPointerException
        at org.eclipse.jetty.server.CachedContentFactory$CachedHttpContent.toString(CachedContentFactory.java:681)
`
