### ISSUE TITLE
Disabling client SSL session caching breaks SNI

### ISSUE THREAD

**Issue by elipsion** [eclipse/jetty.project#7551]
**Jetty version(s)**
11.0.7

**Java version/vendor**
AdoptOpenJDK 11.0.11.9-hotspot

**OS type/version**
Windows 11 21H2

**Description**
Disabling session caching in [SslContextFactory](https://github.com/eclipse/jetty.project/blob/937cb5df95ee41779266730399b7ccd898859405/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1517) has the unexpected side-effect of also disabling SNI.
It affects [a decision when creating an SSLEngine](https://github.com/eclipse/jetty.project/blob/937cb5df95ee41779266730399b7ccd898859405/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1828-L1830) which seeps down into the [innards of Java SSL implementations](https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/fa3ecefdd6eb14a910ae75b7c0aefb1cf8eedcce/src/java.base/share/classes/sun/security/ssl/SSLEngineImpl.java#L88-L91)

**How to reproduce?**
Create two Jetty `HttpClient`s, one having a `SslContextFactory` with Session Caching disabled.
Run `java` with `-Djavax.net.debug=all` and look for [this error](https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/fa3ecefdd6eb14a910ae75b7c0aefb1cf8eedcce/src/java.base/share/classes/sun/security/ssl/ServerNameExtension.java#L261)

**Comment by elipsion** [comment]
Uh, bump?

**Comment by sbordet** [comment]
@elipsion sorry for the delay looking into this.

Disabling session caching via `SslContextFactory` does not have any effect on the underlying `SSLContext`, it is just really to pick whether to call `SSLContext.createSSLEngine()` or `SSLContext.createSSLEngine(String, int)`.
It does not have any effect on the actual `SSLContext` session cache.

So if your goal is to disable `SSLSession` caching, calling `SslContextFactory.setSessionCachingEnabled(false)` is the wrong method.

However, note that disabling `SSLSession` caching is not possible, see #519.

Your only option is to invalidate the `SSLSession` on the server-side, each time, for example using a `Connection.Listener` (see https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-arch-io-connection-listener).

**Comment by sbordet** [comment]
I'm closing this as it works as expected.
Please comment if you have further insights.
