### ISSUE TITLE
Need to suppress or fix WARN in SslSelectChannelTimeoutTest.testMaxIdleNothingSent

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#7572]
**jetty-10**

> Running org.eclipse.jetty.server.ssl.SslSelectChannelTimeoutTest.testMaxIdleNothingSent()
> 2022-02-11 04:29:48.494:INFO :oejs.Server:main: jetty-10.0.9-SNAPSHOT; built: 2022-02-11T04:14:47.061Z; git: 4f4ccf085406ae5d3462c9a5987135f4628ee42d; jvm 11.0.14+9
> 2022-02-11 04:29:48.655:INFO :oejus.SslContextFactory:main: x509=X509@1f027829(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Server@11534eb1[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_PR-7564/jetty-server/src/test/resources/keystore.p12,trustStore=null]
> 2022-02-11 04:29:48.712:INFO :oejs.AbstractConnector:main: Started ServerConnector@24d6ee26{SSL, (ssl, http/1.1)}{0.0.0.0:34517}
> 2022-02-11 04:29:48.712:INFO :oejs.Server:main: Started Server@1913cde9{STARTING}[10.0.9-SNAPSHOT,sto=0] @545988ms
> 2022-02-11 04:29:51.197:WARN :oejs.ConnectorTimeoutTest:junit-timeout-thread-40: Unable to read stream
> javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
> 	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1691)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1411)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451)
> 	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:916)
> 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1007)
> 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
> 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
> 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
> 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.copy(IO.java:221)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.copy(IO.java:129)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.toString(IO.java:332)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.toString(IO.java:301)
> 	at org.eclipse.jetty.server@10.0.9-SNAPSHOT/org.eclipse.jetty.server.ConnectorTimeoutTest.lambda$testMaxIdleNothingSent$4(ConnectorTimeoutTest.java:534)
> 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:102)
> 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: 
> java.io.EOFException: SSL peer shut down incorrectly
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
> 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1501)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1411)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451)
> 	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:916)
> 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1007)
> 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
> 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
> 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
> 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.copy(IO.java:221)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.copy(IO.java:129)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.toString(IO.java:332)
> 	at org.eclipse.jetty.util@10.0.9-SNAPSHOT/org.eclipse.jetty.util.IO.toString(IO.java:301)
> 	at org.eclipse.jetty.server@10.0.9-SNAPSHOT/org.eclipse.jetty.server.ConnectorTimeoutTest.lambda$testMaxIdleNothingSent$4(ConnectorTimeoutTest.java:534)
> 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:102)
> 	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

**Comment by joakime** [comment]
PR #7596 opened
