### ISSUE TITLE
Configurations.add(Configuration) results in UnsupportedOperationException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7613]
**Jetty version(s)**
10.0.x+

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
While troubleshooting the issue reported at https://github.com/jetty-project/embedded-servlet-server/issues/51

I discovered that if the following line of code is used ...

``` java
Configurations.setServerDefault(server).add(new AnnotationConfiguration());
```

It results in an exception ...

```
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.eclipse.jetty.demos.EmbedMe.createServer(EmbedMe.java:61)
```

This is because the `Configurations` class only has an overridden `add()` method that supports `Configuration` arrays, not single `Configuration` instances.

https://github.com/eclipse/jetty.project/blob/716c7afd8e40d8f645b32aff06945a249d6eb511/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/Configurations.java#L269

We should also override the `AbstractList.add(Configuration)` to allow single `Configuration` instances to be added easier.

**Comment by janbartel** [comment]
I'm not totally convinced of the necessity for this, as we don't override most of the AbstractList methods. However FWIW here's a PR: #7631
