### ISSUE TITLE
Potential memory leak in Jetty 10

### ISSUE THREAD

**Issue by Artur-** [eclipse/jetty.project#7636]
**Jetty version(s)**
10.0.8

**Java version/vendor**
Java version: 11.0.4, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11.0.4

**OS type/version**
Linux

**Description**
When upgrading our PR validation from using Jetty 9.4.43 to use 10.0.8 we see a complete change in memory usage on our build agents. 

With 9.4.43 the build agent performance looks like this
![image](https://user-images.githubusercontent.com/260340/155100068-1f81c212-6a2f-4766-8e25-7f3e0291c557.png)

With Jetty 10.0.0 it looks ok
![image](https://user-images.githubusercontent.com/260340/155108057-8110182d-a2cb-482b-af73-f9d7baf3c0fc.png)

With Jetty 10.0.8 it looks like this 
![image](https://user-images.githubusercontent.com/260340/155100204-68223c5a-3a6a-44cd-a159-e55e9fd17315.png)

The build consists of many Maven modules which uses `jetty-maven-plugin` `start` + `stop`.

https://github.com/vaadin/flow/blob/5de63fa4d25503f268f7fdfeacea71f6e02bd2e1/flow-tests/pom.xml#L189-L248

**How to reproduce?**

This is the PR https://github.com/vaadin/flow/pull/12798

I will see if I can track down which the first problematic version is.

**Comment by gregw** [comment]
A bunch of questions:
 + What version of maven are you using?  
 + when the jetty-maven-plugin starts, does it deploy 1 or more webapps?
 + are the webapp(s) deployed as wars or run from built artifacts?
 + any special features that the webapps use? websocket?
 + are any classes from the server classpath loaded by the webapps?

**Comment by janbartel** [comment]
@Artur-  looking into this. In the meanwhile, I would like to point out that the https://github.com/vaadin/flow/blob/5de63fa4d25503f268f7fdfeacea71f6e02bd2e1/flow-tests/pom.xml#L189-L248 contains non-jetty-10 configuration for the jetty-maven-plugin. In particular, `<webAppConfig>` is no longer supported (it was actually deprecated ages ago), and for the `start` goal, the `<scanInterval>` parameter is meaningless (plus for the `jetty:run` goal, it is now `scan`).

**Comment by Artur-** [comment]
> What version of maven are you using?

3.6.3

> when the jetty-maven-plugin starts, does it deploy 1 or more webapps?

I think almost all of the test modules deploy 1 app

> are the webapp(s) deployed as wars or run from built artifacts?

They are using the linked pom.xml configuration so no wars

> any special features that the webapps use? websocket?

Most of the test modules do not use anything special. A few use websockets.

> are any classes from the server classpath loaded by the webapps?

Some webapps might do something special but most are just Vaadin Flow UIs that load Flow classes

**Comment by Artur-** [comment]
A comment on the original graphs. It seems like the Jetty 10.0.0 graph is cut so it might be that this is actually the first problematic version

**Comment by Artur-** [comment]
> @Artur- looking into this. In the meanwhile, I would like to point out that the https://github.com/vaadin/flow/blob/5de63fa4d25503f268f7fdfeacea71f6e02bd2e1/flow-tests/pom.xml#L189-L248 contains non-jetty-10 configuration for the jetty-maven-plugin. In particular, `<webAppConfig>` is no longer supported (it was actually deprecated ages ago), and for the `start` goal, the `<scanInterval>` parameter is meaningless (plus for the `jetty:run` goal, it is now `scan`).

Thanks, I remove `scanInterval` as it is not needed. Let's see if changing `webAppConfig` to `webApp` makes any difference for the tests

**Comment by Artur-** [comment]
Ok so Jetty 10.0.0 has some other issue that causes one of our tests to fail. With Jetty 10.0.1 and the fixed `webApp` tag the build agent still crashed with out of memory
![image](https://user-images.githubusercontent.com/260340/155169266-522eda14-7f8f-4392-8d09-0783a185a54e.png)

**Comment by janbartel** [comment]
@Artur- can you confirm which version of jetty is first to exhibit the memory issue, is it 10.0.0 or is it 10.0.1?

Is there any chance to analyze the heap dump and see what is hogging the memory?

**Comment by olamy** [comment]
@Artur- interesting. do you have similar result using last Maven version?

**Comment by janbartel** [comment]
FWIW I've run `jetty:run` against one of our standard webapps and reloaded it multiple times and that doesn't show any memory leak. It's not quite analogous to your situation, but it's a good datapoint. I will try with a multimodule project that binds `start` and `stop`, but that's quite a bit of work to create, so will take some time. 

Any more information from your end would be helpful in pinpointing where the issue may be.

**Comment by Artur-** [comment]
I am sorry but I think I have to disappoint you all. There does not seem to be any interesting memory leak in Jetty 10.

After further digging and thanks to the comment by @janbartel about pom.xml containing old tags I realized that the system properties in pom.xml are also defined using the old syntax. One of these properties is critical for the modules to do proper cleanup after running the tests.

Now the memory usage looks sensible also with Jetty 10.0.8

![Screenshot 2022-02-23 at 11 11 54](https://user-images.githubusercontent.com/260340/155289835-ecf18b35-7eb1-49b4-9217-a6617c7adeda.png)

What would have helped here a lot is if the Jetty plugin refused to start if there is invalid configuration. Not sure that is possible.

**Comment by janbartel** [comment]
@Artur- glad to hear that you've found the problem! I have been running various memory tools on a multimodule project I created but haven't been able to demonstrate any memory leak.  

I don't think there's any way to detect old parameters, as the way maven works, it just ignores any configuration that it can't match to a plugin (ie can't find a field or setter that matches the name).  Maybe @olamy knows of a maven setting that will complain if you use config that doesn't match a plugin's config parameters?

**Comment by olamy** [comment]
nah it's silently ignored (even with debug level)

**Comment by janbartel** [comment]
Closing as this problem has been resolved (old plugin configuration).
