### ISSUE TITLE
I want to get the role information, but it is private.

### ISSUE THREAD

**Issue by youngledo** [eclipse/jetty.project#7653]
**Target Jetty version(s)**
jetty-11.0.6
**Enhancement Description**
![1645775750385](https://user-images.githubusercontent.com/68590897/155677136-385cb7c0-1085-44b7-9c6a-e032c81b0edc.jpg)

**Comment by janbartel** [comment]
@youngledo what is your use-case for exposing the roles? I'm not sure we want to expose them in the `DefaultUserIdentity`, but you should be able to provide your own `UserIdentity` implementation to achieve whatever it is you want to do.

**Comment by youngledo** [comment]
> 

I want to make the role information available for authentication and authorization. Although I can implement it based on UserIdentity, it is not necessary just for this role information.

**Comment by janbartel** [comment]
@youngledo jetty uses the `DefaultUserIdentity` to represent an _authenticated_ user. It is not used to _do_ the authentication step. The role info inside it is only used to do _authorization_ (roles play no part in authentication). So I think you're already stepping outside the bounds, as it were, so I think your best course of action would be to subclass `DefaultUserIdentity`.
