### ISSUE TITLE
Issue on upgrading http connection to websocket asynchronously on thread not managed by Jetty

### ISSUE THREAD

**Issue by niwinz** [eclipse/jetty.project#7675]
**Jetty version(s)** 10.0.8

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

**OS type/version**
Ubuntu LTS/Docker

**Description**
I don't know if this a bug or is something I'm doing incorrectly. After some hours of investigating, I think is like a bug.

I get the following exception when I try to upgrade http connection to websocket connection where the handler is with asyncContext and running on different thread (other threadpool different from jetty).

```
java.lang.NullPointerException: Cannot invoke "javax.servlet.ServletContext.getAttribute(String)" because "servletContext" is null
        at org.eclipse.jetty.websocket.server.JettyWebSocketServerContainer.getContainer(JettyWebSocketServerContainer.java:61) ~[websocket-jetty-server-10.0.8.jar:10.0.8]
        at yetti.websocket$upgrade_websocket.invokeStatic(websocket.clj:186) ~[?:?]
        at yetti.websocket$upgrade_websocket.invoke(websocket.clj:178) ~[?:?]  
        at yetti.adapter$wrap_async_handler$fn__47898$fn__47899.invoke(adapter.clj:76) ~[?:?]
        at app.http.middleware$wrap_server_timing$fn__48461$fn__48462.invoke(middleware.clj:30) ~[?:?]
[...]
````

Everything works as expected if no other threads are involved (I mean that the upgrade process happens on jetty managed thread).
Looks like `request.getServletContext()` returns NULL if it is executed on other thread.

I oversimplified the explication, but the code involves many steps using completablefutures and custom instance of ForkJoinPool.

**is this expected behavior? or it is expected always upgrade websocket connection in the managed thread?**

**How to reproduce?**

Just setup a handler, launch a separated thread and try to upgrade connection there.

Many thanks for your time.

**Comment by lachlan-roberts** [comment]
I wouldn't expect this to work unless you used `asyncContext.start()` to start your thread, but after testing I can see even that does not work. @gregw do you think this is a bug that `Request` return a null `ServletContext` after an `asyncContext.start()`?

@niwinz is it possible for you call `request.getServletContext()` before you start your other thread and then capture the correct `ServletContext` value?

**Comment by niwinz** [comment]
Hmm, I think no, but i can be wrong. This is the flow:
1. jetty servlet handler starts executon pasing the target, request and response
2. I just start async conctext calling request.startAsync()
3. call some function that runs async stuff with a callback, callback will run on the other thread
4. if some conditional on callback args, I try to start the upgrade process (that already works if everything happens on the same jetty thread)

Do I need to call startAsync also in the other thread/

This is all written in clojure and maybe you are not familiar with but I paste here the code for reference (if proceed):

```clojure
(defn- wrap-async-handler
  "Returns an Jetty Handler implementation for the given Ring **async** handler."
  [handler options]
  (fn [^HttpServletRequest request ^HttpServletResponse response]
    (let [^AsyncContext async-context (.startAsync request)]
      (.setTimeout async-context (:http/idle-timeout options))
      (handler (util/build-request-map request)
               (fn [response-map]
                 (try
                   (if (websocket-upgrade? response-map)
                     (ws/upgrade-websocket request response (:ws response-map) options)
                     (util/update-servlet-response response response-map))
                   (finally
                     (.complete async-context))))
               (fn [^Throwable exception]
                 (.sendError response 500 (.getMessage exception))
                 (.complete async-context))))))

;; And the ws/upgrade-socket here

(defn upgrade-websocket
  [^HttpServletRequest req
   ^HttpServletResponse res
   ^clojure.lang.IFn ws
   {:keys [:websocket/idle-timeout
           :websocket/max-text-msg-size
           :websocket/max-binary-msg-size]}]
  (let [creator   (create-websocket-creator ws)
        container (JettyWebSocketServerContainer/getContainer (.getServletContext req))]
    (.setIdleTimeout container (Duration/ofMillis idle-timeout))
    (.setMaxTextMessageSize container max-text-msg-size)
    (.setMaxBinaryMessageSize container max-binary-msg-size)
    (.upgrade container creator req res)))
```

**Comment by niwinz** [comment]
> @niwinz is it possible for you call `request.getServletContext()` before you start your other thread and then capture the correct `ServletContext` value?


I have tried it: 
1. get the servletcontext before spawning any thread
2. proceed with normal async flow explained before
3. then run JettyWebSocketServerContainer.getContainer(previoslyObtainedServletContext) in the other thread as result of exection of async flow
4. other similar NPE is raised inside Jetty.

Looks like jetty expects the websocket upgrade happen in the same thread at least in two different functions.

**Comment by niwinz** [comment]
The main reason I need it is because I want to run the session handling asynchronously (using redis async client, and then decide if proceed with websocket upgrade or return error). The redis async client runs the "callback" on their own threadpool, that causes the upgrade process happen in other thread. For now we are running this code synchronously, performing blocking operation the jetty thread for all websocket connections.

**Comment by joakime** [comment]
How does the "redis async client" differ from our own async HttpClient (which doesn't suffer from this issue)?
And how does a client impact the server handling of upgrade?

Also be super careful about HttpSession and WebSocket.
Once the WebSocket is upgraded, it is no longer HTTP, and that means the HttpSession is no longer part of the Servlet handling, or HTTP handling, or even connected to the rest of the Session handling (for listeners, or sync back to session store, etc). There's no lifecycle for HttpSession in WebSocket, and the information it contains is essentially frozen in time from the point that the upgrade succeeded.  Changes occurring to that same session elsewhere have no impact on the HttpSession once you are upgraded in WebSocket (and vice versa).  Neither the WebSocket spec, nor the Servlet spec have any answers to this, nor has there been any interest in attempting to solve for this (the recommendation by both specs is to either treat the HttpSession as dead after upgrade, or grab what you want from the HttpSession during upgrade and use them after upgrade, but generally don't hold onto the HttpSession object)

**Comment by niwinz** [comment]
> How does the "redis async client" differ from our own async HttpClient (which doesn't suffer from this issue)? And how does a client impact the server handling of upgrade?
> 
> Also be super careful about HttpSession and WebSocket. Once the WebSocket is upgraded, it is no longer HTTP, and that means the HttpSession is no longer part of the Servlet handling, or HTTP handling, or even connected to the rest of the Session handling (for listeners, or sync back to session store, etc). There's no lifecycle for HttpSession in WebSocket, and the information it contains is essentially frozen in time from the point that the upgrade succeeded. Changes occurring to that same session elsewhere have no impact on the HttpSession once you are upgraded in WebSocket (and vice versa). Neither the WebSocket spec, nor the Servlet spec have any answers to this, nor has there been any interest in attempting to solve for this (the recommendation by both specs is to either treat the HttpSession as dead after upgrade, or grab what you want from the HttpSession during upgrade and use them after upgrade, but generally don't hold onto the HttpSession object)

Thank you for the advice but I'm already aware of this. I'm not doing anything similar, neither use the HttpSession. I used the http session concept just as an example. 

There are "some logic that processes the request", this logic is asynchronous (can be access to the database in a worker thread, can be http call to other service, etc), then the asynchronous response callback is scheduled to be executed in a custom ThreadPool, then we proceed to do the upgrade to websocket connection. If the same logic happens synchronously on jetty managed thread everything works as expected.

This is why I ask it, It is intended behavior or is a bug. If HttpClient from jetty does not suffers from this issue (I didn't tested it), is that it does something additional that I'm not doing and I want to know how to fix this. My sample code which I use for debugging this, does pretty nothing: just spawns a thread and tries to upgrade the request to a websocket connection simulating. And it fails with the reported exception. 

If it is not clear, I try to make some example code, to isolate the problem using plain java.

**Comment by joakime** [comment]
Yeah, lets not mix HttpSession into this issue :-)

Lets just use your backend database check as a step before upgrade is determined as a good example instead.

Using the Servlet API, I've seen this done with a WebSocketServlet (Jetty concept) and WebSocketPreFilter (app concept), where the WebSocketPreFilter does the validation and other things within it's own AsyncContext, and once things are OK to proceed it uses the FilterChain to allow the WebSocketServlet to execute, or responds from the Filter with an error if not able to (or allowed to) upgrade.

I think I see `Handler` in your example code, are you using the raw Jetty `Handler` concepts? or the `ServletContextHandler` and servlet concepts?
If `Handler`, I wonder if you could accomplish the same thing with a `HandlerWrapper`, that does the async steps and then calls the wrapped handler (which is your websocket handler) once you are done with the async steps?

**Comment by niwinz** [comment]
Here I have a small java file that reproduces the issue, so we can talk over clear example, and see if I'm doing something wrong or is a bug:

```java
package yetti_playground;

import java.time.Duration;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ForkJoinPool;
import javax.servlet.AsyncContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory;
import org.eclipse.jetty.server.ConnectionFactory;
import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.server.ForwardedRequestCustomizer;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.server.HttpConnectionFactory;
import org.eclipse.jetty.server.ProxyConnectionFactory;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHandler;
import org.eclipse.jetty.util.thread.QueuedThreadPool;
import org.eclipse.jetty.websocket.api.Session;
import org.eclipse.jetty.websocket.api.WebSocketAdapter;
import org.eclipse.jetty.websocket.server.JettyServerUpgradeRequest;
import org.eclipse.jetty.websocket.server.JettyServerUpgradeResponse;
import org.eclipse.jetty.websocket.server.JettyWebSocketCreator;
import org.eclipse.jetty.websocket.server.JettyWebSocketServerContainer;
import org.eclipse.jetty.websocket.server.config.JettyWebSocketServletContainerInitializer;

public class MyServer {
  public static ForkJoinPool pool = new ForkJoinPool(10);

  public static class MyWebsocketAdapter extends WebSocketAdapter {
    private Session session;

    public MyWebsocketAdapter() {
      super();
    }

    public void onWebSocketConnect(Session sess) {
      super.onWebSocketConnect(sess);
      this.session = session;
      System.out.println("ws connect");
    }

    public void onWebSocketError(Throwable cause) {
      System.out.println("ws error");
      cause.printStackTrace();
    }

    public void onWebSocketClose(int status, String reason) {
      super.onWebSocketClose(status, reason);
      System.out.println("ws closed");
    }

    public void onWebSocketText(String message) {
      try {
        System.out.println("received message: " + message);
        this.getRemote().sendString(message);
      } catch (java.io.IOException e) {
        throw new RuntimeException(e);
      }
    }
  }

  // This Handler works
  public static class MySyncWebsocketHandler extends ServletHandler {
    public void doHandle(String target,
                         Request baseRequest,
                         HttpServletRequest request,
                         HttpServletResponse response) throws java.io.IOException {

      // var actx = request.startAsync();
      System.out.println("receiving request on: " + Thread.currentThread().getName());

      var creator = new JettyWebSocketCreator() {
          public Object createWebSocket(JettyServerUpgradeRequest req, JettyServerUpgradeResponse resp) {
            return new MyWebsocketAdapter();
          }
        };

      System.out.println("upgrading response from: " + Thread.currentThread().getName());
      var container = JettyWebSocketServerContainer.getContainer(request.getServletContext());
      container.setIdleTimeout(Duration.ofMillis(500000));
      container.setMaxTextMessageSize(65536);
      container.upgrade(creator, request, response);
    }
  }

  // This handler raises exception
  public static class MyAsyncWebsocketHandler extends ServletHandler {
    public void doHandle(String target,
                         Request baseRequest,
                         HttpServletRequest request,
                         HttpServletResponse response) throws java.io.IOException {

      var actx = request.startAsync();
      System.out.println("receiving request on: " + Thread.currentThread().getName());

      CompletableFuture.runAsync(() -> {
          System.out.println("upgrading response from: " + Thread.currentThread().getName());
          try {
            var creator = new JettyWebSocketCreator() {
                public Object createWebSocket(JettyServerUpgradeRequest req, JettyServerUpgradeResponse resp) {
                  return new MyWebsocketAdapter();
                }
              };

            var container = JettyWebSocketServerContainer.getContainer(request.getServletContext());
            container.setIdleTimeout(Duration.ofMillis(500000));
            container.setMaxTextMessageSize(65536);
            container.upgrade(creator, request, response);
          } catch (Throwable e) {
            System.out.println("exception on: " + Thread.currentThread().getName());
            e.printStackTrace();
            throw new RuntimeException(e);
          }
        })
        .whenCompleteAsync((result, cause) -> {
            System.out.println("completing context from: " + Thread.currentThread().getName());
            actx.complete();
          }, pool);
    }
  }

  public static Server createServer() {
    var pool = new QueuedThreadPool(10, 0, 60000);
    pool.setDaemon(true);

    var httpConfig = new HttpConfiguration();
    httpConfig.setSecureScheme("https");
    httpConfig.setSendServerVersion(false);

    var server = new Server(pool);
    var connector = new ServerConnector(server,
                                        new HttpConnectionFactory(httpConfig),
                                        new HTTP2CServerConnectionFactory(httpConfig));
    connector.setPort(11000);
    connector.setHost("127.0.0.1");
    connector.setIdleTimeout(200000);

    server.setConnectors(new ServerConnector[] {connector});
    return server;
  }


  public static void main(String args[]) {
    var server = createServer();

    var servletHandler = new ServletContextHandler();
    servletHandler.setAllowNullPathInfo(true);
    JettyWebSocketServletContainerInitializer.configure(servletHandler, null);

    servletHandler.setServletHandler(new MyAsyncWebsocketHandler());
    server.setHandler(servletHandler);

    try {
      server.start();
      server.join();
    } catch (Exception cause) {
      cause.printStackTrace();
    }
  }
}
```

You can imagine that the runAsync code is just a callback that is run (after some hypothetical checks and conditions) on different thread and tries to upgrade the connection to a websocket.

**Comment by niwinz** [comment]
The printed exception is:

```
java.lang.NullPointerException
        at org.eclipse.jetty.websocket.server.JettyWebSocketServerContainer.getContainer(JettyWebSocketServerContainer.java:61)
        at yetti_playground.MyServer$MyAsyncWebsocketHandler.lambda$doHandle$0(MyServer.java:111)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by niwinz** [comment]
And this exception is raised if I get the servletContext syncronously on the jetty thread and then pass it to the `JettyWebSocketServerContainer.getContainer(sctx)` on the async callback:

```
java.lang.IllegalStateException: null servletContext from request
        at org.eclipse.jetty.websocket.core.server.internal.CreatorNegotiator.negotiate(CreatorNegotiator.java:57)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker.upgradeRequest(AbstractHandshaker.java:76)
        at org.eclipse.jetty.websocket.core.server.internal.HandshakerSelector.upgradeRequest(HandshakerSelector.java:39)
        at org.eclipse.jetty.websocket.server.JettyWebSocketServerContainer.upgrade(JettyWebSocketServerContainer.java:184)
        at yetti_playground.MyServer$MyAsyncWebsocketHandler.lambda$doHandle$0(MyServer.java:115)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by joakime** [comment]
First thing I would change is ... never extend from (or use directly) the class `ServletHandler`, that's an internal class of the `ServletContextHandler` and it's own `ServletHolder`.

The way you have this setup, you have no common `javax.servlet.ServletContext` across those separate `ServletHandler` instances (even tho you attempted to declare them against the `ServletContextHandler`).

Use normal `extends HttpServlet` and just implement the `service(HttpServletRequest, HttpServletResponse)` method.

**Comment by joakime** [comment]
Split your `MyAsyncWebsocketHandler` up.
The async before upgrade in a `Filter` and the upgrade itself in a separate `Servlet`.
Handle the pre-websocket async in the Filter implementation, and once you are sure you want to upgrade use the filter chain to progress the request to the Servlet (as this will setup the scope for the everything properly on that Servlet call)

**Comment by niwinz** [comment]
I understand, but I think is not an option from my side. As a context: yetti is an adapter of Jetty to be used with Ring interface, that is a common "protocol" for http servers on Clojure. Here, jetty serves as http/websocket server, but all the following stuff is already happens on the ring async flow. I'm just unable to use Filters and other Jetty facilities, because this code happens outside of my control. The users of the adapter just uses the ring "interface". And it worked almost everything, except when I try to upgrade websocket connection on other thread).

**Comment by niwinz** [comment]
> First thing I would change is ... never extend from (or use directly) the class `ServletHandler`, that's an internal class of the `ServletContextHandler` and it's own `ServletHolder`.
> 
> The way you have this setup, you have no common `javax.servlet.ServletContext` across those separate `ServletHandler` instances (even tho you attempted to declare them against the `ServletContextHandler`).
> 
> Use normal `extends HttpServlet` and just implement the `service(HttpServletRequest, HttpServletResponse)` method.

Hmm interesting. In fact, I'm using this in this manner because this is how was done in the original code I have forked. Is there a way to use websockets without the need of ServletHandler, and just using plain jetty Handler ?

**Comment by joakime** [comment]
> Hmm interesting. In fact, I'm using this in this manner because this is how was done in the original code I have forked. Is there a way to use websockets without the need of ServletHandler, and just using plain jetty Handler ?

Btw, if Ring is using the `ServletHandler`, they better be using 1 and only ever 1 `ServletHandler` with no additional modifications (like extra filters or extra servlets, as that's not supported in Jetty 10).  It was barely supported in Jetty 9 to use a `ServletHandler` directly (it had TONS of limitations, restrictions, and gotchas if you did), and is wholly unsupported in Jetty 10+.

As for a plain Jetty Handler, I would first think of the [`websocket-core-server`](https://github.com/eclipse/jetty.project/tree/jetty-10.0.8/jetty-websocket) as a good place to start. (as it has no servlet concepts or requirements).
Even still, I would split your `MyAsyncWebsocketHandler`, have all of the async logic in a `HandlerWrapper` (with the configured [`WebSocketUpgradeHandler`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.8/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketUpgradeHandler.java) as the internal "wrapped" Handler), which validates and does what you need/want to do in your async way.  Once you have a request that can proceed to upgrade, use the `super.handle(target, baseRequest, request, response);` call to call the `WebSocketUpgradeHandler` to proceed.
Or just copy/paste the `WebSocketUpgradeHandler` code into your own wrapper, your call.

**Comment by niwinz** [comment]
> > Hmm interesting. In fact, I'm using this in this manner because this is how was done in the original code I have forked. Is there a way to use websockets without the need of ServletHandler, and just using plain jetty Handler ?
> 
> Btw, if Ring is using the `ServletHandler`, they better be using 1 and only ever 1 `ServletHandler` with no additional modifications (like extra filters or extra servlets, as that's not supported in Jetty 10). It was barely supported in Jetty 9 to use a `ServletHandler` directly (it had TONS of limitations, restrictions, and gotchas if you did), and is wholly unsupported in Jetty 10+.

Yeah, this is how it is used, just a single handler, without anything else, and it works pretty well. In any case, thanks for the advice, I will look on alternatives on my own fork.

> 
> As for a plain Jetty Handler, I would first think of the [`websocket-core-server`](https://github.com/eclipse/jetty.project/tree/jetty-10.0.8/jetty-websocket) as a good place to start. (as it has no servlet concepts or requirements). Even still, I would split your `MyAsyncWebsocketHandler`, have all of the async logic in a `HandlerWrapper` (with the configured [`WebSocketUpgradeHandler`](https://github.com/eclipse/jetty.project/blob/jetty-10.0.8/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketUpgradeHandler.java) as the internal "wrapped" Handler), which validates and does what you need/want to do in your async way. Once you have a request that can proceed to upgrade, use the `super.handle(target, baseRequest, request, response);` call to call the `WebSocketUpgradeHandler` to proceed. Or just copy/paste the `WebSocketUpgradeHandler` code into your own wrapper, your call.

Thanks, I will try it.

**Comment by niwinz** [comment]
On the end, I didn't found a solution for this. In any case it looks intended behavior so I close this issue.
