### ISSUE TITLE
Jetty client is adding "accept-encoding:gzip" header to requests by its own

### ISSUE THREAD

**Issue by BrahmKauntey** [eclipse/jetty.project#7681]
**Jetty version(s)**
9.4.43.v20210629

**Java version/vendor** `(use: java -version)`
17.0.1

**OS type/version**
Linux

**Description**
Jetty client is adding "accept-encoding:gzip" header to requests while routing out to host by its own.

**How to reproduce?**
Setup client like following code:

``` java
                HTTP2Client h2Client = new HTTP2Client();
                h2Client.setMaxConcurrentPushedStreams(1000);
                SslContextFactory sslCntxtFactory = new SslContextFactory(true);
                HttpClientTransportOverHTTP2 transport = new HttpClientTransportOverHTTP2(h2Client);
                transport.setUseALPN(false);
                HttpClient hClient;
                this.hClient = new HttpClient(transport, sslCntxtFactory);
                this.hClient.setIdleTimeout(600000);
                this.hClient.setMaxRequestsQueuedPerDestination(5000);
                this.hClient.setMaxConnectionsPerDestination(4);
                this.hClient.setFollowRedirects(false);
                this.hClient.setRemoveIdleDestinations(true);
```
send an http2 request and check for "accept-encoding" header.

**Comment by joakime** [comment]
The Gzip handling is just part of the standard `org.eclipse.jetty.client.ContentDecoder` behavior.

The specific `GZIPContentDecoder` implementation is added by default (on startup).
The `HttpClient.getContentDecoderFactories()` is interrogated, with each `ContentDecoder.getEncoding()` resulting in a value-list added to the `Accept-Encoding` header for all Requests by that client instance.

Since `GZIPContentDecoder` is added on startup, you'll have to `hClient.start()` first, then you can manipulate the `getContentDecoderFactories()` to remove that decoder.

Example from our `AbstractProxyServlet`:

https://github.com/eclipse/jetty.project/blob/79cc9cf90ed1d7844fde4376001a5d54d6c68975/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L327-L330

**Comment by sbordet** [comment]
> Jetty client is adding "accept-encoding:gzip" header to requests while routing out to host by its own.

That is intended.

**Comment by BrahmKauntey** [comment]
> The Gzip handling is just part of the standard `org.eclipse.jetty.client.ContentDecoder` behavior.
> 
> The specific `GZIPContentDecoder` implementation is added by default (on startup). The `HttpClient.getContentDecoderFactories()` is interrogated, with each `ContentDecoder.getEncoding()` resulting in a value-list added to the `Accept-Encoding` header for all Requests by that client instance.
> 
> Since `GZIPContentDecoder` is added on startup, you'll have to `hClient.start()` first, then you can manipulate the `getContentDecoderFactories()` to remove that decoder.
> 
> Example from our `AbstractProxyServlet`:
> 
> https://github.com/eclipse/jetty.project/blob/79cc9cf90ed1d7844fde4376001a5d54d6c68975/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L327-L330

After doing changes as suggested, jetty is not sending accept-encoding header now. We have removed GZIPContentDecoder, what will be the impact of this if response is received with encoding as gzip?

**Comment by sbordet** [comment]
> what will be the impact of this if response is received with encoding as gzip?

That it will not be decoded, so you will have to do it if you need to see the uncompressed content.

May I ask why you want to remove this feature? This is very useful for clients such as the one you have shown above.

**Comment by joakime** [comment]
> After doing changes as suggested, jetty is not sending accept-encoding header now. We have removed GZIPContentDecoder, what will be the impact of this if response is received with encoding as gzip?

If you have a server sending gzip encoded content (indicated by the `Content-Encoding: gzip` response header) without first receiving an `Accept-Encoding: gzip` header, then you have a server not following the HTTP and w3c specs.
In this case, you'll have to uncompress the content yourself (like @sbordet pointed out), by using the binary representation of the body content.
If the `Content-Encoding: gzip` response header does _not_ exist, and the content is gzip, then you are simply downloading binary content (eg: you are downloading compressed file).

The existence of the `Accept-Encoding: gzip` header on the request does not force the server to send gzipped content, it's just an indication that the client can accept gzipped content.
Every browser in existence today also forces an `Accept-Encoding` header with their own list of supported encodings.  Every browser currently supports gzip and are slowly removing support for deflate.  Today chrome/edge/firefox for example all send `Accept-Encoding: gzip, deflate, br` announcing they support gzip, deflate, or brotli.

Having that `Accept-Encoding: gzip` header is actually an industry standard now. 

Jetty's HttpClient supports `gzip` and doesn't support `deflate` content encoding, as it's not a formal standard and has multiple interpretations (thanks microsoft!), and we don't support `br` (aka brotli) as there's no good pure Java solution for brotli compression (yet).

**Comment by BrahmKauntey** [comment]
Our application is working as a proxy, whether client or servers can handle gzip content is not known to application. If client is not expecting gzipped response and not adding "accept-encoding: gzip" header, our application is adding it. Also, if one "accept-encoding" header is present in the request, jetty is adding one more "accept-encoding" header with value as gzip.

Jetty should honor what "accept-encoding" header is coming in the request. If application is expecting gzip response, it should add "accept-encoding" header accordingly.

**Comment by sbordet** [comment]
For proxy use cases it is correct to clear the content decoder factories.
You should also re-configure other things, see:

https://github.com/eclipse/jetty.project/blob/79cc9cf90ed1d7844fde4376001a5d54d6c68975/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L330 

and following lines.

**Comment by joakime** [comment]
Closing as answered.
