### ISSUE TITLE
Read data to native memory from HttpInput 

### ISSUE THREAD

**Issue by jiang-cao** [eclipse/jetty.project#7688]
**Target Jetty version(s)**
jetty-11.0.9
**Enhancement Description**
Our purpose is read data direct to native memory from jetty direct buffers, then we could do CPU heavy compute with native lib without copy data between java heap and native heap.

Jetty has provide flexibility let us inherit class and implement our special code. The problem is some fields/methods in HttpChannel and HttpInput are private and can't be accessed in sub class.

The change is explore necessary methods to sub class. I will prepare a PR to show the change.

**Comment by jiang-cao** [comment]
PR: https://github.com/eclipse/jetty.project/pull/7689

With this change, we implement a new method in sub class of HttpInput.

    public int read(long address, int off, int len) throws IOException, CSException {
    ...
    }

The input data will write to native address.

**Comment by sbordet** [comment]
I'm not sure I understand this change?

If you use a direct `ByteBuffer` to read data from `HttpInput` there is no copy, and you can use the direct `ByteBuffer` with native libraries.

I'd rather add a `read(ByteBuffer)` method than a raw `read(long, ...)` that cannot be used without resorting to `Unsafe`.

Can you detail your exact use case? Would a `read(ByteBuffer)` be enough for you?

**Comment by jiang-cao** [comment]
Thanks for your review!  
In my case, I did want the unsafe method, read the data to native buffer address.  In our case, the native memory is not owned by java layer,  so we prefer to have more flexibility to implement read(long, ...) in sub classes.   

read(ByteBuffer) is a good extension, but not match our current requirement.

**Comment by joakime** [comment]
You haven't said why you need this.
What is your use case?

Most of the existing usages in Jetty are ByteBuffer based, and we are consuming more and more JDK APIs that themselves are ByteBuffer based.
Wouldn't a direct ByteBuffer be sufficient to satisfy your native vs heap memory concerns?

**Comment by jiang-cao** [comment]
Explain more detail about my case:
We receive data from HTTP,  the data will be used do some CPU heavy compute work like md5, CRC, Erasing Coding, then the data will be send to remote node by RDMA NIC.   Avoid memory copy is important in the data path.  The idea way is direct used RDMA registered buffer to receive HTTP data and keep all CPU heavy work under native layer.  Use native buffer address is more straightforward here.

**Comment by jiang-cao** [comment]
@sbordet @joakime any suggestion on what I could do to get this extend ability?

**Comment by joakime** [comment]
In practice, a direct ByteBuffer is a native buffer, been this way since Java 1.4.
I would expect your native code would allocate a new direct ByteBuffer, and the Java code uses it.
Same end result.
Tricky part becomes managing the custom ByteBufferPool you have to implement if you want to handle more than 1 concurrent incoming request at a time.

You MUST work with the ByteBuffer construct on the Jetty side, and you have to fit whatever you are doing within the `org.eclipse.jetty.server.HttpInput$Content` class, otherwise you'll just wind up rewriting most of `jetty-server`, `jetty-http`, and `jetty-io` to fit into what you want on the Jetty side.
If "avoid memory copy" is important to you, then the `HttpInput` is a strange place to hook into (that's after potentially many memory copies already due to the nature of the HTTP specs and the interceptors that get added on due to various transfer-encoding or content-encoding behaviors).

`HttpInput` is a servlet level component of Jetty, if you wanted to hook into the handler level (core Jetty, and a common path), you would need other code.
Jetty 12 has already moved `HttpInput` to the appropriate ee level where it belongs, with a `HttpInput` EE specific behaviors (Jakarta EE 8, Jakarta EE 9, and Jakarta EE 10).

What will you do with other technologies in the servlet space? (websocket for example, that doesn't use `HttpInput`)

**Comment by joakime** [comment]
Hooking into HttpInput also means you'll be accessing servlet style data outside of the servlet scope (such as what happens in some request/access logging libraries, after the response is committed, and after the request is dispatched to the webapp).

**Comment by sbordet** [comment]
@jiang-cao can you use [JEP 352](https://openjdk.java.net/jeps/352) or similar mechanism to map the RDMA memory into a mapped `ByteBuffer`?

Alternatively, look at [JEP 412](https://openjdk.java.net/jeps/412): you would be able to do something like this (pseudo-code):
```
MemoryAddress ma = MemoryAddress.ofLong(address);
MemorySegment ms = ma.asSegment(...);
ByteBuffer bb = ms.asByteBuffer();
```
The `bb` object would be mapped to the address you want, and copying bytes into it should have the effect that you want.

Let us know if it works, also considering that you won't be able to use `Unsafe` in recent Java versions.

**Comment by jiang-cao** [comment]
@joakime  Thanks for your detail explanation! I agree with you and will try use directBuffer instead of native address.

In my case, the input HTTP content/body length may several MB to hundred MB. We don't have other encode/decode process, if I understand correctly, for most data, there are two copies: native socket buffer -> DirectBuffer inside jetty -> my  DirectBuffer.  We still depends on other servlet features, so the one extra copy is acceptable. 
By the way, we don't use websocket, so support DirectBuffer in HttpInput can satisfy my case.

@sbordet Thanks for your suggestions! Yes, it should works for me, map native address to java reference without unsafe code.  We still use JDK11,  but I found way can wrap native address to DirectBuffer by JNI call:
JNIEnv * env
    return env->NewDirectByteBuffer(reinterpret_cast<void *>(address), size);

Use DirectBuffer is works for me! Thanks for your help! 

The problem become to support ByteBuffer in HttpInput.  I find HttpInput only support read(byte[] b, int off, int len),  so we need add a new method like read(Bytebuffer buffer) in it.

Any suggestion on how to implement it? 
1. Do you want support it in jetty main stream code?  Then we can add a new method to support read to ByteBuffer.
2. If we can open some private fields and method to sub-class,  like my previous PR https://github.com/eclipse/jetty.project/pull/7689 did.  I can implement it in my project without impact jetty main stream code a lot.

**Comment by sbordet** [comment]
@jiang-cao I would prefer option 1, i.e. add a new `HttpInput.read(ByteBuffer)` method.

**Comment by jiang-cao** [comment]
@sbordet Thank you! I will prepare a draft version for review.

**Comment by jiang-cao** [comment]
I create https://github.com/eclipse/jetty.project/pull/7751 for review.  The solution works in my project.
@sbordet  could you help review it?

**Comment by jiang-cao** [comment]
@sbordet  I create https://github.com/eclipse/jetty.project/pull/7778 base on your comments. Please help review it.
