### ISSUE TITLE
jetty-client close TLS connection unexpectly.

### ISSUE THREAD

**Issue by lisay-yan** [eclipse/jetty.project#7692]
**Jetty version(s)**
Jetty-9.4.43.v20210629

**Java version/vendor** `(use: java -version)`
Java 11

**OS type/version**
linux
**Description**
My application use HttpClient and SslContextFactory.Client for HTTPS traffic.
Based on pcap, jetty-client may send FIN rather than client hello.
![image](https://user-images.githubusercontent.com/61861257/157146462-7e377962-7283-4a3d-98b1-096429563c65.png)

Based on Jetty log study, it hit below WR for java 11.
Is the WR only apply for Jetty-Server? And possible bring negative impact for Jetty-Client?
                            // Workaround for Java 11 behavior.
                            if (netFilled < 0 && isHandshakeInitial() && BufferUtil.isEmpty(_encryptedInput))
                                closeInbound();

Linked issue https://github.com/eclipse/jetty.project/issues/4209.

**How to reproduce?**

My settings:
setMinThreads 4, setMaxThreads 6, and setMaxConnectionsPerDestination 20.
Then start send HTTPS traffic with a small load, it can random shown for bunches of request at the same time.

@sbordet

**Comment by sbordet** [comment]
The pcap shows that it is the server sending the FIN, not the client.

**Comment by lisay-yan** [comment]
@sbordet 

Oh, sorry. That is my fault.
I edit and update correct pcap in initial description. 

BTW, not sure if I can consult generally when jetty-client side take initiative to close TLS connection?
In below pcap, Alert also send from client side after received server response around 540ms.
Precondition:
Both HTTP Client and HTTP Request idle time already set to 0 since expect reuse TLS connection and keep persistent.

![image](https://user-images.githubusercontent.com/61861257/157133598-7de16e0d-44db-4676-966c-8226748c4656.png)

Based on pcap, no FIN from remote side, not sure why client side send the encrypted alert.
My summary for Client close connection possible happen at:
[1] Request Or Response timeout ---Not above pcap case
[2] Idle time expired ---Not above pcap case
[3] Server side send FIN --- Not above pcap case.

Is any other possible reason? Thanks so much.

**Comment by lisay-yan** [comment]
@sbordet 

BTW, the encrypted alert is type 21 for close notify.
Look forward to your valuable feedback and nice help. Thanks.
![image](https://user-images.githubusercontent.com/61861257/157130658-335e74a8-6fac-4644-8503-38cb33b94144.png)

**Comment by sbordet** [comment]
@lisay-yan if you can reproduce this issue, can you enable DEBUG logging and attach the logs here?

The pcap shows that the client sends a CONNECT, receives a 200 and then sends encrypted data like it should.
Do you expect this?

Also, you could enable the system property `-Djavax.net.debug=all` to see what the OpenJDK TLS implementation sees.

I would also double check the idle timeouts to avoid that setting them to 0 does not mean that the connection is immediately closed. I would leave the idle timeouts at their defaults.
