### ISSUE TITLE
Unable to set HttpCompliance mode for org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7710]
**Jetty version(s)**
9.4.x

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
Unlike the normal `org.eclipse.jetty.server.HttpConnectionFactory` which has a `.setHttpCompliance(HttpCompliance)` method, the
`org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory` class does not have the ability to set the `HttpCompliance` mode.

This is only an issue on Jetty 9.4.x, as the `HttpCompliance` configuration was moved to the `HttpConfiguration` class in Jetty 10+

**Comment by joakime** [comment]
Closing, as using the `ServerConnector` scoped `HttpCompliance` works already.

``` java
ServerConnector connectorA = new ServerConnector(server);
connectorA.addBean(HttpCompliance.RFC7230_NO_AMBIGUOUS_URIS);
```

**Comment by bahui80** [comment]
> Closing, as using the `ServerConnector` scoped `HttpCompliance` works already.
> 
> ```java
> ServerConnector connectorA = new ServerConnector(server);
> connectorA.addBean(HttpCompliance.RFC7230_NO_AMBIGUOUS_URIS);
> ```

This isn't working for me for HTTP2CServerConnectionFactory. Even if I specify it like this I am still getting `<h1>Bad Message 400</h1><pre>reason: Ambiguous path separator</pre>%`.

**Comment by joakime** [comment]
@bahui80 don't revive old issues. 

Start a new issue.
Note: Jetty 9.x is now at End of Community Support, you should be using Jetty 10, Jetty 11, or Jetty 12 at this point in time.

* #7958
