### ISSUE TITLE
Flaky StressTest.doLoops:330->doPaths:427 » Socket Connection reset

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#7711]
observed here https://jenkins.webtide.net/job/jetty.project/view/change-requests/job/PR-7695/2/

**Comment by janbartel** [comment]
See also https://jenkins.webtide.net/job/jetty.project/job/jetty-10.0.x/1619/testReport/junit/org.eclipse.jetty.server/StressTest/Parallel_Stage___Build___Test___JDK17___testNonPersistent/
