### ISSUE TITLE
"classpath:/" URL support for Resource?

### ISSUE THREAD

**Issue by sunng87** [eclipse/jetty.project#7722]
**Target Jetty version(s)** 10.0.8/11.0.8

**Enhancement Description**

The `Resource.newResource` API currently has support for `jar:`/`jar:file:`/`file:` support. It would be nice to add `classpath:` for loading resources in embedded scenario. I can create a pull request for that if it makes sense.

**Comment by joakime** [comment]
To support `classpath:` you would need to pass in the `ClassLoader` scope it needs to search from.
And it's fundamentally broken, as you cannot reference directories, only files.

Just use this instead.

``` java
ClassLoader cl = Thread.currentThread().getContextClassLoader(); // or whatever classloader you want to search from
URL url = cl.getResource("/path/to/resource/index.html");
Resource res = Resource.newResource(url);
```

Note that classloader lookup cannot find resources that are a directory in a consistent way across all JVMs and OSs.
It's designed to find resources that are files, things that can be opened with InputStream (which directories are not).

Which means that if you want the directory, you have to locate a file in that directory and resolve to that directory.

``` java
ClassLoader cl = Thread.currentThread().getContextClassLoader(); // or whatever classloader you want to search from
URL url = cl.getResource("/path/to/resource/index.html");
URL dir = url.toURI().resolve("./../").toURL();
Resource res = Resource.newResource(dir);
```

**Comment by joakime** [comment]
Also, if you are referencing URLs, that are in themselves `jar:file://path/to/foo.jar!/deep/ref/` then you need to be aware of jar file URL caching, and need to support the `useCaches` boolean (critically important on Windows).  

You might assume all classloader based resources would use `useCaches`, not true for all classpath usages, some classpath results can easily be just a simple `file://path/to/base-dir-in-classpath/path/to/resource`, which doesn't care about `useCaches` behavior.   (users of runtime compilation libs, like JSP, will encounter this all the time).

On Java 9+ your classpath usage can't even distinguish if the resource is in a jar or not in many cases, you'll get a URL like `jrt://<jpms-module-name>/<resource-in-module>` (these kinds of references are actually `useCaches` immune)

**Comment by joakime** [comment]
Also note that if you don't care about Classloader, and always want to use the thread context classloader, just use ...

``` java
Resource res = Resource.newSystemResource("/path/to/resource/index.html");
```

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.45.v20220203/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java#L217

The rules on file vs directory on `classloader.getResource(String path)` still apply though, keep that in mind.

**Comment by joakime** [comment]
Another option is [`Resource.newClasspathResource(String path)`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.45.v20220203/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java#L270), but you are on the hook to use it with the correct classloader scope.

``` java
ClassLoader oldCl = Thread.currentThread().getContextClassLoader();
try {
    Thead.currentThread().setContextClassLoader(myClassLoaderRef);
    Resource res = Resource.newClasspathResource("path/to/resource/index.html");
    // do something with this resource.
} finally {
    Thread.currentThread().setContextClassLoader(oldCl);
}
```

**Comment by sunng87** [comment]
Thank you for detailed explanation. I was trying to load ssl keystore from classpath via `SslContextFactory`'s `setKeyStorePath` which only accepts url as string and delivers to `Resource.newResource` API. So other resource APIs may not help in this case.

**Comment by joakime** [comment]
Use [`SslContextFactory.setKeyStoreResource(Resource resource)`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.45.v20220203/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L1579) instead.

Like this...

``` java
SslContextFactory.Server ssl = new SslContextFactory.Server();
ssl.setKeyStoreResource(Resource.newSystemResource("path/to/keystore.p12"));
```

**Comment by cliviu** [comment]
what about jetty 12?

**Comment by joakime** [comment]
> what about jetty 12?

Grab a `ResourceFactory`.

https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/util/resource/ResourceFactory.html

Then use one of the `ResourceFactory.newClassLoaderResource` methods that suits you.

**Comment by cliviu** [comment]
I

> > what about jetty 12?
> 
> Grab a `ResourceFactory`.
> 
> https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/util/resource/ResourceFactory.html
> 
> Then use one of the `ResourceFactory.newClassLoaderResource` methods that suits you.

Yes, I have done something like this:
```

        SslContextFactory.Server sslContextFactory = new SslContextFactory.Server();
        Resource keyStoreResource;
        if (myKeyStoreUrl.startsWith("classpath:"))
        {
            String urlWithNoClasspath = myKeyStoreUrl.substring("classpath:".length());
            keyStoreResource = ResourceFactory.of(sslContextFactory).newClassLoaderResource(urlWithNoClasspath);
        }
        else
        {
            keyStoreResource = ResourceFactory.of(sslContextFactory).newResource(myKeyStoreUrl);
         }

```

Do you know how can I register the URL type 'classpath'  at the ResourceFactory so that I can use  sslContextFactory.setKeyStorePath() with an URL that can be "file://..." or "classpath://"  ?

**Comment by joakime** [comment]
> Do you know how can I register the URL type 'classpath' at the ResourceFactory so that I can use sslContextFactory.setKeyStorePath() with an URL that can be "file://..." or "classpath://" ?

Create a new custom `ResourceFactory` that handles `classpath` scheme.
Then register it with `ResourceFactory.registerResourceFactory("classpath", new CustomResourceFactory())`

https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/util/resource/ResourceFactory.html#registerResourceFactory(java.lang.String,org.eclipse.jetty.util.resource.ResourceFactory)

Or find a URL Protocol Handler for `classpath` (an implementation of `java.net.URLStreamHandler` for protocol `classpath`) and register it via ...

``` java
ResourceFactory.registerResourceFactory("classpath", new URLResourceFactory());
```

**Comment by cliviu** [comment]
thank you!

**Comment by cliviu** [comment]
> > Do you know how can I register the URL type 'classpath' at the ResourceFactory so that I can use sslContextFactory.setKeyStorePath() with an URL that can be "file://..." or "classpath://" ?
> 
> Create a new custom `ResourceFactory` that handles `classpath` scheme. Then register it with `ResourceFactory.registerResourceFactory("classpath", new CustomResourceFactory())`
> 
> https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/util/resource/ResourceFactory.html#registerResourceFactory(java.lang.String,org.eclipse.jetty.util.resource.ResourceFactory)
> 
> Or find a URL Protocol Handler for `classpath` (an implementation of `java.net.URLStreamHandler` for protocol `classpath`) and register it via ...
> 
> ```java
> ResourceFactory.registerResourceFactory("classpath", new URLResourceFactory());
> ```
How to link the implementation of the java.net.URLStreamHandler with 
 ```java
 ResourceFactory.registerResourceFactory("classpath", new URLResourceFactory());
 ```
The URLStreamHandler is no  ResourceFactory ....

**Comment by joakime** [comment]
> How to link the implementation of the java.net.URLStreamHandler with
> 
> ```java
> ResourceFactory.registerResourceFactory("classpath", new URLResourceFactory());
> ```
> 
> The URLStreamHandler is no ResourceFactory ....

The `URLStreamHandler` is registered via Java techniques.
The registration of the protocol/scheme against `URLResourceFactory` just allows that scheme to be recognized by the URLResourceFactory, normal Java techniques kick in by the URLResourceFactory implementation.

https://github.com/jetty/jetty.project/blob/jetty-12.0.13/jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java#L233
