### ISSUE TITLE
Can not implement https server at Android.

### ISSUE THREAD

**Issue by test-kouichi-shinotsuka** [eclipse/jetty.project#7723]
Jetty Version: org.eclipse.jetty.websocket:websocket-server:9.4.45.v20220203

Java Version: openjdk 11.0.7

OS type: Android 9(API: 28)

Description:
I try to implement https server with jetty at android.
But when I start https server, "NoClassDefFoundError" is occurred at org.eclipse.jetty.util.ssl.X509 Constructor.
Not found classes are javax.naming.ldap.LdapName and javax.naming.ldap.Rdn.
Android does not support class for javax.naming.\*.
Please consider jetty's implementation not to use class for javax.naming.\*.

**Comment by joakime** [comment]
Android only supports a subset of the OpenJDK 8 classlib.
AFAIK, Android does not yet support OpenJDK 11.

Don't use the standard Jetty artifacts from maven.

You'll need to use the Jetty 9 `compact3` aggregate build from this github repository.

```
$ git clone git@github.com:eclipse/jetty.project.git
$ cd jetty.project
$ git checkout jetty-9.4.45.v20220203
$ cd build-resources/
$ mvn clean install
$ cd ../aggregates/jetty-all-compact3/
$ mvn clean install
$ ls -la target/*.jar
-rw-rw-r-- 1 joakim joakim  3465647 Mar 11 03:39 target/jetty-all-compact3-9.4.45.v20220203.jar
-rw-rw-r-- 1 joakim joakim 10246950 Mar 11 03:39 target/jetty-all-compact3-9.4.45.v20220203-javadoc.jar
-rw-rw-r-- 1 joakim joakim  2168843 Mar 11 03:39 target/jetty-all-compact3-9.4.45.v20220203-sources.jar
```

You now have a minimal Jetty artifact you can use in your Android project.

Your local Maven Repository now has the following artifact you can use.

``` xml
<dependency>
  <groupId>org.eclipse.jetty.aggregate</groupId>
  <artifactId>jetty-all-compact3</artifactId>
  <version>9.4.45.v20220203</version>
</dependency>
```

Note: the `compact3` in this build refers to runtime profiles on the Java 8 JVM.
See: https://www.oracle.com/java/technologies/javase-embedded/compact-profiles-overview.html
It just so happens that this limited Java 8 profile overlaps nicely with the requirements that Android also has.

**Comment by test-kouichi-shinotsuka** [comment]
Thanks for your reply.
I try to use jetty-all-compact3-9.4.45.v20220203.jar.
But when I start https server, "NoClassDefFoundError" is occurred at org.eclipse.jetty.util.ssl.X509 Constructor.
Not found classes are javax.naming.ldap.LdapName and javax.naming.ldap.Rdn.
What should I do?

**Comment by joakime** [comment]
At this point, it might make more sense to provide ldap stub classes in your android specific project.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.45.v20220203/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/X509.java

You'll want stub classes for ...

``` java
import javax.naming.ldap.LdapName;
import javax.naming.ldap.Rdn;
```

To handle the calls to ...

https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/X509.java#L103-L114

Having LdapName throw away the passed constructor values, and return an empty List of RDNS for the call to
https://docs.oracle.com/javase/8/docs/api/javax/naming/ldap/LdapName.html#getRdns-- should be sufficient (you won't be using LDAP on Android anyway).

**Comment by test-kouichi-shinotsuka** [comment]
Thanks for your reply.

Actually I implemented stub for 2 classes before I posted this ticket here.
I attach the files below.
Note:  LdapName.getRdns() returns non empty list for Rdn because exception is thrown if LdapName does not have "CN".

[LdapName.java.txt](https://github.com/eclipse/jetty.project/files/8249380/LdapName.java.txt)
[Rdn.java.txt](https://github.com/eclipse/jetty.project/files/8249374/Rdn.java.txt)

Therefore I success starting https server.
But I guess that regular procedure to start https server exists.
So I posted this ticket here.

Do you have any plans to improve compact3 build?

**Comment by test-kouichi-shinotsuka** [comment]
Thanks for your reply.

Actually I implemented stub for 2 classes before I posted this ticket here.
I attach the files below.
Note:  LdapName.getRdns() returns non empty list for Rdn because exception is thrown if LdapName does not have "CN".

[LdapName.java.txt](https://github.com/eclipse/jetty.project/files/8250232/LdapName.java.txt)
[Rdn.java.txt](https://github.com/eclipse/jetty.project/files/8250235/Rdn.java.txt)



Therefore I success starting https server.
But I guess that regular procedure to start https server exists.
So I posted this ticket here.

Do you have any plans to improve compact3 build?

**Comment by test-kouichi-shinotsuka** [comment]
@joakime 

There is a description that "jetty powered by devices such as Android" at below page.
https://www.eclipse.org/jetty/

So I was conceived that jetty https server can start at android.
But developer needs stubs for javax.naming classes.
Please write notation somewhere that developer needs stubs. 
For example, ReadMe.md.
