### ISSUE TITLE
Jetty-12 Callback wrapping. 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7728]
The Callback contract needs to be clear that succeeded() and failed(t) are idempotent and mutually exclusive. Most of our core Callback implementations are indeed idempotent, but wrappers do not necessarily have the same atomic protections. We need to investigate if we can improve Callback contract and/or provide better utilities for wrapping to help. Why is HttpStream is-a Callback, but we pass a Callback with Request/Response? Because in the later case the callback is associated with both objects.
From #7721

**Comment by gregw** [comment]
@sbordet quick question.  Why was `Callback.completeWith(CompletableFuture<?> completable)` added as a default method and not as a static utility method?

**Comment by gregw** [comment]
Below is a naive first implementation of how we might create an advanced `Callback` that captures the semantic this issue discusses

__I'm not advocating we do this. Nor do I like this impl.  I'm just writing down the semantic as I understand it to make sure we are all on the same page__ 

```java
    abstract class AdvancedCallback implements Callback
    {
        public abstract boolean trySucceeded();

        public abstract void onSuccess();

        @Override
        public final void succeeded()
        {
            if (trySucceeded())
                onSuccess();
        }

        public abstract boolean tryFailure(Throwable x);

        public abstract void onFailure(Throwable cause);

        @Override
        public final void failed(Throwable x)
        {
            if (x == null)
                x = new Throwable();
            if (tryFailure(x))
                onFailure(x);
        }
    }

    class CallbackWrapper extends AdvancedCallback
    {
        private final AdvancedCallback _wrapped;

        public CallbackWrapper(AdvancedCallback wrapped)
        {
            _wrapped = wrapped;
        }

        @Override
        public final boolean trySucceeded()
        {
            return _wrapped.trySucceeded();
        }

        @Override
        public final boolean tryFailure(Throwable x)
        {
            return _wrapped.tryFailure(x);
        }

        @Override
        public void onSuccess()
        {
            _wrapped.onSuccess();
        }

        @Override
        public void onFailure(Throwable cause)
        {
            _wrapped.onFailure(cause);
        }
    }

    abstract class BaseCallbackExample extends AdvancedCallback
    {
        private static final Throwable SUCCESS = new Throwable();
        private final AtomicReference<Throwable> _complete = new AtomicReference<>();

        @Override
        public final boolean trySucceeded()
        {
            return _complete.compareAndSet(null, SUCCESS);
        }

        @Override
        public boolean tryFailure(Throwable x)
        {
            return _complete.compareAndSet(null, x);
        }

        public abstract void onSuccess();

        public abstract void onFailure(Throwable cause);
    }
```

There are lots inefficiencies and issues with this approach,    But before we discuss those and analyse further, I want to check that we are all talking about the same semantic???

**Comment by sbordet** [comment]
> @sbordet quick question. Why was Callback.completeWith(CompletableFuture<?> completable) added as a default method and not as a static utility method?

Because it was acting on an existing `Callback` instance, and it was more natural to add it as non-static.
I have no objections converting it to a `static` method.

**Comment by sbordet** [comment]
> There are lots inefficiencies and issues with this approach, But before we discuss those and analyse further, I want to check that we are all talking about the same semantic???

Semantic seems right to me.
What inefficiencies do you refer to, exactly? The fact that we run twice the callback wrappings?

**Comment by gregw** [comment]
@sbordet I've been doing some experiments, but am finding it hard to be conclusive one way or the other as so much of the branch doesn't compile.     I think I will defer further effort/discussion on this until we have a clean build, so we can reason about callback usages/extensions/wrappers without dealing with broken code.

**Comment by gregw** [comment]
@sbordet OK I lied... my brain didn't defer this until later and I was tossing and turning the last few nights about this.   I don't think this works as it turns async code into a synchronous calling chain between the decision to act and the actual act.
For example, consider the current processor code like:
```java
    void process(Request request, Response response, Callback callback)
    {
        response.setStatus(503);
        callback.succeeded();
    }
``` 

If we start thinking that Callback should provide protected before and after actions, then that setStatus should not be done if the callback is going to fail.   So we could rewrite:

```java
    void process(Request request, Response response, Callback callback)
    {
        new CallbackWrapper(callback)
        {
            public void onSuccess()
            {
                response.setStatus(503);
                super.onSuccess();
            }
        }.succeeded();
    }
```
This kind of works... but only if all other potential callers also wrap their behaviours in such a callback AND only if the base callback is very specific about it's actions.  Currently a call to succeeded on that callback will disable the setStatus method so it can't be called.  With the advanced callback, the trySucceeded call could not do this disable, since the setStatus is done afterwards.    So we would get an atomic decision to act, but the APIs have to be left open until the super call to onSuccess.  Thus the APIs are only protected if all other potential callers of setStatus also wrap their behaviours in AdvancedCallbacks.  

Maybe this could work... but not for async code.   What if the original code was:
 
```java
    void process(Request request, Response response, Callback callback)
    {
        response.setStatus(503);
        response.write(true, callback, "UNAVAILABLE);
    }
``` 

How is that async write going to be put into an `onSuccess` method?    I guess it could be done with the write callback being used to somehow call super.onSuccess, but that will be ugly, complex and difficult.  Even if it can be made to work, it is fragile as any non- AdvancedCallback wrapper in the chain will break the logic.

I think async apps/processors will all have variations on the decision to act followed by the action.  I'm not sure we can generically wrap that up into a before-success method on an advanced callback.

Instead, I have done some experiments with just returning a boolean from callback succeeded and fail, so that after-actions can be correctly conditional (eg in the statistics handler).   However, I have put those experiments on hold until we have more code compiling, so I can better identify the cases where that doesn't work so well.

**Comment by joakime** [comment]
Closing, the `Handler.process` change from #9035 has been merged.
