### ISSUE TITLE
Allow overriding of url-pattern mapping in ServletContextHandler to allow for regex or uri-template matching

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7748]
**Target Jetty version(s)**
10.0.9

**Enhancement Description**

The current ServletContextHandler does it's job nicely with regards to Servlet "url-pattern" based lookups of mapped servlets and filters.
But internally our Path Mapping layer (at `org.eclipse.jetty.http.pathmap`) supports Regex and UriTemplate as well as the original Servlet url-pattern.

Rework `ServletContextHandler` to allow more sophisticated embedded use of the regex and uri-template options for mapping as well.

**Comment by gregw** [comment]
Needs merging to 12.

**Comment by gregw** [comment]
We may also need this in a 9.4 release

**Comment by gregw** [comment]
Closing as:
 + cherry picked 10 to 9
 + improved in 9
 + cherry picked 9 to 10
 + merged to 11
 + cherry picked to 12
 + manually fixed when cherry-pick to 12 missed the renamed files!

whew!
