### ISSUE TITLE
Does Jetty 9.4.x supports RESTEasy 6?

### ISSUE THREAD

**Issue by selva3k** [eclipse/jetty.project#7749]
**Jetty version**
9.4.35

**Java version**
1.8

**Question**
Does Jetty 9.4.35(java version:1.8) supports RESTEasy 6?  If yes, please share some material for the integration (if you have any reference)

**Comment by joakime** [comment]
https://docs.jboss.org/resteasy/docs/6.0.0.Final/userguide/html_single/index.html#standalone_resteasy

This would be a better question to ask the folks at Resteasy.
We don't know the internals of Resteasy to be able to answer that.
