### ISSUE TITLE
jetty.sh ignores JAVA_OPTIONS environment variable

### ISSUE THREAD

**Issue by TimePerformance** [eclipse/jetty.project#7754]
**Jetty version(s)**
10.0.8

**Java version/vendor** `(use: java -version)`
OpenJDK Runtime Environment Corretto-17.0.2.8.1

**OS type/version**
Amazon Linux 2

**Description**
Jetty failed to start after migrating from 10.0.6 to 10.0.8 (no jetty-start.log, no jetty.log)

What is strange is that in jetty.sh, JAVA_OPTIONS is mentioned in the doc in the header of the file but it is not used (except in dumpEnv). 

I've replaced the following lines:

JETTY_SYS_PROPS=$(echo -ne "-Djetty.home=$JETTY_HOME" "-Djetty.base=$JETTY_BASE" "-Djava.io.tmpdir=$TMPDIR")
RUN_ARGS=$("$JAVA" -jar "$JETTY_START" --dry-run=opts,path,main,args ${JETTY_ARGS[*]})
RUN_CMD=("$JAVA" $JETTY_SYS_PROPS ${RUN_ARGS[@]})

(note: having "$JAVA" in RUN_ARGS is strange)

by the corresponding lines from jetty.sh in version 10.0.6:

JAVA_OPTIONS=(${JAVA_OPTIONS[*]} "-Djetty.home=$JETTY_HOME" "-Djetty.base=$JETTY_BASE" "-Djava.io.tmpdir=$TMPDIR")
RUN_ARGS=(${JAVA_OPTIONS[@]} -jar "$JETTY_START" ${JETTY_ARGS[*]})
RUN_CMD=("$JAVA" ${RUN_ARGS[@]})

and now it starts.

**Comment by joakime** [comment]
`RUN_ARGS` must be built from `--dry-run` to avoid a forked JVM.

That means JAVA_OPTIONS must come from your `${jetty.base}` configuration (see `jvm` module).

Your change allows for a forked JVM.

The other option you have is to use `$JETTY_SYS_PROPS` instead of `$JAVA_OPTIONS`. (this is because `$JAVA_OPTIONS` does not carry over to the forked JVM, but the `$JETTY_SYS_PROPS` will)

**Comment by TimePerformance** [comment]
thanks a lot for the explanation

**Comment by TimePerformance** [comment]
It seems that $JETTY_SYS_PROPS is redefined in the jetty.sh like that
`JETTY_SYS_PROPS=$(echo -ne "-Djetty.home=$JETTY_HOME" "-Djetty.base=$JETTY_BASE" "-Djava.io.tmpdir=$TMPDIR" `
Thus previous value of $JETTY_SYS_PROPS is ignored

I've tried to use the jvm module. I've set system properties in jvm.ini with the -DMY_VAR=VALUE syntax. However, in the  RUN_CMD generated by the dry run, ${MY_VAR} are not expanded which causes troubles.

For instance, 
in jvm.ini:
--exec
-DWORKERNAME=localhost 

in sessions.ini:
jetty.sessionIdManager.workerName=${WORKERNAME}

The RUN_CMD contains -DWORKERNAME=localhost jetty.sessionIdManager.workerName=${WORKERNAME} but ${WORKERNAME} is not expanded even when it is run.

**Comment by joakime** [comment]
for property expansion in start modules (be it in `*.mod`, or `*.ini`, or `*.xml`), use simple post-jar properties, don't rely on system properties (that's last resort, backup solution, not the primary solution)

for your example, the use of `JETTY_ARGS` to set the simple property should be enough.  (don't prepend with `-D`)

``` shell
JETTY_ARGS="WORKERNAME=localhost"
```
