### ISSUE TITLE
NCSARequestLog will log extra space when username or user-agent is null

### ISSUE THREAD

**Issue by dynastywind** [eclipse/jetty.project#778]
It's found that there will be extra spaces logged when username or user-agent field is null.

For example, if username is null and its format is %u, then the corresponding field in the log record will be ' - '. Note that '-' is both prepended and appended with a space.

And if user-agent is null and its format is "%{user-agent}i", the result will be
```
"-" 
```
Note that there's an extra space appended after ".

I've no idea if it's a bug or you just do it intentionally. This will cause problems when parsing the log records.

**Comment by gregw** [comment]
Is this the same issue that was just fixed by #770?   If so then that's a huge coincidence!  What are you guys using that is so sensitive to the extra space.  So can you confirm if #770 is a fix for your issue?

**Comment by gregw** [comment]
Ah I see that #770 was a result of your issue raised on logparser: https://github.com/nielsbasjes/logparser/issues/30 .  So I'm closing this as fixed, thanks to @nielsbasjes

**Comment by dynastywind** [comment]
Ah, didn't see that. Thank you.
