### ISSUE TITLE
JSP Session updated before sendRedirect() lose their information

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#784]
Take the following example:

**initial.jsp**

```jsp
<%
    session.setAttribute("foo", "hello");
    response.sendRedirect("/alt.jsp");
%>
```

**alt.jsp**

```jsp
<%@page contentType="text/plain" %>
sess["foo"]=<%=session.getAttribute("foo")%>
```

Some facts:

 * When you hit `/initial.jsp` a 302 redirect is issued to `/alt.jsp`.
 * When `alt.jsp` is executed, the session attribute `"foo"` is `<null>`.
 * The 302 redirect response is missing the `jsessionid` cookie

**Comment by janbartel** [comment]
Unable to reproduce either with servlets or jsps when both redirector and redirect target are on the same node and context. More info needed.

**Comment by janbartel** [comment]
Unable to reproduce. If more info becomes available, please reopen.
