### ISSUE TITLE
Jetty WebSocketClient hanging threads after connection is closed

### ISSUE THREAD

**Issue by xiaochen-db** [eclipse/jetty.project#7852]
**Jetty version**
9.3.27

**Java version**
1.8.0_282

**Question**
I am using WebSocketClient for connecting to servers that supports websocket protocol. The code snippet is written in scala but using Jetty's Java interfaces. I allocated a thread pool to help track the threads allocated by WebSocketClient, as I give each thread a name in form of `ws-client-%d` (%d is the serial number)

```
import java.net.URI
import java.util.concurrent.{SynchronousQueue, ThreadPoolExecutor, TimeUnit}
import com.google.common.util.concurrent.ThreadFactoryBuilder
import org.eclipse.jetty.websocket.api.Session
import org.eclipse.jetty.websocket.api.annotations._
import org.eclipse.jetty.websocket.client.{ClientUpgradeRequest, WebSocketClient}

object Main {
  def main(args: Array[String]): Unit = {
    // corePoolSize = 1, maxPoolSize = 100, keepAliveTime = 150 seconds
    val threadPool = new ThreadPoolExecutor(1,100,150, TimeUnit.SECONDS,
      new SynchronousQueue[Runnable](),
      new ThreadFactoryBuilder()
        .setDaemon(true)
        .setNameFormat("ws-client-%d") // name thread as "ws-client-%d" 
        .build(),
      new ThreadPoolExecutor.AbortPolicy()
    )
    val client = new WebSocketClient(threadPool)
    client.start()
    val request = new ClientUpgradeRequest()
    val socket = new ClientWebSocket()
    client.connect(socket, URI.create("ws://localhost:8888"), request).get(1, TimeUnit.SECONDS) // A jetty websocket server listens on 8888
  }
}

@WebSocket
private class ClientWebSocket() {
  @OnWebSocketMessage
  def onMessage(msgString: String): Unit = {
    println(msgString)
  }
  @OnWebSocketClose
  def onClose(statusCode: Int, reason: String): Unit = {
    println(s"closed: $statusCode and $reason")
  }
  @OnWebSocketConnect
  def onConnect(session: Session): Unit = {
    println("connected")
  }
  @OnWebSocketError
  def onError(cause: Throwable): Unit = {
    println(s"error: $cause")
  }
}
```
I used `jstack <WebSocketClient process id> | grep ws-client` to count the number of threads allocated by WebSocketClient.

I found 10 threads allocated when WebSocketClient is connected to the websocket server listening on port 8888
```
% jstack 12733 | grep ws-client
"ws-client-9" #29 daemon prio=5 os_prio=31 tid=0x00007fe5c225e800 nid=0x6d03 runnable [0x0000700004ecc000]
"ws-client-8" #27 daemon prio=5 os_prio=31 tid=0x00007fe5c297e800 nid=0x9203 waiting on condition [0x0000700004cc6000]
"ws-client-7" #26 daemon prio=5 os_prio=31 tid=0x00007fe5a1895000 nid=0x9403 runnable [0x0000700004bc3000]
"ws-client-6" #25 daemon prio=5 os_prio=31 tid=0x00007fe5a2072000 nid=0x6903 runnable [0x0000700004ac0000]
"ws-client-5" #24 daemon prio=5 os_prio=31 tid=0x00007fe5a2071000 nid=0x9603 runnable [0x00007000049bd000]
"ws-client-4" #23 daemon prio=5 os_prio=31 tid=0x00007fe5a206e000 nid=0x9703 runnable [0x00007000048ba000]
"ws-client-3" #22 daemon prio=5 os_prio=31 tid=0x00007fe5a206b800 nid=0x9803 runnable [0x00007000047b7000]
"ws-client-2" #21 daemon prio=5 os_prio=31 tid=0x00007fe5a1892800 nid=0x6603 runnable [0x00007000046b4000]
"ws-client-1" #20 daemon prio=5 os_prio=31 tid=0x00007fe5c297a800 nid=0x9b03 runnable [0x00007000045b1000]
"ws-client-0" #19 daemon prio=5 os_prio=31 tid=0x00007fe5a2068800 nid=0x9d03 waiting on condition [0x00007000044ae000]
```
Then I killed the server so the websocket is disconnected, I realized 8 threads are hanging in "runnable" state 
```
% jstack 12733 | grep ws-client
"ws-client-7" #26 daemon prio=5 os_prio=31 tid=0x00007fe5a1895000 nid=0x9403 runnable [0x0000700004bc3000]
"ws-client-6" #25 daemon prio=5 os_prio=31 tid=0x00007fe5a2072000 nid=0x6903 runnable [0x0000700004ac0000]
"ws-client-5" #24 daemon prio=5 os_prio=31 tid=0x00007fe5a2071000 nid=0x9603 runnable [0x00007000049bd000]
"ws-client-4" #23 daemon prio=5 os_prio=31 tid=0x00007fe5a206e000 nid=0x9703 runnable [0x00007000048ba000]
"ws-client-3" #22 daemon prio=5 os_prio=31 tid=0x00007fe5a206b800 nid=0x9803 runnable [0x00007000047b7000]
"ws-client-2" #21 daemon prio=5 os_prio=31 tid=0x00007fe5a1892800 nid=0x6603 runnable [0x00007000046b4000]
"ws-client-1" #20 daemon prio=5 os_prio=31 tid=0x00007fe5c297a800 nid=0x9b03 runnable [0x00007000045b1000]
"ws-client-0" #19 daemon prio=5 os_prio=31 tid=0x00007fe5a2068800 nid=0x9d03 runnable [0x00007000044ae000]
```

So why are these threads hanging instead of being recycled? What is the mechanism for jetty thread pool management? Does my code miss some clean-up steps to leave the threads hanging? 

I am concerning since in a real application, I've seen 1000+ such hanging threads that exhaust the entire pool. The thread pool would reject any future `WebSocketClient.connect()`. 

Thanks.

**Comment by sbordet** [comment]
Most likely the executor is your problem. Please try again using `QueuedThreadPool`, or a `ThreadPoolExecutor` with an unbounded queue.

Without stack traces is not possible to tell, but likely the threads you report are selector threads.
If that's the case, they are normal and expected.

**Comment by joakime** [comment]
Jetty 9.3.x is EOL, please upgrade to at least Jetty 9.4.x.

**Comment by joakime** [comment]
Also Java 1.8.0_282 expired on April 20, 2021 and is not meant to be used anymore.
See release notes that came with that JVM.

You are strongly encouraged to upgrade that as well.

**Comment by xiaochen-db** [comment]
@sbordet Thanks for the reply!

I tried the `QueuedThreadPool` and there's the stack trace for one such "runnable" thread (other "runnable" threads show similar stack trace):
```
"qtp1908923184-21" #21 prio=5 os_prio=0 tid=0x00007ff154998000 nid=0x635c runnable [0x00007ff113018000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000fa440208> (a sun.nio.ch.Util$3)
	- locked <0x00000000fa440218> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000fa4401c0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:243)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:191)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:249)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:100)
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
``` 

All threads states:
```
$ jstack 25009 | grep qtp
"qtp1908923184-39" #39 prio=5 os_prio=0 tid=0x00007ff0b800d800 nid=0x68eb waiting on condition [0x00007ff112812000]
"qtp1908923184-29" #29 prio=5 os_prio=0 tid=0x00007ff08c001000 nid=0x6363 runnable [0x00007ff112913000]
"qtp1908923184-25" #25 prio=5 os_prio=0 tid=0x00007ff15499f000 nid=0x6360 runnable [0x00007ff112c13000]
"qtp1908923184-24" #24 prio=5 os_prio=0 tid=0x00007ff15499d800 nid=0x635f runnable [0x00007ff112d15000]
"qtp1908923184-23" #23 prio=5 os_prio=0 tid=0x00007ff15499b800 nid=0x635e runnable [0x00007ff112e16000]
"qtp1908923184-22" #22 prio=5 os_prio=0 tid=0x00007ff15499a000 nid=0x635d runnable [0x00007ff112f17000]
"qtp1908923184-21" #21 prio=5 os_prio=0 tid=0x00007ff154998000 nid=0x635c runnable [0x00007ff113018000]
"qtp1908923184-20" #20 prio=5 os_prio=0 tid=0x00007ff154996800 nid=0x635b runnable [0x00007ff113119000]
"qtp1908923184-19" #19 prio=5 os_prio=0 tid=0x00007ff154994800 nid=0x635a runnable [0x00007ff11321a000]
```

If selector threads are normal, what are they doing? What jetty or non-jetty behaviors cause the number of selector threads to rise or drop? Can more threads to be used if we didn't clean up resources during `OnWebSocketClose`?

**Comment by xiaochen-db** [comment]
@joakime Thanks for the reply! Java 1.8.0_282 happens to be where I tested the snippets. I will push our team for upgrading jetty to 9.4.x.

**Comment by sbordet** [comment]
@xiaochen-db yes those are selector threads, and they are used by Jetty for non-blocking I/O, so they are normal and expected.
Their number is fixed.

If you see 1000+ blocked threads, you have another problem. Take a thread dump of the 1000+ threads, and you will see where they are blocking. I'm expecting either your own code, or they are blocked in I/O due to the receiving side not reading fast enough.

**Comment by xiaochen-db** [comment]
@sbordet I think I found the root cause in my application: we keep creating new `WebSocketClient` against the same shared thread pool without calling `WebSocketClient.stop()` on old ones. As a result, the selector threads accumulate to the maximum thread pool capacity and causes the pool to stall.

I _think_ the old `WebSocketClient`s are GC'ed, but I am little surprised that the selector threads are still alive after that.

Before closing this question, I want to ask about the `WebSocket` recycling methodology. For example, would `WebSocket`s and their resources (e.g. internal objects, threads managing them) be destroyed or recycled after `OnWebSocketClose` is called? Does an application need to explicitly close the `Session` object from the `OnWebSocketClose ` method? 

Thanks again for your helps!

**Comment by lachlan-roberts** [comment]
> Does an application need to explicitly close the Session object from the OnWebSocketClose method?

No, if the `OnWebSocketClose` method has been called a close response will be automatically sent after, you should not need to close the `Session` from `OnWebSocketClose` unless you try to send a custom close frame.

> would WebSockets and their resources (e.g. internal objects, threads managing them) be destroyed or recycled after OnWebSocketClose is called?

The resources associated with that specific WebSocket connection are released. However one `WebSocketClient` may have many WebSocket connections so there are still resources the client keeps until it is stopped.
