### ISSUE TITLE
Remove accidentally included package-info.class in all packages

### ISSUE THREAD

**Issue by gonphsn** [eclipse/jetty.project#7855]
**Jetty version**
jetty-all-compact3-9.4.46.v20220331.jar vs jetty-all-compact3-9.4.45.v20220203.jar

**Java version**
N/A

**Question**
I observed in a diff of the contents of jetty-all-compact3-9.4.45 and jetty-all-compact3-9.4.46 that the latter now contains a package-info.class at every package. See:

![image](https://user-images.githubusercontent.com/32906094/162246610-79eb93e9-cfc5-4661-b877-0bce5b370c00.png)

It was not immediately clear to me from the release notes where this may have been introduced. I know compact3 can be an often overlooked profile, and while the file size increase is marginal, I was curious if this was intentional?

Maybe compact3 has nothing to do with it - I'll compare this to the standard profile as well. UPDATE: It is also in the standard distributions, so nothing to do with compact3 I think.

Thanks!

**Comment by joakime** [comment]
There's been no updates to the pom for the compact3 build in a long time.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/aggregates/jetty-all-compact3/pom.xml

The most recent update was 17 months ago. (commit https://github.com/eclipse/jetty.project/commit/3e35ec362cf408ee254002bfb2c785cccb50e4ca)
And was first present on `jetty-9.4.35.v20201120`

Not sure how you see differences in 9.4.45 to 9.4.46.

Do we need another exclusion on `dependency:unpack-dependencies` perhaps?

**Comment by gonphsn** [comment]
@joakime I've concluded that this is not a compact3 specific issue - it is just where I noticed it first since that is the build we consume. Sorry for the red herring. 

See the following diff just from standard profile distributions published at maven central:

![image](https://user-images.githubusercontent.com/32906094/162256730-0120053c-482e-4957-a505-5b1a44444cd1.png)

**Comment by joakime** [comment]
I can confirm that `package-info.class` is now present on 9.4.46, but not older releases.
This seems like a `maven-jar-plugin` behavior change.

@olamy any thoughts?

**Comment by joakime** [comment]
The `maven-compiler-plugin` is actually compiling them into `${project.basedir}/target/classes`.  Hmm...

**Comment by joakime** [comment]
Confirmed, `maven-compiler-plugin` version 3.10.0 (and the newest 3.10.1) both start compiling the `package-info.java` files into `target/classes`.
The older `maven-compiler-plugin` 3.9.0 does not.

**Comment by joakime** [comment]
This behavior change in `maven-compiler-plugin` 3.10.0 comes from.

* https://issues.apache.org/jira/browse/MCOMPILER-205
* https://github.com/apache/maven-compiler-plugin/pull/88

**Comment by gonphsn** [comment]
Ok, thanks for the confirmation on your end.

**Comment by joakime** [comment]
I opened PR #7856 to configure the maven-compiler-plugin to not do that anymore on our builds.

You can compile with `-Dmaven.compiler.createMissingPackageInfoClass=false` to make the compiler plugin behave like before.
