### ISSUE TITLE
Buffering Response Handler

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#786]
Add a handler that allows an entire response body to be buffered before commit

**Comment by joakime** [comment]
Any advice on when mixing GzipHandler and this new BufferedResponseHandler?

I would think it would be advisable to stick the BufferedResponseHandler after the GzipHandler.

Like this:

Servlet output -> GzipHandler -> BufferedResponseHandler -> Network

It would reduce the size of the buffers being held in memory.

Do we have a testcase on what would happen if the Servlet (or ErrorHandler) decides to just suddenly call HttpServletResponse.sendError() or just use .setStatus(400) and exit?

**Comment by gregw** [comment]
@joakime I saw your comment else where that gzip->buffered->network has minimal memory footprint, while buffered->gzip->network may have better gzip performance.   I think this is correct.

I tend to think the former is more important as the later is still behind an aggregate buffer in HttpOutput and would only be exposed to really poor gzip performance if there was a lot of flushing going on.

**Comment by joakime** [comment]
Closing as this was implemented, with warts and all.
