### ISSUE TITLE
Default servlet drops first accept-encoding header if there is more than one.

### ISSUE THREAD

**Issue by markslater** [eclipse/jetty.project#7863]
**Jetty version(s)**
11.0.9

**Java version/vendor** `(use: java -version)`
N/A

**OS type/version**
N/A

**Description**
When `DefaultServlet` handles a request with multiple `accept-encoding` headers, it attempts to combine their values, but it drops the value of the first header (and produces a value with a leading comma).

**How to reproduce?**
Test case to follow.

**Comment by joakime** [comment]
All merged into `jetty-9.4.x` and `jetty-10.0.x`+
