### ISSUE TITLE
support for non-blocking flushes

### ISSUE THREAD

**Issue by phraktle** [eclipse/jetty.project#787]
With asynchronous writes from a servlet, it would be useful to expose the non-blocking equivalent of the `flushBuffer` call.

**Comment by gregw** [comment]
This is already supported as the normal flush API becomes a non-blocking flush once async write mode is entered (just as the write methods become async also).

See [`HttpOutput.flush`](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java#L291-L325)

I'm not 100% this is well specified in the servlet spec, but it is certainly the only sensible way to interpret the spec and has been implemented IMNSHO. If other containers don't do this, I'd raise bugs on them:)
