### ISSUE TITLE
Attempting to activate a module that is already enabled

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#788]
If a user attempts to enable a module that is already active, there is no warning or message that instructs them to that effect. We should enable a message that effectively says "This module already exists in _directory/*.ini_". 

This is an aesthetic/educational change only - the current process is functionally perfect; it is not adding additional *.ini files in _{$jetty.base}/start.d_ or amending lines to _{$jetty.base}/start.ini_.

**Comment by gregw** [comment]
In 9.4.x we kind of say the inverse, telling the user that no files were changed.  But a helpful message saying that a module is already enabled could be helpful.   However it can be a little complex if a module is already enabled transitively and has not configuration (so not entry in start.d).

Anyway, will look to see what we can do to make this clearer.

**Comment by gregw** [comment]
This is warning too often.  It should not warn during a normal run, it should only warn during and --add-to-start

**Comment by gregw** [comment]
How were these commits merged?    There should have been a PR and all the commits squashed into 1.

**Comment by WalkerWatch** [comment]
Greg, there was #820 that resolved this. Was made up of three commits, albeit one was a merge for my private fork for whatever reason. Unsure why it didn't get flagged on this issue.

**Comment by gregw** [comment]
@WalkerWatch Github normally shows the link to a PR... anyway still confused as there are more commits here than in the PR?        I might just revert, look at a single diff then review and apply with a fix

**Comment by WalkerWatch** [comment]
@gregw I am not sure. I tried to make sure I squashed them all to avoid a mess. Relatively sure https://github.com/eclipse/jetty.project/pull/820/commits/11131acae9bf8300f02c3e0437028373a85d8161 has everything in one commit.

**Comment by gregw** [comment]
@WalkerWatch actually I can see it all in ceed03b, which is the merge commit.

However, I'm not so keen on the change anyway and may revert pending some more analysis.  It is a highly recursive piece of code and changes can have non obvious effects.      Let me ponder a bit more and see if a simple fix is available.

**Comment by gregw** [comment]
Committed a much simpler fix that only looks at the end results and does not attempt to warn deep in the recursive enable method.  It only gives info for `--add-to-start` and not pure `--module` commands.

**Comment by gregw** [comment]
oh ... and sorry for the revert... I should have paid more attention before

**Comment by joakime** [comment]
This revert now causes a documentation concern on past documentation updates from @WalkerWatch that relied on those warnings and the explanation of what is actually going on.

I'm personally -1 for this revert, as it makes the behavior more "magical" and less clear now.

**Comment by joakime** [comment]
I propose we solve this again.

But those warnings should only be displayed when the `--add-to-start` is being used, and not at any other time.

Perhaps we introduce an internal "mode" or "phase" for start.jar which tracks what is actively going on.

Some example phases:

 - **Parsing** - this would the action of parsing the command line, start.ini, and startd/*.ini files stage
 - **Building** - this could be the building of module graph identification and `--add-to-start` phases
 - **Starting** - this could be the normal execution of the XMLConfiguration
 - **Testing** - this could be the special testing mode (that already exists in the start.jar)
 - **Info** - this could be any path that doesn't start XMLConfiguration and is purely informational (like showing `--list-config` or `--help`)

WDYT?

**Comment by jmcc0nn3ll** [comment]
I think the change @gregw made addresses the original need.  We do want less magic in general though, it is pretty obvious to us what is going on but for someone coming to this stuff fresh we need to be as clear as possible what is going on.

```
[catan](jetty-9.4.x)distribution/test-base> java -jar ../start.jar --create-startd
INFO : Base directory was modified
[catan](jetty-9.4.x)distribution/test-base> java -jar ../start.jar --add-to-start=proxy
INFO : proxy           initialised in ${jetty.base}/start.d/proxy.ini
INFO : server          initialised (transitively) in ${jetty.base}/start.d/server.ini
INFO : Base directory was modified
[catan](jetty-9.4.x)distribution/test-base> java -jar ../start.jar --add-to-start=server
INFO : server already enabled by [${jetty.base}/start.d/server.ini]
INFO : Base directory was not modified
[catan](jetty-9.4.x)distribution/test-base> 
```

**Comment by jmcc0nn3ll** [comment]
I wonder if we should review all the output of start.jar --add and --create behavior, those lines about the base directory being modified are kinda meh.  I can totally see a --verbose option that makes all that show up but by default maybe we should be more succinct.

**Comment by joakime** [comment]
The `--verbose` option has merit (and easier to implement too)

**Comment by gregw** [comment]
We now get the output like:
```
INFO : logging-logback already enabled by [${jetty.base}/start.d/logging-logback.ini]
INFO : Base directory was not modified
```
