### ISSUE TITLE
the clinit of MimeTypes can fail with nullpointer

### ISSUE THREAD

**Issue by andresluuk** [eclipse/jetty.project#7893]
**Jetty version(s)**
latest Jetty: 9.4.46.v20220331 and earlier

**Java version/vendor** `(use: java -version)`
JDK 8, but does not matter

**OS type/version**
I used windows, but does not matter

**Description**
The static initializer of MimeTypes has a 2 lines with:
try (InputStream stream = MimeTypes.class.getClassLoader().getResourceAsStream(resourceName)) {
those can fail with nullpointer if Jetty is on java bootclasspath, ie. MimeTypes.class.getClassLoader() returns null.
The result is that the class MimeTypes fails.

**How to reproduce?**
Add jetty to bootclasspath with -Xbootclasspath/a:path and not on normal classpath. Now try to load and initilize MimeTypes with reflection.

**Comment by joakime** [comment]
I cannot see a valid workaround for this.
MimeTypes (and anything else that needs ClassLoader resources) just cannot exist on the bootclasspath.

**Comment by andresluuk** [comment]
I think a getClassLoader() == null check would also be good there or replacing the get with .class.getResourceAsStream(...) without directly finding out the classloader? I think jetty 10 does it that way.
I think it would be fine if it does not find any resources there, it would just be better if it would not have a fatal fail on clinit.

**Comment by sbordet** [comment]
What your reason to put Jetty in the boot class-path?

We have a million places where we assume the Jetty classloader is not null, so to survive when Jetty is in the boot class-path we would have to make a million changes.

I don't see see the use case for putting Jetty on the boot class-path, so closing.
