### ISSUE TITLE
CrossOriginFilter continues chain when origin does not match

### ISSUE THREAD

**Issue by rkennedy-mode** [eclipse/jetty.project#7894]
**Jetty version(s)**

9.4.35+

**Java version/vendor** `(use: java -version)`

All

**OS type/version**

All

**Description**

CrossOriginFilter continues the filter chain when the request `Origin` header value does not match any allowed origins: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java#L309

This means that preflight requests with non-matching origins "fall through" and continue execution within the application server instead of returning a failed preflight response.

This does not seem to be in keeping with the (very) limited documentation I can find regarding handling CORS preflight requests.

**How to reproduce?**

1. Create an endpoint that returns a non HTTP 2xx response and a recognizable body (e.g. "this is my endpoint").
2. Set the CrossOriginFilter `allowedOrigins` init parameter to `host-a.com` and then send a CORS preflight `OPTIONS` request to the endpoint with the header `Origin: host-b.com`.
3. Rather than return an HTTP 200 response with no `Access-Control-Allow-*` headers the server will return the response of the endpoint created in step 1.

**Comment by joakime** [comment]
Are `host-a.com` and `host-b.com` both hosted on the same Jetty instance?
What does virtualhosts setup look like?

**Comment by rkennedy-mode** [comment]
> Are `host-a.com` and `host-b.com` both hosted on the same Jetty instance?

Let's assume they are not (in the case I've run into locally they are not).

> What does virtualhosts setup look like?

There is no virtualhosts setup.

**Comment by joakime** [comment]
If your `CrossOriginFilter` configuration for `"allowedOrigins"` doesn't have `host-b.com` then none of the `CrossOriginFilter` behaviors are applied, regardless of the HTTP Method.

For the cases where you care about Cross Origin behaviors (ie: browsers), a properly setup `CrossOriginFilter` will return the list of origins it allows in the `Access-Control-Allow-Origin` response header, from there on out, it's the Browser in control.

If you have `allowedOrigins = "host-a.com"` configured, and made a request, it would return `Access-Control-Allow-Origin: host-a.com`, which would then instruct the browser to not send requests to `host-a.com` from an origin that isn't `host-a.com`.   So your server would never see a request with `Origin: host-b.com` from a browser that supports Cross Origin behaviors.

Finally, an `OPTIONS` request with an `Origin` header would be quite surprising to me.
Do you have evidence of a Browser actually doing that?  If so, I'd like details.

**Comment by rkennedy-mode** [comment]
> If your `CrossOriginFilter` configuration for `"allowedOrigins"` doesn't have `host-b.com` then none of the `CrossOriginFilter` behaviors are applied, regardless of the HTTP Method.
> 
> For the cases where you care about Cross Origin behaviors (ie: browsers), a properly setup `CrossOriginFilter` will return the list of origins it allows in the `Access-Control-Allow-Origin` response header, from there on out, it's the Browser in control.
> 
> If you have `allowedOrigins = "host-a.com"` configured, and made a request, it would return `Access-Control-Allow-Origin: host-a.com`, which would then instruct the browser to not send requests to `host-a.com` from an origin that isn't `host-a.com`. So your server would never see a request with `Origin: host-b.com` from a browser that supports Cross Origin behaviors.
> 
> Finally, an `OPTIONS` request with an `Origin` header would be quite surprising to me. Do you have evidence of a Browser actually doing that? If so, I'd like details.

Every CORS preflight request is an `OPTIONS` request: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request. CrossOriginFilter knows this as it's one of the things that it checks for when evaluating whether a request is a preflight request or not: https://github.com/eclipse/jetty.project/blob/69c208b6e4f8e16429a3e09b4b9e874e3c76cafb/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java#L379

The problem is that the origin is checked **before** the filter checks to see if it's a preflight request. Since the origin doesn't match, the filter appears to assume that it's not a preflight request and forwards the request on to the remainder of the filter chain, which is not what the preflight request from the browser intended.

**Comment by joakime** [comment]
The Jetty implementation of `CrossOriginFilter` was created against the original spec at https://www.w3.org/TR/2020/SPSD-cors-20200602/

This specifically calls out that a Preflight request without a matching Origin is to skip the steps of Preflight.

https://www.w3.org/TR/2020/SPSD-cors-20200602/#resource-preflight-requests  (See sub-point 2)

> 2. If the value of the [Origin](https://www.w3.org/TR/2020/SPSD-cors-20200602/#http-origin) header is not a [case-sensitive](https://www.w3.org/TR/2020/SPSD-cors-20200602/#case-sensitive) match for any of the values in [list of origins](https://www.w3.org/TR/2020/SPSD-cors-20200602/#list-of-origins) do not set any additional headers and terminate this set of steps.

**Comment by rkennedy-mode** [comment]
CrossOriginFilter doesn't terminate, however. It continues on [executing the rest of the filter chain](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java#L313) as though the request isn't a preflight request.

This results in the whatever Servlet/JAX-RS resource that is bound to the requested URL being executed, which shouldn't happen for a preflight request. In the best case the Servlet/JAX-RS resource returns an HTTP 405 Method Not Allowed. In the worst case that endpoint has handling logic for an OPTIONS request, which is inadvertently executed, violating the CORS policy configured by the server, potentially leaving the server vulnerable.

**Comment by rkennedy-mode** [comment]
Nevermind, I think my understanding of CORS preflight requests may be incorrect.

**Comment by jhsenjaliya** [comment]
I got slightly confused by the responses here ( specially from @joakime , saying this is not according to the spec) if that is the case , is there a plan to fix this by handling preflight requests before checking that origin must not be null ?

**Comment by joakime** [comment]
> I got slightly confused by the responses here ( specially from @joakime , saying this is not according to the spec) if that is the case , is there a plan to fix this by handling preflight requests before checking that origin must not be null ?

Don't follow you.  Can you give some details on what you are looking for?

**Comment by jhsenjaliya** [comment]
sure, sorry to miss the context, so basically building on what @rkennedy-mode explained in this comment: https://github.com/eclipse/jetty.project/issues/7894#issuecomment-1103012784 

- preflight (OPTIONS) requests, fails on CORS, because CrossOriginFilter#handle checks origin present first before it tries to handle preflight request with `isPreflightRequest`. 

so I was wondering that If you agree that this is not as per the spec, hence the original question: " is there a plan to fix this by handling preflight requests before checking that origin must not be null ?"

**Comment by joakime** [comment]
So you have an `OPTIONS` (method) request, without an `Origin` header match (to what you have configured in the `CrossOriginFilter`)?

That's not a valid preflight request per the CORS spec.

 1. No Origin header is defined as outside of the spec (aka "not a CORS preflight request" state)
 2. No matching Origin header also puts the request into a "not a CORS preflight request" state.

Doesn't matter if that same request also has a `Access-Control-Request-Method` header (that header is ignored due the "not a CORS preflight request" state).

That's just a normal HTTP `OPTIONS` request, which the `Servlet` spec itself handles already.

* https://github.com/jakartaee/servlet/blob/5.0.0/api/src/main/java/jakarta/servlet/http/HttpServlet.java#L343-L435

If you have requirements beyond this, then that's an Application specific concern with the `OPTIONS` header that you receive.

**Comment by joakime** [comment]
If you get no (or blank) `Origin` header, that's not ever CORS preflight.

If you get a `Origin` header that doesn't match, then that's either a misconfigured `CrossOriginFilter` (you don't have that host in your `allowedOrigins`) or a misconfigured set of virtualhosts on your context (a common setup, where you only want specific hosts to even reach your context, all other hosts are 404).
