### ISSUE TITLE
Jetty runner SLF4J not found

### ISSUE THREAD

**Issue by sebastianguarin** [eclipse/jetty.project#7895]
**Jetty version(s)**
10.0.7
10.0.8
10.0.9

**Java version/vendor** 
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)

**Description**
Jetty runner does not find a SLF4J  provider by default, not sure if I'm missing something as there isnt too much documentation about jetty-runner nowadays.

**How to reproduce?**
```
java -jar jetty-runner-10.0.9.jar  SampleWebApp.war
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/



```

**Comment by joakime** [comment]
You can provide your own logging implementation.

The decision was made to not bundle the Jetty specific logging implementation, allowing users, like yourself, to pick a logging implementation from the slf4j choices (logback, log4j2, java.util.logging, jetty-logging, simple logging, anything supporting jakarta-commons-logging, etc)

This ability to configure the logging is the most often requested feature of jetty-runner, now you can do whatever you want to do with logging.
Past versions of jetty-runner (pre-Jetty 10) were hardcoded for Jetty's StdErrLog and Jetty's RolloverFileOutputStream. (neither of those 2 classes even exist in Jetty 10 now)

**Comment by sebastianguarin** [comment]
right, then a bit lost with `jetty-slf4j-impl`, isn't that one that acts as a default provider, which  behaves as the previous one StdErrLog.

Sorry, if I'm a bit off, just that not really a java developer, our project is in ruby and then transpiled to JAVA using JRuby. to then be compiled into a war file. 
so just wanted to be sure that is something related to the project and not Jetty-runner, as just calling 
```
java -jar jetty-runner-10.0.9.jar --version
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
```
returns the same output.

BTW: I tried setting some jetty-logging.properties with  SL4j  simple plus the file in the classpath, but didnt seem to work.
maybe I'm missing something.

**Comment by joakime** [comment]
If you want to use the jetty implementation ...

``` shell
$ java -cp /path/to/jetty-slf4j-impl-10.0.9.jar -jar jetty-runner-10.0.9.jar --version
```

Substitute any other sfl4j 2.x provider (a concrete logging implementation) using the same classpath techniques.

https://www.slf4j.org/manual.html#swapping

_Example (if you wanted to use log4j2)_

``` shell
$ java -cp /path/to/log4j-slf4j18-impl-2.17.2.jar:\
    /path/to/lib/logging/log4j-api-2.17.2.jar:\
    /path/to/lib/logging/log4j-core-2.17.2.jar \
    -jar jetty-runner-10.0.9.jar --version
```

**Comment by sebastianguarin** [comment]
thanks, 
then I will have to check my local, I get the same output.

```
$ java -cp /Users/sebastianguarin/Downloads/jetty-slf4j-impl-10.0.9.jar -jar jetty-runner-10.0.9.jar --version
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
org.eclipse.jetty.runner.Runner: 10.0.9
```

**Comment by sebastianguarin** [comment]
@joakime could you please confirm that adding the Jar to the classpath works for you, and you dont have any jetty installation in the machine?

I tried locally and remotely with one of our servers, but I'm still getting the same issue.

** Java version **
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)

** OS **
Linux Ubuntu 18.04.4 LTS
Mac BigSur 11.4

**Comment by olamy** [comment]
Please try this way 
```
java -cp jetty-slf4j-impl-10.0.9.jar:jetty-runner-10.0.9.jar org.eclipse.jetty.runner.Runner
```
or
```
java -cp slf4j-simple-2.0.0-alpha6.jar:jetty-runner-10.0.9.jar org.eclipse.jetty.runner.Runner
```
depending which slf4j implementation you want to use.
I tried 
```
java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

uname -a
Darwin olamy-mbp.modem 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
``` 

it's a interesting problem to figure out why the algorithm used by slf4j cannot find the implementation when mixing `-cp` and `-jar` options

**Comment by sebastianguarin** [comment]
Great!

it works for me as well. now I have to deal with some other external libraries for my project but now I have more info.

Thanks @olamy
