### ISSUE TITLE
Ability to limit the number of connections per proxy

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#7899]
**Target Jetty version(s)**
11.0.8

**Enhancement Description**
When using SOCKS proxies over ssh, the default value of `MaxSessions` is 10. `HttpClient` has `setMaxConnectionsPerDestination()` but I need to be able to limit the number of connections per proxy; otherwise, the proxy begins rejecting new connections.

I'm expecting the client to queue outgoing connections the same way it does in order to respect `setMaxConnectionsPerDestination()`.

I'm not familiar with any workarounds for this problem.

**Comment by cowwoc** [comment]
It turns out that the problem wasn't the number of outgoing connections but rather the destination hostname. If the remote hostname does not exist, the SSH server closes the connection without an explanation. But then if you run `tail -f /var/log/secure` you will see:

`sshd: error: connect_to <hostname>: unknown host (Name or service not known)`

I still think that supporting an overall limit would be useful but I no longer have a concrete use-case for it. It probably doesn't change much, but Apache HTTPClient has this feature:

```
public void executeWithPooledUsingHttpClientBuilder() throws Exception {
    try (CloseableHttpClient httpClient = HttpClients.custom()
                                                     .setMaxConnTotal(100)
                                                     .setMaxConnPerRoute(20)
                                                     .build()) {
        final HttpGet httpGet = new HttpGet(GET_URL);
        try (CloseableHttpResponse response = httpClient.execute(httpGet)) {
            EntityUtils.consumeQuietly(response.getEntity());
        }
    }
}
```

**Comment by sbordet** [comment]
@cowwoc I think this also can be done with tags, since a each proxy tag would create different destinations, so `maxConnectionsPerDestination` would be enforced. The destinations would have the same host/port, but different tags.

**Comment by cowwoc** [comment]
@sbordet That makes a lot of sense. Thank you!
