### ISSUE TITLE
Initial burst of requests processed slowly due to class loading

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse/jetty.project#7910]
Jetty Version - 9.4.43.v20210629
Java Version - 1.8.0_261

Jetty classloader loads all the jersey & model classes dynamically when the 1st request comes to Jetty server. 
Because of which initial burst of requests take time to get processed, hence some of them gets timed-out as well.

Is there any solution for this issue, such that the initial requests are not processed slowly at jetty server.

**Comment by joakime** [comment]
This is highly unlikely to be a simple classloading issue.

You could try configuring the jersey servlets to initialize on server startup within your webapp's descriptor.

Also, review your `WEB-INF/lib/*.jar` files ...

If you have any content with `META-INF/resources`, consider expanding them into your webapp before you package it up (bonus is you'll actually resolve conflicts that the servlet spec cannot resolve for you).  This action moves potentially hundreds of thousands of classloader entries out of the classloader and into the base resource layer.
