### ISSUE TITLE
Jetty-12 configuration / start 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7911]
**Target Jetty version(s)**
Jetty-12

**Enhancement Description**

With jetty 9/10/11, the start.jar mechanism configures the server by using the enabled modules and their ini files to create:
 + a set of properties
 + a classpath list of jars & directories
 + a list of XMLs to execute 

This can no longer be done as-is for jetty-12 because there will be modules that cannot cohabit the same classloader: eg jetty-ee9-servlet and jetty-ee10-servlet depend on different version of the servlet-api.

For the XMLs and properties, there is more scope for cohabitation because we can change the names.  For example the current `jetty-webapp.mod` uses the `jetty-webapp.xml` and the property `jetty.webapp.addSystemClasses` to setup a `ClassMatcher` instance stored as an attribute `org.eclipse.jetty.webapp.systemClasses` on the `Server` instance.     If the names are changed to:  `jetty-ee10-webapp.mod`, `jetty-ee10-webapp.xml`, `jetty.ee10.webapp.addSystemClasses` and `org.eclipse.ee10.jetty.webapp.systemClasses`, then this mechanism could work side by side with the same mechanism for `ee8` and `ee9`.         

However, naming all our properties, attributes etc, with ee8/ee9/ee10 will become a burden when ee11/ee12/ee13 arrive, some of which may have no significant changes to the servlet-api and thus should not require wholesale renaming of configuration on what may be a minor point upgrade for the servlet spec.

Thus I think it may be simpler to come up with a mechanism that recognises named environments and then allows a module to be scoped to an environment.    The properties, xmls, classpath of a module would be applied to the environment, thus whilst the file names would remain scoped, they could set the existing un-scoped names.   Thus `jetty-ee10-webapp.mod` would add the `jetty-ee10-webapp.jar` to the "ee10" environment and apply the `jetty-ee10-webapp.xml` to it, which would use the `jetty.webapp.addSystemClasses` property to set the `org.eclipse.jetty.webapp.systemClasses` attribute on the "ee10" environment.

The interface for the Environment would be something like:
```java
    interface Environment extends Attributes
    {
        String getName();     
        Server getServer();     
        ClassLoader getClassLoader();
    }
```

These would be obtained either as `Server` attributes, or better yet from a method `Server.getEnvironment(String name)` (or perhaps some abstract Environment factory implemented in `util.component` that Server extends.    Perhaps `Environment` should also be a `ContainerLifeCycle`?

The slight issue is that the existence and configuration of the Environments will be known to the start.jar environment, but must be communicated to the JVM instance, which may be separated via a --dry-run to a different JVM.   Thus the start.jar mechanism will need a way to codify the resulting env configuration (libs, properties & xmls) in string form so that can be communicated to the JVM and the env created there.

So this will need a bit of a generalisation of the start.jar code, so that instead of working on a single environment, it can generate configurations for N named environments.

**Comment by gregw** [comment]
modulo jpms complications

**Comment by janbartel** [comment]
@gregw is this done now that you've implemented the `environment` concept?
