### ISSUE TITLE
PathMappings.asPathSpec does not allow root ServletPathSpec

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#7918]
**Jetty version(s)**
all

**Description**

The ServletPathSpec of "" (empty string) is the root only match.  This is not allowed by `PathMappings.asPathSpec`, which can prevent code that does not explicitly use ServletPathSpec from matching root.

**Comment by gregw** [comment]
merged to 10,11 & 12.  Waiting for build for 9

**Comment by joakime** [comment]
Fully merged now.
