### ISSUE TITLE
[HTTP/2] Socket seems to be not closed completely

### ISSUE THREAD

**Issue by Drdoteam** [eclipse/jetty.project#792]
Hi.

Because of APNS's SSL certificate, I often stop and start HttpClient repeatedly.
I found that file descriptors are not decreased when HttpClient.stop method was called.
It seems to be not closed completely.

This is my test code.
```java
while (!Thread.interrupted()) {
	SslContextFactory sslContextFactory = new SslContextFactory();
	sslContextFactory.setKeyStore(keyStore);
	sslContextFactory.setKeyManagerPassword(password);
	sslContextFactory.setKeyStorePassword(password);

	HttpClient httpClient = new HttpClient(new HttpClientTransportOverHTTP2(new HTTP2Client()), sslContextFactory);
	httpClient.start();

	ContentResponse response = httpClient.POST("https://api.push.apple.com")
		.path("/3/device/invalid-token")
		.header("apns-topic", bundleId)
		.content(new StringContentProvider("{\\\"aps\\\":{\\\"alert\\\":\\\"This is a test message for apns.\\\"}}\"}"))
		.send();
	logger.info("status: " + response.getStatus() + ", response: " + response.getContentAsString());

	httpClient.stop();

	Thread.sleep(1000);
}
```
Start and stop HttpClient per one second.

Check open file descriptors, "can't identify protocol" is being increasing.
```
$ sudo /usr/sbin/lsof -p 27688 | grep "can't identify protocol"
jsvc    27688 irteam   44u  sock                0,6       0t0 29446949 can't identify protocol
jsvc    27688 irteam   45u  sock                0,6       0t0 29446955 can't identify protocol
jsvc    27688 irteam   46u  sock                0,6       0t0 29446957 can't identify protocol
jsvc    27688 irteam   47u  sock                0,6       0t0 29447158 can't identify protocol
jsvc    27688 irteam   48u  sock                0,6       0t0 29447209 can't identify protocol
jsvc    27688 irteam   49u  sock                0,6       0t0 29447211 can't identify protocol
jsvc    27688 irteam   50u  sock                0,6       0t0 29447218 can't identify protocol
jsvc    27688 irteam   51u  sock                0,6       0t0 29447220 can't identify protocol
jsvc    27688 irteam   52u  sock                0,6       0t0 29447228 can't identify protocol
jsvc    27688 irteam   53u  sock                0,6       0t0 29447231 can't identify protocol
```
```
$ sudo /usr/sbin/lsof -p 27688 | grep "can't identify protocol" | wc -l
37
$ sudo /usr/sbin/lsof -p 27688 | grep "can't identify protocol" | wc -l
40
$ sudo /usr/sbin/lsof -p 27688 | grep "can't identify protocol" | wc -l
102
```

I found this commit over debugging.
I think HTTP2Connection doesn't call super.close method and socket is not closed completely.

https://github.com/eclipse/jetty.project/commit/3c26ffb227089fc02b59c439c2000850b3399621
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java
```java
    @Override
    public void close()
    {
        // We don't call super from here, otherwise we close the
        // endPoint and we're not able to read or write anymore.
        session.close(ErrorCode.NO_ERROR.code, "close", Callback.NOOP);
    }
```

In my case, I extend HttpClientTransportOverHTTP2 and add closing connection code to close socket completely for a shift.
And Open file descriptors are decreased. 
```java
	@Override
	protected void doStop() throws Exception {
		super.doStop();
		for (org.eclipse.jetty.io.Connection connection : connections) {
			try {
				connection.close();
			} catch (Exception e) {
			}
		}
	}
```

**Comment by Drdoteam** [comment]
I would like to add Callback at HTTP2Connection.close method to close socket completely.
Why should we read or write after close ?

**Comment by joakime** [comment]
(overly simplified explanation...) 

With HTTP2 you have virtual connections (aka streams in HTTP2) and the real physical connection.

We have to be careful to only close the physical connection's endpoint when there are no streams still around, being careful to not allow the virtual connections to close the physical endpoint.

**Comment by Drdoteam** [comment]
Then, how to close the physical endpoint without extending HttpClientTransportOverHTTP2 ?
I would be love Jetty provides the way to close physical endpoint ... or close the physical endpoint when every communication is finished completely.

**Comment by sbordet** [comment]
Jetty's client does send a `GOAWAY` to the server, but the server does not respond to that, nor closes the connection like it should.

However, we should aggressively close after the idle timeout, but apparently we don't.

**Comment by sbordet** [comment]
@Drdoteam can you clarify what exactly do you mean by:

> Because of APNS's SSL certificate, I often stop and start HttpClient repeatedly

Why do you need to start and stop `HttpClient` ?

**Comment by Drdoteam** [comment]
@sbordet 
Many games and services use APNS for notification. 
They have different certificates. 
So, I use many SslContextFactories and HttpClients in one machine and stop them when there is no request during a few minutes.

**Comment by Drdoteam** [comment]
In APNS Guide...
```
Your provider server must support TLS 1.2 or higher when creating the connection to the APNs servers. In addition, the connection must be authenticated with your provider client certificate, which you obtain from Member Center, as described in Creating a Universal Push Notification Client SSL Certificate.
```
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW11

**Comment by sbordet** [comment]
The reason we don't trigger the idle timeout is because `HttpClient` is stopping, so the scheduler and the idle timeout mechanism is stopped as well.

I fixed this by ensuring that when a `Session` is stopped, it sends the `GOAWAY` and then closes the underlying `EndPoint`, thereby closing the underlying TCP connection.

**Comment by Drdoteam** [comment]
@sbordet Thank you!
