### ISSUE TITLE
Correct requestlog formatString commented default

### ISSUE THREAD

**Issue by prenagha** [eclipse/jetty.project#7929]
**Jetty version(s)**
10.0.9

**Java version/vendor** 
17 Coretto

**OS type/version**
Mac 12.3.1

**Description**
Align the commented default `jetty.requestlog.formatString` mentioned in the `requestlog.ini` with the default used in the code (`CustomRequestLog`).
Currently the comment refers to a `%B` that isn't used by the code nor is mentioned as being valid by the documentation.
Also adjust the `%a` parameter option to indicate which form the code uses.

**How to reproduce?**
Add the `requestlog` module to Jetty, observe the commented defaults in `requestlog.ini`

**Comment by prenagha** [comment]
PR in a moment

**Comment by gregw** [comment]
@lachlan-roberts needs to be merged to 12

**Comment by lachlan-roberts** [comment]
done with 24c0e9d4dd5bea62963e664441db7c7cfcba75f5
