### ISSUE TITLE
timeout of root session let context session time out

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#795]
I use embed jetty inside Equinox Osgi container.

I have bundle org.adempiere.server (called "root") deploy with ServerRoot = 1, Web-ContextPath: /, session-timeout = 2

I have other bundle Web-ContextPath: webui (called "sub"), session-timeout = 60

bellow is test case when session of root timeout let session of sub also timeout

1. open browse and go to localhost, so root create a session s1 and a cookie JSESSIONID=x

2. in same browse tab go to localhost/webui (just modify localhost to localhost/webui), so sub create a session s2, because already exists JSESSIONID, s1 and s2 have same id.

3. wait until s1 timeout (2 minute). s2 also timeout by have same id.

it's issue or not?

My work-around add bellow configuration to web.xml of root

`
	<context-param>
    	<param-name>org.eclipse.jetty.servlet.SessionCookie</param-name>
    	<param-value>ROOT_SESSIONID</param-value>
  	</context-param>
`

**Comment by janbartel** [comment]
@hieplq that's actually normal behaviour: as the sessions in context "sub" and "root" share the same sessionid, once one times out, the other must be timed out too.

Your workaround is fine if you don't want the same session id and lifecycle in both contexts.
