### ISSUE TITLE
EOL (End of Life) for Jetty 9 - January 2025

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7958]
It’s been 9 years since Jetty 9 was released and it is time to announce some changes regarding the end of community support for Eclipse Jetty 9.x.

June 1st, 2022 will mark the official _End of Community Support_ for Eclipse Jetty 9.x.

While users of Jetty 9.x will continue to see releases for security and critical issues until 9.x goes _End of Life_ (EOL), the only ongoing support provided will be for Webtide customers.

Official EOL is January 2025.

Action | Before June 1st, 2022 | End of Community Support (June 1st, 2022) | End of Life
--- | --- | --- | ---
Community PRs reviewed and integrated | :heavy_check_mark: | :x: | :x: 
Webtide Customer PRs reviewed and integrated | :heavy_check_mark: | :heavy_check_mark: | :x:
Community triggered releases | :heavy_check_mark: | :x: | :x:
Webtide Customer triggered releases | :heavy_check_mark: | :heavy_check_mark:  | :x:
Security / Vulnerability triggered releases | :heavy_check_mark: | :heavy_check_mark: | :x:

Thank you for your continued usage and support of Jetty, please take a moment to look at Jetty release 12.0.x.

Note: As of January 2024, both Jetty 10 and Jetty 11 are also at End of Service/Support Life

* #10485

Jetty Version | Minimum JDK Version | Jakarta EE | Servlet Version | Namespace
---- | ---- | ---- | ---- | ----
12.0.x - env:`ee8` | 17 | EE8 | 4 | `javax.servlet.*`
12.0.x - env:`ee9` | 17 | EE9 | 5 | `jakarta.servlet.*`
12.0.x - env:`ee10` | 17 | EE10 | 6 | `jakarta.servlet.*`

**Comment by jmcc0nn3ll** [comment]
Let's push it to June 1st, first of the month is always good for this sort of announcement and 10 days might panic someone.  No need to cause a heart attack.

**Comment by joakime** [comment]
I agree. Updating ...

**Comment by joakime** [comment]
We should send an email to the jetty mailing lists - https://www.eclipse.org/jetty/mailing_lists.php

* https://accounts.eclipse.org/mailing-list/jetty-users
* https://accounts.eclipse.org/mailing-list/jetty-dev
* https://accounts.eclipse.org/mailing-list/jetty-announce

And we should update the version table at https://www.eclipse.org/jetty/download.php

**Comment by jmcc0nn3ll** [comment]
Announcements sent, I'll update that table now.

**Comment by prenagha** [comment]
The title of the issue here implies the end of the 9 series entirely. But the issue details all talk about 9.4.x being ended. I assume we really mean that 9.4 is ending and there are no future versions of 9 planned (other than noted major bug fix). Might be worth calling that out explicitly. Or perhaps just refer to 9.x everywhere in this issue and communications.

**Comment by joakime** [comment]
All versions before 9.4.x are already End of Life / Deprecated.
See: https://www.eclipse.org/jetty/download.php#version-table

There will never be a 9.5.x, so the title saying 9.x is actually correct.
All of the 9 series is included in this announcement.

I updated the original text to only use "9.x" and no longer use "9.4.x"

**Comment by joakime** [comment]
Communication has been sent. Closing issue as completed.

**Comment by covertMartin** [comment]
Is this page now out of date? https://www.eclipse.org/jetty/download.php as it show 9.4 as stable?

**Comment by sbordet** [comment]
@covertMartin, the page is up-to-date. Jetty 9.4.x is stable and there is a "Notice" link.
The fact that Jetty 9.4.x is in end of community support does not mean it is not stable.

**Comment by joakime** [comment]
That status will likely change when 9.4.x goes to EOL status.

**Comment by mjs8002** [comment]
> It’s been 9 years since Jetty 9 was released and it is time to announce some changes regarding the end of community support for Eclipse Jetty 9.x.
> 
> June 1st, 2022 will mark the official _End of Community Support_ for Eclipse Jetty 9.x.
> 
> While users of Jetty 9.x will continue to see releases for security and critical issues until 9.x goes _End of Life_ (EOL), the only ongoing support provided will be for Webtide customers.
> 
> As for the official EOL of Jetty 9.x, we will give at least 6 months notice after the last Webtide customer has transitioned off of using 9.x. We can’t provide a firm date, but it is unlikely to happen before 2025.
> 
> Thank you for your continued usage and support of Jetty, please take a moment to look at newer Jetty releases 10.0.x and 11.0.x _(Jetty 12.0.x due later this year)_
> 
> Action	Before June 1st, 2022	End of Community Support (June 1st, 2022)	End of Life (Date TBD)
> Community PRs reviewed and integrated	✔️	❌	❌
> Webtide Customer PRs reviewed and integrated	✔️	✔️	❌
> Community triggered releases	✔️	❌	❌
> Webtide Customer triggered releases	✔️	✔️	❌
> Security / Vulnerability triggered releases	✔️	✔️	❌

What does Webtide customer mean in this sentence, all users?

**Comment by sbordet** [comment]
> What does Webtide customer mean in this sentence, all users?

"Webtide customer" means an entity that has a business support contract with [Webtide Inc.](https://webtide.com)

"Community" means users of Jetty that do not have a business support contract with Webtide Inc.

**Comment by travellertinku** [comment]
> All versions before 9.4.x are already End of Life / Deprecated. See: https://www.eclipse.org/jetty/download.php#version-table
> 
> There will never be a 9.5.x, so the title saying 9.x is actually correct. All of the 9 series is included in this announcement.
> 
> I updated the original text to only use "9.x" and no longer use "9.4.x"

hi,

I understand that community EoS is reached for Jetty 9.4.x (EOL TBD). Can you please share how are we going to get security fixes going further?

regards,
Praveen

**Comment by joakime** [comment]
@praveenyadavP that is addressed in the table in the original comment.

**Comment by travellertinku** [comment]
Thanks @joakime.
Could you please confirm below as well?
Jetty 10.0.x compatible with OpenJava11?
Jetty 10.0.x compatible with OpenJava17?
Jetty 11.0.x compatible with OpenJava11?
Jetty 11.0.x compatible with OpenJava17?

**Comment by joakime** [comment]
There's no such thing as "OpenJava".

The minimum JVM versions are listed at https://www.eclipse.org/jetty/download.php#version-table
We build/test with Temurin JDK (which is based on the OpenJDK), all TLS versions from the minimum JVM to newest.
As well as the most recent non-TLS / Early Access JDKs (currently [JDK 19](https://jdk.java.net/19/))

We have other projects using Jetty with JVMs from Azul Zulu, RedHat, Amazon Corretto, and more on multiple architectures.

**Comment by mma5997** [comment]
Hello @joakime, any specific tentative timelines for 9.X EOL ?
Thanks!

**Comment by joakime** [comment]
> Hello @joakime, any specific tentative timelines for 9.X EOL ?
> Thanks!

From the announcement text at the top of this issue ...

_"As for the official EOL of Jetty 9.x, we will give at least 6 months notice after the last [Webtide](https://webtide.com/) customer has transitioned off of using 9.x. We can’t provide a firm date, but it is unlikely to happen before 2025."_

**Comment by 4devwithgit** [comment]
is there extended support on jetty 9.4.x? Like any paid support?
Thanks

**Comment by jmcc0nn3ll** [comment]
yes, through webtide.com or just send an email to sales@webtide.com and we can set up a chat to discuss

**Comment by sophallee** [comment]
How does End of Community Support differ from End of Life?

**Comment by jmcc0nn3ll** [comment]
Detailed in the original issue text and table.
