### ISSUE TITLE
Setting Traffic Class in HTTP Server underling Socket 

### ISSUE THREAD

**Issue by maucimino** [eclipse/jetty.project#7984]
Jetty 11.0.8

JDK 16

I'd like to set the traffic class in my Jetty HTTP server responses in the underling socket. I have seen that Java offers the `setTrafficClass` method in the `Socket` class.

I was not able to understand how I can reach this method through my Jetty HTTP server. I'm instantiating a server as following:

```
import jakarta.servlet.http.HttpServlet;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletHanlder;
import org.eclipse.jetty.servlet.ServletHolder;

Server server;
MyServlet servlet; // extending the jakarta.servlet.http.HttpServlet abstract class

server = new Server();
((ServletHandler) server.getHandler()).addServletWithMapping(new ServletHolder(servlet), "/myPath");
server.start();
```

It's very basic, but I need to set the traffic class (or the TOS) in the underling socket. Can you help me to understand how to configure it?

Thank you.

**Comment by sbordet** [comment]
May I ask why you need to set this configuration? As it is just a hint, and most of the times is ignored.

**Comment by maucimino** [comment]
Unluckily it's for requirements, you know.. :D

**Comment by sbordet** [comment]
This will set the traffic class in every connection opened by the given `ServerConnector`.

You have to setup this code at `Server` configuration/startup, as you cannot do it from a `Servlet`.

```java
ServerConnector connector = ...;

Connection.Listener listener = new Connection.Listener()
{
    @Override
    public void onOpened(Connection connection)
    {
        Object t = connection.getEndPoint().getTransport();
        if (t instanceof SocketChannel c) {
            c.setOption(SocketOptions.IP_TOS, trafficClass);
        }
    }
};

connector.addBean(listener);
```

**Comment by joakime** [comment]
Before you do this, be aware that IP_TOS is broken and not well supported on the open internet.

My advice is to not even waste your time on this, as no features associated with IP_TOS works today.  If you were investigating this back in 1998, with Java 1.2 you might have a shot at making it work, but today?  Your chances are incredibly slim, and it would never work on the open internet.  It would only work with old JVMs and web clients in a highly controlled private environment.

Java 8 thru Java 19 (so far) has an API for it, but it's highly environment specific, and has practically has no functional support for it in any environment today.

Searching through github for Java usage of IP_TOS, you'll see 98% of the hits are variations of the Java JVM itself (OpenJDK, Corretto, Adoptium, etc).
Of the remaining hits, you'll find Netty, which has specifically disabled the ability to use IP_TOS as it's broken in Java.

See http://mail.openjdk.java.net/pipermail/nio-dev/2018-August/005365.html

[JEP 353](https://openjdk.java.net/jeps/353) attempted to fix this for Java 13, but basically just made IP_TOS worse (it only works on a narrow range of old/deprecated Linux kernels, and does not work on MACOS, Windows, any mobile device, etc)

Windows 10 also has disabled support for IP_TOS in it's own networking stack.

Also, be aware that setting TOS on Responses only is not something Java has ever supported.
Java will set TOS on the entire Socket, both impacting both directions.

Features like QUICK ACK are not something that is set on a specific socket level by code anymore, those kinds of features are now system wide configurations for the entire networking stack, impacting all sockets.

The old Issue #139 is about Jetty Client, not Jetty Server.

That being said, you can do this with Jetty Server as well, using similar techniques.

Both Client and Server will require custom code that overrides the normal behavior to accomplish this.

For Server, you'll need a custom `ServerConnector`, start with extending from `ServerConnector` and implementing the `configure(Socket socket)` method.

For Client, you'll need a custom `HttpClientTransport` for the type of communication you are doing (eg: HTTP/1, HTTP/2, HTTP/3, FCGI, etc).
For HTTP/1 you'll extend from `HttpClientTransportOverHTTP` and override the `configure(HttpClient client, SocketChannel channel)` method and do what you need.

**Comment by maucimino** [comment]
> Before you do this, be aware that IP_TOS is broken and not well supported on the open internet.
> 
> My advice is to not even waste your time on this, as no features associated with IP_TOS works today. If you were investigating this back in 1998, with Java 1.2 you might have a shot at making it work, but today? Your changes are incredibly slim, and it would never work on the open internet. It would only work with old JVMs and web clients in a highly controlled private environment.
> 
> Java 8 thru Java 19 (so far) has an API for it, but it's highly environment specific, and has practically has no functional support for it in any environment today.
> 
> Searching through github for Java usage of IP_TOS, you'll see 98% of the hits are variations of the Java JVM itself (OpenJDK, Corretto, Adoptium, etc). Of the remaining hits, you'll find Netty, which has specifically disabled the ability to use IP_TOS as it's broken in Java.
> 
> See http://mail.openjdk.java.net/pipermail/nio-dev/2018-August/005365.html
> 
> [JEP 353](https://openjdk.java.net/jeps/353) attempted to fix this for Java 13, but basically just made IP_TOS worse (it only works on a narrow range of old/deprecated Linux kernels, and does not work on MACOS, Windows, any mobile device, etc)
> 
> Windows 10 also has disabled support for IP_TOS in it's own networking stack.
> 
> Also, be aware that setting TOS on Responses only is not something Java has ever supported. Java will set TOS on the entire Socket, both impacting both directions.
> 
> Features like QUICK ACK are not something that is set on a specific socket level by code anymore, those kinds of features are now system wide configurations for the entire networking stack, impacting all sockets.
> 
> The old Issue #139 is about Jetty Client, not Jetty Server.
> 
> That being said, you can do this with Jetty Server as well, using similar techniques.
> 
> Both Client and Server will require custom code that overrides the normal behavior to accomplish this.
> 
> For Server, you'll need a custom `ServerConnector`, start with extending from `ServerConnector` and implementing the `configure(Socket socket)` method.
> 
> For Client, you'll need a custom `HttpClientTransport` for the type of communication you are doing (eg: HTTP/1, HTTP/2, HTTP/3, FCGI, etc). For HTTP/1 you'll extend from `HttpClientTransportOverHTTP` and override the `configure(HttpClient client, SocketChannel channel)` method and do what you need.

Thanks for the explanation! As I said, I'm using Jetty 11.0.8 but I'm not able to find the `configure` method when extending the `ServerConnector` class. Also in the Jetty javadoc I'm not able to find any reference about the `configure(Socket socket)` method.

**Comment by joakime** [comment]
> Thanks for the explanation! As I said, I'm using Jetty 11.0.8 but I'm not able to find the `configure` method when extending the `ServerConnector` class. Also in the Jetty javadoc I'm not able to find any reference about the `configure(Socket socket)` method.

Ah, yes. `ServerConnector.configure(Socket)` was removed in PR #7100 when HTTP/3 QUIC was introduced. (When using HTTP/3 QUIC there's no Socket)

**Comment by maucimino** [comment]
> > Thanks for the explanation! As I said, I'm using Jetty 11.0.8 but I'm not able to find the `configure` method when extending the `ServerConnector` class. Also in the Jetty javadoc I'm not able to find any reference about the `configure(Socket socket)` method.
> 
> Ah, yes. `ServerConnector.configure(Socket)` was removed in PR #7100 when HTTP/3 QUIC was introduced. (When using HTTP/3 QUIC there's no Socket)

So there's no other way? Because I tried with the following suggestion:

> This will set the traffic class in every connection opened by the given `ServerConnector`.
> 
> You have to setup this code at `Server` configuration/startup, as you cannot do it from a `Servlet`.
> 
> ```java
> ServerConnector connector = ...;
> 
> Connection.Listener listener = new Connection.Listener()
> {
>     @Override
>     public void onOpened(Connection connection)
>     {
>         Object t = connection.getEndPoint().getTransport();
>         if (t instanceof SocketChannel c) {
>             c.setOption(SocketOptions.IP_TOS, trafficClass);
>         }
>     }
> };
> 
> connector.addBean(listener);
> ```

But I get the exception `IP_TOS not supported` when using the `setOption` method.

**Comment by sbordet** [comment]
> But I get the exception IP_TOS not supported when using the setOption method.

That's what we tried to tell you. You want to set a socket option that is at best ignored, but in reality is not even supported.

And before you ask, this is the JDK implementation of `Socket.setTrafficClass()`: https://github.com/openjdk/jdk/blob/jdk-18-ga/src/java.base/share/classes/java/net/Socket.java#L1456.

Just don't set it.

**Comment by maucimino** [comment]
> > But I get the exception IP_TOS not supported when using the setOption method.
> 
> That's what we tried to tell you. You want to set a socket option that is at best ignored, but in reality is not even supported.
> 
> And before you ask, this is the JDK implementation of `Socket.setTrafficClass()`: https://github.com/openjdk/jdk/blob/jdk-18-ga/src/java.base/share/classes/java/net/Socket.java#L1456.
> 
> Just don't set it.

I see, but my Jetty server is not working in open internet, otherwise I might understand and move on as you suggested.
I'm working in a private enterprise network where the TOS is very important, that's why it seems strange there's not a way to set it properly.

**Comment by joakime** [comment]
If you got a ChannelException attempting to use `setOption(IP_TOS, val)` then you have 2 potential causes.

1. The OS/platform just doesn't support IP_TOS at all (the most common scenario)
2. The OS/platform doesn't support the specific value you have given (on Linux, for example, you need special admin/root level permissions for certain value ranges).

Neither of which can be fixed by Jetty or Java.

**Comment by joakime** [comment]
There's also rules on IP_TOS on some OS/Platforms.

For example, you cannot set IP_TOS on connected sockets on many OS/Platforms that even support IP_TOS, meaning only the client side can set IP_TOS, and it has to set it before the connection is attempted.  These kind of OS/Platform environments makes server side IP_TOS configuration impossible to achieve.

**Comment by maucimino** [comment]
> If you got a ChannelException attempting to use `setOption(IP_TOS, val)` then you have 2 potential causes.
> 
> 1. The OS/platform just doesn't support IP_TOS at all (the most common scenario)
> 2. The OS/platform doesn't support the specific value you have given (on Linux, for example, you need special admin/root level permissions for certain value ranges).
> 
> Neither of which can be fixed by Jetty or Java.

Okay, so this is the only way right now to set the IP_TOS bits in Jetty?

**Comment by sbordet** [comment]
> Okay, so this is the only way right now to set the IP_TOS bits in Jetty?

You are not setting IP_TOS in Jetty. You are setting it on the JDK classes.
We gave you a way to access the JDK classes from Jetty, but turns out your OS/platform does not support setting IP_TOS.

**Comment by maucimino** [comment]
> > Okay, so this is the only way right now to set the IP_TOS bits in Jetty?
> 
> You are not setting IP_TOS in Jetty. You are setting it on the JDK classes. We gave you a way to access the JDK classes from Jetty, but turns out your OS/platform does not support setting IP_TOS.

Okay crystal clear, thank you!
