### ISSUE TITLE
Show session attribute key name when error serializing

### ISSUE THREAD

**Issue by prenagha** [eclipse/jetty.project#7986]
**Target Jetty version(s)**
10, 11

**Enhancement Description**
I am migrating an existing Websphere application to Jetty and running into issues serializing data to the session. Mostly because we (sadly) don't have only proper `Serializable` data in our session. `SessionData` class has a bit of debug logging, and throws an exception but for me it would be more helpful if the exception wrapped in another exception that showed the key name of the attribute that failed.

Something like the below.

If the Jetty team thinks that would be useful I will work up a proper PR for review.
Wanted to gauge interest before I spend time on it however.
**Please let me know**

```java
public class SessionData implements Serializable
{
...
    public static void serializeAttributes(SessionData data, java.io.ObjectOutputStream out)
        throws IOException
    {
        int entries = data._attributes.size();
        out.writeObject(entries);
        for (Entry<String, Object> entry : data._attributes.entrySet())
        {
+           String key = entry.getKey();
+           try {
              out.writeUTF(key);
...
              out.writeObject(entry.getValue());
+           } catch (Throwable t) {
+             throw new IllegalArgumentException("Unable to serialize session attribute " + key, t);
+           }
```

**Comment by joakime** [comment]
We have to be careful to not leak back user provided content to the http response here. (that becomes a security issue)

**Comment by janbartel** [comment]
It would be better to debug log it.

**Comment by prenagha** [comment]
@joakime do people use user provided content as a session attribute key?

@janbartel issue here is we don't normally leave debugging on, and it can be tricky to figure out which session attribute caused the problem after the fact as we have lots of different pages writing data. So if we don't know which attribute caused the problem then figuring out how to resolve is extremely difficult - we almost have to turn on debugging and wait for the issue to happen again.

**Comment by joakime** [comment]
> @joakime do people use user provided content as a session attribute key?

Not super common, but it has been done.

**Comment by prenagha** [comment]
That is unfortunate @joakime , but the code already logs that same field, which also shouldn't ever be done for user provided content. So perhaps this is no worse than what is already in place.

Anyway you all let me know if I should pursue this. If not I will just override locally somehow to catch it.

**Comment by joakime** [comment]
Logging only is fine, but reporting it back to the user on an HTTP Response is where the security problem starts.

**Comment by prenagha** [comment]
I'll just override locally then

**Comment by prenagha** [comment]
If anyone else ends up here in the future wanting same... I added a try catch around the Jetty `SessionData` serialize static method, then rerun the below to give me a more detailed error message I then put in a wrapped regrown exception

```java
  private String serializationErrorMessage(SessionData data) {
    String key = null;
    String valueType = null;
    try (ObjectOutputStream oos = new ObjectOutputStream(OutputStream.nullOutputStream())) {
      for (Map.Entry<String, Object> entry : data.getAllAttributes().entrySet()) {
        key = entry.getKey();
        Object value = entry.getValue();
        if (value == null)
          continue;
        valueType = value.getClass().getSimpleName();
        oos.writeObject(entry.getValue());
      }
    } catch (Throwable t) {
      return "Unable to serialize session attribute " + key + " " + valueType;
    }
    return "Unable to serialize session";
  }
```
