### ISSUE TITLE
JettyWebSocketFrameHandlerFactory.createAnnotatedMetadata(...) does not provide handle methods for Ping and Pong

### ISSUE THREAD

**Issue by MobAbi** [eclipse/jetty.project#7992]
Jetty Version 10.0.9

Java 11

I upgraded from Jetty 9 to 10 and noticed that the Ping/Pong does not work anymore as before.
If I debugged that correctly, then it is because in websocket-jetty-common-10.0.9.jar
the jettyWebSocketFrameHandlerFactory.createAnnotatedMetadata() method does not supply metadata
for the handleMethods for Ping and Pong.

Is this a bug or a feature?

**Comment by lachlan-roberts** [comment]
Can you show us what WebSocket endpoint you had when using `9.4` that does not work in `10.0.9`.

That `createAnnotatedMetadata()` method is for finding the methods on the endpoint annotated with Jetty WebSocket API annotations, and this did not have any ping/pong specific annotations even in `9.4`. You either use the `OnWebSocketFrame` annotation or `WebSocketFrameListener` or `WebSocketPingPongListener` to handle ping/pong.

**Comment by MobAbi** [comment]
Thank you for your reply.As soon as I find the time I will check what you wrote and might come back to this Issue.

**Comment by MobAbi** [comment]
I think I found the reason - it's not Jetty itself, but Spring: 

![Jetty10WebSocketHandlerAdapter_no_onWebSocketFrame](https://user-images.githubusercontent.com/93993912/171872552-78d5fa4e-7032-4804-a7cc-35b5e8123e63.png)

If someone knows how to workaround this, that would be great to know.

**Comment by lachlan-roberts** [comment]
@MobAbi probably best to open an issue asking about this on the spring project.

But it looks like they have addressed this in their `main` branch as part of the work for https://github.com/spring-projects/spring-framework/issues/27424.
See that [JettyWebSocketHandlerAdapter](https://github.com/spring-projects/spring-framework/blob/main/spring-websocket/src/main/java/org/springframework/web/socket/adapter/jetty/JettyWebSocketHandlerAdapter.java) is now using the jetty 10 version of `Frame` at `org.eclipse.jetty.websocket.api.Frame`.

**Comment by MobAbi** [comment]
Thx for your reply.
I'm not so deep into the versions of Spring vs Jetty, but am I right when I say that as soon there is a Spring version that supports Jakarta and uses Jetty 11, then I can migrate to that and the Frame (Ping/Pong) support should be fine. 
Is this correct?

**Comment by lachlan-roberts** [comment]
I don't know much about the available Spring versions either.

Open an issue on their repository if this is still not working because there is nothing we can do to fix it here.
