### ISSUE TITLE
Can we test the deployment of P2 with the new tycho version + signature?

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#8021]
**Jetty version**
10.x , 11.x

**Java version**

don't matter :-)

**Question**

I'd like to ask if it would be possible to once again spin a special "snapshot deploy" to test the new tycho-version before the next release (is there a schedule?) to make sure the following work:

- no additional items included
- PGP signatures are setup

Would be great if that's possible to catch any issues early :+1:

**Comment by olamy** [comment]
they usually run daily if source code change
https://jenkins.webtide.net/job/nightlies/job/jetty-10.0.x-snapshots-deploy/
https://jenkins.webtide.net/job/nightlies/job/jetty-11.0.x-snapshots-deploy/

so you can see date/time of last run

**Comment by laeubi** [comment]
@olamy the "problem" is that the daily run do not PGP sign the artifact, at least last time there must be some "magic" enabled for that (I can't find the issue right now).

**Comment by olamy** [comment]
> @olamy the "problem" is that the daily run do not PGP sign the artifact, at least last time there must be some "magic" enabled for that (I can't find the issue right now).

oh ok. I guess the magic last time was my fingers 🤣
I will do it

**Comment by olamy** [comment]
@laeubi both branches deployed with my sig 
enjoy!

**Comment by laeubi** [comment]
Great, the signatures are there, but I notice that when looking at the `artifacts.xml` here

https://oss.sonatype.org/content/repositories/jetty-snapshots/org/eclipse/jetty/jetty-p2/10.0.10-SNAPSHOT/jetty-p2-10.0.10-20220519.075904-31-p2site.zip

it seems missing a lot of the jetty bundles missing, also for older builds this is the case, currently the repo references the

https://github.com/eclipse/jetty.project/blob/546c382255f69cbc3b467e6ae87a8d9ccb8bd036/jetty-p2/pom.xml#L44-L49

and includes all reactor projects but it seems not to be enough, I see two possible causes:

1. the bom is not enough to make the p2- to be build as a last step
2. not the full set of projects are build

any idea?

**Comment by olamy** [comment]
Oh I think I know. I used -T3 so because of this it looks the p2 is build before some other modules and not at the end because they are not declared in p2 pom.
I will redeploy tomorrow and try to fix that

**Comment by laeubi** [comment]
Good to find that early now :-) Maybe you have a better idea to let the p2 depend on "everything else" instead of referencing the bom or literally every single module?

**Comment by laeubi** [comment]
Maybe `<scope>import</scope>` would be required here?

**Comment by olamy** [comment]
@laeubi I have redeployed both branches without using -T option so it should ok.
but try this `mvn clean install  -DskipTests -pl :jetty-p2 -am` and there is a problem
`<scope>import</scope>` is not possible for a `<dependency>` outside of `<dependencyManagement>`
but looking at it.

**Comment by olamy** [comment]
the easy solution is to make it depending on jetty-home :)

**Comment by laeubi** [comment]
thanks this looks much better now!

I think I'll try to enhance this with a LifeCyleListener that adds all reactor projects as a dependency but this still won't work well with `-pl`  /  `-am` and will most probably only be for Tycho 3.0 so if we can found a nice maven trick it would be cool.

If nothing helps, adding all jetty modules would be possible, I just fear if adding new ones might be forgotten to add it here.

**Comment by olamy** [comment]
`jetty-home` already depends on everything :)

**Comment by laeubi** [comment]
Good to know! If you could adjust this then I think we should be "safe" for the next release many thanks!

**Comment by joakime** [comment]
`jetty-home` doesn't depend on everything, take `jetty-osgi` for example.

**Comment by olamy** [comment]
@joakime good catch! 
`mvn clean install -pl :jetty-p2 -am -DskipTests` doesn't show `jetty-osgi`
we only need to include all the `jetty-osgi-*`

**Comment by olamy** [comment]
see https://github.com/eclipse/jetty.project/pull/8034
