### ISSUE TITLE
setting default Url Encoding broken in Jetty >= 9.3

### ISSUE THREAD

**Issue by 7obywankenobi** [eclipse/jetty.project#804]
Jetty provides the feature to configure the encoding of URL parameters by providing the system property "org.eclipse.jetty.util.UrlEncoding.charset". This feature got introduced as JETTY-1153 in jetty 7.x see http://osdir.com/ml/java-jetty-general/2011-07/msg00021.html

In Jetty 9.2.x this feature works as follows: `org.eclipse.jetty/server/Request.getParameter()` calls `extractParameters()` followed by `extractQueryParameters()`which in turn calls `org.eclipse.jetty.http.HttpURI.decodeQueryTo()`.

    public void decodeQueryTo(MultiMap<String> parameters) {
        if (_query==_fragment)
            return;
        if (_charset.equals(StandardCharsets.UTF_8))
            UrlEncoded.decodeUtf8To(_raw,_query+1,_fragment-_query-1,parameters);
        else
            UrlEncoded.decodeTo(new String(_raw,_query+1,_fragment-_query-1,_charset),parameters,_charset,-1);
    }

The else branch is called if _charset is different vom UTF-8. The HttpUri() Constructor sets ` _charset = URIUtil.__CHARSET;` The latter one has a static initializer which derives the charset from `System.getProperty("org.eclipse.jetty.util.URI.charset");` Given that and inspecting the static initializer for `UrlEncoded.java` reveals that `System.getProperty("org.eclipse.jetty.util.UrlEncoding.charset");` is used to set a default decoding for `UrlEncoded.decodeTo().

see
https://github.com/eclipse/jetty.project/blob/jetty-9.2.x/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
https://github.com/eclipse/jetty.project/blob/jetty-9.2.x/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
https://github.com/eclipse/jetty.project/blob/jetty-9.2.x/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
https://github.com/eclipse/jetty.project/blob/jetty-9.2.x/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java

However in jetty >= 9.3.x (including first Milestone builds) this feature is broken due to a refactoring. `HttpURI.decodeQueryTo` will always default to UTF-8:

    public void decodeQueryTo(MultiMap<String> parameters)
    {
        if (_query==_fragment)
            return;
        UrlEncoded.decodeUtf8To(_query,parameters);
    }

Unless you provide a specific encoding `HttpURI.decodeQueryTo(parameters, encoding)` URL parameters will always default to UTF-8. That's actually my current walkaround: Install a servlet filter which `request.setAttribute("org.eclipse.jetty.server.Request.queryEncoding", "ISO-8859-1");` Doing so triggers `decodeQueryTo(parameters, encoding)` during Request processing in `Request.java`.

I suggest either deprecating setting the system property `"org.eclipse.jetty.util.UrlEncoding.charset"` or fixing this issue. See:
https://wiki.eclipse.org/Jetty/Howto/International_Characters#International_characters_in_URLs
https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java

**Comment by gregw** [comment]
@7obywankenobi awesomely well researched bug report!    This mechanism has been removed and lives on only in old documentation.    I will remove that old documentation.    Did you see it any where else other than URIUtil javadoc?

**Comment by joakime** [comment]
Wouldn't the HTTP/2 requirement that all content in the request line, pseudo entries, and header all be UTF-8 make this difficult to support in a generic way?

Also note, the updated RFCs for URI mention that only the path + query sections can be non-UTF-8 encoded (with no distinction if this is applicable for http or non-http URIs) .   Also says that the existence of a host in a URI (for example) must be UTF-8 encoded.

Lots of ... uh ... "interesting" behavior in the updated specs :)

**Comment by 7obywankenobi** [comment]
> Did you see it any where else other than URIUtil javadoc?

I didn't really research other documentation. It's just that my code broke migrating from jetty 9.2.x to 9.3.x and I tried to understand why and look for walkarounds.

> the updated RFCs for URI mention that only the path + query sections can be non-UTF-8 encoded 

Most likely because the host / domain part of the URI has a different encoding:
https://en.wikipedia.org/wiki/Internationalized_domain_name#Internationalizing_Domain_Names_in_Applications

I think it's a good idea to drop the support for a other than UTF-8 default encoding. The jetty codebase 9.3.x is stable and nobody else seems to have hit on this problem during the one year that jetty 9.3 has been around. Therefore this codepath is basically untestet (no unit test) and should be discarded anyway. There's still sufficient remaining complexity in supporting HTTP/2 and the cleaner the codebase, the better.

It just gives me a bad feeling about how long my current applied workaround (enforcing ISO-8859-1 on a request basis) will work. Maybe it'll break soon as well. For the given applications I don't need HTTP/2 support at the moment (and even if I did could manage this on a different layer e.g. apache). I'm asking myself whether it's smarter to stick with jetty 9.2.x for these use cases.

Actually all I was looking for was a constant flow of security fixes without running into:
https://webtide.com/jetty-7-and-jetty-8-end-of-life/
Are there any plans on when jetty 9.2 will hit it's EOL?

**Comment by gregw** [comment]
Jetty-9.2 uses java7 which is already EOL, so it will be too at some stage.  Currently we are still doing security fixes and updates and they will continue for a while, but not forever.

The ability to set the encoding on the request will definitely remain in all 9.x releases.  So you should be good to upgrade to 9.3 and then 9.4 and you will have something maintained for many years to come.

If we were to drop it, it would only be in 10.x

**Comment by nevafuse** [comment]
Can this issue be re-opened?  @gregw's a1885af commit did not fix the issue.

**Comment by joakime** [comment]
@nevafuse the commit a1885afff8745fd4b7131616bb0a6dd55426125d was not a fix, it merely removed the invalid javadoc to the system property approach `org.eclipse.jetty.util.UrlEncoding.charset` that was removed in Jetty 9.3+

The bug report was about that invalid javadoc.

The OP also reported a Filter + Request Attribute workaround if you really want to break your HTTP spec adherence.

**Comment by faradice** [comment]
You are probably reading directly raw http encoding and you need to decode it to utf-8 using Decoder.
use java.net.URLDecoder line = URLDecoder.decode(line, "UTF-8");

For encoding text to html charset, use URLEncoder, like when posting java String directly using URL connection: line = URLEncoder.encode(line, "UTF-8");
