### ISSUE TITLE
Support Http Response 103 (Early Hints)

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8057]
**Target Jetty version(s)**
10+

**Enhancement Description**

What would it take to have Jetty support response code 103 (Early Hints)?

* https://datatracker.ietf.org/doc/html/rfc8297
* https://www.fastly.com/blog/beyond-server-push-experimenting-with-the-103-early-hints-status-code
* https://developers.cloudflare.com/cache/about/early-hints/

**Comment by sbordet** [comment]
I wonder how a `103` is any different from a HTTP/2 `PUSH_PROMISE`, which would carry exactly the same information.

The only difference I can see is that `PUSH_PROMISE` may send the response content before the client has a chance to cancel it, but typically bandwidth is not a problem.

Server push has been removed from HTTP/3, and a `103` may possibly break clients that are unaware of it.

Furthermore, there is no API on the server to send a `103`, which is similar to `100 Continue` as in the server sends 2 (or more) responses for one request (yes you can have multiple `103` followed by a `200`).
We send the `100` implicitly when the application calls `getInputStream()`, but in the Servlet realm there is no API.

We need to consider whether to add a "send informational response" API in Jetty 12.

**Comment by gregw** [comment]
I think a 103 is very similar to our current support of 102 PROCESSING.   We currently allow a `sendError(102)` to be done that sends a partial response, but without any of the current header fields from the response.   I think all that is needed is that we duplicate the 102 handling, but use a temporary `MetaData.Response` to contain the headers as they currently are.

However, I'm unsure if 102 or 103 are handled completely by http>=2

We also need to consider if we want optional or mandatory Expect headers.

**Comment by joakime** [comment]
Chrome 95 was the first version to support 103 Early Hints.

https://chromium.googlesource.com/chromium/src/+/master/docs/early-hints.md

Fastly opened support in Nov 2020.

Cloudfare opened support in Sep 2021

**Comment by gregw** [comment]
I've opened a branch for this and started by adding a better test for 100 and 102 responses.  These work for all protocols.   
I'll implement 103 support later today.

**Comment by gregw** [comment]
@joakime can you pass this on to the user
