### ISSUE TITLE
Jetty HttpClient authentication - missing any realm option

### ISSUE THREAD

**Issue by svilenvul** [eclipse/jetty.project#806]
In the BasicAuthentication class it is missing an option to set credentials for any realm like in the old [Apache HttpClient API ](https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/auth/AuthScope.html#ANY).

I will post a discussion from the Jetty users mailing list:

Me:
>Hello everybody,

>I am trying to migrate from Apache HttpClient 3.x to Jetty HttpClient 9.2.12, but I am facing problems, how to make a simple basic authentication.
 
>I have no specific realm to match.
In the BasicAuthentication constuctor  - BasicAuthentication(URI uri, String realm, String user, String password), I have passed a null as second parameter, but I noticed that passing null as a realm results in an NPE during the request.  

>I am searching for something as any realm value. What value should I use?
Unfortunately I could not find any info in the Jetty HttpClient documentation for this case.

Simone Bordet:
>Have you tried the empty string ?

>Is the server sending the challenge with a realm at all ?

>Can you detail the server response headers ?

Me:

>I have set up a local Proxy Server and made a few tests:
- I have tried with the empty String - I received 407 Unauthorized as response;
- I have tried with a valid realm value ("CCProxy Authorization"), I receive 200 OK as response;
- null value for realm ends with NPE;
- the server is sending the challenge with a realm;
- Response headers :
     Server: Proxy
     Proxy-Authenticate: Basic realm="CCProxy Authorization"
     Cache-Control: no-cache
     Connection: close
     Proxy-Connection: Close
     Content-Length: 265

>The question remains still the same - is there any option like in the Apache HttpClient API to set credentials for any realm ? 

Simone Bordet:
>Not currently, please file an issue.

>As a workaround, you can override BasicAuthentication.matches(...)
with your own logic

**Comment by sbordet** [comment]
You can now do `new BasicAuthentication(uri, Authentication.ANY_REALM, user, password)` to match any realm.
