### ISSUE TITLE
Jetty 12 is missing a way to record server latencies

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#8069]
**Jetty version(s)**
12.0.x

**Description**
12.0.x currently does not have anything equivalent to 11's `HttpChannel.Listener` API which is needed at least to record server latencies with our performance tests.

**Comment by lorban** [comment]
This actually can be done with the existing wrapper mechanisms by creating a `Handler.Wrapper` that adds a stream wrapper:

```java
    @Override
    public Request.Processor handle(Request request) throws Exception
    {
        long before = System.nanoTime();
        Request.Processor processor = super.handle(request);
        if (processor == null)
            return null;

        request.addHttpStreamWrapper(httpStream -> new HttpStream.Wrapper(httpStream)
        {
            @Override
            public void succeeded()
            {
                super.succeeded();
                recordLatency(System.nanoTime() - before);
            }

            @Override
            public void failed(Throwable x)
            {
                super.failed(x);
                recordLatency(System.nanoTime() - before);
            }
        });

        return processor;
    }
```

**Comment by sbordet** [comment]
@lorban can you make this a utility `Handler` with overridable methods such as `onRequestBegin()`, etc. so people that wants to use it can do so overriding only the few methods they need?

**Comment by gregw** [comment]
It could have a bunch of overridable methods that correspond to the previous listener events... or is that just adding complexity.
Perhaps just have an extensible method that creates the actual listener would be sufficient?

**Comment by sbordet** [comment]
@gregw won't you still need a `Listener` interface with all the `onXYZ()` methods?

**Comment by gregw** [comment]
It could be done with a new listener interface, or just an extendible method to create the stream listener.

My preference is to avoid lots of lists of listeners that we must iterate over.

**Comment by lorban** [comment]
Introduced `AbstractLatencyRecordingHandler` in #9172
