### ISSUE TITLE
Jetty-12 multi environment deployment

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8081]
**Target Jetty version(s)**
Jetty-12 

**Enhancement Description**

The deployer in Jetty-12 is now capable of deploying both ee9 and ee10 webapplications (and soon ee8).    However, thought is needed as to what the user experience should be.

Currently to deploy an eeX webapplication we need to enable the module `eeX-webapp` which will create the directory `webapps-eeX`  (yes we do have to decide a fix and order of the eeX prefix/suffix).   Thus we can have both `webapps-ee9` and `webapps-ee10` applications deployed by dropping them into different directories.

However, this is far less than optimal.    We expect moderately frequent eeX releases in the years ahead and many of them will have only minor changes to webapps with backwards compatibility.     Thus we don't want to have deployers constantly aiming for a moving target directory of `webapps-ee11`, `webapps-ee12`, etc. for the same applications that have not changed.

Thus we want the user experience for the main part to be: enable modules `webapps,deploy` and drop their war file into `webapps` directory.       To achieve the first part is pretty simple, as we can have a default `webapps` module that depends on the current stable `eeX-webapp` and creates a single `webapps` directory.  But then we also need to have a way to indicate different eeX for some deployed applications.    Using a context xml file is not sufficient as by the time the XML run, we need to know the env so the classsoader can be set.  So some options:
 + write a scanner that cracks open any WARs and looks for a WEB-INF/web.xml and infers the version from looking at it's first few lines.    This works fine for webapps, but only if we move unpacking to the deployer.   We'd also need another mechanism for pure context.xml deploys with no web.xml
 + have a separate foobar.env file that just contains the env name, with lack of the file indicating use of the latest env
 + have a convention for some other internal META-INF/jetty-environment file that can be used even for non webapps
 + some other idea
 + some combination of the above

We also need a good mechanism to detect errors and better report of an env is not known.   Having the named env files makes that easy, as otherwise we may need to catch exceptions and work that out.

**Comment by gregw** [comment]
@joakime @janbartel thoughts?

**Comment by olamy** [comment]
looking `WEB-INF/web.xml` as default.
but maybe some way to configure ee9 vs ee10. (e.g war with ee9 web.xml should work with ee10?)

**Comment by joakime** [comment]
If the `WEB-INF/web.xml` exists (doesn't have to exist), we can at least provide a minimum ee level from that information.

I can see folks wanting to put content in their WAR that would bind the ee level on jetty 12.
So is this a good feature for `WEB-INF/jetty-env.xml` ?

**Comment by gregw** [comment]
env switch can't be in `WEB-INF/jetty-env.xml` as by the time we run the xml we need the classloader, so we need the env to be known.  But perhaps we could looke for `WEB-INF/jetty-env-eeX.xml`

I like peeking at the `WEB-INF/web.xml` as a reasonable default.   However there is a complication of both  `WEB-INF/jetty-env.xml` and `WEB-INF/web.xml` that we really need the unpacked war.   Two issues with this:
 
1) We might not unpack, so we could end up with an expensive in-memory unpacking just to look for those files.
2) Currently all the unpacking has been done by the WebAppContext class.  We would need this to be done by the deployer.... which I have already partially implemented.  But it is complicated as the decision of where to unpack to is tied up with what the temporary directory is... and there is a lot of complex logic/legacy in WebAppContext for that as well.    I wouldn't mind simplifying that... but we still ultimately need to be able to run packed WARs

**Comment by janbartel** [comment]
How about `webapps/` is "aliased" to whatever the latest is (eg for now its `webapps-ee10`) so if you want your webapps always to be deployed with the latest and greatest, then put them in `webapps/`.  If you know that you specifically and only ever want particular webapps deployed to a specific version, then deploy to that: eg if you know you want `my.war` to be deployed to `ee8` then enable `ee8-deploy` which will create `webapps-ee8`, and put `my.war` in there.

Whatever mechanism we come up with, the default should be that if you do nothing "special", then your webapp will always be deployed to the latest version, you only have to do something if you want to specifically nail your webapp to a particular version.

By this rule, looking at `WEB-INF/web.xml` won't work, as many many webapps never change their version headers, but deploy year after year with no change on ever updated versions of jetty & spec.

**Comment by gregw** [comment]
Aliasing is enough of a problem without introducing our own extra aliases. Besides, simlinks are not supported on all platforms.

I don't understand your point about web.xml?   Surely even an unmaintained web.xml will be sufficient to indicate the status of: <servlet 5.0; ==servlet 5.0, >=servlet 6.0.   This is the key changes that we need to know.  If something deployed OK on ee10, then it should deploy ok on ee11 without changing the web.xml..... unless there is a big change to the servlet API, which would require a change to the web.xml

**Comment by janbartel** [comment]
> Aliasing is enough of a problem without introducing our own extra aliases. Besides, simlinks are not supported on all platforms.

I'm not saying filesystem aliasing, that's why I put it in quotes. I meant virtual aliasing - as in  inside the deployer - the ee10-deployer knows that it's directory to monitor is `webapps/`. When ee10 is no longer the newest, the ee10-deployer changes it's deploy directory to `webapps-ee10`, and the new eexx-deployer's directory is `webapps/`.

> I don't understand your point about web.xml? Surely even an unmaintained web.xml will be sufficient to indicate the status of: <servlet 5.0; ==servlet 5.0, >=servlet 6.0. This is the key changes that we need to know. If something deployed OK on ee10, then it should deploy ok on ee11 without changing the web.xml..... unless there is a big change to the servlet API, which would require a change to the web.xml.

Fine, currently we only have the version split between `javax.servlet` and `jakarta.servlet`, so you can guess between `ee8` and `ee9`. However, you wouldn't be able to guess `ee10`, _unless_ someone has updated their `web.xml` to servlet 6.  Most webapps don't change their `web.xml` when a new spec version comes out, unless it's something breaking like the `javax/jakarta` change. So after a while, there will have been many more iterations of the servlet spec, but all in the `jakarta.servlet` namespace, but many many webapps who didn't update `web.xml` past 6.0.0. In that case, how would you ever decide to deploy them to the latest ee version?

**Comment by gregw** [comment]
The issue with having "webapps" / "webapps-ee9" / "webapps-ee8" is that it is asymmetric and what do we do if there is both "webapps" and "webapps-ee9".

I think I'm convinced that web.xml inspection is not going to work well.   I'm now leaning towards a tag file of some kind.

**Comment by janbartel** [comment]
@gregw I think this issue is complete now?
