### ISSUE TITLE
To limit json data size in Post Body 

### ISSUE THREAD

**Issue by cg671344** [eclipse/jetty.project#8086]
**Jetty version**
Any
**Java version**
Java8_321, Spring boot 2.6.3
**Question**
I want to post a large json data in post body while using Jetty in sprint boot,  the data size maybe more than 100MB, and will set Content-Type as "application/json" in the header.
1. Is it possible to limit the json data size in the body?  Unlimited data size in body may do harm to the server.
2. Is that only Content-Type "multipart/form-data" that Jetty can limit the size of data ?
Thanks.

**Comment by joakime** [comment]
From a strictly Jetty and Servlet point of view you have 2 Content-Types that can limit size.

* `application/x-www-form-urlencoded` - controlled by `ContextHandler.setMaxFormContentSize(int)` and `org.eclipse.jetty.server.Request.maxFormContentSize` server attribute.  (use `HttpServletRequest.getParameter()` methods to access)
* `multipart/form-data` - controlled via Servlet [`@MultipartConfig`](https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/MultipartConfig.html) - use (use `HttpServletRequest.getPart()` methods, or `HttpServletRequest.getParameter()` methods, to access)

All other Content-Types are not limited by the Servlet spec or Jetty.

For spring-boot neither of these are relevant, as spring-boot does it's own size limitations outside of the Servlet spec.

See: https://stackoverflow.com/questions/33232849/increase-http-post-maxpostsize-in-spring-boot
