### ISSUE TITLE
The javax.servlet.request.key_size attribute is not set on the request by the ForwardedRequestCustomizer, as per servlet specification

### ISSUE THREAD

**Issue by mariapetridean** [eclipse/jetty.project#810]
Project: jetty-server
Affected versions: starting with Jetty 9.0.0
Context: SSL termination proxy

**Problem**:
The ForwardedRequestCustomizer sets the javax.servlet.request.cipher_suite attribute on the request, based on the forwarded cipher suite header, but does not set the key size attribute as well, as per servlet spec, 'SSL Attributes' section. 

For example, in case of a forwarded request which contains the headers X-Forwarded-Proto = https, the cipher suite header and the ssl session id header, the request will be set to secure, will contain the cipher suite attribute and the ssl session id attribute, BUT not the key size attribute.

**Possible fix**: in ForwardedRequestCustomizer, after the cipher suite attribute is set on the request, set also the key size attribute using: org.eclipse.jetty.util.ssl.SslContextFactory.deduceKeyLength(valueOfCipherSuiteHeader)

**Comment by joakime** [comment]
The `SecureRequestCustomizer` sets that attribute.
Enable that and you'll see the attributes you are looking for.

https://github.com/eclipse/jetty.project/blob/jetty-9.3.11.v20160721/jetty-server/src/main/java/org/eclipse/jetty/server/SecureRequestCustomizer.java#L266

**Comment by mariapetridean** [comment]
SecureRequestCustomizer is to be enabled when using the HTTPS connector.
But this issue affects the case when the HTTP connector is used (so no SecureRequestCustomizer).
For example, consider that the forwarding proxy adds X-Forwarded headers. When X-Forwarded-Proto=https, the ForwardedRequestCustomizer can leave the request in a state not conforming with the servlet spec (the cipher suite attribute is set, the ssl session id attribute is set, but the key size attribute missing).

**Comment by joakime** [comment]
Reopening for ForwardedRequestCustomizer specific detail.

Your original explanation didn't make it clear that this was a case of SSL termination at your proxy, talking plain http to Jetty.

**Comment by mariapetridean** [comment]
I updated the description, thanx!

**Comment by joakime** [comment]
Closing...

We can find no `X-Forwarded` header information that can provide this information to the jetty server to use.  

If you know of any appropriate header we can get this information from, feel free to reopen.

As a workaround, If you change to using something like `haproxy` and its `PROXY` protocol support, then this sort of information might be possible to pull out of the underlying connection.
