### ISSUE TITLE
Flaky tests HttpClientStreamTest.testUploadWithConcurrentServerCloseClosesStream, HttpClientStreamTest.testFileUpload

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#8132]
**jetty-10*

jetty-10.0.x has 2 flakey HttpClient tests, visible on this build: https://jenkins.webtide.net/job/jetty.project/job/jetty-10.0.x/1535/

**Comment by joakime** [comment]
The `testFileUpload` flaky is filed on issue #8084

**Comment by joakime** [comment]
Hasn't happened in months.
