### ISSUE TITLE
How does Jetty Client Decide the Default SNI

### ISSUE THREAD

**Issue by dev-chirag** [eclipse/jetty.project#8144]
**Jetty version**
9.4.43
**Java version**
1.8.0_321
**Question**

My Jetty client doesnt send the server_names extension in the Client Hello. 

I am not providing any SNIProvider implementation, so I believe it's using the default:

_private SniProvider sniProvider = (sslEngine, serverNames) -> serverNames;_

This _serverNames_ is fetched from the _sslEngine_ or _sslParameters_ 

But I fail to understand where SSLEngine or SSLParameters get this host name?

Appreciate the help as always,  @sbordet @joakime 

Thanks

**Comment by sbordet** [comment]
The SNI is taken from the request host name, which is used to open a TCP connection to the server, and passed to `SSLEngine`.

The JDK sends the SNI if it's a proper host name such as `google.com`, but not if it's an IP address or a non-domain string (see javadocs for class `SniProvider`).

You can use `SniProvider` to try to force the send of the SNI in the cases the JDK does not send them, but it's brittle as different Java versions allow different sets of characters.

**Comment by dev-chirag** [comment]
Thanks @sbordet , precise and quick as always!
