### ISSUE TITLE
Does the AsyncContext.setTimeout() support dynamic Settings in Jetty?

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#8156]
**Jetty version**
9.4.46.v20220331
**Java version**
jdk1.8.192
**Question**
Does the AsyncContext.setTimeout() support dynamic Settings in Jetty? I have a requirement that the timeout set at the beginning of the request can be set again when needed?

**Comment by sbordet** [comment]
> Does the AsyncContext.setTimeout() support dynamic Settings in Jetty? 
I have a requirement that the timeout set at the beginning of the request can be set again when needed?

No, per specification the timeout applies for every `startAsync` cycle, so you can set it, then it expires, then you can call `startAsync()` again and you can set a different timeout.

Alternatively, you disable the timeout via `setTimeout(0)`, and you manage your own timeouts with your own scheduler.

**Comment by xinguangduan** [comment]
@sbordet ，thank you very much! I will try it.
