### ISSUE TITLE
Stopping server from within AbstractConnector#accept fails and results in a partially stopped QueuedThreadPool

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/jetty.project#8206]
**Jetty version(s)**
11.0.11 (also affecting older versions, such as 9.4.12)

**Java version/vendor** `(use: java -version)`
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment Temurin-18+36 (build 18+36)
OpenJDK 64-Bit Server VM Temurin-18+36 (build 18+36, mixed mode)
and others

**OS type/version**
macOS 12.4

**Description**
A Server instance using `QueuedThreadPool` may shutdown incompletely (preventing the process from terminating) upon a call to Server#stop from within `AbstractConnector#accept`. This is due to the fact that two calls in `QueuedThreadPool#doStop` may throw `InterruptedException` (`joinThreads`), preventing the method to complete as expected.

**How to reproduce?**

```
public class QTPTest {
  public static void main(String[] args) throws Exception {
    Server s1 = newServer();

    try (Socket sock = new Socket()) {
      // triggers AbstractConnector#accept and thus, Server#stop.
      // see below.
      sock.connect(new InetSocketAddress("localhost", 12345));
    }

    s1.join(); // wait until Server stops

    System.out.println("The end."); // not reached without fix
  }

  private static Server newServer() throws Exception {
    Server server = new Server();

    ServerConnector connector = new ServerConnector(server) {

      @Override
      public void accept(int acceptorID) throws IOException {
        super.accept(acceptorID);

        // trigger stop from within accept

        Runnable stopRunnable = () -> {
          try {
            System.out.println("STOPPING: " + server);
            server.stop();
          } catch (Exception e) {
            e.printStackTrace();
          }
        };

        // stopRunnable.run(); // doesn't work
        // throws an InterruptedException via ManagedSelector.doStop(ManagedSelector.java:137)

        // works but creating new Threads may be discouraged by policy
        // new Thread(stopRunnable).start();

        // works but requires a new ExecutorService and shutdown logic
        // ExecutorService es = Executors.newSingleThreadExecutor();
        // es.execute(stopRunnable);
        // es.shutdown();

        getExecutor().execute(stopRunnable); // gets a bit farther, but (without fix) throws an
                                             // InterruptedException in
                                             // QueuedThreadPool.joinThreads(QueuedThreadPool.java:324)
      }

    };
    connector.setHost("localhost");
    connector.setPort(12345);
    connector.setReusePort(true);
    server.addConnector(connector);

    System.out.println("Starting new server: " + server);
    server.start();

    return server;
  }
}
```

**Comment by joakime** [comment]
The `server.stop()` should be from a new thread.

**Comment by kohlschuetter** [comment]
Is calling `#stop()` in a new thread some kind of convention? I think that may need to be documented somewhere.

I can confirm that seems to work, except when using `getExecutor().execute`, which I thought is better than creating your own new Thread.

Ideally, it shouldn't matter what thread the call comes from, though. It reminds me a bit of iOS and having to call some code from the main thread and some not.

**Comment by gregw** [comment]
Ideally it should not be necessary... So let's call it a work around for now, whilst we ponder this issue some more

**Comment by joakime** [comment]
You are attempting to stop the lifecycle from within the lifecycle.
And you are attempting to stop the thread (being managed by QueuedThreadPool) from within a thread being managed by the ThreadPool/Executor.

Using `.getExecutor().execute()` is the same issue.
You couldn't use `getExecutor().execute()` to `server.stop()` from anywhere else in Jetty as well, as the result of calling `server.stop()` is to stop the the Executor being managed by the server as well.

**Comment by gregw** [comment]
fixed in 10 and merged through 11 & 12
