### ISSUE TITLE
Test resources need to be transformed to ee8

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#8209]
**jetty-12.0.x**

Some `jetty-ee8-plus` tests are failing, because they use `src/test/resources` such as `web.xml` and `web-fragment.xml` that have not been transformed from `ee9` to `ee8`.

**Comment by olamy** [comment]
fixed https://github.com/eclipse/jetty.project/commit/68206ce880a334d02fa381adf03fe01e2e5b2015

**Comment by joakime** [comment]
@olamy @janbartel is this still valid? can it be closed?

**Comment by olamy** [comment]
done
