### ISSUE TITLE
When the HttpClientTransportOverUnixSockets is used to send UDS requests, Jetty has lost responses.

### ISSUE THREAD

**Issue by mjs8002** [eclipse/jetty.project#8213]
**Jetty version(s)**
jetty-io-9.4.46.v20220331.jar
**Java version/vendor** `(use: java -version)`
jdk1.8
**OS type/version**
linux
**Description**
_Do not report security issues here! See [Jetty Security Reports](https://www.eclipse.org/jetty/security_reports.php)._
When the HttpClientTransportOverUnixSockets is used to send UDS requests, Jetty has lost responses.

Analyze logs. It is found that the value of key.attachment in the [processSelected method of ManagedSelector](https://github.com/eclipse/jetty.project/blob/1f4c5313576a5d02e7906db0d7cf0a0aa2a40ef3/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L659) is {http.destination=HttpDestination[http://....}.
As a result, the server response cannot match the correct attachment, and the exception log "Could not process key for channel" is recorded. As a result, the Jetty client loses the response thread and is blocked.
We have two questions.
first
I think
https://github.com/eclipse/jetty.project/blob/1f4c5313576a5d02e7906db0d7cf0a0aa2a40ef3/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L398
 key.attach(endPoint) has a certain delay. In high concurrency scenarios, the jetty thread key.attachment() cannot obtain a correct value
second
Why is 
the key in https://github.com/eclipse/jetty.project/blob/1f4c5313576a5d02e7906db0d7cf0a0aa2a40ef3/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L674
 not isConnectable() in TCP scenarios?

**How to reproduce?**

         File file = new File("/opt/unix.sock");
        UnixSocketAddress address = new UnixSocketAddress(file);
        UnixSocketChannel channel = UnixSocketChannel.open(address);
        channel.configureBlocking(false);
        Selector selector = NativeSelectorProvider.getInstance().openSelector();
        SelectionKey selectionKey = channel.register(selector, SelectionKey.OP_CONNECT);
        selector.select();
        System.out.println(selectionKey.isConnectable());
        ByteBuffer allocate = ByteBuffer.allocate(1024);
        int write = channel.write(ByteBuffer.wrap("GET /unix/test HTTP/1.1\r\n\r\n".getBytes(StandardCharsets.UTF_8)));
        int read = channel.read(allocate);
        byte[] data = subByte(allocate.array(), 0, read);
        System.out.println(new String(data));

**Comment by mjs8002** [comment]
![image](https://user-images.githubusercontent.com/41276528/176076514-9aef30a7-7b58-4e01-b814-fe2e01356031.png)

**Comment by mjs8002** [comment]
![image](https://user-images.githubusercontent.com/41276528/176076612-3f3b3358-5ea3-452f-af7b-a1146a653924.png)
why the key is not isConnectable() in TCP scenarios?

**Comment by mjs8002** [comment]
the correct attachment is [WARN ][0][0][qtp109791354-53][ROOT][org.eclipse.jetty.io.ManagedSelector$SelectorProducer][678] attachment=UnixSocketEndPoint{selector=jnr.enxio.channels.PollSelector@30d103fe, key=jnr.enxio.channels.PollSelectionKey@2f6b959f.....} in  UDS scenarios

**Comment by sbordet** [comment]
@mjs8002 like explained in #7187 and #8091, JNR is not stable and it's now deprecated and replaced by Java 16 UnixDomain Socket support in Jetty 10.
See also #8203.

**Comment by gregw** [comment]
@mjs8002 whilst @sbordet is correct (in that we will not be fixing JNR nor jetty-9), I'm interested in analysing why you think there is a race condition registering the attachement, as this may affect current versions of jetty.

Can you explain fully what sequence you think is happening and how a delayed/slow attach can be a problem?    Are you saying that the selection key that is being created is again selected whilst the attachment is being updated?     I've had a quick look and can't see immediately how that can happen, as I think it is protected by interested ops.

@sbordet I'm going to re-open this one... until such  time as we've had time to discuss this possible race (but even if it is a race, we will not be fixing JNR in 9).

**Comment by sbordet** [comment]
Closing this, as now we have official support of unix-domain sockets from the JDK and the use of JNR is deprecated.
