### ISSUE TITLE
Deprecate WebAppProvider.setConfigurationClasses()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8227]
**Jetty version(s)**
Jetty 10+

**Description**
The WebAppProvider has a method called `.setConfigurationClasses(String[])` that will force set the `WebAppContext.setConfigurationClasses(String[])` which is something we really should be discouraging with Jetty 10+ and the new `Configuration` serviceloader and whatnot.

We should deprecate these methods, with warnings on use.

**Comment by sbordet** [comment]
@joakime still a TODO, right?

**Comment by joakime** [comment]
Yes.
