### ISSUE TITLE
Implement notifications of asynchronous error conditions for HTTP/2

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#824]
Differently from HTTP/1.1, with HTTP/2 the socket channel is always read interested.

When an application suspends the request, in HTTP/1.1 we are not able to detect if the client has abruptly closed the connection, while in HTTP/2 we can.

Furthermore, a HTTP/2 client can send a RST_FRAME to indicate it wants to cancel the request.

Idle timeouts for both the session and the stream can cause asynchronous failures as well, that should be notified to the application.

**Comment by sbordet** [comment]
With HTTP/1.1:

1A. Client closes; server cannot detect, AsyncListener.onError() not called.
2A. Server idle timeout; ignored because of the logic in AbstractEndPoint.onIdleExpired(), AsyncListener.onError() not called, connection is kept open forever.

In HTTP/2:

2A. Client send RST_STREAM; currently ignored because of issue #824, AsyncListener.onError() not called.
2B. Client send GOAWAY and closes the connection; server closes the connection, AsyncListener.onError() not called.
2C. Server stream idle timeout; currently ignored, AsyncListener.onError() not called.
2D. Server session idle timeout; server sends GOAWAY and closes the connection, AsyncListener.onError() not called.

**Comment by gregw** [comment]
The servlet spec has discussed the new capability of HTTP/2 of being able to detect a close/failure and there is a [proposed API](https://java.net/jira/browse/SERVLET_SPEC-156)  that will allow notification of the condition.    The has not been accepted yet, but discussion in the EG is positive, so something will be done.

So it is clear that if a h2 stream terminates early for some reason, then the intention it to be able to inform the application of that termination.

So looking at the the AsyncListener - I believe that the onError callback must be called if we know that the underlying stream/connection has been terminated.  So we need to call onError for all of 2A, 2B, 2C & 2D.

We need to clarify in what order AsyncListener and the new API will be called and I will raise that in the EG.

**Comment by sbordet** [comment]
@gregw I think that after our discussion 2C and 2D should be ignored, as it happens now for 2A, to match the Servlet semantic that a dispatched request can outlive the idle timeout.
