### ISSUE TITLE
EofException is reported when the unix domain socket capability is used on the Jetty client

### ISSUE THREAD

**Issue by usertree** [eclipse/jetty.project#8260]
**Jetty version(s)**
9.4.46.v20220331
**Java version/vendor** `(use: java -version)`
JDK 8
**OS type/version**
x86
**Description**
The Jetty client reports an EofException when using the Unix socket domain capability. The cause is that after the Jetty flushes some buffers, the server finds that the request header contains special characters and does not forward the request and returns 503. After the channel is closed, the client reports an error when writing data.
Check the bottom-layer implementation of TCP and UDS. The JDK implementation checks whether the value of buffer remain is greater than 0. However, the JNR-unixsocket does not check whether the value of buffer remain is greater than 0. Instead, the JNR-unixsocket directly flushes the buffer. As a result, an error is reported after the channel is closed.
JDK code：
![image](https://user-images.githubusercontent.com/32734356/176995675-468ad410-15a1-4983-8d9f-edb2a0a15ddf.png)
jnr-unixsocket code：
![image](https://user-images.githubusercontent.com/32734356/176996092-28c3a1b0-c29f-4c04-a7c8-bc4b6fd84a50.png)

Current Solution：
Filter the empty buffer before calling jnr-unixsocket to write data. Modifying the ChannelEndPoint Class:
```
@Override
    public boolean flush(ByteBuffer... buffers) throws IOException
    {
        long flushed;
        try
        {
            flushed = _channel.write(Arrays.stream(buffers).filter(v -> v.remaining() > 0).collect(Collectors.toList()).toArray(new ByteBuffer[0]));
            if (LOG.isDebugEnabled())
                LOG.debug("flushed {} {}", flushed, this);
        }
        catch (IOException e)
        {
            throw new EofException(e);
        }

        if (flushed > 0)
            notIdle();

        for (ByteBuffer b : buffers)
        {
            if (!BufferUtil.isEmpty(b))
                return false;
        }

        return true;
    }
```

**Comment by sbordet** [comment]
This is clearly a bug in JNR and we won't fix it in Jetty.
See also [this comment](https://github.com/eclipse/jetty.project/issues/8213#issuecomment-1171399740).

Jetty 9.4.x is also Community EOL as detailed in #7958.

Please use Jetty 10 with Java 16 since there is support for unix domain sockets in OpenJDK (not using JNR).
