### ISSUE TITLE
Jetty version 10.0.11 imports JDK packages in its manifest.mf

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse/jetty.project#8265]
**Jetty version(s)**
10.0.11

**Java version/vendor** `(use: java -version)`
17.0.3 openjdk

**OS type/version**
Windows 10

**Description**
We are getting the error mentioned in https://github.com/eclipse-pde/eclipse.pde/issues/194. We could find the root cause as addition of jdk packages to Import-package directive in MANIFEST.MF. Wondering if this is intentional.

Here is the jetty-http bundle we are using https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.11/jetty-http-10.0.11.jar

**Comment by janbartel** [comment]
We updated the version of the bundle plugin from 5.1.4 in 10.0.9 to 5.1.6 in 10.0.10, that's probably the cause of the different generated import list.

**Comment by HannesWell** [comment]
> **Description**
> We are getting the error mentioned in [eclipse-pde/eclipse.pde#194](https://github.com/eclipse-pde/eclipse.pde/issues/194). We could find the root cause as addition of jdk packages to Import-package directive in MANIFEST.MF. Wondering if this is intentional.
> 
Yes this is intentional by BND (which I assume jetty is using to generate its manifest): https://github.com/bndtools/bnd/issues/4348

**Comment by sravanlakkimsetti** [comment]
maven-bundle-plugin has upgraded from 5.1.1 to 6.2.0 in https://github.com/apache/felix-dev/commit/b29ea9a5d6dc8662dc0c960eff199c18fcd6b5e4. 


> Yes this is intentional by BND (which I assume jetty is using to generate its manifest): [bndtools/bnd#4348](https://github.com/bndtools/bnd/issues/4348)

Yes jetty was using maven-bindle-plugin and it is in turn using BND. 
Now the question is what should be the approach here.

**Comment by laeubi** [comment]
This is not a bug, this is OSGi good practice since R7 see https://blog.osgi.org/2018/02/osgi-r7-highlights-java-9-support.html

**Comment by HannesWell** [comment]
> Yes jetty was using maven-bindle-plugin and it is in turn using BND. Now the question is what should be the approach here.

IMHO it is fixing the false positive validation-error in PDE.

**Comment by joakime** [comment]
We've heard from developers at BND and Eclipse Equinox that this is correct, and good practice.
I'm inclined to leave this as-is.

**Comment by laeubi** [comment]
> > Yes jetty was using maven-bindle-plugin and it is in turn using BND. Now the question is what should be the approach here.
> 
> IMHO it is fixing the false negative positive validation-error in PDE.

Exactly especially because even if jetty decides to not do it this way now sooner or later people will be hit by this problem by other libraries. The R7 is out about 4 years now, java 9 is out 5 years so we are just a way behind here....

**Comment by sravanlakkimsetti** [comment]
It is confirmed as a bug in PDE. This can be closed now
