### ISSUE TITLE
HTTPClient fails connecting to HTTPS host through an HTTP proxy w/authentication

### ISSUE THREAD

**Issue by brettwooldridge** [eclipse/jetty.project#827]
I have an authenticating HTTP proxy (Squid), and I am trying to connect to a remote server that is running HTTPS.  I've burned a day on it and can't get it to work.

Here is a simple reproduction (added to ``HttpClientProxyTest.java``):

```java
    @Test
    public void testMyProxyAuthentication() throws Exception
    {
        final String user = "cent";
        final String password = "lvi";
        final String serverHost = "https://www.gmail.com";
        final String realm = "Squid Basic Authentication";

        // Squid proxy with authentication
        String proxyHost = "192.168.1.11";
        int proxyPort = 3128;

        sslContextFactory = new SslContextFactory();
        sslContextFactory.setTrustAll(true);

        startClient();

        HttpProxy proxy = new HttpProxy(proxyHost, proxyPort);
        proxy.getIncludedAddresses().add("www.gmail.com");
        proxy.getIncludedAddresses().add("www.gmail.com:443");

        client.getProxyConfiguration().getProxies().add(proxy);

        // Add authentication...
        URI uri = URI.create("http://" + proxyHost + ":" + proxyPort);
        client.getAuthenticationStore().addAuthentication(new BasicAuthentication(uri, realm, user, password));
        
        ContentResponse response = null;
        try {
	        response = client.newRequest(serverHost)
	                .timeout(5, TimeUnit.SECONDS)
	                .send();

	        Log.getLogger(this.getClass()).info("Status: " + response.getStatus());
        }
        catch (Exception e) {
        	Log.getLogger(this.getClass()).warn(e);
        	throw e;
        }
    }

```
The exceptions vary, depending on whether I remove the ``proxy.getIncludedAddresses().add(...)`` calls or not ... but it fails nonetheless.

If I set the squid to non-authenticating, it works without issue.  If I connect to a non-HTTPS target, with proxy authentication, it also works without issue.

**Comment by sbordet** [comment]
Can you enable DEBUG logging in the client for the category `org.eclipse.jetty`, and attach here the log ?

**Comment by brettwooldridge** [comment]
Logs here: [debug-logs.zip](https://github.com/eclipse/jetty.project/files/409548/debug-logs.zip)

When I was debugging, I also saw something similar as was reported in #408 where @smatei says:

> It seems that in HttpRequest.BuildURI, an URI is created from "www.google.com:443", that has no protocol.

**Comment by sbordet** [comment]
@brettwooldridge, issue #408 has been long fixed. What exact version of Jetty are you on ?

The logs show `HttpClient` sending a `CONNECT`, the proxy replying with a `407` with a body, then `HttpClient` skipping the parse of the body of the `407` response. This looks like a weird `HttpParser` bug. Investigating.

**Comment by brettwooldridge** [comment]
@sbordet We were testing with ``9.3.11.v20160721``.  I ran the above code on the head of ``jetty-9.3.x``.

**Comment by brettwooldridge** [comment]
@sbordet Note that the behavior *is* different when configured to proxy only certain URLs:
```java
proxy.getIncludedAddresses().add("www.reddit.com");
proxy.getIncludedAddresses().add("www.reddit.com:443");
```
Our actual case isn't reddit.com, but we do have the requirement to proxy only a few specific URLs.

My point is, whatever the eventual fix, it should be tested both with and without "included" addresses.

**Comment by brettwooldridge** [comment]
@sbordet Sorry for the spam ...

I noted only the similarity to #408 because *at some point* when I set a breakpoint in HttpRequest.buildURI()...

It had seemingly correctly parsed the 407 response and was looking for the authenticator.  The ``AuthenticationProtocolHandler`` calls ``HttpRequest.getURI()``, and ``getURI()`` calls ``buildURI()``, and [buildURI() calls newURI()](https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java#L787), and because the URI passed into ``newURI()`` was "www.reddit.com" (literally that string) it is [declared *opaque*](https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java#L803) and a ``null`` is returned back up the chain.

The ``null`` results in the log message ``No authentication
available for HttpRequest[CONNECT www.reddit.com:443 HTTP/1.1]@39f5ea27``.

**Comment by sbordet** [comment]
@brettwooldridge can you test the latest code and report if it's fixed for you ?

**Comment by brettwooldridge** [comment]
Fails in largely the same way.  Log attached, with source code before the log so you can sanity check my usage: [debug_log4.zip](https://github.com/eclipse/jetty.project/files/411651/debug_log4.zip)

**Comment by sbordet** [comment]
Your latest logs do not run the latest code, so it fails in the same way.

I don't think there was time to build a snapshot and deploy it, so you have to build Jetty yourself to run the latest code.

Perhaps your morning a new snapshot will be available, but we are restructuring the continuous integration and I'm not sure... Better you build Jetty yourself:

```
$ git clone https://github.com/eclipse/jetty.project.git
$ cd jetty.project
$ mvn install -DskipTests=true
```

Thanks !

**Comment by brettwooldridge** [comment]
@sbordet I am running from the latest source, trust me.  Here is a screenshot with a breakpoint showing the debugger stopped on your change:

![screen shot 2016-08-11 at 10 51 15](https://cloud.githubusercontent.com/assets/1538661/17576799/ba3e186e-5fb1-11e6-9477-7b39466d8f72.png)

Please don't patronize me, I am an experienced developer (25 years) of several libraries used by many major frameworks (Hibernate, Typesafe, Facebook Buck, Spring IO...).

**Comment by brettwooldridge** [comment]
@sbordet Why was this closed?

I can confirm that your fix addresses the case when the HttpProxy has no "included" addresses.

However, this fails:
```java
HttpProxy proxy = new HttpProxy(proxyHost, proxyPort);
proxy.getIncludedAddresses().add("www.reddit.com");
proxy.getIncludedAddresses().add("www.reddit.com:443");
```

Counter-intuitively, and out of shear frustration, I added this:
```java
proxy.getIncludedAddresses().add(proxyHost + ":" + proxyPort);
```
Miracle of miracles, it works.  Why this proxy needs to *include itself* is a mystery.  Without that line, the authenticator is not found.  Kinda seems like the proxy should include itself by default, right?

I don't know what it is about *HTTPS* through a proxy with authentication, but I can confirm that line is *not* necessary when connecting to an HTTP target (eg. http://www.wired.com) through the same authenticating proxy.

**Comment by brettwooldridge** [comment]
@sbordet I can also confirm that even reverting back to 1bff5c0, before your fix, and including the proxy itself in the "included addresses" works.

I still consider this a bug, because it certainly appears to be "accidental" behavior (and unnecessary when HTTP instead of HTTPS is used).

**Comment by sbordet** [comment]
@brettwooldridge there is no patronizing, there are no miracles. If you feel it's not fixed, reopen and discuss. I'm working on it, okay ?

**Comment by brettwooldridge** [comment]
@sbordet I have no option to "reopen" the bug.

**Comment by sbordet** [comment]
@brettwooldridge can you try the latest code ?

**Comment by brettwooldridge** [comment]
@sbordet I can confirm that the latest change works.

**Comment by brettwooldridge** [comment]
@sbordet Can we get a release sometime soon?  This is a security exposure.  Customers behind proxies are sending data in the clear to our servers, pending this fix.

**Comment by jmcc0nn3ll** [comment]
@brettwooldridge there is a staged release we are testing out now

https://oss.sonatype.org/content/repositories/jetty-1261/

If this passes our review we will push it into maven central within the next day or three most likely.  We are working on staging 9.4.0.RC0 as well.

Regarding business needs, Webtide is available for those sorts of requirements and I would encourage you to reach out to me <jesse@webtide.com> if you would like to learn more. 

cheers!

**Comment by joakime** [comment]
@brettwooldridge love your hikaricp project!

That staging repository is the potential release for jetty 9.3.12.v20160915 that we are testing.
If you have any feedback on it, we'd love to hear it (before 5pm PST Friday please)
