### ISSUE TITLE
re enable test for jetty-ee8-websocket-jetty-tests and jetty-ee8-websocket-javax-tests

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#8278]

**Comment by joakime** [comment]
None of the ee8 websocket tests are specifically disabled, and there are many ee8 tests showing up in the CI test report.

Package | Duration | Fail | Skip | Pass | Total
-- | -- | -- | -- | -- | --
org.eclipse.jetty.ee8.websocket.client | 0.98 sec | 0 | 0 | 26 | 26
org.eclipse.jetty.ee8.websocket.common | 3.1 sec | 0 | 0 | 68 | 68
org.eclipse.jetty.ee8.websocket.common.invoke | 72 ms | 0 | 0 | 48 | 48
org.eclipse.jetty.ee8.websocket.javax.common | 0.25 sec | 0 | 0 | 58 | 58
org.eclipse.jetty.ee8.websocket.javax.common.messages | 0.26 sec | 0 | 0 | 36 | 36
org.eclipse.jetty.ee8.websocket.javax.common.util | 74 ms | 0 | 0 | 70 | 70
org.eclipse.jetty.ee8.websocket.javax.tests | 9 sec | 0 | 0 | 88 | 88
org.eclipse.jetty.ee8.websocket.javax.tests.client | 1.1 sec | 0 | 0 | 68 | 68
org.eclipse.jetty.ee8.websocket.javax.tests.client.misbehaving | 56 ms | 0 | 0 | 4 | 4
org.eclipse.jetty.ee8.websocket.javax.tests.coders | 6.5 sec | 0 | 0 | 162 | 162
org.eclipse.jetty.ee8.websocket.javax.tests.handlers | 1 sec | 0 | 0 | 46 | 46
org.eclipse.jetty.ee8.websocket.javax.tests.quotes | 0.23 sec | 0 | 0 | 14 | 14
org.eclipse.jetty.ee8.websocket.javax.tests.server | 19 sec | 0 | 2 | 466 | 468
org.eclipse.jetty.ee8.websocket.javax.tests.server.examples | 0.1 sec | 0 | 0 | 6 | 6
org.eclipse.jetty.ee8.websocket.tests | 28 sec | 0 | 0 | 140 | 140
org.eclipse.jetty.ee8.websocket.tests.client | 34 sec | 0 | 0 | 108 | 108
org.eclipse.jetty.ee8.websocket.tests.extensions | 10 ms | 0 | 0 | 16 | 16
org.eclipse.jetty.ee8.websocket.tests.listeners | 0.3 sec | 0 | 0 | 26 | 26
org.eclipse.jetty.ee8.websocket.tests.proxy | 6.2 sec | 0 | 0 | 14 | 14
org.eclipse.jetty.ee8.websocket.tests.server | 25 sec | 0 | 0 | 56 | 56
org.eclipse.jetty.ee8.websocket.tests.util | 9 ms | 0 | 0 | 16 | 16
