### ISSUE TITLE
Improve QosFilter for HTTP/2 Stream capabilities.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#829]
HTTP/2 can allow a single connection to create many requests, which can make it easier for a DOS attacker.

We currently default to no limit of streams per connection.  This should be changed to a value - say 100.

It may also be beneficial to have a thread limit less than the stream limit.   QoSFilter could apply such a thread throttle to a connection.

**Comment by gregw** [comment]
Oops, this partially duplicates #826.    Leaving open for QoSFilter change.

**Comment by sbordet** [comment]
We have 128 max concurrent streams per connection by default.
