### ISSUE TITLE
Jetty-12 EE10 Default Servlet 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8291]
**Target Jetty version(s)**

Jetty-12

**Enhancement Description**

Fix/implement the deficiencies of the ee10 DefaultServlet and ResourceHandler as identified by reviews of #8276: specifically:
 + undisable the `DefaultServletTest` and fix them
 + remove the Generic request/response abstraction
+ enable welcome files
 + javadoc

**Comment by joakime** [comment]
This is mostly done so far.
Most of the remaining work is in the core `ResourceService`
