### ISSUE TITLE
Jetty 9.x Websocket Client hangs during startup on a higher spec VM - ( 32 cores & 64 GB ram)

### ISSUE THREAD

**Issue by arora53** [eclipse/jetty.project#8295]
Jetty Websocket Client hangs during startup on a higher spec VM - ( 32 cores & 64 GB ram), whereas is able to establish a connection on a lower spec machine ( 16 cores & 32 GB ram ). We are using jetty websocket client for one of our applications deployed on VM with the  16 cores & 32 GB ram configuration. On increasing ( doubling ) the config to  32 cores & 64 GB ram the client.start() would hang up infinitely. PFB the code snippet for the same 

``` java
   jettySocketClient = new JettySocketClient(sendNotificationObj);
   client.start();
```

The issue is there for the older version **'9.2.16.v20160414'** as well as the latest version of jetty websocket **9.4.48.v20220622.**
'org.eclipse.jetty.websocket', name: 'websocket-client', version: '9.4.48.v2022062'

Issue Reproducible - Everytime
OS - Linux
Java Version - openjdk version "1.8.0_242"

PFB the snippet from the thread dump taken for the same. 

Thread 2598997: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Interpreted frame)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt() @bci=1, line=836 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(int) @bci=72, line=997 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int) @bci=24, line=1304 (Interpreted frame)
 - java.util.concurrent.CountDownLatch.await() @bci=5, line=231 (Interpreted frame)
 - org.eclipse.jetty.io.ManagedSelector.doStart() @bci=55, line=127 (Interpreted frame)
 - org.eclipse.jetty.util.component.AbstractLifeCycle.start() @bci=31, line=73 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.start(org.eclipse.jetty.util.component.LifeCycle) @bci=1, line=169 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.doStart() @bci=150, line=117 (Interpreted frame)
 - org.eclipse.jetty.io.SelectorManager.doStart() @bci=54, line=262 (Interpreted frame)
 - org.eclipse.jetty.util.component.AbstractLifeCycle.start() @bci=31, line=73 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.start(org.eclipse.jetty.util.component.LifeCycle) @bci=1, line=169 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.doStart() @bci=150, line=117 (Interpreted frame)
 - org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStart() @bci=35, line=64 (Interpreted frame)
 - org.eclipse.jetty.util.component.AbstractLifeCycle.start() @bci=31, line=73 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.start(org.eclipse.jetty.util.component.LifeCycle) @bci=1, line=169 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.doStart() @bci=150, line=117 (Interpreted frame)
 - org.eclipse.jetty.client.HttpClient.doStart() @bci=266, line=255 (Interpreted frame)
 - org.eclipse.jetty.util.component.AbstractLifeCycle.start() @bci=31, line=73 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.start(org.eclipse.jetty.util.component.LifeCycle) @bci=1, line=169 (Interpreted frame)
 - org.eclipse.jetty.util.component.ContainerLifeCycle.doStart() @bci=150, line=117 (Interpreted frame)
 - org.eclipse.jetty.websocket.client.WebSocketClient.doStart() @bci=11, line=413 (Interpreted frame)
 - org.eclipse.jetty.util.component.AbstractLifeCycle.start() @bci=31, line=73 (Interpreted frame)
 - com.avaya.pim.ccaas.ws.WebSocketClientMain.startWebSocket(java.lang.String, java.lang.String) @bci=200, line=83 (Interpreted frame)
 - java.util.concurrent.FutureTask.run() @bci=42, line=266 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1149 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=750 (Interpreted frame)

Can someone look into this on priority. Let me know if any other details are required.

**Comment by joakime** [comment]
_Priority support is offered via Webtide LLC contact jesse@webtide.com for details._

I'm a committer on Eclipse Jetty.
My daily development machine is a AMD Ryzen Threadripper 2990WX (32-core, 64-hyperthreads), with 128GB of RAM, running Ubuntu 20.04.4 LTS.
I have not experienced this websocket client issue you are reporting.

We need more information, as this is not reproducible by simply starting the `org.eclipse.jetty.websocket.client.WebSocketClient`

One last thing, Java `1.8.0_242` expired on April 14, 2020 (per the release notes for that release), you are not supposed to be using that version of Java anymore, consider upgrading your version of Java (if your code uses the public internet, or are using SSL/TLS, then this is a critical task for you)

**Comment by joakime** [comment]
Also, check your `cgroups` within that VM to ensure that you are using BOTH a version of your VM that supports setting cgroups properly for your CPU configuration, and are using a version of Java that also uses the `cgroups` settings properly.

With older version of VMs (docker, containerd, vmware, virtualbox, etc) they didn't set the `cgroups` properly to the limited configurations of the VM, and instead just used the host machines values. 
Also, Java support for `cgroups` wasn't added until Java 10. (though your Java 1.8 VM might have a backport that fixes it)

Finally, Java 9.4.x is now at End of Community Support.
See: https://github.com/eclipse/jetty.project/issues/7958 for details.

**Comment by arora53** [comment]
Thanks for the reply, Here is the sample code that we are using to connect via Jetty WebSocket...

``` java
private ExecutorService executor = Executors.newFixedThreadPool(15,new ThreadFactoryBuilder().setNameFormat("TEST-WS-%d").build());

private void startWebSocket(String dest)
	{
		SslContextFactory sslContextFactory = new SslContextFactory();
		sslContextFactory.setSslContext(this.sslContext);
		WebSocketClient client = new WebSocketClient(sslContextFactory,executor);
		try
		{
			jettySocketClient = new JettySocketClient(sendNotificationObj);
			client.start();
			URI echoUri = new URI(dest);
			ClientUpgradeRequest request = new ClientUpgradeRequest();
			log.finest(fncName, Thread.currentThread().getName() + ":Trying to connect WebSocket Connection...");
			Future<Session> session = client.connect(jettySocketClient, echoUri, request);
			while (!session.isDone())
				;
				
			jettySocketClient.sendMessage("TEST MESSAGE");
			log.getConsoleLogger().finest("Subscription Request  was successful");
			jettySocketClient.awaitClosure();	
		} catch (Exception t)
		{
			log.LogAndPrintStackTraceInLogger(t);
			log.error(fncName, t.getLocalizedMessage());
		}
	}			
```
	
I will check about the cgroups within the team and update the ticket with relevant informantion.

**Comment by joakime** [comment]
Thanks, but that code is incomplete, broken, doesn't compile, and has bugs.

why are you using a custom `Executor`? (this is always a red-flag, just configure the QueuedThreadPool instead)
why is your custom `Executor` setting such a ridiculously tiny max thread pool? (smells of bad premature optimization)
why are you using the deprecated `WebSocketClient(SslContextFactory, Executor)`?
why are you using the deprecated `SslContextFactory`? (you should be using the `SslContextFactory$Client`)?
what's `jettySocketClient`?
what's `sendNotificationObj`?
what's `ThreadFactoryBuilder`?
what's `this.sslContext`?
what does `jettySocketClient.sendMessage(String)` do?
how have you configured the `ClientUpgradeRequest`? (if you didn't configure it, then remove it)
You don't use `Future` like that (tight loop on isDone), that's horrible for your threading.

Tell you what, go test this ... https://github.com/jetty-project/embedded-jetty-websocket-examples/tree/9.4.x/native-jetty-websocket-example/src/main/java/org/eclipse/jetty/demo
Run the `EventServer` first, then run the `EventClient` to test the Jetty `WebSocketClient` against the server.
Does that work for you?

Try forking the above example and modify it to fit your scenario until it fails.
Share that forked project here.

**Comment by joakime** [comment]
This was tested against Jetty 9.4.48.v20220620 and OpenJDK 1.8.0_332 (Eclipse Temurin build/release), on Ubuntu 20.04.04 on a machine with 64 cores and 128GB of ram.

This also does not manifest on Jetty 10+ versions of WebSocketClient.  ([same example project](https://github.com/jetty-project/embedded-jetty-websocket-examples), different branch).

Closing as this is a support request for Jetty 9.4.x as [that version is EOL now](https://github.com/eclipse/jetty.project/issues/7958), this cannot be replicated, and this is not a security issue.

Upgrade to Jetty 10.x and try again, if you still experience this issue, open a new issue and we'll address it for Jetty 10. (but we still need a working project you can share that replicates the issue).
