### ISSUE TITLE
SessionTrackingTest intermittant failure

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#83]
I think it could be a race between client seeing the close and the server completing the close.
Test ignored for now.

Failed tests: 
  SessionTrackingTest.testAddRemoveSessions:164->assertServerOpenConnectionCount:178 Session.isopen: WebSocketSession[websocket=JsrAnnotatedEventDriver[websocket=org.eclipse.jetty.websocket.jsr356.server.SessionTrackingTest$EchoSocket@1b4b1ad3],behavior=SERVER,connection=WebSocketServerConnection@E01395AF{endp=SelectChannelEndPoint@5f21eed1{/127.0.0.1:34636<->40254,CLOSED,ISHUT,OSHUT,-,-,7/300000,WebSocketServerConnection}{io=0/0,kio=-1,kro=-1},ios=IOState@158cf7ca[CLOSED,!in,!out,finalClose=CloseInfo[code=1000,reason=null],clean=true,closeSource=REMOTE],f=Flusher[queueSize=0,aggregateSize=0,failure=null],g=Generator[SERVER,validating],p=Parser@11b371a3[ExtensionStack,s=START,c=0,len=2,f=CLOSE[len=2,fin=true,rsv=...,masked=true]]},remote=WebSocketRemoteEndpoint@17efe836[batching=true],incoming=JsrAnnotatedEventDriver[websocket=org.eclipse.jetty.websocket.jsr356.server.SessionTrackingTest$EchoSocket@1b4b1ad3],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.jsr356.JsrSession,outgoing=org.eclipse.jetty.websocket.server.WebSocketServerConnection]]
Expected: is <true>
     but: was <false>

**Comment by sbordet** [comment]
This was fixed in ebee9f12f914e5dfcc312fa3c6c9a7b259b39573.
