### ISSUE TITLE
Embedded jndi does not work

### ISSUE THREAD

**Issue by mortalisk** [eclipse/jetty.project#831]
I can not get the example at http://www.eclipse.org/jetty/documentation/9.4.x/jndi-embedded.html to work. There must be some important factor missing, as my war application cannot find the resources.

**Comment by WalkerWatch** [comment]
Hello,

Can you be more specific? Can you give the code you are using or the output of the errors?

**Comment by mortalisk** [comment]
I think I got it to work now by simpy using EnvEntry in stead of Resource. I'll report back later, but this seems to indicate there is something misleading in the example regaring Resource. What is the difference anyway?

**Comment by WalkerWatch** [comment]
@mortalisk `EnvEntry` entries are used for defining simple values/properties (String, Integer, Boolean) and is the same as making an `<env-entry>` in the `web.xml` of a particular webapp. Additionally, embedded `EnvEntry` calls can be used to overwrite values in a webapp's `web.xml` which can be useful if you do are using a third party webapp and simply want to alter values without having to break open the war file. 

The use of `Resource` is designed to call object (such as the DataSource or MailRef in the example) that **cannot** be defined in a web.xml for a context/webapp. As such, these need to be defined elsewhere in the server. You then have to link these resources in the `web.xml` of a webapp using a `<resource-ref>` which you can read more about [here](https://www.eclipse.org/jetty/documentation/9.4.x/jndi-configuration.html#configuring-resource-refs-and-resource-env-refs). 

I hope this helps. I am going to take a look at making the documentation, especially this example, a bit clearer as several people have had similar questions surrounding JNDI.
