### ISSUE TITLE
[jetty-jspc-maven-plugin] paths of taglib wrongly prefixed with `/WEB-INF/classes`

### ISSUE THREAD

**Issue by achimmihca** [eclipse/jetty.project#8317]
**Jetty version(s)**
[jetty-jspc-maven-plugin](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-jspc-maven-plugin) 9.4.44.v20210927
The previous version 9.4.43.v20210629 does not have this issue.

**Java version/vendor** `(use: java -version)`
jbrsdk-17.0.3

**OS type/version**
Windows 10

**Description**
We have a multi module maven build. A maven project with a taglib is compiled before the final webapp project.

The taglib project has a tld file with following include:
```
<tag-file>
    <name>my-tag-file</name>
    <path>/META-INF/tags/mytaglib/my-tag-file.tag</path>
</tag-file>
```

When compiling this with jetty-jspc-maven-plugin 9.4.44.v20210927 or newer, then it results in an error:
`java.util.concurrent.ExecutionException: org.apache.jasper.JasperException: JSP file [/WEB-INF/classes/META-INF/tags/mytaglib/my-tag.tag] not found`

Cleary, the path got messed up by prefixing it with `/WEB-INF/classes`. As I said, 9.4.43.v20210629 and earlier did not have this issue.

**Comment by achimmihca** [comment]
You can find here a minimal example project to reproduce the issue: https://github.com/achimmihca/multi.module.webapp.demo

To reproduce the issue
- configure the newer version of jetty-jspc-maven-plugin in the pom.xml file
- compile with `jspCompilation` Maven profile

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* https://github.com/eclipse/jetty.project/issues/7958

Does this happen with Jetty 10.x?

**Comment by achimmihca** [comment]
yes, it even occurs in 11.0.11

**Comment by janbartel** [comment]
@achimmihca I'll take a look into this, but I suspect you're going to need to raise this issue with the Apache Jasper folks. The jetty-jspc-maven-plugin just invokes the standard `org.apache.jsper.JspC` class, so I think this is simply the way that `JspC` works. We do expose the `JspC` instance on the plugin, so maybe you can find some configuration option on there that would do what you need. We updated the version of Apache Jasper to `8.5.70` in `jetty-9.4.44` from `8.5.54` in `jetty-9.4.43`, so it might also be worthwhile having a look at the changelists over on the Apache Tomcat site to see if this was a deliberate change on their behalf, and if so why.

**Comment by jackiedlh** [comment]
I met this issue when using jetty 9.4.47

**Comment by achimmihca** [comment]
> raise this issue with the Apache Jasper folks

I think you are right. I found a bug report that sounds related and that could have introduced the issue: https://bz.apache.org/bugzilla/show_bug.cgi?id=64373

> A .tld living in /WEB-INF/classes referencing a tag-file in /META-INF/tags intends it to be loaded from /WEB-INF/classes/META-INF/tags in the same way that a .tag living in a jar is loaded from /META-INF inside the jar.
HOWEVER the tag-file is instead loaded from /META-INF/tags at the root of the webapp, which of course can't be found.
I think this should be resolved, as Tomcat appears to support .tlds in /WEB-INF/classes/META-INF.

I am not sure but I think they afterwards changed Tomcat to prefix something with `/WEB-INF/classes/`, which leads to my issue here.

The [JSP specification section 7.3.1](https://jakarta.ee/specifications/pages/3.0/jakarta-server-pages-spec-3.0.html#identifying-tag-library-descriptors) says:

> Tag library descriptor files have names that use the extension .tld, and the extension indicates a tag library descriptor file. When deployed inside a JAR file, the tag library descriptor files must be in the META-INF directory, or a subdirectory of it. When deployed directly into a web application, the tag library descriptor files must always be in the WEB-INF directory, or some subdirectory of it.

This is what I do. My taglib is placed inside META-INF directory because it is consumed as JAR by the following project.

In my [example](https://github.com/achimmihca/multi.module.webapp.demo), the build works fine [when removing](https://github.com/achimmihca/multi.module.webapp.demo/commit/e1ce9eb992b7ecf8267259d76bebe69ca34cdefd) `taglib.demo/src/main/resources/META-INF/taglib_demo_include.jsp`, i.e., a JSP file in the taglib project itself.
Thus, I think this file does not meet the expectations of the spec, because it is referencing a taglib but in a project where the taglib is ***not yet*** consumed as JAR. The taglib is included as JAR only in the following project, which works.

Luckily, I don't need the file `taglib.demo/src/main/resources/META-INF/taglib_demo_include.jsp`. It was only an attempt to trigger compilation of all tag files in the taglib project. This leads me back to my original issue #8316 (compile taglibs that are not yet included in a JSP file)

However, my findings leave me with the question whether JSP files in taglibs are covered by the specification. Can one create a taglib that includes a JSP file?
It does not seem so because there is a conflict where to put the taglib: `META-INF directory for JAR` vs. `WEB-INF directory for web app`

**Comment by achimmihca** [comment]
I guess this is just how the JSP spec works.
