### ISSUE TITLE
Allow configuring initial queue size per destination

### ISSUE THREAD

**Issue by leonard84** [eclipse/jetty.project#8319]
**Target Jetty version(s)**
9 🥺 

**Enhancement Description**
Currently, the option `org.eclipse.jetty.client.HttpClient#setMaxRequestsQueuedPerDestination` allows us to set the maximum queue size, however this will pre-allocate a `BlockingArrayQueue` with said number, potentially wasting a lot of space for larger numbers.

We would like to propose to add another parameter `org.eclipse.jetty.client.HttpClient#setInitialRequestQueueSizePerDestination` that uses the other constuctor of `BlockingArrayQueue(int capacity, int growBy, int maxCapacity)`.

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* https://github.com/eclipse/jetty.project/issues/7958

Any such feature would be for Jetty 10+

**Comment by marcphilipp** [comment]
Could we have it for Jetty 10+ then, please? 😇

**Comment by joakime** [comment]
@sbordet you had some opinions recently on this.

**Comment by sbordet** [comment]
We don't mind a pull request, but I would not introduce another property, just hardcode the usage of the "growing" constructor with say `capacity=32` and `growBy=32`.
Would that work for you?

**Comment by marcphilipp** [comment]
> Would that work for you?

Yes, I think so. How would the initial capacity be determined in that case?

**Comment by sbordet** [comment]
> How would the initial capacity be determined in that case?

A hardcoded number like `32`.

**Comment by marcphilipp** [comment]
Should we send a PR?

**Comment by sbordet** [comment]
> Should we send a PR?

Sure, give it a go! Thanks! It's enough one PR against the `jetty-10.0.x` branch.

**Comment by marcphilipp** [comment]
👉 #8331
