### ISSUE TITLE
Jetty HttpRequest Memory leak with version from 9.4.18.v20190429

### ISSUE THREAD

**Issue by dhaboda** [eclipse/jetty.project#8349]
I see that high GC count increase of ConcurrentMarkSweep and ParNew stats leading to high CPU usage when I hit "InterruptedException | TimeoutException | ExecutionException" when jetty is not able to write messages over the stream.
Below is the code snippet.. and the stack heapdump shows the "org.eclipse.jetty.io.MappedByteBufferPool" occupied 70% of the heap memory. Below is code snippet and the heapdump details.. please throw some light.

### code snippet ###
	@Override
	public LowLevelHttpResponse execute() throws IOException {
		Http2JettyLowLevelResponse response = null;
		long transactionId = 0;
		try {
			ByteArrayOutputStream baos = null;
			if (getStreamingContent() != null) {
				baos = new ByteArrayOutputStream();
				getStreamingContent().writeTo(baos);
				ContentProvider cp = new ByteBufferContentProvider(getContentType(), ByteBuffer.wrap(baos.toByteArray()));
				req.content(cp);
			}
			transactionId = Http2JettyClientLogger.logRequest(req, baos);
			ContentResponse res = req.send();
			Http2JettyClientLogger.logResponse(transactionId, res);
			response = new Http2JettyLowLevelResponse(res);
		} catch (InterruptedException | TimeoutException | ExecutionException e) {
			log.error("Exception while sending request: {}", e.getMessage());
			if (log.isDebugEnabled()) {
				log.debug("Exception", e);
			}
			Http2JettyClientLogger.logError(transactionId, e);
			throw new IOException(e);
		}
		return response;
	}

### heapdump details###
![image](https://user-images.githubusercontent.com/110129917/181363143-870cbdfd-8661-4198-905d-d9c77ed86f10.png)

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* https://github.com/eclipse/jetty.project/issues/7958

Does this happen with Jetty 10.x?

Jetty 9.4.18.v20190429 is rather old, and is subject to several CVEs.

* https://www.eclipse.org/jetty/security_reports.php

You should upgrade.  Even if it's only to [9.4.48.v20220622](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622), and try again.

If you cannot upgrade, know that Commercial Support for Jetty 9.x is offered via [webtide.com](https://webtide.com) (contact [jesse@webtide.com](mailto:jesse@webtide.com) for details)
