### ISSUE TITLE
Jetty 11 and Micrometer

### ISSUE THREAD

**Issue by tipsy** [eclipse/jetty.project#8357]
## Background

While [migrating Javalin to Jetty 11](https://github.com/javalin/javalin/commit/f7240c5a91a378bce8dc99a30b4ee57863e1e7da), we discovered that Micrometer doesn't support Jetty 11. We made a ticket with the Micrometer team: https://github.com/micrometer-metrics/micrometer/issues/3234, but adding support isn't straightforward.

In short, Micrometer is not able to support Jetty 11 without dropping support for Jetty 9 (not feasible), or creating a separate module (not desirable).

## Feature request

It would be nice if there existed a `jetty-micrometer` or `micrometer-jetty` artifact. The Micrometer team prefers that the Jetty team provides this artifact, and I guess the Jetty team would prefer that the Micrometer team provides this. I don't know which option makes the most sense, but the Javalin team would be very happy if Micrometer and Jetty 11 could work together, so here I am.

**Comment by gregw** [comment]
We are not opposed to having 3rd party integrations in jetty where in makes sense. But hard to say we will do it without much knowledge of micrometer.
 Perhaps the micrometer team could prepare a PR against jetty that would show what a "handed over"  integration would look like.

**Comment by sbordet** [comment]
Many projects are moving forward and dropping support for Java 8 and requiring at minimum Java 11.
Micrometer will have the same problem you report here when they will have to integrate Tomcat 10.1, which requires Java 11, or other projects Micrometer depends on (kafka, etc.).
It's just that Jetty 11 has bitten that bullet before.

Eventually Micrometer could decide to keep the 1.x releases for Java 8, Jetty 9, Tomcat 9, etc. and have a 2.x release for Java 11, Jetty 11, Tomcat 10.1, and so on.

We know the pain of maintaining multiple branches for multiple dependencies and Java versions and we sympathize with Micrometer, but we cannot maintain integrations for other projects for every project out there.

**Comment by tipsy** [comment]
This was resolved by the Micrometer team.
