### ISSUE TITLE
Jetty 12 - is `Resource.copyTo(Path)` for file to file? or dir to dir?

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8397]
**Jetty version(s)**
Jetty 12

**Description**
The API `Resource.copyTo(Path)` has a contract of File to File.
All the way back to Jetty 7.x version of Resource.
However, in Jetty 7, the specific `JarResource` changes the contract to `Resource.copyTo(directory)` allowing the copying of a JAR contents to a directory somewhere else.

Now that we are Path based, we should just drop the `Resource.copyTo()` method and use the `java.nio.file.Files` APIs instead.
The users of the resource know if  it's a file, or directory, or an archive and decide the best path there.

**Comment by janbartel** [comment]
But if you're handed a Resource, you don't know what it is, so you might not know to copy it.

**Comment by joakime** [comment]
> But if you're handed a Resource, you don't know what it is, so you might not know to copy it.

Unfortunately, as the user of the Resource you need to be sure that your Resource is even capable of being copied, or even needs to be copied.
The behaviors in Jetty 9 thru 11 in this regard is also quietly broken in many places (as copyTo() doesn't do anything in a few cases i looked into)

In Jetty 12 if you are handed a resource (which is always a Path btw)

For Jar/Zip/War files, you have 2 ways to represent them in a Resource.
1. As the Jar/Zip/War itself, which is just a File, and is no more special then any other File.
2. As the root directory of the Jar/Zip/War archive (represented via the zipfs layer), this is a Directory, and is no different than any other Directory.

The logic that we need to settle on as a result of this issue ...

If the `Resource` _____  then copyTo(Path) means what?

**Is a File**  

   1. The destination is a directory then you want the file copied to the destination directory (with the same name?)
   2. The destination is a file, then you want the file contents copied to the destination file.
   3. The destination doesn't exist, then what? do we create a directory? or a file? or fail the copyTo?

**Is a Directory**

1. The destination is a directory, then you want the source directory copied to the destination directory.
    What to do with links? (not just unix symlinks, but any links from any filesystem type, even ntfs)
2. The destination is a file, then what?  Do you want to create a JAR/ZIP?  Concat all of the contents of the source into the file?
3. The destination doesn't exist, then what?  do we create a file? or a directory? or fail the copyTo?

**does not exist**

1. This case should throw an exception, as this points to a bug in the user of a Resource, it should never have reached the point of a blind copyTo(Path)

**Is a ResourceCollection**

1. Iterate through each entry in the ResourceCollection applying the directory logic above (as only Directories can be in a ResourceCollection)?
2. Fail? as it's a meaningless operation? I'm in favor of this approach.
3. Leave the user of the ResourceCollection to decide on a per sub-resource basis? (eg: copy only the META-INF/**/*.tld files to destination?)

**Comment by joakime** [comment]
My personal preference for `Resource.copyTo(Path)`, after looking at all of the users of `Resource` in Jetty 12, is the following ...

* File - option 1 only, preserve the name of the file, but now it exists in a new destination directory. (options 2 and 3 are an IllegalArgumentException)
* Directory - option 1 only, and do not follow links when walking the source Resource. (options 2 and 3 are and IllegalArgumentException)
* Does not exist - throw an IllegalStateException always.
* ResourceCollection - throw an UnsupportedOperationException always.

And we should document this behavior in `Resource.copyTo(Path)` javadoc.
