### ISSUE TITLE
Is Jetty Client API request/response getHeaders method also contain request cookies in it or not

### ISSUE THREAD

**Issue by amartya10** [eclipse/jetty.project#8401]
**Jetty version** 11.0.9

**Java version** 11

**Question** In Jetty Client API request/response getHeaders method also contain request/response cookies in it

I am using  org.eclipse.jetty.client.api.Request and  org.eclipse.jetty.client.api.Response 
both have method
  
```
    /**
     * @return the headers of this response
     */
    HttpFields getHeaders();
```
so my question for  request  object getHeaders() also return cookies value in it or we need to call  
```
/**
     * @return the cookies associated with this request
     */
    List<HttpCookie> getCookies();
```

**Comment by sbordet** [comment]
`Request.getCookies()` only returns cookies that you have added via `Request.cookie(...)`.

Cookies that have been set previously are stored in the `HttpClient` and you can access them via `HttpClient.getCookieStore()`.

**Comment by joakime** [comment]
The Jetty Client `Request` object has 2 ways to access `Cookie` headers.
1. The `Request.getCookies()`
2. The `Request.getHeaders()`

If you used `Request.cookie()` to add Cookies, then those will _not_ be present on the `Request.getHeaders()` until you issue a `send()`.
The entries from `Request.getCookies()`  only show those cookies added via `Request.cookie()` method, and will not show cookies added manually in the raw to the Headers of the request.

As for Cookie persistence...

The Jetty Client uses the `java.net.CookieManager` and associated `java.net.CookieStore` which uses the `java.net.HttpCookie` interface for each stored cookie.

As for Cookies on response ...

Using the `java.net.CookieStore.get(URI)` you can access the current cookies for the specific URI you are working with.

Or you can pass the response headers (`Set-Cookie` or `Set-Cookie2`) through ...

* `java.net.HttpCookie.parse(String header)` and get them yourself for working with in the same way as represented in the `java.net.CookieStore`
* a 3rd party library that can actually parse the extra attributes on a Cookie that have meaning to you, but are not tracked by `java.net.HttpCookie` implementation (such as "Same-Site", which has no meaning outside of a Browser client)

**Comment by amartya10** [comment]
@joakime @sbordet 
Thank you for the help 👍🏿 
I got know about how request wok jetty
