### ISSUE TITLE
BlockingArrayQueue drops all contents on drain

### ISSUE THREAD

**Issue by jmakovecki** [eclipse/jetty.project#8414]
**Jetty version(s)**
11.0.11 (latest) and older

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.15" 2022-04-19

**OS type/version**
Linux: Ubuntu 20.04

**Description**
In specific scenarios, `org.eclipse.jetty.util.BlockingArrayQueue` loses all elements on call to `drainTo`.

**How to reproduce?**
- Create a BlockingArrayQueue with `64 * N` elements, where `N > 1` (64 matches `DEFAULT_GROWTH`)
- Make a call to method `int drainTo(Collection<? super E> c, int maxElements)` with any `maxElements` value
- The queue is now empty and no items were added to the collection it was supposed to drain to

The example works as expected if an additional element is added (and then removed), likely by making the queue grow.

Minimal example:
```java
public static void main(String[] args) {
  BlockingQueue<Integer> queue = new BlockingArrayQueue<>();
  for (int i = 0; i < 192; i++) {   // 192 = 3 * 64
    queue.add(i);
  }

  // uncomment this and the example works as expected
//  queue.add(5);
//  queue.poll();

  System.out.println("Source queue size before draining: " + queue.size());
  List<Integer> list = new ArrayList<>();
  queue.drainTo(list, 1);
  System.out.println("Source queue size after draining: " + queue.size() + ", dest list size: " + list.size());
}
```
Output:
```
Source queue size before draining: 192
Source queue size after draining: 0, dest list size: 0
```

**Comment by lorban** [comment]
Also affects 10.0.x and 9.4.x branches.

**Comment by lorban** [comment]
@jmakovecki thank you for the report, this is a genuine bug that must have been an annoyance to track down! Sorry for the loss of time and sanity it may have caused you.

**Comment by jmakovecki** [comment]
It was quite a ride, I'm happy to see it solved :)
