### ISSUE TITLE
OSGI: getting warning messages about missing Require-Capability in jetty-util and jetty-security

### ISSUE THREAD

**Issue by shubhamGoswami88** [eclipse/jetty.project#8421]
!ENTRY org.eclipse.osgi 2 0 2022-08-05 08:49:55.132
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2022-08-05 08:49:55.132
!MESSAGE Bundle initial@reference:file:../../../../eclipse/jetty/jetty-util/9.4.48.v20220622/jetty-util-9.4.48.v20220622.jar was not resolved.
!SUBENTRY 2 org.eclipse.jetty.util 2 0 2022-08-05 08:49:55.132
!MESSAGE Missing required capability Require-Capability: osgi.serviceloader; filter="(osgi.serviceloader=org.eclipse.jetty.util.security.CredentialProvider)".
!SUBENTRY 1 org.eclipse.osgi 2 0 2022-08-05 08:49:55.132
!MESSAGE Bundle initial@reference:file:../../../../eclipse/jetty/jetty-security/9.4.48.v20220622/jetty-security-9.4.48.v20220622.jar was not resolved.
!SUBENTRY 2 org.eclipse.jetty.security 2 0 2022-08-05 08:49:55.132
!MESSAGE Missing required capability Require-Capability: osgi.serviceloader; filter="(osgi.serviceloader=org.eclipse.jetty.security.Authenticator$Factory)"

I am using the java8 with ASM ow2 9.3 and all the updated jars

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* https://github.com/eclipse/jetty.project/issues/7958

Does this happen with Jetty 10.x?

If you cannot upgrade, know that Commercial Support for Jetty 9.x is offered via [webtide.com](https://webtide.com) (contact [sales@webtide.com](mailto:sales@webtide.com) for details)

**Comment by janbartel** [comment]
@shubhamGoswami88 you don't say to what container you're deploying, nor how you're deploying. I think the best thing for you to do is to look at the jetty-9.4 osgi tests, where we deploy all the jetty jars and their dependencies into an Eclipse osgi container. The tests all pass, so perhaps you can compare your setup with that of the tests.  See https://github.com/eclipse/jetty.project/blob/jetty-9.4.48.v20220622/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java#L108
