### ISSUE TITLE
Warning message "scanned from multiple locations" should be configurable

### ISSUE THREAD

**Issue by thomasnikolay** [eclipse/jetty.project#8422]
**Jetty version(s)**
_[Jetty 9.x is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958)_

**Enhancement Description**
The warning message like 

`[INFO] [WARNING] com.gk_software.swee.ses.server.repl.tx.business.jaxb.pos_upload.ses.v1_3_0.package-info scanned from multiple locations: jar:file:///D:/DEV_HOME/WC/hgb/ses/build/sdc/sdc-it/target/tmp/webapp/WEB-INF/lib/com.gk-software.swee.ses.server.mod-repl-tx-server-5.19.3-HF06-b01.jar!/com/gk_software/swee/ses/server/repl/tx/business/jaxb/pos_upload/ses/v1_3_0/package-info.class, jar:file:///D:/DEV_HOME/WC/hgb/ses/build/sdc/sdc-it/target/tmp/webapp/WEB-INF/lib/com.gk-software.swee.ses.server.mod-repl-utx-server-5.19.3-HF06-b01.jar!/com/gk_software/swee/ses/server/repl/tx/business/jaxb/pos_upload/ses/v1_3_0/package-info.class`

should be configurable.

Why it should be configurable?
* the purpose of the jetty is not to check duplicate classes. There are better tools like the extra-maven-enforcer https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html
* Some projects are too big to resolve duplicate class problems
* the user can't decide to ignore the warning when he is sure that there is no problem

**Comment by janbartel** [comment]
@thomasnikolay my thoughts are:

> * the purpose of the jetty is not to check duplicate classes. There are better tools like the extra-maven-enforcer https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html

If you are seeing these duplicate class warnings, it means you have an annotation somewhere with a non-empty `@HandlesTypes`, which requires the servlet container to scan all accessible classes.  If you have duplicate classes then the annotated class may misbehave in strange ways, depending on which one was scanned first. This is just a warning message, it does not fail deployment, so can be ignored.  Many projects only become aware that they have duplicate classes when running with annotation scanning for the first time, and they usually remove the duplicates . 

> * Some projects are too big to resolve duplicate class problems

I can't agree with that proposition. Duplicate classes on the classpath are a problem irrespective of the size of the project. In fact, good control of dependency jars in  WEB-INF/lib is even more crucial for large projects! Failure to fix is just asking for trouble.

> * the user can't decide to ignore the warning when he is sure that there is no problem

As I said, duplicate classes don't fail the deployment, just ignore the log message.

**Comment by thomasnikolay** [comment]
Sorry I forgot to add my use case:

We use the maven-jetty-plugin to run integration tests and we analyze the logs afterwards. Every warning should be checked from my point of view. 

I agree with you that duplicate classes a really bad approach and we solve many of this problems in the past but but we can't solve each duplicate classes problem of different reason. Therefore should the user have the possibility to ignore the the message or add a exclude pattern like https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html to ignore specfific classes.

**Comment by joakime** [comment]
The `jetty-maven-plugin` (that we create) supports proper maven scopes to avoid these issues.

The other `maven-jetty-plugin` projects out there, that you might be using, we cannot say how they do things nor can we support them.

**Comment by thomasnikolay** [comment]
@joakime But the implementation for the "message" is implemented in this project. https://github.com/eclipse/jetty.project/blob/cb127793e5d8b5c5730b964392a9a905ba49191d/jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationParser.java#L563

The warn message is fine for me but it should be configurable, when I am sure there is no problem with the conflict. Otherwise to many warnings leads to ignore warnings.

**Comment by joakime** [comment]
> The warn message is fine for me but it should be configurable, when I am sure there is no problem with the conflict.

If the conflict is at the same classloader level, it's a bug you can fix by correcting what you put in your classloader at that level.

If the conflict is across classloader parent levels, then it's bug you can correct by either correcting what you put in your classloader at one level or the other, or it's a bug you can correct by specifying the scope of scanning.

* If it's the container jars that needs adjusting for scanning scope, use `org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern`
* If it's the webapp jars that needs adjusting for scanning scope, use `org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern`

See Jetty documentation for examples of use: https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-annotations-scanning

**Comment by thomasnikolay** [comment]
We are switching to another server environment for our integration tests. Therefore we can close the ticket.
