### ISSUE TITLE
Java Client: Get server supported protocols

### ISSUE THREAD

**Issue by himanshumps** [eclipse/jetty.project#8424]
**Jetty client version**
11.0.11
**Java version**
17
**Question**
I want to get the protocols supported by server like HTTP 1.1, HTTP/2, SPDY/3, QUIC and others by making an initial connect request. How can I achieve the same using jetty http client (high level or low level) ?

**Comment by joakime** [comment]
You would have to make a request using each of those techniques to know if the server supports them.

There's no protocol to ask for that list in a single exchange.

**Comment by sbordet** [comment]
ALPN would return you that list for TCP based protocols only (not for UDP based ones), but you have to replace some Jetty internals to have access to the list.

In general you should not worry about what protocols the server speaks. 
If the client speaks more than one protocol, the server will choose the protocol to speak anyway.

**Comment by himanshumps** [comment]
Thanks @sbordet and @joakime. That helped
