### ISSUE TITLE
Use of Overlay WebApp Deployer

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#843]
It looks like we have not included this feature since a 9.1 milestone and I understand it is because we never saw a lot of traction with it. @gregw Do we have any plans to resurrect this as part of the distro? If not, I will pull it from the documentation.

**Comment by joakime** [comment]
Issue #114 is a request to bring back the overlay deployer

**Comment by gregw** [comment]
If it did come back, it would probably end up looking different.    I would delete for now.

Note that Docker takes away a lot of the need for the overlay deployer as you can create deployer overlays with docker images.

**Comment by josivan** [comment]
Hello guys. sorry for delaying.

There is two clients who avoid to using resources outside of their network. Then I need to set up a git repository using http://gitblit.com/ and  track issues with http://itracker.sourceforge.net/. As I have two clients using the same type resource I'd like to reuse (with overlay) both war in different contexts.

**Comment by jmcc0nn3ll** [comment]
@josivan Have you looked at using Docker for that? You could setup a base image with that shared resource and then produce the other two images off of that, then you just fire up the docker instance for each client.  It isn't a panacea but it works really well for many of these use cases we have seen thus far.

**Comment by joakime** [comment]
Or, use the features in Servlet 3 such as web-fragment's to add-on your extra features to the base webapp.

You would essentially create a jar file which represents your add-on's and then add that to the base webapp. (course, the base webapp would need to be at Servlet 3 as well)
