### ISSUE TITLE
Jetty 12 : `Handler.Collection` does not propagate `Server` to handlers in expected way

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8442]
**Jetty version(s)**
Jetty 12

**Description**

In Jetty 12, if you use the jetty-core `org.eclipse.jetty.server.Handler$Collection` the `.setHandlers(List)` does not propagate the `Server` correctly.

Example code.

``` java
WebAppContext context = new WebAppContext();
context.setContextPath("/");
context.setBaseResource(context.getResourceFactory().newResource(staticBase));
server.setHandler(new Handler.Collection(context, new DefaultHandler()));
server.start();
```

The `DefaultHandler.setServer(Server)` never gets called with a valid Server instance.

This is because the internal `Handler.Collection` processing does it's `handler.setServer(server)` far too early.
AFAICT, this seems to be the only Handler implementation with this bug.

**Comment by gregw** [comment]
fixed by a0d6f42

**Comment by lorban** [comment]
@gregw sorry, I've had to revert these changes in https://github.com/eclipse/jetty.project/pull/8452 because they broke the build.

**Comment by gregw** [comment]
@lorban no probs.... any hint to how the build was broken?

**Comment by gregw** [comment]
This was fixed during Handler restructure in 12.
