### ISSUE TITLE
Jetty 12: review `resolve()` and `getPath()` contracts in `ResourceCollection` and `MemoryResource`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#8443]
**Jetty version(s)**
12

**Description**
Review how `resolve()` and `getPath()` are supposed to behave when directory and non-directory resources are part of a `ResourceCollection`, and for `MemoryResource` in general. Or if we want those `Resource` implementations at all.

**Comment by lorban** [comment]
My personal opinion is that neither `resolve()` nor `getPath()` should ever return null, but I'm open to different opinions.

**Comment by gregw** [comment]
If we could arrange for `getPath()` to never return null, then we would not need the resource class and could just use `Path`.    However, that fails on the `ResourceCollection` issue that we are required to provide aggregate base resources and to do so without necessarily extracting.

However, we could have that a non-directory resource would always return a path.

Having resolve never return null is doable, but it may be that we would need to return an empty or bad resource from some resolves (or /dev/null if we must have a path).
