### ISSUE TITLE
I'd like to open the jetty server log data reception window, how to do?

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#8445]
**Jetty version**
9.4.48.v20220622
and 
11.0.10
**Java version**
1.8
11
**Question**
Our scenario is to transmit binary data to the cloud by the client, occasionally find client, data transmission through the client log found distal window is full and no update, so the data transmission will not come, but from the jetty service, everything is normal, **I'd like to open the jetty server log data reception window, how to do?**

**Comment by gregw** [comment]
"distal window"?   Can you clarify what you mean? Is this the TCP/IP flow control window or a HTTP/2 window?  If the latter, is it the connection or stream window?

I'm also unclear if you are having this problem with the jetty client or server or both?

**Comment by xinguangduan** [comment]
hi @gregw ,  Sorry, I did not describe clearly, I think it should be a HTTP/2 stream window. Our client is written in C language, based on Nghttp2 library implementation of Http2 client, from Nghttp2 log show the “stream_remote_window_size" is not updated. the log of NgHttp2 for example as below:

`stream_id:27,session_remote_windows_size:2147406735,stream_remote_window_size:65536,remote_max_frame_size:16777215`

**Comment by xinguangduan** [comment]
any body can answer me?

**Comment by sbordet** [comment]
There is not enough information. The log you posted shows that the windows are open.
I don't think there is a problem with Jetty's HTTP/2 windows.

**Comment by xinguangduan** [comment]
@sbordet, I don't say this is problem, I just want to known how to open the jetty logs for HTTP/2 windows.

**Comment by sbordet** [comment]
The HTTP/2 flow control window on the Jetty server is opened by consuming the data that is received.

Please see the documentation about the low-level API usage here: https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http2-flow-control.

If you use Servlets, it is enough that you read the request content until you see EOF. The Jetty implementation will take care of enlarging the flow control window.

If you think you should do this manually from the application, you are mistaken, exactly like applications should not care about sending TCP ACKs, the implementation does it for them.

**Comment by joakime** [comment]
@xinguangduan if you are asking about Logging in Jetty? then I can answer.

In Jetty 10+ the slf4j-api logging facade is used by Jetty to generate logging events.

This means if you want to see these events, you will use any slf4j-api supported logging implementation (which is quite an extensive list) to configure the events and the output to suit your needs.

There are many named loggers within Jetty, but I think you are wanting the http2 specific logging events, so what you are probably looking for is that the named logger parent `org.eclipse.jetty.http2` which will include all http/2 specific logging events.

If you use your logger implementation of choice, just set that named logger to DEBUG level to see all of the http2 specific logging events in the output style that you want (See your chosen logger implementation for details)

**Comment by xinguangduan** [comment]
@joakime  thanks a lot, I got it.
