### ISSUE TITLE
Improve blocking IO for data rate limiting.

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#845]
Whenever a Servlet IO operation is about to block (read or write), calculate the effective data rate achieved so far and if it is below a threshhold configured in HttpConfiguration, then IO operation is failed with an exception.

This will not apply to async operations.

**Comment by gregw** [comment]
An alternative suggestion, for the read side is:
- when a request header is received, if it has a body adjust the idletimeout to a new value from HttpConfiguration
- when the idletimeout fires, calculate the achieved data rate for reading the body.
- if data rate is too low, do normal IdleTimeout handling.

Issues with this approach are:
- need to take steps to make sure the low idleTimeout does not apply writes.
- does not work for the write side, as data rate on write side has to be measured for the duration of writes and not the duration of the response generation - ie generation can be slow.

**Comment by gregw** [comment]
For the write side,  without file mapped buffers, writes are typically sliced to the buffer size, which is 32KB by default, which with the default idle timeout of 30s gives a minimal data rate of approx 1KB/s 

To detect lower data rates, the output buffer size needs to be reduced.
To improve the detection time, both the output buffer size and the idle timeout need to be reduced.  To detect a data rate of <1KB/s in 5s, the output buffer size would need to be 5KB and the idle timeout 5s.

Such small output buffers can greatly effect server efficiency.      So we really need a better way on the write side.

Note also that with file mapped buffers, write buffers can be very much larger that 32KB

But also not that the call to flush is not required to write all of the data at once and will return to the WriteFlusher if it cannot write all the data - So the WriteFlusher could do some smart data rate detection.

**Comment by sbordet** [comment]
@gregw the write side must be above the `WriteFlusher`, since in HTTP/2 it will be flow controlled (plus it's going to write data for different requests).

**Comment by sbordet** [comment]
@gregw also, I think we should only worry about blocking I/O (at least for now). Writing a mapped buffer is typically done asynchronously, and only using internal Jetty APIs.

For blocking write I/O we already have `HttpConfiguration.blockingTimeout`, perhaps we can use that.

Remains the problem of how we measure write rate. Both HTTP/1.1 and HTTP/2 should be able to track how many bytes have been actually written, so perhaps we need some abstract method in `HttpTransport`.
