### ISSUE TITLE
Review usage of ResourceFactory for favicon and stylesheet

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8450]
**Jetty version(s)**
12

**Description**

Recent CI builds of [12 have failed](https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.0.x/423/tests) because mounts have been left for the server.jar for favicon.ico.   This should have been closed when the server was stopped, so that is the first issue.   But moreover, the mechanism is too expensive to use for favicon.ico, as we need not hold an entire jar in memory as a zipfs when the bytes we need are available via the classloader.

**Comment by joakime** [comment]
This has been addressed over a few PRs.
Most recently with @lachlan-roberts PR #9043
