### ISSUE TITLE
Fix ee10 and ResourceHandler to make them serve jetty-dir.css resource

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#8456]
**Jetty version(s)**
12

**Description**

Here's the current state about which of the static content serving mechanisms (ee9 `DefaultServlet`, ee10 `DefaultServlet` and `ResourceHandler`) can serve jetty-dir.css:

|                            |  jetty-dir.css |
| ---------------------- |  --------------- |
| ee9                      | Y                 |
| ee10                    | N                |
| resource handler | N                |

As a side note, by design, `DefaultHandler` is meant to serve favicon while `ResourceHandler` and both `DefaultServlet`s are supposed to serve only jetty-dir.css.

**Comment by lachlan-roberts** [comment]
done
