### ISSUE TITLE
Jetty 9.2.17 deadlocks in HttpChannelState when using Async loggger.

### ISSUE THREAD

**Issue by zolyfarkas** [eclipse/jetty.project#848]
Thread 1: This thread is blocked because because the LOG message queue is full.
Name: main
State: WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7bb0e8ce
Total blocked: 12  Total waited: 22

org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:89)
org.eclipse.jetty.server.HttpChannelState.handling(HttpChannelState.java:174)
- locked org.eclipse.jetty.server.HttpChannelState@165aed7e
  org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:283)
  org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)

Thread 2: This thread is the consumer thread and is blocked while writing HttpChannel.toString....

Name: ASYNC_LOGGER
State: BLOCKED on org.eclipse.jetty.server.HttpChannelState@165aed7e owned by: pjetty0 - /service/chars?nrBytes=13
Total blocked: 24  Total waited: 46

Stack trace: 
org.eclipse.jetty.server.HttpChannelState.getState(HttpChannelState.java:111)
org.eclipse.jetty.server.HttpChannel.toString(HttpChannel.java:510)
org.spf4j.io.ObjectAppender$1.append(ObjectAppender.java:37)
org.spf4j.base.Slf4jMessageFormatter.safeObjectAppend(Slf4jMessageFormatter.java:219)

One way to resolve this is to get all logging statements outside of the synchronized blocks since a log statement can potentially block... another way is to have aHttpChannel.toString that cannot potentially block...

**Comment by joakime** [comment]
so you are using slf4j and [spf4j](http://zolyfarkas.github.io/spf4j/) together?

What is the slf4j implementation you are using? (if java.util.logging, consider using something more performant)

**Comment by zolyfarkas** [comment]
I am using slf4j 1.7.21 + logback 1.1.7.
I am only using a message formatter from spf4j to do some custom message formatting.

the important things are:

when running in debug log mode:
1) jetty somewhere logs a HttpChannel object instance. 
2).... lots of other logs (enough to fill the logback async logger queue
3) jetty logs a debug message in HttpChannelState:111 since queue is full this log statement blocks while holding onto the monitor of the HttpChannelState object.
4) the AsyncLogger tries to log the log message from 1) and as part of formatting the message, calls HttpChannel.toString which calls HttpChannelState.getState which will try to acquire the monitor of HttpChannelState. Unfortunately this monitor is hold onto at step 3) forever. (the AsyncLogger is stuck now and it is the only guy who concumes messages from the queue...)

hope it is a but clearer now...

**Comment by joakime** [comment]
@gregw this is an old issue, is it still relevant?
I can't see how, in the current `jetty-9.4.x` branch, that this could be an issue.

**Comment by gregw** [comment]
ack
