### ISSUE TITLE
Jetty 12 documentation artifact not releasing

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#8489]
https://repo1.maven.org/maven2/org/eclipse/jetty/documentation/jetty-documentation/12.0.0.alpha0/

the -html artifact is not getting included with the release process, we'll need to sort that for alpha1 so we can get the website process ironed out

**Comment by sbordet** [comment]
It is nice (and IMHO important) to be able to update/clarify the documentation online _without_ making a new release.

So the documentation toolchain should not rely on Maven Central final artifacts, just the source code.
Rebuild it locally and re-deploy it would be my preference.

**Comment by jmcc0nn3ll** [comment]
agreed, the antora work I am doing now would operate in this fashion for 9, 10, 11, and 12
