### ISSUE TITLE
Question: Do websocket endpoints need to allow for parallel message processing?

### ISSUE THREAD

**Issue by tbartley** [eclipse/jetty.project#850]
Hi,

I'm seeing a situation where, for a single session, the client send my Jetty-hosted JSR359 server endpoint two messages in sequence (obviously - since it's just a single TCP connection). The behaviour I see is that both messages are processed in parallel simultaneously by different threads in Jetty. This was unexpected for me - should it have been? This is in 9.3.11, btw.

Cheers,

Tim

**Comment by joakime** [comment]
If the message type is streaming based (Reader / InputStream), then yes.
If the message type is non-streaming, then no.

The threading works like this ...

- [WebSocket Endpoint Thread] reads raw bytes from network
- [WebSocket Endpoint Thread] parses raw bytes
- [WebSocket Endpoint Thread] each fully parsed websocket frame is notified via IncomingFrames chain
- [WebSocket Endpoint Thread] if a frame is BINARY or TEXT, then a determination of the endpoint calling method is made to determine the mode of operation (whole, partial, streaming, decoded or not, etc..)
- [WebSocket Endpoint Thread] if the operation type is streaming, an appropriate stream is created and the endpoint @OnMessage method is called via a dispatched thread (required to be a dispatch, both for the normal operations of the thread and also declared in the JSR356 spec this way).
 - [Endpoint OnMessage Thread 1] the endpoint now starts to read from the stream
- [WebSocket Endpoint Thread] next parse occurs
- [WebSocket Endpoint Thread] if the incoming frame is a CONTINUATION, append this payload to the stream created earlier.   If the stream is full, and the endpoint hasn't read enough yet, block on the payload offer to the stream.
- [WebSocket Endpoint Thread] next parse occurs
- [WebSocket Endpoint Thread] a new BINARY or TEXT occurs, same determination of endpoint calling method is made.
 - [Endpoint OnMessage Thread 2] the endpoint now starts to read from the stream

As you can see, streaming data types are special, and really only useful for large messages (think 1MB+).   

We used to have a concurrency rule that only allowed the processing of the next message if the the @OnMessage method returned.  But that proved problematic for async processing libraries, and streaming libraries (think webrtc).
We also hit problems with CONTROL frames with this approach.
Then we moved it to the stream close event, but many endpoints never closed the stream. (that was a short lived mode, 1 release)
Then we moved it to the stream EOF (on offer), and that's where it is now.

**Comment by tbartley** [comment]
Thanks Joakime for the detailed explanation. I'll think about changing to non-stream based message handling. 

Cheers,

Tim

**Comment by bufistov** [comment]
Hi @joakime,

In our application a browser creates single websocket session and sends all the user requests to server via it. Sometimes browser might send few close-in-time requests each one takes few seconds to complete. I see that jetty websocket server (9.4.11.v20180605) executes all the requests sequentially and I understood from your explanation that this expected. Is that right?

What is the right way to actually parallelize each message handling and avoid potential 30 seconds waiting time of the user in our case?

**Comment by joakime** [comment]
Websocket is a protocol that defines framing for a series of sequential messages.
parallel processing of messages would mean you are using multiple websocket connections.
