### ISSUE TITLE
infinispan projects have been moved in 12.0.x, so renaming is needed.

### ISSUE THREAD

**Issue by MoonLord-LM** [eclipse/jetty.project#8545]
[ infinispan ] projects have been moved, so renaming is needed.

_Originally posted by @MoonLord-LM in https://github.com/eclipse/jetty.project/issues/8542#issuecomment-1235964809_

**Comment by MoonLord-LM** [comment]
https://github.com/eclipse/jetty.project/pull/8542/commits/d4cd67c1c3183af325ca57a1c4e90842c7d953c4

**Comment by olamy** [comment]
PR merged.
thanks!
