### ISSUE TITLE
`getRequestURL` can append "null" if `getRequestURI` is unspecified in an authority-form request-target

### ISSUE THREAD

**Issue by electrum** [eclipse/jetty.project#8578]
**Jetty version(s)**

9.4.x
10.x

**Description**

When upgrading to Jetty 9.4.48, we see that `AbstractProxyServlet.rewriteTarget()` calls `clientRequest.getRequestURL()` which results in `https://localhost:50393null` due to `getRequestURI()` returning null (since the URI path is null). While this `Request` behavior seems to have existed for ~10 years and is not the root issue, it still seems to be a bug.

**Comment by joakime** [comment]
Opened PR #8579 to solve for `jetty-9.4.x`.

Attempting to replicate in `jetty-10.0.x` now ...

**Comment by joakime** [comment]
Opened PR #8580 to solve for `jetty-10.0.x` (this will be merged to `jetty-11.0.x` once approved/merged)

**Comment by joakime** [comment]
Complete.

Merged from 9.4.x through to 12.0.x
