### ISSUE TITLE
Keystore as a Truststore

### ISSUE THREAD

**Issue by nickbabcock** [eclipse/jetty.project#858]
With `_validatePeerCerts=true`

In 9.2.13.v20150730, I could specify a key store (via `setKeyStorePath`) but omit a trust store, in which case the key store would also become the trust store (courtesy of [`checkKeyStore`](https://github.com/eclipse/jetty.project/blob/jetty-9.2.13.v20150730/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L985-L1029))

I tested as far back as 9.3.5, but as of 9.3.11 this behavior is not maintained and when validating the trust store the following exception is generated:

```
! java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
! at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
! at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:157)
! at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:130)
! at org.eclipse.jetty.util.ssl.SslContextFactory.getTrustManagers(SslContextFactory.java:1116)
```

The fix is to explicitly create a trust store with anchor CA. Setting the trust store to the same path as the key store _does not_ work (same error)

`checkKeyStore` was removed in 5ed2f84d06f

I'm assuming this behavior is still supported based on the `testNoTsFileKs` and `testNoTsSetKs`, but please let me know if otherwise.

**Comment by nickbabcock** [comment]
This can be replicated by using the 9.3.11 distribution and modifying `jetty-ssl-context.xml` and adding

```xml
  <Set name="ValidatePeerCerts"><Property name="jetty.sslContext.validatePeerCerts" default="true"/></Set>
```

Results in the mentioned error.

**Comment by joakime** [comment]
I wonder if #1468 would help things here as well?
@gregw thoughts?

**Comment by sbordet** [comment]
The behavior of using the KeyStore as the default TrustStore has been restored by fixing #901.
