### ISSUE TITLE
Indicate units of HttpClient properties

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#8591]
**Jetty version(s)** 11.0.1

**Enhancement Description**

For example, I assume that `HttpClient.setRequestBufferSize()` and `HttpClient.setResponseBufferSize()` refer to a value in bytes but it would be helpful for the Javadoc to state this explicitly. Alternatively, rename the parameter name from say `requestBufferSize` to `requestBufferSizeInBytes`.

**Comment by sbordet** [comment]
Care to contribute a pull request? Against `jetty-10.0.x`, we will merge forward. Thanks!

**Comment by cowwoc** [comment]
Done

**Comment by joakime** [comment]
Might want to link the PR here.
Looks like you went above and beyond with PRs for all three active branches.
We really only need `10.0.x` and we'll merge forward.

**Comment by cowwoc** [comment]
@joakime Here you go: https://github.com/eclipse/jetty.project/pull/8728

Sorry for the other PRs. I'll close the extra ones.
