### ISSUE TITLE
Add WAR project deployer for jetty-maven-plugin

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#86]
migrated from Bugzilla [#293394](https://bugs.eclipse.org/bugs/show_bug.cgi?id=293394)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _7.0.0_ on platform _PC_
Assigned to: Jan Bartel

On 2009-10-27 03:29:22 -0400, Greg Wilkins wrote:

> The jetty-maven plugin can only run a single web project, and it is sometimes desirable to run multiple contexts in development mode.
> 
> A deployer provider could be developed that scans a configured set of maven projects and deploys the webapps described by the poms.  This could either be from deployed artefacts, or in development mode - from the unassembled source of the project (like the jetty-maven-plugin).

On 2011-09-20 12:28:36 -0400, Joakim Erdfelt wrote:

> Moving importance down to Enhancement.

**Comment by joakime** [comment]
Already implemented in `jetty-9.4.x` branch as `deploy-war` goal.
