### ISSUE TITLE
is Max Connection property of connection pool could be changed dynamically without impacting ongoing connection in live traffic processing

### ISSUE THREAD

**Issue by navalgoyal** [eclipse/jetty.project#8608]
**Jetty version**
9.4.43v20210629

**Java version**
Jdk 1.8

**Question**
We are using Jetty client for sending Http2 traffic to outside system where we are setting max connection property of connection pool. Initially the value is set to 5 connection and client is opening 5 connection to send traffic. after some time we need to change the value of max connection to 3. can this be possible without reinitializing the connection pool??

our use case is as below:

When we use round robin and  change the max connection value of connection pool from 5 to 3, client could dynamic reduce 2 of the 5 established links(keep 3 already existing connection and remove any 2 connection) and also this should not impact ongoing traffic and there should not be delay or loss of request while executing the above use case.

same in case we increase the value of max connection from 5 to 8. In this case only 3 new connection should be created and existing connection should be reused.

Kindly suggest the way forward in Jetty client.

**Comment by sbordet** [comment]
This is currently not supported.
