### ISSUE TITLE
Update build for Java 19

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#8613]
**Jetty version(s)**
10+

**Java version/vendor** `(use: java -version)`
19

**Description**
In Java 18, some API that we use was incubating but available without preview.
In Java 19, these APIs have moved to preview, so we need to update the POM files with the right profiles, especially the `quic-quiche` module that relies on the `foreign` APIs.

@lorban @olamy can you please look into this?

**Comment by lorban** [comment]
Regarding the Foreign binding of Quiche, it's not going to be an easy change. The package changed from `jdk.incubator.foreign` to `java.lang.foreign` but there were other breaking API changes too.

I'm going to run `jextract` again on the quiche header file and update our current binding to make it work with JDK 19. But this new binding should replace the existing one; we don't want to keep both the incubator and final bindings, right?

**Comment by lorban** [comment]
Interesting: jextract is now an [open-source project](https://github.com/openjdk/jextract/) but I could not find a pre-built binary. Building it myself is going to need a slightly bigger time investment.

**Comment by sbordet** [comment]
@lorban yes we want to keep the Java 17 version, which I think is also valid for 18, and the Java 19 version.

They will be different modules under `jetty-quic-quiche` parent.

We have done this for years for ALPN for almost every JDK version, we can do 2 modules for foreign with the proper POM config and Jetty module config.

**Comment by lorban** [comment]
@sbordet unfortunately, our JDK 17 impl is not compatible with JDK 18. Maybe adapting it wouldn't take much but it definitely isn't source nor binary compatible.

**Comment by olamy** [comment]
we are now building with 21 :)
