### ISSUE TITLE
Add feature to force Chunked Transfer-Encoding on all Content-Length-less responses regardless of Connection close state

### ISSUE THREAD

**Issue by frankgrimes97** [eclipse/jetty.project#864]
https://github.com/eclipse/jetty.project/issues/805#issuecomment-242096505

**Comment by joakime** [comment]
This is highly undesirable in the vast majority of use cases.
If this were added, it would be an optional feature that could be enabled on the server. (not specific to the request / endpoint / webapp / context / etc)
