### ISSUE TITLE
Jetty 9.3.11 disables the SSLv2Hello protocol

### ISSUE THREAD

**Issue by johngmyers** [eclipse/jetty.project#866]
My Jetty embedded code creates an HTTPS server with a `SslContextFactory` obtained from the `SslContextFactory(String)` constructor. In 9.3.10 and previous, the SSLv2Hello protocol would be enabled per the JSSE default for servers. As of 9.3.11, the SSLv2Hello protocol is disabled.

Initial diagnosis shows that this is because the 9.3.10 `SslConextFactory.doStart()` method obtains the enabled protocols from the SSLEngine, whereas 9.3.11 obtains it from the SSLContext. There is no way for the SSLContext to represent JSSE's differing protocol enable defaults for client versus server.

**Comment by joakime** [comment]
`SSLv2Hello` is considered a vulnerable protocol and is excluded by default in Jetty.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.3.11.v20160721/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L249-L254

If you want to use this vulnerable protocol, you will have to redeclare the `SslContextFactory.setExcludedProtocols()` list.  (Do not simply add it as an included protocol.  that will not work.  excludes win over includes on `SslContextFactory`)

> Also be aware, that your `${JAVA_HOME}/jre/lib/security/java.security` might have `SSLv2Hello` or `SSLv3` (which disables SSLv3 and below) in its `jdk.tls.disabledAlgorithms` list.

**Comment by johngmyers** [comment]
@joakime there are several inaccuracies in your response:

`SSLv2Hello` is not excluded, as I verified by examining the state of the `SslContextFactory._excludeProtocols` field in the debugger. As I stated in the original report, the `SslContextFactory` was obtained from the `SslContextFactory(String)` constructor.

As the `_excludeProtocols` list is already empty, calling `SslContextFactory.setExcludedProtocols()` will have no effect. As I stated in the original report, my initial diagnosis is that this is due to the change between 9.3.10 and 9.3.11 in how `SslContextFactory.doStart()` obtains the list of the JSSE provider's default enabled protocols.

The `SSLv2Hello` protocol is not vulnerable when enabled for a server socket. This would be why the SunJSSE provider [enables SSLv2Hello by default for servers](https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SunJSSE_Protocols).

**Comment by joakime** [comment]
Looks like we have 2 bugs then.
This one (which I'll leave @sbordet and @gregw to address), and the broken protocol exclusions.

SSLv2Hello has been marked excluded since jetty-9.2.4.v20141103 (commit 90e9cfc535dc992b00cb4af21eb7a1ef34da433b)

While its true that `SSLv2Hello` specifically has no vulnerability on servers (merely an issue for clients), its also included in the general industry recommendations to disable all SSLv3 (and below) protocol features.

**Comment by joakime** [comment]
Notes for @gregw and @sbordet ...
Looking back that the commits, there were 2 different attacks that triggered the `SSLv2Hello` server exclusion on Jetty.  The downgrade attack, and the POODLE attack.

**Comment by joakime** [comment]
(just tested this) If we leave `SSLv2Hello` available, then the ssllabs.com will report failures in 3 attacks.  Downgrade, POODLE, and DROWN.

**Comment by joakime** [comment]
One more note, Java 7 disabled `SSLv2Hello` (server and client), then Java 8 quietly re-enabled it for Server only.

See: http://www.oracle.com/technetwork/java/javase/compatibility-417013.html

**Comment by joakime** [comment]
After a talk with the other devs in Jetty, the consensus is this ...

 - `SSLv2Hello` will not be enabled by default in Jetty, for either server or client.
 - If you (or anyone else) wants to use `SSLv2Hello`, then you'll have to configure your SslContextFactory to enable that protocol for your specific use case.
 - If you have different needs (server vs client), then you use 2 different SslContextFactory instances (one for server, and one for client)
 - If you have a demonstrable bug about the inability to enable `SSLv2Hello` for your specific instance, then we would like to see it, and address it specifically (we'll happily reopen this issue to address that).
