### ISSUE TITLE
jetty and 'hot-deploy', not freeing diskspace?

### ISSUE THREAD

**Issue by brianreichert** [eclipse/jetty.project#867]
We're employing the 'hot deploy' feature in jetty to redeploy an updated webapp.

What we're observing is that the redeployment doesn't discard the disk resources of the prior deployment.

This is easily reproducible with stock jetty code:

In one window, spin up the demo-base app, with hot-deploy set:

  # cd /usr/jetty-distribution-9.3.8.v20160314/demo-base/
  # java -jar ../start.jar jetty.deploy.scanInterval=1

In another window, isolate the process ID, and show the current count of deleted files, and the usage of the /tmp partition.

  # lsof -i :8080
  COMMAND  PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
  java    1463 root   89u  IPv6 5047191      0t0  TCP *:webcache (LISTEN)

  # lsof -nP +L1 | grep '(deleted)' | grep 1463 | wc -l
  0
  # df /tmp
  Filesystem     1K-blocks   Used Available Use% Mounted on
  /dev/sda2        2519792 470052   1921740  20% /
  # lsof -nP +L1 | grep '(deleted)' | grep 1463 | wc -l
  0

And periodically trigger hot-deploy, and observe the presence of deleted files that the PID is still holding a reference to, and the increase of utilization of the /tmp partition:

  # touch webapps/test.xml
  # lsof -nP +L1 | grep '(deleted)' | grep 1463 | wc -l
  7
  # df /tmp
  Filesystem     1K-blocks   Used Available Use% Mounted on
  /dev/sda2        2519792 470908   1920884  20% /

  # touch webapps/test.xml
  # lsof -nP +L1 | grep '(deleted)' | grep 1463 | wc -l
  14
  # df /tmp
  Filesystem     1K-blocks   Used Available Use% Mounted on
  /dev/sda2        2519792 471764   1920028  20% /

  # touch webapps/test.xml
  # lsof -nP +L1 | grep '(deleted)' | grep 1463 | wc -l
  21
  # df /tmp
  Filesystem     1K-blocks   Used Available Use% Mounted on
  /dev/sda2        2519792 472620   1919172  20% /

These count of deleted-but-referenced file keeps increasing, and more of /tmp keeps getting consumed.

All of the deleted files are of the pattern:

  /tmp/jetty-0.0.0.0-8080-test.war-_test-any-XXXXXXXXXXXXXXXX.dir/...

Does anyone else see this behavior?

Again, details of our environment:

Details of our environment:

  jetty-distribution-9.3.8.v20160314

  OpenJDK Runtime Environment (build 1.8.0_71-b15)

  CentOS release 6.7 (Final)

  # uname -r
  2.6.32-573.18.1.el6.x86_64

**Comment by joakime** [comment]
Standard URLConnection caching behavior.

A `jar:file://` URL will use the implementation `sun.net.www.protocol.jar.JarURLConnection` which takes uses a cache implemented in `sun.net.www.protocol.jar.JarFileFactory`, that cache is what's holding a reference to the jar files you see as `(deleted)`.

This is the way Java operates, it is normal, and not a bug in Jetty or Java.

You can use `URLConnection.setUseCache(false)` to prevent use of that cache.

Or you can use the following snippet.

**demo-base/etc/disable-url-caches.xml**

```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Set class="org.eclipse.jetty.util.resource.Resource" name="defaultUseCaches">false</Set>
</Configure>
```

**Example of usage**:

```none
# Terminal 1
[demo-base]$ java -jar ../start.jar jetty.deploy.scanInterval=1 etc/disable-url-caches.xml 

# Terminal 2
$ lsof -i :8080
COMMAND   PID   USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
java    17220 joakim  110u  IPv6 1027261593      0t0  TCP *:webcache (LISTEN)

$ lsof -nP +L1 | grep "(deleted)" | grep 17220 | wc -l
0

$ touch webapps/test.xml 

$ lsof -nP +L1 | grep "(deleted)" | grep 17220 | wc -l
0
```

**Comment by joakime** [comment]
Some more links for you ...

- http://stackoverflow.com/a/19125855/775715
- https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02419.html
