### ISSUE TITLE
spring boot app does not deploy to jetty 11 but does so in jetty 10

### ISSUE THREAD

**Issue by ramvem** [eclipse/jetty.project#8680]
My spring boot war doesn't get initialized though Jetty reports the app as STARTED. This happens in jetty 11.0.12 but not in 10.0.12. 

Symptom is the war file is detected, and reported as "STARTED" in localhost:8080, but the spring initialization hooks are not invoked and servlet mappings are not set up. When I click on the application link on localhost:8080 I expect to be taken to the default page of the app (well, should 404 for me) but instead I see the directory listing with META-INF and WEB-INF. This tells me the app initialization is not taking place.

I stripped out everything to have a minimal reproducible case, and am posting a simple gradle project with 3 java files -- a controller, ServletInitializer, and SpringBootApplication.

You can repro by building the war with "gradle :be1:war" and copy the resulting be1-0.0.2-SNAPSHOT-plain.war to the webapps/ directory.

My jetty-base is set up via: java -jar $JETTY_HOME/start.jar --add-module=http,jmx,server,requestlog,logging-log4j2,deploy,websocket

Thanks
[bfshell.tar.gz](https://github.com/eclipse/jetty.project/files/9701688/bfshell.tar.gz)

-Ram

**Comment by ramvem** [comment]
Attaching console log for jetty 10 vs jetty 11 startup
[jetty-11-startup.log](https://github.com/eclipse/jetty.project/files/9701720/jetty-11-startup.log)
[jetty-10-startup.log](https://github.com/eclipse/jetty.project/files/9701721/jetty-10-startup.log)

**Comment by joakime** [comment]
spring-boot (at least the one based on Spring versions before Spring 6.x) are based on the old school `javax.servlet.` namespace.

Spring 6.x (in dev now) will update to use the new Jakarta EE namespace of `jakarta.servlet.*` (which is a requirement for Jetty 11)

See: https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6
