### ISSUE TITLE
Make QuicServerConnector respect configured key store instances

### ISSUE THREAD

**Issue by neoxpert** [eclipse/jetty.project#8694]
**Jetty version(s)**
10+

**Enhancement Description**

As of now the `QuicServerConnector` does not respect a configured key store instance that might have been set on the respective `SslContextFactory` using `setKeyStore`. This makes the use of a in-memory managed key store really cumbersome, especially as it works without problems on other connectors like the http or http2 ones.

It would really help if a set key store instance would be used or at leat an exception is thrown on startup, if the currently used key store resource is not set instead of running into a NPE.

**Comment by sbordet** [comment]
Unfortunately, not much we can do at the moment, since we depend on Quiche, and Quiche can only read PEM files from the file system.

**Comment by neoxpert** [comment]
That's clear to me. If I get it right, in order to extract the key pair and store it in the temp folder, so that Quiche can use it, right now the key store is loaded from the file system using the key store resource / key store location of the SslContextFactory.

Why not just extract the key pair from a already loaded key store if one has been set on the SslContextFactory instance. In the end this would just be a shortcut to the current implementation as the QuicServerConnector would not have to deal with loading the key store to be used. In the end that would offer the same convenience using a loaded key store for the HTTP3ServerConnector like it is available on the ServerConnector when setting up http2/http1.

**Comment by joakime** [comment]
Got an example, in Java code, of extracting a valid PEM from a KeyStore object?  
(Keep in mind that many folks use SslContextFactory without an actual keystore file, but create the KeyStore object directly and give it to the SslContextFactory)

**Comment by neoxpert** [comment]
The required code to read and export a certificate from a key store as PEM is already contained within the constructor of the [SSLKeyPair ](https://github.com/eclipse/jetty.project/blob/cb127793e5d8b5c5730b964392a9a905ba49191d/jetty-quic/quic-quiche/quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/SSLKeyPair.java) class and its methods.

https://github.com/eclipse/jetty.project/blob/cb127793e5d8b5c5730b964392a9a905ba49191d/jetty-quic/quic-quiche/quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/SSLKeyPair.java#L46-L56 

One possible way could be to add a second constructor that takes a KeyStore object and extracts the certificate from it and extend the doStart method of the QuicServerConnector to check for the existence of a key store present on the SslContextFactory instance.

**Comment by joakime** [comment]
That makes the assumption of `storeFile` which is not possible in 100% of use cases.
We have many valid scenarios of people with a `java.security.KeyStore` that was created without a File.

**Comment by neoxpert** [comment]
Yes, but what I linked is the current implementation. It requires a key store to already exist on the file system and does not allow to use a `java.security.KeyStore` that was not created from a file but using the API to create a instance "in memory". To use such a key store would be the point I'd like to have in addition to the current requirement of already having a key store in some "physical" form on the disk. 

That's exactly the issue we have in a project where we have a key store, that was not created / loaded from a file, but should be used for a HTTP3ServerConnector.

**Comment by sbordet** [comment]
@neoxpert, would you like to submit a pull request for this enhancement?
