### ISSUE TITLE
Update quiche to 0.16.0

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8695]
**Jetty version(s)**
Jetty 10, Jetty 11, and Jetty 12

**Description**
Time to update quiche again.

Version 0.15.0 and 0.16.0 were just released.

https://github.com/cloudflare/quiche/releases/tag/0.15.0
https://github.com/cloudflare/quiche/releases/tag/0.16.0

**Comment by joakime** [comment]
@lorban once this is updated for `jetty-12.0.x` branch, your task on Issue #8690 can be checked off.

**Comment by lorban** [comment]
Quiche 0.16.0 has been released, updating straight to that version.
