### ISSUE TITLE
jetty-12 ee8 JakartaWebSocketShutdownContainer NotFoundException

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#8698]
**jetty-12**

Running the `ee8` demos you get `INFO` but nonetheless error messages from the `AnnotationConfiguration` class for every `ee8` webapp that is deployed, here's one example:

> 2022-10-10 17:49:01.408:INFO :oejea.AnnotationConfiguration:main: Error:  for o.e.j.e.w.WebAppContext@a137d7a{ee8-demo-proxy,/ee8-demo-proxy,file:///home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/work/jetty-0_0_0_0-8443-ee8-demo-proxy_war-_ee8-demo-proxy-any-/webapp/,false}{/home/janb/src/jetty-eclipse/jetty-12.0.x/jetty-home/target/base/webapps/ee8-demo-proxy.war}

With some extra debugging in there, we see that all of the errors are caused by this:

> Caused by: java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.eclipse.jetty.ee8.websocket.javax.client.JakartaWebSocketShutdownContainer not found
> 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
> 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
> 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
> 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
> 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
> 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
> 	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:37)

Worth noting that this error does _not_ occur for `ee9`, from which `ee8` is a direct translation (nor FWIW `ee10`).

**Comment by lachlan-roberts** [comment]
This is resulting from an issue when generating the ee8 code.

In `ee8-websocket-javax.mod` there are a few problematic lines which still reference jakarta when it should be javax.
```
[lib]
...
lib/ee8-websocket/jetty-jakarta-websocket-api-@jakarta.websocket.api.version@.jar
lib/ee8-websocket/jetty-ee8-websocket-jakarta-server-${jetty.version}.jar

[jpms]
...
add-reads: org.eclipse.jetty.websocket.jakarta.common=ALL-UNNAMED
```

@olamy do you know where this can be fixed, I couldn't find the code for the plugin which does the translation from ee9 -> ee8.

It would be good if we could translate the class names as well, it is strange to see classes like `org.eclipse.jetty.ee8.websocket.javax.common.JakartaWebSocketSession`.

**Comment by olamy** [comment]
there is not translation for mod files as there is not real pattern for file names :(
so there are in the sources tree :)  (here https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-ee8/jetty-ee8-websocket/jetty-ee8-websocket-javax-server/src/main/config/modules/ee8-websocket-javax.mod )

uhm changing class names is a bit more complicated as this means changing a lot of other part of the code.
we know it;s auto translation and nobody touch it that's it.

**Comment by olamy** [comment]
@lachlan-roberts the source code of the plugin translating ee9 -> ee8 is here https://github.com/jetty-project/jetty-modify-sources-maven-plugin

**Comment by lachlan-roberts** [comment]
fixed with https://github.com/eclipse/jetty.project/pull/8703
