### ISSUE TITLE
Stats handler should measure dispatch latency

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#87]
migrated from Bugzilla [#318264](https://bugs.eclipse.org/bugs/show_bug.cgi?id=318264)
status ASSIGNED severity *enhancement* in component *server* for *7.1.x*
Reported in version *7.1.0* on platform *All*
Assigned to: Project Inbox

On 2010-06-28 20:21:59 -0400, Greg Wilkins wrote:

> The stats handler should measure the ave,max and stddev of the time from when the request is first received by the connector until the time it is first seen by the stats handler.
> 
> It currently has the request timestamp, so it has this information available.
> 
> 
> However, there is a small complication.  The request.setTimestamp(long) method is called in two places:
> 
> HttpConnection$RequestHandler.startRequest - when the request line is first parsed.
> 
> HttpConnection.handleRequest -> Connection.customizeRequest  - which is called after the request is dispatched. 
> 
> I think the second of these should be removed, as it will only be nano seconds before the request is handed to the stats server.
> 
> The first of these is after the request is dispatched, but then all handling in Jetty is dispatched - so it will do for now... perhaps we can eventually replace it with a timestamp set on the endpoint representing the last dispatched time.  Or maybe we have both?

**Comment by gregw** [comment]
Resolved some time ago
