### ISSUE TITLE
TLS protocol exclusion broken for SslContextFactory(String)

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#870]
When the internal in SslContextFactory implementation was changed from using SSLEngine to using SSLContext for protocol / cipher lists apparently broke the Protocol Exclusion behavior.

See Issue #866

**Comment by sbordet** [comment]
This issue stemmed from #866, but it was only a problem related to the fact that one of the constructors of `SslContextFactory` did not initialize the protocol exclusion list.
