### ISSUE TITLE
Got error protocol_error/invalid_preface when using HTTP/2

### ISSUE THREAD

**Issue by cuongngo-orientsoftware** [eclipse/jetty.project#8709]
**Jetty version(s)**
Jetty 11

**Java version/vendor** `(use: java -version)`
Java 17

**OS type/version**
Windows 10

**Description**
I setup conector like this:
![image](https://user-images.githubusercontent.com/74752259/195532915-29b70958-32e2-44b7-bc45-d7aa6ea7fe18.png)

bug got error: protocol_error/invalid_preface

![image](https://user-images.githubusercontent.com/74752259/195533445-a93d3ebb-815a-4e83-8b24-db6ce664f1d9.png)

**Comment by sbordet** [comment]
Please read the documentation about how to properly setup clear-text HTTP/2:
https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector-protocol-http2.

**Comment by cuongngo-orientsoftware** [comment]
> Please read the documentation about how to properly setup clear-text HTTP/2: https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector-protocol-http2.

I did same that but it just works on http/1.1
I separate connector to catch up error

**Comment by sbordet** [comment]
Does the client support HTTP/2?
If so, is it configured to send either an HTTP/1.1 upgrade to HTTP/2 request, or a prior knowledge HTTP/2 request?

Because it seems that it does not.
You don't show your client code, so I can't tell.

**Comment by cuongngo-orientsoftware** [comment]
I test with Google Chrome browser, Is it right client ?

**Comment by sbordet** [comment]
Browsers don't support clear-text HTTP/2.

Use this configuration:
https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector-protocol-http2-tls

**Comment by cuongngo-orientsoftware** [comment]
Thanks !

I add more code:
![image](https://user-images.githubusercontent.com/74752259/195553963-26787f8c-2256-4c8c-aeee-3905b5786364.png)

then get the next erorr:
![image](https://user-images.githubusercontent.com/74752259/195566381-6b1d8990-78fb-4384-884d-f77f7fafa9a2.png)

Might I miss something ?

**Comment by sbordet** [comment]
You should use the `https` scheme in your browser.

**Comment by cuongngo-orientsoftware** [comment]
I tried upper test with https

**Comment by cuongngo-orientsoftware** [comment]
I try with Postman then get another error:
![image](https://user-images.githubusercontent.com/74752259/195579299-e10bb70f-0fef-4625-9cc6-b4c99a83a987.png)

**Comment by sbordet** [comment]
You are probably using a bad certificate in the KeyStore.
Google around, as this is not a Jetty issue, as I understand you were able to make it work with browsers.

**Comment by joakime** [comment]
Also, don't use the JDK/JRE provided cacerts as your keystore.

The shipped cacerts file with the JDK is a truststore, not a keystore.

**Comment by cuongngo-orientsoftware** [comment]
Thanks !

I tried to use KeyStore.jks file instead but get new error

![image](https://user-images.githubusercontent.com/74752259/195634386-07e8aaa6-e53a-47ca-89c9-be917dd32da5.png)

**Comment by sbordet** [comment]
Can you just post the whole stack trace rather than image snippets that are half-cropped in the most important parts?
You are making really difficult to help you.

**Comment by joakime** [comment]
Yes, please use copy/paste, not images.
This is useful for us, and the tooling here, and future folks that are trying to solve similar problems. (you can't search text in an image)

**Comment by cuongngo-orientsoftware** [comment]
I thought it is easier to see, sory about that

[debug log of jetty-http2.txt](https://github.com/eclipse/jetty.project/files/9778303/jetty-http2.txt)

**Comment by joakime** [comment]
> I tried to use KeyStore.jks file instead but get new error

You have to make your own keystore, with Java 9+ it's typically in the pkcs12 format, not jks.
Be careful to pick options in your certificates that work with TLS 1.3 and the version of Java you are using (example, don't use RSA or DES3 as those are disabled in Java)

**Comment by cuongngo-orientsoftware** [comment]
I created keystore.pfx
`keytool -genkey -alias test_PKCS12 -keystore keystore.pfx -storetype PKCS12 -keyalg RSA -storepass 123456 -validity 730`
 with keyalg: 

- RSA or EC but get same upper error
- DSA like eror: https://bugs.openjdk.org/browse/JDK-8211426

**Comment by joakime** [comment]
Check the Java Crypto Roadmap and confirm you are satisfying all of the requirements for your chosen JVM.

* https://www.java.com/en/jre-jdk-cryptoroadmap.html

Example: RSA is not supported under certain key sizes (and you didn't specify a key size in your command line)

**Comment by sbordet** [comment]
The log is at DEBUG level and may report an error even if the server works fine.
The error is due to the client closing the connection.

I'm assuming you're using a self-signed certificate and typically browsers don't like them.
They will present you with a page saying whether you want to continue browsing even if the certificate cannot be trusted, etc.

**Comment by joakime** [comment]
Most browsers today also only support hostnames when connecting to HTTP/2.

IP addresses and localhost are not supported.

**Comment by cuongngo-orientsoftware** [comment]
Now I get error when access from:
- Chrome browser: get error message like this: https://github.com/eclipse/jetty.project/issues/5197
- Firefox: have not error: [firefox_request.txt](https://github.com/eclipse/jetty.project/files/9796548/firefox_request.txt) but still get respone http/1.1

Any idea ?
