### ISSUE TITLE
If client hangs up on a StreamingOutput, the EofException is not handled silently

### ISSUE THREAD

**Issue by tagliola** [eclipse/jetty.project#871]
I'm using Jetty 9.2.3 with RestEasy 3.0.16.

When a client hangs up (f.e. ^c on curl) from a resource which is written using a StreamingOutput, several warnings are logged. In the SynchronousDispatcher.writeException from RestEasy, the EofException is wrapped in an UnhandledException because the response is committed (line 167).

Ongoing and back in the ServletHandler, the catch block in doHandle has code for silently processing an EofException, which works for non streaming resources. However, on line 608 with the comment 'unwrap cause' it does not unwrap the UnhandledException. It is kept as is and triggers several warnings with stacktraces along the way. The cause from the UnhandledException is actually the EofException, so if like 609 would be th=e.getCause(), the handling would be identical to non-streaming resources, which is silence.

**Comment by joakime** [comment]
So you are using RestEasy which is deciding to toss back a RestEasy UnhandledException to Jetty.
We cannot safely unwrap custom exception types on the server side.

If UnhandledException extended ServletException then this kind of unwrapping is safe for a Servlet Container to perform.

Perhaps if you added a servlet error mapping of UnhandledException to your own custom code you could do with it as you please.

**Comment by tagliola** [comment]
I wasn't sure on which side of the fence the actual problem lies :-) Agreed that it's unsafe to unwrap custom exception. Throwing a ServletException is not possible, as the throws signature of StreamingOutput is IOException or WebApplicationException. The first will result in the UnhandledException, the second should not be used because the headers are already committed. I'll open a ticket with RestEasy, as it would seem that there is some EofException handling missing.

I'm not sure how to install a servlet error mapping for UnhandledException. For now I worked around it by swallowing the EofException, but that's quite ugly to leak through in my own code.
