### ISSUE TITLE
ELContextCleaner no longer needed.

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#8712]
**jetty_10**

The `o.e.j.servlet.listener.ELContextCleaner` class is no longer needed, as the class that it attempts to clean up for `javax.el.BeanELResolver` no longer contains a static field called `properties` that was the problem.

**Comment by janbartel** [comment]
Note to self: when merging through to jetty-12, remember to modify `ee9` `ELContextCleaner` to also ignore `NoSuchFieldExceptions` to prevent lines like this during shutdown:

> JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties

**Comment by olamy** [comment]
> Note to self: when merging through to jetty-12, remember to modify `ee9` `ELContextCleaner` to also ignore `NoSuchFieldExceptions` to prevent lines like this during shutdown:

why not simply remove it in jetty-12?

> 
> > JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties

**Comment by janbartel** [comment]
@olamy I've removed it already from ee10, but I figure I need to keep it consistent for ee8 and ee9.

**Comment by janbartel** [comment]
Merged through to jetty-12.
