### ISSUE TITLE
Jetty 12 - Improve usability for ResourceHandler

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#8727]
**Jetty version(s)**
12+

**Description**
For usage from XML, would be nice if `ResourceHandler.setBaseResource()` takes a `String` or a `Path`, because currently only takes a `Resource` which is cumbersome to create in XML.

**Comment by gregw** [comment]
I'll do this unless others have already started?

Note we used to have `setBaseResource(Resource)` and `setResourceBase(String)`, but I think that is too tricky and they should both be called `setBaseResource`

**Comment by sbordet** [comment]
@gregw beware of JMX as it produces the following log lines:

```
2022-10-19 00:00:53.943:INFO :oejj.MetaData:main: Multiple setters for mbean attribute configurationClasses in class org.eclipse.jetty.deploy.providers.ContextProvider
```

or

```
2022-10-19 00:00:53.944:INFO :oejj.MetaData:main: Getter/setter type mismatch for mbean attribute tempDir in class org.eclipse.jetty.deploy.providers.ContextProvider
```

So perhaps instead of overloading, it's better to use another method name.

**Comment by gregw** [comment]
@sbordet How about `setBaseResourceAsString(String)` and then probably `setBaseResourceAsPath(Path)` ?

**Comment by joakime** [comment]
`oejj.MetaData` is our class (`org.eclipse.jetty.jmx.MetaData`), surely we can address that in our MetaData class better.
