### ISSUE TITLE
Jetty 12 - Move org.eclipse.jetty.server.context.ManagedAttributes to core

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#8740]
**Jetty version(s)**
12+

**Description**
Currently, ee9 `ContextHandler` and ee10 `ServletContextHandler` have the constant `MANAGED_ATTRIBUTES=org.eclipse.jetty.server.context.ManagedAttributes` that it used to lookup a comma-separated list of attribute names whose values should be exposed to JMX.

This functionality should be moved to core.

**Comment by joakime** [comment]
Merged PR #9549
