### ISSUE TITLE
How do I know if a websocket client message has been successfully sent to the Websocket Server side?

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#8752]
**Jetty version**
11.0.12
**Java version**
11.0.14
**Question**
I use the jetty websocket client to send byte messages to the websocket server. I use the following method to asynchronously send data to the server and receive a successful callback result. Does that prove that it has been sent to the websocket server?
Or is it only sent to the local buffer or the local network adapter? How do I prove that it has been sent to the websocket server?

**DataAsyncWriteCallback future = new DataAsyncWriteCallback(dialogId);
session.getRemote().sendBytes(ByteBuffer.wrap(data), future);**

**Comment by sbordet** [comment]
> Does that prove that it has been sent to the websocket server?

Yes, it proves that it has been sent, meaning it was handed to the OS for send. From the JVM point of view it is "sent" and you have the proof that you have done everything in your power to send the bytes -- there is nothing more that you can do from Java.
But the OS may have not sent it yet (and may not send it, in very rare cases).

However, that does not mean that it _reached_ the server.
It is not possible to know if it reached the server, unless you implement something at the application level (i.e. the server sends back a "received" message to the client).

**Comment by xinguangduan** [comment]
@sbordet , thanks for detail explain, understood.
