### ISSUE TITLE
Introduce CompressionHandler to support compression from gzip, brotli, and zstandard

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8769]
**Jetty version(s)**
Jetty 12

**Enhancement Description**
The current `GzipHandler` does a good job at handling `Content-Encoding: gzip` (and `Accept-Encoding: gzip`), but we shouldn't hardcode only gzip support.

Can we refactor the existing `GzipHandler` to be more generic, something like `DynamicCompressionHandler` and have the Gzip support (courtesy of the existing `GzipRequest` object) just be loaded via a ServiceLoader?

This way we can encourage other compression algorithms under the same `Accept-Encoding` / `Content-Encoding` / already compressed rules that the existing codebase handles for us?

Other compression algorithms that have been requested in our issue tracker.

* #2553 - [RFC 7932](https://www.rfc-editor.org/rfc/rfc7932) - Brotli Compressed Data Format 
* #6600 - [RFC 8878](https://www.rfc-editor.org/rfc/rfc8878) - Zstandard Compression and the `application/zstd` Media Type

(FYI, `curl` supports both of these compression types now)

**Comment by joakime** [comment]
When we do this we need to keep in mind the effort for Compression Dictionary Transport.

* https://github.com/WICG/compression-dictionary-transport
* https://datatracker.ietf.org/doc/draft-ietf-httpbis-compression-dictionary/
* https://chromestatus.com/feature/5124977788977152

**Comment by gregw** [comment]
@joakime lets start working on this in the 12.1.x branch

**Comment by joakime** [comment]
I'm working on this now.

**Comment by joakime** [comment]
I've got the basics of the Compression API done.
Including the Encoders as Content.Sink, and Decoders as Content.Source.
The DynamicCompressionHandler (needs a new name, perhaps `CompressionHandler` ?) can do the basics right now.

What's left ...

- [ ] CompressionHandler Config
- [x] Encoder Config
- [x] Decoder Config
- [ ] Compressions (plural) as single object to find/use/manage all compressions available (ServiceLoader? bean on Server? bean on Client?)
- [ ] Dictionary Support for Encoders and Decoders
- [ ] HTTP Shared Dictionary support in CompressionHandler - see https://datatracker.ietf.org/doc/draft-ietf-httpbis-compression-dictionary/
- [ ] jetty start modules for CompressionHandler
- [ ] XML examples of configuration of CompressionHandler with examples:
- [ ] More testing around error handling of failures during Encoder / Decoder with a focus on cleanup / release.
- [x] Decide if we want to support multiple entire encodings on Decoder or not (I vaguely recall this coming up for GzipHandler where the content was 2 entire Gzip blocks, with headers + data + trailers, one after the other, but coalesced into a single decode.  This is awkward at best for Gzip, and totally not supported for brotli and zstandard)
- [ ] Documentation for all of the above.

**Comment by joakime** [comment]
@gregw lets have a chat about the remaining tasks.

**Comment by joakime** [comment]
Merged PR #12075

**Comment by jluehe** [comment]
> * XML examples of configuration of CompressionHandler with examples:

@joakime, is this done? Could not find any examples. Would be useful to have! Thank you!

**Comment by sbordet** [comment]
@jluehe the standard Jetty modules that enable compression could be a good example, see for example:

https://github.com/jetty/jetty.project/blob/jetty-12.1.1/jetty-core/jetty-compression/jetty-compression-server/src/main/config/etc/jetty-compression-brotli.xml

There are similar examples for gzip and zstd in this directory:
https://github.com/jetty/jetty.project/tree/jetty-12.1.x/jetty-core/jetty-compression/jetty-compression-server/src/main/config/etc

Would that be enough?

**Comment by jluehe** [comment]
> [@jluehe](https://github.com/jluehe) the standard Jetty modules that enable compression could be a good example, see for example:
> 
> https://github.com/jetty/jetty.project/blob/jetty-12.1.1/jetty-core/jetty-compression/jetty-compression-server/src/main/config/etc/jetty-compression-brotli.xml
> 
> There are similar examples for gzip and zstd in this directory: https://github.com/jetty/jetty.project/tree/jetty-12.1.x/jetty-core/jetty-compression/jetty-compression-server/src/main/config/etc
> 
> Would that be enough?

Thank you, @sbordet! Those examples are useful, but I think it would also be helpful to add an xml snippet for how to configure `CompressionHandler` itself (as opposed to the individual compression algorithm sections) using `CompressionConfig` builder pattern, essentially matching the programmatic approach shown in https://jetty.org/docs/jetty/12.1/programming-guide/server/http.html#handler-use-compression ...

**Comment by sbordet** [comment]
```xml
      <New id="CompressionHandler" class="org.eclipse.jetty.compression.server.CompressionHandler">
        <Call name="builder" class="org.eclipse.jetty.compression.server.CompressionConfig">
          <Call name="compressExcludePath"><Arg>/uncompressed</Arg></Call>
          <Call name="compressIncludeMethod"><Arg>POST</Arg></Call>
          <Call name="compressExcludeMimeType"><Arg>font/ttf</Arg></Call>
          <Call id="compressionConfig" name="build"/>
        </Call>
        <Call name="putConfiguration">
          <Arg>/*</Arg>
          <Arg><Ref refid="compressionConfig"/></Arg>
        </Call>
      </New>
```

**Comment by jluehe** [comment]
Thank you, @sbordet! Perhaps this could be added to the docs as well!
