### ISSUE TITLE
KeyStoreScanner is not able to monitor a symlink file and always resolves to the target.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#8786]
**Jetty version(s)**
9.4.x, 10.0.x, 11.0.x

**Description**
`KeyStoreScanner` is not able to monitor a symlink file and always resolves to the target.

There is a test `org.eclipse.jetty.test.KeyStoreScannerTest#testReloadChangingSymbolicLink` which is incorrectly testing that this use case works, but it is currently not possible to configure in `KeyStoreScanner`.

**Comment by sbordet** [comment]
I miss why do we want to monitor the symlink, seems to make no sense to me?

**Comment by joakime** [comment]
The symlink can be changed to point to a different location?
The underlying filesystem mounts can change, making what the symlink is pointing to different? (or even invalid)

**Comment by joakime** [comment]
@lachlan-roberts don't forget to set labels and projects.

**Comment by lachlan-roberts** [comment]
A user was requesting this feature, they wanted to modify the symlink file to point to a new target instead of just changing the target file of the symlink.

We had a test for it which was wrong. So very least we should fix the test to verify the behaviour we expect.

**Comment by joakime** [comment]
This feature has been further updated as part of PR #9014
