### ISSUE TITLE
Jetty-12 Should Request.Processors be reusable?

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8791]
Currently in Jetty-12, we do not specify in the `Request.Processor` contract/javadoc if it can be reused or not.  i.e, once a Processor has been obtained from `Handle.handle`, can it be used over and over with many different request/response/callback tupples?

This is analogous to `RequestDispatchers` in the servlet API, which currently may be reused multiple times.

In Jetty-12, many of our processor implementations will work fine if reused.  However, we also have many examples of `Handler`s that wrap a request in the `handle` method and then reuse that wrapper in the `process` method rather than re-wrapping. In fact, often it is the request wrapper that is also the processor.

At the very least, we should javadoc if processors may not be re-used or not.

However, I think there are use-cases for re-using processor, so perhaps we should consider either: making all our processors reusable (could be some cost in duplicate wrapping); or making processors declare if they can be reused or not.

**Comment by joakime** [comment]
No longer relevant, we don't have Request.Processors anymore.
