### ISSUE TITLE
Refactor jetty-http's HostPortHttpField logic into new jetty-util class

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#880]
The ability to parse "host" and "host:port" found in HttpPortHttpField would be useful to have refactored into jetty-util for the other IP address features in jetty-util to also make use of.

IPAddressMap and IPAddrPattern would be affected by this, and in turn the various servlets that need to handle this kind of IPv4 vs IPv6 logic (such as IPAccessHandler, ConnectHandler, jetty-client, and ProxyServlet)

This logic could also apply for white/black lists by IP (sometimes called include/excludes) found in various configurations too.

**Comment by joakime** [comment]
Once that exists in jetty-util, we should file new enhancement requests for the other refactorings

**Comment by joakime** [comment]
This work should probably be done in `jetty-9.2.x` branch and be merged forward as part of a general IPv6 support level in Jetty.

**Comment by gregw** [comment]
I will use this as a meta issue to resolve #879 #881 #882 #883 #884 #885 #886

**Comment by gregw** [comment]
The parsing has been extracted into a HostPort class in 9.2.x.   This will need to be merged forward to 9.3.x as HostPortHttpField does not exist in 9.2.x
