### ISSUE TITLE
Add IPv6 support to IPAccessHandler

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#881]
The IPAccessHandler in jetty-server only supports IPv4 currently

**Comment by gregw** [comment]
Depends somewhat on #882, although it should also use the IncludeExclude class, except that is not well suited when the pattern type does not match the predicate type (eg String pattern to test a InetAddress type)

**Comment by gregw** [comment]
Deprecated IPAccessHandler in favour of InetAccessHandler
