### ISSUE TITLE
Add IPv6 support to IPAddressMap in jetty-util

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#882]
The IPAddressMap in jetty-util only currently supports IPv4

**Comment by gregw** [comment]
The class IPAddressMap is seriously broken in it's abstraction, as it implements map, with a comma separated list of patterns as it's key.    But this cannot respect true map semantics.

I'm not sure how to fix this, let alone add IPv6 support without breaking API in a point release?

**Comment by gregw** [comment]
The new IPv6 capable InetAddressSet has been added as an alternative for IPAddressMap
The IncludeExclude class has been generalized to IncludeExcludeSet that can have a different
Predicate type to the set type and this works well with InetAddressSet.

However for #881 and #883, this may not be enough and Map semantics may need to be added.

The IPAccessHandler also has path mappings supported, which could need the map semantics, so for now a new InetAccessHandler has been
added that just uses an IncludeExcludeSet<InetAddressSet>, but this has yet to be tested.

The AbstractProxyServlet uses a host:port combinations, so IncludeExcludeSet<InetAddressSet> is not directly applicable.
