### ISSUE TITLE
Add IPv6 support for AbstractProxyServlet

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#883]
The blacklist / whitelist support in AbstractProxyServlet should be converted to use the updated IPAddressMap from Issue #882

**Comment by joakime** [comment]
This appears to have been completed in 9.4

**Comment by sbordet** [comment]
IPv6 was always supported in `AbstractProxyServlet`, although only via precise match.

```java
proxyServlet.getWhiteListHosts().add("[::1]:8080");
```

The support is only via `String` and not via the more capable `InetAddressSet` though.
