### ISSUE TITLE
Review IPv6 support of URIUtil.appendSchemeHostPort()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#885]
The support for IPv6 in URIUtil.appendSchemeHostPort() looks fishy.

Esp the .indexOf(':') lookup

**Comment by joakime** [comment]
There are 2 .appendSchemeHostPort() methods that should be looked at.

Also, why does one synchronize on url, and the other doesn't?

**Comment by gregw** [comment]
The code is correct.  It is allowing a server name to be passed in as either:

- host
- 127.0.0.1
- ::1
- [::1]

In the last two cases, it uses : in the host name to determine if it is a IPv6 address and then checks to see if it needs to be wrapped with [ ]
