### ISSUE TITLE
How to efficiently increase jetty websocket throughput

### ISSUE THREAD

**Issue by xiaochen-db** [eclipse/jetty.project#8864]
**Jetty version**
9.3.27

**Java version**
1.8.0_282

**Question**
Hi Jetty team, I built a communication channel based on Jetty websocket between two backend services with `WebSocketClient` on one end and `WebSocketHandler` on the other.  This works pretty well for my application which bidirectionally sends and receives text messages using following APIs: 

```
// to send text message 
org.eclipse.jetty.websocket.api.Sesson.getRemote().sendString(msg)

// to receive text message
@org.eclipse.jetty.websocket.api.annotations.OnWebSocketMessage
public void onMessage(string msg) {
   handleMsg(msg)
}
```

As I understand, these APIs are blocking in a sense that both ends of the connection are single threads sending and receiving messages. Now that this application needs to handle higher load (in terms of X MB/s in certain direction) as it scales, and I am considering to let other applications to shared the same connection (sending/receiving text bidirectionally as well). I wonder is there a way I can increase the maximum throughput of this websocket connection bidirectionally? For certain applications the order of message delivery isn't important; for some others the order matters. 

I vaguely learn that jetty websocket can do streaming and async sending messages, but without mentioning in the jetty documentation I am not sure if they would help my case. 

(I understand 9.3.27 is at EOL, but it's not a light task for my organization to conduct an upgrade) 

Thanks!

**Comment by joakime** [comment]
The entire Jetty 9.x line is now at End of Life (or in the case of 9.4.x it's End of Community Support, with End of Life later).

* https://github.com/eclipse/jetty.project/issues/7958

**Comment by joakime** [comment]
Since you are using such an old version of Jetty (9.3.27), please take a moment and see how many published vulnerabilities impact you. (quite a lot)

* https://www.eclipse.org/jetty/security_reports.php

We've helped many organizations (via the webtide.com support contract) upgrade from Jetty 9 (and Java 8) to Jetty 10 or 11 (and Java 11 or 17) with great success.
If you are interested, contact [Jesse @ webtide](mailto:support@webtide.com)

**Comment by lachlan-roberts** [comment]
> I am considering to let other applications to shared the same connection (sending/receiving text bidirectionally as well)

You would want to use separate websocket connections for each of the other applications, you can share the same `WebSocketClient` to make these separate connections. This way messages for each application can be delivered concurrently as each connection will have its own thread reading from the connection and providing the messages to the application.

**Comment by xiaochen-db** [comment]
@lachlan-roberts I generally agree with you on using isolated websockets for different applications. Thanks for the suggestion!

Also I was reading https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-message-streaming-reads and https://github.com/eclipse/jetty.project/issues/2690#issuecomment-879644785:

It sounds that the major benefit of streaming delivery is for reducing memory consumption for handling large messages rather than increasing the throughput of small or medium sized messages? Initially I thought streaming has higher throughput since it uses multiple handling threads, but you mentioned the order of messages delivery is preserved (https://github.com/eclipse/jetty.project/issues/2690#issuecomment-879644785) so that's not necessarily true.

**Comment by lachlan-roberts** [comment]
Using the streaming message reads uses a separate thread to be dispatched with `InputStream` or `Reader` message argument then you can consume the input stream as the message is delivered asynchronously. This is not particularly suited for shorter messages.

You are better off using the partial message handlers if possible, which requires no accumulation or extra threads from Jetty.
