### ISSUE TITLE
Http2: set SettingsFrame.MAX_CONCURRENT_STREAMS optional

### ISSUE THREAD

**Issue by gointuition** [eclipse/jetty.project#8869]
**11.0.12**

`org.eclipse.jetty.http2.client.HTTP2ClientConnectionFactory.HTTP2ClientConnection#onOpen`
```
@Override
public void onOpen()
{
    Map<Integer, Integer> settings = listener.onPreface(getSession());
    if (settings == null)
        settings = new HashMap<>();
    settings.computeIfAbsent(SettingsFrame.INITIAL_WINDOW_SIZE, k -> client.getInitialStreamRecvWindow());
    settings.computeIfAbsent(SettingsFrame.MAX_CONCURRENT_STREAMS, k -> client.getMaxConcurrentPushedStreams());
```
As you can see, Jetty Http2ClientSession always sends the MAX_CONCURRENT_STREAMS in SettingsFrame, while some other http2 clients don't send it, like FireFox. Hope we can set MAX_CONCURRENT_STREAMS optional in Jetty, too.
Thanks.

**Comment by sbordet** [comment]
You can customize the `Map` as you like, by implementing `Session.Listener.onPreface()` and return a non-null `Map`.
See https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-client-http2-configure.

Having said that, a valid server implementation should be able to accept settings as the client sends them, independently from whether Firefox sends it by default or not.

**Comment by joakime** [comment]
@sbordet doesn't matter if you return a non-null map from `listener.onPreface()`

The `onOpen()` will add back the `MAX_CONCURRENT_STREAMS`.

https://github.com/eclipse/jetty.project/blob/c96b14f25ca10058ed64b764e69b3772a7c584ea/jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2ClientConnectionFactory.java#L96-L102

**Comment by sbordet** [comment]
@joakime right.
@gointuition why should I not send it?

**Comment by gointuition** [comment]
@sbordet just a suggestion. It's a low-level library, it would be better to be more extensible, I thought.

**Comment by sbordet** [comment]
@gointuition if you want to prepare a pull request I won't mind (see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md).

The logic could be that if `getMaxConcurrentPushedStreams()` returns a negative value, then it is not set.

**Comment by joakime** [comment]
BTW, The logic in firefox is that if max concurrent streams is 0 or negative or unset, then http/2 push is disabled.  (a strange bit of logic there)

**Comment by joakime** [comment]
IIRC, not sending a max concurrent streams configuration will cause breakage on some servers. (most notably Apple and Cloudflare)
