### ISSUE TITLE
dependency-reduced-pom.xml file generated from building project

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#8870]
**Jetty version(s)**
12.0.x

Building the project sometimes generates a `tests/jetty-jmh/dependency-reduced-pom.xml` file which is not ignored by git.

**Comment by olamy** [comment]
ezy fix by adding this to `maven-shade-plugin` configuration:
```
<createDependencyReducedPom>false</createDependencyReducedPom>
```

**Comment by sbordet** [comment]
This is fixed already.
https://github.com/eclipse/jetty.project/commit/42255442224834b81ed1de1ff11899e0aaccf700#diff-cfe805e5d0f7642f5efc755500f11d7f49b768679dd7858764af172085b6b38e
