### ISSUE TITLE
Can't stop/remove thread that does the SendMessage from a Jetty Websocket

### ISSUE THREAD

**Issue by jarnegr** [eclipse/jetty.project#8879]
I ran in to a problem using a Jetty Websocket when connecting to an endpoint and sending Strings to it.

First off, the websocket is used to connect to a Sonos speaker using a Jetty websocket. Jetty version is 9.4.48 .

These connections can of course be interrupted by a loss of power, connection issues, ... The problem occurs when trying to clean up the threads when a the connection is interrupted. The HTTPclient is able to end all it's threads succesfully, except for 1 thread. This is a thread that is created when the Jetty

``` java
session.getRemote().sendString(message);
```

is called.

I think the problem lies with the fact that I keep sending websocket strings but they never get answered. I found this thread-leak with JProfiler.

Things I've tried already:

Using a `SendStringByFuture` or `SendString` with a new `WriteCallback`:

``` java
session.getRemote().sendString(message, new WriteCallback() {
    @Override
    public void writeFailed(Throwable throwable) {
        log.info(LOG_TAG + " -- Write Failed!");
        log.info(throwable.getMessage());
        log.info(throwable.getCause().getMessage());

        try {
            session.getRemote().flush();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void writeSuccess() {
        log.info(LOG_TAG + " -- Write Success!");
    }
});
```

Any ideas what is causing this thread to stick around? I've had test cases that caused OutOfMemroyExceptions because of this thread leak.

Thanks in advance

I expected the thread to get removed by the garbage collector since it isn't used anymore, but instead the threads stay alive and can cause outofmemoryexceptions when JVM is unable to start a new thread.

**Comment by joakime** [comment]
@lachlan-roberts do we have test cases for this scenario?

**Comment by lachlan-roberts** [comment]
Not sure about the tests for this in 9.4. It could be some bug in one of the flushers.

@jarnegr are these connections using `permessage-deflate` extension? and could you update to `10.0.x`+ and see if you still experience this bug.

**Comment by lachlan-roberts** [comment]
Looks like same issue as https://github.com/eclipse/jetty.project/issues/8766

**Comment by jarnegr** [comment]
I don't think the connections are using the `permessage-deflate` extension, but will check when updating to `10.0.x`. Will post in the coming days if this resolved the issue.

**Comment by jarnegr** [comment]
@lachlan-roberts Am I able to upgrade to `10.0.x` wtihout upgrading the websocket packages? Or am I looking in the wrong places for these updates. The only ones I can find are the normal jetty packages, not the jetty-websocket packages.

**Comment by jarnegr** [comment]
Wrong button, my bad

**Comment by jarnegr** [comment]
@lachlan-roberts Am I able to upgrade to 10.0.x wtihout upgrading the websocket packages? Or am I looking in the wrong places for these updates. The only ones I can find are the normal jetty packages, not the jetty-websocket packages.

**Comment by joakime** [comment]
@jarnegr all jetty versions must be kept in lock-step, sorry.

**Comment by joakime** [comment]
WebSocket dependencies on Jetty 10.x

Core

 * Client -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-core-client
 * Server -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-core-server

Jetty WebSocket

 * API -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-jetty-api
 * Client -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-jetty-client
 * Server -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-jetty-server

javax.websocket

 * Client -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-javax-client
 * Server -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-javax-server
 * Servlet -> https://search.maven.org/artifact/org.eclipse.jetty.websocket/websocket-servlet

**Comment by lachlan-roberts** [comment]
There is a `9.4` -> `10.0` websocket migration guide in the documentation:
https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-migration-94-to-10

**Comment by lachlan-roberts** [comment]
Closing as 9.4 is EOL.
