### ISSUE TITLE
Does the jetty proxy servlet support web socket?

### ISSUE THREAD

**Issue by amartya10** [eclipse/jetty.project#8883]
**Jetty version 11.0.11**

**Java version 11.0.14**

**Does the jetty proxy servlet support web socket?**
I tried but connection upgrade requests fails 

Thank you for help. 😃 

#proxy #jettyproxyservlet

**Comment by sbordet** [comment]
No, it does not support WebSocket upgrades.

**Comment by amartya10** [comment]
Thank you  @sbordet
One more question
Does HTTP2 protocol supported by jetty proxy  ?

**Comment by sbordet** [comment]
> Does HTTP2 protocol supported by jetty proxy ?

Yes, HTTP/2 is supported.

**Comment by amartya10** [comment]
Thanks @sbordet 
closing

**Comment by geezer78** [comment]
Hi There,

are there any plans to include websocket (i use socket.io) connections within jetty-proxy

**Comment by sbordet** [comment]
No plans for now. 

This work can be sponsored, however, with a commercial contract with [Webtide](https://webtide.com)
