### ISSUE TITLE
Preferred Way to Block HTTP/1.0 Requests

### ISSUE THREAD

**Issue by copperleaf91** [eclipse/jetty.project#8889]
**Jetty version**
9.4.49.v20220914

**Java version**
1.8.0_352

**Question**
What is the preferred way to block http/1.0 request coming in?

**Comment by joakime** [comment]
Interesting question.

Why are you wanting to block HTTP/1.0?
(I'm asking, as there might be a different way to block what you don't desire)

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support:

See:
* #7958

In Jetty 10+ this could be implemented as an `HttpCompliance.Violation` for `HTTP_1_0` (just like we do for `HTTP_0_9`).
It would trigger a 400 Bad Request from the `HttpParser` if not set to allowed.

**Comment by joakime** [comment]
You could have an `HttpConfiguration.Customizer` that just rejects 1.0

The implementation would look something like ...

``` java
public void customize(Connector connector, HttpConfiguration channelConfig, Request request)
{
    if (request.getHttpVersion() == HttpVersion.HTTP_1_0)
        request.getResponse().sendError(HttpStatus.HTTP_VERSION_NOT_SUPPORTED_505);
}
```

**Comment by copperleaf91** [comment]
We currently have a support contract with you all (Tridium) for Jetty 9 and need to use it for our currently supported release. The issue we need to solve is the HTTP/1.0-Location issue. I know you have the HostnameCustomizer but that requires "knowing" the hostname to substitute in Location and for our embedded environment, may not be know, yet we are getting pinged for it, Our approach for solving this was to provide a clean way of disabling HTTP/1.0.

I've prototyped basically what you did above. But it one case, when I send the error, somewhere higher in the stack, a different error is returned.

```
# curl -k --http1.0 -v -H "Host:" https://localhost:5011
*   Trying 127.0.0.1:5011...
* Connected to localhost (127.0.0.1) port 5011 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
> GET / HTTP/1.0
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Strict-Transport-Security: max-age=15552000
* no chunk, no close, no size. Assume close to signal end
<
<html>
<body>
<h1>401: Unauthorized</h1>
</body>
</html>* schannel: server closed the connection
* Closing connection 0
* schannel: shutting down SSL/TLS connection with localhost port 5011
```

**Comment by janbartel** [comment]
I think this question has been addressed in the linked issue. If not, please reply on the linked issue instead of this one.
