### ISSUE TITLE
Review MappedByteBufferPool

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#890]
After #432, `MappedByteBufferPool` was broken:

- `newByteBuffer()` was the only method that allocated buffers, allowing subclasses such as `Tagged` to identify them for debugging purposes, but after the changes also `Bucket` allocates buffers, so `Tagged` is now broken
- clear() does not call `Bucket.clear()`
- the lambda passed to `Map.computeIfAbsent()` in `release()` is a capturing lambda which causes allocation; it should be preallocated in the constructor and reused.

**Comment by gregw** [comment]
@sbordet are you fixing these?  if so assign yourself the issue, else I'll fix tomorrow.

**Comment by sbordet** [comment]
Regarding the lambda, see https://www.infoq.com/articles/Java-8-Lambdas-A-Peek-Under-the-Hood.

Even if the lambda can be rewritten more correctly to not capture variable `b` but use `bi`, it still captures `this` to refer to fields `_factor` and `_maxQueue`.
For this reason, it is better to allocate it once in the `Bucket` constructor, and then reuse it.

**Comment by sbordet** [comment]
Regarding the allocation of the buffers, the problem is that `newByteBuffer()` takes primitive types, so trying to model `newByteBuffer()` as a `BiFunction` introduces boxing and therefore allocation, so it needs a smarter solution.

**Comment by gregw** [comment]
@sbordet please double check this when you get a chance

**Comment by sbordet** [comment]
Reviewed.
