### ISSUE TITLE
GzipHandler fails to set Vary header on 304 responses

### ISSUE THREAD

**Issue by markslater** [eclipse/jetty.project#8905]
**Jetty version(s)**
11.0.12

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)

**OS type/version**
Linux 5.4.0-120-generic

**Description**
RFC 9110 [states](https://www.rfc-editor.org/rfc/rfc9110#name-304-not-modified) that a 304 response must generate a `Vary` header matching that generated by the equivalent 200 response:

>The server generating a 304 response MUST generate any of the following header fields that would have been sent in a [200 (OK)](https://www.rfc-editor.org/rfc/rfc9110#status.200) response to the same request:
>
>[Content-Location](https://www.rfc-editor.org/rfc/rfc9110#field.content-location), [Date](https://www.rfc-editor.org/rfc/rfc9110#field.date), [ETag](https://www.rfc-editor.org/rfc/rfc9110#field.etag), and [Vary](https://www.rfc-editor.org/rfc/rfc9110#field.vary)
Cache-Control and Expires (see [[CACHING](https://www.rfc-editor.org/rfc/rfc9110#CACHING)])

Jetty's `GzipHandler` adds a `Vary` header for 200 responses it gzips, but doesn't add it for corresponding 304 responses.

`GzipHttpOutputInterceptor`, which `GzipHandler` uses to modify responses, [infers from the ETag](https://github.com/eclipse/jetty.project/blob/jetty-11.0.12/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java#L148) whether a 304 response it is handling refers to a resource it previously compressed, so perhaps the `Vary` header could be added at this point?

**How to reproduce?**
Using the following class:
```java
package com.example;

import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.gzip.GzipHandler;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;

import java.io.IOException;
import java.io.Writer;
import java.util.UUID;

public class GzipETagServer {
    public static void main(String[] args) throws Exception {
        final Server server = new Server(8080);
        final ServletContextHandler servletContextHandler = new ServletContextHandler();
        servletContextHandler.addServlet(new ServletHolder(new FooServlet()), "/foo");
        final GzipHandler gzipHandler = new GzipHandler();
        gzipHandler.setHandler(servletContextHandler);
        server.setHandler(gzipHandler);
        server.start();
    }

    private static final class FooServlet extends HttpServlet {

        private final String eTag = '"' + UUID.randomUUID().toString() + '"';

        @Override
        protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
            resp.setHeader("etag", eTag);
            if (eTag.equals(req.getHeader("if-none-match"))) {
                resp.setStatus(304);
            } else {
                resp.setStatus(200);
                try (Writer responseWriter = resp.getWriter()) {
                    responseWriter.write("Foo".repeat(100));
                }
            }
        }
    }
}
```
Visiting http://localhost:8080/foo in a browser will result in a gzipped 200 response with `Vary` header `Vary: Accept-Encoding` (and `ETag` e.g. `ETag: "9af0190a-7fb3-4511-873c-75a6fad51345--gzip"`).  Visiting the same address again will result in a 304 response, but with no `Vary` header (with the same `ETag`

**Comment by joakime** [comment]
Opened PR #8906
