### ISSUE TITLE
HttpWriter.write blocks indefinitely

### ISSUE THREAD

**Issue by jllanes3** [eclipse/jetty.project#8911]
**Jetty version(s)**
_[Jetty 9.x is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958)_
9.4.5.v20170502

**Java version/vendor** `(use: java -version)`
8

**OS type/version**
MacOS

**Description**
See last comment here:
https://github.com/eclipse/jetty.project/issues/2380

**How to reproduce?**
(see last comment in closed issue above)

NOTE: We can close this one issue if we re-open the previous one. Or I can copy paste all that comment here.

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958
