### ISSUE TITLE
Jetty's use of `java.util.ServiceLoader$Provider` breaks on Android (as it is not present)

### ISSUE THREAD

**Issue by chefchefchef** [eclipse/jetty.project#8912]
**Jetty version(s)**
Jetty 11

**Java version/vendor** `(use: java -version)`
Dalvik

**OS type/version**
Android SDK 33

**Description**
With Javalin 4 (Jetty 9) and Android I had no problems. After migrating to Javalin 5 (Jetty 11) my server doesn't startup anymore. in JDK 11 I can find the missing class ([ServiceLoader$Provider](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.Provider.html)) but in android sdk I cannot (https://developer.android.com/reference/java/util/ServiceLoader). I use Java 11 and compileSdkVersion 33. I cannot find ServiceLoader$Provider in SDK of Android API 33 (when decompiled).

<pre><code>E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.xxx.yyy, PID: 6634
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/ServiceLoader$Provider;
        at org.eclipse.jetty.util.TypeUtil.serviceProviderStream(TypeUtil.java:800)
        at org.eclipse.jetty.http.PreEncodedHttpField.<clinit>(PreEncodedHttpField.java:42)
        at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:91)
        at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:49)
        at org.eclipse.jetty.http.MimeTypes$Type.values(MimeTypes.java:47)
        at org.eclipse.jetty.http.MimeTypes.lambda$static$0(MimeTypes.java:169)
        at org.eclipse.jetty.http.MimeTypes$$ExternalSyntheticLambda4.get(Unknown Source:0)
        at org.eclipse.jetty.util.Index$Builder.withAll(Index.java:346)
        at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:883)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.server.Server.start(Server.java:470)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
        at org.eclipse.jetty.server.Server.doStart(Server.java:415)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at io.javalin.jetty.JettyServer.start(JettyServer.kt:74)
        at io.javalin.Javalin.start(Javalin.java:171)
        at io.javalin.Javalin.start(Javalin.java:148)
        at ch.xxx.yyy.server.YYYServer.start(YYYServer.kt:237)
        at ch.xxx.yyy.server.ServerBinder.start(ServerBinder.kt:31)
        at ch.xxx.yyy.startup.ServerStateHandler$manage$1$1.invokeSuspend(ServerStateHandler.kt:30)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1766ac3, Dispatchers.Main.immediate]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.ServiceLoader$Provider" on path: DexPathList[[zip file "/data/app/~~vM8Ki57CqJhIAaTm3OsTqw==/ch.xxx.yyy-S1y5IOg5qayhzEybJnMheg==/base.apk"],nativeLibraryDirectories=[/data/app/~~vM8Ki57CqJhIAaTm3OsTqw==/ch.xxx.yyy-S1y5IOg5qayhzEybJnMheg==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 32 more</code></pre>

**How to reproduce?**
Run Javalin 5 / Jetty 11 on Android

**Comment by joakime** [comment]
We cannot fix this.

`java.util.ServiceLoader.Provider` was added in OpenJDK 9.

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.Provider.html

There many components that rely on this, and Jetty is only a small part of this reliance.
This is problem outside of our control, and seems to be entirely within Android, or your use of the Android SDK.

Looking at the android source tree, their JDK 11 has the above class.
https://android.googlesource.com/platform/libcore/+/refs/tags/jdk11u/jdk-11.0.18+3/src/java.base/share/classes/java/util/ServiceLoader.java#440

**Comment by joakime** [comment]
Closing, this works for others on Android.
You have to configure your project to compile on Java 11.
This error only shows up if you haven't done that properly.

**Comment by zugazagoitia** [comment]
I can't get it working any way, using JDK11 and Android SDK33.

I tested for JDK 11 using [this API](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()):
https://github.com/zugazagoitia/jett11-android13-mpoc/blob/6bda1e48c7dcaeedde9a88b9d378a5c2ddc0894d/app/src/main/java/com/example/sample/MainActivity.java#L34

You can find a minimal working example here: https://github.com/zugazagoitia/jett11-android13-mpoc

The `java.lang.NoClassDefFoundError` is raised as soon as a request is made. Javalin just used another Jetty class to trigger the same result earlier. 

The reason, as stated earlier, is clear: the [`ServiceLoader`](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-33/blob/master/java/util/ServiceLoader.java) class in the android SDK is missing the `Provider` interface used by Jetty.

**My question is** will this be addressed or is it a priority at all?

**Comment by sbordet** [comment]
@zugazagoitia did you open an issue to the Android SDK to add the `Provider` interface?

**Comment by zugazagoitia** [comment]
> @zugazagoitia did you open an issue to the Android SDK to add the `Provider` interface?

I've just commented on [this issue](https://issuetracker.google.com/issues/263721391#comment1), which seems they were considering.

**Comment by zugazagoitia** [comment]
Update: [They implemented the rest of the `ServiceLoader` class](https://cs.android.com/android/_/android/platform/libcore/+/c906068af4f973d7371e480735400a65ed3aaac0) into the main working tree. This change is however **not** included in Android 14 (API Level 34) [[1]](https://developer.android.com/sdk/api_diff/34/changes)[[2]](https://developer.android.com/reference/java/util/ServiceLoader.html), likely in a future Android 15 and/or API Level 35 release scheduled for Q3 2024.

**Comment by LukeXeon** [comment]
This works for me, you can create a new Android module and make sure its build.gradle uses Java 1.8，here we temporarily call it "ponyfill".

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

Then create a placeholder **ServiceLoader** type under this module (you don’t need to actually implement it), and add the **Provider** interface definition inside it. Android will always load the system class first when loading a class, so it It will not use the **ServiceLoader** we used to place the placeholder, but when it cannot find the **Provider**, it will use the class we provided.


```
package java.util;

import java.util.function.Supplier;

public final class ServiceLoader<S> {
    public interface Provider<S> extends Supplier<S> {
        Class<? extends S> type();

        S get();
    }
}
```
Finally, you also need to "desugar" Java in your application module
```
android{

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.0.3'
    implementation project(":ponyfill")
}
```

**Comment by LukeXeon** [comment]
However, things are always full of compromises, and I found a case where Jetty called a method that didn't exist on Android. On Android's non-standard jdk, **ServiceLoader** has no **stream()** method no matter what version it is, and Google's "desugar" doesn't handle this, which is frustrating and causes crashes
[org/eclipse/jetty/util/security/Credential.java](https://github.com/jetty/jetty.project/blob/59105bef4de6a92ec26d844a38ea96f7ce4fdc2d/jetty-util/src/main/java/org/eclipse/jetty/util/security/Credential.java#L43)
Ideally it would be great if Jetty also used **ServiceLoaderSpliterator** to implement **Credential**
[org/eclipse/jetty/util/ServiceLoaderSpliterator.java](https://github.com/jetty/jetty.project/blob/59105bef4de6a92ec26d844a38ea96f7ce4fdc2d/jetty-util/src/main/java/org/eclipse/jetty/util/ServiceLoaderSpliterator.java#L22)
This is even just a piece of cake, maybe I can raise a PR if needed?

**Comment by iammmmmmm** [comment]
I successfully ran Javalin (depends on Jetty11) 6.0.1 on Android (SDK 33)! Although it is just a simple “Hello World,” it returned as expected.

I embedded Javalin in a JavaFX program and then successfully packaged the APK through the Maven plugin and GraalVM provided by Gluon. It successfully ran on both Android 9 and Android 13.

The entire test project’s code is available at:![here](https://github.com/iammmmmmm/blog/blob/master/cvAnyWhere.zip)

## Packaging Environment Information:

 ![GraalVM CE Gluon: GraalVM CE Gluon 22.1.0.1-Final](https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final)
Platform: Kali Linux x86
![image](https://github.com/user-attachments/assets/091c3f26-edd7-414e-9b65-605a4fd89358)
Build Tools: Maven and Gluon Maven Plugin

![G%33TO8@Z%WTUS25 JYI3O3](https://github.com/jetty/jetty.project/assets/73742531/58f4c9a7-9d70-4667-aff6-9c7b9e578920)
![image](https://github.com/jetty/jetty.project/assets/73742531/08252e68-2e2c-4ba6-992d-d72c4d6a913d)
![image](https://github.com/jetty/jetty.project/assets/73742531/72d0ce62-99f0-4fbe-8b19-7e40e5937b94)
<img width="369" alt="Snipaste_2024-08-08_11-22-32" src="https://github.com/user-attachments/assets/679a11e3-3495-432e-8d45-de2558d6a074">
![image](https://github.com/user-attachments/assets/432e318d-0522-4571-aa64-139c9b368e88)
![image](https://github.com/user-attachments/assets/07d69997-aeca-47cb-af70-48258866be10)
<img width="393" alt="Snipaste_2024-08-08_11-26-24" src="https://github.com/user-attachments/assets/3c75db18-5fbc-4256-969c-bcefd1df0a7b">

**Comment by emartynov** [comment]
> This works for me, you can create a new Android module and make sure its build.gradle uses Java 1.8，here we temporarily call it "ponyfill".
> 
> ```
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> ```
> 
> Then create a placeholder **ServiceLoader** type under this module (you don’t need to actually implement it), and add the **Provider** interface definition inside it. Android will always load the system class first when loading a class, so it It will not use the **ServiceLoader** we used to place the placeholder, but when it cannot find the **Provider**, it will use the class we provided.
> 
> ```
> package java.util;
> 
> import java.util.function.Supplier;
> 
> public final class ServiceLoader<S> {
>     public interface Provider<S> extends Supplier<S> {
>         Class<? extends S> type();
> 
>         S get();
>     }
> }
> ```
> 
> Finally, you also need to "desugar" Java in your application module
> 
> ```
> android{
> 
>     compileOptions {
>         coreLibraryDesugaringEnabled true
>         sourceCompatibility JavaVersion.VERSION_11
>         targetCompatibility JavaVersion.VERSION_11
>     }
> 
> }
> 
> dependencies {
>     coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.0.3'
>     implementation project(":ponyfill")
> }
> ```

Interesting that this class and method are in desugaring library https://github.com/google/desugar_jdk_libs/tree/master/jdk11/src/java.base/share/classes/java/util

**Comment by emartynov** [comment]
Not sure if desugaring is also applied for the test app (I assume that WireMock is running in context of the test app).

**Comment by zugazagoitia** [comment]
> Update: [They implemented the rest of the `ServiceLoader` class](https://cs.android.com/android/_/android/platform/libcore/+/c906068af4f973d7371e480735400a65ed3aaac0) into the main working tree. This change is however **not** included in Android 14 (API Level 34) [[1]](https://developer.android.com/sdk/api_diff/34/changes)[[2]](https://developer.android.com/reference/java/util/ServiceLoader.html), likely in a future Android 15 and/or API Level 35 release scheduled for Q3 2024.

Since [Android 15 has been released](https://android-developers.googleblog.com/2024/09/android-15-is-released-to-aosp.html), I think this issue can be closed. @joakime @sbordet

**Comment by sbordet** [comment]
Thanks for the feedback!
