### ISSUE TITLE
Unable to start SSL in linux after migrating to 9.3.x 'invalid keystore format'

### ISSUE THREAD

**Issue by chowdarynamala** [eclipse/jetty.project#892]
My solution was all fine when I used 9.2.x version , but after migrating to 9.3.x with same keystore, password and code it is throwing 'invalid keystore format'.

After searching in many blogs, forums I got to know that there is one change in 'SSLContextFactory.java' in 9.3.x version.

**The problem is seen only incase of executing in LINUX**

In 9.2.x it was 
public void More ...setKeyStorePath(String keyStorePath)
     {
         checkNotStarted();
         _keyStorePath = keyStorePath;
     }

where as in 9.3.x it is changed to 
public void setKeyStorePath(String keyStorePath)
    {
        checkNotStarted();
        try
        {
            _keyStoreResource = Resource.newResource(keyStorePath);
        }
        catch (MalformedURLException e)
        {
            throw new IllegalArgumentException(e);
        }
    }

Here is my sample sudo code which I am using.
Server httpServer = new Server();
SslContextFactory sslContextFactory = new SslContextFactory();
sslContextFactory.setKeyStorePath("/path/to/linux/file");
sslContextFactory.setKeyStorePassword("password");
sslContextFactory.setKeyManagerPassword("password");

ServerConnector sslConnector = new ServerConnector(httpServer, sslContextFactory, new HttpConnectionFactory(https_config));
sslConnector.setPort(8443);
httpServer.addConnector(sslConnector);
httpServer.start();

Please help me on resolving this issue.
Thanks
Lakshmi

**Comment by joakime** [comment]
Need more information.

You could enable debug logging for the server and see if there is anything useful (warning / error wise) that could help you.

The change to use `Resource.newResource()` would not have caused your problem.

The `Resource.newResource()` call will attempt to identify the type of resource you are referencing, (a raw filesystem path, a "file://" uri reference, a "jar:file://" uri reference, etc) and make the access to that via the Jetty standard Resource APIs. (something jetty uses extensively in many many places)

The cause of your problem isn't likely Jetty, but most likely a change in your JVM. (the overwhelming reason for "invalid keystore format")

Your existing keystore is likely using an old format, one that has long ago been deprecated by java, it was only a matter of time before it just stopped working entirely.  You just passed the point of no return in the process of upgrading.

You'll need to rebuild your keystore,  using the modern keytool found in your JDK.

If you have a certificate already, then make sure its a PKCS12 format and then build your keystore using the keytool in Java.

If you don't have a certificate already (you are building one, or have a self-signed one), or have a certificate that isn't in PKCS12 format, then use the openssl tooling to convert it to PKCS12 format before using the Java keytool.

See: https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html

**Comment by joakime** [comment]
Also, you might want to show us the entire stacktrace for the "Invalid Keystore Format" error you are receiving (it can often help to identify which keystore its failing on. the Jetty one, or one of the JVM ones)

**Comment by chowdarynamala** [comment]
Hi,

Thank you for your inputs. I can collect following log traces for the exception. I will try on your inputs related to regenerating keystore with new keytool.


java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:650)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:55)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at Test.main(Test.java:32)

Also simple code snippet is below.

KeyStore keystore = KeyStore.getInstance(KeyStore.getDefaultType());
            File file = new File("/some/path/myKs.p12");
            try (InputStream stream = new FileInputStream(file.getAbsolutePath()))
                {
                    System.out.println(file.getAbsolutePath());
                    System.out.println(stream);
                    keystore.load(stream, "password".toCharArray());
                } catch (NoSuchAlgorithmException | CertificateException ex) {
                Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
            }

**Comment by chowdarynamala** [comment]
Dear All,

The issue is resolved after rebuilding with new JDK keytool.  
The keytool will generate only .jks format? If I need to generate .p12 with java 1.8 version can you please suggest me to do so?

Thanks lot for your support and input.

**Comment by joakime** [comment]
jks is the format that java has, and pkcs12 is the more general purpose format (which java supports too). 

IIRC, both are valid on java.

**Comment by chowdarynamala** [comment]
I made one small change in my implementation, added below line to support pkcs12 
sslContextFactory.setTrustStoreType("PKCS12");

This resolved the problem
