### ISSUE TITLE
HttpClient GZIPContentDecoder should remove Content-Length and Content-Encoding: gzip

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#8926]
**Jetty version(s)**
Jetty 10 / 11 / 12

**Description**
When the Jetty HttpClient's `GZIPContentDecoder` modifies the response and decodes a GZIP'd response automatically, it should remove the response `Content-Length`, `Content-Encoding`, and `Transfer-Encoding` response headers.

**Comment by Jakester78** [comment]
What's all this mean  what do I need to do to cash out and repurpose
