### ISSUE TITLE
Review naming of FrameHandler.isDemanding() in Jetty 12

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#8991]
Currently `FrameHandler` has a method called `isDemanding()` which specifies whether a `FrameHandler` will have to manage its own flow control by using the `CoreSession.demand()` method.

`demanding == false` means that demand is combined with the callback.
`demanding == true` means that frame handler must use `demand()` method.

Simone says this is confusing and this should be renamed in Jetty 12.
see https://github.com/eclipse/jetty.project/pull/8487#discussion_r1031768282

**Comment by gregw** [comment]
Kind of agree the name (out at least the sense of the boolean) is messed up (yes it was my name).

Something like `isAutoDemand` would be clearer.

**Comment by sbordet** [comment]
Fixed by #9328.
