### ISSUE TITLE
Extending HttpServlet

### ISSUE THREAD

**Issue by headlamp-software** [eclipse/jetty.project#8992]
9.4.42

Hi, I create classes to extend HttpServlet in a couple of places. No problems to date. However, I noticed in the my code that I don't have constructors for my classes that extend HttpServlet. Should I? I also noticed that I don't call super() anywhere for my classes that extend HttpServlet. Should I?

Thank you

Peter Schaeffer

**Comment by sbordet** [comment]
> However, I noticed in the my code that I don't have constructors for my classes that extend HttpServlet. Should I? 

No. A default, parameterless constructor is automatically added by the `javac` compiler.

> I also noticed that I don't call super() anywhere for my classes that extend HttpServlet. Should I?

No, it is not necessary.

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Please upgrade to Jetty 10 (or newer) when possible

**Comment by headlamp-software** [comment]
Thank you

Peter Schaeffer
