### ISSUE TITLE
Support java:module/ModuleName lookups and injection via @Resource

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#90]
migrated from Bugzilla [#329177](https://bugs.eclipse.org/bugs/show_bug.cgi?id=329177)
status ASSIGNED severity _enhancement_ in component _server_ for _7.1.x_
Reported in version _8.0.0_ on platform _All_
Assigned to: Jan Bartel

On 2010-11-01 03:22:48 -0400, Jan Bartel wrote:

> Consider adding support for the java: namespace hierarchy introduced with Javaee6.

On 2010-11-01 03:28:44 -0400, Jan Bartel wrote:

> Depends on bug # 329175 in the sense that in order to do the injection, you need to be able to specify the lookup= params to @Resource.

**Comment by janbartel** [comment]
There is no demand for jetty to implement this, so I'm closing this issue.
