### ISSUE TITLE
Maven invoker plugin does not support jdk19 with groovy

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9000]
**jetty-12.0.x**

All of the jetty maven plugin it tests are failing on the jdk19 build but passing on the jdk17 build.

The build log shows:

> BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 63
> 	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:905)
> 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
> 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
> 	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
> 	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
> 	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
> 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
> 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
> 	at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
> 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:426)
> 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
> 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
> 	at org.apache.maven.shared.scriptinterpreter.GroovyScriptInterpreter.evaluateScript(GroovyScriptInterpreter.java:76)
> 	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.executeRun(ScriptRunner.java:236)
> 	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.run(ScriptRunner.java:161)
> 	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runPostBuildHook(AbstractInvokerMojo.java:2154)
> 	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:2129)
> 	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1721)
> 	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.lambda$runBuilds$4(AbstractInvokerMojo.java:1431)
> 	at org.apache.maven.plugins.invoker.JobExecutor.lambda$null$1(JobExecutor.java:69)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1589)
> Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
> 	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
> 	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
> 	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
> 	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
> 	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:506)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolveFromDefaultImports(ResolveVisitor.java:661)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolveFromDefaultImports(ResolveVisitor.java:625)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:505)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:468)
> 	at org.codehaus.groovy.control.ResolveVisitor.transformVariableExpression(ResolveVisitor.java:1129)
> 	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:888)
> 	at org.codehaus.groovy.control.ResolveVisitor.transformPropertyExpression(ResolveVisitor.java:1013)
> 	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:890)
> 	at org.codehaus.groovy.control.ResolveVisitor.transformMethodCallExpression(ResolveVisitor.java:1274)
> 	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:896)
> 	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:108)
> 	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
> 	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
> 	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:164)
> 	at org.codehaus.groovy.control.ResolveVisitor.visitBlockStatement(ResolveVisitor.java:1566)
> 	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
> 	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
> 	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
> 	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
> 	at org.codehaus.groovy.control.ResolveVisitor.visitConstructorOrMethod(ResolveVisitor.java:294)
> 	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:106)
> 	at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1100)
> 	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1093)
> 	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
> 	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1483)
> 	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:262)
> 	at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:738)

**Comment by olamy** [comment]
already under investigation here https://github.com/apache/maven-invoker-plugin/pull/154

**Comment by joakime** [comment]
No longer an issue
