### ISSUE TITLE
Flaky Test `ConnectionPoolTest.testConcurrentRequestsAllBlockedOnServer`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9005]
**Jetty version(s)**
10.0.13-SNAPSHOT

**Java version/vendor** `(use: java -version)`
JDK17

**Description**
Flaky Test on `jetty-10.0.x` HEAD.

```
org.eclipse.jetty.client@10.0.13-SNAPSHOT/org.eclipse.jetty.client.ConnectionPoolTest.testConcurrentRequestsAllBlockedOnServer(ConnectionPoolTest.java:447)
org.eclipse.jetty.client@10.0.13-SNAPSHOT/org.eclipse.jetty.client.ConnectionPoolTest.testConcurrentRequestsAllBlockedOnServerWithExactConnectionPool(ConnectionPoolTest.java:391)
```

See https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-10.0.x/1814/tests

**Comment by sbordet** [comment]
I think it's just matter of short timeout and/or too much load created by this test.
I'll reduce the values and submit a pull request.
