### ISSUE TITLE
Problems with WebSockets

### ISSUE THREAD

**Issue by headlamp-software** [eclipse/jetty.project#9034]
11.0.12

Java 17

Windows 10

For a long time I used Jetty 9.4.49. Then I switched to 11.0.12 (and switched from Java 11 to Java 17 at the same time). As it turns out, my code uses WebSockets (and other interfaces).

I got an error message that read 'WebSocketComponents has not been created'.

I solved this problem by adding 

JettyWebSocketServletContainerInitializer.configure(contextInternalWebSockets, null);

However, this wasn't (apparently) needed for 9.4.49. 

Is the new code correct? Was the old code correct?

**Comment by lachlan-roberts** [comment]
Yes you should be using the `JettyWebSocketServletContainerInitializer.configure` method. 

This is also described in the documentation for Jetty-11 see:
https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-websocket-standard-container
