### ISSUE TITLE
Jetty 12 - Review EE10 Http[Input|Output].Interceptor APIs

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9038]
**Jetty version(s)**
12+

**Description**
`HttpInput.Interceptor` has the same signature as `ContentSourceTransformer`, and should have a similar contract.
Furthermore, the current implementation has a API contract that is not precise, so it is possible that an `Interceptor` implementation releases the input (raw) chunk (which goes back into the pool), but the `HttpInput` implementation still references it, causing race conditions.
It would be best if the API contract could be aligned with the one in `ContentSourceTransformer`.

Also, `HttpOutput.Interceptor` should be a sub-interface of `Content.Sink` as their `write()` methods have the same signature.

**Comment by gregw** [comment]
+1  
It would be good if the demand flow could also go through the interceptors.

**Comment by gregw** [comment]
Note also that this should only be changed for the ee10 implementation. The ee8 and ee9 interceptors should remain as they are for the few users that have extended them.

**Comment by gregw** [comment]
The other option is for ee10 to not have interceptors.  They are no longer used by our own code, as we can simple wrap the request and response to do our gzip inflation/deflation now.
They were needed in ee8/ee9 as the servlet API is used to pass requests between handlers and it was impossible to wrap these to intercept both blocking and asynchronous dataflows.  Our new handle design makes that easy to do without the need for a specific interceptor API.   Thus it may be simplest to remove it from ee10 as we have no use-case for it.

**Comment by lachlan-roberts** [comment]
PR https://github.com/eclipse/jetty.project/pull/9040 has been merged so this can be closed.
