### ISSUE TITLE
Regression: Unable to retrieve the endpoint details once the connection is closed

### ISSUE THREAD

**Issue by veramasu** [eclipse/jetty.project#9044]
**Jetty version(s)**
Starting from 9.4.29.

**Java version/vendor** `(use: java -version)`
openjdk version "1.8.0_302"

**OS type/version**
Ubuntu 18.04

**Description**
As part of the code-cleanup activity in https://github.com/eclipse/jetty.project/commit/46ad90598c65d127124395db32172f381579a825 , SocketChannelEndpoint has been modified.  This is breaking the connection listener onClose. when OnClose is called, its missing the remoteAddress details. 

**How to reproduce?**
Simple HTTP2 server implementation with Connection Listerns and print the remoteAddress details. 

``` java
	server.addConnector(http2Connector);
						http2Connector.addBean(new Connection.Listener() {
							public void onOpened(Connection connection) {
								System.out.println(connection.getEndPoint().getRemoteAddress());
							}

							public void onClosed(Connection connection) {
								System.out.println(connection.getEndPoint().getRemoteAddress()); --> will throw NPE
							}
						});
```

**Comment by sbordet** [comment]
I just tried your snippet with the latest code in 9.4.x, and it does not throw NPE.

The remote address is `null` as it should be, as this event is delivered _after_ the `EndPoint` is closed, so the information about the remote address does not exist anymore.

I think this has always been the case, as it is a built-in behavior of the JDK Socket APIs.

**Comment by veramasu** [comment]
Hi @sbordet ,

Thanks for your reply. No until 9.4.28 the remote Address used to be available in the onClose event. But from 9.4.29 its not passed. We keep the audit of what remote address and port connected and closed. Now after moving above 9.4.29, our audit functionality is broken as its not giving the remoteAddress during OnClose event. If you can check with 9.4.28 and 9.2.49 you could see the difference

**Comment by sbordet** [comment]
Yes I can see it's a difference between 9.4.28 and 9.4.29.

If you want to retain the remote address in the `onClose()` event, you have to map it in `onOpen()`.

A gentle reminder that Jetty 9.4.x is End of Community Support, see #7958.

**Comment by veramasu** [comment]
The audit log implementation is like whenever the new connection opened (onOpen()) we get the remoteAddress (Host ,Port) and keep them as the Key as the localAddress will be always same. Upon close(onClose() event) we retrieve the remoteAddress and remove from the cache. While I understand the 9.4.x is reached End of Community support, can this be included in the next version of the 9.4.x ?

**Comment by sbordet** [comment]
You can use the `EndPoint` as the key with the same results.

**Comment by joakime** [comment]
The behavior of if you can access the remote address from a closed SocketChannel is what Java provides, not Jetty.

See: https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SocketChannel.html#getRemoteAddress--

In fact, in Jetty 10+ we even guard for this behavior to prevent exceptions from flowing out during onClose / Logging / etc

See: https://github.com/eclipse/jetty.project/blob/jetty-10.0.13/jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java#L45-L57

https://github.com/eclipse/jetty.project/blob/1c2636ea05c0ca8de1ffd6ca7f3a98ac084c766d/jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java#L45-L57

The fact that you were able to access the remote address before was a total fluke and is considered an error.

> You can use the `EndPoint` as the key with the same results.

Or you can use the `Connection` itself as the key as well.
