### ISSUE TITLE
fqdn resolution to application provided IP

### ISSUE THREAD

**Issue by souravgupta6nov1992** [eclipse/jetty.project#9049]
dns resolution for every request

Jetty version(s)
11.0.11
Java version/vendor (use: java -version)
17.0.1
Spring boot version(s)
2.7.4
OS type/version
Linux

We are using jetty client over http2 to make async calls

       private WebClient destWebClient;

       @PostConstruct
	public void init() {
		SslContextFactory sslContextFactory = new SslContextFactory.Client(true);
		ClientConnector clientConnector= new ClientConnector();
		clientConnector.setSslContextFactory((SslContextFactory.Client) sslContextFactory);
		HTTP2Client http2Client = new HTTP2Client();
		http2Client.setMaxConcurrentPushedStreams(1000);
		HttpClientTransportOverHTTP2 transport = new HttpClientTransportOverHTTP2(http2Client);
		transport.setUseALPN(false);
		transport.updateBean(transport.getBean(ClientConnector.class), clientConnector);
		this.httpClient = new HttpClient(transport);
		this.httpClient.setIdleTimeout(600000);

		this.httpClient.setMaxRequestsQueuedPerDestination(5000);
		this.httpClient.setMaxConnectionsPerDestination(4);
		this.httpClient.setFollowRedirects(false);
		this.httpClient.setRemoveIdleDestinations(true);
		this.httpClient.getRequestListeners().add(new JettyClientRequestMetrics());
		try {
			httpClient.start();
		} catch (Exception e) {
			e.printStackTrace();
		}
		ClientHttpConnector httpConnector = new JettyClientHttpConnector(httpClient);
		this.destWebClient = WebClient.builder().clientConnector(httpConnector).baseUrl(extUrl).build();
	}

Following API is used to send the message

			Mono<ResponseEntity<byte[]>> MonoRsp = destWebClient
				.method(HttpMethod.resolve(contextData.getRequestEntity().getMethod().name())).uri(uri)
				.headers(hdrs -> hdrs.addAll(httpHeaaders))
				.body(BodyInserters.fromValue(body)).retrieve().toEntity(byte[].class)
				.timeout(Duration.ofMillis(perTryTimeout.getTimeMillis()))
				.onErrorResume(Throwable.class, throwable -> {
					Mono<ResponseEntity<byte[]>> rsp = Mono.just(handleError(throwable, contextData));
					return rsp;
				}).doOnCancel(() -> logger.info("Dest Request transaction has been Canceled"))
				.publishOn(Schedulers.fromExecutor(testExecutor));

We have the ips for the fqdn we want to make connections to already resolved with us but that information is very dynamic in nature and can change at any time
But in the uri, we can only pass the fqdn
e.g. fqdn1 resolves to ip1 and ip2

If request comes for fqdn1 we should establish a connection to ip1 and to ip2 based on our load balancing algorithm
but there can be requests where it can be dynamically decided that to same fqdn fqdn1, for which connections are already established in the destination, name resolution should happen from the dns server
lets say there are 3 requests: r1, r2, r3 for the same fqdn1
r1 should connect to ip1
r2 should connect to ip2

some configuration changes came and now we do not have the resolved ips
r3 should resolve ip from nameserver and connect to that ip

some configuration changes come in our backend and now the values of ip1 and ip2 change to ip3 and ip4, respectively and we don not care about ip1 and ip2 anymore
Now,requests: r4 and r5
r4 should connect to ip3
r5 should connect to ip4

I tried giving a custom socketaddress resolver

        httpClient.setSocketAddressResolver(socketAddressResolver());

	private SocketAddressResolver socketAddressResolver() {
		return new SocketAddressResolver() {
			
			@Override
			public void resolve(String host, int port, Promise<List<InetSocketAddress>> promise) {
				System.out.println("host for resolution: {}"+ host);
				InetAddress inetAddress = null;
					try {
						inetAddress = InetAddress.getByName(ip1); // i can pass ip1, ip2 or fqdn1 here based on my custom logic
					} catch (UnknownHostException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
						promise.failed(e);
						return;
					}
				InetSocketAddress inetSocketAddress = new InetSocketAddress(inetAddress, port);
				promise.succeeded(List.of(inetSocketAddress));
				
			}
		};
	}
	
But the issue i saw here was this address resolver gets called only 1 time for a fqdn, after that it reuses the connections already formed

For request r1 where i want to connect to ip1, this method gets called and resolves to ip1 but for request r2, this method is not getting called so i cannot pass it the ip2 and for request r3 i cannot pass it the same fqdn itself
All 3 requets will connect to the same connection resoved in the very first request for the same fqdn

if we give an array of ips ip1 and ip2 here, if the connection attempt to ip1 fails or even a request fails, that information should be propagated back to our code before trying the next ip ip2

We had some look into the code base for jetty and observed that the key Origin used for reusing the connections is based on the host from the request which in our case would be fqdn1. For the next request same key is used and hence it gets the same connection.

Any suggestions on how this can be achieved

**Comment by sbordet** [comment]
You want an extremely dynamic destination resolution, I think you can do it by overriding `HttpClient.resolveDestination(Origin)`.

I did not try, but in pseudo-code should look like this:

```java
new HttpClient(transport) {
  @Override
  public HttpDestination resolveDestination(Origin origin) {
    AddressConfig config = addressConfig.snapshot();
    Origin newOrigin = new Origin(origin.getScheme(), config.getAddress(), origin.getTag(), origin.getProtocol());
    return super.resolveDestination(newOrigin);
  }
};
```

The key is that `addressConfig.snapshot()` returns an immutable address configuration that you want to use for that request.
The next call to `addressConfig.snapshot()` returns a possibly different, immutable, address configuration.
If the address configuration changes, the next call to `addressConfig.snapshot()` returns the updated configuration, and so on.

With the new address information you create a new `Origin` and use that instead of the original one, and you should be good.

Please let us know if this works for you.

**Comment by souravgupta6nov1992** [comment]
Thanks so much for the reply.
We are able to achieve this as per your suggestion
we are overriding the below method following the direction of your suggestion, where we are just overriding the host if we need to with our own resolved IP

		this.httpClient = new HttpClient(transport) {
			@Override
		    public Origin createOrigin(HttpRequest request, Origin.Protocol protocol)
		    {
		        String scheme = request.getScheme();
		        if (!HttpScheme.HTTP.is(scheme) && !HttpScheme.HTTPS.is(scheme) &&
		            !HttpScheme.WS.is(scheme) && !HttpScheme.WSS.is(scheme))
		            throw new IllegalArgumentException("Invalid protocol " + scheme);
		        scheme = scheme.toLowerCase(Locale.ENGLISH);
		        String host = request.getHost();
		        host = host.toLowerCase(Locale.ENGLISH);
				//our implementation
		        List<HttpCookie> cookies = request.getCookies();
		        logger.info("cookies: {}",cookies);
		        String ip = getIpFromCookies(cookies);
		        if(StringUtils.isNotBlank(ip)) {
		        	host = ip;
		        }
				//our implementation
		        int port = request.getPort();
		        port = normalizePort(scheme, port);
		        return new Origin(scheme, host, port, request.getTag(), protocol);
		    }
		};

would it be possible for you to enhance your codebase to allow the user to pass ip additionally for every request along with uri so that dns resolution is not done for the fqdn when IP is passed

**Comment by sbordet** [comment]
> would it be possible for you to enhance your codebase to allow the user to pass ip additionally for every request along with uri so that dns resolution is not done for the fqdn when IP is passed

I don't understand this one, sorry.
Jetty does not do DNS resolution at this point.

**Comment by souravgupta6nov1992** [comment]
@sbordet I mean the ip that we pass additionally should be used as the basis for key to keep the connections and later when dns resolver is called during making the connection that ip would be already present with client so need to do resolution.
Utimately the request will have fqdn in the uri but during resolution and key formation ip will used

**Comment by sbordet** [comment]
Still don't understand.

The IP you pass to `Origin` is a `String`, so no DNS resolution.

Every different `Origin` produces a different `HttpDestination`, and each `HttpDestination` has its own connection pool.

We normally do DNS resolution when we need to open a new connection to a particular destination.
Because you are passing IP addresses to the destinations there will be no DNS resolution involved.

**Comment by souravgupta6nov1992** [comment]
What we meant is, to achieve this functionality we had to override the Jetty API (as mentioned above) in our code.
The ask is, will it be possible for you to support this behavior inside Jetty where user is asked to provide following info for sending a HTTP2 request
1. All existing params +
2. User resolved IP (optional) <-- Proposal from our side
Jetty will do the following :
1. Use the IP if provided by user to establish TCP connection (create ORIGIN using this IP and port from authority) and send HTTP2 message (no need to perform DNS Resolution)
2. If IP is not provided by user, Jetty's usual flow continues

**Comment by sbordet** [comment]
@souravgupta6nov1992 we will not do changes to 9.4.x unless sponsored by a client, so what proposed below would possibly go in 10+.

What we can do is to try to pull the authority from the `Host` header if present.

```java
httpClient.newRequest(ip1, port)
  .version(HttpVersion.HTTP_2)
  .headers(h -> h.put(HttpHeader.HOST, "fqdn:" + port));
  .send()
```

And then modify `HpackEncoder` to check first for the `Host` header to get the authority, and if that is not present then use the authority from the URI.

**Comment by souravgupta6nov1992** [comment]
Hi @sbordet ,
This looks nice.

Few questions below:
- Will you send the Host header in the outgoing request. Can we optionally control sending of Host header in this case?
- Since we are using 11+ version of jetty httpClient, any timeline when we can expect this update?

Thanks in advance.

**Comment by souravgupta6nov1992** [comment]
Hi @sbordet ,
Any update on this.

**Comment by joakime** [comment]
Seems like your problem space could be solved by using the existing tag facilities in Jetty Client to manage this artificial load balancing.
Instead of manipulating the host / IP / etc and causing all kinds of bad behavior in the JVM SSLContext/SSLEngine (which increasingly enforces fqdn, and rejects ips with each new release of the JVM)

Each request can have a tag that marks the request belonging to a group that is managed separately by the ConnectionPool, never allowing a tag-A to talk on a connection belonging to tag-B (and vice-versa)

**Comment by sbordet** [comment]
@souravgupta6nov1992 can you try the following:

```java
// Do the IP resolution for your fqdn.
String ip = ...;

// Resolve a destination based on that IP.
Origin origin = new Origin(scheme, ip, port);
HttpDestination destination = httpClient.resolveDestination(origin);

// Create a request with the fqdn host.
Request request = httpClient.newRequest(fqdn, port);

// Send the request through the destination.
destination.send(request, result -> {
    ...
});
```

Does it work for you?

**Comment by souravgupta6nov1992** [comment]
yes it does. we have implemented this and proceeding with it.
What we want to ask is, as replied by you earlier:
                  **"**
             @souravgupta6nov1992 we will not do changes to 9.4.x unless sponsored by a client, so what proposed below                  
                would possibly go in 10+.
                  
                  What we can do is to try to pull the authority from the Host header if present.
                  
                  httpClient.newRequest(ip1, port)
                    .version(HttpVersion.HTTP_2)
                    .headers(h -> h.put(HttpHeader.HOST, "fqdn:" + port));
                    .send()
                  And then modify HpackEncoder to check first for the Host header to get the authority, and if that is not present then use the authority from the URI.**"**

Regarding this solution which you said you could incorporate in your library in the later relese, Will you send the Host header in the outgoing request. Can we optionally control sending of Host header in this case?

**Comment by sbordet** [comment]
Using the `Destination` is an existing and better solution, so we won't implement the other one that I proposed.

**Comment by sbordet** [comment]
Closing, as solution already exists via `HttpDestination.send(Request, CompleteListener)`.
