### ISSUE TITLE
Jetty terminates SSL connections too early with Connection: close

### ISSUE THREAD

**Issue by chuckdumont** [eclipse/jetty.project#905]
This is similar to  #359, but with TLS1.2 connections.  Closing the outbound side of the connection appears to cause the TLS layer to issue an Encrypted Alert, followed by a FIN/ACK.  The server responds by returning a FIN/ACK with no response data.  The Encrypted Alert effectively closes the connections for both outbound and inbound data since, were the connection not being closed, it would require SSL renegotiation to take place.  Not sure if this is because the outbound connections is being closed improperly, or if it needs to be kept open until the response has been received.

Either way, this new behavior (closing the outbound connection without waiting for the response) should at least be configurable so that it could be disabled when it causes problems.

![wireshark](https://cloud.githubusercontent.com/assets/273476/18292299/7903ec9e-745a-11e6-893c-649b1c4fe7fe.png)

**Comment by gregw** [comment]
Version?   Client or Server?    Http/1.0, Http/1.1 or http/2.0?   Normal close? timeout? close after response???

**Comment by chuckdumont** [comment]
Version is 9.3.9.v20160517 (Eclipse Neon).  Http/1.1.  Using HttpClient with ProxyServlet.Transparent.  Getting EOFException attempting to receive the proxied response in the HttpClient.  See the log details below:

[log.txt](https://github.com/eclipse/jetty.project/files/458009/log.txt)

**Comment by chuckdumont** [comment]
More info:  The problem does not reproduce in Eclipse Mars (Jetty 9.2.13).  The problem seems to have been introduced with https://github.com/eclipse/jetty.project/commit/8c21871cf0ac74ee9569248f3c534e211728b507 by the following change in org/eclipse/jetty/http/HttpGenerator.java:

![image](https://cloud.githubusercontent.com/assets/273476/18297731/01673f0c-7481-11e6-84fc-b657f2c6023f.png)

**Comment by chuckdumont** [comment]
Aside from what appears to be TLS layer issues with premature closing of the outbound connection, I see other problems with this behavior.  How is the client supposed to ACK receipt of the response?  What if there was a problem with receipt of the response and re-transmission needs to be requested at the TCP level?  With the server no longer listening, there's no way to do so.

What was the original motivation for aggressively closing the outbound connection following transmission of the request when Connection:close is requested?

**Comment by joakime** [comment]
It is the right place.
This bug hasn't been reproduced yet using Jetty 9.3.9 Server with an HTTPS ServerConnector and a ProxyServlet.Transparent, using Jetty 9.3.9 HttpClient with HTTP/1.1 to connect to that server.

Can you detail your configuration of the Server side a bit more? (we are missing something)
Also, any details you can give on the SSL/TLS side could be helpful too.  What hosts, what ciphers, what protocols, did you configure your SslContextFactory?

What specific version of Java are you using?  Did you modify the default Java JVM security.properties to enable/disable anything in SSL/TLS?

**Comment by sbordet** [comment]
@chuckdumont, this is the right place to report bugs.

Problem is, this is not really a Jetty defect.

Even if we are willing to add an option to make the behavior configurable, it would complicate things quite a bit, since we will have to schedule the TCP FIN "later".
What if the server misbehaves (like it already does) and does not close the connection ? We would be leaking a connection.
There are a lot of cases to cover to make sure that if we don't send the TCP FIN when we should, then eventually we will. Misbehaving servers, timeouts, HTTP/2 semantic, etc., etc. All potential causes for connections leakage.

To me this is a low-priority enhancement.

**Comment by chuckdumont** [comment]
Not sure I agree that the server is misbehaving here.  It's the client that's sending the Encrypted Alert followed immediately by the FIN/ACK.  I'm not a protocol expert, but it seems to me that if there's any misbehaving, it's the TLS layer not properly handling the close of the outbound connection.  Maybe there's some SSL level house-keeping that needs to take place in the client before the outbound connection can be safely closed.

**Comment by chuckdumont** [comment]
In response to @sbordet, the server is an IBM Domino server behind an F5.  I can't point you to it as it's not on the public internet.  Here's the setup I'm using for the HttpClient in the proxy.
```
  /* (non-Javadoc)
   * @see org.eclipse.jetty.proxy.AbstractProxyServlet#newHttpClient()
   */
  @Override
  protected HttpClient newHttpClient() {
    SslContextFactory scf = new SslContextFactory();
    scf.setTrustAll(true);
    scf.addExcludeProtocols(EXCLUDED_PROTOCOLS);  // Exclude SSL so that we use only TLS
    // F5 doesn't allow client initiated SSL renegotiation
    scf.setRenegotiationAllowed(false);
    return new HttpClient(new HttpClientTransportOverHTTP(), scf);
  }
```
Connection-Close header is added by the proxy to all outbound requests.  

Java version is 1.8.0_102-b14.  No modifications to the JVM security.properties file.

**Comment by sbordet** [comment]
It is perfectly legal to half close a TCP connection. TLS also has a half-close protocol. 

The fact that the client sends a TLS half-close and a TCP half-close only means that it's not sending more data. However, it can read more data. 

If the server interprets these half-closes from the client as "the connection is completely closed", then I don't think it's the right interpretation. The half-closes exist exactly to cover such scenario, otherwise there would not be half-closes, just hard closes.

Do you know if it's F5 or Domino that does not like the half-closes ?
Which element offloads TLS, F5 or Domino ?

>`Connection: close` header is added by the proxy to all outbound requests.

What do you mean here ? Jetty's proxy servlets don't add `Connection: close` to outbound request, so it must be something else that adds them.
Are you using HTTP/1.0 ?

**Comment by chuckdumont** [comment]
So you're saying the the Encrypted Alert sent by the client is carrying the TLS protocol half-close notification?  I don't have access to the SSL certificate for the F5 so I can't view the decrypted content of the alert.

The SSL connection is with the F5.  The F5<->Domino connection is not encrypted.  Looking at the F5 documentation, it looks like perhaps "Passive close" SSL Attribute documented [here](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ssl-administration-11-5-0/4.html)

**Comment by chuckdumont** [comment]
Turns out the "Passive close" SSL Attribute on the F5 doesn't help.  It's only available for the server-side SSL config and we aren't using SSL on the server-side.

**Comment by sbordet** [comment]
@chuckdumont just to be clear, it's: 

client -> F5 -> `ProxyServlet.Transparent` on a backend server

and the issue is that F5 closes the connection when the client sends the TLS Close + TCP FIN ?

Or you have client -> `ProxyServlet.Transparent` -> F5 -> some server ?
Or something else ?

**Comment by chuckdumont** [comment]
client -> `ProxyServlet.Transparent` -> F5 -> server.  The F5 is using SSL on the client-side, non-SSL on the server-side.

We're using `ProxyServlet.Transparent` in our development environments to allow web application resources to be loaded from an Eclipse workspace while proxying requests for data to test/production servers.

**Comment by sbordet** [comment]
Wait a moment. It's `ProxyServlet` that behaves badly, or F5 ?

**Comment by chuckdumont** [comment]
Well, I'm not quite sure.  I thought it was `ProxyServlet` (actually, the `HttpClient` inside of `ProxyServlet`) because it was sending a TLS Encrypted Alert prior to closing the outbound connection, but your previous post implied that the alert was actually the TLS protocol half-close notification, in which case, it would seem that Jetty is doing what it's supposed to and the F5 is misbehaving by closing the inbound connection without waiting for the server's response.

**Comment by sbordet** [comment]
Well, feel free to reopen if you find more details that point to Jetty not behaving correctly. Thanks !

**Comment by chuckdumont** [comment]
So I'm reopening because I can't seem to find a way to make the F5 play nice with the new half-close connection behavior in Jetty 9.3.  I'd like to reiterate my call for a config option that restores the 9.2 behavior (wait for server to close connection).

I am not saying that Jetty is doing anything wrong here.  It seems to be following the spec just as you claim.  But it seems clear that there are still servers in use that do not follow the spec in this regard and it would be good to have a way to make Jetty continue to work with these servers.

I'm not sure I understand your previously stated concern about such an option complicating things "quite a bit".  Jetty needs to be able to handle server initiated connection closes regardless of whether or not the close is in response to a `Connection-Close` header in the request.  If the concern is about misbehaving servers just not closing the connection, then I really don't think you need to worry about that.  Simply document the fact that if this option is used, then misbehaving servers could cause connections to be leaked and leave it at that.

**Comment by sbordet** [comment]
@chuckdumont you have not reopened, can you or you don't have the button in the UI ?

**Comment by chuckdumont** [comment]
Sorry, not sure what happened.

**Comment by sbordet** [comment]
You would be surprised by how many people use Jetty against broken clients or servers, and when Jetty leaks a file descriptor due to the other party broken behavior, people complains that Jetty should not leak, no matter how broken is the other party. And rightfully so.

What you're asking is a feature to support broken servers, which will then have to be carefully implemented and maintained by us. We can't just leak file descriptors.

Besides, we would need to know a lot more before implementing this feature. Whether it's actually F5 or not, what exactly is the trigger that makes the other party choke (the TLS close or the TCP FIN), etc.

Have you tried to file a bug to F5 (if it's really F5) ? Maybe they already have a fix and you just need to update the F5 box.

**Comment by joakime** [comment]
Is the F5 setup to talk HTTP/1.0 or HTTP/1.1 to the server?  (make sure its set to use HTTP/1.1)

**Comment by chuckdumont** [comment]
@sbordet, I would agree with you if this were a request for a new feature.  But it is actually a request to support legacy behavior.  That fact can be reinforced by the selection of the option name (e.g. LEGACY_CONNECTION_CLOSE).  Legacy behavior means legacy bugs.

**Comment by sbordet** [comment]
@chuckdumont just to be clear, it was a bug that we did not send the TCP FIN right away. So this is a new feature to support a legacy behavior that was buggy. You can understand why I'm reluctant.

**Comment by chuckdumont** [comment]
Understood.  But that doesn't change the fact that your fix breaks Jetty with some servers.  Yes, it's the server's fault.  But legacy bugs are a fact of life in our business and we often find ourselves making compromises to accommodate them.

I simply don't agree that supporting legacy connection-close behavior puts you on the hook for fixing all the issues associated with that behavior.  You already fixed the issues!  If someone want's to disable the fix, then they do so at their own peril.  Add a WARNING level log message that will alert you and the user that the option is enabled and that the warranty is voided.

**Comment by chuckdumont** [comment]
@joakime, the F5 is set up to support HTTP1.1 and HTTP2.  But I just learned that our network topology is a bit more complex than I thought.  It turns out that we have Akamai in between the Jetty proxy and the F5.  So the layout looks like this

client -> `ProxyServlet.Transparent` -> Akamai -> F5 -> Domino server

I'm told that Akamai terminates the SSL connection with the client and establishes another SSL connection between the Akamai servers and the virtual server on the F5.

**Comment by sbordet** [comment]
@chuckdumont I have been convinced that I was wrong about this, so standby for a fix. The behavior would be that the client will only close the connection when the request/response exchange is completed, or after the client idle timeout if the server does not close.

**Comment by chuckdumont** [comment]
Great news.  Thanks!
