### ISSUE TITLE
Alt-Svc

### ISSUE THREAD

**Issue by headlamp-software** [eclipse/jetty.project#9052]
11.0.12

Java 17

It looks like I should advertise HTTP/3 support using the Alt-Svc header. For example, something like 

```
Alt-Svc: h3-25=":443"
```

Should h3 be set to 25 or some other number?

**Comment by sbordet** [comment]
Should be:

```
Alt-Svc: h3=":443"
```

See https://httpwg.org/specs/rfc9114.html#alt-svc.

I don't think browsers support any port different from `443`.

**Comment by pschaeffer** [comment]
Thank you. Please close this question. Thank you again.
