### ISSUE TITLE
IteratingCallback not serializing close() and failed()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9059]
**Jetty version(s)**
10+

**Description**
Thread1 is inside `IC.process()`, acting on some custom state.

Thread2 calls `IC.close()` or `IC.failed(failure)`, and this may call `onCompleteFailure()` directly, which may (for example) reset the custom state, or null it out, etc.

Therefore, the contract of IC that it will serialize the processing is not respected, because now 2 threads can access the IC custom state.

We should be more precise at serializing in case of a `close()` call, and possibly introduce a `close(Throwable)` or `fail(Throwable)` different from `failed(Throwable)` if necessary to handle the serialization more precisely.

**Comment by sbordet** [comment]
@gregw throughts? See discussion in #9054.

I think we need to fix it, but we probably need one more state (`CLOSING` or such).

**Comment by gregw** [comment]
@sbordet We need to handle a call to `failed(Throwable)` in `PROCESSING` state the same as a call to succeeded.  Specifically we should not act on that until the process method has returned attempts to switch to PENDING state.

Experimental branch coming....

**Comment by gregw** [comment]
@sbordet I will merge forward to 12.  Does this need to be cherry-picked back to 9?

**Comment by sbordet** [comment]
@gregw I think cherry-picking to 9 would be good, it is a stabilization fix that may help 9 too.

**Comment by gregw** [comment]
done
