### ISSUE TITLE
Review why ServletRequestState#asyncError is never called in Jetty-12

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#9060]
**Enhancement Description**

> @lachlan-roberts can you also review org.eclipse.jetty.ee10.servlet.ServletRequestState#asyncError which is not called.  Need to check if that is correct and that onError is correctly called when necessary.

_Originally posted by @gregw in https://github.com/eclipse/jetty.project/issues/9048#issuecomment-1349705607_

**Comment by sbordet** [comment]
Closing as this issue has been handled in #10933 and #10949.
