### ISSUE TITLE
Jetty 9 Client is unable to send the message to the server resulting in 504 Destination Client Response TimeOut

### ISSUE THREAD

**Issue by sanchit1arora** [eclipse/jetty.project#9065]
**Jetty version(s)**
9.4.43.v20210629

**Java version/vendor** `(use: java -version)`
jdk 17.0.1

**OS type/version**
Linux

**Description**
In our Java application, we are using Jetty HttpClient. 
After some time, we are seeing that the application is not able to send messages towards one of the hosts.

Looking at the DEBUG logs of the Jetty, we see that the connection/session is not found for that host itself and we see a 504 Gateway Timeout Exception at the application level.

Jetty Logs

- "loggerName":"org.eclipse.jetty.client.AbstractConnectionPool","message":"Acquiring create=true on MultiplexConnectionPool@7cc199b8[c=0/2/2,a=0,i=0,q=1]"

- "loggerName":"org.eclipse.jetty.client.AbstractConnectionPool","message":"Try creating connection 2/2 with 0 pending"
 
- "loggerName":"org.eclipse.jetty.client.AbstractConnectionPool","message":"Try creating(true) connection, pending/demand/supply: 0/2/0, result=true"

Also, we looked at the wireshark captures to confirm that there is no connection attempt (TCP) towards the server (SYN/SYN-ACK).

Is it a known issue?  If yes, Has it been fixed in later releases?
Please let us know.

Thanks,
Sanchit Arora
 

**How to reproduce?**
Not sure

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

See:
* #7958

You should be using Jetty 10+ at this point.

Your connection pool is also incredibly tiny (only 2 connections)

**Comment by sbordet** [comment]
> we see a 504 Gateway Timeout Exception at the application level.

If you see that on the client, it means that it was delivered via network by the server, therefore you are connected to the server.

> `MultiplexConnectionPool@7cc199b8[c=0/2/2,a=0,i=0,q=1]`

This means you have a max of 2 connections (the last 2), and both are open (the middle 2).
So you are connected to the server.

> Also, we looked at the wireshark captures to confirm that there is no connection attempt (TCP) towards the server (SYN/SYN-ACK).

The logs you report say otherwise.

Sorry but there is no enough information to proceed with an investigation.
Chances are that it's not a Jetty issue but rather an issue in your code.

What `HttpClientTransport` are you using?

**Comment by joakime** [comment]
Jetty 9.4.43 is also subject to several Security Vulnerabilities.

See: https://www.eclipse.org/jetty/security_reports.php

**Comment by sanchit1arora** [comment]
> > we see a 504 Gateway Timeout Exception at the application level.
> 
> If you see that on the client, it means that it was delivered via network by the server, therefore you are connected to the server.
> 
> > `MultiplexConnectionPool@7cc199b8[c=0/2/2,a=0,i=0,q=1]`
> 
> This means you have a max of 2 connections (the last 2), and both are open (the middle 2). So you are connected to the server.
> 
> > Also, we looked at the wireshark captures to confirm that there is no connection attempt (TCP) towards the server (SYN/SYN-ACK).
> 
> The logs you report say otherwise.
> 
> Sorry but there is no enough information to proceed with an investigation. Chances are that it's not a Jetty issue but rather an issue in your code.
> 
> What `HttpClientTransport` are you using?

We are using HttpClientTransportOverHTTP2.

Yes, we don't see anything on the wireshark towards that host.
Do you think connection pool needs to be increased?

**Comment by sanchit1arora** [comment]
> > > we see a 504 Gateway Timeout Exception at the application level.
> > 
> > 
> > If you see that on the client, it means that it was delivered via network by the server, therefore you are connected to the server.
> > > `MultiplexConnectionPool@7cc199b8[c=0/2/2,a=0,i=0,q=1]`
> > 
> > 
> > This means you have a max of 2 connections (the last 2), and both are open (the middle 2). So you are connected to the server.
> > > Also, we looked at the wireshark captures to confirm that there is no connection attempt (TCP) towards the server (SYN/SYN-ACK).
> > 
> > 
> > The logs you report say otherwise.
> > Sorry but there is no enough information to proceed with an investigation. Chances are that it's not a Jetty issue but rather an issue in your code.
> > What `HttpClientTransport` are you using?
> 
> We are using HttpClientTransportOverHTTP2.
> 
> Yes, we don't see anything on the wireshark towards that host. Do you think connection pool needs to be increased?

The messages are going out towards other hosts. We are seeing this issue only towards this particular host.

**Comment by joakime** [comment]
> > We are using HttpClientTransportOverHTTP2.
> > Yes, we don't see anything on the wireshark towards that host. Do you think connection pool needs to be increased?
> 
> The messages are going out towards other hosts. We are seeing this issue only towards this particular host.

Jetty 9.x is at End of Community Support.

Does this happen with the latest Jetty 10.x release?
If so, we can help.

**Comment by sanchit1arora** [comment]
> > > > we see a 504 Gateway Timeout Exception at the application level.
> > > 
> > > 
> > > If you see that on the client, it means that it was delivered via network by the server, therefore you are connected to the server.
> > > > `MultiplexConnectionPool@7cc199b8[c=0/2/2,a=0,i=0,q=1]`
> > > 
> > > 
> > > This means you have a max of 2 connections (the last 2), and both are open (the middle 2). So you are connected to the server.
> > > > Also, we looked at the wireshark captures to confirm that there is no connection attempt (TCP) towards the server (SYN/SYN-ACK).
> > > 
> > > 
> > > The logs you report say otherwise.
> > > Sorry but there is no enough information to proceed with an investigation. Chances are that it's not a Jetty issue but rather an issue in your code.
> > > What `HttpClientTransport` are you using?
> > 
> > 
> > We are using HttpClientTransportOverHTTP2.
> > Yes, we don't see anything on the wireshark towards that host. Do you think connection pool needs to be increased?
> 
> The messages are going out towards other hosts. We are seeing this issue only towards this particular host.

@sbordet  Please suggest

**Comment by jmcc0nn3ll** [comment]
@sanchit1arora, the recommendation is to use the latest Jetty 9.4.x release and if that doesn't work, reproduce on a publically supported version of Jetty. The End of Community support @joakime indicates that our open-source development efforts focus on Jetty 10, Jetty 11, and the forthcoming Jetty 12.  Any further releases of Jetty 9 stem from changes made to support customers of Webtide.  I am sorry, but we have to draw the line somewhere, and supporting three major versions of Jetty publically is where we have drawn this line right now.
