### ISSUE TITLE
Provide InputStreamProviderRequestContent implementation

### ISSUE THREAD

**Issue by cstamas** [eclipse/jetty.project#9069]
**Jetty version(s)**
JettyClient 10.x

**Enhancement Description**
Currently org.eclipse.jetty.client.api.Request.Content offers following OOTB implementations:
* AbstractRequestContent
* AsyncRequestContent
* ByteBufferRequestContent
* BytesRequestContent
* FormRequestContent
* InputStreamRequestContent
* MultiPartRequestContent
* OutputStreamRequestContent
* PathRequestContent
* RequestContentAdapter
* StringRequestContent

In my use case API would provide InputStream, but I have no file available, still, I'd like to have reproducible content. Also, I _do know_ my contentLength as well, but InputStreamRequestContent does not allows me to set it.

Something like InputStreamProviderRequestContent (stream based but can be "reproduced", content size, content type is all same, just the content can be provided multiple times) would be nice to have OOTB.

Or introduce some "content" abstraction (provider of InputStream, contentType and contentLength) and wrap that?

I may miss something though....

**Comment by sbordet** [comment]
You should be able to subclass `InputStreamRequestContent` and do what you need: override the content-length to the value you know, override `isReproducible()`, and rewind your stream when a new subscription comes, or override `onRead()` to keep the data around.

**Comment by sbordet** [comment]
Closing, as solution has been provided.
