### ISSUE TITLE
The great Jetty-12 renaming omnibus

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9072]
**Jetty version(s)**
12

**Enhancement Description**

As jetty-12 alpha dev comes to a close, there are few classes and methods that could be renamed.   To make our lives simpler, it will be best to do these all at once with minimal other PRs outstanding.   So this issue is here to suggest/discuss renamings that we want  to do, and when we are all agreed we can do them all at once and quickly merge.  Please list suggested renamings in the comments.

**Comment by gregw** [comment]
`Handler.Collection` to `Handler.List` or something else?   The problem with `List` is that it will clash with  `java.util.List` in any `Handler`, be they a `List` or not.   Thus `Handler.Sequence` is probably better.

**Comment by gregw** [comment]
`Handler.process` to `Handler.handle`.  This would mean that `Handler` would not longer implement `Request.Processor`, but I do not think there are any examples of a Handler being used as just a `Request.Processor`.

**Comment by joakime** [comment]
other issues with this 

* #8975 
* #8991
* #4731

**Comment by gregw** [comment]
`SessionConfig` has a TODO for renaming. @janbartel do you know what they are?

**Comment by sbordet** [comment]
> `Handler.process` to `Handler.handle`. This would mean that `Handler` would not longer implement `Request.Processor`, but I do not think there are any examples of a Handler being used as just a `Request.Processor`.

Sure there are! `ErrorProcessor`s! 
I remember there was a problem considering them `Handler`s so I won't mind a common super-interface (maybe separated from `Request`).

**Comment by gregw** [comment]
@sbordet  So an `ErrorProcessor` is currently just a `Processor`.  It is not a `Handler`, so would not be affected by the renaming.
Now we might want to go back to an `ErrorHandler` if we want a life cycle and a server reference in the error thingy, but that would be a different PR as it is more than just a renaming.

I do not think we have any code that is effectively:
```java
    Request.Processor p = myHandler;
```

and even if we did, that could just become:
```java
    Request.Processor p = myHandler::handle;
```

**Comment by lachlan-roberts** [comment]
Adding the websocket isDemanding rename to the omnibus https://github.com/eclipse/jetty.project/issues/8991

**Comment by gregw** [comment]
The jetty-core/jetty-ee module is not really ee specific.  Currently it just contains the Deployable interface, which can apply to non ee contexts.

It could be renamed to `jetty-context-utils` or `jetty-common` and used to hold code that is common between eeN and other types of context.

**Comment by gregw** [comment]
So here is the list of renames that I would like to do:
| old name | new name | Comment
| -------------- | ---------------| --- | 
| ~~Handler.process~~ | ~~Handler.handle~~ | Handler would no longer implement `Request.Processor` |
| ~~Handler.Nested~~ | ~~Handler.Singleton~~ ||
| ~~FrameHandler.isDemanding~~ | ~~FrameHandler.isAutoDemand~~ | |
| ~~DecryptedEndPoint~~ | ~~SslEndPoint~~ ||
| ~~jetty-core/jetty-ee~~ | ~~jetty-core/jetty-context-common~~ | ~~This would also be the destination of any common code extracted from the servlet layers~~ |
| ~~RetainableByteBufferPool~~ | ~~ByteBufferPool~~ ||

I think some of these are trivial, but most will need a PR to be reviewed.  But we should do once we have a minimal number of open PRs

@sbordet @janbartel @lorban @lachlan-roberts @joakime @olamy  @jmcc0nn3ll

**Comment by sbordet** [comment]
Tracking renaming of DecryptedEndPoint to SslEndPoint via #9326.

**Comment by gregw** [comment]
remaining rename to beta1

**Comment by janbartel** [comment]
@gregw with #9883 completed, can we close this issue now?
