### ISSUE TITLE
Jetty-12 isDebugEnabled optimization 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9082]
**Jetty version(s)**
12

**Enhancement Description**

Currently in jetty-12, the `LOG.isDebugEnabled()` method is taking over 2.5% of CPU (e.g. search for it in [this flamegraph](https://jenkins.webtide.net/job/load_testing/job/jetty-perf/job/main-12.0.x/71/artifact/handlers/target/reports/AsyncHandlerPerfTest_testComplete/http/server/load-master/async-profiler-cpu.html)

This is significant overhead, which we should address in several ways:
 + Reduce debugging in hot methods
 + Investigate if methods/classes with lots of debug would benefit from assigning a local boolean or field to the `isDebugEnabled` result.
 + Investigate logger sink options that may reduce the cost of `isDebugEnabled`.

**Comment by lorban** [comment]
For future references, here is the [flamegraph](https://github.com/eclipse/jetty.project/files/10294183/async-profiler-cpu.zip).

**Comment by lorban** [comment]
Having to be careful about not adding too many debug logs on the hot path would be quite painful, so we should investigate is if a config change in logback (which is the impl in use here) or a newer logback version, or a different impl (log4j2?) would make the problem go away.

**Comment by joakime** [comment]
I generally agree with @lorban that a tweak in logback configuration is likely to have the biggest/simplest impact.

But, I went ahead and collected some numbers anyway.
Here's the results of running my experimental branch ...

* https://github.com/jetty-project/jetty-perf/tree/main-12.0.x-logback-custom-counting

This is on my machine, with openjdk-17, up to date slf4j-api and logback-classic, 1 load machine.

You can find these in the results of `server/<host>/server-debug-counts.log` if you run this branch yourself.

These logs show the count of each `LOG.debug()` call during the server run.
They show the Logger Name + line number of each event.

Example:

```
# Log written: 2022-12-23T11:23:37.198085067-06:00[America/Chicago]
# Captured 189 unique events
 3,122,299: org.eclipse.jetty.http.HttpParser:1920
 2,912,108: org.eclipse.jetty.http.HttpParser:1908
 2,080,921: org.eclipse.jetty.http.HttpParser:1922
 1,561,214: org.eclipse.jetty.server.internal.HttpConnection:599
 1,561,198: org.eclipse.jetty.io.SocketChannelEndPoint:101
...
```

AsyncHandlerPerfTest | Param | Results
---- | ---- | ----
testAlone |  http | [AsyncHandlerPerfTest_testAlone_http_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296632/AsyncHandlerPerfTest_testAlone_http_server_localhost_server-debug-counts.log)
testAlone | h2c | [AsyncHandlerPerfTest_testAlone_h2c_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296633/AsyncHandlerPerfTest_testAlone_h2c_server_localhost_server-debug-counts.log)
testComplete | http | [AsyncHandlerPerfTest_testComplete_http_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296634/AsyncHandlerPerfTest_testComplete_http_server_localhost_server-debug-counts.log)
testComplete | h2c | [AsyncHandlerPerfTest_testComplete_h2c_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296635/AsyncHandlerPerfTest_testComplete_h2c_server_localhost_server-debug-counts.log)
testNoGzip | http | [AsyncHandlerPerfTest_testNoGzip_http_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296636/AsyncHandlerPerfTest_testNoGzip_http_server_localhost_server-debug-counts.log)
testNoGzip | h2c | [AsyncHandlerPerfTest_testNoGzip_h2c_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296638/AsyncHandlerPerfTest_testNoGzip_h2c_server_localhost_server-debug-counts.log)
testNoDelay | http | [AsyncHandlerPerfTest_testNoDelay_http_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296725/AsyncHandlerPerfTest_testNoDelay_http_server_localhost_server-debug-counts.log)
testNoDelay | h2c | (failed run, no logs)
testNoDelayNorGzip | http | [AsyncHandlerPerfTest_testNoDelayNorGzip_http_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296726/AsyncHandlerPerfTest_testNoDelayNorGzip_http_server_localhost_server-debug-counts.log)
testNoDelayNorGzip | h2c | [AsyncHandlerPerfTest_testNoDelayNorGzip_h2c_server_localhost_server-debug-counts.log](https://github.com/eclipse/jetty.project/files/10296728/AsyncHandlerPerfTest_testNoDelayNorGzip_h2c_server_localhost_server-debug-counts.log)

>  + Reduce debugging in hot methods

The above results show some opportunity for this in the following classes (in order of most common, see above reports to see line numbers) ...

`http` mode

* org.eclipse.jetty.http.HttpParser
* org.eclipse.jetty.server.internal.HttpConnection
* org.eclipse.jetty.io.SocketChannelEndPoint
* org.eclipse.jetty.io.WriteFlusher

`h2c` mode

* org.eclipse.jetty.http2.hpack.HpackDecoder
* org.eclipse.jetty.http2.internal.HTTP2Stream
* org.eclipse.jetty.http2.hpack.HpackEncoder

>  + Investigate if methods/classes with lots of debug would benefit from assigning a local boolean or field to the `isDebugEnabled` result.

I'm generally against this solution, as it prevents runtime adjustment of debug logging, which has proven to be incredibly useful when troubleshooting.
(eg: wait for problem to occur, turn on DEBUG logging for a minute or two, then go back to previous level)

We have this in some places in code currently (most notably in org.eclipse.jetty.http.HttpParser), but that approach should be kept to a minimum.

>  + Investigate logger sink options that may reduce the cost of `isDebugEnabled`.

This is the suggestion from @lorban

**Comment by gregw** [comment]
> > * Investigate if methods/classes with lots of debug would benefit from assigning a local boolean or field to the `isDebugEnabled` result.
> 
> I'm generally against this solution, as it prevents runtime adjustment of debug logging, which has proven to be incredibly useful when troubleshooting. (eg: wait for problem to occur, turn on DEBUG logging for a minute or two, then go back to previous level)

I agree that any specific logging optimizations in the code should be kept to a minimum and only done on the hot path.

We do have some examples of code like:
``` java
    if (LOG.isDebugEnabled())
        LOG.debug("before {}, something);
    doSomething();
    if (LOG.isDebugEnabled())
        LOG.debug("after {}, something);
```

It would be interesting to know if there is benefit in changing that to:

``` java
    boolean debug = LOG.isDebugEnabled();
    if (debug)
        LOG.debug("before {}, something);
    doSomething();
    if (debug)
        LOG.debug("after {}, something);
```

That remains mostly dynamic, but can reduce the `isDebugEnabled` calls on hot paths a fair bit.


Also, if we are to use the approach of HttpParser in a few spots on the hot path, how about we encapsulate it and make it more explicit. Something like:
```java
    public static final Logger LOG = LoggerFactory.getLogger(HttpParser.class);
    public static final Logger HOT_LOG = new HotLogger(LOG);
```

The HOT_LOG could statically check some system property to see if we are optimizing logs and if so return a logger that has isDebugEnabled() hard wired to the value obtained when created?
But does that just turn `isDebugEnabled()` into a more expensive virtual call?  Maybe it is already?

But then maybe switching away from logback will be sufficient???

Anyway, I think there is 2% to be gained, so worth some experiments... or at least maybe just a little bit of pruning of debug logging on the hot path.

**Comment by joakime** [comment]
> Anyway, I think there is 2% to be gained, so worth some experiments... or at least maybe just a little bit of pruning of debug logging on the hot path.

I think we should do a run with the slf4j `org.slf4j.helpers.NOPLogger` and verify that the 2% we see is something that we can fix on our side, or is it purely an artifact of the logback implementation causing the 2%?

**Comment by joakime** [comment]
For the record, on my machine, running `AsyncHandlerPerfTest` from `jetty-perf`, with FULL DEBUG turned on, only results in 0.02% CPU on the flamegraph (with logback).

**Comment by gregw** [comment]
> For the record, on my machine, running `AsyncHandlerPerfTest` from `jetty-perf`, with FULL DEBUG turned on, only results in 0.02% CPU on the flamegraph (with logback).

@joakime this is is not concerned about the impact when debug is enabled.   When debug is enabled, we know that a lot of work will be done formatting and handling logs, so all other work will diminish as a percentage.

This issue is concerned about the hot path when we are running without debug enabled.  Currently over 2.5% CPU is being used just to check if it is enabled or not.  That feels excessive.   So this issue is about what can we do to reduce that overhead when debug is not enabled.  I suspect the answer will be some combinations of:
 + pruning/rationalizing isDebugEnabled calls on the hot path.
 + perhaps caching the debug status as a field (like HttpParser) or as variable (like my suggestion above).
 + alternate log4j implementations

**Comment by joakime** [comment]
More results
  
Logger Impl | Version | Configured Level | `isDebugEnabled` CPU usage
--- | --- | --- | ---
Logback | 1.4.5 | INFO | 1.79%
slf4j NOPLogger | 2.0.6 | INFO | 0.00% ([too low to measure](https://github.com/qos-ch/slf4j/blob/v_2.0.6/slf4j-api/src/main/java/org/slf4j/helpers/NOPLogger.java#L103-L105))
log4j | 2.19.0 | INFO | 2.06%
jetty-slf4j-impl | 12.0.0-SNAPSHOT | INFO | 0.16%

Yeah, this 2% we are chasing is not the overhead in our code, it's entirely within the logger implementation.

**Comment by sbordet** [comment]
Thanks @joakime for your last comment.
I think we should drop this chase, as it seems entirely a logging library implementation problem -- our logging library does not have the problem.

**Comment by gregw** [comment]
@sbordet the problem exists in several very common libraries. I see no harm in reviewing our usage in the hot paths and doing a bit of rationalization. I.e. don't remove logging, but perhaps a bit less frequent logging might be appropriate in done places. I don't think we should do anything fancier than that

**Comment by sbordet** [comment]
@gregw perhaps, but this is super-super-super low priority.
We can do it past the release of 12.

**Comment by gregw** [comment]
Sure it can wait, but 2% in a common scenario is not that insignificant. I expect with a few hours with we could reduce that by half and that's a good investment in time.
