### ISSUE TITLE
Jetty-12 HttpField cache review

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9083]
**Jetty version(s)**
12

**Enhancement Description**

In [this recent flamegraph](https://jenkins.webtide.net/job/load_testing/job/jetty-perf/job/main-12.0.x/71/artifact/handlers/target/reports/AsyncHandlerPerfTest_testComplete/http/server/load-master/async-profiler-cpu.html), the HttpField cache lookup is consuming 2.98% of CPU.
This is probably reasonable, but the [fixed cache](https://github.com/eclipse/jetty.project/blame/jetty-10.0.x/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java#L105-L130) contents could probably be optimized for the latest clients.  
Ideally we would find a way to continually gather statistics to keep that table up to date.

**Comment by lorban** [comment]
For future references, here is the [flamegraph](https://github.com/eclipse/jetty.project/files/10294249/async-profiler-cpu.zip).

**Comment by lorban** [comment]
I've tried disabling the field cache via `HttpConfiguration.setHeaderCacheSize(-1)` and the measurement shows that disabling it only degrades perf by 5%; `HttpParser.parseFields()` only grows from 10.28% to 11.33% in the [profiler report](https://jenkins.webtide.net/job/load_testing/job/jetty-perf/job/main-12.0.x/72/artifact/handlers/target/reports/AsyncHandlerPerfTest_testComplete/http/server/load-master/async-profiler-cpu.html).



This makes me wonder if we couldn't optimize the non-cache codepath to gain those few % and get rid of the cache.

**Comment by gregw** [comment]
@lorban I think that is just disabling the dynamic cache, where we put headers that miss the static cache.    But good to check that too and it is interesting that the dynamic cache is giving us something... I would not have been surprised if it proved to be an optimization passed its time.

I don't want to spend too much time on this just at the moment (I'm labeling low priority), but I think ultimately we should compare:
 + Update the static cache entries to match common browsers
 + make sure the loaders use headers that are similar to common clients (perhaps we need browser and non browser variants?)
 + profile with and without dynamic cache
 + profile with a branch that has all cache code (static and dynamic) stripped out of the HttpParser.
 + consider if checking the static cache before the dynamic cache would be better?
 + consider specific server wide dynamic caches for headers like User-Agent
 + consider better Cookie caching where the actual cookies themselves are cached with the HttpField?

Without the Trie.getBest approach, we need to scan ahead looking for delimiters, create strings from the bytes, lookup those strings to get any associated HttpHeader enum, create an HttpFields instance and possible parse a long to see if it is 0 or not.  So that is a bit of work that the caches are avoiding, thus making them hit more may be more productive than simplifying the code without caches.... but we should verify.

Anyway, let's not waste too much time on this until we have a beta release (or maybe even after GA).
