### ISSUE TITLE
HttpClient authentication in async mode

### ISSUE THREAD

**Issue by cstamas** [eclipse/jetty.project#9084]
**Jetty version**
Jetty Client 10.0.13

**Java version**
Java 17.0.5 Temurin, Linux Fedora 37

**Question**
Created and configured with authentication a HttpClient instance. Authentication works as expected, when using blocking API (plain PUT /some/file).

But, when using async API (to utilize OutputStreamRequestContent) the client Response I get is 401.

Does it mean that in async mode it is me who needs to handle authentication? As it is not clear from documentations, but I may missed something...

Or the reason is that OutputStreamRequestContent is not reproducible? Is there any other way to get OutputStream of request body (for file upload)?

**Comment by sbordet** [comment]
I think it has to do with reproducibility of the request content.

In the blocking call you are probably using a reproducible content, while `OutputStreamRequestContent` is not reproducible.
See `Request.Content.isReproducible()`.

You may want to preempt the authentication, see https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-client-http-authentication, to avoid the need to reproduce the request content.

**Comment by cstamas** [comment]
yup, you nailed it. For now will do as I did (not using the OutputStreamRequestContent) but "cheating a bit".
