### ISSUE TITLE
How to write (or should I write) Jetty module?

### ISSUE THREAD

**Issue by cstamas** [eclipse/jetty.project#9086]
**Jetty version**
10+

**Java version**
Java 17+

**Question**
Since eons (2007 to be precise) I wrote several web apps (starting with Sonatype Nexus) that embeds Jetty in this or that way. It usually ended up messy, as in all projects so far tended to mess up Jetty.xml that always "drifted away" from Jetty Distribution (as it existed until Jetty 9). So update was pain, especially when OOTB XMLs had changes that needed to be ported (manually) to our messy XML.

Today, am thinking to actually provide "jetty module" for the app, so all the stuff in Jetty operations applies, and deployment would be really "just follow Jetty doco and add app module to $JETTY_BASE" (as you would do with any other module).

So the questions: 
* is this good idea at all? (I would like to avoid WAR as I want to tie deeper into Jetty, use Jetty APIs. With WAR I'd again need special config to "open up" Jetty belly to webapp, etc, and custom config is something I'd like to avoid)
* is there some archetype or any special consideration for Jetty module packaging? Any existing example, or should I just go look into Jetty build? All I found is short snippet in doco https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html#og-modules-custom-create
* how would an app packaged as jetty module be distributed? Just deployed to central and user needs to download and unpack it? I believe packing up whole JETTY_BASE would tie the package to very Jetty version?... is there something that is able to pull module and populate JETTY_BASE? (i mean, using Maven should do it, but am not aware of any existing solution)

**Comment by joakime** [comment]
It might make more sense to just distribute a jetty-base directory, already configured, with minimal XML.

That way it's not tied to a specific version of Jetty.
Others can build on top of that using their own jetty-base directory and the `--include-jetty-dir` directive (pointing at your jetty-base).

You don't have to package your webapp as a war, it can use Jetty Handler's and whatnot, you just won't get any Classloader isolation or automatic configuration that the WAR mode of deployment gives you.

**Comment by joakime** [comment]
Starting with Jetty 12 you can even have your project be a jetty-base directory with it's own declared Environment (which is isolated from all other environments, like: ee8, ee9, ee10)

**Comment by joakime** [comment]
> With WAR I'd again need special config to "open up" Jetty belly to webapp, etc, and custom config is something I'd like to avoid

This can be accomplished with a WAR.

The "opening up" is done by a `org.eclipse.jetty.webapp.Configuration` that configures your WAR to expose server things.
See: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiConfiguration.java

Then it's just a matter of having a module that looks something like this ...

```
# DO NOT EDIT - See: https://www.eclipse.org/jetty/documentation/current/startup-modules.html

[description]
Makes a custom (optional) webapp Configuration available to webapps to use.

[tag]
x-custom-config

[provides]
x-custom-config

[depend]
deploy

[lib]
lib/custom-config-${jetty.version}.jar
```

Your `${jetty.base}/webapps/myapp.xml` would look (something) like this ...

_(I haven't tested this)_

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/myapp</Set>
  <!-- other configuration -->
  <Call name="addConfiguration">
    <Arg>
      <New class="org.example.app.MyCustomConfiguration"/>
    </Arg>
  </Call>
</Configure>
```

**Comment by olamy** [comment]
I like the idea `distribute my app/webapp as a Jetty module`. 
Some thoughts, we probably need some features for this 
- support something to install modules with sort of maven coordinate `--add-module=org.foo:my-module:1.0.0[:jar/zip]`
- adding some maven mojo such `jetty:create-module` (creating a Jetty module from the current war project) (maybe some new packaging such `jetty-module` which will run all the the needed mojo)
- archetype could be nice as well but jetty module could have so many different natures (webapp, session manager, etc...) at least we could have one to create a module file for a war project.

**Comment by joakime** [comment]
We already have a primitive URI scheme behavior in jetty-start, lets continue to use it. (eg: `maven:` vs `https:` vs `file:` etc)
