### ISSUE TITLE
Path and Domain not properly matched in addCookie()

### ISSUE THREAD

**Issue by michael-apptornado** [eclipse/jetty.project#909]
The following code sequence adds a bunch of cookies that should all be sent to the browser. However, some of them are not being added to the response (explanation below):
```
Cookie cookieA1 = new Cookie("test_cookie_a", "value_a1");
cookieA1.setPath("/");
response.addCookie(cookieA1);

Cookie cookieA2 = new Cookie("test_cookie_a", "value_a2");
cookieA2.setPath("/path/");
response.addCookie(cookieA2);

Cookie cookieB1 = new Cookie("test_cookie_b", "value_b1");
cookieB1.setPath("/path/");
response.addCookie(cookieB1);

Cookie cookieB2 = new Cookie("test_cookie_b", "value_b2");
cookieB2.setPath("/");
response.addCookie(cookieB2);

Cookie cookieC1 = new Cookie("test_cookie_c", "value/containing/path/of/c2");
cookieC1.setPath("/");
response.addCookie(cookieC1);

Cookie cookieC2 = new Cookie("test_cookie_c", "another/value/c2");
cookieC2.setPath("/path/");
response.addCookie(cookieC2);
```

The browser (copy/pasted from chrome inspect) receives:
```
Set-Cookie:test_cookie_a=value_a1;Path=/
Set-Cookie:test_cookie_a=value_a2;Path=/path/
Set-Cookie:test_cookie_b=value_b2;Path=/
Set-Cookie:test_cookie_c=another/value/c2;Path=/path/
```
I.e. cookie B1 and C1 have not been sent to the browser (but should have, to the best of my knowledge). I believe the problem is in the method `addSetCookie()` in [Response.java Line 336ff](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L336) that just checks whether the entire response header value contains the specified path and domain (rather than - somehow - checking for path and domain equality). Thus, cookie B1 gets removed because cookie B2's path is a subset of cookie B1's path. Even worse, cookie C1 gets removed because it's _value_ contains a substring of C2's path.

**Comment by janbartel** [comment]
@michael-apptornado investigating where these lines came from reveals they were added way back in the Dark Ages in jetty-6 (!) to a response to a user problem whereby their app was repeatedly adding the same cookie over and over again.  Discussing this with @gregw , we no longer think that its reasonable for jetty to try and second-guess what the app is doing with cookies, so I've removed that section of code in jetty-9.3 and above.
