### ISSUE TITLE
Handshake is failing on TLS 1.0 and TLS 1.1 with Jetty 9.4.x

### ISSUE THREAD

**Issue by vanand123** [eclipse/jetty.project#9094]
**Jetty version**
jetty-distribution-9.4.48.v20220622

**Java version**
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b09)
OpenJDK Server VM (build 25.332-b09, mixed mode)

**Question**
When trying to check SSL handshake using openssl command on port 7443, handshake is failing for TLS 1.0 & TLS 1.1
Is SSL handshake is supported for TLS 1.0 and TLS 1.1?

/usr/local/platform/bin/openssl s_client -tls1 -connect <hostname/ip_address>:7443
```
CONNECTED(00000003)
4144256768:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1544:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 102 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1672152004
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
```
/usr/local/platform/bin/openssl s_client -tls1_1 -connect <hostname/ip_address>:7443
```
CONNECTED(00000003)
4143441664:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1544:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 102 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.1
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1672155552
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
```

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

You should be using Jetty 10+ at this point.

Note that TLS 1.0 and TLS 1.1 is disabled at the Java level for a few years now.

See : https://www.java.com/en/jre-jdk-cryptoroadmap.html

Also note that it's not enough to just enable the protocol TLS/1.0 or TLS/1.1 as most of the Cipher suites those protocols need are also disabled as being insecure.

Turn on your DEBUG level logging and check the output of the SslContextFactory.
Or enable the [Jetty Server Dump](https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-server-dump) and check the SslContextFactory.
You'll quickly see what's enabled/disabled (at the protocol and cipher suite level) and what is disabling it (your JVM and/or Jetty).
