### ISSUE TITLE
How to find package jetty-http-tools

### ISSUE THREAD

**Issue by liresky** [eclipse/jetty.project#9095]
**Jetty version**
10.0.13
**Java version**
JDK11
**Question**
org.eclipse.jetty.tests:jetty-http-tools this package is not available in maven repo。
Can I only compile this package myself?

**Comment by olamy** [comment]
You can find this in the git repo here https://github.com/eclipse/jetty.project/tree/jetty-10.0.x/tests/jetty-http-tools
we do not deploy those artifacts to Maven central as they are only use for testing.
