### ISSUE TITLE
Support java:global/<module-name>!ROOT  lookup and injection of context urls

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#91]
migrated from Bugzilla [#329178](https://bugs.eclipse.org/bugs/show_bug.cgi?id=329178)
status ASSIGNED severity _enhancement_ in component _server_ for _7.1.x_
Reported in version _8.0.0_ on platform _All_
Assigned to: Jan Bartel

On 2010-11-01 03:25:28 -0400, Jan Bartel wrote nothing.
On 2010-11-01 03:28:14 -0400, Jan Bartel wrote:

> Depends on bug # 329175 in the sense that in order to do the injection, you need to be able to specify the lookup= params to @Resource.

**Comment by janbartel** [comment]
There is no demand for jetty to implement this, so I'm closing this issue.
