### ISSUE TITLE
Request.getRequestURI() gets decoded after startAsync(req, resp) is invoked

### ISSUE THREAD

**Issue by tadayosi** [eclipse/jetty.project#911]
If you use Servlet 3.0 Asynchronous API invoking `HttpServletRequest.startAsync(req, resp)` with a request URL that includes encoded path, e.g.:

    http://localhost:8080/hello/jetty%20project

both `HttpServletRequest.getRequestURI()` and `HttpServletRequest.getRequestURL()` unexpectedly get decoded, e.g.:

    http://localhost:8080/hello/jetty project

 after the async context is dispatched and is resumed in the servlet.

Note this issue doesn't happen with the no-arg `HttpServletRequest.startAsync()` method; the request keeps the encoded path (i.e. `http://localhost:8080/hello/jetty%20project`) as expected even after the async context is dispatched.

This issue causes problems with handling the request URI / URL of the asynchronous request such as `java.net.URISyntaxException` when trying to parse it in an application.

**Comment by gregw** [comment]
I have put a simple fix in for startAsync(req,res) for 9.3.x,

however the bigger problem that getContextPath is meant to return the encoded path can only be fixed in 9.4.x as that is a significant change
