### ISSUE TITLE
Wrong value of javax.servlet.forward.context_path attribute

### ISSUE THREAD

**Issue by grgrzybek** [eclipse/jetty.project#9119]
**Jetty version(s)**
10.0.13

**Java version/vendor** `(use: java -version)`
11.0.7

**OS type/version**
Linux/Fedora 37

**Description**
I work on Pax Web project and it unifies 3 embedded web servers (Jetty, Tomcat and Undertow) in OSGi runtime.
I try hard to make the tests consistent and ensure similar behavior between the runtimes.

According to Chapter _9.4.2 Forwarded Request Parameters_ of the Servlets 4 specification:
> The following request attributes must be set:
javax.servlet.forward.mapping
javax.servlet.forward.request_uri
javax.servlet.forward.context_path
javax.servlet.forward.servlet_path
javax.servlet.forward.path_info
javax.servlet.forward.query_string
The values of these attributes must be equal to the return values of the
HttpServletRequest methods getRequestURI, getContextPath, getServletPath,
getPathInfo, getQueryString respectively, invoked on the request object passed to
the first servlet object in the call chain that received the request from the client.

When using Jetty 9.4.50, I see correct (in [org.eclipse.jetty.server.Dispatcher#forward()](https://github.com/eclipse/jetty.project/blob/jetty-9.4.50.v20221201/jetty-server/src/main/java/org/eclipse/jetty/server/Dispatcher.java#L153)):
```java
final String old_context_path = baseRequest.getContextPath();
...
ForwardAttributes attr = new ForwardAttributes(old_attr);
...
attr._contextPath = old_context_path;
```

However in Jetty 10, it's:
```java
if (old_attr.getAttribute(FORWARD_REQUEST_URI) == null)
    baseRequest.setAttributes(new ForwardAttributes(old_attr,
        old_uri.getPath(),
        old_context == null ? null : old_context.getContextHandler().getContextPathEncoded(),
        baseRequest.getPathInContext(),
        source_mapping,
        old_uri.getQuery()));
```

And the forwarded context path is `"/"` instead of `""` (empty string).

**How to reproduce?**

I have a `"/gateway/*"` mapped servlet with:
```java
protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
	String what = req.getParameter("what");
	String where = req.getParameter("where");
	switch (what) {
		case "redirect":
			resp.sendRedirect(where);
			return;
		case "forward":
			// we can't send anything when forwarding
			req.getRequestDispatcher(where).forward(req, resp);
			return;
		case "include":
			resp.getWriter().print(">>>");
			req.getRequestDispatcher(where).include(req, resp);
			resp.getWriter().print("<<<");
			return;
		default:
	}
}
```

And I call it with this URI:
```
"/gateway/x?what=forward&where=/"
```

The test is https://github.com/ops4j/org.ops4j.pax.web/blob/web-9.0.4/pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/UnifiedJettyTest.java#L505-L516

**Comment by grgrzybek** [comment]
The include attributes are fine - there, `org.eclipse.jetty.server.handler.ContextHandler#getRequestContextPath()` is used, while in forward, the method is `org.eclipse.jetty.server.handler.ContextHandler#getContextPathEncoded()`.

**Comment by joakime** [comment]
I have a test case that confirms report.
Working on a fix and PR.

**Comment by joakime** [comment]
Opened PR #9123 to address this
