### ISSUE TITLE
Unnecessary `validate` phase executed by `:start` maven plugin goal

### ISSUE THREAD

**Issue by pzygielo** [eclipse/jetty.project#9130]
Here's my setup - https://github.com/pzrep/jetty-start-goal/:
https://github.com/eclipse/jetty.project/blob/b8db190114d047a4ac60d01c6fdda4fdbba9609e/pom.xml#L82-L88

This however results in [`validate` being executed](https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:52):
```
[INFO] >>> jetty-maven-plugin:11.0.3:start (start-jetty) > validate @ jetty-start-goal >>>
[INFO] 
[INFO] --- maven-help-plugin:3.3.0:active-profiles (default) @ jetty-start-goal ---
[INFO] 
Active Profiles for Project 'pzrep:jetty-start-goal:war:1.6.0-SNAPSHOT':

The following profiles are active:

 - with-jetty (source: pzrep:jetty-start-goal:1.6.0-SNAPSHOT)



[INFO] 
[INFO] <<< jetty-maven-plugin:11.0.3:start (start-jetty) < validate @ jetty-start-goal <<<
[INFO] 
[INFO] 
[INFO] --- jetty-maven-plugin:11.0.3:start (start-jetty) @ jetty-start-goal ---
```

But it was executed in [line 13](https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:14) already.

_Originally posted by @pzygielo in https://github.com/eclipse/jetty.project/issues/9128#issuecomment-1374180531_

**Comment by pzygielo** [comment]
- https://web.archive.org/web/20150511173050/https://jira.codehaus.org/browse/JETTY-1405
- https://github.com/codehaus/jetty-project/commit/2b48882b28341d77bf1c33e9c12b4a1e4d884817 - this should have been `@execute phase="none"` then, IMO, to override inherited execution. Still would need to override with NONE in 9.x, but not in current 10.x, where super has no execution specified.

JETTY-1405 introduced `:start`, which **reduced** forked LC to validate only, but I'd like to have no forked LC at all.

**Comment by joakime** [comment]
@olamy and @jmcc0nn3ll both of you should take a look at this as well (so we can get all 3 maven committers looking at this)

**Comment by pzygielo** [comment]
I propose to
- https://github.com/eclipse/jetty.project/pull/9128

**Comment by janbartel** [comment]
@pzygielo I think we needed to have at least `validate` in order to ensure that some of the project artifacts etc were resolved ... but I might be misremembering. Taking another look.

**Comment by pzygielo** [comment]
> I think we needed to have at least validate

From the goal's description:

> This goal is similar to the jetty:run goal, EXCEPT that it is designed to be bound to an execution inside your pom, rather than being run from the command line. 
>
> When using it, be careful to ensure that you bind it to a phase in which all necessary generated files and classes for the webapp
> will have been created. If you run it from the command line, then also ensure that all necessary generated files and classes for
> the webapp already exist.


So - let me repeat: validate already happens and there is no need for the plugin to execute it *again*. The fact that in some cases there is no visible output that it is executed for the second (and even the first) time does not mean that there is nothing happening.

**Comment by joakime** [comment]
The phase specified in the plugin is a default that is present in the plugin metadata, it can be changed in the plugin configuration of your project.
It doesn't force `validate` phase by ignoring your configuration.
This behavior is handled by, and controlled by, Maven itself, not the plugin, or it's metadata.

The double plugin execution you are seeing is likely from something else, causing unintended side effects.

What we need to diagnose ...

 * an example project
 * details about which jvm version you are using when it happens
 * details about which maven version you are using when it happens
 * details about how you are using maven (examples of some concepts, but not limited to ... command line, from IDE, via maven daemon, using wrappers, from CI, etc)
 * details about your maven command line (what goals and in what order are you using it)

You've referenced https://github.com/pzrep/jetty-start-goal/

But that doesn't show a double execution when run by command line from system installed maven, or the packaged mvnw in the project.
Turning on maven debug `--debug` shows that jetty only starts once as well.

**Comment by pzygielo** [comment]
> The phase specified in the plugin is a default that is present in the plugin metadata, 

That's the point. It's not the default phase that goal is bound to and can be changed with configuration. This would be in the form of `@Mojo(defaultPhase=...)`. Currently it is `@Mojo(name = "start", requiresDependencyResolution = ResolutionScope.TEST)` - and I can see there is no `defaultPhase` there. This _could be_ changed by configuration - but there is nothing _to be_ changed.

This is about `@Execute(phase = LifecyclePhase.VALIDATE)` as this is what I proposed to remove in original PR.

`@Execute` != `@Mojo.defaultPhase`.

I can only suggest https://maven.apache.org/plugin-tools/maven-plugin-plugin/examples/using-annotations.html#annotations

> it can be changed in the plugin configuration of your project.

This cannot be changed by plugin configuration.

> It doesn't force `validate` phase by ignoring your configuration

No. It forces `validate` for other reasons - from the using annotations linked above:
> `@Execute`: Used if your Mojo needs to fork a lifecycle,

And `:start` does that.

> This behavior is handled by, and controlled by, Maven itself, not the plugin, or it's metadata.

It's explicitly requested by the plugin's metadata.

> The double plugin execution you are seeing is likely from something else, causing unintended side effects.

No. It's the forked `validate` life cycle phase forked as requested by `:start` of jetty plugin.

> What we need to diagnose ...
> 
>     * an example project

I provided the simplest one already - https://github.com/pzrep/jetty-start-goal.

>     * details about which jvm version you are using when it happens

Not important. But https://github.com/pzrep/jetty-start-goal/blob/45b102341944c508e3307d8be8653824e904918d/.github/workflows/maven.yml#L14 specifies it as temurin 11.

>     * details about which maven version you are using when it happens

Not important. But https://github.com/pzrep/jetty-start-goal/blob/45b102341944c508e3307d8be8653824e904918d/.mvn/wrapper/maven-wrapper.properties#L18 specifies it as 3.8.7

>     * details about how you are using maven (examples of some concepts, but not limited to ... command line, from IDE, via maven daemon, using wrappers, from CI, etc)
>     * details about your maven command line (what goals and in what order are you using it)

https://github.com/pzrep/jetty-start-goal/blob/45b102341944c508e3307d8be8653824e904918d/.github/workflows/maven.yml#L16:
```
./mvnw --no-transfer-progress verify
```

> You've referenced https://github.com/pzrep/jetty-start-goal/
> 
> But that doesn't show a double execution when run by command line from system installed maven, or the packaged mvnw in the project.

Yes, it does. I linked to https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:52 already and said that validate was achieved for the first time in line 13.

The fact that there is no output for `validate` phase does not mean it doesn't happen. That's why I do explicitly bind `active-profiles` to `validate` phase in https://github.com/pzrep/jetty-start-goal/blob/45b102341944c508e3307d8be8653824e904918d/pom.xml#L23 to show OTHER plugin execution.


There is no need to call maven with `--debug` to observe what I fail to describe here.

**Comment by janbartel** [comment]
@olamy it doesn't seem to do any harm if we remove the `@Execute(phase = LifecyclePhase.VALIDATE)`, all of our integration tests complete in the green. Any objections to simply removing that line?

**Comment by janbartel** [comment]
@pzygielo  can you submit a PR that removes the validate line? Or do you want me to do it?

**Comment by olamy** [comment]
> @olamy it doesn't seem to do any harm if we remove the `@Execute(phase = LifecyclePhase.VALIDATE)`, all of our integration tests complete in the green. Any objections to simply removing that line?

LGTM

**Comment by pzygielo** [comment]
> @pzygielo can you submit a PR that removes the validate line? Or do you want me to do it?

- Can #9128 be reopened, please?
