### ISSUE TITLE
Intermittently having response body as null on high traffic

### ISSUE THREAD

**Issue by owaiscs001** [eclipse/jetty.project#9137]
**Jetty version**
11.0.11

**Java version**
17.0.5

**Spring boot version(s)**
2.7.4

**OS type/version**
Linux

**Question**
While sending the high traffic (same message and payload) we observed some http/2 messages intermittently having response body as null but response header Content-Length value was 86541.
Further we collected tcpdump in the same time interval and observed some unknown type http/2 PDU which contained some jumbled streams of payload.
Also the size of unknown type http/2 PDU payload was very huge between 7MB to 8MB and other normal http/2 PDU payloads were around 118KB.

Can you provide some direction on what could be the reason or how we could debug this issue.

**Comment by sbordet** [comment]
This seems more like a server problem.
What server are you using?
Can you share the TCP dump?

**Comment by joakime** [comment]
Unable to replicate
