### ISSUE TITLE
ResourceFactoryTest, UrlResourceFactoryTest require network access, call webtide.com; fail when blocked

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/jetty.project#9139]
**Jetty version(s)**
12.0.x

**Java version/vendor** `(use: java -version)`
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Temurin-19.0.1+10 (build 19.0.1+10)
OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode)

**OS type/version**
macOS 13.1

**Description**
ResourceFactoryTest and UrlResourceFactoryTest currently exercise UrlResourceFactory by connecting to https://webtide.com.

Outbound firewalls warn about this upon calling `mvn install` (for example), raising unjustified suspicion about why tests would need to contact an external site. Blocking this call, or running the tests in a constrained offline environment, will cause the test to fail. 

I propose to change this test to use a local URL instead (e.g., URL from Class#getResource or a temporarily created jar file), alternatively serving content from a local http(s) server, or, as a last resort, using `https://www.example.com` instead of `https://webtide.com`, which could be dealt with separately.

**How to reproduce?**
```
mvn clean install -Dtest=UrlResourceFactoryTest -pl :jetty-util -am
mvn clean install -Dtest=ResourceFactoryTest -pl :jetty-util -am
```

**Comment by joakime** [comment]
These should be flagged with `@Tag("external")` if they are not already.
