### ISSUE TITLE
Failure when running `add-module` for openid, websocket, and stats modules

### ISSUE THREAD

**Issue by gregpoulos** [eclipse/jetty.project#9145]
**Jetty version(s)**
12

**Java version/vendor** `(use: java -version)`
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10-21)
OpenJDK 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

**OS type/version**
macOS Monterey, 12.6.2

**Description**
I get error messages when trying to add the `openid` and `stats` modules:
```
$ java -jar $JETTY_HOME/start.jar --add-modules=openid
ERROR : No module found to provide security for openid{enabled}

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

```
$ java -jar $JETTY_HOME/start.jar --add-modules=stats
ERROR : No module found to provide servlet for stats{enabled}

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

This is confusing, because both `openid` and `stats` appear in the list of modules that appears when I run `java -jar $JETTY_HOME/start.jar --list-modules=*`:

```
$ java -jar $JETTY_HOME/start.jar --list-modules=* | grep openid
                           ee10-openid - Adds OpenId Connect authentication to the server.
                            ee9-openid - Adds OpenId Connect authentication to the server.
                                openid - Adds OpenId Connect authentication to the server.
$ java -jar $JETTY_HOME/start.jar --list-modules=* | grep stats
                                 stats - Enables detailed statistics collection for the server.
```

**How to reproduce?**
Run `java -jar $JETTY_HOME/start.jar --add-modules=openid,stats`

**Comment by lorban** [comment]
The `stats` module bug is a bit complex and will need some time to get fixed, but the `openid` one looks fairly trivial.

The `openid` module should have been called `ee8-openid`. You could fix it temporarily by renaming `$JETTY_HOME/modules/openid.mod` to `$JETTY_HOME/modules/ee8-openid.mod` and editing it, you'll see that it contains a `[depends]` section like the following that needs to be changed:

```
[depend]
security
client
```

The `security` module doesn't exist anymore as it's specific to which ee version you're running so it should be changed to:

```
[depend]
ee8-security
client
```

That way you should be able to run `java -jar $JETTY_HOME/start.jar --add-modules=ee8-openid` and `--list-modules=*` should now report `ee10-openid`, `ee9-openid` and `ee8-openid`.

**Comment by gregpoulos** [comment]
@lorban Just a heads up that I noticed a similar error when trying to add the `websocket` module:
```
𝄢 java -jar $JETTY_HOME/start.jar --add-modules=websocket
ERROR : No module found to provide websocket-jetty for websocket{enabled}

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

This looks quite similar to the `openid` bug: I think this error is simply an artifact of how the various `websocket-*` modules got split/renamed to support EE8/9/10.

**Comment by lorban** [comment]
Thanks, I've added a fix for the `websocket` module too. You are right: it depends on outdated module names that should be prefixed with ee*.
