### ISSUE TITLE
All prefixes for the eeX versions of the jetty maven plugin should be "jetty".

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9155]
**jetty-12.0.x**

Maven automatically selects the prefix used for plugins based off the artifact id. The prefix in the following: `mvn foo:run` is `foo`.  For the jetty maven plugin, this has traditionally been `jetty`. But due to the convention that uses the artifact id for the prefix, you now have to use eg `mvn jetty-ee9:run` or `mvn jetty-ee10:run`.  This is redundant, as you have to specify which version of the plugin you want to use in your pom. All flavours of the plugin should just use `jetty` prefix.

**Comment by olamy** [comment]
For the record as demonstrated in this comment https://github.com/eclipse/jetty.project/pull/9156#issuecomment-1384854060 this turns the plugin as possible not determined version executed in some configuration.
