### ISSUE TITLE
javadoc build too verbose

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9157]
**Jetty version(s)**
12 at least

**Description**

If a mvn build is done from the command line with a javadoc error in the code, then the output generated is enormous and often larger than the terminal buffer of intellij.  This makes it very difficult to find the actual problem.
Can javadoc build be made less verbose and only report errors and warnings?

**Comment by joakime** [comment]
See PR #9165 for a possible alternative when you are in Intellij. (that PR does not solve for output from command line or CI)
