### ISSUE TITLE
Jetty 12: review/remove ByteBufferPool

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9166]
**Jetty version(s)**
12

**Description**
The Jetty 12 code has now standardized to use `RetainableByteBufferPool`, so `ByteBufferPool` should be removed.

This would simplify a lot the codebase, and also clean up the Jetty component tree, because now the `ByteBufferPool`s appear in the component tree, but not the `RetainableByteBufferPool`s.

This is a prerequisite for #9148, because it would then allow to inject leak-tracking `Pool` instances.

**Comment by gregw** [comment]
I'm just adding my voice of caution here, that we did try to do this before, but found a few cases that were just too hard to use the stricter `Retainable` contract for.  I can't exactly recall what they were, so this time if we find them again and decide it can't be done, then we should document in the code what those cases are.

Note that I think we can change the API of `RetainableByteBuffferPool` to make it easier to leak track independently of removing the non retained pool.   We can track leaks for just retainable usages.

**Comment by gregw** [comment]
I'm just adding my voice of caution here, that we did try to do this before, but found a few cases that were just too hard to use the stricter `Retainable` contract for.  I can't exactly recall what they were, so this time if we find them again and decide it can't be done, then we should document in the code what those cases are.

Note that I think we can change the API of `RetainableByteBuffferPool` to make it easier to leak track independently of removing the non retained pool.   We can track leaks for just retainable usages.

**Comment by sbordet** [comment]
Fixed by #9195.
