### ISSUE TITLE
Jetty 12 - Response.writeError should close the connection on terminal responses (like 503)

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9176]
**Jetty version(s)**
Jetty 12

**Description**
Some code snippets look like this ...

``` java
if (!response.isCommitted())
{
    if (LOG.isDebugEnabled())
        LOG.debug("Service Unavailable (before wrapped process): {}", request.getHttpURI());
    response.getHeaders().put(HttpHeader.CONNECTION, HttpHeaderValue.CLOSE);
    Response.writeError(request, response, callback, HttpStatus.SERVICE_UNAVAILABLE_503);
}
````

In order to not have to specify `Connection: close` for things like HTTP/2 or HTTP/3, some errors should be terminal and close the connection.

**Comment by gregw** [comment]
It is difficult to define "terminal".   In this case, there is nothing about a 503 that is terminal from a protocol point of view.  However, it is likely that this is being done as part of a graceful shutdown, so from an operational point of view the connection should be closed.  I can't see how this distinction can be made at a lower level.

**Comment by gregw** [comment]
Probably not needed as a Connector should know if it is in shutdown mode and do a protocol specific shutdown mechanism.  No need for application layer to say close.

**Comment by joakime** [comment]
How about altering the core API to include a boolean for closeConnection?

``` java
boolean closeConnection = true;
Response.writeError(request, response, callback, closeConnection, HttpStatus.SERVICE_UNAVAILABLE_503);
```

**Comment by sbordet** [comment]
@joakime no, as @gregw says, it is the implementation (by looking at how the request has been processed, for example whether the content has been read) and the `Connector` (when it is shutting down) that knows whether to close the connection.

Otherwise, for a 503 response, we can keep the connection open in HTTP/1.1.

Adding a parameter that only works for HTTP/1.1 does not seem a good idea.

**Comment by joakime** [comment]
The problem still exists, and still needs a http version neutral solution.
Don't get hung up on "close connection", that's just draft terminology for the desire to terminate the exchange.  It needs better language to fit this http version neutral need.

It can easily be ...
``` java
boolean terminateResponse = true; // on http/1.1 it will close the connection, on http/2, and http/3 it will close the stream.
Response.writeError(request, response, callback, terminateResponse, HttpStatus.SERVICE_UNAVAILABLE_503);
```

**Comment by sbordet** [comment]
I'm saying that there is no need for an application to "terminate the exchange".
What would that mean in HTTP/2?

**Comment by gregw** [comment]
I also do not think this is needed.  The application should be mostly neutral with regards to any connection semantics.  The `writeError` method itself will terminate the connection (reset) if necessary.

**Comment by sbordet** [comment]
Closing as not needed.
