### ISSUE TITLE
mvn jetty:run (11.0.13) is unable to find the default websocket server configurer

### ISSUE THREAD

**Issue by Artur-** [eclipse/jetty.project#9180]
**Jetty version(s)**
11.0.13

**Java version/vendor** `(use: java -version)`
openjdk version "19.0.1" 2022-10-18

**OS type/version**
mac / Ventura

**Description**

If I try to register a websocket endpoint like this
```
            ServerEndpointConfig endpointConfig = ServerEndpointConfig.Builder
                    .create(ViteWebsocketEndpoint.class, path)
                    .subprotocols(subProtocols)
                    .build();
```

and run the app with `mvn jetty:run`, it always fails with
```
Caused by: java.lang.RuntimeException: Cannot load platform configurator
	at jakarta.websocket.server.ServerEndpointConfig$Configurator.fetchContainerDefaultConfigurator(ServerEndpointConfig.java:96)
	at jakarta.websocket.server.DefaultServerEndpointConfig.<init>(DefaultServerEndpointConfig.java:57)
	at jakarta.websocket.server.ServerEndpointConfig$Builder.build(ServerEndpointConfig.java:262)

```
which is caused by
```
        static ServerEndpointConfig.Configurator fetchContainerDefaultConfigurator() {
            for (ServerEndpointConfig.Configurator impl : ServiceLoader
                    .load(jakarta.websocket.server.ServerEndpointConfig.Configurator.class)) {
                return impl;
            }
            throw new RuntimeException("Cannot load platform configurator");
        }
```
which in turn is unable to find any `jakarta.websocket.server.ServerEndpointConfig.Configurator` even though Jetty defines one in  https://github.com/eclipse/jetty.project/blob/jetty-11.0.13/jetty-websocket/websocket-jakarta-server/src/main/resources/META-INF/services/jakarta.websocket.server.ServerEndpointConfig%24Configurator

If I add my own `Configurator` like 
```
Configurator configurator = new ServerEndpointConfig.Configurator() {
                @Override
                public <T> T getEndpointInstance(Class<T> endpointClass)
                        throws InstantiationException {
                    try {
                        return endpointClass.getDeclaredConstructor()
                                .newInstance();
                    } catch (IllegalAccessException | IllegalArgumentException
                            | InvocationTargetException | NoSuchMethodException
                            | SecurityException e) {
                        throw new InstantiationException(e.getMessage());
                    }
                }
            };

            ServerEndpointConfig endpointConfig = ServerEndpointConfig.Builder
                    .create(ViteWebsocketEndpoint.class, path)
                    .configurator(configurator).subprotocols(subProtocols)
                    .build();

```

then the websocket endpoint works as apparently no lookup of the configurator is done through the service loader.

**Comment by joakime** [comment]
Sounds like ServiceLoader is broken on your environment.

**Comment by Artur-** [comment]
Well the environment is `mvn jetty:run`. Not sure how the service loader can be "broken"

**Comment by Artur-** [comment]
Another service loader call, apparently by Jetty, for `"META-INF/services/org.eclipse.jetty.webapp.Configuration"` also works fine and returns "file:/.../.m2/repository/org/eclipse/jetty/jetty-maven-plugin/11.0.13/jetty-maven-plugin-11.0.13.jar!/META-INF/services/org.eclipse.jetty.webapp.Configuration"

**Comment by joakime** [comment]
> ```
> Caused by: java.lang.RuntimeException: Cannot load platform configurator
> 	at jakarta.websocket.server.ServerEndpointConfig$Configurator.fetchContainerDefaultConfigurator(ServerEndpointConfig.java:96)
> 	at jakarta.websocket.server.DefaultServerEndpointConfig.<init>(DefaultServerEndpointConfig.java:57)
> 	at jakarta.websocket.server.ServerEndpointConfig$Builder.build(ServerEndpointConfig.java:262)
> ```

This error comes from the Jakarta Websocket Server API jar (not even Jetty).

* See: https://github.com/jakartaee/websocket/blob/2.0.0-RELEASE/api/server/src/main/java/jakarta/websocket/server/ServerEndpointConfig.java#L91-L97

Jetty provides the `META-INF/services/jakarta.websocket.server.ServerEndpointConfig$Configurator` file.

* https://github.com/eclipse/jetty.project/blob/jetty-11.0.13/jetty-websocket/websocket-jakarta-server/src/main/resources/META-INF/services/jakarta.websocket.server.ServerEndpointConfig%24Configurator

Which points to the Jetty implementation

* https://github.com/eclipse/jetty.project/blob/jetty-11.0.13/jetty-websocket/websocket-jakarta-server/src/main/java/org/eclipse/jetty/websocket/jakarta/server/config/ContainerDefaultConfigurator.java

Which has a simple constructor that doesn't fail.

Go ahead and set a breakpoint on the Jakarta Websocket Server API Jar's ` fetchContainerDefaultConfigurator()` implementation and see what's actually happening, it's something with your ServiceLoader environment that's not working as expected.

**Comment by Artur-** [comment]
Yes, I looked at all that earlier but couldn't figure out the root cause. I am still not sure why it is a problem but it seems like `fetchContainerDefaultConfigurator` in this case is run from a separate thread through some async future created in a `ServletContextListener` and in that thread, the service loader won't return the configurator.

**Comment by joakime** [comment]
Do you have a `jetty-maven-plugin` configuration in your vaadin build I can look at?

**Comment by Artur-** [comment]
It is only this
```
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty.version}</version>
                <configuration>
                    <!-- If using IntelliJ IDEA with autocompilation, this
                    might cause lots of unnecessary compilations in the
                    background.-->
                    <scanIntervalSeconds>2</scanIntervalSeconds>
                    <!-- Use war output directory to get the webpack files -->
                    <webAppConfig>
                        <allowDuplicateFragmentNames>true</allowDuplicateFragmentNames>
                    </webAppConfig>
                </configuration>
            </plugin>
```

but I can confirm with a debugger that
```
java.util.ServiceLoader.load(jakarta.websocket.server.ServerEndpointConfig.Configurator.class).findFirst()
```
correctly returns `Optional[org.eclipse.jetty.websocket.jakarta.server.config.ContainerDefaultConfigurator]` when executed inside the servlet context listener and an empty optional once inside `CompletableFuture.runAsync(runnable);`.

The difference appears to be that the context class loader inside `runAsync` is a `jdk.internal.loader.ClassLoaders$AppClassLoader` and not `org.eclipse.jetty.webapp.WebAppClassLoader` like in the context listener

**Comment by Artur-** [comment]
I will fix the Vaadin code then, because it is not even supposed to try to register an endpoint in another thread. Thanks

**Comment by joakime** [comment]
Yes, that would do it.

It's important to maintain the scope of the Servlet dispatch when you start to fire off more threads on your own (if not using the new thread techniques in the Servlet API).

**Comment by joakime** [comment]
If you are so inclined, you can do this ...

Create an Executor that has a custom `ThreadFactory`.
That `ThreadFactory` has a reference to the `ServletContext` `ClassLoader`, and sets `Thread.setContextClassLoader(ClassLoader)` when it's creating new threads.
This configured `Executor` can be used by `CompletableFuture.runAsync(Runnable, Executor)` reliably

You can have an `ServletContextListener` manage this `Executor`, and shove it into the `ServletContext.setAttributes()` for access anywhere else.
(Have it create the `Executor` on  `.contextInitialized(ServletContextEvent sce)` and shut it down on `.contextDestroyed(ServletContextEvent sce)`)

**Comment by Artur-** [comment]
But is it even allowed by the spec to register websocket endpoints "later" in another thread?

**Comment by joakime** [comment]
/me puts on his Jakarta WebSocket Spec hat ...

@Artur- strictly speaking, no.
But it's more nuanced, you should be only deploying new websocket endpoints during the Servlet Initialization phase.
https://github.com/jakartaee/websocket/blob/2.0.0-RELEASE/spec/src/main/asciidoc/WebSocket.adoc#64-programmatic-server-deployment
This makes no restriction on deploying from another thread, just that you do it during the Servlet initialization phase. (before the ServletContext goes available and starts accepting requests)

If you are wanting to be spec compliant across all implementations then you should follow this rule.
