### ISSUE TITLE
Jetty 12 - Public version of JakartaWebSocketServerContainer

### ISSUE THREAD

**Issue by Sineaggi** [eclipse/jetty.project#9182]
**Enhancement Description**
Spring uses the internal `JakartaWebSocketServerContainer`, which requires the use of `--add-opens org.eclipse.jetty.websocket.jakarta.server/org.eclipse.jetty.websocket.jakarta.server.internal=ALL-UNNAMED` when running spring boot under the module path. The spring boot issue is https://github.com/spring-projects/spring-boot/issues/33833

Currently spring boot uses the class for https://github.com/spring-projects/spring-boot/blob/fe7b13ec46f9960bebfddad984816e353f9c9349/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/websocket/servlet/JettyWebSocketServletWebServerCustomizer.java#L23 to call `getContainer` and `ensureContainer`.

**Comment by lachlan-roberts** [comment]
@Sineaggi This code should be using `JakartaWebSocketServletContainerInitializer.configure(ServletContextHandler context, Configurator configurator)` or `JakartaWebSocketServletContainerInitializer.initialize(ServletContextHandler context)` methods for setting up Jakarta WebSockets. This will set up the same internal components but does need direct access to any classes in the internal packages.

Do you know why spring requires use of the `JakartaWebSocketServerContainer` class directly?

**Comment by janbartel** [comment]
@Sineaggi nudge

**Comment by Sineaggi** [comment]
This class is used by spring-boot https://github.com/spring-projects/spring-boot/issues/33833 to configure their internal websocket customizer https://github.com/spring-projects/spring-boot/blob/fe7b13ec46f9960bebfddad984816e353f9c9349/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/websocket/servlet/JettyWebSocketServletWebServerCustomizer.java#L23.

Similar to the call `JettyWebSocketServerContainer.getContainer(context.getServletContext())`, spring boot makes a call to `JakartaWebSocketServerContainer.getContainer(context.getServletContext())`.

**Comment by Sineaggi** [comment]
Perhaps @wilkinsona can add more context

**Comment by wilkinsona** [comment]
> JakartaWebSocketServletContainerInitializer.configure(ServletContextHandler context, Configurator configurator)

Spring Boot [does not support ServletContainerInitializers](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/index.html#web.servlet.embedded-container.context-initializer) so this would have no effect in a Boot app.

> JakartaWebSocketServletContainerInitializer.initialize(ServletContextHandler context)

Apologies if I am looking in the wrong place but this [appears to be `private`](https://github.com/eclipse/jetty.project/blob/e5b313e379fd7a9d2b74094b3beb569da5ac8835/jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/config/JakartaWebSocketServletContainerInitializer.java#L134). If it were public, I think it would meet our needs although this is based purely on looking at the code.

**Comment by lachlan-roberts** [comment]
@wilkinsona the `JakartaWebSocketServletContainerInitializer.configure(ServletContextHandler context, Configurator configurator)` method programatically registers the SCI with Jetty so I think it would still work unless you have overridden the `ServletContextHandler` to modify the behaviour.

But yes I thought `JakartaWebSocketServletContainerInitializer.initialize` was already public. I will put up a PR to make this public, and also review if we should make `JakartaWebSocketServerContainer` public as well.

**Comment by lachlan-roberts** [comment]
I have merged the changes from https://github.com/eclipse/jetty.project/pull/9395 into Jetty 12.

Now both `JakartaWebSocketServletContainerInitializer.initialize` and the `JakartaWebSocketServerContainer` are public. But you should prefer to use the `initialize()` method instead of doing the ensure container yourself.
