### ISSUE TITLE
Support initial bind as web user on LdapLoginModule

### ISSUE THREAD

**Issue by alexandrehuard1** [eclipse/jetty.project#9186]
**jetty-9.4.39-v20210325**

**Support initial bind as web user on LdapLoginModule**

When forceBindingLogin is set to true, make it possible to use the web credentials as bindDn and bindPassword to avoid hard coding them.

Similar to what httpd does. https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html#authldapinitialbindasuser 

AuthLDAPInitialBindAsUser
Description: Determines if the server does the initial DN lookup using the basic authentication users' own username, instead of anonymously or with hard-coded credentials for the server

By default, the server either anonymously, or with a dedicated user and password, converts the basic authentication username into an LDAP distinguished name (DN). This directive forces the server to use the verbatim username and password provided by the incoming user to perform the initial DN search.

**Comment by janbartel** [comment]
@AlexHuard jetty-9 is End of Life, but we'd be pleased to review a PR to implement this against jetty-10.
