### ISSUE TITLE
jetty-12 javadoc on Stream.Listener.onDataAvailable(Stream) is wrong

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9190]
**jetty-12.0.x**

Javadoc from org.eclipse.jetty.http.api.Stream.Listener.onDataAvailable(Stream) says:

>           class MyStreamListener implements Stream.Listener
>           {
>               &#64;Override
>               public void onDataAvailable(Stream stream)
>               {
>                   // Read a chunk of the content.
>                   Stream.Data data = stream.readData();
>                   if (data == null)
>                   {
>                       // No data available now, demand to be called back.
>                       stream.demand();
>                   }
>                   else
>                   {
>                       // Process the content.
>                       process(data.getByteBuffer());
>                       // Notify that the content has been consumed.
>                       data.release();
>                       if (!data.frame().isEndStream())
>                       {
>                           // Demand to be called back.
>                           stream.demand();
>                       }
>                   }
>               }
>           }

However there is no such method `Stream.Data.getByteBuffer()`.

**Comment by sbordet** [comment]
Fixing this in #9195.
