### ISSUE TITLE
Implement ability to filter web crawlers from session creation

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#92]
migrated from Bugzilla [#346819](https://bugs.eclipse.org/bugs/show_bug.cgi?id=346819)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _7.4.2_ on platform _All_
Assigned to: Project Inbox

On 2011-05-22 23:42:53 -0400, Greg Wilkins wrote:

> http://www.tomcatexpert.com/blog/2011/05/18/crawler-session-manager-valve

**Comment by joakime** [comment]
One way to implement this perhaps is a `HttpConfiguration.Customizer` that identifies web crawlers and sets the JSESSION ID to a known "crawler" value, so that all requests use the same Cookie.

**Comment by joakime** [comment]
Also, this could apply to various load balancer and monitoring "ping" requests in a similar fashion.
By artificially specifying a known JSESSION ID for those requests, preventing each request from generating a new Session object.

Example of this - https://stackoverflow.com/questions/7708035/tomcat-how-to-stop-tomcat-creating-a-session-for-all-requests
