### ISSUE TITLE
no main manifest attribute, in jetty-runner-9.2.19.v20160908.jar

### ISSUE THREAD

**Issue by petr-n** [eclipse/jetty.project#920]
Today I have used latest 9.2.\* version - jetty-runner-9.2.19.v20160908.jar and I have got this error:

pene@petr-ThinkPad-T410:~/run$ sudo java -jar -Dabra.basicstorage.home=basicstorage jetty-runner-9.2.19.v20160908.jar --port 80 igate.war
[sudo] heslo pro pene: 
no main manifest attribute, in jetty-runner-9.2.19.v20160908.jar

I have seen there is fix for version 9.3.*. Is it possible to merge the fix to version 9.2?

**Comment by janbartel** [comment]
Bizarre:  when I build jetty-9.2.20-SNAPSHOT locally, the Main-Class property is clearly in the MANIFEST.MF file. However, if I download the latest jetty-9.2.20-SNAPSHOT from https://oss.sonatype.org/content/repositories/jetty-snapshots/org/eclipse/jetty/jetty-runner/9.2.20-SNAPSHOT/, it isn't there!

Investigating.

**Comment by joakime** [comment]
This is still a problem in jetty 9.2.21 release too.

@olamy didn't you do some work on this?

**Comment by olamy** [comment]
well I remember having a look at the build. 
But I didn't really fix it in any branch as 9.2.x is deprecated/obsolete.
let me know I can have a look for sure.

**Comment by joakime** [comment]
@olamy ah, I seem to remember that too.  Do you recall which branch the fix was put into?

**Comment by olamy** [comment]
might be this one https://github.com/olamy/jetty.project/tree/bug/deploy_osgi_missing  (not really sure)
Not sure but it was issue with bundle plugin executed in the wrong phase.

**Comment by joakime** [comment]
If you want to submit those 2 commits as a PR, they look good.  I'll merge em.

**Comment by olamy** [comment]
sure. I will test again the fix.
I will probably focus only on jetty-runner.

**Comment by olamy** [comment]
well after having a look at jetty-runner I wonder if this really need to be OSGI.
As it's simply an uber jar so nothing really OSGI style.
WDYT?

**Comment by jmcc0nn3ll** [comment]
yeah, I don't see why jetty-runner should have anything to do with osgi

**Comment by janbartel** [comment]
PR #1370 applied
