### ISSUE TITLE
Jetty 12 - Clean up shutdown / stop of server

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9200]
**Jetty version(s)**
Jetty 12

**Description**
In Jetty 12 we have the following classes for triggering shutdown / stop of the server.

**`org.eclipse.jetty.ee8.nested.ShutdownHandler`**
    an ee8 `HandlerWrapper` - responds to HTTP requests like `/shutdown?token=blah`

**`org.eclipse.jetty.ee9.nested.ShutdownHandler`**
    an ee9 `HandlerWrapper` (seemingly implemented, with test case) - responds to HTTP requests like `/shutdown?token=blah`

**`org.eclipse.jetty.server.handler.ShutdownHandler`**
    a jetty-core `Handler.Wrapper` (mostly commented out, and disabled test cases).

**`org.eclipse.jetty.server.handler.GracefulShutdownHandler`**
    a jetty-core `Handler.Wrapper` for graceful handling for requests going thru it, not actually involved in triggering stop or shutdown, but rather cooperates with the `Graceful` behaviors triggered elsewhere.

**`org.eclipse.jetty.server.ShutdownMonitor`**
    a jetty-core simple `ServerSocket` that only responds to simple strings (`stop` / `forcestop` / `stopexit` / `exit` / `status` / `pid`) - this is also the central gathering place for any `LifeCycle` in Jetty that wants to stop with the Server but isn't registered as a bean of the Server

What I see here ...

* We have a whole JVM shutdown concept in `ShutdownMonitor`
* We have a Server instance specific stop/shutdown logic in `ShutdownHandler` (in jetty-core)
* We have extra `ShutdownHandler` instances in the environments that seem to have no purpose (lets get rid of them)
* We have a poorly named `GracefulShutdownHandler` that should probably be renamed to just `GracefulHandler` to avoid it being associated with this triggering of stop / shutdown.
* The registration of arbitrary `LifeCycle` in `ShutdownMonitor` isn't mimicked in `ShutdownHandler`

**Comment by joakime** [comment]
Note: the `start.jar --stop` concept is using a simple `Socket` to talk to the `ShutdownMonitor` to perform it's actions.

This is because `start.jar --stop` is viewed as a whole JVM command.

**Comment by gregw** [comment]
I don't think we need any `ShutdownHandler`s - that is a very old concept.     remove them all I think.
Just have a `GracefulHandler`.

I'd probably leave any changes to `start.jar --stop` to another PR.

**Comment by joakime** [comment]
The ShutdownHandler came from a community patch in 2011.

> Johannes Brodwall: https://bugs.eclipse.org/bugs/show_bug.cgi?id=357687

**Comment by gregw** [comment]
I don't think it is a good enough mechanism to include... let alone 4 versions of it!
Maybe keep a single version as a core handler as a demo in the doco?

**Comment by joakime** [comment]
Closing PR #9201 merged
