### ISSUE TITLE
Replacement of WebSocketServerFactory.java class in jetty 10

### ISSUE THREAD

**Issue by Naziburjec** [eclipse/jetty.project#9204]
**Jetty version** 
Jetty 10.0.12

**Java version** 
JDK11

**Question**
Below classes created in jetty 9 by extending from WebSocketHandler class and WebSocketServerFactory class. Now, we want to upgrade to jetty 10 but facing difficulties as both WebSocketHandler and WebSocketServerFactory class is not available in jetty 10. Is there any replacement of WebSocketServerFactory class in jetty 10?

```
public class Jetty9SocketHandler extends WebSocketHandler
{
    private final WebSocketServerFactory _webSocketFactory;
    public NegotiationSocketHandler()
    {
        WebSocketPolicy policy = new WebSocketPolicy(WebSocketBehavior.SERVER);
        configurePolicy(policy);
        _webSocketFactory = new Jetty9SocketServerFactory(policy);
        addBean(_webSocketFactory);
    }

    @Override
    public void configure(final WebSocketServletFactory factory)
    {
        _webSocketFactory.getPolicy().setIdleTimeout(TimeUnit.MINUTES.toMillis(30));
    }
   
    @Override
    public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
    {
        if (_webSocketFactory.isUpgradeRequest(request,response))
        {
            if (_webSocketFactory.acceptWebSocket(request,response))
            {
                baseRequest.setHandled(true);
                return;
            }
            if (response.isCommitted())
            {
                return;
            }
        }
        super.handle(target,baseRequest,request,response);
    }
}
```

```
public class Jetty9SocketServerFactory extends WebSocketServerFactory
{
    private static final Executor executor = CustomExecutors.newFabricCachedThreadPool(10, "jetty-threads");
    private static final ByteBufferPool bufferPool = new ArrayByteBufferPool(0, 0, 65536);

    public Jetty9SocketServerFactory(WebSocketPolicy policy)
    {
        super(policy, executor, bufferPool);
    }

    @Override
    public Object createWebSocket(ServletUpgradeRequest req, ServletUpgradeResponse resp)
    {
        return new sendCustomObject();
    }
    
}
```

**Comment by lachlan-roberts** [comment]
I suggest looking at the websocket migration guide https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-migration-94-to-10-websocket and the documentation for Jetty-10 websocket https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-server-websocket.

But I think the replacement class is the `JettyWebSocketServerContainer` with this you can register `JettyWebSocketCreator`s to different pathspecs which will add the `WebSocketUpgradeFilter`.

But you should use the `JettyWebSocketServletContainerInitializer.configure(ervletContextHandler context, Configurator configurator)` to set up websockets, and then use the `Configurator` to access the `JettyWebSocketServerContainer`.

**Comment by Naziburjec** [comment]
Thank you. how to pass executor object and bufferpool size to JettyWebSocketServerContainer?

**Comment by lachlan-roberts** [comment]
The `JettyWebSocketServletContainerInitializer` will automatically find and use shared instances of these from the server, but if you wish to set your own you can do that as well. 

Take a look at the logic inside `WebSocketServerComponents` and you will see how these resources are acquired:

1. You can create your own `WebSocketComponents` instance and set it at `org.eclipse.jetty.websocket.core.WebSocketComponents` servlet context attribute.
2. You can set an executor as `org.eclipse.jetty.server.Executor` servletContext attribute.
3. You can set your threadPool on the server and it will use that as the executor.
4. `ByteBufferPool` can be set as `jetty.websocket.bufferPool` servletContext attribute.
5. `ByteBufferPool` can be set as a bean on the server.

but I would stick with using what is found on the server unless you have a specific reason to use a custom one for your context.
