### ISSUE TITLE
Jetty 12 - Delete `config` classified artifact produced by `jetty-websocket-core-server`

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9215]
**Jetty version(s)**
12+

**Description**
Due to a change in PR #9160 to delete the file `jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/config/modules/websocket.mod`, the `config` classified artifact being produced by
`jetty-websocket-core-server` will wind up being empty for a little while (to prevent the `websocket.mod` from being accidentally reintroduced from an old SNAPSHOT of that same `-config.jar`)

This is a task to delete the production of this empty `-config.jar` once that PR is merged and the empty config jar shows up on oss.sonatype.org

**Comment by joakime** [comment]
And associated -config.jar

**Comment by joakime** [comment]
This was taken care of in commit 856d3338f23ac028531aa91f52ec84f47780e59e
