### ISSUE TITLE
HttpClient request with Socks4Proxy results in "tunnel failed with code 91"

### ISSUE THREAD

**Issue by IhorYutinDev** [eclipse/jetty.project#9219]
**Jetty version**
9.4.25.v20191220, 9.4.12.v20180830

**Java version
java 8**

**Question**
When i'm trying to send request via jetty httpClient with new Socks4Proxy(socksHost, socksPort),
received: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91

`     
  
      

        SslContextFactory.Client sslContextFactory = new SslContextFactory.Client();
        sslContextFactory.setEndpointIdentificationAlgorithm(null);
        HttpClient httpClient = new HttpClient(sslContextFactory);
        ProxyConfiguration proxyConfig = httpClient.getProxyConfiguration();
        Socks4Proxy proxy = new Socks4Proxy(socksHost, socksPort);
        proxyConfig.getProxies().add(proxy);

        httpClient.start();

        String url = "https://www.google.com";
        Request request = httpClient.newRequest(url);
        request.method(HttpMethod.GET);
        request.onResponseContent(new BufferingResponseListener() {
            @Override
            public void onComplete(Result result) {
                String s = getContentAsString();
            }
        });

        try {
            request.send();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }`
received: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91

Help me please with this problem or show simply way to use httpClient with socks4

**Comment by sbordet** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Please try Jetty 10/11.

**Comment by sbordet** [comment]
This is not a Jetty issue, it's the SOCKS proxy rejecting your request. You should look into that.

**Comment by joakime** [comment]
Closing, as it's been answered twice, on an End of Life version of Jetty.

Previous answer to same question from https://stackoverflow.com/questions/75259557/jetty-httpclient-add-proxy-socks4

> Per https://www.openssh.com/txt/socks4.protocol
>
> Your 91 status means that request was rejected or failed. The user or source program is not authorized to access the proxy server.
>
> Perhaps your SOCKS4 proxy has an authentication requirement.

You'll need to address this issue with whomever is in control over that SOCKS4 Proxy, and then make the appropriate configuration changes to your copy of Jetty HttpClient.
