### ISSUE TITLE
Implements methods Connection.getBytes[In|Out]()

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#922]
Those methods are currently not implemented.

**Comment by sbordet** [comment]
@olamy implementing these for HTTP/2, client and server, so you can have an example for the other transports.

**Comment by sbordet** [comment]
@olamy don't work on this yet, it requires #131 to be fixed first, which I am working on.

**Comment by olamy** [comment]
@sbordet Thanks. 
IMHO we need a ConnectionStatisticsServlet to expose values tru http
I will work on that: http, https and ConnectionStatisticsServlet

**Comment by sbordet** [comment]
@olamy there is no need for `ConnectionStatisticsServlet`, since `StatisticsServlet` already does it.

**Comment by sbordet** [comment]
@olamy, have you got some progress on this ?

**Comment by olamy** [comment]
Nope I was more focused on the Jenkins plugin.

**Comment by olamy** [comment]
@sbordet implemented for http see #1965. thanks to review.
