### ISSUE TITLE
Why does JakartaWebSocketServerContainer extend JakartaWebSocketClientContainer instead of JakartaWebSocketContainer??

### ISSUE THREAD

**Issue by sarobenalt** [eclipse/jetty.project#9222]
Jetty 11.0.13

OpenJDK 11 (Azul Zulu)

I am trying to resolve a dependency issue in an app which embeds Jetty 11 in Apache Felix. My OSGI app provides numerous services via embedded servlets to an Angular based client. In adding a websocket-based service to implement part of my UI functionality, I found that it apparently isn't possible to use the Jakarta Websocket Server implementation without introducing a bunch of dependencies on Websocket Client libraries. While examining the source code for websocket-jakarta-server-11.0.13.jar, I noticed that the dependency on client libs seems to come from the fact that the class hierarchy looks like:

JakartaWebSocketServerContainer extends JakartaWebSocketClientContainer
 - and -
JakartaWebSocketClientContainer extends JakartaWebSocketContainer

Given the general division of jars into the common/server/client triplets, I would expect a server app to require common, but not client, and a client app to require common but not server. If this is a valid assumption, then I would expect JakartaWebSocketServerContainer to extend JakartaWebSocketContainer, possibly requiring movement of code required by both client and server into the common jar.

At first glance, I don't understand why the dependency is the way it is, but I can try to dig deeper. I'm hoping that someone more familiar with the source can explain this to save me some time.

**Comment by lachlan-roberts** [comment]
Its just because the `jakarta.websocket-api` has a dependency on `jakarta.websocket-client-api` so there is nothing we can do about it. The `ServerContainer` interface in the Jakarta WebSocket API extends the `WebSocketContainer` (client container) interface.

For the Jetty WebSocket API we don't have this constraint so we have done it like you have described. You can have the websocket-server package without bringing in the websocket-client. So if you are ok using a Jetty specific API then this is possible.

**Comment by sarobenalt** [comment]
I did see the dependency of jakarta-websocket-api on jakarta-websocket-client-api, but this is a different dependency. Seems to stem from embedding an HttpClient into the JakartaWebSocketServerContainer to allow it to invoke the superclass constructor and I didn't see how the embedded HttpClient was intended to be used. I am going to try experimenting with making the change and see how far I get with it. If it looks promising, I'll provide a PR if wanted.

**Comment by lachlan-roberts** [comment]
The server container is also a client container by design of the API, so it needs to have an HttpClient (or create one if needed). There is nothing we can do about this and it won't be possible to change it in a PR as it is part of the standard API.

If you want to use websocket server without dependency on the client look at the jetty websocket server API.

**Comment by joakime** [comment]
@sarobenalt he's talking about the low level API `jakarta.websocket`.

The Jetty Server implementation has to extend from [`jakarta.websocket.server.ServerContainer`](https://github.com/jakartaee/websocket/blob/master/api/server/src/main/java/jakarta/websocket/server/ServerContainer.java)

The Jakarta WebSocket `ServerContainer` extends from [`jakarta.websocket.WebSocketContainer`](https://github.com/jakartaee/websocket/blob/master/api/client/src/main/java/jakarta/websocket/WebSocketContainer.java), which is the Client container.

This is how the `jakarta.websocket` API / Spec is setup.

**Comment by joakime** [comment]
Note that the `jakarta.websocket.server.ServerContainer` interface has API methods ...

``` java
Session connectToServer(Object annotatedEndpointInstance, URI path) throws DeploymentException, IOException;
Session connectToServer(Class<?> annotatedEndpointClass, URI path) throws DeploymentException, IOException;
Session connectToServer(Endpoint endpointInstance, ClientEndpointConfig cec, URI path) throws DeploymentException, IOException;
Session connectToServer(Class<? extends Endpoint> endpointClass, ClientEndpointConfig cec, URI path) throws DeploymentException, IOException;
```

Which are Client APIs to initiate connections to remote servers.

**Comment by sarobenalt** [comment]
I understand. I'll refrain from commenting further on the spec itself as to why a server container should provide client APIs for those who only need to implement server functionality. I'll look at using the Jetty endpoints instead.
