### ISSUE TITLE
Jetty 10.0.13 - HttpURI

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9226]
**Jetty version**
10.0.13

**Java version**
JDK 17

**Question**
Can anyone know how we can use HttpURI in 10.0.13 in version 9.4 we were able to use it like this 
final HttpURI uri = new HttpURI("http://localhost:9000" + url + params);
but now i am getting 'HttpURI' is abstract; cannot be instantiated

**Comment by sbordet** [comment]
`HttpURI uri = HttpURI.build("http://localhost:9000/" + url + params)` for a mutable version,
`HttpURI uri = HttpURI.from("http://localhost:9000/" + url + params)` for an immutable version.
