### ISSUE TITLE
Jetty 10.0.13 required jars

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9232]
**Jetty version**
10.0.13

**Java version**
17

**Question**
I am upgrading jetty from 9.4 to 10.0.13, we are embedding the jetty server in the final build, in my jetty project's pom.xml if i add dependency mentioned in jetty-bom, after the maven build in target folder i can see many jar(e.g. wildfly,netty,jnr,grpc etc.) which are not part of the jetty 10.0.13 distribution lib. How can i add only required dependency in my pom.xml so that the only the jar which are required at server runtime get included in build e.g. only jar which are part of jetty distribution's lib folder.

**Comment by joakime** [comment]
You shouldn't be using jetty-bom directly like that.
The `jetty-bom` is a Maven Bill of Materials artifact.

It's not meant to be used as a `<dependency>`, but rather as a import in a `<dependencyManagement>` section.

See the official maven docs on bom.
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms

> How can i add only required dependency in my pom.xml so that the only the jar which are required at server runtime get included in build.

That depends on what you use.
The "jetty distribution" doesn't exist in Jetty 10.
There's only the `jetty-home`, which is a subset of some libs, and a module system that will flesh out what libs to use based on your chosen set of features / modules.  
Depending on the modules you add or enable, more libs are often downloaded to your jetty-base to create a valid instance of your chosen configuration.
There is no configuration you can create that will enable all libs in the jetty-home tarball/zip (that would be an impossible classpath and wouldn't allow anything to start).

**Comment by sushikarwasra** [comment]
thanks, i will check the POM again i was referring to lib folder in jetty-home-10.0.13 and trying to add dependency for all the jar's in POM which are present in lib folder.

**Comment by joakime** [comment]
> thanks, i will check the POM again i was referring to lib folder in jetty-home-10.0.13 and trying to add dependency for all the jar's in POM which are present in lib folder.

I would not recommend doing that.
Depending on what exactly you did, you either have an incomplete classpath, or a classpath full of conflicting implementations.

The correct thing to do is to use the build tool of your choice properly, and only select the artifacts / dependencies that you need. (not all of them, or any flavor of all of them)

**Comment by janbartel** [comment]
Seems like your question has been answered.
