### ISSUE TITLE
Does Jetty support Java 17 now?

### ISSUE THREAD

**Issue by JoeJoe1989** [eclipse/jetty.project#9239]
**Jetty version**
10.0.13
**Java version**
Open JDK 17 LTS
**Question**
Hi, 

Does Jetty support Java 17 now? What is the minimum version of Jetty needed? According to [this wiki](https://shibboleth.atlassian.net/wiki/spaces/IDP4/pages/2936012848/Jetty10), it seems to be 10.0.13. However, I did not find such info in [release note](https://github.com/eclipse/jetty.project/releases/tag/jetty-10.0.13). 

Thank you.

**Comment by joakime** [comment]
Jetty 10.x and Jetty 11.x support Java 11 LTS and 17 LTS.

We build / test those Jetty branches with Temurin 11, Temurin 17, and Oracle 19

Jetty 10.x and Jetty 11.x have a Java 11 minimum requirement.

Jetty 12 has a Java 17 minimum requirement.

**Comment by joakime** [comment]
We first started supporting JDK 17 on Jetty 10.x and Jetty 11.x back in July 2021.

Today, we have artifacts being built in Jetty 10.x and 11.x specifically for JDK 17 (the Quic/Quiche stuff), and JDK 19 (the loom stuff)

Jetty tends to support the most recent JDK always.
Our build / test setups on CI are often using a matrix of JVMs (a range from the minimum supported, to LTS versions, to whatever is the latest EA release)

**Comment by JoeJoe1989** [comment]
Got it. Thanks!
