### ISSUE TITLE
Jetty 12 org.mortbay.jasper.* modules contains jakarta packages

### ISSUE THREAD

**Issue by PavelTurk** [eclipse/jetty.project#9241]
**Jetty version(s)**
Jetty 12

**Description**
There are `org.mortbay.jasper.apache-el-10.1.1.jar` and  `org.mortbay.jasper.apache-jsp-10.1.1.jar` in  `jetty-home/target/jetty-home/lib/ee10-apache-jsp`. Both files contains jakarta packages.

`org.mortbay.jasper.apache-el-10.1.1.jar` has `jakarta.el` which is in `jetty-home/target/jetty-home/lib/ee10-glassfish-jstl/jakarta.el.jakarta.el-api-5.0.0.jar`. 

` org.mortbay.jasper.apache-jsp-10.1.1.jar` has `jakarta.servlet.jsp` which is in `jetty-home/target/jetty-home/lib/ee10-glassfish-jstl/jakarta.servlet.jsp.jakarta.servlet.jsp-api-3.1.0.jar`

**Comment by joakime** [comment]
The project managing those dependencies is at https://github.com/jetty-project/jasper-jsp
