### ISSUE TITLE
No LSB Tags on jetty.sh script cause warning on Ubuntu 16.04

### ISSUE THREAD

**Issue by malavolti** [eclipse/jetty.project#926]
I suggest to add these LSB Tags to the **[jetty.sh](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-distribution/src/main/resources/bin/jetty.sh)** script:

```
#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          jetty
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jetty start script.
# Description:       Start Jetty web server.
### END INIT INFO
```

 to solve this kind of warnings:

```
root@jetty:/etc/init.d# cp /usr/local/src/jetty-src/bin/jetty.sh /etc/init.d/jetty
root@jetty:/etc/init.d# update-rc.d jetty defaults
insserv: warning: script 'K01jetty' missing LSB tags and overrides
insserv: warning: script 'jetty' missing LSB tags and overrides
```

On my test instance (Linux Ubuntu 16.04), the configuration works well.

I'm not an expert, but I hope it can be useful for you.

Best Regards,
Marco

**Comment by gregw** [comment]
Thanks - applied to 9.3.x and merge through 9.4 and master
