### ISSUE TITLE
Allow custom schema for session tables

### ISSUE THREAD

**Issue by nevafuse** [eclipse/jetty.project#927]
The session tables default to using the user schema in Oracle.  If you try to prefix the table name with the schema and a period, the prepareTables method will fail because getIndexInfo and getTables require the schema and table as a separate parameters.

A new schema variable with getters and setters with a default value of null needs to be created that can be prefixed to all sql queries and passed into the getIndexInfo and getTables methods.

**Comment by thoptersword** [comment]
+1

**Comment by janbartel** [comment]
Patches are welcome :)

**Comment by janbartel** [comment]
Thanks @nevafuse .
