### ISSUE TITLE
10.0.13 jetty-plus.xml

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9277]
**Jetty version**
10.0.13
**Java version**
jdk 17
**Question**
I am migrating jetty 9.4 to 10.013, in 9.4 we were using jetty-plus.xml but it seems jetty 10.0.13 is not using this xml, if i keep this xml them i am getting below in server logs. It looks the class that mentioned in the xml are no longer exist in 10.0.13.
2023-02-01 09:35:15,470  WARN [main] org.eclipse.jetty.xml.XmlConfiguration - Config error java.lang.ClassNotFoundException: org.eclipse.jetty.webapp.Configuration$ClassList at <Call class="org.eclipse.jetty.webapp.Configuration$ClassList" name="setServerDefault"><Arg><Ref refid="Server"/></Arg><Call name="addAfter"><Arg name="afterClass">org.eclipse.jetty.webapp.FragmentConfiguration</Arg><Arg>
        <Array type="String"><Item>org.eclipse.jetty.plus.webapp.EnvConfiguration</Item><Item>org.eclipse.jetty.plus.webapp.PlusConfiguration</Item></Array>
      </Arg></Call></Call> in file:/etc/jetty-plus.xml

Please suggest should i remove this xml for 10.0.13 or is there any alternative xml to be used instead.

**Comment by joakime** [comment]
Starting with Jetty 10, you don't manage the `Configuration` classes anymore.
Just have the specific jars present in your classpath (or modulepath).
The ServiceLoader mechanism and internal metadata will kick in and add them to the appropriate places.

**Comment by sushikarwasra** [comment]
thanks i will remove the jetty-plus.xml then and keep the jetty-plus-10.0.13.jar

**Comment by sushikarwasra** [comment]
Hi @joakime should i exclude jetty-annotations.xml and any such other xmls  as well which are not part of 10.0.13
2023-02-02 08:52:11,733  WARN [main] org.eclipse.jetty.xml.XmlConfiguration - Config error java.lang.ClassNotFoundException: org.eclipse.jetty.webapp.Configuration$ClassList at <Call class="org.eclipse.jetty.webapp.Configuration$ClassList" name="setServerDefault"><Arg><Ref refid="Server"/></Arg><Call name="addBefore"><Arg name="beforeClass">org.eclipse.jetty.webapp.JettyWebXmlConfiguration</Arg><Arg>
        <Array type="String"><Item>org.eclipse.jetty.annotations.AnnotationConfiguration</Item></Array>
      </Arg></Call></Call> in file:etc/jetty-annotations.xml
2023-02-02 08:52:11,737  WARN [main] org.eclipse.jetty.xml.XmlConfiguration - Unable to execute XmlConfiguration

**Comment by janbartel** [comment]
You don't need `jetty-annotations.xml` any more either. 

IIWY I would start with a clean install of jetty-10, make a new `jetty.base` directory, enable the modules that you know you need, copy only your war and any context xml file to the `jetty.base/webapps` directory, start it and see what is missing.

**Comment by sushikarwasra** [comment]
@joakime if i don't use jetty-plus.xml then my webapps are not loading similar issue reported here https://www.eclipse.org/lists/jetty-users/msg10184.html
i am also getting same error - Instead of add(String[]) it seems to try to call add(Configuration) of Configurations.
Do you know what solution was suggested to solve the problem in above link.

**Comment by joakime** [comment]
Don't manage webapp `Configuration` objects or instances, at all, for anything (server or webapp), in any XML file or embedded Jetty scenario.

The entire webapp `Configuration` layer is based on `java.util.ServiceLoader` now.
Any attempt to configure it manually in XML (for example) will just be undone later by the `ServiceLoader` mechanism present in Jetty 10.
The XML in Jetty 10's own `jetty-home` doesn't even manage webapp `Configuration` objects or instances anymore (like it used to Jetty 9).

The linked to message in jetty-users is old, and that user has now removed all efforts to manage webapp `Configuration` objects or instances as well.

If you have a custom webapp `Configuration` class, then you'll have to introduce the appropriate `META-INF/services/org.eclipse.jetty.webapp.Configuration` file in your jar and optionally specify in your webapp `Configuration` implementation if it depends on any other webapp `Configuration` classes to execute before your custom webapp `Configuration`.

**Comment by janbartel** [comment]
Advice given, no further input so closing issue.
