### ISSUE TITLE
Support or document how to use JAAS with the OSGi HttpService

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#93]
migrated from Bugzilla [#347102](https://bugs.eclipse.org/bugs/show_bug.cgi?id=347102)
status ASSIGNED severity _enhancement_ in component _osgi_ for _9.0.x_
Reported in version _7.4.2_ on platform _All_
Assigned to: Jan Bartel

On 2011-05-24 22:22:20 -0400, Hugues Malphettes wrote:

> At the moment JAAS is documented for webapps. In the OSGi world, it would be nice to be able to associate a user realm to a set of servlet/filters registered on the HttpService.
> 
> Usecase the new example HttpServices expose the equinox console on-line.
> The example configuration of jetty-osgi provided in the EclipseRTWebStarterKit should protect the access to the equinox console.
> JAAS is the obvious choice.

**Comment by janbartel** [comment]
I don't believe that the EclipseRTWebStarterKit exists in the jetty distro, at least not any more.

I think the HttpService is now pretty old, and the osgi world has moved on into supporting webapps.

However, I will leave this issue open, as we could look into putting in a test in jetty-osgi/test-jetty-osgi for a webapp that uses jaas.

**Comment by janbartel** [comment]
Open since 2011 with no updates, so there isn't any appetite for this enhancement. Reopen if you want to contribute to it.
