### ISSUE TITLE
HttpClient stuck/never releases MappedByteBufferPool buffer on timeout/IOExceptions that leads to High GC usage of Old Gen Memory

### ISSUE THREAD

**Issue by dhaboda** [eclipse/jetty.project#9314]
**Jetty version(s)**
9.4.28.v20200408

**Java version/vendor** `(use: java -version)`
1.8

**OS type/version**
"18.04.6 LTS (Bionic Beaver)"
**Description**
When Jetty HttpClient makes a connection to server and when server responds back with "Max Frame Size as 1MB and Concurrent Max Streams as 100 in Https Settings, on response receive the HttpClient allocates the MappedByteBuffer pool per connection is created with 100*1MB=100MB buffer size of max. Say for example if you have 15 connections that will be roughly 1.5GB 

When there are continuous client timeouts or IO Exceptions on a rainy day scenario in the network then Jetty is not releasing this buffer pool and holding in memory for a long time leading to Old gen space after survival in Eden space. Then we are facing a high GC cycles with memory usage of more than 80 to 90%% of JVM old gen memory of 1GB and in heapdump we observed memory leak in Jetty class MappedByteBufferPool. This memory never release even after more than a day from old gen space and we were consistently able to reproduce this by introducing timeouts at client side.

Any idea or wrapper code that we can add to clean the buffer usage of MappedByteBuffer to avoid out of memory issues or is there a way we avoid this situation.

**How to reproduce?**
Make client to timeout continuously 
![Jetty1](https://user-images.githubusercontent.com/110129917/216709234-27d70b70-07ca-4661-adf4-ca25ecf84d26.jpg)
![Jetty2](https://user-images.githubusercontent.com/110129917/216709252-e7e72fc7-0948-490b-89c1-925f43685591.jpg)

**Comment by joakime** [comment]
Jetty 9.4.x is now at End of Community Support.

* #7958

Does this happen with Jetty 10 or Jetty 11?

**Comment by joakime** [comment]
Your version of Jetty, 9.4.28.v20200408, is subject to many security vulnerabilities and you should not be using it production or on the public internet.

See: https://www.eclipse.org/jetty/security_reports.php

[As mentioned last time](https://github.com/eclipse/jetty.project/issues/8349#issuecomment-1197324046), you need to upgrade.

Incidentally, your version of Ubuntu, 18.04.6 LTS (Bionic Beaver), also goes End of Support in 2 months (April 2023)

**Comment by joakime** [comment]
There have been numerous ByteBufferPool improvements and bug fixes in Jetty that you do not have due to your old version of Jetty.

The ByteBufferPool saw numerous improvements around Jetty 9.4.45 (starting with PR #7203), and continued to see more improvements all the way through 9.4.50.

This is a small example of why we tell you that you need to upgrade.

**Comment by dhaboda** [comment]
Thanks joakime for the inputs, yesterday we tried quickly using 9.4.50.v20221201 and seen same issue of old gen not released. Let me try again and let you know

**Comment by sbordet** [comment]
> when server responds back with "Max Frame Size as 1MB ..."

That is quite large, considering the default is 16 KiB.
What server does that?

> HttpClient allocates the MappedByteBuffer pool per connection is created with 100*1MB=100MB buffer size of max. Say for example if you have 15 connections that will be roughly 1.5GB

Jetty's `HttpClient` does not do this.
Did you actually see the above, or you are making (wrong) assumptions?

> we observed memory leak in Jetty class MappedByteBufferPool

There are no leaks, it is a pool and it is _designed_ to keep objects around.
The pool is configured by default with 100 slots per bucket, and likely you are sending or receiving data larger than 1 MiB, so the slots get used.
Your images shows exactly that all the 100 slots for capacity 1 MiB are used, so the pool retains 100 MiB.
This is normal and expected, there is no bug and no leak, this is how it is supposed to work.

If you want to consume less memory, configure `MappedByteBufferPool.maxHeapMemory`.

**Comment by dhaboda** [comment]
Hi Joakime,
  Even with 9.4.50 and latest version the behavior is same.. as per above Simone response it is not actually any bug in jetty rather the way it is used the heap memory taking input as Max Frame Size from Server. So I'was initially checking if there is anyway we can avoid this by writing any wrapper around Jetty.

Hi Simone,
  When we see the server implementation, they are using Golang and it seems the default settings of Max Frame Size in go seems 1MB (transport.go class) and it was not set intentionally.

How can we set the maxHeapMemory? can you please provide this and I'll try and see. 

One doubt If we set this to reduce heap from 100 to 50MB max then this will reduce my streams from 100 threads to 50?
bcoz max threads /2 ie., 200/2=100 we got max Size, if we reduced maxHeap to 50mb then only 50 Threads/streams I'll be able to send in a connection? this will reduce the outgoing requests in a rainy day scenario right? is there a way I can reduce the buffer size of 1MB to 256KB and then still able to process 100 requests?
HttpClient.doStart(){
        if (byteBufferPool == null)
            setByteBufferPool(new MappedByteBufferPool(2048,
                executor instanceof ThreadPool.SizedThreadPool
                    ? ((ThreadPool.SizedThreadPool)executor).getMaxThreads() / 2
                    : ProcessorUtils.availableProcessors() * 2));
}


Appreciate you help.
thanks
DJ

**Comment by sbordet** [comment]
> One doubt If we set this to reduce heap from 100 to 50MB max then this will reduce my streams from 100 threads to 50?

No, there is no correlation between the two because Jetty does not use a thread-per-request model.

> How can we set the maxHeapMemory? can you please provide this and I'll try and see.

Look at the javadocs:
https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/io/MappedByteBufferPool.html#%3Cinit%3E(int,int,long,long,long,long)

**Comment by dhaboda** [comment]
Hi Simone, thanks for the response, yesterday we tried reducing the max heap memory of MappedByteBufferPool and that limits the max buffer allocation. 
But my question above was, with 1mb of frame size request from server with 100 as max size the buffer grows to 100mb right? that means max 100 concurrent streams can serve the traffic in this 100 mb buffer,, by reducing the heap memory to 50mb, will this limits my concurrent max streams to only 50 http connections towards that peer? in case if my traffic is more than 50 then what happens? 

And what we noticed another thing is, one server is sending 1MB frame size and another server is sending 16mb as max frame size.. 16*100=1600mb (1.6gb), it is hard to come up with memory allocation for each server type. Why server really needs to advertise the max frame size for client? is this expected server to send the max frame size in http settings when connection is established? what kinda of servers really wants clients to have such a huge size of buffer for their streaming? 

Also original issue was network timeouts happened long time back, even after more than a day any idea why the buffer never cleared? once the http message is timed out then this buffer should have called release on ByteBufferPool bucket?
It seems that is not happen, we also tried with latest version simply by timing out the messages and seen increase of old gen space and in heapdump and the memory never reclaimed even after stopping the traffic completely.

Basically on network timeouts it seems the buffer is not cleared. This seems very simple to repro the problem and how rest of the world using jetty not facing this memory issue? just wondering what would be the idle solution in this situation.

thanks in advance
DJ

**Comment by dhaboda** [comment]
Hi Simone, 
  I tried allocating the heap size in MappedByteBufferPool and below is the observervation.
The max frame size from server is 1MB in both the cases. (they are not setting this 1mb manually it is the default value in golang rest api)

1>  When I set 10mb heap size in MappedByteBufferPool then the retained heap size in heapdump per stream/connection it is showing 10.02mb allocated and able to server more than 1k traffic and no impact in traffic

2> Where as when I set heapsize below 1mb like around 0.8mb then in the retained heap size in heapdump I saw MappedByteBufferPool is showing only 16kb allocated and able to server more than 1k traffic and no impact in traffic

How it is works? while acquiring memory if it is having enough memory is it taking from the pool and if not excess is taken from the direct memory in first test case? and in second since it is lesser than frame size it is going to default size of 16kb?

Can you please suggest what is best approach is it good idea to set below the frame size so that that jetty automatically sets the MappedByteBufferPool size as it requires? OR reserver 10mb after 10 requests filled is it taking more memory from direct memory?


thanks
DJ

**Comment by sbordet** [comment]
> The max frame size from server is 1MB in both the cases.

Frame sizes this large are actually not a great idea, and this is what even the specification has to say:

> Responsiveness can be improved by using frames that are smaller than
   the permitted maximum size.  Sending large frames can result in
   delays in sending time-sensitive frames (such as RST_STREAM,
   WINDOW_UPDATE, or PRIORITY), which, if blocked by the transmission of
   a large frame, could affect performance.

If you configure the Jetty buffer pool to pool only buffers that are smaller than 1 MiB, then it will not pool 1 MiB buffers and that's why you see your case 2.
The buffers, if necessary will be created on-the-fly and you will have impacts on garbage collection (more allocation rate).

The best approach depends on what you want to have and what works best for you.
Typically buffer pooling is a win, but with the servers configured with these unnecessary large sizes there is less room for configuring the client. 
It really boils down to how much memory you have, how much more CPU you're willing to burn in GC, etc.
Try different configurations, and see what's best for you.

**Comment by sbordet** [comment]
Closing as answered.
