### ISSUE TITLE
Jetty 10.0.13 jetty-lowresources.xml

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9316]
**Jetty version**
10.0.13
**Java version**
17
**Question**
In Jetty 9..4 we used to have maxConnections property in jetty-lowresources.xml but same is not exist in jetty 10.0.13, can we add this property manually in 10.0.13 and what will be the default value for same.

**Comment by joakime** [comment]
This is part of the `connectionlimit` module now.

``` shell
[joakim@hyperion jetty-home-10.0.13]$ cat modules/connectionlimit.mod 
# DO NOT EDIT - See: https://www.eclipse.org/jetty/documentation/current/startup-modules.html

[description]
Enables a server-wide connection limit.

[tags]
connector

[depend]
server

[xml]
etc/jetty-connectionlimit.xml

[ini-template]

## The limit of connections to apply
#jetty.connectionlimit.maxConnections=1000

## The idle timeout to apply (in milliseconds) when connections are limited
#jetty.connectionlimit.idleTimeout=1000
```

Tip: use `--list-modules` to see what's available out of the box.

``` shell
$ java -jar start.jar --list-modules
```

**Comment by sushikarwasra** [comment]
@joakime i was referring to Set name="maxConnections" Property name="jetty.lowresources.maxConnections" deprecated="lowresources.maxConnections"  in jetty-lowresources.xml of jetty 9.4.22
We used to have jetty-connectionlimit.xml also in 9.4.22 which is available in 10.0.13 also.

**Comment by joakime** [comment]
`LowResourceMonitor.setMaxConnections()` is deprecated in Jetty 9.4.x, and replaced with `ConnectionLimit`.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.50.v20221201/jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java#L133-L138

https://github.com/eclipse/jetty.project/blob/da9a0b30691a45daf90a9f17b5defa2f1434f882/jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java#L133-L138

That method was flagged as deprecated around Jetty 9.4.12, and finally removed in Jetty 10.0.0

**Comment by janbartel** [comment]
Looks like your question has been answered
