### ISSUE TITLE
Embedding jetty in eclipse

### ISSUE THREAD

**Issue by DusterTheFirst** [eclipse/jetty.project#932]
I am trying to run an embedded jetty Webserver through a jar file. When I run the code in eclipse, it runs fine, and I can connect to the Webserver. But when I export it into an Executable jar file, it throws a NoClassDefFound Error.  I don't think anything is wrong with my code, but I think eclipse is just not exporting the jetty server jar file, even though it is in my class path.

I am using eclipse mars2,
Jetty 9.3.11.v20160721
And the problem only occurs when you run the jar file from a Spigot server. 
( it's an executable jar file, not a runnable one)

**Comment by sbordet** [comment]
You said that when you export it throws a `NoClassDefFoundError`. During the export ? Or later when you try to run it ?

How do you run it ?

Can you detail the `MANIFEST.MF` file contents ?

Stack trace details ? What is the class that is not found ?

**Comment by jmcc0nn3ll** [comment]
this doesn't seem like a Jetty bug but more of an issue in whatever eclipse editor function is trying to build out that executable jar

my personal recommendation would be to not rely upon features of an code editor to build software artifacts and instead use a proper build system like maven, gradle or even ant to build your code and produce deliverables, you will end up with a more deterministic outcome
