### ISSUE TITLE
404 handler not working in jetty-12

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9322]
**jetty-12.0.x**

If I deploy the `ee10-demo-jsp` module and start jetty then go to `http://localhost:8080` I get the following page returned:

![Screenshot from 2023-02-07 17-42-13](https://user-images.githubusercontent.com/342406/217168044-d3dee2cf-0e4b-40ff-8044-ef2f53407a3b.png)

It should show the `ee10-demo-jsp` context deployed, and the img should not be broken.

**Comment by janbartel** [comment]
Same as new issue #9398

**Comment by gregw** [comment]
fixed by 3bdd75f682d336be7e5c2187791f348110fec070
