### ISSUE TITLE
Can we make rest call to jetty 10 server using jersey 1.19?

### ISSUE THREAD

**Issue by Naziburjec** [eclipse/jetty.project#9323]
**Jetty version**
Jetty 10.0.12
**Java version**
jdk11
**Question**

what are the possible ways to make call to jetty10 server using jersey 1.19?

**Comment by joakime** [comment]
Jetty 10 is Servlet 4 on namespace `javax.servlet` with a minimum JVM requirement of Java 11.

See: 
 * Question about Java 11 support on Jersey - https://stackoverflow.com/questions/62712219/jersey-1-19-4-on-java-11
 * Jersey Issue Tracker - https://github.com/eclipse-ee4j/jersey/issues/3965#issuecomment-671228927

**Comment by Naziburjec** [comment]
Ok. we used jetty 9.4.14.v20181114 and jersey 1.19, which is working fine. Now, we are upgrading to jetty 10

**Comment by joakime** [comment]
That is a better question to ask the folks at Jersey.

From our point of view, the requirements of Jetty 10 are what I've listed, and there are many links to issues that point out you need to use Jersey 2.31 at least to satisfy those requirements.
Beyond that, you'll need Jersey folks to help you the rest of the way.

**Comment by Naziburjec** [comment]
Thanks @joakime for your comment.
