### ISSUE TITLE
All the requests failed due to "GATEWAY TIMEOUT" post Jetty Client TCP Connection closed due to IDLE timeout 

### ISSUE THREAD

**Issue by techdeba901** [eclipse/jetty.project#9324]
**Jetty version(s)**
11.0.11
**Java version/vendor** `(use: java -version)`
17.0.6
**OS type/version**

**Description**
1. Jetty Client is sending request to the server using TCP connection.
2. A TCP connection established between Jetty HTTP/2 Client & Server
3. Applied iptables rule to drop all the packets destined for the Jetty HTTP/2 Client TCP port
4. After this retransmission attempts were seen from Jetty HTTP/2 Client to Server
5. Then the connection was closed after idle timeout
6. After that if any requests are sending, gateway timeout are coming

 Is there any way to find whether Jetty HTTP/2 client context is not cleared or not?
**How to reproduce?**

**Comment by sbordet** [comment]
Sorry, your description is not clear. What's an "HTTP/2 context"?

Please spend a little time to detail _exactly_ what are you doing, what do you expect and what you get instead.

Otherwise it's not possible to help you.
