### ISSUE TITLE
Jetty 12 - Review POMs to remove OSGi directives for internal packages

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9327]
**Jetty version(s)**
12+

**Description**
There used to be special directives for OSGi in the POMs to include `internal` packages.
This was necessary because `module-info.java` had `export ... to ...` directives, but these are now gone with the work of #9293.

What's left in the POMs for OSGi, if anything, should be removed.

**Comment by janbartel** [comment]
There are some packages that are still called `internal` that are being used outside of the jar in which it is declared. For example:

> Trying to start the bundle org.eclipse.jetty.websocket.core.server that was supposed to be active or resolved.
> org.eclipse.jetty.websocket.core.server failed to start
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.websocket.core.server [69]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.core.internal
>

**Comment by lachlan-roberts** [comment]
As part of #9233 I will remove any export of internal packages from websocket. At that point the  OSGi directives can be removed.

**Comment by gregw** [comment]
This should be fixed by #9356

**Comment by lachlan-roberts** [comment]
I looked at all the `<Export-Package>` tags in the poms and there are no other ones that export internal packages. So I think this can be closed.
