### ISSUE TITLE
What might cause a Servlet listener to be invalid?

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#9340]
**Jetty version**
11.0.12
**Java version**
11
**Question**
What might cause a Servlet listener to be invalid?

The server side uses Servlet AsyncContext to serve the client and adds a listener class.
when the client is disconnected, the server listener cannot be triggered. for example onComplete() and onTimeout()

**Key code**

``` java
AsyncContext asyncContext = (AsyncContext) request.getAttribute(AsyncContext.class.getName());
        if (asyncContext == null) {
            asyncContext = request.startAsync();
            asyncContext.setTimeout(directiveTimeout);
            request.setAttribute(AsyncContext.class.getName(), asyncContext);
            BoundaryUtils.setBoundaryForPerDialog(request);
            asyncContext.addListener(new DirectiveListener(request, response));
}
```

**DirectiveListener.java**

``` java
public class DirectiveListener implements AsyncListener {
    private HttpServletRequest request;
    private HttpServletResponse response;
    private final String requestInfo;

    public DirectiveListener(HttpServletRequest request, HttpServletResponse response) {
        log.info("[DirectiveListener]");
        this.request = request;
        this.response = response;
    }

    @Override
    public void onComplete(AsyncEvent event) {
        log.info("DirectiveListener onComplete {}");
    }
    @Override
    public void onTimeout(AsyncEvent event) {
        log.info("DirectiveListener onTimeout {}", requestInfo, event.getThrowable());
    }

    @Override
    public void onError(AsyncEvent event) {
        
    }

    @Override
    public void onStartAsync(AsyncEvent event) {
       
    }
```

**Comment by sbordet** [comment]
Sorry it's not clear.

> What might cause a Servlet listener to be invalid?

What do you mean by "invalid"?

> when the client is disconnected, the server listener cannot be triggered. for example onComplete() and onTimeout()

I have doubt that this is true.

Method `onComplete()` is triggered by the server-side application calling `AsyncContext.complete()`, so it has nothing to do with the client.
Method `onTimeout()` is triggered by the server-side scheduler, so again has nothing to do with the client.

Please write a test case that shows the problem, and attach the code to this issue, otherwise there is no evidence that backs up what you're saying.

**Comment by xinguangduan** [comment]
@sbordet , thanks for your comment. I will try to write a test case and verify it.

**Comment by sbordet** [comment]
No further comments from OP, closing.
