### ISSUE TITLE
Content-type not being set for .mjs files served by ResourceHandler

### ISSUE THREAD

**Issue by tipsy** [eclipse/jetty.project#9342]
**Jetty version(s)**
11.0.13

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
We're using `org.eclipse.jetty.server.handler.ResourceHandler` to service static files. This generally works great, but it doesn't seem to know about `.mjs` files in particular. It was reported by a user here: https://github.com/javalin/javalin/issues/1820

**How to reproduce?**
Setup a server which uses `org.eclipse.jetty.server.handler.ResourceHandler`, and call `handler.handle(target, baseRequest, httpRequest, httpResponse)` manually. The original reporter created a fully working example repo, although Jetty is wrapped in Javalin in the example: https://github.com/crummy/javalin-static-mime

**Comment by gregw** [comment]
Is the file served, but just without a content-type header? If so, this is just configuration (although we can update our defaults as well).

**Comment by tipsy** [comment]
Yes, the file is served, but the header is blank. This is my test case and failure:

```kotlin
@Test
fun `mjs files have correct content type`() = TestUtil.test(defaultStaticResourceApp) { _, http ->
    val response = http.get("/modular-script.mjs")
    assertThat(response.body).contains("Modular JavaScript works")
    assertThat(response.headers.getFirst(Header.CONTENT_TYPE)).contains(ContentType.JAVASCRIPT)
}
```

```text
Expecting actual:
  ""
to contain:
  "application/javascript" 
```

**Comment by gregw** [comment]
You need to do `resourceHandler.getMimeTypes().addMimeMapping("mjs", "application/javascript")`.

We will do a pull request to add this mapping to the defaults in future releases.

**Comment by gregw** [comment]
Hmmm according to [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) the type should be "text/javascript".  I think this is confirmed by https://www.rfc-editor.org/rfc/rfc9239,  but I've not had time to read in detail.

Can you check you have the mapping right before we add it to the default.

**Comment by tipsy** [comment]
> You need to do resourceHandler.getMimeTypes().addMimeMapping("mjs", "application/javascript").
> We will do a pull request to add this mapping to the defaults in future releases.

Great, thank you !

> Hmmm according to [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) the type should be "text/javascript". I think this is confirmed by https://www.rfc-editor.org/rfc/rfc9239, but I've not had time to read in detail. 
> Can you check you have the mapping right before we add it to the default.

It appears that `"application/javascript"` is the old way of doing it. You're correct, it should be `"text/javascript"` now.

**Comment by gregw** [comment]
OK, because we currently also have the old type for js in our defaults, we are not going to change jetty-9 at all.  Thus if you wish to continue using jetty-9, you will need to configure it as we indicated above.
We will fix jetty-10 and beyond with the current mime-type for both js and mjs

**Comment by tipsy** [comment]
> OK, because we currently also have the old type for js in our defaults, we are not going to change jetty-9 at all. Thus if you wish to continue using jetty-9, you will need to configure it as we indicated above.
> We will fix jetty-10 and beyond with the current mime-type for both js and mjs

Great, thank you for the quick response and fix!
