### ISSUE TITLE
Jetty 9.4.50.v20221201 Depends on jackson-databind 2.13.3 which has known vulnerabilities.

### ISSUE THREAD

**Issue by barrycaceres** [eclipse/jetty.project#9353]
Jetty 9.4.50.v20221201 Depends on jackson-databind 2.13.3 which has known vulnerabilities.

Please release a version `9.4.51` that uses `jackson-databind` version `2.14.2` instead.

See: https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

**Comment by sbordet** [comment]
Jetty only uses Jackson as a `test` dependency -- no need for a release.

**Comment by joakime** [comment]
`jackson-databind` is also present as a transient (non-test) dependency for the various `jetty-infinispan` modules.

* `org.eclipse.jetty:infinispan-common` - via infinispan-client-hotrot -> wildfly-elytron -> wildfly-elytron-jose-util -> jackson-databind
* `org.eclipse.jetty:infinispan-embedded-query` -> via infinispan-query -> hibernate-search-serialization-avro -> avro -> jackson-databind
* `org.eclipse.jetty:infinispan-remote` - via infinispan-common > wildfly-elytron-jose-util -> jackson-databind
* `org.eclipse.jetty:infinispan-remote-query` -> via infinispan-query -> hibernate-search-serialization-avro -> avro -> jackson-databind

These are optional modules that don't actually ship with jetty-home.
As stated, `jackson-databind` is not used by anything in Jetty itself.

This will not trigger a new Jetty 9.x release, as the jetty-infinispan modules, allow for separate upgrade of the infinispan versions (when used properly).
