### ISSUE TITLE
Unconsumed input on POST with redirect tests fail

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9355]
**jetty-12.0.x**

See `ee10` `ConstraintTest.testNonFormPostRedirectHttp10` and `ConstraintTest.testNonFormPostRedirectHttp11`.

These tests are currently `@Disabled`, but when run, they fail:

> [ERROR] Failures: 
> [ERROR]   ConstraintTest.testNonFormPostRedirectHttp10:1114 
> Expected: not a string containing "Connection: keep-alive"
>      but: was "HTTP/1.1 302 Found\r\nServer: Jetty(12.0.0-SNAPSHOT)\r\nDate: Wed, 15 Feb 2023 05:00:39 GMT\r\nSet-Cookie: JSESSIONID=node01800fo0boxcauyc6qlkuezy9n9.node0; Path=/ctx\r\nExpires: Thu, 01 Jan 1970 00:00:00 GMT\r\nLocation: http://localhost/ctx/testLoginPage;jsessionid=node01800fo0boxcauyc6qlkuezy9n9.node0\r\nConnection: keep-alive\r\nContent-Length: 0\r\n\r\n"

and

> [ERROR]   ConstraintTest.testNonFormPostRedirectHttp11:1129 
> Expected: a string containing " 303 See Other"
>      but: was "HTTP/1.1 302 Found
> Server: Jetty(12.0.0-SNAPSHOT)
> Date: Wed, 15 Feb 2023 05:00:39 GMT
> Set-Cookie: JSESSIONID=node01gze4mdl8qtok1j5gj632wf52g10.node0; Path=/ctx
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Location: http://test/ctx/testLoginPage;jsessionid=node01gze4mdl8qtok1j5gj632wf52g10.node0
> Content-Length: 0
> 
> "

**Comment by gregw** [comment]
Fixed with 033de8611b2857bccefb0ff4546fc9fbeb190d5a
