### ISSUE TITLE
SSL reports deprecated setting, but ssl.ini still uses it

### ISSUE THREAD

**Issue by ChrisHuebsch-FLIG** [eclipse/jetty.project#9386]
**Jetty version(s)**
jetty-10.0.13; built: 2022-12-07T20:13:20.134Z

**Java version/vendor** `(use: java -version)`
penjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

**OS type/version**
Windows Server 2019

**Description**
Jetty complains about deprecated setting:
oejx.XmlConfiguration:main: Property 'jetty.sslContext.keyStoreAbsolutePath' is deprecated, use 'jetty.sslContext.keyStorePath' instead

But in the provided sample ssl.ini it is still in use:

`## The KeyStore file path (relative to $JETTY_BASE).`
`# jetty.sslContext.keyStorePath=etc/keystore.p12`
`## The KeyStore absolute file path.`
`# jetty.sslContext.keyStoreAbsolutePath=${jetty.base}/etc/keystore.p12`

**How to reproduce?**
Setup a jetty with ssl and start it.

**Question for the discussion**
Is it possible to use keyStorePath with an absolute filename?
Documentation does not indicate so.

**Comment by joakime** [comment]
> Is it possible to use keyStorePath with an absolute filename?

No, it's not possible to use the `jetty.sslContext.keyStorePath` with an absolute filename.

Use `jetty.sslContext.keyStoreAbsolutePath` instead.

**Comment by ChrisHuebsch-FLIG** [comment]
Then please don't remove that setting and/or remove the deprecation warning.
I have several jettys (jetties?) running in parallel and they share one common cert store.
I would not prefer to have to manage the certificates individually on every instance.

**Comment by sbordet** [comment]
@ChrisHuebsch-FLIG it is definitely possible to use absolute file names for `jetty.sslContext.keyStorePath`, since Jetty 10.0.2 and #6021 and #6022.

I'll update the mod files and the documentation.
