### ISSUE TITLE
Jetty 12: port/move Jetty WebSocket APIs, client and server to jetty-core

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9391]
**Jetty version(s)**
12

**Description**
Would be great if it would be possible to use Jetty WebSocket APIs in applications without the need of Jakarta classes (both Servlet and WebSocket).

Probably the Jetty APIs can be moved, same for the client, but for the server there would be a bit more work to do to make them independent from Jakarta classes.

For example have `WebSocketHandler` instead of `WebSocketFilter`/`WebSocketServlet` to bootstrap WebSocket, and higher level APIs to deal with messages (and not frames).

**Comment by lachlan-roberts** [comment]
The `websocket-jetty-client` does not need any Jakarta classes, neither does `websocket-jetty-common`.

We could remove the Servlet API from `websocket-jetty-server`, but it will break some people who use this because we give access to `HttpServletRequest`/`HttpServletResponse`.

**Comment by joakime** [comment]
@sbordet isn't this complete now?

**Comment by sbordet** [comment]
Yes, fixed by #9469.
