### ISSUE TITLE
HTTP/3 encryption configuration

### ISSUE THREAD

**Issue by mluckam** [eclipse/jetty.project#9397]
**Jetty version**
11.0.13
**Java version**
17.0.5

**Question**
I wanted to get some more information about encryption configuration for HTTP/3.  From what I was able to find, it appears that the server certificate and private key are configured via SslContextFactory.Server key store on the HTTP3ServerConnector.  The private key and certificate of the keystore are passed via the QuicheConfig in [QuicServerConnector.newQuicheConfig()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-server/src/main/java/org/eclipse/jetty/quic/server/QuicServerConnector.java#L211) to [JnaQuicheConnection.buildConfig()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java#L121).  For the server this is translated to the following native Quiche calls:

- load_priv_key_from_pem_file
- load_cert_chain_from_pem_file

What I did not see was how to load trust into the server connection.  The [Quiche documentation](https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_verify_locations_from_file) shows the call load_verify_locations_from_file, but I do not see it implemented.  Is there an alternate way to set this configuration for the server?

For the client, I am unclear on how to set the certificate, private key, or trust.  Setting the SslContextFactory.Client set via http3Client.getClientConnector().setSslContextFactory() does not appear to take effect.  More specifically [ClientQuicConnection.onOpen()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-client/src/main/java/org/eclipse/jetty/quic/client/ClientQuicConnection.java#L80) does not configure certificate, private key, or trust.  Is there an alternate way to set these configurations for the client?

My goal is to be able to set a certificate, private key, and trust for the client and server and prove via test that a trusted connection is accepted and an untrusted connection is rejected.  Here is a [sample project](https://github.com/mluckam/jetty-http3-example
) with unit tests.

**Comment by sbordet** [comment]
The encryption/decryption is handled by Quiche, so Jetty is out of the picture here.

We will gladly forward the TLS configuration to Quiche, if possible, but unless we are missing something Quiche does not support what you ask.

Did you ask already at the Quiche project?

**Comment by mluckam** [comment]
For the server, [QuicServerConnector.newQuicheConfig()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-server/src/main/java/org/eclipse/jetty/quic/server/QuicServerConnector.java#L211) is where the private key and certificate are set.  Could the trust pem also be set here if the Jetty JNA layer implemented the Quiche call [load_verify_locations_from_file](https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_verify_locations_from_file)?

For the client, [ClientQuicConnection.onOpen()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-client/src/main/java/org/eclipse/jetty/quic/client/ClientQuicConnection.java#L80) is similar to the server [QuicServerConnector.newQuicheConfig()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-server/src/main/java/org/eclipse/jetty/quic/server/QuicServerConnector.java#L211).  This is where the QuicheConfig is set by Jetty and then passed to Quiche.  The main difference is that the private key and certificate are not set client side.   Was there a reason these configurations were not set on the client side?

**Comment by sbordet** [comment]
@mluckam thanks for pointing this out, we really need to bind these as you suggest.

If you want to give it a go with a pull request, we'll gladly review.

**Comment by sbordet** [comment]
This was fixed by #9788.
