### ISSUE TITLE
DefaultHandler does not list contexts

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9398]
**Jetty version(s)**
12.0.0.beta0

**Java version/vendor** `(use: java -version)`
17

**OS type/version**
linux

**Description**
After deploying `--add-module=ee10-demo-async-rest,ee9-demo-async-rest,ee8-demo-async-rest` the default handler is not listing these contexts

**How to reproduce?**

Fresh install, deploy those modules, hit root URI.

**Comment by janbartel** [comment]
I think this is the same issue as #9322 .

**Comment by gregw** [comment]
fixed by 3bdd75f682d336be7e5c2187791f348110fec070
