### ISSUE TITLE
Support for Pack200 compressed servlets

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#94]
migrated from Bugzilla [#353817](https://bugs.eclipse.org/bugs/show_bug.cgi?id=353817)
status ASSIGNED severity _enhancement_ in component _server_ for _7.5.x_
Reported in version _7.4.0_ on platform _All_
Assigned to: Project Inbox

On 2011-08-03 15:25:45 -0400, Michael Gorovoy wrote:

> Originally created as http://jira.codehaus.org/browse/JETTY-1384 by Nick Nygaard (jetty@nndata.net)
> 
> Classloader for applet cannot find main class, if any library is pack200 packed (pack.gz) and applet requests server for pack200 files:
> 
> <html>...<applet...>
> <param name="java_arguments" value="-Djnlp.packEnabled=true" />
> </applet></html>
> 
> Even if only a dependency library is packed with pack200, the main class cannot be found.
> 
> Is content encoding correct when client receives packed jars: content-encoding=pack200-gzip?
> 
> The code works in another Java container.

On 2011-09-20 13:43:04 -0400, Joakim Erdfelt wrote:

> Lowering priority

**Comment by joakime** [comment]
This is related to Issue #98 as well

**Comment by sbordet** [comment]
Pack200 is terminally deprecated since Java 11: https://openjdk.java.net/jeps/336.

**Comment by joakime** [comment]
pack200 the command line tool doesn't exist.
pack200 the standard java classlibs still exist, even in Java 13.
eclipse still mandates it (btw)
