### ISSUE TITLE
WebAppProviderTest sometimes fails in CI

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9407]
> java.util.concurrent.TimeoutException
> 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
> 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
> 	at org.eclipse.jetty.server@10.0.14-SNAPSHOT/org.eclipse.jetty.server.Server.doStop(Server.java:490)
> 	at org.eclipse.jetty.util@10.0.14-SNAPSHOT/org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
> 	at org.eclipse.jetty.deploy@10.0.14-SNAPSHOT/org.eclipse.jetty.deploy.test.XmlConfiguredJetty.stop(XmlConfiguredJetty.java:427)
> 	at org.eclipse.jetty.deploy@10.0.14-SNAPSHOT/org.eclipse.jetty.deploy.providers.WebAppProviderTest.teardownEnvironment(WebAppProviderTest.java:96)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
> 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
> 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
> 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)
> 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterEachMethod(TimeoutExtension.java:110)
> 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
> 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
> 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
> 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
> 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:520)
> 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$24(ClassBasedTestDescriptor.java:510)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:243)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:276)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:276)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:275)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:241)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:142)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
> 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
> 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
> 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
> 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
> 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
> 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
> 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
> Standard Error
> Running org.eclipse.jetty.deploy.providers.WebAppProviderTest.testStartupContext()
> Copying Webapp: foo-webapp-1.war -> foo.war
> Copy Webapp: /home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/src/test/resources/webapps/foo-webapp-1.war
>   To Webapp: /home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war
> Destination Exists: true - /home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war
> 2023-02-22 23:46:20.149:INFO :oejs.Server:main: jetty-10.0.14-SNAPSHOT; built: 2023-02-22T23:15:31.527Z; git: 588ab5ed426793ec244ca96809e17da490649c37; jvm 17.0.2+8
> 2023-02-22 23:46:20.150:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/]
> 2023-02-22 23:46:20.156:INFO :oejw.StandardDescriptorProcessor:main: NO JSP Support for /foo, did not find org.eclipse.jetty.jsp.JettyJspServlet
> 2023-02-22 23:46:20.157:INFO :oejss.DefaultSessionIdManager:main: Session workerName=node0
> 2023-02-22 23:46:20.159:INFO :oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@6d229b1c{foo-webapp-1,/foo,jar:file:///home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war!/,AVAILABLE}{/home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war}
> 2023-02-22 23:46:20.164:INFO :oejw.StandardDescriptorProcessor:main: NO JSP Support for /bar, did not find org.eclipse.jetty.jsp.JettyJspServlet
> 2023-02-22 23:46:20.180:INFO :oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2bbb44da{foo-webapp-3,/bar,jar:file:///home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/src/test/resources/webapps/foo-webapp-3.war!/,AVAILABLE}{/home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/src/test/resources/webapps/foo-webapp-3.war}
> 2023-02-22 23:46:20.186:INFO :oejw.StandardDescriptorProcessor:main: NO JSP Support for /bob, did not find org.eclipse.jetty.jsp.JettyJspServlet
> 2023-02-22 23:46:20.188:INFO :oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@70a898b0{foo-webapp-1,/bob,jar:file:///home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war!/,AVAILABLE}{/home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war}
> 2023-02-22 23:46:20.188:INFO :oejs.AbstractConnector:main: Started ServerConnector@17e0933c{HTTP/1.1, (http/1.1)}{0.0.0.0:40213}
> 2023-02-22 23:46:20.188:INFO :oejs.Server:main: Started Server@4fb56bea{STARTING}[10.0.14-SNAPSHOT,sto=10] @25756ms
> Found expected generated directory: /home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/workish/jetty-0_0_0_0-40213-foo_war-_foo-any-3957831634041548958
> 2023-02-22 23:46:20.190:INFO :oejs.Server:main: Stopped Server@4fb56bea{STOPPING}[10.0.14-SNAPSHOT,sto=10]
> 2023-02-22 23:46:20.190:INFO :oejs.Server:main: Shutdown Server@4fb56bea{STOPPING}[10.0.14-SNAPSHOT,sto=10]
> 2023-02-22 23:46:20.200:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@17e0933c{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
> 2023-02-22 23:46:20.201:INFO :oejsh.ContextHandler:main: Stopped o.e.j.w.WebAppContext@70a898b0{foo-webapp-1,/bob,null,STOPPED}{/home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war}
> 2023-02-22 23:46:20.201:INFO :oejsh.ContextHandler:main: Stopped o.e.j.w.WebAppContext@2bbb44da{foo-webapp-3,/bar,null,STOPPED}{/home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/src/test/resources/webapps/foo-webapp-3.war}
> 2023-02-22 23:46:20.202:INFO :oejsh.ContextHandler:main: Stopped o.e.j.w.WebAppContext@6d229b1c{foo-webapp-1,/foo,null,STOPPED}{/home/jenkins/agent/workspace/jetty.project_PR-9406/jetty-deploy/target/tests/oejdp.WebAppProviderTest/testStartupContext--0/webapps/foo.war}

**Comment by janbartel** [comment]
In this case, the `Server.setStopTimeout` has been set to `10 milliseconds`. The default in `jetty.xml` is `5000 milliseconds`, so probably `10` is too short in the CI environment.

**Comment by joakime** [comment]
IMO, that exception should be more clear ...

"java.util.concurrent.TimeoutException: Server Stop Timeout exceeded: 10ms"

**Comment by janbartel** [comment]
> IMO, that exception should be more clear ...
> 
> "java.util.concurrent.TimeoutException: Server Stop Timeout exceeded: 10ms"

However it's the `CompletableFuture` that's throwing the `TimeoutException`, not jetty. We'd have to catch the exception and throw a new exception with that message, which is probably not worth it.

**Comment by janbartel** [comment]
I don't think this failure is happening any more, so I'm closing this issue. Will reopen if it reappears.
