### ISSUE TITLE
Jetty 12 Documentation Html artifact not populated

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#9442]
https://repo1.maven.org/maven2/org/eclipse/jetty/documentation/jetty-documentation/12.0.0.beta0/

The -html classifier artifact is not populated with HTML resulting in the Jetty website links being dead.

**Comment by olamy** [comment]
ok I found the issue. arfff :)
the release script is skipping test using `-DskipTests` BUT the `jetty-documentation` module is skipping html generation if `skipTests` is `true` https://github.com/eclipse/jetty.project/blob/def35351f314cf8fe3f79ffd2c480ce3414d4a8b/documentation/jetty-documentation/pom.xml#L16

The solution is to add `-Dasciidoctor.skip=false` to the release script.

**Comment by olamy** [comment]
fixed by https://github.com/eclipse/jetty.project/commit/3ac49c8d6539c6d831fca8b60796be457cc834e4
