### ISSUE TITLE
Enabling TLS 1.3 on IBM JVM with Jetty HTTP Server

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#9443]
**Jetty version** - 9.4.44

**Java version** - ./java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 8.0.7.20 - pxa6480sr7fp20-20221020_01(SR7 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220929_37824 (JIT enabled, AOT enabled)
OpenJ9   - 02180fe
OMR      - 48fc32a
IBM      - bf759bf)
JCL - 20220922_01 based on Oracle jdk8u351-b10

I am working to enable TLS 1.3 on our HTTP Server Adapters running on Jetty. Is there any guidelines to do that?
I understand we need to invoke the api
factory.setIncludeProtocols(protocols) with the appropriate protocol String array.
Besides that, what are the other considerations ? Like for ciphers, only applicable one for tls 1.3 will work, and anything else?
Thanks

**Comment by sbordet** [comment]
@4devwithgit Jetty 9.4.x is at End of Community Support, see #7958.

Try Jetty 10/11 with Java 11 and you should have TLS 1.3 working out of the box.

**Comment by 4devwithgit** [comment]
Sure @sbordet, we will plan for that. When u say JDK 11, u meant open JDK?

Having said that, for the immediate requirement, we still need to work on the TLS 1.3 with jetty 9.4.44. So you have any guidelines for that which we can refer?

Thanks
Dev

**Comment by joakime** [comment]
Your requirement of an IBM JVM will require you to do a ton of extra work and possibly even some custom coding.
See ...

* #2921
* #1547

We know Jetty works, out of the box, with TLS/1.3 on all OpenJDK variants.
We also know that IBM JVMs insist on not using RFC naming for anything related to SSL/TLS which causes a major headache when attempting to live peacefully on the public internet.

Closing, as this is for an End of Life release.

**Comment by joakime** [comment]
One more thing, whatever configuration you come up with for your IBM JVM will be unique to that IBM JVM.
That configuration cannot be used on a different version IBM JVM, nor can it be used on a non-IBM JVM (such as on any OpenJDK variant)
That configuration will be essentially locked to that specific IBM JVM.
