### ISSUE TITLE
Jetty 12 - Review BOMs

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9467]
**Jetty version(s)**
12+

**Description**
There currently are mistakes in the BOM artifact/pom.xml referencing old artifacts ID that have been moved to eeN.
Also, jetty-bom/ and jetty-core/jetty-bom have the same groupId/artifactId, why do we need both?
Etc.

**Comment by olamy** [comment]
jetty-bom/ looks like a left over and should be removed

**Comment by manan1979** [comment]
hi @sbordet  could you assign me this issue

**Comment by sbordet** [comment]
@manan1979 feel free to provide a PR, and we will review it -- no need to re-assign this issue.

**Comment by joakime** [comment]
Opened PR #9551

**Comment by joakime** [comment]
Merged PR #9551
