### ISSUE TITLE
Jetty 10.0.13 jetty-bytebufferpool.xml

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9470]
**Jetty version**
10.0.13

**Java version**
17
**Question**
In bytebufferpool.xml values for maxHeapMemory is changed.
In jetty 9.4.22 

``` xml
 <Arg type="long"><Property name="jetty.byteBufferPool.maxHeapMemory" default="-1"/></Arg>
```

In jetty 10.0.13

``` xml
        <Arg type="long"><Property name="jetty.byteBufferPool.maxHeapMemory" default="0"/></Arg>
```

What is difference between using 0 and -1, can we use the default value of 10.0.13.

**Comment by joakime** [comment]
Your `${jetty.base}/start.d/bytebufferpool.ini` tells you what that property is for, and what those values mean.
