### ISSUE TITLE
Jetty 10.0.13 http3.mod

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9472]
**Jetty version**
10.0.13
**Java version**
17
**Question**
In jetty we have http3.mod which Enables experimental support for the HTTP/3 protocol.

Is this module enabled by default, if yes is there anyway to disable support for HTTP/3 protocol.

**Comment by joakime** [comment]
Check your configuration to see if you have it enabled.

``` shell
$ cd /path/to/my-jetty-base
$ java -jar /path/to/jetty-home/start.jar --list-config
```
