### ISSUE TITLE
Jetty 10.0.13 jetty-threadpool.xml

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9473]
**Jetty version**
10.0.13
**Java version**
17
**Question**
In jetty-threadpool.xml we have below property

``` xml
 <Set name="useVirtualThreads" property="jetty.threadPool.useVirtualThreads" />
```

What is the use of this property, it was not there in jetty 9.4.22, what will be the implication of this property.

**Comment by joakime** [comment]
This name is not set unless the property has a value.

Your `${jetty.base}/start.d/threadpool.ini` tells you what the property is for.
