### ISSUE TITLE
Jetty Client Request side done on caller thread ? 

### ISSUE THREAD

**Issue by pyraca** [eclipse/jetty.project#9482]
**Jetty version**

9.4.50 ... 11.0.13

**Java version**

Java 11.

**Question**

When sending async requests using Jetty http client why is the caller thread used to perform the client side of the request ? 

```
 /**
     * <p>Sends this request and asynchronously notifies the given listener for response events.</p>
     * <p>This method should be used when the application needs to be notified of the various response events
     * as they happen, or when the application needs to efficiently manage the response content.</p>
     * <p>The listener passed to this method may implement not only {@link Response.CompleteListener}
     * but also other response listener interfaces, and all the events implemented will be notified.
     * This allows application code to write a single listener class to handle all relevant events.</p>
     *
     * @param listener the listener that receives response events
     */
    void send(Response.CompleteListener listener);
```

This is true when a connection has been **established** to an end point. 

On the very **initial** request (the one that establishes a connection) everything is done on the jetty thread(s). But once a connection is open the request part of the http exchange is done on the caller thread.

This maybe OK for GETs and simple requests, but when the client actually sends data (say pretty large data) the caller thread is "stuck" doing this super slow I/O.  

Is there some setting someplace that fixes it ? 
Or is this a design choice ?

The **response** is always done on the jetty client threads.

**Comment by sbordet** [comment]
> When sending async requests using Jetty http client why is the caller thread used to perform the client side of the request ?

For performance reasons.

> when the client actually sends data (say pretty large data) the caller thread is "stuck" doing this super slow I/O.

Not sure what you mean by "super slow I/O", but `HttpClient` does not block, so the sender thread is not "stuck" -- on the contrary it is very busy sending data.
If it can send data, it will continue to send data as fast as possible.

The moment the TCP stack reports a TCP congestion so that the send pauses, the sender thread returns.

You do not detail what problems do you have exactly, but the current behavior is so by design.

**Comment by pyraca** [comment]
This is not good for my case. 

An option to have the request side be done on the jetty client threads would be at nice to have. The response is always done on the jetty threads because of the I/O latency or the response latency.

I need the caller thread to be free of I/O. Sort of like nodejs works. 
Or how the http request work in the browser.  I need that thread back for an event loop.

**Comment by joakime** [comment]
You seem to equating Java threading to Javascript threading.
Why?  There's really no comparison.

We use the Jetty HttpClient in our Proxy layer, and it's by far the fastest thing in that layer, easily handling requests routed through it from many hundreds of thousands of clients.

Note that the Jetty HttpClient is actually modeled after web browsers.
Start 1 HttpClient, and use as many threads you want against it, it will handle it.
Stop/Shutdown that HttpClient at the end of your application lifecycle.

You can even opt to use the Reactive HttpClient (built on top of Jetty HttpClient) as well.
See: https://github.com/jetty-project/jetty-reactive-httpclient

**Comment by sbordet** [comment]
> Sort of like nodejs works. Or how the http request work in the browser.

They both work like Jetty's `HttpClient` does.

> This is not good for my case. I need that thread back for an event loop.

You don't explain why.

Do you have benchmarks and measured data that show what is your problem?

**Comment by pyraca** [comment]
Let's assume that I have 60Mb payload to send on a connection that runs at 10MBits/s. So roughly 1Mb/s.

Assuming the Jetty **ContentProvider** or **RequestContentProvider** interfaces are delivering bytes at a rate where there is no TCP congestion this will take a 60 seconds to complete. 

So at this point the caller thread is busy for 60 seconds doing the I/O. Yes ? 

If the above assumption holds, would the browser or nodeJS do this too ? Block the javascript thread while the request side of the request completes ? This seems counter intuitive. 

The reverse situation, where I am downloading a 60M payload, the jetty threads do the I/O, and the caller thread is never stuck.

I was looking for symmetry in operation and whether one has better performance was not necessarily the point. 

The proxy use case seems asymmetric to me because in practice we download a lot more content then we upload (via a content proxy).

I thought I missed something in a configuration but if this is done by design in the Jetty client then I would to look to solve it another way.

Thanks for the replies.

**Comment by sbordet** [comment]
> Let's assume that I have 60Mb payload to send on a connection that runs at 10MBits/s. So roughly 1Mb/s.
Assuming the Jetty ContentProvider or RequestContentProvider interfaces are delivering bytes at a rate where there is no TCP congestion this will take a 60 seconds to complete.
So at this point the caller thread is busy for 60 seconds doing the I/O. Yes ?

No, that is not how it works.
CPU are much faster than the network and will fill up the network buffers almost immediately, so the sender thread returns almost immediately.
We have plenty of tests that can TCP congest the loopback interface, which is waay faster than a normal network, with much less than 60 MiB.

**Comment by joakime** [comment]
Your Jetty HttpClient threading behavior can also be controlled by how you provide the body content to the request. (there is more than one way, and you haven't told us yet what way you are using)

**Comment by sbordet** [comment]
Closing this issue, as the current behavior is so by design, and the behavior wanted by the OP is easily achieved by sending the request through the `HttpClient` `Executor`, like this:

```java
HttpClient httpClient = ...;
Executor executor = httpClient.getExecutor();

Request request = httpClient.newRequest(...);
executor.execute(() -> request.send());
```
