### ISSUE TITLE
HTTP redirect to HTTPS

### ISSUE THREAD

**Issue by yongjinhou** [eclipse/jetty.project#9483]
**Jetty version**
jetty 9
**Java version**
java 8
**Question**
By implement WebServerFactoryCustomizer and extend AbstractConfiguration, I realized HTTP request redirect to HTTPS request. After executing the http request of put, the redirection code is 303, but I expect the redirection code to be 307. Can this be implemented through configuration? If yes, how should it be configured?

**Comment by joakime** [comment]
What version of Jetty?
What version of Java?

**Comment by sbordet** [comment]
@yongjinhou Jetty 11 has a built-in `SecuredRedirectHandler` that performs the redirection from `http` to `https`, and allows to configure the redirect status code.

**Comment by yongjinhou** [comment]
> SecuredRedirectHandler

jetty 9 and java 8.

**Comment by sbordet** [comment]
> jetty 9 and java 8.

Jetty 9 is at end of community support, see #7958.
Please upgrade.
