### ISSUE TITLE
Jetty 12 - Upgrade Infinispan to version 15.x

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9487]
**Jetty version(s)**
Jetty 12

**Java version/vendor** `(use: java -version)`
Java 17

**OS type/version**
All

**Description**
Currently in Jetty 12, Infinispan is on version 11.0.17.Final.
We should upgrade it to 14.0.6.Final

**Comment by janbartel** [comment]
Sure, however it is difficult. They seem to have removed all of the API that we were using instead of using infinispan annotations. Obviously, we can't annotate our generic Session object with infinispan annotations.

**Comment by janbartel** [comment]
Note to self: investigate this doco: https://infinispan.org/docs/stable/titles/query/query.html

**Comment by janbartel** [comment]
I've asked 2 questions on stackoverflow: https://stackoverflow.com/questions/70887340/how-to-do-programmatic-indexing-with-infinispan-13 and https://stackoverflow.com/questions/76606148/how-to-do-programmatic-indexing-on-pojos-with-infinispan

I also opened an issue on Infinispan issue tracker 18 months ago:  https://issues.redhat.com/browse/ISPN-13486

**Comment by olamy** [comment]
Infinispan 15 https://github.com/jetty/jetty.project/pull/11503
because 14 is still javax.transaction dependant.

**Comment by olamy** [comment]
done for 12.0.9
