### ISSUE TITLE
Jetty 12 - Split out weld versions to be ee# specific

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9488]
**Jetty version(s)**
Jetty 12

**Java version/vendor** `(use: java -version)`
Java 17

**OS type/version**
All

**Description**
Currently, in Jetty 12, weld version is environment neutral at version 4.0.3.Final.
This needs to be fixed, as weld is EE version specific.

* Weld 5.x is Servlet 6.0.0 - ee10
* Weld 4.x is Servlet 5.0.0 - ee9
* Weld 3.x is Servlet 4.0.0 - ee8

**Comment by manan1979** [comment]
can you assign me this issue?

**Comment by sbordet** [comment]
@manan1979 no need to re-assign the issue -- if you'd like to open a PR we'll review it.

**Comment by joakime** [comment]
Opened PR #9544

**Comment by joakime** [comment]
Merged #9544 to `jetty-12.0.x`
