### ISSUE TITLE
Embedding Jetty - Chapter 21. Embedding: FileServer example is incomplete

### ISSUE THREAD

**Issue by andlenz** [eclipse/jetty.project#949]
The FileServer example in the jetty documentation "Chapter 21. Embedding" is incomplete. 

The `server.setHandler(handlers);` method call is missing.

see [http://www.eclipse.org/jetty/documentation/current/embedding-jetty.html#_using_handlers](http://www.eclipse.org/jetty/documentation/current/embedding-jetty.html#_using_handlers)

**Comment by jmcc0nn3ll** [comment]
duplicate of #943
