### ISSUE TITLE
jetty-12 tck:  comparison of arquillian and standard servlet 6.0.1 tck test failures

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9493]
Test  com/sun/ts/tests/servlet/pluggability/fragment/URLClient.java.welcomefileTest:
https://jenkins.webtide.net/job/tck/job/servlettck-run-12.0.x-ee10/259/testReport/junit/com_sun_ts_tests_servlet_pluggability_fragment_URLClient/

This test fails because it wants to serve a servlet as a welcomefile instead of a file. To do this in jetty, you need to configure jetty with the `DefaultServlet` `init-param` of `welcomeServlets=exact`. 

Need to change the tck jetty setup to do this.

**Comment by janbartel** [comment]
@olamy I thought we fixed this in the tck tests, but CI is still showing this is broken on the job `servlettck-run-12.0.x-ee10`. Or is that not the right branch I'm looking at?

**Comment by janbartel** [comment]
@olamy I'm very confused, can you help? I can see that the `welcomeServlets exact` is set in the `servlet-tck-run` project both on branch `jetty-12-ee10` and branch `main` here: https://github.com/jetty-project/servlet-tck-run/blob/main/src/test/resources/servlet_spec_fragment_web/webdefault.xml. So it works locally. However, it does not work in CI - why would that be? Which branch is CI using?

Note that I also did a run of the CI job `servlettck-run-12.0.x-ee10` using the build parameter  `TCK_SVLT_JAKARTA_URL=https://download.eclipse.org/jakartaee/servlet/6.0/jakarta-servlet-tck-6.0.1.zip`, as the updated version of the tck is public and it excludes some tests that were failing.

**Comment by olamy** [comment]
Remember there are 2 ways of testing TCK:
- the "official" one using the old TCK technology which takes 1h30m to run (those are https://jenkins.webtide.net/job/tck/job/servlettck-run-12.0.x-ee9/, https://jenkins.webtide.net/job/tck/job/servlettck-run-12.0.x-ee10, https://jenkins.webtide.net/job/tck/job/servlettck-run-jetty-10.0.x/ or https://jenkins.webtide.net/job/tck/job/servlettck-run-jetty-11.0.x/ ) the git repository for this legacy mode is here https://github.com/jetty-project/tck-run)
- the refactor technique which is using a branch no yet merged based on arquilian and makes the TCK running in 20min. The git source repo for this one is here https://github.com/jetty-project/servlet-tck-run. and this run in CI here https://jenkins.webtide.net/job/tck/job/tck-servlet-arquillian-experiment/ (different branch for each eeX)

I have updated the legacy one to use per default 6.0.1 version.
the webdefault looks to be correct (https://github.com/jetty-project/tck-run/blob/master/servlet_spec_fragment_web/webdefault-ee10.xml) but it was maybe due to a bug in the script which should be fixed by https://github.com/jetty-project/tck-run/commit/d1bd92678e55fb8a7af4ef0c59d766e1be72d499 but need to 1h30min now :)

**Comment by janbartel** [comment]
The current state of the tests are:

Tests that fail in the arquillian refactor (ie `tck-servlet-arquillian-experiment`), but not in the standard tck tests (`servlettck-run-12.0.x-ee10`): 
* com.sun.ts.tests.servlet.api.jakarta_servlet_http.cookie.URLClient.setMaxAgePositiveTest
* com.sun.ts.tests.servlet.api.jakarta_servlet_http.readlistener1.URLClient.nioInputTest1
* com.sun.ts.tests.servlet.api.jakarta_servlet_http.readlistener1.URLClient.nioInputTest2
* com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet_http.cookie.URLClient.setMaxAgePositiveTest
* com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet_http.sessioncookieconfig.URLClient.constructortest1
* com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.servletcontext30.URLClient.getEffectiveMajorVersionTest

Tests that fail in both:
* com.sun.ts.tests.servlet.spec.security.clientcert.Client.clientCertTest

We know that `setMaxAgePositiveTest` should be excluded, the same way it is for the standard tck. I'll look into the others.

Can we merge the 6.0.1 tck into the arquillian experiment so that we are testing with the latest?

**Comment by olamy** [comment]
exclusion of com.sun.ts.tests.servlet.api.jakarta_servlet_http.cookie.URLClient.setMaxAgePositiveTest has been removed so this will be part of again with next version 
https://github.com/jakartaee/platform-tck/commit/32e03e6de033e04ed3d64377292f1a69d0e4cf41

**Comment by olamy** [comment]
`com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.servletcontext30.URLClient.getEffectiveMajorVersionTest`
web-fragment file contains 
```
<web-fragment xmlns="https://jakarta.ee/xml/ns/jakartaee"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
              https://jakarta.ee/xml/ns/jakartaee/web-fragment_5_0.xsd"
              version="5.0">
```
The test expect `context.getEffectiveMajorVersion()` to return `5.0` but we return `6.0` because it's a constant in the code.

**Comment by olamy** [comment]
I will look at `com.sun.ts.tests.servlet.spec.security.clientcert.Client.clientCertTest`

**Comment by janbartel** [comment]
@olamy if you look at `com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.servletcontext30.URLClient`, around line 79 where it builds the war on the fly I don't see where it includes a `web.xml`. The header you provided comes from a `web-fragment` and is recorded correctly by jetty at version 5. Jetty is reporting only one other descriptor, which is at version 6, which is I assume is us parsing our `webdefault.xml`. I'm not sure that it's not correct for us to assume version 6 (ie version supported by container) if there is no `web.xml`, and only a `web-fragment.xml`.

**Comment by olamy** [comment]
yes I know this includes only a `META-INF/web-fragment.xml` https://github.com/olamy/jakartaee-tck/blob/0c7cf699487319688d7fdddf9d3648254bf975e1/servlet/src/main/java/com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet/servletcontext30/URLClient.java#L77 which is https://github.com/olamy/jakartaee-tck/blob/servlet-module-atleast/servlet/src/main/java/com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet/servletcontext30/servlet_plu_servletcontext30_web-fragment.xml
from a user perspective I would say it would make sense as the only descriptor provided tell which version. 
but not sure about the specs regarding this case.

**Comment by janbartel** [comment]
If there is no web.xml I'm not sure you are allowed to have a web-fragment. I'll consult the specs.

**Comment by janbartel** [comment]
@olamy I can see the problem. If you look in the `jakarta-servlet-tck-6.0.1.jar` at the test, you can see that the `build.xml` includes the `web.xml` file in the war:

>         <jar destfile="${ts.home}/dist/${pkg.dir}/${app.name}_web.war">
>             <zipfileset dir="${ts.home}/dist/${pkg.dir}"
>                         includes="${app.name}.jar"
>                         prefix="WEB-INF/lib"/>
>             <zipfileset dir="${ts.home}/src/${pkg.dir}"
>                         includes="web.xml"
>                         fullpath="WEB-INF/web.xml"/>
>         </jar>

However, the arquillian test when it builds the war in code leaves out the `web.xml`:

>     return ShrinkWrap.create(WebArchive.class, "servlet_plu_servletcontext30.war")
>             .addAsLibraries(CommonServlets.getCommonServletsArchive())
>             .addClasses(AddFilterClass.class, AddFilterNotFound.class, AddFilterString.class, AddSCAttributeListenerClass.class,
>                     AddSCAttributeListenerString.class, AddSCListenerClass.class, AddSCListenerString.class, AddServletClass.class,
>                     AddServletNotFound.class, AddServletString.class, AddSRAttributeListenerClass.class, AddSRAttributeListenerString.class,
>                     AddSRListenerClass.class, AddSRListenerString.class, BadFilter.class, BadListener.class, BadServlet.class,
>                     CreateFilter.class, CreateSCAttributeListener.class, CreateSCListener.class, CreateServlet.class, CreateSRAttributeListener.class,
>                     CreateSRListener.class, DuplicateFilterClass.class, DuplicateFilterString.class, DuplicateServletClass.class, DuplicateServletString.class,
>                     FilterTestServlet.class, TestListener.class, TestServlet.class)
>             .addAsLibraries(javaArchive);

This explains why it fails in the arquillian test but not in the real servlet 6.0.1 test - are you able to fix the arquillian test?

**Comment by janbartel** [comment]
@olamy for `com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet_http.sessioncookieconfig.URLClient.constructortest1` this fails in arquillian and not in the official 6.0.1 test because the arquillian version is not setting the context root of the context correctly. It is missing the following, taken from the official 6.0.1 class:

>     setContextRoot("/servlet_pluh_sessioncookieconfig_web");

It might also be a problem that it is missing this line too, but I'm not sure:

>     setServletName("TestServlet");

**Comment by janbartel** [comment]
@olamy for the arquillian tests `com.sun.ts.tests.servlet.api.jakarta_servlet_http.readlistener1.URLClient.nioInputTest1` and `com.sun.ts.tests.servlet.api.jakarta_servlet_http.readlistener1.URLClient.nioInputTest2` the context root is not set correctly. The test deploys a war called `readlistener1.war` so `/readlistener1` is the context path, but the test itself is using a different context path. 

The official servlet 6.0.1 test has:

>    setContextRoot("/servlet_jsh_readlistener1_web");

and builds a war called:

> servlet_jsh_readlistener1.war

but the arquillian test does not set the context root explicitly and defaults to some wrong value.

**Comment by olamy** [comment]
@janbartel good catch!! 
fixed https://github.com/olamy/jakartaee-tck/commit/70fd95e4d843850b8af3ed4bc89d7fcc41ff7198
but still failing and looks to be another (real?) issue.

clientCert issue fixed with this PR https://github.com/eclipse/jetty.project/pull/9513

**Comment by janbartel** [comment]
@olamy I see that there are still a similar set of test failures in arquillian that aren't failing in the main servlet tests, namely:

> com.sun.ts.tests.servlet.spec.security.clientcert.Client.clientCertTest
> com.sun.ts.tests.servlet.spec.security.clientcertanno.Client.clientCertTest
> com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet_http.cookie.URLClient.setMaxAgePositiveTest
> com.sun.ts.tests.servlet.api.jakarta_servlet_http.cookie.URLClient.setMaxAgePositiveTest
> com.sun.ts.tests.servlet.api.jakarta_servlet_http.readlistener1.URLClient.nioInputTest1
> com.sun.ts.tests.servlet.api.jakarta_servlet_http.readlistener1.URLClient.nioInputTest2
> com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.servletcontext30.URLClient.getEffectiveMajorVersionTest
> com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet_http.sessioncookieconfig.URLClient.constructortest1

Were all of the previous errors I posted in this issue addressed? What else do we need to do to fix these 8 tests in arquillian?

**Comment by olamy** [comment]
few have been fixed for weeks now.
clientCert with https://github.com/eclipse/jetty.project/pull/9533
my comment here https://github.com/eclipse/jetty.project/issues/9493#issuecomment-1472942059
there is only 5 discrepancies now.
BUT as explained in this comment (https://github.com/eclipse/jetty.project/issues/9493#issuecomment-1471285068) the 3 cookie tests are not excluded anymore (so will be part of TCK 6.0.2 or we have to challenge them).
I will look at nio. I thought I fixed them but not.

**Comment by olamy** [comment]
both nioInput tests fixed by https://github.com/olamy/jakartaee-tck/commit/efc90354ee5605ef5d07080dd7c3f96a7a6db8bb

**Comment by olamy** [comment]
so we have a discrepancy of 3 which looks due to cookie test and the servlet version explained here https://github.com/eclipse/jetty.project/issues/9493#issuecomment-1471292955

**Comment by janbartel** [comment]
@olamy you didn't see my comment about the servlet version explained here: https://github.com/eclipse/jetty.project/issues/9493#issuecomment-1472210857

**Comment by olamy** [comment]
> com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.servletcontext30

arghhh my bad!!
this looks to turn into a IssueWithTooManyCommentsException :) 
fixed by https://github.com/olamy/jakartaee-tck/commit/54621f2958b8590661737d1cf4e578243210f76b

**Comment by gregw** [comment]
@olamy can you close this?

**Comment by olamy** [comment]
yes we have other issues covering TCK
