### ISSUE TITLE
jetty client with proxy - ssl traffic between both proxy and servers

### ISSUE THREAD

**Issue by Michal-Cho** [eclipse/jetty.project#9495]
Jetty version
9.4.44.v20210927
Java version
java version "11.0.3" 2019-04-16 LTS
Question
Hello!
I know that our jetty version is out of support but I hope for some directions/hints that could push me in the right direction.
In our project we need to use jetty client with proxy that requires SSL, same as final destinations servers. We store needed certificates in keystore, both for proxy and dest servers

What I have figured out so far is that I need to create a ```ProxyConfiguration.Proxy``` object (using constructor with ```SslContextFactory.Client```) and add it to client's ProxyConfiguration collections. It is the same ```SslContextFactory.Client```  that is used in the client and it is working fine if we skip a proxy and run traffic client<--> server directly.

I can see in wireshark the following

- once a client needs to send a request it contacts a proxy
- TLS handshake is successful - seems to be correct
- I can see ```tunnelSucceeded``` method from ```HttpProxy``` class being called successfully  what I understood is a sign that the traffic should go via proxy
- (here comes the failing part) I would assume that the proxy server should then try to establish connection to the final destination server using certificates that it could get from the client. But that does not work - we get Broken pipe exception as the traffic between the proxy and a server is just few TCP frames.

If we run similar request from a simple python code:
```
#!/usr/bin/python3

import requests

url = 'https://our.server.net:30820/something' # SSL
PROXY = {'http': 'https://hej:hopp@localhost:8443', 'https': 'https://hej:hopp@localhost:8443'}
AUTH = ('user', 'myPassword')
KEY = '/Users/user/Downloads/both.pem'
verify = requests.get(url,
                      auth=AUTH,
                      proxies=PROXY,
                      verify=KEY)
print(verify.text, verify.status_code)
```
we get correct response.
Proxy does not require authentication for now.
My question here is - have I understood the flow correctly and I should try focus on our proxy server that maybe configured? What confuses me is that it works with the pyton script.

I will be really grateful for any hints/advice where I could find more information about setup described above

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support

* #7958

You should be using Jetty 10, or Jetty 11, or Jetty 12 at this point in time.
Please try again with a newer, supported, version of Jetty.

**Comment by sbordet** [comment]
Upgrade to Jetty 10+ and give us more information about the failure if it still happens.
We have tests that run exactly the scenario you depict (and even more complicated ones) and they run without issues.

**Comment by Michal-Cho** [comment]
sure, I will close this ticket and create a new one with jetty 11 :)
