### ISSUE TITLE
Maven plugin add support for jar projects in `:effective-web-xml`

### ISSUE THREAD

**Issue by mvysny** [eclipse/jetty.project#9497]
I'm building an app as a simple jar project, with embedded Jetty included as a dependency. I've found out that Jetty supports the quickstart mode, thus vastly speeding up boot time (and possibly even enabling native mode with GraalVM).

Unfortunately, `mvn jetty:effective-web-xml` fails with `Packaging type [jar] is unsupported` which leads me to believe that only the WAR-type projects are supported at the moment.

However, the jar-type project has a classpath very similar to the war-type project, and so this ticket could perhaps be fixed simply by removing the limitation in the Jetty Maven Plugin.

Thanks again for your great work :)

I'm using Jetty 11.0.14.

**Comment by janbartel** [comment]
@mvysny can you link to an example maven project?

**Comment by mvysny** [comment]
@janbartel thank you for your reply, please try out https://github.com/mvysny/vaadin-boot-example-maven . Requires JDK 17+. There's `Main.java` which you can simply run.

**Comment by janbartel** [comment]
@mvysny and you tried setting the `supportedPackagings` configuration param for the plugin to include `jar`? See https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#common-configuration

**Comment by mvysny** [comment]
@janbartel thank you, I haven't realized that there's such a configuration parameter. Adding the parameter indeed helped, thank you :)

For future reference, this is what helped:
```xml
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>11.0.14</version>
                <configuration>
                    <supportedPackagings><packaging>jar</packaging></supportedPackagings>
                </configuration>
            </plugin>
```

**Comment by mvysny** [comment]
Unfortunately, the plugin fails with:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getName(int)" because "path" is null
    at org.eclipse.jetty.maven.plugin.JettyEffectiveWebXml.configureWebApp (JettyEffectiveWebXml.java:66)
    at org.eclipse.jetty.maven.plugin.AbstractWebAppMojo.startJetty (AbstractWebAppMojo.java:430)
    at org.eclipse.jetty.maven.plugin.AbstractWebAppMojo.execute (AbstractWebAppMojo.java:419)
```

Indeed, `path` is null since `war` is most probably null since we're not having a war app: https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyEffectiveWebXml.java#L66

**Comment by janbartel** [comment]
@mvysny try using the branch in this PR #9503. It should fix your problem. If not, post the config in the pom.xml that you're using so I have a better test case.
