### ISSUE TITLE
Evaluate if Request recycling is still valid?

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#95]
migrated from Bugzilla [#370088](https://bugs.eclipse.org/bugs/show_bug.cgi?id=370088)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _8.1.0_ on platform _All_
Assigned to: Project Inbox

On 2012-01-30 01:23:59 -0500, Greg Wilkins wrote:

> Currently jetty keeps request/response objects associated with a connection and reuses them for each request received.
> 
> With modern garbage collectors, this may not be an ideal strategy, as it may encourage request/response object (and their associated objects) to migrate into old generation, since the lifetime of a connection is often be many minutes. 
> 
> It may be better to simply recreate new request/response objects for each request. This would free memory while the connection is idle and reduce the chances of those objects ending up in old gen.
> 
> Note that Async Servlets and techniques like long polling will fight against this, as they increase the lifespan of request objects.  However protocols like websocket may make long polling less utilised.
> 
> Another problem with recycling request/responses/continuations/AsyncContexts, is that it makes it harder to detect programming errors in asynchronous code, which wrongly holds onto a reference beyond the objects lifecycle.
> 
> We need to evaluate if recycling is still a net benefit.

On 2012-01-31 04:16:26 -0500, Simone Bordet wrote:

> In addition to the comment above, we need to investigate if recycling of data contained in the request object is effective.
> 
> The HTTP headers name/values will sum up for a large amount of memory occupied by each request, so using interned strings for those may be more effective than recycling the request object that wraps them.

On 2013-01-24 19:57:03 -0500, Greg Wilkins wrote:

> Evaluations in Jetty-9 have show

**Comment by joakime** [comment]
The lifespan of a Request object, and its values, are still kind of undefined.
We encourage folks to copy out what they need and assume that the Request and/or HttpSession (see Issue #136) will become invalid/recycled.

Do we need this issue anymore?

**Comment by gregw** [comment]
Yes let's keep this.    Currently there is a lot of mechanisms used to recycle the request object, which need to be evaluated if they are still necessary.  If the HttpChannel/Request/Response were one time objects, then the simplifications obtained might outweigh the benefits of object recycling.

This is something we should revalidate as the optimization is now very old.

**Comment by joakime** [comment]
@gregw it's been 2 years, and lots of performance testing, I think we can close this.
If it should prove to be a specific issue we can always create a new issue to address that specific case.
