### ISSUE TITLE
supported cipher suites

### ISSUE THREAD

**Issue by selva3k** [eclipse/jetty.project#9500]
**Jetty version**
Jetty 9.4.46

**Java version**
Java 1.8

**Question**
where can i get the supported cipher suites for the above(jetty 9.4.46 & java 1.8).  This is to add in the "IncludeCipherSuites" section in the jetty configuration.

**Comment by sbordet** [comment]
Jetty 9.4.x is at End of Community Support.

* #7958

Consult the JDK version you are using for the list of supported ciphers.
