### ISSUE TITLE
There are no module libraries in the class-path for logging-log4j2

### ISSUE THREAD

**Issue by izemlyanskiy** [eclipse/jetty.project#9505]
**Jetty version**
10.0.14

**Java version**
```
java -version 
openjdk version "11.0.17" 2022-10-18 LTS
```

**Question**
Hello, I try to migrate to jetty 10.x my old project and I find an unexpected for me behavior 

what I did on my linux (I guess it might be any linux version) box: 
```bash
$ wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/10.0.14/jetty-home-10.0.14.tar.gz
$ tar -xzvf jetty-home-10.0.14.tar.gz
$ mkdir test
$ java -jar ../start.jar -Dlog4j2.version=2.20.0 --add-module=logging-log4j2         --approve-all-licenses
```

after the last command I've got a file tree in the current folder like: 
```
find 
.
./resources
./resources/log4j2.xml
./lib
./lib/logging
./lib/logging/log4j-api-2.20.0.jar
./lib/logging/log4j-core-2.20.0.jar
./lib/logging/log4j-slf4j2-impl-2.20.0.jar
./start.d
./start.d/logging-log4j2.ini
```

so far so good. 

But then I want to double-check how would my jetty run with these settings. I run 
```bash 
java -jar ../start.jar --dry-run 
```
and I got a result output: 
```
/home/ivan/.sdkman/candidates/java/11.0.17-librca/bin/java -Djava.io.tmpdir=/tmp -Djetty.home=/tmp/test/jetty-home-10.0.14 -Djetty.base=/tmp/test/jetty-home-10.0.14/test --class-path /tmp/test/jetty-home-10.0.14/test/resources:/tmp/test/jetty-home-10.0.14/lib/logging/slf4j-api-2.0.5.jar org.eclipse.jetty.xml.XmlConfiguration java.version=11.0.17 java.version.major=11 java.version.micro=17 java.version.minor=0 java.version.platform=11 jetty.base=/tmp/test/jetty-home-10.0.14/test jetty.base.uri=file:///tmp/test/jetty-home-10.0.14/test jetty.home=/tmp/test/jetty-home-10.0.14 jetty.home.uri=file:///tmp/test/jetty-home-10.0.14 jetty.webapp.addServerClasses=org.apache.logging.log4j.,org.slf4j. log4j2.version=2.19.0 runtime.feature.alpn=true slf4j.version=2.0.5
```

And here is my question: 
1. First of all why did jetty ignore my parameter `-Dlog4j2.version=2.20.0` and runs it with `log4j2.version=2.19.0`? 
2. But that's kinda "fine". The most important question is why didn't the execute line doesn't contain in classpath the libraries from the module `logging-log4j2`? According to the module description there are 3 libraries in the module https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-home/src/main/resources/modules/logging-log4j2.mod#L25-L27 
and we did download them to the `./lib/logging` folder. 

Correct me if I'm wrong, but I would expect seeing in the exec line something like
```
java <...> --class-path <...>:./lib/logging/log4j-api-2.20.0.jar:./lib/logging/log4j-core-2.20.0.jar:./lib/logging/log4j-slf4j2-impl-2.20.0.jar <...>
```
At least this is what usually happens to the other modules. 

Thank you in advance!

**Comment by olamy** [comment]
can you try using
```
java -jar ../start.jar -Dlog4j2.version=2.20.0 --dry-run
```

the version `2.19.0` is per default in the mod file so you should override it for every commands

Jetty has his own classloader mechanism so do no expect to see many jars in --class-path

**Comment by joakime** [comment]
> ```
> java -jar ../start.jar -Dlog4j2.version=2.20.0 --add-module=logging-log4j2         --approve-all-licenses
> ```

This command did a few things ...
* Created a `${jetty.base}/start.d/logging-log4j2.ini` with a line `--module=logging-log4j2` and the `[ini-template]` section from [the `logging-log4j2.mod` module](https://github.com/eclipse/jetty.project/blob/jetty-10.0.14/jetty-home/src/main/resources/modules/logging-log4j2.mod) (of which there is none).
* Used property `log4j.version=2.20.0` to ensure that the `[files]` section of [the `logging-log4j2.mod` module](https://github.com/eclipse/jetty.project/blob/jetty-10.0.14/jetty-home/src/main/resources/modules/logging-log4j2.mod) is satisfied.

The end result is a `${jetty.base}/start.d/logging-log4j2.ini` that enables the module `logging-log4j2` with no version change, and library files for version 2.20.0 in `${jetty.base}/lib/logging/`

When you run Jetty with the command line ...

> ```
> java -jar ../start.jar --dry-run
> ```

There's no property `log4j2.version=2.20.0` any more, it isn't configured.

Example:
```
[joakim@hyperion log4j2-base]$ tree lib
lib
└── logging
    ├── log4j-api-2.20.0.jar
    ├── log4j-core-2.20.0.jar
    └── log4j-slf4j2-impl-2.20.0.jar

1 directory, 3 files
[joakim@hyperion log4j2-base]$ cat start.d/logging-log4j2.ini 
# --------------------------------------- 
# Module: logging-log4j2
# Configures Jetty logging to use log4j version 2.
# SLF4J is used as the core logging mechanism.
# --------------------------------------- 
--module=logging-log4j2


[joakim@hyperion log4j2-base]$ java -jar ../../jetty-home-10.0.14/start.jar --list-classpath

Jetty Server Classpath:
-----------------------
Version Information on 2 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                    2.0.5 | ${jetty.home}/lib/logging/slf4j-api-2.0.5.jar
```

That's a broken configuration btw.

You can even run `start.jar --list-config` and see the `Properties` section still refers to `log4j2.version=2.19.0`

```
[joakim@hyperion log4j2-base]$ java -jar ../../jetty-home-10.0.14/start.jar --list-config
...(snip)...
Properties:
-----------
 java.version = 17.0.6
 jetty.webapp.addServerClasses = org.apache.logging.log4j.,org.slf4j.
 log4j2.version = 2.19.0
...(snip)...
```

Lets tell Jetty to create any files identified by the various enabled modules `[files]` sections

```
[joakim@hyperion log4j2-base]$ java -jar ../../jetty-home-10.0.14/start.jar --create-files
INFO  : copy /home/joakim/.m2/repository/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar to ${jetty.base}/lib/logging/log4j-slf4j2-impl-2.19.0.jar
INFO  : copy /home/joakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar to ${jetty.base}/lib/logging/log4j-api-2.19.0.jar
INFO  : copy /home/joakim/.m2/repository/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar to ${jetty.base}/lib/logging/log4j-core-2.19.0.jar
INFO  : Base directory was modified
[joakim@hyperion log4j2-base]$ java -jar ../../jetty-home-10.0.14/start.jar --list-classpath

Jetty Server Classpath:
-----------------------
Version Information on 5 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                    2.0.5 | ${jetty.home}/lib/logging/slf4j-api-2.0.5.jar
 2:                   2.19.0 | ${jetty.base}/lib/logging/log4j-slf4j2-impl-2.19.0.jar
 3:                   2.19.0 | ${jetty.base}/lib/logging/log4j-api-2.19.0.jar
 4:                   2.19.0 | ${jetty.base}/lib/logging/log4j-core-2.19.0.jar
```

So how do we fix this?

We add `log4j2.version=2.20.0` to the `${jetty.base}/start.d/logging-log4j2.ini` file (don't use `-D`, just a simple key=value is enough)

Example:
```
[joakim@hyperion log4j2-base]$ cat start.d/logging-log4j2.ini 
# --------------------------------------- 
# Module: logging-log4j2
# Configures Jetty logging to use log4j version 2.
# SLF4J is used as the core logging mechanism.
# --------------------------------------- 
log4j2.version=2.20.0
--module=logging-log4j2


[joakim@hyperion log4j2-base]$ java -jar ../../jetty-home-10.0.14/start.jar --list-classpath

Jetty Server Classpath:
-----------------------
Version Information on 5 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                    2.0.5 | ${jetty.home}/lib/logging/slf4j-api-2.0.5.jar
 2:                   2.20.0 | ${jetty.base}/lib/logging/log4j-slf4j2-impl-2.20.0.jar
 3:                   2.20.0 | ${jetty.base}/lib/logging/log4j-api-2.20.0.jar
 4:                   2.20.0 | ${jetty.base}/lib/logging/log4j-core-2.20.0.jar
```

**Comment by izemlyanskiy** [comment]
Wow! Thank you so much for these answers! 
It was extremely useful. I was under an impression if I generate files for `start.d` and specify a property it will appear in the generated files as well. 
Now I see it's not the case and never be. 

Thank you once again, folks!  @joakime , you're awesome :heart:

**Comment by joakime** [comment]
Your welcome, good luck.
Please close the issue if you feel the question was answered.

**Comment by izemlyanskiy** [comment]
oh, right! sorry, pushed a wrong button. 
thank you once again!
