### ISSUE TITLE
If 'If-None-Match' value ends with '--gzip', Jetty always sends back: 304 - Not Modified

### ISSUE THREAD

**Issue by piotrjanik** [eclipse/jetty.project#952]
Check this line:
https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java#L770

```java
if (etag.equals(ifnm) || ifnm.endsWith(ETAG_GZIP_QUOTE) && ifnm.indexOf(',')<0 && etag.equals(removeGzipFromETag(etag)))
```
`removeGzipFromETag` - removes `--gzip` suffix from etag, so it must return true.
Looks like a typo.

Shouldn't there be `etag.equals(removeGzipFromETag(ifnm))` at the end of if? :)

PJ

**Comment by jan-swiecki** [comment]
Same problem.
