### ISSUE TITLE
Jetty website is unavailable

### ISSUE THREAD

**Issue by adamretter** [eclipse/jetty.project#9520]
Visiting https://www.eclipse.org/jetty/ redirects to this page: https://www.eclipse.org/projects/archives.php

<img width="1677" alt="Screenshot 2023-03-20 at 18 16 46" src="https://user-images.githubusercontent.com/1264057/226417412-2357b806-41eb-48a6-a4e4-f8e19b35eb86.png">

This is problematic for Jetty config files that have this DocType declaration:
```xml
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
```
as this also redirects now to:  https://www.eclipse.org/projects/archives.php, which breaks XML parsing and validation of the configuration. i.e.:

```
❯ curl -vv https://www.eclipse.org/jetty/configure_10_0.dtd

*   Trying 198.41.30.198:443...
* Connected to www.eclipse.org (198.41.30.198) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=CA; ST=Ontario; L=Ottawa; O=Eclipse.org Foundation, Inc.; CN=*.eclipse.org
*  start date: Nov  9 00:00:00 2022 GMT
*  expire date: Dec 10 23:59:59 2023 GMT
*  subjectAltName: host "www.eclipse.org" matched cert's "*.eclipse.org"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
> GET /jetty/configure_10_0.dtd HTTP/1.1
> Host: www.eclipse.org
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Mon, 20 Mar 2023 17:22:20 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://www.eclipse.org/projects/archives.php
< Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
< Content-Security-Policy: frame-ancestors 'self'
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
<
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by joakime** [comment]
Also reported at https://github.com/eclipse/jetty.project/issues/4841#issuecomment-1476508763

We've reached out the eclipse webmaster to fix this.

**Comment by adamretter** [comment]
@joakime Is it possible to find the `.dtd` files somewhere in the GitHub?
I have not found them yet... I could then download them, and use them locally rather than needing to pull them from the web each time.

**Comment by adamretter** [comment]
@joakime NVM, I found them here - https://github.com/eclipse/jetty.project/tree/jetty-11.0.x/jetty-xml/src/main/resources/org/eclipse/jetty/xml

**Comment by joakime** [comment]
@adamretter if you use jetty-xml and it's XmlConfiguration you don't need the DTDs externally, they are shipped within the jetty-xml jar, and XmlConfiguration references them that way.

**Comment by joakime** [comment]
The most up to date versions are in the jetty-12 codebase.

https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml/catalog-configure.xml

**Comment by adamretter** [comment]
> if you use jetty-xml and it's XmlConfiguration you don't need the DTDs externally, they are shipped within the jetty-xml jar, and XmlConfiguration references them that way.

@joakime We are using XSLT to transform a set of Jetty config files at build time. So we need the DTD's to be available to the XML and XSLT processors. We have now configured an OASIS Catalog for the XML and XSLT processors so that they resolve to the local DTD files.

> The most up to date versions are in the jetty-12 codebase.

@joakime Thanks. We are using Jetty 11, so I guess we should stick with `https://www.eclipse.org/jetty/configure_10_0.dtd`? There does not appear to be an updated one for Jetty 11 (as I understand it Jetty 11 is very close to Jetty 10, just jakarta instead of javax).

**Comment by joakime** [comment]
> > The most up to date versions are in the jetty-12 codebase.
> 
> @joakime Thanks. We are using Jetty 11, so I guess we should stick with `https://www.eclipse.org/jetty/configure_10_0.dtd`? There does not appear to be an updated one for Jetty 11 (as I understand it Jetty 11 is very close to Jetty 10, just jakarta instead of javax).

We started using XML Catalogs in Jetty 12 as well.
Jetty 10 is EE 8 / Servlet 4 on namespace `javax.*` (eg: `javax.servlet.*`)
Jetty 11 is EE 9 / Servlet 5 on namespace `jakarta.*` (eg: `jakarta.servlet.*`)

They are "mostly" the same, but with significant dependency and namespace differences.
The codebases are not identical, there are plenty of EE 9 / Servlet 5 specific behaviors in Jetty 11.
The codebases are similar, and that makes merging from Jetty 10 to Jetty 11 mostly painless.

**Comment by sbordet** [comment]
@adamretter the website is back up. Please reopen if you still have problems.

**Comment by adamretter** [comment]
Thanks very much @joakime and @sbordet
