### ISSUE TITLE
How to use ConstraintMapping.setPathSpec()

### ISSUE THREAD

**Issue by yongjinhou** [eclipse/jetty.project#9523]
**Jetty version**
9.4
**Java version**
java8
**Question**
In org.Eclipse.Jetty.Security.ConstraintMapping, we can through setPathSpec () method sets the path for similar "/api/info" this kind of path, You can directly setPathSpec("/api/info"), I would like to know for paths with path variables such as "/api/<path_variable>/info”, how to call the setPathSpec() function.
Note: I need to specify "/api/<path_variable> /info” path separately, I have tried setPathSpec(/api/*/info) does not work.

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

See:

* https://github.com/eclipse/jetty.project/issues/7958

You should be using Jetty 10 / Jetty 11 / or Jetty 12 at this point in time.

The behaviors of PathSpec and Constraint handling is different in Jetty 10+, also know that ConstraintMapping is hard wired to the Servlet spec in Jetty 10 and Jetty 11, and in Jetty 12 the ConstraintMapping is ee# specific.   The servlet spec does not support url-patterns like you are asking about.  You will be unable to use ConstraintMapping successfully along with alternate PathSpec implementations like URITemplatePathSpec or RegexPathSpec.
