### ISSUE TITLE
InputStreamResponseListener's InputStream creates an exception on close()

### ISSUE THREAD

**Issue by tflobbe** [eclipse/jetty.project#9524]
**Jetty version(s)**
_[Jetty 9.x is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958)_
jetty-10
jetty-11
jetty-12

**Enhancement Description**
It seems like `InputStreamResponseListener#Input` always creates an `AsynchronousCloseException` instance on close(), where in many cases is not even needed. I noticed this takes a relatively high amount of time when running [this Solr test](https://github.com/apache/solr/blob/main/solr/benchmark/src/java/org/apache/solr/bench/search/SimpleSearch.java) with a profiler. Would it make sense to only create such instance in the case of callbacks present? Or am I missing something?

**Comment by joakime** [comment]
This is about the Jetty Client `InputStreamResponseListener` right?

And your concern is only about the creation of an `AsynchronousCloseException` instance, even though it might never be used if `chunkCallbacks` is empty and wouldn't process anything.  Is that it?

**Comment by tflobbe** [comment]
> This is about the Jetty Client InputStreamResponseListener right?

Yes

> And your concern is only about the creation of an AsynchronousCloseException instance, even though it might never be used if chunkCallbacks is empty and wouldn't process anything. Is that it?

Right, yes.

**Comment by lorban** [comment]
@tflobbe you meant [this](https://github.com/eclipse/jetty.project/pull/9805)?

**Comment by tflobbe** [comment]
Exactly, yes. Thanks for fixing @lorban

**Comment by lorban** [comment]
Done in 10, merged all the way to 12.
Note that this wasn't done in [Jetty 9.x as it is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958).
