### ISSUE TITLE
Expose TCP connection establishment information

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9529]
**Jetty version(s)**
10+

**Enhancement Description**
Would be nice to have `HttpClient` (or some other component such as `ClientConnector`) emit events for TCP connection establishment/failure (a begin event, and a success/fail event, for a given `SocketAddress`).

This could be useful to track destination servers that are faulty or take a long time to establish a connection.

**Comment by arsenalzp** [comment]
Hello,
It is me again.
As far as I understand you want to have events emitter/listener for TCP conn established/failed to establish in additional to onOpen/onClose events. Am I right?
How complex do you think this task is? Can I work on it?

**Comment by sbordet** [comment]
@arsenalzp I don't think it's too complex, so you can give it a go.

You can start by finding the place in the code that initiate connection establishment, the place where the connection establishment is complete, and the place where the connection establishment is failed.

Then it's a matter of designing the listener APIs, and then emitting the events.

Let me know if you need guidance, but please one at a time 😄 

Thanks!

**Comment by arsenalzp** [comment]
I guess the right place is in `ClientConnector.ClientSelectorManager` 

```
        public void connectionOpened(Connection connection, Object context)
        {
          ....
        }
```

```
        protected void connectionFailed(SelectableChannel channel, Throwable failure, Object attachment)
        {
         ....
        }
```

A draft implementation is showing `connectionFailed()` method is invoked more than one time, I suppose it is due to try-reconnect behavior. Is it valid to invoke `onConnectionFailed()` listener method more than one time?
Another question - what is listener methods signature, I mean what should be put as argument:

`void onConnectionEstablished(Connection c)`
`void onConnectionFailed(Throwable failure)`

**Comment by sbordet** [comment]
@arsenalzp `connectionFailed()` should not be called multiple times.
Do you have stack traces from where it is called the first time, and the subsequent times?

We want to track connection establishment, so we want an event when the connection is initiated, and one when it is completed (either success or failure).
See `ClientConnector.connect()` as the initiating point.

The API should be lower level, so:

`onConnectBegin(SocketChannel s)`
`onConnectSuccess(SocketChannel s);`
`onConnectFailure(SocketChannel s, Throwable x);`

**Comment by arsenalzp** [comment]
Here is stack trace:

```
//1
java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
org.eclipse.jetty.io.ClientConnector.connectFailed(ClientConnector.java:591)
org.eclipse.jetty.io.ClientConnector$ClientSelectorManager.connectionFailed(ClientConnector.java:646)
org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:970)
org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:368)
org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:684)
org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:539)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:512)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:258)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
java.base/java.lang.Thread.run(Thread.java:833)
//2
java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
org.eclipse.jetty.io.ClientConnector.connectFailed(ClientConnector.java:591)
org.eclipse.jetty.io.ClientConnector$ClientSelectorManager.connectionFailed(ClientConnector.java:646)
org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:970)
org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:368)
org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:684)
org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:539)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:512)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:258)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by arsenalzp** [comment]
Here is code snippet:

```
public static void main(String[] args) {
		ClientConnector connector = new ClientConnector();
		connector.onClientConnection(new ClientConnector.ClientConnectionListener() {

			@Override
			public void onEstablishment() {
				System.out.println("Connection established");
			}

			@Override
			public void onFailure() {
				System.out.println("Connection failed");
			}
		});
		try (HttpClient client = new HttpClient(new HttpClientTransportOverHTTP(connector))) {
			client.start();
			Request req = client.newRequest("http://localhost:888");
			req.onResponseContent(new Response.ContentListener() {
				@Override
				public void onContent(Response response, ByteBuffer content) throws Exception {
					if (response.getStatus() != HttpStatus.OK_200) {
						throw new Exception(response.getReason());
					}
					
					OutputStream out = new BufferedOutputStream(System.out);
					while(content.remaining() != 0) {
						out.write(content.get());
					}
					out.close();
				}
				
			});
			req.send();
			client.stop();
		} catch (Exception e) {
			e.printStackTrace();
		}		
	}
```

**Comment by arsenalzp** [comment]
Here is the stack trace of Throwable error:

```
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:707)
	at arsenal.jetty.httpclient.emit.Solution.main(Solution.java:45)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:358)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:346)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:684)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:539)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:512)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:258)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by arsenalzp** [comment]
I found a connection behaviour, `localhost` host name is resolved into two IP-addresses: IPv4 and IPv6, so `HttpClient` tries to connect to both addresses. If host name is resolved in more addresses (addresses number are getting from `socketAddresses.size()`) then `HttpClient` tries to connect to all of them:

```
private void connect(List<InetSocketAddress> socketAddresses, int index, Map<String, Object> context)
 {
                    context.put(HttpClientTransport.HTTP_CONNECTION_PROMISE_CONTEXT_KEY, new Promise.Wrapper<>(promise)
                    {
                        @Override
                        public void failed(Throwable x)
                        {
                            int nextIndex = index + 1;
                            if (nextIndex == socketAddresses.size())
                                super.failed(x);
                            else
                                connect(socketAddresses, nextIndex, context);
                        }
                    });
                    HttpClient.this.transport.connect((SocketAddress)socketAddresses.get(index), context);
}
```

**Comment by sbordet** [comment]
@arsenalzp good finding! 

Can you please check that in the "begin" event, you get two different `SocketChannel` instances?
Can you also check that in the "begin" event, you can access the `SocketAddress.getLocalAddress()` and it reports in one case the IPv4 and in the other the IPv6?

We should get 2 "begin" events and 2 "failure" events and 0 "success" events.
If that's the case, everything works as expected and you can wire in the listener to emit the events to.

**Comment by arsenalzp** [comment]
> @arsenalzp good finding!
> 
> Can you please check that in the "begin" event, you get two different `SocketChannel` instances? Can you also check that in the "begin" event, you can access the `SocketAddress.getLocalAddress()` and it reports in one case the IPv4 and in the other the IPv6?
> 
> We should get 2 "begin" events and 2 "failure" events and 0 "success" events. If that's the case, everything works as expected and you can wire in the listener to emit the events to.

Yes, of course, there two different `SocketChannel` instances.

However, it is not possible to get local address when channel is not connected (connection state is pending), meanwhile it is possible to get remote address, check a channel state, etc. 

Moreover, calling `getLocalAddress` on closed channel throws `ClosedChannelException` exception.

My expectation is that bind operation is the first one before any connection attempt.
Look at the `ClientConnector.connect()` it is good place for `onConnectionBegin` event.
However, there is no `bind` operation for `SocketChannel` instance, but `NetworkChannel` one, so it is not possible to get local address by calling `getLocalAddress()` method; doing so method returns `null` .

Obviously, connection can't be established without binding to local address and port, so this operation is done somewhere else (`ManagedSelector.submit()`).
Here is Javadoc for SocketChannel:

> public abstract SocketChannel bind(SocketAddress local)
>                            throws IOException
>
> Binds the channel's socket to a local address.
>
> This method is used to establish an association between the socket and a local address. Once an association is established then the socket remains bound until the channel is closed. If the local parameter has the value null 
then the socket will be bound to an address that is assigned automatically.

It means getting `null`  local address during the initial phase of connection is valid behavior.

It is still possible to get local address on successful connection event.
