### ISSUE TITLE
Jetty 12 - Rewrite of the Jetty WebSocket APIs

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9552]
**Jetty version(s)**
12+

**Enhancement Description**
The Jetty WebSocket APIs were designed following a similar design of the Jakarta WebSocket APIs.

However, that design is old and it clashes with other Jetty core APIs that we have.
In particular:

* No reason to have `Session.getRemote()`
* Duplicated blocking and non-blocking APIs
* The event handling side (`WebSocket[Connection|Frame|Partial|PingPong]Listener`) has unclear semantic wrt threading. In particular, can an event handler method perform blocking calls?
Not to mention the number of interfaces for the various events that may not be optimal when it comes to `instanceof` checks (see https://bugs.openjdk.org/browse/JDK-8180450).
* Implicit demand for new frames/messages when returning from a method, with `Session.suspend()` to try to cope with it.
This clashes with all the other Jetty 12 APIs that have explicit demand APIs.
* Weird handling of methods that take `Reader` or `InputStream` that the implementation treats specially wrt threading: since they offer blocking APIs, there is no demand because the event handler method is not exited, so the implementation has to demand internally in order to feed the `Reader` or `InputStream`.

This would be the right time to re-design the APIs to align them with the rest of the Jetty 12 APIs.

**Comment by sbordet** [comment]
See also #9550 for an explanation of why the undefined semantic of the APIs, coupled with blocking APIs, causes certain scenarios to lockup.

Would be great if `WebSocketUpgradeHandler` could have back `invocationType==NON_BLOCKING` because now the APIs have a defined semantic wrt threading (and no possibility to invoke WebSocket blocking APIs).

**Comment by sbordet** [comment]
@gregw @lachlan-roberts @lorban @joakime your thoughts?

**Comment by monish-byte** [comment]
hey @sbordet I would like to work on this issue. As I am a beginner I would appreciate your guidance. thank you.

**Comment by lachlan-roberts** [comment]
@monish-byte this issue is not something you could help with.

If you want to contribute look at open issues with the "Help Wanted" tag.
https://github.com/eclipse/jetty.project/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22

**Comment by lachlan-roberts** [comment]
@sbordet I think all of those points are just because the Jetty API is designed to mirror what the Jakarta WebSocket API is doing. 

But I think if we decide to move away from that style now would be a good time.

I would suggest that we preserve the old Jetty WebSocket API for EE8/EE9 and then have a new WebSocket API in jetty-core which is extended in EE10 to give access to the servlet behaviours.

**Comment by sbordet** [comment]
Fixed by #9652.
