### ISSUE TITLE
Move (qpack/hpack) HuffmanDecoder / HuffmanEncoder / NBitInteger* to common location

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9554]
**Jetty version(s)**
Jetty 10 / 11 / 12

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
The code between http2 (hpack) and http3 (qpack) are very similar.
Consider moving them to a common location (jetty-util?) to have 1 place to manage issues/bugs around them.

**Comment by gregw** [comment]
Jetty-http would probably be a better destination than util

**Comment by lachlan-roberts** [comment]
fixed with https://github.com/eclipse/jetty.project/pull/9634
