### ISSUE TITLE
Password Util does not ask for password

### ISSUE THREAD

**Issue by ChrisHuebsch-FLIG** [eclipse/jetty.project#9556]
**Jetty version(s)**
10

**Java version/vendor** `(use: java -version)`
Adoptiom JRE 11

**OS type/version**
Windows

**Description**
Password utility is used to obfuscate passwords, e.g. for keystore.

When running the utility without any parameter 

D:\apps\_current\jre11\bin\java.exe -cp d:\apps\_current\jetty10\lib\jetty-util-10.0.13.jar   org.eclipse.jetty.util.security.Password

 prints out:

_Usage - java org.eclipse.jetty.util.security.Password [<user>] <password>
If the password is ?, the user will be prompted for the password_

**How to reproduce?**

Starting the programm with ?, \? or "?" produces always the same result:

_OBF:1e2n
MD5:D1457b72C3Fb323a2671125aEf3eAb5d_

But I was expecting some input prompt.

**Comment by joakime** [comment]
Opened PR #9557 for this
