### ISSUE TITLE
Add support for updated Cookie spec RFC6265

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#958]
The cookie spec has been updated in RFC6265

https://tools.ietf.org/html/rfc6265

We should provide support for this updated spec in Jetty.
Perhaps Jetty 10 (servlet 4.x)?

Should we ping the servlet-spec-experts group to see if the javax.servlet.http.Cookie class needs to be updated as well for this updated spec (not sure if it needs any changes other then javadoc).

**Comment by joakime** [comment]
Chrome has support for RFC6265 already.
https://bugs.chromium.org/p/chromium/issues/detail?id=572541

Firefox has support for RFC6265 too.
https://bugzilla.mozilla.org/show_bug.cgi?id=1255938

Interesting cookie compliance test found at
https://inikulin.github.io/cookie-compat/

**Comment by gregw** [comment]
See #1396

**Comment by joakime** [comment]
Accomplished many releases ago. closing.
