### ISSUE TITLE
DefaultFileLocatorHelper doesn't work with mvn:// protocol in Felix

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#96]
migrated from Bugzilla [#372656](https://bugs.eclipse.org/bugs/show_bug.cgi?id=372656)
status ASSIGNED severity _normal_ in component _osgi_ for _7.5.x_
Reported in version _8.1.1_ on platform _PC_
Assigned to: Jan Bartel

Original attachment names and IDs:
- _[bugzilla_372656.tgz](https://bugs.eclipse.org/bugs//attachment.cgi?id=211832)_ (ID 211832)

On 2012-02-27 11:06:56 -0500, Caspar MacRae wrote:

> Hi,
> 
> I can see the work needed to unwrap Bundle original location into something that Jetty can inspect the contents of (ie. the cached copy).  The workaround here doesn't work with Karaf/Felix and bundles deployed via the mvn url handler (from PaxUrl).
> 
> I'm using Karaf (2.2.4) where it seems the behaviour of the mvn URL handler differs between Equinox and Felix (from what I can see the bundle original location is set to the cached file for Equinox so gets bundle:file: protocol whereas for Felix it's the genuine original URl of mvn://).
> 
> The following classes, walk the known path of the Felix cache, using documented behaviour (http://felix.apache.org/site/apache-felix-framework-bundle-cache.html) to find the locally cached version of the bundle.
> 
> This is working fine for me when packaged inside a fragment of "org.eclipse.jetty.osgi.boot" - may be this could be merged into 
> org.eclipse.jetty.osgi.boot.utils.internal.DefaultFileLocatorHelper as there's no dependencies and it's a tiny addition?
> 
> Apologies for inline code, but just two classes:
> ---
> 
> package org.eclipse.jetty.osgi.boot.utils;
> 
> import static org.osgi.framework.Constants.FRAMEWORK_STORAGE;
> 
> import java.io.File;
> import java.io.FileFilter;
> import java.net.URL;
> import java.util.Enumeration;
> 
> import org.osgi.framework.Bundle;
> 
> public class FileLocatorHelperImpl implements BundleFileLocatorHelper {
> 
>   private static final String FELIX_BUNDLE_IMP_CLASS = "org.apache.felix.framework.BundleImpl";
> 
>   @Override
>   public File getBundleInstallLocation(Bundle bundle) throws Exception
>   {
>       File retVal = DEFAULT.getBundleInstallLocation(bundle);
> 
> ```
>   if(retVal == null && FELIX_BUNDLE_IMP_CLASS.equals(bundle.getClass().getCanonicalName())) {
>       File cacheDir = new File(bundle.getBundleContext().getProperty(FRAMEWORK_STORAGE));
>       retVal = findBundleCacheDir(bundle, cacheDir);
>   }
>   return retVal;
> ```
> 
>   }
> 
>   private File findBundleCacheDir(final Bundle bundle, File cacheDir)
>   {
>       File[] files = cacheDir.listFiles(new BundleLocationFilter(bundle));
> 
> ```
>   if(files == null || files.length != 1) {
>       return null;
>   }
> 
>   File[] subdirs = files[0].listFiles(new FileFilter() {
>       @Override
>       public boolean accept(File file)
>       {
>           return file.isDirectory() && file.getName().startsWith("version");
>       }
>   });
> 
>   if(subdirs == null || subdirs.length != 1) {
>       return null;
>   }
>   return new File(subdirs[0] + File.separator + "bundle.jar");
> ```
> 
>   }
> 
>   @Override
>   public File getFileInBundle(Bundle bundle, String path) throws Exception
>   {
>       return DEFAULT.getFileInBundle(bundle, path);
>   }
> 
>   @Override
>   public File[] locateJarsInsideBundle(Bundle bundle) throws Exception
>   {
>       return DEFAULT.locateJarsInsideBundle(bundle);
>   }
> 
>   @Override
>   public Enumeration<URL> findEntries(Bundle bundle, String entryPath)
>   {
>       return DEFAULT.findEntries(bundle, entryPath);
>   }
> 
> }
> ---
> 
> package org.eclipse.jetty.osgi.boot.utils;
> 
> import java.io.BufferedReader;
> import java.io.File;
> import java.io.FileFilter;
> import java.io.FileInputStream;
> import java.io.IOException;
> import java.io.InputStreamReader;
> 
> import org.osgi.framework.Bundle;
> 
> public class BundleLocationFilter implements FileFilter {
> 
>   private static final String BUNDLE_LOCATION_FILENAME = "bundle.location";
>   private Bundle bundle;
> 
>   BundleLocationFilter(Bundle bundle)
>   {
>       this.bundle = bundle;
>   }
> 
>   @Override
>   public boolean accept(File file)
>   {
>       if(file.isDirectory()) {
>           File originalLocation = new File(file.getAbsolutePath() + File.separator + BUNDLE_LOCATION_FILENAME);
>           if(originalLocation.isFile()) {
>               try {
>                   BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(originalLocation)));
>                   String location = reader.readLine();
>                   if(bundle.getLocation().equals(location.trim())) {
>                       return true;
>                   }
>               } catch (IOException e) {
>                   return false;
>               }
>           }
>       }
>       return false;
>   }
> }
> ---
> 
> thanks,
> Caspar

On 2012-02-27 20:53:16 -0500, Hugues Malphettes wrote:

> Hi there, thanks for filing this and writing the addition.
> 
> It is tempting to provide the functionality out of the box although I don't think we have the resources to actively test and maintain it.
> As it is documented it should remain quite stable.
> 
> Let me review with the rest of the team.
> 
> One question: is not the method BundleLocationFilter.accept leaking file handles?

On 2012-02-28 04:40:41 -0500, Caspar MacRae wrote:

> Hi Hugues,
> 
> RE: leaked handles - yes and potentially quite a few (cue redface), my only defense is it was hastily written to explore the problem (fixed below).
> 
> On one hand I think there's probably a sizable Felix & maven population, that have never deployed a bundle from a file:// url.  But I quite understand your position wrt resource/maintenance/testing, especially given that this not the targeted runtime and there's already solutions such as PaxWeb.
> 
> thanks
> 
>   @Override
>   public boolean accept(File file)
>   {
>       if(file.isDirectory()) {
>           File originalLocation = new File(file.getAbsolutePath() + File.separator + BUNDLE_LOCATION_FILENAME);
>           if(originalLocation.isFile()) {
>               BufferedReader reader = null;
>               try {
>                   reader = new BufferedReader(new InputStreamReader(new FileInputStream(originalLocation)));
>                   String location = reader.readLine();
>                   if(bundle.getLocation().equals(location.trim())) {
>                       return true;
>                   }
>               } catch (IOException e) {
>                   return false;
>               } finally {
>                   if(reader != null) {
>                       try {
>                           reader.close();
>                       } catch (IOException e) {}
>                   }
>               }
>           }
>       }
>       return false;
>   }

On 2012-02-28 05:21:43 -0500, Hugues Malphettes wrote:

> (In reply to comment # 2)
> 
> > Hi Hugues,
> > 
> > RE: leaked handles - yes and potentially quite a few (cue redface), my only
> > defense is it was hastily written to explore the problem (fixed below).
> > :) I did not mean to insist on that: It definitely looked like you know what you are doing.
> > 
> > On one hand I think there's probably a sizable Felix & maven population, that
> > have never deployed a bundle from a file:// url.  But I quite understand your
> > position wrt resource/maintenance/testing, especially given that this not the
> > targeted runtime and there's already solutions such as PaxWeb.
> > OK writing a short email to the jetty-dev then.
> > Always happy to have more adopters anyways.
> > Cheers,
> > Hugues
> > 
> > thanks

On 2012-02-28 06:22:33 -0500, Caspar MacRae wrote:

> Hi Hugues,
> 
> That's great thanks.
> 
> Still woefully embarrassed re: handle leaks =) 
> 
> cheers,
> Caspar

On 2012-02-29 03:13:42 -0500, Hugues Malphettes wrote:

> Hi Caspar,
> 
> We got the nods from the team to commit this with jetty [1].
> 
> To support the IP process tools at eclipse, would you mind packaging the stages as an attachment and add a comment that you are the author of those attachments and are licensing them with EPL+ASL20?
> 
> Cheers.
> Hugues
> [1] http://dev.eclipse.org/mhonarc/lists/jetty-dev/msg01253.html

On 2012-02-29 14:08:17 -0500, Caspar MacRae wrote:

> Created attachment 211832
> Two classes with EPL license headers

On 2012-02-29 14:09:58 -0500, Caspar MacRae wrote:

> Hi Hugues,
> 
> Wasn't sure of the correct header to add, losely followed some git/gerrit notes on Al Blue's blog.  Attached as a tarball and added the following header to both classes:
> 
> /**
> - http://www.eclipse.org/legal/epl-v10.html
> - http://www.apache.org/licenses/LICENSE-2.0.html
>   *
> - I hereby assert that I authored 100% the content that I am contributing
> - I hereby assert that I have the rights to donate the content to EPL / ASL20
> - I hereby assert that I contribute the content under the EPL / ASL20
> - 
> - @see https://bugs.eclipse.org/bugs/show_bug.cgi?id=372656
> - @author Caspar MacRae
>   */
> 
> If it's not ok, please point me to some documentation and I'll correct it.
> 
> cheers,
> Caspar

On 2012-05-01 05:21:20 -0400, Jan Bartel wrote:

> Caspar,
> 
> The headers on contributed files should follow this format:
> http://eclipse.org/legal/copyrightandlicensenotice.php
> 
> Could you resubmit your attachments (with appropriate headers) as a patch to the jetty codebase (integrating the code from your FileLocatorHelperImpl with DefaultFileLocatorHelper IIUC) so we can apply it?
> 
> thanks,
> Jan

On 2012-05-01 11:01:27 -0400, Jesse McConnell wrote:

> also best to make a statement that you authored 100% of the code and you are free to contribute it, just to make sure the lawyers are happy :)

On 2012-05-02 04:34:47 -0400, Caspar MacRae wrote:

> Hi Jan/Jesse,
> 
> The git links on http://wiki.eclipse.org/Jetty/Contributor/Building seem to be stale, specifically http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git - so took it from source of github mirror git://git.eclipse.org/gitroot/jetty/org.eclipse.jetty.project.git   
> 
> I'll get this done tonight.
> 
> One thing to note with this approach; the zip file closed error https://bugs.eclipse.org/bugs/show_bug.cgi?id=364936 occurs, but the documented fix works perfectly <Set class="org.eclipse.jetty.util.resource.Resource" name="defaultUseCaches">false</Set>
> 
> cheers,
> Caspar

On 2012-05-06 12:43:44 -0400, Caspar MacRae wrote:

> Hi Jan/Jesse,
> 
> Apologies for not get this done yet, I'm now in Cuba for two weeks, I thought I'd be able to squeeze this in before I left - but got distracted writing a paxexam 1 test to demonstrate before/after patch.
> 
> I will absolutely get this submitted on my return - apologies again for the delay.
> 
> Best regards,
> Caspar

On 2012-06-11 15:35:13 -0400, Dan Gravell wrote:

> This is great work but I've noticed that it didn't work for me on Felix 4.0.2 (and I suspect on versions 3 and later). Please see https://bugs.eclipse.org/bugs/show_bug.cgi?id=382032 .

On 2012-06-12 09:41:07 -0400, Caspar MacRae wrote:

> @Jan/@Huges - apologies for the poor time management on this - I _will_ get this sorted this weekend.
> 
> @Dan, you are right, the documented cache behaviour was changed at some point in the 3.x line - this is an easy fix to accommodate both formats, but I don't like the fact that's it's undocumented.
> 
> I will attached an updated patch this weekend and chase this up on the Felix mailing list.

On 2012-06-18 07:20:19 -0400, Caspar MacRae wrote:

> Hi,
> 
> I did some work on this yesterday, making changes to PaxExam tests to verify the cache access, but I also discovered a classloading issue using Jetty with Felix 4.x.
> 
> PaxExam:
> 
> The version of pax exam used (1.2.0) doesn't support later frameworks (the range for Felix ends at 2.0.1), version 2.x of PaxExam is more configurable allowing the framework(s) to be provided as a dependency.
> 
> I changed the two tests TestJettyOSGiBootCore and TestJettyOSGiBootWithJsp (marked @Ingore), and have the TestJettyOSGiBootCore working in PaxExam 2.4.0 with Equinox (3.6.0.v20100517, existing dependency version) and Felix (checked 2.0.1 and most of the 3.x line and 4.x).
> 
> Felix Cache:
> 
> The cache behaviour in Felix 3.x is consistent with the documentation (last release 3.2.2), AFAIK this only changed in 4.x, there's now a ticket raising the out-of-date documentation at https://issues.apache.org/jira/browse/FELIX-3561).
> 
> Felix 4.x classloading:
> 
> The current Jetty classloading for Felix is also affected for versions 4.x
> 
> org.eclipse.jetty.osgi.boot.utils.internal.DefaultBundleClassLoaderHelper#internalGetFelixBundleClassLoader(Bundle)
> line 142 tries to get the field "m_modules" from org.apache.felix.framework.BundleImpl but throws an exception.
> 
> The field "m_modules" referred to a list of org.apache.felix.framework.resolver.Module - a class that no longer exists in Felix 4.0.x with the advent of org.osgi.framework.wiring.BundleRevision in OSGi 4.3
> 
> Should I include the fix for the DefaultBundleClassLoaderHelper#internalGetFelixBundleClassLoader(Bundle) in this patch or create a separate ticket? (I have an additional PaxExam test for this which ensures it works in Felix 3.x/4.x)
> 
> Jan/Huges/Jesse, I'm a little worried about scope creep here - though I've only touched two modules jetty-osgi-boot and test-jetty-osgi (I have separate branches for paxexam-2.4.0, this ticket and the Felix 4.x classloading issue).  How would you like this to proceed?
> 
> thanks,
> Caspar

On 2012-06-20 06:29:28 -0400, Dan Gravell wrote:

> I've more bad news, and something that might want to be considered. When using the OBR project within Felix we get another different location URL String from the bundle again: "obr". Example url string:
> 
> obr://my.bundle/-1340186518508
> 
> Obviously this doesn't work either. I get:
> 
> java.lang.IllegalArgumentException: Unable to locate [jar file] inside unlocated bundle '[bundle name]'
> 
> I'm looking for ways of getting around this now... maybe providing my own file locator, so long as OBR provides some way of finding the filesystem location of the bundle.

**Comment by joakime** [comment]
We've had no reports of this issue in a few years.
Closing as no longer valid.
