### ISSUE TITLE
No p2 repository for Jetty 9.3.12

### ISSUE THREAD

**Issue by lkoniecki** [eclipse/jetty.project#961]
There is not p2 repository for current version of the Jetty 9.3 (9.3.12).

See: http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/

**Comment by jmcc0nn3ll** [comment]
https://hudson.eclipse.org/shared/view/Jetty-RT/job/jetty-rt-bundles-9/75/

build looks like it passed, should be in there now
