### ISSUE TITLE
Configurable behavior for when HttpServletResponse is committed

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#962]
Some methods on HttpServletResponse silently fail if the response is in isCommitted state.

Can we have some configurable behavior to: IGNORE or LOG or EXCEPTION when the following methods are used in a response.isCommitted == true state?
- addCookie(Cookie cookie)
- setDateHeader(String name, long date)
- addDateHeader(String name, long date)
- setHeader(String name, String value)
- addHeader(String name, String value)
- setIntHeader(String name, int value)
- addIntHeader(String name, int value)
- setStatus(int code)

Note: it appears that the servlet spec has no error for when these are used on a committed response.  Meaning that this configurable should default to spec behavior, but allow you to introduce the EXCEPTION behavior to be more strict about your behavior.

**Comment by gregw** [comment]
Perhaps this can be an optional response wrapper added by the DebugHandler

**Comment by joakime** [comment]
I'm still keen on coming up with a configurable for this.

**Comment by joakime** [comment]
This seems to overlap some with Issue #670

**Comment by joakime** [comment]
Issue #1024 also seems to overlap
