### ISSUE TITLE
The link given in the name space declaration leads to page not found error

### ISSUE THREAD

**Issue by Monish-VR** [eclipse/jetty.project#9627]
**Jetty version(s):**
10

**OS type/version:**
Windows

**Description:**
In pom.xml of jetty-client the link given in the namespace declaration leads to page not found error.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

**Comment by olamy** [comment]
if you mean `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">` 
yes that is absolutely normal and I would recommend you have a read of https://www.w3.org/TR/2006/REC-xml-names11-20060816/ or https://www.w3schools.com/xml/xml_namespaces.asp 
If it's another which is causing you some trouble please let us know.

**Comment by Monish-VR** [comment]
Sure. Thank you

**Comment by joakime** [comment]
We do have a difference.

Our POM
``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```

Maven Documentation POM - https://maven.apache.org/pom.html#quick-overview
``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
```

It's just a difference between `http://` and `https://` tho, and is irrelevant to how namespaces are handled.

**Comment by Monish-VR** [comment]
Actually I am new to such projects, so let me tell my understanding to you @joakime .

Though there is a difference between our POM and the the documentation(between http:// and https:// respectively). It does not
affect how it's gonna work. Am I right ?

**Comment by joakime** [comment]
> Though there is a difference between our POM and the the documentation(between http:// and https:// respectively). It does not
> affect how it's gonna work. Am I right ?

What you see as a URL is actually a namespace URI systemID reference.
When running maven, the content of `maven-4.0.0.xsd` is used locally and never fetched over the internet.

**Comment by Monish-VR** [comment]
Alright. I got it now. Thanks a lot :)
