### ISSUE TITLE
Dispatcher.forward closes response.outputStream leaving uncommited data in writer.

### ISSUE THREAD

**Issue by nocach** [eclipse/jetty.project#9636]
**Jetty version(s)**
jetty 10.x

**Java version/vendor** `(use: java -version)`
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
**OS type/version**
Oracle Linux Server 7.9
**Description**
Dispatcher.forward closes outputStream after handling request without flushing response writer. This leads to incomplete/corrupt response data after forwarding request.

**How to reproduce?**
Create class WriterWrappedResponse that extends HttpServletResponseWrapper and overrides `getWriter()` method.
```
class WriterWrappedResponse extends HttpServletResponseWrapper {
...
 @Override
	public PrintWriter getWriter() throws IOException{
		if (writer == null)	{
				writer = new PrintWriter(getOutputStream());
		}

		return writer;
	}
...
}
```
Create filter RequestWrapFilter that will wrap response in custom class WriterWrappedResponse.
```
class RequestWrapFilter implements Filter{
...
@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException
	{
              chain.doFilter(request, new WriterWrappedResponse(response));
        }
...
}
```
Create filter RedirectFilter that will redirect request from url1 to url2
```
class RedirectFilter implements Filter{
...
@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException
	{
              if (needsRedirect(httpRequest)){
                      RequestDispatcher dispatcher = httpRequest.getRequestDispatcher(url1);
                      dispatcher.forward(httpRequest, httpResponse);
              }
        }
...
}
```
in Url2Servlet process request 
```
class Url2Servlet extends HttpServlet{
...
         @Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException
	{
            response.getWriter().append('c');
        }
...
}
```

after dispatching redirect in RedirectFilter response.outputStream is closed
```// If we are not async and not closed already, then close via the possibly wrapped response.
                if (!baseRequest.getHttpChannelState().isAsync() && !baseResponse.getHttpOutput().isClosed())
                {
                    try
                    {
                        response.getOutputStream().close();
                    }
                    catch (IllegalStateException e)
                    {
                        response.getWriter().close();
                    }
                }
```

But information in respone.writer was not closed nor flushed, so character 'c' was lost due to internal buffer of PrintWriter.

**Comment by gregw** [comment]
The problem is with your `WriterWrappedResponse` class.  It wraps `getWriter()` but not `getOutputStream()`.  Check the javadoc of these two methods, if one of them is called then the other must throw `IllegalStateException`.
If you throw ISE from `getOutputStream()` you can see that we catch that and close the writer instead.
