### ISSUE TITLE
Invalid SNI 400 issue in jetty , bad message request 

### ISSUE THREAD

**Issue by Ruturaj09** [eclipse/jetty.project#9661]
trying to ignore hostname varification in jetty server  .
using various methods but faild

**Comment by Ruturaj09** [comment]
![image](https://user-images.githubusercontent.com/7047271/232756262-83e5d2b4-7c04-4253-a23a-4dd9f9795209.png)

**Comment by sbordet** [comment]
Did you read the documentation?
https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-protocols-ssl-sni
