### ISSUE TITLE
Server.stop() does not return when called from shutdown hook that was triggered by a CTRL-C

### ISSUE THREAD

**Issue by rupigill** [eclipse/jetty.project#9671]
**Jetty Version:**
10.0.15

I have an application with an embedded Jetty server (version 10.0.15).  Upon normal exit, I call my stopApplication() method which calls Server.stop() followed by some other calls to cleanup resources, and all works fine.  However, if stopApplication() is called from the shutdown-hook when user terminates application with Ctrl-C, the call to Server.stop() never returns, so the subsequent cleanups of resources are not done.  
Unfortunately, I am not able to debug shutdown hook in Intellij IDEA on Windows.

**Comment by joakime** [comment]
Your cleanup calls should either be a Runtime Shutdown Hook, or a `LifeCycle` bean registered to react on `doStop()`

* The Shutdown Hooks are added via [`java.lang.Runtime.addShutdownHook(Thread)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)).

* The `LifeCycle` can be on the Server as a managed bean like this ...

``` java
LifeCycle cleanup = new AbstractLifeCycle()
{
    @Override
    protected void doStop() throws Exception
    {
        // my cleanup calls here, just be sure to not reference things in the Server object
    }
};
server.addManaged(cleanup);
```

* Or the `LifeCycle` can be a registered (and started) lifecycle at `org.eclipsejetty.server.ShutdownMonitor.register(LifeCycle)` ...

``` java
LifeCycle cleanup = new AbstractLifeCycle()
{
    @Override
    protected void doStop() throws Exception
    {
        // my cleanup calls here, just be sure to not reference things in the Server object
    }
};
cleanup.start();
ShutdownMonitor.register(cleanup);
```

**Comment by rupigill** [comment]
As I implied in the issue description, the cleanup (call to stopApplication()) is indeed added as a shutdown-hook (via Runtime.addShutdownHook).  stopApplication() does indeed run when user terminates application with CTRL-C or some error triggers System.exit().  BUT... stopApplication() calls Server.stop(), which never returns, so the cleanups that need to happen after Server.stop() never get executed.  

BTW, if stopApplication() is called from outside of shutdown-hook, then Server.stop() returns fine and cleanups that follow it are performed successfully.

Later today I will attach the logs produced by stopApplication() when called directly, and when called via shutdown-hook.

**Comment by rupigill** [comment]
Attached are two log files:
jetty-stop-good.txt has the logs generated by Server.stop() when it is called directly (i.e. NOT via shutdown-hook).
jetty-stop-bad.txt has the logs generated when Server.stop() is called via shutdown-hook.  The same set of logs is generated if I invoke shutdown-hook by pressing Ctrl-C, or by having application call System.exit().  I did multiple runs; set of logs is the same.
[jetty-stop-bad.txt](https://github.com/eclipse/jetty.project/files/11328244/jetty-stop-bad.txt)
[jetty-stop-good.txt](https://github.com/eclipse/jetty.project/files/11328245/jetty-stop-good.txt)

**Comment by rupigill** [comment]
Never mind.  The issue is with log4j shutting down prematurely via its own shutdown hook!  I was able to debug the call to Server.stop() in my shutdown hook and saw that it returns fine; but the logs do not show up because log4j has shutdown.
