### ISSUE TITLE
API requests are failing with "403 AWS Signature Mismatch Error"

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9674]
**Jetty Version:**
10.0.15

API requests are failing with 403 AWS Signature Mismatch error post Jetty 10.0.12 upgrade .Setting HttpCompliance.LEGACY used to solve this error as shown below 

https://github.com/gaul/s3proxy/commit/2e61c3862656419f2a0452d9ceab22be311e84fb

But now it fails in Jetty 10 again 
This is because the content type that we are sending "Content-Type: application/x-www-form-urlencoded; charset=**utf-8**" is converted in to uppercase "application/x-www-form-urlencoded; charset=**UTF-8**" .

What exactly should be used to resolve this error in Jetty 10 ? org.eclipse.jetty.http.HttpCompliance.RFC7230 doesn't seem to help here

_Originally posted by @smitagarg1 in https://github.com/eclipse/jetty.project/issues/3009#issuecomment-1521836984_

**Comment by joakime** [comment]
Sounds like your AWS implementation isn't handling HTTP/1.1 headers properly (which are string case-insensitive), so it shouldn't be doing the signature in case-sensitive nature.

Second guess is that you are hitting a side effect of the Header string cache which is by default case-insensitive (per HTTP spec).

Try this ...

``` java
HttpConfiguration httpConfig = new HttpConfiguration();
httpConfig.setHttpCompliance(HttpCompliance.RFC7230);
httpConfig.setHeaderCacheCaseSensitive(true);        
ServerConnector http = new ServerConnector(server, new HttpConnectionFactory(httpConfig));
```

**Comment by smitagarg1** [comment]
This works fine for me after using httpConfig.setHeaderCacheCaseSensitive(true);  .Thanks for the help
