### ISSUE TITLE
Unable to use Jetty 10.0.15 on Android API 23

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9676]
**Jetty Version:**
10.0.14
              
I'm using Cometd 5.0.15, which depends on Jetty 9.4.51, and getting the same errors with minSdk 23.
However, the method name it's happening in has changed (ModuleLocation.apply instead of ModuleLocation.getModuleLocation), exactly according to https://github.com/eclipse/jetty.project/pull/6053

`MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26): Lorg/eclipse/jetty/util/ModuleLocation;apply(Ljava/lang/Class;)Ljava/net/URI;`

In its turn, CometD 6.0.10 (Jetty 10.0.14) fails with this
`MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26): Lorg/eclipse/jetty/util/TypeUtil;getLocationOfClass(Ljava/lang/Class;)Ljava/net/URI;`

Desperately need help, I'm stuck at CometD 3.1.14, which is 3 years old already and has been deprecated.

_Originally posted by @amatsehor-atd in https://github.com/eclipse/jetty.project/issues/6128#issuecomment-1521925139_

**Comment by joakime** [comment]
Per the Android Java SDK documentation.

* `MethodHandle.invoke()` - https://developer.android.com/reference/java/lang/invoke/MethodHandle#invoke(java.lang.Object[]) - requires Android API Level 26
* `MethodHandle.invokeExact()` - https://developer.android.com/reference/java/lang/invoke/MethodHandle#invokeExact(java.lang.Object[]) - requires Android API Level 26

Your use of Android 0 (undefined) is where you are doing things wrong (you need to define the Android API level properly in your project, seek Android specific websites for advice on this)

Your desire to use minSdk 23 is also incompatible, you must be on minSdk 26.

**Comment by amatsehor-atd** [comment]
It's actually Android O, not 0 (from Oreo)

Yes, I understand that lifting minSdk from 23 to 26 can solve a problem, but it's not possible for me now sadly.
But wasn't the whole idea of https://github.com/eclipse/jetty.project/issues/6052 to allow using 9.4.x+ versions to run on Android <26 ?

**Comment by joakime** [comment]
Considering that [targeting Android API level 26 represents 93.3% of all Android users](https://apilevels.com/), we will not be spending the inordinate effort to adjust Jetty 10 to satisfy the remaining 6.7% of Android users that don't want to upgrade. 

[Jetty 9.x is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958), and will not be getting updated without a support contract (see [announcement](https://github.com/eclipse/jetty.project/issues/7958) for details)

**Comment by joakime** [comment]
Note that Google and the AOSP community (all vendors) have the following support for (select) Android versions.

See 
* https://source.android.com/docs/security/bulletin
* https://developer.android.com/about/versions

Android Version | API Level | %Users Left Using | Final Patch Date | Dropped Support from AOSP (and all vendors)
----- | ----- | ----- | ----- | -----
Android 8 | API Level 26 | 6.7% | Oct 2021 | Nov 2021
Android 7 | API Level 25 | 5.6% | Oct 2019 | Nov 2019
Android 6 | API Level 23 | 1.8% | Sept 2018 | Oct 2018

You are basically requesting that we support a version of Android that is unsupported by everyone.
