### ISSUE TITLE
Jetty 9.2.19 Client gets incomplete response without exception

### ISSUE THREAD

**Issue by duan2ping** [eclipse/jetty.project#9679]
**Jetty version**
9.2.19.v20160908
**Java version**
JDK1.8
**Question**
When I used Jettyclient to request a file download API, although the HTTP response was 200, the obtained file was incomplete and some data was lost.

If you delete the timeout configuration or set the timeout to a longer time than the file API response, you can respond to complete data.
```java
request.timeout(10, TimeUnit.SECONDS);
```

I think the reason is that the client set a request timeout and the server responded in segments (Transfer Encoding: chunked). If the server does not fully respond within the specified timeout, but only partially responds. However, the client disconnected due to timeout and did not report a request timeout. It will respond normally to 200 and some data

Request Code Example
```java
private void call() throws Exception {
        HttpClient client = new HttpClient();
        client.start();
        String url = "http://127.0.0.1:8080/chujian.mp4";
        Request request = client.newRequest(url);
        request.timeout(10, TimeUnit.SECONDS);
       
        InputStreamResponseListener responseListener = new InputStreamResponseListener() {
            File file = new File("/opt/file01.mp4");
            FileOutputStream fos = new FileOutputStream(file);
            WritableByteChannel channel = Channels.newChannel(fos);
            @Override
            public void onContent(Response response, ByteBuffer content, Callback callback) {
                System.out.println("[Response.Listener] onContent");
                System.out.println(content.limit());
                try {
                    channel.write(content);
                } catch (Exception e) {
                    callback.failed(e);
                }
            }

            @Override
            public void onComplete(Result result) {
                System.out.println("[Response.Listener] onComplete");
                if (result.isFailed() && result.getResponse().getStatus() != 200) {
                         System.out.println("Request Failed.");
                } else {
                    try {
                        System.out.println(result.getResponse().getStatus());
                        result.getResponse().getHeaders().forEach(h -> {
                            System.out.println(h.getName() + ":" + h.getValue());
                        });
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        request.listener(listener).send(responseListener);
    }
```

File HTTP API：Use nginx to provide file APIs and delay responses.
File Size：132619240 byte
```
 location / {
            root   /opt/files;
            index  index.html index.htm;
             access_by_lua '
                ngx.sleep(9.8)
            ';
        }
```

**Comment by sbordet** [comment]
Please update to Jetty 10 or later.
Jetty 9.2.x is not supported anymore since years now.

Try again with Jetty 10 or later and report back if the error still happens.

**Comment by joakime** [comment]
Regarding Jetty Versions, See ....

* https://www.eclipse.org/jetty/download.php#version-table - where you can see that Jetty 9.2.x was End of Life back in 2018.
* https://github.com/eclipse/jetty.project/issues/7958 - announcement of Jetty 9.x being End of Community Support.

**Comment by joakime** [comment]
Closing, If you can replicate this on Jetty 10 (or newer), let us know here on this issue, and we'll reopen it.

**Comment by duan2ping** [comment]
@joakime Hello, I have upgraded to version 11.0.5 and still have the same problem using the same code.

**Comment by sbordet** [comment]
> I think the reason is that the client set a request timeout and the server responded in segments (Transfer Encoding: chunked). If the server does not fully respond within the specified timeout, but only partially responds

Yes so the behavior of the client is correct.

The response metadata containing the status code and the headers and part of the content has already arrived on the client, so by the time `onComplete(Result result)` is called, that information is already available and cannot be changed.

Whether then the communication is interrupted because it is taking too long, that is a different problem.
If that happens, it will fail the response, even if the status code that is already arrived is 200.

The behavior you are seeing is normal and expected.

**Comment by duan2ping** [comment]
> Yes so the behavior of the client is correct.

If this is correct, what is the significance of obtaining partial response data? Due to incomplete data, users may encounter unexpected issues.
For example, due to network reasons, when the network is unobstructed, returning within the specified time can normally obtain complete data. When the network is blocked, it will exceed the specified timeout, resulting in incomplete data obtained. However, the response codes received by the user are all 200, indicating a normal response. Users have to investigate how the data was lost, which can be a headache.

If we can determine whether the response result is incomplete by throwing an exception or obtaining a certain attribute value, that would be even better.

> Whether then the communication is interrupted because it is taking too long, that is a different problem.
If that happens, it will fail the response, even if the status code that is already arrived is 200.

I am not very familiar with Jetty. May I know how to configure it to achieve the results you mentioned.

**Comment by sbordet** [comment]
> However, the response codes received by the user are all 200, indicating a normal response. Users have to investigate how the data was lost, which can be a headache.

That is a wrong assumption.

Class `Result` explicitly provides APIs such as `isSucceeded()` or `isFailed()` that indicate whether the request/response is succeeded or failed.

You are wrongly assuming that if a partial response arrived with a 200, then it is successful, and this may not be the case in general.

So there is no headache, just read the documentation and use the API properly.

And BTW you are already using `result.isFailed()`, it is just that you have an extra condition (wrong) in your code.

**Comment by duan2ping** [comment]
I understand, there is a problem with my code. Thank you.

**Comment by sbordet** [comment]
Resolved.
