### ISSUE TITLE
Permanent UnavailableException thrown during servlet request handling should cause servlet destroy

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#97]
migrated from Bugzilla [#375013](https://bugs.eclipse.org/bugs/show_bug.cgi?id=375013)
status ASSIGNED severity _normal_ in component _server_ for _9.0.0.RC0_
Reported in version _7.6.2_ on platform _All_
Assigned to: Jan Bartel

On 2012-03-21 22:48:36 -0400, Jan Bartel wrote:

> Servlet spec 3.0, sec. 2.3.3.2, pg 10:
> 
> If a permanent unavailability is indicated by the UnavailableException, the servlet
> container must remove the servlet from service, call its destroy method, and release
> the servlet instance. Any requests refused by the container by that cause must be
> returned with a SC_NOT_FOUND (404) response.
> 
> ...
> 
> The container may choose to ignore the distinction between a permanent and
> temporary unavailability and treat all UnavailableExceptions as permanent,
> thereby removing a servlet that throws any UnavailableException from service.

**Comment by joakime** [comment]
@janbartel is this still valid? 
Looking at the code I think we got this solved in several different ways.

**Comment by joakime** [comment]
@janbartel I think this one is similar to the question on stackoverflow ... https://stackoverflow.com/questions/50907272/get-jetty-to-gracefully-shut-down-a-failed-to-start-webapp-context

**Comment by joakime** [comment]
@janbartel this one also overlaps with eclipse-ee4j/servlet-api#152 and our #412

**Comment by gregw** [comment]
Fixing this in #4083 with a holder cleanup
