### ISSUE TITLE
Modifying of HTTP headers in request metadata is no longer possible with Jetty 10 

### ISSUE THREAD

**Issue by smitagarg1** [eclipse/jetty.project#9721]
Jetty version(s)
Jetty 10.0.12

I was earlier using jetty version 9.4.43 and had following code to change empty content-type to "application/octet-stream" 
in request metadata in order to avoid jetty not supporting empty content type and throwing 400 errors .

**Jetty 9 code :**
  request.getMetaData()
                    .getFields()
                    .computeField(HttpHeader.CONTENT_TYPE, (httpHeader, httpFields) ->
                            new HttpField(httpHeader, MediaType.APPLICATION_OCTET_STREAM));

**Jetty 10 : code changes made to use computeField from HttpFields.Mutable**
HttpFields.build(request.getMetaData()
                    .getFields()).computeField(HttpHeader.CONTENT_TYPE, (httpHeader, httpFields) ->
                    new HttpField(httpHeader, MediaType.APPLICATION_OCTET_STREAM));

But it has started throwing 400 error again .It seems header value is not getting modified to APPLICATION_OCTET_STREAM from empty 

Looks somewhat similar to https://github.com/eclipse/jetty.project/issues/7818

**Comment by joakime** [comment]
Why are you doing that?
What goal are you trying to reach?

There are many paths you could have taken, and it seems you chose one of the most difficult paths.

**Comment by smitagarg1** [comment]
This is how the application has been .My task here only is to upgrade the existing code as per jetty 10 requirements .

**Comment by gregw** [comment]
@smitagarg1 your code is just creating a new HttpFields instance, but not setting that back on the baseRequest.  Try something like:
```java
        MetaData.Request meta = baseRequest.getMetaData();
        HttpFields.Mutable newFields = HttpFields.build(meta.getFields());
        newFields.computeField(HttpHeader.CONTENT_TYPE, (httpHeader, httpFields) ->
            new HttpField(httpHeader, MediaType.APPLICATION_OCTET_STREAM));
        baseRequest.setMetaData(new MetaData.Request(
            meta.getMethod(),
            meta.getURI(),
            meta.getHttpVersion(),
            newFields));
```

**Comment by joakime** [comment]
Question answered, closing.
