### ISSUE TITLE
handshake_failure when connecting with jetty-client > 9.3.6.v20151106

### ISSUE THREAD

**Issue by mailq** [eclipse/jetty.project#975]
### Problem
I can't connect to a specific HTTPS site with a newer version of jetty-client.

### How to reproduce
I use the following code
```
SslContextFactory sslcontext = new SslContextFactory();
sslcontext.setTrustAll(true);
HttpClient httpClient = new HttpClient(sslcontext);
httpClient.setMaxConnectionsPerDestination(4);
URI uri = URI.create("https://admin.dnswl.org");
String realm = "dnswl.org Admin";
AuthenticationStore auth = httpClient.getAuthenticationStore();
auth.addAuthentication(new BasicAuthentication(uri, realm, "test", "test"));
try {
	httpClient.start();
	ContentResponse response = httpClient.GET(uri.toString());
	System.out.println(response.getStatus());
	httpClient.stop();
} catch (Exception e) {
	e.printStackTrace();
}
```
### Expected behavior
Get a "401" printed on the console

### Actual behavior
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### Affected versions
jetty-client 9.3.7.v20160115 and above
jetty-client 9.3.13.M0 (throws ClosedChannelException)
jetty-client 9.4.0.RC0 (throws ClosedChannelException)

### Working versions
jetty-client 9.3.6.v20151106 and below

### System environment
Ubuntu 16.04.1 LTS
openjdk version "1.8.0_91"
build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14

**Comment by sbordet** [comment]
It's a server problem.
The server replies with a handshake failure immediately after the client sends the `ClientHello`.
Fails for me even with Jetty 9.3.6.

**Comment by mailq** [comment]
```
URLConnection openConnection = URI.create("https://admin.dnswl.org").toURL().openConnection();
openConnection.connect();
openConnection.getContent();
```
works as expected (status 401). No jetty involved at all. So can't be a server issue.

**Comment by joakime** [comment]
Your `URLConnection` example doesn't work for me in Linux + Java 6u45 & 7u25 & 8u31 (plain JDKs, no JCE/Unlimited add-ons).  Nor does it work on OSX + Java 6u33 & 7u75 & 8u71.

They all report handshake failure / fatal alert.

@mailq have you analyzed your server configuration against the ssllabs tests? 
https://www.ssllabs.com/ssltest/

Its not that unusual to have missed something with the server setup and configuration for SSL/TLS that can break clients.

The fact that the server issues a handshake failure / fatal alert likely points at some bad server configuration.  Not much that a client can do to get around that.

**Comment by mailq** [comment]
I attached a "clean" test suite for running inside a Docker container.
[issue975.zip](https://github.com/eclipse/jetty.project/files/507203/issue975.zip)

Issue a `make` to create the container.

A `make run936` will show that it works with 9.3.6
A `make run937` will show that it does not work with 9.3.7
A `make runjdk` will show that it works without jetty at all

And yes, the SSL tests also show "handshake_failure". But that is not the point here. There are situations where you can get the content of the URL without a failure (runjdk and run936)

**Comment by joakime** [comment]
What did the https://www.ssllabs.com/ssltest/ report say?

**Comment by mailq** [comment]
As I said (last paragraph):
Java 6u45  Server sent fatal alert: handshake_failure
Java 7u25 	Server sent fatal alert: handshake_failure
Java 8u31 	Server sent fatal alert: handshake_failure

But I can **prove** that it works with an older version of jetty-client. Beside the "configuration mistake" everybody implies.

**Comment by joakime** [comment]
The destination server you are attempting to connect to supports 4 ciphers only (this is a bad configuration on your server).


```
Starting Nmap 7.12 ( https://nmap.org ) at 2016-10-03 15:10 MST
Nmap scan report for admin.dnswl.org (5.9.7.57)
Host is up (0.17s latency).
Other addresses for admin.dnswl.org (not scanned): 2a01:4f8:160:72ac::2
rDNS record for 5.9.7.57: db.dnswl.org
PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 4096) - A
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       Key exchange parameters of lower strength than certificate key
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 4096) - A
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       Key exchange parameters of lower strength than certificate key
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 7.95 seconds
```

Of the 2 ciphers on TLSv1.0
 - both excluded as vulnerable by cipher (Industry recommendation, implemented in Jetty only)
 - all excluded as vulnerable by protocol (Industry recommendation, implemented in JVM and Jetty)

Of the 2 ciphers on TLSv1.2
 - both excluded as vulnerable by cipher (Industry recommendation, implemented in Jetty only)

> History: The combination of RSA + SHA was declared vulnerable in 2005, with industry recommendations to stop using that combination in 2008, with government declarations to stop using those in 2010.

You have 2 solutions:

**1) Long Term Solution**

Upgrade / fix your server configuration (that server scores an `F` on ssllabs.com btw).

Increase the number of available ciphers you have available for TLS/1.2 on that server, you should at a bare minimum support the required TLS/1.2 cipher `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`


**2) Short Term Solution**

Adjust your HttpClient to not exclude any ciphers.

``` java
sslcontext.setExcludeCipherSuites(new String[0]);
```

> IMPORTANT NOTE: This will only work for as long as you don't upgrade your version of Java, or your OS.
>
> All ciphers following this pattern `^.*_RSA_.*_(MD5|SHA|SHA1)$` are vulnerable, and we have been tracking a proposal to mark them excluded in a future Java JVM release.
>
> When TLS/1.3 is released (currently in draft form), those cipher suites will not be available anymore, they will be removed permanently from the supported list of ciphers for all TLS support levels.  When this happens, you will not be able to connect to your server from that OS, no matter what client configuration you attempt to use.

**Comment by joakime** [comment]
When Jan 1, 2017 rolls around Chrome and Firefox will start rejecting SHA/SHA-1 ciphers.  Which means those browsers will no longer be able to connect to the server you are working against.

 - [Chrome news](http://www.securityweek.com/google-sunset-sha-1-crypto-hash-algorithm)
 - [Firefox announcement](https://blog.mozilla.org/security/2014/09/23/phasing-out-certificates-with-sha-1-based-signature-algorithms/)

**Comment by mailq** [comment]
Thank you. The Short Term Solution worked. So that was the problem.
Now I'm going to convince the admins of the server to apply the long term solution...
