### ISSUE TITLE
Jetty http client chooses only the first proxy even when multiple proxies configured

### ISSUE THREAD

**Issue by naseryyash** [eclipse/jetty.project#9755]
**Jetty version**
9.4.49v20220914

**Java version**
17

**Question**
Hi Team,

In our project,  we have the following use case. There is a need to support 2 HTTP proxy servers with Jetty HTTP client. One of the proxy servers will handle HTTP traffic and the other one will handle HTTPS traffic. 

Below is a sample code of how we configure jetty. 

Now the problem here is that jetty always tries to hit the first proxy (http://localhost:8097) irrespective of whether it is up or down, and all the requests which are HTTPS and are supposed to go through the second proxy (http://localhost:3128) never hit it and fail eventually. 

So I have 2 questions. 
1) Is it possible to configure Jetty for such a use case ? 
2) If it is, is this the right way to do it? 

```
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.ProxyConfiguration;
import org.eclipse.jetty.client.HttpProxy;
import org.eclipse.jetty.client.Origin;

private void addProxyConfig(HttpClient httpClient) {
    ProxyConfiguration.Proxy proxy =
            getJettyProxy("127.0.0.1", 8097);
    ProxyConfiguration.Proxy httpsProxy =
            getJettyProxy("127.0.0.1", 3128);

    
    httpClient.getProxyConfiguration().getProxies()
            .add(proxy);
    httpClient.getProxyConfiguration().getProxies()
            .add(httpsProxy);
}

private ProxyConfiguration.Proxy getJettyProxy(
    String host,
    int port) {
    // our proxy is always HTTP
    // the server behind that can be HTTP or HTTPS
    return new HttpProxy(
            new Origin.Address(host, port),
            false);
} 
```

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

By now you should be using Jetty 10, or Jetty 11, or even Jetty 12.
Please upgrade, try again, and if the problem persists, let us know.

**Comment by naseryyash** [comment]
Hi @joakime ,

I am not sure it'd be possible to switch to jetty 11, at least for now. Is there any chance you could help me with this in Jetty 9 ?

**Comment by joakime** [comment]
Jetty 9 support is only available via support contract now.
See #7958 for details.

Closing.  If this is still a problem on Jetty 10, or Jetty 11, or Jetty 12, let us know and we'll reopen this issue.

**Comment by sbordet** [comment]
The implementation of `HttpProxy` is the same for all Jetty versions, so likely you're going to have the same issue in all of them.

Currently, the implementation of `HttpProxy` only matches based on address (host and port), however the scheme information is available so you just need to override `HttpProxy.matches(Origin)` with your own logic.

**Comment by naseryyash** [comment]
Thank you for your answer @sbordet. I will try it.
