### ISSUE TITLE
LdapLoginModule doesn't work if the value of the userRdnAttribute is different from the username entered

### ISSUE THREAD

**Issue by SimonDallaway** [eclipse/jetty.project#976]
If the directory being used creates group member records containing an attribute value different from the username the user entered the LdapLoginModule cannot find the user's roles e.g.
if the user record is
    cn=Simon Dallaway
    uid=simonda

and the group record contains
    member=cn=Simon Dallaway,ou=users,dc=example,dc=com

[LdapLoginModule.java.txt](https://github.com/eclipse/jetty.project/files/507292/LdapLoginModule.java.txt)

Minor modifications to the class resolve this (see attached). I also removed a duplicated user lookup.

**Comment by joakime** [comment]
We cannot accept code this way (for eclipse legal reasons)

Please submit a Github pull request.

**Comment by SimonDallaway** [comment]
Hi Joakim,

Sorry, not a git user so I've had some "fun" trying to do so. I hope it has got through. Apologies in advance for any errors

**Comment by janbartel** [comment]
Looks like a pr #1005  for this was merged on 14th October. Closing.
