### ISSUE TITLE
jetty-12 ee10 ServerPush failures

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9767]
### Tck test: com/sun/ts/tests/servlet/spec/serverpush/Client.java.serverPushNegtiveTest

This test performs a number of checks. The 2 that are failing:

1. `PushBuilder.method(null)` must throw NPE according to the spec, but we throw `IAE` instead
2. `PushBuilder.method(m)`  must throw `IAE` if the method is considered unsafe, which according to the `PushBuilder` javadoc are:  `POST, PUT, DELETE, CONNECT, OPTIONS and TRACE`. However, we do _not_ consider `OPTIONS` and `TRACE` to be unsafe.

**Comment by sbordet** [comment]
@janbartel see #9773.

**Comment by janbartel** [comment]
Fixed.
