### ISSUE TITLE
Why unbounded queue isn't part of the jetty 9.x High Load documentation anymore ? 

### ISSUE THREAD

**Issue by strogiyotec** [eclipse/jetty.project#9769]
**Jetty version**
9.x
**Java version**
11
**Question**
Looking at the old jetty docs(https://wiki.eclipse.org/Jetty/Howto/High_Load) I found a paragraph related to unbounded queue
> It is very important to limit the task queue of Jetty. By default, the queue is unbounded! As a result, if under high load in excess of the processing power of the webapp, jetty will keep a lot of requests on the queue. Even after the load has stopped, Jetty will appear to have stopped responding to new requests as it still has lots of requests on the queue to handle. 

I just checked the source code of jetty 9.4 and the MonitredThreadPool class still uses unbounded array blocking queue by default

However , looking at the new documentation for jetty 9.x I didn't find anything related to the queue size tuning. The thread pool paragraph now only mentions the size of the pool

> Thread Pool
    Configure with goal of limiting memory usage maximum available. Typically this is >50 and <500
   
I wonder why new jetty doc doesn't mention queue size anymore considering it's still an issue during Dos attacks when this queue becomes full consuming all File Descriptors in the server

**Comment by strogiyotec** [comment]
Just in case I would love to contribute to jetty docs if this was unexpected degression

**Comment by gregw** [comment]
The QTP queue is not the correct mechanism to protect against DOS attacks. In fact limiting that queue size is more often likely to make an otherwise recoverable server fail.

DOS attacks are better defended by directly limiting expensive resources: connections, requests, data rates etc.

Trying to protect from DOS in the thread pool is treating a symptom not a cause.

Documentation on jetty 9 is no longer actively maintained. Jetty 12 is our next major release and we do need to put a lot of effort into improving the documentation there. If you want to review/contribute to doco then 12 branch is where active developer is.

**Comment by sbordet** [comment]
We should definitely expand on the documentation about the queue here:
https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-arch-threads-thread-pool

**Comment by strogiyotec** [comment]
@gregw  thanks for the reply. I will explain why I disagree with your suggestion.
There was a case when my server got a few million requests at the same time, the File descriptor(FD)  limit for the Linux server is around 60k, and by sending a million requests server opened all available FD
As a result, most threads from qtp were blocked. It happened because I am using a sync log4j logger which requires an FD to flush data to the file. I believe that by limiting the queue size I can decrease the number of connections that jetty can open and subsequently allow the backend to use FD for things like writing to files or opening JDBC connections.
I was thinking if limiting number of connections will be a better way ? https://github.com/eclipse/jetty.project/issues/512
Thanks in advance

**Comment by sbordet** [comment]
@strogiyotec as @gregw said, using the thread pool to limit other things as a consequence is not a good idea.

The number of FD uses for a "few millions requests" is independent from the number of requests, can be that you send a few millions requests on just one connection, so you don't have any FD problem.

> I believe that by limiting the queue size I can decrease the number of connections that jetty can open

No.

Jetty provides a way to limit the number of incoming connections, see classes `org.eclipse.jetty.server.ConnectionLimit` and `org.eclipse.jetty.server.AcceptRateLimit`.

If these do not fit your needs, you can always write your own following their example.

**Comment by strogiyotec** [comment]
@sbordet  I closed the ticket, thanks for two classes that you  mentioned 
However, could you explain this statement
> can be that you send a few million requests on just one connection, so you don't have any FD problem.
As far as I can tell and I don't remember the sources of that 
Each HTTP request opens a socket, each socket in a UNIX requires a file descriptor so 1mln requests = 1 mln FD
So I didn't get your example when mln requests can use a single connection.
Did you mean 1 HTTP connection/1 user who sends that many requests?

**Comment by strogiyotec** [comment]
From reading the doc for ConnectionLimit

> This listener applies a limit to the number of connections, which when exceeded results in a call to [AbstractConnector.setAccepting(boolean)](https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/server/AbstractConnector.html#setAccepting(boolean)) to prevent further connections being received. It can be applied to an entire server or to a specific connector by adding it via [Container.addBean(Object)](https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/util/component/Container.html#addBean(java.lang.Object))ct))

So we still can face an issue when 1 user can sends a bunch of requests using only one connection Am I right ?

**Comment by sbordet** [comment]
> So we still can face an issue when 1 user can sends a bunch of requests using only one connection Am I right ?

No.

Over 1 connection only 1 FD will be used, and the requests (in HTTP/1.1) will be processed sequentially one after the other.
