### ISSUE TITLE
Jetty 12 - Remove WriteFlusher.Listener

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#9778]
**Jetty version(s)**
12

**Description**
`WriteFlusher.Listener` was introduced to compute the response data rate.
This was necessary because for HTTP/2 or HTTP/3 we do not know often before hand how many bytes are flushed (because we use objects that are serialized just before hitting the network).
Furthermore wrapping with TLS complicates things because of the added wrapping.

However, I think it should now be possible to remove this (expensive) listener mechanism in favor of callbacks.

For HTTP/2, for example, a `[Control|Data]Entry` knows how many bytes it has generated, and upon completion of its write it can update the number of bytes written (for statistics), and check the `minResponseDataRate` in the callback in`HttpStreamOverHTTP2.send()`.

This will only take into account clear-text writes (the overhead of a wrapping protocol such as TLS is not counted).

Note that we cannot move the bytes counting to `EndPoint` because for multiplexed protocols we want to check the `minResponseDataRate` per-stream, not per-session.

**Comment by sbordet** [comment]
@gregw thoughts?

**Comment by gregw** [comment]
@sbordet the less listeners the better
