### ISSUE TITLE
Payload changes during the websocket communication

### ISSUE THREAD

**Issue by kiss034** [eclipse/jetty.project#9793]
**Jetty version(s)**
* 11.0.15
* 10.0.15

**Java version/vendor**
openjdk 17.0.5 2022-10-18 LTS

**OS type/version**
Amazon Linux release 2 (Karoo)

**Description**
Sometimes only a truncated payload arrives to the server side. For example we send a payload with 3'654 bytes, but the server only receives 2'658 bytes. The issue is more common if the messages are larger than 4096 bytes.

**How to reproduce?**
A demo application can be found on this repository: https://github.com/kiss034/websocketdemo
If you run the DemoServer.main() method,
1. it starts a server and a client
2. the client sends 10'000 random binary messages to the server
3. the server checks whether the full message is arrived and sends back the message to the client

**Comment by joakime** [comment]
Your implementation has bugs.

Here's a slightly fixed version - https://github.com/joakime/jetty-issue-9793-websocket/tree/joakime-mavenized (see the `joakime-mavenized` branch).

You send a whole ByteBuffer as a whole WebSocket message, where the first 4 bytes are an integer representing the size of the ByteBuffer you are sending.
Then you attempt to capture the raw WebSocket FRAME (not Message) and validate that the received FRAME is what you sent as a Message.
But you don't take care of following the WebSocket spec behaviors when it comes to handling Frames.

A WebSocket Message is 1...n Frames.
A BINARY Message always starts with a BINARY Frame, and then 0...n CONTINUATION Frames, ending finally with a fin==true.
A TEXT Message always starts with a TEXT Frame, and then 0...n CONTINUATION Frames, ending finally with a fin==true.

I changed your `@OnWebSocketFrame` implementations to accumulate the bytebuffers and then only validate once the entire Message has been received.
It works, but makes assumptions that you only ever send BINARY messages, and never send a TEXT message.
If you intend to support both BINARY and TEXT messages, then your implementation of `@OnWebSocketFrame` needs to be beefed up to check for the data mode (BINARY vs TEXT) and act accordingly. (this is why I said "slightly fixed" above)

If you choose to use `@OnWebSocketMessage` you can skip this accumulation step in your code and just let Jetty handle it for you.
There's an example of this in the `DemoServer`, just comment out the `// @OnWebSocketFrame` line (to make it inactive in code) and then uncomment the `// @OnWebSocketMessage` and rerun your tests.

Note also that DEBUG logging is enabled in the `src/main/resources/jetty-logging.properties`, you can dial that down if you don't want that much noise.

**Comment by kiss034** [comment]
Hi @joakime,

Thanks for the help. I checked your implementation, and it works properly.
