### ISSUE TITLE
Support for Pack200 compressed WEB-INF/lib jars

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#98]
migrated from Bugzilla [#375278](https://bugs.eclipse.org/bugs/show_bug.cgi?id=375278)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _7.6.2_ on platform _All_
Assigned to: Project Inbox

On 2012-03-25 18:06:41 -0400, Greg Wilkins wrote:

> The http://wiki.eclipse.org/Pack200 compression is supported since java 1.5 by URLClassLoader.
> 
> The webapp configuration processing should be updated to look for *.jar.pack.gz as well as *.jar

**Comment by joakime** [comment]
Closing, as Pack200 has been removed from the JVM.
