### ISSUE TITLE
What happened to `jetty-webapp`

### ISSUE THREAD

**Issue by oliveryasuna** [eclipse/jetty.project#9802]
**Jetty version**

12

**Java version**

17

**Question**

We want to begin migration of our embedded Jetty server from 10 to 12 with Servlet 6. We have dependencies on `jetty-webapp` and `websocket-jakarta-server`. Neither have 12 beta versions in Maven Central. Could someone please provide insight into this?

Thank you!

- Oliver

**Comment by sbordet** [comment]
Because Jetty 12 can deploy multiple EE versions, `jetty-webapp` has become `jetty-ee8-webapp`, or `jetty-ee9-webapp`, or `jetty-ee10-webapp`, depending on the EE version you want to use.

Same for `websocket-jakarta-server` it has become `jetty-eeN-websocket-jakarta-server`.

**Comment by oliveryasuna** [comment]
@sbordet Thank you for clarifying. Do you know the replacement for `Resource#newResource(URL url, boolean useCaches)`? I know there is now `ResourceFactory`, but which ones replaced `PathResource`, `JarFileResource`,  `JarResource`, and `URLResource`?

**Comment by sbordet** [comment]
@lorban @joakime ^

**Comment by lorban** [comment]
You shouldn't have to bother yourself with `Resource` subclasses, the right one is chosen by  the different `ResourceFactory.newResource(...)` implementations. In your case, simply calling `ResourceFactory.newResource(URL url)` is what you're looking for.

The caching has been replaced with an explicit control of the lifecycle of the `ResourceFactory`. In its simplest form, you can use it this way:

```java
try (ResourceFactory factory = ResourceFactory.closeable()) {
  Resource res = factory.newResource(url);
  // use the resource here
}
```

but if you need the resource to stick around for later, you have to save the `ResourceFactory` somewhere and close it manually after you have no use for its `Resource`s anymore.

Makes sense?

**Comment by oliveryasuna** [comment]
@lorban Makes sense, thank you. Unfortunately, this doesn't work for me. I used `Resource.newResource` to support finding the resource `src/main/webapp` when running from IDE or in JAR. I have the directory defined in Maven resources and we find the directory by first finding a file named `.root` in it. I tried your code:

```
private static Resource findWebappRoot() throws MalformedURLException {
    final URL rootUrl = App.class.getResource("/webapp/.root");

    if(rootUrl == null) {
        throw new IllegalStateException("Unable to find webapp root file.");
    }

    final String rootUrlString = rootUrl.toString();

    if(!rootUrlString.endsWith("/.root")) {
        throw new IllegalStateException("Unexpected webapp root file URL: " + rootUrlString);
    }

    logger.info("Found webapp root file: {}", rootUrlString);

    final URL webappRootUrl = new URL(rootUrlString.substring(0, rootUrlString.length() - 5));

    logger.info("Found webapp root URL: {}", webappRootUrl);

    try(final ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {
        return resourceFactory.newResource(webappRootUrl);
    }
}
```

It works from IDE, but in JAR:

```
Exception in thread "main" java.nio.file.ClosedFileSystemException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1628)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.checkAccess(ZipFileSystem.java:560)
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.checkAccess(ZipPath.java:892)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:172)
        at java.base/java.nio.file.Files.isAccessible(Files.java:2597)
        at java.base/java.nio.file.Files.isReadable(Files.java:2632)
        at org.eclipse.jetty.util.resource.PathResource.isReadable(PathResource.java:307)
        at org.eclipse.jetty.util.resource.Resources.isReadable(Resources.java:68)
        at org.eclipse.jetty.server.handler.ContextHandler.setBaseResource(ContextHandler.java:902)
        at com.quickstep.App.initializeContext(App.java:75)
        at com.quickstep.App.main(App.java:40)
```

**EDIT:**

Okay, you'll notice the stupid mistake I made. Changed to `return ResourceFactory.root().newResource(webappRootUrl);` and it works.

**Comment by lorban** [comment]
Good that you noticed you own mistake. :+1: 

But beware: I don't think you should use `ResourceFactory.root()` as this factory makes no effort to release the resources at any time and _will leak them_. In the case of file-on-the-filesystem backed resources, there's nothing to release so it's fine but in the case of file-in-a-jar resources the JAR file needs to be closed at some point otherwise you get a memory as well as a file descriptor leak.

You should consider managing the lifecycle of the `ResourceFactory` according to the required availability of the resources.

Since you are using a `ContextHandler`, you could bind the lifecycle of the `ResourceFactory` to the one of the `ContextHandler` so that all JAR files get closed when the context gets stopped. You can use `ResourceFactory.of(Container container)` in this case as that will return a `ResourceFactory` bound to the lifecycle of the passed `Container`, and since pretty much all objects that can be registered in the Jetty server are `Container`s, `ContextHandler` being no exception.

I hope this helps.

**Comment by janbartel** [comment]
Seems this has been satisfactorily dealt with. If not, please reopen with more info.
