### ISSUE TITLE
Jetty JDK17 compatibility

### ISSUE THREAD

**Issue by neilmshah** [eclipse/jetty.project#9876]
Hello,

I'm running Jetty v9.4.48.v20220622 and I'd like to know if I can compile this on JDK8 and run it on a JDK17 environment? 

I know JDK17 support was introduced started jetty 10.x but I was wondering if 9.x had runtime support for JDK17?

Thank you.

**Comment by joakime** [comment]
Jetty 9.x is now at End of Community Support.

* #7958 

At this point in time you should be using Jetty 10, Jetty 11, or Jetty 12.
