### ISSUE TITLE
InputStreamResponseListener.get() throws with HTTP/2 following redirect

### ISSUE THREAD

**Issue by johngmyers** [eclipse/jetty.project#989]
Jetty 9.3.12
I have a test case which:
- Sets up an HTTP/2 (plaintext) Jetty server with two resources. One returns 302 redirecting to the other; the other returns 200.
- Creates an HTTP/2 Jetty client.
- The client creates a request to GET the first resource, with followRedirects set to true.
- The client sends the request, providing an `InputStreamResponseListener`.
- The client calls `listener.get(long, TimeUnit)`.

The `listener.get()` call throws an `ExecutionException` with a `null` cause.

This appears to be because `InputStreamResponseListener.onComplete(Result)` is being called with a Result containing the 302 response.

**Comment by sbordet** [comment]
I just added a test case for this, and it passes cleanly, see https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientStreamTest.java#L1168.

Is your case always reproducible ? Can you please detail how your case is different from the test case above ?

**Comment by sbordet** [comment]
@johngmyers news about this ?

**Comment by johngmyers** [comment]
I hope to be able to investigate more in a week or two. I'm currently buried by a different project.

**Comment by johngmyers** [comment]
Bug disappears after upgrading to 9.3.13.M0.

**Comment by sbordet** [comment]
Thanks for the feedback, glad it's solved for you.
