### ISSUE TITLE
Support for keystores that do not require an input stream

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#99]
migrated from Bugzilla [#381368](https://bugs.eclipse.org/bugs/show_bug.cgi?id=381368)
status ASSIGNED severity _enhancement_ in component _server_ for _9.3.x_
Reported in version _unspecified_ on platform _All_
Assigned to: Greg Wilkins

On 2012-06-01 09:04:18 -0400, Bruno Harbulot wrote:

> Build Identifier: 
> 
> This is a follow up of http://jira.codehaus.org/browse/JETTY-456
> 
> Having a quick look at org.eclipse.jetty.util.security.CertificateUtils [1] used by SslContextFactory, it seems it's not able to load a keystore that doesn't depend on a file or input stream, such as PKCS# 11 tokens or Apple's KeychainStore.
> 
> The JSSE Reference Guide [2] uses "NONE" as a special file name for these (although another configuration option might be to try to load the keystore if the path is null). "NONE" is the JSSE default, and it's unlikely that anyone would use it as an actual file name.
> 
> In these cases, the InputStream passed to load() should be null (the actual configuration is done either via the provider name or via the keystore type).
> 
> [1] http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-util/src/main/java/org/eclipse/jetty/util/security/CertificateUtils.java
> [2] http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html#Customization
> 
> Reproducible: Always

**Comment by gregw** [comment]
closed as some work has been done on this area and we need a concrete example before making any further changes.  Please comment or reopen if you have such an example
