### ISSUE TITLE
Improve `Request.getBeginNanoTime()` accuracy

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9900]
**Jetty version(s)**
12

**Enhancement Description**
It currently is very inaccurate for H2, H3, ~~FCGI~~, and when upgrades happen.

See #8885 for when `Request.getBeginNanoTime()` was introduced.

This and `Request.getBeginNanoTime()` should be backported to 10/11 to ease comparing performance across Jetty versions accurately.

**Comment by sbordet** [comment]
Fixed and backported to 10/11.
