### ISSUE TITLE
Change WOFF MIME type from `application/font-woff` to `font/woff`

### ISSUE THREAD

**Issue by basil** [eclipse/jetty.project#9913]
Jetty's current MIME type configuration in `mime.properties` uses:

```
woff=application/font-woff
woff2=font/woff2
```

As of February 2017, [RFC8081](https://www.rfc-editor.org/rfc/rfc8081#section-4.4.5) is the standard. It defines a top-level media type for fonts:

> Deprecated Alias: The existing registration `application/font-woff` is deprecated in favor of `font/woff`.

That is, the canonical MIME types now are:

```
woff=font/woff
woff2=font/woff2
```

[Apache httpd](https://github.com/apache/httpd/blob/992bb03650fdc72e736d2d722f3b114cd3518bc8/docs/conf/mime.types) and [Nginx](https://github.com/nginx/nginx/blob/6af8fe9cc44dbef43af4db5ea09d54ebd4aadbc5/conf/mime.types), as well as the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), all follow this new convention.

The change is trivial:

```
diff --git a/jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties b/jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties
index f689e3c239..5d2cb60aa1 100644
--- a/jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties
+++ b/jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties
@@ -178,7 +178,7 @@ wml=text/vnd.wap.wml
 wmlc=application/vnd.wap.wmlc
 wmls=text/vnd.wap.wmlscript
 wmlsc=application/vnd.wap.wmlscriptc
-woff=application/font-woff
+woff=font/woff
 woff2=font/woff2
 wrl=model/vrml
 wtls-ca-certificate=application/vnd.wap.wtls-ca-certificate
````

If this is desirable, let me know which branch and I will open a PR.

**Comment by janbartel** [comment]
@basil a PR against jetty-10 would be great.

**Comment by janbartel** [comment]
Thanks for the PR.
