### ISSUE TITLE
How to select client TLS certificate programmatically using jetty client connection 

### ISSUE THREAD

**Issue by techdeba901** [eclipse/jetty.project#9926]
**Jetty version**
11.0.11
**Java version**
17.0.7
**OS type/version**
Linux

Description
**Question**
In our Java application, we are reading multiple TLS certificates and using them to create the keystore and truststore files. Then we load those files into the JVM. Using that, we are creating a Jetty HttpClient over TLS and sending requests to servers. Is it possible to select a server-specific certificate while sending the request using Jetty HttpClient connections?

We have multiple servers with each server having different CARoot/CABundle, using jetty client is it possible to create a connection with servers by providing server specific TLS details?

For instance, if Server A has CARoot file a.pem and Server B has b.pem, in this case with one jetty client instance can we specify a.pem while establishing connection towards A and similarly b.pem while establishing connecting towards B. 

Thanks in advance.

**Comment by sbordet** [comment]
It is the server that chooses what certificate to send to the client.

The client can influence that decision via the server name indication (SNI) extension, typically (it may also use the application protocol, but that's typically very difficult to setup).

Your `HttpClient` should just make requests using different server names.
In your example, you make a request to `https://serverA/path` to hit server A, and `https://serverB/path` to hit server B.

The server will look at the SNI and pick the right certificate based on the certificate subject name (SAN), either the common name or an explicit SAN extension indication.

**Comment by sbordet** [comment]
Closing as answered.
