### ISSUE TITLE
Server doesn't always append a `Connection: close` header when responding during a shutdown

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9949]
**Jetty version(s)**
12

**Description**
`org.eclipse.jetty.server.StopTest.testWriteDuringShutdown()` uncovered this problem and is currently disabled.

**Comment by gregw** [comment]
The ABHandler is wrong.  It is doing two writes with last==true

**Comment by gregw** [comment]
I also think the test is wrong.  It was written assuming writing "a" would be buffered, but now we don't have a buffer, so it is committed on the first write.
Let me take this one.

**Comment by lorban** [comment]
I've re-enabled StopTest and slightly modified it in #9948. I've also modified `ABHandler` so that it doesn't do two writes with `last==true` but kept `testWriteDuringShutdown` disabled.
