### ISSUE TITLE
UrlEncoded.encodeString should skip more characters

### ISSUE THREAD

**Issue by CzBiX** [eclipse/jetty.project#995]
The UrlEncoded.encodeString should skip `*-._` chars that described in https://www.w3.org/TR/html5/forms.html#url-encoded-form-data

**Comment by joakime** [comment]
Current collected ABNF for the URI and URL encoding is actually documented at

https://tools.ietf.org/html/rfc3986#appendix-A

The w3.org reference you linked is listed as outdated.

The character `*` is part of the `sub-delims` group and should be skipped. but the characters `-._` are part of the `unreserved` group and have no meaning in the native or encoded form, they are recommended to be left alone (ie: left unencoded).

**Comment by sbordet** [comment]
There seems to be enough details to tackle this issue.

**Comment by lachlan-roberts** [comment]
Fixed with PR #4348.
