### ISSUE TITLE
Not able to create New Item

### ISSUE THREAD

**Issue by LeelaNandakishore** [eclipse/jetty.project#9951]
In Jenkins, the new item is not working properly
Can you pl
![2023-06-22](https://github.com/eclipse/jetty.project/assets/136099956/74057f96-e07a-47ec-8b75-daa7dc11ddcc)
ease look in to the issue

**Comment by olamy** [comment]
Hi 
This is a Jenkins question/issue and nothing related to Jetty.
Please contact the Jenkins community: https://www.jenkins.io/participate/
