### ISSUE TITLE
Race condition in HttpInput.setReadListener

### ISSUE THREAD

**Issue by pschorf** [eclipse/jetty.project#997]
Hi:

I think there is a race condition in the `setReadListener` method in HttpInput. The symptom I saw was the following error in AsyncContext.complete()

> 2016-10-11 10:29:02,273 WARN  org.eclipse.jetty.io.FillInterest [async-dispatch-2] - Read pending for org.eclipse.jetty.server.HttpConnection$AsyncReadCallback@1362538f prevented AC.ReadCB@621c4486{HttpConnection@621c4486[SelectChannelEndPoint@7afeb46d{/172.22.181.110:57425<->9091,Open,in,OSHUT,FI,-,0/200000,Htt    pConnection@621c4486}{io=1/1,kio=1,kro=1}][p=HttpParser{s=CLOSE,0 of 0},g=HttpGenerator@6d4ed974{s=START},c=HttpChannelOverHttp@a2f3d57{r=1,c=false,a=IDLE,uri=null}]}

I believe the following race is occurring for requests with Content-Length 0 and a ReadListener:

Thread 1:
1. HttpInput.setReadListener()
2. Acquire lock on `_inputQ`
3. HttpInput.nextContent()
4. HttpInput.pollContent()
5. _channelState.onReadReady()
6. HttpInput.wake()

Thread 2:
1. HttpChannel.run()
2. (Eventually) HttpChannelState.handling()
    \* This clears the `_asyncReaddUnready` flag and invokes the callback.
3. (Eventually) HttpInput.run()
4. Block on acquiring lock on `_inputQ`

Thread 1:
7. Return null from nextContent
8. _channelState.onReadUnready()
    \* This sets the `_asyncReadUnready` flag
9. Release lock on `_inputQ`
10. Return from HttpInput.setReadListener()

Thread 2:
5. Acquire lock on `_inputQ`
6. Release lock on `inputQ`
7. Invoke callback `onAllDataRead`
8. (Eventually) HttpChannelState.unhandle()
    \* `_asyncReadUnready` is now true
9. _channel.asyncReadFillInterested()

Now you are in a state where the callback believes it is finished, but when AsyncContext.complete() is called it will throw an exception due to the pending read. I believe this could be fixed by modifying HttpInput.wake() to pass a new Runnable which synchronizes on `_inputQ` before calling HttpChannel.run(). It has fixed my issue. I will be happy to provide a patch once I complete the CLA but I wanted to see if you knew of a better solution.

**Comment by gregw** [comment]
@pschorf I'm not entirely sure it is valid to call setReadListener from a thread other than the original one dispatched to the servlet.  You can get into all sorts of strange situations where one thread could try a blocking read and then another switch to async mode.

So to avoid the problem, call setReadListener in the same thread that calls startAsync before it returns or starts any async processing.

However, having said that, the spec doesn't actually say there are restrictions on when setReadListener should be called, so I would be interested in seeing your PR as if we can make the code more robust, that is always good.

**Comment by pschorf** [comment]
Sorry it wasn't very clear above (not that it's any clearer in my head) but "Thread 2" above is the thread launched by HttpInput.wake(), not a separate application thread. 

Also after thinking about it, a lighter weight solution could be to check that the state is not EOF/AEOF before calling _channelState.onReadUnready() in setReadListener(). I will test that out, and once my Eclipse account/CLA are situated I will open an MR.

**Comment by gregw** [comment]
@pschorf oh I see - well that's definitely in need of a fix.   We have some releases due very soon, so it would be great if you could move forward with a PR. Meanwhile I'm going to try to reproduce in a unit test.

**Comment by pschorf** [comment]
I filed a PR with the change (checking state instead of adding additional synchronization.) 
https://github.com/eclipse/jetty.project/pull/1008

**Comment by gregw** [comment]
@sbordet when you get a moment, can we hangout and discuss this issue.   I can't quiet bring myself to see how it is happening.   The fix looks reasonable except that I have lingering concerns about if/how/when/who calls allContentRead in this case.

**Comment by pschorf** [comment]
Let me know if you need any other information from me as well.

**Comment by gregw** [comment]
@pschorf it would be great if you could just double check your original description.  Specifically:
- thread 1 step 5 should be onReadUnready as there should be no content - we are at EOF?
- thread 1 step 6. cannot happen with the lock held on _inputQ as that is released first.

**Comment by pschorf** [comment]
In step 5 I was referring to the call in pollContent here: https://github.com/eclipse/jetty.project/blob/83f868e473908f6f46d425d6cdda1351a2505334/jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java#L250

The wake call in step 6 is right after that, assuming onReadReady returns true. At that point thread 1 should still be locking _inputQ

**Comment by pschorf** [comment]
Hi, just checking in to see if you had any more questions on this PR.

**Comment by gregw** [comment]
This just popped to the top of my todo stack again.... let's see if I can make some progress before something else pushes on top.... standby....

**Comment by gregw** [comment]
Ah thanks for the extra detail.... I see the wake inside the sync block being held now.  That doesn't look exactly right.

**Comment by gregw** [comment]
This is actually going to be a lot more complex that I thought, as we have spotted a few things that could be improved (like removing that wake call from inside a synchronized block!).

I think most of the changes are perhaps too radical for 9.3.x - even if they may not have any behavioural changes.

So currently I'm thinking that we look at your PR as a stop gap fix in 9.3 and then fix it properly in 9.4 branch.  @sbordet your thoughts on this approach?

**Comment by pschorf** [comment]
I had actually tried to move the wake call, but ended up breaking a good number of the Jetty integration tests so decided to back off. :) Not a great change for my first PR.

I agree that there are probably better ways to improve it, but this fixed my issue without seeming to cause any downstream changes.

**Comment by gregw** [comment]
@pschorf I think we have fixed this properly for the soon to be released 9.4.0 (See #1074).   Are you able to try that (RC out in the next few days).

I don't think we will backport to 9.3 as there are behaviour changes....  Still thinking about if we commit your PR or not.

**Comment by pschorf** [comment]
Yes, I'd be happy to test it. I have had a separate issue that I haven't been able to debug fully which only occurs when I am streaming input, hopefully your PR will fix that as well. Let me know when the RC is available.

**Comment by pschorf** [comment]
Any update on the RC?

**Comment by WalkerWatch** [comment]
@pschorf 9.4.0.RC2 was released late last week.
This release is available to download from the [Maven Central repository](http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.0.RC2/):

**Comment by baldersheim** [comment]
@pschorf Did you verify that this one was fixed ?

**Comment by pschorf** [comment]
Yes, we've been running off Jetty releases since 9.4 came out and off my hacked local build :)
