### ISSUE TITLE
Dose class ProduceExecuteConsume take wrong InvocationType

### ISSUE THREAD

**Issue by Bitros** [eclipse/jetty.project#9976]
- Source File

jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/ProduceExecuteConsume.java

- Question
```           
            // Execute the task.
            if (Invocable.getInvocationType(task) == InvocationType.NON_BLOCKING)
                task.run();
            else
                _executor.execute(task);
```

It takes InvocationType.NON_BLOCKING but runs the task in blocking way. Is that a typo?

**Comment by sbordet** [comment]
It is not a typo, the code is correct.

**Comment by Bitros** [comment]
Thanks for you reply. Understood finally. It is used to indicate the blocking status of task not the execution way.
