### ISSUE TITLE
SSL with KeystoreType Windows-MY or Windows-ROOT not working?

### ISSUE THREAD

**Issue by AlBundy33** [eclipse/jetty.project#9977]
**Jetty version(s)**
all?
tested with 9.4.51.v20230217 and 11.0.15

**Java version/vendor** `(use: java -version)`
tested with
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

and

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

**OS type/version**
Windows 10

**Description**
SSL does not work with KeystoreType Windows-My or Windows-Root

**How to reproduce?**

create JettySSL.java with this content
```
package sandbox;

import java.util.logging.Level;
import java.util.logging.Logger;

import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.server.HttpConfiguration;
import org.eclipse.jetty.server.HttpConnectionFactory;
import org.eclipse.jetty.server.SecureRequestCustomizer;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.SslConnectionFactory;
import org.eclipse.jetty.util.ssl.SslContextFactory;

public class JettySSL
{
  public static void main(String[] args) throws Exception
  {
    Server server = new Server();

    ServerConnector connector = new ServerConnector(server);
    connector.setPort(10080);

    HttpConfiguration https = new HttpConfiguration();
    https.addCustomizer(new SecureRequestCustomizer());

    // create certificate in powershell with
    // New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\CurrentUser\My
    // and export certificate to pfx with
    // Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object Subject -Match "CN=localhost" | Export-PfxCertificate -FilePath localhost.pfx -Password (ConvertTo-SecureString -String '123456' -Force -AsPlainText)
    SslContextFactory.Server sslContextFactoryWindows = new SslContextFactory.Server();
    sslContextFactoryWindows.setKeyStoreType("Windows-MY");
    ServerConnector sslWindows = new ServerConnector(server,
        new SslConnectionFactory(sslContextFactoryWindows, "http/1.1"),
        new HttpConnectionFactory(https));
    sslWindows.setPort(10443);

    SslContextFactory.Server sslContextFactoryFile = new SslContextFactory.Server();
    sslContextFactoryFile.setKeyStoreType("PKCS12");
    sslContextFactoryFile.setKeyStorePath(JettySSL.class.getResource("localhost.pfx").toExternalForm());
    sslContextFactoryFile.setKeyStorePassword("123456");
    sslContextFactoryFile.setKeyManagerPassword("123456");
    ServerConnector sslFile = new ServerConnector(server,
        new SslConnectionFactory(sslContextFactoryFile, "http/1.1"),
        new HttpConnectionFactory(https));
    sslFile.setPort(10444);

    server.setConnectors(new Connector[] { connector, sslWindows, sslFile });

    Logger.getGlobal().setLevel(Level.FINEST);
    Logger.getLogger("main").setLevel(Level.FINEST);
    
    server.start();
    server.join();
  }
}
```

create self signed certificate in powershell
```
New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\CurrentUser\My
```
and export certificate with
```
Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object Subject -Match "CN=localhost" | Export-PfxCertificate -FilePath localhost.pfx -Password (ConvertTo-SecureString -String '123456' -Force -AsPlainText)
```
localhost.pfx has to be in the same folder like JettySSL.class

Now start JettySSL

If you open https://localhost:10443/ (KeystoreType=Windows-MY) in your browser (Google Chrome in my case) the browser shows only a ERR_SSL_PROTOCOL_ERROR (OpenJDK) ERR_SSL_VERSION_OR_CIPHER_MISMATCH (Oracle Java)

If you open https://localhost:10444/ (KeystoreType=PKCS12) in your browser you'll get the usual warning because of the unknown certificate (so this would work in a real-life scenario)

If you create a jetty-loggin.properties in your classpath-root with this content
```
org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog
org.eclipse.jetty.LEVEL=ALL
```
you'll see an exception
OpenJDK
```
javax.net.ssl.SSLHandshakeException: No available authentication scheme
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:972)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:961)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1234)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1170)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:852)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:657)
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:265)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

On Oracle Java with Jetty 9.x you'll also get an SSLHandshakeException but with the message: `no cipher suites in common`

**Comment by joakime** [comment]
The keystore types `Windows-MY` and `Windows-ROOT` are insufficient keystore names (or at least not valid until you use a version of Java that supports those short names).

See https://bugs.openjdk.org/browse/JDK-6782021

**Comment by AlBundy33** [comment]
but the mentioned snippet works also with OpenJDK 8
```
 KeyStore ks = KeyStore.getInstance("Windows-MY");
      ks.load(null, null);
      Enumeration<String> en = ks.aliases();

      while (en.hasMoreElements())
      {
        String aliasKey = (String) en.nextElement();
        X509Certificate c = (X509Certificate) ks.getCertificate(aliasKey);
        System.out.println("---> alias : " + aliasKey);
        System.out.println(" Certificat subjectDN : " + c.getSubjectDN());
        System.out.println(" Certificat issuerDN : " + c.getIssuerDN());
      }
```

and even with
```
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)
```
(according to the page there was a backport to 11.0.18)
I still don't get a successfull connection.

**Comment by joakime** [comment]
```
javax.net.ssl.SSLHandshakeException: No available authentication scheme
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:972)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:961)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1234)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1170)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:852)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
```

Looks like TLS 1.3 was used (based on the class names).

Oracle JDK 8 ... 
 * doesn't have TLS 1.3
 * supports vulnerable cipher suites (that are no longer supported on newer JDKs)
 * supports vulnerable certificate algorithms (that are no longer supported on newer JDKs)

Example, if your certificate is DSA based, you will have no support on newer JDKs. (You would have to update your certificate to be RSA or ECA based)

**Comment by AlBundy33** [comment]
Oracle JDK 8 was only for testing :-)
even with lates OpenJDK 11 I don't get a ssl-connection

It seems that the default for generated keys is RSA.
I've also tried `New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\CurrentUser\My -Subject localhost -KeyAlgorithm ECDSA_nistP256` without luck :-(

If I add this to my test-class
```
    KeyStore keystore = KeyStore.getInstance(sslContextFactoryWindows.getKeyStoreType());
    keystore.load(null, null);
    KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
    kmf.init(keystore, null);
    SSLContext sslContext = SSLContext.getInstance("TLS");
    sslContext.init(kmf.getKeyManagers(), null, null);
    sslContextFactoryWindows.setSslContext(sslContext);
```
I get a succesful ssl-connection but I'm not sure if the code is correct and works in all cases (e.g. missing trust-manager or SecureRandom or "fixed" TLS-context, ...)

I would prefer a configure-windows-my-and-you-are-done-solution :-)

**Comment by joakime** [comment]
@sbordet thoughts? --^

**Comment by sbordet** [comment]
@AlBundy33 `No available authentication scheme` typically means a problem in your certificate, usually a DSA one, which is not supported in TLS 1.3.

I would compare the 2 KeyStores you have, Windows-My versus PKCS12, and see where they differ.
Stick with `RSA` for now and avoid the fancier `ECDSA_nistP256`.

I think it's only an issue of creating the proper Windows-My KeyStore.

I don't think it's a Jetty issue at all, just a misconfiguration of the Windows-My KeyStore.

**Comment by AlBundy33** [comment]
But with the mentioned code the same certificate works. 🤔 
I could try to re-import the certificate.

The mentioned exception was only the first logged stacktrace - not sure if this is really the cause.

We are usually using pkcs12 but using Windows-MY or Windows-ROOT  would have the advantage that customers could manage them by themselves.

**Comment by sbordet** [comment]
Sorry, it is not clear what precisely the "mentioned code" is.

You said that connecting to 10443 with `Windows-MY` throws, while 10444 works.

**Comment by AlBundy33** [comment]
thats right - I've created both certificates in powershell (create the cert and export to pfx).
-> see comments for commamds
exported pfx works but keystoretype = windows-my works only if I load the keystore manually.

```
public class JettySSL
{
  public static void main(String[] args) throws Exception
  {
    Server server = new Server();

    ServerConnector connector = new ServerConnector(server);
    connector.setPort(10080);

    HttpConfiguration https = new HttpConfiguration();
    https.addCustomizer(new SecureRequestCustomizer());

    // create certificate in powershell with
    // New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\CurrentUser\My
    // and export certificate to pfx with
    // Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object Subject -Match "CN=localhost" | Export-PfxCertificate -FilePath localhost.pfx -Password (ConvertTo-SecureString -String '123456' -Force -AsPlainText)
    SslContextFactory.Server sslContextFactoryWindows = new SslContextFactory.Server();
    sslContextFactoryWindows.setKeyStoreType("Windows-MY");

    // this is the additional where I manually load windows-my into a keystore
    KeyStore keystore = KeyStore.getInstance(sslContextFactoryWindows.getKeyStoreType());
    keystore.load(null, null);
    KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
    kmf.init(keystore, null);
    SSLContext sslContext = SSLContext.getInstance("TLS");
    sslContext.init(kmf.getKeyManagers(), null, null);
    sslContextFactoryWindows.setSslContext(sslContext);

    ServerConnector sslWindows = new ServerConnector(server,
        new SslConnectionFactory(sslContextFactoryWindows, "http/1.1"),
        new HttpConnectionFactory(https));
    sslWindows.setPort(10443);

    SslContextFactory.Server sslContextFactoryFile = new SslContextFactory.Server();
    sslContextFactoryFile.setKeyStoreType("PKCS12");
    sslContextFactoryFile.setKeyStorePath(JettySSL.class.getResource("localhost.pfx").toExternalForm());
    sslContextFactoryFile.setKeyStorePassword("123456");
    sslContextFactoryFile.setKeyManagerPassword("123456");
    ServerConnector sslFile = new ServerConnector(server,
        new SslConnectionFactory(sslContextFactoryFile, "http/1.1"),
        new HttpConnectionFactory(https));
    sslFile.setPort(10444);

    server.setConnectors(new Connector[] { connector, sslWindows, sslFile });

    Logger.getGlobal().setLevel(Level.FINEST);
    Logger.getLogger("main").setLevel(Level.FINEST);
    
    server.start();
    server.join();
  }
}
```

**Comment by sbordet** [comment]
I don't have Windows, so I have no idea what storing a file to `Cert:\CurrentUser\My` (is that what the command does?) has to do with setting the KeyStore type to `Windows-MY`.

Are you sure about this step?

Because otherwise you are creating something in a place, but load something else from another place.

**Comment by AlBundy33** [comment]
CurrentUser\My and LocalMachine\My are "Paths" to the windows integrated certificate management.
https://medium.com/the-new-control-plane/generating-self-signed-certificates-on-windows-7812a600c2d8

Windows-MY and Windows-ROOT are special Names to access this certificate stores.

**Comment by sbordet** [comment]
Turn on `-Djavax.net.debug=all` and look at the output. 
It should print what KeyStore is opened, what certificate is sent to the client, and eventually why it fails.

**Comment by AlBundy33** [comment]
I hate `-Djavax.net.debug=all` 😄 

But I tried to debug my test-project and now I've found the issue and a workaround.

The problem is in SslContextFactory#load
there is this check
```
            if (keyStore == null && _keyStoreResource == null && trustStore == null && _trustStoreResource == null)
```

And if your are using "Windows-MY" or "Windows-ROOT" all this variables are null (because that are no actual files) and therefore no keystore is loaded.

But If I call `SSLContextFactory#setKeystorePath` with a path to an existing empty file it seems to work.

A fix for this issue would by to modify the check to something like this
```
            if (keyStore == null && _keyStoreResource == null && trustStore == null && _trustStoreResource == null
              && !"Windows-MY".equalsIgnoreCase(getKeyStoreType()) && !"Windows-ROOT".equalsIgnoreCase(getKeyStoreType()))
```

This is the working version of my example:
```
public class JettySSL
{
  public static void main(String[] args) throws Exception
  {
    Server server = new Server();

    ServerConnector connector = new ServerConnector(server);
    connector.setPort(10080);
    server.addConnector(connector);

    // create certificate in powershell with
    // New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\CurrentUser\My
    // and export certificate to pfx with
    // Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object Subject -Match "CN=localhost" | Export-PfxCertificate -FilePath localhost.pfx -Password (ConvertTo-SecureString -String '123456' -Force -AsPlainText)
    SslContextFactory.Server sslContextFactoryWindows = new SslContextFactory.Server();
    sslContextFactoryWindows.setKeyStoreType("Windows-MY");
    
    // this is the workaround
    final File emptyFile = File.createTempFile("jettydummy_", ".tmp");
    emptyFile.deleteOnExit();
    sslContextFactoryWindows.setKeyStorePath(emptyFile.getAbsolutePath());

    HttpConfiguration https = new HttpConfiguration();
    https.addCustomizer(new SecureRequestCustomizer());
    
    ServerConnector sslWindows = new ServerConnector(server,
        new SslConnectionFactory(sslContextFactoryWindows, "http/1.1"),
        new HttpConnectionFactory(https));
    sslWindows.setPort(10443);
    server.addConnector(sslWindows);

    SslContextFactory.Server sslContextFactoryFile = new SslContextFactory.Server();
    sslContextFactoryFile.setKeyStoreType("PKCS12");
    sslContextFactoryFile.setKeyStorePath(JettySSL.class.getResource("localhost.pfx").toExternalForm());
    sslContextFactoryFile.setKeyStorePassword("123456");
    sslContextFactoryFile.setKeyManagerPassword("123456");
    ServerConnector sslFile = new ServerConnector(server,
        new SslConnectionFactory(sslContextFactoryFile, "http/1.1"),
        new HttpConnectionFactory(https));
    sslFile.setPort(10444);
    server.addConnector(sslFile);

    server.start();
    server.join();
  }
}
```

**Comment by joakime** [comment]
> And if your are using "Windows-MY" or "Windows-ROOT" all this variables are null (because that are no actual files) and therefore no keystore is loaded.
> 
> But If I call `SSLContextFactory#setKeystorePath` with a path to an existing empty file it seems to work.
> 
> A fix for this issue would by to modify the check to something like this
> 
> ```
>             if (keyStore == null && _keyStoreResource == null && trustStore == null && _trustStoreResource == null
>               && !"Windows-MY".equalsIgnoreCase(getKeyStoreType()) && !"Windows-ROOT".equalsIgnoreCase(getKeyStoreType()))
> ```

Not sufficient.
For example, the keywords you are using (`Windows-My` and `Windows-ROOT`) are now considered deprecated. (follow the discussion on https://bugs.openjdk.org/browse/JDK-6782021 and links to other issues and you'll see that)
One of the initial commits for that bug adds more keywords to the JVM for your setup to work around bugs that the original keywords have, see https://github.com/openjdk/jdk11u-dev/commit/f75b74d19e84ac802913d3ee8ba033663b0f17ae (there are more added later)
You should consider using one of the new keywords btw, to be clear about the origin/scope of the virtual keystore: local machine vs current user.
Hard coding keywords in the SslContextFactory.load() to indicate "virtual keystore" is not a good solution in the long run (there are many virtual keystore concepts out there).

Since you are not using a physical keystore, but a virtual one, you should tell the SslContextFactory that by setting the keyStore.

When dealing with a virtual keystore, you have to init/load the java.security.KeyStore yourself and tell SslContextFactory of it.

``` java
String keystoreProvider = "SunMSCAPI";
String keystoreType = "Windows-MY"; // TODO: use non-deprecated type name
String secureRandomAlgo = "Windows-PRNG";
SslContextFactory.Server sslContextFactoryWindows = new SslContextFactory.Server();
sslContextFactoryWindows.setKeyStoreType(keystoreType); 
sslContextFactoryWindows.setKeyStoreProvider(keystoreProvider); // Optional: normally used to synchronize other aspects of Java Security with same provider (eg: truststore, trustmanager, sslcontext, sslengine, supportedprotocols, supportedciphersuites, etc)
KeyStore keyStore = KeyStore.getInstance(keystoreType, keystoreProvider);
keyStore.load(null); // TODO: figure out password access requirements of SunMSCAPI provider and Windows-* types (interactive prompts can be required)
sslContextFactoryWindows.setKeyStore(keyStore);
sslContextFactoryWindows.setSecureRandomAlgorithm(secureRandomAlgo);

/// ... other setup ...
ServerConnector sslWindows = new ServerConnector(server,
    new SslConnectionFactory(sslContextFactoryWindows, "http/1.1"),
    new HttpConnectionFactory(https));
```

Note: when using the SunMSCAPI you are limited to only using Cipher Suites that are RSA based (RSA/ECB/PKCS1Padding only), no other algorithms are supported when using that provider (see documentation on the SunMSCAPI provider).
If you follow the discussion on the bug https://bugs.openjdk.org/browse/JDK-6782021 you'll see developers wondering if the SunMSCAPI still has a place, as the RSA algorithm is constantly under attack and the scope of what's considered safe and non-vulnerable is vanishingly small, there's a real possibility that SunMSCAPI might be deprecated as insecure in the near future unless Microsoft decides to support more robust and safer algorithms.
A real scenario is that the rest of the internet decides that RSA based Cipher Suites are no longer secure and support for it gets dropped in browsers / user-agents / clients / and mobile devices, making them unable to connect to your SunMSCAPI based server.

**Comment by AlBundy33** [comment]
@joakime thank you very much you your answer but wouldn't it be better to support already in java integrated "virtual keystores" out of the box?
I totally understand, that hardcoding names is not the best solution but loading the keystore on start needs - in my opinion - a lot of knowledge of jetty-internals.

For example to use the windows certificate manager as trust-store in (plain-)java I only add `-Djavax.net.ssl.trustStoreType=Windows-ROOT` and I'm done.
From this time on every https-connection validates the certicates agains the certificates in the windows-certificate-manager.


You example by loading the keystore by myself works but when using the "virtual-windows-keystores" it would be better to trust the jetty-developers. 😄 

For example: is `SunMSCAPI` always the correct provider or is `Windows-PRNG` the correct algo?

Your fix works slightly other than my one with the empty-file because SSLContextFactory#load calls
```
                if (trustStore == null)
                    trustStore = loadTrustStore(_trustStoreResource);
````
where `loadTrustStore` has a fallback to the keystore-values and in this case `CertificateUtils#getKeyStore` would return null because `resource` is still null.
I know, that I could call
```
sslContextFactoryWindows.setKeyStore(keyStore);
sslContextFactoryWindows.setTrustStore(keyStore);
```
But I don't know if there are more differences.
-> At least for now the empty-file-workaround seems to be the better one.

Don't you think that keystore-types that are starting with "windows-" should be also supported even if there is no path/resource configured (because they are integrated in java itself)?
If you don't want to add a check like `...toLowerCase().startsWith("windows-")` what would you think about a `SSLContextFactory#setIsVirtualKeystore(boolean)`?
So users could mark the keystore from "outside" as virtual.
-> I still would prefer an integrated solution of (java-)integrated virtual keystores. 😄 

Regarding Windows-MY, Windows-ROOT and the new names:
I don't rely on the deprecated names - they are configurable, so I can switch to the new ones.
I just use them because I did not know the new ones and because they are working in all java-versions (at least vor now). 😄

**Comment by joakime** [comment]
A KeyStore in SslContextFactory can come from 2 techniques.

1. Internal - a keystore file, well documented, and the overwhelming standard.
2. External - a `java.security.KeyStore` that is provided to the SslContextFactory.

The "virtual keystore" comes from the external category.
This is because that kind of keystore has too many varied initialization techniques to standardize within the SslContextFactory.
Your use case is incredibly rare.  Windows + SunMSCAPI + USER Based Scope + No authentication on Keystore + No Windows Domain security + (the myriad of other rules on the use of the SunMSCAPI provider that come from both Java and Windows).
That kind of variation cannot be standardized within the SslContextFactory, it has to be an externally provide KeyStore to the SslContextFactory.

If you want to use a custom TrustStore (not the Java default), then that applies there as well.

The Provider `SunMSCAPI` can provide a SecureRandom implementation, but you have to specify its use, otherwise the Java default is used (which has a different type/name).
Read the documentation on `SunMSCAPI` and you'll discover all of this yourself.

At this point, i'm closing this issue, as it's not an Jetty issue, nor is it possible to add a code to support this use case in a generic way.

**Comment by sbordet** [comment]
I was about to implement something similar to what suggested by @AlBundy33, and went along quite far trying to make it generic, etc. but @joakime is right that we will be going down a slippery slope to support these "virtual" KeyStores.

The best option, and it's only a few lines, is for applications to create the `KeyStore` instance and pass it explicitly to `SslContextFactory`, as @joakime suggested.

We should really document this though.
I opened #9987 about.
