### ISSUE TITLE
Add format option to CustomRequestLog for request authority and request authority scheme

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9980]
**Jetty version(s)**
10

**Enhancement Description**
The `CustomRequestLog` lacks the ability to output:

* the Request authority (which might differ from the Host header).
* the Request scheme
* the entire Request HttpURI (including query)
* the entire Request HttpURI (excluding query)

**Comment by ofrias** [comment]
Please don't close, I think this would be helpful...
