### ISSUE TITLE
URLResource.isDirectory() throws a NullPointerException when created from a jar:file: URL

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/jetty.project#9984]
**Jetty version(s)**
12.0.0.Beta2

**Java version/vendor** `(use: java -version)`
```
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)
```
**OS type/version**
macOS 13.4

**Description**
`URI.getPath()` can return `null` but `URLResourceFactory.URLResource.isDirectory()` assumes that it will not. This can result in a `NullPointerException`.

**How to reproduce?**

```java
new URLResourceFactory().newResource(new URL("jar:file:/example.jar!/")).isDirectory();
```

**Comment by lorban** [comment]
You're right that this `NullPointerException` should not happen, so I've created a PR to fix this: https://github.com/eclipse/jetty.project/pull/9985

But this looks like you're abusing the `URLResourceFactory` as it wasn't designed to handle `file` nor `jar:file:` URIs. Its only intended purpose is to be able to register a `ResourceFactory` handling HTTP or HTTPS schemes like so:

```java
ResourceFactory.registerResourceFactory("https", new URLResourceFactory());
```

Using it for any other purpose sounds like abuse and makes me wonder what you're trying to achieve that cannot be done with the official `ResourceFactory` mechanism.

**Comment by joakime** [comment]
@lorban see issue #9973 for origin of this use

**Comment by wilkinsona** [comment]
Thanks, both. Just to provide a summary of the background, as a (possibly intermediate) step I am trying to get things working with Jetty 12 [as they did with Resource.newResource(String) in Jetty 11](https://github.com/spring-projects/spring-boot/blob/2390c6c1b9d3872b14f6b2aa2eb2598d9b86160f/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/JettyServletWebServerFactory.java#L325). Until we have `FileSystem` support in Spring Boot's fat jars, the goal is to use a `URL` with our custom `Handler` for `jar:file:` URLs as Jetty 11 allowed.

**Comment by lorban** [comment]
I don't think `URLResourceFactory` is advanced enough to usefully handle `jar:file` URLs, and making it this capable sounds overkill as it would basically require duplicating `MountedPathResource` and its integration with `FileSystemPool`.

What kind of magic is your custom `URLStreamHandler` doing? Maybe that could be achieved another way?

**Comment by wilkinsona** [comment]
> What kind of magic is your custom URLStreamHandler doing? Maybe that could be achieved another way?

It's a cornerstone of Spring Boot's [executable jar support](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#appendix.executable-jar). I don't think it can be achieved in another way as a custom `Handler` is essential for compatibility with existing code that uses `jar:` URLs.

**Comment by lorban** [comment]
I'd like to understand better Spring Boot's executable jar support to try to figure out an elegant solution.

Barring that, `URLResourceFactory` will have fairly limited support: it is slow, isDirectory makes a guess, and there is no way to list sub-resources. Hopefully, if you have to resort to using that `ResourceFactory`, it's enough for your needs.
